### ISSUE TITLE
Update all usage @aws-sdk to newer version

### ISSUE THREAD

**Issue by TanjaBayer** [aws-amplify/amplify-js#10010]
### Is this related to another service?

@aws-sdk

### Describe the feature you'd like to request

Update @aws-sdk versions in all subprojects, the currently used version 3.6.1 are already a year old and have unnecessary dependencies which blow up a project, and in our case cause lambda deployments to exceed the available limit.

### Describe the solution you'd like

There was a merge request some time ago which already addresses this: https://github.com/aws-amplify/amplify-js/pull/9137 however this one is also already outdated. In general adding a bot for updating and checking if pipelines are still running might make sense for the future.

### Describe alternatives you've considered

As long as there is no need of having those specific versions I see no alternative, I would always recommend keeping dependencies up to date.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [x] ⚠️ This feature might incur a breaking change

**Comment by kachkaev** [comment]
Getting this warning with each `pnpm install`:

```
deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```

Result of `pnpm why uuid@3`

```
Legend: production dependency, optional only, dev only

dependencies:
@aws-amplify/api-graphql 3.2.0
├─┬ @aws-amplify/api-rest 3.1.0
│ └─┬ @aws-amplify/core 5.3.0
│   ├─┬ @aws-sdk/client-cloudwatch-logs 3.6.1
│   │ └─┬ @aws-sdk/middleware-retry 3.6.1
│   │   └── uuid 3.4.0
│   ├─┬ @aws-sdk/client-cognito-identity 3.6.1
│   │ └─┬ @aws-sdk/middleware-retry 3.6.1
│   │   └── uuid 3.4.0
│   └─┬ @aws-sdk/credential-provider-cognito-identity 3.6.1
│     └─┬ @aws-sdk/client-cognito-identity 3.6.1
│       └─┬ @aws-sdk/middleware-retry 3.6.1
│         └── uuid 3.4.0
├─┬ @aws-amplify/auth 5.3.6
│ └─┬ @aws-amplify/core 5.3.0
│   ├─┬ @aws-sdk/client-cloudwatch-logs 3.6.1
│   │ └─┬ @aws-sdk/middleware-retry 3.6.1
│   │   └── uuid 3.4.0
│   ├─┬ @aws-sdk/client-cognito-identity 3.6.1
│   │ └─┬ @aws-sdk/middleware-retry 3.6.1
│   │   └── uuid 3.4.0
│   └─┬ @aws-sdk/credential-provider-cognito-identity 3.6.1
│     └─┬ @aws-sdk/client-cognito-identity 3.6.1
│       └─┬ @aws-sdk/middleware-retry 3.6.1
│         └── uuid 3.4.0
├─┬ @aws-amplify/cache 5.0.32
│ └─┬ @aws-amplify/core 5.3.0
│   ├─┬ @aws-sdk/client-cloudwatch-logs 3.6.1
│   │ └─┬ @aws-sdk/middleware-retry 3.6.1
│   │   └── uuid 3.4.0
│   ├─┬ @aws-sdk/client-cognito-identity 3.6.1
│   │ └─┬ @aws-sdk/middleware-retry 3.6.1
│   │   └── uuid 3.4.0
│   └─┬ @aws-sdk/credential-provider-cognito-identity 3.6.1
│     └─┬ @aws-sdk/client-cognito-identity 3.6.1
│       └─┬ @aws-sdk/middleware-retry 3.6.1
│         └── uuid 3.4.0
├─┬ @aws-amplify/core 5.3.0
│ ├─┬ @aws-sdk/client-cloudwatch-logs 3.6.1
│ │ └─┬ @aws-sdk/middleware-retry 3.6.1
│ │   └── uuid 3.4.0
│ ├─┬ @aws-sdk/client-cognito-identity 3.6.1
│ │ └─┬ @aws-sdk/middleware-retry 3.6.1
...
```

It does not seem that there is a way of upgrading this transient dep. Hope to see `@aws-sdk/*` updated soon.

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
