### ISSUE TITLE
Installing Vue components also installs React-Native

### ISSUE THREAD

**Issue by armenr** [aws-amplify/amplify-js#10029]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Vue

### Which UI component?

Other

### How is your app built?

Vite

### Please describe your bug.

When installing `@aws-amplify/ui-vue` and `aws-amplify`, React Native appears to be getting installed as well.

```
❯ pnpm add @aws-amplify/ui-vue aws-amplify
Downloading registry.npmjs.org/react-native/0.69.0: 85.6 MB/85.6 MB, done

dependencies:
+ @aws-amplify/ui-vue 2.4.11
+ ajv 8.11.0
+ aws-amplify 4.3.26
+ react-native 0.69.0

```

### What's the expected behaviour?

When working with a pure Vue3 project, I'd expect not to have to have to eat ~90MB in overhead for React-Native.

### Help us reproduce the bug!

Scaffold any new project.

Then run: `pnpm add @aws-amplify/ui-vue aws-amplify`

### Code Snippet

```typescript
// Put your code below this line.

```

N/A

**Comment by janpapenbrock** [comment]
`@aws-amplify/core` also has a dependency on react-native with this path:

```
└─┬ @aws-amplify/core@4.5.9-unstable.6
  └─┬ @aws-sdk/client-cloudwatch-logs@3.6.1
    └─┬ @aws-sdk/middleware-retry@3.6.1
      └─┬ react-native-get-random-values@1.8.0
        └─┬ react-native@0.69.1
          └─┬ @react-native-community/cli@8.0.2
            └── react-native@0.69.1 deduped
```

The dependency on `react-native-get-random-values` was removed from `@aws-sdk/middleware-retry@3.12.0` in April 2021 in this commit: https://github.com/aws/aws-sdk-js-v3/commit/2d3a7f0b74e168b15711783c72f9bc301a48041e

So I assume that updating all `@aws-sdk` dependencies to at least `3.12.0` should resolve this issue.

**Comment by cwomack** [comment]
Hello, @armenr 👋.  This issue appears to be a duplicate and related to an existing Github issue (https://github.com/aws-amplify/amplify-js/issues/9119). I'll be closing this one to keep all information related to this behavior on a single stream to avoid any miscommunication. 
 
 Please feel free to add your comments to the linked issue from here.
