### ISSUE TITLE
Amplify API throws "Unauthorized" error when GraphQL-schema has different @auth rules for different types

### ISSUE THREAD

**Issue by axel-andersson** [aws-amplify/amplify-js#10024]
### Before opening, please confirm:

- [x] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React, Next.js

### Amplify APIs

Authentication, GraphQL API

### Amplify Categories

auth, api

### Environment information

<details>

```
  System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 19.21 GB / 31.93 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 7.21.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.37)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @aws-amplify/ui-react: ^3.0.2 => 3.0.2
    @aws-amplify/ui-react-internal:  undefined ()
    @aws-amplify/ui-react-legacy:  undefined ()
    @testing-library/jest-dom: ^5.16.4 => 5.16.4
    @testing-library/react: ^13.3.0 => 13.3.0
    @testing-library/user-event: ^13.5.0 => 13.5.0
    aws-amplify: ^4.3.26 => 4.3.26
    react: ^18.2.0 => 18.2.0 (18.0.0)
    react-dom: ^18.2.0 => 18.2.0
    react-scripts: 5.0.1 => 5.0.1
    web-vitals: ^2.1.4 => 2.1.4
  npmGlobalPackages:
    @aws-amplify/cli: 7.6.26
    npm: 7.21.1
    serve: 13.0.2

```

</details>

### Describe the bug

When querying data from a schema with a one-to-many relationship, where different @model types have different @auth rules, the query returns an Unauthorized error, even though the client meets the requirements to access each model on their own.

### Expected behavior

The requested data is returned when the user is authorized according to the @auth tags. 

### Reproduction steps

1. Create a new React app with `npx create-react-app connection-test`
2. Run `amplify init`
3. Run `amplify add api` and create a GraphQL-API. You can use the Blog example as a template.
4. Update the schema.graphql file so the types have different auth rules. In the blog example I put Blog as private and the others as public.
5. Run `amplify add auth` and configure it for username. (That is what I had in my original project, where this issue first appeared)
6. Run `amplify push`
7. Install the amplify and amplify-ui packages. `npm i @aws-amplify/ui-react aws-amplify`
8. Add authenthication to the react app
9. Run the listBlogs and listPosts-queries from the react app by using amplify's generated queries.
10. Log the responses and see that errors appear.

### Code Snippet

```
#schema.graphql
type Blog @model @auth(rules: [{ allow: private }]) {
  id: ID!
  name: String!
  posts: [Post] @hasMany
}

type Post @model @auth(rules: [{ allow: public }]) {
  id: ID!
  title: String!
  blog: Blog @belongsTo
  comments: [Comment] @hasMany
}

type Comment @model @auth(rules: [{ allow: public }]) {
  id: ID!
  post: Post @belongsTo 
  content: String!
}
 
```
```javascript
//App.js
import { Amplify, API, Auth } from 'aws-amplify';

import { Authenticator } from '@aws-amplify/ui-react'
import awsconfig from './aws-exports';
import { useEffect } from 'react';
import { listBlogs, listPosts } from './graphql/queries';
Amplify.configure(awsconfig);

function App() {

  return (
    <Authenticator>
      {({ signOut }) => (
        <Content onSignOut={signOut} />
      )}
    </Authenticator>
  );
}

export default App;


function Content({ onSignOut }) {

  useEffect(() => {

    Auth.currentAuthenticatedUser().then(
      () => {
        fetchData()
      },
      error => {
        console.error(error)
      }
    )

  }, [])

  return (
    <button onClick={onSignOut}>Sign out</button>
  )

}


async function fetchData() {
  try {
    const res = await API.graphql({ query: listBlogs })
    console.log("blogs", res)

  } catch (error) {
    console.error("blogs error", error)
  }

  try {
    const res = await API.graphql({ query: listPosts })
    console.log("posts", res)

  } catch (error) {
    console.error("posts error", error)
  }
}
````

### Log output

<details>

```
//error thrown by API.graphql({ query: listBlogs })
{
    "data": {
        "listBlogs": null
    },
    "errors": [
        {
            "path": [
                "listBlogs"
            ],
            "data": null,
            "errorType": "Unauthorized",
            "errorInfo": null,
            "locations": [
                {
                    "line": 2,
                    "column": 3,
                    "sourceName": null
                }
            ],
            "message": "Not Authorized to access listBlogs on type Query"
        }
    ]
}

//error thrown by API.graphql({ query: listPosts })

{
    "data": {
        "listPosts": null
    },
    "errors": [
        {
            "path": [
                "listPosts",
                "items"
            ],
            "data": null,
            "errorType": "Unauthorized",
            "errorInfo": null,
            "locations": [
                {
                    "line": 3,
                    "column": 5,
                    "sourceName": null
                }
            ],
            "message": "Not Authorized to access items on type ModelPostConnection"
        },
        {
            "path": [
                "listPosts",
                "nextToken"
            ],
            "data": null,
            "errorType": "Unauthorized",
            "errorInfo": null,
            "locations": [
                {
                    "line": 19,
                    "column": 5,
                    "sourceName": null
                }
            ],
            "message": "Not Authorized to access nextToken on type ModelPostConnection"
        }
    ]
}


```

</details>

**Comment by vyrga-axel** [comment]
Hi @chrisbonifacio . Thank you for your response.

Running `amplify update api` and selecting GraphQL tells me that the default authorization mode is API Key. The AppSync console tells me the same thing. I have tried running the queries both authenticated and as a guest, and the errors are identical. Adding the authMode: "API_KEY" didn't change antything.

I tried changing authMode to "AMAZON_COGNITO_USER_POOLS" and that fixed the errors with the listBlogs query. I rewrote my code so I could try the requests both authenticated and unauthenticated. When I tried running the queries unauthenticated I now got a _No current user_ error.

When I ran the queries authenticated the _listBlogs_ query didn't throw an error.

```
{
    "data": {
        "listBlogs": {
            "items": [],
            "nextToken": null
        }
    }
}
```

The _listPosts_ query did on the other hand throw the following error:

```
{
    "data": {
        "listPosts": null
    },
    "errors": [
        {
            "path": [
                "listPosts"
            ],
            "data": null,
            "errorType": "Unauthorized",
            "errorInfo": null,
            "locations": [
                {
                    "line": 2,
                    "column": 3,
                    "sourceName": null
                }
            ],
            "message": "Not Authorized to access listPosts on type Query"
        }
    ]
}
```

**Comment by Seikida** [comment]
@axel-andersson 
I have exactly the same issue.
I think the AWS team upgrade Amplify SDK without upgrade the documentation.
It is really not professional of their.

**Comment by 8maxxam8** [comment]
@axel-andersson 
I am also running into the same issue! Did you manage to find a solution?

**Comment by chrisbonifacio** [comment]
> Hi @chrisbonifacio . Thank you for your response.
> 
> Running `amplify update api` and selecting GraphQL tells me that the default authorization mode is API Key. The AppSync console tells me the same thing. I have tried running the queries both authenticated and as a guest, and the errors are identical. Adding the authMode: "API_KEY" didn't change antything.
> 
> I tried changing authMode to "AMAZON_COGNITO_USER_POOLS" and that fixed the errors with the listBlogs query. I rewrote my code so I could try the requests both authenticated and unauthenticated. When I tried running the queries unauthenticated I now got a _No current user_ error.
> 
> When I ran the queries authenticated the _listBlogs_ query didn't throw an error.
> 
> ```
> {
>     "data": {
>         "listBlogs": {
>             "items": [],
>             "nextToken": null
>         }
>     }
> }
> ```
> 
> The _listPosts_ query did on the other hand throw the following error:
> 
> ```
> {
>     "data": {
>         "listPosts": null
>     },
>     "errors": [
>         {
>             "path": [
>                 "listPosts"
>             ],
>             "data": null,
>             "errorType": "Unauthorized",
>             "errorInfo": null,
>             "locations": [
>                 {
>                     "line": 2,
>                     "column": 3,
>                     "sourceName": null
>                 }
>             ],
>             "message": "Not Authorized to access listPosts on type Query"
>         }
>     ]
> }
> ```

I would look at the outgoing request to AppSync and check the headers for how it was authorized. Only public/guest users are authorized to query `listPosts` with an api key. If there's an authorization header in the request then the request was made with a Cognito access token and therefore the auth mode was AMAZON_COGNITO_USER_POOLS which would be unauthorized according to the schema.

For the other reported issues by @Seikida and @8maxxam8 , please also check how the request headers are being set and match against the auth rules in your schema. If the request is being made with an auth mode you don't expect to be authorized, be sure to specify the auth mode in the API.graphql call. Otherwise, if everything seems correct, then the error may have something to do with the combination of an `owner` and `group` auth rules.

Let me know if you are able to verify.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!

**Comment by juri-diener** [comment]
> Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.
> 
> Thank you!

Still same Problem. I try run a query in amplify mock api. And get as response Unauthorized.

**Comment by chrisbonifacio** [comment]
Hi @juri-diener 👋 because you're using the mock api feature, you might be running into a different. I would recommend opening a new issue, fill out the bug report form with your non-sensitive env, schema info, amplify configuration, code snippets, and reproduction steps so that we can accurately troubleshoot the issue you're running into.
