### ISSUE TITLE
Error: No current user | getStaticProps & getStaticPaths W/ AMAZON_COGNITO_USER_POOLS

### ISSUE THREAD

**Issue by temrb** [aws-amplify/amplify-js#10027]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication, GraphQL API, Storage

### Amplify Categories

auth, storage, api

### Environment information

<details>

```
# Put output below this line

Amplify 8.3.1
NextJS

```

</details>

### Describe the bug

Trying to setup ISR with posts from DynamoDB though keep getting error:

Server Error
Error: No current user

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
GraphQLAPIClass.<anonymous>

Term:
error - Error: No current user

I have authcontext with signed in user... using authMode: GRAPHQL_AUTH_MODE.AMAZON_COGNITO_USER_POOLS..
I cannot use APIKEY authmode as these cards are setup for only allow:owner along with almost everything else in my schema.

I have 
```javascript
Amplify.configure({ ...awsconfig, ssr: true });
```

What is the issue ? Or any further setup to get ISR with nextjs?

### Expected behavior

get related querued ID cards on ISR page

I.e. 

http://localhost:4242/card/c8762039-8a6f-477d-8819-ffc9d311dd9b

### Reproduction steps

n/a

### Code Snippet

```javascript
// Put your code below this line.
import React, { ReactElement } from 'react';
import { GetStaticProps, GetStaticPaths } from 'next';
import { withSSRContext, API } from 'aws-amplify';
import { listCards, getCard } from '../../graphql/queries';
import { GRAPHQL_AUTH_MODE } from '@aws-amplify/api';
import { Card, ListCardsQuery, GetCardQuery } from '../../API';

interface Props {
  card: Card;
}

export default function IndividualCard({ card }: Props): ReactElement {
  console.log('card', card);
  return <div></div>;
}

export const getStaticProps: GetStaticProps = async ({ params }) => {
  // Call an external API endpoint to get posts.
  const SSR = withSSRContext();

  const cardsQuery = (await SSR.API.graphql({
    query: getCard,
    variables: {
      id: params?.id,
    },
    authMode: GRAPHQL_AUTH_MODE.AMAZON_COGNITO_USER_POOLS,
  })) as { data: GetCardQuery };

  // By returning { props: { posts } }, the Individual Post component
  // will receive `post` as a prop at build time
  return {
    props: {
      card: cardsQuery.data.getCard as Card,
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 10 seconds
    revalidate: 1, // In seconds
  };
};

export const getStaticPaths: GetStaticPaths = async () => {
  const SSR = withSSRContext();

  const response = (await SSR.API.graphql({
    query: listCards,
    authMode: GRAPHQL_AUTH_MODE.AMAZON_COGNITO_USER_POOLS,
  })) as {
    data: ListCardsQuery;
    errors: any[];
  };

  // Get the paths we want to pre-render based on posts
  const paths = response.data.listCards!.items.map((card) => ({
    params: { id: card!.id },
  }));

  // We'll pre-render only these paths at build time.
  // { fallback: blocking } will server-render pages
  // on-demand if the path doesn't exist.
  return { paths, fallback: true };
};


```

### Log output

<details>

```
// Put your logs below this line
Term logs:
error - Error: No current user
error - Error: No current user

```

</details>

### Additional information and screenshots

![Screen Shot 2022-06-27 at 5 50 19 AM](https://user-images.githubusercontent.com/22056864/175925173-eee250a3-7096-4680-99bb-b74191e02b6d.png)

**Comment by iartemiev** [comment]
Thanks for opening this issue. This will be fixed in https://github.com/aws-amplify/amplify-js/pull/10088

**Comment by iartemiev** [comment]
We released a fix for this issue in `aws-amplify@4.3.28`

**Comment by temrb** [comment]
@iartemiev are there any known errors? 

retrying on .28 it gives me:

```
error - Error: No current user
    at GraphQLAPIClass.<anonymous> (/Volumes/Temur XSSD/careercake/node_modules/@aws-amplify/api-graphql/lib/GraphQLAPI.js:243:31)
    at step (/Volumes/Temur XSSD/careercake/node_modules/@aws-amplify/api-graphql/lib/GraphQLAPI.js:44:23)
    at Object.throw (/Volumes/Temur XSSD/careercake/node_modules/@aws-amplify/api-graphql/lib/GraphQLAPI.js:25:53)
    at rejected (/Volumes/Temur XSSD/careercake/node_modules/@aws-amplify/api-graphql/lib/GraphQLAPI.js:17:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'Error',
  page: '/card/[id]'
}
```

with the same error on the window

**Comment by iartemiev** [comment]
Sorry, I missed this in your code when I first looked at it, but you have to pass the client-side context object to `withSSRContext`. This is what allows Amplify to utilize a client's authentication information with SSR.

```ts
export const getStaticProps: GetStaticProps = async (context) => {
  const SSR = withSSRContext(context);
  ...
}
```

There is no way to do this with `getStaticPaths`.
