### ISSUE TITLE
Error signing in again in apple after the user in the pool is deleted

### ISSUE THREAD

**Issue by emmarq** [aws-amplify/amplify-js#10044]
1. A user sign up using apple, grants a permission within the respective apple account to cognito, in cognito some data  is saved in the user pool, and the oauth authentication flow goes normally for the user, who enters the app.
2. The user data in the user pool in Cognito is deleted.
3. The user tries again to login with the same apple account.
4. The user can not login anymore and the following error appears in console
```
[ERROR] 56:34.742 OAuth - Error handling auth response. [Error: Invalid+user+attributes%3A+name%3A+The+attribute+is+required%0A+]
```

The only way so far to get rid of that error is going to https://appleid.apple.com/ and manually delete the permission granted to the app.

_Originally posted by @emmarq in https://github.com/aws-amplify/amplify-js/issues/9347#issuecomment-1165902268_

**Comment by chrisbonifacio** [comment]
Hi @emmarq 👋 thanks for raising this issue. Is `name` the only required field in your User Pool or are there others?

**Comment by emmarq** [comment]
Hi @chrisbonifacio. `name` and `email` are the required fields we have right now.

**Comment by tannerabread** [comment]
Hi @emmarq can you take a look at #10182 and see if this is the same thing that is happening to you? It seems like Apple is no longer providing the `name` attribute so it is no longer mapping to the cognito attribute

**Comment by tannerabread** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
