### ISSUE TITLE
vue starter -- typescript support?

### ISSUE THREAD

**Issue by shaunc** [aws-amplify/amplify-js#1004]
Do you want to request a feature or report a bug?

Feature request:

What is the current behavior?

No typescript support

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

What is the expected behavior?

Vue supports typescript. Can you also create a Vue sample that provides typescript support?

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by ashika01** [comment]
I guess this should be possible with the new amplify UI - more info https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue

To improve the typescript support further or have any suggestion. Feel free to open up a new issue.
