### ISSUE TITLE
Handling authentication offline

### ISSUE THREAD

**Issue by ArmorDarks** [aws-amplify/amplify-js#1006]
**Do you want to request a feature or report a bug?**

Request a feature

**What is the current behavior?**

When `Auth.currentSession()` is used and the client is offline, an error will be thrown and there won't be possible to retrieve user's session, alongside with his data.

**What is the expected behavior?**

Should be a way to get current user session, if the user has been authenticated recently, but is offline right now.

-------------------------

This issue has been created, because I do not understand, does Amplify assumes that such logic should be handled by individual solutions, or maybe there is a way, which I've missed.

If it should be implemented by developers, I assume that user's session can be stored in local storage, and while being offline app should retrieve user session from there. But I'm not sure how valid that approach, because while the user is offline, tokens can expire and all his session will become invalid.

**Comment by ArmorDarks** [comment]
Here is some of my experience in solving this issue.

Actually, `Auth.currentSession()` works just fine offline, as well as `Auth.currentAuthenticatedUser()`.

If you're offline, both will return data from already created by Amplify localStorage entries — current session and current user.

So, you can use those safely to ensure that user actually has authenticated and his session at least _seems to be valid_.

Now, where actually issues come?

1. Due to described behavior it is actually hard to tell, is user session truly valid and actual, or was it just taken from the localStorage. I feel like there should be specific for this method, or `Auth.currentSession()` and `Auth.currentAuthenticatedUser()` should contain some filed like `validated_by_server` which will indicate is it an offline session and user data or not.
2. There is no built-in way to retrieve offline current user attributes. `Auth.userAttributes(user)` will try to reach the server and will, of course, throw an error.

   The most ironic thing is that `Auth.currentSession()` and `Auth.currentAuthenticatedUser()` actually returns token with payload, which seems to contain attributes values, but there is no official function to extract them. Besides, in other issues, it was said that if somewhere `Auth.updateUserAttributes` were used, `Auth.currentSession()` and `Auth.currentAuthenticatedUser()` payloads would be out of think, which is unfortunaten.

  As a workaround,  I've got to store attributes in localStorage manually after each successful `Auth.userAttributes(user)` calls, and retrieve attributes from localStorage in case `Auth.userAttributes(user)` throwing error with code `NetworkError`.

3. Another strange thing is that while in offline nor `Auth.currentSession()`, nor `Auth.currentAuthenticatedUser()` throwing (which should mean for Amplify that user actually is authorized, right?), after calling those any calls to API gateway (`API.get('dev', '/items')`) will throw an error `No credentials` and will fail. This is quite unfortunate because they even don't try to make a call, otherwise, Service Worker could return a cached result for them. Besides, I think it also should throw error `NetworkError` and not `No credentials`. It makes handling of network errors harder.

   Instead, I've got to manually save `items` in localStorage and return them when `API.get('dev', '/items')` called in offline mode and `Auth.currentSession()` or `Auth.currentAuthenticatedUser()` didn't fail.

**Comment by ArmorDarks** [comment]
nonono

**Comment by allanweir** [comment]
This is definitely a problem we're seeing as well, has there been any success with it yet?

**Comment by ArmorDarks** [comment]
So far the only way is to hijack errors in a `catch`, check the error and if it's fitting, serve data from the local storage. Of course, you'll also need to keep in sync retrieved from Congito data with the one in the local storage.

**Comment by taschik** [comment]
Is there any best practice provided by the AWS team here?

**Comment by ericclemmons** [comment]
Unless I'm mistaken, this is expected behavior:

- `Auth.currentSession` and `Auth.currentAuthenticatedUser` will returned _cached_ data (bypassed via `bypassCache: true`) when offline (via `localStorage`).
- After the session tokens are invalid, they _must_ be refreshed via server call to be considered "valid data".

Imagine a short-lived user session (e.g. to download/stream a movie) or access to a group: you're free to store information about the user in your application state, but accessing their session (after expiration) warrants a redirect+login for security.
