### ISSUE TITLE
Indicate when Cognito temporary password is expired

### ISSUE THREAD

**Issue by ghomem** [aws-amplify/amplify-js#10079]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

REST API

### Amplify Categories

auth

### Environment information

N/A

### Describe the bug

I would like to follow up in the status of #1182. I wanted to put a comment there but the issue is locked. We have the same problem as the original poster: some users are in state FORCE_CHANGE_PASSWORD but the password can't be set because the grace period was expired. Intuitively, it seems that there should be a new state to describe this condition or a new field that can be queried to discover whether this is the case or not.

### Expected behavior

I would expect to have a way to find if the user password can be set or not (by means of the temporary password). Currently we see FORCE_CHANGE_PASSWORD whether or not the password can be set. When managing anything more than a handful of users this because very confusing in terms of support.

### Reproduction steps

1. Create a user via Cognito API
2. Check that its state is FORCE_CHANGE_PASSWORD
3. Let the grace period expire
4. Check that the user state is still FORCE_CHANGE_PASSWORD
5. Conclude that you can't distinguish in your list of users which users can and which users can not, define their password

### Log output

<details>

```
// Put your logs below this line
N/A

```

</details>

### Additional information and screenshots

N/A

**Comment by ghomem** [comment]
@mlecoq FYI the original issue that you opened is not available anymore. Did you find any solution for this?

**Comment by mlecoq** [comment]
We were in a rush and decided to let users notify us when we couldn't connect - so a manual solution

**Comment by ghomem** [comment]
> We were in a rush and decided to let users notify us when they couldn't connect - so a manual solution

Sorry to hear. Thanks for replying @mlecoq .

**Comment by tannerabread** [comment]
hi @ghomem 
Just verifying, are you looking for a solution through Cognito as the console doesn't show this information? Or did you want Amplify to handle this through the code?

**Comment by ghomem** [comment]
> hi @ghomem Just verifying, are you looking for a solution through Cognito as the console doesn't show this information? Or did you want Amplify to handle this through the code?

I would like Cognito to show the information and https://github.com/aws-amplify/amplify-js/issues/1182 was the only reference I could find, so I commented here. I opened a case with Amazon support and they very politely said they would discuss it internally but so far no news. I apologize if I created noise outside of the proper place.

**Comment by tannerabread** [comment]
Not a problem, I was just trying to clarify to see if there was something Amplify should do. I will close this now as it is a Cognito issue but feel free to open a new issue if you encounter problems with Amplify. Also, if Cognito ever gets back to you and adds this functionality to the console, feel free to open a [feature-request here](https://github.com/aws-amplify/amplify-js/issues/new?assignees=&labels=feature-request&template=2.feature_request.yaml) so that we can handle it on the frontend.

Thank you!
