### ISSUE TITLE
npm v8 installs aws-amplify-react old version of dependencies breaks authentication

### ISSUE THREAD

**Issue by fishballzzz** [aws-amplify/amplify-js#10070]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 151.95 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /opt/homebrew/opt/node@16/bin/node
    npm: 8.11.0 - /opt/homebrew/opt/node@16/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Edge: 103.0.1264.51
    Firefox: 102.0
    Safari: 15.5
  npmPackages:
    @atlaskit/tree: ^8.6.0 => 8.6.1
    @atlaskit/tree/types:  undefined ()
    @date-io/date-fns: ^2.14.0 => 2.14.0
    @fortawesome/fontawesome-svg-core: ^6.1.1 => 6.1.1
    @fortawesome/pro-duotone-svg-icons: ^6.1.1 => 6.1.1
    @fortawesome/pro-regular-svg-icons: ^6.1.1 => 6.1.1
    @fortawesome/pro-solid-svg-icons: ^6.1.1 => 6.1.1
    @fortawesome/react-fontawesome: ^0.2.0 => 0.2.0 (0.1.19)
    @kaid-health/ui-components: ^1.1.7 => 1.1.7
    @kaid-health/ui-theme: ^1.2.0 => 1.2.1
    @mui/material: ^5.8.7 => 5.8.7
    @mui/styled-engine-sc: ^5.1.0 => 5.8.0
    @mui/x-date-pickers: 5.0.0-beta.0 => 5.0.0-beta.0
    @relative-ci/agent: ^3.1.3 => 3.1.3
    @types/diff: ^5.0.2 => 5.0.2
    @types/node: ^16.11.43 => 16.11.43
    @types/qrcode.react: ^1.0.1 => 1.0.2
    @types/react: ^17.0.2 => 17.0.45
    @types/react-router: ^5.1.11 => 5.1.18
    @types/react-router-dom: ^5.1.7 => 5.3.3
    @types/styled-components: ^5.1.7 => 5.1.25
    @types/webpack: ^5.28.0 => 5.28.0
    @types/webpack-dev-server: ^4.7.2 => 4.7.2
    aws-amplify: ^4.3.27 => 4.3.27
    aws-amplify-react: ^5.1.9 => 5.1.9
    case-sensitive-paths-webpack-plugin: ^2.4.0 => 2.4.0
    clean-webpack-plugin: ^4.0.0 => 4.0.0
    css-loader: ^6.7.1 => 6.7.1
    css-minimizer-webpack-plugin: ^4.0.0 => 4.0.0
    date-fns: ^2.16.1 => 2.28.0
    diff: ^5.1.0 => 5.1.0 (4.0.2)
    encrypt-storage: ^2.2.1 => 2.2.10
    file-loader: ^6.2.0 => 6.2.0
    fork-ts-checker-webpack-plugin: ^7.2.11 => 7.2.11
    html-webpack-plugin: ^5.5.0 => 5.5.0
    mini-css-extract-plugin: ^2.6.1 => 2.6.1
    poplar-annotation: ^2.0.3 => 2.0.3
    qrcode.react: ^3.1.0 => 3.1.0 (0.8.0)
    react: ^17.0.2 => 17.0.2 (18.0.0, 16.14.0)
    react-app-polyfill: ^3.0.0 => 3.0.0
    react-dom: ^17.0.2 => 17.0.2
    react-google-charts: ^3.0.15 => 3.0.15
    react-phone-input-2: ^2.15.1 => 2.15.1
    react-router: ^5.2.0 => 5.3.3
    react-router-dom: ^5.2.0 => 5.3.3
    sass: ^1.53.0 => 1.53.0
    sass-loader: ^13.0.2 => 13.0.2
    style-loader: ^3.3.1 => 3.3.1
    styled-components: ^5.2.1 => 5.3.5
    styled-components/macro:  undefined ()
    styled-components/native:  undefined ()
    styled-components/primitives:  undefined ()
    terser-webpack-plugin: ^5.3.3 => 5.3.3
    ts-loader: ^8.0.14 => 8.4.0
    ts-node: ^9.1.1 => 9.1.1
    tslib: ^2.1.0 => 2.4.0 (1.14.1)
    typescript: ^4.6.4 => 4.6.4
    typescript-plugin-styled-components: ^2.0.0 => 2.0.0
    url-loader: ^4.1.1 => 4.1.1
    webpack: ^5.73.0 => 5.73.0
    webpack-bundle-analyzer: ^4.4.0 => 4.5.0
    webpack-cli: ^4.10.0 => 4.10.0
    webpack-dev-server: ^4.9.3 => 4.9.3
  npmGlobalPackages:
    node-gyp: 9.0.0
    npm: 7.20.3
    typescript: 4.5.2

```

</details>

### Describe the bug

The issue is basically the same as described in this ticket here https://github.com/aws-amplify/amplify-js/issues/8874. It was closed without any reasoning, so I started a new ticket. 

Everything was working fine with the latest versions of `aws-ampify` and `aws-amplify-react` until recently I upgraded npm from v6 to v8. `npm i` generates lots of vulnerabilities, I can't log in, got error as shown below. I haven't made any changes to my code except updating my node/npm version.
<img width="560" alt="Screen Shot 2022-07-09 at 2 01 18 AM" src="https://user-images.githubusercontent.com/43075130/178093860-f7713bc6-7c0e-42b4-9b8f-fc43a534b05b.png">

So, I suspect the issue is that npm v8 by default installs peer dependencies listed in each `package.json`, it's using the older versions listed in [aws-amplify-react](https://github.com/aws-amplify/amplify-js/blob/f6e2ca25785bb30ab6040f1f8c163e6069ccc392/packages/aws-amplify-react/package.json#L114) instead of the ones listed in [aws-amplify](https://github.com/aws-amplify/amplify-js/blob/f6e2ca25785bb30ab6040f1f8c163e6069ccc392/packages/aws-amplify/package.json#L36)

I am not sure if the latest `aws-amplify-react` can still work with the latest `aws-amplify` using dependencies that are a few major versions behind... But when I force the `aws-amplify-react` to use the newer versions, everything works again... 

```
"overrides": {
    "aws-amplify-react": {
      "@aws-amplify/analytics": "^5.2.7",
      "@aws-amplify/api": "^4.0.40",
      "@aws-amplify/auth": "^4.5.4",
      "@aws-amplify/core": "^4.5.4",
      "@aws-amplify/interactions": "^4.0.40",
      "@aws-amplify/storage": "^4.4.23",
      "@aws-amplify/ui": "^2.0.5",
      "@aws-amplify/xr": "^3.0.40",
      "qrcode.react": "^3.1.0",
      "react": "^17.0.2"
    }
  }
```

Thanks in advance.

### Expected behavior

(v8) npm install have no vulnerabilities/warnings, amplify auth works

### Reproduction steps

1. use npm v8
2. `npm i aws-amplify@latest aws-amplify-react@latest`
3. Should be seeing tons of vulnerabilities warnings, also using auth in 3.x.x versions instead of the latest 4.x.x. When logging in, sees the error as the screenshot shown above

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @fishballzzz thatanks for raising this issue.

We are no longer updating the aws-amplify-react package. We've since released a separate UI library for React that includes an Authenticator, auth provider, and useful auth hooks for a better developer experience.

If you do not want to migrate over to the new Amplify UI library and continue using aws-amplify-react, you will have to continue using the workaround of forcing only the latest and/or compatible versions of the peer dependencies to be installed.

**Comment by fishballzzz** [comment]
Hi @chrisbonifacio, I didn't know that `aws-amplify-react` is no longer maintained, thanks for letting me know. 

I took a quick look at the `aws-amplify-ui-react` library, and it seems very different. Is there a plan for making a migration guide? Currently, we have created many customized components with the old libraries and some APIs are not available anymore.

**Comment by chrisbonifacio** [comment]
@fishballzzz yeah, it is significantly different but unfortunately there are no plans for a migration guide. Which APIs were you using from `aws-amplify-react`? There might be a [`@aws-amplify/ui-react`](https://github.com/aws-amplify/amplify-ui/tree/main/packages/react) equivalent. The authenticator and hooks are still using the `@aws-amplify/auth` library under the hood.

For example, `aws-amplify-react` exposes an `authState` prop that can be used to render custom UI elements. The new `@aws-amplify/ui-react` hook `useAuthenticator` exposes something very similar, only called `route` instead, which can be used the same way - to check the current state of auth and render the appropriate component/view.

**Comment by fishballzzz** [comment]
Thanks Chris, one example I just came across is that we created a few components based of `AuthPiece`. There are some existing handlers like `handleInputChange` and `changeState`. 

Also, I guess I would need to create my own HOC to wrap my app with the new library?

All this seems achievable, but will need some time to do this migration. A guide definitely helps a lot lol...

Anyway, my question is answered. Feel free to close this issue.

**Comment by qwikag** [comment]
> Hi @fishballzzz thanks for raising this issue.
> 
> We are no longer updating the aws-amplify-react package. We've since released a separate UI library for React that includes an Authenticator, auth provider, and useful auth hooks for a better developer experience.
> 
> If you do not want to migrate over to the new Amplify UI library and continue using aws-amplify-react, you will have to continue using the workaround of forcing only the latest and/or compatible versions of the peer dependencies to be installed.
> 
> Otherwise, please see https://ui.docs.amplify.aws/?platform=react for more info.

Sorry, but could you please clarify in a little more detail what the new approach is?
what is and where is this new package you are referring to? Or is it installed with one of the other package installs???
because all AWS guides refer to "npm install "npm install aws-amplify @aws-amplify/ui-react"
this is found for example in: [Deploy a Next.js 13 app with authentication to AWS Amplify](https://aws.amazon.com/blogs/mobile/deploy-a-next-js-13-app-with-authentication-to-aws-amplify/
)

I am working through the AWS Amplify Next.JS install and not having a lot of success due to the way everything has evolved and changed without proper documentation.

**Comment by julianfrank** [comment]
> > Hi @fishballzzz thanks for raising this issue.
> > We are no longer updating the aws-amplify-react package. We've since released a separate UI library for React that includes an Authenticator, auth provider, and useful auth hooks for a better developer experience.
> > If you do not want to migrate over to the new Amplify UI library and continue using aws-amplify-react, you will have to continue using the workaround of forcing only the latest and/or compatible versions of the peer dependencies to be installed.
> > Otherwise, please see https://ui.docs.amplify.aws/?platform=react for more info.
> 
> Sorry, but could you please clarify in a little more detail what the new approach is? I am using "npm install aws-amplify @aws-amplify/ui-react" Is this the correct way for a Next.JS App in Amplify. I am having version issues with this error: " ⚠️ UIBuilder components require version "^4.6.0" of "@aws-amplify/ui-react". You currently are on version "^5.0.3". Run `npm install "@aws-amplify/ui-react@^4.6.0"` . Required to leverage Amplify UI primitives, and Amplify Studio component helper functions. " Following this doc: [Deploy a Next.js 13 app with authentication to AWS Amplify](https://aws.amazon.com/blogs/mobile/deploy-a-next-js-13-app-with-authentication-to-aws-amplify/)
> 
> I am working through the AWS Amplify Next.JS install and not having a lot of success due to the way everything has evolved and changed without proper documentation.

I'm getting the same whenever I do a amplify pull

**Comment by abdallahshaban557** [comment]
Hi @qwikag and @julianfrank  - can you please create new Github issues to help us get all of the steps necessary to replicate your concerns? https://github.com/aws-amplify/amplify-js/issues/new?assignees=&labels=pending-triage&projects=&template=1.bug_report.yaml
