### ISSUE TITLE
Image upload issue with AWS Amplify

### ISSUE THREAD

**Issue by dgosar** [aws-amplify/amplify-js#10080]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

REST API

### Amplify Categories

storage

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I am stuck in an issue, could anyone help me out it would really be great.

Amplify.default.configure({
    Auth: {
        identityPoolId: '',
        region: "",
    },
    Storage: {
        bucket: "bucket-name",
        region: "region",
        credentials: {
            accessKeyId: "",
            secretAccessKey: ""
        }
    }

});
Amplify.Storage.put("file path", "image buffer", { acl: "public-read-write" }, function (err) {
            if (err) {
                reject(err);
            } else{
                    resolve(url);
            }
        });
Is this correct 
because I am getting Error: Amplify has not been configured correctly. Could anybody help me ? 
I am using this on the backend side which is written in Nodejs and my frontend is React Js, I am not using Cognito

### Expected behavior

Its should directly upload the image using AWS S3 on node js side instead of again configuring Amplify on backend side.
s3.putObject(params, function (err) {if (err) {
                reject(err);
            } else {
                resolve(true);
            }
    });

### Reproduction steps

1. install aws-amplify
2. import aws-amplify
3. configure it with IdentityPooId and region
4. Call the put function of Storage class.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by dgosar** [comment]
Hi @chrisbonifacio,
Thanks for the response, I have tried using 'aws-sdk' but still getting the error. The details of the error is attached below.
<img width="556" alt="image" src="https://user-images.githubusercontent.com/107399099/179181206-80fe6269-52ae-4336-b4d8-c5457f8231dc.png">

**Comment by dgosar** [comment]
@chrisbonifacio Yes I have double checked the accessKeyId and secretAccessKey and also I have tried setting the bucket policy to be publicly accessible, Still getting the same error.

**Comment by nadetastic** [comment]
Hi @dgosar 👋,

Following up with you on this. Are you still facing issues? It also appears you switched to using `aws-sdk`
