### ISSUE TITLE
Add support to send additional data to lambda custom auth

### ISSUE THREAD

**Issue by nsalhuan** [aws-amplify/amplify-js#10084]
### Is this related to a new or existing API?

Authentication, GraphQL API

### Is this related to another service?

Lambda

### Describe the feature you'd like to request

Hi,

It would be great to be able to send additional data to the custom authorization rule on the GraphQL API. This would allow us to check for specific scopes in the lambda similar to the other auth methods.

Current implementation
```
type Salary @model @auth(rules: [{ allow: custom }]) {
  id: ID!
  wage: Int
  currency: String
}
```

### Describe the solution you'd like

I'd like to be able to pass in an array of scopes into the auth rule to power group authorization. This data would then be sent in the Event to the lambda and allow devs to create a more sophisticated custom auth solution.

```
type Salary @model @auth(rules: [{ allow: custom, groups: ["admin"] }]) {
  id: ID!
  wage: Int
  currency: String
}
```

### Describe alternatives you've considered

Discussed creating our own OIDC provider but this would still not solve the issue as one token has access to multiple orgs. Our custom auth needs to check if a user is an Admin of the specific org. OIDC would just check if they have the role Admin in the `groupsField`.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by renebrandel** [comment]
Feel free to @-mention me if I'm missing something.

**Comment by SWarrior9** [comment]
@renebrandel
Hello, hope this message find you well.

I want to do something like this:
type Salary @model @auth(rules: [{ allow: custom, customField: [“admin”] }]) {
  id: ID!
  wage: Int
  currency: String
}

And then on my lambda i would receive a token, verify it and compare the groups on the token with the groups passed on my customField.

**Comment by SWarrior9** [comment]
https://gist.github.com/miguelfranco95/5ba6bb33b1277c9eb4a35c27aeacc087
