### ISSUE TITLE
Auth.sendCustomChallengeAnswer() not throwing error with invalid verifyCode 

### ISSUE THREAD

**Issue by timotanhong** [aws-amplify/amplify-js#10097]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 921.59 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/node_modules/.bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 98.0.2
    Safari: 15.5

  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.0
    @emotion/styled: ^11.8.1 => 11.8.1
    @mui/icons-material: ^5.8.3 => 5.8.3
    @mui/lab: ^5.0.0-alpha.85 => 5.0.0-alpha.85
    @mui/material: ^5.8.3 => 5.8.3
    @testing-library/jest-dom: ^5.16.4 => 5.16.4
    @testing-library/react: ^13.3.0 => 13.3.0
    @testing-library/user-event: ^13.5.0 => 13.5.0
    @types/gtag.js: ^0.0.10 => 0.0.10
    @types/jest: ^27.5.2 => 27.5.2
    @types/node: ^16.11.39 => 16.11.39
    @types/react: ^18.0.12 => 18.0.12
    @types/react-dom: ^18.0.5 => 18.0.5
    @types/react-page-visibility: ^6.4.1 => 6.4.1
    aws-amplify: ^4.3.27 => 4.3.27
    material-ui-confirm: ^3.0.4 => 3.0.4
    notistack: ^2.0.5 => 2.0.5
query-string: ^7.1.1 => 7.1.1
    react: ^18.1.0 => 18.1.0 (18.0.0, 16.14.0)
    react-admin: ^4.1.3 => 4.1.3
    react-dom: ^18.1.0 => 18.1.0
    react-google-recaptcha-v3: ^1.9.8 => 1.9.8
    react-infinite-scroll-component: ^6.1.0 => 6.1.0
    react-page-visibility: ^7.0.0 => 7.0.0
    react-router-dom: ^6.3.0 => 6.3.0
    react-scripts: 5.0.1 => 5.0.1
    react-swipeable-views-utils: ^0.14.0 => 0.14.0
    typescript: ^4.7.3 => 4.7.3
    web-vitals: ^2.1.4 => 2.1.4
  npmGlobalPackages:

    @aws-amplify/cli: 8.5.1
    @capacitor/cli: 3.3.0
    @ionic/cli: 6.17.0
    aws-cdk: 2.27.0
    cordova-res: 0.14.0
    cordova: 10.0.0
    corepack: 0.10.0
    lodash: 4.17.21
    moment: 2.29.1
    n: 8.0.2
    native-run: 1.0.0
    ngrok: 3.4.1
    npm: 8.1.2
    serve-static: 1.14.2
    serverless: 2.9.0
    sharp: 0.26.2
    sqlite3: 5.0.0
    ts-node: 10.8.1
    typeorm-model-generator: 0.4.3
    typeorm: 0.2.37
    typescript: 4.7.3
    wscat: 5.0.0

```

</details>

### Describe the bug

Auth.sendCustomChallengeAnswer() not throwing error with invalid verifyCode , instead it return a CognitoUser object, which's
signInUserSession == null 

```
        const res = await Auth.sendCustomChallengeAnswer(
          step.user, verifyCode
        ).then(user => {
          console.log('ok')
          console.log(user)
        }).catch(err => {
          //  !!!! Never reach here even with a wrong verifyCode 
          // 
          console.log('fail')
          console.log(err)
          throw(err)
        });
        console.dir(res)
        
        //.  !!!! Since above error , I have to call currentAuthenticatedUser() to check the verify result 
        //
        const authUser = await Auth.currentAuthenticatedUser();
      } catch (error) {
          console.log('error confirming sign up: ', error);
      }
``` 

My backend setup is with a simple VerifyAuthChallenge Trigger , which was call and return result correctly according to my log 
```
package main

import (
	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
)

func Handler(event events.CognitoEventUserPoolsVerifyAuthChallenge) (events.CognitoEventUserPoolsVerifyAuthChallenge, error) {
	expectedAnswer := event.Request.PrivateChallengeParameters["secretCode"]

	if event.Request.ChallengeAnswer == expectedAnswer {
		event.Response.AnswerCorrect = true
	} else {
		event.Response.AnswerCorrect = false
	}

	return event, nil
}

func main() {
	lambda.Start(Handler)
}

```

### Expected behavior

It should throw a error when verifyCode is invalid , follow the Promise() protocol .

### Reproduction steps

1.  Call Auth.signIn() first 
```
        const user = await Auth.signIn(phoneNum);
``` 

2.  Call Auth.sendCustomChallengeAnswer() with a random verifyCode 

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
{
    "username": "+6512341234",
    "pool": {
        "userPoolId": "ap-southeast-1_.....",
        "clientId": "1ssh931........",
        "client": {
            "endpoint": "https://cognito-idp.ap-southeast-1.amazonaws.com/",
            "fetchOptions": {}
        },
        "advancedSecurityDataCollectionFlag": true,
        "storage": {
            "_grecaptcha": "09AJ0K9lKfrEyuvSja5WvO-wK80F3MQQSp0cq6QuoF2aT8ex1uklqA2yPikp8xswMg6eqJlyhamwvCe5qZ3E_tRiAGwmsn",
            "CognitoIdentityId-ap-southeast-1:dc16f70a-b034-40e2-.....": "ap-southeast-1:db30de37-1737-4a7e-8d62-....."
        }
    },
    "Session": "AYABeOZWbayZyIqQ4jEr1QYyN3U ......... 9RG5lg",
    "client": {
        "endpoint": "https://cognito-idp.ap-southeast-1.amazonaws.com/",
        "fetchOptions": {}
    },
    "signInUserSession": null,
    "authenticationFlowType": "CUSTOM_AUTH",
    "storage": {
        "_grecaptcha": "09AJ0K9lKfrEyuvSja5WvO-wK80F3MQQSp0cq6QuoF2aT8ex1uklqA2yPikp8xswMg6eqJlyhamwvCe5qZ3E_tRiAGwmsn",
        "CognitoIdentityId-ap-southeast-1:dc16f70a-b034-40e2-93a9-da553c618bfe": "ap-southeast-1:db30de37-1737-4a7e-8d62-...."
    },
    "keyPrefix": "CognitoIdentityServiceProvider.1ssh931a0hltc1avupd058vmt8",
    "userDataKey": "CognitoIdentityServiceProvider.1ssh931a0hltc1avupd058vmt8.+6512341234userData",
    "challengeName": "CUSTOM_CHALLENGE",
    "challengeParam": {
        "phone": "+6512341234"
    }
}

```

</details>

**Comment by chrisbonifacio** [comment]
Hi @timotanhong 👋 thanks for raising this issue and providing us with information to reproduce the error. We will look into this and report back soon.

**Comment by nadetastic** [comment]
Hi @timotanhong - I took a look at this issue and so far I have been unable to replicate it, but have a question I'd like to confirm with you.

Looking at the response you shared in the Log output (containing `"signInUserSession": null`), this looks like it may be actually coming from `Auth.signIn()` and not `Auth.sendCustomChallengeAnswer()` - primarily due to it containing the `challengeName` attribute set to `"CUSTOM_CHALLENGE"`. You will typically see this in the response from the signIn method.

Can you confirm this by sharing the response from both `Auth.signIn()` and `Auth.sendCustomChallengeAnswer()` from the same workflow?

**Comment by timotanhong** [comment]
Hi @nadetastic , 

Thanks for following up, 
My case is using the SMS base passwordless approach , the backend cognito triggers is same as below 
https://github.com/joekendal/cognito-passwordless

So the sign in process have two steps, with their output :

```
        // Step 1 , signIn 
        const user = await Auth.signIn(phoneNum);
        console.dir(user);
```
And it' log
```
{
    "username": "+6512341234",
    "pool": {
        "userPoolId": "ap-southeast-1_XXXXX",
        "clientId": "1ssh931a0hltc1avXXXXX",
        "client": {
            "endpoint": "https://cognito-idp.ap-southeast-1.amazonaws.com/",
            "fetchOptions": {}
        },
        "advancedSecurityDataCollectionFlag": true,
        "storage": {
            "_grecaptcha": "09AOWOVp0XY26zPWkdr3bqjGtfQ1ha3QvrJMND8Mq85mkuwvU-Ew30W5bp1_ck1go6MfyQWPN6rOX9KtOOb4hTv-FOyAlJ"
        }
    },
    "Session": "AYABeIPPTRgq8....",
    "client": {
        "endpoint": "https://cognito-idp.ap-southeast-1.amazonaws.com/",
        "fetchOptions": {}
    },
    "signInUserSession": null,
    "authenticationFlowType": "CUSTOM_AUTH",
    "storage": {
        "_grecaptcha": "09AOWOVp0XY26zPWkdr3bqjGtfQ1ha3QvrJMND8Mq85mkuwvU-Ew30W5bp1_ck1go6MfyQWPN6rOX9KtOOb4hTv-FOyAlJ"
    },
    "keyPrefix": "CognitoIdentityServiceProvider.1ssh931a0hltc1avupd058vmt8",
    "userDataKey": "CognitoIdentityServiceProvider.1ssh931a0hltc1avupd058vmt8.+6512341234.userData",
    "challengeName": "CUSTOM_CHALLENGE",
    "challengeParam": {
        "phone": "+6512341234"
    }
}
```

```
        // Step 2 , verify OTP received  
        const res = await Auth.sendCustomChallengeAnswer(
          step.user,    // user object from step 1 
          verifyCode  // verification code , OTP , here give a random (wrong ) code  to test 
        )
        console.dir(res)
        
```
And it's output
```
{
    "username": "+6512341234",
    "pool": {
        "userPoolId": "ap-southeast-1_XXXXX",
        "clientId": "1ssh931a0hltc1avXXXXX",
        "client": {
            "endpoint": "https://cognito-idp.ap-southeast-1.amazonaws.com/",
            "fetchOptions": {}
        },
        "advancedSecurityDataCollectionFlag": true,
        "storage": {
            "_grecaptcha": "09AOWOVp0XY26zPWkdr3bqjGtfQ1ha3QvrJMND8Mq85mkuwvU-Ew30W5bp1_ck1go6MfyQWPN6rOX9KtOOb4hTv-FOyAlJ"
        }
    },
    "Session": "AYABeIPPTRgq8.... ",
    "client": {
        "endpoint": "https://cognito-idp.ap-southeast-1.amazonaws.com/",
        "fetchOptions": {}
    },
    "signInUserSession": null,
    "authenticationFlowType": "CUSTOM_AUTH",
    "storage": {
        "_grecaptcha": "09AOWOVp0XY26zPWkdr3bqjGtfQ1ha3QvrJMND8Mq85mkuwvU-Ew30W5bp1_ck1go6MfyQWPN6rOX9KtOOb4hTv-FOyAlJ"
    },
    "keyPrefix": "CognitoIdentityServiceProvider.1ssh931a0hltc1avupd058vmt8",
    "userDataKey": "CognitoIdentityServiceProvider.1ssh931a0hltc1avupd058vmt8.+6512341234.userData",
    "challengeName": "CUSTOM_CHALLENGE",
    "challengeParam": {
        "phone": "+6512341234"
    }
}
```

**Comment by nadetastic** [comment]
@timotanhong Thanks for sharing the lambda function code, I was able to reproduce this issue with the functions/code at https://github.com/joekendal/cognito-passwordless/tree/7ae5a916e5f56bc19896937cccc8238819cb7efd/functions

From what I see, it looks like when the `secretCode` variable that is sent to the Verify function to confirm if the user entered a correct code doesn't have a value, this can happen.

When a random `secretCode` is generated the first time, it tries to add it to the [Response.ChallengeMetadata parameter](https://github.com/joekendal/cognito-passwordless/blob/7ae5a916e5f56bc19896937cccc8238819cb7efd/functions/create-auth-challenge/main.go#L82). Then on the subsequent invocation, it tries to set the secret code from the [previous sessions ChallengeMetadata](https://github.com/joekendal/cognito-passwordless/blob/7ae5a916e5f56bc19896937cccc8238819cb7efd/functions/create-auth-challenge/main.go#L67) which doesn't contain any values. According to the Cognito docs, [the `challengeMetaData` should contain the challenge name](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-create-auth-challenge.html) which might explain why the secretCode variable is undefined.

Additionally, I'm looking into this further with the team to understand why this doesn't throw an error but returns a Cognito user object. Testing the same with NodeJS (an undefined variable) produces an error as expected, so for now it looks like it may be specific to Go runtime.

Will update once I have additional info.

Note: I also needed to modify the [DefineAuthChallenge](https://github.com/joekendal/cognito-passwordless/tree/7ae5a916e5f56bc19896937cccc8238819cb7efd/functions/define-auth-challenge) function code as I was getting other errors that caused the CreateAuthFunction to not be invoked.

**Comment by nadetastic** [comment]
@timotanhong following up on this.

Do you still need assistance with this? As mentioned, modifying the DefineAuthChallenge function and VerifyAuthChallenge function code should result in a successful flow.
