### ISSUE TITLE
API.post() - 403 Error - When Content-Type:application/x-www-form-urlencoded, URL cannot include query-string parameters (after '?')

### ISSUE THREAD

**Issue by yashBrahma** [aws-amplify/amplify-js#10103]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication, REST API

### Amplify Categories

auth, function, api

### Environment information

<details>

```
# Put output below this line
 System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i3-1125G4 @ 2.00GHz
    Memory: 1.11 GB / 7.65 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.62)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @aws-amplify/ui-react: ^3.0.4 => 3.0.4
    @aws-amplify/ui-react-internal:  undefined ()
    @aws-amplify/ui-react-legacy:  undefined ()
    @testing-library/jest-dom: ^5.14.1 => 5.16.4
    @testing-library/react: ^13.0.0 => 13.3.0
    @testing-library/user-event: ^13.2.1 => 13.5.0
    @types/jest: ^27.0.1 => 27.5.2 (28.1.4)
    @types/node: ^16.7.13 => 16.11.43 (18.0.3)
    @types/react: ^18.0.0 => 18.0.15
    @types/react-dom: ^18.0.0 => 18.0.6
    aws-amplify: ^4.3.27 => 4.3.27
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    react-scripts: 5.0.1 => 5.0.1
    typescript: ^4.4.2 => 4.7.4
    web-vitals: ^2.1.0 => 2.1.4
  npmGlobalPackages:
    @aws-amplify/cli: 8.3.1
    typescript: 4.6.3
    yarn: 1.22.18


```

</details>

### Describe the bug

We created a lambda function with `Serverless ExpressJS function (Integration with API Gateway)` template. And edited app.js file as below. Which is working when I test it on the API gateway console. 

``` 
const aws = require('aws-sdk');
const cognito = new aws.CognitoIdentityServiceProvider();
const express = require('express')
const bodyParser = require('body-parser')
const awsServerlessExpressMiddleware = require('aws-serverless-express/middleware')


// declare a new express app
const app = express()
app.use(bodyParser.json())
app.use(awsServerlessExpressMiddleware.eventContext())

// Enable CORS for all methods
app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*")
  res.header("Access-Control-Allow-Headers", "*")
    res.header("Access-Control-Allow-Methods","OPTIONS,POST,GET,DELETE")
  next()
});

app.get('/addUser', async function(req, res) {
    const event=req.apiGateway.event
    const EMAIL = event['queryStringParameters']["email"];
    const cognitoParams = {
        UserPoolId: process.env.AUTH_TESTPOSTSIGNINLAMBB98FF678_USERPOOLID,
        Username: EMAIL,
        UserAttributes: [{
            Name: "email",
            Value: EMAIL,
        },
            {
                Name: "email_verified",
                Value: "true",
            },
        ],
        TemporaryPassword: "password"//Math.random().toString(36).substr(2, 10),//random password
    };
    let response = await cognito.adminCreateUser(cognitoParams).promise().then(() => {
        return {
            "statusCode": 200,
            'headers': { 'Content-Type': 'application/json' },
            'body':'Successfully created user'
        }
    }).catch(e=>{
        console.log("Error",e)
    });

    res.json({response})

});

app.delete('/deleteUser',async function(req,res){
    const event=req.apiGateway.event
    const EMAIL = event['queryStringParameters']["email"];
    const cognitoParams = {
        UserPoolId: process.env.AUTH_TESTPOSTSIGNINLAMBDAB98FF678B98FF678_USERPOOLID,
        Username: EMAIL
    };
    console.log("Admin delete user payload : "+ EMAIL);
    let response = await cognito.adminDeleteUser(cognitoParams).promise().then(()=>{
        return {
            "statusCode": 200,
            'headers': { 'Content-Type': 'application/json' },
            'body':'Successfully delete user'
        }
    }).catch(e=>{
        console.error("Error",e)
        return {
            "statusCode": 500,
            'headers': { 'Content-Type': 'application/json' },
            'body':'fail to delete user error' + e
        }
    });
    res.json({response})
})

app.post('/addUser',async function(req,res){
    const event=req.apiGateway.event
    const GROUPNAME = event['queryStringParameters']["groupName"];
    console.log("test :",req.body.groupName)
    console.log("contect: ", req.apiGateway.context)
    let params = {
        GroupName: GROUPNAME, /* required */
        UserPoolId: process.env.AUTH_TESTPOSTSIGNINLAMBDFF678_USERPOOLID, /* required */
    }

    let response = await cognito.createGroup(params).promise().then(()=>{
        return {
            "statusCode": 200,
            'headers': { 'Content-Type': 'application/json' },
            'body':'Successfully created groups'
        }
    }).catch(e=>{
        console.error("Error",e)
        return {
            "statusCode": 500,
            'headers': { 'Content-Type': 'application/json' },
            'body':'fail to create group' + e
        }
    });
    res.json({response})
})

app.listen(3000, function() {
    console.log("App started")
});

module.exports = app
```

But, When I do post a request with query parameters from the front-end I'm getting a 403 error with a message `message: "When Content-Type:application/x-www-form-urlencoded, URL cannot include query-string parameters (after '?'): '/dev/addUser?groupName=test123'"`. 
If I send a request without a query string or without a body, then it works without any error. And I'm getting the response back successfully.   

Front end code below
``` 
import React, {useState} from 'react';
import './App.css';
import {Authenticator} from '@aws-amplify/ui-react'
import { TextField } from '@aws-amplify/ui-react'
import {API} from 'aws-amplify'

function App() {
    const [email,setEmail]=useState("")
    const [emailDelete,setEmailDelete]=useState("")
    const [groupName,setGroupName]=useState("")
    const createUser=async ()=>{
        const apiName = 'addUserApi';
        const path = '/addUser';
        const myInit = { // OPTIONAL
            'queryStringParameters':{
                'email': email
            }
            // OPTIONAL
        };
        try {
            const response = await API.get(apiName, path,myInit);
            console.log("sucess ",response);
        } catch (error) {
            console.log("failed",error)
        }
    }

    const deleteUser=async ()=>{
        const apiName = 'addUserApi';
        const path = '/deleteUser';
        const myInit = { // OPTIONAL
            'queryStringParameters':{
                'email': emailDelete
            }
            // OPTIONAL
        };
        try {
            const response = await API.del(apiName, path,myInit);
            console.log("sucess ",response);
        } catch (error) {
            console.log("failed",error)
        }
    }
    const createGroup=async ()=>{
        const apiName = 'addUserApi';
        const path = '/addUser';
        const myInit = { // OPTIONAL
            'queryStringParameters':{
                "groupName":"test123"
            }
        };
        try {
            const response = await API.post(apiName, path,myInit);
            console.log("success ",response);
        } catch (error) {
            console.log("failed",error)
        }
    }

  return (
    <>
      <Authenticator>
        {({ signOut, user , }) => (
            <div>
              <p>
                Hey {user && user.username}, welcome to my channel, with auth!
              </p>
                <p>{user && JSON.stringify(user.attributes)}
                </p>

              <button onClick={signOut}>Sign out</button>
                <input type={"email"} value={email} onChange={(e)=>setEmail(e.target.value)} />
                <button onClick={createUser}>Create user</button>
                <div>
                    <input type={"email"} value={emailDelete} onChange={(e)=>setEmailDelete(e.target.value)} />
                    <button onClick={deleteUser}>delete user</button>
                </div>
                <input type={"email"} value={groupName} onChange={(e)=>setGroupName(e.target.value)} />
                <button onClick={createGroup}>Add Group</button>
            </div>
        )}
      </Authenticator>

    </>
  );
}
export default (App);

```
  

### Expected behavior

When the Post request is done to createGroup from the frontend it should create a group in cognito.

### Reproduction steps

1. Create react app
2. add auth
3. add api > restAPI >create lambda function with Serverless ExpressJS function (Integration with API Gateway) template > API Restrict access Individual Groups for Admin Group.
4. Edited app.js and App.tsx
5. hosted app locally and tried to do post request with a query string to create a group 403 error occured.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by nadetastic** [comment]
Hi @yashBrahma 👋, I've taken a look at this issue and so far I have unfortunately been unable to reproduce the problem.

Looking at the error, it seems that it is related to the ContentType being `application/x-www-form-urlencoded`, however in the sample code you shared it doesn't look like you specify the content type - so I'm curious where that is originating from. I also tested by specifying this header but got the expected response.

Question for you - when you do see this error, can you verify whether or not the request makes it to the Lambda function? This is to understand whether the error is originating from API Gateway or the Lambda function. A quick way to check is to see if any execution logs are generated by the Lambda function when this happens.

**Comment by yashBrahma** [comment]
Hi @nadetastic, Thanks for the response.
There was no log found in CloudFront when I made this request. And I tried doing a post request with query param on the API Gateway console I worked on there. But when I send a request with query param from the client side I got a 403 error. 

If I send a post request without query params it is working.
I tried passing content type too as application/json. I got a 400 error.

Did you try passing query params? And did you try sending requests as an authenticated user?

**Comment by nadetastic** [comment]
Hi @yashBrahma, I was able to reproduce this issue after a few more tests.

In short, this is expected behavior based on how Amplify handles `API.post()` requests and how API Gateway handles requests with `Content-type: application/x-www-form-urlencoded`.

Amplify will by default apply the `Content-type: application/x-www-form-urlencoded` header to `API.post()` requests that do not have a `body` as part of the `init` parameter. The issue then occurs due to API Gateway rejecting requests that have `Content-type: application/x-www-form-urlencoded` and also have query parameters - just as the error message states.

To overcome this, I recommend passing the value in your query parameter as part of the body instead, and retrieve the value from the body in your express app with `req.body`.

```
const myInit = {
      body: { "groupName": groupName }
}
   
await API.post(apiName,path,myInit)
```

A few more things to note:
- By including a body with your `API.post()` request, Amplify will apply `Content-type: application/json` header to the request.
- Specifying `Content-type: application/json` header in `API.post()` without including `body` will result in a Signature mismatch error .

**Comment by yashBrahma** [comment]
Hi @nadetastic, It worked Thank you for the solution.🙂
