### ISSUE TITLE
WARNING: auth is protected and dispatching on it can have unintended consequences

### ISSUE THREAD

**Issue by estrudels** [aws-amplify/amplify-js#10119]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

   "devDependencies": {
        "@aws-amplify/api-graphql": "2.3.10",
        "@aws-amplify/auth": "4.5.10",
        "@aws-amplify/core": "4.5.10",
}

### Describe the bug

When I have update `@aws-amplify/auth` from version `4.5.9` to `4.5.10` and run my tests I have I receive the following Warning for all my tests

`WARNING: auth is protected and dispatching on it can have unintended consequences`

Historically back in **Dec 19th 2019** this was an issue but was fixed
* https://github.com/aws-amplify/amplify-js/issues/4612

I am wondering if something needs to be fixed again?

Thanks

### Expected behavior

I expect when I run my tests the are no warnings being displayed

### Reproduction steps

Have tests in typescript you are using import { Auth } from '@aws-amplify/auth';

### Code Snippet

```javascript
// Put your code below this line.

```

### aws-exports.js

   "devDependencies": {
        "@aws-amplify/api-graphql": "2.3.10",
        "@aws-amplify/auth": "4.5.10",
        "@aws-amplify/core": "4.5.10",
}

**Comment by tannerabread** [comment]
@estrudels are you still experiencing this issue?

**Comment by estrudels** [comment]
@tannerabread 

Yes I am still experiencing this issue in my tests

[WARN] 48:37.405 Hub - WARNING: auth is protected and dispatching on it can have unintended consequences

The current version we are using have been updated also

"@aws-amplify/api-graphql": "2.3.19",
"@aws-amplify/auth": "4.6.8",
"@aws-amplify/core": "4.7.6",

Thanks

**Comment by tannerabread** [comment]
@estrudels  
I'm not sure that original issue you linked is related to this same warning you are seeing. I was pretty unfamiliar with this area but I noticed the warning was from Hub.

What I did find was [this documentation](https://docs.amplify.aws/lib/utilities/hub/q/platform/js/#channels) on Amplify protecting certain channels for Hub to listen on. 
Are you using Hub in your tests to listen for 'auth' events?

note:
`@aws-amplify/auth` only got version bumps for cache/core from 4.5.9-4.5.10, with cache also only getting a core version bump. The only notable difference in these packages is in `@aws-amplify/core` or `aws-amplify/api-graphql` with the introduction of `userAgentSuffix`. The changelog for this release is [here](https://github.com/aws-amplify/amplify-js/compare/aws-amplify@4.3.27...aws-amplify@4.3.28)

**Comment by estrudels** [comment]
Yes we are leveraging the use of Hub as indicated in the documentation

I am just unsure why we are seeing theses errors :(

I will try to see if I can isolate the problem

**Comment by tannerabread** [comment]
Can you give a small snippet of how you are using it in the tests?

**Comment by estrudels** [comment]
>  let contentDiv: jasmine.SpyObj<any>;  
 > let doPageAuthAndFetchAppUrl: () => Promise<void>;
>
> describe('doPageAuthAndFetchAppUrl', () => {
>  beforeEach(() => {
>             sessionStorageGetItemSpy.and.returnValue('?test=1&blerg=blork');
>         });
>  it('should capture no_managedGroup error and log the right message', async () => {
>             await doPageAuthAndFetchAppUrl();
>             Hub.dispatch('auth', {
>                 data: {
>                     message: 'PreTokenGeneration failed with error [no_managedGroup] blah blah blah serverCode blah',
>                 },
>                 event: 'clicked',
>                 message: 'lambda failed',
>             });
>             expect(contentDiv.textContent).toContain(
>                 'Unable to load InGenius as you have not been added to an InGenius Managed Group. Please contact your administrator for assistance.',
>             );
>         });
>     });

See above code snippet

I isolated this very simple and clear test.

As only needs a few lines to setup this test.

I am assuming when we do Hub.dispatch('auth', ...) we are doing something incorrect or unsafe?

@tannerabread

**Comment by tannerabread** [comment]
@estrudels 
The problem is coming from this section of the code:
```js
Hub.dispatch('auth', {
  data: {
    message: 'PreTokenGeneration failed with error [no_managedGroup] blah blah blah serverCode blah',
  },
  event: 'clicked',
  message: 'lambda failed',
});
```

`clicked` is not an Amplify event so it is complaining about using the reserved channel 'auth' with that event

Dispatching internal events through one of the protected channels such as `'auth'` can have unintended side-effects elsewhere within the library. Some part of the library may respond to the event

If you are not emitting an internal event, you can safely ignore the warning. Otherwise, it would be better to not use the `auth` channel at all for custom events and instead use a channel like `my-auth` or similar. Check out the docs on that [here](https://docs.amplify.aws/lib/utilities/hub/q/platform/js/#sending-messages)

**Comment by estrudels** [comment]
@tannerabread Thank you for your analysis and response to the issue. This makes sense and will apply these changes.

I appreciate all your help and will close this Ticket
