### ISSUE TITLE
react-native 0.66.4 Auth.signIn method returns TypeError: undefined is not an object (evaluating 'challengeParameters.USER_ID_FOR_SRP')] 

### ISSUE THREAD

**Issue by codekojo** [aws-amplify/amplify-js#10128]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication, GraphQL API, DataStore, Storage

### Amplify Categories

auth, storage

### Environment information

<details>

```
# Put output below this line
 System:
    OS: macOS 12.4
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Memory: 99.76 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 2021.11.15.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 103.0.5060.134
    Safari: 15.5
  npmGlobalPackages:
    @aws-amplify/cli: 9.1.0
    nodemon: 2.0.12
    npm: 8.1.0
    typescript: 4.4.3


```

</details>

### Describe the bug

When I try to sign in with Auth.sigin(username, password). I get this error [TypeError: undefined is not an object (evaluating 'challengeParameters.USER_ID_FOR_SRP')].

Initially it was working fine but all of the sudden I get this error whenever I try to signIn. 

### Expected behavior

I expect to retrieve token and navigate to the next screen after signing in .

### Reproduction steps

1.   const user = await Auth.signIn(username, password);

  "amazon-cognito-identity-js": "^5.2.9",
  "aws-amplify": "^4.3.26",
  "aws-amplify-react-native": "^6.0.5",
 "react": "17.0.2",
  "react-native": "0.66.4",

### Code Snippet

```
 const user = await Auth.signIn(username, password);

```

### Log output

<details>

```


[TypeError: undefined is not an object (evaluating 'challengeParameters.USER_ID_FOR_SRP')]
```

</details>

### Mobile Device

iPhone 11

### Additional information and screenshots

<img width="1083" alt="Screen Shot 2022-07-28 at 5 04 17 PM" src="https://user-images.githubusercontent.com/42769351/181597070-3db2e43c-1faf-4bf7-a603-4375c6cda86d.png">

**Comment by codekojo** [comment]
Hi @nadetastic any update on this issue?

**Comment by nadetastic** [comment]
Hi @codekojo 👋, I've been doing some testing and haven't been able to replicate this issue yet, still have a few more scenarios to test and will update soon.

In the meantime, have you been able to replicate this issue on multiple devices?

**Comment by nadetastic** [comment]
FYI, this may be happening if you are debugging with `react-native-debugger`

https://github.com/aws-amplify/amplify-js/issues/3612#issuecomment-514606847
https://github.com/aws-amplify/amplify-js/issues/4016#issuecomment-539455465

**Comment by codekojo** [comment]
I have found the issue.  I had this code which was causing such error.

```
const Blob = RNFetchBlob.polyfill.Blob;
const fs = RNFetchBlob.fs;
window.XMLHttpRequest = RNFetchBlob.polyfill.XMLHttpRequest;
window.Blob = Blob;
```

It is working fine now after commenting it. Thanks for the link.

**Comment by nadetastic** [comment]
Glad you were able to find the root of the issue. I'll close out this issue if you don't have any more questions for me.
