### ISSUE TITLE
Issue uploading videos using amplify with expo

### ISSUE THREAD

**Issue by paulsizer** [aws-amplify/amplify-js#10125]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Storage

### Amplify Categories

storage

### Environment information

<details>

```
  System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 526.47 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Safari: 15.4
  npmPackages:
    @aws-amplify/auth: ^4.3.11 => 4.5.10 
    @aws-amplify/core: ^4.3.3 => 4.5.10 
    @aws-amplify/storage: ^4.4.4 => 4.4.29 
    @babel/core: ^7.12.9 => 7.18.9 
    @react-native-async-storage/async-storage: ~1.17.3 => 1.17.7 
    @react-native-community/netinfo: 8.2.0 => 8.2.0 
    HelloWorld:  0.0.1 
    aws-amplify: ^4.3.3 => 4.3.28 
    expo: ^45.0.0 => 45.0.6 
    expo-clipboard: ~3.0.1 => 3.0.1 
    expo-constants: ~13.1.1 => 13.1.1 
    expo-image-picker: ~13.1.1 => 13.1.1 
    hermes-inspector-msggen:  1.0.0 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-web: 0.17.7 => 0.17.7 
  npmGlobalPackages:
    @aws-amplify/cli: 9.1.0
    corepack: 0.10.0
    eas-cli: 0.54.1
    expo-cli: 5.4.11
    npm: 8.5.0
    yarn: 1.22.17


```

</details>

### Describe the bug

I am using the following example to test the amplify process for uploads as we are looking to move to an option that provides progress to the client.

https://github.com/expo/examples/tree/master/with-aws-storage-upload

I have modified the example above to allow the user to pick any media type i.e. videos.

The upload process works fine for images and smaller videos, but I have an issue if you upload a larger video the app crashes with no errors.

Video information:

1080p
1920 x 1080
161.9 MB
H.264
29.99 FPS
01:24

### Expected behavior

I expect the video to upload without any issues.

### Reproduction steps

https://github.com/expo/examples/tree/master/with-aws-storage-upload

Pull down this example, and follow the installation steps and change the following methods:

```
const pickImage = async () => {
    let result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.All,
      aspect: [4, 3],
      quality: 1,
    });

    this.handleImagePicked(result);
```

```
  uploadImage = (uri, img) => {
    Auth.currentCredentials();
    const uriPartsSlash = uri.split('/');
    var filename = uriPartsSlash[uriPartsSlash.length - 1];
    return Storage.put(filename, img, {
      level: "public",
      // contentType: "image/jpeg",
      progressCallback(progress) {
        setLoading(progress);
      },
    })
      .then((response) => {
        return response.key;
      })
      .catch((error) => {
        console.log(error);
        return error.response;
      });
  };
```

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

```
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:XXX",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1XXX",
    "aws_user_pools_web_client_id": "XXX",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "expouploads133433-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;

```

### Mobile Device

iPhone X

**Comment by paulsizer** [comment]
Do you need anymore information from me for this?

**Comment by chintannp** [comment]
@paulsizer ,
                     We are aware of this issue and is being tracked in #9736. As this is a duplicate, I will go ahead and close this issue.
