### ISSUE TITLE
Schema not saving in appsync graphql api

### ISSUE THREAD

**Issue by BastienFerrier** [aws-amplify/amplify-js#10129]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

Amplify app d23eugkgc4oqez

### Describe the bug

I'm deploying a amplify app but while CloudFormation deploy stacks, it get stuck at api stack deployment on Schema resource.
Here is the message I get on the event: "Schema Creation Status is FAILED with details: Internal Failure while saving the schema."

I checked everything but I don't see what could be blocking. It have already created multiple amplify app by the past and never add any issue at this step.

Any help would be really appreciated.

### Expected behavior

Schema saved in API

### Reproduction steps

Create APP in Amplify
Add Graph QL Api
Add table by creating a schema (deployment done with CloudFormation)

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by tannerabread** [comment]
Hi :wave: @BastienFerrier, are you still experiencing this issue?

**Comment by chrisbonifacio** [comment]
Alternatively, you can run the command `amplify diagnose --send-report` and share the identifier id that is output.

**Comment by BastienFerrier** [comment]
> Hi 👋 @BastienFerrier, are you still experiencing this issue?

Well, I still get the issue but I found a workaround with my architecture. It's not really a fix but it's fine to me so far.

**Comment by BastienFerrier** [comment]
> Alternatively, you can run the command `amplify diagnose --send-report` and share the identifier id that is output.

Thanks' for the tip, didn't know about it.
