### ISSUE TITLE
Way to change user password as an admin using developer credentials (Cognito)

### ISSUE THREAD

**Issue by slvlntsv** [aws-amplify/amplify-js#1013]
Hi, 
There is already similar thread in old "amazon-cognito-identity-js" reposiory, but since it's in read-only state, and I couldn't write, I decided to open another one here.  

Currently there is no way to set user's password as Admin, on behalf of user. 
Something similar to AdminResetUserPassword, that I can run from back-end. 
It's been mentioned in old thread 1/2 year ago that this feature is in plan.
What is the status of it? Is it expected to be added soon?

Now the only way for me to control the whole process is to delete User, add him again (+authenticate and completeNewPasswordChallenge on behalf of him), needless to say how comfortable is that.. Plus I need to deal with change of ID (username) in that case

**Comment by JamesGalliford-Pulsion** [comment]
This is essential functionality for many websites. It would be very useful if this could be added soon. I am currently trying to do this and will have to resort to deleting and recreating the user. This is far from ideal, as even though it has no material impact on my application, it will mean that logs can't reliably be searched based on a user's user id if they've ever had their password changed by an admin.

Currently to get around that I think I will have to log a user's previous ids in my database, when the simpler alternative would just be to have something in place to edit as an admin.

**Comment by yannick-fernand** [comment]
Hi, 
did you already add this feature? i do need this feature also. and i am using aws-sdk-java in backend java.
Thanks

**Comment by stripathix** [comment]
Can we do it through AWS-CLI? If not then can anyone please tell by when this feature will be available.

**Comment by jlee95** [comment]
This feature is now available:

https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminSetUserPassword.html

**Comment by sammartinez** [comment]
resolving this feature request as the above statement of the feature being available.
