### ISSUE TITLE
@hasMany on table with @primaryKey w/ sort field not working

### ISSUE THREAD

**Issue by jcary741** [aws-amplify/amplify-js#10138]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line

  System:
    OS: Linux 5.10 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 7.61 GB / 9.63 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.7.0 - /usr/bin/node
    npm: 8.15.0 - /usr/bin/npm
  npmPackages:
    @aws-amplify/ui-react: ^2.20.0 => 2.20.0
    @aws-amplify/ui-react-internal:  undefined ()
    @aws-amplify/ui-react-legacy:  undefined ()
    @testing-library/jest-dom: ^5.16.4 => 5.16.4
    @testing-library/react: ^13.3.0 => 13.3.0
    @testing-library/user-event: ^13.5.0 => 13.5.0
    aws-amplify: ^4.3.28 => 4.3.28
    react: ^18.2.0 => 18.2.0 (18.0.0)
    react-dom: ^18.2.0 => 18.2.0
    react-helmet: ^6.1.0 => 6.1.0
    react-helmet-async: ^1.3.0 => 1.3.0
    react-scripts: 5.0.1 => 5.0.1
    web-vitals: ^2.1.4 => 2.1.4
  npmGlobalPackages:
    @aws-amplify/cli: 9.1.0
    corepack: 0.12.1
    npm: 8.15.0


```

</details>

### Describe the bug

The GraphQL schema directive `@hasMany` doesn't appear to work in combination with a table that has a hash key and sort key set via `@primaryKey`. Using the generated "getAlphas" query returns no "Bravos".

### Expected behavior

```
await API.graphql(graphqlOperation(getAlpha, {
    AlphaId: '123'
}))
```
should return "Bravos" with matching `AlphaId`, but does not.

### Reproduction steps

1. deploy a GraphQL API with a schema of the form:
```
type Alpha @model {
    AlphaId: ID! @primaryKey
    label: String
    Bravos: [Bravo] @hasMany
}

type Bravo @model {
    AlphaId: ID! @primaryKey(sortKeyFields: ["BravoId"])
    BravoId: ID!
    label: String
}
```
2. Populate tables with one Alpha and multiple Bravos with a common AlphaID
2. Attempt to query for Bravos on Alpha:
```
await API.graphql(graphqlOperation(getAlpha, {
    AlphaId: '123'
}))
```
3. Observe that while the Alpha entry is returned, the Bravos are not.

**Comment by alharris-at** [comment]
I believe this will be fixed by the release of Custom Primary Key support. We will verify by:
1. Seeding test data (at least one Alpha, multiple Betas)
2. Verify that a query for alpha (including linked betas) returns no betas.
3. Enabling the `respectprimarykeyattributesonconnectionfield` in the `cli.json` file and redeploying.
4. Re-verify query, ensure betas come back.
5. Verify that Javascript API.query also returns betas.

**Comment by neaumusic** [comment]
Matthews answer should fix this

I'm having great success with two PK/SK models and `"respectprimarykeyattributesonconnectionfield": true,` in `amplify/cli.json`

```
enum CONTENT { CONTENT }
type Content
  @model
  @auth(rules: [{ allow: groups, groups: ["Admin"] }]) {
  PK: CONTENT! @primaryKey(sortKeyFields: ["SK"])
  SK: ID!
  images: [Image]! @hasMany
}

enum IMAGE { IMAGE }
type Image
  @model
  @auth(rules: [{ allow: groups, groups: ["Admin"] }]) {
  PK: IMAGE! @primaryKey(sortKeyFields: ["SK"])
  SK: ID!
}
```

just delete `amplify/mock-data/` and `amplify mock --recreate-tables`
```
mutation m1 { createContent(input: {PK: CONTENT, SK: "1234"}) { PK SK } }
mutation m2 { createContent(input: {PK: CONTENT, SK: "2345"}) { PK SK } }
mutation m3 { createImage(input: {PK: IMAGE, SK: "1234", contentImagesPK: CONTENT, contentImagesSK: "1234"}) { PK SK contentImagesPK contentImagesSK } }
query q1 { listContents { items { PK SK images { items { PK SK contentImagesPK contentImagesSK } } } } }
```

this should show the relationships correctly and both Content and Image have PK/SK
I would just use Matthews answer in your case, I think it's a misconfiguration

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
