### ISSUE TITLE
RequestHeaderSectionTooLarge Amplify hosting error after Auth.signIn

### ISSUE THREAD

**Issue by pptavozl** [aws-amplify/amplify-js#10135]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication

### Amplify Categories

auth, hosting

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 135.88 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 102.0.1
    Safari: 15.6
  npmGlobalPackages:
    corepack: 0.10.0
    nodemon: 2.0.19
    npm: 8.11.0
    pnpm: 7.3.0



```

</details>

### Describe the bug

*Sometimes* after Auth.signIn(username, password), my applications send me this error:
![1](https://user-images.githubusercontent.com/7065779/181823703-d4487f6e-731a-4250-b299-4159bb180e6d.png)
![3](https://user-images.githubusercontent.com/7065779/181823878-31eb42db-33a3-439e-966b-77edbcbf7f22.png)

This error is very random, this capture was sent to me by the girl who does testing, I tried to replicate it without success.

Is there any way to solve it?

### Expected behavior

Login normally.

### Reproduction steps

1.- The user enters his username and password
2.- The application executes Auth.signIn()
3.- The page is reloaded
4.- Sometimes this error appears

### Code Snippet

```javascript
async logIn(username: string, password: string): Promise<void> {
		await Auth.signIn(username, password);
	}


```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

```javascript
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:xxxxxxxxxxx",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xxxxxxxxxxx",
    "aws_user_pools_web_client_id": "xxxxxxxx",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://xxxxxxx.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-xxxxxxxxxxxx",
    "aws_cloud_logic_custom": [
        {
            "name": "xxxxx",
            "endpoint": "https://xxxxxxxx.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "xxxxxx-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};
```

**Comment by nadetastic** [comment]
Hi @pptavozl 👋,

Looking at the Application storage screenshot, I assume you have configured your App to use Cookie storage instead of the default use of Local storage? If so, can you confirm what each of the cookies are for? The name of each will describe it, for example: `CognitoIdentityServiceProvider.<webclientid>.<username>.userData`

I'm also curious if any of them are for different users. If so, you may need to call `Auth.signOut` to clear the cookies.

Additionally, since it looks like your app is configured to use Cookie storage, is this a requirement or is it possible to use the default Local storage?

**Comment by pptavozl** [comment]
Hi @nadetastic thank you for answering,

I used Auth.singnOut() and it clear cookies.

I can switch from cookies to LocalStorage, there are documentation about it ?

Thank you

**Comment by nadetastic** [comment]
Hi @pptavozl, glad you were able to clear the un-needed cookies.

As describe [in the docs](https://docs.amplify.aws/lib/auth/start/q/platform/js/#re-use-existing-authentication-resource), Cookie Storage is usually set by manually adding `cookieStorage` to your Amplify configuration. Below are examples of how it can look:


With `Amplify.configure`
```
Amplify.configure({
    Auth: {
        ...,
        cookieStorage: {
            domain: "example.com",
            ...
        }
    }
})
```

With `Auth.configure`
```
Auth.configure({
    ...
    cookieStorage: {
        domain: "example.com",
        ...
    },
    ...
})
```

To use the default Local storage, remove `cookieStorage` from your Amplify configuration.

**Comment by nadetastic** [comment]
Hi @pptavozl, just following up on this making sure you don't have more questions for me. If not I'll go ahead close out this issue.
