### ISSUE TITLE
changePassword is calling callback twice on success.

### ISSUE THREAD

**Issue by alishah-edgy** [aws-amplify/amplify-js#1014]
```

      cognitoUser.changePassword(passwordOld, passwordNew, (err, result) => {
        console.log("change password result called");
        err ? reject(err.message) : resolve(result);
      });

```
Change password calls this result function twice. if correct values are provided 
first time will be 
err => null
result => SUCCESS
Second time will be
err => Object {code: "UnknownError", message: "Unkown error"} 
result => null
If incorrect values are provided it only gets called once.

**Comment by alishah-edgy** [comment]
@powerful23 Hi, any updates on this?

**Comment by powerful23** [comment]
@alishah-edgy sorry for the late. I tried to reproduce it but seems fine to me. Are you using the latest version of Amplify? Can you provide more details around this issue?

**Comment by alishah-edgy** [comment]
@powerful23 Yes I am using latest version of 2.0.11. Here is trace of both results.

I call the changepassword once but it responds twice.

![image](https://user-images.githubusercontent.com/35536928/41909322-2ca59bba-7960-11e8-9e56-13b079522f70.png)

**Comment by alishah-edgy** [comment]
Newer versions seems to have fixed it.
