### ISSUE TITLE
[The incoming token has expired] error log

### ISSUE THREAD

**Issue by Taehwan-Hwang-Medihere** [aws-amplify/amplify-js#10147]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>
react: 18.0.0
react-native: 0.68.0
aws-amplify: 4.3.20
</details>

### Describe the bug

Currently, APP service is using Amplify auth to process authentication.
The API environment is using AWS lambda and has processed Cognito token security on the API gateway.

In Cognito, the expiration time for ID Token and Access Token is set to 60 minutes, and the expiration time for Refresh Token is set to 3650 days.

By default, when using the service, you can check that the idToken is updated normally through the currentSession.

However, it was confirmed that [The incoming token has expired] occurred intermittently when analyzing the log of CloudWatch.

I wonder when this log can occur.

### Expected behavior

Normal token renewal completed without log of [The incoming token has expired]

### Reproduction steps

Analyze logs on specific channels with CloudWatch and Slack

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>
Error_Log
errlog:-, errlog2:-,errlog3:The incoming token has expired
</details>

**Comment by nadetastic** [comment]
Hi @Taehwan-Hwang-Medihere 👋,

I'd like to gather additional info from you on this - are you experiencing `
[The incoming token has expired]` consistently? Or is it intermittent and resolves on subsequent requests?

**Comment by nadetastic** [comment]
Hi @Taehwan-Hwang-Medihere , following up on this to see if you still need help

**Comment by nadetastic** [comment]
I'll be closing out this issue soon, if you still need assistance on this feel free to re-open at your convenience.
