### ISSUE TITLE
Linked logins disabled on Federated Identities

### ISSUE THREAD

**Issue by Jun711** [aws-amplify/amplify-js#1015]
Do you want to request a feature or report a bug?
Bug? 

What is the current behavior?
Unauthenticated users are not linked properly to the cognito User Pool and resulting in Linked logins DISABLED status for those identities on Federated Identities console. 
Thus, some unauthenticated users gets 403 requests upon landing on our web page. This happens intermittently.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.
Not sure how to reproduce. See the images for error message
https://drive.google.com/file/d/1bEFd0hkMV9CDFCDE69nTGBO76glF5i4r/view?usp=sharing
https://drive.google.com/file/d/1BKlUj2WE7nJp-fOzhvFoNIFu-aokOZNu/view?usp=sharing

What is the expected behavior?
Expect to be able to assume unauthenticated user roles.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
Amplify 0.4.3
Chrome Version 66.0.3359.181, Safari Version 11.1 (13605.1.33.1.4)

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.
We haven't encountered this when we test.

**Comment by Jun711** [comment]
I wonder under what situations an identity browser will be disabled. 
1) Amplify doesn't seem to have any function to disable / enable it. Not even on Federated identities console. So, I don't think we have accidentally disabled it. 

2) is there a way to re-enable it?

**Comment by Jun711** [comment]
@powerful23 
sorry, I didn't realize about your reply.
1) Linked logins as in an identity browser associated with a cognito user. (on the console, Cognito > Federated Identities > Select an identity pool > (left panel) Identity Browser 
I think every browser is recorded here and there is a unique id associated with a browser stored in the local storage. 

2) The unauthenticated users can assume a role to invoke a lambda endpoint. 

The issue here is somehow some of the Identity browsers are disabled(not sure how it happened) and thus, users who have their identity browsers disabled can't login using Amplify unless that disabled identity browser id in the local storage is removed. 

My question is 
i) how to prevent an identity browser from being disabled?
ii) how does this happen? 
iii) is there a way to re-enable an identity browser if it is disabled?

**Comment by Jun711** [comment]
No idea why. 

For both the unauthenticated roles / authenticated roles that are assumed by the app has 
Maximum CLI/API session duration set as 1 hour on IAM console. Other than that, not sure what other expiration time that it has.

**Comment by Jun711** [comment]
It still happens. 

The workaround that I do is it checks the response of `Auth.currentCredentials()` and if  `credentials.statusCode === 400 && credentials.code === 'NotAuthorizedException'`, `CognitoIdentityId...` key set by Amplify will be removed and then, call Auth.CurrentCredentials() again to get new CognitoIdentityId.

**Comment by zhongwencm** [comment]
Same issue
