### ISSUE TITLE
PubSub connection does not reconnect after connection lost

### ISSUE THREAD

**Issue by SamVerschueren** [aws-amplify/amplify-js#1016]
**Do you want to request a feature or report a bug?** 
bug

**What is the current behavior?**
We use `PubSub` to connect to a GraphQL topic. When our device goes offline, the websocket gets closed and it does nothing to try to reconnect.

**What is the expected behavior?**
I would expect the socket connection to try to recover after the device goes back online. This is also what Firebase does, it keeps on reconnecting until it recovers and the real-time part kicks back in.

I noticed that the `paho-mqtt` client does not use the `reconnect: true` flag. I'm not sure if this would solve it but it looks promising. The only downside is that it uses exponential backoff with a maximum of 2 minutes. This means that if your device is offline for a while, it could take up to 2 minutes for the websocket to recover which is a long time. Not sure if we can work around this problem.

**Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?**
We use `aws-amplify@^0.4.4` on Chrome. Don't think it ever worked.

**Comment by elorzafe** [comment]
Hi @SamVerschueren. Thanks for your feedback!

I would say that is more a Feature request than a bug. There are some use cases, for example if you get disconnected maybe you want to do something else like re-subscribe and get all the information that you may lost when you were offline. In that case re-subscribing only is not the solution, maybe we can add to the PubSub provider a callback in case you disconnected and enable re-subscription. What do you think?

**Comment by SamVerschueren** [comment]
I was fiddling around with this myself and was sending the disconnect error to the Observable instead of just logging. Then I did something like this

```js
from(PubSub.subscribe(...)).pipe(
    retryWhen(errors => {
        return errors.pipe(
            delay(5000)
        );
    })
):
```

I've wrapped the ZenObservable in a RxJS Observable so that I have more operators (also, it's an Angular app). Whenever an error occurs, it will retry the subscription 5 seconds later. This didn't work for some reason. Maybe you guys have a better idea at what I was doing wrong. If this had worked I would've sent a PR immediately.

**Comment by SamVerschueren** [comment]
Also, I changed [this block](https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify/src/PubSub/Providers/MqttOverWSProvider.ts#L151-L152) to the following

```ts
try {
	client = await this.connect(clientId, { url });
	client.onConnectionLost = err => {
		logger.info(err);
		observer.error(err);
	};

	targetTopics.forEach(topic => { client.subscribe(topic); });
} catch (err) {
	logger.info(err);
	observer.error(err);
}
```

The reason I used the `try-catch` is because `client.subscribe(topic);` throws if the client is in a disconnected state.

**Comment by SamVerschueren** [comment]
By the way, if you can point my in a specific direction on how you think the resubscription could/should work, please feel free and I will do a PR.

**Comment by SamVerschueren** [comment]
Made a PR for this #1167.

**Comment by rufoot** [comment]
@sammartinez 
```
from(PubSub.subscribe(...)).pipe(
    retryWhen(errors => {
        return errors.pipe(
            delay(5000)
        );
    })
):
```
I am trying to follow this. But I am not sure how can I use the `from` in the React and JavaScript.

**Comment by stocaaro** [comment]
Reconnection is now staged on the `next` tag in preparation for release in aws-amplify v5. To test against this update install the `next` tag version of the aws-amplify packages your project is using. eg `yarn add aws-amplify@next`.

With this change any disrupted connection will attempt to reconnect when possible. Reconnection can be expected to trigger 5 seconds after the resources to reconnect are available. If the network is disrupted in a way that can't be detected, reconnection will be attempted every minute until the connection is recovered.

Note that missed messages will not backfill on recovery. If you need to trigger behavior to catch up missed messaged on recovery, this should be possible to implement using the [connection state Hub messages](https://docs.amplify.aws/lib/pubsub/subunsub/q/platform/js/#unsubscribe) released last month.

**Comment by stocaaro** [comment]
Good news. Automated Reconnection is now available on the latest `aws-amplify` release! Review the [updated subscription docs](https://docs.amplify.aws/lib/pubsub/subunsub/q/platform/js/#connection-issues-and-automated-reconnection) and consider any application behavior you may want to add to best meet your users needs when subscriptions reconnect.

Please review our [breaking change guidance](https://github.com/aws-amplify/amplify-js#notice) before upgrading your application.

To upgrade Amplify to version 5, run the following in your project folder:
```
yarn add aws-amplify@latest
```

Check `package.json` to see if your project uses other `@aws-amplify/*` packages directly and upgrade them to latest as well.

With this behavior released, I am closing this issue as resolved.
