### ISSUE TITLE
Support adding lockout support for CUSTOM_AUTH Verify Authentication Response Challenge

### ISSUE THREAD

**Issue by hikarunoryoma** [aws-amplify/amplify-js#10171]
### Is this related to a new or existing API?

Authentication

### Is this related to another service?

Cognito

### Describe the feature you'd like to request

It would be nice during the Verify Authentication Response or Define Authentication Challenge to be able to lock out a user after failing to authenticate or upon a trigger defined by custom logic.  Currently this is not supported out of the box.  Meanwhile using the default authentication flow this is enforced after 5 failed attempts.  

### Describe the solution you'd like

I would expect to be able to pass a number to onCustomChallenge in amazon-cognito-identity-js to fail after a number of requests were made.  This might also be logic defined on the server side, but as of right now custom logic does not support lock outs.  Maybe the solution is for Auth.initiate to define this at the config level...

### Describe alternatives you've considered

Considered adding a lockout counter as a customAttribute for cognito and handling things on server side, but there is no API to lock out a user.  

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by nadetastic** [comment]
Hi @hikarunoryoma 👋,

This should be supported, where an error `NotAuthorizedException: Password attempts exceeded` is returned after 5+ wrong password attempts.

Could you confirm how you have configured your custom auth flow?

**Comment by nadetastic** [comment]
For more information on the lockout mechanism provided by Cognito, please reference [this link](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-authentication-flow.html#:~:text=Amazon%20Cognito%20lockout%20behavior%20for%20failed%20sign%2Din%20attempts). I'll go ahead and close this issue out for now, thank you!
