### ISSUE TITLE
CognitoUserPool.signUp() missing optional parameter types

### ISSUE THREAD

**Issue by RafaelMonteiroExaud** [aws-amplify/amplify-js#10183]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Not applicable

### Amplify Categories

Not applicable

### Environment information

<details>

```
System:
    OS: macOS 12.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 94.14 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.15.5 - /usr/local/bin/node
    npm: 7.19.0 - /usr/local/bin/npm
  Browsers:
    Safari: 15.6
  npmPackages:
    <%= name %>:  <%= version %> 
    @fastify/static: ^6.4.1 => 6.4.1 
    @nestjs/cli: ^9.0.0 => 9.0.0 
    @nestjs/common: ^9.0.0 => 9.0.7 
    @nestjs/config: ^2.2.0 => 2.2.0 
    @nestjs/core: ^9.0.0 => 9.0.7 
    @nestjs/mapped-types: * => 1.1.0 
    @nestjs/platform-express: ^9.0.0 => 9.0.7 
    @nestjs/platform-fastify: ^9.0.7 => 9.0.7 
    @nestjs/schematics: ^9.0.0 => 9.0.1 
    @nestjs/sequelize: ^9.0.0 => 9.0.0 
    @nestjs/swagger: ^6.0.4 => 6.0.4 
    @nestjs/testing: ^9.0.8 => 9.0.8 
    @types/express: ^4.17.13 => 4.17.13 
    @types/jest: 28.1.4 => 28.1.4 
    @types/node: ^16.0.0 => 16.11.46 
    @types/sequelize: ^4.28.14 => 4.28.14 
    @types/supertest: ^2.0.11 => 2.0.12 
    @typescript-eslint/eslint-plugin: ^5.0.0 => 5.31.0 
    @typescript-eslint/parser: ^5.0.0 => 5.31.0 
    amazon-cognito-identity-js: ^5.2.10 => 5.2.10 
    class-transformer: ^0.5.1 => 0.5.1 
    class-validator: ^0.13.2 => 0.13.2 
    eslint: ^8.0.1 => 8.20.0 
    eslint-config-prettier: ^8.3.0 => 8.5.0 
    eslint-plugin-prettier: ^4.0.0 => 4.2.1 
    jest: 28.1.2 => 28.1.2 
    mysql2: ^2.3.3 => 2.3.3 
    prettier: ^2.3.2 => 2.7.1 
    reflect-metadata: ^0.1.13 => 0.1.13 
    rimraf: ^3.0.2 => 3.0.2 
    rxjs: ^7.2.0 => 7.5.6 (6.6.7)
    rxjs/ajax:  undefined ()
    rxjs/fetch:  undefined ()
    rxjs/internal-compatibility:  undefined ()
    rxjs/operators:  undefined ()
    rxjs/testing:  undefined ()
    rxjs/webSocket:  undefined ()
    sequelize: ^6.21.3 => 6.21.3 
    sequelize-typescript: ^2.1.3 => 2.1.3 
    source-map-support: ^0.5.20 => 0.5.21 (0.5.13)
    sqlite3: ^5.0.10 => 5.0.10 
    supertest: ^6.1.3 => 6.2.4 
    ts-jest: 28.0.5 => 28.0.5 
    ts-loader: ^9.2.3 => 9.3.1 
    ts-node: ^10.0.0 => 10.9.1 
    tsconfig-paths: 4.0.0 => 4.0.0 (3.14.1)
    typescript: ^4.3.5 => 4.7.4 
  npmGlobalPackages:
    @asyncapi/generator: 1.8.14
    @asyncapi/html-template: 0.23.11
    @nestjs/cli: 9.0.0
    artillery: 1.7.6
    mocha: 8.3.1
    npm: 7.19.0
    pino-gelf: 2.0.0
    pino-pretty: 4.7.0
    pm2: 4.5.4
    sqlite3: 5.0.2
    swagger-cli: 4.0.4
```

</details>

### Describe the bug

When using the `amazon-cognito-identity-js` package, and trying to write a function to sign up a user in Cognito using code as shown in the [examples'](https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/README.md) use case 1, the `validationData` parameter of the `signUp` function doesn't accept `null`, opposed to what is show in the examples.
This seems to be a bug in the generated typing for the Typescript, as the generated `signUp` signature in `CognitoUserPool` is as follows:
```javascript
public signUp(
	username: string,
	password: string,
	userAttributes: CognitoUserAttribute[],
	validationData: CognitoUserAttribute[], <-- Here
	callback: NodeCallback<Error, ISignUpResult>,
	clientMetadata?: ClientMetadata
): void;
```
Which doesn't accept `null` in validationData. If I try to force Typescript to ignore the error with the following lines:
```javascript
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
```
It works as expected.

So right now forcing the error to be ignored works, but feels like a hack.

### Expected behavior

For Typescript not to throw an error when passing `null` to `validationData` in `CognitoUserPool.signUp()`

### Reproduction steps

1. Install `amazon-cognito-identity-js` library using `npm i --save amazon-cognito-identity-js`
2. Import `amazon-cognito-identity-js` into a Typescript file.
3. Create a `CognitoUserPool` object.
4. Try to call the `signUp` method on the `CognitoUserPool` object with `validationData` set to null.
5. The error will pop up, and prevent the project from compiling.

### Code Snippet

```javascript
return this.userPool.signUp(
        username,
        password,
        [new CognitoUserAttribute({ Name: 'email', Value: email })],
        null,
        (err, result) => {
          if (!result) {
            reject(err);
          } else {
            resolve(result.user);
          }
        },
      );
```

### Log output

<details>

```
error TS2345: Argument of type 'null' is not assignable to parameter of type 'CognitoUserAttribute[]'.

33         null,
           ~~~~

```

</details>

**Comment by nadetastic** [comment]
Hi @RafaelMonteiroExaud 👋,

Thanks for opening this issue. Out of curiosity, is there a requirement/reason to use `amazon-cognito-identity-js` and not Amplify Auth?

**Comment by RafaelMonteiroExaud** [comment]
Hello, there's not really a requirement, as I'm implementing auth in a new project.
As for the reason, when I searched how to integrate Cognito with the framework being used (Nest.js), all articles that showed up used the `amazon-cognito-identity-js` library.
I have stumbled upon Amplify Auth before, but from what I saw in the docs it looked like it used some extra Amazon services, while what I wanted was just to use Cognito. Am I mistaken?
Also, upon seeing that the latest build of `amazon-cogito-identity-js` was a few days old when I started implementing it, I thought it was still under active development. Is this not the case?

**Comment by nadetastic** [comment]
We have created a streamlined experience for our developers needing to use Authentication with Cognito using the Authentication library from Amplify. You can opt in to use just the [JS library without the Amplify CLI](https://docs.amplify.aws/lib/auth/start/q/platform/js/#re-use-existing-authentication-resource) if you feel like that would be better for your use case. While we do provide some occasional fixes/upgrades to the cognito-identity-js library, we are planning on deprecating that package in the near future.

**Comment by danadn** [comment]
@nadetastic the link you posted throws 404 - may you please update it? Thanks

**Comment by nadetastic** [comment]
Hi @danadn, this link should contain the same information.

https://docs.amplify.aws/lib/client-configuration/configuring-amplify-categories/q/platform/js/#general-configuration
