### ISSUE TITLE
Small issue in your documentation with the Jekyll Page Generator.

### ISSUE THREAD

**Issue by michaelcuneo** [aws-amplify/amplify-js#1018]
BUG

Small issue in your documentation with the Jekyll Page Generator.

AWS Amplify Authentication module exposes set of APIs to be used in any JavaScript framework. Please check [AWS Amplify API Reference]({%if jekyll.environment == 'production'%}{{site.amplify.baseurl}}{%endif%}/api/classes/authclass.html) for full API list.

**Comment by jordanranz** [comment]
This seems to be fixed in the new docs repo:
https://aws-amplify.github.io/docs/js/authentication

Please reopen if you are still experiencing the issue.
