### ISSUE TITLE
Custom events not showing in Pinpoint console under Filter

### ISSUE THREAD

**Issue by sampleaccount2** [aws-amplify/amplify-js#10202]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Analytics

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 245.50 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - /opt/homebrew/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 104.0.5112.79
    Safari: 15.5
  npmPackages:
    @aws-amplify/cli: ^8.2.0 => 8.2.0 
    @babel/core: ^7.12.9 => 7.14.3 
    @babel/runtime: ^7.12.5 => 7.14.0 
    @react-native-async-storage/async-storage: ^1.17.4 => 1.17.4 
    @react-native-community/eslint-config: ^2.0.0 => 2.0.0 
    @react-native-community/netinfo: ^8.3.0 => 8.3.0 
    @react-native-community/slider: 4.2.0 => 4.2.0 
    @react-native-picker/picker: ^2.4.1 => 2.4.1 
    @react-navigation/bottom-tabs: ^6.3.1 => 6.3.1 
    @react-navigation/native: ^6.0.10 => 6.0.10 
    @react-navigation/stack: ^6.2.1 => 6.2.1 
    @types/babel__core: ^7.1.19 => 7.1.19 (7.1.14)
    @types/cpx: ^1.5.2 => 1.5.2 
    @types/eslint: ^7.29.0 => 7.29.0 
    @types/ini: ^1.3.31 => 1.3.31 
    @types/inquirer: ^8.2.1 => 8.2.1 
    @types/jest: ^26.0.23 => 26.0.23 
    @types/react: 17.0.2 => 17.0.2 (17.0.45)
    @types/react-native: ^0.64.5 => 0.64.7 (0.67.3)
    @types/react-native-flip-card: ^3.5.2 => 3.5.2 
    @types/react-native-vector-icons: ^6.4.10 => 6.4.10 
    @types/react-test-renderer: ^16.9.2 => 16.9.5 
    @types/rimraf: ^3.0.2 => 3.0.2 
    HelloWorld:  0.0.1 
    add: ^2.0.6 => 2.0.6 
    amazon-cognito-identity-js: ^5.2.8 => 5.2.8 
    aws-amplify: ^4.3.22 => 4.3.22 
    aws-amplify-react-native: ^6.0.4 => 6.0.4 
    babel-jest: ^26.6.3 => 26.6.3 
    cpx: ^1.5.0 => 1.5.0 
    eslint: ^7.14.0 => 7.27.0 
    hermes-inspector-msggen:  1.0.0 
    ini: ^1.3.5 => 1.3.8 
    inquirer: ^6.5.1 => 6.5.2 
    jest: ^26.6.3 => 26.6.3 
    metro-react-native-babel-preset: ^0.66.0 => 0.66.2 
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-animatable: ^1.3.3 => 1.3.3 
    react-native-codegen: ^0.0.7 => 0.0.7 
    react-native-flip-card: ^3.5.6 => 3.5.6 
    react-native-gesture-handler: ^2.4.0 => 2.4.0 
    react-native-linear-gradient: ^2.5.6 => 2.5.6 
    react-native-localize: ^2.2.2 => 2.2.2 
    react-native-modal: ^13.0.1 => 13.0.1 
    react-native-safe-area-context: ^4.2.4 => 4.2.4 
    react-native-screens: 3.11.0 => 3.11.0 
    react-native-simple-toast: ^1.1.4 => 1.1.4 
    react-native-text-ticker: ^1.14.0 => 1.14.0 
    react-native-track-player: 2.1.2 => 2.1.2 
    react-native-url-polyfill: ^1.3.0 => 1.3.0 
    react-native-vector-icons: ^9.1.0 => 9.1.0 
    react-native-version: ^4.0.0 => 4.0.0 
    react-native-windows: ^0.65.0-0 => 0.65.7 
    react-test-renderer: 17.0.2 => 17.0.2 
    rimraf: ^3.0.2 => 3.0.2 (2.7.1, 2.2.8, 2.6.3)
    rn-placeholder: ^3.0.3 => 3.0.3 
    typescript: ^3.8.3 => 3.9.9 
  npmGlobalPackages:
    @aws-amplify/cli: 8.5.1
    expo-cli: 6.0.0
    npm: 8.15.0
    yarn: 1.22.19

```

</details>

### Describe the bug

I followed the guide [here](https://catalog.us-east-1.prod.workshops.aws/workshops/bb080ee8-4722-4290-ac6e-d4cde0a65142/en-US/03-adding-analytics/01-collect-analytics) and [here](https://docs.amplify.aws/lib/analytics/getting-started/q/platform/js/).

My Pinpoint Lambda role, authRole and unAuthRole already have `mobiletargeting:*` permissions:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "mobileanalytics:*",
                "mobiletargeting:*"
            ],
            "Resource": "*",
            "Effect": "Allow"
        }
    ]
}
```

I have both Auth and Analytics set up via `amplify auth/analytics add`.

I have exported my incremental interactions dataset from Personalize for the project linked to this, and I confirm that my custom events are indeed recorded correctly. However, the problem is that I still do not see my custom events in the Pinpoint console under Events > Filter > Event:

![image](https://user-images.githubusercontent.com/102210869/184522480-1b2915a0-ff37-47b0-b0ff-f5c05a9c547a.png)

I have also waited a few days per [here](https://stackoverflow.com/q/52108481/5305519) to ensure that this problem is not because of any delay in showing, but my custom events still do not show.

I also confirm that my Cognito identity pool has enabled access to unauthenticated identities.

I have also referred to [a similar issue](https://github.com/aws-amplify/amplify-ios/issues/841) and confirm that I have followed all the steps listed there as well but to no avail (i.e. making sure Auth/Unauth roles have IAM access, cognito identity pool has access to unauth identities)

### Expected behavior

My custom events should show in the Events Filter in Pinpoint console.

### Reproduction steps

Set up Amplify Analytics using the official guides [here](https://catalog.us-east-1.prod.workshops.aws/workshops/bb080ee8-4722-4290-ac6e-d4cde0a65142/en-US/03-adding-analytics/01-collect-analytics) and [here](https://docs.amplify.aws/lib/analytics/getting-started/q/platform/js/)

### Code Snippet

N/A

### Log output

N/A

### aws-exports.js

```javascript
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "REDACTED",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "REDACTED",
    "aws_cognito_identity_pool_id": "REDACTED",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "REDACTED",
    "aws_user_pools_web_client_id": "REDACTED",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_mobile_analytics_app_id": "REDACTED",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
```

**Comment by cwomack** [comment]
Hello @sampleaccount2 👋 .  I've been able to reproduce the issue of custom events missing from the filter list on the **Pinpoint > [Project] > Analytics > Events** page after following the tutorial steps for setup.  Despite seeing the request being sent to Pinpoint for the custom event... it was not being logged within the Pinpoint console. 

However, I was able to get both the custom _**event type**_ to show in the filter section AND to allow filtering of Attributes/Metrics/Values after tweaking the IAM role permissions policy.  I only did it for authenticated users in my test app, but here's the JSON format under **IAM > Roles > [Your-Project-Role] > Permissions Policies**: 

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "mobiletargeting:PutEvents"
            ],
            "Resource": [
                "arn:aws:mobiletargeting:us-west-2:AWS-ACCOUNT-ID:apps/YOUR-PROJECT-ID/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "mobiletargeting:UpdateEndpoint"
            ],
            "Resource": [
                "arn:aws:mobiletargeting:us-west-2:AWS-ACCOUNT-ID:apps/YOUR-PROJECT-ID/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "mobileanalytics:PutEvents"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}

```

Just to confirm, do you have page event tracking enabled somewhere in your code for events?  The `immediate` flag used below is optional, but makes it so you don't have to wait for network batching for faster confirmation: 

```
Analytics.autoTrack('event', {
  enable: true,
  immediate: true
});
```

@giorgiocarniel, tagging you as well to see if the above helps you as well.

**Comment by cwomack** [comment]
Hi 👋 Closing this issue as we have not heard back from you. If you are still experiencing problems and in need of assistance, please feel free to comment back so we can better assist you.

Thank you!
