### ISSUE TITLE
Can DataStore methods that use "idOrCriteria" (query, delete) cater for @primaryKey which have sortFieldKeys in some way?

### ISSUE THREAD

**Issue by SteveJamesDev** [aws-amplify/amplify-js#10204]
### Is this related to a new or existing API?

DataStore

### Describe the feature you'd like to request

Currently, the following works for @models that have a standard (single property) ID! field

const post = await DataStore.query(Post, "1234567");

However, this doesn't work if the @model contains something such as follows:-

type Inventory @model {
  productID: ID! @primaryKey(sortKeyFields: ["warehouseID"])
  warehouseID: ID!
  InventoryAmount: Int!
}

It would be good if the "idOrCriteria" of query() [and delete()] allowed multi-part keys to be passed in somehow

### Describe the solution you'd like

Perhaps

await DataStore.query(Inventory, { productID: 'abcdef', warehouseID: 'efghijk' })

### Describe alternatives you've considered

Using predicates works, but I am unsure (not confident) that this is a cost effective solution

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by dpilch** [comment]
The suggested syntax will be available with the custom primary key feature. https://github.com/aws-amplify/amplify-js/pull/9432. However, we do not have an ETA on the release at this time.

**Comment by david-mcafee** [comment]
@SteveJamesDev - details on how to query against composite keys can be found [in our docs](https://docs.amplify.aws/lib/datastore/advanced-workflows/q/platform/js/#querying-records-with-custom-primary-keys). If you have additional questions, please feel free to re-open this issue. Thanks!
