### ISSUE TITLE
aws-amplify-react to support for out of band registrations

### ISSUE THREAD

**Issue by jsyrjala** [aws-amplify/amplify-js#1020]
Do you want to request a feature or report a bug?

Feature request

What is the current behavior?

I have an use case where creating a new account creation is not allowed via the login form. Instead the accounts are created by administrators to Cognito. 

However, the https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify-react/src/Auth/SignIn.jsx shows always the `Sign Up` link. Clicking this link opens the registration form and submitting registration gives me error `SignUp is not permitted for this user pool`.

Currently it seems that I would have to re-implement the whole `SignIn.jsx` to get rid of that `Sign Up` link.

What is the expected behavior?

It would be nice to parametrize `SignIn.jsx` somehow so that I can select which features I need for my use cases e.g. These links are not wanted in all use cases.

- Forgot Password
- Sign Up

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

    "aws-amplify": "0.4.4",
    "aws-amplify-react": "0.1.50",

**Comment by sammartinez** [comment]
@jsyrjala are you still looking for this use case? Can you provide a little more detail on what you're looking for? Seems that you may want to SignUp to show but want to hide other links? Please let us know.

**Comment by jsyrjala** [comment]
I am using different kind of authentication solution now. 

The idea was basically to hide some of the links depending on the features which are used in the authentication.

**Comment by haverchuck** [comment]
@jsyrjala - This is actually possible with the react withAuthenticator HOC or the Authenticator component.  Here's an example of how to do this with the HOC:

```
import { ConfirmSignIn, ConfirmSignUp, ForgotPassword, RequireNewPassword, SignIn, SignUp, VerifyContact, withAuthenticator } from 'aws-amplify-react';
...
export default withAuthenticator(App, true, [
  <SignIn/>,
  <ConfirmSignIn/>,
  <VerifyContact/>,
  <ConfirmSignUp/>,
  <ForgotPassword/>,
  <RequireNewPassword />
]);
```

As you can see, I'm passing in the specific components I want my Authenticator component to display (i.e. I'm NOT passing in SignUp).  It should hide the associated links, as demonstrated in the following screenshot:

![image](https://user-images.githubusercontent.com/10621276/70740509-294d6480-1cce-11ea-8fb8-68660479f7e0.png)

The [docs](https://aws-amplify.github.io/docs/js/authentication#customization) can give you more details.

I'm closing this issue for now.
