### ISSUE TITLE
Cognito: Support 2 step login process

### ISSUE THREAD

**Issue by tobiastornros** [aws-amplify/amplify-js#1021]
Do you want to request a feature or report a bug?
Feature

What is the current behavior?

When we authenticate users we need to provide both username and password via the hosted UI or SDK to see if username/email/phonenumber is used or not. 

What is the expected behavior?

Split username and password inputs to two separate operations.
Google, Apple and other services are moving to two step login process that makes the user to first enter email or username and then customize step 2 depending whether the user exists or not. 

Is it possible to support this today with the SDK? 

For more info about the "new" 2 step flow, read here: https://ux.stackexchange.com/questions/78805/why-is-google-using-a-new-2-step-gmail-sign-in-process

**Comment by yuntuowang** [comment]
I will create a feature request on your behalf. However, we cannot comment on the delivery time. Thanks!

**Comment by harrysolovay** [comment]
This request prompts changes that would need to occur in the Cognito service itself (not the AmplifyJS library).

I'd recommend going into your AWS Console, navigating to Cognito, and then selecting "Feedback" in the bottom left-hand corner. This should prompt a modal, in which you can make this request.
