### ISSUE TITLE
AWS S3 upload with acceleration is not working

### ISSUE THREAD

**Issue by lnxct** [aws-amplify/amplify-js#10219]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Storage

### Amplify Categories

storage

### Environment information

System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Xeon(R) CPU E3-1225 v5 @ 3.30GHz
    Memory: 5.21 GB / 15.55 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.17.0 - ~/greenlync-frontend/greenlync/node_modules/.bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 103.0
  npmPackages:
    @babel/core: ^7.12.9 => 7.18.10
    @babel/runtime: ^7.12.5 => 7.18.9
    @react-native-async-storage/async-storage: ^1.17.0 => 1.17.9
    @react-native-community/blur: ^3.6.0 => 3.6.0
    @react-native-community/cameraroll: ^4.1.2 => 4.1.2
    @react-native-community/eslint-config: ^3.1.0 => 3.1.0
    @react-native-community/netinfo: ^8.2.0 => 8.3.1
    @react-native-community/push-notification-ios: ^1.10.1 => 1.10.1
    @react-native-picker/picker: ^2.3.1 => 2.4.4
    @react-native-seoul/masonry-list: ^1.1.4 => 1.3.1
    @react-navigation/bottom-tabs: ^6.2.0 => 6.3.2
    @react-navigation/material-top-tabs: ^6.1.1 => 6.2.2
    @react-navigation/native: ^6.0.8 => 6.0.11
    @react-navigation/native-stack: ^6.5.0 => 6.7.0
    @reduxjs/toolkit: ^1.8.0 => 1.8.4
    @reduxjs/toolkit-query:  1.0.0
    @reduxjs/toolkit-query-react:  1.0.0
    @types/jest: ^26.0.23 => 26.0.24
    @types/lodash: ^4.14.180 => 4.14.182
    @types/react-native: ^0.66.15 => 0.66.21
    @types/react-native-check-box: ^2.1.2 => 2.1.2
    @types/react-native-star-rating: ^1.1.2 => 1.1.2
    @types/react-native-vector-icons: ^6.4.10 => 6.4.11
    @types/react-native-video: ^5.0.12 => 5.0.14
    @types/react-test-renderer: ^17.0.1 => 17.0.2
    @types/redux-logger: ^3.0.9 => 3.0.9
    @typescript-eslint/eslint-plugin: ^5.7.0 => 5.33.0
    @typescript-eslint/parser: ^5.7.0 => 5.33.0
    Basic:  0.0.1
    HelloWorld:  0.0.1
    LocationEnable:  0.0.1
    ReactNativeRootToast:  0.0.1
    SimpleEnable:  0.0.1
    accordion-collapse-react-native: ^1.1.0 => 1.1.1
    amazon-cognito-identity-js: ^5.2.8 => 5.2.10
    aws-amplify: ^4.3.16 => 4.3.30
    aws-amplify-react-native: ^6.0.3 => 6.0.5
    axios: ^0.26.1 => 0.26.1 (0.26.0)
    babel-jest: ^26.6.3 => 26.6.3
    babel-plugin-module-resolver: ^4.1.0 => 4.1.0
    dayjs: ^1.10.8 => 1.11.5
    eslint: ^8.21.0 => 8.22.0
    eslint-import-resolver-babel-module: ^5.3.1 => 5.3.1
    eslint-plugin-import: ^2.26.0 => 2.26.0
    example:  0.0.1
    fbemitter: ^3.0.0 => 3.0.0
    geolib: ^3.3.3 => 3.3.3
    hermes-inspector-msggen:  1.0.0
    ignore-case: ^0.1.0 => 0.1.0
    jest: ^26.6.3 => 26.6.3
    lodash: ^4.17.21 => 4.17.21
    metro-react-native-babel-preset: ^0.66.2 => 0.66.2
    moment: ^2.29.2 => 2.29.4
    npm: ^8.12.1 => 8.17.0
    prettier: ^2.7.1 => 2.7.1
    prettier-eslint: ^15.0.1 => 15.0.1
    react: 17.0.2 => 17.0.2
    react-native: 0.67.3 => 0.67.3
    react-native-android-location-enabler: ^1.2.2 => 1.2.2
    react-native-auto-height-image: ^3.2.4 => 3.2.4
    react-native-check-box: ^2.1.7 => 2.1.7
    react-native-circle-floatmenu: ^0.1.1 => 0.1.1
    react-native-circular-action-menu: ^0.5.0 => 0.5.0
    react-native-code-push: ^7.0.4 => 7.0.5
    react-native-config: ^1.4.6 => 1.4.6
    react-native-date-picker: ^4.2.0 => 4.2.5
    react-native-device-info: ^8.5.0 => 8.7.1
    react-native-fast-image: ^8.5.11 => 8.5.11
    react-native-flash-message: ^0.2.1 => 0.2.1
    react-native-fs: ^2.19.0 => 2.20.0
    react-native-geolocation-service: ^5.3.0-beta.4 => 5.3.0
    react-native-gesture-bottom-sheet: ^1.1.0 => 1.1.0
    react-native-gesture-handler: file:./src/CustomModules/react-native-gesture-handler => 2.5.0
    react-native-google-maps-directions: ^2.1.1 => 2.1.1
    react-native-image-picker: ^4.7.3 => 4.8.5
    react-native-image-size: ^1.1.3 => 1.1.3
    react-native-keyboard-aware-scroll-view: ^0.9.5 => 0.9.5
    react-native-linear-gradient: ^2.5.6 => 2.6.2
    react-native-maps: ^0.30.1 => 0.30.2
    react-native-media-controls: ^2.3.0 => 2.3.0
    react-native-modal: ^13.0.1 => 13.0.1
    react-native-orientation-locker: ^1.5.0 => 1.5.0
    react-native-pager-view: ^5.4.11 => 5.4.25
    react-native-paper: ^4.11.2 => 4.12.4
    react-native-permissions: ^3.3.1 => 3.6.1
    react-native-progress: ^5.0.0 => 5.0.0
    react-native-push-notification: ^8.1.1 => 8.1.1
    react-native-ratings: ^8.1.0 => 8.1.0
    react-native-root-siblings: ^4.1.1 => 4.1.1
    react-native-root-toast: ^3.3.0 => 3.4.0
    react-native-safe-area-context: ^4.1.2 => 4.3.1
    react-native-screens: ^3.13.1 => 3.15.0
    react-native-share: ^7.3.7 => 7.8.0
    react-native-size-matters: ^0.4.0 => 0.4.0
    react-native-slider: ^0.11.0 => 0.11.0
    react-native-star-rating: ^1.1.0 => 1.1.0
    react-native-svg: ^12.4.3 => 12.4.4
    react-native-swipe-gestures: ^1.0.5 => 1.0.5
    react-native-switch: ^1.5.1 => 1.5.1
    react-native-tab-view: ^3.1.1 => 3.1.1
    react-native-vector-icons: ^9.1.0 => 9.2.0 (4.6.0)
    react-native-video: ^5.2.0 => 5.2.0
    react-native-video-controls: ^2.8.1 => 2.8.1
    react-native-video-player: ^0.12.0 => 0.12.0
    react-native-view-more-text: ^2.1.0 => 2.1.0
    react-redux: ^7.2.6 => 7.2.8
    react-test-renderer: 17.0.2 => 17.0.2
    redux: ^4.1.2 => 4.2.0
    redux-persist: ^6.0.0 => 6.0.0
    redux-persist/integration/react:  undefined ()
    reselect: ^4.1.5 => 4.1.6
    test:  0.0.1
    toggle-switch-react-native: ^3.3.0 => 3.3.0
    typescript: ^4.4.4 => 4.7.4
  npmGlobalPackages:
    @angular/cli: 14.1.1
    @aws-amplify/cli: 9.2.1
    corepack: 0.12.2
    eas-cli: 0.57.0
    expo-cli: 6.0.1
    npm: 6.14.8
    react-native-cli: 2.0.1
    serverless: 3.22.0
    yarn: 1.22.19

### Describe the bug

we have enabled S3 acceleration as per the change given merge in your repository.
`https://github.com/aws-amplify/amplify-js/pull/8750`
but it is not affected by fast acceleration.

### Expected behavior

Must be expected S3 acceleration work and user able to upload file fast compared to normal fileupload.

### Reproduction steps

1. install https://github.com/aws-amplify

### Code Snippet

packages/storage/src/providers/AWSS3ProviderManagedUpload.ts
```javascript
protected async _createNewS3Client(config, emitter?: events.EventEmitter) {
		const credentials = await this._getCredentials();
		const {
			region,
			dangerouslyConnectToHttpEndpointForTesting,
			cancelTokenSource,
			useAccelerateEndpoint
		} = config;
		let localTestingConfig = {};
```

packages/storage/src/types/AWSS3Provider.ts
```
export interface S3ProviderPutConfig extends StorageOptions {
	progressCallback?: (progress: any) => any;
	track?: boolean;
	cancelTokenSource?: CancelTokenSource;
	serverSideEncryption?: PutObjectRequest['ServerSideEncryption'];
	SSECustomerAlgorithm?: PutObjectRequest['SSECustomerAlgorithm'];
	SSECustomerKey?: PutObjectRequest['SSECustomerKey'];
	SSECustomerKeyMD5?: PutObjectRequest['SSECustomerKeyMD5'];
	SSEKMSKeyId?: PutObjectRequest['SSEKMSKeyId'];
	acl?: PutObjectRequest['ACL'];
	bucket?: PutObjectRequest['Bucket'];
	cacheControl?: PutObjectRequest['CacheControl'];
	contentDisposition?: PutObjectRequest['ContentDisposition'];
	contentEncoding?: PutObjectRequest['ContentEncoding'];
	contentType?: PutObjectRequest['ContentType'];
	expires?: PutObjectRequest['Expires'];
	metadata?: PutObjectRequest['Metadata'];
	tagging?: PutObjectRequest['Tagging'];
	useAccelerateEndpoint?: boolean;
}
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by jcollinc** [comment]
Hi @lnxct, I attempted to reproduce this issue, however accelerated uploads worked as expected. I noticed this issue was posted before the official release of the fix referenced in the issue you've linked to. If you are still having trouble with accelerated uploads I would try updating amplify to the latest version if you haven't already done so, and see if that sorts out the problem - otherwise I'm happy to take another look and see if we can troubleshoot. For now, this issue will be closed but please feel free to reach back out if you need more help.
