### ISSUE TITLE
DataStore not syncing on new project

### ISSUE THREAD

**Issue by justinjaeger** [aws-amplify/amplify-js#10228]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v16.15.1

### Amplify CLI Version

9.2.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

None

### Amplify Categories

auth, api

### Amplify Commands

add

### Describe the bug

I set up an api and am using DataStore. The data is not syncing with the cloud.

I get this error message when calling DataStore.clear(), but following the steps in the troubleshooting link did not solve my problem.

`[ERROR] 04:34.104 DataStore - Schema is not initialized. DataStore will not function as expected. This could happen if you have multiple versions of DataStore installed. Please see https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js/#check-for-duplicate-versions`

I found the function that gives me the error message in the first place as well, checkSchemaInitialized().
`https://github.com/aws-amplify/amplify-js/blob/main/packages/datastore/src/datastore/datastore.ts#L236`
It fails on the check to see if the schema has been initialized by initSchema().

Other guesses:

Perhaps the bug is the fact that my appId is different than AppSync's Graphql API appId. The AppSync GraphQL API is created automatically when I do `amplify add api` though, so I don't why it wouldn't be in sync. Maybe it's intentional that it uses a different appId. Hope someone can confirm.

I also observed that in aws-exports.js (which I re-generated by deleting and re-running `$ amplify pull --appId xxxxxxxx --envName dev`, the aws_appsync_graphqlEndpoint contains what appears to be a different AppSync apiId from the one shown in the AppSync console. For ex, my AppSync's apiId is "xxx" while I'm seeing `"aws_appsync_graphqlEndpoint": "https://yyy.appsync-api.us-east-1.amazonaws.com/graphql"`

However, when I download the config in the AppSync page, the values in that config are the same that are inside my aws-exports.js file. So perhaps these are the correct values.

### Expected behavior

Expected the DataStore to sync in the cloud, but it's not sending anything to the DynamoDB tables from my app.

### Reproduction steps

1. amplify init
2. amplify add api (with conflict detection enabled)
3. add User table to schema.graphql
4. amplify push
5. amplify codegen && amplify codegen models
6. subscribe to user table in a useEffect
```
  useEffect(() => {
    const sub = DataStore.observeQuery(User).subscribe(({ items }) => {
      setUsers(items);
    });

    return () => {
      sub.unsubscribe();
    };
  }, []);
```
7. create a user manually in dynamodb console OR create user from the app (which is in DataStore locally)
8. observe no users in the dynamodb console

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line

enum UserRole {
  ADMIN
  USER
}

type User @model @auth(rules: [{allow: public}]) {
    id: ID! @primaryKey
    email: String!
    username: String
    name: String
    bio: String
    image: String
    role: UserRole! @default(value: "USER")
}


```

</details>

### Project Identifier

[report-1660811631676.zip](https://github.com/aws-amplify/amplify-cli/files/9371881/report-1660811631676.zip)

Project Identifier: 6e09cfa89c194655d06e94a2a3ed1fa5

### Log output

<details>

```
# Put your logs below this line

[ERROR] 04:34.104 DataStore - Schema is not initialized. DataStore will not function as expected. This could happen if you have multiple versions of DataStore installed. Please see https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js/#check-for-duplicate-versions

```

</details>

### Additional information

I'm not using Amplify Studio, just the console. I've deleted and re-created my app many times with the same result.

**Comment by chrisbonifacio** [comment]
Hi @justinjaeger 👋 thanks for raising this issue. Can you share the contents of your app's package.json file?

**Comment by chrisbonifacio** [comment]
>create a user in my app using DataStore (successfully created locally)
DynamoDB tables are empty. When I call DataStore.clear(), then query for all users, I can see that no users have been created in the cloud.

Can you attempt to create another user and watch the Network Activity tab for any requests made to your AppSync API? I'm curious what the error might be in the response if the mutation is being attempted by DataStore.

**Comment by justinjaeger** [comment]
> Hi @justinjaeger 👋 thanks for raising this issue. Can you share the contents of your app's package.json file?
[package copy.json.zip](https://github.com/aws-amplify/amplify-js/files/9384890/package.copy.json.zip)

**Comment by justinjaeger** [comment]
I updated the steps to reproduce (and posted my package.json above). Originally I noted this was an issue with DataStore.clear(), but upon performing the steps outlined, this doesn't seem to be the case.

**Comment by justinjaeger** [comment]
Update: I solved my problem. The issue was because I didn't run "amplify codegen" and "amplify codegen models" AFTER enabling conflict detection (by running "amplify api update"). Then I had to run amplify push after doing so for everything to be in sync.
