### ISSUE TITLE
AWS Amplify GraphQL query return null result

### ISSUE THREAD

**Issue by da45** [aws-amplify/amplify-js#10224]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

```
  System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 3.15 GB / 15.89 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 104.0.5112.101
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.54)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @babel/core: ^7.12.9 => 7.18.10
    @react-native-async-storage/async-storage: ^1.17.9 => 1.17.9
    @react-native-community/netinfo: ^9.3.0 => 9.3.0
    @react-native-picker/picker: ^2.4.2 => 2.4.2
    @react-navigation/bottom-tabs: ^6.3.2 => 6.3.2
    @react-navigation/drawer: ^6.4.3 => 6.4.3
    @react-navigation/native: ^6.0.11 => 6.0.11
    @react-navigation/native-stack: ^6.7.0 => 6.7.0
    @reduxjs/toolkit: ^1.8.4 => 1.8.4
    @reduxjs/toolkit-query:  1.0.0
    @reduxjs/toolkit-query-react:  1.0.0
    HelloWorld:  0.0.1
    amazon-cognito-identity-js: ^5.2.10 => 5.2.10
    aws-amplify: ^4.3.31 => 4.3.31
    aws-amplify-react-native: ^6.0.5 => 6.0.5
    axios: ^0.27.2 => 0.27.2 (0.26.0)
    expo: ~46.0.7 => 46.0.7
    expo-image-picker: ~13.3.1 => 13.3.1
    expo-localization: ~13.1.0 => 13.1.0
    expo-location: ~14.3.0 => 14.3.0
    expo-status-bar: ~1.4.0 => 1.4.0
    formik: ^2.2.9 => 2.2.9
    hermes-inspector-msggen:  1.0.0
    install: ^0.13.0 => 0.13.0
    react: 18.0.0 => 18.0.0
    react-native: 0.69.4 => 0.69.4
    react-native-confirmation-code-field: ^7.3.0 => 7.3.0
    react-native-dotenv: ^3.3.1 => 3.3.1
    react-native-gesture-handler: ^2.5.0 => 2.5.0
    react-native-maps: 0.31.1 => 0.31.1
    react-native-paper: ^4.12.4 => 4.12.4
    react-native-phone-number-input: ^2.1.0 => 2.1.0
    react-native-reanimated: ^2.9.1 => 2.9.1
    react-native-safe-area-context: 4.3.1 => 4.3.1
    react-native-screens: ~3.15.0 => 3.15.0
    react-redux: ^8.0.2 => 8.0.2
    yup: ^0.32.11 => 0.32.11
  npmGlobalPackages:
    @aws-amplify/cli: 9.2.1
    @ionic/cli: 6.6.0
    eas-cli: 0.42.4
    expo-cli: 6.0.2
    npm-check-updates: 14.1.1
    npm-windows-upgrade: 6.0.1
    npm: 8.15.1
    sharp-cli: 2.1.1

```

</details>

### Describe the bug

when running the below query,  results are null, however  the same command in AWS AppSync console returns a non-null result !

onst oneTodo = await API.graphql({
  query: queries.getTodo,
  variables: { id: 'some id' }
});

### Expected behavior

return a non null result

### Reproduction steps

just run the example in the doc 
https://docs.amplify.aws/lib/graphqlapi/query-data/q/platform/js/#simple-query

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by dpilch** [comment]
I wasn't able to reproduce this. Are you sure that the you are entering a valid id on the app?  `null` will be returned in the case that the filter doesn't find a matching record.

**Comment by da45** [comment]
> I wasn't able to reproduce this. Are you sure that the you are entering a valid id on the app? `null` will be returned in the case that the filter doesn't find a matching record.

same query in AWS AppSync console works fine,

**Comment by dpilch** [comment]
Ok, can you provide additional information on how you are calling `API.graphql`? Could you also try inspecting the network tab to see what GraphQL query is being used?

Like I said, I was unable to reproduce this, so any additional information will be useful.

**Comment by Diogo-V** [comment]
I am facing a similar issue but instead I get null result in both cases (console and app) and when querying and creating an item:

Query:
![image](https://user-images.githubusercontent.com/50443643/185764293-a89dc030-d3d6-449c-8e10-6359582c5181.png)

Mutation:
![image](https://user-images.githubusercontent.com/50443643/185764571-d940b5e4-746f-4164-b93f-e6da17616cf3.png)


#### Aditional information:
* The Event table has no items (because I can't insert anything)
* Amplify version is 9.1.0

**Comment by da45** [comment]
> facing a similar issue but instead I get null result in both cases (console and app) and when querying and creating an item:

 I am using the @auth directive as below: 
 @auth(rules: [
  { allow: public, operations: [read]},
  { allow: owner }])

**Comment by Diogo-V** [comment]
I am using @auth as below:
![image](https://user-images.githubusercontent.com/50443643/185810418-2d0c5ea6-5aad-4754-9101-275f02f3e174.png)

But I don't think this is an auth error because, if it was, it would return at least an error with an unauthorized message.

**Comment by chrisbonifacio** [comment]
Is there any difference between the shape of the graphql query (check the browser Network tab for the request) being made from your apps and the one you're writing in the AppSync console?

**Comment by Diogo-V** [comment]
#### Graphql query from the AppSync console as is in the Network tab:
```json
{
    "query": "query MyQuery {\n  listEvents {\n    items {\n      id\n    }\n  }\n}\n",
    "variables": null,
    "operationName": "MyQuery"
}
```

#### Graphql query from the web app as is in the Network tab:
```json
{
    "query": "query ListEvents {\n  listEvents {\n    items {\n      id\n    }\n  }\n}\n",
    "variables": {}
}
```

#### API.graphql code snippet:
![image](https://user-images.githubusercontent.com/50443643/185875780-db7c5eaf-7114-4c32-bf4a-8f4bc83ec528.png)

And the result from that console log is the same as in the AppSync console:
```json
{"data":{"listEvents":null}}
```

**Comment by da45** [comment]
I end up deleting and recreating again rows in my table, it works, but don't have any explanation about what happened exactly

**Comment by charlesfayal** [comment]
I just had the same issue, no idea how to recreate it but very similar issue where it just returns null and doesn't save to the databse. I have plenty of similar create requests that work fine

**Comment by charlesfayal** [comment]
The other odd issue is it works fine in another environment.
