### ISSUE TITLE
TooManyRequestsException: Rate exceeded while adminCreateUser

### ISSUE THREAD

**Issue by AsitDixit** [aws-amplify/amplify-js#10243]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Authentication

### Amplify Categories

function

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
    Memory: 4.43 GB / 7.84 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.63)
  npmGlobalPackages:
    @aws-amplify/cli: 9.0.0
    touch-cli: 0.0.1


```

</details>

### Describe the bug

In pre-signup lambda function I'm trying to create user through ```adminCreateUser```. But signup is taking longer time than my expectation. My other code such as adminGetUser, ListUser,adminDeleteUser  are working very well. But this is taking longer time & throwing TooManyRequestsException.
1. I'm not getting this error in adminGetUser, ListUser,adminDeleteUser
2. It is taking very long time to execute.

### Expected behavior

My expectation is it should take at max 5 sec to run. 
It should not throw the error.
It should  create a user in userpool.

### Reproduction steps

1. My user pool configured for email & preferred username signin & required attributes for signup is only email.
2. I am using presingup  trigger to create user.

### Code Snippet

```
const aws = require('aws-sdk');
const cognito = new aws.CognitoIdentityServiceProvider({apiVersion: "2016-04-18",});



exports.handler = async (event, context,callback) => {
    const EMAIL = event.request.userAttributes.email;
    const cognitoParams = {
        UserPoolId: event.userPoolId,
        Username: event.userName,
        MessageAction:"SUPPRESS",
        ForceAliasCreation:true,
        TemporaryPassword: "Pass@123",
        UserAttributes: [{
            Name: "email",
            Value: EMAIL,
        },
        {
            Name: "email_verified",
            Value: "true",
        },
          
        ],
      
    };

    let response = await cognito.adminCreateUser(cognitoParams).promise();
    console.log(JSON.stringify(response, null, 2));
    callback(null,event);
};
```

### Log output

```
2022-08-22T05:16:40.444Z    XXXXXXX-XXXXXXX-XXXXXX-XXXXXX   ERROR   Invoke Error    {
    "errorType": "UserLambdaValidationException",
    "errorMessage": "PreSignUp failed with error PreSignUp invocation failed due to error TooManyRequestsException..",
    "code": "UserLambdaValidationException",
    "message": "PreSignUp failed with error PreSignUp invocation failed due to error TooManyRequestsException..",
    "time": "2022-08-22T05:16:40.400Z",
    "requestId": "XXXXXXXX-XXXXX-XXXXX-XXXXXXXXX",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 52.896734522859056,
    "stack": [
        "UserLambdaValidationException: PreSignUp failed with error PreSignUp invocation failed due to error TooManyRequestsException..",
        "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)",
        "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
    ]
}
```

**Comment by AsitDixit** [comment]
"errorType": "UserLambdaValidationException" what does it mean??

**Comment by AsitDixit** [comment]
Basically I'm getting 2 types of error one is ```UnexpectedLambdaException``` and other is ```serLambdaValidationException``` and the massage is common ```PreSignUp invocation failed due to error TooManyRequestsException```.

**Comment by stocaaro** [comment]
@AsitDixit Looking at your code, I'm not seeing the part that connects to the Amplify library. Is there missing context that would help me identify where to begin debugging?  If this is an issue with how the `aws-sdk` library is behaving, can you reopen this issue against that repository?

**Comment by nadetastic** [comment]
Hi @AsitDixit following up on this.

As @stocaaro mentioned, this may not be an issue with `aws-amplify` but with `aws-sdk`.  Let me know if you believe that it is related to `aws-amplify` and are still looking for help on this.

**Comment by subhan300** [comment]
I am getting the same issue when trigger the lambda function on pre-signup.
