### ISSUE TITLE
PubSub: How do I know data from which topic

### ISSUE THREAD

**Issue by bightg30098** [aws-amplify/amplify-js#1025]
Do you want to request a feature or report a bug?

Feature

What is the current behavior?

PubSub.subscribe(['myTopic1','myTopic2']).subscribe(myHandler);
In callback I can get value and provider object.
But how do i know data from which topic ?

**Comment by loganwedwards** [comment]
Is there even an undocumented way to get this? I see `_topicObservers` available when the data is received, but no clear way to figure out which topic this message came from.

Would (a non-ideal) alternative be to create different subscriptions
```
const subA = PubSub.subscribe('topicA').subscribe(() => {next: handlerA})
const subB = PubSub.subscribe('topicB').subscribe(() => {next: handlerB})
```

**Comment by jangwonsuh** [comment]
I was having a similar problem and I found a way to get the topic from the data.

`const topic = data.value[Object.getOwnPropertySymbols(data.value)[0]]`

I did not know what Symbols were until I cam across this article: [](https://www.keithcirkel.co.uk/metaprogramming-in-es6-symbols/) 

Let me know if this works for you!

**Comment by loganwedwards** [comment]
@jangwonsuh Thanks for the suggestion. It's not working for me, although I am still using `0.3.4` of Amplify and that might be the issue. The article on Symbols was interesting. Thanks for the share. I will work on updating my lib to a post 1.x release and try your suggestion again.

**Comment by bightg30098** [comment]
@jangwonsuh Thanks! It works.

**Comment by fmaker** [comment]
Please don't close, this really should be added. Otherwise using filters for topics has limited utility.

**Comment by watanabeshuji** [comment]
`data.provider.getTopicForValue(data.value)`
https://github.com/aws-amplify/amplify-js/blob/main/packages/pubsub/src/Providers/MqttOverWSProvider.ts#L93-L95

But, I want to get topic simply and generally...

**Comment by ericclemmons** [comment]
When the data is provider-specific, I recommend subscribing individually `PubSub.subscribe(topic)` rather than with `[...topics]`:
> https://docs.amplify.aws/lib/pubsub/subunsub/q/platform/js#subscribe-to-a-topic

Subscribing to multiple topics at once works best when multiple topics are publishing the same data types.

It slightly changes the implementation (one `PubSub.subscribe` vs. multiple `PubSub.subscribe`s), but allows for easier TypeScript support as well (whereas supporting multiple topics would require union types & logic gates in your code).

**Comment by wmarshdev** [comment]
> When the data is provider-specific, I recommend subscribing individually `PubSub.subscribe(topic)` rather than with `[...topics]`:
> 
> > https://docs.amplify.aws/lib/pubsub/subunsub/q/platform/js#subscribe-to-a-topic

This doesn't work for subscribing to topics with a wildcard filter.
