### ISSUE TITLE
Request to recognize api url in CN  region

### ISSUE THREAD

**Issue by GangZhang** [aws-amplify/amplify-js#10255]
### Is this related to a new or existing API?

PubSub

### Describe the feature you'd like to request

For now, the regular expression of checking if url matches standard domain pattern can not recognize the api url in CN region , for example,  https://xxxxxxxxxxxxxxxxxxxxxxxxxx.appsync-api.cn-northwest-1.amazonaws.com.cn/graphql

### Describe the solution you'd like

Provide the expected url like 'https://xxxxxxxxxxxxxxxxxxxxxxxxxx.appsync-realtime-api.cn-northwest-1.amazonaws.com.cn/graphql' rather than 'https://xxxxxxxxxxxxxxxxxxxxxxxxxx.appsync-api.cn-northwest-1.amazonaws.com.cn/graphql/realtime'

### Describe alternatives you've considered

Change the standardDomainPattern in  packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider/index.ts  file as below,

-- before --
const standardDomainPattern =
	/^https:\/\/\w{26}\.appsync\-api\.\w{2}(?:(?:\-\w{2,})+)\-\d\.amazonaws.com\/graphql$/i;

-- after --
const standardDomainPattern = /^https:\/\/\w{26}\.appsync\-api\.\w{2}(?:(?:\-\w{2,})+)\-\d\.amazonaws\.com(\.cn)?\/graphql$/i;

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by GangZhang** [comment]
@stocaaro Hi, any update on this? 
Or Could you please give a timeline as to when this will be supported? 
We expected that it can be supported before 10th Oct, so we can take App Sync as our solution in CN region . If not, we will research other solutions  ASAP.
Thanks.

**Comment by cwomack** [comment]
Hello @GangZhang, this should be taken care of by #10087 at this point.
