### ISSUE TITLE
Need to verify a user's phone number, but federated identity providers do not provide phone number.

### ISSUE THREAD

**Issue by mikeRChambers610** [aws-amplify/amplify-js#10251]
### Is this related to a new or existing framework?

Existing Amplify framework.

### Is this related to a new or existing API?

Existing API

### Is this related to another service?

Amplify, Cognito

### Describe the feature you'd like to request

I am looking for guidance on how I can set up a process to verify a user's phone number via SMS code AFTER a user has already signed up in cognito user pools. They will not be able to provide their phone number since I am using federated identity providers and these providers usually do not have that information. Therefor I need to sign them up without the phone number even though phone number verification needs to be mandatory in my application. So how do I set up the phone number verification manually outside of the Amplify.Auth flow since the user will already be created using a federated identity provider?

### Describe the solution you'd like

I would like to be able to use Amplify.Auth to be able to get a user's phone number verified after the user has signed up in cognito user pools. Then if they get a new phone number, they can verify the new phone number. This is currently not available. If there is an alternate solution to be used please let me know.

### Describe alternatives you've considered

Possibly lambda function for generating the verification SMS code, then another lambda function to confirm the user entered the correct verification code. Although, I am not sure if this can even be done or how to go about setting it up.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by tannerabread** [comment]
Hi @mikeRChambers610 
Excuse the delayed response on this issue.

Depending on the UX you are going for, it should be possible to sign up users via federated identities and then updateUserAttributes like:
```js
await Auth.updateUserAttributes(user, {
  phone_number: '+15557778888',
});
```
and then verify the phone number like:
```js
await Auth.verifyCurrentUserAttributeSubmit('phone_number', code)
  .then(() => {
     console.log('phone number verified');
  }).catch((e) => {
     console.log('failed with error', e);
  });
```

I suppose it might run into issues if requiring phone verification disables federated sign up. I haven't tried that yet but if that doesn't block you, I think you could add it and verify retroactively like the above.

Let me know if I understood correctly what you are trying to do

**Comment by tannerabread** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and are in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!

**Comment by mikeRChambers610** [comment]
@tannerabread  thanks!!

This worked but I also needed to add the below method which sends the actual code to the phone number.

 const usercreds = await Auth.currentAuthenticatedUser();
 
    try {
      
       const user = await Auth.updateUserAttributes(usercreds, {
        phone_number: this.state.phonenumString,
      }); 
      // Verification successful
      console.log('Verification successful');
      console.log(user);
   

      
    } catch (error) {
      // Handle verification error
      console.log('Verification error');
      console.log(error);
     

    }
