### ISSUE TITLE
AppSync Not Using IAM for Auth

### ISSUE THREAD

**Issue by jjbuck** [aws-amplify/amplify-js#10254]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

```



  System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 733.83 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Firefox: 91.11.0
    Safari: 15.5
  npmPackages:
    @aws-amplify/ui-react: ^3.4.1 => 3.4.1 
    @aws-amplify/ui-react-internal:  undefined ()
    @aws-amplify/ui-react-legacy:  undefined ()
    @testing-library/jest-dom: ^5.16.5 => 5.16.5 
    @testing-library/react: ^13.3.0 => 13.3.0 
    @testing-library/user-event: ^13.5.0 => 13.5.0 
    aws-amplify: ^4.3.32 => 4.3.32 
    react: ^18.2.0 => 18.2.0 (18.0.0)
    react-dom: ^18.2.0 => 18.2.0 
    react-scripts: 5.0.1 => 5.0.1 
    web-vitals: ^2.1.4 => 2.1.4 
  npmGlobalPackages:
    @aws-amplify/cli: 9.2.1
    corepack: 0.12.1
    npm: 8.15.0

```
</details>

### Describe the bug

I'm attempting to use IAM as an authentication mechanism for an AppSync/GraphQL API. As background, my React app will interface with another service that will provide temporary IAM credentials. For local testing, I'm attempting to use hardcoded credentials just to make it easier to figure out how to work with Amplify.

Even when I have the GraphQL schema set to use `@aws_iam`, the `aws_appsync_authenticationType` set to `AWS_IAM', and `authMode` in the GraphQL API call set to `AWS_IAM`, I'm seeing "No credentials" errors. When I enable debug level logs in my React app, it actually looks like Amplify is trying to use Cognito in some way.

### Expected behavior

I expect Amplify to use the credentials provided and to allow the client to invoke my AppSync endpoint without errors.

### Reproduction steps

I'm mostly following the beginner tutorial provided in https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql.

### Code Snippet

```javascript

# schema.graphql
type Note @model @auth(rules: [{ allow: public, provider: iam }]) @aws_iam {
  id: ID!
  name: String!
  description: String
}

# App.js
import React, { useState, useEffect } from 'react';
import './App.css';
import { API, Amplify, Auth, graphqlOperation } from 'aws-amplify';
import { listNotes } from './graphql/queries';
import { createNote as createNoteMutation, deleteNote as deleteNoteMutation } from './graphql/mutations';
import config from './aws-exports';
import * as subscriptions from './graphql/subscriptions';
import AWS from "aws-sdk";
window.LOG_LEVEL = 'DEBUG';

const creds = {
  accessKeyId: '<temporary access key>',
  secretAccessKey: '<temporary secret access key>',
  sessionToken: "<temporary session token",
}

AWS.config.credentials = new AWS.Credentials(creds)

Auth.currentCredentials()
  .then(d => console.log('data: ', d))
  .catch(e => console.log('error: ', e))

config.aws_appsync_authenticationType = 'AWS_IAM';
Amplify.configure(config);


const initialFormState = { name: '', description: '' }

function App() {
  const [notes, setNotes] = useState([]);
  const [formData, setFormData] = useState(initialFormState);

  useEffect(() => {
    fetchNotes();
  }, []);

  async function fetchNotes() {
    const apiData = await API.graphql({ query: listNotes, authMode: "AWS_IAM" });
    setNotes(apiData.data.listNotes.items);
  }

  async function createNote() {
    if (!formData.name || !formData.description) return;
    const authToken = await getAuthToken()
    await API.graphql({ query: createNoteMutation, variables: { input: formData }, authMode: "AWS_LAMBDA", authToken: authToken });
    setNotes([ ...notes, formData ]);
    setFormData(initialFormState);
  }

  async function deleteNote({ id }) {
    const authToken = await getAuthToken();
    const newNotesArray = notes.filter(note => note.id !== id);
    setNotes(newNotesArray);
    await API.graphql({ query: deleteNoteMutation, variables: { input: { id } },  authMode: "AWS_LAMBDA", authToken: authToken });
  }

  return (
    <div className="App">
      <h1>My Notes App</h1>
      <input
        onChange={e => setFormData({ ...formData, 'name': e.target.value})}
        placeholder="Note name"
        value={formData.name}
      />
      <input
        onChange={e => setFormData({ ...formData, 'description': e.target.value})}
        placeholder="Note description"
        value={formData.description}
      />
      <button onClick={createNote}>Create Note</button>
      <div style={{marginBottom: 30}}>
        {
          notes.map(note => (
            <div key={note.id || note.name}>
              <h2>{note.name}</h2>
              <p>{note.description}</p>
              <button onClick={() => deleteNote(note)}>Delete note</button>
            </div>
          ))
        }
      </div>
    </div>
  );
}

export default App;

```

### Log output

<details>

```
[DEBUG] 04:35.347 Credentials - getting credentials
ConsoleLogger.ts:115 [DEBUG] 04:35.347 Credentials - picking up credentials
ConsoleLogger.ts:115 [DEBUG] 04:35.347 Credentials - getting old cred promise
[DEBUG] 04:35.348 AWSAppSyncRealTimeProvider - Authenticating with AWS_LAMBDA
ConsoleLogger.ts:115 [DEBUG] 04:35.348 AuthClass - Getting current session
ConsoleLogger.ts:115 [DEBUG] 04:35.348 AuthClass - getting guest credentials
ConsoleLogger.ts:115 [DEBUG] 04:35.348 Credentials - setting credentials for guest
ConsoleLogger.ts:115 [DEBUG] 04:35.348 Credentials - No Cognito Identity pool provided for unauthenticated access


GraphQLAPI.ts:154 Uncaught (in promise) Error: No credentials
    at GraphQLAPIClass.<anonymous> (GraphQLAPI.ts:154:1)
    at step (reportWebVitals.js:13:1)
    at Object.next (reportWebVitals.js:13:1)
    at fulfilled (reportWebVitals.js:13:1)
```

### aws-exports.js

/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://inuwoxcofvgjthpdy7mjdqxvjq.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AWS_LAMBDA"
};

export default awsmobile;

**Comment by jjbuck** [comment]
I finally figured this out (I think) and want to share the solution for posterity. I essentially followed the approach described in https://docs.amplify.aws/guides/functions/graphql-from-lambda/q/platform/js/ and had to construct a GraphQL client and manually construct the request with the sigV4 signing.

Perhaps this is just user error, but I'll say it was significantly non-obvious that this would be required when every other setting and configuration in the client-side code specified `@aws_iam`, `provider: iam`, etc.

**Comment by arundna** [comment]
@jjbuck - 👋 Thanks for opening this issue and providing additional details. You can also optionally use the **graphqlOperation** helper function to construct the argument object as shown in our docs - https://docs.amplify.aws/lib/graphqlapi/mutate-data/q/platform/js/

The Getting Started Hands On Tutorial needs an update and we'll change the code in the respective sections.

**Comment by elorzafe** [comment]
@jjbuck 

Currently is not possible to hydrate AWS Amplify with your own AWS credentials. Which AWS credentials provider are you using?

Thanks!

**Comment by jjbuck** [comment]
Thanks for your response @elorzafe . The full details of my use case are a little beyond the scope of the original question, but in a nutshell I have an adjacent system that will provide IAM credentials that I want Amplify (or more specifically, an AppSync client) to use. 

We can probably close this issue since I think I've figure out the solution as described above in https://github.com/aws-amplify/amplify-js/issues/10254#issuecomment-1228718319. My closing thought would be to take this as just one data point that a user was confused by some of the `@aws_iam`, `provider: iam` directors and found them to be non-intuitive. You might consider updating documentation or adding wording to make it a little clear what these things do, and importantly, what they **don't** do.

**Comment by abdallahshaban557** [comment]
Thank you for the feedback @jjbuck - this feedback has been shared with our documentation/data team to further enhance this piece!
