### ISSUE TITLE
Cognito SMS verification not being sent out to iPhone devices

### ISSUE THREAD

**Issue by sydiaplatform** [aws-amplify/amplify-js#10262]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

GraphQL API

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
Expo React Native and amplify.

```

</details>

### Describe the bug

Hi,

I've setup Cognito and set the SNS limits and moved to production.

The SMS verification is being sent to Android devices upon signup but not iPhone devices.

The CloudWatch logs show the SMS were sent.

Any suggestions?

### Expected behavior

To receive and SMS with the verification code.

### Reproduction steps

Configured Auth with React Native and followed the steps as per the amplify docs.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by ncarvajalc** [comment]
I tried to reproduced this error following the steps bellow:

- Configured Auth with React Native and followed the steps as per the Amplify docs using the Auth class
- Created a simple sign up app
- Moved from Sandbox SNS environment to production
- Sended SMS both to an Android and iPhone device and recieved the message

![IMG_6389](https://user-images.githubusercontent.com/66692533/192879507-4e737245-30a5-4213-8205-759dd023ab74.png)
![WhatsApp Image 2022-09-28 at 3 16 53 PM](https://user-images.githubusercontent.com/66692533/192880257-d2791d19-904d-47ae-8769-eab86d37ffa4.jpeg)

**Comment by nadetastic** [comment]
Hi @sydiaplatform closing this issue out for now.

If you are still facing this issue, you can re-open and confirm if this is happening on a physical iOS device or on the Simulator.
