### ISSUE TITLE
Auth session issue in few Android devices during time travel to future date

### ISSUE THREAD

**Issue by muniramachandra15** [aws-amplify/amplify-js#10263]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Apple M1
    Memory: 18.68 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.19.2 - /usr/local/opt/node@14/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 6.14.17 - /usr/local/opt/node@14/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Firefox: 104.0
    Safari: 15.4
 npmPackages:
    aws-amplify: ^2.2.0 => 2.2.0 
    aws-appsync: 4.0.3 => 4.0.3 
    aws-appsync-react: ^2.0.2 => 2.0.2 
 npmGlobalPackages:
    corepack: 0.10.0
    npm: 8.8.0

```

</details>

### Describe the bug

If user login to the App, AWS-Amplify is creating a session for the user with a 1 hour validity of access token. This flow is working fine in all iPhone and Android mobiles as well.

As per our requirement, User has an option to do time travel (Changing mobile system date) to execute some tasks from mobile App. When user do a time travel to future date for more than a month ( > 30 days) in mobile, Amplify is creating a session with current date and time only, not with time travel date.

App is able to hit the backend server with this access token and  is able to get the data from backend server in iPhone mobiles.

But In Android, few devices aren’t able to hit the backend server with this access token when user does the time travel to future date. Client request times out after 5 minutes and In the logs we are getting below error.

**Network error** : Network request failed

For example we tested in two Samsung A11 (Android OS version 11), One device time zone is UTC+5.30 and another device is time zone is UTC-5.00. It is working fine in mobile with time zone UTC+5.30.

Second device is getting network error. 

We noticed this issue is happening in few android devices only.

### Expected behavior

App should communicate with the backend server even when user does time travel to future date in mobile.

### Reproduction steps

1. Open the App and Login with user credentials. 
2. Kill the App.
3. Do time travel to future date (more than a 30 days) in Android mobile by changing the mobile system date.
4. Open the App and enter the user credentials.
5. Try to communicate with backend server to fetch the data with the session created during the login time.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

<img width="1373" alt="timetravel_amplify-session" src="https://user-images.githubusercontent.com/77112924/186900842-9fea9618-5902-4466-9ff1-439199e36ef5.png">

**Comment by tannerabread** [comment]
@muniramachandra15 
Are you using physical devices for these tests or through an emulator?
What method are you using to check the session data?
I see you are using an old version of Amplify, is there a particular reason for that?

**Comment by muniramachandra15** [comment]
1. Tested in physical device (Android mobile) only.
2. We are using below method to get session 
      let userPool = new AWSCognito.CognitoUserPool(poolData);
      let authenticationData = { Username: username, Password: pw };
      let authenticationDetails = new AWSCognito.AuthenticationDetails(authenticationData);
      this._cognitoUser = new AWSCognito.CognitoUser({
        Username: username,
        Pool: userPool,
      });
      this._cognitoUser.authenticateUser(authenticationDetails, {});

**Comment by tannerabread** [comment]
Hi @muniramachandra15 I lost this issue for a while, but I just tried this and I'm not seeing the same results. I'll try to discuss with the team to see if this is something that **should** be supported
