### ISSUE TITLE
Hosted-UI issue when using with electron

### ISSUE THREAD

**Issue by evanrbowers** [aws-amplify/amplify-js#10275]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 12.5
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 2.20 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.18.3/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v14.18.3/bin/npm
  Browsers:
    Brave Browser: 104.1.42.97
    Chrome: 104.0.5112.101
    Firefox: 92.0
    Safari: 15.6
  npmPackages:
    @aws-amplify/auth: ^4.6.3 => 4.6.4 
    @aws-amplify/core: ^4.7.1 => 4.7.2 
    @date-io/date-fns: ^1.3.13 => 1.3.13 (2.14.0)
    @emotion/react: ^11.9.3 => 11.9.3 
    @emotion/styled: ^11.9.3 => 11.9.3 
    @fortawesome/fontawesome-svg-core: ^6.1.1 => 6.1.2 
    @fortawesome/free-brands-svg-icons: ^6.1.1 => 6.1.2 
    @fortawesome/pro-duotone-svg-icons: ^6.1.1 => 6.1.2 
    @fortawesome/pro-light-svg-icons: ^6.1.1 => 6.1.2 
    @fortawesome/pro-regular-svg-icons: ^6.1.1 => 6.1.2 
    @fortawesome/pro-solid-svg-icons: ^6.1.1 => 6.1.2 
    @fortawesome/pro-thin-svg-icons: ^6.1.1 => 6.1.2 
    @fortawesome/react-fontawesome: ^0.2.0 => 0.2.0 
    @mui/lab: ^5.0.0-alpha.92 => 5.0.0-alpha.92 
    @mui/material: ^5.9.2 => 5.9.2 
    @mui/styles: ^5.9.2 => 5.9.2 
    @mui/x-date-pickers: ^5.0.0-beta.3 => 5.0.0-beta.3 
    @rematch/core: ^2.0.0-next.6 => 2.2.0 
    @rematch/immer: ^1.2.0 => 1.2.0 
    @types/axios: ^0.14.0 => 0.14.0 
    @types/classnames: 2.2.9 => 2.2.9 
    @types/debug: ^4.1.5 => 4.1.5 
    @types/google.analytics: 0.0.41 => 0.0.41 
    @types/humanize-duration: ^3.18.0 => 3.18.1 
    @types/lodash.clonedeep: ^4.5.6 => 4.5.6 
    @types/lodash.debounce: ^4.0.6 => 4.0.6 
    @types/lodash.isequal: ^4.5.5 => 4.5.5 
    @types/luxon: ^1.26.5 => 1.26.5 
    @types/md5: ^2.2.0 => 2.3.0 
    @types/node: ^18.6.2 => 18.6.3 
    @types/react: ^18.0.15 => 18.0.15 
    @types/react-dom: ^18.0.6 => 18.0.6 
    @types/react-dropzone: ^5.1.0 => 5.1.0 
    @types/react-redux: ^7.1.24 => 7.1.24 
    @types/react-router-dom: ^5.3.3 => 5.3.3 
    @types/react-select: 4.0.2 => 4.0.2 
    @types/redux: ^3.6.0 => 3.6.0 
    @types/redux-logger: ^3.0.9 => 3.0.9 
    @types/seedrandom: ^3.0.2 => 3.0.2 
    @types/segment-analytics: 0.0.32 => 0.0.32 
    @types/socket.io-client: ^1.4.35 => 1.4.35 
    @types/validator: ^13.7.2 => 13.7.2 
    axios: ^0.21.2 => 0.21.4 
    classnames: 2.2.6 => 2.2.6 
    cross-env: ^6.0.3 => 6.0.3 
    date-fns: ^2.16.1 => 2.28.0 
    eslint: ^8.20.0 => 8.20.0 
    filesize: ^6.0.1 => 6.1.0 (8.0.7)
    humanize-duration: ^3.25.1 => 3.25.1 
    i18n-unused: ^0.8.0 => 0.8.0 
    i18next: ^21.8.16 => 21.8.16 
    i18next-browser-languagedetector: ^6.1.4 => 6.1.4 
    lodash.clonedeep: ^4.5.0 => 4.5.0 
    lodash.debounce: ^4.0.8 => 4.0.8 
    lodash.isequal: ^4.5.0 => 4.5.0 
    luxon: ^2.5.0 => 2.5.0 (1.28.0)
    md5: ^2.3.0 => 2.3.0 
    npm-run-all: 4.1.5 => 4.1.5 
    onchange: ^6.1.0 => 6.1.1 
    qrcode.react: ^1.0.1 => 1.0.1 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    react-dropzone: ^12.0.4 => 12.0.4 
    react-i18next: ^11.18.3 => 11.18.3 
    react-phone-input-2: ^2.14.0 => 2.15.0 
    react-redux: ^8.0.2 => 8.0.2 
    react-router-dom: ^5.1.2 => 5.3.3 
    react-scripts: ^5.0.1 => 5.0.1 
    react-select: ^4.0.2 => 4.1.0 
    react-string-replace: ^0.4.4 => 0.4.4 
    reaptcha: ^1.7.3 => 1.7.3 
    rebound: 0.1.0 => 0.1.0 
    reconnecting-websocket: ^4.4.0 => 4.4.0 
    redux: ^4.0.5 => 4.2.0 
    redux-logger: ^3.0.6 => 3.0.6 
    remote.it: ^0.48.1 => 0.48.1 
    screenfull: ^5.1.0 => 5.1.0 
    seedrandom: ^3.0.5 => 3.0.5 
    socket.io-client: 2.3.1 => 2.3.1 
    typescript: ^4.7.4 => 4.7.4 
    url: ^0.11.0 => 0.11.0 
    use-clipboard-copy: ^0.2.0 => 0.2.0 
    use-resize-observer: ^7.0.1 => 7.0.1 
    validator: ^13.7.0 => 13.7.0 
    webpack: ^5.74.0 => 5.74.0 
    zxcvbn: ^4.4.2 => 4.4.2 
  npmGlobalPackages:
    @aws-amplify/auth: 4.6.3
    @aws-amplify/core: 4.7.1
    @types/node: 17.0.12
    dotenv-cli: 5.1.0
    npm-check-updates: 12.2.0
    npm: 8.3.1
    nvm: 0.0.4
    serverless-domain-manager: 5.4.1
    serverless: 3.7.5
    ts-node: 10.4.0
    typescript: 4.5.5
    yarn: 1.22.19

```

</details>

### Describe the bug

There is in issue when using Hosted-UI with electron.  It appears the library is trying to push the redirect url on the history.  However, the history of the app is http:localhost but the redirect is an app name and path when using in electron.  This errors and prevents some final logic to execute including setting the "amplify-signin-with-hostedUI" key.  This then prevents the app from fully signing out via the hostedUI.  The library is also not removing the "amplify-signin-with-hostedUI" key after signout.

I've put together a fix for this issue and will be submitting shortly.

### Expected behavior

When signing out of app in electron.  You should also be signed out in the hosted ui.

### Reproduction steps

1. You need to run an app inside of an electron app that supports hosted-ui login (like google sign-in).
2. Sign in
3. Sign out
4. Should be signed out in hosted ui but you are not
5. Attempt to sign in again and you will not be given any options. You will just be directed back to the app as you are already signed in on the hosted ui

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by evanrbowers** [comment]
Created PR: https://github.com/aws-amplify/amplify-js/pull/10276

**Comment by abdallahshaban557** [comment]
Thank you @evanrbowers for submitting this PR! Our team is currently taking a look at it and we will get back to you!

**Comment by tannerabread** [comment]
Hi @evanrbowers 
Sorry for the delayed response on this, you are experiencing this with HostedUI, so to be clear you are using `Auth.federatedSignIn()`? And the issue is actually that you still navigate to the hosted UI, but when you click the `Continue with Google` button, you are not given the choice of which google account to use?

**Comment by evanrbowers** [comment]
Yes we are using federated sign in.  No, the issue is after you are being
directed back to the app after doing your federates sign in.  It's throwing
an error in the console and not completing its full sign in process.  This
leaves it in a state that does not recognize it used federated sign in.
When you go to sign out, amplify never calls signout in the hosted ui, so
the user stays signed in there.  There may be other things left incomplete
but the primary issue is "amplify-signin-with-hostedUI" never gets set in
local storage.  So on signout it does not call logout in the hosted ui.
Evan

**Comment by Meags27** [comment]
I think this is because the Hosted UI contains a one hour session separate from your app and if you login and logout within that hour, then login again, you will automatically login.

But if you waited an hour, then the Hosted UI session is cleared.

I tested this myself and I have this behaviour. I personally would prefer the session to clear in the Hosted UI but I don't control it.
