### ISSUE TITLE
AWSJSON is array type has a bug when fetching data

### ISSUE THREAD

**Issue by rkushkuley** [aws-amplify/amplify-js#10274]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

DataStore

### Amplify Categories

Not applicable

### Environment information

<details>

```
"@aws-amplify/datastore": "^3.11.3",
"aws-amplify": "^4.3.24",

```

</details>

### Describe the bug

When i had a datafield of column type awsjson is array, it returns different behaviors. When i save a list to a column - for ex. test: [1,2,3,4] it is saved in my datastore as an actual list. if i do obj.test[0] i get 1, if i do obj.test[1] i get 2 -  this behavior is expected. Once i refresh the page or once i pull clean data into datastore it , test is actually an array with a string element of my array ... for example test: ['[1,2,3,4]']. To get the data i must call the 0th element and json.parse it -> like this: Json.parse(test[0]).  

### Expected behavior

I expect the behavior to be consistent, ideally its an actual array but if not I would like it to be the same throughout the application. Either i always do json.parse(test[0]) to get the array or i just get test as an actual array. 

### Reproduction steps

1. Create a model with a field of type awsjson is array. 
2. Write to that field with an actual array [test, test, test]
3. Call that data an access it like an array
4. Refresh the page, and it will not be a signular element array with a string array inside of it in which you will have to parse.  

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Mobile Browser

Chrome

**Comment by chrisbonifacio** [comment]
Hi @rkushkuley 👋 thanks for raising this issue. Could you please share your GraphQL schema and code snippets where you are using DataStore to query for your array of values so that we may reproduce this issue?

**Comment by rkushkuley** [comment]
Thank you for the quick response. What version of amplify and datastore do you have?

I am querying and saving the same way you are. 

type Team @model @auth(rules: [{allow: owner}]) {
  id: ID!
  team_name: String
  team_users: [AWSJSON]
  user_info: AWSJSON
}

^ this is my graphql schema, do you have your list field as an [AWSJSON] or AWSJSON?

**Comment by chrisbonifacio** [comment]
oh okay, yeah our schema is different. my field is just AWSJSON.

```graphql
type Grocery @model @auth(rules: [{ allow: public }]) {
  id: ID!
  lists: AWSJSON
}
```

**Comment by rkushkuley** [comment]
Ok that makes sense thank you. Is this something that will be fixed in the future? It makes sense that AWSJSON is array should be an array not a string. For everyones benefit here is a helper function that I use currently. 

```
export function safeAWSJSONArrayQuery(list_obj) {
    try {
        return JSON.parse(list_obj[0])
    } catch (error) {
        return list_obj
    }
}
```

**Comment by chrisbonifacio** [comment]
> Yes the [AWSJSON] is the field im having issues. It is a single array but it is returning as a single element nested string array. Is this something that will be fixed in the future?

I think the issue you're running into when using [AWSJSON] type is a bug but, if you just need a single array as the value of the field, I would suggest changing the type to just AWSJSON. This way you won't have to parse the response.

Here you can see the difference in the way the fields are stored when I try to save a single array to both

```js
  async function addGrocery(grocery) {
    await DataStore.save(
      new Grocery({
        lists: ["milk", "bread", "eggs"],
        users: ["user1", "user2"],
      })
    );
  }
```

<img width="1257" alt="Screenshot 2022-09-02 at 12 29 43 PM" src="https://user-images.githubusercontent.com/16952986/188198267-eeceb05b-8716-474b-9197-f0370cd02c81.png">
