### ISSUE TITLE
Facebook login on ios is failing

### ISSUE THREAD

**Issue by hieunv12** [aws-amplify/amplify-js#10316]
I have followed the instructions on  (https://docs.amplify.aws/lib/auth/social/q/platform/js/#full-samples) page but only on android and ios side is having problem not getting login information from aws

**Comment by tannerabread** [comment]
Duplicate of #10315

**Comment by tannerabread** [comment]
Duplicate of https://github.com/aws-amplify/amplify-js/issues/10315
