### ISSUE TITLE
(aws-amplify-react-native): Federated Signin for react-native with Google and Facebook providers not login on ios

### ISSUE THREAD

**Issue by LogTime1h** [aws-amplify/amplify-js#10315]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

follow link:https://docs.amplify.aws/lib/auth/social/q/platform/js/#launch-social-web-ui-sign-in

### Describe the bug

1. On the app for Facebook login we are using Facebook SDK, after successful login will use Auth.federatedSignIn to login
2. After successful login with Auth.federatedSignIn:
  + App received the 'signIn' event
  + App receives about user information
  + Received successful login status with Facebook on AWS console
3. Problem: Can't get user info from GraphQL schema: "no current user"

### Expected behavior

Login success

### Reproduction steps

1. Setup IOS enviroment by link: https://docs.amplify.aws/lib/auth/social/q/platform/js/#launch-social-web-ui-sign-in
2. Click button to run:   await Auth.federatedSignIn({
        provider: CognitoHostedUIIdentityProvider.Facebook,
      });
3. Navigate to facebook page, perform login, navigate back to app
4. The response data of Hub.listen('auth') is "null", which causes error on IOS

### Code Snippet

import React, { useEffect, useState } from 'react';
import { Button, Linking, Text, View } from 'react-native';
import { Amplify, Auth, Hub } from 'aws-amplify';
import InAppBrowser from 'react-native-inappbrowser-reborn';
import awsconfig from './aws-exports';

async function urlOpener(url, redirectUrl) {
  await InAppBrowser.isAvailable();
  const { type, url: newUrl } = await InAppBrowser.openAuth(url, redirectUrl, {
    showTitle: false,
    enableUrlBarHiding: true,
    enableDefaultShare: false,
    ephemeralWebSession: false,
  });

  if (type === 'success') {
    Linking.openURL(newUrl);
  }
}

Amplify.configure({
  ...awsconfig,
  oauth: {
    ...awsconfig.oauth,
    urlOpener,
  },
});

function App() {
  const [user, setUser] = useState(null);

  useEffect(() => {
    Hub.listen('auth', ({ payload: { event, data } }) => {
      switch (event) {
        case 'signIn':
        case 'cognitoHostedUI':
          getUser().then(userData => setUser(userData));
          break;
        case 'signOut':
          setUser(null);
          break;
        case 'signIn_failure':
        case 'cognitoHostedUI_failure':
          console.log('Sign in failure', data);
          break;
      }
    });

    getUser().then(userData => setUser(userData));
  }, []);

  function getUser() {
    return Auth.currentAuthenticatedUser()
      .then(userData => userData)
      .catch(() => console.log('Not signed in'));
  }

  return (
    <View>
      <Text>User: {user ? JSON.stringify(user.attributes) : 'None'}</Text>
      {user ? (
        <Button title="Sign Out" onPress={() => Auth.signOut()} />
      ) : (
        <Button title="Federated Sign In" onPress={() => Auth.federatedSignIn()} />
      )}
    </View>
  );
}

export default App;

### Log output

<details>

```
// Put your logs below this line
The response data of Hub.listen('auth') is "null" on IOS.


```

</details>

### aws-exports.js

const awsmobile = {
  aws_project_region: '',
  aws_cognito_identity_pool_id: '',
  aws_cognito_region: '',
  aws_user_pools_id: '',
  aws_user_pools_web_client_id: '',
  oauth: {
    domain:
      '',
    scope: [
      'phone',
      'email',
      'openid',
      'profile',
      'aws.cognito.signin.user.admin',
    ],
    redirectSignIn:
      'myapp://',
    redirectSignOut:
      'myapp://',
    responseType: 'code',
  },
  federationTarget: 'COGNITO_USER_POOLS',
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: ['FACEBOOK', 'APPLE'],
  aws_cognito_signup_attributes: ['EMAIL'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  }
 
};

### Manual configuration

    redirectSignIn:
      'myapp://',
    redirectSignOut:
      'myapp://',
    responseType: 'code',

### Additional configuration

all

### Mobile Device

all

### Mobile Operating System

all

### Mobile Browser

all

### Mobile Browser Version

all

### Additional information and screenshots

all

**Comment by hieunv12** [comment]
+1

**Comment by abdallahshaban557** [comment]
@LogTime1h  - were you able to resolve your issue?

**Comment by LogTime1h** [comment]
1.
