### ISSUE TITLE
Random authentication failures from Cognito

### ISSUE THREAD

**Issue by spaternina** [aws-amplify/amplify-js#10320]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

DefineAuthChallenge_Authentication is returning NotAuthorizedException (Incorrect username or password) randomly when checkig username and password.

This is a intermitent behavior even when we are sending same username and passsword.

Below is the CloudTrail log for reference:
"eventSource": "cognito-idp.amazonaws.com",
"eventName": "RespondToAuthChallenge",
"userAgent": "aws-sdk-java/2.10.69 Linux/4.14.255-276-224.499.amzn2.aarch64 Substrate_VM/GraalVM_22.1.0_Java_11_CE Java/11.0.15 vendor/Oracle_Corporation io/sync http/UrlConnection",
"errorCode": "NotAuthorizedException",
"errorMessage": "Incorrect username or password.",

We're using SDK Java por the requests to Cognito.

### Expected behavior

Access token reponded sucessfully all the time when username and password are correct.

### Reproduction steps

We're using a lambda function to authenticate the users and the lamba function calls Cognito to the authentication requests.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by tannerabread** [comment]
Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
