### ISSUE TITLE
Reading AWS Cognito User Pool attributes of another user

### ISSUE THREAD

**Issue by vahdet** [aws-amplify/amplify-js#1034]
**[Feature Request]**

**Current behavior**
For authentication `Auth.currentAuthenticatedUser()` fits well with an AWS Cognito User Pool attached. to a MobileHub project. However, in Cognito User Pool, there are also [attributes](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html) for managing user profile e.g. `profile`, `picture`. If a user visits his/her **own profile page**; I **can** show up the those attributes by making use of `Auth.currentAuthenticatedUser()`; 

**Expected behavior**
I try to bring those attributes also for the other users of my site (for read-only access of course); but with AWS Amplify I could not find a way to do it. I mean, what if a user wants to visit **another user's profile page**? Can I use the `picture` attribute of the user of the visited account? Is there a way like `Cognito.getUserWithUsername('visited-user').attributes.picture` or so?

**Amplify version**
0.3.4

**Comment by luizdanieldesouza** [comment]
Hi, 

Did you find any alternative solution to this issue? I’m also facing the same

Dan

**Comment by vahdet** [comment]
I actually worked around it by moving the user info to a DynamoDB table with a Lambda function attached to the User Pool's [Post Confirmation Lambda Trigger](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-post-confirmation.html).

**Comment by vahdet** [comment]
@3rfan Actually I did not build a federated structure for my work. But my starting point was [this page](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html#cognito-user-identity-pools-working-with-aws-lambda-trigger-sources), the trigger source with value `PostConfirmation_ConfirmSignUp`. I have not seen an evident federated-sign-in (or even simple sign-in) trigger; but those are **user pool** triggers, if something is added/changed in your user pool; you're likely to have a chance. And finally, have look suffering from the same struggle as yours [here](https://stackoverflow.com/q/47655707/4636715) :)

**Comment by 3rfan** [comment]
@vahdet Ok, thx for the info! I think I will just send the user info to a Lambda function which creates me a DynamoDB user entry. This whole process should be a lot better described inside the Docs 😐

**Comment by harrysolovay** [comment]
> I actually worked around it by moving the user info to a DynamoDB table with a Lambda function attached to the User Pool's [Post Confirmation Lambda Trigger](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-post-confirmation.html).

^ this is the correct solution, but be weary of permissions. Aka., making all user profiles accessible to all users is uncommon.

Abstracting profile-sharing functionality into the lib is not within the scope of our present roadmap. However, we're always open to reviewing PRs!
