### ISSUE TITLE
vue + vite + pubsub issue with latest update

### ISSUE THREAD

**Issue by jens3911** [aws-amplify/amplify-js#10341]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

PubSub

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 21.74 GB / 31.27 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.17 - /usr/local/bin/npm
  Browsers:
    Chromium: 105.0.5195.102
    Firefox: 104.0
  npmPackages:
    @vitejs/plugin-vue: ^3.0.3 => 3.1.0 
    aws-amplify: ^4.3.35 => 4.3.35 
    vite: ^3.0.9 => 3.1.2 
    vue: ^3.2.38 => 3.2.39 
  npmGlobalPackages:
    @tailwindcss/language-server: 0.0.7
    @volar/server: 0.32.1
    live-server: 1.2.2
    neovim: 4.10.1
    npm-check-updates: 15.0.5
    sass: 1.53.0
    tree-sitter-cli: 0.20.6
    tree-sitter: 0.20.0
    typescript-language-server: 0.10.1
    typescript: 4.7.2
    vscode-langservers-extracted: 4.2.1

```

</details>

### Describe the bug

I tried to implement the Pubsub module in a project. however i had problems using it in the dev build. However, the error "AMQJS0010E WebSocket is not supported by this browser" always came up(when i run 'npm run build', everything works fine). 
Anyone have any Idea? I tried installing the seperated ws npm module, but the error persist.

So I tried to update amplify and Vite. However, this created a new error that seems to be related to the latest amplify update?
https://github.com/aws-amplify/amplify-js/pull/10298

After adding this line in the Code: 
'import { AWSIoTProvider } from '@aws-amplify/pubsub';'
This error comes up: 
'Uncaught TypeError: Object.setPrototypeOf: expected an object or null, got undefined'
even if you remove the line and restart the vite server, the error persists, you then have to delete the node module folder and reinstall it.

For faster investigation i reproduced the bug in a fresh vue + amplify setup:
https://github.com/jens3911/vue-test

### Expected behavior

Import AWSIoTProvider and use it as expected in the Doc.

### Reproduction steps

npm init vue@latest
npm install aws-amplify
npm i

Add to main.js
import { Amplify, Auth, Hub, PubSub } from 'aws-amplify'
import { AWSIoTProvider } from '@aws-amplify/pubsub';

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by tannerabread** [comment]
I was able to reproduce this issue consistently with the instructions provided.

It's possible you might have to add a polyfill to fix a `global` error
If so, add this above the `<script>` tag importing `main.js` in `index.html`
```html
<script type="module">
    if (window.global === undefined) {
      window.global = window
    }
</script>
```

**Comment by jens3911** [comment]
I tried your solution, but nothing changed, i also deleted node modules and reinstalled.
https://github.com/jens3911/vue-test/commit/ad496ad5ef20d0ccf2d871bd2a721e6b00ada7c7

When i set this version everything works fine
    "aws-amplify": "4.3.26",

**Comment by tannerabread** [comment]
@jens3911, sorry that wasn't meant to be a solution for you but rather a note for any of the engineers that look at this issue and run into the 'global' error

**Comment by tannerabread** [comment]
@stocaaro it seems to work on everything up until `aws-amplify@4.3.32`, this is the first one that breaks

![image](https://user-images.githubusercontent.com/30082936/191274972-dfb447dd-9f72-4c24-8622-3b938a812e52.png)

Check out [this repo](https://github.com/tannerabread/aws-amplify-10341) if you are having trouble reproducing on your own

**Comment by tannerabread** [comment]
> @tannerabread No Problem, It even helped me with my other problem: "AMQJS0010E WebSocket is not supported by this browser" Comes when i use amplify with vite(with webpack it works). because webpack is no longer maintained by vue, I'll continue to use vite. I had to run npm run build every time I want to use the PubSub module because npm run dev doesn't work because of the error. With this line in index.html I can use websockets in dev build too: <script type="module"> import WebSocket from 'isomorphic-ws' window.global = window window.global.WebSocket = WebSocket </script>
> 
> So thanks anyway :)

Glad I was able to help with something!

**Comment by stocaaro** [comment]
Hello,

I've been troubleshooting this issue yesterday and today. I have a [tested fix out for PR](https://github.com/aws-amplify/amplify-js/pull/10353).  I had attempted to resolve this in a [prior change](https://github.com/aws-amplify/amplify-js/pull/10298) that solved for one of the repro cases, but not all. I have tested this change for both vue and react reproduction cases and expect it to resolve all the the vite build issues related to pubsub access.

Thanks,
Aaron

**Comment by stocaaro** [comment]
The fix has been merged and will be available on the `unstable` tag shortly. The full release that you can auto-upgrade is expected to be out a week from tomorrow.

**Comment by abdallahshaban557** [comment]
We have now released the fix in our latest version. Please inform us if you are still facing an issue!

**Comment by renemroger** [comment]
@abdallahshaban557

I know this issue has been closed but I am facing the same issue. I am on version `5.0.4`.

**Comment by tannerabread** [comment]
@renemroger Did this issue only arise with 5.0.4?

**Comment by renemroger** [comment]
I just started using the library today so I am not sure. I can provide more details if needed

**Comment by tannerabread** [comment]
Hi @renemroger, more information would be great. Are you seeing this only when you import from the `pubsub` package? Are you getting the same error as the OP?

**Comment by renemroger** [comment]
I am using the latest version of vite and amplify and I was getting this error - "AMQJS0010E WebSocket is not supported by this browser".

I was able to fix using the script suggestion that someone posted but I was wondering if there is a way around it.

**Comment by jens3911** [comment]
I ended with this Solution, this works for me in dev and build mode of vite:
I add this in head tag of index.html

`    <% if(isDev){ %>
    <script type="module">
    import WebSocket from 'isomorphic-ws'
    window.global = window
    window.global.WebSocket = WebSocket
    </script>
    <% } %>
`
And use this Plugin for Vite for this + the window.global declaration:

`import { ViteEjsPlugin } from "vite-plugin-ejs";

export default defineConfig({
  plugins: [
    vue(),
    ViteEjsPlugin()
  ],
  resolve: {
    alias: {
      '@': resolve(__dirname, 'src'),
      './runtimeConfig': './runtimeConfig.browser'
    },
  },
  define: {
    'window.global': {},
  },
})`
