### ISSUE TITLE
Multiple Redirects Causes Empty Login

### ISSUE THREAD

**Issue by Zak-Guetter** [aws-amplify/amplify-js#10366]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
  System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 7.18 GB / 31.73 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (105.0.1343.42)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @aws-amplify/core: ^4.5.6 => 4.7.2
    @aws-sdk/client-s3: ^3.99.0 => 3.160.0 (3.6.1)
    @babel/core: ^7.18.0 => 7.18.13
    @react-native-async-storage/async-storage: ~1.17.3 => 1.17.10
    @react-native-community/netinfo: 8.2.0 => 8.2.0
    @react-native-picker/picker: 2.4.0 => 2.4.0 (1.16.8)
    @react-navigation/bottom-tabs: ^6.3.1 => 6.3.3
    @react-navigation/drawer: ^6.4.1 => 6.4.4
    @react-navigation/material-bottom-tabs: ^6.2.1 => 6.2.3
    @react-navigation/native-stack: ^6.6.2 => 6.8.0
    @types/react: ~17.0.21 => 17.0.49
    @types/react-native: ^0.64.24 => 0.64.26
    @types/react-native-vector-icons: ^6.4.12 => 6.4.12
    HelloWorld:  0.0.1
    amazon-cognito-identity-js: ^5.2.10 => 5.2.10
    aws-amplify: ^4.3.22 => 4.3.33
    aws-amplify-react-native: ^6.0.4 => 6.0.5
    expo: ^45.0.6 => 45.0.8
    expo-av: ~11.2.3 => 11.2.3
    expo-camera: ~12.2.0 => 12.2.0
    expo-image-picker: ~13.1.1 => 13.1.1
    expo-splash-screen: ~0.15.1 => 0.15.1
    expo-status-bar: ~1.3.0 => 1.3.0
    expo-updates: ^0.13.3 => 0.13.4
    expo-web-browser: ~10.2.1 => 10.2.1
    fbemitter: ^3.0.0 => 3.0.0
    fbjs: ^3.0.4 => 3.0.4
    hermes-inspector-msggen:  1.0.0
    isomorphic-fetch: ^3.0.0 => 3.0.0
    jest: ^26.6.3 => 26.6.3
    mime: ^3.0.0 => 3.0.0 (2.6.0, 1.6.0)
    node-fetch: ^3.2.4 => 3.2.10 (2.6.7)
    prop-types: ^15.8.1 => 15.8.1
    react: 17.0.2 => 17.0.2 (16.14.0)
    react-dom: 17.0.2 => 17.0.2
    react-hook-form: ^7.31.2 => 7.34.2
    react-native: 0.68.2 => 0.68.2
    react-native-camera-kit: ^12.1.0 => 12.1.0
    react-native-draggable-flatlist: ^3.1.1 => 3.1.2
    react-native-gesture-handler: ~2.2.1 => 2.2.1
    react-native-google-places-autocomplete: ^2.4.1 => 2.4.1
    react-native-maps: 0.30.2 => 0.30.2
    react-native-paper: ^4.12.1 => 4.12.4
    react-native-picker-select: ^8.0.4 => 8.0.4
    react-native-ratings: ^8.1.0 => 8.1.0
    react-native-reanimated: ~2.8.0 => 2.8.0
    react-native-safe-area-context: 4.2.4 => 4.2.4
    react-native-screens: ~3.11.1 => 3.11.1
    react-native-swipeable-item: ^2.0.2 => 2.0.9
    react-native-vector-icons: ^9.1.0 => 9.2.0
    react-native-web: 0.17.7 => 0.17.7
    react-select: ^5.3.2 => 5.4.0
    react-switch: ^6.0.0 => 6.1.0
    typescript: ~4.3.5 => 4.3.5
  npmGlobalPackages:
    @aws-amplify/cli: 9.1.0
    @expo/ngrok: 4.1.0
    eas-cli: 2.1.0
    expo-cli: 6.0.5

```

</details>

### Describe the bug

I am setting up OAuth on amplify and whenever I put in more than 1 redirect URI it works fine but returns a 400 error with the logins map empty - {cognito-idp.us-XXX-X.amazonaws.com/us-west-2_XXXXXXX: ""}. 

I am able to go through the authentication fine but when I return to my redirect URI that I programmatically chose it returns the 400 code. 

### Expected behavior

It should be returning the login to either URI's based on what redirect is chosen: 
http://localhost:19006/
https://example.com/

### Reproduction steps

npm install,
amplify init
setup auth with federation
get apple credentials 
assign multiple URI's
try to login with multiple URI's

### Code Snippet

example adjustment of aws-exports programmatically doesn't fix error - 

```javascript

import awsConfig from './src/aws-exports';
awsConfig.oauth.redirectSignIn = `${window.location.origin}/`;
awsConfig.oauth.redirectSignOut = `${window.location.origin}/`;

Amplify.configure(awsConfig);

Auth.federatedSignIn({ provider: 'SignInWithApple' });

```

### Log output

<details>

```

{
    "event": "customState_failure",
    "data": {
        "__type": "ValidationException",
        "name": "ValidationException",
        "$fault": "client",
        "$metadata": {
            "httpStatusCode": 400,
            "requestId": "e72c1abe-032d-42d0-8cdb-0fbd48fa2a33",
            "attempts": 1,
            "totalRetryDelay": 0
        }
    },
    "message": "A failure occurred when returning state"
}

```

</details>

### aws-exports.js

I can use token in place of code in responseType under the aws-exports file. However that is not a real solution as anytime I pull the back-end I will have to fix it. I have also tried programmatically assigning responseType to token but that doesn't change the outcome. It only changes it when its directly in the aws-exports

```javascript
const awsmobile = {
    aws_project_region: 'us-west-2',
    aws_cognito_identity_pool_id: 'us-west-XXXX',
    aws_cognito_region: 'us-west-2',
    aws_user_pools_id: 'XXX',
    aws_user_pools_web_client_id: 'XXXX',
    oauth: {
        domain: 'XXXX.auth.us-west-2.amazoncognito.com',
        scope: ['phone', 'email', 'openid', 'profile', 'aws.cognito.signin.user.admin'],
        redirectSignIn: 'http://localhost:19006/,https://www.example.app/',
        redirectSignOut: 'http://localhost:19006/,https://www.example.app/',
        responseType: 'code',
    },
    federationTarget: 'COGNITO_USER_POOLS',
    aws_cognito_username_attributes: ['EMAIL'],
    aws_cognito_social_providers: ['APPLE'],
    aws_cognito_signup_attributes: ['EMAIL'],
    aws_cognito_mfa_configuration: 'OFF',
    aws_cognito_mfa_types: ['SMS'],
    aws_cognito_password_protection_settings: {
        passwordPolicyMinLength: 8,
        passwordPolicyCharacters: [],
    },
    aws_cognito_verification_mechanisms: ['EMAIL'],
    aws_appsync_graphqlEndpoint:
        'https://XXXXappsync-api.us-west-2.amazonaws.com/graphql',
    aws_appsync_region: 'us-west-2',
    aws_appsync_authenticationType: 'API_KEY',
    aws_appsync_apiKey: 'XXXXX,
    aws_user_files_s3_bucket: 'XXXX',
    aws_user_files_s3_bucket_region: 'us-west-2',
};
```

**Comment by nadetastic** [comment]
Hi @Zak-Guetter 👋,

I haven't been able to reproduce this issue, however, I'd like to confirm your experience - when attempting to federate, you are directed to the Apple Sign In page where you successfully enter your credentials, however on redirect back to your APP you get the 400 code?

If so could you share the full message of any errors that you see?

Also I am assuming that you are handling the multiple redirect URIs in a manner such as [described in the docs](
https://docs.amplify.aws/lib/auth/social/q/platform/js/#configure-auth-category:~:text=Note%3A%20if%20you%20have%20multiple%20redirect%20URI%20inputs%2C%20you%27ll%20need%20to%20handle%20both%20of%20them%20where%20you%20configure%20your%20Amplify%20project.%20For%20example%3A
).

**Comment by Zak-Guetter** [comment]
Yes, I go to the apple auth page and successfully login to apple or any other federated login (I tried with AzureAD too) and I have tried following the docs to the tee but it still got me to the same error. I know the doc's talk about the expo-browser plugin but I am currently testing via web so that shouldn't matter and it was working with just one URI. 

![Screenshot 2022-09-28 124429](https://user-images.githubusercontent.com/61286318/192853046-c05402e4-5322-4059-a8ef-83567e5cf98e.png)
![Screenshot 2022-09-28 124623](https://user-images.githubusercontent.com/61286318/192853052-8ca002c7-d265-4792-98ab-e5fcb2cfee74.png)
![Screenshot 2022-09-28 124735](https://user-images.githubusercontent.com/61286318/192853055-ddc4f0d4-a612-4eeb-ae02-9fdc0606111e.png)

**Comment by Zak-Guetter** [comment]
So I fixed this problem by rebuilding my Auth from the ground up. I initially must have setup OAuth with the authorization code grant and for some reason the CLI would not allow me to change it to implicit. Nor would it change if I updated the Cognito to only use Implicit.

Thanks for your help @nadetastic !
