### ISSUE TITLE
Expand IAuthDevice type to include more device info (similar to the AWSAuthDevice type in amplify-ios)

### ISSUE THREAD

**Issue by ryantsang92** [aws-amplify/amplify-js#10360]
### Is this related to a new or existing API?

Authentication

### Is this related to another service?

amplify-ios

### Describe the feature you'd like to request

Right now, the fetchDevices method in this library returns an array of IAuthDevice.  If my understanding is correct, based on [this code](https://github.com/aws-amplify/amplify-js/blob/06504e649068f01b85392373fdf80e2ed2a6cada/packages/auth/src/Auth.ts#L2690) we're actually getting the entire device info but returning just the device key and the device name?  I'd like to see this method return something similar to what the [fetchDevices method in amplify-ios](https://github.com/aws-amplify/amplify-ios/blob/02ac2ba5c417883ea90f3d59b3cd28e63d2a1d39/AmplifyPlugins/Auth/AWSCognitoAuthPlugin/ClientBehavior/AWSCognitoAuthPlugin%2BDeviceBehavior.swift) returns so that there's at least some consistency between the two libraries

### Describe the solution you'd like

Modify the [fetchDevices](https://github.com/aws-amplify/amplify-js/blob/06504e649068f01b85392373fdf80e2ed2a6cada/packages/auth/src/Auth.ts#L2690) method so that more device info is returned, similar to the [AWSAuthDevice type](https://github.com/aws-amplify/amplify-ios/blob/3f700ac8b16dbfed3d7d40b461d508d6e0f7d1ab/AmplifyPlugins/Auth/AWSCognitoAuthPlugin/Models/AWSAuthDevice.swift) in the amplify-ios library

### Describe alternatives you've considered

I've considered saving a timestamp to my database when a user logs into my app but this doesn't work when a user accesses the app through multiple different devices

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by ryantsang92** [comment]
Hello, is there any update to this?

**Comment by ryantsang92** [comment]
Hello, is there any update to this? I'm happy to explain further, if need be

**Comment by ryantsang92** [comment]
Hello, is there any update to this? I'm happy to explain further, if need be

**Comment by tannerabread** [comment]
Hi @ryantsang92 
Sorry that you have had no response on this issue up until now. I believe I understand the requirements of what you want.

I think this is good feedback and I will make sure it gets looked at by the team. I can't guarantee a timeline on when it will get accomplished but I will make sure we speak about it soon and will update this issue when I know more.

Thank you for your patience

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.  

Feel free to review the new new [fetchDevices](https://docs.amplify.aws/react/build-a-backend/auth/remember-device/#fetch-devices) API and let us know if there are any further questions or feedback.  Thanks.
