### ISSUE TITLE
Registration requires a phone number as a username. Although "Email or Phone Number" was selected when "amplify add auth"

### ISSUE THREAD

**Issue by anyaokpesten** [aws-amplify/amplify-js#10381]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

Authentication

### Environment information

<details>
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 94.16 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Safari: 15.2
  npmPackages:
    @aws-amplify/ui-components: ^1.9.0 => 1.9.1 
    @vitejs/plugin-vue: ^1.9.3 => 1.9.4 
    @vitejs/plugin-vue-jsx: ^1.2.0 => 1.2.0 
    amazon-cognito-identity-js: ^5.2.1 => 5.2.1 
    amplify-ui-components-loader:  undefined ()
    aws-amplify: ^4.3.36 => 4.3.3 
    aws-sdk: ^2.1223.0 => 2.1048.0 
    axios: ^0.27.2 => 0.24.0 (0.21.4)
    click-outside-vue3: ^4.0.1 => 4.0.1 
    graphql: ^16.0.1 => 16.2.0 (14.0.0)
    graphql-tag: ^2.12.6 => 2.12.6 
    less: ^4.1.2 => 4.1.2 
    normalize.css: ^8.0.1 => 8.0.1 
    stripe: ^8.186.1 => 8.186.1 
    typescript: ^4.4.3 => 4.4.4 
    uuid: ^3.4.0 => 3.4.0 (3.3.2, 8.3.2)
    vite: ^2.6.4 => 2.6.12 
    vue: ^3.2.16 => 3.2.20 
    vue-cookie-next: ^1.3.0 => 1.3.0 
    vue-final-modal: ^3.4.3 => 3.4.3 
    vue-router: ^4.0.11 => 4.0.12 
    vue-tsc: ^0.3.0 => 0.3.0 
    vuex: ^4.0.2 => 4.0.2 
  npmGlobalPackages:
    @aws-amplify/cli: 9.1.0
    corepack: 0.10.0
    localtunnel: 2.0.2
    npm: 8.11.0
    serverless: 2.69.1
    yarn: 1.22.19
</details>

### Describe the bug

InvalidParameterException: Username should be a phone number.

### Expected behavior

Expected successful registration via email

### Reproduction steps

<img width="760" alt="Screenshot 2022-09-28 at 17 24 26" src="https://user-images.githubusercontent.com/106517182/192811252-af66262c-13ff-46dc-9899-c0bde19be8d9.png">

1. I chose an email address or a phone number, as it is written that it will help to register using these values (shown on the screen)
2. call the signUp function

### Code Snippet

```javascript

let poolData = {
  UserPoolId: COGNITO_IDENTITY_POOL_ID,
  ClientId: COGNITO_CLIENT_ID
};
let userPool = new AmazonCognitoIdentity.CognitoUserPool(poolData);
const email = "test@gmail.com"
const password = "test@gmail.com"

function start(){
  let attributeList = [];
  let dataEmail = {
    Name: 'email',
    Value: email,
  };
  
  let attributeEmail = new AmazonCognitoIdentity.CognitoUserAttribute(dataEmail);
  attributeList.push(attributeEmail);
  let username = email
  registration(username, password, attributeList)
  .then(result => console.log(result))
  .catch(err => console.log(err))
}


function registration(username, password, attributeList){
  return new Promise(async (resolve, reject )=>{
    userPool.signUp(username, password, attributeList, attributeList, async (err,result) => {
    if (err) {
      console.log(err.message);
      reject(err);
    }
    let cognitoUser = result.userSub;
    await addUserInDb(email, cognitoUser )
    resolve(result)
    })
  })
}

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by nadetastic** [comment]
Hi @anyaokpesten 👋,

Thanks for opening this issue. Out of curiosity, since it looks like you are using `amazon-cognito-identity-js`, is there a requirement/reason for doing so and not Amplify Auth?

**Comment by nadetastic** [comment]
@anyaokpesten following up on this, we have created a streamlined experience for our developers needing to use Authentication with Cognito using the Authentication library from Amplify. You can opt in to use just the [JS library without the Amplify CLI](https://docs.amplify.aws/lib/auth/start/q/platform/js/#re-use-existing-authentication-resource) (https://docs.amplify.aws/lib/auth/start/q/platform/js/#re-use-existing-authentication-resource) if you feel like 
that would be better for your use case.

While we do provide some occasional fixes/upgrades to the cognito-identity-js library, we are planning on deprecating
that package in the near future.

**Comment by anyaokpesten** [comment]
> https://docs.amplify.aws/lib/auth/start/q/platform/js/#re-use-existing-authentication-resource

habitual approach for external scripts to fill with test data

**Comment by anyaokpesten** [comment]
> @anyaokpestenследуя этому, мы создали упрощенный интерфейс для наших разработчиков, которым необходимо использовать аутентификацию с Cognito, используя библиотеку аутентификации от Amplify. Вы можете выбрать использование только [библиотеки JS без Amplify CLI](https://docs.amplify.aws/lib/auth/start/q/platform/js/#re-use-existing-authentication-resource) ( https://docs.amplify.aws/lib/auth/start/q/platform/js/#re-use-existing-authentication-resource ), если чувствую , что это было бы лучше для вашего варианта использования.
> 
> Хотя мы время от времени предоставляем некоторые исправления/обновления библиотеки cognito-identity-js, в ближайшем будущем мы планируем прекратить поддержку этого пакета.

Thanks
