### ISSUE TITLE
React application not working when cookies are disabled

### ISSUE THREAD

**Issue by ParulSharma2622** [aws-amplify/amplify-js#10396]
We have a react application which is hosted on AWS amplify and running absolutely fine.

But it doesn't work when Cookies are disabled in the browser. 

Attaching a screenshot for your reference. Please note, we are using AWS lambda function and API gateway to request data from some third party API's and AWS IAM is the authorization mode for our graphQL API's.

Please suggest a way out, so our application can work even when cookies are disabled in the browser settings.

Here is the app details :
App Id : d2ye14uucmhrvd
App region : ap-southeast-2

![Screenshot_227](https://user-images.githubusercontent.com/69511562/193221388-28afba75-58d7-42b4-a178-2854554d3d1c.png)

**Comment by tannerabread** [comment]
hi :wave: @ParulSharma2622 
just to clarify, you are using some Authentication on the front-end of this app?

Amplify stores data/user-info in localStorage and currently there is no way to enable/disable web storage independently of cookies in Chrome/Firefox

**Comment by tannerabread** [comment]
I am going to close this as disabling cookies/localStorage separately is not possible in chrome/firefox and Amplify stores data in localStorage. Feel free to comment if you feel this is not resolved so that we can re-open the issue and assist you
