### ISSUE TITLE
getSession automatically update idToken when expire

### ISSUE THREAD

**Issue by Nut41tank** [aws-amplify/amplify-js#10407]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 34.73 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Edge: 105.0.1343.53
    Firefox: 104.0.2
    Safari: 16.0
  npmGlobalPackages:
    corepack: 0.10.0
    npm: 8.11.0
    yarn: 1.22.19

```

</details>

### Describe the bug

when call cognito.getSession is automatically update local storage token if expire
-> https://www.npmjs.com/package/amazon-cognito-identity-js

### Expected behavior

local storage token update when call cognitoUser.refreshSession only

### Reproduction steps

1. call getSession

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by nadetastic** [comment]
Hi @Nut41tank 👋,

Thanks for opening this issue. Out of curiosity, is there a requirement/reason to use `amazon-cognito-identity-js` and not Amplify Auth?

**Comment by nadetastic** [comment]
@Nut41tank following up on this - We have created a streamlined experience for our developers needing to use Authentication with Cognito using the Authentication library from Amplify. You can opt in to use just the [JS library without the Amplify CLI](https://docs.amplify.aws/lib/auth/start/q/platform/js/#re-use-existing-authentication-resource) (https://docs.amplify.aws/lib/auth/start/q/platform/js/#re-use-existing-authentication-resource) if you feel like that would be better for your use case.

While we do provide some occasional fixes/upgrades to the cognito-identity-js library, we are planning on deprecating
that package in the near future.
