### ISSUE TITLE
custom fetch implementation isn't passed to amazon-cognito-identity-js

### ISSUE THREAD

**Issue by JoshBarr** [aws-amplify/amplify-js#10436]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>
```
# N/A
```
</details>

### Describe the bug

`Auth.configure` accepts a custom `fetch`, however the `amazon-cognito-identity-js` package uses `isomorphic-fetch` directly. 

See the implementation here:
https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/src/Client.js#L91

Because of this, it's not possible to pass an `AbortSignal` to fetch requests initiated by Auth, that rely on methods in `amazon-cognito-identity-js`. 

### Expected behavior

Ideally all async methods in Auth would accept a signal, for instance:
```js
const abort = new AbortController();
await Auth.currentAuthenticatedUser({ bypassCache: true, signal: abort.signal })
```

If the custom `fetch` property was respected, then we could work around the missing signals with a custom implementation:
```js
const abort = new AbortController();
function customFetchImpl(input, init) {
  init.signal = abort.signal;
  return window.fetch(input, init);
}

Auth.configure({
    // ...other config
    fetch: customFetchImpl,
  });
```

Currently, this workaround is not possible.

### Reproduction steps

1. Configure Auth with a custom fetch:

```js
function customFetch(input, init) {
  throw new Error("expect custom fetch to throw");
}

Auth.configure({
    // ...other config
    authenticationFlowType: "USER_PASSWORD_AUTH",
    fetch: customFetchImpl,
  });
```

2. Initiate requests that use `amazon-cognito-identity-js`
```js
const user = await Auth.currentAuthenticatedUser({ bypassCache: true })
const session = await Auth.userSession(user);
```

3. Notice that the custom fetch implementation is not invoked

### Code Snippet

```javascript
See above
```

### Log output

<details>
```
// Put your logs below this line
// N/A
```
</details>

**Comment by chrisbonifacio** [comment]
Hi @JoshBarr 👋 A little confused by this issue. Looking at the current [AuthOptions type](https://github.com/aws-amplify/amplify-js/blob/c222d226dc1abba33a4045e62f4d608d0541fceb/packages/auth/src/types/Auth.ts#L40), it doesn't seem we support a custom fetch implementation. 

I can label this a feature request but I'm curious to know where you might've seen that this was an already supported feature?

**Comment by nadetastic** [comment]
Hi @JoshBarr following up on this - as @chrisbonifacio mentioned, configuring Auth with a custom fetch is not currently supported. Based on your use case, we can mark this as a feature request. Also, I'd like to understand where you might've seen that this was an already supported feature.

Thanks!

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
