### ISSUE TITLE
authenticationFlowType : CUSTOM_AUTH returns invalid authentication

### ISSUE THREAD

**Issue by zensim** [aws-amplify/amplify-js#10447]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
 System:
    OS: Linux 4.14 Amazon Linux AMI 2018.03
    CPU: (1) x64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
    Memory: 523.70 MB / 985.18 MB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.1/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
  npmPackages:
    aws-amplify: ^1.0.0 => 1.1.9 
    aws-amplify-react: ^1.0.0 => 1.0.8 
    benchmark-uuid:  undefined ()
    esri-loader: ^2.2.0 => 2.5.0 
    normalize.css: ^8.0.0 => 8.0.0 
    react: ^16.2.0 => 16.6.0 
    react-dom: ^16.2.0 => 16.6.0 
    react-router-dom: ^4.2.2 => 4.3.1 
    react-scripts: 1.1.1 => 1.1.1 
    uuid: ^3.2.1 => 3.3.2 (3.1.0, 2.0.3)
  npmGlobalPackages:
    @aws-amplify/cli: 10.0.0
    cdk: 2.44.0
    coffeescript: 2.7.0
    corepack: 0.12.1
    esformatter: 0.11.3
    js-beautify: 1.14.6
    npm: 8.15.0
    prettier: 2.7.1
    typescript: 3.7.5
    yarn: 1.22.19

```

</details>

### Describe the bug

Hi,

I keep getting "invalid authentication.." message when using CUSTOM_AUTH to do MFA using Cognito via Lambda triggers. I got my define, createauth and verify lambdas. All other authentication types work.
I also looked at the issue (similar) below which has been closed with no fix.
https://github.com/aws-amplify/amplify-js/issues/3215

I am using React with amplify. My user pool is configured correctly for CUTOM_AUTH.
I get this in the Auth.signIn() when I try to sign in an existing user. If I change to any other authentication like USER_SRP_AUTH or even leaving it blank or removing it completly in the config works.

Please let me know how to get CUSTOM_AUTH working for custom_challege

Thanks

### Expected behavior

Custom_challenge to be triggered, after passwd validation, cognito lambda trigger to send MFA code in the email to the user.
User enters the MFA code, lambda verify triggers validates the MFA code.

### Reproduction steps

1. reference { auth } from 'aws-amplify'
2. set the authenticationFlowType: 'CUSTOM_AUTH' in amplify.config.js
3. use Auth.signIn()

### Code Snippet

```javascript
// Put your code below this line.
amplify.config.js:
const awsConfig = {
    Auth: {
        identityPoolId: 'ur user identity pool id', // example: 'us-east-2:c85f3c18-05fd-4bb5-8fd1-e77e7627a99e'
        region: 'us-east-1', // example: 'us-east-2'
        userPoolId: 'ur user pool id', // example: 'us-east-2_teEUQbkUh'
        authenticationFlowType: 'CUSTOM_AUTH', //added after for custom_auth MFA
        //AuthFlow:'CUSTOM_AUTH',
        userPoolWebClientId: 'ur app client id' // example: '3k09ptd8kn8qk2hpk07qopr86'
    }
}

export default awsConfig;


SignIn.js:
async onSubmitForm(e) {
    e.preventDefault();
    try {
        console.log('entering signin');
        
        const userObject = await Auth.signIn(
            this.state.email.replace(/[@.]/g, '|'),
            this.state.password
        );
        console.log('userObject', userObject);
        if (userObject.challengeName) {
            // Auth challenges are pending prior to token issuance
            this.setState({ userObject, stage: 1 });
        } else {
            // No remaining auth challenges need to be satisfied
            const session = await Auth.currentSession();
            // console.log('Cognito User Access Token:', session.getAccessToken().getJwtToken());
            console.log('Cognito User Identity Token:', session.getIdToken().getJwtToken());
            // console.log('Cognito User Refresh Token', session.getRefreshToken().getToken());
            this.setState({ stage: 0, email: '', password: '', code: '' });
            this.props.history.replace('/app');
        }
    } catch (err) {
        alert(err.message);
        console.error('Auth.signIn(): ', err);
    }
  }


export default withRouter(SignIn);
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Mobile Browser Version

none

### Additional information and screenshots

using chrome

**Comment by zensim** [comment]
DefineAuth Lambda code (Node16x)
exports.handler = async (event) => {
        //console.log("entering define challenge", event)
        if (event.request.session && event.request.session.length === 1
            && event.request.session[0].challengeName === 'SRP_A'
            && event.request.session[0].challengeResult === true) {
            //SRP_A is the first challenge, this will be implemented by cognito. Set next challenge as PASSWORD_VERIFIER.
            event.response.issueTokens = false;
            event.response.failAuthentication = false;
            event.response.challengeName = 'PASSWORD_VERIFIER';
            
        } else if (event.request.session && event.request.session.length === 2
            && event.request.session[1].challengeName === 'PASSWORD_VERIFIER'
            && event.request.session[1].challengeResult === true) {
            //If password verification is successful then set next challenge as CUSTOM_CHALLENGE.
            event.response.issueTokens = false;
            event.response.failAuthentication = false;
            event.response.challengeName = 'CUSTOM_CHALLENGE';
            
        } else if(event.request.session && event.request.session.length === 3 
            && event.request.session[2].challengeName === 'CUSTOM_CHALLENGE'  
            && event.request.session[2].challengeResult === true){
            event.response.issueTokens = true;
            event.response.failAuthentication = false;
            
        }else if (event.request.session && event.request.session.length >= 5
            && event.request.session.slice(-1)[0].challengeName === 'CUSTOM_CHALLENGE'
            && event.request.session.slice(-1)[0].challengeResult === false) {
            //The user has exhausted 3 attempts to enter correct otp.
            event.response.issueTokens = false;
            event.response.failAuthentication = true;
            
        } else if (event.request.session  && event.request.session.slice(-1)[0].challengeName === 'CUSTOM_CHALLENGE'
            && event.request.session.slice(-1)[0].challengeResult === true) {
            //User entered the correct OTP. Issue tokens.
            event.response.issueTokens = true;
            event.response.failAuthentication = false;
            
        } else {
            //user did not provide a correct answer yet.
            event.response.issueTokens = false;
            event.response.failAuthentication = false;
            event.response.challengeName = 'CUSTOM_CHALLENGE';
        }

        return event;
};


CreateAuth lambda:
exports.handler = async (event) => {

    const crypto = require('crypto')
    const aws = require('aws-sdk')
    
    let verificationCode = ""; 
    //Only called once after SRP_A and PASSWORD_VERIFIER challenges. Hence session.length == 2
    if (event.request.session.length === 2) {

        verificationCode = crypto.randomBytes(3).toString('hex');
        const mailRequest = {
            Source: 'uxkaruppiah@torchmarkcorp.com', //ID Configured in SES as the source email id
            Destination: {
                ToAddresses: [
                    event.request.userAttributes["email"]
                ]
            },
            Message: {
                Subject: {
                    Data: 'WildRydes-OTP'
                },
                Body: {
                    Text: {
                        Data: 'Your password for secure login is ' + verificationCode
                    }
                }
            }
        }

        const ses = new aws.SES();
        await ses.sendEmail(mailRequest).promise();
      
    } else {
        //if the user makes a mistake, we utilize the verification code from the previous session so that the user can retry.
        const previousChallenge = event.request.session.slice(-1)[0];
        verificationCode = previousChallenge.challengeMetadata;
    }

    //add to privateChallengeParameters. This will be used by verify auth lambda.
    console.log(verificationCode)
    event.response.privateChallengeParameters = {
        "verificationCode": verificationCode
    };

    //add it to session, so its available during the next invocation.
    event.response.challengeMetadata = verificationCode;

    return event;

};


verifyauth:

exports.handler = async (event) => {
    const expectedAnswer = event.request.privateChallengeParameters["verificationCode"];
    if (event.request.challengeAnswer === expectedAnswer) {
        event.response.answerCorrect = true;

    } else {
        event.response.answerCorrect = false;

    }
    return event;
};

**Comment by zensim** [comment]
what I am seeing in amplifyjs/authjs file:
    AuthClass.prototype.signInWithoutPassword = function (username) {
        var _this = this;
        var user = this.createCognitoUser(username);
        user.setAuthenticationFlowType('CUSTOM_AUTH');
        var authDetails = new amazon_cognito_identity_js_1.AuthenticationDetails({
            Username: username
        });
        return new Promise(function (resolve, reject) {
            user.initiateAuth(authDetails, _this.authCallbacks(user, resolve, reject));
        });
    };

AuthClass.prototype.signInWithPassword = function (username, password) {
        var _this = this;
        var user = this.createCognitoUser(username);
        var authDetails = new amazon_cognito_identity_js_1.AuthenticationDetails({
            Username: username,
            Password: password
        });
        return new Promise(function (resolve, reject) {
            user.authenticateUser(authDetails, _this.authCallbacks(user, resolve, reject));
        });
    };

**Comment by zensim** [comment]
signInWithPassword()  does not have the
user.setAuthenticationFlowType('CUSTOM_AUTH');

**Comment by zensim** [comment]
SignIn.js in the client side:

  async onSubmitForm(e) {
    e.preventDefault();
    try {
        console.log('entering signin');
        
        const userObject = await Auth.signIn(
            this.state.email.replace(/[@.]/g, '|'),
            this.state.password
        );
        console.log('userObject', userObject);
        if (userObject.challengeName) {
            // Auth challenges are pending prior to token issuance
            this.setState({ userObject, stage: 1 });
        } else {
            // No remaining auth challenges need to be satisfied
            const session = await Auth.currentSession();
            // console.log('Cognito User Access Token:', session.getAccessToken().getJwtToken());
            console.log('Cognito User Identity Token:', session.getIdToken().getJwtToken());
            // console.log('Cognito User Refresh Token', session.getRefreshToken().getToken());
            this.setState({ stage: 0, email: '', password: '', code: '' });
            this.props.history.replace('/app');
        }
    } catch (err) {
        alert(err.message);
        console.error('Auth.signIn(): ', err);
    }
  }

  async onSubmitVerification(e) {
    e.preventDefault();
    try {
       
        //const data = await Auth.confirmSignIn(
        const data = await Auth.sendCustomChallengeAnswer(
        this.state.userObject,
        this.state.code
        );
        console.log('Cognito User Data:', data);
        const session = await Auth.currentSession();
        // console.log('Cognito User Access Token:', session.getAccessToken().getJwtToken());
        console.log('Cognito User Identity Token:', session.getIdToken().getJwtToken());
        // console.log('Cognito User Refresh Token', session.getRefreshToken().getToken());
        this.setState({ stage: 0, email: '', password: '', code: '' });
        this.props.history.replace('/app');
    } catch (err) {
        alert(err.message);
        console.error('Auth.confirmSignIn(): ', err);
    }
  }

**Comment by cwomack** [comment]
Hello, @zensim 👋.   Were your lambda triggers set up via the CLI upon initial addition of Auth?

**Comment by cwomack** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested so we can re-open this issue and be better able to assist you.

Thank you!
