### ISSUE TITLE
the amount of returned data does not meet the LIMIT

### ISSUE THREAD

**Issue by anyaokpesten** [aws-amplify/amplify-js#10448]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

GraphQL API

### Environment information

<details>

  System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 115.92 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 106.0.5249.103
    Safari: 15.2
  npmPackages:
    @asseinfo/react-kanban: ^2.2.0 => 2.2.0 
    @hookform/resolvers: ^2.8.10 => 2.9.7 
    @hookform/resolvers/ajv:  1.0.0 
    @hookform/resolvers/class-validator:  1.0.0 
    @hookform/resolvers/computed-types:  1.0.0 
    @hookform/resolvers/io-ts:  1.0.0 
    @hookform/resolvers/joi:  1.0.0 
    @hookform/resolvers/nope:  1.0.0 
    @hookform/resolvers/superstruct:  1.0.0 
    @hookform/resolvers/typanion:  1.0.0 
    @hookform/resolvers/vest:  1.0.0 
    @hookform/resolvers/yup:  1.0.0 
    @hookform/resolvers/zod:  1.0.0 
    @reduxjs/toolkit: ^1.8.1 => 1.8.3 
    @reduxjs/toolkit-query:  1.0.0 
    @reduxjs/toolkit-query-react:  1.0.0 
    @testing-library/jest-dom: ^5.16.4 => 5.16.4 
    @testing-library/react: ^13.1.1 => 13.3.0 
    @testing-library/user-event: ^13.5.0 => 13.5.0 
    amazon-cognito-identity-js: ^5.2.1 => 5.2.10 
    aws-amplify: ^4.3.20 => 4.3.29 
    aws-sdk: ^2.1033.0 => 2.1185.0 
    buffer: ^6.0.3 => 6.0.3 (4.9.2)
    class-names: ^1.0.0 => 1.0.0 
    classnames: ^2.3.1 => 2.3.1 
    crypto-browserify: ^3.12.0 => 3.12.0 
    draft-js: ^0.11.7 => 0.11.7 
    eslint: ^8.13.0 => 8.21.0 
    eslint-config-prettier: ^8.5.0 => 8.5.0 
    eslint-plugin-jsx-a11y: ^6.5.1 => 6.6.1 
    eslint-plugin-prettier: ^4.0.0 => 4.2.1 
    eslint-plugin-react-hooks: ^4.4.0 => 4.6.0 
    husky: ^7.0.4 => 7.0.4 
    joi: ^17.6.0 => 17.6.0 
    lint-staged: ^12.3.8 => 12.5.0 
    marked: ^4.0.16 => 4.0.18 
    moment: ^2.29.3 => 2.29.4 
    node-fetch: ^2.6.7 => 2.6.7 
    node-sass: ^7.0.1 => 7.0.1 
    prettier: ^2.6.2 => 2.7.1 
    process: ^0.11.10 => 0.11.10 
    prop-types: ^15.8.1 => 15.8.1 
    react: ^18.0.0 => 18.2.0 
    react-app-rewired: ^2.2.1 => 2.2.1 
    react-calendar: ^3.7.0 => 3.7.0 
    react-colorful: ^5.5.1 => 5.5.1 
    react-dom: ^18.0.0 => 18.2.0 
    react-error-boundary: ^3.1.4 => 3.1.4 
    react-grid-layout: ^1.3.4 => 1.3.4 
    react-hook-form: ^7.30.0 => 7.34.0 
    react-images-viewer: ^1.7.1 => 1.7.1 
    react-redux: ^8.0.0 => 8.0.2 (7.2.8)
    react-resizable: ^3.0.4 => 3.0.4 
    react-router-dom: ^6.3.0 => 6.3.0 
    react-scripts: 5.0.1 => 5.0.1 
    react-tabs: ^5.1.0 => 5.1.0 
    react-textarea-autosize: ^8.3.4 => 8.3.4 
    react-transition-group: ^4.4.2 => 4.4.5 (2.9.0)
    react-transition-group/CSSTransition:  undefined ()
    react-transition-group/ReplaceTransition:  undefined ()
    react-transition-group/SwitchTransition:  undefined ()
    react-transition-group/Transition:  undefined ()
    react-transition-group/TransitionGroup:  undefined ()
    react-transition-group/TransitionGroupContext:  undefined ()
    react-transition-group/config:  undefined ()
    redux: ^4.2.0 => 4.2.0 
    sanitize-html: ^2.7.0 => 2.7.1 
    stream-browserify: ^3.0.0 => 3.0.0 
    textarea-markdown-editor: ^1.0.1 => 1.0.1 
    uniqid: ^5.4.0 => 5.4.0 
    util: ^0.12.4 => 0.12.4 
    web-vitals: ^2.1.4 => 2.1.4 
    webpack: ^5.72.0 => 5.74.0 
    yup: ^0.32.11 => 0.32.11 
  npmGlobalPackages:
    @aws-amplify/cli: 9.1.0
    corepack: 0.10.0
    localtunnel: 2.0.2
    npm: 8.11.0
    serverless: 2.69.1
    yarn: 1.22.19

</details>

### Describe the bug

data is not returned in accordance with the limit, although the database has the required number of records

### Expected behavior

return data in an amount equal to the limit, if there is such an amount of data

### Reproduction steps

there are 4 records in the database with ticketId equal to “61b25636-9b59-431c-8e2b-ddb86cee39f5”
<img width="885" alt="Screenshot 2022-10-10 at 13 47 12" src="https://user-images.githubusercontent.com/106517182/194854610-4ca2e0a1-fe75-4df3-bf12-c6280a7634df.png">

**limit 5, there are 4 records in the database, the response is an empty array**
_Code_
![код5](https://user-images.githubusercontent.com/106517182/194855676-d35e8793-a8dc-42c4-96ea-23fdd59dc649.jpg)
_Result_
![рез5](https://user-images.githubusercontent.com/106517182/194855689-15c23f91-045c-48dc-8b98-9c728c1d50d4.jpg)

**limit 100, there are 4 records in the database, the response is an array of one element**
_Code_
![код100](https://user-images.githubusercontent.com/106517182/194855791-e87e7a47-c7ad-4e51-b0b0-0c7a2e6a1613.jpg)
_Result_
![рез100](https://user-images.githubusercontent.com/106517182/194855805-196c8bf7-60a8-4c34-b450-314358360647.jpg)

**limit 10000, there are 4 records in the database, the response is an array of 3 elements**
_Code_
![код1000](https://user-images.githubusercontent.com/106517182/194855892-b629f270-5716-499d-8a27-ecf041888c1d.jpg)
_Result_
![рез10000](https://user-images.githubusercontent.com/106517182/194855904-c29e1d06-8b83-48b1-8cd7-bd22d3a87d44.jpg)

### Code Snippet

```javascript

 async getActivitiesByTicket(ticketId){
    const filter = { ticketId: { eq: ticketId} }
    console.log('FILTER - ', filter)
    const result = await API.graphql(graphqlOperation(queries.listActivities , {
      filter,
      limit: 5
    }))
    console.log("RESULT - ", result)
  }

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @anyaokpesten 👋 can you share your schema?

**Comment by anyaokpesten** [comment]
> Привет@anyaokpesten 👋можете поделиться схемой?
> 
> Похоже, вы должны индексировать GSI, чтобы получить результаты, поэтому вы должны использовать такой запрос, как `listActivitiesByTicket`.
> 
> Для получения дополнительной информации: https://aws.amazon.com/premiumsupport/knowledge-center/appsync-wrong-query-item-number-dynamodb/

yes, i can do indexing and it will solve the problem if i need to search **_only by one_** ticketId. but if I need to do a search **_on multiple ticket IDs_**, what should I do in that case? an example of searching by multiple ticket IDs is shown in the screenshots
Code
<img width="729" alt="Screenshot 2022-10-10 at 21 56 49" src="https://user-images.githubusercontent.com/106517182/194935186-5c4cd7fd-d23e-4c38-97e6-69ea50047ce6.png">
Result
<img width="957" alt="Screenshot 2022-10-10 at 21 48 35" src="https://user-images.githubusercontent.com/106517182/194935241-1a2f712b-c6e9-4939-a1d5-baabbf6cec60.png">

**increased the limit**
Code
<img width="734" alt="Screenshot 2022-10-10 at 21 58 16" src="https://user-images.githubusercontent.com/106517182/194935361-ef566d1e-73c9-45b7-a284-8a69374ad5df.png">
Result
<img width="946" alt="Screenshot 2022-10-10 at 21 58 11" src="https://user-images.githubusercontent.com/106517182/194935423-280211f1-b3ed-421d-835f-903484c7928c.png">
I received a non-empty array of elements in the response when the limit was increased, but why did the empty array come when the limit was 20?

**Comment by chrisbonifacio** [comment]
@anyaokpesten the reason the limit had to be increased for results to show is because when you specify a limit AND a filter expression, you're asking DynamoDB to filter the number of records up to the limit (or 1MB max worth of data), and return the records that match the filter.

So, in your first query, there were only 5 records scanned and then the filter was applied to those. In the second, 10k records (or until 1MB), were scanned and then filtered. Because there are more records to be scanned, you also get a `nextToken` in the response to be able to paginate through the next set of records. It is only when `nextToken` is `null` that there are no more records to apply the filter to.
