### ISSUE TITLE
Auth signin fails the very first time due to PKCE session storage issue

### ISSUE THREAD

**Issue by pablovargasosorio** [aws-amplify/amplify-js#10457]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 90.86 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 106.0.5249.103
    Edge: 106.0.1370.42
    Firefox: 105.0.3
    Safari: 16.0
  npmGlobalPackages:
    corepack: 0.10.0
    npm: 8.11.0
```

</details>

### Describe the bug

I have configured cognito login in our project with PKCE. It normally works, but randomly the token verification fails (after cognito form submit), and we need to click on Sign In button again (which works in that second try)
After this first issue, the following login attempts will work forever, even if I close and open the browser again, etc. No second try needed anymore for that user.

It is happening only when the browser is clean (no resident cookies, local storage, etc.) and it's not 100% reproducible. I realized I can reproduce most times opening a new window in Chrome 'Incognito' mode, so we start the login flow in a clean context.

The root cause of the issue is because I'm trying to validate the token without the PKCE key. When clicking on Sign In, the Auth library is setting the 'pkce' key with:

authStorage.ts:
`window.sessionStorage.setItem('ouath_pkce_key', private_key);`

So when coming back from the cognito auth form, the Auth lib gets the stored value to validate the token:

OAuth.ts:
```javascript
[...]
const code_verifier = oAuthStorage.getPKCE();

const oAuthTokenBody = {
	grant_type: 'authorization_code',
	code,
	client_id,
	redirect_uri,
	...(code_verifier ? { code_verifier } : {}),
};
[...]
```

The code_verifier is empty in that case, because session storage has been reset somehow in the middle of the cognito Auth flow.

Some conclusions after my research:
- I confirmed the session storage property is set before jumping to cognito auth form.
- I've been looking into the Auth lib for any code which cleans the session storage and I found nothing, so I don't have a clue WHO is cleaning the 'ouath_pkce_key' property.

PS There's a typo in 'ouath_pkce_key' ;)

### Expected behavior

The SignIn flow with PKCE is working always, even in clean or private browser windows.

### Reproduction steps

1. Open a new clean window in any browser (Chrome, Safari, Mozilla) You can open 'private' or 'Incognito' window mode, or clean all the data of the browser.
2. Click button which starts the Auth.federatedSignIn method. Cognito should be configured with PKCE enabled.
3. Fill the authentication form and submit, which should relocate to the main page and check the auth token by calling to the oauth2 token verification with params: grant_type, code, client_id, redirect_uri, code_verifier.
4. See how code_verifier is MISSING, which should be present always when PKCE is enabled.

### Code Snippet

SignIn button which should start the Google auth flow:
```javascript
/**
 * This function opens the Google login popup
 */
googleSocialSignIn(): Promise<ICredentials> {
  return Auth.federatedSignIn({
    'provider': CognitoHostedUIIdentityProvider.Google,
  });
}

```

Angular guard which checks the current user session (should be OK when coming back from a successfully cognito login)

```javascript
@Injectable({
  providedIn: 'root',
})
export class AuthGuard implements CanActivate {
  constructor() {}

  canActivate(
    next: ActivatedRouteSnapshot,
    state: RouterStateSnapshot
  ): Observable<boolean> | Promise<boolean> | boolean {
    return fromPromise(Auth.currentAuthenticatedUser()).pipe(
      map(() => {
        // Whatever extra logic
        return of(true);
      }),
      catchError((error) => {
        // Some error happened (token verification error)
        this.router.navigate(['/login']);
        return of(false);
      })
    );
  }
}
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

Session Storage properly set after clicking on SignIn button:
![Captura de Pantalla 2022-10-11 a las 12 38 41](https://user-images.githubusercontent.com/18540292/195069295-f9733c63-6f32-4c4d-8b2e-0a2aa7424e16.png)

After cognito auth form is submitted, when lib tries to get the PKCE value, session storage is empty and token verify fails:
![Captura de Pantalla 2022-10-11 a las 12 39 49](https://user-images.githubusercontent.com/18540292/195069439-bf4ca9e7-8783-485d-be00-a30a71bbcc3b.png)
![Captura de Pantalla 2022-10-11 a las 12 40 15](https://user-images.githubusercontent.com/18540292/195069462-b30747a7-1c82-4191-ba02-79f9245b8305.png)

**Comment by cwomack** [comment]
Hey there @pablovargasosorio 👋.  I've built an angular app to attempt reproduction of the issue you're seeing, but have some follow up questions since you stated it's difficult to reliably reproduce.  

- What version of Amplify are you currently on? 
- What version of Angular are you using? (mainly are you using Angular v9.X or newer?)
- Within your `app.module.ts`, is `responseType: 'code'` or are you using `responseType: 'token'`?
- Is the `invalid_request` error only seen when the sign in fails or always visible in the console? 
- Is Google the only Social Provider you see this with/are using? 

I'll continue to dig deeper into how Auth is handling the PKCE authorization flow, but might need clarity on the above points to better determine if this is a bug.

**Comment by pablovargasosorio** [comment]
Hey Chris! Here is the info:

- Amplify/Auth: 4.5.9

- Angular: 14.2.9

- "responseType": "code"

- Reproduced also with Office provider 
`Auth.federatedSignIn({
      'customProvider': 'Office',
    })`

- `Are you able to find out what is throwing the OAuth - Error handling auth response. Error: invalid_request (or find what endpoint in network tab of console is yielding that response).` Not sure what you need, but the reason why it's failing is the missing 'code_verifier' parameter in the request payload. I guess it tries internally to validate the token with a missing code_verifier.
There's something "special" in our app.module, because the Auth.configure(-->config<--) call is made with a requested JSON from our API, not a local config constant. So, firstly we call to our API, then we get that config JSON and configure Auth.
That's something required in our project because the Auth config would depend on some stuff like the region, etc.
This is how (maybe you see a cleaner way):

`export function factoryFunction(config: ConfigService) {
  return (): Promise<any> => config.configureAuth();
}
[...]
@NgModule({
[...]
  providers: [
  [...]
  {
      provide: APP_INITIALIZER,
      useFactory: factoryFunction,
      deps: [ConfigService],
      multi: true,
    },
[...]`

The ConfigService:
`export class ConfigService {
  private configUrl: string;

  constructor() {
    this.configUrl = 'api/auth-config';
  }

  getAuthConfig(): Promise<any> {
    //Use fetch so that we do not try to access the JWT token which is hooked into the HTTPClient before we configure
    return fetch(this.configUrl).then(response => {
      if (!response.ok) {
        throw new Error('HTTP error ' + response.status);
      }
      return response.json();
    });
  }

  configureAuth(): Promise<any> {
    return this.getAuthConfig().then(res => {
      Auth.configure(res.config);
    });
  }
}`

- The 'extra_logic' thing is basically a post-login step, like getting the user status from our database, etc. We're not reaching that part when failing anyway...


Thanks for digging into it! Let me know if you need anything else...

**Comment by cwomack** [comment]
@pablovargasosorio, thanks for the detailed response! As for how you're configuring Auth after waiting for the API call, I'm wondering if the async configuration is causing issues.  Got a few extra questions now: 

1. Have you tried using a static config by chance to see if you get the same errors? 
2. Are you calling the `configureAuth()` from the root file of the app?
3. Did you implement a custom storage solution?

**Comment by pablovargasosorio** [comment]
Hey @cwomack!
1. I couldn't test that because it's only failing in production environment, and we cannot change that sensitive config flow in that environment.
2. The configureAuth() call should be made by Angular APP_INITIALIZER so I guess the answer is yes, that's in the root of the app loading flow.
3. Yes I tried with custom storage which saves the info in localStorage, but it seems sessionStorage and localStorage behaves the same during the issue, they're both empty.

Thanks very much!

**Comment by cwomack** [comment]
@pablovargasosorio, can you clarify what version of  RxJS you're using at this point?  I'm curious if the use of `fromPromise(Auth.currentAuthenticatedUser()).pipe(...)` as a now outdated method with RxJS v6+ might be causing some issues on that first sign in attempt.  

As for your number 3 above regarding both storages being empty, do you see the same result upon the second sign in attempt? Or when this is working (second attempt and after), does the local storage contain the usual Cognito key: values?

**Comment by pablovargasosorio** [comment]
@cwomack Hey Chris, I think I finally found the root issue. The pkce session storage value was missing because we have 2 different domains (with www prefix/without prefix)
Depending on how Cognito redirect URL is configured we can have that scenario where the sessionStorage is gone (actually was in the other domain)
I'll keep an eye to make sure this was the cause, and if it happens again I'll let you know. For now I think we can close it!
Thank you very much for your time!!
