### ISSUE TITLE
amplify-js appears to be incompatible with chrome extension service workers under manifest v3

### ISSUE THREAD

**Issue by emmby** [aws-amplify/amplify-js#10468]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

```
 System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 6.43 GB / 6.45 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 14.20.1 - /usr/bin/node
    npm: 6.14.17 - /usr/bin/npm
  npmPackages:
    @notionhq/client: ^2.2.1 => 2.2.1 
    @types/chrome: 0.0.197 => 0.0.197 
    aws-amplify: ^4.3.37 => 4.3.37 
    canvas: ^2.10.1 => 2.10.1 
    copy-webpack-plugin: ^11.0.0 => 11.0.0 
    dexie: ^3.2.2 => 3.2.2 
    js-sha256: ^0.9.0 => 0.9.0 
    linkedom: ^0.14.17 => 0.14.17 
    perf_hooks: 0.0.1 => 0.0.1 
    ts-loader: ^9.4.1 => 9.4.1 
    typescript: ^4.8.4 => 4.8.4 
    webpack: ^5.74.0 => 5.74.0 
    webpack-cli: ^4.10.0 => 4.10.0 
  npmGlobalPackages:
    @angular/cli: 14.2.5
    @aws-amplify/cli: 10.2.3
    corepack: 0.10.0
    npm: 6.14.17
```

</details>

### Describe the bug

```
TypeError: adapter is not a function
    at dispatchRequest (chrome-extension://.../background.js:122665:10)
    at Axios.request (chrome-extension://.../background.js:122443:15)
    at wrap (chrome-extension://.../background.js:123083:15)
    at RestClient._request (chrome-extension://.../background.js:37316:60)
    at RestClient.<anonymous> (chrome-extension://.../background.js:37121:56)
    at step (chrome-extension://.../background.js:36957:23)
    at Object.next (chrome-extension://.../background.js:36938:53)
    at chrome-extension://.../background.js:36932:71
    at new Promise (<anonymous>)
    at chrome-extension://.../background.js:36928:12
```

When attempting to use API.graphql from a chrome extension (v3) service worker.

### Expected behavior

No exception

### Reproduction steps

Follow the tutorial here: https://docs.amplify.aws/lib/q/platform/js/

### Code Snippet

In your background service worker

background.js:
```javascript
import { Amplify, API, graphqlOperation } from 'aws-amplify';
const awsconfig = require('./aws-exports').default;
Amplify.configure(awsconfig);
import { createTodo, updateTodo, deleteTodo } from './graphql/mutations';
import { listTodos } from './graphql/queries';


chrome.action.onClicked.addListener(async (tab) => {
    console.log('click!');

    const todos = await API.graphql(graphqlOperation(listTodos));
    console.log(todos);

    console.log('done!');
});

```

manifest.json:
```json
{
	"name": "...",
	"description": "...",
	"version": "0.0.1",
	"manifest_version": 3,
	"action": {},
	"permissions": [
		"cookies",
		"storage"
	],
	"host_permissions": [
		"*://amazon.com/*",
		"<all_urls>"
	],
	"background": {
		"service_worker": "background.js"
	}
}
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

```javascript
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://....appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-..."
};


export default awsmobile;
```

### Mobile Operating System

chrome

### Additional information and screenshots

The problem appears to be Axios' use of xhr instead of fetch.
https://stackoverflow.com/questions/66305856/typeerror-adapter-is-not-a-function-error-when-using-axios-and-webpack-in-chrom/70206333#70206333

Providing a way to configure axios to use fetch may fix the problem.

**Comment by jfloodnet** [comment]
I am currently working around this by forking the RestAPI classes into my solution and hard coding the fetchAdapter. Not ideal but saves me ripping it out altogether.

**Comment by jeromeheissler** [comment]
I've upgraded my code to the Amplify v6 and it seems not not to rely on axios.

**Comment by chrisbonifacio** [comment]
Closing this as Amplify no longer relies on axios and should be more compatible with chrome extension service workers
