### ISSUE TITLE
React Native Map Examples

### ISSUE THREAD

**Issue by GeorgeBellTMH** [aws-amplify/amplify-js#10467]
Currently the only examples in the geo section are for maplibre that works for react. It would be good if there was a react-native example as well...perhaps using: @rnmapbox/maps.

My guess is that to get this working there would need to be some information on correctly setting up the headers for auth.

**Comment by GeorgeBellTMH** [comment]
Yup, really looking for something that works in expo on web, iOS and android all at the same time...that's the dream!

**Comment by abdallahshaban557** [comment]
Hi @GeorgeBellTMH  - we are tracking a feature request to create a UI component to be used with the Amplify Geo category in this [Github issue](https://github.com/aws-amplify/amplify-ui/issues/2280). Please feel free to give this an upvote!
