### ISSUE TITLE
Amplify - GraphQL Client Subscribe not working 

### ISSUE THREAD

**Issue by tongzahub** [aws-amplify/amplify-js#1046]
Do you want to request a feature or report a bug?
ask question

  GraphQL Client Subscribe not working some subscribe (React Js)

           componentDidMount = async () => {
            const subscriptionDeleteProduct = API.graphql(graphqlOperation(SubscribeProductDelete)).subscribe({
			next: (eventData) =>{
				this.handleSubscriptionDelete(eventData)},
				error:(error)=>{
					console.log('error',error)
					
				}
		});
		
		const subscriptionCreateProduct = API.graphql(graphqlOperation(SubscribeProductCreate)).subscribe({
			next: (eventData) => {console.log('subscriptionCreateProduct');
			},
			error:(error)=>{
				console.log('error',error)
				
			}
		});
	
		const subscriptionUpdateProduct = API.graphql(graphqlOperation(SubscribeProductUpdate)).subscribe({
			next: (eventData) => {this.handleSubscriptionUpdate(eventData)},
			error:(error)=>{
				console.log('error',error)
			}
		});

           }

some component subscribe create and delete , they worked, but subscribe  update doesn’t work
I check query on  AWS AppSync , It works
For the create code ,I have checked on Appsync and the process was normally worked.

how to solve the problem ?

**Comment by haverchuck** [comment]
Hi @tongzahub ,

Thanks for reaching out!  Will you please clarify what you mean by "doesn't work"?  Are you receiving an error, and if so what does it say?  Or are you seeing unexpected behavior without any error output... and if so what is the unexpected behavior?

Thanks in advance for your clarification.

**Comment by tongzahub** [comment]
Hi @haverchuck 
Thanks for responded

The error didn’t happen in this situation cause of the client couldn’t subscribe data as usual. 
Then I made it like a 2 components and other situation such as when I had registered user on conito first time to login, I could normally use all functional subscribe action. 

compoent 1
subscribe  create - work
subscribe  update- work
subscribe  delete- work

compoent 2
subscribe  create - work
subscribe  update- work
subscribe  delete- work

But when I refreshed that, the error situation above its happened.

compoent 1
subscribe  create - work
subscribe  update- doesn’t work
subscribe  delete- work

compoent 2
subscribe  create - doesn’t work
subscribe  update- work
subscribe  delete- work



this my code on React 

```

            var subscriptionDeleteProduct ,subscriptionCreateProduct ,subscriptionUpdateProduct ;
             class {


             componentDidMount (){
             subscriptionDeleteProduct =await API.graphql(graphqlOperation(SubscribeProductDelete)).subscribe({
			next: (eventData) =>{
				this.handleSubscriptionDelete(eventData)}
				,error:(error)=>{
					console.log('error',error)
					
				}
		});
		console.log(subscriptionDeleteProduct);
		
		
		 subscriptionCreateProduct =await API.graphql(graphqlOperation(SubscribeProductCreate)).subscribe({
			next: (eventData) => {this.handleSubscriptionCreate(eventData)}
			,error:(error)=>{
				console.log('error',error)
				
			}
		});

		console.log(subscriptionCreateProduct);

		 subscriptionUpdateProduct =await API.graphql(graphqlOperation(SubscribeProductUpdate)).subscribe({
			next: (eventData) => {this.handleSubscriptionUpdate(eventData)}
			,error:(error)=>{
				console.log('error',error)
				
			}
		});
		
		console.log(subscriptionUpdateProduct);
          }


     }
```

console

![image](https://user-images.githubusercontent.com/12952880/41597768-918ae1a6-73f8-11e8-8010-fb67b4aca90c.png)


Today .i add unsubscribe in componentWillUnmount .when  i change component . i have error

```
	componentWillUnmount(){
		subscriptionDeleteProduct.unsubscribe();
		subscriptionCreateProduct.unsubscribe();
		subscriptionUpdateProduct.unsubscribe();
	}

```


![image](https://user-images.githubusercontent.com/12952880/41597921-00f732b0-73f9-11e8-8947-8f6dbfc2b25c.png)

thanks you very much ,and sorry abound my endlish skil

**Comment by jordanranz** [comment]
@tongzahub Are you still experiencing this issue with the latest version of `aws-amplify`? If so is it possible to show screenshots of the Network tab when the update and create failed that you mentioned above.
