### ISSUE TITLE
User pool client xxxx does not exist.

### ISSUE THREAD

**Issue by Arnav7501** [aws-amplify/amplify-js#10490]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication, GraphQL API, DataStore, Storage

### Environment information

<details>

```
# Put output below this line


```

</details>
 System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 131.45 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Safari: 15.1
  npmPackages:
    @babel/core: ^7.12.9 => 7.18.13 
    @react-native-async-storage/async-storage: ^1.17.10 => 1.17.10 
    @react-native-community/netinfo: ^9.3.0 => 9.3.0 
    @react-native-picker/picker: ^2.4.4 => 2.4.4 
    @react-navigation/native: ^6.0.12 => 6.0.12 
    @react-navigation/native-stack: ^6.8.0 => 6.8.0 
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: ^5.2.10 => 5.2.10 
    aws-amplify: ^4.3.33 => 4.3.33 
    aws-amplify-react-native: ^6.0.5 => 6.0.5 
    expo: ~46.0.9 => 46.0.9 
    expo-clipboard: ~3.1.0 => 3.1.0 
    expo-image-picker: ~13.3.1 => 13.3.1 
    expo-status-bar: ~1.4.0 => 1.4.0 
    hermes-inspector-msggen:  1.0.0 
    ini: ^1.3.5 => 1.3.8 
    inquirer: ^6.5.1 => 6.5.2 
    react: 18.0.0 => 18.0.0 
    react-hook-form: ^7.37.0 => 7.37.0 
    react-native: 0.69.4 => 0.69.4 
    react-native-safe-area-context: 4.3.1 => 4.3.1 
    react-native-screens: ~3.15.0 => 3.15.0 
    uuid: ^9.0.0 => 9.0.0 (3.4.0, 3.3.2, 8.3.2, 7.0.2, 7.0.3)
  npmGlobalPackages:
    @aws-amplify/cli: 10.0.0
    n: 9.0.0

### Describe the bug

Anytime i try to use Auth.signup or Auth.signin or any feature, i get the userpool client xxxx does not exist, haven't found anything online to explain why the auth commands simply won't work.

### Expected behavior

I expected to either sign in or sign up.

### Reproduction steps

1. install expo
2. in authentication
login - enable username
signup - email and name.

### Code Snippet

```javascript
// Put your code below this line.

```
  const onRegisterPressed = async data => {
        const {username, password, email, name} = data;
        try {
            await Auth.signUp({
                username,
                password,
                attributes: {email, name, preferred_username: username}, 
            });
        navigation.navigate('ConfirmEmail', {username});
        } catch(e) {
            setdebug(e.message)
            Alert.alert('Oops ',  e.message);
            console.log(e.message)
        }

### Log output

<details>

```
// Put your logs below this line


```

</details>
user pool client xxxx does not exist

**Comment by haverchuck** [comment]
@Arnav7501 Could you please 
1. Post the content from your `aws-exports.js` file or the object you're using to configure? Feel free to obscure the actual values (I just want to see the keys).
2. Post a snippet of the code you are using to call configure?

**Comment by Arnav7501** [comment]
@haverchuck 
Alright, I have located the main problem. 
In this image, you can see i configured email and name for the signup field
<img width="914" alt="image" src="https://user-images.githubusercontent.com/90722645/196250667-e7d601cf-62d1-4d39-81dd-86cb499a9d3f.png">

However, 
my  "aws_cognito_signup_attributes": [], is empty. Even after i pulled the updated environment multiple times my aws-exports won't update. Do you have any idea how I should get it to update?

**Comment by haverchuck** [comment]
@Arnav7501 Thank you for the update. When you say "pulled the updated environment", what exactly do you mean? You cannot change the required attributes after the user pool is created.

**Comment by tannerabread** [comment]
hi @Arnav7501
Just a follow up, if you were trying to update the required attributes after the user pool has been created, you will not be able to update the project. Can you confirm if this is what you were trying to do?

**Comment by Arnav7501** [comment]
yes, that is what i was trying to do. I ultimately just gave up and created a new project and it started working

**Comment by tannerabread** [comment]
Okay I will close this issue as resolved then. 

Please feel free to open up more issues if you run in to any issues with Amplify and join our [discord](https://discord.com/invite/amplify) for help/discussion with the Amplify community.

Thank you!
