### ISSUE TITLE
Sign in with Apple configuration rejected by App Store

### ISSUE THREAD

**Issue by SanjitIdigitalxp** [aws-amplify/amplify-js#10507]
In my experience since apple is making mandatory using "sign in with apple" in your project like a mobile app if you use other socials like Facebook or google, nothings seems to solve the issue that amplify with cognito using federatedSignIn with apple sign in does not work at all! I have spent days testing everything and still not having any solution! Please amplify put a clear working sample of using federatedSignIn with signInwithApple because it seems it is not working and only Facebook and google socials works fine!
thanks

_Originally posted by @rapgithub in https://github.com/aws-amplify/amplify-js/issues/6637#issuecomment-862114210_

In my case, the apple review team rejected my app certification because of this issue anyone knows an alternate way to use Cognito apple login with react native without calling the browser as a middle man to authenticate react native app

**Comment by nadetastic** [comment]
Hi @SanjitIdigitalxp 👋,

I'm taking a look at this issue, and would like some additional details - looks like you are using React Native, is it with Expo or  React Native CLI? Also could you also share the versions you are using?

**Comment by SanjitIdigitalxp** [comment]
Hi,

I am using React Native CLI. I am attaching the package.json file for your reference and I am using amplify version 9.2.0 on my mac machine.

We have setup a react native app using Amplify framework. We have followed the following documentation https://docs.amplify.aws/lib/auth/social/q/platform/js/#full-samples
[https://docs.amplify.aws/assets/ogp.jpg]<https://docs.amplify.aws/lib/auth/social/q/platform/js/#full-samples>
Authentication - Social sign-in (OAuth) - JavaScript - AWS Amplify Docs<https://docs.amplify.aws/lib/auth/social/q/platform/js/#full-samples>
OAuth and Federation Overview. OAuth 2.0 is the common Authorization framework used by web and mobile applications for getting access to user information ("scopes") in a limited manner. Common analogies you will hear in OAuth is that of boarding a plane or staying in a hotel - showing your identification is the Authentication piece (signing into an app) and using the boarding pass/hotel key is ...
docs.amplify.aws
We are using Cognito with Apple as a federated identity provider to let our users sign in using Apple Id.

Our Apple Certification failed because of the highlighted text you can see in AppleLogin.png

This highlighted text is not visible when using appleAuth for Apple login provided by Apple in react-native app.
________________________________

**Comment by haverchuck** [comment]
@SanjitIdigitalxp We are looking into this. In terms of not using the 'browser as a middleman', would your use case be helped by using an [In-App](https://docs.amplify.aws/lib/auth/social/q/platform/react-native/#full-samples) browser like [react-native-inappbrowser](https://github.com/proyecto26/react-native-inappbrowser)?

**Comment by SanjitIdigitalxp** [comment]
Hello,

 would your use case be helped by using an In-App<https://docs.amplify.aws/lib/auth/social/q/platform/react-native/#full-samples> browser like react-native-inappbrowser<https://github.com/proyecto26/react-native-inappbrowser>?
=> No, this will not work.

      I had a talk with the apple review team, sabchalo ios app certification was not failed because of the "Use a different Apple ID" option. It's failed because of Apple ID screen generated in sabcalo ios       app when user clicks on the sign in with apple button. This issue is not following ios app human interface and design guideline for ios app certificatin.

      Ideally when we are using sign-in with apple in any ios app it should detect you are signed in into your device otherwise it will show popup to go into your setting and sign-in first and If user is           clicking first time on apple signin button then show benifits of apple signin screen.  This is not happening when we are using an In-App<https://docs.amplify.aws/lib/auth/social/q/platform/react-native/#full-samples> browser like react-native-inappbrowser<https://github.com/proyecto26/react-native-inappbrowser>.
      
      It automatically redirects me to Apple ID screens, it does not detect whether you are logged in to your device or not if I go with react-native-inappbrowser<https://github.com/proyecto26/react-native-inappbrowser> flow.

      I am attaching one diagram (reactNativeCognitoAppleSigninUsingAmplify.png) for your reference.
[https://repository-images.githubusercontent.com/147781722/cd16ab00-6f5c-11e9-84ee-b1ffbe450b35]<https://github.com/proyecto26/react-native-inappbrowser>
GitHub - proyecto26/react-native-inappbrowser: 📱InAppBrowser for React Native (Android & iOS) 🤘<https://github.com/proyecto26/react-native-inappbrowser>
📱InAppBrowser for React Native (Android & iOS) 🤘. Contribute to proyecto26/react-native-inappbrowser development by creating an account on GitHub.
github.com
Thanks,
Sanjit


________________________________

**Comment by haverchuck** [comment]
@SanjitIdigitalxp I can't seem to access the diagram you intended to leave?

**Comment by haverchuck** [comment]
@SanjitIdigitalxp To confirm your issue: Sign In with Apple is technically functional, but Apple has rejected the application because the sign in experience is launched in a browser?

**Comment by SanjitIdigitalxp** [comment]
Hello,

Apple review team is rejecting certification because of the "Apple ID" screen generated during the apple login process. And I tried this setup in react native with react native CLI, Cognito, and amplify.
In the native apple login flow, you will never get "Apple ID" screen. For this, I am attaching another zip file ( appleAuthReactNativeFlowDiagram.png.zip ) for your reference.

As you mention you were not able to get access to the image which I attached. So, I am attaching the image zip file for your reference.

Thanks,
Sanjit Maji
________________________________

**Comment by nadetastic** [comment]
@SanjitIdigitalxp would you be available for a call in order to better discuss this issue with you?

**Comment by SanjitIdigitalxp** [comment]
Hi,

Sorry, I was busy with some other work.

I just saw your email and Yes, I am available for the call this will be really helpful for me as well.
I am also working on an apple sign-in issue at my end with swift code and WebView but still facing issues not being able to resolve it.

Thanks,
Sanjit

________________________________

**Comment by nadetastic** [comment]
Thank you for working with me on this.

As security is our main priority at AWS please share your contact/email information through my email `dkkiuna@amazon.com` and let me know a good time to connect with you. My availability is 9am-6pm CST (North America)

**Comment by SanjitIdigitalxp** [comment]
Hello,

I sent an Email to ***@***.***".
Can we keep this meeting tomorrow between 8:30 pm - 9:30 pm IST i.e. 9 am - 10 am CST?

I am able to find a way to tackle this apple login issue with native code and I want to discuss this complete flow with you.

Thanks,
Sanjit
________________________________

**Comment by nadetastic** [comment]
Hi @SanjitIdigitalxp 

I received the email, that works and will setup a meeting shortly.

**Comment by haverchuck** [comment]
#7373

**Comment by nadetastic** [comment]
Closing this issue in favor of #7373 - As discussed in that issue the fix for this is not to redirect to the default browser (aka take your user away from the app/open safari) but to use an in-app browser with `react-native-inappbrowser-reborn` by passing a `urlOpener` to `Amplify.configure()` as shown in the [documentation](https://docs.amplify.aws/lib/auth/social/q/platform/react-native/#full-samples).
