### ISSUE TITLE
[Vue] installing aws-amplify warns about an unmet peer dependency react-native

### ISSUE THREAD

**Issue by CptSpaceToaster** [aws-amplify/amplify-js#10500]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Vue

### Which UI component?

Other

### How is your app built?

Webpack

### Please describe your bug.

I installed aws-amplify and @amplify-ui/ui-vue with the instructions from the [Vue getting started steps](https://ui.docs.amplify.aws/vue/getting-started/installation)

`yarn add @aws-amplify/ui-vue aws-amplify`

After solving dependencies, I was given this warning:

```warning "aws-amplify > @aws-amplify/analytics > @aws-sdk/client-firehose > @aws-sdk/middleware-retry > react-native-get-random-values@1.8.0" has unmet peer dependency "react-native@>=0.56".```

It appears that `aws-amplify` brings in `react-native-get-random-values`.

Version `aws-amplify@4.3.37`

This warning continues to occur when I bump other project dependencies, and can't be silenced.

### What's the expected behaviour?

I don't think I should be receiving a warning to install react-native in my vue3 project.

### Help us reproduce the bug!

I think it's as straight forward as creating a template vue3 project (or any non react-native project?), then installing `aws-amplify` with `yarn add aws-amplify`

**Comment by tannerabread** [comment]
hi @CptSpaceToaster 
Can you confirm if you are still experiencing this behavior? I tried to make a sample app following [these steps](https://vuejs.org/guide/quick-start.html) up to the `npm run dev` step and then added `aws-amplify@4.3.37` and `@aws-amplify/ui-vue` to the project. I am not seeing the error you describe.

This also looks possibly related to #9119 where react-native is being pulled in from `@aws-amplify/core`

**Comment by CptSpaceToaster** [comment]
The trouble seems to be coming from other packages in my project, and yarn's dependency resolution... after uninstalling `aws-amplify` and `@aws-amplify/ui-vue` and reinstalling them... I'm still seeing the issue as yarn pulls in `@aws-sdk@3.6.1`... when we'd need to see that bump up to 3.12.1 or later... the entire 3.6.1 dependency graph includes `@aws-sdk/middleware-retry@3.6.1` which shows up here and [in other issues](https://github.com/aws-amplify/amplify-js/issues/10029#issuecomment-1167603779) but I'm a little lost trying to understand why yarn isn't pulling something a little more recent.

I noticed the instructions you're following install `vue@latest`, and I'm still on `vue@3.2.39`... but that's all I have to go on...

**Comment by tannerabread** [comment]
Closing this in favor of the duplicate/previous issue #9119 to track with better coverage. @CptSpaceToaster if you find anything additional please add it to that issue, but I think @erinleigh90's response gives all of the context for why it has not been changed before now

**Comment by CptSpaceToaster** [comment]
My only quibble is that `react-native` isn't actually being installed and the duplicate issue claims that it is. I did see that issue a while back, but figured the landscape had changed. The current issue is far more minor. I'm just being asked to install `react-native` because `react-native-get-random-values` is being installed, which is more than ignorable. Thanks for the responses. I'll keep watch on #9119.

**Comment by tannerabread** [comment]
Understandable, I see the difference now. I do think that the fix would be the same though with upgrading the aws-sdk version. I'm happy it's not blocking your project though and will continue to track on that issue.

Thank you
