### ISSUE TITLE
After signin successfully try to get data from other collection 

### ISSUE THREAD

**Issue by ahsan-abrar** [aws-amplify/amplify-js#10531]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication, DataStore

### Amplify Categories

auth

### Environment information

after signing successfully and request to user collection not get user data but when I click a second time to signing button then it gave the expected results

https://user-images.githubusercontent.com/58684529/197899208-b1c656cd-43e7-4f97-a30b-d1bcb0d65e04.mp4

Packages:
<details>

```
 "@azure/core-asynciterator-polyfill": "^1.0.2",
    "@react-native-async-storage/async-storage": "^1.17.10",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/netinfo": "^9.3.4",
    "@react-native-picker/picker": "^2.4.7",
    "@react-navigation/bottom-tabs": "^6.3.3",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/stack": "^6.2.0",
    "add": "^2.0.6",
    "amazon-cognito-identity-js": "^5.2.10",
    "aws-amplify": "^4.3.37",
    "aws-amplify-react-native": "^6.0.5",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "prop-types": "^15.8.1",
    "react": "18.1.0",
    "react-native": "^0.70.0",
    "react-native-audio-recorder-player": "^3.5.1",
    "react-native-dropdown-picker": "^5.4.2",
    "react-native-floating-action": "^1.22.0",
    "react-native-gesture-handler": "^2.6.0",
    "react-native-iphone-x-helper": "^1.3.1",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-pager-view": "^5.4.25",
    "react-native-raw-bottom-sheet": "^2.2.0",
    "react-native-safe-area-context": "^4.3.1",
    "react-native-screens": "^3.14.1",
    "react-native-snackbar": "^2.4.0",
    "react-native-splash-screen": "^3.3.0",
    "react-native-svg": "^12.3.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-uuid": "^2.0.1",
    "react-native-vector-icons": "^9.2.0",
    "react-redux": "^8.0.2",
    "reactotron-react-native": "^5.0.2",
    "redux": "^4.2.0",
    "redux-logger": "^3.0.6",
    "redux-storage": "^4.1.2",
    "redux-storage-decorator-filter": "^1.1.8",
    "redux-storage-engine-reactnativeasyncstorage": "^1.0.7",
    "remote-redux-devtools": "^0.5.16",
    "rn-fetch-blob": "0.13.0-beta.2",
    "seamless-immutable": "^7.1.4",
    "twrnc": "^3.4.0",
```

</details>

### Describe the bug

after signing successfully and request to user collection not get user data but when I click a second time to signing button then it gave the expected results

### Expected behavior

when the user signs in successfully I need user detail

### Reproduction steps

- Simply request to sign in 
- If sign in successfully then send any request to get data from any collection.

### Code Snippet

```javascript
// Put your code below this line.

      const handleSignin = async () => {
          if (validation()) {
            return false;
          }
          setIsLoading(true);
          try {
            const response = await Auth.signIn(email, password);

            setIsLoading(false);
            if (!response?.attributes?.email_verified) {
              return util.bottomAlert('Please verify your email address ');
            }
            reactotron.log({
              response,
            });

            const getUserAllDetail = await DataStore.query(User, c =>
              c.userID('eq', response.username),
            );

            reactotron.log({
              getUserAllDetailget_: getUserAllDetail,
            });

            setIsLoading(false);
          } catch (error: any) {
            console.log({
              error,
            });

            setIsLoading(false);
            util.authErrors(error?.name);
          }
        };
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:35cf4db1-1dc2-44ea-8c91-ce9bb93b7ded",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_UAeEmrYdN",
    "aws_user_pools_web_client_id": "",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "GENDER",
        "NAME",
        "PREFERRED_USERNAME",
        "EMAIL",
        "PICTURE"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": ""
};

export default awsmobile;

### Mobile Device

Simulator iphone 13

**Comment by chrisbonifacio** [comment]
Hi @ahsan-abrar 👋 can you share your GraphQL schema as well as the code snippets on how you are creating users?

**Comment by chrisbonifacio** [comment]
@ahsan-abrar on React Native you can use a tool like https://github.com/infinitered/reactotron to log AsyncStorage. Or, if using the SQLite Adapter for DataStore, you can find the db file using this https://gist.github.com/junjizhi/e60e7e70f034aca28d668831f59bff50 and open it with https://sqlitebrowser.org/

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
