### ISSUE TITLE
Can I validate user input w/o subsequent signup? Only validation

### ISSUE THREAD

**Issue by wzup** [aws-amplify/amplify-js#1054]
### Do you want to request a feature or report a bug?

Issue

### What is the current behavior?

DOn't know, can't find methods in docs

### What is the expected behavior?

Validate user input WITHOUT subsequent sign up action. Please see example below

```javascript
        // method like this, no subsequent signup, just validate
        Auth.verifySignupInput()
            .then(response => {
                // input is valid
            })
            .catch( err => {
                // input is invalid
                // pasword is short
                // email doesn't have @ sign
            });

// currently validation is done in exactly during signUp action.
Auth.signUp( email, password )
```
SO question 
https://stackoverflow.com/questions/50922919/can-i-validate-user-input-w-o-subsequent-signup-only-validation-no-signup

**Comment by haverchuck** [comment]
Hi @wzup ,

Thanks for reaching out.  Can you please clarify what you mean by 'validate' user input?  Specifically - do you mean validate that the inputs fall within predefined parameters (for example, correct password length and character restrictions) or do you mean validate that the actual user credentials (username/password combination) are correct?

If you are actually trying to verify that the credentials are correct, can you please give a little more detail about your usecase - why would you want to do this without lgging the user in?  It would help us answer your question or take action.

Thanks so much.

**Comment by wzup** [comment]
@haverchuck 

This variant:
> _do you mean validate that the inputs fall within predefined parameters (for example, correct password length and character restrictions)_

Because there is **Policies** section where for example you can set up password strength:

![screen shot 2018-06-21 at 9 19 52 am](https://user-images.githubusercontent.com/3880497/41701255-7ddfc1de-7534-11e8-9eb0-6d481730b7ae.png)

So we end up having password restrictions in Cognito, but not on client-side. We have to manually create regex that match Cognito's settings to validate a password client-side. Why this duplication? It is redundant. Same applies to email string.

Currently I use [validate.js](http://validatejs.org/#validators-length). But why if it would be better to use single source of validation - exactly in Cognito?

```javascript
Auth.isPasswordValid('password')
Auth.isEmailValid('email')
```

**Comment by haverchuck** [comment]
@wzup 
So essentially you're trying to avoid calls to the backend that you already know will result in a failure because of the field constraints?

**Comment by haverchuck** [comment]
Hi @wzup 

Just checking in on this issue - are you asking for a UI component that will get the input restrictions form Cognito in advance of the user making a signUp call?

**Comment by wzup** [comment]
@haverchuck 
> _that will get the input restrictions form Cognito in advance_

This also possible.

The idea is to have one source of validators. If I set validators in Cognito, let's use it on the client as well. Either by making a request like `validatePassword( {method: POST, password: 'zxcvb567'} )` or as you say by getting _the input restrictions form Cognito in advance_.

Currently it is not possible. I have to create validators (regex string) on the client that matches my Cognito's validators.

**Comment by haverchuck** [comment]
I'm marking this as a feature request.

**Comment by jordanranz** [comment]
FYI, we have started an RFC discussion for a proposed Amplify UI Component refactor to increase customizability and flexibility for our components. Please feel free to add any additional comments to the following issue:

https://github.com/aws-amplify/amplify-js/issues/3279

**Comment by harrysolovay** [comment]
Unfortunately this is not something that we could implement. If you'd like this feature (a service feature), it would require a new endpoint and new validation functionality. I recommend going into your AWS Console, navigating to Cognito, and submitting feedback (bottom left-hand corner).
