### ISSUE TITLE
Update js-cookie package to 3.0.1

### ISSUE THREAD

**Issue by NtchPlayer** [aws-amplify/amplify-js#10552]
### Is this related to a new or existing framework?

Vue, New framework

### Describe the feature you'd like to request

Update js-cookie for amazon-cognito-identity-js to 3.0.1.

Version 3.0.1 is release since one year. The usage of version 2.2.1 cause error on deploying web with Nuxt-bridge from Nuxt.

### Describe the solution you'd like

Update js-cookie package to 3.0.1 in package.json.

### Describe alternatives you've considered

update js-cookie.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
