### ISSUE TITLE
graphqlOperation throws error (which isn't an error object) when fields are unauthorized

### ISSUE THREAD

**Issue by jdanielsyeah** [aws-amplify/amplify-js#10574]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Authentication, GraphQL API

### Amplify Categories

auth, api

### Environment information

<details>

```
type Yellow @model {
  anyone: String
    @auth(
      rules: [
        { allow: groups, groupsField: "canRead" }
        { allow: private, provider: userPools, operations: [create] }
      ]
    )
  canRead: [String]
    @auth(
      rules: [
        { allow: groups, groupsField: "canRead" }
        { allow: private, provider: userPools, operations: [create, read] }
      ]
    )
  canReadDynamic: String
    @auth(
      rules: [
        { allow: groups, groupsField: "canRead" } # Leave off only here.
        { allow: private, provider: userPools, operations: [create] }
      ]
    )
}

```

</details>

### Describe the bug

When I run a GraphQL query using AppSync in my NextJS front-end, I get an error thrown if some of the return records contain a field that the user is not authorized to access.

It's quite confusing, as the error isn't actually an `Error` object (ie, when I typecheck with `error instanceof Error` it returns `false`). Furthermore, the object is as follows:
```js
{
  data: { listYellows: { items: <records of Yellow>[] } }
  errors: <AppSync Errors>[]
}
```

Where the records of the `Yellow` model being returned are actually what I'm trying to retrieve, eg:
```js
{
 anyone: null,
 canRead: null,
 canReadDynamic: null,
 createdAt: "2022-10-31T14:14:51.914Z",
 id: "fabd4c25-e327-47ac-9620-0fbf799194b5",
 updatedAt: "2022-10-31T14:14:51.914Z",
 _deleted: null,
 _lastChangedAt: 1667225691916,
 _version: 1
}
``` 

And the error objects, eg:
```js
{
  data: null,
  errorInfo: null,
  errorType: "Unauthorized",
  locations: [{…}],
  message: "Not Authorized to access anyone on type String",
  path: ['listYellows', 'items', 0, 'anyone'],
}
```

This has confused me, as since the error being thrown isn't an error, and also contains the exact data that I'm trying to retrieve, I'm tempted to capture the 'error' in a try/catch block and just render my front end with the data. But on the other hand that seems like a messy way to do things?

### Expected behavior

It would be more intuitive if the response was returned without errors, with `null` returned for any fields that the user isn't authorized on. And alternatively, if this isn't done, it might make more sense for the thrown error to actually be an instance of `Error`.

### Reproduction steps

1. amplify add api & auth
2. update schema.graphql as above
3. make appsync call for `listYellows` as per generated query
```graphql
# schema.graphql:

type Yellow @model {
  anyone: String
    @auth(
      rules: [
        { allow: groups, groupsField: "canRead" }
        { allow: private, provider: userPools, operations: [create] }
      ]
    )
  canRead: [String]
    @auth(
      rules: [
        { allow: groups, groupsField: "canRead" }
        { allow: private, provider: userPools, operations: [create, read] }
      ]
    )
  canReadDynamic: String
    @auth(
      rules: [
        { allow: groups, groupsField: "canRead" } # Leave off only here.
        { allow: private, provider: userPools, operations: [create] }
      ]
    )
}

```

### Code Snippet

```javascript

type AppSyncError = {
  data: any[];
  errors: any[];
};

function isAppSyncError(error: unknown): error is AppSyncError {
  return (
    typeof error === "object" && !!error && "data" in error && "errors" in error
  );
}

export async function listItemsAppsync(modelQuery: string) {
  try {
    const listResponse = await API.graphql(graphqlOperation(modelQuery));
    return listResponse;
  } catch (error) {
    if (error instanceof Error) { // Doesn't trigger this conditional as isn't error
      throw error;
    }
    if (isAppSyncError(error)) { 
      console.log({ isAppSyncError: true });
      return error; // Seems nearly sensible to send this as a return value?
    } else throw error;
  }
}

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

```js
const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:54ffc58e-6bff-4a53-8ce4-a998ff90ca3f",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_1KQbeOgi1",
    "aws_user_pools_web_client_id": "6hif2ro4ch55lo89gpnpim5smq",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://6427uugt4vgzjlznsy7otaw7ye.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-q2xze637hjht7nzxma2ajae5fu"
};
```

**Comment by chrisbonifacio** [comment]
Hi @jdanielsyeah 👋 can you share your schema so that we can reproduce this with the same auth rules?

**Comment by jdanielsyeah** [comment]
Thanks @chrisbonifacio I had included it in the environment section in error. I've added the schema to the Reproduction Steps now.

**Comment by ncarvajalc** [comment]
Hi @jdanielsyeah. I could reproduce your issue and found a way to handle those errors safely.

This type you are mentioning:
```ts
type AppSyncError = {
  data: any[];
  errors: any[];
};
```
is the intended error structure returned by AppSync when a GraphQL API is created in AWS. It might have a `data` attribute as this is used in some case scenarios, such as Datastore and conflict resolving, or your specific situation, when there is relevant data that can be used but when there are errors that can be useful to you or the user. That is the reason why this is not an instance of `Error`.

If you see the response you are getting in the `data` attribute:
```js
{
 anyone: null,
 canRead: null,
 canReadDynamic: null,
 createdAt: "2022-10-31T14:14:51.914Z",
 id: "fabd4c25-e327-47ac-9620-0fbf799194b5",
 updatedAt: "2022-10-31T14:14:51.914Z",
 _deleted: null,
 _lastChangedAt: 1667225691916,
 _version: 1
}
```
You can see that the fields you have no access to are `null`. The important thing is to handle the errors correctly. 

Take a look at the `handleCreatePost` function suggested in the [Amplify docs](https://docs.amplify.aws/start/getting-started/data-model/q/integration/next/#api-with-server-side-rendering-ssr):
```js
async function handleCreatePost(event) {
  event.preventDefault();

  const form = new FormData(event.target);

  try {
    const { data } = await API.graphql({
      authMode: 'AMAZON_COGNITO_USER_POOLS',
      query: createPost,
      variables: {
        input: {
          title: form.get('title'),
          content: form.get('content')
        }
      }
    });

    window.location.href = `/posts/${data.createPost.id}`;
  } catch ({ errors }) { // Gets errors from {errors: any[], data: any[]}
    console.error(...errors);
    throw new Error(errors[0].message);
  }
}
```
You can notice that those errors are getting handled.

One suggestion I would make for your code would be the following:
```ts
export async function listItemsAppsync(modelQuery: string) {
  try {
    const listResponse = (await API.graphql({
      query: modelQuery,
    })) as { data: typeof modelQuery };
    return listResponse.data; // Returns data when there are no errors
  } catch ({ errors, data }) {
    if (data) {
      console.warn("Errors with data", errors)
      return data; // Returns data when there are auth errors
    } else {
      console.error("Unhandled error", errors);
      // Handle no data error
    }
  }
}
```

The last else is important as an error which returns no data can be received. An example is shown below:
```ts
listItemsAppsync(`query ListYellows(
    $filter: ModelYellowFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listYellows(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        anyone
        canRead
        canReadDynamic
        id
        createdAt
        updatedAt
        notAFieldInSchema  <- This will produce an error
      }
      nextToken
    }
  }`)
```
If the query inserted is not a valid one, you should be notified about that error and handle it as you want. 
![image](https://user-images.githubusercontent.com/66692533/199549287-a232bf95-ded3-4fa1-a0d3-3b7eb965727d.png)

**Comment by jdanielsyeah** [comment]
That's a great help @ncarvajalc - exactly what I needed, thank you. I had a hunch that I could handle the error to utilise the `data`, but wasn't confident in the face of an error. I've updated my AppSync calls to anticipate the errors by filtering out any fields that the user doesn't have access to, but it's reassuring to know that in future I can just handle as per your example.
