### ISSUE TITLE
DataStore - Constructor is not for a valid model, Object {   "modelConstructor": undefined, }

### ISSUE THREAD

**Issue by tonybs03** [aws-amplify/amplify-js#10615]
Hello everyone

I am making a react native application using EXPO along with AWS studio for backend (DynamoDB)
I started getting this error message as titled. 
Does anyone know what is likely the problem?

I have checked all the models that I have, they are all capitalized. 
I traced back to the the original file that gave the error, it is in node_modules\@aws-amplify\datastore\lib-esm\datastore\datastore.js
In particular, the codes are:

` 
this.query = function (modelConstructor, identifierOrCriteria, paginationProducer) { return __awaiter(_this, void 0, void 0, function () {
            var msg, modelDefinition, keyFields, predicate, msg, pagination, result, returnOne;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, this.start()];
                    case 1:
                        _a.sent();
                        //#region Input validation
                        if (!isValidModelConstructor(modelConstructor)) {
                            msg = 'Constructor is not for a valid model';
                            logger.error(msg, { modelConstructor: modelConstructor });
                            throw new Error(msg);
}
`

Any hints or helpful tips are much appreciated!

**Comment by chrisbonifacio** [comment]
Hi @tonybs03 can you try running `amplify codegen models`, clearing the database and restarting the app?

If that doesn't work, please share the contents of the models/schema.js and models/index.js files?

**Comment by tonybs03** [comment]
> 

Hey there
I managed to solve this issue. Turns out I had codes that were implemented with a older model name, which is why it was bugging.
