### ISSUE TITLE
Push Notification not working when app is in foreground

### ISSUE THREAD

**Issue by GokulDharumar** [aws-amplify/amplify-js#1065]
We followed the sample code 
https://aws.github.io/aws-amplify/media/push_notifications_setup

We used console to send push notification to particular device token and we are getting the message when app is in background. But nothing happens when the app is in foreground.

**Comment by haverchuck** [comment]
Hi @GokulDharumar ,

Thanks for reaching out!

It sounds like this might be typical behavior for foreground apps.

Are you handling the notification using an override of the [onMessageReceived](https://firebase.google.com/docs/cloud-messaging/android/receive) method?

**Comment by GokulDharumar** [comment]
@haverchuck,
 Thanks for the response. We are not doing android version. We are implementing it using react-native. We use the below code

PushNotification.onNotification((notification) => {
  });

**Comment by haverchuck** [comment]
@GokulDharumar 
You are using the react-native-push-notification npm package?
And if so, is the onNotification function receiving the notification datat when the app is in the foreground, but just not popping in the ui?

**Comment by GokulDharumar** [comment]
@haverchuck 
Yes you are right... we are using 
import { PushNotification } from 'aws-amplify-react-native';

Amplify.configure(aws_exports);
PushNotification.configure(aws_exports);
PushNotification.onNotification((notification) => {
    console.log('in app notification', notification);   
  });
We are getting message on the console but not popping up in the phone .

Thanks for the reply

**Comment by haverchuck** [comment]
@GokulDharumar 

I am marking this as a feature request.

**Comment by GokulDharumar** [comment]
@haverchuck ,
 Thanks for the update. Also i have another question/doubt. Right now i don't see any actions on the notification pop up. Is it possible to add actions to the notification? Or if it is already there can you please point me to the right documentation?

Thanks again for the help

**Comment by haverchuck** [comment]
@GokulDharumar I don't believe we have action support yet, but this too is a great feature request.

**Comment by pribadi1st** [comment]
@haverchuck , is the current version able to show the pop up when the application in foreground ?
like the bacgkround and killed state.

**Comment by mlabieniec** [comment]
This is a function of the operating system. The OS doesn't show notifications while the app is in the foreground. The push listeners are setup and the OS displays them when the app is not active which is the part of the point of push notifications in general. To handle the notification when the app is in the foreground, you would need to just listen to the notification listener via the native module and handle appropriately yourself within the app (generally you don't want to show OS notifications while the app is in the foreground but handle the UX within the app).
