### ISSUE TITLE
Make PushNotifications compatible with Android 12

### ISSUE THREAD

**Issue by estebandiazfront** [aws-amplify/amplify-js#10676]
### Is this related to a new or existing framework?

React Native

### Is this related to a new or existing API?

Push Notifications

### Describe the feature you'd like to request

I was making a test with a react native app to use push notifications, all the setup done natively was properly configured as the docs stated. However, when I test sending a message to a device with Android 12, the push notification is not displayed but its handled in the background by this [code](https://docs.amplify.aws/lib/push-notifications/working-with-api/q/platform/react-native/) 

Running `adb logcat` throws this:

`RNPushNotificationHelper: java.lang.IllegalArgumentException: com.myapp: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.`

I would like to have the ability to send push notifications to devices with Android 12.

### Describe the solution you'd like

Declaring a variable to handle all android versions
`private static final int pendingFlags = Build.VERSION.SDK_INT >= Build.VERSION_CODES.S ? PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE : PendingIntent.FLAG_UPDATE_CURRENT;
` and using it across all instances of `PendingIntent.FLAG_UPDATE_CURRENT` inside the file [RNPushNotificationHelper](https://github.com/aws-amplify/amplify-js/blob/main/packages/pushnotification/android/src/main/java/com/amazonaws/amplify/pushnotification/modules/RNPushNotificationHelper.java#L81)

I attach the entire file modified.
[helper.txt](https://github.com/aws-amplify/amplify-js/files/10015704/helper.txt)

I have test this solution on my Emulator and it works.
![pinpoint](https://user-images.githubusercontent.com/84983049/202011480-90846ef3-dbe6-45cf-815e-f2500cf6bf0b.png)

### Describe alternatives you've considered

None

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by tannerabread** [comment]
Hi @estebandiazfront, this is a known issue and is being tracked in issue #10252 
There are plans to fix this in future versions but without a definite timeline
There are also some workarounds in the linked issue

I am going to close this issue in favor of the previous one but will note your solution internally

**Comment by tannerabread** [comment]
@estebandiazfront would you be interested in opening a PR to implement this?
