### ISSUE TITLE
Unable to safely call `unsubscribe` on an AppSync subscription in some cases

### ISSUE THREAD

**Issue by bellkev** [aws-amplify/amplify-js#1068]
With React Native on iOS, after locking the screen and reopening, calling `unsubscribe` on an AppSync subscription (using Amplify version 0.4.4) results in the following error from paho-mqtt:

```
AMQJS0011E Invalid state not connected.
```

The tricky thing is that wrapping it in a try/catch doesn't help, because Zen Observables [rethrow errors](https://github.com/zenparsing/zen-observable/blob/3d059a3a46421224135d876136a694fd9e35c098/src/Observable.js#L44) that happen in cleanup, and unhandled exceptions cause the app to crash in React Native.

My current workaround for now is to use the [machinery](https://github.com/zenparsing/zen-observable/blob/3d059a3a46421224135d876136a694fd9e35c098/test/setup.js) from Zen-Observables' tests to suppress those errors. That seems hacky and wrong though... (Actually, that doesn't work on the Android runtime I tested, so I just forked zen-observable.)

Maybe I'm missing something about this hostReportError convention for observables?

**Comment by bellkev** [comment]
(As a debugging tip, I could only get the issue to occur on a phone, but I could debug it on a desktop by setting a breakpoint [here](https://github.com/eclipse/paho.mqtt.javascript/blob/master/src/paho-mqtt.js#L921) and setting `this.connected = false` in the console.)

**Comment by EthanRBrown** [comment]
I have been experiencing this as well (ReactDOM, desktop browser), though I haven't been able to nail down exactly when/why it occurs.  I'm calling `unsubscribe` on `componentDidUnmount`

**Comment by elorzafe** [comment]
This issue was fixed. Can you try version 1.1.3?

**Comment by EthanRBrown** [comment]
Will do; I should have checked the version first.  We're pretty far
behind.  Thanks for replying, and sorry for the trouble.
