### ISSUE TITLE
DataStore error when deleting optional @hasOne relationship when empty

### ISSUE THREAD

**Issue by mmoulton** [aws-amplify/amplify-js#10685]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

DataStore

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 274.03 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
    Yarn: 1.22.1 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v14.18.2/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 94.0.2
    Safari: 16.0
  npmPackages:
    aws-amplify: ^4.3.43 => 4.3.43 
    typescript: ^4.5.5 => 4.7.4 (3.9.10, 4.4.4)
  npmGlobalPackages:
    @aws-amplify/cli: 8.5.1
```

</details>

### Describe the bug

DataStore is throwing `Failed to execute 'get' on 'IDBIndex': The parameter is not a valid key.` when attempting to delete a model that contains a `@hasOne` relationship that is optional and that relationship is not set on the model being removed.

The original error starts here:
https://github.com/aws-amplify/amplify-js/blob/b3c507f78089dac3e329ff3c748284f642fcc3de/packages/datastore/src/storage/adapter/IndexedDBAdapter.ts#L911

However I traced the root of the issue to this block here:

https://github.com/aws-amplify/amplify-js/blob/b3c507f78089dac3e329ff3c748284f642fcc3de/packages/datastore/src/storage/adapter/IndexedDBAdapter.ts#L889-L890

It seems that when the relationship is not defined `value` will be `null`, making `values` equal `[null]`.

This is a problem for the break condition defined here:

https://github.com/aws-amplify/amplify-js/blob/b3c507f78089dac3e329ff3c748284f642fcc3de/packages/datastore/src/storage/adapter/IndexedDBAdapter.ts#L904 

Since `values` being `[null]` will not satisfy this condition, as it should.

### Expected behavior

To be able to delete models with `@hasOne` relationships.

### Reproduction steps

1) Define a model with a `@hasOne` relationship to another model where the relationship is not required.
2) Create a now instance of the 'parent' model.
3) Attempt to delete the 'parent' model.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by dpilch** [comment]
I was able to reproduce. Investigating a fix.

**Comment by dpilch** [comment]
A patch was released in V5. Please upgrade to aws-amplify@5.0.3 or downgrade to aws-amplify@4.3.37. The patch will be backported to V4 in the next few days.

**Comment by chrisbonifacio** [comment]
@mmoulton closing this as fixed. Please upgrade and let us know if this is resolved on your end afterwards. Thank you!
