### ISSUE TITLE
How to add an Axios Interceptor to all Auth calls and to all API calls as well?

### ISSUE THREAD

**Issue by josoroma-zz** [aws-amplify/amplify-js#1069]
How to add an Axios Interceptor to all Auth calls and to all API calls as well?

Thanks!

**Comment by haverchuck** [comment]
@josoroma 

Thanks for reaching out... Amplify already uses axios under the hood in it's API module, but I don't think there is an OOB way to define your own intercepters.  Can you let us know a little bit more about your use case?

In any case, I'm marking this as a feature request.

**Comment by josoroma** [comment]
@haverchuck it comes up because I need to add a kind of global interceptor to catch all failure responses.

**Comment by haverchuck** [comment]
Thanks @josoroma - We will leave this open as a feature request.

**Comment by josoroma** [comment]
Hi!

Any news on adding our own interceptors? it would be really useful.

Thanks!

**Comment by elorzafe** [comment]
@josoroma what are trying to do by adding a global interceptor? Is only to have on a single point for error handling, or you are trying something else?

**Comment by rdsedmundo** [comment]
+1. This is useful for error handling as OP suggested, and another use case is for handling the global "loading state" of the app, i.e if a request is being made, if it's not, etc.

**Comment by undefobj** [comment]
@josoroma @rdsedmundo We do expose errors though and state which we can enhance more with loading properties via Amplify's Hub module: https://aws-amplify.github.io/docs/js/hub

By adding interceptors/middlware we'd be introducing more complexity into the network requests, whereas Amplify aims for simple design and automatically handling things for you. So if the use cases are better Error notification of failures and loading state (which we'd need to better define) could we just give better eventing through Hub of these taking place?

**Comment by sachinh19** [comment]
Is there a way we can set a timeout on http calls? Also what is the default http timeout for amplify? Is there any documentation on this?

**Comment by srchulo** [comment]
@undefobj Also, it would be nice to use this to refresh tokens before API calls. I'm getting errors from API calls sending no authentication token. `{"message":"Missing Authentication Token"}`

**Comment by Visible-Radio** [comment]
> @undefobj but it looks like Auth via Hub doesn't publish things like a failed API call and the reason? My use case is that for unauthorized calls, I'd like to redirect the user to the login page if their tokens have expired.

I've got a similar use case and am wondering what the best way to handle it is.

**Comment by pedro199288** [comment]
How is this feature request going? I have a use case for it where I would like to use `login_hint` from google oauth (https://developers.google.com/identity/protocols/oauth2/openid-connect) as a query parameter when using `Auth.federatedSignIn` from amplify.

**Comment by thefat32** [comment]
You can use interceptors with Amplify if your project is set to use the same axios version than the lib. You can check it with `npm ls axios`

Example:
```sh
PS C:\Projects\my-project> npm ls axios
my-project@0.1.0 C:\Projects\my-project
├─┬ @types/axios@0.14.0
│ └── axios@0.26.0 deduped
├─┬ aws-amplify@4.3.14
│ ├─┬ @aws-amplify/api@4.0.32
│ │ └─┬ @aws-amplify/api-rest@2.0.32
│ │   └── axios@0.21.4
│ └─┬ @aws-amplify/storage@4.4.15
│   └── axios@0.21.4
└── axios@0.26.0
```

In the command you can see my project was using `axios@0.26.0` and amplify libs `axios@0.21.4`. So changing my package.json to use `axios@0.21.4`, will install only one axios instance for the whole project in node_mopdules and your global interceptors will work.

```diff
-"axios": ^"0.26.0",
+"axios": "0.21.4",
```

**Comment by hoseinsoleymani** [comment]
@thefat32 How can we implement it in code? Would u pls provide an example? I try to use that but it's not worked for me.

**Comment by thefat32** [comment]
@hoseinsoleymani if you are using yarn in your project just add this to package.json

```json
  "resolutions": {
    "axios": "^1.4.0"
  }
```

This will force use of same axios version for every package in your repo

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), we'll close this issue out for a few reasons. Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information on v6! 

With such a well documented workaround in this issue via @thefat32's comment ([here](https://github.com/aws-amplify/amplify-js/issues/1069#issuecomment-1221062027)), `axios` version being updated to 1.6.0 (as of v5.3.12 if you're still on v5), and our desire to limit the amount of complexity introduced, I think this issue can be closed.
