### ISSUE TITLE
Auth.currentUserInfo() is returning null response, when page reload

### ISSUE THREAD

**Issue by sadashivm** [aws-amplify/amplify-js#10694]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication, Storage

### Amplify Categories

auth, storage, function

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I have used import { Auth } from 'aws-amplify'; in my react project. 

I have used below methods in my projects,

`"aws-amplify": "^4.3.30",`

Auth.signIn(userName)
Auth.sendCustomChallengeAnswer(authUser, code)

The method Auth.currentUserInfo(); returns null value if I do page refresh.

And also Unable to download profile image from storage. below is the download profile image code,
`import { Storage } from 'aws-amplify';`

  `useEffect(() => {`
    `if (userID) {`
    `  downloadProfileImage()`
    `    .catch(err => {`
   `       console.log('Failed to Download Image: ', err);`
  `      });`
 `   }`
`  }, [userID]);`

  `async function downloadProfileImage () {`
   ` const s3Path = `profile/${userID}/profile.jpeg`;`
    `const result = await Storage.get(s3Path, { expires: 60 });`
    `setSrcImage(result);`
  `}`

It is throwing a below error,

Failed to Download Image:  Error: No credentials
    at AWSS3Provider.<anonymous> (AWSS3Provider.js:489:1)
    at step (AWSS3Provider.js:140:1)
    at Object.next (AWSS3Provider.js:71:1)
    at fulfilled (AWSS3Provider.js:25:1).
    
    

### Expected behavior

Auth.currentUserInfo() API returns response, even user do refresh.

### Reproduction steps

1. install the 'aws-amplify' npm package.
2 Import Auth from 'aws-amplify'
3.  Call the Auth.currentUserInfo() method
4.  Do a page refresh.
5.  The above method returns null value

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

![Download_Image_Error](https://user-images.githubusercontent.com/10355473/203058364-6a8df6bb-ab86-42a5-8cda-79dd3e4aa081.png)

![image](https://user-images.githubusercontent.com/10355473/203058431-a191b74b-9ddf-40a2-816c-b873e9414818.png)

![image](https://user-images.githubusercontent.com/10355473/203058611-262f6944-17e9-488a-a0c1-c2e91c7a982a.png)

**Comment by alexlevy0** [comment]
const user = await Auth.currentAuthenticatedUser()

**Comment by nadetastic** [comment]
Hi @sadashivm 👋, just to confirm are you using a custom Auth flow here? Meaning adding the Auth Lambdas and configuring the client with `Auth.configure({ authenticationFlowType: 'CUSTOM_AUTH' })` 

Based on the errors, it sounds like the user is never signed in successfully and wanted to confirm the above

**Comment by sadashivm** [comment]
@nadetastic thank you for reply, here is the amplify configuration,

![image](https://user-images.githubusercontent.com/10355473/203470813-78a7bc65-709b-4c3e-a55e-ac5cf2d94c90.png)

Please let me know if you need further information.

**Comment by sadashivm** [comment]
Apart from that,

**`const user = await Auth.currentSession(); `**

is also returning null values when user do page refresh.

**Comment by nadetastic** [comment]
@sadashivm Do you get session data before you refresh from `Auth.currentUserInfo()`

Also, looking at local storage, do you see something similar to the screenshot _before_ refreshing?

![localstorage](https://user-images.githubusercontent.com/87148442/203625030-758a6214-d5a1-47dc-add1-f2d7dcbdc337.png)



If you are experiencing the above, then im wondering if a refresh is clearing local storage.

**Comment by sadashivm** [comment]
@nadetastic yes  I can see the local storage data before refreshing, 
here is the screenshot,

![image](https://user-images.githubusercontent.com/10355473/203703377-e9554602-b160-4608-a755-3bb5acccc3ca.png)

**Comment by nadetastic** [comment]
@sadashivm It definitely looks like the session data is being cleared on refresh and Im not quite sure why - are you able to reproduce the issue on a different browser?

**Comment by nadetastic** [comment]
@sadashivm follow up on this, were you able to get this resolved?
