### ISSUE TITLE
Multiple Authorization Types not work on React native

### ISSUE THREAD

**Issue by didar-dev** [aws-amplify/amplify-js#10735]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

DataStore

### Amplify Categories

auth, api

### Environment information

<details>

```
# Put output below this line

  System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 4.28 GB / 15.89 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.819.0), Chromium (107.0.1418.62)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @babel/core: ^7.20.5 => 7.20.5
    @react-native-async-storage/async-storage: 1.17.11 => 1.17.11
    @react-native-community/masked-view: 0.1.11 => 0.1.11
    @react-native-community/netinfo: 9.3.5 => 9.3.5
    @react-navigation/native: 6.0.13 => 6.0.13 (3.8.4)
    @react-navigation/native-stack: 6.9.1 => 6.9.1
    @types/react: ^18.0.26 => 18.0.26
    @types/react-native: ^0.70.7 => 0.70.7
    HelloWorld:  0.0.1
    amazon-cognito-identity-js: 5.2.12 => 5.2.12 (6.0.1)
    aws-amplify: ^5.0.3 => 5.0.3
    expo: ^47.0.8 => 47.0.8
    expo-font: 11.0.1 => 11.0.1
    expo-linear-gradient: ~12.0.1 => 12.0.1
    expo-localization: ~14.0.0 => 14.0.0
    expo-notifications: ~0.17.0 => 0.17.0
    expo-status-bar: 1.4.0 => 1.4.0
    expo-updates: 0.14.7 => 0.14.7
    hermes-inspector-msggen:  1.0.0
    i18n-js: 4.2.0 => 4.2.0
    i18next: 22.0.6 => 22.0.6
    react: 18.0.0 => 18.0.0
    react-hook-form: 7.40.0 => 7.40.0
    react-i18next: 12.0.0 => 12.0.0
    react-native: 0.69.6 => 0.69.6
    react-native-gesture-handler: 2.5.0 => 2.5.0
    react-native-localize: ^2.2.4 => 2.2.4
    react-native-paper: 5.0.0-rc.10 => 5.0.0-rc.10
    react-native-reanimated: 2.13.0 => 2.13.0
    react-native-reanimated-carousel: 3.1.5 => 3.1.5
    react-native-redash: 18.1.0 => 18.1.0
    react-native-safe-area-context: 4.4.1 => 4.4.1
    react-native-screens: 3.18.2 => 3.18.2
    react-native-svg: 13.6.0 => 13.6.0
    react-navigation: 4.4.4 => 4.4.4
    typescript: 4.9.3 => 4.9.3
  npmGlobalPackages:
    @aws-amplify/cli: 10.5.0
    depcheck: 1.4.3
    eas-cli: 2.7.1
    expo-cli: 6.0.8
    yarn: 1.22.19


```

</details>

### Describe the bug

I have two Data model

One is  Subscriptions that Owner-based is Enabled 
The other one is Books which is public and Anyone authenticated with API Key can Read Books
So in this scenario, I have to configure multiple authorization types 

but when I use this 
![image](https://user-images.githubusercontent.com/70973049/205367730-9d2dff10-e3e7-4bb2-a849-5cd1f903afdc.png)

The Subscriptions  Model works fine but the Books model doesn't work 
![image](https://user-images.githubusercontent.com/70973049/205368158-7837ef15-672b-4bf0-b37c-5ad395debaf6.png)

I change the Default authorization mode to Cognito User Pool but same error and nothing changes

and also when i don't use multiple authorization types 
The book's model works fine but the Subscriptions model doesn'tI

### Expected behavior

Both  Subscriptions and Books models should work fine when i configure multiple authorization types I

### Reproduction steps

1. Created and Configured all settings on amplify studio ( browser )
2. after all is done add Pulled to the project and the bug happens 

### Code Snippet

```javascript
// Put your code below this line.
import { StatusBar } from "expo-status-bar";
import React, { useEffect, useState } from "react";
import { Text, View, StyleSheet, I18nManager, Platform } from "react-native";
import Navigation from "./src/navigation";
import { Amplify, AuthModeStrategyType } from "aws-amplify";
import awsconfig from "./src/aws-exports";
import fonts from "./constants/Fonts";
import { useFonts } from "expo-font";
import * as Updates from "expo-updates";
Amplify.configure({
  ...awsconfig,
  DataStore: {
    authModeStrategyType: AuthModeStrategyType.MULTI_AUTH,
  },
});
import {
  MD3LightTheme as DefaultTheme,
  Provider as PaperProvider,
} from "react-native-paper";
const theme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: "black",
    secondary: "yellow",
  },
  animation: {
    scale: 1.0,
  },
};

const App = () => {
  const [fontsLoaded] = useFonts(fonts);
  if (!fontsLoaded) {
    return console.log("Loading...");
  }

  const shouldBeRTL = true;

  if (shouldBeRTL !== I18nManager.isRTL && Platform.OS !== "web") {
    I18nManager.allowRTL(shouldBeRTL);
    I18nManager.forceRTL(shouldBeRTL);
    Updates.reloadAsync();
  }
  return (
    <View
      style={{
        flex: 1,
      }}
    >
      <PaperProvider theme={theme}>
        <Navigation />
        <StatusBar style="auto" />
      </PaperProvider>
    </View>
  );
};

export default App;

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:7ad23e71-6c28-4392-9b8XXXXXXXXXa",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_LEjhy4Jz9",
    "aws_user_pools_web_client_id": "565klkmosd847aXXXXXXXXX",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "PREFERRED_USERNAME",
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 6,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://dyma742XXXXXXXXXcwxteg23hi.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2iskbterhXXXXXXXXXyo4"
};

export default awsmobile;

### Mobile Device

iPhone 11 pro max

### Mobile Operating System

IOS 16.1.1

### Mobile Browser

Expo

### Mobile Browser Version

Latest SDK

**Comment by didar-dev** [comment]
Hi @chrisbonifacio, I uploaded the source code to a private repo, I will add you as a collaborator 
if you look at  src/screens/HomeScreen/HomeScreen.js 

in this time  AuthModeStrategyType.MULTI_AUTH Used

The subscriptions Model works fine since it owner based 
but none of the other models work like Sliders, Books, Grades

The repo name is "Qutabe"

**Comment by chrisbonifacio** [comment]
Hi @didar-dev sorry, for the delay. If you are still experiencing this issue, can you confirm that the user trying to sync/read the other models either belongs to the `Admin` User Pool group or is not logged in? I pulled your project down and see that models such as `Books` or `Sliders` are restricted to Admin group users or guest users (allow: public).

```graphql
type Books @model @auth(rules: [{allow: groups, groups: ["Admin"], operations: [read, update, delete, create]}, {allow: public, operations: [read]}]) {
  id: ID!
  Name: String
  Image: String
  About: String
  Grade: String
  Subjects: [String]!
  Lessons: [String]
  Available: Boolean
}
```

If you want to enable logged in users to have read access to a model without belonging to a user group or being the owner of a record, you can add the `{ allow: private }` auth rule to the model.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
