### ISSUE TITLE
Getting my node backend to Amplify

### ISSUE THREAD

**Issue by jbenite2** [aws-amplify/amplify-js#10751]
### Which Specific Feature is your question related to?

Amplify backend

### Question

My stack is composed of a React frontend and a Node backend that serves as the middleware between the client and the Planet Scale relational database. I got my domain set up and the React app is running without any problems. However, I'm having trouble connecting my existing index.js to Amplify so it runs simultaneously with the React app. Any ideas on how to have my frontend communicate simultaneously with my **existing** backend in Amplify?

**Comment by tannerabread** [comment]
Hi @jbenite2
Our library allows manual import of backend resources that are supported by Amplify. Check out the [documentation here](https://docs.amplify.aws/lib/client-configuration/configuring-amplify-categories/q/platform/js/). Let me know if this is what you were looking for

**Comment by tannerabread** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and are in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
