### ISSUE TITLE
Querying using Datastore.query function returning a Promise type for related Data Models

### ISSUE THREAD

**Issue by moeabbas92** [aws-amplify/amplify-js#10771]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

DataStore

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M2
    Memory: 857.33 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.2.0 - /opt/homebrew/bin/node
    npm: 8.19.3 - /opt/homebrew/bin/npm
    Watchman: 2022.12.05.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 108.0.5359.98
    Safari: 15.6
  npmPackages:
    @aws-amplify/ui-react: ^4.0.3 => 4.2.0 
    @aws-amplify/ui-react-internal:  undefined ()
    @emotion/react: ^11.10.5 => 11.10.5 
    @emotion/styled: ^11.10.5 => 11.10.5 
    @mui/material: ^5.10.17 => 5.10.17 
    @testing-library/jest-dom: ^5.16.5 => 5.16.5 
    @testing-library/react: ^13.4.0 => 13.4.0 
    @testing-library/user-event: ^13.5.0 => 13.5.0 
    aws-amplify: ^5.0.4 => 5.0.5 
    react: ^18.2.0 => 18.2.0 (18.1.0, 16.14.0)
    react-dom: ^18.2.0 => 18.2.0 
    react-scripts: 5.0.1 => 5.0.1 
    react-swipeable-views: ^0.14.0 => 0.14.0 
    web-vitals: ^2.1.4 => 2.1.4 
  npmGlobalPackages:
    npm: 8.19.3

```

</details>

### Describe the bug

When querying a Model using the Datastore.query function, I am expecting my query result to contain related Data Models but instead it contains my related Data Models as Promise data types.

### Expected behavior

The query should result in the related Data Models contained in the json block so that I am able to access them.

### Reproduction steps

1. Query Data Model using Datastore.query function
2. Print out the result of this query
3. Related Data Models should be present in result but they are included as Promises

### Code Snippet

```javascript
// Put your code below this line.
  const [bookings, setBookings] = useState([])

  const getBookings = async () => {
    const data = await DataStore.query(Booking)
    setBookings(data)
  }

  useEffect(() => {
    getBookings()
  }, [])

  console.log(bookings)
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

<img width="1246" alt="Screenshot 2022-12-13 at 09 50 44" src="https://user-images.githubusercontent.com/115354873/207295873-594d84e3-20f3-4cd5-ad7e-f8edbb0c8fde.png">
Screenshot of the console.log(bookings) result

**Comment by chrisbonifacio** [comment]
Hi @moeabbas92 👋 thanks for raising this issue. Sounds like you might've recently upgraded your `aws-amplify` package to the latest major version. That comes with some breaking changes such as this one where related fields are lazy loaded in DataStore.

For more info on querying relations with the new lazy loading syntax, please refer to the docs:

https://docs.amplify.aws/lib/datastore/relational/q/platform/js/#querying-relations

**Comment by drmzio** [comment]
@chrisbonifacio I see that there's also an EagerLoading type but I see no documentation on it. Will it be possible to eager load relation fields?
