### ISSUE TITLE
Need to login with different user after logout.

### ISSUE THREAD

**Issue by SagarTS** [aws-amplify/amplify-js#10772]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
Ionic/react

```

</details>

### Describe the bug

When I log out **userA** using Auth.signOut(), and now if I have to log in as userB the Auth.FederatedSignIn({ provider: 'UBWallet'}) directly logs in using the userA credentials. It does not show login page.

### Expected behavior

Show the login page each time user tries to log in.

### Reproduction steps

1. userA logs in
2. userA logs out
3. userB tries to log-in
4. userA gets logged in automatically without any login screen

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by tannerabread** [comment]
Hi @SagarTS, @Sandip-Z
We have an open issue tracking this #4044. Unfortunately, this is a Cognito limitation and we have opened a ticket with that team to try to resolve this.

Please leave +1 and any additional comments on that issue. I believe there is a workaround in the comments that involves signing out in the browser outside of your app. 

We want to consolidate to a single issue so I will close this one for #4044. Thank you!

**Comment by kewur** [comment]
I think the workaround mentioned on that thread is to migrate to FusionAuth and drop Cognito/Amplify

**Comment by SagarTS** [comment]
@kewur a bad workaround is to logout the user from linked account (google or any) from the browser itself. That can be the only solution. And as mentioned on the thread migrating to FusionAuth is there too.
