### ISSUE TITLE
Sync Expressions in DataStore in Amplify@5 with old API's break the sync

### ISSUE THREAD

**Issue by svidgen** [aws-amplify/amplify-js#10785]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

DataStore

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I'm not sure what version/flags of the CLI is necessary to create this scenario. But, I have an "old" sample app wherein the FK fields from some connected models are not available for in the GQL sync query selection set.

I have a `Blog` model where I can provide a `blogOwnerId` at mutation time:

<img width="192" alt="image" src="https://user-images.githubusercontent.com/8375502/208199658-39c06c9a-78a5-4fbd-b9f9-619ad02b5122.png">

However, `blogOwnerId` is not available in the selection set.

<img width="200" alt="image" src="https://user-images.githubusercontent.com/8375502/208199428-acb0bd8a-9e3a-4286-bc84-fd467600a9a5.png">

When I add a `syncExpression` on `Blog`, `blogOwnerId` is included to the selection set on sync, and the sync therefore fails.

### Expected behavior

DataStore should only include these connection/FK fields in the selection set if they're explicitly defined.

### Reproduction steps

🤷

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by micstepper** [comment]
Any updates @svidgen ? Did you find a solution?

**Comment by svidgen** [comment]
@micstepper I started poking at it, but no solution yet. I'm planning on focusing more on this over the next couple weeks.

**Comment by svidgen** [comment]
This fix should be out in yesterday's fix.
