### ISSUE TITLE
Upgrade to Lerna 6 and enable task caching

### ISSUE THREAD

**Issue by isaacplmann** [aws-amplify/amplify-js#10784]
### Describe the feature you'd like to request

I see that you're using Lerna 3.  If you update to Lerna 6, you can enable task caching, which will make so that you don't need to repeat the same work twice.  This will enable a local cache for each developer machine for builds, tests and whatever other scripts you enable.

If you want to share that cache with other developers and your CI, you can run `npx nx connect-to-nx-cloud` and then get a coupon from us for free unlimited distributed caching (since you're an open source repo).

### Describe the solution you'd like

We're happy to have someone from Nx (we're maintaining Lerna now) open a PR if you're interested.  Or we could just have a conversation to talk about any questions you have.

### Describe alternatives you've considered

Say "no thanks" and stay on Lerna 3. :-)

### Is this something that you'd be interested in working on?

- [x] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by abdallahshaban557** [comment]
Hi @isaacplmann, thank you for reaching out! We are interested in the upgrade - would your team be able to submit the PR as you've recommended. We will need to talk that through our internal review process, and then understand what would need to change on our packages.

For the coupon you've mentioned, are there any limitations to that which we should be aware of?

**Comment by isaacplmann** [comment]
The only change that would be needed is bumping the version number of Lerna up to version 6.  There's also a little extra configuration to tell Lerna what should be cached for each task.

The development flow would be identical.  Run the same commands, just get your results faster.

**Comment by isaacplmann** [comment]
The coupon is free for any open source project and gives you unlimited use of the distributed caching service.

**Comment by isaacplmann** [comment]
Let me know if you need any more information from me for the review

**Comment by jimblanc** [comment]
Happy to report we just upgraded to Lerna 6, which will go out in our next release.
