### ISSUE TITLE
Public and private use is not possible for the same project ?

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/amplify-js#10791]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.18.1

### Amplify CLI Version

10.5.2

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

None.

### Describe the bug

With this schema.graphql (and double auth (API_KEY and Cognito_User_Pool)) :

```graphql
type Todopublic @model
@auth(rules: [
{ allow: public }
]){
id: ID!
name: String!
}

type Todoprivate @model
@auth(rules: [
{ allow: owner }
]){
id: ID!
name: String!
}
```

If I set the default authorization to API_KEY, I can deal with Todopublic but not with Todoprivate (while connected).
If I set the default authorization to Cognito Userpool, I can deal with Todoprivate (while connected and even while not connected, so I do not know how owner is set...) but not with Todopublic.

So how to achieve the use of twice ? When I do mutations or queries in AppSync Console it works normally and well.

### Expected behavior

Public and private use.

https://docs.amplify.aws/lib/graphqlapi/mutate-data/q/platform/js/ is a solution for an Angular App.
But I do not manage to import a generated query or mutation.

**Comment by rudyhadoux** [comment]
Yes but I do not manage to import a generated query or mutation.

const createdTodo = await API.graphql({
  query: queries.createTodo,
  variables: {input: todoDetails},
  authMode: 'AWS_IAM'
});

This is a problem query: **queries.createTodo** => impossible to import with Typescript for Angular.

**Comment by rudyhadoux** [comment]
And why is it possible to create an OWNER (Cognito User Pool) object without being connected ? It should be impossible.

**Comment by chrisbonifacio** [comment]
Hi @rudyhadoux 👋 your code snippet making the request suggests that you have configured your API to grant access via an IAM role but your schema does not include an IAM auth rule. I only see `public` and `owner`, which grants access to users/clients with an API key or users authenticated by Cognito User Pools respectively.

If you are trying to use IAM as an auth mode, please update your api by running `amplify update api` and selecting IAM as an additional authorization type. Then, add `{ allow: public, provider: iam }` to your schema.

**Comment by rudyhadoux** [comment]
Yes it is just the documentation example.

For me it is 

const createdTodopublic = await API.graphql({
query: queries.createTodopublic,
variables: {input: todoDetails},
authMode: 'API_KEY'
});

const createdTodoprivate = await API.graphql({
query: queries.createTodoprivate,
variables: {input: todoDetails},
authMode: 'AMAZON_COGNITO_USER_POOLS'
});

But the problem remains. query: queries.createTodo => impossible to import with Typescript for Angular.

**Comment by rudyhadoux** [comment]
I think my issue is a clone of this
https://github.com/aws-amplify/amplify-category-api/issues/373

**Comment by rudyhadoux** [comment]
**For Angular users, API.service.ts (typescript file) is sufficient for simple and unique authorization mode. But it does not work for multiple authorization modes.**

The best feature to create is to generate two functions by example for public and private.

For this example :

type Todo @model
@auth(rules: [
{ allow: public, operations: [read] }, // API_KEY
{ allow: owner, operations: [create, read, update] } // AMAZON_COGNITO_USER_POOLS
]){
id: ID!
text: String!
}

API.service.ts should generate public functions and private functions.

**Comment by rudyhadoux** [comment]
With a CODEGEN TYPESCRIPT that works, import is possible.
