### ISSUE TITLE
Remove React Native from dependency tree

### ISSUE THREAD

**Issue by dustindclark** [aws-amplify/amplify-js#10795]
### Describe the feature you'd like to request

React Native is a massive dependency and is unnecessary for all clients. Remove it from dep tree. Here's the path:

```
└─┬ @aws-amplify/api-graphql@3.0.7
  └─┬ @aws-amplify/core@5.0.7
    └─┬ @aws-sdk/client-cloudwatch-logs@3.6.1
      └─┬ @aws-sdk/middleware-retry@3.6.1
        └─┬ react-native-get-random-values@1.8.0
          └── react-native@0.70.6
```

### Describe the solution you'd like

React Native is a massive dependency and is unnecessary for all clients. Remove it from dep tree. Here's the path:

```
└─┬ @aws-amplify/api-graphql@3.0.7
  └─┬ @aws-amplify/core@5.0.7
    └─┬ @aws-sdk/client-cloudwatch-logs@3.6.1
      └─┬ @aws-sdk/middleware-retry@3.6.1
        └─┬ react-native-get-random-values@1.8.0
          └── react-native@0.70.6
```

### Describe alternatives you've considered

React Native is a massive dependency and is unnecessary for all clients. Remove it from dep tree. Here's the path:

```
└─┬ @aws-amplify/api-graphql@3.0.7
  └─┬ @aws-amplify/core@5.0.7
    └─┬ @aws-sdk/client-cloudwatch-logs@3.6.1
      └─┬ @aws-sdk/middleware-retry@3.6.1
        └─┬ react-native-get-random-values@1.8.0
          └── react-native@0.70.6
```

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by tannerabread** [comment]
Hi @dustindclark we are aware of this dependency and are discussing the steps necessary to remove it.

Please follow issue #9119 for updates

**Comment by dustindclark** [comment]
Thanks. Sorry for the dupe. I swear I searched for this :/

**Comment by abdallahshaban557** [comment]
@dustindclark - don't worry about it! Thank you for reporting this!
