### ISSUE TITLE
Datasore:save does not work

### ISSUE THREAD

**Issue by KYOOBAEKLEE** [aws-amplify/amplify-js#10806]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication, GraphQL API, DataStore

### Environment information

<details>

```
System:
    OS: macOS 12.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 22.53 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 2021.12.20.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 90.1.23.73
    Chrome: 108.0.5359.124
    Safari: 15.6.1
  npmPackages:
    @aws-amplify/ui-react-native: ^1.2.0 => 1.2.0 
    @babel/core: ^7.12.9 => 7.20.7 
    @expo/osascript: ^2.0.33 => 2.0.33 
    @react-native-async-storage/async-storage: ^1.17.11 => 1.17.11 
    @react-native-community/netinfo: 9.3.5 => 9.3.5 
    @react-native-picker/picker: ^2.4.8 => 2.4.8 
    @react-navigation/bottom-tabs: ^6.4.3 => 6.5.2 
    @react-navigation/material-bottom-tabs: ^6.2.7 => 6.2.10 
    @react-navigation/native: ^6.0.16 => 6.1.1 
    @react-navigation/native-stack: ^6.9.4 => 6.9.7 
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: ^6.0.1 => 6.1.1 
    aws-amplify: ^5.0.7 => 5.0.7 
    aws-amplify-react-native: ^7.0.2 => 7.0.2 
    expo: ^47.0.9 => 47.0.9 
    expo-status-bar: ~1.4.2 => 1.4.2 
    hermes-inspector-msggen:  1.0.0 
    react: 18.1.0 => 18.1.0 
    react-devtools: ^4.27.1 => 4.27.1 
    react-native: 0.70.5 => 0.70.5 
    react-native-get-random-values: ^1.8.0 => 1.8.0 
    react-native-paper: ^4.12.5 => 4.12.5 
    react-native-safe-area-context: ^4.4.1 => 4.4.1 
    react-native-screens: ~3.18.0 => 3.18.2 
    react-native-url-polyfill: ^1.3.0 => 1.3.0 
    react-native-vector-icons: ^9.2.0 => 9.2.0 
  npmGlobalPackages:
    @aws-amplify/cli: 10.5.1
    corepack: 0.12.1
    eas-cli: 3.0.0
    expo-cli: 6.0.8
    n: 9.0.0
    npm: 8.15.0
    pm2: 5.1.1
    react-devtools: 4.27.1
    react-native-cli: 2.0.1
```
</details>

### Describe the bug

I worked on this for 7days, and I couldn't solve the problem
{basketDish.Dish.name} doesn't work

seems like, while DataStore.save,  Dish:dish didn't work

----------------------------------------------------------------
```
  const addDishToBasket = async (dish, quantity) => {
    console.log("add dish to basket", dish, quantity);

    let theBasket = basket || (await createNewBasket());
    console.log("theBasket.id",theBasket.id)

    const newDish = await DataStore.save(
      new BasketDish({ quantity ,Dish: dish, basketID: theBasket.id, })
    );
    console.log("BasketDish", BasketDish)
    console.log("newDish", newDish)
    setBasketDishes([...basketDishes, newDish]);
  };
```
  
  ----------------------------------------------------------------

`    console.log("add dish to basket", dish, quantity);`
I could see 'dish' comes right.

` LOG  add dish to basket {"_deleted": null, "_lastChangedAt": 1671372527456, "_version": 2, "createdAt": "2022-12-18T14:08:26.885Z", "description": "taste good", "id": "7354b920-af42-4cd1-832e-8f3e42c61ae9", "image": null, "name": "downtown burger", "price": 2.1, "restaurantID": "f5cdaf6c-64f7-4cbc-bdb2-19fcace7f65f", "updatedAt": "2022-12-18T14:08:47.432Z"} 1`

but console.log("newDIsh", newDish) comes like this : 
`LOG newDish {"_deleted": undefined, "_lastChangedAt": undefined, "_version": undefined, "basketID": "725bb4fc-2656-4082-ac03-85c7f844168f", "dishID": "7354b920-af42-4cd1-832e-8f3e42c61ae9", "id": "5159dc5f-960c-41b5-904a-c2df6813c03b", "quantity": 1}`

Can't find Dish from newDish.

there is my BasketDish and Dish model

![image](https://user-images.githubusercontent.com/120049647/209133625-9c2989cd-ac1d-4e40-9421-655e3a6b30e0.png)

### Expected behavior

I expected to happen like : 

{"_deleted": undefined, "_lastChangedAt": undefined, "_version": undefined, "basketID": "725bb4fc-2656-4082-ac03-85c7f844168f", "dishID": "7354b920-af42-4cd1-832e-8f3e42c61ae9", "id": "d213373f-9282-40ed-a668-8bcb570e1361", "quantity": 1, Dish: {"_deleted": null, "_lastChangedAt": 1671372527456, "_version": 2, "createdAt": "2022-12-18T14:08:26.885Z", "description": "taste good", "id": "7354b920-af42-4cd1-832e-8f3e42c61ae9", "image": null, "name": "downtown burger", "price": 2.1, "restaurantID": "f5cdaf6c-64f7-4cbc-bdb2-19fcace7f65f", "updatedAt": "2022-12-18T14:08:47.432Z"}} 

so I can use basketDish.Dish.name

### Reproduction steps

........................

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @KYOOBAEKLEE 👋 thanks for raising this issue. May I ask why you are only passing the `basketID` to `DataStore.save` and not the `basket` record itself?

**Comment by KYOOBAEKLEE** [comment]
Hi @chrisbonifacio Thank you for your time, 

```
const newDish = await DataStore.save(
      new BasketDish({ quantity , Dish: dish, basket: theBasket })
    );
```

First, I've tried suggestion code and I got a warn, still didn't work and couldn't save it to Datastore
`WARN  [WARN] 11:26.283 DataStore {"cause": {"locations": [[Object]], "message": "Variable 'input' has coerced Null value for NonNull type 'ID!'", "path": null}, "errorInfo": undefined, "errorType": "BadRecord", "localModel": {"_version": undefined, "basketDishDishId": "4d2b8d8f-0ed2-414c-b23b-9570fe77b030", "basketID": undefined, "createdAt": undefined, "id": "91748a92-8bb7-40a4-9036-c7c6445de1f1", "quantity": 1, "updatedAt": undefined}, "message": "Variable 'input' has coerced Null value for NonNull type 'ID!'", "operation": "Create", "process": "mutate", "recoverySuggestion": "Ensure app code is up to date, auth directives exist and are correct on each model, and that server-side data has not been invalidated by a schema change. If the problem persists, search for or create an issue: https://github.com/aws-amplify/amplify-js/issues", "remoteModel": null}`

Second, to answer why I am passing basketID to DataStore.save 
1) Basket @hasMany BasketDishes, in BasketDish model there is basketID(string type) as relationship source 

Basket hasMany BasketDish, BasketDish hasOne Dish

In case it can be helpful, there is schema and my BasektConext code,
<schema.graphql>
```
type Basket @model @auth(rules: [{allow: public}]) {
  id: ID!
  restaurantID: ID! @index(name: "byRestaurant")
  userID: ID! @index(name: "byUser")
  BasketDishes: [BasketDish] @hasMany(indexName: "byBasket", fields: ["id"])
}

type BasketDish @model @auth(rules: [{allow: public}]) {
  id: ID!
  quantity: Int!
  Dish: Dish @hasOne
  basketID: ID! @index(name: "byBasket")
}

type Dish @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String!
  image: String
  description: String
  price: Float!
  restaurantID: ID! @index(name: "byRestaurant")
}
```
-----------------------------------
```
import { createContext, useState, useEffect, useContext } from "react";
import { DataStore } from "aws-amplify";
import { Basket, BasketDish } from "../models";
import { useAuthContext } from "./AuthContext";

const BasketContext = createContext({});

const BasketContextProvider = ({ children }) => {
  const { dbUser } = useAuthContext();

  const [restaurant, setRestaurant] = useState(null);
  const [basket, setBasket] = useState(null);
  const [basketDishes, setBasketDishes] = useState([]);
  
 
  useEffect(() => {
    DataStore.query(Basket, (b) => b.and(b => [
        b.restaurantID.eq(restaurant.id),
        b.userID.eq(dbUser.id)
      ])).then(
        (baskets) => setBasket(baskets[0])
        );
  },[dbUser, restaurant]);
  
  // useEffect(() => {
  //   DataStore.query(Basket, (b) =>
  //     b.restaurantID.eq(restaurant.id).userID.eq(dbUser.id)
  //   ).then((baskets) => setBasket(baskets[0]));
  // }, [dbUser, restaurant]);



  useEffect(() => {
    if (basket) {
      DataStore.query(BasketDish, (bd) => bd.basketID.eq(basket.id)).then(setBasketDishes);
      
    }
  }, [basket]);
  


  const addDishToBasket = async (dish, quantity) => {
    console.log("add dish to basket", dish, quantity);
    console.log("type of dish", typeof(dish))
    // 기본 Basket이 존재한다면 그것을 선택하고, 없다면 새로운 Basket을 생성하여 선택한다.
    let theBasket = basket || (await createNewBasket());
    console.log("theBasket.id",theBasket.id)
    // 새로운 Dish를 새로운 Basket Dish를 생성하며 그곳에 추가하는데, 수량, Dish 객체(모델), 
    const newDish = await DataStore.save(
      new BasketDish({ 
        quantity: quantity,
        Dish: dish, 
        basketID: theBasket.id
      })
    );
    console.log("BasketDish", BasketDish)
    console.log("newDish", newDish)
    setBasketDishes([...basketDishes, newDish]);
  };

  const createNewBasket = async () => {
    const newBasket = await DataStore.save(
      new Basket({ userID: dbUser.id, restaurantID: restaurant.id })
    );
    
    setBasket(newBasket);
    
    return newBasket;
  };

  return (
    <BasketContext.Provider
      value={{
        addDishToBasket,
        setRestaurant,
        restaurant,
        basket,
        basketDishes,
      }}
    >
      {children}
    </BasketContext.Provider>
  );
};

export default BasketContextProvider;

export const useBasketContext = () => useContext(BasketContext);
```


Am I doing wrong with DataStore Save..? I was studying from [here](https://youtu.be/WFo_IxhBxF4?list=PLY3ncAV1dSVBc5v8jfQXQZrfZO93X3PGP&t=16085)
* Sorry that, my English can be bad, it's not my mother language.

**Comment by chrisbonifacio** [comment]
I think because you're using DataStore, the `hasOne` relationship needs to be replaced with `@belongsTo`. Can you try that?

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!

**Comment by Ayush7455** [comment]
import { useNavigation } from "@react-navigation/native";
import {User,ChatRoom,ChatRoomUser} from "../src/models"
import React from "react";
import {Text,View,Image, Pressable} from "react-native";
import {DataStore} from "@aws-amplify/datastore";
import { Auth } from "aws-amplify";
const UserItem=({user})=>{
  const navigation=useNavigation()
  const onPress=async()=>{
   const newChatRoom=await DataStore.save(new ChatRoom({newMessages:0}))
   const authUser=await Auth.currentAuthenticatedUser()
   const dbUser=await DataStore.query(User,authUser.attributes.sub)
   await DataStore.save(new ChatRoomUser({User:dbUser,ChatRoom:newChatRoom}))
   await DataStore.save(new ChatRoomUser({User:user,ChatRoom:newChatRoom}))
   navigation.navigate("ChatRoom",{id:newChatRoom.id})
  }
    return (
        <Pressable onPress={onPress} style={{flexDirection:"row",padding:10}}>
        
       <Image source={{
        uri:user.imageUri
       }} style={{width:50,height:50,borderRadius:25,marginRight:10}}/>

       <View style={{flex:1,justifyContent:"center"}}>
        <View style={{flexDirection:"row",justifyContent:"space-between"}}>
        <Text style={{fontWeight:"bold",fontSize:18}}>{user.name}</Text>
        </View>
       </View>
       </Pressable>
    )

}
export default UserItem
Getting the warning :
[WARN] 17:29.380 DataStore {"cause": {"locations": [[Object]], "message": "Variable 'input' has coerced Null value f
or NonNull type 'ID!'", "path": null}, "errorInfo": undefined, "errorType": "BadRecord", "localModel": {"_version": undefin
ed, "chatRoomId": undefined, "createdAt": undefined, "id": "08c6d89c-b6a3-42e5-b8c0-ff4b2fea7605", "updatedAt": undefined, 
"userId": undefined}, "message": "Variable 'input' has coerced Null value for NonNull type 'ID!'", "operation": "Create", "
process": "mutate", "recoverySuggestion": "Ensure app code is up to date, auth directives exist and are correct on each mod
el, and that server-side data has not been invalidated by a schema change. If the problem persists, search for or create an
 issue: https://github.com/aws-amplify/amplify-js/issues", "remoteModel": null}
 WARN  [WARN] 17:29.647 DataStore {"cause": {"locations": [[Object]], "message": "Variable 'input' has coerced Null value f
or NonNull type 'ID!'", "path": null}, "errorInfo": undefined, "errorType": "BadRecord", "localModel": {"_version": undefin
ed, "chatRoomId": undefined, "createdAt": undefined, "id": "7025dd76-2631-478b-bdd7-fc6c5b948752", "updatedAt": undefined, 
"userId": undefined}, "message": "Variable 'input' has coerced Null value for NonNull type 'ID!'", "operation": "Create", "
process": "mutate", "recoverySuggestion": "Ensure app code is up to date, auth directives exist and are correct on each mod
el, and that server-side data has not been invalidated by a schema change. If the problem persists, search for or create an

**Comment by satishkumarc54** [comment]
import { useNavigation } from "@react-navigation/native";
import {User,ChatRoom,ChatRoomUser} from "../src/models"
import React from "react";
import {Text,View,Image, Pressable} from "react-native";
import {DataStore} from "@aws-amplify/datastore";
import { Auth } from "aws-amplify";
const UserItem=({user})=>{
  const navigation=useNavigation()
  const onPress=async()=>{
   const newChatRoom=await DataStore.save(new ChatRoom({newMessages:0}))
   const authUser=await Auth.currentAuthenticatedUser()
   const dbUser=await DataStore.query(User,authUser.attributes.sub)
   await DataStore.save(new ChatRoomUser({User:dbUser,ChatRoom:newChatRoom}))
   await DataStore.save(new ChatRoomUser({User:user,ChatRoom:newChatRoom}))
   navigation.navigate("ChatRoom",{id:newChatRoom.id})
  }
    return (
        <Pressable onPress={onPress} style={{flexDirection:"row",padding:10}}>
        
       <Image source={{
        uri:user.imageUri
       }} style={{width:50,height:50,borderRadius:25,marginRight:10}}/>

       <View style={{flex:1,justifyContent:"center"}}>
        <View style={{flexDirection:"row",justifyContent:"space-between"}}>
        <Text style={{fontWeight:"bold",fontSize:18}}>{user.name}</Text>
        </View>
       </View>
       </Pressable>
    )

}
export default UserItem


The code is giving warning:
[WARN] 17:29.380 DataStore {"cause": {"locations": [[Object]], "message": "Variable 'input' has coerced Null value f
or NonNull type 'ID!'", "path": null}, "errorInfo": undefined, "errorType": "BadRecord", "localModel": {"_version": undefin
ed, "chatRoomId": undefined, "createdAt": undefined, "id": "08c6d89c-b6a3-42e5-b8c0-ff4b2fea7605", "updatedAt": undefined, 
"userId": undefined}, "message": "Variable 'input' has coerced Null value for NonNull type 'ID!'", "operation": "Create", "
process": "mutate", "recoverySuggestion": "Ensure app code is up to date, auth directives exist and are correct on each mod
el, and that server-side data has not been invalidated by a schema change. If the problem persists, search for or create an
 issue: https://github.com/aws-amplify/amplify-js/issues", "remoteModel": null}
 WARN  [WARN] 17:29.647 DataStore {"cause": {"locations": [[Object]], "message": "Variable 'input' has coerced Null value f
or NonNull type 'ID!'", "path": null}, "errorInfo": undefined, "errorType": "BadRecord", "localModel": {"_version": undefin
ed, "chatRoomId": undefined, "createdAt": undefined, "id": "7025dd76-2631-478b-bdd7-fc6c5b948752", "updatedAt": undefined, 
"userId": undefined}, "message": "Variable 'input' has coerced Null value for NonNull type 'ID!'", "operation": "Create", "
process": "mutate", "recoverySuggestion": "Ensure app code is up to date, auth directives exist and are correct on each mod
el, and that server-side data has not been invalidated by a schema change. If the problem persists, search for or create an
