### ISSUE TITLE
Auth.ts is throwing an internal error

### ISSUE THREAD

**Issue by HMilbradt** [aws-amplify/amplify-js#10809]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 13.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 8.45 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.2 - ~/.nvm/versions/node/v14.19.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.19.2/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.2/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox Developer Edition: 107.0
    Safari: 16.1
  npmPackages:
    aws-amplify: ^4.3.16 => 4.3.43 

```

</details>

### Describe the bug

We are occasionally seeing Amplify throw an error internally.  The line that is throwing is [this](https://github.com/aws-amplify/amplify-js/blob/b9ec1926c8ba3d2d0b2289a9b84090fb5d724ad9/packages/auth/src/Auth.ts#L1692).

The specific exception is:

```
Cannot read properties of undefined (reading 'length')
```

This is currently happening in one of our bigger apps, so I'm unable to pull that out into a reproducible example.  However, looking at the Amplify code I don't see how this should be possible either.  We setup Amplify in a Nuxt plugin, and everything that uses Amplify runs after it's set up.

Below is a screenshot of this in our Sentry account.

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/22685915/209245965-263b7316-2b8c-46ae-a236-2838329b335d.png">

### Expected behavior

It shouldn't throw

### Reproduction steps

Unsure

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by nadetastic** [comment]
Hi @HMilbradt - thanks for opening this issue. You mentioned that this happens intermittently and sounds like when you have high usage on your app. Any other context on this? Is there a specific action that seems to be the user is going through in the app that involves [`Auth.currentUserPoolUser()`](https://aws-amplify.github.io/amplify-js/api/classes/authclass.html#currentuserpooluser)?

Based on what you have mentioned, it sounds like the current user when this error occurs doesn't have any attributes.

**Comment by HMilbradt** [comment]
Thanks for the response @nadetastic.  Judging based on where I'm seeing these errors, I think it's likely the call is related to `Auth.currentSession()` or `Auth.currentAuthenticatedUser()` when the user first enters our application. 

Now that I'm looking at the code I've noticed that we pass `{ bypassCache: true }` in a couple of places.  I dove into the Cognito and Amplify code a bit and noticed the cache is checked in a few places, so perhaps changing this will "fix" the issue on our end.

I wish I had more information to share.  As soon as we determine the reproduction I will repost that here.

**Comment by nadetastic** [comment]
Hi @HMilbradt let me know if you are still having this issue or if you were able to determine reproduction steps. I'll go ahead and mark this as closed but can re-open if you have any updates for me.
