### ISSUE TITLE
AuthError

### ISSUE THREAD

**Issue by yanivams** [aws-amplify/amplify-js#10803]
### Which Specific Feature is your question related to?

Amplify Auth

### Question

 I keep getting this error in the console: 
"Error: Amplify has not been configured correctly. 
            The configuration object is missing required auth properties."
 I checked I don't have duplication of libraries , and tried to uninstall all modules and re-install them, I also   amplify push again and did anything else I could find on the web but couldn't figure out how to solve it. Anyone know's how to solve it ?

Here is my package.json
```json
{
  "name": "vanilla-typescript",
  "version": "1.0.0",
  "description": "JavaScript and TypeScript example starter project",
  "main": "src/products/products.html",
  "scripts": {
    "dev": "webpack --config bundler/webpack.dev.js",
    "start": "webpack serve --config bundler/webpack.dev.js",
    "build": "webpack  --config bundler/webpack.prod.js",
    "deploy": "vercel --prod"
  },
  "devDependencies": {
    "@types/file-saver": "^2.0.5",
    "@types/three": "^0.139.0",
    "@types/webgi": "https://storage.googleapis.com/dist.pixotronics.com/webgi/runtime/bundle-types-0.6.1.tgz",
    "clean-webpack-plugin": "^4.0.0",
    "client-zip": "^2.3.0",
    "copy-webpack-plugin": "^11.0.0",
    "css-loader": "^6.7.1",
    "file-saver": "^2.0.5",
    "html-loader": "^4.2.0",
    "html-webpack-plugin": "^5.5.0",
    "mini-css-extract-plugin": "^2.6.1",
    "portfinder-sync": "^0.0.2",
    "ts-loader": "^9.4.1",
    "typescript": "^4.4.4",
    "webgi": "https://storage.googleapis.com/dist.pixotronics.com/webgi/runtime/bundle-0.6.1.tgz",
    "webpack": "^5.74.0",
    "webpack-cli": "^4.10.0",
    "webpack-dev-server": "^4.11.1",
    "webpack-merge": "^5.8.0"
  },
  "resolutions": {
    "@babel/preset-env": "7.13.8"
  },
  "keywords": [
    "typescript",
    "javascript"
  ],
  "staticFiles": {
    "staticPath": [
      {
        "staticPath": "assets",
        "staticOutDir": "assets"
      }
    ]
  },
  "dependencies": {
    "@aws-amplify/auth": "^5.1.1",
    "@aws-amplify/ui-react": "^4.2.1",
    "@types/react": "^18.0.26",
    "@types/react-dom": "^18.0.9",
    "aws-amplify": "^5.0.7",
    "react": "^18.1.0",
    "react-dom": "^18.2.0",
    "three": "^0.143.0",
    "vercel": "^28.2.2"
  }
}
```

my index.ts:
```ts
import { Amplify } from "aws-amplify";

import awsconfig from "./src/aws-exports";

Amplify.configure(awsconfig);

window.location.replace("/src/login/login.html");
```

login.html:

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />        
        <title>Login</title>
    </head>
    <body>
        <div class="content">
            <h1>Login</h1>
            <div id="loginplacholder"></div>
        </div>    
    </body>
</html>
```

and login.tsx:
```tsx
import * as React from "react";
import ReactDOM from "react-dom/client";
import { Authenticator } from "@aws-amplify/ui-react";
import '@aws-amplify/ui-react/styles.css';


const root = ReactDOM.createRoot(document.getElementById("loginplacholder") as HTMLElement);
root.render(
<Authenticator>
    {({signOut}) => (
        <div>
            <h1>Hello, you are authenticated</h1>
            <button onClick={signOut}>Sign Out</button>
        </div>
    )}
</Authenticator>
)
```

**Comment by tannerabread** [comment]
Hi @yanivams, you shouldn't need both the `@aws-amplify/auth` package and the `aws-amplify` package. Can you try removing the scoped `@aws-amplify/auth` package and trying again?

I do not see anything else wrong from first glance, so if that doesn't help, can you also add your `aws-exports.js` file

**Comment by yanivams** [comment]
Hi @tannerabread , thanks a lot for trying to help! 
Unfortunately , removing @aws-amplify/auth package didn't help, I get the same error.

Here is aws-exports.js
```
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5edb49df-e3aa-42b1-9c56-c10d3edb34d6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_IomXwwqQa",
    "aws_user_pools_web_client_id": "7csr6m7psb3vtna4ubvjsj3hrv",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
```

I really hope that can help in finding a solution.

**Comment by nadetastic** [comment]
Hi @yanivams 

Could you run `npm list aws-amplify` in you project and share the response? This is to confirm there aren't conflicting versions of it due to some package dependency - namely the UI package

**Comment by yanivams** [comment]
Hi @nadetastic, thanks for answering.

`npm list aws-amplify` gives this output:
```
├─┬ @aws-amplify/ui-react@4.3.0
│ ├─┬ @aws-amplify/ui-react-core@2.1.5
│ │ └── aws-amplify@5.0.7 deduped
│ ├─┬ @aws-amplify/ui@5.4.0
│ │ └── aws-amplify@5.0.7 deduped
│ └── aws-amplify@5.0.7 deduped
└── aws-amplify@5.0.7
```

**Comment by nadetastic** [comment]
Thanks for providing this @yanivams, a few more questions:
- is this happening locally on when you deploy to prod?
- could you log the auth config in `index.ts` right _after_ `Amplify.configure()`? Something like
> ```js
> import { Auth} from 'aws-amplify'
> console.log(Auth.configure())
> ```
- Im still trying to understand your app, but it looks like you've added some react to a vanilla typescript app? Any clarification/context on this would be appreciated

**Comment by yanivams** [comment]
@nadetastic , your questions helped me to get some progress with this issue. 

I moved these lines:

```
import { Amplify } from "aws-amplify";

import awsconfig from "./src/aws-exports";

Amplify.configure(awsconfig);
``` 
to login.tsx from index.ts  and the error is gone. I am not sure I understand why it does it make a difference but it is.

However, I still seem to have a problem because the style of the authenticator seems to be missing. This is what I get.  

<img width="217" alt="Screen Shot 2022-12-24 at 10 30 58 PM" src="https://user-images.githubusercontent.com/20768815/209450298-21e9ed39-126b-455f-93eb-02c3792cd45a.png">

Any idea what can be the problem ?

I guess the awsconfig printout is not relevant anymore beacuse of the progress mentioned. But if it is here it is 
```
aws_cognito_identity_pool_id
: 
"us-east-1:64bb9062-8d88-4591-9234-9bc6254253fd"
aws_cognito_mfa_configuration
: 
"OFF"
aws_cognito_mfa_types
: 
['SMS']
aws_cognito_password_protection_settings
: 
{passwordPolicyMinLength: 8, passwordPolicyCharacters: Array(4)}
aws_cognito_region
: 
"us-east-1"
aws_cognito_signup_attributes
: 
[]
aws_cognito_social_providers
: 
[]
aws_cognito_username_attributes
: 
['EMAIL']
aws_cognito_verification_mechanisms
: 
['EMAIL']
aws_project_region
: 
"us-east-1"
aws_user_pools_id
: 
"us-east-1_2IYWa1jYs"
aws_user_pools_web_client_id
: 
"3bbkeihuvcsgc3khpgc36f7mau"
```

Regard your other questions:
* Problem is seen locally and in production. 
* Yes. It was started as a vanilla typescript project and react, along with amplify is added now.


Thanks again for the help!

**Comment by nadetastic** [comment]
@yanivams  Glad you were able to make some progress here! I'm not sure why moving the imports/config made a difference, but in general the config needs to be loaded and available on the page. For SPAs, adding the config to the entry point of the app should work fine.

For the styling, make sure you have imported the styles as described [in the docs](https://ui.docs.amplify.aws/react/getting-started/installation#styles)

```js
// js example
import { Authenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';
```

```css
/* CSS example */
@import "@aws-amplify/ui-react/styles.css";
```

**Comment by yanivams** [comment]
Thanks @nadetastic . That solved it completely.

Very much appreciated! Thank you!
