### ISSUE TITLE
Add TVMLKit Support

### ISSUE THREAD

**Issue by febbraro** [aws-amplify/amplify-js#1081]
When attempting use this library via TVMLKit (the Javascript runtime within Apple TV) we run into a problem that `storage` is null.

`[WARN] 40:14.48 Cache - getItem failed! TypeError: null is not an object (evaluating 'this.config.storage.getItem')`

This is happening because in `packages/aws-amplify/src/Common/StorageHelper/index.ts` when it tries to attach to `localStorage`, it uses the following code

`const StorageHelper = window.localStorage; `

The problem is that within TVMLKit `window` is not a valid object. `localStorage` is just in the global context and not attached to a `window` object.  The correct way to fix this is the check if `window` is undefined and `navigationDocument` is not undefined then assign `localStorage` to `StorageHelper` otherwise assign `window.localStorage`

I tried to implement this in a fork of the repo, but I kept getting the following TypeScript error:

```
> aws-amplify@0.4.5-unstable.0 clean /Users/frank/Projects/aws-amplify/packages/aws-amplify
> rimraf lib lib-esm dist

src/Common/StorageHelper/index.ts(18,64): error TS2304: Cannot find name 'navigationDocument'.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! exec Errored while executing 'yarn build' in 'aws-amplify'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn build
lerna ERR!     at Promise.all.then.arr (/Users/frank/Projects/aws-amplify/node_modules/lerna/node_modules/execa/index.js:236:11)
{ Error: Command failed: yarn build
    at Promise.all.then.arr (/Users/frank/Projects/aws-amplify/node_modules/lerna/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  killed: false,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'yarn build',
  timedOut: false,
  exitCode: 1 }
error Command failed with exit code 1.
```

This is effecting aws-amplify 0.4.5.

I'm happy to help and submit a PR, but I was not able to figure out how to get past the TypeScript error above.

**Comment by haverchuck** [comment]
@febbraro 

Are you using navigationDocument as a typescript type in the amplify code?

**Comment by febbraro** [comment]
@haverchuck this was my initial attempt that generated the error above: 

https://github.com/phase2/aws-amplify/commit/3dd5833d1a1b9a32c4a98c54d863f635ee2c13fd

**Comment by mlabieniec** [comment]
@febbraro you could possible use a polyfill for the window object similar to [here](https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify/src/Common/Polyfills/Polyfills.ts#L31), perhaps add a similar line for window.localStorage to use the memory storage...

**Comment by haverchuck** [comment]
@febbraro - Just checking in.... have you tried using a polyfill as suggested by @mlabieniec ?

**Comment by febbraro** [comment]
I have not gotten to that yet, but it is in my list and I appreciate the pointer to how to handle polyfill in TS.

**Comment by mlabieniec** [comment]
Feel free to reopen as a feature-request for apple-tv/platform support, will close for now given the workaround.
