### ISSUE TITLE
`CognitoUser` does not inherit storage from `CognitoUserPool`

### ISSUE THREAD

**Issue by nolde** [aws-amplify/amplify-js#10810]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify Categories

auth

### Describe the bug

When creating a pool with a custom storage instance, like so...

```js
const userPool = new CognitoUserPool({
  ClientId: userPoolClientId,
  Storage: new MyCustomStorage(),
  UserPoolId: userPoolId
})
```

... and then later creating a user to sign in...

```js
const authDetails = new AuthenticationDetails(authData)
const user = new CognitoUser({ Username: email, Pool: userPool })
user.authenticateUser(authDetails, { onFailure: /*...*/ , onSuccess: /*...*/ })
```
... the user pool is a required argument of `CognitoUser`, but it does not use the storage of `CognitoUserPool` as default; instead, if no `Storage` option is passed into `CognitoUser`, it just uses `StorageHelper` to create a new one, [as can be seen here](https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/src/CognitoUser.js#L89).

As the pool instance is a required argument of the user instance, and it is the root of the structure, one would assume the storage option would be respected by any other instances that depend on it. Instead, other instances are just creating their own, if one is not careful to use the `Storage` argument.

### Expected behavior

`CognitoUser` and any other classes depending on `CognitoUserPool` should use the storage configured in the pool as default.

```js
// CognitoUser.js
this.storage = data.Storage || this.pool.storage || new StorageHelper().getStorage();
```

### Reproduction steps

Just use code above.

**Comment by nolde** [comment]
This is a *bug*, not a feature request. Anything created from a `CognitoPool` using an specific storage should inherit that storage, no? Why would I want to give different storages to user and pool? Most importantly, why would those two instances having a different storage be default behaviour?

**Comment by nadetastic** [comment]
Hi @nolde, after discussing this with the team, we agree that this is more of a bug than a feature request. However please note that it may not be prioritized right away. I will be following up on this issue in case of any updates.

Thanks!

**Comment by nadetastic** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should be resolved and we highly recommend updating to the most recent version. Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
