### ISSUE TITLE
Initialise Amplify using STS credentials

### ISSUE THREAD

**Issue by thaniidesk** [aws-amplify/amplify-js#10816]
### Is this related to a new or existing framework?

React

### Is this related to a new or existing API?

Authentication

### Is this related to another service?

AppSync

### Describe the feature you'd like to request

We need feature to initialise/configure Amplify using STS credentials. We are getting STS credentials from our backend service, and would like to initialise Amplify using those credentials.  We want to invoke AppSync GraphQL APIs using STS (short lived) IAM credentials. We couldn't find a way to do Amplify.configure(...) using STS credentials. 
 

### Describe the solution you'd like

We need ability to do something similar to the below code:-

```
import Amplify from 'aws-amplify';

const stsCredentials = {
  accessKeyId: 'ACCESS_KEY_ID',
  secretAccessKey: 'SECRET_ACCESS_KEY',
  sessionToken: 'SESSION_TOKEN',
  region: 'REGION'
};

Amplify.configure({
  // Other Amplify configuration options
  credentials: stsCredentials
});
```

### Describe alternatives you've considered

Alternatives is using aws_cognito_identity_pool_id with UnAuthenticated login enabled. However, it exposes out aws_cognito_identity_pool_id in the client side code. We would like to generated the STS credentials for aws_cognito_identity_pool_id and pass it to the frontend. 

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by gvnavin** [comment]
+1

**Comment by ak-laivann** [comment]
+1

**Comment by kishnu0** [comment]
+1

**Comment by aaraamuthan** [comment]
+1

**Comment by nadetastic** [comment]
Hi @thaniidesk 

Thanks for opening this issue. At this time, Amplify configure does not support use of STS credentials, and will mark this as a feature request.

However, since you are looking to protect your AppSync/GraphQL API with IAM, you can configure IAM as your provider in the [schema auth rules](https://docs.amplify.aws/cli/graphql/authorization-rules/#authorization-strategies) but it sounds like you've looked into this and are worried of exposing your Identity Pool ID on the client?

**Comment by nadetastic** [comment]
Following up on this - chatting with the Cognito team, there shouldn't be an issue exposing the identity pool id on the client as these are public identifiers similar to website domain name. However I am curious as to what your concern may be.

Additionally, configuring the STS credentials as you have mentioned would be more of a security concern as it exposes your secretAccessKey on the client. The recommended way to do this is to setup your Auth resources and use IAM authentication.

**Comment by nadetastic** [comment]
Hi @thaniidesk

Following up on this - support for using STS credentials with `Amplify.configure()` is not something that is currently planned as it would be a security issue, exposing your SecretKey on the client. I'll be closing this issue out soon, but let me know if you have any questions.
