### ISSUE TITLE
export 'default' (imported as 'Amplify') was not found in 'aws-amplify'

### ISSUE THREAD

**Issue by guychevelle** [aws-amplify/amplify-js#10827]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

DataStore

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 11.7
    CPU: (4) x64 Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz
    Memory: 159.15 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    npm: 8.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.0
  npmPackages:
    @aws-amplify/ui-react: ^4.3.1 => 4.3.1 
    @aws-amplify/ui-react-internal:  undefined ()
    @testing-library/jest-dom: ^5.16.5 => 5.16.5 
    @testing-library/react: ^13.4.0 => 13.4.0 
    @testing-library/user-event: ^13.5.0 => 13.5.0 
    aws-amplify: ^5.0.8 => 5.0.8 
    react: ^18.2.0 => 18.2.0 (18.1.0)
    react-dom: ^18.2.0 => 18.2.0 
    react-icons: ^4.7.1 => 4.7.1 
    react-router-dom: ^6.6.1 => 6.6.1 
    react-scripts: 5.0.1 => 5.0.1 
    web-vitals: ^2.1.4 => 2.1.4 
  npmGlobalPackages:
    @aws-amplify/cli: 9.2.1
    corepack: 0.10.0
    npm: 8.6.0


</details>


### Describe the bug

Attempting to configure for multi auth (cognito and IAM) in index.js.  This same code works with no issue for an application using aws-amplify 4.3.36.

### Expected behavior

No errors when running npm start

### Reproduction steps

index.js copied from an existing application that runs with no errors.

### Code Snippet

```javascript
// Put your code below this line.
import { DataStore, AuthModeStrategyType } from 'aws-amplify';
import Amplify from 'aws-amplify';
import config from './aws-exports';

//  additional DataStore configuration to avoid subscription errors
//  when using multiple auth modes (cognito + IAM). aws-amplify bug
//  reference:  https://github.com/aws-amplify/amplify-js/issues/9369
Amplify.configure({
   ...config,
   DataStore: {
     authModeStrategyType: AuthModeStrategyType.MULTI_AUTH
   }
  });



### Log output

<details>

```
// Put your logs below this line
Compiled with problems:

ERROR in ./src/index.js 22:0-17

export 'default' (imported as 'Amplify') was not found in 'aws-amplify' (possible exports: API, APIClass, AWSCloudWatchProvider, AWSKinesisFirehoseProvider, AWSKinesisProvider, AWSPinpointProvider, AmazonPersonalizeProvider, Amplify, Analytics, Auth, AuthModeStrategyType, Cache, ClientDevice, DataStore, Geo, Hub, I18n, Interactions, Logger, Notifications, Predicates, Predictions, PubSub, ServiceWorker, Signer, SortDirection, Storage, StorageClass, XR, graphqlOperation, syncExpression, withSSRContext)

```

</details>


### aws-exports.js

_No response_

### Manual configuration

_No response_

### Additional configuration

_No response_

### Mobile Device

_No response_

### Mobile Operating System

_No response_

### Mobile Browser

_No response_

### Mobile Browser Version

_No response_

### Additional information and screenshots

My assumption is that something has changed between aws-amplify versions 4.3.36 and 5.0.8.  Is there now a different method/configuration for apps that intend to use multiple auth methods?

**Comment by guychevelle** [comment]
Get the same error when simply using the below:

Amplify.configure(config)

**Comment by nadetastic** [comment]
Hi @guychevelle 

Amplify as a default export is deprecated and you would need to import it as a named export

```js
import { Amplify } from 'aws-amplify'
```

Could you try this?

**Comment by guychevelle** [comment]
awesome!  that works.

**Comment by cbou** [comment]
This tutorial should be updated:
https://aws.amazon.com/blogs/mobile/use-existing-cognito-resources-for-your-amplify-api-storage-and-more/

**Comment by akbarm** [comment]
I'm still getting this error applying : 

import { Amplify } from 'aws-amplify'

ERROR in ./src/index.js 12:0-14
export 'default' (imported as 'Amplify') was not found in 'aws-amplify' 

Full code

import logo from './logo.svg';
import './App.css';

import { Amplify } from 'aws-amplify'
import { withAuthenticator, signOut  } from '@aws-amplify/ui-react'

function App({ signOut }) {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
      <signOut />
    </div>
  );
}

export default withAuthenticator(App);

**Comment by nadetastic** [comment]
Hi @akbarm, could you open a new issue for this and also share your `package.json`?

Open new issue - [https://github.com/aws-amplify/amplify-js/issues/new/choose](https://github.com/aws-amplify/amplify-js/issues/new/choose)

**Comment by yashwanth78-bobby** [comment]
export 'API' (imported as 'API') was not found in 'aws-amplify' (possible exports: Amplify)

what about this issue??
