### ISSUE TITLE
AWSS3Provider-ensure credentials error No Cognito Identity pool provided for unauthenticated access

### ISSUE THREAD

**Issue by tyarai** [aws-amplify/amplify-js#10825]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication, Storage

### Amplify Categories

auth, storage

### Environment information

<details>

```
# Put output below this line

 System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
    Memory: 710.58 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    npm: 8.10.0 - /usr/local/bin/npm
    Watchman: 2021.05.31.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 107.0.1
    Safari: 15.5
  npmGlobalPackages:
    @aws-amplify/cli: 8.3.0
    corepack: 0.10.0
    create-react-app: 3.4.0
    npm-check-updates: 13.0.3
    npm: 8.10.0
    watchman: 1.0.0


```

</details>

### Describe the bug

Following an upgrade to **aws-amplify 5.0.8**, I keep getting this issue and am **not able to get signed Url for images in public** folder. Note that for previous version of aws-amplify everything worked very well.

### Expected behavior

Calling **Storage.get(key)** should return the signed Url of the images

### Reproduction steps

1. install the latest aws-amplify 5.0.8
2. Call Storage.get(key) should return the signed url

### Code Snippet

```javascript
// Put your code below this line.
try {
      const _signedUrl = await Storage.get(fileName, {
        level: "public",
      });
      return _signedUrl;
    } catch (err) {
      console.log(
        `functionUtils::getImageSignedUrl() returning image 'signedUrl' : ${err}`
      );
    }

```

### Log output

<details>

```
// Put your logs below this line
react_devtools_backend.js:4012 [WARN] 48:59.752 AWSS3Provider - ensure credentials error No Cognito Identity pool provided for unauthenticated access

```

</details>

### aws-exports.js

const awsmobile = {
  aws_project_region: "eu-central-1",
  aws_cognito_identity_pool_id:   "eu-central-1:xxxxxxxxxxxxxxxxx",
  aws_cognito_region: "eu-central-1",
  aws_user_pools_id: "eu-central-1_xxxxxxxxxx",
  aws_user_pools_web_client_id: "xxxxxxxxxxxxxx",
  oauth: {},
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["NAME", "FAMILY_NAME", "EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: [],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_appsync_graphqlEndpoint:
    "https://xxxxxxxxxxxxxxxxx.appsync-api.eu-central-1.amazonaws.com/graphql",
  aws_appsync_region: "eu-central-1",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
  aws_user_files_s3_bucket: "xxxxxxxxxxxxx",
  aws_user_files_s3_bucket_region: "eu-central-1",
  aws_cognito_login_mechanisms: ["PREFERRED_USERNAME"],
};

### Mobile Browser

Chrome

**Comment by nadetastic** [comment]
Hi @tyarai, thanks for opening this issue - I am currently looking into this

A quick question, what was the previous version of `aws-amplify` you are upgrading from?

**Comment by nadetastic** [comment]
May be related to #10790

**Comment by tyarai** [comment]
@nadetastic Thanks for your reply. Please find my answer below in bold text
1- What was the previous version of aws-amplify you are upgrading from?   **aws-amplify 4.3.37**
2- Did you create the Storage resource with the Amplify CLI (amplify add storage) or did you set it up manually? I created the storage with **amplify add storage** command

**Comment by nadetastic** [comment]
Thanks for confirm - could you log out the Auth config right before the Storage call is made?
```js
console.log( Auth.configure() )
```
Looking to see if the output contains this key for the identity pool: ` aws_cognito_identity_pool_id:"<region>:<uuid>"`

In addition, this can happen if you haven't allowed Guest user to make Storage calls and are trying to without a signed in user.

**Comment by tyarai** [comment]
@nadetastic  it's working now. In fact have just removed the node_modules folder then re-install all dependencies. It's that simple. Thanks for your support
