### ISSUE TITLE
Auth.currentUserCredentials can return an error object

### ISSUE THREAD

**Issue by cshfang** [aws-amplify/amplify-js#10823]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
N/A

```

</details>

### Describe the bug

Duplicating issue found internally here to be triaged per our preferred processes. Customer description of issue is as follows:

`Auth.currentUserCredentials` is explicitly typed and documented to return a `ICredentials object` (see docs: https://aws-amplify.github.io/amplify-js/api/classes/authclass.html#currentcredentials), but I am experiencing that it can also return an error object like:

```
{
  "name": "NotAuthorizedException",
  "$fault": "client",
  "$metadata": {
    "httpStatusCode": 400,
    "requestId": "<id>",
    "attempts": 1,
    "totalRetryDelay": 0
  }
}
```

### Expected behavior

> The AmplifyJS library should either throw this error instead of returning it, or change its documentation and typescript types to indicate that an error object may be returned.

### Reproduction steps

Not consistently reproducible - an error must occur.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by joebernard** [comment]
What version of Amplify are you using?

**Comment by cwomack** [comment]
The developer preview for v6 of Amplify has officially been released with improvements to TypeScript support and much more! Please check out our [announcement](https://aws.amazon.com/blogs/mobile/aws-amplify-javascripts-new-developer-preview-with-reduced-bundle-sizes-improved-typescript-and-next-js-support/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=238088647) and updated [documentation](https://docs.amplify.aws/lib-v1/project-setup/create-application/q/platform/js/) to see what has changed.

This issue should be resolved within the dev preview and upcoming General Availability for Amplify v6, but let us know with a comment if there are further issues.

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
