### ISSUE TITLE
Sub dependency package of amazon-cognito-identity-js, 'Buffer' throwing an error for 'global is not defined' and causing web app to whitescreen.

### ISSUE THREAD

**Issue by norvalbv** [aws-amplify/amplify-js#10832]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Not applicable

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 83.17 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 3.2.1 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 105.0.3
    Safari: 15.5
  npmPackages:
    @babel/core: ^7.19.1 => 7.20.7 
    @babel/plugin-syntax-flow: ^7.18.6 => 7.18.6 
    @babel/plugin-transform-react-jsx: ^7.19.0 => 7.20.7 
    @badeball/cypress-cucumber-preprocessor: ^13.0.3 => 13.1.0 
    @bahmutov/cypress-esbuild-preprocessor: ^2.1.5 => 2.1.5 
    @cypress/angular:  0.0.0-development 
    @cypress/mount-utils:  0.0.0-development 
    @cypress/react:  0.0.0-development 
    @cypress/react18:  0.0.0-development 
    @cypress/svelte:  0.0.0-development 
    @cypress/vue:  0.0.0-development 
    @cypress/vue2:  0.0.0-development 
    @react-spring/web: ^9.5.5 => 9.6.1 
    @types/cypress-cucumber-preprocessor: ^4.0.1 => 4.0.1 
    @types/jest: ^29.0.3 => 29.2.5 
    @types/react: ^18.0.15 => 18.0.26 
    @types/react-dom: ^18.0.6 => 18.0.10 
    @types/react-test-renderer: ^18.0.0 => 18.0.0 
    @types/socket.io-client: ^3.0.0 => 3.0.0 
    @visx/annotation: ^2.12.2 => 2.17.0 
    @visx/axis: ^2.12.2 => 2.17.0 
    @visx/curve: ^2.1.0 => 2.17.0 
    @visx/responsive: ^2.10.0 => 2.17.0 
    @visx/scale: ^2.2.2 => 2.17.0 
    @visx/shape: ^2.11.1 => 2.17.0 
    @vitejs/plugin-react: ^2.0.0 => 2.2.0 
    amazon-cognito-identity-js: ^6.1.2 => 6.1.2 
    autoprefixer: ^10.4.7 => 10.4.13 
    axios: ^0.27.2 => 0.27.2 
    buffer: ^6.0.3 => 6.0.3 (4.9.2, 5.7.1)
    cypress: ^10.11.0 => 10.11.0 
    daisyui: ^2.33.0 => 2.46.0 
    eslint: ^8.20.0 => 8.30.0 
    formik: ^2.2.9 => 2.2.9 
    jest: ^29.0.3 => 29.3.1 
    jest-environment-jsdom: ^29.1.2 => 29.3.1 
    postcss: ^8.4.14 => 8.4.20 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    react-error-boundary: ^3.1.4 => 3.1.4 
    react-router-dom: ^6.4.3 => 6.6.1 
    react-test-renderer: ^18.2.0 => 18.2.0 
    socket.io-client: ^4.5.1 => 4.5.4 (4.4.0)
    tailwindcss: ^3.1.6 => 3.2.4 
    ts-jest: ^29.0.1 => 29.0.3 
    typescript: ^4.8.3 => 4.9.4 
    uuid: ^9.0.0 => 9.0.0 (8.3.2)
    vite: ^3.0.0 => 3.2.5 
    yup: ^0.32.11 => 0.32.11 
  npmGlobalPackages:
    corepack: 0.10.0
    npm: 8.11.0
    yarn: 1.22.19

```

</details>

### Describe the bug

A white screen occurs in my web application when trying to use amazon-cognito-identity-js. 

I get the following error:

`Uncaught ReferenceError: global is not defined.`

The variable 'global' comes from the sub-dependency package of amazon-cognito-identity-js, **'Buffer'.**

Where Buffer is called like so:
<img width="735" alt="image" src="https://user-images.githubusercontent.com/79381943/210118246-10199df0-e109-4a9e-9cb9-fcc094f07e94.png">

It displays that global is not defined within the Buffer package:
<img width="798" alt="image" src="https://user-images.githubusercontent.com/79381943/210118278-bf43d6c4-c494-479c-a589-411bfdfc8535.png">

### Expected behavior

I am expecting to see the web application not display a white screen and render the UI correctly.

### Reproduction steps

1. yarn add amazon-cognito-identity-js
2. yarn start

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line
Uncaught ReferenceError: global is not defined
    at node_modules/buffer/index.js (amazon-cognito-identity-js.js?v=0251b1ad:215:35)
    at __require2 (chunk-S5KM4IGW.js?v=0251b1ad:18:50)
    at amazon-cognito-identity-js.js?v=0251b1ad:2738:29

```

</details>

**Comment by nadetastic** [comment]
Thanks for opening this issue. Out of curiosity, is there a requirement/reason to use `amazon-cognito-identity-js` directly and not Amplify Auth? 

We have created a streamlined experience for our developers needing to use Authentication with Cognito using the Authentication library from Amplify. You can opt in to use just the [JS library without the Amplify CLI](https://docs.amplify.aws/lib/auth/start/q/platform/js/#re-use-existing-authentication-resource) if you feel like that would be better for your use case.

While we do provide some occasional fixes/upgrades to the `amazon-cognito-identity-js library`, we are planning on deprecating that package in the near future.

**Comment by norvalbv** [comment]
@nadetastic  Hi, thanks for the response. I am pretty new to a lot of AWS services so as of now, my only reason to use Cognito from `amazon-cognito-identity-js` instead of Amplify directly is out of the size of the bundle... I guess? (i.e., no ultimate reason). 

I will switch to using Amplify Auth if it is recommended and the `amazon-cognito-identity-js` package will depreciate shortly and see if that fixes anything. Also, as Amplify bundles various packages is there / will there be a solution to allow for just the Auth? Eliminating the need for the redundant/unused other packages in Amplify?

In the meantime, off the top of your head - is there any simple reasoning of why I am experiencing a white screen with the current solution?

**Comment by abdallahshaban557** [comment]
Hi @norvalbv - when you use the `aws-amplify` package, we do tree shake any packages that you are not using. We are also working on improvements to our bundle size even further this year!

**Comment by norvalbv** [comment]
@nadetastic  @abdallahshaban557  Hi guys, I have switched to Amplify but I am still getting the same error, I'm presuming because Congito is used under the hood for the authentication.

**Comment by abdallahshaban557** [comment]
Hi @norvalbv  - are you using Vite with your app?

**Comment by abdallahshaban557** [comment]
Hi @norvalbv  - you can also follow the workaround in this documentation page on how to use Vite with Amplify! https://docs.amplify.aws/lib/project-setup/create-application/q/platform/js/#vue-vite-config

**Comment by nadetastic** [comment]
Hi @norvalbv - following up on this. Are you are still facing issues?

**Comment by bsor-dev** [comment]
I got same issue

**Comment by norvalbv** [comment]
@bsor-dev Hi! Not sure if you are still facing this issue but i've recently come back to Vite and the error still persists.

I managed to fix it using the following code:

```React
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react-swc';
declare const global: Window;

// https://vitejs.dev/config/
export default defineConfig({
  define: {
    global: typeof global === 'undefined' && Window,
  },
  plugins: [react()],
});
```

Namely the line for defining the global variable. This can work in your vite.config.ts file... Seems to work fine for me right now; so hopefully nothing breaks
