### ISSUE TITLE
React Native Expo - Notifying reachability change is false for android, true for iOS

### ISSUE THREAD

**Issue by 5ecured** [aws-amplify/amplify-js#10845]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

DataStore

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 319.59 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.2.0 - ~/.nvm/versions/node/v19.2.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v19.2.0/bin/npm
    Watchman: 2022.11.28.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
    Safari: 16.2
  npmPackages:
    @babel/core: ^7.12.9 => 7.20.12 
    @react-native-async-storage/async-storage: ^1.17.11 => 1.17.11 
    @react-native-community/netinfo: ^9.3.7 => 9.3.7 
    @react-native-picker/picker: ^2.4.8 => 2.4.8 
    @react-navigation/bottom-tabs: ^6.5.2 => 6.5.2 
    @react-navigation/material-bottom-tabs: ^6.2.10 => 6.2.10 
    @react-navigation/native: ^6.1.1 => 6.1.1 
    @react-navigation/native-stack: ^6.9.7 => 6.9.7 
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: ^6.1.2 => 6.1.2 
    aws-amplify: ^5.0.8 => 5.0.8 
    aws-amplify-react-native: ^7.0.2 => 7.0.2 
    expo: ~47.0.9 => 47.0.11 
    expo-status-bar: ~1.4.2 => 1.4.2 
    hermes-inspector-msggen:  1.0.0 
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 
    react-native-paper: ^5.1.2 => 5.1.2 
    react-native-safe-area-context: 4.4.1 => 4.4.1 
    react-native-screens: ~3.18.0 => 3.18.2 
    react-native-vector-icons: ^9.2.0 => 9.2.0 
  npmGlobalPackages:
    @aws-amplify/cli: 10.5.2
    corepack: 0.15.1
    npm: 8.19.3

```

</details>

### Describe the bug

In my React Native Expo project, I am fetching data using `DataStore.query` to my amplify backend.

For iOS, I get:
```
iOS Bundling complete 125ms
 LOG  [INFO] 53:57.609 Reachability - subscribing to reachability in React Native
 LOG  [INFO] 53:58.504 Reachability - Notifying reachability change true
```

However for Android, I get:
```
Android Bundling complete 129ms
 LOG  [INFO] 53:58.358 Reachability - subscribing to reachability in React Native
 LOG  [INFO] 53:58.380 Reachability - Notifying reachability change false
```

Because it is false, I fail to fetch any data from the backend. (For android, works fine for ios).

Anyone had a similar issue?

### Expected behavior

For Android to work as well as iOS (successful fetching) and for Android to say `Notifying reachability change true` instead of `false`

### Reproduction steps

Just simple fetching using `DataStore.Query` like shown below in the Code Snippet

### Code Snippet

```javascript
// Put your code below this line.
```
import { DataStore } from 'aws-amplify';
import { Restaurant } from '../../models'
```

```
const [restaurants, setRestaurants] = useState([])

    const fetchRestaurants = async () => {
        const results = await DataStore.query(Restaurant)
        setRestaurants(results)
    }

    useEffect(() => {
        fetchRestaurants()
    }, [])
```
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by dpilch** [comment]
Hi @5ecured, according to https://github.com/react-native-netinfo/react-native-netinfo/issues/653 there appears to be an incompatibility with the latest versions of React Native and `@react-native-community/netinfo` (used by the reachability listener in DataStore on React Native).

Could you try using `react-native@0.67.5`? Some have said these versions will work well together.

There doesn't seem to be a fix yet, but it is being investigated by some https://github.com/react-native-netinfo/react-native-netinfo/issues/615

**Comment by dpilch** [comment]
I haven't been able to reproduce this myself. @5ecured are you using a physical android device?

**Comment by dpilch** [comment]
I am still not able to reproduce using a physical device on Device Farm. Could you add additional details to help with reproduction?

**Comment by mohanataraj** [comment]
This issue is reproducible and for me it was because I was using VPN on my device and tend to login reachability turns to false, without VPN its possible for me to login and reachability turn to true.
