### ISSUE TITLE
Support for EMAIL channelType for AWSAnalyticsProvider

### ISSUE THREAD

**Issue by golatoye** [aws-amplify/amplify-js#1085]
**Do you want to request a feature or report a bug?**
Feature

**What is the current behaviour?**
only GCM and APNS pinpoint changes are supported for recording events
> /packages/aws-amplify/src/Analytics/Providers/AWSAnalyticsProvider.ts : 340 
> const ChannelType = Address? ((clientInfo.platform === 'android') ? 'GCM' : 'APNS') : undefined;

**What is the expected behaviour?**
I would like to be able to specify channel type explicitly and choose "EMAIL"

**Comment by sammartinez** [comment]
@golatoye is this still a valid use case for you? Please let us know.

**Comment by mynameisguy** [comment]
for future users:

Despite what written in the documentation, using channelType: 'EMAIL' does work. At least in `Analytics.updateEndpoint`
