### ISSUE TITLE
Issues with Amplify Auth in React Project

### ISSUE THREAD

**Issue by liam-wolfgang** [aws-amplify/amplify-js#10865]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication, REST API

### Amplify Categories

auth, hosting

### Environment information

<details>

```
# Put output below this line

  System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 400.86 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /opt/homebrew/bin/node
    npm: 9.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.0
  npmPackages:
    @aws-amplify/ui-react: ^0.2.5 => 0.2.38 
    @chakra-ui/core: ^0.8.0 => 0.8.0 
    @emotion/core: ^10.0.28 => 10.3.1 
    @emotion/styled: ^10.0.27 => 10.3.0 
    @reduxjs/toolkit: ^1.5.0 => 1.9.1 
    @reduxjs/toolkit-query:  1.0.0 
    @reduxjs/toolkit-query-react:  1.0.0 
    @testing-library/jest-dom: ^4.2.4 => 4.2.4 
    @testing-library/react: ^9.3.2 => 9.5.0 
    @testing-library/user-event: ^7.1.2 => 7.2.1 
    @types/jest: ^24.0.0 => 24.9.1 
    @types/json2csv: ^5.0.3 => 5.0.3 
    @types/lodash: ^4.14.155 => 4.14.191 
    @types/markdown-it: ^12.0.1 => 12.2.3 
    @types/node: ^12.0.0 => 12.20.55 
    @types/react: ^16.9.0 => 16.14.34 
    @types/react-date-range: ^0.94.4 => 0.94.4 
    @types/react-dom: ^16.9.0 => 16.9.17 
    @types/react-onclickoutside: ^6.7.3 => 6.7.4 
    @types/react-redux: ^7.1.9 => 7.1.25 
    @types/react-router-dom: ^5.1.5 => 5.3.3 
    @types/react-select: ^3.0.13 => 3.1.2 
    @types/react-syntax-highlighter: ^11.0.4 => 11.0.5 
    @types/react-table: ^7.0.28 => 7.7.14 
    @types/recharts: ^1.8.10 => 1.8.24 
    @types/uuid: ^8.0.0 => 8.3.4 
    @types/yup: ^0.29.8 => 0.29.14 
    aws-amplify: ^5.0.9 => 5.0.9 
    aws-amplify-react: ^4.1.9 => 4.2.35 
    axios: ^0.21.1 => 0.21.4 (0.21.1, 0.26.0)
    date-fns: ^2.14.0 => 2.29.3 
    emotion-theming: ^10.0.27 => 10.3.0 
    json2csv: ^5.0.6 => 5.0.7 
    lodash: ^4.17.19 => 4.17.21 
    markdown-it: ^12.0.4 => 12.3.2 
    react: ^16.13.1 => 16.14.0 (18.1.0)
    react-date-range: ^1.0.3 => 1.4.0 
    react-dom: ^16.13.1 => 16.14.0 
    react-hook-form: ^6.14.1 => 6.15.8 
    react-hook-form-generator: ^0.3.6 => 0.3.6 
    react-icons: ^3.10.0 => 3.11.0 
    react-markdown-editor-lite: ^1.2.4 => 1.3.4 
    react-onclickoutside: ^6.10.0 => 6.12.2 
    react-redux: ^7.2.0 => 7.2.9 
    react-router-dom: ^5.2.0 => 5.3.4 
    react-scripts: ^4.0.3 => 4.0.3 
    react-select: ^3.1.0 => 3.2.0 
    react-spring: ^8.0.27 => 8.0.27 
    react-syntax-highlighter: ^15.4.3 => 15.5.0 
    react-table: ^7.6.3 => 7.8.0 
    recharts: ^1.8.5 => 1.8.6 
    remove: ^0.1.5 => 0.1.5 
    typescript: ~3.7.2 => 3.7.7 
    uuid: ^8.1.0 => 8.3.2 (3.4.0, 3.3.2)
    yup: ^0.29.3 => 0.29.3 
  npmGlobalPackages:
    @aws-amplify/cli: 10.6.1
    npm: 9.2.0

```

</details>

### Describe the bug

I have been getting an issue when trying to test the app locally and I'm looking for some help to get it working again correctly.

We are getting an Amplify auth error when trying to log in ( locally ) - The live version of the app is still working as we have not been able to update anything without running locally. I have not changed anything to do with the aws-exports.js file etc.

Console Error message when on log in page running locally:

• [ERROR] 42:27.494 AuthError
index.js:
Error: Amplify has not been configured correctly.
The configuration object is missing required auth properties.
Did you run "amplify push
after adding auth via amplify add auth'?
See
https://aws-amplify_github.lo/docs/js/authentication#amplify_project-setup for
more
information

Also the Amplify.configure(awsExports); was not working so I have changed it to:

import { Amplify, Auth } from 'aws-amplify';
import awsExports from './aws-exports';
Amplify.configure(awsExports);
Auth.configure(awsExports);

But I am still getting the same error message.

I would really appreciate your help on this issue because we are looking to build out some additional features by the end of the month.
![Screenshot 2023-01-12 at 16 42 37](https://user-images.githubusercontent.com/97950303/212284328-03bdbfe3-e2d0-4f5f-ba64-d5691850616c.png)

### Expected behavior

Normally the project would have no problem running locally so I can implement new features and test.

### Reproduction steps

1. Clone the Github repo
2. Make sure the package.json file is the same as when it was working locally previously.
3. Do a npm install --force in the terminal
4. npm start
5. The project runs with no issues from the terminal but there is an issue with amplify on the local host.

### Code Snippet

```javascript
// Put your code below this line.
// Initial Code

import React from 'react';
import ReactDOM from 'react-dom';
import Amplify from 'aws-amplify';

import './index.css';
import * as serviceWorker from './serviceWorker';
import awsExports from './aws-exports';
import App from './App';

Amplify.configure(awsExports);

// Remove strict mode until react-select legacy context API error fixed

ReactDOM.render(
  //<React.StrictMode>
    <App />
  //</React.StrictMode>
  ,
  document.getElementById('root')
);

serviceWorker.unregister();

// I then tried

import React from 'react';
import ReactDOM from 'react-dom';
import { Amplify, Auth } from 'aws-amplify';

import './index.css';
import * as serviceWorker from './serviceWorker';
import awsExports from './aws-exports';
import App from './App';

Amplify.configure(awsExports);
Auth.configure(awsExports);

// Remove strict mode until react-select legacy context API error fixed

ReactDOM.render(
  //<React.StrictMode>
    <App />
  //</React.StrictMode>
  ,
  document.getElementById('root')
);

serviceWorker.unregister();

// still didn't work
```

### Log output

<details>

```
// Put your logs below this line
[DEBUG] 26:51.358 AuthClass - getting current authenticated user
ConsoleLogger.ts:91 [DEBUG] 26:51.358 AuthClass - get current authenticated userpool user
index.js:1 [ERROR] 26:51.358 AuthError - 
            Error: Amplify has not been configured correctly. 
            The configuration object is missing required auth properties. 
            Did you run `amplify push` after adding auth via `amplify add auth`?
            See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information
        
console.<computed> @ index.js:1
ConsoleLogger.ts:99 [DEBUG] 26:51.358 AuthClass - The user is not authenticated by the error NoUserPoolError: Authentication Error
    at NoUserPoolError.AuthError [as constructor] (Errors.ts:24:1)
    at new NoUserPoolError (Errors.ts:39:1)
    at AuthClass.rejectNoUserPool (Auth.ts:2188:1)
    at AuthClass.currentUserPoolUser (Auth.ts:1194:1)
    at AuthClass.<anonymous> (Auth.ts:1360:1)
    at step (Auth.ts:1:1)
    at Object.next (Auth.ts:1:1)
    at fulfilled (Auth.ts:1:1)
ConsoleLogger.ts:99 [DEBUG] 26:51.358 Hub - Dispatching to UI Auth with  Object
ConsoleLogger.ts:99 [INFO] 26:51.358 Authenticator - Inside onAuthStateChange Method current authState: loading
ConsoleLogger.ts:91 [INFO] 26:51.358 Authenticator - authState has been updated to signin
ConsoleLogger.ts:99 [DEBUG] 26:51.358 Hub - Dispatching to UI Auth with  Object

// and also

![Screenshot 2023-01-13 at 09 28 17](https://user-images.githubusercontent.com/97950303/212285592-b76dfb09-4d62-47a0-a066-23e7aaf81ab3.png)


```

</details>

### Additional information and screenshots

```json
{
  "name": "wolfgang-analytics",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@aws-amplify/ui-react": "^0.2.5",
    "@chakra-ui/core": "^0.8.0",
    "@emotion/core": "^10.0.28",
    "@emotion/styled": "^10.0.27",
    "@reduxjs/toolkit": "^1.5.0",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "@types/jest": "^24.0.0",
    "@types/node": "^12.0.0",
    "@types/react": "^16.9.0",
    "@types/react-dom": "^16.9.0",
    "@types/react-table": "^7.0.28",
    "aws-amplify": "^5.0.9",
    "aws-amplify-react": "^4.1.9",
    "axios": "^0.21.1",
    "date-fns": "^2.14.0",
    "emotion-theming": "^10.0.27",
    "json2csv": "^5.0.6",
    "lodash": "^4.17.19",
    "markdown-it": "^12.0.4",
    "react": "^16.13.1",
    "react-date-range": "^1.0.3",
    "react-dom": "^16.13.1",
    "react-hook-form": "^6.14.1",
    "react-hook-form-generator": "^0.3.6",
    "react-icons": "^3.10.0",
    "react-markdown-editor-lite": "^1.2.4",
    "react-onclickoutside": "^6.10.0",
    "react-redux": "^7.2.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^4.0.3",
    "react-select": "^3.1.0",
    "react-spring": "^8.0.27",
    "react-table": "^7.6.3",
    "recharts": "^1.8.5",
    "remove": "^0.1.5",
    "typescript": "~3.7.2",
    "uuid": "^8.1.0",
    "yup": "^0.29.3"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "prettier": {
    "printWidth": 100,
    "semi": true,
    "singleQuote": true
  },
  "devDependencies": {
    "@types/json2csv": "^5.0.3",
    "@types/lodash": "^4.14.155",
    "@types/markdown-it": "^12.0.1",
    "@types/react-date-range": "^0.94.4",
    "@types/react-onclickoutside": "^6.7.3",
    "@types/react-redux": "^7.1.9",
    "@types/react-router-dom": "^5.1.5",
    "@types/react-select": "^3.0.13",
    "@types/react-syntax-highlighter": "^11.0.4",
    "@types/recharts": "^1.8.10",
    "@types/uuid": "^8.0.0",
    "@types/yup": "^0.29.8",
    "react-syntax-highlighter": "^15.4.3"
  }
}
```

**Comment by nadetastic** [comment]
Hi @liam-wolfgang, thank you for opening this issue. Could you log the config by adding the following and sharing the out put?

```js
console.log( Auth.configure() )
```

**Comment by liam-wolfgang** [comment]
Hi @nadetastic,

Thanks for your reply!

The log is attached
![Screenshot 2023-01-16 at 09 35 44](https://user-images.githubusercontent.com/97950303/212645735-4982c0fa-3b62-4d8e-9a68-d9798ce22f81.png)


I have also checked to see if I have multiple versions here:
![Screenshot 2023-01-16 at 09 37 14](https://user-images.githubusercontent.com/97950303/212645918-e092a507-b9fb-45e6-9bf6-3753aa57f18c.png)

Thanks!

**Comment by nadetastic** [comment]
@liam-wolfgang thanks for providing the above, so far it looks configured properly.

Im curious if you have an `/amplify` folder at the root of your project? You may also need to run `amplify pull` to pull in you app configuration from AWS to your local project - could you confirm/try this?

**Comment by liam-wolfgang** [comment]
@nadetastic  I have an amplify folder in the root, here:

![Screenshot 2023-01-19 at 10 17 09](https://user-images.githubusercontent.com/97950303/213416342-233a2e74-e331-4b9c-8bb6-b1b2c9248101.png)

Would it be beneficial to delete it and run amplify pull again?

**Comment by liam-wolfgang** [comment]
@nadetastic I have an amplify folder in my root here:

![Screenshot 2023-01-19 at 10 21 37](https://user-images.githubusercontent.com/97950303/213417292-d30a37c1-c1ed-42ba-a062-2681351d1197.png)

Would it be beneficial to delete this and do an amplify pull or can I do amplify pull when its already there?

**Comment by nadetastic** [comment]
Either way should produce the same outcome, however I recommend removing the amplify folder then running `amplify pull`.

**Comment by liam-wolfgang** [comment]
Hi @nadetastic, I have tried that and it still has the same error in the console - Is there anything else that we could try?

**Comment by nadetastic** [comment]
@liam-wolfgang is it possible for you to share a repo/copy of you app in minimal form so I can test with it?

**Comment by liam-wolfgang** [comment]
@nadetastic Sure thing - whats the most secure way of sending you this?

I could send you a .zip file ?

**Comment by nadetastic** [comment]
A zip file can work @liam-wolfgang

**Comment by liam-wolfgang** [comment]
@nadetastic Thanks man, here you go!

https://github.com/Wolfgang-Digital/wolfgang-analytics 
or 
[wolfgang-analytics-master.zip](https://github.com/aws-amplify/amplify-js/files/10558464/wolfgang-analytics-master.zip)

**Comment by liam-wolfgang** [comment]
Hey @nadetastic do you have any update on this?

We are looking to build out additional components for the app asap!

Thanks!

**Comment by tannerabread** [comment]
Hi @liam-wolfgang I looked through this briefly and in your [`index.tsx`](https://github.com/Wolfgang-Digital/wolfgang-analytics/blob/master/src/index.tsx) you are incorrectly importing `Amplify` rather than the named import `{ Amplify }` from the package.

As of v5.0.0, [default exports are no longer supported in the library](https://github.com/aws-amplify/amplify-js/releases/tag/aws-amplify%405.0.0)

Could you try changing line 3 to `import { Amplify } from 'aws-amplify'`

**Comment by tannerabread** [comment]
@liam-wolfgang 
I cloned your repo and messed around with it, and the problem seems to stem from using a bunch of outdated packages. I upgraded @aws-amplify/ui-react to 4.3.7 which no longer has the Authenticator components you were using in `Authenticator.tsx` but rather a main Authenticator that handles all of the individual components in one piece that you can [configure](https://ui.docs.amplify.aws/react/connected-components/authenticator/configuration) and [customize](https://ui.docs.amplify.aws/react/connected-components/authenticator/customization).
See the[ migration guide ](https://ui.docs.amplify.aws/react/getting-started/migration)for upgrading

I then got rid of the `aws-amplify-react` which has been [deprecated since amplify v5.0.0](https://github.com/aws-amplify/amplify-js/releases/tag/aws-amplify%405.0.0)

That forced me to upgrade `react-scripts` to 5.0.1 to handle the named exports 

These changes seemed to get rid of the configure error you were experiencing, but would modify your Authenticator component a little bit.
I had other errors when running it this way that were unrelated to the configure/auth portions of the app, but they were consistent before and after the fix I applied.

**Comment by liam-wolfgang** [comment]
@tannerabread Thanks for your reply! So would you suggest to 1. Follow the migration docs 2. Configure 3. Customise ?

Really appreciate your help on this.

**Comment by tannerabread** [comment]
Yes that should work for you, from what I saw your authenticator was fairly basic based off of the previous UI package so I wouldn't think there should be too much you have to change. Possibly just the styling you had might need to be manually applied. Here is the [direct link to the docs](https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#styling) on Authenticator styling.

I don't believe you were using the legacy `aws-amplify-react` package either, so you should be good to just remove it from dependencies and continue on with the new one.

Let us know if you run into any trouble upgrading!

**Comment by liam-wolfgang** [comment]
Great! Just to confirm that I will be using the 3.x to 4.x docs for migration?

**Comment by liam-wolfgang** [comment]
Also was it able to run locally after these new updates to the Auth part of the app?

**Comment by tannerabread** [comment]
I'm not too positive if you should just follow the entire migration guide or just try to start from scratch with the authenticator following the newest docs. I was able to get it to work in your app by changing the `App.tsx` to import the Authenticator directly instead of the component you had made, like this:

// App.tsx
<details>

```js
import React, { Suspense } from 'react';
import { ThemeProvider, CSSReset, Box } from '@chakra-ui/core';
import { BrowserRouter as Router, Switch } from 'react-router-dom';
import { Provider } from 'react-redux';

import routes from './routes';
import store from './store';
import theme from './theme';
import Layout from './components/Layout';
// import Authenticator from './features/profile/Authenticator';
import { Authenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';  // easy to miss authenticator styles
import { Routes } from './components/Routes';
import BusyIndicator from './components/BusyIndicator';

const App: React.FC = () => {
  // return <></>
  return (
    <Provider store={store}>
      <Authenticator>
        <ThemeProvider theme={theme}>
          <CSSReset />
          <Box width="100vw">
            <Router>
              <Layout>
                <Switch>
                  <Suspense fallback={<BusyIndicator isBusy color="#4FD1C5" />}>
                    <Routes routes={routes} />
                  </Suspense>
                </Switch>
              </Layout>
            </Router>
          </Box>
        </ThemeProvider>
      </Authenticator>
    </Provider>
  );
};

export default App;

```

</details>

You may want to still customize your authenticator more than the default though and keep it in that separate file.

Let me know if that doesn't answer your question

**Comment by liam-wolfgang** [comment]
Hey @tannerabread, Thanks for this! I have been able to run it locally now and get the login page rendering. However when I try to login I am getting this error:
![Screenshot 2023-02-28 at 15 12 53](https://user-images.githubusercontent.com/97950303/221895552-4610d0f2-98b0-4424-b5ec-c60f511fd0ef.png)

I have done step 1 already and no change, what would you suggest to do with this error?

**Comment by liam-wolfgang** [comment]
Hey @tannerabread, I have finally got it to run locally!

However there are certain features of the app that arent showing / working. The main one being the 'pipeline' feature - all the features are set up with Lambda Functions - would you have any idea why this is not rendering?

Thank you so much!

**Comment by tannerabread** [comment]
I think we went through a few things for fixing the authenticator, so it's worth coming back to the initial configuration of Amplify in your app. In your original post you had a couple of different ways you had tried, along with a discrepancy between which version of amplify is in your sample repo and which you had listed in the post.

Can we verify:
1. Which version of amplify you are currently using, or the current package.json
2. How you are importing `Amplify` into the project and calling the configure method, are you still doing both Amplify.configure and Auth.configure?

These questions might have been answering the original comment you had put that you might have deleted.

For your 2 follow up comments, I would suggest running the project with `Amplify.Logger.LOG_LEVEL = 'DEBUG'` which you can add into your project right after you configure the resources

**Comment by liam-wolfgang** [comment]
Yes of course:

1. ![Screenshot 2023-02-28 at 15 41 38](https://user-images.githubusercontent.com/97950303/221903368-65b6fd7b-816e-4d49-b8ee-6bd37ab49b8a.png)

2. I am importing via:  import { Amplify } from 'aws-amplify';

also I have seen that I am importing : import { Auth } from 'aws-amplify'; - should this be change to the new : import { Authenticator } from '@aws-amplify/ui-react'; ?

**Comment by tannerabread** [comment]
So the Amplify import is correct now, as we only have the named export in v5+

For the 2nd question, those are 2 different things now:
`import { Auth } from 'aws-amplify'` will give you the [manual functionality of the AuthClass in the Amplify JS library ](https://docs.amplify.aws/lib/auth/getting-started/q/platform/js/)
`import { Authenticator } from '@aws-amplify/ui-react'` is how you access the [Authenticator UI component](https://ui.docs.amplify.aws/react/connected-components/authenticator) which is the UI built upon the AuthClass for the JS library

In your case, I believe you will still be using that `Authenticator` component for your login/signup UI, but for your configuration you should only need to import `Amplify` and then configure like:
`Amplify.configure(awsExports)`
You shouldn't need to configure Auth separately, as the Amplify method will handle that for you, especially if you are using the exports file produced by Amplify.

Lastly I would suggest checking out this [troubleshooting page](https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js/) as we have sometimes seen problems when upgrading packages where duplicate versions get created in node_modules or elsewhere and cause the configuration issue

Let me know the results of this or if you are still running into issues after doing all of this!

**Comment by liam-wolfgang** [comment]
Hey @tannerabread, Thanks for clearing that up, that makes sense!

Here is what came back after running the command suggested on the troubleshooting page:

![Screenshot 2023-03-06 at 13 00 39](https://user-images.githubusercontent.com/97950303/223117519-8982c320-8f60-4312-92c1-1704344faece.png)

@aws-amplify/core seems to come back!

**Comment by tannerabread** [comment]
Ah yeah this is normally the culprit. Looking at your package.json this shouldn't be showing up with only the main package and the UI package installed, I checked on my local version of your project with the same dependencies and didn't get the duplicate.

I don't believe I have asked you yet to remove node_modules and package-lock.json/yarn.lock and try reinstalling. Can you try this and see that it at least removes the duplicate package we were just seeing. I'm hoping that also fixes your other problem

**Comment by liam-wolfgang** [comment]
Hey @tannerabread, I finally figured it out - so basically what was happening is:

When I ran it locally & logged in with my dev account It was showing a loading symbol for the user profile. So I opened the profile and no info was showing, I edited the username and submitted the request & it was working away perfectly. 

I think that it is not correctly passing the authenticated user's information to the Redux store. Do you think I may need to add something else to the App.tsx? Where the Authenticator is?

Let me know what you think!

**Comment by tannerabread** [comment]
Hi @liam-wolfgang, I am a bit rusty with my redux and didn't realize that that was the reason you had your own Authenticator component set up before. I noticed that the redux devtools weren't dispatching any actions from `App.tsx`, and then when I moved it back to `Authenticator.tsx` I'm getting denied because the API is hardcoded to your own environment, but it's at least showing updates in the redux devtools now.

That being said, I think maybe if you change your App.tsx back to how it was, and then in your Authenticator.tsx modify it to use the new Authenticator like below:
```js
import React, { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { Hub } from 'aws-amplify';
// import { AmplifyAuthenticator, AmplifySignIn, AmplifySignUp } from '@aws-amplify/ui-react';
import { Authenticator as AuthenticatorUI } from '@aws-amplify/ui-react';

import { fetchCurrentUser, getCurrentUser, fetchNotifications } from './slice';

const Authenticator: React.FC = ({ children }) => {
  const dispatch = useDispatch();
  const profile = useSelector(getCurrentUser);

  useEffect(() => {
    const updateUser = () => {
      dispatch(fetchCurrentUser());
    };
    Hub.listen('auth', updateUser);
    return () => Hub.remove('auth', updateUser);
  }, [dispatch]);

  useEffect(() => {
    if (profile.user) {
      dispatch(fetchNotifications());
    }
  }, [dispatch, profile.user, profile.update]);

  return <AuthenticatorUI>{children}</AuthenticatorUI>;
};

export default Authenticator;

```
I'm hoping this works for you since the rest of the app is set up with your resources. Excuse me if this fixes it because I ignored the redux in this custom Authenticator component you built before. I think as long as you update the UI component in that file it should work as you had it previously without having to modify the rest of your app.

**Comment by liam-wolfgang** [comment]
Hi @tannerabread, you see I didn't actually build this project it was the previous dev who did, so some of this is new to me!

Yeah that makes perfect sense! I have done that now but the UI doesn't seem to work from @aws-amplify/ui-react anymore, I know we are renaming it as AuthenticatorUI but it still doesnt seem to pull in:

![Screenshot 2023-03-07 at 15 10 44](https://user-images.githubusercontent.com/97950303/223464008-f1fff4a4-d111-4ce9-8676-514748945519.png)

**Comment by tannerabread** [comment]
Oh woops, forgot to import the css into that component, I have updated the last comment with the addition of `import '@aws-amplify/ui-react/styles.css';` after the Authenticator import

**Comment by tannerabread** [comment]
Hi @liam-wolfgang did this solve all of the issues you were seeing with this project?

**Comment by liam-wolfgang** [comment]
Hi @tannerabread, not yet still working on the redux state when logging in

**Comment by nadetastic** [comment]
Hi @liam-wolfgang following up on this issue. Let me know if you still have any issues or questions.

**Comment by nadetastic** [comment]
Closing this issue out for now, let me know if you still have questions - thanks!
