### ISSUE TITLE
all amplify storage operations give error "data is undefined"

### ISSUE THREAD

**Issue by justinjaeger** [aws-amplify/amplify-js#10861]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Storage

### Amplify Categories

storage

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 13.0.1
    CPU: (10) x64 Apple M1 Max
    Memory: 605.11 MB / 64.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.17 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 90.0.2
    Safari: 16.1
  npmPackages:
    @babel/core: ^7.12.9 => 7.14.0 
    @babel/runtime: ^7.12.5 => 7.14.0 
    @eva-design/eva: ^2.1.0 => 2.1.0 
    @react-native-async-storage/async-storage: ^1.17.10 => 1.17.10 
    @react-native-community/datetimepicker: ^6.7.1 => 6.7.1 
    @react-native-community/eslint-config: ^2.0.0 => 2.0.0 
    @react-native-community/netinfo: ^9.3.0 => 9.3.0 
    @react-native-masked-view/masked-view: ^0.2.8 => 0.2.8 
    @react-native-picker/picker: ^2.4.2 => 2.4.2 
    @react-navigation/bottom-tabs: ^5.x => 5.11.15 
    @react-navigation/native: ^5.9.4 => 5.9.4 
    @react-navigation/stack: ^5.14.4 => 5.14.4 
    @tanstack/react-query: ^4.14.1 => 4.14.1 
    @types/lodash: ^4.14.184 => 4.14.184 
    @types/react-native: ^0.64.0 => 0.64.29 
    @types/styled-components: ^5.1.3 => 5.1.26 
    @typescript-eslint/eslint-plugin: ^4.22.1 => 4.22.1 (3.10.1)
    @typescript-eslint/parser: ^4.22.1 => 4.22.1 (3.10.1)
    @ui-kitten/components: ^5.1.0 => 5.1.0 
    @ui-kitten/eva-icons: ^5.1.0 => 5.1.0 
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: ^5.2.10 => 5.2.10 (6.1.2)
    aws-amplify: ^5.0.9 => 5.0.9 
    aws-amplify-react-native: ^6.0.5 => 6.0.5 
    axios: ^0.27.2 => 0.27.2 (0.26.0)
    eslint: ^7.14.0 => 7.26.0 
    eslint-config-prettier: ^8.3.0 => 8.3.0 (6.15.0)
    eslint-config-standard: ^16.0.2 => 16.0.2 
    eslint-plugin-import: ^2.22.1 => 2.22.1 
    eslint-plugin-node: ^11.1.0 => 11.1.0 
    eslint-plugin-prettier: ^3.4.0 => 3.4.0 (3.1.2)
    eslint-plugin-promise: ^5.1.0 => 5.1.0 
    eslint-plugin-sonarjs: ^0.8.0-125 => 0.8.0-125 
    eslint-plugin-standard: ^5.0.0 => 5.0.0 
    expo-status-bar: ^1.4.2 => 1.4.2 
    hermes-inspector-msggen:  1.0.0 
    lint-staged: ^11.0.0 => 11.0.0 
    lodash: ^4.17.21 => 4.17.21 
    lottie-react-native: 4.0.2 => 4.0.2 
    memo-parser:  0.2.1 
    metro-react-native-babel-preset: ^0.64.0 => 0.64.0 
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-bootsplash: ^3.2.3 => 3.2.3 
    react-native-cache: ^2.0.2 => 2.0.2 
    react-native-clean-project: ^3.6.3 => 3.6.3 
    react-native-config: ^1.4.2 => 1.4.2 
    react-native-draggable-flatlist: ^3.1.2 => 3.1.2 
    react-native-fast-image: ^8.5.12 => 8.5.12 
    react-native-gesture-handler: ^1.10.3 => 1.10.3 
    react-native-image-picker: ^5.0.0 => 5.0.0 
    react-native-linear-gradient: ^2.6.2 => 2.6.2 
    react-native-localize: ^2.2.4 => 2.2.4 
    react-native-pager-view: ^6.0.2 => 6.0.2 
    react-native-reanimated: ^2.1.0 => 2.1.0 
    react-native-safe-area-context: ^3.2.0 => 3.2.0 
    react-native-screens: ^3.1.1 => 3.1.1 
    react-native-snackbar: ^2.4.0 => 2.4.0 
    react-native-svg: ^12.1.1 => 12.1.1 
    react-native-svg-transformer: ^0.14.3 => 0.14.3 
    react-native-tab-view: ^3.3.0 => 3.3.0 
    react-native-webview: ^11.23.0 => 11.23.0 
    styled-components: ^5.2.0 => 5.3.5 
    styled-components/macro:  undefined ()
    styled-components/native:  undefined ()
    styled-components/primitives:  undefined ()
    title-case: ^3.0.3 => 3.0.3 
    typescript: ^3.8.3 => 3.9.9 
  npmGlobalPackages:
    @aws-amplify/cli: 9.2.1
    corepack: 0.10.0
    expo-cli: 4.3.2
    gulp-cli: 2.2.0
    ios-deploy: 1.11.4
    nodemon: 2.0.4
    npm: 6.14.17
    python: 0.0.4
    python3: 0.0.1

```

</details>

### Describe the bug

When I do any operation with amplify's Storage (for ex, `await Storage.list('')`) I get the following error:

` AWSS3Provider - list InvalidArgument [TypeError: undefined is not an object (evaluating 'data.byteLength')`

The bug is the same as [here](https://github.com/aws-amplify/amplify-js/issues/7768) but I followed the steps that fixed it for that user (granting permissions to Auth and Guest Users) and it hasn't worked.

I also found the issue [here](https://stackoverflow.com/questions/65815639/typeerror-cannot-read-property-bytelength-of-undefined-aws-s3-upload) which says that turning off a dev tools network inspector could resolve the issue, I can't identify any dev tools that might be interfering

I'm not migrating an existing S3 bucket, just doing the basic steps.

If it helps, I found the source of the issue [here](https://github.com/aws-amplify/amplify-js/blob/6caccc7b4c06cf034df98bf42a265e4fff9be12f/packages/storage/src/providers/AWSS3Provider.ts#L764)

### Expected behavior

Returns a successful response

### Reproduction steps

- amplify add storage
- give permission to Auth/Guest Users
- grant both auth and guest users permission to do everything

### Code Snippet

```javascript
// Put your code below this line.

import { Storage } from 'aws-amplify';
const res = await Storage.list('');
```

### Log output

<details>

```
// Put your logs below this line

AWSS3Provider - list InvalidArgument [TypeError: undefined is not an object (evaluating 'data.byteLength')]
```

</details>

### aws-exports.js

/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ac172d82-0fcf-40e4-8fd5-cd1a8f2cf989",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_VMzrwBU85",
    "aws_user_pools_web_client_id": "gohe2ac7hojuepg2rbse4s659",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://dghkcylmvbegdbnlt6tv6uqxke.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "REDACTED",
    "aws_user_files_s3_bucket": "awardsapp873e5f6cbb714623a1108c8be7ab2680115717-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};

export default awsmobile;

### Manual configuration

none

### Additional configuration

{
    "UserPool": {
        "Id": "us-east-1_VMzrwBU85",
        "Name": "awardsappa4e66206_userpool_a4e66206-dev",
        "Policies": {
            "PasswordPolicy": {
                "MinimumLength": 8,
                "RequireUppercase": false,
                "RequireLowercase": false,
                "RequireNumbers": false,
                "RequireSymbols": false,
                "TemporaryPasswordValidityDays": 7
            }
        },
        "LambdaConfig": {},
        "LastModifiedDate": "2022-10-15T12:00:34.738000-04:00",
        "CreationDate": "2022-10-15T12:00:34.738000-04:00",
        "SchemaAttributes": [
            {
                "Name": "sub",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": false,
                "Required": true,
                "StringAttributeConstraints": {
                    "MinLength": "1",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "given_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "family_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "middle_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "nickname",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "preferred_username",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "profile",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "picture",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "website",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "email",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": true,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "email_verified",
                "AttributeDataType": "Boolean",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false
            },
            {
                "Name": "gender",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "birthdate",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "10",
                    "MaxLength": "10"
                }
            },
            {
                "Name": "zoneinfo",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "locale",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "phone_number",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "phone_number_verified",
                "AttributeDataType": "Boolean",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false
            },
            {
                "Name": "address",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "updated_at",
                "AttributeDataType": "Number",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "NumberAttributeConstraints": {
                    "MinValue": "0"
                }
            }
        ],
        "AutoVerifiedAttributes": [
            "email"
        ],
        "UsernameAttributes": [
            "email"
        ],
        "EmailVerificationMessage": "Your verification code is {####}",
        "EmailVerificationSubject": "Your verification code",
        "VerificationMessageTemplate": {
            "EmailMessage": "Your verification code is {####}",
            "EmailSubject": "Your verification code",
            "DefaultEmailOption": "CONFIRM_WITH_CODE"
        },
        "UserAttributeUpdateSettings": {
            "AttributesRequireVerificationBeforeUpdate": []
        },
        "MfaConfiguration": "OFF",
        "EstimatedNumberOfUsers": 1,
        "EmailConfiguration": {
            "EmailSendingAccount": "COGNITO_DEFAULT"
        },
        "UserPoolTags": {},
        "AdminCreateUserConfig": {
            "AllowAdminCreateUserOnly": false,
            "UnusedAccountValidityDays": 7
        },
        "UsernameConfiguration": {
            "CaseSensitive": false
        },
        "Arn": "arn:aws:cognito-idp:us-east-1:709934184485:userpool/us-east-1_VMzrwBU85"
    }
}

**Comment by nadetastic** [comment]
Hi @justinjaeger, thank you for opening this issue. So far I have been unable to reproduce it with expo, and would like to get some additional info from you.

- Are you adding storage to a new amplify app or an existing one?
- Could you enable DEBUG level logging by adding the following right before `Amplify.configure()`? Hoping to see if any helpful logs are generated before the error is thrown
```js
Amplify.Logger.LOG_LEVEL = 'DEBUG'
Amplify.configure(config)
```
- Could you share the output of `amplify status`?

**Comment by justinjaeger** [comment]
Hi Dan, thanks for your reply!

I'm adding to an existing amplify app. I also have set up "amplify auth" and authenticate my users with email.

Here's the output of the debug logger. Seems helpful:

```
 LOG  [DEBUG] 35:40.805 Credentials - set credentials from session
 LOG  [DEBUG] 35:41.48 Credentials - Failed to load credentials {"_U": 1, "_V": 3, "_W": {"_1": 5, "_U": 0, "_V": 2, "_W": [InvalidIdentityPoolConfigurationException: Invalid identity pool configuration. Check assigned IAM roles for this pool.], "_X": null}, "_X": null}
 LOG  [DEBUG] 35:41.50 Credentials - Error loading credentials [InvalidIdentityPoolConfigurationException: Invalid identity pool configuration. Check assigned IAM roles for this pool.]
```

So as I understand it, something has gone wrong with the step where "the CLI will configure appropriate IAM policies on the bucket using a Cognito Identity Pool Role".

I don't see anything written in the "Bucket Policy" section of the S3 bucket created for me upon "amplify add storage".

Hopefully this is helpful, let me know if I can provide any other information

**Comment by nadetastic** [comment]
Hi @justinjaeger sorry for the delay - from the logs you shared, it looks like credentials is a problem here. Did you run `amplify push` after you configured your auth and storage resources?

one way to check this is to run `amplify push` and see if any categories are in `Create` or `Update` status

Also if only authenticated users are allow to access the bucket, can you confirm that the current user is logged in? It can look something like:
```js
import { Auth, Storage } from 'aws-amplify';

...

try {
    const user = await Auth.currentAuthenticatedUser();
    const res = await Storage.list('');
} catch(err){
    console.log(err)
}
...
```

**Comment by justinjaeger** [comment]
Hi thanks for getting back to me!

I went through the `amplify update storage` settings to ensure that "Auth and guest users" is enabled, then ran `amplify push`, but am still seeing the same error unfortunately.

Even though I don't believe I restricted it to authenticated users only, I can confirm that the user is logged in using the command you sent along. A user object appears, though the "Session" attribute is null (not sure if that's normal)

Any other information I can offer? I even looked in the IAM authRole that cognito configures for me and it seems to have all the proper permissions to access the s3 bucket

**Comment by nadetastic** [comment]
Thank you for confirming @justinjaeger. Im not quite sure what exactly is happening, but looking at the [source of the error message](https://github.com/aws-amplify/amplify-js/blob/6caccc7b4c06cf034df98bf42a265e4fff9be12f/packages/storage/src/providers/AWSS3Provider.ts#L764), it seems that the issue could be when interfacing with the `aws-sdk` when calling `_list()`.

I'd like to get some additional context on some of the other methods - could you share the errors you get from the following, including the output from the debug logger before each method is called? 
```js
// upload a simple text file and attempt to retrieve it, or one that exists if put() fails
await Storage.put('test.txt',"This is some sample text")
await Storage.get('text.txt')
```

If it is a credentials issue, then the `Storage.get` would normally give as an error stating that or may return `AWSS3Provider - get signed url error [TypeError: Cannot read property 'byteLength' of undefined]`

**Comment by justinjaeger** [comment]
Thanks again for the follow up! Here's my debug log when I run the test:

` LOG  [DEBUG] 08:07.102 Credentials - getting credentials
 LOG  [DEBUG] 08:07.102 Credentials - picking up credentials
 LOG  [DEBUG] 08:07.102 Credentials - getting new cred promise
 LOG  [DEBUG] 08:07.102 Credentials - checking if credentials exists and not expired
 LOG  [DEBUG] 08:07.102 Credentials - need to get a new credential or refresh the existing one
 LOG  [DEBUG] 08:07.102 Credentials - no credentials for expiration check
 LOG  [DEBUG] 08:07.103 AuthClass - Getting current user credentials
 LOG  [DEBUG] 08:07.103 AuthClass - failed to get or parse item aws-amplify-federatedInfo [SyntaxError: JSON Parse error: Unexpected identifier "undefined"]
 LOG  [DEBUG] 08:07.103 AuthClass - Getting current session
 LOG  [DEBUG] 08:07.105 AuthClass - Succeed to get the user session
 LOG  [DEBUG] 08:07.108 AuthClass - Succeed to get the user session
 LOG  [DEBUG] 08:07.109 AuthClass - getting session success
 LOG  [DEBUG] 08:07.109 Credentials - set credentials from session
 LOG  [DEBUG] 08:07.710 Credentials - Failed to load credentials {"_U": 1, "_V": 3, "_W": {"_1": 41, "_U": 0, "_V": 2, "_W": [InvalidIdentityPoolConfigurationException: Invalid identity pool configuration. Check assigned IAM roles for this pool.], "_X": null}, "_X": null}
 LOG  [DEBUG] 08:07.711 Credentials - Error loading credentials [InvalidIdentityPoolConfigurationException: Invalid identity pool configuration. Check assigned IAM roles for this pool.]
 LOG  [DEBUG] 08:07.711 AuthClass - getting guest credentials
 LOG  [DEBUG] 08:07.711 Credentials - setting credentials for guest
 LOG  [DEBUG] 08:08.70 Credentials - Failed to load credentials {"_U": 1, "_V": 3, "_W": {"_1": 43, "_U": 0, "_V": 2, "_W": [InvalidIdentityPoolConfigurationException: Invalid identity pool configuration. Check assigned IAM roles for this pool.], "_X": null}, "_X": null}
 LOG  [DEBUG] 08:08.86 Credentials - Error loading credentials 
[InvalidIdentityPoolConfigurationException: Invalid identity pool configuration. Check assigned IAM roles for this pool.]
 LOG  [DEBUG] 08:08.879 S3ClientUtils - credentials provider get credentials {"accessKeyId": undefined, "authenticated": undefined, "identityId": undefined, "secretAccessKey": undefined, "sessionToken": undefined}
`

**Comment by justinjaeger** [comment]
Hey @nadetastic, just following up on this. If this is a mystery I'll use another service for image storage. Thanks!

**Comment by nadetastic** [comment]
@justinjaeger One error that sticks out to me is "InvalidIdentityPoolConfigurationException" which can usually mean that the roles used by they identity pool haven't been configured correctly. This can commonly happen if you configured your Auth resource manually.

I recommend verifying this, by checking the "Auth" and "UnAuth" roles in IAM, and confirm that there is a trust relationship that allows your identity pool to assume the roles. 

For example, you UnAuth role should look like the following:
![TrustRelationship](https://user-images.githubusercontent.com/87148442/216110384-ba1f67f5-7c01-4ca5-a9b4-50c4b679eadf.png)

The Auth Role should be similar with the difference being the condition `ForValueLike:StringLike` being set to `authenticated`

**Comment by justinjaeger** [comment]
@nadetastic Thanks so much for sending an example of the trust policy. Mine was set to `"Effect": "Deny` for some reason, so I edited the policy to say "Allow" and it's now working

Really appreciate your help
