### ISSUE TITLE
feild added on aws database not reflacted in datastore

### ISSUE THREAD

**Issue by SharvariSPatil** [aws-amplify/amplify-js#10867]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

I have added feild on aws quiry but this field is not reflected in dataStore

### What's the expected behaviour?

automatically reflected new data  in dataStore

### Help us reproduce the bug!

--

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by sreeramsama** [comment]
Transferring to JS team as it is related to Datastore

**Comment by iartemiev** [comment]
It's not clear from the description what steps you performed and what was the expected outcome. Can you give us some more context? 
Where did you add the field? Was it in your local GraphQL schema file? If so, did you run `amplify push` afterwards? Or did you add the field through the AppSync Console? If that's the case, you will need to add that same field to your local schema, followed by `amplify push`.

**Comment by SharvariSPatil** [comment]
I have pushed graphql field on aws.  when I call by graphql API 1st time after login I get the data but when I refresh the page I am not getting data

**Comment by iartemiev** [comment]
> I have pushed graphql field on aws

Where on AWS? Are you using Amplify Studio? Or are you updating the field through the AppSync Console?
If you're using Studio, did you run `amplify pull` locally after making the change?

**Comment by iartemiev** [comment]
Closing due to lack of response. Happy to re-open if we hear back from you.
