### ISSUE TITLE
Issue with aws-amplify upgrading React 

### ISSUE THREAD

**Issue by hnestorova** [aws-amplify/amplify-js#10877]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Not applicable

### Amplify Categories

auth

### Environment information

<details>

<details>

node:internal/modules/cjs/loader:1056
  throw err;
  ^

Error: Cannot find module 'C:\Projects\private\private\node_modules\envinfo\dist\cli.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1053:15)
    at Module._load (node:internal/modules/cjs/loader:898:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:84:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v19.4.0
</details>

</details>

### Describe the bug

Hi,

When trying to upgrade React to the latest 18th version we get the below errors. 
`pm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: aws-amplify-react@4.1.21
npm ERR! Found: @aws-amplify/auth@3.3.3
npm ERR! node_modules/@aws-amplify/auth
npm ERR!   @aws-amplify/auth@"^3.2.13" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @aws-amplify/auth@"^2.0.0" from aws-amplify-react@4.1.21
npm ERR! node_modules/aws-amplify-react
npm ERR!   aws-amplify-react@"^4.1.16" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @aws-amplify/auth@2.1.8
npm ERR! node_modules/@aws-amplify/auth
npm ERR!   peer @aws-amplify/auth@"^2.0.0" from aws-amplify-react@4.1.21
npm ERR!   node_modules/aws-amplify-react
npm ERR!     aws-amplify-react@"^4.1.16" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!`

Do you have an idea what the problem could be and how it can be resolved?

Thanks

### Expected behavior

Successful update of the aws-amplify versions

### Reproduction steps

1. Run npm install react react-dom or npm install -save react@18

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Manual configuration

```json
{
  "name": "private",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@aws-amplify/auth": "^3.2.13",
    "@aws-amplify/core": "^3.3.3",
    "@aws-amplify/ui": "^2.0.2",
    "@date-io/moment": "^1.3.8",
    "@material-ui/core": "4.10.2",
    "@material-ui/icons": "4.9.1",
    "@material-ui/lab": "4.0.0-alpha.56",
    "@material-ui/pickers": "3.2.10",
    "@vidyard/embed-code": "^4.2.38",
    "aws-amplify-react": "^4.1.16",
    "classnames": "^2.2.6",
    "d3": "^5.8.0",
    "d3-array": "^1.2.4",
    "d3-format": "^1.3.2",
    "d3-scale": "^2.1.2",
    "fuse.js": "^6.4.0",
    "history": "^4.9.0",
    "hoist-non-react-statics": "^3.0.1",
    "lodash": "^4.17.19",
    "moment-timezone": "^0.5.25",
    "numeral": "^2.0.6",
    "prop-types": "^15.7.2",
    "query-string": "^6.12.1",
    "react": "^16.13.1",
    "react-animated-number": "^0.4.4",
    "react-autosuggest": "^9.4.2",
    "react-csv": "^2.0.3",
    "react-dom": "^16.8.6",
    "react-idle-timer": "^4.2.9",
    "react-router": "^5.0.1",
    "react-router-dom": "^5.0.1",
    "react-scripts": "3.4.1",
    "react-scroll": "1.7.7",
    "react-spring": "^8.0.27",
    "react-virtualized": "^9.21.2",
    "react-window": "^1.8.5",
    "source-map-explorer": "^2.2.1",
    "use-state-if-mounted": "^1.0.7",
    "uuid": "^3.3.2",
    "victory": "^33.0.0"
  },
  "lint-staged": {
    "*.{js,jsx}": [
      "eslint --max-warnings 0"
    ]
  },
  "scripts": {
    "analyze": "source-map-explorer 'build/static/js/*.js'",
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "test:integration": "echo hi",
    "preload": "jest -c integration/jest.preload.config.js",
    "serve": "npx serve --no-clipboard --single --listen 3000 build",
    "eject": "react-scripts eject",
    "lint": "eslint 'src/**/*.js' --fix"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "browserslist": {
    "production": [
      "chrome > 70",
      "edge > 14",
      "firefox > 51",
      "safari > 11",
      "ios > 11"
    ],
    "development": [
      "last 1 chrome version"
    ]
  },
  "devDependencies": {
    "eslint-config-airbnb": "^18.0.1",
    "eslint-config-prettier": "^6.1.0",
    "husky": "^3.0.0",
    "jest-puppeteer": "^4.2.0",
    "lint-staged": "^9.2.0",
    "puppeteer": "^1.18.1",
    "serve": "^11.3.2",
    "typescript": "^3.5.3"
  }
}
```

**Comment by tannerabread** [comment]
Hi @hnestorova 

I noticed you are using quite dated version of amplify in your project, is there a particular reason for that?

Specifically:
* "@aws-amplify/auth": "^3.2.13", current version -> 5.1.4
* "@aws-amplify/core": "^3.3.3", current version -> 5.0.10
* "@aws-amplify/ui": "^2.0.2", current version -> 5.5.1

* "aws-amplify-react": "^4.1.16", this package has been deprecated

It's also worth trying removing your `node_modules` folder and reinstalling dependencies as sometimes we see errors from that

**Comment by hnestorova** [comment]
Hi @tannerabread 

Thank you. There is no particular reason for having so many outdated versions - just that the project has not been upgraded for quite some time and we are trying to do it now...

I will try with removing the node_modules folder to check if it will help and post an update

**Comment by tannerabread** [comment]
@hnestorova when you do get around to upgrading your amplify versions, please note the breaking changes and upgrade guides [found here](https://github.com/aws-amplify/amplify-js#notice)

**Comment by hnestorova** [comment]
Hi @tannerabread 

Unfortunately, deleting the node_modules folder did not help so as a next step I will try to replace the seemingly problematic aws-amplify-react with @aws-amplify/ui-react and then try to upgrade React's version to 18 with the single command.

However, when I added @aws-amplify/ui-react instead of aws-amplify-react,  I started getting errors like this one, for e.g.
import { Authenticator, Greetings, SignUp } from '@aws-amplify/ui-react';
->  'Greetings' is not exported from '@aws-amplify/ui-react':
where previously we had it as:
import { Authenticator, Greetings, SignUp } from 'aws-amplify-react/lib/Auth';
I was not able to find the Greetings anywhere in aws-amplify/ui-react, do you know where I should search for it?

Thank you in advance

**Comment by tannerabread** [comment]
@hnestorova
Unfortunately, those components have been deprecated with the package as far as I know. Here is the new docs for the [current Authenticator](https://ui.docs.amplify.aws/react/connected-components/authenticator) enabled by the `@aws-amplify/ui-react` package.

From old docs I have come across when updating things, I am not sure the Greetings, SignUp are still necessary if you use the new UI components. Here is a [link to the docs](https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js/) for calling Auth methods from the current versions of the main Amplify package as well.
