### ISSUE TITLE
Firefox abnormal memory consumption when uploading big files(>100gb) 

### ISSUE THREAD

**Issue by AllanZhengYP** [aws-amplify/amplify-js#10874]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular, React, Vue, Web Components, Next.js

### Amplify APIs

Storage

### Amplify Categories

storage

### Environment information

<details>

```
System:
    OS: macOS 12.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 3.10 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2022.12.05.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 89.1.21.77
    Chrome: 109.0.5414.87
    Firefox: 102.6.0
    Safari: 16.2


```

</details>

### Describe the bug

After the Amplify release [5.0.10](https://github.com/aws-amplify/amplify-js/releases/tag/aws-amplify%405.0.10), the storage category supports uploading files > 50gb. However, for bigger files(~> 100 gb), Firefox browser would use up the Application memory and eventually hang.

The same upload task works properly on Chrome and Edge.

### Expected behavior

The upload should succeed in Firefox.

### Reproduction steps

See code snippet

### Code Snippet

```javascript
// Put your code below this line.
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by jimblanc** [comment]
Issue has been fixed with the release of custom clients, closing ticket.
