### ISSUE TITLE
TypeError: Cannot read property 'configure' of undefined, js engine: hermes

### ISSUE THREAD

**Issue by chatofking** [aws-amplify/amplify-js#10881]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line

  System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400F
    Memory: 3.79 GB / 15.86 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.52)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @babel/core: ^7.12.9 => 7.20.12
    @babel/runtime: ^7.12.5 => 7.20.7
    @react-native-async-storage/async-storage: ^1.17.11 => 1.17.11
    @react-native-community/eslint-config: ^2.0.0 => 2.0.0
    @react-native-community/netinfo: ^9.3.7 => 9.3.7
    @react-native-picker/picker: ^2.4.8 => 2.4.8
    @react-navigation/native: ^6.1.1 => 6.1.2
    @react-navigation/native-stack: ^6.9.7 => 6.9.8
    HelloWorld:  0.0.1
    amazon-cognito-identity-js: ^6.1.2 => 6.1.2
    aws-amplify: ^5.0.10 => 5.0.10
    aws-amplify-react-native: ^7.0.2 => 7.0.2
    babel-jest: ^26.6.3 => 26.6.3
    eslint: ^7.32.0 => 7.32.0
    hermes-inspector-msggen:  1.0.0
    jest: ^26.6.3 => 26.6.3
    metro-react-native-babel-preset: 0.72.3 => 0.72.3
    react: 18.1.0 => 18.1.0
    react-hook-form: ^7.42.1 => 7.42.1
    react-native: 0.70.6 => 0.70.6
    react-native-safe-area-context: ^4.4.1 => 4.4.1
    react-native-screens: ^3.18.2 => 3.19.0
    react-test-renderer: 18.1.0 => 18.1.0
  npmGlobalPackages:
    @aws-amplify/cli: 10.6.2
    npm-check-updates: 16.6.2
```

</details>

### Describe the bug

 ERROR  TypeError: Cannot read property 'configure' of undefined, js engine: hermes
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
 ### Expected behavior

can run an android emulator without this error .

### Reproduction steps

install
react native
npm install -g @aws-amplify/cli
amplify configure
npm install aws-amplify amazon-cognito-identity-js @react-native-community/netinfo @react-native-async-storage/async-storage
npm install aws-amplify-react-native
npm install @react-native-picker/picker --save 
npm run android

### Code Snippet

```javascript
// Put your code below this line.
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow strict-local
 */

import React from 'react';
import {SafeAreaView, StyleSheet, Text,} from 'react-native';
import Navigation from './src/navigation';
import { withAuthenticator, AmplifyTheme } from 'aws-amplify-react-native';
import Amplify, {Auth} from 'aws-amplify';
import awsconfig from './src/aws-exports';

Amplify.configure(awsconfig);

const App = () => {
  // Auth.signOut();
  return (
    <SafeAreaView style={styles.root}>
      <Navigation />
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#F9FBFC'
  },
});

const signUpConfig = {
  header: "My Customized Sign Up",
  hideAllDefaults: true,
  signUpFields: [
    {
      label: "Full name",
      key: "name",
      required: true,
      displayOrder: 1,
      type: "string",
    },
    {
      label: "Email",
      key: "email",
      required: true,
      displayOrder: 2,
      type: "string",
    },
    {
      label: "Username",
      key: "preferred_username",
      required: true,
      displayOrder: 3,
      type: "string",
    },
    {
      label: "Password",
      key: "password",
      required: true,
      displayOrder: 4,
      type: "password",
    },
  ],
};

const customTheme = {
  ...AmplifyTheme,
  button: {
    ...AmplifyTheme.button,
    backgroundColor: 'blue',
    borderRadius: 10,
  }
};

export default withAuthenticator(App, {signUpConfig, theme: customTheme});

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Mobile Operating System

android sdk31

**Comment by chatofking** [comment]
change to  import { Amplify } from 'aws-amplify'; just worked.

**Comment by tannerabread** [comment]
Hi @chatofking I realize you found your own mistake, but did you see the import as `import Amplify, { Auth } from 'aws-amplify'` somewhere in our docs? If so, can you point me to it so that we can correct that.

**Comment by chatofking** [comment]
no, I watch a video from another source.

**Comment by tannerabread** [comment]
Thank you for the clarification
