### ISSUE TITLE
userSession is null after Auth.signUp with autoSignIn enabled. 

### ISSUE THREAD

**Issue by benjaminliang2** [aws-amplify/amplify-js#10885]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 7.27 GB / 15.73 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @babel/core: ^7.12.9 => 7.19.6
    @react-native-async-storage/async-storage: ~1.17.3 => 1.17.11
    @react-native-community/netinfo: ^9.3.7 => 9.3.7
    @react-navigation/native: ^6.0.13 => 6.0.13
    @react-navigation/native-stack: ^6.9.1 => 6.9.1
    @react-navigation/stack: ^6.3.11 => 6.3.11
    @reduxjs/toolkit: ^1.8.6 => 1.8.6
    @reduxjs/toolkit-query:  1.0.0
    @reduxjs/toolkit-query-react:  1.0.0
    @types/jest: ^29.2.3 => 29.2.3
    @types/node: ^18.11.10 => 18.11.10
    @types/react: ^18.0.25 => 18.0.25
    @types/react-dom: ^18.0.9 => 18.0.9
    @types/react-native: ~0.69.1 => 0.69.15
    HelloWorld:  0.0.1
    amazon-cognito-identity-js: ^6.0.1 => 6.1.1
    aws-amplify: ^5.0.7 => 5.0.7
    expo: ~46.0.16 => 46.0.16
    expo-app-loading: ~2.1.0 => 2.1.1
    expo-checkbox: ~2.2.0 => 2.2.2
    expo-font: ~10.2.0 => 10.2.1
    expo-image-picker: ~13.3.1 => 13.3.1
    expo-status-bar: ~1.4.0 => 1.4.0
    hermes-inspector-msggen:  1.0.0
    ini: ^1.3.5 => 1.3.8
    inquirer: ^6.5.1 => 6.5.2
    jest: ^26.6.3 => 26.6.3
    jest-expo: ^47.0.1 => 47.0.1
    react: 18.2.0 => 18.2.0
    react-native: 0.69.6 => 0.69.6
    react-native-circular-progress-indicator: ^4.4.0 => 4.4.0
    react-native-gesture-handler: ^2.9.0 => 2.9.0
    react-native-popup-menu: ^0.16.1 => 0.16.1
    react-native-progress: ^5.0.0 => 5.0.0
    react-native-reanimated: ^2.12.0 => 2.12.0
    react-native-safe-area-context: 4.3.1 => 4.3.1
    react-native-screens: ~3.15.0 => 3.15.0
    react-native-svg: ^12.3.0 => 12.3.0
    react-native-vector-icons: ^9.2.0 => 9.2.0
    react-redux: ^8.0.4 => 8.0.4
    react-test-renderer: ^18.2.0 => 18.2.0 (18.1.0)
    typescript: ^4.9.3 => 4.9.3
  npmGlobalPackages:
    @aws-amplify/cli: 10.5.2
    expo-cli: 6.0.8
    nodemon: 2.0.20


```

</details>

### Describe the bug

The response object from `Auth.signUp`  contains a `user` of type CognitoUser. However, `user.signInUserSession` is null even if i include `autoSignIn: { enabled: true}` . Not sure why but if i were to refresh my app, the user would be authenticated and `user.signInUserSession` is valid as expected. 

### Expected behavior

Expect `user.signInUserSession` to be valid in `Auth.signUp` response object in same app instance. 

### Reproduction steps

1. initalize react native project through expo with `npx create-expo-app my-app`
2. write signup form. 
3. Include code snippet below in `app.js` 
4. run `expo start`

### Code Snippet

```javascript
// Put your code below this line.
  const signUp = async () => {
      await Auth.signUp({
        username: email,
        password,
        attributes: {
          email,
          name,
        },
        autoSignIn: {
          enabled: true
        },
        validationData: [], 
      })
        .then((data) => {
          console.log(data)  // data.user.signInUserSession is null
        })
        .catch((err) => {
          console.log(err);
        });

  };
```

### Log output

<details>

```
// Put your logs below this line
[15:09:47] Object {
[15:09:47]   "codeDeliveryDetails": undefined,
[15:09:47]   "user": CognitoUser {
[15:09:47]     "Session": null,
[15:09:47]     "authenticationFlowType": "USER_SRP_AUTH",
[15:09:47]     "client": Client {
[15:09:47]       "endpoint": "https://cognito-idp.us-east-1.amazonaws.com/",
[15:09:47]       "fetchOptions": Object {},
[15:09:47]     },
[15:09:47]     "keyPrefix": "CognitoIdentityServiceProvider.xxxx",
[15:09:47]     "pool": CognitoUserPool {
[15:09:47]       "advancedSecurityDataCollectionFlag": true,
[15:09:47]       "client": Client {
[15:09:47]         "endpoint": "https://cognito-idp.us-east-1.amazonaws.com/",
[15:09:47]         "fetchOptions": Object {},
[15:09:47]       },
[15:09:47]       "clientId": "xxxx",
[15:09:47]       "storage": [Function MemoryStorage],
[15:09:47]       "userPoolId": "us-east-1_xxxx",
[15:09:47]       "wrapRefreshSessionCallback": [Function anonymous],
[15:09:47]     },
[15:09:47]     "signInUserSession": null,
[15:09:47]     "storage": [Function MemoryStorage],
[15:09:47]     "userDataKey": "CognitoIdentityServiceProvider.xxxx.test@emailuh.com.userData",
[15:09:47]     "username": "test@example.com",
[15:09:47]   },
[15:09:47]   "userConfirmed": true,
[15:09:47]   "userSub": "xxxx-xxxx-xxxx-xxxx-xxxx",
[15:09:47] }


```

</details>

**Comment by tannerabread** [comment]
Hi @benjaminliang2
I was able to reproduce this. 

I think the problem is looking for the signInUserSession a bit early. When you look for it in the `.then(data => console.log(data))` on the signUp method, the user is not yet confirmed and so doesn't automatically get signed in.

Do you have the [`confirmSignUp` method](https://docs.amplify.aws/lib/auth/emailpassword/q/platform/react-native/#confirm-sign-up) in your code after this `signUp` method? It would be a bit odd that refreshing the app would sign the user in. The autoSignIn fires after the user is confirmed through the code sent to the email.

After confirming sign up, you can listen for the [Hub event](https://docs.amplify.aws/lib/auth/auth-events/q/platform/react-native/) `autoSignIn` and log `data.payload.data` there to see the signInUserSession

**Comment by benjaminliang2** [comment]
I forgot to mention that I have a lambda function for the cognito "presignup" trigger. I assume that takes care of the user confirmation. In this case, do i still need to listen for the hub event?

**Comment by tannerabread** [comment]
Hi @benjaminliang2, sorry for the delayed response, I wanted to verify on my own app before responding. I set up a preSignUp lambda trigger on my own app and then went through the signUp process and can confirm that yes, in the singUp method itself, the CogitoUser that is returned still shows a null `signInUserSession`. But if you listen to the Hub events `signIn` and `autoSignIn` it shows the `signInUserSession` with the information you are looking for.

**Comment by benjaminliang2** [comment]
Thank you! I got a working solution with `Hub.listen`.

**Comment by rashidwiizb** [comment]
Hi @benjaminliang2  I signup the user and confirm the user in pre-signup trigger itself so I got a "signUpStep": "COMPLETE_AUTO_SIGN_IN". Then I call the autosignIn() and listen the hub. The user get signedIn and got "signedIn" event but the payload  data contained only username and userId of the signup user, it doesn't contain user sessions like token
