### ISSUE TITLE
Email instead of username in Cognito invitation message

### ISSUE THREAD

**Issue by pimmee** [aws-amplify/amplify-js#10926]
### Is this related to a new or existing framework?

React

### Is this related to a new or existing API?

Authentication

### Is this related to another service?

Cognito

### Describe the feature you'd like to request

Reading the Cognito documentation of [Customizing user invitation messages](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-settings-user-invitation-message-customization.html) it says the following:
```
Your custom message must contain the {username} and {####} placeholders.
When Amazon Cognito sends the invitation message, it replaces these placeholders 
with your user's user name and password.
```

In my application the username is an UUID where the user logs in with their (alias) email. Having the username in the invitation message is just confusing for the user. For example:

```
Your username is 1c7527bc-8b7d-4804-aa27-f29a5a2f59d6 and temporary password is Example123.
```

### Describe the solution you'd like

I would like to be able to send an invitation message with the login details the user will actually use to login.

```
Your username is {email} and temporary password is {####}.
```

### Describe alternatives you've considered

For the email invitation messages, we just hide the username with HTML. However, this is not possible for SMS invitation messages. For SMS invitation messages we've thought of doing something like the following:

```
Your username is {email} and temporary password is {####}.
ID: {username}
```

But would prefer not to.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by nadetastic** [comment]
Hi @pimmee thank you for opening this issue.

Although you aren't able to use the email in the provided template, a solution for this would be to setup your own custom lambda trigger to send the message. Some documentation and an example is shown at [1] below. You are able to customize this message and access the users attributes through `event.request.userAttributes`

[1] https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-message.html#aws-lambda-triggers-custom-message-admin-example

**Comment by pimmee** [comment]
As far as I understand the documentation, you still need to have `{{username}}` in the message. Is this not the case?

**Comment by nadetastic** [comment]
If you are setting up the custom message Lambda function, then no you do not need to have `{{username}}` ( which isn't accessible in the Lambda functions as is). 

Only if you are customizing messages in the **Messaging** tab under the **Message templates** heading, then yes you do need to have `{{username}}`

Here's some documentation that helps explain how Cognito and Lambda triggers work - https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html

Essentially, you create a lambda function with your own custom logic, that is attached to your userpool and listens to specific events from Cognito.

**Comment by pimmee** [comment]
Ahh, okay. I must of misunderstood the documentation then.

What is meant by the following then? https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-message.html

<img width="798" alt="image" src="https://user-images.githubusercontent.com/33460567/219278706-3c4b86df-f49d-44d3-aff0-fca2a91dcb11.png">

**Comment by nadetastic** [comment]
When the lambda function is invoked, it will contain an event object with the following @pimmee :
```json
    "request": {
        "userAttributes": {
            "string": "string",
            ...otherAttribtes
        }
        "codeParameter": "####",
        "usernameParameter": "string",
        "clientMetadata": {
            "string": "string",
            ...otherMetadata
        }
    }
```
You would then apply you own custom logic (for example customizing the email message you need) and the response would look like the following:


```json
{
    "response": {
        "smsMessage": "string", // if sending an SMS
        "emailMessage": "string", // if sending an email
        "emailSubject": "string"
    }
} 
```
The content for `emailMessage` in the response (or `smsMessage` for text messages) needs to include the `usernameParameter` (or in your case the primary method of login since it isn't) and the `codeParameter` that is included in the request above.

**Comment by pimmee** [comment]
Okay understood, so the "must include" text is a "recommendation" rather than a "must"?

Reading the documentation, I assumed Cognito would reject the response or similar if I didn't include the `usernameParameter` based on the following text:
 ```
 the response from your function must include both request.usernameParameter and request.codeParameter
 ```

**Comment by nadetastic** [comment]
@pimmee In the context of the Lambda trigger, the `username` that must be included should be the value/attribute that the user will using to sign in, so if you provide an alternate way for users to sign in that is not `usernameParameter` be sure to include that.

But if not using the Lambda trigger, then the Cognito email must include `username` and doesn't allow you to include any other parameters.

**Comment by ronytesler** [comment]
Not sure why this is marked as closed instead of allowing the template to include the alternative login ways instead of the username.

**Comment by nosyarlin** [comment]
I am running into the same issue. I tried sending a custom email without the `usernameParameter` and my custom email did not get sent. AWS Cognito ended up sending an email using the message template
