### ISSUE TITLE
Nuxt 3 app not deploying on aws amplify: Auth Error only in aws hosting deployment 

### ISSUE THREAD

**Issue by dhallX** [aws-amplify/amplify-js#10927]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

GraphQL API, Storage

### Amplify Categories

hosting

### Environment information

<details>

```
# Put output below this line
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 13.38 GB / 31.67 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    vuetify: ^3.0.2 => 3.0.3
  npmGlobalPackages:
    @angular/cli: 13.3.7
    @aws-amplify/cli: 10.4.0
    json-server: 0.17.0
    nodemon: 2.0.19
    yarn: 1.22.19


```

</details>

### Describe the bug

Hello AWS Team,

I am having an issue on my deployment with my Nuxt 3 app. I have checked my yml file and my build log which looks of. I have verified that the artifact gets built and attached. no I am getting an Auth error that does not show up on local host.  this error is only shown in aws build. local host works just fine.

index.f69ae020.js:14 [ERROR] 10:15.551 AuthError - 
            Error: Amplify has not been configured correctly. 
            The configuration object is missing required auth properties.
            This error is typically caused by one of the following scenarios:
I have ran amplify push and can also verify that I don't have duplicates of aws-amplify package

PS C:\Users\dhall\Documents\Projects\enxess\damage-recording> npm list aws-amplify
damage-recording@ C:\Users\dhall\Documents\Projects\enxess\damage-recording
└── aws-amplify@5.0.4

I have given you as much information to this issue that I know of. if you need anything else please let me know.

Thank you for your support!

### Expected behavior

I expect that the app deploys correctly.

### Reproduction steps

when I run aws hosting and spin my app up on the deployment url i get this.

![image](https://user-images.githubusercontent.com/106660145/216933191-f3c347b4-db4d-495f-a897-d28d32e62169.png)

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line
[log (18).txt](https://github.com/aws-amplify/amplify-js/files/10661346/log.18.txt)


```

</details>

### aws-exports.js

```const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://dzjqhaizfjan5jz3p3py4pqbke.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3njrb4yeczbq3jf3txofnxx2im",
    "aws_cognito_identity_pool_id": "eu-central-1:ed5a091d-fb4f-44ff-a0c0-934fb9673501",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_57ovsfg8C",
    "aws_user_pools_web_client_id": "4u9boqf0am5ijeg7t9r6f4mbaa",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "damagerecordingf3385f16edb64ce69165c30c9660d634165420-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
```

### Manual configuration

```{
  "private": true,
  "scripts": {

    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "typecheck": "nuxt typecheck"
  },
  "devDependencies": {
    "@types/uuid": "^9.0.0",
    "nuxt": "3.0.0",
    "vue-hooks": "^0.3.2"
  },
  "dependencies": {
    "@mdi/font": "^7.0.96",
    "@pinia/nuxt": "^0.4.6",
    "@vuepic/vue-datepicker": "^3.6.4",
    "aws-amplify": "^5.0.4",
    "dropzone-vue": "^0.1.11",
    "pinia": "^2.0.27",
    "sass": "^1.56.1",
    "uuid": "^9.0.0",
    "vue-material-datepicker": "^2.0.1",
    "vuetify": "^3.0.2"
  }
}
````

### Additional configuration

```



export default defineNuxtConfig({
  ssr: false,
  modules: [
    [
      "@pinia/nuxt",
      {
        autoImports: ["defineStore"],
      },
    ],
  ],
  css: [
    "vuetify/lib/styles/main.sass",
    "@mdi/font/css/materialdesignicons.min.css",
  ],
  build: {
    transpile: ["vuetify", "@vuepic/vue-datepicker"],
  },
  vite: {
   
    resolve: {
      alias: { './runtimeConfig': './runtimeConfig.browser',}
    },
    define: {
      'window.global': {}
  }
  
  }, 

alias: {
  // 'aws-amplify': 'aws-amplify/lib/', 
  '@aws-amplify/core': '@aws-amplify/core/lib',
  '@aws-amplify/auth': '@aws-amplify/auth/lib',
}
});
```

**Comment by dhallX** [comment]
I just found my issue! it is vital that the source folder for your plugins is written 'plugins' and not 'Plugins'. nuxt could not find the folder where the aws config is located because of the folder name. therefore there is no config file sent in the build. this is why I was getting the auth error. just in case some one comes to the same issue. :)

**Comment by tannerabread** [comment]
Hi @dhallX and thanks for using Amplify! I'm glad you were able to find your issue
