### ISSUE TITLE
DataStore clear, start, clear results in runtime error

### ISSUE THREAD

**Issue by dpilch** [aws-amplify/amplify-js#10922]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

DataStore

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line

  System:
    OS: macOS 13.2
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 116.51 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.18.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v14.18.0/bin/npm
    Watchman: 2023.01.30.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 102.7.0
    Safari: 16.3
  npmPackages:
    @aws-amplify/ui-react: ^3.5.11 => 3.6.1 
    @aws-amplify/ui-react-internal:  undefined ()
    @aws-amplify/ui-react-legacy:  undefined ()
    @testing-library/jest-dom: ^5.16.5 => 5.16.5 
    @testing-library/react: ^13.4.0 => 13.4.0 
    @testing-library/user-event: ^13.5.0 => 13.5.0 
    @types/jest: ^27.5.2 => 27.5.2 (29.4.0)
    @types/node: ^16.18.3 => 16.18.11 (18.11.18)
    @types/react: ^18.0.24 => 18.0.27 
    @types/react-dom: ^18.0.8 => 18.0.10 
    aws-amplify: unstable => 5.0.12-unstableV5.10+bbf4a4cbf 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    react-scripts: 5.0.1 => 5.0.1 
    typescript: ^4.8.4 => 4.9.5 
    web-vitals: ^2.1.4 => 2.1.4 
  npmGlobalPackages:
    @aws-amplify/analytics: 6.0.12
    @aws-amplify/api-graphql: 3.1.0
    @aws-amplify/api-rest: 3.0.12
    @aws-amplify/api: 5.0.12
    @aws-amplify/auth: 5.1.6
    @aws-amplify/cache: 5.0.12
    @aws-amplify/cli-internal: 10.6.0-graphql15.0
    @aws-amplify/cli: 10.6.2
    @aws-amplify/core: 5.0.12
    @aws-amplify/datastore-storage-adapter: 2.0.12
    @aws-amplify/datastore: 3.14.0
    @aws-amplify/geo: 2.0.12
    @aws-amplify/interactions: 5.0.12
    @aws-amplify/predictions: 5.0.12
    @aws-amplify/pubsub: 5.0.12
    @aws-amplify/pushnotification: 5.0.12
    @aws-amplify/storage: 5.1.2
    @aws-amplify/xr: 4.0.12
    amazon-cognito-identity-js: 6.1.2
    amplify: 0.0.11
    aws-amplify-react-native: 7.0.2
    aws-amplify: 4.3.39
    eslint: 8.24.0
    lerna: 5.5.2
    npm: 8.19.2
    ts-node: 10.9.1
    verdaccio: 5.18.0
    yarn: 1.22.19

```

</details>

### Describe the bug

When running DataStore clear, then start, then clear in rapid succession a runtime error occurs.

```
index.ts:656 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'lastFullSync')
    at SyncEngine.<anonymous> (index.ts:656:1)
    at step (tslib.es6.js:147:1)
    at Object.next (tslib.es6.js:128:1)
    at fulfilled (tslib.es6.js:118:1)
```

### Expected behavior

No runtime error.

### Reproduction steps

Run the code block below.

The sync engine has a subscription triggering twice (https://github.com/aws-amplify/amplify-js/blob/main/packages/datastore/src/sync/index.ts#L555). Waiting for DataStore to be ready consistently places the `clear` between the two subscription messages. The second one attempts to read from IndexedDB, but the db has already been removed by `clear`.

### Code Snippet

```javascript
// Put your code below this line.
async function repro() {
  await DataStore.clear();
  await DataStore.start();
  let unsubscribe: () => void;
  await new Promise((resolve) => {
    const hubCallback = (message: any) => {
      if (message.payload.event === "ready") {
        unsubscribe();
        resolve(true);
      }
    };
    unsubscribe = Hub.listen("datastore", hubCallback);
  });
  await DataStore.clear();
}
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by svidgen** [comment]
Is this loop being entered again?

https://github.com/aws-amplify/amplify-js/blob/main/packages/datastore/src/sync/index.ts#L528

Is `syncQueriesObservable()` firing again?

https://github.com/aws-amplify/amplify-js/blob/main/packages/datastore/src/sync/index.ts#L514

**Comment by dpilch** [comment]
The loop is entered again. `syncQueriesObservable()` is firing only once. It appears that even though the `terminated` is still false the IDB is already cleared. 

This line reads the model metadata from the IDB (https://github.com/aws-amplify/amplify-js/blob/main/packages/datastore/src/sync/index.ts#L651). The query is returning no results (https://github.com/aws-amplify/amplify-js/blob/main/packages/datastore/src/sync/index.ts#L914).
