### ISSUE TITLE
Error: "Response to preflight request doesn't pass access control check: It does not have HTTP ok status."

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [aws-amplify/amplify-js#10934]
Seems related to this closed issue: https://github.com/aws-amplify/amplify-cli/issues/8019#issue-977959660

### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

REST API

### Amplify Categories

auth, api

### Environment information

<details>

Notes:

* Happens in all browsers (chrome, firefox, edge)
* Not exactly sure what I did before it started happening
* As you can see here on aws api gateway page, cors is enabled for the route:
![image](https://user-images.githubusercontent.com/34586104/217239552-bb102de5-b155-4b9c-a771-8fa8b5d208cb.png)
![image](https://user-images.githubusercontent.com/34586104/217242373-362dd8c4-1033-4a2b-beff-9d6f96073e8e.png)

</details>

### Describe the bug

When on localhost, making a request, e.g.

`AWS.get('test', '/test', {})`

(even to an unauthenticated route), will result in this error in the dev-tools console:

```
Access to XMLHttpRequest at 'https://9rueezf0j0.execute-api.eu-north-1.amazonaws.com/test' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
```

However, I can successfully make requests to the endpoint from elsewhere, e.g. the sst console.

### Expected behavior

I should get the expected output from the dummy endpoint, namely: `{"hello world", status: 200}`

### Reproduction steps

Not sure how to reproduce.

### Code Snippet

Backend ApiStack
```ts
	const api = new Api(stack, 'Api', {
		defaults: {
			authorizer: 'iam',
			function: {
				bind: [],
			},
		},
		routes: {
			"GET /test-authentication": "services/functions/pages/test-api/lambda.main",
			 "GET /test": {
				  type: "function",
				  function: "services/functions/pages/test-api/lambda.main",
				  authorizer: 'none',
			 },

		}
	})
```

Frontend AmplifyConfig
```ts
import {Amplify} from "aws-amplify";
import config from "./config";

Amplify.configure({
	Auth: {  // cognito
		mandatorySignIn: true,
		region: config.cognito.REGION,
		userPoolId: config.cognito.USER_POOL_ID,
		identityPoolId: config.cognito.IDENTITY_POOL_ID,
		userPoolWebClientId: config.cognito.APP_CLIENT_ID
	},
	Storage: { // S3
		region: config.s3.REGION,
		bucket: config.s3.BUCKET,
		identityPoolId: config.cognito.IDENTITY_POOL_ID
	},
	API: { // API Gateway
		endpoints: [
			{
				name: "test",
				endpoint: config.apiGateway.URL,
				region: config.apiGateway.REGION
			}
		]
	}
});
```
Frontend config.js
```js
const config = {
	MAX_ATTACHMENT_SIZE: 5000000,
	// Backend config
	s3: {
		REGION: process.env.REACT_APP_REGION,
		BUCKET: process.env.REACT_APP_BUCKET,
	},
	apiGateway: {
		REGION: process.env.REACT_APP_REGION,
		URL: process.env.REACT_APP_API_URL,
	},
	cognito: {
		REGION: process.env.REACT_APP_REGION,
		USER_POOL_ID: process.env.REACT_APP_USER_POOL_ID,
		APP_CLIENT_ID: process.env.REACT_APP_USER_POOL_CLIENT_ID,
		IDENTITY_POOL_ID: process.env.REACT_APP_IDENTITY_POOL_ID,
	},
	SENTRY_DSN: "ht...",
};

console.table(config)

export default config;
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by bothra90** [comment]
@Sebastian-Nielsen : Curious what resolved the error for you. We're running into this for API Gateway (not Amplify).
