### ISSUE TITLE
DataStore query for not-beginsWith results in error

### ISSUE THREAD

**Issue by svidgen** [aws-amplify/amplify-js#10957]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

DataStore

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

There's a missing case for handling `query()` predicates like `not(m => m.beginsWith(...))`. This will fail:

```js
await DataStore.query(Model, m => m.not(m => m.beginsWith('anything')));
```

With an error like this:

```
Non-existent operator: `undefined()`
```

### Expected behavior

No error.

### Reproduction steps

1. Do regular DataStore things.
2. Query for the negation of a `beginsWith`

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by iartemiev** [comment]
Fixed in latest release - aws-amplify@5.0.15
