### ISSUE TITLE
Issue with DataStore.observeQuery change snapshots with  'or' predicate

### ISSUE THREAD

**Issue by alex-breen** [aws-amplify/amplify-js#10955]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

DataStore

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line


```
  System:
    OS: Windows 10 10.0.22621
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Memory: 771.55 MB / 15.94 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.10.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 109.0.5414.120
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.70)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @aws-amplify/ui-react: ^4.1.0 => 4.3.4
    @aws-amplify/ui-react-internal:  undefined ()
    @emotion/react: ^11.10.5 => 11.10.5
    @emotion/styled: ^11.10.5 => 11.10.5
    @mui/base: ^5.0.0-alpha.109 => 5.0.0-alpha.115
    @mui/icons-material: ^5.10.16 => 5.11.0
    @mui/material: ^5.10.17 => 5.11.6
    @tensorflow-models/universal-sentence-encoder: ^1.3.3 => 1.3.3
    @tensorflow/tfjs: ^4.2.0 => 4.2.0
    @testing-library/jest-dom: ^5.16.5 => 5.16.5
    @testing-library/react: ^13.4.0 => 13.4.0
    @testing-library/user-event: ^13.5.0 => 13.5.0
    aws-amplify: ^5.0.13 => 5.0.13
    compromise: ^14.8.0 => 14.8.1
    debounce: ^1.2.1 => 1.2.1
    is-hotkey: ^0.2.0 => 0.2.0 (0.1.8)
    nlcst-to-string: ^3.1.0 => 3.1.1
    react: ^18.2.0 => 18.2.0
    react-color: ^2.19.3 => 2.19.3
    react-dom: ^18.2.0 => 18.2.0
    react-scripts: 5.0.1 => 5.0.1
    retext: ^8.1.0 => 8.1.0
    retext-keywords: ^7.2.0 => 7.2.0
    retext-pos: ^4.1.0 => 4.1.0
    slate: ^0.88.0 => 0.88.1
    slate-history: ^0.86.0 => 0.86.0
    slate-react: ^0.88.2 => 0.88.2
    web-vitals: ^2.1.4 => 2.1.4
  npmGlobalPackages:
    @aws-amplify/cli: 10.4.0
    @forge/cli: 4.2.0
    npm-check-updates: 14.0.1
    npm: 8.10.0
    typescript: 4.8.4
</details>

### Describe the bug

I'm noticing unexpected behavior with DataStore.observeQuery with 'or'.  When it first runs, it pulls the data for the query (for both 'or' criteria), but any updates only trigger a snapshot for the FIRST predicate. With 'and' it works fine. Is this a bug or am I missing something?

So when first invoked, it pulls records that match either of the 'or' conditions. But any future changes only trigger a snapshot if the first criteria (of the two 'or' conditions) changes. 

### Expected behavior

Changes should trigger for either of the "or" predicate conditions.

### Reproduction steps

Run a simple observeQuery subscription in React.

### Code Snippet

```javascript
// Put your code below this line.

    useEffect(() => {
        const subscritpion = DataStore.observeQuery(
            Docs,
            q => (
                q.or(q => [
                    q.owners?.contains('one'),
                    q.tags?.contains('two')
                ])
            ),
            {
                sort: q => q.createdAt(SortDirection.DESCENDING),
            }
        ).subscribe(snapshot => {
            const { items, isSynced } = snapshot
            console.log('data updated')
        })
        return () => {
            subscritpion.unsubscribe()
        }

    }, [])

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by david-mcafee** [comment]
Hey @alex-breen, thanks for opening this issue!

I just tested this, and `observeQuery` seems to be working as expected. I tested using the following schema:

```graphql
type Todo @model {
  id: ID!
  name: String!
  description: String
}
```

And tested with the following:
```javascript

async function onCreate() {
    await DataStore.save(
        new Todo({
            name: `name ${Date.now()}`,
            description: `description ${Date.now()}`,
        })
    );
}

useEffect(() => {
    const subscription = DataStore.observeQuery(
        Todo,
        (q) =>
            q.or((q) => [
                q.name.contains("should not match this"),
                q.description.contains("description"),
            ]),
        {
            sort: (q) => q.createdAt(SortDirection.DESCENDING),
        }
    ).subscribe((snapshot) => {
        const { items } = snapshot;
        console.log("snapshot", snapshot);
        setSnapshots((prev) => [...prev, ...items]);
    });
    return () => {
        subscription.unsubscribe();
    };
  }, []);
```

Here, the Todo's are created with a name that will _not_ match the first `or` condition (i.e. `q.name.contains("should not match this")`). The second condition (`q.description.contains("description")`) will match, and the results are returned as expected in the snapshot. 

I see the same expected behavior when updating a record:

```javascript
async function updateLastTodo() {
    const [_todo] = await DataStore.query(Todo);
    await DataStore.save(
        Todo.copyOf(_todo, (updated) => {
            updated.description = "updated";
        })
    );
}

useEffect(() => {
    const subscription = DataStore.observeQuery(
        Todo,
        (q) =>
            q.or((q) => [
                q.name.contains("should not match this"),
                q.description.contains("updated"),
            ]),
            {
                sort: (q) => q.createdAt(SortDirection.DESCENDING),
            }
    ).subscribe((snapshot) => {
        const { items } = snapshot;
        console.log("snapshot", snapshot);
        setSnapshots((prev) => [...prev, ...items]);
    });
    return () => {
        subscription.unsubscribe();
    };
}, []);
```

Here, nothing is returned by `observeQuery` until I make the update, and the second condition is met. However, if I am misunderstanding your repro steps, please let me know! Thank you!

**Comment by alex-breen** [comment]
Hi @david-mcafee thank you so much for the reply (with hosted code!). 

I should have clarified that the field queried is an array of strings in my schema. So the predicate is a "contains" for a List, not a String. 

I.e., a schema like this: 
```
type Todo @model {
  id: ID!
  name: [String]
  description: [String]
}  
```

I've verified that, in my code, if I run a similar observeQuery against a String field, it works as expected. But if the field is an array of Strings, I run into the problem I noted above. 

I hope that is useful. I'll try to reproduce it using your code as well in a new project, to make sure there isn't something else interfering.

**Comment by david-mcafee** [comment]
Thanks for the clarification, @alex-breen! I'll attempt to reproduce the issue and get back to you.

**Comment by david-mcafee** [comment]
Hi @alex-breen, I'm still not able to repro the issue on my end. Here is what I have thus far:

Updated schema: https://github.com/david-mcafee/ds-demo/blob/main/amplify/backend/api/dsdemo102022/schema.graphql#L12-L16

Business logic: https://github.com/david-mcafee/ds-demo/blob/main/src/Todo2.tsx

Latest is currently hosted [here](https://www.davidmcafee.com/datastore-demo/)

Could you let me know if I'm missing something? Also, what versions are you using of the library, and the CLI? 

Thank you!

**Comment by alex-breen** [comment]
Hi @david-mcafee,

I made the following modification to your code above:

```
import logo from './logo.svg';
import './App.css';
import {Todo} from "./models";
import {DataStore, SortDirection} from "aws-amplify";
import {useEffect} from "react";
import {Button} from "@aws-amplify/ui-react";

function App() {
  async function add() {
    await DataStore.save(
        new Todo({
          // name: [`name ${Date.now()}`],
          // description: [`description ${Date.now()}`],
            name: ['irma'],
            description: ['vep'],
            ts: Date.now()
        })
    )
  }

  useEffect(() => {
    const subscription = DataStore.observeQuery(
        Todo,
        (q) =>
            q.or((q) => [
              q.name?.contains('irma'),
              q.description?.contains('vep'),
            ]),
        {
          sort: (q) => q.createdAt(SortDirection.DESCENDING),
        }
    ).subscribe((snapshot) => {
      const { items } = snapshot;
      console.log(items?.map((el, index) => `${index} ${new Date(el.ts)}`).join('\r\n'))
      // console.log("snapshot", snapshot);
      // setSnapshots((prev) => [...prev, ...items]);
    });
    return () => {
      subscription.unsubscribe();
    };
  }, []);

  return (
    <div className="App">
        <Button onClick={()=> add()}>
            Add
        </Button>
    </div>
  );
}

export default App;
```
The following "save" triggers a snapshot:
```
name: ['irma'],
description: null,
```
But the following "save" does not trigger a snapshot: 
```
name: null,
description: ['vep'],
```
Same if comment out the line with 'name' so none is stored. 
If instead of null, the value is an empty array [] or [null], then a snapshot is triggered. 

So...maybe this is not really a bug, but unexpected behavior due to my sloppy use of null as a value when I should make sure to use an empty array.

**Comment by david-mcafee** [comment]
Thanks @alex-breen, I was able to repro this! Going to discuss with the team on next steps. Thank you!

**Comment by david-mcafee** [comment]
Summary: when a schema contains a field with a list, and that field is set to `null`, `observeQuery` will only emit a snapshot when the first `or` condition is met - the second `or` condition will not generate a snapshot. The following code snippet reproduces the issue:

```javascript
useEffect(() => {
  const subscription = DataStore.observeQuery(
    Todo2,
    (q) =>
      q.or((q) => [
        q.name.contains("name present; description null"),
        q.description.contains("name null; description present"),
      ]),
    {
      sort: (q) => q.createdAt(SortDirection.DESCENDING),
    }
  ).subscribe((snapshot) => {
    const { items } = snapshot;
    console.log("snapshot", snapshot);
    setNameSnapshots((prev) => [...prev, ...items]);
  });

  return () => {
    subscription.unsubscribe();
  };
}, []);

async function onCreateNullName() {
  await DataStore.save(
    new Todo2({
      name: null,
      description: ["name null; description present"],
    })
  );
}
```
