### ISSUE TITLE
API.Post 403 when hitting endpoint with IAM Auth on API Gateway When Logged in With Authenticated User

### ISSUE THREAD

**Issue by mjmostachetti** [aws-amplify/amplify-js#10950]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

REST API

### Amplify Categories

function

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 12.6.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 57.83 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 2021.11.15.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 107.0
    Safari: 16.1
  npmPackages:
    @aws-amplify/pushnotification: ^5.0.13 => 5.0.13
    @aws-sdk/client-cognito-identity: ^3.128.0 => 3.128.0 (3.6.1, 3.121.0)
    @aws-sdk/client-kinesis: ^3.128.0 => 3.128.0 (3.6.1)
    @aws-sdk/credential-provider-cognito-identity: ^3.128.0 => 3.128.0 (3.6.1)
    @azure/core-asynciterator-polyfill: ^1.0.2 => 1.0.2
    @babel/core: ^7.12.9 => 7.17.5 (7.20.5)
    @babel/runtime: ^7.12.5 => 7.17.2 (7.18.3, 7.18.9)
    @craftzdog/react-native-buffer: ^6.0.4 => 6.0.4
    @notifee/react-native: ^7.4.0 => 7.4.0
    @react-native-async-storage/async-storage: ^1.17.7 => 1.17.7
    @react-native-community/datetimepicker: ^6.3.2 => 6.3.2
    @react-native-community/eslint-config: ^2.0.0 => 2.0.0
    @react-native-community/netinfo: ^8.2.0 => 8.2.0
    @react-native-picker/picker: ^2.4.1 => 2.4.1
    @react-navigation/drawer: ^6.3.1 => 6.3.1
    @react-navigation/native: ^6.0.8 => 6.0.8
    @react-navigation/native-stack: ^6.5.0 => 6.5.0
    @types/jest: ^26.0.23 => 26.0.24
    @types/react-native: ^0.66.15 => 0.66.16
    @types/react-test-renderer: ^17.0.1 => 17.0.1
    @typescript-eslint/eslint-plugin: ^5.7.0 => 5.12.1 (3.10.1)
    @typescript-eslint/parser: ^5.7.0 => 5.12.1 (3.10.1)
    HelloWorld:  0.0.1
    amazon-cognito-identity-js: ^5.2.8 => 5.2.8 (6.1.2)
    aws-amplify: 5.0.13 => 5.0.13
    aws-amplify-react-native: ^7.0.2 => 7.0.2
    babel-jest: ^26.6.3 => 26.6.3
    date-fns: ^2.29.3 => 2.29.3
    eslint: ^7.14.0 => 7.32.0
    eventemitter3: ^4.0.7 => 4.0.7
    hermes-inspector-msggen:  1.0.0
    jest: ^26.6.3 => 26.6.3
    metro-config: ^0.72.0 => 0.72.0 (0.66.2)
    metro-react-native-babel-preset: ^0.66.2 => 0.66.2 (0.72.0)
    native-base: ^3.4.9 => 3.4.9
    react: 17.0.2 => 17.0.2
    react-native: 0.67.5 => 0.67.5
    react-native-biometrics: ^2.2.0 => 2.2.0
    react-native-bluetooth-state-manager: ^1.3.3 => 1.3.3
    react-native-device-info: ^10.0.2 => 10.0.2
    react-native-error-boundary: ^1.1.12 => 1.1.12
    react-native-geolocation-service: ^5.3.0 => 5.3.0
    react-native-gesture-handler: ^2.8.0 => 2.8.0
    react-native-get-random-values: ^1.8.0 => 1.8.0
    react-native-mask-input: ^1.2.2 => 1.2.2
    react-native-notifications: ^4.3.1 => 4.3.3
    react-native-reanimated: ^2.4.1 => 2.4.1
    react-native-safe-area-context: ^4.3.1 => 4.3.1
    react-native-screens: ^3.13.1 => 3.13.1
    react-native-sensors: ^7.3.6 => 7.3.6
    react-native-svg: ^13.6.0 => 13.6.0
    react-native-svg-transformer: ^1.0.0 => 1.0.0
    react-native-url-polyfill: ^1.3.0 => 1.3.0
    react-native-version-info: ^1.1.1 => 1.1.1
    react-test-renderer: 17.0.2 => 17.0.2
    typescript: ^4.4.4 => 4.5.5
  npmGlobalPackages:
    @aws-amplify/cli: 8.5.1
    ember-cli: 3.7.1
    expo-cli: 5.4.9
    forever: 0.15.3
    generator-keystone: 0.5.1
    graphql-default-value-transformer: 2.0.1
    jshint: 2.10.1
    lighthouse: 4.0.0-alpha.2-3.2.1
    npm: 8.1.0
    sass-lint: 1.12.1
    template-file: 6.0.1
    yo: 2.0.5

```

</details>

### Describe the bug

I get a 403 error when I try to hit a POST endpoint in my express js lambda function. I just upgraded to the latest aws amplify js node package - this was working just fine previously in my old version. The POST endpoints are locked down by IAM Auth, which I'd assume would be fine to do once I am authenticated with cognito. 

### Expected behavior

I can make the request as I did previously without the 403 error.

### Reproduction steps

Upgrade to the latest aws amplify and react native node packages. Spin up an amplify environment with an api that is restricted to authenticated users via IAM. Try to hit the endpoint and you'll get a 403.

### Code Snippet

```javascript
// Put your code below this line.

```
try {
    const resp = await API.post('myapi', '/api/env', { body : { stuff: "yo"}});
    console.log(resp);
    return true;
  } catch (e) {
    console.log(JSON.stringify(e));
    console.log('failed');
    return false;
  }

### Log output

<details>

```
// Put your logs below this line
{
    "message": "Request failed with status code 403",
    "name": "Error",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json; charset=UTF-8",
            "User-Agent": "aws-amplify/5.0.12 react-native",
            "Authorization": "Bearer eyJraWQiOiJzV0ZFelNYVUVaOGRHVWlJUitLS0lTRUUzMldRYVlDMnZIK0lPK0puRjVRPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJjYTM3MTFjYi1mMTUwLTRjZGMtYWNiMy1iNWExZDI2NWQ3ZmQiLCJjb2duaXRvOmdyb3VwcyI6WyJkZDE5Y2U1Yi00Y2YyLTQxZTItODViMS1mMDcyMjkyYjBkMzkiXSwiZW1haWxfdmVyaWZpZWQiOnRydWUsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX291T2FReGx3SSIsImNvZ25pdG86dXNlcm5hbWUiOiJjYTM3MTFjYi1mMTUwLTRjZGMtYWNiMy1iNWExZDI2NWQ3ZmQiLCJvcmlnaW5fanRpIjoiNmExZTc0OGEtYjE4Zi00NjNmLWFlZGMtNzA5M2RiNWFhNjRiIiwiYXVkIjoibDVlYW0zNXNyb2kwbjgyYTh0NzhoZzVnNyIsImV2ZW50X2lkIjoiMDk1NjA2NzYtMWFhOS00MTZjLWIyMDUtODU2NDBjYWNiN2VmIiwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE2NzU4OTk3MzQsImV4cCI6MTY3NTkwMzMzNCwiaWF0IjoxNjc1ODk5NzM0LCJqdGkiOiJjYTc1ZTg3Mi0yMWMyLTQxZmYtOWI0ZS0wMzRkMmYwMjNkMmUiLCJlbWFpbCI6Im1qbW9zdGFjaGV0dGlAZ21haWwuY29tIn0.uFxMnDBTmNBSWYHeMNBByKd-9s50R36_57u1vFICek9Iaiap6sLjy9sAywRW1v4ywqvdUpC8FMrFuK4SEVLCOgLmHVpF3f3WOTxZkP3zLVBSN28oj15hWwGIoRuDcnQ5UWNjGEcAiUVUTp8SWJqmX6uMO5E-oGFs0XC3PX8e6mWBvwWCiXk1Dg0ArnKMPu0_KaXnXLcCKdDn4yS6estH2bBd_ttsd_4aQ6EyJSaIjQmdz0jmXDf54oUG2WhQNINGiZM0PTiAZDIqcfT72l_gW3GjrXNtbuvpTs8nOfOy_9FLmwVOHn0idkEhXLhuisTMdOGgqkOUCcNG2hPorT7D7Q"
        },
        "method": "post",
        "url": "my url",
        "host": "my host,
        "path": "",
        "data": "my data"
        "responseType": "json",
        "cancelToken": {
            "promise": {
                "_h": 1,
                "_i": 0,
                "_j": null,
                "_k": {
                    "onRejected": null,
                    "promise": {
                        "_h": 0,
                        "_i": 0,
                        "_j": null,
                        "_k": null
                    }
                }
            },
            "_listeners": []
        }
    },
    "status": 403
}

```

</details>

### Manual configuration

None

**Comment by mjmostachetti** [comment]
If this is helpful, here are the old(worked in this version) and new package versions(doesn't work here) that may be part of the cause.
"aws-amplify": "4.3.26" -> "5.0.13",
"aws-amplify-react-native": "^7.0.1", -> "^7.0.2",

**Comment by mjmostachetti** [comment]
Getting some clarification in this help prompt from the CLI might be useful to -
You can restrict access using CRUD policies for Authenticated Users, Guest Users, or on individual Group that users belong to in a User Pool. If a user logs into your application and is not a member of any group they will use policy set for “Authenticated Users”, however if they belong to a group they will only get the policy associated with that specific group.

We have tons of cognito groups that we use as dynamic groups(aren't explicitly defined in the graphql.schema) to control access to models in our graphql.schema. I don't think it's viable to set a CRUD policy for each group, and the CLI only prompted me for the most liberal control group that is hardcoded into the graphql.schema.

**Comment by josefaidt** [comment]
Hey @mjmostachetti :wave: thanks for raising this! Typically we'll encounter a 403 error when attempting to call a protected route that does not return CORS headers as a part of its response. Can you confirm whether the CORS headers are uncommented from the Lambda function template and are returned in its response?

Additionally, Chrome will show a CORS error and hide the actual response, whereas FireFox will show you the CORS error and the response body. If CORS is the issue you should see your error response body in FireFox

**Comment by mjmostachetti** [comment]
@josefaidt 


// Enable CORS for all methods
app.use(function (req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "*");
  next();
});

Since this was working before upgrading my amplify node package, I don't think it has anything to do with the lambda.

**Comment by chrisbonifacio** [comment]
Hi @mjmostachetti have you had a change to check the headers of the outgoing requests to the POST endpoint made by Amplify? I'm curious if the request is being signed.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
