### ISSUE TITLE
Event Buffer error in console after Datastore Sync completes

### ISSUE THREAD

**Issue by mjmostachetti** [aws-amplify/amplify-js#10966]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication, REST API, GraphQL API, DataStore, Push Notifications

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

My console logs this error. I'm not sure what it means.

```
 ERROR  [ERROR] 39:10.251 EventsBuffer - event undefined : undefined failed with error: Event type cannot be null, empty or blank
 WARN  Possible Unhandled Promise Rejection (id: 0):
Object {
  "EventsResponse": Object {
    "Results": Object {
      "adb71890-a97c-11ed-b637-cbea19e5f461": Object {
        "EventsItemResponse": Object {
          "undefined": Object {
            "Message": "Event type cannot be null, empty or blank",
            "StatusCode": 400,
          },
        },
      },
    },
  },
}
```

### Expected behavior

Not sure - trying to understand what it means.

### Reproduction steps

It seems to happen after I do a sync in the datastore, but I'm not 100% sure. Have you seen this before?

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by tannerabread** [comment]
hi @mjmostachetti, do you have some more information on how you are using Push Notifications or Pinpoint in your project? This issue might stem from there

**Comment by mjmostachetti** [comment]
There is one call to Analytics.updateEndpoint. Besides that I'm using Pinpoint to send push notifications from the server. I'm not using the amplify push notifications library.

**Comment by tannerabread** [comment]
Sorry @mjmostachetti I missed your response.

That EventsBuffer class is only used in by Pinpoint, here is a link to the [code where it is imported](https://github.com/aws-amplify/amplify-js/blob/main/packages/analytics/src/Providers/AWSPinpointProvider.ts#L32)

We can try to debug your updateEndpoint call if you can post it here but that would be where the error is being thrown

**Comment by tannerabread** [comment]
I'll close this for now, but if you want help with what was previously asked please comment and let me know

**Comment by tyndria** [comment]
@tannerabread hi, I'm having the same problem now and I'm using push notifications
Do you need details from me or you already have some guesses?

thanks!

**Comment by tannerabread** [comment]
@tyndria if you could provide some details on how you are using PN in your project, what version you are on (maybe your package.json), and confirm that you are seeing the same error as the OP that would be a good start

Is this only when Datastore Sync completes as well?

**Comment by tannerabread** [comment]
yes that would probably be best

**Comment by tyndria** [comment]
@tannerabread done: https://github.com/aws-amplify/amplify-js/issues/11097
