### ISSUE TITLE
Project No Longer Builds

### ISSUE THREAD

**Issue by ianfmc** [aws-amplify/amplify-js#10971]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

18.12.1

### Amplify CLI Version

10.7.1

### What operating system are you using?

MacOS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No.

### Describe the bug

Updated package.json file. Previously working application now does not build.

```
Error: node_modules/@aws-sdk/util-retry/dist-types/AdaptiveRetryStrategy.d.ts:1:20 - error TS2305: Module '"@aws-sdk/types"' has no exported member 'RetryErrorInfo'.

1 import { Provider, RetryErrorInfo, RetryStrategyV2, RetryToken, StandardRetryToken } from "@aws-sdk/types";
                     ~~~~~~~~~~~~~~


Error: node_modules/@aws-sdk/util-retry/dist-types/AdaptiveRetryStrategy.d.ts:1:36 - error TS2724: '"@aws-sdk/types"' has no exported member named 'RetryStrategyV2'. Did you mean 'RetryStrategy'?

1 import { Provider, RetryErrorInfo, RetryStrategyV2, RetryToken, StandardRetryToken } from "@aws-sdk/types";
                                     ~~~~~~~~~~~~~~~


Error: node_modules/@aws-sdk/util-retry/dist-types/AdaptiveRetryStrategy.d.ts:1:53 - error TS2305: Module '"@aws-sdk/types"' has no exported member 'RetryToken'.

1 import { Provider, RetryErrorInfo, RetryStrategyV2, RetryToken, StandardRetryToken } from "@aws-sdk/types";
                                                      ~~~~~~~~~~


Error: node_modules/@aws-sdk/util-retry/dist-types/AdaptiveRetryStrategy.d.ts:1:65 - error TS2305: Module '"@aws-sdk/types"' has no exported member 'StandardRetryToken'.

1 import { Provider, RetryErrorInfo, RetryStrategyV2, RetryToken, StandardRetryToken } from "@aws-sdk/types";
                                                                  ~~~~~~~~~~~~~~~~~~


Error: node_modules/@aws-sdk/util-retry/dist-types/StandardRetryStrategy.d.ts:1:20 - error TS2305: Module '"@aws-sdk/types"' has no exported member 'RetryErrorInfo'.

1 import { Provider, RetryErrorInfo, RetryStrategyV2, StandardRetryToken } from "@aws-sdk/types";
                     ~~~~~~~~~~~~~~


Error: node_modules/@aws-sdk/util-retry/dist-types/StandardRetryStrategy.d.ts:1:36 - error TS2724: '"@aws-sdk/types"' has no exported member named 'RetryStrategyV2'. Did you mean 'RetryStrategy'?

1 import { Provider, RetryErrorInfo, RetryStrategyV2, StandardRetryToken } from "@aws-sdk/types";
                                     ~~~~~~~~~~~~~~~


Error: node_modules/@aws-sdk/util-retry/dist-types/StandardRetryStrategy.d.ts:1:53 - error TS2305: Module '"@aws-sdk/types"' has no exported member 'StandardRetryToken'.

1 import { Provider, RetryErrorInfo, RetryStrategyV2, StandardRetryToken } from "@aws-sdk/types";
```

### Expected behavior

Application should build.

### Reproduction steps

1. updated package.json file with npm update -g npm-check-upgrades
2. run ng build

### Project Identifier

**project identifier**: 57d9c35c7fe718a21c0bb7bab86f4f1b

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

package.json file is listed below:

```
{
  "name": "elyc-online",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "node --max_old_space_size=8196 node_modules/@angular/cli/bin/ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "browser": {
    "crypto": false
  },
  "private": true,
  "dependencies": {
    "@angular-material-extensions/password-strength": "^12.0.2",
    "@angular/animations": "^15.0.3",
    "@angular/cdk": "^15.0.1",
    "@angular/common": "^15.0.3",
    "@angular/compiler": "^15.0.3",
    "@angular/core": "^15.0.3",
    "@angular/forms": "^15.0.3",
    "@angular/material": "^15.0.1",
    "@angular/platform-browser": "^15.0.3",
    "@angular/platform-browser-dynamic": "^15.0.3",
    "@angular/router": "^15.0.3",
    "@aws-amplify/api-graphql": "^3.0.5",
    "@aws-amplify/cli": "^10.7.2",
    "@aws-amplify/core": "^5.0.14",
    "@aws-amplify/ui-angular": "^3.2.7",
    "@aws-sdk/client-cognito-identity-provider": "^3.267.0",
    "@aws-sdk/client-s3": "^3.267.0",
    "@aws-sdk/s3-request-presigner": "^3.267.0",
    "@aws-sdk/types": "3.267.0",
    "@stripe/stripe-js": "^1.46.0",
    "@types/stripe-checkout": "^1.0.4",
    "@types/stripe-v3": "^3.1.27",
    "aws-amplify": "^5.0.14",
    "aws-amplify-angular": "^6.0.60",
    "aws-rum-web": "^1.12.0",
    "hammerjs": "^2.0.8",
    "libphonenumber-js": "^1.10.14",
    "rxjs": "^7.6.0",
    "stripe": "^11.2.0",
    "tslib": "^2.4.1",
    "zone.js": "~0.12.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.0.2",
    "@angular/cli": "^15.0.2",
    "@angular/compiler-cli": "^15.0.3",
    "@angular/language-service": "^15.0.3",
    "@types/jasmine": "^4.3.1",
    "@types/jasminewd2": "^2.0.10",
    "@types/node": "^18.11.11",
    "codelyzer": "^6.0.2",
    "jasmine-core": "^4.5.0",
    "jasmine-spec-reporter": "^7.0.0",
    "karma": "^6.4.1",
    "karma-chrome-launcher": "^3.1.1",
    "karma-coverage-istanbul-reporter": "^3.0.3",
    "karma-jasmine": "^5.1.0",
    "karma-jasmine-html-reporter": "^2.0.0",
    "mock-amplify-auth": "^2.2.0",
    "protractor": "~7.0.0",
    "schematics-scss-migrate": "^1.3.15",
    "ts-node": "~10.9.1",
    "tslint": "~5.20.1",
    "typescript": "~4.8.4"
  }
}

```

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by tannerabread** [comment]
Hi @ianfmc I believe the problem comes from the `@aws-sdk` upgrades. Amplify is currently pinned to @aws-sdk v3.6.1. It cannot be upgraded outside of a major version upgrade sometime in the future.

Can you supply what your `package.json` was before the upgrade?

Additionally but probably unrelated to your error, the `aws-amplify-angular` package has been [deprecated](https://www.npmjs.com/package/aws-amplify-angular) as of [v5.0.0](https://github.com/aws-amplify/amplify-js/releases/tag/aws-amplify%405.0.0) as it is the legacy UI package for the library.

**Comment by ianfmc** [comment]
> Hi @ianfmc I believe the problem comes from the `@aws-sdk` upgrades. Amplify is currently pinned to @aws-sdk v3.6.1. It cannot be upgraded outside of a major version upgrade sometime in the future.
> 
> Can you supply what your `package.json` was before the upgrade?
> 
> Additionally but probably unrelated to your error, the `aws-amplify-angular` package has been [deprecated](https://www.npmjs.com/package/aws-amplify-angular) as of [v5.0.0](https://github.com/aws-amplify/amplify-js/releases/tag/aws-amplify%405.0.0) as it is the legacy UI package for the library.

Thanks, Tanner...I removed aws-amplify-angular and the application compiles and works. I went line by line through the package.json and when I tried to find the latest aws-amplify-angular, it simply didn't return anything. Is there a general way to find deprecated packages? How did you come across the link you provided? Appreciate it!

**Comment by tannerabread** [comment]
I don't have a good reason other than I was here during the release and knew about it. We are currently trying to find a way to help with the discovery of those deprecated packages and documentation. Any feedback or suggestions you can make in order to make this easier to find would be appreciated. 

I don't know the exact date of when the package was switched from the legacy `aws-amplify-angular` to the newer `@aws-amplify/ui-angular`, but it should remain that going forward.

For future reference, we have split the UI into a [separate repo](https://github.com/aws-amplify/amplify-ui) that also has its own [documentation site](https://ui.docs.amplify.aws/angular/getting-started/installation) in order to decouple the main JS package from UI components. Any UI updates should be published to that docs site and followed through the other repo.

And here is a link to the [releases page](https://github.com/aws-amplify/amplify-js/releases), which we are trying to keep updated now with each new release.

**Comment by ianfmc** [comment]
That's a good question! I will start reading the release notes before I update the package.json for sure...Makes sense to change to the new package format, looks like I just missed it. I also appreciate the responsiveness...

**Comment by tannerabread** [comment]
We appreciate you opening this issue so we can identify gaps in our documentation. I will close it for now but feel free to open a new issue if you run in to more problems with our library.

Thank you!
