### ISSUE TITLE
"No Cognito Identity pool provided for unauthenticated access" when using @aws-amplify/api

### ISSUE THREAD

**Issue by cpineda** [aws-amplify/amplify-js#10999]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

GraphQL API

### Amplify Categories

auth, api

### Environment information

<details>

```
# Put output below this line
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 9.1.3 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Safari: 16.1
  npmGlobalPackages:
    @aws-amplify/cli: 10.5.2
    aws-cdk: 2.54.0
    corepack: 0.14.2
    create-next-app: 13.1.1
    lerna: 6.1.0
    npm: 9.1.3
    yarn: 1.22.19
```

</details>

### Describe the bug

When using the API.graphql library for a Mutation using @aws_cognito_user_pools auth I had this import:

```
import { API } from '@aws-amplify/api'
import { Auth } from 'aws-amplify'
```

When I ran my query I got this error:
"No Cognito Identity pool provided for unauthenticated access"

Then I changed the code to have these imports:

```
import { Auth, API } from 'aws-amplify'
```

The query run successfully.

Auth.configure had the information needed as the query run successfully and authenticated using the aws-amplify import.

### Expected behavior

Consistency between the APIs or clear documentation on differences between the two. Documentation for example here calls out specific functionality in @aws-amplify/api library: https://aws.amazon.com/blogs/mobile/announcing-aws-amplify-javascript-library-version-5/

### Reproduction steps

See description of bug.

dependencies:
```
"@aws-amplify/api": "5.0.7"
"aws-amplify": "5.0.6",
```

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by iartemiev** [comment]
Does your package.json contain both `@aws-amplify/api` and `aws-amplify`?

If so, we don't recommend manually installing the scoped packages (`@aws-amplify/*`) as well as `aws-amplify` into the same project. This can create duplicate dependencies which can cause unexpected behavior such as what you're describing. 

Note that `@aws-amplify/api` is a dependency of `aws-amplify`, so you can still import from `@aws-amplify/api` in your App code if you'd like, even if you've only installed `aws-amplify`. The key point is to avoid explicitly installing them both via the package manager you're using.

**Comment by cpineda** [comment]
Yes the package.json includes both, I'll follow your advice. Are there generally good practices on when to use one or the other? Will for example `was-amplify` have feature parity with `@aws-amplify/api`? Thanks.

**Comment by chrisbonifacio** [comment]
@cpineda Generally it's better to go with `aws-amplify` if you're generating Amplify generated & managed resources.

Using only the scoped api package, just as an example, might make sense if you are using it to make requests to an API Gateway endpoint, or simply as a data fetching library (it uses axios under the hood), and are manually configuring API with your own non-Amplify generated resources as opposed to the Amplify CLI generated `aws-exports.js` file.

However, seeing as how you're using more than just the api resource (I see auth/Cognito in the schema), it's simpler to use the `aws-amplify` package to configure multiple categories (api, auth, etc) with Amplify.configure with the `aws-exports` file. You can still import scoped packages from it and [tree-shaking](https://developer.mozilla.org/en-US/docs/Glossary/Tree_shaking) will keep the js bundle from including unused Amplify libraries.
