### ISSUE TITLE
Android  Class referenced in the manifest, com.amazonaws.amplify.pushnotification.RNPushNotificationDeviceIDService, was not found in the project or the libraries

### ISSUE THREAD

**Issue by linweiboy** [aws-amplify/amplify-js#11032]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Push Notifications

### Amplify Categories

notifications

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

my configuration environment：
 "aws-amplify": "^5.0.16",
 "@aws-amplify/pushnotification": "^5.0.16",
 "react": "18.0.0",
 "react-native": "0.69.1",
I followed the configuration steps, and finally when running Android, this problem occurs [https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/js/#setup-for-android](url)

![image](https://user-images.githubusercontent.com/31678213/221749558-8cac4baf-6af1-4d3f-bf0f-fa148c99ec3f.png)

### Expected behavior

It is expected that you can accurately access AWS push on Android

### Reproduction steps

1. install  "aws-amplify": "^5.0.16", "@aws-amplify/pushnotification": "^5.0.16";
2. Add classpath("com.google.gms:google-services") in the dependencies under buildscript;
3. Open android/app/build.gradle and Add firebase libs to the dependencies, add apply plugin: "com.google.gms.google-services";
4. Open android/app/src/main/AndroidManifest.xml file and add the following configuration into application element.
5. Open android/app/src/main/AndroidManifest.xml file and add the following configuration into application:
<application ... >

    
        
        <service
            android:name="com.amazonaws.amplify.pushnotification.RNPushNotificationMessagingService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
        </service>
        
        
        <service
            android:name="com.amazonaws.amplify.pushnotification.RNPushNotificationDeviceIDService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>
        <receiver
            android:name="com.amazonaws.amplify.pushnotification.modules.RNPushNotificationBroadcastReceiver"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.amazonaws.amplify.pushnotification.NOTIFICATION_OPENED"/>
            </intent-filter>
        </receiver>
    

</application>

### Code Snippet

none

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Mobile Device

Android Samsung

### Mobile Operating System

Android 12

### Mobile Browser

Chrome

### Mobile Browser Version

22

### Additional information and screenshots

![image](https://user-images.githubusercontent.com/31678213/221753255-e775b328-5052-4a2b-9e01-97c170a52647.png)

**Comment by tannerabread** [comment]
Hi @linweiboy I am not seeing this error with the setup you mentioned. I started with a new react native project v0.69.1 and added the bare minimum as in your steps, I don't get that error.

It's possible this is an IDE error, can you try to restart the IDE or invalidate your cache on android studio and then restart?

**Comment by linweiboy** [comment]
> 
Hi @tannerabread ,because I did not find the RNPushNotificationBroadcastReceiver file and the RNPushNotificationBroadcastReceiver file in the Android aws-amplify-pushnotification package

<img width="520" alt="image" src="https://user-images.githubusercontent.com/31678213/223001436-cac38e8e-c3f5-4f8f-92ea-169ab15650c8.png">

**Comment by linweiboy** [comment]
@tannerabread I checked the latest version of "@aws-amplify/pushnotification": "^5.0.16", in the source code, Android does not have that file, and the path "com.amazonaws.amplify.pushnotification.modules.RNPushNotificationBroadcastReceiver" is also wrong , so should the operation steps need to be updated?

![image](https://user-images.githubusercontent.com/31678213/223015105-8aec8f1c-80e1-4e8c-b45c-c86142275c58.png)

**Comment by tannerabread** [comment]
@linweiboy I see what you mean now, are you having just linter errors or is it effecting your build also?

**Comment by linweiboy** [comment]
I commented out those two related places, so that it can be built, but I don't know if it will affect the reception and related processing functions.

**Comment by tannerabread** [comment]
I investigated this further and it seems like the docs change was missed when these files were removed. You are safe to remove those two imports in the manifest and I have [opened a docs PR to fix this ](https://github.com/aws-amplify/docs/pull/5218)

Thank you for pointing this out!
