### ISSUE TITLE
`PASSWORD_VERIFIER` challenge fails if `Auth` uses the default authentication flow: `USER_SRP_AUTH`

### ISSUE THREAD

**Issue by Kapelianovych** [aws-amplify/amplify-js#11034]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Solid JS

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 1.16 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.7.0 - /opt/homebrew/bin/node
    npm: 9.5.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 110.0.5481.77
    Firefox: 110.0
    Safari: 16.3
  npmPackages:
    @aws-amplify/auth: ^5.1.10 => 5.1.10 
    @aws-amplify/core: ^5.0.16 => 5.0.16 
    @babel/core: ^7.20.2 => 7.21.0 (7.12.9)
    @halo-lab/future: ^0.0.5 => 0.0.5 
    @okikio/sharedworker: ^1.0.4 => 1.0.4 
    @solid-primitives/intersection-observer: ^2.0.3 => 2.0.6 
    @solid-primitives/resize-observer: ^2.0.7 => 2.0.9 
    @solid-primitives/scroll: ^2.0.6 => 2.0.8 
    @solidjs/meta: ^0.28.2 => 0.28.2 
    @solidjs/router: ^0.6.0 => 0.6.0 
    @storybook/addon-actions: ^6.5.16 => 6.5.16 
    @storybook/addon-essentials: ^6.5.16 => 6.5.16 
    @storybook/addon-interactions: ^6.5.16 => 6.5.16 
    @storybook/addon-links: ^6.5.16 => 6.5.16 
    @storybook/builder-vite: ^0.4.2 => 0.4.2 
    @storybook/html: ^6.5.16 => 6.5.16 
    @storybook/testing-library: ^0.0.13 => 0.0.13 
    @types/sharedworker: ^0.0.91 => 0.0.91 
    amazon-cognito-identity-js: ^6.1.2 => 6.1.2 
    autoprefixer: ^10.4.13 => 10.4.13 (9.8.8)
    babel-loader: ^8.3.0 => 8.3.0 
    bowser: ^2.11.0 => 2.11.0 
    jwt-decode: ^3.1.2 => 3.1.2 
    postcss: ^8.4.19 => 8.4.21 (7.0.39)
    prettier: ^2.7.1 => 2.8.4 (2.3.0)
    rxjs: ^7.8.0 => 7.8.0 
    rxjs/ajax:  undefined ()
    rxjs/fetch:  undefined ()
    rxjs/operators:  undefined ()
    rxjs/testing:  undefined ()
    rxjs/webSocket:  undefined ()
    solid-js: ^1.6.11 => 1.6.11 
    solid-js/h:  undefined ()
    solid-js/h/jsx-dev-runtime:  undefined ()
    solid-js/h/jsx-runtime:  undefined ()
    solid-js/html:  undefined ()
    solid-js/store:  undefined ()
    solid-js/universal:  undefined ()
    solid-js/web:  undefined ()
    tailwind-scrollbar: ^2.1.0 => 2.1.0 
    tailwindcss: ^3.2.4 => 3.2.7 
    ts-brand: ^0.0.2 => 0.0.2 
    tslib: ^2.4.1 => 2.5.0 (1.14.1)
    typescript: ^4.9.3 => 4.9.5 
    vite: ^4.0.0 => 4.1.4 
    vite-plugin-solid: ^2.5.0 => 2.5.0 
    vite-plugin-solid-svg: ^0.6.0 => 0.6.0 
    zustand: ^4.3.2 => 4.3.4 
  npmGlobalPackages:
    npm: 9.5.0

```

</details>

### Describe the bug

By using the `Auth.signIn` method the first request `InitiateAuth` succeeds and the next `PASSWORD_VERIFIER` fails with `NotAuthorizedException`. When I provide config for the `Auth` module:

```js
Auth.configure({
  authenticationFlowType: 'USER_PASSWORD_AUTH',
});
```

the `Auth.signIn` succeeds and the `signIn` event is fired.

Federated login (Google, Facebook) works as expected.

### Expected behavior

I expect the `USER_SRP_AUTH ` flow to work correctly without triggering error.

### Reproduction steps

I don't have special reproduction steps. You can bootstrap a simple application and try to login with email and password. 

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line
[Log] [DEBUG] 28:28.459 Amplify - amplify config (chunk-Y37TKAW5.js, line 4532)
  {
    Auth: {
      oauth: {
        domain: "e*********.amazoncognito.com"
        redirectSignIn: "https://localhost:3000/account/external"
        redirectSignOut: "https://localhost:3000/my"
        responseType: "code"
      },
    region: "u********"
    userPoolId: "u**********"
    userPoolWebClientId: "1************l"
    }
  }
[Log] [DEBUG] 28:28.460 I18n - configure I18n (chunk-Y37TKAW5.js, line 4522)
[Log] [DEBUG] 28:28.460 I18n - create I18n instance (chunk-Y37TKAW5.js, line 4522)
[Log] [DEBUG] 28:28.461 AuthClass - configure Auth (chunk-Y37TKAW5.js, line 4522)
[Log] [DEBUG] 28:28.461 Parser - parse config – [Object, "to amplifyconfig", Object] (3) (chunk-Y37TKAW5.js, line 4532)
[Object, "to amplifyconfig", Object]Array (3)
[Log] [DEBUG] 28:28.462 Hub - Dispatching to auth with  – {event: "parsingCallbackUrl", data: {url: "https://localhost:3000/my"}, message: "The callback url is being parsed"} (chunk-Y37TKAW5.js, line 4532)
[Log] [DEBUG] 28:28.463 Hub - Dispatching to auth with  – {event: "parsingCallbackUrl", data: {url: "https://localhost:3000/my"}, message: "The callback url is being parsed"} (chunk-Y37TKAW5.js, line 4532)
[Log] [DEBUG] 28:28.465 Hub - Dispatching to auth with  – {event: "configured", data: null, message: "The Auth category has been configured successfully"} (chunk-Y37TKAW5.js, line 4532)
[Log] [DEBUG] 28:28.465 Hub - Dispatching to auth with  – {event: "configured", data: null, message: "The Auth category has been configured successfully"} (chunk-Y37TKAW5.js, line 4532)
[Log] [DEBUG] 28:28.466 AuthClass - configure Auth (chunk-Y37TKAW5.js, line 4522)
[Log] [DEBUG] 28:28.466 Parser - parse config – [{}, "to amplifyconfig", Object] (3) (chunk-Y37TKAW5.js, line 4532)
[{}, "to amplifyconfig", Object]Array (3)
[Log] [DEBUG] 28:28.466 Hub - Dispatching to auth with  – {event: "parsingCallbackUrl", data: {url: "https://localhost:3000/my"}, message: "The callback url is being parsed"} (chunk-Y37TKAW5.js, line 4532)
[Log] [DEBUG] 28:28.467 Hub - Dispatching to auth with  – {event: "parsingCallbackUrl", data: {url: "https://localhost:3000/my"}, message: "The callback url is being parsed"} (chunk-Y37TKAW5.js, line 4532)
[Log] [DEBUG] 28:28.467 Hub - Dispatching to auth with  – {event: "configured", data: null, message: "The Auth category has been configured successfully"} (chunk-Y37TKAW5.js, line 4532)
[Log] [DEBUG] 28:28.467 Hub - Dispatching to auth with  – {event: "configured", data: null, message: "The Auth category has been configured successfully"} (chunk-Y37TKAW5.js, line 4532)
[Error] Failed to load resource: the server responded with a status of 400 () (cognito-idp.u********.amazonaws.com, line 0)
[Log] [DEBUG] 28:52.810 AuthClass - signIn failure – NotAuthorizedException: Incorrect username or password. (chunk-Y37TKAW5.js, line 4532)
NotAuthorizedException: Incorrect username or password.
[Log] [DEBUG] 28:52.811 Hub - Dispatching to auth with  – {event: "signIn_failure", data: NotAuthorizedException: Incorrect username or password., message: "4c9508e7-c5ca-497f-9898-122a6befab8f failed to signin"} (chunk-Y37TKAW5.js, line 4532)
{event: "signIn_failure", data: NotAuthorizedException: Incorrect username or password., message: "4c9508e7-c5ca-497f-9898-122a6befab8f failed to signin"}
[Log] [DEBUG] 28:52.812 Hub - Dispatching to auth with  – {event: "signIn_failure", data: NotAuthorizedException: Incorrect username or password., message: "4c9508e7-c5ca-497f-9898-122a6befab8f failed to signin"} (chunk-Y37TKAW5.js, line 4532)
{event: "signIn_failure", data: NotAuthorizedException: Incorrect username or password., message: "4c9508e7-c5ca-497f-9898-122a6befab8f failed to signin"}

```

</details>

### Manual configuration

```js
	Amplify.configure({
		Auth: {
			region:"u********",
			userPoolId: "u********",
			userPoolWebClientId: "1************l",
			oauth: {
				domain: "e*********.amazoncognito.com",
				responseType: 'code',
				redirectSignIn: `${location.origin}/account/external`,
				redirectSignOut: `${location.origin}/my`,
			},
		},
	});

```

**Comment by nadetastic** [comment]
Hi @Kapelianovych thank you for raising this issue.

Do you have MFA/TOTP or a custom auth flow defined?

**Comment by Kapelianovych** [comment]
Hello, @nadetastic. At the current moment there is no implementation for the MFA/TOTP but we plan to add it in the future. We have one special way to sign up though (not through the `Auth.signUp`). The sign up functionality is hosted on the server-side, because we have to make a record in our database. All other methods (`signIn`, `forgetPassword`, `resetPassword`, etc.) are invoked in the browser. Can it be that autogenerated password is different because of the environment difference? The strange thing is that it worked and stopped not a long ago (a week ago or so).

**Comment by ak37165** [comment]
Answering for @Kapelianovych: Yes, those flows are allowed in our App Client.

![image](https://user-images.githubusercontent.com/10171302/223165851-0eef8c2b-bba4-4a86-ab84-d863b5da9784.png)

**Comment by Kapelianovych** [comment]
@nadetastic hello. Sorry for the late response. In addition to the @ak37165's answer: we have MFA enabled in auth flow, but we see problems even with accounts which didn't set up the MFA verification.

**Comment by nadetastic** [comment]
Also, an additional thought I had, you mention that sign up is handled differently, which leads me to believe you are using `AdminCreateUser` to sign up your users - can you also confirm this?

**Comment by ak37165** [comment]
@nadetastic - We have checked that the users are not in FORCE_CHANGE_PASSWORD state. The Auth.SignIn call succeeds is we use USER_PASSWORD_AUTH. The exact same user and with all remaining code staying the same, Auth.SignIn fails if we set the authenticationFlowType to USER_SRP_AUTH.

(Regarding how users are created: They are created from our server-side code. We use the .Net SDK, AmazonCognitoIdentityProviderClient.SignUpAsync with a pre-signup Lambda trigger to mark the email verified, using code based on this example: [](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-sign-up.html#aws-lambda-triggers-pre-registration-example-2). This ensures that the user is good to login.)

**Comment by nadetastic** [comment]
@ak37165 Is the Password Verifier challenge returned from `Auth.signIn` and are needing to handle that yourself?

**Comment by Kapelianovych** [comment]
@nadetastic we provide the password along with the username in one go like this:

```ts
Auth.signIn({ username: 'some@domain.io', password: 'sdlhlskdhfl5a' });
```

I debugged the `signIn` and saw that it triggers two calls and the second is password verifier which is failed.

**Comment by nadetastic** [comment]
@Kapelianovych As far as your signUp method, are you including a [SecretHash](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_SignUp.html#CognitoUserPools-SignUp-request-SecretHash)? Also could you share the network logs as well?

**Comment by ak37165** [comment]
@nadetastic SignUp method does use SecretHash (as its using an AppClientId that does need a secret; intended for server side use). The SignIn method is using a different AppClient, with no secret, as its intended for client side Javascript use.

Could you please advise where to find the network logs? Would they be on AWS Cognito server side or would they be from the Amplify JS client side.

**Comment by ak37165** [comment]
> @nadetastic we provide the password along with the username in one go like this:
> 
> ```ts
> Auth.signIn({ username: 'some@domain.io', password: 'sdlhlskdhfl5a' });
> ```
> 
> I debugged the `signIn` and saw that it triggers two calls and the second one is the password verifier that always fails.

Also to add, we are using the AWS Amplify library's [SignIn method](https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js/#sign-in) which **internally** makes the two calls needed in the SRP flow. So our code only makes one call to Auth.SignIn() with both username and password provided.

**Comment by Kapelianovych** [comment]
@nadetastic we send the email and password as raw values and some project specific data to the server while signing up. We don't do anything more on the client. As for the server's part @ak37165 may provide more information.

As for the login process I can show you the info about requests:
1. *InitiateAuth* operation:
```
**Summary**
URL: https://cognito-idp.us-xxxx-x.amazonaws.com/
Status: 200
Source: Network
Address: 3x.2xx.xxx.x4:443
Initiator: Client.js:102

**Request**
:method: POST
:scheme: https
:authority: cognito-idp.us-xxxx-x.amazonaws.com
:path: /
Content-Type: application/x-amz-json-1.1
Accept: */*
Accept-Language: en-GB,en;q=0.9
Accept-Encoding: gzip, deflate, br
Cache-Control: no-store
Host: cognito-idp.us-xxxx-x.amazonaws.com
Origin: https://localhost:3000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15
Referer: https://localhost:3000/
Content-Length: 913
Connection: keep-alive
X-Amz-User-Agent: aws-amplify/5.0.4 js
X-Amz-Target: AWSCognitoIdentityProviderService.InitiateAuth

**Response**
:status: 200
Date: Wed, 08 Mar 2023 09:49:18 GMT
Access-Control-Expose-Headers: x-amzn-RequestId,x-amzn-ErrorType,x-amzn-ErrorMessage,Date
Content-Type: application/x-amz-json-1.1
Content-Length: 2731
Access-Control-Allow-Origin: *
x-amzn-requestid: 4135xxxx-9aa2-44xx-86cc-xxxx02xxxx47

**Request Data**
MIME Type: application/x-amz-json-1.1
Request Data:
{
	"AuthFlow": "USER_SRP_AUTH",
	"ClientId": "xxxxx37xxxxxeixxxxxuvxxxxx",
	"AuthParameters": {
		"USERNAME": "foo@gmail.com",
		"SRP_A": "cb051910b23be4c1c0b3db78d4ea059f3992605fc4e2cc0e288396352c89831cf8781ef7491096ab9e8c0dd9a6eedbc99a9ffb575c2c1a51ceb8977cbd10c1bdb9dc38205043c1df2eeec3ea99c9fb1a215e54bf9d7627e70750c5de4de070309a91ffb519cda47d80ccc8f48159f45f88f21b5800e49d286cce88289349a742f075aa7094248fa9ce98eb2275e50cb77c5e62a244f19d02555c6d0bb0315fa1e8f04f629304c02b955e1347c2b78ddb2d7fa7d9243da8c567411e77e804ee0ace06f35b7d4bc4ed82c80320c20b70079a2ece0a0b2228c00695ed5509964183dd1f6bb249b1e69a81fb1171d1ee3c1d00103dcde74b91ec2a4a499e155967815aa09378a40d45351a2e48028389c7b7ce9c45471e0e8d4d96c57c250ab5d9632e333c472c3e0ad8a7195bd6a089858cac9935e05852cc3c3845ca3ad568cd31259b03d18c958ebafced4c0ea1f4acaa3bb00d3602afcaa0a455465d53e5132fe57b65620b59a53d76a90f31c1320fe7c604114d3fd095cd68516a5cd6e28265"
	},
	"ClientMetadata": {}
}
```
2. *RespondToAuthChallenge*:
```
**Summary**
URL: https://cognito-idp.us-xxx-x.amazonaws.com/
Status: 400
Source: Network
Address: 1x.2xx.xx.1xx:443
Initiator: Client.js:102

**Request**
:method: POST
:scheme: https
:authority: cognito-idp.us-xxxx-x.amazonaws.com
:path: /
Content-Type: application/x-amz-json-1.1
Accept: */*
Accept-Language: en-GB,en;q=0.9
Accept-Encoding: gzip, deflate, br
Cache-Control: no-store
Host: cognito-idp.us-xxxx-x.amazonaws.com
Origin: https://localhost:3000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15
Referer: https://localhost:3000/
Content-Length: 2043
Connection: keep-alive
X-Amz-User-Agent: aws-amplify/5.0.4 js
X-Amz-Target: AWSCognitoIdentityProviderService.RespondToAuthChallenge

**Response**
:status: 400
Content-Type: application/x-amz-json-1.1
Access-Control-Expose-Headers: x-amzn-RequestId,x-amzn-ErrorType,x-amzn-ErrorMessage,Date
Date: Wed, 08 Mar 2023 10:07:45 GMT
Content-Length: 79
Access-Control-Allow-Origin: *
x-amzn-errortype: NotAuthorizedException:
x-amzn-requestid: 5ca10e66-24a1-4c63-b268-a88abe75cf03
x-amzn-errormessage: Incorrect username or password.

**Request Data**
MIME Type: application/x-amz-json-1.1
Request Data:
{
	"ChallengeName": "PASSWORD_VERIFIER",
	"ClientId": "xxxxx37xxxxxeixxxxxuvxxxxx",
	"ChallengeResponses": {
		"USERNAME": "4cxxxxe7-xxxx-49xf-xxx-xxxxxbefab8f",
		"PASSWORD_CLAIM_SECRET_BLOCK": "3E4wHYjW+Qy+DraLBxHbt6KKiiQnHZlOspdjEJIFr9MNISBmQ2LW/17L1hGuiURnAnwQc+p7WnS3DWK6nxOzhISb0wE868QIcEu/UxZmy0lmFCkVZd1kQObHqEMgkEY/acyti9MG+ED6LAOmr4kPKaUruXYoiJLE4TeaWv4z4rDNJsWlz9w7AOoYm0et2Am2ElAODcC92PvLbvyXOSUdM0KSzVEzdqPa1sEt8JDy00mV2wtvE9tBAcwubZ+Oc+UY7HfG0hTJckubYkY/yLMs4UlWS/+e8KWXkPsNgXYi2WTl1vXw45NTTUjZs8MONeFAm994NPrFeS8BKu4MpowR6SGktexcCAhvm1qV3+SDREyO8o/2w45Qqh2zbpm9fwLRuandbl/xdgOg29QKvyR2sOai72StVpOSceadM3gytES81H2Ty3TF56ZXi354Hq38C+etTqJqRucAbmU1YeZStT57HID/xlYWoQztSXL7Qydp9qjCKA/+A1P+rldF2hYWNHXUwgGzWjnZz6lbsXuRDkk1CJaQO8n3yxAkUpw+/QqUQns/3//lJuDWLsuOpD3QmTU0YPwdh94o3m8/HkVDCSfiWh0KtMiPJU3XQzwl2/rWToP2VAmQVljNE/DnbouH6PfaFfxA9hLdHI1kYEK7cr57fL/VTYtAIaXYY3/LVkXhrKQW/co4kDdrRDPfyUdIUuRcoZE5wpTP6KIeufyfNf8zq6mO8RsZbyaGaH1VmdMmfspXubEg1ebj5R8vCSP5gK41bH0OUpiXqWG2vupNxdzVIbkIMmdXh6fG7nSGkRQusiiR3eY/9e5ckJO5tWtcGWkgl2za2z1kJ74OCk6BJyB6OHts4/X/XBTVJ70lVAlOC8sHjFHhpA7PFHCPR+QZ+Rq+1zISaql7Vq03gpqENQvD6KeWYGBDDA3fQYBSlI0yxjemi61c3Erh7cr270k382CCSL3ejF+13Pr+hEtycd+EDRbfpGegrV7bA4xUoBNUYPkSyzoEmbgkolNw70EUxPsjk81sSlQhFomadGAmd+zm2rfmwqPMBBtgioUxrzK3jCFMA+T5bMEn8gZgt51wVJEdDcuuYGR6eF3c1rgo3/qIhlECVwkVVgtlUdcPvO/NPjjFsNmoW/Bth8fr2OWElrDyL5LR6G+MGqHsRF6c41QVXHiVgiq2axFDQlrLIPZjPhi3+5e5+Of1AWUM750saBG1i03gRv30JvsfLSul6cn9PUtAVQSZqPVNAy0SjPnmISh3Rs6OwLwauHR2FizPV2mWYgahmQEywfz0cW3Ritv6eYREL9+6EVUAFKqQHcSe8PpTSO7WmoqIBAQWsxqxrjrXLJIlAAQNUd6uECgyMRwf3ndlzu+NR63+nRLhGmj3Uh3Cjl53+8VxjxCPAdiK1jXwBc/SipCQCpwCsufUM/jBf4eCot3cvurg2sHjFCQtqXR/6wKi8rDDzoN8Y93RLUKFudc3Zwz3V5lPNkCuVqMvVrF6/DG1GjENrNl/1XHgt66AF/QlQh1UksGrrCqfkbe0BkozYR8J7L/vi7aubGvZ8sQ6ZRaJsn7/wtyZ1bgFspUxrZzFzzoc9lkhubpJU7U78PmpFndRJJzWn2Uuza0HOlPNIsiGfRHJBR8qi9Pn+bgouzH17LtQFLPD+NppZ4QZhNxFMiq/fj4ZLdV8ZVNprieFNReGLr0heCK9CevF+mh2HpL7QP1kbw==",
		"TIMESTAMP": "Wed Mar 8 10:03:19 UTC 2023",
		"PASSWORD_CLAIM_SIGNATURE": "984L7cOp0+s/TVNKqwr8cRM8aOkHJUb1E6bmcsWfZ2o="
	},
	"ClientMetadata": {}
}
```

**Comment by nadetastic** [comment]
@ak37165 @Kapelianovych  Thank you for the clarification. I believe the problem here is that you are sending the password as a raw value when signing up and then using SRP to signIn. The fact that regular username_password sign in flow is working also suggests this, and signIn returns incorrect username or _password_.

I'm doing some testing to confirm this and will follow up with my findings.

**Comment by nadetastic** [comment]
So far I am not facing this issue, I am able to sign up a user with the aws sdk using a client with a secret and then sign in via amplify through a different client with no secret without issue.

im hoping to eliminate where this issue may lay (Amplify vs Cognito). Are you able to test sign in directly through the hosted UI?

**Comment by nadetastic** [comment]
Also any additional context on how the server side sign up code is configured (parameters included etc) would be helpful.

**Comment by ak37165** [comment]
Here are some additional details on server side signup:

The server uses this request in AmazonCognitoIdentityProviderClient.SignUpAsync 

` 
var signupRequest = new SignUpRequest
            {
                ClientId = <ServerAppClientId, that uses secret>,
                Password = <new password provided by yuser when signing up>,
                SecretHash = ComputeSecretHash(email), // computed using email as the username (userpool is set to use email as username)
                UserAttributes = new List<AttributeType>
                {
                    new AttributeType{ Name = "custom:e****", Value = <string value>},
                    new AttributeType{ Name = "custom:a***", Value = <string value>}
                },

                // Cognito does not store ClientMetadata but only passes it to lambda triggers.
                ClientMetadata = new Dictionary<string, string>
                {
                    {"serversignupsecret", "used by presignup lambda to verify the signup request" }
                },
                Username = email
            };
`

The presignup lambda sets the following on the new user:

`
// Confirm the user
        event.response.autoConfirmUser = true;

        // Set the email as verified if it is in the request 
        // (also ensure its in lowercase, as email supplied by social provider may not be lowercase)
        if (event.request.userAttributes.hasOwnProperty("email")) {
            event.request.userAttributes["email"] = event.request.userAttributes["email"].toLowerCase();            
            event.response.autoVerifyEmail = true;
        }

        // Set the phone number as verified if it is in the request
        if (event.request.userAttributes.hasOwnProperty("phone_number")) {
            event.response.autoVerifyPhone = true;
        }

        // Return to Amazon Cognito
        callback(null, event);
`

**Comment by ak37165** [comment]
Hosted UI is working fine with the same AppClient (the one used from AmplifyJS):

**response_type=code**
Signing in with hosted UI https://e****.auth.us-east-1.amazoncognito.com/login?response_type=code&client_id=1***l&redirect_uri=https%3A%2F%***
correctly redirects to our-callback-url?code=999ee099-guid-truncated-for-github-message

**response_type=token**
Signing in with the hosted UI https://e****.auth.us-east-1.amazoncognito.com/login?response_type=token&client_id=1***l&redirect_uri=https%3A%2F%***
correctly redirects to our-callback-url#id_token=eyJraWQiOiJkZFJL...&expires_in=3600&token_type=Bearer

Also, as Auth.SignIn with Password flow is working, it would seem the user signup is happening correctly.
Even Auth.SignIn with SRP flow had worked until about Feb 20 (same userpool and AppClient settings).

**Comment by nadetastic** [comment]
@ak37165 any context on what may have changed when it stopped working on or before Feb20?

**Comment by ak37165** [comment]
@nadetastic We do not believe anything related to signin changed in our code around then. The confusing this is jut changing the authentication flow to password makes it work.

**Comment by nadetastic** [comment]
@ak37165 @Kapelianovych Could you share a copy of your package.json as well a simple version of you Solid app that main shows the use of `aws-amplify`? Additionally, we can try and connect on a call to help streamline our conversation but there may be timezone differences.

**Comment by ak-en** [comment]
@nadetastic We will create the minimal version and share it with you. Is there a way to send it to you privately?

**Comment by nadetastic** [comment]
If possible, you can set a private repo and add me as a collaborator @ak-en

**Comment by ak-en** [comment]
@nadetastic Thanks. Got it, will do.

**Comment by nadetastic** [comment]
Received - will work to reproduce and follow here with my findings
