### ISSUE TITLE
Amplify Predictions convert text to audio does not work for voice: Kevin

### ISSUE THREAD

**Issue by evertson90** [aws-amplify/amplify-js#11046]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.13.2

### Amplify CLI Version

10.8.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

When I run amplify add predictions, Generate speech audio from text, I choose speaker: Kevin - Male.

When I try to run Predictions.convert({textToSpeech .... }) without giving a voiceId, I get the following error from the backend:

"This voice does not support the selected engine: standard"

When I explicitly add the voiceId of "Kevin", it also does not work.
Only when I add voiceId of "Amy" does it work. 

CLI commands:
Evertsons-MacBook-Pro:theamplifyapp evertsoncroes$ amplify add predictions
✔ Please select from one of the categories below · Convert
✔ What would you like to convert? · Generate speech audio from text
✔ Provide a friendly name for your resource · speechGenerator11c4cfca
? What is the source language? ...  (Use arrow keys or type to filter)
✔ What is the source language? · US English
✔ Select a speaker · Kevin - Male
✔ Who should have access? · Auth users only
Successfully added resource speechGenerator11c4cfca locally

### Expected behavior

That the polly /speech endpoint returns a success response

### Reproduction steps

1. Check out this project at this commit: https://gitlab.com/evertson90/theamplifyapp/-/commit/87db85a1acf0bf057fc86070cf3271d6990540c8
2. run "amplify add predictions"
3. See "describe the bug" section for answers I used
4. run "amplify push"
5. Run convert in the following way:

`Predictions.convert({
      textToSpeech: {
        source: {
          text: this.textInput
        }
      }
    })`

### Project Identifier

bfaf6cb7a4743f03f665dbc0848381fe

### Log output

<details>

```
# Put your logs below this line
{"message":"This voice does not support the selected engine: standard"}

```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by cwomack** [comment]
Hello, @evertson90 👋.  If you're using the voices "Amy" and "Kevin" within the Amazon Polly for text to speech, they fall under [different categories](https://docs.aws.amazon.com/polly/latest/dg/voicelist.html#:~:text=the%20Voices.-,Available%20Voices,-Amazon%20Polly%20provides) for what type of voice they are (Neural vs. Standard).  This means that the string that needs to be passed in as the [engine](https://docs.aws.amazon.com/polly/latest/dg/API_SynthesizeSpeech.html#API_SynthesizeSpeech_RequestSyntax:~:text=in%20JSON%20format.-,Engine,-Specifies%20the%20engine) parameter needs to match.  

"Amy" can be both Neural Voice and Standard Voice, while "Kevin" appears to be ONLY Neural.  If you get a chance to look at that chart that breaks down the voice options (and shows on the far right 2 columns which engine/voice is supported), does it seem like the messages you get back align?

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!

**Comment by frederic-nevers** [comment]
Hi @cwomack, 
It appears Amplify Predictions does not support the required option to set the engine to 'neural' and is always set to 'standard' when a call is made (it may even be 'null' - not sure). Below are the interface definitions in Predictions.d.ts 

The 'engine' bit is missing. Is that expected behaviour? In the Amplify Predictions documentation, there is no mention of any API limitations with Polly. It is also unclear what 'terminology' refers to (is it the same as Lexicon?).

export interface TextToSpeechInput {
    textToSpeech: {
        source: {
            text: string;
        };
        terminology?: string;
        voiceId?: string;
    };
}
export interface TextToSpeechOutput {
    speech: {
        url: string;
    };
    audioStream: Buffer;
    text: string;
}

**Comment by philip1986** [comment]
Can we please reopen the issue? I don't think the question answered. How can one use a "natural" voice through Amplify Predictions?

**Comment by GauthierWillemse** [comment]
I am having the same issues. Text-to-speech conversion is working smoothly but only with the mediocre non-neural voices. I would like to know how I can use the neural voices as well. Please reopen @cwomack 
Thank you!
