### ISSUE TITLE
Auth.currentUserCredentials() doesn't throw an exception on error

### ISSUE THREAD

**Issue by its-aazizi** [aws-amplify/amplify-js#11071]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
 System:
    OS: macOS 13.2.1
    CPU: (8) x64 Apple M1
    Memory: 32.32 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.2 - ~/.nvm/versions/node/v14.19.2/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.2/bin/npm
    Watchman: 2022.10.03.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 110.0
    Safari: 16.3
  npmPackages:
    @aws-amplify/ui-react: ^3.5.11 => 3.6.1 
    @aws-amplify/ui-react-internal:  undefined ()
    @aws-amplify/ui-react-legacy:  undefined ()
    @tanstack/react-query: ^4.22.0 => 4.22.0 
    @turf/turf: ^6.5.0 => 6.5.0 
    @types/aws-sdk: ^2.7.0 => 2.7.0 
    @types/mapbox__mapbox-gl-draw: ^1.3.3 => 1.3.3 
    @types/ngeohash: ^0.6.4 => 0.6.4 
    @types/node: ^18.11.9 => 18.11.18 
    @types/ramda: ^0.28.18 => 0.28.20 
    @types/react: ^18.0.17 => 18.0.26 
    @types/react-dom: ^18.0.6 => 18.0.10 
    @types/react-lottie: ^1.2.6 => 1.2.6 
    @types/react-syntax-highlighter: ^15.5.6 => 15.5.6 
    @typescript-eslint/eslint-plugin: 5.33.1 => 5.33.1 
    @typescript-eslint/parser: 5.33.1 => 5.33.1 
    @vitejs/plugin-react: ^2.1.0 => 2.2.0 
    aws-amplify: ^4.3.43 => 4.3.45 
    aws-sdk: ^2.1248.0 => 2.1293.0 
    csvtojson: ^2.0.10 => 2.0.10 
    date-fns: ^2.29.3 => 2.29.3 
    eslint: 8.22.0 => 8.22.0 
    eslint-config-prettier: ^8.5.0 => 8.6.0 
    eslint-plugin-flowtype: ^8.0.3 => 8.0.3 
    eslint-plugin-import: ^2.26.0 => 2.27.4 
    eslint-plugin-jsx-a11y: ^6.6.1 => 6.7.1 
    eslint-plugin-prettier: ^4.2.1 => 4.2.1 
    eslint-plugin-react: ^7.30.1 => 7.32.0 
    eslint-plugin-react-hooks: ^4.6.0 => 4.6.0 
    mapbox-gl-draw-circle: ^1.1.2 => 1.1.2 
    ngeohash: ^0.6.3 => 0.6.3 
    prettier: ^2.7.1 => 2.8.2 
    ramda: ^0.28.0 => 0.28.0 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    react-html-parser: ^2.0.2 => 2.0.2 
    react-html-parser-demo:  0.0.0 
    react-lottie: ^1.2.3 => 1.2.3 
    react-router-dom: ^6.4.3 => 6.6.2 
    react-syntax-highlighter: ^15.5.0 => 15.5.0 
    react-toastify: ^9.1.1 => 9.1.1 
    react-tooltip: ^5.8.3 => 5.8.3 
    react-visibility-sensor: 5.1.1 => 5.1.1 
    sass: ^1.57.1 => 1.57.1 
    stylelint: ^14.15.0 => 14.16.1 
    stylelint-config-airbnb: ^0.0.0 => 0.0.0 
    stylelint-config-prettier: ^9.0.4 => 9.0.4 
    stylelint-config-standard: ^29.0.0 => 29.0.0 
    stylelint-order: ^5.0.0 => 5.0.0 
    stylelint-prettier: ^2.0.0 => 2.0.0 
    typescript: ^4.9.3 => 4.9.4 
    vite: ^3.1.0 => 3.2.5 
    vite-plugin-eslint: ^1.7.0 => 1.8.1 
    vite-plugin-svgr: ^2.2.1 => 2.4.0 
    zustand: ^4.1.4 => 4.3.1 
  npmGlobalPackages:
    corepack: 0.10.0
    localtunnel: 2.0.2
    npm: 6.14.17

```

</details>

### Describe the bug

When fetch current user creds using Auth.currentUserCredentials() with an incorrect IdentityPoolId in amplify's config, the method doesn't throw an exception, instead it return the error as it is. Which is ResourceNotFound with a status code of 400.

### Expected behavior

It should throw an exception so that try catch block can take care of the exception accordingly.

### Reproduction steps

1. install Amplify sdk
2. configure amplify using Amplify.configure [link to doc](https://docs.amplify.aws/lib/client-configuration/configuring-amplify-categories/q/platform/js/#scoped-configuration)
3. import Auth module from amplify
4. wrap Auth.currentUserCredentials() in try catch and note that an exception will not be thrown and code execution will remain in try block

### Code Snippet

```javascript
// Put your code below this line.
try {
    const credentials = await getCurrentUserCredentials();
    console.log({ credentials });
} catch (error) {
    console.error({ error });
}
```

### Log output

<details>

```
// Put your logs below this line

{
    "name": "ResourceNotFoundException",
    "$fault": "client",
    "$metadata": {
        "httpStatusCode": 400,
        "requestId": "1ed79f7d-211a-4370-88fa-81a436c503e0",
        "attempts": 1,
        "totalRetryDelay": 0
    }
}
```

</details>

**Comment by tannerabread** [comment]
Hi @its-aazizi, I was able to reproduce this and will mark it as a bug as I believe the currentUserCredentials method is not returning as it should when an error is thrown.

I would like to confirm your thoughts though that this would most likely not be a user-facing bug and would be found during development only since it involves putting in the wrong IdentityPoolId

**Comment by cwomack** [comment]
Related to #10823

**Comment by its-aazizi** [comment]
Hi @tannerabread Yes this is mainly encountered during development, but in my current use case user can also run into this error and needs to be handled accordingly, because we allow the user to connect their own account by taking their IdentityPoolId, furthermore during stack rotation if env is updated user is likely to run into this error as well.

**Comment by cwomack** [comment]
@its-aazizi, apologies for the delays in communication on this issue.  This bug was part of the work that had been done in v6 to completely rewrite the Auth API's and improve error handling.  The errors referenced in this issue are being thrown as expected when the identity pool id is invalid in v6 of Amplify.  

We'd recommend upgrading to v6 and reviewing the docs covering the new [getCurrentUser](https://docs.amplify.aws/react/build-a-backend/auth/manage-user-session/#retrieve-your-current-authenticated-use) and [fetchAuthSession](https://docs.amplify.aws/react/build-a-backend/auth/manage-user-session/#retrieve-a-user-session) API's to test this yourself. I'll close this as resolved, but let me know if there are more questions/concerns!
