### ISSUE TITLE
How to query nested nodes in graphql APi

### ISSUE THREAD

**Issue by ShaimaaHamdan** [aws-amplify/amplify-js#11079]
### Which Specific Feature is your question related to?

Graphql API

### Question

I am trying to fetch data from certain Menu model using graphql API  which have many to many relation ship with menuitem model but always the menuitems array come empty array following is my model and my query any one know how to load it ?

```
type Menu @model @auth(rules: [{allow: public}]) {
  id: ID
  name: String
  description: String
  isDefault: Boolean
  image: String
  restaurantID: ID! @index(name: "byRestaurant")
  isActive: Boolean
  MenuItems: [MenuItem!] @manyToMany(relationName: "MenuMenuItem")
}
type MenuItem @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String
  description: String
  image: String
  price: Float
  isActive: Boolean
  MenuCategory: MenuCategory @hasOne
  ordersID: ID! @index(name: "byOrders")
  menus: [Menu] @manyToMany(relationName: "MenuMenuItem")
}
 
 await API.graphql<GraphQLQuery<GetMenuQuery>>(
      graphqlOperation(queries.getMenu, { id: this.selectedMenu })

    ).then(({data})=>{
      console.log('mutation complete', data);
    });
```  
always the menuitems come with empty array

**Comment by david-mcafee** [comment]
@ShaimaaHamdan can you also add a snippet of how you are attempting to create the `Menu` and `MenuItem` records? Thank you!

**Comment by david-mcafee** [comment]
@ShaimaaHamdan - are you sure that you are also creating the appropriate records for the join table?

For example, with the following schema:

```graphql
type Post @model {
  id: ID!
  title: String!
  blog: Blog @belongsTo
  comments: [Comment] @hasMany
  tags: [Tag] @manyToMany(relationName: "PostTags")
}

type Tag @model {
  id: ID!
  label: String!
  posts: [Post] @manyToMany(relationName: "PostTags")
}
```

I would create the join between Post and Comment as follows:

```typescript
const postTagDetails: CreatePostTagsInput = {
    postId: currentPostId,
    tagId: currentTagId,
};

const newPostTag = await API.graphql<GraphQLQuery<CreatePostTagsMutation>>({
    query: mutations.createPostTags,
    variables: { input: postTagDetails },
});
```

I would then either query Post or Tag to get the nested m:n record:

```typescript
const post = await API.graphql<GraphQLQuery<GetPostQuery>>({
    query: queries.getPost,
    variables: { id: postId },
});

const tag = await API.graphql<GraphQLQuery<GetTagQuery>>({
    query: queries.getTag,
    variables: { id: tagId },
});
```

If you'd like to see it working in the context of a full repro, see here: https://github.com/david-mcafee/amplify-graphql-api-relational/blob/main/src/App.tsx

Let me know if this helps! :)

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
