### ISSUE TITLE
Next 13 'app' directory

### ISSUE THREAD

**Issue by ben-sommer** [aws-amplify/amplify-js#11074]
### Is this related to a new or existing framework?

Next.js

### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

When will the Next 13 'app' directory be supported for SSR? The [docs](https://docs.aws.amazon.com/amplify/latest/userguide/ssr-Amplify-support.html) say `Next.js 13 app directory (beta)` is an `Unsupported feature` but there is no indication of if/when this support will be added. 

### Describe the solution you'd like

In [server components](https://beta.nextjs.org/docs/rendering/server-and-client-components#server-components) there should be a way to call Auth APIs such as `currentAuthenticatedUser()`. In older versions of Next this was achieved by passing the `getServerSideProps` `request` object into `withSSRContext`, but as Next 13 server components do not receive any equivalent `request` object from `layout.tsx`, there is nothing to pass into `withSSRContext`.

### Describe alternatives you've considered

I have tried creating an object with a similar structure to the Next 12 `getServerSideProps` `request` object manually using Next 13's `cookies()` function which returns the cookies in server components, but this method throws `Error: Amplify has not been configured correctly.`.

### Additional context

`cookies.ts`
```ts
export const serialize = (c: any) => {
  const attrs = [
    "path" in c && c.path && `Path=${c.path}`,
    "expires" in c && c.expires && `Expires=${c.expires.toUTCString()}`,
    "maxAge" in c && c.maxAge && `Max-Age=${c.maxAge}`,
    "domain" in c && c.domain && `Domain=${c.domain}`,
    "secure" in c && c.secure && "Secure",
    "httpOnly" in c && c.httpOnly && "HttpOnly",
    "sameSite" in c && c.sameSite && `SameSite=${c.sameSite}`,
  ].filter(Boolean);

  return `${c.name}=${c.value ? decodeURIComponent(c.value) : ""}; ${
    attrs.join("; ") + (attrs.length > 0 ? "; " : "")
  }`;
};

export const serializeMultiple = (cookies: any[]) => {
  return cookies.map(serialize).join("");
};
```

`page.tsx` (e.g. a login page - only shown to unauthenticated users)
```tsx
export default async function Page() {
  const cookieStore = cookies();

  const { Auth: serverAuth } = withSSRContext({
    req: { headers: { cookie: serializeMultiple(cookieStore.getAll()) } },
  });

  console.log(serverAuth.configure());

  try {
    const user = await serverAuth.currentAuthenticatedUser();

    console.log(user);

    return redirect("/dashboard");
  } catch (e) {
    return (
        /* rest of component */
    ```

**Comment by ben-sommer** [comment]
Found a workaround that was suggested as the solution for a different problem in #8011. In my case, calling `serverAuth.configure(myAuthConfiguration)` after calling `withSSRContext` worked. I could then use `serverAuth.currentAuthenticatedUser()` as expected without any issues. Note that I still had to Frankenstein the cookies into `withSSRContext` - is there any chance this could be fixed in a future update?

**Comment by Tomekmularczyk** [comment]
Hi @ben-sommer ! thanks for the snippet, I'm having the same issue - how to fetch data with amplify in server components, where there is no `req` object. Based on your suggestion I tried this:

```tsx
export default async function EventPage() {
  const cookieStore = cookies();
  const SSR = withSSRContext({
    req: { headers: { cookie: serializeMultiple(cookieStore.getAll()) } },
  });
  const config = JSON.parse(process.env.NEXT_PUBLIC_AWS_EXPORTS_CONFIG!);
  SSR.configure({ ...config, ssr: true });

  const user = await SSR.Auth.currentAuthenticatedUser();
  console.log(user);

  return <>TODO</>;
}
```

but I'm still getting errors in the console:

> error - The user is not authenticated
error - [Error: Error: The user is not authenticated] { digest: '193452068' }

Do you know how to fix it?

PS. I think you should reopen the issue, we need a good solution to use amplify in server components when they become a standard.

**Comment by yepMad** [comment]
That's still a problem, right?

**Comment by abdallahshaban557** [comment]
Hi @yepMad  - we have guidance available now for how to use Amplify in the App directory from NextJS - please let us know if this resolves your problem. If not, please create a new Github issue for us to better track this.

https://docs.amplify.aws/lib/ssr/q/platform/js/#use-amplify-with-nextjs-app-router-app-directory

**Comment by abdallahshaban557** [comment]
Hi @JKeddo95  - are you still investigating how to enable your app to work with Amplify Hosting? It sounds like you were not really trying to use the libraries here - so I would recommend if you are still facing issues - please create a Github issue [here](https://github.com/aws-amplify/amplify-hosting/issues/new?assignees=&labels=bug%2Cpending-triage&projects=&template=1.bug_report.yaml)
