### ISSUE TITLE
Typescript 2.9.2 and type error

### ISSUE THREAD

**Issue by romainquellec** [aws-amplify/amplify-js#1108]
Hi ! I just updated typescript to escape a crafty bug with previous version of typescript.
Now, I've got this error with aws-amplify.

```
ERROR in /frontend/node_modules/aws-amplify/lib/Interactions/Interactions.d.ts(19,44):
TS7006: Parameter 'err' implicitly has an 'any' type.
ERROR in /frontend/node_modules/aws-amplify/lib/Interactions/Interactions.d.ts(19,49):
TS7006: Parameter 'confirmation' implicitly has an 'any' type.
```

**Comment by powerful23** [comment]
@romainquellec can you set the `noImplicitAny` to `false` in your typescript config? Unfortunately for now amplify hasn't eliminated all the implicit any types yet.

**Comment by jordanranz** [comment]
@romainquellec have you tried @powerful23's suggestion or do you have any update on this?

**Comment by romainquellec** [comment]
yes, its working with noImplicitAny tricks. 
But it should work without these kind of tricks, right ?

(I can still close this issue if you want)

**Comment by powerful23** [comment]
Mark this issue as `enhancement`.

**Comment by romainquellec** [comment]
Closing this.
