### ISSUE TITLE
DataStore - Sync error DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.

### ISSUE THREAD

**Issue by Chipui-Kasar** [aws-amplify/amplify-js#11098]
### Before opening, please confirm:

- [x] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

GraphQL API, DataStore

### Amplify Categories

api

### Environment information

<details>

```
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 5500U with Radeon Graphics
    Memory: 895.63 MB / 7.33 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (110.0.1587.69)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @aws-amplify/ui-react: ^4.0.3 => 4.4.0 
    @aws-amplify/ui-react-internal:  undefined ()
    @aws-sdk/client-cognito-identity-provider: ^3.259.0 => 3.290.0 
    @testing-library/jest-dom: ^5.16.5 => 5.16.5 
    @testing-library/react: ^13.4.0 => 13.4.0 
    @testing-library/user-event: ^13.5.0 => 13.5.0 
    @types/jest: ^27.5.2 => 27.5.2 
    @types/node: ^16.18.3 => 16.18.16 
    @types/react: ^18.0.25 => 18.0.28 
    @types/react-dom: ^18.0.9 => 18.0.11 
    @types/react-router-dom: ^5.3.3 => 5.3.3 
    @types/react-transition-group: ^4.4.1 => 4.4.5 
    aws-amplify: ^5.0.4 => 5.0.19 
    aws-sdk: ^2.1332.0 => 2.1335.0 
    chart.js: 3.9.1 => 3.9.1
    chart.js-auto:  undefined ()
    chart.js-helpers:  undefined ()
    chartjs-plugin-datalabels: ^2.1.0 => 2.2.0
    ini: ^1.3.5 => 1.3.8
    inquirer: ^6.5.1 => 6.5.2
    moment: ^2.29.4 => 2.29.4
    primeicons: ^6.0.1 => 6.0.1
    primereact: ^8.7.2 => 8.7.3
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    react-router-dom: 6.3.0 => 6.3.0
    react-scripts: 5.0.1 => 5.0.1
    react-transition-group: ^4.4.1 => 4.4.5
    react-transition-group/CSSTransition:  undefined ()
    react-transition-group/ReplaceTransition:  undefined ()
    react-transition-group/SwitchTransition:  undefined ()
    react-transition-group/Transition:  undefined ()
    react-transition-group/TransitionGroup:  undefined ()
    react-transition-group/TransitionGroupContext:  undefined ()
    react-transition-group/config:  undefined ()
    sass: ^1.54.8 => 1.59.3
    typescript: ^4.9.3 => 4.9.5
    web-vitals: ^2.1.4 => 2.1.4
    webpack-cli: ^5.0.1 => 5.0.1
    xlsx: ^0.18.5 => 0.18.5
  npmGlobalPackages:
    @aws-amplify/cli: 10.8.1
    corepack: 0.15.2
    npm: 9.2.0
    typescript: 4.9.5


```

</details>

### Describe the bug

I'm trying to fetch the data of a table from dynamodb using DataStore.
I'm getting an error, 
_TypeError: Cannot read properties of undefined (reading 'message') at handler (datastore.ts:1482:1)_

<img width="427" alt="Screenshot 2023-03-17 162729" src="https://user-images.githubusercontent.com/52714538/225886322-aaed9148-f973-495e-97df-aa253e8f4588.png">

### Expected behavior

I want to get the items available in a table

### Reproduction steps

When trying to access the table with DataStore

### Code Snippet

```javascript
// Put your code below this line.
const models = await DataStore.query(dxVendors);
        console.log(models);
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

@rideddy84

**Comment by chrisbonifacio** [comment]
Hi @Chipui-Kasar 👋 thanks for raising this issue!

Can you run `amplify status` to make sure there are no pending updates to the schema that need to be deployed?

Afterwards, try running `amplify codegen models` and refresh the app.

**Comment by Chipui-Kasar** [comment]
> Hi @Chipui-Kasar 👋 thanks for raising this issue!
> 
> Can you run `amplify status` to make sure there are no pending updates to the schema that need to be deployed?
> 
> If there are, run `amplify push`.
> 
> Afterwards, try running `amplify codegen models` and refresh the app.

Have tried all the steps you've mentioned, none works

**Comment by chrisbonifacio** [comment]
@Chipui-Kasar can you share your GraphQL schema and how you're importing the models?

**Comment by chrisbonifacio** [comment]
Did you create any records outside of DataStore by chance?

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
