### ISSUE TITLE
Wrong type definitions on user.signOut()

### ISSUE THREAD

**Issue by seivan** [aws-amplify/amplify-js#11109]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line

Irrellevant 
```

</details>

### Describe the bug

The signature is incorrect for `signOut` since it passes an error in the callback, but missing in type definition
```ts
public signOut(callback?: () => void): void;
```

### Expected behavior

The signature for `signOut` should pass an optional error in the callback
```ts
public signOut(callback?: (error?: Error | undefined) => void): void;
```

### Reproduction steps

```ts
user.signOut(() => {
//? Handle error? 
}
```

### Code Snippet

```javascript
// Put your code below this line.

```

**Comment by tannerabread** [comment]
Hi @seivan we are working on improvements to our types and TypeScript so I will bring this up with the rest of the team to ensure it gets included in the efforts.

Thanks for bringing it to our attention!

**Comment by seivan** [comment]
Do you want me to fix it? Or rewrite the cognito layer in TS? I don’t mind and would probably fix most of your issues.

**Comment by tannerabread** [comment]
Hi @seivan I was waiting for it to go live but you can check out this [new RFC for typescript improvements](https://github.com/aws-amplify/amplify-js/issues/11113) and leave feedback there so that we can hopefully incorporate all of your feedback.

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
