### ISSUE TITLE
Bug  When sign in/sign up /forget password using aws amplify with ionic

### ISSUE THREAD

**Issue by Jasminou** [aws-amplify/amplify-js#1110]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
Can't sign in or sign up or forgot password(email are not even send) with aws amplify on mobile (with ionic-cordova). and getting this error message: 
{code: "UnknownError", message: "Unkown error" }
Also is working fine on webApp 

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.
I just tried to sign up a user or sign in user as usual 
What is the expected behavior?
to be able to login/sign up a user
Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
   "aws-amplify": "^0.4.1",
    "aws-amplify-angular": "^0.1.1",
on mobile framework (ionic cordova)
I also tried to update my amplify version for the latest version: 
    "aws-amplify": "^0.4.6",
    "aws-amplify-angular": "^0.1.6",

and I'm getting the same issues again can't login or wtvr 

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.
![image](https://user-images.githubusercontent.com/14798195/41919963-b1862896-792d-11e8-97ab-7f3197cbf793.png)

when I comment the mandatory sign in, i got this error
![image](https://user-images.githubusercontent.com/14798195/41920483-d27b5d5e-792e-11e8-912f-21cb24aa0338.png)

**Comment by powerful23** [comment]
Can you look into the network tab and provide some info around the sign in http request?

**Comment by Jasminou** [comment]
@powerful23 it's not possible for me now to reproduce the issues its working again sinece few minutes ( didn't work all day. It's first time that I was facing this issues

**Comment by Jasminou** [comment]
@powerful23 I did see 302 http code in the request and 200 for the get one, I don't know if its related to the 302

**Comment by arsewizz** [comment]
can you please share your package.json file ? @Jasminou

**Comment by jordanranz** [comment]
Going to close this as the original issue has been solved. Please reopen if you have any more related questions.
