### ISSUE TITLE
Filter a collection by current user/owner

### ISSUE THREAD

**Issue by flying-mojo** [aws-amplify/amplify-js#11115]
### Which Specific Feature is your question related to?

Auth, Content, Data

### Question

Hi!
I have a UI collection associated with the following schema:
type Question @model @auth(rules: [{allow: owner, ownerField: "creator"}, {allow: private}]) {
  id: ID!
  title: String
  creator: String
}

How can I filter that collection to display only record that belong to the current user (i.e. creator filed equals to the current user)?

**Comment by iartemiev** [comment]
My comment above assumes you're using `DataStore` but after re-reading your question, it's not clear whether you are or not. 

If you're just using the Amplify API category you can also modify the auth rule to limit client access only to records created by that user. 

Or you can pass a filter to your list query ([link to docs](https://docs.amplify.aws/lib/graphqlapi/query-data/q/platform/js/#filtering-queries))
```js
const variables = {
  filter: {
    creator: {
      eq: user.username
    }
  }
};

const res = await API.graphql({ 
  query: listQuestions, variables
});;
```

**Comment by flying-mojo** [comment]
Thank you @iartemiev !
The filter option works fine (but not with eq operator only with contains operator - no idea why, but thats a different problem;)
Is there a benefit/recommendation to use DataStore over graphql API directly? I am using the graphql API so would like to know if it is recommended to switch to DataStore.
Thank you!

**Comment by chrisbonifacio** [comment]
@flying-mojo Unless you specifically have a need for offline-first functionality in your app, I would recommend continuing to use API.graphql for the versatility and control over your graphql statements. DataStore abstracts some of that away by generating the queries/mutations at runtime and requires you to reason about the sync process and how it would help your app's use case.
