### ISSUE TITLE
PubSub 'topicSymbol' is now an entry in the message instead of a JS symbol

### ISSUE THREAD

**Issue by WolfWalter** [aws-amplify/amplify-js#11114]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

PubSub

### Amplify Categories

Not applicable

### Environment information

<details>

```
 System:
    OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1265U
    Memory: 25.72 GB / 46.73 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 3.2.2 - ~/.nvm/versions/node/v18.13.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
  npmPackages:
    fs-extra: ^11.1.0 => 11.1.0 
  npmGlobalPackages:
    @githubnext/github-copilot-cli: 0.1.20
    corepack: 0.15.2
    npm: 8.19.3

```

</details>

### Describe the bug

After the PR https://github.com/aws-amplify/amplify-js/pull/10954 from aws-amplify  5.0.17 till current the pubsub message format has been changed.

`topicSymbol` is now an object key and the Symbol is not used anymore. This totally changed how to get the topic and the message object gets altered in an unexpected way.
https://github.com/aws-amplify/amplify-js/commit/5147c5ce555d042722e2888fc423430f517b91b7#diff-2a29f8a41f2b66733bb64a134e53acb5e67615e026667885a5686ce933d3869eL267-R300

This change seems unintentional and breaks existing code, like the workarround to read the message topic mentioned in https://github.com/aws-amplify/amplify-js/issues/1025.

### Expected behavior

`topicSymbol` stays an JS Symbol or the topic name gets returned with the message, but most importantly the message keeps unchanged and not polluted with unexpected keys.

### Reproduction steps

Receive and console.log pubsub messages.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by nadetastic** [comment]
Hi @WolfWalter thank you for opening this issue. I can verify that the behavior changed and the topic name is now included as the object key instead of a Symbol. Im discussing this with the team, however Im curious of any issues that you may see your self experience by reading the topic name from the object instead of as a symbol?

FYI you should still be able to access the topic name through `data.value.topicSymbol` as the payload now has this shape

```json
{
    "provider": "<AWSIoTProvider>",
    "value": {
        "message": "........",
        "topicSymbol":"mytopic/dev"
    }
}
```

**Comment by WolfWalter** [comment]
Hi @nadetastic,
no real issue on my end. But it was an unexpected breaking change and I was not sure if I should change my code or this change will be reverted. 
If it stays that way "topicSymbol" is a strange name. "topic" would be more sensible. I could also image where an extra key in the payload could lead to unexpected behavior if you expect a fixed format four your payload. `data.topic` would be optimal imho.

**Comment by nadetastic** [comment]
@WolfWalter Got it - makes sense. We're working to revert the change for now and are discussing the option of including the topic name as part of the payload as well, for example as `data.topic` as you suggested.

**Comment by stocaaro** [comment]
The change is released. Should be back to good. Let us know if you are having any more issues around this!
