### ISSUE TITLE
How to disable login for specific page

### ISSUE THREAD

**Issue by Frankjunyulin** [aws-amplify/amplify-js#11126]
### Is this related to another service?

Auth

### Describe the feature you'd like to request

I want to disable login for my landing page (with AWS Amplify Auth).

My page is https://www.dearai.online/. By default, everyone need to login.

But I want to build a page like  https://www.dearai.online/landing which it should not require visitors to login. 

Anyway to do it? 

### Describe the solution you'd like

Not sure

### Describe alternatives you've considered

Not sure

### Additional context
My current `_app.tsx` file:
```js
Amplify.configure({
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:e1b23467-b561-4511-8c7a-91cda3bbc0cc",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_hHUKoCPHp",
  aws_user_pools_web_client_id: "57fh330o1c8lalef69g6i6h6dc",
  oauth: {
    domain: "dear3683324a-3683324a-dev.auth.us-east-1.amazoncognito.com",
    scope: [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin",
    ],
    redirectSignIn: "https://www.dearai.online/",
    redirectSignOut: "https://www.dearai.online/",
    responseType: "code",
  },
  federationTarget: "COGNITO_USER_POOLS",
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OPTIONAL",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  ssr: true,
});
Auth.configure({
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:e1b23467-b561-4511-8c7a-91cda3bbc0cc",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_hHUKoCPHp",
  aws_user_pools_web_client_id: "57fh330o1c8lalef69g6i6h6dc",
  oauth: {
    domain: "dear3683324a-3683324a-dev.auth.us-east-1.amazoncognito.com",
    scope: [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin",
    ],
    redirectSignIn: "https://www.dearai.online/",
    redirectSignOut: "https://www.dearai.online/",
    responseType: "code",
  },
  federationTarget: "COGNITO_USER_POOLS",
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OPTIONAL",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
});

function MyApp({Component, pageProps}: AppProps) {
  return <Component {...pageProps} />;
}

export default withAuthenticator(MyApp);
```

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by nadetastic** [comment]
Hi @Frankjunyulin thanks for opening this issue. From the link it looks like you are using the UI library, and in that case the recommendation is instead of wrapping the entire app with the `<Authenticator />`, you would separate them and only wrap the components that need auth, while the landing page components would not be wrapped by it.

As seen in the [UI Authenticator docs](https://ui.docs.amplify.aws/react/connected-components/authenticator#step-3-add-the-authenticator) example, all the content in wrapped by the authenticator ( `<main>... </main>`) will be protected, while any content that is placed outside of it will not be protected.

Let me know if you need more clarification.

**Comment by Frankjunyulin** [comment]
Thank you! @nadetastic
