### ISSUE TITLE
Does using AWS Mobile Hub + AWS Amplify will carry or rise problems with a HIPAA Audit process?

### ISSUE THREAD

**Issue by josoroma** [aws-amplify/amplify-js#1113]
Hi,

Just a concern about using AWS Mobile Hub + AWS Amplify in order to make easier our tasks on the frontend side:

Does the use of AWS Mobile Hub + AWS Amplify will carry or rise problems with a HIPAA Audit process?

Thanks!

**Comment by josoroma** [comment]
We don't see Mobile Hub listed as service here:

 * https://aws.amazon.com/compliance/hipaa-eligible-services-reference/

ooooooor... is it just a tool that will help our app to securely and easiily talk with a plethora of Amazon Web Services?

**Comment by ChadElias** [comment]
Hey @josoroma seems that it's a service that utilizes underlining services which are covered in the agreement.

**Comment by mlabieniec** [comment]
Mobile Hub will spin up services on your behalf, so you need to check those services for compliance
https://aws.amazon.com/compliance/hipaa-compliance/
