### ISSUE TITLE
Getting my array of strings in appsync console but not in my fetch

### ISSUE THREAD

**Issue by MatrickPF21** [aws-amplify/amplify-js#11137]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line
"aws-amplify": "^5.0.22",
amplify cli: 10.6.2

```

</details>

### Describe the bug

I have a GraphQL API with a Todo schema like:
```
type Todo @model {
  id: ID!
  name: String!
  description: String
  preferredMethods: [Methods!]
}

enum Methods {
  GET
  POST
  PUT
  DELETE
}
```
I didnt try this earlier so, for a simple query, i went to appsync console and queried for a created Todo with a list of preferredMethods and the data looks like: 
[
![image](https://user-images.githubusercontent.com/98290154/227819269-d86499ce-258b-47d3-84bc-2b4796ac6fe6.png)
](url)
So having this working, i tried in my new next app the fetch but it does not give me the preferredMethods list:
[
![image](https://user-images.githubusercontent.com/98290154/227819374-28806607-0f57-41bc-9798-68eca272fe90.png)
](url)
Using this autogenerated query:
[
![image](https://user-images.githubusercontent.com/98290154/227819451-0ac3563b-4d4e-40de-afb4-06732c91b461.png)
](url)

### Expected behavior

This query:
[
![image](https://user-images.githubusercontent.com/98290154/227819374-28806607-0f57-41bc-9798-68eca272fe90.png)
](url)
To be:
[
![image](https://user-images.githubusercontent.com/98290154/227819269-d86499ce-258b-47d3-84bc-2b4796ac6fe6.png)
](url)

### Reproduction steps

1. Create new amplify app
2. Add a GraphQL API
3. Push the schema
4. Try out

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @MatrickPF21 👋 thanks for raising this issue

When making the `getTodo` request from your Next.js app, can you check the outgoing graphql request and make sure that the `preferredMethods` field is included in the selection set of the query?

**Comment by MatrickPF21** [comment]
@chrisbonifacio So, i checked and preferredMethods wasnt in the graphql request and that was problem. I just copy the autogenerated query to the page where i fetch my todos and it works. I don't know why it didn't work when i import the query.

**Comment by chrisbonifacio** [comment]
Do you happen to have more than `graphql/queries` file? Sometimes I generate `js` files and switch my codegen configuration to `ts` and end up with a `queries.js` and `queries.ts` file. Without specifying the file extension, the `js` file gets imported and may not be up to date. While trying to reproduce this issue I was getting an unexpected response but realized I was importing the wrong file.

Might not be the case here but just mentioning it as it may be worth keeping in mind.

In any case, running `amplify codegen` will make sure your graphql statements are up to date. They should be updating after every deployment as well with any new changes made to the schema.
