### ISSUE TITLE
Geo.searchByText use Language attribute from SearchPlaceIndexForSuggestionsSummary

### ISSUE THREAD

**Issue by roelvandenbrand** [aws-amplify/amplify-js#11177]
### Is this related to a new or existing framework?

Currently using  @aws-amplify/ui-react": "^2.18.1"

### Is this related to another service?

Geo service.

### Describe the feature you'd like to request

We would want to see place lookup in a specified language. For example if we search in English for a shop in Thailand, we do not get the results in English but in Thai. Which is hard for us to read. 

### Describe the solution you'd like

We see that AWS Location supports a Language parameter in different Search methods. But the Amplify implementation for searchByText does not. 

Is it possible for the Amplify Geo component to support a language parameter to return results in?

### Describe alternatives you've considered

There is no way to set a language currently. The only workaround we are considering is using a different place-index provider.

### Additional context

Maybe it could be added to the AmazonLocationServiceProvider.ts and implemented.

### Is this something that you'd be interested in working on?

- [x] 👋 I may be able to implement this feature request

**Comment by roelvandenbrand** [comment]
What would it take to get it changed? I think I made the correct Pull Request for it.

**Comment by cwomack** [comment]
@roelvandenbrand, I'll reach out to the dev assigned to the PR and see if we can get you an update.

**Comment by roelvandenbrand** [comment]
> @roelvandenbrand, I'll reach out to the dev assigned to the PR and see if we can get you an update.

Did you hear anything back? This feature would be helpfull, otherwise we need to switch to use aws location natively to provide our customer with the feature they need.

**Comment by cwomack** [comment]
Appreciate your patience, @roelvandenbrand.  I spoke with the team internally regarding the PR and the review is still underway.  We're testing the changes and will update you either here or via comments on the PR (if further changes are needed) as soon as we can.

**Comment by roelvandenbrand** [comment]
Cool, thanks for the update @cwomack!

**Comment by roelvandenbrand** [comment]
So, we switched to AWS Location native, to have results in a difference language. After testing we might have to change the place index, because we cannot find all the locations we want to find.

**Comment by roelvandenbrand** [comment]
But it would still be a nice upgrade to support the language setting in the Amplify implementation I would think.

**Comment by cwomack** [comment]
@roelvandenbrand, this issue should now be resolved with the most recent releases! We merged your suggestions in the associated PR #11178 and will close this issue as resolved.  Please feel free to comment back and let us know if there are any issues.  Thank you for your patience and contributions!
