### ISSUE TITLE
Storage.put resumable does not call errorCallback for unauthenticated errors

### ISSUE THREAD

**Issue by dbanksdesign** [aws-amplify/amplify-js#11172]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Storage

### Amplify Categories

storage

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 12.6.3
    CPU: (8) arm64 Apple M1
    Memory: 104.19 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 9.2.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: 2023.01.02.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 111.0.5563.146
    Firefox: 102.9.0
    Safari: 16.4
  npmGlobalPackages:
    @aws-amplify/cli: 10.6.1
    @ionic/cli: 6.20.1
    corepack: 0.10.0
    gifify: 2.4.3
    gnomon: 1.5.0
    npkill: 0.8.3
    npm: 9.2.0
    npx: 10.2.2
    serve: 14.0.1


```

</details>

### Describe the bug

If there is no authenticated user and I try to upload a file with protected or private level the errorCallback doesn't get called. Instead the error gets swallowed and output on the console. 

```js
Storage.put('somefile', blob, {
  level: 'protected',
  resumable: true,
  errorCallback: () => {
    // I don't get called
  }
});
```

Doing a non-resumable upload _does_ call errorCallback in this case though.

### Expected behavior

Storage.put with resumable and `errorCallback` function for an unauthenticated user trying to upload a file should call the `errorCallback` function. 

### Reproduction steps

See above

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by nadetastic** [comment]
Hi @dbanksdesign 👋, thank you for opening this issue, I can confirm that I experience the same. I'm discussing this with the team and will follow up.

**Comment by nadetastic** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
