### ISSUE TITLE
Unable to switch social login account

### ISSUE THREAD

**Issue by parasfusemachine** [aws-amplify/amplify-js#11201]
### Is this related to a new or existing framework?

React Native

### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

Is there any way to switch social login like google after logout?

The login screen provide option to choose the account for google login but after the logged in and logout, you cannot choose the account but logins with previous selection

### Describe the solution you'd like

The login screen provide option to choose the account for google login but after the logged in and logout, you cannot choose the account but logins with previous selection

### Describe alternatives you've considered

Please allow user to choose their social login

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [X] ⚠️ This feature might incur a breaking change

**Comment by nadetastic** [comment]
Related #4044

**Comment by tannerabread** [comment]
Closing this to track progress in the above mentioned related issue (#4044)

Currently this is blocked by the Cognito service team and related to Hosted UI so any progress will be tracked on that issue.

Thank you!
