### ISSUE TITLE
Q: Cognito Auth vs. Cognito Identity? Difference?

### ISSUE THREAD

**Issue by wzup** [aws-amplify/amplify-js#1120]
What's the difference?
Why two?
Why no docs about difference?
What to use for what use cases?

https://github.com/aws/amazon-cognito-auth-js
https://github.com/aws/aws-amplify/tree/master/packages/amazon-cognito-identity-js

**Comment by wzup** [comment]
@mlabieniec 

Amplify doesn't have very important method - check if a username (email) already exists in Codnito User Pool.
Here is my issue on that
https://github.com/aws/aws-amplify/issues/1067#issuecomment-400565311

**Comment by mlabieniec** [comment]
@wzup thanks we are working on getting full feature coverage on the library w/the SDKs and will get this one moved up.

**Comment by syang** [comment]
@powerful23 does Amplify client currently support a Cognito User Pool sign-up / sign-in page, for Facebook and Google IdP, https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-social-idp.html

I wanted to build a sign-up page like this 
[landing page](https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwiOxrPNkPjdAhXjGTQIHTFBDRUQjRx6BAgBEAU&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dvr1njQyqlbk&psig=AOvVaw1ULKI7DMIdthI_afeB49NR&ust=1539132254022985)

**Comment by powerful23** [comment]
@syang you can add your customized UI in your app and use the Cognito Hosted UI to login from Google/Facebook: https://aws-amplify.github.io/amplify-js/media/authentication_guide#launching-the-hosted-ui

**Comment by syang** [comment]
@powerful23 the code snippet for React App does not seem to work. 

`import { withOAuth } from 'aws-amplify-react';

class MyApp extends React.Component {
    // ...
    render() {
        return(
            <button onClick={this.props.OAuthSignIn}>
                Sign in with AWS
            </button>
        )
    }
}

export default withOAuth(MyApp);`


How should one incorporate the "Launching the Hosted UI" (your link) into the above React code snippet?

**Comment by powerful23** [comment]
@syang if you only want to use the facebook/google sign in, you need to write your own button component which will take you to that url in https://aws-amplify.github.io/amplify-js/media/authentication_guide#launching-the-hosted-ui

**Comment by powerful23** [comment]
@askaliuk Hi, for now you can only use the Cognito Hosted UI to sign in with facebook into your Cognito User Pool. Once you get redirect back from Facebook, the url which contains the tokens will automatically be parsed by Amplify as long as you called `Auth.configure()` with your Cognito Hosted UI related setting. Then you can listen on the hub event to tell whether the parsing url succeeds or not.

Example:
```js
import {Auth, Hub} from 'aws-amplify';
// your redirected page
Auth.configure({
    awsCognito: {
     }
});

class your_component {
     constructor() {
            this.onHubCapsule = this.onHubCapsule.bind(this);
            Hub.listen('auth', this);
     }
     onHubCapsule(capsule) {
             const { channel, payload, source } = capsule;
             if (channel === 'auth' ) {
                     if (payload.event === 'signIn') //user signed in
                     if (payload.event === 'signIn_failure') //user failed to signed in
             }
        }
     }
}
```

**Comment by OndeVai** [comment]
I'm also super confused by the "amazon-cognito-auth-js" library. The documentation is very sparse and the sample doesn't shed any light. It would to make at least some mention of Amplify in this repo's readme.

@powerful23 For hosted UI, using this pattern above, how you suggest securing certain javascript pages/routes/components if the user deep links to them? For example, say there's a route "/secured" that users can only access when authenticated. I want to check if the user exists and if not, redirect to back to the hosted UI to log in.

**Comment by OndeVai** [comment]
@powerful23 Thanks for the quick response, but it looks like Auth.currentAuthenticatedUser() always fails when hitting the auth callback url from the hosted UI page the first time. It seems like the session isn't quite populated yet. I think I can work something out between using both the Hub on the callback url url and Auth.currentAuthenticatedUser() and then user Auth.currentAuthenticatedUser() to check the other routes. But, it seems like Auth.currentAuthenticatedUser() should succeed after coming back  and I should have to mess around with the Hub. Think this is worthy of a separate bug report?

**Comment by powerful23** [comment]
@OndeVai In fact we have noticed this issue. Because when you get redirected back from the hosed UI, the url has't been parsed yet so at that moment `Auth.currentAuthenticatedUser()` would return no user. You need to listen on hub events which will be emitted when parsing url finishes and at that time you can tell whether the user signs in or not. We are working on docs to make this part more clear.

**Comment by sammartinez** [comment]
Here is our documentation on [Authentication](https://aws-amplify.github.io/docs/js/authentication) within Amplify. Resolving this as the documentation is present today
