### ISSUE TITLE
Cookies not set using withSSRContext in getInitialProps

### ISSUE THREAD

**Issue by affanshahid** [aws-amplify/amplify-js#11210]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 13.3
    CPU: (12) arm64 Apple M2 Pro
    Memory: 246.50 MB / 16.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 19.8.1 - ~/Library/Caches/fnm_multishells/53166_1680965947661/bin/node
    npm: 9.5.1 - ~/Library/Caches/fnm_multishells/53166_1680965947661/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Firefox: 111.0.1
    Safari: 16.4
  npmPackages:
    @ampproject/toolbox-optimizer:  undefined ()
    @babel/core:  undefined ()
    @babel/runtime:  7.15.4
    @commitlint/cli: ^17.4.4 => 17.4.4
    @commitlint/config-conventional: ^17.4.4 => 17.4.4
    @edge-runtime/primitives:  2.0.0
    @emotion/react: ^11.10.6 => 11.10.6
    @emotion/server: ^11.10.0 => 11.10.0
    @graphql-codegen/cli: ^3.0.0 => 3.0.0
    @graphql-codegen/client-preset: ^2.0.0 => 2.0.0
    @hapi/accept:  undefined ()
    @heroicons/react: ^1.0.6 => 1.0.6
    @mantine/core: ^6.0.5 => 6.0.5
    @mantine/dates: ^6.0.5 => 6.0.5
    @mantine/dropzone: ^6.0.5 => 6.0.5
    @mantine/form: ^6.0.5 => 6.0.5
    @mantine/hooks: ^6.0.5 => 6.0.5
    @mantine/modals: ^6.0.5 => 6.0.5
    @mantine/next: ^6.0.5 => 6.0.5
    @mantine/notifications: ^6.0.5 => 6.0.5
    @napi-rs/triples:  undefined ()
    @next/font: 13.1.6 => 13.1.6
    @next/react-dev-overlay:  undefined ()
    @segment/ajv-human-errors:  undefined ()
    @types/google.maps: ^3.52.4 => 3.52.4
    @types/node: 18.13.0 => 18.13.0
    @types/react: 18.0.28 => 18.0.28
    @types/react-dom: 18.0.11 => 18.0.11
    @urql/exchange-auth: ^2.1.0 => 2.1.0
    @vercel/nft:  undefined ()
    acorn:  undefined ()
    amphtml-validator:  undefined ()
    anser:  undefined ()
    arg:  undefined ()
    assert:  undefined ()
    async-retry:  undefined ()
    async-sema:  undefined ()
    aws-amplify: ^5.0.25 => 5.0.25
    babel-packages:  undefined ()
    browserify-zlib:  undefined ()
    browserslist:  undefined ()
    buffer:  undefined ()
    bytes:  undefined ()
    chalk:  undefined ()
    change-case: ^4.1.2 => 4.1.2
    ci-info:  undefined ()
    cli-select:  undefined ()
    client-only:  0.0.1
    comment-json:  undefined ()
    compression:  undefined ()
    conf:  undefined ()
    constants-browserify:  undefined ()
    content-disposition:  undefined ()
    content-type:  undefined ()
    cookie:  undefined ()
    cross-spawn:  undefined ()
    crypto-browserify:  undefined ()
    css.escape:  undefined ()
    cssnano-simple:  undefined ()
    data-uri-to-buffer:  undefined ()
    dayjs: ^1.11.7 => 1.11.7
    debug:  undefined ()
    devalue:  undefined ()
    domain-browser:  undefined ()
    dotenv-cli: ^7.0.0 => 7.0.0
    edge-runtime:  undefined ()
    eslint: 8.34.0 => 8.34.0
    eslint-config-next: 13.1.6 => 13.1.6
    events:  undefined ()
    find-cache-dir:  undefined ()
    find-up:  undefined ()
    fresh:  undefined ()
    get-orientation:  undefined ()
    glob:  undefined ()
    graphql: ^16.6.0 => 16.6.0 (15.8.0)
    gzip-size:  undefined ()
    http-proxy:  undefined ()
    https-browserify:  undefined ()
    husky: ^8.0.3 => 8.0.3
    icss-utils:  undefined ()
    ignore-loader:  undefined ()
    image-size:  undefined ()
    is-animated:  undefined ()
    is-docker:  undefined ()
    is-wsl:  undefined ()
    jest-worker:  undefined ()
    json5:  undefined ()
    jsonwebtoken:  undefined ()
    lint-staged: ^13.1.2 => 13.1.2
    loader-utils:  undefined ()
    lodash.curry:  undefined ()
    lru-cache:  undefined ()
    micromatch:  undefined ()
    mini-css-extract-plugin:  undefined ()
    nanoid:  undefined ()
    native-url:  undefined ()
    neo-async:  undefined ()
    next: 13.1.6 => 13.1.6
    next-urql: ^5.0.0 => 5.0.0
    node-fetch:  undefined ()
    node-html-parser:  undefined ()
    ora:  undefined ()
    os-browserify:  undefined ()
    p-limit:  undefined ()
    path-browserify:  undefined ()
    platform:  undefined ()
    postcss-flexbugs-fixes:  undefined ()
    postcss-modules-extract-imports:  undefined ()
    postcss-modules-local-by-default:  undefined ()
    postcss-modules-scope:  undefined ()
    postcss-modules-values:  undefined ()
    postcss-preset-env:  undefined ()
    postcss-safe-parser:  undefined ()
    postcss-scss:  undefined ()
    postcss-value-parser:  undefined ()
    prettier: ^2.8.4 => 2.8.4
    prettier-plugin-organize-imports: ^3.2.2 => 3.2.2
    process:  undefined ()
    punycode:  undefined ()
    querystring-es3:  undefined ()
    raw-body:  undefined ()
    react: 18.2.0 => 18.2.0 (18.3.0-next-3ba7add60-20221201)
    react-dom: 18.2.0 => 18.2.0 (18.3.0-next-3ba7add60-20221201)
    react-google-autocomplete: ^2.7.3 => 2.7.3
    react-is: ^18.2.0 => 18.2.0 (16.13.1, 17.0.2)
    react-refresh:  0.12.0
    react-server-dom-webpack:  undefined ()
    regenerator-runtime:  0.13.4
    sass-loader:  undefined ()
    scheduler:  undefined ()
    schema-utils:  undefined ()
    semver:  undefined ()
    send:  undefined ()
    server-only:  0.0.1
    setimmediate:  undefined ()
    shell-quote:  undefined ()
    source-map:  undefined ()
    stacktrace-parser:  undefined ()
    states-us: ^1.0.2 => 1.0.2
    stream-browserify:  undefined ()
    stream-http:  undefined ()
    string-hash:  undefined ()
    string_decoder:  undefined ()
    strip-ansi:  undefined ()
    tar:  undefined ()
    terser:  undefined ()
    text-table:  undefined ()
    timers-browserify:  undefined ()
    tty-browserify:  undefined ()
    typescript: 4.9.5 => 4.9.5
    ua-parser-js:  undefined ()
    undici:  undefined ()
    unistore:  undefined ()
    urql: ^4.0.0 => 4.0.0
    urql-core:  undefined ()
    util:  undefined ()
    vm-browserify:  undefined ()
    watchpack:  undefined ()
    web-vitals:  undefined ()
    webpack:  undefined ()
    webpack-sources:  undefined ()
    ws:  undefined ()
  npmGlobalPackages:
    @aws-amplify/cli: 11.0.3
    corepack: 0.17.0
    npm: 9.5.1

```

</details>

### Describe the bug

Attempting to complete a login (which involves a code challenge) on the server-side using `withSSRContext` and `ssr: true` does not set any cookies even though the requests succeed.

Note: The same works perfectly if done on the client-side with `ssr: true` (i.e the cookies get set)

### Expected behavior

Upon successful completion of the auth flow, the cookies should be set and visible in the browser's inspect tools.

### Reproduction steps

1. Setup a new Next.js app
1. Install Amplify along with Auth
1. Setup code based verification
1. Create a route (ie. pages/index.tsx) that takes the user's email and code as a query param
1. Attempt to complete the auth flow in `getInitialProps`

### Code Snippet

```typescript
SomePage.getInitialProps = async (ctx) => {
  const Auth = withSSRContext(ctx).Auth;

  try {
    const user = await Auth.signIn(ctx.query.email as string);
    await Auth.sendCustomChallengeAnswer(user, ctx.query.token as string);
    redirect(ctx, '/');
  } catch {}

  return {};
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Manual configuration

```js
Amplify.configure({
  Auth: {
    region: process.env.NEXT_PUBLIC_COGNITO_REGION,
    userPoolId: process.env.NEXT_PUBLIC_COGNITO_USER_POOL_ID,
    userPoolWebClientId: process.env.NEXT_PUBLIC_COGNITO_CLIENT_ID,
  },
  ssr: true,
});
```

**Comment by tannerabread** [comment]
Hi @affanshahid the library and withSSRContext was currently only designed to [work in getServerSideProps](https://docs.amplify.aws/lib/ssr/q/platform/js/#:~:text=and%20their%20getServerSideProps%20data%20fetching%20mechanism)

Have you tried moving the logic to that data fetching mechanism instead?

**Comment by weisisheng** [comment]
FWIW, believe my experience is connected.  Trying the next.js amplify example from this page
https://docs.amplify.aws/start/getting-started/data-model/q/integration/next/
 and getting the error "Server Error Error: No current user" when trying to access the list of posts or create a new one.  This seems to be an ongoing niggling issue in the community of users.

**Comment by tannerabread** [comment]
@weisisheng 
Did that error show up following the guide as it's written? I noticed a couple of differences in the CLI prompts which I have opened an [issue in the docs for](https://github.com/aws-amplify/docs/issues/5366) showing what it should now display, but with the code provided on that page my app seems to work as expected

**Comment by tannerabread** [comment]
@affanshahid I wanted to ask what your use case was for setting it up how you had it above. What were you trying to accomplish by logging in on the server? 

The way it is set up won't work in either `getInitialProps` or `getServerSideProps` as these functions are not called on the client, and therefore cannot directly set cookies on the browser/client. You are able to `return` the information/user and capture it in your component/page, but to get the cookies to populate from that point you would basically need to rewrite the auth flow to manually set those cookies with the returned user.

The normal flow for using SSR with an Amplify app would be to login on the client, then use `getServerSideProps` along with `withSSRContext` to capture the details needed from Auth to make authenticated requests to an API or something similar. I don't believe that you can log in and hold a session on the server itself nor set the cookies on the client from either of these methods

**Comment by weisisheng** [comment]
> @weisisheng Did that error show up following the guide as it's written? I noticed a couple of differences in the CLI prompts which I have opened an [issue in the docs for](https://github.com/aws-amplify/docs/issues/5366) showing what it should now display, but with the code provided on that page my app seems to work as expected

It did.  I will try again tomorrow.  Thanks!

**Comment by weisisheng** [comment]
Doing some experimentation and I am not familiar with cookie handling.

This next.js SSR/graphl APi example from an AWS DA/community builder (?) dated 12/2020 returns "authenticated user=false".  But the DEBUG log indicates a proper access token and id token (I shortened the jwts here and removed the payloads for security and brevity purposes).  I am logged in elsewhere in the app.  What do I not understand?

# example
https://teachsomebody.com/blog/view/aXetI5qdjY4OqlBkf2ien/server-side-support-for-aws-amplify-authentication-and-graphql-api

import {withSSRContext} from 'aws-amplify'
import {createFoo} from '../src/graphql/mutations'

export async function getServerSideProps(context) {
  const { Auth, API } = withSSRContext(context)
  let is_authenticated = false
  
  try {
    const user = await Auth.currentAuthenticatedUser()
    // This is an authenticated user
    is_authenticated = true
  } catch (err) {
    console.log(err, 'User is not authenticated')
  }
    
  if (is_authenticated){
    // Time to make some authenticated API calls
    try {
      await API.graphql({
        query: createStock,
        variables: {
          input: {
            id: 'xxx',
            stockValue: 100
          }
        },
        authMode: 'AMAZON_COGNITO_USER_POOLS'
      })
    } catch (err) {
      console.log(err)
    }
  }
  
  return {
    props: { // will be passed to the page component as props
      authenticated: is_authenticated
    }, 
  }
}

# debug log

[DEBUG] 00:55.63 AuthClass - Succeed to get the user session 
CognitoUserSession {idToken: CognitoIdToken, refreshToken: CognitoRefreshToken, accessToken: CognitoAccessToken, clockDrift: 0}

accessToken: CognitoAccessToken

jwtToken: "eyJraWQiOiJiODBwXUzI1NiJ9.pc3MiOiJodHRwczpcL1wvY29nbml..."

idToken: CognitoIdToken

    "jwtToken": "eyJraWQiOiJudjBvSVFiRVd0Y0pocWw4bjU...-Gsw"

**Comment by weisisheng** [comment]
Separately, I worked back thru the next.js example on the amplify site and it works.

**Comment by nadetastic** [comment]
@weisisheng Are you logged in on the client before making the Server Side call?

The way SSR with Amplify Auth works is you would need to get a session on the client side first, then when making a call to the server (with `getServerSideProps()`) the session information would be sent and accessible on `req` when using `withSSRContext({req})`. However, if you do not have a session on the client, then there will not be a valid session on accessible on `req` either.

**Comment by weisisheng** [comment]
Noted. Will try your advice.

**Comment by weisisheng** [comment]
> @weisisheng Are you logged in on the client before making the Server Side call?
> 
> The way SSR with Amplify Auth works is you would need to get a session on the client side first, then when making a call to the server (with `getServerSideProps()`) the session information would be sent and accessible on `req` when using `withSSRContext({req})`. However, if you do not have a session on the client, then there will not be a valid session on accessible on `req` either.

Perhaps I don't understand the client session.  If I am logged in using cognito on the main page and then navigate to the page I am attempting to use SSR on, I was under the impression withSSRContext() makes a complete copy of the existing in-session user credentials for server side auth use.  What am I missing?

**Comment by nadetastic** [comment]
@weisisheng sorry for the delay, following up here - what you have explained is currently how it works. withSSRContext() will pass the client side credentials to the server via cookies which are the accesses via the request object.
