### ISSUE TITLE
amazon-cognito-identity-js not able to link to StorageHelper-rn

### ISSUE THREAD

**Issue by brucem1976** [aws-amplify/amplify-js#11226]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Not applicable

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line

 System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M2
    Memory: 549.02 MB / 24.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Brave Browser: 111.1.49.132
    Chrome: 112.0.5615.49
    Safari: 16.2
  npmPackages:
    @babel/core: ^7.20.0 => 7.21.4 
    @react-native-async-storage/async-storage: 1.17.11 => 1.17.11 
    @react-navigation/native: ^6.1.6 => 6.1.6 
    @react-navigation/native-stack: ^6.9.12 => 6.9.12 
    @types/react: ~18.0.14 => 18.0.31 
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: ^6.2.0 => 6.2.0 
    axios: ^1.3.5 => 1.3.5 
    expo: ~48.0.9 => 48.0.9 
    expo-device: ~5.2.1 => 5.2.1 
    expo-notifications: ~0.18.1 => 0.18.1 
    expo-status-bar: ~1.4.4 => 1.4.4 
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-safe-area-context: 4.5.0 => 4.5.0 
    react-native-screens: ~3.20.0 => 3.20.0 
    typescript: ^4.9.4 => 4.9.5 
    yup: ^1.0.2 => 1.0.2 
  npmGlobalPackages:
    aws-cdk: 2.73.0
    corepack: 0.10.0
    eas-cli: 3.9.0
    expo-cli: 6.3.2
    jest: 29.3.1
    npm: 8.15.0
    ts-node: 10.9.1
    typescript: 4.8.4
    yarn: 1.22.19

```

</details>

### Describe the bug

Although there is a `StorageHelper-rn` js file to allow for local storage of tokens on React Native for `amazon-cognito-identity-js`, it is never imported anywhere, only the non React Native version, as follows in `CognitoUserPool.js`:
`import StorageHelper from './StorageHelper';`
then used as:
`this.storage = data.Storage || new StorageHelper().getStorage();`

There needs to be a way to also bring in the React Native version, perhaps something like:
```
import StorageHelper from './StorageHelper';
import StorageHelperRn from './StorageHelper-rn';
...
this.storage = data.Storage || isReactNative ? new StorageHelperRn().getStorage() : new StorageHelper().getStorage();
```

### Expected behavior

It should be possible to programatically select the react native storage helper for the UserPool.

### Reproduction steps

Attempt to use `StorageHelper-rn` in `UserPool.js`

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by brucem1976** [comment]
@tannerabread so `amazon-cognito-identity-js` is the AWS recommended library for frontend access to Cognito. Amplify is one was to achieve this, but there are many other ways to integrate cognito. Seeing `amazon-cognito-identity-js` is now officially maintained as part of amplify, it makes sense to keep it usable beyond just Amplify as well, so that any updates to it are applicable regardless of how it is being used.

**Comment by tannerabread** [comment]
Understood. Let me discuss this with the team this week and get back to you

**Comment by tannerabread** [comment]
Hi @brucem1976 after some discussions I have marked this as a bug and someone will look into this deeper

**Comment by brucem1976** [comment]
> Hi @brucem1976 after some discussions I have marked this as a bug and someone will look into this deeper

@tannerabread has this progressed at all?

**Comment by nadetastic** [comment]
Hi @brucem1976 @carterjc we are still working determining the best path forward to achieve this, and cannot provide an ETA/updates quite yet. However, I'll provide an update for you all, as soon as I have one.

**Comment by HuiSF** [comment]
I believe `StorageHelper-rn.js` is used in a react-native environment per:

https://github.com/aws-amplify/amplify-js/blob/7762f1a7076e622ec354c24539a3b57ce3ec4290/packages/amazon-cognito-identity-js/package.json#L52-L55

With this configuration you should not need to instantiate the react-native version of `StorageHelper` and manually configure the storage mechanism. 

You can verify this by inspect the async storage of your react-native app, it should contain the tokens after signing in a user.

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
