### ISSUE TITLE
What is Auth.currentUser()? Why not documented?

### ISSUE THREAD

**Issue by wzup** [aws-amplify/amplify-js#1123]
#### Do you want to request a feature or report a bug?

Bug

#### What is the current behavior?

Nobody knows. No any info in docs

#### What is the expected behavior?

At least some info in docs

#### Issue
Here is your code. `Auth` class uses [Auth.currentUser()](https://github.com/aws/aws-amplify/blob/1c0073b220ed8273392ff0fa4088cc8b6b9d6537/packages/aws-amplify-react/src/Auth/AuthStateWrapper.jsx#L46)

```javascript
    checkUser() {
        return Auth.currentUser()
            .then(user => {
                const state = user? 'signedIn' : 'signIn';
                this.handleStateChange(state, user)
            })
            .catch(err => logger.error(err));
    }
```

Now here is your api for `Auth` class https://aws.github.io/aws-amplify/api/classes/authclass.html
WHere is `Auth.currentUser()`?
How can you use it, it's not documented
What does it do? What does it return?
Why do you hide it?

**Comment by mlabieniec** [comment]
@wzup thanks for the feedback and apologies for the confusion. We are working on revamping our docs as well as getting the API docs (which are auto-generated) updated with each build. Also, we are working on a revamp on the Auth class, it's been through a lot and has some confusing methods. We have a plan on cleaning this up and will have an update with fixes to the parts that have been vocally confusing to customers. This method is part of the HOCs in react, it does look like it's deprecated and needs to be remove apologies for the confusion and thanks for pointing it out.

**Comment by wzup** [comment]
@mlabieniec 

But which one of those to use instead? https://aws.github.io/aws-amplify/api/classes/authclass.html

The goal is initially on app bootstrap to check if a user is authenticated or not. Forward a user to personal area or display a Login screen.

`Auth.currentUser()` did exactly that I guess. Why do you deprecate it? There are no alternatives currently

**Comment by jordanranz** [comment]
Hi @wzup, there is a method to get the current authenticated user:
https://aws-amplify.github.io/amplify-js/api/classes/authclass.html#currentauthenticateduser

If this returns success, you can redirect to their personal area.
If the returns a failure, you can display a Login screen.

I am going to close this issue for now. Please reopen and let us know if you are still having trouble.
