### ISSUE TITLE
App store REQUIRES displaying user's name when using Apple federated sign in. Amplify does not provide the Apple user's name in the Auth.currentAuthenticatedUser() request

### ISSUE THREAD

**Issue by justinjaeger** [aws-amplify/amplify-js#11231]
### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

16.15.1

### Amplify CLI Version

10.0.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

When doing federated signing, the app store will require you make Apple oauth an option. I've done this successfully, but they also require that if you are asking for a user's name, you automatically use the name from the response of signing in with Apple.

`Auth.currentAuthenticatedUser()` does not return the Apple user's name.

I'm submitting this as a bug because it prevents me from uploading from the app store so long as my users are asked to enter their name.

Is it possible for Amplify to set the apple user's name so that it appears in the `Auth.currentAuthenticatedUser()` response?

### Expected behavior

Expected a "name" field to be returned on `Auth.currentAuthenticatedUser()` after user signs in with Apple

### Reproduction steps

...

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
Hey @justinjaeger :wave: thanks for raising this! I've transferred this over to our amplify-js repo for better assistance with the library!

**Comment by nadetastic** [comment]
Hi @justinjaeger thanks for opening this issue.

Could you provide some additional info on the requirement to "...automatically use the name from the response of signing in with Apple"?

**Comment by nadetastic** [comment]
I'll go ahead and close/merge this issue with #10182 as they are discussing the same issue, in order to track this in a central place.

Thanks @justinjaeger!
