### ISSUE TITLE
Q: What Auth method to use after confirmSignUp method?

### ISSUE THREAD

**Issue by wzup** [aws-amplify/amplify-js#1124]
### Do you want to request a feature or report a bug?

Question

### What is the current behavior?

Nobody knows, it's not documented

### What is the expected behavior?

Seamless login. After confirmation a user is logged in smoothly, no additional login screen required.

```javascript
Auth.confirmSignUp(username, confirmationCode)    
    // data is merely "SUCCSESS"
    .then( data => {
        return Auth.currentUserPoolUser( ); ??
        return Auth.currentAuthenticatedUser( ); ??
        return Auth.currentcredentials( ); ??
        return Auth.currentSession( ); ??
        return Auth.currentUserCredentials( ); ??
        return Auth.currentUserInfo( ); ??
        return Auth.currentUserInfo( ); ??
    } )
    .then( user => {
        // I need The CognitoUser object here with jwsToken 
    } ) 

```

"aws-amplify": "^0.3.3",
Chrome Version 67.0.3396.87 (Official Build) (64-bit)

**Comment by powerful23** [comment]
After confirmation you need to jump back to your sign in page and ask users to sign in with `Auth.signIn()`

**Comment by j0b0sapi3n** [comment]
Was this ever figured out? I want to automatically log a user in after they've confirmed their sign up, instead of having them go back to sign in which is unnecessary friction for a user sign up flow. Can't seem to find any additional info about this elsewhere.

**Comment by powerful23** [comment]
@j0b0sapi3n you can achieve this by directly calling `Auth.signIn()` when confirming sign up succeeded. But it's not available by using aws-amplify-react by now.

**Comment by mlabieniec** [comment]
There is a feature-request open for this:
https://github.com/aws-amplify/amplify-js/issues/991
