### ISSUE TITLE
AWS Amplify function Auth.signIn(username, password, {"metadataKey": "metadataKey1"}) doesnt send client metadata to cognito

### ISSUE THREAD

**Issue by aditya-passbird** [aws-amplify/amplify-js#11256]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I have tried sending the custom client metadat when user SignsIN but it never sends metadata to the cognito lambda.

### Expected behavior

the Auth.SignIn(username, password, {"clientmetadatakey": "clientMetadataKey1"} should send clientMetadataKey to the pre token generation lambda while it signs in.

### Reproduction steps

use auth.SignIn(username, password, clientmetadata) to signin User. 
Check the clientmetadata in pre token generation lambda

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello, @aditya-passbird 👋 and thanks for opening this issue.  As for the problem you're experiencing with the Cognito Lambda missing the client metadata, can you see if changing the syntax for the passed in parameter to the following fixes this: 
```
Auth.signIn(username, password, {
    metadata: {
        metaDataKey: `metaDataValue`
    }
})
```

Also, are you receiving any errors when you're trying to make these sign in requests?

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
