### ISSUE TITLE
Data constraint issue between amplify datastore and dynamo DB

### ISSUE THREAD

**Issue by kaiznanji** [aws-amplify/amplify-js#11254]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

DataStore

### Amplify Categories

storage

### Environment information

<details>

```
# Put output below this line

  System:
    OS: macOS 11.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.02 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
    Watchman: 2023.04.03.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 112.0.5615.49
    Firefox: 88.0
    Safari: 14.1
  npmPackages:
    @aws-sdk/client-cognito-identity-provider: ^3.312.0 => 3.312.0 
    @aws-sdk/credential-providers: ^3.312.0 => 3.312.0 
    @date-io/dayjs: ^2.16.0 => 2.16.0 
    @emotion/react: ^11.10.5 => 11.10.5 
    @emotion/styled: ^11.10.5 => 11.10.5 
    @mapbox/mapbox-gl-geocoder: ^5.0.1 => 5.0.1 
    @mapbox/mapbox-gl-style-spec:  13.28.0 
    @mui/icons-material: ^5.11.0 => 5.11.0 
    @mui/material: ^5.11.6 => 5.11.6 
    @mui/system: ^5.11.7 => 5.11.7 
    @mui/x-date-pickers: ^5.0.20 => 5.0.20 
    @reduxjs/toolkit: ^1.9.2 => 1.9.2 
    @reduxjs/toolkit-query:  1.0.0 
    @reduxjs/toolkit-query-react:  1.0.0 
    @testing-library/jest-dom: ^5.16.5 => 5.16.5 
    @testing-library/react: ^13.4.0 => 13.4.0 
    @testing-library/user-event: ^13.5.0 => 13.5.0 
    aws-amplify: ^5.0.25 => 5.0.25 
    aws-sdk: ^2.1358.0 => 2.1358.0 
    dayjs: ^1.11.7 => 1.11.7 
    mapbox-gl: ^2.12.1 => 2.12.1 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    react-hook-form: ^7.43.9 => 7.43.9 
    react-material-ui-carousel: ^3.4.2 => 3.4.2 
    react-redux: ^8.0.5 => 8.0.5 
    react-router-dom: ^6.8.0 => 6.8.0 
    react-scripts: 5.0.1 => 5.0.1 
    recharts: ^2.4.3 => 2.4.3 
    redux: ^4.2.1 => 4.2.1 
    url: ^0.11.0 => 0.11.0 (0.10.3)
    web-vitals: ^2.1.4 => 2.1.4 
    webpack-cli: ^5.0.1 => 5.0.1 
  npmGlobalPackages:
    @aws-amplify/cli: 11.0.3
    create-react-app: 5.0.1
    npm: 9.5.1
    yarn: 1.22.10

```

</details>

### Describe the bug

I am receiving a data constraint error when I change values in an object in my User table in DataStore. When I try and change values directly in DynamoDB it works. I am assuming there is an issue in the connection between these DataStore and DynamoDB. Having troubles recreating this error but it seems like my DataStore is just bugged out. I have tried deleting the table and recreating it, as well as removing DataStore from amplify but nothing seems to work. Even when I create a new table and try and change the any field in Amplify Studio content tab I get the error. Here are some screenshots.

<img width="1030" alt="Screen Shot 2023-04-16 at 1 35 00 AM" src="https://user-images.githubusercontent.com/76850669/232273183-f2d7322c-9574-4dd1-b777-200374a3f21a.png">

<img width="640" alt="Screen Shot 2023-04-16 at 1 37 52 AM" src="https://user-images.githubusercontent.com/76850669/232273270-5be4c954-7cf1-43b1-bfcc-55fd3096b062.png">

I'm also getting a similar issues when I try and query from the table in my code.  Users is imported from my models and DataStore is taken from 'aws-amplify'. 

<img width="751" alt="Screen Shot 2023-04-16 at 1 36 52 AM" src="https://user-images.githubusercontent.com/76850669/232273246-0e21e84a-f2c9-495a-8071-805fc31a2bb1.png">

<img width="1788" alt="Screen Shot 2023-04-16 at 1 36 07 AM" src="https://user-images.githubusercontent.com/76850669/232273216-f9e4a411-effc-45ef-8eb9-dabdde7977f4.png">

### Expected behavior

I should be able to change values directly in Amplify Studio table content. I should also not receive data constraint issues when I try to query from the table.

### Reproduction steps

Unable to recreate this error. Wondering if there is a way to reset DataStore's cached data or as a whole since it seems like an internal bug.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by dpilch** [comment]
Hi @kaiznanji, I wasn't able to reproduce this behavior. Could you provide the full `schema.graphql` contents?

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
