### ISSUE TITLE
Setting Authorization header by default

### ISSUE THREAD

**Issue by EgidioCaprino** [aws-amplify/amplify-js#1127]
## Do you want to request a feature or report a bug?
Feature.

## What is the current behavior?
When setting up Amplify with `Amplify.configure` I'm not setting `API.graphql_headers`. When calling `API.graphql` I get a `401` unauthorized error, even though the user is authenticated. I'm using `aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS'`.

If I manually set
```
graphql_headers: async () => {
  const { idToken } = await Amplify.Auth.currentSession();
  return { Authorization: idToken.jwtToken };
},
```
then `API.graphql` works fine.

## What is the expected behavior?
I would expect `Amplify` to set the `Authorization` header for me.

## Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
```
aws-amplify-react-native@0.2.17
aws-amplify@0.4.6
```

**Comment by wjramos** [comment]
Is this something that was ever addressed?
