### ISSUE TITLE
DataStore.observe receives UPDATE instead of an INSERT event if the new model was created while DataStore was stopped

### ISSUE THREAD

**Issue by guy-a** [aws-amplify/amplify-js#11288]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

DataStore

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

Normal:
Client A - create a new model
Client B - Receives an INSERT with the new model

During stoppage:
Client B - DataStore.stop()
Client A - create a new model
Client B - DataStore.start()
Client B - Receive an UPDATE with the new model

### Expected behavior

When a new model arrive to the client the event should always be INSERT

### Reproduction steps

.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by david-mcafee** [comment]
@guy-a - I attempted to reproduce this, but was not able. Can you please include a few more details to repro the issue? Specifically, 1) what browsers you are using for clients A and B, 2) what version of Amplify you are using, and 3) a code snippet showing how / where you are calling both `DataStore.observe`, as well as `DataStore.start` and `DataStore.stop`? Thank you!

**Comment by guy-a** [comment]
Hi @david-mcafee, thank you for the reply.
I'm using some overridden resolvers so maybe that's part of it.
I will try to find the time to create a new project and reproduce the issue.

**Comment by david-mcafee** [comment]
Thank you, @guy-a! Once you have a working repro, let us know!
