### ISSUE TITLE
Attempted import error: 'Cache' is not exported from '@aws-amplify/cache' (imported as 'Cache').

### ISSUE THREAD

**Issue by pergunt** [aws-amplify/amplify-js#11291]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

REST API

### Environment information

<details>

```
System:
    OS: macOS 12.6.3
    CPU: (8) arm64 Apple M1 Pro
    Memory: 119.95 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Safari: 15.6.1
  npmPackages:
    @ant-design/icons: 4.7.0 => 4.7.0 (5.0.1)
    @ant-design/pro-layout: 7.10.3 => 7.10.3 
    @aws-amplify/pubsub: 4.3.2 => 4.3.2 (5.1.12)
    @babel/eslint-parser: 7.16.3 => 7.16.3 (7.21.3)
    @babel/preset-env: 7.16.0 => 7.16.0 (7.21.4)
    @babel/preset-react: 7.16.0 => 7.16.0 (7.18.6)
    @craco/craco: 6.4.0 => 6.4.0 
    @react-pdf-viewer/core: 3.6.0 => 3.6.0 
    @react-pdf-viewer/page-navigation: 3.6.0 => 3.6.0 
    @reduxjs/toolkit: 1.7.1 => 1.7.1 
    @reduxjs/toolkit-query:  1.0.0 
    @reduxjs/toolkit-query-react:  1.0.0 
    @trulioo/globalgateway-image-capture-sdk: ^1.1.16 => 1.1.16 
    @types/flat: 5.0.2 => 5.0.2 
    @types/lodash: 4.14.176 => 4.14.176 
    @types/node: ^16.18.12 => 16.18.24 (18.16.0)
    @types/react: ^18.0.27 => 18.0.38 
    @types/react-dom: ^18.0.10 => 18.0.11 
    @types/react-highlight-words: 0.16.3 => 0.16.3 
    @types/react-redux: 7.1.20 => 7.1.20 (7.1.25)
    @types/react-router-dom: 5.3.2 => 5.3.2 
    @types/redux-logger: 3.0.9 => 3.0.9 
    @types/uuid: 8.3.1 => 8.3.1 
    amazon-cognito-identity-js: 5.2.4 => 5.2.4 (6.2.0, 5.2.8)
    antd: 5.4.5 => 5.4.5 
    aws-amplify: 5.1.3 => 5.1.3 
    buffer: 6.0.3 => 6.0.3 (4.9.2, 5.7.1)
    classnames: 2.3.1 => 2.3.1 (2.3.2)
    eslint-config-airbnb: 19.0.0 => 19.0.0 
    eslint-config-prettier: 8.3.0 => 8.3.0 
    flat: 5.0.2 => 5.0.2 
    generate-password: 1.7.0 => 1.7.0 
    lodash: 4.17.21 => 4.17.21 
    moment: 2.29.1 => 2.29.1 
    npm-run-all: 4.1.5 => 4.1.5 
    pdfjs-dist: 2.14.305 => 2.14.305 
    prettier: 2.8.3 => 2.8.3 
    process: 0.11.10 => 0.11.10 
    qrcode.react: 3.0.1 => 3.0.1 (3.1.0)
    query-string: 7.0.1 => 7.0.1 
    react: 17.0.2 => 17.0.2 (18.2.0)
    react-country-flag: 2.0.1 => 2.0.1 
    react-dom: 17.0.2 => 17.0.2 
    react-highlight-words: 0.16.0 => 0.16.0 
    react-intl: 6.0.5 => 6.0.5 
    react-jss: 10.8.2 => 10.8.2 
    react-phone-input-2: 2.13.9 => 2.13.9 
    react-redux: 7.2.6 => 7.2.6 
    react-router-dom: 5.1.2 => 5.1.2 
    react-scripts: 5.0.1 => 5.0.1 
    redux: 4.1.2 => 4.1.2 
    redux-logger: 3.0.6 => 3.0.6 
    redux-saga: 1.1.3 => 1.1.3 
    redux-saga/effects:  undefined ()
    redux-thunk: 2.4.0 => 2.4.0 (2.4.2)
    sst: 2.5.5 => 2.5.5 
    stream-browserify: 3.0.0 => 3.0.0 
    typescript: 4.1.2 => 4.1.2 
    uuid: 8.3.2 => 8.3.2 (3.4.0, 8.0.0, 9.0.0)
    web-vitals: ^2.1.3 => 2.1.4 
  npmGlobalPackages:
    corepack: 0.10.0
    npm: 6.14.8
    serverless: 2.67.0

```

</details>

### Describe the bug

# I have updated `aws-amplify` to v5.1.3 and got the following error
Attempted import error: 'Cache' is not exported from '@aws-amplify/cache' (imported as 'Cache').
ERROR in ./node_modules/@aws-amplify/api/lib-esm/API.js 22:17-22
export 'Cache' (imported as 'Cache') was not found in '@aws-amplify/cache' (possible exports: BrowserStorageCache, InMemoryCache, default)

webpack compiled with 1 error
No issues found.

```
node -v
v16.13.0
 npm -v
6.14.8

### Expected behavior

This error must dissapear

### Reproduction steps

1. install react-app with the deps described above
2. install "aws-amplify": "5.1.3",
3. start the app
4. looks in the terminal

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by nadetastic** [comment]
Hi @pergunt thank you for opening this issue.

I see you are trying to import Cache from `@aws-amplify/cache` - could you try importing from `aws-amplify` instead?

```js
import { Cache } from 'aws-amplify';
```

**Comment by pergunt** [comment]
@nadetastic But this import is defined in `node_modules`. Not in my code

**Comment by nadetastic** [comment]
Hi @pergunt - I'm going to go ahead and close out this issue. Let me know if you are still needed help.

Thanks!

**Comment by anandbundela-softdel** [comment]
@nadetastic 

I am using Angular 14, 

in my package.json i am using this

 "aws-amplify": "^4.3.42",
 "@aws-amplify/auth": "^4.6.13",
 "@aws-amplify/pubsub": "^5.0.11",
 "@aws-amplify/ui-angular": "^2.4.25",


./node_modules/@aws-amplify/api/lib-esm/API.js:190:17-22 - Error: export 'default' (imported as 'Cache') was not found in '@aws-amplify/cache' (possible exports: BrowserStorageCache, Cache, InMemoryCache)


Can you please help me with this?

Thanks
