### ISSUE TITLE
Make it configurable to refresh auth credentials earlier than after 50 minutes

### ISSUE THREAD

**Issue by damoberg** [aws-amplify/amplify-js#11294]
### Is this related to a new or existing framework?

React

### Is this related to a new or existing API?

Authentication using a Cognito UserPool and JWT tokens. The JWT token is added to the AppSync request headers for each request: (simplified)

```js
const amplifyConfig = {
  API: {
    graphql_headers: async () => ({
      Authorization: (await Auth.currentSession()).getIdToken().getJwtToken()
    })
  }
};
```

### Is this related to another service?

Cognito

### Describe the feature you'd like to request

When using the Amplify Auth library, we would like to request making the force refresh of JWT credentials to be configurable so that we can support shorter access token timeouts. We suggest adding this configuration to `Amplify.configure(...)`.

(Update: we have since learned that the referenced patch below is not involved in the refresh flows for JWT tokens. Keeping it in the ticket as a similar mechanism could potentially be implemented for JWT tokens)

In [4205](https://github.com/aws-amplify/amplify-js/pull/4205) a [hard coded configuration](https://github.com/aws-amplify/amplify-js/blob/main/packages/core/src/Credentials.ts#L25) was added to refresh credentials after 50 minutes, assuming the token availability is generally configured to 1 hour. We need to tweak this to allow for shorter timeouts, ex 5 min.

### Describe the solution you'd like

We'd like to be able to support using 5 minute access token credentials without risking that the credentials are being invalidated in flight. For example if the token expiry is at 4m 59s when using it to make a request, when the token is received in the API it could be expired depending on latency.

### Describe alternatives you've considered

An alternative could be to adjust the API to allow for expired tokens, ex if they are not expired with more than 15 seconds. That would require a custom authorizer which we are not able to add currently.

### Additional context

We are also curious to learn if there are other workarounds we can investigate.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by nadetastic** [comment]
Hi @damoberg thank you for opening this issue. It looks related to an existing issue https://github.com/aws-amplify/amplify-js/issues/2714 that is currently open as a feature request.

I'll go ahead and close this issue out in favor of tracking the request on #2714 

Thanks!
