### ISSUE TITLE
Change default Cognito Hosted UI in Amplify to use an website in mobile (desktop mode)

### ISSUE THREAD

**Issue by NarayaneRM** [aws-amplify/amplify-js#11293]
### Describe the bug

I have a responsive website (react js) that uses Cognito as Amplify Auth. The problem is that when the user made Sign In to my customized login page, he/she can't change from mobile mode to desktop mode without being redirected to Cognito Hosted UI. 

### Expected behavior

The user doesn't need to confirm login every time he/she changes the view from mobile mode to desktop mode or vice versa. Even if it is extremely necessary to ensure login, at least the user should be redirected to my own customized page.

### Confirming:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
    Memory: 4.04 GB / 15.75 GB
  Binaries:
    Node: 18.12.1 - c:\NodeJS\node.EXE
    npm: 9.4.2 - c:\NodeJS\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (111.0.1661.54)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @aws-amplify/auth: ^5.1.9 => 5.2.0 
    @aws-amplify/core: ^5.1.6 => 5.1.6 (5.1.5)
    @aws-amplify/ui-react: ^4.4.2 => 4.4.2
    @aws-amplify/ui-react-internal:  undefined ()
    @testing-library/jest-dom: ^5.16.5 => 5.16.5
    @testing-library/react: ^13.4.0 => 13.4.0
    @testing-library/user-event: ^13.5.0 => 13.5.0
    aws-amplify: ^5.0.22 => 5.0.22
    aws-sdk: ^2.1337.0 => 2.1337.0
    axios: ^1.3.5 => 1.3.5 (0.26.0)
    history: ^5.3.0 => 5.3.0
    jwt-decode: ^3.1.2 => 3.1.2
    react: ^18.2.0 => 18.2.0
    react-router-dom: ^6.8.1 => 6.8.1
    react-scripts: 5.0.1 => 5.0.1
    react-super-responsive-table: ^5.2.1 => 5.2.1
    react-table: ^7.8.0 => 7.8.0
    web-vitals: ^2.1.4 => 2.1.4
    zip: ^1.2.0 => 1.2.0
  npmGlobalPackages:
    @aws-amplify/cli: 10.7.1
    create-react-app: 5.0.1
    npm: 9.4.2

```

</details>

### Reproduction steps

1. Open the website login page in a mobile browser and click on the bottom: Sign In ("Entrar")
![1](https://user-images.githubusercontent.com/86672908/234080541-90efd2b0-475d-4f2c-af7c-2f919b1ace73.png)

2. You will be redirected to Google Login. Choose your account
![page 5 (360 × 800 px)](https://user-images.githubusercontent.com/86672908/234094534-95c33430-813f-475e-ba8f-0c3beff59218.png)

4. On the home page, click on 3 points in the left if you are an Android User 
![3](https://user-images.githubusercontent.com/86672908/234080713-ac297957-9bcb-4d48-8793-65b4f0e98d0e.png)

5.  Choose Desktop mode ("Para computador")
![4](https://user-images.githubusercontent.com/86672908/234080745-e494c05a-af70-405b-a607-f5abd9f353f2.png)

6. Now you are in the bug: you are by default redirected to the Cognito Hosted UI SignIn page
![5](https://user-images.githubusercontent.com/86672908/234080845-9af6799c-87a7-4ee8-915e-98c1e8b37b9e.png)

### aws-exports.js

```Javascript

const awsmobile = {
    "aws_project_region": "XXXXX",
    "aws_cognito_region": "XXXXX",
    "aws_user_pools_id": "XXXXX",
    "aws_user_pools_web_client_id": "XXXXX",
    "oauth": {
        "domain": "XXXXX",
        "scope": [
            "XXXXX"
        ],
        "redirectSignIn": "XXXXXXX",
        "redirectSignOut": "XXXXXX",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "XXXXXX"
    ],
    "aws_cognito_social_providers": [
        "XXXXXX"
    ],
    "aws_cognito_signup_attributes": [
        "XXXXXX"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "XXXXX"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "XXXXX"
    ],
    "aws_content_delivery_bucket": "XXXXX",
    "aws_content_delivery_bucket_region": "XXXXX",
    "aws_content_delivery_url": "XXXXX"
};


export default awsmobile;
```

### Additional information

Please, note that this is a problem similar to #2115 and #5027 and both issues used `urlopener` using dependencies in React Native to resolve. Maybe the solution to my bug is something similar but considering React (not React Native).

**Comment by tannerabread** [comment]
Hi @NarayaneRM does it only break when switching between the modes? Can you login if you start in desktop mode and then go through the auth flow?

**Comment by tannerabread** [comment]
@NarayaneRM I'm trying to set up a repro of this, can you provide some details on how you are setting up those private pages? 

From your environment it looks like you are using react-router for navigation, is that correct?

Or if you have a sample repo that I can clone to reproduce this that would be nice as well

**Comment by nadetastic** [comment]
Hi @NarayaneRM is you mobile/desktop versions of you app on different subdomains/domains? It sounds like when switching the modes, the current session becomes invalid for some reason. What happens when you go from mobile -> desktop -> back to mobile?

**Comment by cwomack** [comment]
@NarayaneRM, can you clarify if your mobile and desktop versions for your app/site are on different domains or subdomains?

**Comment by cwomack** [comment]
@NarayaneRM, just wanted to check in and see if you're still being impacted by this issue.  Are you able to confirm if you have different domains or subdomains for your mobile and desktop versions?

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
