### ISSUE TITLE
Automatic logout with Authenticator -  using on ReactJS app

### ISSUE THREAD

**Issue by PratimOlym** [aws-amplify/amplify-js#11302]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I am using the Amplify Authenticator component in a react app. Post authentication flow is completed, I can get the user object in the app component and it leads me to a protected route. On arriving at the protected page, and doing some UI interaction, the user is automatically logged out and I land back at login screen. I can see in the browser localstorage that all the cognito credentials are removed.

### index.js essential code (App wrapped with Authenticator.provider):
```js
ReactDOM.render(
  <React.StrictMode>
    <BrowserRouter>
      <AppContextProvider>
        <Authenticator.Provider>
        <Provider store={store}> 
          <App />
        </Provider> 
        </Authenticator.Provider>
      </AppContextProvider>
    </BrowserRouter>  
  </React.StrictMode>,
  document.getElementById("root")
);

```

### App.js essential codes (getting user and leading to protected route):
```js
function App() {
  const { user, signOut } = useAuthenticator((context) => [context.user]);

  useEffect(() => {
    console.log("amplify user is: ", user);
    if (user) {
      console.log("User is logged in");
      console.log("User is: ", user);
    }
  }, [user]);
 

  return (
  
    <div className="App">
      {showTopbar && (
        <header className="topbar">
          {/* Topbar content goes here */}
          <Topbar signOut={signOut}/>
        </header>
      )}
            
        <div className="home-container" style={homeContainerStyle}>
            <div className="content-container" >
              <Routes>
            <Route exact path="/" element={user?<Home/>:<LandingMain/>} />
              </Routes>
            </div>
          
        </div>
      
    </div>
    
  );
}
```

### Home Component (Visible in protected route):

```js
export default function Home() {

  const leftbarSelectedOptionId = 'stories';

  return (
    <div className="content">
      {leftbarSelectedOptionId === "stories" && <StoryListNew />}
    </div>
  );
}
```

### Expected behavior

The authentication should remain active until I explicitly signout using signOut function from userAuthenticator. 

### Reproduction steps

npm start (starts react app)

login in the Landing page. (Keep the localstorage visible to see it gets cognito credentials)

you land in home screen. Scroll down or click the three dots in the topbar.

You should be logged out and land back to the Landing page. (Ignore the sidebars in Landing page). Local storage cognito credentials are removed.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

I have edited some values to direct it to another cognito user pool I have manually created:

```js
const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:3b764224-3b65-4d8b-87dc-ebb84ba6dc59",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_JQ9p3ezZq",
    "aws_user_pools_web_client_id": "22thjn0hhd4stur8onh9a20nam",
    "oauth": {
        "domain": "testapp29a36ec4-29a36ec4-dev.auth.ap-south-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://localhost:3000/",
        "redirectSignOut": "https://localhost:3000/logout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;

```

### Additional information and screenshots

https://user-images.githubusercontent.com/89311328/234575106-a2effccd-b162-4132-9093-ab310f28c3e0.mp4

### package.json:
```json
{
  "name": "react-social",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@aws-amplify/ui-react": "^3.5.4",
    "@emotion/react": "^11.7.1",
    "@emotion/styled": "^11.6.0",
    "@fortawesome/free-solid-svg-icons": "^6.4.0",
    "@fortawesome/react-fontawesome": "^0.2.0",
    "@material-ui/core": "^4.11.3",
    "@material-ui/icons": "^4.11.2",
    "@mui/icons-material": "^5.4.2",
    "@mui/lab": "^5.0.0-alpha.70",
    "@mui/material": "^5.4.0",
    "@reduxjs/toolkit": "^1.8.5",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "antd": "^5.3.3",
    "axios": "^0.21.1",
    "bootstrap": "^5.1.3",
    "dotenv": "^16.0.2",
    "history": "^5.3.0",
    "http-proxy-middleware": "^2.0.6",
    "jwt-decode": "^3.1.2",
    "path": "^0.12.7",
    "query-string": "^8.1.0",
    "react": "^17.0.2",
    "react-bootstrap": "^2.1.2",
    "react-dom": "^17.0.2",
    "react-google-login": "^5.2.2",
    "react-icons": "^4.4.0",
    "react-redux": "^8.0.2",
    "react-router-dom": "^6.3.0",
    "react-scripts": "^5.0.1",
    "styled-components": "^5.3.5",
    "timeago.js": "^4.0.2",
    "web-vitals": "^1.0.1"
  },
  "scripts": {
    "dev": "react-scripts start",
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "heroku-postbuild": "npm run build"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browser": {
    "crypto": false,
    "fs": false,
    "path": false,
    "os": false,
    "net": false,
    "stream": false,
    "tls": false
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
}
```

**Comment by PratimOlym** [comment]
Hi @tannerabread I could check that aws-amplify is part of node-modules in my project, despite it being missing in package.json. Please check the attached image.

![Screenshot_20230427_162149](https://user-images.githubusercontent.com/89311328/234842691-55598f37-1844-47d0-8534-da2c79bce844.png)

I am configuring Amplify in a file named AmplifyLogin. Sharing the file here for your ref. (Please change the ext to JSX.)
[AmplifyLogin.txt](https://github.com/aws-amplify/amplify-js/files/11342668/AmplifyLogin.txt)


FYI - In my project, I am using just auth feature of Amplify. Also, I am configuring aws-exports.js file manually to direct to user pool I have setup in Cognito, which is working fine. I am not taking help of amplify cli or amplify studio for auth setup.

**Comment by cwomack** [comment]
@PratimOlym, thanks for the additional context and confirmation that you've got the `aws-amplify` dependency installed.  Just to confirm, what is your app's _entry point_?  Is it the **AmplifyLogin.jsx** file you described above?  If not, then can you try calling the `Amplify.configure()` in your **index.js** file?

**Comment by cwomack** [comment]
@PratimOlym can you also try running `npm install aws-amplify` (as seen [here](https://ui.docs.amplify.aws/react/connected-components/authenticator#:~:text=npm%20install%20%40aws,Copy) in the Authenticator docs) so we can rule out that needed dependency? 

In reviewing the above comments and dependencies again, it appears you may still be missing this.  Even through the ui-package brings in the `node_modules` that you captured in your screenshot, you'd still need `aws-amplify` for authentication to work properly.

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
