### ISSUE TITLE
Not getting Federated Access Token and Refresh Token when calling function Auth.currentSession()

### ISSUE THREAD

**Issue by rajkinkhabwala** [aws-amplify/amplify-js#11321]
### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

So this Auth.currentSession() says that it gives out a new Cognito User session to void any error with the APIs. and I also saw that Auth.currentUserSession() also does the same thing and also refreshes the Federated Tokens.

So What I am describing is sending the federated tokens which are the latest in Cognito as Cognito mentions that it stores all of those but does not give them out to the user.

### Describe the solution you'd like

Please send the latest token to the attribute which we can map in the Cognito to google.

### Describe alternatives you've considered

I am searching for a alternative solution.

### Additional context

I am trying to use it will calendar API. but I am not able as token gets expire and my requests get failed.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by rajkinkhabwala** [comment]
What kind of logs you are expecting me to report? But still here are some:

Output of `(user.getSignInUserSession())?.getIdToken().payload` 

`
{
    "at_hash": "j6_cRKvC1Q6r4ZTRNRgnFA",
    "sub": "",
    "cognito:groups": [
        ""
    ],
    "email_verified": ,
    "iss": "https://cognito-idp.us-west-2.amazonaws.com/us-west-2_xyzy",
    "cognito:username": "",
    "origin_jti": "",
    "aud": "79k8bpt4c7cpf0imsmhd1sjcoi",
    "identities": [
        {
            "userId": "",
            "providerName": "",
            "providerType": "",
            "issuer": null,
            "primary": "",
            "dateCreated": ""
        }
    ],
    "token_use": "id",
    "auth_time": 1683013865,
    "exp": ,
    "iat": ,
    "jti": "",
    "email": ""
}
`
This ID Token.

`
{
    "sub": "",
    "cognito:groups": [
        ""
    ],
    "iss": "https://cognito-idp.us-west-2.amazonaws.com/us-west-2_",
    "version": 2,
    "client_id": "",
    "origin_jti": "",
    "token_use": "access",
    "scope": "aws.cognito.signin.user.admin phone openid profile email",
    "auth_time": ,
    "exp": ,
    "iat": ,
    "jti": "",
    "username": ""
}
`
This is the access Token.

So my question is I have seen Supabase that gives me a provider token and also a Supabase token if I configure my application with Supabase.

But there is nothing like that in Cognito.

So now there is one option in which I map Google access token in custom attribute but it only updates when I sign in or signup to a application. But what about a situation in which I want to use the token in Google API and when the token from the custom attribute expires. it gives me an error.

But What I have read from a guide in AWS Amplify docs. It says it auto-refreshes the provider token in Cognito but the custom-mapped attribute never updates. which does not make sense to me. Also, I found a function in Credential Class in which it says to update the federatedToken (function name is `Auth.Credentials.refreshFederatedToken()` But I can't find any document where it states how to use it.

Is it possible to have the token given to me in a function called `Auth.currentUserSession()` or Similar of that kind.

**Comment by nadetastic** [comment]
Hi @rajkinkhabwala

It sounds like you are trying to get the Token from the provide (ex Google) sent through Cognito to your client - let me know if this is accurate. If so, cognito doesn't currently support this unfortunately, however there is a different flow that you can use where you get the tokens directly from Google back to your client, then use `Auth.federatedSignIn` to authorize with Cognito. More on this [here](https://docs.amplify.aws/lib/auth/advanced/q/platform/js/#identity-pool-federation).

Let me know if this is correct.

May be similar to #6236

**Comment by rajkinkhabwala** [comment]
Hey,

I tried implementing the same code but I did not understand it.

```javascript
import { Auth } from 'aws-amplify';

// To derive necessary data from the provider
const {
  token, // the token you get from the provider
  domainOrProviderName, // Either the domain of the provider(e.g. accounts.your-openid-provider.com) or the provider name, for now the library only supports 'google', 'facebook', 'amazon', 'developer'
  expiresIn, // the time in ms which describes how long the token could live
  user,  // the user object you defined, e.g. { username, email, phone_number }
  identity_id // Optional, the identity id specified by the provider
} = getFromProvider(); // arbitrary function

Auth.federatedSignIn(
  domain,
  {
    token,
    identity_id, // Optional
    expires_at: expiresIn * 1000 + new Date().getTime() // the expiration timestamp
  },
  user
).then(cred => {
  // If success, you will get the AWS credentials
  console.log(cred);
  return Auth.currentAuthenticatedUser();
}).then(user => {
  // If success, the user object you passed in Auth.federatedSignIn
  console.log(user);
}).catch(e => {
  console.log(e)
});
```

Just for your reference which code I am talking about, I have pasted it above.
I am not able to understand where I can getFromProvider(). Right now I am assuming I have to make it myself.

Also, what is the domain here?
Also, I am assuming this will trigger in a scenario of the provider token being expired which I have stored in my local store from Cognito attributes.

**Comment by nadetastic** [comment]
@rajkinkhabwala - you're correct, `getFromProvider()` is a function that you would define yourself, while domain would be the provider.

Since you mentioned Google in the original issue, here's [a link to how this would look like with google](https://docs.amplify.aws/lib/auth/advanced/q/platform/js/#google-sign-in-react) as well as the relevant sample code:

```js
import React, { useEffect } from 'react';
import jwt from 'jwt-decode';
import { Auth } from 'aws-amplify';

// A function that you define to initialize Google client and get the login screen
const SignInWithGoogle = () => {
  useEffect(() => {
  // Check for an existing Google client initialization
    if (!window.google && !window.google?.accounts) createScript();
  }, []);

  // Load the Google client
  const createScript = () => {
    const script = document.createElement('script');
    script.src = 'https://accounts.google.com/gsi/client';
    script.async = true;
    script.defer = true;
    script.onload = initGsi;
    document.body.appendChild(script);
  }

  // Initialize Google client and render Google button
  const initGsi = () => {
    if (window.google && window.google?.accounts) {
      window.google.accounts.id.initialize({
        client_id: process.env.GOOGLE_CLIENT_ID,
        callback: (response: any) => {
          getAWSCredentials(response.credential)
        },
      });
      window.google.accounts.id.renderButton(
        document.getElementById("googleSignInButton"),
        { theme: "outline", size: "large" }
      );
    }
  }

  // Exchange Google token for temporary AWS credentials
  const getAWSCredentials = async (credential: string) => {
    const token = jwt(credential) as any;
    const user = {
      email: token.email,
      name: token.name
    };      
    await Auth.federatedSignIn(
      'google',
      { token: credential, expires_at: token.exp },
      user
    );
  }

  return (
    <div>
      <button id="googleSignInButton"/>
    </div>
  );
}```

**Comment by nadetastic** [comment]
@rajkinkhabwala following up here. Let me know if you still have questions - otherwise I'll mark this issue as resolved.

Thanks!
