### ISSUE TITLE
Add option to redirect to federated *signup* page instead of *login*

### ISSUE THREAD

**Issue by jchorl** [aws-amplify/amplify-js#11336]
### Is this related to a new or existing framework?

Web Components

### Is this related to a new or existing API?

Authentication

### Is this related to another service?

Cognito

### Describe the feature you'd like to request

Cognito has a separate `/signup` endpoint, described here: https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-userpools-server-contract-reference.html

It would be awesome if the client libs allowed you to redirect to the signup page. This would enable e.g. "Signup" buttons on a site that doesn't use social login.

### Describe the solution you'd like

I believe we could add a field to [`FederatedSignInOptions`](https://github.com/aws-amplify/amplify-js/blob/d53501ec542258611546d030e24e7d29854b103a/packages/auth/src/types/Auth.ts#L62) (perhaps `is_signup`?). 

That would eventually get passed to [`oauthSignIn`](https://github.com/aws-amplify/amplify-js/blob/d53501ec542258611546d030e24e7d29854b103a/packages/auth/src/OAuth/OAuth.ts#L105) and impact the URL.

### Describe alternatives you've considered

Unfortunately it doesn't look like `oauth2/authorize` can accept a param to tell it whether to redirect to login or signup. If there is some way to hint cognito which page you want, the amplify client implementation would probably just leverage that.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by nadetastic** [comment]
Hi @jchorl thank you for opening this issue. Since its currently possible to get to the sign up view of the hosted ui after using `Auth.federatedSignIn`, I'm currently discussing this with the team on how to best address this - however it may not be prioritized any time soon. I'll follow up soon with any new information. Thanks!

**Comment by nadetastic** [comment]
With the recent release of v6, I will consolidate this feature request into the related feature request at #12282 - which requests the same thing while providing additional context and is more recent.
