### ISSUE TITLE
Subscription not working with filter

### ISSUE THREAD

**Issue by manifiserv** [aws-amplify/amplify-js#11337]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

```
Nothing

```

</details>

### Describe the bug

I created the @model in graphql and it created the mutation and subcriptions. Also I created the custom subscription based on my requirements.

The problem is default subscription is working with filter and without filter. But my custom subscription is not working with filter but it's working without filter.

Please help me to resolve this issue.

The above scenario is only working in local env which is runningamplify push cli command.

After merged the local code into git branch, In the Amplify Hosting build is not working for all subscriptions with filter(default and custom) but it's working without filter.

Custom subscription in schema.graphql:
```
type MyEvents
  @model(timestamps: null)
  @auth(rules: [{allow: private}])
  {
  event_id: ID! @primaryKey(sortKeyFields: ["version"])
  version: Int!
  status: String!
  merchant_id: Int! 
  event_name: String 
  event_type: String
}

input MyEventsFilterInput{
  status: CustomSubscriptionStringInput
  merchant_id: CustomSubscriptionIntInput
  event_type: CustomSubscriptionStringInput
}

type Subscription {
  onCreateCustomMyEvents(filter: MyEventsFilterInput): MyEvents
    @aws_subscribe(mutations: ["createMyEvents"])
}
```
Subscriptions.js:
```
My Custom Subscription:
export const onCreateCustomMyEvents= /* GraphQL */ `
  subscription OnCreateCustomMyEvents($filter: MyEventsFilterInput) {
    onCreateCustomMyEvents(filter: $filter) {
      event_id
      version
      status
      merchant_id
      event_type
    }
  }
`;
Default Subscription:
export const onCreateMyEvents = /* GraphQL */ `
  subscription OnCreateMyEvents(
    $filter: ModelSubscriptionMyEventsFilterInput
  ) {
    onCreateMmpUserEvents(filter: $filter) {
      event_id
      version
      status
      merchant_id
      event_type
    }
  }
`;
```

### Expected behavior

Please help me to resolve subscription with filter amplify cli buld and amplify hosting build.

### Reproduction steps

Nothing

### Code Snippet

```javascript
// Put your code below this line.

```
Graphql code

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by manifiserv** [comment]
@aws 
please help me to resolve the issue.

**Comment by manifiserv** [comment]
@chrisbonifacio 

Now my major issue is not custom subscription..
I need to resolve the default subscription is not working when build the amplify hosting to env.

I found the reason why the filter is not coming to default subscription in amplify hosting CI/CD.

This is my model:
```
type MyEvents
  @model(timestamps: null)
  @auth(rules: [{allow: private}])
```
When i do the amplify push command(from my terminal) to the particular env, the filter is coming in default subscription.
But when i use the amplify CI/CD build command like the ```amplifyPush --simple``` then the filter is not coming to the default subscription.

Please help me to what is the best command to use in CI/CD build to get the filter in subscription.

**Comment by manifiserv** [comment]
@chrisbonifacio 
9.2.1

My local amplify version is 10.6.0 and the CI/CD amplify version is 9.2.1..

is this may be the issue?

**Comment by manifiserv** [comment]
@aws-amplify-ops 

Please help me to resolve this issue

**Comment by manifiserv** [comment]
I changed to this version 10.6.0 in amplify ci/cd but i am getting below error:
2023-05-05T17:43:22.769Z [WARNING]: - Initializing your environment: develop
2023-05-05T17:43:24.274Z [WARNING]: - Building resource api/merchantportal
2023-05-05T17:43:24.275Z [WARNING]: - Building resource auth/merchantportalnonpro1d675c4e
2023-05-05T17:43:24.276Z [WARNING]: - Building resource storage/merchantuseractions
2023-05-05T17:43:24.301Z [WARNING]: - Building resource storage/mmpeventhistory
2023-05-05T17:43:24.316Z [WARNING]: - Building resource storage/mmpmerchantfavorite
2023-05-05T17:43:24.327Z [WARNING]: ✔ Initialized provider successfully.
2023-05-05T17:43:25.503Z [WARNING]: ✖ There was an error initializing your environment.
2023-05-05T17:43:25.503Z [INFO]: 🛑 The "path" argument must be of type string. Received undefined
2023-05-05T17:43:25.503Z [INFO]: Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
2023-05-05T17:43:25.507Z [INFO]: 
2023-05-05T17:43:25.507Z [INFO]: Session Identifier: df8a8068-4693-4e85-a24c-49794caba99b
2023-05-05T17:43:25.569Z [ERROR]: !!! Build failed
2023-05-05T17:43:25.569Z [ERROR]: !!! Non-Zero Exit Code detected
2023-05-05T17:43:25.569Z [INFO]: # Starting environment caching...
2023-05-05T17:43:25.569Z [INFO]: # Environment caching completed

I am stuck in so places...

**Comment by chrisbonifacio** [comment]
Hi @manifiserv. Apologies for the delay here. We'll try to reproduce the issue you're currently running into.

Can you please run this command in your project directory?

`amplify diagnose --send-report`

Can you give us a little more information about the app you're building?

**Comment by chrisbonifacio** [comment]
Btw, @manifiserv there was an issue opened before in the CLI repo with the same error.

Please take a look at this comment and let us know if it helps: https://github.com/aws-amplify/amplify-cli/issues/11724#issuecomment-1397718764

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!

**Comment by manifiserv** [comment]
> Hi @manifiserv. Apologies for the delay here. We'll try to reproduce the issue you're currently running into.
> 
> Can you please run this command in your project directory and share the output project identifier?
> 
> `amplify diagnose --send-report`
> 
> Can you give us a little more information about the app you're building?

The error happend in amplify hosting CI/CD, So I couldn't run the above command..

**Comment by manifiserv** [comment]
Please read my main issue and let me know the solution please.

**Comment by david-mcafee** [comment]
@manifiserv - as @chrisbonifacio mentioned above, there was a ticket in the CLI repo with the same error. Can you please take a look at this comment and let us know if it resolves the issue for you? https://github.com/aws-amplify/amplify-cli/issues/11724#issuecomment-1397718764

Thank you!

**Comment by manifiserv** [comment]
@david-mcafee 
My issue is filter is not working and i resolved the path error issue.

**Comment by manifiserv** [comment]
@chrisbonifacio 
This issue is not only for custom filteres, also for auto generated subscription filters also.

This issue happened only in CI/CD, 

When I manually amplify push to the env it's working, but CI/CD build from github it's not working.

**Comment by chrisbonifacio** [comment]
Oh! That's interesting... have you checked what CLI version the CI/CD might be using? In the hosting console there should be an environment variable named something like "_LiVE_UPDATES" and include a CLI version. Can you confirm what that version is?

**Comment by david-mcafee** [comment]
@manifiserv - to add to @chrisbonifacio's comment above, can you elaborate with more detail on how you've implemented your GitHub CI/CD flow works? 

Additionally, with custom subscriptions, you will need to write your own resolvers to support filter arguments. `$extensions.setSubscriptionFilter()` is the method you will need to call in the resolver to set the subscription filter.

Additionally, auth is not enabled by default (you will have to build that on your own, as well).

For additional documentation, see https://docs.aws.amazon.com/appsync/latest/devguide/aws-appsync-real-time-enhanced-filtering.html.

Please let us know if this helps!

**Comment by chrisbonifacio** [comment]
> @chrisbonifacio 
> 
> 
> 
> My local amplify version is 10.6.0 and the CI/CD amplify version is 9.2.1..
> 
> 
> 
> is this may be the issue?

I just realized you had already mentioned the CI/CD version. This could be potentially be the issue. There would be missing improvements to the transformer and feature flags that you are using locally and not in production.

**Comment by manifiserv** [comment]
> Oh! That's interesting... have you checked what CLI version the CI/CD might be using? In the hosting console there should be an environment variable named something like "_LIVE_UPDATES" and include a CLI version. Can you confirm what that version is?

I am using the CLI version is 10.2.3

**Comment by david-mcafee** [comment]
> @manifiserv - to add to @chrisbonifacio's comment above, can you elaborate with more detail on how you've implemented your GitHub CI/CD flow works?
> 
> Additionally, with custom subscriptions, you will need to write your own resolvers to support filter arguments. `$extensions.setSubscriptionFilter()` is the method you will need to call in the resolver to set the subscription filter.
> 
> Additionally, auth is not enabled by default (you will have to build that on your own, as well).
> 
> For additional documentation, see https://docs.aws.amazon.com/appsync/latest/devguide/aws-appsync-real-time-enhanced-filtering.html.
> 
> Please let us know if this helps!

@manifiserv - did you see my previous comments (included above)? In order to better assist you, we would need to know if you've already written your own resolvers / added auth. Thank you!!

**Comment by david-mcafee** [comment]
@manifiserv - closing this ticket as we have not heard back from you. If you need further assistance, please let us know!
