### ISSUE TITLE
Amplify Sync subscription limit too low

### ISSUE THREAD

**Issue by DougalW** [aws-amplify/amplify-js#11353]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

DataStore

### Environment information

<details>

```
# Put output below this line

  System:
    OS: macOS 12.6.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 515.78 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.5.0 - /opt/homebrew/bin/node
    npm: 9.3.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 112.0.2
    Safari: 16.3
  npmPackages:
    @aws-amplify/ui-react: ^4.6.0 => 4.6.0 
    @aws-amplify/ui-react-internal:  undefined ()
    @testing-library/jest-dom: ^5.16.5 => 5.16.5 
    @testing-library/react: ^13.4.0 => 13.4.0 
    @testing-library/user-event: ^13.5.0 => 13.5.0 
    aws-amplify: ^5.1.3 => 5.1.3 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    react-scripts: 5.0.1 => 5.0.1 
    web-vitals: ^2.1.4 => 2.1.4 
  npmGlobalPackages:
    npm: 9.3.1


```

</details>

### Describe the bug

Hi

I have a data model with 35 tables and 23 enums, and 70 forms. I keep getting a "Max number of 100 subscriptions reached" error message.

Can you please double this to 200 to handle my workload.

referencing issue #5050 previously.

This is an urgent issue as it's holding up our development.
            

### Expected behavior

Sync should just sync the local and Amplify models.

### Reproduction steps

Running a page in our React app will trigger this.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_appsync_graphqlEndpoint": "https://lhf7jkuwgzcd5ckfjnwepqhov4.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-aneclgwfezfyldrtjrbjfspoim"
};

export default awsmobile;

### Additional information and screenshots

![Screen Shot 2023-05-09 at 10 04 49 AM](https://user-images.githubusercontent.com/47440012/236986204-d323721f-9793-48d0-9d1f-02bab091fe0c.png)

**Comment by chrisbonifacio** [comment]
Hi @DougalW 👋  It is possible to request a service limit increase from the AppSync service team. Please submit one via the AWS console.

https://docs.aws.amazon.com/servicequotas/latest/userguide/request-quota-increase.html

![CleanShot 2023-05-10 at 12 55 17](https://github.com/aws-amplify/amplify-js/assets/16952986/f963a16d-0f21-414e-941e-2b9c6fba4af7)

**Comment by DougalW** [comment]
Thanks, I've requested an increase.
