### ISSUE TITLE
Graphql subscription does not work with default identityClaim if allow: owner is set

### ISSUE THREAD

**Issue by michaelrios** [aws-amplify/amplify-js#11354]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

This is kind of how it is supposed to work, so you may not consider it a bug, but this is at the very least something that should be added to documentation.

When subscribed to an appsync mutation, the subscription is only listening to the return object when the `create` event occurs. This is normally not a problem UNLESS the subscribed object is using `allow: owner`.

When the `create` event happens the `API.graphql` function call returns `owner: {username}`, and not `owner: {sub::username}` as is the standard `identityClaim` format. So when the subscription is listening for mutations, it only sees `owner: {username}`, which is not the actual value used to verify the subscribed user.

If I override the `identityClaim` to be `username`, then the subscription works since the creation only returns `username`, and not the full default identity claim `sub::username`

### Expected behavior

Given the following graphql.schema
```
type Message @model @auth(rules: [
  { allow: owner, ownerField: "owners", operations: [read]}
]) {
  id: ID!
  message: String!
  owners: [String!]!
}
```

The `onCreateMessage` subscription should work, but it will not unless the `identityClaim` is overridden to be just `username`, and not the default `sub::username`.

### Reproduction steps

1. use the above model in a graphql.schema
2. `amplify push`
3. login as the user
4. subscribe to `onCreateMessage`
5. create a message using `createMessage`, and set the `owners` field
6. You will not see the message
7. if you override the `identityClaim` as I mentioned above, resubscribe, and create a new message only using the `username` in the owners, then you will then see the message

**Comment by michaelrios** [comment]
Without changing the `identityClaim` I can `listMessges` no problem, the issue is only while subscribed to the changes.

**Comment by michaelrios** [comment]
to recreate the issue, I am setting the owners field to `sub::username`
Thanks for looking into this 🙏🏼

**Comment by cwomack** [comment]
Hello, @michaelrios 👋. With the release of the latest major version of Amplify (aws-amplify@>6), we highly recommend updating to the most recent version. Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.

Can you please try to upgrade to v6 and see if this issue persists? Thank you!

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
