### ISSUE TITLE
DataStore.stop removing subscription to model

### ISSUE THREAD

**Issue by andrii-gds** [aws-amplify/amplify-js#11365]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

DataStore

### Amplify Categories

storage

### Environment information

<details>

  System:
    OS: macOS 12.6.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 409.43 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.6.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.0 - /usr/local/bin/npm
    Watchman: 2023.04.17.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 113.0.5672.92
    Safari: 15.6.1
  npmPackages:
    @aws-amplify/datastore-storage-adapter: ^2.0.7 => 2.0.16 
    @babel/cli: ^7.14.3 => 7.21.0 
    @babel/core: ^7.12.9 => 7.21.0 (7.9.0)
    @babel/preset-env: ^7.14.2 => 7.20.2 
    @expo/webpack-config: ~0.16.2 => 0.16.27 
    @react-native-async-storage/async-storage: ~1.15.0 => 1.15.17 
    @react-native-community/datetimepicker: 4.0.0 => 4.0.0 
    @react-native-community/masked-view: 0.1.10 => 0.1.10 
    @react-native-community/netinfo: 7.1.3 => 7.1.3 
    @react-native-picker/picker: 2.2.1 => 2.2.1 
    @react-navigation/bottom-tabs: ^5.11.1 => 5.11.15 
    @react-navigation/drawer: ^5.11.2 => 5.12.9 
    @react-navigation/material-top-tabs: ^5.3.10 => 5.3.19 
    @react-navigation/native: ^5.8.2 => 5.9.8 
    @react-navigation/stack: ^5.11.1 => 5.14.9 
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: ^5.2.8 => 5.2.14 (6.1.2)
    aws-amplify: ^5.0.14 => 5.0.16 
    aws-amplify-react-native: ^7.0.2 => 7.0.2 
    babel-preset-expo: 9.0.2 => 9.0.2 
    buffer: ^6.0.3 => 6.0.3 (4.9.2, 5.7.1)
    date-fns: ^2.16.1 => 2.29.3 
    expo: ^44.0.6 => 44.0.6 
    expo-barcode-scanner: ~11.2.0 => 11.2.1 
    expo-blur: ~11.0.0 => 11.0.0 
    expo-build-properties: ^0.2.0 => 0.2.0 
    expo-calendar: ~10.1.0 => 10.1.1 
    expo-camera: ~12.1.2 => 12.1.2 
    expo-checkbox: ~2.0.0 => 2.0.0 
    expo-constants: ~13.0.1 => 13.0.2 
    expo-document-picker: ~10.1.3 => 10.1.3 
    expo-file-system: ~13.1.4 => 13.1.4 
    expo-image-picker: ~12.0.1 => 12.0.2 
    expo-intent-launcher: ~10.1.0 => 10.1.3 
    expo-localization: ~12.0.0 => 12.0.1 
    expo-location: ~14.0.1 => 14.0.2 
    expo-modules-core: ~0.6.4 => 0.6.5 
    expo-permissions: ~13.1.0 => 13.1.1 
    expo-splash-screen: ~0.14.1 => 0.14.2 
    expo-sqlite: ~10.1.0 => 10.1.1 
    expo-status-bar: ~1.2.0 => 1.2.0 
    expo-updates: ~0.11.7 => 0.11.7 
    hermes-inspector-msggen:  1.0.0 
    i18n-js: ^3.8.0 => 3.9.2 
    modal-react-native-web: ^0.2.0 => 0.2.0 
    react: 17.0.1 => 17.0.1 
    react-dom: 17.0.1 => 17.0.1 
    react-native: 0.64.3 => 0.64.3 
    react-native-calendars: ^1.427.0 => 1.1293.0 
    react-native-gesture-handler: ~2.1.0 => 2.1.3 
    react-native-maps: 0.29.4 => 0.29.4 
    react-native-modal: ^11.10.0 => 11.10.0 
    react-native-reanimated: ~2.3.1 => 2.3.3 
    react-native-safe-area-context: 3.3.2 => 3.3.2 
    react-native-screens: ~3.10.1 => 3.10.2 
    react-native-select-two: ^1.1.0 => 1.1.0 
    react-native-signature-canvas: ^3.3.0 => 3.6.0 
    react-native-sqlite-storage: ^6.0.1 => 6.0.1 
    react-native-svg: 12.1.1 => 12.1.1 
    react-native-tab-view: ^2.15.2 => 2.16.0 
    react-native-vector-icons: ^4.6.0 => 4.6.0 
    react-native-web: 0.17.1 => 0.17.1 
    react-native-web-maps: ^0.3.0 => 0.3.0 
    react-native-webview: 11.15.0 => 11.15.0 
  npmGlobalPackages:
    @aws-amplify/cli: 11.0.5
    @zendesk/zcli: 1.0.0-beta.32
    expo-cli: 6.3.2
    npm: 9.4.0
    yarn: 1.22.19

</details>

### Describe the bug

1) I'm subscribing to WorkerOrder model
2) Post new model from admin
3) Function subscribe invoking and from snapshot i receives orderId and set it to asyncStorage
4) Need to reinvoke asyncExpressions because i should refetch all fields by new orderId that i've received from snapshot
5) For (4) invoke performOrderSync that refreshes DataStore by stop and start methods, however it's canceling subscription for future updates, i even tried to resubscribe to this model after DataStore.stop and start and this allow subscription callback invoke 2 times only
6) Is there a way to syncExpressions without DataStore.stop or DataStore.clear methods and without canceling subscription?

### Expected behavior

stop method invokes syncExpression and shouldn't remove subscription

### Reproduction steps

1) I'm subscribing to WorkerOrder model
2) Post new model from admin
3) Function subscribe invoking and from snapshot i receives orderId and set it to asyncStorage
4) Need to reinvoke asyncExpressions because i should refetch all fields by new orderId that i've received from snapshot
5) For (4) invoke performOrderSync that refreshes DataStore by stop and start methods, however it's canceling subscription for future updates, i even tried to resubscribe to this model after DataStore.stop and start and this allow subscription callback invoke 2 times only
6) Is there a way to syncExpressions without DataStore.stop or DataStore.clear methods and without canceling subscription?

### Code Snippet

useEffect(() => {
    const hubSubscription = Hub.listen("datastore", listener);
    let subscription;

    const listener = async (msg) => {
        const event = msg.payload.event;
        if (event === "ready") {
          await getMyOrders();
          setRefreshing(false);
        }
      };
      
    const observeWorkerOrder = () => {
       
        subscription = DataStore.observe(WorkerOrderAssign, (c) =>
        c.and((c) => [
          c.companyID.eq(user.company),
          c.workerID.eq(user.record.id),
        ])
      ).subscribe(async (snapshot) => {
        console.log(snapshot);
        const { opType, element } = snapshot;
        const orderId = element.orderID;

        if (workerOrderAssignmentObserveTypes[opType] && orderId) {
          await setItemToAsyncStorage(ASYNC_STORE_KEYS.ORDER_ID, orderId); //setted orderId then invoking syncExpressions to refetch data from remote db to local by orderID
          await performOrderSync(); // DataStore.stop and start methods invoking here
          await removeItemFromAsyncStorage(ASYNC_STORE_KEYS.ORDER_ID); //remove item after syncExpressions invoked
        }
    
      });
    };
    
    observeWorkerOrder();
    return () => {
      hubSubscription.remove("datastore", listener);
      subscription?.unsubscribe();
    };
  }, []);

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by andrii-gds** [comment]
this in DataStore.configure syncExpression(FieldWorkOrder, async () => {
                        const newOrderId = await getItemFromAsyncStorage(ASYNC_STORE_KEYS.ORDER_ID)
                        if(newOrderId) {
                            syncOrderIDs.push(newOrderId)
                       }
                        return fwo => fwo.and(f => [
                            f.companyID.eq(companyID),
                            (syncOrderIDs && syncOrderIDs.length) ? f.or(f => syncOrderIDs.reduce((acc, id) =>{
                                return [...acc, f.id.eq(id)]
                            }, [])) : f.id.eq(null)
                        ]);
                    }),

**Comment by david-mcafee** [comment]
@andrii-gds I apologize, but I'm not sure I understand what you mean by `how it's possible to dynamically invoke resync inside subscription callback` - can you explain? 

Can you include a code snippet of how you are creating a new subscription? I see that you're creating the initial subscription with `useEffect` - do you have a function that calls `DataStore.observe` elsewhere? Also, after you call `DataStore.stop`, are you calling `DataStore.start` to restart DataStore? Thank you!

**Comment by andrii-gds** [comment]
`const listener = async (msg) => {
        const event = msg.payload.event;
        if (event === "ready") { 
            await getMyOrders();
            setRefreshing(false)
        } 
    }

    useEffect( () => {
        const hubSubscription = Hub.listen('datastore', listener); 
        const subscription = DataStore.observe(WorkerOrderAssignment,c => c.and(c => [c.companyID.eq(user.company), c.workerID.eq(user.record.id) ]))
        .subscribe( async (snapshot) => {
            const { opType, element } = snapshot;
            if(!workerOrderAssignmentObserveTypes[opType]) return;
            const orderId = element.orderID;        
            if (!orderId) return;
            await setItemToAsyncStorage(ASYNC_STORE_KEYS.ORDER_ID, orderId);
            await DataStore.stop()
            await DataStore.start()
            await removeItemFromAsyncStorage(ASYNC_STORE_KEYS.ORDER_ID) //remove item after syncExpressions invoked
        })
        return () => {
            hubSubscription.remove('datastore', listener)
            subscription.unsubscribe();
        }
    },[])`
I am setting orderId to async store, after that refreshing store by stop and start, and invoking sync expressions 
`syncExpression(FieldWorkOrder, async () => {
                        const newOrderId = await getItemFromAsyncStorage(ASYNC_STORE_KEYS.ORDER_ID)
                        if(newOrderId) {
                            syncOrderIDs.push(newOrderId)
                       }
                        return fwo => fwo.and(f => [
                            f.companyID.eq(companyID),
                            (syncOrderIDs && syncOrderIDs.length) ? f.or(f => syncOrderIDs.reduce((acc, id) =>{
                                return [...acc, f.id.eq(id)]
                            }, [])) : f.id.eq(null)
                        ]);
                    }),`

**Comment by andrii-gds** [comment]
@david-mcafee here my 2nd try with resubscription, will be happy if you can suggest workaround for first example that i sent or with this one.
<img width="740" alt="image" src="https://github.com/aws-amplify/amplify-js/assets/131213049/bae3027e-4bae-45fe-bd39-e7cf0af06581">

**Comment by chrisbonifacio** [comment]
Hi @andrii-gds unfortunately there's no way to avoid subscriptions being closed when calling DataStore.stop and/ore re-evaluating sync expressions. I would recommend re-establishing the `WordOrderAssignment` subscription where you are calling `removeItemFromAsyncStorage`.

**Comment by david-mcafee** [comment]
@andrii-gds - can you explain your use-case for wanting to update the sync expression for every update received by the subscription (i.e. `DataStore.observe`)? Perhaps that could help us provide a better solution here. Thanks!

**Comment by andrii-gds** [comment]
@david-mcafee from snapshot i need receive orderId field, that means sync expressions need to be re evaluated with new orderID. Ok i understood that not possible invoke syncExpression without calling stop method, however i invoking observe function in line 112 after dataStore stopped and started, why this doesn't work? Maybe you have any suggestions how i can safely make re subscription after stop method

**Comment by andrii-gds** [comment]
@david-mcafee I'm also trying make changes to schema, maybe you know why i'm receiving field as Promise and first time it undefined, after app reload it's object 
<img width="464" alt="image" src="https://github.com/aws-amplify/amplify-js/assets/131213049/e33d9e4e-c9c3-44bc-b124-ad507c9aeed5">
this field was added in schema.grapql `order: FieldWorkOrder @connection(fields: ["orderID"])`

**Comment by andrii-gds** [comment]
@chrisbonifacio Are you planing to add possibility to sync expressions without stop datastore?

**Comment by david-mcafee** [comment]
@andrii-gds - checking in to see if you were able to take a look at @svidgen's guidance on how sync expressions work / if you were able to test using a larger data set. Thanks!

**Comment by david-mcafee** [comment]
@andrii-gds - closing this ticket as we have not heard back from you. If you need further assistance, please let us know!
