### ISSUE TITLE
How can I change the Section Header words on Authenticator React Native?

### ISSUE THREAD

**Issue by smellysocks12314** [aws-amplify/amplify-js#1136]
Apologies for the naive question but I was scratching my head for quite some time going through the source code and I can't seem to find forums for this question. I'm using the default withAuthenticator component for my React Native application. The default works well for my purpose but I only need to change the default header text of "Sign In" to another String Value Is there an easy way to do this?

**Do you want to request a feature or report a bug?**
Question

**Comment by jordanranz** [comment]
Going to close this due to inactivity. Please see the link posted above to configure custom styling for the Section Header. If you have any more related questions or concerns please reopen this issue.
