### ISSUE TITLE
AWS AppSync multi client support

### ISSUE THREAD

**Issue by SamVerschueren** [aws-amplify/amplify-js#1137]
Do you want to request a feature or report a bug? *Not Sure*

**What is the current behavior?**

I described a lot of our use case on the [AWS forum](https://forums.aws.amazon.com/thread.jspa?threadID=284905), it might be interesting for some background of how our architecture works.

Currently, the result of a `subscription` call returns an array of 2 `mqttConnections`. In the source code, we noticed [this line](https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify/src/PubSub/Providers/AWSAppSyncProvider.ts#L43-L44). 

> TODO: support multiple clients

It's unclear to us why we get an array of 2 connections (would be nice if someone knows the answer to this :)), but it results in sockets failing to connect as it sometimes needs the second client instead of the first one.

So how can we solve this? We dived into the code and changed [this line]() to the following

```js
const { client: clientId, url } = mqttConnections.find(client => client.topics.includes(topics[0]);
```

> **Note:** We just used `topics[0]` for testing purposes, might have to do it in a better way

But that change seemed to work correctly. I just find it weird that we ask for a subscription for a topic, and we get back two clients, why?

**Comment by mlabieniec** [comment]
This was fixed in a previous PR but not referenced and should be fixed in the latest. Please re-open if you are still experiencing the issue.
