### ISSUE TITLE
[Feedback]Update email example not working

### ISSUE THREAD

**Issue by sharived** [aws-amplify/amplify-js#11376]
**Page**: [`/lib/auth/manageusers/q/platform/[platform]`](https://docs.amplify.aws/lib/auth/manageusers/q/platform/js)

**Feedback**:

I am trying to update an email after a user is already confirmed.  I am basing my code on the example code, within my UI.
The issue is that since the user is already confirmed when I try and pass the code I get the error :  User cannot be confirmed. Current status is CONFIRMED

I start with 
        Auth.updateUserAttributes(user, {email: data.email});
User gets an email with the code and send it with
       Auth.verifyCurrentUserAttributeSubmit('email', code)
At this point I get the error: User cannot be confirmed. Current status is CONFIRMED

Note I have tried both with currentUser and passing in userSub id, I also have tried with and without "Keep original attribute value active when an update is pending"

So not sure if there is a bug or there is an issue with the documentation

**Comment by nadetastic** [comment]
@sharived Since you mentioned that you no longer have federated login, could you try running `amplify pull` in order to update the `aws-exports.js` file? Also note that if it doesn't update you may need to delete the `./amplify` folder as well as the `aws-exports.js` file. Once it updates verify if updating the email works.

**Comment by sharived** [comment]
@nadetastic Thanks for your support.  When I regenerate everything I'm still getting the same was-exports.js file.  I guess I still have remnants of when I had created the federated login.  I still see an identity pool with a Facebook login.  I will attempt to delete this and I guess worst case is I'll regenerate my user pool again.

**Comment by sharived** [comment]
@nadetastic - I recreated my user pool and got rid of the federated login.  Unfortunately it didn't change anything with trying to update an email.  Still getting the same error.  here is my updated aws-exports.js

```
"oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
```

**Comment by nadetastic** [comment]
@sharived I'm still not able to reproduce this issue. Here's some context to what I am doing:

Updating the email
```js
const updateEmail = async () => {
    try {
      const _user = await Auth.currentAuthenticatedUser()
      const _res1 = await Auth.updateUserAttributes(_user, {
        email: '<the_new_email>',
      })
      console.log(_res1) // logs SUCCESS
    } catch (error) {
      console.log(error)
    }
  }
```
The above sends a verification code to the new email. I take that code and submit it with the following:

```js
  const confirmEmailUpdate = async () => {
    try {
      const _res2 = await Auth.verifyCurrentUserAttributeSubmit('email',code_sent_to_email)
      console.log(_res2) // logs SUCCESS
    } catch (error) {
      console.log(error)
    }
  }
```
Checking my user in Cognito I see they have been updated with the new email.

Here's my aws-exports.js which seems to matche what you have.
```js
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:76f0d621-5a8d-455c-af69-e28479fef385",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ct8blXsZT",
    "aws_user_pools_web_client_id": "6hrc6oin37ct1mlquuqrkj4adn",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};
```

Do you mind sharing the full aws-exports so I can try reproduce with your setup?

**Comment by sharived** [comment]
@nadetastic Thanks for your help.  Here you go - they look virtually the same. 

 Note that currently I "keep the original value active when update is pending" (see below screenshot) - So my process is I update the email, get the code to new email, then send the code via Auth.verifyCurrentUserAttributeSubmit('email', code).  I then get the error message [NotAuthorizedException: User cannot be confirmed. Current status is CONFIRMED]. So I never update the email in the user pool.
 
<img width="1236" alt="Screenshot 2023-05-18 at 1 49 23 PM" src="https://github.com/aws-amplify/amplify-js/assets/1163591/e47c7df6-ecaf-490e-b9c4-010c51c984ae">

If I disable "Keep original attribute value active when an update is pending" - then I see the email changed in the user pool, but it is not verified since I still get the same error when I submit the code.
<img width="1393" alt="Screenshot 2023-05-18 at 2 05 36 PM" src="https://github.com/aws-amplify/amplify-js/assets/1163591/a0b89a43-5f4a-49d2-b677-ba16949737ec">


```
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://pta3d4jwyzea3i5w3xehzluz44.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-dtvvq22rrnbtjpdkul2a4bwyvm",
    "aws_cognito_identity_pool_id": "us-east-1:16b2d942-75a3-4e2a-bbd6-bf3628411c11",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_mv6vrwr1g",
    "aws_user_pools_web_client_id": "13e8ij6mhh1i8dd8uraqcd74i2",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "nspyre134150-test",
    "aws_user_files_s3_bucket_region": "us-east-1"
};

```

**Comment by nadetastic** [comment]
@sharived I'm still unable to reproduce this error and even when using your `aws-exports.js` - I'm able to sign up, confirm the account, and update the email address successfully. 

Is there any other specific configuration you may have on your client or backend that wouldn't be the default? Im also curious how your client is setup - for reference is a [repo of the application i've tested with under the 11376 branch](https://github.com/nadetastic/vite-amplified-react/tree/11376).

**Comment by sharived** [comment]
@nadetastic thanks.  My configuration is pretty generic I believe.  I'm heading out for the weekend but will look at your reference in a couple of days.  If it's allowed I can give you access to my AWS account too.

**Comment by sharived** [comment]
So I'm trying to use your code, but I don't think I'm setting it up right.  However I am seeing that you successfully ran it in my environment and were able to add a user and update the email.
<img width="1503" alt="Screenshot 2023-05-22 at 11 42 17 AM" src="https://github.com/aws-amplify/amplify-js/assets/1163591/0965103b-2d7a-4dd3-9fb4-ea54bce07e6f">
So this leads me to believe it's not my setup, it's more likely my code.  I will try incorporating your code back into mine - I see a few differences (they look minor, but maybe not).

**Comment by sharived** [comment]
@nadetastic It turns out it was a programmatic error on my part.  I had some incorrect logic and was actually calling confirmCodeEmail instead of confirmCodeUpdateEmail - so now that error message makes complete sense.  I'm so sorry to have wasted your time.  Thank you so much for your help.
