### ISSUE TITLE
Relax version requirement

### ISSUE THREAD

**Issue by daveisfera** [aws-amplify/amplify-js#11373]
### Is this related to a new or existing framework?

React Native

### Is this related to a new or existing API?

Storage

### Describe the feature you'd like to request

Currently, specific versions are used for dependencies, but relaxed versions would allow users more flexibility in what's installed.

### Describe the solution you'd like

Use `^` instead of a specific version

### Describe alternatives you've considered

Use `~` 

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by nadetastic** [comment]
Hi @daveisfera thank you for opening this issue. I'd like to gather more information on the use case you are looking for with this request. Could you explain a bit more about it? Also is this specific to one of the packages (ex `@aws-amplify/storage`) or the `aws-amplify` package itself?

**Comment by daveisfera** [comment]
It's for `aws-amplify` in general, but `@aws-amplify/storage` is the one that is causing multiple versions of packages to be installed in our project currently. Here's the list of dependencies:
```
dependencies:
    "@aws-amplify/core" "5.1.13"
    "@aws-sdk/client-s3" "3.6.2"
    "@aws-sdk/s3-request-presigner" "3.6.1"
    "@aws-sdk/util-create-request" "3.6.1"
    "@aws-sdk/util-format-url" "3.6.1"
    axios "0.26.0"
    events "^3.1.0"
    tslib "^1.8.0"
```

Multiples versions of `axios` are being installed because a specific version is being specified. Ideally, it would be `^0.26.0` so there's more flexibility in the version that's installed. The same would be true with the `@aws-sdk` packages as well.

**Comment by nadetastic** [comment]
@daveisfera thanks for clarifying - I've marked this as a feature request and are discussing with the team. Will follow up with any updates. Thanks!

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
