### ISSUE TITLE
Cognito user administration/management

### ISSUE THREAD

**Issue by clementAC** [aws-amplify/amplify-js#1138]
Do you want to request a feature or report a bug?

It's a feature request

What is the current behavior?

Currently it's not possible to make simple user administration without going to cognito web GUI. For exemple, listing users from user pool, deleting or deactivate users.

What is the expected behavior?

The expected behavior is the possibility to interrract via amplify with cognito to make simple user administration.

**Comment by abdallahshaban557** [comment]
Hi @clementAC - do this admin actions provide you with the functionality you need? https://github.com/aws-amplify/amplify-js/issues/1138

**Comment by tannerabread** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and are in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
