### ISSUE TITLE
Using S3 Storage with Amplify

### ISSUE THREAD

**Issue by pokemon963** [aws-amplify/amplify-js#11386]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

us-east-1

### Step

Domain activation

### Status

Failed

### Issue or question

Hi! I am trying to use S3 buckets with my AWS Amplify. However, I keep getting errors with regards to importing aws-amplify. As of right now, my errors are: Failed to load resource: the server responded with a status of 404 () and Uncaught (in promise) TypeError: Storage.get is not a function. This is the code I have :

HTML:
```
<script src="amplifyConfig.js" type="module"></script>
<script>
  // Import the Storage library and make it available globally
  window.Storage = window.amplifyStorage.default;
</script>
<script type="text/javascript">
		window.onload = async function downloadFile() {
	  const url = await Storage.get('________.txt');
	  console.log('Downloaded file: ', url);
	};

</script>
```

amplifyConfig.js:
```
import Amplify from './aws-amplify';
import { Storage } from './aws-amplify';


Amplify.configure({
  Auth: {
    // your auth config
    region: '________',
    userPoolId: '______________',
    userPoolWebClientId: '__________'
  },
  Storage: {
    AWSS3: {
      bucket: '_____________',
      region: '_______________',
      identityPoolId: '____________'
    }
  }
});

export default {
  // Export the Storage module as a property of the default export
  amplifyStorage: Storage,
};
```

### Error message

Failed to load resource: the server responded with a status of 404 ()
Uncaught (in promise) TypeError: Storage.get is not a function

**Comment by nadetastic** [comment]
Hi @pokemon963 thank you for opening this issue. Could you tell me more about how your project is setup? It looks like you are not using a package manager and are link the package directly with `<script src="amplifyConfig.js" type="module"></script>`
