### ISSUE TITLE
JS: Auth does not return current signed in user details for LOGIN Endpoint

### ISSUE THREAD

**Issue by reesscot** [aws-amplify/amplify-js#11390]
Migrated from Discussions
<div type='discussions-op-text'>

<sup>Originally posted by **@nishi-vinod-bhatt** November  3, 2021</sup>
Hello
Can someone help me to understand how can we use currentAuthenticatedUser on the user who has been signed in using LOGIN endpoint.
We have used LOGIN endpoint in case of social login and are not able to retrieve user details for currently signed in user.

But in case of users signed in with Auth.signIn(), we get the user details.

</div>

**Comment by nadetastic** [comment]
Hi @nishi-vinod-bhatt following up here. Currently, you should be able to get the current signed with `Auth.currentAuthenticatedUser()` in user if they signed in with either `Auth.signIn()` or `Auth.federatedSignIn()`

I'll go ahead and close out this issue for now. But do let me know if you still have questions.
