### ISSUE TITLE
How to move Auth.Signup logic in backend server ( .net ) 

### ISSUE THREAD

**Issue by dev1gestionhb** [aws-amplify/amplify-js#11402]
### Is this related to a new or existing framework?

React Native

### Is this related to a new or existing API?

Authentication

### Is this related to another service?

DynanamoDB, lambda function

### Describe the feature you'd like to request

I have an application for real time chat using aws amplify with react native all working fine, but am wondering about security.
I have a two lambda function

1. PostConfirmation: to create save user to dynamoDB

```js
exports.handler = async (event) => {
 const params = {
        Item: { __typename: { S: 'User' },createdAt: { S: now.toISOString() },
        updatedAt: { S: now.toISOString() }, etc...},
        TableName: process.env.USER_TABLE
    };
    await ddb.putItem(params).promise();
    };
```
2-PreSignup: to auto confirm user

```js
exports.handler = async (event) => {
        event.response.autoConfirmUser = true;
        if (event.request.userAttributes.hasOwnProperty('email')) {
            event.response.autoVerifyEmail = true;
        }
    return event;
};
```
and in my react component

```js
 const { user } = await Auth.signUp({
      username:"test",
      password:"test",
      attributes: {
        email:"test@tt.ca"
      }
    });
  } 
}
```

### Describe the solution you'd like

I am trying to create api route in my backend server .net core to prevent fake account sign-ups or account deletion, otherwise move Auth.signUp(..) in server side ! any ideas ?
.

### Describe alternatives you've considered

if a hacker can get the code with reverse engineering he can spam the database with infinity of users and delete all users.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cwomack** [comment]
@dev1gestionhb, can you give a little more context on your statement of "_if a hacker can get the code with reverse engineering he can spam the database with infinity of users and delete all users._"?  Are you referring to the TOTP or MFA code provided by Cognito after sign up? And what would be the way they'd delete users once signed in, the `deleteUser()` method?

**Comment by dev1gestionhb** [comment]
@cwomack thanks for ur quick answer.
I dont want to active MFA or TOTP,
Am looking to to protect all api like Auth.SignUp()  by moving the logic in server side .net core

**Comment by israx** [comment]
Hello @dev1gestionhb , if you want to use AWS resources in the backend, you can use the `.NET` [AWS SDK](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/welcome.html)  and either using the [AdminCreateUser](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminCreateUser.html) API or [SignUp](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_SignUp.html) APIs.

**Comment by dev1gestionhb** [comment]
hello @israx , i think i cant change all the logic ( graphql (mutation etc ) , signup  and lambda function ) in net core side ! in their documentation there is only ( react native , swift , fltuter and javascript ) there is no .net core or python for example

**Comment by cwomack** [comment]
@dev1gestionhb, have you already moved or set up the authentication logic to the server side and created API Endpoints for it?  If so, are you seeing any specific errors when trying to call the Auth methods such as `Auth.signUp()`?

Or are you currently trying to get guidance on how to implement them within your .NET server?

**Comment by israx** [comment]
@dev1gestionhb at the moment Amplify is supported for client side usage. If any resource needs to be implemented in the backend you would need to either create API endpoint or use the .Net AWS SDK. You still can use Amplify for other services.

**Comment by dev1gestionhb** [comment]
thanks for your answer @israx  @cwomack

**Comment by cwomack** [comment]
@dev1gestionhb, just wanted to add to what @israx said, the [Post Confirmation Lambda Trigger](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-post-confirmation.html) only gets invoked after a new user is confirmed.  This will require the user to enter their confirmation code (from SMS or email) in both scenarios of the auth logic being client side or server side.  

The lambda trigger would offer the same level of protection in both scenarios of server and client side.  Let us know if there's an edge case we're missing or additional context that would create a further need for the authentication logic to be moved away from the client.

**Comment by nadetastic** [comment]
Hi @dev1gestionhb I'll go ahead and close this out, if you have any additional questions please let us know. Thanks!
