### ISSUE TITLE
React Native fires an error "{"_observer":{}}" everytime the apps renders a view with a appsync subscription

### ISSUE THREAD

**Issue by jesuscovam** [aws-amplify/amplify-js#11408]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 54.06 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.4.2 - /opt/homebrew/bin/npm
    Watchman: 2023.02.20.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 113.0.5672.126
    Safari: 16.3
  npmPackages:
    @aws-crypto/sha256-js: ^2.0.1 => 2.0.2 (3.0.0)
    @aws-sdk/credential-provider-node: ^3.76.0 => 3.329.0
    @aws-sdk/protocol-http: ^3.58.0 => 3.329.0
    @aws-sdk/signature-v4: ^3.58.0 => 3.329.0
    @types/node-fetch: 2 => 2.6.3
    @types/uuid: ^8.3.4 => 8.3.4
    aws-sdk: ^2.1167.0 => 2.1377.0
    axios: ^0.27.2 => 0.27.2 (0.24.0)
    expo-server-sdk: ^3.6.0 => 3.7.0
    facturapi: ^3.3.0 => 3.3.0
    node-fetch: 2 => 2.6.11
    stripe: ^9.11.0 => 9.16.0
    testing: * => 1.0.0
    tsconfig: * => 0.0.0
    uuid: ^8.3.2 => 8.3.2 (8.0.0)
  npmGlobalPackages:
    @aws-amplify/cli: 10.5.1
    eas-cli: 3.12.0
    expo-cli: 6.3.7
    node-gyp: 9.3.1
    npm: 9.4.2
    yarn: 1.22.10

```

</details>

### Describe the bug

Every time the react-native app renders a view with an AppSync subscription, it will fire this error in the console.

### Expected behavior

No console error should be fired just by rendering the view

### Reproduction steps

It happens when the app renders a view with a subscription in it

### Code Snippet

```typescript
// Put your code below this line.
useFocusEffect(
		useCallback(() => {
			if (profileID) {
				const subscription = API.graphql<
					GraphQLSubscription<OnUpdateProfileByMessageSubscription>
				>(
					graphqlOperation(onUpdateProfileByMessage, { id: profileID })
				).subscribe({
					next: async () => {
						try {
							await handlerFetchChatRoomUsers({ withRefresh: false })
						} catch (error) {
							console.error(
								'Error en update de subscription useChatRoomUsers',
								{ error }
							)
						}
					},
					error: (error: any) => {
						console.log('error in chats subscription useChatRoomUsers', {
							error,
						})
					},
				})

				return () => subscription.unsubscribe()
			}
		}, [profileID, handlerFetchChatRoomUsers])
	)
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

<img width="323" alt="Screenshot 2023-05-25 at 10 41 03" src="https://github.com/aws-amplify/amplify-js/assets/46403187/32833026-45fd-4e70-80b3-38966ee24654">
<img width="331" alt="Screenshot 2023-05-25 at 10 41 10" src="https://github.com/aws-amplify/amplify-js/assets/46403187/232b39fe-f785-4f62-9ce7-e21b0f43d06b">

**Comment by iartemiev** [comment]
Hey @jesuscovam, I tried to reproduce the issue with the code sample you provided, but I'm not encountering that error. 

I created a minimal Expo app that establishes a subscription inside of a `useFocusEffect` hook here: https://github.com/iartemiev/issue-11408/. All the relevant code is in the [App.js file](https://github.com/iartemiev/issue-11408/blob/main/App.js). Please let me know what needs to be added to it (or feel free to open a PR into that repo) in order to reproduce the error.

**Comment by jesuscovam** [comment]
Thank you @iartemiev, I follow up on the test in your example and you're right, it must be something on our side that's unrelated to app sync.

In your example, the logs of reachability got a confirmation
<img width="804" alt="Screenshot 2023-05-29 at 14 36 19" src="https://github.com/aws-amplify/amplify-js/assets/46403187/6b5b2bfc-8654-4179-ad73-18e05324ffd6">


But ours always end on the second log and fires the console.error {_observer:{}}
<img width="742" alt="Screenshot 2023-05-29 at 14 43 19" src="https://github.com/aws-amplify/amplify-js/assets/46403187/9ac0044a-e30e-4144-b1db-8a8de971b561">
