### ISSUE TITLE
Node 14 vs aws-amplify compatible issue

### ISSUE THREAD

**Issue by kelin-pivot** [aws-amplify/amplify-js#11443]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 13.3.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 91.14 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.21.3 - /opt/homebrew/opt/node@14/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 6.14.18 - /opt/homebrew/opt/node@14/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 112.0
    Safari: 16.4
  npmGlobalPackages:
    @builder.io/ai-shell: 1.0.1
    aws-cdk: 2.78.0
    corepack: 0.15.1
    d: 1.0.1
    es5-ext: 0.10.62
    es6-iterator: 2.0.3
    es6-symbol: 3.1.3
    ext: 1.7.0
    lerna: 6.6.1
    next-tick: 1.1.0
    npm: 6.14.18
    nvm: 0.0.4
    rimraf: 5.0.0
    serverless: 3.30.1
    type: 2.7.2
    yarn: 1.22.19

```

</details>

### Describe the bug

[note] our app needs Node14 to work, and we can't upgrade to node16 as of today.

Failed to compile.

./~/@aws-amplify/geo/~/camelcase-keys/index.js
Module parse failed: /Users/XXXXX/Desktop/apps/XXXXXXXX/node_modules/@aws-amplify/geo/node_modules/camelcase-keys/index.js Unexpected token (33:2)
You may need an appropriate loader to handle this file type.
|               deep: false,
|               pascalCase: false,
|               ...options
|       };
|

### Expected behavior

expect the app is able to connect to graphqlAPI via amplify API

code sample:
const result = await API.graphql({ query: listDevices }) as DeviceGraphQLResponseI;

### Reproduction steps

npm start

### Code Snippet

```javascript
// Put your code below this line.

import config from './aws-exports'
Amplify.configure(config)

then this should work
const result = await API.graphql({ query: listDevices }) as DeviceGraphQLResponseI;
```

### Log output

<details>

```
// Put your logs below this line


Failed to compile.

./~/@aws-amplify/geo/~/camelcase-keys/index.js
Module parse failed: /Users/XXXXX/Desktop/apps/XXXXXXXX/node_modules/@aws-amplify/geo/node_modules/camelcase-keys/index.js Unexpected token (33:2)
You may need an appropriate loader to handle this file type.
|               deep: false,
|               pascalCase: false,
|               ...options
|       };
|


</details>


### aws-exports.js

_No response_

### Manual configuration

_No response_

### Additional configuration

_No response_

### Mobile Device

_No response_

### Mobile Operating System

_No response_

### Mobile Browser

_No response_

### Mobile Browser Version

_No response_

### Additional information and screenshots

_No response_

**Comment by chrisbonifacio** [comment]
Hi @kelin-pivot unfortunately Node doesn't support Node 14 anymore as the maintenance period has ended and has reached end of life. The lowest supported version is 16. I think the only way to unblock you here is to downgrade to the last version of the amplify library that supported Node 14. I highly recommend upgrading to 16 when you can as Node 14 will no longer receive security updates.

**Comment by chrisbonifacio** [comment]
What are you using that requires Node 14? Maybe that dependency can be updated or replaced with something that supports Node 16?

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
