### ISSUE TITLE
Invalid details for authenticateUser on a unconfirmed user should not return UserNotConfirmed on amazon-cognito-identity-js

### ISSUE THREAD

**Issue by jamaybyrone** [aws-amplify/amplify-js#11488]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I'm using amazon-cognito-identity-js version 6.2.0 when authenticating a unconfirmed user, you can enter invalid passwords and there is no way to tell the details are incorrect.

Steps to replicate:

Register a user, but do not confirm, when going through an authentication journey, if you enter incorrect password for a user, the only error message from: `authenticateUser` is `UserNotConfirmed` there is no way to tell if the credentials are correct or not.

### Expected behavior

I would expect the error message: `NotAuthorizedException: Incorrect username or password.` to take precedence over `UserNotConfirmed`

### Reproduction steps

Call signUp method, but never confirm, call authenticateUser, with a incorrect password.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by nadetastic** [comment]
Hi @jamaybyrone thank you for opening this issue, I did some testing and can confirm the behavior you are experiencing  but only if I have my App Client setting for "Prevent User Existence" disabled as shown below.

![UserExistence](https://github.com/aws-amplify/amplify-js/assets/87148442/36af7ff6-79a1-44b9-9fec-38b72c207a16)

If you enable this setting, which is recommended, you will be able to observe the behavior that you expect. Can you confirm if you have this setting enabled?

**Comment by jamaybyrone** [comment]
Ahhh thank you so much, yes this was the issue! Little odd that without that setting that becomes the priority of errors.
