### ISSUE TITLE
PubSub subscribing with wildcards 

### ISSUE THREAD

**Issue by binary-birthday** [aws-amplify/amplify-js#11506]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

PubSub

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

Hello, 

I am having the exact same issues described in closed #issue #993 

When subscribing to a topic that includes a wildcard like below

```
PubSub.subscribe('my-topic/+/sensor1').subscribe({
    next: data => console.log('Message received', data),
    error: error => console.error(error),
    close: () => console.log('Done'),
});
```

PubSub fails to invoke the next function when I publish to a topic like 'my-topic/data/sensor1'.

However, a subscription with a topic that doesn't include a wildcard does invoke the next function when I publish to the topic 'my-topic/data/sensor1'.

```
PubSub.subscribe('my-topic/data/sensor1').subscribe({
    next: data => console.log('Message received', data),
    error: error => console.error(error),
    close: () => console.log('Done'),
});
```

I have configured my role, attached it to the Cognito identity id, and debugged to confirm that the topic is subscribed to successfully and the connection is made successfully.

I am using "aws-amplify": "^5.1.4"

### Expected behavior

I expect that using a wildcard in a subscription topic would allow for matching to that topic using the wildcard as per MQTT topic rules for wildcards.

### Reproduction steps

In a react app using:

react:  ^18.2.0,
vite:  ^4.3.2,
aws-amplify: ^5.1.4 

follow the steps to configure amplify pub-sub from the Amplify docs found here: 

https://docs.amplify.aws/lib/pubsub/getting-started/q/platform/js/

subscribe to a topic with a wildcard such as 'my-topic/+/sensor1' and publish to topic 'my-topic/data/sensor1' using the iot-core test client.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by stocaaro** [comment]
Hello @binary-birthday,

This is interesting. I verified that the Test Client in the AWS console behaves the way you expect it to (when `my-topic/data/sensor1 `sends a message, then `my-topic/+/sensor1` receives it). Next I setup a sample app, which I've used to test other IoT MQTT issues. When I use a single app with a subscription to both `my-topic/data/sensor1` and `my-topic/+/sensor1`, this app doesn't receive the message on the `my-topic/+/sensor1` channel that it sends on the `my-topic/data/sensor1` channel. However, when I open two separate applications, one for each subscription, then send a message on the channel with no wildcard, then both subscriptions receive the message.

**Before message sent:**

<img width="823" alt="image" src="https://github.com/aws-amplify/amplify-js/assets/94858815/f6dd9da3-d373-4391-97ba-c64fb2099b0b">

which when the message is submitted shows up for both subscriptions


**After message sent:**
<img width="816" alt="image" src="https://github.com/aws-amplify/amplify-js/assets/94858815/283f8f1f-ec34-4f83-9027-5b154b0cc48e">

In your testing, where you sending the message from the same runtime that you where expecting to receive it?

Hope this helps. If the message you are expecting to receive is sent from another runtime / source, can you provide more information about your applications setup and the action sequence that leads to the result your seeing?

Thanks,
Aaron

**Comment by binary-birthday** [comment]
Hi Aaron,

Thanks for your reply. 

I'm only subscribing to topics in my web app and using the IoT core test client to publish topics.

I am subscribing to several topics in the app, each using a slight variance of the same topic (ie: changing the sensor id). I receive all data expected when the topic is supplied without any wildcards, even with multiple subscriptions in the same app. 

Please let me know if you require any more information from me.

Thanks, 
Wade

**Comment by stocaaro** [comment]
Hello @binary-birthday ,

In the sample app I provided screen shots from above, I am able to set up a subscription with wildcards, which receives content posted to a different channel that matches the wildcard. I am also able to verify this behavior by posting to the IoT test client for my account (an outside data source). In your code, it looks like your subscriptions are conditional based on different sensor id inputs, which seems strange unless depending on your usecase. Do you have a sample of the code you are using the subscribes with wildcards?

I'm not sure why its working in my app and not in yours. Any further information you can provide would help.

Thanks,
Aaron

**Comment by stocaaro** [comment]
This has been out there a few months without input. I'm closing it, but if there is more info to chase down, please reply with details and happy to reopen the investigation.

Thanks!
Aaron
