### ISSUE TITLE
User is not created in Cognito User pool for users who login in with Google federated login, Auth.fedratedSignIn()

### ISSUE THREAD

**Issue by MinaSamir11** [aws-amplify/amplify-js#11517]
### On which framework/platform would you like to see this feature implemented?

React Native

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

I need to add a user after being added to the identity pool, to be founded in the user pool also, with username, and email. 

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by nadetastic** [comment]
Hi @MinaSamir11 thank you for opening this issue. When you are using `Auth.federatedSignIn`, which process are you using? Note that the behavior you are using is expected if you are first getting tokens from google then sending them to Cognito, [as described here](https://docs.amplify.aws/lib/auth/advanced/q/platform/js/#google-sign-in-react).

However, if you call with just the provider parameter, `Auth.federatedSignIn({provider: 'Google'})` then you should see a user created in the user pool.

**Comment by MinaSamir11** [comment]
Yes that exactly as you said, but when i use provider Google i must have to install google in coginto with web client id. but i’m using the react native, then i have to behave the google auth login as native mobile experience, and use mobile sdk for auth. ,when i get token from sdk and send through provider ‘google’ and exipre token . it create user in identity pool only. but i need this user to be created also on the cognito user pool as the same basic flow of register user with their email and password !!

**Comment by nadetastic** [comment]
Got it @MinaSamir11, thanks for the clarification - it sounds like you are experiencing expected behavior. I'll discuss with the team and provide you with an update soon.

**Comment by nadetastic** [comment]
@MinaSamir11 following up here - after discussing with the team, your request sounds pretty similar to an existing feature request here - https://github.com/aws-amplify/amplify-js/issues/4008

I understand that you would like to federate with Cognito in a way that creates a UserPool user without the need to use the Cognito Hosted UI. The Cognito team is aware of this request, and have been making efforts around it. Im unable to provide an ETA at this time however I recommend that you subscribe to issue https://github.com/aws-amplify/amplify-js/issues/4008 for on going and future updates.

I will close this issue out to consolidate this request with https://github.com/aws-amplify/amplify-js/issues/4008

Thanks!
