### ISSUE TITLE
awsmobile appsync enable forces schema creation

### ISSUE THREAD

**Issue by oste** [aws-amplify/amplify-js#1151]
**Do you want to request a feature or report a bug?**
Feature

**What is the current behavior?**
When running `awsmobile appsync enable` awsmobilejs/backend/appsync is created with default comment and events schema and data tables.

**What is the expected behavior?**
It would be great if it was possible to start with an empty "Custom Schema" in the same way this is possible when choosing Create new API from the AppySync console.

Currently it seems you would have to create the sample schema then delete DynamoDB tables and adjust the schema and data sources accordingly.

Main reason this would be nice is to take advantage of the `awsmobile push` and `awsmobile pull` features so AppSync development doesn't have to be done in the AWS console. It seems like this is not possible when choosing "Manual Configuration" explained here https://aws.github.io/aws-amplify/media/api_guide#manual-configuration

**Comment by jordanranz** [comment]
Hello oste, thanks for submitting this feature request. This is actually something we are currently working on for the next version of our CLI. We will update this issue when the feature has been implemented.

**Comment by oste** [comment]
Any updates on this feature?

**Comment by jordanranz** [comment]
@oste, apologies for the late response. This feature should now be implemented with the new Amplify CLI.

Here are the usage docs:
https://aws-amplify.github.io/docs/cli/init?sdk=js

and here are some schema specific docs related to your question:
https://aws-amplify.github.io/docs/js/api#updating-your-graphql-schema

I will close this for now. Please reopen if you have any related questions or concerns.
