### ISSUE TITLE
I am using inidan number +9198*****270 in aws amplify to sign in. it gives me error of invalid format. is there a way that i can specify country for the phone number.

### ISSUE THREAD

**Issue by workforfilmsGithub** [aws-amplify/amplify-js#1152]
Do you want to request a feature or report a bug?

What is the current behavior?

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

What is the expected behavior?

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by powerful23** [comment]
Hey can you check if the error comes from the http request sent to the Cognito service? I think it's not an error from the library.

**Comment by jordanranz** [comment]
Could you help us understand the steps to reproduce the issue that you are experiencing. I am having trouble understanding where the invalid format error occurs for you. 

- Is this during sign up or sign in?
- Are you using the withAuthenticator HOC?
- Which versions of Amplify are you using?

**Comment by jordanranz** [comment]
Going to close this due to inactivity. Please feel free to reopen if you are still experiencing this issue.
