### ISSUE TITLE
 '@aws-amplify/interactions' does not contain a default export (imported as 'Interactions'). 

### ISSUE THREAD

**Issue by skullpunks** [aws-amplify/amplify-js#11529]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Not applicable

### Amplify Categories

Not applicable

### Environment information

<details>

./node_modules/aws-amplify-react/lib-esm/Interactions/ChatBot.js
Attempted import error: '@aws-amplify/interactions' does not contain a default export (imported as 'Interactions'). 

Versions:
@aws-amplify/interactions": "^5.2.0"
    "aws-amplify": "^4.3.4",

```
# Put output below this line


```

</details>

### Describe the bug

./node_modules/aws-amplify-react/lib-esm/Interactions/ChatBot.js
Attempted import error: '@aws-amplify/interactions' does not contain a default export (imported as 'Interactions').

### Expected behavior

Try to use Chatbot

import { Amplify } from 'aws-amplify';
import { ChatBot } from "aws-amplify-react";
import { AWSLexV2Provider } from '@aws-amplify/interactions';

Amplify.addPluggable(new AWSLexV2Provider());
Amplify.configure(awsconfig);

### Reproduction steps

NA

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by nadetastic** [comment]
Hi @skullpunks thank you for opening this issue. It looks like you are using the legacy UI package for Amplify React. I am curious where the import error is coming from, and due to that have you had a chance to review the sample app as [described here](https://github.com/aws-amplify/amplify-ui/blob/legacy/legacy/aws-amplify-react/README.md#sample-react-app)?

**Comment by nadetastic** [comment]
Hi @skullpunks following up here, when setting a simple app with Interactions as described in [our documentation](https://docs.amplify.aws/lib/interactions/getting-started/q/platform/js/). I am not able to see the error you face. Can you confirm if you are still experiencing this issue? If so could you also confirm the questions above?

**Comment by nadetastic** [comment]
@skullpunks going to close this issue out for now. If you still have questions around this, let me know and I can re-open to continue discussing.

Thanks!
