### ISSUE TITLE
Storage.get() url should dispaly the custom domain instead of the bucket name

### ISSUE THREAD

**Issue by BThato2** [aws-amplify/amplify-js#11533]
### Is this related to a new or existing framework?

Angular, React, Next.js

### Is this related to a new or existing API?

Storage

### Is this related to another service?

S3

### Describe the feature you'd like to request

The use case is if I do the 

  const result = await Storage.get("hendrik-schlott-eItFTPsvKTs-unsplash(2).jpg", { 
        level:"public",
        expires: 60 * 60 * 24*7, // 24 hours in seconds
    });
       console.log(result)
       
 Url gets singed, so when access the url Image on the browser I can see the underlying hosting provider, which I dont want the users to know underlying hosting provider but see the customer domain
 
 e.g  domain name (https://example.com/)) instead of displaying the bucket name ([https://bucketName.s3.us-east-1.amazonaws.com/ ] in the signed URLs?
 
 

### Describe the solution you'd like

Would like the user not to be able to see the hosting provider(the bucket name) that I am using but the domain name when accessing the signed url  

### Describe alternatives you've considered

-------

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by nadetastic** [comment]
Possibly related to https://github.com/aws-amplify/amplify-js/issues/3851

**Comment by nadetastic** [comment]
Hi @BThato2 im going to go ahead and close this in favor of tracking this request on #3851 . If you have any additional questions, please feel free to follow up on that issue. Thanks!

**Comment by BThato2** [comment]
There isnt much difference from  #3851, just did not see that this issue was opened before
