### ISSUE TITLE
Dynamic Lex Bots

### ISSUE THREAD

**Issue by brecistoptal** [aws-amplify/amplify-js#11534]
### Amplify CLI Version

11.0.0

### Question

1. Says bot is not available even if I hard-code details in aws-exports. I'm using your `waitUntilBotAvailable` function, and it says it's available, but your chatbot UI says the bot doesn't exist.

2. Can I not build a bot on the front-end, and use it dynamically? Or do I need to hard-code every bot in aws-exports. I have different chatflows, that are dynamic, and I would like to spin up unique bots at runtime.

Using React + TypeScript

**Comment by nadetastic** [comment]
Hi @brecistoptal thank you for opening this issue. You mention that you are using a UI component for with your application. Can you clarify that it is the`<ChatBot />` [component that is provided by the legacy UI library for React](https://github.com/aws-amplify/amplify-ui/blob/legacy/legacy/aws-amplify-react/README.md#interactions---chatbot)?

**Comment by brecistoptal** [comment]
Yep, I'm using that, but only as a last resort.

I built my own custom UI and am getting the same response when I use the `Interactions.send` function.

**Comment by nadetastic** [comment]
@brecistoptal I'm working to reproduce this issue and wanted to clarify a couple of things:
- Are you using Lex V1 or Lex V2?
- If using Lex V1, did you first create the Bot in the console or did you use the Amplify CLI?
- For Manual setup of V1, or if using V2, can you confirm the config is similar to the documentation [as described here](https://docs.amplify.aws/lib/interactions/getting-started/q/platform/js/#manual-setup)?

**Comment by brecistoptal** [comment]
Confirming with the back-end dev what the backend is doing.

But we are spinning up the bot on the front-end, using this library `@aws-sdk/client-lex-models-v2`.

The bot is then available in the console, if we check.

And we have the `aws-exports` config with the following:

```    "Interactions": {
        "bots": {
...
```
Which used to work, if we hard-code the botname/botId. But now that isn't working, as described above.

But my bigger concern is that we won't be able to spin up dynamic bots at runtime. Do we have to know the flow for each bot beforehand, and hard-code the botId in the config?

**Comment by nadetastic** [comment]
@brecistoptal Just did a bit of testing I'm not having any issues with the V1 (via CLI and manually) or V2 type of bots.

What thing that can cause this issue, is if the bot name that you are providing when calling `Interactions.send("<bot-name>",input)` doesn't match the name of the bot listed in your config as well as the name that is seen when viewing through the console. If any one of these are incorrect, you will get the error message "Bot <bot-name> does not exist"

```js
/* config */
Amplify.configure({
  ...,
  Interactions: {
    bots: {
      BookTrip: {. // <== This should match
        name: 'BookTrip', // <== This should match
        ...
      },
    }
  }
})
```
```js
/* App.js */
Interactions.send(
    "BookTrip", // <== This should match
    input
)
```
The three sections above should match the name of the bot as seen in the console.

**Comment by brecistoptal** [comment]
I can confirm the names are correct, however, they are `-` delimited. Not sure if `-`'s would break the bot name. But it worked before.

**Comment by brecistoptal** [comment]
What about dynamic bots at runtime? That's sort of the bigger concern, because I had this working at some point.

I'm curious, if I built a UI to build a flow with intents, etc, can not only create the bot at runtime, but give myself access to it in the aws-config? Because the bot is creating fine and I can see it in the console. But the ID/name of the bot, wouldn't be configured in the aws-config, so I can't USE the newly created bot at runtime,

**Comment by nadetastic** [comment]
@brecistoptal Theoretically, creating a bot dynamically should work fine, as long as the bot is created in time to be registered with Lex, then you would need to update your config (`Amplify.configure()`) to include the new bot After it has been created.

**Comment by nadetastic** [comment]
@brecistoptal wanted to follow up - if you still had any questions, let me know.

**Comment by brecistoptal** [comment]
Sorry, I figured it out, thanks!
