### ISSUE TITLE
No callback from federated logins when app is saved to HomeScreen in iOS and Android.

### ISSUE THREAD

**Issue by michaelcuneo** [aws-amplify/amplify-js#1154]
Do you want to request a feature or report a bug? BUG

What is the current behavior? Authenticator works with federated logins for Facebook and Google inside the browser on iOS and Android. If I add my app to the HomeScreen federated sign in's never come back from the call out... it will open a Facebook window to process the login request, authorise, but never return to the app. 

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

What is the expected behavior?

Expecting it to return to the app, and log me in successfully.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by jordanranz** [comment]
Hey @michaelcuneo,

Are you still experiencing this bug with the latest version of Amplify? There was no version posted in the original issue. Also, which framework are you using?

**Comment by powerful23** [comment]
Closing this due to no further response?

**Comment by michaelcuneo** [comment]
I'm not sure why I missed this, but I believe I solved it eventually. I'll double check with my records here and see what I can find.
