### ISSUE TITLE
Storage.Put returns 403 for users who is in a user group

### ISSUE THREAD

**Issue by qinbyd** [aws-amplify/amplify-js#11541]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

GraphQL API

### Amplify Categories

auth, storage, api

### Environment information

<details>

```
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
    Memory: 20.39 GB / 31.84 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.14.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.51)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @aws-amplify/ui-react: ^5.0.2 => 5.0.2
    @aws-amplify/ui-react-internal:  undefined ()
    @aws-amplify/ui-react-storage: ^2.0.2 => 2.0.2
    @headlessui/react: ^1.7.13 => 1.7.15
    @heroicons/react: ^2.0.17 => 2.0.18
    @tailwindcss/aspect-ratio: ^0.4.2 => 0.4.2
    @tailwindcss/forms: ^0.5.3 => 0.5.3
    @tailwindcss/typography: ^0.5.9 => 0.5.9
    @tanstack/react-query: ^4.29.3 => 4.29.15
    @types/dompurify: ^3.0.2 => 3.0.2
    @types/react: ^18.0.28 => 18.2.13
    @types/react-dom: ^18.0.11 => 18.2.6
    @vitejs/plugin-react: ^3.1.0 => 3.1.0
    autoprefixer: ^10.4.14 => 10.4.14
    aws-amplify: ^5.3.1 => 5.3.1
    classnames: ^2.3.2 => 2.3.2 (2.3.1)
    compressorjs: ^1.2.1 => 1.2.1
    dompurify: ^3.0.2 => 3.0.3
    formik: ^2.2.9 => 2.4.2
    postcss: ^8.4.21 => 8.4.24
    quill-image-uploader: ^1.2.4 => 1.3.0
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    react-image-crop: ^10.0.9 => 10.1.4
    react-quill: ^2.0.0 => 2.0.0
    react-router-dom: ^6.10.0 => 6.13.0
    tailwindcss: ^3.3.1 => 3.3.2
    typescript: ^5.0.3 => 5.1.3
    uuid: ^9.0.0 => 9.0.0 (3.4.0, 8.3.2)
    vite: ^4.2.0 => 4.3.9
    yup: ^1.1.1 => 1.2.0
  npmGlobalPackages:
    @angular/cli: 14.1.0
    @aws-amplify/cli: 10.7.3
    @tadrop/editorjs-code: 2.8.0
    @tadrop/react-simple-resizer: 2.1.0
    npm: 8.14.0
```

</details>

### Describe the bug

I have given Auth Users `update, read` permission, but calling `Storage.put("test.txt", "Hello");` still gives me 403 error.
After several experiments, i noticed the issue only happens when the user is in a group, remove the user from any group, the issue will be gone and no 403 errors.

### Expected behavior

No 403 error for the storage put for auth users who are in a user group, since users in a group is also an auth (private) user.
Or could you kindly provide an instruction how to get around this during waiting for the fix, anyway to config grouped users also have the Storage.Put permission.

### Reproduction steps

1. amplify add storage
2. set Auth/Guest users permissions, let Auth update, read, let Guest Read
3. ci-inputs.json looks like this 
```
  "storageAccess": "authAndGuest",
  "guestAccess": [
    "READ"
  ],
  "authAccess": [
    "CREATE_AND_UPDATE",
    "READ"
  ],
  "trig
```

### Code Snippet

```javascript
Storage.put("test.txt", "Hello");

```

### Log output

<details>

```
{appname}-files60649-staging.s3.us-west-1.amazonaws.com/public/test.txt?x-id=PutObject:1     Failed to load resource: the server responded with a status of 403 (Forbidden)
ConsoleLogger.js:126 [DEBUG] 25:53.398 axios-http-handler ProgressEventisTrusted: truebubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}defaultPrevented: falseeventPhase: 0lengthComputable: falseloaded: 255returnValue: truesrcElement: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}target: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}timeStamp: 4905.699999928474total: 0type: "progress"[[Prototype]]: ProgressEvent
ConsoleLogger.js:122 [ERROR] 25:53.398 axios-http-handler - Request failed with status code 403
ConsoleLogger2._log @ ConsoleLogger.js:122
Show 1 more frame
Aws_restXml.ts:9275 Uncaught (in promise) AccessDenied: Access Denied
    at http://localhost:2002/node_modules/.vite/deps/chunk-FDTOAZIJ.js?v=66362245:41412:51
    at step (http://localhost:2002/node_modules/.vite/deps/chunk-ZTIZMG63.js?v=66362245:1577:19)
    at Object.next (http://localhost:2002/node_modules/.vite/deps/chunk-ZTIZMG63.js?v=66362245:1524:14)
    at fulfilled (http://localhost:2002/node_modules/.vite/deps/chunk-ZTIZMG63.js?v=66362245:1495:24)

</details>


### aws-exports.js

```

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_appsync_graphqlEndpoint": "https://5crwkou6kbba3fqxo45lszl6xq.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-bibl3fbixnd4tdiuanhxrrt46e",
    "aws_cognito_identity_pool_id": "us-west-1:479a2470-80cf-4c57-b176-663edaa3082e",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_ZwWYmboM1",
    "aws_user_pools_web_client_id": "5jrvoql88a6fsk3l2055gvcrfv",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "{appname}-files60649-staging",
    "aws_user_files_s3_bucket_region": "us-west-1"
};

export default awsmobile;
```

### Manual configuration

_No response_

### Additional configuration

run `aws cognito-idp describe-user-pool --user-pool-id us-west-1_ZwWYmboM1 --region us-west-1`
```
Unable to locate credentials. You can configure credentials by running "aws configure".
```

### Mobile Device

_No response_

### Mobile Operating System

_No response_

### Mobile Browser

_No response_

### Mobile Browser Version

_No response_

### Additional information and screenshots

_No response_

**Comment by nadetastic** [comment]
Hi @qinbyd thank you for opening this issue. It sounds like only users in groups are facing this issue - based on this, I wanted to point out that one of the prompts will be the method to "Restrict access by", with the options being

a) Auth and guest
b) Individual groups
c) Both

![Screenshot 2023-06-22 at 11 41 51 AM](https://github.com/aws-amplify/amplify-js/assets/87148442/f6b17a36-850d-488b-a23a-e724146b39b2)

You may need to select the option of "**Both**" when going through this, in order to also provide access to users in groups. Can you verify this?


- [Storage Access Permissions](https://docs.amplify.aws/cli/storage/overview/#s3-access-permissions)

**Comment by nadetastic** [comment]
@qinbyd glad to help and happy to hear it's working now! For the other app, i'm curious as well - it's possible that the app was created with an older version of the Amplify CLI? Another potential reason is that the permissions were manually added via the AWS Console. Either way, keep in mind if you decided to update the other app, you may need to follow the same steps as we have done here.

For now I will go ahead and close out this issue. If you do have any questions regarding the other application, please feel free to open up a new issue. Thanks!
