### ISSUE TITLE
SSR Cognito Authentication not work when accessing my site from another domain

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-js#11575]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.44 GB / 32.00 GB
    Shell: 3.4.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
    pnpm: 8.6.2 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Edge: 114.0.1823.55
    Safari: 16.3
  npmPackages:
    @apollo/client: ^3.7.16 => 3.7.16 
    @harlem/core: ^3.1.8 => 3.1.8 
    @neolithic-css/framework: ^1.4.5 => 1.4.5 
    @neolithic-css/toolkit: ^1.4.0 => 1.4.0 
    @nuxt/devtools: ^0.6.6 => 0.6.6 
    @nuxtjs/apollo: ^5.0.0-alpha.6 => 5.0.0-alpha.6 
    @types/jsdom: ^21.1.1 => 21.1.1 
    @types/lodash-es: ^4.17.7 => 4.17.7 
    @vueform/multiselect: ^2.6.2 => 2.6.2 
    @vueuse/core: ^10.2.1 => 10.2.1 
    @vueuse/head: ^1.1.26 => 1.1.26 
    @vueuse/motion: ^2.0.0 => 2.0.0 
    EventDispatcher: ^3.2.0 => 3.2.0 
    animated-scroll-to: ^2.3.0 => 2.3.0 
    aws-amplify: ^5.3.3 => 5.3.3 
    aws-appsync-auth-link: ^3.0.7 => 3.0.7 
    aws-appsync-subscription-link: ^3.1.2 => 3.1.2 
    core-js: ^3.31.0 => 3.31.0 
    cropperjs: ^2.0.0-alpha.1 => 2.0.0-alpha.1 
    crypto-browserify: ^3.12.0 => 3.12.0 
    dayjs: ^1.11.9 => 1.11.9 
    dompurify: ^3.0.4 => 3.0.4 
    graphql: ^16.7.1 => 16.7.1 
    graphql-tag: ^2.12.6 => 2.12.6 
    jsdom: ^22.1.0 => 22.1.0 
    jszip: ^3.10.1 => 3.10.1 
    lodash-es: ^4.17.21 => 4.17.21 
    mobile-detect: ^1.4.5 => 1.4.5 
    muku-ui: ^1.2.3 => 1.2.3 
    nprogress: ^0.2.0 => 0.2.0 
    nuxt: ^3.6.1 => 3.6.1 
    nuxt-jsonld: ^2.0.8 => 2.0.8 
    partial-gql: ^1.0.0 => 1.0.0 
    pica: ^7.0.0 => 7.0.0 
    prettier: ^2.8.8 => 2.8.8 
    purgecss: ^5.0.0 => 5.0.0 
    react: ^18.2.0 => 18.2.0 
    rollup-plugin-node-globals: ^1.4.0 => 1.4.0 
    sass: ^1.63.6 => 1.63.6 
    scroll-into-view-if-needed: ^3.0.10 => 3.0.10 
    sticky-sidebar: ^3.3.1 => 3.3.1 
    tiny-slider: ^2.9.4 => 2.9.4 
    ts-toolbelt: ^9.6.0 => 9.6.0 
    tslib: ^2.6.0 => 2.6.0 
    uuid: ^9.0.0 => 9.0.0 
    v-calendar: ^3.0.0-alpha.8 => 3.0.0-alpha.8 
    vee-validate: ^4.10.3 => 4.10.3 
    vue: ^3.3.4 => 3.3.4 
    vue-router: ^4.2.2 => 4.2.2 
    vuedraggable: ^4.1.0 => 4.1.0 
    yup: ^1.2.0 => 1.2.0 
    yup-locale-ja: ^1.0.0 => 1.0.0 
  npmGlobalPackages:
    @aws-amplify/cli: 12.0.3
    firebase-tools: 11.0.1
    graphql-auto-transformer: 1.3.1
    graphql-default-value-transformer: 2.0.1
    pnpm: 8.6.2
    vercel: 30.2.2
    wrangler: 2.0.6


```

</details>

### Describe the bug

When using Amplify Auth, I got the error message "The user is not authenticated" when accessing my site from another domain(by clicking an `<a>` tag within another domain which the `href` is the url of my site).

```ts
import { Amplify, Auth, withSSRContext } from 'aws-amplify'

Amplify.configure({ ...awsConfig, ssr: true })

let user
let authClass

if (process.server) {
  const req = useRequestEvent().node.req

  const { Auth } = withSSRContext({ req })
  authClass = Auth
} else {
  authClass = Auth
}

try {
  user = await authClass.currentAuthenticatedUser()
  console.log(user, 'Authenticated') // I got this after I refreshed the page or access directly from URL.
} catch (err) {
  user = undefined
  console.log(err, 'Not Authenticated') // I got this when accessing from another domain.
}
```

### Expected behavior

-

### Reproduction steps

-

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello, @yaquawa 👋 and thanks for opening this issue.  It sounds like you're able to sign in and authenticate without issue, but this error is only getting thrown on the _inital_  redirect from a separate domain (and goes away if you refresh).  Is that correct? Also, are you importing your `awsConfig` somewhere else or do you have it configured elsewhere in the file?

**Comment by yaquawa** [comment]
@cwomack yes, your understanding is correct. 

> are you importing your awsConfig somewhere else or do you have it configured elsewhere in the file?
Yes, of course. also I'm able to sign in and authenticate without issue on the client site.

**Comment by yaquawa** [comment]
Hello @cwomack, I would like to know if you could reproduce this issue.

**Comment by cwomack** [comment]
@yaquawa, apologies for the delayed response on this.  It looks like we could be documenting the default behavior of `cookieStorage`, `sameSite: lax` vs. `strict`, etc. Both this and #11350 appear to be describing the same thing, so we'll close this issue as a duplicate.  For an explanation of the expected/default behavior, please see [this comment](https://github.com/aws-amplify/amplify-js/issues/11350#issuecomment-1758581422) on that issue. We'd be happy to clarify things further if needed as well! 

In the mean time, we'll work on improving the documentation for behavior in v5.X of Amplify when using SSR via [this docs issue](https://github.com/aws-amplify/docs/issues/6000) (also referenced above) that I've opened for both of these related issues.
