### ISSUE TITLE
getBadgeCount return undefined and setBadgeCount is not triggered

### ISSUE THREAD

**Issue by MensurRasic** [aws-amplify/amplify-js#11601]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Push Notifications

### Amplify Categories

notifications

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 76.11 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.2.0 - /opt/homebrew/bin/node
    npm: 9.8.0 - ~/Documents/ReactNative/RN0.72/Menimo/node_modules/.bin/npm
    Watchman: 2023.05.15.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5
  npmPackages:
    @aws-amplify/analytics: ^6.0.16 => 6.3.2 
    @aws-amplify/rtn-push-notification: ^1.1.1 => 1.1.1 
    @babel/core: ^7.12.9 => 7.22.8 
    @babel/runtime: ^7.12.5 => 7.22.6 
    @react-native-async-storage/async-storage: ^1.19.0 => 1.19.0 
    @react-native-community/push-notification-ios: ^1.10.1 => 1.11.0 
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: ^5.2.14 => 5.2.14 (6.3.1)
    amazon-cognito-identity-js/internals:  undefined ()
    aws-amplify: ^5.3.3 => 5.3.3 
    aws-amplify-react-native: ^7.0.2 => 7.0.2 
    aws-sdk: ^2.1220.0 => 2.1413.0 
    react: 18.2.0 => 18.2.0 
    react-devtools: 4.25.0 => 4.25.0 
    react-devtools-core: 4.25.0 => 4.25.0 (4.27.8)
    react-native: 0.72.1 => 0.72.1 
    react-native-push-notification: ^8.1.1 => 8.1.1 
  npmGlobalPackages:
    @aws-amplify/cli: 12.1.1
    ios-deploy: 1.12.1
    jest: 29.0.3
    jetifier: 2.0.0
    npm: 9.6.6
    react-devtools-core: 4.25.0
    react-devtools: 4.27.1
    react-native-cli: 2.0.1
    react-native-rename: 2.9.0
    react-native: 0.72.1

```

</details>

### Describe the bug

I am trying to get and set the badge count upon sending a push notification using AWS pinpoint on a physical device (Android).

The idea is to get the badge count on notification received in background and set the new value.

```js
Notifications.Push.onNotificationReceivedInBackground(async notification => {
  console.log('onNotificationReceivedInBackground : ', notification);

  console.log('badgeCount : ');
  try {
    const badgeCount = await Notifications.Push.getBadgeCount();
    console.log(badgeCount);
  } catch (error) {
    console.log(error);
  }
});
```

Unfortunately the `await Notifications.Push.getBadgeCount()` is returning undefined : 

![Screenshot 2023-07-10 at 12 08 43 PM](https://github.com/aws-amplify/amplify-js/assets/23143508/fe9c3cf7-00d8-4a66-be7b-324da204065b)

### Expected behavior

Get the current value of the badge count as [mentioned in the documentation](https://docs.amplify.aws/lib/push-notifications/app-badge-count/q/platform/react-native/#get-the-current-badge-count).

### Reproduction steps

1. Set up [Notifications.Push.onNotificationReceivedInBackground](https://docs.amplify.aws/lib/push-notifications/interact-with-notifications/q/platform/react-native/)
2. Push a notification with [pinpoint](https://docs.aws.amazon.com/pinpoint/latest/userguide/settings-push.html)
3. Receive notification in the background
4. Expect to get the current value of the badge count

### Code Snippet

```javascript
Notifications.Push.onNotificationReceivedInBackground(async notification => {
  console.log('onNotificationReceivedInBackground : ', notification);

  console.log('badgeCount : ');
  try {
    const badgeCount = await Notifications.Push.getBadgeCount();
    console.log(badgeCount);
  } catch (error) {
    console.log(error);
  }
});

```

### Log output

<details>

```
onNotificationReceivedInBackground :  {"body": "123", "data": {"pinpoint.campaign.campaign_id": "_DIRECT", "pinpoint.notification.body": "123", "pinpoint.notification.silentPush": "0", "pinpoint.notification.title": "test", "pinpoint.openApp": "true"}, "fcmOptions": {"channelId": "PINPOINT.NOTIFICATION"}, "title": "test"}
badgeCount :
undefined


```

</details>

### Mobile Device

Samsung Galaxy A03s

**Comment by nadetastic** [comment]
Related - https://github.com/aws-amplify/amplify-js/issues/11596

**Comment by nadetastic** [comment]
Hi @MensurRasic thank you for opening this this issue. Im currently investigating and out of curiosity - you mentioned that this is happening on android, have you seen if this is also happening on iOS?

**Comment by MensurRasic** [comment]
@nadetastic No I haven't tested yet on iOS, I will keep you posted when I do!

**Comment by nadetastic** [comment]
@MensurRasic after discussing internally with the team, I'll go ahead and close this issue in favor of https://github.com/aws-amplify/amplify-js/issues/11596

If you have any additional questions/comments or updates, please feel free to share on the other issue. Thanks!
