### ISSUE TITLE
Storage.get returns correct URL, but *sometimes* setting it as source-uri for Image gives a 404

### ISSUE THREAD

**Issue by DaryBeattie** [aws-amplify/amplify-js#11629]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Storage

### Amplify Categories

storage

### Environment information

<details>

```
  System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 34.60 GB / 63.69 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (114.0.1823.82)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @babel/core: ^7.20.0 => 7.22.1 
    [redacted]
  npmGlobalPackages:
    @aws-amplify/cli: 11.0.0
    aes-cli: 1.3.0
    csvtojson: 2.0.10
    eas-cli: 3.15.1
    expo-cli: 6.3.10
    npm-check-updates: 16.3.8
    npm: 9.6.7
```

</details>

### Describe the bug

I ask for an image that I know (100% sure!) exists, and Storage.get() returns me a URL for it. But for some images, when I take the result from Storage.get() and set it as the source-uri of a react-native `<Image>` or `<BackgroundImage>`, it simply doesn't render. I've added an onError and I find out from the nativeEvent that there's a "Failed to load [followed by the super-long URL]" error message and a responseCode of 404.

Now, I know this image exists. And in fact from other clients using my react-native app, the same image shows up just fine (pulled from the same object-path in the database).

It's just that sometimes, the images give a 404.

I cannot seem to find any pattern to it. It's not that the images are big, they're like 100-150kb. Some have spaces in the filenames and some do not. I compare the permissions of the files and all their attributes to the ones that consistently work, and they're all identical. They're in the same bucket too. And yes, I've made sure the image has a height/width specified, as some people on the the web have indicated not-specifying those can cause issues.

I've attached my EXACT code and logs below, not just "sample" code.

Now this works for >95% of the images most of the time. But I do get those weird 404s and I cannot explain them.

*** EDIT!! *** Turns out my mime-types were wrong with my file extensions, which caused my code to request the photo by the wrong extension.
Also, for any future readers, this entire thing can mostly be replaced with an `<S3Image>` component.

### Expected behavior

I expect Storage.get() to return me a URL for a photo that can be loaded, and for the `<Image>` to be able to load it from that source-URI, 100% of the time.

### Reproduction steps

For my case, I load up my app and go to the screen that displays images. I'm not sure how to explain it other than that.

### Code Snippet

```javascript
// Put your code below this line.
const BackgroundCardImage = ({ profile }) => {
  const [profilePhotoLoadedURL, setProfileLoadedPhotoURL] = useState();

  useEffect(() => {
    Storage.get(profile.avatarURL).then((result) => {
      console.log("BackgroundCardImage: loaded: ", result);
      setProfileLoadedPhotoURL(result);
    });
  }, [profile]);

  return (
    <ImageBackground
      source={{ uri: profilePhotoLoadedURL }}
      style={styles.image}
      onError={(error) => {
        console.log("ERROR loading photo. ResponseCode=" + error?.nativeEvent?.responseCode + ": " + error?.nativeEvent?.error);
      }}
    >
      [[omitted; a <LinearGradient> over the bottom of the image and 2 nested <View>s to that.]]
    </ImageBackground>
  );
};
```

### Log output

<details>

```
// Put your logs below this line
 LOG  BackgroundCardImage: loaded:  https://profiles144014-dev.s3.us-east-1.amazonaws.com/public/photos/large/Susan-Williams.png?[[super long bunch of params, don't see anything weird here]]
 LOG  ERROR loading photo. ResponseCode=404: Failed to load https://profiles144014-dev.s3.us-east-1.amazonaws.com/public/photos/large/Susan-Williams.png?[[exact same params]]
```

</details>

### Mobile Device

iPhone13Pro

### Additional information and screenshots

Using ExpoGo or my iOS build I experience the same issue, but for different images!

**Comment by DaryBeattie** [comment]
Closing this; there was an error with my data. The file extension was wrong. So sorry for the report; please delete this issue-report.

**Comment by cwomack** [comment]
Thanks for letting us know, @DaryBeattie.  Feel free to open a new issue anytime you feel there's a bug or join us on our Discord server for additional help from the Amplify community!
