### ISSUE TITLE
Plus sign in password handled differently than other symbols

### ISSUE THREAD

**Issue by clintfoster** [aws-amplify/amplify-js#1164]
Do you want to request a feature or report a bug?
Bug.

What is the current behavior?
The Cognito [User Guide](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-policies.html) says:
>The following characters are allowed in passwords, regardless of the policy you set: uppercase and lowercase letters, numbers, and the special characters listed below...
>?^ $ * . [ ] { } ( ) ? - " ! @ # % & / \ , > < ' : ; | _ ~ `

Notice the plus sign is _not_ included. However, it does work if another special character is also present. For example, Cognito accepts the first and last passwords below, but not the one in the middle:

- `MyPassword1?` - OK
- `MyPassword1+` - FAIL
- `MyPassword1?+` - OK

The error returned by Cognito for passwords containing the plus sign as the only symbol is:

>InvalidPasswordException: Password did not conform with policy: Password must have symbol characters

Is this the intended behavior? If so, it should be documented. However, this exception will be difficult to explain to end users and validate in clients, e.g. with a regular expression. 

What is the expected behavior?
The plus sign should be allowed as a special character even when it is the only special character.

**Comment by jordanranz** [comment]
Hi @clintfoster, thank you for submitting this issue.

As you mentioned Cognito does _not_ include the plus sign in their documentation for what is **required**, so it makes sense that the middle attempt using solely the plus sign in the password would fail. Furthermore, the set Cognito uses is not an exhaustive list of all special characters so characters like '=' would also be subject to the issue you are experiencing. 

I believe this may just be unclear documentation as the set mentioned below for **Require special character** is the list of characters required in the password whereas the statement above mentions  "The following characters are allowed". It seems other special characters not listed are allowed but not required.

Let me clear this up with someone from the Cognito team.

**Comment by jordanranz** [comment]
Cognito followed up saying they would add clarification to their documentation here. '+' and '=' are currently valid _allowed_ characters for a password but they are not **required** for the special character check.

**Comment by clintfoster** [comment]
Thanks for the quick response. I think we will need to switch from a regular expression to a custom JavaScript validator for the password input field. But if anyone reading this can suggest a regular expression that requires 8 characters, upper, lower, number, symbol and `+` or `=` only in combination with another symbol, that would be interesting...
