### ISSUE TITLE
For Interactions, AWSLexProvider.ts should send more information to the onComplete() callback

### ISSUE THREAD

**Issue by danilop** [aws-amplify/amplify-js#1166]
Do you want to request a feature or report a bug?

This is a feature request, to improve the usability of Interactions with Amazon Lex.

What is the current behavior?

For Interactions, the AWSLexProvider.ts is only reporting back `data.slots` to the callback function, but there is much more info that is returned by the Amazon Lex `postText` API, such as `intentName` and `sessionAttributes`. This is especially useful for fulfillment that not invoke a Lambda function, but return parameters to the client. In that case, currently, you only see the slots and have no way to understand which intent was selected by Amazon Lex.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

What is the expected behavior?

I would suggest giving back to the onComplete callback **all** the information returned by the `postText` API, and not just the `slots`.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

This behavior is in the master branch now, I am planning to propose a PR to have the expected behavior described earlier.

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by asmiki** [comment]
How can we send session variables to the interaction message? I need to pass a user id to handle a database call through lambda, but there is no way it can be done. PostText command of Amazon Lex Runtime obviously supports session variables, but that part is omitted from AWSLexProvider.ts https://docs.aws.amazon.com/lex/latest/dg/API_runtime_PostText.html

Any workaround?

**Comment by asmiki** [comment]
@danilop were you able to work around this?

**Comment by howdyhyber** [comment]
Any updates about this?

**Comment by ashwinkumar6** [comment]
Hi @danilop @asmiki this feature has been released and merged.
Please try out this our in the latest version and let us know
