### ISSUE TITLE
Multiple social auth redirect url

### ISSUE THREAD

**Issue by looksbo** [aws-amplify/amplify-js#11689]
### Amplify CLI Version

11.1.1

### Question

Background. 
I have a react application that uses Amplify with FB and Google authentication. I currently have setup 2 redirect URIs, one for production and the other one LocalHost. 
But I also want to test on mobile that is connected to the same network as my dev computer. The host for the device on mobile is not LocalHost but something along the lines of 192.0.00 etc. Right now it is not possible to signin on mobile when testing the project because I don't have the host of the mobile set up as a redirect URL. is there a way to simply redirect all non production signings to whatever location it came from

**Comment by israx** [comment]
Hello @looksbo

If you are in a web environment, you can use `window.location.href` to handle your redirect logic. If you are using React Native you can follow the RN [guide](https://docs.amplify.aws/lib/auth/social/q/platform/react-native/#redirect-urls) to setup your redirect signIn/out logic.

**Comment by cwomack** [comment]
@looksbo, let us know if the documentation and comments above help resolve the issue you're experiencing.

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
