### ISSUE TITLE
I have a problem when I import 'aws-amplify' in a boot file from quasar.js

### ISSUE THREAD

**Issue by daviddevcas** [aws-amplify/amplify-js#11712]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue, Not applicable

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

 System:
    OS: macOS 13.4.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 255.06 MB / 16.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
  Managers:
    Homebrew: 2.5.0 - /usr/local/bin/brew
    pip3: 23.1.2 - /Library/Frameworks/Python.framework/Versions/3.11/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 14.0.3 - /usr/bin/gcc
    Git: 2.40.0 - /usr/local/bin/git
    Clang: 14.0.3 - /usr/bin/clang
    Curl: 7.88.1 - /usr/bin/curl
  Servers:
    Apache: 2.4.56 - /usr/sbin/apachectl
  Virtualization:
    Docker: 23.0.5 - /usr/local/bin/docker
  IDEs:
    Vim: 9.0 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Perl: 5.30.3 - /usr/bin/perl
    Python3: 3.11.3 - /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
  Databases:
    SQLite: 3.39.5 - /usr/bin/sqlite3
  Browsers:
    Chrome: 115.0.5790.114
    Safari: 16.5.2

</details>

### Describe the bug

When I import "aws-amplify" to my boot file from Quasar.js, I have the following problem:

Boot error `[Quasar]: Reference error: Cannot find variable: global node_modules/amazon-cognito-identity-js/node_modules/buffer/index.js - index.js:43 __require2 - chunk-S5KM4IGW.js:18 Module code - AuthentiHelper.js:6`

### Expected behavior

I expected the boot to work well, as I need to use the authenticator 

### Reproduction steps

quasar dev

### Code Snippet

```javascript
// Put your code below this line.

```
`import { Amplify, Auth } from 'aws-amplify';
import awsconfig from 'src/aws-exports';

export default async ({ app }) => {
  Amplify.configure(awsconfig)
  app.config.globalProperties.$auth = Auth;
};
`

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!

**Comment by daviddevcas** [comment]
> Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.
> 
> Thank you!

Hi,  I forgot this issue, mmm, my package.json is it: 
<img width="1680" alt="Screenshot 2023-08-21 at 15 36 11" src="https://github.com/aws-amplify/amplify-js/assets/74804591/d81f3489-4a47-4988-90c7-052a6fd17a8b">
