### ISSUE TITLE
Hub auth events don't appear to be emitted on a page reload

### ISSUE THREAD

**Issue by eoliphan** [aws-amplify/amplify-js#1171]
I'm not sure if this is a bug or works as intended.  I'm trying to use hub events to sync up my app's local database with the user's authentication status.  I've so far only been able to see _signIn_ events when I'm using the Authenticator component to create the login form, directly on my page.  

If I say refresh the page, I'd sort of expect to see it at that point, since amplify/cognito have saved off the users login in local storage.  Though strictly speaking, I guess the event is not 'happening' at that point, so perhaps another one like, 'signedIn' or something might be better.   However, in the case of the hosted UI, when you're redirected back to the page, it is not _signIn_ is not emitted as well.  In that case, it seems like that should definitely happen.

**Comment by powerful23** [comment]
@eoliphan good point. We should enhance the Hub category to emit auth events on page refreshing. Will mark this as enhancment

**Comment by jkeys-ecg-nmsu** [comment]
@powerful23 is the behavior described in OP still happening? We're trying to pin down some weird auth issues (e.g. getting random "missing credentials in config" errors that seemingly don't actually break anything besides the user experience) and I'm wondering if this might be related.

**Comment by powerful23** [comment]
@eoliphan hi just want to do a check if you are still have this issue with the current version of Amplify as we have done a refactor on the Hub category.

**Comment by powerful23** [comment]
Closing the issue. Please let me know if you want to reopen it.

**Comment by pbasista** [comment]
> check if you are still have this issue with the current version of Amplify

Yes, the behavior when no `Hub` event is emitted on "auth" channel when the user details are already available in the local cache (either local storage or cookies) and the page is reloaded is still present with `@aws-amplify/auth@3.2.8`.
