### ISSUE TITLE
Sign In component has unexpected behaviour when signing in with `Enter` key

### ISSUE THREAD

**Issue by stonecauldron** [aws-amplify/amplify-js#1175]
#### Do you want to request a feature or report a bug?
bug

#### What is the current behavior?

We are using the `withAuthenticator` HOC to provide our app with authentication capabilities.

We changed the base HOC the following way:

```jsx
export function createWithMyAuthenticator(awsConfig) {
  Amplify.default.configure(awsConfig);
  return (comp) =>
    withAuthenticator(comp, false, [
      <SignIn />,
      <ConfirmSignIn />,
      <VerifyContact />,
      <SignUp />,
      <ConfirmSignUp />,
      <ForgotPassword />,
    ]);
}
```
After we fill the username and password of the user the problem occurs when we try to sign in not by clicking the sign in button but by submitting the sign in form with the `Enter` key.

After pressing the `Enter` key a warning appears with the message `Username cannot be empty` even if it is actually not empty. This issue does not prevent login however and if the username and password are correct we can proceed to the application itself after a short delay.

The bug seems to be related to the arguments of the `authenticatorComponents` parameter i.e.
```jsx
[
      <SignIn />,
      <ConfirmSignIn />,
      <VerifyContact />,
      <SignUp />,
      <ConfirmSignUp />,
      <ForgotPassword />,
]
```
since this issue disappears if we use `withAuthenticator` without providing any arguments to the `authenticatorComponents` parameter.

#### What is the expected behavior?
The warning saying `Username cannot be empty` should not appear unless the username is actually empty.

#### Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
I am getting the bug with the following setup:
```
macOS 10.13.5
"electron": "2.0.4"
"aws-amplify": "0.4.8",
 "aws-amplify-react": "0.1.54",
```

**Comment by stonecauldron** [comment]
Hello,

Were you able to reproduce this bug?

In any case thank you for your time

**Comment by stonecauldron** [comment]
@powerful23 Thank you very much for looking into the problem and solving the issue! 👍

**Comment by powerful23** [comment]
@stonecauldron My pleasure! Thanks for giving the feedback.
