### ISSUE TITLE
How to get user_identity_id in DynamoDB trigger in order to save a private file on storage?

### ISSUE THREAD

**Issue by maziarzamani** [aws-amplify/amplify-js#11761]
### How did you install the Amplify CLI?

yarn

### Amplify CLI Version

12.0.0

### What operating system are you using?

macOS

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made.

### Describe the bug

I am trying to generate a PDF based on a users mutation, which is then saved to the Amplify Storage (S3) [privately](https://docs.amplify.aws/lib/storage/configureaccess/q/platform/js/). This requires that the user_identity_id is known, otherwise the folder cannot be created or found private/<user_identity_id>/<filename>.

I was quite surprised that it isn't possible to get this piece of information bidirectionally. What to do?

### Expected behavior

That I can get the user_identity_id

### Reproduction steps

1. Create a model
2. Setup a DynamoDB lambda trigger
3. Create a random file
4. Attempt to save the file on Amplify Storage (S3) in a private manner

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by nadetastic** [comment]
Hi @maziarzamani following up here - from both your and @ykethan comments, that is the recommend way to get the specific users identity id by using `Auth.currentCredentials()` to get the IdentityID and build the key for private or protected files. I'll go ahead and mark this issue as resolved as continue tracking this as a documentation improvement here - https://github.com/aws-amplify/docs/issues/5672

If you still have questions about this, let me know.
