### ISSUE TITLE
API methods in offline returning wrong error

### ISSUE THREAD

**Issue by ArmorDarks** [aws-amplify/amplify-js#1176]
## Do you want to request a feature or report a bug?

Report a bug

## What is the current behavior?

When API methods used (saying, `API.put`) offline, they will result in error with message `Network Error`, without code and name

## What is the expected behavior?

Expected to receive an Error in same format as for other AWS-related errors — an Object with following signature:

```js
{
  code: 'NetworkError',
  name: 'whatever',
  message: 'whatever'
}
```

**Comment by ArmorDarks** [comment]
nope

**Comment by chrisbonifacio** [comment]
Closing this issue as stale since there has been no traffic, and it reads more as an issue than feeture request.

Many changes have been made to the library since this issue was opened. If anyone is experiencing this or similar issues, please open a new issue with steps to reproduce.
