### ISSUE TITLE
Push notification do not display on android API > 23, RN 0.56

### ISSUE THREAD

**Issue by ddemoll** [aws-amplify/amplify-js#1177]
Bug report

What is the current behavior?

Push notifications are logged to console, but do not display on screen on Android 26. I cannot use RN 0.56 Android 26 with this library.

Will this library support Android 8.0 (API level 26) by [August 1, 2018](https://developer.android.com/distribute/best-practices/develop/target-sdk)

**Comment by powerful23** [comment]
@ddemoll we will let the library support Android 8.0 but for now I can't tell you the exact timeline for that.

**Comment by reedyrm** [comment]
I hate to leave a "same for me" post here, but I am encountering the same issue.  I started looking into the android debug logs for my simulator and found this error

" No Channel found for pkg=<com.myapp>"

Debug logs snippets
```
07-08 13:54:33.391 17175-17383/<com.myapp> I/RNPushNotificationMessagingService: Message From: 291627952913
07-08 13:54:33.393 17175-17175/<com.myapp> I/emit: notification emit
07-08 13:54:33.395 17175-17175/<com.myapp> I/RNPushNotificationMessagingService: sendNotification: Bundle[{pinpoint.openApp=true, userInteraction=false, pinpoint.notification.title=Test, pinpoint.notification.body=Test, id=1338474920, pinpoint.campaign.campaign_id=_DIRECT, pinpoint.notification.silentPush=0}]
07-08 13:54:33.406 2136-2647/? E/NotificationService: No Channel found for pkg=<com.myapp>, channelId=null, id=1338474920, tag=null, opPkg=<com.myapp>, callingUid=10085, userId=0, incomingUserId=0, notificationUid=10085, notification=Notification(channel=null pri=1 contentView=null vibrate=[0,300] sound=content://settings/system/notification_sound defaults=0x4 flags=0x10 color=0x00000000 category=call vis=PRIVATE)
```

I started googling around for the issue and ran into a few posts of other libraries running into the same problems and what their solutions were:
* https://github.com/xamarin/GooglePlayServicesComponents/issues/76
* https://github.com/wix/react-native-notifications/issues/175
* https://github.com/wix/react-native-notifications/issues/194

Then, I did some digging into the Android code and a channelId needs to be set on the Notification to be compatiable with SDK 26.  

https://github.com/aws/aws-amplify/blob/2e03162f40cc6c3e3fbf874a82821e845c9bb1a1/packages/aws-amplify-react-native/android/src/main/java/com/amazonaws/amplify/pushnotification/modules/RNPushNotificationHelper.java#L181

This  StackOverflow answer outlines the potential fixes by setting the ChannelId (https://stackoverflow.com/questions/43093260/notification-not-showing-in-oreo/43093261#43093261)

I dont have time to work on this, but please someone use this and create a PR.  If not, I'll probablly get to this next week.

**Comment by powerful23** [comment]
Closing the issue. Feel free to reopen if you still have this issue.
