### ISSUE TITLE
Allow options for generating CheckSum while uploading object using Storage category (i.e. CRC-32, SHA-256, etc.) 

### ISSUE THREAD

**Issue by muvashi** [aws-amplify/amplify-js#11776]
### Is this related to a new or existing framework?

Angular, React, React Native, Vue, Web Components, Next.js

### Is this related to a new or existing API?

Storage

### Describe the feature you'd like to request

When using S3 PubObjectCommand API, we can specify the CheckSumAlgorithm which generate the checksum in S3 that can be used later.

However, there is no option to generate the checksum via Amplify storage API call.

### Describe the solution you'd like

Option to pass ChecksumAlgorithm while using Storage.put() API call.

### Describe alternatives you've considered

.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by wiewiur667** [comment]
Thanks for quick action on that ticket. 

Do you know rough ETA? I need to put something in our system.

**Comment by cwomack** [comment]
Hello, @wiewiur667 👋 and thank you for opening this issue. I've marked it as a feature request at this time because we do not currently support passing `ChecksumAlgorithm` while calling the `Storage.put()` API.  I'll review this with the team internally and provide updates on any progress as it's made.

**Comment by tlmader** [comment]
@cwomack Any news from the team on this? I'm currently using `Storage.put` in our React Native app for image upload, and sometimes corrupted images make it through. The ability to pass a pre-calculated checksum is something we'd love to try.

**Comment by cwomack** [comment]
@muvashi and @tlmader, we just released the [Storage Browser connected component](https://ui.docs.amplify.aws/react/connected-components/storage/storage-browser) within the Amplify UI library that will support crc32 checksum.  Also, the `uploadData` API in v6 of Amplify will support `checksumAlgorithm: 'crc-32'` as an option (not documented, but we'll get that updated).

Can you let us know if the two of these updates are sufficient for your use cases? Thanks.

**Comment by eliottparis** [comment]
Is there any plan to support other checksum algorithms (SHA-1, SHA-256)?
