### ISSUE TITLE
AWSCloudWatchProvider fails to log if there is no authenticated user

### ISSUE THREAD

**Issue by DaryBeattie** [aws-amplify/amplify-js#11785]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Not applicable

### Amplify Categories

Not applicable

### Environment information

<details>

```
 System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 35.73 GB / 63.69 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (115.0.1901.200)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @babel/core: ^7.20.0 => 7.22.1 
    @react-native-async-storage/async-storage: 1.17.11 => 1.17.11 
    @react-native-clipboard/clipboard: ^1.11.2 => 1.11.2 
    @react-native-community/netinfo: 9.3.7 => 9.3.7 
    @react-native-picker/picker: 2.4.8 => 2.4.8 
    @react-navigation/bottom-tabs: ^6.5.7 => 6.5.7 
    @react-navigation/native: ^6.1.6 => 6.1.6 
    @react-navigation/native-stack: ^6.9.12 => 6.9.12 
    @reduxjs/toolkit: ^1.9.3 => 1.9.5 
    @reduxjs/toolkit-query:  1.0.0 
    @reduxjs/toolkit-query-react:  1.0.0 
    @rneui/base: ^0.0.0-edge.2 => 0.0.0-edge.2 
    @rneui/themed: ^0.0.0-edge.2 => 0.0.0-edge.2 
    @tsconfig/react-native: ^3.0.2 => 3.0.2 
    @types/fastestsmallesttextencoderdecoder: ^1.0.0 => 1.0.0 
    @types/jest: ^29.5.2 => 29.5.2 
    @types/react: ^18.2.14 => 18.2.14 
    @types/react-test-renderer: ^18.0.0 => 18.0.0 
    @types/seamless-immutable: ^7.1.16 => 7.1.16 
    HelloWorld:  0.0.1
    amazon-cognito-identity-js: ^6.3.1 => 6.3.1 (6.2.0)
    amazon-cognito-identity-js/internals:  undefined ()
    aws-amplify: ^5.0.19 => 5.2.5
    aws-amplify-react-native: ^7.0.2 => 7.0.2
    crypto-js: 3.1.9-1 => 3.1.9-1
    dayjs: ^1.11.8 => 1.11.8 (1.10.5)
    expo: ~48.0.6 => 48.0.19
    expo-asset: ~8.9.1 => 8.9.2
    expo-av: ~13.2.1 => 13.2.1
    expo-constants: ~14.2.1 => 14.2.1 (14.3.0)
    expo-device: ~5.2.1 => 5.2.1
    expo-document-picker: ~11.2.2 => 11.2.2
    expo-file-system: ~15.2.2 => 15.2.2 (15.3.0)
    expo-haptics: ~12.2.1 => 12.2.1
    expo-image-manipulator: ~11.1.1 => 11.1.1
    expo-image-picker: ~14.1.1 => 14.1.1
    expo-sharing: ~11.2.2 => 11.2.2
    expo-status-bar: ~1.4.4 => 1.4.4
    expo-updates: ~0.16.4 => 0.16.4
    fastestsmallesttextencoderdecoder: ^1.0.22 => 1.0.22
    husky: ^8.0.0 => 8.0.3
    react: 18.2.0 => 18.2.0
    react-native: 0.71.8 => 0.71.8
    react-native-document-picker: ^9.0.1 => 9.0.1
    react-native-gesture-handler: ~2.9.0 => 2.9.0
    react-native-haptic-feedback: ^2.0.3 => 2.0.3
    react-native-reanimated: ~2.14.4 => 2.14.4
    react-native-safe-area-context: 4.5.0 => 4.5.0
    react-native-screens: ~3.20.0 => 3.20.0
    react-native-share: ^9.0.2 => 9.0.2
    react-native-svg: 13.4.0 => 13.4.0
    react-native-webview: 11.26.0 => 11.26.0
    react-redux: ^8.0.5 => 8.0.7
    redux: ^4.2.1 => 4.2.1
    typescript: ^5.1.6 => 5.1.6
  npmGlobalPackages:
    @aws-amplify/cli: 11.0.0
    aes-cli: 1.3.0
    csvtojson: 2.0.10
    eas-cli: 4.0.0
    expo-cli: 6.3.10
    npm-check-updates: 16.3.8
    npm: 9.6.7
```

</details>

### Describe the bug

AWSCloudWatchProvider works fine when writing to the logs if you have an authenticated user, but if you don't have an authenticated user, it repeatedly fails, spewing errors every 2 seconds for eternity.

I was attempting to log to CloudWatch whenever I have client-side user authentication failing -- i.e. they do not have an authenticated user and _I want to know why_, and set up alerts and such whenever my authentication breaks.

The same errors that are repeated are:
```
 ERROR  [ERROR] 30:57.979 AWSCloudWatch - error getting log group - TypeError: Cannot read property 'byteLength' of undefined
 ERROR  [ERROR] 30:57.981 AWSCloudWatch - failure during log group search: TypeError: Cannot read property 'byteLength' of undefined
 ERROR  [ERROR] 30:58.1 AWSCloudWatch - failure while getting next sequence token: TypeError: Cannot read property 'byteLength' of undefined
 ERROR  [ERROR] 30:58.13 AWSCloudWatch - error during _safeUploadLogEvents: TypeError: Cannot read property 'byteLength' of undefined
 ERROR  [ERROR] 30:58.24 AWSCloudWatch - error when calling _safeUploadLogEvents in the timer interval - TypeError: Cannot read property 'byteLength' of undefined
```

Some Clues:
- Note the "failure when getting next sequence token" and it being "undefined". This bug changed the code to be undefined instead of empty: https://github.com/aws-amplify/amplify-js/pull/9181
- When people usually ask why they're getting "TypeError: Cannot read property 'byteLength' of undefined", the answer is usually that their IAM Role permissions aren't set up correctly, but mine are (to my knowledge?). I mean, the logging works fine when I have a logged-in user.

Some Notes:
- Could this be specific to **React-Native**?
- I'm on React-Native, and thus have installed the polyfill as described here:  https://stackoverflow.com/a/74754749/60218 -- It does work.

Things I have tried:
- Adding FULL CloudWatch & CloudWatchLogs access permissions to my authed and unauthed IAM Roles.
- Creating a new stream manually and specifying it in the code manually as well.
- Adding a single log event to the stream so that it's not an "empty stream", to try to bypass the issue described here: https://github.com/aws-amplify/amplify-js/pull/8309#issuecomment-892287246
- Starting with a completely fresh LogGroup.

### Expected behavior

I would expect that the Logger with the to work AWSCloudWatchProvider to support the unauthenticated state as well as authenticated.

### Reproduction steps

1. Set up the AWS logger in React-Native as instructed by the following:  https://github.com/aws-amplify/amplify-js/pull/8309
2. Make sure your IAM roles have the permissions listed.
3. Try to log to the stream without having an authenticated user.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello, @DaryBeattie 👋.  I'll close this issue in favor of #9575 due to the scope of the log failures and "TypeError: Cannot read property 'byteLength' of undefined" error you experienced being captured in that issue.  As stated [in a comment](https://github.com/aws-amplify/amplify-js/issues/9575#issuecomment-1674173120) on that issue, we'll have this bug fixed with the revamped version of our CloudWatch Logger when it gets released.  Thank you for your patience while we work on this!

**Comment by DaryBeattie** [comment]
As long as the root cause of #9575 is the same, I'm cool with that. It wasn't clear from 9575 that it was the same error being reported, as I could not find that info in the bug report or its comments.

As this bug is being closed-completed without an actual version to test being released yet, how will I know when I can re-test this scenario to verify that it is fixed?

**Comment by cwomack** [comment]
@DaryBeattie, if you expand the "[Log Output](https://github.com/aws-amplify/amplify-js/issues/9575#:~:text=below%20this%20line.-,Log%20output,-Details)" section within the other issue you'll see a matching sequence of log group error that you reported.  Between this issue being mentioned in the comments and our internal notes marking the two as related, we'll ensure both are considered for what the scope of a "fix" will be. 

As for the "closed-complete" status, good catch! This should be marked as "closed as not planned" due to this being considered a duplicate (updating that with this comment).  And we'll make sure we circle back to #9575 to leave a comment when there's any updates on progress for you to re-test and verify the fix!

**Comment by DaryBeattie** [comment]
Ah, okay, thanks for pointing that out. Guess I missed it.

Perfect, will keep my eyes peeled for the update! 👀

**Comment by DarylBeattie** [comment]
Any update on this?
