### ISSUE TITLE
Error: not authenticated – Electron

### ISSUE THREAD

**Issue by philippefutureboy** [aws-amplify/amplify-js#1178]
**Do you want to request a feature or report a bug?** Potentially both. Report a bug first, and potentially a feature second. 

**What is the current behavior?**

Calling `Auth.currentAuthenticatedUser();` after a successful sign in with `Auth.signIn(email, password);` returns `Error: not authenticated`.

[Code on Pastebin](https://pastebin.com/5HxgcW1J)

Alternate version: 
1. Save the CognitoUser returned by `Auth.signIn` in the state of the React Component.
2. Call `Auth.changePassword(this.state.user, this.state.oldPassword, this.state.newPassword);`
3. Get `Error: Local storage is missing an ID Token, Please authenticate`

[Code on Pastebin](https://pastebin.com/U3CTvj7L)

**What is the expected behavior?**

https://aws.github.io/aws-amplify/media/authentication_guide <= this to work :P

**Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?**

**AWS-Amplify:** v^0.4.8,
**Browser:**  Electron v^2.0.2 (Chrome v61.0.3163.100)
**Source Boilerplate:** https://github.com/chentsulin/electron-react-boilerplate/ (with customizations)

**You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.**

First version:
<img width="1257" alt="screen shot 2018-07-06 at 11 50 54 am" src="https://user-images.githubusercontent.com/31741972/42389242-0bce9000-8116-11e8-9241-c75d3917a6ee.png">
<img width="1265" alt="screen shot 2018-07-06 at 11 50 25 am" src="https://user-images.githubusercontent.com/31741972/42389244-0daee0c8-8116-11e8-9452-286c86c03255.png">

Alternate version:
<img width="1276" alt="screen shot 2018-07-06 at 11 55 29 am" src="https://user-images.githubusercontent.com/31741972/42389256-1564010e-8116-11e8-89a6-b9df7dad62d3.png">

**Any idea of where to start?**

* I believe the problem may be related to Electron's localStorage. From memory Electron does not use localStorage in the same way as Chrome does.
* It may also be my lack of understanding of UserPools vs Federated Identities. My config has the identityPoolId, region, userPoolId, userPoolWebClientId and mandatorySignIn specified. Am I misunderstanding something?

**Any other comments?**

* If you could suggest a temporary solution where I handle the session & user state directly in my React application, I'd be supppppeeeeerrrr grateful 🎉
* If you need a test repo, let me know and I'll see what I can do.
* If it is indeed an Electron thing, this then becomes a **feature request** for supporting Electron ✨

**Comment by powerful23** [comment]
@philippefutureboy yes this could be a problem with Electron. For now I would suggest using CookieStorage for your application: https://aws.github.io/aws-amplify/media/authentication_guide#manual-setup . We are also having a plan to provide a more generic interface for developers so they can provide their own Storage interface to the library.

**Comment by philippefutureboy** [comment]
@powerful23 Thanks for your answer :)
For the time being, we have decided to hold off on the Auth in the app since it is not a priority.
I'll be looking forward to see your solution!

**Comment by powerful23** [comment]
Closing the issue as this enhancement has been implemented in the current version.

**Comment by themuli** [comment]
I could be experiencing a similar issue with electron: https://github.com/aws-amplify/amplify-js/issues/3321, eg. credentials might not be persisted properly after a successful login, and debug statements show my session as null. @powerful23 @philippefutureboy Can you explain which libraries you upgraded to solve this? Was it an Amplify or electron bug?

@powerful23 As a temporary workaround, what are the correct settings to use with cookieStorage? I followed the link you gave and set `.mydomain.com` as the domain but am getting

```24:45.9 AuthClass - Failed to get the signed in user No current user```

Your help is much appreciated.
