### ISSUE TITLE
Datastore event modelSynched is taking too much time with 28K data

### ISSUE THREAD

**Issue by diyajohnc** [aws-amplify/amplify-js#11843]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

DataStore

### Amplify Categories

storage

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I need to use datastore as my app supports offline scenarios. But modelsynched event is taking too much time, more than 20s, with only 28K data.
Any solution for this

### Expected behavior

20sec for modelsynched event to get fired is not acceptable

### Reproduction steps

Amplify datastore connected to a Dynamodb having 30k data is very slow

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello, @diyajohnc 👋.  I've got a few questions to help clarify what is happening in this situation to see if we can better assist.  

- What version of Amplify are you currently on?  Could you share your full `package.json`?
- Can you share your full schema?
- How many records in each table? (Including `_deleted: true` records)
- What does your Amplify/DataStore configure steps look like? (Including sync expressions)

**Comment by svidgen** [comment]
There are a lot of factors that could affect final performance here, network latency and device speed among them. For your specific case, I don't think I saw any sync expressions listed here.  The original graphql schema would also help &mdash; I'm looking in particular for your `@auth` rules and indexing.

Are you intentionally syncing *all* the data down for all users?

Is there any possibility of limiting that set with a sync expression? Perhaps by signed in user? Or by created/updated date? Or rough location? Etc.

With ~28k records, is your amount of data expected to grow over time? If so, and if selective sync can't get your sync down to a reasonable size, does the GraphQL API category make more sense for your use-case?

**Comment by diyajohnc** [comment]
> There are a lot of factors that could affect final performance here, network latency and device speed among them. For your specific case, I don't think I saw any sync expressions listed here. The original graphql schema would also help — I'm looking in particular for your `@auth` rules and indexing.
> 
> Are you intentionally syncing _all_ the data down for all users?
> 
> Is there any possibility of limiting that set with a sync expression? Perhaps by signed in user? Or by created/updated date? Or rough location? Etc.
> 
> With ~28k records, is your amount of data expected to grow over time? If so, and if selective sync can't get your sync down to a reasonable size, does the GraphQL API category make more sense for your use-case?

Beow is the schema graphql
type DeviceEntity @aws_iam @aws_cognito_user_pools @aws_api_key {
  id: ID!
  deviceCode: String
  deviceName: String
  deviceIp: String
  port: String
  deviceRange: String
  deviceType: String
  manufacturer: String
  commercialReference: String
  serialNumber: String
  isFavourite: Boolean
  deviceId: String
  bluetoothAddress: String
  zigbeeStatus: Boolean
  bluetoothStatus: Boolean
  lastUpdated: String
  _version: Int!
  _deleted: Boolean
  _lastChangedAt: AWSTimestamp!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  owner: String
}

Only the signed in users data is what we are synching. When I checked th network tab, graphql queries are being send in batch by batch to get the data of the sighed in user. Is there a way to optimise the call to get the data of the signed in user

>>With ~28k records, is your amount of data expected to grow over time? If so, and if selective sync can't get your sync down to a reasonable size, does the GraphQL API category make more sense for your use-case?
Data will definitily grow. But not drastically.

**Comment by chrisbonifacio** [comment]
Hi @diyajohnc , apologies for the delayed response. The amount of time it takes to sync data down is heavily dependent on network latency. 

Like @svidgen mentioned, I would recommend leveraging the [Selective Sync](https://docs.amplify.aws/lib/datastore/sync/q/platform/js/#selectively-syncing-a-subset-of-your-data) feature to only sync down the data that is necessary for the user.


Also, this won't speed up the sync process but you can render data as it is synced if you use [`observeQuery`](https://docs.amplify.aws/lib/datastore/real-time/q/platform/js/#observe-query-results-in-real-time).

If neither of these help your use case, then I would try using the API.graphql library instead to gain more control over the queries themselves.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
