### ISSUE TITLE
Make Amplify.configure functions return promises

### ISSUE THREAD

**Issue by davemackintosh** [aws-amplify/amplify-js#11842]
### Is this related to a new or existing framework?

React

### Describe the feature you'd like to request

Similar to #2082 I'd like these configure functions to return promises as this will make it possible to authenticate using SSO providers invisibly possible. Currently we face a race condition between a redirect for the user to take them to their desired page and the configure competing for authentication status which we can only set a timeout for.

### Describe the solution you'd like

All configure functions to return a promise 

### Describe alternatives you've considered

Setting timeouts and using hub events to get auth status

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by davemackintosh** [comment]
While I was searching through some of the source code for the amplify libraries, I discovered internal usage of `Hub` which got me to thinking "What if the different libraries are using different versions of @aws-amplify/core? So I pinned the version in `resolutions` in my `package.json` and now Hub.listen gives me the events I need.

However, this Promise-cation would still be beneficial if you don't want to have to ensure all core hub references the same version of the library with a hard version pinning and it could have saved me a day of work if I could just guarantee at configure time that the task is complete.

**Comment by davemackintosh** [comment]
A further update on this, it appears bundling breaks the hub and events and once NextJS has compiled this all down to static assets Hub gets spread out across the different chunks and thus loses it's own reference so events go back to not firing and I'm back to naive setTimeout and crossing my fingers for configuration and auth status checks completing in time.

**Comment by cwomack** [comment]
@davemackintosh, thank you for creating this issue.  I've marked this as a feature request and will review this with the team internally.

**Comment by cwomack** [comment]
@davemackintosh, for the Hub getting spread out across the different chunks and losing references, could you try this with the recently released v6 developer preview for JS? The [documentation](https://docs.amplify.aws/lib-v1/utilities/hub/q/platform/js/) has been updated (including Hub) and the bundling improvements may resolve this issue.  Check out our[ blog post](https://aws.amazon.com/blogs/mobile/aws-amplify-javascripts-new-developer-preview-with-reduced-bundle-sizes-improved-typescript-and-next-js-support/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=238088647) about it as well for more information.

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
