### ISSUE TITLE
vite build mode: progressCallback not trigger when Storage.put()

### ISSUE THREAD

**Issue by natuan62** [aws-amplify/amplify-js#11863]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

Storage

### Amplify Categories

storage

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

When I call storage.put(), this progressCallback() doesn't trigger.

I found this case have same issue https://github.com/vitejs/vite/discussions/14038

### Expected behavior

progressCallback() trigger work fine.

### Reproduction steps

1. Config vite + vue project and install aws-amplify package

```
const uploadFileToStorage = async (itemFile: any) => {
      try {
        const filePath = (itemFile.name;
        const metadata: Record<string, any> = {
          
        };
        const config = {
          level: 'private',
          contentType: 'text/plain',
          metadata,
          progressCallback({
            loaded,
            total,
          }: {
            loaded: number;
            total: number;
          }) {
            percent.value = Math.round((loaded / total) * 100);
            console.log('percent.value', percent.value);
          },
        };
         await Storage.put(filePath, itemFile.file, config);
      } catch (err: any) {
        console.log('err', err);
      }
    };
```

2. Run yarn build + yarn preview

3. Upload file with Storage.put()

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

![image](https://github.com/aws-amplify/amplify-js/assets/10808157/9964661f-189e-4894-a2b4-bbcf9375e300)

- dev mode (progressCallback work fine)

![image](https://github.com/aws-amplify/amplify-js/assets/10808157/de1b67fd-7d2a-4d66-89b2-786450e2dec8)

- build mode (progressCallback not trigger)

![image](https://github.com/aws-amplify/amplify-js/assets/10808157/3502f0b5-ec7c-4f1c-bf0d-854964e3632e)

**Comment by natuan62** [comment]
@cwomack 

Yes, I uploading the same file. 
And size of the file is 3 MB, but all files with any size still not working 

![image](https://github.com/aws-amplify/amplify-js/assets/10808157/5f7b0742-00a6-414b-80a2-624670f8823e)

**Comment by michaelhoarau** [comment]
Hi,
I'm experimenting the same issue.

This part of my code hasn't changed since a couple weeks: I see the upload progress bar working fine on my dev environment, but not in the hosted environment (after `amplify publish`). I tried to minimize any change between these two environments and basically:
* The target bucket where the upload happens is the same in both environments
* The files I use for my test is the same (they are CSV files ranging from **50 MB to 700 MB**)
* The role I used once authenticated is the same

My upload code is following:

```
// --------------------------------------
// Called while a file is pushed to S3 to 
// provide feedback to the user during an 
// upload:
// --------------------------------------
const progressCallback = (progress) => {
    console.log(progress)
    if (!progress['timeStamp']) {
        setProgressPercent(parseInt(progress.loaded / progress.total * 100))
        setBytesTransferred(`${getHumanReadableSize(progress.loaded)} bytes loaded`)            
    }
    else {
        setProgressPercent(100)
        setBytesTransferred('Done')
    }
}

// -----------------------
// Uploading a file to S3:
// -----------------------
const uploadFileToS3 = async (asset, component, file) => {
    try {
        setFilename(file.name)
        setUploadInProgress(true)

        await Storage.put(
            asset+ '/' + component + '/sensors.csv', 
            file,
            { 
                contentType: file.type,
                level: "private",
                tagging: `L4EDemoAppUser=${uid}&AssetDescription=${assetDescription}`,
                progressCallback,
            }
        )
    }
    catch (error) {
        console.log("Error uploading file:", error, error.response);
    }
}
```

On my local environment, the `progressCallback` function is called and I can see the `console.log()` calls.
When I publish the app, the `console.log()` calls are not fired (the function is not called at all).
What should I check? Note that this was working a while ago so I don't think it comes from this code (it hasn't changed for weeks).

Thanks for any pointer!

**Comment by achlubek** [comment]
I encountered exactly the same problem today, works until bundled. Surprisingly it worked ok with very similar code that had different file directory layout and imports. The callback is just not fired at all.

**Comment by cwomack** [comment]
@achlubek  and @natuan62,  I believe we have found the issue and possibly the resolution.  Can you see if passing in `resumable: true` as [seen here](https://docs.amplify.aws/lib/storage/upload/q/platform/js/#pause-and-resume-uploads) in the docs will help resolve the problem?

If so, I believe we'll be updating the documentation, but our local testing indicates this should fix the issue in v5 of Amplify.  I've already got one confirmation this should be fixed (from @michaelhoarau), but let me know! Thanks.

**Comment by achlubek** [comment]
@cwomack yes this is how we worked the issue around, using resumable = true and wrapping the code in a promise that ultimately resolves, inside the promise there is a setInterval that fires the progressCallback based on the percentage read from the upload. Hacky but works

**Comment by michaelhoarau** [comment]
Hi @cwomack ,

Yes, I confirm that this works. I just added resumable = true to my code. If anyone stumbles upon this issue, the following code works and generates the calls to the progress callback:

```
import { useState } from 'react'

const [ progressPercent, setProgressPercent ] = useState(0)
const [ bytesTransferred, setBytesTransferred ] = useState("0 bytes loaded")

// --------------------------------------
// Called while a file is pushed to S3 to 
// provide feedback to the user during an 
// upload:
// --------------------------------------
const progressCallback = (progress) => {
    if (!progress['timeStamp']) {
        setProgressPercent(parseInt(progress.loaded / progress.total * 100))
        setBytesTransferred(`${getHumanReadableSize(progress.loaded)} bytes loaded`)            
    }
    else {
        setProgressPercent(100)
        setBytesTransferred('Done')
    }
}

// -----------------------
// Uploading a file to S3:
// -----------------------
const uploadFileToS3 = async (asset, component, file) => {
    try {
        await Storage.put(
            'target_filename.csv', 
            file,
            { 
                contentType: file.type,
                level: "private",
                resumable: true,
                progressCallback,
            }
        )
    }
    catch (error) {
        console.log("Error uploading file:", error)
    }
}
```
Thanks a lot for your support and for pointing out the workaround!

**Comment by cwomack** [comment]
Appreciate the confirmations on this! We'll capture the needed docs update to make a callout for Storage within the v5 in [this linked issue](https://github.com/aws-amplify/docs/issues/6086) and close this out.

**Comment by natuan62** [comment]
Hi @cwomack When i set `resumable: true`. this error occurred although I'm working on `localhost`

If I remove `resumable: true`, upload still work on `localhost`

```
33:54.35 AWSS3UploadTask - Error initializing the upload task AccessDenied: Access Denied
```

![image](https://github.com/aws-amplify/amplify-js/assets/10808157/e5edc557-eeb7-43c5-9a30-599bda8ae89d)


```
    const uploadFileToStorage = async (itemFile: any) => {
      try {
       // authen
        await Auth.signIn(loginForm.email, loginForm.password);

        const filePath = kebaCase(itemFile.name);
        const metadata: Record<string, any> = {
          //
        };
        const config = {
          level: 'private',
          contentType: 'text/plain',
          metadata,
          resumable: true,
          progressCallback({
            loaded,
            total,
          }: {
            loaded: number;
            total: number;
          }) {
            percent.value = Math.round((loaded / total) * 100);
            console.log('percent.value', percent.value);
          },
        };

        Storage.configure({
          bucket: '',
          region: 'us-west-2',
          customPrefix: {
            public: 'public/',
            protected: 'protected/',
          },
        });
        const res = await Storage.put(filePath, itemFile.file, config as any);
        console.log('res', res);
        itemFile.uploading = 100;
      } catch (err: any) {
        console.log('err', err);
      }
    };
```
