### ISSUE TITLE
Google SSO Invalid State

### ISSUE THREAD

**Issue by Mark-Durkot** [aws-amplify/amplify-js#11881]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
 System:
    OS: macOS Mojave 10.14.6
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Memory: 17.98 GB / 40.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    npm: 9.8.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 116.0.5845.110
    Safari: 14.1.2
  npmPackages:
    @angular-devkit/build-angular: ^16.0.5 => 16.2.0 
    @angular/animations: ^16.0.5 => 16.2.2 
    @angular/cdk: ^16.0.4 => 16.2.1 
    @angular/cli: ^16.2.0 => 16.2.0 
    @angular/common: ^16.0.5 => 16.2.2 
    @angular/compiler: ^16.0.5 => 16.2.2 
    @angular/compiler-cli: ^16.0.5 => 16.2.2 
    @angular/core: ^16.0.5 => 16.2.2 
    @angular/forms: ^16.0.5 => 16.2.2 
    @angular/google-maps: ^15.2.9 => 15.2.9 
    @angular/platform-browser: ^16.0.5 => 16.2.2 
    @angular/platform-browser-dynamic: ^16.0.5 => 16.2.2 
    @angular/router: ^16.0.5 => 16.2.2 
    @aws-amplify/auth: ^5.6.4 => 5.6.4 
    @types/amazon-cognito-auth-js: ^1.3.0 => 1.3.0 
    @types/jasmine: ~4.0.0 => 4.0.3 
    amazon-cognito-auth-js: ^1.3.3 => 1.3.3 
    aws-amplify: ^5.3.8 => 5.3.10 
    aws-sdk: ^2.1444.0 => 2.1444.0 
    bootstrap: ^5.3.0 => 5.3.1 
    bootstrap-icons: ^1.10.5 => 1.10.5 
    jasmine-core: ~4.3.0 => 4.3.0 
    karma: ~6.4.0 => 6.4.2 
    karma-chrome-launcher: ~3.1.0 => 3.1.1 
    karma-coverage: ~2.2.0 => 2.2.1 
    karma-coverage-coffee-example:  1.0.0 
    karma-jasmine: ~5.1.0 => 5.1.0 
    karma-jasmine-html-reporter: ~2.0.0 => 2.0.0 
    ngx-indexed-db: ^12.0.0 => 12.0.0 
    ngx-spinner: ^16.0.2 => 16.0.2 
    rxjs: ~7.5.0 => 7.5.7 (7.8.1)
    rxjs/ajax:  undefined ()
    rxjs/fetch:  undefined ()
    rxjs/operators:  undefined ()
    rxjs/testing:  undefined ()
    rxjs/webSocket:  undefined ()
    tslib: ^2.3.0 => 2.6.2 (2.6.1, 1.14.1)
    typescript: ~4.9.5 => 4.9.5 
    zone-mix:  undefined ()
    zone-node:  undefined ()
    zone-testing:  undefined ()
    zone.js: ~0.13.0 => 0.13.1 
    zone.js/async-test:  undefined ()
    zone.js/async-test.min:  undefined ()
    zone.js/fake-async-test:  undefined ()
    zone.js/fake-async-test.min:  undefined ()
    zone.js/jasmine-patch:  undefined ()
    zone.js/jasmine-patch.min:  undefined ()
    zone.js/long-stack-trace-zone:  undefined ()
    zone.js/long-stack-trace-zone.min:  undefined ()
    zone.js/mocha-patch:  undefined ()
    zone.js/mocha-patch.min:  undefined ()
    zone.js/proxy:  undefined ()
    zone.js/proxy.min:  undefined ()
    zone.js/sync-test:  undefined ()
    zone.js/sync-test.min:  undefined ()
    zone.js/task-tracking:  undefined ()
    zone.js/task-tracking.min:  undefined ()
    zone.js/webapis-media-query:  undefined ()
    zone.js/webapis-media-query.min:  undefined ()
    zone.js/webapis-notification:  undefined ()
    zone.js/webapis-notification.min:  undefined ()
    zone.js/webapis-rtc-peer-connection:  undefined ()
    zone.js/webapis-rtc-peer-connection.min:  undefined ()
    zone.js/webapis-shadydom:  undefined ()
    zone.js/webapis-shadydom.min:  undefined ()
    zone.js/wtf:  undefined ()
    zone.js/wtf.min:  undefined ()
    zone.js/zone-bluebird:  undefined ()
    zone.js/zone-bluebird.min:  undefined ()
    zone.js/zone-error:  undefined ()
    zone.js/zone-error.min:  undefined ()
    zone.js/zone-legacy:  undefined ()
    zone.js/zone-legacy.min:  undefined ()
    zone.js/zone-patch-canvas:  undefined ()
    zone.js/zone-patch-canvas.min:  undefined ()
    zone.js/zone-patch-cordova:  undefined ()
    zone.js/zone-patch-cordova.min:  undefined ()
    zone.js/zone-patch-electron:  undefined ()
    zone.js/zone-patch-electron.min:  undefined ()
    zone.js/zone-patch-fetch:  undefined ()
    zone.js/zone-patch-fetch.min:  undefined ()
    zone.js/zone-patch-jsonp:  undefined ()
    zone.js/zone-patch-jsonp.min:  undefined ()
    zone.js/zone-patch-message-port:  undefined ()
    zone.js/zone-patch-message-port.min:  undefined ()
    zone.js/zone-patch-promise-test:  undefined ()
    zone.js/zone-patch-promise-test.min:  undefined ()
    zone.js/zone-patch-resize-observer:  undefined ()
    zone.js/zone-patch-resize-observer.min:  undefined ()
    zone.js/zone-patch-rxjs:  undefined ()
    zone.js/zone-patch-rxjs-fake-async:  undefined ()
    zone.js/zone-patch-rxjs-fake-async.min:  undefined ()
    zone.js/zone-patch-rxjs.min:  undefined ()
    zone.js/zone-patch-socket-io:  undefined ()
    zone.js/zone-patch-socket-io.min:  undefined ()
    zone.js/zone-patch-user-media:  undefined ()
    zone.js/zone-patch-user-media.min:  undefined ()
  npmGlobalPackages:
    @angular/cli: 14.2.3
    @aws-amplify/cli: 12.3.0
    corepack: 0.12.1
    npm: 9.8.1
    typescript: 4.8.3
```

</details>

### Describe the bug

Hi guys, I'm trying to implement SSO Login with AWS Cognito using AWS Amplify with angular.

To trigger the auth I call:

`Auth.federatedSignIn({ provider: 'Google' })`

After I submit my credentials to google I get redirected to error page saying 'Invalid State', but still the user adds to the user pool having Confirmation Status - External Provider.

I checked the AWS, Google and environment credentials and if they match many times. I also added the Google identity provider in Cognito User Pools -> App Integration -> Client -> Hosted UI -> Identity Providers.

### Expected behavior

I want to get AWS Cognito JWT tokens in response.

### Reproduction steps

1. npm install aws-amplify
2. auth.service.ts
```
export class AwsCongnitoService {

  constructor() {
    Amplify.configure({
      Auth:environment.AwsCognito
    });
  }

  public googleSignIn() {
    return Auth.federatedSignIn({ provider: CognitoHostedUIIdentityProvider.Google });
  }
```
3. login.html
```<button (click)="googleSignInClicked()">Sign In with Google</button>```
4. login.ts
```
googleSignInClicked() {
    const user = await this.awsCognitoService.googleSignIn();
    console.log(user);
}
```

5. environment.ts
```
AwsCognito: {
    userPoolId: '****',
    userPoolWebClientId: '****',
    oauth: {
      domain: '****.amazoncognito.com',
      scopes: ['phone', 'email', 'profile', 'openid'],
      redirectSignIn: 'https://****.amazoncognito.com/oauth2/idpresponse',
      responseType: 'code'
    }
  }
```

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

<img width="367" alt="Screen Shot 2023-08-25 at 00 45 37" src="https://github.com/aws-amplify/amplify-js/assets/85638790/d6d19bdf-21c8-44a2-b480-ccbaa346106a">
<img width="1306" alt="Screen Shot 2023-08-25 at 00 46 26" src="https://github.com/aws-amplify/amplify-js/assets/85638790/8feeef24-262c-4f51-bee5-992deb00fa15">
<img width="1306" alt="Screen Shot 2023-08-25 at 00 47 12" src="https://github.com/aws-amplify/amplify-js/assets/85638790/71545406-a356-4a60-b8df-6c4eda1a8c68">
<img width="1304" alt="Screen Shot 2023-08-25 at 00 48 07" src="https://github.com/aws-amplify/amplify-js/assets/85638790/1c7a8c43-094b-445d-b551-5a06887c41ae">
<img width="1304" alt="Screen Shot 2023-08-25 at 03 36 17" src="https://github.com/aws-amplify/amplify-js/assets/85638790/7d83cd4d-fb7a-4bd2-b1a1-89c9b6c9f60d">
<img width="1303" alt="Screen Shot 2023-08-25 at 03 36 26" src="https://github.com/aws-amplify/amplify-js/assets/85638790/76395c97-799a-4ab0-838e-869455548e1d">
<img width="1301" alt="Screen Shot 2023-08-25 at 03 36 35" src="https://github.com/aws-amplify/amplify-js/assets/85638790/58babd7a-be25-4e25-a231-94d76c096c08">

**Comment by cwomack** [comment]
Hello, @Mark-Durkot and thanks for opening this issue.  Can you confirm that the scopes you have listed within your `aws-exports` align with what you show for the User Pool in Cognito along with the Google Console?  Also, would you be able to share further frontend code where the Auth calls are being made related to the federated sign in with Google?

**Comment by Mark-Durkot** [comment]
Sorry for late reply @cwomack I was working on other features.
I'm not sure if it is a issue with Amplify or Cognito. Because the same problem appears when I click "Hosted UI" in the AWS Concole under user pools -> app integration -> app client -> hosted ui.
Yes, the scopes do match.
This is the only line of code I am calling related to federated sign in with Google:
`Auth.federatedSignIn({ provider: CognitoHostedUIIdentityProvider.Google });`

**Comment by ihor1337** [comment]
Any updates on this? Having the same issue

**Comment by nadetastic** [comment]
Hi @Mark-Durkot following up here - looking at the screenshots you shared, your `redirect_uri` look wrong. Instead of the being the cognito hosted ui domain, it should be the URI of your app where the user will eventiually be redirected back to. Can you confirm what this value is in your `aws-exports.js` file? It will be under `oauth` object:

```js
oauth: {
      domain: 'your_cognito_domain',
      scope: [
        'phone',
        'email',
        'profile',
        'openid',
        'aws.cognito.signin.user.admin'
      ],
      redirectSignIn: 'http://localhost:3000/', // <=== this value
      redirectSignOut: 'http://localhost:3000/',
      clientId: '1g0nnr4h99a3sd0vfs9',
      responseType: 'code' // or 'token', note that REFRESH token will only be generated when the responseType is code
    }
```

@ihor1337 for your case can you also confirm the above?

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
