### ISSUE TITLE
Unable to set field-level authorization rule

### ISSUE THREAD

**Issue by belfortf** [aws-amplify/amplify-js#11937]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

Authentication, REST API, GraphQL API, Storage

### Amplify Categories

auth, storage

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 13.0.1
    CPU: (8) x64 Apple M1
    Memory: 94.91 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Brave Browser: 107.1.45.131
    Chrome: 116.0.5845.140
    Safari: 16.1
  npmGlobalPackages:
    @luminati-io/luminati-proxy: 1.391.825
    corepack: 0.15.3
    npm: 9.5.0
    nuxi: 3.6.5
    purgecss: 5.0.0

```

</details>

### Describe the bug

I have a large type with many indexes but below you'll find a simplified version. Basically, I want to use field-level auth to make some fields not public. For example, in the schema below I would like "model" to be seen only by the owner, while "id" has to be seen by everyone, so that I can access it via the frontend. Even though field-level auth has been added to the required fields, I still see the same error message. Or am I doing something wrong ?

### Expected behavior

I get this error message even though the field-level auth has been set for the required fields:

> When using field-level authorization rules you need to add rules to all of the model's required fields with at least read permissions. Found model "Product" with required fields ["id","userprofileID"] missing field-level authorization rules.
> 
> For more information visit https://docs.amplify.aws/cli/graphql/authorization-rules/#field-level-authorization-rules

I would expect not to get this error message. 

### Reproduction steps

1) Try to do amplify push in the schema below. For me it fails.
        

### Code Snippet

```javascript
// Put your code below this line.
@model
	@auth(
		rules: [
			{ allow: public, operations: [get,list] }
			{ allow: owner, operations: [create] }
		]
	) {
	id: ID! @auth(rules: [{ allow: public }])
	userprofileID: ID! @auth(rules: [{ allow: public }]) @index(name: "byUserprofile") 
	model: String @auth(rules: [{ allow: owner }])
        name: String}
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello, @belfortf 👋.  I'm wondering if some refactoring of your schema might be able to help with the `amplify push` failing.  I believe your `@index` directive needs to be outside `@auth` directive.  The error message looks like it's related to field-level auth rules missing on the model.  Can you see if the following refactored schema helps resolve the issue?
```js
@model
	@auth(
		rules: [
			{ allow: public, operations: [get, list] }
			{ allow: owner, operations: [create] }
		]
	) {
	id: ID!
	userprofileID: ID! @index(name: "byUserprofile")
	model: String @auth(rules: [{ allow: owner }])
	name: String
}
```

**Comment by belfortf** [comment]
Hi @cwomack, this is what I did first, then I got the amplify error message from above and did what it suggested....so unfortunately not working :(

**Comment by belfortf** [comment]
@cwomack , same thing happening here:

``` Javascript
type Userprofile
	@model
	@auth(
		rules: [
			{ allow: public, operations: [read, create] },
			{ allow: owner, operations: [read, create] }
			{ allow: groups, groups: ["Admins"], operations: [read, create, update, delete] }
		]
	) {
	id: ID!
	email: String! @auth(rules: [{ allow: owner},{ allow: groups, groups: ["Admins"]}]) @index(name: "byEmail", queryField: "listUserProfileByEmail")
```
By taking the ! off of String, it all compiles well. Then of course String is not required anymore and that's not optimal for my use-case.

**Comment by belfortf** [comment]
> @belfortf, appreciate you providing more details on the schema! After looking at this further, the error might be happening due to the model's field level `@auth` rules and the CLI wanting all required fields to have rules too.
> 
> Can you see if the following schema works:
> 
> ```js
> type Product
> 	@model
> 	@auth(
> 		rules: [
> 			{ allow: public, operations: [get, list] }
> 			{ allow: owner, operations: [create] }
> 		]
> 	) {
> 	id: ID!
> 	assets: [Asset]
> 	userprofileID: ID! @index(name: "byUserprofile") 
> 	Orders: [Order] @manyToMany(relationName: "ProductOrder")
> 	category: Category
> 		@index(
> 			name: "productsByCategoryAndTypeAndEngine"
> 			sortKeyFields: ["type", "engine"]
> 			queryField: "listProductsByCategoryAndTypeAndEngine"
> 		)
> 		@index(
> 			name: "productsByCategoryAndEngineAndType"
> 			sortKeyFields: ["engine", "type"]
> 			queryField: "listProductsByCategoryAndEngineAndType"
> 		)
> 		@index(
> 			name: "productsByCategoryDate"
> 			sortKeyFields: ["createdOn"]
> 			queryField: "listProductByCategoryDate"
> 		)
> 	engine: Engine
> 		@index(
> 			name: "productsByEngineAndTypeAndCategory"
> 			sortKeyFields: ["type", "category"]
> 			queryField: "listProductsByEngineAndTypeAndCategory"
> 		)
> 		@index(
> 			name: "productsByEngineAndCategoryAndType"
> 			sortKeyFields: ["category", "type"]
> 			queryField: "listProductsByEngineAndCategoryAndType"
> 		)
> 	model: String
> 	type: Type
> 		@index(
> 			name: "productsByTypeAndCategoryAndEngine"
> 			sortKeyFields: ["category", "engine"]
> 			queryField: "listProductsByTypeAndCategoryAndEngine"
> 		)
> 		@index(
> 			name: "productsByTypeAndEngineAndCategory"
> 			sortKeyFields: ["engine", "category"]
> 			queryField: "listProductsByTypeAndEngineAndCategory"
> 		)
> 	
> 	Userprofile: Userprofile @belongsTo(fields: ["userprofileID"])
> 	ProductLikes: [ProductLike] @hasMany(indexName: "byProduct", fields: ["id"])
> 	photoUsedID: ID @index(name: "byPhoto", sortKeyFields: ["id"])
> }
> ```

Yes, but this is the code without any field-level authorization. Public users shouldn't see "model", even though they should be able to list and get the other aspects of the table. Model here is just a placeholder, imagine that I'm selling a digital asset and the asset would be in "model". Public users should be able to get and list products, so that they see them on the website, but they shouldn't be allowed to see all fields of the table. Am I misunderstanding something here ?

**Comment by cwomack** [comment]
@belfortf, understood and your goals make complete sense. Thank you for trying to see if any of those changes gave different results. 

The changes you made after the initial error message's guidance should have let you push, so I'll mark this as a bug for now and review it further with the team internally.  We'll reach out with any updates or further questions as soon as we can!
