### ISSUE TITLE
using sameSite: "lax" with cookies leads to authentication error - special characters in username are encoded in lax vs not from strict

### ISSUE THREAD

**Issue by asp3** [aws-amplify/amplify-js#11945]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

latest amplify version

### Describe the bug

For our use case, we needed to make sure that users were authenticated for requests where they clicked on a link they were sent, which means we had to set sameSite to `lax`.

// awsConfig
```
    cookieStorage: {
        sameSite: "lax",
    },
```

After this, however, all server side requests for Auth.currentSession threw an error, with the message:

```
- error ../node_modules/amazon-cognito-identity-js/lib/CognitoUser.js (1150:15) @ CognitoUser.getSession
- error Error: Local storage is missing an ID Token, Please authenticate
    at new Promise (<anonymous>)
    at new Promise (<anonymous>)
    at new Promise (<anonymous>)
```

I verified that the cookies were available, both from inspect element, and right before the `withSSRContext` call was made.

```
export const createSSRContext = cache(() => {
    // Construct a req object & prepare an SSR enabled version of Amplify
    const req = {
        headers: {
            cookie: headers().get("cookie"),
        },
    };

    const val = new Cookies(req.headers.cookie);
    console.log(val);

    return withSSRContext({ req });
});
```

Here, val has the proper values, which means that the UniversalStorage object should also have them.

I did some investigation into the bug, and I realized that on our deployed site (where `sameSite: "strict"`), the keys are stored as:

`CognitoIdentityServiceProvider.{id}.{email}@-@{site}.idToken`

however, when sameSite: "lax", it becomes

`CognitoIdentityServiceProvider.{id}.{email}%40-%40{site}.idToken`

And therefore, the fetch for the cookies fails!

Anything we can do to resolve this? Its currently stopping users from clicking on links to our site, which is a pretty big source of traffic.

Alternatively, I would probably propose that "lax" be the default for this storage going forward, as I assume other people would also want authenticated capabilities when clicking on links.

### Expected behavior

logging in even with sameSite: "lax" should work 

### Reproduction steps

change cookies to be sameSite: "lax"

sign in with an account that has special characters in the username (@)

try to authenticate from serverside

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by asp3** [comment]
note: after manually changing all cookie keys to their non encoded versions, authentication flow works as expected

**Comment by cwomack** [comment]
Hello again, @asp3! Thanks for creating this issue as it looks like it's related to the URI encoding issue of the "@" in an email address (see #11014 and #7684, which I see you commented on).  Appreciate you also confirming that changing the cookie keys to non-encoded versions resolves the issue.  I'll mark this as a bug and review this with the team!

**Comment by cwomack** [comment]
@asp3, quick favor to ask of you to verify something.  Can you go into your `node_modules/@aws-amplify/core/lib-esm/UniversalStorage/index.js` and find this line: 
```
            ? new Cookies(context.req.headers.cookie)
```

And then change to: 
```
            ? new Cookies(decodeURIComponent(context.req.headers.cookie))
```

Then let me know if that resolves the issue? Thanks!

**Comment by asp3** [comment]
yes, i can confirm that it fixes the issue! @cwomack

**Comment by cwomack** [comment]
@asp3, thank you for testing that! I'll let the team know then and see if we can get a fix implemented on our side.

**Comment by asp3** [comment]
hey, any update on this issue? should we try to go ahead with a patch for the meantime? @cwomack

**Comment by cwomack** [comment]
@asp3, we have a PR in the works and are testing it currently.  I'll update you with more progress as soon as I can!

**Comment by asp3** [comment]
any idea when the release will be that includes this change? Thanks again for fixing this quickly! @cwomack

**Comment by cwomack** [comment]
@asp3, the fix is going to be included in the next release! Should be within the week, but I'll let you know if that gets delayed.

**Comment by WafikAlmasry** [comment]
if (!in_array(strtolower($config->cookieSameSite ?? Cookie::SAMESITE_LAX), Cookie::ALLOWED_SAMESITE_VALUES, true)) {
    throw CookieException::forInvalidSameSite($config->cookieSameSite);
    }
