### ISSUE TITLE
Voice bots on react-native

### ISSUE THREAD

**Issue by siddhantg-cbre** [aws-amplify/amplify-js#1196]
The chatbot tutorial here https://aws.github.io/aws-amplify/media/interactions_guide#create-your-chatbot doesn't have support for a voice bot, even though Amazon Lex does. I couldn't find this in the docs either, are voice bots explicitly not supported by Amplify?

**Comment by mbahar** [comment]
Hi @siddhantg-cbre, currently only text bots are supported. Voice support is in the roadmap.
