### ISSUE TITLE
Expo debugger error

### ISSUE THREAD

**Issue by AnasZineddine** [aws-amplify/amplify-js#11973]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Not applicable

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Memory: 104.23 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
    npm: 9.6.6 - ~/.nvm/versions/node/v20.2.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.140
    Safari: 16.1
  npmPackages:
    @aws-amplify/ui-react-native: ^1.2.27 => 1.2.27 
    @babel/core: ^7.20.0 => 7.22.15 
    @react-native-async-storage/async-storage: 1.18.2 => 1.18.2 
    @react-native-community/netinfo: 9.3.10 => 9.3.10 
    @react-native-community/progress-bar-android: ^1.0.5 => 1.0.5 
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: ^6.3.5 => 6.3.5 
    amazon-cognito-identity-js/internals:  undefined ()
    aws-amplify: ^5.3.10 => 5.3.10 
    expo: ~49.0.8 => 49.0.9 
    expo-document-picker: ^11.5.4 => 11.5.4 
    expo-status-bar: ~1.6.0 => 1.6.0 
    metro-config: ^0.79.0 => 0.79.0 (0.76.7)
    react: 18.2.0 => 18.2.0 
    react-native: 0.72.4 => 0.72.4 
    react-native-document-picker: ^9.0.1 => 9.0.1 
    react-native-get-random-values: ^1.9.0 => 1.9.0 
    react-native-url-polyfill: ^2.0.0 => 2.0.0 (1.3.0)
  npmGlobalPackages:
    @aws-amplify/cli: 12.4.0
    @expo/ngrok: 4.1.1
    corepack: 0.17.2
    npm: 9.6.6

```

</details>

### Describe the bug

I have an error when trying to run the expo debugger in my amplify project : 

<img width="1059" alt="Screenshot 2023-09-04 at 16 00 51" src="https://github.com/aws-amplify/amplify-js/assets/45426914/07a7b85b-a8ee-4b07-96ea-1b635b2a27a9">

### Expected behavior

I expect the debugger to open

### Reproduction steps

1. npm start
2. Press j to open the debugger

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello @AnasZineddine and glad you were able to get this figured out before we could even respond! Was it the exact issue/fix mentioned in that CLI repo comment? And was this a tutorial that was followed that potentially had outdated information? 

Just want to make sure there's nothing in our documentation that needs an update.  Thanks!

**Comment by cwomack** [comment]
@AnasZineddine, it looks like this might be a result of how the dependencies are conflicting when Expo is bundling. Can you see if excluding the entire `amplify/` directory entirely in your `metro.config.js` stops the errors with something like the following?  

```
const exclusionList = require('metro-config/src/defaults/exclusionList');

module.exports = {
  resolver: {
    blacklistRE: exclusionList([
      /#current-cloud-backend\/.*/,
      /\/amplify\//,
    ]),
  },
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
};
```

This shouldn't impact anything on your frontend code, but let me know if that's not the case.

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
