### ISSUE TITLE
Add GetUserData to obtain PreferredMfaSetting

### ISSUE THREAD

**Issue by MiroslavPetrik** [aws-amplify/amplify-js#1204]
Do you want to request a feature or report a bug?
feature
What is the current behavior?
When MFA is enabled with TOTP, the `getMFAOptions` returns `undefined`.
https://github.com/aws/aws-amplify/issues/360

However I need to know whether the MFA is enabled... I am able to get `PreferredMfaSetting: "SOFTWARE_TOKEN_MFA"` from a call to `cognitoUser.getUserData`
https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_GetUser.html

or use case 31 in 
https://github.com/aws/aws-amplify/tree/master/packages/amazon-cognito-identity-js

but there is no respective method in amplify so would be nice to have it, or enhance the `getMFAOptions`.

What is the expected behavior?
getMFAOptions returns info about TOTP.

**Comment by CHR15-** [comment]
@powerful23 || @hyandell 

I'm really confused at how this is supposed to work... We've got 2 flows:

PATH 1: `Auth.setPreferredMFA(user, SMS)`
PATH 2: `Auth.setPreferredMFA(user, TOTP);`

when we run `Auth.currentAuthenticatedUser()` after these flows to get the mfa preference.. we get the following response:

PATH 1
```
{  
   "MFAOptions":[  
      {  
         "AttributeName":"phone_number",
         "DeliveryMedium":"SMS"
      }
   ],
   "UserAttributes":[  
      {  
         "Name":"sub",
         "Value":"uuid"
      },
      {  
         "Name":"email_verified",
         "Value":"true"
      },
      {  
         "Name":"name",
         "Value":"chris"
      },
      {  
         "Name":"phone_number_verified",
         "Value":"false"
      },
      {  
         "Name":"phone_number",
         "Value":"XXX"
      },
      {  
         "Name":"custom:signupdomain",
         "Value":"http://localhost:9001"
      },
      {  
         "Name":"email",
         "Value":"chris@example.com"
      }
   ],
   "Username":"UUID"
}
```

PATH 2:
```
{
   "PreferredMfaSetting":"SOFTWARE_TOKEN_MFA",
   "UserAttributes":[
      {
         "Name":"sub",
         "Value":"uuid"
      },
      {
         "Name":"email_verified",
         "Value":"true"
      },
      {
         "Name":"name",
         "Value":"chris"
      },
      {
         "Name":"custom:signupdomain",
         "Value":"http://localhost:9001"
      },
      {
         "Name":"email",
         "Value":"chris@example.com"
      }
   ],
   "UserMFASettingList":[
      "SOFTWARE_TOKEN_MFA"
   ],
   "Username":"uuid"
}
```

Surely both should follow the same response format? they are currently completely different.

**Comment by powerful23** [comment]
@MiroslavPetrik I agree. I created a new api for developers to get the current preferred mfa type: #1254
