### ISSUE TITLE
Auth.signIn() succeeds, but CognitoUser and/or access token is never returned.

### ISSUE THREAD

**Issue by SwhiteMHC** [aws-amplify/amplify-js#12053]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M2 Pro
    Memory: 57.75 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - /opt/homebrew/bin/npm
    pnpm: 8.7.5 - /opt/homebrew/bin/pnpm
    Watchman: 2023.08.14.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 117.0.5938.62
    Safari: 16.5
  npmPackages:
    @aws-amplify/ui-react-native: ^1.2.27 => 1.2.27 
    @babel/core: ^7.20.0 => 7.22.17 
    @babel/plugin-proposal-class-properties: ^7.18.6 => 7.18.6 
    @babel/plugin-proposal-decorators: ^7.22.15 => 7.22.15 
    @babel/preset-env: ^7.20.0 => 7.22.15 
    @babel/runtime: ^7.20.0 => 7.22.15 
    @react-native-async-storage/async-storage: ^1.19.3 => 1.19.3 
    @react-native-community/netinfo: ^9.4.1 => 9.4.1 
    @react-native/eslint-config: ^0.72.2 => 0.72.2 
    @react-native/metro-config: ^0.72.11 => 0.72.11 
    @react-navigation/native: ^6.1.7 => 6.1.7 
    @react-navigation/native-stack: ^6.9.13 => 6.9.13 
    @testing-library/jest-native: ^5.4.3 => 5.4.3 
    @testing-library/react-native: ^12.2.2 => 12.3.0 
    @tsconfig/react-native: ^3.0.0 => 3.0.2 
    @types/jest: ^29.5.4 => 29.5.4 
    @types/react: ^18.0.24 => 18.2.21 
    @types/react-test-renderer: ^18.0.0 => 18.0.1 
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: ^6.3.5 => 6.3.5 
    amazon-cognito-identity-js/internals:  undefined ()
    aws-amplify: ^5.3.10 => 5.3.10 
    babel-jest: ^29.2.1 => 29.7.0 
    bac-rn-module: github:managedhealth/bac-rn-module => 1.0.0 
    eslint: ^8.19.0 => 8.49.0 
    jest: ^29.2.1 => 29.7.0 
    metro-react-native-babel-preset: 0.76.8 => 0.76.8 (0.76.7)
    mobx: ^6.10.2 => 6.10.2 
    mobx-react-lite: ^4.0.4 => 4.0.4 
    native-base: ^3.4.28 => 3.4.28 
    nativewind: ^2.0.11 => 2.0.11 
    prettier: ^2.4.1 => 2.8.8 
    react: 18.2.0 => 18.2.0 
    react-native: 0.72.4 => 0.72.4 
    react-native-dotenv: ^3.4.9 => 3.4.9 
    react-native-get-random-values: ^1.9.0 => 1.9.0 
    react-native-safe-area-context: ^4.7.2 => 4.7.2 
    react-native-screens: ^3.24.0 => 3.25.0 
    react-native-svg: ^12.5.1 => 12.5.1 
    react-native-url-polyfill: ^2.0.0 => 2.0.0 (1.3.0)
    react-test-renderer: 18.2.0 => 18.2.0 
    tailwindcss: 3.3.2 => 3.3.2 
    typescript: 4.8.4 => 4.8.4 
  npmGlobalPackages:
    @aws-amplify/cli: 12.4.0
    @graphql-cli/serve: 4.1.0
    amplify: 0.0.11
    appium-doctor: 1.16.2
    appium: 2.1.3
    graphql-cli: 4.1.0
    graphql: 16.8.0
    npm: 9.8.1
    react-devtools: 4.28.0
    react-native-cli: 2.0.1
    react-native-log-ios: 1.5.0
    saucectl: 0.156.0
```
</details>

### Describe the bug

When using the Amplify UI Authenticator, or the Auth.signIn method, and the USER_PASSWORD_AUTH authentication flow type, on successful sign in, nothing is returned, even though the network shows a 200 response with an access token. The target child component is not rendered either.

### Expected behavior

After Auth.signIn runs, I anticipate the cognito user and/or the access token to be returned for future requests, OR for the child component to be rendered instead of the UI.

### Reproduction steps

I followed the instructions located here: https://ui.docs.amplify.aws/react-native/getting-started/installation

### Code Snippet

```javascript
// Put your code below this line.
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 */

import React from 'react';
import {CustomNavigationStack} from './src/navigation/CustomNavigationStack';
import {NativeBaseProvider} from 'native-base';

import {Amplify, Auth} from 'aws-amplify';
import {Authenticator} from '@aws-amplify/ui-react-native';

import awsExports from './src/aws-exports';
Amplify.configure(awsExports);
Auth.configure({
  authenticationFlowType: 'USER_PASSWORD_AUTH',
});

function App(): JSX.Element {
  return (
    <Authenticator.Provider>
      <Authenticator
        services={{
          handleSignIn: async formData => {
            let {username, password} = formData;
            // custom username
            username = username;
            password = password;
            return Auth.signIn({
              username,
              password,
            });
          },
        }}>
        <NativeBaseProvider>
          <CustomNavigationStack />
        </NativeBaseProvider>
      </Authenticator>
    </Authenticator.Provider>
  );
}

export default App;

```

### Log output

<details>

```
// Put your logs below this line

FLIPPER Network Response Body (Values removed)

{"AuthenticationResult":{"AccessToken":"","ExpiresIn":3600,"IdToken":"","RefreshToken":"","TokenType":"Bearer"},"ChallengeParameters":{}}


```
</details>

### aws-exports.js

```javascript
onst awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_My5gzt1vU",
    "aws_user_pools_web_client_id": "",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};
```

### Mobile Device

iPhone 14, iPhone SE, iPhone 6, Android Samsung Galaxy

### Additional information and screenshots

![Screenshot 2023-09-14 at 9 10 19 AM](https://github.com/aws-amplify/amplify-js/assets/141669959/e7205d3c-8798-4cd7-ae4a-84d0261f987f)

**Comment by cwomack** [comment]
Hello, @SwhiteMHC 👋.   Just to confirm, have you [configured your app](https://docs.amplify.aws/lib/auth/switch-auth/q/platform/js/#set-up-auth-backend) within the console to allow the implementation of 'USER_PASSWORD_AUTH`?

**Comment by SwhiteMHC** [comment]
Yes.

**Comment by cwomack** [comment]
@SwhiteMHC, apologies for the delayed reply on this issue.  With the release of the latest major version of Amplify (aws-amplify@>6), we highly recommend updating to the most recent version. Are you able to upgrade and see if this issue persists? 

Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.

**Comment by SwhiteMHC** [comment]
@cwomack Yes. I have successfully migrated to version 6 and functionality is now working as expected.

**Comment by cwomack** [comment]
@SwhiteMHC, appreciate the confirmation! I'll close out the issue then and feel free to create any new issues related to v6 if you run into further blockers.
