### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 3): while sending data from form to aws data model

### ISSUE THREAD

**Issue by TheShivaa** [aws-amplify/amplify-js#12054]
### Which Specific Feature is your question related to?

Data Model - Content - AWS Amplify

### Question

TypeError: Symbol.asyncIterator is not defined.
TypeError: Symbol.asyncIterator is not defined.

This is what I am getting for sending my name, bio, image, and gender from my sign-up form to aws data model and I am not sure how to handle this error. Although I have configured my aws amplify correctly.

  const save = async () => {
        if (!isValid()) {
            console.warn('Not Valid');
            return;
        }
    
        await DataStore.save(
            new User({
                "name": "",
                "image": 'https://media.vanityfair.com/photos/5a7b182c9b38580e8603ca4f/master/w_2560%2Cc_limit/elon-musk-showman-rocket.jpg',
                "bio": "",
                "gender": {gender},
                "lookingFor": {gender}
            })
        );
    };

**Comment by cwomack** [comment]
Hello, @TheShivaa 👋.  Can you clarify which version of Amplify you're currently on or share your `package.json`?  This looks like it's related to an older issue (#8176) that appears to have a [workaround](https://github.com/aws-amplify/amplify-js/issues/8176#issuecomment-827632909) that's helped quite a few people. Let me know if the steps in that comment help resolve the error!

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. Let us know if the above comment and workaround resolved the issue so that we can determine if documentation updates are needed.  

Thank you!
