### ISSUE TITLE
Webpack command not found

### ISSUE THREAD

**Issue by simonmcho** [aws-amplify/amplify-js#12063]
"It doesn't even go to the step where webpack should run.

/bin/sh: ./node_modules/.bin/webpack: No such file or directory

Webpack doesn't exists although it was just installed in the previous step, it has nothing to do with webpack config.

**Anyway, I discovered something really strange. If I set NODE_ENV env var to something else than 'production', everything works fine.**

Thanks"

_Originally posted by @ionutcirja in https://github.com/aws-amplify/amplify-js/issues/5933#issuecomment-635800469_

This problem still exists in Amplify as of Sep 14, 2023. I've been trying for nearly 2 weeks to try and figure out why the `webpack` command could not be found.

I can't seem to find any root reason for setting`NODE_ENV` environment variable to `production` would cause this issue.

**Comment by nadetastic** [comment]
Hi @simonmcho, thanks for opening this issue. There are few questions I'd like to ask as we look into this:
- What version of amplify are you seeing this on?
- Are there any specific reproduction steps you could share?
- Any specific frameworks you are using here? (react, angular, none)
- Are you able to also share what version of webpack you are using,or better yet share your package.json?

**Comment by nadetastic** [comment]
Following up here @simonmcho - going to close this issue due to no response. If you still need assistance let me know.
