### ISSUE TITLE
Question - Why Mobile Hub adds two apps in cognito when we add an existing user pool to our Mobile Hub project

### ISSUE THREAD

**Issue by josoroma** [aws-amplify/amplify-js#1206]
I was wondering... why Mobile Hub adds two apps when we add an existing user pool to our Mobile Hub project:

myapp_userpoolapp_MOBILEHUB_333

myapp_userpoolapp_MOBILEHUB_333 web

Thanks!

**Comment by mlabieniec** [comment]
I believe the reason for this is so that data loss does not occur on your current user pool. 

For new projects we are recommending the Amplify CLI now which using cloudformation directly:
https://github.com/aws-amplify/amplify-cli
