### ISSUE TITLE
After timeout get Cannot read properties of undefined (reading 'byteLength') Storage

### ISSUE THREAD

**Issue by shopizer-ecommerce** [aws-amplify/amplify-js#12064]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Storage

### Amplify Categories

storage

### Environment information

System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 825.82 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
  Browsers:
    Chrome: 116.0.5845.110
    Safari: 14.1.2
  npmPackages:
    @aws-amplify/cli: ^12.4.0 => 12.4.0 
    @headlessui/react: ^1.7.17 => 1.7.17 
    @heroicons/react: ^2.0.18 => 2.0.18 
    @tailwindcss/forms: ^0.5.5 => 0.5.6 
    @testing-library/jest-dom: ^5.16.5 => 5.17.0 
    @testing-library/react: ^13.4.0 => 13.4.0 
    @testing-library/user-event: ^13.5.0 => 13.5.0 
    autoprefixer: ^10.4.8 => 10.4.15 
    aws-amplify: ^4.3.42 => 4.3.46 
    axios: ^1.2.0 => 1.5.0 (0.26.0, 0.26.1)
    moment: ^2.29.4 => 2.29.4 
    nanoid: ^4.0.0 => 4.0.2 (3.3.6)
    postcss: ^8.4.16 => 8.4.29 (7.0.39)
    react: ^18.2.0 => 18.2.0 
    react-calendar: ^4.6.0 => 4.6.0 
    react-dom: ^18.2.0 => 18.2.0 
    react-icons: ^4.10.1 => 4.11.0 
    react-modal: ^3.16.1 => 3.16.1 
    react-phone-number-input: ^3.2.12 => 3.3.6 
    react-phone-number-input/commonjs:  undefined ()
    react-phone-number-input/core:  undefined ()
    react-phone-number-input/flags:  undefined ()
    react-phone-number-input/input-core:  undefined ()
    react-phone-number-input/input-max:  undefined ()
    react-phone-number-input/input-min:  undefined ()
    react-phone-number-input/input-mobile:  undefined ()
    react-phone-number-input/max:  undefined ()
    react-phone-number-input/min:  undefined ()
    react-phone-number-input/mobile:  undefined ()
    react-phone-number-input/react-hook-form:  undefined ()
    react-phone-number-input/react-hook-form-core:  undefined ()
    react-phone-number-input/react-hook-form-input:  undefined ()
    react-phone-number-input/react-hook-form-input-core:  undefined ()
    react-phone-number-input/react-native-input:  undefined ()
    react-phone-number-input/react-styleguidist:  undefined ()
    react-router-dom: ^6.3.0 => 6.16.0 
    react-scripts: 5.0.1 => 5.0.1 
    react-select: ^5.6.1 => 5.7.4 
    react-table: ^7.8.0 => 7.8.0 
    tailwindcss: ^3.1.8 => 3.3.3 
    web-vitals: ^2.1.4 => 2.1.4 
  npmGlobalPackages:
    corepack: 0.17.0
    npm: 8.19.4

### Describe the bug

Single page application using storage gives the error above when the application times ou

Tried try catch
Tried ErrorBoundary

Any test i can do

### Expected behavior

try catch should intercept

### Reproduction steps

npm start
log on amplify / cognito

Open main page

Let it timeout

reload

### Code Snippet

```javascript
        Storage.get(imgName)
          .then(url => {
            console.log('Image Get ' + JSON.stringify(url));
            var myRequest = new Request(url);
            console.log('Generated Image URL:', url);
            console.log('Request Object:', myRequest);
            fetch(myRequest).then(function(response) {
              if (response.status === 200) {
                //console.log('Image Url ' + url);
                setImage(url);
              }
            });
          })
          .catch(err => console.log(err));
        } catch(error) {
          console.log('Error while getting picture');
        }

```

### Log output

<details>

```
Cannot read properties of undefined (reading 'byteLength')
TypeError: Cannot read properties of undefined (reading 'byteLength')
    at isEmptyData (http://localhost:3000/static/js/bundle.js:29355:15)
    at Sha256.update (http://localhost:3000/static/js/bundle.js:28457:32)
    at Sha256.update (http://localhost:3000/static/js/bundle.js:28277:15)
    at hmac (http://localhost:3000/static/js/bundle.js:67791:8)
    at http://localhost:3000/static/js/bundle.js:67732:32
    at step (http://localhost:3000/static/js/bundle.js:144419:17)
    at Object.next (http://localhost:3000/static/js/bundle.js:144368:14)
    at http://localhost:3000/static/js/bundle.js:144342:67
    at new Promise (<anonymous>)
    at __awaiter (http://localhost:3000/static/js/bundle.js:144324:10)
ERROR
Cannot read properties of undefined (reading 'byteLength')
TypeError: Cannot read properties of undefined (reading 'byteLength')
    at isEmptyData (http://localhost:3000/static/js/bundle.js:29355:15)
    at Sha256.update (http://localhost:3000/static/js/bundle.js:28457:32)
    at Sha256.update (http://localhost:3000/static/js/bundle.js:28277:15)
    at hmac (http://localhost:3000/static/js/bundle.js:67791:8)
    at http://localhost:3000/static/js/bundle.js:67732:32
    at step (http://localhost:3000/static/js/bundle.js:144419:17)
    at Object.next (http://localhost:3000/static/js/bundle.js:144368:14)
    at http://localhost:3000/static/js/bundle.js:144342:67
    at new Promise (<anonymous>)
    at __awaiter (http://localhost:3000/static/js/bundle.js:144324:10)

```

</details>

**Comment by cwomack** [comment]
Hello, [@shopizer-ecommerce](https://github.com/shopizer-ecommerce) and thanks for opening this issue. Usually when there’s a `byteLength` error, there’s an empty object in the response tied to either duplicated calls or missing permissions. Will you please verify the following:
- Does the identity pool for your app have the expected IAM permissions for the S3 bucket access?
- Are you experiencing this in both dev mode and production builds?
- Is the call to Storage.get() within a useEffect hook by chance?

**Comment by shopizer-ecommerce** [comment]
Hi @cwomack 

Yes under normal circumstances the app runs well, logon and pages are running with Storage.put and Storage.get. 
I leave my browser open for a while, reload the page should display the page but since upgrading amplify i started having this issue

yes storage.get happens during useEffect(() => { ...

**Comment by cwomack** [comment]
@shopizer-ecommerce, appreciate the reply! Have a few follow up questions for you:

- When you mention that you "leave browser open for a while", how long is that for?  
- I'm also curious to know what the durations are set for on your access token and refresh token.  What is the duration set for on both of these? This can be found in the Cognito console under Cognito > [User Pool for the app] > App Integration > App Client List > Click on your app client, then you'll see the configurations under the "App client information" section.
- Since you mentioned the code that results in this error is within a useEffect hook, can you verify if this happens in production builds as well (and not just dev mode)?

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
