### ISSUE TITLE
Support of Dispatcher for fetch in case of an HttpProxy

### ISSUE THREAD

**Issue by Tatsukyo** [aws-amplify/amplify-js#12071]
### Is this related to a new or existing framework?

Vue

### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

Currently using Amplify with SSR on a network with an HttpProxy
After investigating, it seems its not possible to add a proxy agent
I found https://github.com/aws-amplify/amplify-js/pull/724 which I think do what I need

If I understand right:

Right there we pass the options for the fetch which use undici
```js
  _proto.request = function request(operation, params, callback) {
    var headers = {
      'Content-Type': 'application/x-amz-json-1.1',
      'X-Amz-Target': "AWSCognitoIdentityProviderService." + operation,
      'X-Amz-User-Agent': (0, _UserAgent.getAmplifyUserAgent)(),
      'Cache-Control': 'no-store'
    };
    var options = Object.assign({}, this.fetchOptions, {
      headers: headers,
      method: 'POST',
      mode: 'cors',
      body: JSON.stringify(params)
    });
    var response;
    var responseJsonData;
    fetch(this.endpoint, options).then(function (resp) { //using Undici so we have to use a dispatcher
      response = resp;
      return resp;
    }
```

After looking a lil more, it seems undici use either the GlobalDispatcher or the dispatcher of the options
```js
module.exports.fetch = async function fetch(resource) {
  const dispatcher = arguments[1] && arguments[1].dispatcher || getGlobalDispatcher();
  try {
    return await fetchImpl.apply(dispatcher, arguments);
  } catch (err) {
    Error.captureStackTrace(err, this);
    throw err;
  }
};
```

Touching the GlobalDispatcher seems kind of bad to me so I'm looking to pass the first dispatcher  (in the options) so the only way is to impact this.fetchOptions defined there
```js
  /**
   * Constructs a new AWS Cognito Identity Provider client object
   * @param {string} region AWS region
   * @param {string} endpoint endpoint
   * @param {object} fetchOptions options for fetch API (only credentials is supported)
   */
  function Client(region, endpoint, fetchOptions) {
    this.endpoint = endpoint || "https://cognito-idp." + region + ".amazonaws.com/";
    var _ref = fetchOptions || {},
      credentials = _ref.credentials;
    this.fetchOptions = credentials ? {
      credentials: credentials
    } : {};
  }
```

Am I missing something or is it not supported? or maybe it's not the way we shall do it ? 

### Describe the solution you'd like

Add the fetchOptions in the class AuthOptions so we can type :
```js
		const {
			userPoolId,
			userPoolWebClientId,
			cookieStorage,
			oauth,
			region,
			identityPoolId,
			mandatorySignIn,
			refreshHandlers,
			identityPoolRegion,
			clientMetadata,
			endpoint,
			storage,
			fetchOptions
		} = this._config;
```

so we can:
```js
			const userPoolData: ICognitoUserPoolData = {
				UserPoolId: userPoolId,
				ClientId: userPoolWebClientId,
				endpoint,
				fetchOptions
			};
```

and it get used by 

```js
  function CognitoUserPool(data, wrapRefreshSessionCallback) {
    var _ref = data || {},
      UserPoolId = _ref.UserPoolId,
      ClientId = _ref.ClientId,
      endpoint = _ref.endpoint,
      fetchOptions = _ref.fetchOptions,
      AdvancedSecurityDataCollectionFlag = _ref.AdvancedSecurityDataCollectionFlag;
    if (!UserPoolId || !ClientId) {
      throw new Error('Both UserPoolId and ClientId are required.');
    }
    if (UserPoolId.length > USER_POOL_ID_MAX_LENGTH || !/^[\w-]+_[0-9a-zA-Z]+$/.test(UserPoolId)) {
      throw new Error('Invalid UserPoolId format.');
    }
    var region = UserPoolId.split('_')[0];
    this.userPoolId = UserPoolId;
    this.clientId = ClientId;
    this.client = new _Client["default"](region, endpoint, fetchOptions);
```

### Describe alternatives you've considered

GlobalDispatcher but seems breaking fetch in other case

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cwomack** [comment]
@Tatsukyo, thank you for creating this issue.  I'll mark this as a feature request for now, but have some clarifying questions to make sure we're capturing the "ask" properly.  It sounds like you've implemented SSR in your app... but this is specifically asking for improved client-side proxy support via more options for proxy configurations.

Does that sounds correct? And can you clarity which API/package you're currently using as well as what the use case of their proxy agent would be?

**Comment by Tatsukyo** [comment]
@cwomack, to be honest, I dont need it anymore, we will just let the client navigator render it itself.

If it's CSR, there is no need to set the agent since it is the client navigator which should be configured with their things but if it's SSR, since it's the server, we shall set an appropriate agent if needed 

Using the doc: https://aws.amazon.com/fr/blogs/mobile/ssr-support-for-aws-amplify-javascript-libraries/

`user = await Auth.currentAuthenticatedUser();` will fetch cognito to get the attributes of the current user of the cookie
and get a timeout in my case because my server is not supposed to get out without an http proxy

I tried with :
`setGlobalDispatcher(new ProxyAgent('https://my.proxy.agent/'))`
It resolves the call but it breaks ohmyfetch which is used by Nuxt so no luck for me

Both are coming from undici:
`import { setGlobalDispatcher, ProxyAgent } from 'undici'`

**Comment by cwomack** [comment]
@Tatsukyo, appreciate the follow up.  I'll close out this issue then if it's no longer needed on your end.  Should there be any further issues regarding use cases requiring agent/proxy support, feel free to create a new feature request!
