### ISSUE TITLE
VS Code and Amplify queries ans mutations code errors

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/amplify-js#12072]
### Is this feature request related to a new or existing Amplify category?

api

### Describe the feature you'd like to request

Is it possible to detect and display schema errors in VS Code when we do API.graphql queries and mutations ?

Because currently no error is detected.

### Describe the solution you'd like

VS Code plugin to detect schema errors with queries ans mutations.

### Describe alternatives you've considered

I launch my web app and I see errors after.
Waste of time.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by cwomack** [comment]
Hello, @rudyhadoux and thank you for opening this issue.  We've marked this as a feature request because it sounds like you're looking for us to surface types and have the GraphQL API enforce those types/surface build errors in VS Code.  Does that sound correct?

**Comment by cwomack** [comment]
@rudyhadoux, appreciate the clarity.  I've got good news then... this feature will be available in the next major version of Amplify! I'll ensure this issue gets an update when we release it.

**Comment by rudyhadoux** [comment]
Good news indeed. 
version 13 ?

**Comment by cwomack** [comment]
@rudyhadoux, I think you might be referencing the CLI version.  The most recent version of the `aws-amplify` package is 5.3.11, so once we bump to the next major version (**v6**) this feature should be included.  

Since this issue was transferred from the CLI repo, I'm not sure what version you're currently on... but you can check your `package.json` to verify.
