### ISSUE TITLE
Unable to resolve "core-js/full/symbol/async-iterator"

### ISSUE THREAD

**Issue by popoviciyoel** [aws-amplify/amplify-js#12070]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

DataStore

### Amplify Categories

api

### Environment information

<details>

```
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M2
    Memory: 141.69 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 8.5.1 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 16.3
  npmPackages:
    @babel/core: ^7.20.0 => 7.22.20 
    @react-native-async-storage/async-storage: 1.18.2 => 1.18.2 
    @react-native-community/netinfo: 9.3.10 => 9.3.10 
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: ^6.3.6 => 6.3.6 
    amazon-cognito-identity-js/internals:  undefined ()
    aws-amplify: ^5.3.11 => 5.3.11 
    expo: ~49.0.11 => 49.0.11 
    expo-status-bar: ~1.6.0 => 1.6.0 
    ini: ^1.3.5 => 1.3.8 
    inquirer: ^6.5.1 => 6.5.2 
    react: 18.2.0 => 18.2.0 
    react-native: 0.72.4 => 0.72.4 
  npmGlobalPackages:
    @aws-amplify/cli: 12.0.0
    corepack: 0.17.0
    eas-cli: 5.2.0
    expo-cli: 6.3.10
    npm: 9.5.1
    react-native-cli: 2.0.1
    sass: 1.63.6
    serve: 14.2.0



```

</details>

### Describe the bug

I follow AWS Amplify's DataStore Getting started documentation, and during bundling I receive

iOS Bundling failed 28ms
Unable to resolve "core-js/full/symbol/async-iterator" from "App.js"

### Expected behavior

I expect the module to be installed and resolved when following the Amplify Datastore guide. I'm guessing maybe it has to do with the Expo or React Native version I'm running

### Reproduction steps

npx create-expo-app AmplifyDataStoreExpo
cd AmplifyDataStoreExpo
npx amplify-app@latest
expo install aws-amplify amazon-cognito-identity-js @react-native-community/netinfo @react-native-async-storage/async-storage

npm install aws-amplify

then import 'core-js/full/symbol/async-iterator' in entry point of app

### Code Snippet

```javascript
import 'core-js/full/symbol/async-iterator';

import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View , Button} from 'react-native';
import { DataStore } from 'aws-amplify';
import {Post} from './src/models'
 
export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
      <Button title='Save Post' onPress={() => savePost()}/>
    </View>
  );
}


```

### Log output

<details>

```
iOS Bundling failed 28ms
Unable to resolve "core-js/full/symbol/async-iterator" from "App.js"
iOS Bundling failed 33ms
Unable to resolve "core-js/full/symbol/async-iterator" from "App.js"


```

</details>

**Comment by cwomack** [comment]
Hey, @popoviciyoel 👋.  It looks like if you were using the [React Native docs for DataStore](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/react-native/#option-1-platform-integration) and chose to use Expo, the block switcher may not have had `core-js` listed in the dependencies.  This might be a documentation issue (which we'll get updated if so), but can you see if running `npm i core-js` resolves your issue? 

You may also need to delete you `package-lock.json` along with your `node_modules`, then reinstall the dependencies with `npm i`.  Let me know if that resolves the issue!

**Comment by popoviciyoel** [comment]
> Hey, @popoviciyoel 👋. It looks like if you were using the [React Native docs for DataStore](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/react-native/#option-1-platform-integration) and chose to use Expo, the block switcher may not have had `core-js` listed in the dependencies. This might be a documentation issue (which we'll get updated if so), but can you see if running `npm i core-js` resolves your issue?
> 
> You may also need to delete you `package-lock.json` along with your `node_modules`, then reinstall the dependencies with `npm i`. Let me know if that resolves the issue!

Hi @cwomack, I resolved this issue by explicitly installing the core-js package! I hope the guide gets updated for future references!
