### ISSUE TITLE
Android: Push Notification icon on top left corner is default to android icon

### ISSUE THREAD

**Issue by LYevhen** [aws-amplify/amplify-js#12080]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Push Notifications

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 72.98 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 20.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.4 - /opt/homebrew/bin/npm
    Watchman: 2023.05.15.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 117.0.5938.88
    Safari: 16.6
  npmGlobalPackages:
    npm: 9.6.4

```

</details>

### Describe the bug

When Push notification is received instead of app icon in top left corner of push notification I get default android icon, image is shown bellow.
<img width="547" alt="image" src="https://github.com/aws-amplify/amplify-js/assets/44976185/690e69a7-6dbe-4705-a5b9-6c667291ed6a">

iOS is as expected, everything is fine, also on deprecated SDK it is working fine for both platforms

### Expected behavior

Push Notification Icon to be app icon, or icon which is stored in assets folder
![image](https://github.com/aws-amplify/amplify-js/assets/44976185/c602a805-093e-4dc6-875a-a069278caba9)

### Reproduction steps

I'm working on migration from old Push notification SDK to new.
followed instructions on https://docs.amplify.aws/lib/push-notifications/migrate-from-previous-version/q/platform/react-native/
read all and checked from https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/react-native/
install
configure
build project
send push notification from amazon console
Observe on real android device.
In addition I've tried to override default icon for push notification in "android/app/src/main/AndroidManifest.xml" by adding
```
<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource=“@drawable/ic_launcher" />
or
<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@mipmap/ic_launcher" />
```
regenerated assets with android studio image assets according to https://developer.android.com/, cleaned build and recompiled.

package dependancies
```
aws-amplify ^5.3.10
@aws-amplify/rtn-push-notification ^1.1.7
amazon-cognito-identity-js 6.3.5
@react-native-community/netinfo 9.4.1
@react-native-async-storage/async-storage ^1.19.3
react-native-get-random-values ^1.9.0
react-native-url-polyfill ^2.0.0
```

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

```javascript
const config = {
  awsProjectRegion: 'xxx',
  awsCognitoIdentityPoolId: 'xxx',
  awsCognitoRegion: 'xxx',
  awsUserPoolsId: 'xxx',
  awsUserPoolsWebClientId: 'xxx',
  oauth: {},
  awsAppsyncGraphqlEndpoint: 'xxx',
  awsAppsyncRegion: 'xxx',
  awsAppsyncAuthenticationType: 'AMAZON_COGNITO_USER_POOLS',
  Notifications: {
    Push: {
      AWSPinpoint: { appId: 'xxx', region: 'xxx', },
    },
  },
}
```

### Mobile Device

Samsung SM-G975U1 - 12

### Mobile Operating System

Android 12

### Additional information and screenshots

I'll appreciate if @tannerabread could join discussion, he helped me before with old SDK

**Comment by ZakariaNaija** [comment]
For a temporary solution, you can just add  ic_launcher_foreground.png asset in drawable folders and you'll get it instead of the default one. That's because of util used in `com.amplifyframework.pushnotifications.pinpoint` called `PushNotificationsUtils` where the icon is hardcoded like this: 

`builder.apply { ` 
`                setContentTitle(payload.title)` 
                `setContentText(payload.body)`  
                `setSmallIcon(R.drawable.ic_launcher_foreground)` 
                `setContentIntent(pendingIntent)` 
                `setPriority(NotificationCompat.PRIORITY_DEFAULT)` 
                `setLargeIcon(largeImageIcon)` 
                `setAutoCancel(true)` 
            `}`

**Comment by LYevhen** [comment]
@ZakariaNaija Thank You so much, it worked for me, You saved my day.

**Comment by cwomack** [comment]
Hey, @LYevhen 👋.  @ZakariaNaija was quick to beat us to an answer and glad it provided the workaround you needed.  We love it when the Amplify community steps up to help and provide answers, so thank you @ZakariaNaija!  

If there's further questions, feel free to comment back... but we'll leave this issue closed for now.

**Comment by aalindQuantel** [comment]
@ZakariaNaija do i need to add this ic_launcher_foreground to res>drawable or res>mipmaps

**Comment by dylan-westbury** [comment]
This needs to be added to documentation 🙂
