### ISSUE TITLE
Have the possibility to compress the payload with the API functions

### ISSUE THREAD

**Issue by clementAC** [aws-amplify/amplify-js#1209]
Do you want to request a feature or report a bug?

it's a feature request =)

What is the expected behavior?

The expected behavior is the possibility to leverage an option mainly on post api requests in order to compress the payload. This feature can be great to have a faster user experience when transfering big data.

**Comment by jordanranz** [comment]
This can be done with API Gateway:
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-gzip-compression-decompression.html

Are you requesting the feature to be built into Amplify?

**Comment by clem91** [comment]
Yes i know it exist in api gateway. I'm talking about in implementation in client side with Amplify

**Comment by sammartinez** [comment]
@clementAC From Jordans response above this is possible today, Im curious if you have an idea of what the client side implementation would look like for this. Can you share or if this is not a use case you are looking for anymore please feel free to close the issue
