### ISSUE TITLE
Amplify Auth UI stores user tokens in local storage

### ISSUE THREAD

**Issue by matborowiak** [aws-amplify/amplify-js#12093]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Other

### Which UI component?

Authenticator

### How is your app built?

Next.js

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

After signing in using Amplify Auth UI all the tokens end up in local storage. This isn't considered a secure practice. Also Amazon in all Cognito docs themselves advise using cookies for storing all the tokens, yet Amplify UI is using local storage. Why is that?

### What's the expected behaviour?

Tokens are stored as cookies and handled using typical good secuirty practices

### Help us reproduce the bug!

1. Deploy Amplify Auth UI 
2. Configure it with Cognito
3. Login using valid credentials
4. Inspect browser local storage

**Comment by matborowiak** [comment]
I have just realised this behaviour is configurable through aws-config object passed to Amplify.configure();

We can close it. Thanks.

**Comment by cwomack** [comment]
Hey there, @matborowiak 👋.  Glad you were able to resolve the issue on your own so quickly! The majority of developers use the `aws-exports` file generated by the CLI and pass it to `Amplify.configure()`, as you said. But if you need further customization, check out or documentation on the [Client Configuration](https://docs.amplify.aws/lib/client-configuration/configuring-amplify-categories/q/platform/js/) as well.  

Feel free to comment back with further questions or issues if needed.
