### ISSUE TITLE
Add a way to remove Hub listeners

### ISSUE THREAD

**Issue by tallpants** [aws-amplify/amplify-js#1210]
> Do you want to request a feature or report a bug?

Feature

> What is the current behavior?

No way to remove hub listeners

> What is the expected behavior?

Having a way to remove listeners from hub.

Like the title says, it'd be nice to have a way to remove listeners from the Hub.

**Comment by powerful23** [comment]
Thanks for your feedback.

**Comment by adilosa** [comment]
Added in #2235. This issue can probably be closed.

**Comment by powerful23** [comment]
@adilosa thanks.
