### ISSUE TITLE
AWS.config.credentials.params.IdentityId returning as undefined even though it's present in params

### ISSUE THREAD

**Issue by TWDBrob** [aws-amplify/amplify-js#12129]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1265U
    Memory: 11.80 GB / 30.78 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
  npmPackages:
    @aws-sdk/client-cognito-identity: ^3.405.0 => 3.405.0 
    @aws-sdk/client-cognito-sync: ^3.405.0 => 3.405.0 
    @aws-sdk/client-sns: ^3.408.0 => 3.408.0 
    @aws-sdk/credential-providers: ^3.405.0 => 3.405.0 
    @icon/foundation-icons: ^3.0.0-alpha.3 => 3.0.0-alpha.3 
    @reduxjs/toolkit: ^1.9.5 => 1.9.5 
    @reduxjs/toolkit-query:  1.0.0 
    @reduxjs/toolkit-query-react:  1.0.0 
    @testing-library/jest-dom: ^5.17.0 => 5.17.0 
    @testing-library/react: ^13.4.0 => 13.4.0 
    @testing-library/user-event: ^13.5.0 => 13.5.0 
    amazon-cognito-identity-js: ^6.3.4 => 6.3.4 
    amazon-cognito-identity-js/internals:  undefined ()
    aws-sdk: ^2.1446.0 => 2.1446.0 
    leaflet: ^1.9.4 => 1.9.4 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    react-icons: ^4.11.0 => 4.11.0 
    react-redux: ^8.1.2 => 8.1.2 
    react-scripts: 5.0.1 => 5.0.1 
    sass: ^1.68.0 => 1.68.0 
    web-vitals: ^2.1.4 => 2.1.4 
  npmGlobalPackages:
    aws-cdk: 2.87.0
    corepack: 0.17.0
    npm: 9.5.1


```

</details>

### Describe the bug

For the following code:

```js
export const foo = async () => {
    const syncClient = new CognitoSyncClient({
        region: AWS.config.region,
        credentials: AWS.config.credentials,
    });
    console.log("params", AWS.config.credentials.params);
    console.log("Identity id", AWS.config.credentials.params.IdentityId);
    // snipped
}
```

I am getting the following output:

params {
...
IdentityId: "<**the expected identity id**>",

...

}
Identity id **undefined**

How is that possible?  If it matters, I set up AWS.config.credentials using the following code:

```js
const setAWSCredentials = (jwt) => {
    AWS.config.credentials = new AWS.CognitoIdentityCredentials({
        IdentityPoolId: appConfig.IdentityPoolId,
        Logins: {
            [appConfig.Logins.cognito.identityProviderName]: jwt,
        },
    });
    console.log("ever here");
    AWS.config.credentials.clearCachedId();
    AWS.config.credentials.refresh((err) => {
        return err ? err : null;
    });
};
```

### Expected behavior

When I dereference IdentityId, it should have the same value as what's found in the IdentityId field of AWS.config.credentials.params.

### Reproduction steps

Log in using 

```js
(username, password) => {
    const authenticationDetails = new AuthenticationDetails({
        Username: username,
        Password: password,
    });

    cognitoUser = getNewCognitoUser(username);

    return new Promise((resolve, reject) => {
        cognitoUser.authenticateUser(authenticationDetails, {
            onSuccess: function (result) {
                const err = setAWSCredentials(result.idToken.jwtToken);
                if (err) {
                    reject(err);
                } else {
                    resolve(result);
                }
                // AWS.config.credentials = new AWS.CognitoIdentityCredentials({
                //     IdentityPoolId: appConfig.IdentityPoolId,
                //     Logins: {
                //         [appConfig.Logins.cognito.identityProviderName]:
                //             result.idToken.jwtToken,
                //     },
                // });
                // AWS.config.credentials.clearCachedId();
                // AWS.config.credentials.refresh((err) => {
                //     err ? reject(err) : resolve(result);
                // });
            },
            onFailure: function (err) {
                reject(err);
            },
            newPasswordRequired: function (userAttributes, requiredAttributes) {
                reject({
                    code: "PasswordResetRequiredException",
                    message: "New Password Required",
                    newPasswordRequired: true,
                });
            },
        });
    });
};
```

### Code Snippet

```javascript
// Put your code below this line.
export const foo = async () => {
    const syncClient = new CognitoSyncClient({
        region: AWS.config.region,
        credentials: AWS.config.credentials,
    });
    console.log("params", AWS.config.credentials.params);
    console.log("Identity id", AWS.config.credentials.params.IdentityId);
    // snipped
}
```
### Log output

<details>

```
// Put your logs below this line


```

</details>
params 
IdentityId: "us-east-1:<the expected value>"
IdentityPoolId: "us-east-1:xxxxxxxxxxx"
Logins: {cognito-idp.us-east-1.amazonaws.com/us-east-1_xxxxxxxxxxx'}
RoleSessionName: "web-identity"
[[Prototype]]: Object

Identity id undefined

**Comment by TWDBrob** [comment]
The issue was that AWS.config.credentials.refresh takes a callback function and I needed to promisify it like this:

`const setAWSCredentials = (jwt) => {
    return new Promise((resolve, reject) => {
        AWS.config.credentials = new AWS.CognitoIdentityCredentials({
            IdentityPoolId: appConfig.IdentityPoolId,
            Logins: {
                [appConfig.Logins.cognito.identityProviderName]: jwt,
            },
        });
        AWS.config.credentials.clearCachedId();
        AWS.config.credentials.refresh((err) => {
            err ? reject(err) : resolve();
        });
    });
};`

and then modify the calling code:

`                const err = setAWSCredentials(result.idToken.jwtToken);
                if (err) {
                    reject(err);
                } else {
                    resolve(result);
                }`

like so:

`                setAWSCredentials(result.idToken.jwtToken)
                    .then(() => {
                        resolve(result);
                    })
                    .catch((err) => {
                        reject(err);
                    });`

**Comment by cwomack** [comment]
Hey, @TWDBrob and thank you for opening this issue. Were you able to resolve everything then with the updated code snippet in your comment above?  

The use of the `amazon-cognito-identity-js` package _without_ the Auth category being implemented is not well documented, so greatly appreciate your providing the additional code example for others that may find this if it unblocked you!
