### ISSUE TITLE
Pass extra remembered device information already received by list of devices API response

### ISSUE THREAD

**Issue by TheTimeWalker** [aws-amplify/amplify-js#12134]
### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

Currently, it is not possible to fetch the following information from saved devices:

- Status
- Last IP address used
- Creation timestamp
- Last modification timestamp
- Last Authentication timestamp

Cognito itself sends this information anytime a list of devices is being fetched which means that this already exists on Cognito, but is not available when used with the Authentication module.

### Describe the solution you'd like

The Authentication module should be extended to also pass the extra device information as it is already available by the API response.

### Describe alternatives you've considered

I have opened a pull request https://github.com/aws-amplify/amplify-js/pull/10174 on August 2022, which has been fully ignored by the team.

### Additional context

This change allows the client to show more information about the saved devices e.g. where the login location was via GeoIP, when the device has last been used and in combination with the pull request https://github.com/aws-amplify/amplify-js/pull/10510, it can be used for the user to immediately remove old or unknown devices.

I've decided to instead open a feature request issue to determine if the AmplifyJS team even wants this implemented at all or not. This is information which we need for our product, and we would like to not have to monkey patch it in internally but to have it generally available for all users of this framework.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cwomack** [comment]
Hello, @TheTimeWalker 👋. First and foremost, apologies that we didn't get you a response and further review on your PR (#10174).  I've marked this issue as a feature request and will be reviewing it with the team along with your PR.  I'll try and get you an update on both as soon as I can!

**Comment by cwomack** [comment]
@TheTimeWalker, with the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.

With the improvements in device information that's available when listing devices, we'll close this feature request out along with the PR associated with it.  We greatly appreciate you creating this issue to help drive this improvement in v6, and taking the time to make the PR as well.  Please upgrade to v6 to test this out yourself!
