### ISSUE TITLE
API Call (Lambda) when logged-in with Google

### ISSUE THREAD

**Issue by vinaykumarkas** [aws-amplify/amplify-js#1214]
Hi There,

Good Day.

I was using aws-amplify earlier to Authenticate users with AWS Congito user pool, used identity pool and usepool details to initialize aws-amplify and call lambda via api gateway. It was all working as expected.

Now, I am changing from AWS user pool to Google Authentication. I have created identity pool using my google client id, created a role.
I am able to login to the web application using google sign-in. But I am having issues in making API calls.

How do I initialize aws-amplify, so that I can make API calls using aws-amplify ? I followed: https://github.com/aws/aws-amplify/issues/542 but there I could't find answer for API calls.

Can you please help with some steps that can help me with configuration ?

**Comment by jordanranz** [comment]
Apologies for the late response here.

Have you followed this documentation:
https://aws-amplify.github.io/docs/js/api#using-rest

**Comment by elorzafe** [comment]
@vinaykumarkas are you still experiencing problems with this?

**Comment by jordanranz** [comment]
Going to close this due to this issue being stale. Please open a new issue if this problem still exists.
