### ISSUE TITLE
I have got multiple foreground push notifications.

### ISSUE THREAD

**Issue by koreahn** [aws-amplify/amplify-js#12179]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Push Notifications

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line

  System:
    OS: macOS 13.5.2
    CPU: (8) arm64 Apple M1
    Memory: 219.02 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    npm: 9.8.1 - /usr/local/bin/npm
    Watchman: 2023.07.24.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 117.0.5938.132
    Safari: 16.6
  npmPackages:
    @aws-amplify/rtn-push-notification: ^1.1.2 => 1.1.6 
    @aws-amplify/ui-react-native: ^1.2.23 => 1.2.27 
    @azure/core-asynciterator-polyfill: ^1.0.2 => 1.0.2 
    @babel/core: ^7.20.0 => 7.22.15 
    @babel/preset-env: ^7.20.0 => 7.22.15 
    @babel/runtime: ^7.20.0 => 7.22.15 
    @lunalee/react-native-raw-bottom-sheet: ^2.2.4 => 2.2.4 
    @react-native-async-storage/async-storage: ^1.19.1 => 1.19.3 
    @react-native-community/netinfo: ^9.4.1 => 9.4.1 
    @react-native-community/push-notification-ios: ^1.11.0 => 1.11.0 
    @react-native/eslint-config: ^0.72.2 => 0.72.2 
    @react-native/metro-config: ^0.72.9 => 0.72.11 
    @react-navigation/material-bottom-tabs: ^6.2.16 => 6.2.16 
    @react-navigation/native: ^6.1.7 => 6.1.7 
    @react-navigation/native-stack: ^6.9.13 => 6.9.13 
    @tsconfig/react-native: ^3.0.0 => 3.0.2 
    @types/react: ^18.0.24 => 18.2.21 
    @types/react-test-renderer: ^18.0.0 => 18.0.1 
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: ^6.3.1 => 6.3.5 
    amazon-cognito-identity-js/internals:  undefined ()
    aws-amplify: ^5.3.6 => 5.3.10 
    aws-sdk: ^2.1450.0 => 2.1452.0 
    babel-jest: ^29.2.1 => 29.6.4 
    eslint: ^8.19.0 => 8.48.0 
    jest: ^29.2.1 => 29.6.4 
    metro-react-native-babel-preset: 0.76.7 => 0.76.7 (0.76.8)
    prettier: ^2.4.1 => 2.8.8 
    react: 18.2.0 => 18.2.0 
    react-hook-form: ^7.45.4 => 7.46.1 
    react-native: 0.72.3 => 0.72.3 
    react-native-chart-kit: ^6.12.0 => 6.12.0 
    react-native-dialog: ^9.3.0 => 9.3.0 
    react-native-dotenv: ^3.4.9 => 3.4.9 
    react-native-geocoding: ^0.5.0 => 0.5.0 
    react-native-geolocation-service: ^5.3.1 => 5.3.1 
    react-native-get-random-values: ^1.9.0 => 1.9.0 
    react-native-image-picker: ^5.6.0 => 5.6.1 
    react-native-keyboard-aware-scroll-view: ^0.9.5 => 0.9.5 
    react-native-maps: ^1.7.1 => 1.7.1 
    react-native-maps-directions: ^1.9.0 => 1.9.0 
    react-native-push-notification: ^8.1.1 => 8.1.1 
    react-native-safe-area-context: ^4.7.1 => 4.7.2 
    react-native-screens: ^3.24.0 => 3.25.0 
    react-native-svg: ^13.13.0 => 13.13.0 
    react-native-upi-payment: ^1.0.4 => 1.0.4 
    react-native-url-polyfill: ^2.0.0 => 2.0.0 (1.3.0)
    react-native-vector-icons: ^10.0.0 => 10.0.0 
    react-test-renderer: 18.2.0 => 18.2.0 
    typescript: 4.8.4 => 4.8.4 
  npmGlobalPackages:
    @aws-amplify/cli: 12.4.0
    corepack: 0.15.3
    create-expo-app: 2.0.3
    create-react-native-app: 3.8.0
    eas-cli: 3.12.1
    expo-cli: 6.3.10
    npm: 9.8.1
    react-native-cli: 2.0.1
```

</details>

### Describe the bug

I have got multiple foreground push notifications.(The log is printed multiple times)

### Expected behavior

When the app is in the foreground and receives a push notification, the log should be printed only once

### Reproduction steps

run pinpoint.sendMessages function.

### Code Snippet

```javascript
// Put your code below this line.

// send push notifications
const sendPushNotifications = () => {
    const messageRequest = CreateMessageRequest();

    AWS.config.update({
      region: region,
      apiVersion: 'latest',
      credentials: {
        accessKeyId: AWS_ACCESS_KEY,
        secretAccessKey: AWS_SECRET_KEY,
      },
    });

    const params = {
      ApplicationId: PINPOINT_APP_ID,
      MessageRequest: messageRequest,
    };

    const pinpoint = new AWS.Pinpoint();

    pinpoint.sendMessages(params, function (err, data) {
      if (err) console.error(err);
      else {
        console.log('sendMessages result', data.MessageResponse);
      }
    });
  };

  const CreateMessageRequest = () => {
    const recipientPushToken = deviceToken;
    
    const messageRequest = {
      Addresses: {
        [recipientPushToken]: {
          ChannelType: 'GCM',
        },
      },
      MessageConfiguration: {
        GCMMessage: {
          RawContent: JSON.stringify({
            notification: {
              title: 'Hello Android',
              body: 'From PinPoint',
            },
            data: {
              message: 'data message',
              title: 'data title',
              custom: 'data custom',
            },
          }),
        },
      },
    };
    return messageRequest;
  };



// receive push notification foreground in App.js
useEffect(() => {
    handlePermissions();
    const listener = Notifications.Push.onTokenReceived(myTokenReceivedHandler);
    Notifications.Push.onNotificationReceivedInForeground(async message => {
      console.log('foreground', message);
      if (message.body) {
        Alert.alert(message.title, message.body);
      }
    });
    return () => listener && listener.remove();
  }, []);
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

----------------------------------------------------------------------
I have got multiple foreground push notifications.

As you can see in the source snippet above, the console.log('foreground', message); is in Notifications.Push.onNotificationReceivedInForeground. but the log is being printed multiple times below image. I'm not sure why this is happening, so if anyone has any insights, I would appreciate your help.

----------------------------------------------------------------------

<img width="801" alt="Screenshot 2023-10-04 at 3 00 25 AM" src="https://github.com/aws-amplify/amplify-js/assets/126758360/0c74d732-7d6a-42ab-aea9-0493d86570ac">

----------------------------------------------------------------------
One more thing. I'm trying to display an image in the push notification, but even after adding ImageIconUrl, ImageSmallIconUrl, and ImageUrl, the image is not appearing. When I test it on the Pinpoint Test Messaging page with the same URL, the image displays correctly. If anyone has any insights on this, please, I would appreciate your help.

----------------------------------------------------------------------
<img width="1196" alt="Screenshot 2023-10-04 at 3 09 40 AM" src="https://github.com/aws-amplify/amplify-js/assets/126758360/ad23a145-fc44-4b8b-96e7-bc189ff8429b">

**Comment by cwomack** [comment]
Hello, @koreahn 👋 and thanks for opening this issue.  Can you clarify if this happens every time your app is started? And do you potentially multiple listeners?  I'm curious to hear what the log output is on just a simple fresh boot of the app (e.g. if it has the same repeated behavior) vs. if the multiple logs are happening due to "hot reloads" potentially.

**Comment by koreahn** [comment]
@cwomack . Thank you for your reply.

At first, when I launched the app, I received notifications only once from Notifications.Push.onNotificationReceivedInForeground. However, when I add or remove most of the items in the GCMMessage object below (e.g., Action, ImageUrl, etc.), the log is printed one more time. It happens not only when I add the lines but also when I delete lines. As I mentioned in my original question, I'm testing while adding and removing ImageIconUrl, ImageSmallIconUrl, ImageUrl, etc., to add an icon to the push notification, but the icon doesn't appear, and only the log is added.
I have only one listener, and I don't think it's because of 'hot reloads.'

Thank you again for your response. If you have any information regarding the push notification icon, please provide assistance with that as well.


```
MessageConfiguration: {
        GCMMessage: {
          Action: 'OPEN_APP',
          ImageUrl:
            'https://www.domain.com/ic_notification.png',
          RawContent: JSON.stringify({
            notification: {
              title: 'Hello Android',
              body: 'From PinPoint',
            },
            data: {
              message: 'data message',
              title: 'data title',
              custom: 'data custom',
            },
          }),
        },
      },
```

**Comment by koreahn** [comment]
Today, as soon as I launched the app, I received multiple notifications. (Now, this happens every time my app is started) the console.log and Alert.alert in the code are being called multiple times. I'll rewrite the code below. If you need any additional information, please let me know.

Any advice will be greatly helpful. Even small suggestions are welcome. Thanks.



```
  useEffect(() => {
    handlePermissions();
    const listener = Notifications.Push.onTokenReceived(myTokenReceivedHandler);
    Notifications.Push.onNotificationReceivedInForeground(async message => {
      console.log('foreground', message);
      if (message.body) {
        Alert.alert(message.title, message.body);
      }
    });
    return () => listener && listener.remove();
  }, []);
```

**Comment by cwomack** [comment]
@koreahn, regarding the questions about the image and Pinpoint here: 

> One more thing. I'm trying to display an image in the push notification, but even after adding ImageIconUrl, ImageSmallIconUrl, and ImageUrl, the image is not appearing. When I test it on the Pinpoint Test Messaging page with the same URL, the image displays correctly. If anyone has any insights on this, please, I would appreciate your help.

I'm not certain what type of parsing that Pinpoint might be doing under the hood for it.  The expected behavior would be that message are created and then sent through the console.  It's possible that there's a formatting issue, so can you double check that you've [configured the message correctly](https://docs.aws.amazon.com/pinpoint/latest/userguide/campaigns-message.html) or if you're using a template, you're not hitting any of the [character or description limits](https://docs.aws.amazon.com/pinpoint/latest/userguide/message-templates-creating-push.html)? Also, I believe that on Android we're looking for an `imageUrl` property under `data` (where you currently only have message/title).  

As for the multiple listeners being fired, I'm still not certain why this would be occurring.  If you only have a single listener, then something else must be making that `useEffect` hook fire more than once or possibly the component is being rendered multiple times.  Can you check to see how many times your `handlePermissions()` and `myTokenReceivedHandler()` are being called? Since these are push notifications, I'm not sure how they are being received upon app launch when you mentioned "as soon as I launched the app, I received multiple notifications".

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
