### ISSUE TITLE
AWS auth Cookie storage is not encoding the plus(+) character

### ISSUE THREAD

**Issue by arunk-uc** [aws-amplify/amplify-js#12170]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I have the below code

```
const config = awsconfig;
config.cookieStorage = { domain: "mydomain", path: "/", expires: 365, sameSite: "lax", secure: true };
```
For example, if the email id arunk@gmail.com, is getting stored as expected. ie : `CognitoIdentityServiceProvider.727vitcmg8qrnffc3lmrnb9.arunk%40gmail.com.accessToken`

But for the mail id arunk+1@gmail.com

`CognitoIdentityServiceProvider.727vitcmg8qrnffc3lmrnb9.arunk+1%40gmail.com.accessToken`
But the expected should be

`CognitoIdentityServiceProvider.727vitcmg8qrnffc3lmrnb9.arunk%2B1%40gmail.com.accessToken`
So the **+ character is not is getting encoded**. Since I am using ngx-cookie-service in my angular project, this cookie is not getting deleted.

### Expected behavior

The cookies with plus character should have been encoded to %2B

### Reproduction steps

//

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by arunk-uc** [comment]
Hi @nadetastic ,
we are using **aws-amplify": "^5.1.2"**
So it should take a stable version **5.3.11**

**Comment by nadetastic** [comment]
Hi @arunk-uc thanks for providing and confirming the above. We've identified this as a bug in the current version of the library and are working to address this. I'll label this issue as a bug and will continue to provide any updates as available.

Let me know if you have any other questions in the meantime.

**Comment by arunk-uc** [comment]
Hi @nadetastic, thanks for the confirmation. 
As of now we don't have any question.

**Comment by nadetastic** [comment]
Hi @arunk-uc wanted to follow up here - could you further clarify how you are using ngx-cookie-service here? Im looking to better understand why it's trying and failing to delete the cookie?

**Comment by nadetastic** [comment]
Hi @arunk-uc following up here after some additional investigating and discussion about this, it seems that the library does not expect the `+` to be encoded therefore it works as expected. The issue here seems to be the dependency on the `ngx-cookie-service` package. I going to go ahead and close out this issue as it has been some time since we have heard from you, but if you are able to provide additional context here we can re-open and discuss further.

Thanks!
