### ISSUE TITLE
Verify contact screen will never appear on React Native (includes fix)

### ISSUE THREAD

**Issue by tallpants** [aws-amplify/amplify-js#1221]
> Do you want to request a feature or report a bug?

Bug

> What is the current behavior?

If using `withAuthenticator` and contact verification is required in Cognito, the verify contact screen never shows up in React Native (`aws-amplify-react-native`). However, it works fine if using the regular React library on web (`aws-amplify-react`).

> If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

* Create a cognito user with contact verification required.
* Wrap a React app with `withAuthenticator` from `aws-amplify-react-native`.
* Sign in with the username and password.
* The verify contact screen does not appear on React Native. However it does show up in React.

> What is the expected behavior?

The verify contact screen needs to appear if contact verification is required in Cognito.

> Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

aws-amplify: 0.4.8
aws-amplify-react-native: 0.2.19

Platform: React Native
OS: Both (iOS and Android)

--- 

I think I've found the problem as well:

In the regular React library, the `change` function in the `RequireNewPassword` calls `checkContact`: https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify-react/src/Auth/RequireNewPassword.jsx#L65

In the same function in the React Native library, there's no call to `checkContact` at all:
https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify-react-native/src/Auth/RequireNewPassword.js#L61

The verify contact screen will also never show up on regular sign-ins because the user attributes object looks like this (from the debug log):

```
{
  "unverified": Object {
    "email": "adithya@gobranch.com",
    "phone_number": "+18885551212",
  },
  "verified": Object {},
}
```

This is fine in the regular React library, since you check if the `verified` object is empty: https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify-react/src/Auth/SignIn.jsx#L63

However, in React Native, you're only checking if the `verified` object exists -- not whether it's empty. So this check will always be true, and you'll never see the verify contact screen under any circumstances: https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify-react-native/src/Auth/SignIn.js#L72

I've opened an associated PR with this. Please review it and let me know if you can merge it, or if you'd like to fix it yourself.

**Comment by powerful23** [comment]
Thanks for your feedback and contribution. We will review it later on.

**Comment by powerful23** [comment]
Hi we just merged your pull request. Great job! We will publish a new version including this fix next week. If you have any concern please feel free to reopen the issue.
