### ISSUE TITLE
AdminQueries returning 403 forbidden when using SSR

### ISSUE THREAD

**Issue by davidjulakidze** [aws-amplify/amplify-js#12244]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

REST API

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line

  System:                    
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 27.21 GB / 47.93 GB
  Binaries:
    Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.7.5 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (117.0.2045.60)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @ampproject/toolbox-optimizer:  undefined ()
    @babel/core:  undefined ()
    @babel/runtime:  7.15.4
    @edge-runtime/cookies:  3.4.1
    @edge-runtime/ponyfill:  2.4.0
    @edge-runtime/primitives:  3.1.1
    @emotion/react: ^11.11.1 => 11.11.1
    @emotion/server: ^11.11.0 => 11.11.0
    @hapi/accept:  undefined ()
    @mantine/hooks: ^7.1.2 => 7.1.2 (7.1.0)
    @mswjs/interceptors:  undefined ()
    @napi-rs/triples:  undefined ()
    @next/font:  undefined ()
    @next/react-dev-overlay:  undefined ()
    @opentelemetry/api:  undefined ()
    @segment/ajv-human-errors:  undefined ()
    @types/crypto-js: ^4.1.2 => 4.1.2
    @types/node: 20.8.2 => 20.8.2 (20.6.3, 16.18.53)
    @types/react: 18.2.25 => 18.2.25 (18.2.21)
    @types/react-dom: 18.2.10 => 18.2.10
    @vercel/nft:  undefined ()
    @vercel/og:  undefined ()
    acorn:  undefined ()
    amphtml-validator:  undefined ()
    anser:  undefined ()
    arg:  undefined ()
    assert:  undefined ()
    async-retry:  undefined ()
    async-sema:  undefined ()
    autoprefixer: 10.4.16 => 10.4.16
    aws-amplify: ^5.3.11 => 5.3.11
    axios: ^1.5.1 => 1.5.1 (0.26.0)
    babel-packages:  undefined ()
    browserify-zlib:  undefined ()
    browserslist:  undefined ()
    buffer:  undefined ()
    bytes:  undefined ()
    ci-info:  undefined ()
    cli-select:  undefined ()
    client-only:  0.0.1
    comment-json:  undefined ()
    compression:  undefined ()
    conf:  undefined ()
    constants-browserify:  undefined ()
    content-disposition:  undefined ()
    content-type:  undefined ()
    cookie:  undefined ()
    cookies-next: ^4.0.0 => 4.0.0
    cross-spawn:  undefined ()
    crypto-browserify:  undefined ()
    css.escape:  undefined ()
    data-uri-to-buffer:  undefined ()
    dayjs: ^1.11.10 => 1.11.10
    debug:  undefined ()
    devalue:  undefined ()
    domain-browser:  undefined ()
    edge-runtime:  undefined ()
    encoding: ^0.1.13 => 0.1.13
    eslint: 8.50.0 => 8.50.0
    eslint-config-next: ^13.5.4 => 13.5.4
    events:  undefined ()
    find-cache-dir:  undefined ()
    find-up:  undefined ()
    fresh:  undefined ()
    get-orientation:  undefined ()
    glob:  undefined ()
    gzip-size:  undefined ()
    html-react-parser: ^4.2.2 => 4.2.2
    http-proxy:  undefined ()
    http-proxy-agent:  undefined ()
    https-browserify:  undefined ()
    https-proxy-agent:  undefined ()
    icss-utils:  undefined ()
    ignore-loader:  undefined ()
    image-size:  undefined ()
    is-animated:  undefined ()
    is-docker:  undefined ()
    is-wsl:  undefined ()
    jest-worker:  undefined ()
    json5:  undefined ()
    jsonwebtoken:  undefined ()
    loader-runner:  undefined ()
    loader-utils:  undefined ()
    lodash.curry:  undefined ()
    lru-cache:  undefined ()
    micromatch:  undefined ()
    mini-css-extract-plugin:  undefined ()
    nanoid:  undefined ()
    native-url:  undefined ()
    neo-async:  undefined ()
    next: ^13.5.4 => 13.5.4
    node-fetch:  undefined ()
    node-html-parser:  undefined ()
    ora:  undefined ()
    os-browserify:  undefined ()
    p-limit:  undefined ()
    path-browserify:  undefined ()
    pino: ^8.15.6 => 8.15.6
    platform:  undefined ()
    postcss: 8.4.31 => 8.4.31 (8.4.29)
    postcss-flexbugs-fixes:  undefined ()
    postcss-modules-extract-imports:  undefined ()
    postcss-modules-local-by-default:  undefined ()
    postcss-modules-scope:  undefined ()
    postcss-modules-values:  undefined ()
    postcss-preset-env:  undefined ()
    postcss-safe-parser:  undefined ()
    postcss-scss:  undefined ()
    postcss-value-parser:  undefined ()
    process:  undefined ()
    punycode:  undefined ()
    querystring-es3:  undefined ()
    raw-body:  undefined ()
    react: ^18.2.0 => 18.2.0
    react-builtin:  undefined ()
    react-dom: ^18.2.0 => 18.2.0
    react-dom-builtin:  undefined ()
    react-dom-experimental-builtin:  undefined ()
    react-experimental-builtin:  undefined ()
    react-is:  18.2.0
    react-refresh:  0.12.0
    react-server-dom-webpack-builtin:  undefined ()
    react-server-dom-webpack-experimental-builtin:  undefined ()
    regenerator-runtime:  0.13.4
    sass-loader:  undefined ()
    scheduler-builtin:  undefined ()
    scheduler-experimental-builtin:  undefined ()
    schema-utils:  undefined ()
    semver:  undefined ()
    send:  undefined ()
    server-only:  0.0.1
    setimmediate:  undefined ()
    shell-quote:  undefined ()
    source-map:  undefined ()
    stacktrace-parser:  undefined ()
    stream-browserify:  undefined ()
    stream-http:  undefined ()
    string-hash:  undefined ()
    string_decoder:  undefined ()
    strip-ansi:  undefined ()
    superstruct:  undefined ()
    tailwindcss: 3.3.3 => 3.3.3
    tar:  undefined ()
    terser:  undefined ()
    text-table:  undefined ()
    timers-browserify:  undefined ()
    transport:  0.0.1
    ts-loader: ^9.4.4 => 9.4.4
    tty-browserify:  undefined ()
    typescript: 5.2.2 => 5.2.2
    ua-parser-js:  undefined ()
    undici:  undefined ()
    unistore:  undefined ()
    util:  undefined ()
    vm-browserify:  undefined ()
    watchpack:  undefined ()
    web-vitals:  undefined ()
    webpack: 5.88.2 => 5.88.2 ()
    webpack-sources:  undefined ()
    ws:  undefined ()
  npmGlobalPackages:
    @aws-amplify/cli: 12.2.1
    @tsmodule/tsmodule: 44.7.0
    pnpm: 8.7.5
    yarn: 1.22.19
```
</details>

### Describe the bug

the following function is a server action 

```js
"use server";

Amplify.configure({
  ...awsconfig,
  ssr: true,
});

export async function listUsers(): Promise<CognitoUser[] | undefined> {
  let apiName = "AdminQueries";
  let path = "/listUsers";
  try {
    const req = {
      headers: {
        cookie: headers().get("cookie"),
      },
    };
    const SSR = withSSRContext({req});
    let myInit = {
      headers: {
        "Content-Type": "application/json",
        Authorization: `${(await SSR.Auth.currentSession())
            .getAccessToken()
            .getJwtToken()}`,
      },
    };
    const result = await SSR.API.get(apiName, path, myInit);
    return result;
  } catch (error) {
    logger.info(error);
  }
  return undefined;
}
```

returns 403 Forbidden error.

the same function in a client component:

```js
  useEffect(() => {
    const fetchUsers = async () => {
      let apiName = "AdminQueries";
      let path = "/listUsers";
      try {
        let myInit = {
          headers: {
            "Content-Type": "application/json",
            Authorization: `${(await Auth.currentSession())
                .getAccessToken()
                .getJwtToken()}`,
          },
        };
        const result = await API.get(apiName, path, myInit);
        return result;
      } catch (error) {
        console.log(error)
      }
    };
    fetchUsers();
  }, [])

```
succeeds and returns users. 

Confirmed:
1. user is part of the group that has access to adminQueries
2. user is authenticated
3. JWT token retrieved in server action is the same as in the client component when making the api request
4. Confirmed the same request and JWT token work in PostMan
5. the listUsers accepts a get request

### Expected behavior

for the SSR version of the admin query function to succeed

### Reproduction steps

1. Make SSR api call to adminQueries

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_mobile_analytics_app_id": "",
    "aws_mobile_analytics_app_region": "us-east-1",
    "Analytics": {
        "AWSPinpoint": {
            "appId": "",
            "region": "us-east-1"
        }
    },
    "aws_appsync_graphqlEndpoint": "",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_",
    "aws_user_pools_web_client_id": "",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 12,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "",
    "aws_user_files_s3_bucket_region": "us-east-1"
};

export default awsmobile;

**Comment by nadetastic** [comment]
Hi @davidjulakidze thank you for opening this issue. Im currently taking a look and working to reproduce this. In the meantime, can you confirm that you are getting a valid session on the server by logging the response from `await SSR.Auth.currentSession()`?

**Comment by davidjulakidze** [comment]
Hi @nadetastic I've logged the JWT token returned by the ```
(await SSR.Auth.currentSession())
                .getAccessToken()
                .getJwtToken()
```

and copy pasted it in a postman request which succeed and returns users

**Comment by davidjulakidze** [comment]
@nadetastic any updates on this? were you able to reproduce?

**Comment by chrisbonifacio** [comment]
Hi @davidjulakidze can you compare the headers between the server action request and a client/postman request? Are there any notable differences?

**Comment by davidjulakidze** [comment]
Attempting to reproduce again, I will post results soon

**Comment by nadetastic** [comment]
Hi @davidjulakidze following up here - with the release of Amplify v6, we have improved support for SSR application and you can read more about this [here](https://docs.amplify.aws/react/build-a-backend/server-side-rendering/) and learn more about NextJS specific configuration [here](https://docs.amplify.aws/react/build-a-backend/server-side-rendering/nextjs/).

Additionally, please note that the way the API are used has been changed, and you can view the migration guide here - https://docs.amplify.aws/react/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/

Could you let me know if this is still an issue for you?

**Comment by davidjulakidze** [comment]
this has been resolved, thanks!

**Comment by GreyWuTMGM** [comment]
May I ask how did you solve this problem？ It that something about the ip white list？
