### ISSUE TITLE
SAML 2.0 React Native Integeration

### ISSUE THREAD

**Issue by eshwarsv** [aws-amplify/amplify-js#12247]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

Hello all,

I have successfully integrated Okta IDP with Amplify react native application. During Logout, after following this documentation.
[+]  https://github.com/aws-amplify/amplify-android/issues/1287#issuecomment-1132266263

The current issue at hand is when trying to perform logout, its opening the URL in a separate external Chrome browser in Android.

I have also attached the screenshots referring to this issue.

### Expected behavior

Expected behaviour:

Logout should log the user out without firing the external web browser.
![same_issue_chromebrowser_isstill_launched](https://github.com/aws-amplify/amplify-js/assets/102645548/ecda470c-6b41-413b-950a-753c5941f9f4)

### Reproduction steps

-

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_XXXXX",
    "aws_user_pools_web_client_id": "XXXXXXXXX",
    "oauth": {
        "domain": "reactnativesaml.auth.us-west-2.amazoncognito.com",
        "scope": [
            "email",
            "openid",
            "phone"
        ],
        "redirectSignIn": "myapp://",  // Your redirect Sign in
        "redirectSignOut": "myapp://--/https://google.com",   // Your redirect Sign out
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};

export default awsmobile;

### Manual configuration

-

### Additional configuration

-

### Mobile Device

Pixel 5 API 33

### Mobile Operating System

Android 

### Mobile Browser

Expo and Google Chrome

### Mobile Browser Version

-

### Additional information and screenshots

-

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
