### ISSUE TITLE
Display cognito failures in aws-amplify-vue in browser instead of browser console

### ISSUE THREAD

**Issue by pydanny** [aws-amplify/amplify-js#1225]
> Do you want to request a feature or report a bug?

Feature

> What is the current behavior?

During account signup, in order to discover any issues with your phone number, password, or email, problems are not displayed in the browser. Instead, they only display in the console.

> What is the expected behavior?

Cognito errors should be displayed in the browser.

Tools like [vee-validate](https://baianat.github.io/vee-validate/) make implementing this kind of thing easy in VueJS.

> Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

Amplify 0.4.8 on Chrome/Firefox/Safari on OSX. Has never worked as far as I can tell.

**Comment by haverchuck** [comment]
This should be fixed now with the use of our aws-amplify-vue library package.
