### ISSUE TITLE
Caught exception when recording events

### ISSUE THREAD

**Issue by arthurtyukayev** [aws-amplify/amplify-js#12250]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Analytics

### Amplify Categories

analytics

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

When configuring the project and running the application, everything seems to work fine, however when recording events the following exception is logged into the console:

```
[ERROR] 11:41.311 AWSPinpointProvider - updateEndpoint failed [TypeError: this._url.endsWith is not a function. (In 'this._url.endsWith('/')', 'this._url.endsWith' is undefined)]
```

I am not sure if events still being captured, I do not see any network traffic aside from the initial authentication request. 

This was tested in my existing application as well as a newly generated React Native project, it happens in both.

### Expected behavior

It shouldn't log any errors and network events should go through when `immediate: true`.

### Reproduction steps

1. Install and configure the plugin with `Auth` and `Analytics`
2. Run the React Native application, and record any event.
3. There should be a console error.

### Code Snippet

```javascript
import { Amplify } from 'aws-amplify';
import { awsConfig } from '@utils/analytics';

Amplify.configure(awsConfig);
...

import { Analytics } from 'aws-amplify';


await Analytics.record({
  name: event,
  attributes: attributesObjct,
});


```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Manual configuration

```javascript
export const awsConfig = {
  Auth: {
    identityPoolId: AWS_COGNITO_ID,
    region: AWS_REGION,
  },
  Analytics: {
    disabled: false,
    autoSessionRecord: true,
    AWSPinpoint: {
      appId: AWS_ANALYTICS_ID,
      region: AWS_REGION,
      bufferSize: 1000,
      flushInterval: 5000,
      flushSize: 100,
      resendLimit: 5,
      endpoint: {
        demographic: {
          appVersion: DeviceInfo.getVersion(),
          model: DeviceInfo.getDeviceId(),
          platform: DeviceInfo.getSystemName(),
          platformVersion: DeviceInfo.getSystemVersion(),
        },
      },
    },
  },
}
```

**Comment by cwomack** [comment]
Hello, @arthurtyukayev 👋. Can you clarify what version on Amplify you are on? What type of authentication flow are you currently using?  

One thing to note on the use of the `immediate: true` flag for recording events is that while Amplify will send them to Pinpoint immediately, they won't potentially show up on the Pinpoint console for 30+ minutes.

**Comment by arthurtyukayev** [comment]
I'm currently using the latest version for both `amazon-cognito-identity-js` and `aws-amplify`. It seems to appear on the latest version.

As for the authentication flow, we're using Cognito Identity Pools unauthenticated.

**Comment by dinesh-brilworks** [comment]
Getting the same error while calling Analytics.updateEndpoint and Analytics.record, 

Using following dependancy version:
```
    "aws-amplify": "~5.3.0",
    "aws-amplify-react-native": "6.0.1",
```

**Comment by dinesh-brilworks** [comment]
@arthurtyukayev did you find a fix for the issue?

**Comment by arthurtyukayev** [comment]
I have no fix for this despite a couple of hours of debugging. 

To be it seems as though the library doesn't really know that it's running into a React Native JS runtime. It's calling functions like `URL.hostname` and `URL.host` on the URL class, which doesn't exist in a RN JS: https://github.com/facebook/react-native/blob/main/packages/react-native/Libraries/Blob/URL.js#L177

**Comment by cwomack** [comment]
@arthurtyukayev and @dinesh-brilworks, it looks like you may both missing the `url` polyfill.  Can you see if installing [this package](https://github.com/charpeni/react-native-url-polyfill) your v5 app resolves the issue? 

In v6, this is a dependency of our React Native module and should no longer be an issue in the latest major version.

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!

**Comment by julian-dotcom** [comment]
@cwomack, installing the recommended polyfill fixed the problem for me. 

Thanks!
