### ISSUE TITLE
crypto-browserify should be updated in amazon-cognito-identity-js

### ISSUE THREAD

**Issue by capaj** [aws-amplify/amplify-js#1227]
the current version is `1.0.9` which has been published 5 years ago
![image](https://user-images.githubusercontent.com/1305378/42662818-4cd6e102-8633-11e8-901b-7e7f5680270b.png)

also it causes build issues when in strict mode as seen here #888 and #891.

**Comment by jordanranz** [comment]
It seems we experienced issues upgrading to the newest version: #857 

I have added a task to our backlog to spike on this.
