### ISSUE TITLE
Config API region dynamically per Route 53 return endpoint

### ISSUE THREAD

**Issue by jackywxd** [aws-amplify/amplify-js#1230]
Hi there, 

Is there anyway I can config API region dynamically base on the domain name returned by Route 53? In active-active configuration, Route 53 is configured to return different regional API endpoints with the same custom domain name per DNS latency. So even though the URL is the same, but the region is different depends on where the users access the backend. If the region is not correctly configured to the same region of the endpoint, amplify API call returns 403 error. I believe the reason is the http is not signed correctly in this case.

It will be great that amplify can handle this situation, automatically configure the region based on the Route 53 resolved result before calling the API endpoint.

Thanks!
Jacky

**Comment by mlabieniec** [comment]
@jackywxd if i understand correctly, you have geo or weighted routing setup in route53? Can you elaborate a bit more on your setup in Route53? Is your setup a static S3 / CloudFront app and the top-level dns serves a different one based on weight / geo?

**Comment by elorzafe** [comment]
@jackywxd Did you find a solution for this?

**Comment by jackywxd** [comment]
@mlabieniec That's correct. We have Geolocation Routing setting with Route53. And it is API only, so no need static S3 or CloudFront. We deploy our API with serverless framework to three different regions, and endpointType is set to "regional". So we have three different target domain names returned from API gateway from each region. Custom Domain Name is setup in API gateway to map our own Domain Name. Finally we setup three Health check policies and three CNAME records in Route 53 for each region.

With this setup, our mobile App in different region will use different endpoint based on our customer's location. Also it will automatically route to other regions in case of current region experienced outage.

**Comment by jackywxd** [comment]
@elorzafe Yes, we did have a workaround for our iOS App using AWS SDK.

Our Route53 is configured to do health check. One open API was setup for this purpose, all it does is to return the current region name. And Route 53 health check will match the returned region string.

So we were able to leverage this API in our mobile App to determine the backend region our application try to access, and configure AWS SDK dynamically according the region returned by the API.

In theory in a React webapp, I can call the same API to get the region name in componentDidMount, then call Amplify.configure. But I am not sure whether Amplify-js supports it. 

So the question is, can we call Amplify.configure in componentDidMount?

**Comment by elorzafe** [comment]
@jackywxd You can call configure on `componentDidMount` but what I would is adding a prefix/suffix on your endpoint names, something like this.

```javascript
Amplify.configure( {
  API: {
    endpoints: [ 
      { name: 'api1-<region1>', endpoint: 'https://.......' }, 
      { name: 'api1-<region2>', endpoint: 'https://.......' }, 
      { name: 'api2-<region1>', endpoint: 'https://.......' }, 
      { name: 'api2-<region2>', endpoint: 'https://.......' }, 
    ]
  }
});

var region; // the current region

// to use your region
API.get('api1-' + region, 'path')
```


I hope this helps

**Comment by jackywxd** [comment]
@elorzafe I see. So endpoints accepts an array with different region endpoints. That opens my eye! Thanks a lot for your help!

**Comment by jackywxd** [comment]
I just double checked the Amplify document, now endpoints support regional endpoint by passing in service and region. Not sure if it can handle switching endpoints dynamically based on current region if passing multiple regions. If it does, it will perfectly solve this issue.


```
API: {
    endpoints: [
        {
            name: "MyCustomLambda",
            endpoint: "https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/yourFuncName/invocations",
            service: "lambda",
            region: "us-east-1"
        }
    ]
}
```

**Comment by haverchuck** [comment]
Closing this issue.  Please open new issue if needed.
