### ISSUE TITLE
Storage.put when response should return eTag instead of only key

### ISSUE THREAD

**Issue by natuan62** [aws-amplify/amplify-js#12321]
### Is this related to a new or existing framework?

Vue

### Is this related to a new or existing API?

Storage

### Is this related to another service?

S3

### Describe the feature you'd like to request

**Storage.put** should return **eTag**.

And now we must use Storage.get to get eTag information like that

```
const { key } = await Storage.put(filePath, itemFile.file, config);

const { eTag } = await Storage.getProperties(key, {
     level: 'private',
 }) ;
```

### Describe the solution you'd like

Response of Storage.put is key and eTag like that

`const { key, eTag } = await Storage.put(filePath, itemFile, config);`

### Describe alternatives you've considered

Response of Storage.put is key and eTag like that

`const { key, eTag } = await Storage.put(filePath, itemFile, config);`

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by natuan62** [comment]
Or anyway how we can get `eTag` from headers ?
![Screenshot 2023-10-17 at 16 27 13](https://github.com/aws-amplify/amplify-js/assets/10808157/59e4e217-605e-4cb8-964a-4c57a629879f)

**Comment by cwomack** [comment]
Hello, @natuan62 👋.  I'll mark this as a feature request at this time, as there's no "out of the box" way for the `Storage.put()` to get the` eTag`. 

We'll also see if there's potentially a workaround that can be done to get the `eTag`, but in the mean time can you describe a little more about the use case and what you're needing the `eTag` for?  If you're looking for more fine-grained access control or creating "folders" (really prefixes) in S3, then there may be other ways to accomplish that.

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
