### ISSUE TITLE
Authenticator UI message when setting password

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-js#1233]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
There's no message telling the user to create a new password.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.
Enable user-signin feature using the awsmobile cli.
Push changes.
Manually add a user in Cognito.
Use that created user to sign in into angular application.
The amplify-authenticator UI does not indicate to the user that they have to set a new password. It just has a password field.

What is the expected behavior?
The amplify-authenticator UI should have text/label that prompts the user that they have to set a new password.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
"aws-amplify": "^0.4.8",
"aws-amplify-angular": "^0.1.6",

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.
This is just a text/label change, don't think debugging is needed.

**Comment by jarrettj** [comment]
Just to add on, my workaround for now is to hide the element via css. 

```
.amplify-greeting { display: none; }
```

**Comment by jordanranz** [comment]
Have you tried using the latest version of aws-amplify and aws-amplify-angular?

There should be a require-new-password component in there used for this.

**Comment by jarrettj** [comment]
Hi,

Good day.

I'll close this issue, and relook when I use this framework again.

Regards.
