### ISSUE TITLE
Too many password attempts exceeded needs its own error code from Cognito

### ISSUE THREAD

**Issue by tobiastornros** [aws-amplify/amplify-js#1234]
Password attempts exceeded needs its own error code from Cognito.

Do you want to request a feature or report a bug?
Feature

What is the current behavior?

When a user has exceeded their password attempts or entering wrong password the error code is: 'NotAuthorizedException'. 

Only the message property is different: 
Wrong password =  'Incorrect username or password'
Too many attempts = 'Password attempts exceeded'

How to reproduce: 
Try to authenticate user 5-10 times with incorrect password. 

What is the expected behavior?
Maybe provide new error code for this case. PasswordAttemptsExceeded to make it easier to handle this in the client.

**Comment by jordanranz** [comment]
Hello, thanks for submitting this issue.

Seems this has been brought up within the Cognito team last year:
https://github.com/amazon-archives/amazon-cognito-identity-js/issues/479

**Comment by chefren** [comment]
Could this be explained in the docs?
https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html

Some RFIs require more detail to ensure requirements are met

**Comment by edotassi** [comment]
is there any update about this issue?

**Comment by jnapprogs** [comment]
Just going to shout in the echo chamber:

Is there any update on this issue yet?  Did the team forget about this issue or forget to post here???

**Comment by undefobj** [comment]
Hello - We've passed this information to the Cognito team internally and they're tracking it. I'll go ahead and close this issue but if you'd like to raise it on another channel you could also open an AWS support case.

**Comment by sysFactory12345** [comment]
Hola chicos intento entrar para bajar el repositorio de codigo por linea de comandos y me dice que la contraseña es icorrecta, sin embargo entro al repositorio de git hub con la misma que digito en la linea de comandos y me permite la entrada al sitio. alguien sabe que sucede?

**Comment by chefren** [comment]
> Hola chicos intento entrar para bajar el repositorio de codigo por linea de comandos y me dice que la contraseña es icorrecta, sin embargo entro al repositorio de git hub con la misma que digito en la linea de comandos y me permite la entrada al sitio. alguien sabe que sucede?

https://github.com/git-guides/git-clone

**Comment by garrettmaring** [comment]
I think most of us agree that the Amazon UX is ideal ✅  Passwords when registering should *always* require confirmation input.

![Screen Shot 2020-12-10 at 2 46 02 PM](https://user-images.githubusercontent.com/8270120/101839045-886ad280-3af6-11eb-9627-f339382f0b28.png)

**Comment by tylerjames** [comment]
Greetings from 2021!

If anyone was wondering this problem still exists

**Comment by anil1712** [comment]
Yes, I am still getting the same error. 

Has someone got any solution ?

**Comment by Abdelmottaleb** [comment]
Hi everyone,
do you have any idea if the Cognito team addresses this? I m  still getting the same exception for both cases:

`NotAuthorizedException:` Incorrect username or password.
`NotAuthorizedException:` Password attempts exceeded

**Comment by marck0zz** [comment]
Sorry to be intrusive but I'm having exactly the same situation in the SDK for .NET so, maybe is not only a issue with a specific SDK. I'm just looking for a solution or workaround haha.

**Comment by tylerjames** [comment]
Yeah the errors are returned by Cognito and just forwarded by the SDK so until Cognito provides better errors there's not much the SDK teams can do about it.
