### ISSUE TITLE
Can't find variable: setTimeout  in react-native

### ISSUE THREAD

**Issue by shinnapatthesix** [aws-amplify/amplify-js#1235]
I got this error when run react-native in release mode

![screen shot 2561-07-13 at 20 48 42](https://user-images.githubusercontent.com/40481591/42695002-47d5d996-86de-11e8-919d-ba521e9e42f5.png)

**Comment by jordanranz** [comment]
Hello, thanks for submitting an issue. Could you please provide a bit more detail.

- Are you using a starter project or your own with Amplify.
- Which version of aws-amplify are you using?
- Which version of react-native are you using?
- Which version of Node are you using (node -v)?

**Comment by ricsam** [comment]
I had the same issue, tried to reproduce it but it was really hard. I think it might have something to do with shared dependencies of amplify and appsync or it is some kind of race issue when installing the dependencies.

The solution for me was to remove the appsync dependencies from package.json, delete yarn.lock 😞, delete node_modules and reinstalling (yarn install). Thereafter I re-added the appsync dependencies and ran yarn install.

I was not able to consistently reproduce the error in a test repo so I think it might be some race issue when yarn installing 🤷‍♂️  or the order of calling yarn add ...

My yarn version is 1.3.2
react native version 0.56.0
amplify version 1.0.0
appsync version 1.2.1

**Comment by powerful23** [comment]
Closing this issue. Feel free to reopen if you still have this issue.
