### ISSUE TITLE
User not being signed in After Federated Sign-In with Google (in production, working locally)

### ISSUE THREAD

**Issue by vesapupovci** [aws-amplify/amplify-js#12350]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React(NextJS)

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I am encountering an issue with federated sign in with Google, where the user is successfully created in Cognito, but they're not being signed in.
The problem occurs when my application is deployed; it works correctly in my local development environment.
After the federated sign-in with Google, the user is created in Cognito, but the user is not effectively logged in or granted a user session.
I've reviewed my AWS Cognito User Pool and identity pool settings, Google config the OAuth consent screen settings, and everything seems correctly configured.

I am seeing this error in the browser console:
`Uncaught (in promise) DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'https://<url>/login/confirm' cannot be created in a document with origin 'https://<url>' and URL 'https://<url>/login/confirm/?code=3ab8fddf-30ae-4606-9e0d-30e0c5d71945&state=o39J7jOeYjfS2m5TLFOqrFWdhCj9FOYH'.`
I've replaced the actual url with <url>

I'm using version 5.3.9 of `aws-amplify`

### Expected behavior

After the user is redirected to my application, I'm expecting them to be signed in.

### Reproduction steps

1. Click on Sign Up with Google
2. Select the email address that you want to sign up with
3. The user gets redirected to the application (using the redirect url that I've specified in amplify config)
4. The method for getting the authenticated user returns `undefined`

### Code Snippet

```javascript
import Amplify from 'aws-amplify';
// Amplify config
function initAmplify(options: Options): any {
  Amplify.configure({
    Auth: {
      region: options.cognitoRegion,
      userPoolId: options.cognitoUserPoolId,
      userPoolWebClientId: options.cognitoUserPoolWebClientId, // Generate a client app with no secret
        : {}),
    },
    oauth: {
      domain: process.env.NEXT_PUBLIC_COGNITO_URL,
      scope: ['email', 'profile', 'openid'],
      redirectSignIn: `${process.env.NEXT_PUBLIC_MARKETING_WEBSITE_URL}/login/confirm`,
      redirectSignOut: `${process.env.NEXT_PUBLIC_MARKETING_WEBSITE_URL}/login/logout`, 
      responseType: 'code',
      client_id: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID,
    },
  });
}

// sign up with google
import Amplify from 'aws-amplify'
const { Auth } = Amplify
async function signUpWithGoogle(): Promise<any> {
  try {
    const user = await Auth.federatedSignIn({ provider: 'Google' })
    return user
  } catch (e) {
    console.log(e)
  }
}

// After clicking on `signUpWithGoogle`, users are redirected to Google, where they can select their email address and log in.
// They are then successfully redirected back to the app (using the redirect url that I've specified in the amplify config)
// We then call this method to get the authenticated user, but it returns `undefined`:
import { Auth } from 'aws-amplify';
async function getCurrentlyAuthenticatedUser(): Promise<any> {
  try {
    return await Auth.currentAuthenticatedUser();
  } catch (e) {
    // handle error
  }
}
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello, @vesapupovci 👋 and thank you for opening this issue.  It looks like the issues you're experiencing could be related to the redirect URI's specified for the federated sign in.  Are you able to share your `aws-exports.js` if you're using the CLI  created Auth resources (feel free to redact anything confidential) or what your `Amplify.configure()` code looks like if you've done a scoped config? Thanks!

**Comment by vesapupovci** [comment]
> Are you able to share your `aws-exports.js` if you're using the CLI created Auth resources (feel free to redact anything confidential) or what your `Amplify.configure()` code looks like if you've done a scoped config? Thanks!

hi @cwomack I've included my `Amplify.configure()` code in my original message. To clarify, the value of `redirectSignIn` is `https://www.qa.new.<domain>.com`

**Comment by vesapupovci** [comment]
@cwomack I'm printing out Hub events and I'm seeing this:

Event `signIn_failure`, stack `Error: Username and Pool information are required.\n ` and message `The OAuth response flow failed`.

**Comment by vesapupovci** [comment]
Fixed, according to this [tutorial](https://creativedesignsguru.com/next-js-aws-amplify-cognito-oauth/) the sign in uri needs a trailing slash at the end. I also had to enable the`trailingSlash` option in `next.config.js`
