### ISSUE TITLE
Integrating aws amplify in React Native [iOs] doesn't work

### ISSUE THREAD

**Issue by takeerdevs** [aws-amplify/amplify-js#12408]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
  System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 1.37 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.18.2/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    Watchman: 2023.10.02.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 117.0.5938.149
    Edge: 111.0.1661.62
    Safari: 17.0
  npmPackages:
    @babel/core: ^7.20.0 => 7.23.2 
    @babel/preset-env: ^7.20.0 => 7.23.2 
    @babel/runtime: ^7.20.0 => 7.23.2 
    @react-native-async-storage/async-storage: ^1.19.3 => 1.19.3 
    @react-native-community/netinfo: ^9.4.1 => 9.4.1 
    @react-native/eslint-config: ^0.72.2 => 0.72.2 
    @react-native/metro-config: ^0.72.11 => 0.72.11 
    @tsconfig/react-native: ^3.0.0 => 3.0.2 
    @types/react: ^18.0.24 => 18.2.31 
    @types/react-test-renderer: ^18.0.0 => 18.0.5 
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: ^6.3.6 => 6.3.6 
    amazon-cognito-identity-js/internals:  undefined ()
    aws-amplify: ^5.3.11 => 5.3.11 
    babel-jest: ^29.2.1 => 29.7.0 
    eslint: ^8.19.0 => 8.52.0 
    jest: ^29.2.1 => 29.7.0 
    metro-react-native-babel-preset: 0.76.8 => 0.76.8 
    prettier: ^2.4.1 => 2.8.8 
    react: 18.2.0 => 18.2.0 
    react-native: 0.72.6 => 0.72.6 
    react-test-renderer: 18.2.0 => 18.2.0 
    typescript: 4.8.4 => 4.8.4 
  npmGlobalPackages:
    corepack: 0.19.0
    npm: 9.8.1
    patch-package: 8.0.0
    yarn: 1.22.19

```

</details>

### Describe the bug

I failed to integrate amplify to our existing project due to migration to `@smithy` packages, complained some plugins are not available like `http`,`crypto`, `path`, `os` etc.. 
<img width="388" alt="Screenshot 2023-10-24 at 17 47 23" src="https://github.com/aws-amplify/amplify-js/assets/49426357/8d506f60-d6b9-4db7-9a1e-5269e58370c6">

I managed to solve some of these errors by going to specific `@smithy` package like  `@smithy/util-stream` then `package.json` then change `"main": "./dist-cjs/index.js",` to `"main": "./dist-es/index.js",` but finally kept on throwing errors not finding `crypto` then `path` then `os` etc.

even after installing those packages kept throwing errors then i decided to initialise a new project by following easy to do amplify integration guide here [Amplify integration guide for React Native](https://docs.amplify.aws/start/getting-started/setup/q/integration/react-native/) but doesn't work.
<img width="1411" alt="Screenshot 2023-10-24 at 17 33 24" src="https://github.com/aws-amplify/amplify-js/assets/49426357/84239a09-831d-4df1-89bb-263109cd090a">

So briefly, the guide to integrate amplify in react-native project throw errors when running a project.

### Expected behavior

Amplify plugins added shouldn't throw errors. Errors kept popping in react-native after migration to `@smithy`

### Reproduction steps

1. Initialize new react-native project `npx react-native init amplified_todo && cd amplified_todo`
2. `npm install aws-amplify amazon-cognito-identity-js @react-native-community/netinfo @react-native-async-storage/async-storage`
3. `npx pod-install`
4. `npm start`
5.  Initialize a new backed as shown in amplify docs here [initialize-a-new-backend](https://docs.amplify.aws/start/getting-started/setup/q/integration/react-native/#initialize-a-new-backend)
6.  in `App.js` file in root project directory i.e in `amplified_todo` folder, add contents as specified in Code snippet below
7.  Open `amplified_todo.xcworkspace` via Xcode in `cmplified_todo` then `ios` and build the project then run

### Code Snippet

```javascript
//App.js file

import React, { Component } from 'react';
import { Text, View } from 'react-native';

import { Amplify } from 'aws-amplify';
import awsExports from './aws-exports';
Amplify.configure(awsExports);

export default class App extends Component {
  render(){
    return (
      <View style={{ flex:1, alignItems:'center', justifyContent:'center' }}>
        <Text>Hello World!</Text>
      </View>
    )
  }
}

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello, @takeerdevs 👋 and thank you for opening this issue.  Can you see if deleting your `node_modules` folder along with your `package-lock.json` file, then reinstalling your dependencies with `npm install` resolves the issue? If not, would you mind sharing your `package.json` after doing this? Thanks!

**Comment by takeerdevs** [comment]
Now it works, Thanks!.
