### ISSUE TITLE
Release 2.0.14 - Uncaught TypeError: Cannot set property 'createCredentials' of undefined 

### ISSUE THREAD

**Issue by JoseWebby** [aws-amplify/amplify-js#1243]
Report a bug. 

In my ember project I am using `amazon-cognito-identity-js` and when I run my app, I am getting below error.

<img width="875" alt="screen shot 2018-07-16 at 1 26 19 am" src="https://user-images.githubusercontent.com/10756710/42739986-8c64941a-8898-11e8-8647-5218f211ea7c.png">

Version: `amazon-cognito-identity-js - 2.0.14`
Browser: Chrome/MacOS

I could see similar issue here (https://github.com/aws-amplify/amplify-js/issues/546) But it looks quite old and may be fixed. Because it was all working fine 3 days back with `amazon-cognito-identity-js - 2.0.13`

Any help/suggestion will be much appreciable. 

Thanks in advance!

**Comment by JoseWebby** [comment]
This release update is breaking the entire app and I am not sure how is this just a patch release. Can somebody help me in identifying what I am missing please.

**Comment by powerful23** [comment]
@JoseWebby can you check the version of `cryptro-browerify` under the `node_modules`? It should be `1.0.9`

**Comment by JoseWebby** [comment]
Hi @powerful23, Thanks for your response. Yes, it is `1.0.9`. 
I did `npm list crypto-browserify` and got 
![npm_list](https://user-images.githubusercontent.com/10756710/42804682-9c24d6c6-89a1-11e8-9f9c-35d3e0f831dd.png)

**Comment by JoseWebby** [comment]
Tried with old and latest node/npm version as well, but same issue. 
v6.11.2 / 3.10.10 
v10.4.0 / 6.1.0

**Comment by paulcwatts** [comment]
This breaks if you include the file `dist/amazon-cognito-identity.min.js`. If you include `dist/amazon-cognito-identity.js`, it works.

**Comment by powerful23** [comment]
Duplicated to #546 so closing it.

@simodroussi We have updated the library to use `crypto-js` instead of `crypto-browserify`. Do you still have this issue?
