### ISSUE TITLE
manyToMany relationship has incorrect auth

### ISSUE THREAD

**Issue by jackshi0912** [aws-amplify/amplify-js#12448]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

GraphQL API, DataStore

### Environment information

<details>

```
# Put output below this line
System:
    OS: Linux 5.15 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 54.20 GB / 62.70 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 19.8.1 - /usr/local/bin/node
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 117.0.5938.132
  npmGlobalPackages:
    @aws-amplify/cli: 12.0.0
    @sanity/cli: 3.8.3
    npm: 9.6.4

```

</details>

### Describe the bug

I have the following setup with a simple many-to-many relationship between Team and Project

```
type Team @model @auth(rules: [{allow: groups, groups: ["admin"]}]) {
  id: ID!
  projects: [Project] @manyToMany(relationship: "TeamProject")
}


type Project @model @auth(rules: [{allow: groups, groups: ["admin"]}]) {
  id: ID!
  team: [Team] @manyToMany(relationship: "TeamProject")
}
```

When I try to use `DataStore.save` to upload some data, the upload succeeded for my array of `Project` and array of  `Team`. I was unable to upload my array of TeamProject with error type `Unauthorized`.

### Expected behavior

Since both models allow `admin` to create new records, `TeamProject` should also allow `admin` to create the connections.

### Reproduction steps

Create a schema
```
type Team @model @auth(rules: [{allow: groups, groups: ["admin"]}]) {
  id: ID!
  projects: [Project] @manyToMany(relationship: "TeamProject")
}


type Project @model @auth(rules: [{allow: groups, groups: ["admin"]}]) {
  id: ID!
  team: [Team] @manyToMany(relationship: "TeamProject")
}
```

Observe the fact that you can't use `DataStore.save` to upload `TeamProject`.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by jackshi0912** [comment]
Update, the config is actually:
```
type Team @model @auth(rules: [
 {allow: public, operations: [read]},
 {allow: groups, groups: ["admin"]}]) {
  id: ID!
  projects: [Project] @manyToMany(relationship: "TeamProject")
}


type Project @model @auth(rules: [
 {allow: public, operations: [read]},
 {allow: groups, groups: ["admin"]}]) {
  id: ID!
  team: [Team] @manyToMany(relationship: "TeamProject")
}
```

**Comment by cwomack** [comment]
Hello, @jackshi0912 👋.  Can you clarify what version of `aws-amplify` you're currently on?

**Comment by jackshi0912** [comment]
Hello!
According to `amplify version`: 12.7.1

**Comment by chrisbonifacio** [comment]
Hi @jackshi0912 :wave: thanks for raising this issue. 

A few things:

1. That seems to be the version of the Amplify CLI. We're curious what version of the library you're using.

You can find that in the package.json file. Can you share the contents here?

2. Also, please share the contents of your aws-exports.js file

3. Please share a code snippet of how you're calling Amplify.configure or DataStore.configure

4. Lastly, please check the network activity for the graphql request that is sent and unauthorized? I'm curious to see if DataStore sent the request with an `x-api-key` or an `authorization` header.

**Comment by jackshi0912** [comment]
Oh right, amplify package is set to `^5.3.3`

aws-exports.js
```

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_appsync_graphqlEndpoint": "https://jpwkp3ahazcltftypmtlqah7v4.appsync-api.eu-north-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-north-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-idx6dytd3vbhdaa4hxmgme4sfe",
    "aws_cognito_identity_pool_id": "eu-north-1:4b5e2484-62ed-4eb4-83bf-2738d9f5327d",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_q0xFG5yqR",
    "aws_user_pools_web_client_id": "68nr2va3jdei5jvfirar7kkj4c",
    "oauth": {
        "domain": "renaissance7e3be97a-7e3be97a-dev.auth.eu-north-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "renaissance-storage-482f822d04929-dev",
    "aws_user_files_s3_bucket_region": "eu-north-1"
};


export default awsmobile;
```


`Amplify.configure`:
```
Amplify.configure({
  ...awsExports,
  DataStore: {
    authModeStrategyType: AuthModeStrategyType.MULTI_AUTH
  },
  ssr: true
});
```

I'm signed in to Google while the request is sent. Let me look into the graphql request header.

Thanks!

**Comment by jackshi0912** [comment]
Request header from chrome `Developper Tools` -> `Network`:
```
Request URL:
https://jpwkp3ahazcltftypmtlqah7v4.appsync-api.eu-north-1.amazonaws.com/graphql
Request Method:
POST
Status Code:
200 OK
Remote Address:
18.244.179.70:443
Referrer Policy:
strict-origin-when-cross-origin
Access-Control-Allow-Origin:
*
Access-Control-Expose-Headers:
x-amzn-RequestId,x-amzn-ErrorType,x-amz-user-agent,x-amzn-ErrorMessage,Date,x-amz-schema-version
Content-Length:
253
Content-Type:
application/json;charset=UTF-8
Date:
Fri, 27 Oct 2023 15:50:18 GMT
Via:
1.1 85c7eb00d1c619654f7c50f01330c9a0.cloudfront.net (CloudFront)
X-Amz-Cf-Id:
QI6BY-gXtyTaPUn5YgNddZDhnUwhSS16tjAO6biAvRC0SIB4qBYLpQ==
X-Amz-Cf-Pop:
LHR61-P7
X-Amzn-Appsync-Tokensconsumed:
1
X-Amzn-Requestid:
5cfd9869-ffd1-47e9-9e9d-49f9db6db65f
X-Cache:
Miss from cloudfront
:authority:
jpwkp3ahazcltftypmtlqah7v4.appsync-api.eu-north-1.amazonaws.com
:method:
POST
:path:
/graphql
:scheme:
https
Accept:
application/json, text/plain, */*
Accept-Encoding:
gzip, deflate, br
Accept-Language:
en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7
Content-Length:
476
Content-Type:
application/json; charset=UTF-8
Dnt:
1
Origin:
http://localhost:3000
Referer:
http://localhost:3000/
Sec-Ch-Ua:
"Google Chrome";v="117", "Not;A=Brand";v="8", "Chromium";v="117"
Sec-Ch-Ua-Mobile:
?0
Sec-Ch-Ua-Platform:
"Linux"
Sec-Fetch-Dest:
empty
Sec-Fetch-Mode:
cors
Sec-Fetch-Site:
cross-site
User-Agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
X-Amz-User-Agent:
aws-amplify/5.3.3 datastore/2 framework/2
X-Api-Key:
da2-idx6dytd3vbhdaa4hxmgme4sfe
```

Response (this example uses `ArtArtist` but same idea):
```
{
    "data": {
        "createArtArtist": null
    },
    "errors": [
        {
            "path": [
                "createArtArtist"
            ],
            "data": null,
            "errorType": "Unauthorized",
            "errorInfo": null,
            "locations": [
                {
                    "line": 2,
                    "column": 3,
                    "sourceName": null
                }
            ],
            "message": "Not Authorized to access createArtArtist on type Mutation"
        }
    ]
}
```

**Comment by jackshi0912** [comment]
![Screenshot from 2023-10-27 16-56-15](https://github.com/aws-amplify/amplify-js/assets/10685803/4236b021-690c-4f4e-9dd5-430459e2c95e)

**Comment by chrisbonifacio** [comment]
@jackshi0912 Thank you for sharing the info! It appears on the request that DataStore used an API Key to authorize the request, which means public access. 

You do have MULTI_AUTH enabled, so DataStore would first attempt to authorize the request with Cognito User Pools first, and if that fails, try again with another authMode like `API_KEY` if available. 

Here's the priority order of auth types:
https://docs.amplify.aws/lib/datastore/setup-auth-rules/q/platform/js/#multiple-authorization-types-priority-order

That being said, can you share the contents of your `aws-exports` file? I'm curious to see what `authenticationType`s you have enabled for your API.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
