### ISSUE TITLE
Nextjs 14.0.0 does not support node <18.17 while docket image supports 18.13.0

### ISSUE THREAD

**Issue by adarsh-drishya** [aws-amplify/amplify-js#12449]
### Is this related to a new or existing framework?

Next.js

### Describe the feature you'd like to request

 EBADENGINE Unsupported engine {
    npm WARN EBADENGINE   package: 'next@14.0.0',
    npm WARN EBADENGINE   required: { node: '>=18.17.0' },
    npm WARN EBADENGINE   current: { node: 'v18.13.0', npm: '8.19.3' }
    npm WARN EBADENGINE }

### Describe the solution you'd like

i want default docker image to support 18.17.0 atleast

### Describe alternatives you've considered

i dont know

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by adarsh-drishya** [comment]
not for this repo

**Comment by cwomack** [comment]
Hey, @adarsh-drishya 👋. Appreciate you recognizing the repo that can assist you better.  Did you want me to reopen this and transfer? Or are you creating a new issue within another?

**Comment by adarsh-drishya** [comment]
> Hey, @adarsh-drishya 👋. Appreciate you recognizing the repo that can assist you better.  Did you want me to reopen this and transfer? Or are you creating a new issue within another? 

I have created this issue in amplify-hosting a while back. @cwomack can you please prioritise this. I hope you understand the urgency.
