### ISSUE TITLE
Push Notifications on Android don't arrive on APP in Killed state.

### ISSUE THREAD

**Issue by matamicen** [aws-amplify/amplify-js#1245]
Hi everybody,

The Push is arriving in the 3 ways on Android: 

App in Foreground
App in Background
App is Killed

But when the App is killed, the notification message never arrives to the APP, so we can't process the message, we only can open the Notification.

We are sending pushs from PinPoint. 
We test on emulators an real Deviced with the same result.

We followed the AWS Amplify tutorial [https://aws-amplify.github.io/amplify-js/media/push_notifications_setup.html](url)

Thanks!!!

**Comment by supermock** [comment]
You should be needing this functionality, as I am, but it's been **27 days** since I opened this PR(https://github.com/aws-amplify/amplify-js/pull/1056) and so far without any feedback, I even had to rebase. I do not know what is happening...

**Comment by matamicen** [comment]
Ok, thanks for the update! ... it's a pitty because others librarys such as one signal is working fine that issue, so I think is a matter of time, I prefer to have some patient and  keep it with Amplify ...

**Comment by elorzafe** [comment]
Hi @matamicen, sorry for the delay on the response, we are looking into this issue. @powerful23 what do you think?

**Comment by matamicen** [comment]
Hi @elorzafe, thanks! ... Guys, we didn't try with **react-native run-android --variant=release** (I mean with the APK Signed) ... any of you try that? or you think the issue will still fail? 

Thanks.

**Comment by powerful23** [comment]
#1056 looks good to me. will merge it after testing.

**Comment by pribadi1st** [comment]
PushNotification works on me in android.

you need to put the PushNotification.configure outside the component

[Here's an example](https://github.com/zo0r/react-native-push-notification/issues/754#issuecomment-394850342)

**Comment by matamicen** [comment]
Thanks @powerful23 and @pribadi1st for that reference, it works now, we had to place this code before the component, so now the app is receiving the push if it is killed also! (And it is also working on Emulator!) 

```
PushNotification.onNotification((notification) => {
    console.log('in app notification', notification);
});
```

I will Paste the whole code of the test just for help others:

```

import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View} from 'react-native';
import Analytics from '@aws-amplify/analytics';
import PushNotification from '@aws-amplify/pushnotification';
import aws_exports from './aws-exports';

// PushNotification need to work with Analytics
Analytics.configure(aws_exports);

PushNotification.configure(aws_exports);

if(Platform.OS === 'android'){
    PushNotification.onNotification((notification) => {
    console.log('in app notification', notification);


});
}

const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' + 'Cmd+D or shake for dev menu',
  android:
    'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});


export default class App extends Component {


constructor(props) {
  super(props);

  
  
  this.state = {
 
   mensaje: '',
   token: '',
   login: ''
   
   
  };
}

  async componentDidMount() {
    if(Platform.OS === 'android'){
    PushNotification.onNotification((notification) => {
      console.log('in app notification', notification);
    
   
  
    });
            // get the registration token
      PushNotification.onRegister((token) => {
        console.log('in app registration', token);
        this.setState({token: token})
      });

    }

   
  }



  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}> Welcome to React Native!</Text>
        <Text style={styles.instructions}>To get started, edit App.js</Text>
        <Text style={styles.instructions}>{instructions}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});


```
