### ISSUE TITLE
Node aws-amplify has sub-sub dependency axios@0.26.0 which has high security vulnerability (snyk registry)

### ISSUE THREAD

**Issue by jackirvine97** [aws-amplify/amplify-js#12479]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Not applicable

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

- latest stable node build depends on axios 0.26.0
- this has a high security vulnerability - https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459

Relevant output from package lock json when you install LST aws-amplify into node application:
```
 "node_modules/@aws-amplify/api-rest": {
      "dependencies": {
        "@aws-amplify/core": "5.8.5",
        **"axios": "0.26.0",**
      }
}
```

### Expected behavior

n/a

### Reproduction steps

- Create node application
- install LST amplify-js
-  inspect package json

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello @jackirvine97,

Thank you for reaching out regarding the Axios package flagged by your report. On November 6, 2023, Amplify has published a new version of the aws-amplify package, version 5.3.12, which upgrades our Axios dependency from 0.26.0 to 1.6.0. We recommend that you upgrade to the latest version of aws-amplify to address this issue.

https://www.npmjs.com/package/aws-amplify/v/5.3.12

**Comment by jackirvine97** [comment]
That is awesome news - thank you so much for helping to resolve this issue!
