### ISSUE TITLE
Unknown error response when trying to authenticate user

### ISSUE THREAD

**Issue by kvowinckel** [aws-amplify/amplify-js#1249]
Hey,

When I try to use the **cognitoUser.authenticateUser** function, I receive the failure:

`Unknown error, the response body from fetch is: undefined`

The code is:

```
var authenticationData = {
      Username : details.email,
      Password : details.password,
    }
    var authenticationDetails = new AmazonCognitoIdentity.AuthenticationDetails(authenticationData);
    var poolData = {
      UserPoolId : '...',
      ClientId : '...',
    }
    var userPool = new AmazonCognitoIdentity.CognitoUserPool(poolData);
    var userData = {
       Username : details.email,
       Pool : userPool
    };
    var cognitoUser = new AmazonCognitoIdentity.CognitoUser(userData);

    cognitoUser.authenticateUser(authenticationDetails, {
       onSuccess: function (result) {
           var accessToken = result.getAccessToken().getJwtToken();
           this.storage.set('...', accessToken);
           this.navCtrl.setRoot('...');
         },
       onFailure: function(err) {
          console.log(err.message || JSON.stringify(err));
       },
       newPasswordRequired: (userAttributes, requiredAttributes) => {
          delete userAttributes.email_verified;
          userAttributes.family_name = "AutoComplete by app";
          userAttributes.name = "app user";

          cognitoUser.completeNewPasswordChallenge(
            "DummyPwd",
            userAttributes,
            this
          );

        }
     });
```

Updating npm-fetch did not help. The previouse issue was, that the password needed to be changed - it now takes the "DummyPwd".

Any ideas? 

Further info:
    "@ionic/app-scripts": "3.1.10",
    "@types/node": "^10.5.2",
    "@types/paho-mqtt": "^1.0.3",
    "@types/zen-observable": "^0.8.0",
    "json-loader": "^0.5.7",
    "typescript": "~2.6.2",
    "amazon-cognito-identity-js": "^2.0.14",
    "aws-amplify": "^0.2.9",
    "webpack": "^4.16.1"

**Comment by mikecann** [comment]
Im having exactly the same error!

```
Amplify.configure({
    identityPoolId: "XXXX",
    region: "XXXX",
    userPoolId: "XXXX",
    userPoolWebClientId: "XXXX"
});

const user: any = await Auth.signIn("mike.cann@gmail.com", "password");
console.log("user", user);
```

Trying to run it in a Jest test (fetch polyfilled using "isomorphic-fetch") so I can test end-to-end serverless lambdas.

```
"aws-amplify": "^1.0.0",
"typescript": "^2.8.1",
"jest": "^23.4.1",
```

**Comment by nk2580** [comment]
i solved this by downgrading the library to use 1.31.0 because fetch sucks

**Comment by elorzafe** [comment]
Hi @kvowinckel can you paste the HTTP response that is failing ? (hiding of course sensitive info)

**Comment by kvowinckel** [comment]
The main issue in the end was quite simple:
The following lines:
```
           this.storage.set('...', accessToken);
           this.navCtrl.setRoot('...');
```
are not referencing to the storage and navCtrl of the Page, but to the CognitoUser.
There, of cause, these functions do not exist. 

A solution for me was something like:
```
    page = this;
    cognitoUser.authenticateUser(authenticationDetails, {
       onSuccess: function (result) {
           var accessToken = result.getAccessToken().getJwtToken();
           page.storage.set('...', accessToken);
           page.navCtrl.setRoot('...');
         },
       onFailure: function(err) {
          console.log(err.message || JSON.stringify(err));
       },
       newPasswordRequired: (userAttributes, requiredAttributes) => {
          delete userAttributes.email_verified;
          userAttributes.family_name = "AutoComplete by app";
          userAttributes.name = "app user";

          cognitoUser.completeNewPasswordChallenge(
            "DummyPwd",
            userAttributes,
            this
          );

        }
     });
```

**Comment by TheNew000** [comment]
For anyone else running into this issue I resolved it by looking at the response from the network call and saw `"ChallengeName":"NEW_PASSWORD_REQUIRED"`  Then I looked up **Use case 23** in the readme docs:

[](https://github.com/aws-amplify/amplify-js/tree/master/packages/amazon-cognito-identity-js)
