### ISSUE TITLE
Error: Can't determine type for tag '<macro name="m3_comp_assist_chip_container_shape">?attr/shapeAppearanceCornerSmall</macro>'

### ISSUE THREAD

**Issue by vishnulanka-dataevolve** [aws-amplify/amplify-js#12503]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Push Notifications

### Amplify Categories

notifications

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I am getting the below mentioned error while installing the @aws-amplify/rtn-push-notification package for push notification.
Error: Can't determine type for tag '<macro name="m3_comp_assist_chip_container_shape">?attr/shapeAppearanceCornerSmall</macro>'
below i have given my package.json 
{
  "name": "DigiYatra",
  "version": "3.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native --openssl-legacy-provider start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@aws-amplify/ui-react": "^2.9.0",
    "@bam.tech/react-native-image-resizer": "^3.0.4",
    "@gorhom/bottom-sheet": "^4.1.5",
    "@openspacelabs/react-native-zoomable-view": "^2.1.1",
    "@react-icons/all-files": "^4.1.0",
    "@react-native-async-storage/async-storage": "^1.19.4",
    "@react-native-community/art": "^1.2.0",
    "@react-native-community/checkbox": "^0.5.12",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-community/geolocation": "^3.0.4",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/netinfo": "^8.3.1",
    "@react-native-community/toolbar-android": "^0.2.1",
    "@react-native-firebase/app": "^15.3.0",
    "@react-native-firebase/crashlytics": "^15.3.0",
    "@react-native-material/core": "^1.3.7",
    "@react-native-picker/picker": "^2.3.1",
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/core": "^6.1.1",
    "@react-navigation/drawer": "^6.5.6",
    "@react-navigation/material-bottom-tabs": "^6.1.1",
    "@react-navigation/native": "^6.1.2",
    "@react-navigation/native-stack": "^6.9.8",
    "@types/react-native-phone-input": "^0.2.2",
    "@types/react-native-snap-carousel": "^3.8.5",
    "add": "^2.0.6",
    "amazon-cognito-identity-js": "^5.2.14",
    "aws-amplify": "^4.3.46",
    "aws-amplify-react-native": "^6.0.3",
    "base-64": "^1.0.0",
    "bootstrap": "^5.2.3",
    "list": "^2.0.19",
    "lottie-react-native": "^5.0.1",
    "material-ui-community-icons": "^0.15.0",
    "moment": "^2.29.4",
    "native-base": "^3.4.3",
    "newrelic-react-native-agent": "^1.2.1",
    "or": "^0.2.0",
    "pdf-to-base64": "^1.0.3",
    "pdf-to-png-converter": "^2.6.0",
    "pdf2pic": "^2.1.4",
    "react": "17.0.2",
    "react-icons": "^4.3.1",
    "react-native": "0.67.3",
    "react-native-app-intro-slider": "^4.0.4",
    "react-native-barcode-builder": "^2.0.0",
    "react-native-barcode-creator": "^0.1.4",
    "react-native-base64": "^0.2.1",
    "react-native-bootstrap-styles": "^4.5.0-r",
    "react-native-btr": "^2.1.2",
    "react-native-camera": "^4.2.1",
    "react-native-confirmation-code-field": "^7.3.0",
    "react-native-confirmation-code-input": "^1.0.4",
    "react-native-countdown-component": "^2.7.1",
    "react-native-device-info": "^10.2.1",
    "react-native-dialog": "^9.2.1",
    "react-native-document-picker": "^8.2.0",
    "react-native-element-dropdown": "^2.10.0",
    "react-native-elements": "^3.4.2",
    "react-native-encrypted-storage": "^4.0.2",
    "react-native-event-listener": "^1.0.2",
    "react-native-event-listeners": "^1.0.7",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-get-random-values": "^1.9.0",
    "react-native-image-base64": "^0.1.4",
    "react-native-image-crop-picker": "^0.37.3",
    "react-native-image-filter-kit": "^0.8.0",
    "react-native-image-picker": "^4.10.3",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-in-app-review": "^4.2.1",
    "react-native-inappbrowser-reborn": "^3.6.3",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-local-mongodb": "^4.0.0",
    "react-native-modal": "^13.0.1",
    "react-native-navigation-drawer": "^1.2.2",
    "react-native-nfc-manager": "^3.14.8",
    "react-native-otp-auto-fill": "^0.1.17",
    "react-native-otp-verify": "^1.1.6",
    "react-native-paper": "^4.11.2",
    "react-native-pdf-thumbnail": "^1.2.1",
    "react-native-pdf-to-image": "^3.0.2",
    "react-native-permissions": "^3.3.1",
    "react-native-phone-number-input": "^2.1.0",
    "react-native-popup-dialog": "^0.18.3",
    "react-native-popup-menu": "^0.16.1",
    "react-native-progress-bar": "^0.1.2",
    "react-native-qrcode-svg": "^6.2.0",
    "react-native-radio-buttons-group": "^3.0.3",
    "react-native-raw-bottom-sheet": "^2.2.0",
    "react-native-reanimated": "^2.17.0",
    "react-native-redash": "^18.1.0",
    "react-native-responsive-dimensions": "^3.1.1",
    "react-native-responsive-fontsize": "^0.5.1",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-saf-x": "^0.5.3",
    "react-native-safe-area-context": "^4.2.4",
    "react-native-screens": "^3.18.2",
    "react-native-sha256": "^1.4.7",
    "react-native-shared-preferences": "^1.0.2",
    "react-native-side-menu": "^1.1.3",
    "react-native-side-menu-updated": "^1.3.2",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-sqlite-storage": "^6.0.1",
    "react-native-svg": "^13.14.0",
    "react-native-tab-navigator": "^0.3.4",
    "react-native-timer": "^1.3.6",
    "react-native-toast-message": "^2.1.3",
    "react-native-touch-id": "^4.4.1",
    "react-native-url-polyfill": "^2.0.0",
    "react-native-uuid": "^2.0.1",
    "react-native-vector-icons": "^9.1.0",
    "react-native-version-check": "^3.4.3",
    "react-native-video": "^5.2.1",
    "react-native-vision-camera": "^2.15.2",
    "react-native-walkthrough-tooltip": "^1.3.1",
    "react-native-weather-api": "^3.4.0",
    "react-native-webview": "^11.26.1",
    "react-native-xml2js": "^1.0.3",
    "react-native-zip-archive": "^6.0.8",
    "react-navigation": "^4.4.4",
    "react-navigation-stack": "^2.10.4",
    "react-phone-number-input": "^3.1.47",
    "react-redux": "^8.1.2",
    "react-responsive-carousel": "^3.2.23",
    "reanimated-bottom-sheet": "^1.0.0-alpha.22",
    "redux": "^4.2.1",
    "redux-persist": "^6.0.0",
    "regex": "^0.1.1",
    "rn-fetch-blob": "^0.12.0",
    "sp-react-native-in-app-updates": "^1.2.0",
    "vision-camera-face-detector": "^0.1.8",
    "watchman": "^1.0.0",
    "yarn": "^1.22.17"
  },
  "devDependencies": {
    "@babel/core": "7.17.5",
    "@babel/runtime": "7.17.2",
    "@react-native-community/eslint-config": "2.0.0",
    "@types/react": "^17.0.43",
    "@types/react-native": "^0.67.3",
    "babel-jest": "26.6.3",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "eslint": "7.14.0",
    "jest": "26.6.3",
    "metro-react-native-babel-preset": "0.66.2",
    "react-native-progress-steps": "^1.3.4",
    "react-native-typescript-transformer": "^1.2.13",
    "react-test-renderer": "17.0.2",
    "typescript": "^4.6.3"
  },
  "jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules/(?!@react-native|react-native|newrelic-react-native-agent)"
    ]
  }
}

### Expected behavior

App is not running and giving the mentioned error message 

### Reproduction steps

I have installed the @aws-amplify/rtn-push-notification and the app stops running 

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by vishnulanka-dataevolve** [comment]
Error: Can't determine type for tag '<macro name="m3_comp_assist_chip_container_shape">?attr/shapeAppearanceCornerSmall</macro>'  this is the proper error message which i am getting after installing the @aws-amplify/rtn-push-notification package. please help @cwomack

**Comment by vishnulanka-dataevolve** [comment]
Error: Can't determine type for tag '?attr/shapeAppearanceCornerSmall' this is the proper error message which i am getting after installing the @aws-amplify/rtn-push-notification package. please help @cwomack

**Comment by cwomack** [comment]
Hello, @vishnulanka-dataevolve and apologies on the delayed response! It looks like you're using the previous major version of Amplify with the latest version of Push Notifications.  Can you see if upgrading to the most recent version for your `@aws-amplify` package resolves the issue?

In building a new app with push notifications implemented, I wasn't able to reproduce the issues on the latest major version of Amplify (v5.x).  You may also need to delete your `node_modules` folder and `package-lock.json`, then reinstall the dependences with `npm install`.  If none of this works, then can you also share your full `package.json` please? Thanks!

**Comment by vishnulanka-dataevolve** [comment]
@cwomack  the same error is coming even after updating my aws-amplify package also. I even tried removing node modules and package-lock.json and do npm install but the error is same. Please provide me a solution for the same thanks.

**Comment by vishnulanka-dataevolve** [comment]
Any reply please...... Waiting for your response @cwomack

**Comment by HuiSF** [comment]
Hi @vishnulanka-dataevolve  this error is not actually caused by the `rtn-push-notification` package itself, this error occurred from your react-native android app. You may need to update your android app settings, this may be helpful for your case:

https://stackoverflow.com/questions/74191324/cant-determine-type-for-tag-macro-name-m3-comp-bottom-app-bar-container-colo

**Comment by vishnulanka-dataevolve** [comment]
I have already tried using all the above methods which are mentioned in stackoverflow solutions, but its not working and throwing the same error. Please provide me any other solution for the same @HuiSF

**Comment by cwomack** [comment]
Hey, @vishnulanka-dataevolve  👋.  Wanted to circle back on this issue now that v6 we've released v6 after this was opened.  Are you still experiencing this on a v6 app if you upgraded, or on a v5 app if not?

We may need more reproduction steps to determine what's happening, but appreciate your patience on responses here.

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
