### ISSUE TITLE
Expo Metro Web Build Failing

### ISSUE THREAD

**Issue by Stewartarmbrecht** [aws-amplify/amplify-js#12514]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication, DataStore

### Amplify Categories

storage, api

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 8.93 GB / 15.42 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 20.8.0 - /usr/local/bin/node
    Yarn: 4.0.1 - /usr/local/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 8.8.0 - /usr/local/share/npm-global/bin/pnpm
  npmPackages:
    @aws-amplify/datastore-storage-adapter: ^2.0.48 => 2.0.48 
    @aws-amplify/ui-react-native: ^1.2.28 => 1.2.28 
    @babel/core: ^7.20.0 => 7.23.2 
    @babel/preset-env: ^7.1.6 => 7.23.2 
    @expo/webpack-config: ^19.0.0 => 19.0.0 
    @react-native-async-storage/async-storage: 1.18.2 => 1.18.2 
    @react-native-community/netinfo: 9.3.10 => 9.3.10 
    @types/react: ~18.2.14 => 18.2.33 
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: ^6.3.6 => 6.3.6 
    amazon-cognito-identity-js/internals:  undefined ()
    aws-amplify: ^5.3.11 => 5.3.11 
    core-js: ^3.33.1 => 3.33.1 
    expo: ~49.0.15 => 49.0.16 
    expo-file-system: ~15.4.4 => 15.4.4 
    expo-sqlite: ~11.3.3 => 11.3.3 
    expo-status-bar: ~1.6.0 => 1.6.0 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    react-native: 0.72.6 => 0.72.6 
    react-native-get-random-values: ^1.9.0 => 1.9.0 
    react-native-safe-area-context: 4.6.3 => 4.6.3 
    react-native-url-polyfill: ^2.0.0 => 2.0.0 (1.3.0)
    react-native-web: ~0.19.6 => 0.19.9 
    typescript: ^5.1.3 => 5.2.2 
  npmGlobalPackages:
    eslint: 8.50.0
    pnpm: 8.8.0

```

</details>

### Describe the bug

When I run my app using "npx expo start --port=19100 --web"  I get the error "Uncaught TypeError: Class extends value undefined is not a constructor or null" when this code runs:  "import {
  Authenticator,
} from '@aws-amplify/ui-react-native';"

This started happening when I switched to using metro for the build.

I have a repo you can use to reproduce the error:  https://github.com/Stewartarmbrecht/my-app

### Expected behavior

The app runs and I don't get this error.

### Reproduction steps

use this repo:  https://github.com/Stewartarmbrecht/my-app

Once you spin up the container:

yarn install
yarn start

### Code Snippet

```javascript
// Last three lines in App.tsx from the snippet below.
import 'core-js/full/symbol/async-iterator';

import React, { useEffect, useState } from 'react';
import {
  StyleSheet,
  Text,
  View,
  TextInput,
  Pressable,
  SafeAreaView,
  Button,
} from 'react-native';
import { DataStore } from 'aws-amplify';
import { Todo } from './src/models/index';
import {
  Authenticator,
} from '@aws-amplify/ui-react-native';

```

### Log output

<details>

```
// Put your logs below this line
Uncaught TypeError: Class extends value undefined is not a constructor or null
    at __extends (tslib.es6.js:28:19)
    at LexRuntimeServiceServiceException.js:6:28
    at LexRuntimeServiceServiceException.js:11:24
    at loadModuleImplementation (require.js:352:5)
    at guardedLoadModule (require.js:242:1)
    at metroRequire (require.js:128:1)
    at models_0.js:5:15
    at loadModuleImplementation (require.js:352:5)
    at guardedLoadModule (require.js:242:1)
    at metroRequire (require.js:128:1)
__extends @ tslib.es6.js:28
(anonymous) @ LexRuntimeServiceServiceException.js:6
(anonymous) @ LexRuntimeServiceServiceException.js:11
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ models_0.js:5
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ DeleteSessionCommand.js:6
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ LexRuntimeService.js:4
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ index.js:1
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ AWSLexProvider.js:7
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ index.js:5
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ Interactions.js:5
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ index.js:5
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ index.js:13
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ App.tsx:16
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ AppEntry.js:5
loadModuleImplementation @ require.js:352
guardedLoadModule @ require.js:242
metroRequire @ require.js:128
(anonymous) @ aws-amplify-datastore-sqlite-adapter-expo.js:1674

```

</details>

### aws-exports.js

```javascript
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://<removed>.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "<removed>",
    "aws_cognito_identity_pool_id": "us-east-1:<removed>",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_<removed>",
    "aws_user_pools_web_client_id": "<removed>",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;

```

### Additional information and screenshots

I'm running the app in Edge.

**Comment by Stewartarmbrecht** [comment]
It looks like I might be wrong.  I think the error is originating in this file:  http://localhost:19100/workspaces/javascript-node/my-app/node_modules/@aws-amplify/datastore-storage-adapter/dist/aws-amplify-datastore-sqlite-adapter-expo.js

**Comment by Stewartarmbrecht** [comment]
When I run the app building with webpack I still get 5 packaging errors:

WARNING in ./node_modules/@aws-amplify/datastore-storage-adapter/dist/aws-amplify-datastore-sqlite-adapter-expo.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack:///../../src/ExpoSQLiteAdapter/ExpoSQLiteAdapter.ts' URL is not supported  

But the app runs fine in the browser.

**Comment by chrisbonifacio** [comment]
Hi @Stewartarmbrecht thanks for raising this issue. I tried visiting the repo you shared but it might be private as it redirects to a 404 page at the moment. Can you make sure it's public?

>When I run the app building with webpack I still get 5 packaging errors:

What are the other errors you're getting?

It seems that the webpack output regarding the sqlite-adapter-expo package is a warning and shouldn't be an impactful one. Is it blocking you from building?

**Comment by Stewartarmbrecht** [comment]
My bad.  I have updated it to be public.

**Comment by Stewartarmbrecht** [comment]
> Hi @Stewartarmbrecht thanks for raising this issue. I tried visiting the repo you shared but it might be private as it redirects to a 404 page at the moment. Can you make sure it's public?
> 
> > When I run the app building with webpack I still get 5 packaging errors:
> 
> What are the other errors you're getting?
> 
> It seems that the webpack output regarding the sqlite-adapter-expo package is a warning and shouldn't be an impactful one. Is it blocking you from building?

The WebPack error does not prevent the app from working.  I shared it because I thought it might be related to the metro error.  In other words I have something wrong that webpack treats as a warning.  Metro doesn't throw a warning in the build process but the app fails.

**Comment by Stewartarmbrecht** [comment]
I was able to build a second repo that is working.  It has all the right ingredients; datastore, appsync/api, auth, auth ui, yarn, typescript, and metro.  I just need to find out what is different.  Here is the working repo:  https://github.com/Stewartarmbrecht/AmplifyDataStoreExpo

**Comment by Stewartarmbrecht** [comment]
I think I pinpointed the problem.  Something about this metro.config.js causes the error:

```
const { getDefaultConfig } = require('expo/metro-config');
const path = require('path');

// Find the project and workspace directories
const projectRoot = __dirname;
// This can be replaced with `find-yarn-workspace-root`
const workspaceRoot = path.resolve(projectRoot, '../..');

const config = getDefaultConfig(projectRoot);

// 1. Watch all files within the monorepo
config.watchFolders = [workspaceRoot];
// 2. Let Metro know where to resolve packages and in what order
config.resolver.nodeModulesPaths = [
  path.resolve(projectRoot, 'node_modules'),
  path.resolve(workspaceRoot, 'node_modules'),
];
// 3. Force Metro to resolve (sub)dependencies only from the `nodeModulesPaths`
config.resolver.disableHierarchicalLookup = true;

module.exports = {
  ...config,
  resolver: {
    ...config.resolver,
    blockList: [config.resolver.blockList, /\/amplify\/.*$/],
    sourceExts: [...config.resolver.sourceExts, 'mjs'],
  },
};
```
This fixes it:
```
const { getDefaultConfig } = require("expo/metro-config");

const config = getDefaultConfig(__dirname);

module.exports = {
    ...config,
    resolver: {
        ...config.resolver,
        blockList: [config.resolver.blockList, /\/amplify\/.*$/],
        sourceExts: [...config.resolver.sourceExts, "mjs"],
    },
};
```

**Comment by Stewartarmbrecht** [comment]
Well, while the change above fixed the issue.  I soon realized the reason I had the first metro.config.js.  It was to handle expo in a mono-repo.  So I changed the repo I shared so the project is a mono-repo and added the second metro.config.js back.  I am back to getting the error:  
```
require.js:373  Uncaught TypeError: Class extends value undefined is not a constructor or null
    at __extends (tslib.es6.js:28:19)
    at LexRuntimeServiceServiceException.js:6:28
    at LexRuntimeServiceServiceException.js:11:24
    at loadModuleImplementation (require.js:352:5)
    at guardedLoadModule (require.js:242:1)
    at metroRequire (require.js:128:1)
    at models_0.js:5:15
    at loadModuleImplementation (require.js:352:5)
    at guardedLoadModule (require.js:242:1)
    at metroRequire (require.js:128:1)
```

**Comment by Stewartarmbrecht** [comment]
The error above is when running in web mode.  I also get this error when running on an external ios device:
```
 ERROR  TypeError: Super expression must either be null or a function, js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

**Comment by Stewartarmbrecht** [comment]
I changed App.tsx to only have text in a view.  The errors went away.  When I added back the line below both errors above occured.
```
Amplify.configure(awsExports);
```

**Comment by Stewartarmbrecht** [comment]
I fixed the issue by setting yarn to not hoist the amplify packages when using yarn workspaces.

## Yarn Classic

In this project I used Yarn classic.  https://github.com/Stewartarmbrecht/my-app
I fixed the issue by modifying the package.json in the sub package to include a top level property:
```
  "workspaces": {
    "nohoist": ["**/aws-amplify", "**/aws-amplify/**", "**/@aws-amplify", "**/@aws-amplify/**"]
  }
```
This project no longer gets the error but it has other problems when running not related to this issue.

## Yarn Latest

In this project I used the latest version of yarn.  https://github.com/Stewartarmbrecht/AmplifyDataStoreExpo

To fix the issue I added this to the sub packages package.json:

```
  "installConfig": {
    "hoistingLimits": "workspaces"
  },
```
This project is working fully. It also has an example of a custom package included in the expo app.
