### ISSUE TITLE
Change GetCurrentUserOutput type declaration

### ISSUE THREAD

**Issue by mehrdad-shokri** [aws-amplify/amplify-js#12515]
### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

Change `GetCurrentUserOutput` type
methods `
signIn,
  signInWithRedirect,
  signOut,
  signUp
` from `aws-amplify/auth` have their curresponding return types: `ConfirmSignUpOutput,
  SignInOutput,
  SignUpOutput` all method outputs type is an object with the relevant information about that method for example here's sign in type:
```
export type AuthSignInOutput<UserAttributeKey extends AuthUserAttributeKey = AuthUserAttributeKey> = {
	isSignedIn: boolean;
	nextStep: AuthNextSignInStep<UserAttributeKey>;
};
```
My problem is that type `GetCurrentUserOutput` is equal to `CognitoAuthUser` because it should be like other types here, be an object containing the relevant response information 

### Describe the solution you'd like

Convert response to object: 
`export type GetCurrentUserOutput = {
	user?: CognitoAuthUser;
};`
I think it is more inlined with the other type declarations and more readable.

### Describe alternatives you've considered

right now, it causes confusions both for me and my ide, to recognize the response type, because I've declared my function type as `GetCurrentUserOutput` and my ide is yelling at me saying `CognitoAuthUser` is not assignable to `GetCurrentUserOutput`

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [X] ⚠️ This feature might incur a breaking change

**Comment by ashwinkumar6** [comment]
Thanks for raising this issue @mehrdad-shokri 
>I've declared my function type as GetCurrentUserOutput and my ide is yelling at me saying CognitoAuthUser is not assignable to GetCurrentUserOutput

Could you please also share the code snippet or screenshot for the same so we can understand the API / type usage

**Comment by cwomack** [comment]
@mehrdad-shokri, let us know if there are further issues with this! We'd love to know if there's any room to improve our documentation related to the v6 release.  Thanks!
