### ISSUE TITLE
"No current user" Error When Accessing AppSync Query using API.graphql

### ISSUE THREAD

**Issue by reggie3** [aws-amplify/amplify-js#1252]
Do you want to request a feature or report a bug?
bug

What is the current behavior?
Attempting to access an AppSync query that has no access control on it results in a "No current user" error.  

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.
Create an AppSync API with "Amazon Cognito User Pool" as the Authorization type and "ALLOW" as the Default action.  Connect it to a user pool.  Create a query with that does not have @aws_auth directive as described in the AppSync security documentation [here](https://docs.aws.amazon.com/appsync/latest/devguide/security.html) 
The query I created looks like this:
![image](https://user-images.githubusercontent.com/7347192/42812376-74df87f2-898b-11e8-9366-0029530e193b.png)

What is the expected behavior?
The query should be run without requiring a user to sign in

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
Chrome Version 67.0.3396.99
Firefox 61.0 
AWS-Amplify 1.0
AWS-Amplify-React 1.0

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.
Debug info indicates that the program is attempting to get the user from the user pool even though the user has not attempted to sign in yet:
![image](https://user-images.githubusercontent.com/7347192/42812426-999673da-898b-11e8-9c21-236d12137c28.png)

**Comment by j2d2** [comment]
Had a similar issue - this is not clear in the docs. 
...changing to IAM with policies for the Auth & UnAuth Roles according to the IAM permissions link above made it so i could control the AppSync endpoints granularly.

But, I would like to manage some field level permissions with Cognito Groups - appears I can't pull this off with IAM as opposed to Cognito.

**Comment by reggie3** [comment]
@j2d2 Have you figured out a way to have additional IAM roles?  Power users or admins for example?

**Comment by j2d2** [comment]
haven't solved this yet... Reading the [Authorization Use Cases](https://docs.aws.amazon.com/appsync/latest/devguide/security-authorization-use-cases.html#use-case-owner-can-read) says that
> the check uses $context.identity.username which will be the friendly user sign-up name if Amazon Cognito user pools is used and will be the user identity if AWS IAM is used (including Amazon Cognito Federated Identities). There are other values to store for an owner such as the unique "Amazon Cognito identity" value, which is useful when federating logins from multiple locations...
it then refers to the [Resolver Mapping Template Context Reference](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-context-reference.html#aws-appsync-resolver-context-reference-identity), which explains the shape of the identity context, but the closest to an answer i see is in the "username" field description:
> In case of AMAZON_COGNITO_USER_POOLS authorization, the value of username is the value of attribute cognito:username. In case of AWS_IAM authorization, the value of the username is the value of the AWS User Principal. We recommend that you use cognitoIdentityId if you are using AWS IAM authorization with credentials vended from Amazon Cognito federated identities.

So, if we have the cognitoIdentityId can we somehow query Cognito for a list of Groups for that User in the backend?

If not, the only "solution" i've come up with is to pass the groups in a custom header... but i expect this raises some security concerns... open to ideas!!

**Comment by reggie3** [comment]
Right now, I'm leaning towards creating a separate table in DynamoDB to track user specific information using the user pool users' "sub" attribute or Cognito IAM ID as an ID for each user in that table, and keeping track of each user's groups there.

**Comment by rayhaanq** [comment]
Is there any solution/work around for this yet? I'm currently facing the same problem. For a type, I want reads to be allowed for the public, but writes only for a specific group of authenticated users

**Comment by etwillbefine** [comment]
I have the same issue. Identity Pool is configured to accept unauthenticated identities. Amplify is configured with `Auth: { mandatorySignIn: false }` identityPool and oauth settings for the hosted UI. AppSync and Amplify use `AMAZON_COGNITO_USER_POOLS` auth. Unauthenticated role from my Identity Pool is allowed to invoke and request graphql/AppSync. 

The request I want to be publicly available will not be made. Instead the error "No current user" is thrown. When I change auth type to `AWS_IAM` everything works fine without further changes. I think its not intended to only allow authenticated users when using cognito user pool auth?!

**Comment by selipso** [comment]
Any solutions or workarounds to this? I'm still having trouble keeping track of user identities. Would have to just use local storage and not use an API at all for unauthenticated users otherwise.

**Comment by GroveDev** [comment]
I'm on this boat too. Not able to do queries while not logged in makes no sense to me either. I'm looking forward to any fix on this one.

**Comment by undefobj** [comment]
@reggie3 @GroveDev @selipso @aldarund @etwillbefine @rayhaanq to clarify, it sounds like you want to allow public access to your AppSync GraphQL API for all or part of your schema. Currently AppSync supports one auth mode at a time though supporting multiple auth modes simultaneously is something that is being evaluated for the 2019 roadmap. In the meantime if this is something you're looking to do let me provide some options:

First, the most common solution is to use Cognito Identity and set your AppSync Authorization mode to AWS_IAM. You can then enable "unauthenticated access" in the Cognito Identity Pool which will allow the client to assume a role without logging in. You can set IAM permissions on that role for whatever parts of your GraphQL types you want to execute as outlined here: https://docs.aws.amazon.com/appsync/latest/devguide/security.html#aws-iam-authorization

Enabling UnAuthenticated access can be done with the amplify CLI when you run `amplify add auth` or `amplify update auth` and do **not** select the default configuration (it's disabled by default for least privilege). Alternatively you can perform this in the Cognito Identity console.

Another alternative that some customers have done is to create two GraphQL APIs, one for unauthenticated/anonymous access and one for when the user is authenticated. The unauthenticated one uses a strict subset of the schema (for example, queries only) for the other API and is configured with API key for authorization. They both use the same data sources. Your client then uses the appropriate endpoint with authentication configuration as appropriate when you call `amplify.configure` at which point your `API.graphql` calls will respect this configuration.

Hope this is helpful for the time being.

**Comment by NikoMontana** [comment]
@undefobj 
If I am using this method like you described with Cognito Identity and IAM permissions would I be able to use the user context within the resolvers to have fine grained access control?

**Comment by Jaikant** [comment]
@undefobj Thanks for your note. Creating two GraphQL API's would mean two API end points which the frontend would need to configure. An unnecessary complication.

**Comment by chriszirkel** [comment]
> @reggie3 @GroveDev @selipso @aldarund @etwillbefine @rayhaanq to clarify, it sounds like you want to allow public access to your AppSync GraphQL API for all or part of your schema. Currently AppSync supports one auth mode at a time though supporting multiple auth modes simultaneously is something that is being evaluated for the 2019 roadmap. In the meantime if this is something you're looking to do let me provide some options:
> 
> First, the most common solution is to use Cognito Identity and set your AppSync Authorization mode to AWS_IAM. You can then enable "unauthenticated access" in the Cognito Identity Pool which will allow the client to assume a role without logging in. You can set IAM permissions on that role for whatever parts of your GraphQL types you want to execute as outlined here: https://docs.aws.amazon.com/appsync/latest/devguide/security.html#aws-iam-authorization
> 
> Enabling UnAuthenticated access can be done with the amplify CLI when you run `amplify add auth` or `amplify update auth` and do **not** select the default configuration (it's disabled by default for least privilege). Alternatively you can perform this in the Cognito Identity console.
> 
> Another alternative that some customers have done is to create two GraphQL APIs, one for unauthenticated/anonymous access and one for when the user is authenticated. The unauthenticated one uses a strict subset of the schema (for example, queries only) for the other API and is configured with API key for authorization. They both use the same data sources. Your client then uses the appropriate endpoint with authentication configuration as appropriate when you call `amplify.configure` at which point your `API.graphql` calls will respect this configuration.
> 
> Hope this is helpful for the time being.

I want to be able to query data on the frontend web app depending on the some user id (cognito username or identityId) and I want to insert new data from my backend lambda function. Both options sound possible, but I have the following concerns:

1) enabling unauth access means that possibly everyone on the frontend could call my APIs, so I cannot be sure that only my lambda function is calling the graphql endpoint - right? is there a possibility to enable only authenticated access with a role that allows only graphql queries resources. Then my lambda execution role gets the same role plus additional access to all resources (e.g. appsync full access)?

2) Two APIs with different auth modes, user pools for frontend and API key for backend sounds manageable. How can I configure Amplify CLI to use the same data sources (dynamodb tables) on the second API?

**Comment by NikoMontana** [comment]
I went with exactly this approach (IAM) and gave this whole lib up. 

 https://github.com/aws-amplify/amplify-js/issues/2363#issuecomment-449011422

**Comment by mihaerzen** [comment]
@NikoMontana You maybe have a code example or point me to documentation on how exactly you achieved this? I'm only interested in the client-side code, obtaining the credentials. Thank you.

**Comment by dimitarrusev** [comment]
@j2d2 @reggie3 @rayhaanq I'm facing the same issue right now. I'm curious, (how) did you guys solve this? 

Ping @undefobj

**Comment by aireater** [comment]
> Another alternative that some customers have done is to create two GraphQL APIs, one for unauthenticated/anonymous access and one for when the user is authenticated....

@undefobj do you have an example of how to set this up?

I created another create react app site that i want to have anon access and added amplify as per docs. When I create a new graphql api in the front end it complains that i don't have any resolvers for my type (no @model since that will create a new table) so i removed it. If I create the graphql in the appsync console then I can't update the front end using the cli. 

What am i missing?

**Comment by undefobj** [comment]
We're looking at putting an example together for this. As outlined above if you want to allow multiple types of access permissions on the same API, at this point you will need to use IAM as AppSync doesn't yet support multi-auth.

This statement by @chriszirkel "enabling unauth access means that possibly everyone on the frontend could call my APIs" needs clarification. Enabling unauthenticated roles in Identity Pools means the client can receive AWS credentials which are separate from the authenticated role. This allows you to assign different IAM permissions to those roles, per the link I pointed to earlier: https://docs.aws.amazon.com/appsync/latest/devguide/security.html#aws-iam-authorization

To be crystal clear, this means that you can have unauthenticated access which the IAM policy for that role can just do one thing - like run queries only. Then the other authenticated role (which could be when users log in or from a Lambda function) can do more like perform mutations. In the link I posted above note that the `Resource` in the policy is set on a type in your schema like so:

```{
   "Version": "2012-10-17",
   "Statement": [
      {
         "Effect": "Allow",
         "Action": [
            "appsync:GraphQL"
         ],
         "Resource": [
            "arn:aws:appsync:us-west-2:123456789012:apis/YourGraphQLApiId/types/Query/fields/<Field-1>",
            "arn:aws:appsync:us-west-2:123456789012:apis/YourGraphQLApiId/types/Query/fields/<Field-2>",
            "arn:aws:appsync:us-west-2:123456789012:apis/YourGraphQLApiId/types/Mutation/fields/<Field-1>",
            "arn:aws:appsync:us-west-2:123456789012:apis/YourGraphQLApiId/types/Subscription/fields/<Field-1>"
         ]
     }
   ]
}
```

So you can use this to set appropriate values in the `../types/XXXXXX` definition.

@aireater I would suggest you open up a new issue with details on the CLI repo as your question seems to be related to something else with your API deployment.

**Comment by dimitarrusev** [comment]
@undefobj How can i get access to the user's groups when using **AWS_IAM** auth mode?

**Comment by undefobj** [comment]
@dimitarrusev unfortunately the Cognito User Pool groups are not available when using IAM.

**Comment by manueliglesias** [comment]
@joebernard 

I haven't tested it, but something like this might work and help you
https://codesandbox.io/s/25l7or15r

The idea is to wrap the `<ApolloProvider>` in a component that passes a different client depending on the auth state. Note that you might need to cleat the apollo client cache when swapping clients.

**Comment by dimitarrusev** [comment]
@undefobj Hey man, thanks for clearing things up. So, how should i approach this issue? Can you point me to any documentation or perhaps provide an example?

**Comment by mkaschke** [comment]
@All - Is there is a workaround when using AMAZON_COGNITO_USER_POOLS to have a public (non-logged in users )/private API? I couldn't find a solution so far, so I assume nobody would like to build a simple website like a blog or something with Amplify (API, Cognito)

**Comment by dimitarrusev** [comment]
@mkaschke As far as i know, there isn’t. You’ll have to either use **AWS_IAM** auth mode (check [this comment](https://github.com/aws-amplify/amplify-js/issues/1252#issuecomment-455336850)) or have two API’s (one public, one private). But even then, there are far too many issues e.g. there’s no docs on how to configure two different apollo profiles based on the user’s state (see [this comment](https://github.com/aws-amplify/amplify-js/issues/1252#issuecomment-456480589)), you can’t access user pool groups (see [this comment](https://github.com/aws-amplify/amplify-js/issues/1252#issuecomment-456522746)) which is very important etc. My conclusion at this point is that AppSync paired with Cognito is garbage. Yes, you can build very simple apps, quickly. But, if your intention is to build complex, real world application, run away.

**Comment by ngocketit** [comment]
I'm running into the same trouble and the workaround I'm currently using is to have 2 APIs, one using API_KEY and the other using AMAZON_COGNITO_USER_POOLS. The first one is mostly used on the server side and the later is on the client side, where a pre-created guest account is used and logged in to enable public features.

**Comment by undefobj** [comment]
@ngocketit @dimitarrusev @mkaschke @aireater @mihaerzen @NikoMontana @chriszirkel @Jaikant  we are looking to automate the setup of some more common admin tasks, including the IAM permissions for unauth and auth access to AWS resources such as APIs and Storage. If you could please take a look at the following RFC and leave any comments/feedback on your ideal workflows so that we can account for them in the upcoming design: https://github.com/aws-amplify/amplify-cli/issues/766

**Comment by mkaschke** [comment]
@All  :( - two thoughts / workarounds : 
**First:** Maybe a workaround could be to build a Route -> Lambda -> DB / Dynamodb stack for public data and use the appsync (graphsql / Cognito) just for private data (logged in users). 
**Second:** Does anyone tried googles firebase especially with authentification?

**Comment by dimitarrusev** [comment]
@undefobj Thanks, will do. While we’re here, can you respond to https://github.com/aws-amplify/amplify-js/issues/1252#issuecomment-456580797?

**Comment by undefobj** [comment]
@dimitarrusev I believe I have but perhaps the guidance has been lost in this thread. For clarity please follow the strategy to use IAM with Cognito Federated Identities here: https://github.com/aws-amplify/amplify-js/issues/1252#issuecomment-455336850

I suggest if you are unfamiliar with this process to use the Amplify CLI to create a new project and use the `amplify add auth` which creates a User Pool and Identity Pool, federating them both. By default an unauthenticated role will not be created for that Identity Pool but you can follow the manual `amplify add auth` questions to enable this. Then create an AppSync API with `amplify add api` and follow the directions. When you use the Amplify JS library in your app the `amplify.configure('aws_exports.js')` configuration step will allow your users to login with Cognito User Pools, and behind the scenes it will automatically get AWS IAM credentials for the appropriate auth or unauth role from Cognito Identity. If the user hasn't logged in yet you can get those credentials by calling `Auth.currentCredentials()` which will be for the unauthenticated role.

The thing that isn't automated yet, as outlined in the above comment is that you will need to:
1. Manually in the AppSync console set the Authorization mode to IAM
2. In the IAM console you will need to find the roles that the CLI created for the Cognito Identity Pool, and give the appropriate permissions for the unauth vs auth role.

**Comment by dimitarrusev** [comment]
@undefobj Hey man, again, thanks for taking the time to respond to my questions. I’m not sure if we’re on the same page here (i hope i'm not missing something) :)

Basically, i got that working (allowing access to unauthenticated and authenticated users by using **AWS_IAM** auth mode). However, i need to have different permissions for the authenticated users e.g. admin, author, user etc. and i'm trying to do that by putting them in a group, based on which i'll allow or deny access to specific queries and mutations. 

The thing is (like you said [here](https://github.com/aws-amplify/amplify-js/issues/1252#issuecomment-456522746)) that user pool groups are not available when using **AWS_IAM** auth mode (i can't access them in the resolver).

So my question is, how should i go about solving this issue?

**Comment by undefobj** [comment]
@dimitarrusev you are asking a separate question then the main issue asked in the thread (which is Public vs Private API). As you noted IAM doesn't have the concept of Groups, instead it has Roles which you'll need to "logically group" based on conditions. Amplify doesn't have tooling for this currently so you'll need to do it manually using Cognito Identity. I suggest you comment on the RFC here with your specific use case as we're looking to provide this in the coming months: https://github.com/aws-amplify/amplify-cli/issues/766
See the section entitled "Fine-grained access control by dynamically assigning roles based on Group membership or rules/token claims"

**Comment by undefobj** [comment]
All - Please see @dabit3 instructions above or the sample we posted here: https://github.com/dabit3/appsync-auth-and-unauth

As mentioned before we are looking to make this easier with CLI tooling in the following RFC: https://github.com/aws-amplify/amplify-cli/issues/766
For the short term hopefully this helps you get up and running.

**Comment by vparpoil** [comment]
I ran into the same issue, which is really blocking in a real use of amplify to build an app. It make me really question the choice we made of using amplify... 
I just tried the proposal [given above](https://github.com/aws-amplify/amplify-js/issues/1252#issuecomment-459920695) in order to allow unauthenticated users to run a mutation with the following : 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "appsync:GraphQL"
            ],
            "Resource": [
                "arn:aws:appsync:<REGION>:<CLIENTID>:apis/<APIID>/types/Mutation/fields/MutationName"
            ]
        }
    ]
} 
```

Here is my JS : 
```
Auth.currentCredentials().then(response => {
            API.graphql(graphqlOperation(MutationName), {input: input}).then(response => console.log(`response: ${response}`))
                .catch(error => console.log(error));
        })
```
And I always get a GraphQLError : "Request failed with status code 401". 
@dabit3 @undefobj  do you have insights on where to look ?

**Comment by mkaschke** [comment]
@vparpoil  - it is still not working right?

**Comment by vparpoil** [comment]
@mkaschke It's working now. I can get a unauthenticated user to run a graphql mutation using this setup

**Comment by vparpoil** [comment]
Another issue with this setup that happens to me : when running `amplify push`, the aws-exports.js file is overwritten and the `aws_appsync_authenticationType` switch back to AMAZON_COGNITO_USER_POOLS, resulting in 403 errors. 
It's quite annoying, but is it a bug or a feature ?

**Comment by selipso** [comment]
While the above setup instructions by @dabit3 work when using `API.graphql`, when following the following example from Amplify, the same `no current user` error occurs.

```
const result = await client.mutate({
    mutation: gql(createTodo),
    variables: {
      input: {
        name: 'Use AppSync',
        description: 'Realtime and Offline',
      }
    }
  });
```

**Comment by selipso** [comment]
After hours of struggling with converting my Cognito code to IAM, I've found the solution with migrating to AppSync with IAM. The [angular-chat-starter](https://github.com/aws-samples/aws-mobile-appsync-chat-starter-angular) repository helped, but I had to make a few changes.

Example source code for doing a mutation:

```ts
this.appsync.hc().then(
      client => {
        console.log('Received client. Mutating...');
        console.log(client);
        return client.mutate({
          mutation: gql(createTodo),
          variables: {
            input: {
              name,
              active: true
            }
          }
        }).then(({ data }) => {
          console.log('mutation complete', data);
        }).catch(err => console.log('Error creating classroom', err));
      }
    )
```

The above code is very similar to the app sync chat starter. However the chat starter uses Cognito. To use IAM, you have to initialize the AWSAppsyncClient() with different auth params, like so:

```ts
export class AppsyncService {
  // hc;
  _hc;

  constructor() {
    const client = new AWSAppSyncClient({
      url: aws_exports.aws_appsync_graphqlEndpoint,
      region: aws_exports.aws_project_region,
      auth: {
        type: AUTH_TYPE.AWS_IAM,
        credentials: () => Auth.currentCredentials()
      }
    });
    // this.hc = client.hydrated;
    this._hc = client;
  }
  hc() {
    return this._hc.hydrated();
  }
}
```

Works cleanly and with offline handling capabilities (yet to test those)

**Comment by jordanranz** [comment]
I am going to go ahead and close this as the original question seems to have been answered. Please reopen if you are experiencing any related problems.

**Comment by gl2748** [comment]
@dabit3 
One thing i would add to your how-to (which was very helpful btw - thanks!) is that for the unauthenticated role policy that you describe:
```
 "arn:aws:appsync:<REGION>:<ACCOUNTID>:apis/<APIID>/types/Mutation/fields/listTodos"
```
I think you meant `types/Query/fields/listTodos` - note `Query` and not `Mutation`.


That's it!.

For others working through this, the following were helpful tidbits.

It's worth noting that the IAM permissions on the AppSync 'DataSources'  config, under 
```
Create or use an existing role
Allow AWS AppSync to securely interact with your data source.
```
Are distinct from the IAM roles configured to interface the Cognito Users with Appsync, I'd suggest not editing or recreating these roles after your initial `amplify api create`.

**Comment by gl2748** [comment]
@vparpoil regarding the way `aws_appsync_authenticationType` is overridden you can do this to preserve your change outside editting the `aws-exports.js` directly.
```
const aws_exports_override = {...aws_exports, aws_appsync_authenticationType: "AWS_IAM",}
Amplify.configure(aws_exports_override);
```

**Comment by rudyhadoux** [comment]
Hi @elorzafe, Amplify-CLI does not allow unauth configuration anymore ??? So, how to allow unauthentified users ?

**Comment by rudyhadoux** [comment]
I have found the answer here :
https://stackoverflow.com/questions/53766100/how-to-properly-handle-unauthenticated-users-and-requests-in-aws-amplify-appsync

**Comment by dabit3** [comment]
@rudyhadoux we've also added first class support for multiple authentication / authorization types in the CLI. Here's the release blog -> https://aws.amazon.com/blogs/mobile/using-multiple-authorization-types-with-aws-appsync-graphql-apis/

**Comment by rudyhadoux** [comment]
OK thanks @dabit3. It is easier to test within apps without authentication...

**Comment by rudyhadoux** [comment]
@dabit3, I find that your fourteen steps are very tedious... why not allow unauthenticated users directly and easily with a new amplify-cli feature ? Besides, I use Angular and not React. I know AWS developers are React fans but Angular does exist too...

**Comment by aireater** [comment]
@dabit3 what's the process for adding another auth type to an existing graphql api (cognito). Can be done using the latest Amplify CLI or only the AppSync console?

**Comment by vanleuvenze** [comment]
@dabit3 Hurrah for [multiple auth types](https://aws.amazon.com/blogs/mobile/using-multiple-authorization-types-with-aws-appsync-graphql-apis/), nice work!

I'm having a little trouble using the new [authMode](https://aws-amplify.github.io/docs/js/api#aws-appsync-multi-auth) field with Amplify's API.graphql request function - it seems like authMode is overridden by whatever "aws_appsync_authenticationType" is defined as in aws-exports..

I'm wondering if authMode is meant to take precedence over the authenticationType field in aws-exports.js?

**Comment by rudyhadoux** [comment]
Help needed... I do not understand. Only for public datas, setting and generating an api-key with amplify-cli is enough ?

With a type example :
type Post @aws_api_key {
    id: ID!
    author: String
    title: String
    content: String
    url: String
    ups: Int!
    downs: Int!
    version: Int!
} 

That is all ?

**Comment by elliott-king** [comment]
Hello from Oct 2019. Posting for anyone who may be trying to implement multiple auth levels/types, and is confused on how to get there. To make some GraphQL queries public, I am using two auth modes. I am also using AWS AppSync with Amplify, which you may or may not be using.

Here are the relevant links I used:

[This tells you how to annotate your schema.](https://docs.aws.amazon.com/appsync/latest/devguide/security.html#using-additional-authorization-modes)

[This tells you what your client js should look like.](https://aws-amplify.github.io/docs/js/api#aws-appsync-multi-auth-1)

I also called `amplify update api` to update the auth used for my API. You want the advanced setup, choose your main auth mode (cognito pools in my case), then the `additional changes` bit (in my case, to add an api key). You do NOT need to call `amplify add auth` for an api key, but you will need to use it to set up cognito pools. 

----------
For some reason, there are two headers in the docs' api section for handling multiple auth methods. The one I linked above is if you are using AppSync, but [there is one if you aren't.](https://aws-amplify.github.io/docs/js/api#aws-appsync-multi-auth) It is easy to get them confused.

**Comment by rush86999** [comment]
I tried using multi-auth with amplify js. I also followed https://github.com/aws-amplify/amplify-cli/issues/2373 but did not work. 

here are the things I tried:
1. amplify update api and added iam for pubic auth
2. followed the docs and passed an object with authMode:

```
const hostData = await API
        .graphql({
          query: CheckProfileId,
          variables: params,
          authMode: 'AWS_IAM',
        });
```
any help? should I switch to API_KEY?

**Comment by rudyhadoux** [comment]
The solution I have found is to use only Cognito Groups with a "public" group.
And @auth rules for different groups.

**Comment by rush86999** [comment]
how do you add "public" group for unauthenticated users?

**Comment by rudyhadoux** [comment]
I log in and use a "public" user.

**Comment by grigull** [comment]
When you say "log in" do you mean that you create a single dummy user in cognito which is part of a group called "public" with some random email and password and give that email and password to any user that is not logged in?

**Comment by rudyhadoux** [comment]
You can log-in in your front-end with a public "dummy" user yes. 
And the real user knows nothing about that, but has access to public datas.

**Comment by naedx** [comment]
I configured _multiple authentication modes_ on my `@model` as described [here](https://aws.amazon.com/blogs/mobile/using-multiple-authorization-types-with-aws-appsync-graphql-apis/) but requests would be authenticated using only the _default_ authentication mode as specified using `amplify api configure`.  

As show below, I had tried specifying the auth mode inside my service class, but this would be overwritten every time I updated my schema.

```javascript
//MyAppAPI.service.ts 
const response = (await API.graphql(
  {
    query: statement, 
    variables: gqlAPIServiceArguments,
    authMode: GRAPHQL_AUTH_MODE.API_KEY
  });
````

I eventually found that I could instead change the auth mode programatically by doing the following: 

```javascript
// import { AmplifyService } from 'aws-amplify-angular';
// import Amplify from '@aws-amplify/core';
// ...
// ...
  
this.amplifyService.authStateChange$
  .subscribe(authState => {
      
  this.isLoggedIn = authState.state === 'signedIn';
  this.user = authState.user;

  if(this.isLoggedIn)
  {       
    Amplify.configure({
      "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS", 
    });
  }
  else
  {
    Amplify.configure({
      "aws_appsync_authenticationType": "API_KEY", 
    });
  }

});
  
  
// ...
```

I hope this helps someone.

**Comment by rudyhadoux** [comment]
Useful, thanks.

**Comment by half2me** [comment]
@naedx thanks so much for this, it saved me valuable time reading through outdated documentation 🙄 .
I'd like to add a piece of info here, I'm not sure about React, but in vue, the `authStateChange` is only triggered on changes, and on first load if the user is logged in. In the case of no users being logged in, when you first load the page, that bit of code will never run, so you have to assume that you are not logged in. 😢
