### ISSUE TITLE
User Pool & Federated Identities not working across multiple regions

### ISSUE THREAD

**Issue by ejdigby** [aws-amplify/amplify-js#1253]
**Do you want to request a feature or report a bug?**

Report a bug

**What is the current behavior?**

When a Cognito user pool is in a different region to an identity pool, a user can authenticate against the pool but doesn't receive an identity and receives a ```'cannot get guest credentials when mandatory signin enabled'``` error message.

Reproducible by creating a user pool and identity pool in different regions and using the built in _withAuthenticator_ HOC

**What is the expected behavior?**
The login credentials should be verified (which they are) and then a new identity should be created in the identity pool which isn't happening.

**Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?**

Using:
"aws-amplify": "^0.4.8",
"aws-amplify-react-native": "^0.2.19"

**Comment by powerful23** [comment]
@ejdigby did you set the `mandatorySignIn` to `true` when configuring the auth? If you did, then you cannot get the guest credentials from the federated identity pool

**Comment by ejdigby** [comment]
@powerful23 I did set it to true because I require my users to be authenticated when using the app. 

That error message shows me that the app can't get an IdentityID from the Identity pool which is in a different region.

**Comment by powerful23** [comment]
@ejdigby I see. Will look into that.

**Comment by powerful23** [comment]
you can now follow https://aws-amplify.github.io/amplify-js/media/authentication_guide#manual-setup to set the identity pool region. While this is not published yet, you can install `aws-amplify@unstable`
