### ISSUE TITLE
None of these failes exist None of these files exist:   * node_modules/@aws-amplify/core/src/awsClients/cognitoIdentity"

### ISSUE THREAD

**Issue by talaikis** [aws-amplify/amplify-js#12556]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

GraphQL API, Not applicable

### Amplify Categories

api, Not applicable

### Environment information

<details>

```
# Put output below this line
System:
    OS: Windows 11 10.0.22621
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 14.08 GB / 31.93 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20230709.023423.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
  Browsers:
    Edge: Chromium (119.0.2151.44)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @aws-amplify/api-graphql: 4.0.1 => 4.0.1
    @aws-amplify/api-graphql/internals:  undefined ()
    @aws-amplify/core: 6.0.1 => 6.0.1
    @aws-amplify/core/internals/adapter-core:  undefined ()
    @aws-amplify/core/internals/aws-client-utils:  undefined ()
    @aws-amplify/core/internals/aws-client-utils/composers:  undefined ()
    @aws-amplify/core/internals/aws-clients/cognitoIdentity:  undefined ()
    @aws-amplify/core/internals/aws-clients/pinpoint:  undefined ()
    @aws-amplify/core/internals/providers/pinpoint:  undefined ()
    @aws-amplify/core/internals/utils:  undefined ()
    @aws-amplify/core/server:  undefined ()
    @aws-amplify/datastore: 5.0.1 => 5.0.1
    @aws-amplify/pubsub: 6.0.1 => 6.0.1
    @aws-amplify/react-native: 1.0.1 => 1.0.1
    "amazon-cognito-identity-js": "6.3.6",
  npmGlobalPackages:
    @aws-amplify/cli: 12.8.2
    @react-native-community/cli: 12.0.0
    corepack: 0.20.0
    npm: 10.1.0
    snyk: 1.1238.0

```

</details>

### Describe the bug

```
None of these files exist:
  * node_modules\@aws-amplify\core\src\awsClients\cognitoIdentity(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs)
```

### Expected behavior

Working version 6.

### Reproduction steps

1. Install version 6 @aws-amplify lubs
2. Run app

### Code Snippet

N/A

### Log output

N/A

### aws-exports.js

N/A

### Manual configuration

N/A

### Additional configuration

N/A

### Mobile Device

N/A

### Mobile Operating System

N/A

### Mobile Browser

N/A

### Mobile Browser Version

N/A

### Additional information and screenshots

N/A

**Comment by nadetastic** [comment]
Hi @talaikis thanks for opening this issue. Could you clarify how you installed `aws-amplify`?

**Comment by nadetastic** [comment]
Hi @talaikis following up here - let me know if you still need assistance or can provide context to the question above.

**Comment by marleypowell** [comment]
> Hi @talaikis following up here - let me know if you still need assistance or can provide context to the question above.

Solution was to delete `node_modules/@aws-amplify` and `yarn install --force`. Folder name casing had changed...
