### ISSUE TITLE
Angular 17 SSR support?

### ISSUE THREAD

**Issue by RobertHH-IS** [aws-amplify/amplify-js#12555]
### Is this related to a new or existing framework?

Angular

### Is this related to another service?

SSR

### Describe the feature you'd like to request

Does Amplify work with the new Angular SSR functionality?  If so, would be interested in a quick description of how to get it to work correctly.  If not, it would be a great addition.

### Describe the solution you'd like

That amplify can simply deploy SSR enabled Angular applications.

### Describe alternatives you've considered

Not sure.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cwomack** [comment]
Hello, @RobertHH-IS 👋 and thank you for opening this issue. While we have first class SSR support for Next.js and Nuxt coming soon in v6, we're working on improvements for other frameworks like Angular.  As such, I'll convert this to a feature request and use this issue to aggregate feedback from the community related to Angular SSR in Amplify v6. 

We'd love to hear more details about what the intended use cases are for running SSR with Angular.  Can you (or anyone who upvotes/sees this issue) provide more information on how you want/intend to run Amplify in the server context with Angular? Thanks!

**Comment by MattyBalaam** [comment]
> … we're working on improvements for other frameworks…

@cwomack does this mean there will be a solution that we can use for server-side login in Remix? Or should I open a new ticket for this case?

**Comment by nadetastic** [comment]
With Amplify JS v6 we provide an adapter for Next.js for SSR support, however the underlying generic adapters can be used with other frameworks as well. 

We have published documentation on how to use the generic adapters which can be viewed [here](https://docs.amplify.aws/react/build-a-backend/server-side-rendering/). Please take a look and let me know if you have any questions.

**Comment by Leonelmarianog** [comment]
I managed to deploy an Angular 17 SSR application following the [deployment specification](https://docs.aws.amazon.com/amplify/latest/userguide/ssr-deployment-specification.html). Hope it points people in the right direction until we get official Angular support.

**Comment by Mitesh1711** [comment]
Hi @Leonelmarianog , would you be able to post the structure of your application on was amplify and also sample deploy-manifest.json?

**Comment by sbalfour** [comment]
I got it working by following [Deploying an Express server](https://docs.aws.amazon.com/amplify/latest/userguide/deploy-express-server.html), as Angular 17 already provides the express server.ts.

Follow the steps from 'Set up the Amplify deployment manifest'. Here are the basic changes to make it work, adjust them to suit...

`deploy-manifest.json` at root of project

```
{
  "version": 1,
  "framework": { "name": "express", "version": "4.18.2" },
  "routes": [
    {
      "path": "/*.*",
      "target": {
        "kind": "Static",
        "cacheControl": "public, max-age=1, immutable"
      },
      "fallback": {
        "kind": "Compute",
        "src": "default"
      }
    },
    {
      "path": "/*",
      "target": {
        "kind": "Compute",
        "src": "default"
      }
    }
  ],
  "computeResources": [
    {
      "name": "default",
      "runtime": "nodejs20.x",
      "entrypoint": "server.mjs"
    }
  ]
}
```

`postbuild.sh` in /bin 

```
#!/bin/bash

rm -rf ./.amplify-hosting

mkdir -p ./.amplify-hosting/compute

cp -r ./dist/your-project/server ./.amplify-hosting/compute/default

cp -r ./dist/your-project/browser ./.amplify-hosting/static

cp deploy-manifest.json ./.amplify-hosting/deploy-manifest.json
```

Add the postbuild command to package.json scripts

`"postbuild": "chmod +x bin/postbuild.sh && ./bin/postbuild.sh",`

Adjust the `server.ts` browserDistFolder to point the static folder

`const browserDistFolder = resolve(serverDistFolder, '../../static');`

and to use port 3000

`const port = process.env['PORT'] || 3000;`

Update`amplify.yml` in the AWS amplify

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .amplify-hosting
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

And finally, in Rewrites and redirects, remove or adjust the 200 rewrite rule to index.html that looks like this:

`</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>`

I think that covers all the changes. Would be nice if it just worked though  :sweat_smile:

**Comment by mumin-khan** [comment]
@sbalfour Can you please confirm whether env variables are available to express server at run-time?
We have some custom configurations which we pass to the express server and then hit an endpoint on it from the web-apps, which we are unable to run on amplify, we get a 404 error.

**Comment by daroczig** [comment]
@mumin-khan I think you might be looking for https://docs.aws.amazon.com/amplify/latest/userguide/ssr-environment-variables.html

**Comment by wis-dev** [comment]
@sbalfour following your steps on **Angular 18.2** it's not working.

AWS Amplify build error:
```
[WARNING]: Node.js version v18.18.2 detected.
The Angular CLI requires a minimum Node.js version of v18.19.
Please update your Node.js version or visit https://nodejs.org/ for additional instructions.

[ERROR]: !!! Build failed
[ERROR]: !!! Error: Command failed with exit code 3
```

Angular `18.1.x || 18.2.x` its only compatible with Node.js `^18.19.1 || ^20.11.1 || ^22.0.0`
See [Version compatibility](https://angular.dev/reference/versions).

I tried setting engine node version in `package.json` and disabling version checking, but I have the same result.

```
"scripts": {
  ...
  "build": "NG_DISABLE_VERSION_CHECK=1 ng build",
  "postbuild": "chmod +x bin/postbuild.sh && ./bin/postbuild.sh"
},
"engines": {
    "node": "18.0.0"
}
```

Downgrade to Angular 17 is not an option.

Can someone help me to find a solution for this case?

**Comment by daroczig** [comment]
FTR, we also used Amplify for Angular 17 SSR based on @sbalfour's fantastic write-up above, but we decided to move away after all, as response times were really bad. So instead we containerized the app, deployed on ECS and put Cloudfront in front of it -- which is quite a bit more work than setting up Amplify (especially if you want to autoscale it), and depending on (low) traffic, it might cost more, but much more flexible (e.g. you don't even see the deployed Edge Lambda fn in Amplify as being managed by AWS) and the performance is not comparable.

**Comment by RobertHH-IS** [comment]
Neither Angular or Amplify simply have the support or ecosystem - support for next js, vue when it comes to deployment is simply 10x.  I would consider how much effort you put into these ecosystems.

**Comment by albanx** [comment]
I am using right now CF + lambda + CF functions to power SSR with Angular 18. I was considering moving to amplify mainly because of the costs. Right now I pay around 40$ per month and with Amplify I would pay just 10$, but I cannot find a way to create the SSR in Angular neither documented. Also according to Daroczig it has worst performance.
For me right now a SSR takes around 2 seconds (which gets cached in CloudFront). Also CloudFront allows adding extra headers too which makes it more flexible in controlling requests.

Not sure if Amplify can support all of it

**Comment by StevenLopez-007** [comment]
> FTR, we also used Amplify for Angular 17 SSR based on @sbalfour's fantastic write-up above, but we decided to move away after all, as response times were really bad. So instead we containerized the app, deployed on ECS and put Cloudfront in front of it -- which is quite a bit more work than setting up Amplify (especially if you want to autoscale it), and depending on (low) traffic, it might cost more, but much more flexible (e.g. you don't even see the deployed Edge Lambda fn in Amplify as being managed by AWS) and the performance is not comparable.

I have the amplify.yml like this:
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm use 20
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .amplify-hosting
    files:
      - "**/*"
  cache:
    paths:
      - .npm/**/*
      
and works!
