### ISSUE TITLE
Amplify JS Library v6 - Module not found: Can't resolve '@aws-amplify/core/internals/adapter-core'

### ISSUE THREAD

**Issue by rpostulart** [aws-amplify/amplify-js#12564]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Authentication

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 14.0
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 902.11 MB / 16.00 GB
    Shell: 5.0.11 - /usr/local/bin/bash
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 119.0.6045.123
    Safari: 17.0
  npmPackages:
    @ampproject/toolbox-optimizer:  undefined ()
    @aws-amplify/adapter-nextjs: ^0.0.2-console-preview.e8aa063.0 => 0.0.2-console-preview.e8aa063.0+e8aa063 
    @aws-amplify/auth: ^5.6.6 => 5.6.6 (6.0.1-next.a1ea0f2.0+a1ea0f2)
    @aws-amplify/auth/cognito:  undefined ()
    @aws-amplify/auth/cognito/server:  undefined ()
    @aws-amplify/auth/server:  undefined ()
    @aws-amplify/core: ^5.8.6 => 5.8.6 (6.0.1-next.a1ea0f2.0+a1ea0f2)
    @aws-amplify/core/internals/adapter-core:  undefined ()
    @aws-amplify/core/internals/aws-client-utils:  undefined ()
    @aws-amplify/core/internals/aws-client-utils/composers:  undefined ()
    @aws-amplify/core/internals/aws-clients/pinpoint:  undefined ()
    @aws-amplify/core/internals/providers/pinpoint:  undefined ()
    @aws-amplify/core/internals/utils:  undefined ()
    @aws-amplify/core/server:  undefined ()
    @aws-amplify/ui-react: ^5.3.2 => 5.3.2 
    @aws-amplify/ui-react-internal:  undefined ()
    @babel/core:  undefined ()
    @babel/runtime:  7.22.5 
    @edge-runtime/cookies:  4.0.2 
    @edge-runtime/ponyfill:  2.4.1 
    @edge-runtime/primitives:  4.0.2 
    @hapi/accept:  undefined ()
    @headlessui/react: ^1.7.17 => 1.7.17 
    @heroicons/react: ^2.0.18 => 2.0.18 
    @mswjs/interceptors:  undefined ()
    @napi-rs/triples:  undefined ()
    @next/font:  undefined ()
    @next/react-dev-overlay:  undefined ()
    @opentelemetry/api:  undefined ()
    @react-google-maps/api: ^2.19.2 => 2.19.2 
    @segment/ajv-human-errors:  undefined ()
    @types/node: ^20 => 20.9.0 
    @types/react: ^18 => 18.2.37 
    @types/react-dom: ^18 => 18.2.15 
    @vercel/nft:  undefined ()
    @vercel/og:  0.5.15 
    acorn:  undefined ()
    amphtml-validator:  undefined ()
    anser:  undefined ()
    arg:  undefined ()
    assert:  undefined ()
    async-retry:  undefined ()
    async-sema:  undefined ()
    autoprefixer: ^10.0.1 => 10.4.16 
    aws-amplify: ^6.0.1-next.a1ea0f2.0 => 6.0.1-next.a1ea0f2.0+a1ea0f2 
    aws-amplify/analytics:  undefined ()
    aws-amplify/analytics/pinpoint:  undefined ()
    aws-amplify/auth:  undefined ()
    aws-amplify/auth/cognito:  undefined ()
    aws-amplify/auth/cognito/server:  undefined ()
    aws-amplify/auth/server:  undefined ()
    aws-amplify/internals/adapter-core:  undefined ()
    aws-amplify/storage:  undefined ()
    aws-amplify/storage/s3:  undefined ()
    aws-amplify/storage/s3/server:  undefined ()
    aws-amplify/storage/server:  undefined ()
    babel-packages:  undefined ()
    browserify-zlib:  undefined ()
    browserslist:  undefined ()
    buffer:  undefined ()
    bytes:  undefined ()
    ci-info:  undefined ()
    cli-select:  undefined ()
    client-only:  0.0.1 
    comment-json:  undefined ()
    compression:  undefined ()
    conf:  undefined ()
    constants-browserify:  undefined ()
    content-disposition:  undefined ()
    content-type:  undefined ()
    cookie:  undefined ()
    cross-spawn:  undefined ()
    crypto-browserify:  undefined ()
    css.escape:  undefined ()
    data-uri-to-buffer:  undefined ()
    debug:  undefined ()
    devalue:  undefined ()
    domain-browser:  undefined ()
    edge-runtime:  undefined ()
    eslint: ^8 => 8.53.0 
    eslint-config-next: 14.0.2 => 14.0.2 
    events:  undefined ()
    find-cache-dir:  undefined ()
    find-up:  undefined ()
    fresh:  undefined ()
    get-orientation:  undefined ()
    glob:  undefined ()
    gzip-size:  undefined ()
    http-proxy:  undefined ()
    http-proxy-agent:  undefined ()
    https-browserify:  undefined ()
    https-proxy-agent:  undefined ()
    icss-utils:  undefined ()
    ignore-loader:  undefined ()
    image-size:  undefined ()
    is-animated:  undefined ()
    is-docker:  undefined ()
    is-wsl:  undefined ()
    jest-worker:  undefined ()
    json5:  undefined ()
    jsonwebtoken:  undefined ()
    loader-runner:  undefined ()
    loader-utils:  undefined ()
    lodash.curry:  undefined ()
    lru-cache:  undefined ()
    micromatch:  undefined ()
    mini-css-extract-plugin:  undefined ()
    nanoid:  undefined ()
    native-url:  undefined ()
    neo-async:  undefined ()
    next: 14.0.2 => 14.0.2 
    node-fetch:  undefined ()
    node-html-parser:  undefined ()
    ora:  undefined ()
    os-browserify:  undefined ()
    p-limit:  undefined ()
    path-browserify:  undefined ()
    platform:  undefined ()
    postcss: ^8 => 8.4.31 
    postcss-flexbugs-fixes:  undefined ()
    postcss-modules-extract-imports:  undefined ()
    postcss-modules-local-by-default:  undefined ()
    postcss-modules-scope:  undefined ()
    postcss-modules-values:  undefined ()
    postcss-preset-env:  undefined ()
    postcss-safe-parser:  undefined ()
    postcss-scss:  undefined ()
    postcss-value-parser:  undefined ()
    process:  undefined ()
    punycode:  undefined ()
    querystring-es3:  undefined ()
    raw-body:  undefined ()
    react: ^18 => 18.2.0 
    react-builtin:  undefined ()
    react-dom: ^18 => 18.2.0 
    react-dom-builtin:  undefined ()
    react-dom-experimental-builtin:  undefined ()
    react-experimental-builtin:  undefined ()
    react-is:  18.2.0 
    react-refresh:  0.12.0 
    react-server-dom-turbopack-builtin:  undefined ()
    react-server-dom-turbopack-experimental-builtin:  undefined ()
    react-server-dom-webpack-builtin:  undefined ()
    react-server-dom-webpack-experimental-builtin:  undefined ()
    regenerator-runtime:  0.13.4 
    sass-loader:  undefined ()
    scheduler-builtin:  undefined ()
    scheduler-experimental-builtin:  undefined ()
    schema-utils:  undefined ()
    semver:  undefined ()
    send:  undefined ()
    server-only:  0.0.1 
    setimmediate:  undefined ()
    shell-quote:  undefined ()
    source-map:  undefined ()
    stacktrace-parser:  undefined ()
    stream-browserify:  undefined ()
    stream-http:  undefined ()
    string-hash:  undefined ()
    string_decoder:  undefined ()
    strip-ansi:  undefined ()
    superstruct:  undefined ()
    tailwindcss: ^3.3.0 => 3.3.5 
    tar:  undefined ()
    terser:  undefined ()
    text-table:  undefined ()
    timers-browserify:  undefined ()
    tty-browserify:  undefined ()
    typescript: ^5 => 5.2.2 (5.0.2)
    ua-parser-js:  undefined ()
    unistore:  undefined ()
    util:  undefined ()
    vm-browserify:  undefined ()
    watchpack:  undefined ()
    web-vitals:  undefined ()
    webpack:  undefined ()
    webpack-sources:  undefined ()
    ws:  undefined ()
    zod:  undefined ()
  npmGlobalPackages:
    @aws-amplify/cli: 12.6.0
    corepack: 0.17.0
    eas-cli: 5.4.0
    expo-cli: 6.3.10
    npm: 9.5.1


```

</details>

### Describe the bug

When I run:

 npm install aws-amplify@next

And run this:

```

import { runWithAmplifyServerContext } from "@aws-amplify/adapter-nextjs";
import { fetchAuthSession } from "aws-amplify/auth/server";
import { NextRequest, NextResponse } from "next/server";

export async function middleware(request: NextRequest) {
  const response = NextResponse.next();

  const authenticated = await runWithAmplifyServerContext({
    nextServerContext: { request, response },
    operation: async (contextSpec) => {
      try {
        const session = await fetchAuthSession(contextSpec, {});
        return session.tokens !== undefined;
      } catch (error) {
        console.log(error);
        return false;
      }
    },
  });

  if (authenticated) {
    return response;
  }

  return NextResponse.redirect(new URL("/login", request.url));
}

export const config = {
  matcher: ["/events/:path*", "/profile/:path*"],
};
```

I get this error:

Module not found: Can't resolve '@aws-amplify/core/internals/adapter-core'

### Expected behavior

I expect this code would run without errors

### Reproduction steps

1.  npm install aws-amplify@next

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by HuiSF** [comment]
Hello @rpostulart looking at your installed packages versions, there should be error there.

Could you try to reinstall the packages by running

```batch
npm install aws-amplify@next @aws-amplify/adapter-nextjs@next
```

It appears that the developer preview documentation has an error missing the info about the `@aws-amplift/adapter-nextjs` package.

**Comment by cwomack** [comment]
@rpostulart,can you share any relevant documentation you followed so we can make improvements if needed?

Beyond what @HuiSF stated above, you may also need to delete your `node-modules` folder and `package-lock.json` file, then reinstall dependencies with `npm install`.

**Comment by rpostulart** [comment]
```
@HuiSF @cwomack 

I have followed this instruction: https://docs.amplify.aws/lib-v1/ssr/nextjs/q/platform/js/#configure-amplify-for-client-side-usage

And I have used this sample as middleware:
https://docs.amplify.aws/lib-v1/ssr/nextjs/q/platform/js/#manage-auth-session-with-the-middleware

And change this line in the middleware:
```
export const config = {
  matcher: ["/events/:path*", "/profile/:path*"],
};
```


When running the app with npm run dev, I get this error:

```
Compiling /src/middleware ...
 ⨯ ./node_modules/@aws-amplify/adapter-nextjs/lib-esm/utils/createCookieStorageAdapterFromNextServerContext.js:15:0
Module not found: Can't resolve '@aws-amplify/core/internals/adapter-core'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@aws-amplify/adapter-nextjs/lib-esm/utils/index.js
./node_modules/@aws-amplify/adapter-nextjs/lib-esm/runWithAmplifyServerContext.js
./node_modules/@aws-amplify/adapter-nextjs/lib-esm/index.js
./src/middleware.tsx
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (395kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
```

**Comment by rpostulart** [comment]
in this folder @aws-amplify/core/internals I only see these folders:
- aws-client-utils
- aws-clients

But not:
- adapter-core

**Comment by Meags27** [comment]
I think I had the same issue here and documented the process here:

https://github.com/aws-amplify/amplify-js/issues/12147#issuecomment-1758809557

I solved by installing it exactly like this: npm install @aws-amplify/adapter-nextjs@^0.0.2-next.a1ea0f2.0 instead of what I tried which was "npm install @aws-amplify/adapter-nextjs"

And I was following this: https://docs.amplify.aws/lib-v1/ssr/nextjs/q/platform/js/#configure-amplify-for-server-side-usage

**Comment by rpostulart** [comment]
@Meags27 That did not the trick. Still the same issue. I also have this in next.config.js:

```
/** @type {import('next').NextConfig} */

const { withAmplify } = require("@aws-amplify/adapter-nextjs/with-amplify");
const config = require("./src/amplifyconfiguration.json");

/** @type {import('next').NextConfig} */
const nextConfig = {
  // your Next.js app configuration
};

module.exports = withAmplify(nextConfig, config);

```

Like I mentioned: https://github.com/aws-amplify/amplify-js/issues/12564#issuecomment-1808924843 the folder still does not exist

**Comment by rpostulart** [comment]
When starting from scratch with this new Amplify V6 documentation it works like charm:
https://docs.amplify.aws/nextjs/start/getting-started/setup/

And this instruction for the middleware:
https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/

**Comment by funes79** [comment]
I am doing the same instructions for middleware but got: `NotAuthorizedException` 
The cookies seems ok, on client side I have a user logged in, the Amplify is configured with ssr: true.

**Comment by cwomack** [comment]
@rpostulart, were you able to get things up an running on your existing project yet?  You may need to also delete your `.next` folder and try running the app again (should be generated again at runtime).  Good to hear that a fresh app in v6 worked like a charm, but want to get your existing next.js app running on v6 as well!

**Comment by cwomack** [comment]
@funes79, are you also on v6?

**Comment by HuiSF** [comment]
Hi @funes79 which API did you call to receive `NotAuthorizedException`? Can you briefly described your setup, and the request transition flow (e.g. from middleware to a page etc)?

**Comment by rallona** [comment]
This error for me: Error: Failed to read source code from /Users/rallona/web2023/winetour23/node_modules/@aws-amplify/adapter-nextjs/lib-esm/index.js

Using: "dependencies": {
        "@aws-amplify/adapter-nextjs": "^1.0.4",

**Comment by rallona** [comment]
Same problem to me. 

This function doesnt work:
```
const currentUser = await runWithAmplifyServerContext({
      nextServerContext: { cookies },
      operation: (contextSpec) => getCurrentUser(contextSpec)
    });
```

Neither this one:

      const currentUser = await runWithAmplifyServerContext({
```
        nextServerContext: { cookies },
        operation: async (contextSpec) => {
          try {
            const session = await fetchAuthSession(contextSpec);
```

The error is the same to me: **NotAuthorizedException: Unauthenticated access is not supported for this identity pool.**

**Comment by nadetastic** [comment]
Hi @rallona, just to confirm, are you passing `ssr: true` into Amplify.configure()?

```js
import { Amplify } from 'aws-amplify'
import amplifyconfig from 'amplifyconfiguration.json'

Amplify.config( amplifyconfig,  { ssr: true } )
```

**Comment by rallona** [comment]
Hi @nadetastic no because is a server page, not a client one.

In the docs say that only the client pages need SSR:True isn't it?

**Comment by rallona** [comment]
I have added the Amplify.configure( amplifyconfig,  { ssr: true } ) altought is a server page, but same error:

**NotAuthorizedException: Unauthenticated access is not supported for this identity pool.**

**Comment by HuiSF** [comment]
Hi @rallona when you encountered this exception, were you expecting a valid user session? I.e. valid token cookies were sent to your Next.js server?

If not, this is expected, you catch this exception and redirect the request to your sign in route.

If yes, can you double check if the request was sent from the browser with correct cookie header?

**Comment by HuiSF** [comment]
Thanks for the detail @rallona 

>After several test I cant see that the flow that fails is "From Next client page that has the login UI" -> "Server Nextjs Page"

Could you inspect the following using browser dev tool:

1. At the moment that sign in has completed, do you have Amplify auth tokens in the cookie store? For example:
<img width="861" alt="image" src="https://github.com/aws-amplify/amplify-js/assets/10602282/0714975f-0d09-486f-b044-835190641808">

2. When the transition of "From Next client page that has the login UI" -> "Server Nextjs Page" happens, does the corresponding HTTP request send the cookies via the `Cookie` header containing the Amplify auth tokens seen in item 1? For example:

<img width="1132" alt="image" src="https://github.com/aws-amplify/amplify-js/assets/10602282/7aa54257-e375-400b-9610-a562ddba6cf7">

In addition, could you provide your code examples that handles the transition of "From Next client page that has the login UI" -> "Server Nextjs Page"?

**Comment by rallona** [comment]
Hi @HuiSF 

Yes, the cookies are correctly created and sent in request headers (Including: LastAuthUser, accessToken, idToken, refreshToken, clockDrift...)

The transition is automatically setup in amplify configuration. I have set that after login go to /dashboard page.

So, after login UI it loads:

`https://myproject23bae-00518-develop.auth.eu-west-1.amazoncognito.com/oauth2/authorize?redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fdashboard%2F&response_type=code&client_id=10ntagmjq9cu&identity_provider=Google&scope=phone%20email%20openid%20profile%20aws.cognito.signin.user.admin&state=FLqCoaNBczoTe&code_challenge=2GS-u2jESvaAnTLeUQ&code_challenge_method=S256
`
And after this it loads /dashboard that has a page.js nextjs server page where I call the function:

` const currentUser = await runWithAmplifyServerContext({`

Where I get the error:

**NotAuthorizedException: Unauthenticated access is not supported for this identity pool.**

**Comment by rallona** [comment]
Hi @HuiSF 

Te cookies are received ok. I can see with the console.log. But the error persist, even after several page refresh. No changes at his point.

Ohther question, hoy can I know if the /utils/amplifyServerUtils.ts is working?

This is the code:

```
import { createServerRunner } from '@aws-amplify/adapter-nextjs';
import config from '@/amplifyconfiguration.json';


export const { runWithAmplifyServerContext } = createServerRunner({
  config
});
```

And this is the code inside amplifyconfiguration.json

```
{
  "aws_project_region": "eu-west-1",
  "aws_cognito_identity_pool_id": "eu-west-1:d2f0e0bd3",
  "aws_cognito_region": "eu-west-1",
  "aws_user_pools_id": "eu-west-1_HIxr",
  "aws_user_pools_web_client_id": "10ntagb4jq9cu",
  "oauth": {
    "domain": "w0518-develop.auth.eu-west-1.amazoncognito.com",
    "scope": [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin"
    ],
    "redirectSignIn": "http://localhost:3000/dashboard/",
    "redirectSignOut": "http://localhost:3000/",
    "responseType": "code"
  },
  "federationTarget": "COGNITO_USER_POOLS",
  "aws_cognito_username_attributes": [
    "EMAIL"
  ],
  "aws_cognito_social_providers": [
    "FACEBOOK",
    "GOOGLE"
  ],
  "aws_cognito_signup_attributes": [
    "EMAIL"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
    "SMS"
  ],
  "aws_cognito_password_protection_settings": {
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
    "EMAIL"
  ]
}
```

I dont know what other checks could I make... Thanks a lot for your help!

**Comment by HuiSF** [comment]
Can you paste the output from `cookies().getAll()` that made in this server component? mainly the cookie names, you can remove the tokens from it.

**Comment by rallona** [comment]
```
CognitoIdentityServiceProvider.XXXXXX.LastAuthUser
CognitoIdentityServiceProvider.XXXXXX.google_114970942558014885988.accessToken
CognitoIdentityServiceProvider.XXXXXX.google_114970942558014885988.idToken
CognitoIdentityServiceProvider.XXXXXX.google_114970942558014885988.refreshToken
CognitoIdentityServiceProvider.XXXXXX.google_114970942558014885988.clockDrift
```

**Comment by HuiSF** [comment]
Followed up in the other issue you opened @rallona

**Comment by HuiSF** [comment]
Hi @funes79  I think you were facing this issue https://github.com/aws-amplify/amplify-js/issues/12589, we are implementing a solution to resolve this issue. In the meantime please refer to this comment for workaround https://github.com/aws-amplify/amplify-js/issues/12648#issuecomment-1843952765

The issue in the original post should have been resolve (it was due to version resolution with pre-release tags). I optimistically recommend to close this issue.

**Comment by cwomack** [comment]
Given @HuiSF's comment above, we'll close this issue with the inbound solution and duplicate issues referenced in the comment.

**Comment by guillermoscript** [comment]
Im having a similar issue like this [comemnt](https://github.com/aws-amplify/amplify-js/issues/12564#issuecomment-1808924843) 
the error message that I get: `Error: Cannot find module @aws-amplify/core/internals/utils' imported from /@aws-amplify/adapter-nextjs/dist/esm/utils/getAmplifyConfig.mjs`

im using next.js and have posted a similar comment [here](https://github.com/aws-amplify/amplify-js/issues/13054#issuecomment-2027495972) 
im migrating from v5 to v6 so not sure this issue is resolved.


[Screenshot 2024-04-01 at 11 02 59 AM](https://github.com/aws-amplify/amplify-js/assets/52298929/4a0dcbcc-fced-4a5c-bbff-56ea0db7f24f)
