### ISSUE TITLE
Can not see the data created locally in Content in amplify studio 

### ISSUE THREAD

**Issue by elkee2003** [aws-amplify/amplify-js#12573]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-adminui/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-adminui/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

arn:aws:amplify:us-east-1:115372163617:apps/dnxdny8iom5jq

### Region

us-east-1

### Environment name

VS code

### Amplify CLI Version

12.4.0

### If applicable, what version of Node.js are you using?

v18.14.2

### What operating system are you using?

Windows

### Browser type?

Google Chrome

### Describe the bug

When I try to save to Datastore in one of the models locally, I won't be able to see it in the studio in 'Content'.
**Note:** I had to run amplify codegen before I could get the model repository into my local code, I don't know if this has anything to do with it. Previously this was automatically added. 
I also receive a warning in the console `User is unauthorized to query syncUsers with auth mode API_KEY. No data could be returned`

### Expected behavior

When I save to DataStore, I should be able to see it in the remote server (in content in amplify studio)

### Reproduction steps

1) I save to DataStore using:
` const user = await DataStore.save(new User({
         name, 
         address,
         phoneNumber,
         lat:parseFloat(lat), 
         lng:parseFloat(lng), 
         sub
       })`
2) I input the data

3) if i console.log it I can see the data

4) If i check on the remote server (ie in amplify studio in content), the data is not saved in the models

**Comment by chrisbonifacio** [comment]
Hi @elkee2003 I see that you were able to get something working after enabling multi_auth in the DataStore configuration. Could you confirm what that was? 

A few other questions:

1. Are you able to create records using `DataStore.save` and observe that they are persisted to the DynamoDB table?

2. Are you still observing the `User is unauthorized to query syncUsers with auth mode API_KEY. No data could be returned` warning in the console?

If so, please share your schema, Amplify.configuration and/or DataStore.configuration.

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
