### ISSUE TITLE
Option to Retrieve Social Profiles When Using withFederated Component from aws-amplify-react

### ISSUE THREAD

**Issue by reggie3** [aws-amplify/amplify-js#1258]
Do you want to request a feature or report a bug?
Request Feature

What is the current behavior?
Using `withFederated` component from aws-amplify-react provides no option to get the social profile of the Facebook or Google user being logged in.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.
N/A; not a bug.

What is the expected behavior?
It would be useful to have the option of retrieving the user's social profile.  I'm currently using the `withFederated` HOC like this:

```
const Buttons = props => (
  <div
    style={{
      display: 'flex',
      flexDirection: 'row',
    }}
  >
    <GoogleLoginButton onClick={props.googleSignIn} />
    <FacebookLoginButton onClick={props.facebookSignIn} />
  </div>
);
const Federated = withFederated(Buttons);
```

I think it should be possible to add a prop to the components passed to the withFederated HOC that is then passed to the `withGoogle`, and `withFacebook` components.  The prop would alter the components request to the Google and FaceBook APIs to include a request for the profile.  The profile information could then be returned alongside the information from the Auth.currentAuthenticatedUser() call.  Possibly as the following:
`return {...Auth.currentAuthenticatedUser(), {socialProfile: <SOCIAL PROFILE OBJECT HERE>};`

This should allow the continuation of accessing the current authenticated user information as currently expected while also having access to the optional  socialProfile information.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
Using 1.0.0

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by reggie3** [comment]
BTW, I'd like to work on implementing this feature in a fork as a possible pull request.  Sorry, I didn't make that clear in the original post.  I just wanted to discuss it with somebody first.

**Comment by reggie3** [comment]
@mbahar Are you planning on implementing this feature, or would a pull request suffice?

**Comment by sammartinez** [comment]
@reggie3 Is this still a use case for you? Please let us know. Thanks!
