### ISSUE TITLE
MFA SMS & TOTP: 'currentAuthenticatedUser' response differing

### ISSUE THREAD

**Issue by CHR15-** [aws-amplify/amplify-js#1259]
### Do you want to request a feature or report a bug?

**Bug** 🐛 

### What is the current behavior?

PATH 1: `Auth.setPreferredMFA(user, SMS)`
PATH 2: `Auth.setPreferredMFA(user, TOTP)`

when we run `Auth.currentAuthenticatedUser()` after these flows to get the mfa preference.. we get the following response:

PATH 1
```
{  
   "MFAOptions":[  
      {  
         "AttributeName":"phone_number",
         "DeliveryMedium":"SMS"
      }
   ],
   "UserAttributes":[  
      {  
         "Name":"sub",
         "Value":"uuid"
      },
      {  
         "Name":"email_verified",
         "Value":"true"
      },
      {  
         "Name":"name",
         "Value":"chris"
      },
      {  
         "Name":"phone_number_verified",
         "Value":"false"
      },
      {  
         "Name":"phone_number",
         "Value":"XXX"
      },
      {  
         "Name":"custom:signupdomain",
         "Value":"http://localhost:9001"
      },
      {  
         "Name":"email",
         "Value":"chris@example.com"
      }
   ],
   "Username":"UUID"
}
```

PATH 2:

```
{
   "PreferredMfaSetting":"SOFTWARE_TOKEN_MFA",
   "UserAttributes":[
      {
         "Name":"sub",
         "Value":"uuid"
      },
      {
         "Name":"email_verified",
         "Value":"true"
      },
      {
         "Name":"name",
         "Value":"chris"
      },
      {
         "Name":"custom:signupdomain",
         "Value":"http://localhost:9001"
      },
      {
         "Name":"email",
         "Value":"chris@example.com"
      }
   ],
   "UserMFASettingList":[
      "SOFTWARE_TOKEN_MFA"
   ],
   "Username":"uuid"
}
```

Surely both should follow the same response format? they are currently completely different.

What adds even more complexity to this is if I now set SMS after I've enabled TOTP, I get the following response:

```
{  
   "PreferredMfaSetting":"SMS_MFA",
   "UserAttributes":[  
      {  
         "Name":"sub",
         "Value":"uuid"
      },
      {  
         "Name":"email_verified",
         "Value":"true"
      },
      {  
         "Name":"name",
         "Value":"chris"
      },
      {  
         "Name":"phone_number_verified",
         "Value":"false"
      },
      {  
         "Name":"phone_number",
         "Value":"xxx"
      },
      {  
         "Name":"custom:signupdomain",
         "Value":"http://localhost:9001"
      },
      {  
         "Name":"email",
         "Value":"chris@example.com"
      }
   ],
   "UserMFASettingList":[  
      "SMS_MFA"
   ],
   "Username":"uuid"
}
```

So now we have 1 flow for SMS, 1 flow for TOTP... 2 completely different responses.. If I overwrite the TOTP path with SMS.. I get the correct response back for both flows.. but not the initial SMS setup (PATH1)..

`Auth.getMFAOptions` also seems to be broken for TOTP options returning too as mentioned in https://github.com/aws-amplify/amplify-js/issues/1204, so currently there isn't a standardised way of retrieving the MFA selection for a given authed user, right? I wouldn't say it's feature request, more of a bug.

### What is the expected behavior?

`Auth.currentAuthenticatedUser()` (or `getMFAOptions`) should return the same payload for either SMS or TOTP MFA setup

### Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

1.0+

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Linked Bugs**
https://github.com/aws-amplify/amplify-js/issues/1226
https://github.com/aws-amplify/amplify-js/issues/1204

**Comment by elorzafe** [comment]
@powerful23 what do you think?

**Comment by powerful23** [comment]
@CHR15- I made a new api to get the current mfa option type. #1254

**Comment by CHR15-** [comment]
@elorzafe & @powerful23 .. seems to be more issues here: https://github.com/aws-amplify/amplify-js/issues/1343
