### ISSUE TITLE
Federated sign in doesn't complete on Android using web links

### ISSUE THREAD

**Issue by markgaucher** [aws-amplify/amplify-js#12597]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 13.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.00 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.6 - ~/.nvm/versions/node/v20.2.0/bin/npm
    Watchman: 2023.10.30.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 16.6
  npmPackages:
    @babel/core: ^7.23.2 => 7.23.2 (7.18.6, 7.12.0, 7.21.3, 7.18.9)
    @babel/runtime: ^7.23.2 => 7.23.2 (7.16.5, 7.10.5, 7.18.6, 7.18.0, 7.21.0, 7.12.0, 7.11.2, 7.18.9)
    @bugsnag/plugin-react-navigation: ^7.17.0 => 7.17.0 
    @bugsnag/react-native: ^7.20.2 => 7.20.2 
    @bugsnag/source-maps: ^2.0.0 => 2.0.0 
    @datadog/mobile-react-native: ^1.0.0 => 1.0.0 
    @datadog/mobile-react-navigation: ^1.0.0 => 1.0.0 
    @formatjs/intl-getcanonicallocales: ^2.0.4 => 2.0.4 
    @formatjs/intl-locale: ^3.0.8 => 3.0.8 
    @formatjs/intl-numberformat: ^8.3.0 => 8.3.0 
    @formatjs/intl-pluralrules: ^5.1.5 => 5.1.5 
    @hookform/resolvers: ^3.1.1 => 3.1.1 
    @hookform/resolvers/ajv:  1.0.0 
    @hookform/resolvers/arktype:  1.0.0 
    @hookform/resolvers/class-validator:  1.0.0 
    @hookform/resolvers/computed-types:  1.0.0 
    @hookform/resolvers/io-ts:  1.0.0 
    @hookform/resolvers/joi:  1.0.0 
    @hookform/resolvers/nope:  1.0.0 
    @hookform/resolvers/superstruct:  1.0.0 
    @hookform/resolvers/typanion:  1.0.0 
    @hookform/resolvers/typebox:  1.0.0 
    @hookform/resolvers/vest:  1.0.0 
    @hookform/resolvers/yup:  1.0.0 
    @hookform/resolvers/zod:  1.0.0 
    @react-native-community/async-storage: ^1.12.1 => 1.12.1 
    @react-native-community/clipboard: ^1.2.3 => 1.5.0 
    @react-native-community/netinfo: ^9.3.7 => 9.3.7 
    @react-native-firebase/analytics: ^7.3.1 => 7.6.7 
    @react-native-firebase/app: ^8.2.0 => 8.4.5 
    @react-native-firebase/crashlytics: ^8.1.2 => 8.4.9 
    @react-native-masked-view/masked-view: ^0.2.6 => 0.2.6 
    @react-native-picker/picker: ^2.3.1 => 2.3.1 
    @react-navigation/bottom-tabs: ^6.0.9 => 6.0.9 
    @react-navigation/elements: ^1.2.1 => 1.2.1 
    @react-navigation/native: ^6.0.6 => 6.0.6 
    @react-navigation/stack: ^6.0.11 => 6.0.11 
    @shopify/flash-list: ^1.4.3 => 1.4.3 
    @svgr/cli: ^6.5.1 => 6.5.1 
    @testing-library/dom: ^7.12.0 => 7.26.0 (8.11.3, 9.0.0)
    @testing-library/jest-dom: ^5.9.0 => 5.11.4 
    @testing-library/jest-native: ^5.4.1 => 5.4.1 
    @testing-library/react: ^14.0.0 => 14.0.0 (12.1.3)
    @testing-library/react-hooks: ^8.0.1 => 8.0.1 (7.0.2)
    @testing-library/react-native: ^11.2.0 => 11.5.2 
    @types/i18n-js: ^3.0.3 => 3.0.3 
    @types/jest: ^26.0.0 => 26.0.14 
    @types/node: ^13.7.4 => 13.13.15 (14.14.37, 14.11.8, 13.13.48)
    @types/react: ^18.0.0 => 18.0.34 
    @types/react-dom: ^18.0.0 => 18.0.11 
    @types/react-native: ^0.69.8 => 0.69.20 
    @types/react-test-renderer: ^17.0.2 => 17.0.2 (17.0.1)
    @types/yup: ^0.29.2 => 0.29.4 
    @typescript-eslint/eslint-plugin: ^4.8.1 => 4.8.1 (4.29.3)
    @typescript-eslint/parser: ^3.7.1 => 3.8.0 (4.29.3)
    @ua/react-native-airship: ^16.1.1 => 16.1.1 
    AirshipExample:  0.0.1 
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: 5.2.10 => 5.2.10 (6.2.0)
    babel-jest: ^26.1.0 => 26.5.2 (26.6.0)
    date-fns: ^2.14.0 => 2.16.1 (2.29.3)
    eslint: ^7.5.0 => 7.6.0 (7.32.0)
    eslint-plugin-flowtype: ^5.9.1 => 5.9.1 
    eslint-plugin-import: ^2.24.2 => 2.24.2 
    eslint-plugin-jsx-a11y: ^6.4.1 => 6.4.1 
    eslint-plugin-react: ^7.25.1 => 7.25.1 (7.24.0)
    eslint-plugin-react-hooks: ^4.2.0 => 4.2.0 
    example:  0.0.1 
    expo: ^47.0.14 => 47.0.14 
    expo-localization: ~14.1.1 => 14.1.1 
    expo-print: 11.2.0 => 11.2.0 
    expo-sharing: 11.4.0 => 11.4.0 
    expo-web-browser: ^11.4.0 => 12.0.0 
    firepit:  1.1.0 
    formik: ^2.2.9 => 2.2.9 
    hermes-inspector-msggen:  1.0.0 
    husky: ^4.2.5 => 4.3.0 
    i18n-js: ^3.5.1 => 3.7.1 
    jest: ^26.6.0 => 26.6.0 
    json-schema-yup-transformer: ^1.6.12 => 1.6.12 
    lottie-ios: 3.2.3 => 3.2.3 
    lottie-react-native: ^5.1.3 => 5.1.3 
    metro-react-native-babel-preset: ^0.71.3 => 0.71.3 (0.70.3, 0.72.3, 0.67.0)
    msw: ^0.38.1 => 0.38.2 
    path: ^0.12.7 => 0.12.7 
    prettier: ^2.6.0 => 2.6.0 (2.8.6, 2.8.8)
    pretty-quick: ^3.1.0 => 3.1.0 
    query-string: ^6.12.0 => 6.13.5 (7.1.0, 5.1.1)
    react: 18.0.0 => 18.0.0 
    react-dom: 18.0.0 => 18.0.0 
    react-hook-form: ^7.44.3 => 7.44.3 
    react-native: 0.69.8 => 0.69.8 (0.68.2)
    react-native-appsflyer: ^6.9.4 => 6.9.4 
    react-native-bootsplash: ^5.0.4 => 5.0.4 
    react-native-config: ^1.4.6 => 1.4.6 
    react-native-date-picker: ^4.2.10 => 4.2.10 
    react-native-default-preference: ^1.4.3 => 1.4.3 
    react-native-device-info: ^10.0.2 => 10.0.2 
    react-native-gesture-handler: ^1.10.3 => 1.10.3 
    react-native-inappbrowser-reborn: ^3.7.0 => 3.7.0 
    react-native-linear-gradient: ^2.6.2 => 2.6.2 
    react-native-mmkv: ^2.4.3 => 2.4.3 
    react-native-safe-area-context: ^3.4.1 => 3.4.1 
    react-native-screens: ^3.15.0 => 3.15.0 
    react-native-svg: ^12.4.4 => 12.4.4 
    react-native-webview: ^13.6.0 => 13.6.0 
    react-test-renderer: ^18.0.0 => 18.2.0 
    typescript: ^4.6.3 => 4.6.4 (4.4.2)
    victory-native: ^36.2.0 => 36.6.8 
    yup: ^0.32.11 => 0.32.11 (0.29.3)
    zod: ^3.22.3 => 3.22.4 
  npmGlobalPackages:
    appium-xcuitest-driver: 4.33.2
    appium: 2.0.1
    corepack: 0.17.2
    eas-cli: 3.17.0
    expo-cli: 6.3.10
    npm: 9.6.6
```

</details>

### Describe the bug

I currently use `@aws-amplify/auth`, `@aws-amplify/core`, and `amazon-cognito-identity-js` to handle authentication in a React Native application. I use a custom `urlOpener` function that opens a `react-native-inappbrowser-reborn` window to complete federated sign in. I have been using a custom URL scheme (`myapp://`) for `redirectSignIn` and `redirectSignOut` for several years without issue.  I am looking at migrating the redirects for our federated sign in from `myapp://` to a `https://` domain in order to utilize [Android App Links](https://developer.android.com/training/app-links). My application already supports Android App Links outside of authentication, but they typically use the built in Chrome browser as opposed to Chrome Custom Tabs, which is what’s used in `react-native-inappbrowser-reborn` (and equivalent libraries such as `expo-web-browser`).

In practice what I’m noticing is that when `https://` redirects are used in combination with `react-native-inappbrowser-reborn` they are not functioning as expected. Instead of automatically dismissing the browser window they are opening the equivalent web application in the federated sign in window. If I do not provide a custom `urlOpener` function (and use the default Chrome browser) then the flow works as expected, with an added (undesired) step where the user must specify what application should be used to open the link. Because I don’t have a strong Android background it’s unclear whether or not this is expected behaviour for `https://` redirects used in a federated sign in, or if there's something I'm missing in my setup. 

### Expected behavior

The browser window currently dismisses when the user is sent to the provided `redirectSignIn` (or `redirectSignOut`). The expectation was that switching to an `https://` redirect would result in no user facing changes (the in app browser window is automatically dismissed without any additional user interactions).

### Reproduction steps

1. Set up an `<intent-filter>` in the `AndroidManifest.xml` file
2. Set a `redirectSignIn` redirect to use an `https://` URL
3. Add a custom `urlOpener` function that opens an in app browser for social sign in
4. Open the Android application
5. Open a social sign in using the `federatedSignIn` function
6. Note that the in app browser window is not dismissed automatically when authentication completes

### Code Snippet

```javascript
// used to open a Chrome Custom Tab to begin the federated sign in process
const response = await Browser.openAuth("social-login-url", "https://foo.bar/xxx", {
    animated: true,
    enableDefaultShare: false,
    enableUrlBarHiding: true,
    ephemeralWebSession: true,
    forceCloseOnRedirection: true,
    showInRecents: false,
    showTitle: false,
});

// this is the intent-filter in the AndroidManifest.xml file that handles Android App Links
<intent-filter android:autoVerify="true">
  <action android:name="android.intent.action.VIEW" />
  <category android:name="android.intent.category.DEFAULT" />
  <category android:name="android.intent.category.BROWSABLE" />
  <data android:scheme="https" android:host="foo.bar" android:path="/xxx" />
</intent-filter>
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by nadetastic** [comment]
Hi @markgaucher thank you for opening this issue. Can you clarify what version of `aws-amplify` you are currently using with this project?

**Comment by markgaucher** [comment]
My apologies for missing that.
```
@aws-amplify/auth@5.3.3
@aws-amplify/core@5.1.12
```

**Comment by nadetastic** [comment]
@markgaucher it should be possible to use android intents with `redirectSignIn` if you are initiating the call (ie `signInWithRedirect()` )from the app, however I haven't fully tested this. Essentially, as long as you provided the intent url into cognito as a valid redirect/signout url then it should successfully redirect the user back to the app after authenticating with Cognito. Have you had a chance to try this out?

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
