### ISSUE TITLE
V6 Cookie Storage not working as expected

### ISSUE THREAD

**Issue by nadetastic** [aws-amplify/amplify-js#12629]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

> Opening on behalf of CX

My name is José, and I am currently in the process of migrating from aws-amplify@5 to aws-amplify@6, the JavaScript version that I use in React.

Despite thoroughly reviewing the provided [documentation](https://docs.amplify.aws/javascript/tools/libraries/configure-categories/#pageMain) and making the necessary adjustments to align with version 6, it appears that the "cookieStorage" option is no longer functioning as expected.

Furthermore, I observed that employing the configuration object structure outlined in the [documentation](https://docs.amplify.aws/react/build-a-backend/auth/set-up-auth/#set-up-and-configure-amplify-auth) link attached above does not seamlessly integrate with my project. I have consulted an alternative documentation source tailored for React, but regrettably, the issue with the "cookieStorage" persists. This is due to the apparent absence of the "cookieStorage" option in that documentation
Upon attempting to execute the getCurrentUser() method from 'aws-amplify/auth', I encountered the following error message: "User needs to be authenticated to call this API." It's essential to note that I am not leveraging the Amplify CLI; instead, I am working with existing sources.

I appreciate your time and expertise in addressing this matter. Any guidance or support you can provide would be immensely valuable.

Thank you for your attention to this request.

### Expected behavior

Cookie Storage to work

### Reproduction steps

Attempt to setup cookie storage

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by josemsb92** [comment]
That worked perfectly for me, thank you very much.
Another question I have is, when using `signOut` from `aws-amplify/auth`, it doesn't delete the stored cookie called `CognitoIdentityServiceProvider.**********.userData`. Previously, this cookie used to be deleted using `Auth.signOut()`.

**Comment by nadetastic** [comment]
@josemsb92 v6 of the library should not be setting `CognitoIdentityServiceProvider.**********.userData` (i've also tested and confirmed) so that may be a left over key from v5. Can you try to clear your cookies and check again?

**Comment by nadetastic** [comment]
Ok great, glad to hear that his was resolved for you! Let me know if you have any other questions, otherwise i'll mark this as closed.

**Comment by josemsb92** [comment]
@nadetastic, I have deployed my React App, and something unusual has occurred. I have two Apps: the first one manages the login workflow, where I call aws-amplify/auth signIn, and the second one redirects to the first App to execute the login workflow and retrieve the authentication information that will be stored in the cookies to access the attributes of the logged-in user.

After migrating to version 6, I can only get the authentication information from the second App once. If I log out of `using aws-amplify/auth signOut`, I notice that the cookies are not cleared. Additionally, if I refresh the browser or redo the login workflow, every time `fetchUserAttributes from aws-amplify/auth` is called, I encounter the following error: NotAuthorizedException: "Access Token has been revoked".

I realized that if I clear the access token cookie, it works again one more time, but shortly after that, the same issue occurs. I also tried to perform a global signOut, but it has the same effect in this case.

In the previous version, after signing out, it used to clear cookies from both the first and second App. 

It seems like I miss something on the migration but I can't find out what.
I hope you can help me resolve this.

**Comment by josemsb92** [comment]
Just in case it helps someone in the future, I had an issue with `CookieStorage` where I needed to access Cognito cookies stored on one domain's website from another website within the same domain. The problem was that I wasn't passing the correct domain to the 'domain' parameter of this class, or as in the example above, it wouldn't work since no domain was provided.

It's crucial that subdomains share the same domain if you want to access cookies stored in both. Otherwise, methods like `signOut` might not work correctly.

So, following the example above, to share cookies between subdomains, it would be something like this:

```javascript
cognitoUserPoolsTokenProvider.setKeyValueStorage(new CookieStorage({ domain: 'myDomain'}));
```

**Comment by mlombar3** [comment]
> Just in case it helps someone in the future, I had an issue with `CookieStorage` where I needed to access Cognito cookies stored on one domain's website from another website within the same domain. The problem was that I wasn't passing the correct domain to the 'domain' parameter of this class, or as in the example above, it wouldn't work since no domain was provided.
> 
> It's crucial that subdomains share the same domain if you want to access cookies stored in both. Otherwise, methods like `signOut` might not work correctly.
> 
> So, following the example above, to share cookies between subdomains, it would be something like this:
> 
> ```js
> cognitoUserPoolsTokenProvider.setKeyValueStorage(new CookieStorage({ domain: 'myDomain'}));
> ```

i try to apply this example but when i try to log in in answer this error:
User needs to be authenticated to call this API.

**Comment by kevoj7** [comment]
This is extremely critical piece. I've been banging my head for a while on this one. I'm using nextjs with app router.


If not you won't be able to send ajax request to your api gateway:

    const handleAPICall = async () => {
        const url = 'example.com';

        try {
            const response = await fetch(url, {
                method: 'GET',
                credentials: 'include',
            });

            const data = await response.json();
            setApiResponse(data);
        } catch (error) {
            console.error('Error making API call:', error);
        }
    };



(Provider file)
'use client';
import {Amplify} from 'aws-amplify';
import {CookieStorage} from 'aws-amplify/utils';
import {cognitoUserPoolsTokenProvider} from 'aws-amplify/auth/cognito';
import config from '@/amplifyconfiguration.json';


Amplify.configure(config, {ssr: true});


cognitoUserPoolsTokenProvider.setKeyValueStorage(new CookieStorage({domain: 'example.com'}));

export default function ConfigureAmplifyClientSide() {
    return null;
}
