### ISSUE TITLE
why call AWSCognitoIdentityProviderService.GetUser after every login by hosted UI?

### ISSUE THREAD

**Issue by goldenbearkin** [aws-amplify/amplify-js#1262]
I use Cognito hosted UI, every time after the user hit the login page and redirect back to my app, I see a call against 'AWSCognitoIdentityProviderService.GetUser' and return some user attributes.

Then I try to limit the scope to disable  'aws.cognito.signin.user.admin', then it still calls against 'AWSCognitoIdentityProviderService.GetUser' and predictably return 400.

For both cases, I still able to log user in. But to enable and disable the 'aws.cognito.signin.user.admin' scope just wanted to show the call against 'AWSCognitoIdentityProviderService.GetUser' seems to be unnecessary.

So why call AWSCognitoIdentityProviderService.GetUser after every login by hosted UI?

**Comment by elorzafe** [comment]
@powerful23 what do you think?
