### ISSUE TITLE
v6 `useAuthenticator` does not return `user.signInUserSession` anymore

### ISSUE THREAD

**Issue by arnaud-deprez** [aws-amplify/amplify-js#12637]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

In v5, we could get the current user idToken decoded with:
```tsx
const { user } = useAuthenticator((context) => [context.user])
const idToken = signInUserSession.idToken.payload
```

In v6, we cannot anymore. How to proceed ?

### What's the expected behaviour?

Ideally we don't want to run another call to Cognito with `fetchAuthSession` but return the token from browser storage.

### Help us reproduce the bug!

Just try it in v6

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by nadetastic** [comment]
Hi @arnaud-deprez to get the `idToken` of the current user, you can utilize the [`fetchAuthSession`](https://docs.amplify.aws/react/build-a-backend/auth/manage-user-session/#retrieve-a-user-session) api.

```js

import { fetchAuthSession } from 'aws-amplify/auth';

async function fetchTodos() {
    try {
      const { tokens } = await fetchAuthSession()
      const idToken = tokens?.idToken;
    } catch (error) {
      console.log(error)
    }
}
```

Let me know if you have any questions.
