### ISSUE TITLE
V6 TypeScript strict mode error with API

### ISSUE THREAD

**Issue by Khumain** [aws-amplify/amplify-js#12630]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

amplify codegen
# Put output below this line

TS2339: Property 'graphql' does not exist on type 'typeof import("node_modules/@aws-amplify/api-graphql/dist/esm/index")'.

</details>

### Describe the bug

I am trying the new V6 of Amplify with Angular with strict TypeScript mode. I have created a dummy API with `amplify add api` with the _One-to-many relationship (e.g., “Blogs” with “Posts” and “Comments”)_ template. However, after creating the API, when I do `amplify codegen`, I get the following error multiple times across the TypeScript API.service.ts created:
`TS2339: Property 'graphql' does not exist on type 'typeof import("node_modules/@aws-amplify/api-graphql/dist/esm/index")'.`

### Expected behavior

No error in the API.service.ts in strict mode. The error happens with codes looking like the following:
`const response = (await API.graphql(graphqlOperation(statement, gqlAPIServiceArguments))) as any;`

### Reproduction steps

1. Create a blank Angular project
2. `amplify add api`
3. `amplify codegen`
4. see error in API.service.ts

### Code Snippet

```javascript
const response = (await API.graphql(graphqlOperation(statement, gqlAPIServiceArguments))) as any;
// graphql in API.graphql is shown in red
```

### Log output

<details>

```
TS2339: Property 'graphql' does not exist on type 'typeof import("C:/Users/afnan/WebstormProjects/doctra/node_modules/@aws-amplify/api-graphql/dist/esm/index")'.

```

</details>

**Comment by nadetastic** [comment]
Hi @Khumain, thank you for opening this issue. Since it looks like you trying to use V6 of `aws-amplify`, the error message you see is expected based on the code snippet you have shared:
```js
const response = (await API.graphql(graphqlOperation(statement, gqlAPIServiceArguments))) as any;
```
We no longer export the API class, but instead have a `generateClient()` export to setup a client to make the graphql calls. You can view an example of this in our [documentation](https://docs.amplify.aws/react/build-a-backend/graphqlapi/set-up-graphql-api/#add-your-first-record). Let me know if you have any questions.

**Comment by Khumain** [comment]
Hello Amplify Team! Thank you very much for your answer. I will use the new way of doing it with `amplify codegen add` and `typescript` as the option. I was using `angular`, hence the issues... Will it be compatible some day or you will no longer use the API.service.ts?

Thanks again!

**Comment by chrisbonifacio** [comment]
Hi @Khumain 👋 for an idea of how the API experience will change in the future, please check out our documentation for Gen 2 Amplify projects. The developer experience for interfacing with your AppSync APIs will include a autogenerated, type safe client.

https://docs.amplify.aws/gen2/build-a-backend/data/set-up-data/

**Comment by krissm** [comment]
This issue got me stuck for many hours before finding this post. Would most people who uses angular not assume that you should pick 'angular' not 'typescript'? Is there a way to add this to the documentation so others don't get stuck on this issue? Can I somehow suggest an update to the documentation?

There is also no documentation on how to add type to get type safety on the return value. After many attempts I finally figured it out; you have to add the type to: 

client = generateClient<Type>();
