### ISSUE TITLE
After migrating from v5 to v6, my custom graphql function no longer works with its lambda. 

### ISSUE THREAD

**Issue by zeth** [aws-amplify/amplify-js#12647]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

GraphQL API

### Amplify Categories

auth, function, api

### Environment information

<details>

```
# Put output below this line

System:
    OS: Linux 6.5 Ubuntu 23.10 23.10 (Mantic Minotaur)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 1008.48 MB / 7.48 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    pnpm: 8.6.9 - ~/.local/share/pnpm/pnpm
  npmPackages:
    @aws-amplify/ui-react: ^6.0.3 => 6.0.3 
    @aws-amplify/ui-react-internal:  undefined ()
    @aws-amplify/ui-react-storage: ^3.0.4 => 3.0.4 
    @babel/plugin-proposal-private-property-in-object: ^7.21.11 => 7.21.11 (7.21.0-placeholder-for-preset-env.2)
    @testing-library/jest-dom: ^5.17.0 => 5.17.0 
    @testing-library/react: ^13.4.0 => 13.4.0 
    @testing-library/user-event: ^13.5.0 => 13.5.0 
    @types/jest: ^27.5.2 => 27.5.2 
    @types/node: ^16.18.46 => 16.18.65 
    @types/react: ^18.2.21 => 18.2.39 
    @types/react-dom: ^18.2.7 => 18.2.17 
    aws-amplify: ^6.0.5 => 6.0.5 
    aws-amplify/adapter-core:  undefined ()
    aws-amplify/analytics:  undefined ()
    aws-amplify/analytics/kinesis:  undefined ()
    aws-amplify/analytics/kinesis-firehose:  undefined ()
    aws-amplify/analytics/personalize:  undefined ()
    aws-amplify/analytics/pinpoint:  undefined ()
    aws-amplify/api:  undefined ()
    aws-amplify/api/server:  undefined ()
    aws-amplify/auth:  undefined ()
    aws-amplify/auth/cognito:  undefined ()
    aws-amplify/auth/cognito/server:  undefined ()
    aws-amplify/auth/server:  undefined ()
    aws-amplify/datastore:  undefined ()
    aws-amplify/in-app-messaging:  undefined ()
    aws-amplify/in-app-messaging/pinpoint:  undefined ()
    aws-amplify/push-notifications:  undefined ()
    aws-amplify/push-notifications/pinpoint:  undefined ()
    aws-amplify/storage:  undefined ()
    aws-amplify/storage/s3:  undefined ()
    aws-amplify/storage/s3/server:  undefined ()
    aws-amplify/storage/server:  undefined ()
    aws-amplify/utils:  undefined ()
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    react-infinite-scroll-component: ^6.1.0 => 6.1.0 
    react-router-dom: ^6.15.0 => 6.20.0 
    react-scripts: 5.0.1 => 5.0.1 
    typescript: ^4.9.5 => 4.9.5 
    web-vitals: ^2.1.4 => 2.1.4 

```

</details>

### Describe the bug

Hello, I upgraded my site from v5 to v6. I followed the guide to change the API functions ( https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/#api-(graphql) ) The basic graphql generated queries still work, but I have one custom graphql query that connects to a (Python) lambda to update server side metadata that doesn't work with v6. In the browser network console, it looks like is sending the right argument (image_id) but in the lambda end, the argument is blank. I don't know what I am doing wrong. Help please.

### Expected behavior

I want the argument to get to my lambda function.

### Reproduction steps

Call the graphql API function in v6.

### Code Snippet

```javascript
// Put your code below this line.

// graphql/mutations.ts

export const updateProfileImage = /* GraphQL */ `
  mutation UpdateProfileImage($image_id: String) {
    updateProfileImage(image_id: $image_id)
  }
`;

// Component

    import { updateProfileImage } from '../graphql/mutations';

    async function updateAvailableImages() {
        const profileImageDetails = {
            image_id: image_id,
        }

        // v5 version:
        //const result = await API.graphql(graphqlOperation(updateProfileImage, profileImageDetails))

        // v6 version:
        const client = generateClient();
        const result = await client.graphql({
            query: updateProfileImage,
            variables: { input: profileImageDetails },
        });
  }
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

![Screenshot from 2023-11-29 01-42-22](https://github.com/aws-amplify/amplify-js/assets/945574/2701fd72-5540-490a-969b-2c2dfecaeceb)
![Screenshot from 2023-11-29 01-19-11](https://github.com/aws-amplify/amplify-js/assets/945574/915988f6-63d9-4de1-9114-afba29ca8100)
![Screenshot from 2023-11-29 01-17-31](https://github.com/aws-amplify/amplify-js/assets/945574/0876cd54-bf59-4b5e-82fb-66075bf72dce)
![Screenshot from 2023-11-29 01-17-02](https://github.com/aws-amplify/amplify-js/assets/945574/57cf3b67-0a73-4073-8aed-8695dbd1ff4c)
![Screenshot from 2023-11-29 01-46-32](https://github.com/aws-amplify/amplify-js/assets/945574/5bbe8289-d3b8-414c-9896-7c757bcd28b9)
![Screenshot from 2023-11-29 01-47-35](https://github.com/aws-amplify/amplify-js/assets/945574/d186ebfd-2fb9-45b4-ab50-81c03939cb10)

**Comment by zeth** [comment]
Someone on the amplify discord explained how to fix it.

`const result = await client.graphql({
            query: updateProfileImage,
            variables: profileImageDetails,
        });`

Thanks.

**Comment by cwomack** [comment]
@zeth, glad you were able to get an answer so quickly from our Discord server! Sorry we didn't get you a reply sooner, but let us know if there are more issues.
