### ISSUE TITLE
can I use this library in node to check the validity of the token

### ISSUE THREAD

**Issue by dagda1** [aws-amplify/amplify-js#1265]
Can I use amplify-js to check the token's validity.

I've been looking at [cognito-express](https://github.com/ghdna/cognito-express) but could I use this library instead?

**Comment by elorzafe** [comment]
@dagda1 Amazon Cognito Federated Identities validates the token when you are invoking `Auth.federatedSignIn` on Amplify, then it returns credentials if token is valid or not.

**Comment by dagda1** [comment]
thanks, but i am not using federated identities.

**Comment by powerful23** [comment]
@dagda1 what do you mean by checking the token's validity?

**Comment by dagda1** [comment]
@powerful23 yes, to decode the token and check the validity

**Comment by powerful23** [comment]
Can you try 
```js
Auth.currentSession(session => {
    const payload = session.getIdToken().decodePayload();
    console.log('decode jwt token from cognito', payload);
})
```

**Comment by powerful23** [comment]
Closing the issue. Feel free to reopen if you still have this issue.
