### ISSUE TITLE
Array of strings is returned as object

### ISSUE THREAD

**Issue by erickriva** [aws-amplify/amplify-js#12663]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

GraphQL API

### Environment information

<details>

```
  System:
    OS: Windows 11 10.0.23590
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics
    Memory: 13.21 GB / 23.91 GB
  Binaries:
    Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.11.0 - ~\AppData\Local\pnpm\pnpm.EXE
    bun: Not Found
    Watchman: Not Found
  npmPackages:
    @aws-amplify/backend: 0.5.5
    @aws-amplify/backend-cli: 0.9.1
    aws-amplify: 6.0.5
    aws-cdk: Not Found
    aws-cdk-lib: 2.111.0
    typescript: 5.3.2

```

</details>

### Describe the bug

When requesting data with `amplifyClient.models.ModelName.list()`, a model with a prop declared as 'array of strings' returns an object instead of the string array datatype I have declared.

### Expected behavior

I expect to receive an array of string values, as I have declared in my schema.

### Reproduction steps

- Declare a model with following code:

```
import { a } from "@aws-amplify/backend";

const schema = a.schema({
  CommunityPost: a.model({
    id: a.id().required(),
    pictures: a.string().array()
  })
})
```

- To return data, use `list` function with `pictures` included in `selectionSet`:
```
amplifyClient.models.CommunityPost.list({
  selectionSet: ["id", "createdAt", "pictures"],
});
```

- Check `pictures` value. 
Typescript should works and show `pictures` as `Nullable<string>[] | null | undefined`, but received data will have `pictures` as an object, like ` { "0": "value", "1": "value" } `

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @erickriva 👋 thanks for raising this issue.

I was able to reproduce the described behavior and have marked this issue as a bug for the team to investigate further.

<img width="351" alt="CleanShot 2023-12-04 at 14 08 45@2x" src="https://github.com/aws-amplify/amplify-js/assets/16952986/0206008b-4dc4-402c-9606-6d3b65f0c89d">

Reproduction App: https://github.com/chrisbonifacio/gen2-repro-12663

**Comment by cwomack** [comment]
@erickriva with [v6.0.7 now live](https://www.npmjs.com/package/aws-amplify/v/6.0.7), can you upgrade and verify that this issue is resolved?

**Comment by erickriva** [comment]
@cwomack Now it's working fine! Thank you all!
