### ISSUE TITLE
Third party SAML with azure on v6

### ISSUE THREAD

**Issue by AdamKuemmel** [aws-amplify/amplify-js#12664]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

When upgrading to v6, im having trouble getting a custom provider to work, from what i can see the syntax is now signInWithRedirect({ provider: "customProvider"}) im not sure if im heading down the right avenue here. Has anyone done this with v6 yet?

### Expected behavior

expected to redirect to custom Federated Auth provider

### Reproduction steps

federate login with amplify

### Code Snippet

```javascript
// Put your code below this line.

```
        <Button
          data-testid="login-button"
          type="submit"
          fullWidth
          variant="contained"
          sx={{ mt: 3, mb: 2 }}
          onClick={() => signInWithRedirect({ provider: "muscoAD" })}
        >
          Sign In with Microsoft
        </Button>

### Log output

<details>

```
// Put your logs below this line
this is the error:
OAuthNotConfigureException: oauth param not configured.

```

</details>

**Comment by israx** [comment]
Hello @AdamKuemmel. You would need to configure your identity provider via the Amazon Cognito UserPool [console](https://aws.amazon.com/cognito/). If that is done then you only need to call `signInWithRedirect` with your custom provider name. 

Note that the config above is passing a `string` as a `redirectSignIn/Out` . V6 is supporting multiple redirects and you can define them inside an `array` e.g `redirectSignIn:[process.env.REACT_APP_redirectSignInURL]`

**Comment by nadetastic** [comment]
@AdamKuemmel addition to the comment form @israx above, I've seen this error happen in two scenarios:
- You aren't running `Amplify.configure()` at the entry point of you app
- You may need to delete `node-modules/` and re-install you dependencies

**Comment by nadetastic** [comment]
Hi @AdamKuemmel let me know if you are still needing assistance, otherwise will close out this issue. Thanks!

**Comment by pieter-vandenburg** [comment]
@AdamKuemmel , your json attribute `userPoolWebClientId` should be updated to `userPoolClientId`
