### ISSUE TITLE
Server-side Auth login, in particular for Remix, but preferably framework agnostic

### ISSUE THREAD

**Issue by MattyBalaam** [aws-amplify/amplify-js#12660]
### Is this related to a new or existing framework?

React - and meta-frameworks like Remix which work server-side, but I also see no reason why this could not be more wide and web-standards friendly than that.

### Is this related to a new or existing API?

Authentication

### Is this related to another service?

https://github.com/remix-run/remix

### Describe the feature you'd like to request

The ability to login a user server side in Remix in an [action](https://remix.run/docs/en/main/route/action) - where it is possible to log a users IP and user agent via request headers to store in Cognito would be very appreciated.

### Describe the solution you'd like

Purely server-side javascript to call the Auth functions, with logging of users details. Not a hybrid solution where there is some client-side code too.

### Describe alternatives you've considered

I spent a while attempting to get Amplify Auth 5 to work server side - and while it is possible (with a couple of hacks) it only logs the node user agent and IP address of server.

### Additional context

There are some previously opened PRs for other frameworks with similar requests:

- https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+is%3Aopen+SSR
- https://github.com/aws-amplify/amplify-js/issues/11598

Here are some other related issues:

- https://github.com/aws-amplify/amplify-js/issues/9780
- https://github.com/aws-amplify/amplify-js/issues/9362

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by nadetastic** [comment]
Hi @MattyBalaam, thank you for opening this issue.

With Amplify JS v6 we provide an adapter for only Next.js, although the underlying generic adapters can be used with other frameworks. We will be provide instructions of using the generic adapters with other frameworks soon, but for now II'll mark this as a feature request and follow up once the instructions are available.

**Comment by nadetastic** [comment]
Hi @MattyBalaam following up here - we have published documentation on how to use the generic adapters which can be viewed here - [docs.amplify.aws/react/build-a-backend/server-side-rendering](https://docs.amplify.aws/react/build-a-backend/server-side-rendering/)

Let me know if you have any questions.

**Comment by MattyBalaam** [comment]
Thanks for this @nadetastic . I’ll investigate this.

One question I have is that you mention “You will need to call Amplify.configure() on the client side of your app ”

I am assuming this means that any initial login requires that all the functions to setup and signin are run in a browser context - and they use internal hidden methods to get the users device and IP info?

**Comment by kldeb** [comment]
@MattyBalaam did you make any progress? I was able to sign in using amplify auth client side. I had to set ssr to true on amplify configure to get the tokens in the cookie to send to the server. The next step in the plan is to parse the cookie server-side using an aws jwt token verify package.

**Comment by MattyBalaam** [comment]
@kldeb our requirement is to log in 100% server side so I did not look into loggin in first client-side. For our use case you *can* hack the current library to log in server-side but it is not designed to do this so it could break at any time, and you will not be able to log the clients device and IP address if that is important to you.

I exchanged a couple of messages from @renebrandel on Twitter in December who said they are looking into a server-side solution, but I don’t know if that has progressed internally at all.

In the meantime we have decided to write our own service at my company to accomplish this so I have not been chasing.

**Comment by nadetastic** [comment]
@MattyBalaam following up here - apologies for the delay. You are correct that the auth session needs to be initiated on the client side first and is not supported server side yet. We are tracking that feature request here - https://github.com/aws-amplify/amplify-js/issues/11598

@kldeb could you elaborate a bit more on your use case?

**Comment by nadetastic** [comment]
@kldeb thanks for the context, you should still be able to handle the user login on the client side and perform the supported api's (such as fetchAuthSession) on the server side. Since we are tracking the feature request to support authentication on the server side on issue #11598, I'll go ahead and close this and consolidate it into the other issue. Feel free to subscribe to it and provide any additional context on it.

**Comment by misha-erm** [comment]
hello @nadetastic 

you mentioned that there should be documentation for generic adapters but as I can see the link [docs.amplify.aws/react/build-a-backend/server-side-rendering](https://docs.amplify.aws/react/build-a-backend/server-side-rendering/) now contains only info about next.js. Was it removed? 

thank you

**Comment by MattyBalaam** [comment]
> hello @nadetastic
> 
> you mentioned that there should be documentation for generic adapters but as I can see the link [docs.amplify.aws/react/build-a-backend/server-side-rendering](https://docs.amplify.aws/react/build-a-backend/server-side-rendering/) now contains only info about next.js. Was it removed?
> 
> thank you

I have a feeling when I did this I just had to reverse-engineer the next solution to create something that worked in Remix. We’re moving our apps away from Cognito now because of the lack of support.

**Comment by misha-erm** [comment]
yeah, I was about to do the same. But hoped maybe there is a better way to do it now

here is our use-case: we had a SPA and moved to remix to be able to render couple of pages on server. We are okay with keeping whole auth flow client-side as it was before. What we need most is:
- check whether user has valid session so we can return server-rendered Landing page instead of app's homepage
- perform AppSync requests on behalf of user

**Comment by erinleigh90** [comment]
@misha-erm We still have documentation on using the generic adapter that you should be able to use [here](https://docs.amplify.aws/gen1/javascript/build-a-backend/server-side-rendering/). It looks like this page was not ported over to Gen2 docs, which now defaults to NextJS. There is also a [guide for using SSR with Nuxt](https://docs.amplify.aws/javascript/build-a-backend/server-side-rendering/nuxt/) using the generic adapter that might be of use as a reference in both the Gen1 and Gen2 docs.

**Comment by misha-erm** [comment]
awesome, thank you 🙇🏻

**Comment by th-m** [comment]
Would love to see support for Remix.

**Comment by cjoecker** [comment]
This is how Cognito can be used with Amplify v6 (Gen 2) and Remix / React Router v7:

Create a `auth.server.ts` file in your app folder with this:
```ts
import {
	createAWSCredentialsAndIdentityIdProvider,
	createKeyValueStorageFromCookieStorageAdapter,
	createUserPoolsTokenProvider, runWithAmplifyServerContext
} from "aws-amplify/adapter-core";
import {authConfig} from "../amplify.config";
import {getCurrentUser} from "aws-amplify/auth/server";

export const ensureEncodedForJSCookie = (name: string): string => {
	return encodeURIComponent(name).replaceAll(
		/%(2[346B]|5E|60|7C)/g,
		decodeURIComponent,
	);
};

export const getAmplifyUser = async (request: Request) => {
	const cookies = request.headers.get("cookie") || "";

	// Create the key-value storage from Remix's cookie API
	const keyValueStorage = createKeyValueStorageFromCookieStorageAdapter({
		get(name) {
			const encodedName = ensureEncodedForJSCookie(name);
			const cookieRegex = new RegExp(`(^|;)\\s*${encodedName}=([^;]+)`);
			const match = cookies.match(cookieRegex);
			const cookie = match ? {name, value: match[2]} : undefined;

			if (cookie && name.endsWith('.signInDetails')) {
				cookie.value = decodeURIComponent(cookie.value);
			}

			return cookie;
		},
		getAll() {
			return cookies.split("; ").map((cookie) => {
				const [name, value] = cookie.split("=");
				return {name, value};
			});
		},
		set(name, value) {
			// Not needed on the server unless setting cookies
		},
		delete(name) {
			// Not needed on the server unless deleting cookies
		},
	});

	// Create the tokenProvider
	const tokenProvider = createUserPoolsTokenProvider(
		authConfig,
		keyValueStorage,
	);

	// Create the credentialsProvider
	const credentialsProvider = createAWSCredentialsAndIdentityIdProvider(
		authConfig,
		keyValueStorage,
	);

	// Run Amplify in a secure server context
	const authSession = await runWithAmplifyServerContext(
		{Auth: authConfig},
		{Auth: {tokenProvider, credentialsProvider}, ssr: true},
		async (contextSpec) => {
			try {
				return await getCurrentUser(contextSpec);
			} catch (error) {
				console.error("Error fetching authentication session:", error);
				return null;
			}
		}
	);


	// Extract the user information from the auth session
	const user = authSession?.username;

	return user;
};
```

Add the Amplify and Cognito config to `amplify.config.ts` in your root folder
```ts
const cognitoConfig = {
	authenticationFlowType: "USER_PASSWORD_AUTH",
	region: "your region",
	userPoolId: "your user pool id",
	identityPoolId: "your identity pool id",
	userPoolClientId: "your web client id",
};
export const authConfig = {
	Cognito: cognitoConfig,
};
export const amplifyConfig = {
	Auth: authConfig,
};

```

Add this to you `root.ts` file
```ts
Amplify.configure(amplifyConfig, {ssr: true});
```

Now, you will be able to use cognito in the client and server side.

To sign in, you should do it in a client route like this:
```ts
// app/routes/login.ts

import { signIn } from "@aws-amplify/auth";
import { useState } from "react";
import { useNavigate } from "react-router";

export default function Login() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const navigate = useNavigate();

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      await signIn({ username, password });
      navigate("/auth");
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <div>
      <form onSubmit={handleLogin}>
        <div>
          <label htmlFor="username">Username</label>
          <input
            id="username"
            type="text"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            required
          />
        </div>
        <div>
          <label htmlFor="password">Password</label>
          <input
            id="password"
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
          />
        </div>
        <button type="submit">Sign In</button>
      </form>
    </div>
  );
}
```

Then, two authenticate the user in the server, you can use the `getAmplifyUser` above like this:
```ts
export async function loader({request}: LoaderFunctionArgs) {
	const user = await getAmplifyUser(request);
	if(!user) {
		return {
			status: 403,
			error: "User not authenticated"
		};
	}
	return {
		user,
	};
}
```

**Comment by cjoecker** [comment]
> [@cjoecker](https://github.com/cjoecker) we tried something similar, however note that this means your users IP address and browser will not be logged correctly working around the issue like this - instead you just get the IP of your server and the runtime you are using, e.g. Node.
> 
> Depending on your security requirements this could be a no-go.

@MattyBalaam thanks for the hint! Have you created an extra issue for that or clarify it with the AWS customer support?

**Comment by MattyBalaam** [comment]
@cjoecker this is is the issue for that.

**Comment by HuiSF** [comment]
Hi @cjoecker thanks for suggesting the solution for Remix using the generic SSR adapter. 

Hi @MattyBalaam thanks for posting the concerns about the IP address of end users in the SSR use cases. Could you clarify, where do you need to log the IP addresses of end users, from AWS service resources? 

If a service calls is originated from the server, for SSR processes, yes, only the server's IP address can be detected currently.
