### ISSUE TITLE
why Auth is not supporting "friendlyDeviceName" while verifyTotpToken ?

### ISSUE THREAD

**Issue by HanojHanu** [aws-amplify/amplify-js#12673]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

# ..\node_modules\@aws-amplify\auth\lib-esm\Auth.d.ts
``` js
/**
 * verify TOTP setup
 * @param {CognitoUser} user - the current user
 * @param {string} challengeAnswer - challenge answer
 * @return - A promise resolves is success
 */
verifyTotpToken(user: CognitoUser | any, challengeAnswer: string): Promise<CognitoUserSession>;
```

# But, cognito offering to provide friendlyDeviceName, right ?
# ...\node_modules\amazon-cognito-identity-js\index.d.ts
``` js
public verifySoftwareToken(
	totpCode: string,
	friendlyDeviceName: string,
	callbacks: {
		onSuccess: (session: CognitoUserSession) => void;
		onFailure: (err: Error) => void;
	}
): void;
```

### Describe the bug

# Unable to add friendlyDeviceName while verifying TOTP token using Amplify Auth.

### Expected behavior

``` jsx
verifyTotpToken(user: CognitoUser | any, challengeAnswer: string, friendlyDeviceName: string)
```

### Reproduction steps

"aws-amplify": "^5.3.10",

### Code Snippet

...

### Log output

...

### aws-exports.js

...

### Manual configuration

...

### Additional configuration

...

### Additional information and screenshots

....

**Comment by Meags27** [comment]
I had the exact issue, so I went into the source code and called the method Amplify calls itself which is verifyTOTPSetup() and pass in a friendly name, but would prefer not to have to do that. 

  ```
import {getCurrentUser, setUpTOTP, verifyTOTPSetup, VerifyTOTPSetupInput} from 'aws-amplify/auth';

const verifyTotpSetupInput : VerifyTOTPSetupInput ={
                code: mfaCode,
                options: {
                    serviceOptions: {
                        friendlyDeviceName: "authenticator app"
                    }                       
                } 
            }
            await verifyTOTPSetup(verifyTotpSetupInput)
```

**Comment by nadetastic** [comment]
Hi @HanojHanu,

Thank you for opening this issue. Although `friendlyDeviceName` was not supported with previous versions of `aws-amplify` you are able to use it with the latest major version `6.x.x`.

You can make use of with the `verifyTOTPSetup()` method. More information here: https://docs.amplify.aws/react/build-a-backend/auth/auth-migration-guide/#authverifytotptoken

cc @Meags27

**Comment by HanojHanu** [comment]
But, plans for support in `5.x.x` version ?

**Comment by nadetastic** [comment]
@HanojHanu with respect to v5, we don't plan to make any updates beyond major bug fixes or security concerns. We recommend migrating to v6 as soon as you can.

**Comment by HanojHanu** [comment]
https://github.com/aws-amplify/amplify-js/issues/12780

**Comment by sohibegit** [comment]
> Hi @HanojHanu,
> 
> Thank you for opening this issue. Although `friendlyDeviceName` was not supported with previous versions of `aws-amplify` you are able to use it with the latest major version `6.x.x`.
> 
> You can make use of with the `verifyTOTPSetup()` method. More information here: https://docs.amplify.aws/react/build-a-backend/auth/auth-migration-guide/#authverifytotptoken
> 
> cc @Meags27

We are using version 6.0.20. Although friendlyDeviceName is available in the SDK, it seems to be ignored; setting it to any value does not affect the output of fetchDevices(), as the results do not reflect our settings.

**Comment by beikeni** [comment]
I'm having the same problem as @sohibegit
