### ISSUE TITLE
Unexpected token axios utils.js

### ISSUE THREAD

**Issue by xxjt123xx** [aws-amplify/amplify-js#12689]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Not applicable

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line
[vite-plugin-pwa:build] Unexpected token (715:2) in web/node_modules/@aws-amplify/api-rest/node_modules/axios/lib/utils.js
file: web/node_modules/@aws-amplify/api-rest/node_modules/axios/lib/utils.js:715:2
713:   toFiniteNumber,
714:   findKey,
715:   {}: _global,
       ^
716:   isContextDefined,
717:   ALPHABET,
error during build:
SyntaxError: Unexpected token (715:2) in web/node_modules/@aws-amplify/api-rest/node_modules/axios/lib/utils.js
    at pp$4.raise (file://web/node_modules/rollup/dist/es/shared/node-entry.js:21621:13)
    at pp$9.unexpected (file://web/node_modules/rollup/dist/es/shared/node-entry.js:18829:8)

```

</details>

### Describe the bug

on build it is throwing this build error and i am not even 

### Expected behavior

build using ^5.3.13

### Reproduction steps

Build using aws-amplify js ^5.3.13

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello @xxjt123xx, 👋.  If you've recently updated to the latest version of Amplify, can you see if deleting your `node_modules` folder as well as your `package-lock.json`, then reinstalling dependencies with `npm i` resolves the issue? If not, feel free to reply back with your full package.json and we can dig into this further! Thanks.

**Comment by xxjt123xx** [comment]
I did that and it did not resolve it

**Comment by xxjt123xx** [comment]
> Reference

I did that and it didn't work

**Comment by cwomack** [comment]
@xxjt123xx, it looks like this might be needing an update to the `vite.config.ts` file to have `_global: ({})` defined.  Can you try importing `defineConfig` and defining the `_global` like below to see if it helps? 

```
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [react()],
    server: {
        host: true,
        strictPort: true,
        port: 5173
    },
    resolve: {
        alias: {
            './runtimeConfig': './runtimeConfig.browser'
        }
    },
    define: {
        _global: ({})
    }
})

```

If that doesn't, can you share your full `package.json` and `vite.config.ts`?

**Comment by xxjt123xx** [comment]
I had the following that I guess was added when the app was generated and once removed based on your hint it started working. thanks for the help on this.

```
  define: {
    global: {},
  },
```

**Comment by stephenykk** [comment]
> I had the following that I guess was added when the app was generated and once removed based on your hint it started working. thanks for the help on this.
> 
> ```
>   define: {
>     global: {},
>   },
> ```

very helpful, thanks a lot~
