### ISSUE TITLE
Cannot get existing config with Amplify.getConfig in Angular setup

### ISSUE THREAD

**Issue by ddotx** [aws-amplify/amplify-js#12685]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

Not applicable

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 7600 6-Core Processor
    Memory: 7.99 GB / 15.19 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.18.0/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
  npmGlobalPackages:
    @angular-devkit/schematics-cli: 17.0.5
    @angular/cli: 16.2.4
    @aws-amplify/cli: 12.5.1
    corepack: 0.19.0
    http-server: 14.1.1
    ng-schematics: 0.0.0
    npm: 9.8.1
    yarn: 1.22.19

```

</details>

### Describe the bug

When attempting to use the existing API  from another project as outlined in [this link](https://docs.amplify.aws/angular/build-a-backend/restapi/existing-resources/), I encountered an issue with the provided example code. The Angular app fails to work as expected because it is unable to retrieve the existing configuration when the application has started.

```javascript
const existingConfig = Amplify.getConfig();
```

### Expected behavior

```javascript
{
    "API": {
        "GraphQL": { ... },
        "REST": { ... }
    },
    "Auth": { ... }
}
```

### Reproduction steps

After the initial Angular and Amplify setup has been completed
1. add amplify configuration in `main.ts`
```javascript
import { Amplify } from 'aws-amplify';
import amplifyconfig from './amplifyconfiguration.json';
Amplify.configure(amplifyconfig);
```
2. add existing api from another Amplify project
```javascript
const existingConfig = Amplify.getConfig();
Amplify.configure({
  ...existingConfig,
  API: {
    ...existingConfig.API,
    REST: {
      ...existingConfig.API?.REST,
      '[API NAME]': {
        endpoint: '[API GATEWAY ENDPOINT]',
        region: '[REGION]'
      }
    }
  }
});
```
3. run with `ng serve`

### Code Snippet

```javascript
// Put your code below this line.
import { Amplify } from 'aws-amplify';
import amplifyconfig from './amplifyconfiguration.json';


const existingConfig = Amplify.getConfig();

Amplify.configure({
  ...existingConfig,
  API: {
    ...existingConfig.API,
    REST: {
      ...existingConfig.API?.REST,
      "gbzApiOps": {
        endpoint: "https://xxx.execute-api.ap-southeast-1.amazonaws.com/beta",
        region: "ap-southeast-1"
      }
    }
  }
})

Amplify.configure(amplifyconfig);
```

### Log output

<details>

```
// Put your logs below this line
ERROR Error: Uncaught (in promise): InvalidApiName: API name is invalid.
InvalidApiName: API name is invalid.

```

</details>

**Comment by cwomack** [comment]
Hello, @ddotx 👋.  Appreciate the code snippets and think I might see what's happening here.  It looks like you're making that second call of `Amplify.configure(amplifyconfig);` at the bottom of your code, and that's essentially overriding the initial configuration.  Can you see if moving that last line of code in your example to essentially the 3rd line (approximately) like the following resolves the issue?

```
import { Amplify } from 'aws-amplify';
import amplifyconfig from './amplifyconfiguration.json';
Amplify.configure(amplifyconfig);

const existingConfig = Amplify.getConfig();

Amplify.configure({
  ...existingConfig,
  API: {
    ...existingConfig.API,
    REST: {
      ...existingConfig.API?.REST,
      "gbzApiOps": {
        endpoint: "https://xxx.execute-api.ap-southeast-1.amazonaws.com/beta",
        region: "ap-southeast-1"
      }
    }
  }
})
```

If this doesn't work, then I may have more questions as to the scope, components, etc... but lets try this first!

**Comment by nadetastic** [comment]
Related to https://github.com/aws-amplify/amplify-js/issues/12696

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
