### ISSUE TITLE
Migrate v5 to v6 - Upgrading Issues

### ISSUE THREAD

**Issue by HanojHanu** [aws-amplify/amplify-js#12697]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

![image](https://github.com/aws-amplify/amplify-js/assets/53425981/f05da70f-92c2-4f64-849b-d249205f5d70)
```
npm install @aws-amplify/ui-react aws-amplify
```
`@aws-amplify/ui-react : 6.0.5` latest
`aws-amplify : 6.0.6` Latest

### Expected behavior

not able migrate v5 to v6

### Reproduction steps

```
npm install @aws-amplify/ui-react aws-amplify
```
`@aws-amplify/ui-react : 6.0.5` latest
`aws-amplify : 6.0.6` Latest

that, start run

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by nadetastic** [comment]
Hi @HanojHanu thank you for opening this issue.

Could you please try and delete your `/node_modules` folder and reinstall your dependencies again?

**Comment by HanojHanu** [comment]
@nadetastic 

Yeah, Before reaching out you itself. 

I tried deleting `node_module` + `package-lock.json` still not working after this even.

also tried with clean cache and npm cache ... all options even not worked..

**Comment by nadetastic** [comment]
@HanojHanu can you share your `package.json` or a sample app so I can try and reproduce this issue? Unfortunately I'm not able to on my own.

**Comment by HanojHanu** [comment]
Perhaps, there's a conflict with other peerDependencies within the internal package, as it still references "@aws-amplify/ui-react" at version 5.1.1, even though the main project version is up-to-date. I suspect that the issue is arising from this inconsistency.

**Comment by HanojHanu** [comment]
Hey.. what about Jest test case ?

**Comment by HanojHanu** [comment]
``` jsx
import * as Auth from "aws-amplify/auth";

// ...

it("test-error login", async () => {
    Auth.signIn = jest.fn().mockRejectedValue(errorSignIn);
    const { getByText, getByRole, getAllByRole } = render(<Login />);
}
//...
```

Error
![image](https://github.com/aws-amplify/amplify-js/assets/53425981/54e72a9c-c2f2-4417-83b2-8ca46977b860)

**Comment by HanojHanu** [comment]
other error - 
![image](https://github.com/aws-amplify/amplify-js/assets/53425981/3a09b324-e961-47d5-b10b-43e47b1f0e00)
