### ISSUE TITLE
Incorrect filepath when Importing AWSIoTProvider

### ISSUE THREAD

**Issue by jameshamann** [aws-amplify/amplify-js#1270]
Do you want to request a feature or report a bug?

**Bug**

What is the current behaviour?

The app fails to load the AWSIoTProvider with error: Module not found: Can't resolve 'aws-amplify/lib/PubSub/Providers'. 

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

Following the Documentation, importing the AWSIoTProvider Component like so: 

`import { AWSIoTProvider } from 'aws-amplify/lib/PubSub/Providers';`

Causes the above Error.

What is the expected behavior?

The app should correctly load the component. 

**Suggested Fix**

To fix the issue, amend the documentation to the correct file path below:

`import { AWSIoTProvider } from '@aws-amplify/pubsub/lib/Providers';`

I've opened a pull request at [here](https://github.com/aws-amplify/amplify-js/pull/1271).

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

1.0.0

**Comment by elorzafe** [comment]
Thanks @jameshamann, @mbahar can you review the PR?

**Comment by Jun711** [comment]
@jameshamann 
What js framework r u using? 

`import { AWSIoTProvider } from 'aws-amplify/lib/PubSub/Providers';` works for me in Angular

**Comment by jameshamann** [comment]
@Jun711 I'm using React. 

I think you're right because I did double check with an older version to see if it worked, it's just an issue with renaming the folder names in the path.

I've opened a PR to update the website but it can be fixed using the suggestion above if you ever do run into the issue.

**Comment by drewdecarme** [comment]
Amplify Package: `"aws-amplify": "^1.0.6"`

I just had this same problem. They consolidated their imports. Since AWSIoTProvider was under the PubSub directory originally, I checked their module export file and saw that the PubSub was namespaced to `@aws-amplify/pubsub`

So in order to get it working, use

```js
import { AWSIoTProvider } from "@aws-amplify/pubsub";
```

For reference, here are all of their new import namespaces
```js
var analytics_1 = require("@aws-amplify/analytics");
exports.Analytics = analytics_1.default;
exports.AnalyticsClass = analytics_1.AnalyticsClass;
exports.AWSPinpointProvider = analytics_1.AWSPinpointProvider;
exports.AWSKinesisProvider = analytics_1.AWSKinesisProvider;
var auth_1 = require("@aws-amplify/auth");
exports.Auth = auth_1.default;
exports.AuthClass = auth_1.AuthClass;
var storage_1 = require("@aws-amplify/storage");
exports.Storage = storage_1.default;
exports.StorageClass = storage_1.StorageClass;
var api_1 = require("@aws-amplify/api");
exports.API = api_1.default;
exports.APIClass = api_1.APIClass;
exports.graphqlOperation = api_1.graphqlOperation;
var pubsub_1 = require("@aws-amplify/pubsub");
exports.PubSub = pubsub_1.default;
exports.PubSubClass = pubsub_1.PubSubClass;
var cache_1 = require("@aws-amplify/cache");
exports.Cache = cache_1.default;
var interactions_1 = require("@aws-amplify/interactions");
exports.Interactions = interactions_1.default;
exports.InteractionsClass = interactions_1.InteractionsClass;
var core_1 = require("@aws-amplify/core");
```

**Comment by jordanranz** [comment]
This seems to have been fixed in the [docs](https://aws-amplify.github.io/docs/js/pubsub#aws-iot). Going to close this. Please reopen if there are any related questions or concerns.
