### ISSUE TITLE
Cache createInstance expects all options to be specified

### ISSUE THREAD

**Issue by dreamorosi** [aws-amplify/amplify-js#12705]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Cache

### Amplify Categories

Not applicable

### Environment information

<details>

```
System:
    OS: macOS 13.6.2
    CPU: (12) arm64 Apple M2 Pro
    Memory: 58.95 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/Library/Caches/fnm_multishells/74754_1702529254682/bin/node
    npm: 10.1.0 - ~/Library/Caches/fnm_multishells/74754_1702529254682/bin/npm
  Browsers:
    Chrome: 120.0.6099.71
    Safari: 17.2
  npmPackages:
    @types/node: ^20.5.9 => 20.8.9 (16.9.1)
    @typescript-eslint/eslint-plugin: ^6.4.0 => 6.9.1 
    @typescript-eslint/parser: ^6.4.0 => 6.9.1 
    eslint: ^8.47.0 => 8.52.0 
    eslint-config-prettier: ^9.0.0 => 9.0.0 
    eslint-plugin-prettier: ^5.0.0 => 5.0.1 
    ts-node: ^10.9.1 => 10.9.1 
  npmGlobalPackages:
    corepack: 0.20.0
    npm: 10.1.0


```

</details>

### Describe the bug

When creating a new cache instance (`Cache.createInstance`) I would like to override some of the settings/options while leaving all others as default.

At the moment, the `createInstance` method expects all options to be passed. This forces me to have to set all options even though I want to override only some of them.

### Expected behavior

The `createInstance` method should allow me to specify only one or few options and consider all others as optional. For the ones that are not specified, default values should be used instead.

### Reproduction steps

1. install latest `aws-amplify` package
2. import `import { Cache } from 'aws-amplify/utils';`
3. create a new cache instance

### Code Snippet

```javascript
// Put your code below this line.
import { Cache } from 'aws-amplify/utils';

const cache = Cache.createInstance({
  storage: window.localStorage,
  keyPrefix: 'aws-lambda-powertools-workshop-',
  // other properties should be optional & use default values
});
```

### Log output

<details>

```
// Put your logs below this line
Argument of type '{ storage: Storage; keyPrefix: string; }' is not assignable to parameter of type 'CacheConfig'.
  Type '{ storage: Storage; keyPrefix: string; }' is missing the following properties from type 'CacheConfig': capacityInBytes, itemMaxSize, defaultTTL, warningThreshold, defaultPriority

```

</details>

**Comment by nadetastic** [comment]
Hi @dreamorosi thank you for opening this issue. If you would like to create an new instance while keep default values for some of the options, you should be able to pass the default config into the createInstance method like this:

```js
// Get default config 
const defaultConfig = Cache.configure();

// Pass default config and overwrite only the options you want, ex: keyPrefix
const customConfig = Cache.createInstance({
    ...defaultConfig,
    keyPrefix: "my-custom-instance-prefix-",
});
```

Could you try this out and let me know if this works for you?

**Comment by dreamorosi** [comment]
I can confirm that the suggested workaround, albeit not ergonomic, works.

It'd be great if this could be documented in the docs under the section dedicated to [`createInstance()` here](https://docs.amplify.aws/javascript/build-a-backend/utilities/cache/#createinstance).

If not, feel free to close the issue. Thanks!
