### ISSUE TITLE
Issues with Documentation on Analytics record event

### ISSUE THREAD

**Issue by pascalito007** [aws-amplify/amplify-js#12723]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Analytics

### Amplify Categories

analytics

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

The migration from v5 to v6 documentation is saying in order to record event, we should do below:

![Capture d’écran 2023-12-19 à 07 00 21](https://github.com/aws-amplify/amplify-js/assets/4120406/bdb30b5c-2afe-40d4-a6a2-4a3b9b8a3b1c)

This is I guess wrong because the Analytics session of the documentation is saying something else

![Capture d’écran 2023-12-19 à 07 10 25](https://github.com/aws-amplify/amplify-js/assets/4120406/de76bb97-4ff6-4634-ac5c-f8bc70584d34)

### Expected behavior

We need to know what is the real way to record event because currently events are not sent to pinpoint when using both methods.

### Reproduction steps

N/A

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
@pascalito007, thank you for opening this issue and calling out the need for a docs fix! That `event` field should not be there and we will get a PR out to update the docs ASAP.  The record API should look like the following in v6: 

```
import { record } from 'aws-amplify/analytics';

record({
  name: 'albumVisit',
  attributes: { genre: '', artist: '' },
});
```

**Comment by cwomack** [comment]
@pascalito007.  With the [docs issue](https://github.com/aws-amplify/docs/issues/6696) created and the [PR with fix ](https://github.com/aws-amplify/docs/pull/6703)already submitted for the fix to the impacted pages, I'll go ahead and close out this issue as resolved.  We can track the progress of the updates within those from here. We appreciate you calling this out and helping improve the docs!
