### ISSUE TITLE
Custom Analytics Plugin not working (or available?) in v6.0.8 of aws-amplify

### ISSUE THREAD

**Issue by Alk3m1st** [aws-amplify/amplify-js#12725]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Analytics

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line

  System:
    OS: Linux 5.10 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (2) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 614.65 MB / 5.80 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
  npmGlobalPackages:
    aws-cdk: 2.100.0
    awsp: 0.2.0
    corepack: 0.15.3
    npm: 9.5.0
    typescript: 5.1.6

```

</details>

### Describe the bug

We have been using a Custom Analytics plugin to send events to API Gateway and then Kinesis as a journey analytics solution following guidance in the v5 documentation - https://docs.amplify.aws/javascript/prev/build-a-backend/more-features/analytics/create-custom-plugin/

This has been working well for us however when I went to upgrade to the newer v6 aws-amplify JS library so that we can benefit from the recent file size and tree shaking improvements, I've found there's no obvious equivalent or documentation around how to migrate a Custom Analytics plugin to the new version.

### Expected behavior

Detailed documentation on how to migrate to the new version and where the various imports have been migrated to.

### Reproduction steps

`npm i aws-amplify`
verify that v6 has been installed
notice that the Analytics class is not exposed and thus access to the addPluggable method
no obvious way to configure an existing Custom Analytics Plugin

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by pascalito007** [comment]
The are lot of issues that are no more working when migrating from v5 wich I find very frustrating.

**Comment by cwomack** [comment]
Hello, @Alk3m1st 👋.  We appreciate you opening this issue, as more people will likely run into this when upgrading to v6.   Custom plugins for Analytics are not currently supported in v6.  Can you provide more details as to what your custom plugin was doing to send events to API Gateway/Kinesis as a journey analytics solution to see if there's a workaround or alternative that can be implemented?

**Comment by Alk3m1st** [comment]
> Hello, @Alk3m1st 👋. We appreciate you opening this issue, as more people will likely run into this when upgrading to v6. Custom plugins for Analytics are not currently supported in v6. Can you provide more details as to what your custom plugin was doing to send events to API Gateway/Kinesis as a journey analytics solution to see if there's a workaround or alternative that can be implemented?

Hi @cwomack.

Happy to provide more details if you can recommend an alternative or workaround.

We have a Custom Plugin that implements the `AnalyticsProvider` interface from `@aws-amplify/analytics` to enable us to send custom events that can contain additional context fields, can be enriched with additional data (such as who was the producer) and also additional meta data (we borrowed some of this from how CloudWatch RUM works). We have a custom event buffer and event dispatcher for batching the events through to our API gateway endpoint.

We use `Amplify` from `@aws-amplify/core` to configure our endpoint, API key, etc. We also use `Credentials`, `Signer` and `StorageHelper` from `@aws-amplify/core` as we're not using the Auth module and need to manually configure the Credentials service. This works similar to RUM with our Identity Pool and STS allowing us to assume an unauth role. These seem to be internal in v6 and not exposed anymore? The `StorageHelper` allows us to create and save a short-lived sessionId in local storage to help consolidate events to a user/device.

On the API Gateway side we perform some lightweight validation before going into a Kinesis Stream and writing to an S3 bucket via Firehose. Ultimately we ingest these events into our Data Lake. We are only using the Amplify JS library, not the platform, we use CDK for our infrastructure.

Hopefully there's a migration strategy we could use to get onto v6 or a straightforward alternative that allows us to keep sending the same events through to our Data Lake.

**Comment by Alk3m1st** [comment]
Just checking in to see if there's been any movement or updates since I raised this issue?

**Comment by cwomack** [comment]
@Alk3m1st, wanted to follow up on this issue after reviewing it further with our team.  With v6 functional approach, you shouldn't need to implement your own solution as an Amplify plugin and can use the `fetchAuthSession` [API](https://docs.amplify.aws/gen1/react/build-a-backend/auth/manage-user-session/) in Auth to obtain credentials for the user along with the `@smithy/signature-v4 package ` package for `Signer`.  For the `Signer` aspect of this issue in particular, we have #13340 as a feature request already if you'd like to add a comment/update on it.

With the above said, I'll close this issue out for now... but we can reopen if we revisit our support Custom Analytics Plugins again.
