### ISSUE TITLE
Passing down className prop in S3Image component

### ISSUE THREAD

**Issue by Hugodby** [aws-amplify/amplify-js#1272]
**Feature request**

What is the current behavior?
In _aws-amplify-react_ Passing `className` prop to S3Image components has no effect. The prop is ignored. I want to be able to set CSS class on the S3Image component.

```
<S3Image className="thumbnail" imgKey={props.image} />
```

**Comment by jnreynoso** [comment]
it is not possible to modify the sizes (width, height) of the image contained in the div.

**Comment by gabehollombe-aws** [comment]
👍  I'd like this, too.  

My specific use case is that I'm using semantic-ui-react and am rendering some images captured by a webcam, with the img src passed directly to Semantic UI React's Image component. I'm rendering these images alongside existing images in an S3 bucket via aws-amplify-react's S3Image component.

My problem is that I want the S3Image images to render similarly to the Image images. To do this, I'd like to get the `img` tag inside the S3Image component to have 'ui image' classes on it. It would be nice if I could pass those in via a prop to S3Image.

**Comment by jordanranz** [comment]
FYI, we have started an RFC discussion for a proposed Amplify UI Component refactor to increase customizability and flexibility for our components. Please feel free to add any additional comments to the following issue:

https://github.com/aws-amplify/amplify-js/issues/3279

**Comment by akasper-connyun** [comment]
Would love to have this too! The workaround with an enclosing div and `img` in CSS is not nice as one cannot reuse CSS classes.

**Comment by emmafass** [comment]
@ericclemmons I am trying to pass className to S3Image and I am not able to get it to recognize the className prop.

`<S3Image imgKey={profilePictureKey} className="img-thumbnail" />`

Does this look right to you?
