### ISSUE TITLE
Unable to use the Angular http interceptor when using aws-amplify

### ISSUE THREAD

**Issue by brianreinhold** [aws-amplify/amplify-js#12738]
### Is this related to a new or existing framework?

Angular

### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

I want to be able to intercept the http requests being sent out by my client app (mainly to see that there are correct). If I send my own http request using the Angular HttpClient, I can see the request in the interceptor. But when I send an aws-amplify method like 'signIn()' I do not. I do not know what goes on under the hood when I call that method.

If there IS a way to trap these requests I would like to know how to do it or point me to some documentation that explains how it can be done.

### Describe the solution you'd like

The ability to trap aws-amplify http requests in the Angular Http Interceptor (Angular 17)

### Describe alternatives you've considered

I do not know of any.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cwomack** [comment]
Hello, @brianreinhold and thanks for opening this issue.  There was a similar feature request opened a while back with some good workarounds suggested [here](https://github.com/aws-amplify/amplify-js/issues/1069#issuecomment-1221062027).  Can you take a look at that and see if it will suffice for what you're looking to do?

**Comment by brianreinhold** [comment]
I stumbled upon axios later in my searches (I think in a StackOverflow). I could use that. It would be more convenient to use just one http interceptor but that's a twist of laziness. Once I get authenticated through Cognito all the http requests I make are my own apis and thus use the HttpClient.

**Comment by cwomack** [comment]
@brianreinhold, could you potentially clarify the use case and implementation that you're looking for here? We don't have `axios` in v6 of Amplify (latest major version), but want to make sure there's not a feature that we're missing here.  Thanks!

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. We don't intend on implementing `axios` again for http interceptors due to our goals on reducing complexity in the latest version of Amplify as well as trying to remove our dependencies on third parties. Feel free to reply back and provide any additional context that we missed and we can re-open the issue if needed.

Thank you!
