### ISSUE TITLE
API name is invalid exception with Amplify Gen 2

### ISSUE THREAD

**Issue by rpostulart** [aws-amplify/amplify-js#12743]
### Environment information

```plain text
System:
    OS: macOS 14.1.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 69.78 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 20.8.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 10.1.0 - /usr/local/bin/npm
    pnpm: Not Found
    bun: Not Found
    Watchman: 2022.12.26.00 - /usr/local/bin/watchman
  npmPackages:
    @aws-amplify/backend: ^0.6.0 => 0.6.0 
    @aws-amplify/backend-cli: ^0.9.2 => 0.9.2 
    aws-amplify: ^6.0.7 => 6.0.7 
    aws-cdk: Not Found
    aws-cdk-lib: ^2.115.0 => 2.115.0 
    typescript: ^5.3.3 => 5.3.3
```

### Description

When I create an API gateway via CDK with AWS Amplify GEN2 and I add this to the root file like this:

```
import { Amplify } from "aws-amplify";
import config from "../../amplifyconfiguration.json";
import CDKConfiguration from "./cdk-exports.json";

Amplify.configure(config); // <=== Initialize Amplify with the exports config
const existingConfig = Amplify.getConfig(); // <=== the initialized config should now be returned to existingConfig

Amplify.configure({
  ...existingConfig, // <=== existingConfig instead of awsconfig
  API: {
    ...existingConfig.API,
    REST: {
      ...existingConfig.API?.REST,
      ['ACGateway']: {
        endpoint: CDKConfiguration.CdkGatewayStack.ACGatewayEndpointD965756B1,
      },
    },
  },
});

console.log( Amplify.getConfig()?.API);
```

Then Amplify.getConfig()?.API gives me:

```
REST: {
    ACGateway: {
      endpoint: 'xxxxxxx'
    }
  }

```

When I debug @aws-amplify>api-rest>dist>esm>utils> resolveApiUrl.mjs
```

const resolveApiUrl = (amplify, apiName, path, queryParams) => {
    const urlStr = amplify.getConfig()?.API?.REST?.[apiName]?.endpoint;
    assertValidationError(!!urlStr, RestApiValidationErrorCode.InvalidApiName);
    try {
        const url = new AmplifyUrl(urlStr + path);
        if (queryParams) {
            const mergedQueryParams = new AmplifyUrlSearchParams(url.searchParams);
            Object.entries(queryParams).forEach(([key, value]) => {
                mergedQueryParams.set(key, value);
            });
            url.search = new AmplifyUrlSearchParams(mergedQueryParams).toString();
        }
        return url;
    }
    catch (error) {
        throw new RestApiError({
            name: RestApiValidationErrorCode.InvalidApiName,
            ...validationErrorMap[RestApiValidationErrorCode.InvalidApiName],
            recoverySuggestion: `Please make sure the REST endpoint URL is a valid URL string. Got ${urlStr}`,
        });
    }
};
```

Then in amplify.getConfig

The REST object is not available, but only the GRAPHQL object

```
API
: 
{GraphQL: {…}}
Auth
: 
{Cognito: {…}}
```

and then the exception (API name is invalid )  is thrown on this code:

```
  async function updateTodo() {
      try {
        const todo = { name: "My first todo", message: "Hello world!" };
        const restOperation = post({
          apiName: "ACGatewayEndpointD965756B1",
          path: "invitation",
          options: {
            body: todo,
          },
        });
        const response = await restOperation.response;
        console.log("PUT call succeeded: ", response);
      } catch (err) {
        console.log("PUT call failed: ", err);
      }
    }
```

**Comment by nadetastic** [comment]
Hi @rpostulart thank you for opening this issue. From the sample you provided, it looks like you are passing the wrong apiName into `post()` and the error looks to be expected. From the config, the api name looks to be `ACGateway` but you are calling `ACGatewayEndpointD965756B1` which does not exist.

Could you try calling post() with `ACGateway` instead?

```js
...
const restOperation = post({
          apiName: "ACGateway",
```

**Comment by rpostulart** [comment]
So, that has caused by trail and error but also with apiName: "ACGateway" I get the same result. 
I expect that the Amplify.getConfig is not passed correctly to resolveApiUrl

**Comment by nadetastic** [comment]
@rpostulart are you calling Amplify.configure() anywhere else in you app? It sounds like it may be overwriting the config again at a different location

**Comment by rpostulart** [comment]
Wow that did the trick, thanks!
I am calling Amplify.configure from this component:
https://docs.amplify.aws/react/build-a-backend/server-side-rendering/nextjs/#configure-amplify-library-for-client-side-usage

**Comment by rpostulart** [comment]
By the way, this was created with CDK because with GEN 2 (https://docs.amplify.aws/gen2/build-a-backend/add-aws-services/custom-resources/)  when I create an apigateway CDKstack. I had the same error, because I don't have access to the cdk-export.json (because it is not generated with GEN2) and also in amplifyconfiguration.json it's key and endpoint is also not available / added

**Comment by xkem** [comment]
> Wow that did the trick, thanks! I am calling Amplify.configure from this component too: https://docs.amplify.aws/react/build-a-backend/server-side-rendering/nextjs/#configure-amplify-library-for-client-side-usage

What did the trick?

**Comment by piedmontlong** [comment]
> Wow that did the trick, thanks! I am calling Amplify.configure from this component too: https://docs.amplify.aws/react/build-a-backend/server-side-rendering/nextjs/#configure-amplify-library-for-client-side-usage

From my case, I have following code in main.ts:
import outputs from "../amplify_outputs.json";
Amplify.configure(outputs);
The apiName is correct in amplify_outputs.json. But still got same error: InvalidApiName: API name is invalid.
How did you fix it? Thanks
