### ISSUE TITLE
Changelog output is pretty pointless currently

### ISSUE THREAD

**Issue by ossareh** [aws-amplify/amplify-js#1274]
## Bug

**current behavior**

The current behaviour of your recent changes to releases makes the changelogs pretty impossible to understand.

**Examples**

[Core Amplify Package](https://github.com/aws-amplify/amplify-js/blob/release/packages/aws-amplify/CHANGELOG.md)

We moved from v0.4.9 to v 1.0.1 and there is literally no information about what happened in that change.

[Cognito Identity JS](https://github.com/aws-amplify/amplify-js/blob/release/packages/amazon-cognito-identity-js/CHANGELOG.md)

the note is:

> _Note_: Version bump only for package amazon-cognito-identity-js

which is clearly wrong because this is the package that is being bumped.

This pattern repeats across the whole set of packages.

**Expected Behaviour**

Meaningful changelogs are superful to establish whether it is time to update. For example, it's not easy for me to tell whether #1200 is in the current release; it should be.

**Analysis**

From what I can tell the issue is coming from not following the Conventional Commits pattern in commit messages ([examples](https://github.com/aws-amplify/amplify-js/commits/master)). Perhaps consider using [husky](https://github.com/typicode/husky/blob/dev/DOCS.md) with [commit lint](https://github.com/marionebl/commitlint) to enforce commit messages.

I'm happy to submit a fix for this, but it's pretty fundamental so would like to discuss this first.

**Comment by michaelbrewer** [comment]
I am not sure where to look for the changes, i would suggest to the team to implement something like what happens with the Lambda Powertools (https://github.com/awslabs/aws-lambda-powertools-python/releases)

**Comment by abdallahshaban557** [comment]
We have now introduced a changelog process, and are also including any upgrade details that are needed if you were running a previous version of the Amplify library.
