### ISSUE TITLE
NodeJS - Auth.signOut is signing all users out 

### ISSUE THREAD

**Issue by peadarkelly** [aws-amplify/amplify-js#1275]
Version - 0.4.8

When `Auth.signOut()` is executed by a single user, all active user sessions are invalidated. After some investigation, it looks like the `LastAuthUser` storage entry is causing the problem when multiple users are accessing the application.

* When `Auth.signIn()` is executed, the provided username is placed in Amplify's storage using this key.

* When `Auth.currentAuthenticatedUser()` is executed, it reads this entry, and if it exists then it will create a CognitoUser with this username, otherwise it will throw "not authenticated".

* When `Auth.signOut()` is executed, this entry is deleted

*Example*

On startup of my Node app, I am configuring Amplify.Auth as follows:
```
Amplify.configure({
    Auth: {
        region: ...,
        userPoolId: ...,
        userPoolWebClientId: ...,
        mandatorySignIn: true
    }
  })
```

I have 2 users belonging to the same User Pool - user1 and user2

1. User 1 signs in:
```
Auth.signIn("user1", "somePassword")
```
LastAuthUser is set to "user1"

2. User 2 signs in:
```
Auth.signIn("user2", "somePassword")
```
LastAuthUser is set to "user2"

3. User 1 signs out:
```
Auth.signOut(<user1>)
```
LastAuthUser has been cleared and is now undefined

4. As User 2 progresses through the app, the following is executed:
```
Auth.currentAuthenticatedUser()
```
LastAuthUser is now undefined, therefore a "not authorised" exception is thrown.

User 2 was never logged out and should therefore still have a valid session.

It seems that the LastAuthUser storage key cannot handle concurrent users from the same user pool using the app.

**Comment by powerful23** [comment]
Closing the issue as no further response. Please feel free to reopen if you still have this issue.

**Comment by max77p** [comment]
@powerful23 I currently have the following sign in method, where after i get response i send that to node server side and then filter through which challenge type it is.  It works fine, but If I open lets say three tabs up, and sign in using three accounts. Then sign out any ONE user, how can I implement it so that all users are not signed out and my local storage updates accordingly?

`  handleSubmit(e) {
    e.preventDefault();
    console.log(`user is ${this.state.user} and pass is ${this.state.pass}`);
    //val.user has the email
    // this.props.userinfo({ user: this.state.user, pass: this.state.pass })
    this.handleAuth({ user: this.state.user, pass: this.state.pass })

    this.setState(prevState => ({
      ...prevState,
      user: '',
      pass: ''
    }))
  }


  async handleAuth(user) {
    console.log(user)
    const test = await Auth.signIn({
      username: user.user, // Required, the username
      password: user.pass, // Optional, the password
    })
    console.log(test);
    this.props.userinfo(test);
  }`
