### ISSUE TITLE
Cognito ValidationException when multiple redirect URIs

### ISSUE THREAD

**Issue by redjonzaci** [aws-amplify/amplify-js#12764]
### Amplify CLI Version

12.3.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Describe the bug

I get the following error only when I have multiple redirect URIs:
```{
    "__type": "ValidationException",
    "message": "1 validation error detected: Value '{cognito-idp.us-east-1.amazonaws.com/us-east-1_XXXXXXXXXX}' at 'logins' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 50000, Member must have length greater than or equal to 1]"
}
```

I tried the solution described in https://github.com/aws-amplify/amplify-cli/issues/7359#issuecomment-893039375, but nothing changed.

### Expected behavior

I expect Google login to work with multiple redirect URIs.

### Reproduction steps

1. Add multiple redirect URIs.
2. Try to login with Google.

The user will be created, but you won't be able to login because of the error above.

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by nadetastic** [comment]
Hi @redjonzaci thank you for opening this issue. Can you confirm the following:
- What version of `aws-amplify` are you using?
- Are you calling Amplify.configure() multiple times and updating the redirectUrls?

**Comment by nadetastic** [comment]
Related - https://github.com/aws-amplify/amplify-js/issues/10060

**Comment by nadetastic** [comment]
Related https://github.com/aws-amplify/amplify-js/issues/12819
