### ISSUE TITLE
Amplify API (GQL): Two different types with this name exist, but they are unrelated

### ISSUE THREAD

**Issue by armenr** [aws-amplify/amplify-js#12772]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Nuxt + Vue

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

```
  System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 141.22 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.21 - ~/Library/pnpm/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: 8.13.1 - ~/Library/pnpm/pnpm
    bun: 0.1.10 - ~/.bun/bin/bun
  Browsers:
    Chrome: 120.0.6099.129
    Edge: 113.0.1774.57
    Safari: 17.2.1
  npmPackages:
    @nuxt/types: ^2.15.8 => 2.17.2
    @nuxt/typescript-build: ^2.1.0 => 2.1.0
    @nuxtjs/tailwindcss: ^5.3.3 => 5.3.5
    @vue/compiler-sfc:  2.7.16
    core-js: ^3.25.3 => 3.35.0
    nuxt: ^2.15.8 => 2.17.2
    postcss: ^8.4.17 => 8.4.32 (7.0.39)
    vue: ^2.7.10 => 2.7.16
    vue-server-renderer: ^2.7.10 => 2.7.16
    vue-template-compiler: ^2.7.10 => 2.7.16
  npmGlobalPackages:
    corepack: 0.22.0
    npm: 10.2.3


```
</details>

### Describe the bug

This is a weird bug, and it's increasingly painful for us. 

We're using NuxtJS (latest) with Vue3 + TypeScript, and the latest Amplify libraries and CLI.

Here's a minimal reproduction from a Vue3 component we have: 

```vue
<script setup lang="ts">
import { generateClient } from 'aws-amplify/api'
import { Amplify } from 'aws-amplify'
import config from '@/amplifyconfiguration.json'
import type { Post } from '~/API'

const client = generateClient()
const newPosts = ref<Post[]>([])

Amplify.configure(config)

const moreData = await client.graphql({
  query: listPosts,
  variables: {},
})

newPosts.value = moreData.data.listPosts.items

definePageMeta({
  layout: 'user-nav',
})
</script>

<template>
  <div />
</template>
```

VScode poops its pants and complains:

```
Type '{ __typename: "Post"; id: string; body: string; user?: { __typename: "User"; id: string; owner: string; emailAddress: string; phoneNumber: string; firstName: string; lastName: string; birthdate: string; ... 5 more ...; updatedAt: string; } | null | undefined; userId: string; comments?: { ...; } | ... 1 more ... | un...' is not assignable to type '{ __typename: "Post"; id: string; body: string; user?: { __typename: "User"; id: string; owner: string; emailAddress: string; phoneNumber: string; firstName: string; lastName: string; birthdate: string; ... 5 more ...; updatedAt: string; } | null | undefined; userId: string; comments?: { ...; } | ... 1 more ... | un...'. Two different types with this name exist, but they are unrelated.

Type '{ __typename: "Post"; id: string; body: string; user?: { __typename: "User"; id: string; owner: string; emailAddress: string; phoneNumber: string; firstName: string; lastName: string; birthdate: string; ... 5 more ...; updatedAt: string; } | null | undefined; userId: string; comments?: { ...; } | ... 1 more ... | un...' is not assignable to type '{ __typename: "Post"; id: string; body: string; user?: { __typename: "User"; id: string; owner: string; emailAddress: string; phoneNumber: string; firstName: string; lastName: string; birthdate: string; ... 5 more ...; updatedAt: string; } | null | undefined; userId: string; comments?: { ...; } | ... 1 more ... | un...'. Two different types with this name exist, but they are unrelated.ts(2719)

API.ts(189, 3): 'items' is declared here.
```

Screenshots:
![Screenshot 2023-12-29 at 3 37 51 PM](https://github.com/aws-amplify/amplify-js/assets/7662191/85289e2b-145d-42bb-995b-53ccb776c8fe)

![Screenshot 2023-12-29 at 3 38 41 PM](https://github.com/aws-amplify/amplify-js/assets/7662191/b26da523-ffc5-4a16-a7de-480ee3d2ba47)

Weirdly (or not weirdly), an explicit Type Assertion makes it all go away:
```vue
<script setup lang="ts">
import { generateClient } from 'aws-amplify/api'
import { Amplify } from 'aws-amplify'
import config from '@/amplifyconfiguration.json'
import type { Post } from '~/API'

const client = generateClient()
const newPosts = ref<Post[]>([])

Amplify.configure(config)

const moreData = await client.graphql({
  query: listPosts,
  variables: {},
})

newPosts.value = moreData.data.listPosts.items as Post[]

definePageMeta({
  layout: 'user-nav',
})
</script>

<template>
  <div />
</template>
```
![Screenshot 2023-12-29 at 3 40 17 PM](https://github.com/aws-amplify/amplify-js/assets/7662191/d0b833cd-9df3-446a-97f6-ea8a84ecb779)

### Expected behavior

We expect not to have to explicitly provide Type Assertions on results that are already typed correctly (or should be typed correctly) from GraphQL, for every call we make, everywhere.

We'd expect for this to work as expected, without throwing weird errors or warnings.

```vue
<script setup lang="ts">
import { generateClient } from 'aws-amplify/api'
import { Amplify } from 'aws-amplify'
import config from '@/amplifyconfiguration.json'
import type { Post } from '~/API'

const client = generateClient()
const newPosts = ref<Post[]>([])

Amplify.configure(config)

const moreData = await client.graphql({
  query: listPosts,
  variables: {},
})

newPosts.value = moreData.data.listPosts.items

definePageMeta({
  layout: 'user-nav',
})
</script>

<template>
  <div />
</template>

```

### Reproduction steps

1. Set up a nuxt3 + typescript + amplify boilerplate (vanilla, nothing weird or special)
2. Amplify add api (graphql)
3. Open VScode
4. Create a model named "Post" (or rename your generic Todo starter model to Post)
5. Create a generic page in Vue
6. Copy paste the above code into the `.vue` file
7. Be sad

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by nadetastic** [comment]
HI @armenr thanks for opening this issue. The reason you are seeing the type errors in VSCode is because you are instantiating the variable `newPosts` as type of `Post[]`, however the response from `client.graphql()` where the query is listPosts is not `Post[]`. Further, accessing `moreData.data.listPosts.items` will give you a type that is essentially `Post[] | null` which is not the same as `Post[]`

The solution is to do an assertion as you have or use a different type on newPosts - for example you should have a `ListPostsQuery` type which is what `client.graphql()` returns. With this type you can define `newPost: ListPostsQuery["listPosts"]` for example:

```js
const newPosts = ref<ListPostsQuery["listPosts"] | null>(null)

Amplify.configure(config)

const moreData = await client.graphql({
  query: listPosts,
  variables: {},
})

newPosts.value = moreData.data.listPosts
```

**Comment by cwomack** [comment]
Hey, @armenr wanted to give you one more bit of info on this. We expect that there can be discrepancies in the returned types from the API calls, so you can use the `GraphQLReturnType` util method to adapt the generated types to receive/work with the types API response.  You can do something like the following: 

- `GraphQLReturnType<Post>`
- `GraphQLReturnType<Post>[]`

That util method is effectively a DeepOptional typemap, but this issue has brought to light that we need to detail this better in our documentation as well.

**Comment by chrisbonifacio** [comment]
@armenr I believe those `EagerModel` types were meant for DataStore backwards compatibility after Lazy Loading was introduced in v5 of the `aws-amplify` library. We now have types for Eager and Lazy models. They may work for now but I would not rely on them to work long term.

Did you try the typing that @cwomack suggested?

> * `GraphQLReturnType<Post>`
> * `GraphQLReturnType<Post>[]`
