### ISSUE TITLE
Backup/Restore Amplify Datastore - React Native

### ISSUE THREAD

**Issue by digvijaysinh-york** [aws-amplify/amplify-js#12770]
### Is this related to a new or existing framework?

React Native

### Is this related to a new or existing API?

DataStore

### Is this related to another service?

Amplify Datastore

### Describe the feature you'd like to request

We are creating an app with offline sync scenarios. In that user can perform operations without internet for month because users are engineers working on sites with no network. So we need feature to backup and restore data for data safety on local device.

### Describe the solution you'd like

We can create backup of datastore and then after also we should be able to restore any selected version of backup.

### Describe alternatives you've considered

Backup and restore SQLite database on document directory.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cwomack** [comment]
Hello @digvijaysinh-york and thanks for opening this issue.  Can you clarify what version of Amplify you're using as well as elaborate a little more on what your database setup currently looks like?

There isn't an existing feature within DataStore to create a backup of sorts.  If you're using the SQLite adapter, then DataStore will create a database named `AmplifyDatastore` on the device which is just a file that can be backed up/restored like any other file you have locally. Let me know if that helps!

**Comment by digvijaysinh-york** [comment]
> Hello @digvijaysinh-york and thanks for opening this issue. Can you clarify what version of Amplify you're using as well as elaborate a little more on what your database setup currently looks like?
> 
> There isn't an existing feature within DataStore to create a backup of sorts. If you're using the SQLite adapter, then DataStore will create a database named `AmplifyDatastore` on the device which is just a file that can be backed up/restored like any other file you have locally. Let me know if that helps!

Thanks @cwomack I'll check it.
