### ISSUE TITLE
Ampliy-Auth V6, How to get ChallengeParameters to show back to user in UI

### ISSUE THREAD

**Issue by HanojHanu** [aws-amplify/amplify-js#12780]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 PRO 4650U with Radeon Graphics
    Memory: 6.00 GB / 15.23 GB
  Binaries:
    Node: 18.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.3 - ~\node_modules\.bin\npm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.91)
    Internet Explorer: 11.0.19041.3636
  npmGlobalPackages:
    @angular/cli: 13.3.0
    @aws-amplify/cli: 10.4.1
    @cyclonedx/cyclonedx-npm: 1.6.1
    aws-sdk-js-codemod: 0.14.0
    create-react-app: 5.0.1
    http-server: 14.1.1
    jest: 27.5.1
    newman: 5.3.2
    node-prune: 1.0.2
    nodemon: 2.0.20
    npm: 9.6.3
    nx: 16.7.4
    rimraf: 5.0.5
    rollup: 3.7.5
    yarn: 1.22.21

```

</details>

### Describe the bug

**Where to get these values "CODE_DELIVERY_DESTINATION" or "FRIENDLY_DEVICE_NAME"**
![image](https://github.com/aws-amplify/amplify-js/assets/53425981/0943cda5-2b5a-4738-8e99-8e9d183a3682)
![image](https://github.com/aws-amplify/amplify-js/assets/53425981/de8c36c4-ba83-4c36-9287-43b4d423d6de)
![image](https://github.com/aws-amplify/amplify-js/assets/53425981/74ea812d-b56f-4456-b298-9907304adf1b)
With Latest version of Auth V6

> We are **not able to get** _`CODE_DELIVERY_DESTINATION`_ _`FRIENDLY_DEVICE_NAME`_

To showcase to user - based-on choose MFA option to Auth

### Expected behavior

![image](https://github.com/aws-amplify/amplify-js/assets/53425981/37682384-1f53-4694-b0dd-8e896997142e)
![image](https://github.com/aws-amplify/amplify-js/assets/53425981/34b57169-185a-4aff-86ef-9092d88f5b68)

Expected behavior is we want show to user, their ChallengeParameters based-on option selected.
CODE_DELIVERY_DESTINATION
FRIENDLY_DEVICE_NAME

### Reproduction steps

1. install auth 6v
2. sign-in with MFA 
3. enable totp to user
4. now, try to sign-in with MFA this time you'll not-able to show ChallengeParameters to display in UI

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by nadetastic** [comment]
HI @HanojHanu thank you for opening this issue. Can you clarify how the user is signing in? The screenshots you shared seem to be the Hosted UI. Im assuming that you want the same behavior when calling `signIn()`? As a note, the signIn function returns an out put that contains a next step and context on that next step. You should be able to get the values you need from that.

- https://docs.amplify.aws/react/build-a-backend/auth/enable-sign-up/#sign-in
- https://docs.amplify.aws/react/build-a-backend/auth/manage-mfa/#update-the-current-users-mfa-preferences

The second link above also shows an example of how to handle MFA next steps in you app.

**Comment by HanojHanu** [comment]
@nadetastic, Screen shots mentioned here.. for pointing out referance example i have taken from hosted-ui.

But my point is clear, we are using amplify auth npm package in our react application.

**Comment by HanojHanu** [comment]
> Im assuming that you want the same behavior when calling signIn()? As a note, the signIn function returns an out put that contains a next step and context on that next step. You should be able to get the values you need from that.
https://docs.amplify.aws/react/build-a-backend/auth/enable-sign-up/#sign-in
https://docs.amplify.aws/react/build-a-backend/auth/manage-mfa/#update-the-current-users-mfa-preferences
The second link above also shows an example of how to handle MFA next steps in you app.

Amplify `sign-in` returns only next step to do.
But not shown, never recived in response like challengeParameters.
this network log we can see here... but  `sign-in` not getting this values back us.
![image](https://github.com/aws-amplify/amplify-js/assets/53425981/858b2027-8406-418e-b0fd-b455bba9ac76)

**Comment by nadetastic** [comment]
@HanojHanu you should be able to access the DESTINATION from the return out put of sign in like this:
```js
const result: SignInOutPut = await signIn({username,password})

// For SMS MFA
const destination = result.nextStep.codeDeliveryDetails.destination;
```
Could you try this? Or try to console log the `result` object that is returned by signIn()?

For friendly device name, let me confirm the behavior with the team and will follow up.

**Comment by HanojHanu** [comment]
![image](https://github.com/aws-amplify/amplify-js/assets/53425981/ed3ce9f8-1b12-4e8a-86c4-d0dacd6db8f3)
![image](https://github.com/aws-amplify/amplify-js/assets/53425981/691b8f71-d4ed-4dc1-9d73-5572e4c2bfea)

**Comment by HanojHanu** [comment]
@nadetastic

**Comment by oliverjohns** [comment]
Im experiencing the same problem, aws-amplify v6 does not seem to include this `CODE_DELIVERY_DESTINATION` nor the `CODE_DELIVERY_DELIVERY_MEDIUM` .

**Comment by HanojHanu** [comment]
@cwomack  and @nadetastic, any updates here ?

**Comment by nadetastic** [comment]
@HanojHanu Im still unable to reproduce this issue on my end. After I have created a user and setup SMS MFA, I call `signIn()` and this is the response I get when I `console.log` the result of signIn()

```js

const result = await signIn({username,password});

console.log('signIn result: ',result):
signIn result: {
    isSignedIn: false,
    nextStep: {
        codeDeliveryDetails: {
            deliveryMedium: "SMS",
            destination: "+*******1234"
        },
        signInStep: "CONFIRM_SIGN_IN_WITH_SMS_CODE"
    }
}
```

Is there any additional context you can provide here? For example, how did you create you Cognito resources, or more information about how you MFA configuration is done, such as Is it optional or required?

**Comment by cwomack** [comment]
Hey, @HanojHanu are you still experiencing this issue?  Don't know if you had a chance to look at @nadetastic's [comment above](https://github.com/aws-amplify/amplify-js/issues/12780#issuecomment-1953056770) and example code snippet, but let us know if you're blocked by this.

**Comment by nadetastic** [comment]
@HanojHanu following up here - going to mark this issue as closed for now. If you are still facing issues or have questions please let me know and I'll be happy to help.

**Comment by hanoj-budime** [comment]
@nadetastic, Yes we're still facing that same issue..

**Comment by hanoj-budime** [comment]
@nadetastic, can you check with your team is this changes supported or not ?

even in in your documention also missing that, Please check @nadetastic & @cwomack.

**Comment by hanoj-budime** [comment]
> @HanojHanu Im still unable to reproduce this issue on my end. After I have created a user and setup SMS MFA, I call `signIn()` and this is the response I get when I `console.log` the result of signIn()
> 
> ```js
> const result = await signIn({username,password});
> 
> console.log('signIn result: ',result):
> signIn result: {
>     isSignedIn: false,
>     nextStep: {
>         codeDeliveryDetails: {
>             deliveryMedium: "SMS",
>             destination: "+*******1234"
>         },
>         signInStep: "CONFIRM_SIGN_IN_WITH_SMS_CODE"
>     }
> }
> ```
> 
> Is there any additional context you can provide here? For example, how did you create you Cognito resources, or more information about how you MFA configuration is done, such as Is it optional or required?

version ?

**Comment by hanoj-budime** [comment]
@nadetastic, open this issue. still not working.

Checked with latest version, no luck in getting "FRIENDLY_DEVICE_NAME"
