### ISSUE TITLE
Calls to reset password reveal if user registered

### ISSUE THREAD

**Issue by OperationalFallacy** [aws-amplify/amplify-js#12794]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React Native

### Which UI component?

Authenticator

### How is your app built?

next.js

### What browsers are you seeing the problem on?

Safari

### Please describe your bug.

This is more for the Cognito team. I see a few problems with requests to reset passwords:

1. Cognito responds with UserNotFoundException to reset the password. I believe it should be instead "requested; we'll send a link if the user exists". Otherwise, a bad actor can quickly check if a specific email is registered with a service.
2. Does Cognito prevent multiple requests to the account recovery endpoint? Somebody can start checking emails with 30 RPS (default quote for UserAccountRecovery).

![image](https://github.com/aws-amplify/amplify-ui/assets/62673610/bded4c03-bf85-4989-a881-e594a17b31d9)

PS I'm not a security specialist; it may be all standard practices.
PPS I haven't done extensive research how it should behave, so if you point me out to some sources on Amplify/Cognito security, I'd appreciate that.

Thank you.

### What's the expected behaviour?

I want Cognito and UI to say nothing about user existence and, respectively, UI to say something along those lines about sending recovery information if user exists.

### Help us reproduce the bug!

Standard recover password flow on Authenticator.

### Code Snippet

```typescript
// Put your code below this line.

```

**Comment by Meags27** [comment]
Have you looked into this? This is what I use to prevent that

https://repost.aws/knowledge-center/cognito-prevent-user-existence-errors

**Comment by OperationalFallacy** [comment]
@Meags27 thank you, exactly what I was looking for

**Comment by cwomack** [comment]
Closing this issue since the answer was already pointed out by @Meags27 [comment](https://github.com/aws-amplify/amplify-js/issues/12794#issuecomment-1877494961) above.

Thank you @Meags27 for helping out the community with this answer!
