### ISSUE TITLE
version "^1.0.1" throws yellows Warnings

### ISSUE THREAD

**Issue by matamicen** [aws-amplify/amplify-js#1279]
Hi guys,
We updated amplify to 1.0.1 using RN 0.56, the the library seems to be working fine  but is throwing this yellow warning when execute **_Amplify.configure(awsconfig);_**

Promise Rejection (id: 0):
SyntaxError: JSON Parse error: Unexpected identifier "undefined"

it doesn't happen with 0.4.8 version. (Tested on Android and iOS, same result).

Thanks!

**Comment by powerful23** [comment]
@matamicen this is a bug which has been fixed in 1.0.2, please update the version of amplify. Thanks.

**Comment by matamicen** [comment]
Thanks @powerful23 and all the team, it is working now.
