### ISSUE TITLE
API.endpoint replace by ... in aws-amplify v6 ?

### ISSUE THREAD

**Issue by natuan62** [aws-amplify/amplify-js#12807]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

REST API

### Amplify Version

v6

### Amplify Categories

api

### Backend

Other

### Environment information

<details>

```
# Put output below this line

  System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 98.48 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 7.20.0 - ~/.config/yarn/global/node_modules/.bin/npm
    pnpm: 8.14.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 120.0.6099.199
    Safari: 17.2.1
  npmPackages:
    @graphql-codegen/plugin-helpers: 5.0.0 => 5.0.0 
    amazon-cognito-identity-js: ^6.3.7 => 6.3.7 
    ant-design-vue: ^3.2.20 => 3.2.20 
    aws-amplify: ^6.0.10 => 6.0.10 
  npmGlobalPackages:
    @aws-amplify/cli: 11.1.1
    npm: 8.19.2
    serve: 14.2.1
    typescript: 5.3.2
```

</details>

### Describe the bug

In aws-amplify v5. we use 

```
import { API } from 'aws-amplify';

const endpoint = await API.endpoint(this.apiName);
```

### Expected behavior

How to use API.endpoint in amplify v6

### Reproduction steps

How to use API.endpoint in amplify v6

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello @natuan62, and thanks for opening this issue.  If you're just upgraded your app to the latest major version (v6.x of Amplify) then the best way to see the differences in v5 vs v6 usage of the REST API  would be in our [migration guide examples](https://docs.amplify.aws/react/build-a-backend/restapi/restapi-v5-to-v6-migration-guide/).  These will compare the two version side by side so you can see how they've been updated! 

Depending on if you were making a `GET`, `POST`, `PUT`, etc. request, the v6 configuration and syntax may differ. Let me know if this helps and if you want to provide more examples of your v5 code, I can help with the refactoring as well.

**Comment by chrisbonifacio** [comment]
@natuan62 I do see the `endpoint` method that was part of the `API` library in v5. I don't see that there is a similar method in v6. However, unless there's an easier way to do it and I'm unaware, you can do something like:

```js
import { Amplify } from 'aws-amplify'

const apiName = 'todoApi'

Amplify.getConfig().API.REST[apiName].endpoint
```
![CleanShot 2024-01-08 at 13 51 33](https://github.com/aws-amplify/amplify-js/assets/16952986/45e6133e-7385-4ce5-8a5a-7839d6951cfb)
