### ISSUE TITLE
[Package Upgrade] Issue with aws-amplify 

### ISSUE THREAD

**Issue by sanjoydey23** [aws-amplify/amplify-js#12800]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

local environment.

System:
    OS: Linux 5.4 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (6) x64 Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz
    Memory: 4.43 GB / 15.63 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    pnpm: 7.33.6 - ~/.nvm/versions/node/v16.14.2/bin/pnpm

npmPackages:
  @aws-amplify/ui-react: ^6.0.3 => 6.0.3 
  @aws-amplify/ui-react-internal:  undefined ()

aws-amplify: ^6.0.4 => 6.0.4 
    aws-amplify/adapter-core:  undefined ()
    aws-amplify/analytics:  undefined ()
    aws-amplify/analytics/kinesis:  undefined ()
    aws-amplify/analytics/kinesis-firehose:  undefined ()
    aws-amplify/analytics/personalize:  undefined ()
    aws-amplify/analytics/pinpoint:  undefined ()
    aws-amplify/api:  undefined ()
    aws-amplify/api/server:  undefined ()
    aws-amplify/auth:  undefined ()
    aws-amplify/auth/cognito:  undefined ()
    aws-amplify/auth/cognito/server:  undefined ()
    aws-amplify/auth/server:  undefined ()
    aws-amplify/datastore:  undefined ()
    aws-amplify/in-app-messaging:  undefined ()
    aws-amplify/in-app-messaging/pinpoint:  undefined ()
    aws-amplify/push-notifications:  undefined ()
    aws-amplify/push-notifications/pinpoint:  undefined ()
    aws-amplify/storage:  undefined ()
    aws-amplify/storage/s3:  undefined ()
    aws-amplify/storage/s3/server:  undefined ()
    aws-amplify/storage/server:  undefined ()
    aws-amplify/utils:  undefined ()

npmGlobalPackages:
    @aws-amplify/cli: 12.8.2
    corepack: 0.10.0
    npm: 8.5.0
    pnpm: 7.33.6

### Describe the bug

Hi Team,

I have upgraded the `aws-amplify` and `@aws-amplify/ui-react` to latest. After upgrading and changing code as it is in official document, getting below error:-

```
# Put output below this line

./node_modules/@aws-amplify/ui-react/dist/esm/components/Authenticator/shared/RemoteErrorMessage.mjs
Can't import the named export 'Alert' from non EcmaScript module (only default export is available)

```

Code changes made :- 

Facing issue after upgrading the aws-amplify component to latest.

From:
"@aws-amplify/ui-react": "^1.2.24",
 "aws-amplify": "^4.3.6",

Upgraded to:
"@aws-amplify/ui-react": "^6.0.3",
 "aws-amplify": "^6.0.4",

Import statement: 
```js
import { Amplify } from 'aws-amplify';

Amplify.configure(config, {
  ssr: true
});
```
and below usage:

```js
import { signIn, signOut, signUp } from 'aws-amplify/auth';

await signUp({
        username,
        password,
        options: {
          userAttributes: {
            email: email
          }
        }
      });
```
Now when I run the application -> npm run start

I am getting below error in console and page is blank..

```
**./node_modules/@aws-amplify/ui-react/dist/esm/components/Authenticator/shared/RemoteErrorMessage.mjs
Can't import the named export 'Alert' from non EcmaScript module (only default export is available)**
```

Anyone please help?

### Expected behavior

Login page should work and there shouldn't be any error in console.

### Reproduction steps

1. Upgrade version 

From:
"@aws-amplify/ui-react": "^1.2.24",
 "aws-amplify": "^4.3.6",

Upgraded to:
"@aws-amplify/ui-react": "^6.0.3",
 "aws-amplify": "^6.0.4",

2. Modify code as per doc.  

From - 
```js
import { Auth } from 'aws-amplify'; 
```
to 
```js
import { signIn, signOut, signUp } from 'aws-amplify/auth';
```
3. Deleted existing node modules and ran `npm i`. Now run your application. 
```sh
npm run start
```
### Code Snippet

Code snippet provided in the details box above.

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

Provided all required information. I would appreciate any help on this. thanks!

**Comment by cwomack** [comment]
@sanjoydey23, is this still being experienced when you upgrade the app to v6?  If so, can you see if (after bumping to v6 again) deleting your `node_modules` folder, deleting your `package-lock.json`, and then reinstalling dependencies via `npm i` helps at all?

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!

**Comment by squirrelhomie** [comment]
> @reesscot @ioanabrooks - I have downgraded to v5 and looks ok. However, getting below error. Any idea how to resolve this?
> 
> ResizeObserver loop completed with undelivered notifications.

I'm also experiencing this issue, on v6 of aws-amplify/ui-react. 

I've tried breaking it down to the simplest parts. 

import { withAuthenticator } from "@aws-amplify/ui-react";
import "@aws-amplify/ui-react/styles.css";

App.js 

```
function App({ signOut, user }) {
  return (
    <>
      <h1>Hello {user.username}</h1>
      <button onClick={signOut}>Sign out</button>
    </>
  );
}

export default withAuthenticator(App);
```

Index.js

```
import React from "react";
import ReactDOM from "react-dom/client";
import "./index.css";
import App from "./App";
import reportWebVitals from "./reportWebVitals";

import { Amplify } from "aws-amplify";
import config from "./amplifyconfiguration.json";

Amplify.configure(config);

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
```

package.json 

```
{
  "name": "sample",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@aws-amplify/ui-react": "^6.1.6",
    "@aws-amplify/ui-react-core": "^3.0.12",
    "@headlessui/react": "^1.7.18",
    "@heroicons/react": "^2.1.3",
    "@radix-ui/react-direction": "^1.0.1",
    "@radix-ui/react-dropdown-menu": "^2.0.6",
    "@radix-ui/react-slider": "^1.1.2",
    "@svgr/core": "^8.1.0",
    "@tailwindcss/forms": "^0.5.7",
    "@testing-library/jest-dom": "^6.4.2",
    "@testing-library/react": "^15.0.0",
    "@testing-library/user-event": "^14.5.2",
    "@types/qrcode": "^1.5.5",
    "@xstate/react": "^3.2.2",
    "aws-amplify": "^6.0.26",
    "formik": "^2.4.5",
    "jest-matchmedia-mock": "^1.1.0",
    "lodash": "^4.17.21",
    "lottie-react": "^2.4.0",
    "qrcode": "^1.5.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.22.3",
    "react-scripts": "5.0.1",
    "resize-observer-polyfill": "^1.5.1",
    "tailwindcss": "^3.4.3",
    "tslib": "^2.6.2",
    "web-vitals": "^3.5.2",
    "yup": "^1.4.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```

I get this error 

```
ResizeObserver loop completed with undelivered notifications.
    at handleError (http://localhost:3000/static/js/bundle.js:48832:58)
    at http://localhost:3000/static/js/bundle.js:48851:7
```

whenever I attempt to _navigate_ around the authenticator. So when I click 'Forgot Password' or after I click 'Create Account' to go to the verify email screen
