### ISSUE TITLE
AWS Crypto Util is returning an error on deploy

### ISSUE THREAD

**Issue by seedwalk** [aws-amplify/amplify-js#12811]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Version

v6

### Backend

None

### Environment information

<details>

```

![image](https://github.com/aws-amplify/amplify-js/assets/4202661/5331c3a7-1a08-4ae8-9301-b6e7449b5042)

![image](https://github.com/aws-amplify/amplify-js/assets/4202661/c03d90e4-c3fa-4fdb-83b9-a4ecf07c0c9d)

pnpm vitejs react app, build suceeded but when loading the deployed app, it returns that error due to aws amplify library dependencies


```

</details>

### Describe the bug

pnpm vitejs react app, build suceeded but when loading the deployed app, it returns that error due to aws amplify library dependencies

### Expected behavior

the app works 

### Reproduction steps

Install a react app aplication with pnpm react and implement cognito on it, to work as if it was par of the aplication. (therefore amplify is needed )

### Code Snippet

```javascript
// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
import { fromUtf8 as fromUtf8Browser } from "@smithy/util-utf8";
// Quick polyfill
var fromUtf8 = typeof Buffer !== "undefined" && Buffer.from
    ? function (input) { return Buffer.from(input, "utf8"); }
    : fromUtf8Browser;
export function convertToBuffer(data) {
    // Already a Uint8, do nothing
    if (data instanceof Uint8Array)
        return data;
    if (typeof data === "string") {
        return fromUtf8(data);
    }
    if (ArrayBuffer.isView(data)) {
        return new Uint8Array(data.buffer, data.byteOffset, data.byteLength / Uint8Array.BYTES_PER_ELEMENT);
    }
    return new Uint8Array(data);
}
//# sourceMappingURL=convertToBuffer.js.map

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello, @seedwalk and thanks for opening this issue.  Want to clarify a few things so I can work on reproducing this issue on our side and understand the root cause.  It looks like the error you provided is "Cannot access fromUtf8 before initialization", but the source debugger shows the error emitting from the reference to `fromUtf8Browser`.  I'm curious if this is something tied to your bundler or name shadowing.  

Any chance you could provide your full `package.json` or share a minimal sample repo by chance?  I'll work on reproducing the issue in the mean time.

**Comment by seedwalk** [comment]
Sorry i should closed this one. This happend due to the way we were doing code splitting in our bundler. 

Sorry and thanks for reaching out!

**Comment by cwomack** [comment]
@seedwalk, no worries! Thanks for the follow up on this and closing out the issue.  Glad to hear you're unblocked.
