### ISSUE TITLE
Vue + Vite with amplify v6 : Auth UserPool not configured

### ISSUE THREAD

**Issue by natuan62** [aws-amplify/amplify-js#12819]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

GraphQL API

### Amplify Version

v6

### Amplify Categories

auth

### Backend

Other

### Environment information

<details>

```
# Put output below this line
 System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 3.58 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh

npmPackages:

"aws-amplify": "^6.0.10",

```

</details>

### Describe the bug

```
err AuthUserPoolException: Auth UserPool not configured.
    at http://localhost:8081/node_modules/.vite/deps/chunk-PZK3XFUA.js?v=5a19cc1b:42:11
    at assertTokenProviderConfig (http://localhost:8081/node_modules/.vite/deps/chunk-PZK3XFUA.js?v=5a19cc1b:164:10)
    at signInWithSRP (http://localhost:8081/node_modules/.vite/deps/chunk-PZK3XFUA.js?v=5a19cc1b:10090:3)
    at signIn (http://localhost:8081/node_modules/.vite/deps/chunk-PZK3XFUA.js?v=5a19cc1b:10203:14)
    at async logIn (http://localhost:8081/src/views/SignIn.vue:53:9)
SignIn.vue: Auth UserPool not configured. err
```

![image](https://github.com/aws-amplify/amplify-js/assets/10808157/9d555c8f-eb25-4a57-b47b-b18ebda00de6)

### Expected behavior

`Amplify.configure(amplifyconfig)` working fine.

### Reproduction steps

Amplify.getConfig() only return empty object

![image](https://github.com/aws-amplify/amplify-js/assets/10808157/eab51d1c-546d-4076-b9b7-1948c2e445df)

### Code Snippet

```javascript
// Put your code below this line.

// SignIn.vue
import { Auth } from '@aws-amplify/auth';

    const signIn = async () => {
      try {
        await Auth.signIn(email, password);
        redirectTo();
      } catch (err: any) {
      
      }
    };

// main.ts
import { createApp, h } from 'vue';
import { Amplify } from 'aws-amplify';
import amplifyconfig from './aws-exports.json';

Amplify.configure(amplifyconfig);
console.log('14 awsconfig', amplifyconfig);
console.log('15 Amplify', Amplify);

const currentConfig = Amplify.getConfig();
console.log('18 Amplify.getConfig()', currentConfig);

const app = createApp({
  setup() {
    const { t } = useI18n();

    app.config.globalProperties.$i18nRoute = (to: RouteLocationNormalized): RouteLocationNormalized => ({
      ...to,
      params: { lang: i18n.global.locale.value, ...to.params },
    });
  },
  render() {
    return (h(App));
  },
});

app.use(router);
app.mount('#app');

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello, @natuan62 👋.  I've got a few questions for you to clarify some things within your app and see if we can help unblock you.  Are you importing `amplifyconfig` anywhere in your `main.ts` that was detailed in the code examples above?  Additionally, it appears that there are multiple calls happening for `Amplify.configure`.  Every subsequent call will be overriding the previous, which could be the root cause of the errors that you're experiencing.  Is there any reason why you're calling it so much?

**Comment by natuan62** [comment]
@cwomack Oh my mistake when copy code for a sample

```
// main.ts

import amplifyconfig from './aws-exports.json';
```

Additionally, it appears that there are multiple calls happening for Amplify.configure => Thanks for explain, I'll recheck for it

**Comment by cwomack** [comment]
@natuan62, were you able to recheck for the multiple calls to `Amplify.configure()`? Just wanted to check in and see if you're still blocked by this.

**Comment by natuan62** [comment]
Hi @cwomack I just call Amplify.configure() 1 one time

![image](https://github.com/aws-amplify/amplify-js/assets/10808157/a584060e-4841-451d-a3bd-be788b71bc3e)

And try to move cognito import under Auth field like this https://github.com/aws-amplify/amplify-js/issues/12627#issuecomment-1848214340
But it still return error like i commented before

**Comment by nadetastic** [comment]
Hi @natuan62 following up here, since you are manually configuring your Auth resources to you app, the recommended approach is to nest the resources under `Auth.Cognito` as seen in the documentation here - https://docs.amplify.aws/react/tools/libraries/configure-categories/#authentication-amazon-cognito

An example of how this would look like for you:

```js
Amplify.configure({
  Auth: {
    Cognito: {
      userPoolClientId: 'abcdefghij1234567890',
      userPoolId: 'us-east-1_abcd1234',
      loginWith: { // Optional
        oauth: {
          domain: 'abcdefghij1234567890-29051e27.auth.us-east-1.amazoncognito.com',
          scopes: ['openid email phone profile aws.cognito.signin.user.admin '],
          redirectSignIn: ['http://localhost:3000/','https://example.com/'],
          redirectSignOut: ['http://localhost:3000/','https://example.com/'],
          responseType: 'code',
        },
        username: 'true',
        email: 'false',
        phone: 'false',
      }
    }
  }
});
```

Could you try with this setup and let us know if you are still having issues?

**Comment by natuan62** [comment]
Hi @nadetastic 

Seem in old aws-export with amplify v5, my **userPoolClientId** field is **userPoolWebClientId**.
And when I changed userPoolWebClientId to userPoolClientId, it works !

And when i try 3 ways, all of them works

// 1
```
Amplify.configure({
  Auth: {
    Cognito: {
      userPoolClientId: '1',
      userPoolId: 'us-west-2',
      identityPoolId: 'us-west-2:',
    },
  },
});
```

// 2
```
import amplifyconfig from './aws-exports.json';

Amplify.configure(amplifyconfig);
```

// 3
```
import awsconfig from './aws-exports'; // is js file like const awsmobile = { } ... export default awsconfig;

Amplify.configure(awsconfig);
```

**Comment by Not-Qualified** [comment]
We have face this similar issue and we have resolved it by removing duplicate entry of aws-amplify library was there as we had multiple package.json files
