### ISSUE TITLE
SSR getCredentialsForIdentity not caching between requests resulting in 400:TooManyRequestsException from Cognito

### ISSUE THREAD

**Issue by BmjEarhart** [aws-amplify/amplify-js#12839]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

GraphQL API, Storage

### Amplify Version

v6

### Amplify Categories

storage, api

### Backend

Amplify CLI

### Environment information

<details>

```
# Put output below this line

  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 117.28 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 21.2.0 - ~/.nvm/versions/node/v21.2.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v21.2.0/bin/npm
  Browsers:
    Chrome: 120.0.6099.216
    Edge: 120.0.2210.121
    Safari: 16.2
  npmPackages:
    @ampproject/toolbox-optimizer:  undefined ()
    @aws-amplify/adapter-nextjs: ^1.0.10 => 1.0.11 
    @aws-amplify/adapter-nextjs/api:  undefined ()
    @aws-amplify/adapter-nextjs/data:  undefined ()
    @aws-amplify/ui-react: ^6.0.1 => 6.0.1 
    @aws-amplify/ui-react-internal:  undefined ()
    @babel/core:  undefined ()
    @babel/runtime:  7.22.5 
    @edge-runtime/cookies:  4.0.2 
    @edge-runtime/ponyfill:  2.4.1 
    @edge-runtime/primitives:  4.0.2 
    @emotion/cache: ^11.11.0 => 11.11.0 
    @emotion/react: ^11.11.1 => 11.11.1 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @hapi/accept:  undefined ()
    @mswjs/interceptors:  undefined ()
    @mui/icons-material: ^5.14.18 => 5.14.18 
    @mui/lab: ^5.0.0-alpha.153 => 5.0.0-alpha.153 
    @mui/material: ^5.14.18 => 5.14.18 
    @mui/material-nextjs: ^5.15.0 => 5.15.0 
    @napi-rs/triples:  undefined ()
    @next/font:  undefined ()
    @next/react-dev-overlay:  undefined ()
    @opentelemetry/api:  undefined ()
    @segment/ajv-human-errors:  undefined ()
    @types/node: ^20 => 20.9.0 
    @types/react: ^18 => 18.2.37 
    @types/react-dom: ^18 => 18.2.15 
    @vercel/nft:  undefined ()
    @vercel/og:  0.5.15 
    acorn:  undefined ()
    amphtml-validator:  undefined ()
    anser:  undefined ()
    arg:  undefined ()
    assert:  undefined ()
    async-retry:  undefined ()
    async-sema:  undefined ()
    aws-amplify: ^6.0.10 => 6.0.11 
    aws-amplify/adapter-core:  undefined ()
    aws-amplify/analytics:  undefined ()
    aws-amplify/analytics/kinesis:  undefined ()
    aws-amplify/analytics/kinesis-firehose:  undefined ()
    aws-amplify/analytics/personalize:  undefined ()
    aws-amplify/analytics/pinpoint:  undefined ()
    aws-amplify/api:  undefined ()
    aws-amplify/api/server:  undefined ()
    aws-amplify/auth:  undefined ()
    aws-amplify/auth/cognito:  undefined ()
    aws-amplify/auth/cognito/server:  undefined ()
    aws-amplify/auth/enable-oauth-listener:  undefined ()
    aws-amplify/auth/server:  undefined ()
    aws-amplify/datastore:  undefined ()
    aws-amplify/in-app-messaging:  undefined ()
    aws-amplify/in-app-messaging/pinpoint:  undefined ()
    aws-amplify/push-notifications:  undefined ()
    aws-amplify/push-notifications/pinpoint:  undefined ()
    aws-amplify/storage:  undefined ()
    aws-amplify/storage/s3:  undefined ()
    aws-amplify/storage/s3/server:  undefined ()
    aws-amplify/storage/server:  undefined ()
    aws-amplify/utils:  undefined ()
    babel-packages:  undefined ()
    browserify-zlib:  undefined ()
    browserslist:  undefined ()
    buffer:  undefined ()
    bytes:  undefined ()
    ci-info:  undefined ()
    cli-select:  undefined ()
    client-only:  0.0.1 
    comment-json:  undefined ()
    compression:  undefined ()
    conf:  undefined ()
    constants-browserify:  undefined ()
    content-disposition:  undefined ()
    content-type:  undefined ()
    cookie:  undefined ()
    cross-spawn:  undefined ()
    crypto-browserify:  undefined ()
    css.escape:  undefined ()
    data-uri-to-buffer:  undefined ()
    date-fns: ^3.0.6 => 3.0.6 
    debug:  undefined ()
    devalue:  undefined ()
    domain-browser:  undefined ()
    edge-runtime:  undefined ()
    events:  undefined ()
    find-cache-dir:  undefined ()
    find-up:  undefined ()
    formik: ^2.4.5 => 2.4.5 
    fresh:  undefined ()
    get-orientation:  undefined ()
    glob:  undefined ()
    gzip-size:  undefined ()
    http-proxy:  undefined ()
    http-proxy-agent:  undefined ()
    https-browserify:  undefined ()
    https-proxy-agent:  undefined ()
    icss-utils:  undefined ()
    ignore-loader:  undefined ()
    image-size:  undefined ()
    is-animated:  undefined ()
    is-docker:  undefined ()
    is-wsl:  undefined ()
    jest-worker:  undefined ()
    json5:  undefined ()
    jsonwebtoken:  undefined ()
    loader-runner:  undefined ()
    loader-utils:  undefined ()
    lodash.curry:  undefined ()
    lru-cache:  undefined ()
    micromatch:  undefined ()
    mini-css-extract-plugin:  undefined ()
    nanoid:  undefined ()
    native-url:  undefined ()
    neo-async:  undefined ()
    next: 14.0.2 => 14.0.2 
    node-fetch:  undefined ()
    node-html-parser:  undefined ()
    notistack: ^3.0.1 => 3.0.1 
    ora:  undefined ()
    os-browserify:  undefined ()
    p-limit:  undefined ()
    path-browserify:  undefined ()
    platform:  undefined ()
    postcss-flexbugs-fixes:  undefined ()
    postcss-modules-extract-imports:  undefined ()
    postcss-modules-local-by-default:  undefined ()
    postcss-modules-scope:  undefined ()
    postcss-modules-values:  undefined ()
    postcss-preset-env:  undefined ()
    postcss-safe-parser:  undefined ()
    postcss-scss:  undefined ()
    postcss-value-parser:  undefined ()
    process:  undefined ()
    punycode:  undefined ()
    querystring-es3:  undefined ()
    raw-body:  undefined ()
    react: ^18 => 18.2.0 
    react-builtin:  undefined ()
    react-device-detect: ^2.2.3 => 2.2.3 
    react-dom: ^18 => 18.2.0 
    react-dom-builtin:  undefined ()
    react-dom-experimental-builtin:  undefined ()
    react-experimental-builtin:  undefined ()
    react-is:  18.2.0 
    react-phone-number-input: ^3.3.8 => 3.3.8 
    react-phone-number-input/commonjs:  undefined ()
    react-phone-number-input/core:  undefined ()
    react-phone-number-input/flags:  undefined ()
    react-phone-number-input/input-core:  undefined ()
    react-phone-number-input/input-max:  undefined ()
    react-phone-number-input/input-min:  undefined ()
    react-phone-number-input/input-mobile:  undefined ()
    react-phone-number-input/max:  undefined ()
    react-phone-number-input/min:  undefined ()
    react-phone-number-input/mobile:  undefined ()
    react-phone-number-input/react-hook-form:  undefined ()
    react-phone-number-input/react-hook-form-core:  undefined ()
    react-phone-number-input/react-hook-form-input:  undefined ()
    react-phone-number-input/react-hook-form-input-core:  undefined ()
    react-phone-number-input/react-native-input:  undefined ()
    react-phone-number-input/react-styleguidist:  undefined ()
    react-query: ^3.39.3 => 3.39.3 
    react-refresh:  0.12.0 
    react-server-dom-turbopack-builtin:  undefined ()
    react-server-dom-turbopack-experimental-builtin:  undefined ()
    react-server-dom-webpack-builtin:  undefined ()
    react-server-dom-webpack-experimental-builtin:  undefined ()
    recoil: ^0.7.7 => 0.7.7 
    regenerator-runtime:  0.13.4 
    sass-loader:  undefined ()
    scheduler-builtin:  undefined ()
    scheduler-experimental-builtin:  undefined ()
    schema-utils:  undefined ()
    semver:  undefined ()
    send:  undefined ()
    server-only:  0.0.1 
    setimmediate:  undefined ()
    shell-quote:  undefined ()
    source-map:  undefined ()
    stacktrace-parser:  undefined ()
    stream-browserify:  undefined ()
    stream-http:  undefined ()
    string-hash:  undefined ()
    string_decoder:  undefined ()
    strip-ansi:  undefined ()
    superstruct:  undefined ()
    swiper: ^11.0.5 => 11.0.5 
    tar:  undefined ()
    terser:  undefined ()
    text-table:  undefined ()
    timers-browserify:  undefined ()
    tty-browserify:  undefined ()
    typescript: ^5 => 5.2.2 
    ua-parser-js:  undefined ()
    unistore:  undefined ()
    util:  undefined ()
    vm-browserify:  undefined ()
    watchpack:  undefined ()
    web-vitals:  undefined ()
    webpack:  undefined ()
    webpack-sources:  undefined ()
    ws:  undefined ()
    yup: ^1.3.2 => 1.3.2 
    zod:  undefined ()
  npmGlobalPackages:
    @aws-amplify/cli: 11.1.1
    corepack: 0.23.0
    npm: 10.2.3

```

</details>

### Describe the bug

This behaviour presents for us upon large SSR page loads that require multiple graphQL / storage requests. 

It seems that for each request that is made server-side, the server attempts to get credentials for the Cognito User via @aws-amplify/auth/dist/esm/providers/cognito/credentialsProvider/credentialsProvider.js. This generally works, but gets throttled at higher volumes (I estimate ~50 request/s in a short burst) as the credentials fail to be cached. See below for stack trace.

credentialsProvider does have caching logic built in (see _credentialsAndIdentityId) but it seems that the same instance of credentialsProvider is not used between multiple requests. I've confirmed this on a local run by adding debug statements in the credentialsProvider.

We see similar behaviour for our Appsync API requests, omitting that log for brevity.

It's possible there is a problem in our setup so I'm including our client code and configuration - I believe we are configured in accordance with [the docs here](https://docs.amplify.aws/javascript/build-a-backend/server-side-rendering/nextjs/). There is documentation that makes explicit mention of injecting token/credentials providers to the amplifyServerContext [here](https://docs.amplify.aws/javascript/build-a-backend/server-side-rendering/), but as far as I can tell that's using a lower level SSR features that are not currently available (aws-amplify/adapter-core).

### Expected behavior

Cognito credentials should be cached between requests and allow for a higher volume of requests from the server to S3 / Appsync when generating pages.

### Reproduction steps

1) Configure amplify project as has been done below
2) Make a large number of storage.getUrl requests in a loop
3) If running locally, easy to verify that credentialsProvider is not caching with a debug line in the constructor

### Code Snippet

```javascript
// Put your code below this line.

// Amplify configuration
'use client';

import { Amplify } from 'aws-amplify';
import config from '@/aws-exports';

Amplify.configure(config, { ssr: true });

//RunWithAmplifyServerContext 
import config from '@/aws-exports';
import { createServerRunner } from '@aws-amplify/adapter-nextjs';

export const { runWithAmplifyServerContext } = createServerRunner({
    config
});

// Storage DAO (this is what we call multiple times in parallel to fetch s3 resources)

import { StorageDAO } from "../storage/StorageDAO";
import { cookies } from "next/headers";
import { getUrl } from "aws-amplify/storage/server";
import { runWithAmplifyServerContext } from "./runWithAmplifyServerContext";


private async getFileUrl(key: string): Promise<URL> {
        return await runWithAmplifyServerContext({
            nextServerContext: { cookies },
            operation: async (contextSpec) => {
                try {
                    console.log("Getting file url for key", key, "with context", contextSpec)
                    const storageGetUrlOutput = await getUrl(
                        contextSpec,
                        { key }
                    );
                    return storageGetUrlOutput.url;
                } catch (error) {
                    console.error(error);
                    throw new Error(`Error getting file url for key ${key}`);
                }
            }
        });
    }

```

### Log output

<details>

```
// Put your logs below this line


TooManyRequestsException: Rate exceeded
    at parseJsonError (webpack-internal:///(rsc)/./node_modules/@aws-amplify/core/dist/esm/clients/serde/json.mjs:28:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getCredentialsForIdentityDeserializer (webpack-internal:///(rsc)/./node_modules/@aws-amplify/core/dist/esm/awsClients/cognitoIdentity/getCredentialsForIdentity.mjs:28:23)
    at async eval (webpack-internal:///(rsc)/./node_modules/@aws-amplify/core/dist/esm/clients/internal/composeServiceApi.mjs:23:16)
    at async CognitoAWSCredentialsAndIdentityIdProvider.credsForOIDCTokens (webpack-internal:///(rsc)/./node_modules/@aws-amplify/auth/dist/esm/providers/cognito/credentialsProvider/credentialsProvider.mjs:129:30)
    at async AuthClass.fetchAuthSession (webpack-internal:///(rsc)/./node_modules/@aws-amplify/core/dist/esm/singleton/Auth/index.mjs:36:40)
    at async resolveS3ConfigAndInput (webpack-internal:///(rsc)/./node_modules/@aws-amplify/storage/dist/esm/providers/s3/utils/resolveS3ConfigAndInput.mjs:27:41)
    at async getUrl (webpack-internal:///(rsc)/./node_modules/@aws-amplify/storage/dist/esm/providers/s3/apis/internal/getUrl.mjs:50:45)
    at async operation (webpack-internal:///(rsc)/./src/utils/server/ServerStorageDAO.ts:46:49)
    at async runWithAmplifyServerContext (webpack-internal:///(rsc)/./node_modules/aws-amplify/dist/esm/adapterCore/runWithAmplifyServerContext.mjs:23:24)
    at async ServerStorageDAO.getFileUrl (webpack-internal:///(rsc)/./src/utils/server/ServerStorageDAO.ts:39:16)
    at async ServerStorageDAO.getFileAsJson (webpack-internal:///(rsc)/./src/utils/server/ServerStorageDAO.ts:33:25
```

</details>

**Comment by HuiSF** [comment]
Hi @BmjEarhart, thanks for reaching out.

You are correct that the credentials are not being cached between requests.

The Amplify library API operations on the server side are supposed to be stateless. They initialize resources to function per request when you call `runWithAmplifyServerContext` and destroy everything when the request completes to avoid cross-request state pollution.

Looking at the code example and your use case description (`getUrl` is using the `guest` access level), have you tried combining multiple operations into one to run in a context? For example, you were saying:

>Make a large number of storage.getUrl requests in a loop

You can alternatively do the following:
> NOTE: this is a simple example, you may need to alter according to your own use case.
```ts
private async getFileUrl(keys: string[]): Promise<URL[]> {
    return runWithAmplifyServerContext({
        nextServerContext: { cookies },
        operation: async (contextSpec) => {
            try {
                const results = await Promise.all(
                    keys.map(key => getUrl(
                        contextSpec,
                        { key }
                    ))
                )
                return results.map(result => result).url;
            } catch (error) {
                console.error(error);
                throw new Error(`Error getting file url for key ${key}`);
            }
        }
    });
}
```

With this, the `getUrl` gets called multiple times in the same context, which contains the cached credentials.

**Comment by BmjEarhart** [comment]
Ah, interesting, thank you for the information! So we can work around this by essentially building batch operations into our SSR S3 data fetching operations. 

However this problem also applies to our AppSync APIs, where we use a client built from 'generateServerClientUsingCookies'. It seems that each request  via this client also follows the same behaviour and fetches cognito credentials per-request. I believe roughly aligned with documentation [found here](https://docs.amplify.aws/gen2/build-a-backend/data/connect-from-server-runtime/)

For illustration, see this code

```
// serverClient

import config from '@/aws-exports';
import { cookies } from 'next/headers';
import { generateServerClientUsingCookies } from '@aws-amplify/adapter-nextjs/api';

export const cookieBasedClient = generateServerClientUsingCookies({
    config,
    cookies
});

// Foo DAO

    public async get(id: string) {
        try {
            const authToken = await this.authTokenProvider.get(); //in our stack this also goes through runWithAmplifyServerContext
            const variables: GetFooQueryVariables = {
                id
            }
           //This request spins up a new server context
            const result = await cookieBasedClient.graphql({
                query: getFoo,
                variables,
                authToken
            }) as GraphQLResult<GetFooQuery>;
            return result.data?.getFoo as Foo;
        } catch (error) {
            console.error(error);
            throw new Error(`Error getting foo ${id}`);
        }
    }

```
This seems to spin up a Server context (and query cognito credentials) per-request through the client from generateServerClientUsingCookies. So we're pinging cognito for each GraphQL request, right?

Now, our setup is using custom auth tokens created server-side via runWithAmplifyServerContext, which exacerbates the problem, but really only by 2x if I'm understanding things correctly.

Is there a similar way to batch this kind of request to avoid spamming Cognito from SSR? Or are we stuck with one server context spin-up per appsync query?

**Comment by HuiSF** [comment]
Hi @BmjEarhart Sorry for the delay. This "rate limit" needs to be lifted on the service side, but before that, I'd like to learn more details about your setup; there may be a chance that can be optimized further.

Could you provide more details about this function, `this.authTokenProvider.get()`? E.g., which Amplify API it calls. In addition, what's the reason you need to supply the `authToken` parameter in the call to `cookieBasedClient.graphql()`?

**Comment by BmjEarhart** [comment]
No worries. We've been able to optimize our way out of this by shifting the heavy-lifting to client side, so it's not a burning question. 

With that said, this thread might be useful for future devs running into similar problems so let me just dump our observations here and finish up the thread.

Regarding authTokenProvider, specifically it's in part calling fetchAuthSession from "aws-amplify/auth/server". It's an implementation detail specific to us which we could probably improve on but for now I can say it exacerbates the problem by also making an additional Cognito request on top of the one made by our GQL query, but isn't the root cause here in and of itself.

The core limitation is that server side operations that require cognito auth such as S3 and AppSync/GQL queries can be bottlenecked by the fetching of cognito Credentials which is done per request. The best ways we've found to work around it is by batching these operations, either with custom batch GQL queries or by batching the S3 requests as you've shown us above. This way you can at least fetch multiple resources with less server contexts.

Then of course we improved on this by shifting the heavy lifting to client side where one is able to rely on the caching mechanism in CognitoAWSCredentialsAndIdentityIdProvider, so cognito isn't queried per-request.

Unless there's a way to batch multiple distinct GQL requests under the same server context, I don't think there's much else to say here. Maybe it's worth calling out in the docs since it is a little hard to grok where and why the throttling is coming from, but we personally aren't blocked by this any more. Thanks again for your help on the topic!

**Comment by HuiSF** [comment]
Thanks for the great details, @BmjEarhart, and letting me know about your strategy for moving some of the request onto the client side. I'm glad to hear that batching the API calls within one server context helped partially solve the problem.

I agree, this is a service limitation that cannot be avoided, as the adapter implementation is meant to be stateless. I've created an action item to call this out on the documentation site and started working on it. In addition, the rate limits defined on the Cognito service side are mostly adjustable according to the demands. See [this document](https://docs.aws.amazon.com/cognito/latest/developerguide/limits.html#amazon-cognito-identity-pools-federated-identities-request-rate-quotas) for details.

Following up on this point:

>Unless there's a way to batch multiple distinct GQL requests under the same server context,

This is true when the distinct GQL requests are based on different user sessions. Is this the case for you?

**Comment by festusyuma** [comment]
Hi @HuiSF I have a server client defined as

```
export const serverClient = generateServerClientUsingCookies<Schema>({
  config,
  cookies,
  authMode: 'userPool',
});
```

and a server action which runs multiple request in a loop as 

```
  for (const data of questions) {
    const questionRes = await serverClient.models.Question.create({
      id: data.id,
      excerpt: data.content ?? '',
      complexity: (data.complexity?.[0] as QuestionComplexityType) ?? 'EASY',
      topic: data.topic ?? '',
      questionGradeId: data.grade,
      questionSubjectId: data.subject,
    });

    console.log({ questionError: questionRes.errors });

    if (questionRes?.data?.id) {
      await serverClient.models.QuestionLanguage.create({
        id: `${questionRes.data?.id}-eng-us`,
        content: data.content ?? '',
        questionLanguageLanguageId: 'eng-us',
        optionValues: data.optionValues ?? [],
        correctOptionValue: data.correctOptionValue ?? '',
        questionLanguagesId: data.id,
      });
    }
  }
```

but I get hit with a too many request error and it seems each of these request calls cognito. my question is. since these queries happen in a single function, how do I tell it to use one auth context

I tried using this below
```
// declared in another file
function withServer<T>(
  operation: (ctx: AmplifyServer.ContextSpec) => Promise<T>
) {
  return serverContext({
    nextServerContext: { cookies },
    operation,
  });
}

const client = generateServerClientUsingReqRes<Schema>({ config });

// server action function
await withServer(async (ctx) => {
    for (const data of questions) {
      const questionRes = await client.models.Question.create(ctx, {
        id: data.id,
        excerpt: data.content ?? '',
        complexity: (data.complexity?.[0] as QuestionComplexityType) ?? 'EASY',
        topic: data.topic ?? '',
        questionGradeId: data.grade,
        questionSubjectId: data.subject,
      });

      console.log({ questionError: questionRes.errors });

      if (questionRes?.data?.id) {
        await client.models.QuestionLanguage.create(ctx, {
          id: `${questionRes.data?.id}-eng-us`,
          content: data.content ?? '',
          questionLanguageLanguageId: 'eng-us',
          optionValues: data.optionValues ?? [],
          correctOptionValue: data.correctOptionValue ?? '',
          questionLanguagesId: data.id,
        });
      }
    }
  });
```

 but I get unauthorized. my question is, is it possible to achieve something like this, or would I have to use a custom mutation

**Comment by HuiSF** [comment]
Hi @festusyuma The `generateServerClientUsingCookies` function creates the client, and underlying it calls runWithAmplifyServerContext with each query and mutation to create a context that fetches credentials.

Your intention is correct to use `generateServerClientUsingReqRes` instead, but you may need some adjustments. A more generic version of `generateClient` is exported from `aws-amplify/api/server`. See [this document](https://docs.amplify.aws/javascript/build-a-backend/server-side-rendering/#supported-apis-for-server-side-usage) for details.

Here's the pseudo code refactoring based on your thoughts:

```ts
import { generateClient } from 'aws-amplify/api/server';
import { parseAmplifyConfig } from 'aws-amplify/utils';
import { cookies } from 'next/headers';

import config from '@/amplifyconfiguration.json';

// an extra required step to parse the config object
const amplifyConfig = parseAmplifyConfig(config);

const client = generateClient<Schema>({ config: amplifyConfig });

async function myServerAction(formData: FormData) {
  runWithAmplifyServerContext({
    nextServerContext: { cookies },
    operation: (contextSpec) => {
      // the for loop is running within the same context
      for (const data of questions) {
        const questionRes = await client.models.Question.create(contextSpec, {...});
        if (questionRes?.data?.id) {
          await client.models.QuestionLanguage.create(contextSpec, {...});
        }
      }
    }
  })
}
```

Could you give it a try and let us know if you run into any issues?

**Comment by festusyuma** [comment]
Hi @HuiSF . Thank you. this is actually what I initally wanted to try but couldn't get the config to show up as valid, what I was mising was the `parseAmplifyConfig ` function. I went ahead and created a custom mutation but I'll also try this out to see if it works. Thanks again

**Comment by festusyuma** [comment]
It worked @HuiSF . Thank you. but I think I might stick with the custom mutations since I only make 1 request to dynamo DB. but the server actions are easier to update and test. guess that's something I'll need to think about

**Comment by cwomack** [comment]
We'll close this issue with @festusyuma and @BmjEarhart seemingly unblocked. Thank you for the assistance @HuiSF!
