### ISSUE TITLE
How to remove confirmSignUp page after registering new user.

### ISSUE THREAD

**Issue by Jeet007das** [aws-amplify/amplify-js#12837]
Hi, I don't want the confirm sign-up page when I am onboarding a new user, because I am implementing a verification email link to verify the user. I am using aws-amplify v6 , wrapping my main app.

**Comment by israx** [comment]
Hello @Jeet007das . You can enable `autoSignIn` via the [signUp](https://docs.amplify.aws/react/build-a-backend/auth/enable-sign-up/#sign-up) API, and set the `signUpVerificationMethod` to `link` in your configuration. e.g { signUpVerificationMethod:'link'} . Then you would need to call the [autoSignIn](https://docs.amplify.aws/react/build-a-backend/auth/enable-sign-up/#auto-sign-in) API after calling signUp

**Comment by cwomack** [comment]
@Jeet007das, can you let us know if the [comment above](https://github.com/aws-amplify/amplify-js/issues/12837#issuecomment-1887856058) helps clarify how to accomplish what you're looking for here related to the "confirm sign up" page? Thanks!
