### ISSUE TITLE
Refresh the access token without reloading the tab

### ISSUE THREAD

**Issue by mrSingh007** [aws-amplify/amplify-js#12832]
### Is this related to a new or existing framework?

Angular

### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

currently when session is expired the 'fetchAuthSession' in version-6 or any method in version-5 either returning undefined, is url does not contain token value or reloading the page (so basically going to AWS cognito hosted ui and coming back to redirect URL).

This is very unfriendly for user as user loosing his data when page reloads. So there should be a method, which should get new access token without reloading the page.

### Describe the solution you'd like

there is signInSilently method should be introduces that always refresh the access token, if it expired. (so same like fetchAuthSession but without any redirects)

### Describe alternatives you've considered

When access token expires

Option 1: Hub should dispatch event and a method can be called to get new token without redirects

Option 2: signInSilently should check if token expire and return the new one after refreshing it. 

### Additional context

Currently we are stuck at this point, as user loosing data with redirect. Version-6 is not stable and version-5 don't have any method that can help to refresh the access token on hosted cognito ui.

Redirect URL which are configured on AWS cognito, also don't accept regex/wildcard sothat after redirect user can be brought to same page.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cwomack** [comment]
Hello, @mrSingh007 and thanks for opening this.  It sounds like this is a feature request surrounding token expiration and renewal, specifically to allow for "silent" refreshes in the background so that users don't have to sign-in again (and no loss of data).  Is that pretty close to what you're looking for? Or are you looking for guidance more specifically on how to handle when the `fetchAuthSession` API in v6 returns undefined when session is expired?

**Comment by israx** [comment]
@mrSingh007 we currently added [documentation](https://docs.amplify.aws/react/build-a-backend/auth/manage-user-session/#refreshing-sessions-with-social-providers) on how to refresh a session while using a social provider.

**Comment by mrSingh007** [comment]
@cwomack correct, what you have written
@israx if using flow with 'code' instead of 'token', still there should be method like 'refreshSession' or 'silentLogin' which should take 'refresh_token' and should return new access_token. 
But there is no such a method

**Comment by israx** [comment]
using a `code` OAuth flow for authentication will generate a `refresh_token`, then the Amplify library is able to automatically refresh tokens. If you want to force refresh the session you can call the `fetchAuthSession` with the `forceRefresh` flag enabled.

**Comment by mrSingh007** [comment]
@israx when i use `code` flow and do loginWithRedirect, after logging in on cognito, direct is done on 'redirectUrl' and 'code' and 'state' can be seen on URL BUT fetchAuthSession still gives error that user is not authorized/loggedIn. 
According to the login flow, code should be authorized and exchanged against 'refresh' and 'access' token. BUT to do this step, there is no such a method.

Steps (with code flow):
Navigate to http://localhost:4200 (method loginWithRedirect called)
Redirect happen to cognito, user fills the login data.
Redirect brings user back to http://localhost:4200
User is still not logged In and no method giving access or refresh token<==

If these steps are done with 'token' flow, then user is indeed logged in but then there is no way to get access token with redirect again.

**Comment by mrSingh007** [comment]
it was issue with client configuration. Now i am getting tokens from authSession

**Comment by mrSingh007** [comment]
The issue was mis.configured AWS config. Its working now as expected.  Auth flow must be with 'code' and client_secret must be also kept in mind

**Comment by Steven-sdx** [comment]
The docs list this warning:
> Warning: by default, sessions from external identity providers cannot be refreshed.

To clarify, if we have a SAML federated identity provider through our cognito user pool will the authToken refresh with responseType: code or is there something we need to do to manually refresh it?

**Comment by theewl** [comment]
@Steven-sdx doesnt seem to be refreshing for me with responseType: code
