### ISSUE TITLE
v1.0.2 Runtime error with @types/zen-observale:  error TS2300: Duplicate identifier 'Subscriber'.

### ISSUE THREAD

**Issue by XCarle** [aws-amplify/amplify-js#1284]
Problem with npm dependencies.

I tried some npm dedupe which did not fix the problem. 

I think the Subscriber is defined in rxjs.

**Comment by rayhaanq** [comment]
I've got the same issue

**Comment by ajhool** [comment]
Unable to run a server created with create-react-app due to this bug. This bug was also seen in ApolloGraphQL:

https://github.com/apollographql/apollo-link/pull/623

and there is an effort by @types/zen-observable to resolve it from within the zen-observable types library:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26239#issuecomment-395925181

**Comment by SudduK** [comment]
Thanks @XCarle. I ran into similar issue like below 
_node_modules\@aws-amplify\pubsub\node_modules\@types\zen-observable\index.d.ts (32,14): error TS2300: Duplicate identifier 'Subscriber'._

I tried **npm dedupe** that worked for me.
Before running **npm dedupe**, ran the **npm find-dupes** and found the below changes are being made 

_remove  @types/zen-observable   0.5.4   node_modules\@aws-amplify\pubsub\node_modules\@types\zen-observable
move    @types/zen-observable   0.5.4   node_modules\@types\zen-observable        node_modules\@aws-amplify\api\node_modules\@types\zen-observable_

**Comment by jordanranz** [comment]
@XCarle,

Are you still experiencing this issue?

**Comment by cheeks** [comment]
@jordanranz I am. I've tried *npm dedupe* but to no avail. Any other ideas?

**Comment by amaingot** [comment]
Is anything happening with this issue? Looks like it is still happening for me too. I'm on v1.1.23.

**Comment by elorzafe** [comment]
@cheeks @amaingot can you paste your `package.json` to try to reproduce the problem.

**Comment by alebiavati** [comment]
Closing issue as inactive, please open another issue with more details if you still need support.

**Comment by adamfoerster** [comment]
I'm getting this error too. I'm trying to use amplify with my Angular app. This is my package.json
--
{
  "name": "udm",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "gql": "graphql-codegen --config codegen.yml"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~7.2.14",
    "@angular/cdk": "~7.3.7",
    "@angular/common": "~7.2.14",
    "@angular/compiler": "~7.2.14",
    "@angular/core": "~7.2.14",
    "@angular/forms": "~7.2.14",
    "@angular/http": "~7.2.14",
    "@angular/platform-browser": "~7.2.14",
    "@angular/platform-browser-dynamic": "~7.2.14",
    "@angular/pwa": "^0.13.9",
    "@angular/router": "~7.2.14",
    "@angular/service-worker": "~7.2.14",
    "@herodevs/lazy-af": "0.0.8",
    "@nebular/auth": "^4.0.0-beta.0",
    "@nebular/eva-icons": "4.0.0-beta.0",
    "@nebular/theme": "^4.0.0-beta.0",
    "animate.css": "^3.7.0",
    "apollo-angular": "^1.5.0",
    "apollo-angular-link-http": "^1.6.0",
    "apollo-cache-inmemory": "^1.5.1",
    "apollo-client": "^2.5.1",
    "apollo-link-error": "^1.1.10",
    "aws-amplify": "^1.1.27",
    "aws-amplify-angular": "^3.0.2",
    "core-js": "^3.0.1",
    "dayjs": "^1.8.14",
    "eslint": "^5.16.0",
    "eslint-config-airbnb-base": "^13.1.0",
    "eslint-config-prettier": "^4.2.0",
    "eslint-plugin-import": "^2.17.2",
    "eslint-plugin-prettier": "^3.0.1",
    "eva-icons": "^1.1.1",
    "graphql": "^14.3.0",
    "graphql-tag": "^2.10.1",
    "ng2-completer": "^2.0.8",
    "ng2-smart-table": "^1.4.0",
    "ngx-auto-unsubscribe": "^3.0.0",
    "prettier": "^1.17.0",
    "rxjs": "~6.5.1",
    "rxjs-compat": "^6.5.1",
    "tslint-config-prettier": "^1.18.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.13.9",
    "@angular/cli": "~7.3.9",
    "@angular/compiler-cli": "~7.2.14",
    "@angular/language-service": "~7.2.14",
    "@graphql-codegen/fragment-matcher": "1.1.3",
    "@graphql-codegen/introspection": "^1.1.3",
    "@graphql-codegen/typescript": "1.1.3",
    "@graphql-codegen/typescript-apollo-angular": "1.1.3",
    "@graphql-codegen/typescript-graphql-files-modules": "1.1.3",
    "@graphql-codegen/typescript-operations": "1.1.3",
    "@schematics/angular": "~7.3.9",
    "@types/jasmine": "~3.3.12",
    "@types/jasminewd2": "~2.0.6",
    "@types/node": "^11.13.10",
    "apollo-codegen": "^0.20.2",
    "codelyzer": "~5.0.1",
    "graphql-codegen-introspection": "^0.18.1",
    "graphql-codegen-typescript-apollo-angular": "^0.18.1",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.5",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.2",
    "ts-node": "~8.1.0",
    "tslint": "^5.16.0",
    "typescript": "^3.2.4"
  }
}
