### ISSUE TITLE
DataStore Query Performance Very Slow on Expo React Native App

### ISSUE THREAD

**Issue by Oyetayo** [aws-amplify/amplify-js#12848]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

GraphQL API, DataStore

### Amplify Version

v5

### Amplify Categories

api

### Backend

Amplify CLI

### Environment information

Pls, can someone help me out with this:

I've been encountering slow query performance in my app's AWS Amplify DataStore since it started getting more usage. Despite my efforts to troubleshoot, I've done pagination, cached data, and all and haven't been able to find a solution. Simple operation like updating data takes up to 30 minutes. Here are the dependencies I'm currently using:

"@aws-amplify/datastore-storage-adapter": "^2.0.30",
"@react-native-async-storage/async-storage": "1.17.11",
"aws-amplify": "^5.3.14",
"expo": "~48.0.15",

Thanks in anticipation of a response.

### Reproduction steps

Datastore query

### Code Snippet

 const original = await DataStore.query(Myguests, visitorId);
      await DataStore.save(
        Guests.copyOf(original, (myUpdate) => {
          myUpdate.status = true;
          myUpdate.timeIn = String(checkInTime);
        })
      );

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello, @Oyetayo 👋 and sorry to hearing you're experiencing this.  

- Have a few questions to see if we can't help clarify what's happening here.  
- Can you clarify if this is only happening on your initial sync?  
- What is the total number of records in the DynamoDB table that is backing the API?  
- Can you share you schema? 
- When you say that updating data is taking a long time, do you mean to be available locally, visible on your backend in the DB's table, or on another device?

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
