### ISSUE TITLE
Upgrading from v5 to v6 Error Code when trying to call graphQL api: [TypeError: Cannot read property 'getConfig' of undefined]

### ISSUE THREAD

**Issue by ChristopherGabba** [aws-amplify/amplify-js#12855]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

20.7

### Amplify CLI Version

12.5.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I upgraded v5 to v6 amplify per the docs here: 

https://docs.amplify.aws/react/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/ 

Followed the instructions exactly. 

### Describe the bug

Any time I try to run a graphql operation, for example: 
``` typescript
const { graphql } = generateClient()
const userQueryResults = await graphql({ query: listUsers, variables: listUserQueryInput })
```

I get the following error: 

[TypeError: Cannot read property 'getConfig' of undefined]

### Expected behavior

It should properly fetch the data from my dynamodb table

### Reproduction steps

1. Follow the steps laid out in guide:
 Changing configuration in App.js:
``` 
import { Amplify } from 'aws-amplify';
// import awsExports from './app/aws-exports';  NO LONGER IN USE IN V6
import amplifyconfig from './amplifyconfiguration.json'

const libraryOptions = {
  Storage: {
    S3: {
      prefixResolver: async ({ accessLevel, targetIdentityId }) => {
        if (accessLevel === 'guest') {
          return 'public/';
        } else if (accessLevel === 'protected') {
          return `protected/${targetIdentityId}/`;
        } else {
          return `private/${targetIdentityId}/`;
        }
      }
    }
  }
};


Amplify.configure(amplifyconfig, libraryOptions); // USED TO BE Amplify.configure(awsExports)
```
3. Modify all graphql queries from old nomenclature to new:
```typescript
/* OLD: Worked fine in v5 */
import { API } from "aws-amplify"
const response = await API.graphql(graphqloperation(listUsers, listUsersInput))

/* NEW: Not working in v6 */
import { listUsers } from "app/services/api/AWS/graphql/queries"
import { generateClient } from "aws-amplify/api"

const { graphql } = generateClient()
const userQueryResults = await graphql({ query: listUsers, variables: listUserQueryInput })
```

### Project Identifier

c8bc6e450011067eeb6e35e2f72f878f

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

Here is my amplifyconfiguration.json:
```
{
  "aws_project_region": "us-east-1",
  "aws_appsync_graphqlEndpoint": *REDACTED*,,
  "aws_appsync_region": "us-east-1",
  "aws_appsync_authenticationType": "API_KEY",
  "aws_appsync_apiKey": *REDACTED*,
  "aws_cognito_identity_pool_id": *REDACTED*,
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": *REDACTED*,,
  "aws_user_pools_web_client_id": *REDACTED*,,
  "oauth": {},
  "aws_cognito_username_attributes": [],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [
    "GIVEN_NAME",
    "FAMILY_NAME",
    "BIRTHDATE",
    "PHONE_NUMBER"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [],
  "aws_cognito_password_protection_settings": {
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": [
      "REQUIRES_LOWERCASE",
      "REQUIRES_UPPERCASE",
      "REQUIRES_NUMBERS",
      "REQUIRES_SYMBOLS"
    ]
  },
  "aws_cognito_verification_mechanisms": [
    "PHONE_NUMBER"
  ],
  "aws_user_files_s3_bucket": *REDACTED*,,
  "aws_user_files_s3_bucket_region": "us-east-1"
}
```

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ChristopherGabba** [comment]
@ykethan Hello everyone,
I managed to figure out the cause of the issue, which to be honest, is quite perplexing to me.

I was trying to save one line of code for by doing this: 
``` javascript
// DO NOT DO THIS, THROWS GETCONFIG ERROR:
const { graphql } = generateClient() // tried destructuring early
const response = graphql(...., ....)

// DO THIS:
const client = generateClient()
const response = client.graphql(..., ...)
```

Maybe there should be something in the docs suggesting not to do this....

Thanks,
Chris

**Comment by cwomack** [comment]
@ChristopherGabba, were you able to unblock yourself then for the TypeErrors you were experiencing with `getConfig`?

The object that's returned from calling `generateClient()` needs to be stored in a variable to then be used later, which the updates to your code fixed! Otherwise the first example of your code returns an undefined object and results in the TypeError you experienced.  

This should be detailed in [this section of the docs](https://docs.amplify.aws/javascript/build-a-backend/graphqlapi/set-up-graphql-api/#configure-the-amplify-library-in-your-app-code) where you set up the Amplify GraphQL API, but if you feel that it wasn't clear or needs to be updated then feel free to let us know!

**Comment by ChristopherGabba** [comment]
@cwomack Correct, it is not presenting the TypeError anymore and it is working great now.  I read that section, and understand the need for the generateClient, but don't see anything specifically warning about this. Maybe it's my somewhat inexperience with javascript ( only about a year or two), but I thought everything could be safely de-structured if the underlying variable was present. This is my first time running into an error like this, and somewhat goes against functional norms. 

I think maybe there could be a comment in the docs about this specifically. That or the error presented could be more specific "Do not destructure client, etc. etc."...

**Comment by ShivamJoker** [comment]
Got the same issue. Had to use it without destructuring the variable.
