### ISSUE TITLE
object Object at handleError graphql using amplify

### ISSUE THREAD

**Issue by Arya-Bastani23** [aws-amplify/amplify-js#12851]
### Amplify CLI Version

12.10.1

### Question

I created a graphQL API for my amplify project following [this Amplify documentation](https://docs.amplify.aws/javascript/build-a-backend/graphqlapi/connect-to-api/). 

I've followed all the steps layed out here but whenever I try to call the `createItem` function I show below I get the following error:

```
ERROR
[object Object]
    at handleError (http://localhost:3000/static/js/bundle.js:69505:58)
    at http://localhost:3000/static/js/bundle.js:69528:7

```

At first I thought it's because I'm passing in the wrong object type and it should be of type `CreateApplicationInput!`,  so I created a class with that name and created a new instance of it named `new_input`, but that didn't work. I'm not sure if amplify already created a class of that type I need to import into this file (I couldn't find anything like that).

**Any input for why this error is popping up or how to debug would be really appreciated**

I have the following function that's called when a button is clicked to use graphQL to create a new item in my backend DB: 
```
const client = generateClient();

class CreateApplicationInput {
  constructor(name, description) {
    this.name = name;
    this.description = description;
  }
}

async function createItem() {
  const old_input = {name: "test", description: "first one"}

  const new_input = new CreateApplicationInput('test', 'idk')

  console.log(test)

  await client.graphql({
    query: createApplication,
    variables: {
      input: new_input
    }
  });
```

The `createApplication` function that's used is here and was automatically generated by amplify:
```
export const createApplication = /* GraphQL */ `
  mutation CreateApplication(
    $input: CreateApplicationInput!
    $condition: ModelApplicationConditionInput
  ) {
    createApplication(input: $input, condition: $condition) {
      id
      name
      description
      createdAt
      updatedAt
      __typename
    }
  }
`;
```

And this is what my graphQL schema looks like:
```
type Application @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String!
  description: String
}
```

**Comment by cwomack** [comment]
Hey, @Arya-Bastani23 👋.  Let us know if you got a chance to review @ykethan's [comment](https://github.com/aws-amplify/amplify-js/issues/12851#issuecomment-1892471612) above or if you're still blocked.  And is this related to the Discord Office Hours error you're experiencing as well (left a comment there)?

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
