### ISSUE TITLE
requestPermission called twice with amplify push notifications 1.0.2.

### ISSUE THREAD

**Issue by eoinboylan** [aws-amplify/amplify-js#1286]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?

Initialising the amplify PushNotification class causes error below when asking for permission on IOS. 
<img width="365" alt="screen shot 2018-07-20 at 22 45 30" src="https://user-images.githubusercontent.com/2372105/43026880-7eeb64c8-8c6f-11e8-8a10-79f941deea01.png">

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

Create new react application with 1.0.2 versions of amplify library. Link PushNotificationIOS libraries, following amplify documentation. Initialise amplify PushNotification with Pinpoint app id. 

What is the expected behavior?

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
1.0.2

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by ianpogi5** [comment]
Same thing happening to me.

**Comment by edmundojr** [comment]
Same thing happening here :\

**Comment by muhammetdemirci** [comment]
same thing

**Comment by eoinboylan** [comment]
@aris-b This fixes the issue, Amplify docs should be updated to reflect this.
