### ISSUE TITLE
Amazon cognito not giving refresh token provided by federated identity provider (AzureAD)

### ISSUE THREAD

**Issue by arifannosh** [aws-amplify/amplify-js#12864]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Version

v5

### Amplify Categories

auth

### Backend

None

### Environment information

<details>
.
```
# Put output below this line
"aws-amplify": "5.3.4",

```

</details>

### Describe the bug

I am facing a consistent issue in which the refresh token is not being retrieved successfully for users federated with AzureAD, while the process works as intended for users who are not federated (simple users) within the user pool. Specifically, AzureAD federated users do not receive a valid refresh token during the authentication process, leading to difficulties in handling token refreshes for this user group.

### Expected behavior

i call this function " Auth.currentSession(); " 

### Reproduction steps

 users federated with AzureAD

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by israx** [comment]
Hey @arifannosh . If you are authenticating with a social provider via Cognito and using an `implicit grant` (code) OAuth flow. It is expected to not get a `refresh_token` because the Authorization server, in that case Azure, will not return it. If you want to get back a `refresh_token` you must use the `code grant` OAuth flow in your Amplify configuration. `e.g { responseType: "code" }`

**Comment by arifannosh** [comment]
thanks @israx

**Comment by nadetastic** [comment]
Hi @arifannosh following up here - did the comment from @israx resolve you issue and answer your questions?

**Comment by arifannosh** [comment]
@nadetastic yes
