### ISSUE TITLE
How to update only nested field property values in `DataStore` to avoid conflicts / overwrites like FireBase `update()`

### ISSUE THREAD

**Issue by gaurav21r** [aws-amplify/amplify-js#12879]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

All Frameworks

### Amplify APIs

DataStore

### Amplify Version

v5

### Backend

Amplify CLI

### Environment information

<details>

```bash
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 164.13 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
  Browsers:
    Chrome: 120.0.6099.234
    Edge: 120.0.2210.144
    Safari: 17.2.1
  npmPackages:
    @aws-amplify/datastore: ^5.0.12 => 5.0.12 
    @types/react: ^18.2.43 => 18.2.48 
    @types/react-dom: ^18.2.17 => 18.2.18 
    @typescript-eslint/eslint-plugin: ^6.14.0 => 6.19.0 
    @typescript-eslint/parser: ^6.14.0 => 6.19.0 
    @vitejs/plugin-react: ^4.2.1 => 4.2.1 
    aws-amplify: ^6.0.12 => 6.0.12 
    aws-amplify/adapter-core:  undefined ()
    aws-amplify/analytics:  undefined ()
    aws-amplify/analytics/kinesis:  undefined ()
    aws-amplify/analytics/kinesis-firehose:  undefined ()
    aws-amplify/analytics/personalize:  undefined ()
    aws-amplify/analytics/pinpoint:  undefined ()
    aws-amplify/api:  undefined ()
    aws-amplify/api/server:  undefined ()
    aws-amplify/auth:  undefined ()
    aws-amplify/auth/cognito:  undefined ()
    aws-amplify/auth/cognito/server:  undefined ()
    aws-amplify/auth/enable-oauth-listener:  undefined ()
    aws-amplify/auth/server:  undefined ()
    aws-amplify/datastore:  undefined ()
    aws-amplify/in-app-messaging:  undefined ()
    aws-amplify/in-app-messaging/pinpoint:  undefined ()
    aws-amplify/push-notifications:  undefined ()
    aws-amplify/push-notifications/pinpoint:  undefined ()
    aws-amplify/storage:  undefined ()
    aws-amplify/storage/s3:  undefined ()
    aws-amplify/storage/s3/server:  undefined ()
    aws-amplify/storage/server:  undefined ()
    aws-amplify/utils:  undefined ()
    eslint: ^8.55.0 => 8.56.0 
    eslint-plugin-react-hooks: ^4.6.0 => 4.6.0 
    eslint-plugin-react-refresh: ^0.4.5 => 0.4.5 
    json-diff-ts: ^2.2.1 => 2.2.1 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.2.2 => 5.3.3 
    vite: ^5.0.8 => 5.0.12 


```

</details>

### Describe the bug

The graphql model is a simple
```graphql
type Page @model {
  id: String!
  name: String!
  data: AWSJSON
}
```
`data` is a JSON here and NOT a top level property because the field names for every `data` in `Page` is dynamic and is not suitable as a top top level field for a Relational DB like Dynamo as you can see from the object examples below.

Two web clients, A & B currently conencted to the Internet with Datastore offline capabilities enabled with `AutoMerge` for conflict resolution.

#### `T(0)`Add this to Client A and go offline

```javascript
await DataStore.save(new Page({
    "name": "doc",
    "data": {
        "shape 1": {
            "type": "rectangle",
            "x": 100,
            "y": 100,
            "color": "red"
        }
    }
}))
```

#### `T(1)`Client B Synchronizes and goes offline
```javascript
await DataStore.query(Page)
```
#### `T(2)` Client A Updates the DB while Offline
```js
const docObject = (await DataStore.query(Page, p => p.name.eq("doc")))[0]
DataStore.save(Page.copyOf(docObject, updated => {
    updated.data['shape 1'].x = 10;
    updated.data['shape 1'].y = 10;
}))
```

#### `T(3)` Client B also Updates the DB while Offline
_Note there are no directly conflicting sub fields_
```js
const docObject = (await DataStore.query(Page, p => p.name.eq("doc")))[0]
DataStore.save(Page.copyOf(docObject, updated => {
    updated.data['shape 1'].color = "blue";
    updated.data['shape 2'] = {"type": "circle"};
}))
```

#### `T(6)` Both Clients are queried to show the document

```js
(await DataStore.query(Page, p => p.name.eq("doc")))[0]
```

### Expected behavior

This should be the correct result with the `AutoMerge` algorithm described in

```js
var resultJSON = {
    "name": "doc2",
    "data": {
        "shape 1": {
            "type": "rectangle",
            "x": 10,
            "y": 10,
            "color": "blue"
        },
        "shape 2": {
            "type": "circle"
        }
    }
}
```

But instead, we're getting
```js
var actualResult = {
    "name": "doc2",
    "data": {
        "shape 1": {
            "type":"rectangle",
            "color":"red",
            "x":10,
            "y":10
        },
        "shape 2": {
            "type":"circle"
        }
    }
}
```

The `color` property is completely ignored when `Client B` changes it while the `shape 2` update remains.

### Reproduction steps

Mentioned above in detail.

### Additional information and screenshots

Firebase allows us to do the same operation while giving the expected result using an `update` with dot notation.

From https://firebase.google.com/docs/firestore/manage-data/add-data#update_fields_in_nested_objects

<img width="811" alt="image" src="https://github.com/aws-amplify/amplify-js/assets/1716462/f6655eb4-dea2-4c20-9c7d-e6bf1f04ef75">
<img width="772" alt="image" src="https://github.com/aws-amplify/amplify-js/assets/1716462/bc8505db-fce9-483a-9178-15e6268eda76">

We can use for A
```js
updateDoc(doc(db, 'pages', 'doc'), {
    'data.shape 1.x': 10,
    'data.shape 1.y': 10
});
```
And for B
```js
updateDoc(doc(db, 'pages', 'doc2'), {
    'data.shape 1.color': 'blue',
    'data.shape 2.type': 'circle'
});
```
And *get the expected result*

**Comment by gaurav21r** [comment]
I just peeked under the hood of the network tab at `T(4)` and pasting the `Copy as fetch` of the relevant request.

```js
fetch("https://ziibcu2zwbddjhlnhnwhllf6sy.appsync-api.us-east-1.amazonaws.com/graphql", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-US,en;q=0.9",
    "cache-control": "no-cache",
    "content-type": "application/json; charset=UTF-8",
    "pragma": "no-cache",
    "sec-ch-ua": "\"Not_A Brand\";v=\"8\", \"Chromium\";v=\"120\", \"Google Chrome\";v=\"120\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"macOS\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "cross-site",
    "x-amz-user-agent": "aws-amplify/6.0.12 datastore/2 framework/1",
    "x-api-key": "*********"
  },
  "referrer": "http://localhost:5173/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"query\":\"mutation operation($input: UpdateCORASPageInput!, $condition: ModelCORASPageConditionInput) {\\n  updateCORASPage(input: $input, condition: $condition) {\\n    id\\n    name\\n    data\\n    createdAt\\n    updatedAt\\n    _version\\n    _lastChangedAt\\n    _deleted\\n  }\\n}\\n\",\"variables\":{\"input\":{\"id\":\"9a79b9bf-b34a-41f9-b06b-ba619d608c9e\",\"data\":\"{\\\"shape 1\\\":{\\\"color\\\":\\\"red\\\",\\\"x\\\":10,\\\"y\\\":10,\\\"type\\\":\\\"rectangle\\\"}}\",\"_version\":1},\"condition\":null}}",
  "method": "POST",
  "mode": "cors",
  "credentials": "omit"
});
```

A nicer version of the `body:` is:
```js
{
    "query": "mutation operation($input: UpdateCORASPageInput!, $condition: ModelCORASPageConditionInput) {\n  updateCORASPage(input: $input, condition: $condition) {\n    id\n    name\n    data\n    createdAt\n    updatedAt\n    _version\n    _lastChangedAt\n    _deleted\n  }\n}\n",
    "variables": {
        "input": {
            "id": "9a79b9bf-b34a-41f9-b06b-ba619d608c9e",
            "data": "{\"shape 1\":{\"color\":\"red\",\"x\":10,\"y\":10,\"type\":\"rectangle\"}}",
            "_version": 1
        },
        "condition": null
    }
}
```

As you can see even though *Client A* only updated `x` & `y` at `T(2)` the _entire_ object at `T(2)` is being sent, which is probably the reason why AutoMerge is failing.

**Comment by cwomack** [comment]
Hello, @gaurav21r and thank you for opening this issue. It seems that the problem comes from how nested JSON objects are handled during conflict resolution in DataStore’s AutoMerge feature. AutoMerge is optimized for top-level attributes, but does not have the same behavior when doing deep merges for nested structures. I think this might be causing an unexpected race condition, leading to that color attribute in your example being overwritten.

Can you see if updating your schema to use a child model instead of JSON changes the behavior?

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please review the comment above and let us know if updating the schema helps alleviate the the problem.  If not, reply back and we'd be happy to re-open the issue.

Thank you!
