### ISSUE TITLE
Android complaining about SCHEDULE_EXACT_ALARM

### ISSUE THREAD

**Issue by stefoid** [aws-amplify/amplify-js#12878]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Push Notifications

### Amplify Version

v5

### Amplify Categories

notifications

### Backend

None

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 14.2.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 19.66 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.0.0 - ~/.nvm/versions/node/v18.0.0/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.6.0 - ~/.nvm/versions/node/v18.0.0/bin/npm
    Watchman: 2023.02.13.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 17.2.1
  npmGlobalPackages:
    corepack: 0.10.0
    ios-deploy: 1.12.1
    npm: 8.6.0
    react-native-cli: 2.0.1

```

</details>

### Describe the bug

On uploading our RN app to google play console, we see
<img width="724" alt="Screenshot 2024-01-23 at 11 54 54 am" src="https://github.com/aws-amplify/amplify-js/assets/8017974/8aab9066-7eb6-4947-b12f-b586c97c3276">

Your use of exact alarms is causing your app to crash for some Android users
Your app schedules exact alarms without checking whether the
SCHEDULE_EXACT_ALARM permission has been granted. This is causing your app to crash for users on Android 14 because the permission is no longer granted by default.
In most cases, alternative methods of scheduling work or inexact alarms are more appropriate. If your use of exact alarms is justified, update your app so that it checks this permission is granted before scheduling.

We dont explicitly use this permission, but I guess it is being detected in some merged manifest due to a library, and my best guess is the amplify push library because some googling has revealed it is used by RNPushNotification.  We dont use that in the app, but Im assuming if one push library has a use for this permission, then its likely the amplify push implementation does also?

question - is SCHEDULE_EXACT_ALARM  used by amplify push notification?

- if so, is it safe to use amplify push notification 'out of the box' with android 14 devices, or do I need to do something about it ?

- any other info I need to know about SCHEDULE_EXACT_ALARM / Android 14 WRT  amplify push notification?
thanks!

### Expected behavior

Id expect that amplify push handles anything to do with SCHEDULE_EXACT_ALARM that needs to be done to run safely, such as explicitly request permission for android 14 devices where it is requried to

### Reproduction steps

none at this stage

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Mobile Operating System

android 14

**Comment by nadetastic** [comment]
Hi @stefoid thank you for opening this issue. To first answer your question, Push Notifications doesn't use SCHEDULE_EXACT_ALARM on android, as seen in the manifest/source code for [v6 branch](https://github.com/aws-amplify/amplify-js/blob/main/packages/rtn-push-notification/android/src/main/AndroidManifest.xml) and [v5 branch](https://github.com/aws-amplify/amplify-js/blob/v5-stable/packages/rtn-push-notification/android/src/main/AndroidManifest.xml).

With that said, I'm curious if you have any other dependency that is most likely causing this issue?

**Comment by stefoid** [comment]
In a generated file called manifest-merger...release-report.txt  ,  I see

		ADDED from [androidx.room:room-runtime:2.5.0]  .....  /transformed/room-runtime-2.5.0/AndroidManifest.xml:25:13-74
uses-permission#android.permission.SCHEDULE_EXACT_ALARM

I dont know what room-runtime is or why it is included at this point....

**Comment by nadetastic** [comment]
@stefoid for this issue, I believe that this setting is not being used by Amplify, but instead from what looks like room-runtime. One way to test is to try and check the generated on an application that does not have the `aws-amplify` dependency.

**Comment by stefoid** [comment]
Thanks Dan.  Its definitely room-runtime, but Im not sure what that is or why it is being pulled in.  Ill keep an eye on it and let you know if anything amplify related occurs.

thanks

**Comment by aswani-mmm** [comment]
Hi @nadetastic ,
In my project im using here : ios/.symlinks/plugins/flutter_local_notifications/android/src/main/AndroidManifest.xml
