### ISSUE TITLE
Storage API should passthrough timeout override, and support progress callback

### ISSUE THREAD

**Issue by eoliphan** [aws-amplify/amplify-js#1288]
Do you want to request a feature or report a bug?  **Request a feature**

What is the current behavior? **The storage API's (e.g. put()) don't appear to allow the Storage client code to override the default timeout, or set a progress callback function.   The moment one wants to transfer files of any non-trivial size, timeout overrides and a mechanism to provide the user with feed back are a must.  The timeout can be overridden globally, but fine-grained support would be a lot better**

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify. **N/A**

What is the expected behavior? **The global and method level options maps should allow for an override of the httpOptions.timeout, or for that matter just an httpOptions key that would allow one to override any of them as necessary.  The put, etc methods should include an .on() callback or something similar**

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions? **N/A**

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.  **N/A**

**Comment by sashafklein** [comment]
Agreed. Is there any way to track upload/download progress? Important feature for large files.

**Comment by ffxsam** [comment]
Seconded. This has been missing for quite awhile, and IMO is pretty crucial for large file uploads.

@sashafklein You wouldn't need it for download, right? As your browser will provide a download progress bar.

**Comment by mpodlasin** [comment]
I need this so much! Will the PR get accepted if I write this functionality?

**Comment by mpodlasin** [comment]
Nope, I need a way to manipulate timeouts. Uploading 17mb file fails for us on relatively slow connections (cafe wifi etc). We need it to be more robust, even if upload will take a long time.

**Comment by ffxsam** [comment]
Ah I see. I actually have no idea, and don't have time to investigate right now. But I will at some point.

**Comment by ffxsam** [comment]
@mpodlasin Can you do me a favor and open a new issue, with as many details as possible? Thanks!

**Comment by mpodlasin** [comment]
@eoliphan you mentioned you can change timeout globally.

Can you tell us how?

**Comment by sammartinez** [comment]
In looking at the above PR, I do see that this feature was implemented. Resolving
