### ISSUE TITLE
Investigating AWS Amplify Cognito sign in failed with ConsoleLogger

### ISSUE THREAD

**Issue by judoaseeta** [aws-amplify/amplify-js#12893]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Version

v6

### Backend

None

### Environment information

<details>
 @aws-amplify/auth": "^6.0.9",
   "@aws-amplify/core": "^6.0.9",

</details>

### Describe the bug

We run an application on production for last 3 years with AWS-amplify. From last year, we decided to move out from amplify-backend, so we have just used Amplify-Auth only on Client side(our app built with React 18).

Since that a few of user complained us they failed to sign-in. We started to invesitgate and what we knew was in that case once user trigger sign-in browser never send POST to cognito-idp.  As i know usually when signing in with Cognito, Amplify or Cognito should send POST to cognito-idp to validate refresh token. 

So what we did was add DEBUG logger with (window.LOG_LEVEL = 'DEBUG'). and we found a case which failed to sign-in and saw log on dev tool.  

we checked a console message like below. 

Hub - Dispatching to core with 

and object with that log show us cognito was configured properly.

but after triggering sign-in again, there are no further logs.

For furthermore information , 

- Browser: Chrome
- OS: Mac

a funny thing is at the same time when this happen, sign-in with Safari browser successfully.

### Expected behavior

sign-in should work and DEBUG logger should 

### Reproduction steps

1. deploy on Production
2. wait to fail on a browser(usually Chromium based one)

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by nadetastic** [comment]
Hi @judoaseeta thank you for opening this issue. To clarify the issue, it sounds like some of your users on Chrome browsers on Mac OS are having an issue when signing in. Are there any additional error messages that you can share, or a link to the app that is having the error so I can take a look?

Any other additional context would be greatly help full. I tried a quick reproduction on my end and I did not face any errors, so I would like to match you setup as much as possible.

**Comment by judoaseeta** [comment]
@nadetastic Hi. Yes it happened some of the users(it happened among almost 5 of 2000 +users.). Occasionally we can reproduce it one of my colleague's laptop (macOS and chrome), there is no error message on the console and network. as i described on the above, there was no http POST request to cognito-idp , too.   Unfortunately. It's hard for us to reproduce this.

**Comment by nadetastic** [comment]
@judoaseeta thanks for the context. Could you share the shape of the config you are passing to `Amplify.configure()` as well as confirm the exact version of `aws-amplify` you are using? I'd like to see if there is anything that may stand out to me and also try to reproduce it myself.

**Comment by nadetastic** [comment]
@judoaseeta following up here - are you still seeing this issue? Understandably its intermittent so you may not have seen it for some time. I'd still like to get the config you are using and the exact version of `aws-amplify` as well.

**Comment by nadetastic** [comment]
Hi 👋 Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
