### ISSUE TITLE
No func available to respond to user.challengeName 'NEW_PASSWORD_REQUIRED'

### ISSUE THREAD

**Issue by NotoriousLisp** [aws-amplify/amplify-js#1290]
Do you want to request a feature or report a bug?
Request a feature.

What is the current behavior?
When logging in with a user created from the AWS console with a verified email address, the user is returned with a challengeName of `NEW_PASSWORD_REQUIRED`.  As far as I can tell, there is no way to fulfill this challenge using the Amplify library.  Before I migrated to Amplify, I was able to call `completeNewPasswordChallenge` on the Cognito user object.

What is the expected behavior?
AWS Amplify Auth should have a function to fulfill this requirements, or if it already exists, please update the docs with an example for clarity!

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
Amplify 1.0.1

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by PerfectPixel** [comment]
This is the function in `Auth.ts` ([link](https://github.com/aws-amplify/amplify-js/blob/42f101ce98c0511bcce0a935e5b9fda294c9cd39/packages/auth/src/Auth.ts#L630-L673)) that is used for that challenge:

```
public completeNewPassword(
        user: any,
        password: string,
        requiredAttributes: any
    ): Promise<any>
```

**Comment by JesusTSeger** [comment]
@PerfectPixel Just to be clear, is the `user` parameter the same user object that is returned from the  `Auth.signIn()` promise?
