### ISSUE TITLE
Cannot Initiate Cognito CUSTOM_AUTH flow with an SRP_A challenge.

### ISSUE THREAD

**Issue by stevetkdo** [aws-amplify/amplify-js#1291]
Do you want to request a feature or report a bug?

report a bug

What is the current behavior?

To initiate a custom authentication flow, I have to call `signIn` with only username parameter like so: `authResult = await Auth.signIn(username)`. I am using a custom authentication flow which requires password check first; I am following the AWS documentation [here](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-authentication-flow.html#amazon-cognito-user-pools-custom-authentication-flow) which states: 

> If you want to include SRP in a custom authentication flow, you need to start with it. To initiate SRP password verification, the DefineAuthChallenge Lambda trigger returns SRP_A as the challenge name and SRP_A in the authentication parameters map

My lambda code indeed does return this as the first challenge. I can see in the response that the challenge name is set to `SRP_A`, however `authResult` does not contain `challengeName`. 

![screen shot 2018-07-22 at 09 38 57](https://user-images.githubusercontent.com/3032418/43043865-6e98931e-8d93-11e8-984c-16df0da5dfbf.png)

![screen shot 2018-07-22 at 09 43 21](https://user-images.githubusercontent.com/3032418/43043891-c4346726-8d93-11e8-9e56-4c3e2c406be8.png)

I understand in this situation I am probably required to calculate SRP myself, however I am not even getting the chance to respond to this challenge. If I am doing something wrong here then I apologise and would appreciate being told what that is, as I am, I believe, following the AWS documentation.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

To reproduce the problem, simple set a custom authentication flow from the client and set the first challenge from the `define auth challenge` lambda as `SRP_A`.

What is the expected behavior?
I expect to be able to set the SRP_A challenge first (as instructed in the AWS documentation) and continue my custom authentication flow.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
Amplify version 1.0.2
amplify-react version 1.0.2. 
Firefox version 61.0.1
MacOSX 10.13.6

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by annjawn** [comment]
Hey @stevetkdo , were you able to get it to work? We have a similar requirement of verifying password first and then do a Custom Auth flow.

**Comment by powerful23** [comment]
@stevetkdo @annjawn can you paste your `Define Auth Challenge Lambda Trigger` here? According to the cognito js code: , the challenge name returned by the lambda function should be `CUSTOM_CHALLENGE`: https://github.com/aws-amplify/amplify-js/blob/master/packages/amazon-cognito-identity-js/src/CognitoUser.js#L176

**Comment by annjawn** [comment]
@powerful23 nevermind, I got it to work with SRP_A first and then CUSTOM_CHALLENGE to do password verification & custom auth flow. My bad!
