### ISSUE TITLE
amplify-Vue-starter

### ISSUE THREAD

**Issue by rojagit** [aws-amplify/amplify-js#1292]
App is not allowing me to create a new user (during sign up) - just does nothing, no errors anywhere - what gives ?

**Comment by manueliglesias** [comment]
Hi @rojagit 

Do you see some output in the console?

**Comment by rojagit** [comment]
nope, nothing at all, even on dev console in browser there is nothing. I do not see a form for this page in the source code, and the button doesnt show it is a submit.

**Comment by manueliglesias** [comment]
Can you verify that you have an `aws-exports.js` file in your src directory?

also, what is the output of `awsmobile features` ? (which features are enabled?)

**Comment by rojagit** [comment]
So I re-created step-by-step on another box, this time I got a bit further, managed to pass all validations,  painfully by looking at the error message object, then finally got the code, submitted code, got accepted, went to SignIn screen, there it yelled that no MFA in account.


![image](https://user-images.githubusercontent.com/4193031/43407820-bf70213e-93ed-11e8-9fc6-863f6a9353a7.png)

**Comment by rojagit** [comment]
Ignore last message, I just disabled MFA in Cognito all all is good now. 

(That sample structure image threw me off and I was scratching my head on it for some time though :)

I'm going back to my original code and will try to debug that now. I always start with a fresh user (init project) instead of downloading the aws-export but will check it there and update you on that.

**Comment by rojagit** [comment]
So I went back to the 'No User Pool' code, verified aws-exports.js exists under src, and you were spot on, for some reason the user features were not enabled. Enabled it and am gtg. Thanks for your help !!
