### ISSUE TITLE
Proxy Pinpoint Analytics API to avoid ads blocker

### ISSUE THREAD

**Issue by phuctm97** [aws-amplify/amplify-js#12925]
### Is this related to a new or existing API?

Analytics

### Is this related to another service?

Pinpoint

### Describe the feature you'd like to request

To avoid Ads Blocker, it would be great to be able to proxy Pinpoint APIs for Analytics. How do we configure that in the latest Amplify JS? Is it possible at all?

### Describe the solution you'd like

1. Proxy Pinpoint API via an API gateway (or any backend APIs)
2. Set Pinpoint URL in Amplify configuration
3. Use everything like normally

### Describe alternatives you've considered

There's no options.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cwomack** [comment]
Hello @phuctm97, and thank you for opening this issue.  I'll mark this as a feature request since proxy support for Pinpoint and Analytics isn't something we have readily supported out of the box (or documented).

As for a workaround, you could potentially set up an API Gateway endpoint that will forward any calls made to Pinpoint and then redirect back to Pinpoint from the API Gateway.  I'm not certain if this will bypass the ad blockers, but will review this with our team to see if we can offer some better suggestions.

**Comment by phuctm97** [comment]
> Hello @phuctm97, and thank you for opening this issue. I'll mark this as a feature request since proxy support for Pinpoint and Analytics isn't something we have readily supported out of the box (or documented).
> 
> As for a workaround, you could potentially set up an API Gateway endpoint that will forward any calls made to Pinpoint and then redirect back to Pinpoint from the API Gateway. I'm not certain if this will bypass the ad blockers, but will review this with our team to see if we can offer some better suggestions.

That will work, however how do I configure that in the current Amplify SDK?

**Comment by afgallo** [comment]
Hi, we have come across the same issue and would love to see this resolved without the need of a proxy in between our front-end layer and Pinpoint APIs. Maybe Pinpoint endpoints can be whitelisted with the main Ad Blocker vendors.

**Comment by cwomack** [comment]
In an effort to consolidate the context, comments, and criteria for success regarding improved support for proxies with Amplify, we'll be closing this issue in favor of the more recent #13048.  Please follow that issue and leave any additional feedback there going forward.  Thank you!
