### ISSUE TITLE
Not able to use Storage.put , await Storage.get or any other methods

### ISSUE THREAD

**Issue by devzaveri** [aws-amplify/amplify-js#12932]
### Amplify CLI Version

12.10.1

### Question

Hello Team,
Question 1 - I'm facing troble to use aws-amplify - storage, every time when I tried to call storage.get or storage.put I am getting error that "get"/"put" is not a property.

Question 2 - in aws-amplify/storage "getUrl" this method I am calling I am const getUrlResult = await getUrl({}) calling like this I am getting uri but with my actual Key is AWSDynamoDB/01706692467967-3801d88f/Main Parwaana - Full Video _ Pippa _ Ishaan & Leysan _ Arijit Singh _ A. R. Rahman _ Shellee.mp3 but they are showing my public/AWSDynamoDB/01706692467967-3801d88f/Main Parwaana - Full Video _ Pippa _ Ishaan & Leysan _ Arijit Singh _ A. R. Rahman _ Shellee.mp3 this Key there for I am getting error <Code>NoSuchKey</Code>
![image](https://github.com/aws-amplify/amplify-cli/assets/84063889/677bec4f-c0c1-4e07-be9e-4ae796d44e4a)

Please Help me whih this or give proper guidance how to implement this in my React Native Code.

Also I want to store multipal audio files. and I want to read that files in my application. how to implement this?

**Comment by cwomack** [comment]
Sorry to hear that you're running into this, @devzaveri.  Just to confirm based on the reference to `Storage.get()` and `Storage.put`, are you on v.5x of Amplify for your project?  Also, can you share the frontend code that's producing these errors?  Thanks!

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
