### ISSUE TITLE
Typo in API_GUIDE documentation

### ISSUE THREAD

**Issue by eolasd** [aws-amplify/amplify-js#1293]
Typo in the documentation 
https://github.com/aws-amplify/amplify-js/blob/master/docs/media/api_guide.md#custom-request-headers

```
Amplify.configure({
  API: {
    endpoints: [
      {
        name: "sampleCloudApi",
        endpoint: "https://xyz.execute-api.us-east-1.amazonaws.com/Development",
        custom_header: async () => { 
          return { Authorization : 'token' } 
          // Alternatively, with Cognito User Pools use this:
          // return { (await Auth.currentSession()).idToken.jwtToken } 
        }
      }
    ]
  }
});
```

Line 10: error at the " return { (await Auth " line, missing the 'Authorization' key:

```
Amplify.configure({
  API: {
    endpoints: [
      {
        name: "sampleCloudApi",
        endpoint: "https://xyz.execute-api.us-east-1.amazonaws.com/Development",
        custom_header: async () => { 
          return { Authorization : 'token' } 
          // Alternatively, with Cognito User Pools use this:
         //    return { Authorization: (await Auth.currentSession()).idToken.jwtToken }; 
        }
      }
    ]
  }
}); 
```

Thank you!
ps. This is my first ever contribution, so please enlighten me if I have messed it up!

**Comment by manueliglesias** [comment]
Hi @eolasd 

Typically the preferred way to send contributions is by [creating a pull request](https://help.github.com/articles/creating-a-pull-request/)

Since this was a small fix, I applied the change.

Thank you for the contribution! 😄
