### ISSUE TITLE
Credentials should not be empty. error on Amplify storage function

### ISSUE THREAD

**Issue by FlyingTurkman** [aws-amplify/amplify-js#12945]
### Which Specific Feature is your question related to?

Amplify

### Question

I am newbie for aws. I am trying to learn deploy an app in amplify with Nexj.js 15. I did everything like on docs but when I am trying to uploadData giving an error "Credentials should not be empty."

**Comment by FlyingTurkman** [comment]
> @FlyingTurkman are you utilizing the documentation [here](https://docs.amplify.aws/react/build-a-backend/storage/upload/)? Does the application have auth resource configured?
> 
> transferring to Amplify JS repository for further assistance.

Yes I did but not worked.

**Comment by nadetastic** [comment]
Hi @FlyingTurkman is this issue happening locally or after you deploy to hosting?

**Comment by FlyingTurkman** [comment]
@nadetastic I figure it out. Problem was about security policy.

**Comment by Mxctr1** [comment]
Can you tell me more about that @FlyingTurkman ? What about security policy ? I have the same problem

**Comment by Mxctr1** [comment]
Whats the IAM_username ? I have a userool and I want to allow all my user in the userpool to upload their profile picture

**Comment by FlyingTurkman** [comment]
> Whats the IAM_username ? I have a userool and I want to allow all my user in the userpool to upload their profile picture

https://docs.aws.amazon.com/IAM/latest/UserGuide/introduction_access-management.html

You can allow upload files for auth users with security policies.

There is example about your situation. https://docs.aws.amazon.com/AmazonS3/latest/userguide/example-bucket-policies.html

**Comment by reactnetau** [comment]
After adding "AmplifyBackendDeployFullAccess" to my Amplify logged in User role policy it worked.
