### ISSUE TITLE
API import Module from @aws-amplify for graphql mutation

### ISSUE THREAD

**Issue by PixelJunkie33** [aws-amplify/amplify-js#12949]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

GraphQL API

### Amplify Version

v6

### Amplify Categories

api

### Backend

Amplify CLI

### Environment information

<details>

```
# Put output below this line
I am importing API, says no longer  in module aws-amplify :
**export 'API' (imported as 'API') was not found in 'aws-amplify' (possible exports: Amplify)**

My Packages: 
dependencies": {
    "@aws-amplify/cli": "^12.10.1",
    "@aws-amplify/core": "^6.0.13",
    "@aws-amplify/ui-react": "^6.1.2",
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "aws-amplify": "^6.0.13",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },

```

</details>

### Describe the bug

This is the error message I get:

**export 'API' (imported as 'API') was not found in 'aws-amplify' (possible exports: Amplify)**

### Expected behavior

The API should mutate data to DB. as used in the handle function.

**  await API.graphql({ query: createKebobHouseMutation, variables: { input: dataInput } });
        event.target.reset();
        console.log("Form submitted successfully");**

### Reproduction steps

NA

### Code Snippet

```javascript
// Put your code below this line.
import { API, graphqlOperation } from 'aws-amplify';
import {
  Button,
    TextAreaField,
    SelectField,
  View,
  withAuthenticator,
} from "@aws-amplify/ui-react";
import { 
    createKebobHouse as createKebobHouseMutation,
} from "../graphql/mutations";

const ResForm = ({ signOut }) => {

    const[firstname, setFirstname] = useState("");
    const[lastName, setLastName] = useState("");
    const[email, setEmail] = useState("");
    const[phonenumber, setPhonenumber] = useState("");
    const[inquiryType, setInquiryType] = useState("");
    const[message, setMessage] = useState("");


    async function createKebobHouseReservation(event) {
        event.preventDefault();
        const form = new FormData(event.target);
        const dataInput = {
            firstname: form.get("firstname"),
            lastName: form.get("lastName"),
            email: form.get("email"),
            phonenumber: form.get("phonenumber"),
            inquiryType: form.get("inquiryType"),
            message: form.get("message"),
          }
        await API.graphql({ query: createKebobHouseMutation, variables: { input: dataInput } });
        event.target.reset();
        console.log("Form submitted successfully");

        setFirstname("");
        setLastName("");
        setEmail("");
        setPhonenumber("");
        setInquiryType("");
        setMessage("");
        
    }
```

### Log output

<details>

```
// Put your logs below this line

NA
```

</details>

### aws-exports.js

NA

### Manual configuration

NA

### Additional configuration

NA

### Additional information and screenshots

NA

**Comment by PixelJunkie33** [comment]
The solution was, use an older version of dependencies.  "@aws-amplify/ui-react": "^5.3.0",
    "aws-amplify": "^5.3.15",

**Comment by cwomack** [comment]
@PixelJunkie33, sorry we didn't get you a reply in time before you unblocked yourself.  If you feel there was an area of our documentation that could be improved to better avoid this, feel free to reply back and let us know.
