### ISSUE TITLE
Storage. Unable to specify bucket name.

### ISSUE THREAD

**Issue by pergunt** [aws-amplify/amplify-js#12952]
### Describe the feature you'd like to request

In previous versions of aws-amplify js we can specify a bucket name before read/upload/remove any file. 
However, the new one 6+ version doesn't have this ability. 
Is there a way to dynamically set the bucket name before any operation? (getUrl, uploadFile, download,remove etc)
Thanks

### Describe the solution you'd like

It would be nice to set it during runtime in `options` argument

### Describe alternatives you've considered

Currently I am reusing the whole `Amplify.configure()` which is redundant because I need to a bucket name but not the whole config (Auth, Api) any time I use Storage

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cwomack** [comment]
Hello, @pergunt and thanks for opening this issue.  You should still be able to specify a bucket name by using a scoped configuration with Storage as seen [here](https://docs.amplify.aws/react/build-a-backend/storage/existing-resources/). Can you try this and let me know if it accomplishes what you're looking for?

**Comment by pergunt** [comment]
@cwomack Well...this is quite the same what I do - set the credentials anytime bucketName changes. 
But my question is: doesn't the new version of "aws-amplify" have the handy way of specifying a bucketName exactly like it is in aws-amplify < v6 ?

**Comment by cwomack** [comment]
@pergunt, marking this as a feature request for v6.  While it was never documented in v5 that this could be done, it was permissible to dynamically change the bucket name.  I'll review this with the team for consideration as a supported feature in v6 and let you know if we have further questions about context.  Thank you again for opening this!

**Comment by ashika112** [comment]
@pergunt this feature is now available in Amplify v6 (`version 6.5.1`). More information on multi-bucket support can be found [here](https://aws.amazon.com/blogs/mobile/add-multiple-storage-buckets-amplify/?sc_channel=sm&sc_publisher=TWITTER&sc_country=global&sc_geo=GLOBAL&sc_outcome=awareness&linkId=559926045). Let us know if you have any other issue.
