### ISSUE TITLE
Question: Storage get for Email Content / Message? Pre-signed url expiry?

### ISSUE THREAD

**Issue by darren-rogan** [aws-amplify/amplify-js#1295]
This is more a question than a bug or feature request.

How would I embed an image from S3 (in the public folder) for email content to multiple people / group message, for example the image is a task that two or people need to be notified about (Can't do a url per person plus I don't have their credentials).  

At the moment the expiry for the pre-signed url is for user token expiry.. that did the action (uploaded the task with image). So if a person raised a task and then logs out the pre-signed url is invalid? I think i read something to that effect in another ticket.

I get the general use case of the url generated per person, and that is expired when they log out. Make sense. I'm just not sure how to effectively use this access pattern for this scenario.

I do have the option to drop down to the s3 library and make the file public then use that url but I'd prefer not to do that. 

Is there a way to create a pre-signed url that is attached to a system user or just a timed expiry? These user tokens can time out pretty quickly if using cognito etc.

**Comment by manueliglesias** [comment]
Hi @darren-rogan 

Seems to me that you are storing the actual pre-signed urls, is that right?

Ideally, what you store is the info needed to generate a pre-signed url at a later time (bucket, key, region) and only generate a pre-signed url when you actually need it

**Comment by powerful23** [comment]
Closing the issue. Feel free to reopen if you still have this issue.
