### ISSUE TITLE
Update legacy auth configuration and abandoned documentation

### ISSUE THREAD

**Issue by andrew-aladev** [aws-amplify/amplify-js#1296]
Hello. I saw your auth configuration for the first time in my life.

```
Auth: {
        identityPoolId: 'XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab',
        region: 'XX-XXXX-X',
        identityPoolRegion: 'XX-XXXX-X',
        userPoolId: 'XX-XXXX-X_abcd1234',
        userPoolWebClientId: 'a1b2c3d4e5f6g7h8i9j0k1l2m3'
    }
}
```

I couldn't understand anything: what these options are about and why they are here. This "config" looks like abandoned legacy code.

----

I've searched in your documentation: `site:docs.aws.amazon.com userPoolWebClientId` and found single [page](https://docs.aws.amazon.com/AmazonS3/latest/API/browser-based-uploads-aws-amplify.html).

```
identityPoolId: 'XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab', //REQUIRED - Amazon Cognito Identity Pool ID
```

Wow, it is required, I need to create it. Maybe I could understand other options there. Lets create an [identity pool](https://docs.aws.amazon.com/cognito/latest/developerguide/getting-started-with-identity-pools.html).

> choose **Manage Federated Identities**, and then choose **Create new identity pool**

There are no **Manage Federated Identities**, **Create new identity pool** buttons there. It is ok for amazon to deploy new production design without updating docs. Lets press **Manage identity pools**.

Here I can see that url is **/cognito/create**, **Cognito Identity Pool** is **not required** for **identity pool**. My brain is broken. So docs and admin panel both are completely broken. Nobody cares about it, I shouldn't use any amazon _tips_ for navigation.

----

I've used grandfather's poking method and solved that config should looks like:

```
Auth: {
  internal: { // OPTIONAL, managed amazon users
    poolId: 'region_123',
    webClientId: '345'
    // region is already encapsulated
  },
  federated: { // OPTIONAL, managed amazon users + google + facebook, etc
    poolId: '345',
    // region and webClientId are already encapsulated
  }
}
```

Please remove legacy code, update configuration, documentation and admin panel. Do not use words "identity", "cognito", etc. Today these "products" are unusable. If amazon won't be popular you would never sell such "products".

**Comment by andrew-aladev** [comment]
[API guide](https://aws-amplify.github.io/amplify-js/media/api_guide.html):

```
identityPoolId: 'XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab',
region: 'XX-XXXX-X', 
userPoolId: 'XX-XXXX-X_abcd1234', 
userPoolWebClientId: 'XX-XXXX-X_abcd1234'
```

**XX-XXXX-X** used 4 times here. How it is possible not to start refactoring of this junk immediately? Will amazon drown in legacy code?

**Comment by mlabieniec** [comment]
@andrew-aladev what is it you are having trouble with in this exactly? The config is correct in the documentation. It can be used with either a module:

```js
import Auth from '@aws-amplify/auth';

Auth.configure({ // block you reference above});

// or import the ./aws-exports.js file generated from the cli
Auth.configure(awsExports);

// or if you import the entire lib
import Amplify from 'aws-amplify';
Amplify.configure({
 Auth: {
  ...block you referenced above
  }
});
```

There is also a [visual studio code extension](https://marketplace.visualstudio.com/items?itemName=aws-amplify.aws-amplify-vscode) (search amplify) and you can get snippets for all these configs automatically generated for you.
