### ISSUE TITLE
Angular 6 build issue with Chatbox component, even though I am not using it

### ISSUE THREAD

**Issue by Ajji11** [aws-amplify/amplify-js#1297]
Do you want to request a feature or report a bug?
BUG

What is the current behavior?
I'm running into the same issue with Angular 6 when I do ng build --aot.

`ERROR in node_modules\aws-amplify-angular\lib\components\interactions\chatbot\chatbot.component.core.d.ts.ChatbotComponentCore.html(20,43): : Expected 1 arguments, but got 0.
node_modules\aws-amplify-angular\lib\components\interactions\chatbot\chatbot.component.ionic.d.ts.ChatbotComponentIonic.html(59,19): : Expected 1 arguments, but got 0.`

I just wanted to use the API service to connect to API Gateway, I'm not using the chatbox component.

I followed the tutorial and imported this into Main.ts

```
//------Main.ts--------
import Amplify, { API } from 'aws-amplify';

Amplify.configure({
  Auth: { //auth configs here  },
  API: { //api configs here  }
});
```

```
//-------App.Module
import { AmplifyAngularModule, AmplifyService } from 'aws-amplify-angular';
@NgModule({
  ...
  imports: [
    ...
    AmplifyAngularModule
  ],
  providers: [AmplifyService],
})
```

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

What is the expected behavior?
Build with no errors.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
AWS-Amplify 1.0.2
AWS-Amplify-Angular 1.0.1
Angular 6.0.3

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by haverchuck** [comment]
@Ajji11 We just merged a fix for this into the unstable branch.  Please check it out when you have a chance.

**Comment by Ajji11** [comment]
@haverchuck - I'm still pretty new to npm/github...
What would the npm command be to update to this unstable branch?

**Comment by Ajji11** [comment]
@haverchuck  - thank you.  It builds successfully now.
