### ISSUE TITLE
"User needs to be authenticated to call this API"

### ISSUE THREAD

**Issue by cabcookie** [aws-amplify/amplify-js#12978]
### Environment information

```plain text
System:
    OS: macOS 14.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.30 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: Not Found
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: Not Found
    bun: Not Found
    Watchman: Not Found
  npmPackages:
    @aws-amplify/backend: ^0.5.4 => 0.5.5 
    @aws-amplify/backend-cli: ^0.9.0 => 0.9.1 
    aws-amplify: ^6.0.3 => 6.0.4 
    aws-cdk: Not Found
    aws-cdk-lib: Not Found
    typescript: ^5.3.2 => 5.3.2
```

### Description

I followed the documentation here: https://docs.amplify.aws/gen2/start/quickstart/nextjs-app-router-client-components/
After the step **[Add a login form](https://docs.amplify.aws/gen2/start/quickstart/nextjs-app-router-client-components/#add-a-login-form)**, I get the above mentioned error message when trying to login.

After following the instructions in the documentation I created an account, confirmed the registration with the code I received by Email. I try to sign in and it shows the error message.
I stopped `next dev` deleted the folder `.next` and run `npm run dev` again. Same issue. I deleted all resources (local code and Amplify environment), created the app again and added authorization again, same issue.

Current code visible [here](https://github.com/cabcookie/personal-crm/commit/bc217d4d15c4ae5fa2afae62f2fe4b6a8227b76c).

**Comment by nadetastic** [comment]
Possible related - https://github.com/aws-amplify/amplify-js/issues/12873

**Comment by nadetastic** [comment]
Hi @cabcookie thank you for opening this issue - I just went through this guide and did not encounter this error after signing up and trying to sign in multiple times. Were you able to get unblocked on this?

**Comment by nadetastic** [comment]
@cabcookie let me know if you are still facing issues, if not, I can go ahead and close out this issue. Thanks!

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
