### ISSUE TITLE
Amplify backend and db

### ISSUE THREAD

**Issue by GustavoMFS** [aws-amplify/amplify-js#12989]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

us-east-2

### Amplify Hosting feature

Backend builds

### Question

Im still learning to deploy websites and i got an dev intership on a company, despite they dont have an dev. So I created an frontend on angular and the backend on node.js, its working and sending the data to mongodb. My question is how do i deploy the site online? I wanted to try amplify and could deploy the frontend, but i dont know how to connect it to my backend, also about the data I tried to create an exemple of what the data would look like on amplify but it doesnt have an object or array type, the data would be something like that:

key: string;
tableName: string;
debito: {
masterCard: { valor: number },
visa: { valor: number },
outros: { valor: number },
}

can I deploy my front and backend together on amplify? and can i store the data exactly the way my code is making or if i dont, can i still use another db like mongo?

**Comment by nadetastic** [comment]
Hi @GustavoMFS following up here - did the comment from @Jay2113 address you concerns, or did you have any additional questions?

**Comment by nadetastic** [comment]
Hi 👋 Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
