### ISSUE TITLE
Amplify UI Authenticator not picking up authorisation code from Cognito HostedUI redirect

### ISSUE THREAD

**Issue by Pylinho** [aws-amplify/amplify-js#12983]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App

### What browsers are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### Which region are you seeing the problem in?

eu-west-1

### Please describe your bug.

In a React 18 application, I am using aws-amplify 6.0.13 to handle authentication with Cognito. This is working fine for sign ins where a user is inputting there login details themselves, but isn't working for SSO logins managed via Cognito's Hosted UI. Let me describe my setup.

My amplify is configured as so in my React application:

```
import { Amplify } from 'aws-amplify';
import { defaultStorage } from 'aws-amplify/utils';
import { cognitoUserPoolsTokenProvider } from 'aws-amplify/auth/cognito';

export default function amplifyConfigure() {
  Amplify.configure({
    Auth: {
      Cognito: {
            identityPoolId: myIdPoolId,
            region: myRegion,
            userPoolId: myUserPoolId,
            userPoolClientId: myUserpoolAppClientId,
            loginWith {
                  oauth: {
                      domain: myOAuthDomain,
                      scopes: [ "email", "profile", "openid"],
                      redirectSignIn: "http://localhost:3000/",
                      redirectSignOut: "http://localhost:3000/",
                      responseType: "code",
                  }
            }
      }
    }
  });

  cognitoUserPoolsTokenProvider.setKeyValueStorage(defaultStorage);
}
```

for which I have anonymised the inputs. amplifyConfigure() is called in my index.js file.

I have a HostedUI in Cognito, which is configured to redirect back to the root directory of my application with an authorisation code grant. When debugging locally, I can see that the user is being authenticated in the HostedUI and the auth code is being attached by the Hosted UI correctly, as I get redirected to http://localhost:3000/?code={code}. However, this code is not then being traded for the authentication tokens with Cognito, as there is no further activity in the developer console in my browser.

I have confirmed that the redirect sign in and sign out URLs are configured identically in both my application code for the Amplify.configure() setup and the Hosted UI, so I have ruled out this as the issue. What could be causing Amplify to not trade the code for the authentication token in my application?

I have tried importing and using Hub to listen for auth events, which has confirmed to me that the code is definitely not being taken and used:

```
import { Hub } from 'aws-amplify/utils';

Hub.listen('auth', (data) => {
  const { payload } = data;
  this.onAuthEvent(payload);
  console.log(
    'A new auth event has happened: ',
    data.payload.data.username + ' has ' + data.payload.event
  );
});
```

and can see from my browser dev tools that no calls are being made to Cognito from my application after being redirected.

Just to note, this issues has arisen as we have recently upgraded from amplify v5, where we had our components wrapped with withAuthenticator(), where the SSO for our clients who used it was set up and working just fine through the Cognito HostedUI and aws-amplify setup.

I have raised the issue both here and over at https://github.com/aws-amplify/amplify-js, as I was unsure which specifically the bug would relate to.

### What's the expected behaviour?

The Authenticator component takes the authorisation code automatically and uses it to authenticate the user with Cognito and login in our application.

### Help us reproduce the bug!

N.A.

Too complex and application specific for me to provide a reproducible example, unfortunately.

### Code Snippet

My App.js file returns:
```javascript
// Put your code below this line.
return (
    <ThemeProvider theme={theme}> 
      <Authenticator components={components}>
        <UserProvider>
          <MyRouting/>
        </UserProvider>
      </Authenticator>
    </ThemeProvider>
  );
```
where MyRouting contains the routing for my application.

I can provide the theme and components objects if necessary, but components just contains a Header with a logo.

### Additional information and screenshots
The object I pass into Amplify configure:
```
{
    Auth: {
      Cognito: {
            identityPoolId: myIdPoolId,
            region: myRegion,
            userPoolId: myUserPoolId,
            userPoolClientId: myUserpoolAppClientId,
            loginWith {
                  oauth: {
                      domain: myOAuthDomain,
                      scopes: [ "email", "profile", "openid"],
                      redirectSignIn: "http://localhost:3000/",
                      redirectSignOut: "http://localhost:3000/",
                      responseType: "code",
                  }
            }
      }
    }
  }
```

**Comment by reesscot** [comment]
@Pylinho The way that the authorization code is consumed was changed in `aws-amplify@6` which is why you see the issue go away when downgrading both libraries to v5. I'm transferring this over to the JS repo for further triage.

**Comment by nadetastic** [comment]
Hi @Pylinho, I'd like to provide some clarity on this issue. It looks like the app where the request to Hosted UI is made from is on a different domain than where the user is finally redirected to - in this case, that won’t work (for security reasons). In short, the flow has to be initiated from same app, or at least the same domain.

However a possible work around is for you to potentially set up a proxy page for this purpose, with a flow like the following:
1.  Initial App A
2. App B’s proxy page with `signInWithRedirect()`
3. Hosted UI
4. App B with authenticated user session

**Comment by Pylinho** [comment]
Hi @nadetastic,

Cheers again for the information. 

We did consider implementing a proxy on our end as suggested. However, this would involve some dev work on our clients end, who have set up their dev and prod environments to be configured to point straight at Cognito HostedUI to allow for SSO between their respective sites and ours. 

We want to avoid this, as it is not a good look for us to get back to them to say we are moving away from what is a pretty fundamental and commonly implemented authentication flow, and requiring them to put some developer time into it as a result. 

What are the security concerns surrounding yourselves supporting ingesting the authentication code from Cognito when the request was not initiated from within the application? The authorisation code has to be exchanged for access tokens with Cognito before a user is authenticated anyway, so if a bad actor was to try and send an invalid authorisation code to gain access to our system, the automatic pickup and transfer of the code for the tokens with Cognito would fail anyway.

If there is no plan to add back in support for this authentication flow in v6, we would likely look at moving away from aws-amplify and implementing our own custom authentication solution, unfortunately. It feels like this functionality shouldn't have been removed between v5 and v6 from our perspective.  

Thanks again for your time and continued support.

**Comment by sankaran85** [comment]
Facing same issue with v6 , after login with congnito hosted ui when i try to access the getCurrentUser . Im getting error like 

 **UserUnAuthenticatedException: User needs to be authenticated to call this API.
    at assertAuthTokens (webpack-internal:///./node_modules/@aws-amplify/auth/dist/esm/providers/cognito/utils/types.mjs:29:15)
    at getCurrentUser (webpack-internal:///./node_modules/@aws-amplify/auth/dist/esm/providers/cognito/apis/internal/getCurrentUser.mjs:16:71)**
    
    No call to cognito made from amplify on page load. Please help us in solving this issue.

**Comment by nadetastic** [comment]
HI @Pylinho following up here as there is another alternative that can work for you.

Instead of setting a proxy page between the starting app (A) and the final app (B), you can have a user go directly to the final app (B), and check if a session exists> If it doesn't then you could automatically trigger a signIn to Hosted UI which would complete successfully on the redirect since the request originated from app B

1. Start at app A
2. From app A, user is sent to app B
3. On app B, if there is no session call `signInWithRedirect()`
4. After completing authentication the user is redirected back to app B successfully

**Comment by nadetastic** [comment]
@Pylinho following up here - wanted to see if you still have any questions with this issue.

**Comment by dimo121** [comment]
So with v6 we need to wrap with the Authenticator component and it should pick up the code and set the session in Amplify once authenticated, then we can call through amplify to get user details?

**Comment by Pylinho** [comment]
Hi @nadetastic,

The other solution you have proposed does not solve our problem. We don't want our clients to have to implement a workaround when a request direct to Cognito HostedUI redirecting their users to our application with an authorisation code should suffice.

Where you previously mentioned:

"It looks like the app where the request to Hosted UI is made from is on a different domain than where the user is finally redirected to - in this case, that won’t work (for security reasons)."

What are the security concerns preventing your Authenticator component from picking up the code?

**Comment by cwomack** [comment]
Hey, @Pylinho 👋.  Was there additional context or questions here that were missed that caused you to reopen this issue? 

As for the "why" behind this being not supported, [this](https://datatracker.ietf.org/doc/html/rfc6749#section-10.12) RFC on OAuth 2.0 security best practices will provide some insight and reasoning around Cross-Site Request Forgery.

**Comment by Deanfei** [comment]
Same issue here. It stucked there when using signInWithRedirect in the application. It's so frustrating.

**Comment by Pylinho** [comment]
Morning @cwomack. No additional context, I just came back to check up on the issue and realised I had hit "Close with comment" rather than just "Comment" when submitting last time around.

Thanks for the CSRF link. However, I'm still not sure how a potential attacker injecting their own authorisation code between Cognito HostedUI and the Authenticator component receiving this poses a security risk. 

Given the object we are passing to Amplify.configure() would be as so for v6:

`{
    Auth: {
      Cognito: {
            identityPoolId: myIdPoolId,
            region: myRegion,
            userPoolId: myUserPoolId,
            userPoolClientId: myUserpoolAppClientId,
            loginWith {
                  oauth: {
                      domain: myOAuthDomain,
                      scopes: [ "email", "profile", "openid"],
                      redirectSignIn: myRedirectSignInURL,
                      redirectSignOut: myRedirectSignOutURL,
                      responseType: "code",
                  }
            }
      }
    }
  }`

surely this configuration prevents an authorisation code injected into the redirect URI by a bad actor from being used maliciously? The Authenticator component would try and exchange the authorisation code for a token with our Cognito domain/user pool, which would be rejected, correct me if I'm wrong?

Unless there is something that is not secure about how the Amplify configuration is set up/used in the Authenticator component, meaning that a bad actor could take the authorisation code from the outgoing request and redirect it to their own Cognito domain?

Cheers again for your time.

**Comment by bbdev9805** [comment]
Is there any update on this issue? I am experiencing a similar problem. Since upgrading to Amplify V6, SSO via SAML works for SP-initiated but not for IdP-initiated SSO. I am redirected from the Idp to https://www.example.com/?code=[Authorization code] but cannot obtain the authentication token. This needs to be resolved immediately if IdP-initiated SSO is to be supported. https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-SAML-session-initiation-idp-initiation.html

**Comment by Deanfei** [comment]
I believe it's caused by this: https://github.com/aws-amplify/amplify-js/issues/13306

**Comment by cwomack** [comment]
@Pylinho and others on this issue, thank you for the additional context around what's being asked for in this issue.  This looks to be a duplicate of the feature request detailed within #13343.  We'll close this issue as a duplicate and encourage anyone on this issue to give upvotes, comments, and any further context on #13343.
