### ISSUE TITLE
Amplify Storage uploads objects to S3 at a reduced size

### ISSUE THREAD

**Issue by buildforprod** [aws-amplify/amplify-js#12988]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d21kc3ho29wsqv

### AWS Region

us-east-1

### Amplify Hosting feature

Not Applicable

### Question

I'm observing that objects uploaded to S3 using Amplify Storage are stored at a reduced size! The code for uploading the objects is working fine when tested outside of Amplify. 

The code used in React:

```js
const [files, setFiles] = useState([]);
const handleDrop = async (e) => {
        e.preventDefault();
        const newFiles = [...files];
        for (let i = 0; i < e.dataTransfer.files.length; i++) {
            const file = e.dataTransfer.files[i];
            newFiles.push({ key: file.name, file });
        }
        setFiles(newFiles);
    };

const handleUpload = async () => {
        for (const file of files) {
            const result = await Storage.put(`${city}/${resource}/${file.key}`, file, {
                contentType: file.file.type, });
        }
    };
```

**Comment by nadetastic** [comment]
HI @buildforprod I'm currently investigating this and will follow up soon. In the meantime let me know if there have been any updates or additional context to provide.

**Comment by nadetastic** [comment]
Hi @buildforprod following up here - this isn't something that the library is doing after doing some investigation. As seen on this [thread](https://repost.aws/questions/QUP0kzNY8eSMCmLsGfvwxyXA/awss3uploadtask-error-completing-upload-error-file-size-does-not-match-between-local-file-and-file-on-s3#ANfprXXiM9QGeIUvWyb_DNkQ), this can be the result of s3 not working like a traditional filesystem and rather uses a key and prefix patterns for storage and all permission related information and metadata is controlled at the bucket level along with AWS IAM which is Identity and Access Management system. Hence, we observe this difference in object size.

**Comment by cwomack** [comment]
@buildforprod, wanted to check in and see if you're still experiencing this issue.  Let us know if you got a chance to review the [comment](https://github.com/aws-amplify/amplify-js/issues/12988#issuecomment-1982056854) above and have any additional questions. Thanks!
