### ISSUE TITLE
Update test example in Local Development wiki page

### ISSUE THREAD

**Issue by buggy** [aws-amplify/amplify-js#1301]
Do you want to request a feature or report a bug?

BUG

What is the current behavior?

In the [Local Development wiki page](https://github.com/aws-amplify/amplify-js/wiki/Local-Development) it uses the example 

```sh
yarn test --scope auth
```

but it should be 

```sh
yarn run test --scope @aws-amplify/auth
```

What is the expected behavior?

It should be

```sh
yarn run test --scope @aws-amplify/auth
```

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

N/A

**Comment by jordanranz** [comment]
Fixed this in the Local development wiki page. Thanks for the feedback :D
