### ISSUE TITLE
Amplify's failure to recognize the authenticated session for federated users.

### ISSUE THREAD

**Issue by suhas-007** [aws-amplify/amplify-js#13042]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v20.10.0

### Amplify CLI Version

12.10.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

Amplify's failure to recognize the authenticated session for federated users using the Auth.currentAuthenticatedUser().

### Expected behavior

We should be able to recognize the authenticated session for federated users using the Auth.currentAuthenticatedUser().

### Reproduction steps

1. log into an amplify app using a adfs credentials
2.Try uploading the document using the storage.put method before that  try to  recognize the authenticated session for federated users using the Auth.currentAuthenticatedUser().

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by nadetastic** [comment]
Hi @suhas-007 thank you for opening this issue - and apologies for the delay. Could you share what the error returned from `Auth.currentAuthenticatedUser()` is? Also since you mentioned storage, is the `Storage.put()` command also generating an error?

**Comment by cwomack** [comment]
@suhas-007, let us know if you are still experiencing this issue and can provide the context request above.  Thanks!

**Comment by suhas-007** [comment]
Sorry for the delayed response, yes we are still experiencing the Issue . 

When we login as a adfs user the Auth.currentAuthenticatedUser() is not returning any error but when the DEBUG was enabled we saw the authenticated was set to false , hence we think the storage.put was not working.

Below in the DEBUG log: 

[DEBUG] 48:15.955 Credentials - credentials not changed and not expired, directly return
{accessKeyId: '', sessionToken: '', secretAccessKey: '', identityId: 'us-east-1:517a9728-c678-ce7c-55e9-25118c3a6625', authenticated: false}

Regards
Suhas R

**Comment by cwomack** [comment]
@suhas-007, if `Auth.currentAuthenticatedUser()` is not returning any errors in v5 then we'd expect there to be a `CognitoIUser` object. Can you confirm if you see this?  

As for the `Storage.put()`, do you get an error for this when calling it?

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
