### ISSUE TITLE
CodeDeliveryFailureException on valid email addresses.

### ISSUE THREAD

**Issue by michaelcuneo** [aws-amplify/amplify-js#1305]
Hey guys,

The Authenticator HOC has a bug.

Signup errors with emails, 'Invalid email provided/Unable to send the email.

The email addresses I'm using to test with are fine.

Worked with 1.0.0. Doesn't work with 1.0.2

{[DEBUG] 03:05.347 Analytics - on hub capsule auth: {…}}
[DEBUG] 03:05.347 Analytics - on hub capsule auth
:
data
:
{code: "CodeDeliveryFailureException", name: "CodeDeliveryFailureException", message: "Invalid email provided/Unable to send the email"}
event
:
"signUp_failure"
__proto__
:
Object
__proto__
:

**Comment by powerful23** [comment]
@michaelcuneo Hi I tried on my machine with amplify@1.0.2 and it works fine for me. I created the user pool by choosing option 2: `Email address or phone number - Users can use an email address or phone number as their "username" to sign up and sign in.` ?

**Comment by michaelcuneo** [comment]
My Cognito User Pool was correctly set up, it appears to be working fine today, it must have been a problem on the AWS services end...
