### ISSUE TITLE
AuthProvider.tsx:26 Error signing in AuthUserPoolException: Auth UserPool not configured.

### ISSUE THREAD

**Issue by gjyoungjr** [aws-amplify/amplify-js#13053]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Authentication

### Amplify Version

v6

### Amplify Categories

auth

### Backend

None

### Environment information

<details>

```
System:
    OS: macOS 14.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 85.00 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.1.0 - /opt/homebrew/bin/npm
    pnpm: 8.12.1 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 122.0.6261.69
    Safari: 17.3
  npmPackages:
    @heroicons/react: 2.1.1 => 2.1.1 
    @radix-ui/react-avatar: 1.0.4 => 1.0.4 
    @radix-ui/react-dropdown-menu: 2.0.6 => 2.0.6 
    @radix-ui/react-icons: 1.3.0 => 1.3.0 
    @radix-ui/react-label: 2.0.2 => 2.0.2 
    @radix-ui/react-select: 2.0.0 => 2.0.0 
    @radix-ui/react-separator: 1.0.3 => 1.0.3 
    @radix-ui/react-slot: 1.0.2 => 1.0.2 
    @radix-ui/react-tooltip: 1.0.7 => 1.0.7 
    @tailwindcss/forms: 0.5.3 => 0.5.3 
    @tailwindcss/typography: 0.5.9 => 0.5.9 
    @tiptap/extension-placeholder: 2.2.2 => 2.2.2 
    @tiptap/pm: 2.2.2 => 2.2.2 
    @tiptap/react: 2.2.2 => 2.2.2 
    @tiptap/starter-kit: 2.2.2 => 2.2.2 
    @types/ms: 0.7.31 => 0.7.31 
    @types/node: 18.11.17 => 18.11.17 
    @types/react: 18.0.26 => 18.0.26 
    @types/react-dom: 18.0.9 => 18.0.9 
    @types/react-syntax-highlighter: ^15.5.11 => 15.5.11 
    @types/uuid: 9.0.8 => 9.0.8 
    @vercel/git-hooks: 1.0.0 => 1.0.0 
    ai: 2.2.31 => 2.2.31 
    autoprefixer: 10.4.13 => 10.4.13 
    aws-amplify: 6.0.17 => 6.0.17 
    class-variance-authority: 0.7.0 => 0.7.0 
    clsx: 1.2.1 => 1.2.1 
    date-fns: 2.29.3 => 2.29.3 
    dinero.js: 2.0.0-alpha.8 => 2.0.0-alpha.8 
    eslint: 8.30.0 => 8.30.0 
    eslint-config-next: 13.1.0 => 13.1.0 
    lint-staged: 13.1.0 => 13.1.0 
    ms: 3.0.0-canary.1 => 3.0.0-canary.1 
    next: 14.0.3-canary.7 => 14.0.3-canary.7 
    next-themes: 0.2.1 => 0.2.1 
    novel: 0.1.22 => 0.1.22 
    openai-edge: 1.2.2 => 1.2.2 
    postcss: 8.4.20 => 8.4.20 
    prettier: 2.8.1 => 2.8.1 
    prettier-plugin-tailwindcss: 0.2.1 => 0.2.1 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    react-markdown: 9.0.1 => 9.0.1 
    react-resizable-panels: 1.0.6 => 1.0.6 
    react-syntax-highlighter: 15.5.0 => 15.5.0 
    react-textarea-autosize: 8.5.3 => 8.5.3 
    remark-gfm: 4.0.0 => 4.0.0 
    remark-math: 6.0.0 => 6.0.0 
    server-only: 0.0.1 => 0.0.1 
    styled-components: 6.0.0-beta.2 => 6.0.0-beta.2 
    tailwind-merge: 2.2.0 => 2.2.0 
    tailwindcss: 3.3.1 => 3.3.1 
    tailwindcss-animate: 1.0.7 => 1.0.7 
    typescript: 4.9.4 => 4.9.4 
    use-count-up: 3.0.1 => 3.0.1 
    uuid: 9.0.1 => 9.0.1 
    vercel: 30.2.1 => 30.2.1 
  npmGlobalPackages:
    @amplitude/ampli: 1.31.5
    @aws-amplify/cli: 10.0.0
    @microsoft/rush: 5.89.0
    aws-cdk: 2.130.0
    esbuild: 0.19.2
    expo-cli: 6.0.8
    npm: 10.1.0
    pnpm: 8.12.1
    serverless: 3.25.0
    ts-node: 10.9.1
    typescript: 4.9.5


```

</details>

### Describe the bug

Amplify Auth Configurations is not working even though I've copied the exact code from the docx. 

### Expected behavior

Sign in user.

### Reproduction steps

1. Install `aws-amplify` 
2. Set up Amplify Configs 
3. Try to use any function from `aws-amplify/auth` 

## Amplify Configuration 
```javascript
import { Amplify } from 'aws-amplify';

Amplify.configure({
  Auth: {
    Cognito: {
      userPoolId: process.env.AWS_COGNITO_USER_POOL_ID!,
      userPoolClientId: process.env.AWS_COGNITO_CLIENT_ID!,
      signUpVerificationMethod: 'code', // 'code' | 'link'
    },
  },
});

// You can get the current config object
const currentConfig = Amplify.getConfig();
```

## Using Amplify Auth Functions
```javascript
import { signIn } from 'aws-amplify/auth';

const handleSignIn = async (email: string, password?: string) => {
    try {
      const user = await signIn({ username: email, password });
      console.log(`User ${user.isSignedIn} signed in successfully!`);
    } catch (error) {
      console.error('Error signing in', error);
    }
  };
```

### Log output

<details>

```
AuthProvider.tsx:26 Error signing in AuthUserPoolException: Auth UserPool not configured.
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@aws-amplify+c…odules/@aws-amplify/core/dist/esm/errors/createAssertionFunction.mjs:13:15)
    at assertTokenProviderConfig (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@aws-amplify+c…de_modules/@aws-amplify/core/dist/esm/singleton/Auth/utils/index.mjs:26:62)
    at signInWithSRP (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@aws-amplify+a…/@aws-amplify/auth/dist/esm/providers/cognito/apis/signInWithSRP.mjs:48:97)
    at signIn (webpack-internal:///(app-pages-browser)/./node_modules/.pnpm/@aws-amplify+a…modules/@aws-amplify/auth/dist/esm/providers/cognito/apis/signIn.mjs:42:85)
    at async handleSignIn (webpack-internal:///(app-pages-browser)/./contexts/AuthProvider.tsx:27:26)
hot-reloader-client.js:162 
```

</details>

### Manual configuration

Amplify.configure({
  Auth: {
    Cognito: {
      userPoolId: process.env.AWS_COGNITO_USER_POOL_ID!,
      userPoolClientId: process.env.AWS_COGNITO_CLIENT_ID!,
      signUpVerificationMethod: 'code', // 'code' | 'link'
    },
  },
});

### Additional information and screenshots

amplify version    ` "aws-amplify": "6.0.17"`

**Comment by renanwilliam** [comment]
I have the same error here.

**Comment by gjyoungjr** [comment]
@renanwilliam yeah its frustrating. I've followed the exact [documentation](https://docs.amplify.aws/nextjs/build-a-backend/auth/set-up-auth/)  on Amplify and it still did not work.

**Comment by cwomack** [comment]
Hello, @gjyoungjr and thank you for opening this issue.  Want to make sure I'm not missing something here in the documentation that you linked in comment above vs. the code snippets provided in the issue description.

Did you create new resources via the Amplify CLI command,`amplify add auth` or were you trying to use existing Cognito resources and manually configuring them? Also, are you trying to build this Next.JS app for client side or server-side use?  I ask this because if you're trying to do this client side, I believe you may need to prefix your env variables with `NEXT_PUBLIC_` as shown [here](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser) in the Next.JS docs. 

One thing you can do to verify the user pool is properly in the config at runtime would be to log out the following: 
`console.log(Amplify.getConfig())`.  

CC: @renanwilliam as well

**Comment by gjyoungjr** [comment]
I'm setting up Cognito for client-side auth with existing resources. The hitch might be the missing `NEXT_PUBLIC` prefix on vars, as you suggested. Testing it in a few, will keep you posted! 👍

**Comment by gjyoungjr** [comment]
ok, this issue can be closed. @cwomack your last suggestion was correct my issue was my env vars were missing the prefix `NEXT_PUBLIC`. Appreciate the help 🤝 

@renanwilliam were you able to solve your problem?

**Comment by renanwilliam** [comment]
No, my problems is not related with the environment variables. The values are OK on Amplify.configure

I have a central class AmplifyAccessStore just to manage the configs:
```typescript
import type {ResourcesConfig} from "aws-amplify";
import {Amplify} from "aws-amplify";

export default class AmplifyAccessStore {
  static changeConfig(configuration: ResourcesConfig) {
    Amplify.configure(configuration);
  }

  static getConfig() {
    return Amplify.getConfig();
  }
}
```

My function looks like:
```typescript
import {signIn} from 'aws-amplify/auth';
import type {ResourcesConfig} from "aws-amplify";
import AmplifyAccessStore from "@/utils/amplifyAccessStore";
//...other imports

//...
async function login(email: string, password: string, companyId: string) {
    setIsLoading(true);
    try {
      const companies = await searchCompanies({accountName: companyId});
      if (companies.length > 0) {
        const company = companies[0];

        const amplifyConfig: ResourcesConfig = {
          Auth: {
            Cognito: {
              // loginWith: {
              //   email: true
              // },
              userPoolId: (company.object.cognito?.dedicated?.UserPoolId ?? company.object.cognito?.shared?.UserPoolId) as string,
              userPoolClientId: (company.object.cognito?.dedicated?.userPoolClientId ?? company.object.cognito?.shared?.userPoolClientId) as string,
              identityPoolId: (company.object.cognito?.dedicated?.IdentityPoolId ?? company.object.cognito?.shared?.IdentityPoolId) as string,
              signUpVerificationMethod: 'code'
            },
          }
        };
        AmplifyAccessStore.changeConfig(amplifyConfig);
        localStorage.setItem('@mycompany/amplify-config', JSON.stringify(AmplifyAccessStore.getConfig()));

        const signResponse = await signIn({
          username: email,
          password,
          options: {
            authFlowType: 'USER_PASSWORD_AUTH'
          }
        });

        console.log(signResponse);

        if (initialState?.loadDataFromServer) {
          const remoteInitialState = await initialState.loadDataFromServer();
          await setInitialState((s) => ({
            ...s,
            ...remoteInitialState
          }));
        }
      }
    } finally {
      setIsLoading(false);
    }
  }
//other irrelevant code
  ```

if I check my localstorage, I can see the config:
![image](https://github.com/aws-amplify/amplify-js/assets/19995615/0e05695a-930e-45d1-8b46-de5618706904)

**Comment by gjyoungjr** [comment]
If its not env vars, what is your core problem? @renanwilliam

**Comment by cwomack** [comment]
@renanwilliam, do you have a sample repo that can reproduce what you're experiencing? And can you confirm if you created new Auth resources via `amplify add auth` or had any different reproduction step than detailed here?

I don't think the code snippet you provided should cause any problem, but feel free to create a [new issue](https://github.com/aws-amplify/amplify-js/issues/new/choose) if you'd like so we can capture what's happening in better detail.

**Comment by renanwilliam** [comment]
I have deleted node_modules and updated them to the latest version, and it's working now. It's all ok now.

**Comment by nadetastic** [comment]
@renanwilliam Glad you were able to get this resolved. Will mark this issue as closed for now.
