### ISSUE TITLE
gen2 Please add sortDirection support in the client api

### ISSUE THREAD

**Issue by sevenkkk** [aws-amplify/amplify-js#13055]
### Describe the feature you'd like to request

Please add sortDirection support in the client api

DB schema 
`Todo: a
    .model({
      todoId: a.id().required(),
      status: a.string().required(),
      content: a.string(),
    })
    .identifier(['todoId','status'])`

    
Client Api:
`client.models.Todo.list();`
No sortDirection parameter

### Describe the solution you'd like

Hope to support something like this:
`client.models.Todo.list({
   sortDirection: ModelSortDirection.DESC,
});`

### Describe alternatives you've considered

none

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cwomack** [comment]
Hello, @sevenkkk 👋.  Appreciate you creating this feature request and wanted to let you know that we indeed have it on our Gen2 Roadmap to include a `sortDirection` param for queries!  We'll update this issue when progress is made and ping you if there's any further questions. Thanks!

**Comment by renebrandel** [comment]
we've just launched this in the latest aws-amplify version and also upgrade your backend to use the latest beta:
```
npm i aws-ampify@latest @aws-amplify/backend@beta @aws-amplify/backend-cli@beta
```
