### ISSUE TITLE
AWS Amplify Storage

### ISSUE THREAD

**Issue by saharJ95** [aws-amplify/amplify-js#13065]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React, Next.js

### Amplify APIs

Storage

### Amplify Version

v6

### Amplify Categories

storage

### Backend

None

### Environment information

Production and Development

### Describe the bug

Unable to access bucket which is already described in Configuration. I am getting  missing bucket name issue  

Can You please Identify if there is anything wrong with config things?

### Expected behavior

Upload images in multiple bucket

### Reproduction steps

Configure  Storage (s3 bucket) in Amplify
Upload Data in respective buckets

### Code Snippet

![image](https://github.com/aws-amplify/amplify-js/assets/113641921/b87fe029-4b79-4122-a83b-bb7f51219f50)

This is Amplify.getConfig() result
![image](https://github.com/aws-amplify/amplify-js/assets/113641921/f167d7f1-cdce-4301-b391-446310e31e8c)

![image](https://github.com/aws-amplify/amplify-js/assets/113641921/3f072ac1-b964-48c6-a445-c72008bfd6d3)

### Log output

![image](https://github.com/aws-amplify/amplify-js/assets/113641921/5bbc0783-e876-4f19-8efd-a45b92ae3646)

**Comment by saharJ95** [comment]
Hi @cwomack ,
Any update on this ? I am waiting for your response

**Comment by saharJ95** [comment]
Hi @nadetastic , Thankyou for your response.

**Comment by saharJ95** [comment]
One more thing i want to know how we can upload files in multiple buckets ? @nadetastic

**Comment by nadetastic** [comment]
@saharJ95 glad to hear that you were unblocked. As for your follow up question, Amplify doesn't currently support multiple buckets, and we are tracking this as a feature request on this github issue - https://github.com/aws-amplify/amplify-cli/issues/5836 - feel free to subscribe and follow to the issue for whenever we have future updates. There may also be some workarounds in the comments that could work for you.
