### ISSUE TITLE
npm version behind: 4.0.18, please publish the latest

### ISSUE THREAD

**Issue by brianmgray** [aws-amplify/amplify-js#13067]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

GraphQL API

### Amplify Version

v6

### Amplify Categories

api

### Backend

Amplify Gen 2 (Preview)

### Environment information

```
# Put output below this line


```

  System:
    OS: macOS 14.3.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 3.48 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.11.0/bin/yarn
    npm: 10.3.0 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.15.3 - ~/.nvm/versions/node/v20.11.0/bin/pnpm
  Browsers:
    Chrome: 122.0.6261.69
    Safari: 17.3.1
  npmPackages:
    @angular-devkit/build-angular: ^17.2.0 => 17.2.0 
    @angular-eslint/builder: 17.2.1 => 17.2.1 
    @angular-eslint/eslint-plugin: 17.2.1 => 17.2.1 
    @angular-eslint/eslint-plugin-template: 17.2.1 => 17.2.1 
    @angular-eslint/schematics: 17.2.1 => 17.2.1 
    @angular-eslint/template-parser: 17.2.1 => 17.2.1 
    @angular/animations: ^17.2.1 => 17.2.1 
    @angular/cli: ^17.2.0 => 17.2.0 
    @angular/common: ^17.2.1 => 17.2.1 
    @angular/compiler: ^17.2.1 => 17.2.1 
    @angular/compiler-cli: ^17.2.1 => 17.2.1 
    @angular/core: ^17.2.1 => 17.2.1 
    @angular/forms: ^17.2.1 => 17.2.1 
    @angular/platform-browser: ^17.2.1 => 17.2.1 
    @angular/platform-browser-dynamic: ^17.2.1 => 17.2.1 
    @angular/router: ^17.2.1 => 17.2.1 
    @luckycatfactory/esbuild-graphql-loader: ^3.8.1 => 3.8.1 
    @types/jasmine: ~5.1.0 => 5.1.4 
    @typescript-eslint/eslint-plugin: 6.19.0 => 6.19.0 
    @typescript-eslint/parser: 6.19.0 => 6.19.0 
    aws-amplify: ^6.0.17 => 6.0.17 
    aws-amplify-monorepo: github:aws-amplify/amplify-js#aws-amplify-angular@6.0.18 => 0.1.30 
    esbuild: ^0.20.1 => 0.20.1 
    eslint: ^8.56.0 => 8.56.0 
    graphql: ^16.8.1 => 16.8.1 
    graphql-tag: ^2.12.6 => 2.12.6 
    jasmine-core: ~5.1.0 => 5.1.2 
    json: ^11.0.0 => 11.0.0 
    karma: ~6.4.0 => 6.4.2 
    karma-chrome-launcher: ~3.2.0 => 3.2.0 
    karma-coverage: ~2.2.0 => 2.2.1 
    karma-jasmine: ~5.1.0 => 5.1.0 
    karma-jasmine-html-reporter: ~2.1.0 => 2.1.0 
    rimraf: ^5.0.5 => 5.0.5 
    rxjs: ~7.8.0 => 7.8.1 
    tslib: ^2.3.0 => 2.6.2 
    typescript: ~5.3.2 => 5.3.3 
    zen-observable-ts: ^1.1.0 => 1.1.0 
    zone.js: ~0.14.3 => 0.14.3 
  npmGlobalPackages:
    @angular/cli: 17.1.1
    @aws-amplify/cli: 12.10.1
    aws-amplify-angular: 6.0.60
    aws-amplify: 6.0.15
    corepack: 0.23.0
    netlify-cli: 17.15.3
    npm: 10.3.0
    nx: 18.0.4
    pnpm: 8.15.3
    serverless: 3.38.0

### Describe the bug

When I run `npm install @aws-amplify/api-graphql`, it installs version `4.0.18` even though the latest version in Github is `6.0.18`–2 major versions later.

### Expected behavior

Version `6.0.18` gets installed

### Reproduction steps

Run `npm install @aws-amplify/api-graphql`

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

![Screenshot 2024-02-28 at 11 34 00 AM](https://github.com/aws-amplify/amplify-js/assets/638937/0b77efe0-f958-4d86-9b7c-e26d707ab9d4)

![Screenshot 2024-02-28 at 11 41 50 AM](https://github.com/aws-amplify/amplify-js/assets/638937/7c18d387-607f-4dcc-a525-8776dc587a57)

**Comment by cwomack** [comment]
Hello, @brianmgray and thanks for creating this issue.  You should only need to install the umbrella package of `aws-amplify` and not specifically the scoped package for `@aws-amplify/api-graphql`.  Was there a docs page that suggested otherwise when setting up your Gen2 app?

It looks like v6.0.18 is the current latest version that is installed when running the command to install the `aws-amplify` umbrella package.

**Comment by brianmgray** [comment]
Hi @cwomack , ah ok I think I figured out the issue. During `amplify push` I chose `angular` as the `code generation target language`.

This generated a file with this line in it: 
`import API, { graphqlOperation, GraphQLResult } from "@aws-amplify/api-graphql";`

This caused a compile error in the generated code. I thought the issue was due to the old version, and indeed upgrading it did fix the issue. 

But I rechecked the [guide](https://docs.amplify.aws/angular/start/getting-started/data-model/) I am following and indeed for the Angular guide, it tells me to choose `typescript`, not `angular`.
![Screenshot 2024-02-28 at 3 59 47 PM](https://github.com/aws-amplify/amplify-js/assets/638937/2ab4319d-4df0-4bb7-b676-5dc49ce40f2b)

I retried with these settings and I don't get any compile errors. Working on getting it running now, but you can close this issue. 

I'm interested to understand the purpose of the `angular` option though, or suggest it get a different name if it's not supposed to be used in an Angular application.

**Comment by brianmgray** [comment]
See above - use `typescript` as the `code generation target language` for angular, not `angular`
