### ISSUE TITLE
Change password basic functionality is not working

### ISSUE THREAD

**Issue by andrew-aladev** [aws-amplify/amplify-js#1306]
I started to investigate amazon amplify auth 2 days ago, created sample react application using `withAuthenticator`. I was wondering how _cognito_ works.

Than I created a new user in pool using amazon console. His status is `FORCE_CHANGE_PASSWORD`. Than I tried to login using my sample application.

I saw that `ChallengeName: USER_SRP_AUTH` query passed. "Sign In" block disappeared and `Change Password` block appeared. I've randomized new password and pressed "Change" button...

I received the following result for `ChallengeName: NEW_PASSWORD_REQUIRED`:

> {"__type":"InvalidParameterException","message":"Invalid attributes given, name is missing"}

![screenshot_2018-07-25_15-35-14](https://user-images.githubusercontent.com/941925/43201653-c28d0816-9021-11e8-9332-86601b1611fe.png)

So your basic auth functionality is not working. How it is possible for such popular _amazon_ company?

![risitas](https://user-images.githubusercontent.com/941925/43202370-ff344854-9023-11e8-987a-f0bf3e0f73f9.gif)

----

We couldn't integrate our new application today with auth service that doesn't work. Maybe this issue is related with https://github.com/aws/aws-sdk-net/issues/972, I don't know and I shouldn't know.

Please implement unit tests for all packages in `packages` folder starting from core packages. Than please implement integration tests for all products that you are selling. It looks like you will find thousands of issues.

**Comment by andrew-aladev** [comment]
UPD we can compare reset password form from cognito.

![screenshot_2018-07-25_16-45-43](https://user-images.githubusercontent.com/941925/43205011-05ec5c52-902b-11e8-940b-7c00e36ea9c0.png)

with [packages/aws-amplify-react/src/Auth/RequireNewPassword.jsx](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Auth/RequireNewPassword.jsx)

```
<SectionHeader theme={theme}>{I18n.get('Change Password')}</SectionHeader>
<SectionBody>
    <InputRow
        autoFocus
        placeholder={I18n.get('New Password')}
        theme={theme}
        key="password"
        name="password"
        type="password"
        onChange={this.handleInputChange}
    />
    <ButtonRow theme={theme} onClick={this.change}>
        {I18n.get('Change')}
    </ButtonRow>
</SectionBody>
<SectionFooter theme={theme}>
    <Link theme={theme} onClick={() => this.changeState('signIn')}>
        {I18n.get('Back to Sign In')}
    </Link>
</SectionFooter>
```

So cognito deployed new version of backend which requires `name`, `phone`, `family name`, etc for password change. Amazon's `amplify` developers ... couldn't know about that because they have no unit, not integrations tests. They just think that it is still working.

If I want to develop an application using `amplify-js` I need to update all their components to fit with recent version of cognito backend by myself.

![large](https://user-images.githubusercontent.com/941925/43206016-5a2d9cfc-902d-11e8-836c-1d027a3bb81a.jpg)

**Comment by rudyhadoux** [comment]
Same problem for me.

**Comment by rudyhadoux** [comment]
Did you use this ? It works.
import { Auth } from 'aws-amplify';

Auth.forgotPassword(username)
    .then(data => console.log(data))
    .catch(err => console.log(err));

// Collect confirmation code and new password, then
Auth.forgotPasswordSubmit(username, code, new_password)
    .then(data => console.log(data))
    .catch(err => console.log(err));

**Comment by andrew-aladev** [comment]
@rudyhadoux I am just ignoring current `aws-amplify-react` folder. I think it is abandoned and can be used as an old example.

```
const attributes = get(user, 'challengeParam.requiredAttributes');
if (attributes == null) ...
const attributesData = pick(data, attributes);
Auth.completeNewPassword(user, password, requiredAttributes)...
```

works fine.

**Comment by rudyhadoux** [comment]
Yes it works, I was just wrong in the order of parameters...
