### ISSUE TITLE
Authentication flow issue aws-amplify >= 6.0.10

### ISSUE THREAD

**Issue by danieljandey** [aws-amplify/amplify-js#13070]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

Authentication

### Amplify Version

v6

### Amplify Categories

auth

### Backend

None

### Environment information

<details>

```
# Put output below this line

System:
    OS: Linux 5.15 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1265U
    Memory: 10.25 GB / 15.54 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.11.1 - /usr/local/share/nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.2.4 - /usr/local/share/nvm/versions/node/v20.11.1/bin/npm
    pnpm: 8.15.3 - /usr/local/share/nvm/versions/node/v20.11.1/bin/pnpm
  npmPackages:
    @vitejs/plugin-vue: ^4.2.3 => 4.6.2 
    aws-amplify: 6.0.10 => 6.0.10 
    aws-amplify/adapter-core:  undefined ()
    aws-amplify/analytics:  undefined ()
    aws-amplify/analytics/kinesis:  undefined ()
    aws-amplify/analytics/kinesis-firehose:  undefined ()
    aws-amplify/analytics/personalize:  undefined ()
    aws-amplify/analytics/pinpoint:  undefined ()
    aws-amplify/api:  undefined ()
    aws-amplify/api/server:  undefined ()
    aws-amplify/auth:  undefined ()
    aws-amplify/auth/cognito:  undefined ()
    aws-amplify/auth/cognito/server:  undefined ()
    aws-amplify/auth/enable-oauth-listener:  undefined ()
    aws-amplify/auth/server:  undefined ()
    aws-amplify/datastore:  undefined ()
    aws-amplify/in-app-messaging:  undefined ()
    aws-amplify/in-app-messaging/pinpoint:  undefined ()
    aws-amplify/push-notifications:  undefined ()
    aws-amplify/push-notifications/pinpoint:  undefined ()
    aws-amplify/storage:  undefined ()
    aws-amplify/storage/s3:  undefined ()
    aws-amplify/storage/s3/server:  undefined ()
    aws-amplify/storage/server:  undefined ()
    aws-amplify/utils:  undefined ()
    axios: ^1.6.7 => 1.6.7 
    bootstrap: ^5.3.3 => 5.3.3 
    eslint: ^8.56.0 => 8.56.0 
    eslint-plugin-vue: ^9.21.1 => 9.21.1 
    moment: ^2.30.1 => 2.30.1 
    vite: ^4.5.2 => 4.5.2 
    vue: ^3.4.19 => 3.4.19 
    vue-multiselect: ^3.0.0-beta.3 => 3.0.0-beta.3 
    vue-router: ^4.2.5 => 4.3.0 
  npmGlobalPackages:
    aws-cdk: 2.129.0
    corepack: 0.23.0
    npm: 10.2.4
    pnpm: 8.15.3

```

</details>

### Describe the bug

Steps: 
1. Attempting to retrieve the currentUser throws an error, 'UserUnAuthenticatedException' which is expected. 
2. The signInWithRedirect function is called and is successful. This performs the correct redirect.
3. Attempting to retrieve the currentUser for the second time after the signIn flow has completed, the 'UserUnAuthenticatedException' exception throws even though we have just signed in.
4. The flow attempts to sign in again due to the exception, but this time the 'UserAlreadyAuthenticatedException' error throws.

Something has been changed between versions 6.0.9 - 6.0.10 that changes the behavior of the flow.

```javascript
try{
console.log("Retrieving current user...")
await Auth.getCurrentUser() 
} catch(e) {
console.log("Signing in...")
await Auth.signInWithRedirect({ provider: { custom: "Azure" } });
console.log("Signed in...")
}
```

```console

Retrieving current user...

UserUnAuthenticatedException: User needs to be authenticated to call this API.
    at assertAuthTokens (http://localhost:5000/node_modules/.vite/deps/chunk-L5BIKJHY.js?v=d8563c0c:6035:11)
    at getCurrentUser (http://localhost:5000/node_modules/.vite/deps/chunk-L5BIKJHY.js?v=d8563c0c:6082:3)
    at async http://localhost:5000/src/main.js?t=1709162623500:32:24
chunk-L5BIKJHY.js?v=d8563c0c:8416 Uncaught (in promise) 

Signing in...

Signed in...

Retrieving current user...

UserUnAuthenticatedException: User needs to be authenticated to call this API.
    at assertAuthTokens (http://localhost:5000/node_modules/.vite/deps/chunk-L5BIKJHY.js?v=d8563c0c:6035:11)
    at getCurrentUser (http://localhost:5000/node_modules/.vite/deps/chunk-L5BIKJHY.js?v=d8563c0c:6082:3)
    at async http://localhost:5000/src/main.js?t=1709162623500:32:24
chunk-L5BIKJHY.js?v=d8563c0c:8416 Uncaught (in promise) 

console.log("Signing in...")

UserAlreadyAuthenticatedException: There is already a signed in user.
    at assertUserNotAuthenticated (http://localhost:5000/node_modules/.vite/deps/chunk-L5BIKJHY.js?v=d8563c0c:8416:11)
    at async Module.signInWithRedirect (http://localhost:5000/node_modules/.vite/deps/chunk-L5BIKJHY.js?v=d8563c0c:10209:3)
    at async http://localhost:5000/src/main.js?t=1709162623500:51:13
```

Working fine from v6.0.0 -> v.6.0.9

Attempting to get some more details.

Edit: Seems to be an issue with how quickly you call getCurrentUser after you authenticate.

Calling getCurrentUser near instantly after authenticating doesn't register that you're authed. By the time you get to the 'catch' to auth again the 'UserAlreadyAuthenticatedException' exception occurs.

For example, if I adjust the code to add a minor delay to the retrieval of 'getCurrentUser' the flow works again:

```javascript
try{
await new Promise(r => setTimeout(r, 100));
await Auth.getCurrentUser() 
} catch(e) {
await Auth.signInWithRedirect({ provider: { custom: "Azure" } });
}
```

I'm not exactly sure what is happening in the background as I haven't dug deep yet, but is it possible to only return on "signInWithRedirect" once the session data has been stored?

### Expected behavior

If logged out, the getCurrentUser() throws an error, and when attempting to authenticate the process flows and does not throw the 'UserAlreadyAuthenticatedException' exception

### Reproduction steps

Auth.signOut
Auth.getCurrentUser()
Auth.signInWithRedirect({ provider: { custom: "Azure" } });

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by didemkkaslan** [comment]
Hello @danieljandey  `signInWithRedirect({ provider: { custom: "Azure" } });` using signInWithRedirect I needed to put a listener to the page you redirect user after sign in  so that it can pick up the authenticated user

import 'aws-amplify/auth/enable-oauth-listener';

I'm not sure if its the cause of the problem but this section might be helpful 
https://docs.amplify.aws/javascript/build-a-backend/auth/add-social-provider/#required-for-multi-page-applications-complete-social-sign-in-after-redirect

**Comment by cwomack** [comment]
@danieljandey, I believe the comment above is correct.  It sounds like you'll need to import the OAuth Listener if the page you're redirecting from is not the same.  Please review the comment above and let us know if that unblocks you.  

Thank you, @didemkkaslan for helping out others in the community with your comment!

**Comment by danieljandey** [comment]
Hi @cwomack , even after importing 'import 'aws-amplify/auth/enable-oauth-listener';' the error is still occurring.

The sign in and redirect pages / paths are the same.

**Comment by cwomack** [comment]
@danieljandey, thank you for the response.  We'll investigate this further for versions after v6.0.9.

**Comment by israx** [comment]
hello @danieljandey . Can you upgrade to the latest version of Amplify and see if the issue still persists ? Please delete your `node_modules` and `package.lock.json` before bumping the version

**Comment by danieljandey** [comment]
Hi @israx . I have upgraded to v6.0.21 and the issue is still persisting, with and without the 'aws-amplify/auth/enable-oauth-listener' import

Happy to provide more info or a full code snippet if it will help.

**Comment by israx** [comment]
Thank you for the clarification. Yeah please provide some code snippets. I'll try to reproduce this issue and follow up with next steps. Thanks for the patience.

**Comment by israx** [comment]
hello @danieljandey . I was able to reproduce this issue using Vue. I'll go ahead and mark it as a bug. I'll keep following up with next steps.

**Comment by israx** [comment]
hello @danieljandey . The fix was released on the [latest](https://www.npmjs.com/package/aws-amplify?activeTab=versions) version of Amplify. Can you upgrade your amplify dependency and test it out ? . Please, don't forget to delete your `node_modules` and `package.lock.json` file

**Comment by danieljandey** [comment]
Hey @israx . Lol, I just started to troubleshoot the package last night and was way off base with the fix.

Looks like it's working now, nice find :) 

Thanks for that!!

**Comment by chai86** [comment]
Hi @israx, i am using Amplify v6.4.3 and i am getting this error: `UserAlreadyAuthenticatedException`. Once i've signed out it's no issue, but if i simply refresh my browser or rebuild the application, i get back to the my Login page with the above exception (when i already have logic to check auth status and navigate straight to my home page). This never happened with v5. So there is something not quite right here. I do this on my login page and pass props to the main App entry page:

**Login.js**
```
const handleLogin = async () => {
        try {
            console.log('Login');
            console.log(username);
            console.log(password);    

            await signIn({username, password})

            props.updateAuthStatus(true)
            navigate('/questionform')
        } catch (err) { console.log(err) }
    }
```

Then in **App.js**
```
function App() {
  const [isAuthenticated, setIsAuthenticated] = useState(false)

  function updateAuthStatus(authStatus) {
    setIsAuthenticated(authStatus)
  }

  return (
    <div>
      <SiteNav isAuthenticated={isAuthenticated} updateAuthStatus={updateAuthStatus} />
      <Routes>
        <Route path='*' element={<HomePage isAuthenticated={isAuthenticated} />} />
        <Route path='/' exact={true} element={<HomePage isAuthenticated={isAuthenticated} />} />
        <Route path='/login' element={<LoginPage updateAuthStatus={updateAuthStatus} />} />
        <Route path='/register' element={<RegisterPage />} />
        <Route path='/validate' element={<ValidatePage />} />
        <Route path='/questionform' element={<QuestionForm isAuthenticated={isAuthenticated} />} />
      </Routes>
      <SiteFooter />
    </div>
  )
};
```

**Comment by israx** [comment]
Hello @chai86. The `UserAlreadyAuthenticatedException` is thrown when `authentication` tokens are present in `localStorage`, and when the `sign-in` or `signInWithRedirect` APIs are called. V5 allowed to sign-in multiple times, but that is not ideal because auth tokens could get mixed up.

In order to update the `signInStatus`, you will want to check a user is already authenticated first by calling the `getCurrentUser` API and then navigate the user to the `login` or `authenticated` routes.

**Comment by chai86** [comment]
Thank you. I have this at my App.js entry page now. I don't necessarily think its the best way, but it doesn't throw the `UserAlreadyAuthenticatedException ` error anymore:
```

 useEffect(() => {
    async function checkUserAlreadySignedIn(){
      try {
        const { username, userId, signInDetails } = await getCurrentUser();
        console.log("user: " + username);
        updateAuthStatus(true);
      }
      catch (err) { 
        console.log("getCurrentUser error: " + err);
        updateAuthStatus(false);
      }
    }
    checkUserAlreadySignedIn();
  }, []);
```
