### ISSUE TITLE
SSR Error: User is not authenticated

### ISSUE THREAD

**Issue by reeslabree** [aws-amplify/amplify-js#13112]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Next.js

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

Connecting to app after deploying, the app recognizes that I am logged in, but does not recognize server-side and won't return me user-specific data, rather just displays the blank dashboard.

### What's the expected behaviour?

Open app, log in, and am returned data associated with my Cognito user sub.

### Help us reproduce the bug!

I'm not sure - this works locally just fine but only fails on deployment.

### Code Snippet

```typescript
// getServerSideProps
try {
    const { Auth } = withSSRContext(context);

    const user = await Auth.currentAuthenticatedUser();
    ....
} catch(e) {
  console.log(e)
}

// _app.tsx
import config from "../aws-exports";

Amplify.configure({
  ...config,
  ssr: true,
});
Auth.configure({
  ...config,
  ssr: true,
});
```

### Log Output

<details>

```
START RequestId: 357f7a06-dab7-4841-984f-bd22217f68ce Version: 10
[logs related to sensitive information, thus redacted]
2023-02-17T22:41:26.683Z	357f7a06-dab7-4841-984f-bd22217f68ce	INFO	SSR Error: The user is not authenticated
2023-02-17T22:41:26.821Z	357f7a06-dab7-4841-984f-bd22217f68ce	ERROR	(node:8) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
END RequestId: 357f7a06-dab7-4841-984f-bd22217f68ce
```

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
