### ISSUE TITLE
Getting the error 'await is a reserved word'

### ISSUE THREAD

**Issue by ykbryan** [aws-amplify/amplify-js#1312]
**Do you want to request a feature or report a bug?**

Report a bug

**What is the current behavior?**

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

I am developing a prototype with React Native and I have a SyntaxError due to "await is a reserved word".
Followed the exact steps provided in the AWS amplify doc. 
https://aws-amplify.github.io/amplify-js/media/api_guide#simple-query

The **solution** is to wrap the await code in an arrow function with `async()` as follow: 
```
  getAllEvents = async () => {
    const AllEventsQuery = `query listEvents{
      listEvents{
        items{
          Title
          Description
          }
        }
      }`;
    var allEvents = await API.graphql(graphqlOperation(AllEventsQuery));
    console.log(allEvents);
  }

```

**What is the expected behavior?**

To be able to query the list of events.

**Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?**

```
    "aws-amplify": "^1.0.2",
    "aws-amplify-react-native": "^1.0.2",
    "react": "16.3.1",
    "react-native": "~0.55.2",
```

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by manueliglesias** [comment]
Hi @ykbryan 

The sample you are following uses the new `async`/`await` keywords from ES2017. `await` must be used within an `async` function (see [here](https://davidwalsh.name/async-await))

If you want to do the same thing with promises (instead of async/await) it could look something like this:

```javascript
API.graphql(graphqlOperation(ListEvents)).then(function(allEvents) {
    console.log(allEvents);
});
```

This could be stated more clearly in the docs, so I'll be sharing this feedback with the team.

**Comment by ykbryan** [comment]
@manueliglesias agree, pls update the documentation :) thanks!
