### ISSUE TITLE
[Question] Is there a way to get the user attributes before the 2FA / MFA?

### ISSUE THREAD

**Issue by philippefutureboy** [aws-amplify/amplify-js#1315]
I would like to do an interface along the lines of [this one](https://dribbble.com/shots/4105017-Two-step-verification-login), where the user is displayed their phone number when requested to answer the SMS auth challenge. Is there a way to get the user info before the MFA challenge is successful?

I have attempted multiple methods on the Auth object (userAttributes, currentUser, currentUserInfo, currentSession) to no avail. I went through the [API docs](https://aws-amplify.github.io/amplify-js/api/classes/authclass.html) without finding any further clues.

Any way I can do this?

Thanks for your answer!

Have a great day 🦄 ✨

**Comment by powerful23** [comment]
@philippefutureboy from what I know you can't because all those methods need a valid access_token which is not available before the user is authenticated.

**Comment by philippefutureboy** [comment]
Hmm, I see. Any way I can return extra payload in the object returned by `Auth.signIn` through a pre/post authentication lambda trigger?

**Comment by mlabieniec** [comment]
technically you could proxy the call and return what-ever you like in the pre-authentication trigger:
https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-authentication.html
