### ISSUE TITLE
Remembered device's friendly name

### ISSUE THREAD

**Issue by Milad-Akarie** [aws-amplify/amplify-js#13165]
### Is this related to a new or existing framework?

Angular

### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

When listing the remembered devices there's no way to display a friendly name for users to recognize the them. 
I tried passing `deviceFriendlyName` with both `verifyTOTPSetup` and `confirmSignIn` but I still can't get the name I pass inside `AWSAuthDevice`

### Describe the solution you'd like

I'd like to have access to the `deviceFriendlyName` I assign inside `AWSAuthDevice`

### Describe alternatives you've considered

I can not think of any

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cwomack** [comment]
Hello, @Milad-Akarie and sorry to hear you're running into this issue.  This sounds like it is related to the known bug of #12854, but wanted to double check with you on the API's that you're trying to use here.  Is the intent here to use the v6 Auth API's of `rememberDevice()` ([docs link](https://docs.amplify.aws/react-native/build-a-backend/auth/remember-device/#remember-device)) and `fetchDevices()` ([docs link](https://docs.amplify.aws/react-native/build-a-backend/auth/remember-device/#fetch-devices)) to get a device's friendly name?  

If so, can you review the linked/related issue and let me know if it captures the scope of what you're reporting here?  We can track any additional context or requests within that issue if so as we work on a fix.  Thanks!

**Comment by Milad-Akarie** [comment]
Hey @cwomack Yup, closing this as a duplicate of https://github.com/aws-amplify/amplify-js/issues/12854

**Comment by cwomack** [comment]
Appreciate the quick reply on this, @Milad-Akarie! Feel free to leave any additional context, upvotes, etc. on that issue.
