### ISSUE TITLE
oauthTokenRefreshException thrown but not using oauth flow

### ISSUE THREAD

**Issue by clement-faure** [aws-amplify/amplify-js#13168]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Authentication

### Amplify Version

v6

### Amplify Categories

auth

### Backend

None

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

This error is thrown on my production environment, but i have never use oauth flow.

![Capture d’écran 2024-03-25 à 10 36 14](https://github.com/aws-amplify/amplify-js/assets/23209488/1e62cfd9-5ddc-4730-b8ba-99e549dca192)

### Expected behavior

Token refresh should refresh normally.

### Reproduction steps

1) Upgrade from amplify v5 to v6 on authentication flow
2) Randomly get refresh token error regarding oauth flow

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

![Capture d’écran 2024-03-25 à 10 52 12](https://github.com/aws-amplify/amplify-js/assets/23209488/63e04251-5a4c-4266-a056-6f6c17be02ae)

**Comment by israx** [comment]
hello @clement-faure . Can you please expand how you are able to reproduce this issue ? Plase share,
- amplify configuration
- code snippets
- dev environment

**Comment by israx** [comment]
the `OAuthTokenRefreshException` is usually thrown when storage doesn't have a `refresh_token` . Can you make sure tokens are stored in the cookies ?

**Comment by clement-faure** [comment]
Thank you for your quick response !

Amplify configuration :

<img width="645" alt="Capture d’écran 2024-03-25 à 14 09 45" src="https://github.com/aws-amplify/amplify-js/assets/23209488/0eeaead1-c8e7-44e4-bf6f-c8edb7193173">

Amplify storage mode (default localeStorage) : 

<img width="882" alt="Capture d’écran 2024-03-25 à 14 10 26" src="https://github.com/aws-amplify/amplify-js/assets/23209488/acc2e008-22fc-407f-859c-289981019144">

When use click on remember checkbox true, storage in persisted in local storage, otherwise stored in cookies for session

**Comment by israx** [comment]
I think the library might not being able to pull in the tokens from the current storage mechanism. Hence the error showed. Can you run your application and do the following,

1. authenticate.
2. call `fetchAuthSession` with the `forceRefresh` flag enabled.
3. check if the error was thrown 
4. check where tokens are stored

In addition to that, we added additional support for [Next-JS](https://docs.amplify.aws/nextjs/build-a-backend/server-side-rendering/nextjs/) as well and the configuration requires to pass the SSR flag.

```
Amplify.configure(config, {
  ssr: true // required when using Amplify with Next.js
});
```

**Comment by clement-faure** [comment]
I'm gonna try that right away. I'm not using SSR on my application, do i have to enabled SSR flag necessarily ?

**Comment by clement-faure** [comment]
I confirm that all is working fine when reproducing your steps.

I think the error is linked to aws-amplify upgrade, my customer probably logged in on aws amplify v5, and when reloading app and refreshing app on aws amplify v6, the error has been thrown ? But it's not happening to all my customers.. very strange.

**Comment by israx** [comment]
If Amplify is used only on the client side, then you wouldn't need the SSR flag. 

Strange, we kept the same key format between v5 and v6, so the refresh token should be there. Probably asking the end user to delete their keys and authenticate again might help.

**Comment by cwomack** [comment]
@clement-faure, I'll put the `pending-response` label on this issue for now until we hear back from you on implementing @israx's guidance above.

**Comment by cwomack** [comment]
@clement-faure, wanted to check in and see if you're still experiencing this.  Let us know if you are!

**Comment by clement-faure** [comment]
> put the `pending-response` label on this issue for now until we hear back from you on implementing @israx's guidance above.

The issue didn't happened again so i think we can close this issue safely !

**Comment by cwomack** [comment]
@clement-faure, appreciate the quick reply! I'll close this issue then for now, but feel free to leave further comments or context if this persists.
