### ISSUE TITLE
Resending confirmation code is working but not sending email.

### ISSUE THREAD

**Issue by therealkh** [aws-amplify/amplify-js#13166]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Version

v5

### Backend

None

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I am working on user flow when user creates account, but doesn't verify it. Closes app and tries to sing in.
Here is my HubListener code snippet:
```typescript
          case 'signIn_failure': {
          if (event.payload.data.code === 'UserNotConfirmedException') {
            Auth.resendSignUp(values.email)
              .then((data) => {
                return navigation.navigate(Routes.confirmSignUpScreen, {
                  username: values.email,
                  isSms: data.CodeDeliveryDetails.AttributeName !== 'email',
                  sentTo: data.CodeDeliveryDetails.Destination,
                });
              })
              .catch((error) => {
                if (error.message && typeof error.message === 'string') {
                  ToastError(error.message as string);
                }
              });
          }
        }
```

I am receiving response as code was sent. In `.then` I have data that includes all data as when confirmation code was successfully sent. But I am not receiving email with confirmation code. Email address is valid, I am able to receive code when user is signing up and confirming sign up. But not when user leaves confirmation and tries again.

### Expected behavior

Email should be delivered if response indicates success.

### Reproduction steps

1. Sign up
2. Leave confirmation
3. reopen app and try to sign in
4. Code is sent but not received

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```typescript
          case 'signIn_failure': {
          if (event.payload.data.code === 'UserNotConfirmedException') {
            Auth.resendSignUp(values.email)
              .then((data) => {
                return navigation.navigate(Routes.confirmSignUpScreen, {
                  username: values.email,
                  isSms: data.CodeDeliveryDetails.AttributeName !== 'email',
                  sentTo: data.CodeDeliveryDetails.Destination,
                });
              })
              .catch((error) => {
                if (error.message && typeof error.message === 'string') {
                  ToastError(error.message as string);
                }
              });
          }
        }
```

</details>

**Comment by therealkh** [comment]
Found an issue in my code. Closing issue.

**Comment by cwomack** [comment]
@therealkh, glad you were able to unblock yourself! Let us know if there was anything when following the documentation that could be improved on or led to confusion

**Comment by mmtvarela** [comment]
@therealkh I'm trying to make a similar implementation on a react app (using Gen 1 v6), I can't seem to find the right implementation documentation. Could you point me out to it?
