### ISSUE TITLE
amplify-js and ionic 3 Cannot find name 'Buffer'.

### ISSUE THREAD

**Issue by arsewizz** [aws-amplify/amplify-js#1317]
hello, I tried to integrate the module into an ionic application, all this by initializing aws but I have an error
**Cannot find name 'Buffer'.**

**Comment by manueliglesias** [comment]
Hi @arsewizz 

I found this similar issue aws-samples/aws-mobile-ionic-sample#2

Does that work for you?
>Thanks. Just saw this now, after I resolved it this morning. I only needed to add:
```
"typeRoots": [
"node_modules/@types"
]
```

**Comment by arsewizz** [comment]
thanks, it woks.

**Comment by salvadoroarias** [comment]
Gracias
