### ISSUE TITLE
React Native withAuthenticator HOC breaks test.

### ISSUE THREAD

**Issue by Philosec** [aws-amplify/amplify-js#1320]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
Running the default App test created from CRNA fails when you add the react native withAuthenticator HOC.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.**
Create a react native app with CRNA. Run awsmobile-cli init to spin up backend project and also import amplify. Modify App.js to the following and the test fails.
```javascript
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import Amplify from "aws-amplify";
import config from './src/aws-exports'
import { withAuthenticator } from "aws-amplify-react-native";

Amplify.configure(config)

class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>Changes you make will automatically reload.</Text>
        <Text>Shake your phone to open the developer menu.</Text>
      </View>
    );
  }
}

export default withAuthenticator(App)
```
The default test created by CRNA. I did not modify this.
```javascript
import React from 'react';
import App from './App';

import renderer from 'react-test-renderer';

it('renders without crashing', () => {
  const rendered = renderer.create(<App />).toJSON();
  expect(rendered).toBeTruthy();
});

```
The error
```bash
Test suite failed to run

    TypeError: window.addEventListener is not a function

      at Object.<anonymous> (node_modules/@aws-amplify/core/lib/ClientDevice/browser.js:91:12)
      at Object.<anonymous> (node_modules/@aws-amplify/core/lib/ClientDevice/index.js:15:15)
      at Object.<anonymous> (node_modules/@aws-amplify/core/lib/index.js:23:22)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.99s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

**What is the expected behavior?**
I believe the test should still pass.

**Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?**
```json
"dependencies": {
    "aws-amplify": "^1.0.2",
    "aws-amplify-react-native": "^1.0.2",
    "expo": "^28.0.0",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz"
  },
  "devDependencies": {
    "jest-expo": "~27.0.0",
    "react-native-scripts": "1.14.0",
    "react-test-renderer": "16.3.1"
  }
```

**You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.**
Issue is during tests.

**Comment by powerful23** [comment]
Closing the issue. This should have been fixed in the latest version. Feel free to reopen if you still have this issue.
