### ISSUE TITLE
Auth: No event emitted to Hub when error thrown in pre-authentication trigger lambda for signInWithRedirect

### ISSUE THREAD

**Issue by deeheber** [aws-amplify/amplify-js#13219]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Version

v5

### Amplify Categories

auth

### Backend

CDK

### Environment information

<details>

```
# Put output below this line

  System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 1.47 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: 8.7.0 - ~/.nvm/versions/node/v18.19.0/bin/pnpm
  Browsers:
    Chrome: 123.0.6312.107
    Edge: 121.0.2277.112
    Safari: 17.4.1
  npmPackages:
    @apollo/client: ^3.7.14 => 3.7.17 
    @apollo/client/cache:  undefined ()
    @apollo/client/core:  undefined ()
    @apollo/client/errors:  undefined ()
    @apollo/client/link/batch:  undefined ()
    @apollo/client/link/batch-http:  undefined ()
    @apollo/client/link/context:  undefined ()
    @apollo/client/link/core:  undefined ()
    @apollo/client/link/error:  undefined ()
    @apollo/client/link/http:  undefined ()
    @apollo/client/link/persisted-queries:  undefined ()
    @apollo/client/link/retry:  undefined ()
    @apollo/client/link/schema:  undefined ()
    @apollo/client/link/subscriptions:  undefined ()
    @apollo/client/link/utils:  undefined ()
    @apollo/client/link/ws:  undefined ()
    @apollo/client/react:  undefined ()
    @apollo/client/react/components:  undefined ()
    @apollo/client/react/context:  undefined ()
    @apollo/client/react/hoc:  undefined ()
    @apollo/client/react/hooks:  undefined ()
    @apollo/client/react/parser:  undefined ()
    @apollo/client/react/ssr:  undefined ()
    @apollo/client/testing:  undefined ()
    @apollo/client/testing/core:  undefined ()
    @apollo/client/utilities:  undefined ()
    @apollo/client/utilities/globals:  undefined ()
    @aws-amplify/ui-react: ^4.6.3 => 4.6.4 
    @aws-amplify/ui-react-internal:  undefined ()
    @chakra-ui/icons: 2.0.0 => 2.0.0 
    @chakra-ui/react: ^2.5.2 => 2.8.0 
    @emotion/react: 11.9.3 => 11.9.3 
    @emotion/styled: 11.9.3 => 11.9.3 
    @fullstory/browser: ^1.7.1 => 1.7.1 
    @graphql-codegen/cli: ^3.3.1 => 3.3.1 
    @graphql-codegen/client-preset: ^3.0.1 => 3.0.1 
    @graphql-codegen/introspection: 4.0.0 => 4.0.0 
    @graphql-codegen/typescript-react-apollo: ^3.3.7 => 3.3.7 
    @graphql-tools/mock: ^9.0.0 => 9.0.0 
    @reduxjs/toolkit: 1.8.2 => 1.8.2 
    @reduxjs/toolkit-query:  1.0.0 
    @reduxjs/toolkit-query-react:  1.0.0 
    @testing-library/jest-dom: 5.16.4 => 5.16.4 
    @testing-library/react: 13.2.0 => 13.2.0 
    @testing-library/user-event: 13.5.0 => 13.5.0 
    @types/jest: 27.5.1 => 27.5.1 
    @types/luxon: ^3.4.2 => 3.4.2 
    @types/node: 17.0.34 => 17.0.34 
    @types/react: 18.0.9 => 18.0.9 
    @types/react-datepicker: 4.4.2 => 4.4.2 
    @types/react-dom: 18.0.4 => 18.0.4 
    @types/react-text-mask: ^5.4.11 => 5.4.11 
    @types/uuid: ^9.0.1 => 9.0.2 
    @typescript-eslint/eslint-plugin: ^5.60.1 => 5.62.0 
    aws-amplify: ^5.2.2 => 5.3.5 
    chakra-react-select: ^4.7.3 => 4.7.3 
    chart.js: ^4.4.1 => 4.4.1 
    chart.js-auto:  undefined ()
    chart.js-helpers:  undefined ()
    chartjs-plugin-annotation: ^3.0.1 => 3.0.1 
    date-fns: 2.28.0 => 2.28.0 
    downshift: ^7.6.0 => 7.6.2 
    eslint: ^8.43.0 => 8.45.0 
    eslint-config-prettier: ^8.8.0 => 8.9.0 
    eslint-config-standard-with-typescript: ^35.0.0 => 35.0.0 
    eslint-plugin-import: ^2.27.5 => 2.27.5 
    eslint-plugin-n: ^15.7.0 => 15.7.0 
    eslint-plugin-prettier: ^4.2.1 => 4.2.1 
    eslint-plugin-promise: ^6.1.1 => 6.1.1 
    eslint-plugin-react: ^7.32.2 => 7.33.0 
    eslint-plugin-unused-imports: ^2.0.0 => 2.0.0 
    focus-visible: 5.2.0 => 5.2.0 
    framer-motion: 6.3.16 => 6.3.16 
    graphql: ^16.6.0 => 16.7.1 (15.8.0)
    graphql-request: 4.3.0 => 4.3.0 (6.1.0)
    launchdarkly-react-client-sdk: ^3.0.6 => 3.0.8 
    lodash: 4.17.21 => 4.17.21 
    luxon: ^3.4.4 => 3.4.4 
    msw: ^1.2.1 => 1.2.3 
    prettier: ^2.8.8 => 2.8.8 
    react: 18.1.0 => 18.1.0 (18.2.0)
    react-chartjs-2: ^5.2.0 => 5.2.0 
    react-datepicker: 4.8.0 => 4.8.0 
    react-dom: 18.1.0 => 18.1.0 
    react-hook-form: ^7.43.2 => 7.45.2 
    react-icons: 4.10.1 => 4.10.1 
    react-redux: 8.0.2 => 8.0.2 
    react-router-dom: 6.3.0 => 6.3.0 
    react-scripts: 5.0.1 => 5.0.1 
    react-text-mask: ^5.5.0 => 5.5.0 
    react-textarea-autosize: ^8.5.3 => 8.5.3 
    redux-persist: ^6.0.0 => 6.0.0 
    redux-persist/integration/react:  undefined ()
    standard-version: ^9.5.0 => 9.5.0 
    text-mask-addons: ^3.8.0 => 3.8.0 
    typescript: ^5.1.5 => 5.1.6 (5.0.2)
    uuid: ^9.0.0 => 9.0.0 (3.4.0, 8.3.2)
    web-vitals: 2.1.4 => 2.1.4 
    workbox-background-sync: 6.5.3 => 6.5.3 (6.6.0)
    workbox-broadcast-update: 6.5.3 => 6.5.3 (6.6.0)
    workbox-cacheable-response: 6.5.3 => 6.5.3 (6.6.0)
    workbox-core: 6.5.3 => 6.5.3 (6.6.0)
    workbox-expiration: 6.5.3 => 6.5.3 (6.6.0)
    workbox-google-analytics: 6.5.3 => 6.5.3 (6.6.0)
    workbox-navigation-preload: 6.5.3 => 6.5.3 (6.6.0)
    workbox-precaching: 6.5.3 => 6.5.3 (6.6.0)
    workbox-range-requests: 6.5.3 => 6.5.3 (6.6.0)
    workbox-routing: 6.5.3 => 6.5.3 (6.6.0)
    workbox-strategies: 6.5.3 => 6.5.3 (6.6.0)
    workbox-streams: 6.5.3 => 6.5.3 (6.6.0)
  npmGlobalPackages:
    corepack: 0.22.0
    npm: 10.2.3
    pnpm: 8.7.0

```

</details>

### Describe the bug

Errors are being thrown in a pre-authentication Lambda trigger and those errors are not being shown in the frontend. 

I've validated by looking at my CloudWatch logs that the pre-authentication trigger lambda is indeed being triggered when I attempt to login.

We're using Cognito with Active Directory and calling `await signInWithRedirect();` on our button submit handler.

Code snippet to listen to auth events on hub

```
Hub.listen('auth', (data) => {
    // TODO get rid of this console log
    console.log('auth event ', data);
    if (data.payload.event === 'signInWithRedirect_failure') {
      const err = data.payload.data.error?.message ?? 'login error fallback';
      setErrorMsg(err);
    }
  });
  ```
  
  This isn't getting triggered at all for errors thrown in a pre-authentication trigger lambda. I have purposefully thrown errors in a pre-token-generation lambda trigger and saw the event hit the Hub as expected.

### Expected behavior

I would expect to see a `signInWithRedirect_failure` hit that Hub as an event.

### Reproduction steps

1. Start our app
2. Click login on our sign in form
3. Redirected to the Cognito hosted UI where I enter my credentials
3. It redirects to my login form, with query string that contains the error that I threw the Cognito pre-authentication trigger Lambda which looks similar to 

```
http://localhost:3000/?error_description=Invalid+SAML+response+received%3A+PreAuthentication+failed+with+error+Test+error+on+purpose+from+Danielle.+&state=dVefufuw4Q5dYoneNXt3imSQb1Oe8flQ&error=server_error
```

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Mobile Browser

Latest version of Chrome

### Additional information and screenshots

I noticed https://github.com/aws-amplify/amplify-js/issues/5318 and verified that my User Pool does not have the setup of only `CUSTOM_AUTH_FLOW_ONLY`. On my User Pool userPassword is set to true.

**Comment by cwomack** [comment]
Hello, @deeheber 👋 and sorry to hear you're running into this.  Are you trying to ensure that when this error is thrown that it's captured on the client side to enable client side logic for a user to be informed? I'll look into how we're handling these lambda errors on the Amplify side.

**Comment by deeheber** [comment]
Hey @cwomack thanks for the reply and for looking into this.

>Hello, @deeheber 👋 and sorry to hear you're running into this. Are you trying to ensure that when this error is thrown that it's captured on the client side to enable client side logic for a user to be informed? I'll look into how we're handling these lambda errors on the Amplify side.

Correct. I'm hoping to be able to react to an auth event published to the Hub to show a toast informing the user with the error. 

I didn't see any errors hit this channel for preauthentication...we do have a pretokengeneration lambda too and those errors hit the Hub just fine.

Open to other suggestions or feedback if we're doing something wrong on our end though. Thanks again.

**Comment by cwomack** [comment]
@deeheber, thanks for the clarity.  The `signInWithRedirect()` API is exclusive to v6, so if you're listening for that in a v5 Amplify app then it won't be emitted via the Auth channel in Hub.  You can review [this list](https://docs.amplify.aws/react/prev/build-a-backend/auth/auth-events/#listen-to-and-log-auth-events) of v5 Hub events for the Auth channel that can be used.  It looks like you could be listening for the `cognitoHostedUI_failure` event in v5 instead.  

Let me know if this clears things up!

**Comment by deeheber** [comment]
Thanks for looking into this and I appreciate the help.

I'll close this issue as resolve for you.

**Comment by ChrisBoik** [comment]
Hi there,

Forgive me if I am out of line, but is this not still relevant to v6?
The Hub does not receive error events (or any event emitted) for this exact scenario (a pre-authentication function failure/error during federated sign-in or other signInWithRedirect
