### ISSUE TITLE
Authenticator support for AWS IAM Identity Center using a third-party identity provider

### ISSUE THREAD

**Issue by jmbuss** [aws-amplify/amplify-js#13210]
### Is this related to a new or existing framework?

React

### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

[IoT Application](https://github.com/awslabs/iot-application) is currently using Amplify V5. It allows users to use IAM Identity Center as their authentication source - [docs](https://github.com/awslabs/iot-application/blob/main/deploymentguide/README.md). Users can do so following [these integration instructions](https://repost.aws/knowledge-center/cognito-user-pool-iam-integration). When upgrading Amplify to V6, this flow no longer works. We are looking for a path forward to upgrade Amplify in IoT Application.

### Describe the solution you'd like

Documentation on how to support this flow, including information about how to configure Amplify, and any specific configuration required on the authentication resource (or links to relevant documentation). Also, any upgrades to Amplify Authenticator that are required to do so.

### Describe alternatives you've considered

Alternatively we would have to implement the authentication ourselves in order to support this flow.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cwomack** [comment]
Hello, @jmbuss and sorry to hear that you're running into this when upgrading from v5 to v6 of Amplify.  We might need a few more details about your app (including the frontend code/API's causing the issue), but I'll look through the links provided to see if I can spot something as well.  In the mean time, can you do the following just to ensure it's not an issue tied to duplicate dependencies?  

1. Delete your `node_modules` folder
2. Delete your`package-lock.json` file
3. Reinstall dependencies with `npm i`

After taking these steps, if you're still experiencing the error then could you please share the dependencies in your `package.json` along with the errors that are being thrown? Thanks!

**Comment by cwomack** [comment]
@jmbuss, just wanted to also check and see if you updated the Auth API's after moving to v6 (instructions [here](https://docs.amplify.aws/react/build-a-backend/auth/auth-migration-guide/)).  We moved from class based API's to functional API's, so both the imports and the way you'll call the API's will change in v6.

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
