### ISSUE TITLE
[v6] Attempt limit exceeded please try after some time when "reset pasword", how long extract time ?

### ISSUE THREAD

**Issue by natuan62** [aws-amplify/amplify-js#13225]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication

### Amplify Version

v6

### Backend

None

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I search but can't find extract how long (15min - 30min or 1 hours, etc).
I need to know how long to alert for users to know they can try forgot password again.

> https://github.com/amazon-archives/amazon-cognito-identity-js/issues/548

In this issue, he mention that `We do have those protection mechanisms mentioned, however we do not share externally the exact limits involved.`

and 
> https://docs.aws.amazon.com/cognito/latest/developerguide/how-to-recover-a-user-account.html#forgot-password

```
In a given hour, we allow between 5 and 20 attempts for a user to request or enter a password reset code as part of forgot-password and confirm-forgot-password actions. The exact value depends on the risk parameters associated with the requests. Please note that this behavior is subject to change.
```

### Expected behavior

Extract time to know how long

### Reproduction steps

1. resetPassword
2. cognito send code to email
3. confirmSignUp with wrong confirmationCode serveral times
4. Amplify catch error `Attempt limit exceeded please try after some time`

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by jimblanc** [comment]
@natuan62 Thank you for your report! As mentioned in the Cognito docs, the exact throttling limit for password reset requests is not exposed and Amplify has no control over this limit. For a safe message that you could display to your customers, I would recommend 1 hour.

**Comment by cwomack** [comment]
@natuan62 to add a little more context, it may be that the [Cogntio lockout behavior](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-authentication-flow.html#:~:text=Amazon%20Cognito%20lockout%20behavior%20for%20failed%20sign%2Din%20attempts) is kicking in for repeated failed sign-in attempts.  The lockout duration will **_double_** up to a maximum of approximately 15 minutes after continued failures.

Also worth noting that users will have [3 minutes](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-authentication-flow.html#:~:text=By%20default%2C%20your%20users%20have%20three%20minutes%20to%20complete%20each%20challenge%20before%20the%20session%20string%20expires.) to complete the challenge each time before it expires as well.

**Comment by himanshugogroup** [comment]
As checked if I only do failed retry after 5attempts it reset after 15minute else it keep on increasing exponentially.
