### ISSUE TITLE
Uploading file to storage issue

### ISSUE THREAD

**Issue by RaduIm** [aws-amplify/amplify-js#13222]
### Environment information

```plain text
System:
  OS: macOS 14.4
  CPU: (8) arm64 Apple M1
  Memory: 95.27 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 21.6.1 - /opt/homebrew/bin/node
  Yarn: 1.22.21 - /opt/homebrew/bin/yarn
  npm: 10.2.4 - /opt/homebrew/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 0.13.0-beta.15
  @aws-amplify/backend-cli: 0.11.1
  aws-amplify: 6.0.27
  aws-cdk: 2.135.0
  aws-cdk-lib: 2.135.0
  typescript: 5.4.4
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!                                                                                                                      !!
!!  This software has not been tested with node v21.6.1.                                                                !!
!!  Should you encounter odd runtime issues, please try using one of the supported release before filing a bug report.  !!
!!                                                                                                                      !!
!!  This software is currently running on node v21.6.1.                                                                 !!
!!  As of the current release of this software, supported node releases are:                                            !!
!!  - ^20.0.0 (Planned end-of-life: 2026-04-30)                                                                         !!
!!  - ^18.0.0 (Planned end-of-life: 2025-04-30)                                                                         !!
!!                                                                                                                      !!
!!  This warning can be silenced by setting the JSII_SILENCE_WARNING_UNTESTED_NODE_VERSION environment variable.        !!
!!                                                                                                                      !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

I discussed this topic in the Amplify Office Hours on Discord yesterday @cwomack 

I am trying to upload a file to storage and getting the following error:
![Pasted Graphic 4](https://github.com/aws-amplify/amplify-backend/assets/33747167/792193e2-403f-4c22-be30-b6436e8c560f)

This is how I define the storage:
![image](https://github.com/aws-amplify/amplify-backend/assets/33747167/0f29042a-7f13-4135-a434-768f877604e2)

This is my backend:
![image](https://github.com/aws-amplify/amplify-backend/assets/33747167/886025d0-202e-447c-9ce1-682e362a83ee)

This is my auth:
![image](https://github.com/aws-amplify/amplify-backend/assets/33747167/672d83ae-6bb4-4918-aed6-b355618494d0)

This is my client component:
![image](https://github.com/aws-amplify/amplify-backend/assets/33747167/8bbc8f10-5551-4eb1-bc4a-ee05e759b68c)

A simple example of uploading a file to storage would be greatly appreciated!

Thanks
Radu

**Comment by ashika112** [comment]
Hi, thanks for opening up the issue. this is expected, we are working on changes to library to fully support the backend flexbility. 

If you are interested in trying out the new changes, we have a tagged release at `gen2-storage` still under works / experimental along with the backend.

Steps:
1. npm install `aws-amplify@gen2-storage`
2. update code to be

```const uploadDataAsync = async () => {
const result = await uploadData({
path: "uploads/ExampleKey",
data: data
}).result;
console.log("result:", result);
}
```

note: gen2 backend storage does not have access levels anymore. So you need to provide full path in `path` parameter.

**Comment by ashika112** [comment]
If you want to make this work with the existing amplify js, then in your backend.ts you need to update the paths like so
```
access: (allow) => ({
"public/*": [allow.guest.to(["read", "write"])], 
})
```

**Comment by RaduIm** [comment]
Thanks, @ashika112, this helps a lot!

**Comment by cwomack** [comment]
Thanks for confirming and closing the issue out, @RaduIm.  Let us know if you have further questions!
