### ISSUE TITLE
[v6] How to resetPassword when <Email verified = No, Confirmation status = Confirmed> case 

### ISSUE THREAD

**Issue by natuan62** [aws-amplify/amplify-js#13220]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

Authentication

### Amplify Version

v6

### Amplify Categories

auth

### Backend

None

### Environment information

<details>

```
# Put output below this line


  System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1
    Memory: 265.92 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 7.20.0 - ~/.config/yarn/global/node_modules/.bin/npm
    pnpm: 8.15.5 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 123.0.6312.107
    Safari: 17.4.1
  npmPackages:
    @graphql-codegen/plugin-helpers: 5.0.0 => 5.0.0
    @intlify/unplugin-vue-i18n: ^0.11.0 => 0.11.0
    @mdi/js: ^7.4.47 => 7.4.47
    @nabla/vite-plugin-eslint: ^1.6.0 => 1.6.0
    @peculiar/webcrypto: ^1.4.6 => 1.4.5
    @sentry/browser: ^7.109.0 => 7.108.0
    @sentry/tracing: ^7.109.0 => 7.108.0
    @sentry/types: ^7.109.0 => 7.108.0
    @sentry/vue: ^7.109.0 => 7.108.0
    @types/chai: ^4.3.14 => 4.3.14
    @types/crypto-js: ^4.2.2 => 4.2.2
    @types/fontfaceobserver: ^2.1.3 => 2.1.3
    @types/mocha: ^10.0.6 => 10.0.6
    @types/node: ^20.12.4 => 20.11.30
    @types/opentype.js: ^1.3.8 => 1.3.8
    @types/pako: ^2.0.3 => 2.0.3
    @types/tinycolor2: ^1.4.6 => 1.4.6
    @types/zen-observable: ^0.8.7 => 0.8.7
    @typescript-eslint/eslint-plugin: ^5.62.0 => 5.62.0
    @typescript-eslint/parser: ^5.62.0 => 5.62.0
    @vitejs/plugin-vue: ^4.6.2 => 4.6.2
    @vue/test-utils: ^2.4.5 => 2.4.5
    amazon-cognito-identity-js: ^6.3.12 => 6.3.12
    ant-design-vue: ^3.2.20 => 3.2.20
    aws-amplify: ^6.0.27 => 6.0.21
    axios: ^1.6.8 => 1.6.8
    babel-eslint: ^10.1.0 => 10.1.0
    babel-loader: ^8.3.0 => 8.3.0
    babel-plugin-import: ^1.13.8 => 1.13.8
    babel-plugin-root-import: ^6.6.0 => 6.6.0
    babel-plugin-transform-decorators: ^6.24.1 => 6.24.1
    babel-plugin-transform-remove-console: ^6.9.4 => 6.9.4
    buffer: ^6.0.3 => 6.0.3
    canvas-svgjs:  1.0.0
    chai: ^4.4.1 => 4.4.1
    core-js: ^3.36.1 => 3.36.1
    corjl-fabric: gitlab:corjl2/fabric-js#dev => 1.0.1
    crypto-js: ^4.2.0 => 4.2.0
    cypress: ^9.7.0 => 9.7.0
    cypress-graphql-mock: 0.5.0-alpha.4 => 0.5.0-alpha.4
    dayjs: ^1.11.10 => 1.11.10
    draggabilly: ^3.0.0 => 3.0.0
    easygraphql-tester: ^6.0.1 => 6.0.1
    eslint: ^8.57.0 => 8.57.0
    eslint-config-proste: ^7.7.0 => 7.7.0
    eslint-plugin-cypress: ^2.15.1 => 2.15.1
    eslint-plugin-import: ^2.29.1 => 2.29.1
    eslint-plugin-import-newlines: ^1.4.0 => 1.4.0
    eslint-plugin-vue: ^9.24.0 => 9.23.0
    fabric:  5.3.0
    fast-json-patch: ^3.1.1 => 3.1.1
    file-type: ^18.7.0 => 18.7.0
    fontfaceobserver: ^2.3.0 => 2.3.0
    graphql: ^16.8.1 => 16.8.1
    husky: ^8.0.3 => 8.0.3
    idb: ^7.1.1 => 7.1.1
    is-svg: ^5.0.0 => 5.0.0
    jest: ^29.7.0 => 29.7.0
    jsdom: ^22.1.0 => 22.1.0
    less: ^4.2.0 => 4.2.0
    less-loader: ^11.1.4 => 11.1.4
    lint-staged: ^13.3.0 => 13.3.0
    mitt: ^3.0.1 => 3.0.1
    mocha: ^10.4.0 => 10.3.0
    node-sass: ^9.0.0 => 9.0.0
    opentype.js: gitlab:corjl2/opentype.js#dev => undefined ()
    pako: ^2.1.0 => 2.1.0
    paper: ^0.12.17 => 0.12.17
    paper-jsdom: file:src/vue-plugins/paper-jsdom => 0.12.17
    path-data-polyfill: ^1.0.4 => 1.0.4
    pinia: ^2.1.7 => 2.1.7
    pusher-js: ^8.3.0 => 8.3.0
    sass: ^1.74.1 => 1.72.0
    sass-loader: ^13.3.3 => 13.3.3
    source-map-support: ^0.5.21 => 0.5.21
    tinycolor2: ^1.6.0 => 1.6.0
    typescript: 5.1.3 => 5.1.3
    typings: ^2.1.1 => 2.1.1
    vite: ^4.5.3 => 4.5.2
    vite-plugin-node-polyfills: ^0.9.0 => 0.9.0
    vite-svg-loader: ^4.0.0 => 4.0.0
    vue: ^3.4.21 => 3.4.21
    vue-i18n: 9.2.2 => 9.2.2
    vue-router: ^4.3.0 => 4.3.0
    vue-router-loader-yaml: gitlab:corjl2/vue-router-loader-yaml => 0.0.6
    vue-toastification: 2.0.0-rc.5 => 2.0.0-rc.5
    vue-tsc: ^1.8.27 => 1.8.27
    vuedraggable: ^4.1.0 => 4.1.0
  npmGlobalPackages:
    @angular/cli: 10.1.2
    @aws-amplify/cli: 12.10.1
    corepack: 0.23.0
    npm: 10.2.4

```

</details>

### Describe the bug

Cannot resetPassword when my account have `Email verified = No, Confirmation status = Confirmed`

### Expected behavior

Can verify email and reset password

### Reproduction steps

I have an cognito account with `Email verified = No, Confirmation status = Confirmed`

1 . When i call `resetPassword`

```
import { resetPassword, confirmResetPassword, resendSignUpCode, confirmSignUp } from 'aws-amplify/auth';

resetPassword({ username: emailForm.value.email });
```

it throw `error InvalidParameterException: Cannot reset password for the user as there is no registered/verified email or phone_number`

2 . Next, If I call `resendSignUpCode`
```
resendSignUpCode({ username: emailForm.value.email })
```
it throw `error InvalidParameterException: User is already confirmed.`

How I can use amplify to verify email instead open cognito and `Mark email address as verified` ?
 

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello, @natuan62 👋.  Can you possibly share the frontend code for the Auth flow that you have set up?  The errors you're describing sound like expected behavior if a user is in this state, but how did you originally **_confirm_** the user that's experiencing this?

**Comment by natuan62** [comment]
Hi @cwomack Thanks for reply. This case occurr when on testing preSignUp lamda trigger, I did set `autoConfirmUser`

```
export const handler = async (event: CognitoUserPoolTriggerEvent, context: Context, callback: Callback) => {
   event.response.autoConfirmUser = true;
   callback(null, event);
}
``` 
but not verify email, so when use amplify to signUp an account. This account created on cognito with 2 fields 
`Email verified = No, Confirmation status = Confirmed` like I mention above. So it not the users that's experience.

And when research amplify api, seem no way to reset password for this user.
Could you confirm this for me must use cognito to verified email before using amplify again to reset password normally ?

**Comment by israx** [comment]
hello @natuan62 . Cognito will auto verify the email when `confirmSignUp` has being called successfully. If you are using the `preSignUp` lambda, you would need to verify the email as well. e.g  `event.response.autoVerifyEmail = true;` . 

Or is there a use case where you want to force your end-users to reset their passwords ? If that is the case I believe you might be able to do it by having the following lambda

```
export const handler = async (event: CognitoUserPoolTriggerEvent, context: Context, callback: Callback) => {
   event.response.autoConfirmUser = false;
   event.response.autoVerifyEmail = true;
   callback(null, event);
}
```

Let us know if that works!
