### ISSUE TITLE
In `fetchAuthSession()`, `token` and `subs` are undefined, whereas in Amplify version 5, they are available.

### ISSUE THREAD

**Issue by TitusEfferian** [aws-amplify/amplify-js#13236]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Version

v6

### Amplify Categories

auth

### Backend

Amplify CLI

### Environment information

<details>

```
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 509.73 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.19.1/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
  Browsers:
    Chrome: 123.0.6312.107
    Chrome Canary: 125.0.6409.0
    Edge: 123.0.2420.81
    Safari: 17.4.1
  npmPackages:
    @auth0/auth0-react: ^2.2.4 => 2.2.4 
    @aws-sdk/client-cognito-identity: ^3.540.0 => 3.540.0 
    @types/react: ^18.2.66 => 18.2.74 
    @types/react-dom: ^18.2.22 => 18.2.24 
    @typescript-eslint/eslint-plugin: ^7.2.0 => 7.5.0 
    @typescript-eslint/parser: ^7.2.0 => 7.5.0 
    @vitejs/plugin-react: ^4.2.1 => 4.2.1 
    aws-amplify: ^6.0.27 => 6.0.27 
    aws-amplify/adapter-core:  undefined ()
    aws-amplify/analytics:  undefined ()
    aws-amplify/analytics/kinesis:  undefined ()
    aws-amplify/analytics/kinesis-firehose:  undefined ()
    aws-amplify/analytics/personalize:  undefined ()
    aws-amplify/analytics/pinpoint:  undefined ()
    aws-amplify/api:  undefined ()
    aws-amplify/api/server:  undefined ()
    aws-amplify/auth:  undefined ()
    aws-amplify/auth/cognito:  undefined ()
    aws-amplify/auth/cognito/server:  undefined ()
    aws-amplify/auth/enable-oauth-listener:  undefined ()
    aws-amplify/auth/server:  undefined ()
    aws-amplify/data:  undefined ()
    aws-amplify/data/server:  undefined ()
    aws-amplify/datastore:  undefined ()
    aws-amplify/in-app-messaging:  undefined ()
    aws-amplify/in-app-messaging/pinpoint:  undefined ()
    aws-amplify/push-notifications:  undefined ()
    aws-amplify/push-notifications/pinpoint:  undefined ()
    aws-amplify/storage:  undefined ()
    aws-amplify/storage/s3:  undefined ()
    aws-amplify/storage/s3/server:  undefined ()
    aws-amplify/storage/server:  undefined ()
    aws-amplify/utils:  undefined ()
    eslint: ^8.57.0 => 8.57.0 
    eslint-plugin-react-hooks: ^4.6.0 => 4.6.0 
    eslint-plugin-react-refresh: ^0.4.6 => 0.4.6 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.2.2 => 5.4.3 
    vite: ^5.2.0 => 5.2.8 
  npmGlobalPackages:
    @aws-amplify/cli: 12.10.1
    corepack: 0.22.0
    npm: 10.2.4
    vercel: 33.6.1
    yarn: 1.22.22

```

</details>

### Describe the bug

I want to try integrating federation with Auth0 based on the [documentation](https://docs.amplify.aws/react/build-a-backend/auth/advanced-workflows/#federate-with-auth0). The authentication with Auth0 is successful, as I've already passed the idToken to the Amplify credentialProvider. However, when using `fetchAuthSession()`, two values from the object are undefined: `tokens` and `userSub`.

App.tsx
```typescript
import { useAuth0 } from "@auth0/auth0-react";
import "./App.css";
import { Amplify } from "aws-amplify";
import {
  fetchAuthSession,
  CredentialsAndIdentityIdProvider,
  CredentialsAndIdentityId,
  GetCredentialsOptions,
} from "aws-amplify/auth";
import awsconfig from "./amplifyconfiguration.json";

// Note: This example requires installing `@aws-sdk/client-cognito-identity` to obtain Cognito credentials
// npm i @aws-sdk/client-cognito-identity
import { CognitoIdentity } from "@aws-sdk/client-cognito-identity";
import { DataStore, AuthModeStrategyType } from "aws-amplify/datastore";

import { AnotherTodo } from "./models";

// You can make use of the sdk to get identityId and credentials
const cognitoidentity = new CognitoIdentity({
  region: awsconfig.aws_cognito_region,
});

// Note: The custom provider class must implement CredentialsAndIdentityIdProvider
class CustomCredentialsProvider implements CredentialsAndIdentityIdProvider {
  // Example class member that holds the login information
  federatedLogin?: {
    domain: string;
    token: string;
  };

  // Custom method to load the federated login information
  loadFederatedLogin(login?: typeof this.federatedLogin) {
    // You may also persist this by caching if needed
    this.federatedLogin = login;
  }

  async getCredentialsAndIdentityId(
    getCredentialsOptions: GetCredentialsOptions,
  ): Promise<CredentialsAndIdentityId | undefined> {
    try {
      // You can add in some validation to check if the token is available before proceeding
      // You can also refresh the token if it's expired before proceeding

      const getIdResult = await cognitoidentity.getId({
        // Get the identityPoolId from config
        IdentityPoolId: "xxx",
        Logins: { [this.federatedLogin.domain]: this.federatedLogin.token },
      });

      const cognitoCredentialsResult =
        await cognitoidentity.getCredentialsForIdentity({
          IdentityId: getIdResult.IdentityId,
          Logins: { [this.federatedLogin.domain]: this.federatedLogin.token },
        });

      const credentials: CredentialsAndIdentityId = {
        credentials: {
          accessKeyId: cognitoCredentialsResult.Credentials?.AccessKeyId,
          secretAccessKey: cognitoCredentialsResult.Credentials?.SecretKey,
          sessionToken: cognitoCredentialsResult.Credentials?.SessionToken,
          expiration: cognitoCredentialsResult.Credentials?.Expiration,
        },
        identityId: getIdResult.IdentityId,
      };
      return credentials;
    } catch (e) {
      console.log("Error getting credentials: ", e);
    }
  }
  // Implement this to clear any cached credentials and identityId. This can be called when signing out of the federation service.
  clearCredentialsAndIdentityId(): void {}
}

// Create an instance of your custom provider
const customCredentialsProvider = new CustomCredentialsProvider();

Amplify.configure(
  {
    ...awsconfig,
  },
  {
    Auth: {
      // Supply the custom credentials provider to Amplify
      credentialsProvider: customCredentialsProvider,
    },
  },
);

function App() {
  const { loginWithRedirect, getIdTokenClaims, logout, isLoading } = useAuth0();

  if (isLoading) {
    return <div>Loading...</div>;
  }

  return (
    <>
      <button
        onClick={() => {
         // login with redirect to auth0
          loginWithRedirect();
        }}
      >
        login redirect
      </button>
      <button
        onClick={async () => {
          try {
            
            const token = await getIdTokenClaims();
            // pass the token to customCredentialProvider
            await customCredentialsProvider.loadFederatedLogin({
              domain: "testing-amplify.jp.auth0.com",
              token: token?.__raw || "",
            });
            const fetchSessionResult = await fetchAuthSession(); // will return the credentials
            console.log("fetchSessionResult: ", fetchSessionResult);
          } catch (err) {
            console.log(err);
          }
        }}
      >
        login
      </button>
    </>
  );
}

export default App;
```

when we try to get the data from `fetchAuthSession();` it returns like this:
```json
{
  "credentials": {
    "accessKeyId": "xxx",
    "secretAccessKey": "xxx",
    "sessionToken": "xxx"
  },
  "identityId": "xxx",
  "tokens": undefined,
  "userSub": undefined
}
```

### Expected behavior

The expected behavior is that `tokens` and `userSubs` should have values, because using the similar approach in version 5 returns the values.

### Reproduction steps

1. init react project using vite
2. configure the amplify with version 6 documentation
3. change the app.tsx similar to the snippet code from previous description
4. loginWithRedirect to auth0
5. try to get the information using `fetchAuthSession()`

### Code Snippet

```javascript
// Put your code below this line.

```

**Comment by cwomack** [comment]
Hello, @TitusEfferian 👋.  It looks like you are missing the tokenProvider for your custom auth flow.  You'll need to import the `TokenProvider` from  `aws-amplify/auth` and use that within your `Amplify.configure()` call like seen [here](https://docs.amplify.aws/react/build-a-backend/auth/advanced-workflows/#custom-token-providers:~:text=22-,Amplify.configure(awsconfig%2C%20%7B,%7D)%3B,-API%20reference).  Doing so should provide you with both the `tokens` and `userSub`.  

Let me know if that doesn't resolve the issue for you!

**Comment by TitusEfferian** [comment]
Hi @cwomack, thanks for the response. Yes, it's now working as expected. However, as a user who has transitioned from Amplify version 5 to version 6, I feel that the documentation could be improved. In the previous version (v5), performing this action would automatically return `tokens`:

```typescript
// get data from auth0
const sync = await getIdTokenClaims();

const cred = await Auth.federatedSignIn(
  "my auth0 domain",
  {
    token: sync?.__raw || "",
    expires_at: (sync?.exp || 0) * 1000,
  },
  {
    name: sync?.name || "",
    email: sync?.email || "",
    picture: sync?.picture || "",
    sub: sync?.sub || "",
   ...add another additional data here
  },
);
```

```typescript
const user = await Auth.currentAuthenticatedUser();
// output
{
  "id": "my id",
  "token": "my token"
}
```

In version 6, I need to undertake additional processes to achieve the same expected result, as you mentioned:
> You'll need to import the TokenProvider from aws-amplify/auth and use that within your Amplify.configure() call like seen [here](https://docs.amplify.aws/react/build-a-backend/auth/advanced-workflows/#custom-token-providers:~:text=22-,Amplify.configure(awsconfig%2C%20%7B,%7D)%3B,-API%20reference). Doing so should provide you with both the tokens and userSub.

This is just my proposal for improvement: perhaps this section could be moved after the Identity Pool Federation section, as they are still related. I didn't realize this additional step was necessary.

![image](https://github.com/aws-amplify/amplify-js/assets/27436728/684852e2-9c93-4750-8b89-aafd5e2d1035)

**Comment by jimblanc** [comment]
@TitusEfferian Glad to hear you got it working! Thank you for your feedback on the documentation structure, we will take that into consideration.

**Comment by jonoh0224** [comment]
Hi, @TitusEfferian 
I'm going through the same issue.
Could you please share how you implemented your myTokenProvider?
I'm migrating the google signin feature from v5 to v6, and I'm not sure where to get the token strings to decode

**Comment by david-sunsyte** [comment]
Hi @TitusEfferian - Same as above. Can you please share your implementation of the customTokenProvider?

**Comment by TitusEfferian** [comment]
@jonoh0224 @david-sunsyte sorry for late reply, as they mentioned here
> Hello, @TitusEfferian 👋. It looks like you are missing the tokenProvider for your custom auth flow. You'll need to import the TokenProvider from aws-amplify/auth and use that within your Amplify.configure() call like seen [here](https://docs.amplify.aws/react/build-a-backend/auth/advanced-workflows/#custom-token-providers:~:text=22-,Amplify.configure(awsconfig%2C%20%7B,%7D)%3B,-API%20reference). Doing so should provide you with both the tokens and userSub.


We need to import the token provider and use it within `Amplify.configure`.

Here is a code snippet showing what the implementation looks like. Depending on your framework, you may need to adjust the order and lifecycle of this approach:

```typescript
try {
  const token = await getIdTokenClaims();

  const myTokenProvider: TokenProvider = {
    async getTokens() {
      return {
        accessToken: decodeJWT(token?.__raw),
        idToken: token?.__raw,
      };
    },
  };
  
  Amplify.configure(
    {
      ...awsconfig,
    },
    {
      Auth: {
        credentialsProvider: customCredentialsProvider,
        tokenProvider: myTokenProvider,
      },
    }
  );
  
  await customCredentialsProvider.loadFederatedLogin({
    domain: "your-domain",
    token: token?.__raw || "",
  });
  
  const fetchSessionResult = await fetchAuthSession(); // will return the credentials
  console.log("fetchSessionResult: ", fetchSessionResult);
} catch (err) {
  console.log(err);
}
```

**Comment by david-sunsyte** [comment]
Thank you for this! So when using federation/identity pools and the credentials returned as such, how would one go about securing a backend API? I have a .NET backend that I currently have set to utilize JwtBearer auth, but this only works when access tokens (id_tokens for Cognito) are in play

**Comment by david-sunsyte** [comment]
And the 'credentials' are definitely returned, but the below still shows, undefined userSub and tokens
```
{
  "credentials": {
    "accessKeyId": "xxx",
    "secretAccessKey": "xxx",
    "sessionToken": "xxx"
  },
  "identityId": "xxx",
  "tokens": undefined,
  "userSub": undefined
}
```
