### ISSUE TITLE
Amplify/auth - Get current cognito user device

### ISSUE THREAD

**Issue by lucashfreitas** [aws-amplify/amplify-js#13244]
### Is this related to a new or existing framework?

React Native

### Is this related to a new or existing API?

Authentication

### Is this related to another service?

Auth & Cognito

### Describe the feature you'd like to request

We would like to use cognito as a single source of truuth and use the id that it provides to identify user devices, therefore there is no way to get what is the user current device id in react native.

We would like to use it to avoid using another lib/solution to identify devices to an user.  Not sure if it's possible, but if amplify can expose a method to get the current device, we would use the cognito ID for the mobile phone and it would be easier to integrate with events that happen with that device via LambdaTriggers, for example. 

There is a similar request on amplify/flutter repo:  https://github.com/aws-amplify/amplify-flutter/issues/1472 

### Describe the solution you'd like

I'd like a method in `aws-amplify/auth` that exposes a `getDevice` function which returns the current device info and it's id, so I can associate it with the cognito device id, so we can have a single source of truth for user/device storage.

### Describe alternatives you've considered

I have investigated other options to identify a device id but would love to do it using amplify without needing  to add another library or tool to our stack. 

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by lucashfreitas** [comment]
Just realised that the `deviceId` is exposed as device_key through the accessToken

```typescript
const authSession = await fetchAuthSession();
const deviceKey = authSession.tokens?.accessToken.payload.device_key || "";
```

**Comment by cwomack** [comment]
Hey there, @lucashfreitas 👋.  Sounds like you found the way to get the `deviceId` in v6, but want to make sure you're fully unblocked at this point before closing out the issue.

Additionally, if you're looking to have the remembered device name in v6 then that's being tracked in #12854 as well.

**Comment by lucashfreitas** [comment]
Awesome, thanks @cwomack :) I am closing this issue since I've found a way to get the token using the access token.
