### ISSUE TITLE
[Amplify Admin Actions] CORS error and unable to pass queryStringParameters

### ISSUE THREAD

**Issue by muvashi** [aws-amplify/amplify-js#13259]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

REST API

### Amplify Version

v6

### Amplify Categories

api

### Backend

None

### Environment information

NA

### Describe the bug

1. On trying to pass Authorization header as mentioned in below example, the following error occurs.

https://docs.amplify.aws/javascript/build-a-backend/auth/admin-actions/#example

Access to fetch at 'https://aaaa.execute-api.us-east-1.amazonaws.com/dev/listGroups' from origin 'http://localhost:3001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

2. On trying to pass query string parameters using the above example, no error occurs but the parameters are not passed in request URL and they are not visible in the Lambda function event.

### Expected behavior

1. No CORS error.
2. Query string parameters should be passed in the request.

### Reproduction steps

Follow the above mentioned docs

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by muvashi** [comment]
Submitted PR to fix both these behaviour :- [PR7234](https://github.com/aws-amplify/docs/pull/7234)

**Comment by ShaimaaHamdan** [comment]
I am facing same issue after upgrading to Amplify V6
![image](https://github.com/aws-amplify/amplify-js/assets/8478773/417c4f1b-78db-4c88-8c27-e4aa42bf5faa)

**Comment by muvashi** [comment]
@ShaimaaHamdan Please check the PR https://github.com/aws-amplify/docs/pull/7234

**Comment by cwomack** [comment]
@muvashi, thank you for the submission of the docs PR.  I see that it's already been merged, so I'll close this issue out.  Greatly appreciate your contribution to improve our documentation, and let us know if there's a need to reopen this issue or address anything else.
