### ISSUE TITLE
Angular v17 and latest typescript having issues with @aws-amplify sub-dependencies

### ISSUE THREAD

**Issue by simonramosb** [aws-amplify/amplify-js#13260]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

GraphQL API

### Amplify Version

v6

### Amplify Categories

api

### Backend

Other

### Environment information

<details>

```
# Put output below this line
Angular v17.3.4
node 18 lts
typescript: 5.4.5
aws-amplify: 6.0.28

```

</details>

### Describe the bug

I'm migrating an app made with ionic and angular, to newer versions (v17, where i need typescript >= 5.2.0). Everything seems fine, until i built. 

I had lots of these errors, with the `@aws-amply/plugin-types` package. (Detailed in log output section)

```
Error: node_modules/@aws-amplify/plugin-types/lib/function_resources.d.ts:1:40 - error TS2307: Cannot find module 'aws-cdk-lib/aws-lambda' or its corresponding type declarations
```

I found out that is a dependency of  @aws-amplify/data-schema-types
`yarn.lock` screenshot: 
![image](https://github.com/aws-amplify/amplify-js/assets/64170232/d15cce16-f22c-48a8-bf96-159dac48431e)

If i rollback to typescript `4.9.5` everything works fine, but its not compatible with angular v17.

Thanks in advance for reading my issue, any ideas or possible hacks will be highly appreciated :)

### Expected behavior

Correct build

### Reproduction steps

1. yarn install
2. ionic serve // ng serve // ng build

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>
// Put your logs below this line

```
[ng] Error: node_modules/@aws-amplify/plugin-types/lib/auth_resources.d.ts:1:23 - error TS2307: Cannot find module 'aws-cdk-lib/aws-iam' or its corresponding type declarations.
[ng] 
[ng] 1 import { IRole } from 'aws-cdk-lib/aws-iam';
[ng]                         ~~~~~~~~~~~~~~~~~~~~~
[ng] 
[ng] 
[ng] Error: node_modules/@aws-amplify/plugin-types/lib/auth_resources.d.ts:2:142 - error TS2307: Cannot find module 'aws-cdk-lib/aws-cognito' or its corresponding type declarations.
[ng] 
[ng] 2 import { CfnIdentityPool, CfnIdentityPoolRoleAttachment, CfnUserPool, CfnUserPoolClient, CfnUserPoolGroup, IUserPool, IUserPoolClient } from 'aws-cdk-lib/aws-cognito';
[ng]                                                                                                                                                ~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] 
[ng] 
[ng] Error: node_modules/@aws-amplify/plugin-types/lib/backend_secret_resolver.d.ts:1:27 - error TS2307: Cannot find module 'constructs' or its corresponding type declarations.
[ng] 
[ng] 1 import { Construct } from 'constructs';
[ng]                             ~~~~~~~~~~~~
[ng] 
[ng] 
[ng] Error: node_modules/@aws-amplify/plugin-types/lib/backend_secret_resolver.d.ts:3:29 - error TS2307: Cannot find module 'aws-cdk-lib' or its corresponding type declarations.
[ng] 
[ng] 3 import { SecretValue } from 'aws-cdk-lib';
[ng]                               ~~~~~~~~~~~~~
[ng] 
[ng] 
[ng] Error: node_modules/@aws-amplify/plugin-types/lib/backend_stack_creator.d.ts:1:23 - error TS2307: Cannot find module 'aws-cdk-lib' or its corresponding type declarations.
[ng] 
[ng] 1 import { Stack } from 'aws-cdk-lib';
[ng]                         ~~~~~~~~~~~~~
[ng] 
[ng] 
[ng] Error: node_modules/@aws-amplify/plugin-types/lib/construct_container.d.ts:1:27 - error TS2307: Cannot find module 'constructs' or its corresponding type declarations.
[ng] 
[ng] 1 import { Construct } from 'constructs';
[ng]                             ~~~~~~~~~~~~
[ng] 
[ng] 
[ng] Error: node_modules/@aws-amplify/plugin-types/lib/function_resources.d.ts:1:40 - error TS2307: Cannot find module 'aws-cdk-lib/aws-lambda' or its corresponding type declarations.
[ng] 
[ng] 1 import { CfnFunction, IFunction } from 'aws-cdk-lib/aws-lambda';
[ng]                                          ~~~~~~~~~~~~~~~~~~~~~~~~
[ng] 
[ng] 
[ng] Error: node_modules/@aws-amplify/plugin-types/lib/resource_access_acceptor.d.ts:1:24 - error TS2307: Cannot find module 'aws-cdk-lib/aws-iam' or its corresponding type declarations.
[ng] 
[ng] 1 import { Policy } from 'aws-cdk-lib/aws-iam';
[ng]                          ~~~~~~~~~~~~~~~~~~~~~
[ng] 
[ng] 
[ng] 
```

</details>

**Comment by cwomack** [comment]
@simonramosb, thank you for opening this issue. Just to confirm, is this a Gen2 app that you're experiencing this in?

**Comment by simonramosb** [comment]
Hey @cwomack! Thanks for your reply. No, the last team used this library just for handling connections to an appsync endpoint. Why? I dont really know haha. I'm here just for the typescript version, cause i can't upgrade angular.

**Comment by cwomack** [comment]
@simonramosb, can you clarify if you are trying to create a Gen 2 app in this migration and do you have the `aws-cdk-lib` package under your dev dependencies (alternatively, you could share your `package.json` as well)?

**Comment by cwomack** [comment]
@simonramosb, just wanted to ping you again to see if you're still blocked by this or saw the above comment.  Let us know!

**Comment by simonramosb** [comment]
We did a rollback and put that task on our backlog. We'll see what happens in a few weeks. 
@cwomack Thanks for the following :)

I'll reopen the issue if the problem persist.
