### ISSUE TITLE
Amplify Authenticator: Buttons "frozen" after back clicking social login 

### ISSUE THREAD

**Issue by alex-breen** [aws-amplify/amplify-js#13274]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Vite

### What browsers are you seeing the problem on?

Chrome, Firefox

### Please describe your bug.

Steps to reproduce: 
1. Load login page running `Authenticator` .
2. Click `Sign in with Google`.
3. Click `back` on your browser to return to the login page.
4. Click `Sign in with Google`.

Observe:
1. All buttons on page are unresponsive.
2. No errors logged.
3. Only workaround is to reload page.

### What's the expected behaviour?

Buttons work after if you click back to the login page. 

### Help us reproduce the bug!

Strangely, this occurs only on a production build, but not on a dev build. 
Ie: Using vite, if you `npm run dev` the behavior is not observed. But if you `npm run build` and `npm run preview` the frozen behavior is observed. 

Reproduction: I've pasted code snippets. But basically this is the came code as documented in v6 of https://docs.amplify.aws/react/start/getting-started/ and https://ui.docs.amplify.aws/react/connected-components/authenticator.

### Code Snippet

```typescript
// Put your code below this line.

-------- index.html  -----------
<!doctype html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <link rel="icon" type="image/svg+xml" href="/vite.svg" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="manifest" href="manifest.json" />
  <title>Vite + React</title>
</head>

<body>
  <div id="root"></div>
  <script type="module" src="/src/main2.jsx"></script>
</body>

</html>

--------  main2.jsx  -----------
import React from 'react'
import ReactDOM from 'react-dom/client'
import App3 from './App3.jsx'

import { Amplify } from 'aws-amplify';
import amplifyconfig from './amplifyconfiguration.json';

Amplify.configure(amplifyconfig);

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App3 />
  </React.StrictMode>,
)

--------  App3.jsx  -----------
import { Authenticator } from "@aws-amplify/ui-react";
import "@aws-amplify/ui-react/styles.css";

const App3 = () => {
    return (
        <div>
            <Authenticator>
                {({ signOut, user }) => (
                    <div>
                        <h1>Hello {user?.username}</h1>
                        <button onClick={signOut}>Sign out</button>
                    </div>
                )}
            </Authenticator>
        </div>
    );
};

export default App3;

```

**Comment by cwomack** [comment]
Hello again, @alex-breen 👋. I'll review this with the JS team and see if we can identify the root cause.

**Comment by cshfang** [comment]
Hi @alex-breen. We are looking into this and I just wanted to provide a quick update on our investigation so far. At this time we believe the issue is related to back/forward cache. Currently, Amplify assumes OAuth redirection causes a page reload but, in the case of a back button press, this may not be the case.

Thank you for reporting this and we appreciate your patience as we work towards a solution.

**Comment by alex-breen** [comment]
For anyone in need of an immediate fix, here is my (somewhat hacky?) workaround which reloads the page on back click. 

```
window.addEventListener("pageshow", (event) => { 
      if (event.persisted) {
           window.location.reload(); 
      }
});
```

**Comment by cwomack** [comment]
@alex-breen, appreciate the workaround suggestion.  There's a PR currently being reviewed and tested for a fix (linked above).

**Comment by israx** [comment]
hello @alex-breen . The fix was released on the latest [version](https://www.npmjs.com/package/aws-amplify) of the library. Can you upgrade and let us know if that worked for you ?

**Comment by alex-breen** [comment]
@israx - it works like a charm after upgrade. Thanks!
I'll close this issue.
