### ISSUE TITLE
how to give user an option to choose between sms and email to get the verification code while Signing Up?

### ISSUE THREAD

**Issue by Sourabhd1164** [aws-amplify/amplify-js#1328]
So by default Cognito sends the verification code to user's email unless phone number is set on user's attribute property and if both sms and email are set on attribute of User the code is sent via sms. 

Is there a way to control this ?

**Comment by pbzona** [comment]
Someone else may have a better way, but here's how I handle the initial verification.

Log into the AWS web console, go to the Cognito service, and choose "Manage User Pools" (not Identity Pools). Select the User Pool for your app, and from the menu on the left, go to "MFA and verifications."

In that section, look for the heading "Do you want to require verification of emails or phone numbers?" and make sure that only the "Email" box is checked:

![screen shot 2018-07-30 at 7 52 26 am](https://user-images.githubusercontent.com/16768769/43398494-dbbcd406-93cd-11e8-861e-4c6a60224b8e.png)

Once you do that, the initial verification will be sent to email, even if a valid phone number exists for the user. For all authentications afterward, SMS will be used as the second factor. Not sure if there's a way to set this on a per-user or per-verification basis, but there are plenty of other global options in the console that may do what you need.

**Comment by Sourabhd1164** [comment]
@pbzona 
I have checked all the options on the console

**Comment by pbzona** [comment]
This sounds like more a problem with the SDK or the Cognito service itself than Amplify. You can likely build out this workflow with SES/SNS yourself if Cognito doesn't support it, but Amplify is just an interface at the end of the day.

**Comment by Sourabhd1164** [comment]
I found a way to achieve this.

When Signing up if you pass just phone number in the user attributes you will get a text and the phone is verified and when you send just email you will get verification code to your email and email is verified but phone number is not verified at this point


**To recieve verification to your phone:**
Auth.signUp(
     username,
     password,
     attributes:{
          phone_number
     }
**To recieve verification to your email:**

Auth.signUp(
     username,
     password,
     attributes:{
          email
     }

**Comment by pbzona** [comment]
Nice, thanks for the update!

Does this only force the verification method by providing a single contact attribute though? If I wanted to store both an email and a phone number, is there a way to specify one verification method over the other?

I'm still thinking this behavior would be configured within Cognito itself, but I could be mistaken.

**Comment by Sourabhd1164** [comment]
Yes, I dont think there is a way to do that rn.
Cognito verifies only phone number when you specify both email and phone_number in the user attributes.
You'll have to verify the email in the next step or sometime later by storing the phone_number( Not sure how )

**Comment by huihe** [comment]
Facing the same issue here. Really hope this could be configurable, email or sms when both are provided.

**Comment by pbzona** [comment]
I don't think there's a way to configure this currently, but it's a limit of the Cognito service, not Amplify. From the Cognito docs:

> If a user signs up with both a phone number and an email address, and your user pool settings require verification of both attributes, a verification code is sent via SMS to the phone. The email address is not verified. Your app can call GetUser to see if an email address is awaiting verification. If it is, the app should call GetUserAttributeVerificationCode to initiate the email verification flow and then submit the verification code by calling VerifyUserAttribute.

[Source](https://docs.aws.amazon.com/cognito/latest/developerguide/signing-up-users-in-your-app.html#allowing-users-to-sign-up-and-confirm-themselves)

So you can probably code in a custom verification flow that does something close to what you want, but it doesn't seem like there's a way to do this out of the box. Seems significant enough that the AWS team might consider it as a feature request - they're good about taking customer feedback if you wanted to contact them about it.

**Comment by haverchuck** [comment]
Closing this issue for now but notifying the Cognito service team.
