### ISSUE TITLE
string.prototype.startswith polyfill does not work in IE for AWS-Amplify

### ISSUE THREAD

**Issue by Ajji11** [aws-amplify/amplify-js#1333]
Do you want to request a feature or report a bug?
BUG

What is the current behavior?
Although a polyfill exists on the project a .startswith function is throwing a 'Syntax' error in vendor.js or main.js in IE 11, preventing the website from loading.
Polyfill for string.prototype.startswith is in the project and works for every other string.startswith.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

This is the function causing the issue:

```
function configFromURL() {
    const config = {};
    const win = window;
    win.location.search.slice(1)
        .split('&')
        .filter(entryText => entryText.startsWith('ionic:'))
        .map(entryText => entryText.split('='))
        .forEach(entry => {
        config[entry[0].slice(6)] = decodeURIComponent(entry[1]);
    });
    return config;
}

```
This line is breaking -         .filter(entryText => entryText.startsWith('ionic:'))

Include AWS-Amplify / AWS-Amplify-Angular in Angular project and use one of the modules.  It adds ionic/core dependency which has this function causing the issue.  In my case I used AmplifyService.api().

What is the expected behavior?
Webpage should load with no errors.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
AWS-Amplify / 1.0.3-unstable.6
AWS-Amplify-Angular / 1.0.2-unstable.1
Ionic-Angular / 4.0.0-alpha.7
Ionic-Core  / 4.0.0-alpha.7

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by jordanranz** [comment]
Hey @Ajji11,

Unfortunately `aws-amplify` will not support for IE11 going forward.

Amplify supports the following browsers:
https://aws.amazon.com/premiumsupport/knowledge-center/browsers-management-console/

I am going to close this issue now, please reopen this issue if you have any related questions or concerns.
