### ISSUE TITLE
Amplify Auth v6 - CookieStorage not working in Localhost

### ISSUE THREAD

**Issue by hanoj-budime** [aws-amplify/amplify-js#13344]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Version

v6

### Amplify Categories

auth

### Backend

None

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

``` cmd
Error at fetchUserAttributes :>>  Error: Network error
    at fetchTransferHandler (:3000/node_modules/.vite/deps/chunk-OF4A5D2P.js?v=2f1ea17f:9074:13)
    at async retryMiddleware (:3000/node_modules/.vite/deps/chunk-OF4A5D2P.js?v=2f1ea17f:8748:20)
    at async userAgentMiddleware (:3000/node_modules/.vite/deps/chunk-OF4A5D2P.js?v=2f1ea17f:9024:24)
    at async :3000/node_modules/.vite/deps/chunk-OF4A5D2P.js?v=2f1ea17f:9115:22
    at async fetchUserAttributes (:3000/node_modules/.vite/deps/chunk-KDJGD37D.js?v=2f1ea17f:6670:30)
    at async fetchUserAttributes (:3000/src/services/amplify.js:80:18)
    
error :>>  Error: Network error
    at fetchTransferHandler (:3000/node_modules/.vite/deps/chunk-OF4A5D2P.js?v=2f1ea17f:9074:13)
    at async retryMiddleware (:3000/node_modules/.vite/deps/chunk-OF4A5D2P.js?v=2f1ea17f:8748:20)
    at async userAgentMiddleware (:3000/node_modules/.vite/deps/chunk-OF4A5D2P.js?v=2f1ea17f:9024:24)
    at async :3000/node_modules/.vite/deps/chunk-OF4A5D2P.js?v=2f1ea17f:9115:22
    at async fetchUserAttributes (:3000/node_modules/.vite/deps/chunk-KDJGD37D.js?v=2f1ea17f:6670:30)
    at async fetchUserAttributes (:3000/src/services/amplify.js:80:18)
```

### Expected behavior

[Update token-saving mechanism](https://docs.amplify.aws/react/build-a-backend/auth/concepts/tokens-and-credentials/#update-your-token-saving-mechanism)

Cookie Storage
https://docs.amplify.aws/react/build-a-backend/auth/concepts/tokens-and-credentials/#update-your-token-saving-mechanism

### Reproduction steps

1. Install Amplify v6
2. Update token-saving mechanism with Cookie Storage

### Code Snippet

This code not working for localhost
``` jsx
import { Amplify } from 'aws-amplify';
import { CookieStorage } from 'aws-amplify/utils';
import { cognitoUserPoolsTokenProvider } from 'aws-amplify/auth/cognito';

const authConfig = {
  Cognito: {
    userPoolId: 'your_user_pool_id',
    userPoolClientId: 'your_user_pool_client_id'
  }
};

Amplify.configure({
  Auth: authConfig
});

cognitoUserPoolsTokenProvider.setKeyValueStorage(new CookieStorage());
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello, @hanoj-budime 👋.  The fact that you're getting a network errors makes me wonder if we need more details about what API's are being called and how Auth has been setup.  Can you clarify if you experience this same errors for all API's?  Are you able to share the fronted code that's calling the Auth API's that are causing this?

**Comment by hanoj-budime** [comment]
![image](https://github.com/aws-amplify/amplify-js/assets/53425981/fc73dbb8-567a-4ec9-9608-0bb22ceeeb29)
![image](https://github.com/aws-amplify/amplify-js/assets/53425981/4a5f3723-e746-47b9-a68f-30f7f6cd626f)
![image](https://github.com/aws-amplify/amplify-js/assets/53425981/f271cf34-312c-4fb6-8e4f-3aab6e0258fa)

**Comment by lucasantunes-ciandt** [comment]
Hello @hanoj-budime, were you able to fix this issue? I'm having a similar issue, with also several Cognito Requests resulting in errors.
