### ISSUE TITLE
Property 'then' does not exist on type 'Promise<GraphQLResult>

### ISSUE THREAD

**Issue by musso** [aws-amplify/amplify-js#1337]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
Angular failed to compile due to `Property 'then' does not exist on type 'Promise<GraphQLResult> | Observable<object>'`

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

1. Create new angular using `Angular CLI: 6.1.1`
`ng new project`
2. Install latest version of Amplify and Amplify 
`npm i -S aws-amplify`
`npm i -S aws-amplify-angular`
3. Setup appsync graphql and config file
4. In a component, `ngOnInit()` function 
`
API.graphql(
      graphqlOperation(your_graphql_here)
).then(data => {
      console.log(data);
});
` or 
`
API.graphql(
      graphqlOperation(your_graphql_here)
).subscribe(data => {
      console.log(data);
});
`

Error message
`error TS2339: Property 'then' does not exist on type 'Promise<GraphQLResult> | Observable<object>'.
  Property 'then' does not exist on type 'Observable<object>'.`

What is the expected behavior?
API.graphql should be an observable or a promise that could use subscribe / toPromise function

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
`"aws-amplify": "^1.0.2",`
`"aws-amplify-angular": "^1.0.2",`
All browsers

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

`error TS2339: Property 'then' does not exist on type 'Promise<GraphQLResult> | Observable<object>'.
  Property 'then' does not exist on type 'Observable<object>'.`

**Comment by musso** [comment]
It only works using async / await function.
```
ngOnInit() {
    this.getAllEvents()
  }


  getAllEvents = async() => {
    let allEvents = await API.graphql(graphqlOperation(`query GetEvent {
      getEvent {
          id
      }
    }`))
  }
```

**Comment by musso** [comment]
For anyone run into this problem, it may be due to the different `Observable` using in amplify-js and angular's default rxjs v6.0.0.

If you re casting `Observable<object>` using `import { Observable } from 'rxjs'`, it fails. 

You have to cast `Observable<object>` using `import * as Observable from 'zen-observable'`

**Comment by stephannagel** [comment]
Hi Musso,

Running in the same issue here. Do you have a working example to share?

Thanks
Stephan

**Comment by musso** [comment]
Hi @stephannagel , try this
```
import { Component, OnInit } from '@angular/core';
import { API, graphqlOperation } from 'aws-amplify';
import * as Observable from 'zen-observable';

@Component({
  selector: 'app-your',
  templateUrl: './your.component.html',
  styleUrls: ['./your.component.scss']
})
export class YourComponent implements OnInit {

 public subscribeSth() {
    let subscription: Observable<object> = API.graphql(graphqlOperation(Your_GraphQL)) as Observable<object>
    subscription.subscribe(res => console.log(res)
}
}```

**Comment by stephannagel** [comment]
Thanks, this works!
