### ISSUE TITLE
Next runWithAmplifyServerContext operation sometimes returns contextSpec for another user if requests are in parallel

### ISSUE THREAD

**Issue by MarekBodingerBA** [aws-amplify/amplify-js#13380]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React, Next.js

### Amplify APIs

Authentication

### Amplify Version

v6

### Amplify Categories

auth

### Backend

Other

### Environment information

Details in the security advisory.

### Describe the bug

I've reported a security advisory, as I can see the issues here are being assigned and resolved while the advisory is without a response for 21 hours. The issue seems to be critical and a bug in Amplify library. Please take a look at the advisory.

https://github.com/aws-amplify/amplify-js/security/advisories/GHSA-78h9-vrf3-cxx5

### Expected behavior

Details in the security advisory.

### Reproduction steps

Details in the security advisory.

### Code Snippet

Details in the security advisory.

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by haverchuck** [comment]
@MarekBodingerBA We are investigating.

**Comment by OrmEmbaar** [comment]
Has this been resolved?

**Comment by haverchuck** [comment]
This has been addressed in aws-amplify version 6.3.4. If you are using the @aws-amplify/adapter-nextjs package version, you should use 1.2.4 or newer.
