### ISSUE TITLE
Login flow - random User cancelled OAuth flow errors

### ISSUE THREAD

**Issue by Lirontal1** [aws-amplify/amplify-js#13393]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

React App using Vite

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

We're using Amplify as our 3rd party library for logging in with Cognito.
We're seeing some users get `User cancelled OAuth flow` randomly when trying to log in.
I've looked at Amplif's code base, and can confirm the users have BOTH state & code in the URL, and they do not go back using the browser.
In the hub listener we have in our app, we logout the user when we recieve a `signInWithRedirect_failure` event, so it logs them out.

### What's the expected behaviour?

Users should always be able to log in without a trouble

### Help us reproduce the bug!

Unsure, it's really random and didn't find a reproducable way

### Code Snippet

```typescript
// Put your code below this line.

 const unsubscribe = Hub.listen('auth', ({ payload }) => {
      switch (payload.event) {
        ....
        case 'signInWithRedirect_failure':
          logout();
          navigate('');
          console.error(`[authentication error]: LOGIN FAIL: ${JSON.stringify(payload.data.error?.message)}`);
          document.location.reload();
          break;
        ....
        default:
          break;
      }
    });
```

### Console log output

[authentication error]: LOGIN FAIL: "User cancelled OAuth flow."

**Comment by israx** [comment]
hello @Lirontal1 . Getting the `User cancelled OAuth flow` error and receiving `code` and `state` in the query params should be mutually exclusive. Usually that error is thrown as long as the user clicks the browser's back button.

**Comment by israx** [comment]
We had a similar issue and a customer solved it by changing some app routes. Could that solution applied [here](https://github.com/aws-amplify/amplify-js/issues/12999#issuecomment-2078749907) solve your issue ?

**Comment by ronbhomri** [comment]
@israx it happens to several users, all uses SAML for login (Okta, Azure AD etc..).
we can see in the session recording all the users return to our login page with the `code` and `state` in the URL, but we get in the `Hub.listen` the `signInWithRedirect_failure`. In the second time usually works.

**Comment by cwomack** [comment]
@Lirontal1 or @ronbhomri, wanted to check in and see if either of you are able to help us reproduce this better via a sample app per @israx request above.  Let us know if this is still a blocker for you, thanks!

**Comment by ronbhomri** [comment]
@cwomack we shared a sample repo [here](https://github.com/aws-amplify/amplify-js/issues/13486). Thanks!

**Comment by israx** [comment]
hello @ronbhomri . I was not able to reproduce the issue based on the provided app. Could you specific the steps to reliable reproduce it ?

**Comment by ronbhomri** [comment]
@israx it happens usually when you try to login via SAML connection (for example Okta)

**Comment by cwomack** [comment]
@ronbhomri, can you provide the entirety of networks logs that you see when attempting to sign in and experiencing this?  It's sounding like there's an issue happening when trying to redirect back from the federation from the Okta side.

**Comment by cwomack** [comment]
@Lirontal1 or @ronbhomri, are either one of you able to confirm/provide any further details about the about network logs? Thanks.

**Comment by ronbhomri** [comment]
@cwomack Can it be related to internet connection? we experienced a lot on network connection issues lately and we think it has something to do with it

**Comment by ronbhomri** [comment]
@cwomack or @israx, can you answer on the above question? I believer it has something to do with poor internet connection

**Comment by cwomack** [comment]
Hey, @ronbhomri! Appreciate your patience on a response here as I haven't been able to reproduce this on our side.  It's possible that a poor network connection could result in errors you're experiencing, but I think we need more information to definitively say that.  Do you have any additional information or logs that we can dissect further that would help us understand the users that are experiencing this?

**Comment by ronbhomri** [comment]
@cwomack I think the best thing here that will also solve us more errors we have during login will be to have a way to know the users passed the `signInWIthRedirect` login -> meaning they logged in via the custom provider and now they should have a valid session. 
Since Cognito add a cookie which is not reachable via JS, is there another way to know it?

**Comment by cwomack** [comment]
@ronbhomri, you should be able to use the 'signInWithRedirect' case (as seen [here](https://docs.amplify.aws/react/build-a-backend/auth/connect-your-frontend/listen-to-auth-events/#listen-to-and-log-auth-events)).  I know in the original description of this issue the `signInWithRedirect_failure` Hub event was being listened for, but do you already have the `signInWithRedirect` implemented as well?

**Comment by cwomack** [comment]
@ronbhomri, did the above the above docs link help? Wanted to check in and see if you're still blocked here. 

CC: @Lirontal1

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
