### ISSUE TITLE
Support for Content-MD5 header irrespective of objectlock.

### ISSUE THREAD

**Issue by sushpatg** [aws-amplify/amplify-js#13395]
### Is this related to a new or existing framework?

React

### Is this related to a new or existing API?

Storage

### Describe the feature you'd like to request

To add ContentMD5 header while making request irrespective of objectlock.

### Describe the solution you'd like

Currently we have Pull request - [11611](https://github.com/aws-amplify/amplify-js/pull/11611) where Content-MD5 header is supported when ObjectLock is enabled.

I was able to see ContentMD5header if `isObjectLockEnabled: true` in Storage.configure(). But have not enabled object lock for S3 bucket.

Looking for solution to pass pass ContentMD5 header irrespective of objectlock.

### Describe alternatives you've considered

I was able to see ContentMD5header if `isObjectLockEnabled: true` in Storage.configure(). But have **not** enabled object lock for S3 bucket.

```

Amplify.configure(config);
Storage.configure(
  {
    AWSS3:
    {
      bucket: config.aws_user_files_s3_bucket, //REQUIRED -  Amazon S3 bucket name
      region: config.aws_user_files_s3_bucket_region, //OPTIONAL -  Amazon service region
      isObjectLockEnabled: true
    }
  }
)

```

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by HuiSF** [comment]
Hi @sushpatg thanks for making this feature request. In your use cases, do you compute the MD5 digest yourself?

**Comment by cwomack** [comment]
@sushpatg, can you confirm that what's being asked for in this issue is support of the `ContentMD5` option within Storage (as detailed [here](https://docs.amplify.aws/gen1/react/build-a-backend/storage/storage-v5-to-v6-migration-guide/#pageMain:~:text=ContentMD5%3F%3A%20string%3B) in v5 docs) for the v6 `uploadData` API? Or was there another use case or API that you're trying to use for this?

**Comment by sushpatg** [comment]
@cwomack, as per my testing `ContentMD5` does not work even in v5 unless one has configured [isObjectLockEnabled](https://docs.amplify.aws/gen1/react/build-a-backend/storage/existing-resources/#configure-s3-object-lock) to true.

Also as per the below excerpt from [S3 documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html), we should be able to  pass ContentMD5 header manually(calculated outside) or if not passed amplify-js should calculate it for us

```
When you upload an object, you can optionally include a precalculated checksum as part of your request. Amazon S3 compares the provided checksum to the checksum that it calculates by using your specified algorithm. If the two values don't match, Amazon S3 reports an error
```

**Comment by sushpatg** [comment]
> Hi @sushpatg thanks for making this feature request. In your use cases, do you compute the MD5 digest yourself?

Yes, we can calculate it ourselves

**Comment by cwomack** [comment]
@sushpatg, this should now be supported within the Storage client library.  Can you test and validate this to let us know if it's working sufficiently for you? Thanks!
