### ISSUE TITLE
Validating phone number fails even if phone number is optional

### ISSUE THREAD

**Issue by therealkh** [aws-amplify/amplify-js#13391]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Version

v5

### Amplify Categories

auth

### Backend

None

### Environment information

<details>

```
Permission denied


```

</details>

### Describe the bug

I created the same user pool as we are using for a while with the same configuration. Phone number is optional field. And when you try to sign up without entering phone number to old user pool it works fine. But when you try to do it with new user pool (with the same configuration) it throws error that says that phone number validation failed.

# Request: 
```json
{
  "ClientId": "4rl2ggkq6dgjo9at*******",
  "Username": "ukhamidov******.io",
  "Password": "123456789Pp",
  "UserAttributes": [
    {
      "Name": "phone_number",
      "Value": ""
    },
    {
      "Name": "email",
      "Value": "ukhamidov@******.io"
    }
  ],
  "ValidationData": null
}
```
# Response: 
```json
{
  "__type": "InvalidParameterException",
  "message": "Attributes did not conform to the schema: 2 validation errors detected: Value at 'userAttributes.phoneNumbers.member.complexListValue.1.member.value.member.stringValue' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\p{L}\\p{M}\\p{S}\\p{N}\\p{P}\\t\\n\\r  　]+; Value at 'userAttributes.phoneNumbers.member.complexListValue.1.member.value.member.stringValue' failed to satisfy constraint: Member must have length greater than or equal to 1"
}
```

### Status Code

`400`

The same is happening with V6 as well. 

### Expected behavior

Cognito shouldn't try to validate phone number if it is optional and user didnt enter it.

### Reproduction steps

Here is user pool configuration: 
<img width="809" alt="Screenshot 2024-05-16 at 16 24 57" src="https://github.com/aws-amplify/amplify-js/assets/65399389/e2232e88-b6b2-4242-b5c1-11fbd0e76337">
<img width="809" alt="Screenshot 2024-05-16 at 16 25 54" src="https://github.com/aws-amplify/amplify-js/assets/65399389/c10659b8-2a28-43d6-bc49-0ff2dcd210a2">
<img width="810" alt="Screenshot 2024-05-16 at 16 25 23" src="https://github.com/aws-amplify/amplify-js/assets/65399389/314ba4ae-ebbb-454f-904f-1379b5508e89">
<img width="818" alt="Screenshot 2024-05-16 at 16 23 48" src="https://github.com/aws-amplify/amplify-js/assets/65399389/53d81227-ed35-4a43-a4a9-fd2ab1a7cfbb">
<img width="809" alt="Screenshot 2024-05-16 at 16 25 13" src="https://github.com/aws-amplify/amplify-js/assets/65399389/bc9d7179-dd8a-4b03-a535-f89fb7630846">
<img width="813" alt="Screenshot 2024-05-16 at 16 24 25" src="https://github.com/aws-amplify/amplify-js/assets/65399389/464a5853-c873-4a9c-9d98-9c7934dfad1f">
<img width="837" alt="Screenshot 2024-05-16 at 16 23 22" src="https://github.com/aws-amplify/amplify-js/assets/65399389/3b0cf02b-761b-4249-8ec1-70db3f0f74b3">
<img width="811" alt="Screenshot 2024-05-16 at 16 25 42" src="https://github.com/aws-amplify/amplify-js/assets/65399389/e11293d7-bcc2-4752-9286-c0bf44148669">
<img width="821" alt="Screenshot 2024-05-16 at 16 23 39" src="https://github.com/aws-amplify/amplify-js/assets/65399389/c3dd52a3-3526-467d-9e26-36eaf91d3278">
<img width="816" alt="Screenshot 2024-05-16 at 16 24 15" src="https://github.com/aws-amplify/amplify-js/assets/65399389/e052a0ae-3f66-46f2-aa33-df6c18408bab">
<img width="808" alt="Screenshot 2024-05-16 at 16 24 48" src="https://github.com/aws-amplify/amplify-js/assets/65399389/8b531e10-d7da-4daa-9690-45478093e735">

**Comment by israx** [comment]
hello @therealkh . The request contains the `phone_number` as an empty string. Even though the attribute is optional, cognito is trying to validate the input. Is it possible for you to not include the phone_number at runtime ? Optional attributes can always be added at a later point

**Comment by therealkh** [comment]
@israx thanks for response, it helped

**Comment by makeitraina** [comment]
This issue should be re-opened. @israx your comment is a work-around. It doesn't address the fact that this is a regression in Cognito. Why did this stop working.

@therealkh called out:
> I created the same user pool as we are using for a while with the same configuration. Phone number is optional field. And when you try to sign up without entering phone number to old user pool it works fine

Im experiencing the same issue, and I dont expect to update our codebase to fix the problem, rather I expect Cognito to work consistently. Can you please link to documentation that explains when this changed and any other coms from the Cognito team here.

**Comment by vrajasekhar1** [comment]
We are also facing exactly the same issue. Our signup code works with old user pool, but fails with new user pool. Seems some latest changes to cognito have introduced this issue. Please reopen and resolve this issue, so that signup implementations work seamlessly.
