### ISSUE TITLE
API Adapter Class for REST Operations

### ISSUE THREAD

**Issue by Rajan-Gupta1** [aws-amplify/amplify-js#13401]
### Is this related to a new or existing framework?

Angular

### Is this related to a new or existing API?

REST API

### Describe the feature you'd like to request

In previous versions of Amplify it provides a API() function which was easy to convert into an observable by applying the rxjs from such as 
 getData(): Observable<Doctor[]> {
    const queryParam = {
      headers: {
      },
      queryStringParameters: {
      }
    };
    return from(API.get(this.MDapiEndPoint, "/getData", queryParam));
  }
Would it be possible to provide a helper class which really made it easy to use REST ops in an angular app.

### Describe the solution you'd like

Put back API class that was available in previous versions of Amplify

### Describe alternatives you've considered

None

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by jimblanc** [comment]
@Rajan-Gupta1 Thank you for your report! Are you trying to use Amplify JS v6? You should be able to use RXJS' `from` utility on the response promise, for example:

```
const getOperation = get('apiName', '/getData');
return from(getOperation.response);
```

**Comment by Rajan-Gupta1** [comment]
@jimblanc  Thanks for your response. The challenge I am having is that it is forcing me to make the function async since now I am unable to provide the Authorization token in awsconfig in the configuration like I was able to like this:
 {
                name: "chimeAPI",
                endpoint: environment.medBodyCareAPI_endpoint,
                custom_header: async () => { 
                    return { Authorization: `Bearer ${(await Auth.currentSession()).getIdToken().getJwtToken()}` }
                }
            },
Now I am having to provide get the idToken as await 
const authToken = (await fetchAuthSession()).tokens?.idToken?.toString();
which is making me mark the function async. 
How do you suggest that your above suggestion will work when authorization token is needed and an observable using from must be returned?

**Comment by cwomack** [comment]
@Rajan-Gupta1, did you only experience this when upgrading to v6? And can you provide any context on why you're not looking to have the functions async?  

You can get the tokens needed elsewhere for your custom header (using await) or convert your function to async.  But I don't think there's going to be a way around making things async/await if I'm understanding your use case properly.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
