### ISSUE TITLE
No federated JWT token when using AppSync OIDC in Amplify Gen2

### ISSUE THREAD

**Issue by tafman2002** [aws-amplify/amplify-js#13428]
### Environment information

```plain text
System:
  OS: macOS 14.4.1
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 44.23 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.12.2 - /usr/local/bin/node
  Yarn: 1.22.21 - /usr/local/bin/yarn
  npm: 10.5.0 - /usr/local/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.0
  @aws-amplify/backend-cli: 1.0.1
  aws-amplify: 6.2.0
  aws-cdk: Not Found
  aws-cdk-lib: Not Found
  typescript: 5.4.5
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

**Description:**
Currently, when trying to use AppSync OIDC (OpenID Connect) authorizer using external identity provider (e.g Auth0, Clerk) within an Amplify project, it throws an error related to the federated JWT not being available within Next JS application.
**Steps taken**
We found resources on using external identity providers like Auth0 within the console from the blog (https://aws.amazon.com/blogs/mobile/appsync-auth0/). Tried to replicate that but this time using a Next js app with aws amplify gen2 library (authentication is handled by the auth0 sdk by creating `/api/auth/[auth0]`) following example:
(https://auth0.com/docs/quickstart/webapp/nextjs/01-login)

 and once we receive the access token from Auth0, we attempt to set it in the graphql call when calling a route handler: 
 ```
 const newTodo  = await cookieBasedClient.graphql({
        query: `
        mutation CreateTodo($input: CreateTodoInput!) {
          createTodo(input: $input) {
            content
          }
        }
      `,
        variables: {
            input: {
                content: form.get('content') as string
            },
        },
        authToken: token, 
    }); 
```

In the `amplify/data/resource.ts`:
```
const schema = a.schema({
 Todo: a
   .model({
     content: a.string(),
   })
   .authorization([a.allow.owner('oidc'), a.allow.private('oidc').to(['read'])]),
 Post: a.model({
   title: a.string().required(),
   comments: a.hasMany("Comment")
 }).authorization([a.allow.private('oidc').to(['read']), a.allow.owner('oidc').identityClaim('user_id')]), // Allow signed-in user to create, read, update,


 // Comment Table created in DynamoDB
 Comment: a.model({
   content: a.string(),
   post: a.belongsTo("Post")
 }).authorization([a.allow.private('oidc').to(['read']), a.allow.owner('oidc').identityClaim('user_id')]),
});


export type Schema = ClientSchema<typeof schema>;


export const data = defineData({
 schema,
 authorizationModes: {
   defaultAuthorizationMode: 'oidc',
   oidcAuthorizationMode: {
     oidcProviderName: 'Auth0-Provider',
     oidcIssuerUrl: 'URL',
     clientId: 'CLIENT_ID,
     tokenExpiryFromAuthInSeconds: 300,
     tokenExpireFromIssueInSeconds: 600,
   },
 },
});
```
But I continue to get a `no federated jwt`. I found the following [github issue](https://github.com/aws-amplify/amplify-js/issues/6585) which seems to be similar but Any guidance here is helpful. Thanks

**Comment by chrisbonifacio** [comment]
Hi @tafman2002 👋

Can you share some details about how the user is authenticating? Are you using `federatedSignIn` to authenticate the user and exchange the Auth0 credentials for Cognito credentials?

Otherwise, did you try the steps mentioned in this comment on the issue you linked?

https://github.com/aws-amplify/amplify-js/issues/6585#issuecomment-674556103

**Comment by tafman2002** [comment]
Hi @chrisbonifacio 
So a quick update: My first approach was using the the following api route handler which takes me through the Auth0 login portal:
```
 <a href="/api/auth/login">Login</a>
``` 
That was a direct sdk and attempted to AppSync OIDC Token. 

I am now attempting the integration using ***Amazon Cognito*** but using Cognito Identity Pool, not Cognito User Pool (CUP) which the `federatedSignIn` falls under. Looking at the Cognito Federation in the Gen2 wiki [Advanced Workflow](https://docs.amplify.aws/nextjs/build-a-backend/auth/advanced-workflows/),the example seems to show for React Frontend so not sure if this will work for Next Server Components. 

I haven't tried the following code `Cache.setItem('federatedInfo', { token: raw_token })` in the [comment](https://github.com/aws-amplify/amplify-js/issues/6585#issuecomment-674556103) yet but I wanted to see if this is a recommended practice or an anti-pattern with AWS Amplify

**Comment by chrisbonifacio** [comment]
Hi @tafman2002 , either approach should be fine. If you don't authenticate the user using `federatedSignIn`, then the `Cache.setItem` approach would be the way to "hydrate" the Amplify client with the credentials. However, if you can federate using the Identity Pool then we recommend that approach instead. Amplify will simply exchange the OIDC token for Cognito credentials and perform the `Cache.setItem` step in the background.

**Comment by tafman2002** [comment]
Alright. Sounds Good. I will attempt the approach above and get back to you

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
