### ISSUE TITLE
[v6] resetPassword not trigger UserMigration lambda

### ISSUE THREAD

**Issue by natuan62** [aws-amplify/amplify-js#13425]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

Authentication

### Amplify Version

v6

### Amplify Categories

auth

### Backend

None

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

when resetPassword with amplify v6, but not trigger UserMigration lambda

### Expected behavior

UserMigration lambda trigger works fine

### Reproduction steps

1. resetPassword
2. confirmResetPassword
3. check cloud-watch but UserMigration not trigger

### Code Snippet

```javascript
// Put your code below this line.
import { resetPassword } from 'aws-amplify/auth';

const email = '';
await resetPassword({ username: emaill });

const password = '';
const code = '';
await confirmResetPassword({
          username: email,
          newPassword: password,
          confirmationCode: code,
        });
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

```
    Auth: {
      Cognito: {
        userPoolClientId: '',
        userPoolId: '',
        identityPoolId: '',
       // https://stackoverflow.com/questions/52664612/cognito-user-migration-trigger-not-firing?rq=4
        authenticationFlowType: 'USER_PASSWORD_AUTH', //<=== try to add this flowtype but it still not working
      },
    },
```

**Comment by cwomack** [comment]
Hello, @natuan62 and sorry to hear you're running into this.  Do you know what the UserStatus of the user is that you're trying to migrate (i.e. CONFIRMED / UNCONFIRMED / FORCE_CHANGE_PASSWORD)?
