### ISSUE TITLE
setPreferredMFA -> getPreferredMFA still broken :(

### ISSUE THREAD

**Issue by CHR15-** [aws-amplify/amplify-js#1343]
### Do you want to request a feature or report a bug?

**Bug**

### What is the current behavior?

I have the following code

```
return updateUserAttribute('phone_number', phoneNumber)(dispatch)
    .then(() => Auth.currentAuthenticatedUser())
    .then((user: AmplifyUser) => Auth.setPreferredMFA(user, SMS))
    .then(() => Auth.currentAuthenticatedUser())
    .then((user: AmplifyUser) => getPreferredMFA(user)(dispatch));
```

The first issue is setting SMS as MFA initially fails (`Auth.setPreferredMFA(user, SMS))`), returning `User has not verified software token mfa`. I believe this error comes from [CognitoUser.Protoype.setUserMfaPreference](https://github.com/aws-amplify/amplify-js/blob/07a671f79e40daed7dbd2086182eb7881c046dd5/packages/amazon-cognito-identity-js/es/CognitoUser.js#L894). There is no software token MFA because we are setting sms!

For some reason, the above (even in the exception) works and sets the user to SMS MFA. If I now log out and log back in.. I get presented with an MFA challenge and an SMS is sent to my phone, however the API call to getUser still has an odd response that differs to SOFTWARE_TOKEN_MFA (same response again as https://github.com/aws-amplify/amplify-js/issues/1259) 

Example of incorrect format:

```
{  
   "MFAOptions":[  
      {  
         "AttributeName":"phone_number",
         "DeliveryMedium":"SMS"
      }
   ],
   "UserAttributes":[  
      {  
         "Name":"sub",
         "Value":"83687830-daeb-48fe-a0d0-3120d428a0be"
      },
      {  
         "Name":"email_verified",
         "Value":"true"
      },
      {  
         "Name":"name",
         "Value":"chris"
      },
      {  
         "Name":"phone_number_verified",
         "Value":"true"
      },
      {  
         "Name":"phone_number",
         "Value":"+44XXXXX"
      },
      {  
         "Name":"custom:signupdomain",
         "Value":"http://localhost:9001"
      },
      {  
         "Name":"email",
         "Value":"XXXXX"
      }
   ],
   "Username":"XXXXX"
}
```

This should be exactly how TOTP works, but with SMS:

```
"PreferredMfaSetting":"SMS_MFA",
"UserAttributes":[...]
"UserMFASettingList":[  
      "SMS_MFA"
   ],
```

If I check Auth.getPreferredMFA, the response after setting SMS & logging in with the text message gives me 'NOMFA'.. which isn't right as clearly it's set! :/ 

### What is the expected behavior?

- There shouldn't be a failure when setting SMS as MFA option initially
- getPreferredMFA should return `SMS_MFA` rather than `NOMFA`
- getUser after setting SMS as MFA should be returning the following:

```
{  
   "PreferredMfaSetting":"SMS_MFA",
   "UserAttributes":[  
      {  
         "Name":"sub",
         "Value":"uuid"
      },
      {  
         "Name":"email_verified",
         "Value":"true"
      },
      {  
         "Name":"name",
         "Value":"chris"
      },
      {  
         "Name":"phone_number_verified",
         "Value":"false"
      },
      {  
         "Name":"phone_number",
         "Value":"xxx"
      },
      {  
         "Name":"custom:signupdomain",
         "Value":"http://localhost:9001"
      },
      {  
         "Name":"email",
         "Value":"chris@example.com"
      }
   ],
   "UserMFASettingList":[  
      "SMS_MFA"
   ],
   "Username":"uuid"
}
```

### Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

**1.0.4**

**Comment by powerful23** [comment]
@CHR15- @CHR15- sorry about that. I am working on to have a fix on that and we will also talk to the Cognito service team about this issue.

**Comment by CHR15-** [comment]
thanks @powerful23 .. appreciated as always!

**Comment by nihp** [comment]
I have set the MFA as optional, so some users not receiving code and their MFA is in disable state. Need to manually enable the MFA.

How can I enable via aws-amplify-react-native while signUp for this case
