### ISSUE TITLE
Auth.SignIn not allowing username only signin

### ISSUE THREAD

**Issue by akhilrangu** [aws-amplify/amplify-js#13435]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Version

v6

### Amplify Categories

auth

### Backend

None

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

Auth.signIn throws the following error in Amplify v6 EmptySignInPassword: password is required to signIn when I am only logging in with a username.
I've configured lambda trigger, clientMetaData/validationData is getting triggered as well in backend, when given password.
But without password, it is throwing the "EmptySignInPassword" error.

### Expected behavior

Allow signin with username only but require next step to provide challenge via confirmSignin

### Reproduction steps

  try {
    const user = await Auth.signIn({ username, options : { clientMetadata: { key: "value"   } } });
    return user;
  } catch (error) {
    console.error("Error ", error);
    throw error;  }
};

### Code Snippet

```javascript
// Put your code below this line.
  try {
    const user = await Auth.signIn({ username, options : { clientMetadata: { key: "value"   } } });
    return user;
  } catch (error) {
    console.error("Error ", error);
    throw error;  }
};


```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by israx** [comment]
hello @akhilrangu . In order to kickoff a custom sign-in flow without password you need to call `signIn` the `CUSTOM_WITHOUT_SRP` authFlowType. e.g

```
await signIn({
username:'your-username',
options:{
  authFlowType:'CUSTOM_WITHOUT_SRP',
}})
```

**Comment by cwomack** [comment]
@akhilrangu, wanted to check in and see if you've had a chance to review @israx's recommendation above.  Let us know if you're still experiencing this issue.  Thanks!

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
