### ISSUE TITLE
[v6] sendUserAttributeVerificationCode not send code to destination email

### ISSUE THREAD

**Issue by natuan62** [aws-amplify/amplify-js#13432]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

Authentication

### Amplify Version

v6

### Amplify Categories

auth

### Backend

None

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

1. updateUserAttribute with `email` attributeKey
2. sendUserAttributeVerificationCode but can't receive any code

### Expected behavior

sendUserAttributeVerificationCode will works fine

### Reproduction steps

1. updateUserAttribute
2. sendUserAttributeVerificationCode

### Code Snippet

```javascript
// Put your code below this line.
import {
  signIn,
  fetchUserAttributes,
  updateUserAttribute,
  confirmUserAttribute,
  UpdateUserAttributeOutput,
  sendUserAttributeVerificationCode,
} from 'aws-amplify/auth';

const handleUpdateUserAttributeNextSteps = async (output: UpdateUserAttributeOutput) => {
      const { nextStep } = output;

      switch (nextStep.updateAttributeStep) {
        case 'CONFIRM_ATTRIBUTE_WITH_CODE':
          const {codeDeliveryDetails} = nextStep;
          console.log(
            `Confirmation code was sent to ${codeDeliveryDetails?.deliveryMedium}.`,
          );
          const res = await sendUserAttributeVerificationCode({
            userAttributeKey: 'email',
          });
          console.log('sendUserAttributeVerificationCode res', res);
          // Collect the confirmation code from the user and pass to confirmUserAttribute.
          break;
        case 'DONE':
          console.log('attribute was successfully updated.');
          break;
      }
    };

const output = await updateUserAttribute({
          userAttribute: {
            attributeKey: 'email',
            value: formEmail.newEmail,
          },
        });
        console.log('updateUserAttribute output', output);
        await handleUpdateUserAttributeNextSteps(output);
```

### Log output

```

 1. console.log('updateUserAttribute output', output);
=> {
    "isUpdated": false,
    "nextStep": {
        "updateAttributeStep": "CONFIRM_ATTRIBUTE_WITH_CODE",
        "codeDeliveryDetails": {
            "attributeName": "email",
            "deliveryMedium": "EMAIL",
            "destination": "l***@g***"
        }
    }
}

 2. console.log(
            `Confirmation code was sent to ${codeDeliveryDetails?.deliveryMedium}.`,
          );

=> Confirmation code was sent to EMAIL.

3. console.log('sendUserAttributeVerificationCode res', res);
=> {
    "destination": "l***@g***",
    "deliveryMedium": "EMAIL",
    "attributeName": "email"
}
```

**Comment by natuan62** [comment]
I try to add email value field like this https://github.com/pj4269/amplify-vite-react-template/blob/12be5f0d77ca9f182d3f33e29f1cc15d828676f8/src/components/Profile.tsx#L100
But it still not working

```javascript
const email = '';

await sendUserAttributeVerificationCode({
        userAttributeKey: 'email',
        email, <======
      } as SendUserAttributeVerificationCodeInput);
```

**Comment by israx** [comment]
Hello @natuan62 . You should get a verification code when using the `updateUserAttribute` API and then you should be able to confirm it using the `confirmUserAttribute` API.

The `sendUserAttributeVerificationCode` API can be used to send a code for an attribute that hasn't being verified yet. Sometimes you would create a user with `phone_number` and `email` but only one of them might end up being verified during the registration and login process.

**Comment by natuan62** [comment]
@israx thanks for your reply. but when I using 

```
await updateUserAttribute({
          userAttribute: {
            attributeKey: 'email',
            value: formEmail.newEmail,
          },
        });
```

my email on cognito changed to new email, and email_verified set to false. but it didn't receive any email for verficiation code

**Comment by israx** [comment]
is `email` configured to be an optional attribute ?

**Comment by ElvisSerafim** [comment]
Hello! 

I'm going through exactly this problem. How did you solve it? My email field is optional too. Do I need to change it to mandatory only or do I need to do another step?
