### ISSUE TITLE
Any chance of an Amplify-Vue/cli3.0 starter with User Auth and sample lists ?

### ISSUE THREAD

**Issue by rojagit** [aws-amplify/amplify-js#1344]
Do you want to request a feature or report a bug?
Feature

**Comment by haverchuck** [comment]
@rojagit Do you mean a starter application that is build with v3.0 of the Vue CLI?   I am not aware that v3.0 of the actual Vue library is available yet.

**Comment by rojagit** [comment]
@haverchuck Cudv've sworn I saw it somewhere :) You're right, I will close this out.

**Comment by rojagit** [comment]
I guess it was Vue-cli 3.0 I was lookin at...this is all soooo confusing lol

**Comment by rojagit** [comment]
Re-opening with edit in title, I meant Vue-cli 3.0

**Comment by haverchuck** [comment]
Should include ability to:
a) access remotely, not just local
b) persist data in dynamobdb.

**Comment by rojagit** [comment]
@haverchuck Will the starter app include all presets ? Or at least PWA, Router & Vuex so as to show us the right way to start using it ? Thanks...and any rough ETA on this ? days/weeks/etc ?

**Comment by haverchuck** [comment]
@rojagit We've just added an aws-amplify-vue package to our main amplify library, and the starter has been updated to use it.  The next step is to add the cloud persistence as you described.

**Comment by haverchuck** [comment]
@rojagit We have just updated the starter app so that it uses AWS Appsync to store the 'notes' instead of the cache.  I am closing this issue now, but please feel free to reopen it if this isn't what you wanted.

**Comment by rojagit** [comment]
Awesome ! Will give it a shot soon ..Thank you!
