### ISSUE TITLE
React-Native endpoint un-recognized.

### ISSUE THREAD

**Issue by thomasobrien99** [aws-amplify/amplify-js#1347]
Thank you in advance for any assistance you can offer. I've been working more on Android, but having this issue in iOS as well.

Followed the docs here: 
https://aws-amplify.github.io/amplify-js/media/push_notifications_setup.html#configure-your-app

and here: https://aws-amplify.github.io/amplify-js/media/analytics_guide

Configuring this way:
```
import Amplify from 'aws-amplify';
import PushNotification from '@aws-amplify/pushnotification';
import awsExports from '../../aws-exports';

// import Analytics from '@aws-amplify/analytics';
// Analytics.configure(awsExports);

Amplify.configure(awsExports);
PushNotification.configure(awsExports);
```

I also tried configuring just the Analytics module (rather than the whole Amplify export), and just the @amplify-core export, but neither seemed to make a difference. **The docs are unclear about which of these configuration methods is current.** 

And despite what seems like successful logs: (?)

{[DEBUG] 54:31.80 Amplify - amplify config: {…}}
 [DEBUG] 54:31.92 I18n - configure I18n
 [DEBUG] 54:31.92 I18n - create I18n instance
{[DEBUG] 54:31.93 I18n: undefined}
 [DEBUG] 54:31.94 AnalyticsClass - configure Analytics
{[DEBUG] 54:31.94 Parser - parse config: Array(3)}
{[DEBUG] 54:31.94 DeviceInfo: Array(2)}
{[DEBUG] 54:31.96 AWSPinpointProvider - configure Analytics: {…}}
{[DEBUG] 54:31.97 Analytics - on hub capsule analytics: {…}}
{[DEBUG] 54:31.98 AnalyticsClass - current configuration: {…}}
 [DEBUG] 54:31.98 AuthClass - configure Auth
{[DEBUG] 54:31.98 Parser - parse config: Array(3)}
{[DEBUG] 54:31.100 Analytics - on hub capsule auth: {…}}
 [DEBUG] 54:31.100 AnalyticsClass - configure Analytics
 [DEBUG] 54:31.103 Credentials - getting credentials
 [DEBUG] 54:31.103 Credentials - picking up credentials
 [DEBUG] 54:31.104 Credentials - getting new cred promise
 [DEBUG] 54:31.105 Credentials - checking if credentials exists and not expired
 [DEBUG] 54:31.106 Credentials - need to get a new credential or refresh the existing one
 [DEBUG] 54:31.106 AuthClass - Getting current user credentials
{[DEBUG] 54:31.107 AuthClass - failed to get or parse item aws-amplify-federatedInfo: SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at AuthCla…}
 [DEBUG] 54:31.109 AuthClass - Getting current session
 [DEBUG] 54:31.111 Storage - configure called
 [DEBUG] 54:31.112 StorageClass - configure Storage
 [DEBUG] 54:31.113 StorageClass - Do not have bucket yet
 [DEBUG] 54:31.113 StorageClass - configure Storage
 [DEBUG] 54:31.113 StorageClass - Do not have bucket yet
{[DEBUG] 54:31.114 API - configure API: {…}}
 [DEBUG] 54:31.114 API - create API instance
{[DEBUG] 54:31.115 RestClient - API Options: {…}}
{[DEBUG] 54:31.116 PubSub - configure PubSub: {…}}
{[DEBUG] 54:31.116 Interactions - configure Interactions: {…}}
 [DEBUG] 54:31.584 Credentials - getting credentials
 [DEBUG] 54:31.584 Credentials - picking up credentials
 [DEBUG] 54:31.585 Credentials - getting old cred promise
{[DEBUG] 54:31.588 AuthClass - getting session failed: "No userPool"}
 [DEBUG] 54:31.589 Credentials - setting credentials for guest
{[DEBUG] 54:31.598 Notification - update endpoint in push notification: "eSOEKtwoOqQ:APA91bHt_hkCbbbEfhT3n8bS7mbsK2sL1H00ER…iKko7ADegtW9GRB0taXvXwF1Xd7rlyWaV9fvQPwn9-I3EI79A"}
1e7a7412-57c3-4f1f-9…-a5e8c6fce656:61351 in app registration eSOEKtwoOqQ:APA91bHt_hkCbbbEfhT3n8bS7mbsK2sL1H00ERhE4pw_z_rxu7Dcae9i9g4acOIlek5p0HNDBQmd8puF1qBLIAGYk2zZdizzmZ5fVjp5SE6zmHIgeiKko7ADegtW9GRB0taXvXwF1Xd7rlyWaV9fvQPwn9-I3EI79A
{[DEBUG] 54:31.625 Notification - update endpoint in push notification: "eSOEKtwoOqQ:APA91bHt_hkCbbbEfhT3n8bS7mbsK2sL1H00ER…iKko7ADegtW9GRB0taXvXwF1Xd7rlyWaV9fvQPwn9-I3EI79A"}
1e7a7412-57c3-4f1f-9…-a5e8c6fce656:61351 in app registration eSOEKtwoOqQ:APA91bHt_hkCbbbEfhT3n8bS7mbsK2sL1H00ERhE4pw_z_rxu7Dcae9i9g4acOIlek5p0HNDBQmd8puF1qBLIAGYk2zZdizzmZ5fVjp5SE6zmHIgeiKko7ADegtW9GRB0taXvXwF1Xd7rlyWaV9fvQPwn9-I3EI79A
{[DEBUG] 54:32.339 Credentials - Load credentials successfully: CognitoIdentityCredentials}
{[DEBUG] 54:32.340 AWSPinpointProvider - set credentials for analytics: CognitoIdentityCredentials}
{[DEBUG] 54:32.341 AWSPinpointProvider - set credentials for analytics: CognitoIdentityCredentials}
21e7a7412-57c3-4f1f-9…a5e8c6fce656:325212 Get item: key is AWSPinpoint_54ffba5acbdb4dfab2d287e233ded215 with options undefined
{[DEBUG] 54:43.892 AWSPinpointProvider - endpointId from cache: Array(3)}
 [DEBUG] 54:43.893 AWSPinpointProvider - init clients
{[DEBUG] 54:43.895 AWSPinpointProvider - init clients with credentials: {…}}
"[DEBUG] 54:43.903 AWSPinpointProvider - updateEndpoint with params: ": {…}}
{[DEBUG] 54:43.922 AWSPinpointProvider - endpointId from cache: Array(3)}
 [DEBUG] 54:43.923 AWSPinpointProvider - init clients
 [DEBUG] 54:43.924 AWSPinpointProvider - no change for aws credentials, directly return from init
 [DEBUG] 54:43.924 AWSPinpointProvider - record session start
{[DEBUG] 54:44.301 AWSPinpointProvider - updateEndpoint success: {…}}
"[DEBUG] 54:44.533 AWSPinpointProvider - record event success. ": {…}}

**No endpoints are registered in the Pinpoint console. Nothing is targetable.**

Using : 
  "@aws-amplify/analytics": "^1.0.3",
  "@aws-amplify/pushnotification": "^1.0.3",
  "aws-amplify": "^1.0.4",
  "aws-amplify-react-native": "^1.0.4"

And buildscript dependencies
  'classpath 'com.android.tools.build:gradle:2.3.2' // --> 2.2.3 as suggested in the docs doesn't appear to work with '@aws-amplify/pushnotification'
  'classpath 'com.google.gms:google-services:3.2.0'

I am not sure if something could have changed, because this was working for me before. The app is getting registered in Firebase, and I can see some analytics there.

**Comment by goodryanboy** [comment]
what version did you use when you got it working?

**Comment by goodryanboy** [comment]
I solve this by adding Pinpoint policy in the roles of the Cognito,, hope it helps you

**Comment by goodryanboy** [comment]
``

> I got the same issue, my logs also seems successful but no endpoint targetable , also added Pinpoint policy to Cognito Identity Pool with no luck

can you send your code?

**Comment by pmd30011991** [comment]
@goodryanboy : Actually I just upgrade the aws-amplify to 1.1.4 then solved THanks

**Comment by powerful23** [comment]
@thomasobrien99 I am going to close this issue. Feel free to reopen if you still have this issue.
