### ISSUE TITLE
All signed errors using RestClient are returned as 403 - Missing Authentication Token

### ISSUE THREAD

**Issue by mikecann** [aws-amplify/amplify-js#1348]
I just spent the last few hours getting to the bottom of this and im pretty sure its not intentional.

*Do you want to request a feature or report a bug?*

Bug

*What is the current behavior?*

If you use any `API.get`, `API.post` or any one of the functions to call a lambda while authenticated *and* that lambda then errors with an error such as a 503, then RestClient defaults to retrying the lambda but unsigned this time. 

This results in every single error being turned into a 403 - Missing Authentication Token error when it should be 503 or whatever the lambda actually threw during the signed request.

The error is around [these lines](https://github.com/aws-amplify/amplify-js/blob/master/packages/api/src/RestClient.ts#L125-L131) in RestClient:

```
// Signing the request in case there credentials are available
        return Credentials.get()
            .then(credentials => this._signed({ ...params, ...extraParams }, credentials, isAllResponse))
            .catch(err => {
                logger.debug('No credentials available, the request will be unsigned');
                return this._request(params, isAllResponse);
            });
```

Note above how its going to ALWAYS perform the this._request call if the _signed call fails, thus swallowing the original error. 

Im pretty sure this isnt intended?

BTW this is using aws-amplify@1.0.4

**Comment by elorzafe** [comment]
related to #1341

**Comment by mikecann** [comment]
@elorzafe okay thanks, good to know that its not just me then.
