### ISSUE TITLE
UserAttributes Limits global or per user?

### ISSUE THREAD

**Issue by BHesseldieck** [aws-amplify/amplify-js#1349]
Do you want to request a feature or report a bug?
Question

What is the current understanding?
Referring to https://docs.aws.amazon.com/pinpoint/latest/developerguide/limits.html#limits-increase is my understanding that you can have 40 different user attributes globally and 50 values per attribute. Unfortunately is the scope of the values not clear to me. Getting this right is very important since changing it in the future is almost impossible.

Lets take an example:

I want to track the interests of my users, but every user can input individual interests. So my code would look like this, except the interests are provided via input: 

```
Analytics.updateEndpoint({
    UserAttributes: {
      language: ['en'],
      interests: ['diving', 'eating', 'surfing'],
    }
  });

```
So if I have 1000 Users I easily get more than 50 different interests. So the question is if the limit is applied to the length of the array, meaning 50 different values per user:

```
Analytics.updateEndpoint({
    UserAttributes: {
      language: ['en'],
      events: [ Array of max. 50 Elements ], // Every User can input 50 individual answers/interests here
    }
  });
```

or globally, meaning my 1000 users can have max. 50 different interests in total? 
I use the interests as a tool to target push notifications with aws pinpoint to specific user groups.

Thank you for your help!

Best,
Ben

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

React Native: 0.55.4
aws-amplify: 1.0.2

**Comment by sammartinez** [comment]
@BHesseldieck Apologizes for the late response, I have asked the Pinpoint team on this and will let you know what they say on this once I have an answer for ya.

**Comment by sammartinez** [comment]
From talking to Pinpoint on this question, Limits are per user level and not global. Closing this issue. If you have any further questions on Pinpoint, please feel free to reach out to them on [AWS Forums](https://forums.aws.amazon.com/tags/pinpoint)
