### ISSUE TITLE
Clockskew handling does not work in Rest API calls

### ISSUE THREAD

**Issue by severi** [aws-amplify/amplify-js#13493]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

REST API

### Amplify Version

v6

### Amplify Categories

api

### Backend

None

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 1.89 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
    Yarn: 4.2.2 - ~/.nvm/versions/node/v18.20.2/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
  Browsers:
    Chrome: 125.0.6422.142
    Safari: 17.2.1
  npmGlobalPackages:
    corepack: 0.25.2
    npm: 10.5.0

```

</details>

### Describe the bug

The clockskew handling seems to be broken at the moment (or non existent?). In my setup I get a "NetworkError" with the following response header "X-Amzn-Errortype: InvalidSignatureException" when doing an API call towards an API Gateway (served via a custom domain + https which I assume causes the Cloudfront error?)

The used "isClockSkewError" does not recognize the clocksew correctly
https://github1s.com/aws-amplify/amplify-js/blob/main/packages/core/src/clients/middleware/retry/isClockSkewError.ts#L23-L24

I realized there is another "isClockSkew" function that seems to have a bit better logic for this:

There is another isClockSkew function in https://github1s.com/aws-amplify/amplify-js/blob/main/packages/core/src/Signer/DateUtils.ts#L82

However this does not really as help even if the retry logic would be fixed (tried this manually) the retryed requests will still fail i.e. I assume the clock skew is not fixed in the retryed requests either

How can a clock skew scenario be fixed? I'd imagine this should be something that would be automatically handled by the framework

### Expected behavior

Clockskew should be automatically fixed and API request should succeed

### Reproduction steps

Change the clock on the computer to 1 hour prior the actual time and try to utilize Amplify to do a Rest API request

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello, @severi 👋 and thank you for opening this issue.  Can you share the contents of your `package.json`? This looks related to #9281 and could potentially have the same root cause.  We'll investigate this further and reproduce on our side.

**Comment by jimblanc** [comment]
Hello @severi So the `InvalidSignatureException` is handled by the library as seen here: https://github.com/aws-amplify/amplify-js/blob/main/packages/core/src/clients/middleware/retry/isClockSkewError.ts#L7

If the library encounters this error in REST API, it should retry the request automatically with the clock skew corrected. I confirmed that this mechanism was working as expected in Amplify JS 6.3.6. Are you observing that the automatic retry request is not happening?

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!

**Comment by severi** [comment]
sorry for the delayed answer, for some reason the notifications got buried in my mailbox.

This issue ended up being caused by our ApiGateway configuration as explained in here <https://github.com/aws-amplify/amplify-js/issues/6494#issuecomment-982221646>

so not an amplify issue after all :)
