### ISSUE TITLE
getCurrentUser return {username: undefined, userId: undefined } after successful login with cognito hosted UI

### ISSUE THREAD

**Issue by jreyero12** [aws-amplify/amplify-js#13500]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Not applicable

### Amplify Version

v6.3.6

### Amplify Categories

auth

### Backend

None

### Environment information

<details>

```
# Put output below this line
```

</details>

### Describe the bug

getCurrentUser return {username: undefined, userId: undefined } after successful login with cognito hosted UI using the example of official documentation https://docs.amplify.aws/gen1/react/build-a-backend/auth/add-social-provider/
In the browser I receive the tokens after login I can see them in the network tab of the console but amplify ignores them.

### Expected behavior

Get user and userID

### Reproduction steps

1. call signInWithRedirect
2. login in cognito hosted UI
3.  print getCurrentUser result is {username: undefined, userId: undefined } 

### Code Snippet

```javascript
Amplify.configure({
  Auth: {
    Cognito: {
      userPoolId: 'us-east-1_xxxxxxxxxx',
      userPoolClientId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      signUpVerificationMethod: 'code',
      loginWith: {
        oauth: {
          domain: 'auth.xxxxxx.com',
          scopes: [
            'aws.cognito.signin.user.admin'
          ],
          redirectSignIn: [
            "http://localhost:3000"
          ],
          redirectSignOut: [
            "http://localhost:3000"
          ],
          responseType: 'code'
        }
      }
    }
  }
});

function App() {
  const [user, setUser] = useState<AuthUser | null>(null);
  const [error, setError] = useState<unknown>(null);
  const [customState, setCustomState] = useState<string | null>(null);
 

  useEffect(() => {
    const unsubscribe = Hub.listen("auth", ({ payload }) => {
      switch (payload.event) {
        case "signInWithRedirect":
          getUser();
          break;
        case "signInWithRedirect_failure":
          setError("An error has occurred during the Oauth flow.");
          break;
        case "customOAuthState":
          setCustomState(payload.data);
          break;
      }
    });

    return unsubscribe;
  }, []);

  const getUser = async (): Promise<void> => {
    try {
      const currentUser = await getCurrentUser();
      setUser(currentUser);
      console.log(currentUser)
    } catch (error) {
      console.error(error);
    }
  };
  return (
    <div className="App">
      <button onClick={() => signInWithRedirect()}>Login</button>
      <button onClick={() => signOut()}>SignOut</button>
      <div>{user?.username}</div>
    </div>
  );
}
```

### Log output

<details>

```
{username: undefined, userId: undefined }

```

</details>

**Comment by israx** [comment]
Hello @jreyero12. Sorry to hear you are experiencing issues with the library. 

Is the only issue happing with `getCurrentUser` ? Are you able to call other Auth APIs after you authenticate? e.g `fetchAuthSession`

**Comment by jreyero12** [comment]
fetchAuthSession does not work, I can't get the tokens using the amplify library.

**Comment by israx** [comment]
It appears that authentication is not successful, resulting in the failure of `fetchAuthSession` and `getCurrentUser`. 

Are you able to get any hub events at all ? also try to add a forward slash (`/`) at the end of your redirects, e.g. 
```
redirectSignIn: [
            "http://localhost:3000/"
          ],
          redirectSignOut: [
            "http://localhost:3000/"
          ]
```

**Comment by jreyero12** [comment]
I will try to set the / later
Hub auth event is executed and payload.event value is signInWithRedirect

**Comment by jreyero12** [comment]
I have added in the cognito allowed urls configuration http://localhost:3000/ with the / I have added the / in my code and it doesn't work.
The authentication if successful I can see the tokens in the console but amplify ignores them.
![imagen](https://github.com/aws-amplify/amplify-js/assets/173051903/a9bb14a0-4fd1-4424-94ee-d3a2934075b6)

**Comment by israx** [comment]
You need to add additional scopes in your OAuth config. This will allow the resource server (Cognito) to send additional payload in your id/access token.  

```
loginWith: {
        oauth: {
          domain: 'auth.xxxxxx.com',
          scopes: [
             'aws.cognito.signin.user.admin',
             'openid',
             'profile',
             'email',  // Set this value only if you are signing in with email or have it as required attribute 
             'phone' // Set this value only if you are signing in with phone number or have it as required attribute 
          ],
        }
     }
```

**Comment by jreyero12** [comment]
Thanks, it worked when I added
`scopes: [
            'aws.cognito.signin.user.admin',
            'openid',
            'profile'
          ]`
