### ISSUE TITLE
Please describe minor change of currentAuthenticatedUser

### ISSUE THREAD

**Issue by andrew-aladev** [aws-amplify/amplify-js#1350]
This task is a request for @powerful23. Please be careful when trying to change something in core modules [like this](https://github.com/aws-amplify/amplify-js/commit/a3f91f60d1c8efcadb9818f346330e22c87570b9#diff-1cf5b10c87e919f81d5f1ea503f15074).

I can give a few steps to understand what I am talking about:

1. `currentAuthenticatedUser` throws `no current user`.
2. Open amazon panel and create new user. It's status becomes `FORCE_CHANGE_PASSWORD`.
3. Process `Auth.signIn` and `Auth.completeNewPassword` for this user. It's status becomes `CONFIRMED`.
4. `currentAuthenticatedUser` returns current user data.
5. Open amazon panel and press `reset password` for user. It's status becomes `RESET_REQUIRED`.
6. `currentAuthenticatedUser` throws good error: `{code: "PasswordResetRequiredException", name: "PasswordResetRequiredException", message: "Password reset required for the user"}`.

Yesterday we had to use `currentUserPoolUser`, because wrapper was wrong.

Please fix `rej('getting preferred mfa failed: ' + err);` in the same way and the cover it with unit tests. Please provide detailed information in changelog that some functions become able to bypass errors properly. Thank you.

**Comment by powerful23** [comment]
@andrew-aladev thanks for your feedback. I am really sorry about the mistake I made. Will definitely pay attention to avoid making those bad changes again. To be safe for now I will just revert those changes in this pr.
