### ISSUE TITLE
"Max number of 100 subscriptions reached" after frequent "subscribe" and "unsubscribe" actions?

### ISSUE THREAD

**Issue by mayucoisobe** [aws-amplify/amplify-js#13507]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

GraphQL API

### Amplify Version

Older than v5

### Amplify Categories

api

### Backend

None

### Environment information

<details>

```
# Put output below this line

  System:
    OS: macOS 13.6（22G120）
    CPU: Apple M1
    Memory: 8 GB / 32.00 GB
    Shell: zsh 5.9  - /bin/zsh
  Binaries:
    Node: v16.20.2 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/node_modules/.bin/yarn
    npm: 8.19.4 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 112.0.2
    Safari: 16.3
  npmPackages:
   "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^12.1.5",
    "@testing-library/react-hooks": "^8.0.1",
    "@testing-library/user-event": "^14.4.3",
    "@types/classnames": "^2.2.11",
    "@types/clipboard": "^2.0.1",
    "@types/draftjs-to-html": "^0.8.0",
    "@types/file-saver": "^2.0.5",
    "@types/html-to-draftjs": "^1.4.0",
    "@types/jest": "^28.1.1",
    "@types/lodash-es": "^4.17.5",
    "@types/mocha": "^9.1.0",
    "@types/node": "^17.0.23",
    "@types/papaparse": "^5.3.1",
    "@types/react": "^17.0.47",
    "@types/react-dom": "^17.0.17",
    "@types/react-draft-wysiwyg": "^1.13.0",
    "@types/react-image-crop": "^8.1.3",
    "@types/react-redux": "^7.1.9",
    "@types/react-router-dom": "^5.1.5",
    "@types/react-router-hash-link": "^2.4.5",
    "@types/sanitize-html": "^2.3.2",
    "@types/selenium-webdriver": "^4.0.18",
    "@types/uuid": "^8.3.0",
    "@typescript-eslint/eslint-plugin": "^4.14.0",
    "@typescript-eslint/parser": "^4.14.0",
    "aws-amplify": "^3.0.18",
    "chromedriver": "^104.0.0",
    "eslint": "^7.18.0",
    "eslint-config-prettier": "^7.2.0",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-jest": "^24.1.3",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-react": "^7.22.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "eslint-plugin-unused-imports": "^2.0.0",
    "husky": "^4.3.8",
    "lint-staged": "^10.5.3",
    "mocha": "^9.2.2",
    "mutationobserver-shim": "^0.3.7",
    "prettier": "^2.2.1",
    "react-chartjs-2": "^4.2.0",
    "react-test-renderer": "16.13.1",
    "redux-devtools": "^3.5.0",
    "reflect-metadata": "^0.1.13",
    "sass": "^1.60.0",
    "sass-loader": "^13.2.2",
    "selenium-webdriver": "^4.1.1",
    "ts-node": "^10.7.0"

```

</details>

### Describe the bug

I am encountering frequent errors stating "Max number of 100 subscriptions reached" after adding new pages and features to an existing service.

I understand that this error occurs because the subscription limit is exceeded, and I am aware that it is possible to request a service limit increase from the AppSync service team.

However, my concern is that the current implementation seems to be unnecessarily creating subscriptions. Here are the logs and data obtained from CloudWatch metrics (total / each 1min).
The number of registered subscriptions is **only 6**.

<img width="612" alt="スクリーンショット 0006-06-19 0 02 26" src="https://github.com/aws-amplify/amplify-js/assets/121940353/396514bb-a92a-404a-8fbe-f002d936170d">
<img width="326" alt="スクリーンショット 0006-06-19 0 44 03" src="https://github.com/aws-amplify/amplify-js/assets/121940353/96a71a86-4578-47a3-a823-dc802f3e1758">

As I understand, a subscription does not need to be recreated every time data is updated. In the current implementation, subscriptions are frequently being subscribed and unsubscribed, which may not be the best practice (or possibly an anti-pattern?). I would appreciate any guidance on this.

By removing onDate from the dependency array in the following code, the unnecessary creation of subscriptions is eliminated (though it leads to another error...).
I would like to confirm if my understanding is correct.

### Expected behavior

I would like to refactor the code to prevent errors and implement it following best practices. Since the developer who created this code is no longer available and there is no documentation.
Any advice would be greatly appreciated, thank you.

### Reproduction steps

- use react 17
- create more pages and functions
- I did NOT create any other new subscriptions this time(use present subscriptions)

### Code Snippet

```javascript
import { useCallback, useEffect } from 'react'
import { API } from 'aws-amplify'
import { Observable } from 'zen-observable-ts'
import { gqlOp, GqlSubRes } from '../utils/gql'


export const useSubscribe = <T>(
  sbBody: string,
  sbName: string,
  filterKey: string,
  filterVal: string | undefined,
  onData: (data: T) => void,
  onError?: () => void
) => {
  const makeSb = useCallback(
    (filterVal: string) => {
      const observer = API.graphql(gqlOp(sbBody, { [filterKey]: filterVal })) as Observable<object>
      const subscription = observer.subscribe({
        next: (value: GqlSubRes<typeof sbName, T>) => {
          const data = value.value.data[sbName] as T
          if (data) {
            onData(data)
          }
        },
        error: (e) => {
          console.log(e)
        },
      })
      return subscription
    },
    Before: [filterKey, onData, onError, sbBody, sbName]
    After: [filterKey, onError, sbBody, sbName] ※Remove `onData` from the dependency array　
  )

  useEffect(() => {
    if (!filterVal) return
    const sb = makeSubscription(filterVal)
    return () => {
      sb.unsubscribe()
    }
  }, [filterVal, makeSb])
}

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @mayucoisobe 👋 thanks for raising this issue. Without knowing the other business requirements of your application, I can try answering the questions asked on the description of this issue:

> 1. Is it necessary to recreate subscriptions when updating data ? Assuming a specific teamId is passed as an argument and remains unchanged during the connection?

No, it is generally not necessary to recreate subscriptions when updating data, as long as the subscription query and filter conditions remain unchanged.

> Is there a problem with the current implementation where subscriptions are always released/created?

The `makeSb` function is re-created whenever the `onData` function, or prop, changes (e.g., due to a component re-render). This means that the previous subscription is unsubscribed, and a new one is created every time `onData` changes, which can lead to unnecessary subscriptions and potential performance issues.

Simply removing the `onData` function from the dependency array may result in a [stale closure](https://javascript.plainenglish.io/stale-closures-in-react-afb0dda37f0b#:~:text=A%20stale%20closure%20occurs%20when,irrelevant%20in%20the%20current%20context.) which might explain the next error. Moving the subscription logic to the useEffect might help prevent this. In general, it's not a good practice to use functions as props or in dependency arrays because they will always be different on render unless they are wrapped in `useCallback` and I'm not sure if `onData` or `onError` are wrapped as such from the components they are passed from.

So yeah, try moving the subscription logic to the useEffect instead of in a useCallback or make sure that any function props are wrapped in a `useCallback` so they don't trigger re-renders unless their own dependencies change. And, if you don't expect any filter arguments to change, maybe just create a one-off subscription without the use of this hook.

Hopefully that helps!

**Comment by mayucoisobe** [comment]
Hi @chrisbonifacio 👋 thanks so much for your quick reply. You've been very helpful!
I am going to create a one-off 6-subscriptions with useEffect cause the present code seem to be complicated and difficult to make sure all function props or in dependency arrays are wrapped in a `useCallback`(also considering component re-render).

And here, I have another quiestion, regard to schema.
If the return value type is the same as below `TeamMember`, would it better to merge them into one?

``` Currnet

type Subscription {
  onUpdateTeamMember(teamId: ID!): TeamMember @aws_subscribe(mutations: ["updateTeamMember"])
  onDeleteTeamMember(teamId: ID!): TeamMember @aws_subscribe(mutations: ["deleteTeamMember"])
}

```

``` After

type Subscription {
  onChangeTeamMember(teamId: ID!): TeamMember @aws_subscribe(mutations: ["updateTeamMember", "deleteTeamMember"])
}

```

**Comment by chrisbonifacio** [comment]
Hi @mayucoisobe I think it makes sense to separate the subscriptions into different "events" to be able to differentiate between operations.

**Comment by mayucoisobe** [comment]
Hi @chrisbonifacio Thanks again for your kindness reply.
As you mentioned, it makes sense to separate the subscriptions into different "events", thanks and noted.

Finally I've got success to mitigate the subscription number by create a each 6-subscription with useEffect instead of useCallback (custom hook).

It would have taken much longer without your advice!! thank you!

**Comment by chrisbonifacio** [comment]
@mayucoisobe Happy to help 😄 Thank you for the update, glad to know you're unblocked!
