### ISSUE TITLE
GEN2 - Unable to query with sorting

### ISSUE THREAD

**Issue by grfortun** [aws-amplify/amplify-js#13527]
### Environment information

```plain text
System:
  OS: macOS 14.5
  CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  Memory: 178.72 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.13.0 - ~/.nvm/versions/node/v20.13.0/bin/node
  Yarn: undefined - undefined
  npm: 10.5.2 - ~/.nvm/versions/node/v20.13.0/bin/npm
  pnpm: 9.3.0 - ~/.nvm/versions/node/v20.13.0/bin/pnpm
NPM Packages:
  @aws-amplify/backend: 1.0.3
  @aws-amplify/backend-cli: 0.16.0
  aws-amplify: 6.3.6
  aws-cdk: 2.145.0
  aws-cdk-lib: 2.145.0
  typescript: 5.4.5
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

I am query with sorting by date but facing issues with using the `sortDirection` property. Following the Gen 2 documentation:
[+] https://docs.amplify.aws/react/build-a-backend/data/data-modeling/secondary-index/

### Schema:
```
const schema = a.schema({
  Todo: a
    .model({
      content: a.string(),
      accountRepresentativeId: a.id().required(),
      responseTime: a.string(),
    }).authorization(allow => [allow.owner()])
    .secondaryIndexes((index) => [
      index("accountRepresentativeId")
        .name("repByDate")
        .queryField("listByDate")
        .sortKeys(["responseTime"]),
    ])
});

export type Schema = ClientSchema<typeof schema>;
```
### Query:

```
const {
      data,
      errors
    } = await client.models.Todo.listByDate({
      accountRepresentativeId: '1',
      sortDirection: 'ASC'
    })
```

### Error:
When running my application the query works fine and sorts the data accordingly but I am unable to build my application as I am faced with the following error:
```
Type error: Object literal may only specify known properties, and 'sortDirection' does not exist in type 'IndexQueryInput<{ Todo: ClientModel<..., SchemaMetadata<ModelSchema<{ types: { Todo: ModelType<SetTypeSubArg<SetTypeSubArg<{ fields: { name: ModelField<Nullable<string>, never, undefined>; phoneNumber: ModelField<Nullable<string>, never, undefined>; accountRepresentativeId: ModelField<...>; responseTime: ModelField<...'.

  24 |     } = await client.models.Todo.listByDate({
  25 |       accountRepresentativeId: '1',
> 26 |       sortDirection: 'ASC'
     |       ^
  27 |       
  28 |     
  29 |     })
  ```

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!

**Comment by anishniroula1** [comment]
@david-mcafee When ever I create a new secondary indexes or update secondary indexes, it erases the data from Database. Is that suppose to happen?

this is my schema:
```
Favourite: a.model({
    id: a.id(),
    userId: a.id().required(),
    createdAt: a.string().required(),
    professionalUserId: a.id(),
    businessId: a.id(),
    user: a.belongsTo('User', 'userId'),
    professionalUser: a.belongsTo('ProfessionalUser', 'professionalUserId'),
    business: a.belongsTo('Business', 'businessId'),
  }).authorization((allow) => [allow.authenticated()]).secondaryIndexes((index) => [
        index("userId").queryField("userFavouriteList").sortKeys(["createdAt", "businessId"]),
```

**Comment by chrisbonifacio** [comment]
> @david-mcafee When ever I create a new secondary indexes or update secondary indexes, it erases the data from Database. Is that suppose to happen?
> 
> 
> 
> this is my schema:
> 
> ```
> 
> Favourite: a.model({
> 
>     id: a.id(),
> 
>     userId: a.id().required(),
> 
>     createdAt: a.string().required(),
> 
>     professionalUserId: a.id(),
> 
>     businessId: a.id(),
> 
>     user: a.belongsTo('User', 'userId'),
> 
>     professionalUser: a.belongsTo('ProfessionalUser', 'professionalUserId'),
> 
>     business: a.belongsTo('Business', 'businessId'),
> 
>   }).authorization((allow) => [allow.authenticated()]).secondaryIndexes((index) => [
> 
>         index("userId").queryField("userFavouriteList").sortKeys(["createdAt", "businessId"]),
> 
> ```

Yes, that is expected behavior for sandbox environments. Those changes are destructive.

**Comment by anishniroula1** [comment]
thanks for the response and clarification. I was worried this might happen in prod also.

**Comment by Arjay0004** [comment]
@david-mcafee Is there a way I can query sort keys with multiple begins_with ? I know its possible with raw dynamo db 

Here is my model
```
PageMember: a
      .model({
        pageId: a.id().required(),
        userId: a.id().required(),
        page: a.belongsTo("Page", "pageId"),
        user: a.belongsTo("UserProfile", "userId"),
        role: a.enum(["Admin", "Follower", "Moderator"]),
      })
      .secondaryIndexes((index) => [
        index("pageId").sortKeys(["role", "userId"]).queryField("pageUsers"),
        index("userId").sortKeys(["role", "pageId"]).queryField("userPages"),
      ])
```

and I need a query that looks something like this
```
await cookieBasedClient.models.PageMember.userPages(
    {
      userId: user.userId,
      rolePageId : {
           beginsWith : {
                 or : ["Admin", "Moderator"]
           }
      }
    })
```

I hope my question makes sense.

**Comment by dlamon1** [comment]
Hey Amplify team ! It would be extremely helpful to have information like this in documentation somewhere. It took me well over an hour with multiple google searches and llm searches to find this information. Intenseness does not show the desired arguments without an object typed, and this is a second object, so it ends up being very very hidden.
