### ISSUE TITLE
Access denied when enabling S3 server side kms encryption

### ISSUE THREAD

**Issue by MainAero** [aws-amplify/amplify-js#1352]
When I enable server side encryption with s3, my Storage.put request are failing with access denied.
Is server side encryption supported?

**Comment by elorzafe** [comment]
@MainAero server side encryption with s3 is on our backlog right now.

**Comment by rudyhadoux** [comment]
Hi, is it an Angular project ?

**Comment by rudyhadoux** [comment]
It works for me for S3 objects with AES-256 KMS.

**Comment by jordanranz** [comment]
Seems a solution has been merged. Going to close this issue.

Please reopen if you have any related questions or concerns.
