### ISSUE TITLE
Subscribe is not working in Nuxt 3 (aws amplify Gen2)

### ISSUE THREAD

**Issue by jewells07** [aws-amplify/amplify-js#13535]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

GraphQL API

### Amplify Version

v6

### Amplify Categories

api

### Backend

Amplify Gen 2 (Preview)

### Environment information

<details>

```
# Put output below this line



```

</details>

### Describe the bug

I'm trying to get the on-create data with amplify gen subscribe functionality. but it seems it is not working.

### Expected behavior

onCreate or any other subscription works on Gen 2.

### Reproduction steps

Add onCreate subscription in onMounted.

### Code Snippet

I have followed this steps to get **`$Amplify`** from useNuxtApp() (https://docs.amplify.aws/gen1/vue/build-a-backend/server-side-rendering/nuxt/#implement-01amplifyapisclientts)
```javascript
// Put your code below this line.
onMounted(() => {
  $Amplify.GraphQL.client.models.Todo.onCreate({
    filter: {
      userId: {
        eq: user.value.id,
      },
    },
    authMode: 'userPool',
  }).subscribe({
    next: (data: any) => console.log(data),
    error: (error: any) => console.warn(error),
  });
});

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @jewells07 👋 thanks for raising this issue.

Can you provide some more details around how the subscription is not working?

Are you seeing any errors messages from the subscription's `error` callback's console log?

You can also check the network requests and search for `ws` to find the subscription and check the messages. You might be getting an Unauthorized error or other from AppSync.

Lastly, can you also share the schema for the affected model and any related models so that we can attempt to reproduce the issue?

**Comment by veerendrapatel** [comment]
Hi,
I also face same issue with - When I hit mutation, there is nothing in console. I can just see WS call in network tab. no errors in console.
 "aws-amplify": "6",
"nuxt": "3.10.3",
`const createSub = $amplifyClient
    .graphql({
      query: `
        subscription MySubscription {
          onNotifiedUser(
            input: {
              ppEventId: "stova-demo"
              userUId: "e4bcb413-6579-41ce-8059-f477e626ef3d"
            }
          ) {
            payload
            payloadType
            ppEventId
            userUId
          }
        }
      `,
    })
    // @ts-ignore
    .subscribe({
      next: (data: any) => console.log(data),
      error: (error: any) => console.warn(error),
    });`

**Comment by chrisbonifacio** [comment]
Hi @veerendrapatel As far as I can tell, the subscription shared in the screenshot is not the one established by the Amplify library. It seems the subscription was not established. The one shared is probably the nuxt websocket for hot reloads.

Are you sure that the code is being executed on the client side?

**Comment by jewells07** [comment]
It just console log one time when we call them in mounted. no error in console log

**Comment by veerendrapatel** [comment]
`onMounted(async () => {
  const { $amplifyClient } = useNuxtApp();
  console.log($amplifyClient);  //  amplifyClient is object returned by generateClient()
  const createSub = $amplifyClient
    .graphql({
      query: `
        subscription MySubscription {
          onNotifiedUser(
            input: {
              ppEventId: "stova-demo"
              userUId: "e4bcb413-6579-41ce-8059-f477e626ef3d"
            }
          ) {
            payload
            payloadType
            ppEventId
            userUId
          }
        }
      `,
    })
    // @ts-ignore
    .subscribe({
      next: (data: any) => console.log(data),
      error: (error: any) => console.warn(error),
    });

  console.log(createSub);
});
`
@chrisbonifacio please find  console.log($amplifyClient); and   console.log(createSub); SS
<img width="978" alt="Screenshot 2024-06-29 at 10 45 33 PM" src="https://github.com/aws-amplify/amplify-js/assets/7859851/71558c3e-e5e0-4cd2-a606-e70ddf1a8837">

**Comment by veerendrapatel** [comment]
@chrisbonifacio I got subscription working. It was failing due to Auth token.
Now only issue remain is - I have to use // @ts-ignore when I call .subscribe.
Property 'subscribe' does not exist on type 'UnknownGraphQLResponse'.
  Property 'subscribe' does not exist on type 'Promise<GraphQLResult<any>>'.ts-plugin(2339)
Can you guide me how can I get rid of this TS error?
Thanks

**Comment by jewells07** [comment]
It works for me too. My issue was the real-time data problem with modeling relationships ([Here](https://github.com/aws-amplify/amplify-category-api/issues/2686)).

**Comment by veerendrapatel** [comment]
using <GraphQLSubscription<myType>> that typescript issue also resolved.
