### ISSUE TITLE
Amplify V6 build error with subscribe method

### ISSUE THREAD

**Issue by lingomksr** [aws-amplify/amplify-js#13532]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

GraphQL API

### Amplify Version

v6

### Amplify Categories

api

### Backend

CDK

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I am trying to migrate from V5 to V6.  I am Just following the same from https://docs.amplify.aws/gen1/react/build-a-backend/graphqlapi/subscribe-data/ (V6). 

I am just trying to use same method
```
import { generateClient } from 'aws-amplify/api';
import * as subscriptions from './graphql/subscriptions';

const client = generateClient();

// Subscribe to creation of Todo
const createSub = client
  .graphql({ query: subscriptions.onCreateTodo })
  .subscribe({
    next: ({ data }) => console.log(data),
    error: (error) => console.warn(error)
  });

// Subscribe to update of Todo
const updateSub = client
  .graphql({ query: subscriptions.onUpdateTodo })
  .subscribe({
    next: ({ data }) => console.log(data),
    error: (error) => console.warn(error)
  });

// Subscribe to deletion of Todo
const deleteSub = client
  .graphql({ query: subscriptions.onDeleteTodo })
  .subscribe({
    next: ({ data }) => console.log(data),
    error: (error) => console.warn(error)
  });

// Stop receiving data updates from the subscription
createSub.unsubscribe();
updateSub.unsubscribe();
deleteSub.unsubscribe();
```

But I am getting build error like 

```
TS2339: Property 'subscribe' does not exist on type 'UnknownGraphQLResponse'.
  Property 'subscribe' does not exist on type 'Promise<GraphQLResult<any>>'.
```
I tried to change the subscription method with any  return type it fixed the build error. But the subscription is not working 

```
// Subscribe to creation of Todo
const createSub = (client
  .graphql({ query: subscriptions.onCreateTodo }) as any)
  .subscribe({
    next: ({ data }) => console.log(data),
    error: (error) => console.warn(error)
  });
```

### Expected behavior

It should not throw build error and subscription should work as like v5

### Reproduction steps

https://docs.amplify.aws/gen1/react/build-a-backend/graphqlapi/subscribe-data/

try same code as mentioned in the document

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @lingomksr thanks for raising this issue.

Can you try deleting your node_modules folder and package-lock.json file, then re-install your dependencies? Please make sure your amplify packages are fully up to date.

It might also help to restart the TS server. This past week I have run into several instances in my IDE (VSCode) where types were not behaving as expected and I had to restart my TS server for it to work again.

If none of these work, please share your package.json file so that we can try to reproduce the behavior.

**Comment by lingomksr** [comment]
Hi @chrisbonifacio ,
Thanks for your response. I just deleted `node-modules` and` package-lock.json`. Ans also restarted TS server.  Nothing works for me :(

I just created new application and installed amplify package. But still facing same issues.
 Here is the `package.json` of my new application


`{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
`

**Comment by chrisbonifacio** [comment]
@lingomksr can you try upgrading to the latest version of the Amplify CLI and re-generating the graphql statements by running the `amplify codegen` and see if that resolves the issue.

If that doesn't help, then please share the current subscriptions being used in the `graphql/subscriptions` file.

**Comment by lingomksr** [comment]
Hi @chrisbonifacio,
Thanks your help. After adding the API types, Its works fine now. :)

**Comment by musthafa-pa** [comment]
@chrisbonifacio - Could you please specify from where should I import the below types?
`as GeneratedSubscription<
    APITypes.OnCreateImpressionSubscriptionVariables,
    APITypes.OnCreateImpressionSubscription
  >`
