### ISSUE TITLE
Cant create mock response appsync subscription on V6 

### ISSUE THREAD

**Issue by lingomksr** [aws-amplify/amplify-js#13548]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

GraphQL API

### Amplify Version

v6

### Backend

Other

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I am just upgraded the aws-amplify from v5 to v6. Seems subscriptions working fine. I tried to create mock response for those subscriptions.
In v5 I used spyon to create mock response.
`  jest.spyOn(API, "graphql").mockImplementation(() => {
    return of(mockResponse);
  });`
  
  But in V6 seems API is removed. I am not able to mock those subscription.
  
  

### Expected behavior

Mock should work with v6

### Reproduction steps

create spyon for subscription

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by lingomksr** [comment]
I tried to use like this

 ```
const amplifyClient = generateClient();
    const apiSpy = jest.spyOn(amplifyClient, "graphql").mockImplementation(() => {
      return of(mockResponse);
    });
```

But its not throws type mismatch build error!

**Comment by chrisbonifacio** [comment]
Hi @lingomksr , I would recommend checking out how we test subscriptions in our library:

https://github.com/aws-amplify/amplify-js/tree/main/packages/api-graphql/__tests__

If that doesn't help, I'll try and see if I can get you some feedback and/or guidance on your tests.

Also, can you please share the error message you're seeing?

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
