### ISSUE TITLE
Amplify datastorage adapter not compatible with Ionic/Capacitor

### ISSUE THREAD

**Issue by brucevilo1013** [aws-amplify/amplify-js#13550]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

GraphQL API, DataStore

### Amplify Version

v6

### Amplify Categories

api

### Backend

Amplify CLI

### Environment information

<details>

```
I need to use the amplify storage adapter module (https://www.npmjs.com/package/@aws-amplify/datastore-storage-adapter) to integrate SQLite with my existing Ionic/Capacitor ios app.
I installed the amplify storage adapter and configured datastore, but It doesn't work in Ionic/Capacitor project.

If I configure datastore like below, It throws error "Missing dependency error: not found module react-native-sqlite-storage in @aws-amplify/datastore-storage-adapter" . But this error does not make sense as I don't use in React Native, I just it in Ionic/Capacitor.
```
DataStore.configure({
  storageAdapter: SQLiteAdapter
});
```
```

</details>

### Describe the bug

I need to use the amplify storage adapter module (https://www.npmjs.com/package/@aws-amplify/datastore-storage-adapter) to integrate SQLite with my existing Ionic/Capacitor ios app.
I installed the amplify storage adapter and configured datastore, but It doesn't work in Ionic/Capacitor project.

If I configure datastore like below, It throws error "Missing dependency error: not found module react-native-sqlite-storage in @aws-amplify/datastore-storage-adapter" . But this error does not make sense as I don't use in React Native, I just it in Ionic/Capacitor.
```
DataStore.configure({
  storageAdapter: SQLiteAdapter
});
```
```

### Expected behavior

The storage adapter module (@aws-amplify/datastore-storage-adapter) should be compatible with Ionic/Capacitor project, as It does in React Native.

### Reproduction steps

1. Setup fresh Ionic/Capacitor project
2. Configure amplify with datastore
3. Change default indexed db with SQLite using the storage adapter
4. This simple project throws error "Missing dependency error: not found module react-native-sqlite-storage in @aws-amplify/datastore-storage-adapter"

### Code Snippet

```
import { SQLiteAdapter } from '@aws-amplify/datastore-storage-adapter/SQLiteAdapter';

DataStore.configure({
  storageAdapter: SQLiteAdapter
});

```


### Log output

<details>

```
// Put your logs below this line

```

</details>


### aws-exports.js

_No response_

### Manual configuration

_No response_

### Additional configuration

_No response_

### Mobile Device

_No response_

### Mobile Operating System

_No response_

### Mobile Browser

_No response_

### Mobile Browser Version

_No response_

### Additional information and screenshots

_No response_

**Comment by chrisbonifacio** [comment]
Hi @brucevilo1013 , I'm going to close this issue in favor of the [feature request](https://github.com/aws-amplify/amplify-js/issues/13549). I've referenced it so they're stilled linked. Please track the feature request for any updates.
