### ISSUE TITLE
Type Error on Create Model

### ISSUE THREAD

**Issue by jewells07** [aws-amplify/amplify-js#13557]
### Environment information

```plain text
System:
  OS: Windows 11 10.0.22631
  CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Memory: 419.57 MB / 7.91 GB
Binaries:
  Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
  Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
  npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  pnpm: 9.3.0 - ~\AppData\Local\pnpm\pnpm.EXE
NPM Packages:
  @aws-amplify/backend: 1.0.3
  @aws-amplify/backend-cli: 1.0.4
  aws-amplify: 6.3.6
  aws-cdk: 2.145.0
  aws-cdk-lib: 2.145.0
  typescript: 5.4.5
AWS environment variables:
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
  AWS_STS_REGIONAL_ENDPOINTS = regional
No CDK environment variables
```

### Data packages

```plain text
nuxt-app@ D:\Todo\Todo
├─┬ @aws-amplify/backend-cli@1.0.4
│ └─┬ @aws-amplify/schema-generator@1.0.0
│   └── @aws-amplify/graphql-schema-generator@0.8.6
└─┬ @aws-amplify/backend@1.0.3
  └─┬ @aws-amplify/backend-data@1.0.2
    └── @aws-amplify/data-construct@1.8.5
```

### Description

I am using Nuxt 3, and this code is intended for server-side execution. The utilities were created following the steps outlined in [this AWS Amplify documentation](https://docs.amplify.aws/vue/build-a-backend/server-side-rendering/nuxt/#set-up-amplify-server-context-utility). Note: the link may redirect to Gen 1, but please check for Gen 2.

```javasacript
import { runAmplifyApi, gqlServerClient } from '@/utils/amplifyUtils';

export default defineEventHandler(async (event) => {
  const { data, errors } = await runAmplifyApi(event, (contextSpec: any) =>
    gqlServerClient.models.Todo.create(
      contextSpec,
      {
        content: 'HELLO WORLD',
      },
      { authMode: 'userPool' },
    ),
  );

  const TodoId = data.id;
});
```
In this code **`const TodoId = data.id;`**
It displays the error **`Property 'id' does not exist on type ClientModel<...`**.  Also, it appears that the create function lacks a selectionSet. I believe there should be a selectionSet in the create function.

**Comment by chrisbonifacio** [comment]
Hi @jewells07 👋 thanks for raising this issue. Is your schema the default one generated when creating an amplify app or did you make any changes? If not the default, can you share the schema?

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
