### ISSUE TITLE
Accessing awsAmplify-Vue remotely

### ISSUE THREAD

**Issue by rojagit** [aws-amplify/amplify-js#1357]
Do you want to request a feature or report a bug?
bug

What is the current behavior?
Can access app om local, not on remote within LAN, even after changing port.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.
Just the awsAmplify-Vue starter pack found at https://github.com/aws-samples/aws-amplify-vue

What is the expected behavior?
Should be able to access remotely, Vanilla appSync-react starter works fine from remote.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
Latest as of the starter pack, Windows/Vivaldi

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by haverchuck** [comment]
@rojagit Thanks for reporting this.  We are doing some evaluation of this sample app.

**Comment by haverchuck** [comment]
Closing this issue for now, but referencing it in #1344 so that these related issues are consolidated and so that we tackle them all when we look at the vue-cli 3.0 sample app.
