### ISSUE TITLE
I have created a profile model and I have done amplify push but I keep getting "profile model is not defined" and I don't know how to fix please help.

### ISSUE THREAD

**Issue by Jinyoung3** [aws-amplify/amplify-js#13603]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

GraphQL API

### Amplify Version

v6

### Backend

Amplify Gen 2 (Preview)

### Environment information

<details>

```
# Put output below this line


```

</details>
...

### Describe the bug

I use npx expo run:ios and run on an iphone simulator and when I click on profile button and click edit profile I get profile model is not defined and no information is being saved. I don't really know what I'm doing as I am new to aws amplify so please help me and tell me what I'm doing wrong.  I posted link to github repo below so you can just do git clone and the url

### Expected behavior

just says Profile model is not defined correctly or Profile model is not defined or update method is not available..

### Reproduction steps

...

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

you can run https://github.com/Jinyoung3/awsman.git to clone my repo and run it on your device. amplify/data/resource has model, type.ts has type. I run by doing npx expo run:ios

**Comment by chrisbonifacio** [comment]
Hi @Jinyoung3 👋 thanks for raising this issue.

After looking through your repo, it seems you're generating a client in different places, including the editProfile.ts file and I noticed one also in the amplify/backend/data folder. 

I would recommend creating a util folder outside in the root directory of your project where you generate it once and export it where needed.

Give that a try and let me know if it helps.

**Comment by Jinyoung3** [comment]
should I move the amplify/backend/data/resource.ts into util folder in root directory and should I delete all other codes where I generate client?

**Comment by chrisbonifacio** [comment]
Hi @Jinyoung3 👋 

It seems you opened another [issue](https://github.com/aws-amplify/amplify-js/issues/13626) recently. Are you still experiencing this particular issue or were you able to get unblocked and are only experiencing the more recent issue?

Also, the link to the repo seems to redirect to a 404 and I can't find a react or amplify project among your public repositories.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
