### ISSUE TITLE
POST https://cognito-idp.us-XXXX-X.amazonaws.com/ [400]

### ISSUE THREAD

**Issue by aliza-khu** [aws-amplify/amplify-js#13617]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Version

v6

### Amplify Categories

auth

### Backend

None

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I have set a configuration regarding about refresh token expiring after one hour. But the user is getting logout within 30 to 40 minutes after the ideal state. This issue is only happening to Android users

### Expected behavior

User should logout after an hour.

### Reproduction steps

- Open app
- Authenticate the user.
- After successfully logging in keep it ideal.
- Later after 30 to 40 Minutes try to call the app by opening the app.
- User logged out with POST https://cognito-idp.us-XXXX-X.amazonaws.com/ [400].
- Also window.LOG_LEVEL = 'DEBUG'; is not working.

### Code Snippet

```javascript
// Put your code below this line.
await fetchAuthSession().then(async data => {
    if (data && data.tokens === undefined && data.userSub === undefined) {
      return Promise.reject('logout user');
    }

    const { accessToken } = data.tokens ?? {};

    const updatedToken = accessToken?.toString() ?? '';
    await getAuthToken().then(
      async currentToken => currentToken !== updatedToken && (await setAuthToken(updatedToken))
    );
  });
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

```
class MyStorage implements KeyValueStorageInterface {
     async setItem(key: string, value: string): Promise<void> {
     .....
     }
     async  getItem(key: string): Promise<string | null> {
     .....
     }
     async removeItem(key: string): Promise<void> {
     .....
     }
     async clear(): Promise<void> {
     .....
     }
}

const authConfig = {
  Cognito: {
    // Amazon Cognito User Pool ID
    userPoolId: AWS_USERPOOLID,
    // Amazon Cognito Web Client ID (26-char alphanumeric string)
    userPoolClientId: AWS_USERPOOLWEBCLIENTID,
    loginWith: {
      oauth: {
        responseType: AWS_RESPONSETYPE,
      },
    },
  },
};

Amplify.configure({
  Auth: authConfig,
});
cognitoUserPoolsTokenProvider.setKeyValueStorage(new MyStorage());
```

### Mobile Device

Samsung or Pixel

**Comment by aliza-khu** [comment]
@cwomack,
- The reason behind using **KeyValueStorageInterface** is Privacy as we are using a keychain for storing token-related info.
- Yes, Ideal that you consider it as the user logged in and essentially keep them signed for a while(around 30 minutes to 45 minutes) or the app closes down.
- As mentioned due to window.LOG_LEVEL = 'DEBUG'; not working. I am not able to log all exceptions or errors due to which I have only POST https://cognito-idp.us-XXXX-X.amazonaws.com/ [400] as the last and only thread.
- Also one more query for you: When the user refresh token expires I call the fetchAuthSession() method in which I find tokens and userSub as undefined based on which I am considering the user logged out as this is the only way I can identify. Please share if there is any other way to identify the refresh token expire. I don't find the same situation in the doc if exist please share the link.

Thank you.

**Comment by cwomack** [comment]
@aliza-khu, thanks for the additional information.  The 400 error you're getting back from Cognito should happen if there's a token that being persisted, but possibly ineffective/mismatched to the user session.  The expected behavior would be that we'd get a new refreshToken every time the user signs in (clearing the previous one) that lasts for a fixed timeframe.  

Can you clarify how you're handling any clearing/removal of the initial tokens with your custom value store? I'm wondering if the original token is being persisted from the first sign in, but then when the user signs in again... that first token isn't getting cleared and causing the errors when Auth API's are called.

**Comment by cwomack** [comment]
@aliza-khu, just wanted to ping you again to check in and see if you saw the above comment and if you were still experiencing this issue.  Let us know if there's further assistance needed!

**Comment by aliza-khu** [comment]
@cwomack, With the latest version on AWS-Amplify. I am not facing any such kind of issue now. I will let you know if anything comes up.
