### ISSUE TITLE
[bug] android: Push notifications headless task not allowed

### ISSUE THREAD

**Issue by enzzoperez** [aws-amplify/amplify-js#13625]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Push Notifications

### Amplify Version

v6

### Amplify Categories

notifications

### Backend

None

### Environment information

<details>

```
# Put output below this line

System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 52.27 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    Watchman: 2024.06.17.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 126.1.67.134
    Safari: 17.4.1
  npmPackages:
    @amplitude/analytics-react-native: ~0.4.7 => 0.4.11
    @aws-amplify/react-native: ^1.1.1 => 1.1.3
    @aws-amplify/rtn-push-notification: ~1.2.30 => 1.2.31
    @babel/core: ^7.20.0 => 7.24.9
    @babel/preset-env: ^7.20.0 => 7.24.8
    @babel/runtime: ^7.20.0 => 7.24.8
    @react-native-async-storage/async-storage: ~1.17.9 => 1.17.12
    aws-amplify: ~6.3.8 => 6.3.8
```

</details>

### Describe the bug

Hi, 
Im trying to run a notifications handler in a terminated app, but Im getting the follow error in logcat:

>Something went wrong while starting headless task: Not allowed to start service Intent { cmp=my-app-id/com.amazonaws.amplify.rtnpushnotification.PushNotificationHeadlessTaskService (has extras) }: app is in background uid UidRecord{31d9af5 u0a4 RCVR idle change:uncached procs:0 seq(0,0,0)}

the handlers in iOS (with a terminated app) work well, here in android the notification is received but the handlers not running.. something idea what happen? Is there some extra step for this?

### Expected behavior

Same behavior that iOS.. in a terminated app receive a notification, show the notification banner and run headless handler, in this case a simple console.log function.

I've tried with emulators and physical device and get the same error

### Reproduction steps

1. install app
2. configure aws notifications
3. run app
4. send notification form pinpoint console

### Code Snippet

```javascript

import 'react-native-gesture-handler';
import { AppRegistry } from 'react-native';
import App from './src/App';
import { name as appName } from './app.json';
import { Amplify } from 'aws-amplify';
import {
  initializePushNotifications,
  onNotificationReceivedInBackground,
} from 'aws-amplify/push-notifications';
import awsconfig from 'src/aws-exports';

Amplify.configure(awsconfig);

initializePushNotifications();

// Note: This handler does not *need* to be async, but it can be!
const myAsyncNotificationReceivedHandler = notification => {
  console.log('--> MY NOTIFICATION TERMINATED', notification);
};

onNotificationReceivedInBackground(myAsyncNotificationReceivedHandler);

AppRegistry.registerComponent(appName, () => App);
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by HuiSF** [comment]
Hi @enzzoperez Thanks for reporting this issue, can you confirm, which Android version and API level you were testing with?

**Comment by enzzoperez** [comment]
Hi @HuiSF , sure.. Android 12 in physical and 13 (API 33) in virtual device, 

my project has this config in android 

```
ext {
        buildToolsVersion = "34.0.0"
        compileSdkVersion = 34
        targetSdkVersion = 34
        minSdkVersion = 24
        ndkVersion = "26.2.11394342"
        kotlinVersion = "1.8.0"
        kotlin_version = '1.8.0'
        androidXAnnotation = "1.2.0"
        androidXBrowser = "1.3.0"
    }
```

**Comment by saczx** [comment]
Same issue here, headless background handlers doesn't work on Android.

**Comment by HuiSF** [comment]
Hi @enzzoperez @saczx I was able to reproduce this behavior, when sending PN to Android with a `normal` priority. With this priority, data processing is denied hence the headless mode cannot be started.

The Amplify JS [Push Notification documentation](https://docs.amplify.aws/gen1/react-native/build-a-backend/push-notifications/interact-with-notifications/#notification-received-in-background) indicated this:

>Notifications received in a terminated state will be considered low priority by Android unless you increase the priority of the payload by setting the priority to high (you will need to create a Raw Message in Amazon Pinpoint to set this priority).

To define the priority of a Push Notification message, you would need to use the "raw message" with Pinpoint. For example:

```
{
    // ios message configuration
    "APNSMessage": {
        "aps": {
            "alert": ""
        }
    },
    // android message configuration
    "GCMMessage": {
        "priority": "high", // <- specify high priority to start headless mode
        "data": {
            "pinpoint.notification.title": "Message Title",
            "pinpoint.notification.body": "Message body.",
        }
    },
}
```

See this [Pinpoint documentation](https://docs.aws.amazon.com/pinpoint/latest/apireference/apps-application-id-messages.html#apps-application-id-messages-schemas) for detailed schema definition. 

Could you give it a try and confirm whether this meets your requirement?

**Comment by enzzoperez** [comment]
yes, setting priority 'high' worked.. I was read the note about priority but unfortunately couldn't find in docs how to change the that property in raw msg, 

Thanks @HuiSF , I will close the issue
