### ISSUE TITLE
Support ResetPassword to accept verified email address to send OTP code

### ISSUE THREAD

**Issue by mattiLeBlanc** [aws-amplify/amplify-js#13620]
### Is this related to a new or existing framework?

Angular

### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

When offering self service password reset, we are in a non logged in state, however the `resetPassword` function requires a username input. But when I am offering a password reset, I don't want the  user to provide the username, but I let them enter the email address and if registered and verified, we will send a reset link to that address. Because I think most people can't remember usernames, but they can remember email addresses.

So now I have create a lambda to do an admin `searchUserByAttribute` on the email address provided to get the user and then I can request a reset link.

### Describe the solution you'd like

Wouldn't it be easier if we can do this from the frontend with an Amplify Auth call? I don't there is a security risk because you now accept username, so email address should be fine. And only when registered will it send link.

Is this something to consider?
Maybe a verified phone number can also be supported.

### Describe alternatives you've considered

I described using a lambda to do the task currently, which works. It is just more coding.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cwomack** [comment]
Hello, @mattiLeBlanc 👋.  Want to make sure I'm understanding the ask in this issue properly, because you should be able to use the email (see [here](https://docs.amplify.aws/react/build-a-backend/auth/manage-users/manage-passwords/#reset-password)) to reset the password and still get the code to reset.  Are you saying that when calling the `resetPassword` API in this way, you're not getting this expected behavior?

**Comment by mattiLeBlanc** [comment]
@cwomack No, I don't think you understand, maybe I didn't lay it out correctly.

The main issue is you are required to provide a `username` for all these wonderful Amplify Api calls (I love the simplicity now) but I want to offer users only an `email` field to input their verified email address and not a field for their username.
(I could do that of course).
So now I have to send the email to the backend and use a lambda to fetch the username of a verified email value and then do the PW reset from the lambda.

I hope it is more clear now?

**Comment by cwomack** [comment]
@mattiLeBlanc, if the user pool was originally set up with usernames (and no email), then unfortunately you'd need to create a new user pool with `email` as the usernames.  The `signUp` API has "username" that gets passed in, but it can actually be an alias (canonical "username"), email, or phone number for the username (see [here](https://docs.amplify.aws/react/build-a-backend/auth/connect-your-frontend/sign-up/)).  The same thing applies to the `resetPassword` API.  

To make sure we're helping you best, can you just give some more details and context about how you set up Auth with Amplify and the configuration of your user pool?

**Comment by cwomack** [comment]
@mattiLeBlanc, I think this issue highlights some better clarity needed around the `signUp` docs and how we should mention the flexibility of what can be passed in upon initial sign up better.  The docs don't clearly state this.

**Comment by mattiLeBlanc** [comment]
@cwomack darn, you are right. If I add a verified email address to a username, I can login with that email address. That is great.
The only remark I have to make is this error:
```
code: InvalidParameterException
message: Username cannot be of email format, since user pool is configured for email alias.
```
so you can;t make the username an email address and use a verified email address. Then I guess you need a username (bill) and email (bill@bol.com).
So I guess we can close this request.

**Comment by cwomack** [comment]
@mattiLeBlanc, thanks for the follow up and glad you're unblocked from here. I'm going to open a docs issue to make this section of the `signUp` API docs more clear.  We'll close out this issue on the `amplify-js` repo however now that you're cleared up. 

Thank you again for creating this issue, as it will help improve our docs and ensure others don't run into this.
