### ISSUE TITLE
No support for Angular modularized Amplify

### ISSUE THREAD

**Issue by mordka** [aws-amplify/amplify-js#1365]
Do you want to request a feature or report a bug?
bug
What is the current behavior?

```
ng new someName
cd someName
npm install
npm install aws-amplify-angular --save
npm install @aws-amplify/analytics --save
```
Import `AmplifyAngularModule` in `app.module.ts`
```import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import {AmplifyAngularModule} from 'aws-amplify-angular';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AmplifyAngularModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

This app won't compile.

```
ERROR in node_modules/aws-amplify-angular/lib/providers/amplify.service.d.ts(3,86): error TS2307: Cannot find module 'aws-amplify'.
```

I expect to use modularized Amplify in Angular application.
This is mentioned on wiki page, but it doesn't apply to Angular app when helped module from `aws-amplify-angular` is used. https://github.com/aws-amplify/amplify-js/wiki/Amplify-modularization#apply-modularized-amplify-to-other-packages

**Comment by mlabieniec** [comment]
The aws-amplify-angular package will pull in the entire amplify library. You don't need to install aws-amplify modules separately, they are exposed via a service:
https://aws-amplify.github.io/amplify-js/media/angular_guide#using-amplify-service

If you want to use individual modules, you would just import only @aws-amplify modules and NOT use the aws-amplify-angular package. The angular package provides UI components that utilize multiple categories e.g. Storage and Auth, so it includes all the modules in it as deps.

**Comment by haverchuck** [comment]
@mordka Thanks for reporting this issue.  When you import AmplifyService from aws-amplify-angular and include it in the providers array like so...
`
@NgModule({
  ...
  imports: [
    ...
    AmplifyAngularModule
  ],
  ...
  providers: [
    ...
    AmplifyService
  ]
  ...
});`
... what happens?

**Comment by mordka** [comment]
@mlabieniec you were right. aws-amplify-angular should not be imported when using individual modules. 
We can close this.
