### ISSUE TITLE
Auto signin after signup not working

### ISSUE THREAD

**Issue by Ladvace** [aws-amplify/amplify-js#13666]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Version

v6

### Amplify Categories

auth

### Backend

Amplify Gen 2 (Preview)

### Environment information

<details>

```
 System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 175.64 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.13.0 - ~/.nvm/versions/node/v20.13.0/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.0/bin/npm
    pnpm: 9.4.0 - ~/Library/pnpm/pnpm
    bun: 1.1.7 - ~/.bun/bin/bun
    Watchman: 2024.07.15.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 127.0.6533.74
    Safari: 17.5
  npmPackages:
    @aws-amplify/ui-react: ^6.1.14 => 6.1.14
    @headlessui/react: ^2.1.2 => 2.1.2
    @reduxjs/toolkit: ^2.2.6 => 2.2.6
    @tanstack/eslint-plugin-query: ^5.50.0 => 5.50.0
    @tanstack/react-form: ^0.25.2 => 0.25.2
    @tanstack/react-query: ^5.49.2 => 5.49.2
    @tanstack/react-router: ^1.43.6 => 1.43.6
    @tanstack/router-cli: ^1.43.12 => 1.43.12
    @tanstack/router-devtools: ^1.43.6 => 1.43.6
    @tanstack/router-plugin: ^1.43.5 => 1.43.9
    @tanstack/zod-form-adapter: ^0.25.2 => 0.25.2
    @types/react: ^18.3.3 => 18.3.3
    @types/react-dom: ^18.3.0 => 18.3.0
    @typescript-eslint/eslint-plugin: ^7.15.0 => 7.15.0
    @typescript-eslint/parser: ^7.15.0 => 7.15.0
    @vitejs/plugin-react: ^4.3.1 => 4.3.1
    autoprefixer: ^10.4.19 => 10.4.19
    aws-amplify: ^6.4.3 => 6.4.3
    date-fns: ^3.6.0 => 3.6.0
    eslint: ^8.57.0 => 8.57.0
    eslint-plugin-react-hooks: ^4.6.2 => 4.6.2
    eslint-plugin-react-refresh: ^0.4.7 => 0.4.7
    flowbite: ^2.4.1 => 2.4.1
    flowbite-react: ^0.10.1 => 0.10.1
    globals: ^15.8.0 => 15.8.0
    immer: ^10.1.1 => 10.1.1
    postcss: ^8.4.39 => 8.4.39
    react: ^18.3.1 => 18.3.1
    react-dom: ^18.3.1 => 18.3.1
    react-pdf: ^9.1.0 => 9.1.0
    react-redux: ^9.1.2 => 9.1.2
    react-select: ^5.8.0 => 5.8.0
    tailwindcss: ^3.4.4 => 3.4.4
    typescript: ^5.2.2 => 5.5.2
    vite: ^5.3.3 => 5.3.3
    zod: ^3.23.8 => 3.23.8
  npmGlobalPackages:
    @aws-amplify/cli: 12.12.4
    corepack: 0.28.0
    npm: 10.5.2
    pnpm: 9.1.0


```

</details>

### Describe the bug

as in this issue https://github.com/aws-amplify/amplify-js/issues/991, the `autoSignIn` parameters in the signUp function doesn't work, the user doesn't get logged in, this is quite annoying and it makes the library almost unusable for me.

An issue for this already exist but got closed.

### Expected behavior

to sign in after the signup is successful

### Reproduction steps

just sign in

### Code Snippet

```javascript
   const signUpOutput = await signUp({
      username: email,
      password,
      options: {
        userAttributes: {
          email,
        },
        autoSignIn: true,
      },
    });
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by dylan-tabist** [comment]
https://docs.amplify.aws/react/build-a-backend/auth/connect-your-frontend/sign-up/

You'll have to call `await autoSignIn()` if the `signUpOutput.nextStep` is `COMPLETE_AUTO_SIGN_IN`.

Please refer to the documentation that I just shared

**Comment by Ladvace** [comment]
I've already tried it actually and I get the following error:

`AutoSignInException: The autoSignIn flow has not started, or has been cancelled/completed.
    at initialAutoSignIn `
    
    
 I this this is due to the fact that when I want to sign in the user after the signup, the user is not confirmed yet, I would like to sign in the user after the sign up but before the verification step

**Comment by dylan-tabist** [comment]
@Ladvace yes your understanding is correct.

I guess in your case, you might want to consider to use [AdminConfirmSignUp]( https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminConfirmSignUp.html)

**Comment by Ladvace** [comment]
yeah I came across this, is there a way to achieve this via amplify? or is this something that I have to do on the backend?

**Comment by dylan-tabist** [comment]
@Ladvace 

You might want to look into Pre Sign Up lambda trigger. 

https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-sign-up.html#aws-lambda-triggers-pre-registration-example-2

**Comment by Ladvace** [comment]
thanks, I'll check it out

**Comment by cwomack** [comment]
Hello, @Ladvace and thanks for opening this issue.  As @dylan-tabist stated above, the default behavior for a basic auth flow in Amplify will require a user to sign up, get confirmed, then be signed in.  If you're looking to bypass this middle step for a quicker sign up/sign in process for users, then the customizing the pre-sign up lambda can allow for this. 

Thanks @dylan-tabist for proving some community help here!

**Comment by cwomack** [comment]
Actually, wanted to follow up on this with a little more relevant information.  While the [Pre Sign Up Lambda trigger](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-sign-up.html#aws-lambda-triggers-pre-registration-example-2) will work (as referenced in comments above), you can also circumvent paying for that compute cost with this auto-verify policy: 

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cognito.UserPool.html#autoverify

You can use in the following way for a Gen 2 app (it will leverage the L1 Construct): 

```
const { cfnUserPool } = backend.auth.resources.cfnResources

cfnUserPool.autoVerifiedAttributes = ["EMAIL"]
```

Depending on the use case here, you may want to conditionally autoverify (for example if they come from a "verified" domain) which is where that trigger comes in handy.  While all this can be done, also want to be clear that this runs the risk of allowing absolutely anyone into your app as verified/confirmed, but I'm assuming this issue was opened with that understanding already.

**Comment by Ladvace** [comment]
thanks for the answer, I'm gonna try it out

**Comment by cwomack** [comment]
@Ladvace, just wanted to ping you and follow up to see if you had a chance to try this out.  Let us know if you're still blocked here or have further questions.

**Comment by Ladvace** [comment]
Hi, in the end, I opted for an easier solution, I just merged the login and verification steps, after the verification step, I log in the user, It's not 100% optimal but it's the easiest in my case I think

**Comment by yinka0136** [comment]
Hi @cwomack , I have a similar issue. on confirmation I get this response: 

` {
    "isSignUpComplete": true,
    "nextStep": {
        "signUpStep": "COMPLETE_AUTO_SIGN_IN"
    }
}`

 but when I call await autoSignIn(). I get this same error : 
> AutoSignInException: The autoSignIn flow has not started, or has been cancelled/completed.

**Comment by oznekenzo** [comment]
there is hardly any documentation on how to handle the email verification process when the user is sent a link and not a confirmation code. is the link process case also handled by `autoSignIn` ?

**Comment by oznekenzo** [comment]
I am also unsure how I invoke `signUp` so that I get the response `COMPLETE_AUTO_SIGN_IN` and not the `CONFIRM_SIGN_UP` response which I am getting now.

**Comment by oznekenzo** [comment]
there is only one mention of how to implement in the docs and it hardly goes over any implementation details:

```
[Auto sign-in](https://docs.amplify.aws/react/build-a-backend/auth/connect-your-frontend/sign-in/#auto-sign-in)
The autoSignIn API will automatically sign-in a user when it was previously enabled by the signUp API and after any of the following cases has completed:

User confirmed their account with a verification code sent to their phone or email (default option).
User confirmed their account with a verification link sent to their phone or email. In order to enable this option you need to go to the [Amazon Cognito console](https://aws.amazon.com/pm/cognito), look for your userpool, then go to the Messaging tab and enable link mode inside the Verification message option. Finally you need to define the signUpVerificationMethod to link inside the Cognito option of your Auth config.
```

**Comment by yinka0136** [comment]
> I am also unsure how I invoke `signUp` so that I get the response `COMPLETE_AUTO_SIGN_IN` and not the `CONFIRM_SIGN_UP` response which I am getting now (I am passing `autoSignIn: true` under `options` to `signUp`)

After signup with `autoSignIn: true` , you still have to confirm signup. before you get `COMPLETE_AUTO_SIGN_IN`

**Comment by oznekenzo** [comment]
> After signup with `autoSignIn: true` , you still have to confirm signup. before you get `COMPLETE_AUTO_SIGN_IN`

the docs state that this can be returned after `signUp`

```
The signUp API response will include a nextStep property, which can be used to determine if further action is required. It may return the following next steps:

CONFIRM_SIGN_UP - The sign up needs to be confirmed by collecting a code from the user and calling confirmSignUp.
DONE - The sign up process has been fully completed.
COMPLETE_AUTO_SIGN_IN - The sign up process needs to complete by invoking the autoSignIn API.
```

so either the docs or you are wrong :/
appreciate the help

**Comment by yinka0136** [comment]
> > After signup with `autoSignIn: true` , you still have to confirm signup. before you get `COMPLETE_AUTO_SIGN_IN`
> 
> the docs state that this can be returned after `signUp`
> 
> ```
> The signUp API response will include a nextStep property, which can be used to determine if further action is required. It may return the following next steps:
> 
> CONFIRM_SIGN_UP - The sign up needs to be confirmed by collecting a code from the user and calling confirmSignUp.
> DONE - The sign up process has been fully completed.
> COMPLETE_AUTO_SIGN_IN - The sign up process needs to complete by invoking the autoSignIn API.
> ```
> 
> so either the docs or you are wrong :/ appreciate the help

Read this. 

The autoSignIn API will automatically sign-in a user when it was previously enabled by the signUp API and after any of the following cases has completed:

User confirmed their account with a verification code sent to their phone or email (default option).
User confirmed their account with a verification link sent to their phone or email. In order to enable this option you need to go to the [Amazon Cognito console](https://aws.amazon.com/pm/cognito), look for your userpool, then go to the Messaging tab and enable link mode inside the Verification message option. Finally you need to define the signUpVerificationMethod to link inside the Cognito option of your Auth config.

This means you must confirmUser.  keyword `previously enabled by the signUp API and after`

**Comment by oznekenzo** [comment]
I have already read this and quoted it 5 comments above.

`confirmUser` is not a method provided by the library. if you mean `confirmSignUp` then this method requires a confirmation code. again, I am trying to find the appropriate implementation for the `link` sign up verification method.

The quote from the docs mentions defining `signUpVerificationMethod` to `link` inside the Cognito option of my Auth config, although in their docs the only way they've set up their config is by passing the auto generated `amplifyconfiguration.json` file into `Amplify.configure`

```
import amplifyconfig from "./amplifyconfiguration";
Amplify.configure(amplifyconfig);
```

**Comment by oznekenzo** [comment]
Amplify Studio does not seem to support the link way of confirming an email address, simply from judging their provided interface:
<img width="826" alt="Screenshot 2024-08-09 at 3 12 33 PM" src="https://github.com/user-attachments/assets/e346a2e0-f679-4b20-808d-e8bd7b915a32">

however, it is supported in AWS Cognito:
<img width="860" alt="Screenshot 2024-08-09 at 3 13 43 PM" src="https://github.com/user-attachments/assets/537bdc95-d699-43f1-b2b1-6d3cdd746960">

**Comment by israx** [comment]
Hello all. Sorry for any confusion when using the `autoSignIn` API. To create an account during sign-up, Cognito's default behavior requires users to either submit a `confirmation code` or click a `verification link`. Also The `autoSignIn` API is designed to work exclusively on active sessions within single page application contexts. Therefore, it cannot be utilized in the following scenarios:
1. page was refreshed. 
2. API is called on a new tab.


@oznekenzo in order to enable `autoSignIn` with verification link you have to,
1. Enable verification link on your Cognito User Pool— I see you already did it.
2. call `Amplify.configure` as follows:
 ```
const config:ResourcesConfig={
    Auth: {
        Cognito: {
          userPoolId: "xxxxxxxx",
          userPoolClientId: "xxxxxxxxx",
          signUpVerificationMethod:'link'
        },
      },
  };

Amplify.configure(config)
```
3. call `signUp` with `autoSignIn` enabled.
4. click the verification link sent to your email or phone
5. call the `autoSignIn` API

**Comment by oznekenzo** [comment]
@israx awesome - that worked - thank you very very much

**Comment by israx** [comment]
Thanks @oznekenzo for bringing that up. I created a task in our backlog to add specific documentation to address this use case.

**Comment by yinka0136** [comment]
> Hello all. Sorry for any confusion when using the `autoSignIn` API. To create an account during sign-up, Cognito's default behavior requires users to either submit a `confirmation code` or click a `verification link`. Also The `autoSignIn` API is designed to work exclusively on active sessions within single page application contexts. Therefore, it cannot be utilized in the following scenarios:
> 
> 1. page was refreshed.
> 2. API is called on a new tab.
> 
> @oznekenzo in order to enable `autoSignIn` with verification link you have to,
> 
> 1. Enable verification link on your Cognito User Pool— I see you already did it.
> 2. call `Amplify.configure` as follows:
> 
> ```
> const config:ResourcesConfig={
>    Auth: {
>        Cognito: {
>          userPoolId: "xxxxxxxx",
>          userPoolClientId: "xxxxxxxxx",
>          signUpVerificationMethod:'link'
>        },
>      },
>  };
> 
> Amplify.configure(config)
> ```
> 
> 3. call `signUp` with `autoSignIn` enabled.
> 4. click the verification link sent to your email or phone
> 5. call the `autoSignIn` API

Hi @israx  Thank you for your feed back. 
I have a single page application and I am calling the autologin in the same tab I called confirm signup. 

from confirmSignup I get  { "isSignUpComplete": true, "nextStep": { "signUpStep": "COMPLETE_AUTO_SIGN_IN" } }
which means my autosignin was set up correctly.

but when I call await autoSignIn(). I get this same error :

AutoSignInException: The autoSignIn flow has not started, or has been cancelled/completed.

**Comment by israx** [comment]
Hello @yinka0136. Could you please share code snippets about how you are calling the `signUp` and `autoSignIn` API?

**Comment by yinka0136** [comment]
> Hello @yinka0136. Could you please share code snippets about how you are calling the `signUp`, `confirmSignUp` and `autoSignIn` APIs?

@israx  just to clarify before I send the snippet, do you mean that , Signup, confirmSignup and autologin have to be called on the same tab?

**Comment by israx** [comment]
Yes. The 3 APIs should share the same context. You can still call these APIs on the same tab but using different routes. e.g
`/signup` , `/confirm-sign-up` and `/auto-sign-in`

**Comment by yinka0136** [comment]
> Yes. The 3 APIs should share the same context. You can still call these APIs on the same tab but using different routes. e.g `/signup` , `/confirm-sign-up` and `/auto-sign-in`

This is my function to signup. `  signUpUser(user: Partial<AtomickitUser>): Observable<any> {
    return defer(() => from(AmplifyAuth.signUp({
      username: user.email,
      password: user.password,
      options: {
        userAttributes: {
          email: user.email,
          given_name: user.first_name,
          family_name: user.last_name,
          phone_number: user.phone_number,
          'custom:UserType': user.user_type,
          'custom:shopifyBilling': user.shopify_billing ? '1' : '0',
          'custom:UserTrialExpDate': `${moment().add(General.SUBSCRIPTION_TRIAL_PERIOD, 'days').valueOf()}`,
          'custom:currentBizProfileId': '0'
        },
        autoSignIn: true,
      }
    }))
      .pipe(
        catchError(this.handleError('Sign Up User')),
        tap({
          next: () => this.analyticsManagerService.sendEvent(EventTypes.SIGNUP_COMPLETED, {
            name: `${user.first_name} ${user.last_name}`,
            email: user.email
          })
        })
      ));
  }`. I call it in my register component like this `async register(): Promise<void> {
    this.loading = true;
    this.user.user_type = USERTYPES.merchant;
    this.user.shopify_billing = this.isShopifyUser();
    this.authService.signUpUser(this.user)
      .pipe(
        finalize(() => this.loading = false)
      )
      .subscribe({
        next: (res) => {
          this.toastr.success('User signup was successful');
          this.router.navigate([`/user-verification/${encodeURIComponent(this.user.email).replace(/\./g, '%2E')}`]);
        }
      });
  }` 

and when successful it goes to the verification page.

- On the verification page I call `  verifyEmailAddressToken(code: string): void {
    this.verified = undefined;
    this.loading = true;

    this.auth.verifyEmailAddressToken(this.email, code)
      .subscribe({
        next: (res: any) => {
          console.log(res)
          this.loading = false;
          this.verified = true;
          this.analyticsManagerService.sendEvent(EventTypes.EMAIL_VERIFIED, {})
          },
        error: (err) => {
          this.verified = false;
          this.loading = false;
          this.toastr.error(err.message);
        }
      });
  }`. 
which uses  
`  verifyEmailAddressToken(email: string, code: string): Observable<SignUpOutput> {
    return defer(() => from(
      AmplifyAuth.confirmSignUp({ username: email, confirmationCode: code })
    ))
      .pipe(
        catchError(this.redirectUnconfirmedUser({email})),
        catchError(this.conceiveDisabledUser()),
        switchMap(this.checkForSignUpNextSteps(email)),
        filter((shouldContinue) => shouldContinue),
        switchMap(() => this.startNewSession(true)),
        tap({
          next: (user) => this.router.navigateByUrl(this.redirectUrl || '/dashboard'),
          error: () => this.logoutUser()
        }),
        catchError(this.handleError('Verify Email Address', null))
      );
  }` to confirm signup and then if the step is COMPLETE_AUTO_SIGN_IN, I call autoSignIn

**Comment by firliilhami** [comment]
> Hello @yinka0136. Could you please share code snippets about how you are calling the `signUp`, `confirmSignUp` and `autoSignIn` APIs?

Hi @israx I have the same issue, this is my code snippet for testing, for the nextStep. I already get  **COMPLETE_AUTO_SIGN_IN** status but somehow when call autoSignIn() get the error **AutoSignInException: The autoSignIn flow has not started, or has been cancelled/completed.**
`
async function debugAuthFlow() {
  try {
    // Example: Sign Up
    const signUpResult = await signUp({
      username: phone_number,
      password: password,
      options: {
       autoSignIn: {
         authFlowType: "USER_PASSWORD_AUTH",
       },
       userAttributes: {
         phone_number: phone_number,
       },
     },
    });
    console.log('Sign Up Result:', signUpResult);

    rl.question('Enter the confirmation code you received: ', async (confirmationCode) => {
     try {
       console.log("Confirming sign-up...");
       const confirmationResult = await confirmSignUp({
        username: phone_number,
        confirmationCode: confirmationCode,
      });
       console.log("Sign-up confirmed! ", confirmationResult);
       const autoSignInResult = await autoSignIn();
       console.log("Auto sign-in result: ", autoSignInResult);
     } catch (error) {
       console.error("Error confirming sign-up or auto sign-in:", error);
     } finally {
       // Close the readline interface after the input is handled
       rl.close();
     }}) ; 
  } catch (error) {
    console.error('Error in authentication flow:', error);
  }
}
`

**Comment by firliilhami** [comment]
> > Hello @yinka0136. Could you please share code snippets about how you are calling the `signUp`, `confirmSignUp` and `autoSignIn` APIs?
> 
> @israx just to clarify before I send the snippet, do you mean that , Signup, confirmSignup and autologin have to be called on the same tab?

Hi @yinka0136 , do you solve the issue?

**Comment by cwomack** [comment]
@Ladvace, @firliilhami, @yinka0136, and anyone else following this issue/experiencing this, just wanted to follow up here and let you all know that we've created a docs issue (see link below) to try and prevent the confusion captured in this issue with the `autoSignIn()` API from happening further.

Typically, we'll close the `amplify-js` repo issue (keeping it for search-ability rather than transferring it) and open a new issue on the docs repo to track them there.  As such, I'll close out this issue on our repo and point anyone to the `amplify-docs` repo issue [#8018](https://github.com/aws-amplify/docs/issues/8018).

**Comment by 432i** [comment]
> [@israx](https://github.com/israx) [@cwomack](https://github.com/cwomack) Commenting regarding [#13666 (comment)](https://github.com/aws-amplify/amplify-js/issues/13666#issuecomment-2277940594) Need some clarifications
> 
>     * Doesn't autoSignIn work when signUpVerificationMethod is code? According to the docs, it does.
> 
>     * I am unable to make it work with my react native app. The output returned by confirmSignUp =>  nextStep.signUpStep is 'DONE' and not 'COMPLETE_AUTO_SIGN_IN'.

Hello, I think this is not explained very well in the docs but I discovered that if you pass:
```
options: {
          autoSignIn: true,
        }
}
```
to the `signUp` function now instead of returning `DONE` it will return `COMPLETE_AUTO_SIGN_IN`, allowing you to call the `autoSignIn` method. This is how I stopped getting the `AutoSignInException`

I think the documentation needs an update about this

**Comment by richstimson** [comment]
For me, autoSignIn works after signUp unless the user makes an error on sign - e.g. enters an incorrect OTP code. 

I would like sign-up and auto sign-in even if a mistake was made, and they take 2 attempts to enter the code.

For me, a second signin attempt has to be made as signUpStep === "DONE" rather than "COMPLETE_AUTO_SIGN_IN", so a second OTP code is sent - which is really poor UX. 

Can anyone assist?

  ```
const onSignInPressed = async () => {

      const session = await signIn({
        username: email,
        options: {
          authFlowType: "USER_AUTH",
          preferredChallenge: "EMAIL_OTP",
        },
      });

      setSinSession(session);
      setIsOtpSent(true);

}

  const onVerifyOtp = async () => {

     if (nextStepAction === "CONFIRM_SIGN_UP") {
        // Confirm sign up with the OTP received
        console.log("OTP-SUP: Confirming sign up...");
        const { nextStep: supNextStep } = await confirmSignUp({
          username: email,
          confirmationCode: otp,
        });

        console.log("OTP-SUP: ConfirmSignUp nextStep", supNextStep);

        if (supNextStep.signUpStep === "COMPLETE_AUTO_SIGN_IN") {
          // Call `autoSignIn` API to complete the flow
          const { nextStep: autoSignInNextStep } = await autoSignIn();

          if (autoSignInNextStep.signInStep === "DONE") {

            setSupSession(null); // All done
          } else {
            console.log("OTP-: AutoSignIn in not complete", autoSignInNextStep);
          }
        } else if (supNextStep.signUpStep === "DONE") {
           // Auto sign in - not complete - sign in again.
           // Note - a new OTP code is sent.

          const session = await signIn({
            username: email,
            options: {
              authFlowType: "USER_AUTH",
              preferredChallenge: "EMAIL_OTP",
            },
          });
}
```
