### ISSUE TITLE
Adding nonexistant attribute mappings using Cognito CDK configuration breaks Facebook OAuth Social Sign In

### ISSUE THREAD

**Issue by seanimamo** [aws-amplify/amplify-js#13674]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Version

v6

### Amplify Categories

auth

### Backend

CDK

### Environment information

    "aws-cdk-lib": "^2.148.0",
    
    Other environment variables don't matter.

### Describe the bug

When using CDK to specify custom attributes mapping for facebook social sign-in for a cognito userpool using an attribute name that isnt provided by it will result in the federated facebook sign in settings being in an invalid state and will break the attribute mapping which results in silent failures on cognito where attributes from facebook will not be mapped aside from the username attribute. 

It can only be remediated by removing the custom attribute mappings. It's important to note that these custom attributes are ones that facebook doesn't actually provide.

In this example, it is adding a custom mapping for "email_verified" 

### Expected behavior

attributes map as expected.

### Reproduction steps

deploy a congito stack with the snippet provided for federated sign in cdk synth + cdk deploy.

### Code Snippet

```javascript
// Put your code below this line.
    userPool.addClient(userPoolId, {
      userPoolClientName: userPoolId,
      // We would only want a secret if were NOT using a UI to access this user pool.
      generateSecret: false,
      authFlows: {
        adminUserPassword: true,
        userSrp: true,
        userPassword: true,
        custom: true,
      },
      preventUserExistenceErrors: true,
      // Adds basic OAuth config if provided.
      ...(socialSignIn !== undefined && {
        oAuth: {
          flows: {
            authorizationCodeGrant: true,
            implicitCodeGrant: true,
          },
          callbackUrls: socialSignIn.callbackUrls,
          logoutUrls: socialSignIn.logoutUrls,
          // All the basic OAuth scopes gives flexibility while maintaining user privacy.
          scopes: [
            cognito.OAuthScope.COGNITO_ADMIN, // Necessary for social sign in flows.
            cognito.OAuthScope.OPENID,
            cognito.OAuthScope.EMAIL,
            cognito.OAuthScope.PROFILE,
          ],
        },
      }),
    });

 const facebookProvider = new cognito.UserPoolIdentityProviderFacebook(this, id, {
      clientId: facebookOAuthClientId,
      clientSecret: facebookOAuthClientSecret,
      userPool,
      scopes: ["public_profile", "email"],
      attributeMapping: {
        email: cognito.ProviderAttribute.FACEBOOK_EMAIL,
        custom: {
           // @@@ THIS LINE BREAKS FACEBOOK ATTRIBUTE MAPPING @@@
          email_verified: cognito.ProviderAttribute.other("email_verified"),
        },
      },
    });
    // Attach the identity provider to the user pool
    userPool.registerIdentityProvider(facebookProvider);
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello, @seanimamo 👋.  Just to confirm, are you using AWS Amplify in any part of your project?  Or strictly using the AWS CDK (which looks to be the case based on the code provided).  Just want to make sure we've got this issue in the proper repo to help your best! Thanks. 

You should be able to map custom attributes for you user pool if using the Pre-Authentication Lambda trigger, and there's more info on that [here](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-specifying-attribute-mapping.html#cognito-user-pools-specifying-attribute-mapping-console).
