### ISSUE TITLE
Aws Amplify Not Sync with Mongodb, After Db changed its not fetching latest data, always shows 1 step previous!!!

### ISSUE THREAD

**Issue by qasim5611** [aws-amplify/amplify-js#13684]
Ment Stack NextJs Site and its AdminPanel Deployed on AWS Amplify

**Comment by qasim5611** [comment]
[chrisbonifacio](https://github.com/chrisbonifacio) 
Hi Have you understood my problem? I On localhost admin panel and Site fetching the latest records but on Live here Aws Amplify not, I need any solution or the way to see it further
Thanks

**Comment by chrisbonifacio** [comment]
Hi @qasim5611 it seems like you might be running into some sort of caching issue.

Are you setting any custom headers to cache page requests?

https://docs.aws.amazon.com/amplify/latest/userguide/ttl.html

**Comment by qasim5611** [comment]
My customHttp.yml file inside Customheaders Was Empty before:
and I placed an cache content here like:

customHeaders:
  - pattern: /**/*
    headers:
      - key: Cache-Control
        value: no-cache, no-store, must-revalidate
      - key: Pragma
        value: no-cache
      - key: Expires
        value: "0"


And also During Nextjs Api Call inside globalSlice, I include headed cache too

But Still Issue Not Resolved
<img width="950" alt="customheader" src="https://github.com/user-attachments/assets/4f6d93ca-c5a8-428a-ba79-c88e1af32ee9">
<img width="908" alt="Screenshot 2024-08-07 151057" src="https://github.com/user-attachments/assets/33159390-675c-4d6f-82f5-04e14f8d05a2">


Should I need to change my customHttp.yml file content?

**Comment by qasim5611** [comment]
In my LocalHost everything working smoothly,
I am too little bit sure about this AWS Amplify Cache settings needs to be done now.
[chrisbonifacio](https://github.com/chrisbonifacio)

**Comment by qasim5611** [comment]
[chrisbonifacio](https://github.com/chrisbonifacio)

Hy!
My issue have been tresolved by Nextjs 15 updegradation from 14, as in nextjs 15 fetch requests, GET Route Handlers, and client navigations are no longer cached by default

https://nextjs.org/blog/next-15-rc
