### ISSUE TITLE
Modularization - User pool client XXX does not exist.

### ISSUE THREAD

**Issue by iarroyo5** [aws-amplify/amplify-js#1369]
Do you want to request a feature or report a bug?
bug

What is the current behaviour?
I have the following code:

```js
// index.ts

import { setupAuth } from './core/service';

setupAuth();
...
```
```js
// core/service.ts

import { AWSAmplifyAuthOptions, setupAwsAmplifyAuth } from '../libs/auth';
import { config } from './config';

const awsAmplifyConfig: AWSAmplifyAuthOptions = {
  Auth: {
    identityPoolId: config.AWS_IDENTITY_POOL_ID,
    region: config.AWS_REGION,
    userPoolId: config.AWS_USER_POOL_ID,
    userPoolWebClientId: config.AWS_USER_POOL_WEB_CLIENT_ID
  }
};

export const setupAuth = () => {
  setupAwsAmplifyAuth(awsAmplifyConfig);
};
```
```js
// auth-service.ts

import Auth from '@aws-amplify/Auth';
import { AmplifyError, AWSAmplifyAuthOptions } from 'aws-amplify/types';

export const setupAwsAmplifyAuth = (config: AWSAmplifyAuthOptions): void => {
  Auth.configure(config);
};
```
```js
// login.ts

import Auth from '@aws-amplify/Auth';

export const signIn = () => {
  if (!Auth || typeof Auth.signIn !== 'function') {
    throw new Error('No Auth module found, please ensure @aws-amplify/auth is imported');
  } else {
    console.log('Auth-signIn', Auth);
  }

  Auth.signIn()...
}
```
The first issue is that `Auth` has the correct data inside the object

<img width="875" alt="afad" src="https://user-images.githubusercontent.com/5355188/43572001-4b03ea7e-9636-11e8-9461-a1f6991c3580.png">

and it never throws the error `No Auth module found...`, but every time I am trying to `SignIn` the response is `User pool client XXXX does not exist.`

What is the expected behaviour?
Not throw the error.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
`1.0.4`

**Comment by iarroyo5** [comment]
The user pool was recreated due to an update in the CloudFormation stack. This meant the user pool IDs had changed which is why I was unable to communicate with cognito vis Amplify.

**Comment by marcelinhov2** [comment]
How do you solve it? Thanks
