### ISSUE TITLE
type errors when using client.models.mymodel.create

### ISSUE THREAD

**Issue by cookiejest** [aws-amplify/amplify-js#13695]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

GraphQL API

### Amplify Version

v6

### Amplify Categories

function

### Backend

Amplify Gen 2 (Preview)

### Environment information
<img width="480" alt="Screenshot 2024-08-08 at 07 35 25" src="https://github.com/user-attachments/assets/1afaaf07-57cd-4296-b2aa-d6b9458887f8">
<img width="673" alt="Screenshot 2024-08-08 at 07 35 56" src="https://github.com/user-attachments/assets/d7ef50ba-3e65-4864-9e84-d85d67a98b43">

<details>

Type script errors are being generated incorrectly when using the create method from a model generated with amplify v2

```

</details>


### Describe the bug


### Expected behavior

See screenshot. I expect the typescript errors to not be there!


### Reproduction steps

create a simple model through amplify v2. Use typescript. Addec code for example.

### Code Snippet

```javascript
  Run: a
    .model({
      prompt: a.belongsTo('Prompt', 'promptId'),
      promptId: a.id(),
      trigger: a.string(),
      promptContent: a.string(),
      promptName: a.string(),
      promptCron: a.string(),
      runLabel: a.string(),
      startTimestamp: a.timestamp(),
      endTimestamp: a.timestamp(),
      isRunning: a.boolean(),
      accessToken: a.string(),
      messages: a.hasMany('Message', 'runId')
    })



  const createCommand = await client.models.Run.create({
    trigger: 'manual',
    promptId: selectedPrompt.value.id,
    promptName: selectedPrompt.value.name,
    promptContent: selectedPrompt.value.content,
    promptCron: selectedPrompt.value.cron,
    runLabel: runLabel,
    isRunning: false,
    startTimestamp: startEpoc,
    accessToken: session.tokens.accessToken.toString(),
    endTimestamp: null
  })

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @cookiejest can you copy/paste the TS error you're getting when trying to perform `.create()`?

**Comment by david-mcafee** [comment]
@cookiejest - in addition to sharing the full TS error you're getting, can you also please include the full schema found `amplify/data/resource.ts`? Thank you!

**Comment by cookiejest** [comment]
here is the amplify/data/resource.ts 


`import { type ClientSchema, a, defineData } from "@aws-amplify/backend";

const schema = a.schema({
  Prompt: a
    .model({
      content: a.string(),
      name: a.string(),
      cron: a.string(),
      active: a.boolean(),
      runs: a.hasMany('Run', 'promptId'),
      messages: a.hasMany('Message', 'promptId')
    })
    .authorization((allow) => [allow.owner()]),
  Run: a
    .model({
      prompt: a.belongsTo('Prompt', 'promptId'),
      promptId: a.id(),
      trigger: a.string(),
      promptContent: a.string(),
      promptName: a.string(),
      promptCron: a.string(),
      runLabel: a.string(),
      startTimestamp: a.timestamp(),
      endTimestamp: a.timestamp(),
      isRunning: a.boolean(),
      messages: a.hasMany('Message', 'runId')
    })
    .authorization((allow) => [allow.owner()]),
  Message: a
    .model({
      type: a.string(),
      message: a.string(),
      color: a.string(),
      runId: a.id(),
      promptId: a.id(),
      run: a.belongsTo('Run', 'runId'),
      prompt: a.belongsTo('Prompt', 'promptId')
    })
    .authorization((allow) => [allow.owner()])
});


export type Schema = ClientSchema<typeof schema>;

export const data = defineData({
  schema,
  authorizationModes: {
    defaultAuthorizationMode: "userPool"
  },
});`

API client generated:
`import { defineBackend } from '@aws-amplify/backend';
import { auth } from './auth/resource';
import { data } from './data/resource';

/**
 * @see https://docs.amplify.aws/react/build-a-backend/ to add storage, functions, and more
 */
const backend = defineBackend({
  auth,
  data
});
`

**Comment by chrisbonifacio** [comment]
Hi @cookiejest , I was unable to reproduce the issue with the provided schema. Can you provide the versions of `@aws-amplify/backend` and `@aws-amplify/backend-cli` packages you have installed?

I would recommend upgrading if they are not the latest version. You can do so by running the following command:

```sh
npm install @aws-amplify/backend@latest @aws-amplify/backend-cli@latest
```

Then run the following to make sure `@aws-amplify/data-schema` is up to date as well

```sh
npm update @aws-amplify/data-schema
```

**Comment by cookiejest** [comment]
I upgraded now it has gone away. Strange

**Comment by gregoryjscott** [comment]
I'm getting the same error on both `.create()` and `.update()`. I have the latest versions of @aws-amplify/backend, @aws-amplify/backend-cli, and aws-amplify installed.

The client appears to be aware of the `device` and `snapshot` fields.

<img width="885" alt="Screenshot 2024-08-15 at 10 56 06 AM" src="https://github.com/user-attachments/assets/58492ba6-3fa2-48a9-bd34-40d97be9b658">

However, `.create()` and `.update()` are not.

<img width="740" alt="Screenshot 2024-08-15 at 10 56 17 AM" src="https://github.com/user-attachments/assets/7804056c-6e55-454f-a27b-944cc38db744">
<img width="741" alt="Screenshot 2024-08-15 at 10 56 26 AM" src="https://github.com/user-attachments/assets/4f218267-5275-4314-a665-1fd40cc5f447">
<img width="1075" alt="Screenshot 2024-08-15 at 10 56 41 AM" src="https://github.com/user-attachments/assets/fec73c69-b573-4549-9037-0d53850f90c7">

**Comment by gregoryjscott** [comment]
It looks like the project where Amplify is installed must have `strict` set to `true` in its tsconfig.json file. After adding that my compile errors went away.

```
{
  "compilerOptions": {
    "strict": true,
    ...
  },
  ...
}
```

**Comment by cookiejest** [comment]
that didnt fix it for me, im using it within a vue project. Not sure if that is the cause but think not.

**Comment by chrisbonifacio** [comment]
Hi @cookiejest I've been unable to reproduce these type errors on the latest version.

Are you still running into these type errors? If so, have you tried deleting node_modules, package-lock.json, and clean installing your dependencies with the latest versions of the amplify packages in your package.json?

It might help to restart the TS server.

**Comment by tomphan** [comment]
Hi I also facing this. After playing around adding some `secondaryIndexes` and some other `required()` and `default()` options to the schema, now I cannot calling `create` with custom fields, event with default Todo sample:

```
    Todo: a.model({
      content: a.string(),
      isDone: a.boolean(),
    }),    
```


```
Amplify.configure(outputs);
const client = generateClient<Schema>();

              const { errors, data: newTodo } = await client.models.Todo.create({
                content: "My new todo",
                isDone: true,
              });
```

Compiler error output:

> 
> npm run build
> 
> > amplify-vite-react-template@0.0.0 build
> > tsc && vite build
> 
> src/utils/fn.tsx:70:17 - error TS2322: Type 'string' is not assignable to type 'string[]'.
> 
> 70                 content: "My new todo",
>                    ~~~~~~~
> 
>   node_modules/@aws-amplify/data-schema-types/dist/esm/util.d.ts:15:130
>     15 export type Prettify<T> = T extends (...args: infer ArgsType) => any ? (...args: ArgsType) => ReturnType<T> : T extends object ? {
>                                                                                                                                         ~
>     16     [P in keyof T]: Prettify<T[P]>;
>        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     17 } : T;
>        ~
>     The expected type comes from property 'content' which is declared here on type '{ [x: string]: string[]; [x: number]: string[]; id?: string; }'
> 
> src/utils/fn.tsx:71:17 - error TS2322: Type 'boolean' is not assignable to type 'string[]'.
> 
> 71                 isDone: true,
>                    ~~~~~~
> 
>   node_modules/@aws-amplify/data-schema-types/dist/esm/util.d.ts:15:130
>     15 export type Prettify<T> = T extends (...args: infer ArgsType) => any ? (...args: ArgsType) => ReturnType<T> : T extends object ? {
>                                                                                                                                         ~
>     16     [P in keyof T]: Prettify<T[P]>;
>        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     17 } : T;
>        ~
>     The expected type comes from property 'isDone' which is declared here on type '{ [x: string]: string[]; [x: number]: string[]; id?: string; }'
>

**Comment by tomphan** [comment]
> It looks like the project where Amplify is installed must have `strict` set to `true` in its tsconfig.json file. After adding that my compile errors went away.
> 
> ```
> {
>   "compilerOptions": {
>     "strict": true,
>     ...
>   },
>   ...
> }
> ```

Yes, trying `strict` to `true` makes the error went away, however strict mode requires all other variable need to declare to specific type, that costs much effort. So I would prefer to back to not use `strict` mode ==> need to find other solution.

**Comment by tomphan** [comment]
Sorry for sending comment multiple times, but this is for confirming that, removing `"strict": true,` in `tsconfig.json` makes the error. 

To reproduce the issue, just follow the Quickstart sample for Vite (https://docs.amplify.aws/react/start/quickstart/), clone the React Vite Github template, then remove `"strict": true,` in `tsconfig.json`. The error appears.

Please could the team give any hint to bypass the error with `"strict": true,` off? Thx.

**Comment by jtweeks** [comment]
I am having a similar issue, my largest model create shows the correct properties, my newer models show [x: string].  data resource and outputs seem fine.

**Comment by akmalpopalzi98** [comment]
I am not sure whether my issue is related to the ones above but I am having Graphql API type mismatch:

![Image](https://github.com/user-attachments/assets/9045b1ce-d8c9-421c-b91e-97cd4e7f696a)

The error says 'Property listUsersByHandleName does not exist on type. Did you mean listusersByHandleName ?'
This error is odd since the available method on the client.models.users object has 'listUsersByHandleName'

![Image](https://github.com/user-attachments/assets/e007d3e0-747f-4ceb-9aa4-27e3116338f4)

**Comment by bbodien** [comment]
This is still an issue, using Next.js, and `"strict": false` in `tsconfig.json` results in the issue of properties on models being incorrectly typed as arrays, e.g. `myProperty: a.string()` will be typed as `string[]` when calling `create()`. As soon as you set `"strict": true` in `tsconfig.json`, the typescript error disappears.
