### ISSUE TITLE
Set remember device on SignIn?

### ISSUE THREAD

**Issue by Skaronator** [aws-amplify/amplify-js#137]
I'd like that the user can choose if they want to remember their device but it looks like there is currently no way to remember the device on login when you have the user pool set to "Opt In"?

https://github.com/aws/aws-amplify/blob/master/media/authentication_guide.md#sign-in

![image](https://user-images.githubusercontent.com/2886913/34753339-ba559802-f5b7-11e7-931d-eb98d52928fc.png)

**Comment by mlabieniec** [comment]
@Skaronator Are you still having this issue?

**Comment by Sourabhd1164** [comment]
@mlabieniec  I'm still having this issue

**Comment by bjclark13** [comment]
@mlabieniec I see this was removed from the 2.1 milestone? Are there still any plans for implementing this functionality into Amplify?

**Comment by Skaronator** [comment]
Not stale

**Comment by Vivek205** [comment]
#Following. Required option to #remember device during SignIN

**Comment by harrysolovay** [comment]
You're unable to do this from the `signIn` method, but you can do the following:

```ts
const user = await Auth.currentUserPoolUser({bypassCache: true});

await new Promise((resolve, reject) => {
  user.setDeviceStatusRemembered((error, success) => {
    if (error) return reject(error);
    return resolve(success);
  });
});
```

You can also do the same thing to forget the device (but using `forgetDevice` instead of `setDeviceStatusRemembered`).
