### ISSUE TITLE
Add SelectionSets on Mutations

### ISSUE THREAD

**Issue by ChristopherGabba** [aws-amplify/amplify-js#13748]
### Is this related to a new or existing framework?

React Native

### Is this related to a new or existing API?

GraphQL API

### Is this related to another service?

DynamoDB

### Describe the feature you'd like to request

I would like the ability to define selectionSets for mutations as well. Currently the mutation responses return a lot of unneeded data and I'm also getting some TS errors when comparing them to other data structures because I can't define them.

<img width="402" alt="Screenshot 2024-08-23 at 7 36 25 AM" src="https://github.com/user-attachments/assets/ad558b02-c5ea-467b-9c51-76c18fc27bbf">

### Describe the solution you'd like

```typescript
        const response = await client.models.Friendship.create({
          status: FriendStatus.PENDING,
          senderId: userStore.currentUser?.id!,
          receiverId: friend.id,
        },
        {
         selectionSet: friendshipSelectionSet
        })
```

### Describe alternatives you've considered

N/A

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by chrisbonifacio** [comment]
Hey @ChristopherGabba This feature is now supported!

Please upgrade to the latest version of `@aws-amplify/backend` and `@aws-amplify/backend-cli`

**Comment by ChristopherGabba** [comment]
Awesome @chrisbonifacio! Thank you guys very much for knocking this out.
