### ISSUE TITLE
Why no cloud persistence with Vue starter ?

### ISSUE THREAD

**Issue by rojagit** [aws-amplify/amplify-js#1374]
Do you want to request a feature or report a bug?
AWS persistence missing in  https://github.com/aws-samples/aws-amplify-vue

What is the current behavior?
browser cache persistence only
schema all wrong
resources all wrong

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

What is the expected behavior?
Persist in AWS DynoDB - thats what we expect and  signed up for right

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
latest

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by haverchuck** [comment]
@rojagit Thanks for reporting this - I am marking it as a feature request.  It definitely makes sense.  However, I'm also closing the issue and documenting it in #1344 , that way the vue-sample issues are more consolidated.
