### ISSUE TITLE
No upgrade path for custom auth.storage configuration

### ISSUE THREAD

**Issue by jfloodnet** [aws-amplify/amplify-js#13740]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Version

v6

### Amplify Categories

auth

### Backend

None

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

Hi, so I'm going through the upgrade for v5 to v6. Was a lot of work to just get it to the point that I could attempt to run anything.

However, there is no upgrade path for people who used a "custom storage" provider for auth.

Please see the v5 definition for Auth config: https://docs.amplify.aws/gen1/javascript/prev/tools/libraries/configure-categories/ 

![image](https://github.com/user-attachments/assets/09913712-5057-419f-b3df-93088ee71a14)

### Expected behavior

v6 would offer some equivalent method of customising the storage of tokens and attributes

### Reproduction steps

Migrate v5 to v6

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

```
export default {
    Auth: {

        // identityPoolId: 'XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab',

        region: region,

        // identityPoolRegion: 'XX-XXXX-X',

        userPoolId: userPoolId,

        userPoolWebClientId: appClientId,

        identityPoolId: identityPoolId,

        providerKey: `cognito-idp.${region}.amazonaws.com/${userPoolId}`,

        mandatorySignIn: true,

        storage: CustomUserStorage,
    }
}
```

**Comment by jfloodnet** [comment]
If there is an alternative api provided in v6, please provide documentation on how one could migrate their custom storage implementation to it.

**Comment by israx** [comment]
Hey @jfloodnet. Thank you for upgrading to v6. You can provide your own Storage mechanism by implementing the `KeyValueStorageInterface` interface. You can find the `Custom Storage` section in the following [documentation](https://docs.amplify.aws/gen1/react/build-a-backend/auth/manage-user-session/#update-your-token-saving-mechanism)

**Comment by israx** [comment]
Thanks @jfloodnet for bringing this up. I created a task in our backlog to add specific documentation to migrate the use cases of `Amplify.configure` in v5.

**Comment by cwomack** [comment]
@jfloodnet, thanks again for creating this issue.  We'll be tracking the docs improvement within the above linked docs issue [#7981](https://github.com/aws-amplify/docs/issues/7981).  Feel free to follow that for updates on when the docs update gets merged in, but I'll back to this issue with a comment when it's complete as well.
