### ISSUE TITLE
GEN2 Default Sorting Functionality Not Working as Expected

### ISSUE THREAD

**Issue by designbystephen** [aws-amplify/amplify-js#13759]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

GraphQL API, DataStore

### Amplify Version

v6

### Backend

None

### Environment information

<details>

```
# Put output below this line
 System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700K
    Memory: 35.51 GB / 63.75 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    bun: 1.0.27 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (127.0.2651.74)
  npmPackages:
    husky: ^9.1.5 => 9.1.5
    lint-staged: ^15.2.7 => 15.2.9
    prettier: 3.3.3 => 3.3.3 (2.3.2, 2.8.8, 1.19.1)
    typescript: ^5 => 5.5.4 (4.4.4, 4.9.5)
  npmGlobalPackages:
    @aws-amplify/cli: 12.7.0
    yarn: 1.22.19

```

</details>

### Describe the bug

I am finding that currently with my GEN2 implementation, there is no longer any `sortDirection` provided by default. Further, the results for list queries using the AppSync console do not provide sorted results.   

### Expected behavior

A list query should provide basic sort functionality based on generated `id` and `createdAt` attributes. I should see the option for a `sortDirection` option in the AppSync console when testing queries AND I should also see the list results ordered by the `createdAt` attribute. 

### Reproduction steps

1. Typical aws-amplify configuration using Gen2
2. Add a new model to the schema using the provided code snippet 
3. Note the lack of `id` and `createdAt` attributes
4. Add to `backend.ts` module where `defineBackend` is called, as docs indicate
5. Deploy to sandbox using `npx ampx sandbox`
6. Create some new records ( I used the graphql api to do this)
7. Access AppSync via AWS console and test queries for the newly deployed resource in the sandbox environment (`awsAppsyncApiId` in outputs)
8. Error: Observe the lack of sorting based on `createdAt` values should be ordered based on `createdAt` where the most recent record is at the bottom (in ascending order)
9. Error: Observe the lack of `sortDirection` option using a query in the AppSync console 

### Code Snippet

```typescript
// ArticleItem model defined in a module
import { a } from '@aws-amplify/backend';

const schema = {
 ArticleItem: a
    .model({
      title: a.string().required(),
      summary: a.string().required(),
      md5sum: a.string().required(),
      link: a.url().required(),
      image: a.url(),
      source: a.string(),
      tags: a.string().array(),
      publishedDate: a.datetime(),
    })

    .authorization((allow) => [
      // anyone who is authenticated with the app can view the event
      allow.authenticated().to(['read']),

      // owners of the event can modify/delete the event
      allow.owner(),

      // administrators can freely modify events as if they were owners
      allow.groups(['administrator']).to(['read', 'create', 'update', 'delete']),
    ]),
};

export default schema;
```

```typescript
// Schema with models
import { type ClientSchema, a, defineData } from '@aws-amplify/backend';

import ArticleItem from './ArticleItem';

const schema = a.schema({
  ...ArticleItem,
})

export type Schema = ClientSchema<typeof schema>;

export const data = defineData({
  schema,
});
```

These are the results from using the out-of-the-box list query, as I indicated in the bug description I was not able to provide a sortDirection without encountering an error.

Note the order of the list is not ordered by `createdAt`:

```gql
query MyQuery {
  listArticleItems(limit: 100) {
    items {
      id
      createdAt
    }
  }
}
```

```json
{
  "data": {
    "listArticleItems": {
      "items": [
        {
          "id": "d138c9b2-6116-412d-83d3-aa674286bdee",
          "createdAt": "2024-08-27T18:38:24.056Z"
        },
        {
          "id": "001f238c-c9a0-4aeb-8ae8-1314447afcdb",
          "createdAt": "2024-08-27T18:38:24.013Z"
        },
        {
          "id": "eb288751-a96d-47ce-9629-3f6a1a62da9a",
          "createdAt": "2024-08-27T18:38:24.028Z"
        },
        {
          "id": "aa7b5133-88c7-4410-89b6-2fdb70ab6ec2",
          "createdAt": "2024-08-27T18:38:23.995Z"
        },
        {
          "id": "682ea19d-7a92-4fb2-bc55-4ced65e43d30",
          "createdAt": "2024-08-27T18:38:24.012Z"
        },
        {
          "id": "808174ef-b734-4e25-aeba-efd4fa437416",
          "createdAt": "2024-08-27T18:38:24.022Z"
        },
        {
          "id": "3562f6b9-4600-42e0-af74-91fedde13bc6",
          "createdAt": "2024-08-27T18:38:24.030Z"
        },
        {
          "id": "331eb707-eec0-4a7a-9210-55f2738dad67",
          "createdAt": "2024-08-27T18:38:23.986Z"
        },
        {
          "id": "9b1813bb-5788-477a-962c-33efa12782b0",
          "createdAt": "2024-08-27T18:38:24.022Z"
        },
        {
          "id": "cedc8c1a-e92c-4b54-b0a1-8d127b07a23e",
          "createdAt": "2024-08-27T18:38:24.008Z"
        },
        {
          "id": "0e5fe61a-8e65-4c09-8ee0-73e174cff871",
          "createdAt": "2024-08-27T18:38:23.997Z"
        },
        {
          "id": "37113af2-2ac2-4d4a-8a37-37772069df94",
          "createdAt": "2024-08-27T18:38:24.000Z"
        }
      ]
    }
  }
}
```

These are the results from a query using a secondary index of  `source`, specifying the sort index as `publishedDate` and then providing a `sortDirection` of  `DESC`. This is something of a workaround from Amplify Gen 1 and I don't think I should need to do this to accomplish a simple sort based on what I have read and explored via issues.

Note the order of the list is working as I would expect with the "out-of-the-box" query:

```gql
query MyQuery {
  listArticleItemBySourceAndPublishedDate(source: "sourceId", sortDirection: DESC, limit: 100) {
    items {
      publishedDate
      id
    }
  }
}
```

```json
{
  "data": {
    "listArticleItemBySourceAndPublishedDate": {
      "nextToken": null,
      "items": [
        {
          "id": "0e5fe61a-8e65-4c09-8ee0-73e174cff871",
          "publishedDate": "2024-07-28T19:31:33.161Z"
        },
        {
          "id": "aa7b5133-88c7-4410-89b6-2fdb70ab6ec2",
          "publishedDate": "2024-07-28T13:06:52.276Z"
        },
        {
          "id": "3562f6b9-4600-42e0-af74-91fedde13bc6",
          "publishedDate": "2024-07-19T19:07:08.933Z"
        },
        {
          "id": "808174ef-b734-4e25-aeba-efd4fa437416",
          "publishedDate": "2024-07-18T06:27:21.441Z"
        },
        {
          "id": "cedc8c1a-e92c-4b54-b0a1-8d127b07a23e",
          "publishedDate": "2024-07-08T15:48:46.926Z"
        },
        {
          "id": "682ea19d-7a92-4fb2-bc55-4ced65e43d30",
          "publishedDate": "2024-06-21T23:11:21.501Z"
        },
        {
          "id": "331eb707-eec0-4a7a-9210-55f2738dad67",
          "publishedDate": "2024-06-12T13:58:16.498Z"
        },
        {
          "id": "9b1813bb-5788-477a-962c-33efa12782b0",
          "publishedDate": "2024-06-11T05:08:47.501Z"
        },
        {
          "id": "d138c9b2-6116-412d-83d3-aa674286bdee",
          "publishedDate": "2024-06-02T21:21:44.329Z"
        },
        {
          "id": "37113af2-2ac2-4d4a-8a37-37772069df94",
          "publishedDate": "2024-06-01T21:43:58.663Z"
        },
        {
          "id": "eb288751-a96d-47ce-9629-3f6a1a62da9a",
          "publishedDate": "2024-05-19T01:04:55.309Z"
        },
        {
          "id": "001f238c-c9a0-4aeb-8ae8-1314447afcdb",
          "publishedDate": "2024-05-04T02:28:02.790Z"
        }
      ]
    }
  }
}
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @designbystephen 👋 Unfortunately, there is no default sorting functionality unless you use a secondary index with a sort key.

To enable sorting, you can create a global secondary index on one of your fields and then use a field like `createdAt` as the sort key. Here's an example in our docs:

https://docs.amplify.aws/javascript/build-a-backend/data/data-modeling/secondary-index/#add-sort-keys-to-secondary-indexes

modified example for `createdAt`:

```ts
export const schema = a.schema({
  Customer: a
    .model({
      name: a.string(),
      phoneNumber: a.phone(),
      accountRepresentativeId: a.id().required(),
      createdAt: a.datetime().required()
    })
    .secondaryIndexes((index) => [
      index("accountRepresentativeId")
        .sortKeys(["createdAt"]),
    ])
    .authorization(allow => [allow.owner()]),
});
```

**Comment by designbystephen** [comment]
> Hi @designbystephen 👋 Unfortunately, there is no default sorting functionality unless you use a secondary index with a sort key.
> 
> To enable sorting, you can create a global secondary index on one of your fields and then use a field like `createdAt` as the sort key. Here's an example in our docs:
> 
> https://docs.amplify.aws/javascript/build-a-backend/data/data-modeling/secondary-index/#add-sort-keys-to-secondary-indexes
> 
> modified example for `createdAt`:
> 
> ```ts
> export const schema = a.schema({
>   Customer: a
>     .model({
>       name: a.string(),
>       phoneNumber: a.phone(),
>       accountRepresentativeId: a.id().required(),
>       createdAt: a.datetime().required()
>     })
>     .secondaryIndexes((index) => [
>       index("accountRepresentativeId")
>         .sortKeys(["createdAt"]),
>     ])
>     .authorization(allow => [allow.owner()]),
> });
> ```

Thanks for the confirmation and link back to the documentation. This pattern works well for listing data with some type of relationship where that "index" is a known value. Looks like the best approach when you don't have this is still to create a static string attribute and associate it with the `secondaryIndex` definition for that model. 

If anything hopefully someone will find this when searching around.

A bit of feedback: I think it would be nice if the documentation pointed this out a bit more clearly. If you are trying to sort a list then you MUST have a secondaryIndex. It feels like you must know what a secondaryIndex (or GSI) is before you can find the answer in the documentation.

Thanks again for the quick response.
