### ISSUE TITLE
Rest API Calls with Authenticated Users and User Groups

### ISSUE THREAD

**Issue by thomasdavidwang** [aws-amplify/amplify-js#13785]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

REST API

### Amplify Version

v6

### Amplify Categories

api

### Backend

Amplify Gen 2 (Preview)

### Environment information

<details>

```
# Put output below this line

System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 4.09 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.0.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.5.1 - /opt/homebrew/bin/npm
    bun: 1.1.6 - /opt/homebrew/bin/bun
    Watchman: 2024.04.22.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 128.0.6613.119
    Safari: 17.5

```

</details>

### Describe the bug

I created a Rest API using Amplify Gen 2 and AWS CDK according to the documentation, using IAM as an authorizer. When attempting to call this API from the frontend, the API calls were being made with the Group Role instead of the Authenticated User Role. As a result, we were getting 403 errors that stated "The client is not authorized to perform this operation."

### Expected behavior

Successful API Requests

### Reproduction steps

1. Create an amplify gen 2 backend, with user groups enabled in the Auth, and a Rest API. 
2. Send a Post request using AWS Amplify from the front end, after a user associated with a user group signs in. 

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hey, @thomasdavidwang 👋.  Can you clarify which docs you were following to set up the group roles and access?  Also, does your `amplify/backend.ts` mimic [this section](https://docs.amplify.aws/react/build-a-backend/add-aws-services/rest-api/set-up-rest-api/#:~:text=unauthenticated%20IAM%20roles-,backend.auth.resources.authenticatedUserIamRole.attachInlinePolicy(,)%3B,-//%20add%20outputs%20to) of the docs with the associated policies?

**Comment by thomasdavidwang** [comment]
Hi Chris, thanks for looking into this!

The user groups were created according to: https://docs.amplify.aws/react/build-a-backend/auth/concepts/user-groups/

Appropriate users are automatically put into a user group using a post-confirmation trigger: https://docs.amplify.aws/react/build-a-backend/functions/examples/add-user-to-group/

And our backend does attach the relevant policies to the authenticated and unauthenticated roles, as described in the docs you shared. 

However, what we were seeing from the API Gateway access logs is that the API calls were being made using a User Group Role, which did not have the appropriate policies, and not the authenticated user role.

**Comment by cwomack** [comment]
@thomasdavidwang, thanks for the follow up and additional context.  This looks related to another issue in the `amplify-cli` repo [#13916](https://github.com/aws-amplify/amplify-cli/issues/13916).  We're looking into this and will provide an update as soon as we can.

**Comment by cwomack** [comment]
@thomasdavidwang, we're tracking this as a bug on the `amplify-backend` repo within issue [#1771](https://github.com/aws-amplify/amplify-backend/issues/1771) over there.  We'll close this out as a duplicate on the JS side, but please follow that issue for updates on progress.
