### ISSUE TITLE
 "Validation error of type UnknownType: Unknown type AWSTimestamp"

### ISSUE THREAD

**Issue by fistofzen** [aws-amplify/amplify-js#13797]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

GraphQL API

### Amplify Version

v6

### Amplify Categories

api

### Backend

None

### Environment information

  System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.64 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.5.1 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.8.2 - /opt/homebrew/bin/npm
    Watchman: 2024.07.15.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 128.0.6613.120
    Safari: 17.6
  npmPackages:
    @aws-amplify/react-native: ^1.0.28 => 1.1.1 
    @aws-amplify/rtn-web-browser: ^1.0.12 => 1.0.30 
    @azure/core-asynciterator-polyfill: ^1.0.2 => 1.0.2 
    @babel/core: ^7.20.0 => 7.24.6 
    @babel/preset-env: ^7.20.0 => 7.24.6 
    @babel/runtime: ^7.20.0 => 7.24.6 (7.25.6)
    @gorhom/bottom-sheet: ^4.6.3 => 4.6.3 
    @ptomasroos/react-native-multi-slider: ^2.2.2 => 2.2.2 
    @react-native-async-storage/async-storage: ^1.19.5 => 1.23.1 
    @react-native-clipboard/clipboard: ^1.11.1 => 1.14.1 
    @react-native-community/blur: ^4.3.2 => 4.4.0 
    @react-native-community/cli-platform-ios: ^12.0.0 => 12.3.6 (12.3.0)
    @react-native-community/datetimepicker: ^7.5.0 => 7.7.0 
    @react-native-community/netinfo: ^11.1.0 => 11.3.2 
    @react-native-community/progress-view: ^1.3.2 => 1.4.2 
    @react-native-community/slider: ^4.4.1 => 4.5.2 
    @react-native-picker/picker: ^2.7.7 => 2.7.7 
    @react-native/eslint-config: ^0.74.0 => 0.74.83 
    @react-native/metro-config: ^0.73.2 => 0.73.5 
    @react-navigation/bottom-tabs: ^6.5.8 => 6.5.20 
    @react-navigation/drawer: ^6.5.0 => 6.6.15 
    @react-navigation/native: ^6.1.9 => 6.1.17 
    @react-navigation/stack: ^6.3.2 => 6.3.29 
    @stripe/stripe-react-native: ^0.35.0 => 0.35.1 
    @tsconfig/react-native: ^3.0.0 => 3.0.5 
    @twotalltotems/react-native-otp-input: ^1.3.11 => 1.3.11 
    @types/react: ^18.0.24 => 18.3.3 
    @types/react-test-renderer: ^18.0.0 => 18.3.0 
    @wix/blog: ^1.0.275 => 1.0.275 
    @wix/sdk: ^1.12.12 => 1.12.12 
    HelloWorld:  0.0.1 
    aws-amplify: ^6.1.4 => 6.3.4 
    aws-amplify/adapter-core:  undefined ()
    aws-amplify/analytics:  undefined ()
    aws-amplify/analytics/kinesis:  undefined ()
    aws-amplify/analytics/kinesis-firehose:  undefined ()
    aws-amplify/analytics/personalize:  undefined ()
    aws-amplify/analytics/pinpoint:  undefined ()
    aws-amplify/api:  undefined ()
    aws-amplify/api/server:  undefined ()
    aws-amplify/auth:  undefined ()
    aws-amplify/auth/cognito:  undefined ()
    aws-amplify/auth/cognito/server:  undefined ()
    aws-amplify/auth/enable-oauth-listener:  undefined ()
    aws-amplify/auth/server:  undefined ()
    aws-amplify/data:  undefined ()
    aws-amplify/data/server:  undefined ()
    aws-amplify/datastore:  undefined ()
    aws-amplify/in-app-messaging:  undefined ()
    aws-amplify/in-app-messaging/pinpoint:  undefined ()
    aws-amplify/push-notifications:  undefined ()
    aws-amplify/push-notifications/pinpoint:  undefined ()
    aws-amplify/storage:  undefined ()
    aws-amplify/storage/s3:  undefined ()
    aws-amplify/storage/s3/server:  undefined ()
    aws-amplify/storage/server:  undefined ()
    aws-amplify/utils:  undefined ()
    babel-jest: ^29.2.1 => 29.7.0 
    babel-preset-react-app: ^10.0.1 => 10.0.1 
    date-fns: ^3.6.0 => 3.6.0 
    deprecated-react-native-prop-types: ^5.0.0 => 5.0.0 (2.3.0)
    eslint: ^8.19.0 => 8.57.0 
    example:  0.0.1 
    ini: ^4.1.1 => 4.1.3 
    jest: ^29.2.1 => 29.7.0 
    lottie-react-native: ^6.4.0 => 6.7.2 
    metro-react-native-babel-preset: 0.77.0 => 0.77.0 
    moment: ^2.30.1 => 2.30.1 
    native-base: ^3.4.28 => 3.4.28 
    nativewind: ^2.0.11 => 2.0.11 
    prettier: ^3.0.3 => 3.2.5 
    react: 18.2.0 => 18.2.0 (18.3.1)
    react-content-loader: ^6.2.0 => 6.2.1 
    react-content-loader/native:  undefined ()
    react-native: 0.73.2 => 0.73.2 
    react-native-blob-util: ^0.19.9 => 0.19.9 
    react-native-circular-progress-indicator: ^4.4.2 => 4.4.2 
    react-native-corner-video: ^1.0.2 => 1.0.2 
    react-native-countdown-circle-timer: ^3.2.1 => 3.2.1 
    react-native-date-picker: ^5.0.4 => 5.0.4 
    react-native-fast-image: ^8.6.3 => 8.6.3 
    react-native-floating-label-input: ^1.4.3 => 1.4.3 
    react-native-gesture-handler: ^2.8.0 => 2.16.2 
    react-native-get-random-values: ^1.10.0 => 1.11.0 
    react-native-health: ^1.18.0 => 1.18.0 
    react-native-health-connect: ^3.1.0 => 3.1.0 
    react-native-heroicons: ^3.2.0 => 3.2.1 
    react-native-inappbrowser-reborn: ^3.7.0 => 3.7.0 
    react-native-keyboard-aware-scroll-view: ^0.9.5 => 0.9.5 
    react-native-linear-gradient: ^2.6.2 => 2.8.3 
    react-native-loading-spinner-overlay: ^3.0.1 => 3.0.1 
    react-native-logs: ^5.1.0 => 5.1.0 
    react-native-modal: ^13.0.1 => 13.0.1 
    react-native-orientation-locker: ^1.5.0 => 1.7.0 
    react-native-otp-inputs: ^7.4.0 => 7.4.0 
    react-native-otp-textinput: ^1.1.3 => 1.1.5 
    react-native-pager-view: ^6.3.3 => 6.3.3 
    react-native-pdf: ^6.7.5 => 6.7.5 
    react-native-pell-rich-editor: ^1.9.0 => 1.9.0 
    react-native-phone-number-input: ^2.1.0 => 2.1.0 
    react-native-progress: ^5.0.0 => 5.0.1 
    react-native-purchases: 7.4.0-beta.2 => 7.4.0-beta.2 
    react-native-reanimated: ^3.5.4 => 3.11.0 
    react-native-reanimated-carousel: ^3.1.0 => 3.5.1 
    react-native-redash: ^18.1.3 => 18.1.3 
    react-native-render-html: ^6.3.4 => 6.3.4 
    react-native-responsive-dimensions: ^3.1.1 => 3.1.1 
    react-native-responsive-screen: ^1.4.2 => 1.4.2 
    react-native-safe-area-context: ^4.7.4 => 4.10.1 
    react-native-screens: ^3.27.0 => 3.31.1 
    react-native-sound: ^0.11.2 => 0.11.2 
    react-native-sound-player: ^0.13.2 => 0.13.2 
    react-native-styled-text: ^2.0.0 => 2.0.0 
    react-native-svg: ^13.14.0 => 13.14.1 
    react-native-tab-view: ^3.5.2 => 3.5.2 
    react-native-uuid: ^2.0.1 => 2.0.2 
    react-native-vector-icons: ^10.0.2 => 10.1.0 
    react-native-video: ^6.0.0-beta.3 => 6.1.2 
    react-native-webview: ^13.6.2 => 13.10.2 
    react-redux: ^8.0.4 => 8.1.3 
    react-test-renderer: 18.2.0 => 18.2.0 
    redux: ^4.2.0 => 4.2.1 
    redux-thunk: ^2.4.1 => 2.4.2 
    responsive-screen:  0.1.0 
    responsive-screen-orientation-change:  0.1.0 
    responsive-screen-styled-components:  0.1.0 
    rn-sliding-up-panel: ^2.4.6 => 2.4.6 
    styled-components: ^6.1.12 => 6.1.12 
    styled-components/native:  undefined ()
    tailwindcss: 3.3.2 => 3.3.2 
    typescript: 5.2.2 => 5.2.2 
  npmGlobalPackages:
    @aws-amplify/cli: 12.12.4
    yarn: 1.22.22

### Describe the bug

Hello guys,
When I try to add a content from amplify studio I am getting, 

"Validation error of type UnknownType: Unknown type AWSTimestamp".
"Cannot return null for non-nullable type: 'AWSDateTime' within parent 'Equipment'"

Regards.

### Expected behavior

Save the content

### Reproduction steps

go to content
click on an existing item
change it
press save

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello, @fistofzen 👋.  This looks related to issue #12490 where there was a field and query potentially missing from a schema. Can you double check your schema to confirm if this is the case? 

Also, is this a Gen 2 app?

**Comment by chrisbonifacio** [comment]
Hi @fistofzen since this is Amplify Studio related, I checked to see if there might be a similar issue in the `amplify-studio` repo and came across this [issue](https://github.com/aws-amplify/amplify-studio/issues/1111). I'm going to transfer this issue and close as a duplicate. Please track [amplify-studio/1111](https://github.com/aws-amplify/amplify-studio/issues/1111) for updates.
