### ISSUE TITLE
Don't remove additional field types with WithListsFixed

### ISSUE THREAD

**Issue by HikaruTakakura** [aws-amplify/amplify-js#13812]
### Is this related to a new or existing framework?

Next.js

### Is this related to a new or existing API?

GraphQL API

### Describe the feature you'd like to request

Modify `WithListsFixed` to enhance type inference.

The `total` property generated when using `@searchable` will disappear during the type inference process.
I reported same problem [here](https://github.com/aws-amplify/amplify-js/issues/13766) as a bug, but it was closed with inadequate answers, so I started this issue again.
I think type inference, not type annotation, should solve this problem.
Please see that issue for more details.

### Describe the solution you'd like

Change `WithListsFixed` defined [here](https://github.com/aws-amplify/amplify-js/blob/ced891c2e4f6b0f1fdeaf44ab80cae9d585b6d15/packages/api-graphql/src/types/index.ts#L103) as follows.

```typescript
type WithListsFixed<T> =
  T extends PagedList<infer IT, infer NAME>
    ? PagedList<Exclude<IT, null | undefined>, NAME> &
        Exclude<T, keyof PagedList<any, any>>
    : T extends Record<string, unknown>
      ? {
          [K in keyof T]: WithListsFixed<T[K]>
        }
      : T
```

### Describe alternatives you've considered

As suggested in the previous issue, the property itself can be revived by type annotation, but without the benefit of `WithListsFixed`.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by chrisbonifacio** [comment]
Hi @HikaruTakakura, I see that you had proposed a solution to properly infer the `total` property without using the type helper.

I will close this and re-open the original issue to continue the discussion with the team and post any updates there
