### ISSUE TITLE
amplify vulnerability in snyk due to old dependency

### ISSUE THREAD

**Issue by gustavo-rios** [aws-amplify/amplify-js#1381]
I've found that snyk is reporting the following vulnerability in one of the dependencies and I just wanted you to be aware. Seems like updating crypto-browserfify to the latest version should fix this issue.

![amplifyvuln](https://user-images.githubusercontent.com/8270535/43649149-62bfea8a-970a-11e8-8b3f-d466b181077f.png)

**Comment by haverchuck** [comment]
@gustavo-rios  - thank you for letting us know!

**Comment by jordanranz** [comment]
Seems crypto-browserify was updated in this PR: #731

**Comment by jordanranz** [comment]
Hey @gustavo-rios, thanks for reporting this.

We did actually try upgrading the crypto-browserify version: #731, but we experienced issues with it and Angular 6: #857 

I will investigate the status of this.

**Comment by stephannagel** [comment]
Hi, any updates on this issue?
