### ISSUE TITLE
Amplify Core not picking up existing Cognito credentials

### ISSUE THREAD

**Issue by mordka** [aws-amplify/amplify-js#1382]
Do you want to request a feature or report a bug?
**This is a bug**
What is the current behavior?

I'm working on adding Pinpoint Analytics to the existing project, which has Cognito auth already implemented. I'm using amazon-cognito-identity-js separately (it was implemented before Amplify was developed). The user is logged in and credentials are available in AWS.config.credentials
I've imported @aws-amplify/auth and configured it to use the same details as in manual Cognito set up.
Event is not sent correctly:
```
[DEBUG] 39:58.186 Credentials - getting credentials
[DEBUG] 39:58.188 Credentials - picking up credentials
[DEBUG] 39:58.191 Credentials - getting new cred promise
[DEBUG] 39:58.193 Credentials - checking if credentials exists and not expired
[DEBUG] 39:58.195 Credentials - need to get a new credential or refresh the existing one
[DEBUG] 39:58.196 AuthClass - Getting current user credentials
[DEBUG] 39:58.200 AuthClass - Getting current session
[DEBUG] 39:58.201 AuthClass - Failed to get user from user pool
//event registered here
{[DEBUG] 39:58.205 AuthClass - Failed to get the current user: "No current user"}
{[DEBUG] 39:58.209 AuthClass - getting session failed: "No current user"}
[DEBUG] 39:58.210 Credentials - setting credentials for guest
{[DEBUG] 39:59.0 Credentials - Failed to load credentials: CognitoIdentityCredentials}
{[DEBUG] 39:59.4 AWSPinpointProvider - ensure credentials error: Error: IdentityPool 'ap-southeast-2:idpoolid' not found.
```

What is the expected behavior?

I expect it to pick up existing AWS credentials stored in `AWS.config.credentials`

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
I'm using 
```
    "@aws-amplify/analytics": "^1.0.3",
    "@aws-amplify/auth": "^1.0.4",
```

I noticed a possible bug in line https://github.com/aws-amplify/amplify-js/blob/7bba431f4f194cd8c6461a50cd2fad239ecdf325/packages/core/src/Credentials.ts#L63

After I change this line to:
```
if (AWS.config && AWS.config.credentials && AWS.config.credentials instanceof AWS.Credentials) {
```
It successfully sends event and all works.

Related: https://github.com/aws-amplify/amplify-js/issues/1273#issuecomment-409723274

**Comment by haverchuck** [comment]
@mordka  - thank you!

**Comment by jordanranz** [comment]
Seems like the PR merged fixed the issue. Please reopen if there are any more related questions or concerns.
