### ISSUE TITLE
When we are getting support for EMAIL_OTP challengeName, email MFA? 

### ISSUE THREAD

**Issue by gurindertrantor** [aws-amplify/amplify-js#13837]
### Describe the feature you'd like to request

MFA for email was introduced by Cognito but Amplify doesn't provide support for this particular challenge name. 
<img width="453" alt="Screenshot 2024-09-21 at 9 46 43 PM" src="https://github.com/user-attachments/assets/06890bef-0c01-44a9-b3c2-d100b37427ca">

### Describe the solution you'd like

Ideally it should support email MFA by default as it support MFA for phone number.

### Describe alternatives you've considered

Ideally it should support email MFA by default as it support MFA for phone number.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cwomack** [comment]
Hello, @gurindertrantor 👋 and thanks for opening this issue.  Yes, we are definitely tracking this on our side and already have a [feature branch](https://github.com/aws-amplify/amplify-js/compare/main...feat/email-mfa) (with associated PR's) that is in the works at this point.  We'll update this issue as progress is made and keep anyone following informed when it's merged.  Thanks!

**Comment by gurindertrantor** [comment]
Hi @cwomack and @jjarvisp any update on this? Is there any expected timeline?

Thanks!

**Comment by Mehdi-android** [comment]
Hi @cwomack and @jjarvisp what is the update? I am using this library in android kotlin
 implementation("com.amplifyframework:core:1.28.0")
    implementation("com.amplifyframework:aws-auth-cognito:1.28.0")
    
    I am getting error
    AuthException{message=Sign in failed, cause=java.lang.IllegalArgumentException: No enum constant com.amazonaws.mobile.client.results.SignInState.EMAIL_OTP, recoverySuggestion=See attached exception for more details.}
    
   Give timeline please, when can we expect this issue to be resolved?

Thanks!

**Comment by cwomack** [comment]
@Mehdi-android, we try to avoid stating specific dates or time frames for when a feature is available to ensure we don't fall short of promises/expectations.  That being said, I can state that this is being actively worked on and tested at this point (and I'll again point to the [feature branch](https://github.com/aws-amplify/amplify-js/compare/main...feat/email-mfa) as something to watch 😉).  

We will follow up on this issue as soon as we can with any further progress!

**Comment by sators** [comment]
Following

**Comment by smartersign** [comment]
Email MFA can't come fast enough.. thanks all for working on this!

**Comment by haverchuck** [comment]
This shipped on version 6.8.0!

**Comment by smartersign** [comment]
thanks all!

**Comment by lgolubenkobit** [comment]
Is not working for me.
Mail is received but the form to enter 2FA code is never showed.

**Comment by smartersign** [comment]
> Is not working for me. Mail is received but the form to enter 2FA code is never showed.

it sounds like you are confusing the hosted UI with the amplify-js package

**Comment by lgolubenkobit** [comment]
> > Is not working for me. Mail is received but the form to enter 2FA code is never showed.
> 
> it sounds like you are confusing the hosted UI with the amplify-js package

We are using Amplify UI instead of Cognito UI. Some time ago we had the same error that first post.
After update to 6.8.0 error doesn't ocurr anymore but form is never showed.

**Comment by cwomack** [comment]
@lgolubenkobit, the support for Email MFA is only for the JS library at this point and not yet available for use with the Amplify UI Authenticator component.  We are tracking that feature request [here](https://github.com/aws-amplify/amplify-ui/issues/5983) in the `amplify-ui` repo.

**Comment by lgolubenkobit** [comment]
> @lgolubenkobit, the support for Email MFA is only for the JS library at this point and not yet available for use with the Amplify UI Authenticator component. We are tracking that feature request [here](https://github.com/aws-amplify/amplify-ui/issues/5983) in the `amplify-ui` repo.

When I read the post informing that it had been merged, I understood that the entire flow was solved. We will then wait for the solution from the amplify-ui repository.
Tranks!
