### ISSUE TITLE
DataStore Sync Issue: Sometimes, DataStore saves data locally when the network is available.

### ISSUE THREAD

**Issue by vijaykishan312** [aws-amplify/amplify-js#13832]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

DataStore

### Amplify Version

v5

### Amplify Categories

storage, api

### Backend

Amplify CLI

### Environment information

<details>

```
# Put output below this line
**Issue: AWS Amplify DataStore Sync Problem**

**Description**: The AWS Amplify DataStore is not functioning correctly when data is inserted using DataStore.save(). Occasionally, the data does not sync with the server and remains only in the local storage (DynamoDB). After some time, the data eventually syncs with the server.

**Library Versions:**

- @aws-amplify/datastore-storage-adapter: ^1.4.5
- aws-amplify: ^5.3.10 
- react-native:0.68.2


```

</details>

### Describe the bug

**Issue: AWS Amplify DataStore Sync Problem**

**Description**: The AWS Amplify DataStore is not functioning correctly when data is inserted using DataStore.save(). Occasionally, the data does not sync with the server and remains only in the local storage (DynamoDB). After some time, the data eventually syncs with the server.

**Library Versions:**

- @aws-amplify/datastore-storage-adapter: ^1.4.5
- aws-amplify: ^5.3.10 
- react-native:0.68.2

### Expected behavior

All data is also synchronised via the datastore

### Reproduction steps

1. Create data with DataStore and AWS GraphQL
2. Check the code logs
3. Check the data in DynamoDB, but note that there might be some issues or additional information to review

### Code Snippet

```javascript
// Put your code below this line.

```
const dataCollection = {
          sessionDuration: dataResponse[0]?.sessionDuration,
          collectionStorage: dataResponse[0]?.collectionStorage,
          currentStorageLocation: privousCollectionData[0]
            ?.previousCurrentStorageLocation
            ? privousCollectionData[0]?.previousCurrentStorageLocation
            : dataResponse[0]?.currentStorageLocation,
          CollectionUsedDate: null,
          isCollectionUsed: false,
          storeReferenceId: privousCollectionData[0]?.previousStoreReferenceId,
          collectionUsedBy: '',
          otherUsedMessage: null,
          isActivityFinish: true,
          collectionId: null,
          id: privousCollectionData[i]?.id,
          locationChangeDate:
            privousCollectionData[0]?.previousLocationChangeDate,
          storageExpiryAlert:
            privousCollectionData[0]?.previousStorageExpiryAlert,
          storageExpiry: privousCollectionData[0]?.previousStorageExpiry,
          updatedAt: currentUTCTime(),
          activityType: 'Collection',
          activitySide: dataResponse[0]?.activitySide,
          activityEndTime: privousCollectionData[0]?.previousActivityEndTime,
          sessionEndTime: privousCollectionData[0]?.previousSessionEndTime,
          previousStoreReferenceId: '',
          previousStorageExpiryAlert: '',
          previousLocationChangeDate: '',
          previousCurrentStorageLocation:
            privousCollectionData[0]?.previousCurrentStorageLocation,
          previousStorageExpiry: '',
          previousActivityEndTime: '',
          previousSessionEndTime: '',
          subjectId: '',
          stashTotalFeed: '',
          activityDoneVia: dataResponse[0]?.activityDoneVia,
          activityDuration:dataResponse[0]?.activityDuration,
          sessionStartTime:dataResponse[0]?.sessionStartTime,
          subjectAvatarName:dataResponse[0]?.subjectAvatarName,
          activityStartTime:dataResponse[0]?.activityStartTime,
          unitOfMeasurement:dataResponse[0]?.unitOfMeasurement,
          appId:dataResponse[0]?.appId,
          _deleted:dataResponse[0]?._deleted,
          preStorageLocation:dataResponse[0]?.preStorageLocation,
          stashUsedCollectionId:dataResponse[0]?.stashUsedCollectionId,
          stashStart:dataResponse[0]?.stashStart,
          vijay:dataResponse[0]?.vijay,
          createdAt:dataResponse[0]?.createdAt,
          deviceType:dataResponse[0]?.deviceType,
          _lastChangedAt:dataResponse[0]?._lastChangedAt,
          isSync:dataResponse[0]?.isSync,
          owner:dataResponse[0]?.owner,
          collectionStorageUsed:String(dataResponse[0]?.collectionStorageUsed),
          sessionId:dataResponse[0]?.sessionId,
        };

// Code for data save
const response = await DataStore.save(new Activity(dataCollection))

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Mobile Device

iPhone 15

**Comment by cwomack** [comment]
@vijaykishan312, closing this issue because it appears that there was a duplicate (exact match) opened up with #13833.
