### ISSUE TITLE
Documentation update: add documentation showing how to configure a cognito password policy in `Amplify.configure`

### ISSUE THREAD

**Issue by jackirvine97** [aws-amplify/amplify-js#13856]
### On which framework/platform would you like to see this feature implemented?

React, Angular

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

A cognito password policy can be added to an `Amplify.configure()` call as follow:

```
Amplify.configure({
    aws_cognito_password_protection_settings: {
        passwordPolicyMinLength: 8,
        passwordPolicyCharacters: [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE",
        ],
    },
    Auth: {
        region: awsExports.REGION,
        userPoolId: awsExports.USER_POOL_ID,
        userPoolWebClientId: awsExports.USER_POOL_APP_CLIENT_ID,
    },
})
```

This automatically passes your password policy to a the password input field in the `Authenticator` component.

**The problem** - this straightforward pattern is not mentioned in the documentation!

### Please describe a solution you'd like.

Please add a reference to this in the documentation!

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by HuiSF** [comment]
Hi @jackirvine97 Amplify JS v6 now accepts password format fields by calling `Amplify.configure()`, for exmaple:

```ts
Amplify.configure(
  {
    Auth: {
      Cognito: {
        userPoolClientId: "YOUR_USER_POOL_CLIENT_ID",
        userPoolId: "YOUR_USER_POOL_ID",
        passwordFormat: {
          minLength: 8,
          requireLowercase: true,
          requireNumbers: true,
          requireUppercase: true,
          requireSpecialCharacters: true,
        },
      },
    },
  },
);
```

Can you confirm whether this fulfills your request?

**Comment by jackirvine97** [comment]
Awesome - this ticket is related to the documentation. The docs (when I made this ticket) had no mention of how configure password policy and i thought it should be added given how common a pattern it is. Do the V6 docs now mention it?

**Comment by ashika112** [comment]
@jackirvine97 we have section [our doc](https://docs.amplify.aws/react/build-a-backend/auth/modify-resources-with-cdk/#override-cognito-userpool-password-policies) now on how to do this with Amplify backend.

Also, how to configre Auth resource without amplify backend [here](https://docs.amplify.aws/react/build-a-backend/auth/use-existing-cognito-resources/#use-auth-resources-without-an-amplify-backend) which talks about password policy overrides.

If this satisfies the ask, can we close down this issue?

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
