### ISSUE TITLE
custom attributes not works react amplify 

### ISSUE THREAD

**Issue by gonzabt3** [aws-amplify/amplify-js#13895]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Version

v6

### Amplify Categories

auth

### Backend

Amplify Gen 2 (Preview)

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I am trying to define custom attributes but I have and error of typescript.I followed the official  documentation 
```

ERROR:
TypeScript validation check failed.
Resolution: Fix the syntax and type errors in your backend definition.

`import { defineAuth } from '@aws-amplify/backend';

/**
 * Define and configure your auth resource
 * @see https://docs.amplify.aws/gen2/build-a-backend/auth
 */
export const auth = defineAuth({
  loginWith: {
    email: true,
  },    
  userAttributes: {
    "custom:payed": {
      dataType: "Boolean",
      mutable: true,
    },
    "custom:is_trial_user": {
      dataType: "Boolean",
      mutable: true,
    },
    "custom:start_free_trial_date": {
      dataType: "DateTime",
      mutable: true,
    },
    "custom:end_free_trial_date": {
      dataType: "DateTime",
      mutable: true,
    },
  },
});`
```

### Expected behavior

following the docs I need to add the prefix custom,

### Reproduction steps

npm amps sandbox

### Code Snippet

```javascript
// Put your code below this line.



### Log output

<details>

```
// Put your logs below this line

```

</details>


### aws-exports.js

_No response_

### Manual configuration

_No response_

### Additional configuration

_No response_

### Mobile Device

_No response_

### Mobile Operating System

_No response_

### Mobile Browser

_No response_

### Mobile Browser Version

_No response_

### Additional information and screenshots

_No response_

**Comment by cwomack** [comment]
Hello, @gonzabt3 and sorry to hear you're running into this issue.  To better understand how you got here, can you clarify if you've already followed either our [Quickstart Guide](https://docs.amplify.aws/react/start/quickstart/) or the [manual installation](https://docs.amplify.aws/react/start/manual-installation/) steps to set up your app? If so, can you share what you have in your `package.json` so we can see the dependencies? Thanks!

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

If there's further questions or issues with setting up the backend in the Gen 2 Developer Experience, please also review the existing issues (or open a new one) on the `amplify-backend` repository ([here](https://github.com/aws-amplify/amplify-backend/issues)). 

Thank you!
