### ISSUE TITLE
Cognito auth and cognito identity can we use both together

### ISSUE THREAD

**Issue by saneera** [aws-amplify/amplify-js#1392]
Hi All

one of my app I m going to use cognito identity as native sign in sign up but for google and face book going to use cognito auth js library

but both are is not working together

is there anyway to user cognito identity js to social login ? (without url based , i need to save token on local storage)

Thanks

**Comment by powerful23** [comment]
@saneera For now you can only use Cognito Hosted UI(which is url based) to sign in the Cognito User Pool with federated providers.

**Comment by mlabieniec** [comment]
This can be accomplished using the OAuth implementation in Amplify Auth (and the hosted UI):
https://aws-amplify.github.io/amplify-js/media/authentication_guide#using-amazon-cognito-hosted-ui

Let us know if this works for you, feel free to re-open the issue.

**Comment by undefobj** [comment]
Hello everyone, we have created an RFC for feature work that should make the challenges found in this issue easier in the future. If you have a moment please read through the details and add any comments: https://github.com/aws-amplify/amplify-js/issues/2716

Your feedback in the RFC will help us ensure that we are delivering the best experience possible. Thank you.
