### ISSUE TITLE
 Unable to Implement Email-Based MFA Authentication

### ISSUE THREAD

**Issue by arpita3112** [aws-amplify/amplify-js#13929]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Version

v6

### Amplify Categories

auth

### Backend

None

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

We are trying to implement MFA (Multi-Factor Authentication) using email-based authentication. We have followed the steps and configured the SDK as per the official documentation:
https://docs.amplify.aws/javascript/start/connect-to-aws-resources/

However, we are still encountering the following error:
`signInHelpers.ts:611 Uncaught (in promise) SignInException: An error occurred during the sign in process. EMAIL_OTP challengeName returned by the underlying service was not addressed.
    at getSignInResult (http://localhost:3000/static/js/bundle.js:85307:9)
    at signInWithSRP (http://localhost:3000/static/js/bundle.js:82737:85)
    at async loginBtnClick (http://localhost:3000/main.a99b129….hot-update.js:67:9)`
    
We have reviewed the guide but could only find information related to SMS or TOTP-based MFA:
 https://docs.amplify.aws/react/build-a-backend/auth/concepts/multi-factor-authentication/#enable-totp-after-a-user-is-signed-in
 
We also tried implementing the functionality using amplify/ui-react, but the error persists.
 
 We are using the SDK version :
 aws-amplify : **v6.6.5**
 
Is there a way to achieve email-based MFA with the above setup? Any guidance or solutions would be greatly appreciated.

### Expected behavior

Complete the sign-in process without errors after the correct OTP is entered.

### Reproduction steps

1) First, install the SDK and configure it with Cognito.  
2) After that, call the `signIn` method from the SDK and pass the email and password.

### Code Snippet

```
  Amplify.configure({
          Auth: {
            Cognito: {
              userPoolId: get(authcredetilas, "userPoolId", null),
              region: get(authcredetilas, "region", null),
              userPoolClientId: get(
                authcredetilas,
                "userPoolWebClientId",
                null
              ),
              identityPoolId: get(authcredetilas, "identityPoolId", null),
              loginWith: {
                email: true,
              },
            },
          },
        });
```

And 
```
await signIn({
      username: "****",
      password: "****",
    })
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by arpita3112** [comment]
@cwomack 
Is there any update on this?

**Comment by cwomack** [comment]
Hello, @arpita3112 👋.  This feature was released by Cognito recently and we are actively working on this feature to be supported within Amplify.  We're tracking this feature request in #13837 as well as [#5829](https://github.com/aws-amplify/amplify-ui/issues/5829) on the `amplify-ui` repo for support on the Authenticator connected component.  You can also keep an eye on [this feature branch](https://github.com/aws-amplify/amplify-js/compare/main...feat/email-mfa) in particular. 

Please follow those issues for updates and progress as it's made, and I'll close this one out as a duplicate.

**Comment by sators** [comment]
Following
