### ISSUE TITLE
Unable to use "between" for multiple sort keys

### ISSUE THREAD

**Issue by lwang-79** [aws-amplify/amplify-js#13951]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

GraphQL API

### Amplify Version

v6

### Amplify Categories

api

### Backend

Amplify Gen 2

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 15.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 71.03 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.9.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.8.3 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 130.0.6723.59
    Safari: 18.0.1
  npmGlobalPackages:
    @aws-amplify/cli: 11.0.3
    @types/node: 18.7.4
    @ziglang/cli: 0.0.12
    aws-cdk: 2.131.0
    npm-check-updates: 17.1.2
    npm: 10.8.3
    nx: 19.8.3
    ts-node: 10.9.1
    typescript: 4.8.4
    yarn: 1.22.19

```

</details>

### Describe the bug

I have a model "Job" wich has a GSI with 3 sort keys "datetime", "status", "type". When I try to query the data between tow datetime, I can't find a way to write the code. The "between" operator only accepts one itme in the array.

![image](https://github.com/user-attachments/assets/8569f87c-6ec2-42af-ae23-10b3dbc1a958)
![image](https://github.com/user-attachments/assets/4d16e395-bc2b-4505-8ce6-1a4c59c8abfa)

### Expected behavior

The "between" operator can accept tow items.

### Reproduction steps

1. create a model with GSI similar to "index('instructorId').sortKeys(['datetime', 'status', 'type'])"
2. try to query the data between tow datetime.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @lwang-79 can you please provide more information about the project's environment, such as the package.json file and dependencies listed in it?

**Comment by lwang-79** [comment]
Hi @chrisbonifacio, thank you for checking this. Here is my package.json
```
{
  "name": "next-driving",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@aws-amplify/geo": "^3.0.52",
    "@chakra-ui/icons": "^2.1.1",
    "@chakra-ui/next-js": "^2.2.0",
    "@chakra-ui/react": "^2.8.2",
    "@emotion/react": "^11.13.3",
    "@emotion/styled": "^11.13.0",
    "aws-amplify": "^6.6.2",
    "framer-motion": "^11.5.6",
    "next": "^14.2.14",
    "react": "^18",
    "react-dom": "^18",
    "react-slick": "^0.30.2",
    "react-webcam": "^7.2.0"
  },
  "devDependencies": {
    "@aws-amplify/backend": "^1.3.0",
    "@aws-amplify/backend-cli": "^1.2.8",
    "@types/node": "^22",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "@types/react-slick": "^0.23.13",
    "aws-cdk": "^2.159.1",
    "aws-cdk-lib": "^2.159.1",
    "constructs": "^10.3.0",
    "esbuild": "^0.23.1",
    "tsx": "^4.19.1",
    "typescript": "^5.6.2"
  }
}
```

**Comment by chrisbonifacio** [comment]
it looks like you are a bit behind on the package versions.

can you upgrade to the latest versions of `@aws-amplify/backend` and `@aws-amplify/backend-cli`?

also, after upgrading, please run the following command and confirm that the version output is 1.10.2.

```sh
npm list @aws-amplify/data-schema
``` 

if not, run the following command to update the package and re-run the above command to confirm.

```sh
npm update @aws-amplify/data-schema
```

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
