### ISSUE TITLE
Can't send the MFA token when user has both of SMS MFA method and Software Token MFA method

### ISSUE THREAD

**Issue by KimThanh27920** [aws-amplify/amplify-js#13962]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

React App

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Please describe your bug.

When user has multiple MFA methods, I try to send MFA code with type SOFTWARE_TOKEN_MFA, it always return invalid code error 

### What's the expected behaviour?

I believe the function should execute successfully and return my token.

### Help us reproduce the bug!

Set up both of SMS MFA and Software Token MFA for the user, login normally and enter correct Software Token Code. It return invalid code error

### Code Snippet

```
cognitoUser.sendMFACode(
          verifyCode,
          {
            onSuccess: () => {
               updateChallengeScreen();
               clearLoginProcessCookies();
              setIsSubmitting(false);
            },
            onFailure: function (err) {
              handleSessionExpired(err.message);
              setIsSubmitting(false);
            },
          },
          MFA_TYPE.SOFTWARE_TOKEN_MFA
        );
```

**Comment by HuiSF** [comment]
Hi @KimThanh27920 Thanks for opening this issue. Could you post the packages and versions listed in the `package.json` of your project?

**Comment by cwomack** [comment]
@KimThanh27920, wanted to circle back and see if you could share what's in your `package.json` as well as any relevant frontend code that's part of the MFA/signin flows.  

Can you see if calling the `confirmSignIn()` API (in Amplify v5) rather than the `sendMFACode()` (as seen [here](https://docs.amplify.aws/gen1/react/prev/build-a-backend/auth/manage-mfa/#:~:text=Manage%20SMS%20MFA%20during%20sign%2Din)) resolves the issue? Please ensure that you are calling `Auth.signIn()` followed by `Auth.confirmSignIn()` as well.

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
