### ISSUE TITLE
adapter-nextjs for NextJS 15

### ISSUE THREAD

**Issue by XC3S** [aws-amplify/amplify-js#13983]
### Describe the feature you'd like to request

Currently adapter-nextjs support nextjs version <15.0.0

### Describe the solution you'd like

support for Nextjs 15

### Describe alternatives you've considered

-

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cwomack** [comment]
Hello, @XC3S 👋 and thank you for opening this issue.  We're currently tracking the support for v15 of NextJS in issue #13924 and will close this one as a duplicate.  Please follow that issue for updates, thanks!
