### ISSUE TITLE
TypeError: Promise.allSettled is not a function (it is undefined) calling DataStore.clear() (React Native)

### ISSUE THREAD

**Issue by talaikis** [aws-amplify/amplify-js#14035]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

DataStore

### Amplify Version

v6

### Backend

None

### Environment information

<details>

```
# Put output below this line

System:
    OS: Windows 11 10.0.22631
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 10.54 GB / 31.93 GB
  Binaries:
    Node: 22.11.0 - ~\AppData\Local\fnm_multishells\11184_1732523016089\node.EXE
    Yarn: 3.6.4 - ~\AppData\Local\fnm_multishells\11184_1732523016089\yarn.CMD
    npm: 10.9.0 - ~\AppData\Local\fnm_multishells\11184_1732523016089\npm.CMD
    Watchman: 20230709.023423.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @aws-amplify/react-native: 1.1.6 => 1.1.6
    @azure/core-asynciterator-polyfill: 1.0.2 => 1.0.2
    aws-amplify: 6.9.0 => 6.9.0
```

</details>

### Describe the bug

Calling DataStore.clear() in React Native latest versions (approx after 6.7+):

```
TypeError: Promise.allSettled is not a function (it is undefined) 
```

### Expected behavior

Working `clear()`

### Reproduction steps

1. install 6.8 or 6.9 aws-amplify on a React Native app
2. call Datastore.clear()

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by HuiSF** [comment]
Hi @talaikis could you confirm the exact version of the react-native package you are using?

**Comment by talaikis** [comment]
> Hi @talaikis could you confirm the exact version of the react-native package you are using?

```
"aws-amplify": "6.9.0"
```

**Comment by HuiSF** [comment]
Hi @talaikis I was asking for the **react-native** package version. As far as I know, this error `TypeError: Promise.allSettled is not a function (it is undefined)` happens due to the lower version of react-native JS engine doesn't provide this function.

Amplify JS v6 requires react-native 0.70.0 as the lowest supported version at this moment.
