### ISSUE TITLE
Can't build vue 3 project if importing aws-amplify package

### ISSUE THREAD

**Issue by ivanovvitaly** [aws-amplify/amplify-js#14031]
**Describe the bug**
I installed aws-amplify npm package to the clean vue 3 project and added Amplify import. When I run `npm run build` I get long list of errors, `npm run serve` runs without errors though. If I remove aws-amplify import statement the project compiles without errors.
Please advice

**To Reproduce**
1. Setup new vue 3 project with webpack, typescript
2. Install aws-amplify package
3. Add Amplify import in main.ts `import { Amplify } from 'aws-amplify';`
4. Build project with `npm run build`
5. See errors [error.txt](https://github.com/user-attachments/files/17848646/error.txt)

**Expected behavior**
Project should compile without errors

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise 22H2 Build 22621.4460
 - Browser -
 - Version -
 - Node v22.9.0
 - Npm v10.9.0
 -  "aws-amplify": "^6.9.0"

**Additional context**

main.ts
```
import { createApp } from 'vue'
import App from './App.vue'

import { Amplify } from 'aws-amplify';

const app = createApp(App)
app.mount('#app')

```

package.json
```
{
  "dependencies": {
    "@primevue/themes": "^4.1.1",
    "aws-amplify": "^6.9.0",
    "core-js": "^3.8.3",
    "primeflex": "^3.3.1",
    "primeicons": "^7.0.0",
    "primevue": "^4.1.1",
    "vue": "^3.5.13",
    "vue-router": "^4.0.3"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~5.0.0",
    "@vue/cli-plugin-router": "~5.0.0",
    "@vue/cli-plugin-typescript": "~5.0.0",
    "@vue/cli-service": "~5.0.8",
    "sass": "^1.32.7",
    "sass-loader": "^12.6.0",
    "typescript": "~4.5.5"
  }
}
```

**Comment by HuiSF** [comment]
Hi @ivanovvitaly thank you for opening this issue.

I did a quick test with creating a new Vue starter app, and I couldn't reproduce this issue. I've taken the following steps:

1. `npm create vue@latest`
2. `npm install aws-amplify`
3. modified `main.ts` using the code example you provided
4. `npm run build` succeeded with the following output

```shell
❯ npm run build                   

> test-build@0.0.0 build
> run-p type-check "build-only {@}" --


> test-build@0.0.0 type-check
> vue-tsc --build --force


> test-build@0.0.0 build-only
> vite build

vite v5.4.11 building for production...
✓ 585 modules transformed.
dist/index.html                       0.43 kB │ gzip:  0.29 kB
dist/assets/AboutView-CSIvawM9.css    0.09 kB │ gzip:  0.10 kB
dist/assets/index-5dJgFXHu.css        4.21 kB │ gzip:  1.30 kB
dist/assets/AboutView-6XaiO942.js     0.23 kB │ gzip:  0.20 kB
dist/assets/index-Dsxzz0b4.js       145.63 kB │ gzip: 53.13 kB
✓ built in 854ms
```

In noticed that you are using `@vue/cli-service` which is already in [the maintenance mode](https://cli.vuejs.org/guide/cli-service.html#cli-service), and your typescript version is quite low (may have compatibility issue with `@types/node` (not particular the aws-amplify packages)). Could you try to upgrade your Vue tooling and try again?

**Comment by ae-vivanov** [comment]
Hey @HuiSF, thanks for quick feedback! I tried clean vue 3 with vite template it builds without issues.
The initial project was setup with vue 3 with **webpack** . 
Can I make it work with webpack?

**Comment by cwomack** [comment]
@ae-vivanov, that's great to hear that it's now building without issues using Vite.  We don't think webpack is the issue here, but rather Typescript.  Did you also upgrade the version of typescript as well before trying the webpack build again?

**Comment by ivanovvitaly** [comment]
@cwomack upgraded to typescript 5.6.3, compiled without errors. Thank you so much!

**Comment by cwomack** [comment]
@ivanovvitaly, glad to hear that and thanks for following up and closing the issue!
