### ISSUE TITLE
Pubsub: {} in Amplify.configure conflict with appsync subscriptions

### ISSUE THREAD

**Issue by aaayushsingh** [aws-amplify/amplify-js#1404]
This is _partially_ related to #823

Do you want to request a feature or report a bug?
**Bug**

What is the current behavior?

This configuration throws an error, while the configuration below it works fine
```
Amplify.configure({
  Auth: {
    identityPoolId: 
    region: 
    userPoolId: 
    userPoolWebClientId: 
  },
  PubSub: {
    aws_pubsub_region: 
    aws_pubsub_endpoint: 
 },

  aws_appsync_graphqlEndpoint:
  aws_appsync_region: 
  aws_appsync_authenticationType: 
  aws_pubsub_endpoint: 
});
```

```
Amplify.configure({
  Auth: {
    identityPoolId: 
    region: 
    userPoolId: 
    userPoolWebClientId: 
  },
//  PubSub: {
//    aws_pubsub_region: 
//    aws_pubsub_endpoint: 
// },

  aws_appsync_graphqlEndpoint:
  aws_appsync_region: 
  aws_appsync_authenticationType: 
  aws_pubsub_endpoint: 
});

```
**With the second configuration, I can subscribe to Appsync graphql endpoint**

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

```

let subquery = `a subscription`
Auth.signIn("username", "password").then(data =>{
  try {
      let sub = API.graphql(graphqlOperation(subquery));
      sub.subscribe({
        next: data => {
          console.log(data);
        },
        error: err => console.log(err)
      });
    } catch (e) {
      console.log(e);
    }
}

```

What is the expected behavior?

Subscriptions should work normally

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

Tested on ReactNative

**Comment by milashenko** [comment]
Seems to be related to #1302

**Comment by kirkryan** [comment]
Also have the same problem
