### ISSUE TITLE
Update `@aws-amplify/adapter-nextjs` to Support `next@15.x` for Seamless Installation

### ISSUE THREAD

**Issue by mgmgpyaesonewin** [aws-amplify/amplify-js#14055]
### Is this related to a new or existing framework?

Next.js

### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

Please update the `@aws-amplify/adapter-nextjs` package to support `next@15.0.3`. Currently, the package's peer dependency restricts compatibility to versions <15.0.0. Since the changes from 15.0.0 to 15.0.3 are minor, compatibility should be feasible. Updating this dependency will allow users to integrate the adapter with the latest Next.js version without dependency resolution issues.

Steps to Reproduce:

Create a new project with Next.js version 15.0.3.
```bash
npx create-next-app@latest
```

Install the @aws-amplify/adapter-nextjs package:
```bash
npm install @aws-amplify/adapter-nextjs
```

Observe the following error:
```bash
npm ERR! code ERESOLVE  
npm ERR! ERESOLVE unable to resolve dependency tree  
npm ERR!  
npm ERR! While resolving: evp-config-gen@0.1.0  
npm ERR! Found: next@15.0.3  
npm ERR! node_modules/next  
npm ERR!   next@"15.0.3" from the root project  
npm ERR!  
npm ERR! Could not resolve dependency:  
npm ERR! peer next@">=13.5.0 <15.0.0" from @aws-amplify/adapter-nextjs@1.2.32
```

### Describe the solution you'd like

Update the @aws-amplify/adapter-nextjs peer dependency to accept next@15.x versions, or at least test and validate compatibility with 15.0.x. This will resolve the dependency tree issues and allow users to leverage the latest features and updates of Next.js.

### Describe alternatives you've considered

As a temporary workaround, the package can be installed using the --force flag:

```bash
npm install @aws-amplify/adapter-nextjs --force
```

However, this is not an ideal solution. Using --force overrides the dependency resolution, which may introduce potential issues or incompatibilities in the project.

The package should be updated to allow seamless installation without the need for forcing, ensuring compatibility with next@15.x versions. This would provide a more reliable and user-friendly experience while avoiding risks associated with overriding peer dependency constraints.

### Additional context

This issue blocks the adoption of the latest Next.js versions for projects relying on @aws-amplify/adapter-nextjs, hindering access to new features and optimizations in Next.js 15.x. If compatibility concerns exist, consider providing an alpha or beta release for users to test and provide feedback.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by jjarvisp** [comment]
Hey @mgmgpyaesonewin! Thanks for opening this issue. We are currently working towards providing support for Next.js 15 in Amplify JS and have released a tagged version for testing. You can install with
```
npm install aws-amplify@next-15 @aws-amplify/adapter-nextjs@next-15
```
We will be working to finalize this update and should have a stable release in the near future.

As we are currently tracking support for Next.js 15 in issue #13924, I will close this one as a duplicate. Please follow that issue any new updates, thank you!
