### ISSUE TITLE
PreSignUp Trigger error not forwarding to signInWithRedirects_failure

### ISSUE THREAD

**Issue by bilalAlgoace** [aws-amplify/amplify-js#14063]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Authentication

### Amplify Version

v6

### Amplify Categories

auth

### Backend

Amplify CLI

### Environment information

<details>

```
# Put output below this line

npm run dev
```

</details>

### Describe the bug

I have created a preSignUp trigger which checks whether the email is registered or not and if registered then do not allow user to register that email this is working fine with simple email and password process and throwing error of user already exists but with i am using signInWithRedirects it is showing error in search params like this:

http://localhost:3000/signup?error_description=PreSignUp+failed+with+error+User+already+exists..+&state=lymVlSL5AV0pIeORuFFVDdSe1r3Wh7zx&error=invalid_request

but not forwarding any error in signInWIthRedirects_failure 

I am using Next js 14 app router

but this code is working in Reavt Native and showing proper error in signInWIthRedirects_failure 

### Expected behavior

It should show error in signInWIthRedirects_failure

### Reproduction steps

I am using signInWithRedirects for social logins with amplify

### Code Snippet

```javascript
// Put your code below this line.
My Code:

useEffect(() => {
    const unsubscribe = Hub.listen("auth", ({ payload }) => {
      console.log("auth", payload)
      switch (payload.event) {
        case "signedIn":
          console.log("HUB SIGNED IN");
          // getUserData();
          isUserExist(setUser);
          break;
        case "signedOut":
          console.log("HUB SIGNED OUT");
          break; 
        case "signInWithRedirect":
          console.log("case signInWithRedirect")
          // getUserData();
          isUserExist(setUser);
          break;
        case "signInWithRedirect_failure":
          setError("An error has occurred during the OAuth flow.");
          console.log("Error")
          break;
      }
    });
    console.log("out of switch case")

    // getUserData();

    return unsubscribe;
  }, []);
  
  
  function for social logins: 
  
    const handleSocialLogin = async (provider: AuthProvider) => {
    try {
      const res = await signInWithRedirect({ provider: provider});
      console.log("🚀 ~ handleSocialLogin ~ res:", res);
    } catch (error) {
      console.error("Error with social login: ", error);
    }
  };
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2xxxxxxxxxxxxxxx",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_xxxxxxxxxxxxxxxxx",
    "aws_user_pools_web_client_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "oauth": {
        "domain": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "kwelta://,http://localhost:3000/signup",
        "redirectSignOut": "kwelta://,http://localhost:3000/signin",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE",
        "APPLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};

export default awsmobile;

### Manual configuration

{
  "aws_project_region": "us-east-2",
  "aws_cognito_identity_pool_id": "us-east-2xxxxxxxxxxxxxxxxxxxxxxx",
  "aws_cognito_region": "us-east-2",
  "aws_user_pools_id": "us-east-2_xxxxxxxxxxxxx",
  "aws_user_pools_web_client_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "oauth": {
    "domain": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "scope": [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin"
    ],
    "redirectSignIn": "kwelta://,http://localhost:3000/signup",
    "redirectSignOut": "kwelta://,http://localhost:3000/signin",
    "responseType": "code"
  },
  "federationTarget": "COGNITO_USER_POOLS",
  "aws_cognito_authentication_flow_type": "CUSTOM_AUTH",
  "aws_cognito_username_attributes": [
    "EMAIL"
  ],
  "aws_cognito_social_providers": [
    "FACEBOOK",
    "GOOGLE",
    "APPLE"
  ],
  "aws_cognito_signup_attributes": [
    "EMAIL"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
    "SMS"
  ],
  "aws_cognito_password_protection_settings": {
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
    "EMAIL"
  ]
}

**Comment by cwomack** [comment]
Hello, @bilalAlgoace 👋.  This looks similar to what's being captured in issue #13436 where there's possibly a race condition where the Hub event is dispatched before the useEffect hook is called. Can you see the advice within [this comment](https://github.com/aws-amplify/amplify-js/issues/13436#issuecomment-2383720223) to see if moving the `Amplify.configure()` call within the useEffect hook resolves the issue?

**Comment by bilalAlgoace** [comment]
@cwomack  Thank you it works for me. 👍

**Comment by cwomack** [comment]
Glad to hear, @bilalAlgoace and thanks for following up!

**Comment by bilalAlgoace** [comment]
@cwomack now i am facing a issue on social authentications i am trying to sigin with google it is throw error:

 {
    "event": "signInWithRedirect_failure",
    "data": {
        "error": {
            "name": "OAuthSignInException",
            "recoverySuggestion": "Make sure Cognito Hosted UI has been configured correctly"
        }
    }
}

error message : "User cancelled OAuth flow."

The reason I think is that in cogtino my redirect callbackurl is: http://localhost:3000/ and I have added a protection layer in my app that if user is not authenticated it should get redirected to http://localhost:3000/login.

That's why it is showing this: "User cancelled OAuth flow" error.

but It is only happening with social logins and if i am using normal signin with email password it is working perfect. 

and If I changed my cogtino redirect callbackurl is: http://localhost:3000/login which doesn't need any authentication in my app it is also working properly and is signing in normally with social logins too.

@cwomack if you can please guide me in this too.

**Comment by cwomack** [comment]
@bilalAlgoace, it's possible that the added protection layer is impacting the behavior here when returning back from the Cognito Hosted UI.  Can you provide a little more detail as to what's happening there (or share the relevant code)?

But you should be able to keep using the redirect callback URL of http://localhost:3000/login (which should avoid the auth protection step) and then wait for the user session to be available via a call to the `fetchAuthSession` API before redirecting back to the home page or listen to the `signedIn` event with the Hub utility.

**Comment by bilalAlgoace** [comment]
@cwomack  yeah I did the same thing you you are telling in the comment and it is working perfectly.
Thank You. 👍
