### ISSUE TITLE
With new version of aws-amplify issue with redirect signInWithRedirect method

### ISSUE THREAD

**Issue by HemangiVekaria** [aws-amplify/amplify-js#14078]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Version

v6

### Amplify Categories

auth

### Backend

None

### Environment information

@aws-amplify/analytics: ^7.0.58 => 7.0.62
    @aws-amplify/react-native: ^1.1.6 => 1.1.6
    @aws-amplify/rtn-push-notification: ^1.2.31 => 1.2.31
    @aws-amplify/rtn-web-browser: ^1.1.1 => 1.1.1

### Describe the bug

I am currently using the latest version of aws-amplify. Previously, I was using the following versions:

```
aws-amplify: 3.3.1
@aws-amplify/analytics: ^3.3.4
```

My application includes an option for users to Sign In/Sign Up with Apple, using the custom provider `appleid.apple.com.` In the earlier version of aws-amplify, I was using the `Auth.federatedSignIn `method, which worked perfectly.

After updating to the latest version of aws-amplify, the `Auth.federatedSignIn` method is no longer available. Instead, there is a new method called `signInWithRedirect`. However, when I implemented it, it didn't work as expected.

When I call this method, a popup appears in the app with the message:
"App wants to use 'amazoncognito.com' to sign in."
It includes two buttons: "Cancel" and "Continue."

If I click "Cancel," the dialog closes.
If I click "Continue," it opens a webpage that displays an error.

This behavior is different from the previous version, where no popup appeared.

I have already configured my aws-config.json file with the following redirect URLs:

```
redirectSignIn: 'myapp://',
redirectSignOut: 'myapp://'
```

What can I do to resolve this issue?"

### Expected behavior

Login should work

### Reproduction steps

From iphone click on apple sign in and it do sign in success from apple and then call signInWithRedirect and it shows as above

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
Hello, @HemangiVekaria 👋. Can you share a screenshot or log of what the actual error is when you're calling `signInWithRedirect`?  Going from v3 to v6 is a HUGE upgrade with lots of changes, so we may need to get a little more details here on what's happening when you're calling the API's on the frontend.  Could you please also share the code where you're calling signInWithRedirect() as well? Thanks, and welcome to v6 of Amplify!

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
