### ISSUE TITLE
Option needed to assume different Cognito Roles for an user 

### ISSUE THREAD

**Issue by miljojohn** [aws-amplify/amplify-js#1407]
Dear Team,
Scenario :  In our application, one user can assume multiple Cognito roles. For each role, the UI rendering will change. After login, all users are provided with an drop down with the Role which they can assume while using the ERP. For Example Super Admin (user type) will have roles like, Super Admin, Department Head, Course Manager etc.  student (user type) might have have some roles like Union Leader, Class Representative.

Immediate screen rendered after user login will check the roles assigned to the user and will pick the role with least precedence (preferred role). We are using Amplify for all the above functionalities.

At the server side, in Cognito, we have configured all above mentioned roles. Its a one to one mapping with Cognito Group. All API calls are routed through API gateway where authorizer is set as AWS_IAM. 

In Identity pool configuration we are using 'choose role from token'. 

Issue:
We are not seeing any option available with Amplify to change the preferred/custom role dynamically without re-login. 

In the ID Token generated by Cognito, there is an attribute Custom_role_arn, based on which Cognito will assign the corresponding role/permission.  

Is there any way we can regenerate the token (with the new role set in Custom_role_arn) without logoff.

If this is not possible, please suggest some work around.

Kind Regards
Miljo

**Comment by rudyhadoux** [comment]
Why don't you manage roles inside your app ? And Cognito only to identify users without roles.
