### ISSUE TITLE
Amplify - user.sendMFACode is not a function 

### ISSUE THREAD

**Issue by PedroS11** [aws-amplify/amplify-js#1411]
I'm using aws amplify login and register on my backend for an api. I created two routes, login and confirmLogin. On the first one, i have:

    router.post('/login', (req, res, next) => {
        const { username, password } = req.body

        Group().Auth.signIn(username, password)
            .then(user => {
                res.send(user)
            })
            .catch(err => next(createError(httpStatusCode.BAD_REQUEST, err)))
    })

that sends the user after the successful login.
And on confirmLogin:

    router.post('/confirmLogin', (req, res, next) => {
        const { user, code } = req.body
        Group().Auth.confirmSignIn(user, code, 'SMS_MFA')
            .then(user => {
                res.send(user)
            })
            .catch(err => {
                console.log(err.message)
                next(createError(err.status, err))
            })
    })

However, when I try to confirm the login the error "user.sendMFACode is not a function" shows. In the frontend, I save the user sent from the /login and use it on /confirmLogin with the code. Any ideas how to solve this problem?

**Comment by grgaortiz** [comment]
Same here. Using: aws-amplify 0.3.3, aws-amplify-react-native 0.2.9., redux-saga 0.15.6

While calling the Auth.confirmSignIn using redux-saga:

let confirmedUserData = yield call([Auth, Auth.confirmSignIn], userObj, authCode, 'SMS');

Getting the following error: "TypeError: user.sendMFACode is not a function"

The response object from Auth.signIn is the following: https://d.pr/AX6IQI. This response object is what gets passed to Auth.confirmSignIn as the user object. While looking into the response object, there is not sendMFACode function. Further, seeing the following: https://d.pr/i/gmzi0E which exists multiple times throughout the response object:

"TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them"

I'm not sure if the error above is relative to the "TypeError: user.sendMFACode is not a function" error as I'm not sure where the sendMFACode is supposed to live.

The Auth.confirmSignIn function looks like this: https://gist.github.com/grgaortiz/9a9dacefe1deca932396beea34ebebf2. You can see it trying to call the sendMFACode function from the response "user" object.

**Comment by raisiqueira** [comment]
Same with Amplify 1.1.10 on the `Auth.confirmSignIn(username, code)`.

```
TypeError: user.sendMFACode is not a function
    at Auth.js:747
    at tryCallTwo (core.js:45)
    at doResolve (core.js:200)
    at new Promise (core.js:66)
    at AuthClass.confirmSignIn (Auth.js:746)
    at AuthProvider._this.confirmLogin (Provider.js:177)
    at Object.onPress (Login.js:101)
    at Object.touchableHandlePress (TouchableOpacity.js:212)
    at Object._performSideEffectsForTransition (Touchable.js:784)
    at Object._receiveSignal (Touchable.js:698)
```

**Comment by BarryBuitelaar** [comment]
I also have the same error. Is there already a solution?

**Comment by tmackness** [comment]
Wow, I can not believe this issue has been around since Aug 2018 and still not fixed.

**Comment by sagenate24** [comment]
I am having this same issue. I am passing the user object returned by ```Auth.signIn()``` as the first parameter in ```Auth.confirmSignIn(user, "123456", "SMS_MFA")```. but yet that user object still does not have the ```sendMFACode``` function.

Anyone still having issues with this?
```"@aws-amplify/auth": "^1.2.23",```

**Comment by elorzafe** [comment]
I usually see this problem when using the `username` as first argument instead of the user that is returned from `Auth.signIn`

```javascript
       const user = await Auth.signIn(username, password);
        if (user.challengeName === 'SMS_MFA' ||
            user.challengeName === 'SOFTWARE_TOKEN_MFA') {
            // You need to get the code from the UI inputs
            // and then trigger the following function with a button click
            const code = getCodeFromUserInput();
            // If MFA is enabled, sign-in should be confirmed with the confirmation code
            const loggedUser = await Auth.confirmSignIn(
                user,   // Return object from Auth.signIn()
                code,   // Confirmation code  
                mfaType // MFA Type e.g. SMS_MFA, SOFTWARE_TOKEN_MFA
            );
        }
```

**Comment by mtimbs** [comment]
I'm also running into this issue with Vuex. The issue with Vuex/Redux is you are serialising the response when putting it in state. This means you only get the user data and none of the methods on .__proto__ (which is where confirmSignIn is accessed).

The Amplify library also doesn't have an easy way to new up a CognitoUser from the user data that can be serialised in state from what I can see. It looks like you won't be able to use Redux for your Auth flow and will have to use local component state that doesn't need serialisation
