### ISSUE TITLE
React-Native starter project: Auth.signIn fails only in Release Mode

### ISSUE THREAD

**Issue by ladybugcollab** [aws-amplify/amplify-js#1414]
Do you want to request a feature or report a bug?

Report a potential bug

What is the current behavior?

I am trying to get aws-mobile-react-native-starter running. I have things working in Debug mode, but when I switch to release mode, the call to Auth.signIn fails with message "Sign in failed". However, when I kill the app and reopen it, the user is authenticated! This only happens in release mode and I am having trouble logging the error to see if there is more information about the exception.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

What is the expected behavior?

Sign in should not fail.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

Here are my dependencies:

```
"dependencies": {
    "amazon-cognito-identity-js": "1.31.0",
    "aws-amplify": "^0.2.4",
    "aws-amplify-react-native": "^0.2.3",
    "babel-preset-es2015": "^6.24.1",
    "buffer": "^5.0.7",
    "mime-type": "^3.0.5",
    "path": "^0.12.7",
    "prop-types": "^15.6.0",
    "react": "16.4.1",
    "react-devtools": "^2.5.0",
    "react-native": "0.56.0",
    "react-native-calendars": "^1.19.4",
    "react-native-elements": "^0.19.1",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-uuid": "^1.4.9",
    "react-native-vector-icons": "^4.3.0",
    "react-navigation": "^2.9.3",
    "rn-prompt": "^1.0.3"
  },
```

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

I don't think this applies to RN application.

**Comment by powerful23** [comment]
@ladybugcollab can you update to use the latest version of `aws-amplify-react-native`. And you don't need to install `aws-amplify` or `amazon-cognito-identity-js`. Also could you try `react-native log-android` to get the log info?

**Comment by ladybugcollab** [comment]
Thank you. Upgrading `aws-amplify-react-native` seems to have fixed the issue.
