### ISSUE TITLE
'no userpool' error in both android and IOS.

### ISSUE THREAD

**Issue by DIPANSHU61** [aws-amplify/amplify-js#1417]
Hello guys,

I have use below mention version.
"react-native": "0.56.0",
"react-native-aws-cognito-js": "0.0.7",
"react": "16.4.1",

Please help me.

**Comment by mlabieniec** [comment]
not familiar with the react-native-aws-cognito-js library, but you might want to post this issue there.
https://github.com/AirLabsTeam/react-native-aws-cognito-js
