### ISSUE TITLE
npm ERR!

### ISSUE THREAD

**Issue by roghib** [aws-amplify/amplify-js#1418]
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:

**Comment by manueliglesias** [comment]
Hi @roghib 

Can you provide some more details?

- What were you trying to do?
- Which environment?
- Which npm package in this repo?

**Comment by roghib** [comment]
$ npm install aws-amplify --save

SyntaxError: Unexpected end of JSON input while parsing near '...el-loader":"^7.1.2","'
process._tickCallback (internal/process/next_tick.js:188:7)

Windows_NT 10.0.17134
node v8.11.3
npm  v6.3.0

**Comment by mlabieniec** [comment]
This looks like an npm issue, seems as though clearing cache may fix it as referenced here:
https://github.com/npm/npm/issues/19072
