### ISSUE TITLE
Resending verification link in cognito ?

### ISSUE THREAD

**Issue by Private-SO** [aws-amplify/amplify-js#1420]
HI,

I have scenario like this in cognito :

When the user has entered the credentials but didn't confirm it , then it will be saved as unconfirmed in the cognito. So, unless the user confirms the link it will be in unconfirmed state in cognito . For this i had used `Auth.resendSignUp`  API but after usage of this API i got an error saying that `LIMITEXCEEDEDEXCEPTON` . But `Auth.signup` API is working fine without any error. 

My Question :

Is there any limit for `Auth.resendSignUp` API ? If it is , How much ?

How long the confirmation link is active ?

Does `Auth.forgotpassword` API's verification can be done by sending a link rather than a code ?

Does Amplify has `adminResetUserPassword` API ? Usually the `adminResetUserPassword` API will reset the user password and also send an email with confirmation code. What i want is it need to reset the password but should not send the confirmation code. Is there any property in the API to change to achieve that ?

Any help is appreciated 
Thanks

**Comment by mlabieniec** [comment]
For limits:
https://docs.aws.amazon.com/cognito/latest/developerguide/limits.html

The verification code/link is valid for 24 hours:
https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-email-phone-verification.html

For forgot password, the confirmation currently supported is code:
https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ForgotPassword.html

@yuntuowang do you have insight as to if this is in the pipeline for the service? 

Currently amplify does not have admin user functionality but this is in our roadmap. The cognito SDK directly does support this which you can drill down and use via Amplify directly in these cases.

**Comment by Yaswanth-C** [comment]
Thanks @mlabieniec `The cognito SDK directly does support this which you can drill down and use via Amplify directly in these cases.` You mean the `adminResetUserPassword` in cognito SDK supports resetting password and without sending you a code ?

**Comment by mlabieniec** [comment]
No, what i mean is this API, the admin functionality, in general is not something that is currently supposed via Amplify, it IS supported via the Cognito SDK directly. See discussion on this here:
https://github.com/aws-amplify/amplify-js/issues/1213

**Comment by mlabieniec** [comment]
Got it, I'm not aware there is that feature, @yuntuowang do you know if this is something that is possible with the API, otherwise can you record as a feature request.

**Comment by malinda1986** [comment]
@Private-SO Did you find a way to resend the verification link, not the " CODE"

**Comment by jordanranz** [comment]
@malinda1986 This request is included in the following RFC:
https://github.com/aws-amplify/amplify-cli/issues/766
