### ISSUE TITLE
More informations about the PubSubOptions please!

### ISSUE THREAD

**Issue by XCarle** [aws-amplify/amplify-js#1421]
Hi guys,

the only informations we get about the PubSubOptions documentation are :
`
aws_pubsub_region: 'eu-west-1',
aws_pubsub_endpoint: '',
`
The informations we can get from the code is : 
`
export interface PubSubOptions {
    [key: string]: any;
}
`

May you provide a list of the configurable options for the PubSub mecanism?

**Comment by jordanranz** [comment]
aws_pubsub_region and aws_pubsub_endpoint are currently the only two options supported.
