### ISSUE TITLE
Master branch amazon-cognito-identity.js is minified, probably shouldn't be

### ISSUE THREAD

**Issue by aaronseatsmart** [aws-amplify/amplify-js#1423]
Do you want to request a feature or report a bug?

_Bug_

What is the current behavior?

_In master branch, the file /packages/amazon-cognito-identity-js/dist/amazon-cognito-identity.js Is minified, and probably shouldn't be._ 

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

What is the expected behavior?

_That amazon-cognito-identity.js would be unminified for developers and users of this repo to be able to look at the code in a human readable way. amazon-cognito-identity.min.js already exists in the repo._

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

_This looks to have been pushed to master recently. A few commits ago the file was not minified._

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by powerful23** [comment]
@aaronseatsmart the build files in the github repo is not correctly updated with the latest version. We are going to remove those files in the recent days.
