### ISSUE TITLE
API, graphqlOperation, AppSync

### ISSUE THREAD

**Issue by pjay79** [aws-amplify/amplify-js#1430]
First of all, I really think the work done on AWS Amplify is amazing, thank you.

But i'm also a bit stuck with using API with graphql, so any help would be appreciated.

I am using AWS Amplify with Cognito User Pools for authentication. I have user sign up / sign in / sign out all working nicely. I have also enabled AppSync with some basic queries and mutations and have a User table setup. When the user signs up for the first time I want to add them to the User table. I am trying to use AWS Amplify API with graphqlOperation to run the getUser query and createUser mutation, but i am running into troubles... here is some of the code to get context...

GetUser.js

```
export default `
  query getUser($id: ID!) {
    getUser(id: $id) {
      id
      username
    }
  }
`;

```

CreateUser.js
```
export default `
  mutation createUser($id: ID!, $username: String!) {
    createUser(input: { id: $id, username: $username }) {
      id
      username
    }
  }
`;
```

SignIn.js
```
import Auth from '@aws-amplify/auth';
import Amplify from '@aws-amplify/core';
import API, { graphqlOperation } from '@aws-amplify/api';
import GetUser from '../graphql/queries/GetUser';
import CreateUser from '../graphql/mutations/CreateUser';

 signIn = async () => {
    const { username, password } = this.state;
    const { navigation } = this.props;
    try {
      this.setState({ loading: true, error: '' });
      if (username && password) {
        await Auth.signIn(username, password);
        const currentUser = await Auth.currentAuthenticatedUser();
        console.log(currentUser);

        const userId = currentUser.signInUserSession.accessToken.payload.sub;
        const user = currentUser.signInUserSession.accessToken.payload.username;
        console.log(`id: ${userId} username: ${user}`);

        const authenticatedUser = await API.graphql(graphqlOperation(GetUser, { id: userId }));
        console.log(authenticatedUser);

        if (!authenticatedUser.data.getUser) {
          await API.graphql(graphqlOperation(CreateUser, { id: userId, username: user }));
        }
        navigation.navigate('App');
      } else {
        this.setState({ loading: false, error: 'Complete missing fields' });
      }
    } catch (error) {
      this.setState({ loading: false, error });
      console.log(error);
    }
  };
```
I am getting errors from this line:

`const authenticatedUser = await API.graphql(graphqlOperation(GetUser, { id: userId }));`

**

> Invariant Violation: Objects are not valid as a React child (found: object with keys {data, errors}). If you meant to render a collection of children, use an array instead.

**

I have tried adding the following to SignIn.js without any change, not sure if this is necessary given the aws-exports has the graphql details already anyway:

```
Amplify.configure({
  API: {
    graphql_endpoint:
      'endpoint_url',
  },
  graphql_headers: async () => {
    const { idToken } = await Auth.currentSession();
    return { Authorization: idToken.jwtToken };
  },
});
```

I have also changed the API call to look like this:

```
await API.graphql(graphqlOperation(GetUser, { id: userId }))
          .then(response => console.log(`Authenticated user: ${response}`))
          .catch(error => console.log(error.message));
```

This gives me the following error:

**

> In this environment the sources for assign MUST be an object. This error is a performance optimization and not spec compliant.

**
I'm sorry in advance if this is something really simple that i have completely missed!!

Kind Regards,

PJ.

**Comment by totaland** [comment]
Have you been able to solve this issue man?
