### ISSUE TITLE
Latest Amplify 1.0.5 and Apollo 2.3.8 / AppSync 1.3.3 can't coexist?

### ISSUE THREAD

**Issue by dguisinger** [aws-amplify/amplify-js#1435]
I have an Angular 6 application with Apollo 2.3.8 and AppSync 1.3.3.  I recently tried to add AWS Amplify and am getting:

ERROR in node_modules/@aws-amplify/api/node_modules/@types/zen-observable/index.d.ts(32,14): error TS2300: Duplicate identifier 'Subscriber'.
node_modules/@types/zen-observable/index.d.ts(33,14): error TS2300: Duplicate identifier 'Subscriber'.

Are these libraries not compatible?  I get the following when I look for @types/zen-observable in my node_modules....
npm ls @types/zen-observable
├─┬ apollo-client@2.3.8
│ └── @types/zen-observable@0.8.0
├─┬ aws-amplify@1.0.5
│ ├─┬ @aws-amplify/api@1.0.5
│ │ └── @types/zen-observable@0.5.4
│ └─┬ @aws-amplify/pubsub@1.0.4
│   └── @types/zen-observable@0.5.4
└─┬ aws-appsync@1.3.3
  └─┬ apollo-client@2.3.7
    └── @types/zen-observable@0.8.0  deduped

**Comment by manueliglesias** [comment]
Hi @dguisinger 


I am having trouble recreating the issue, can you provide some more details? or even better, a codesandbox.io or similar showing the problem? (e.g. I did this https://codesandbox.io/s/ww6524ozk)

This is my `npm ls @types/zen-observable`:
```
186590cffc5d:my-app manuelig$ npm ls @types/zen-observable
my-app@0.0.0 /private/var/folders/t2/9mln5kt56vlclhj4d7b6sjjn896kfm/T/tmp.HznhRWg7/my-app
├─┬ apollo-client@2.3.8
│ └── @types/zen-observable@0.8.0
├─┬ aws-amplify@1.0.5
│ ├─┬ @aws-amplify/api@1.0.5
│ │ └── @types/zen-observable@0.5.4
│ └─┬ @aws-amplify/pubsub@1.0.4
│   └── @types/zen-observable@0.5.4  deduped
└─┬ aws-appsync@1.3.3
  └─┬ apollo-client@2.3.7
    └── @types/zen-observable@0.8.0
```

and my `main.ts` (from `ng new my-app`)
```typescript
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

import Amplify from 'aws-amplify';
import AWSAppSyncClient, { AUTH_TYPE } from 'aws-appsync';
import gql from 'graphql-tag';

if (environment.production) {
  enableProdMode();
}

Amplify.configure({});

(() => {
  const client = new AWSAppSyncClient({
    url: 'https://xxxxxxxxxxxxxxxxxxxxxxxxxx.appsync-api.us-east-1.amazonaws.com/graphql',
    region: 'us-east-1',
    auth: {
      type: AUTH_TYPE.API_KEY,
      apiKey: 'da2-xxxxxxxxxxxxxxxxxxxxxxxxxx',
    },
  });

  client.subscribe({
    query: gql`query {__schema { types { name } }}`
  }).subscribe({
    next: console.log,
  });
})();

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.log(err));

```

**Comment by dguisinger** [comment]
Odd, I tried to reproduce it in CodeSandbox like you suggested and couldn't, then I turned back to my code.... and it was no longer occurring even though I hadn't touched it since copying and pasting the error last night, and had spent several hours over multiple days trying to figure out what was going on....

Guess its working now... and I am beyond confused

**Comment by marcoturi** [comment]
Same issue with the following output. Using yarn resolve the issue.
```
npm ls @types/zen-observable       

├─┬ apollo-client@2.4.6
│ └── @types/zen-observable@0.8.0 
├─┬ aws-amplify@1.1.13
│ ├─┬ @aws-amplify/api@1.0.23
│ │ └── @types/zen-observable@0.5.4 
│ └─┬ @aws-amplify/pubsub@1.0.19
│   └── @types/zen-observable@0.5.4 
└─┬ aws-appsync@1.7.0
  └─┬ apollo-link-retry@2.2.5
    └── @types/zen-observable@0.8.0  deduped
```

**Comment by rogerheykoop** [comment]
I am getting the same issue when simply building https://github.com/aws-samples/aws-amplify-ionic-sample.git

ionic build
> ng run app:build

Date: 2018-12-29T21:50:10.491Z
Hash: 56dd478986546b458fb4
Time: 6212ms
chunk {main} main.js, main.js.map (main) 651 bytes [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 706 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 57.5 kB [initial] [rendered]

ERROR in node_modules/@aws-amplify/api/node_modules/@types/zen-observable/index.d.ts(32,14): error TS2300: Duplicate identifier 'Subscriber'.

[ERROR] An error occurred while running subprocess ng.

**Comment by rcwestlake** [comment]
@manueliglesias I am also seeing the issue except with a React application:

aws-amplify: `1.1.10`
aws-appsync: `1.7.0`
typescript: `3.1.6`

The issue arose when I added `aws-appsync` to my project. 

This is the error: `node_modules/@aws-amplify/api/node_modules/@types/zen-observable/index.d.ts
(32,14): Duplicate identifier 'Subscriber'.`

And when I run `npm ls @types/zen-observable`, these are the results:
```apollo-client@2.4.7
│ └── @types/zen-observable@0.8.0 
├─┬ aws-amplify@1.1.10
│ ├─┬ @aws-amplify/api@1.0.21
│ │ └── @types/zen-observable@0.5.4 
│ └─┬ @aws-amplify/pubsub@1.0.18
│   └── @types/zen-observable@0.5.4 
└─┬ aws-appsync@1.7.0
  ├─┬ apollo-client@2.4.6
  │ └── @types/zen-observable@0.8.0  deduped
  └─┬ apollo-link-retry@2.2.5
    └── @types/zen-observable@0.8.0  deduped```

**Comment by jayalog** [comment]
Any solutions for this issue ?
