### ISSUE TITLE
Custom UI withAuthenticator

### ISSUE THREAD

**Issue by wdm954** [aws-amplify/amplify-js#1436]
I've created a custom **SignIn** component and I'm attempting to use it as documented here:
https://aws-amplify.github.io/amplify-js/media/authentication_guide#customize-withauthenticator

I'm assuming once **Auth.signIn** is successful the library will render **ConfirmSignIn** however this doesn't happen. It just stays on the **SignIn** component. I know the call was successful because I console.log the success response and I received a confirmation code via SMS.

My relevant code is below. Am I missing something? The docs for this section are pretty sparse.

    import { ConfirmSignIn, ConfirmSignUp, ForgotPassword, SignUp, VerifyContact, withAuthenticator } from 'aws-amplify-react';
    import SignIn from './SignIn';

    import Amplify from 'aws-amplify';
    import aws_exports from './aws-exports';
    Amplify.configure(aws_exports);

    class App extends Component {...}

    export default withAuthenticator(App, false, [
        <SignIn/>,
        <ConfirmSignIn/>,
        <VerifyContact/>,
        <SignUp/>,
        <ConfirmSignUp/>,
        <ForgotPassword/>
    ]);

-------

    class SignIn extends Component {
        handleSubmit = event => {
            event.preventDefault();
            const { email, password } = event.target;
            Auth.signIn(email.value, password.value)
            .then(response => {
                console.log('Auth.signIn success', response);
            });
        }
        render() {
            return (
                <form onSubmit={this.handleSubmit}>
                    <input type="email" name="email"/>
                    <input type="password" name="password"/>
                    <button type="submit">Sign In</button>
                </form>
            );
        }
    }

**Comment by hannahbennett27** [comment]
Hi wdm954 - have you made any progress on your query? I'm working on a near-enough-identical example. 
withAuthenticator works through its modals and renders the app once logged in when using the default settings, but seem to stay static when the log in etc components are personalised as per the docs. I'd appreciate feedback if you've had any success- Thank you!

**Comment by wdm954** [comment]
@hannahbennett27 Yes, I've made progress! Initially I wasn't extending Amplify's `SignIn` class.

https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Auth/SignIn.jsx

I copied the rendered portion from the above linked class and made my desired changes. My custom `SignIn` component now looks more like this:

    import { SignIn } from 'aws-amplify-react';

    class MySignIn extends SignIn {
        showComponent(theme) {
            ...
            return (
                <FormSection theme={theme}>
                    ...
                </FormSection>
            );
        }
    }

Next, once I removed the `hide` code from the `showComponent` method the auth flow started to work as desired.

    showComponent(theme) {
        const { authState, hide = [], federated, onStateChange } = this.props;
        /* removed...
        if (hide && hide.includes(SignIn)) { return null; }
        const hideSignUp = hide.some(component => component.name === 'SignUp')
        const hideForgotPassword = hide.some(component => component.name === 'ForgotPassword')gotPassword = hide.some(component => component.name === 'ForgotPassword')
        */

Disclaimer: I haven't deep-dived into their code related to `hide` so not sure if this is the best solution.

If you'd like to change anything in the call to the `Auth` api you can override their `signIn` method. Copy `signIn() { ... }` into your component and change what you'd like. I found this useful when customizing the `SignUp` component to change username to email.

When you see a call to `changeState` this is how they're triggering which component to render:

`this.changeState('confirmSignIn', user);`

This is a call to `handleStateChange` which is passed down through props from the `Authenticator ` component.

https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Auth/Authenticator.jsx

Also, see `AuthPiece` since `SignIn` etc... extends this component.

https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Auth/AuthPiece.jsx

**Comment by hannahbennett27** [comment]
@wdm954, thank you!

**Comment by jonasao** [comment]
@wdm954 
You do not need co remove the `hide` code from `showComponent()`, you will just have to replace the name of the SignIn class with the name of your own class, e.g. "CustomSignIn":
```
 showComponent(theme) {
        console.log('props: ', this.props);
        const { authState, hide = [], federated, onStateChange } = this.props;
        if (hide && hide.includes(CustomSignIn)) { return null; }
        const hideSignUp = hide.some(component => component.name === 'SignUp');
        const hideForgotPassword = hide.some(component => component.name === 'ForgotPassword');
```

**Comment by kashgupta** [comment]
@wdm954 When I extend the SignIn class, none of the functions or imports are inherited. Could you provide a full sample of your MySignIn.js file? I'm having trouble reproducing how you extended the SignIn class.

**Comment by grudelsud** [comment]
hey @kashgupta if it's of any help, I've created a Gist with my SignIn class extension using Material UI, and working fine for me 😄 you can find it [here](https://gist.github.com/grudelsud/3a944749acdb38ff1d009a8b9fb2d8ba) hope it helps!

**Comment by wdm954** [comment]
@kashgupta Here is a basic example. I've created a sandbox where you can see this in action: https://codesandbox.io/s/k2jl5p6vrr

    import { SignIn } from "aws-amplify-react";

    class MySignIn extends SignIn {
        componentDidMount() {
            console.log("MySignIn mounted");
            console.log(this.onKeyDown);
            console.log(this.checkContact);
            console.log(this.showComponent);
        }
    }

If you view the console you'll see we're able to log the methods that exist in the `SignIn` component.

https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Auth/SignIn.jsx

**Comment by kashgupta** [comment]
Thanks @grudelsud  this is helpful!
@wdm954 Even using your sandbox, I am still confused how to render the UI. I understand that we have access to the "showComponent" method, but I have had zero success getting anything to render in the MySignIn object. Even if it's just a "<div> hello world </div>" and I'm not sure how to get the MySignIn object to render.

**Comment by wdm954** [comment]
@kashgupta you stated that none of the functions or imports are inherited so I was showing that they were in my example.

`showComponent` is the method you'll use to render. If you look at the `AuthPiece` component you'll see the logic behind it since `SignIn` extends `AuthPiece`.

https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Auth/AuthPiece.jsx

@jonasao comment above should also be helpful: https://github.com/aws-amplify/amplify-js/issues/1436#issuecomment-428556455

**Comment by marioarizaj** [comment]
Hi @wdm954 , So if we override the showComponent() method, the sign in method is inherited? 
What about custom sign up? By looking at the SignIn.jsx code the create account button is only showed when the default sign up form is not hidden. But if a custom sign up is used the default will be hidden so the create account link will not show. Did you find any solution for this?

**Comment by patoncrispy** [comment]
I'm looking to do the same thing (override UI components) but I feel that the concept of overriding components and the appropriate methodologies to do so are not documented well enough (if at all - I haven't seen anything on this). The only reason I'm aware this is possible or advisable is because of [this article](https://blog.kylegalbraith.com/2018/11/29/how-to-easily-customize-the-aws-amplify-authentication-ui/). To his credit, Kyle actually does a pretty good job of explaining things.

As this work is quite involved and relatively complex, I think it would be great if someone from the Amplify team could document the best practices for doing this in order to avoid potential pitfalls. As this deals with security, I feel leaving it up to the community to dissect source code is only going to lead to problems and vulnerabilities (and more GitHub Issues).

**Comment by mlabieniec** [comment]
@patoncrispy this is part of our active backlog and being worked on right now (in terms of better customization options for components, documentation, and more). Thanks for the feedback we'll make sure to consider all these points in the work being done.

**Comment by jordanranz** [comment]
FYI, we have started an RFC discussion for a proposed Amplify UI Component refactor to increase customizability and flexibility for our components. Please feel free to add any additional comments to the following issue:

https://github.com/aws-amplify/amplify-js/issues/3279

**Comment by gkpty** [comment]
Hey Guys,

Im trying to customize my withauthenticator as follows:

```
const MyTheme = {
  googleSignInButton: { backgroundColor: "red", borderColor: "red" },
  button: { backgroundColor: "green", borderColor: "red" },
  signInButtonIcon: { display: "none" }
};

const signUpConfig = {
  header: 'My Customized Sign Up',
  hideAllDefaults: true,
  signUpFields: [
    {
      label: 'Email',
      key: 'email',
      required: true,
      displayOrder: 1,
      type: 'string'
    },
    {
      label: 'Username*',
      key: 'username',
      required: true,
      displayOrder: 1,
      type: 'string'
    },
    {
      label: 'Password',
      key: 'password',
      required: true,
      displayOrder: 2,
      type: 'password'
    },
  ],
};

export default withAuthenticator(App, false, [
<SignIn/>,
  <SignUp/>,
  <ForgotPassword/>,
  <RequireNewPassword/>
], null, MyTheme, {signUpConfig});
```

It appears that i can only either pass the auth components array (& theme) or the signUpConfig object but not both.

Any idea on how i can do both?

Thanks!!

**Comment by kristianmandrup** [comment]
I'm having problems when using TypeScript. I'm told that with `render: void` it is not a valid JSX element and a component extending SignIn cannot be used as a JSX component.

I can see that `Signin` component extends `AuthPiece`:

```ts
export default class AuthPiece<Props extends IAuthPieceProps, State extends IAuthPieceState> extends React.Component<Props, State> {
    _validAuthStates: string[];
    _isHidden: boolean;
    inputs: any;
    phone_number: any;
    constructor(props: any);
    componentDidMount(): void;
    getUsernameFromInput(): any;
    onPhoneNumberChanged(phone_number: any): void;
    renderUsernameField(theme: any): JSX.Element;
    getUsernameLabel(): {
        [UsernameAttributes.EMAIL]: string;
        [UsernameAttributes.PHONE_NUMBER]: string;
        [UsernameAttributes.USERNAME]: string;
    }[Props["usernameAttributes"]];
    usernameFromAuthData(): string;
    errorMessage(err: any): any;
    triggerAuthEvent(event: any): void;
    changeState(state: any, data?: any): void;
    error(err: any): void;
    handleInputChange(evt: any): void;
    render(): void;                                                              // WHY void!?
    showComponent(theme: any): void;
}
```

Please advice how to resolve this type error.

```sh
JSX element type 'CustomSignIn' is not a constructor function for JSX elements.
  Types of property 'render' are incompatible.
    Type '() => void' is not assignable to type '() => ReactNode'.
      Type 'void' is not assignable to type 'ReactNode'.
```

```ts
export class CustomSignIn extends SignIn {
  constructor(props: any) {
    super(props);
    this._validAuthStates = ["signIn", "signedOut", "signedUp"];
  }

  showComponent(theme: any) {
    return (
      <div className="mx-auto w-full max-w-xs">
      </div>
  )
}
}
```

```ts
class AppWithAuth extends React.Component {
  constructor(props: any, context: any) {
    super(props, context);
  }

  render() {
    return (
      <div>
        <Authenticator hide={[SignIn]} amplifyConfig={config}>
          <CustomSignIn /> .   <=== complains that this is not a valid class to be used as JSX tag
          <App />
        </Authenticator>
      </div>
    );
  }
}
```

**Comment by kristianmandrup** [comment]
If I change the render return type to `JSX.Element` it works :)

```ts
  // ...
  render(): JSX.Element;
  showComponent(theme: any): void;
}
```

Please fix this. Cheers!

**Comment by kristianmandrup** [comment]
I  found another way around it:

```tsx
export class CustomSignIn extends SignIn {
  constructor(props: any) {
    super(props);
    this._validAuthStates = ["signIn", "signedOut", "signedUp"];
  }

  // @ts-ignore
  render(): any {
    return super.render();
  }

  /// ...
}
```

**Comment by ashika01** [comment]
Hi, we have introduced new UI components for authenticator. For more information check [these docs](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react). These components bring in parity among all frameworks we support.

Also, we have introduced completely customizable UI components using a functionality called `slots` which could address this feature request - https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#customization

If you have troubles with the new UI components or any suggestions for enhancement. Please open an new issue/feature request.
