### ISSUE TITLE
photopicker component imports CognitoIdentify client unnecessarily

### ISSUE THREAD

**Issue by srchase** [aws-amplify/amplify-js#1442]
Hello,

An issue has been opened on the JavaScript SDK: [https://github.com/aws/aws-sdk-js/issues/2192](https://github.com/aws/aws-sdk-js/issues/2192)

Specifically, the photopicker component is causing issues when importing the CognitoIdentity client.

https://github.com/aws-amplify/amplify-js/blob/8f6c448b8f231cf9ba93a314730a81246cd5f7c5/packages/aws-amplify-angular/src/components/storage/photo-picker-component/photo-picker.factory.ts#L8

I don't believe that component needs to import the client.

I'm happy to submit a PR if it would be helpful to correct this issue.

**Comment by AllanFly120** [comment]
Basically in [aws-sdk v2.287.0](https://github.com/aws/aws-sdk-js/commit/67081dcf5c07bd26cd06e9262149b522430c5e12), the unused typings are removed from the model, which contains the `String` type referred here. You can just remove the `String` import and instead use normal `string` types here.

**Comment by haverchuck** [comment]
The { String } import has been removed from `photo-picker-factory.ts`.

**Comment by ShaneCotter** [comment]
I am still getting this error even though there is no string import in my photo-picker-factory.ts file which was generated.

**Comment by appwerkz** [comment]
Yes, I am getting the same error too.

ERROR in node_modules/aws-amplify-angular/lib/components/storage/photo-picker-component/photo-picker.factory.d.ts(3,10): error TS2305:
Module '"{hard coded path}/aws-activities/aws-amplify-ionic/aws-amplify-ionic-sample/node_modules/aws-sdk/clients/cognitoidentity"' has no exported member 'String'.

**Comment by harsh594** [comment]
I replaced `import { String } from 'aws-sdk/clients/cognitoidentity';` with  `import * as String from 'aws-sdk/clients/cognitoidentity';` and it works for me now.
