### ISSUE TITLE
Storage.put should accept Streams outside of Node environments

### ISSUE THREAD

**Issue by kidcosmic** [aws-amplify/amplify-js#1446]
Do you want to request a feature or report a bug?
This is a feature and a bug i believe.

What is the current behavior?

Storage.put fails in react native when passing in a stream as the file object. Error:
```
StorageClass - error uploading: Error: Unsupported body payload object
    at ManagedUpload.self.fillQueue
```

What is the expected behavior?

Storage uploads the file.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

```
"aws-amplify": "^1.0.5",
"aws-amplify-react-native": "^1.0.5",
"react-native": "^0.56.0",
```

**Comment by manueliglesias** [comment]
Hi @kidcosmic 

The S3 implementation of the Storage category uses the aws-sdk S3 client to do the upload by setting the `Body` param. According to the [aws-sdk S3 client docs for putObject](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property), this param accepts the following types:

```
Body — (Buffer, Typed Array, Blob, String, ReadableStream)
  Object data.
```

With that being said, my suggestion would be to try to get a Buffer from your stream

From [Node.js docs on Stream](https://nodejs.org/api/stream.html#stream_buffering):
> Both Writable and Readable streams will store data in an internal buffer that can be retrieved using writable.writableBuffer or readable.readableBuffer, respectively.

Let us know how it goes

**Comment by kidcosmic** [comment]
Won't work out without loading the entire file into memory. You're right about this being an aws-sdk issue. I'll move this there. Cheers!

**Comment by kidcosmic** [comment]
So after chatting

**Comment by joebernard** [comment]
@kidcosmic I know it's old but did you find a resolution to this?
