### ISSUE TITLE
Websockets reconnection behaviour

### ISSUE THREAD

**Issue by yarax** [aws-amplify/amplify-js#1448]
I've just found out, that according to https://github.com/aws-amplify/amplify-js/blob/400b1cb2f393d33efe5aa824f730b3155a2f9822/packages/pubsub/src/Providers/MqttOverWSProvider.ts#L73 doesn't handle loosing of websocket connection.

So using GraphQL subscriptions we don't have any possibility to handle reconnection. 
Or I'm wrong and there is any way to do it?

**Comment by manueliglesias** [comment]
Hi @yarax 

It is currently not supported, I am labeling this as a feature request so we can track it, thanks!

**Comment by felixis-1** [comment]
Hi @manueliglesias,

This feature is somewhat critical for us and may also be the reason for #1283. Do you think that might be the case? Also, is there any timeline available for this to be fixed so that we can plan our system accordingly.

Also, if there can be a way to detect that the subscription has ended, we can manually resubscribe to it. But I did not find any such support in the documentation. Can something be done to achieve this?

Thanks.

**Comment by elorzafe** [comment]
The pr that I am sending can give a solution for reconnection and handle network errors on the observable like this.

```
 var subscription;

  subscribe = (retrying = 0) => {
    console.log('subscribing in...', retrying)
    setTimeout(() => {  
      const observable = API.graphql(
        graphqlOperation(SubscribeToEventComments, { eventId: eventid })
      );
      subscription = observable.subscribe({
        next: (eventData) => {
          retrying = 0;
          console.log(eventData)
        },
        error: (data) => {
          const { errors } = data;
          if (errors && errors.find(error => error.message === 'Network Error')) {
            if (retrying === 0) {
              retrying = 50
            }
            this.subscribe(retrying * 2)
          }
        },
        complete: (data) => console.log('completed', data)
      });
    }, retrying)
  };

  disconnect = () => {
    console.log('disconnect', subscription);
    if (subscription && typeof subscription.unsubscribe === 'function') {
      subscription.unsubscribe()
    }
  }

  connect = () => {
    this.disconnect();
    this.subscribe(0);
  }
```

**Comment by elorzafe** [comment]
Hi @felixis-1 PR #1698 Is already published. Let me know if you need any help on this

**Comment by felixis-1** [comment]
Hi @elorzafe, I am using version 1.1.3 of aws-amplify. With this version, using the example above always goes into the error block within the observable with the error "Network Error". However, my queries and mutations on that same screen are running fine. What might be missing in getting this subscription past this problem?

**Comment by elorzafe** [comment]
@felixis-1 can you paste a code snippet?

**Comment by rogueturnip** [comment]
It seems that this PR fixed the websockets problem with API but not PubSub. When I use the above with PubSub I don't get any error logged or a reconnect.
