### ISSUE TITLE
Feature Request: Storage.put accept {uri} for React Native

### ISSUE THREAD

**Issue by lightchaser411** [aws-amplify/amplify-js#1453]
Currently, entire files have to be loaded into memory in order to upload a file in React Native.

React Native has added support for Files/Blobs in `XMLHttpRequest` and `FormData` which allows for optimal memory usage with file uploads.

`XMLHttpRequest.send({uri, name, type})`
`FormData.add({uri, name, type})`

Since, amplify-js may want to fully support React Native, amplify can add support for React Native's file handling via wrapping aws-sdk-js's `S3.getSignedUrl` and leveraging XMLHttpRequest/FormData

Examples:

```
var xhr = new XMLHttpRequest();
xhr.open('PUT', this.url, true);
xhr.setRequestHeader('Content-Type', this.contentType); <=== video/mp4
xhr.setRequestHeader('Content-Range', 'bytes ' + this.offset + '-' + (end - 1) + '/' + this.filesize);
xhr.setRequestHeader('X-Upload-Content-Type', this.filetype);  <=== video/mp4

if (xhr.upload) {
  xhr.upload.addEventListener('progress', this.onProgress);
}
xhr.onload = this.onContentUploadSuccess_.bind(this);
xhr.onerror = this.onContentUploadError_.bind(this);
xhr.send({uri: this.file.path});  <=== file:///.....
```

```
let data = new FormData();
data.append('File', {
      uri:  source.path,
      type: source.type,
      name: source.name
});
var xhr = new XMLHttpRequest();
  xhr.open('PUT', this.url, true);
  //xhr.setRequestHeader('Content-Type', this.contentType);  
  //=== comment this, because it throw error 'multipart != video/mp4'
  //xhr.setRequestHeader('Content-Range', 'bytes ' + this.offset + '-' + (end - 1) + '/' + this.filesize);
  //=== comment this, because sending data size != filesize
  xhr.setRequestHeader('X-Upload-Content-Type', this.filetype);

  if (xhr.upload) {
    xhr.upload.addEventListener('progress', this.onProgress);
  }
  xhr.onload = this.onContentUploadSuccess_.bind(this);
  xhr.onerror = this.onContentUploadError_.bind(this);
  xhr.send(data); <==== FormData
```

**Comment by ngocketit** [comment]
Any update on this please? Currently, uploading a large video file (about 200MB) makes my app crash.

**Comment by CodySwannGT** [comment]
This would be a great feature

**Comment by sacrampton** [comment]
Hi @manueliglesias - we are also getting our app crashing when loading large files to S3. Is there any work around that you or anyone else can suggest that we can implement so that our app is not crashing. This is impacting our production customers so any inputs would be welcome.

**Comment by sacrampton** [comment]
Hi @manueliglesias  and anyone else that might be watching this issue.

As I mentioned, this is a production impacting issue in that the app is crashing with significant memory issues by using the Amplify Storage Framework for react native apps. Have not heard any options for an approved work around for this issue, so we are going to go forward with abandoning the Amplify Storage framework and directly implement the AWS S3 React Native libraries to deal with file uploads. To date this appears to be working. If anyone has any comments or experiences in going this route I'd appreciate hearing them.

**Comment by ericclemmons** [comment]
@sacrampton When looking into this, what is considered large enough to crash the app?  Does it need to be several GBs to exhaust memory?

@ngocketit mentions 200Mb, but that wasn't enough in my testing to crash the app.

But still, the proposed API (`Storage.put({ uri })`) makes sense to handle this issue.  The only consideration is exactly what this API will be since there likely isn't web-equivalent.

Until then, using the AWS SDK in the interim as you described is the best workaround for now. (Example of how others are doing it in the ecosystem: https://codedaily.io/tutorials/179/Upload-a-File-to-an-S3-Pre-Signed-URL-with-React-Native)

**Comment by sacrampton** [comment]
Hi @ericclemmons - I have an app that is used in industrial applications where network access may be good, intermittent, or non-existent. In the case of intermittent network access when we are getting photos banked up and the newer phones with larger phone sizes cause the issue - that after a while of usage the App would crash giving out memory errors in Crashlytics that we traced to this. Don't know that we could say how many GB - but after about 2hrs usage in an area with intermittent network access our users crash. That has disappeared now we went to AWS SDK.

**Comment by haolinj** [comment]
Hi, I would love Storage.put({ uri }) to be supported as well. 

But the xhr workaround described works in the meantime. Just want to point out you can sign the upload URL with the access key, secret key and session token from (as mentioned here https://github.com/aws-amplify/amplify-js/issues/337#issuecomment-367735416): 
```
Auth.currentCredentials()
  .then(credentials => {
    // access keys available on:
   const keys = Auth.essentialCredentials(credentials)
  })
```

**Comment by tannerabread** [comment]
Related #9736

**Comment by stocaaro** [comment]
The issue covers the same issue discussed in #9736, which has more recent details and engagement at this time. Closing this, preferring to focus the conversation to this other more active issue.

Closing as duplicate.

Thanks,
Aaron
