### ISSUE TITLE
New User Registration not working

### ISSUE THREAD

**Issue by rojagit** [aws-amplify/amplify-js#1461]
Do you want to request a feature or report a bug? Bug

What is the current behavior? New User Registration not working via app nor console

Following https://github.com/aws-samples/aws-serverless-appsync-loyalty, after the app starts I cannot register a new user even after all validations have passed.
I dont get any email or SMS
Then I created a user manually. I did get an email asking me to change password.
I entered a new pwd.
Then it did not accept new pwd during Sign-in
So I did a forgot pwd
Not only did I not get an email nor SMS, it is still asking for a code.
The app author told me its a higher-order issue and asked me to report it here.
I have tried many amplify starter apps - one or two of them successfully work with user registration.

Is Cognito with amplify ready for prime time at all ??

What is the expected behavior? Just register a user !

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions? Latest, and doing this in cloud9

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by rojagit** [comment]
I also set DEBUG mode, even though the core issue is on the cognito end, and it had no effect

Also, the user has "SMS MFA Status" Disabled, and even though the Pool has MFA enabled, it gives this error:

Cannot change the MFA setting when the user pool MFA is required. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: fec55583-a2f6-11e8-a2eb-7315f4a2b9c2)

------------------------------------

And this is another thing I had noticed even before, even though these two flags are set to true,  it is always ignored and keeps on asking for a CODE which I never get

email_verified | true
-- | --
phone_number_verified | true

**Comment by rojagit** [comment]
This app caused SNS overages from AWS. The registration DOES NOT EVEN WORK, and still you have managed to incur charges. Ridiculous. 

Apps like this should not be made starter apps for people like us who are just seeking to experiment with AWS to see if the services are viable for our products.

I have experimented with a handful of starter apps, some which work but are very basic, and others that dont, like this one, but this takes the cake for making me incur charges.

**Comment by rojagit** [comment]
ok nm the rant, I realized the error:

My cell phone # starts with 91 and when I do a user registration, the Cognito mechanism doesnt tell me 
it expects an international # and happily accepts my US # starting with a '#' and was sending SMSs to India !! (India intl. code is 91)

jeez...Cognito...please fix this !!

but app-wise, I still dont see any unicorn stuff, all I see is a react page saying do something with app.js

**Comment by mlabieniec** [comment]
@rojagit On the Amplify docs we do reference the need for the phone_number needing to be E.164 number convention in the Authentication Guide: https://aws-amplify.github.io/amplify-js/media/authentication_guide#sign-up

Also, the Cognito docs do reference cost for SMS messaging:
https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-mfa-sms-text-message.html

Let us know if you have any suggestions on improving the documentation to assist.

**Comment by rojagit** [comment]
While it's a fact that not many read or dig deep into documentation, (and you point to a comment in code, really ??  ) 'specially when coming from a HOI, Cognito / amplify or these starter-apps need to be more proactive in checking valid phone #s, and alerting developers to the fact that intl. SMS incurs charges and to maintain E.164 format which we in the US are NOT used to. This is a basic necessity IMO. Wasted much time and effort.
