### ISSUE TITLE
Cognito `UserNotConfirmedException` when calling `authenticateUser()`

### ISSUE THREAD

**Issue by n1te1337** [aws-amplify/amplify-js#1464]
Hi,

This is a behaviour I came across when testing the `amazon-cognito-identity-js` library, hoping someone else had a similar issue and can point me in the right direction.

**Do you want to request a feature or report a bug?**

Not sure.

**What is the current behavior?**

When calling `authenticateUser()` for a user that didn't confirm their email the `amazon-cognito-identity-js` library throws a `UserNotConfirmedException`. The problem is that the `UserNotConfirmedException` is thrown regardless of whether the supplied password is correct or not. This is causing a bit of an issue with the UX of the Login flow:

(the user signed up but didn't confirm their email)
1. The user goes to the Login page
2. The user enters the correct username (email) but an incorrect password
3. The user is redirected to the confirmation page
4. The user enters the code and confirms their email
5. The user is redirected back to the login page and enters the same details as in step 2
6. The user gets "Incorrect Username/Password" message 

**What is the expected behavior?**

Ideally, the library would return the incorrect username/password error before checking if the email is confirmed and only throwing the `UserNotConfirmedException` after entering correct credentials.

I found [this issue](https://github.com/amazon-archives/amazon-cognito-identity-js/issues/288) hinting that this (unfortunately) may be the intended behavior. 

My questing is, is there a way to validate password for a user that didn't confirm their email? If not, what UX flow are people using for this scenario?
Right now, the only thing I can think of is to either keep it as it is (which is a bit confusing), or to say in step 2 that their email needs to be confirmed and the password they supplied may or may not be correct (which is less than ideal).

Any feedback/pointers much appreciated.

Thanks.

**Comment by powerful23** [comment]
@n1te1337 this is an expected behavior of Cognito Service. From what I know there is no way to tell if the password is correct or not when the user is not confirmed.

**Comment by jordanranz** [comment]
Going to close this as it seems the question your answered. Please reopen if you have any further questions or concerns.

**Comment by alexrec22** [comment]
@jordanranz, @powerful23, I would appreciate if you could explain why this is the expected behaviour of Cognito. From what I see:

1. This behaviour reveals whether a username exists or not, which is less than ideal from a security standpoint.
2. This leads to a terrible UX as mentioned by @n1te1337. The user enters their credentials, validates the account, and is then told the credentials they entered at step 1 were actually wrong and have to be re-entered again.

Thanks.

**Comment by mynameisguy** [comment]
@jordanranz, @powerful23 has anything changed with this?
as both @n1te1337 and @alexrec22  mentioned this leads to a really bad UX.
I also can't think of a scenario in which it will be better to validate the user before requiring the right password...

**Comment by nzayatz14** [comment]
+1

**Comment by isotopeee** [comment]
Any updates?

**Comment by clehnert** [comment]
+1
