### ISSUE TITLE
Unknown error, the response body from fetch is: undefined

### ISSUE THREAD

**Issue by Aslamdesusa** [aws-amplify/amplify-js#1466]
When I am trying to login Getting this error 
Unknown error, the response body from fetch is: undefined

Here Is my code What I have done 

// console.log(request)
			const loginDetails = {
				Username: 'aslam17@navgurukul.org',
				Password: '*****************'
			}
			const authenticationDetails = new AmazonCogintoIdentity.AuthenticationDetails(loginDetails)

			const userDetails = {
				Username: 'aslam17@navgurukul.org',
				Pool: userPool
			}
			const cognitoUser = new AmazonCogintoIdentity.CognitoUser(userDetails)

			cognitoUser.authenticateUser(authenticationDetails, {
				onSuccess: function (result) {
					console.log('access token + ' + result.getAccessToken().getJwtToken());
		            console.log('id token + ' + result.getIdToken().getJwtToken());
		            console.log('refresh token + ' + result.getRefreshToken().getToken());
		            console.log(result)
		        },
		        onFailure: function(err) {
		            console.log(err);
		            // console.log('not onSuccess')
		        },
			});

please Help me to solve this error

**Comment by mlabieniec** [comment]
@Aslamdesusa are you using this in Node.js? If so, you need to install a node-fetch:
https://aws-amplify.github.io/amplify-js/media/authentication_guide#nodejs-support

**Comment by Aslamdesusa** [comment]
Thank you @mlabieniec it was helpful

**Comment by gpolyn** [comment]
> @Aslamdesusa are you using this in Node.js? If so, you need to install a node-fetch:
> https://aws-amplify.github.io/amplify-js/media/authentication_guide#nodejs-support

Link fails to refer ^^^

**Comment by lexakozakov** [comment]
I got the same error, Im using Web browser to login.

**Comment by xemil** [comment]
I moved to CognitoIdentityServiceProvider from 'aws-sdk'. It had all the functionality i needed, and worked. 

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html

Typescript Node solution.

**Comment by powerful23** [comment]
Closing the issue as you will no longer receive `unknown` error in the latest version.
