### ISSUE TITLE
Can't Disable SignUp

### ISSUE THREAD

**Issue by myrcutio** [aws-amplify/amplify-js#1467]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
the withAuthenticator HOC only shows the default components, even when an array of components is passed as the third argument.

I'm trying to remove the SignUp component (since my User Pool isn't configured to allow it) using this code:
```
export default withAuthenticator(App, true, [
  <Greetings />,
  <SignIn />,
  <ConfirmSignIn />,
  <VerifyContact />,
  <ForgotPassword />
])
```

Instead this is what loads:
![image](https://user-images.githubusercontent.com/1391968/44311874-7fe5af80-a3b4-11e8-82fc-6bd6ee289fa3.png)
I see the same behavior when using the <Authenticator /> component.

What is the expected behavior?
I expected to see only the SignIn and ForgotPassword components loaded on the login page.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
package.json dependencies:
```
  "dependencies": {
    "aws-amplify": "^1.0.6",
    "aws-amplify-react": "^1.0.6",
    "isomorphic-fetch": "^2.2.1",
    "lodash.find": "^4.6.0",
    "lodash.get": "^4.4.2",
    "lodash.orderby": "^4.6.0",
    "moment": "^2.22.2",
    "mysql": "github:mysqljs/mysql",
    "next": "^6.1.1",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-modal": "^3.5.1",
    "react-protected-mailto": "^1.0.3"
  },
  "devDependencies": {
    "@zeit/next-sass": "^0.2.0",
    "node-sass": "^4.9.3",
    "serverless": "^1.30.0",
    "serverless-plugin-include-dependencies": "^3.1.1",
    "serverless-plugin-inject-dependencies": "0.0.5",
    "serverless-plugin-warmup": "^3.6.2-rc.1"
  }
```

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by yuth** [comment]
This is the issue with current implementation. Paassing `authenticatorComponents` props, to `withAuthenticator` HoC did render only the components that were passed to it, but the `SignIn` component did not check to see if `SignUp`  was allowed. I have created a #1478 which checks for this and conditionally renders the links

**Comment by yuth** [comment]
Fixed in #1478

**Comment by s-hussain639** [comment]
Oh Thanks man you are a life saver :dancer:

**Comment by taylorgrahamedb** [comment]
I still can't seem to get this to work?
