### ISSUE TITLE
Decrease AWS-Amplify-Angular Bundle Size

### ISSUE THREAD

**Issue by haverchuck** [aws-amplify/amplify-js#1469]
Do you want to request a feature or report a bug?
Feature

What is the current behavior?
The AWS-Amplify-Angular includes all of the Amplify library as a dependency even when not strictly needed.  Attempt to include only required modules to decrease bundle size.  Other ways to decrease bundle size should also be considered.

**Comment by MainaWycliffe** [comment]
This issue needs to be addressed. I included the aws-amplify-angular into my project and the main bundle size increased over 6 MB right from just under 1MB. That's very huge considering I only need Cognito.

**Comment by dave-irvine** [comment]
@haverchuck Same issue on aws-amplify-react I'm afraid. Looks like the entire graphql lib gets imported even though a small portion gets used.

**Comment by MainaWycliffe** [comment]
@haverchuck Would it be possible to break it down into smaller modules so at least one can only import just that module they are using? Like having an AmplifyAuthModule, AmplifyStorageModule, AmplifyAnalyticsModule etc. This would allow it to be more tree shakable removing unused modules and libraries.

**Comment by haverchuck** [comment]
I've been digging into this a bit, and here is the current bundle size for the aws-amplify-angular package (i.e. just the amplify-angular package, not the main amplify package):

```
-----------------------------
Rollup File Analysis
-----------------------------
bundle size:    452.454 KB
original size:  551.576 KB
code reduction: 17.97 %
module count:   146
-----------------------------
```

Part of the issue here is that we aren't declaring `@angular/core` as an external in our rollup config.  Doing so changes the bundle size like so:

```
-----------------------------
Rollup File Analysis
-----------------------------
bundle size:    244.845 KB
original size:  322.112 KB
code reduction: 23.99 %
module count:   145
-----------------------------
```

This is a not-insignificant reduction and I'm going to open a PR.  Additionally, we will continue investigating the other bundle-size issues discussed on this thread.

**Comment by haverchuck** [comment]
@MainaWycliffe @dave-irvine  @gege251  - 
We have merged a PR for this issue and will be deploying it to NPM soon.  It addresses the bundle size of the actual aws-amplify-angular package.  Here is the improvement:

BEFORE:
```
-----------------------------
Rollup File Analysis
-----------------------------
bundle size:    452.454 KB
original size:  551.576 KB
code reduction: 17.97 %
module count:   146
-----------------------------
```
AFTER:
```
-----------------------------
Rollup File Analysis
-----------------------------
bundle size:    244.845 KB
original size:  322.112 KB
code reduction: 23.99 %
module count:   145
-----------------------------
```

The bundle size issues you've noted in the other amplify modules (such as api) will need to be addressed seperately.  Thanks.
