### ISSUE TITLE
Why Auth.signIn() and Auth.currentAuthenticatedUser() return different Cognito user structure?

### ISSUE THREAD

**Issue by wzup** [aws-amplify/amplify-js#1474]
### Do you want to request a feature or report a bug?

Bug

### What is the current behavior?

`Auth.currentAuthenticatedUser()` 
and 
`Auth.signIn()` 
return different structure of Cognito users objects. Fields are missing.

### What is the expected behavior?

I expect to have consistent structure of Cognito user objects from both methods.

Why fields are missing in `Auth.signIn()`?

This is from `.signIn()`:
```
{
  "username": "59...4565",
  "pool": {},
  "Session": null,
  "client": {},
  "signInUserSession": {},
  "authenticationFlowType": "...",
  "deviceKey": "...",
  "randomPassword": "...",
  "deviceGroupKey": "...",
  "storage": MemoryStorage()
}
```

And this is from `.currentAuthenticatedUser()`.
```
{
  "username": "...",
  "pool": {},
  "Session": null,
  "client": {},
  "signInUserSession": {},
  "authenticationFlowType": "",
  "attributes": {
    "phone_number_verified": true,
    "phone_number": "+1..."
  },
  "storage": MemoryStorage()
}
```

I help you to see the difference. There is no `attributes` in `.signIn()`.

Why? 
Who has decided to remove them from `.signIn()` and leave them in `.currentAuthenticatedUser()`?
How can I have consistent **Cognito** user structure for all methods? WITHOUT additional redundant api calls like `Auth.userAttributes()`.

**Comment by annjawn** [comment]
Any update on this? I am noticing this too. Accessing the `attributes` property is going to be very helpful right after the user signs. Having to make another call to `currentAuthenticatedUser()` just to get the attributes sounds redundant to me. The only way to get the attributes right after signIn is by parsing the result of `session.getIdToken().getJwtToken()` .

**Comment by powerful23** [comment]
@annjawn we will look into this issue. As for now as you said the work around is to parse the jwt token.

**Comment by powerful23** [comment]
Related to #1257
