### ISSUE TITLE
Cognito: forgetting a password after changing an email without confirming it can lock users out of their accounts

### ISSUE THREAD

**Issue by n1te1337** [aws-amplify/amplify-js#1475]
**Do you want to request a feature or report a bug?**

Bug.

**What is the current behavior?**

As far as I can tell the following scenario can permanently (unless they contact an admin) lock users out of their account:

(a user pool uses an email address as the "username")
1. User signs up and confirms their email
2. User logs in
3. User updates their email via `updateUserAttributes()` without confirming the new email
4. User logs out
5. User forgets their password
6. User can't log into their account

The problem in this scenario is that the user can't call `forgotPassword()` because their email isn't verified and they can't verify their new email because they'd need to be able to call `verifyUserAttribute()` for which they need to be authenticated (which they can't do because they don't know their password).

**What is the expected behavior?**

The user needs to be able to verify their new email without logging in.

---
Is there any way around this issue? I've been combing through Cognito docs but I can't seem to find a way around it.

Any help much appreciated.

Thanks.

**Comment by powerful23** [comment]
@n1te1337 did this case actually happen? As far as I can tell, if the new email is not confirmed, then the old email should still be valid or there would be a problem.

**Comment by n1te1337** [comment]
@powerful23 definitely still happening. If you sign up with an email as your username and then change it (with or without confirming it) then the old email will bebe replaced with the new one, then if you try to call `authenticateUser` or `forgotPassword` you'll get `UserNotFoundException`.

- old email
<img width="660" alt="cognito_old_email" src="https://user-images.githubusercontent.com/1946858/44474240-8d7d8c80-a675-11e8-8bc5-a1663a2704d9.png">

- new unconfirmed email
<img width="660" alt="cognito_new_email" src="https://user-images.githubusercontent.com/1946858/44474257-979f8b00-a675-11e8-8fcf-39a62e5fa074.png">

- logging in with the old email and getting `UserNotFoundException` 
<img width="862" alt="cognito_old_email_login_error" src="https://user-images.githubusercontent.com/1946858/44474274-a1c18980-a675-11e8-89b9-d350f957c05e.png">

---
Let me know if you need any more details.

**Comment by powerful23** [comment]
@n1te1337 from what I heard from the Cognito team in that situation the user needs to contact the administrator to verify his new email or use the [api](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminUpdateUserAttributes.html) to verify the email.

**Comment by powerful23** [comment]
Closing this issue. Please feel free to reopen if you still have this issue.

**Comment by mattccrampton** [comment]
This is still an issue, not sure why it was closed.  If a user submits a change to their email address it should not take affect until they've confirmed the change.  Either the old email address should be used when the user logs in (until the new one is confirmed) or both email addresses (old and new) should be able to be used to login or reset their password until the new email address is verified.

**Comment by qu-y** [comment]
Can confirm that this is still an issue. My current workaround is to request a password change, to confirm again. Of course it doesn't work if the old email has a typo and user has no access to it.
