### ISSUE TITLE
Why Amplify and not AWS-SDK?

### ISSUE THREAD

**Issue by davidgatti** [aws-amplify/amplify-js#1477]
Hello AWS team,

I'm bit confused as of why this Amplify SDK exists. Why Cognito is not in the AWS-SDK package? Why did you decide to brake out of the browser version of the SDK to this separate project?

**Comment by XCarle** [comment]
Moreover, Amplify seems to require (ahah) browserification

**Comment by mlabieniec** [comment]
You can find the principles of what we are providing here:
https://github.com/aws-amplify/amplify-js/wiki

Amplify in-general is meant to be a **client-focused** (mobile/web) library with escape hatches to lower-level functionality via the SDK.
