### ISSUE TITLE
Cognito: substitute {username} in password reset message

### ISSUE THREAD

**Issue by ammulder** [aws-amplify/amplify-js#1480]
Right now a new account e-mail in Cognito lets you specify {username} and {####} parameters, which Cognito will substitute for you.

However the reset password e-mail does not substitute {username} and only substitutes {####}.

Since I am not using e-mail addresses as usernames, a reasonably common situation where a user can't sign in is that they have their username wrong (perhaps an error in the capitalization, perhaps they just forgot).  For that reason, I would REALLY like the password reset e-mail to repeat their exact username as well as the confirmation code needed to reset the password.

I tried putting {username} in my password reset message template but that just leaves the literal text "{username}" in my password reset e-mail.

**Comment by mchong-teal** [comment]
I am unable to get the {username} parameter in the new account email.  If I create a custom email verification message with the content:
```{username}```
I also just get the literal text '{username}'.  This is contrary to what is indicated in the documentation..
