### ISSUE TITLE
signIn() returns different Cognito object depending on authenticationFlowType

### ISSUE THREAD

**Issue by tobiastornros** [aws-amplify/amplify-js#1481]
Do you want to request a feature or report a bug?

Bug

What is the current behavior?

`Auth.signIn()` returns different Cognito object if `authenticationFlowType` is set to `USER_PASSWORD_AUTH`.
The Cognito object is missing `deviceKey` which is required to exists if you want to use Auth.completeNewPassword(cognitoUser, password, ...)

Example:
```
Auth.configure({
	authenticationFlowType: 'USER_PASSWORD_AUTH'
})

Auth.signIn('email@email.com', 'password').then(
	(user) => {
		if (user.challengeName === 'NEW_PASSWORD_REQUIRED') {
			// This will fail if authenticationFlowType is USER_PASSWORD_AUTH
			Auth.completeNewPassword(user, 'someNewPassword', []).then(
				data => console.log(data)
			).catch( 
				err => console.log(err)
			)
		} else {
			console.log(user)

		}
	}
)
```

Compare Cognito user objects: 

With authenticationFlowType USER_PASSWORD_AUTH
```
{
	Session: '',
	authenticationFlowType: '',
        challengeName: '',
        challengeParam: {},
	client: {},
	pool: {},
	signInUserSession: {},
	storage: f(),
	username: ''
}
```

With standard authenticationFlowType USER_SRP_AUTH 
``` {
	Session: '',
	authenticationFlowType: '',
        challengeName: '',
        challengeParam: {},
	client: {},
	deviceGroupKey: '',
	deviceKey: '',
	pool: {},
	randomPassword: '',
	signInuserSession: {},
	storage: f(),
	username: '',
	verifierDevices: '',
}
```

What is the expected behavior?

Cognito User object should include deviceKey when using authenticationFlowType USER_PASSWORD_AUTH. 

```
    "aws-amplify": "^1.0.6",
    "aws-amplify-react-native": "^1.0.6",

```

**Comment by powerful23** [comment]
@tobiastornros Hi thanks for reporting the issue. How did you set your Cognito User Pool. Did you set it to remember your user's devices?

**Comment by tobiastornros** [comment]
@powerful23 Yes, it is configured to always remember device.
