### ISSUE TITLE
Something i do not get for PubSub to work with a cognitoPoolId

### ISSUE THREAD

**Issue by XCarle** [aws-amplify/amplify-js#1483]
Hi Guys,

we have been implementing some PubSub with the aws-sdk using a cognitoIdentityPoolId. We are not yet implementing our user loggin so for now it allows us to update the AWSIotData.device WebSocketCredentials on the accessKeyId, secretKey and sessionToken update (loaded by the cognitoidentity).

After validating this behaviour, i tried implementing it on Angular (AmplifyService.pubsub() & AmplifyService.auth())

I could not receive messages from the topic registered. So i thought it could be usefull to register and login the user using the session credentials. But problems, i cannot retrieve a proper user object with any of the awsAmplifyService.

It is hard to find any implementation over the pubsub mecanism over a cognitoIdentityPoolId. 

**Are operations other than init / config usefull to integrate pubsub over a cognitoIdentityPool?**

**Comment by elorzafe** [comment]
@XCarle can you add a code snippet on how you are trying to use it? You are using unauth or auth users or both? Can you see error messages on console or network?

**Comment by alebiavati** [comment]
Closing issue as inactive, please open another issue with more details if you still need support.
