### ISSUE TITLE
Amazon-Cognito Registering User using Java-Script SDK

### ISSUE THREAD

**Issue by mahmoudsheir** [aws-amplify/amplify-js#1486]
I'm trying to make a Java function to register a user at AWS Cognito user pool, I'm using the below Link example for the registration:

https://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-user-identity-pools-javascript-examples.html

I'v faced the below errors at Firefox and same at Chrome

  	document.getElementById('submit').onclick = cognitostandard;
	function cognitostandard(){
		var CognitoUserPool = AmazonCognitoIdentity.CognitoUserPool;
	
	    var poolData = { UserPoolId : 'eu-west-xxxxxxx',
	        ClientId : 'xxxxxxxxxxxxxxxx'
	    };
	    var userPool = new AmazonCognitoIdentity.CognitoUserPool(poolData);
	
	    var attributeList = [];
	    
	    var dataEmail = {
	        Name : 'email',
	        Value : 'email@mydomain.com'
	    };
	    var dataPhoneNumber = {
	        Name : 'phone_number',
	        Value : '+15555555555'
	    };
	    var attributeEmail = new AmazonCognitoIdentity.CognitoUserAttribute(dataEmail);
	    var attributePhoneNumber = new AmazonCognitoIdentity.CognitoUserAttribute(dataPhoneNumber);
	
	    attributeList.push(attributeEmail);
	    attributeList.push(attributePhoneNumber);
	
	    userPool.signUp('username', 'password', attributeList, null, function(err, result){
	        if (err) {
	            alert(err);
	            return;
	        }
	        cognitoUser = result.user;
	        console.log('user name is ' + cognitoUser.getUsername());
	    });

Also below is my scripts add at my js folder which is downloaded from AWS:

    <script src="js/amazon-cognito-identity.min.js"></script> 
    <script src="js/testAWS.js"></script> 

FireFox errors

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cognito-idp.eu-west-1.amazonaws.com/. (Reason: CORS request did not succeed).
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: file:///Users/msheir/Desktop/data/download%20documents(review)/learn%20site/js/amazon-cognito-identity.min.js
Source Map URL: amazon-cognito-identity.min.js.map`

**Comment by yuth** [comment]
From the error, it looks like you're loading page using local file path. Can you try loading it using a web server either spinning up your own server or using [Node HTTP Server](https://www.npmjs.com/package/http-server).

**Comment by mahmoudsheir** [comment]
I have tried installing the Node HTTP server
then i started it as below:

`msheir-mbp:~ msheir$ http-server 
Starting up http-server, serving ./public
Available on:
  http://127.0.0.1:8080
  http://172.29.65.61:8080
Hit CTRL-C to stop the server`

and then i have reloaded my page to try again but the problem still exist

**Comment by yuth** [comment]
When using [amazon-cognito-identity-js](the https://github.com/aws-amplify/amplify-js/blob/master/packages/amazon-cognito-identity-js/README.md#network-configuration), you will have to white-list   the domains. You can do it with node-http by pass `--cors` flag

Run the server with the following command
```
$ http-server --cors
```

**Comment by mahmoudsheir** [comment]
I have tried run the server as you stated but still the issue exist.

Also i tried to whitelist "*.amazonaws.com"  for chrome using below macbook commands but still the issue exist

	sudo defaults write com.google.Chrome AuthServerWhitelist "*.amazonaws.com"
	sudo defaults write com.google.Chrome AuthNegotiateDelegateWhitelist  "*.amazonaws.com"

**Comment by yuth** [comment]
Do you still get the CORs error or some other error?

**Comment by mahmoudsheir** [comment]
I still have the CORS and the Fetch error at Firefox as below 

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cognito-idp.eu-west-1.amazonaws.com/. (Reason: CORS request did not succeed).
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: file:///Users/msheir/Desktop/data/download%20documents(review)/learn%20site/js/amazon-cognito-identity.min.js
Source Map URL: amazon-cognito-identity.min.js.map[Learn More]`

**Comment by mahmoudsheir** [comment]
I have tried to use amazon EC2 instance to host my application but still the same error and the attached alert is fired, can you please check it or help:



<img width="1433" alt="screen shot 2018-08-26 at 10 50 16 pm" src="https://user-images.githubusercontent.com/33501675/44632425-f4a38580-a982-11e8-97f7-63eba51f92b5.png">
