### ISSUE TITLE
 Federated identities put into my user pool (Angular) 

### ISSUE THREAD

**Issue by nickygb** [aws-amplify/amplify-js#1488]
I'm developing an Angular app and I want to utilize Cognito to handle my users.

When a user registers themselves via Facebook/Google I want to put their information in the user pool.
In the documentaion I saw that is possible to do this in React and React Native by using withAuthenticator HOC. 

What I need is:

*  I Get the Facebook / Google token 
* The token is sent to Cognito which auth the user and puts them into the user pool.
* An access token is sent back.

I have tried to do that by using the method [`Auth.federatedSignIn()`](https://aws-amplify.github.io/amplify-js/media/authentication_guide.html#federated-identities-social-sign-in) but it not add the user into the user pool

Is it possible to do in Angular?

**Comment by nickygb** [comment]
@powerful23 is it possible to do it without using the Cognito Hosted UI? I have to use my own UI instead

**Comment by powerful23** [comment]
@nickygb maybe you can try this: https://github.com/aws-amplify/amplify-js/issues/1316#issuecomment-408228241

**Comment by BKB503** [comment]
@powerful23 with hosted UI how refresh tokens are issued? before expiring access token, as I don't want to re-authenticate, i want to use in Angular 6 and AngularJS

**Comment by BKB503** [comment]
@powerful23 it will automatically set the new access token after getting refresh token or do we need to it manually? 
I have another question which I have raised in this link [](https://github.com/aws-amplify/amplify-js/issues/1316#issuecomment-444312027) please let me know the right process and library to use

**Comment by powerful23** [comment]
Closing the issue as this can be solved by using Cognito Hosted UI. Please check the doc: https://aws-amplify.github.io/docs/js/authentication#social-provider-federation

**Comment by GIOkafor** [comment]
What if I don't want to use the Cognito Hosted UI, is there a way around this?

**Comment by pbirsinger** [comment]
Agreed . Is there no way to do federated Login with just regular withAuthenticator component?
