### ISSUE TITLE
Do not autocapitalize usernames

### ISSUE THREAD

**Issue by hutch120** [aws-amplify/amplify-js#1496]
> Do you want to request a feature or report a bug?

Bug

> What is the current behavior?

autocapitalize on inputs is the default behaviour in many browsers. This causes problems when entering a username and attempting to log into Cognito. Regardless of the problems, the UI should not autocapitalize, autocorrect, or spellcheck anything in a username or password input box.

> If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

Attempting to login using the auth UI... attempt to enter a lowercase username in the input box (classname = .amplify-input)

> What is the expected behavior?

Should never auto capitalize the first letter of the username.

> Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

Latest

> You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

N/A

To fix this add attributes to the inputs `.amplify-input`
```
autocapitalize, 'none'
autocorrect', 'off'
spellcheck', 'false'
autocomplete', 'off'  // Maybe not?
```

Workaround, add this to your react component.

```
componentDidMount() {
 var ai = document.querySelectorAll('.amplify-input')
 if (ai && ai.length > 0) {
   for (var i = 0; i < ai.length; i++) {
      ai[i].setAttribute('autocapitalize', 'none')
      ai[i].setAttribute('autocorrect', 'off')
      ai[i].setAttribute('autocomplete', 'off')
      ai[i].setAttribute('spellcheck', 'false')
    }
  }
}
```

**Comment by jordanranz** [comment]
Thanks for the feedback!

This does not seem to be an issue with the latest Amplify UI. I am going to close this issue.

If you are still experiencing this issue can you please reopen this, mention what amplify package you are using, and post the version number of Amplify you are using and I can assist you further.

**Comment by kjetilge** [comment]
I still have this problem in a Vue app.
My config:
```
        signUpConfig: {
          // hideAllDefaults: true,
          header: 'Meld inn',
          signUpFields: [
            { label: 'Epost', key: 'username', required: true, type: 'email', displayOrder: 1 },
            // { label: 'Epost', key: 'email', required: true, type: 'email', displayOrder: 1 },
            { label: 'Passord', key: 'password', required: true, type: 'password', displayOrder: 2 },
            { label: 'Skolekode', key: 'profile', required: true, type: 'string', displayOrder: 3 }
          ],
          hiddenDefaults: ['email', 'username', 'password', 'phone_number'],
          defaultCountryCode: '47',
          authenticationFlowType: 'email'
        },
```
