### ISSUE TITLE
How to validate Federated Identity using cognito ,nodejs and angular and put in User pool

### ISSUE THREAD

**Issue by sachita011993** [aws-amplify/amplify-js#1497]
I want to know that how we validate Federated Login user in cognito .
Case 1 : i'm using node js sdk and angular as front-end.
case 2 : from angular i have get Facebook access token after login . and send it to cognito using AWS.config.credentials.get method.
case 3 : after that i have get three token as ( accessKeyId : , secretAccessKe , sessionToken  identityId )
case 4 : Now i'm stuck here and want know that how i validate this as JWT token ?

**Comment by powerful23** [comment]
@sachita011993 the object you get from `AWS.config.credentials.get` is an AWS credentials which is used to sign your http request to AWS resources. I am not quite understanding why you would want to validate it?

**Comment by powerful23** [comment]
Closing this issue due to no further response. Feel free to reopen if you still have this issue.
