### ISSUE TITLE
While registering the user get the error message as "Can't find variable : fetch" on iOS 10.1.1.

### ISSUE THREAD

**Issue by anjalitanpure** [aws-amplify/amplify-js#1498]
Description of a bug found on iOS 10.1.1.
- While registering the user get the error message as "Can't find variable : fetch".
- This issue is related to Safari version, I was able to produced this issue on iOS 10.1.1 and this issue is not coming on latest iOS versions.
- AWS-Amplify "amazon-cognito-identity-js", internally uses fetch API and it doesn't supports to older versions of Safari.

**Comment by anjalitanpure** [comment]
@JoseWebby Hey thanks Jose for the input, I ended up using 'whatwg-fetch', 'https://github.com/github/fetch' in my application and I am using Angular-5. Thanks for the issue pointer.

**Comment by anjalitanpure** [comment]
Thanks for the input Jose. I ended up using 'whatwg-fetch', 'https://github.com/github/fetch' in my Angular-5 application. Thanks for the issue pointer.

**Comment by JoseWebby** [comment]
Wicked, glad that helped!
