### ISSUE TITLE
What code turn to signedIn?

### ISSUE THREAD

**Issue by ume-lap** [aws-amplify/amplify-js#1499]
Do you want to request a feature or report a bug?
*just a question*

I try below sign up flow with React Auth.
signUp -> confirmSignUp -> ORIGINAL_STATE_A -> signedIn

However, when user is in ORIGINALSTATE_A, user try reflesh(F5) with his browser, authState is turn to `signedIn` because browser has LastAuthUser in localStorage, not `ORIGINALSTATE_A`.

I wanna confirm what code turn to signedIn.
Anyone has some clue?

**Comment by powerful23** [comment]
@ume-lap if you are using `Authenticator`, it will check the current user when the page is reloaded: https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Auth/Greetings.jsx#L43

**Comment by haverchuck** [comment]
@ume-lap I am closing this issue as your questions seems to have been answered by @powerful23 .  Please feel free to reopen it.
