### ISSUE TITLE
Documentation using awsmobile?

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-js#1500]
Hi,

Good day.

I might still be asleep, but has awsmobile cli been replaed by amplify cli?

The documentation has switched from awsmobile to amplify? Where's the old docs? And if so how do we move an existing app to amplify?

Regards.

**Comment by jordanranz** [comment]
Hi @jarrettj,

Apologies for the delayed response. The awsmobile cli documentation was moved to [AWS documentation](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-cli-reference.html).

The migration plugin was introduced later and is located [here](https://github.com/awslabs/amplify-mobilehub-migrator).

Going to close this for now. Please reopen if you have any further questions or concerns.

**Comment by jarrettj** [comment]
No worries. :)
