### ISSUE TITLE
How federated Identity ID is populated and sent to IAM policies?

### ISSUE THREAD

**Issue by Private-SO** [aws-amplify/amplify-js#1503]
I want to know , from where this value is `${cognito-identity.amazonaws.com:sub}` populated . I had checked in JWT token too where `sub` will have `username` of cognito. But i cant able to see federated ID any where in JWT Id token. I can only see the ID generated in federated identity pool. 

Does it is a hash of cognito and federated pool ID ?

Because if it is taking from JWT token,  i have `custom:Attribute1` does i use this parameter like this in `${cognito-identity.amazonaws.com:custom:Attribute1}` in IAM role of dynamodb where this value is a partition key in my table?

Thanks 
Any help is appreicated

**Comment by manueliglesias** [comment]
Hi @Private-SO 

> I want to know , from where this value is ${cognito-identity.amazonaws.com:sub} populated

from https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_iam-condition-keys.html#condition-keys-wif :
> For Amazon Cognito users, the keys are cognito-identity.amazonaws.com:aud (for the identity pool ID) and cognito-identity.amazonaws.com:sub (for the user ID).

---

> Because if it is taking from JWT token, i have custom:Attribute1 does i use this parameter like this in ${cognito-identity.amazonaws.com:custom:Attribute1} in IAM role of dynamodb where this value is a partition key in my table?

Custom attributes are not available as policy variables, see link to docs above.
