### ISSUE TITLE
Errors Related to Ionic in Angular (Cannot find module '@stencil/core  and error TS2344: Type 'keyof B' does not satisfy the constraint 'string'.)

### ISSUE THREAD

**Issue by MainaWycliffe** [aws-amplify/amplify-js#1512]
**Do you want to request a feature or report a bug?**

BUG

**What is the current behavior?**

I am getting the following error:

```
ERROR in node_modules/ionicons/dist/types/generated.d.ts(7,29): error TS2307: Cannot find module '@stencil/core'.
node_modules/@ionic/core/dist/types/utils/overlays.d.ts(9,82): error TS2344: Type 'keyof B' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.
```

**What is the expected behavior?**

Should compile successfully, especially considering i am not using Ionic which seems to be the issue.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

Windows 10
Node 10.8.0
Angular 6.1.4
Angular CLI: 6.1.5
aws-amplify 1.0.6 
aws-amplify-angular 1.0.3

**Comment by haverchuck** [comment]
@MainaWycliffe - We recently merged a fix for this problem into our unstable build of AWS-Amplify-Angular.  Please try removing @ionic and AWS-Amplify-Angular from your node modules and then running npm i aws-amplify-angular@1.0.4-unstable.2

We will be merging this into the main build soon.
