### ISSUE TITLE
aws-amplify@^0.1.36 undefined is not a function (near ...window.addEventListener...)

### ISSUE THREAD

**Issue by 7772** [aws-amplify/amplify-js#1513]
## Related Issue
[#230](https://github.com/aws-amplify/amplify-js/issues/230)

## Do you want to request a feature or report a bug?

- report a bug and
- request a feature 

## What is the current behavior?

- If do not turn on debugger

undefined is not a function (near ...window.addEventListener...)

- If turn on debugger

Worked well.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

1. npm install
```
  npm install --save aws-amplify  // This line installed "^0.1.36" in my case.
  npm install --save aws-amplify-react
  npm install --save aws-amplify-react-native
```
2. import and used
```
  import Amplify, { Auth } from "aws-amplify";
  import aws_exports from "../aws-exports";  
  import authConfigure from "../authConfigure";
  Amplify.configure(aws_exports);
  Auth.configure(authConfigure);

  Auth.federatedSignin()
```

## This issue can be resolved 
```
npm install --save aws-amplify@latest
```

## What is the expected behavior?

- AWS amplify should work regardless of if debugger turns on.
- This issue should be wrote in docs.
  - Want to change document like this
    ```
      npm install --save aws-amplify@(version that rightly work)
    ```

**Comment by powerful23** [comment]
@7772 I am going to close this issue as this is out of date. If you still have this issue in the latest version of amplify please reopen it.

**Comment by PyrrhaDev** [comment]
I have pretty much the same problem. Debugged remotely it works well, without remote debugging, "undefined is not a function(evaluation 'Uint32Array.from')" is displayed. aws-amplify aws-amplify-react and aws-amplify-react-native are all up to date. I'm sure it's from amplify since there's AmazonAIConvertPredictionsProvider.js mentionned in the error

**Comment by PyrrhaDev** [comment]
May be unrelated to this problem, looks like the new @aws-amplify/predictions dependency is creating similar problems. Just install aws modules one by one to only get the one you'll use.

**Comment by 0xR** [comment]
I'm running into Uint32Array.from not being defined on IE11 when using a AppSync api. I've traced it to this line: https://github.com/aws/aws-sdk-js-crypto-helpers/blob/master/packages/sha256-js/src/RawSha256.ts#L13

I'm investigating wheter I can polyfill it or configure amplify-js differently to not use this code.
