### ISSUE TITLE
Send Verification Code on Signup and send a link on forget password using Cognito User Pool

### ISSUE THREAD

**Issue by sachita011993** [aws-amplify/amplify-js#1514]
I want to send Verification Code on Signup and send a link on forget password .
Is it possible to send two different verification strategy using user pool ?
How i could do this  ? 
I have set code verification radio on while create User Pool .

**Comment by powerful23** [comment]
@sachita011993 unfortunately Cognito doesn't support sending a link on forget password. Will mark as feature request.

**Comment by sammartinez** [comment]
Resolving as this is now possible in the `ForgotPassword` component that it will send a code to the user's email
