### ISSUE TITLE
Federated Identity allow access to others individuals to see my account ?

### ISSUE THREAD

**Issue by Private-SO** [aws-amplify/amplify-js#1523]
It is a question .
Hi,

**MyUsecase**
{ Cognito+Federated Identity and accessing DyanamoDB via API gateway }
I have a federated identity ID for every user who logged in to my app . Using this i can restrict them access others account. Now i have additional requirement where i want to allow my team members to see my dynamodb row contents but don't want them to write or delete them. 

BTW everyone will have to register to app via cognito so every one will have a unique federated identity ID .

IS there is a way for this ?

Thanks
Any help is appreciated.

**Comment by powerful23** [comment]
@Private-SO Hi are you still having this question? Sorry to respond so late but I think if you want certain people to have read access to your dynamoDB, you can create a user group in your Cognito User Pool and customize the IAM policy for that group to allow them to read your db content. 

Please check the doc: [Adding users to group](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-user-groups.html)
