### ISSUE TITLE
Angular Production Build Generates 103 Bundles When Using Amplify!

### ISSUE THREAD

**Issue by tuhinkarmakar** [aws-amplify/amplify-js#1526]
#### Do you want to request a feature or report a bug?
Bug

#### What is the current behavior?
Angular CLI generates 103 bundles when `aws-amplify` and `aws-amplify-angular` are used in a project. As far as I can tell, most of them are related to Ionic.

**Output of the build process**
![image](https://user-images.githubusercontent.com/11135104/44738783-99ed6380-ab13-11e8-8fd0-c2db6f9d1179.png)

**Content of a bundle**
![image](https://user-images.githubusercontent.com/11135104/44739277-f69d4e00-ab14-11e8-953a-f15ec650bd70.png)

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

- Generate a new Angular project using the Angular CLI
- Add `aws-amplify` and `aws-amplify-angular` to the project
- Configure the library in `main.ts`
- Inject `AmplifyService`
- Run a production build of the project

#### What is the expected behavior?
Angular CLI will generate _4 + number of lazy-loaded modules_ modules.

#### Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

I tested with the latest versions of Angular, TypeScript, AWS Amplify and AWS Amplify Angular. I tested on a Windows 10 and a Kubuntu 18.04 system.

**Comment by haverchuck** [comment]
@tuhinkarmakar   - We recently merged a fix for this problem into our unstable build of AWS-Amplify-Angular. Please try removing @Ionic and AWS-Amplify-Angular from your node modules and then running npm i aws-amplify-angular@1.0.4-unstable.2

We will be merging this into the main build soon.
