### ISSUE TITLE
Can't login anymore due to Credentials on Android (failed to load credentials)

### ISSUE THREAD

**Issue by wbeuil** [aws-amplify/amplify-js#1530]
Do you want to request a feature or report a bug?
I want to request a bug as I can't login anymore with amplify. It only occurs on Android.

What is the current behavior?
When I try to login with amplify, it rejects with debug log 'Credentials - Failed to load credentials' and 'AWSPinpointProvider - ensure credentials error: Error: Network Failure at XMLHttpRequest.<anonymous>'

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.
I updated amplify to its newest version and try to login with Auth.signIn(username, password).

What is the expected behavior?
It throws above errors.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
"aws-amplify": "^1.0.8",
"aws-amplify-react-native": "^2.0.0",

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

![screen shot 2018-08-29 at 11 40 07](https://user-images.githubusercontent.com/8110579/44779645-52e98780-ab80-11e8-945b-f05c94e27883.png)

**Comment by elorzafe** [comment]
Hi @wbeuil I just tested with this dependencies and is working properly
"dependencies": {
    "aws-amplify": "^1.0.8",
    "aws-amplify-react-native": "^2.0.0",
    "expo": "^27.0.1",
    "react": "16.3.1",
    "react-native": "~0.55.2"
  }

my userpool is in eu-central-1, I will create a project on eu-west-1 and let you know

**Comment by elorzafe** [comment]
@wbeuil I create an amplify project on eu-west-1 with the same configuration and worked. Do you still have this issue?

**Comment by elorzafe** [comment]
@wbeuil I tested on eu-west-1 and is working correctly. If you still have this problem feel free to reopen the issue.

**Comment by elorzafe** [comment]
I will leave the issue open until the problem is root caused. How are you importing Amplify and Auth on your App?

**Comment by powerful23** [comment]
@wbeuil  seems like it is the network connection problem. If you are using Android emulator, maybe it's caused by some configuration in your machine like the firewall?

**Comment by wbeuil** [comment]
@elorzafe I'm importing Amplify and Auth as below:

import Amplify from 'aws-amplify';
import { Auth } from 'aws-amplify';

@powerful23 I don't know how I can disable the firewall on the android emulator, would you help me ?

**Comment by elorzafe** [comment]
@wbeuil can you paste some network info?

**Comment by wbeuil** [comment]
@elorzafe I don't know why but I re-tried yesterday and it worked... Thanks anyway

**Comment by elorzafe** [comment]
Cool!
