### ISSUE TITLE
How to Update / Deploy Lambda Correctly?

### ISSUE THREAD

**Issue by oneduckoo** [aws-amplify/amplify-js#1531]
Do you want to request a feature or report a bug? No

What is the current behavior? I have difficulty in updating Lambda

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify. N/A

What is the expected behavior? N/A

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions? 
"aws-amplify": "^1.0.6",
"aws-amplify-react-native": "^1.0.6",
"expo": "^27.0.1",
"react": "16.3.1",
"react-native": "~0.55.2",
"npm": "5.6.0

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

I have tried out Amplify API to access dynamodb using API gateway, Cloudformation and Lambda, and it has been successful. However, as I begin to develop my app more, I feel that I need to customize and update Lambda function, but I am not sure what is the best way to do so.

Accessing to the console of Lambda and trying to update function was my first approach, and it was impossible to edit the function on the page as it is big, and I noticed that it is necessary to upload it to S3. So, I tried to upload it. After it is deployed, however, I got 5xx response on my app. 

Secondly, I have checked files in S3, and I noticed that some related information (ex. s3key) is stored in cloudformation json. I also realized that I can update and get 200 response if I upload Lambda zip file to S3 without changing zip name. The problem is that it is not updating, and I cannot see updated result on my app. I doubt it is because the name has not been changed.

As I use AWS through Amplify, I am wondering how I can edit and update Lambda on the right way.

**Comment by mbahar** [comment]
@oneduckoo did you create your API Gateway endpoints with the AWSMobile CLI? If so, you will have a local code to change and deploy. Also, the Amplify CLI enables you to connect to a Lambda function with `amplify add api` command. https://aws-amplify.github.io/amplify-js/media/api_guide#automated-setup

**Comment by oneduckoo** [comment]
@mbahar Yes. I made it with CLI, and I found a local code! I really appreciate it.
