### ISSUE TITLE
Cookie Storage sizes are too large

### ISSUE THREAD

**Issue by guanzo** [aws-amplify/amplify-js#1545]
Relevant issue: https://github.com/amazon-archives/amazon-cognito-identity-js/issues/688

The benefit of cookie storage is that it enables single sign on for a root domain and all subdomains, it's a great feature! However there are some drawbacks concerning storage size.

When I log in as User A, Cognito creates cookies with a total size of ~4.5k bytes. The largest cookies are the refreshToken, idToken, and accessToken. This size is over the limit that Safari sets per domain: 4k bytes. When I log in again as User B, **without signing out User A**, Cognito will create another set of cookies, increasing the total size to 10k bytes for a single domain. This means 10k bytes are sent for every single request set to that domain. 

I think Cognito should strive to keep the total cookie size to a minimum. Regarding my example, what if when signing in as User B, Cognito deleted all cookies related to User A? Or simply, Cognito deletes all cookies unrelated to User B?

If not, is there a way to do this in my code? That is, during Sign In, can I delete all cookies unrelated to the current authenticated user?

**Comment by hilkeheremans** [comment]
The main thing to remember here is that Cognito tries to include all user data in the identity token. Especially if you include custom data, this will quickly start to add up as you add lots of data.

Here's a trick: if you want to reduce token size, the easiest way to do so is to evaluate which information you _really_ need in the identity token, and then use `claimsToSuppress` on a Pre Token Generation Lambda (see https://docs.amazonaws.cn/en_us/cognito/latest/developerguide/user-pool-lambda-pre-token-generation.html) to _not_ include fields you don't really need. This can make a huge difference.

I would add some example code here if I still had it, but I built this for a confidential project which I am no longer involved with, so I deleted the code afterwards. Still, you should be able to figure it out -- if not, throw a shout in here.

**Comment by hilkeheremans** [comment]
Second thing: to avoid the issue in the first place, you should be able to log out the old user which should also delete those cookies. I don't recall if this kind of logout happened automatically in the old pre-Amplify cognito library if it detected a new user, or if I coded something manually to do that. I certainly don't know how one would go about this in Amplify. 

Good luck!

**Comment by guanzo** [comment]
Thanks @hilkeheremans, I'll give the Lambda solution a try.

**Comment by wcoppens** [comment]
@hilkeheremans Did you ever get the total cookie size below 4kb? Because even when we suppress all claims which we are allowed to suppress according the documentation, we still exceed the 4kb with +/- 200 bytes.

**Comment by kushmangal** [comment]
Any update on this issue? Large cookie storage size breaks the system due to limitations in request header size.

**Comment by dallen4** [comment]
Also looking for updates on this issue. We store only a few attributes within a user in Cognito and still get performance issues. I think it's disappointing this issue (and those preceding it that contained nearly identical experiences) received so little attention and most people are told to implement a custom pre-token generation lambda trigger. Cookies generated by an auth system as widely used as Cognito should not exceed browser storage limits that can break websites. It should at least be better detailed in documentation as practices to avoid and mitigate these issues if the library doesn't see browser compatibility as crucial.

**Comment by damjanvucina** [comment]
Here's a working example of such lambda.

`// should be set up in cognito triggers as a Pre Token Generation trigger

exports.handler = (event, context, callback) => {
    event.response = {
        "claimsOverrideDetails": {
            "claimsToSuppress": ["email", "fullName", "whatever"]
        }
    };

    callback(null, event);
};`

**Comment by thomaswr** [comment]
This is a major issue for us.

Cognito amounts to almost 5K of cookies with the cookieStorage implementation, while many webservers define 8K as the default maximum.

Are there any alternative Implementations besides cookieStorage and localStorage?
Why are the cookie names alone that long? Can it be renamed?
Are all cookies required?
What's the official stance towards this issue?

Thank you

**Comment by ryanvade** [comment]
https://github.com/aws-amplify/amplify-js/issues/5330#issuecomment-658841382
