### ISSUE TITLE
[Question] API.graphql(graphqloperation(query, attrs)) are tagged on client or sent to server as it is and tagged there?

### ISSUE THREAD

**Issue by aaayushsingh** [aws-amplify/amplify-js#1547]
API.graphql uses simple strings instead of gql-tags. I couldn't find this looking into the source code.

question is, suppose there's a query
```
query Example( $id: ID!, $a: String, $b: String, $c: String, $d: String, $e: String){
  getQuery( id: $id ){
    // some fields
  }
} 
```
when calling `API.graphql(graphqloperation(query, {id, a, b, c, d, e}))` are the attributes passed tagged into the query on the client side or are they sent as it is to Appsync service and tagged there?

**Comment by manueliglesias** [comment]
Hi @aaayushsingh

The client SDK sends two separate fields to the server: `query` and `variables`. Then the server does the replacement and executes it
