### ISSUE TITLE
Feature Request: Option to return object metadata with Storage.list()

### ISSUE THREAD

**Issue by lemmingworks** [aws-amplify/amplify-js#1550]
It's often very useful to store extra information about the files stored on S3 in metadata. e.g. the row count in a csv file, a user readable name etc, but this info isn't available using Storage.list().

Storage.list() uses S3.listObjects() which doesn't return object metadata, so an extra S3.headObject() call would need to be made for each file returned by S3.listObjects() in order to get the metadata for each object, which is a performance hit, but it would be nice to have the option, e.g. to pass in a `metadata: true` flag in the options for Storage.list().

If this feature would be acceptable, then I would be happy to create a pull request for it.

**Comment by mrichman** [comment]
I'm trying to do this as well.

**Comment by theodorehadges** [comment]
Hi all, any update on this? Also could benefit from having object metadata included in `Storage.list()`.

**Comment by sw-yx** [comment]
related - #6157

**Comment by tiomun** [comment]
Its kind of absurd that list doesn't already return the files meta data and other parameters, or at least have an option to toggle the data on and off in the response.

Frankly this may end up being a deal breaker for us using amplify which sucks massively since were 6 months into development using amplify for our application already. But I never would have imagined that listing files would be the point of failure for us....

**Comment by ashika01** [comment]
@tiomun this seems like a limitation even from s3 sdk side. There was FR -> https://github.com/aws/aws-sdk-js/issues/1181

I would suggest reaching out S3 directly if this is a feature for s3 to provide. A workaround in mentioned in the linked issue above. You can try to use that.

**Comment by kvramyasri7** [comment]
Now we can access metadata of an object using `Storage.getProperties` method.

**Comment by natikagg** [comment]
> Now we can access metadata of an object using `Storage.getProperties` method. Please do find the [Reference Doc](https://docs.amplify.aws/lib/storage/get-properties/q/platform/js/).

Not able to get the metadata back, it is always coming back as undefined
