### ISSUE TITLE
GraphQL query via POST

### ISSUE THREAD

**Issue by garyrutland** [aws-amplify/amplify-js#1554]
Hi,

Our GraphQL server only allows access via POST, I can't seem to find any way of setting this in the AWS Amplify API but assuming it defaults to GET for queries?

Is there a way of setting the method?

Thanks,
Gary

**Comment by manueliglesias** [comment]
Hi @garyrutland 

Amplify issues a POST request when invoking a GraphQL query:

https://github.com/aws-amplify/amplify-js/blob/10c8edd3f48d21f5c55926679e5d5136ce0b0954/packages/api/src/API.ts#L396

**Comment by jordanranz** [comment]
Going to close this as the question was answered by @manueliglesias. Please reopen if you have any related questions or concerns.
