### ISSUE TITLE
[React Native] - withAuthenticator(App, { includeGreetings: true }) no longer renders the actual app UI, only the sign out button

### ISSUE THREAD

**Issue by dabit3** [aws-amplify/amplify-js#1558]
Do you want to request a feature or report a bug?
bug

What is the current behavior?
when using the `{ includeGreetings: true }` argument to `withAuthenticator`, the actual application UI is no longer rendered, only the Sign Out button.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.
1. Create a React Native app with Authentication service enables
2. Use withAuthenticator(App, { includeGreetings: true }) as the default export for your main App.js component

What is the expected behavior?
Sign Out button appears along with the rest of the application UI

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
aws-amplify-react-native: __2.0.0__
aws-amplify: __1.0.8__

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.
<img width="373" alt="screen shot 2018-09-02 at 4 33 11 am" src="https://user-images.githubusercontent.com/1857282/44955517-5ecb9700-ae69-11e8-8d18-a5e532e99aaf.png">

**Comment by SudarAbisheck** [comment]
Facing the same issue here.
