### ISSUE TITLE
Promoting a user to admin

### ISSUE THREAD

**Issue by jonsmirl** [aws-amplify/amplify-js#156]
I don't believe this is being addressed in the current amplify plans. Probably something to consider before the architecture gets too far along. 

Pieces of this have already been mentioned...
#54  -- the identity pool is not recording detailed information from federated logins. My mobile apps (based on mobile hub) do that so there must be some missing code from amplify
#126, #45 --- Expose the federated UI on user pool
#83 -- Demo program showing admin access
#146 - user assigned to a group with permissions
#96 - Converting unauthenticated users to authenticated 

Description of the problem: You have an existing federated user (via identity pool) and you want to promote them to admin. But.. only user pool users support being flagged as admin's.  Since this is an existing user you don't want delete their account and make a new one which makes them lose everything since their ID will change.

I think this process needs to work something like this, but this is going to be tricky to handle in the UI.
1) Make a new federated login for the same federated account but do it in the user pool.  Doing that creates an alias for this new id in the identity pool.
2) Mark this user as an admin
3) Now you need to merge identity pool identities -- the old user in the identity pool and the new one aliasing the federated login into the user pool. This merge has to end up with the Cognito ID of the old user ID so that they keep their data.

Question: assume amplify has already put a federated user into the identity pool.  Now use the hosted UI of user pool to log into that same federated user. Will this result in two entries for that user in the identity pool, or will the hosted UI find the existing entry? This problem is not too hard if the hosted UI locates the existing entry instead of creating a parallel one.  The hosted UI would then need to add a 'login' pointing back to user pool, but I don't know if the existing identity pool API supports altering an  entry.

4) When federated users login, their credentials need to be checked against both pools since you don't know if they are a normal user or an admin.
5) Also the problems with converting an unauthenticated user on identity pool into an authenticated one.  

You could punt this by forcing everyone into the user pool. But doing that pointlessly drags hordes of casual users into the User Pool which can lead to a $100K+/yr expense. Doing it that way also causes a mess for unauthenticated users since they are in the Identity Pool.

Another way to solve it is to use two Identity Pools -- one for normal users and one for admins. But then how do you move someone between the identity pools without changing their Cognito ID.

This is a complicated problem that needs some design work. Hopefully you can come up with a generic solution that we can all use.

**Comment by elorzafe** [comment]
@jonsmirl we created this [RFC](https://github.com/aws-amplify/amplify-cli/issues/766)  to see what features would you like to see in the future related to Auth Admin Tasks. Feel free to add comments or suggestions!
