### ISSUE TITLE
Cloudfront & S3 not configured for gzip

### ISSUE THREAD

**Issue by hawkett** [aws-amplify/amplify-js#1564]
Do you want to request a feature or report a bug? **Feature**

What is the current behavior? **Cloudfront not honoring `Accept-Encoding: gzip`**

- `amplify publish` (reports 'File sizes after gzip')
- Hit cloudfront and observe that js/css files are uncompressed.

What is the expected behavior? **gzipped files**

I was able to get this working by modifying the CloudFormation files:

1. The `"Compress": true` setting needs to be configured in the `DefaultCacheBehavior` section for CloudFront (amplify/backend/hosting/S3AndCloudFront/template.json).

```
...
"DefaultCacheBehavior": {
    "AllowedMethods": [
        "DELETE",
        "GET",
        "HEAD",
        "OPTIONS",
        "PATCH",
        "POST",
        "PUT"
    ],
    "TargetOriginId": "hostingS3Bucket",
    "ForwardedValues": {
        "QueryString": "false"
    },
    "ViewerProtocolPolicy": "allow-all",
    "DefaultTTL": 86400,
    "MaxTTL": 31536000,
    "MinTTL": 60,
    "Compress" : true
},
...
```

2. The `"Content-Length"` header needs to be added to the `CorsConfiguration` for S3 (amplify/backend/hosting/S3AndCloudFront/template.json), or Cloudfront will refuse to gzip.

```
...
"AllowedHeaders": [
    "Authorization",
    "Content-Length"
 ],
...
```

Also - `/index.html` (which can't be versioned) appears not to be invalidated on `amplify publish` -  so when a newly published amplify site is served from cloudfront, an old version of the site is being returned until `/index.html` expires from the cloudfront cache). Seems to be two options here:

1. `Cache-Control` header configured as S3 metadata on index.html to be either `max-age=0` or  maybe `no-cache` (https://stackoverflow.com/questions/1046966/whats-the-difference-between-cache-control-max-age-0-and-no-cache) - or perhaps a relatively small number.
2. Programmatically invalidate the cloudfront cache for `/index.html` as part of `amplify publish`. Probably the most performant option, but adds a lot of time to complete `amplify publish`, so the `Cache-Control` approach might be preferred.

**Comment by kaustavghosh06** [comment]
@hawkett  That's a great feature request! 
Could you please open this feature request in this repo -> https://github.com/aws-amplify/amplify-cli instead as I feel this is tied to the Amplify CLI and not the Amplify JS lib. Would be happy to work this out with you. Thanks!

**Comment by hawkett** [comment]
Yep - sorry about that! https://github.com/aws-amplify/amplify-cli/issues/107
