### ISSUE TITLE
Auth.signup with invalid phone number format doesnt resolve the promise

### ISSUE THREAD

**Issue by mateen-hussain** [aws-amplify/amplify-js#1567]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
when signinUp a user with invalid phone number then the promise is neither resolved nor rejected with an exception. Rather the request is hung indefinetly.

```
Auth.signUp({
     username: emailToSignUp,
     password,
		attributes: {
		email: emailToSignUp,
		name: firstName,
		family_name: lastName,
		phone_number:'1234567890',
	},
}).then(user => console.log(user))
  .catch(error => console.log(error));
```

What is the expected behavior?
It should give an exception that invalid phone number format is entered.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

    "aws-amplify": "^1.0.5",
    "aws-amplify-react-native": "^1.0.5",
    "expo": "25.0.0",
    "prop-types": "15.6.0",
    "react": "16.2.0",
    "react-native": "0.52.0",

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by jordanranz** [comment]
The service should return an exception here. Is this problem still occurring for you?

**Comment by mateen-hussain** [comment]
I dont know, havent tested this again.

**Comment by elorzafe** [comment]
I tested with the latest version of amplify, and is working without issues. Please feel free to create a new issue if you still have any concerns. Thanks!
