### ISSUE TITLE
API no configured

### ISSUE THREAD

**Issue by fadur** [aws-amplify/amplify-js#1571]
I keep getting "Api no configured" when calling the API.

src/aws-exports.js looks like this:
`
 ```
 const awsmobile =  { 
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://***.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-***"
};
export default awsmobile;

```
I've tried setting it up manually.
Same results.

in App.js

````
import Amplify, { API, graphqlOperation } from 'aws-amplify';
import awsmobile from './aws-exports';

Amplify.Logger.LOG_LEVEL = 'DEBUG';
Amplify.configure(awsmobile);

const call = async () => {
  const getAll = `query getAll{
      listPrograms{
        items {
          id, name, description
        }
      }
    }`;

  const query = graphqlOperation(getAll);
  const data = await API.graphql(query);
  console.log(data);
};`
```
```
 "aws-amplify": "^1.0.8",
 "aws-amplify-react": "^1.0.6",
  "aws-appsync": "^1.3.4",

```

**Comment by haverchuck** [comment]
Hi @fadur -

This error message is returned when Amplify's API module doesn't receive the data from your aws-exports file... in otherwords, when the API functionality is called before Amplify.configure is successfully called.  

Are you positive that 'call' is only being invoked AFTER Amplify.configure?

**Comment by fadur** [comment]
Yes, I believe so, I keep get the same error.

```
import React from 'react';
import Amplify, { API, graphqlOperation } from 'aws-amplify';

import awsmobile from './aws-exports';

Amplify.Logger.LOG_LEVEL = 'DEBUG';
Amplify.configure(awsmobile);

const Programs = () => {
  const getAll = `query getAll{
    listPrograms{
      items {
        id, title, description
      }
    }
  }`;
  const data = API.graphql(graphqlOperation(getAll));
  console.log(data);
  return <div />;
};


export default Programs;
```
<img width="1632" alt="screen shot 2018-09-04 at 23 02 03" src="https://user-images.githubusercontent.com/4476/45057710-a4b97280-b096-11e8-98d7-7c8b8005827e.png">

**Comment by elorzafe** [comment]
Hi @fadur 
```
const awsmobile =  { 
   "aws_project_region": "eu-west-1",
   "aws_appsync_graphqlEndpoint": "https://***.appsync-api.eu-west-1.amazonaws.com/graphql",
   "aws_appsync_region": "eu-west-1",
   "aws_appsync_authenticationType": "API_KEY",
   "aws_appsync_apiKey": "da2-***"
};
```
You are missing the export piece,`aws-exports.js` should be like this

```
const awsmobile =  { 
   "aws_project_region": "eu-west-1",
   "aws_appsync_graphqlEndpoint": "https://***.appsync-api.eu-west-1.amazonaws.com/graphql",
   "aws_appsync_region": "eu-west-1",
   "aws_appsync_authenticationType": "API_KEY",
   "aws_appsync_apiKey": "da2-***"
};

export default awsmobile;
```

**Comment by fadur** [comment]
@elorzafe it's there.  I just didn't paste it ,sorry. 
Edited.

I've also tried configuring it manually.

**Comment by fadur** [comment]
I've got it to work when i tried using modular imports.
So this works, as opposed to the examples in the doc.

```
import API, { graphqlOperation } from '@aws-amplify/api';
import awsmobile from './aws-exports';

API.configure(awsmobile);
```

**Comment by haverchuck** [comment]
@fadur - Glad to hear that you got it working.  I'm leaving this issue open since I think it demands further investigation.

**Comment by knuula** [comment]
Just dealt with this same error. Uninstalled then reinstalled the aws-amplify npm package. Everything went back to normal and worked again.

**Comment by mattiLeBlanc** [comment]
Yeah, it works also in Angular 7+ using the `API.configure(amplify)`.
A bit confusing because the docs  tell you to use `Amplify.configure(amplify);` which I would assume would configure any child app under Amplify?

**Comment by adrianhdezm** [comment]
I'm trying to use the `API.graphql` as replacement for my existing CRUD data service and I'm getting the same error, and unfortunately the solution proposed by @knuula didn't work for me, also the when I tried to put the configuration as suggested by @mattiLeBlanc `API.configure(config)` I'm getting the following error  `No userPool`.  Any hints about how to debug `aws-amplify` bootstrapping to catch this problem ?

**Comment by mattiLeBlanc** [comment]
Without knowing any of your details: Did you run the amplify cli
configuration steps creating you IAM user. And then did you add AUTH using
amplify add auth?
User pool would only be used for cognito, if I am correct.

**Comment by adrianhdezm** [comment]
Thanks for your comment and hints @mattiLeBlanc, I'm running a simple React project with CRUD operations with Entity type. I did a version working with hooks https://github.com/adrianhdezm/spa-boilerplate/tree/3.0.0, but when I've tried to migrate to Redux and using the `API.graphql` in the context of Redux Observable, the problem showed up. To your first question, the answer is yes, I run the cli and the Auth is working well, I can do all the login register without problemas. The problem appears when I use `API.graphql`. I'm trying to check that `@aws-amplify/api` is imported after the `@aws-amplify/core`.

**Comment by adrianhdezm** [comment]
I solved it by removing `aws-amplify` package and installing the individual feature packages
<img width="643" alt="Bildschirmfoto 2019-06-20 um 01 13 58" src="https://user-images.githubusercontent.com/3098149/59807561-c4a1e600-92f8-11e9-807a-3a2e3b0c20f3.png">

**Comment by mattiLeBlanc** [comment]
that is weird. But glad you solved it.

**Comment by n4development** [comment]
make sure` aws-exports.js` at the same level as App.js

**Comment by epicfaace** [comment]
I had the same issue as @adrianhdezm and the solution they mentioned fixed it for me.

**Comment by cyrfer** [comment]
I received this error when Amplify had not finished checking for a valid user session. My solution was to use the Hub to listen to the auth's `configured` event, then update my React app's state for my  `user` and then fire the API calls I was trying to do after the `user` is valid.
