### ISSUE TITLE
Unable to unsubscribe from specific topics for SPA

### ISSUE THREAD

**Issue by rickydo** [aws-amplify/amplify-js#1572]
**Do you want to request a feature or report a bug?**
Reporting a bug or maybe requesting a new feature...

**What is the current behavior?**
Creating two separate subscriptions for different React components that need to function independently and unsubscribing from one actually unsubscribes all subscriptions. For reproducing purposes, I'll assign them to window variables.

Minimally, if I write 
````
    const topicSub1 = PubSub.subscribe('topic_for_chat_component').subscribe({
      next: data => console.log("chat:", data.value),
      error: error => console.error(error),
      close: () => console.log('Done')
    });

    const topicSub2 = PubSub.subscribe('topic_for_different_component').subscribe({
      next: data => console.log("diff:", data.value),
      error: error => console.error(error),
      close: () => console.log('Done')
    });

   window.topicSub1 = topicSub1;
   window.topicSub2 = topicSub2;
````

**What is the expected behavior?**

If a user is on the page with both components but I need to rerender a single component AND unsubscribe from topicSub1 doing:

`window.topicSub1.unsubscribe()`

in the console should only unsubscribe the user from listening to topic_for_chat_component. However, the user is unable to receive messages from the topicSub2.  

**Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?**

I am using AWS-Amplify: "1.0.7", "Aws-amplify-react": "1.0.6", with React "16.2.0" for Chrome, IE11, Firefox, and Edge on windows 10.  This is new development so I'm not sure if this worked in previous version of Amplify.

Hope this helps. Let me know if anything is unclear.

**Comment by laurib** [comment]
Any solution for that ?

**Comment by yyberi** [comment]
I can confirm the same problem with "aws-amplify": "1.1.22",  "aws-amplify-angular": "2.1.9".
By monitoring "$aws/events/presence/disconnected" topic form Aws Iot Core I can see that connection is disconnected immediately after unsubscribe().

**Comment by powerful23** [comment]
@rickydo thanks for reporting. We have confirmed as a bug and will fix it ASAP.

**Comment by jordanranz** [comment]
The fix for this issue has been made in the referenced PR above. If you are still experiencing any related issue here feel free to open a new issue for us to track. For now, I will close this issue.
