### ISSUE TITLE
TypeError: Cannot read property 'items' of undefined inside API react Connect component

### ISSUE THREAD

**Issue by JeremyKirkham** [aws-amplify/amplify-js#1577]
** Which Category is your question related to? **
API

** What AWS Services are you utilizing? **
API (GraphQL AppSync)
Auth

** Provide additional details e.g. code snippets **
Error:
<img width="544" alt="screen shot 2018-09-05 at 4 22 07 pm" src="https://user-images.githubusercontent.com/7122713/45074716-e3e3d400-b127-11e8-8f4b-6e10befdeea6.png">

My App.js:
```
import React, { Component } from 'react';
import './App.css';
import Amplify, { graphqlOperation }  from "aws-amplify";
import { Connect } from "aws-amplify-react";
import awsmobile from './aws-exports';
Amplify.configure(awsmobile)

class App extends Component {
  render() {
    const ListView = ({ companies }) => (
      <div>
        <h3>All companies</h3>
        <ul>
            {companies.map(company => <li key={company.id}>{company.name} ({company.id})</li>)}
        </ul>
      </div>
    );

    const ListCompanys = `query ListCompanys {
      listCompanys {
        items {
          id
          name
        }
      }
    }`;

    return (
      <div className="App">
        <Connect query={graphqlOperation(ListCompanys)}>
          {({ data: { listCompanys } }) => (
              <ListView companies={listCompanys.items} />
          )}
        </Connect>
      </div>
    );
  }
}

export default App;
```

**Comment by lazydragon** [comment]
I am having similar issues, the same query succeed with API.graphql call directly, but fail with Connect.

**Comment by haverchuck** [comment]
@JeremyKirkham  @lazydragon 

I think the issue here is that because you have placed everything in the render method, it is trying to render the element(s) before the query has completed.

Try setting a condition on the <ListView> like so:

`
    return (
      <div className="App">
        <Connect query={graphqlOperation(ListCompanys)}>
          {({ data: { listTodos } }) => (
             **listTodos &&** <ListView companies={listTodos.items} /> 
          )}
        </Connect>
      </div>
    );
`

**Comment by blbradley** [comment]
@haverchuck Thanks for the tip, worked for me!

**Comment by mikeRChambers610** [comment]
Hi I have a very similar issue. I have a few queries without variables that are exactly the same but are working fine. Now I am executing this query and getting "items" of undefined. 

In the queries console I am getting the correct output for the group messages of the group where I provide the ID. Please let me know if you see anything wrong with the below :

graphql(ListGroupMessages, {
    options: ({ props }) => ({
      fetchPolicy: 'cache-and-network',
      variables: {
        groupID : "91555b01-20bb-400b-b39c-abc298a11f2c",
      }
    }),
    props: props => {
      return {
        messages: props.data.listGroupMessages ? props.data.listGroupMessages.items : [],
      }
    }
  })
