### ISSUE TITLE
Cognito changePassword returning "Incorrect username or password."

### ISSUE THREAD

**Issue by gutobrz** [aws-amplify/amplify-js#1580]
When try to change password for an user already authenticated, I got "Incorrect username or password."

```
function changePassword(currentPassword, newPassword) {
    return new Promise(function(resolve, reject) {
        cognitoUser.changePassword(currentPassword, newPassword, (err, result) => {
            if (err) {
                reject(err);
            } else {
                resolve(result);
            }
        });
    });
}
```
Response headers
```
x-amzn-errormessage: Incorrect username or password.
x-amzn-errortype: NotAuthorizedException:
x-amzn-requestid: 3bc78236-b179-11e8-a474-05a7f0743ba7

{"__type":"NotAuthorizedException","message":"Incorrect username or password."}
```

My user poolId 'us-east-1_aMHyGfO7d

**Comment by haverchuck** [comment]
@gutobrz - Thanks for reporting this.  Just from the information provided, it looks like you actually have the wrong username/password.  Assuming that isn't the case though, you might want to try using the [AWS-Amplify library Auth category](https://aws-amplify.github.io/amplify-js/media/authentication_guide.html#configure-your-app), which would also enable you to enable a [logger](https://aws-amplify.github.io/amplify-js/media/logger_guide#logger) to assist you in debugging.  This would be the recommended way of calling changePassword.

**Comment by gutobrz** [comment]
hi @haverchuck, I will try the Amplify and if the issue continue I let you know.

**Comment by nunosofiane** [comment]
Having the same issue, I guess the error message is misleading!

**Comment by nunosofiane** [comment]
I am using Amplify and having the same issue, I guess the error message is misleading!

**Comment by gruckionvit** [comment]
> @gutobrz - Thanks for reporting this. Just from the information provided, it looks like you actually have the wrong username/password. Assuming that isn't the case though, you might want to try using the [AWS-Amplify library Auth category](https://aws-amplify.github.io/amplify-js/media/authentication_guide.html#configure-your-app), which would also enable you to enable a [logger](https://aws-amplify.github.io/amplify-js/media/logger_guide#logger) to assist you in debugging. This would be the recommended way of calling changePassword.

Can you re-open this. If the inputs for the function are `old password` and `new password` getting an error message of `Incorrect username or password` is not suitable when the user has entered an the wrong password.

The message would be better of as `Incorrect old password`

I now have to create a work around for this. Which is going to be tacky as this response is the same as the sign in error response when a user has typed an incorrect password.
