### ISSUE TITLE
Sign Out Federated(google) users

### ISSUE THREAD

**Issue by imewish** [aws-amplify/amplify-js#1583]
** Which Category is your question related to? **
AWS Amplify
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **

Hello,

I am using AWS amplify to SignUp and SignIn my user pool users and federated users in the pool,

For Cognito User pool user's I use,

`Auth.signIn(this.username, this.password)`

and for federated(Google) users to log in to the pool, I use,

Auth.federatedSignIn() method.

Now the issue is on SignOut.

When I do 

`Auth.signOut()`

it only signOut users who had signIn with `Auth.signIn(this.username, this.password)` method.

it doesnt SignOut federated users. 

Please help.

**Comment by powerful23** [comment]
@imewish To federatedSignIn() method is to get the aws credentials from the Cognito Federated Identity Pool and has nothing to do with Cognito User Pool. To login federated users into the User Pool, you need to use the Cognito Hosted UI: https://aws-amplify.github.io/amplify-js/media/authentication_guide#create-your-own-ui

**Comment by csepulv** [comment]
I have this same issue. While I understand that the Federated Identity Pool is separate from the User Pool, there doesn't seem to be a way to clear/logout of the Identity Pool. 

For example, if I sign in a user (let's say via Google) and then use `Auth.federatedSignIn()`, I will get credentials for the Identity Pool. If I then logout via Google, and login again, when I call `Auth.federatedSignIn()`, there is a console warning. 

```
There is already a signed in user: ${loggedInUser} in your app. 
You should not call Auth.federatedSignIn method again as it may cause unexpected behavior.
```

It is generated by Amplify code: https://github.com/aws-amplify/amplify-js/blob/master/packages/auth/src/Auth.ts#L1347

So how do you sign out / clear the federated credentials?

**Comment by imewish** [comment]
@csepulv 

You need to call this URL on sign out function.
`'https://' + cognitodomain + '/logout?client_id=' + clientId + '&logout_uri=' + signoutUrl`

So your federated user will be signed out properly.

This fixed my issue.

**Comment by csepulv** [comment]
@imewish Thanks. Did you manually clear local storage? (I think there are methods buried in the various Cognito SDKs for this as well)

**Comment by imewish** [comment]
@csepulv the local storage is cleared automatically on signout call.

**Comment by csepulv** [comment]
@imewish thanks

**Comment by jonasao** [comment]
> @csepulv the local storage is cleared automatically on signout call.

Sorry, but this is not working as expected. Local storage is not cleared automatically when calling `Auth.signout()`.

**Comment by jonasao** [comment]
@powerful23 My situation is quite simple: When I call Auth.signOut() local storage is not clear. I had to add a method that manually clears the local storage. Debug mode is turned on.

**Comment by davidlandais** [comment]
I use Facebook with federatedSignIn. When i ask to signOut with Auth.signOut, I got the same problem. token doesn't seems to be cleared.

**Comment by yareyaredesuyo** [comment]
When using in React native (like Expo)

```js
Auth.federatedSignIn({provider: 'Google'}) // browser cache

Auth.signOut(); // browser cache exists
```

does not affect to browserr signout (test in mobile safari).

How should be solved?

**Comment by imewish** [comment]
@yareyaredesuyo  Try calling this url on sign out.

`'https://' + cognitodomain + '/logout?client_id=' + clientId + '&logout_uri=' + signoutUrl` 

Also, for federated login, i later realized `Auth.federatedSignIn({provider: 'Google'})` not a recommended method.

**Comment by malithjkmt** [comment]
@yareyaredesuyo 
Can you please tell us, why `Auth.federatedSignIn({provider: 'Google'})` not a recommended method ?

**Comment by sammartinez** [comment]
Im going to close this issue as @imewish was able to solve his issue. Please feel free to reopen if you are still experiencing this issue.

**Comment by daniel500tech** [comment]
@imewish can you explain why `Auth.federatedSignIn({provider: 'Google'})` is not recommended?
Is there another recommended way?

And does manually calling the url (`'https://' + cognitodomain + '/logout?client_id=' + clientId + '&logout_uri=' + signoutUrl`) you suggested is still a valid solution?
Because I can see in the source code that it's being called only if the user has signed in via hosted ui ([here](https://github.com/aws-amplify/amplify-js/blob/master/packages/auth/src/Auth.ts#L1461))

I'm using `aws-amplify@2.3.0`

**Comment by ThomasCarca** [comment]
I'm having the same issue. Has something been done to prevent using a hack such as manually calling a formatted url ?

**Comment by cristhian-boc** [comment]
@ThomasCarca I've managed to solve this using an "incognito" web browser, so Google/Facebook can't cache anything there.

**Comment by aibrahim3546** [comment]
> p

How did you call this? When i use get method, it throws me `Network Error`.

**Comment by MDangleben** [comment]
> @yareyaredesuyo Try calling this url on sign out.
> 
> `'https://' + cognitodomain + '/logout?client_id=' + clientId + '&logout_uri=' + signoutUrl`
> 
> Also, for federated login, i later realized `Auth.federatedSignIn({provider: 'Google'})` not a recommended method.

Seconding the request to elaborate on this method.

**Comment by cristhian-boc** [comment]
> > When using React, it works pretty well.
> > But, When using in React native (like Expo)
> > ```js
> > Auth.federatedSignIn({provider: 'Google'}) // browser cache
> > 
> > Auth.signOut(); // browser cache exists
> > ```
> > 
> > 
> > Signout does not affect to browser cache clean (test in mobile safari).
> > How it should be solved?
> 
> Hey, I'm facing same issue. Did you find any workaround this?

Hi @Reenagrg100 . I've already posted a workaround. Did you try it?

**Comment by Reenagrg100** [comment]
> > > When using React, it works pretty well.
> > > But, When using in React native (like Expo)
> > > ```js
> > > Auth.federatedSignIn({provider: 'Google'}) // browser cache
> > > 
> > > Auth.signOut(); // browser cache exists
> > > ```
> > > 
> > > 
> > > Signout does not affect to browser cache clean (test in mobile safari).
> > > How it should be solved?
> > 
> > 
> > Hey, I'm facing same issue. Did you find any workaround this?
> 
> Hi @Reenagrg100 . I've already posted a workaround. Did you try it?

No, I only found that URL to hit and that doesn't seem to be work in my case. Any other solution?

**Comment by cristhian-boc** [comment]
@Reenagrg100 we used https://github.com/proyecto26/react-native-inappbrowser in our project. It will only work with iOS though. This is our code:
```
import config from './aws-exports'
const urlOpener = async (url, redirectUrl) => {
  if (await InAppBrowser.isAvailable()) {
    const result = await InAppBrowser.openAuth(url, null, { ephemeralWebSession: true })
    console.log('result from webview', result)
    if (result.type === 'success' && result.url) {
      return Linking.openURL(result.url)
    }
    Hub.dispatch('authCancel', { event: 'cancelled', data: result })
  } else {
    return Linking.openURL(url)
  }
}

config.oauth.urlOpener = Platform.OS === 'ios' ? urlOpener : null
```

**Comment by Reenagrg100** [comment]
> @Reenagrg100 we used https://github.com/proyecto26/react-native-inappbrowser in our project. It will only work with iOS though. This is our code:
> 
> ```
> import config from './aws-exports'
> const urlOpener = async (url, redirectUrl) => {
>   if (await InAppBrowser.isAvailable()) {
>     const result = await InAppBrowser.openAuth(url, null, { ephemeralWebSession: true })
>     console.log('result from webview', result)
>     if (result.type === 'success' && result.url) {
>       return Linking.openURL(result.url)
>     }
>     Hub.dispatch('authCancel', { event: 'cancelled', data: result })
>   } else {
>     return Linking.openURL(url)
>   }
> }
> 
> config.oauth.urlOpener = Platform.OS === 'ios' ? urlOpener : null
> ```

Okay, so in my project, I'm using react-native safari view for iOS. I'm not getting how you are fixing that problem by above code. Can you please elaborate more.
Thanks in advance!

**Comment by cristhian-boc** [comment]
@Reenagrg100 the trick is using this property:

`ephemeralWebSession (Boolean) | Prevent re-use cookies of previous session (openAuth only) [true/false]`

It will not store cookies from Amplify, so whenever the federated UI is presented, it will be a fresh page. The library I shared with you is using Safari as a modal (when using openAuth method). It's the required method by Apple for them to approve your iOS app. I'm not sure if there is another library out there that can handle this feature, but you will need to further investigate in that case on your own, sorry.

**Comment by Reenagrg100** [comment]
> @Reenagrg100 the trick is using this property:
> 
> `ephemeralWebSession (Boolean) | Prevent re-use cookies of previous session (openAuth only) [true/false]`
> 
> It will not store cookies from Amplify, so whenever the federated UI is presented, it will be a fresh page. The library I shared with you is using Safari as a modal (when using the openAuth method). It's the required method by Apple for them to approve your iOS app. I'm not sure if there is another library out there that can handle this feature, but you will need to further investigate in that case on your own, sorry.

Thank you so much, @cristhian-boc !! I know about this library to open the in-app browser. The same behaviour is achieved by react-native safari view library. Well I'll look into it how can I achieve same in my case.

**Comment by wywarren** [comment]
> @csepulv
> 
> You need to call this URL on sign out function.
> `'https://' + cognitodomain + '/logout?client_id=' + clientId + '&logout_uri=' + signoutUrl`
> 
> So your federated user will be signed out properly.
> 
> This fixed my issue.

We're trying to do this as well, although manually navigating to the URL works as expected, trying to invoke it with js throws CORS errors as the logout endpoint does not have `Access-Control-Allow-Origin` headers nor is there a way to set them in cognito as far as I know. I've also tried hitting it with a hidden iframe but also `X-Frame-Options` is set to deny as expected.

**Comment by jyoo** [comment]
> > @yareyaredesuyo Try calling this url on sign out.
> > `'https://' + cognitodomain + '/logout?client_id=' + clientId + '&logout_uri=' + signoutUrl`
> > Also, for federated login, i later realized `Auth.federatedSignIn({provider: 'Google'})` not a recommended method.
> 
> Seconding the request to elaborate on this method.

Me too. Can anyone know why `Auth.federatedSignIn({provider: 'Google'})` is not a recommended method? If there is any problem with the method (and if it should not be used), it should not be in the official documentation.
