### ISSUE TITLE
Cannot localize SignIn dialogs - two instances of I18n?

### ISSUE THREAD

**Issue by jfo8000** [aws-amplify/amplify-js#1584]
For AWS Amplify React login UI - recently the localization imports for SignIn.js changed to '@aws-amplify/core' .   

```
// new imports in SignIn.js (react component)
import { I18n, JS, ConsoleLogger as Logger } from '@aws-amplify/core';

// used to be the same as the public util class
import { I18n } from 'aws-amplify';
```
This means if someone localizes the dialog using the aws-amplify import, the dictionary is not picked up. It seems as if there are now two localization dictionary instances floating around?  

```
// https://aws-amplify.github.io/amplify-js/media/i18n_guide
import { I18n } from 'aws-amplify';
...
const dict = {
    'en': {
        'Sign In': "Log In",
        'Sign Up': "Welcome!"
    },
};
I18n.putVocabularies(dict);
```

If I immediately do a `I18n.get('Sign In') ` I get the correct key, but my dictionary is not passed down to the SignIn component.

Am I missing something - is this as simple as changing my import?

**Comment by haverchuck** [comment]
@jfo8000 

If I understand you're question correctly, you are asking if you can continue to import I18n from `aws-amplify` in your app when the aws-amplify-react components are importing it form `@aws-amplify/core`?

If so , I believe the answer is yes.

For example, I tested with the following:

```
import React, { Component } from 'react';
import './App.css';
import Amplify, { graphqlOperation, I18n }  from "aws-amplify";
import awsmobile from './aws-exports';
import { Authenticator } from 'aws-amplify-react';
Amplify.configure(awsmobile)

class App extends Component {
  render() {


    const dict = {
      'en': {
        'Foo': 'Bar',
        'Password': 'I am the new password value!'
      }
    };

    I18n.putVocabularies(dict)

    return (
      <div className="App">
        <h1> { I18n.get('Foo') } </h1>
        <Authenticator />
      </div>
    );
  }
}

export default (App);
```
I'm importing I18n from `aws-amplify`, while the `<Authenticator />` is importing it from `@aws-amplify/core`.   

Both the value in my header as well as in the auth component are successfully translated:

![screen shot 2018-09-07 at 10 54 57 am](https://user-images.githubusercontent.com/10621276/45235068-8f0d9e00-b28c-11e8-9bd7-5838cafa83db.png)

Does this address your question?

**Comment by jfo8000** [comment]
My code which used to work, broke upon upgrade to aws amplify 0.1.54.  

I have since copied the code for SignIn.js to my own codebase and changed the import to the old import style... leaving everything else the same.   This seems to have fixed it?  I think there's a bug.  

I don't want to have my own copy of SignIn just to change the strings.  Also this solution will break in the future, as I see you've relabeled everything in future versions.  

What is the best practice to add a 'Welcome to my website' to the login dialog?  Can we have a better solution here as my boss doesn't like the default text.  I can pretty much change everything else in the theme.

**Comment by jfo8000** [comment]
(For reference I am attempting to format the sign dialog to look and feel like the Pintrest login).   

I can do most of it through themes.

![image](https://user-images.githubusercontent.com/16273166/45247012-f5a3c200-b347-11e8-8371-95f5c66759e3.png)
