### ISSUE TITLE
Typo on "Retrieve Current Authenticated User" Documentation

### ISSUE THREAD

**Issue by zacharywenner** [aws-amplify/amplify-js#1587]
**Describe the bug**
Hi, there's a small typo in "Retrieve Current Authenticated User" in the documentation.

**To Reproduce**
1. Go to 
https://aws-amplify.github.io/amplify-js/media/authentication_guide#retrieve-current-authenticated-user
2. There's a typo, a semicolon after ".then..." statement.

**Expected behavior**
No semicolon after then .then statement, since the ".catch..." statement comes after.

**Screenshots**
![screen shot 2018-09-07 at 12 34 25 pm](https://user-images.githubusercontent.com/10377501/45239540-71dfcc00-b29a-11e8-87b8-0e932bf9d8ce.jpg)

**Comment by haverchuck** [comment]
@zacharywenner - Nice catch! I'm submitting a PR.
