### ISSUE TITLE
how custom Graphql Schema (eg: Add mutation)

### ISSUE THREAD

**Issue by mickadoua** [aws-amplify/amplify-js#1594]
** Which Category is your question related to? **
API GraphQl Scheam

** What AWS Services are you utilizing? **
AppSync 

** Provide additional details e.g. code snippets **
Hello, I would like to know the best way to add Custom mutation, type...

= What I tried
1) I tried to Add a mutation "updateUserLocation" on Schema.graphql. This mutation was never Added on aws appsync or on build/schema.graphql
The other mutation "updateUser" and type "UpdateUserInput" was not correctly updated 

2) I tried to add on build/schema.graphql And on Appsync dashboard. when i run `amplify push` both was overide 

here my schema.graphQl
```
input CoordsInput {
  lat: Float
  lon: Float
}
input UpdateUserLocationInput {
  id: ID!
  location: CoordsInput
}
input UpdateUserInput {
  id: ID!
  name: String
  location: CoordsInput
}

type Mutation {
  updateUserLocation(input: UpdateUserLocationInput!): User
  updateUser(input: UpdateUserInput!): User
}
```
Thanks for your help

**Comment by mickadoua** [comment]
any update about this ? 
More globally, How to override schema and resolver ? 
other idea : disable schema (and resolver) generation if it was edited by the user

**Comment by tobiv** [comment]
See https://github.com/aws-amplify/amplify-cli/issues/74

**Comment by kaustavghosh06** [comment]
Please re-open this issue if you think  https://github.com/aws-amplify/amplify-cli/issues/74 hasn't answered your queries.
