### ISSUE TITLE
How to hide Create account in sign in dialog?

### ISSUE THREAD

**Issue by mogadanez** [aws-amplify/amplify-js#1596]
I choose "Only allow administrators to create users"
but  create account link is still present.
How to hide it? maybe it some config option?

**Comment by haverchuck** [comment]
@mogadanez  - Are you using a particular front-end framework?  If so, which one?

**Comment by mogadanez** [comment]
React

пн, 10 сент. 2018 г., 18:06 Dustin Noyes <notifications@github.com>:

**Comment by haverchuck** [comment]
@mogadanez Yes - you can hide specific components.  Please see [this documentation](https://aws-amplify.github.io/docs/js/authentication#using-the-authenticator-component-directly).

I'm closing this issue for now, but please feel free to reopen it.

**Comment by nishant8BITS** [comment]
If anyone wants to hide signup link/Create account link in react then you can use:

`      <AmplifySignIn slot="sign-in" usernameAlias="email" hideSignUp />`
