### ISSUE TITLE
Cognito: Unable to access authentication details

### ISSUE THREAD

**Issue by brianfitzgerald** [aws-amplify/amplify-js#1597]
**Describe the bug**

Here's my code (written in React with the latest version of Amplify):

    Auth.signIn(this.state.username, this.state.password)
      .then(user => {
        console.log("sign in success");
        console.log(user);
        userStore.setUser(user);
        Auth.currentSession()
          .then(sess => {
            console.log("current session");
            console.log(sess);
          })
          .catch(err => {
            console.log("current session err", err);
          });
      })
      .catch(err => {
        console.log("sign in err");
        console.log(err);
      });

This code succeeds in logging in, but then when I attempt to call currentSession, it gives me `AuthClass - Failed to get user from user pool`. I then get `current session err No current user`. The status of the user is `NEW_PASSWORD_REQUIRED`, if that might make a difference.

**Comment by brianfitzgerald** [comment]
I also get `    const combinedPlugins = { ...categoryPlugins, ...providerPlugins };
                              ^^^

SyntaxError: Unexpected token ...`

when I run `amplify configure`, but I suspect that is unrelated.

**Comment by kaustavghosh06** [comment]
Hey Brian. The above error is due to an old version of Node that you must be using. Please upgrade to the latest node version and you should be fine.

**Comment by powerful23** [comment]
@brianfitzgerald I am gonna close the issue. Please reopen it if you still have the question.
