### ISSUE TITLE
CSS of withAuthenticator easily broken

### ISSUE THREAD

**Issue by Gerharddc** [aws-amplify/amplify-js#1598]
**Describe the bug**
When you wrap a component that uses something like semantic-ui-css for its styling with withAuthenticator then the styling of the Authenticator is automatically broken.

**To Reproduce**
1. Create a barebones React app that uses withAuthenticator
2. Install semantic-ui-css
3. Import semantic-ui-css in any of your components

**Expected behavior**
The styling of the Authenticator screens should not be so easily affected by the presence of the CSS of common UI libraries such as Semantic-UI.

**Screenshots**
<img width="496" alt="screen shot 2018-09-09 at 11 20 10" src="https://user-images.githubusercontent.com/11624490/45263036-88189400-b422-11e8-9898-4e4632361068.png">

**Desktop:**
 - OS: MacOS High Sierra
 - Browser Safari
 - Version 11.1.2

**Comment by jordanranz** [comment]
Hi @Gerharddc. Thanks for the feedback. 

The problem occurring here is that Semantic UI is applying a global box-sizing property. Explicitly setting this on the Amplify UI side will protect this from being set by parent or global styles. I will go ahead and make this fix.

**Comment by jordanranz** [comment]
#1754 should fix this issue. Please reopen if you have any further questions or concerns.
