### ISSUE TITLE
User credential is not available after successful sign-in

### ISSUE THREAD

**Issue by alangault** [aws-amplify/amplify-js#1601]
I am trying to setup federated SSO using Ping Federate and OpenID Connect.  Code hits AWS Cognito and is redirected PingFed.  After logging in successfully, AuthenticationCallback is called.

The call to Auth.currentAuthenticatedUser() in getCreds() returns "No current user".  If I continue, I see "message": "Missing Authentication Token" in the API Gateway log with a 400 error.

I've attached the App.js I'm using, which I cobbled together from a couple of sources.  Any help would be greatly appreciated.

App.js:

    import React, { Component } from 'react';
    import logo from './logo.svg';
    import './App.css';

    import Nav from "./Nav";
    import {
      BrowserRouter as Router,
      Route,
      Redirect
    } from 'react-router-dom';

    import Amplify, { Auth, API } from 'aws-amplify';

    Amplify.Logger.LOG_LEVEL = 'DEBUG';

    Amplify.configure({
      Auth: {
        // REQUIRED only for Federated Authentication - Amazon Cognito Identity Pool ID
        identityPoolId: 'us-east-2:xxxxxxxxxxxxxxxxxxxxxxx',
        
        // REQUIRED - Amazon Cognito Region
        region: 'us-east-2',

        // OPTIONAL - Amazon Cognito User Pool ID
        userPoolId: 'us-east-2xxxxxxxxxxxxx',

        // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
        userPoolWebClientId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx',

        // OPTIONAL - Enforce user authentication prior to accessing AWS resources or not
        mandatorySignIn: true,

        oauth: {
          // Domain name
          domain : 'xxxxxxxx.auth.us-east-2.amazoncognito.com', 
          
          // Authorized scopes
          scope : ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin'], 
      
          // Callback URL
          redirectSignIn : 'http://localhost:3000/authentication/callback', 
          
          // Callback URL
          redirectSignOut : 'http://localhost:3000/',
      
          // 'code' for Authorization code grant, 
          // 'token' for Implicit grant
          responseType: 'token',
      
          // optional, for Cognito hosted ui specified options
          options: {
              // Indicates if the data collection is enabled to support Cognito advanced security features. By default, this flag is set to true.
              AdvancedSecurityDataCollectionFlag : true
          }
        }
      },
      API: {
        endpoints: [
          {
            name: "APIGateway_sys",
            region: 'us-east-2',
            endpoint: "https://www.example.com/v2/api"
          },
      ],
      }  
    });

    const OidcValues = {
      'accessToken': 'unknown',
      'idToken': 'unknown'
    };

    const AuthStatus = {
      isAuthenticated: false
    };

    const UrlHelper = {
      getAuthUrl() {
        const config = Auth.configure();
        const { 
          domain,  
          redirectSignIn,
          redirectSignOut, 
          responseType } = config.oauth;

        const clientId = config.userPoolWebClientId;

        const url = 'https://' + domain + '/oauth2/authorize?&response_type=' + responseType + '&client_id=' + clientId + '&scope=email+openid+profile+aws.cognito.signin.user.admin&redirect_uri=' + redirectSignIn;

        console.log("url:  " + url);
        console.log("config = ", config);

        return url;
      },

      generateNonce(length) {
        var text = "";
        var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

        for(var i = 0; i < length; i++) {
            text += possible.charAt(Math.floor(Math.random() * possible.length));
        }

        return text;
      },

      getParams(url) {
        var regex = /[#?&]([^=#]+)=([^&#]*)/g,
            params = {},
            match;

        // eslint-disable-next-line
        while (match = regex.exec(url)) {
          params[match[1]] = match[2];
        }

        return params;
      }
    };

    const StorageHelper = {
      saveNonce(nonce) {
        if (typeof(Storage) !== "undefined") {
          localStorage.setItem("nonce", nonce);
        }
      },

      loadNonce() {
        if (typeof(Storage) !== "undefined") {
          var nonce = localStorage.getItem("nonce");

          localStorage.removeItem("nonce");

          return nonce;
        }
      }
    };

    const SSOTest = () => (
      <Router>
        <div className="container">
          <Nav/>

          <Route path="/" exact component={Home}/>
          <Route path="/login" component={Login}/>
          <Route path="/authentication/callback" component={AuthenticationCallback}/>

          <PrivateRoute path="/tokens/access" component={AccessToken}/>
          <PrivateRoute path="/tokens/id" component={IdToken}/>
          <PrivateRoute path="/tokens/callapi" component={CallAPI}/>

        </div>
      </Router>
    );

    const PrivateRoute = ({ component: Component, ...rest }) => (
      <Route {...rest} render={props => (
        AuthStatus.isAuthenticated ? (
          <Component {...props}/>
        ) : (
          <Redirect to={{
            pathname: '/login',
            state: { from: props.location }
          }}/>
        )
      )}/>
    )

    const Home = () => (
      <div className="mt">
        <h1>React.js OIDC Sample</h1>

        <p>
          This page is unprotected by Ping Federate.
        </p>
      </div>
    );

    const AccessToken = () => (
      <div className="mt">
        <div className="panel panel-default">
          <div className="panel-heading">
            <h3 className="panel-title">Access Token</h3>
          </div>
          <div className="panel-body">
            {OidcValues.accessToken}
          </div>
        </div>
      </div>
    );

    const IdToken = () => (
      <div className="mt">
        <div className="panel panel-default">
          <div className="panel-heading">
            <h3 className="panel-title">ID Token</h3></div>
          <div className="panel-body">
            {OidcValues.idToken}
          </div>
        </div>
      </div>
    );

    class AuthenticationCallback extends React.Component {
      constructor(props) {
        super(props);
        this.redirectTo = '/';
      }

      componentWillMount() {
        // eslint-disable-next-line
        var storedNonce = StorageHelper.loadNonce();
        var params = UrlHelper.getParams(window.location.href);

        OidcValues.idToken = params['id_token'];
        OidcValues.accessToken = params['access_token'];

        this.redirectTo = decodeURIComponent(params['state']);

        // Set authenticated to true
        AuthStatus.isAuthenticated = true;

        this.getCreds();
      }

      async getCreds() {
        // THIS CALL RETURNS "No current user", although i've just signed on
        let user = await Auth.currentAuthenticatedUser();
        console.log("authenticated user: " + user);
      }

      render() {
        return (
          <Redirect to={this.redirectTo} />
        )
      }
    }

    class Login extends React.Component {
      state = {
        redirectToReferrer: false
      }

      componentWillMount() {
        const { from } = this.props.location.state || { from: { pathname: '/' } };

        var nonce = UrlHelper.generateNonce(32);
        StorageHelper.saveNonce(nonce);

        var authUrl = UrlHelper.getAuthUrl();

        console.log('Redirecting: ' + authUrl);

        window.location = authUrl;
      }

      render() {
        return (
          <section>Redirecting to SSO...</section>
        )
      }
    }

    class CallAPI extends React.Component {
      constructor(props) {
        super(props);
        this.redirectTo = '/';
      }

      componentDidMount() {
        this.get();
      }

      get() {
      // FOS API
        let apiName = "FOSAPIGateway_sys";
        let path = "/blockColumns";

        let myInit = { // OPTIONAL
          headers: { 
            'x-api-key': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
          }
        };

        API.get(apiName, path, myInit).then(response => {
            console.log('API.get: ', response);
        }).catch(error => {
            console.log('Error:  ', error);       
        });
      }

      render(){
        return (
          <h1>CallAPI</h1>
        )
      }
    }

    export default SSOTest;

**Comment by powerful23** [comment]
@alangault if you are using Cognito Hosted UI, I would recommend you to use the react component we provided: https://aws-amplify.github.io/amplify-js/media/authentication_guide.html#launching-the-hosted-ui-in-react
If you would prefer to do it yourself, you can follow this doc: https://github.com/aws-amplify/amplify-js/pull/1552/files to check the user after redirecting back.

**Comment by jordanranz** [comment]
Going to close the question has been answered. Please reopen if you have any related questions or concerns.
