### ISSUE TITLE
Cannot "signOut" federated session

### ISSUE THREAD

**Issue by thrixton** [aws-amplify/amplify-js#1602]
**Describe the bug**
It is not possible to clear the session of a federated session.

**To Reproduce**

1. Sign in with a federated provider
```Typescript
Auth.federatedSignIn(
            'google',
            {
              token: user.idToken,
              expires_at: expirationDate.getTime()
            },
            {
              email: user.email
            }
          )
            .then(() => {
              console.log('federated signin ok');
// ...
```
2. Clear cached Id 
```Typescript
Auth.currentCredentials()
      .then(creds => {
        if (creds) {
          console.log('Clearing cached credentials');
          creds.clearCachedId();
          AWS.config.credentials = null;
// ...
```

**Expected behavior**
Local storage keys `aws-amplify-cachefederatedInfo` and `aws-amplify-federatedInfo` should be cleared.
`Auth.currentCredentials` should be null.

**Desktop (please complete the following information):**
 - Windows
 - Chrome
 - Version 69.0.3497.81 (Official Build) (64-bit)

**Comment by powerful23** [comment]
@thrixton for now you can only clear the cached info by calling `Auth.signOut()`

**Comment by thrixton** [comment]
Thanks @powerful23 , that works. I tried that previously and was getting an error with a federated identity, must have been something else.
However I'm still seeing one element left in local storage which has the user's email address in it, is this a bug?
`CognitoIdentityServiceProvider.XXXXX.user@email.com.clockDrift`

**Comment by powerful23** [comment]
@thrixton this item is not related to the federation login. It's created when you log in with your Cognito Account. It should be deleted after signing out. Will look into that.
