### ISSUE TITLE
React customize-withauthenticator doesnt work on v2.0.0-2.0.1

### ISSUE THREAD

**Issue by DmitryNefedov** [aws-amplify/amplify-js#1603]
**Describe the bug**
Using `withAuthenticatior` with passed elements [as described in the guide](https://aws-amplify.github.io/amplify-js/media/authentication_guide#customize-withauthenticator) works on v 1.0.8 but shows an empty page on v 2.0.0 or 2.0.1

**To Reproduce**
1. use code based on Docs
```
import React from 'react';
import { withAuthenticator, SignIn, SignUp, ForgotPassword, RequireNewPassword } from 'aws-amplify-react';

class CustomNoSignUp extends SignUp {

  render() {
    if (this.props.authState !== 'signUp') { return null; }
    return (<div>Please check with your administrator to create a user</div>);
  }
}

class App extends React.Component {
  render() {

    if (this.props.authState !== 'signedIn') { return null; }

    return (
     <div style={{textAlign: 'center'}}>
        <h1>Hello World</h1>
      </div>);
  }
}

export default withAuthenticator(App,
  { includeGreetings: true },
  [
    <SignIn />,
    <CustomNoSignUp/>,
    <ForgotPassword/>,
    <RequireNewPassword/>
  ]
);
```

**Expected behavior**
Login form should be shown, after login "Hello World" should be shown

**Actual behavior**
Blank screen, no errors in console/dev-server

**Comment by pronevich** [comment]
Same issue

**Comment by bluefig99** [comment]
same issue . Can someone look in to this issue?

**Comment by DmitryNefedov** [comment]
@emmkong,
its not just hiding sign up.
It hides the wrapped element.
If it has been changed to use with `showComponent`, shouldnt the docs been updated?

**Comment by emmkong** [comment]
@DmitryNefedov I agree that the behavior of custom Auth UI components has been changed since version 2.0 and it hasn't mentioned in any document yet. :(

Do you mind to elaborate more about what wrapped element that you are expecting so that I could help you a bit more. Thanks.

**Comment by richardm-surevine** [comment]
The same thing happens if you use the base SignUp component without even customising it, if you pass it in like this.

Seems a bit broken.

**Comment by adamdiy** [comment]
having the same problem with v1.1.19

**Comment by robhyb19** [comment]
Bump.
Seeing the same issue after following the docs ( https://aws-amplify.github.io/docs/js/authentication ) and after following recommendations made in this issue.

**Comment by jordanranz** [comment]
FYI, we have started an RFC discussion for a proposed Amplify UI Component refactor to increase customizability and flexibility for our components. Please feel free to add any additional comments to the following issue:

https://github.com/aws-amplify/amplify-js/issues/3279
