### ISSUE TITLE
Use Amplify + Aws SDK

### ISSUE THREAD

**Issue by henrysachs** [aws-amplify/amplify-js#1604]
Hey Guys,

i would really like the S3 Part of the AWS SDK because i'm missing some of the features in amplify currently but like the auth part. Is it somehow possible to use both?

**Comment by henrysachs** [comment]
So I found a possibility.. If i export the whole aws-sdk in the Facet.js it seems to work.. But for me that doesn't feel right.

**Comment by henrysachs** [comment]
Sorry guys i found the Solution myself. For everyone using Angular this is how you can import things from the AWS-SDK even if your IDE doesn't show any recommendations. 

```javascript
import * as S3 from 'aws-sdk/clients/s3';

	constructor(private amplifyService: AmplifyService) {}
	ngOnInit() {
		this.amplifyService
			.auth()
			.currentCredentials()
			.then((creds) => {
				console.log(creds);
				const s3 = new S3({ credentials: creds, region: 'eu-central-1' });
				s3.listObjectsV2({ Bucket: environment.aws_user_files_s3_bucket }, (err, data) => {
					if (err) {
						console.log(err);
					} else {
						console.log(data);
					}
				});
			});
          }
```

**Comment by henrysachs** [comment]
The Problem was just that vscode doesnt identify this. I was a bit too reliant on my ide there. Vs code(and maybe others) tried to import the AWS object from amplify/core.

**Comment by jkeys-ecg-nmsu** [comment]
@mlabieniec https://github.com/aws-amplify/amplify-js/issues/1604#issuecomment-420047781 contains a dead link

**Comment by mlabieniec** [comment]
@jkeys-ecg-nmsu updated link (very last section here): https://aws-amplify.github.io/docs/js/start#next-steps
