### ISSUE TITLE
Can't use amplifyjs with federated identities with cognito user pools authorizer on api-gateway

### ISSUE THREAD

**Issue by behnamx** [aws-amplify/amplify-js#1609]
My ultimate goal is to make a user only able to read/delete/insert photos they own into S3 in addition to my regular note-taking app (note context with photo). From my understanding I have to use federated identities. However whenever I put the identity pool id into my amplifyjs config file it breaks all api-gateways calls that use cognito user pools authorizer. If I can get help with this that would be terrific!! I want to continue protecting api calls with authentication.

**Comment by behnamx** [comment]
I think I get a different jwt token from the user session when the federated identities ID is in the config file. That gives me 401 unauthorized and/or a cors issue.

**Comment by behnamx** [comment]
Cognito User Pools Id with User Pools client ID works perfectly in config file.

**Comment by elorzafe** [comment]
Hi @behnmax did you take a look into this sample https://github.com/aws-samples/aws-amplify-graphql You will see a similar use case.

For API Gateway you could AWS_IAM to protect your api. [amplify-cli](https://github.com/aws-amplify/amplify-cli) has a built-in functionality to create protected APIs, and also implement CRUD  operations.
