### ISSUE TITLE
Add Golang/other lambda backend language support

### ISSUE THREAD

**Issue by 0xdevalias** [aws-amplify/amplify-js#1620]
**Is your feature request related to a problem? Please describe.**
I would like to be able to automagically deploy non-javascript based lambda functions (eg. golang)

**Describe the solution you'd like**
Add support for using any supported lambda languages, particularly Golang

**Describe alternatives you've considered**
* Manually adding the required CloudFormation/etc to my repo.
* Using pre-deployed lambda's (from AWS SAM or similar)

**Additional context**
N/A

**Comment by mlabieniec** [comment]
@0xdevalias can you please open this issue on the cli repo:
https://github.com/aws-amplify/amplify-cli/issues/new?template=feature_request.md

**Comment by 0xdevalias** [comment]
https://github.com/aws-amplify/amplify-cli/issues/156
