### ISSUE TITLE
How can I confirm sign-up with a default aws-mobile-react-sample setup?

### ISSUE THREAD

**Issue by Nadesri** [aws-amplify/amplify-js#1622]
** Which Category is your question related to? **
aws-mobile-react-sample

** What AWS Services are you utilizing? **
Cognito/IAM

** Provide additional details e.g. code snippets **
I'm trying to play around with aws-mobile-react-sample for the first time, but I can't get past the "Confirm Sign Up" screen. I was following the instructions on Readme.md; specifically I tried the following:
1. Ran:
  $ awsmobile start my-project react
  $ cd my-project
  $ awsmobile publish
2. Navigated to the new hosting-mobilehub AWS address returned by the console
3. Click "Sign Up"
4. Enter a User Name, Password, Email, and Phone Number
5. At the "Confirm Sign Up" page, wait for the code <-- got stuck here

I never end up receiving the code on my phone.... I suppose I'm doing something silly, but I have no idea what's wrong. Any help is appreciated. Thanks :)

**Comment by powerful23** [comment]
@Nadesri can you check the network requests to see if sign up request failed? If not, the most probable reason is that the sms service is not responding.

**Comment by powerful23** [comment]
@Nadesri No I think, but we will look into that. So the request [`signUp`](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_SignUp.html) didn't fail right? Maybe you can try again in your local.

**Comment by jordanranz** [comment]
This issue is stale. Please open a new issue if you are having any more related questions or concerns.
