### ISSUE TITLE
Analytics.record() is not sending data to Pinpoint

### ISSUE THREAD

**Issue by jorge-sanz** [aws-amplify/amplify-js#1623]
** Which Category is your question related to? **

** What AWS Services are you utilizing? **
AWS Amplify Analytics + AWS Pinpoint

** Provide additional details e.g. code snippets **
I configure Analytics on my React Native Expo app like this:
```javascript
Analytics.configure({
    disabled: false,
    autoSessionRecord: true,

    AWSPinpoint: {
      appId: appId,
      region: region,
      clientContext: {
        clientId: userId,
        appTitle: Constants.manifest.name,
        appVersionCode: Constants.manifest.version,
        platform,
        platformVersion,
        model,
        locale: user.language,
      },
      bufferSize: 1000,
      flushInterval: 5000, // 5s
      flushSize: 100,
      resendLimit: 5,
    },
  });
```

And I call the method like this at some point of my app:

```javascript
Analytics.record({ name: eventName });
```

But it doesn't work. That event is not sent to AWS Pinpoint.

What should I check?

Thank you 🙂

**Comment by elorzafe** [comment]
Hi @jorge-sanz Analytics required Auth to be configured (it needs an identityPoolId). We updated the docs to make it more explicit on Manual setup section [here](https://aws-amplify.github.io/amplify-js/media/analytics_guide#manual-setup). I hope this works for you. I will close the issue but feel free to reopen if it doesnt work for you. 

Is much easier if you use amplify-cli to create your resources and then integrate with your App. Take a look on [this](https://aws-amplify.github.io/amplify-js/media/analytics_guide#automated-setup) section.
