### ISSUE TITLE
Customize AWS Amplify Authentication UI for React

### ISSUE THREAD

**Issue by chgasparoto** [aws-amplify/amplify-js#1624]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
I'm trying to create a customized UI for all the pages related to the authentication on a React app. I need a big form with various fields to be inserted when the user is signing up.

I was following this tutorial (https://github.com/richardzcode/Journal-AWS-Amplify-Tutorial) until a realize the versions for `aws-amplify` and `aws-amplify-react` were different.

I tried to read the documentation about it but is too superficial, I can't get it, really. https://aws-amplify.github.io/amplify-js/media/authentication_guide#create-your-own-ui

I tried to look up directly in the `aws-amplify-react` source code and reproduce the same pattern that I found there, no success.

Here my Auth component:
 
```
import { Authenticator } from 'aws-amplify-react'

  import {
    LoginForm,
    RegisterForm,
    ConfirmRegisterForm,
    VerifyContactForm,
    ForgotPasswordForm
  } from '../components'

  export default class Login extends Component {
    render () {
      return (
        <Authenticator hideDefault>
          <LoginForm />
          <RegisterForm />
          <ConfirmRegisterForm />
          <VerifyContactForm />
          <ForgotPasswordForm />
        </Authenticator>
      )
    }
  }
```
And here my LoginForm:

```
    import React from 'react'
    import { Button, Form, Grid, Header, Image, Message, Segment } from 'semantic-ui-react'
    import Auth from '@aws-amplify/auth'
    import { ConsoleLogger as Logger } from '@aws-amplify/core'
    import { AuthPiece } from 'aws-amplify-react'

    const logger = new Logger('LoginForm')

    class LoginForm extends AuthPiece {
      constructor (props) {
        super(props)
        this.signIn = this.signIn.bind(this)
        this._validAuthStates = ['signIn', 'signedOut', 'signedUp']
        this.state = {}
        console.log('this.props->', JSON.stringify(this.props))
      }

      signIn () {
        const { username, password } = this.inputs
        logger.debug(`username: ${username}`)

        Auth.signIn(username, password)
        .then(user => this.changeState('signedIn', user))
        .catch(err => this.error(err))
      }

      showComponent (theme) {        
        const { hide = [] } = this.props

       if (hide && hide.includes(LoginForm)) {
        return null
       }

       return (
         {/* My Login Form */}
       )
    }
  }
  export default LoginForm
```
When I go to the login form the `authState` is always as `loading`. I can't make them work properly because of this.

Any help is welcome.

**Comment by powerful23** [comment]
@chgasparoto Hi, I guess that's because you didn't can you try to include `Greetings` component:
```js
import { Greetings } from 'aws-amplify-react';

<Authenticator hideDefault>
          <LoginForm />
          <RegisterForm />
          <ConfirmRegisterForm />
          <VerifyContactForm />
          <ForgotPasswordForm />
          <Greetings/>
       </Authenticator>
```

Also can you provide some debug info by putting `window.LOG_LEVEL='DEBUG'` in you code.

**Comment by yuth** [comment]
The current implementation of react component require `Greetings` component to be always present to render the Auth UI. Changes in  #1632 should fix this

**Comment by chgasparoto** [comment]
@powerful23 @yuth it worked! Thanks!

**Comment by richardzcode** [comment]
Just FYI https://github.com/richardzcode/Journal-AWS-Amplify-Tutorial/tree/master/step-03 is updated with the latest Amplify. Hope it is helpful 😄

**Comment by jordanranz** [comment]
Closing this issue, as it seems the question has been answered. Please reopen if there are still related questions or concerns.

**Comment by ysfmag** [comment]
I created a lib that help you customise amplify authentication UI,  please check https://github.com/ysfmag/aws-amplify-react-custom-ui

**Comment by sophieevnex** [comment]
I found this tutorial incredibly useful, it shows you how to customise your sign in component by extending the aws-amplify SignIn component:
https://dev.to/kylegalbraith/how-to-easily-customize-the-aws-amplify-authentication-ui-42pl
