### ISSUE TITLE
React - Federated buttons - cant turn off icons in theme

### ISSUE THREAD

**Issue by jfo8000** [aws-amplify/amplify-js#1629]
**Describe the bug**

In react, the FederatedButtons for google and facebook login include a new SVG element that looks strange and you can't theme to turn off.   

I would also like proper theme support for styling the facebook button differently to the google button, etc.  The old way of doing it was based on the id of the element, which seems to have changed in the new UI.  My specific need is to adjust the background colour / font  / spacing and location of the buttons.

 I see there is support for signInButtonIcon and signInButtonContent in the theme but it somehow doesn't seem to flow through for me.  However even if they did work, I couldn't use this to style google separately from facebook, etc.

(I finally was able to upgrade to aws-amplify-react@2.0.1 after uninstalling an old graphql).

**To Reproduce**
Create react app
npm install aws-amplify --save
npm install aws-amplify-react --save

Add this code into app.js
```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import { Authenticator } from 'aws-amplify-react';
const federated = {
  facebook_app_id: '12345',
  google_client_id:
    '12345.apps.googleusercontent.com'
}

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <Authenticator federated={federated}/>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
      </div>
    );
  }
}

```

**Expected behavior**

- A clear, first class way to style buttons from each Federated Oauth provider

**Screenshots**
![image](https://user-images.githubusercontent.com/16273166/45453402-15f6c680-b724-11e8-9ced-04b314a3e67d.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac 
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Additional context**

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by jordanranz** [comment]
Hi @jfo8000,

We are currently working on a better way to override styles with CSS Modules and themes. In the meantime a theme object with the correct key related to the element must be passed down. 

The theme object is not being passed through to the signInButtonIcon and signInButtonContent. I will go ahead add code to propagate the theme object down to the signInButtonIcon and signInButtonContent so you can add your own inline styles to those elements. I will also add some selectors for customizing specific provider sign-in buttons.

**Comment by jordanranz** [comment]
I have merged the changes that allow for more customizability for federated buttons.

Usage will look like:

const federated = ...
const theme = {
  signInButtonIcon: { 'display': 'none' },
  signInButtonContent: { 'font-family': 'Helvetica Neue' },
  googleSignInButton: { 'backgroundColor': 'red' }
}

<Authenticator federated={federated} theme={theme} />

**Comment by jordanranz** [comment]
#1754 should allow you to customize the styles on the requested components. Please reopen this if you run into anymore problems or have any related concerns.
