### ISSUE TITLE
"Cannot read property 'challengeParam' of undefined" when resetting password

### ISSUE THREAD

**Issue by POANG1** [aws-amplify/amplify-js#1630]
**Describe the bug**
I set a cognito user to REQUIRE_PASSWORD_CHANGE (from the AWS console), now I am asked to reset the password using the amplify auth UI (without any changes). When submitting the new password and pressing the change button I get a "Cannot read property 'challengeParam' of undefined". The issue is on line 98 of RequireNewPassword.js where user is undefined.

**To Reproduce**
Set a user in cognito to REQUIRE_PASSWORD_CHANGE using the aws console.
Use the aws-amplify-react default auth UI to login
When asked to reset the password, input a new password
Press the CHANGE button and the error is in the console.

**Expected behavior**
Stack trace:
RequireNewPassword.js:98 Uncaught TypeError: Cannot read property 'challengeParam' of undefined
    at RequireNewPassword.change (RequireNewPassword.js:98)
    at HTMLUnknownElement.callCallback (react-dom.development.js:145)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:195)
    at invokeGuardedCallback (react-dom.development.js:248)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:262)
    at executeDispatch (react-dom.development.js:548)
    at executeDispatchesInOrder (react-dom.development.js:570)
    at executeDispatchesAndRelease (react-dom.development.js:668)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:679)
    at forEachAccumulated (react-dom.development.js:649)
    at runEventsInBatch (react-dom.development.js:810)
    at runExtractedEventsInBatch (react-dom.development.js:819)
    at handleTopLevel (react-dom.development.js:4679)
    at batchedUpdates$1 (react-dom.development.js:17331)
    at batchedUpdates (react-dom.development.js:2144)
    at dispatchEvent (react-dom.development.js:4758)
    at interactiveUpdates$1 (react-dom.development.js:17386)
    at interactiveUpdates (react-dom.development.js:2163)
    at dispatchInteractiveEvent (react-dom.development.js:4735)

**Desktop (please complete the following information):**
 - Windows 10
 - Node.js v8.9.3 / Chrome 68.0.3440.106 (64-bit)
 - aws-amplify: 1.0.11
- aws-amplify-react: 2.0.1

**Comment by powerful23** [comment]
@POANG1 can you provide more details like some code snippets about how you are using amplify. Also you can turn on the debug mode by putting `window.LOG_LEVEL='DEBUG'` in your code.

**Comment by pigmanbear** [comment]
I received this error as well implementing some custom components and copy and pasted the 'signIn' method on the Amplify component SignIn from github. Reverting back to the default and the error went away, so comparing the node_modules v the current implementation:
Current: 

```js
           .catch(err => {
                if (err.code === 'UserNotConfirmedException') {
                    logger.debug('the user is not confirmed');
                    this.changeState('confirmSignUp');
                } 
                else if (err.code === 'PasswordResetRequiredException') {
                    logger.debug('the user requires a new password');
                    this.changeState('requireNewPassword');
                } else {
                    this.error(err);
                }
            });
```

Previous
```js
           .catch(err => {
                if (err.code === 'UserNotConfirmedException') {
                    logger.debug('the user is not confirmed');
                    this.changeState('confirmSignUp');
                } 
                else {
                    this.error(err);
                }
            });
```

The RequireNewPassword Component needs a user object, but the changeState call in current version calls changeState without passing in a user. Previously, the Toast Component would show the error and then 'Forgot Password' click was required. 

It could be handled using be calling 'changeState('forgotPassword')' as opposed to 'requireNewPassword' . This, of course, would send the user without necessarily displaying a message. 

I am customizing the components and implementing with material-ui and custom toasts, so taking a look at the 'ForgotPassword' component, you could call

```js
       Auth.forgotPassword(username)
            .then(data => {
                logger.debug(data)
                this.setState({ delivery: data.CodeDeliveryDetails });
            })
            .catch(err => this.error(err));
```
and of course would already have the username, so could take the user would get a code and fill in the password field, then have a Snackbar message indicating the message. 

This definitely is a bug as of the most recent code in the repo.

**Comment by powerful23** [comment]
@pigmanbear thanks. I will submit a fix for this bug.

**Comment by LoganArnett** [comment]
Are there any updates on this?

**Comment by emmkong** [comment]
@powerful23 Do you have an update about this issue? Thanks

**Comment by powerful23** [comment]
@emmkong I will try to fix that but for now can't provide an ETA for that.
