### ISSUE TITLE
[Storage] How to put item to 'uploads'

### ISSUE THREAD

**Issue by j2d2** [aws-amplify/amplify-js#1636]
I can't figure out how to put a file to the 'uploads' folder in S3 for the mobilehub userfiles.
The [docs](https://aws-amplify.github.io/amplify-js/media/storage_guide) clearly explain how to interact with the other 'levels' such as public|private|protected, but i don't see any mention of this uploads folder which appears to be a peer in functionality, and created by mobilehub automatically with permissions & readme.

thanks for any direction!

**Comment by powerful23** [comment]
@j2d2 you can try using [customizing your own s3 path](https://aws-amplify.github.io/amplify-js/media/storage_guide#customization) so you can upload files to that uploads folder.

**Comment by j2d2** [comment]
Good idea, thanks @powerful23 , but then you lose the option to use of those levels, which are already configured and useful.  
I noticed that the 'uploads/' path is also preconfigured with a readme specifying the usage, and an IAM policy (auth_mobilehub role) when setup with mobilehub, so i'd expect that this could be a 4th 'level' that Amplify might support?

**Comment by powerful23** [comment]
@j2d2 I can mark this as feature request but I can't give the word that we will have the 4th level.

**Comment by j2d2** [comment]
thanks @powerful23 ! just thought i'd point it out...

**Comment by chai86** [comment]
@powerful23 Was this feature implemented? i am now having to create my key as "images/xxxxxx" when calling Storage.Put(), just to get it into my images folder. This is no help when trying to retrieve data when you just need to use the "xxxxx".

**Comment by hisham** [comment]
+1. What's the point of setting up this dir if you don't offer us out of the box way to upload to it? Seems like this is the best way to allow unauthenticated users to upload files.

**Comment by hisham** [comment]
Also the documentation has zero mentions of this "upload" dir - https://docs.amplify.aws/lib/storage/upload/q/platform/js.

**Comment by hisham** [comment]
I figured out how to upload to this folder - just need to pass the following in Storage.put: 

```
customPrefix: {
        public: 'uploads/'
      }
```

Weird that this folder is not documented at all. Is this a left over from mobile hub that is planned to be deprecated or something?

**Comment by abdallahshaban557** [comment]
We have added documentation on how to use the custom prefixes. https://docs.amplify.aws/lib/storage/getting-started/q/platform/js/#using-amazon-s3
