### ISSUE TITLE
please provide details on how to change the URL of a hosted website

### ISSUE THREAD

**Issue by SogoGolf** [aws-amplify/amplify-js#1639]
** Which Category is your question related to? **
amplify hosting

** What AWS Services are you utilizing? **
amplify

** Provide additional details e.g. code snippets **
we've created a great React web app and published it without issue to Amplify "hosting".

now we want to change the default URL for that site (eg. "http://xxxxxxxxx-hostingyyyyyy.s3-website-ap-southeast-2.amazonaws.com") to "http://dev.somenewurl.com"

how/where/what do we need to make this happen. you can make the assumption that the domain has been setup and is ready to go/available via Route 53.

**Comment by powerful23** [comment]
@SogoGolf you might need to go to the Route 53 documentation to search for how to change the default URL: https://aws.amazon.com/route53/faqs/

**Comment by jordanranz** [comment]
For a static website see this documentation:
https://docs.aws.amazon.com/AmazonS3/latest/dev/website-hosting-custom-domain-walkthrough.html

I am going to close this issue for now. Please reopen if you have any further questions.
