### ISSUE TITLE
API request signature failure results in unrecoverable config for amplify

### ISSUE THREAD

**Issue by jliebrand** [aws-amplify/amplify-js#1642]
We are seeing a small percentage of our users failing their API requests to our server with generic Network Errors. Whilst I've not yet determined how they got their devices in a bad state, I *am* now able to reproduce the problem. I appreciate the following might appear to be contrived (manually editing localStorage), but my point with this bug is that storage *can* get corrupted, and when it does one should be able to recover from it. Which I am not sure we can with amplify.

Steps to reproduce:
```
1- Login to a service
2- Open the local storage and find the Cognito idToken
3- Edit the token (eg change the first character from "eyJraWQi...." to "XyJraWQi....")
4- Attempt any API call
```

Step four here will result in a generic Network Error being thrown, with an added confusion of also triggering a CORB error. 

The CORB error is a slight red herring, because the server side error (403) is not sent with any allow origin headers in my case. There is potentially some configuration on the server side that would fix that, but the real problem is the 403 itself, not the CORB.

Amplify.API.get will sign the request, and that signature is going to fail because we changed the token randomly. But as the client of Amplify.API.get, all we get back is a generic Network Error. We can 'catch' that error, but there's no way to know this is because of a broken signature.

Worst, there is no way to tell Amplify that it should revoke the tokens and start again. 

The only work around I can see is to configure Amplify.AUTH with our own storage, and then if there is a Network Error, just clear that storage. This is a rather big kludge since (a) this should be handled under the hood IMHO, and (b) we would be clearing tokens for *any* Network Error....

**Comment by jliebrand** [comment]
It looks like calling currentCredentials() will trigger amplify to "reset" the tokens. So that's the way out of this.

Unfortunately our users are still seeing 403s unrelated to corrupt tokens. But that is a separate issue I'll debug further (and might raise a separate bug for)

**Comment by zigzhang** [comment]
@jliebrand I'm encountering the same issues as well. I'm also refreshing the credentials as much as possible, but still randomly get those generic `Network Error`.

When looking at my API Gateway logs, I see the `OPTIONS` call being successful, but I have no logs for the `GET` when the error appears.

Did you manage to find a way to fix this? Or even understand where it comes from?
