### ISSUE TITLE
How to make Storage.get use sigv4?

### ISSUE THREAD

**Issue by SashaMoe** [aws-amplify/amplify-js#1652]
I'm trying to use Storage.get to download server side encrypted file from S3, and get 'Request require Signature Version 4' exception. Is there a way to make Storage.get use sigv4?

**Comment by nidsharm** [comment]
Hi @SashaMoe ,

Are you using your custom keys for encryption or are your keys managed by KMS/S3 ?

**Comment by SashaMoe** [comment]
I'm using a custom key.

**Comment by rush86999** [comment]
same issue please bump this problem

**Comment by zacharybergmann** [comment]
using KMS here as well

**Comment by jordanranz** [comment]
Amplify does not currently support this. I will mark this as a feature request to be tracked and prioritized.
