### ISSUE TITLE
Getting 403 Error on API.get() calls with Cognito Federated Identities and IAM

### ISSUE THREAD

**Issue by TigerSheng** [aws-amplify/amplify-js#1654]
**Describe the bug**
Currently I am using API Gateway to host my backend (small express app in Lambda) and Cognito user pool and identity pool. The API is secured by AWS_IAM such that only authorized users will be able to invoke. 

However, when I call API.get() I get a 403 code with a CORS error (since 403 error response does not have proper CORS headers set up). What's weird was when I called GET to the same API in POSTMAN with my credentials it works perfectly fine. Seems to me that the credentials, which should have been handled by Auth from Amplify, was not sent to the API and consequently there was an authentication failure.

**To Reproduce**

Here is my configuration for Amplify:
```
Amplify.configure({
  Auth: {
    mandatorySignIn: true,
    region: config.cognito.REGION,
    userPoolId: config.cognito.USER_POOL_ID,
    identityPoolId: config.cognito.IDENTITY_POOL_ID,
    userPoolWebClientId: config.cognito.APP_CLIENT_ID
  },
  API: {
    endpoints: [
      {
        name: name,
        endpoint: config.apiGateway.URL,
        region: config.apiGateway.REGION
      }
    ]
  }
});
```

Here is my API call (I don't know if I should send any sort of credentials to the API so I left init empty):
`const notes = await API.get('notes', '/notes');`

Then this gives me the following errors in Chrome:

`xhr.js:178 OPTIONS https://e0l1mzvi9c.execute-api.us-east-2.amazonaws.com/latest/notes 403
`

`Failed to load https://e0l1mzvi9c.execute-api.us-east-2.amazonaws.com/latest/notes: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.`

**Expected behavior**

The GET request should return an array of object requested if authentication went through. I have also tested the API using aws-api-gateway-cli-test to make sure the authentication works properly. 

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 10.0.17134 Build 17134
 - Browser Google Chrome
 - Version 69.0.3497.92 (Official Build) (32-bit)
 - aws-amplify: ^1.0.11
 - react: ^16.5.0

**Additional context**

The problem looked like a CORS problem at first since the response was missing 'Access-Control-Allow-Origin' header, but I have incorporated CORS handler in my backend and problem still persisted. Then I realized that there was a 403 error taken place before the network error. I sent a GET request without any credential in POSTMAN, and subsequently the 403 error response was missing the 'Access-Control-Allow-Origin' header.

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

I never knew about this debug mode before but this became very useful. From the debug logs I can seethat my app had successfully acquired credentials. However, error took place after signing the request: 

![image](https://user-images.githubusercontent.com/22460252/45583349-3e9acf80-b88e-11e8-9fc9-f7db7a33c2dd.png)

`AWSPinpointProvider - cannot send events without credentials, applicationId or region
`

~~Region is in the signer object; credential seemed to be embedded in the headers of the signed request. So maybe the missing one is applicationId, and I'm stuck here.~~

**Update:** I have disabled analytics explicitly in Amplify.configure but issue still persists. I am still getting 403 even when I signed my request with credentials.

**Comment by TigerSheng** [comment]
**Update:** I have gotten rid of the CORS error from the 403 response and enabled cloudwatch logs on my API Gateway. Now the actual error message is discovered - the security token included in the request is invalid. However in debug logs my credential was successfully acquired.

**Comment by jliebrand** [comment]
@TigerSheng - can I ask how you enabled the api cloudwatch logging? I tried doing the same thing, but I'm not seeing the 403s in the logs? Checking the documentation seems to imply that auth errors aren't logged?
"Also failed requests due to throttling (429) or access (403) errors are not logged and will not be included in the report."
from https://docs.aws.amazon.com/apigateway/latest/developerguide/view-cloudwatch-log-events-in-cloudwatch-console.html

So just curious how you got that logging enabled

**Comment by TigerSheng** [comment]
@jliebrand - I enabled api gateway cloudwatch logging through a setting identical to below:

![image](https://user-images.githubusercontent.com/22460252/45689356-c2201f00-bb21-11e8-8179-af71abbdc393.png)

Also interesting enough - the docs said 403 errors are not logged as you mentioned, but I was seeing 403 logs like below:

![image](https://user-images.githubusercontent.com/22460252/45689441-fc89bc00-bb21-11e8-8d50-a755538b28f5.png)

**Comment by TigerSheng** [comment]
@jliebrand - Agree with what you said about doc. I have done some research and seems like a lot of people are getting 403 because they are accessing resource that never existed. Not in my case though and that's why my request ended up in logs.

Also I have noticed a lag in logging. So if you see 403 in your user but not in your logs you might want to wait for a bit. Also for enabling these logs you need to configure IAM. You can follow this link - [How do I enable Amazon CloudWatch Logs for APIs I created in the Amazon API Gateway?](https://aws.amazon.com/premiumsupport/knowledge-center/api-gateway-cloudwatch-logs/)

**Comment by jliebrand** [comment]
Yep - got that all set up... but it's not showing any 403s... not even from yesterday (when I know there were some...) Will tweak some settings and see if I can get it to work

**Comment by nidsharm** [comment]
Hi @TigerSheng,

 Can you update the path on API.get as follows : '/notes/$primary_key_value' or '/notes/object/partition_key_value/sort_key_value' . Amplify CLI currently doesn't support the scan feature for dynamoDB but we support querying using primary key and sort key.

**Comment by jliebrand** [comment]
is 1.0.12 released yet? or just as unstable?

**Comment by TigerSheng** [comment]
@nidsharm - Thanks for all this feedback and I just resolved my problem. I have had Authorization for OPTIONS method under Resources in API Gateway to be AWS_IAM. However when my browser send a request it will send one to OPTIONS first to check for certain headers without the credentials in this request. Since I set OPTIONS with IAM authorization, the OPTIONS method then checked against IAM with this request without my credentials. This is why I received "Missing Authentication Token".

I have built my backend through serverless so scan was not the issue. And I have just updated to 1.0.12, seems everything was working fine. You can close this issue now. Thanks.

@jliebrand if you update your aws-amplify to v1.1.1 your API module will be updated to 1.0.12.

**Comment by nidsharm** [comment]
@jliebrand , 1.0.12 is released.  
I'm closing the issue for now. Please feel free to re-open if you have any other issues.

**Comment by danielhep** [comment]
@TigerSheng Was the problem the version and was it fixed by simply updating? A bit confused by your response I guess.

**Comment by TigerSheng** [comment]
@danielhep problem was I had AWS_IAM authorization for my OPTIONS method in API gateway. Made it none and solved the problem.

**Comment by danielhep** [comment]
Ah, I see. So you weren't trying to make an API that required authorization? I'm having this problem but I do want my API to be authenticated. :/

**Comment by TigerSheng** [comment]
@danielhep I wanted to make an API that required authorization. But for API gateway, it will create an options method for all the lambda proxy method I created. That method should not be authenticated because the browser will request that method first for appropriate headers and etc. That request to options method is not signed and thus if you have authentication on options method you will get 403.

**Comment by danielhep** [comment]
@TigerSheng Oh, I see what you're talking about now. Looking into it, my OPTIONS method has no authentication, so I must not have the same cause. Thanks for the help though. 
As for logging:
I also set up logging and it looks like a logging group was created, but none of the event streams have any items in them, which isn't making this easier to debug. :/

**Comment by TigerSheng** [comment]
@danielhep No problem for the help. However it seems that you have a different problem.

Just for logging, maybe you can try to go to API gateway -> stage, find the corresponding stage to log, then select INFO log level for more detailed logs even when no error occurred on your API side. Good luck debugging.
