### ISSUE TITLE
Use React <PhotoPicker> component to upload to an S3 bucket

### ISSUE THREAD

**Issue by SogoGolf** [aws-amplify/amplify-js#1656]
Once a user chooses an image using this React component - there should be an option (prop) to then automatically upload the chosen image to the S3 bucket that is configured via Amplify. A success/fail callback should also be provided.

**Comment by powerful23** [comment]
@SogoGolf Hi you can use the `S3Image` component to upload the image to S3 bucket: https://aws-amplify.github.io/amplify-js/media/storage_guide#s3image

**Comment by powerful23** [comment]
@SogoGolf I am going to close the issue. Reopen it if you still have this issue.
