### ISSUE TITLE
Is there federatedSignOut?

### ISSUE THREAD

**Issue by oneduckoo** [aws-amplify/amplify-js#1658]
** Which Category is your question related to? ** Auth

** What AWS Services are you utilizing? ** AWS Cognito 

** Provide additional details e.g. code snippets **
I am using amplify for my react native app. While I have been reading several issues related to federatedSignIn, I have noticed that there is no method for signing out if a user signed in with 3rd party such as Google or Facebook.
Is there any method for signout that I missed on API page? or I am not sure how to handle if a user wants to sign out.

**Comment by powerful23** [comment]
@oneduckoo if you want to sign out from Google or Facebook, you need to call the sign out method provided by their sdks. In the meantime you need to call `Auth.signOut()` to sign out from Amplify to clean up the cached tokens.
