### ISSUE TITLE
404 error code in API GET method with angular

### ISSUE THREAD

**Issue by jocactus** [aws-amplify/amplify-js#1660]
**Which Category is your question related to?**
API

**What AWS Services are you utilizing?**
REST service type

**Provide additional details e.g. code snippets**
In my Angular project, I try to use the GET method to retrieve data in my DynamoDB as explained in the [documentation](https://aws-amplify.github.io/amplify-js/media/api_guide) but I have this error message:
![capture d ecran 2018-09-16 a 19 06 31](https://user-images.githubusercontent.com/13972080/45598945-af9fcb80-b9e3-11e8-91b8-73d3de2fb8cb.png)

 
FYI, I succeed to post a record on my DynamoDB with a PUT method.

Below the code I use to test the GET method:

```
getPersons() {
    const apiName = 'api2a9802ce';
    const path = '/persons';

    this.amplifyService.api().get(apiName, path, { })
      .catch(err => console.log(err.response))
}
```

that I call in a button on my DOM.

Any input to solve that?

Thanks for your answer,

**Comment by nidsharm** [comment]
Hi @jocactus ,

Your calls look correct, we will need some more information from you to help debug the issue. Did you use [Amplify-cli](https://github.com/aws-amplify/amplify-cli) to create your AWS resources? 
If not, can you add your lambda function code for the get request ?

**Comment by jocactus** [comment]
Hi @nidsharm ,

I used Amplify-cli and strictly follow the steps of the `amplify add api` with the REST endpoints which enables CRUD operations on an Amazon DynamoDB table and deployed my app.

**Comment by nidsharm** [comment]
Hi @jocactus ,

The GET operation you are trying to perform to get all the object from a path, is called a scan in dynamoDB. The Amplify CLI doesn't currently support a scan of the dynamodb table but querying is supported. 

You will have modify your path on the getPersons call as follows to get data back: 

path = '/persons/partition_key_value' or path = '/persons/object/partition_key_value/sort_key_value (as needed in your use case)

Please let us know if this approach works for you.

**Comment by elorzafe** [comment]
HI @jocactus I will close this issue for now. Feel free to reopen in case you need any help.

**Comment by lanbau** [comment]
Hi @VetBoard did you manage to find a solution? It's quite important as i want to get all items from /items.
