### ISSUE TITLE
Securing Anonymous Cognito Roles

### ISSUE THREAD

**Issue by ehorodyski** [aws-amplify/amplify-js#1664]
**Which Category is your question related to?**

APIs, Auth

**What AWS Services are you utilizing?**

API Gateway, Cognito

**Provide additional details e.g. code snippets**

In a strictly-web environment, how does one keep AWS secrets...secret? I have a web app where I don't want to have authentication, but still sign all my API calls using Sigv4. I can put the unauth cognito roles in my `aws_exports.js` file, but I don't want them to be exposed to the public. How can I go about securing `aws_exports.js` so that it is not crackable?

**Comment by elorzafe** [comment]
@ehorodyski in order to secure your api is by allowing only authenticated users to have access to it. If your identityPool is allowing guest access I am not sure how to do that. @mlabieniec @powerful23   what do you think?

**Comment by blbradley** [comment]
What secrets are in the aws-exports.js file that should not be exposed to the public?

**Comment by ehorodyski** [comment]
I suppose the IDs of the identity pools.

⁣Sent from TypeApp ​

**Comment by jordanranz** [comment]
[This post](https://stackoverflow.com/questions/39837246/is-it-safe-to-show-the-aws-cognito-pool-id-in-my-html) explains the risk involved here and ways to mitigate.

I am going to close this as it is stale issue. Please reopen or open a new issue if you have any more related questions or concerns.
