### ISSUE TITLE
AWS Mobile react native starter - package.json naming collision

### ISSUE THREAD

**Issue by chai86** [aws-amplify/amplify-js#1665]
When running "npm run ios" for the first time i get the error: 
Loading dependency graph...jest-haste-map: @providesModule naming collision:

1. "npm run ios"

**Expected behavior**
A running screen on the iPhone simulator pf the Pet Tracker app 

**Desktop (please complete the following information):**
I've used recommended versions for compatibility of react, expo etc...
 - OS: iOS
 - react: 16.3.1
 - react-native: 0.55.0
 - react-native-scripts: 1.14.1
 - expo: 27.0.0

**Additional context**
It seems package.json exists in the 'backend' folder and 'current-backend-info' folder and this is causing a clash. No idea why below:

 Paths: /Users/my_username/app_name/awsmobilejs/backend/cloud-api/itemsHandler/package.json collides with /Users/my_username/app_name/awsmobilejs/#current-backend-info/cloud-api/itemsHandler/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.

**Comment by chai86** [comment]
Thanks @nidsharm for the prompt response.

I followed the steps precisely outlined in the aws-mobile-react-native-starter instructions. When executing commands in the iOS terminal, i did get recommendations when running "npm install" to follow up with an "npm audit fix" which forced a fix to other vulnerabilities. I've subsequently downgraded to various versions of react and react-native. 

I see you have a forked version of the github tutorial on this (which i didn't follow), i followed the aws-samples/aws-mobile-react-native-starter tutorial. Would it make sense to try this?

Just for clarification, i do get a BUILD SUCCEEDED message in the iOS terminal, and i can see in my AWS console all the backend services have been created. It's from there onwards, in the Metro Bundle terminal i get the error message, and did have a red screen in the iPhone simulator pointing me to the @providesModule error. 

Would you mind telling me which versions of: react / react-native / react-native-scripts / expo you are on? Likewise i'll check my version of npm and Node i run. I don't have yarn installed :/

Thanks

chai86

**Comment by nidsharm** [comment]
@chai86 , I did fork the starter, but for testing it out right now, I just followed the exact 4 steps that I had mentioned to get the project working. 
As for the versions: react-native : "0.47.1". We have a yarn.lock file which would be installing only specific versions of each package. 
Also, could you install yarn first, then redo the steps on the repo as yarn is usually better in managing duplicate dependencies.

**Comment by chai86** [comment]
Wow, thanks for the suggestion. I created a new project, and instead of using npm used 'yarn' and everything magically worked!!! Why such a massive difference. Huge thank you.

**Comment by jordanranz** [comment]
Closing this as this issue seems to have been solved and is stale. Please reopen if you are still experiencing similar problems.
