### ISSUE TITLE
Auth.currentSession() return No userPool in React app

### ISSUE THREAD

**Issue by 3dw1np** [aws-amplify/amplify-js#1670]
I'm using the modular import of Amplify for Auth Module.
I am able to login with a cognito user and see that the credentials are stored in my browser localstorage.

But if I reload the page, the promise method Auth.currentSession() executed by my react application at the begining returns me: **No userPool**

Someone can enlighten me on this error with more details?

```
"@aws-amplify/auth": "^1.1.2",
"@aws-amplify/core": "^1.0.9",
"aws-amplify-react": "^2.0.1"
```

**Comment by powerful23** [comment]
@3dw1np can you paste some code snippets about how you are using Amplify? If you are using something from `aws-amplify-react`, then you must install `aws-amplify` first.

**Comment by 3dw1np** [comment]
My mistake the package aws-amplify-react is not used, so I removed that.
Finally I found my problem, it's was because the Amplify wasn't configured when I triggered the method Auth.currentSession() in the index.js entry of my React App, it's was done after ...
