### ISSUE TITLE
Facebook credentials are not refreshed

### ISSUE THREAD

**Issue by jayair** [aws-amplify/amplify-js#1671]
**Describe the bug**
Facebook credentials don't refresh in version `1.0.11`. And any API requests just hang.

**To Reproduce**
1. Implement login with Facebook using Amplify.
2. Login is successful.
3. After credentials expire Amplify tries to refresh it but just hangs.

**Expected behavior**
Facebook credentials should be refreshed.

**Screenshots**
<img width="1280" alt="screen shot 2018-09-17 at 9 23 49 pm" src="https://user-images.githubusercontent.com/53023/45722894-9c743380-bb7c-11e8-89b8-f79802f1ae66.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 11.1.2

The code to test is available in this repo - https://github.com/AnomalyInnovations/serverless-stack-demo-fb-login-client

**Comment by powerful23** [comment]
@jayair this is probably caused because the browser is blocking the pop-up window. Related to #1540

**Comment by jayair** [comment]
@powerful23 I see. It'll be good if we can just log the user out, if we are unable to refresh their credentials.

**Comment by powerful23** [comment]
@jayair do you still have this issue?

**Comment by jayair** [comment]
@powerful23 It seems like the issue is fixed with the latest release I tried (`1.1.13`). I'm not able to reproduce it. I think we can close this.

**Comment by powerful23** [comment]
Closing the issue.
