### ISSUE TITLE
"Unknown error, the response body from fetch is: undefined" at Auth.confirmSignIn

### ISSUE THREAD

**Issue by d-olivas** [aws-amplify/amplify-js#1672]
**Describe the bug**
I am trying to send the verification code received by the user to confirm the signIn, I have the SMS_MFA enabled. However, I keep getting this error `Unknown error, the response body from fetch is: undefined` and thats all I get, there is nothing else to help me understand what the error is about. And everything else is working fine, I call signIn, signUp, confirmSignUp and resendSignUp, they all work fine. The problem is only with confirmSignIn and I have no idea what it could be, I already researched online, but had no success. Another strange thing that happens, when I enter the wrong code, it shows me the 'CodeMismatchException', but it fails with 'Unknown error' when code is the right one. PS: I already have cognito configured to work with SMS MFA

**To Reproduce**
I just installed aws-amplify and started using Auth according to the docs, everything else works fine, it's just when I call confirmSignIn

**Expected behavior**
Receive a successful response when the correct code is sent for verification.

**Smartphone (please complete the following information):**
The problem happens in android and iOS

**Additional context**
I'm using:
react-native version 0.55.4
aws-amplify version ^1.0.11

**Code**
I have a file where a call all the Auth functions and export them
```
export const confirmSignIn = (cognitoUser, code) => Auth.confirmSignIn(cognitoUser, code, 'SMS_MFA');
```
Then I call that confirmSignIn function from a different file
```
confirmSignIn(cognitoUser, code).then((userSession) => {
         console.log(userSession);
      }).catch((error) => {
         switch (error.name) {
           case 'CodeMismatchException':
            this.codeInput.clear();
            break;
           default:
            console.log(error);
            break;
        }
      });
```

<img width="546" alt="screen shot 2018-09-18 at 17 53 25" src="https://user-images.githubusercontent.com/43193032/45722889-cffa9200-bb6b-11e8-8385-0dbf126d8ebc.png">

**Comment by smccumsey** [comment]
I think I have the same problem with Auth.confirmSignIn. But I get it when trying to fit the [amplify vue demo](https://github.com/aws-samples/aws-amplify-vue) to my own vue app (that uses vue cli 3). The weird part is that confirmSignIn works fine in the demo app. And in my app if I remove the navigation guard on the router then the fetch from confirmSignIn works. Or it'll sometimes work if I step through confirmSignIn with the chrome dev-tools debugger.

possibly relevant dependencies:
"amazon-cognito-identity-js": "^2.0.1",
"aws-amplify": "^0.2.10",
"aws-sdk": "^2.209.0",

<img width="1120" alt="screen shot 2018-09-18 at 10 31 08 pm" src="https://user-images.githubusercontent.com/3529657/45731060-c9334580-bb92-11e8-86b6-737e900a8f36.png">

**Comment by d-olivas** [comment]
Hasn't anyone else had this problem? Is there anyone who can help us? =( This issue is blocking progress in the project I'm working on right now. I updated the amplify-js version to 1.1.4 but still doesn't work

**Comment by haverchuck** [comment]
@smccumsey - Have you tried using the aws-amplify-vue package, and if so are you having the same issue?

**Comment by smccumsey** [comment]
@haverchuck no I haven't. But I see it uses the AmplifyEventBus when confirmSignIn resolves. And in the updated vue example the 'signedIn' event is handled in the router. Do you think following that same approach would solve the problem I was having? Thank you!

**Comment by novellizator** [comment]
had the same issue with `cognitoUser.getUserAttributes`. my hack: i found the data _was_ fetched in the internal structures, despite triggering the error. So I am accessing the internal properties (in my case user attributes) through good old notation

**Comment by giginkrishnan** [comment]
Any solution to this, I'm having the same problem when using **Auth.confirmSignin** in my React-Native project

**Comment by taurenk** [comment]
I think I figured this out after a few hours. Its an error that is getting thrown in your code (probably in your callback method) and getting improperly caught/re-thrown by the Client class. 
if you add a `console.log(err.stack)` to this line https://github.com/aws-amplify/amplify-js/blob/b34b9ac7a6357900314dbd09e04566e9820434a6/packages/amazon-cognito-identity-js/src/Client.js#L71 in `node_modules/amazon-cognito-identity-js/es/Client.js` you should see the true error. 

Hope this helps!

**Comment by jordanranz** [comment]
@d-olivas,

Are you still experiencing this issue?

**Comment by d-olivas** [comment]
@jordanranz not anymore. After I posted the issue I didn't use the confirmSignIn for a while and forgot about the issue and then I had to use it again and it's working fine now. I'm using the same react-native version, 0.55.4, react 16.3.1 but updated the aws-amplify to ^1.1.19, probably that was it.
