### ISSUE TITLE
AWS Cognito: Trigger the MFA if the user is already logged in

### ISSUE THREAD

**Issue by guillaumecodet** [aws-amplify/amplify-js#1675]
Is it possible to trigger a MFA check if the user is already logged in with Cognito ? and so get a new token if successful ?

I can't ask for his password.

Thank you.

**Comment by powerful23** [comment]
@guillaumecodet can you give more details about this question? Do you mean you want to check if the current user is logged in with Cognito or not?

**Comment by powerful23** [comment]
@guillaumecodet I am gonna close the issue. Reopen it if you still have the issue.
