### ISSUE TITLE
Can not use Federated entity with react native's HOC 

### ISSUE THREAD

**Issue by mickadoua** [aws-amplify/amplify-js#1677]
**Describe the bug**
Can not use Federated entity with react native's HOC 

**To Reproduce**
```
class App3 extends React.Component {
  render(){
      facebook_app_id: '123456',
      return (
        <Authenticator federated={federated}>
          <Text>...</Text>
        </Authenticator>
    )
  }
}
export default App
```

Can you explain source code : 
on line https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react-native/src/Auth/Authenticator.js#L141
federaed object is pass to Signin component

but Signin component do nothing with it. 
Did I miss something ?

**Expected behavior**
I think the correct behavior is to add Facebook connect's Button

**Screenshots**
![Uploading Capture d’écran 2018-09-19 à 17.24.40.png…]()

**Smartphone (please complete the following information):**
 - iPhone5s
 - OS: IOS12
    "aws-amplify": "^1.1.1",
    "aws-amplify-react-native": "^2.0.1",

**Comment by powerful23** [comment]
@mickadoua I'm sorry but for now this feature is not supported in React Native. You can follow this doc: https://aws-amplify.github.io/amplify-js/media/authentication_guide#federated-identities-social-sign-in to get the token from federated providers and then call `Auth.federatedSignIn()` to get the aws credentials.

**Comment by mickadoua** [comment]
ok Thanks, 
I create a PR #1694 to clarify the doc

**Comment by haverchuck** [comment]
The documentation PR listed above was merged, so I'm closing this issue for now.  Please feel free to reopen.
