### ISSUE TITLE
Update Crypto Browserify package for amazon-cognito-identity-js

### ISSUE THREAD

**Issue by Ch3ck** [aws-amplify/amplify-js#1679]
**Describe the bug**
I encountered an issue as many others with the `undefined` _global variable appearing as a side effect as others have pointed out below:
1. https://github.com/aws/aws-sdk-js/issues/1512
2. https://github.com/aws/aws-sdk-js/issues/1566

I literally had to patch this package as a temporary solution, however after filing an issue with the 
* [crypto-browerify developers](https://github.com/crypto-browserify/crypto-browserify/issues/180)

One recommendation is to update this package reference. Let me know your thoughts I'll be happy to make the PR for this if necessary.

**To Reproduce**
After installing the `amazon-cognito-identity-js` I get the crypto undefined error.

**Expected behavior**
No error is supposed to occur if only this package had been updated.

**Screenshots**
I don't have any screenshots, since I literally patched that package to fix this problem

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Mac Book Pro 15
 - OS: OS X High Sierra
 - Browser : Google Chrome
 - Version : Latest version

**Additional context**
Others have faced the issue as reported here:
1. https://github.com/aws/aws-sdk-js/issues/1512
2. https://github.com/aws/aws-sdk-js/issues/1566

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by powerful23** [comment]
related to #1439 #891 #888

**Comment by Ch3ck** [comment]
@powerful23 has this been fixed yet?
