### ISSUE TITLE
Redirect after signIn with JWT in Authorization header

### ISSUE THREAD

**Issue by jrp-23** [aws-amplify/amplify-js#1683]
I am using Amplify’s Authentication API with a custom login form - just a basic HTML form. The form’s onSubmit handler function makes a call to Amplify’s Auth.signIn method. Upon successful return from this method, I want to:
1.  Redirect to my index.html on my server.
2. Add the JWT to the Authorization header for the redirect request.

How do I do this?

**Comment by D2KX** [comment]
You can get the access, id and refresh tokens with Auth.currentSession() from the @aws-amplify/auth module. Passing them over to your other site is not strictly an AWS Amplify issue and depends on the HTTP client or method you want to use.

You could also attach the token to the url as a hash, similar to how the Implicit Grant Type works with OAuth2.

Another way to do what I think you're trying to do (have a dedicated auth page) is to use something like Zendesk's [cross-storage](https://github.com/zendesk/cross-storage) library to share a local storage among multiple domains and implement a silent SSO or embedded login to your site this way.

To be honest, from a security perspective, all of these options aren't all that great and I'd love for AWS to just allow prompt=none for silent SSO and better customization of their hosted UI solution.

**Comment by jrp-23** [comment]
I agree that it is not strictly an AWS issue, but it seems to me to be a very basic and common use case, yet I am not finding much on the internet for how to accomplosh this.  It would be helpful if Amplify documentation at least provided options or suggestions for how to implement this portion.  They do have react component examples and a hosted UI that accomplishes this, but no example for a custom dedicated login page.  I was hoping I could implement this in the simplest way possible - i.e. without having to do SSO or use react or too many other frameworks.  I also want to utilize the Authoriztion header to transport the token as it seems that is the recommended & most secure approach.

**Comment by undefobj** [comment]
Are you looking for information on this "Add the JWT to the Authorization header for the redirect request."?

You can use the API category and just add this to the headers. For example:

```
async function postData() { 
    let apiName = 'MyApiName';
    let path = '/path';
    let myInit = { 
        headers: {'Authorization' : Auth.currentSession().idToken}
    }
    return await API.post(apiName, path, myInit);
}

postData();
```

The API category works with any generic backend, not just AWS for both REST and GraphQL endpoints. Or is there more out of the box functionality you're describing that you want either the Amplify APIs or some framework component to handle in these cases?

**Comment by jrp-23** [comment]
I am looking for either a pure JavaScript solution, or via Amplify out of the box.  I am trying to avoid the additional layer of the API category, and other frameworks for that matter.
