### ISSUE TITLE
where is the Authenticator component that is pictured in the style guide

### ISSUE THREAD

**Issue by luke-lim** [aws-amplify/amplify-js#1689]
I would like to use the authenticator mentioned in the style guide instead of the default one provided for react.  

It looks great and has a country code picker for the phone number.  

[screen shot 2018-09-19 at 9 47 15 pm](https://user-images.githubusercontent.com/4475325/45792962-99994180-bc55-11e8-948d-f6dfbb2e59e3.png)

instead what i see is this

![screen shot 2018-09-19 at 9 48 24 pm](https://user-images.githubusercontent.com/4475325/45793010-c51c2c00-bc55-11e8-82d0-9a3a16faaf05.png)
As someone mentioned in an earlier post.. the +1 really hinders user adoption, and rather then going through the trouble of making a custom auth component i'd rather just use the one pictured above.

**Comment by mlabieniec** [comment]
@luke-lim The new authenticator using the new UI / Styleguide is provided out-of-the-box with the latest aws-amplify-react. Are you using @latest or v1.x ? The new UI is part of v2.x in aws-amplify-react and part of the amplify-ui package now. If you install aws-amplify-react@latest you should get the latest w/the new ui

**Comment by jordanranz** [comment]
As @mlabieniec mentioned above the new UI is part of v2.x of aws-amplify-react. I am going to close this for now. Please reopen if you are still having trouble using the new UI.
