### ISSUE TITLE
Question: Is it possible to track events that happened offline with AWS Amplify Analytics using React Native Expo environment?

### ISSUE THREAD

**Issue by jorge-sanz** [aws-amplify/amplify-js#1692]
** Which Category is your question related to? **
Analytics

** What AWS Services are you utilizing? **
AWS Pinpoint

** Provide additional details e.g. code snippets **
I am using React Native with Expo and I would like to track offline events. Is it possible with this? Any solution for the problem?

**Comment by jorge-sanz** [comment]
This is the way to do it, right? https://github.com/aws-amplify/amplify-js/blob/master/docs/media/service_workers_guide.md

**Comment by jorge-sanz** [comment]
Is it completely necessary to configure service worker for offline events tracking?

**Comment by cwomack** [comment]
Hello, @jorge-sanz 👋.  This issue appears to be a duplicate and related to Github issue https://github.com/aws-amplify/amplify-js/issues/834. I will close this Github issue to keep the updates pertaining to this feature request and related behavior on a single stream. 
 
Please feel free to add any future comments to the linked issue.
