### ISSUE TITLE
How to authenticate Identity Pool User without using Amplify Components

### ISSUE THREAD

**Issue by ghost** [aws-amplify/amplify-js#1696]
** **Which Category is your question related to?** **

Authentication

** **What AWS Services are you utilizing?** **

Cognito Identity Pool (_not_ User Pools)

** **Provide additional details e.g. code snippets** **

**A little background**
Our organization does not require users to use passwords, so we could not use User pools. We created a custom authentication service, but leveraged Cognito Identity Pools behind the scenes. The custom service returns this information after a user successfully authenticates:
- Custom Refresh Token—this can be use to hit an endpoint we've established that calls the retrieves a fresh Cognito Identity ID and Cognito Access Token.
- Cognito Access Token—this is use to make authenticated requests to API Gateway

**The question**
I would like to know how we can leverage AWS Amplify in our React Native app, but not be required to use the Amplify React Components for sign-in, and would also like to know if Amplify can handle refreshing the access token itself.

**Comment by haverchuck** [comment]
@ghost I believe you could have your identity pool[ federate with a developer-created identity provider](https://aws-amplify.github.io/docs/js/authentication#federated-identities-social-sign-in), which would enable the use of Amplify's federated signin and credential storing features.

I'm closing this issue for now, but please feel free to reopen.
