### ISSUE TITLE
css box-sizing and react auth component

### ISSUE THREAD

**Issue by jonsmirl** [aws-amplify/amplify-js#1697]
This is beyond my understanding of how css works, but I can describe the problem.  Some component in this large app I am working on is adding the 'sanitize.css' stylesheet.  https://github.com/csstools/sanitize.css

That stylesheet contains:
*,
::before,
::after {
  background-repeat: no-repeat; /* 1 */
  box-sizing: border-box; /* 2 */
}

This doesn't impact anything except the SVG icons on the federated login in buttons. That box-sizing directive causes those SVG images to end up at 4x4px instead of 28x28 like they are suppose to be.  It appears that the box-sizing style causes the 20x pad on the SVG icon to shink the icon down to 4x4.  If I turn off the box-sizing style the icon pops back up to 28x28 and it looks like it should.

So something must be messed up with the CSS on those icons since turning on box-sizing shouldn't make them change. I would classify this as difficult to debug, a beginner is never going to figure out where the problem lies.

I'll see if I can work around this by adding a theme on the auth component that turns off box-sizing.

Adding this to the style on the Authenticator component works around the problem.
  box-sizing: content-box;

But.. that sanitize sheet is there to work around cross browser CSS inconsistencies which implies that the there is a cross bowser problem with the CSS on the SVG icon.

**Comment by jonsmirl** [comment]
To be more precise I added box-sizing: content-box; to the SPAN wrapping the SVG element. It does not work directly on the SVG element.

**Comment by jordanranz** [comment]
Hi @jonsmirl,

Some third party UI libraries will add a global box-sizing: border-box; property to all elements. This makes the elements account for padding and border values: https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing

Specifically for the federated buttons, they need to be explicitly set to content-box to work with their given width, height, and padding. I am making a change to explicitly set box-sizing on elements that are affected by third party global box-sizing. This should fix the UI issue with federated buttons.

**Comment by jordanranz** [comment]
#1754 fixes this issue. Please reopen if you have any more related questions or concerns.
