### ISSUE TITLE
[Question] - [Analytics]: Demographic data are sent two times, the second time with invalid data !

### ISSUE THREAD

**Issue by ngouass** [aws-amplify/amplify-js#1699]
** Which Category is your question related to? **
Analytics
** What AWS Services are you utilizing? **
Pinpoint
** Provide additional details e.g. code snippets **
I followed the documentation for implementing analytics on my React-Native app. I'm able to see result on Pinpoint but I also get some additional data that I don't want.

**Config**
```
Analytics: {
    AWSPinpoint: {
      appId: Config.ANALYTIC_APP_ID,
      region: Config.AWS_REGION,
      clientContext: {
        appVersionName: DeviceInfo.getVersion(),       // 0.0.1
        platform: Platform.OS,                                         // ios
        platformVersion: platformVersion.toString(),    // 11.4
        model: DeviceInfo.getModel(),                          // iPhone 6
        make: DeviceInfo.getManufacturer(),               // Apple
        locale: DeviceInfo.getDeviceLocale(),              // en-US
      },

      // Buffer settings used for reporting analytics events.
     ...
    }
}
```

With that config I'm able to get the following result:
![pinpoint](https://user-images.githubusercontent.com/17073855/45841516-59e85d80-bd1a-11e8-9afb-21f574b9d0bc.png)

But Demographic graphs have more data than expected. after Investigating I found that the endpoitn get updated with the following request:

```
{ '[DEBUG] 53:50.94 AWSPinpointProvider - updateEndpoint with params: ': 
   { ApplicationId: 'xxxxxxxxxx',
     EndpointId: 'xxxxxxx',
     EndpointRequest: 
      { Address: undefined,
        Attributes: { isTablet: [ 'NO' ] },
        ChannelType: undefined,
        Demographic: 
         { AppVersion: 'ios/11.4',
           Make: iPhone,
           Model: 'iPhone 6/7/8',
           ModelVersion: '11.4',
           Platform: 'ios' },
        OptOut: undefined,
        RequestId: undefined,
        EffectiveDate: undefined,
        User: 
         { UserId: 'xxxxxx',
           UserAttributes: undefined } } } }
```

I want to know how I can avoid that second endpoint update and if I'm doing something wrong, how should I do it ?

Thanks.

**Comment by ngouass** [comment]
hey guys, still waiting for any clues that could help me !! Thanks

**Comment by powerful23** [comment]
@ngouass sorry for the late response. This issue will be marked as bug. We will try to fix it ASAP.

**Comment by ngouass** [comment]
@powerful23 thanks for your work. Looking forward to hearing from you.
