### ISSUE TITLE
Manually configuring an API Gateway Authorizer for use with @aws-amplify/api authenticated requests

### ISSUE THREAD

**Issue by ajhool** [aws-amplify/amplify-js#1702]
**Which Category is your question related to?**
Auth + API

**What AWS Services are you utilizing?**
API Gateway, Lambda, Cognito, AWS Serverless Application Model + Cloudformation

**Provide additional details e.g. code snippets**
We're currently using the AWS Amplify client library while configuring our backend with AWS Serverless Application Model (SAM). I just wanted to confirm that our understanding of AWS Amplify's Authentication approach is correct:

Are the following two statements correct?:

1. To configure an API Gateway endpoint as a proxy to Lambda so that the Lambda function can access `event.requestContext.identity.cognitoIdentityId`, we need to add an Authorizer to the API Gateway. The Authorizer should have type: `COGNITO_USER_POOLS`. The Authorizer's header should be: `"method.request.header.Authorization"`

2. Without configuring the Authorizer, `event.requestContext.identity.cognitoIdentityId` will be null, even if AWSAmplify is the client. The Lambda proxy integration does not populate the identity field by default>

Put together, something like this:
```
  #template.yaml
  Authorizer:
    Name: CustomerCognitoAuthorizer
    Type: COGNITO_USER_POOLS
    ProviderARNs:
      - !Ref CustomerCognitoPoolARN
    IdentitySource: "method.request.header.Authorization"

  -------
  // lambdaFunction.ts
  function handler(event, context, handler) {
    if(event.requestContext.identity.cognitoIdentityId) {
      handler(null, 'Hello Authenticated Client Side!');
    }
  }

  -------
  // client side, using AWS Amplify
  await Auth.signIn(...); //success
  const result = await API.get('APIName', '/path', {});
  // result === 'Hello Authenticated Client Side!');
```

This upcoming PR should add the Authorizer functionality to SAM, as it does not currently exist.
https://github.com/awslabs/serverless-application-model/pull/546

**Comment by kmb266** [comment]
any update here?

**Comment by jordanranz** [comment]
Hey @ajhool, apologies for the late response.

I believe this is something that the Amplify CLI does for you. With the CLI it uses the [aws-serverless-express/middleware here](https://github.com/aws-amplify/amplify-cli/blob/fee247c74f54b050f7b7a6ea0733fbd08976f232/packages/amplify-category-function/provider-utils/awscloudformation/function-template-dir/crud-app.js.ejs#L12) from the following repo: https://github.com/awslabs/aws-serverless-express

Did you make any progress on this implementation or have an update?

@kmb266, do you have any specifics to add?
