### ISSUE TITLE
Auth.sign() Not Resolving or Throwing an Error

### ISSUE THREAD

**Issue by reggie3** [aws-amplify/amplify-js#1704]
**Describe the bug**
Using `Auth.signIn()` is not resolving or rejecting.  However, Logger `DEBUG` output is being produced indicating a `CognitoUserSession` exists

**To Reproduce**
1. Creating a React Native application
2. Used same Amplify configuration settings that work successfully in React JS web application
3. Attempt to login in using `Auth.signIn(username, password)`

The code I am using is shown below.

```
try{
 let res = await Auth.signIn(
        this.state.username,
        this.state.password
      );
   debugger;    // this point is never reached
}
catch(error){
     console.log(error);   // this point is never reached
     debugger;
}
```
4. Nothing happens, `Auth.signIn` does not provide a resolution or rejection.

**Expected behavior**
A result from `Auth.signIn()`.  Either a successful response or a rejection to be caught.

**Screenshots**
Even though the Auth.signIn() does not resolve, the following information is logged to DEBUG:
![image](https://user-images.githubusercontent.com/7347192/45851466-0c172980-bd09-11e8-9b2b-12ba5f995e55.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - Version: 68.0.3440.106 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: One Plus 5 (ONEPLUS A5000)
 - OS: Android 8.1.0
 - Browser: Stock Chrome
 - Version: 69.0.3497.100

**Additional context**

- I am building the App using Expo 30.0.1
- This application shares the same Amplify configuration files as my properly working React JS web application.
- This application is successfully able to AWS-Amplify API and graphqlOperation libraries to make API calls to the configured AppSync backend.

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

- See screen shot for debug output

**Comment by mandriv** [comment]
Are you sure you are using `async` keyword for your function?

**Comment by reggie3** [comment]
@mandriv Yep.
Also, I'm using the Render Prop pattern, and this is the same code that lets me successfully login in the React JS application.

**Comment by reggie3** [comment]
Login works properly if I completely restart my development environment with `expo start`.

**Comment by nidsharm** [comment]
Shouldn't the debugger; statement be after the catch block ? I tried using try catch with a statement in the middle and got the error: Missing catch or finally after try.

**Comment by reggie3** [comment]
@nidsharm Good point.  The debugger statement should have been after the assignment to the `res` variable.  I have updated the example in my report.

**Comment by reggie3** [comment]
Still having the same problem, and it persists even after restarting the expo environment.

Here are all DEBUG statements that are logged by Logger when my application starts:
```
{[DEBUG] 47:47.933 Amplify - amplify config: {…}}
[DEBUG] 47:47.937 I18n - configure I18n
[DEBUG] 47:47.938 I18n - create I18n instance
{[DEBUG] 47:47.938 I18n: undefined}
[DEBUG] 47:47.939 AnalyticsClass - configure Analytics
{[DEBUG] 47:47.939 Parser - parse config: Array(3)}
{[DEBUG] 47:47.940 DeviceInfo: Array(2)}
{[DEBUG] 47:47.941 AWSPinpointProvider - configure Analytics: {…}}
[DEBUG] 47:47.952 Credentials - getting credentials
[DEBUG] 47:47.953 Credentials - picking up credentials
[DEBUG] 47:47.953 Credentials - getting new cred promise
[DEBUG] 47:47.955 Credentials - checking if credentials exists and not expired
[DEBUG] 47:47.955 Credentials - need to get a new credential or refresh the existing one
[DEBUG] 47:47.956 AuthClass - Getting current user credentials
{[DEBUG] 47:47.956 AuthClass - failed to get or parse item aws-amplify-federatedInfo: TypeError: Cannot read property 'getItem' of undefined
    at AuthClass.currentUserCredentials (blob…}
[DEBUG] 47:47.957 AuthClass - Getting current session
{[DEBUG] 47:47.962 Analytics - on hub capsule analytics: {…}}
{[DEBUG] 47:47.962 AnalyticsClass - current configuration: {…}}
[DEBUG] 47:47.962 AuthClass - configure Auth
{[DEBUG] 47:47.963 Parser - parse config: Array(3)}
{[DEBUG] 47:47.965 Analytics - on hub capsule auth: {…}}
[DEBUG] 47:47.965 Credentials - getting credentials
[DEBUG] 47:47.966 Credentials - picking up credentials
[DEBUG] 47:47.966 Credentials - getting old cred promise
[DEBUG] 47:47.967 Storage - configure called
[DEBUG] 47:47.968 StorageClass - configure Storage
[DEBUG] 47:47.968 StorageClass - Do not have bucket yet
[DEBUG] 47:47.968 StorageClass - configure Storage
[DEBUG] 47:47.969 StorageClass - Do not have bucket yet
{[DEBUG] 47:47.969 API - configure API: {…}}
[DEBUG] 47:47.970 API - create API instance
{[DEBUG] 47:47.970 RestClient - API Options: {…}}
{[DEBUG] 47:47.970 PubSub - configure PubSub: {…}}
{[DEBUG] 47:47.972 AbstractPubSubProvider - configure AWSAppSyncProvider: {…}}
{[DEBUG] 47:47.973 AbstractPubSubProvider - configure AWSAppSyncProvider: {…}}
{[DEBUG] 47:47.973 Interactions - configure Interactions: {…}}
{[DEBUG] 47:47.974 Amplify - amplify config: {…}}
[DEBUG] 47:47.974 I18n - configure I18n
[DEBUG] 47:47.975 I18n - create I18n instance
[DEBUG] 47:47.975 AnalyticsClass - configure Analytics
{[DEBUG] 47:47.975 Parser - parse config: Array(3)}
{[DEBUG] 47:47.976 AWSPinpointProvider - configure Analytics: {…}}
{[DEBUG] 47:47.977 Analytics - on hub capsule analytics: {…}}
{[DEBUG] 47:47.977 AnalyticsClass - current configuration: {…}}
[DEBUG] 47:47.977 AuthClass - configure Auth
{[DEBUG] 47:47.977 Parser - parse config: Array(3)}
{[DEBUG] 47:47.979 Analytics - on hub capsule auth: {…}}
[DEBUG] 47:47.979 Storage - configure called
[DEBUG] 47:47.979 StorageClass - configure Storage
[DEBUG] 47:47.980 StorageClass - Do not have bucket yet
[DEBUG] 47:47.980 StorageClass - configure Storage
[DEBUG] 47:47.981 StorageClass - Do not have bucket yet
{[DEBUG] 47:47.981 API - configure API: {…}}
[DEBUG] 47:47.981 API - create API instance
{[DEBUG] 47:47.981 RestClient - API Options: {…}}
{[DEBUG] 47:47.982 PubSub - configure PubSub: {…}}
{[DEBUG] 47:47.983 AbstractPubSubProvider - configure AWSAppSyncProvider: {…}}
{[DEBUG] 47:47.983 Interactions - configure Interactions: {…}}
{[DEBUG] 47:48.447 AuthClass - getting session failed: "No userPool"}
[DEBUG] 47:48.448 Credentials - setting credentials for guest
```

**Comment by jordanranz** [comment]
Hey @reggie3, are you still experiencing this problem with the latest version of aws-amplify and expo?
