### ISSUE TITLE
Refreshing user

### ISSUE THREAD

**Issue by mandriv** [aws-amplify/amplify-js#1705]
So I have the following scenario:

1. User signs in authenticating against user pool.
2. I am updating user's custom attribute on my backend using [AdminUpdateUserAttributes](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminUpdateUserAttributes.html)
3. `const user = await Auth.currentAuthenticatedUser()` or `const attributes = await Auth.userAttributes(user)` are not returning updated attributes. User object still holds old values.

I can't use [. updateUserAttributes](https://aws-amplify.github.io/amplify-js/api/classes/authclass.html#updateuserattributes), the update is triggered outside the web app scope.

Is there any way to force refresh current user's attributes?

**Comment by mandriv** [comment]
Apologies, my bad - attribute was not set as 'Readable Attribute' in user pool settings.

**Comment by choxnox** [comment]
How did you manage to display updated values? I have exactly the same use case - attributes are updated server-side and changes are immediately visible in the Cognito but changes are not visible on the client-side until user logs out and then logs in (basically invalidating current session).

**Comment by cliffordh** [comment]
Ever figure this out? I'm running into the same scenario... trying to refresh custom attributes but no luck.
