### ISSUE TITLE
AWS Amplify not working with latest angular universal engine / server side rendering

### ISSUE THREAD

**Issue by yuridolzhenko** [aws-amplify/amplify-js#1714]
Server-side rendering is not working with AWS Amplify, resulting in error:

var proto = window['Element'].prototype;
                              ^
TypeError: Cannot read property 'prototype' of undefined

that is coming from dom-utils's matches.js which is used by Amplify: 

Object.defineProperty(exports, "__esModule", { value: true });
var proto = window['Element'].prototype;

1. Enable server-side rendering / universal engine in Angular 6.

angular version 6.1.8
nguniversal 6.1.0
aws-amplify 1.1.2
aws-amplify-angular 2.0.5

**Comment by thomasmichaelwallace** [comment]
This seems related to #1668 - which has a matching PR to get it fixed.

**Comment by yuridolzhenko** [comment]
looks like this is it! Thanks. closing this one then.

**Comment by ntegral** [comment]
@thomasmichaelwallace  If you are looking to use Angular Universal with AWS Cognito you can check out ngx-amplify @https://www.npmjs.com/package/ngx-amplify
