### ISSUE TITLE
Issue installing cli

### ISSUE THREAD

**Issue by nicksmithr** [aws-amplify/amplify-js#1717]
**Describe the bug**

Tried installing aws-cli from terminal, ran into ```node-modules``` issue.

**To Reproduce**
Terminal
Run ```sudo npm i -g @aws-amplify/cli```
Output
```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! path /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/npm/node_modules/ansistyles
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/npm/node_modules/ansistyles' -> '/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/npm/node_modules/.ansistyles.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nick/.npm/_logs/2018-09-21T19_07_38_332Z-debug.log
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
**MacOS | 10.13.6**

**Smartphone (please complete the following information):**

**Additional context**
```Nicks-MacBook-Pro:backend_api nick$ node -v
v8.11.3
Nicks-MacBook-Pro:backend_api nick$ npm -v
5.6.0```

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by nicksmithr** [comment]
Wrong repo, sorry

**Comment by kaustavghosh06** [comment]
I’ve seen this happen sometimes due to a previous version of the CLI installed. You either might want to first npm uninstall the CLI and then install it again. Or you might want to delete this folder -> npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/@aws-amplify/ and then install the CLI.
