### ISSUE TITLE
Multi app and multi environment best approach?

### ISSUE THREAD

**Issue by kevinwolfcr** [aws-amplify/amplify-js#1721]
Hello, at my current work we want to implement Amplify.

Currently we have two native apps (client and employee), and an administrative dashboard. On those apps we want to share some data and authentication (through user groups).

As far as I've read, all the guides explain how to add amplify to a single app, but I haven't found any guide on how to share backend on different apps. Any approach 
or suggested best practice for this?

Also, is there any way to add environments (dev, test, staging, prod) to an amplify app?

**Comment by Larsrdev** [comment]
As far as I understood the apps are independent from each other? 
Than every app needs his own implementation of the Amplify API. Amplify is the "connection-helper" to get connected to your AWS Backend.
At first, get some decent architectural pattern. Do you really need two apps for client and employee? 
Environments can be controlled via your env-variables / build-stages / scripts, etc.
Each environment is connected to an other S3 / EC2 or whatever. 
Someone can correct me if I am wrong :)

**Comment by elorzafe** [comment]
@kevinwolfcr you are be able to share backend resources between different apps just by using the same configuration. If you use [amplify-cli](https://github.com/aws-amplify/amplify-cli) it will generate a file called `aws-exports.js` with all your resource endpoints. If you want to configure those manually, you still can copy the same configuration when you call `Amplify.configure({...})`

**Comment by kevinwolfcr** [comment]
@Larsrdev we do need two different apps. Imagine Uber, they have the user (app), the driver (employee) app, and they can have a dashboard on which they activate new drivers. So yes, we need separate applications.

---

@elorzafe yes, I had that in mind and is may be the approach I will take. So I think, I will have the cloud services on one repo (aka amplify source) and then just pull the configuration into my other apps.

IMHO, there should be a `pull` command as well, on which we can specify a Mobile Hub app id.

I think this existed before, isn't it?

**Comment by eibay** [comment]
@kevinwolfcr i wanted to build exactly what you're asking. i wonder how did you go about it?..
