### ISSUE TITLE
The "Host your App" section is not applicable to React-Native guides

### ISSUE THREAD

**Issue by jalooc** [aws-amplify/amplify-js#1722]
**Describe the bug**
The `Getting Started` guide for selected `React-Native` framework features the `Host your App` section. This probably doesn't make sense in the context of a mobile app.

**To Reproduce**
Go to https://aws-amplify.github.io/amplify-js/media/quick_start#step-5-host-your-app

**Expected behavior**
This section shouldn't be there, or it should explain how to fire the analytics event on a simulator instead of hosting a web page.

**Comment by mlabieniec** [comment]
Thanks for the feedback! The section is there (and may need better wording) for the ability to host your static assets i.e. images, videos, remote assets etc. Via cdn / CloudFront for your native apps.

**Comment by jordanranz** [comment]
Clarification has been made here. I am going to close this issue. Please reopen if you have any related questions or concerns.
