### ISSUE TITLE
[IOS] onnotification not trigger when apps is killed

### ISSUE THREAD

**Issue by pribadi1st** [aws-amplify/amplify-js#1727]
**Describe the bug**
onnotification not triggered when app is killed.
Works well on background and foreground.
Works fine on android (Foreground, background, app killed).
i don't know if i'm missing something.

**To Reproduce**
1. I've followed the instruction at
https://aws-amplify.github.io/amplify-js/media/push_notifications_setup.html
2. Check background fetch and remote notification on xcode
3. Followed this [issued](https://github.com/aws-amplify/amplify-js/issues/722#issue-317275068)

**Expected behavior**
onNotification trigger when the app is killed (not in background)

**Smartphone (please complete the following information):**
 - Device: iphone 5
 - react-native : 0.57.0
 - aws-amplify : "^1.1.1",
 - aws-amplify-react-native": "^2.0.1",

**Comment by powerful23** [comment]
#1245

**Comment by matamicen** [comment]
@pribadi1st we have the same issue, @powerful23 the #1245 works for Android, not for IOS.
We are testing the app on the physical phone (iphone X) with the bundle running on the mac, so these are the steps of the test:

1) We Killed de APP in the Phone (Swiping it)
2) We send a Push from PinPoint , it arrives ok, when we tap the push the app Reload the bundle from the Mac and Start the APP without the notification. (We couldnt debug this, so we did an AsynStorage of the notification and then try to access it when the APP is complety open)
  
3) We are trying just with content-available: 1 .... we did not try with content-available: 0 (we do not understood very well what is it ... and some people say that has to be set to 1 [https://medium.com/posts-from-emmerge/ios-push-notification-background-fetch-demystified-7090358bb66e](url) and in this article [(https://samwize.com/2015/08/07/how-to-handle-remote-notification-with-background-mode-enabled/)](url) explains that if content-available: 0 and the app is killed, then when you tap the message the app will call the methods (application:didFinishLaunchingWithOptions: then application:didReceiveRemoteNotification:fetchCompletionHandler: are both called) but we did not try that yet.

Thanks for your help!

**Comment by powerful23** [comment]
@matamicen thanks for your feedback. Yes I agree we should get the initial notification after the app is opened from killed state. Currently we have a pr #1434 which uses the `PushNotificationIOS.getInitialNotification()` to make it work in IOS.

**Comment by matamicen** [comment]
Thanks @powerful23 , so How is the process go on? Do we have to wait the approval of the pr #1434 in order to merge to Master? Once the Master is merged you release a new verision of the library? Sorry for this basic question but I don't know how the process is :) ... Could you explain to me? Thanks again.

**Comment by powerful23** [comment]
@matamicen currently the pr is not fully tested in IOS device and we have received a customer's feedback so will update that. Once it passes the test and gets approved, we will merge it and get it published in the next release. I can't tell you the exact timeline but we'll try to make it ASAP.

**Comment by matamicen** [comment]
thanks @powerful23

**Comment by jordanranz** [comment]
Is this issue safe to close?

**Comment by pribadi1st** [comment]
@jordanranz i think not yet, because when i triggered the push notification using iphone 5 from postman, the result still same

**Comment by matamicen** [comment]
@pribadi1st @jordanranz @powerful23 in our business case we dont need to solve this issue any more, because the app is killed so when it starts again we show to the user all the notifications in His inbox (we pull from our server). Thanks guys anyway.

**Comment by powerful23** [comment]
@pribadi1st we need to do more testing around this issue.
