### ISSUE TITLE
How to get an access token for custom audience server

### ISSUE THREAD

**Issue by willycamargo** [aws-amplify/amplify-js#1729]
**Which Category is your question related to?**
User Auth

**What AWS Services are you utilizing?**
aws-amplify

**Provide additional details**
I want to create an API and have custom scopes etc, so I followed what I could find of the docs and did this:

- created user pool
- created app client
- created resource server + scopes

but now, I can't seem to get an access token for that resource server (with the correct `aud` claim)
I'm using `aws-amplify` with a simple `await Auth.signIn("user", "pwd");`, but I can't seem to pass a custom audience/resource server etc.

What am I missing? Thanks!

**Comment by jordanranz** [comment]
@willycamargo apologies for the late response. Are you still experiencing this issue?

If so,
- Which documentation did you follow?
- Did you use the Amplify CLI?

**Comment by willycamargo** [comment]
No, I have switched to [Auth0](https://auth0.com) because of this issue. 😟

I didn't use the amplify-cli, and unfortunately, I don't remember which docs I have read.

Thanks for response.
