### ISSUE TITLE
React Native Enabling Federated Identities working with Expo?

### ISSUE THREAD

**Issue by vmurillo** [aws-amplify/amplify-js#1730]
** Which Category is your question related to? **
It is related to adding Federates Identities to a React Native App.

** What AWS Services are you utilizing? **
Cognito with Simplify

** Provide additional details e.g. code snippets **
After following the instructions in [https://aws-amplify.github.io/amplify-js/media/authentication_guide#enabling-federated-identities], I tried to add Facebook and Google login to my app, however after following the snippet I could not see any change in the app.

`12345678910import { withAuthenticator } from 'aws-amplify-react';
const AppWithAuth = withAuthenticator(App);

const federated = {
    google_client_id: '',
    facebook_app_id: '',
    amazon_client_id: ''
};

ReactDOM.render(<AppWithAuth federated={federated}/>, document.getElementById('root'));
`

I can't use exactly this syntax since I am using Expo but I created the same component like this:

`const AppWithLogin = withAuthenticator(AwesomeApp, { includeGreetings: true });
const FederatedLogin = () => (
  <Fragment>
    <AppWithLogin federated={federated} />
  </Fragment>
);

export default FederatedLogin;`

I was expecting this feature would display facebook/google/amazon log in buttons in the signIn screen, however I don't see any change.

What is the behavior of props federated ? Is it related to Expo?

Thanks for your answer

**Comment by jordanranz** [comment]
We currently do not support federated UI buttons for React Native.

The docs mention this (rather subtly) here:
https://aws-amplify.github.io/amplify-js/media/authentication_guide#enabling-federated-identities 

 There is a backlog item to support this feature request but I do not currently have an ETA on completion

**Comment by leesolway** [comment]
Would love to see this feature added.

**Comment by bocodigital** [comment]
Me too!!

**Comment by josephbridgwaterrowe** [comment]
@jordanranz is this backlog item somewhere in the open issues? I'd love to track the progress on this.

Thanks.

**Comment by bazsodombiandras** [comment]
Eagerly awaiting this feature...

**Comment by vmurillo** [comment]
no news?

**Comment by tannerabread** [comment]
Closing this as the UI team is working on a React Native Authenticator currently. Outside of that, this is now possible by calling Auth directly and following the [steps here.](https://docs.amplify.aws/lib/auth/social/q/platform/react-native/)
