### ISSUE TITLE
Auth.currentCredentials() authenticated becomes false after refre the page

### ISSUE THREAD

**Issue by ruilunli** [aws-amplify/amplify-js#1731]
**Describe the bug**
Hi, I am using office365 as an identity provider and Cognito as the service provider for the authentication.
I followed these documentations [Using Amazon Cognito Hosted UI](https://aws-amplify.github.io/amplify-js/media/authentication_guide) and [How to set up AWS Cognito with federation to Office365](https://www.idea11.com.au/how-to-set-up-aws-cognito-federation-office365/) to setup the configuration and it worked fine for the first load. (authenticated was true from Auth.currentCredentials())

However, when I tried to refresh the page, the Auth.currentCredentials() always return authenticated to be false.

My question is should I rely on Auth.currentCredentials() to check whether the user has logged in, or I can use Auth.currentAuthenticatedUser()?

Thanks.

**Comment by powerful23** [comment]
@ruilunli Hi you should use `Auth.currentAuthenticatedUser()` to check if the user is logged in or not. But in the meantime you should get an authenticated user if you are logged in and have those tokens stored in your local cache. Can you provide more details like some debug info?

**Comment by powerful23** [comment]
Closing the issue due to no further response. Feel free to reopen if you still have this issue.
