### ISSUE TITLE
Duplicate identifier 'Subscriber with typescript

### ISSUE THREAD

**Issue by karlmosenbacher** [aws-amplify/amplify-js#1732]
**Describe the bug**
Getting the error:
"Duplicate identifier Subscriber" when trying to run my react application with typescript.

The error seems to be located in:
my_project/node_modules/@aws-amplify/api/node_modules/@types/zen-observable/index.d.ts

My dependencies:
"react": "^16.4.1",
"aws-amplify": "1.1.3",
"aws-amplify-react": "^2.0.4",
"typescript": "2.8.3"

**To Reproduce**
1. install latest stable aws-amplify and aws-amplify-react
2. run the application

**Desktop (please complete the following information):**
 - OS: [Mac OS High Sierra 10.13.6]
- Chrome webbrowser

Have I missed any @types dependencies perhaps?

BR

**Comment by rcwestlake** [comment]
I am also seeing the issue except with a React application and using yarn:

aws-amplify: `1.1.10`
aws-appsync: `1.7.0`
typescript: `3.1.6`

The issue arose when I added `aws-appsync` to my project. 

This is the error: `node_modules/@aws-amplify/api/node_modules/@types/zen-observable/index.d.ts
(32,14): Duplicate identifier 'Subscriber'.`

And when I run `npm ls @types/zen-observable`, these are the results:
```apollo-client@2.4.7
│ └── @types/zen-observable@0.8.0 
├─┬ aws-amplify@1.1.10
│ ├─┬ @aws-amplify/api@1.0.21
│ │ └── @types/zen-observable@0.5.4 
│ └─┬ @aws-amplify/pubsub@1.0.18
│   └── @types/zen-observable@0.5.4 
└─┬ aws-appsync@1.7.0
  ├─┬ apollo-client@2.4.6
  │ └── @types/zen-observable@0.8.0  deduped
  └─┬ apollo-link-retry@2.2.5
    └── @types/zen-observable@0.8.0  deduped```

**Comment by rcwestlake** [comment]
FYI.. My fix for the time being is to exclude `node_modules` in my `tsconfig.json` file. You also need to set `skipLibCheck` to `true`
