### ISSUE TITLE
Can you specify cookies for cookie storage?

### ISSUE THREAD

**Issue by jrp-23** [aws-amplify/amplify-js#1735]
I’m considering using cookie storage for the purpose of sending a JWT to the server on every HTTP request.

I configured my app to use cookie storage but doing so will include all 3 JWTs (id, access, and refresh) as separate cookies.  All 3 cookies will be sent for each request, but I only need 1 (access token).  I don’t want the other 2 cookies sent as it is unnecessary additional payload which has the potential to decrease performance.

My question is:  can I specify that just the access token is stored in a cookie?

**Comment by powerful23** [comment]
@jrp-23 sorry but for now there is no way to do that. Will mark as feature request.

**Comment by ShawnCorrigan** [comment]
We are having issues with our websites as the header size is too large with all of the cookies that are set. We also only need the access token. This feature would be nice. As of right now we're looking at having Amplify use local storage and additionally setting an access token cookie, but that's messy.

**Comment by pwfcurry** [comment]
You can use a custom storage & filter out cookie keys you don't want to use.

https://aws-amplify.github.io/docs/js/authentication#managing-security-tokens

Related: https://github.com/aws-amplify/amplify-js/issues/1545

**Comment by ericclemmons** [comment]
Closing as https://docs.amplify.aws/lib/auth/manageusers/q/platform/js#managing-security-tokens is the best way to customize credential storage.

It's worth noting that `431` errors can occur for tokens with a large number of claims!
