### ISSUE TITLE
Theme not available on amplify-angular 

### ISSUE THREAD

**Issue by alsco77** [aws-amplify/amplify-js#1755]
**Describe the bug**
CSS files are not being correctly linked from the `aws-amplify-angular/theme.css` file, meaning that none of my front end components (when using `amplify-authenticator-ionic framework="Ionic"`) show with any styling.

**To Reproduce**
1. Fresh install of both `aws-amplify` and `aws-amplify-angular` 
2. Navigate to `node_modules/aws-amplify-angular/theme.css`
3. Attempt to navigate to `~@aws..../Theme.css` by `ctrl + click` (or use this link manually)
4. See that the file is not linked correctly

**Expected behavior**
Import statement should reference the specified `Theme.css` file and thus link up the style sheets correctly for use in the app

**Screenshots**
![image](https://user-images.githubusercontent.com/5690430/46056904-529bd680-c196-11e8-907a-e17d6922f392.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Editor VsCode

**Comment by D2KX** [comment]
I think you need to install @aws-amplify/ui manually. It was not part of the dependencies of either aws-amplify nor aws-amplify-angular last time I checked.

**Comment by henkesde92** [comment]
I successfully installed the UI package using: 

`npm install -S @aws-amplify/ui`

But I still don't have a 'ui' folder in my node_modules/@aws-amplify and thus the styles can't be loaded.

Can someone check this please?

**Comment by CGregoryDunn** [comment]
I'm seeing the same behaviour as @alsco77 on macOS 10.14

**Comment by haverchuck** [comment]
@CGregoryDunn  @aldo-roman  @henkesde92  - Is this issue pesistent with the latest versions?  I've been unable to reproduce.

**Comment by aldo-roman** [comment]
I am unable to reproduce either. Notice I added styles as per instructed on docs, and not as per this bug:

```
// styles.scss
@import '~aws-amplify-angular/theme.css';
```

Also, it seems the bundler/sass-compiler is not looking at the correct directory on the error. 
I notice the bundler is rollup, but the tilde operator `~` is native to webpack.

So, there are some possible root causes to this bug. Either case, unable to reproduce on my side so far.

**Comment by haverchuck** [comment]
@CGregoryDunn @alsco77 Are you using the Angular CLI to build?

**Comment by jordanranz** [comment]
FYI, we have started an RFC discussion for a proposed Amplify UI Component refactor to increase customizability and flexibility for our components. Please feel free to add any additional comments to the following issue:

https://github.com/aws-amplify/amplify-js/issues/3279

**Comment by kinetik06** [comment]
I don't know who needs to see this, but on my machine, it was theme.css (all lowercase) not Theme.css

**Comment by DKFletcher** [comment]
thanks kinetik saved my bacon today  😊
