### ISSUE TITLE
AWS SDK in React Native

### ISSUE THREAD

**Issue by vmurillo** [aws-amplify/amplify-js#1756]
** Which Category is your question related to? **
AWS Amplify integration with AWS services

** What AWS Services are you utilizing? **
SQS, SNS, etc

** Provide additional details e.g. code snippets **
I would like to know if it is possible to use the AWS Javascript SDK in a React Native project. Personally I am intending to use SQS but I dont see a mention of it in Amplify documentation. My understanding is AWS SDK only wraps AWS web endpoints therefore it should be possible to use it in any platform capable of calling web endpoints.

**Comment by powerful23** [comment]
@vmurillo I would say yes you can use `aws-sdk` in your react native project. It's just a plain javascript library.

**Comment by sammartinez** [comment]
Closing this issue as per powerful23 call out above. Please feel free to reopen if need be
