### ISSUE TITLE
How to fake Aws Cognito User Pool

### ISSUE THREAD

**Issue by yuankunluo** [aws-amplify/amplify-js#1758]
** Which Category is your question related to? **
Auth, Cognito User Pool

** What AWS Services are you utilizing? **
Cognito User Pool, Cognito Identity Pool, S3

** Provide additional details e.g. code snippets **
no

Hi guys. I am in China and as you know, due to the government's policy the Beijing Region ( cn-northeast-1) and Ningxia Region are completely separated from AWS global. 

Currently, there is no Cognito User Pool and AppSync in China.

I have read the User Pool Documentation, which detailed that the user pool return JWT Token, in the token there is a role arn ( if the user group binds a role). 

With the role, Amplify will make a call to AWS STS to get temporary credentials. 

So I want to ask if it possible to fake a User Pool Service with Aws Lambda?

That means I can write a Lambda which does authentication and return the JWT Token. This step is not hard.

The hard part is how to use these customed return JWT with amplify service?

I have noticed there is a Hub there, but the documentation about the HUB is very limited.

So, anyone has an idea for that? It will be appreciated.

**Comment by haverchuck** [comment]
This would be problematic at the moment, but there might be some changes to Amplify in the near future to make it easier.

**Comment by powerful23** [comment]
Closing the issue due to no further response. Feel free to reopen if you still have this issue.
