### ISSUE TITLE
AWSPinpointProvider - Please ensure you have updated you Pinpoint IAM Policywith the Action: "mobiletargeting:PutEvents" in order tocontinue using AWS Pinpoint Service

### ISSUE THREAD

**Issue by ugurgungezerler** [aws-amplify/amplify-js#1759]
AWSPinpointProvider - Please ensure you have updated you Pinpoint IAM Policywith the Action: "mobiletargeting:PutEvents" in order tocontinue using AWS Pinpoint Service

```
componentDidMount() {
    Analytics.record('APP_STARTED');
}
```

**Comment by powerful23** [comment]
@ugurgungezerler hi this is warning message because the AWS Pinpoint Service has updated their API so you need to change your IAM policy. What's your concern about this message?

**Comment by ugurgungezerler** [comment]
It is working, just wanted to inform
Thanks

**Comment by eturner0** [comment]
Are there instructions on how to change the IAM policy to correct this error?

**Comment by powerful23** [comment]
@eturner0 you need to go to your corresponding IAM in the AWS IAM console and change the policy like this: https://aws-amplify.github.io/amplify-js/media/analytics_guide#update-your-iam-policy

**Comment by Senneseph** [comment]
I'm getting this same warning in the console from my Angular application.

From what I can see it's originating in file `@aws-amplify/analytics/lib/Providers/AWSPinpointProvider.js`, line 74 (@aws-amplify/analytics version 1.2.0).

```
var AWSPinpointProvider = /** @class */ (function () {
    function AWSPinpointProvider(config) {
        this._buffer = [];
        this._config = config ? config : {};
        this._config.bufferSize = this._config.bufferSize || BUFFER_SIZE;
        this._config.flushSize = this._config.flushSize || FLUSH_SIZE;
        this._config.flushInterval = this._config.flushInterval || FLUSH_INTERVAL;
        this._config.resendLimit = this._config.resendLimit || RESEND_LIMIT;
        this._clientInfo = core_1.ClientDevice.clientInfo();
        // flush event buffer
        this._setupTimer();
        logger.warn('Please ensure you have updated you Pinpoint IAM Policy' +
            'with the Action: \"mobiletargeting:PutEvents\" in order to' +
            'continue using AWS Pinpoint Service');
    }
...
}());
```

I'd like to get rid of this warning - I see several problems:
  1. I am not using AWS Pinpoint Service in any way that I am aware of.
  2. This warning is logged every time AWSPinpointProvider() is called.
  3. The warning is logged whether or not your IAM Policy has the mobiletargeting:PutEvents permission.
  4. There are missing spaces in the log message, causing "Policywith" and "tocontinue" to appear as a single word.

Does anyone have a work-around?  Should I try a different version of the libarary?

**Comment by powerful23** [comment]
@Senneseph understood. We will try to move this warning message to somewhere else so that people who don't use Pinpoint service won't see that message.

**Comment by ehorodyski** [comment]
What policy do they mean? There's a million AWS policies I have. I'm having trouble figuring out the correct one to modify.

**Comment by powerful23** [comment]
@ZebGirouard the warning will be removed in our next release and will only show up if sending events failed.

**Comment by callmekatootie** [comment]
I have updated the module in my app and I no longer get the error. Thank you for the fix.

Out of curiosity, why did we get the error even if we are not using analytics?

**Comment by powerful23** [comment]
@wraila can you paste the your configuration part and the debug log info?

**Comment by wraila** [comment]
Looks like latest version of amplify (or perhaps appsync) makes the warning go away. I had thought I was on latest but in writing the message above I realized I was behind by a little. Now using 
```
    "aws-amplify": "^1.1.6",
    "aws-amplify-angular": "^2.0.9",
    "aws-appsync": "^1.4.0",
```

No longer see warning. Thanks @powerful23 for the follow-up.

**Comment by SMJ93** [comment]
Has anyone managed to get this working?

**Comment by callmekatootie** [comment]
@SMJ93 Not sure where you are stuck. You only need to update the module to the latest version to resolve the issue

**Comment by SMJ93** [comment]
We are using:

```
"aws-amplify": "1.1.7",
"aws-sdk": "2.338.0",
```

But still get the error:

`AWSPinpointProvider - Please ensure you have updated you Pinpoint IAM Policywith the Action: "mobiletargeting:PutEvents" in order tocontinue using AWS Pinpoint Service`

**Comment by powerful23** [comment]
@SMJ93 are you using Pinpoint Analytics in your app? The error message will show up if the request sent to pinpoint service failed.

**Comment by SMJ93** [comment]
Yeah we are. So the first initialise event works, but then all of the others seem to fail with this error message.

All of these events were tested and working before this pinpoint change.

**Comment by SMJ93** [comment]
We get this error message on repeat:

```
[ERROR] 50:59.882 AWSPinpointProvider - Please ensure you have updated you Pinpoint IAM Policywith the Action: “mobiletargeting:PutEvents” in order tocontinue using AWS Pinpoint Service
```

We have updated the policy as explained [here](https://aws-amplify.github.io/docs/js/analytics#update-your-iam-policy) and updated to the latest version.

**Comment by powerful23** [comment]
@SMJ93 I mean could you check your network requests and find the those failed requests?

**Comment by SMJ93** [comment]
It returns a `202` so it looks like it is not being completed.

**Comment by powerful23** [comment]
@SMJ93 yeah does it has a response which contains an error message?

**Comment by SMJ93** [comment]
I am using Reactotron with React-native, show no response.

**Comment by lafiosca** [comment]
Along the lines of what @ehorodyski said, the official latest Pinpoint documentation does not even list `PutEvents` as an API action for IAM policies: https://docs.aws.amazon.com/pinpoint/latest/developerguide/permissions-actions.html#permissions-actions-apiactions

Is there anything the Amplify team can do to apply pressure to the team responsible for updating that documentation?

**Comment by SMJ93** [comment]
It is listed [here](https://aws-amplify.github.io/docs/js/analytics#update-your-iam-policy):

![screenshot 2018-10-24 at 14 28 52](https://user-images.githubusercontent.com/2145641/47433904-473dca00-d799-11e8-9dfa-4747b851f00d.png)

**Comment by lafiosca** [comment]
Yeah, but that's bogus. In fact, through experimentation I was able to determine that this policy is sufficient to get past the errors:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "mobiletargeting:UpdateEndpoint",
            "Resource": "arn:aws:mobiletargeting:<region>:<accountId>:apps/<pinpointAppId>/*",
            "Effect": "Allow"
        }
    ]
}
```

**Comment by lafiosca** [comment]
After further experimentation, I realized the policy above could be refined further:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "mobiletargeting:UpdateEndpoint",
            "Resource": [
         
       "arn:aws:mobiletargeting:<region>:<accountId>:apps/<pinpointAppId>/endpoints/*",
     
     
     
 "arn:aws:mobiletargeting:<region>:<accountId>:apps/<pinpointAppId>/events/legacy"
            ],
            "Effect": "Allow"
        }
    ]
}
```

The first resource is for the actual updateEndpoint calls, and the second resource is what the API is using when it complains about the "mobileTargeting:PutEvents" permission.

**Comment by powerful23** [comment]
@lafiosca the reason why the `mobiletargeting:PutEvents` policy for now is totally unnecessary is that we are calling a `legacy` endpoint when putting events as you already found out. That `legacy` endpoint only needs `UpdateEndpoint` policy so that your app won't break because of the IAM policy. But the correct policy for `putEvents` should be `mobiletargeting:PutEvents` and we hope users can change to that policy in time so that in the future when Pinpoint service stops using that `legacy` endpoint, the developers could avoid the breaking changes.

**Comment by lafiosca** [comment]
@powerful23 Will `mobiletargeting:PutEvents` be added to the official documentation and the IAM web console at that time? Right now if you try to use it, the web console doesn't recognize it and complains. (You can ignore the warnings.)

Additionally, does it make sense to have us add a policy that is currently meaningless in support of a future version we haven't installed yet? I prefer for my IAM policies to be locked down as tightly as possible. Would it perhaps be better to use semantic versioning and a changelog?

**Comment by powerful23** [comment]
@lafiosca I have reported this issue to the Pinpoint team.

**Comment by kunsachdeva** [comment]
Please update the documentation with new policy. I wasted almost a day before finding @lafiosca's solution.

**Comment by TheVaporTrail** [comment]
I am currently getting this error. Yesterday I updated to the latest `aws-amplify`:
```
  "dependencies": {
    "aws-amplify": "^1.1.19"
  }
```
The error I had been seeing now appears as this:
> [ERROR] 23:06.968 AWSPinpointProvider - Please ensure you have updated you Pinpoint IAM Policywith the Action: "mobiletargeting:PutEvents" in order tocontinue using AWS Pinpoint Service

I tried all of the suggestions above and nothing helped. Now my policy is this, and I still see the problem:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "mobileanalytics:PutEvents"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "mobiletargeting:*"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```
A couple of points:
* I do not see network traffic associated with the Pinpoint errors. 
* There are no exceptions occurring in the code. 
* It is possible that I change the wrong role/policy, since I have a few projects.

**Comment by roborourke** [comment]
I'm seeing this issue when trying to use the `Analytics.record()` method too. I only set this up in January and had the latest version of amplify at the time. Both `mobiletargeting:UpdateEndpoint` and `mobiletargeting:PutEvents` are present - there are quite a few different IAM roles that were created via amplify CLI.

**Comment by christopherdiehl** [comment]
Still receiving 403 errors when using the policy outlined in the docs for unauthenticated users.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "mobiletargeting:PutEvents"
            ],
            "Resource": [
                "arn:aws:mobiletargeting:[redacted]:apps/[redacted]"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "mobiletargeting:UpdateEndpoint"
            ],
            "Resource": [
                "arn:aws:mobiletargeting:[redacted]:apps/[redacted]"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "mobileanalytics:PutEvents"
            ],
            "Resource": [
                "*"
            ]
        }
```

Receiving the following error from the node sdk:

 `Analytics.record`: `[ERROR] 37:18.135 AWSPinpointProvider - Please ensure you have updated you Pinpoint IAM Policywith the Action: "mobiletargeting:PutEvents" in order tocontinue using AWS Pinpoint Service`
 
Does anyone have a fix? `@aws-amplify/analytics v 1.2.10`.

**Comment by powerful23** [comment]
@christopherdiehl is this policy attached to the unauth role you set in the Cognito Federated Identity Pool?

**Comment by christopherdiehl** [comment]
@powerful23 yes it is

**Comment by roborourke** [comment]
@christopherdiehl can you paste the record call you’re using? I found I got this when some of my custom attributes weren’t strings. Also make sure your metrics if any are numbers. The permission error seems to be a default fallback one, I lost hours finding that out 🤦‍♂️

Try enabling debug mode and check the console, hopefully there’s something more specific that will help you figure it out.

**Comment by powerful23** [comment]
@christopherdiehl maybe you can check the http response to see what is the root cause of this error. Also as @roborourke commented, turn on the debug mode by putting `window.LOG_LEVEL='DEBUG'` in your code.

**Comment by christopherdiehl** [comment]
Thank you @roborourke  and @powerful23, I had to shift gears for a little bit, but I'll be sure to try out @roborourke's advice when I come back to the integration.

**Comment by stevemao** [comment]
mobile hub created a bunch of roles. I'm not sure which role should I update. @ehorodyski any idea?

**Comment by powerful23** [comment]
@stevemao it should be in something like `{your_mobile_hub_project_name}_auth_MOBILEHUB_{uuid}` -> `....mobileanalytics...`. Same for the unauth role.

**Comment by stevemao** [comment]
Thanks @powerful23 I updated those two. As @ehorodyski pointed out the messages don't go away immediately (I'll try it again later). Maybe worth to add this to migration docs.

**Comment by TheVaporTrail** [comment]
@powerful23, I am getting these errors in the console:

> PolygoniaBundle.js:201 [ERROR] 53:14.742 AWSPinpointProvider - Please ensure you have updated you Pinpoint IAM Policywith the Action: "mobiletargeting:PutEvents" in order tocontinue using AWS Pinpoint Service

This is the name of my role: `polygonia_unauth_MOBILEHUB_XXXXXX`

The same policy is listed in the identity pool settings: 
`Unauthenticated role: polygonia_unauth_MOBILEHUB_XXXX `

These are the statements I have in IAM for the role listed above:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "mobileanalytics:PutEvents"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": "mobiletargeting:*",
            "Resource": "*"
        }
    ]
}
```

I made the change to the role some time ago. 

Can you tell me what I need to do to resolve the console messages or how to debug the issue? 

I do not seem to get the same errors when I am logged in. There is a slight difference in the `mobiletargeting` role:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "mobileanalytics:PutEvents"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "mobiletargeting:*"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```

**Comment by bazsodombiandras** [comment]
I'm very new to AWS, I keep getting this warning in my mobile app, please help me understand why I'm getting it and how to solve it.

I have created a new React Native project with AWS Amplify following the instructions from [here](https://aws-amplify.github.io/docs/js/start?platform=react-native&ref_url=/amplify-js/media/tutorials/building-react-native-apps&ref_content=Tutorial:%20Building%20React%20Native%20Apps%20with%20AWS%20Amplify&ref_content_section=configure-your-app).

My AWS dependency versions are as follows:
`"aws-amplify": "^1.1.23", 
"aws-amplify-react-native": "^2.1.9",`

I keep getting the following warning on repeat:

> [WARN] 14:08.753 AWSPinpointProvider - If you have not updated your Pinpoint IAM Policy with the Action: "mobiletargeting:PutEvents" yet, please do it. This action is not necessary for now but in order to avoid breaking changes in the future, please update it as soon as possible.

I see the instructions [here](https://aws-amplify.github.io/docs/js/analytics#update-your-iam-policy) to update the IAM policy.

The problem is that I've only started AWS a day ago and I haven't got the slightest idea where or how to update that policy. Is that something that has to be updated in a local file and then use "amplify push" to push the changes to AWS? Or should I update that policy somewhere on the web in some AWS console? If yes, where? Can somebody please give me a kinder garden level explanation about how the warning can be made to disappear? Note that the events show up nicely in Pinpoint console, so it's actually working, I don't understand why it gives this warning...

**Comment by TheVaporTrail** [comment]
@bazsodombiandras Did you get an answer yet?

**Comment by bazsodombiandras** [comment]
> @bazsodombiandras Did you get an answer yet?

Nope, unfortunately not.

**Comment by roborourke** [comment]
@bazsodombiandras @TheVaporTrail have you tried setting `window.LOG_LEVEL='DEBUG'` yet? The permissions error is a default catch all error message unfortunately. I was seeing it when I was sending custom attributes with values other than type `string` (or array of strings) and metrics as values other than type `number`. It's worth double checking that.

**Comment by bazsodombiandras** [comment]
Thanks @roborourke, I'll give that a try. Still it seems odd that the tutorial sample has this problem out of the box...

**Comment by TheVaporTrail** [comment]
@roborourke, @powerful23, When I enabled debug, with `window.LOG_LEVEL='DEBUG'` I saw the following debug output reported each time I received the `mobiletargeting:PutEvents` error:
```
[DEBUG] 44:19.407 AWSPinpointProvider - init clients
PolygoniaBundle.js:201 [DEBUG] 44:19.408 AWSPinpointProvider - no change for aws credentials, directly return from init
PolygoniaBundle.js:201 [DEBUG] 44:19.408 AWSPinpointProvider - record session start
PolygoniaBundle.js:201 [DEBUG] 44:19.409 AWSPinpointProvider - pinpoint put events with params {.....params details.....
PolygoniaBundle.js:201 [DEBUG] 44:19.409 AWSPinpointProvider - record event failed.  CredentialsError: Missing credentials in config
    .....call stack.....
PolygoniaBundle.js:201 [ERROR] 44:19.410 AWSPinpointProvider - Please ensure you have updated you Pinpoint IAM Policywith the Action: "mobiletargeting:PutEvents" in order tocontinue using AWS Pinpoint Service

```
My main source file starts like this:
```javascript
// Add AWS Amplify
import Amplify, { Logger, Storage }  from 'aws-amplify';

// Set-up Amplify
import aws_exports from "../../aws-exports";
Amplify.configure(aws_exports);
// 2019.02.07: Added when the "missing config" error started showing up. 
// I am not sure if the problem actually exists somewhere else.
AWS.config.update({region: aws_exports.aws_project_region});

// Main design app and support libraries
import { SystemAnalytics } from "./SystemAnalytics.js";
```

The `SystemAnalytics.js` file is a wrapper for the AWS analytics. It abstracts away the AWS API, but otherwise does not do much more at present. 

**The error seems to be resolved by duplicating the lines to configure the Amplify and to configure the region in AWS. I would have thought that having these lines in the main file would be sufficient.** Javascript is a new language for me, so I suspect there is something I don't understand about what needs to be called when and where.

```javascript
// SystemAnalytics.js

// Add AWS Amplify
import { Analytics }  from 'aws-amplify';

// 2019.04.08: Trying to address "CredentialsError: Missing credentials in config". 
import aws_exports from "../../aws-exports";
Amplify.configure(aws_exports);
AWS.config.update({region: aws_exports.aws_project_region});

//------------------------------------------------------------------------------
//	System Analytics
//
//	Wrapper around AWS Amplify Analytics API
//------------------------------------------------------------------------------
var SystemAnalytics = (function() {
	
	//------------------------------------------------------------------------------
	//	Main entry point for the application
	//------------------------------------------------------------------------------
	var SystemAnalytics_Record = function(event, attributes, metrics)
	{
		/*
		console.log("SystemAnalytics_Record: " + event + 
						", attributes: " + ((attributes != undefined) ? JSON.stringify(attributes) : "none") +
						", metrics: " + ((metrics != undefined) ? JSON.stringify(metrics) : "none"));
		*/		
		Analytics.record(event, attributes, metrics)
	}
		
	//------------------------------------------------------------------------------
	//	Public API
	//------------------------------------------------------------------------------
	return {
		Record:		SystemAnalytics_Record
	}
	
}());


export { SystemAnalytics };
```
I will provide an update if this does not resolve the problem. 

Also I will start revising the policy as recommended by @lafiosca

**Comment by TheVaporTrail** [comment]
@bazsodombiandras, you can find the *Roles* and *Policies* in the **IAM** Service in the AWS Console (https://console.aws.amazon.com/iam/). 

On the left, click on **Roles** to see the roles in your account

Look for a role that has the name of your app, followed by `auth` or by `unauth`, then `MOBILEHUB` and then a number. Something like `yourapp_auth_MOBILEHUB_123456789`

Click on that role. You should see a summary of your role and a list of permissions at the bottom of the page. Click on the `Show N more` to see the complete list of policies attached to the role.

One of them should have a name like `yourapp_mobileanalytics_MOBILEHUB_123456789`

Click on the triangle to the left to see the policy summary.

From here you can click on `Edit Policy` and then the `JSON` tab to bring up a window to edit the policy.

**Comment by roborourke** [comment]
@TheVaporTrail are you using `Amplify` anywhere else in that main js file? I'd probably just import the analytics and auth packages in your analytics JS file only and configure them there. You may have to configure the AWS objects in each file you use them in, depends on how your js is compiled. Either that or try creating one file where you configure them then re-export the configured objects. I'm using something similar to this myself:

```
import Auth from "@aws-amplify/auth";
import Analytics from "@aws-amplify/analytics";
import aws_exports from "./aws-exports";

Auth.configure({
  identityPoolId: aws_exports.aws_cognito_identity_pool_id,
  region: aws_exports.aws_cognito_region,
});

Analytics.configure({
  autoSessionRecord: true,
  AWSPinpoint: {
    appId: aws_exports.aws_mobile_analytics_app_id,
    region: aws_exports.aws_mobile_analytics_app_region,
  },
});

// Analytics.record() etc...
```

Also make sure you sanitise the attributes and metrics being passed to `Analytics.record()`. They have to be strings and numbers respectively.

**Comment by powerful23** [comment]
@TheVaporTrail The `Missing credentials in config` is usually caused by duplicated packages in your `node_modules`. Can you please paste the `dependencies` of your `package.json` here?

**Comment by TheVaporTrail** [comment]
@powerful23: 
```
  "dependencies": {
    "aws-amplify": "^1.1.19"
  }
```
My app is https://polygonia.design/

I type
```
window.LOG_LEVEL='DEBUG'
```
right into the developer console (in Chrome) to control the debug output, so I don't have to have it on by default.

**Comment by powerful23** [comment]
@TheVaporTrail hi, seems like the events are being sent successfully in your app.

**Comment by TheVaporTrail** [comment]
@roborourke, my root file now looks likes this:
```javascript
// AWS Amplify
import Amplify from '@aws-amplify/core';
import Auth from '@aws-amplify/auth';
import Analytics from '@aws-amplify/analytics';
import API from '@aws-amplify/API';
import Storage from '@aws-amplify/storage';
import aws_exports from "../../aws-exports";
Amplify.configure(aws_exports);

// 2019.02.07: Added when the "missing config" error started showing up. 
// 2019.04.10: Still needed for DynamoDB
AWS.config.update({region: aws_exports.aws_project_region});
```

and all of the other files use a version of this
```javascript
import Amplify from '@aws-amplify/core';
const Analytics = Amplify.Analytics;
```

One file also uses DynamoDB:
```javascript
import Amplify from '@aws-amplify/core';
const Auth = Amplify.Auth;

// 2019.04.10: Import only dynamodb to reduce bundle size
//var AWS = require('aws-sdk');
var dynamoDB = require('aws-sdk/clients/dynamodb');
var AWS = require('aws-sdk/global');
```
It seems to be working okay, but I am still testing.

@powerful23, I think that the problem only happens using localhost, which is my oldest workspace and when I am not signed in. Once I sign in when using my localhost build, the problem goes away. Thank you for your time looking into this.

**Comment by 1pocketaces1** [comment]
I fixed this issue a while back and had no issues for a bit, but recently had the warning start popping up again. From reading this thread it seems like the issue was fixed where the warning only showed if the event logging failed, but it seems like my events are being logged correctly in Pinpoint.
Here is my IAM policy please let me know if there are any mistakes or if I can ignore the warning:
<img width="804" alt="Screen Shot 2019-06-23 at 4 29 44 PM" src="https://user-images.githubusercontent.com/34732486/59982269-12f30580-95d5-11e9-953e-077df0eb1485.png">

**Comment by ldgarcia** [comment]
@TheVaporTrail 

I also have in my entry point:
````javascript
import Amplify from '@aws-amplify/core';
Amplify.configure({ /* config here */ });
````

For the other files you can use:
````javascript
import { Analytics } from '@aws-amplify/core';
````
Instead of:
````javascript
import Amplify from '@aws-amplify/core';
const Analytics = Amplify.Analytics;
````
