### ISSUE TITLE
How to use aws-amplify-vue components?

### ISSUE THREAD

**Issue by monsieurTut** [aws-amplify/amplify-js#1760]
Hello,

I am trying to build a Vue.js application that uses AWS AppSync and AWS Cognito user pools.
I followed the Amplify documentation to  configure my app to use amplify vue components.

Here are the steps I took:

- Created new vue app with vue-cli 3:
  `vue create my-project`

- Initiated amplify and added api:
  ```
  amplify init
  amplify add api
  ```

- Installed aws-amplify and aws-amplify-vue:
  ```
  npm i aws-amplify@beta 
  npm i aws-amplify-vue@beta
  ```

- Edited main.js:
  ```javascript
  import Vue from 'vue'
  import App from './App.vue'

  Vue.config.productionTip = false

  import Amplify from 'aws-amplify'
  import * as AmplifyModules from 'aws-amplify'
  import * as AmplifyVue from 'aws-amplify-vue'
  import awsmobile from './aws-exports'
  Amplify.configure(awsmobile)

  Vue.use(AmplifyVue.plugins.amplifyPlugin, {AmplifyModules})

  new Vue({
    render: h => h(App)
  }).$mount('#app')
  ```

- Started dev server:
  `npm run serve`

When I open my app in a web-browser, I get this error: `TypeError: aws_amplify_vue__WEBPACK_IMPORTED_MODULE_6__.plugins is undefined`

What am I doing wrong?

**Comment by haverchuck** [comment]
@monsieurTut - Thanks for reporting this.  We have a bug in our documentation that should be fixed shortly.  

Please try this:

```
import Amplify, * as AmplifyModules from 'aws-amplify';
import { AmplifyPlugin } from 'aws-amplify-vue';
import aws_exports from './aws-exports';
Amplify.configure(aws_exports)

Vue.use(AmplifyPlugin, AmplifyModules);
```
