### ISSUE TITLE
No Cache module registered in Amplify

### ISSUE THREAD

**Issue by tafelito** [aws-amplify/amplify-js#1761]
**Describe the bug**
I'm getting `No Cache module registered in Amplify` when using Storage.put method. Everything was working fine when I was importing everything form `aws-amplify`. Because of the bundle size, I wanted to only import the packages I'm using so I added `@aws-amplify/auth` & `@aws-amplify/storage`. I'm using federated identities for authentication. It seems that Storage needs the cache package as well when loading credentials https://github.com/aws-amplify/amplify-js/blob/cc629f5a7141b32a11644cc448d42598aa1e3d39/packages/core/src/Credentials.ts#L281 

If I import `@aws-amplify/cache` everything works again, but I don't use the Cache for anything else so I'm just importing it to prevent the error. What's the best way to prevent this? 

Do I also need to add the core packages as a dependency? I know I don't have to in order to work, but what's the best practices in this case? Because Amplify needs to be imported as well from `@aws-amplify/core` to configure credentials and storage. Because core is a dependency from the other modules, it works, but as an indirect dependency.

**Expected behavior**
Not having to import modules that I don't directly use, in this case the Cache module

**Comment by powerful23** [comment]
@tafelito can you provide some code snippets about how you are importing those modules. The error happens when the `Cache` module is not correctly registered into the `Amplify` object. The desired order is:
```js
import Auth from '@aws-amplify/auth';
import Storage from '@aws-amplify/storage';
import Amplify from '@aws-amplify/core';
```

**Comment by tafelito** [comment]
when my app starts, I do this

```js
import Amplify from "@aws-amplify/core";
Amplify.configure({
    Auth: {
      identityPoolId: IdentityPoolId,
      region: BucketRegion,
    },
    Storage: {
      bucket: BucketName, 
      region: BucketRegion,
    },
  });
```

Then, after login, I do

```js
import Auth from "@aws-amplify/auth";
Auth.federatedSignIn("facebook", {
            token: accessToken,
            expires_at: expiresAt,
          })
            .then(credentials => {
              console.log("get aws credentials", credentials);
            })
            .catch(e => {
              console.log(e);
            });
```

And then, when I upload an image to S3, I do

```js
import Storage from "@aws-amplify/storage";
Storage.put(photoKey, file, {
      customPrefix: {
        public: path,
      },
      contentType: file.type,
    });
```

**Comment by maksimsemenov** [comment]
I'm still seeing this bug. I installed the latest stable release for `@aws-amplify/auth`:
`package-lock.json`
```
"@aws-amplify/auth": {
      "version": "1.2.6",
      "resolved": "https://registry.npmjs.org/@aws-amplify/auth/-/auth-1.2.6.tgz",
      "integrity": "sha512-QNYcVwskuHP9zVC4v1LAn53OjfQ96xHLftIVHWVQKSLBqOxZceTEwC60BmluXJX+WVA/WaQAbRSRvYcfkgyP/A==",
      "requires": {
        "@aws-amplify/cache": "^1.0.15",
        "@aws-amplify/core": "^1.0.15",
        "amazon-cognito-auth-js": "^1.1.9",
        "amazon-cognito-identity-js": "^3.0.2"
      }
    },
    "@aws-amplify/cache": {
      "version": "1.0.15",
      "resolved": "https://registry.npmjs.org/@aws-amplify/cache/-/cache-1.0.15.tgz",
      "integrity": "sha512-qYhSJEoVJoKWLGVmrVsfI60tl5TEA7HXoJIOIcBHnIdl2vbTG+SPoaBXZ9hTCJ2k1LDmnXO2BCxv+/799Y0toQ==",
      "requires": {
        "@aws-amplify/core": "^1.0.15"
      }
    },
    "@aws-amplify/core": {
      "version": "1.0.15",
      "resolved": "https://registry.npmjs.org/@aws-amplify/core/-/core-1.0.15.tgz",
      "integrity": "sha512-dkZgQu+Ax2WMLMOBGu92N3Qw59ckTpH++91v8GWemf+5y/4X0YkalmJwoG4gUuWfuC3fU2+8dZF4dmL4ORUohA==",
      "requires": {
        "aws-sdk": "^2.312.0",
        "url": "^0.11.0"
      }
    },
```
But in `node_modules/@aws-amplify/core/lib/Credentials.js` I'm still seeing:
```
if (Amplify_1.default.Cache && typeof Amplify_1.default.Cache.setItem === 'function') {
   Amplify_1.default.Cache.setItem('federatedInfo', {
       provider: provider,
       token: token,
       user: user,
       expires_at: expires_at,
       identity_id: identity_id
    }, { priority: 1 });
}
else {
    rej('No Cache module registered in Amplify'); <- still rejecting
    return [2 /*return*/];
}
```

Is it how it supposed to be? What will be the workaround?

**Comment by powerful23** [comment]
@maksimsemenov sorry for the confusion but the fix is not published yet. We will make a release ASAP.

**Comment by maksimsemenov** [comment]
Oh, got it. Thanks!

**Comment by hotgazpacho** [comment]
FYI, I ran into this issue yesterday. I'm on 1.0.10, and I had previously only been using the `Auth` and `Analytics` modules. When I pulled out the `Analytics` module _(Pinpoint is not currently fit for browser analytics, but that's a whole other issue)_, it apparently ALSO caused the `Cache` module not to be initialized, which then caused the `Auth` module to be unable to store the tokens from Cognito.

My solution was to explicitly import the `Cache` module AFTER importing `Amplify` from core:

```
import Amplify from '@aws-amplify/core';
import '@aws-amplify/cache';
import AmplifyAuth from '@aws-amplify/auth';
```

**Comment by tafelito** [comment]
@powerful23 was this already published ? I'm seeing a similar issue but with the Auth module now, even tho I haven't changed anything on my side. I have the same issue as in #1977 and I tried deleting the node_modules folder but did not work. 
Any other suggestions?
