### ISSUE TITLE
Connect component mutation docs are incomplete

### ISSUE THREAD

**Issue by blbradley** [aws-amplify/amplify-js#1762]
**Describe the bug**
Connect component mutation docs do not describe how to pass variables to the mutation function.

**To Reproduce**
1. Go to [relevant portion of docs](https://aws-amplify.github.io/amplify-js/media/api_guide#connect)
1. Scroll down to 'For mutations,'
4. No docs about passing variables

**Expected behavior**
Docs about passing variables

**Additional context**
I had to read the library code to figure it out.

**Comment by jordanranz** [comment]
Hey @blbradley, thanks for the feedback.

We are currently migrating our docs repo to this one here:
https://github.com/aws-amplify/docs

If you want to submit a PR here, it will go live by end of this week or early next week.
