### ISSUE TITLE
XR Guide Issue

### ISSUE THREAD

**Issue by 107356019** [aws-amplify/amplify-js#1769]
**Describe the bug**
The XR document in  https://aws-amplify.github.io/amplify-js/media/xr_guide has missing a comma 

**Expected behavior**
Modify this issue .

**Screenshots**
![2018-09-27 5 08 51](https://user-images.githubusercontent.com/43407272/46135882-d62df400-c278-11e8-9cb6-e70d269a9db9.png)

**Comment by jordanranz** [comment]
Hello @107356019, good catch.

This will be fixed as soon as our new docs repo is live by end of week. Thanks for calling it out.

**Comment by jordanranz** [comment]
This is fixed with our new documentation. Thanks again for the feedback.

https://aws-amplify.github.io/docs/js/xr
