### ISSUE TITLE
Attribute value for phone_number must not be null

### ISSUE THREAD

**Issue by stevemao** [aws-amplify/amplify-js#1776]
**Describe the bug**
phone_number is optional when register so it can be left out. Also react component

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by jordanranz** [comment]
Hi @stevemao,

#1774 should fix this. Thanks for submitting feedback.

**Comment by jordanranz** [comment]
I am going to close this issue. Please reopen if you have any related problems.
