### ISSUE TITLE
When there's an error popup, it doesn't disappear when all my input data is valid and click submit

### ISSUE THREAD

**Issue by stevemao** [aws-amplify/amplify-js#1777]
**Describe the bug**
When there's an error, say my phone number's format is not correct. I fixed the error by entering a valid phone number and click "register". The error popup at the top should disappear. But instead, a blank popup is still there. Also react.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by jordanranz** [comment]
The Toast component was not being reset on auth state change. I have submitted a PR to fix this. Thanks for the feedback!

**Comment by jordanranz** [comment]
This should be fixed: #2030 

Please reopen if you are experiencing any related issues.
