### ISSUE TITLE
Getting undefined error for push notification

### ISSUE THREAD

**Issue by AakashRainaClairvoyant** [aws-amplify/amplify-js#1778]
Related to push notifications

My Code:

import Amplify from "aws-amplify";
import Analytics from "aws-amplify";
import { PushNotification } from "aws-amplify-react-native";
import aws_exports from "./aws-exports";

Amplify.configure(aws_exports);
Analytics.configure(aws_exports);
PushNotification.configure(aws_exports);

componentDidMount() {
     PushNotification.onNotification(notification => {
      console.log("in app notification", notification);
    });
    PushNotification.onRegister(token => {
      console.log("in app registration", token);
    });
  }

![screenshot_20180928-143651](https://user-images.githubusercontent.com/33493345/46199598-1484eb00-c32d-11e8-909e-156d346034a3.png)

**Comment by powerful23** [comment]
@AakashRainaClairvoyant hi please follow the latest doc to configure pushnotification module: https://aws-amplify.github.io/amplify-js/media/push_notifications_setup#configure-your-app

**Comment by powerful23** [comment]
Closing this issue due to no further response. Feel free to reopen if you still have this issue.
