### ISSUE TITLE
aws-amplify-vue leaks global styles

### ISSUE THREAD

**Issue by dominiklessel** [aws-amplify/amplify-js#1783]
**Describe the bug**
When using `aws-amplify-vue` and `bootstrap-vue` in the same project everything seems fine in dev. When deployed and built for production global `aws-amplify-vue` style overwrite bootstrap styles. Also global css vars are leaked.

**To Reproduce**
Take a look at this [CodeSandbox](https://codesandbox.io/s/nn17m9jolp). Preview looks fine. If you download it, install deps, run `npm run build` and take a look at the results, it will clearly show you my problem.

**Expected behavior**
No global styles leaked by `aws-amplify-vue` if I don't want it. It would be nice to have control over this behavior.

**Screenshots**
![amplify-vs-bootstrap-styles](https://user-images.githubusercontent.com/582281/46242868-e9060d00-c3cd-11e8-8846-5e18189d75e9.jpg)

**Desktop**
 - OS: macOS Sierra 10.12.6
 - Browser: Chrome, Firefox
 - Version: 69.0.3497.100, 62.0.2

**Comment by haverchuck** [comment]
@dominiklessel - Thanks for reporting this. We will take a look.

**Comment by haverchuck** [comment]
@dominiklessel  - We've merged a PR that should hopefully address this into our master branch.   You can pull it directly from GitHub or using the 'unstable' tag in npm (keep in mind it may take a bit of time to propogate to npm, as I merged the code seconds before writing this).

**Comment by dominiklessel** [comment]
@haverchuck Thank you very much! This works as expected 👍
