### ISSUE TITLE
amplify graphql transform complex object support

### ISSUE THREAD

**Issue by hannersmatto** [aws-amplify/amplify-js#1788]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hannersmatto** [comment]
Hi Folks loving the declarative aspect to GraphQL Transform in Amplify. I would like to be able to be able to include complex objects such as S3 Objects in the schema. What do you all think?

**Comment by sammartinez** [comment]
@hannersmatto Is this still a use case you are looking for. Please let us know
