### ISSUE TITLE
Federated identity - ReactJS: Sign-in buttons does not support translation

### ISSUE THREAD

**Issue by jonasao** [aws-amplify/amplify-js#1791]
The Sign-in buttons representing the different federated identity providers, Facebook, Google etc.
does not support translation. 

An improvement would be to make the button texts support the I18n-format, allowing the user to translate the button text to their native language.

**Comment by jonasao** [comment]
Thanks @jordanranz

**Comment by jordanranz** [comment]
Going to go ahead and close this issue now. Please reopen if you experience any issues.
