### ISSUE TITLE
Is is possible to use Amplify for authentication via secrets and certificates?

### ISSUE THREAD

**Issue by AntonSmatanik** [aws-amplify/amplify-js#1795]
Is is possible to use Amplify for authentication via secrets and certificates?

With aws-iot-device-sdk I just set it like:

`awsIot.device({
    keyPath: awsConfig.broker.keyPath,
    certPath: awsConfig.broker.certPath,
    caPath: awsConfig.broker.caPath,
    host: awsConfig.broker.endpoint,
    clientId: uuid.v4(),
    baseReconnectTimeMs: awsConfig.broker.reconnect,
    maximumReconnectTimeMs: awsConfig.broker.maximumReconnect,
})`

Question is if something like this is possible with Amplify...

**Comment by haverchuck** [comment]
@AntonSmatanik I believe that the usage of certs you've cited out is specific to IoT.  Amplify does not currently offer this functionality, although we will pass this request along.  Thanks for reaching out.
