### ISSUE TITLE
No Targetable Endpoint After Register Pinpoint

### ISSUE THREAD

**Issue by pmd30011991** [aws-amplify/amplify-js#1797]
Look seems OK but no targetable endpoint on Pinpoint

**Describe the bug**
{[DEBUG] 41:12.675 AWSPinpointProvider - endpointId from cache: Array(3)}
[DEBUG] 41:12.676 AWSPinpointProvider - init clients
{[DEBUG] 41:12.676 AWSPinpointProvider - init clients with credentials: {…}}
{"[DEBUG] 41:12.686 AWSPinpointProvider - updateEndpoint with params: ": {…}}
{[DEBUG] 41:12.703 AWSPinpointProvider - endpointId from cache: Array(3)}
[DEBUG] 41:12.705 AWSPinpointProvider - init clients
[DEBUG] 41:12.705 AWSPinpointProvider - no change for aws credentials, directly return from init
[DEBUG] 41:12.706 AWSPinpointProvider - record session start
{[DEBUG] 41:13.285 AWSPinpointProvider - updateEndpoint success: {…}}
{"[DEBUG] 41:13.954 AWSPinpointProvider - record event success. ": {…}}

My packages.json

![image](https://user-images.githubusercontent.com/1608649/46299328-b299df00-c5d3-11e8-9911-b835fb954923.png)

**Comment by pmd30011991** [comment]
Thanks for replying
I’m trying to push notification to both ios and android phones which are install my application

I also share cognito user data to analytics as well

I also test with mobile push configurations with device token to make sure the config correct.

**Comment by haverchuck** [comment]
@pmd30011991  Did you set up analytics with the Amplify-CLI?

**Comment by powerful23** [comment]
Related to #1779

**Comment by pmd30011991** [comment]
I just upgrade aws-amplify to version 1.1.4 then solved.
