### ISSUE TITLE
react-native Connect to existing user Identity pool

### ISSUE THREAD

**Issue by Uzairrrr** [aws-amplify/amplify-js#1798]
can we connect our new project of react-native to existing user Identity pool?

**Comment by haverchuck** [comment]
@Uzairrrr - Yes!  Please check out the instructions [here](https://aws-amplify.github.io/amplify-js/media/quick_start#step-5-host-your-app), under the heading "Existing AWS Resources".

I'm closing this issue for now, but please feel free to re-open it if your question has not been addressed.
