### ISSUE TITLE
Parcel fails to bundle amplify: Cannot resolve dependency 'aws-sdk/global'

### ISSUE THREAD

**Issue by jadbox** [aws-amplify/amplify-js#1806]
parcel-bundler: "^1.10.1"

```
🚨  ./myproject/node_modules/@aws-amplify/core/lib/Facet.js:16:18: Cannot resolve dependency 'aws-sdk/global'
  14 | Object.defineProperty(exports, "__esModule", { value: true });
  15 | // import * as S3 from 'aws-sdk/clients/s3';
> 16 | var AWS = require("aws-sdk/global");
     |                  ^
  17 | exports.AWS = AWS;
  18 | //# sourceMappingURL=Facet.js.map
```

**Comment by haverchuck** [comment]
@jadbox  - trying to reproduce this in a parcel-bundler [Vue example](https://github.com/parcel-bundler/examples), and so far unable.  Can you provide a little more detail as to how you're importing/using Amplify?

Much appreciated!

**Comment by jadbox** [comment]
There's not a lot of code in my project. I've included my line of imports below. 

[Latest] Versions:
* "aws-amplify": "^1.1.4",
* "aws-amplify-react": "^2.0.5"

Toolchain:

* Typescript 3.1.1 + react-scripts-ts
* Parcel bundler 1.10.1

```
import 'aws-sdk/lib/node_loader'; // first time only
import Core from 'aws-sdk/lib/core'
import AWS from 'aws-sdk/global'
import Auth from '@aws-amplify/auth';
```

tsconfig:
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "preserve",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": false,
    "noImplicitThis": true,
    "noImplicitAny": false,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": false,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "isolatedModules": false
  },
  "include": [
    "src/**/*",
    "typings/*"
  ],
  "exclude": [
    "webpack.config.prod.js",
    "webpack.config.js",
    "backend",
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts",
    "proxy.js",
    "*.md",
    "CHANGELOG.md",
    "awsmobilejs",
    "/assets",
    "public",
    "/backend"
  ]
}
```

**Comment by haverchuck** [comment]
@jadbox  I was able to import these modules in a parcel build with [this sample app](https://github.com/jaredpalmer/react-parcel-example). This leads me to think it has something to do with your tsconfig and/or react-scripts-ts.  

Out of curiosity, why do you have webpack files in your exclude array?  Are you using webpack and paracel concurrently somehow?

**Comment by jadbox** [comment]
@haverchuck Hah nice catch, I've been currently trying out both to see which one would be better for my project.
I'm going to close this ticket for now since you have a working test, and I've had to move on and decided to go with Webpack as it wasn't giving me this issue.
