### ISSUE TITLE
Automatic Page View Tracking

### ISSUE THREAD

**Issue by nedlowe** [aws-amplify/amplify-js#1808]
** Which Category is your question related to? **
Analytics - Automatic Page View Tracking:
https://aws-amplify.github.io/amplify-js/media/analytics_guide.html#page-view-tracking

** What AWS Services are you utilizing? **
Pinpoint

** Provide additional details e.g. code snippets **
Has anyone managed to get this working using the link above (POJO, I'm not using React/Angular or anything else that might be complicating this)?  I can record bespoke events, and the Session Tracking works - but I can't work out how to get pageView working.  A working example would be hugely appreciated!

Thanks

**Comment by haverchuck** [comment]
@nedlowe  - Which version of Amplify are you using?  Are you receiving any sort of error output?

**Comment by nedlowe** [comment]
1.1.4

No error I'm afraid. Session tracking and custom events are fine, it's just the automatic pageView ones.

If you have a working example, I'd love to see your app.js - I can use that to work backwards and work out what I'm doing wrong.

Many thanks

**Comment by haverchuck** [comment]
@nedlowe  - Are you building a single page app, and if so did you set the Analytics 'type' config value to `'SPA'`?

**Comment by nedlowe** [comment]
Hi,

1. No.
2. No.
3. Thanks.

Do you have an example of it working in any situation?

Thanks

**Comment by haverchuck** [comment]
Yeah - working on getting a Vue example pushed outt to GH but it might be a little while before that happens.  
When you do verbose logging, are there any Pinpoint entries in your console?

**Comment by nedlowe** [comment]
OK so through the use of VERBOSE I could see that when I reloaded the page it was giving the 'the url is same' mentioned above (it's not SPA, it doesn't have a router - I was just reloading).  I guess that that was invalidating my debugging/testing, as anytime I changed anything I was reloading the page - and that was probably being filtered I guess.  I got it to work now.   Thanks.

**Comment by haverchuck** [comment]
@nedlowe - thanks for letting use know it's resolved.
