### ISSUE TITLE
Overriding existing s3 data on iOS is broken

### ISSUE THREAD

**Issue by BronxBombers** [aws-amplify/amplify-js#1814]
**Describe the bug**
I have amplify configured correctly and working for Auth and Storage (s3). All s3 operations work, except when trying to override an existing file with put, or delete. The issue only happens on iOS, and works perfectly fine on Android. The specific error message I am getting is a "501 Error: A header you provided implies functionality that is not implemented". 

**To Reproduce**
Here is my code for put: `Storage.put("note1538447017.txt", "test text", {level: "protected"})`
And Delete: `Storage.remove("note1538447017.txt", {level: 'protected'})`

**Expected behavior**
This file exists before calling either of these, so I expect the put to override the contents, and the delete to remove it. I have configured Amplify correctly as everything works on Android, so something is happening with iOS.

**Desktop (please complete the following information):**
 - OS: MacOS

**Smartphone (please complete the following information):**
 - Device: iPhone Simulator
 - OS: iOS 9

**Additional context**

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***
<img width="523" alt="screen shot 2018-10-01 at 2 50 43 pm" src="https://user-images.githubusercontent.com/28161704/46358526-27e9cc00-c635-11e8-992d-79d2dab07061.png">

**Comment by haverchuck** [comment]
@BronxBombers Are you using React Native?

**Comment by BronxBombers** [comment]
Yes react native

**Comment by elorzafe** [comment]
Hi @BronxBombers I try to reproduce your use and put and remove works for me. (I used "aws-amplify": "^1.1.4", "aws-amplify-react-native": "^2.0.4") My simulator is an iPhone 6 with iOS 11.2

Which version of aws-amplify aws-amplify-react-native are you using?

**Comment by BronxBombers** [comment]
I was using ^1.1.3 and ^2.0.3. i will try upgrading and see what happens.

**Comment by elorzafe** [comment]
@BronxBombers, how are you configuring Amplify?

**Comment by BronxBombers** [comment]
Using `Amplify.configure(AWSCONFIG);` with that being my aws-exports.js file which I did not touch, and was generated by my calls to Amplify init, Amplify add storage, Amplify add auth.

**Comment by BronxBombers** [comment]
@elorzafe Actually my last comment was not the whole truth! I'm unable to override/delete admin created data, and more broadly, **any data that was not created in the current session**. For example, I upload data, and before logging out, I am able to delete/change it. However, once I close the app, and re-log in, I get the 501 error when trying to change that data that I was just able to manipulate.

**Comment by BronxBombers** [comment]
@elorzafe Same user. The error message I'm receiving is not a permission denied. I tried granting administrator permissions to the user group, and got the same error message back so it definitely has nothing to do with permissions. Just to be clear on what is happening, I log in with a user. I am able to get the user's data, create new data, and modify/delete data that was created only in the current session. When I log out, and log back in with the same user, I am able to see the data created in the last session, but cannot modify or delete it.

**Comment by elorzafe** [comment]
@BronxBombers How large are the files?

**Comment by BronxBombers** [comment]
@elorzafe small text files <100 Bytes

**Comment by elorzafe** [comment]
I tried this code on my App.js file
```
import React from 'react';
import { StyleSheet, View, Button } from 'react-native';
import Amplify, { Storage } from 'aws-amplify';
import uuid from 'uuid';
import awsconfig from './aws-exports';
import { withAuthenticator } from 'aws-amplify-react-native';

Amplify.Logger.LOG_LEVEL = 'DEBUG';
Amplify.configure(awsconfig);

class App extends React.Component {

  putObject() {
    const content = uuid();
    Storage.put('content.txt', content, { level: "protected"});
  }
  deleteObject() {
    Storage.remove('content.txt', { level: "protected"});
  }

  render() {
    return (
      <View style={styles.container}>
        <Button onPress={this.putObject} title="putObject"></Button>
        <Button onPress={this.deleteObject} title="deleteObject"></Button>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default withAuthenticator(App, true);
```

This is my package.json
```
{
  "name": "empty-project-template",
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "aws-amplify": "^1.1.4",
    "aws-amplify-react-native": "^2.0.4",
    "expo": "^30.0.1",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz",
    "uuid": "^3.3.2"
  },
  "devDependencies": {
    "reactotron-react-native": "^2.1.0"
  }
}
```

Can you try that code? Let me know how it goes

**Comment by BronxBombers** [comment]
https://github.com/BronxBombers/Simpacta-Notes/blob/master/Mobile/package.json

**Comment by BronxBombers** [comment]
Here is the code for my delete: https://github.com/BronxBombers/Simpacta-Notes/blob/eb546ced36937864ef5dc3ff1e9d1009251e978d/Mobile/App/NotesScreen/Notes/NotesContainer.js#L50

**Comment by BronxBombers** [comment]
And this is the update code: https://github.com/BronxBombers/Simpacta-Notes/blob/eb546ced36937864ef5dc3ff1e9d1009251e978d/Mobile/App/NotesScreen/Notes/Note.js#L44

**Comment by elorzafe** [comment]
The code looks good to me, can you try a couple of things?

Can you verify the key of the object (There is a debug message: [DEBUG] 40:34.998 StorageClass - put...) When you are trying to update the file. Just compare if is the same.

The other is more challenging but it will be use withAuthenticator HOC and wrap your app around it like this.
```
export default withAuthenticator(App, true);
```
You will need to disable your login flow :/

**Comment by BronxBombers** [comment]
@elorzafe 
The keys are 100% valid and I have checked and verified that this error message only happens when I am performing an operation with a key that already exists. For some reason whenever I try to use any Amplify UI components I get this error 
<img width="342" alt="screen shot 2018-10-08 at 10 46 31 am" src="https://user-images.githubusercontent.com/28161704/46616093-c9ff2d80-cae7-11e8-84b9-23b2aceb8a41.png">

**Comment by BronxBombers** [comment]
I checked to make sure that mentioned file exists on my computer, and have ran all of the usual commands to resolve something missing from the Haste module map.

**Comment by BronxBombers** [comment]
@elorzafe I archived the project and ran it on a new device through test flight, and the same exact behavior is still happening. So this is not an issue with a development build, or the simulator...

**Comment by BronxBombers** [comment]
@elorzafe This issue is still happening, waited to hope it would disappear with an update, but on versions 2.0.7 of the react-native library, and 2.1.1 it is still happening.

**Comment by jordanranz** [comment]
Hey @BronxBombers, are you using aws-amplify-react in your project? The error mentioned above suggests you are trying to use one of our web specific component libraries (React, Angular, Vue). Using one of these libraries in React Native is not supported.

**Comment by BronxBombers** [comment]
No, this error is originating from using the Storage object from the base aws-amplify module. I am not using any react or react-native specific components in the project.

**Comment by jordanranz** [comment]
Sorry, I was talking about the React Native error above. You mention "For some reason whenever I try to use any Amplify UI components I get this error". This error is likely caused by using `aws-amplify-react` instead of `aws-amplify-react-native`

**Comment by annjawn** [comment]
Did this ever get resolved? I am also encountering this exact issue. It only happens in iOS with react native bit works fine in Android.
