### ISSUE TITLE
Amplify Init Run on each machine used to develop?

### ISSUE THREAD

**Issue by LiquidSean** [aws-amplify/amplify-js#1815]
So I am working on a project and my team decided to go with amplify-js and react.js. My question is realated to 'amplify init'. Does that command need to be run on each developers machine when the pull the code? I noticed when I ran the command it created hardcoded paths to locations on my macbook. Also it looks like running amplify init on another machines destroys the previous instance

**Comment by mwarger** [comment]
This seems related to https://github.com/aws-amplify/amplify-cli/issues/233

**Comment by jordanranz** [comment]
Closing this issue as it pertains to the CLI and the issue above answers your question. If you are still experiencing issues or have any further related questions please open an issue in the amplify-cli repo: 
https://github.com/aws-amplify/amplify-cli/issues
