### ISSUE TITLE
Auth/Unauth roles

### ISSUE THREAD

**Issue by ryanwmarsh** [aws-amplify/amplify-js#1819]
Could you help me understand the necessity for the auth/unauth roles? I’d like to understand more of what’s going on with the CloudFormation that Amplify is generating and how it’s used, especially before putting it into prod.

** Which Category is your question related to? **
Roles in the CFN templates

** What AWS Services are you utilizing? **
This is in the base template

** Provide additional details e.g. code snippets **
```json
"AuthRole": {
"Type": "AWS::IAM::Role",
"Properties": {
    "RoleName": {
    "Ref": "AuthRoleName"
    },
    "AssumeRolePolicyDocument": {
    "Version": "2012-10-17",
    "Statement": [
        {
        "Sid": "",
        "Effect": "Allow",
        "Principal": {
            "Federated": "cognito-identity.amazonaws.com"
        },
        "Action": "sts:AssumeRoleWithWebIdentity",
        "Condition": {
            "ForAnyValue:StringLike": {
            "cognito-identity.amazonaws.com:amr": "authenticated"
            }
        }
        }
    ]
    }
}
},
"UnauthRole": {
"Type": "AWS::IAM::Role",
"Properties": {
    "RoleName": {
    "Ref": "UnauthRoleName"
    },
    "AssumeRolePolicyDocument": {
    "Version": "2012-10-17",
    "Statement": [
        {
        "Sid": "",
        "Effect": "Allow",
        "Principal": {
            "Federated": "cognito-identity.amazonaws.com"
        },
        "Action": "sts:AssumeRoleWithWebIdentity",
        "Condition": {
            "ForAnyValue:StringLike": {
            "cognito-identity.amazonaws.com:amr": "unauthenticated"
            }
        }
        }
    ]
    }
}
}
```

**Comment by elorzafe** [comment]
Hi @ryanwmarsh 

One option to give access to your app end users to AWS resources is by giving them temporary AWS credentials. (Those temporary credentials are provided by Amazon Cognito Federated Identities (IdentityPool))

Your App IdentityPool can give credentials to authenticated and unauthenticated users (guest user that didn't signup in your app). Each group of users (auth and unauth) has an IAM Role which basically is the permission that each group has. (Maybe you dont want the same privileges for unauth users)

When you use aws-amplify/cli the permissions are configured for you automatically for each resource by attaching IAM policies (permissions configuration) to each role.

**Comment by NikoMontana** [comment]
@elorzafe Thanks for the explanation!

I tried to understand this for the last few days. But by looking into the amplify documentation I simply cannot achieve to call the Appsync API. Could you be so kind to provide some code or appsync configuration to get an idea of this use case?

I have come to the point where I configured amplify cli auth with IAM Role models like you said and I can see, by using the app, that the counter for unauth goes up in the cognito console for federated identities.
