### ISSUE TITLE
Allowing API users to run lambda using execution role from Cognito

### ISSUE THREAD

**Issue by MathiasGruber** [aws-amplify/amplify-js#1823]
What I want to do is have a lambda function, which assumes the cognito roles, so as to allow it to access the S3 buckets of the user making the request and nobody else. I've followed this guide for setting up API gateway:
https://aws.amazon.com/premiumsupport/knowledge-center/cognito-user-pool-group/

But "cognito:roles" key never appears in the event variable in the lambda handler. Everything else seems to work fine. Am I doing this completely wrong?

** Which Category is your question related to? **
Cognito & Storage

** What AWS Services are you utilizing? **
Lambda, Cognito, API gateway

** Provide additional details e.g. code snippets **

**Sending the request**
`let myImage = {
            headers: {
              "Authorization": this.props.authData.signInUserSession.idToken.jwtToken
            },
            response: true,
            queryStringParameters: {
                level: level,
                user: unescape(user_identity_id),
                image: key
            }
        }`
`
API.get(apiName, path, myImage).then(response => {
            Storage.get(response['data']['key'], { level: response['data']['level'] })
            .then(url => {
              this.setState({result_img: url})
            })
            .catch(err => {
              console.log('Error', err)
            });
        }).catch(error => {
          console.log("Error", error)
        });`

**Comment by 10ky** [comment]
According to the instruction, in this step:

An Amazon Cognito user pool and group with an associated IAM role

I believe in order for a resource to assume a role, that resource has to be in a trusted relationship.  You can check out how assume role works with AWS docs.

This means to me, you may want to check your role and click on the "trust relationship".  Edit the trust relationship, add your lambda ARN in there.

The AWS guide you are referring don't have that steps.  I wonder if that is what is missing.

**Comment by elorzafe** [comment]
@MathiasGruber why do you need to allow access to individual buckets per user? If you need fine-grained access control you can do that with only one bucket. Amplify-cli configures permissions to one S3 bucket to allow this access control for individual users. Take a look [here](https://aws-amplify.github.io/docs/js/storage#file-access-levels) for information.

**Comment by alebiavati** [comment]
Closing issue as inactive, please open another issue with more details if you still need support.

**Comment by rathpa** [comment]
To get the "cognito:roles" to exist, in Cognito the user needs to be part of a group and that group needs to have a role.  Thus, go into Cognito, select your user pool, users and groups, groups, create a group (adding a role to that group), and then add the user to the group.
