### ISSUE TITLE
Provide a set of built-in example projects

### ISSUE THREAD

**Issue by stormit-vn** [aws-amplify/amplify-js#1825]
**Is your feature request related to a problem? Please describe.**
Like other authentication modules such as Okta. They built some example projects that allow developer easy to clone and work on that project without spending the time to set up new empty project even using CLI. If we have the example projects, then we only focus to learn how to use this module and its APIs

**Describe the solution you'd like**
Develop more example projects (e.g. angular, react, react native, etc.).

**Comment by haverchuck** [comment]
@stormit-vn - Thanks for reaching out.  This is a great suggestion.   We have several starters that are in the works or just need to be updated, but for now here is a Vue.js starter that you can take a look at:

 [AWS Amplify Vue Starter](https://github.com/aws-samples/aws-amplify-vue)

**Comment by stormit-vn** [comment]
@haverchuck  Thanh you for your response. I am looking for angular/react project. Much appropriate if anyone can share your example that you are working on.

**Comment by haverchuck** [comment]
Taking the thumbs up as an indicator that @richardzcode 's comment is adequate, and closing this issue.
