### ISSUE TITLE
ReactJS - Auth - missing I18n support

### ISSUE THREAD

**Issue by jonasao** [aws-amplify/amplify-js#1826]
**Description**
The text "or" between the federated identity choice and username/password in the authentication form cannot be translated to du missing support for I18n.

This bug resides in the following file:
https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Auth/FederatedSignIn.jsx

**Expected behavior**
Support for I18n, allowing the user to translate this text string.

**Comment by haverchuck** [comment]
@jonasao -  we just merged a fix for this into our unstable branch.  You can install it from npm using the '@unstable' tag.
