### ISSUE TITLE
GraphQL always gets bundled (webpack)

### ISSUE THREAD

**Issue by jadbox** [aws-amplify/amplify-js#1831]
These are the only imports I have of Amplify, and I'm not using any of the GraphQL features. However, when using Webpack Bundle Analyzer, I see that almost 150kb of my project hundle is the GraphQL module that Amplify imports. I did try to tell Webpack to exclude the module from my build, but then Amplify fails to load because it explicitly imports GraphQL in one of its files (there was no stack trace given). Again, below are the only imports my project uses:

```
import Auth from '@aws-amplify/auth';
import { Hub, ConsoleLogger } from '@aws-amplify/core';
```

aws-amplify          1.1.4
aws-amplify-react    2.0.5

**Comment by powerful23** [comment]
@jadbox can you try removing `aws-amplify` and only installing `@aws-amplify/auth`?

**Comment by jadbox** [comment]
@powerful23 So installed `@aws-amplify/core'` (I need it for Hub unless there's another way to get it) and  `@aws-amplify/auth`. However, I forgot I was importing aws-amplify-react for the hosted UI redirect feature and now it complains about missing all sorts of amplify modules... I didn't get through them all but a good guess might be that graphql might be one of them. This is my only import for amplify-react:
`import { withOAuth } from 'aws-amplify-react';`

Once I removed aws-amplify-react from my project, the build dropped by 500kb. However, my Analyzer is broken now and I'm not sure if this ended up also removing graphql.

Is there a better way to just get withOAuth? Is aws-amplify-react modular too?

**Comment by zyzski** [comment]
graphql is bundled in mine even after removing aws-amplify-react. here's a screenshot of my bundle generated by create-react-app.

![screen shot 2018-10-04 at 12 08 10 pm](https://user-images.githubusercontent.com/4314335/46487605-6f579000-c7ce-11e8-8ae7-c32b43a4cc03.png)

this is my only import statement:   
`import Amplify, { Auth } from 'aws-amplify';`

**Comment by powerful23** [comment]
The root cause is the `aws-amplify` which will import all the modules. And if you are using `aws-amplify-react`, you have to import the whole `aws-amplify` library for now.

**Comment by zyzski** [comment]
thanks for the quick response. is there any way to configure the auth module with cognito pool info without including Amplify?

**Comment by kadrach** [comment]
`@aws-amplify/api` always required bundling graphql as well. It would be nice if the `aws4` signature process for REST endpoints (e.g. Lambda) could be loaded individually.

**Comment by dave-irvine** [comment]
Is anyone still looking into this? I'm still getting all of GraphQL bundled even though I don't access any GraphQL features.

It looks like this line: https://github.com/aws-amplify/amplify-js/blob/master/packages/api/src/API.ts#L13

gets compiled down to:

```
var graphql_1 = require("graphql");
```

when transpiled from TS to JS, so instead of just importing the parts needed to create a GraphQLError, you get the entire library.

**Comment by samparnell** [comment]
> The root cause is the `aws-amplify` which will import all the modules. And if you are using `aws-amplify-react`, you have to import the whole `aws-amplify` library for now.

Will this be resolve at some point? If you are just using Amplify for Auth in a React app then there is an excessive amount of additional stuff that gets included.
