### ISSUE TITLE
Basic user signin issue in starter app

### ISSUE THREAD

**Issue by chai86** [aws-amplify/amplify-js#1834]
In the _aws-mobile-react-native-starter app_, when using the app to sign in (having successfully signed up), i get the error:  **cannot read property of 'signIn' undefined**. It appears in the login screen window on the iOS iPhone simulator. 

I'm trying to use the username and password combination that i signed up with, but it returns this error and i don't know why. The error appears to be thrown when auth.signIn(username,password) returns a null session. Any ideas?

**Comment by chai86** [comment]
@nidsharm Would you be able to assist/delegate here? The issue is just in the initial sign in when first loading the original app, no changes to the code have been made at this point.

**Comment by chai86** [comment]
@luigibaute @mlabieniec @swaminator @UnleashedMind can you assist here please?

**Comment by powerful23** [comment]
@chai86 hey we found the version of `aws-amplify` used by react native starter is pretty old and has sent a pr to update it: https://github.com/aws-samples/aws-mobile-react-native-starter/pull/78
