### ISSUE TITLE
Missing Paho type definitions 

### ISSUE THREAD

**Issue by stormit-vn** [aws-amplify/amplify-js#1836]
I am getting this error when importing AmplifyAngularModule into Angular project

ERROR in node_modules/@aws-amplify/pubsub/lib/Providers/MqttOverWSProvider.d.ts(11,72): error TS2694: Namespace ''*'' has no exported member 'Client'.
node_modules/@aws-amplify/pubsub/lib/Providers/MqttOverWSProvider.d.ts(28,70): error TS2694: Namespace ''*'' has no exported member 'Client'.
node_modules/@aws-amplify/pubsub/lib/Providers/MqttOverWSProvider.d.ts(29,87): error TS2694: Namespace ''*'' has no exported member 'Client'.

**Comment by mwarger** [comment]
I raised this as well with a previously closed error: https://github.com/aws-amplify/amplify-js/issues/552

**Comment by mwarger** [comment]
@haverchuck this isn't just an Angular issue.  This happens as well for me for a React project using TypeScript.  I think it's a more general issue with the types.

**Comment by haverchuck** [comment]
@mwarger and @stormit-vn - I just made a fresh angular 6 app and imported these amplify libraries...
```
    "aws-amplify": "^1.1.5",
    "aws-amplify-angular": "^2.0.8",
```
...and integrated the authenticator module.  No problems so far.  Could you provide a little more detail about your project(s) so I can reproduce this issue?

**Comment by stormit-vn** [comment]
@haverchuck ha are you able to share your sample project? You are using angular with webpack bundler or with angular cli starter project?

FYI - I used [angular starter](https://github.com/gdi2290/angular-starter)  and tried to import modules and getting above error

**Comment by haverchuck** [comment]
@stormit-vn I used the angular cli.  I'll pull down the project you linked to above and try to repro.

**Comment by stormit-vn** [comment]
@haverchuck  you can use my fork repo at https://github.com/stormit-vn/angular-starter/

**Comment by haverchuck** [comment]
@stormit-vn and @mwarger -  try:
```
npm i aws-amplify@unstable aws-amplify-angular@unstable
```
I believe this issue has been fixed on those builds.  Using the unstable builds I got the starter to work without issue.

Closing for now, but feel free to re-open!
