### ISSUE TITLE
Customize how Cognito JWT's are stored

### ISSUE THREAD

**Issue by guanzo** [aws-amplify/amplify-js#1840]
** Which Category is your question related to? **

Auth

** What AWS Services are you utilizing? **

Cognito

** Provide additional details e.g. code snippets **

Is it possible to connect this lib: https://github.com/zendesk/cross-storage with aws-amplify? As far as I know, you can tell amplify to either store the JWTs in localStorage or cookies. Can the Auth module accept some sort of class that implements the localStorage API?

**Comment by powerful23** [comment]
@guanzo You can try to provide a storage interface to the Auth module: https://aws-amplify.github.io/amplify-js/media/authentication_guide.html#managing-security-tokens

**Comment by guanzo** [comment]
Great, this looks like exactly what I need, thanks.
