### ISSUE TITLE
Expose api to retrieve authenticated status

### ISSUE THREAD

**Issue by stormit-vn** [aws-amplify/amplify-js#1847]
**Is your feature request related to a problem? Please describe.**
I want to determine whether we have any authenticated user to allow or not allow user access to a particular component of the app such as using Guard in Angular

**Describe the solution you'd like**
It would be better if we can expose an API in the auth module to retrieve the authentication state (i.e. auth.isAuthenticated() => return boolean or Promise<boolean>. I think it can be done by checking the current authenticated user.

Moreover, if we can implement an Angular guard likes [okta.guard](https://github.com/okta/okta-oidc-js/blob/master/packages/okta-angular/src/okta/okta.guard.ts) that would be great.

**Comment by sammartinez** [comment]
@stormit-vn Is this still a valid use case for you, please let us know.
