### ISSUE TITLE
PushNotification open action deeplinking

### ISSUE THREAD

**Issue by schavaLogi** [aws-amplify/amplify-js#1849]
Push Notification deep-linking behaviour:
Would like to know how to detect the notification open and detect deeplink uri from the pinpoint object. Based on deeplink would like to open particular screen in the application

Current Behaviour:
Application launching directly but there is no information in Linking.getInitialUrl()

**Comment by elorzafe** [comment]
@schavaLogi you can redirect your app when you get the notification on the `onNotification` event handler. Take a look [here](https://aws-amplify.github.io/amplify-js/media/push_notifications_setup#working-with-the-api)

I will close this issue for now, but feel free to reopen in the case you have issues with this.

**Comment by schavaLogi** [comment]
@elorzafe The callbacks are not intuitive to handle all scenarios. 
Android: When app killed and notification received then also onNotification triggered but not in react lifecycle context.
I think https://github.com/aws-amplify/amplify-js/pull/1434 PR will help to handle in global and react life cylces scopes.
