### ISSUE TITLE
CORS error when trying to invoke cloud-api function created in AWS Mobile.

### ISSUE THREAD

**Issue by danielhep** [aws-amplify/amplify-js#1855]
** Which Category is your question related to? **
Cloud API/Lambda function
** What AWS Services are you utilizing? **
AWS Mobile, AWS Lambda
** Provide additional details e.g. code snippets **
I am getting a CORS error when I use API.get() in my code to invoke a private cloud-API that I created using the AWS Mobile CLI. It's an auto-generated lambda function based on a dynamo DB. When I invoke the function through the console it seems like it works fine, giving access forbidden because of course the console is not logged in. But when I call it from a web app I get CORS error. 

I realize this is probably a usage error and not a bug, but I think it's possible there's a bug going on here.

**Comment by elorzafe** [comment]
@danielhep is your api restricted to signed in users, are you configuring Amplify using `aws-exports.js` file?

**Comment by danielhep** [comment]
@elorzafe Thanks for the reply. I did set up Amplify using the instructions provided, using the aws-exports.js file that is provided by AWS Mobile. The API is restricted to signed in users. 

After doing some more research, it looks like this kind of error is likely caused by Amplify not attaching the authentication information to the request, and the 403 response not having correct CORS headers. So I guess the question is now how do I fix Amplify to have it attach proper authentication tokens?

**Comment by s-schrampfer** [comment]
@danielhep Hi, any update on the issue, were you able to fix it?
I'm having the same issue. My browser is throwing CORS errors when using awsmobile's auto-generated CRUD API. The error occurs only when access is restricted to signed-in users as can be configured with awsmobile from the console. Interestingly, after signing into my Angular app i can use the API just fine, but when i refresh the page CORS errors occur and i have to sign out and in again to get it to work.

**Comment by s-schrampfer** [comment]
@danielhep  It appears as though my problem was fixed after upgrading aws-amplify from 1.1.3 to 1.1.9!

**Comment by danielhep** [comment]
Just got this resolved. I was using the AWS Mobile CLI and when I re-set up
my project using Amplify CLI everything worked. Apparently the AWS Mobile
CLI is deprecated!
Daniel Heppner

**Comment by jordanranz** [comment]
Closing as it seems the issue was resolved. Please reopen if you are still experiencing related issues.
