### ISSUE TITLE
Amplify API get request example for listing all items throws an error

### ISSUE THREAD

**Issue by sam-webchef** [aws-amplify/amplify-js#1857]
I followed all the steps in the official doc and when used the code in the [example](https://aws-amplify.github.io/amplify-js/media/api_guide#get) as below replacing the API name and path, it doesn't return the list, instead it throws 404 error. I haven't made any manual changes in the API or related Lambda function.

```
async getData() { 
    let apiName = 'MyApiName';
    let path = '/path';
    let myInit = { // OPTIONAL
        headers: {} // OPTIONAL
    }
    return await API.get(apiName, path, myInit);
}

getData();
```

But, if I pass an id of an existing record with the same request, it returns the object.

Ex.

```
async getData() { 
    let apiName = 'MyApiName';
    let path = '/path/<id>';
    let myInit = { // OPTIONAL
        headers: {} // OPTIONAL
    }
    return await API.get(apiName, path, myInit);
}

getData();
```
Is there a different way of loading all items?

**Comment by elorzafe** [comment]
@sam-webchef did you create the API with CRUD operations on an Amazon DynamoDB table?

**Comment by sam-webchef** [comment]
Hi @elorzafe,

Thanks for your response. Yes, I created the API with CRUD operations.

**Comment by sam-webchef** [comment]
Actually, I found out that it is required to add my own get method to scan the database. Added the following function in the app.js file of the Lambda Function. **IT IS REQUIRED TO ADD THIS FUNCTION ABOVE OTHER `get` FUNCTIONS.**

```
app.get('/<YOUR_PATH>', function (req, res) {
  var params = {
    TableName: tableName,
    Select: 'ALL_ATTRIBUTES',
  };
  dynamodb.scan(params, (err, data) => {
    if (err) {
      res.json({ error: 'Could not load items: ' + err.message });
    }
    res.json({
      data: data.Items.map(item => {
        return item;
      })
    });
  });
```

**Comment by ZalgirisKaunas** [comment]
how does it work, can I use amplify-cli to push this code ? I've updated the file with this code but I still get 404 response

**Comment by tvb** [comment]
> Actually, I found out that it is required to add my own get method to scan the database. Added the following function in the app.js file of the Lambda Function. **IT IS REQUIRED TO ADD THIS FUNCTION ABOVE OTHER `get` FUNCTIONS.**
> 
> ```
> app.get('/<YOUR_PATH>', function (req, res) {
>   var params = {
>     TableName: tableName,
>     Select: 'ALL_ATTRIBUTES',
>   };
>   dynamodb.scan(params, (err, data) => {
>     if (err) {
>       res.json({ error: 'Could not load items: ' + err.message });
>     }
>     res.json({
>       data: data.Items.map(item => {
>         return item;
>       })
>     });
>   });
> ```

You are missing an closing `});` And this is indeed needed! 

Although I don't understand why as the out-of-the-box Lambda function says it has already such function? (which indeed doesn't work as described)

```
/********************************
 * HTTP Get method for list objects *
 ********************************/

app.get(path + hashKeyPath, function(req, res) {
  var condition = {}
  condition[partitionKeyName] = {
    ComparisonOperator: 'EQ'
  }

  if (userIdPresent && req.apiGateway) {
    condition[partitionKeyName]['AttributeValueList'] = [req.apiGateway.event.requestContext.identity.cognitoIdentityId || UNAUTH ];
  } else {
    try {
      condition[partitionKeyName]['AttributeValueList'] = [ convertUrlType(req.params[partitionKeyName], partitionKeyType) ];
    } catch(err) {
      res.json({error: 'Wrong column type ' + err});
    }
  }
```

**Comment by erodrig** [comment]
Any response in the last comment, why closed?

**Comment by mikhael28** [comment]
@sam-webchef this did indeed work for me, thank you. Makes a lot of sense, just need to add another get function to properly scan the dynamo table. 

Have you thought about submitting a pull-request to the amplify team, essentiall adding a 'scan' route to the auto-generated function code?

**Comment by jarrettj** [comment]
@tvb I don't understand either. This explains things, at least you helped me :). Will checkout how to submit a PR.

**Comment by ilyador** [comment]
I have a similar problem. Seems like the DynamoDB scanning already implemented in the template generated by `create API`

```
/********************************
 * HTTP Get method for list objects *
 ********************************/

app.get(path + hashKeyPath, function (req, res) {
  var condition = {}
  condition[partitionKeyName] = {
    ComparisonOperator: 'EQ'
  }

  if (userIdPresent && req.apiGateway) {
    condition[partitionKeyName]['AttributeValueList'] =
      [req.apiGateway.event.requestContext.identity.cognitoIdentityId || UNAUTH]
  } else {
    try {
      condition[partitionKeyName]['AttributeValueList'] =
        [convertUrlType(req.params[partitionKeyName], partitionKeyType)]
    } catch (err) {
      res.statusCode = 500
      res.json({ error: 'Wrong column type ' + err })
    }
  }

  let queryParams = {
    TableName: tableName,
    KeyConditions: condition
  }

  dynamodb.query(queryParams, (err, data) => {
    if (err) {
      res.statusCode = 500
      res.json({ error: 'Could not load items: ' + err })
    } else {
      res.json(data.Items)
    }
  })
})
```

I do `const data = await API.get('picturesapi', '/userpictures')` from the client and get 404.

**Comment by bradgreens** [comment]
> You are missing a closing }); but this is indeed needed!

Emphasis that @sam-webchef's example is missing the closing `});` ❗️ 

I was troubleshooting this in CloudWatch logs and found `Runtime.UserCodeSyntaxError: SyntaxError: Unexpected end of input"` on my recent lambda requests.

For completeness:

I had the same Issue where adding a _REST API_ with Amplify's `amplify add api` command generated the `/amplifiy/backend/function/myApi/src/app.js` file and used the default path of `/items`. Then, `API.get('myApi', '/items', {});` resulted in `Uncaught (in promise) Error: Request failed with status code 404` in the browser Javascript console.

I added the following block of code ABOVE the first `app.get()` function, at approximately line 68 in `/amplify/backend/function/:myApi/src/app.js`:

```
/********************************
 * MANUALLY ADDED
 * HTTP Get method to scan all objects *
 *
 * The generated lambda code from `amplify add api` only created a `get` endpoint
 * to "list" an _individual_ object.
 *
 * This adds the ability to perform a scan which returns an Items array of all objects.
 ********************************/

app.get(path, function (req, res) {
  var params = {
    TableName: tableName,
    Select: 'ALL_ATTRIBUTES',
  };

  dynamodb.scan(params, (err, data) => {
    if (err) {
      res.json({ error: 'Could not load items: ' + err.message });
    }

    res.json({
      data: data.Items.map(item => {
        return item;
      }),
    });
  });
});
```

Then run `amplify push` and observe that your API `Function` is flagged to `Update`. Hit `Y` + `enter` to deploy the new function you just modified.

If that succeeds, the request to `API.get('myTableName', '/items', {});` should now succeed as a `200` response and include data in the following structure:

```
{
  "data": [
    {
      "id": "abc123",
      "name": "test"
    }
  ]
}
```

To confirm this was working end-to-end, I also used the generated API to create one item in the database like so:

```
  // In App.js / App.tsx
  async function createItem(item: any) {
    const params = {
      body: { ...item }
    }
    const response = await API.post('myAPI', '/items', params);
    console.log('-- createItem() response', response);
  }

  createItem({ id: 'abc123', name: 'test' });
```

It would be really nice to see the REST configuration of `amplify add api` generate a `app.get()` method to list all objects (perhaps, with optional pagination?). It's a very common use case.

**Comment by mimeonline** [comment]
Why is the issue is closed. The behavior is still present. I can't get a collection of items without the fix which is described in this thread.

**Comment by ryanhyslop** [comment]
For what its worth, as someone who is trying this out for the first time, I hit this issue and its quite confusing that the description of the method looks like it'll return a collection but it actually is for one item? 

Thanks for the comments above actually helped me figure out what was going on!

**Comment by msurguy** [comment]
+1, having the same exact issue and quite a lot of time was spent figuring out where the problems is located...

**Comment by lucas-dolsan** [comment]
> Actually, I found out that it is required to add my own get method to scan the database. Added the following function in the app.js file of the Lambda Function. **IT IS REQUIRED TO ADD THIS FUNCTION ABOVE OTHER `get` FUNCTIONS.**
> 
> ```
> app.get('/<YOUR_PATH>', function (req, res) {
>   var params = {
>     TableName: tableName,
>     Select: 'ALL_ATTRIBUTES',
>   };
>   dynamodb.scan(params, (err, data) => {
>     if (err) {
>       res.json({ error: 'Could not load items: ' + err.message });
>     }
>     res.json({
>       data: data.Items.map(item => {
>         return item;
>       })
>     });
>   });
> ```

Is this solution still the way to go?

**Comment by bradgreens** [comment]
> Is this solution still the way to go?

Try it? We're not all actively still in the codebase. If it doesn't work I'd suggest opening a new issue as that would imply the solution here is no longer effective.

**Comment by lrivera** [comment]
actually the code 
`/********************************
 * HTTP Get method for list objects *
 ********************************/

app.get(path + hashKeyPath, function (req, res) {
  var condition = {}
  condition[partitionKeyName] = {
    ComparisonOperator: 'EQ'
  }

  if (userIdPresent && req.apiGateway) {
    condition[partitionKeyName]['AttributeValueList'] =
      [req.apiGateway.event.requestContext.identity.cognitoIdentityId || UNAUTH]
  } else {
    try {
      condition[partitionKeyName]['AttributeValueList'] =
        [convertUrlType(req.params[partitionKeyName], partitionKeyType)]
    } catch (err) {
      res.statusCode = 500
      res.json({ error: 'Wrong column type ' + err })
    }
  }

  let queryParams = {
    TableName: tableName,
    KeyConditions: condition
  }

  dynamodb.query(queryParams, (err, data) => {
    if (err) {
      res.statusCode = 500
      res.json({ error: 'Could not load items: ' + err })
    } else {
      res.json(data.Items)
    }
  })
})`
is working but if you see is the path + hashKeyPath
and
`const hashKeyPath = '/:' + partitionKeyName;`

so if you do this
`API.get("rest" , "/items/:");`

will work without adding some extra code

**Comment by gleysonmelo** [comment]
> so if you do this
> 
> `API.get("rest" , "/items/:");`
> 
> will work without adding some extra code

Just as a feedback, it didn't work for me :( I got an error 500 anyway (I looks like it is trying to convert the ":" to a number.

**Comment by kimuhjin** [comment]
I Tried this code:


app.get('/<YOUR_PATH>', function (req, res) {
  var params = {
    TableName: tableName,
    Select: 'ALL_ATTRIBUTES',
  };
  dynamodb.scan(params, (err, data) => {
    if (err) {
      res.json({ error: 'Could not load items: ' + err.message });
    }
    res.json({
      data: data.Items.map(item => {
        return item;
      })
    });
  });
});

but data returned not in ordered.
is there have any solution to solve this problem?

**Comment by shubhamsharma98** [comment]
+1 to @bradgreens suggestions. Works perfectly now after adding that extra code in the Lambda function.

**Comment by Alonski** [comment]
This is still an issue :)
Can we reopen this please?
