### ISSUE TITLE
Unable to customize Builtin Vue Components (no examples / incorrect documentation )

### ISSUE THREAD

**Issue by armedoctopus** [aws-amplify/amplify-js#1861]
** Which Category is your question related to? **
Amplify Builtin Vue Auth Component customizing
** What AWS Services are you utilizing? **
IAM S3 LAMBDA DYNAMODB APPSYNC
** Provide additional details e.g. code snippets **
I am trying to customize the amplify vue sample using https://aws-amplify.github.io/amplify-js/media/vue_guide#signup-fields documentation to remove the phone number requirement from the SignUp builtin amplify Auth component. According to stackoverflow documentation https://stackoverflow.com/questions/52578961/how-to-pass-objects-to-aws-amplify-vue-signup the aws amplify document is incorrect
and I cannot find any real-world examples showing customization of the builtin amplify Vue components in this repo. Having a real-world example showing how to customize the builtin amplify Vue components would be great and prove that the documentation is correct and then I could Use the documented techniques successfully.

**Comment by mlabieniec** [comment]
Have to tried the vue sample? This has been updated to use the new components:
https://github.com/aws-samples/aws-amplify-vue

which part are you finding to be incorrect in the documentation?

**Comment by armedoctopus** [comment]
I am using https://github.com/aws-samples/aws-amplify-vue
The default SignUp Vue component is in /src/router/index.js
From what I understand I need to customize the Auth component inside of that index.js using AmplifyEventBus I was researching how to do this and came across https://stackoverflow.com/questions/52578961/how-to-pass-objects-to-aws-amplify-vue-signup
After reading this I am unsure how to do it since it shows that the documentation is incorrect:
https://aws-amplify.github.io/amplify-js/media/vue_guide#signup
########### this is *supposedly* the correct answer which is not found in the amplify documentation:

> 
sure, maybe the complete solution will help you. you should have <amplify-authenticator v-bind:authOptions="authOptions"></amplify-authenticator> on the template section. Now on the data section you should refers to the authOptions : { signUpConfig: { signUpFields: [{ label: 'Name', key: 'name', required: true, displayOrder: 1, type: 'string' }]}};
> 

#############################

Please help me understand how to do this customization that I would like to achieve which is to remove the phone number field from the SignUp component in the Amplify Vue example.

**Comment by armedoctopus** [comment]
Here is a screenshot of the signUp component with the phone_number computed option object I would like to remove when loading the signUp component. I thought with Vue it is possible to dynamically change option objects of vue components? Otherwise what is the recommended way to change these builtin Vue components for Authorization, or are we forced to use the defaults? However, that wouldn't make any sense if we are forced to use defaults because you guys recently refactored all the auth components into their own builtins from this vue amplify example because we can customize the components at run time? 
<img width="1103" alt="screen shot 2018-10-09 at 7 56 58 pm" src="https://user-images.githubusercontent.com/804010/46710668-bd6cf900-cbfd-11e8-875d-d4a831a7a3c8.png">

**Comment by haverchuck** [comment]
@armedoctopus -  There was indeed a mismatch between the docs and the Authenticator component - thanks for calling this out.  The fixed code should be available on our unstable npm tag shortly.  If you need to get it to work ASAP or don't want to download a new version of aws-amplify-vue, simply replace the props name `authConfig` with `authOptions`.  

Additionally, to answers your question - the Authenticator component is rendered via the Vue router in the sample app, so you need to pass in the signUpFields via the props object in the route:

`{
      path: '/auth',
      name: 'Authenticator',
      component: components.Authenticator,
      props: {
        authConfig: {    <-- replace me with 'authOptions' if you are using older version of package
          signUpConfig: {
            header: 'I am the new header for the Authenticator component!',
            signUpFields: [
              {
                label: 'Address',
                key: 'address',
                type: 'string',
              }
            ]
          }
        }
      }
    }`

**Comment by haverchuck** [comment]
@armedoctopus - The fix has been merged in github and should be on it's way to NPM.  I'm closing this issue but feel free to let us know if there is still a problem.
