### ISSUE TITLE
Requirements to have required attributes displayed by authenticator?

### ISSUE THREAD

**Issue by mattgogerly** [aws-amplify/amplify-js#1871]
So when I run amplify add auth I can specify required attributes. If I specify "name" for example, it doesn't get displayed as an input when registering with the amplify-authenticator Angular component. As a result registration fails as the attribute is missing. 

Is the component supposed to display the required attributes or is that something I need to do myself?

**Comment by powerful23** [comment]
@mattgogerly this is not implemented in yet, will mark as feature request.

**Comment by canivel** [comment]
Just happen to me too... so how we add the extra field to the <amplify-authenticator></amplify-authenticator> ? is there a example?

**Comment by karlmosenbacher** [comment]
This should be implemented for react as well.

**Comment by sammartinez** [comment]
Closing as implemented from the above PR
