### ISSUE TITLE
Cannnot get setupTOTP function to work

### ISSUE THREAD

**Issue by koolkav1** [aws-amplify/amplify-js#1872]
** Which Category is your question related to? **
Auth()

** What AWS Services are you utilizing? **
aws-amplify
aws-amplify-angular

** Provide additional details e.g. code snippets **
https://stackoverflow.com/questions/52720807/cannot-get-setuptotp-in-amplify-js-to-work-associatesoftwaretoken

**Comment by powerful23** [comment]
@koolkav1 hey from you code snippet the `user` object you passed into `setupTOTP` is undefined.

**Comment by koolkav1** [comment]
Okay, thanks. I finally got it to work.
