### ISSUE TITLE
authenticateUser always calls SMS MFA by default

### ISSUE THREAD

**Issue by sivaramit14** [aws-amplify/amplify-js#1875]
How to allow users to choose between SMS MFA and TOTP MFA during signing in and how to setup TOTP MFA for users?
However the user pool is configured as 
MFA - Required
Second Factors - SMS and TOTP enabled

The user pool has confirmed users with phone number and email verified. I tried to execute the use case 27 in the link [link](https://github.com/aws-amplify/amplify-js/tree/master/packages/amazon-cognito-identity-js)
trying to choose the mfa method and authenticate, but authenticateUser call always falls on mfaRequired callback method and doesn't call mfaSetup callback method to associate software token.

However if the userpool has only TOTP MFA option enabled the same script works good. The issue happens when the user pool is configured with both SMS and TOTP MFA's.

When i try to setUserMFAPreference with 
`var params = {
  AccessToken: accessToken, /* required */
  SMSMfaSettings: {
    Enabled: true,
    PreferredMfa: false
  },
  SoftwareTokenMfaSettings: {
    Enabled: true,
    PreferredMfa: true
  }
};`

it returns below as response error message.
> Error: User has not set up software token mfa

getUser method returns the below

> MFAOptions: [{DeliveryMedium: "SMS", AttributeName: "phone_number"}]

> UserMFASettingList: []

is there a way to setup TOTP MFA for a user pool where SMS MFA is also configured and do we have an option to choose between the MFA methos when signing in?
Please let me know.

Thanks in advance.

**Comment by powerful23** [comment]
@sivaramit14 as far as I know currently you can only choose the MFA type after you get signed in. By default when you first sign in, you will always be asked for SMS verification unless you didn't choose SMS in your user pool configuration.

After you get signed in, you can set your preferred mfa type but for TOTP you need to setup before turning it on by using `associateSoftwareToken` method.  You can try using Amplify which has more detailed doc around that: https://aws-amplify.github.io/amplify-js/media/authentication_guide#enabling-totp

**Comment by powerful23** [comment]
Closing the issue due to no further response. Feel free to reopen if you still have this issue.

**Comment by johhansantana** [comment]
Does any of you know how to check if the user already has an `associateSoftwareToken` ? I am unable to find something that gives me this information about the signed-in user

**Comment by ryanwh-dw** [comment]
Regarding "By default when you first sign in, you will always be asked for SMS verification unless you didn't choose SMS in your user pool configuration." Can an override be created for this default via a custom lambda or another approach?
