### ISSUE TITLE
Auth.verifyCurrentUserAttribute - Error: No current user

### ISSUE THREAD

**Issue by rfdc** [aws-amplify/amplify-js#1878]
**Describe the bug**
The process to verifying the attribute like 'email', via Auth.verifyCurrentUserAttribute(attr), is not finding the user and sending the 'the_verification_code' to email. 

I already have successfully implemented every other Authentication feature needed in the app.  

**Code To Reproduce**
Redux Action that connects w/ AWS: 
```import { Auth } from 'aws-amplify';
export function checkAttribute(email) {
  return dispatch => {
    dispatch(confirmUserLoading(true));
    console.log('UserEmail:', email);
    Auth.verifyCurrentUserAttribute(email)
      .then(() => {
        dispatch(confirmUserCodeSentSucessfully());
        console.log('verification code - UserEmail:', email);
        console.log('a verification code is sent');
      })
      .catch(err => {
        dispatch(confirmUserError());
        dispatch(confirmUserErrorMsg(err));
        console.log('error - UserEmail:', email);
        console.log('confirmUser with error', err);
      });
    dispatch(confirmUserLoading(false));
  };
}
```

**Expected behavior**
find user and send the_verification_code to email to continue process

**Screenshots**
![auth verifycurrentuserattribute-issue](https://user-images.githubusercontent.com/32999759/46723406-56594e00-ccaa-11e8-901c-c44f0283bcca.png)

**dependencies :**
```
"dependencies": {
        "aws-amplify": "^1.1.5",
        "aws-amplify-react-native": "^2.0.5",
        "native-base": "^2.7.2",
        "react": "16.4.1",
        "react-native": "0.56.0",
        "react-native-prompt": "^1.0.0",
        "react-native-vector-icons": "^5.0.0",
        "react-navigation": "^2.11.2",
        "react-redux": "^5.0.7",
        "redux": "^4.0.0",
        "redux-thunk": "^2.3.0"
    },
```

**Smartphone :**
 - Device: iPhone6

Let me know if you need further info.
Thanks for looking into it

**Comment by rfdc** [comment]
> 
> 
> @rfdc are you signed in before you call this method?

Hi @powerful23,

Based on the documentation I believe this method is used for account recovery. So I guess the user cannot login into account thus needs this method. Or have restarted the app without entering the verification code, so needs a new code to be sent either to the user's phone number or email address.

Is that right? 

Thanks

**Comment by powerful23** [comment]
@rfdc no the `verifyCurrentUserAttribute` method can only be used when the user is logged, and is to be used to verify the user's email/phone_number. When to reset password, you need to call `Auth.forgotPassword()` to initiate the process and `Auth.forgotPasswordSubmit()` to submit the code you received from phone/email

**Comment by powerful23** [comment]
@rfdc you can use `Auth.resendSignUp(username)` to get the verification code again.

**Comment by rfdc** [comment]
> @rfdc you can use `Auth.resendSignUp(username)` to get the verification code again.

Thanks, I will try

**Comment by powerful23** [comment]
@rfdc do you still have this issue? If not, could you close it?

**Comment by rfdc** [comment]
thanks for helping...closing now

**Comment by ngocketit** [comment]
@powerful23 How could that `Auth.resendSignUp` help if the username is auto generated? Currently, I'm generating username automatically and use email/phone number as alias to sign in. If user signs up with email and not enter the confirmation code right after the click the "Sign Up" button, and later tries to log in with email, he will get `User does not exist`. I'm thinking of a way to get the auto generated username from email (such as a Lambda) and use that instead of email for logging in. In that case, I'll get `UserNotConfirmedException` and I can show the confirmation screen for user to enter the code again. Is there any other better workaround? Thanks!

**Comment by johnvanhulsen** [comment]
Maybe you needs to check `confirmSignUp` for this case.
After registration and for activate the user for the first name, you must not use`verifyCurrentUserAttribute` or `verifyCurrentUserAttributeSubmit`
