### ISSUE TITLE
React Native: "Confirm" AmplifyButton not linked to theme

### ISSUE THREAD

**Issue by kingstonfung** [aws-amplify/amplify-js#1882]
**Describe the bug**
The "Confirm" button inside `ConfirmSignIn.js` and `ConfirmSignUp.js` is missing the `theme` parameter, making the buttons at those screens unstyleable.

**npm package version**
aws-amplify-react-native@2.0.5

**To Reproduce**
Please implement the following snippet to reproduce the issue:
```
// JSX:
<Authenticator hideDefault theme={MyTheme}>
  <SignIn />
  <SignUp />
  <ForgotPassword />
  <ConfirmSignUp />
</Authenticator>

// JS:
const MyTheme = StyleSheet.create({
  button: {
    backgroundColor: '#ff0000',
    alignItems: 'center',
    padding: 16
  },
  buttonDisabled: {
    backgroundColor: '#ff0000',
    opacity: 0.5
  },
});
```

**Expected behavior**
The "Confirm" button styling should respect the theme stylesheet supplied to `<Authenticator />`

**Screenshots**
I wanted to style the UI to green, but button stayed at the AWS orange color:
![screen shot 2018-10-10 at 3 00 15 pm](https://user-images.githubusercontent.com/10535453/46765801-38392100-cc9d-11e8-80c9-d9d7d8c12b4c.png)

**Desktop (please complete the following information):**
 - N/A
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: iPhone 8 Simulator via XCode 10.0 (10A255)
 - OS: 12.0
 - Browser N/A (React Native v0.57.1)
 - Version N/A 

**Additional context**
Similar to [`SignIn.js`](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react-native/src/Auth/SignIn.js#L94) ... the `<AmplifyButton>` element should have a `theme: theme` attribute in [`ConfirmSignUp.js`](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react-native/src/Auth/ConfirmSignUp.js#L93-L96) and [`ConfirmSignIn.js`](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react-native/src/Auth/ConfirmSignUp.js#L93-L96).

**Comment by jordanranz** [comment]
Hey @kingstonfung,

Good find, I have submitted a PR to pass the theme object to these components.

**Comment by jordanranz** [comment]
PR has been merged. Closing this issue now. Please reopen if you run into related issues.

**Comment by kingstonfung** [comment]
thank you @jordanranz !
