### ISSUE TITLE
Cannot unsubscribe for AppSync observable after putting them in vue data attribute

### ISSUE THREAD

**Issue by goatandsheep** [aws-amplify/amplify-js#1883]
**Describe the bug**
I'm getting the following error: `TypeError: this.createObservable.unsubscribe is not a function`

**To Reproduce**

This is a rough run-down of the component:

```javascript

export default {
  data() {
    return {
      createObservable: {}
  },
  beforeDestroy() {
    this.createObservables.unsubscribe();
  },
  mounted() {
    const SubCreateItem = `subscription createJob {
      createJob {
        jobId
      }
    }`;
    const obs = Amplify.API.graphql(
      graphqlOperation(SubCreateItem)
    );
    obs.subscribe({
      next: data => console.log(data),
      error: (data) => {
        obs.unsubscribe();
      },
    });
    this.createObservables = obs;
  }
}

```

As you'll notice, I'm saving the Observable as a property.

**Expected behavior**
The observable to unsubscribe

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Framework: Vue
 - Version [e.g. 22]: 1.0.0

**Comment by goatandsheep** [comment]
This is consistent with multiple frameworks whenever you put the observable into props

**Comment by haverchuck** [comment]
@goatandsheep  - There might be some syntax errors in the code you posted.  It looks like your `data` method is possibly missing a closing brace (maybe just a copy/paste error?), and also you are referencing createObservable vs createObservables (with an 's' at the end).  Just wanted to confirm that this is only an issue with the code sample you pasted.
