### ISSUE TITLE
Light Code Review

### ISSUE THREAD

**Issue by evilmaniac** [aws-amplify/amplify-js#1887]
- Interfaces are not included within modules. This is not in-line with `aws-sdk` where all Types associated with a client can be referenced as follows: `AWS.<ServiceClient>.Types` to avoid importing fragmented type files such as: 
```
import {AuthClass} from '@aws-amplify/auth';
import {AuthOptions} from "@aws-amplify/auth/lib/types";
```
- Analytics events are not associated with an interface and event structure is loosely defined on how Providers consume an event.
- Analytics module is not provider agnostic. Autotracking does not function with `AWSKinesisProvider`.
- `AWSKinesisProvider` errors propagate into run-time as no event interface exists to differentiate required properties such as `streamName` from optional ones during build time
- `AWSPinpointProvider` is [not agnostic of event types](https://github.com/aws-amplify/amplify-js/blob/master/packages/analytics/src/Providers/AWSPinpointProvider.ts#L233-L242)
- Implicit usage of `any` for arguments. 
- [Unnecessary helper functions performing identical tasks with the exception of log messages](https://github.com/aws-amplify/amplify-js/blob/master/packages/analytics/src/Providers/AWSPinpointProvider.ts#L304-L344)
- Utilities are enabled by default such as Analytics. Utilities should ideally be enabled when configuration is written.
- [Useless comments](https://github.com/aws-amplify/amplify-js/blob/master/packages/analytics/src/Providers/AWSPinpointProvider.ts#L304-L307)
- `Auth` documentation fails to mention requirement of not setting an `App Client Secret` for Cognito User Pools

Hopefully this proves to be of some use.

**Comment by powerful23** [comment]
@SauronKitty thanks for you feedback.

**Comment by ericclemmons** [comment]
Amplify with TypeScript support was released earlier this year, addressing most of these issues.

If there are any further improvements, we welcome PRs (which are usually pretty easy to cut in the GitHub editor) 🙏
