### ISSUE TITLE
Please update graphql to 14.0.2

### ISSUE THREAD

**Issue by JustFly1984** [aws-amplify/amplify-js#1891]
I have a project, which renders `React` app to static files on build with` react-static`. It uses webpack 4 and Babel7 to compile source code to static and dynamic pages. Similar to `gatsby.js`
Currently I have an issue with aws-amplify dependency on `graphql@0.13.0`. I have installed graphql@14.0.2 as dependency to my project, but then I run `npm ls graphql` I see this:

```
$ npm ls graphql
/projects/project
└─┬ aws-amplify@1.1.6
  └─┬ @aws-amplify/api@1.0.17
    └── graphql@0.13.0
```

and I do not see my freshly installed 14.0.2. Then I try to run dev environment, I got errors:

```
Attempted import error: 'print' is not exported from 'graphql'.
```

I'm looking at node_modules/graphql/index.js and I see the export of print in index.js file, and the version is 14.0.2 in package.json, but for some reason webpack using aws-amplify's version of graphql.

Please make loose dependency on graphql or make it peer-dependency.

**Comment by wnkz** [comment]
`0.13.0` also has a bug on IE11 https://github.com/graphql/graphql-js/issues/1356

**Comment by pungggi** [comment]
I also had a problem with gatsby. I ended using `"resolutions": {
    "graphql": "0.13.2"
  },` in my package.json with yarn

**Comment by JustFly1984** [comment]
Is there any movement on this issue?

**Comment by JustFly1984** [comment]
Hello, please update graphql dependency - it causes a lot of frustration.
