### ISSUE TITLE
No userPool with aws-amplify

### ISSUE THREAD

**Issue by engharb** [aws-amplify/amplify-js#1892]
I am using aws-amplify 0.3.4. with my Mobile Application. When I try to login I used to get "No userPool"

I followed the configuration as mentioned and it was working perfectly. Suddenly I used to get such error.

My configuration:
* I am using Ionic and Cordova,
* in my app.module 
```
import Amplify from 'aws-amplify';
const aws_exports = require('./aws-exports').default;
Amplify.configure(aws_exports);

```
```
//aws-exports.ts
const awsmobile = {
    'aws_app_analytics': 'enable',
   
    'aws_cognito_region': '***,
    'aws_project_region': '****',
    'aws_facebook_app_id': '',
    'aws_facebook_app_permissions': 'public_profile,email',
    'aws_google_app_permissions': 'email,profile,openid',
    'aws_google_web_app_id': '',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': '***',
    'aws_user_files_s3_bucket_region': '***',
    'aws_project_name': '***',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': '***',
    'aws_user_pools_web_client_id': '****',
    'aws_cognito_user_pool_domain': '***.auth.***.amazoncognito.com',
    'aws_user_pools_arn': '***',
    'aws_user_pools_mfa_type': 'OFF',
};

export default awsmobile;
```

I do not know where is the problem and why I used to get such error?!

Any idea?

regards,

**Comment by mlabieniec** [comment]
Your amplify version is very old so it would be hard to determine what is going on here without a debug log. Usually this error occurs when your amplify core library is not in sync with a component library and the component library ends up using its own instance of amplify core in that case, hence no user pool. Are you using the aws-amplify-angular package as well? Can you try upgrading your amplify core to its latest version?

**Comment by powerful23** [comment]
Closing the issue as no further response. Please feel free to reopen if you still have this issue.
