### ISSUE TITLE
Getting 404 Not Found

### ISSUE THREAD

**Issue by nirmalkumarv** [aws-amplify/amplify-js#1894]
**Describe the bug**
After following the tutorial and deployed the application it says 404 Not Found

404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: index.html
RequestId: 9F9924995AC1F5F9
HostId: GMygtS5R2Q3Mbof/G+q5SYiotbfFF5UeATieQJ0Xab2gZAyul4ekh4qw3vh5gM9wiy+LCX5jV/0=
An Error Occurred While Attempting to Retrieve a Custom Error Document
Code: NoSuchKey
Message: The specified key does not exist.
Key: index.html

**To Reproduce**
- Followed this Tutorial https://aws-amplify.github.io/amplify-js/media/quick_start

**Expected behavior**
- Should show the Index.html page

**Desktop (please complete the following information):**
- Chrome

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by mlabieniec** [comment]
Are you using a framework or plain js. Basically S3 can not find your index.html file so if you run amplify configure project make sure your build script is building your app correctly and then try amplify configure hosting and make sure the dist path is correctly pointing to the built files and your index.html. Note, on angular your dist may need to change to dist/app-name. Just check your dist directory and make sure everything is pointing/configured correctly.

**Comment by kevinyea** [comment]
I was able to repeat the problem as Kumar by creating an https (production) version.
The public bucket was empty at the end of the procedure - hence the 404. I copied index.html and main.bundle.js into the production bucket from the successful dev attempt and the front end ran as https.

**Comment by nirmalkumarv** [comment]
I tried once again all the steps and this time i ran the build process to ensure the dist folder are created. Now i can able to see the hosted files. You can close this ticket.

In the Tutorial, You can add this as a Note that "ensure the dist folder is there or run the build to create the dist folders before publishing to s3"
