### ISSUE TITLE
React Native. Multiple endpoints created on app register.

### ISSUE THREAD

**Issue by BaumDigital** [aws-amplify/amplify-js#1899]
**Describe the bug**
Multiple endpoints created for the first app run. Amplify push notification creates up to 8 endpoints for the same device. Those endpoints have all the same addresses and the same user Id, which are auto generated by amplify.

**To Reproduce**
1. Set up amplify 1.1.6 and @aws-amplify/pushnotification 1.0.15.
2. Configure a project with amplify-cli using a IAM role with administrator access.
3. Add a default auth, default analytics (guest tracking), and notifications for APNS, FCM, EMAIL, SMS.
4. Push amplify project with the amplify-cli and check the pinpoint analytics dashboard to verify the endpoints in 0.
5. Run app (Tested in android emulator and android device)
6. Check pinpoint dashboard and see multiple endpoints available.

**Expected behavior**
For the first app run without signing up or signing in. It should only create one guest endpoint for the current device.

**Screenshots**
![screenshot from 2018-10-12 18-18-42](https://user-images.githubusercontent.com/36079135/46898987-5d6b9200-ce4b-11e8-9a07-f75794f4d6ea.png)

![screenshot from 2018-10-12 17-57-22](https://user-images.githubusercontent.com/36079135/46898692-a5d58080-ce48-11e8-9944-1d6cda39566f.png)

**Smartphone**
 - Device: [Samsung Galaxy J7]
 - OS: [Android 6.0.1]

**Emulator:**
 - Device: [Google Pixel 2]
 - OS: [Android 6.0]

**Comment by powerful23** [comment]
Related to #1121

**Comment by BaumDigital** [comment]
Thanks for the help @powerful23

**Comment by powerful23** [comment]
Closing this issue as this is a duplicated one.
