### ISSUE TITLE
cannot remove Phone Number Field UI in signUp Component using props in router.js

### ISSUE THREAD

**Issue by armedoctopus** [aws-amplify/amplify-js#1901]
** Which Category is your question related to? **
To get a context for this usage question please read https://github.com/aws-amplify/amplify-js/issues/1861

** What AWS Services are you utilizing? **
S3 DynamoDB Cognito Appsync
** Provide additional details e.g. code snippets **
These are the computed signUpFields props that are hardcoded in SignUp.vue:
computed: {
    options() {
      const defaults = {
        header: 'Sign Up',
        signUpFields: [
          {
            label: 'Username',
            key: 'username',
            required: true,
            type: 'string',
            displayOrder: 1,
          },
          {
            label: 'Password',
            key: 'password',
            required: true,
            type: 'password',
            displayOrder: 2,
          },
          {
            label: 'Email',
            key: 'email',
            required: true,
            type: 'string',
            displayOrder: 3
          },
          {
            label: 'Phone Number',
            key: 'phone_number',
            required: true,
            displayOrder: 4
          }
        ]
      }

I would like to remove the key: 'phone_number' but I cannot find any Vue mechanisms that would allow me to do so, and I cannot change the code in SignUp.vue directly because it lives here in amplify-js.
The reason I would like to remove this key is because I would like to remove the Phone Number field from the SignUp UI because I do not use it. I was able to remove the asterisk and requirement from the form by passing required: false in the prop in router.js.
However that does not solve my problem because the UI field is still there and even when passing false to required there is validation on the Phone Number that does not allow the field to remain as blank even when passing requirement false.
That validation cannot be removed because it lives in the template of SignUp.vue so setting values for the props becomes somewhat redundant.
Here is the validation in the template:
``
"""""""""<div v-if="signUpField.key === 'phone_number'" v-bind:class="amplifyUI.selectInput">
          <select v-model="country">
            <option v-for="country in countries" v-bind:key="country.label">{{country.label}}</option>
          </select>
          <input 
            v-bind:class="[amplifyUI.input, signUpField.invalid ? 'invalid': '']" 
            v-model="signUpField.value"
            type="number"
            :placeholder="signUpField.label"
            v-on:change="clear(signUpField)"
          />
        </div>"""""""
``

So then you can see from this that removing the phone_number field from the SignUp.vue component might be the only way to actually remove the Phone Number field.
I have looked around and cannot find any way to do this.
Is there some kind of mechanism that is subtractive in Vue that will allow me to subtract UI elements from SignUp.vue?
Please let me know if there are any options here.

Thanks.

Here is a screenshot of the phone number field showing it is not a requirement but still giving the format error when the field is blank as per setting the required to false:

<img width="520" alt="screen shot 2018-10-14 at 10 53 55 am" src="https://user-images.githubusercontent.com/804010/46920208-a7658c80-cf9f-11e8-8a32-3bd8f81d5f7b.png">

**Comment by haverchuck** [comment]
I believe this is fixed.
