### ISSUE TITLE
Pushnotification JS layer not receiving pinpoint.jsonBody

### ISSUE THREAD

**Issue by schavaLogi** [aws-amplify/amplify-js#1905]
**Describe the bug**
When we send FCM push message from pinpoint with pinpoint.jsonBody it's not giving to JS layer but data received in native layer

**To Reproduce**
1. Update Endpoint from Android device and send push notification with silentPush as false

**Expected behavior**
JS layer must receive all the data which sent from the pinpoint

Logs:
RNPushNotificationMessagingService: sendNotification: Bundle
[
{pinpoint.jsonBody={"id":"1234","code":"notins","src":"test"}, 
userInteraction=false, 
pinpoint.notification.title=Harmony Express (Living Room), 
pinpoint.notification.body=dev pavarotti app is not installed on your test device label,, id=-1575456246, 
pinpoint.campaign.campaign_id=_DIRECT, 
pinpoint.notification.silentPush=0
}
]

JS Layer:
notification', { title: 'Living Room',
body: 'Test body,',
data: 
{ pinpoint: 
  { campaign: 
{ campaign_id: '_DIRECT',
campaign_activity_id: undefined,
treatment_id: undefined },
deeplink: undefined,
url: undefined } },
foreground: true }

**Comment by schavaLogi** [comment]
@powerful23 I added as VERBOSE I see a lot of logs related pinpoint specific(AWSPinpointProvider - Keys and tokens) logs but not Android PushMessage related logs.

Please do let me know is there any other option to get FCM notification parse related logs

**Comment by powerful23** [comment]
@schavaLogi if there is no message returned from native side , you should see a logging info like: `no notification payload received`

**Comment by powerful23** [comment]
Closing the issue due to no further response. Feel free to reopen if you still have this issue.
