### ISSUE TITLE
Error when using Sumerian scene that has Polly text to speech enabled.

### ISSUE THREAD

**Issue by dabit3** [aws-amplify/amplify-js#1908]
**Describe the bug**
When loading a Sumerian scene using Amplify, everything works fine. Once I add a Sumerian Host, I can test it out in the Sumerian dashboard & everything works as expected. When I republish the same scene with the Polly text-to-speech enabled in the Sumerian scene, I get the following error:

`An unhandled error has occured: AWS.Polly is not a constructor TypeError: AWS.Polly is not a constructor`

See screenshot for full error.

**To Reproduce**
1. Create new web project (e.g. React)
2. Add Amplify project with auth service
3. Create Sumerian project
4. Configure Amplify project to add Sumerian scene
5. Add Sumerian Host to Sumerian project with Polly permissions.

**Expected behavior**
No error

**Screenshots**

<img width="1130" alt="screen shot 2018-10-15 at 11 40 10 am" src="https://user-images.githubusercontent.com/1857282/46970822-25449900-d06f-11e8-8a9d-0769fa08bbc4.png">

**Desktop (please complete the following information):**
macOS Sierra 10.12.6

Chrome

1.1.4

**Additional context**
This seems like it could be an issue with the underlying __aws-sdk__.

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by dabit3** [comment]
Update, I'm thinking this may be a bug in Sumerian. Polly is no longer working at all even in the Sumerian dashboard. I'm continuing to look into this but I would hold off investigating this until I figure out what is going on with the service.

**Comment by prestomation** [comment]
Hey Nader.  Sumerian is using the AWS SDK already present on the page that is in your application bundle. Your build is likely treeshaking out all the AWS clients you are not using in your app. Your build does not know that the Sumerian scene needs Polly.

If you import the polly sdk and add a `new AWS.Polly()` in your app.js, this will not be tree shaken out and your scene should work as expected

**Comment by dabit3** [comment]
@prestomation thanks for the info. I'll give this a shot & report back!

**Comment by jordanranz** [comment]
I will add better documentation to clarify this known issue and workaround until we come up with a long term fix.

**Comment by mlabieniec** [comment]
moving this into pivotal

**Comment by Todmy** [comment]
Hi, have the same problem. I'm trying to create vue project. And my scene fails without any adequate error.
![screen shot 2018-12-26 at 7 22 59 pm](https://user-images.githubusercontent.com/7693369/50452688-37329a00-0944-11e9-9b1e-c68eef4bbda5.png)
After debugging I have found the error: "AWS.Polly is not a constructor". So probably it is related to this issue.

**Comment by rentox** [comment]
add this for testing:
<script src="https://sdk.amazonaws.com/js/aws-sdk-2.472.0.min.js">
</script>

<script>// Create an Polly client
const Polly = new AWS.Polly({
    signatureVersion: 'v4',
    region: 'us-east-1'
})</script>`

**Comment by karthikReigns** [comment]
I created a Sumerian host and Cognito identity pool also applied and I give the speech as well as behavior too.....but it was not speaking
