### ISSUE TITLE
Pinpoint - Update OptOut with custom UserId Bug

### ISSUE THREAD

**Issue by pmd30011991** [aws-amplify/amplify-js#1910]
Hi, I'm facing an issue with Pinpoint (React Native)
I'm using Amplify version 1.1.6
This is my update

```
await Analytics.updateEndpoint({
          UserId: userInfo.attributes.sub,
          OptOut: 'NONE'
        });
```

![image](https://user-images.githubusercontent.com/1608649/47007380-aa60a880-d16a-11e8-953f-727d969f5c88.png)

If I take out the OptOut everything back to normal, why I need update OptOut to NONE is that because OptOut by default is 'ALL'.

**Comment by powerful23** [comment]
@pmd30011991 related to #1801. For now `OptOut` is not supported in Analytics module.

**Comment by pmd30011991** [comment]
@powerful23 Thanks, btw I can fix it by adding device token to `Address` field. then everything is fine. however without Device Token I can't update OptOut, so can I say after this feature merged we can just update OptOut without Device Token ?

**Comment by powerful23** [comment]
@pmd30011991 you mean you can't update `OptOut` even your endpoint has been updated with the device token in `Address`?

**Comment by powerful23** [comment]
Closing this issue as now you can update the `optOut` property: https://aws-amplify.github.io/docs/js/analytics#update-endpoint
