### ISSUE TITLE
amplify add hosting - Option to Disable Word-Readable S3 Buckets

### ISSUE THREAD

**Issue by matwerber1** [aws-amplify/amplify-js#1917]
Hi, 

The Amplify's "add hosting" command deploys a public-readable S3 back end. I find the tool kit useful but would prefer that the default bucket's configuration does *not* include public-readable access so that developers start with a "least privilege" security model and only make the bucket public if needed. This reduces the chances of a private S3 hosted site accidentally being made public. 

Perhaps the default should be a website-hosted bucket with no access policy and something like an optional "--access public" could be added to make the bucket world readable.

**Comment by manueliglesias** [comment]
Hi @matwerber1 

Let me know if I am missing something, but couldn't you just not enable hosting until you actually need it/want it?

**Comment by matwerber1** [comment]
Good point - and thinking through use case a bit more... to your point, my suggestion seems counter-intuitive to the whole point of the CLI "add hosting" command. Closing this issue, thank you for your time.
