### ISSUE TITLE
Multiple file uploads <amplify-photo-picker>

### ISSUE THREAD

**Issue by edxxgardo** [aws-amplify/amplify-js#1921]
Hello,
I'm trying the awesome amplify Vue components. Even though for a simple upload <amplify-photo-picker> works well, I'm wondering whether there is a possibility to select many files at the same time using the same component. Thanks for any feedback.

**Comment by haverchuck** [comment]
@edxxgardo This is not currently supported but I am marking it as a feature request, as it is a good idea!

**Comment by ericclemmons** [comment]
Closing as we've since released https://docs.amplify.aws/ui/q/framework/vue via #6104.

If you'd still like to see this feature, please open a discussion here: https://github.com/aws-amplify/amplify-js/discussions
