### ISSUE TITLE
Auth.currentAuthenticatedUser() should return cognito:groups attribute

### ISSUE THREAD

**Issue by epicfaace** [aws-amplify/amplify-js#1923]
**Is your feature request related to a problem? Please describe.**
I have to parse the JWT token myself to actually see the groups the user is in.

**Describe the solution you'd like**
It's be nice if `Auth.currentAuthenticatedUser()` returns the `cognito:groups` attribute.

**Comment by sammartinez** [comment]
Resolving as per the above comment
