### ISSUE TITLE
ConfirmSignUp: Code cannot be empty

### ISSUE THREAD

**Issue by k3j123** [aws-amplify/amplify-js#1924]
** Which Category is your question related to? **
Usage
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **

```javascript
export const ConfirmCodeForSignUp = data => {
    console.log('Data confirm code', data)
    let { username, code } = data
    if (username.search(/[@]]/g) === -1 )  throw new Error("Must provide a valid email")

    return Auth.confirmSignUp(username, code, {})
}
```

running the code above to confirm a user and the verification code that is sent to them returns error:
"Code cannot be empty" 

Even though I supply the email/username and code sent to the email. I can confirm that the data is being passed with the console log. So I am not sure why I am receiving this error. Any help would be grateful.

**Comment by powerful23** [comment]
Closing the issue as no further response. Feel free to reopen if you still have this issue.

**Comment by madrus** [comment]
I have the same issue. Here is my [codesandbox.io](https://codesandbox.io/s/n318z2pq74) pen. You can see the console messages in DevTools in the image below.
I had to obviously delete my Amplify / Cognito authorisation, so you will need to provide your own versions for the following:
- `amplify` folder
- `aws-config.js`
![code-cannot-be-empty](https://user-images.githubusercontent.com/7058116/52517123-61ab8e80-2c36-11e9-98d7-a75f04db1a30.jpg)
 file

**Comment by springcoil** [comment]
I'm seeing a very similar issue too, has anyone resolved this.

**Comment by irmanherdiana** [comment]
Yes I'm having the same issue here
