### ISSUE TITLE
How do I get Subscribe working properly with Amplify in Angular

### ISSUE THREAD

**Issue by kangks** [aws-amplify/amplify-js#1927]
** Which Category is your question related to? **
Subscribe to AppSync using Amplify API in Angular 6

** What AWS Services are you utilizing? **
AppSync, aws-amplify-angular@2.0.10

** Provide additional details e.g. code snippets **
I am following the example of subscription in https://aws-amplify.github.io/amplify-js/media/api_guide#subscriptions, but encountered error subscribing to the API.graphql() 

```
import Amplify, { API, graphqlOperation } from "aws-amplify";
@Injectable()
export class UserService {
   constructor() {
    API.graphql(graphqlOperation(onCreateUser)).subscribe({
       next: (eventData) => console.log(eventData)
    });
  }
```

Error:
``` 
[ts]
Property 'subscribe' does not exist on type 'Promise<GraphQLResult> | Observable<object>'.
Property 'subscribe' does not exist on type 'Promise<GraphQLResult>'.
``` 
 
I encountered error casting to Observable<object> as well.

I noticed the multiple return types from graphql in `API.d.ts`
 
``` 
graphql({ query, variables }: GraphQLOptions): Promise<GraphQLResult> | Observable<object>;
```

Question: how do I overcome the error of using amplify-angular for subscription?

Thanks!
Richard

**Comment by kangks** [comment]
Apparently it was due to name conflict, over Observable from rxjs and zen-observable, renaming one of them fix the issue:

```
import { Observable as rxObservable, of } from "rxjs";
import * as Observable from "zen-observable";
import Amplify, { API, graphqlOperation } from "aws-amplify";
@Injectable()
export class UserService {
   constructor() {
    API.graphql(graphqlOperation(onCreateUser)).subscribe({
       next: (eventData) => console.log(eventData)
    });
  }
  /** GET users from the server */
  getUsers(): rxObservable<User[]> {
[...]
```

**Comment by agabardo** [comment]
I am running with the same problem here for 2 days and cannot fix it.

Property 'subscribe' does not exist on type 'Promise<GraphQLResult> | Observable<object>'.

If I log the variable with console.log I can see a Promise there

Observable {_subscriber: ƒ}
_subscriber: ƒ (observer)
__proto__: Object

Anyone could come to a solution?

**Comment by myrcutio** [comment]
This one worked perfectly for me: https://stackoverflow.com/questions/39319279/convert-promise-to-observable

`import { from } from 'rxjs';
const observable = from(promise);`

**Comment by mihallabrin** [comment]
Add // @ts-ignore
It's Typescript causing the issue as it does actually work right out of the box.
