### ISSUE TITLE
React Native Login with Amazon

### ISSUE THREAD

**Issue by fkguygu** [aws-amplify/amplify-js#1929]
Any solution on how to perform a Login with Amazon using Amplify for React Native?
I tried to find some examples using the Auth.federatedSignIn() function but couldn't find any.

**Comment by powerful23** [comment]
@fkguygu you need to perform the Login with Amazon by your own. What Amplify could help is to use the token you get from the Amazon Login to get you a credentials from Cognito Identity Pool by using `Auth.federatedSignIn()`

**Comment by fkguygu** [comment]
Hey, Thanks for the reply - I understood that, but I couldn't find any documentation to perform that with React Native and Expo. Any suggestions?

**Comment by powerful23** [comment]
@fkguygu hey, sorry for the late response. If you are still having this issue please check the doc: https://aws-amplify.github.io/docs/js/authentication#federated-sign-in

I am going to close this issue now. Feel free to reopen if you still have this issue.
