### ISSUE TITLE
I have exactly 6 400 requests to https://pinpoint.us-east-1.amazonaws.com/v1/apps

### ISSUE THREAD

**Issue by JustFly1984** [aws-amplify/amplify-js#1930]
I do not know how to fix it. 

full link: https://pinpoint.us-east-1.amazonaws.com/v1/apps/41cb864403584ffa8d7c2225060ee4fc/endpoints/d2479cb0-d2cc-11e8-a990-21493bfb5f09 

<img width="1004" alt="screenshot 2018-10-18 07 13 23" src="https://user-images.githubusercontent.com/2255993/47153467-56a6aa00-d2a5-11e8-93cb-a9a1dc03ea60.png">

and response is: {"Message":"Exceeded maximum endpoint per user count 10"}

Please advise

**Comment by manueliglesias** [comment]
Hi @JustFly1984 

Could you share here how you are configuring Amplify?

**Comment by JustFly1984** [comment]
Sure thing!

In index.js before rendering React, I do `Amplify.configure(awsmobile)` passing correct `awsmobile` according to environment. In this case it is development environment and hostname is `https://localhost:3000`

Also I'm using Amplify.Auth in React components and nothing else. I was planing to use GraphQL, but currently I'm stuck with https://github.com/aws-amplify/amplify-cli/issues/185 so until it is resolved, I'm not planing to invest much time to amplify. How can I stop this 6 requests from happening?

**Comment by mlabieniec** [comment]
@JustFly1984 do you have analytics enabled in your application? If so do you have your iam policies setup via the cli or manually? Seems like this may be related to session tracking events , which you can turn off: 
https://aws-amplify.github.io/docs/js/analytics#manual-setup

Also this error will generally occur if an endpoint id can not be cached and reused for some reason I.e. local storage not supported etc. what browser are you on?

@powerful23 what do you think?

**Comment by powerful23** [comment]
This issue is related to #1378

**Comment by powerful23** [comment]
Closing this issue as it's duplicated to 1378.
