### ISSUE TITLE
How to merge user identities 

### ISSUE THREAD

**Issue by mohanrao** [aws-amplify/amplify-js#1931]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Pinpoint, Cognito user pool, Coginto Identity Pool

** Provide additional details e.g. code snippets **
Hi,

I am trying to find the sample code on the client side (ours is a web app) and on the server side how to achieve merge identities like fb, google with matching email. 

I found adminLinkProviderForUser can be used. But seems it has issues (as per support forum)

https://forums.aws.amazon.com/thread.jspa?threadID=267154&tstart=0

**Comment by sammartinez** [comment]
Closing this issue as powerful23 PR above. Please feel free to reopen if needed
