### ISSUE TITLE
awsmobile vs awsconfig in the aws-exports.js file?

### ISSUE THREAD

**Issue by kylekirkby** [aws-amplify/amplify-js#1937]
** Which Category is your question related to? **
aws-amplify

** What AWS Services are you utilizing? **
aws-amplify

** Provide additional details e.g. code snippets **

When the generated aws-exports.js file is added to my project it contains the awsmobile constant but the docs state it should be awsconfig. Why is this?

const awsmobile =  {
vs 
const awsconfig = {

**Comment by et304383** [comment]
I came here from Google looking for an answer to this as well.  The tutorials attempt to load "awsconfig" from aws-exports.
