### ISSUE TITLE
Can't resolve '@aws-amplify/analytics'

### ISSUE THREAD

**Issue by karlmosenbacher** [aws-amplify/amplify-js#1938]
**Describe the bug**
Trying to run npm run start with the (at the moment) latest stable versions of aws-amplify and aws-amplify-react and get this error message:

***
Failed to compile.
./node_modules/aws-amplify-react/dist/Analytics/trackUpdate.js

Module not found: Can't resolve '@aws-amplify/analytics' in ' ... node_modules/aws-amplify-react/dist/Analytics'
***

**To Reproduce**
1. Get the latest stable versions of aws-amplify and aws-amplify-react. I am using:
aws-amplify: 1.1.7,
aws-amplify-react: 2.1.1

2. npm run start in terminal

**Expected behavior**
The application to run and build without errors

**Desktop (please complete the following information):**
 - OS: [Mac OS High Sierra version 10.13.6]
 - Browser [chrome]

**Additional context**
Application created with react-scripts-ts version 2.16.0.
Works with
aws-amplify: 1.1.4
aws-amplify-react: 2.1.1

**Comment by manueliglesias** [comment]
Hi @karlmosenbacher 

Can you share a little bit more code? (e.g. how are you configuring Amplify).

I am having trouble reproducing the issue, this is what I am doing and I can see analytics events being logged:

```bash
npx create-react-app my-app --scripts-version=react-scripts-ts@2.16.0
cd my-app
npm i aws-amplify@1.1.7 aws-amplify-react@2.1.1
npm run start
```

App.tsx:
```typescript
import Amplify, { Analytics } from "aws-amplify";
import aws_exports from "./aws-exports";
Amplify.configure(aws_exports);

Analytics.record({ name: 'anEvent' });
```

**Comment by karlmosenbacher** [comment]
@manueliglesias thanks for the answer, but the thing is that I don't even use analytics in my application at all. 

Below is how I configure amplify
```
Amplify.configure({
  Auth: {
    region: appRegion,
    userPoolId: appUserPoolId,
    userPoolWebClientId: appClientId,
  }
});
```
and thats it. The only module I am using is the Auth module from the aws-amplify library and the authenticator component from aws-amplify-react.

**Comment by dani-media** [comment]
Same issue, I reinstalled with these versions as suggested by @manueliglesias 

npm i aws-amplify@1.1.7 aws-amplify-react@2.1.1

**Comment by karlmosenbacher** [comment]
@dani-media Im glad Im not the only one with this issue, and I was still investigating if I have done something wrong. 
@manueliglesias Did you manage to re-produce the issue?

**Comment by karlmosenbacher** [comment]
@dani-media Solved it by creating a new project with react-script-ts and copied over the source-folder. I dont really know what the underlying problem was...

**Comment by jeffsee55** [comment]
For what it's worth I had this exact same error and realized `aws-amplify` wasn't in my `package.json`. I think I just assumed it would be due to the `amplify init` call I'd made from the CLI.

**Comment by davidsowerby** [comment]
You may have missed:
```
yarn add aws-amplify
```
(or the npm equivalent)

It's in the docs, but easy to miss

**Comment by ricxsar** [comment]
Hi. I'm also experiencing the same issue. I'm following this [tutorial](https://github.com/richardzcode/Journal-AWS-Amplify-Tutorial/blob/master/step-03) which is work as expected. However, thanks to the introduction of modular approach, I was able to reduced of the bundled size. I only need `@aws-amplify/core` and `@aws-amplify/auth` for the `aws-amplify-react` but  it still needs `@aws-amplify/analytics`.

Why is it still needed? Do `aws-amplify-react` needs it for something else?

**Comment by ricxsar** [comment]
@darthmayhem How `Upgrade your AWS-SDK` solve the issue? This is somewhat related to `aws-amplify-react` only which explicitly require us to include `@aws-amplify/analytics` which we don't want to. That's why I'm asking

> Why is it still needed? Does aws-amplify-react needs it for something else?

If someone can answer the above question, then I will be happy to include it to my build.

**Comment by jgiunta1** [comment]
This issue appeared after I updated my mac OS. This also broke git. Solution here: https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-update-xcrun-error-invalid-active-developer-pa

**Comment by marlonmarcello** [comment]
I have the same question as @ricxsar 
Just bumped into this issue and updating the SDK didn't solve it.
