### ISSUE TITLE
Not able to update channel type in aws pinpoint

### ISSUE THREAD

**Issue by noellaby** [aws-amplify/amplify-js#1943]
Hello,
I have just started to use the AWS pinpoint, and I was trying to update the channelType in with the updatePinpoint call, but it is not using the provided value in the code, and setting it to by default to APNS,

The same issue is happening with the location and some other fields.

`Analytics.updateEndpoint({
    Address: user.email,
    Attributes: {
      userProfile: [user.companyId]
    },
    ChannelType: 'GCM',
    UserId: user.pid,
    UserAttributes: {
      role: userRoles
    },
  });`

link debud console (channelType undefined) => https://www.noelshack.com/2018-42-7-1540077851-pin.png

thanks

**Comment by noellaby** [comment]
@powerful23 help me pls?

**Comment by powerful23** [comment]
@noellaby for now it's not available, Related to #1801

**Comment by powerful23** [comment]
Closing this issue as #1801 has been merged.
