### ISSUE TITLE
login failed

### ISSUE THREAD

**Issue by shengliZh** [aws-amplify/amplify-js#1951]
Login failed:
null is not an object(evaluating 'info.username')

![image](https://user-images.githubusercontent.com/25652977/47287770-f8bbee80-d625-11e8-81ec-80f6dd8b884b.png)

**Comment by nidsharm** [comment]
Hi @shengliZh , could you please tell us if you are using the Cognito SDK or Amplify , and which API to make the call ?

**Comment by shengliZh** [comment]
Yes, I'm use aws-amplify, and I have call the API   Auth.signIn(username,password);

**Comment by nidsharm** [comment]
I'm assuming that you are passing info.username to the SignIn API as the username. Could you try printing it out in console.log before passing it to SignIn ?

**Comment by shengliZh** [comment]
Yes, you are right. I have console.log it before signIn, the value is right, but call the api will failure.

![image](https://user-images.githubusercontent.com/25652977/47414077-b0760b00-d7a2-11e8-8132-90799fcca484.png)

**Comment by shengliZh** [comment]
I have find the reason, because I have call this api:
const info = await Auth.currentUserInfo();  after signIn success, but I don't know why?
