### ISSUE TITLE
Amplify stop session event is not received in pinpoint

### ISSUE THREAD

**Issue by PrasannaLearnyst** [aws-amplify/amplify-js#1954]
Configuration
===========
```


Amplify.configure({
  Auth: {
    identityPoolId: COGNITO_IDENTITY_POOL_ID,
    mandatorySignIn: false,
    region: REGION,
  },
  refreshHandlers: {
    'developer': async () => {
      await refreshToken();
    }
  },
  AWSPinpoint: {
    appId: MOBILE_ANALYTICS_APP_ID,
    region: REGION,
    mandatorySignIn: false,
    autoSessionRecord: true
  }
});


const federatedAuth = async ({ identity_id, token }, user) => {
  let federatedCreden = await Auth.federatedSignIn(
    'developer',
    {
      token,
      identity_id,
      expires_at: COGNITO_TOKEN_EXPIRY_TIME
    },
    user
    ).catch(err =>{
      console.log('federated sign in : ', err);
    });

    let { name, id, school_id, email } = user;

    await Analytics.updateEndpoint({
      UserId: id+''
    });
}
```

=============

**Describe the bug**
1. The _session_start events are automatically pushed to pinpoint but unable to receive the _session_stop, do it need to send manually

2. AWS auth credentials are not getting updated on init

Error stack

`[DEBUG] 05:39.335 AuthClass - failed to get or parse item aws-amplify-federatedInfo: SyntaxError: Unexpected token u in JSON at position 0 at JSON.parse (<anonymous>) at AuthClass.currentUserCredentials (blob:http://localhost:8081/...) at Credentials._keepAlive (blob:http://localhost:8081/...) at Credentials._pickupCredentials (blob:http://localhost:8081/...:86) at Credentials.get (blob:http://localhost:8081/...25) at AWSPinpointProvider._getCredentials (blob:http://localhost:8081/...:39) at AWSPinpointProvider.<anonymous> (blob:http://localhost:8081/...:151681:45) at step (blob:http://localhost:8081/...:151483:31) at Object.next (blob:http://localhost:8081/...:151413:24) at blob:http://localhost:8081/...:151385:75`

```
**Expected behavior**
1. The _session_stop is expected to receive automatically on app killed or closed.
2. The credentials are expected to update automatically when app is init
3. How can i restore the UserID on app restart / continue in next app open / next session
```

**Smartphone (please complete the following information):**
 - Device: Vivo v9
 - OS: Android 8
 - React native

**Comment by powerful23** [comment]
@PrasannaLearnyst 
1. Could you check if you have this message when the app is switched to background: https://github.com/aws-amplify/amplify-js/blob/master/packages/analytics/src/trackers/SessionTracker-rn.ts#L73

2. The credentials do get updated when the request is sent. The debug info you pasted is not an error message.

3. Why do you want to restore the UserId? Are you using your own? By default Amplify would use the identityId from the aws credentials as the UserId.

**Comment by PrasannaLearnyst** [comment]
@powerful23 
thanks for the reply

1. Could you check if you have this message when the app is switched to background
No i'm unable to get "App has come to inactive/background, recording stop session"

2. The credentials do get updated when the request is sent. The debug info you pasted is not an error message.
Yes, its not a error, i have checked [Auth.ts](https://github.com/aws-amplify/amplify-js/blob/94b6116d80911be862f9605b85aaef34616dd217/packages/auth/src/Auth.ts#L1012). Its taking from storage, as per the docs the storage will be using asyncstorage in react native.

After federated developer auth is success, the next app opens has to take the credentials from aws-amplify-federatedInfo its not taking from there.

please correct me if i'm wrong.

3. Why do you want to restore the UserId? Are you using your own? By default Amplify would use the identityId from the aws credentials as the UserId.

I need to send user related data to the pinpoint where it pushes to kinesis -> s3.
Is there option to set global attributes where those attributes will be send with all events to pinpoint.

====

**Comment by powerful23** [comment]
@PrasannaLearnyst I am not understanding how you are initing. The desired way is first configuring Amplify(by the way the configuration is not correct):
```js
Amplify.configure({
    Auth: {
        identityPoolId: COGNITO_IDENTITY_POOL_ID,
        mandatorySignIn: false,
        region: REGION,
        refreshHandlers: {
        }
    },
    Analytics: {
         AWSPinpoint: {
              appId: MOBILE_ANALYTICS_APP_ID,
              region: REGION,
              autoSessionRecord: true
         }
     }
});
```

The library will automatically get a credentials(guest or authenticated based on whether you are signed in or not) before sending the start session event.

**Comment by PrasannaLearnyst** [comment]
@powerful23 

can you please guide me which part of the init is incorrect

**Comment by PrasannaLearnyst** [comment]
@powerful23 

In this file [Auth.ts#L1012](https://github.com/aws-amplify/amplify-js/blob/master/packages/auth/src/Auth.ts#L1012)

you are getting the user details but its not stored in this key, rather its stored in key 

```
aws-amplify-cachefederatedInfo
or 
@MemoryStorage:aws-amplify-federatedInfo
```

can you please cross check once

**Comment by PrasannaLearnyst** [comment]
@powerful23 
Sorry,

just checked code of Auth.ts, its getting data from reactnative.ts StorageHelper class.

The StorageHelper.getItem it will be taken from datastorage, for the datastorage the source is sync method of StorageHelper.

the sync is not called, how to make the data sync.

thanks

**Comment by PrasannaLearnyst** [comment]
@powerful23 can you please provide me any guidance on this i'm importing all the classes from 

```
import Amplify, { Auth, Analytics } from 'aws-amplify';
```
for react native do i need to import from any other package. 

I have changed my config as you said

```
Amplify.configure({
    Auth: {
        identityPoolId: COGNITO_IDENTITY_POOL_ID,
        mandatorySignIn: false,
        region: REGION,
        refreshHandlers: {
        }
    },
    Analytics: {
         AWSPinpoint: {
              appId: MOBILE_ANALYTICS_APP_ID,
              region: REGION,
              autoSessionRecord: true
         }
     }
});

```

i've checked in cache the details persist, kindly help me in restore of credentials on app restart

**Comment by powerful23** [comment]
@PrasannaLearnyst yes, the way you import is correct. We will test if stop session events are sent as expected.

**Comment by PrasannaLearnyst** [comment]
@powerful23 no, the stop session events are not sent as exprected

**Comment by PrasannaLearnyst** [comment]
@powerful23 

any update?

**Comment by powerful23** [comment]
@PrasannaLearnyst confirmed. Will mark this as bug.

**Comment by PrasannaLearnyst** [comment]
@powerful23 
thanks

can you please review [this pull request](https://github.com/aws-amplify/amplify-js/pull/1987) or whats the process of getting it reviewed.

https://github.com/aws-amplify/amplify-js/pull/1987
