### ISSUE TITLE
Allow to put secure cookies into CookieStorage

### ISSUE THREAD

**Issue by goatandsheep** [aws-amplify/amplify-js#1961]
**Is your feature request related to a problem? Please describe.**
I'm trying to use secure cookies for an HLS video player pulling private content from CloudFront. My current understanding is that CookieStorage only allows for one cookie.

**Describe the solution you'd like**
I'm content with the auth token my users get from my Federated Identity Pool, but I'd need to store a second one if I wanted to send both cookies when I try to fetch from the protected CloudFront portal. Can CookieStorage be made to hold multiple cookies, i.e. an Array?

**Describe alternatives you've considered**
I could use another cookie storage package, but that defeats the whole purpose of using Amplify Cookie Storage and makes it inconsistent.

**Additional context**
I'm generating the secure cookie from a lambda and will send it to the app through `Amplify.API`

**Comment by ericclemmons** [comment]
You can provide a custom storage adapter via https://docs.amplify.aws/lib/auth/manageusers/q/platform/js#managing-security-tokens that stores multiple cookies however you see fit.

Amplify's default is still `localStorage`, but we understand that cookie usage is often app-specific, such as cases like this.
