### ISSUE TITLE
Device not getting remembered after login from Cognito Hosted UI 

### ISSUE THREAD

**Issue by noorahmed94** [aws-amplify/amplify-js#1962]
** Which Category is your question related to? **
My question is related to AWS Auth (Federation of Cognito User Pools). 

** What AWS Services are you utilizing? **
I am using Amazon Hosted UI for social signin using React JS.

** Provide additional details e.g. code snippets **
I am using AWS Amplify's Hosted UI Feature for supporting Social Signin (Facebook and Google). The problem I am facing is that after the user get's authenticated and callback is received in my redirect URL, the user's device isn't getting registered on Cognito.

I have set Device Tracking "Always" for my user pool and my social user is being registered in Userpool too.

```
constructor(props) {
        super(props);
        this.state = {
            showErrorAlert: false,
            alertMessage: "",
        }
        Hub.listen('auth', this);
    }

    onHubCapsule(capsule) {
        const { channel, payload, source } = capsule;
        if (channel === 'auth' && (payload.event === 'configured' || payload.event === 'signIn')) {
            Auth.currentAuthenticatedUser()
                .then(() => {
                    this.initialze();
                }).catch(() => { });
        } else if (channel === 'auth' && (payload.event === 'configured' || payload.event === 'signOut')) {
            this.onLogoutUser();
        }
    }

    initialze = () => {
           // redirect to authenticated page
    }
```

**Comment by emailismail** [comment]
@powerful23 

Any idea when this can be accomplished?

Do we have any other alternative to achieve this..i.e get the devices tracked in cognito hosted UI.

And also any reference urls or documents to host the cognito ourselves and get all the required functionalities?

Thanks !
Ismail

**Comment by angeld287** [comment]
I have the same problem, please help!

**Comment by ztnark** [comment]
Having this same issue. Wonder if anyone here ever found an answer/solution?

**Comment by rcosgrave** [comment]
Same issue here
