### ISSUE TITLE
Getting error when implement to nextJs

### ISSUE THREAD

**Issue by louiskhenghao** [aws-amplify/amplify-js#1963]
**Describe the bug**

I've implemented aws-amplify to nextjs and it work just fine until i import aws-amplify-react, there is an error when i tried to load up the site and the error i getting was:
```
/Users/helloworld/dashboard/node_modules/@aws-amplify/ui/dist/style.css:1
(function (exports, require, module, __filename, __dirname) { :root {
                                                              ^

SyntaxError: Unexpected token :
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/helloworld/dashboard/node_modules/aws-amplify-react/dist/Amplify-UI/Amplify-UI-Components-React.js:16:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)

``` 
I was trying to fix the issue and unfortunately i have no luck. But i find out that If i goes to the files below and uncomment certain part of the code, the site will be loaded without any error but the styling is not reflected
1.  `/node_modules/aws-amplify-react/dist/Amplify-UI/Amplify-UI-Components-React.js` and uncomment `require('@aws-amplify/ui/dist/style.css');` 
2. `/node_modules/@aws-amplify/ui/dist/style.css` and uncomment/remove all the code inside.

**To Reproduce**
1. Import `aws-amplify-react` to nextjs project
2. Start nextjs dev server (it should compiled without error)
3. Go to localhost:3000
4. The error shown in terminal

**Expected behavior**
The site should render with nicely styling and running without error 

**Screenshots**
<img width="940" alt="screenshot 2018-10-23 at 5 41 04 pm" src="https://user-images.githubusercontent.com/5268771/47351793-51a18a80-d6eb-11e8-8dad-057c0d8f4086.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave @ version 10.14
 - Browser Google Chrome
 - Version 69.0.3497.100

**Additional context**
the environment is under the version listed below:
- next: ^7.0.2
- @zeit/next-css:  ^1.0.1,
- @zeit/next-sass:  ^1.0.1
- aws-amplify: ^1.1.7
- aws-amplify-react: ^2.1.1
- aws-appsync: ^1.4.0
- aws-appsync-react": ^1.2.0

**Comment by jordanranz** [comment]
Hi @louiskhenghao,

This seems related to: #2230. I am currently looking into how to fix this. I will send an update to this issue as soon as possible.

**Comment by cgarvis** [comment]
I found a workaround here: https://github.com/zeit/next-plugins/issues/267#issuecomment-436454048

**Comment by ajhool** [comment]
Can confirm that when using the workaround, this issue does not occur
