### ISSUE TITLE
SignOut component is not automatically redirect to SignIn

### ISSUE THREAD

**Issue by ahmetcetin** [aws-amplify/amplify-js#1965]
**Describe the bug**
When you use SignOut component in a page, it doesn't automatically show SignIn component. I use customized auth components (including SignIn) passed to withAuthenticator.

**To Reproduce**
Just use SignOut component anywhere on the page. When you click it signouts the user but user still sees the page which shouldn't be visible to unauthenticated users.

**Expected behavior**
After sign out, it should show sign in page. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 69

**Additional context**
When you refresh the browser, it shows the Sign In page, but it should automatically show it instead of waiting browser refresh. I extended existing SignOut component to use `<a>` tag with href and onClick events together in render method instead of NavButton to refresh the page, but obviously it's not the proper solution.

**Comment by karlmosenbacher** [comment]
perhaps:
https://github.com/aws-amplify/amplify-js/issues/1269

**Comment by ahmetcetin** [comment]
indeed, thx!
