### ISSUE TITLE
onSubscriptionMsg usage in the React Connect component

### ISSUE THREAD

**Issue by amymc** [aws-amplify/amplify-js#1968]
Hi,
I'm using the `Connect` component in the `aws-amplify-react` library.

My component executes a query and subscribes to an update action in the underlying dynamo table. I would like to receive the updated record in the table when the update action has been triggered. 

This is how my component looks currently 
```
     <Connect
          query={graphqlOperation(GetBot, {
            id: this.props.match.params.botId
          })}
          subscription={graphqlOperation(onUpdateBot, {
            id: this.props.match.params.botId
          })}
          onSubscriptionMsg={async () => {
            const result = await API.graphql(
              graphqlOperation(GetBot, { id: this.props.match.params.botId })
            );
            return result.data;
          }}
        >
           {({ data: { getBot } }) => {
               // render the component with the data received
            }}
      </Connect>
```

This works but I have a feeling calling the `GetBot` query again in `onSubscriptionMsg`  isn't the approach I should be taking. 

In addition, in order for that to work I've had to modify the `Connect` component in the `aws-amplify-react` library.

I have replaced [these lines](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/API/GraphQL/Connect.js#L79-L81)  with the following: 
```
   next: async ({ value: { data } }) => {
            const { data: prevData } = this.state;
            const newData = await onSubscriptionMsg(prevData, data);
```

Any guidance on how best to approach this would be appreciated. 

Thanks,
Amy

**Comment by elorzafe** [comment]
Hi Amy, onSubscriptionMsg callback receives two params. The first is the previous data (the one you got from the query), and the second is the data coming from the subscription. You can do something like this. 

```jsx
<Connect
          query={graphqlOperation(GetBot, {
            id: this.props.match.params.botId
          })}
          subscription={graphqlOperation(onUpdateBot, {
            id: this.props.match.params.botId
          })}
          onSubscriptionMsg={(prev, {onUpdatedBot}) => {
            prev.getBot = onUpdatedBot;
            return prev;
          }}
        >
           {({ data: { getBot } }) => {
               // render the component with the data received
            }}
      </Connect>
```

**Comment by amymc** [comment]
Hi @elorzafe,

I had tried that originally but `onUpdateBot` never contained all the fields I needed.

After reading the following in the docs I realised the problem was with my `updateBot` mutation
```
 the selection set that is received by subscribers is specified by the client triggering the mutation.
```

Thanks,
Amy
