### ISSUE TITLE
Change Auth.Login Cognito Identity Pool Url

### ISSUE THREAD

**Issue by weasnerb** [aws-amplify/amplify-js#1970]
** Which Category is your question related to? **
Authentication

** What AWS Services are you utilizing? **
Cognito User and Identity Pools

** Provide additional details e.g. code snippets **
I am wondering if there is a way for me to change the URL that the Auth.signIn function calls to login to my Amplify App. I am using LastPass, which is throwing an error saying that my form is insecure, and I believe that it is due to Auth.signIn making a post request to a different domain than the one that the frontend was served from?
If that is the case I would love it if I could use auth.example.com as the URL endpoint for the Auth.signIn function.
I have already set auth.example.com to my preferred domain under app integration in my user pool, however I believe that that is only used for AWS hosted UI, which I am not using.

I don't want my users that use LastPass to think that my application is insecure when in reality I am just using Amplify to handle my User Auth

**Comment by powerful23** [comment]
@Weasnerb what do you mean by `Auth.login` function? There is no such method in Amplify.

**Comment by Weasnerb** [comment]
@powerful23  My bad, I meant the `Auth.signIn(email, password)` function

**Comment by powerful23** [comment]
@Weasnerb According to the Cognito team for now you cannot do that but they will mark this as feature request.

**Comment by Weasnerb** [comment]
I may seem crazy but I have not changed a thing with Amplify or my Cognito and I am no longer getting the LastPass insecure form error. I still think that changing the url that `Auth.signIn(email, password)`  uses is something that would be cool to have, however I guess it is not necessary to fix this specific bug I was experiencing.

**Comment by sammartinez** [comment]
Resolving this as per the comment above
