### ISSUE TITLE
Best way to persist Auth Credentials during developing app

### ISSUE THREAD

**Issue by hyoungbin** [aws-amplify/amplify-js#1974]
Hi, I'm trying to build a react-native app with serverless features (cognito, api gateway, s3 etc)

On my app, I use only facebook login and google login, and I get cognito credentials like
```
const FBLogin = async ( ) => {

... get facebook permissions...

const credentials = await Auth.federatedSignIn("facebook", { token, expires_at }, user)
}
```
So I get cognito credentials when user clicks login button (I made my own button. not built in UI)
(actually not checking whether user is logged in when restart the app. I think this could be a problem.)

The Problem is, 
when I develop my react-native app, I reload a lot to check my code.
But after reload and trying to fetch some data from api gateway, (my api gateway check cognito identity pool authenticated role for security)
each time I reload my app, credentials deleted and I get error 

> NotAuthorizedException: Unauthenticated access is not supported for this identity pool

so when I reload my app I have to login again to get credentials.

in production level, this situation might not be happen, but when developing it is a big problem.
I know there are solutions to fix this, but I don't know how. 

What I'm thinking is 
Save cognito credentials to local storage or cache, and in `App.js` 
```
componentDidMount ( ) {
  if not authenticated, then get credential from local storage or cache
}
 ```

now I'm using
```
 "dependencies": {
    "aws-amplify": "^1.0.6",
    "react": "16.4.1",
    "react-native": "0.56.0",
    .....
}
```

What is the best way to retain cognito credentials ??

**Comment by powerful23** [comment]
@hyoungbin we do cache the tokens into the AsyncStorage to keep the user logged in. Can you do a check if the AsyncStorage is not working or something is clearing your AsyncStorage?

**Comment by hyoungbin** [comment]
@powerful23  Thanks to you I found my problem. the credentials were in AsyncStorage.
What I did was I fetched some data at `componentDidMount`, when Auth was not even configured. 

By doing this, I found it takes about two seconds to get credentials from AsyncStorage.
```
class App extends Component {
  constructor(props) {
    super(props);
    console.log("App started", Date());
  }

  render() {
    return (
      <Provider store={store}>
        <PersistGate persistor={persistor} loading={null}>
          <Authenticator
            hideDefault={true}
            onStateChange={authState => {
              console.log("authState", `${authState} : ${Date()}`);
            }}
          />
          <AppNavigator />
        </PersistGate>
      </Provider>
    );
  }
}
```

> App started Sat Oct 27 2018 17:43:47 GMT+0900 (KST)
> authState signIn : Sat Oct 27 2018 17:43:49 GMT+0900 (KST)


But I don't know to use `<Authenticator>` because of my own UI component and navigation logic. 
So I added Hub following the document. 

```
class App extends Component {
  constructor(props) {
    super(props);
    Hub.listen("auth", this, "auth-listener");
    console.log("App started", Date());
  }

  onHubCapsule(capsule) {
    const { channel, payload } = capsule;
    if (channel === "auth") {
      console.log("auth", payload.event);
    }
  }

  render() {
    return (
      <Provider store={store}>
        <PersistGate persistor={persistor} loading={null}>
          <AppNavigator />
        </PersistGate>
      </Provider>
    );
  }
}
```

The problem is, when I reload the app Hub logs nothing. 
I thought Hub could listen 'configured' situation. 
the document says 
> Auth.currentAuthenticatedUser()
>This method can be used to check if a user is logged in when the page is loaded. It will throw an error if there is no user logged in. This method should be called after the Auth module is configured or the user is logged in. 
> To ensure that you can listen on the auth events **configured** or **signIn**
[documents](https://aws-amplify.github.io/docs/js/authentication)

Hub listens perfectly when I do Auth.signOut(), Auth.federatedSignIn().
but not when I reload the app. 
is it a bug? or do I missing something??

**Comment by powerful23** [comment]
@hyoungbin can you try putting `this.onHubCapsule = this.onHubCapsule.bind(this);` into the `constructor`?

**Comment by hyoungbin** [comment]
@powerful23 I tried several things including your advice.
At last I could catch 'configured' situation. 

what I did is putting `Amplify.configure(awsConfig)` into `constructor` in my `App.js` which is my root class

```
import React, { Component } from "react";
import { awsConfig } from "./constants";
import Amplify, { Hub } from "aws-amplify";
....
// Amplify.configure(awsConfig);    <-- Before

class App extends Component<Props, State> {
  constructor() {
    super();
    Hub.listen("auth", this, "Auth");
    Amplify.configure(awsConfig);    <-- After
  }

 onHubCapsule(capsule) {
    const { channel, payload } = capsule;
    if (channel === "auth") {
      if (payload.event === "configured") {
        Auth.currentCredentials()
          .then(result => {
            console.log("credentials", result);
          })
          .catch(e => {
            console.log("error", e.message);
          });
      }

  render() {
    return (
      <Provider store={store}>
        <PersistGate persistor={persistor} loading={null}>
          <AppNavigator />
        </PersistGate>
      </Provider>
    );
  }
}
export default App;
```

But the problem is, in `onHubCapsule` `Auth.currentCredentials()` still gives me an error

> Unauthenticated access is not supported for this identity pool

So I looked in `node_modules/@aws-amplify/lib/Auth.js` 
```
AuthClass.prototype.configure = function (config) {

....

    core_1.Credentials.configure({   <-- This is my case (my app has only social logins) 
            mandatorySignIn: mandatorySignIn,
            region: identityPoolRegion || region,
            userPoolId: userPoolId,
            identityPoolId: identityPoolId,
            refreshHandlers: refreshHandlers,
            storage: this._storage
        });
     
    // initiailize cognitoauth client if hosted ui options provided
    if (oauth) { 
        ....
    }

dispatchAuthEvent('configured', null);
return this._config;
}
```
but `core_1.Credentials.configure()` which is the part getting the tokens from AsyncStorage, is not a Promise. 
so although 'configured' is dispatched I got the error because it's not async

`AuthClass.prototype.federatedSignIn()` dispatches Auth event 'signIn' after promise `core_1.Credentials.set()`

What I want to do is to fetch some data from the server after users credentials configured when users open my app. (not the first launch)

Is there a way to know users credentials configured ?

**Comment by powerful23** [comment]
@hyoungbin Glad to hear that. I am closing this issue. Feel free to reopen if you still have the issue.
