### ISSUE TITLE
withAuthenticator renders greetings with flag value false

### ISSUE THREAD

**Issue by kacpermigala** [aws-amplify/amplify-js#1976]
As I mentioned in title, I see that authPiece is rendered even if you use includeGreetings=false flag.

For react-native it is hard to style custom auth UI, because of it.
Screenshot below shows how View component looks with `flex:1` styling (it should take full screen & it's working like that without withAuthenticator HOC).

<img width="322" alt="screen shot 2018-10-24 at 14 42 24" src="https://user-images.githubusercontent.com/15971848/47430953-15c5fe00-d79b-11e8-8eed-e143ed0a43cf.png">

**Comment by nidsharm** [comment]
Hi @kacpermigala ,

I tried creating my own react-native app, and added Auth with Cognito User Pools and no federated identities. 
This is the code for my App.js file : 
```
import {withAuthenticator} from 'aws-amplify-react-native';
import Amplify from 'aws-amplify';
import awsmobile from './aws-exports';
Amplify.configure(awsmobile);
class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
      </View>
    );
  }
}

export default withAuthenticator(App,includeGreetings = false);
```

and resulting UI when a customer is signed in as follows : 
<img width="257" alt="screen shot 2018-10-25 at 2 44 37 pm" src="https://user-images.githubusercontent.com/28815212/47532204-8a18a400-d864-11e8-8d21-a5385fed1ae1.png">

I dont see the Greetings in my UI. Could you please share your code where withAuthenticator is called ? Also, what are the configurations for Auth in your App ?

**Comment by powerful23** [comment]
Closing this issue due to no further response. Feel free to reopen if you still have this issue.
