### ISSUE TITLE
Undeclared dependencies on aws-amplify-react

### ISSUE THREAD

**Issue by aldo-roman** [aws-amplify/amplify-js#1978]
**Describe the bug**
During runtime, `aws-amplify-react` depends (at least) on:
```
@aws-amplify/analytics
@aws-amplify/api
@aws-amplify/interactions
@aws-amplify/storage
```
But these dependencies are not declared on the respective `package.json`.
They seem to be expected to be installed by `aws-amplify`.
That wouldn't be a problem, but at least having them as `peer-dependency` would warn the developer about the problem.

**To Reproduce**
1. Create an npm project
2. Install and use `aws-amplify-react` and some `@aws-amplify/*` module, but not `aws-amplify`
3. Run

**Expected behavior**
App should run OR `aws-amplify-react` should declare its own dependencies

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Version: All

**Additional context**
I was trying to use only `@aws-amplify/auth` and `aws-amplify-react`.

**Comment by powerful23** [comment]
@aldo-roman for now you must install `aws-amplify` when using `aws-amplify-react`.

**Comment by jpaas** [comment]
The docs seem to imply that this is already supposed to work: https://github.com/aws-amplify/amplify-js/wiki/Amplify-modularization#apply-modularized-amplify-to-other-packages

**Comment by jpaas** [comment]
I am using `aws-amplify-react-native` BTW and its the same issue

**Comment by powerful23** [comment]
Closing the issue because the `aws-amplify` has been marked as `peerDenpendencies`.

**Comment by ecovirtual** [comment]
Does `aws-amplify-react` really need to depend on `@aws-amplify/xr`? 
I just want to have a component not Augmented Reality on my app.
