### ISSUE TITLE
User should be able to remove ""sign in with AWS" in signIn page

### ISSUE THREAD

**Issue by bluefig99** [aws-amplify/amplify-js#1980]
**Describe the bug**
As we are using AWS Amplify HOC , we need to have an option to remove the "sign in with AWS". As we do not have any option to change the background color of the page in case of Hosted UI ,we are using AWS Amplify HOC.

So , please provide us the option to remove ""sign in with AWS" from signIn page.

**Comment by aldo-roman** [comment]
I could remove that button by disabling OAuth. Just sign in against Cognito using:
```
Amplify.configure({Auth: {...}})
```

**Comment by bluefig99** [comment]
@aldo-roman I tried to remove it.But still i can see the button.

 Amplify.configure({
     Auth: {
        //   oauth: oauth,
          userPoolWebClientId: 'xyz',
          region: 'us-east-1',
          userPoolId: 'us-east-1_xyz',
     },
 });

**Comment by aldo-roman** [comment]
are you using any federated setup? the signin button loads from Federated component

**Comment by bluefig99** [comment]
i am just using this

 class App extends Component {

   render() {
       return(
            <div>
               <SecondPage />
            </div>
       )
   }
 }
 export default withAuthenticator(App);

**Comment by bluefig99** [comment]
@nidsharm Can you please help with this issue? Is anyone looking in to it?

Thanks
Aravind

**Comment by nidsharm** [comment]
@bluefig99 , I used the [Amplify CLI](https://github.com/aws-amplify/amplify-cli) to add Auth to my basic app that I created using CRA. I only have SignIn with UserPools enabled (no federated identities) and my app code looks like this : 

```import {withAuthenticator} from 'aws-amplify-react';
import Amplify from 'aws-amplify';
import awsmobile from './aws-exports';
Amplify.configure(awsmobile);
class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <p>
            Edit <code>src/App.js</code> and save to reload.
          </p>
          <a
            className="App-link"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Learn React
          </a>
        </header>
      </div>
    );
  }
}

export default withAuthenticator(App);
```

and my authenticator component looks like this 
 
<img width="542" alt="screen shot 2018-10-25 at 12 27 05 pm" src="https://user-images.githubusercontent.com/28815212/47525310-c4c51100-d851-11e8-92fa-e63aab529cad.png">

So I dont see the SignIn with Amazon button unlike you.

**Comment by nidsharm** [comment]
@bluefig99, could you please tell us more about your Auth configuration like are you using any of the federated identity providers or just Cognito User Pools ?

**Comment by bluefig99** [comment]
@nidsharm I am using <Authenticator> directly in my component. The issue was , i was not using webclientid. After fixing it, the behavioud is as expected. I can see the same screen as above.

Thanks
Aravind

**Comment by h-hub** [comment]
I removed the **OPTIONAL - Hosted UI configuration**  from the aws-exports.js and it worked.
