### ISSUE TITLE
Is there a way to change or update user's email using amplify from the front end?

### ISSUE THREAD

**Issue by josoroma** [aws-amplify/amplify-js#1981]
** Auth **

** Cognito / MobileHub **

Using Email address to sign in... Is there a way to change or update user's email using amplify from the front end?

I don't get the flow yet.

Thanks.

**Comment by josoroma** [comment]
I just found it: **updateUserAttributes**

https://aws-amplify.github.io/docs/js/authentication

**Comment by Luckygirlllll** [comment]
@josoroma Will it update username (if I use email as username)? or it will only update value in attributes?

**Comment by tomaszdudek7** [comment]
@Luckygirlllll did you find the answer to your question? :P

**Comment by Luckygirlllll** [comment]
@tomaszdudek7 I used method `verifyCurrentUserAttribute()` , here is a link to the official documentation: https://aws-amplify.github.io/amplify-js/api/classes/authclass.html#verifyuserattribute

**Comment by tomaszdudek7** [comment]
@Luckygirlllll Thank you, this indeed worked.

This might be related: when you change a phone number or an email which is treated as a username, using `updateUserAttributes`, then you verify the attributes, the `username` attribute does not get updated!

Pre-update:
```
CognitoUser {username: "+48999999999", attributes: {phone_number: "+48999999999"}
```
Post-update:
```
CognitoUser {username: "+48999999999", attributes: {phone_number: "+48123456789"}
```
Only after logging out and logging in again, the attribute is shown properly:
```
CognitoUser {username: "+48123456789", attributes: {phone_number: "+48123456789"}
```

Any idea how would one trigger `username` update after changing and veryfing the `phone_number` attribute?

**Comment by Luckygirlllll** [comment]
@tomaszdudek7 Do you use `Auth.currentUserInfo()` for getting info about the user?

**Comment by tomaszdudek7** [comment]
@Luckygirlllll Yes, `attributes { phone_number ` are indeed refreshed. But the `userName` and `userNameKey` field (which are on the same level as `attributes` - one level above `phone_number` for example) are the same.

Only logging in and out refreshes them.

**Comment by Luckygirlllll** [comment]
@tomaszdudek7 You can try to use this method `Auth.currentAuthenticatedUser()`.

**Comment by jamzrob** [comment]
@tomaszdudek7 Any update on this?

**Comment by jamzrob** [comment]
A little update on this, am allowing username and phone_number as username with signup looks like it solves the unchangeable username policy and creates a nice uuid, not sure if it will let me change the email and phone_number depending on what was used to sign up
