### ISSUE TITLE
User profile with federated login

### ISSUE THREAD

**Issue by ahmetcetin** [aws-amplify/amplify-js#1983]
**Is your feature request related to a problem? Please describe.**
Using withAuthenticator with federated authentication (facebook), the logged in user has only name and id, no other info like email, user photo, etc. Tried to setup mapping in User Pool, but still doesn't work. It looks amplify only uses Federated Identities only.

**Describe the solution you'd like**
Either it should use Cognito User Pool to add user data, or it should give in front end additional user info.

**Describe alternatives you've considered**
Dropping Cognito, and implement ourselves

**Additional context**
I just can't imagine any app which uses Facebook login for example, without utilizing user's profile info, it would look weird also to ask user to ask their email in a popup after they login with facebook, because when they authorize in Facebook, the asked data is email and public profile. As it is, federated login in amplify is kinda useless.

**Comment by nidsharm** [comment]
Hi @ahmetcetin , 

The withAuthenticator component calls another FB login underneath and the data that we pass back currently is just the username. We can make this into a feature-request and have more of the logged in user data be passed back from facebook. 

For the time being, you could use Cognito Hosted UI with your app : https://aws-amplify.github.io/docs/js/authentication#using-amazon-cognito-hosted-ui and get a user signed in with facebook, then import them into Cognito User Pool and add all the attributes for them in Cognito.

**Comment by ahmetcetin** [comment]
Thx for reply @nidsharm, well hosted ui is not customizable afaik, therefore it's not really useful for anything except mvp or toy projects. I'd try to fix it and send pr if you can tell me in which file this authentication request sent to facebook.

Cheers,

**Comment by nidsharm** [comment]
@ahmetcetin , that would be great. This is where we pass the user's name facebook authentication : https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Auth/Provider/withFacebook.jsx#L71

**Comment by nidsharm** [comment]
Also, there is an App Integration -> UI Customization section on the Cognito console, and that might help with the customizations you might want for hosted UI.

**Comment by ahmetcetin** [comment]
Thx, I sent PR #1996 to cover this. hosted ui doesn't help much, as i want to use custom components.

**Comment by ahmetcetin** [comment]
pr #1996 merged, closing.
