### ISSUE TITLE
Selectors to style Amplify UI Nav and Toast components in aws-amplify-react

### ISSUE THREAD

**Issue by namya-r** [aws-amplify/amplify-js#1985]
I'm able to add custom styling to Amplify UI components by using selectors from [this template](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Amplify-UI/Amplify-UI-Theme.jsx).
```
const MyTheme = {
  button: { backgroundColor: '#FFC0CB' },
  a: { color: '#FFC0CB' },
};
```
I'm passing my theme as a parameter to withAuthenticator in React.

Are there any selectors I can use to style the Amplify UI Nav (including NavBar, NavItem and NavButton) and Toast components?

**Comment by jordanranz** [comment]
Hi @namya-r, thanks for submitting feedback.

I believe adding navBar: { ... } and navItem: { ... } to your theme will style those components respectively. As for styling the NavButton and Toast component there may be a bug in the way these pick up theme styling. I will investigate and report back when I have that fixed.

Let me know if the navBar and navItem styling works

**Comment by mbassov** [comment]
+1 for not being able to style the Toast. Code below doesn't seem to change the background color.
```
export const MyToast = {
    backgroundColor: "#43ac6a"
}
const MyTheme = Object.assign({}, AmplifyTheme, { 
    toast: MyToast
});
<Authenticator theme={MyTheme} />
```

**Comment by namya-r** [comment]
Hi @jordanranz, thank you!

I added navBar and navItem but am still unable to style them. Not sure if I've added them correctly.

```
const MyTheme = {
  navBar: { backgroundColor: '#FFC0CB' },
  navItem: { backgroundColor: '#FFC0CB' },
};
```

**Comment by jordanranz** [comment]
You have added them correctly!

The theme was not being passed down to the Authenticator UI component within the withAuthenticator HOC. I have submitted a PR to fix this. I will update this issue when it has been merged into our release version. Thanks again for the feedback.
