### ISSUE TITLE
error aws pinpoint when apps is foreground 

### ISSUE THREAD

**Issue by noellaby** [aws-amplify/amplify-js#1988]
Hello

when the application is in foreground mode, Aws Aplify Push notification does not display the notification, I use the zo0r / react-native-push-notification library to display a local notification. i have this errorr
`undefined is not an object (evaluating 'dataPayload['pinpoint.campaign.campaign_id']')`

### my source code 

` 

PushNotification.onNotification((notification) => {

            console.log('in app notification aws push', notification);

            if (notification.foreground == true) {

                PushNotificationRNZo0r.localNotification({
                    autoCancel: true, // (optional) default: true
                    largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
                    smallIcon: "ic_notification",
                    color: "red", // (optional) default: system default
                    vibrate: true, // (optional) default: true
                    vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
                    tag: 'some_tag', // (optional) add tag to message
                    group: "group", // (optional) add group to message
                    ongoing: false, // (optional) set whether this is an "ongoing" notification
                    priority: "high", // (optional) set notification priority, default: high
                    visibility: "private", // (optional) set notification visibility, default: private
                    importance: "high", // (optional) set notification importance, default: high                 
                    title: notification.title, // (optional)
                    message: notification.body, // (required)
                    playSound: true, // (optional) default: true
                    soundName: 'default'
                });
            }
        }); 
`
Pls :  How to fix error (Link Image error : https://www.noelshack.com/2018-43-4-1540499852-whatsapp-image-2018-10-25-at-21-34-15.jpeg)

**Comment by noellaby** [comment]
@noellaby

**Comment by noellaby** [comment]
@powerful23  help me

**Comment by pribadi1st** [comment]
is this on android or ios ?
