### ISSUE TITLE
Amplify Analytics does not batch submit events

### ISSUE THREAD

**Issue by lambrospetrou** [aws-amplify/amplify-js#1989]
**Describe the bug**
The AWS Amplify Analytics do not batch the events, even when using the buffering capabilities offered, but instead submit each event individually (two requests per event, OPTIONS+submission).

I was using the old [amazon mobile analytics](https://github.com/aws/aws-sdk-mobile-analytics-js) and it was batching the events just fine, but upgraded to amplify for the new features and due to the fact that the AMA bundled the whole AWS SDK.

It's unfortunate that this shiny new library does not batch submit the events, resulting in hundreds of API calls in my application, hence restricting me on how many things to record.

**To Reproduce**
1. Enable Amplify analytics using the [default guide](https://aws-amplify.github.io/docs/js/analytics#record-a-custom-event-with-attributes)
2. Call `Analytics.record(...)` many times (10+) in the same second to add events to the buffer
3. Open the **network** section in your web developer tools
4. See the numerous submissions to the API with each submission containing a single event

**Expected behavior**
I expected a submission to contain multiple recorded events, not necessarily to the local buffer size, but definitely not 1 event per API call.

**Desktop (please complete the following information):**
 - OS: Linux, MacOS
 - Browser: Chrome, Firefox, Safari

**Issue in the code**

I believe the problem is [this line of the code](https://github.com/aws-amplify/amplify-js/blob/master/packages/analytics/src/Providers/AWSPinpointProvider.ts#L76) which executes `this._sendFromBuffer(params);` for each individual event from the buffer, which in turn calls `_recordCustomEvent`, which in turn calls [`_generateBatchItemContext(params)`](https://github.com/aws-amplify/amplify-js/blob/master/packages/analytics/src/Providers/AWSPinpointProvider.ts#L341-L343). Note the misleading name, which is not a **BatchItemContext** since it only includes a **single** event.

In my opinion, [this looping over the **buffered** events](https://github.com/aws-amplify/amplify-js/blob/master/packages/analytics/src/Providers/AWSPinpointProvider.ts#L74-L77) should create a batch context containing several events and then doing one API call for each of those batches.

**Comment by mlabieniec** [comment]
The methods you are referencing here are part of a larger update/refactor to the Pinpoint provider to actually support an updated batch events Pinpoint service API that did not exist prior. This update on the Amplify Analytics side should in-turn be complete in the next couple sprints and is in our backlog up next now that the API is available. Will track the release of that update here.

**Comment by lambrospetrou** [comment]
Hello @mlabieniec happy new year first of all;p
Is there any update on the batch event submission or a ticket/issue that we can track the progress?

Thanks

**Comment by jordanranz** [comment]
Hey @lambrospetrou, @powerful23 is currently in the process of designing support for this. We will make an update to this issue when progress has been made on the code implementation.

**Comment by lambrospetrou** [comment]
What's the status on this? Has it been implemented?

**Comment by laygir** [comment]
Any updates?  👀

**Comment by lambrospetrou** [comment]
This has been open for more than a year now...Is it still in-progress since last January?

The library generates tens and sometimes hundreds of event submission requests (since half of them are the `OPTIONS` requests).

**Comment by iartemiev** [comment]
@lambrospetrou there's a PR up that adds support for this (#4289). I'll let you know when it's merged

**Comment by iartemiev** [comment]
@lambrospetrou We just merged the PR that enables batch event sending with Pinpoint. It's available through the unstable tag, i.e. `yarn add aws-amplify@unstable`
