### ISSUE TITLE
Add an attribut isSignUpDisplayed to the config objects for the components amplify-sign-in

### ISSUE THREAD

**Issue by cde06** [aws-amplify/amplify-js#1993]
Pullrequest #1994

**Is your feature request related to a problem? Please describe.**
I don't want to allow end-user to signup.  So, I have disable signup feature from cognito but signup link is still available in the UI component SignIn.vue.

**Describe the solution you'd like**
I would like to be able to disable the signup feature on the component 
aws-amplify-vue/src/components/authenticator/SignIn.vue thank to a boolean 'isSignUpDisplayed'
as: 
`<amplify-sign-in :signInConfig="signInConfig" />`
```
 export default {
  data() {
    return {
        signInConfig: {
          isSignUpDisplayed : false //default true
        }
    };
  }
}
```

To achieve this target we just need to add a `v-if="options.isSignUpDisplayed"` on wrapping span tag in SignIn.vue
```
<span v-bind:class="amplifyUI.sectionFooterSecondaryContent" v-if="options.isSignUpDisplayed">
        No Account?
        <a v-bind:class="amplifyUI.a" v-on:click="signUp">Sign Up</a>
</span>
```

**Comment by haverchuck** [comment]
@shawnlauzon - We will take a look doing this for Angular.
