### ISSUE TITLE
Is token decode considered stable ?

### ISSUE THREAD

**Issue by eltonio450** [aws-amplify/amplify-js#2001]
Hello,

Yesterday, I wanted to access the cognito group info after login a user with Amplify. It turns out the info is not easily accessible (it's not documented btw...). I ended up decoding the token 👍 
```
 Auth.currentSession().then((res) => {
      const payload = res.getIdToken().decodePayload()
      const isAdmin = payload["cognito:groups"] && payload["cognito:groups"].includes("admin")
      this.setState({isAdmin})
    }

```

So, two questions:
- did I miss an easier method somewhere ?
- if not, is this pattern considered as standard, and am I assured that it will remain in the future of Amplify/Cognito ?

Thank you

### Which Category is your question related to? 

Cognito user pool information access1

### What AWS Services are you utilizing? 

AWS Amplify + Cognito user pools

**Comment by powerful23** [comment]
@eltonio450 hey as I know for now the Amplify has no explicit API to get the cognito group info. But I think the work around you made is safe to use and will remain in the version of `1.x.x`

**Comment by eltonio450** [comment]
Thanks :)
