### ISSUE TITLE
undefined is not an object e.TYPED_ARRAY_SUPPORT

### ISSUE THREAD

**Issue by woodpav** [aws-amplify/amplify-js#2005]
**Describe the bug**
When running the release build on both iOS and Android I get a crash `undefined is not an object (evaluating 'e.TYPED_ARRAY_SUPPORT')`. Searching my node_modules leads me to this repo. The relevant lines are in `node_modules/@aws-amplify/auth/dist/aws-amplify-auth.min.js` and others.

    "@aws-amplify/api": "^1.0.18",
    "@aws-amplify/auth": "^1.2.7",
    "@aws-amplify/core": "^1.0.16",
    "aws-sdk": "^2.344.0",
    "buffer": "^5.2.1",
    "react": "^16.6.0-alpha.8af6728",
    "react-native": "^0.57.4",

`shim.js`. This is the first JS code executed.

    global.Buffer = require('buffer/').Buffer;

`.babelrc` I am ignoring the `aws-sdk` because of https://github.com/aws/aws-sdk-js/issues/1877#issuecomment-366825293

    "presets": [
        "module:metro-react-native-babel-preset"
    ],
    "ignore": [
        "node_modules/aws-sdk/dist/aws-sdk-react-native.js",
    ],

Amplify modules are imported like `import Auth from '@aws-amplify/auth';`

**To Reproduce**
1. Build for release (iOS or Android)
2. Open release build (iOS or Android)
3. Experience crash immediately

**Expected behavior**
The release build runs.

Related: #803

**Comment by woodpav** [comment]
I am experiencing this error after upgrading to react-native `0.57.4`. 

I get this message when I run `install`.

    DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

I am getting this log in the console:

    Require cycle: node_modules/@aws-amplify/core/node_modules/aws-sdk/lib/react-native-loader.js -> node_modules/@aws-amplify/core/node_modules/aws-sdk/lib/credentials/temporary_credentials.js -> node_modules/@aws-amplify/core/node_modules/aws-sdk/clients/sts.js -> node_modules/@aws-amplify/core/node_modules/aws-sdk/lib/react-native-loader.js

    Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

and

    require.js:122 Require cycle: node_modules/@aws-amplify/core/node_modules/aws-sdk/lib/react-native-loader.js -> node_modules/@aws-amplify/core/node_modules/aws-sdk/lib/credentials/cognito_identity_credentials.js -> node_modules/@aws-amplify/core/node_modules/aws-sdk/clients/cognitoidentity.js -> node_modules/@aws-amplify/core/node_modules/aws-sdk/lib/react-native-loader.js

    Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

**Comment by woodpav** [comment]
I changed the require to `require('buffer/')` and downgraded to 4.x with no luck. 

https://github.com/feross/buffer/blob/c8e3dc7af4e9367bcb14efd3d95c0bf467a67bee/index.js#L24

**Comment by woodpav** [comment]
`@babel/runtime` needs to be in `dependencies` not `devDependencies` and `@babel/plugin-transform-runtime` in `.babelrc`. Doing this resulted in the same error as #803 and in debug mode.

**Comment by woodpav** [comment]
I was able to resolve the issue by manually editing the `aws-sdk.js` file. I have posted a seperate issue in the `aws-sdk` repo. My temporary solution is here: https://github.com/aws/aws-sdk-js/issues/2326

**Comment by woodpav** [comment]
For the record, I am no longer getting this error. I'm not sure what changed 😅

**Comment by elorzafe** [comment]
@woodpav is ok to close the issue?
