### ISSUE TITLE
PubSub connection lifecycle handling

### ISSUE THREAD

**Issue by nayan27** [aws-amplify/amplify-js#2007]
Hi there,
I am using Amplify PubSub with AWS IoT.
I have trouble understanding how Amplify with IoT lifecycle works.
I would like to be able to easily retrieve the connection status of the IoT provider.
To me it seems like the connection is established automatically at a certain point after the call to addPlugable(new AWSIoTProvider({...})).
Can i request the connection by myself ? Can i intercept error message from the connection attempt ?
Can i provide a callback to acknoledge the different connection status (Connecting, Connected, ConnectionLost) ?
How can i know if the connection was lost ?
Thank you,

**Comment by loganwedwards** [comment]
This would be a great improvement. At minimum, Paho already supports `onConnectionLost`, so it should be minimal effort. My client suffers from disconnects from time to time and knowing how to automatically handle that would be great UX improvement.

**Comment by nayan27** [comment]
Any update on this topic ? We really need an interface to handle connection status! Thank you!

**Comment by schaq8** [comment]
+1 request for connection/subscription event handlers and methods to retrieve current status.

**Comment by nayan27** [comment]
This has been open for more than 6 months now and from what i understand the fix seems fairly quick to make. When can we expect to have some news for this ?

@manueliglesias  @elorzafe 

Thank you

**Comment by jordanranz** [comment]
@nayan27, we are open to accept PRs for this. Please feel free to contribute if you'd like this feature.

In the meantime, I can mark this as a feature request and we can evaluate whether or not to prioritize it.

**Comment by Flora140** [comment]
+1 Request 

> PRs

Would really appreciate this change
