### ISSUE TITLE
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

### ISSUE THREAD

**Issue by muhammaddadu** [aws-amplify/amplify-js#2026]
**Describe the bug**
This bug is related to the way Chrome throws an exception when accesing `localStorage`.

The error thrown by the browser is
```
index.js:25 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object../node_modules/@aws-amplify/core/lib/RNComponents/index.js
```

**To Reproduce**
1. Disable `localStorage` on chrome browser. Instructions can be found [here](https://mid.as/kb/article/00103)
2. Visit a project that utilizes localStorage and amplify
3. Project throws the above exception

**Expected behavior**
1. Disable `localStorage` on chrome browser. Instructions can be found [here](https://mid.as/kb/article/00103)
2. Visit a project that utilizes localStorage and amplify
3. Project should not throw the above exception and should handle accordingly

**Desktop:**
 - OS: OSX High Sierra
 - Browser: Chrome
 - Version: 70.0.3538.77 (Official Build) (64-bit)

**Comment by muhammaddadu** [comment]
PR: https://github.com/aws-amplify/amplify-js/pull/2027

**Comment by jordanranz** [comment]
Seems a change was merged for this. Closing this issue now.
