### ISSUE TITLE
Uncaught ReferenceError: require is not defined     at Object.crypto (external "crypto":1)

### ISSUE THREAD

**Issue by ngoyal16** [aws-amplify/amplify-js#2033]
**Describe the bug**
When we added aws-amplify for authentication with vuejs with the dev mode it is working fine. but when we build it for test and deployed on server it is giving this error

**To Reproduce**
1. Go to 'http://owl-verify.technovendors.com'
2. Noting will show you on this. 
3 open dev-tool console 

**Expected behavior**
should work with webpack

**Comment by ngoyal16** [comment]
@haverchuck any

**Comment by haverchuck** [comment]
@ngoyal16 - Apologies for the late reply.  I don't see any app at the url you posted above. Perhaps you could supply an updated one?  Also, which versions of aws-amplify or aws-amplify and aws-amplify-vue are you using?

**Comment by ngoyal16** [comment]
I fixed the issue

**Comment by jalmazora** [comment]
@ngoyal16 how did you fix this?

**Comment by volkanunsal** [comment]
I'm having the same issue.
