### ISSUE TITLE
appsync subscriptions not working (react app)

### ISSUE THREAD

**Issue by dmvakh** [aws-amplify/amplify-js#2039]
I'm new in Amplify, can't understand how to use subscriptions

All queries/subscriptions generated through `amplify add codegen`
All code took from the documentation.
All mutations made through `AWS AppSync Queries console`.
Queries work like a charm.

No reactions - `onSubscriptionMsg` haven't fired.

Please explain what's wrong with my code.

**GraphQL Schema**
```
input CreateMyModelTypeInput {
	title: String
}

type Mutation {
	createMyModelType(input: CreateMyModelTypeInput!): MyModelType
}

type MyModelType {
	id: ID!
	title: String
}

type MyModelTypeConnection {
	items: [MyModelType]
	nextToken: String
}

type Query {
	listMyModelTypes(limit: Int, nextToken: String): MyModelTypeConnection
}

type Subscription {
	onCreateMyModelType(id: ID, title: String): MyModelType
		@aws_subscribe(mutations: ["createMyModelType"])
}
```
**AWS Config**
```
{
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://***/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "***"
}
```

`subscriptions` file
```
export const onCreateMyModelType = `subscription OnCreateMyModelType($id: ID, $title: String) {
  onCreateMyModelType(id: $id, title: $title) {
    id
    title
  }
}
`;
```

**React App**
```
import React, { Component } from 'react';

import Amplify, { graphqlOperation }  from "aws-amplify";
import { Connect } from "aws-amplify-react";

import aws_config from "./aws-exports";

import * as queries from './graphql/queries';
import * as subscriptions from './graphql/subscriptions';

Amplify.configure(aws_config);

class App extends Component {

  render() {
    const ListView = ({ todos }) => (
        <div>
            <h3>All Todos</h3>
            <ul>
                {todos.map(todo => <li key={todo.id}>{todo.title} ({todo.id})</li>)}
            </ul>
        </div>
    );

    return (
      <Connect
        query={graphqlOperation(queries.listMyModelTypes)}
        subscription={graphqlOperation(subscriptions.onCreateMyModelType)}
        onSubscriptionMsg={(prev, { onCreateMyModelType }) => {
            console.log ( onCreateMyModelType );
            return prev; 
        }}
      >
          {({ data: { listMyModelTypes }, loading, error }) => {
              if (error) return (<h3>Error</h3>);
              if (loading || !listMyModelTypes) return (<h3>Loading...</h3>)
              return <ListView todos={listMyModelTypes.items} />
          }}
      </Connect>
    );
  }
}

export default App;
```
Version: 
aws-amplify ^1.1.9
aws-amplify-react ^2.1.3
react ^16.6.0

Browser: Chrome

OS: MacOS 10.14

**Comment by undefobj** [comment]
AppSync subscription notifications are fired in response to a mutation being triggered, and the fields that are sent must be specified in the selection set of the mutation. So looking at your schema here is the subscription defined:

```
onCreateMyModelType(id: ID, title: String): MyModelType
		@aws_subscribe(mutations: ["createMyModelType"])
```

This means that when a mutation for `createMyModelType` runs, the `onCreateMyModelType` will be triggered. So you could test this by running your application and in the console running the mutation:

```
mutation M {
  createMyModelType(input: {
    title:"War and Peace"
  }){
    id
    title
  }
}
```

If that runs fine but there is no message to the client, it's possible the client subscription is setup incorrectly. You could validate this by opening up another instance of the console and doing the subscription in one window and the mutation in the other.

**Comment by YikSanChan** [comment]
I have the same issue. Only difference is, rather than using `<Connect />`:
```js
componentDidMount() {
  this.updateItemListener = API.graphql(
      graphqlOperation(subscriptions.onUpdateItem)
    ).subscribe({
      next: updateItemResult => {
        logger.debug("updateItemResult from subscription", JSON.stringify(updateItemResult, null, 2));
      }
    });
}

componentWillUnmount() {
  this.updateItemListener.unsubscribe();
}
```
My schema:
```graphql
type Subscription {
  onUpdateItem: Item @aws_subscribe(mutations: ["updateItem"])
}
```
subscriptions.js
```js
export const onUpdateItem = `subscription OnUpdateItem {
  onUpdateItem {
    id
    ...
  }
}
`;
```
Then I update item on AppSync console, however, nothing happens, even though I expect to see logger DEBUG message.

**Comment by YikSanChan** [comment]
I solved the problem by upgrading aws-amplify to the latest version. @dmvakh

**Comment by alxx** [comment]
> I solved the problem by upgrading aws-amplify to the latest version. @dmvakh

What version do you use now? My mutations still don't trigger the subscriptions and I'm using the latest as of today, 1.1.19

**Comment by jordanranz** [comment]
@dmvakh/@alxx  , are you still experiencing this issue with the latest version?

**Comment by alxx** [comment]
I don't know; I stopped using Amplify and switched to an alternative library instead.

**Comment by dmvakh** [comment]
@jordanranz tested it again near 2 months ago - the result was the same

**Comment by shlomizadok** [comment]
It seems to be not working when passing a parameter to the subscription.
My code is:
```
this.subscription = await API.graphql(
      graphqlOperation(subscriptions.onCreatePost, {path: this.state.path})
    ).subscribe({
      next: postData => {...}
```

My graphql original schema was:
```
type Subscription {
	...
	onCreatePost(path: String): Post
		@aws_subscribe(mutations: ["createPost"])
       ...
```
Which returned nothing.
Had to change it to:
```
type Subscription {
	...
	onCreatePost: Post // <-- No (path: String)
		@aws_subscribe(mutations: ["createPost"])
       ...
```
to receive the subscription
