### ISSUE TITLE
AWSIoTProvider connect and disconnect

### ISSUE THREAD

**Issue by rogueturnip** [aws-amplify/amplify-js#2040]
Hi,

I'm trying to disconnect and reconnect my AWSIoTProvider instance as my React Native goes background to foreground.  The documentation is very limited on these 2 methods (connect and disconnect).

What I'm wondering is when I issue disconnect does it unsubscribe from all the tops?  If it doesn't, does the connect re-establish them all?

When I look at the object for AWSIotProvider it has an array of all the topics both after disconnect and after connect but when I send messages on the topic after restoring the connection it doesn't seem to receive anything.

Thanks!  It would be great if AWSIotProvider was observable or able to reconnect on it's own then I wouldn't need to dive into these methods.

Tony

**Comment by rogueturnip** [comment]
I ended up using the paho library directly to create my client.

**Comment by sammartinez** [comment]
Here is documentation on using our [PubSub](https://aws-amplify.github.io/docs/js/pubsub) category. I do see that you went with another solution. Resolving as the documentation talks about subscribing and unsubscribing
