### ISSUE TITLE
API.get with parenthesis results in InvalidSignatureException

### ISSUE THREAD

**Issue by 0xR** [aws-amplify/amplify-js#2041]
**Describe the bug**
When I make a GET request which contain parenthesis anywhere in the url I get 
 InvalidSignatureException.

**To Reproduce**
```js
  API.get('my-api', '/my-path', {
    queryStringParameters: {
      name: 'name with (parens)',
    },
  });
```

I get a 403 from API gateway with these headers:

```
x-amzn-errortype: InvalidSignatureException
x-cache: Error from cloudfront
```

**Expected behavior**
A valid response

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome

**Comment by elorzafe** [comment]
This was fixed by PR #2631
