### ISSUE TITLE
how to create custom attributes in demographics pinpoint

### ISSUE THREAD

**Issue by pribadi1st** [aws-amplify/amplify-js#2043]
** Which Category is your question related to? **
Analytics
** What AWS Services are you utilizing? **
Aws-amplify/analytics | React-Native
** Provide additional details e.g. code snippets **
Hi, i want to know how to create custom demographic chart, so i can use in my segmentation.

i followed the instruction in documentation https://aws-amplify.github.io/docs/js/analytics

My Configuration : 
`import Analytics from '@aws-amplify/analytics';`
`Analytics.configure(aws_exports);`

How to update : 
`Analytics.updateEndpoint({`
`      optOut: 'ALL',`
`      attributes: {`
`        language: "english"`
`     },`
`    });`

is this correct way to add custom attribute ?  since i dont see the "Language" in my demographics chart.

i really appreciate your help. thank you

**Comment by powerful23** [comment]
@pribadi1st hey can you try something like:
```js
Analytics.updateEndpoint({
optOut: 'ALL',
demographic: {
language: "english"
},
});
```

**Comment by pribadi1st** [comment]
thank you for your reply @powerful23 , it seems i made a mistake at my configuration.
i'm closing this issue now
