### ISSUE TITLE
Add ResponseContentDisposition support in Storage.get

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-js#2052]
**Is your feature request related to a problem? Please describe.**
Would like to override name of file being downloaded. One way to do this is to support a ReponseContentDisposition param that can be passed to Storage.get. See 'response-content-disposition' at https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html. 

**Describe the solution you'd like**
Pass a 'responseContentDisposition' in the options param of Storage.get in https://github.com/aws-amplify/amplify-js/blob/168707e27e5bcec496a6fb6d1b09286262fe2d9c/packages/storage/src/Storage.ts#L86 similar to expires. 

**Describe alternatives you've considered**
Can set content-disposition on upload (though aws appsync does not seem to support this right now, will file ticket), or just download the binary and handle the file download myself (using https://github.com/eligrey/FileSaver.js), or call s3 directly outside of amplify. 

**Additional context**
Need to show original filename at download and not the uuid.

**Comment by jonasduever** [comment]
Has such a feature/parameter been integrated in the meantime?
Or is there a workaround (using Amplify)?

**Comment by chrisbonifacio** [comment]
Closing as this feature request has been addressed in the PR mentioned above.
