### ISSUE TITLE
Authentication with Active Directory for a ReactNative application

### ISSUE THREAD

**Issue by hoang-innomizetech** [aws-amplify/amplify-js#2053]
** Which Category is your question related to? **
Authentication

** What AWS Services are you utilizing? **
AWS Cognito
AWS Lambda
AWS API Gateway

** Provide additional details e.g. code snippets **
I am trying to implement the authentication flow that integrates Cognito User Pool with Active Directory for a ReactNative application (support both iOS and Andriod). There are a few approaches I am looking for:
* Enable SAML provider and configure app clients.
Basically, we have successfully implemented for an SPA using hosted UI
Does is work for a ReactNative application or we have to use native code?
* Using custom authorizer of by using custom Lambda function that connects to the AD using LDAP https://github.com/trentm/node-ldapauth. We can build a custom sign in form from the mobile app and trigger a custom authentication flow.

Does anyone has successfully implemented this authentication flow? If so, can you share your idea and sample code?

Thank in advance!

**Comment by hoang-innomizetech** [comment]
@powerful23  Do you have any update on this issue? Currently, our dev team is trying to implement this by using AuthSession (the Expo module that built on top of the WebBrowser). Basically, we are able to implement it but we also wanted to know whether Amplify team has a different approach to implement this feature

**Comment by powerful23** [comment]
@hoang-innomizetech sorry for the latest response. Can you check the doc: https://aws-amplify.github.io/docs/js/authentication#oauth-and-federation-overview which has detailed info about how to use Hosted UI in React Native.

**Comment by hoang-innomizetech** [comment]
@powerful23  yeah, we checked the documentation, but Amplify currently only supported social sign in. However, we are looking for ADFS authentication, there is no detail about that on the site

**Comment by powerful23** [comment]
@hoang-innomizetech Hi, I am going to close the issue as you can do the same thing in React Native App as what you did in SPA that you can use the Hosted UI to sign in with Active Directory. Please check the doc of launching Hosted UI in Expo: https://aws-amplify.github.io/docs/js/authentication#a-note-for-expo-users
