### ISSUE TITLE
Auth : SSR, Polyfill

### ISSUE THREAD

**Issue by romainquellec** [aws-amplify/amplify-js#2054]
**Is your feature request related to a problem? Please describe.**
https://github.com/aws-amplify/amplify-js/issues/1770
Next, Nuxt, and SSR solutions are more and more common.

**Describe the solution you'd like**
A working Auth solution for server side and client side.

**Describe alternatives you've considered**
It's hard to get a complete auth solution only for client side (but possible).

**Additional context**
I dont upgrade my version often, but it seems that the polyfill is sometimes here, sometimes not.
window variable breaks a lot of things server side. It's not a viable solution.

**Comment by ericclemmons** [comment]
Closed via #6146 (SSR support).

Amplify works with Next.js!
