### ISSUE TITLE
Pinpoint connection errors appear in log when pinpoint is disabled

### ISSUE THREAD

**Issue by samparnell** [aws-amplify/amplify-js#2057]
**Describe the bug**
I had pinpoint disabled on my web app, both in the local aws-exports.js file and on the mobile hub backend. I consistently get errors in the developer console with pinpoint still trying to connect. When disabled it should not do anything. 

AWS Support Case Id: 5386646321 

Gist of console log: https://gist.github.com/samparnell/70cb3023e5633a126e82002ae43c7ee3

**To Reproduce**
1. Start an app with pinpoint disabled
2. Open a web browser
3. Check logs in browser
4. 4-5 errors showing 400 (Bad Request)

**Additional context**
This has been happening for several months. Confirmed on the most recent version 1.1.9.

**Comment by haverchuck** [comment]
@samparnell I am not sure how you are disabling the aws-exports file, but you might want to try disabling it by manually passing ` { Analytics: {disabled} } ` to the `Amplify.configure` method.  

Here is an example (Angular frontend, main.js file) where I am using the aws-exports file along with a manaully passed value to stop this error.

```
import Amplify from 'aws-amplify';
import amplify from './aws-exports';
Amplify.configure({
  ...amplify,
  Analytics: {
    disabled: true
  }
});
```

If this works for you but you still want to fix it via aws-exports alone (which is totally understandable!), please let us know what key you are using in the aws-exports file.

**Comment by samparnell** [comment]
Confirming that setting it manually does appear to correctly disable pinpoint and prevent the errors.
