### ISSUE TITLE
No Auth module registered in Amplify 

### ISSUE THREAD

**Issue by tafelito** [aws-amplify/amplify-js#2058]
**Describe the bug**
Same issue as #1977 and maybe related to #1761. Both issues are closed so I opened a new one.

I'm still having the same issue reported there. Problem seems to be on this line 

https://github.com/aws-amplify/amplify-js/blob/94b6116d80911be862f9605b85aaef34616dd217/packages/core/src/Credentials.ts#L85

Amplify.Auth is null. 

**To Reproduce**
Same as https://github.com/aws-amplify/amplify-js/issues/1761#issuecomment-424834490

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser [any]

**Additional context**
I'm using  `"@aws-amplify/auth": "^1.2.9", @aws-amplify/storage": "^1.0.18"`

**Comment by haverchuck** [comment]
@tafelito Are you importing the Auth package before using Storage?

**Comment by tafelito** [comment]
@haverchuck I just updated both auth `(1.2.15)` and storage `(1.0.25)` packages and now the error seems to be different

![image](https://user-images.githubusercontent.com/5973652/51393177-16a1ce00-1b05-11e9-94b2-70d20df87d95.png)

The error is because the list of _pluggables list is empty, but as you see here, it looks like the pluggable is inside the vault
![image](https://user-images.githubusercontent.com/5973652/51393520-df7fec80-1b05-11e9-82df-dd0e7eccdd9f.png)

**Comment by kldeb** [comment]
what was the solution?
