### ISSUE TITLE
Usage of attribute sync in return value after login: user.pool.storage.sync and user.storage.sync

### ISSUE THREAD

**Issue by truongluong1314520** [aws-amplify/amplify-js#2062]
** Which Category is your question related to? **
AWS Sync DB

** What AWS Services are you utilizing? **
AWS Cognito

** Provide additional details e.g. code snippets **
Hi AWS-Amplify

I make a login function and sync data between AWS Cognito and my mobile app. My mobile app is developed under React Native.

I am able to make a signIn to AWS Cognito using aws-amplify

    Auth.signIn(email, password)
        .then(user => {

            success(user);
        })
        .catch(error => {

            fail(error);
        });

Inside the `user` attribute, I see the function `sync` in `user.pool.storage.sync` and `user.storage.sync`

![screen shot 2018-11-07 at 4 03 57 pm](https://user-images.githubusercontent.com/32918401/48121169-cdccce00-e2a6-11e8-851f-632af6d95889.png)

My questions: 
1/ What is the that function? Is it used for sync user data like: image, video,... from AWS Cognito storage
2/ How do I use it?

Thank you in advance!

**Comment by haverchuck** [comment]
@truongluong1314520 - I believe these particular functions are related to local storage, not S3 or other types of content storage.  Amplify uses these under the covers and I supposed you COULD try to use as well, but you might want to instead check out Amplify's [Hub](https://aws-amplify.github.io/docs/js/hub) feature.

I'm closing this issue for now - feel free to reopen.
