### ISSUE TITLE
hideDefaults in Vue SignUp component is not implemented

### ISSUE THREAD

**Issue by lucasmike** [aws-amplify/amplify-js#2063]
**Describe the bug**
As per the documentation, the **Vue SignUp** component is supposed to implement `hideDefaults` boolean value which enables to switch off displaying all default fields on the sign up form. 

I don't think this functionality is implemented in the component.

**To Reproduce**
1. set hideDefaults to true
2. provide your own list of fields in the signUpFields object
3. you will see that default fields are still displayed

**Expected behavior**
When `hideDefaults: true`, default fields should not be forced into the field object. The piece of code responsible for this is below. 

I believe what is missing is another conditional statement to execute this code below only when `hideDefaults == false`

```js
        defaults.signUpFields.forEach((f, i) => {
          const matchKey = this.signUpConfig.signUpFields.findIndex((d) => {
            return d.key === f.key;
          });
          if (matchKey === -1) {
            this.signUpConfig.signUpFields.push(f);
          }
        });
```
        

**Screenshots**
N/A

**Additional context**
hideDefaults does not seem to be implemented in the props and in the logic of the component

**Comment by haverchuck** [comment]
@lucasmike  Thanks for catching this!  A fix is forthcoming.

**Comment by jbouse** [comment]
Fix looks good to me... Hopefully we can get it released.

**Comment by haverchuck** [comment]
@jbouse  - The fix is currently available via `npm install aws-amplify-vue@unstable`.
