### ISSUE TITLE
required field attribute is not properly implemented in Vue SignUp component

### ISSUE THREAD

**Issue by lucasmike** [aws-amplify/amplify-js#2064]
**Describe the bug**
When the `user` object is created with new values to sign up a new user, values for all default attributes are assigned to the object even if some of the attributes have a `required` property set to `false` and no input was provided in the form.

This means that it is impossible to sign up new users unless all default fields are filled in. This is causing an issue when you don't want to collect mobile phone numbers. If you set a mobile phone number `required` to `false`, and the user leaves this field blank in the registration form, the code will still try to submit an invalid phone number to Cognito.

**To Reproduce**
1. Set `required` for phone number to `false`
2. Try to register a new user without providing a phone number

**Expected behavior**
When `required: false` for a phone number, this field should not be submitted to Cognito when creating a new user

**Screenshots**
The issue is with the following code:

```js
      this.options.signUpFields.forEach((e) => {
        if (e.key === 'username') {
          user.username = e.value
        } else if (e.key === 'password') {
          user.password = e.value
        } else if (e.key === 'phone_number') {
          user.attributes.phone_number = `+${this.countryCode}${e.value}`
        } else {
          user.attributes[e.key] = e.value;
        };
      })
```
The code above assign `user.attributes.phone_number = `+${this.countryCode}${e.value}`` regardless of the `required flag` so when no phone number is provided, an invalid value for this field is submitted to Cognito

**Comment by jbouse** [comment]
TH PR on this looks like a clean and elegant solution to the problem. Hopefully it can get merged and released so I can actually make use of the components in my project.

**Comment by haverchuck** [comment]
@jbouse  @lucasmike  - Thanks for your comments.  The PR is currently merged into our unstable branch.  It can be installed via `npm install aws-amplify-vue@unstable`.  Look for it to make it's way into the main release branch soon.
