### ISSUE TITLE
New Error: Token is not from a supported provider of this identity pool

### ISSUE THREAD

**Issue by JasonLunsford** [aws-amplify/amplify-js#2067]
Been using Amplify without any trouble the past several days. No changes were made to the configuration (customized Amplify configuration, not using the default config file), but all of a sudden now seeing the error "Token is not from a supported provider of this identity pool". Triple checked all IDs, LoginKey, and verified the SignIn process works. Amplify appears to be working fine, other than this issue.

Not sure how to troubleshoot from here. Please help?

**Comment by undefobj** [comment]
This could be an issue with the configured client IDs in your Cognito Identity Pool not matching up with the app ID in the Cognito User Pool.

**Comment by haverchuck** [comment]
@JasonLunsford -  When you look at the identity pool via the Cognito Console -> Manage Identity Pools -> Edit Identity Pool -> Authorization Providers, do you see the user pool info in the Cognito tab?

Also, are you using any third party providers such as Facebook or Google?

**Comment by JasonLunsford** [comment]
@haverchuck - Looks like I was wrong to suggest everyone on my end was squared away. Inspired by your comment I took a really careful look at the Authorization Provider tab and noticed we have the wrong Client ID's (and in one case the wrong User Pool ID) associated. I'll update these values and see if the error messages go away.

**Comment by JasonLunsford** [comment]
@haverchuck - that was it! Wrong Client and User Pool IDs associated with the Identity Pool. Thank you very much for the help.
