### ISSUE TITLE
amplify push - process never completes, no error

### ISSUE THREAD

**Issue by kristianmandrup** [aws-amplify/amplify-js#2072]
Trying to get the appsync app working. 

What I did:

- `amplify init`
- `aws configure` using the key and secret from AWS console (IAM user)
- `amplify add api` using default Blog API
- `amplify push` gets stuck after compiling... can't even Ctrl-C to terminate the process. Need to shut down my Terminal

**Comment by 4thjuly** [comment]
I have maybe the same issue (or maybe different).

Following Getting Started (for React Native) on a Mac:

amplify init (works)
amplify add analytics (using defaults, works)
amplify push (spinning forever at "Updating resources in the cloud")

The last few lines in the console before spinning: 
```
CREATE_IN_PROGRESS PinpointFunction                                                  AWS::Lambda::Function      
CREATE_IN_PROGRESS PinpointFunction                                                  AWS::Lambda::Function      
CREATE_COMPLETE    PinpointFunction                                                  AWS::Lambda::Function     
CREATE_IN_PROGRESS PinpointFunctionOutputs                                           Custom::LambdaCallout  
CREATE_COMPLETE    authcognito9af98dfd                                               AWS::CloudFormation::Stack 
```

**Comment by kaustavghosh06** [comment]
@4thjuly This issue should be fixed with the latest version of the CLI.
