### ISSUE TITLE
[Storage] how to access content-type on get

### ISSUE THREAD

**Issue by goatandsheep** [aws-amplify/amplify-js#2074]
**Which Category is your question related to?**

Storage

**What AWS Services are you utilizing?**

S3

**Provide additional details e.g. code snippets**

I'm using Storage.get(). everything is working. however, when the response comes back with the signed URL, how do I also get the `Content-type` from S3?

**Comment by nidsharm** [comment]
@goatandsheep , Storage.get only returns a signed url if you don't set the option {download: true} in the API options. You could do that and get the object metadata with it.

**Comment by jordanranz** [comment]
The question was answered. I am going to close this issue now. Please reopen if you have any related questions or concerns.
