### ISSUE TITLE
Customize AWS Amplify Authenticator UI for Angular

### ISSUE THREAD

**Issue by hoang-innomizetech** [aws-amplify/amplify-js#2075]
**Is your feature request related to a problem? Please describe.**
I want to use this authenticator to our project to reduce our development time to develop the comment. However, currently, this authenticator for Angular does not allow to customize. There is no input parameter.

**Describe the solution you'd like**
The Authenticator should provide an input prop for the component so so that we can customize authenticator UI such as rename label, button text, show/hide feature (e.g. Sign Up, Reset password, etc.)

**Comment by karlmosenbacher** [comment]
https://github.com/aws-amplify/amplify-js/issues/1911

**Comment by hoang-innomizetech** [comment]
@karlmosenbacher  Thank you. Hope we can get this updated soon.

**Comment by hoang-innomizetech** [comment]
@mechero I don't think this is supported

**Comment by mechero** [comment]
Well, I saw once the updated docs as per described [in the linked comment](https://github.com/aws-amplify/amplify-js/issues/1911#issuecomment-437090097), detailing the fields to include in the sign-up form. But I can't find them anymore.

**Comment by hoang-innomizetech** [comment]
@mechero Yeah, this is for React not Angular

**Comment by holtc** [comment]
@mechero is [this](https://aws-amplify.github.io/docs/js/angular) what you are looking for?

**Comment by mechero** [comment]
@holtc yes, that's it, thanks! I'll give it a try

**Comment by jordanranz** [comment]
FYI, we have started an RFC discussion for a proposed Amplify UI Component refactor to increase customizability and flexibility for our components. Please feel free to add any additional comments to the following issue:

https://github.com/aws-amplify/amplify-js/issues/3279

**Comment by jordanranz** [comment]
You can customize the `formFields` in the new UI components.

Here are the docs for this: https://docs.amplify.aws/ui/auth/authenticator/q/framework/angular#custom-form-fields

If there are any further request, please go ahead and open a new issue in this repo.
