### ISSUE TITLE
Auth token is invalid after Auth.signOut()... but only if Storage.get() was already called?

### ISSUE THREAD

**Issue by LeoTheMighty** [aws-amplify/amplify-js#2081]
** Which Category is your question related to? **
Authentication Token generation

** What AWS Services are you utilizing? **
Auth and Storage

** Provide additional details e.g. code snippets **
So we have a ReactJS PWA and we are trying to display images from AWS S3. We checked the S3 keys and they are valid, we are using other AWS services that work completely fine all the time (like app sync GraphQL queries and Lambda invocations), but Storage.get() is being problematic. 

Storage.get() works if you call it after refreshing for the first time, but the problem arises after we call Auth.signOut() and we log back in. No matter who we log into, Storage.get() always fails, giving us a 403 Forbidden error. We have checked the HTTP requests going out and they are the same, save for the updated authentication token. We don't know why this is the issue because when we do Auth.signIn() from the get go, it works perfectly. Evidently, it must be an issue with Auth.signOut specifically...

We call the Storage.get() without any options, the Auth.signIn() without any options, and the Auth.signOut() with options {global: true} (we switched this to global: false with no avail as well). 

Our config looks like this:
```js
import Amplify from "aws-amplify";

function setupAWS() {
    let myAppConfig = {
        'aws_appsync_authenticationType': 'AMAZON_COGNITO_USER_POOLS',
    };

    Amplify.configure(myAppConfig);

    Amplify.configure({
        API: {
            graphql_endpoint: 'our_graphql_endpoint',
            graphql_endpoint_iam_region: 'our_graphql_region'
        }
    });

    Amplify.configure({
        Auth: {

            // REQUIRED only for Federated Authentication - Amazon Cognito Identity Pool ID
            identityPoolId: 'our_identity_pool_ID',

            // REQUIRED - Amazon Cognito Region
            region: 'our_cognito_region',


            // OPTIONAL - Amazon Cognito User Pool ID
            userPoolId: 'our_user_pool_ID',

            // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
            userPoolWebClientId: 'our_pool_web_client_ID',

            // OPTIONAL - Enforce user authentication prior to accessing AWS resources or not
            mandatorySignIn: true,


            authenticationFlowType: 'USER_PASSWORD_AUTH'
        },
        Storage: {
            bucket: 'our_storage_bucket', //REQUIRED -  Amazon S3 bucket
            region: 'our_storage_region', //OPTIONAL -  Amazon service region
            identityPoolId: 'our_identity_pool_ID', //Specify your identityPoolId for Auth and Unauth access to your bucket;
        }
    });

    var AWS = require('aws-sdk');

    AWS.config.update({region: 'our_region'});
    AWS.config.credentials = new AWS.CognitoIdentityCredentials({IdentityPoolId: 'our_identity_pool_ID'});
}

export default setupAWS;
```

Again, this happens whenever we use Auth.signOut() and it isn't fixed until we refresh the page again. 

Any help on this issue would be greatly appreciated!
~ Leo

**Comment by mlabieniec** [comment]
The reason may be related to your instantiation or the additional sdk at the bottom there. Is there a reason you are doing that? Amplify will do this, bootstrap those credentials and set the region based on the configuration you send to Amplify.configure. If you do this you will end up with two different Sdks running since Amplify bootstraps one and then you are again here.

**Comment by LeoTheMighty** [comment]
Hmm... Okay I tried getting our AWSConfig.js to the bare bones that it possibly worked, but it still doesn't work. Here's the updated file

```js
import Amplify from "aws-amplify";

function setupAWS() {
    Amplify.configure({
        'aws_appsync_authenticationType': 'AMAZON_COGNITO_USER_POOLS',
    });

    Amplify.configure({
        API: {
            graphql_endpoint: 'our_graph_ql_endpoint',
            graphql_endpoint_iam_region: 'our_graph_ql_iam_region'
        },
        Auth: {
            // REQUIRED only for Federated Authentication - Amazon Cognito Identity Pool ID
            identityPoolId: 'our_identity_pool_ID',

            // REQUIRED - Amazon Cognito Region
            region: 'our_cognito_region',

            // OPTIONAL - Amazon Cognito User Pool ID
            userPoolId: 'our_cognito_user_pool_ID',

            // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
            userPoolWebClientId: 'our_user_pool_web_client_ID',
        },
        Storage: {
            bucket: 'our_bucket_name', //REQUIRED -  Amazon S3 bucket
        }
    });
}

export default setupAWS;
```

I looked through the rest of the files too to make sure there isn't anywhere else we're accidentally configuring, but we simply call this function whenever we need to use a service.

**Comment by LeoTheMighty** [comment]
UPDATE: It seems to always happen when we try to do `Storage.get()` on the same `imgKey` twice and in between those two calls, we use `Auth.signOut()`. We always get a 403 Forbidden message when it comes up. So our workaround has been to cache the images so we don't have to grab them twice. Obviously, this isn't ideal, because there still seems to be a fundamental problem (potentially), but it works for now.

Thanks!

**Comment by LeoTheMighty** [comment]
UPDATE 2: Where `Storage.get()` would fail, `Storage.put()` also fails with an "ACCESS DENIED" message.

**Comment by nidsharm** [comment]
@LeoTheMighty , I tried reproducing the issue, but my Storage.put and Storage.get work fine after SignOut too (I tried it with the withAuthenticator component). Could you please tell us what version of amplify, storage and auth you are using, so I could try those to see if we can replicate this and get the root cause?

**Comment by LeoTheMighty** [comment]
@nidsharm We are not using withAuthenticator, we implement the authentication manually, using the Auth module from Amplify. Here is what our sign out looks like.

```js
import { Auth } from "aws-amplify";

Auth.signOut({global: true}).then((data) => {
    handle(data)
}).catch((error) => {
    handle(error);
});
```

using `npm show aws-amplify version`, we get `1.1.10`.

Let me know if any of that helps!

**Comment by powerful23** [comment]
@LeoTheMighty Hi, sorry for the late response. I tried to reproduce your issue by do a `Storage.get()`, log out, log back in and `Storage.get()` again but no 403 error happens. Could you verify that you still have this issue with the latest version? And if applicable, please provide more info like the debugging messages. To turn on the the debug mode, putting `window.LOG_LEVEL='DEBUG'` in the code. Thanks!
