### ISSUE TITLE
IE11 beforeunload causes system alert popup

### ISSUE THREAD

**Issue by hutch120** [aws-amplify/amplify-js#2088]
**Describe the bug**
In IE11, if you return anything from beforeunload, it triggers an alert. `Are you sure you want to leave this page?`

**To Reproduce**
1. Load a page in IE11 with this module
2. Open the console (F12)
3. Search debugger source for `_trackBeforeUnload` 
4. Click on file `SessionTracker.js`
5. Put a break point on `switch (_b.label) {` in function `SessionTracker.prototype._trackBeforeUnload = function () {`
6. Try to close IE
7. You should see it hit that breakpoint.
8. Let it run (F8), and it should popup the alert box.

**Expected behavior**
No popup is displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/1034955/48328754-993b8680-e699-11e8-9d3e-e5f601c10895.png)

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser: IE 11
 - Version: 11.345.17134.0

**Possible solution**
Psudo code
```
 SessionTracker.prototype._trackBeforeUnload = function () {
    if (IE11) return
    ...
```

**Comment by powerful23** [comment]
@hutch120 Hi sorry to be late. Can you try turn off the autotracking in Analytics module and see if it happens again. Put `Analytics.configure({ autoSessionRecord: false });` right after configuring Amplify.

I also checked the code but didn't find any return statement in the `beforeunload` listener, not sure if it's the cause: https://github.com/aws-amplify/amplify-js/blob/master/packages/analytics/src/trackers/SessionTracker.ts#L104

**Comment by powerful23** [comment]
@hutch120 I see, although not in the source code but actually in the transpiled js code there is a return statement. Will try to find a solution.

**Comment by hutch120** [comment]
@powerful23 Thanks!! Adding the Analytics section to my configuration object fixed the issue. 

```
import Amplify, { Auth, Storage } from 'aws-amplify'

var amplifyConfig = {
  Auth: {
    identityPoolId: '...',
    region: '...',
    userPoolId: '...',
    userPoolWebClientId: '...'
  },
  Storage: {
    bucket: '...',
    region: '...'
  },
  Analytics: {
    autoSessionRecord: false
  }
}

Amplify.configure(amplifyConfig)
```

@CodingToBeWithHer See config above.

This is an issue in it's own right, but it does remind me of a previous issue I raised (for another project)... https://github.com/aws-amplify/amplify-js/issues/1416 where you recommended including just the two specific modules, that may have been a work around for this issue.

```
import Auth from '@aws-amplify/auth';
import Storage from '@aws-amplify/storage';

Auth.configure(); // in order to login and get credentials;
Storage.configure();
```
