### ISSUE TITLE
How to add a signup using LinkedIn?

### ISSUE THREAD

**Issue by nomadus** [aws-amplify/amplify-js#2091]
How could I add a user signup by using LinkedIn account? I am currently using HostedUI.

**Comment by haverchuck** [comment]
@nomadus: Have you tried [integrating Cognito with Auth0](https://auth0.com/docs/integrations/integrating-auth0-amazon-cognito-mobile-apps)?

**Comment by powerful23** [comment]
Closing the issue due to no further response. Feel free to reopen if you still have this issue.
