### ISSUE TITLE
"No userPool" error message with aws-amplify-angular on AOT build

### ISSUE THREAD

**Issue by hoang-innomizetech** [aws-amplify/amplify-js#2094]
I am getting "No userPool" on production mode built with AOT mode for Angular project. I am using the latest amplify and amplify-angular version.

ere is my config file ```aws-exports.ts```
```ts
export default {
    Auth: {
        // // REQUIRED only for Federated Authentication - Amazon Cognito Identity Pool ID
        // // identityPoolId: 'XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab',

        // // REQUIRED - Amazon Cognito Region
        region: 'xxxxx',

        // // OPTIONAL - Amazon Cognito Federated Identity Pool Region
        // // Required only if it's different from Amazon Cognito Region
        // // identityPoolRegion: 'XX-XXXX-X',

        // // OPTIONAL - Amazon Cognito User Pool ID
        userPoolId: 'xxxxx',

        // // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
        userPoolWebClientId: 'dddd'
    }
}
```

this is my code from ```app.module.ts```
the below code will throw this error with development mode and AOT mode
```ts
import Amplify from '@aws-amplify/core';
import Auth from '@aws-amplify/auth';
import * as amplify from './aws-exports';

console.log('amplify config', amplify);

Amplify.configure(amplify);
```

this configuration works fine in development mode but not when building bundler files with AOT mode
```ts
import Amplify from '@aws-amplify/core';
import Auth from '@aws-amplify/auth';
import amplify from './aws-exports';

console.log('amplify config', amplify);

Amplify.configure(amplify);

```

I set the Amplify log level to DEBUG and here is what I can see on the console

Development mode
![image](https://user-images.githubusercontent.com/43955692/48388096-bec4a080-e72a-11e8-88f9-f864ab5d5a63.png)

Production mode (AOT build)
![image](https://user-images.githubusercontent.com/43955692/48388141-e87dc780-e72a-11e8-961e-db357bbb1ac3.png)

**[DEBUG] 53:38.162 Auth - Create Auth Instance - the Auth instance is initialized with config param is null and the configure function is not called to configure Auth instance likes development mode (this log entry does not appear in the development mode)**

I am using this starter kit to try the Amplify so you can try to apply and replicate this issue 
https://github.com/gdi2290/angular-starter

We cannot go-live without this issue fixed, I hope someone has encountered this issue and figured out the root cause and get it fixed. 

 "aws-amplify": "1.1.9",
 "aws-amplify-angular": "2.0.12",
 "@angular": "7.0.2"

**Comment by hoang-innomizetech** [comment]
Related #1372

**Comment by haverchuck** [comment]
@hoang-innomizetech - thanks for posting this.  We are investigating.

**Comment by haverchuck** [comment]
@hoang-innomizetech  - Can you please try removing the following code from 'app.module'...

```
import Amplify from '@aws-amplify/core';
import Auth from '@aws-amplify/auth';
import amplify from './aws-exports';

console.log('amplify config', amplify);

Amplify.configure(amplify);
```

...and then placing the following in main.ts?

```
import Amplify from '@aws-amplify/core';
import amplify from './aws-exports';
Amplify.configure(amplify);
```

Please test that it let us know the result.

**Comment by hoang-innomizetech** [comment]
@haverchuck  Thank you for your information. Previously, i have added amplify configure to main.ts module and got some issue, so i have moved to another module. 

But I have moved back to main.ts module and it is working now. Thanks
