### ISSUE TITLE
Error: rxjs/Subject"' has no exported member 'Subject'

### ISSUE THREAD

**Issue by chenji28** [aws-amplify/amplify-js#2103]
**Describe the bug**
"aws-amplify-angular": "^2.0.13" has a bug in src/providers/auth.decorator.ts 
import { Subject } from 'rxjs/Subject';
should be 
import { Subject } from 'rxjs';

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by haverchuck** [comment]
@chenji28 -  I believe this has been fixed on a recent version.  Please feel free to reopen if you continue to experience the issue.

**Comment by haverchuck** [comment]
@chenji28 A fix for this has been merged into our @unstable tag in npm, and should be available in our main build in a while.

**Comment by cptflammin** [comment]
@haverchuck 

* In 1.1.25 [OK, fixed]

`import { Subject, Observable } from 'rxjs';`

* In >1.1.26 [bug strikes again !]

`import { Subject } from 'rxjs/Subject';`

**Comment by wizardbluebolt** [comment]
Actually it appears to be aws-amplify-angular 3.0.1.  aws-amplify-angular 2.1.12 with aws-amplify 1.1.26 does not show this error.

**Comment by DavidHospital** [comment]
It appears that this error was reintroduced in commit: 86310899b68a537f050e14da68d3649ce7476cfb.
