### ISSUE TITLE
Provide a function to customize error message

### ISSUE THREAD

**Issue by hoang-innomizetech** [aws-amplify/amplify-js#2104]
When an error occurs during sign in, I wanted to customize the error message to display on UI. 

For an example, when signing in I got below error from Cognito User Pool
{"__type":"UserNotFoundException","message":"UserMigration failed with error Username or password is incorrect.."}

![image](https://user-images.githubusercontent.com/43955692/48461272-80e87a80-e805-11e8-8fd2-4a19aeda2037.png)

I wanted to change error message such as remove **UserMigration failed with error** text or using locale (ref #867)

**Comment by TOPS-Aman** [comment]
Any update on this?

**Comment by hoang-innomizetech** [comment]
@elorzafe oza could you please let us know the status of this issue?

**Comment by elorzafe** [comment]
@hoang-innomizetech Sorry for the late response, but this is still on our backlog.

**Comment by eanntuan** [comment]
Is there any update on this feature request? Also - would be extremely helpful for the iOS SDK. Customizing error messaging to help us guide users is extremely important for our app!

**Comment by crcommons** [comment]
@eanntuan as a hack, you could customize your error messages using the i18n translations instead. Write your custom error messages as values with the existing error messages as the keys, and then wire up amplify's i18n module.

**Comment by jordanranz** [comment]
FYI, we have started an RFC discussion for a proposed Amplify UI Component refactor to increase customizability and flexibility for our components. Please feel free to add any additional comments to the following issue:

https://github.com/aws-amplify/amplify-js/issues/3279

**Comment by satishmolletipipra** [comment]
@elorzafe Any update on this feature(customize error message) and while signing into the application we are not showing the loader for the user. currently i didn't find any property or function handle the loader feature while login. can you please help me on these two issues.

**Comment by hoang-innomizetech** [comment]
For over 6 months UI refactor epic just completed 30%, so we might need to wait for one more year to get this change released

**Comment by nihp** [comment]
I need to customize most of the error messages.

For eg) I got network error in UI. 

Message needs to tell, Turn on your network connection to proceed the process(May be sign in, sign up, Forgot password or any thing)

Any update on this?

Or can anyne suggest any good way to customize the authentication screens

**Comment by bmilesp** [comment]
Is there a way to maybe capture the errors via eventbus? 

If so you could maybe use I18n.get() the incoming message to translate.

**Comment by satishmolletipipra** [comment]
is there any way to capture and customize the error message in Amplify Angular.
