### ISSUE TITLE
Storing and managing tokens on iOS Keychain

### ISSUE THREAD

**Issue by GutteApps** [aws-amplify/amplify-js#2105]
** Which Category is your question related to? **
Storing and managing JWT tokens

** What AWS Services are you utilizing? **
aws-amplify/auth
amazon-cognito-identity-js

** Provide additional details e.g. code snippets **

Trying to provide my own storage (iOS Keychain) as described here: https://aws-amplify.github.io/docs/js/authentication

Not sure how to implement it since iOS keychain store/ retrieve is async.

**Comment by powerful23** [comment]
@GutteApps hello, do you mean you want to configure the `storage` option in the Auth module? https://aws-amplify.github.io/docs/js/authentication#managing-security-tokens

**Comment by powerful23** [comment]
Closing this issue due to no further response. Feel free to reopen if you still have this issue.

**Comment by GutteApps** [comment]
@powerful23 yes, I'd like to configure the storage option to use KeyChain. also, I need the updated token to be available also from the native (swift) side. can you advise on what's the best way to achieve that.

**Comment by powerful23** [comment]
@GutteApps you can make it as a storage object and pass it into the auth module: https://aws-amplify.github.io/docs/js/authentication#managing-security-tokens

**Comment by akoshek** [comment]
@GutteApps did you succeed to use the keychain? If yes, Can you tell me what is the configuration to be able to reach this implementation
