### ISSUE TITLE
ReactJS - Auth - missing I18n support for toasts

### ISSUE THREAD

**Issue by jonasao** [aws-amplify/amplify-js#2106]
**The bug**
I have translated most of the text strings for the React.js GUI-components to Norwegian, but when attempting to log on to our solution with a user that has expired, the following text appears: "User account has expired, it must be reset by an administrator." This text appear in English, but should have been appearing in Norwegian as I have included the text in our I18n file containing the rest of the translated strings. 

To me it seems that texts that appears within a Toast, as a result of a call to AWS Cognito does not support translation.

**Reproduce**
1. Create a new authentication application based on React.js and AWS Amplify.
2. Include texts for a foreign language, e.g. Norwegian: 
```
const norwegianTexts = {
    'Username': "Brukernavn",
    'Password': "Passord",
    'Create account': 'Opprett konto',
    'Reset password': 'Nullstill passord',
    'Sign in to your account': 'Logg inn med din brukerkonto',    
    'Sign In': 'Logg på',
    'Enter your username': 'Skriv inn ditt brukernavn',
    'Enter your password': 'Skriv inn ditt passord',
    'Forget your password? ': 'Glemt passord? ',
    'No account? ': 'Ingen konto? ',
    'Username cannot be empty': 'Du må fylle inn et brukernavn',
    'User does not exist': 'Brukeren eksisterer ikke',
    'Incorrect username or password': 'Feil brukernavn/passord',
    'Reset your password': 'Nullstill passordet',
    'Back to Sign In': 'Tilbake',
    'Send Code': 'Send kode',
    'Create a new account': 'Opprett ny konto',
    'Create a username': 'Skriv inn brukernavn',
    'Create a password': 'Skriv inn passordet',
    'Email Address': 'E-post adresse',
    'Phone Number': 'Telefonnummer',
    'Create Account': 'Opprett konto',
    'Have an account? ': 'Har du allerede en konto? ',
    'Sign in': 'Logg på',
    'Password cannot be empty': 'Feltet "Passord" må ha en verdi',
    'Invalid password format': 'Ugyldig passordformat',
    'Attribute value for phone_number must not be null': 'Feltet "Telefonnummer" må ha en verdi',
    'Invalid email address format.': 'Ugyldig e-post adresse format',
    'Confirm Sign Up': 'Bekreft registrering',
    'Confirmation Code': 'Bekreftelseskode',
    'Enter your code': 'Skriv inn bekreftelseskoden',
    'Lost your code? ': 'Mistet koden? ',
    'Resend Code': 'Send kode på nytt',
    'Confirm': 'Bekreft',
    'Invalid verification code provided, please try again.': 'Ugyldig verifiseringskode, vennligst forsøk på nytt.',
    'Sign In with Facebook': 'Logg på med Facebook',
    'Family name': 'Etternavn',
    'Given name': 'Fornavn',
    'or': 'eller',
    'User account has expired, it must be reset by an administrator': 'Kontoen er utløpt, og må nullstilles av en administrator.'
  };
```
NOTE: The last line appears inside the toast, and is not translated to Norwegian.
3. Attempt to log on with a user by typing in his/hers username and password for a user that has expired.
4. The text on the last line in the example above will appear in English instead of Norwegian.

**Expected behavior**
I expected the text string to appear in Norwegian, when implemented in the same manner as the rest of the GUI-related, translated, text-strings.

**Screenshots**
![screenshot from 2018-11-14 14-47-19](https://user-images.githubusercontent.com/8456082/48486674-7ab1c880-e81c-11e8-8887-b303afcb839c.png)

**Desktop (please complete the following information):**
Irrelevant for this bug.

**Smartphone (please complete the following information):**
Irrelevant for this bug.

**Comment by powerful23** [comment]
@jonasao Hey I noticed that you might miss the last token which is `.`
Can you try `'User account has expired, it must be reset by an administrator.': 'Kontoen er utløpt, og må nullstilles av en administrator.'`

**Comment by powerful23** [comment]
Closing this issue due to no further response. Feel free to reopen if you still have this issue.
