### ISSUE TITLE
Improve async consistency and types

### ISSUE THREAD

**Issue by madroneropaulo** [aws-amplify/amplify-js#2109]
**Is your feature request related to a problem? Please describe.**
The CognitoUser does NOT have typescript types, this makes it difficult to work with the returned CognitoUser object when a request is made. On top of that, the way to make requests is not consistent, so for example, `Auth.signIn` returns a promise to get the call result, whereas `cognitoUser.completeNewPasswordChallenge` needs an object with success and failure callbacks.

**Describe the solution you'd like**
Code should be consistent so it becomes intuitive. it's a good practice.
Is there any reason why CognitoUser and all the other exports from `amazon-cognito-identity-js` don't have types?

**Comment by jimblanc** [comment]
We have published an RFC on our plan for improving TypeScript support in Amplify JS & would love to get your feedback & suggestions!

[RFC: Amplify JS TypeScript Improvements](https://github.com/aws-amplify/amplify-js/issues/11113)

**Comment by cwomack** [comment]
The developer preview for v6 of Amplify has officially been released with updates to the Auth package, better type support, and much more! Please check out our [announcement](https://aws.amazon.com/blogs/mobile/aws-amplify-javascripts-new-developer-preview-with-reduced-bundle-sizes-improved-typescript-and-next-js-support/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=238088647) and updated [documentation](https://docs.amplify.aws/lib-v1/project-setup/create-application/q/platform/js/) to see what has changed. Please take note that for this issue in particular, the confirmSignIn() method is imported directly in v6 and replaced the Auth.completeNewPassword() method.

We believe this issue should be resolved within the dev preview and upcoming General Availability for Amplify v6, but let us know with a comment if there are further issues.

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
