### ISSUE TITLE
no such file or directory: ‘[userhome]/Library/Developer/Xcode/DerivedData/myMoleMobileApp-ebujizzrluykvrcevmttzifhpxqm/Build/Products/Debug-iphonesimulator/libRNAWSCognito.a'

### ISSUE THREAD

**Issue by wolfag** [aws-amplify/amplify-js#2110]
**Describe the bug**

**To Reproduce**
 `Build on xcode 10`
**Environment:**

  - React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
      Memory: 38.22 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        API Levels: 23, 24, 26, 27, 28
        Build Tools: 23.0.1, 26.0.1, 26.0.3, 27.0.3, 28.0.3
        System Images: android-26 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.0 => 0.57.0
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Error message**
`no such file or directory: ‘[userhome]/Library/Developer/Xcode/DerivedData/myMoleMobileApp-ebujizzrluykvrcevmttzifhpxqm/Build/Products/Debug-iphonesimulator/libRNAWSCognito.a'`

**Please help to fix**

**Comment by elorzafe** [comment]
@wolfag Which version of amplify are you using?

**Comment by powerful23** [comment]
@wolfag did you run `react-native link amazon-cognito-identity-js` before starting the app?

**Comment by wolfag** [comment]
I re-link and it work fine. Please close this ticket.
Thanks

**Comment by wolfag** [comment]
I re-link and it work fine. Thanks
