### ISSUE TITLE
Cross-service transaction

### ISSUE THREAD

**Issue by YikSanChan** [aws-amplify/amplify-js#2111]
**Is your feature request related to a problem? Please describe.**
I have an app, in which I want to upload an image as part of a form and submit the form to create an item. Since AWS amplify stores files via Storage service first and then it saves the created item (via GraphQL backend in my case) into DynamoDB, if the first step succeeds and the second step fails, it is not ideal.

**Describe the solution you'd like**
Cross-service transactions between storage, database, etc.

**Describe alternatives you've considered**
The problem is hard to solve in client code I believe.

**Comment by elorzafe** [comment]
@YikSanChan thanks for your feedback. I labeled this as a feature-request

**Comment by baffleinc** [comment]
Is this a validation issue? I would try to upload the file first then if successful, validate the form and push to graphql. S3 succeeding/failing is essentially your server side validation. 

If you wanted to track the file against the particular user you could use versioning to create a progressive version of the entry. 

Finally it can help to create an S3Object type in your scema to link the form object and file.

**Comment by YikSanChan** [comment]
> Is this a validation issue? I would try to upload the file first then if successful, validate the form and push to graphql. S3 succeeding/failing is essentially your server side validation.
> 
> If you wanted to track the file against the particular user you could use versioning to create a progressive version of the entry.
> 
> Finally it can help to create an S3Object type in your scema to link the form object and file.

Thanks for the reply! No necessarily a validation rule, I simply want to make sure the following case doesn't appear: After hitting the "submit form" button, the file is uploaded to storage service, then when I try to write the whole form to dynamodb it fails. As a result, I have an orphan file in the storage. 

Yes, these are all the things I can do in client side, just like NoSQL users can always hack around to guarantee some level of transaction support. But this doesn't change the fact that Google Spanner / [TiDB](https://github.com/pingcap/tidb) provides a more user-friendly solution to developers.

**Comment by mbahar** [comment]
@YikSanChan did you evaluate AppSync pipeline resolvers? https://docs.aws.amazon.com/appsync/latest/devguide/pipeline-resolvers.html 
Seems like it is and applicable use-case.

**Comment by YikSanChan** [comment]
@mbahar Is it atomic?

**Comment by sammartinez** [comment]
@YikSanChan Is this still a valid use case, I do want to point out that we do have documentation on the[ Storage category](https://aws-amplify.github.io/docs/js/storage#put) and also React Components in regards to this. Please let us know if you are still looking for this.
