### ISSUE TITLE
Run query in AppSync console returns UnauthorizedException

### ISSUE THREAD

**Issue by YikSanChan** [aws-amplify/amplify-js#2112]
** Which Category is your question related to? **
AppSync console

** What AWS Services are you utilizing? **
AppSync

** Provide additional details e.g. code snippets **
Whatever query I run in https://us-west-2.console.aws.amazon.com/appsync/home?region=us-west-2#/xxx/v1/queries, I get:
```
{
  "errors": [
    {
      "errorType": "UnauthorizedException",
      "message": "Unable to parse JWT token."
    }
  ]
}
```
In amplify I configure to use User Pools and I can find registered users of my app in User Pools console. I also try "Login with User Pools" but I cannot find the User Pool client ID.

**Comment by miwillhite** [comment]
I could only find the client id when tracing cognito user information that was returned from the Auth API after sign in.

**Comment by elorzafe** [comment]
@YikSanChan are you using amplify-cli?, If that is the case, you can look the userpool client id on `aws-exports.js` file on `aws_user_pools_web_client_id` param.

**Comment by YikSanChan** [comment]
> @YikSanChan are you using amplify-cli?, If that is the case, you can look the userpool client id on `aws-exports.js` file on `aws_user_pools_web_client_id` param.

It solves the problem! Is it recommended to contribute by adding a brief instruction on https://aws-amplify.github.io/docs/js/react? I will be happy to do this, as users like me do want to directly query the GraphQL backend even before writing any app code!

**Comment by JaredMathis** [comment]
Open AWS AppSync
Select your api (followed by environment ID)
Click Run a query
Click Login with User Pools
Copy your aws_user_pools_web_client_id to ClientId
Sign in with credentials from an account you've created
Now you can run queries
