### ISSUE TITLE
aws-amplify-react-native -> VerifyContact -> Picker errors when provided with null

### ISSUE THREAD

**Issue by Foosballfan** [aws-amplify/amplify-js#2114]
**Describe the bug**
When using aws-amplify-react-native in an Expo app on version 31, if you are signing in as an unverified user and presented with the Verify Contact screen then the app errors and crashes.

**To Reproduce**
 - Sign in as an unverified user in an Expo (probably any React Native) app which uses the default sign in components.
 - You are directed to the Verify Contact screen
 - Errors and crashes

**Expected behavior**
The component should render correctly and allow you to select how to verify the user

**Screenshots**
<img src="https://user-images.githubusercontent.com/15104463/48556006-92e81d00-e8da-11e8-96bc-53ef581b96a8.png" width="300" />

**Smartphone (please complete the following information):**
 - Device: Android emulator

**Additional context**
Bug can be resolved by editing the code in node_modules to ensure null is not passed to the component
```
React.createElement(
    Picker,
    {
        selectedValue: this.state.pickAttr,
        onValueChange: (value, index) => this.setState({ pickAttr: value })
    },
    email ? React.createElement(Picker.Item, { label: I18n.get('Email'), value: 'email' }) : null,
    phone_number ? React.createElement(Picker.Item, { label: I18n.get('Phone Number'), value: 'phone_number' }) : null
),
```

Bug caused at 
`VerifyContact.js, line 82`
Error
`TypeError: null is not an object (evaluating 'child.props')
This error is located at:
    in PickerAndroid (at Picker.js:159)`

**Comment by powerful23** [comment]
@Foosballfan hey I tried an app with Expo@31.0, aws-amplify@1.1.10, aws-amplify-react-native@2.0.8 on an Android device and didn't have this issue. Can you reproduce that in the real device?

**Comment by Foosballfan** [comment]
Hi @powerful23 ,

I just published my app and tested on the device. The error message doesn't appear as it's production mode but the error still exists as the app just white screens.

I also ensured that I'm on the same versions as you:Expo@31.0.4, aws-amplify@1.1.10, aws-amplify-react-native@2.0.8 

The one thing that could be a factor is the expo provided version of react-native: https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz

**Comment by Foosballfan** [comment]
@powerful23 @elorzafe Do you need any more information from me?

**Comment by powerful23** [comment]
@Foosballfan although I can‘t reproduce this issue but we can try to fix it from the code.  According to

> Bug can be resolved by editing the code in node_modules to ensure null is not passed to the component

How about I sent you the fixed code so you can replace it in the `/dist/VerifyContact.js` and see if it will work?

**Comment by powerful23** [comment]
@Foosballfan could you try replace the 
```
email ? React.createElement(Picker.Item, { label: I18n.get('Email'), value: 'email' }) : null,
    phone_number ? React.createElement(Picker.Item, { label: I18n.get('Phone Number'), value: 'phone_number' }) : null
```
with
```
email && React.createElement(Picker.Item, { label: I18n.get('Email'), value: 'email' }),
                phone_number && React.createElement(Picker.Item, { label: I18n.get('Phone Number'), value: 'phone_number' })
```

**Comment by powerful23** [comment]
@Foosballfan Can you try replace these two lines:
```js
email ? React.createElement(Picker.Item, { label: I18n.get('Email'), value: 'email' }) : null,
    phone_number ? React.createElement(Picker.Item, { label: I18n.get('Phone Number'), value: 'phone_number' }) : null
``` 
with 
```js
email && React.createElement(Picker.Item, { label: I18n.get('Email'), value: 'email' }),
                phone_number && React.createElement(Picker.Item, { label: I18n.get('Phone Number'), value: 'phone_number' })
```

**Comment by Foosballfan** [comment]
@powerful23 Unfortunately that doesn't work either. createElement is really particular and won't allow any null type value or even an empty string.

I tried to  construct an array of the children that only contained existent one and then use spread operator in createElement but that failed too.

this code works but is a bit rubbish:
```
                email ? React.createElement(Picker.Item, { label: I18n.get('Email'), value: 'email' }) : React.createElement(Picker.Item, { label:'', value: '' }),
                phone_number ? React.createElement(Picker.Item, { label: I18n.get('Phone Number'), value: 'phone_number' }) : React.createElement(Picker.Item, { label:'', value: '' })
```

For further clarification, this is happening for a user that is created without a phone number (phone_number is undefined).
For a user with both a phone number and email this is not an issue.
