### ISSUE TITLE
List users in user pool implementation

### ISSUE THREAD

**Issue by PedroS11** [aws-amplify/amplify-js#2120]
Cognito identity has a method for listing users in a user pool, however, amplify doesn't have one so I created a function to solve this problem and I would like to know your opinion about my solution because I would like to do a PR with this feature

```
var AWS = require('aws-sdk');

exports.getUsers= () => {
	var params = {
	  UserPoolId: USER_POOL_ID
	  AttributesToGet: [
	    'ATTRIBUTE_NAME',
	  ],
	};
	
	return new Promise((resolve, reject) => {
		AWS.config.update({ region: USER_POOL_REGION, 'accessKeyId': AWS_ACCESS_KEY_ID, 'secretAccessKey': AWS_SECRET_KEY });
		var cognitoidentityserviceprovider = new AWS.CognitoIdentityServiceProvider();
		cognitoidentityserviceprovider.listUsers(params, (err, data) => {
			if (err) {
				console.log(err);
				reject(err)
			}
			else {
				console.log("data", data);
				resolve(data)
			}
		})
	});
}
```

In order to this be implemented, it would require to be a function receiving the attributes to get as parameters. I'm open to suggestions/errors.

**Comment by elorzafe** [comment]
@PedroS11 thanks for your feedback. I think listing users is more oriented to **app admin** rather than **app users** which Amplify is focus on. I can mark this as feature-request so the team can discuss more about it. 

Why do you need to list all the app users? 

Thanks!

**Comment by PedroS11** [comment]
Because I had an admin panel to list the users in a user pool and wanted to do actions on them (delete/update)

**Comment by mcammaert** [comment]
+1, Also add/remove users to groups.

**Comment by undefobj** [comment]
@PedroS11 @mcammaert we're looking at providing such a feature in the future. However, it wouldn't be something that goes into the Amplify library because as pointed out by @elorzafe this is more of an administrative feature rather than a client application feature. However, I can see where you might have a client application that needs to list all members in a group in which case executing a REST or GraphQL call would be a more secure and scalable design.

If we were to automate this process by using the Amplify CLI and allow you to make API calls using your own resources would that meet your needs?

**Comment by undefobj** [comment]
One idea is that we could automate setting up an API endpoint (perhaps with a Lambda function or replicating the user information in a DynamoDB table, which supports LIST operations better) using the CLI. Baking admin features into the client library wouldn't be optimal from a scalability perspective and additionally it would add bloat to the bundle size.

**Comment by mcammaert** [comment]
@undefobj this would be great, especially if the data would be accessible through graphQL! It should also be possible to do basic mutations on users and groups: add / remove / update / activate / deactivate / add to group / remove from group / etc…

**Comment by mcammaert** [comment]
Also, is there currently a way to check if a user belongs to a given group? I would like to dynamically generate a navigation menu based on membership of certain groups… I checked the Auth.currentAuthenticatedUser() object, but I cannot find any group information in it.

**Comment by rawadrifai** [comment]
@elorzafe the admin is a user too. Do you know this has been implemented?

**Comment by undefobj** [comment]
@rawadrifai this is in the proposal phase at this point. If you have a use case that would require the above functionality please comment on the RFC: https://github.com/aws-amplify/amplify-cli/issues/766

**Comment by elorzafe** [comment]
@rawadrifai that is not implemented on amplify-js/amplify-cli. A workaround for that is using groups on Cognito UserPool (admin group with permissions to listUsers for that UserPool). Then you will need to update your IdentityPool on **Authenticated Role Selection** section to **Choose role from token**. On your client app you should use aws-sdk to list the users.

**Comment by haverchuck** [comment]
@PedroS11 @rawadrifai @mcammaert  - Please see [this RFC](https://github.com/aws-amplify/amplify-cli/issues/766).  I think it would address some of the functionality you are requesting.  Feel free to comment on it!

Thanks.

**Comment by rufoot** [comment]
@PedroS11 @elorzafe 
I wanna exactly make sure about getting user list from Cognito using Amplify. Is it possible?
Getting user list from Cognito using AWS Lambda. Is it possible?

**Comment by elorzafe** [comment]
@rufoot Currently you cannot get a user list using Amplify. You could do it from AWS lambda using aws-sdk. That is why we are working on that [RFC](https://github.com/aws-amplify/amplify-cli/issues/766)

**Comment by rufoot** [comment]
OK. Thanks.
I have researched about the Amplify and Lambda. So we can implement the Amplify authentication functionalities using Lambda functions and API Gateway. Amplify should support authentication for only an admin and an individual user.

Amplify have good user authentication system and user familiar UI. So we can use this for building serverless web and mobile application.

**Comment by houmark** [comment]
This should not be closed. Most apps these days have a client facing frontend and some kind of administrative UI where users should be possible to list and edit. I don't understand why you think this should not be baked in to Amplify.

Do you expect me to teach my administrators to use the Cognito UI and give them access to the AWS administration so they can manage users? I'm frankly surprised there haven't been more requests for this.

**Comment by christensen143** [comment]
Something else to add on to what @houmark is saying is that you cannot change attributes in the Cognito UI. Therefore the only way to change user attributes is using the CLI or API which is not acceptable. Changing user attributes should have been part of the MVP for Cognito.

**Comment by andrew-aernos** [comment]
Distributing aws key and secret is way too hackish. Just to think there might be millions of users with such key and secret in their phone's memory.

In order to NOT use the Cognito API with key and secret, My hellish workaround involves:
- Setting up set of Lamdba handlers on the Cognito user pool
- Triggers syncs and replicates each user data change to a read-only data source. (eg. dynamodb)
- Implement a ListUser from using AppSync with GraphQL, backed by dynamodb User table.

I really wish amplify / cognito team expose  their API to better support p2p client apps. Any app that has any level of user to user interaction needs this.

**Comment by undefobj** [comment]
Hello everyone. As @haverchuck and @elorzafe mentioned in their comments we had an RFC for this feature last year to address the request in a scalable and secure way. It was shipped but commenting on this issue and closing it slipped through the cracks unfortunately.

You can read how to add this functionality here: https://aws-amplify.github.io/docs/cli-toolchain/quickstart#administrative-actions
