### ISSUE TITLE
How to refresh token for DynamoDB when using Amplify

### ISSUE THREAD

**Issue by TheVaporTrail** [aws-amplify/amplify-js#2122]
**Which Category is your question related to?**
Credentials, DynamoDB

**What AWS Services are you utilizing?**
Amplify Auth, Storage, API, Analytics, etc

**Provide additional details e.g. code snippets**

In general everything works great with Amplify. Recently I started using DynamoDB, via `DocumentClient`. After an hour I get `ExpiredTokenException` errors from DynamoDB calls. I know that Amplify handles refreshing tokens as needed. How do I refresh the token that DynamoDB is using? 

I tried calling `Auth.currentSession()` or `Auth.currentUserCredentials()` before DynamoDB calls. The Amplify credentials are not expired, but the DynamoDB ones are.

I would like to know the best practice for doing this. In particular, I would like to handle it in a way that do not adversely affect Amplify. 

This is my function to get the key params for a DynamoDB call. Originally it did not have a call to `Auth.currentUserCredentials`. It returns a promise that resolves to the DynamoDB params with the table and the key set to the userId. When I added the `currentUserCredentials` call I also added the logging of the credential expiration info, just to see if that showed anything useful.

```
	var AccountManager_GetKeyParams = function()
	{
		// Return, via a Promise, an object with the table name and key populated
		return new Promise((resolve, reject) => 
			{
				// Calling currentSession will refresh the token if needed
				//Auth.currentSession()
				//.then(session => 
				Auth.currentUserCredentials()
				.then(credentials =>
				{
					var timeStr = (new Date()).toLocaleTimeString();
					var needsRefresh = (credentials.needsRefresh != undefined) ? credentials.needsRefresh() : "???"; // credentials.needsRefresh();
					var expired = credentials.expired;
					var expireTimeStr = credentials.expireTime;
	
					var s = timeStr + ", " + "needsRefresh:" + needsRefresh + ", expired: " + expired + " expireTime:" + expireTimeStr;

					console.log(s);
					
					Auth.currentUserInfo()
					.then(currentUser =>
					{	
						var keyParams = {
							TableName: acctTableName,
							Key: {userId: currentUser.id}
						};
					
						resolve(keyParams);
					})
				})
				.catch(err => 
				{
					reject(err);
				});
			});
	}
```

```
	var AccountManager_GetDocClient = function()
	{
		if (acctDocClient == undefined)
			acctDocClient = new AWS.DynamoDB.DocumentClient({apiVersion: '2012-08-10'});
			
		return acctDocClient;
	}
```
This is the "ping" test I added that is called one a minute. After an hour it starts returning an error:

```
	var AccountManager_PingTest = function()
	{
		AccountManager_GetKeyParams()
		.then(getParams =>
		{	
			acctDocClient = AccountManager_GetDocClient();
	
			return new Promise((resolve, reject) =>
				{
					acctDocClient.get(getParams, (error, result) => { (error) ? reject(error) : resolve(result); });
				});
		})
		.then(data =>
		{
			acctItemInfo = data.Item;
			
			if (acctItemInfo == undefined)
			{
				console.log("AccountManager_PingTest: account info is undefined");
			}
			else
			{
				console.log("ping test success");
			}
		})
		.catch(err => 
		{
			console.error("AccountManager_PingTest err: " + err);
		});
	}
```

Here is a log showing one call to the ping test. The first line shows the Amplify credential info, the remaining show the DynamoDB errors:

> 11:41:26 PM, needsRefresh:false, expired: false expireTime:Fri Nov 16 2018 00:41:25 GMT-0500 (Eastern Standard Time)
> PolygoniaBundle.js:201 POST https://dynamodb.us-east-1.amazonaws.com/ 400 (Bad Request)
> PolygoniaBundle.js:201 POST https://dynamodb.us-east-1.amazonaws.com/ 400 (Bad Request)
> PolygoniaBundle.js:201 POST https://dynamodb.us-east-1.amazonaws.com/ 400 (Bad Request)
> PolygoniaBundle.js:201 POST https://dynamodb.us-east-1.amazonaws.com/ 400 (Bad Request)
> PolygoniaBundle.js:201 POST https://dynamodb.us-east-1.amazonaws.com/ 400 (Bad Request)
> PolygoniaBundle.js:201 POST https://dynamodb.us-east-1.amazonaws.com/ 400 (Bad Request)
> PolygoniaBundle.js:201 POST https://dynamodb.us-east-1.amazonaws.com/ 400 (Bad Request)
> PolygoniaBundle.js:201 POST https://dynamodb.us-east-1.amazonaws.com/ 400 (Bad Request)
> PolygoniaBundle.js:201 POST https://dynamodb.us-east-1.amazonaws.com/ 400 (Bad Request)
> PolygoniaBundle.js:201 POST https://dynamodb.us-east-1.amazonaws.com/ 400 (Bad Request)
> PolygoniaBundle.js:201 POST https://dynamodb.us-east-1.amazonaws.com/ 400 (Bad Request)
> PolygoniaBundle.js:225 AccountManager_PingTest err: ExpiredTokenException: The security token included in the request is expired

Thank you,
David

**Comment by powerful23** [comment]
@TheVaporTrail  can you try passing the `credentials` like `acctDocClient = new AWS.DynamoDB.DocumentClient({apiVersion: '2012-08-10', credentials});`?

**Comment by TheVaporTrail** [comment]
@powerful23 That worked. I wasn't sure if I should create a new document client with every DynamoDB call, so my solution was to create a `_DocClientRefresh` function that runs periodically with
```
		// Periodically refresh the document client credentials
		setInterval(AccountManager_DocClientRefresh, 13 * 60 * 1000);
```
I still use my original `_GetDocClient` function:
```
//------------------------------------------------------------------------------
//	Get Doc Client
//		Return a database client handle
//------------------------------------------------------------------------------
var AccountManager_GetDocClient = function()
{
	if (acctDocClient == undefined)
		acctDocClient = new AWS.DynamoDB.DocumentClient({apiVersion: '2012-08-10'});
		
	return acctDocClient;
}
```
The `_DocClientRefresh` function gets the current user credentials and creates a new `DocumentClient` object:
```
//------------------------------------------------------------------------------
//	Doc Client Refresh
//		The credentials in the DynamoDB DocumentClient object expire and are not
//		refreshed automatically in the same way as the credentials in the Amplify
//		objects. This function is called via setInterval to periodically create a 
//		DocumentClient object with refreshed credentials.
//------------------------------------------------------------------------------
var AccountManager_DocClientRefresh = function()
{
	Auth.currentUserCredentials()
	.then(credentials => 
	{
		acctDocClient = new AWS.DynamoDB.DocumentClient({apiVersion: '2012-08-10', credentials:credentials});
	})
	.catch(err =>
	{
		console.log("AccountManager_DocClientRefresh error: ", err);
	});
		
}
```
I restored my `_GetKeyParams` function back to the way I had it originally:
```
//------------------------------------------------------------------------------
//	Get Key Params
//		Get an object that we can use to find the account in the db
//------------------------------------------------------------------------------
var AccountManager_GetKeyParams = function()
{
	// Return, via a Promise, an object with the table name and key populated
	return new Promise((resolve, reject) => 
		{
			Auth.currentUserInfo()
			.then(currentUser =>
			{	
				var keyParams = {
					TableName: acctTableName,
					Key: {userId: currentUser.id}
				};
			
				resolve(keyParams);
			})
			.catch(err => 
			{
				reject(err);
			});
		});
}

```
**A couple of notes:**
I used 
`{apiVersion: '2012-08-10', credentials:credentials}` instead of 
`{apiVersion: '2012-08-10', credentials}`, as you had in your comment, because I wasn't sure if there is something I don't understand about Javascript syntax or if it was a typo.

After waking my computer from being asleep for a long while I was getting a 'missing credentials' error from the document client calls. The error went away after the `_DocClientRefresh` function executed again. I don't know if this means I should create a new document client for every document client call. 

Thank you,
David

**Comment by powerful23** [comment]
@TheVaporTrail happy to hear that. The key is to pass the valid credentials every time the client is being initialized so that refresh works because it ensures the credentials is always the valid one.
