### ISSUE TITLE
How safe is updateUserAttributes on the client-side?

### ISSUE THREAD

**Issue by choxnox** [aws-amplify/amplify-js#2125]
** Which Category is your question related to? **
User authentication

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
Let's say we have defined several custom attributes in the user pool and one of them is signaling user's subscription plan (free plan, team plan, enterprise plan etc.). According to this attribute we can provide different services within our React app. It would be wise to note users can upgrade their usage plan after they sign up (so attribute mutation is allowed). Basically this attribute can only be modified either manually by users with admin privileges or automatically by running custom script/Lambda.

Now my question is how can we make sure malicious users won't execute `updateUserAttributes` for their account and modify this attribute which is exposed on the client side?

**Comment by choxnox** [comment]
I did some further research and it seems this is actually possible by using two different Cognito app clients with different set of read/write permissions per attribute: one for the client-side and the other for the server-side.

So for example, client-side app client which is anyway exposed through our React app (using aws-amplify) would be able to only read current subscription plan attribute while the server-side app client (which is not exposed to users) would be able to actually read and write this same attribute.

We're still new to serverless paradigm (and we like it so much we're seriously considering to switch from dockerized to serverless infrastructure) so this question might be really a simple one but I'm curious to know whether the solution with two app clients is the way to go?

**Comment by l8nite** [comment]
@choxnox That's my impression too (second app-client that only allows read); however, it seems like you are unable to make "email" "phone number" "given name" and "family name" read-only.

I was hoping to use Cognito as an out-of-the-box authorization server for arbitrary 3rd party oauth2 clients, but without being able to make them read-only for our userpool attributes, I don't think it will work.

**Comment by sammartinez** [comment]
Closing this issue as it seems the above conversation concludes the limitations of using user attributes when using Cognito. If you were looking for a feature request this may be something appropriate to write a [aws forums](https://forums.aws.amazon.com/tags/cognito) response to Cognito asknig for this.
