### ISSUE TITLE
cognitoUser missing signInUserSession

### ISSUE THREAD

**Issue by karlmosenbacher** [aws-amplify/amplify-js#2126]
**Describe the bug**
Dont know if this should be a question or a bug report, but lets give it a try.

When using the Hub module listening for hub events, the cognitoHostedUi event sometimes get dispatched and catched by the onHubCapsule function. In its payload, the cognitoUser object is added with a signInUserSession that is ***null***.

If I on the other hand make the Auth.currentAuthenticatedUser after signed in with the HostedUI I also get the cognitoUser but with the signInUserSession ***not empty.*** 

Is this the expected behavior or am I doing something wrong?

**To Reproduce**
1. Sign in with the HostedUi
2. catch the cognitoHostedUI in onHubCapsule function
3. Check its payload for cognitoUser object

**Expected behavior**
That the signInUserSession is not empty when catching cognitoHostedUI events in onHubCapsule

**Desktop (please complete the following information):**
 - OS: Mac OS High Sierra 10.13.6
 - Browser: Chrome

***Dependencies***
aws-amplify": "^1.1.9"
aws-amplify-react: ^2.1.3

**Comment by charliedavison** [comment]
+1 @karlmosenbacher Did you ever find an answer to this?

**Comment by karlmosenbacher** [comment]
@charliedavison It was a long time ago since I added this issue and the amplify team seems to have change the way the Hub module is used.

Have you tried the following:
https://aws-amplify.github.io/docs/js/authentication#oauth-and-hosted-ui

That worked for me 👍
