### ISSUE TITLE
[Storage] add versionId to StorageOptions

### ISSUE THREAD

**Issue by goatandsheep** [aws-amplify/amplify-js#2131]
**Is your feature request related to a problem? Please describe.**
I need to be able to list and view all the available versions of an object in a given S3 bucket

**Describe the solution you'd like**

* List: `Storage.list('bucket/obj', { options })`
* View: `Storage.get('obj', { versionId: 'versionid' }`

**Describe alternatives you've considered**
Frankly, none so far

**Additional context**

**Comment by goatandsheep** [comment]
is this a possibility still? It's an important requirement that otherwise requires that we go through the other aws-sdk

**Comment by t-lm** [comment]
Hi. I would be interested in that API. Thanks

**Comment by seldenj** [comment]
Hi, I would also be interested in this feature. Thanks!

**Comment by Zilvinaskli** [comment]
Hi, I would also be interested in this feature. Thanks!

**Comment by katiegoines** [comment]
Hi! Unfortunately versionId doesn't exist on `list` with S3. I'd love to gather some information on whether adding versionId to `get` would be useful without list and about your use cases in general. Thanks!

**Comment by sammartinez** [comment]
Hey folks, as @katiegoines has mentioned above, the `versionId` does not exist on `list` for the S3Client. That being stated, we were trying to gather more information on what you would use this for if it was only available via the `get` method. We are going to close this feature request out for now as we have not heard from you on your use case. If we receive use cases where we feel its worth for us to tackle, we will look to reopen it. Thanks again for opening this!
