### ISSUE TITLE
How do I get the cognito user (and sub) when using federated signin?

### ISSUE THREAD

**Issue by jliebrand** [aws-amplify/amplify-js#2133]
Perhaps I'm missing something here. But if I use Auth.federatedSignIn with an auth token from Facebook, then I can get credentials.

But those are not the same as the Cognito User from the user pool. Is that correct?  How can I match those two up?

eg I already have users signed up with their email address. If they login with Facebook, I need to be able to get the same user details (eg the cognito sub) and lookup the correct data from the db for their account details (which are keyed off of the sub)

**Comment by powerful23** [comment]
@jliebrand yes the `federatedSignIn` can only return the `credentials` for you, it doesn't have any relation to the user pool. Can you check this doc? https://github.com/aws-amplify/amplify-js/wiki/FAQ#how-can-i-get-jwt-token-when-using-amplify-to-get-federated-users-login

**Comment by baffleinc** [comment]
Further, when referencing an owner for an object and federated sign in do you use the `IdentityId` ? Will graphql transformer pick that up as well as the sub?

**Comment by powerful23** [comment]
Closing the issue due to no further response. Feel free to reopen if you still have this issue.
