### ISSUE TITLE
static Amplify.configure no longer sets the userpool on authclass

### ISSUE THREAD

**Issue by jason-h-michael** [aws-amplify/amplify-js#2134]
**Describe the bug**
As of aws-amplify@1.1.11-unstable.2, Amplify.configure is no longer setting the userPool in /authClass.

**To Reproduce**
Use the following code to initialize amplify:
```
  import Amplify from 'aws-amplify';

  initAmplify() {
    const awsConfig = this.getConfig();
    const amplifyConfig = {
      Auth: {
        region: awsConfig.API_REGION,
        userPoolId: awsConfig.USER_POOL_ID,
        userPoolWebClientId: awsConfig.USER_POOL_CLIENT_ID
      }
    };
    Amplify.configure(amplifyConfig);
    this._amplifyService = new AmplifyService();
    this._amplifyService.auth().configure(amplifyConfig);    // did not have to do this when using aws-amplify@1.1.11-unstable.0, but need to now that we are using aws-amplify@1.1.11-unstable.2
  }
```
Without that last line, we are getting "No userpool" error when trying to signin or signup.

**Expected behavior**
`Amplify.configure(amplifyConfig);` should set up userPool in AuthClass.

**Comment by powerful23** [comment]
@jason-h-michael this usually happens if something messed up in your node_modules. Can you check if you have duplicate `@aws-amplify/auth` packages under `node_modules` for example one is under `node_modules/aws-amplify/node_modules` and one is under `node_modules/@aws-amplify/auth`?

**Comment by powerful23** [comment]
@jason-h-michael did you also check if there is `node_modules` under `node_modules/@aws-amplify/auth/`?

**Comment by jason-h-michael** [comment]
Yes, no `node_modules` there either.
