### ISSUE TITLE
getting access denied error from elasticsearch for cognito unauthrole

### ISSUE THREAD

**Issue by rainnaren** [aws-amplify/amplify-js#2135]
i was trying to giving access to elasticsearch based on cognito users role .for authenticated role it was working fine .but for unauth role it is getting denied. i added both auth and unauth role

**Comment by elorzafe** [comment]
@rainnaren how are you calling elasticsearch api?

**Comment by rainnaren** [comment]
var AWS = require('aws-sdk'); var connectionClass = require('http-aws-es'); var elasticsearch = require('elasticsearch'); var cognitoidentity = new AWS.CognitoIdentity({ region: "ap-northeast-1" }); var params = { IdentityPoolId: 'ap-northeast-1:df4fe4d8-b844-4df9-bfaf-dfa03d0080ac' }; cognitoidentity.getId(params, function(err, data) { if (err) { console.log(err, err.stack); } else { AWS.config.credentials = new AWS.CognitoIdentityCredentials({ IdentityPoolId: 'ap-northeast-1:df4fe4d8-b844-4df9-bfaf-dfa03d0080ac', IdentityId: data.IdentityId }); cognitoidentity.getCredentialsForIdentity(data, function(err, data) { if (err) { console.log(err, err.stack); } else { var creds = new AWS.Credentials(data.Credentials.AccessKeyId, data.Credentials.SecretKey, data.Credentials.SessionToken); AWS.config.update({ region: "ap-northeast-1", credentials: creds }); console.log(creds) var elasticClient = new elasticsearch.Client({ host: 'https://search-bcommerce-bwpdd75t5dke5oijyfxkrrqbri.ap-northeast-1.es.amazonaws.com', log: 'debug', connectionClass: connectionClass, amazonES: { credentials: creds } }); elasticClient.search({ index: 'devbcommerceproducts', type: 'product' }).then(console.log); } }); } });

**Comment by jordanranz** [comment]
@rainnaren,

It doesn't look like you are using Amplify. Does this issue belong here?
