### ISSUE TITLE
xhr.js:87 OPTIONS https://cognito-identity.us-west-1.amazonaws.com/ net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by Waseemrajashaik** [aws-amplify/amplify-js#2146]
**Describe the bug**

I am using aws-amplify api for sign up , sign in and log out till now . everything is working fine . when i am trying to upload image . i am getting error saying 
<img width="565" alt="screenshot 2018-11-19 at 12 49 50 pm" src="https://user-images.githubusercontent.com/12861819/48691755-b58b7600-ebf9-11e8-836d-9595000a0bed.png">

i added Identity pool .

export const AWSCI = {
  Auth: {
    identityPoolId: 'xxxx',
    region: 'xxxx',
    userPoolId:  'xxxx',
    userPoolWebClientId: 'xxxxx',
  },
  Storage: {
    bucket: 'xxxxxx',
    region: 'xxxx',
  },
};
then i am getting error saying this - continually  

![screenshot 2018-11-19 at 12 52 38 pm](https://user-images.githubusercontent.com/12861819/48691850-10bd6880-ebfa-11e8-9026-e3dee731c759.png)

If i try to upload image i am getting error saying this 

![screenshot 2018-11-19 at 12 53 39 pm](https://user-images.githubusercontent.com/12861819/48691892-35b1db80-ebfa-11e8-8bd9-8ae012eebb8c.png)

**Expected behavior**
Just want to upload image using aws-amplify 

Using create-react-app

**Comment by Waseemrajashaik** [comment]
@powerful23 @robbevan 
Sorry for tagging you . guys . 
But i need answer for this

**Comment by elorzafe** [comment]
@Waseemrajashaik are you doing `Amplify.configure(AWSCI)`? or `Auth.configure(AWSCI)`

**Comment by Waseemrajashaik** [comment]
@elorzafe i am doing Amplify.configure(AWSCI);

**Comment by Waseemrajashaik** [comment]
@elorzafe any solution ?

**Comment by hurou927** [comment]
set `identityPoolRegion` in config

**Comment by Waseemrajashaik** [comment]
@hurou927  add identityPoolRegion but getting error saying 

OPTIONS https://cognito-identity.us-west-1.amazonaws.com/ net::ERR_CERT_AUTHORITY_INVALID

**Comment by Waseemrajashaik** [comment]
identityPoolRegion did the trick 👍

**Comment by br1ansho3** [comment]
> identityPoolRegion did the trick 👍

Where do you set this?
