### ISSUE TITLE
MobileHub Console corrupts Cloud Logic and CloudFormation

### ISSUE THREAD

**Issue by TheVaporTrail** [aws-amplify/amplify-js#2151]
**Describe the bug**
Even more recent: In one of my projects, clicking on the API name no longer brings up the window to configure the API. Nothing happens. If I click on the API name again, the window goes to the 'Your Projects' view of Mobile hub. 

Most recent occurrence: Trying to delete an API using the Cloud Logic view of the project results in "Failed to update project. Created API must have at least one path." I have not been able to resolve this.

Previous occurrence: Adding a new API in the Cloud Logic view resulted in two other APIs being deleted. My solution this time was to delete all of the APIs, all of the development data in the bucket, and all of the Lambda functions. After that I was able to recreate everything again.

The first time this happened I made the mistake of touching the CloudFormation stack. Once I did that, MobileHub would not let me make any changes to the Cloud Logic configuration. I had to create a new project from scratch to work around that.

**To Reproduce**
The behavior is not consistent.

**Expected behavior**
Operations selected in the Cloud Logic view work as expected.

**Screenshots**
(none)

**Desktop (please complete the following information):**
 - MacOS: [e.g. iOS]
 - Chrome
 - 70.0.3538.77 (Official Build)

**Smartphone (please complete the following information):**
 - (none)

**Additional context**

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by powerful23** [comment]
@TheVaporTrail Hi I have escalated this issue to the service team. Thanks for your feedback.
