### ISSUE TITLE
currentAuthenticatedUser is slow for checking if authenticed

### ISSUE THREAD

**Issue by jadbox** [aws-amplify/amplify-js#2154]
Calling currentAuthenticatedUser anytime the page loads to check if the user is logged in is very slow (1 to 10 seconds with 1.5s being average), and we're getting user complaints. We've tested on several machines on fast cable lines and get the same results.

Is there any way to improvement the performance and, side question, what's the best way to deal with the delay UI wise for the user?

**Comment by manicode097** [comment]
I am also experiencing a similar issue on page reload. I am using withAuthenticator and each time I reload the page it fetches the loginState from server. This makes around 5 network calls to https://cognito-idp.us-east-1.amazonaws.com and each call takes 400ms to 1s.

**Comment by powerful23** [comment]
@jadbox Hi we have noticed that the method would send requests sometimes maybe redundant to the developers. By eliminating those requests would decrease the latency. We will look for a solution for that.

**Comment by powerful23** [comment]
Also related to #1792
