### ISSUE TITLE
Using developer federated identity and cognito pools together with API

### ISSUE THREAD

**Issue by mayteio** [aws-amplify/amplify-js#2156]
**Which Category is your question related to?**
Auth, API

**What AWS Services are you utilizing?**
AppSync, Cognito User Pools, Cognito Identity Pools, AmplifyJS

**Provide additional details e.g. code snippets**
Our app needs to have both email (CUP) and Instagram (CIP) logins. Auth is fine using `Auth.signIn` and `Auth.federatedSignIn`.

API is where it falls over. I am lost on how to use the federated sign-in to authorise against the API, specifically using the `@auth` directive. No username is given with a federated identity. 

I have tried within a GraphQL transformer to use the `$ctx.identity.IdentityId` however this is only available for IAM, not cognito pools. 

1. What do I use to` @auth` API `@models` with a developer federated identity?
2. Do I need to create a user in the user pool whenever Instagram is authorized, and how to I remember which user is attached to which Instagram?
3. By signing in with Instagram am I effectively using `OPENID_CONNECT` instead of Cognito pools for authorisation?

**Comment by JakeStoeffler** [comment]
@mayteio I have many of these same questions as I am starting a new application. @powerful23 could we get some insight? Is there a plan to fix the `@auth` directive for Identity Pools or will it only ever work with User Pools?

**Comment by undefobj** [comment]
@mayteio @JakeStoeffler the `@auth` directive supports Cognito User Pools per the Transformer documentation: https://aws-amplify.github.io/docs/cli/graphql#auth
IAM via Cognito Identity Pools is not supported and you will need to set that up manually right now. We have a sample created for this: https://github.com/dabit3/appsync-auth-and-unauth
There will be more automation for that use case in the coming months. 

If you leverage both User Pools and Identity Pools in your app and configure them with `Amplify.configure()` then you do not need to call `Auth.federatedSignIn()` as the standard `Auth.signIn()` will get the appropriate JWT token from user pools and pass it to Identity Pools for you when the user logs in. I suggest walking through the automated setup and selecting the default configuration: https://aws-amplify.github.io/docs/js/authentication#automated-setup

Then when using IAM for AppSync these credentials will be leveraged: https://aws-amplify.github.io/docs/js/api#using-aws_iam

**Comment by undefobj** [comment]
Hello everyone, we have created an RFC for feature work that should make the challenges found in this issue easier in the future. If you have a moment please read through the details and add any comments: https://github.com/aws-amplify/amplify-js/issues/2716

Your feedback in the RFC will help us ensure that we are delivering the best experience possible. Thank you.

**Comment by powerful23** [comment]
Closing this issue. Please the check the doc about how to do OAuth in Amplify: https://aws-amplify.github.io/docs/js/authentication#oauth-and-hosted-ui
