### ISSUE TITLE
Security on Appsync Mutations?

### ISSUE THREAD

**Issue by rygo6** [aws-amplify/amplify-js#2159]
I am a bit naïve in this area, but am trying to understand it better. But the way amplify sets up security with cognito does not seem to be that secure to me.

What I mean by this is, lets say I add cognito user pool login. Then I add a appsync backend. From the looks of how the roles and permissions are configured, any authenticated user could then call any graphql mutation. Again, I am not highly experienced on this, I am just trying to understand, but it seems that is a bit insecure. I assume someone could hack the JS frontend to figure out how to get an authenticated id and then call any graphql mutation. 

Is the JS frontend framework really secure enough, or is there supposed to be some additional security I am supposed to be doing on graphql mutation themselves to ensure users aren't calling them inappropriately from hacked frontends?

**Comment by elorzafe** [comment]
@rygo6 On the use case you mention, `Amplify` sends the access token from a jwt (token generated by Cognito User Pools) to AppSync service. That token is validated on the service and grant permission to access the api. 

The token is generated when a user sign-in and it has an expiration time. 

If your app is compromised and someone stole that token, is similar to someone stole a password. The App should be secure.

**Comment by elorzafe** [comment]
Closing the issue because of inactivity, feel free to create a new issue if there are new concerns.
