### ISSUE TITLE
iPhone display width overflow of React Authenticator component

### ISSUE THREAD

**Issue by kennu** [aws-amplify/amplify-js#2162]
**Describe the bug**
The display width overflows when opening a React Authenticator component on iPhone. Form fields expand past the right edge of the screen.

This problem is caused by the default FormContainer's `min-width: 460px` style. It can be fixed by an overridden custom theme like this:

```
  formContainer: {
    minWidth: 375,
  }
```

I think the default should be something that works on any phone.

**To Reproduce**
1. Open Amplify React based web app in iPhone.

**Screenshots**
![screenshot 2018-11-21 at 3 30 01](https://user-images.githubusercontent.com/13944/48813094-03a99200-ed3e-11e8-9acb-87646407afc3.png)

**Expected behavior**
Width should keep within screen size instead of blowing up.

**Smartphone (please complete the following information):**
 - Device: iPhone 6

**Comment by CodingToBeWithHer** [comment]
+1

**Comment by jordanranz** [comment]
Just merged a PR to fix this. Try it with the latest unstable version. Closing for now. Please reopen if this issue persists.

**Comment by heitorlessa** [comment]
I've just installed amplify for a new project and hit this issue - Opened up and min-width is still there -- Perhaps a new npm release is in order @jordanranz ?

```javascript
```

**Comment by iqbalt** [comment]
I am having the same issue with latest release.

**Comment by iqbalt** [comment]
I am having the same issue.

**Comment by Erlix322** [comment]
push...
