### ISSUE TITLE
React Authenticator component should use minimum 16px font size on form fields

### ISSUE THREAD

**Issue by kennu** [aws-amplify/amplify-js#2163]
**Describe the bug**
The React Authenticator component should use a minimum of 16px font size in all form fields to avoid iPhone annoyingly zooming into the web view when you focus a form field.

Currently the default is something less than 16px and I have overridden it in a custom SignIn component like this:

```
                        <Input
                            autoFocus
                            style={{ fontSize: '16px' }}
                            placeholder={I18n.get('Enter your email', 'Enter your email')}
                            theme={theme}
                            key="email"
                            name="email"
                            onChange={this.handleInputChange}
                        />
```

**To Reproduce**
1. Open Amplify React based web app in iPhone and tap on a form field.

**Expected behavior**
The form field should become focused without the webview zooming in.

**Smartphone (please complete the following information):**
 - Device: iPhone 6

**Comment by jordanranz** [comment]
Just merged a PR to fix this. Try it with the latest unstable version of aws-amplify-react.

Please reopen if you have any related questions or concerns.
