### ISSUE TITLE
Documentation of PubSub usage is wrong

### ISSUE THREAD

**Issue by pnaa** [aws-amplify/amplify-js#2164]
Can anyone help with the new usage?

**Comment by powerful23** [comment]
@pnaa hey can you point out which part of the doc is wrong?

**Comment by pnaa** [comment]
When I use the subscribe example, the editor informs me that is missing a parameter ProviderOptions.

**Comment by pnaa** [comment]
PubSub.subscribe('myTopic').subscribe({
    next: data => console.log('Message received', data),
    error: error => console.error(error),
    close: () => console.log('Done'),
});

**Comment by praveshkhatana** [comment]
@pnaa use
```
PubSub.subscribe('myTopicA', []).subscribe({
      complete: () => console.log("Done"),
      next: (data) => console.log("Message Received", data),
      error: (error) => console.log( error)
    });
```
