### ISSUE TITLE
Can I use Amplify Codegen on an existing schema?

### ISSUE THREAD

**Issue by philiiiiiipp** [aws-amplify/amplify-js#2166]
** Which Category is your question related to? **
[amplify codegen](https://aws-amplify.github.io/docs/cli/codegen)

** What AWS Services are you utilizing? **
AppSync

** Provide additional details e.g. code snippets **
I am wondering if it is possible to generate flowtypes based of an existing appsync graphql schema?

The project was not done using Amplify init. I was able to use aws-appsync-codegen in the past, but its not maintained any longer + does not have support for AWSDate etc.

**Comment by yuth** [comment]
Amplify does support adding [external Appsync API](https://aws-amplify.github.io/docs/cli/codegen#amplify-add-codegen-) by passing `--apiId <api-id>` to the `add` command. It still needs a project to be initialized to use it (even if you don't use it to publish).

If this doesn't fit your need, you could use [amplify-graphql-docs-generator](https://www.npmjs.com/package/amplify-graphql-docs-generator) and [amplify-graphql-types-generator](https://www.npmjs.com/package/amplify-graphql-types-generator), which amplif-cli uses internally. Both these packages have their own CLI (albeit limited) 

We  still don't have support for `AWSDate`  in the codege. We have this feature request in our backlog.

**Comment by jpaas** [comment]
If I run `amplify init` followed by `amplify add codegen --apiId XXX` I get the error message `Codegen support only one GraphQL API per project`

**Comment by jpaas** [comment]
@yuth I figured it out. I had a `.graphqlconfig.yml` hanging around from a previous `amplify init`. Once I deleted it, it worked.

**Comment by skc18** [comment]
hey @jpaas  I am trying to use your approach, but I don't have the file .graphqlconfig.yml at all, I check the root and all the files within. The project is in Desktop. Thanks

**Comment by kaustavghosh06** [comment]
@skc18 If you're using file explorer, you won't be able to view the .graphqlconfig.yml file. Please use an editor or the terminal to view the file. Also, please let me know if you're still stuck on this.

**Comment by wallowabk** [comment]
@kaustavghosh06 you might need to do > amplify codegen remove

**Comment by LipYoung** [comment]
@wallowabk You are my hero.

**Comment by mohaumpoti** [comment]
Thanks @wallowabk

**Comment by Woodz** [comment]
Most of the scenarios observed in this issue would be a lot simpler to resolve if the error message was not misleading and contained resolution steps. For example, I think that we should replace
`Codegen support only one GraphQL API per project` with `Amplify currently only support creation of a single GraphQL API codegen configuration file (.graphqlconfig.yml) per project.`

**Comment by rogerms** [comment]
> @yuth I figured it out. I had a `.graphqlconfig.yml` hanging around from a previous `amplify init`. Once I deleted it, it worked.

That fixed my problem too. Thanks
