### ISSUE TITLE
Can't seem to update custom attributes via Auth method 

### ISSUE THREAD

**Issue by michaelsmedley** [aws-amplify/amplify-js#2167]
** Which Category is your question related to? **
Auth signUp
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
I am trying to register a new user and set a custom attribute.  I created a custom attribute labelled 'favorite_flavor', but when it has saved in Cognito it has been renamed to custom:favorite_flavor.  When I try and signUp the user using 'favorite_flavor' and I get a 'Attributes did not conform to the schema: favorite_flavor: Attribute does not exist in the schema.' response

Example code:
```javascript
Auth.signUp({
      username: this.username.value,
      password: this.password.value,
      attributes: {
        email: this.email.value,
        favorite_flavor: "this is a test"
      }
    })
      .then(data => {
        console.log(data);
        this.setState({ toConfirm: true, userObj: data });
      })
      .catch(err => this.setState({ error: err.message }));
  };
```

If I need to try and write to custom:favorite_flavor then come someone help me in determining what i need to post up please?

Many thanks for any help!

**Comment by haverchuck** [comment]
@michaelsmedley try using “custom:favorite_flavor” as your attribute key.

**Comment by michaelsmedley** [comment]
🤣🤣🤣

Well I feel like an idiot now, I did definitely try that I'm sure.

But yes, easily resolved now.  Thanks for the prompt response

**Comment by gsandiford** [comment]
I have a similar issue and tried the same thing

`signUp = async (username, password, email, birthdate, policycode) => {
    try {
      await Auth.signUp({ username, password, attributes: { email, birthdate, custom:policycode }})
      console.log('successful sign up..')
      this.setState({ stage: 1 })
    } catch (err) {
      console.log('error signing up...', err)
      alert(err.message)
    }
  }`

But get now get an error message "Attributes did not conform to the schema: custom: Attribute does not exist in the schema.". As a noob I think I may be missing something obvious... 

Any help would be most welcome thanks

**Comment by petahbred** [comment]
Haven't tried it myself, but @gsandiford appears you're just setting `custom: policycode`. You want `'custom:policycode': policycode`

**Comment by scott-lydon** [comment]
I'm getting this error as well, however here is my print out: 

```Swift
AuthUserAttribute(key: Amplify.AuthUserAttributeKey.custom("company_name"), value: "Starbucks")
```

The error is: 

```Swift
Attributes did not conform to the schema: custom:company_name: Attribute does not exist in the schema.
```

Obviously the attribute does not exist in the schema, that is why I am using the custom case.  
What is the issue with this?
