### ISSUE TITLE
Login through Hosted UI fails (Local Storage is missing an ID token)

### ISSUE THREAD

**Issue by jsbalucan** [aws-amplify/amplify-js#2168]
**Describe the bug**
I have configured User pool with social login, as well as Identity Pool with User Pool as IDP. After logging in through the hosted UI (and being redirected back to callback URL), I encounter "Error: Local Storage is missing an ID token. Please Authenticate at CongitoUser.getSession".

**To Reproduce**
1. Set up Cognito User Pools with Social Login (I used google), as well as the appropriate domain for login.
2. Set up Cognito Identity Pools, with the Cognito User Pool as IDP
3. Set up react app and use Authenticator (Amplify config attached below)
4. Run server, then select sign in with AWS
5. Get redirected to Cognito Hosted Login
6. Login
    6.a. Login via Google
    6.b. Login using username + password
7. Get redirected back to app
8. See error

**Amplify Config**
```
Amplify.configure({
  Auth: {
    mandatorySignIn: true,
    region: config.cognito.REGION,
    userPoolId: config.cognito.USER_POOL_ID,
    identityPoolId: config.cognito.IDENTITY_POOL_ID,
    userPoolWebClientId: config.cognito.APP_CLIENT_ID,
    oauth: {
      domain : '***REDACTED***.auth.ap-southeast-1.amazoncognito.com', 
      scope : ['aws.cognito.signin.user.admin'], 
      redirectSignIn : 'http://localhost:3000/', 
      redirectSignOut : 'http://localhost:3000/',
      responseType: 'code',
      options: {
        AdvancedSecurityDataCollectionFlag : true
      }
    }
  },
  API: {
    endpoints: [
      {
        name: 'testApiCall',
        endpoint: config.apiGateway.URL,
      }
    ]
  }
});
```

**Expected behavior**
1. If social login is from a new user, User Pool entry will be created (YES)
2. Identity pool will contain a new identity entry, with the source coming from the User Pool (NO)
3. Web App will get logged in (NO)

**Screenshots**
Note: I started debugging this on my own, which is why it's logging more data (considering the redirect nature of the process, I am not able to turn on debugging logs via window.LOG_LEVEL="DEBUG"). Details on what I've found so far included below.
<img width="1224" alt="screen shot 2018-11-21 at 9 08 13 pm" src="https://user-images.githubusercontent.com/11612170/48846266-a531f180-edd9-11e8-90ac-20dae70d9161.png">

**Desktop (please complete the following information):**
 - OS: OS 10.13.6
 - Browser: Chrome Version 70.0.3538.102
 - React app
 - Amplify versions:
    - aws-amplify@1.1.10
    - aws-amplify-react@2.1.4

**Additional context**
I'm not sure if it's just that I'm doing something wrong. I tried to debug the code on my own, and found that:
1. Code or Token (I tried both auth code grant and implicit grant) query parameter seems to be processed by Amplify
2. I tried printing out whatever's in the storage, and I've pasted it below. I noticed that idToken is, in fact, empty. If I log in directly via Authenticator (username+password / non-social log in), storage _will_ contain an idToken.
```
Storage {
 "CognitoIdentityServiceProvider.24****REDACTED****4k.Google_10****REDACTED****18.accessToken": "eyJr****REDACTED****HDg",
 "CognitoIdentityServiceProvider.24****REDACTED****4k.Google_10****REDACTED****18.idToken": "",
 "CognitoIdentityServiceProvider.24****REDACTED****4k.Google_10****REDACTED****18.refreshToken": "eyJ****REDACTED****rQ",
 "CognitoIdentityServiceProvider.24****REDACTED****4k.Google_10****REDACTED****18.tokenScopesString": "aws.cognito.signin.user.admin",
  "CognitoIdentityServiceProvider.24****REDACTED****4k.LastAuthUser": "Google_10****REDACTED****18",
  "amplify-authenticator-authState": "signIn",
  "aws-amplify-cacheCurSize": "0"
}
```

I'm kind of stumped right now. Please let me know if I just missed parts of the configuration. I'd be willing to help in the debugging, but there are a lot of things I don't know yet, especially with the internal flows. I had hoped I can easily set up AWS Cognito and Amplify and use it to provide gateway access to our AWS resources, but I ran into this. In any case, thanks so much for the help!

**Comment by karlmosenbacher** [comment]
Do you have a codesnippet to share perhaps?.

**Comment by powerful23** [comment]
@jsbalucan the `idToken` should not be empty. Can you provide some debug info to see if the url is parsed successfully. You can click on `Preserve log` in the chrome so the console will not be cleared when the page is redirected/reloaded.

**Comment by jsbalucan** [comment]
Hi @karlmosenbacher , I basically just used the Authenticator
```
async handleAuthStateChange(state) {
  console.log('handleAuthStateChange', state);
  if (state === 'signedIn') {
    try {
      const signedInUser = await Auth.currentAuthenticatedUser();
      console.log('signedInUser', signedInUser);

      const creds = await Auth.currentCredentials()
      console.log('credentials', creds);

    } catch (e) {
      console.log('Error stateChange:', e);
    }
  }
}

render() {
  const map = (message) => {
    if (/user.*not.*exist/i.test(message)) {
      return 'User does not exist';
    }
    if (/user.*already.*exist/i.test(message)) {
      return 'User exists';
    }
    if (/validation.*password/i.test(message)) {
      return 'Password does not conform to rules!';
    }
    if (/invalid.*phone/i.test(message)) {
      return 'Invalid phone number format.';
    }
    if (/incorrect.*username.*password/i.test(message)) {
      return 'Incorrect username/password.';
    }
    if (/incorrect.*username/i.test(message)) {
      return 'User does not exist';
    }
    return message;
  };

  return (
    <div className="App container">
      <Authenticator errorMessage={map} hideDefault={false}  onStateChange={this.handleAuthStateChange}>
      </Authenticator>
    </div>
  );
}
```

Hi @powerful23 . I actually run with Preserve log already. But, considering the redirections, it's not preserving the _window.LOG_LEVEL="DEBUG"_ setting. In any case, I just set the log level config in Amplify instead. 

Full logs. Marked user actions ("LOAD PAGE", "SIGN IN WITH AWS", "SOCIAL LOGIN") :
[amplify.log](https://github.com/aws-amplify/amplify-js/files/2606174/amplify.log)

Upon checking the debug logs, there is some mention of
```
ConsoleLogger.js:96 [DEBUG] 52:57.148 AuthClass - Failed to get user from user pool
ConsoleLogger.js:112 {[DEBUG] 52:57.148 AuthClass - The user is not authenticated by the error: "No current user"}
```
I can confirm that the user has been created and viewable in the Cognito User Pool Users & Groups.

As for:
```
ConsoleLogger.js:112 {[DEBUG] 52:57.282 AuthClass - Error in cognito hosted auth response: "{"error":"invalid_grant"}"}
```
I configured User Pools for Authorization Code Grant, and applied that as well in the oauth config _responseType: 'code'_. I've also followed the setup indicated in the documentation: https://aws-amplify.github.io/docs/js/authentication#using-amazon-cognito-hosted-ui

See app client settings below:
![screen shot 2018-11-22 at 8 16 50 am](https://user-images.githubusercontent.com/11612170/48874644-3aaba080-ee2f-11e8-8939-37d05186ef10.png)

Thanks for the help! I really appreciate it.

**Comment by jsbalucan** [comment]
Also, in case it helps, I've included the objects for when the parsing occurs:
![screen shot 2018-11-22 at 8 33 12 am](https://user-images.githubusercontent.com/11612170/48875107-e5bd5980-ee31-11e8-9d8a-e67028aebf8c.png)

**Comment by jsbalucan** [comment]
I finally solved this issue after coming across one of the AWS Cognito [documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/authorization-endpoint.html).

> The Amazon Cognito authorization server redirects back to your app with access token. Since openid scope was not requested, an ID token is not returned. A refresh token is never returned in this flow. Token and state are returned in the fragment and not in the query string.

I didn't configure my client's scope (App Integration > App client settings > Allowed OAuth Scopes) to **include** openid. This caused the authorize endpoint to not return the ID token, thereby causing the empty id token error.

I'm not sure if it's common knowledge, but additional documentation about this being a requirement might come handy for those looking to just "dive in".

In any case, I'll close this issue now. Thanks! :smile:

**Comment by powerful23** [comment]
@jsbalucan thanks, will add this to the doc.

**Comment by undefobj** [comment]
Hello everyone, we have created an RFC for feature work that should make the challenges found in this issue easier in the future. If you have a moment please read through the details and add any comments: https://github.com/aws-amplify/amplify-js/issues/2716

Your feedback in the RFC will help us ensure that we are delivering the best experience possible. Thank you.
