### ISSUE TITLE
Safari: "Are you sure you want to leave this page?" popup

### ISSUE THREAD

**Issue by CodingToBeWithHer** [aws-amplify/amplify-js#2174]
<img width="1865" alt="screen shot 2018-11-22 at 09 18 58" src="https://user-images.githubusercontent.com/14866119/48893266-e1943a80-ee37-11e8-92f7-03c708d42f46.png">

**Describe the bug**
In Safari Redirecting after sign in triggers popup window:
"Are you sure you want to leave this page?"

This behaviour also happens when user clicks "Reset password" and tries to refresh the page in safari.

**To Reproduce**
1. add line of code like:
window.location.href = "https://example.com"
in componentDidMount in the main App component (this is loaded after successful sign in)
2. Open the code in Safari browser, Enter username, password, click Sign in
3. The safari displays the popup window

Or
1. Click "Reset password"
2. try to refresh the page
3. Safari displays the popup: "Are you sure you want to leave this page?" even though the form is empty! It does not happen in Chrome or Mozilla this behaviour

**Expected behavior**
There should be no popup window in the above scenarios in Safari

**Desktop (please complete the following information):**
 - Browser Safari 11.0.1

**Comment by powerful23** [comment]
This happens if the `window.location.href` is assigned. Will look into that.

**Comment by georgeevans1995** [comment]
We spent a while looking into a similar issue and found this issue useful for a fix:
https://github.com/aws-amplify/amplify-js/issues/2088

Seems to be amplify analytics session tracking that causes the popup so just needed the following in our aws-exports file.
```
 Analytics: {
    autoSessionRecord: false
  }
```

**Comment by CodingToBeWithHer** [comment]
@georgeevans1995 
yes, you are absolutely right, I actually found this issue: 
https://github.com/aws-amplify/amplify-js/issues/2088

some time ago and indeed: 

> Analytics: {
    autoSessionRecord: false
  }

fixed the issue, thx for posting, 
do you know what Javascript was causing this? just curious if I ever see similar behaviour somewhere I'd know what Javascript function/event was causing this.

**Comment by CodingToBeWithHer** [comment]
I'm closing the issue as solution has been posted, but if someone has extra feedback regarding what particular Javascript is causing this behaviour I'd appreciated if they could explain below.
