### ISSUE TITLE
Add dial code dropdown to React Native Authenticator

### ISSUE THREAD

**Issue by jimbol** [aws-amplify/amplify-js#2176]
**Is your feature request related to a problem? Please describe.**
Without the proper phone number prefix, sign up fails. In the react version, a prefix dropdown is provided ([see here](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Auth/SignUp.jsx#L114-L136)). In the React Native version, however, it is not ([see here](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react-native/src/Auth/SignUp.js#L93-L100))

**Describe the solution you'd like**
Add the same prefix dropdown to the react native version.

**Describe alternatives you've considered**
I could roll my own SignUp page, but I'd really like to leverage the nice tools you've provided. 
Alternatively, you could allow removing the field if a phone number is not required.

**Comment by jimbol** [comment]
@powerful23 I'll work on this

**Comment by jimbol** [comment]
Progress! Just have to style the android version and we'll be all set.
![phone](https://user-images.githubusercontent.com/1278367/49292602-bafb8280-f47b-11e8-8d59-ab577f5942ff.gif)

**Comment by jimbol** [comment]
@powerful23 PR submitted!

**Comment by jordanranz** [comment]
Closing this issue as the PR has been merged. Thanks for adding this! Please reopen if there are any further questions or concerns.
