### ISSUE TITLE
S3Image component ignores preview="hidden" if path prop specified

### ISSUE THREAD

**Issue by russelltaga** [aws-amplify/amplify-js#218]
When using the `S3Image` component, if you include the `path` prop like so, the component seems to ignore suppressing the preview via `preview="hidden"`.

```
<S3Image level="private" preview="hidden" path="test/" fileToKey={this.fileToKey} onLoad={this.handleLoad} picker />
```
Here are screenshots showing how this renders:

<img width="189" alt="screen shot 2018-01-31 at 10 22 39 pm" src="https://user-images.githubusercontent.com/27798268/35664270-27cf47a0-06d6-11e8-8508-137a9de441e6.png">

and in the JS console:

<img width="812" alt="screen shot 2018-01-31 at 10 23 43 pm" src="https://user-images.githubusercontent.com/27798268/35664273-2cd46bb8-06d6-11e8-8ac5-474d47984381.png">

If you select an image with the picker, it'll render it vs. suppressing the preview as well.

**Comment by powerful23** [comment]
@russelltaga I think that ```preview``` props is only for ```PhotoPicker```. I will make a pr to hide images in ```S3Image```.

**Comment by russelltaga** [comment]
Ugh, my bad, but thank you so much!

**Comment by powerful23** [comment]
@russelltaga  this issue has been fixed in the latest release. Please feel free to reopen the issue if neccessary.

**Comment by russelltaga** [comment]
@powerful23 Thank you much!

**Comment by russelltaga** [comment]
@powerful23 Sorry to bother you about this, but one side effect with the hidden image, is that I'm not seeing a way to know when the file has been uploaded. The `onLoad` event understandably doesn't fire since you're no longer loading the image to preview it. Are there any other hooks that I overlooked by chance when using `S3Image`?

**Comment by powerful23** [comment]
@russelltaga we will look into that.

**Comment by hernangarcia** [comment]
> <S3Image level="private" preview="hidden" path="test/" fileToKey={this.fileToKey} onLoad={this.handleLoad} picker />

Hello @russelltaga , can you please share a sample about using the component? I am getting weird display when using it.

This is my code:
<S3Image imgKey={username + '_profile_img'} picker />

And you can see in the image what I get.
<img width="523" alt="screenshot 2018-09-28 11 32 24" src="https://user-images.githubusercontent.com/882474/46221266-3c1a8a00-c312-11e8-8e35-5d6cb572a9f3.png">

**Comment by russelltaga** [comment]
@hernangarcia Over time some of the requirements we had at the time shifted and I ended up implementing a custom UI and using the Storage APIs directly. It's been many months and a little tied up right now, but will try to whip up an example next week.

**Comment by ceich** [comment]
@russelltaga are you looking at the 2.1.x version of aws-amplify-react? I just upgraded today and see what @hernangarcia is seeing.

**Comment by russelltaga** [comment]
@ceich My bad, I'm definitely on an older version (completely forgot to upgrade to the latest for the test). Will try to verify soon.

**Comment by jordanranz** [comment]
FYI, we have started an RFC discussion for a proposed Amplify UI Component refactor to increase customizability and flexibility for our components. Please feel free to add any additional comments to the following issue:

#3279

**Comment by sammartinez** [comment]
Looking at responses from @russelltaga I do see that he was able to resolve this other ways and there are other FRs open for similar things, as referenced above. I am going to resolve this feature request. Please feel free to make comments on the RFC if there are further callouts.
