### ISSUE TITLE
is cognito email address case sensitive???????

### ISSUE THREAD

**Issue by hemanth-sp** [aws-amplify/amplify-js#2189]
** Which Category is your question related to? **

** What AWS Services are you utilizing? **

** Provide additional details e.g. code snippets **

**Comment by SagarMhatre** [comment]
I have seen that the User Id is case sensitive. If I create a user with username "sagar", I cannot login using the username "Sagar".

**Comment by powerful23** [comment]
@hemanth-sp Yes, it's case sensitive.

**Comment by elorzafe** [comment]
@hemanth-sp from today new User Pools can be created with case insensitivity for username input
More info [here](https://aws.amazon.com/about-aws/whats-new/2020/02/amazon-cognito-user-pools-service-now-supports-case-insensitivity-for-user-aliases)
