### ISSUE TITLE
AppSync authorised mutations but queries for everyone?

### ISSUE THREAD

**Issue by XC3S** [aws-amplify/amplify-js#2191]
I have a GraphQL API using **Amazon Cognito User Pool** as Authorization type. Mainly to allow only  authorised users to use mutations. But I want query for everyone including unauthorised users.

Is there a way to configure AppSync this way or is there a recommended best practice? 

I use this schema
```
type Recipe 
  @model 
  @auth(rules: [
    { allow: owner, ownerField: "owner", mutations: [update], queries: null }
  ]) {
  id: ID!
  name: String!
  images: [String]
  owner: String!
  comments: [Comment] @connection(name: "RecipeComments")
}
type Comment 
  @model 
  @auth(rules: [
    { allow: owner, ownerField: "owner", mutations: [update], queries: null }
  ]) {
  id: ID!
  content: String
  recipe: Recipe @connection(name: "RecipeComments")
}
```

**Comment by D2KX** [comment]
You'll have to chose IAM as Authorization type and use Cognito Federated Identities with Unauthenticated Roles enabled for now.

**Comment by undefobj** [comment]
@SubChord IAM is still needed for this scenario at the moment, however the AppSync team is looking at alternatives for the service in the coming months to give additional options. 

@XC3S if you have IAM configured in your AppSync API, and your clients are configured for those credentials yet you are still getting a 403, then it's possible that the IAM Role on your Federated Identity Pool doesn't have appropriate permissions for AppSync. Take a look at the role and ensure that it has permissions of this style: https://docs.aws.amazon.com/appsync/latest/devguide/security.html#aws-iam-authorization

**Comment by undefobj** [comment]
@SubChord @XC3S @D2KX the following RFC might be interesting for your use case: https://github.com/aws-amplify/amplify-cli/issues/766

**Comment by jordanranz** [comment]
Going to close this as the answers to your questions are posted above. Please go ahead and reopen this if you have any related questions or concerns.

**Comment by undefobj** [comment]
In the short term, we've published a sample here: https://github.com/dabit3/appsync-auth-and-unauth

**Comment by sis-dk** [comment]
Any updates on this?
