### ISSUE TITLE
Federated with auth0 documentation has invalid javascript and is wrong

### ISSUE THREAD

**Issue by willdady** [aws-amplify/amplify-js#2194]
**Describe the bug**
 Documentation for **Federated with auth0** is wrong and does not contain valid javascript.

**To Reproduce**
See Step 2 [here](https://aws-amplify.github.io/docs/js/authentication#federated-with-auth0), it has syntax errors and it's function signature doesn't match the [federatedSignIn documentation](https://aws-amplify.github.io/amplify-js/api/classes/authclass.html#federatedsignin).

I've tried calling the function without the object wrapping the params but in resulted in the error `You must specify a federated provider`.

**Expected behavior**
The documentation to provide valid and working examples.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***
N/A

**Comment by powerful23** [comment]
@willdady thanks for your feedback. I've sent out a pr to fix it: https://github.com/aws-amplify/docs/pull/237

**Comment by willdady** [comment]
Thanks @powerful23 I've added some comments to your PR as it still has invalid syntax.

**Comment by powerful23** [comment]
@willdady Thanks. I have submitted another pr: https://github.com/aws-amplify/docs/pull/244 if you could take a look that would be great.

**Comment by powerful23** [comment]
Closing this issue due to it has been fixed.
