### ISSUE TITLE
Cache documentation error?

### ISSUE THREAD

**Issue by ahmetcetin** [aws-amplify/amplify-js#2195]
Well, the explanation and the example given in the Cache documentation are just opposite:

> When using priority setting, the cached item with the lower number will be expired first. The Cache module decides expiration based on the memory available to the cache. In the following example,breakfastFoodOrder will be expired before mothersBirthday.

```
Cache.setItem('mothersBirthday', 'July 18th', { priority: 1 });
Cache.setItem('breakfastFoodOrder', 'Pancakes', { priority: 3 });
```

mothersBirthday priority is 1 lower than breakfastFoodOrder's priority, which is 3, so according to explanation in the first sentence above, mothersBirthday should expire first, but the last sentence above says just the opposite.

So which one is correct?

**Comment by powerful23** [comment]
@ahmetcetin The explanation is correct. The priority 1 is higher then priority 3. The lowest priority is 5: https://aws-amplify.github.io/docs/js/cache#configuration

**Comment by ahmetcetin** [comment]
thx for the answer @powerful23. apparently i didn't check the configuration options at the bottom of the page, my bad.
