### ISSUE TITLE
Update identity providers of user pool using Amplify CLI

### ISSUE THREAD

**Issue by jocactus** [aws-amplify/amplify-js#2197]
**Which Category is your question related to?**
Authentication with Angular 7, Social Sign-in

**What AWS Services are you utilizing?**
auth

**Provide additional details e.g. code snippets**
In my Angular project, I updated my auth configuration with the Amplify CLI to allow users to authenticate via Google and pushed my configuration.

But I am not sure of the next steps to configure the authentication via Google. I read the documentation and I am confused because I find mostly react examples with Authenticator.

Is it possible to configure the authentication via Google without Authenticator?

From my understanding, I have to configure the Amazon Cognito Hosted UI.

Am I correct?

**Comment by wollerman** [comment]
@jocactus did you determine how to do this? I am currently working on integrating the google identity provider into my user pool as an option for sign in. But the Amplify documentation shows examples with the Identity Pool which is not what I'm looking for. I was hoping to have a simple "log in with google" button that can create a user in my User Pool federated correctly.

**Comment by jocactus** [comment]
@wollerman I configured the hosted UI to manage google as described here: [https://aws-amplify.github.io/docs/js/authentication#using-amazon-cognito-hosted-ui](https://aws-amplify.github.io/docs/js/authentication#using-amazon-cognito-hosted-ui)

**Comment by wollerman** [comment]
I see, so you ended up with the hosted UI. I'm holding out for being able to use federation without the hosted UI. Thanks!

**Comment by undefobj** [comment]
@wollerman are you looking to Federated with Cognito Identity (e.g. no hosted UI)? If so you can use `Auth.federatedSignIn()` as per this documentation: https://aws-amplify.github.io/docs/js/authentication#federated-identities-social-sign-in

Alternatively if you want to use Federation with Cognito User Pools but not "launch" the Hosted UI (e.g. just use the endpoint and bypass it to go straight to the social provider) please see the code sample here: https://aws-amplify.github.io/docs/js/authentication#make-it-work-in-your-app

**Comment by wollerman** [comment]
@undefobj I was looking to use only the Cognito User Pools without Hosted UI or Federated Identity. I was imagining having a button like "sign in with Google" which redirects back to my app. It looks like the second link you posted does that? I might have glossed over it being unfamiliar with React (I'm using Angular). 

I'll definitely give that a shot. Thanks!
