### ISSUE TITLE
Amplify is not a proper es6 module

### ISSUE THREAD

**Issue by goatandsheep** [aws-amplify/amplify-js#2199]
**Describe the bug**
Unable to use the package at all without Webpack loaders. I get `The requested module '../../node_modules/@aws-amplify/core/lib/index.js' does not provide an export named 'default'`

**To Reproduce**
1. Setup [PWA Starter Kit](https://github.com/Polymer/pwa-starter-kit/)
2. `npm install --save aws-amplify`
3. `import Amplify from 'aws-amplify' in `my-app.js`

**Expected behavior**
Amplify should be an es6 module, not just fake that it is by putting `Object.defineProperty(exports, "__esModule", { value: true });` at the [top of the package](https://unpkg.com/aws-amplify@1.1.10/lib/index.js)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 1.0.18
 - Webcomponents, Gulp, Lit-Element

**Additional context**
[This ticket says that the package needs to have an export](https://github.com/Polymer/pwa-starter-kit/issues/122), which is [not the case for aws-amplify](https://unpkg.com/aws-amplify@1.1.10/lib/index.js)

**Comment by goatandsheep** [comment]
I tried doing: `import * as Amplify from 'aws-amplify'` and got `ReferenceError: exports is not defined
    at index.ts:15`

**Comment by karlito-who-else** [comment]
The documentation makes little to no mention of this issue and really should be updated to reflect the limitations of the package only being available in CommonJS format until all of the tasks in #2309 are complete.  This would avoid a lot of frustration and wasted time for developers who are keen to work with the package.  I saw mention of configuring Webpack for bundling modules in one page of the documentation but other pages - including the README.md of this repo - are very misleading in that they read as though the developer should be able to directly import amplify-js in the browser.
