### ISSUE TITLE
Admin endpoints

### ISSUE THREAD

**Issue by cbernardes** [aws-amplify/amplify-js#2200]
**Is your feature request related to a problem? Please describe.**
Amplify auth provides a good range of options to the user to manage its accounts. Unfortunately it doesn't have the Admin endpoints implemented, such as adminAddUserToGroup, adminConfirmSignUp, adminDeleteUser, etc.

**Describe the solution you'd like**
Access those endpoints through the Amplify Auth methods.

**Describe alternatives you've considered**
I have been considering to use the cognito aws sdk node module

**Additional context**
- During my tests automation I wanted to confirm an user authentication through the admin confirm sign up method.
- I need to update one of my user's custom attribute based on which environment (mobile, web) they are. This without the authentication.

**Comment by undefobj** [comment]
@cbernardes thanks for the feature request. This isn't something that we would put in Amplify JS library as it's explicitly for client applications (browser based or hybrid, such as React Native) and not administrative service use. The library is aimed at helping the frontend application development experience. For those use cases you should use the AWS SDK on the backend.

**Comment by undefobj** [comment]
@cbernardes the following RFC might be interesting for your use case: https://github.com/aws-amplify/amplify-cli/issues/766
