### ISSUE TITLE
Access Token has been revoked

### ISSUE THREAD

**Issue by hoang-innomizetech** [aws-amplify/amplify-js#2205]
We are using withAuthenticator HOC. Sometimes we got this unexpected exception

```
[Warning] Possible Unhandled Promise Rejection (id: 0):
Object {
  "code": "NotAuthorizedException",
  "message": "Access Token has been revoked",
  "name": "NotAuthorizedException",
}
```

Does anyone know the root cause and how to prevent this exception to occur?

**Comment by hoang-innomizetech** [comment]
Before getting this exception, we call Auth.currentSession() and it still return isValid() = true. Is there any way we can check whether a token is revoked?

**Comment by manueliglesias** [comment]
Hi @hoang-innomizetech 

Is there a way you can share some of the code you are using? Or a simplified version of it?

**Comment by powerful23** [comment]
Closing the issue due to no further response. Feel free to reopen if you still have this issue.

**Comment by maziarz** [comment]
I have recently noticed same issue, and use-case as @mllrmat
