### ISSUE TITLE
Send SMS OTP using Twilio or Nexmo

### ISSUE THREAD

**Issue by ianpogi5** [aws-amplify/amplify-js#2206]
**Is your feature request related to a problem? Please describe.**
Our customers receive OTP sender as "NOTICE" or some random phone number. We want to be able to use our own SenderID for branding.

**Describe the solution you'd like**
Be able to get the OTP from API call on the server and we'll send it to customer via Twilio/Nexmo.

**Describe alternatives you've considered**
Tried to set SenderID in AWS Cognito but there is none.

**Comment by manueliglesias** [comment]
Hi @ianpogi5 

Your use case might be possible using [Cognito User Pool triggers](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html), specifically:

> Pre Sign-up Lambda Trigger
The pre sign-up Lambda function is triggered just before Amazon Cognito signs up a new user. It allows you to perform custom validation to accept or deny the registration request as part of the sign-up process.

**Comment by malithjkmt** [comment]
@KhaledSoliman, can you elaborate more on **"The better approach is to  allow cognito to pass off any code sms or invitiation sms to a lambda trigger"** please?

There are [Custom Authentication Challenge Lambda Triggers](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-challenge.html) to generate otp and send via my own sms api and get the verification..... but, 

it would be much simpler if we have a way to bypass only sns's SMS sending part.

My requirements are,
SNS SMS price is too high and need my product's name as sms sender (mask) so, need to plug a third  party sms api

**Comment by KhaledSoliman** [comment]
@malithjkmt I was suggesting to the cognito devs to allow us to bypass the SNS provider using a lambda trigger that receives all message out bound and we use the API that would work better in our local area to send those messages

**Comment by malithjkmt** [comment]
@KhaledSoliman yes, that'll help thousands of devs.. 
But, for now is there a workaround for this other than  Custom Authentication Challenge Lambda Triggers? or anything?

**Comment by KhaledSoliman** [comment]
@malithjkmt As far as I know, no the only way to bypass SNS is to creat your own auth flow using triggers

**Comment by malithjkmt** [comment]
@KhaledSoliman I did start on custom auth flow implementing 3 Lambda triggers for aws userpool.
According to [Amplify docs](https://aws-amplify.github.io/docs/js/authentication#switching-authentication-flow-type), we need to change authenticationFlowType, from `USER_SRP_AUTH` to `CUSTOM_AUTH`

But, when user **signup** it's still going through builtin auth flow (sends sms OTP via SNS).
But, when **signIn**, the newly added triggers are running which I don't want to happen.

So, I have a new question now. Does this [Custom Authentication Flow](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-authentication-flow.html#amazon-cognito-user-pools-custom-authentication-flow) work when signIn only?
I need it to run when signup.

**Comment by dinukasal** [comment]
@malithjkmt and team was able to send sms with local sms gateway. We used custom auth challenge and its three triggers, Define Auth Challenge, Create Auth Challenge and Verify Auth Challenge.

**Comment by sammartinez** [comment]
Closing this issue as @manueliglesias followed up with the customer above. As for the Cognito related feature request, please go to Cognito's [AWS Forums](https://forums.aws.amazon.com/tags/cognito) to request feature requests to the Cognito Service team
