### ISSUE TITLE
VS Code Extension breaks other snippet extension

### ISSUE THREAD

**Issue by SebSchwartz** [aws-amplify/amplify-js#2207]
**Describe the bug**
When installing and enabling VS Code Snippet Extension, it breaks other code snippet extension (in my case: dsznajder.es7-react-js-snippets).

**To Reproduce**
1. Install "Amplify VS Code Snippet Extension) -> aws-amplify.aws-amplify-vscode
2. Install "VS Code ES7 React/Redux/React-Native/JS snippets" -> dsznajder.es7-react-js-snippets
3. Try to execute a snippet like "rafce"
4. See error: It doesn't work or show in the list when hitting tab button.

**Expected behavior**
Other snippet extension should still work.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Version 10.14.1

**Smartphone (please complete the following information):**

**Additional context**

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by deadcoder0904** [comment]
Yep, this is really terrible. It even breaks my emmet autocompletion. Even if I type `p`, it suggests `PhotoPicker` to me so I've currently disabled this extension.

Hope this fixes soon 🤞

**Comment by deadcoder0904** [comment]
Bad bot
