### ISSUE TITLE
How to get selection outline on S3Image using <S3Album select ... />?

### ISSUE THREAD

**Issue by ceich** [aws-amplify/amplify-js#2215]
** Which Category is your question related to? **
aws-amplify-react

** What AWS Services are you utilizing? **
S3

** Provide additional details e.g. code snippets **
If the `select` prop is given to `S3Album`, it tracks image selection (click to toggle) and passes it to each `S3Image` (or `S3Text`) as a `selected` prop. `S3Image` uses the prop to set the style of a sibling `div` to the actual image to either `overlay` or `overlaySelected`, as seen in `imageEl()`:
```
            <div style={containerStyle} onClick={this.handleClick}>
                <img
                    style={theme.photoImg}
                    src={src}
                    onLoad={this.handleOnLoad}
                    onError={this.handleOnError}
                />
                <div style={selected? theme.overlaySelected : theme.overlay}></div>
            </div>
```

I am using S3Album like so:
```
<S3Album level="protected" path="pictures/"
  select onSelect={this.handleSelect}
  theme={{overlaySelected: {'border-style': 'solid', 'border-width': 'thick', 'border-color': 'red'}}} />
```
but the selection shows up as a flattened red box, _below_ the clicked image. The overlay `div` is not expanding to fit the parent `div`. 

Should I be doing something with other theme elements, like `album` or `albumPhoto`, to make the sibling `img` and `div` tags have the same size and overlap? (`containerStyle` above is always `position:relative`) but there are parent div's that use the `album` and `albumPhoto` theme elements.)

**Comment by jordanranz** [comment]
Hey @ceich,

Do you have a screenshot of this issue. I will try and reproduce and diagnose what you are experiencing.

**Comment by ceich** [comment]
Thanks, @jordanranz.
![screen shot 2018-12-06 at 2 16 57 pm](https://user-images.githubusercontent.com/38611/49615208-ae869680-f961-11e8-8d7d-24dc33b61f1b.png)
The top picture (of an iPhone) is selected, but the selection outline is rendered below the picture. As you can see in the inspector, the computed height is 10px.

**Comment by ceich** [comment]
I am a CSS n00b but it seems I need to give both the `img` and the sibling `div` an absolute position. If I do this in the dev tools console, all the photos in the album overlap each other. Pretty much lost here....

**Comment by ceich** [comment]
TIL that `position:relative` is the way to set the containing block for a div with `position:absolute`. So all I need is to give the overlay div this style:
```
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
```
and it should work. Wish it were built in as a default!
