### ISSUE TITLE
How do I validate user server side when using amazon-cognito-identity-js?

### ISSUE THREAD

**Issue by jeremywhittington** [aws-amplify/amplify-js#2218]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
What is the proper way to validate the user on the server after they login using authenticateUser?

**Comment by manueliglesias** [comment]
Hi @jeremywhittington 

Can you provide some more information or code snippet to get a better picture of your use case?

**Comment by jeremywhittington** [comment]
> Hi @jeremywhittington
> 
> Can you provide some more information or code snippet to get a better picture of your use case?

@manueliglesias I have a python web application and ive successfully implemented amazon-cognito-identity-js client side to authenticate a user on my website. What I am trying to understand is how can I make sure on the back end that they are authenticated?

I have been looking at how to read the token from cookies but havent figured it out yet.

**Comment by jeremywhittington** [comment]
> Hi @jeremywhittington
> 
> Can you provide some more information or code snippet to get a better picture of your use case?

For example, when I use cookie storage in authenticateUser which cookie should I look at server side?

**Comment by manueliglesias** [comment]
Hi @jeremywhittington 

Yeah, the basic idea is to send the token(s) to your backend, and then your backend validates the tokens and their claims.

Some references:

- [Access Your Server-side Resources with a User Pool
](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-scenarios.html#scenario-backend)

- [Verifying a JSON Web Token
](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html)

> If you need to manually process tokens for server-side API processing, or if you are using other programming languages, there are many good libraries for decoding and verifying a JWT. See the [OpenID Foundation list of libraries for working with JWT tokens](http://openid.net/developers/jwt/).

**Comment by powerful23** [comment]
Closing this issue due to no further response. Feel free to reopen if you still have this issue.

**Comment by danzuck** [comment]
What if you are using a Federated login like Facebook?

**Comment by ddennis** [comment]
Is there any way to get an idToken or other token which can be used with both Federated Login user pools?
