### ISSUE TITLE
XR Scene not loading 

### ISSUE THREAD

**Issue by rajababu3** [aws-amplify/amplify-js#2221]
**Which Category is your question related to?** 
General Usage Question
**What AWS Services are you utilizing?**

Amplify XR

**Provide additional details e.g. code snippets**

I am trying my hands on Sumerian and used [this](https://aws-amplify.github.io/docs/js/xr)  guide to setup xr in my react project.

I have made two scenes one private and other public. I have enabled auth role for sumerian. 
For public scene I used iframe and scene loads. 
Private scenes are not loading and there is no error in the code. 
I followed this medium post  [Link](https://hackernoon.com/building-ar-vr-experiences-with-react-amazon-sumerian-aws-amplify-789976db1689) to setup and configure my project.

**Comment by jordanranz** [comment]
Hi @rajababu3,

By "no error in the code" do you mean no error in the browser console or that your code matches the example?

Can you provide a bit more detail on what is logged in the console.

A few additional questions:
- Do you see anything like: "[Sumerian] Loaded Sumerian Engine Version".  in your console log?
- Have you signed up and signed into your application using the Auth UI (withAuthenticator)?
- Have you sized the containing div for the scene? (Note that whatever dom element you use to load your scene with adapt it's size to the parent dom element)

**Comment by rajababu3** [comment]
Hi @jordanranz 
Problem is solved using new SumerianScene Component from aws-amplify-react.

**Comment by jordanranz** [comment]
I will close this issue for now then. Please reopen if you have any related issue.
