### ISSUE TITLE
Federated auth not restored synchronously (React Native)

### ISSUE THREAD

**Issue by willdady** [aws-amplify/amplify-js#2237]
**Describe the bug**
Amplify's doesn't initialise federated sign-in synchronously. My app performs a few API requests on mount however these initial ones fail. **It begins to work after an arbitrary amount of time (a second? next tick?).**

**To Reproduce**

This is my entry file, `index.js`, for my React Native app and assumes you've previously authenticated with `Auth.federatedSignIn()`. Note calling `Auth.currentCredentials()` resolves with an error however calling `Auth.currentCredentials()` after an artificial delay of 2 seconds yields a successful response!?!

``` javascript
import { AppRegistry } from 'react-native';
import Amplify, { Auth } from 'aws-amplify';
import Config from 'react-native-config';
import delay from 'lodash/delay';
import App from './App';

Amplify.Logger.LOG_LEVEL = 'DEBUG';

Amplify.configure({
  Auth: {
    identityPoolId: Config.AWS_IDENTITY_POOL_ID,
    region: Config.AWS_REGION,
    refreshHandlers: {
      [Config.AUTH0_DOMAIN]: async () => {
        // Code omitted
      }
    }
  },
  API: {
    endpoints: [
      {
        name: 'GoodWorkAPI',
        endpoint: Config.API_DOMAIN,
        region: Config.AWS_REGION,
        custom_header: async () => ({
          'Content-Type': 'application/json; charset=utf-8',
          'GW-Client-App': Config.API_APPLICATION
        })
      }
    ]
  }
});

// This yields an error, 'Unauthenticated access is not supported for this identity pool.'
Auth.currentCredentials()
  .then(creds => console.log('~~~~ CREDS', creds))
  .catch(err => console.log('~~~~ CREDS ERR', err));

// This works fine!?!
delay(() => {
  console.log('****** Delayed call! ******');
  Auth.currentCredentials()
    .then(creds => console.log('~~~~ CREDS', creds))
    .catch(err => console.log('~~~~ CREDS ERR', err));
}, 2000);

AppRegistry.registerComponent('Goodwork', () => App);
```

**Expected behavior**
Amplify should initialise synchronously and the federated signin should be restored without delay.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone6 (Simulator)
 - OS: iOS8.1

**Comment by willdady** [comment]
@powerful23 I believe the problem is `Auth.currentUserCredentials()` is trying to read from storage BEFORE `storage.sync()` has been called. I noticed I was getting the following error with DEBUG enabled.

```
[DEBUG] 34:38.734 AuthClass - failed to get or parse item aws-amplify-federatedInfo: SyntaxError: Unexpected token u in JSON at position 0
```

I'm able to hack around the problem by monkey patching `Auth.currentUserCredentials` as follows.

```
// BEGIN HACK!
const storage = new StorageHelper().getStorage();

const origCurrentUserCredentials = Auth.currentUserCredentials;

Auth.currentUserCredentials = async () => {
  await storage.sync();
  return origCurrentUserCredentials();
};
// END HACK!

Amplify.configure({ ... });

// This now works!
Auth.currentCredentials()
  .then(creds => console.log('~~~~ CREDS', creds))
  .catch(err => console.log('~~~~ CREDS ERR', err));
```

**Comment by powerful23** [comment]
@willdady thanks for your feedback, will mark this as bug.
