### ISSUE TITLE
Forgot Password, Sign Up shows up when deployed to S3

### ISSUE THREAD

**Issue by jitsunen** [aws-amplify/amplify-js#2238]
**Describe the bug**
I have disabled Forgot Password and Sign Up functionality by using the following code in my react app: 

`export default withAuthenticator(App, true, [<SignIn />, <RequireNewPassword/>]);`

**Expected behavior**
On my local server, the Forgot Password and Sign Up links don't show on login page, however, once I build the app and deploy to S3, the Forgot Password and Sign Up appear on the login page.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I am using aws-amplify@1.1.0, aws-amplify-react@2.1.4

**Comment by chrishawes** [comment]
I'm experiencing the same issue, here are some steps to recreate:
```
npx create-react-app amplify-2238
cd amplify-2238
npm i aws-amplify aws-amplify-react --save
```

Edit `src/App.js` to be as follows:

```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import Amplify from 'aws-amplify'
import {
  withAuthenticator,
  SignIn,
  RequireNewPassword
} from 'aws-amplify-react';

Amplify.configure({
  Auth: {
    mandatorySignIn: true,
    region: 'eu-west-1',
    userPoolId: 'redacted',
    identityPoolId: 'redacted',
    userPoolWebClientId: 'redacted'
  }
});

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <p>
            Edit <code>src/App.js</code> and save to reload.
          </p>
          <a
            className="App-link"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Learn React
          </a>
        </header>
      </div>
    );
  }
}

export default withAuthenticator(App, false, [<SignIn />, <RequireNewPassword/>]);
```

Run `npm start` - in your browser you'll see the signup component is absent.
Run `npm run build` to create your production build.
Serve your production build. Running `npx serve -s build` will do it.

Visit your production build URL and you'll see you'll see the signup component is rendered.
