### ISSUE TITLE
Ability to edit documents stored in S3

### ISSUE THREAD

**Issue by oluomoniyi** [aws-amplify/amplify-js#2239]
Which Category is your question related to? 
AWS Amplify Storage

What AWS Services are you utilizing?
S3

So guys I am building this app where users can upload documents to S3 via a frontend, download, delete etc However there is a requirement to edit documents (specifically word documents), I was wondering does anyone know of any solutions for this?

I know I can get the user to download the document edit the document locally and then reupload but that is not the best user experience.

**Comment by YikSanChan** [comment]
I believe [Storage#put](https://aws-amplify.github.io/docs/js/storage#put) is what you need.

**Comment by oluomoniyi** [comment]
Hiya @YikSanChan, my question probably wasn't clear enough I am aware of the Storage.put method this is what I kinda explained here "I know I can get the user to download the document edit the document locally and then reupload but that is not the best user experience." in pseudocode terms Storage.get(doc) => edit document locally => Storage.put(doc)

@jordanranz yes an in-broswer document editor will be perfect!

**Comment by YikSanChan** [comment]
Seems `Storage.get(doc) => edit document locally => Storage.put(doc)` is the only way, as long as `locally` means users edit text on the `<textarea/>` or `<div/>` of the web app.

**Comment by oluomoniyi** [comment]
Thanks a lot, solved it, I used fetch this document editor https://ej2.syncfusion.com/react/demos/#/material/document-editor/default

I used Storage.get(key) to retrieve the publicFileURL then used the snippet below to create a file and then sent that file into my document editor above and then I hooked up the Storage.put method into the save button functionality in the editor. 

Lots of semi hackScript but it seems to work well so far.

```js
fetch(publicFileURL)
  .then(res =>
    res.blob().then(blob => {
        const file = new File([blob], "fileName", {
          type:
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
      });

     doSomethingWithFile(file)

    })
  )
  .catch(e => console.log(e));
```
