### ISSUE TITLE
Password is sent in the clear on SignUp (within Request Payload)

### ISSUE THREAD

**Issue by JasonLunsford** [aws-amplify/amplify-js#2243]
**Describe the bug**
When executing the Sign Up API, within the Request Payload the user's password is exposed in clear text.

**To Reproduce**
1. Go to a basic implementation of Auth.signUp (requires username, password, attributes).
2. Watch the network traffic, especially pay attention to failed (400 on POST) Sign Ups (these are easier to catch).
3. Drill into the Request Payload. Look at the password - in clear text!

**Expected behavior**
The password typed by the user and passed into Auth.signUp should be masked. I assume there IS a way to do this and I simply cannot find the right documentation.

**Desktop (please complete the following information):**
 - OS: MacOS X
 - Browser: Chrome
 - Version 70.0.3538.77

**Additional context**
This occurs when doing a regular SignUp. The request payload contains the password, and the password is in clear text. That's the security issue. Either I'm doing something wrong or there's a defect.

![screen shot 2018-12-03 at 15 33 31](https://user-images.githubusercontent.com/636314/49400269-ba7c1980-f711-11e8-945f-019dda8b6379.png)

**Comment by richardzcode** [comment]
Hey @JasonLunsford the payload is sent over `https`, the clear text is only viewable by user him/herself who typed the password in. In terms of security concern we need to make sure 1) everything over `https`; 2) do not store sensitive data in local storage / cookies. Masking payload is doable but comes with cost, requires server support. Most website don't do that. I just checked a banking site I can see my password in payload too :)

**Comment by JasonLunsford** [comment]
That makes sense actually. HTTPS would protect the password in flight. Thank you for pointing that out. I'm happy to close this thread unless anymore remains to be added.
