### ISSUE TITLE
Search from DynamoDB 

### ISSUE THREAD

**Issue by omkarkhalipe** [aws-amplify/amplify-js#2244]
I have been able to implement almost all features using Amplify library, but I am not able to search users and also I am not able to add pagination while retrieving list.
Not sure if get method is capable of these features

**Comment by YikSanChan** [comment]
You are able to do both.

Pagination: https://docs.aws.amazon.com/appsync/latest/devguide/designing-your-schema.html#advanced-relations-and-pagination
Search: https://aws-amplify.github.io/docs/cli/graphql#searchable

**Comment by omkarkhalipe** [comment]
Yes

**Comment by omkarkhalipe** [comment]
@YikSanChan, is it possible with REST API?

**Comment by YikSanChan** [comment]
> @YikSanChan, is it possible with REST API?

Sorry I have no context around REST API usage with Amplify.

**Comment by jordanranz** [comment]
@omkarkhalipe that should be possible. It depends on how you REST endpoint is configured.

If you are using API gateway, here is a related tutorial:
https://aws.amazon.com/blogs/compute/using-amazon-api-gateway-as-a-proxy-for-dynamodb/

**Comment by jordanranz** [comment]
I will close this issue for now, please reopen if the answer above does not solve your question :)
