### ISSUE TITLE
Getting 403 Error on API calls, its redirect to `Prod` stage default, facing CORS issue

### ISSUE THREAD

**Issue by pallavparikh** [aws-amplify/amplify-js#2247]
I have react web app, I have set up Auth, Function, Api using amplify CLI. ( version 0.1.35 )

When I try to access my back-end function through api gateway, its default add `/Prod` route to my endpoints. for example

```
API.get("apiname", "/xyz/func1")
     .then(response => console.log(response))
     .catch(err => console.log(err));
```
above call is goes to `https://adayuwhrvbe.execute-api.eu-west-1.amazonaws.com/Prod/xyz/func1 `instead of `https://adayuwhrvbe.execute-api.eu-west-1.amazonaws.com/xyz/func1`

and I am hitting 403

`POST https://adayuwhrvbe.execute-api.eu-west-1.amazonaws.com/Prod/xyz/func1   => 403`

Also, I am running in to following issues even if I manually enable CORS on Api Gateway on my api

`Access to XMLHttpRequest at 'https://adayuwhrvbe.execute-api.eu-west-1.amazonaws.com/Prod/xyz/func1' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

there was issue earlier https://github.com/aws-amplify/amplify-js/issues/1654 with earlier version

Not sure if I am doing something wrong, or its bug. 

any thoughts ?

**Comment by rmitula** [comment]
Did you figured it out?

**Comment by gerrytsui** [comment]
In our environment we add the equivalent of "Prod" to the AWS API Gateway console -> Custom Domain Names -> Base Path Mappings -> Path. 
My guess is you(someone) specified  "Prod" there.
