### ISSUE TITLE
Recreate a Cognito user from the access, id and refresh tokens

### ISSUE THREAD

**Issue by asnaseer-resilient** [aws-amplify/amplify-js#2253]
** Which Category is your question related to? **
amazon-cognito-identity-js

** What AWS Services are you utilizing? **
Cognito User Pools

** Provide additional details e.g. code snippets **
We have several development teams in our company, each one responsible for a specific product. We all use _Cognito User Pools_ for authentication and one of our teams (**Authentication Team**) has written a login service that presents the user with a login form and, upon successful login, sets sessions cookies for each of the 3 Cognito tokens (i.e. _Access_, _ID_, and _Refresh_).

Our team is developing a web front end for managing Cognito Users. We login by redirecting the user to the login service (developed by our **Authentication Team**) passing it a URL to redirect back to upon successful login. This all works fine and we have access to all 3 Cognito tokens in our Web application after the user has logged in (via session cookies).

We now want to manage the Cognito users in the User Pool by making use of your **amazon-cognito-identity-js** library.

The problem we are facing is - how do we create a **CognitoUser** from the tokens that we have?

**Comment by asnaseer-resilient** [comment]
@powerful23 Thanks for your response. I myself was on holiday and only just got back - hence my late response :)

**Comment by oenayet** [comment]
@powerful23  Is there a way to do the same via the C++ Cognito SDK?
