### ISSUE TITLE
Vue project is throwing `Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'`

### ISSUE THREAD

**Issue by murribu** [aws-amplify/amplify-js#2254]
When initializing an amplify project in Vue, an error is thrown: `Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'`

**To Reproduce**
```bash
$ vue init webpack-simple my-project
> [Select All Defaults]
$ cd my-project
$ npm i
$ npm run dev
```
Works fine! Hooray!
```bash
$ npm i aws-amplify aws-amplify-vue
```
Make changes to main.js and App.vue, per https://aws-amplify.github.io/docs/js/vue
```bash
$ amplify init
> [Select All Defaults]
$ amplify push
$ npm run dev
```

**Screenshots**
![image](https://user-images.githubusercontent.com/5056153/49522138-9254fd80-f86c-11e8-820e-f465f568542b.png)

**Desktop (please complete the following information):**
 - OS: Linux 16.04 LTS
 - Browser Chrome
 - Version 70.0.3538.110
```bash
$ node -v
v10.14.1
$ npm -v
6.4.1
```

**Comment by binarytide** [comment]
I'm also experiencing this issue, stopped me dead in my tracks for 2 days now.

**Comment by haverchuck** [comment]
We think there may be a dependency issue broken upstream - we are looking at it currently.

**Comment by haverchuck** [comment]
@murribu @binarytide  - We just merged a fix for this into our unstable branch. Please feel free to npm install aws-amplify-vue@unstable to access it.

**Comment by felimartina** [comment]
Just came across this issue.
Using the `unstable` version fixed it for me. Spent 1 hour troubleshooting thou :(

**Comment by lotjuh** [comment]
> Just came across this issue.
> Using the `unstable` version fixed it for me. Spent 1 hour troubleshooting thou :(

Only 1 hour?.... I spend 1,5 day on this )-:
I'm new to node.js and been thinking I was doing something wrong. Have been googling the error as well but didn't get to this issue until I ran into some other problem with I18n and just ctrl-f'ed 'exports' on all issues here as well (-;
Luckily using the unstable version also fixed my issue with I18n

**Comment by felimartina** [comment]
@lotjuh I know the feeling!
I was lucky 'cause I had ampify working before on a different project and came across this issue while helping a colleague to setup his project...so I assumed it was a problem with amplify version.

Never ending story of JS/NPM ecosystem...

**Comment by haverchuck** [comment]
@murribu @lotjuh  @felimartina @binarytide  - The fix for this should now be merged into our main build, so I'm closing the issue for now.  However, if you continue to experience the issue after installing the latest version please feel free to re-open it.  

Thank you for your patience and for testing out the fix on our unstable tag.
