### ISSUE TITLE
Amplify Interactions integration with Sumerian Lex Actions (state machines/behaviors), Share Conversation Context with Embedded Scenes

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-js#2255]
**Is your feature request related to a problem? Please describe.**
Currently we have use cases where we would like to have a container Amplify site containing a privately published Sumerian scene by leveraging the XR category. In this Sumerian scene, we have a state machine similar to the sample state machine suggested here by the Sumerian devs. 

<img width="1015" alt="download" src="https://user-images.githubusercontent.com/22964702/49526428-01caed00-f86d-11e8-8df0-7719385e5c97.png">

We have HTML5 elements in the Amplify site that need to interact with the Sumerian scene, primarily via responding to Lex responses. The Amplify site and Sumerian need to smoothly interact in general, especially w.r.t. handling Lex requests and responses.

**Describe the solution you'd like**
I would like the Interactions category to natively integrate with private Sumerian scenes, such that the Interactions module receives the same Lex responses that are received by the Sumerian scene after finishing the "Process With Lex" Action. I'd rather the Amplify Interactions category sitting in the container site receive Lex responses synchronously as the Sumerian Lex Actions.

I would also like the ability to bring Interactions into Sumerian and use the `send()` API to seamlessly pass control between a chatbot-like script (which is passed control in response to e.g. certain utterances), and the chatbot state machine, which is the main driver. (By seamless, I mean that the Interactions object in the Amplify site shares credentials, current state, and Lex conversation context, with the scene's active Lex session.)  This would give us the flexibility to locally handle utterances that require immediate attention, where even the latency of a Lex request might severely impact UX, while retaining the ability to let a relatively simple chatbot state machine with event listeners to handle the majority of Lex responses.

This integration would allow us to use an Execute Script Action to easily determine whether we need to pass control of the Lexbot to a special utterances script, or continue as normal to Lex, simply by parsing the input before sending it to Lex.

**Describe alternatives you've considered**
The clear alternative seems to be using the postMessage API to send any Lex Response from the Sumerian scene to the Amplify container site. This could also be used to copy the conversation context from Amplify site to Sumerian or vice versa. I'd rather not have to worry about passing credentials around and just let Amplify and Sumerian handle this integration natively.

**Comment by jordanranz** [comment]
Hey @jkeys-ecg-nmsu,

Thank you for submitting this feature request. This is an optimization that would require some work on both the Amplify and Sumerian side to execute. It is actually one of the first cross category features we talked about when developing the Sumerian Provider. I will add this as a task on our backlog to investigate the work required for this. I'll update this issue as soon as we make progress toward this feature.

**Comment by jkeys-ecg-nmsu** [comment]
@jordanranz Thank you! I agree that this falls squarely in the optimization category, but also the simplification (so neither the Amplify site nor Sumerian scene depend on the other forwarding the Lex response). 

Do you agree that postMessage API(s) (either window or maybe a web worker) is the best way to implement this in the meantime?

(Also, I'm looking to cut my teeth on contributing to FOSS projects; is this project looking for occasional contributors?)

**Comment by jkeys-ecg-nmsu** [comment]
@jordanranz any update on this FR? We're looking to do a minor architectural refactor and I want to determine whether Interactions might be useful for interacting with, at the least, the top-level scene (in a dynamically (pre-)loaded scene architecture that defers functionality to "sub-scenes").

**Comment by jkeys-ecg-nmsu** [comment]
No longer relevant to our use case.
