### ISSUE TITLE
How can I SELECT FIELD FROM MODEL with GraphQL?

### ISSUE THREAD

**Issue by YikSanChan** [aws-amplify/amplify-js#2256]
** Which Category is your question related to? **
AppSync

** What AWS Services are you utilizing? **
AppSync

** Provide additional details e.g. code snippets **
Let's assume I have defined the model in my Amplify app:
```graphql
type Item @model {
  id: ID!
  inventoryType: String!
  itemName: String!
  imgKey: String
}
```
I want to do things like:
```sql
SELECT DISTINCT(inventoryType) FROM Item;
```
As far as I know, I can use codegen listItems query to retrieve all items and compute distinct inventory types afterwards. But wonder if there are more straightforward way to do it.

**Comment by jordanranz** [comment]
Hi @YikSanChan,

Here are a few resources that may help you with this:
- https://stackoverflow.com/questions/52077167/appsync-query-on-global-secondary-index
- https://stackoverflow.com/questions/35036221/support-of-aggregate-function-in-graphql/35074801#35074801

**Comment by YikSanChan** [comment]
Thanks @jordanranz 

I believe DynamoDB+ElasticSearch is a more appropriate solution since aggregation/analytics is better served by ElasticSearch.
Closed in favor of https://github.com/aws-amplify/amplify-js/issues/2373, a more scoped (ElasticSearch) question
