### ISSUE TITLE
AuthClass - getting session failed: "No userPool"

### ISSUE THREAD

**Issue by Evokator** [aws-amplify/amplify-js#2259]
** Which Category is your question related to? **
Auth/Cognito/Storage
** What AWS Services are you utilizing? **
Auth/Cognito/Storage
** Provide additional details e.g. code snippets **
I'm fairly new to AWS and am having some issues. Currently when logging into our app the user has the ability to view and upload files to our S3 bucket using Storage.put(). When closing and reopening the app, although the user appears to be signed in, they no longer have the ability to view or upload the files. When trying to upload, an Access Denied error is thrown. 

It seems that the session isn't persisting after closing and reopening, and logs this:

`[DEBUG] 23:00.862 AuthClass - getting current authenticted user
 [DEBUG] 23:00.866 AuthClass - cannot load federated user from auth storage
[DEBUG] 23:00.866 AuthClass - get current authenticated userpool user
[DEBUG] 23:00.875 AuthClass - getting session failed: "No userPool"}
[DEBUG] 23:00.885 Credentials - setting credentials for guest`

Logging out, then back in fixes it, and the user is able to view and upload files again. We're using the withAuthenticator HOC:
`  export default withAuthenticator(App, false, [
      <SignIn />,
      <ConfirmSignIn />,
      <VerifyContact />,
      <RequireNewPassword />,
      <ForgotPassword />
   ]);
`

**Comment by jitsunen** [comment]
@Evokator , in case you have configured your user pool properly and your app suddenly stopped working, upgrade your aws-amplify and aws-amplify-react to latest versions. I had a similar problem yesterday and upgrading to latest solved the issue.

**Comment by Evokator** [comment]
@jitsunen @powerful23, Updating aws-amplify to "^1.1.12" and aws-amplify-react-native to ""^2.0.10" seems to have fixed the issue. Thank you, @jitsunen, for the suggestion!

**Comment by jordanranz** [comment]
Going to close this issue as you seemed to have resolved the issue. Please reopen if you are experiencing any related issues.
