### ISSUE TITLE
CognitoUser.updateAttributes gives user is not authenticated if user is logged in but MFA has not been completely setup

### ISSUE THREAD

**Issue by stephanie-sim-openx** [aws-amplify/amplify-js#2260]
** Which Category is your question related to? **
Authentication

** What AWS Services are you utilizing? **
Cognito / amazon-cognito-identity-js

** Provide additional details e.g. code snippets **

**Situation:** 
- Admin creates a user with a temporary password using only email. Phone number is not set. (User pool has MFA as required. )
- User logs in using their email and temporary password. We redirect them to a page to set their new password. 
- After the user enters their new password and we save the new password, it's indicated that mfaSetup is needed so they are redirected to a page to set their phone number to complete the MFA setup. 

**Problem:**
CognitoUser.updateAttributes is not letting us update their phone number so we can start the phone number verification process. Also we want to be able to update the phone number if for some reason they screw up and need to send the code again.
Problem appears to be in this section of code. https://github.com/aws-amplify/amplify-js/blob/master/packages/amazon-cognito-identity-js/src/CognitoUser.js#L983) and the fact that the signInUserSession isn't getting set until all setups are done (https://github.com/aws-amplify/amplify-js/blob/master/packages/amazon-cognito-identity-js/src/CognitoUser.js#L464)

I'm unsure if there is a step I might be missing or if this is a problem with the code as linked above.

**Comment by powerful23** [comment]
@stephanie-sim-openx is the `phone_number` a required attribute in your user pool? If so, you will need to pass it when calling `completeNewPasswordChallenge`

**Comment by stephanie-sim-openx** [comment]
@powerful23 no it's not a required attribute.

**Comment by powerful23** [comment]
@stephanie-sim-openx hi, I tried to reproduce your case but instead I got this error when submitting the new password: `{"__type":"MFAMethodNotFoundException","message":"No MFA mechanism registerd in the account."}`. 

I created a user pool with:
1.  `phone number` not required.
2.  MFA required, SMS enabled

Then I created a new user with temporary code and email using Cognito console. 

Are those steps the same for you?

**Comment by stephanie-sim-openx** [comment]
Our user pool has these settings:
- `email` is required and `phone_number` is NOT required
- MFA required
- SMS is enabled
- TOTP is enabled
- We only require verification of email (should this be changed if we want to do MFA with SMS?)
- Advanced Security settings is off

Yes we've been creating the user through the Cognito console:
- Username is set to email
- Temporary password is set
- Phone number is empty
- Email is set and marked as verified
