### ISSUE TITLE
Is there any good way to implement Linkedin authentication?

### ISSUE THREAD

**Issue by risingtalent22** [aws-amplify/amplify-js#2278]

**Comment by jkeys-ecg-nmsu** [comment]
In the absence of native integration, I believe you can implement your own authentation UI & logic to get the LinkedIn tokens, and then use [AdminLinkProviderForUser](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminLinkProviderForUser.html) to federate their LinkedIn identity with their user in the user pool. (@jordanranz is this correct?)
