### ISSUE TITLE
React Native - withAuthenticator - Custom Greetings UI

### ISSUE THREAD

**Issue by jessedoyle** [aws-amplify/amplify-js#2281]
** Which Category is your question related to? **

* Authentication

** What AWS Services are you utilizing? **

* Cognito, AppSync

Hi There! Is it possible to replace the built in `Greetings` component in `aws-amplify-react-native` with a custom component when using `withAuthenticator`?

From looking at the related code for `withAuthenticator` [here](https://github.com/aws-amplify/amplify-js/blob/02ee1d6aa6481f1ef55eacf1444159998cb62ea6/packages/aws-amplify-react-native/src/Auth/index.js#L83-L88) it appears that the Amplify's built-in `Greetings` component is hard-coded.

We've followed the documentation for custom UI [here](https://aws-amplify.github.io/docs/js/authentication#create-your-own-ui) and have successfully built our own components for `SignIn`, etc. Unfortunately we have been unable override `Greetings`.

**Comment by jessedoyle** [comment]
@jordanranz - I did try the overrides as per the documentation you linked without luck. I'm going to revisit our code today and see if we're making any mistakes.

If I'm able to build anything reproducible that illustrates the issue, I'll report back!

**Comment by jordanranz** [comment]
hey @jessedoyle,

Could you post some code of the overridden Greetings component and how you passed it to withAuthenticator. This would help us debug a bit further.

**Comment by jordanranz** [comment]
Glad you got this working! 

I think your solution is the preferred way to achieve what you are asking for. Since the Greetings component simply provides a UI wrapper for sign out and username text, it is simpler to use the Auth method mentioned above and create your own Header above your app. I will close this for now. Please reopen if you experience any related issue.

**Comment by gkpty** [comment]
Hi Guys!

Im also having some issues customizing authentication. Im trying to customize my withauthenticator as follows:

```
  const MyTheme = {
  googleSignInButton: { backgroundColor: "red", borderColor: "red" },
  button: { backgroundColor: "green", borderColor: "red" },
  signInButtonIcon: { display: "none" }
};

const signUpConfig = {
  header: 'My Customized Sign Up',
  hideAllDefaults: true,
  signUpFields: [
    {
      label: 'Email',
      key: 'email',
      required: true,
      displayOrder: 1,
      type: 'string'
    },
    {
      label: 'Username*',
      key: 'username',
      required: true,
      displayOrder: 1,
      type: 'string'
    },
    {
      label: 'Password',
      key: 'password',
      required: true,
      displayOrder: 2,
      type: 'password'
    },
  ],
};

export default withAuthenticator(App, false, [
<SignIn/>,
  <SignUp/>,
  <ForgotPassword/>,
  <RequireNewPassword/>
], null, MyTheme, {signUpConfig});
It appears that i can only either pass the auth components array (& theme) or the signUpConfig object but not both.
```
Any idea on how i can do both?

Thanks!!

**Comment by evah88** [comment]
@jessedoyle Can you please share the exact code you used to trigger sign out using `onStateChange`?
We tried to do the same without luck.

> Hi @jordanranz! Thanks for reminding me of this issue!
> 
> We ended up going down an alternate path to achieve the same results (I'll explain this later), but I can give a brief overview of the issue we encountered.
> 
> Unfortunately I don't have the exact code we had written handy, but it was similar to this:
> 
> ```js
> // App.js
> import React from 'react';
> import { StyleSheet } from 'react-native';
> import { withAuthenticator } from 'aws-amplify-react-native';
> import { 
>   Greetings,
>   Loading,
>   SignIn,
>   ForgotPassword
> } from './customAuth';
> 
> const authComponents = [
>   <Greetings />
>   <Loading />,
>   <SignIn />,
>   <ForgotPassword />,
> ]
> 
> const App = ...
> 
> export default withAuthenticator(
>   App,
>   false,
>   authComponents,
>   null,
>   StyleSheet.create({
>     container: {
>       flex: 1,
>     },
>   }),
> );
> 
> // customAuth/Greetings.js
> import React from 'react';
> import { 
>   Text,
>   View
> } from 'react-native';
> import { Auth } from 'aws-amplify';
> import { Greetings } from 'aws-amplify-react-native';
> 
> export default class CustomGreetings extends Greetings {
>   render() {
>     const name = Auth.user && Auth.user.username;
>     const message = `Hello, ${name}`;
> 
>     return (
>       <View>
>         <Text>{message}</Text>
>       </View>
>     );
>   }
> }
> ```
> 
> Unfortunately this approach didn't work for us and the custom Greetings component didn't appear to display in the `Authenticator` component.
> 
> I wasn't able to troubleshoot the root issue, but I believe the custom `Greetings` component was not displayed due to the following:
> 
> * The `Greetings` component defines a  [`render` function](https://github.com/aws-amplify/amplify-js/blob/0112b4cd29ac96d9d2cd51051a3c930c1d9475e6/packages/aws-amplify-react-native/src/Auth/Greetings.js#L44) as opposed to a `showComponent` function.
> * The `Greetings` class does not set the `_validAuthStates` property in the constructor ([example](https://github.com/aws-amplify/amplify-js/blob/0112b4cd29ac96d9d2cd51051a3c930c1d9475e6/packages/aws-amplify-react-native/src/Auth/Loading.js#L24)).
> 
> The approach we ultimately went forward with was creating our own custom component to display the user message by reading from `Auth.currentAuthenticatedUser()` directly. Our custom component was able to initiate a sign out by utilizing the [`onStateChange` prop](https://github.com/aws-amplify/amplify-js/blob/0112b4cd29ac96d9d2cd51051a3c930c1d9475e6/packages/aws-amplify-react-native/src/Auth/index.js#L86) that is passed down from `withAuthenticator`.
> 
> I would say we were able to work around the issue we were encountering, so feel free to close this issue if necessary.

**Comment by jessedoyle** [comment]
@evah88 - We moved to the `withOAuth` HOC (see: https://github.com/aws-amplify/amplify-js/pull/2665) to handle authentication so our code in this area has changed significantly.

Looking at some of our older commits, the code we had when using `withAuthenticator` to logout was similar to this:

```js
async logout() {
  await Auth.signOut();
  // onStateChange function passed in as a prop from withAuthenticator
  this.props.onStateChange('signedOut');
}
```

**Comment by nihp** [comment]
I have my UI as same from the aws-amplify-react-native.

Now I needs to change for the custom UI.

If I change my UI, Shall I add the withAuthenticator and the screens.

I have AuthenticatorScreen.js file (<Loading/>, <SignUp/> etc...) before. It has all the screens from aws-amplify-react-native. 

How to add my custom screens inside the Authenticator.

The withAuthenticator file has an app. How it will be handled.

(or)

Shall I need to add all the screens in stackNavigator and create the navigations and add the Auth.signin and so on to do all the login methods.
