### ISSUE TITLE
Add typings support for aws-amplify-react-native

### ISSUE THREAD

**Issue by adrianhall** [aws-amplify/amplify-js#2286]
**Is your feature request related to a problem? Please describe.**

When developing a React Native app with aws-amplify-react-native, adding the following line:

```typescript
import { withAuthenticator } from 'aws-amplify-react-native';
```

results in the following warning:

```
{
	"resource": "/Users/adrianha/GitHub/restaurant-reviews/mobile-app/src/screens/UserScreen.tsx",
	"owner": "typescript",
	"code": "7016",
	"severity": 8,
	"message": "Could not find a declaration file for module 'aws-amplify-react-native'. '/Users/adrianha/GitHub/restaurant-reviews/mobile-app/node_modules/aws-amplify-react-native/dist/index.js' implicitly has an 'any' type.\n  Try `npm install @types/aws-amplify-react-native` if it exists or add a new declaration (.d.ts) file containing `declare module 'aws-amplify-react-native';`",
	"source": "ts",
	"startLineNumber": 1,
	"startColumn": 35,
	"endLineNumber": 1,
	"endColumn": 61
}
```

**Describe the solution you'd like**

Generate and publish typings information that is distributed with aws-amplify-react-native.

**Describe alternatives you've considered**

I have added a custom typings file to my project that provides this information.

**Comment by fantapop** [comment]
@adrianhall will you share your types?

**Comment by adrianhall** [comment]
I don't have that project available any more.

**Comment by dantasfiles** [comment]
> will you share your types?

I'm using these: https://github.com/dantasfiles/AmplifyReactNativeTypes

**Comment by andrekovac** [comment]
@dantasfiles how can I use them? Where should I place this type definition in my project so that it works?

**Comment by jstrunk** [comment]
Why doesn't this just work? The module is written in Typescript, but the build script does not include the declaration files. I tried adding `tsc --emitDeclarationOnly`,  but so far there are many errors. I'm going to try to work through them.

Are there any insights for why this module was written in Typescript but get built without the declaration files? This seems more like a bug than a feature request.

**Comment by joedevgee** [comment]
Since the library is written in Typescript, one should expect typings work out-of-box. Is this some build config that the amplify team can easily fix? It's been two years

**Comment by Kamran21** [comment]
Any updates on this, 

You would expect to have typescript support with type definition out of the box,
It seems that any project now and a specially with the scale of amplify to be with typescript in mind.

Not recommended, But for now I ended up with:

// @ts-expect-error
import { withAuthenticator } from "aws-amplify-react-native";
// @ts-expect-error
import config from "./aws-exports";

**Comment by fredlemieux** [comment]
> @dantasfiles how can I use them? Where should I place this type definition in my project so that it works?

I'd like to bump this question.  I've downloaded the .d.ts file and put it in my types folder, but I'm still getting Type errors.  How do I include this in my project? I've tried to add it to my "include":[] array it in my tsconfig file.

**Comment by dantasfiles** [comment]
@fredlemieux  In the past, I've used it by placing [`aws-amplify-react-native.d.ts`](https://github.com/dantasfiles/AmplifyReactNativeTypes/blob/master/aws-amplify-react-native.d.ts) in the base directory of a project, and by placing the file in `./src/types` of a project. Visual Studio Code seemed happy either way. Maybe there's some difference between my [`tsconfig.json`](https://github.com/dantasfiles/AmplifyReactNativeTypes/blob/master/tsconfig.json) and yours?

**Comment by George-S-Mulbah** [comment]
@dantasfiles I downloaded the file   too but still facing trouble on how to implement it in my typescript React-native template

**Comment by ajitsinghmalra** [comment]
@George-S-Mulbah did u get past this somehow ?


Placing aws-amplify-react-native.d.ts in root folder of the Project makes vscode happy but when I install the bundle on iPhone simulator it complains of this :



To reload the app press "r"
To open developer menu press "d"

 BUNDLE  ./index.js 

 ERROR  TypeError: (0, _$$_REQUIRE(_dependencyMap[6], "aws-amplify-react-native").WithAuthenticator) is not a function. (In '(0, _$$_REQUIRE(_dependencyMap[6], "aws-amplify-react-native").WithAuthenticator)(App)', '(0, _$$_REQUIRE(_dependencyMap[6], "aws-amplify-react-native").WithAuthenticator)' is undefined)
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

**Comment by ajitsinghmalra** [comment]
While aws-amplify-react-native.d.ts  was giving me some errors pasted above and it seems that I had to little more stuff like including aws-amplify-react-native.d.ts  in ts-config.json but  this simple  ignore worked for me to move forward 


// @ts-ignore
import Amplify, { Auth } from 'aws-amplify';
// @ts-ignore
import awsconfig from './aws-exports';
// @ts-ignore
import { withAuthenticator } from 'aws-amplify-react-native'

Amplify.configure(awsconfig);

**Comment by camello222** [comment]
WHy hasn't this been solved yet? It's been almost three years.

**Comment by eettaa** [comment]
+1 to resolving this issue

**Comment by Weixuanf** [comment]
+1 hope to resolve this issue

**Comment by kwesimanny** [comment]
+1 hope to resolve this issue

**Comment by Dashue** [comment]
Another +1
@jamesaucode I saw may currently be giving feedback on typescript related pr's so I thought I'd tag you in hopes of you being able to give input or tag someone that may be able to help with this one?

**Comment by EvanErickson** [comment]
+1 Still not resolved as of 2022-04-06

**Comment by crutchcorn** [comment]
I would like to work on this issue and introduce `.d.ts` generation to the `aws-amplify-react-native` package.

For now, I introduced #10442 to fix TypeScript typing errors from strict mode usage in TS. Once this is merged/resolved, we can work around this temporarily by adding in a `.d.ts` file in consuming app's codebases:

```
declare module "aws-amplify-react-native" {
  export * from "aws-amplify-react-native/src/index";
}
```

**Comment by abdallahshaban557** [comment]
Hello everyone, the aws-amplify-react-native library is on its path to deprecation. We are planning on introducing a new Authenticator library that would live in the [Amplify UI](https://github.com/aws-amplify/amplify-ui) repository.

**Comment by tannerabread** [comment]
This should now be handled with the new React Native UI Component as @abdallahshaban557 mentioned in the previous message. It can be used as shown in [this link](https://ui.docs.amplify.aws/react-native/connected-components/authenticator#step-3-add-the-authenticator) and clicking on the `withAuthenticator` tab in that section. Note that `withAuthenticator` is now imported through the package `@aws-amplify/ui-react-native`.

If someone could test this out and verify that the error no longer shows up that would be great

**Comment by tannerabread** [comment]
Closing as this should be better handled with the new React Native Authenticator components, link to the documentation in my previous comment. If you are still experiencing issues with the new components, please feel free to open an issue in the [amplify-ui repo](https://github.com/aws-amplify/amplify-ui).

Thank you!
