### ISSUE TITLE
Amplify GraphQL Request "Missing authorization header"

### ISSUE THREAD

**Issue by mwarger** [aws-amplify/amplify-js#2288]
**Describe the bug**
While using the API.graphql call - I'm receiving a GraphQL error that says "Request failed with status code 401".  The underlying network request fails:

errorType: "UnauthorizedException"
message: "Missing authorization header"

**To Reproduce**
1. Setup a multi-environment project with a single environment using Amplify-CLI
2. Deploy everything
3. Run a graphQL query

**Expected behavior**
The request should work.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

I don't get much back in the way of logs or any other errors, so I know this is a little sparse.  I'm happy to answer any questions.

**Comment by mwarger** [comment]
I believe this was a result of migration using the amplify-cli.  This is no longer happening and I haven't been able to recreate this problem since reporting this issue.  Closing for now.

**Comment by ajhool** [comment]
I'm having this issue as well. I have an original project that I created using amplify-cli and then I tried to create a different frontend project (typescript) using the same amplify configuration. Everything (everything I've noticed :) ) looks the same but the Authorization header isn't being attached, even though the user is authenticated and the Auth token is retrieved.

**Comment by dbramwell** [comment]
May not be of much use for me to do this, but I also have the issue of `"aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"` not being added to aws-exports.js

This started happening for me today after upgrading to @aws-amplify/cli@multienv

**Comment by BrianFarnhill** [comment]
I'm in the same boat as @dbramwell here, I upgraded my project to the multienv stuff today and that's what broke this for me from what I can tell. I can also confirm that running `amplify update api` seemed to do the trick for me as well.

**Comment by dbramwell** [comment]
Yeah, the issue kept reoccurring for me every time I switched environment. Luckily I wasn't far into the project, so just ditched my stack and started from scratch with the multi env cli.

**Comment by BrianFarnhill** [comment]
@dbramwell Yea I find it happens whenever i check out an environment as well. So you're saying it doesn't happen on a project that was created with the new version though, as opposed to one that was created in an older version and then upgraded to the mutilenv stuff? If so I might spin up a new one from scratch and see if I can play spot the difference in the config of that to the migrated one - there might be a setting somewhere in one of the config files that got lost or something. If I find anything use I'll share it here.

**Comment by lorensr** [comment]
For me the problem was I had:

```js
import AWSAppSyncClient, { AUTH_TYPE } from 'aws-appsync'
import aws_config from '../aws-exports'

const client = new AWSAppSyncClient({
  url: aws_config.aws_appsync_graphqlEndpoint,
  region: aws_config.aws_appsync_region,
  auth: {
    type: AUTH_TYPE.API_KEY,
    apiKey: aws_config.aws_appsync_apiKey
  }
})
```

Fixed with:

```js
import AWSAppSyncClient, { AUTH_TYPE } from 'aws-appsync'
import { Auth } from 'aws-amplify'
import aws_config from '../aws-exports'

const client = new AWSAppSyncClient({
  url: aws_config.aws_appsync_graphqlEndpoint,
  region: aws_config.aws_appsync_region,
  auth: {
    type: AUTH_TYPE.AMAZON_COGNITO_USER_POOLS,
    jwtToken: async () =>
      (await Auth.currentSession()).getIdToken().getJwtToken()
  }
})

```

**Comment by ajhool** [comment]
Is everybody else still experiencing this issue ( where "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS" ) is not automatically added to `aws_exports.js`?

I've checked the source code and don't see an obvious reason why this bug exists because it appears to be adding the field -> 

https://github.com/aws-amplify/amplify-cli/blob/13d9fc3fa32be5fc6be454fe91e0de0bb7226bef/packages/amplify-frontend-javascript/lib/frontend-config-creator.js

```
function getAppSyncConfig(appsyncResources, projectRegion) {
  // There can only be one appsync resource
  const appsyncResource = appsyncResources[0];
  return {
    aws_appsync_graphqlEndpoint: appsyncResource.output.GraphQLAPIEndpointOutput,
    aws_appsync_region: projectRegion,
    aws_appsync_authenticationType: appsyncResource.output.securityType,
    aws_appsync_apiKey: appsyncResource.output.GraphQLAPIKeyOutput || undefined,
  };
}
```

I have not done much research, but my best guess is that `appsyncResource.output.securityType` is undefined and somewhere along the line, amplify is removing any undefined fields from the config output
