### ISSUE TITLE
Usage between amplifyService.authStateChange$ and onHubCapsule

### ISSUE THREAD

**Issue by jocactus** [aws-amplify/amplify-js#2290]
**Which Category is your question related to?**
Authentication with Angular

**What AWS Services are you utilizing?**
Amazon Cognito Hosted UI

**Provide additional details e.g. code snippets**
I configured Amazon Cognito Hosted UI in my Angular project with `onHubCapsule` to handle authentication events.

The things is I also have `this.amplifyService.authStateChange$` to  listen for auth state changes.

For me it seems like I have a duplicate between these two listeners.

Is it possible to clarify the usage of these two listeners?

Thanks for you help.

**Comment by haverchuck** [comment]
The amplifyService.authStateChange uses Hub under the covers, but also employs an 'authDecorator' which does some additional parsing of the auth state to provide more granular information like whether mfa is required.  Using the Hub is probably enough if you are just concerned with signup, signin and signup events.  If you need more detail than that, authStateChange might be useful.
