### ISSUE TITLE
Could not find com.android.tools:common:25.2.3

### ISSUE THREAD

**Issue by Zafeer** [aws-amplify/amplify-js#2291]
**Describe the bug**
This issue started happening yesterday and is similar to react-native-community/react-native-image-picker#999

**Error:**
A problem occurred configuring project ':@aws-amplify/pushnotification'.
> Could not resolve all files for configuration ':@aws-amplify/pushnotification:classpath'.
   > Could not find com.android.tools:common:25.2.3.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/common/25.2.3/common-25.2.3.pom
         https://jcenter.bintray.com/com/android/tools/common/25.2.3/common-25.2.3.jar
     Required by:
         project :@aws-amplify/pushnotification > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3
         project :@aws-amplify/pushnotification > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools.build:manifest-merger:25.2.3
         project :@aws-amplify/pushnotification > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools.ddms:ddmlib:25.2.3
         project :@aws-amplify/pushnotification > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools.analytics-library:shared:25.2.3
         project :@aws-amplify/pushnotification > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools.analytics-library:tracker:25.2.3
         project :@aws-amplify/pushnotification > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools:sdklib:25.2.3 > com.android.tools.layoutlib:layoutlib-api:25.2.3
         project :@aws-amplify/pushnotification > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools:sdklib:25.2.3 > com.android.tools:dvlib:25.2.3
         project :@aws-amplify/pushnotification > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools:sdklib:25.2.3 > com.android.tools:repository:25.2.3

**Comment by Zafeer** [comment]
Okay for anyone facing a similar issue and unable to change node_modules manually can use this as a drop in in your current project build.gradle (not app/build.gradle)


`subprojects` {project ->
    if (project.name.contains('@aws-amplify/pushnotification')) {
            buildscript {
            repositories {
              maven { url 'https://maven.google.com' }
              jcenter()
              google()
            }
            dependencies {
                classpath 'com.android.tools.build:gradle:2.3.0'
            }
        }
    }
}`

**Comment by hello-error** [comment]
Still persists.

**Comment by Zafeer** [comment]
It still is searching for the 2.2.3 package when it should take 2.3.0
Can you clear your gradleCache and try again ??

**Comment by Zafeer** [comment]
For the time if you still cannot get it to work , since you are running it on local eclipse please make the changes in the @amplify/pushnotification android/build.gradle file directly by changing 2.2.3 to 2.3.0
<img width="1304" alt="screen shot 2018-12-09 at 8 11 40 pm" src="https://user-images.githubusercontent.com/5039557/49698798-b5760900-fbee-11e8-8677-3139bff0c98a.png">

**Comment by hello-error** [comment]
Yes that did it... Had to change it inside the location you indicate. Thanks

**Comment by powerful23** [comment]
Closing the issue. Feel free to reopen if you still have this issue.
