### ISSUE TITLE
Can't minify after aws-appsync upgrade to 1.6.0

### ISSUE THREAD

**Issue by vbudilov** [aws-amplify/amplify-js#2297]
**Describe the bug**
After upgrading to  "aws-appsync" 1.6.0 I get the following error: 

```
yarn run v1.6.0
$ react-app-rewired build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/aws-appsync/node_modules/debug/src/browser.js:155 
```

I had to downgrade to 1.4.0 to make it work again (see below):

```
    "aws-amplify": "1.1.13",
    "aws-amplify-react": "2.1.7",
    "aws-appsync": "1.4.0",
    "aws-appsync-react": "1.2.4",
```

**Comment by Zorail** [comment]
> @vbudilov Can you try with `aws-appsync@1.7.0` ?

yes , it worked after changing the version .
Thanks

**Comment by Zorail** [comment]
@manueliglesias It worked after changing the version to 1.7.0.
Thanks.

**Comment by manueliglesias** [comment]
Nice! I am closing the issue
