### ISSUE TITLE
@beta branch error message is treated as signUp field in SignUp.js

### ISSUE THREAD

**Issue by ajroberts0417** [aws-amplify/amplify-js#2300]
**Describe the bug**

When an error message is created in SignUp.js it gets added to `this.state` as `this.state.error`.
In the signUp() function, `inputKeys = Object.keys(this.state);`, error becomes a part of inputKeys. 
Error occurs in needPrefix(key) when error is passed as the key parameter because `const field = this.signUpFields.find(e => e.key === key);` becomes undefined.
Then when the function tries to return `field.custom`, field is undefined so it throws an error.

**To Reproduce**
1. use aws-amplify-react-native 2.1.1-beta.3
2. Set up the a SignUp screen using SignUp.js (we used withAuthenticator())
3. Attempt to sign up but purposefully generate an error message (for example, fail to enter a valid password and attempt to sign up)
4. Attempt to sign up again.
5. Bug

**Expected behavior**
No error

**Smartphone (please complete the following information):**
 iOS 12.1, iPhone XR simulator.

**Additional context**
Beta branch is being used due to suggestion from issue #2160 

Currently I am temporarily adding this conditional as a solution in the following [snippet](https://github.com/aws-amplify/amplify-js/blob/beta/packages/aws-amplify-react-native/src/Auth/SignUp.js#L173:L182):

```
if(key !== 'error') {
   const newKey = `${this.needPrefix(key) ? 'custom:' : ''}${key}`;
   signup_info.attributes[newKey] = inputVals[index];
}
```

Error on iOS simulator:
```
undefined is not an object (evaluating 'field.custom')

needPrefix
    SignUp.js:112:26
<unknown>
    SignUp.js:154:54
signUp
    SignUp.js:151:26
touchableHandlePress
    TouchableOpacity.js:201:45
_performSideEffectsForTransition
    Touchable.js:744:34
_receiveSignal
    Touchable.js:662:44
touchableHandleResponderRelease
    Touchable.js:431:24
invokeGuardedCallback
    ReactNativeRenderer-dev.js:39:15
invokeGuardedCallback
    ReactNativeRenderer-dev.js:221:34
invokeGuardedCallbackAndCatchFirstError
    ReactNativeRenderer-dev.js:245:48
executeDispatch
    ReactNativeRenderer-dev.js:572:4
executeDispatchesInOrder
    ReactNativeRenderer-dev.js:603:20
executeDispatchesAndRelease
    ReactNativeRenderer-dev.js:761:29
forEachAccumulated
    ReactNativeRenderer-dev.js:740:16
runEventsInBatch
    ReactNativeRenderer-dev.js:927:6
runExtractedEventsInBatch
    ReactNativeRenderer-dev.js:952:19
<unknown>
    ReactNativeRenderer-dev.js:2703:6
batchedUpdates
    ReactNativeRenderer-dev.js:13724:16
batchedUpdates
    ReactNativeRenderer-dev.js:2565:27
_receiveRootNodeIDEvent
    ReactNativeRenderer-dev.js:2701:17
receiveTouches
    ReactNativeRenderer-dev.js:2777:28
__callFunction
    MessageQueue.js:351:47
<unknown>
    MessageQueue.js:116:26
__guardSafe
    MessageQueue.js:314:6
callFunctionReturnFlushedQueue
    MessageQueue.js:115:17
```

**Comment by haverchuck** [comment]
@ajroberts0417  - Thanks for the heads up on this!  We should have a fix in place in the @unstable build (the signup config functionality was ported to our unstable branch yesterday).

**Comment by haverchuck** [comment]
@ajroberts0417 I'm closing this issue for now, but please feel free to reopen if it persists.
