### ISSUE TITLE
Authenticator components should use form onSubmit method

### ISSUE THREAD

**Issue by mrcoles** [aws-amplify/amplify-js#2310]
**Is your feature request related to a problem? Please describe.**

I noticed that the Authenticator UIs do not actually use a `<form />` element, but instead just listen to an `onclick` handler on the submit button for each one, e.g., [SignIn.jsx](https://github.com/aws-amplify/amplify-js/blob/8a52918f1933688717ed3934df3e819ae03fee69/packages/aws-amplify-react/src/Auth/SignIn.jsx#L160).

As a result, pressing enter in a form element doesn’t submit it. I believe this also impacts mobile where you can often submit a form from a keyboard option while inside a field instead of explicitly tapping the submit button. More generally, the standard expectation for how a form works is not met as a result of submit being handled in the way it currently is.

**Describe the solution you'd like**

I would like the Authenticator components, e.g., SignIn.jsx, SignUp.jsx, VerifyPassword.jsx, etc. (and for the other JS libraries too in addition to React), to get wrapped in a `<form  />` with an `onClick` method matching the previous `onClick` of the submit buttons and for the buttons to simply be changed to a button of `type="submit"` without an `onClick` handler.

The only quirk, is that I noticed the FederatedSignin gets triggered for Google sometimes… one workaround is to move the federated signin buttons outside of the form.

**Describe alternatives you've considered**

The only alternative I’ve found is to write my own forms, which sort of defeats the purpose of this library.

**Additional context**

I noticed these other closed issues on this topic (https://github.com/aws-amplify/amplify-js/issues/2085 and https://github.com/aws-amplify/amplify-js/issues/1019), however, I hope this one provides some more context and a clearer path forward.

**Comment by haverchuck** [comment]
@mrcoles - Thanks for submitting this.  I was thinking along similar lines myself.

**Comment by ashika01** [comment]
Closing this feature request, since this is how the [new UI components](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react) implement the form handling. Though there were some frictions and we had to work around for shadow dom introduced.

Reference: https://github.com/aws-amplify/amplify-js/blob/master/packages/amplify-ui-components/src/components/amplify-form-section/amplify-form-section.tsx#L30
