### ISSUE TITLE
Provide XR.stop() method for XRServiceProvider

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-js#2312]
**Is your feature request related to a problem? Please describe.**
I'm experimenting with dynamically loading private Sumerian scenes from within an Amplify site. Dynamic loading -- background loading of scenes not currently being rendered or played -- seems possible with the combination of the `XR.loadScene()`, `XR.start()`, and hopefully `XR.stop()`.

**Describe the solution you'd like**
A `stop()` method on the XRServiceProvider, to allow private scenes to be stopped gracefully.

**Describe alternatives you've considered**
1. Dynamic loading inside a top-level Sumerian scene using @prestomation's sumerian-scene-loader library, and making any "scene switches" occur within this scene. Or,
2. Attempt to use `loadScene` and `start`, in combination with manipulation of the DOM to simulate an `exit` method, e.g. deleting the root div that the original `XR.loadScene` references.

**Additional context**
- https://github.com/prestomation/sumerian-scene-loader
-https://aws-amplify.github.io/amplify-js/api/classes/abstractxrprovider.html

**Comment by jordanranz** [comment]
A stop() or pause() needs to be exposed by the sceneController loaded by the Sumerian API. I'll make note of this feature request and work with the Sumerian team to come up with a path forward on this. Will update this issue when I have new information.

**Comment by jkeys-ecg-nmsu** [comment]
@jordanranz Since you made a note on your end, and our dynamic loading architecture relies on a Top Level Scene pattern (courtesy of @prestomation), I'm closing this issue.

Please feel free to update me or someone from ECG on Slack if you make progress on this!

**Comment by jordanmcdougall** [comment]
@jordanranz Did this ever make it in as a feature?

**Comment by BruceWheaton** [comment]
I have this problem too. The XR system runs in the background when user routes away.The Sumerian React samples show how to stop listeners, but it's a waste of time since the whole XR system is still running but can't be accessed any more or restarted

**Comment by jkeys-ecg-nmsu** [comment]
@jordanmcdougall not as far as I know, we worked around it by always having a scene loaded and doing orchestration within that scene. I'll re-open since other people need support for this.

**Comment by cwomack** [comment]
@jkeys-ecg-nmsu, the XR category is on a deprecation path. Please see https://github.com/aws-samples/aws-tools-for-babylonjs-editor for examples on using AWS services with Babylon.js.
