### ISSUE TITLE
Federated Sign-in with Auth0

### ISSUE THREAD

**Issue by jeromeky** [aws-amplify/amplify-js#2314]
** Which Category is your question related to? **
Authentication

** What AWS Services are you utilizing? **
AppSync / API Gateway

** Provide additional details e.g. code snippets **
Hi there,

I'm planning to start a new project using Amplify.

I would like to use Auth0 as my identity provider. I saw that we can sign-in with Auth0 then use Federated sign-in in order to use AWS services https://aws-amplify.github.io/docs/js/authentication#federated-with-auth0.

Does that means I can then call AppSync / API Gateway services ?
Should I use Amplify to generate the AppSync project ? And should I configure it to use Amazon Cognito User Pool as authentication ?

Thanks for your help.

**Comment by powerful23** [comment]
@jeromeky as long as you have the corresponding IAM policy in your authenticated role, you can sign in with Auth0 and get the credentials which will give you access to those aws resources. In this case you should configure it to use IAM as authentication: https://aws-amplify.github.io/docs/js/api#using-aws_iam

**Comment by haverchuck** [comment]
Closing this issue due to non-activity, and also it looks like @powerful23 's answer is sufficient.  Please feel free to reopen if needed.
