### ISSUE TITLE
Auth.signIn() promise is taking up to 2 minutes to resolve

### ISSUE THREAD

**Issue by wowMuchgit** [aws-amplify/amplify-js#2317]
**Describe the bug**
Im using Amplify in React
The best way i can describe it is by using the Network tab as a flow "diagram".
The following happens once i click Login in my form:

Auth.signIn() is called,

->HTTP POST with USER_SRP_AUTH is made,
<-PASSWORD_VERIFIER response is recieved,
->HTTP POST with PASSWORD_VERIFIER challenge is made,
<-AuthenticationResult response is recieved,
¬Long pause of up to 2 mins,
->HTTP POST with AccessToken is made,
<-UserAttributes is recieved (User object)

However if i click Login and then refresh the page, a Auth.currentAuthenticatedUser() call is triggerd and it instantly returns the User object

**Screenshots**
Network Tab
![git issue snip](https://user-images.githubusercontent.com/31740094/49871317-c18be180-fe0d-11e8-9da0-882eb6e446ce.PNG)

console.log() of just clicking login
![git issue login snip](https://user-images.githubusercontent.com/31740094/49872406-d9b13000-fe10-11e8-87d2-b426dce486a0.PNG)

console.log() of refreshing page after clicking login
![git issue refresh after login snip](https://user-images.githubusercontent.com/31740094/49872437-f2214a80-fe10-11e8-80b8-ea63bda566d8.PNG)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox
 - Dependencies: 
    "@material-ui/core": "^3.6.2",
    "aws-amplify": "^1.1.7",
    "aws-amplify-react": "^2.1.1",
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "react-redux": "^5.1.1",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "react-scripts": "2.0.4",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0"

**Additional context**
All Auth methods are housed in a Redux action.js file and i have a bunch of console.log() through out the chain of calls

Any help will be greatly appreciated. Thank you

**Comment by wowMuchgit** [comment]
I would like to add that this problem also occurs with Auth.completeNewPassword()

**Comment by wowMuchgit** [comment]
I noticed this in the debug log:

[DEBUG] 24:00.43 AuthClass - failed to get or parse item aws-amplify-federatedInfo SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"

The rest of the log:

[DEBUG] 22:35.771 AuthClass 
Object { idToken: {…}, refreshToken: {…}, accessToken: {…}, clockDrift: 1 }
ConsoleLogger.js:99
[INFO] 22:35.774 Cache - Remove item: key is federatedInfo ConsoleLogger.js:97
[DEBUG] 22:35.774 Credentials - set credentials from session ConsoleLogger.js:97
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cognito-identity.eu_west_2.amazonaws.com/. (Reason: CORS request did not succeed).[Learn More]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cognito-identity.eu_west_2.amazonaws.com/. (Reason: CORS request did not succeed).[Learn More]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cognito-identity.eu_west_2.amazonaws.com/. (Reason: CORS request did not succeed).[Learn More]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cognito-identity.eu_west_2.amazonaws.com/. (Reason: CORS request did not succeed).[Learn More]
[DEBUG] 24:00.36 Credentials - Failed to load credentials 
Object { expired: true, expireTime: null, accessKeyId: undefined, sessionToken: undefined, params: {…}, data: null, _identityId: null, _clientConfig: {…}, webIdentityCredentials: {…}, cognito: {…}, … }
ConsoleLogger.js:107
[DEBUG] 24:00.38 AuthClass - cannot get cognito credentials NetworkingError: "Network Failure"
	handleRequest http://localhost:3000/static/js/0.chunk.js:67696:34
ConsoleLogger.js:107
[DEBUG] 24:00.39 Analytics - on hub capsule auth 
Object { event: "signIn", data: {…} }
ConsoleLogger.js:107
[DEBUG] 24:00.41 Credentials - getting credentials ConsoleLogger.js:97
[DEBUG] 24:00.41 Credentials - picking up credentials ConsoleLogger.js:97
[DEBUG] 24:00.41 Credentials - getting new cred promise ConsoleLogger.js:97
[DEBUG] 24:00.42 Credentials - checking if credentials exists and not expired ConsoleLogger.js:97
[DEBUG] 24:00.42 Credentials - need to get a new credential or refresh the existing one ConsoleLogger.js:97
[DEBUG] 24:00.42 AuthClass - Getting current user credentials ConsoleLogger.js:97
[DEBUG] 24:00.43 AuthClass - failed to get or parse item aws-amplify-federatedInfo SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"
	currentUserCredentials http://localhost:3000/static/js/0.chunk.js:6836:23
	_keepAlive http://localhost:3000/static/js/0.chunk.js:9614:14
	_pickupCredentials http://localhost:3000/static/js/0.chunk.js:9593:69
	get http://localhost:3000/static/js/0.chunk.js:9581:12
	_getCredentials http://localhost:3000/static/js/0.chunk.js:1847:12
	record http://localhost:3000/static/js/0.chunk.js:1349:15
	step http://localhost:3000/static/js/0.chunk.js:1058:14
	verb http://localhost:3000/static/js/0.chunk.js:988:14
	__awaiter http://localhost:3000/static/js/0.chunk.js:960:67
	__awaiter http://localhost:3000/static/js/0.chunk.js:937:10
	record http://localhost:3000/static/js/0.chunk.js:1342:12
	_sendEvent http://localhost:3000/static/js/0.chunk.js:455:9
	_sendEvent http://localhost:3000/static/js/0.chunk.js:453:5
	record http://localhost:3000/static/js/0.chunk.js:426:11
	step http://localhost:3000/static/js/0.chunk.js:159:14
	verb http://localhost:3000/static/js/0.chunk.js:89:14
	__awaiter http://localhost:3000/static/js/0.chunk.js:61:67
	__awaiter http://localhost:3000/static/js/0.chunk.js:38:10
	record http://localhost:3000/static/js/0.chunk.js:403:12
	authEvent http://localhost:3000/static/js/0.chunk.js:1989:7
	onHubCapsule http://localhost:3000/static/js/0.chunk.js:1953:7
	toListeners http://localhost:3000/static/js/0.chunk.js:10189:9
	toListeners http://localhost:3000/static/js/0.chunk.js:10187:5
	dispatch http://localhost:3000/static/js/0.chunk.js:10152:7
	dispatchAuthEvent http://localhost:3000/static/js/0.chunk.js:5491:3
	onSuccess http://localhost:3000/static/js/0.chunk.js:5928:17
	step http://localhost:3000/static/js/0.chunk.js:5459:14
	verb http://localhost:3000/static/js/0.chunk.js:5389:14
	rejected http://localhost:3000/static/js/0.chunk.js:5349:14
ConsoleLogger.js:107
[DEBUG] 24:00.44 AuthClass - Getting current session ConsoleLogger.js:97
Object { username: "XXXXXXXXXXXX", pool: {…}, Session: null, client: {…}, signInUserSession: {…}, authenticationFlowType: "USER_SRP_AUTH", storage: {…}, keyPrefix: "XXXXXXXXX", userDataKey: "XXXXXXXXX" }
authActions.js:16
signin action authActions.js:25
Object { type: "SIGN_IN", payload: {…} }
authReducer.js:15
true AuthContainer.js:62
Home Container HomeContainer.js:14
[DEBUG] 24:00.187 AuthClass - Getting the session from this user: 
Object { username: "XXXXXXXXXX", pool: {…}, Session: null, client: {…}, signInUserSession: {…}, authenticationFlowType: "USER_SRP_AUTH", storage: {…}, keyPrefix: "XXXXXXXX", userDataKey: "XXXXXXXXXX", attributes: {…}, … }
ConsoleLogger.js:107
[DEBUG] 24:00.187 AuthClass - Succeed to get the user session 
Object { idToken: {…}, refreshToken: {…}, accessToken: {…}, clockDrift: 1 }
ConsoleLogger.js:107
[DEBUG] 24:00.188 AuthClass - getting session success 
Object { idToken: {…}, refreshToken: {…}, accessToken: {…}, clockDrift: 1 }
ConsoleLogger.js:107
[DEBUG] 24:00.189 Credentials - set credentials from session

**Comment by wowMuchgit** [comment]
Iv tried it with a blank project, see attached source and log.
The thing that stands out to me from the log is the network error and the syntax error but other than that i have no idea what could be causing this bug :(
I you need any more information please let me know.

Thank you

app.js
```
class App extends Component {

  signin = async => {
    Auth.signIn('user@email.com', 'password')
      .then(user => console.log(user))
      .catch(err => console.log(err))
  }

  render() {
    return (
      <div className="App">
        <button
          onClick={this.signin}
        >
          Button </button>
      </div>
    );
  }
}

export default App;
```
index.js

```
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';

import Amplify from "aws-amplify";
import awsConfig from "./awsConfig";

Amplify.configure({
    Auth: {
        mandatorySignIn: true,
        region: awsConfig.cognito.REGION,
        userPoolId: awsConfig.cognito.USER_POOL_ID,
        identityPoolId: awsConfig.cognito.IDENTITY_POOL_ID,
        userPoolWebClientId: awsConfig.cognito.APP_CLIENT_ID,
        cookieStorage: {
            // REQUIRED - Cookie domain (only required if cookieStorage is provided)
            domain: 'localhost',
            // OPTIONAL - Cookie path
            path: '/',
            // OPTIONAL - Cookie expiration in days
            expires: 365,
            // OPTIONAL - Cookie secure flag
            secure: false
        }
    },

});

ReactDOM.render(<App />, document.getElementById('root'));
serviceWorker.unregister();
```

window.LOG_LEVEL = 'DEBUG'
![blank react app](https://user-images.githubusercontent.com/31740094/50971781-cc08cc00-14dc-11e9-891d-156c1b45bec6.PNG)

**Comment by powerful23** [comment]
@wowMuchgit the `failed to get or parse item aws-amplify-federatedInfo SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"` is not actually an error, please ignore it. Can you provide a complete log from the moment you click on sign in button? Thanks!

**Comment by wowMuchgit** [comment]
What about the network error?
![network opsie](https://user-images.githubusercontent.com/31740094/50990794-f2ddf700-150a-11e9-84d9-c4cdeaf53fb2.PNG)

Thats the rest of the log, what i have attached in the above comment is the same every time, if necessary i can copy/paste the text instead so you have it all in one post?
![rest of log](https://user-images.githubusercontent.com/31740094/50990650-83680780-150a-11e9-9242-a9a98dc9a781.PNG)

**Comment by wowMuchgit** [comment]
This is the whole log in txt, it receives the tokens then triggers CORS errors and then a network error but then logs in straight after that. This makes me think that it CAN'T reach https://cognito-identity.eu_west_2.amazonaws.com/ because of CORS but CAN reach https://cognito-idp.eu-west-2.amazonaws.com/
I think it may have something to do with what is referenced here:
https://forums.aws.amazon.com/message.jspa?messageID=586526
I will be posting in that thread also when my account is "ready to post messages" but i would appreciate it if someone could look into it if at all possible.

Thank you for your efforts so far

Refresh the page if necessary. 0.chunk.js:73690:5
[DEBUG] 20:09.449 AuthClass 
Object { idToken: {…}, refreshToken: {…}, accessToken: {…}, clockDrift: 25 }
ConsoleLogger.js:99
[INFO] 20:09.455 Cache - Remove item: key is federatedInfo ConsoleLogger.js:97
[DEBUG] 20:09.456 Credentials - set credentials from session ConsoleLogger.js:97
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cognito-identity.eu_west_2.amazonaws.com/. (Reason: CORS request did not succeed).[Learn More]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cognito-identity.eu_west_2.amazonaws.com/. (Reason: CORS request did not succeed).[Learn More]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cognito-identity.eu_west_2.amazonaws.com/. (Reason: CORS request did not succeed).[Learn More]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cognito-identity.eu_west_2.amazonaws.com/. (Reason: CORS request did not succeed).[Learn More]
[DEBUG] 21:34.103 Credentials - Failed to load credentials 
Object { expired: true, expireTime: null, accessKeyId: undefined, sessionToken: undefined, params: {…}, data: null, _identityId: null, _clientConfig: {…}, webIdentityCredentials: {…}, cognito: {…}, … }
ConsoleLogger.js:107
[DEBUG] 21:34.114 AuthClass - cannot get cognito credentials NetworkingError: "Network Failure"
	handleRequest http://localhost:3000/static/js/0.chunk.js:31952:34
ConsoleLogger.js:107
[DEBUG] 21:34.117 Analytics - on hub capsule auth 
Object { event: "signIn", data: {…} }
ConsoleLogger.js:107
[DEBUG] 21:34.123 Credentials - getting credentials ConsoleLogger.js:97
[DEBUG] 21:34.124 Credentials - picking up credentials ConsoleLogger.js:97
[DEBUG] 21:34.124 Credentials - getting new cred promise ConsoleLogger.js:97
[DEBUG] 21:34.126 Credentials - checking if credentials exists and not expired ConsoleLogger.js:97
[DEBUG] 21:34.128 Credentials - need to get a new credential or refresh the existing one ConsoleLogger.js:97
[DEBUG] 21:34.128 AuthClass - Getting current user credentials ConsoleLogger.js:97
[DEBUG] 21:34.131 AuthClass - failed to get or parse item aws-amplify-federatedInfo SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"
	currentUserCredentials http://localhost:3000/static/js/0.chunk.js:6836:23
	_keepAlive http://localhost:3000/static/js/0.chunk.js:9614:14
	_pickupCredentials http://localhost:3000/static/js/0.chunk.js:9593:69
	get http://localhost:3000/static/js/0.chunk.js:9581:12
	_getCredentials http://localhost:3000/static/js/0.chunk.js:1847:12
	record http://localhost:3000/static/js/0.chunk.js:1349:15
	step http://localhost:3000/static/js/0.chunk.js:1058:14
	verb http://localhost:3000/static/js/0.chunk.js:988:14
	__awaiter http://localhost:3000/static/js/0.chunk.js:960:67
	__awaiter http://localhost:3000/static/js/0.chunk.js:937:10
	record http://localhost:3000/static/js/0.chunk.js:1342:12
	_sendEvent http://localhost:3000/static/js/0.chunk.js:455:9
	_sendEvent http://localhost:3000/static/js/0.chunk.js:453:5
	record http://localhost:3000/static/js/0.chunk.js:426:11
	step http://localhost:3000/static/js/0.chunk.js:159:14
	verb http://localhost:3000/static/js/0.chunk.js:89:14
	__awaiter http://localhost:3000/static/js/0.chunk.js:61:67
	__awaiter http://localhost:3000/static/js/0.chunk.js:38:10
	record http://localhost:3000/static/js/0.chunk.js:403:12
	authEvent http://localhost:3000/static/js/0.chunk.js:1989:7
	onHubCapsule http://localhost:3000/static/js/0.chunk.js:1953:7
	toListeners http://localhost:3000/static/js/0.chunk.js:10189:9
	toListeners http://localhost:3000/static/js/0.chunk.js:10187:5
	dispatch http://localhost:3000/static/js/0.chunk.js:10152:7
	dispatchAuthEvent http://localhost:3000/static/js/0.chunk.js:5491:3
	onSuccess http://localhost:3000/static/js/0.chunk.js:5928:17
	step http://localhost:3000/static/js/0.chunk.js:5459:14
	verb http://localhost:3000/static/js/0.chunk.js:5389:14
	rejected http://localhost:3000/static/js/0.chunk.js:5349:14
ConsoleLogger.js:107
[DEBUG] 21:34.133 AuthClass - Getting current session ConsoleLogger.js:97
Object { username: "e6826c28-6910-408f-8992-77efe0e19bbb", pool: {…}, Session: null, client: {…}, signInUserSession: {…}, authenticationFlowType: "USER_SRP_AUTH", storage: {…}, keyPrefix: "CognitoIdentityServiceProvider.XXXXXXXXXXXXXXXXXXXXXXXXX", userDataKey: "CognitoIdentityServiceProvider.XXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXX.userData" }
App.js:10
[DEBUG] 21:34.266 AuthClass - Getting the session from this user: 
Object { username: "e6826c28-6910-408f-8992-77efe0e19bbb", pool: {…}, Session: null, client: {…}, signInUserSession: {…}, authenticationFlowType: "USER_SRP_AUTH", storage: {…}, keyPrefix: "CognitoIdentityServiceProvider.XXXXXXXXXXXXXXXXXXXXXXXXX", userDataKey: "CognitoIdentityServiceProvider.XXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXX.userData", attributes: {…}, … }
ConsoleLogger.js:107
[DEBUG] 21:34.267 AuthClass - Succeed to get the user session 
Object { idToken: {…}, refreshToken: {…}, accessToken: {…}, clockDrift: 25 }
ConsoleLogger.js:107
[DEBUG] 21:34.267 AuthClass - getting session success 
Object { idToken: {…}, refreshToken: {…}, accessToken: {…}, clockDrift: 25 }
ConsoleLogger.js:107
[DEBUG] 21:34.268 Credentials - set credentials from session

**Comment by wowMuchgit** [comment]
Found and fixed issue, i was passing an identiy pool id in my auth configuration which i wasnt making use of and hadnt set up properly. Dumb mistake on my part. I will close this issue, sorry to have wasted your time :(
