### ISSUE TITLE
Method authenticateUser don't call the callback at Lamba environment

### ISSUE THREAD

**Issue by lucaslrolim** [aws-amplify/amplify-js#2319]
I'm developing a microservice API in Express JS to handle all authentication and authorization stuff of my other services. I need a login method that receives email and password as input and returns the user JWT.

I add the following method as middleware:

```
    login(req, res, next) {
        var  email = req.body.email;
        var password = req.body.password;

        console.log(email);
        console.log(password);

        var authenticationDetails = new AmazonCognitoIdentity.AuthenticationDetails({
            Username : email,
            Password : password,
        });

        let userData = {
            Username : email,
            Pool : this.user_pool
        };

        var AWSCognitoUser = AmazonCognitoIdentity.CognitoUser;
        var cognitoUser = new AWSCognitoUser(userData);
        cognitoUser.authenticateUser(authenticationDetails, {
            onSuccess: function (result) {
                console.log("success");
                req.login_status = {
                    "token": result.getAccessToken().getJwtToken(),
                    "message": "success"
                };
                next();
            }
        });

    }
```
On my index.js I have:

```
'use strict'
const express = require('express');
const app = express();
const bodyParser = require('body-parser')
app.use(bodyParser.urlencoded({
  extended: true
}));
app.use(bodyParser.json());
var cognito = require("./cognito.js");

function send_response(res,response_string){
  var response_obj = {
    "statusCode": 200,
    "headers": {
      "Content-Type": 'application/json',
      "Access-Control-Allow-Origin": "*"
    },
    "body": JSON.stringify(response_string),
    "isBase64Encoded": false
  };
  res.send(response_obj);
}

// other routes .....

/* @params {
  email: {String},
  password: {String}
} */
app.post('/login', cognito.login.bind(cognito), (req, res) => {
  send_response(res,req.login_status);
})
```

This **works ok when use Postman to send a request to my node local server, but results in "Internal Server Error" when I try on my Lambda + API gateway instance.**

My lamba.js config file

```
'use strict'
const awsServerlessExpress = require('aws-serverless-express')
const app = require('./index')
const binaryMimeTypes = [
	'application/octet-stream',
	'font/eot',
	'font/opentype',
	'font/otf',
	'image/jpeg',
	'image/png',
	'image/svg+xml'
]
const server = awsServerlessExpress.createServer(app, null, binaryMimeTypes);
exports.handler = (event, context) => awsServerlessExpress.proxy(server, event, context)
```
 

To reproduce:
1. mock user  {"email": lucas.rolimml@gmail.com, "password": "lucasROLIM123"}
2. API link: https://phyz5cuyik.execute-api.us-east-1.amazonaws.com/latest/login

Log on CloudWatch:

http://tinypic.com/r/2mn2gwi/9

**Comment by undefobj** [comment]
You might need to enable detailed CloudWatch metrics in API Gateway or Lambda to see what your error is or where the configuration problem lies. This question is probably better handled on the AWS forums for either API Gateway or Lambda, as this repo is for the Amplify library which is designed to be used in a client mobile or web application. You can find the service forums here: https://forums.aws.amazon.com/index.jspa

**Comment by lucaslrolim** [comment]
Thank you for the quick answer. I created this issue because during debug I found that the problem is exactly at:

```
        var cognitoUser = new AWSCognitoUser(userData);
        cognitoUser.authenticateUser(authenticationDetails, {
            onSuccess: function (result) {
                console.log("success");
                req.login_status = {
                    "token": result.getAccessToken().getJwtToken(),
                    "message": "success"
                };
                next();
            } //I also try use onFailure callback
        });
```
It works perfectly on Lambda and API gateway if I simple change to : 

```
                req.login_status = {
                    "token": "random test token",
                    "message": "success"
                };
                next();
```

So, I guess maybe there is something to change on authenticateUser method from the amazon-cognito-identity-js library.

**Comment by pedroo21** [comment]
I can confirm this is an issue and also happens to me. It is very common in NodeJS environments.

There are issues about this problem in the past, which refer to slow calculations in the authenticate (and other) methods: https://github.com/amazon-archives/amazon-cognito-identity-js/

**Comment by pedroo21** [comment]
I made a few tests and the problem indeed gets solved by changing the timeout of the lambda function to 30s. In my case, the requests take around 5-12 seconds to answer.
However, I did made another discovery, my local version only takes 1-2 seconds to answer (normal behavior). The difference is I'm using node v11. I strongly believe this is a performance issue with some lib in Node.JS v8 (as the  #43 referenced in previous comment suggests). Would be great to provide an alternative implementation.

**Comment by headz68** [comment]
I have a similar use-case. I'm trying to call  `authenticateUser` from a Lambda function in order to de-couple the token & session management from the clients. If I run my Lambda function locally with `sam-cli`, login is successful. However, it fails when deployed to AWS. I have a very basic user pool. No triggers and no phone number for signIn, only email. Also, my Lambda's execution role has full access to Cognito.

The error message I receive in the Lambda logs is: 
```
"Please provide an `arn`, `name` or `phone` number"  
```
I tried using the Amplify function:
```
Auth.signIn({
    username,
    password
  });
```
as well as using amazon-cognito-identity-js lib directly.
```
const userPoolData = new CognitoUserPool({
    UserPoolId: process.env.COGNITO_USER_POOL_ID,
    ClientId: process.env.COGNITO_CLIENT_ID
  });
  const userData = {
    Username: username,
    Pool: userPoolData
  };
  const user = new CognitoUser(userData);
  const authDetails = new AuthenticationDetails({
    Username: username,
    Password: password
    // ValidationData: { },
  });

  return new Promise((resolve, reject) => {
    user.authenticateUser(authDetails, {
      onSuccess(result) {
        resolve(result);
      },
      onFailure(err) {
        reject(err);
      },
    });
```
I noticed that AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY env vars change frequently between Lambda executions. I've tried updating the credentials with my Amplify admin user credentials but no luck:
```
AWS.config.update({
  region: process.env.REGION,
  credentials: new AWS.Credentials({
    accessKeyId: amplifyKeyId,
    secretAccessKey: amplifyAccessKey
  }),
});
```

@undefobj what's the reccommended approach to login from Lambda??
