### ISSUE TITLE
Hub giving error on dispatch

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-js#2326]
**Describe the bug**
Hub.dispatch() seems to not work under certain conditions, including either failing to send the message, ~~OR sending the wrong message (i.e. clicking on button A triggers button B's `onclick` handler).~~

**To Reproduce**
1. Install aws-amplify, and import { Hub } from 'aws-amplify'
2. Use `Hub.dispatch("myChannel", {}, "MyClass")` (with an empty map) in one component.
3. Listen on the same channel in another component with `Hub.listen("myChannel", this, "MyClass")`

**Expected behavior**
The event is published to the listener, and the listener consumes the event ~~and activates the proper callback~~.

**Desktop (please complete the following information):**
 - OS: Windows 10 (developing on Ubuntu for WSL)
 - Browser Chrome latest stable

**Additional context**
App.jsx: 

```
  constructor(props) {
    super(props);
    this.state = this.getInitialState();
    this.state.authData = this.props.authData;
    Hub.listen("sceneLoaded", this, "SceneLoaded");
  } //end ctor 
```

AppScene.jsx:

```
 componentDidUpdate() {
    let isLoaded = false;
    if (!isLoaded && XR.isSceneLoaded(this.state.sceneName)) {
      isLoaded = true;
      Hub.dispatch("sceneLoaded", {}, "SceneLoaded");
      if (XR.isMuted(this.state.sceneName)) {      // The scene is muted
          XR.setMuted(this.state.sceneName, false) // Unmute
      }
    }
  }
```

Edit: removed references to wrong callback being triggered (**not** Amplify bug), see [this comment](https://github.com/aws-amplify/amplify-js/issues/2326#issuecomment-447169912) for explanation of what was causing that.

**Comment by powerful23** [comment]
@jkeys-ecg-nmsu hi can you paste the warning/error context here?

**Comment by jkeys-ecg-nmsu** [comment]
@powerful23 I've been trying to replicate it. The error seems to have disappeared since upgrading aws-amplify to `@latest` branch.

Closing this issue. Thank you!
