### ISSUE TITLE
Allow null as default for countryCode in signup components

### ISSUE THREAD

**Issue by haverchuck** [aws-amplify/amplify-js#2327]
**Is your feature request related to a problem? Please describe.**
Country Code selectors in SignUp UI components force a default selected value.

**Describe the solution you'd like**
Allow for default to be 'no value selected'.

**Comment by sammartinez** [comment]
Resolving as this is not a case we are looking to support at this time. For Amazon Cognito, it is required to Sign Up with a country code when using their APIs
