### ISSUE TITLE
Ionic authenticator shows signIn although authState.state is singedIn

### ISSUE THREAD

**Issue by meeximum** [aws-amplify/amplify-js#2328]
** Which Category is your question related to? **
Ionic Authenticator Template
** What AWS Services are you utilizing? **
auth (Cognito)
* Provide additional details e.g. code snippets **
I user the ionic 4 tab starter template and added the <amplify-authenticator framework="ionic"> to a page

page.ts content
`import { Component, AfterContentInit } from '@angular/core';
import { Events } from '@ionic/angular';
import { AuthGuardService } from '../services/auth-route-guard'
import { AmplifyService }  from 'aws-amplify-angular';
import { Auth } from 'aws-amplify';
import { AuthState } from 'aws-amplify-angular/dist/src/providers/auth.state';

@Component({
  selector: 'app-page-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss']
})
export class HomePage implements AfterContentInit{

  authState: AuthState;
  // including AuthGuardService here so that it's available to listen to auth events
  authService: AuthGuardService
  amplifyService: AmplifyService

  constructor(
    public events: Events,
    public guard: AuthGuardService,
    public amplify: AmplifyService
  ) {
    
    this.authState = {state: 'signIn', user : null};
    this.authService = guard;
    this.amplifyService = amplify;
    amplify.auth().currentAuthenticatedUser().then( user => {
      console.log(user);
    });
    this.amplifyService.authStateChange$
    .subscribe(authState => {
      this.authState = authState;
      this.events.publish('data:AuthState', this.authState);
      console.log('constructor: ' + authState.state);
    });
  }

  ngAfterContentInit(){
    this.events.publish('data:AuthState', this.authState);
  }
}`

although the console logs 'signedIn' and a current authenticated user is logged, the template shows not the Greeting but the SignIn section?

Here a link to the hosted application, you can sign up for testing issues
[http://fancytools-20181213105437-hostingbucket.s3-website.eu-central-1.amazonaws.com](http://fancytools-20181213105437-hostingbucket.s3-website.eu-central-1.amazonaws.com)

**Comment by haverchuck** [comment]
@meeximum Which versions of aws-amplify and aws-amplify-angular are you using?

**Comment by meeximum** [comment]
Hi, I'm using
`"aws-amplify": "^1.1.13",
    "aws-amplify-angular": "^2.0.16",`

I try to build my app as described in this tutorial
[https://aws-amplify.github.io/docs/js/tutorials/building-ionic-4-apps/](https://aws-amplify.github.io/docs/js/tutorials/building-ionic-4-apps/)

My AuthGuard
`import { Injectable } from '@angular/core';
import { Router, CanActivate } from '@angular/router';
import { Events } from '@ionic/angular'

@Injectable({
  providedIn: 'root'
})
export class AuthGuardService implements CanActivate {

  signedIn: boolean = false;

  constructor(public router: Router, public events: Events) {
    this.events.subscribe('data:AuthState', async (data) => {
      this.signedIn = data.state === 'signedIn';
    });
  }

  canActivate() {
    if (!this.signedIn) {
      this.router.navigate(['/']);
    }
    return this.signedIn;
  }
}`

**Comment by NuruddinBadawi** [comment]
I have the same issue here, the 'data:AuthState' event doesn't fire at all

**Comment by NuruddinBadawi** [comment]
@meeximum did you get a solution?
