### ISSUE TITLE
Interactions Prompting for Microphone Erroneously

### ISSUE THREAD

**Issue by keegandonley** [aws-amplify/amplify-js#2338]
**Describe the bug**
My web application (React using amplify-react) has started prompting the browser for access to the microphone, but my application does no such thing. This issue occurs for all my deploys starting around after this pull request was merged: https://github.com/aws-amplify/amplify-js/pull/2121 leading me to think it may be the culprit.

Downgrading back to aws-amplify@1.1.13 and aws-amplify-react@2.1.5 has resolved the issue on my production site.

**To Reproduce**
1. Go to https://5c131e8bbda63e0009a7105a--happy-minsky-16b66b.netlify.com (my application under development)
2. You will be immediately prompted to grant microphone access

**Expected behavior**
The user should not be prompted to grant microphone access as I never request it

**Additional context**
By going back in time through Netlify deploys I am able to find a deployment in which this breaks - some time between December 12 and December 13

**Comment by joltcoke** [comment]
Same problem here. Microphone request is triggered by aws-lex-audio.js

**Comment by sarathchama** [comment]
We are facing the same problem the following versions of amplify. Can someone help us to fix this?
"aws-amplify": "^1.0.11",
"aws-amplify-angular": "^2.0.3"

**Comment by joltcoke** [comment]
> We are facing the same problem the following versions of amplify. Can someone help us to fix this?
> "aws-amplify": "^1.0.11",
> "aws-amplify-angular": "^2.0.3"

Try: npm install aws-amplify@1.0.11 aws-amplify-angular@2.0.3 --save-exact

**Comment by haverchuck** [comment]
@keegandonley  - Thanks for posting this issue.  We are investigating.

**Comment by ilrein** [comment]
@haverchuck I am still getting this issue on 

```"aws-amplify": "1.1.17",
    "aws-amplify-react": "^2.2.3",```

![screen shot 2018-12-23 at 12 42 38 pm](https://user-images.githubusercontent.com/5523014/50386209-64ffb080-06b0-11e9-9a1d-fdf4d8f22fad.png)

**Comment by abdelhakim-atmani** [comment]
@ilrein The amplify latest version seems to be the 1.1.18 and you are using the 1.1.17.
