### ISSUE TITLE
Push notification didnt open application on tap (^1.0.20)

### ISSUE THREAD

**Issue by pribadi1st** [aws-amplify/amplify-js#2339]
**Describe the bug**
The apps doesn't open when i tapped it.

**To Reproduce**
1. install latest pushnotification (1.0.20)
2. Send push notification using api
3. Tap
4. doesn't open the apps

**Expected behavior**
open the app after tapping the notification

**Smartphone (please complete the following information):**
 - Device : Samsung S7 
 - Version : Pushnotification (1.0.20) works fine on 1.0.19

**Comment by matamicen** [comment]
@pribadi1st @powerful23 the same issue happens to us just in Android 8.1 (We did not try on 8.0 yet), but the app with the  1.0.20 opens when tap  on android 7.0 and 7.1. 

More **not Working** scenarios on **Android 8.1**: 
 
aws-amplify@1.1.17 with
 @aws-amplify/pushnotification@1.0.20 
**and other one:**
 aws-amplify@1.1.16 with
@aws-amplify/pushnotification@1.0.20

Here are **Working** Scenarios on **Android 8.1**:

aws-amplify@1.1.14  with
@aws-amplify/pushnotification@1.0.19
**and other one:**
aws-amplify@1.1.13 with
@aws-amplify/pushnotification@1.0.19 

Hope this helps!

Thanks to the Aws Amplify Team ... the library is getting super stable!

**Comment by powerful23** [comment]
@pribadi1st Hi I am trying to reproduce this issue but it works for me with Android 7.0. Can you tell me which Android version are you testing with?

@matamicen unfortunately for now there is no device with v8.1 around me. Is there any error or any message which might indicate the root cause?

**Comment by pribadi1st** [comment]
@powerful23 i used samsung s7 with android version 8.0.0

**Comment by matamicen** [comment]
@powerful23 in the react-native log nothing happens when you tap the notification. 
Can you use a simulador? Because the same behavor happens on it.
@pribadi1st

**Comment by matamicen** [comment]
@powerful23 the issue is on android versión 8.0 and 8.1. 
Thanks for your help.

**Comment by powerful23** [comment]
That's mainly caused by this change: https://developer.android.com/about/versions/oreo/background

**Comment by matamicen** [comment]
@powerful23  Yeah, it make sense ... Tapping a notification and open the APP  is a super core task of engagement for any APP ....  any ideas to solve that problem? 
Thanks!

@pribadi1st

**Comment by powerful23** [comment]
@matamicen I have sent a pr to fix this issue.

**Comment by matamicen** [comment]
Thanks @powerful23 !!
