### ISSUE TITLE
Mismatched Graphql version, @aws-amplify/api and aws-appsync

### ISSUE THREAD

**Issue by Foosballfan** [aws-amplify/amplify-js#2340]
**Is your feature request related to a problem? Please describe.**
The bundle size is made ~500KB larger than necessary as Graphql is imported twice

**Describe the solution you'd like**
@aws-amplify/api and aws-appsync should share the same version of Graphql 

**Additional context**
```
aws-appsync@^1.7.0:
  version "1.7.0"
  resolved "https://registry.yarnpkg.com/aws-appsync/-/aws-appsync-1.7.0.tgz#a6b7fcaec6f52438d923e23ae249967d802156da"
  dependencies:
    ...
    graphql "^0.11.7"
    ...
```
```
"@aws-amplify/api@^1.0.23":
  version "1.0.23"
  resolved "https://registry.yarnpkg.com/@aws-amplify/api/-/api-1.0.23.tgz#43a00f8712366b1032f25596318247c7311edac0"
  dependencies:
    ...
    graphql "0.13.0"
    ...
```

**Comment by elorzafe** [comment]
@Foosballfan thanks for your feedback I will send a pr to fix that
