### ISSUE TITLE
{React Native} withAuthenticator() crashes with unknown fontFamily

### ISSUE THREAD

**Issue by adrianhall** [aws-amplify/amplify-js#2345]
**Describe the bug**
When using withAuthenticator() in a React Native (expo-cli created) app, I get a console error as follows:

```
[10:10:51] fontFamily 'Material Icons' is not a system font and has not been loaded through Font.loadAsync.

- If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.

- If this is a custom font, be sure to load it with Font.loadAsync.
- node_modules/expo-font/src/Font.js:51:10 in processFontFamily
- ... 28 more stack frames from framework internals
```

**To Reproduce**
1. Go to github.com/adrianhall/restaurant-reviews and use Serverless Framework to deploy the backend in the backend directory.
3. Go to mobile-app directory and run yarn install / yarn start
4. Run the iOS Simulator
4. Go to the "me" tab, then click the sign up link
5. Fill in the information and sign-up

**Expected behavior**
Expecting a new screen which asks for the MFA validation.

**Screenshots**
![screen shot 2018-12-14 at 10 14 39 am](https://user-images.githubusercontent.com/1489465/50019889-21f35e00-ff89-11e8-96a7-80b3fc3045a9.png)

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Running via expo-cli 

**Smartphone (please complete the following information):**
 - Device: iPhone X Simulator
 - OS: iOS 11.0.1

**Comment by jim-at-jibba** [comment]
I have this issue too.

**Comment by adrianhall** [comment]
There is a temporary workaround:

1) yarn add @expo/vector-icons
2) Run `Font.loadAsync` for Material Icons during your initialization.  For instance, I use the following to produce a loader:

```
    private loadResourcesAsync = async(): Promise<void> => {
        return Font.loadAsync({
            'Material Icons': require('../node_modules/@expo/vector-icons/fonts/MaterialIcons.ttf'),
            'space-mono': require('../assets/fonts/SpaceMono-Regular.ttf')
        });
    }
```

I produce a "loading" page while the resources are loading, then switch over to the app once the promises are resolved.

**Comment by fvonhoven** [comment]
> There is a temporary workaround:
> 
> 1. yarn add @expo/vector-icons
> 2. Run `Font.loadAsync` for Material Icons during your initialization.  For instance, I use the following to produce a loader:
> 
> ```
>     private loadResourcesAsync = async(): Promise<void> => {
>         return Font.loadAsync({
>             'Material Icons': require('../node_modules/@expo/vector-icons/fonts/MaterialIcons.ttf'),
>             'space-mono': require('../assets/fonts/SpaceMono-Regular.ttf')
>         });
>     }
> ```
> I produce a "loading" page while the resources are loading, then switch over to the app once the promises are resolved.

If you're not using Expo, you can: 
`yarn add react-native-vector-icons` 
and then 
`react-native link react-native-vector-icons`
😉

**Comment by swarnim89** [comment]
Same issue i m facing while running the application in iphone 5s

**Comment by andrewchaa** [comment]
As @fvonhoven said, add react-native-vector-icons and link it, but one more thing, rebuild the iso project.

```
yarn add react-native-vector-icons
react-native link react-native-vector-icons

react-native run-ios
```

**Comment by jordanranz** [comment]
This seems unrelated to Amplify. Is this safe to close or is there a particular issue with Amplify UI here?

**Comment by andrewchaa** [comment]
It's safe to close, IMO

**Comment by ryosuke-hujisawa** [comment]
Just do 

```
% npm install -g @expo/vector-icons
```

**Comment by ravirajar** [comment]
Did anyone get this sorted out? I'm still facing this issue.
