### ISSUE TITLE
Delay loading Sumerian engine if sceneName prop is passed as null or empty string to SumerianScene Component

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-js#2350]
**Is your feature request related to a problem? Please describe.**
I'm testing out a few different ways to implement dynamic loading for Sumerian scenes within an Amplify site, and it occurred to me that, if the SumerianScene component would delay loading until it received a proper sceneName prop, that would largely solve the problem. 

**Describe the solution you'd like**
Delay loading a scene until it receives a Truthy expression or a non-null string. In this example, since the sceneName prop starts as an empty string, I would expect this to render a hidden <SumerianScene> component but not load the engine/scene.

It would also be great if updating the sceneName prop back to an empty string or null unloaded the scene.

```
  getInitialState() {
    return {
    	loaded: false,
      play: false,
      sceneName: ""
    };
  }

  constructor(props) {
    super(props);
    this.state = this.getInitialState();
  } 

  render() {  
    return (
        <div className={this.state.play ? "App-scene" : "hidden"}>
          <SumerianScene sceneName={this.state.sceneName} />
        </div>
    ); 
```

**Describe alternatives you've considered**
Rendering nothing based on the state of the component, which seems like a hack.
  ```
render() {  
    return this.state.play ? (
        <React.Fragment>
          <AppButtons />
          <div className={this.state.play ? "App-scene" : "hidden"}>
            <SumerianScene sceneName={this.state.sceneName} />
          </div>
        </React.Fragment>
      ) : ( null )
  }
```

**Additional context**
This would eliminate the need for the feature request proposed in #2312.

**Comment by jkeys-ecg-nmsu** [comment]
@prestomation pointed out that it's a bit hackish itself to rely on the prop being null or empty string. So perhaps add a prop or two?

`<SumerianScene sceneName={this.state.sceneName) load={this.state.load} play={this.state.play} >`

**Comment by jordanranz** [comment]
I like this idea. Let me test out a way to pass in autoPlay and autoLoad props to override the default behavior.

**Comment by jordanranz** [comment]
As talked about in Slack. This feature request will have to wait until the Sumerian scene loader support dynamic loading for multiple scenes on a single page. I will make an update to this issue when I have more information.
