### ISSUE TITLE
Bad signature for special characters *!() in query string

### ISSUE THREAD

**Issue by dannymcpherson** [aws-amplify/amplify-js#2356]
**Describe the bug**
API Gateway returns a 403 whenever the query string contains any of these characters: *!()

**To Reproduce**
Make a call to API.get() on an endpoint protected with the AWS_IAM authorization type, passing it the init value similar to the following: {queryStringParameters: {foo: "*"}}

**Expected behavior**
For the correct signature to be generated, and the request not be automatically rejected by API Gateway with a 403.

**Desktop (please complete the following information):**
 - OS: macOS mojave 10.14 (18A391)
 - Browser chrome 70.0.3538.102 (Official Build) (64-bit)
 - Version 1.1.17

**Additional context**
This could be related to RFC 3986, explained here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

**Comment by dannymcpherson** [comment]
If it helps, I was able to work around the issue by moving the affected `queryStringParameters` into a custom header.

**Comment by silvanaweb** [comment]
Hi, I have the same issue, when I use "*" in a query parameter, I get the error 

> The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method

This is a big issue, because * is used as a search parameter. Any hint how to solve it?

**Comment by dannymcpherson** [comment]
@silvanaweb - Just curious... where did your logs come from?

**Comment by silvanaweb** [comment]
> @silvanaweb - Just curious... where did your logs come from?

First I tried in my website and got a 403 error. Then I tried with with the **curl** command and and I got that error message.

**Comment by xkollar** [comment]
@dannymcpherson I see the error in response when calling API Gateway.

**Comment by elorzafe** [comment]
@silvanaweb @dannymcpherson I merged into master now, I will do more testing on the unstable release before doing a publish.
