### ISSUE TITLE
My country is not available in dropdownlist for the countrycode

### ISSUE THREAD

**Issue by chris86** [aws-amplify/amplify-js#2357]
**Describe the bug**
When I am using a sample Angular App with Authenticator to be specific  this one https://github.com/aws-samples/aws-mobile-appsync-chat-starter-angular  ,when I try ti signup I cannot put my phone number in it because my countrycode is not available in the dropdown list. My Country is Curacao , I also noticed Sint Maarten is not on the list.

**Comment by haverchuck** [comment]
@chris86 - I merged a fix for this.  It should be available right now on our unstable build (npm i aws-amplify-angular@unstable) and will be available on our main build soon.
