### ISSUE TITLE
Pinpoint SendMessage return status code is 200 also with wrong tokens

### ISSUE THREAD

**Issue by lisandrolan** [aws-amplify/amplify-js#2361]
**Describe the bug**
If I try to send a PushNotification to a wrong token in FCM, I will receive an error message saying that the token is not registered. 
I I try to do the same for APN, Im not getting any error message. 

**To Reproduce**
Go to Pinpoint Console and try to send a PushNotification to a wrong APN token. 

**Expected behavior**
Receive an error message saying that the token is not registered or invalid

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by lisandrolan** [comment]
@powerful23

**Comment by powerful23** [comment]
@lisandrolan thanks for reporting. Will escalate this to the Pinpoint team.

**Comment by lisandrolan** [comment]
any update?

**Comment by powerful23** [comment]
@lisandrolan Can you provide more details? The pinpoint team cannot reproduce this issue.

**Comment by lisandrolan** [comment]
the issue seems to be solved.
