### ISSUE TITLE
Cannot use namespace 'DocumentNode' as a type.

### ISSUE THREAD

**Issue by hoang-innomizetech** [aws-amplify/amplify-js#2362]
I am getting below error when using this module. Does anyone know the root cause?

When running with webpack
ERROR in node_modules/@aws-amplify/api/lib/types/index.d.ts(45,21): error TS2709: Cannot use namespace 'DocumentNode' as a type.

AOT build error
ERROR in node_modules/@aws-amplify/api/lib/types/index.d.ts(45,21): error TS2709: Cannot use namespace 'DocumentNode' as a type.
node_modules/aws-amplify-angular/dist/src/components/xr/sumerian-scene-component/sumerian-scene.component.core.d.ts(14,16): error TS2709: Cannot use namespace 'AmplifyUI' as a type.
node_modules/aws-amplify-angular/dist/src/components/xr/sumerian-scene-component/sumerian-scene-loading.component.core.d.ts(6,16): error TS2709: Cannot use namespace 'AmplifyUI' as a type.
node_modules/aws-amplify-angular/dist/src/components/xr/sumerian-scene-component/sumerian-scene.component.ionic.d.ts(5,16): error TS2709: Cannot use namespace 'AmplifyUI' as a type.

angular: 7.1.3
typescript: 3.16
aws-amplify: 1.1.17
aws-amplify-angular: 2.14

**Comment by haverchuck** [comment]
#2365 related

**Comment by hoang-innomizetech** [comment]
After adding @types/graphql, I got another error related to AmplifyUI

**Comment by hoang-innomizetech** [comment]
Does anyone know how to fix this error when building AOT build?

ERROR in node_modules/aws-amplify-angular/dist/src/components/xr/sumerian-scene-component/sumerian-scene.component.core.d.ts(14,16): error TS2709: Cannot use namespace 'AmplifyUI' as a type.
node_modules/aws-amplify-angular/dist/src/components/xr/sumerian-scene-component/sumerian-scene-loading.component.core.d.ts(6,16): error TS2709: Cannot use namespace 'AmplifyUI' as a type.
node_modules/aws-amplify-angular/dist/src/components/xr/sumerian-scene-component/sumerian-scene.component.ionic.d.ts(5,16): error TS2709: Cannot use namespace 'AmplifyUI' as a type.

**Comment by fredericomaia10** [comment]
I have the same problem @hoang-innomizetech. Actually, all the times I try to use aws-amplify it's unstable. :(

**Comment by hoang-innomizetech** [comment]
Yeah. Currently, it blocking us migrate to latest version to get some bug fixes :(

**Comment by hoang-innomizetech** [comment]
@fredericomaia10 have you able to get this issue fixed?

**Comment by fredericomaia10** [comment]
@hoang-innomizetech unfortunately no.

**Comment by mrowles** [comment]
@fredericomaia10 What's worse is that they parked their [old repository](https://github.com/amazon-archives/amazon-cognito-identity-js) and forced everyone over to this, and it barely work.

**Comment by temesxgn** [comment]
Any update on this? This is fix is urgent for me

**Comment by Exomus** [comment]
Adding `"@types/graphql": "0.13.0"` to the `package.json` manually seems to fix it in my project for the moment.

**Comment by xaviertorgerson** [comment]
Just installing the latest `@types/graphql` with `npm install @types/graphql` did it for me.

**Comment by hoang-innomizetech** [comment]
@xaviertorgerson  @Exomus The DocumentNode issue can be fixed when installing the latest @types/graphql package, but when we are trying to build Angular AOT release, we are getting another error related to the AmplifyUI that I have reported above. This does not happen when we use aws-amplify-angular: 2.0.13 version.

**Comment by Christilut** [comment]
`npm install @types/graphql` doesn't work for me

I don't know how to get rid of this error right now

**Comment by tours232** [comment]
The fix seems to be to change the api/lib/types/index.d.ts line to the following because there is nothing in the graphql/language/ast file to import. I'm assuming the graphql dependency changed their code and ended up breaking this somehow?

```
import { DocumentNode } from 'graphql'
```

See https://github.com/graphql/graphql-js/blob/master/src/index.js.

**Comment by Christilut** [comment]
Current fix for me (which also removes the unused graphql dependency) is to use modular imports and not the whole amplify package. See https://github.com/aws-amplify/amplify-js/issues/2401#issuecomment-450195022

**Comment by hoang-innomizetech** [comment]
Yeah, I upgraded to latest version and also uninstall the **graphql** dependency and it is worked. But it is only worked when we added the skipLibCheck: true to the tsconfig.json file, I think this fine as long as we don't want to check the type for lib dependencies.

After adding **skipLibCheck** option, the issue related to the **AmplifyUI** also fixed. So I am closing this ticket

**Comment by AdamShechter9** [comment]
just upgraded Angular6 project to 8 and having issues with AWS-Amplify-angular similar to @hoang-innomizetech above.
`ERROR in ../node_modules/aws-amplify-angular/dist/src/components/xr/sumerian-scene-component/sumerian-scene.component.core.d.ts:15:16 - error TS2709: Cannot use namespace 'AmplifyUI' as a type.

15     amplifyUI: AmplifyUI;
                  ~~~~~~~~~
../node_modules/aws-amplify-angular/dist/src/components/xr/sumerian-scene-component/sumerian-scene-loading.component.core.d.ts:6:16 - error TS2709: Cannot use namespace 'AmplifyUI' as a type.

6     AmplifyUI: AmplifyUI;
                 ~~~~~~~~~
../node_modules/aws-amplify-angular/dist/src/components/xr/sumerian-scene-component/sumerian-scene.component.ionic.d.ts:5:16 - error TS2709: Cannot use namespace 'AmplifyUI' as a type.

5     amplifyUI: AmplifyUI;
                 ~~~~~~~~~
`


running:
`Angular CLI: 8.2.1
Node: 10.9.0
OS: darwin x64
Angular: 9.0.0-next.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.1
@angular-devkit/build-angular     0.802.1
@angular-devkit/build-optimizer   0.802.1
@angular-devkit/build-webpack     0.802.1
@angular-devkit/core              8.2.1
@angular-devkit/schematics        8.2.1
@angular/cdk                      8.1.2
@angular/cli                      8.2.1
@angular/material                 8.1.2
@ngtools/webpack                  8.2.1
@schematics/angular               8.2.1
@schematics/update                0.802.1
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.38.0`

package dependencies:
`  "dependencies": {
    "@angular/animations": "^9.0.0-next.2",
    "@angular/cdk": "^8.1.2",
    "@angular/common": "^9.0.0-next.2",
    "@angular/compiler": "^9.0.0-next.2",
    "@angular/core": "^9.0.0-next.2",
    "@angular/forms": "^9.0.0-next.2",
    "@angular/material": "^8.1.2",
    "@angular/platform-browser": "^9.0.0-next.2",
    "@angular/platform-browser-dynamic": "^9.0.0-next.2",
    "@angular/router": "^9.0.0-next.2",
    "ajv": "^6.10.0",
    "amazon-cognito-auth-js": "^1.3.2",
    "angularx-qrcode": "^1.6.4",
    "aws-amplify": "^1.1.36",
    "@aws-amplify/ui": "1.0.23",
    "aws-amplify-angular": "^2.1.12",
    "core-js": "^2.4.1",
    "js-cookie": "^2.2.0",
    "rxjs": "^6.5.2",
    "rxjs-compat": "^6.0.0-rc.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },`

node version 10.9.0

**Comment by AdamShechter9** [comment]
I temporarily fixed it and got it compiling by adding 
// @ts-ignore
in a few locations in the node_module folder pointed out to me by the IDE.
but this could only be a temporary solution.

**Comment by hoang-innomizetech** [comment]
@AdamShechter9 Did you try my solution as mentioned above

> After adding skipLibCheck option, the issue related to the AmplifyUI also fixed. So I am closing this ticket

**Comment by amey91** [comment]
@hoang-innomizetech I would ideally not want to skip type check for dependencies. Can we get a better fix for this?
