### ISSUE TITLE
cli@multienv allows uppercase characters in env, which causes s3 buckets to fail during publish

### ISSUE THREAD

**Issue by danludwig** [aws-amplify/amplify-js#2364]
**Describe the bug**
When starting with a new project, the cli@multienv prompts for an environment. There are no items to select from, user types the environment name, and uppercase characters are allowed. If the user enters "Dev", or any environment with a capital letter, then adds hosting and tries to push, the nested hosting stack will fail to create due to "S3 bucket names cannot contain uppercase characters". 

**To Reproduce**
1. Create a new project and amplify init
2. During init, enter "Dev" for environment
3. amplify add hosting
4. amplify push

**Expected behavior**
Stack will lowercase the environment name for the s3 bucket that gets deployed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 70.0.3538.110

**Additional context**
Experienced this issue on Friday 12/14/2018

**Comment by UnleashedMind** [comment]
I have pasted the bug to the amplify-cli repo
https://github.com/aws-amplify/amplify-cli/issues/602

**Comment by UnleashedMind** [comment]
This issue is already solved in the latest version of the multienv
0.2.1-multienv.12. 
Could you please update the cli and confirm?

**Comment by kaustavghosh06** [comment]
Closing this issue since it's already been fixed. Please feel free to re-open if you're still facing this problem.
