### ISSUE TITLE
Failing builds in Typescript project using aws-amplify/api since this line was added

### ISSUE THREAD

**Issue by nihakue** [aws-amplify/amplify-js#2365]
**Describe the bug**
Since the addition of the [linked line](https://github.com/aws-amplify/amplify-js/blob/be5ec549d8c30b42e01701644d9e12aed2b9e39d/packages/api/src/types/index.ts#L13), our builds have been failing with:

```
<truncated>/@aws-amplify/api/lib/types/index.d.ts
ERROR in <truncated>/node_modules/@aws-amplify/api/lib/types/index.d.ts(1,30):
TS7016: Could not find a declaration file for module 'graphql/language/ast'. '<truncated>/node_modules/graphql/language/ast.js' implicitly has an 'any' type.
  Try `npm install @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql/language/ast';`
```

We are using typescript@3.2.2 and @aws-amplify/api@1.0.23. Our tsconfig.json is: 

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": false,
    "typeRoots": [
      "./typings/", "./node_modules/@types/"
    ]
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ]
}
```

I can work-around the issue with the following steps
1. Add @types/graphql as a dev dependency
2. Change typsecript lib ( tsconfig.json: compilerOptions.lib: ["esnext", "dom"])

At the moment, we aren't using graphql, so the graphql dependency is a little unfortunate.

**To Reproduce**
1. Create a new typescript app (we use [create-react-app-ts](https://github.com/wmonk/create-react-app-typescript))
2. Add a dependency on @aws-amplify/api
3. Try to build

**Expected behavior**
When not using graphql, I shouldn't have to use graphql types.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Any
 - Version Any

**Comment by revmischa** [comment]
Same problem here

**Comment by amwill04** [comment]
Still no resolution to this?

**Comment by ffjanhoeck** [comment]
Same problem

**Comment by msweetland** [comment]
Reporting the same issues. A workaround I found is only installing the modules of Amplify that are needed and not the entire library.

`yarn add @aws-amplify/auth`

Most likely will not solve your issues if you're using the module that requires the graphql types.

**Comment by silltho** [comment]
I'm facing the same issue. Any updates to fix this?

**Comment by mspoulsen** [comment]
Me too :(

**Comment by pbrianmackey** [comment]
Upgrading to `"aws-amplify": "1.1.24-beta.10",` fixed it for me

**Comment by ColtenP** [comment]
Another work around for this issue is to just declare your .d.ts file and place the following inside of the file.
`declare module 'graphql/language/ast' {
  export type DocumentNode = any
}`

**Comment by jono-allen** [comment]
I got around this by using patch package and patching @types/react-native with 
```
interface Storage {}
interface Cache {}
interface File {}
interface ServiceWorker {}
```

**Comment by coleHafner** [comment]
> Another work around for this issue is to just declare your .d.ts file and place the following inside of the file.
> `declare module 'graphql/language/ast' { export type DocumentNode = any }`

Just in case anyone is wondering, the best case to declare this file is to create a `types.d.ts` file in `src/`

**Comment by leopsidom** [comment]
Still having this problem with `"aws-amplify": "^3.0.13"`

**Comment by galbus** [comment]
[@types/graphql](https://www.npmjs.com/package/@types/graphql) is deprecated, because:

> graphql provides its own type definitions

Try adding [graphql](https://www.npmjs.com/package/graphql) as a dev dependency:

```
yarn add -D graphql
```

For me, this added `"graphql": "^15.3.0",` into `devDependencies`, and removed the error I was seeing from `"aws-amplify": "^3.0.20"`.

**Comment by Ruu-i** [comment]
i added `declare module 'graphql/language/ast' { export type DocumentNode = any }` to my d.ts file but I got this error `import { GraphQLError } from 'graphql/error/GraphQLError';`. so i added `declare module 'graphql/error/GraphQLError';` in to my d.ts file. but I got error `    errors?: GraphQLError[];`.  how to fix it?

**Comment by nikhilavula** [comment]
installing graphql solved the problem for me.

https://www.npmjs.com/package/graphql

**Comment by Ruu-i** [comment]
@nikhilavula i tried it but not worked for me

**Comment by Ruu-i** [comment]
@nikhilavula i tried it. it worked. but in the browser console show this error:
```ERROR TypeError: Cannot read property 'viewContainerRef' of undefined
    at AuthenticatorComponent.push.XRHW.AuthenticatorComponent.loadComponent (authenticator.factory.js:47)
    at AuthenticatorComponent.push.XRHW.AuthenticatorComponent.ngOnInit (authenticator.factory.js:31)
    at callHook (core.js:4776)
    at callHooks (core.js:4746)
    at executeInitAndCheckHooks (core.js:4698)
    at refreshView (core.js:9153)
    at refreshComponent (core.js:10291)
    at refreshChildComponents (core.js:8935)
    at refreshView (core.js:9188)
    at refreshEmbeddedViews (core.js:10245)
```

**Comment by CGarces** [comment]
> i added `declare module 'graphql/language/ast' { export type DocumentNode = any }` to my d.ts file after that I got this error `import { GraphQLError } from 'graphql/error/GraphQLError';`. so i added `declare module 'graphql/error/GraphQLError';` in to my d.ts file. again I got error ` errors?: GraphQLError[];`. how to fix it?

hi @Ruu-i try:

```javaScript
declare module 'graphql/language/ast' { export type DocumentNode = any }
declare module 'graphql/error/GraphQLError' { export type GraphQLError = any }
```

**Comment by cadesalaberry** [comment]
@CGarces I tried your solution but it led to:
```
Invalid module name in augmentation. Module 'graphql/error/GraphQLError' resolves to an untyped module at '/projects/my-last-project/node_modules/graphql/error/GraphQLError.js', which cannot be augmented.ts(2665)
module "graphql/error/GraphQLError"
```
Here is my original error:
```
ERROR in /projects/my-last-project/node_modules/@aws-amplify/api-graphql/lib-esm/types/index.d.ts(1,30):
1:30 Could not find a declaration file for module 'graphql/error/GraphQLError'. '/projects/my-last-project/node_modules/graphql/error/GraphQLError.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/graphql` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql/error/GraphQLError';`
  > 1 | import { GraphQLError } from 'graphql/error/GraphQLError';
      |                              ^
    2 | import { DocumentNode } from 'graphql/language/ast';
    3 | export interface GraphQLOptions {
    4 |     query: string | DocumentNode;
```

**Comment by javadtaghia** [comment]
Install npm install graphql --save-dev
