### ISSUE TITLE
Multi-region support for XR Category

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-js#2366]
**Is your feature request related to a problem? Please describe.**
Currently the `XR.configure()` method expects an object with this schema:

```
XR.configure({ // XR category configuration
  region: 'us-west-2', // Sumerian region
  scenes: { 
    "scene1": { // Friendly scene name
      sceneConfig: scene1Config // Scene configuration from Sumerian publish
      publishParamOverrides: { alpha: true } // Optional publish parameters
    }
  }
});
```

This makes it (seemingly) impossible to setup multiple scenes residing in different regions.

**Describe the solution you'd like**
Change the schema to be this:

```
XR.configure({ 
  scenes: { 
    "scene1": { 
      region: 'us-west-2', // Sumerian region for `scene 1`
      sceneConfig: scene1Config // Scene configuration from Sumerian publish
      publishParamOverrides: { alpha: true } // Optional publish parameters
    }
  }
});
```

In other words, attach the region at the scene level rather than the XR category level.

**Describe alternatives you've considered**
Move all scenes to the same region. Not very difficult to do, but it does require all Sumerian developers work in the same region (again not very difficult to do). 

**Additional context**
Since all Sumerian scenes are fronted by a CloudFront distribution, the actual region that the Sumerian scene sits in seems like a relative non-issue in terms of latency.

**Comment by jordanranz** [comment]
This is a feature request that is currently on the Sumerian team's backlog. Once the change is made on their end we can add the functionality to the Amplify code. The proposed solution is to add the region inside of the sceneConfig downloaded from the Sumerian scene publish. I'll send an update to this issue when we have made progress here.

**Comment by jkeys-ecg-nmsu** [comment]
@jordanranz does XR support cross-account authentication? Assuming the identity pool's role(s) allow for all of our accounts ot execute scenes, it should work?

On this assumption, I'm closing this issue. It's currently a non-issue for us and a headache for you all. 

CloudFront's the true MVP.
