### ISSUE TITLE
Cannot do a ng-build with prod/aot parameters set

### ISSUE THREAD

**Issue by willkara** [aws-amplify/amplify-js#2368]
**Describe the bug**
This is almost a complete copy of issue #766. I cannot run **ng build** with AOT without getting an error.

I followed the [example ](https://aws-amplify.github.io/docs/js/api) from the Amplify website. 

My main.ts looks like:

```
import {enableProdMode} from '@angular/core';
import {platformBrowserDynamic} from '@angular/platform-browser-dynamic';

import {AppModule} from './app/app.module';
import {environment} from './environments/environment';

import Amplify, { API } from 'aws-amplify';
import aws_exports from './aws-exports';

Amplify.configure(aws_exports);

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));

```

And my method looks like:

```
import {API} from 'aws-amplify';

.......

  onSubmit(f: NgForm) {
    console.log(f);

    const apiName = 'ContactMailer';
    const path = '/contact';
    const myInit = {
      body: {test: 'tester'}, // replace this with attributes you need
      headers: {} // OPTIONAL
    };


    API.post(apiName, path, myInit).then(response => {
      // Add your code here
      console.log(response);
    }).catch(error => {
      console.log(error.response);
    });

  }
```

I am trying to build with the following commands:

`ng build --prod --aot`

and I get the following error:

```
ERROR in ./node_modules/aws-amplify-angular/src/aws-amplify-angular.module.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\Users\***\Development\Projects\Wamplify\node_modules\aws-amplify-angular\src\aws-amplify-angular.module.t
s is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged l
ibrary. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular P
ackage Format (https://goo.gl/jB3GVv).
```

It will only successfully build with the following build command:

ng build --prod --aot=false --build-optimizer=false

**To Reproduce**

1. Create a basic Angular CLI app
2. Run amplify init
3. Create an API
4. Run ng build --prod --aot

**Expected behavior**
I expect a full prod build with AOT enabled to complete successfully

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [WebStorm IDE]
 - Version --- NodeJS Deps:

-  "@angular/animations": "~7.1.0",
-     "@angular/common": "~7.1.0",
-     "@angular/compiler": "~7.1.0",
-     "@angular/core": "~7.1.0",
-     "@angular/forms": "~7.1.0",
-     "@angular/platform-browser": "~7.1.0",
-     "@angular/platform-browser-dynamic": "~7.1.0",
-     "@angular/router": "~7.1.0",
-     "aws-amplify": "^1.1.16",
-     "aws-amplify-angular": "^2.1.3",

**Additional context**
This seems to be an issue that was actually resolved earlier. My guess is that I have a bad version mismatch or need to enable something like the build_optimizer being off in angular.json.

I also came across the following PRs while doing my research...

https://github.com/aws-amplify/amplify-js/pull/958

https://github.com/aws-amplify/amplify-js/pull/958

**Comment by haverchuck** [comment]
@willkara If you have a chance, will you please see if removing the importation of API resolves this issue?  I'm not suggesting that this is a solution (obviously); however, this information would help us determine whether this is related to another issue that was submitted.

**Comment by willkara** [comment]
@haverchuck , just to confirm...

turn this:

`import Amplify, { API } from 'aws-amplify';
`

into this:

`import Amplify from 'aws-amplify';
`

in my main.ts file?

What would you want me to do in my service file? Wouldn't that need an import of API to use as a reference in the method?

**Comment by haverchuck** [comment]
@willkara I was basically trying to see if the issue was isolated to the API module (I have reason to believe it is).  This wouldn't be a solution, and you would need to comment out the references to API.  You could try importing Auth or another module for the purpose of the test.  If you don't have time for this don't worry about it - I'll try to replicate it on my side.

**Comment by willkara** [comment]
@haverchuck I still **wasn't** able to build after:

- Removing all references to API in imports & classes

Only way to do a ng build --prod --aot was to take out all references to amplify in the above and ***.module.ts**. AKA, take it out of the project.

I **was** able to build with:

- Amplify setup in main.ts

Could NOT build with the imports in app.module.ts

Are you thinking it's an issue with how aot processes the imported classes? I'm not that familiar with aot, but I wonder if it's too agressive and the amplify service has a few holes in how it's compiled.

**Comment by willkara** [comment]
So after making sure I ONLY imported:

`import {API} from 'aws-amplify';
`

Within the necessary classes/services, I was able to build. It seems like it DIDN'T like me import the AngularService/Angular Component modules in the *.module.ts files.

**Comment by willkara** [comment]
@haverchuck 

So I can confirm it WILL build with:

`ng build --prod
`
with the following settings in angular.json

```
"optimization": true,
"outputHashing": "all",
"sourceMap": false,
"extractCss": true,
"namedChunks": true,
"aot": false,
"extractLicenses": true,
"vendorChunk": false,
"buildOptimizer": false,
```

I am importing the services like this:

in main.ts:

```
import Amplify from 'aws-amplify';
import aws_exports from './aws-exports';

Amplify.configure(aws_exports);
```

In a service class:

```
import {API} from 'aws-amplify';

....

  constructor(private amp: AmplifyService) {
  }

...

return API.get(this.apiName, this.path, getAllInit);
```

It still fails when I try building with aot enabled:

```
ERROR in ./node_modules/aws-amplify-angular/src/aws-amplify-angular.module.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\Users\wkara\Resilio Sync\Development\Projects\Wamplify\node_modules\aws-amplify-angular\src\aws-amplify-angular.module.
ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.

```

Just to check, I also tried importing the Auth module and got the same kind of error.

**Comment by haverchuck** [comment]
@willkara - I'm able to build with `ng build --prod --aot`, but I'll keep digging into this issue.

**Comment by willkara** [comment]
@haverchuck , I'll try and experiment with a minimal app and see if I messed it up anywhere. Thanks for looking into it.

**Comment by willkara** [comment]
@haverchuck got it working! I had to get rid of all references to the AmplifyService & AmplifyComponents to get it working.

So now, all I do is the initial setup in main.ts and import the individual parts (api, auth ...etc) in the respective services/classes.
