### ISSUE TITLE
PUBSUB connect, disconnect with mqttStatus callback

### ISSUE THREAD

**Issue by praveshkhatana** [aws-amplify/amplify-js#2372]
**Is your feature request related to a problem? Please describe.**
We are using IOT for presence system and there is no such method to Connect & Disconnect like we have in other IOS/Android IOT SDK. Also no way to check the mqttStatus. It requires to build the logic based on it, for example, we can update user online/offline status in Database based on returned mqttStatus 1/3/5.

**Describe the solution you'd like**
Provide Connect (with MqttStatus Callback) & Disconnect methods.

**Describe alternatives you've considered**
Any other way to provide MqttStatus Callback(important part, need this to update database) with current Subscribe method. But I think, It won't work in this way. It should be the same like we have in IOS/Android SDK.

**Comment by Stefano1990** [comment]
Since this has been closed what is the recommended approach for implementing a presence system in aws amplify?

**Comment by stocaaro** [comment]
We've just released connection state monitoring for the IoT integration, which is now [documented here](https://docs.amplify.aws/lib/pubsub/subunsub/q/platform/js/). For the use-case of presence monitoring, I wouldn't recommend the PubSub IoT integration as this requires the user to be logged in and individually authorized against the IoT policy from [the PubSub getting started guide](https://docs.amplify.aws/lib/pubsub/getting-started/q/platform/js/).

If I where building presence monitoring today, I would use [the API category](https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/js/) to add a non-persisted subscribe-able mutation which other users could then subscribe to which other users can listen for. If each user is signaling presence once per minute, then all other users can track the number of events that have happened in the past minute.

Adjust as needed to account for auth/use uniqueness or persistence to best capture initial state.
