### ISSUE TITLE
Cannot generate presigned URL for AWS KMS-managed encrypted files

### ISSUE THREAD

**Issue by aldo-roman** [aws-amplify/amplify-js#2378]
**Describe the bug**
If a file is AWS KMS-managed encrypted, an error is thrown while opening the generated presigned URL.

Error is a flag should explicity declare `signatureVersion: 'v4'`

**To Reproduce**
1. Create an AWS KMS-encrypted file in S3.
2. `S3.get()` to that file.

**Expected behavior**
Presigned URL should work as expected.

**Screenshots**

**Comment by elorzafe** [comment]
Hi @aldo-roman thanks for your pr, is already merged on master branch. You can test it on our latest unstable (aws-amplify@1.1.18-unstable.0) meanwhile we do new release.
