### ISSUE TITLE
AWS Credentials file preferred over Cognito credentials when using API in node.js

### ISSUE THREAD

**Issue by rustyconover** [aws-amplify/amplify-js#2380]
**Describe the bug**
When using the API Gateway calling functionality credentials supplied by aws-sdk are preferred over the Amplify obtained credentials.

Using node.js this is a common.  The credentials obtained via Cognito should be preferred.

When ~/.aws/credentials does not exist:
```
DEBUG] 05:37.918 RestClient - GET https://21bqwalunc.execute-api.us-east-1.amazonaws.com/test2/private/cognito
[DEBUG] 05:37.920 Credentials - getting credentials
[DEBUG] 05:37.920 Credentials - picking up credentials
[DEBUG] 05:37.920 Credentials - getting new cred promise
[DEBUG] 05:37.920 Credentials - checking if credentials exists and not expired
[DEBUG] 05:37.920 Credentials - is this credentials expired?
[DEBUG] 05:37.922 Credentials - credentials not changed and not expired, directly return
[DEBUG] 05:37.924 Signer - GET
```

When ~/.aws/credentials does exist.
```
[DEBUG] 40:53.9 RestClient - GET https://21bqwalunc.execute-api.us-east-1.amazonaws.com/test2/private/cognito
[DEBUG] 40:53.10 Credentials - getting credentials
[DEBUG] 40:53.11 Credentials - picking up credentials
[DEBUG] 40:53.11 Credentials - getting new cred promise
[DEBUG] 40:53.11 Credentials - setting credentials from aws
[DEBUG] 40:53.11 Credentials - Load credentials successfully SharedIniFileCredentials {
```

This is also likely related to #1999.

**To Reproduce**

Have a valid AWS credentials file in ~/.aws/credentials call any Amplify API Gateway operation.

**Expected behavior**

Use the Cognito obtained credentials.
Or have a configuration option to disable the loading of ~/.aws/credentials.

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Node

**Comment by haverchuck** [comment]
@rustyconover  At this time we do not support Node.js usage of the Amplify library; however, we understand that there is demand for such support and are discussing it.
