### ISSUE TITLE
AWS Cognito Hosted UI - How to allow an EXTERNAL_PROVIDER user to create password?

### ISSUE THREAD

**Issue by TOPS-Aman** [aws-amplify/amplify-js#2383]
Cognito - Hosted UI 

In Cognito, is there any way where I can allow a user (Account status: External provider) to create a password for their account and do login using username and password. I am using a Hosted UI.

Consider a case where a user logged in using the Google sign-in method and the user pool has a user entry. I have given the user a preferred username and email options to sign in. but since it does not have a password yet, the user should be able to reset their password using forgot password method. But I get the error "User password cannot be reset in the current state." Can you please suggest if there is any method or workaround for this.

Thanks.

**Comment by TOPS-Aman** [comment]
Any update on this?

**Comment by TOPS-Aman** [comment]
I have google login along with custom email/pass way. This should be a great feature considering a user has to always remember that he can only access his account using his google account.

**Comment by sammartinez** [comment]
Im going to close this issue, this seems to be related specifically to Cognito Hosted UI and not Amplify specifically. However, this is a feature request so please open a [AWS Forums](https://forums.aws.amazon.com/tags/cognito) ticket on Cognito for this feature request
