### ISSUE TITLE
Amplify with Angular Universal - ReferenceError: window is not defined 

### ISSUE THREAD

**Issue by jocactus** [aws-amplify/amplify-js#2388]
**Describe the bug**
I cannot compile and serve my Angular Universal application. 
I have the following error during the compilation:
```
var URL = window.URL || window.webkitURL || window.mozURL || window.msURL;
                          ^

ReferenceError: window is not defined
```

**To Reproduce**
1. Create an Angular project `ng new amplify-universal`
2. Install Universal `ng add @nguniversal/express-engine --clientProject amplify-universal`
3. Install Amplify as describe in the [documentation](https://aws-amplify.github.io/docs/js/ionic)
4. Compile and serve the Universal app `npm run build:ssr && npm run serve:ssr`
4. See following error

```
/Users/jocactus/Programming/tmp/amplify-universal/dist/server.js:134135
                var URL = window.URL || window.webkitURL || window.mozURL || window.msURL;
                          ^

ReferenceError: window is not defined
    at module.exports (/Users/jocactus/Programming/tmp/amplify-universal/dist/server.js:134135:27)
    at /Users/jocactus/Programming/tmp/amplify-universal/dist/server.js:134149:30
    at Object../node_modules/aws-amplify-angular/dist/src/components/interactions/chatbot/aws-lex-audio.js.5../worker.js (/Users/jocactus/Programming/tmp/amplify-universal/dist/server.js:134297:15)
    at s (/Users/jocactus/Programming/tmp/amplify-universal/dist/server.js:133687:13)
    at /Users/jocactus/Programming/tmp/amplify-universal/dist/server.js:133687:71
    at /Users/jocactus/Programming/tmp/amplify-universal/dist/server.js:133692:27
    at Object../node_modules/aws-amplify-angular/dist/src/components/interactions/chatbot/aws-lex-audio.js.1../recorder.js (/Users/jocactus/Programming/tmp/amplify-universal/dist/server.js:133897:15)
    at s (/Users/jocactus/Programming/tmp/amplify-universal/dist/server.js:133687:13)
    at /Users/jocactus/Programming/tmp/amplify-universal/dist/server.js:133687:71
    at Object.<anonymous> (/Users/jocactus/Programming/tmp/amplify-universal/dist/server.js:134070:48)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! amplify-universal@0.0.0 serve:ssr: `node dist/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the amplify-universal@0.0.0 serve:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jocactus/.npm/_logs/2018-12-19T20_55_36_803Z-debug.log
```

**Expected behavior**
The Universal app is served with Amplify.

**Desktop (please complete the following information):**
 - OS: macOS Mojave v 10.14.2
 - Browser: Chrome Version 71.0.3578.98 (Build officiel) (64 bits)

**Additional context**
excerpt of my package.json

```
"dependencies": {
    "@angular/animations": "~7.1.0",
    "@angular/common": "~7.1.0",
    "@angular/compiler": "~7.1.0",
    "@angular/core": "~7.1.0",
    "@angular/forms": "~7.1.0",
    "@angular/http": "~7.1.0",
    "@angular/platform-browser": "~7.1.0",
    "@angular/platform-browser-dynamic": "~7.1.0",
    "@angular/platform-server": "~7.1.0",
    "@angular/router": "~7.1.0",
    "@nguniversal/express-engine": "^7.0.2",
    "@nguniversal/module-map-ngfactory-loader": "v7.0.2",
    "aws-amplify": "^1.1.17",
    "aws-amplify-angular": "^2.1.4",
    "core-js": "^2.5.4",
    "express": "^4.15.2",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
```

**Comment by elorzafe** [comment]
Hi @jocactus you should add this polyfills.ts
```(window as any).global = window;```

https://aws-amplify.github.io/docs/js/angular#angular-6-support

**Comment by jocactus** [comment]
Unfortunately, this step is already done.

**Comment by neonguru** [comment]
I see the problem occurs (server side where there is no window object) because window is not defined in the following file, line 472:
node_modules/aws-amplify-angular/dist/src/components/interactions/chatbot/aws-lex-audio.js

The app is trying to load AmplifyService when this happens.
Which is loading the following in order:
AmplifyAngularModule
./node_modules/aws-amplify-angular/dist/src/components/interactions/chatbot/chatbot.factory.js
./node_modules/aws-amplify-angular/dist/src/components/interactions/chatbot/chatbot.component.ionic.js
./node_modules/aws-amplify-angular/dist/src/components/interactions/chatbot/chatbot.component.core.js
./node_modules/aws-amplify-angular/dist/src/components/interactions/chatbot/aws-lex-audio.js

Perhaps it could not run this code if window is not defined - always assume they are not logged in. I have put conditions around Amplify.configure to not execute if server side, but I see no way to conditionally not include the AmplifyService (when server side) in the AppModule providers.

Not sure if you know that Angular Universal runs the app server side to serve up full HTML to the client for SEO purposes. I do not need to serve Auth pages though, so I am coding it to omit full HTML for those pages.

**Comment by jocactus** [comment]
@neonguru How do you put conditions around `Amplify.configure`?
I read on the [Universal "Gotchas"](https://github.com/angular/universal/blob/master/docs/gotchas.md) that I need to inject the `PLATFORM_ID` to check the current platform but I don't find a way to do it directly in the `main.ts`.

**Comment by neonguru** [comment]
@jocactus you should read the amplify angular docs.

I have a service that imports Amplify from 'aws-amplify' and in the constructor I call Amplify.configure(amplify) where amplify is imported from 'aws-exports'.

Yes, you can use isPlatformBrowser(this.platformId) to see if you are browser side.

**Comment by neonguru** [comment]
@jocactus I put it in a service after it wasn't working in main.ts.

**Comment by D2KX** [comment]
Alright, a couple of notes:

1) The error is thrown by the Interactions module. Think about if you really need the AmplifyService from aws-amplify-angular, or if aws-amplify with modular imports (and not importing the Interactions module) isn't what you want anyway for a smaller bundle size.

2) Angular uses Domino to "emulate" document and window objects, but it is not available quite this early into the application bootstrap. You can look into creating a window with Domino in your server.ts before the app renders. Amplify is focused on clients, so I wouldn't expect them to be overly careful about checking for these kinds of things as it is not strictly an Amplify issue.

3) The polyfills.ts in Angular does not have any effect on the server, it only gets used in a Browser environment.

4) What you really want is probably to move the import/configure logic out of the main.ts, use Angular's isPlatformBrowser/isPlatformServer checks before configuring/using Amplify and maybe ditching aws-amplify-angular for just aws-amplify and its modular imports.

**Comment by neonguru** [comment]
@D2KX I was able to get it mostly working without the AmplifyService and aws-amplify-angular, which (in hindsight) is what I think you are saying in note 1.

@jocactus check out the [angular-aws-amplify](https://github.com/daikiojm/angular-aws-amplify) repo for an example.

**Comment by jocactus** [comment]
@neonguru @D2KX Thanks for your notes. I refactored my code without aws-amplify-angular and I don't have the problem anymore.

**Comment by ntegral** [comment]
If you are looking to use Angular Universal with AWS Cognito you can check out ngx-amplify @https://www.npmjs.com/package/ngx-amplify
