### ISSUE TITLE
currentAuthenticatedUser bypassCache true not working

### ISSUE THREAD

**Issue by MatteoGioioso** [aws-amplify/amplify-js#2389]
**Describe the bug**
When I try to change user email the status of 
`signInUserSession.idToken.payload.email_verified` should be false. On the AWS console it actually is. So it is correctly working.

However, when I call:
```
Auth.currentAuthenticatedUser({
    bypassCache: true
}).then(user => console.log(user))
```
the 
`signInUserSession.idToken.payload.email_verified`

is still true

**Expected behavior**
I am expecting to retrieve the current updated changes as stated from the docs

> If set to true, this call will send a request to Cognito to get the latest user data

**Comment by powerful23** [comment]
@MatteoGioioso can you confirm that the `attributes` in the `user` object returned by `Auth.currentAuthenticatedUser` has `email_verified` and it is correctly updated? The `idToken` in the `signInUserSession` will not be updated when calling `Auth.currentAuthenticatedUser`

**Comment by MatteoGioioso** [comment]
@powerful23 Yes the `attributes` in the user object are correctly updated.
So, is not possible to get the update value from the `idToken` object? I noticed it is updated when Cognito requests new refresh tokens.
Anyway I am closing this, thanks

**Comment by powerful23** [comment]
@MatteoGioioso because the idToken is granted when the user signs in which will be unchanged until the user signs in again or it's refreshed by the refresh token.

**Comment by nihp** [comment]
Here I am also using the Auth.currentAuthenticatedUser. I am experiencing the {401,{"message":"The incoming token has expired"}.

How can I re-initialize or refresh the token in such conditions.

Auth.currentAuthenticatedUser({
    bypassCache: true
}).then(user => console.log(user))
