### ISSUE TITLE
aws-mobile-react-native-starter: Invariant Violation: Invariant Violation: The navigation prop is missing for this navigator

### ISSUE THREAD

**Issue by Chinna12345678** [aws-amplify/amplify-js#2391]
**Describe the bug**
Looks like we need to define appcontainer directly if we use React-Navigation 3.0.

and the code in this master repository is based on react navigation 2.0 or lower and this is the reason the code is broken and not working anymore.
debugging is very difficult , need to look at each and every JSON file to resolve the issues.

Can someone review all the JSON files and how the AppContainers defined 

**To Reproduce**
just pull the code (aws-mobile-react-native-starter) directly from github and try to execute 

### _Actual result:_
Invariant Violation: The navigation prop is missing for this navigator. In react-navigation 3 you must set
 up your app container directly. More info: https://reactnavigation.org/docs/en/app-containers.html

This error is located at:
    in Navigator (at App.js:114)
    in AppContainer (at WithAuth.js:75)
    in _class (at renderApplication.js:34)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:33)
getDerivedStateFromProps

**Comment by Chinna12345678** [comment]
can someone please help me with this issue?

**Comment by jordanranz** [comment]
Hey @Chinna12345678,

Apologies for the late response. By 'pull the code' do you mean you are cloning the repo and trying to run the app from the cloned repo or are you trying to use your own react-native app?
