### ISSUE TITLE
Use Storage server side

### ISSUE THREAD

**Issue by RedHatter** [aws-amplify/amplify-js#2397]
I have an app using Amplify for authentication and storage. Everything works great client side. The user can sign in and get/set S3 objects. The problem is that I need to use Storage server side as well. I pass the `jwtToken` as a header but don't know how to use it with Storage.

    // Client side
    Amplify.configure({
      Storage: {
        region: 'us-west-1',
        bucket: '...',
        identityPoolId: '...'
      },
      Auth: {
        region: 'us-west-2',
        identityPoolId: 'us-west-2:...,
        userPoolId: 'us-west-2_...,
        userPoolWebClientId: '...'
      }
    })
   
    fetch(url, {
      method: 'POST',
      body: JSON.stringify(body)
      headers: {
        'Content-Type': 'application/json',
        Authorization: (await Auth.currentSession()).idToken.jwtToken
      }
    })

    // Server side
    await Storage.put(path, buffer, {
        contentType: 'image/png' 
        Authentication: ctx.headers.authorization // doesn't work
    })

**Comment by elorzafe** [comment]
@RedHatter 

Can you try this?

```
import  { Storage, Auth } from 'aws-amplify';
import { AWS } from "@aws-amplify/core";

AWS.config.update({
  credentials: new AWS.Credentials ({
    accessKeyId: "xxxxxxxxxxxxxxx",
    secretAccessKey: "xxxxxxxxxxxxxxxxxxxxx"
  })
});

Storage.configure({
  "bucket": "xxxxxxxxxxxxxxxxxxxxxxx",
  "region": "xxxxxxx",
});

Auth.configure({
  identityPoolId: '',
  region: ''
});
```

**Comment by elorzafe** [comment]
@RedHatter I found a problem with aws credentials while testing that code (that was fixed with pr 2399). Can you try amplify latest unstable version (1.1.18-unstable.3) with this code?

```
import { Storage } from 'aws-amplify';
import { AWS } from "@aws-amplify/core";

AWS.config.update({
  credentials: new AWS.Credentials ({
    accessKeyId: "xxxxxxxxxxxx",
    secretAccessKey: "xxxxxxxxxxxxxxxxxxxxxxx"
  })
})

Storage.configure({
  "bucket": "xxxxxxxxxxxxx",
  "region": "xx-xxxx-x",
});
```

You wont need to configure Auth if you set credentials that way

**Comment by elorzafe** [comment]
@RedHatter this worked for you?

**Comment by jordanranz** [comment]
This should be fixed in the latest version of aws-amplify as per @elorzafe's comments. Closing this issue now. Please go ahead and reopen if you have any further questions or concerns.
