### ISSUE TITLE
Angular Amplify Authenticator 'hide' attribute does not work

### ISSUE THREAD

**Issue by holtc** [aws-amplify/amplify-js#2402]
**Describe the bug**
The `hide` input property does not work on the `<amplify-authenticator>` component

**To Reproduce**
1. set `[hide]` to `['Greetings']`, and after successful sign in, the greetings page still shows.
2. set a breakpoint in the `shouldHide` function in `authenticator.component.core.ts`, and you will see that `hide` is set to `[]`

**Expected behavior**
The `hide` attribute should be respected

**Additional context**
In `authenticator.component.core.ts`, the code for `hide` is as follows:

```
@Input()
hide: string[] = [];
```

However, for the other input attribute `signUpConfig`, the code is as follows:
```
@Input()
set signUpConfig(signUpConfig: any) {
  this._signUpConfig = signUpConfig;
}
```

Maybe this slight difference and lack of the `_hide` attribute is causing the error?

**Comment by haverchuck** [comment]
@holtc  - This should be fixed on our unstable build (npm i aws-amplify-angular@unstable).

**Comment by AdamShechter9** [comment]
this is still an issue

**Comment by jarrettj** [comment]
Should we use JS hacks to hide things? :) Is there a working example of how to hide auth components? Thanks.

**Comment by vjindalaurea** [comment]
Hi any update on it ?
