### ISSUE TITLE
non-required phone number bug in aws-amplify-angular

### ISSUE THREAD

**Issue by holtc** [aws-amplify/amplify-js#2404]
**Describe the bug**
There is a bug when a phone number is not required using `signUpConfig`, I assume it is similar to [this](https://github.com/aws-amplify/amplify-js/pull/2065).

**To Reproduce**
Create a `signUpConfig` as below and pass as 
`<amplify-authenticator [signUpConfig]="signUpConfig"></amplify-authenticator>`:

```
    const signUpConfig = {
        hideAllDefaults: true,
        signUpFields: [
            {
                label: 'First Name',
                key: 'nickname',
                required: true,
                displayOrder: 1,
                type: 'text',
            },
            {
                label: 'Email',
                key: 'username',
                required: true,
                displayOrder: 2,
                type: 'email',
            },
            {
                label: 'Password',
                key: 'password',
                required: true,
                displayOrder: 3,
                type: 'password',
            }
        ]
    };
```

**Expected behavior**
The form should submit without the phone number, but there is an error thrown, and the form never submits.

**Screenshots**

**Additional context**
You need to change the following lines (I think line 203) in `sign-up.component.core.ts` from 

```
this.user.phone_number = `+${this.country_code}${this.local_phone_number}`;
```

to something like 

```
// Check to ensure the phone number exists
if (this.user.phone_number) {
    // format phone number
    this.user.phone_number = `+${this.country_code}${this.local_phone_number}`;
}
```

**Comment by haverchuck** [comment]
@holtc This should be fixed on our @unstable build (npm i aws-amplify-angular@unstable).  Please let us know if it is not!

**Comment by holtc** [comment]
Looks good, thanks!
