### ISSUE TITLE
onStateChange gets called on page refresh when state is still the same.

### ISSUE THREAD

**Issue by amnajunaid** [aws-amplify/amplify-js#2405]
** Which Category is your question related to? **
bug | incorrect usage
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **

Hi, i am using Authenticator component on a page lets say /auth. After i signed in, when i refresh the page. Why onStateChange gets called when state is still the same.
This line causes onStateChange called -> https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Auth/Authenticator.jsx#L125

Following is my code:
```
const redirectTo = (state: string) => {
	if (state === 'signedIn') {
		router.history.push('/sample');
	}
};

return (
<Authenticator hideDefault={true} onStateChange={(state) => redirectTo(state)} >
	<SignIn />
	<SignUp />
	<ConfirmSignUp />
	<ForgotPassword />
	<Greetings />
</Authenticator>
);```

**Comment by powerful23** [comment]
@amnajunaid that's expected because when the page is refreshed, the auth state would be unknown until `Authenticator` checks the current user and then set the state back to `signedIn`. What's the issue you have due to this behavior?

**Comment by powerful23** [comment]
Closing this issue due to no further response. Feel free to reopen if you still have this issue.
