### ISSUE TITLE
No Cyprus phone code at registration form

### ISSUE THREAD

**Issue by boskiv** [aws-amplify/amplify-js#2408]
** Which Category is your question related to? **
React Create Account form
** What AWS Services are you utilizing? **
Auth (Cognito)
** Provide additional details e.g. code snippets **
Cyprus phone code (+357) is missing
![screenshot 2018-12-24 at 8 59 16 pm](https://user-images.githubusercontent.com/1939783/50405540-f8bfa280-07be-11e9-8fa2-34982547a4de.png)

**Comment by boskiv** [comment]
And next question, is it possible to filter out phone_codes that we will not use for registration ?

**Comment by haverchuck** [comment]
Fix should be available in unstable build (npm i aws-amplify-react@unstable)
