### ISSUE TITLE
<SelectMFAType> widget -> preselect current user MFA option

### ISSUE THREAD

**Issue by ColdFire87** [aws-amplify/amplify-js#2410]
**Is your feature request related to a problem? Please describe.**

> The `<SelectMFAType>` shows available MFA types but does not preselect what the current MFA option
> is configured for the user.

**Describe the solution you'd like**

> Do something along the lines of:
```javascript
componentDidMount() {
    this.inputs = {}
    
    Auth
        .getPreferredMFA(this.props.authData)
        .then(option => {
            switch (option) {
            case 'SMS_MFA':
                this.inputs['SMS'] = true;
                break;
            case 'SOFTWARE_TOKEN_MFA':
                this.inputs['TOTP'] = true;
                break;
            case 'NOMFA':
                this.inputs['NOMFA'] = true;
                break;
            }
        })
}
```
**Describe alternatives you've considered**

> Overriding / Rewriting the component

**Additional context**

> Nothing here

**Comment by tannerabread** [comment]
Hi 👋 Closing this as resolved. We no longer support this component but you can create your own flow with selecting MFA type as shown [here](https://docs.amplify.aws/lib/auth/mfa/q/platform/js/#setup-mfa-type) or through the code that you supplied.

Thank you!
