### ISSUE TITLE
<amplify-authenticator> Angular open in Sign Up instead of Sign In

### ISSUE THREAD

**Issue by holtc** [aws-amplify/amplify-js#2414]
** Which Category is your question related to? **
Amplify Authenticator component in Angular

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
Is there a way to specify which view the authenticator component opens first?  Currently it always opens on the Sign In part.  It would be great to be able to specify to open in either the Sign In or the Sign Up view.  Have I missed something and this is already possible?  If not, would it be possible add a boolean flag to allow this, similar to the new `signUpConfig` attribute?

**Comment by holtc** [comment]
I tried to create a PR but I do not have the permissions, so I have uploaded the diff files as .txt files.  I have tested locally and it works as desired.  The code also helps solve [2414](https://github.com/aws-amplify/amplify-js/issues/2414) and [2403](https://github.com/aws-amplify/amplify-js/issues/2403).

[authenticator.component.core.ts.txt](https://github.com/aws-amplify/amplify-js/files/2709655/authenticator.component.core.ts.txt)
[authenticator.factory.ts.txt](https://github.com/aws-amplify/amplify-js/files/2709656/authenticator.factory.ts.txt)

**Comment by sanket-tubbr** [comment]
How to hide Sign Up link in amplify-authenticator?
