### ISSUE TITLE
<amplify-authenticator> Sign Up with email link verification still asks for code in Angular

### ISSUE THREAD

**Issue by holtc** [aws-amplify/amplify-js#2415]
**Is your feature request related to a problem? Please describe.**
My application uses an email verification link rather than a code.  When a user creates an account, the `<amplify-authenticator>` flow still asks them to enter a code, rather than to check their email for a verification link, which is very confusing.

**Describe the solution you'd like**
Ideally, the `<amplify-authenticator>` flow would ask them to check their email for the verification link, rather than entering a code.  Perhaps this could be a field in the `signUpConfig` object?

**Describe alternatives you've considered**
The only alternative I can think of would be to create my own authentication UI.

**Additional context**

**Comment by holtc** [comment]
I tried to create a PR but I do not have the permissions, so I have uploaded the diff files as .txt files.  I have tested locally and it works as desired.  The code also helps solve [2414](https://github.com/aws-amplify/amplify-js/issues/2414) and [2403](https://github.com/aws-amplify/amplify-js/issues/2403).

[authenticator.component.core.ts.txt](https://github.com/aws-amplify/amplify-js/files/2709655/authenticator.component.core.ts.txt)
[authenticator.factory.ts.txt](https://github.com/aws-amplify/amplify-js/files/2709656/authenticator.factory.ts.txt)

**Comment by jordanranz** [comment]
The request for support of email verification link is included in the following RFC:
https://github.com/aws-amplify/amplify-cli/issues/766

**Comment by jordanranz** [comment]
Related to: https://github.com/aws-amplify/amplify-js/issues/539

**Comment by jordanranz** [comment]
Closed in favor of this: #2777
