### ISSUE TITLE
updateUserAttributes options

### ISSUE THREAD

**Issue by MatteoGioioso** [aws-amplify/amplify-js#2417]
When I want to update the user attributes I use `updateUserAttributes` from the Amplify library.
If I am updating the `email` I will receive a confirmation code. 

Is it possible or is there an option object to decide whether receive this confirmation code?
With the current implementation looks like I cannot pass any option.
If not could it be possible to have this feature?

Thanks

**Comment by MatteoGioioso** [comment]
up

**Comment by sammartinez** [comment]
@MatteoGioioso Please provide a snippet of your code so we can dive deeper into this. Thanks!

**Comment by MatteoGioioso** [comment]
@sammartinez Sorry, what code snippet? This is a question.

I will try to explain it better.
From you docs:
```
let result = await Auth.updateUserAttributes(user, {
    'email': 'me@anotherdomain.com',
    'family_name': 'Lastname'
});

If you change the email address, the user will receive a confirmation code. In your app, you can confirm the verification code...
```

Is it possible to not receive the verification code?
Implementation would be something like that

```
let result = await Auth.updateUserAttributes(user, {
    'email': 'me@anotherdomain.com',
    'family_name': 'Lastname'
}, {verificationCode: false});
```

Thanks

**Comment by MatteoGioioso** [comment]
up

**Comment by MatteoGioioso** [comment]
up

**Comment by ericclemmons** [comment]
Hi @MatteoGioioso,

> Is it possible or is there an option object to decide whether receive this confirmation code?
>  If not could it be possible to have this feature?

Could you help me understand why you would like to "not receive the verification code"?

From my perspective, it appears that the verification code is necessary for security reasons. (Changing a user's email _should_ require validation, since even a typo could lock them out)

**Comment by MatteoGioioso** [comment]
Our use case is to add an additional step for the user to send the email.
As my understanding the email is already changed after the `updateUserAttributes` has been called successfully.
