### ISSUE TITLE
Using a GraphQL API from both React and Lambda

### ISSUE THREAD

**Issue by LK** [aws-amplify/amplify-js#2418]
** Which Category is your question related to? **
GraphQL, React, Lambda

** What AWS Services are you utilizing? **
AppSync, S3, Cognito, Lambda, DynamoDB

** Provide additional details e.g. code snippets **
I'm setting up a project with Amplify using a GraphQL API, Cognito for authentication, and a React frontend. I need the data in GraphQL to be query-able (and subscribe-able) from React; however I also have some more complicated mutation logic that will go in lambda functions. I've run into a couple snags trying to figure out how to make this setup work:

1. I need my lambda functions to run with higher access privileges than what the frontend is allowed to access. From what I've gathered, this means I need to authenticate to the GraphQL API using IAM from the lambda functions and Cognito from the frontend — however when setting up the API with the Amplify CLI, I am forced to choose one or the other. How do I get around this?
2. In the documentation for the `@auth` GraphQL directive, it says this is only supported for Cognito authentication. If I wanted to have separate (looser) access restrictions for GraphQL interactions coming from my lambda function, how do I go about doing this?

I suppose one workaround would be to interact with DynamoDB directly from my lambda function instead of going through the GraphQL layer, but it seems to me like it would be cleaner to have all queries and mutations pass through GraphQL first. Is there any way to make this work?

**Comment by jkeys-ecg-nmsu** [comment]
Can you create an admin user and group in your user pool and authenticate in your lambda with those credentials? 

>I suppose one workaround would be to interact with DynamoDB directly from my lambda function instead of going through the GraphQL layer, but it seems to me like it would be cleaner to have all queries and mutations pass through GraphQL first.

That will not trigger subscriptions because they are not mutations.

**Comment by LK** [comment]
@jkeys-ecg-nmsu will try that — thanks for the suggestion.

Another reason why I would prefer to have the Lambda function go through the GraphQL layer to interact with the data.

**Comment by jkeys-ecg-nmsu** [comment]
@LK You're welcome. Here's roughly what you'll need, where `decrypted` is a global variable holding KMS-decrypted Lambda environment variables -- for anyone encountering this in the future:

```

**Comment by jkeys-ecg-nmsu** [comment]
@LK get it figured out?

**Comment by LK** [comment]
Yes, seems like it. Thanks again for your help!
