### ISSUE TITLE
InvalidSignatureException on AppSync calls with identity pools (react native)

### ISSUE THREAD

**Issue by mllrmat** [aws-amplify/amplify-js#2422]
**Describe the bug**
When I try to authenticate against appsync with the federated identities issues IAM tokens, I get a InvalidSignatureException on AppSync. 

Before calling appsync I retrieved FB tokens and made a successful call to Auth.federatedSignIn(), recieving back the credentials. 

Amplify config: 
```
Amplify.configure({
      Auth: {
        identityPoolId: AppSync.identityPoolId,
        region: AppSync.region,
        userPoolId: AppSync.userPoolId,
        userPoolWebClientId: AppSync.userPoolWebClientId 
      },
      API: {
        aws_appsync_graphqlEndpoint: AppSync.graphqlEndpoint,
        aws_appsync_region: AppSync.region,
        aws_appsync_authenticationType: AUTH_TYPE.AWS_IAM,
        aws_appsync_apiKey: 'null'
      }
    });
```
The client gets a "GraphQLError: Request failed with status code 403", in cloudwatch I can see a "Response Headers: {x-amzn-ErrorType=InvalidSignatureException}" error.

**Expected behavior**
Access to appsync resources. 

**Additional context**
I am using react native and testing with facebook login.

**Comment by powerful23** [comment]
@mllrmat can you provide some code snippets about how did you sign in and then call the appsync related functions? Also can you show your IAM roles to see if you have the right policies?

**Comment by laurachevalier4** [comment]
@powerful23 I am seeing this same problem for my React-Native app.

Configuring Auth component with `Auth.configure(awsconfig);`

`awsconfig` looks like:
```
const config = {
  Auth: {
    userPoolId: "us-east-1_...",
    identityPoolId: "us-east-1:...",
    region: "us-east-1",
    userPoolWebClientId: "..."
  },
  "aws_appsync_authenticationType": "AWS_IAM",
  ...
}
export default config;
```

Within AWS Management console, I have:
* A User Pool with two app clients created, without client secrets; the user pool ID is used in the `awsconfig` object and in the Identity Pool
* An Identity Pool, whose ID is used above in configs, with Cognito set as Identity Provider, using the UserPoolID and App Client ID from the user pool. `Authenticated Role Selection` is left as `Use default role`.
* Permissions to the IAM Auth role created for my Identity Pool. It has 2 policies attached:
1.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "dynamodb:GetItem",
                "dynamodb:PutItem",
                "dynamodb:Query",
                "dynamodb:BatchGetItem",
                "dynamodb:BatchWriteItem",
                "appsync:GraphQL"
            ],
            "Resource": [
                "arn:aws:dynamodb:us-east-1:myaccountid:table/myresource",
                "arn:aws:dynamodb:us-east-1:myaccountid:table/myresource/*",
                "arn:aws:appsync:us-east-1:myaccountid:apis/myapiid/*"
            ]
        }
    ]
}
```
2.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "mobileanalytics:PutEvents",
                "cognito-sync:*",
                "cognito-identity:*"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```

I am able to authenticate my user in my React Native app but get an error when I make a call to my API:
```
GraphQLError: Request failed with status code 403
```
and in CloudWatch I see the same thing as @mllrmat:
```
Response Headers: {x-amzn-ErrorType=InvalidSignatureException}
``` 

I followed a similar pattern with the same API backend in my React app, the main difference being that I used User Groups and attached an IAM Role there, then set the `Authenticated role selection` in the corresponding Identity Pool to `Choose role from token` --> `DENY`. Hopefully I'm missing something obvious but haven't been able to debug this. Any ideas? Happy to provide more info if needed.

**Comment by laurachevalier4** [comment]
*Update* also tried with user groups in the same way as my webapp and still facing the same error.

**Comment by powerful23** [comment]
@laurachevalier4 Hi
- First, can you check if the configuration is passed down to the module correctly? You can call `const auth_config = Auth.configure()` and `const api_config = API.configure()` to do that.
- Second, can you open the debug mode by putting `window.LOG_LEVEL='DEBUG'` in your code.and paste some debugging info here when calling the graphql operation? We want to see if the aws credentials is correctly attached to the request.
- Third, you can also check the `network` in the browser console to those request and response body back from the aws service.

**Comment by laxxers** [comment]
@powerful23 I'm facing the same issue for my React Native app. I have similar configurations like @laurachevalier4 's and @mllrmat 's. However, the issue happens at random only on Android release build.

Seeing similar in CloudWatch:
`Response Headers: {x-amzn-ErrorType=InvalidSignatureException}`

and also in app:
`GraphQLError: Request failed with status code 403`

@mllrmat @laurachevalier4 any luck solving this?

**Comment by laurachevalier4** [comment]
@laxxers I was able to work around this by changing my authentication type to `AMAZON_COGNITO_USER_POOLS`. Now my two APIs have auth mode set to `Amazon Cognito user Pool` and they both point to the same user pool with `Default Action = ALLOW`. Not sure if this is a valid option for you but it works for me.

**Comment by laxxers** [comment]
Thanks @laurachevalier4. But I do need AWS_IAM to work because I have authenticated and unauthenticated requests.

Thanks anyway 😁

**Comment by laurachevalier4** [comment]
Cognitive also allows unauthenticated access to your resources https://docs.aws.amazon.com/cognito/latest/developerguide/identity-pools.html#enable-or-disable-unauthenticated-identities. If that doesn't help.. good luck!

**Comment by laxxers** [comment]
Hey @laurachevalier4 just wanna let you know I got it working with

`Auth.currentCredentials();`

before calling any APIs.
