### ISSUE TITLE
S3Image does not support access to protected files of other users

### ISSUE THREAD

**Issue by ceich** [aws-amplify/amplify-js#2424]
**Describe the bug**
Storage.get supports passing the `identityId` option to access another user's protected files, but S3Image does not pass this option through. There is no way to access the protected files of multiple users without this.

**To Reproduce**
1. Try to pass `identityId` to access another user's protected image.
2. See incorrect URL (using own `identityId`) in Chrome Developer Tools Network tab.

**Expected behavior**
S3Image (and S3Album) should pass through the `identityId` prop, at least when `level === protected`.

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.14.2
 - Browser: Chrome
 - Version: 2.1.7 (aws-amplify-react)

**Comment by ceich** [comment]
@mwarger In my case, I have the identityId embedded in the key for the other user's protected image file; just another way to do what you did.

But the bug remains that S3Image does not pass through an `identityId` prop. I am inclined to add this and submit a PR. Comments?

**Comment by ceich** [comment]
Note that the PR adds `identityId` support to `S3Text` and `S3Album` as well, for consistency.

**Comment by elorzafe** [comment]
@ceich thanks for your PR, I answered in more detail on the PR but in order to merge it we need to add some instructions on our docs, so others can use it 🙂
