### ISSUE TITLE
AuthClass - The user is not authenticated by the error No userPool

### ISSUE THREAD

**Issue by dahof1** [aws-amplify/amplify-js#2425]
**Describe the bug**
I manually configured my amplify vue project like the official vue sample (aws-samples). Sign-In worked, but everytime i did a manual page refreshes i got an `AuthClass - The user is not authenticated by the error No userPool` Error in the logs.

Amplify/Amplify-Vue Version:
aws-amplify: 1.1.18,
aws-amplify-vue": 0.2.5

Vue Cli 3

It is also very irritating that the offical documentation in https://aws-amplify.github.io/docs/js/vue and the vue sample differ.

**To Reproduce**
Implemented my sample project like the official amplify-vue-sample:
- (Manuelly) configured amplify in the main.js
- Vue.use(AmplifyPlugin, AmplifyModules) in router.js
- Start dev-server, sign in -> Everthing works
- Manuell page refresh -> User object gets null and get `AuthClass - The user is not authenticated by the error No userPool`

After some debugging i found that AuthClass was always getting an empty config the first time of the page refresh. 

My **Workaround** so far: Moving the whole Amplify.configure part completly in the router.js

**Expected behavior**
Better documentation of how to configure amplify-vue properly. 

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Browser: chrome, firefox

**Comment by sammartinez** [comment]
@dahof1 Documentation for Vue has been updated since this feature request was cut. I am resolving this feature as the documentation has been improved on.
