### ISSUE TITLE
AmplifyMessageMap for aws-amplify-vue

### ISSUE THREAD

**Issue by meteorza** [aws-amplify/amplify-js#2426]
I would like to change the default amplify-vue Authenticator error messages using a custom AmplifyMessageMap prop (like AmplifyMessageMap.js for react-natice package). I am launching the authenticator through the vue router:

```
{
        path: '/auth',
        name: 'Authenticator',
        component: components.Authenticator,
        props: {
          errorMessage: CustomAmplifyMessageMap,
          authConfig: {
            signUpConfig: {
              header: 'I am the new header for the Authenticator component!',
              hiddenDefaults: ['phone_number']
            }
          }
        }
      }
```

In the example, I have added the new prop:

`errorMessage: CustomAmplifyMessageMap,`

Does not seem this prop exists for aws-amplify-vue Authenticator? If not, could it be added?

**Comment by ericclemmons** [comment]
`aws-amplify-vue` has been deprecated in favor of https://docs.amplify.aws/ui/q/framework/vue.

Customizing messages can be done via translations:
https://docs.amplify.aws/ui/customization/translations/q/framework/vue
