### ISSUE TITLE
 Analytics- Incorrect Demographical data

### ISSUE THREAD

**Issue by JemaaWassim** [aws-amplify/amplify-js#2427]
**Describe the bug**
Platform not reporting correct results for Android devices
Device model/Device make not reporting correct information for all platforms
No data for User location

**To Reproduce**
I followed this basic tutorial to create a JavaScript app[1] and i added analytics[2] the hosted the app[3]. The app works as expected. pushing events to pinpoint and all is perfect. You can see the attached screenshot. However in the demorapphical data I can see that the reported data for "Platform", "Device model" and "Device make" are incorrect and "User location" is missing. I have uploaded the screenshot to illustrate the issue. 

[1] https://aws-amplify.github.io/docs/js/start?platform=purejs
[2] https://aws-amplify.github.io/docs/js/analytics
[3] https://aws-amplify.github.io/docs/cli/hosting?sdk=js

**Expected behavior**
i expected this to be showing correct data 

**Screenshots**
![pinpoint analytics](https://user-images.githubusercontent.com/8850391/50520570-01fb8880-0ab9-11e9-889a-d39d4bcdc61d.png)

Bellow is an example of a event stream coming from a Samsung S9 

{"event_type":"AWS Amplify Tutorial Event","event_timestamp":1545939211659,"arrival_timestamp":1545939215220,"event_version":"3.1","application":{"app_id":"deleted for security reasons","cognito_identity_pool_id":"","sdk":{},"version_name":"Chrome/59.0.3071.125"},"client":{"client_id":"deleted for security reasons","cognito_id":""},"device":{"make":"Gecko","model":"Chrome","platform":{"name":"linux armv8l"}},"session":{"session_id":"deleted for security reasons","start_timestamp":1545939206176},"attributes":{},"endpoint":{"EndpointStatus":"ACTIVE","OptOut":"ALL","RequestId":"deleted for security reasons,"Location":{},"Demographic":{"Make":"Gecko","Model":"Chrome","ModelVersion":"deleted for security reasons","AppVersion":"Chrome/59.0.3071.125","Platform":"linux armv8l"},"EffectiveDate":"2018-12-27T19:33:35.210Z","Attributes":{},"Metrics":{},"User":{"UserId":"deleted for security reasons","UserAttributes":{}},"ApplicationId":"deleted for security reasons","Id":"deleted for security reasons4","CohortId":"51","CreationDate":"2018-12-27T18:44:24.498Z"},"awsAccountId":"deleted for security reasons"}

Below is an event stream comming from an Iphone s5.
{"event_type":"AWS Amplify Tutorial Event","event_timestamp":1545939640358,"arrival_timestamp":1545939643079,"event_version":"3.1","application":{"app_id":"deleted for security reasons","cognito_identity_pool_id":"","sdk":{},"version_name":"Safari/602.1"},"client":{"client_id":"deleted for security reasons","cognito_id":""},"device":{"make":"Gecko","model":"Safari","platform":{"name":"iphone"}},"session":{"session_id":"46ba4330-0a0f-11e9-a991-35e3bbe342cb","start_timestamp":1545939633891},"attributes":{},"endpoint":{"EndpointStatus":"ACTIVE","OptOut":"ALL","RequestId":"0c94874c-0a07-11e9-94e3-33c760dd8983","Location":{},"Demographic":{"Make":"Gecko","Model":"Safari","ModelVersion":"602.1","AppVersion":"Safari/602.1","Platform":"iphone"},"EffectiveDate":"2018-12-27T19:40:43.071Z","Attributes":{},"Metrics":{},"User":{"UserId":"deleted for security reasons","UserAttributes":{}},"ApplicationId":"deleted for security reasons","Id":"deleted for security reasons","CohortId":"96","CreationDate":"2018-12-27T18:41:39.176Z"},"awsAccountId":"deleted for security reasons"}

**Comment by powerful23** [comment]
@JemaaWassim are you making a web app or a react native app?

**Comment by JemaaWassim** [comment]
@powerful23 the above test was made using a web app.

**Comment by powerful23** [comment]
@JemaaWassim we will look into that. In the meantime, you can define the default demographic info yourself: https://aws-amplify.github.io/docs/js/analytics#manual-setup if you've already got your own way to get the correct device info.

**Comment by JemaaWassim** [comment]
@powerful23 Any update on this ?
