### ISSUE TITLE
How to do an API call for blob data

### ISSUE THREAD

**Issue by epicfaace** [aws-amplify/amplify-js#2433]
I need to get blob data, not JSON data, from my REST API. Essentially, I'm looking for  the equivalent of using fetch and https://developer.mozilla.org/en-US/docs/Web/API/Body/blob. How can I do this with Amplify?

**Comment by jordanranz** [comment]
Hey @epicfaace,

Are you using Amazon API Gateway to manage your REST API?

**Comment by elorzafe** [comment]
@epicfaace you can change the headers of the request like this

```javascript
const data = await API.get('myApi','/myPath/to/my/data', {
      headers: {
        'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'
      }
    });
```

**Comment by epicfaace** [comment]
@jordanranz No, I am not.
@elorzafe , that doesn't work. What I need is the ability to set responseType (https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType) to "blob", which would mean passing in `{responseType: blob}` when calling `axios`.

Essentially, I am working around this issue by using `fetch` for now like this:
`fetch(url).then(e => e.blob());`

Because it seems that AWS Amplify assumes that the data type is json by default.

**Comment by elorzafe** [comment]
I will mark this as feature-request. @epicfaace thanks for your feedback

**Comment by KevinToala** [comment]
I have the same problem.
Is there any tentative date by when this feature?

**Comment by epicfaace** [comment]
> I have the same problem when use AWS Amplify API. I need passing responseType: 'blob'
> Is there any tentative date by when this feature?

@elorzafe
