### ISSUE TITLE
API Network Errors

### ISSUE THREAD

**Issue by jayair** [aws-amplify/amplify-js#2435]
**Description**

I have an Amplify React app and every so often I notice **Network Errors** in our Sentry logs while making API requests (while everything has been working fine till that point). The HTTP Status code is `0`. And the CloudWatch logs for API Gateway show that there was a request but the Lambda logs don't show anything. I'm unable to see the response of these requests both through the browser and in CloudWatch. Once the error occurs all other API requests also fail until the page is refreshed.

The APIs are using IAM and federated identities with Cognito User Pool. I think this error happens when the credentials are out of date.

Is there a way in Amplify to detect that the credentials are out of date and need to be refreshed?

-----

**Which Category is your question related to?**

API requests.

**What AWS Services are you utilizing?**

- API Gateway
- AWS Lambda
- Cognito User Pool
- Cognito Federated Identities

**Provide additional details e.g. code snippets**

<img width="459" alt="screen shot 2018-12-31 at 4 41 09 pm" src="https://user-images.githubusercontent.com/53023/50568074-ef808980-0d1a-11e9-8de0-35cad50ae733.png">

**Comment by jayair** [comment]
I've made some progress. I managed to log the API Gateway error in CloudWatch:

```
"status":"403",
"protocol":"HTTP/1.1", 
"responseLength":"2033", 
"errorMessage":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
```

The requests made right before these seem to be working. But some requests just fail every once in a while.

Is this in some way related to the credentials not being refreshed properly on the client?

**Comment by elorzafe** [comment]
@jayair yes, Amplify refreshes the credentials when they expire. Do you have some code snippet?

**Comment by jayair** [comment]
@elorzafe Thanks for the reply. The login flow can be a bit tricky to put up here. But is there something I can log before an API call is made to see if the credentials are being set properly?

**Comment by elorzafe** [comment]
@jayair you can enable DEBUG logs like this

```Amplify.Logger.LOG_LEVEL = 'DEBUG'```

**Comment by jayair** [comment]
@elorzafe Is there someway to listen on these log events? I need to log them to Sentry.
