### ISSUE TITLE
What are the potential causes of `error dispatching ${event} event to ${listener}` for Hub?

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-js#2438]
** Which Category is your question related to? **
Hub - I just want to know what might cause this warning for debugging purposes. The problem is so intermittent that it's hard to debug.

** What AWS Services are you utilizing? **
Amplify.

** Provide additional details e.g. code snippets **
`Hub - error dispatching UIReset event to noname`

**Comment by jordanranz** [comment]
I see this warning here:
https://github.com/aws-amplify/amplify-js/blob/1ee161db4d46136379c5a79ca5ab5de2cee2b817/packages/core/src/Hub.ts#L82

This method seems to be called on dispatch. If you name the listener you are using when calling .listen you can pass a listener name as a third parameter:
https://github.com/aws-amplify/amplify-js/blob/1ee161db4d46136379c5a79ca5ab5de2cee2b817/packages/core/src/Hub.ts#L46

With that set we can see which listener is failing on the onHubCapsule call.

**Comment by jkeys-ecg-nmsu** [comment]
Thanks @jordanranz. How difficult would it be to fork just Hub.ts so that I can add some more logging and add error handling?
