### ISSUE TITLE
Auth.federatedSignin failing with error "No userPool"

### ISSUE THREAD

**Issue by mikepugh** [aws-amplify/amplify-js#2445]
**Describe the bug**
I'm using federated authentication with Azure AD. I recently upgraded my aws-amplify and aws-amplify-react libraries to the latest versions and now authentication is failing with the error `The user is not authenticated by the error No userPool`. 

Based on the following debug messages you can see that the library successfully gets temporary IAM access credentials from Cognito, but then fails to pass those back to me.

```
[DEBUG] 05:56.933 Credentials - Load credentials successfully CognitoIdentityCredentials { accessKeyId: "*****", authenticated: true, cognito: features.constructor { **** }, ... } ConsoleLogger.js:97 
[INFO] 05:56.935 Cache - Set item: key is federatedInfo, value is [object Object] with options: [object Object]
[DEBUG] 05:56.937 AuthClass - getting current authenticted user ConsoleLogger.js:97 
[DEBUG] 05:56.937 AuthClass - cannot load federated user from auth storage ConsoleLogger.js:97 
[DEBUG] 05:56.937 AuthClass - get current authenticated userpool user ConsoleLogger.js:107 
[DEBUG] 05:56.938 AuthClass - The user is not authenticated by the error No userPool
```

This appears to be related to #2320 where the `federatedSignIn` code was re-factored, in particular, adding a call to `const currentUser = await this.currentAuthenticatedUser();` [on this line](https://github.com/aws-amplify/amplify-js/blame/a8dcf86465023954114a155e45c2323ba51e180b/packages/auth/src/Auth.ts#L1341)

Eventually `currentAuthenticatedUser` calls into `currentAuthenticatedUser` which checks if `this.userPool` is set, and if not it rejects with `No userPool`. 

For federated authentication, we're not using cognito user pools - only a cognito identity pool.

**To Reproduce**
1. Setup the amplify library for federated authentication without any cognito user pools
2. Make a call to `federatedSignIn` after obtaining the token from federated auth service (in our case Azure AD)
3. Amplify fails with `No userPool` error

**Expected behavior**
`federatedSignIn` method should succeed and return credentials to calling code.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 71.0.3578.98

**Additional context**
N/A

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by mikepugh** [comment]
The underlying error appears to be related to how the Credentials are cached. I had `Auth.cookieStorage` configured in my Amplify config and for some reason the code was unable to properly store the federated user info in there, so the code was failing. 

I've removed the `cookieStorage` config from my app and now it's working again.

**Comment by thedanielforum** [comment]
This is probably not the cause of your problem but it worked for me so I am just gonna put it out there.
If the account you are logging in with was created in the cognito AWS console and not by using the aws-amplify package the login will softly fail just printing to console "No user" and it will not write any data to local storage.
If you create the user with the aws-amplify package this error goes away.
Anyway hope this helps someone~

**Comment by carolina-cascade** [comment]
@thedanielforum Can you elaborate more? I did create my account from the AWS console (I am following the tutorial in https://serverless-stack.com).
