### ISSUE TITLE
AR support for sumerian scenes

### ISSUE THREAD

**Issue by Todmy** [aws-amplify/amplify-js#2454]
** Which Category is your question related to? **
XR

** What AWS Services are you utilizing? **
Sumerian

** Provide additional details e.g. code snippets **
I spent a ton of time for understanding how to make work AR sumerian scene. It was not hard to deploy scene to the web, but camera was not requested so it looks like just 3d scene. Could you please help with this issue or point me where I can find an answer or working examples?

P.S.: I make it with Vue.

**Comment by jordanranz** [comment]
Hi @Todmy,

Publishing an AR scene to a web page is currently not officially supported. 

It is required that you publish a scene publicly and utilize native functionality (ARKit or ARCore) to build an AR scene. Here are some related resources:
- https://docs.sumerian.amazonaws.com/tutorials/create/intermediate/augmented-reality-using-sumerian-arkit/
- https://docs.sumerian.amazonaws.com/tutorials/create/intermediate/augmented-reality-using-sumerian-arcore/

There is also a possible work around I have heard of where you can use ARjs to anchor a Sumerian scene but this has not been officially tested. 

As the WebXR spec continues to be refined and implemented into browsers, we will update support for the functionality you are asking for. I will mark this as a feature request and update this issues as soon as there has been some progress made on it.

**Comment by Todmy** [comment]
@jordanranz thank you a lot

**Comment by jordanranz** [comment]
This may also be something you can do using the 8th Wall SDK:
https://8thwall.com/products-web.html

https://mobile-ar.reality.news/news/amazon-sumerian-8th-wall-weave-web-ar-experience-for-spider-man-into-spider-verse-movie-0190488/

We are working to find a way to best integrate with these solutions to allow users to simplify building AR web apps.

Thanks for your interest @Todmy.

**Comment by jordanranz** [comment]
Here is the 8th Wall integration documentation:
https://github.com/8thwall/web/tree/master/gettingstarted/xrsumerian

**Comment by Outer-net** [comment]
Is it possible to embed very simple 3D assets of art/paintings in AR onto a site using AWS Without 8th Wall ? 
All the best
