### ISSUE TITLE
I18n React Native in static navigationOptions

### ISSUE THREAD

**Issue by rogueturnip** [aws-amplify/amplify-js#2457]
Hi,

I'm trying to localize my app which uses react-navigation v2.  In the component for the tab I've got the title set using static navigationOptions where I wrap the text with the I18n.get however I only get back the label and not the translated text.

I also noticed that this happens with const that are defined globally.

Is there something I need to do beyond what the documentation indicates?  The library works fine when done within the render.

Thanks!

**Comment by apertureless** [comment]
A temporary workaound would be to pass it as a function and wrap inside a `Text` element.

```js
tabBarLabel: (<Text style={{color: 'white'}}>{I18n.get('Home')}</Text>),
```
