### ISSUE TITLE
Require New Password in Authenticator doesn't allow user to enter required attributes

### ISSUE THREAD

**Issue by scottjbaldwin** [aws-amplify/amplify-js#2461]
**Is your feature request related to a problem? Please describe.**
If I create a user in the UserPool as an Admin, you can use the Angular `amplify-authenticator` to Sign the user in. This helpfully handles the "require new password" flow, but doesn't allow you to enter any required attributes. For example if I specified 'given_name' as a required attribute, when I attempt to change my password, I will receive an error stating **Invalid attributes given, given_name is missing**, but there is no way to enter it.

**Describe the solution you'd like**
A solution similar to the `signUpConfig` in [signUpComponent](https://github.com/aws-amplify/amplify-js/tree/master/packages/aws-amplify-angular/src/components/authenticator/sign-up-component) would work, i.e. a `requireNewPasswordConfig` attribute with required fields, although it does seem a little manual. Ideally something automated like described in #1871 would be great.

**Describe alternatives you've considered**

The only alternative I can see is to not use the `amplify-authenticator` and implement the auth flow myself.

**Additional context**

Angular 6

**Comment by lclghst** [comment]
Any way to get around this? 
Currently cannot log in using an admin created user

**Comment by jordanranz** [comment]
Seems in our Angular authenticator component it does iterate through the required attributes for this use case. I can work on getting this fixed.

**Comment by jordanranz** [comment]
This will be part of the UI component refactor attached as a milestone.

**Comment by altabayoyon** [comment]
jordanranz if haven't already stashed a fix for this issue and are interested, I have fixes for this issue on my fork's "Angular5_issue-2461" branch and can initiate a pull request.
The 5 files I modified are in the aws-amplify-angular package:
    src/components/authenticator/
        autnenticator/
            authenticator.component.core.ts
            authenticator.component.ionic.ts
        require-new-password-comonent/
            require-new-password.component.core.ts
            require-new-password.component.ionic.ts
    __test__/components/authenticator/
        require-new-password.component.core.spec.ts
Let me know if you'd like me to initiate a pull request.

**Comment by jordanranz** [comment]
This is now supported in the new UI component library: https://docs.amplify.aws/ui/auth/authenticator/q/framework/angular

per: https://github.com/aws-amplify/amplify-js/pull/5765. required attribute form inputs for `amplify-require-new-password` are automatically populated now.

Please feel free to open a new issue if you are running into any related problems.
