### ISSUE TITLE
Authenticator HOC - ForgotPassword.js: Use theme instead of style for "Send" button

### ISSUE THREAD

**Issue by TLaue** [aws-amplify/amplify-js#2465]
**Describe the bug**
It is not possible to apply a custom style to the button text on the ForgotPassword page as the theme is not given as prop for the "Send" button but just the style directly:

`React.createElement(AmplifyButton, {`
`text: I18n.get('Send').toUpperCase(),`
`style: theme.button,`
`onPress: this.send,`
`disabled: !this.state.username`
`})`

In contrast the following code on the SignIn.js page is working correctly as the complete theme is given as prop:

`React.createElement(AmplifyButton, {`
`                        text: I18n.get('Sign In').toUpperCase(),`
`                        theme: theme,`
`                        onPress: this.signIn,`
`                        disabled: !this.state.username || !this.state.password`
`                    })`

**Expected behavior**
It should be possible to apply a custom style to the "Send" button as well.

**Additional context**
Version 1.1.18 of aws-amplify-react-native

**Comment by jordanranz** [comment]
I have submitted a PR to fix this. Thank you for catching this.

**Comment by jordanranz** [comment]
Closing this as the PR should fix the issue. Please reopen if you are still experiencing any related problems.
