### ISSUE TITLE
Expose profile picture for federated authentication providers

### ISSUE THREAD

**Issue by christophgysin** [aws-amplify/amplify-js#2466]
**Is your feature request related to a problem? Please describe.**
Using withAuthenticator with federated authentication, only name and email are exposed.

**Describe the solution you'd like**
Additionally, the profile picture url should also be exposed.

**Describe alternatives you've considered**
It's possible to fetch the image url manually after the user has logged in.

**Additional context**
Should be supported for
- [x] Google (#2467)
- [ ] Facebook (#4206)
- [x] Auth0 (#4329)

**Comment by jordanranz** [comment]
This is a valid ask. Thanks for the PR. Would you like to PR for Facebook and Auth0 as well?

**Comment by christophgysin** [comment]
Yes, I have commits for Facebook and Auth0, as well as exposing the email for the Amazon provider. These are not fully tested yet and lack tests. Will try to create PRs for those too.

**Comment by evertson90** [comment]
Will this no longer be supported?

**Comment by ericclemmons** [comment]
Finally closed via https://github.com/aws-amplify/amplify-js/pull/4206.  Thanks everone!
