### ISSUE TITLE
Amplify with Angular - Cannot update attributes of user connected with the Cognito Hosted UI

### ISSUE THREAD

**Issue by JohanRin** [aws-amplify/amplify-js#2468]
**Describe the bug**
Cannot update attributes of user connected with the Cognito Hosted UI

**To Reproduce**
1. Sign in with the Cognito Hosted UI (for instance Google)
2. Go to the User profile
3. Type new _given_name_ and _family_name_
4. Click on 'Confirm' button
5. User attributes are now updated
6. Check on Cognito if user attributes are updated => OK
7. Sign out the user
8. Sign in with the same user in Cognito Hosted UI
9. Go to the User profile
10. The user attributes are completed with the previous values (before the update)
11. Check on Cognito the user attributes => user attributes with old values

**Expected behavior**
The user attributes are updated and persisted in Cognito.

**Desktop (please complete the following information):**
 - OS: macOS Mojave v 10.14.2
 - Browser: Chrome Version 71.0.3578.98 (Build officiel) (64 bits)

**Additional context**
Excerpt of my code to update user attributes

```
private updateCognitoUserAttributes(userForm: FormGroup): Observable<string> {
    return this.authService.currentAuthenticatedUser().pipe(
        switchMap((user: any) => this.authService.updateUserAttributes(user, {
            family_name: userForm.value.familyName ? userForm.value.familyName : '',
            given_name: userForm.value.givenName ? userForm.value.givenName : '',
            email: userForm.value.email,
            phone_number: userForm.value.phoneNumber ? userForm.value.phoneNumber : ''
        }))
    )
}
```

**Comment by elorzafe** [comment]
@JohanRin where are you getting that `authService` from?

**Comment by JohanRin** [comment]
@elorzafe `authService` is a service I wrote to encapsulate Amplify Auth module. Basically, I convert promise in observable like this:
```
currentAuthenticatedUser(): Observable<any> {
    return from(Auth.currentAuthenticatedUser());
} 
```

**Comment by JohanRin** [comment]
Issue solved with the last versions of Amplify.
