### ISSUE TITLE
Pinpoint console doesn't display Amplify session events

### ISSUE THREAD

**Issue by Hugodby** [aws-amplify/amplify-js#2469]
**Describe the bug**
Pinpoint session tracker event names are incorrect. This lead to session events not being correctly displayed in the Pinpoint console. Session events appear on the  "Analytics"->"Events" page but not on "Analytics"->"Usage" page.

**To Reproduce**
1. Configure Pinpoint on an Amplify project
2. Open the application so session events are sent to Pinpoint
3. Check a couple minute later on Pinpoint console

**Expected behavior**
Amplify is sending events with an `_` instead of `.`:
* `_session_start` -> `_session.start`
* `_session_stop` -> `_session.stop`

cf Android SDK (https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-pinpoint/src/main/java/com/amazonaws/mobileconnectors/pinpoint/analytics/SessionClient.java)

*I will be happy to propose a PR to fix this issue if no one is working on it right now.*

**Comment by powerful23** [comment]
@Hugodby thanks for reporting this issue. I have sent a pr to fix it.
