### ISSUE TITLE
Customize AWS Amplify Authentication UI for Vue

### ISSUE THREAD

**Issue by cliffordh** [aws-amplify/amplify-js#2470]
**Is your feature request related to a problem? Please describe.**
I would like to customize the look and feel (CSS) of the Authentication components for Vue. This is either not documented or it is not clear how to accomplish this.

**Describe the solution you'd like**
I would like to be able to override the default styles with minimal effort!

**Describe alternatives you've considered**
I have considered implementing my own auth components directly but this seems to eliminate one of the primary benefits of the Amplify platform, which is to be an 'out of the box' jumpstart for app development on the AWS platform. I note that UI customization is possible for React.

**Comment by jordanranz** [comment]
Hey @cliffordh,

I have just responded to a similar issue and will close this so we can consolidate this into a single tracked issue: #2471
