### ISSUE TITLE
[Vue] How to safely override Amplify built-in components via CSS?

### ISSUE THREAD

**Issue by heitorlessa** [aws-amplify/amplify-js#2471]
** Which Category is your question related to? ** Amplify UI

** What AWS Services are you utilizing? ** Cognito

** Provide additional details e.g. code snippets **

Different from React I can't pass a theme object to override drop-in components from Amplify for example - ``<amplify-authenticator>``

After some digging I notice it creates a random class at build time `.Form__formSection___3tqxz`. While I can easily override the typography and color I'm quite sure this will break in upcoming updates. 

Is there a safe way to do that or are you working on providing friendly classes one can go and override regardless of what framework (Angular/Vue/React) is using it?

Thanks a lot!

**Comment by jordanranz** [comment]
Hey @heitorlessa,

At the moment overriding the styling of the Vue components is not explicitly supported. It is a high priority item on our backlog to unify the theming/customizability for each of our supported frameworks by allowing a user to pass in custom classnames to granular elements of the components we provide. 

I am going to mark this as a feature request for now but will update as soon we begin to make progress here. At the moment we are applying the solution to our Angular components. Following this we will begin work on the Vue components.

I would also recommend **not** trying to apply styles to the randomly generated PostCSS class name as it can change.

**Comment by cliffordh** [comment]
@heitorlessa @jordanranz 

I created #2470 shortly before you posted this very similar question. I poked around a bit and found a workaround that should at least let you theme the components:

In your App.vue <style> section insert this code and define the colors how you see fit. I changed the built-in Amazon orange to a dark green as an example:

```
:root {

  /* Colors */
  --amazonOrange: #009900; /* Redefined to dark green */
  --lightAmazonOrange: #FFAC31;
  --darkAmazonOrange: #E88B01;
  --squidInk: #232F3E;
  --lightSquidInk: #31465F;
  --deepSquidInk: #152939;
  --grey: #828282;
  --lightGrey: #C4C4C4;
  --silver: #E1E4EA;
  --darkBlue: #31465F;
  --red: #DD3F5B;
  --white: #FFFFFF;
  --light-blue: #00a1c9;
  }
```

What you're doing is overriding the CSS variables which control the theme used by Amplify. Check out https://github.com/aws-amplify/amplify-js/blob/master/packages/amplify-ui/src/Theme.css for more overridable CSS.

I would consider this a hack but it will work for my needs for now... this may not be forwards compatible if the variable names change in Theme.css. I don't think this issue should be closed but hopefully this workaround will help someone out there in the meantime.

**Comment by israelroldan** [comment]
Besides using the CSS variables @cliffordh pointed out, you may also come across a moment where you need to remove paddings or change dimensions. 

I achieved this by passing an additional class in the route to the authenticator:
in `router.js`:
```
const router = new Router({
  routes: [
    //...
    {
      path: '/auth',
      name: 'Authenticator',
      component: components.Authenticator,
      props: {
        class: "authenticator" // arbitrary class name
      }
    }
    //...
  ]
});

```
Then on my `App.vue` sytle:
```
.authenticator > div {
    padding: 0;
    min-width: 100%;
    box-shadown: none;
    -webkit-box-shadow: none;
}
```
I hope this helps someone! :)

**Comment by etnlbck** [comment]
I ran into an issue with responsiveness with vuetify cards. Here's the override to get the authenticator to fit properly.

```[class^="Form__formSection"] {
    min-width: 100% !important;
  }```

**Comment by jdchmiel** [comment]
I learned the hard way for this issue that if you add "scoped" to your style block, the styles do not apply to child components, like the authenticator.

**Comment by jordanranz** [comment]
FYI, we have started an RFC discussion for a proposed Amplify UI Component refactor to increase customizability and flexibility for our components. Please feel free to add any additional comments to the following issue:

https://github.com/aws-amplify/amplify-js/issues/3279

**Comment by sciarrilli** [comment]
+1 amplify-authenticator css responsiveness resizing for mobile

**Comment by Erlix322** [comment]
+1

**Comment by ashika01** [comment]
Closing this feature request as we have introduced theming with CSS Vars in the [new UI components](https://docs.amplify.aws/ui/customization/theming/q/framework/react). For any improvements and suggestions around UI components styling, please open up new feature request.

**Comment by farshi** [comment]
using pattern match selectors in css you can find the class attribute which is started with `Button__button`  and change the `background-color` attribute:

in your template style section add the code  below:
```
<style lang="sass">
  // changing aws login form button
  button[class^="Button__button"]
    background-color: #30bf71 //Green color
</style>
```

**Comment by heitorlessa** [comment]
Updating here for anyone who might come later now that Web components have replaced the older authenticator.

Here's what I'm currently using to customize the layout:

```sass
@import '../css/app'

amplify-authenticator
    display: flex
    justify-content: center
    align-items: center
    height: 100vh
    font-family: 'Raleway', 'Open Sans', sans-serif
    min-width: 80vw
    padding: 10vmin

    @media only screen and (min-device-width: 700px)
        margin: auto
        padding: 15vmin
        min-width: 100%

    --amplify-font-family: $typography-font-family
    --amplify-primary-color: #FA3336
```
