### ISSUE TITLE
Advanced Control Cognito User Access to S3

### ISSUE THREAD

**Issue by davidbillamboz** [aws-amplify/amplify-js#2476]
**Which Category is your question related to?**
Auth, Storage

**What AWS Services are you utilizing?**
AppSync, Cognito, S3, Dynamodb, IAM

**Provide additional details e.g. code snippets**
Hello!

I am trying to design a solution to:
- let users upload objects to S3 for their projects at /projects/{project_UUID}/{object_UUID}
- some users have access to the projects and should have access to the objects
- have the ability to track who GET/PUT what 

I tried:
- IAM roles 
With a role per user or per project. I don't think this is a viable solution.
- Bucket Policy 
You can't use the Cognito Identity here.
- IAM policy attached to a role 
The solution used by Amplify. I don't understand how to share an object between users.
- S3 Signed Urls 
It is not compliant with my security policy but it is working.

The only solution I found for the moment:
- an IAM policy attached to the role let user upload to their directory 
- an user uploads to S3 at /user_id/{project_UUID}/{object_UUID}
- an S3 event trigger a lambda and move the object to /projects/{project_UUID}/{object_UUID}
- a CloudFront with a Lambda@Edge controls the access with the Cognito JWT in front of S3

Did I missed something?
Thank you!

**Comment by rfdc** [comment]
I've setup my User File Storage via awsmobile instead, have a look:
https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-cli-reference.html
