### ISSUE TITLE
How to persist login across page refresh

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-js#2480]
I want to be able to keep users logged in on page refresh (which I believe was the default behavior of Amplify a couple of months ago). I am using the withAuthenticator HOC with a customized LogIn component.

@jordanranz Is there a config issue at play here preventing page reloads from persisting credentials?

** Which Category is your question related to? **
Auth, React HOC

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **

**Comment by jordanranz** [comment]
We solved this by moving the Amplify.configure routine before loading other Amplify resources. Closing this now. Please reopen if you run into any similar issues.

**Comment by leokishan** [comment]
I have Auth.configure in App.js file.

Login from root path and after login i am redirecting to another page but i cannot get Auth.user in another page.
