### ISSUE TITLE
Cannot read property 'ConsoleLogger'/prototype of undefined with parcel tree shaking

### ISSUE THREAD

**Issue by ApolloGun** [aws-amplify/amplify-js#2485]
**Describe the bug**
My react app crashes when I enable experimental-scope-hoisting using parcel. I had been using the full library but reduced it to: 
    "@aws-amplify/auth": "^1.2.14",
    "@aws-amplify/core": "^1.0.22-unstable.1",

When core is set to 1.0.9 the error is consolelogger of undefined otherwise it's prototype of undefined.

Here is where the error is occurring in the source:
 cs.util.update(cs.STS.prototype, {
        credentialsFrom: function(e, t) {
            return e ? (t || (t = new cs.TemporaryCredentials),
            t.expired = !1,
            t.accessKeyId = e.Credentials.AccessKeyId,
            t.secretAccessKey = e.Credentials.SecretAccessKey,
            t.sessionToken = e.Credentials.SessionToken,
            t.expireTime = e.Credentials.Expiration,
            t) : null
        },

**To Reproduce**
Use with parcel bundler and tree-shaking.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by powerful23** [comment]
@ApolloGun can you provide more details? I tried with the same amplify versions on a react app and run command `parcel build src/index.js --experimental-scope-hoisting`, so far no error showed up.

**Comment by ApolloGun** [comment]
Okay, in that case I'm going to close the issue, since it does not seem to be connected to amplify and I'm getting similar issues  with other modules.
