### ISSUE TITLE
signUpConfig Username required when hideAllDefaults = true

### ISSUE THREAD

**Issue by robotlemons** [aws-amplify/amplify-js#2486]
**Describe the bug**
With hideAllDefaults set to true, would expect "Username cannot be empty" error to not occur.

**To Reproduce**
Setup signUpConfig to include whatever fields but hideAllDefaults set to true. Username is not a field in the form now but when form is filled out completely, "Username cannot be empty" error is shown.

**Expected behavior**
If Username is required by Cognito but not required on the form, why doesn't it follow the standard of generating a UUID as that's what happens on the back-end?

**Screenshots**
<img width="877" alt="screen shot 2019-01-07 at 11 57 32 am" src="https://user-images.githubusercontent.com/45703810/50784515-7978a700-1273-11e9-8d75-61826a63d606.png">

**Desktop (please complete the following information):**
 - OS:  OSX Mojave
 - Browser: Chrome
 - Version: 71.0.3578.98

**Comment by powerful23** [comment]
@robotlemons if you don't have a username field, then which field would you like to be the username? `email`?

**Comment by robotlemons** [comment]
@powerful23 i use email to have my users login and username is filled in with UUID by Cognito when a new user is created in the Pool. 

<img width="1049" alt="screen shot 2019-01-07 at 3 45 11 pm" src="https://user-images.githubusercontent.com/45703810/50795268-46461000-1293-11e9-9729-37b9ba2a1f3a.png">

**Comment by powerful23** [comment]
@robotlemons I'm going to close this as it's related to #104. We are working on this feature but I cannot provide an ETA here.
