### ISSUE TITLE
Vue example for aws-amplify + aws-appsync

### ISSUE THREAD

**Issue by lobosan** [aws-amplify/amplify-js#2496]
Hi, I just started having a look at the docs and I'm confused about the use of aws-amplify and aws-appsync in a vue project.

For instance, in the documentation says "The Amplify GraphQL is a lighter weight option if you’re looking for a simple way to leverage GraphQL features and do not need the offline capabilities or caching of the Apollo client. If you need those features, choose the AWS AppSync SDK."

Since my project requires offline and caching I assume I have to use aws-appsync and not aws-amplify but the only good example I found to start learning is this one https://github.com/aws-samples/aws-amplify-vue but it uses aws-amplify

So what do I need to change in the code example in order to add offline and cache capabilities?

**Comment by undefobj** [comment]
For using the AppSync SDK with Vue Apollo please see the documentation here: https://github.com/awslabs/aws-mobile-appsync-sdk-js#vue

If you have any issues with running that sample code it's best to use the issue tracker on that repo.

**Comment by lobosan** [comment]
Hi @undefobj thanks for your quick response.

If I use the configuration proposed by the link you sent me, it means I loose all the functionality provided by aws-amplify? or is it possible to use both simultaniusly without interfering one with the other?

**Comment by undefobj** [comment]
You can still use Amplify for things like `Auth` but I would recommend not using the GraphQL capabilities from the `API` category if you are using the AppSync Apollo SDK.

For example here is how you use the `Auth` category with Cognito User Pools configured with AppSync: https://aws-amplify.github.io/docs/js/api#cognito-user-pools-auth

**Comment by CrashyBang** [comment]
If I was building an app that required offline support (so I would want to use the appsync-sdk) but I also wanted to take advantage of Amplifies storage module, could I do both, or at that point would I need to pick between amplify and appsync?

**Comment by mfreeman451** [comment]
@CrashyBang I'm using the AppSync SDK for my AppSync needs (instead of Amplify), and Amplify for Auth and Storage and everything else. You can definitely mix and match and the documentation that I've read sort of seems to indicate that as well. For instance, the Amplify docs say if you need offline access, you should use the AppSync JS SDK.
