### ISSUE TITLE
Amplify Auth calls sync function of MyStorage twice

### ISSUE THREAD

**Issue by anis-shaikh** [aws-amplify/amplify-js#2505]
Describe the bug
I am trying to configure custom storage for storing the cognito tokens with Amplify Auth MyStorage.
https://aws-amplify.github.io/docs/js/authentication#managing-security-tokens

To Reproduce
Configure the MyStorage object as mentioned in the link and override the sync method and log something in console and return some mock promise as per the contract.

Expected behavior
On loading the application sync method should be invoked once.

Actual behavior
Console log is getting print twice.
(Actually I am calling the API to get appropriate tokens and store it to my custom storage however because of this my API server is getting two calls on page load)

Screenshots
![image](https://user-images.githubusercontent.com/34154259/50892866-8806c000-1425-11e9-89e2-9722eb11ef01.png)

**Comment by powerful23** [comment]
@anis-shaikh I'm going to close this issue as it is duplicated to the one in the docs repo.
