### ISSUE TITLE
How to have GraphQL and REST apis in same project using the same tables

### ISSUE THREAD

**Issue by JulioBarros** [aws-amplify/amplify-js#2513]
** Which Category is your question related to? **
GraphQL and REST API

** What AWS Services are you utilizing? **
Amplify, react, typescript, auth, graphql api, rest api

** Provide additional details e.g. code snippets **
I'd like my main api to be GQL but also need a simple web hook rest api for a smaller part of my app.  Is there an example/tutorial that shows how to use both a GraphQL and REST api in the same project?

To start with I'd like to use the same dynamo tables in the REST api that were set up in the GQL api. How do I get the table names automatically/programmatically? How do I give my lambda function the correct permissions to read one and write another? What else do I need to do?

I tried creating storage first but the GQL api does not seem to use that. I can get the table names from the console but eventually want to use different environments and would like the names set (in a config or environment var) automatically depending on env.

I'm an experienced dev but new to all this, Is there a better way to get more training/help?

Thanks.

Julio

**Comment by aaronhayes** [comment]
Any answers to this one?

**Comment by undefobj** [comment]
@JulioBarros @aaronhayes would this feature request address your needs: https://github.com/aws-amplify/amplify-cli/issues/689

**Comment by grudra7714** [comment]
Any timeline on this @undefobj ?  aws-amplify/amplify-cli#689 would definitely address my needs

**Comment by ozimos** [comment]
try https://sofa-api.com/

**Comment by rickcha** [comment]
Are we NOT supposed to use both GraphQL and REST apis on Amplify architecture?
