### ISSUE TITLE
aws-amplify/ui package version ^1.0.15 is not available on NPM

### ISSUE THREAD

**Issue by reggie3** [aws-amplify/amplify-js#2515]
**Describe the bug**
aws-amplify instillation is looking for unavailable "@aws-amplify/ui" that matches "^1.0.15"

**To Reproduce**
Attempt to install aws-amplify using `yarn aws-amplify`
Receive the following prompt: 

**Expected behavior**
Expect to be able to install aws-amplify successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/7347192/51005590-76004c80-150d-11e9-8f5c-d3a97fbee51e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser N/A

**Smartphone (please complete the following information):**
 - Device:  N/A

**Additional context**
Attempted 

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by powerful23** [comment]
@reggie3 can you try it again? I tried to reproduce it but everything works fine for me.

**Comment by reggie3** [comment]
I just tried installing it again, and it appears to be working.  Thanks.

**Comment by powerful23** [comment]
@reggie3 No problem.
