### ISSUE TITLE
Question: Should components.Authenticator show federated login providers when they are enabled in the console?

### ISSUE THREAD

**Issue by 99hats** [aws-amplify/amplify-js#2516]
** Which Category is your question related to? **
3rd party authentication  on Vue

** What AWS Services are you utilizing? **
Cognito User Pools
AppSync

** Provide additional details e.g. code snippets **

Using the demo https://github.com/aws-samples/aws-amplify-vue
I added federated logins for Facebook and Google. 

These show up nicely in on the test url ui but the ui on the web app does not change.

Is this expected?

Thank you!

**Comment by powerful23** [comment]
@99hats Which service you are federating with 3rd part provider? Cognito User Pool Service or Cognito Federated Identity Pool Service?

**Comment by 99hats** [comment]
@powerful23  Cognito User Pool Service

**Comment by powerful23** [comment]
@99hats hi, as I know we do not have the functionality to do that kind of federation in the vue sample. Can you provide more details about how did you do that?

**Comment by carlschroedl** [comment]
Hi! Could this please be re-opened?

**Comment by carlschroedl** [comment]
@OrozcoJonathan 's attempt looks pretty good. There's additional inspiration here:
https://stackoverflow.com/questions/54162881/facebook-login-component-using-vue-js-and-amplify

**Comment by elorzafe** [comment]
@carlschroedl @cliffordh @99hats 

This was fixed with the new amplify-ui-components package. More information on how to use it you can find it [here](https://github.com/aws-amplify/amplify-js/tree/master/packages/amplify-ui-components#amplify-authenticator-federated)
