### ISSUE TITLE
Interactions failing on missing userId

### ISSUE THREAD

**Issue by Jefftopia** [aws-amplify/amplify-js#2517]
** Which Category is your question related to? **
Interactions

** What AWS Services are you utilizing? **
Lex

** Provide additional details e.g. code snippets **
I'm following the guide for starting with [Interactions](https://aws-amplify.github.io/docs/js/interactions). When I call the `send` method on Interactions, I get the following error:

>(node:27796) UnhandledPromiseRejectionWarning: MissingRequiredParameter: Missing required key 'userId' in params

It looks like Lex is expecting a userId, which in `@aws-amplify/interactions/lib/Providers/AWSLexProvider.js`, is supposed to be pulled from `credentials.identityId`. However, when I log `credentials`, it is type `SharedIniFileCredentials`, which does not have an `identityId` property [according to the documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SharedIniFileCredentials.html).

From [reading the docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityCredentials.html), `identityId` would have to be a Cognito user. `AWSLexProvider.js` makes no attempt at calling `CognitoIdentityCredentials` to get Cognito credentials. I am not sure where `identityId` is supposed to come from.

My code is the example from the Amplify website:

```
import Amplify, { Interactions } from 'aws-amplify';
import aws_exports from './aws-exports';

Amplify.configure(aws_exports);

async function test() {
    let userInput = "I want to reserve a hotel for tonight";

    // Provide a bot name and user input
    const response = await Interactions.send("BookTrip", userInput);

    // Log chatbot response
    console.log (response['message']);
}

test();

```

**Comment by surajSDM** [comment]
hi same error here  **Missing required key 'userId' in params**

this is mine configuration for aws-export:
const awsmobile = {
  aws_project_region: "****",
  aws_cognito_identity_pool_id:
     "****",
  aws_cognito_region: "****",
  aws_user_pools_id:  "****",
  aws_user_pools_web_client_id:  "****",
  Auth: {
    identityPoolId:  "****",
    region:  "****"
  },
  Interactions: {
    bots: {
      "botname": {
        name: "****",
        alias: "$LATEST",
        region:  "****"
      }
    }
  }
};

and i am . using interactions like:
** Interactions.send("botname", "start")
      .then(response =>
        console.log(response, "<========res")
      )
      .catch(e => console.log(e));**

**Comment by surajSDM** [comment]
@Jefftopia  @elorzafe @powerful23 @robbevan please let me confirm any update on this?

**Comment by Jefftopia** [comment]
@surajSDM I dropped this line of work in favor of using the aws-sdk directly which unblocked me.

For some reason, the only way I can get some amplify services to work is if I create anonymous Cognito users with the appropriate roles. This makes sense if I'm using a front-end, but I was using amplify on a node server that had secure access to my credentials.

**Comment by alikhorsandian** [comment]
Having the same problem. has anyone come up with any solution for this

**Comment by imoldfella** [comment]
Would also like a solution to this. I can see that It is ticking up the identity pool and the identity pool has role with policy AmazonLexRunBotsOnly. ConsoleLogger.js?36de:84 [ERROR] 17:01.869 Chatbot - Missing required key 'userId' in params. This doesn't make a lot of sense to me, there is no obvious place for it to get a userId since it is forcing a unauthenticated access.
