### ISSUE TITLE
Facebook/Google Sign In on User Pool (Not Identity Pool)

### ISSUE THREAD

**Issue by krgutierrez** [aws-amplify/amplify-js#2518]
** Which Category is your question related to? **
Cognito** User Pool

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
AWS Cognito is now supporting Federated Identities via User Pool. We want to implement our own login page. 

Using the AWS Cognito hosted UI, it supports adding users who logged in via Facebook or Google to the User Pool. Does AWS Amplify React supports this sign in? How?

NOTE: 
We don't want to use the `federatedSignIn` method which is for ** Identity Pool **.

**Comment by powerful23** [comment]
@krgutierrez yes, please check the doc: https://aws-amplify.github.io/docs/js/authentication#using-amazon-cognito-hosted-ui

**Comment by krgutierrez** [comment]
@powerful23 Thanks for the link. :D

**Comment by jamesgraham** [comment]
@powerful23 what if you don't want to use the Hosted UI? Any options?

**Comment by uclaeagit** [comment]
So far [this](https://github.com/aws-amplify/amplify-js/issues/1316) is the best solution I can find anywhere.

**Comment by undefobj** [comment]
Hello everyone, we have created an RFC for feature work that should make the challenges found in this issue easier in the future. If you have a moment please read through the details and add any comments: https://github.com/aws-amplify/amplify-js/issues/2716

Your feedback in the RFC will help us ensure that we are delivering the best experience possible. Thank you.
