### ISSUE TITLE
AWS-Amplify Auth Set Preferred MFA not Working

### ISSUE THREAD

**Issue by krgutierrez** [aws-amplify/amplify-js#2519]
<img width="508" alt="screen shot 2019-01-11 at 3 26 11 pm" src="https://user-images.githubusercontent.com/28826227/51019649-a64ff580-15b6-11e9-829c-8d8bc25a91e8.png">
**Describe the bug**
When calling the `setPreferredMFA` with **SMS** as the `mfaMethod`, it returns successfully. But when calling `getPrefferedMFA`, it still returns **NOMFA**.

**To Reproduce**
1. call `setPrefferedMFA` with **SMS** as `mfaMethod` parameter.
2. After `setPrefferedMFA` is successful, call `getPreferredMFA`.

**Expected behavior**
User's preferred MFA should be updated to **SMS**

**Actual behavior**
User's preffered MFA did not changed (Still **NOMFA**).

**Desktop (please complete the following information):**
 - MACOS
 - Chrome
 - 71.0.3578.98

**Additional context**
The user that I am changing is registered via Facebook (I used the User Pool not Identity Pool because we require to users to have an account to use not just an access)

**Comment by powerful23** [comment]
@krgutierrez I don't think setting preferred MFA would work if you are using the Cognito Hosted UI to login via third-party provider. The MFA feature is only for the native users(registered via Cognito Service).

**Comment by krgutierrez** [comment]
<img width="892" alt="screen shot 2019-01-13 at 9 52 44 pm" src="https://user-images.githubusercontent.com/28826227/51086137-96364280-177d-11e9-8381-19575a7f29ff.png">

@powerful23 Is there a plan to add a support for external providers or any alternative way? Somehow, we need the SMS MFA functionality.

**Comment by guanzo** [comment]
I can confirm that trying to setup MFA with TOTP or SMS is broken. 

```
const result = await Auth.setPreferredMFA(user, 'TOTP')
console.log(result) // SUCCESS

const preferredMfa = await Auth.getPreferredMFA(user)
console.log(result) // NOMFA
```

I'm using `"@aws-amplify/auth": "^1.2.14"`

Please fix ASAP

**Comment by cocacrave** [comment]
Please keep this issue from going stale.

**Comment by andy-edvalson** [comment]
This bug is still present in Amplify.
