### ISSUE TITLE
Custom storageOptions in Angular PhotoPicker 

### ISSUE THREAD

**Issue by XC3S** [aws-amplify/amplify-js#2524]
my target is to upload photos in a private s3 bucket using the photopicker component.
I tried the following way, however it does not work as expected and the storageOptions is ignored
```
opt:any = {
    'level': 'private'
}
```
```
<amplify-photo-picker path="testpath" storageOptions="{{opt}}"></amplify-photo-picker>
```

After I debugged it it seams like the `photo-picker.factory.js` receives the object as `"[object Object]"`.
How am i supposed to pass the option? I tried different ways and nothing seams to work.

also it seams like it relaters to #2223

**Comment by haverchuck** [comment]
@XC3S  Which versions of aws-amplify & aws-amplify-angular are you using?

**Comment by joshstir** [comment]
I'm not sure if you figured this out yet, but here is how I got it to work:

in my component:
`public myOptions: StorageOptions = {level: `private`};`

then in my template
`<amplify-photo-picker [storageOptions]="myOptions"></amplify-photo-picker>`

Hope this helps!

**Comment by XC3S** [comment]
@joshstir thanks for the info, I will try it out today
