### ISSUE TITLE
[Facebook] Deauthorize Callback URL Handling

### ISSUE THREAD

**Issue by cliffordh** [aws-amplify/amplify-js#2528]
I'd love to see an example of a Lambda or support in the Hosted UI auth endpoint for Facebook Deauthorize Callback URL. When a user removes your app from Facebook they should be disabled (maybe deleted based on policy) in Cognito. 

Same for "Data Deletion Requests"...

**Comment by undefobj** [comment]
How would you trigger this from happening? Does Facebook have the ability to execute a script or HTTP request whenever someone removes the app in their platform? I'm not sure this is possible to implement without an event source.
