### ISSUE TITLE
Updating user attributes does not update cached user data

### ISSUE THREAD

**Issue by safinn** [aws-amplify/amplify-js#2534]
**Is your feature request related to a problem? Please describe.**
Updating user attributes should update the cached user data.

**Describe the solution you'd like**
`Auth.updateUserAttributes()` refreshes the cached user information with the updated attributes.

**Describe alternatives you've considered**
Current solution is to call `Auth.currentAuthenticatedUser({ bypassCache: true })` after `Auth. updateUserAttributes()`. 

**Additional context**
n/a

**Comment by andidev** [comment]
This have been driving me crazy for a year now. Thanks for workaround! It works like a charm! After calling `Auth.currentAuthenticatedUser({ bypassCache: true })`, `Auth.currentUserPoolUser()` now returns all updated attributes.

**Comment by mikeokner** [comment]
Thank you! Would nice to at least have a mention of this in the docs.

**Comment by Christilut** [comment]
Thanks for the workaround! This should documented [here](https://aws-amplify.github.io/docs/js/authentication#working-with-user-attributes) at the very least

**Comment by emeagenciadigital** [comment]
@andidev thanks! was looking for this as Auth.updateUserAttributes amplify not working and couldn't find anything related. I was receiving success on the result but still didn't work.

Please AWS AMPLIFY update the DOCS.

**Comment by joroe** [comment]
I would say this is unexpected behavior. I would expect the local storage to be updated when updateUserAttributes is called.

**Comment by DirkPodolakEssquare** [comment]
As you have the user at hand, you may update the attribute manually and trigger storing.

```
let value = 'Joe'
await Auth.updateUserAttributes(user, { 'given_name': value })
user.attributes['given_name'] = value
user.cacheUserData()
```

But of course this should be part of `Auth.updateUserAttributes()` in the first place.

**Comment by iartemiev** [comment]
Should be fixed now in the latest **unstable** release. Will be released to stable in the near future as well. Closing this issue.

**Comment by nihp** [comment]
I have a clarification, Auth.currentCredentials sometimes giving expired token
(i.e) while i am in the app, it shows your incoming token has expired (401 message).
