### ISSUE TITLE
React hooks and Hub

### ISSUE THREAD

**Issue by Jaikant** [aws-amplify/amplify-js#2542]
** Which Category is your question related to? **
AWS Amplify - Hub

** What AWS Services are you utilizing? **
Amplify, AppSync, Lambda

** Provide additional details e.g. code snippets **
What will be the recommended way to use `Hub` with the propose React hooks (and arrow functions). With Hooks, we are doing away with ES6 classes. More specifically, from within the `onHubCapsule` how do we call the function to set the hook state.

Lets say I have a React component as follows, I have marked the specific question in the code below.

```
const Menu = props => {
	const [authState, setAuthState] = useState('loading');
  return (
      <div> {authState} </div>
      <button onClick={props.OAuthSignIn}> Login </button>
  )
}

Menu.onHubCapsule = capsule => {
	const {channel, payload, source} = capsule;
	if (channel === 'auth') {
	  switch (payload.event) {
	     case 'signIn':
              // -----> What is the recommended pattern to call setAuthState from here?
		 setAuthState('signedIn');
		 break;
	     case 'signIn_failure':
             // -----> What is the recommended pattern to call setAuthState from here?
		 setAuthState('signIn');
		 break;
	    default:
		break;
	}
     }
};

Hub.listen('auth', Menu);

const MenuAuth = withOAuth(Menu);

```

**Side Note:** Making it a name function or an anonymous function will still lead to internal react errors of `too many renders` when the `setAuthState` function.

**Comment by NuruddinBadawi** [comment]
any update on how to use Hub.listen with react hooks?

**Comment by markau** [comment]
```
  useEffect(() => {
    Hub.listen('auth', onHubCapsule)
  });
```
hangs my browser :cry:

**Comment by kevinwolfcr** [comment]
> ```
>   useEffect(() => {
>     Hub.listen('auth', onHubCapsule)
>   });
> ```
> 
> hangs my browser 😢
> 
> but, the non-hooks implementation like below was OK
> 
> ```
>   componentDidMount() {
>     Hub.listen('auth', this.onHubCapsule)
>   }
> ```

did you tried adding a dependency check?

```js
useEffect(() => {
  Hub.listen('auth', onHubCapsule)
}, [])
```

Also, make sure to return unsubscribe function.

**Comment by jordanranz** [comment]
The Hub interaction has been refactored as per this documentation:
https://aws-amplify.github.io/docs/js/hub#listening-for-messages

Is anyone still having issues with the new implementation of Hub?

**Comment by ericclemmons** [comment]
@Jaikant We're investigating user interest in hooks, starting with the API/GraphQL integrations: https://github.com/aws-amplify/amplify-js/issues/4235

Based on interest & feedback, the Auth category could also be a candidate for simplifying integration within your app.
