### ISSUE TITLE
Compatibility issues with ReactXP

### ISSUE THREAD

**Issue by agionfriddo** [aws-amplify/amplify-js#2553]
**Describe the bug**
I'm attempting to use Amplify to handle Authentication for my app built with ReactXP. When I try to run `Amplify.configure` the application fails to run with the following error: `Invariant Violation: No dimension set for key screen`. I've attached an image of the error stack to this issue. When I comment out the `Amplify.configure` code, the project runs as expected.

**To Reproduce**
1. Create a basic ReactXP app.
2. Install the Amplify library
3. Run Amplify.configure with configuration options

**Expected behavior**
I expected the project to build and run as expected.

**Screenshots**
![reactxpamplifyerror](https://user-images.githubusercontent.com/17485944/51260818-15459980-197d-11e9-9b1a-60b8c670c249.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] -- Windows 10
 - Browser [e.g. chrome, safari] -- N/A the issue happens with the Windows 10 build of the ReactXP app
 - Version [e.g. 22] -- N/A

**Smartphone (please complete the following information):**

**Additional context**

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by haverchuck** [comment]
@agionfriddo- Thanks for posting this. We are not super familiar with ReactXP; I am going to mark this as investigating so that we can investigate this issue as well as investigate compatibility with this library more generally.

**Comment by agionfriddo** [comment]
Great, thanks for the prompt reply! Let me know if you need anymore information, and I look forward to seeing how this resolves.

**Comment by haverchuck** [comment]
@agionfriddo -  Are you using the aws-amplify package only, or aws-amplify AND aws-amplify-react-native?

**Comment by agionfriddo** [comment]
Just the aws-amplify package

**Comment by damianesteban** [comment]
Update on this issue:

Without using the react-native library and with the following code:

```
  public login({ email, password }: AuthenticationInput) {
    console.log(`Logging in with: \n Email: ${email} \n Password: ${password}`);
    this._isLoading = true;
    Auth.signIn(email, password)
      .then(res => {
        console.log('logged in!', res);
        this._isLoading = false;
        this._isAuthenticated = true;
      })
      .catch(e => console.log(e));
  }
```

We are getting this error:

```TypeError: Cannot read property 'computeModPow' of undefined
    at BigInteger.nativeModPow [as modPow] (C:\Users\andrewgionfriddo\source\repos\request-management-app\node_modules\url\util.js:3)
    at AuthenticationHelper.calculateA (C:\Users\andrewgionfriddo\source\repos\request-management-app\node_modules\url\util.js:3)
    at AuthenticationHelper.getLargeAValue (C:\Users\andrewgionfriddo\source\repos\request-management-app\node_modules\url\util.js:3)
    at new AuthenticationHelper (C:\Users\andrewgionfriddo\source\repos\request-management-app\node_modules\url\util.js:3)
    at CognitoUser.authenticateUserDefaultAuth (C:\Users\andrewgionfriddo\source\repos\request-management-app\node_modules\url\util.js:3)
    at CognitoUser.authenticateUser (C:\Users\andrewgionfriddo\source\repos\request-management-app\node_modules\url\util.js:3)
    at C:\Users\andrewgionfriddo\source\repos\request-management-app\node_modules\url\node_modules\punycode\punycode.js:266
    at tryCallTwo (C:\Users\andrewgionfriddo\source\repos\request-management-app\node_modules\promise\setimmediate\core.js:45)
    at doResolve (C:\Users\andrewgionfriddo\source\repos\request-management-app\node_modules\promise\setimmediate\core.js:200)
    at new Promise (C:\Users\andrewgionfriddo\source\repos\request-management-app\node_modules\promise\setimmediate\core.js:66)```


Any ideas?

**Comment by damianesteban** [comment]
When we run `react-native link` the project is no longer buildable in Visual Studio. An example of one of the many errors:

```
Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error | CS0246 | The type or namespace name 'IReactPackage' could not be found (are you missing a using directive or an assembly reference?) | RequestManagementApp | C:\Users\damianesteban\source\repos\request-management-app-master\windows\RequestManagementApp\MainReactNativeHost.cs | 25 | Active
```

**Comment by haverchuck** [comment]
@damianesteban @agionfriddo It sounds like you will need to use the aws-amplify-react-native package, as this allows for the utilization of custom react-native bridge code which is necessary for certain things like SRP with Cognito (for example).  There could potentially be issues using aws-amplify and aws-amplify-react-native with ReactXP.

**Comment by agionfriddo** [comment]
I tried installing the aws-amplify-react-native package to make use of the withAuthenticator higher order component, like so

`import * as React from 'react';
import RX from 'reactxp';
import Amplify from '@aws-amplify/core';
import awsExports from './config/amplify';
import { withAuthenticator } from 'aws-amplify-react-native';
Amplify.configure(awsExports);

import Root from './views/Root';
class App extends RX.Component {
  public render() {
    return <Root />;
  }
}

export default withAuthenticator(App, true);`

However, I'm still getting the same error as before.

![other-amplify-error](https://user-images.githubusercontent.com/17485944/51355191-51afed00-1a84-11e9-8a33-59acedc2b660.png)

If I don't run the Amplify.configure method, I'm able to see the react-native login component, but the code breaks when I add it back in.
