### ISSUE TITLE
Should federatedSignIn automatically refresh the access token?

### ISSUE THREAD

**Issue by jdolinski1** [aws-amplify/amplify-js#2555]
** Which Category is your question related to? **

** What AWS Services are you utilizing? **
Cognito, aws-amplify

** Provide additional details e.g. code snippets **
I am using Google for federated auth. I let user successfully log in and obtain `token` and `expires_at`, which i then use in aws-amplify function:
```
Auth.federatedSignIn(
            "google",
            {
                token: response.tokenId,
                expires_at: response.Zi.expires_at,
            },
            user
).then()...
```
Everything is good, but after 1 hour, the token is not refreshed, meaning there is expired token in localStorage:
<img width="1077" alt="screen shot 2019-01-16 at 20 08 31" src="https://user-images.githubusercontent.com/25304988/51273368-c889af00-19cc-11e9-9deb-fc930c9798ae.png">
Should the automatic token refresh be working? I mean, the docs says so:
```
By default, AWS Amplify will automatically refresh the tokens for Google and Facebook, so that your AWS credentials will be valid at all times. 
```
but how could it be working when i am not providing the refresh token to the amplify lib in any way?

Thanks for info.

**Comment by haverchuck** [comment]
@jdolinski1 I believe you need to have the google sdk in the window, as shown in the react sample [here](https://aws-amplify.github.io/docs/js/authentication#code-samples).

Alternatively, you can provide a refresh handler to the Auth module:
```
Auth.configure({
    refreshHandlers: {
        'developer': refreshToken // the property could be 'google', 'facebook', 'amazon', 'developer', OpenId domain
    }
})
```

**Comment by elorzafe** [comment]
The automatic refresh token will happen if you provided that [code snippet](https://aws-amplify.github.io/docs/js/authentication#code-samples) on your react app. The library requires in order to refresh the tokens without add `refreshHandlers` callback

**Comment by jdolinski1** [comment]
I am now using the method you advised. The logging in works good with the Amplify docs code snippet, but still, the token is not refreshing.

I am including the FB and Google scripts as soon as the app mounts, and call `currentAuthenticatedUser` after that like this:
```
   componentDidMount() {
        if (!window.FB) this.createFacebookAuthScript()
        const ga = window.gapi && window.gapi.auth2 ? window.gapi.auth2.getAuthInstance() : null
        if (!ga) this.createGoogleAuthScript()

        Auth.currentAuthenticatedUser().then(...)
    }

    createGoogleAuthScript() {
        // load the Google SDK
        const script = document.createElement("script")
        script.src = "https://apis.google.com/js/platform.js"
        script.async = true
        script.onload = this.initGapi
        document.body.appendChild(script)
    }

    createFacebookAuthScript() {
        // load the sdk
        window.fbAsyncInit = this.fbAsyncInit
        const script = document.createElement("script")
        script.src = "https://connect.facebook.net/en_US/sdk.js"
        script.async = true
        script.onload = this.initFB
        document.body.appendChild(script)
    }

    initGapi() {
        // init the Google SDK client
        const g = window.gapi
        g.load("auth2", () => {
            g.auth2.init({
                client_id: envVars.GOOGLE_OAUTH_CLIENT_ID,
                // authorized scopes
                scope: "profile email openid",
            })
        })
    }

    initFB() {
        // const fb = window.FB
        // console.log("FB SDK inited")
    }

    fbAsyncInit() {
        // init the fb sdk client
        const fb = window.FB
        fb.init({
            appId: envVars.FACEBOOK_LOGIN_APP_ID,
            cookie: true,
            xfbml: true,
            version: "v2.11",
        })
    }
```

But still, after one hour, the token and expires_at properties in local storage does not change.
<img width="948" alt="screen shot 2019-01-30 at 15 38 22" src="https://user-images.githubusercontent.com/25304988/51994887-f7665180-24b1-11e9-963a-f56d2986981a.png">

Should i call any other Amplify function to refresh the token or am i doing anything else wrong?

**Comment by powerful23** [comment]
@jdolinski1 sorry to be late. The tokens will not be refreshed as soon as expired. They will be refreshed by the library when some certain function calls `Auth.currentCredentials()` which will use the token to get a new aws credentials. At that moment the tokens will be refreshed as we cannot use the expired ones to get a new credential.

**Comment by enzo-beltrami** [comment]
i had this problem and using the snippet + `Auth.currentCredentials()` worked, thanks!

**Comment by elorzafe** [comment]
I will close the issue for now, feel free to create a new one if you still have any concerns.
