### ISSUE TITLE
Analytics updateEndpoint failed - iPhone XR only 

### ISSUE THREAD

**Issue by RobertNg1125** [aws-amplify/amplify-js#2566]
**Describe the bug**

Hi, I run into an issue where updateEndpoint failed only on iPhone XR. 
There is a complain about the Make and Model of the iPhone XR which are not string. 

The `updateEndpoint()` works well on other iPhone (6, 6s, 7) and the values of Make and Model on these phones are String. 

Could we somehow alter the device info data before sending `updateEndpoint()`?

Thanks

The error says: 
**InvalidParameterType: Expected params.EndpointRequest.Demographic.Make to be a string** 
**InvalidParameterType: Expected params.EndpointRequest.Demographic.Model to be a string**

```
019-01-17 11:59:16.659 [info][tid:com.facebook.react.JavaScript] '[DEBUG] 59:16.657 AWSPinpointProvider - updateEndpoint with params: ', { ApplicationId: '201282b947d9426c9eb7fcd868dd1dc5',
  EndpointId: '35c0d830-1a74-11e9-88bd-93a8d730a5db',
  EndpointRequest: 
   { ChannelType: 'APNS',
     RequestId: '39522300-1a79-11e9-8e1a-8302b0e39adf',
     EffectiveDate: '2019-01-17T16:59:16.656Z',
     Address: '58431fe74e49df78a96f7b1f93be164ede6120111063b1915a6f3a223ef94085',
     Attributes: {},
     Demographic: 
      { AppVersion: 'ios/12.1.2',
        Make: {},
        Model: {},
        ModelVersion: '12.1.2',
        Platform: 'ios' },
     Location: {},
     Metrics: {},
     User: 
      { UserId: '58431fe74e49df78a96f7b1f93be164ede6120111063b1915a6f3a223ef94085',
        UserAttributes: { notificationOptIn: [ 'optOut' ] } } } }
2019-01-17 11:59:16.660 [info][tid:com.facebook.react.JavaScript] '[DEBUG] 59:16.660 AWSPinpointProvider - updateEndpoint failed', [MultipleValidationErrors: There were 2 validation errors:
* InvalidParameterType: Expected params.EndpointRequest.Demographic.Make to be a string
* InvalidParameterType: Expected params.EndpointRequest.Demographic.Model to be a string]
2019-01-17 11:59:16.661 [info][tid:com.facebook.react.JavaScript] [DEBUG] 59:16.661 AWSPinpointProvider - resending event undefined with 4 retry times left
```

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS
 - Version: 12.1.2

**Comment by RobertNg1125** [comment]
Update: 
I finally come up with a workaround where I manually setup Analytics (as per described in [the doc](https://aws-amplify.github.io/docs/js/analytics)). And in this `demographic` attribute, I make sure `make` and `model` are String. This can be done using `react-native-device-info` to extract Make and Model.

**Comment by jordanranz** [comment]
Hey @RobertNg1125,

It is odd that the Make and Model parameters in the request are empty objects instead of strings. This may be something wrong with the way we retrieve default client info for the iPhone XR. I'll mark this as a bug and we can investigate this further.

**Comment by jordanranz** [comment]
The fix has been released to the latest amplify release.
