### ISSUE TITLE
aws-amplify-vue Connect.vue mutation does not handle errors in graphql operation correctly.

### ISSUE THREAD

**Issue by ryanhollander** [aws-amplify/amplify-js#2568]
**Describe the bug**

The bug is in the block constrained by the if statement "if (hasValidMutation) on line 126 of aws-amplify-vue/src/components/api/graphql/Connect.vue. There is no error handling and any error is essentially swallowed by the code and only emitted to console, making it invisible to the component. Instead, there should be error handling that pushes the error into the errors list, as it does in the block above (if (hasValidQuery)).

```
     if (hasValidQuery) {
        try {
          this.data = {};
          this.loading = true;
          const response = await this.$Amplify.API.graphql({ query, variables });
          this.data = response.data;
        } catch (error) {
          this.logger.warn(error);
          this.errors = error.errors;
          this.$emit('error', error);
        }
      }

      if (hasValidMutation) {
        this.isMutation = true;

        this.internalMutation = async () => {
          / * should put a try/catch here! */
          const result = await this.$Amplify.API.graphql({ query: mutation, variables: mutationVariables });
          this.$emit('done', result);
          return result;
        };
      }
```

**To Reproduce**
Create a form that uses a mutation against a DynamoDB database using GraphQL. Make a field required, but omit it the value in the submitted form or put an invalid (to Dynamo) value in the form and submit the form. The form will not complete processing and an error is displayed in the console.

**Expected behavior**
The error to be pushed to errors so I could handle it in the form code.

**Screenshots**
 
![image](https://user-images.githubusercontent.com/8209945/51339281-097bd500-1a5a-11e9-8030-f94f299b1663.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by haverchuck** [comment]
@ryanhollander Merged a fix for this into our unstable branch.  Once it propogates it should be availble via 'npm install aws-amplify-vue@unstable'.  It will be merged into our main build in the near future.
