### ISSUE TITLE
[Vue] UserNotConfirmedException, and a fix...

### ISSUE THREAD

**Issue by cliffordh** [aws-amplify/amplify-js#2571]
**Describe the bug**
Using Amplify Vue, if a user creates an account, doesn't confirm their email, but then comes back to the app and tries to sign in, they are given the error that they are "not confirmed"... however there is no path to get them to confirm.

I have rewritten the Amplify Vue components as I don't need anything but the auth logic and I've removed AmplifyEventBus (all told I've saved 160k by not using aws-amplify-vue and rewriting the auth components). Anyway, in SignIn.vue, you need to handle the "UserNotConfirmedException" and emit an event on the event bus. Here's my code using the Hub and then again using AmplifyEventBus. 

SignIn.vue, method signIn... at catch(e)

          if (e && e.code && e.code == "UserNotConfirmedException") {
            this.$Amplify.Hub.dispatch(
              "authorization",
              {
                event: "confirmSignUp",
                data: ""
              },
              "authorization"
            );
          } else {
            this.setError(e);
          }

or, using the AmplifyEventBus:

          if (e && e.code && e.code == "UserNotConfirmedException") {
                AmplifyEventBus.$emit("authState", "confirmSignUp");
          } else {
            this.setError(e);
          }

Hope this helps.

Cliff

**Comment by haverchuck** [comment]
@cliffordh  - What would you think of a component that the user goes to themselves via a link like 'Already have a code? Confirm here.'.

**Comment by haverchuck** [comment]
@cliffordh Merged a fix for this into our @unstable build (will take awhile to propagate).  It will be merged into our main build in the coming days.  Once it propagates to unstable, it will be available via `npm install aws-amplify-vue@unstable`.

**Comment by borisdayma** [comment]
Just for info, the hosted UI has the same problem.
