### ISSUE TITLE
PubSub | How to subscribe to a topic?

### ISSUE THREAD

**Issue by Vingtoft** [aws-amplify/amplify-js#2575]
According to [documentation](https://aws-amplify.github.io/docs/js/pubsub), subscribing to AWS IoT Core should be done this way:

`PubSub.subscribe('topic').subscribe({/*do something*/)`

It's now required to add  `ProvidertOptions`, like this: 

`subscribe(topics: string[] | string, options: ProvidertOptions): Observable<any>;`

I cannot find any example of how to use `ProvidertOptions`, but passing an empty object will work on the development server:

`PubSub.subscribe('topic', {}).subscribe({/*do something*/)`

This approach works in dev but generates an error that blocks any build. 

**What is `ProvidertOptions` and how can I subscribe to a topic?**

**Comment by lclghst** [comment]
ProvidertOptions is found in '@aws/amplify/pubsub/lib/types'

`export interface ProvidertOptions {
    [key: string]: any;
}`

The documentation does not provide information on what (if any) options we can use here.

Why is this a required param?
