### ISSUE TITLE
[aws-amplify-angular] Display password policy in signup component

### ISSUE THREAD

**Issue by codingnuclei** [aws-amplify/amplify-js#2576]
**Is your feature request related to a problem? Please describe.**
Currently the password input in the signup component displays no indication of the password policy used in cognito. This causes the user to try multiple time when creating a password.

**Describe the solution you'd like**
I suggest passing in another field (passwordPolicy: string) in the signUpConfig object.
The component will then use this string to render it to the view (under the password input).  Defaults to undefined, leaving the current behaviour (no policy shown).

example: `signUpConfig =  {passwordPolicy: 'Use 8 or more characters with a mix of letters, numbers & symbols'}`

**Describe alternatives you've considered**
Could instead pass in a boolean, and get the policy using the CognitoIdentityServiceProvider. And build the sentence dynamically.  This I think adds unnecessary complexity. 

**Additional context**
When you follow the reset flow the New password input should probably also have the policy. I suggest the policy be added to this component the same way once configs for those components have been implemented.

**Comment by haverchuck** [comment]
Fixed by PR #2589.
