### ISSUE TITLE
Storing userPoolId, region in javascript

### ISSUE THREAD

**Issue by anandvasu** [aws-amplify/amplify-js#2583]
** Which Category is your question related to? **
aws-amplify

** What AWS Services are you utilizing? **
AWS Cognito

** Provide additional details e.g. code snippets **

Hi,

I am building a web app using reactjs and i am using AWS cognito user pool for maintaining users. The aws-amplify developer guide suggests to store the region, userPoolId and other detail in a javascript file. is it secure to store these detail in a javascript file. If hackers get to know these detail, they can signup/signin users and start using the application.

Regards
Anand

**Comment by haverchuck** [comment]
These are standard configuration parameters that do not expose extra security risks, and are in line with technologies that Cognito uses such as SRP, OAuth, etc. They help the clients construct endpoint URLs during these processes that are unique to your account, and do not give access to administrative commands or access to other user accounts.

**Comment by haverchuck** [comment]
Related to #2495

**Comment by jordanranz** [comment]
Closing as the question has been answered. Please reopen if you have any further questions or concerns.
