### ISSUE TITLE
Unable to exitVR using amplify xr react component 

### ISSUE THREAD

**Issue by runpiw** [aws-amplify/amplify-js#2595]
**Description**
By using amplify-react-component XR and Amazon Sumerian, after clicking enterVR button to enter vr in a scene, there is no way to exitVR from the scene.

**To Reproduce**
1. Follow amplify tutorial to setup a Sumerian VR scene with amplify-react-component
2. Hit enterVR button to enter the VR experience of Sumerian scene
3. Unable to exitVR once you're in VR

**Expected behavior**
Have a way to exitVR either from a separate button or the same enterVR button

**Additional context**
Probably want to keep a state for whether inVR https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/XR/SumerianScene.jsx#L138
And call exitVR function https://github.com/aws-amplify/amplify-js/blob/master/packages/xr/src/XR.ts#L115

**Comment by jordanranz** [comment]
Merged the change. It should be in the latest unstable release.

**Comment by jordanranz** [comment]
Reopening until published to release branch.

**Comment by jordanranz** [comment]
This is now in the latest release.
