### ISSUE TITLE
Pass request options through to Axios

### ISSUE THREAD

**Issue by exptom** [aws-amplify/amplify-js#2596]
@haverchuck suggested that I open a feature request here.

I am utilising the rest features of the `API` module in amplify. I would like to be able to show a loading/progress bar and had hoped to hook this into the `onDownloadProgress` option of the axios.
I had assumed I could simply pass a function through the `myInit` parameter of the `API.get()` but the options do not seemed to be passed through to axios.

What is the reason for the options being discarded? Is there an alternative way that I could show a progress bar?

**Comment by elorzafe** [comment]
@exptom thanks for your feedback. Just curious, which REST API are you calling that requires this functionality?

**Comment by exptom** [comment]
@elorzafe I'm calling an API Gateway rest api and want to be able to show a progress indicator on requests. I can't find a way to do this currently.

**Comment by LosD** [comment]
`transformRequest` and `transformResponse` is unfortunately also not forwarded. Those makes serializing to proper objects, much easier when using non-simple objects (e.g. using `JSON.parse` with a reviver, or `JSON.stringify` with a replacer)

In general, I think it would make most sense to pass all params (that Amplify doesn't use itself) as-is.

XSRF prevention is also a crucial feature that is currently being thrown away.

**Comment by sammartinez** [comment]
@exptom Is this still a valid use case for you? Please let us know

**Comment by exptom** [comment]
@sammartinez it would still be useful for these options to be passed through but we have worked around this issue and I am no longer working on the project where this was a problem.

**Comment by sammartinez** [comment]
@exptom Thank you for the update on this. Resolving this request since you are no longer needing this.

**Comment by LosD** [comment]
@sammartinez That he has worked around it doesn't make it less of a horrible bug. We've worked around it too... By not using it anymore, because it is so badly designed.

**Comment by ffxsam** [comment]
I'd like to see this issue re-opened if possible, @elorzafe. It would be great to allow devs to freely pass axios options into `API`. I have a similar use case as the other people on this thread, which is to be able to use `transformResponse` to transform a raw API response by camel-casing all the keys. Right now I'm doing this:

```js
export async function getGroups() {
  const data = await API.get('v2', '/groups', {});
  return camelcaseKeys(data, { deep: true });
}
```

which is really just a bit too much extra code. If I could use `transformResponse`, I could just define that function as:

```js
export const getGroups = () => API.get('v2', '/groups', {});
```
