### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by flybayer** [aws-amplify/amplify-js#2598]
**Describe the bug**
I'm unable to use `Auth` in my app without installing and using babel-polyfill. I really do not want to add this as an extra dependency.

**Expected behavior**
I expect this library code to not use polyfills. If I need polyfills for my app, then I want to add them myself as needed.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox
 - Version 65

**Additional context**
I'm using a basic React SPA with Parcel defaults.

**Comment by elorzafe** [comment]
@flybayer which versions of aws-amplify are you using?

**Comment by flybayer** [comment]
aws-amplify 1.1.19

**Comment by elorzafe** [comment]
Maybe this issue is related to this one parcel-bundler/parcel#871, I think this is problem with parcel.

Did you try aws-amplify-react?

**Comment by flybayer** [comment]
Wow you are right, thanks!

**Comment by elliott-king** [comment]
I am confused at the solution here. It seems like @elorzafe is suggesting to import Auth from aws-amplify-react, but it seems like it can't be done? It does not show up on the list of imports. 

If possible @flybayer, is there a quick overview of the fix you made?

**Comment by tuanardouin** [comment]
I'm also working with amplify but with vuejs and I had this problem. @elliott-king answer is correct, my `babel.config.js` file look like this :
```js
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        useBuiltIns: 'entry',
        corejs: 3
      }
    ]
  ],
  "plugins": [				// The part
    "@babel/plugin-transform-runtime"	// I had to change
    ], 
}
```
