### ISSUE TITLE
Anonymous credentials to access resources

### ISSUE THREAD

**Issue by ilrein** [aws-amplify/amplify-js#2599]
**Which Category is your question related to?**
Auth

**What AWS Services are you utilizing?**
Cognito

**Provide additional details e.g. code snippets**
When setting up a custom Cognito configuration:

```
Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) I want to learn more.

If you select 'yes', your identity pool will provide temporary AWS credentials for unauthenticated guest users.

```
You get prompted with the option of allowing unauthenticated logins, in order to access resources without logging in, but I can't find any documentation explaining how to leverage this. Any suggestions?

**Comment by ilrein** [comment]
@elorzafe any update on this sir?

**Comment by haverchuck** [comment]
@ilrein If you are using Amplify and you have configured your other resources (i.e. Storage, API, etc) to allow unauthenticated identities, then this should be handled for you automatically.  However, if you are using other services not supported by Amplify, you should be able to leverage the credentials to sign the request for these services assuming that they too are configured to accept unauthenticated credentials.  And yes - Auth.currentCredentials should work.
