### ISSUE TITLE
When amplify use AuthStateWrapper

### ISSUE THREAD

**Issue by plum-shiga** [aws-amplify/amplify-js#2600]
** Which Category is your question related to? **
just a question.

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
This question is about aws-amplify-react.

When user signin, automatially authState turn to 'signedIn'.
I confirmed package code, then I found `AuthStateWrapper` have checkUser() and turn to 'signedIn'.

I grep `aws-amplify-react` but I can not found the place of used `AuthStateWrapper`.

When amplify use AuthStateWrapper?

**Comment by elorzafe** [comment]
@plum-shiga I think this is not getting use at all. I will review this with the team.

Thanks!

**Comment by plum-shiga** [comment]
> elorzafe

Thanks for your reaction.
but, it is storange. I confirmed turn to `automatically turn to signedIn-state`, I assume it is why user object (token) is already stored in localstorage.

At checkUser() call Auth.currentUser(), then change `AuthState`.

If `this is not getting use at all`, what code turn to `signedIn` ?

**Comment by haverchuck** [comment]
@plum-shiga  This is getting set by the checkUser function in Authenticator.jsx.  I am closing this issue for now, but please feel free to open a new issue if this answer is not satisfactory.
