### ISSUE TITLE
Efficiently detect if already signed in

### ISSUE THREAD

**Issue by cliffordh** [aws-amplify/amplify-js#2601]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
I've used the Authenticator widget and it works well, but I want to break Sign In and Sign Up into their own pages. Primarily because I want to add marketing messages on the Sign Up flow. Now, my question is this: if I have my "main page" and then have my Sign In and Sign Up flows. Am I going to be able to know if the user is "signed in" on the main page? I plan on presenting different content if someone is signed in... 

e.g. Not signed in - Sees advertisements
Signed in - No advertisements

I don't want to load my main page, with ads, then wait for "currentAuthenticatedUser" to return and then remove the ads... there has to be a better way to detect if someone has a current "session".

Thanks,
Cliff

**Comment by elorzafe** [comment]
@cliffordh which frontend framework are you using?

**Comment by angryeuan** [comment]
I'm also curious about this. 

at the moment i'm doing:

`    this.$Amplify.Auth.currentUserCredentials().then(resp => {
      console.log(resp.authenticated)
    })
`
