### ISSUE TITLE
aws-amplify Auth Network Error

### ISSUE THREAD

**Issue by goalguy10** [aws-amplify/amplify-js#2605]
I have a React application that I am building. I have a custom Sign Up page and Sign In page. Both were working about 20 minutes ago and now they are not. I am getting a very generic "NetworkError" returned from Auth.signIn and Auth.signUp. Nothing has changed in the code or configuration since it was working. I am getting the error when I run the application locally and when I run it in my S3 bucket. Anybody have any ideas?

**Comment by elorzafe** [comment]
@goalguy10 on which region do you have your Cognito User Pool? I can try to replicate the issue. Can you try on a different network. Maybe a firewall is blocking the requests to Cognito?

Which version of amplify are you using?

**Comment by goalguy10** [comment]
I believe it is east-1 Virginia. I tried on multiple networks and even tried it hosted with amplify. It was working at one point then 15-20 minutes later it was no longer working. I am using the most recent version.

**Comment by elorzafe** [comment]
I created userpools on virginia and oregon and both work correctly with aws-amplify. Are you located on the east coast?

**Comment by elorzafe** [comment]
@goalguy10 what HTTP response code are you getting? If you enable 'DEBUG' `Amplify.Logger.LOG_LEVEL = 'DEBUG'` maybe there is something else.

**Comment by Iboss** [comment]
I do have the same problem. The weird thing is my friends tried to signup also and the got the same error but they still got the verification code !

**Comment by goalguy10** [comment]
@elorzafe yes I am located on the east coast. I do not get any http response. I get the error “networkerror” returned and then the page refreshes. I will turn on debugger and post the results.

**Comment by goalguy10** [comment]
Same result with debugger. No other information other then network error. My user pool is in Virginia. I even deleted and re added the amplify Auth with no change.

**Comment by elorzafe** [comment]
@goalguy10 I will continue trying to diagnose this issue

**Comment by elorzafe** [comment]
@goalguy10 Can you paste the HTTP response code?

**Comment by goalguy10** [comment]
I was able to reproduce the issue using a completely new project. I am not getting any HTTP response. the only thing I get is the following console prinout: 

`error signing in...:  
{…}
​
code: "NetworkError"
​
message: "Network error"
​
name: "Error"
​
<prototype>: Object { … }
main.chunk.js:159:9 `

That is the response to:
`Auth.signIn(username, password)
      .then(user => {
        console.log('Success');
      })
      .catch(err => {
        console.log('error signing in...: ', err);
      })`

With this same project I can register and login using the withAuthenticator.

**Comment by elorzafe** [comment]
@goalguy10 can you paste (commenting the sensible parts) on how you are configuring amplify, and importing Auth.

**Comment by elorzafe** [comment]
@goalguy10 I have just tried this react-app and it works ok for me. Can you try this code (replacing username and password)
```jsx
import React, { Component } from 'react';
import './App.css';
import Amplify, { API, Auth } from 'aws-amplify';
import config from './aws-exports';

Amplify.configure(config);

class App extends Component {

  async getUserInfo() {
    const user = await Auth.currentUserInfo();
    console.log({ user });
  }

  signIn(){
    Auth.signIn("xxxxxxxxx", "xxxxxxxx");
  }
  signOut(){
    Auth.signOut();
  }

  render() {
    return (
      <div className="App">
        <button onClick={this.getUserInfo}>userInfo</button>
        <button onClick={this.signIn}>signIn</button>
        <button onClick={this.signOut}>signOut</button>
      </div>
    );
  }
}

export default App;
```

This is my aws-exports.js
```javascript
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:********-****-****-****-*************",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_*********",
    "aws_user_pools_web_client_id": "*************************"
};


export default awsmobile;
```

**Comment by elorzafe** [comment]
@goalguy10 can you share some screenshots from your network tab. Maybe I can diagnose better with that information.

**Comment by guiaamaral** [comment]
@goalguy10 I'm with the same problem but my code is for React Native. I tryed to simulate the problem with another two smartphones (iPhone X - iOS 12 and Moto G5 - Android 8.1) and worked! I'm using Android 9.0... It's possible to be an OS problem?

**Comment by jtarini** [comment]
@guiaamaral Did you solve this problem for your Moto G6 Plus with Android 9.0?
I'm facing the same issue with my Android devices only, for me it's a React Native app too.

**Comment by guiaamaral** [comment]
@jtarini Nothing yet! I don't now why this happen. I tried to debbug but with no success.

**Comment by s-hood** [comment]
I'm having the same error but from changePassword. signIn and deleteUser both work for me. Has anyone made progress?

**Comment by joebernard** [comment]
I am seeing this too. In my case, I have multiple Cognito triggers associated with Lambda functions for custom authentication. The problem always seems to occur during cold starts of my Lambdas. If my dev environment has been sitting all night and I attempt a login in the morning, I will see this error for up to 30 minutes.

I only get this error when calling `Auth.sendCustomChallengeAnswer`. My calls to `Auth.signIn` and `Auth.signUp` work fine.

`Auth.sendCustomChallengeAnswer` will usually invoke my Cognito trigger assigned to Verify Auth Challenge Response. When I start seeing this `NetworkError` problem, the Lambda associated with this trigger is not called. There is a disconnect somewhere between Cognito and that function during these events. It seems like when Lambda is cold starting a function, Cognito is n unable to deal with it.

Here is the error I'm catching

> {"code":"NetworkError","name":"Error","message":"Network error"}

This issue should be re-opened.

Amplify 1.0.31

**Comment by boboci9** [comment]
I also encounter this same issue with react-native, while the same setup works in a simple react project!

**Comment by tjhowe** [comment]
joebernard @boboci9 I've also had issues with this on react native when calling the   `Auth.sendCustomChallengeAnswer ` method. Has anyone had an update on this?

**Comment by kevinhankinson** [comment]
I am also seeing this issue using Vue.js
both the username and password are populated.

try {
          await Auth.signUp({
            username, password
          })

          } catch(e) {
            console.log('Exception: ', e)
          }

 I enter the page for the first time, enter the datq and try to signup - I get an  error message: {code: "NetworkError", name: "Error", message: "Network error"}. The page represents, I enter the details againa and it works.

**Comment by dvyue** [comment]
Have the same issue with React. The set up works with the AWS web UI, but doesn't work with amplify Auth.

**Comment by Edisonsan** [comment]
Same Error, we are working fine a few hours ago, and suddenly:

{"code": "NetworkError", "message": "Network error", "name": "Error"}

**Comment by giulioambrogi** [comment]
Same error here, we are experiencing a spike in Network errors since late afternoon (after 6PM London time) on 22 Oct 2019. Any idea?

![Screenshot 2019-10-23 at 12 12 44](https://user-images.githubusercontent.com/11599158/67397048-87987980-f5a0-11e9-9d33-64d642a297ae.png)

**Comment by stopitdan** [comment]
I was having this same problem in my react app - while it is slightly mentioned in an answer previously, it seems to be looked over, so ill outline the EASY EASY fix i was able to do.

I realized that in my react app it was refreshing the page by default when i would submit a form, before the `await Amplify.signUp` was able to finish. that's why sometimes it would work rarely, but mostly not. 

All i did was add an `event.preventDefault()` on the form's `onSubmit` handler, and voila!

pretty simple, but it was not made clear thats all i needed with the answers above, i found this info elsewhere, so i thought i'd save other people with the same issue the trouble of searching elsewhere!

**Comment by Audace** [comment]
We're having the same issue intermittently with a react-native app. I checked the lambda metrics and it doesn't seem that we're anywhere close to our timeout limit there. This happens across Android and iOS devices. The error is the following:
```
{
    code: NetworkError, 
    message: Network error, 
    name: Error
}
```

**Comment by rahulje9** [comment]
We're having the same issue with a react-native app. any solution for this?

**Comment by nir099** [comment]
did anyone get a solution?

**Comment by bernardnongpoh** [comment]
Any Solutions?

**Comment by 24jr** [comment]
Everything was working fine for me in vue js and then I had to install react native stuff for work and also updated my aws stuff and went back to create a vue project and got the Network Error issue for GraphQL. So Idk if it was something with that react native stuff I installed cause I see other people mention react-native or an aws amplify update or what

**Comment by hisham** [comment]
Am also having some users reports this. Angular app.

**Comment by hisham** [comment]
For anyone running into this, I'm able to repro my issue if my system's clock is off. See https://github.com/aws-amplify/amplify-js/pull/5869. The actual call to Cognito was working, I had a followon call to API Gateway that was failing. So I believe users had some clock drift. Fortunately the amplify team just merged in a fix for this 2 days ago.

**Comment by chai86** [comment]
@elorzafe Was a solution ever found for this issue? I keep getting `Network Error` when trying to Auth.SignUp().


```
signUp = async (event) => {

    event.preventDefault();

    const username = "John"
    const password = "Abcdefgh12"
    const email = "mypersonalemail@hotmail.com"
  
    await Auth.signUp({
      username,
      password,
      attributes: { email }
    })
    .then(() => {
      console.log('sign up successful!')
      Alert.alert('Enter the confirmation code you received.')
    })
    .catch(err => {
      if(err['code'] === "UsernameExistsException"){ 
         Alert.alert('Username already taken', 'Please try another')
      }
      if (! err.message) {
        console.log('Error when signing up: ', err)
        Alert.alert('Error when signing up: ', err)
      } else {
        console.log('Error when signing up: ', err.message)
        Alert.alert('Error when signing up: ', err.message)
      }
    })
  }
```

**Comment by nir099** [comment]
hey everyone who got this issue here's whats happened in my scenario. the cause for this issue was that the emulator doesn't have the access to the internet , please make sure that you emulator has the network connection, that's the reason to display error "Network Error".  Please make sure your emulator is displaying wifi icon.

**Comment by chai86** [comment]
@nir099 Yup, Emulator can access the internet. I get a 'This connection is not private' page on the web browser, but when i click visit anyway, it does get me to the website. Perhaps this is the issue?

**Comment by nir099** [comment]
> @nir099 Yup, Emulator can access the internet. I get a 'This connection is not private' page on the web browser, but when i click visit anyway, it does get me to the website. Perhaps this is the issue?

hey @chai86 did you try this, shut down the laptop, start again then connect to the internet then run the emulator, verify the wifi icon is on, remove the app from the emulator , run npx react-native run-android if you using RN. then try again. the reason why I'm telling this because in my problem it got solved automatically, i didn't do anything in particular in next day when i run the emulator it was working. here's another idea make another emulator instance run the app in there.

**Comment by chai86** [comment]
@nir099 Unfortunately that didn't work.

**Comment by benjeater** [comment]
I was having this issue when using React Redux because the event wasn't set to persist.  Fixing the issue for me was as simple as adding `event.preventDefault();` to the form submit function.

**Comment by mkarsene** [comment]
@benjeater  I also faced this issue, e.preventDefault() worked for me as well!

**Comment by sureshUngarala** [comment]
👍  event.preventDefault() did the trick.

**Comment by tnraddatz** [comment]
If you're using API Gateway and are running into this issue, make sure you update the API Gateway's "Gateway Responses" Default 5XX and Default 4XX header's to contain correct response headers (and/or messages) -- or else Access-Control-Allow-Origin wont be sent on error responses and your browser will throw "Network Error".

For example, set response headers for Default 5XX and 4XX to:

Response header: Access-Control-Allow-Origin
Value: '*'

Updating these default header values resolved my issue, now proper error messages are being resolved.

**Comment by jgiunta1** [comment]
I'm using Formik and [it already calls "preventDefault()"](https://github.com/formium/formik/blob/master/packages/formik/src/Formik.tsx#L796) so not sure that will help me.  

Stack Trace:
#### 3 Client Level
- Network Error 

#### 2 Amplify Level
- [/auth/src/Auth.ts#L618](https://github.com/aws-amplify/amplify-js/blob/4d39773b0c174538d0d7c1b770bc276700bcf953/packages/auth/src/Auth.ts#L618)

#### 1 Cognito Level
- Error Thrown Here: [amazon-cognito-identity-js/src/Client.js#L85](https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/src/Client.js#L85)

**Comment by jgiunta1** [comment]
> hey everyone who got this issue here's whats happened in my scenario. the cause for this issue was that the emulator doesn't have the access to the internet , please make sure that you emulator has the network connection, that's the reason to display error "Network Error". Please make sure your emulator is displaying wifi icon.

I originally thumbed this down bc it seemed way out of left field and unrelated. But as I wrapped up my work for the night I unplugged my ethernet cable from my mac, and the issue disappeared. My ethernet works, and I'm on wifi, but it seems that for some unkown reason this call fails if my ethernet is plugged in.

**Comment by JonatanTrack** [comment]
Hello. I also have the same problem, but in our case we are using expo for react.native and when executing it with the command "expo start" and sending it to localhost, the problem works when we make the apk, the application does not work with wifi network, and if with a 4G mobile network, all queries to the database work.

**Comment by mikeRChambers610** [comment]
Is the amplify team looking into this issue?? If the phone has internet connection, why are we getting a network error from the auth.signup?

**Comment by renanbronchart** [comment]
I have the same error with cognito and with auth.signup().
I found the error only on android (not on ios).
I use react-native

The error : 
{"code": "NetworkError", "message": "Network error", "name": "Error"} #############signup Error#####################

**Comment by opqpop** [comment]
My issue was because I was on a VPN, and had been debugging for the past 4 hours making a lot of calls, so I suspect it decided to throttle me.

Amplify team, is there somewhere where I can read more about VPN throttling? Is it to counter against bots?

**Comment by hanselrios** [comment]
I fixed the error by calling event.preventDefault() at the beginning of my function before Auth.signIn()
