### ISSUE TITLE
is there a SEO solution?

### ISSUE THREAD

**Issue by littleone2018** [aws-amplify/amplify-js#2607]
does it support something like prerender.io?

**Comment by jonasao** [comment]
@littleone2018 forgive me, but why do you want to open a password-protected site/part of your site for search engine crawling?

**Comment by littleone2018** [comment]
@jonasao it is a quora like website, i have to...

**Comment by bkeating** [comment]
Currently I do it through `react-snap` and adjusting amplify.yml accordingly (you need to install/use headless google-chrome). It's got nothing to do with Amplify, though. I found this post on a search for something built into Amplify. Ideally; just let me use `react-helmet` and things work automagically.
