### ISSUE TITLE
Issue with signOut

### ISSUE THREAD

**Issue by Kedarnag13** [aws-amplify/amplify-js#2612]
I’m building authentication using Cognito which is written in NodeJS. The issue I’m facing is when I’m trying to signOut.

I’m using 

> amazon-cognito-identity-js, AWS Cognito

Here is my code snippet.

```
module.exports.destroy = (event, _context, callback) => {

  var userPoolData = {
    UserPoolId: 'xxxxxxxx',
    ClientId: 'xxxxxxx'
  };
  var userPool = new CognitoUserPool(userPoolData);
  
  const currentUser = userPool.getCurrentUser() // this is null, however it works in my local as I'm getting the currentUser, this value is popluated from localStorage, however, backend does not use localStorage, it uses memoryStorage. How would I go about getting the value?
  if (currentUser != null) {
    currentUser.signOut();
    AWS.config.credentials.clearCachedId();
    AWS.config.credentials = new AWS.CognitoIdentityCredentials({});
    return callback(null, {
      statusCode: 200,
      message: 'Logged out successfully!'
    });
  } else {
    return callback(null, {
      statusCode: 422,
      error: 'Session does not exist!' // in deployed environment, the request always comes here.
    });
  }
}
```
This is not a bug, it's a question I want help with, as I have been stuck with this for a while.

Appreciate the help.

**Comment by franzwong** [comment]
So what environment will this piece of code execute? Frontend or backend?

**Comment by Kedarnag13** [comment]
The signOut is handled on the backend, written in NodeJS

**Comment by franzwong** [comment]
`amazon-cognito-identity-js` is designed for frontend. It cannot serve multiple users concurrently. You should use `aws-sdk` for backend.

Btw, `amazon-cognito-identity-js` reads and writes to local storage. You can override that with the `Storage` property of the constructor parameter.

**Comment by Kedarnag13** [comment]
Yea, I actually understood that `amazon-cognito-identity-js` is for front-end and I'm going to using `aws-sdk` for the backend. Thank you for the clarification.

**Comment by jordanranz** [comment]
It seems your question was answered. Going to close this for now. Please reopen if you have any related questions or comments.
