### ISSUE TITLE
Module does not exist in the module map

### ISSUE THREAD

**Issue by Martyneris** [aws-amplify/amplify-js#2614]
**Describe the bug**
App crashes  after getting an error when trying to use either of  these imports : 

import Analytics from '@aws-amplify/analytics';
or
import Analytics from 'aws-amplify/analytics';

**To Reproduce**
I was following this guide step by step -> https://aws-amplify.github.io/docs/js/start?ref=amplify-rn-btn&platform=react-native

**Expected behavior**
App builds and a test Analytics record is being sent to amazon pinpoint service.

**Screenshots**
![screenshot 2019-01-28 at 18 28 28](https://user-images.githubusercontent.com/33836575/51850601-bbed4b00-232a-11e9-81a5-ac020f58c82b.png)

A sample snippet I was using : 

import Analytics from '@aws-amplify/analytics';
import Amplify from '@aws-amplify/core';
import aws_exports from './aws-exports';

Amplify.configure(aws_exports);

If I would remove the "import Analytics from '@aws-amplify/analytics';" import - app would build no problem.

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.1 
 - React Native : version": "0.50.0"
- @aws-amplify/api  version": "1.0.26"

**Comment by elorzafe** [comment]
@Martyneris  Did you installed @aws-amplify/analytics? or just @aws-amplify/api?

**Comment by Martyneris** [comment]
@elorzafe yes I did

**Comment by powerful23** [comment]
@Martyneris Hi are you still having this issue? If you do, can you do a check if you have `aws-sdk` in your `node_modules`?
