### ISSUE TITLE
Auth.currentUserInfo() not returning cognitoIdentityId [NEW]

### ISSUE THREAD

**Issue by juliohds** [aws-amplify/amplify-js#2616]
I am reopen this question: 

https://github.com/aws-amplify/amplify-js/issues/249

When Running Auth.currentUserInfo() is not returning the cognitoIdentityId it just says id: undefined

{ id: undefined,
username: 'ivan2',
attributes:
{ email_verified: true,
phone_number_verified: false,
phone_number: '+555555555555',
email: '*********@gmail.com' } }

We are using this function to get the userInfo on login

**Comment by elorzafe** [comment]
@juliohds You will see `id:undefined` if you don't have an identityPoolId configured on Amplify. I have tested both configurations (with/without identityPoolId) to confirm that.

**Comment by juliohds** [comment]
![sem titulo](https://user-images.githubusercontent.com/22122055/51865695-3b304e00-232e-11e9-86b7-a68fa07d6010.png)

**Comment by juliohds** [comment]
@elorzafe , thank you for answer.

So, i had test with identitypoolid configured, as you can see below.

What im confused, because my project teamate have a mac, and same code works on his computer. I had tested with 5 computer which 1 = Mac and 4 = windows, also all computer running same version of aws-amplify, and when i debbug, ALL response are ok, but id from identitypool is undefined.

FYI, in the console, i have one error: "STS is not a constructor", when im debbuging, amplify call "utils.js" from amplify, and when utils creating the constructor for type "sts", isn't work.

i hope anyone can help me coz i losing my mind ;D

![sem titulo](https://user-images.githubusercontent.com/22122055/51865744-5bf8a380-232e-11e9-8bbd-612d21190857.png)

Best regards.

**Comment by elorzafe** [comment]
@juliohds Maybe there is an issue with dependencies installed, can you double check aws-sdk version you are using? I recommend to not include aws-sdk as dependency because amplify already has a dependency for it.

**Comment by elorzafe** [comment]
@brunosallum do you have enabled tree shaking on parcel? are you using alias for module resolution?

**Comment by juliohds** [comment]
This question are resolved, problem happen when Parcel generate bundle.js. We are moving to WebPack and no had more error.
