### ISSUE TITLE
New version of React Native + withAuthenticator == funky background

### ISSUE THREAD

**Issue by dabit3** [aws-amplify/amplify-js#2618]
**Describe the bug**
The new version of React Native renders a black background when using the `withAuthenticator` HOC.

**To Reproduce**
1. Create new React Native project (0.58+).
2. Install Amplify + Amplify React Native libraries
3. Add amplify & auth category
4. Use the withAuthenticator HOC

**Expected behavior**
White background & normal UI shows up

**Screenshots**
<img width="383" alt="screen shot 2019-01-28 at 11 58 17 am" src="https://user-images.githubusercontent.com/1857282/51862975-b70da480-22f4-11e9-86e6-49cf95c6216a.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version: 
```
{
  "name": "randomrn",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "aws-amplify": "^1.1.19",
    "aws-amplify-react-native": "^2.1.7",
    "react": "16.6.3",
    "react-native": "0.58.2"
  },
  "devDependencies": {
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "24.0.0",
    "jest": "24.0.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - Version [e.g. 22] 10.1

**Additional context**
I tested this with older versions of React Native, as late as 0.57.8, & it worked fine.

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by manueliglesias** [comment]
A workaround for react-native >= 58

```
const theme = StyleSheet.create({
  ...AmplifyTheme,
  container: {
    ...AmplifyTheme.container,
    backgroundColor: '#FFFFFF'
  }
});
export default withAuthenticator(App, false, [], null, theme);
```

**Comment by tetreault** [comment]
This was great thanks @manueliglesias ! Does anyone have any recommendations on fixing the busted styling on iPhone X simulator?

<img width="437" alt="screen shot 2019-02-17 at 5 03 51 pm" src="https://user-images.githubusercontent.com/5934354/52920051-835fe200-32d6-11e9-8b69-7ced8097b301.png">
<img width="476" alt="screen shot 2019-02-17 at 5 03 46 pm" src="https://user-images.githubusercontent.com/5934354/52920052-835fe200-32d6-11e9-8cca-f042ada87322.png">

**Comment by mailyokesh** [comment]
Am seeing this in the latest version of react native vs the amplify react native library i installed today. Was any one able to get this fixed? also am noticing that the AmplifyTheme.js is not present inside node_modules/aws-amplify-react-native/src , its empty

**Comment by matt-paul** [comment]
Same issue here, not found a good fix yet
