### ISSUE TITLE
Logged in users can upload but not list files

### ISSUE THREAD

**Issue by marksteele** [aws-amplify/amplify-js#2619]
**Describe the bug**

I have a react app that is able to upload files to S3, however when trying to list files, the pre-flight OPTIONS request succeeds, but the actual list gets a 403.

The IAM role for the cognito user is:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "mobileanalytics:PutEvents",
                "cognito-sync:*",
                "cognito-identity:*"
            ],
            "Resource": "*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::dev-drop-bucket-files/private/${cognito-identity.amazonaws.com:sub}/*",
                "arn:aws:s3:::dev-drop-bucket-files/private/${cognito-identity.amazonaws.com:sub}"
            ],
            "Effect": "Allow"
        }
    ]
}
```

Here's a sample of the code that is what I'm using for the uploads/downloads:

```
import { Storage } from "aws-amplify";

export async function s3Upload(file) {
  Storage.configure({ level: 'private' });
  const stored = await Storage.vault.put(file.name, file, {
    contentType: file.type
  });

  return stored.key;
}
export async function listFiles() {
  Storage.configure({ level: 'private' });
  const files = await Storage.list('/');
  return files;
}
```

**Expected behavior**

List should return a list of files.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 71.0.3578.98

**Comment by manueliglesias** [comment]
Hi @marksteele 

Can you include some debug information?

I am particularly interested in this message, to see if the path is correctly formed:
```
logger.debug('list ' + path + ' from ' + final_path);
```

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by manueliglesias** [comment]
can you try:

```js
Storage.list('', {level: 'private'})
```

**Comment by marksteele** [comment]
Same result (a 403 response).

**Comment by jordanranz** [comment]
Hi @marksteele,

Could you try adding the "Condition" block located in this IAM sample code:
https://aws-amplify.github.io/docs/js/storage#using-amazon-s3

**Comment by powerful23** [comment]
Closing the issue. Please let us know if you still have this issue.

**Comment by sergi** [comment]
I'm having this exact issue, which I believe is also related to https://github.com/aws-amplify/amplify-js/issues/3034. Can you please reopen?

**Comment by Mitchell-Stone** [comment]
Is it possible for an update on this issue? I used the automated process to setup the S3 Storage. I can put, get and remove but not list.
