### ISSUE TITLE
Is it possible to add identity pool credentials to axios?

### ISSUE THREAD

**Issue by enzo-beltrami** [aws-amplify/amplify-js#2622]
** Which Category is your question related to? **
API calls with cognito
** What AWS Services are you utilizing? **
API gateway && cognito identity pools
** Provide additional details e.g. code snippets **
I want to be able to call my api without using the API module of amplify, is it possible? i'm already using axios and i'm migrating the old code to amplify and if i could add the identity pool credentials to axios it would save me a lot of work.

**Comment by manueliglesias** [comment]
Hi @enzo-beltrami 

Yes, it is possible but it might not be straight-forward, you need to sign your requests using the credentials.

Your best bet would be to directly use [Amplify's sigv4 signer](https://github.com/aws-amplify/amplify-js/blob/master/packages/core/src/Signer.ts)

Some additional resources:

- https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html
- [aws-sdk sigv4 signer](https://github.com/aws/aws-sdk-js/tree/cc29728c1c4178969ebabe3bbe6b6f3159436394/lib/signers)
