### ISSUE TITLE
Scroll listener causing jank

### ISSUE THREAD

**Issue by blainekasten** [aws-amplify/amplify-js#2623]
**Describe the bug**
Your scroll listener causes scroll-jank on lower powered android devices. For one, I'm not sure why an auth library needs to track scroll behavior. But at the very least, the scroll listener should be a passive listener.

https://github.com/aws-amplify/amplify-js/blob/master/packages/core/src/ClientDevice/browser.ts#L97

https://developers.google.com/web/updates/2016/06/passive-event-listeners

**Comment by manueliglesias** [comment]
Thank you for the report @blainekasten 

I am labeling this issue as a bug.

I couldn't find where this is used, so I think it should be removed, or at the very least improved

**Comment by jordanranz** [comment]
This could be resolved with the Hub refactor: https://github.com/aws-amplify/amplify-js/issues/2669
