### ISSUE TITLE
How could I reference AuthenticationDetails, CongintoUser, CognitoUserAttribute from aws-amplify

### ISSUE THREAD

**Issue by JiajiSun** [aws-amplify/amplify-js#2625]
** Which Category is your question related to? **

Referencing issue

** What AWS Services are you utilizing? **

Authentication

** Provide additional details e.g. code snippets **

ERROR in node_modules/@aws-amplify/auth/node_modules/amazon-cognito-identity-js/index.d.ts(5,17): error TS2300: Duplicate identifier 'NodeCallback'.
node_modules/@aws-amplify/auth/node_modules/amazon-cognito-identity-js/index.d.ts(28,18): error TS2300: Duplicate identifier 'AuthenticationDetails'.
node_modules/@aws-amplify/auth/node_modules/amazon-cognito-identity-js/index.d.ts(49,18): error TS2300: Duplicate identifier 'CognitoUser'.
node_modules/@aws-amplify/auth/node_modules/amazon-cognito-identity-js/index.d.ts(126,18): error TS2300: Duplicate identifier 'CognitoUserAttribute'.
node_modules/@aws-amplify/auth/node_modules/amazon-cognito-identity-js/index.d.ts(150,18): error TS2300: Duplicate identifier 'CognitoUserPool'.
node_modules/@aws-amplify/auth/node_modules/amazon-cognito-identity-js/index.d.ts(167,18): error TS2300: Duplicate identifier 'CognitoUserSession'.
node_modules/@aws-amplify/auth/node_modules/amazon-cognito-identity-js/index.d.ts(180,18): error TS2300: Duplicate identifier 'CognitoAccessToken'.
node_modules/@aws-amplify/auth/node_modules/amazon-cognito-identity-js/index.d.ts(191,18): error TS2300: Duplicate identifier 'CognitoIdToken'.
node_modules/@aws-amplify/auth/node_modules/amazon-cognito-identity-js/index.d.ts(202,18): error TS2300: Duplicate identifier 'CognitoRefreshToken'.
node_modules/@aws-amplify/auth/node_modules/amazon-cognito-identity-js/index.d.ts(214,18): error TS2300: Duplicate identifier 'CookieStorage'.
node_modules/amazon-cognito-identity-js/index.d.ts(5,17): error TS2300: Duplicate identifier 'NodeCallback'.
node_modules/amazon-cognito-identity-js/index.d.ts(28,18): error TS2300: Duplicate identifier 'AuthenticationDetails'.
node_modules/amazon-cognito-identity-js/index.d.ts(49,18): error TS2300: Duplicate identifier 'CognitoUser'.
node_modules/amazon-cognito-identity-js/index.d.ts(126,18): error TS2300: Duplicate identifier 'CognitoUserAttribute'.
node_modules/amazon-cognito-identity-js/index.d.ts(150,18): error TS2300: Duplicate identifier 'CognitoUserPool'.
node_modules/amazon-cognito-identity-js/index.d.ts(167,18): error TS2300: Duplicate identifier 'CognitoUserSession'.
node_modules/amazon-cognito-identity-js/index.d.ts(180,18): error TS2300: Duplicate identifier 'CognitoAccessToken'.
node_modules/amazon-cognito-identity-js/index.d.ts(191,18): error TS2300: Duplicate identifier 'CognitoIdToken'.
node_modules/amazon-cognito-identity-js/index.d.ts(202,18): error TS2300: Duplicate identifier 'CognitoRefreshToken'.
node_modules/amazon-cognito-identity-js/index.d.ts(214,18): error TS2300: Duplicate identifier 'CookieStorage'.

As you can see above, since amazon-cognito-identity-js is included in the aws-amplify, how could I reference some of the things that I want to use to create custome register for users in the amazon-cognito-identity-js in my application

**Comment by manueliglesias** [comment]
Hi @JiajiSun 

Looks like you have some duplicated packages in your project.

Ideally, you wouldn't need to directly use the `amazon-cognito-identity-js` package, since Amplify's auth category is much easier to use. (let us know if you really need amazon-cognito-identity-js and what is missing in Amplify so we can improve it)

If you really want to use the `amazon-cognito-identity-js` in your code, I would suggest you first make sure it is not duplicated in your project. (e.g. by pinning the version in your package.json to match the version used by amplify)

**Comment by JiajiSun** [comment]
Hi @manueliglesias,

Thanks for the quick reply, I am trying to register another user in cognito after an authorized user is logged in (after registration, not switch the current authorized user to the new user). It seems that amplify doesn't have that function. Let me know if I am wrong about that.
Sure, I will check and match the version of amazon-cognito-identity-js.
