### ISSUE TITLE
403 on APIGateway with identity pool

### ISSUE THREAD

**Issue by enzo-beltrami** [aws-amplify/amplify-js#2626]
My env:
- I have an identity pool setup(federated Sign in with Google) 
- The api gateway is expecting AWS_IAM
- The OPTIONS method works fine.
- Amplify version: 1.1.19
- I'm using React
- Cloudwatch wont log anything other than the options method being completed with 200

Amplify config:
```
Amplify.configure({
		Auth: {
			identityPoolId: 'us-east-1:*****************',
			region: 'us-east-1',
			mandatorySignIn: true,
		},
		API: {
			endpoints: [{
                              name: 'myApi',
                              endpoint: 'https://myurl.apigateway/prod',
		              region: 'us-east-1',
                         }]
		},
	});
```
When  i try to make the request i get 403 with no response and CORS issue.

I tried to fake the request with postman and i get:
```
{"message":"The security token included in the request is invalid."}
```
The Authorization Header has an "undefined" under the Credentials (idk if that is causing the issue)
```
Authorization: AWS4-HMAC-SHA256 Credential=undefined/*******/us-east-1/execute-api/aws4_request, SignedHeaders=host;x-amz-date, Signature=**********************************************************
```

And there is the SignedHeaders, there is no host header on the request

Looking at my identity pool on AWS i can find my identity on identity browser but there are 0 identities on the dashboard...

**Comment by enzo-beltrami** [comment]
Looks like the problem was some old code using AWS NodeJS SDK to connect to cognito.

**Comment by manueliglesias** [comment]
Thank you for letting us know, I am closing the issue.
