### ISSUE TITLE
Better error messages for debugging Auth issues

### ISSUE THREAD

**Issue by undefobj** [aws-amplify/amplify-js#2629]
**Is your feature request related to a problem? Please describe.**
When using AppSync configured with IAM, if you make a mistake and leave the `aws_appsync_authenticationType` configuration as `AMAZON_COGNITO_USER_POOLS` you will get an error of `No current user` when invoking `API.graphql()`. This error is not descriptive for customers during the debugging process.

**Describe the solution you'd like**
A more descriptive error message with information for customers to check, something like:
"No user detected. API category currently configured for `${authtype}` on `${endpoint}` in `${region}`

We should evaluate how we could do this generically in different categories, but specifically using Auth in context of the API, Storage, and PubSub categories.

cc @dabit3

**Comment by undefobj** [comment]
Related: https://github.com/aws-amplify/amplify-js/issues/1252

**Comment by sammartinez** [comment]
Closing this issue in favor of #2839
