### ISSUE TITLE
Connect component not exported (aws-amplify-vue)

### ISSUE THREAD

**Issue by mrname** [aws-amplify/amplify-js#2633]
**Describe the bug**
When following the documentation for `aws-amplify-vue`, I am unable to use the `<amplify-connect>` component. This is due to the fact that it is not exported from the top level of the module. Not certain as to whether this is an issue with the exports or just out of date documentation.

**To Reproduce**
1. Follow the configuration instructions at https://aws-amplify.github.io/docs/js/vue#configuration
2. Attempt to use the `<amplify-connect>` component as described at https://aws-amplify.github.io/docs/js/vue#connect
3. Console will reveal the following error:

```
Unknown custom element: <amplify-connect> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

**Expected behavior**
The Connect component should be able to be imported as described in the documentation OR the documentation should specify how to import this component properly.

**Desktop (please complete the following information):**
 - OS: iOS (Mac)
 - Browser chrome
 - Version 71.0.3578.98

**Additional context**
I edited the `index.js` files locally, adding the proper imports and exports and things seemed to be working for me, so let me know if a pull request would be appropriate.

**Comment by manueliglesias** [comment]
Thank you @mrname 

I've labeled this as a bug for follow-up, also:

> so let me know if a pull request would be appropriate.

We always welcome PRs 😄

**Comment by haverchuck** [comment]
@mrname I've merged a fix for this into our unstable build (npm i aws-amplify-vue@unstable).  It should be available on the main build in the near future.

Closing this issue for now; please feel free to reopen.
