### ISSUE TITLE
[React] Amplify Custom Component override option hides default SignUp link

### ISSUE THREAD

**Issue by pippo111** [aws-amplify/amplify-js#2640]
**Describe the bug**
When trying to override React Component as stated in https://aws-amplify.github.io/docs/js/authentication#customize-ui link to Sign Up is missing, which requires to add custom text.

**To Reproduce**
1. Create Authenticator Component like so:
```
import { Authenticator, SignUp, SignIn } from 'aws-amplify-react';

<Authenticator hideDefault={true}>
  <SignIn />
  <MyCustomSignUp override={SignUp}/> {/* to tell the Authenticator the SignUp component is not hidden but overridden */}
</Authenticator>
```
2. Open page with auth form

**Expected behavior**
Default SignIn form should appear with "No Account ? Create One" link.

**Screenshots**
![image](https://user-images.githubusercontent.com/22401020/52050369-a5c0d400-2550-11e9-8715-41ac95078378.png)

![image](https://user-images.githubusercontent.com/22401020/52050377-aeb1a580-2550-11e9-94ae-ab081899091e.png)

**Desktop (please complete the following information):**
 - OS: Linux Solus
 - Browser Chrome
 - Version 67

**Comment by jordanranz** [comment]
Hi @pippo111,

It looks like the documentation may be incorrect here. Can you try changing `override={SignUp}` to use a string instead like: `<MyCustomSignUp override={'SignUp'} />`

Let me know if that works. Based on your response we can either improve the documentation or improve the actual code driving this.

**Comment by pippo111** [comment]
Hi @jordanranz 

Yes, changing override to use a string fixed the issue, so it seems that documentation is in fact incorrect here. Thank you.

**Comment by jordanranz** [comment]
No problem, I'll go ahead and fix the documentation. Going to close this now. Please reopen this if you run into any related issues.

**Comment by dtelaroli** [comment]
The API doesn't have override anymore.
I want change the form with email confirmation field, but after 3 days loosing time, I need help:

https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Auth/SignUp.tsx

The button disappears if I hide SignUp with configuration.

**Comment by dtelaroli** [comment]
@jordanranz this option does not exists

I want to add a email and password confirmation fields, but I can't override component:

<img width="1038" alt="Screen Shot 2020-02-26 at 13 20 27" src="https://user-images.githubusercontent.com/536500/75367088-80f77700-589e-11ea-99fc-ce075f8c97c3.png">
