### ISSUE TITLE
Verified user always prompted to enter verification code

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [aws-amplify/amplify-js#2642]
I have set up a user pool requiring email verification. After signing up, I've got the code and  verified the user. It should up as verified in the Cognito console, as well as when queries via AWS CLI. The CognitoUser object in amplify, however, lists the email as an unverified attribute.

What I found out so far is that `Auth.verifiedContact` checks the user attribute `email_verified`, but this attribute is not present in the userAttributes object. Here again, i see the attribute when getting the user via AWS CLI.

This could also be related to #2608

**Comment by OrangeDrangon** [comment]
To be able to see that with `userAttributes` I had to set the attribute to readable. Under `User Pools > App Clients > Show Details > Set attribute.read and write permissions

**Comment by BlackbitNeueMedien** [comment]
Thanks you, that solves the problem for me as well. In hindsight, that even makes a lot of sense.

I think that the Amplify CLI should list `email_verified` as a readable attribute by default if you choose to use email verification.

**Comment by powerful23** [comment]
@BlackbitNeueMedien I am going to close this issue as the issue has been resolved. Feel free to reopen if you still have this issue. Also if you want to send any request to the amplify-cli, you can go to the repo and open an issue: https://github.com/aws-amplify/amplify-cli  Thanks!

**Comment by revmischa** [comment]
> I think that the Amplify CLI should list email_verified as a readable attribute by default if you choose to use email verification.

I super super agree with this. This is an implementation detail leaking out

**Comment by undefobj** [comment]
@revmischa @BlackbitNeueMedien could you please open a Feature Request in the CLI repo so that team can track your request? Thank you.
