### ISSUE TITLE
Feature Request: Allow adding custom link/script tags to the head of the hosted page

### ISSUE THREAD

**Issue by alshdavid** [aws-amplify/amplify-js#2644]
It's unfortunate that we are unable to customise the HTML of the hosted page. 

Allowing developers the ability to add custom `<script>` or `<link>` tags would address this as we could augment the existing html.

**Comment by manueliglesias** [comment]
Hi @alshdavid 

One of the benefits of using hosted pages for login is that the pages offer some protection for common attacks (CSRF, XSS, etc); this is partially achieved by having control of the scripts running in the page. I would assume that having the option to allow arbitrary scripts would hinder those efforts.

If you need more flexibility, have you consider using the Amplify HOC (`withAuthenticator`) or implementing your own UI by interacting directly with the library? (e.g. `Auth.signIn(username, password`)

**Comment by alshdavid** [comment]
Does that mean your suggestion is to reimplement the sign in page using the JavaScript library - say, by hosting an html page on S3, implementing the oauth flow redirects and calling cognito functions directly

**Comment by manueliglesias** [comment]
@alshdavid I think using `withAuthenticator` would be the starting point. You can also customize it, see [Customize UI](https://aws-amplify.github.io/docs/js/authentication#customize-ui)

**Comment by undefobj** [comment]
Hello everyone, we have created an RFC for feature work that should make the challenges found in this issue easier in the future. If you have a moment please read through the details and add any comments: https://github.com/aws-amplify/amplify-js/issues/2716

Your feedback in the RFC will help us ensure that we are delivering the best experience possible. Thank you.

**Comment by powerful23** [comment]
Closing this issue.  You can make your own UI and use `Auth.federatedSignIn` to do the OAuth flow. Please check the doc: https://aws-amplify.github.io/docs/js/authentication#oauth-and-hosted-ui
