### ISSUE TITLE
Android-only, <Authenticator> + react-navigation navigator crash

### ISSUE THREAD

**Issue by paulreimer** [aws-amplify/amplify-js#2652]
**Describe the bug**
Adding the `<Authenticator>` component to an existing app already using `react-navigation`'s `createDrawerNavigator`, does not display the navigator content on Android (E.g. none of the app screens are displayed). The authenticator login pieces (`SignIn`, `SignUp` flow etc) are there, but after a valid `"signedIn"` event, the wrapped content does not display (`<Greetings />` does get displayed, so that's extra weird).

Everything works correctly as expected on iOS -- simulator and real device -- so I think this is an Android specific issue. As well, without `<Authenticator>`, the navigator worked fine on Android.

If I change the navigator type from drawer to `createSwitchNavigator`, then it works on Android (although this is not the type of navigator I want). All other navigator types are broken within the `<Authenticator>`.

As well, using a simple `<Text>` within `<Authenticator>`, instead of a navigator, does work fine.

Finally, trying to inspect the issue in `react-devtools` with the inspector, if I drill down into the first `<View>` within the `<Authenticator>`, as soon as I even hover over it, RN crashes with an `Invariant violation`.

**To Reproduce**
The following is a `react-native` top-level App component that fails when `createStackNavigator` or `createDrawerNavigator` is used, but works only with `createSwitchNavigator`.

```
class SimpleContent extends Component {
  render() {
    return <Text>WTF</Text>;
  }
}

// This "works":
// const AppContent = createSwitchNavigator(

// Does not display content, crashes in DevTools.
const AppContent = createStackNavigator(
  {
    AppContent: {screen: SimpleContent},
  },
  {
    initialRouteName: "AppContent",
  }
);


// This "Works":
//export default () => (
//  <Authenticator>
//    <SimpleContent />
//  </Authenticator>
//);

export default () => (
  <Authenticator>
    <AppContent />
  </Authenticator>
);
```

**Expected behavior**
I expected my navigator content to be displayed after the `<Greetings />` component (and to match behaviour on iOS which is working correctly).

**Smartphone (please complete the following information):**
 - Device: Android Emulator, Nexus 5 (or a real device, Samsung S4)
 - API Version: 27

**Comment by bng-dev** [comment]
Hi @paulreimer
Did you find a solution for this?
I'm struggling with the same issue, and I can't find any explanation.

**Comment by rawadrifai** [comment]
@paulreimer @bng-dev did you guys find a solution for this?
