### ISSUE TITLE
Users are able to sign up without giving a value for "required attributes".

### ISSUE THREAD

**Issue by TamsynJennifer4** [aws-amplify/amplify-js#2653]
**Describe the bug**
Users are able to sign up without giving a value for "required attributes." 

**To Reproduce**
1. Amplify init
2. Amplify add auth (mark some standard attributes as required e.g. family_name)
3. Write your signup code. e.g.

        signUp = async () => {
	      const { lastName, email, password } = this.state;
		   try {
			   await Auth.signUp({
			 	username: email,
			 	password,
			 	attributes: {
			 		email,
					given_name: firstName,
					family_name: lastName,
					birthdate
	 			}
		 	});
	 	    } 
        }
4. Check your standard attributes are marked as required in the Cognito console: 
<img width="975" alt="screen shot 2019-02-02 at 15 42 58" src="https://user-images.githubusercontent.com/32341857/52166761-65588600-2709-11e9-9533-732f59a19ce3.png">

5. Sign up with your username/email and password but don't give any value for your required standard attribute/s.

6. Check the console to see you have successfully registered without giving the required values.

**Expected behavior**
A user should not be able to register/ sign up if they have not given a value for the required attributes.
"When a standard attribute is marked as required, a user cannot register unless a value for the attribute is provided."

**Screenshots**
A side by side example of two users in the Cognito console. (one has given a value for all the required attributes and the other user has left the family_name and birthdate empty and has still managed to register.)
<img width="1091" alt="screen shot 2019-02-02 at 15 19 40" src="https://user-images.githubusercontent.com/32341857/52166802-fb8cac00-2709-11e9-97ab-06c5d6f25ef1.png">

**Desktop (please complete the following information):**
 - OS: macOS HighSierra

**Smartphone (please complete the following information):**
 - Device: iPhone X simulator

**Additional context**

**Comment by jordanranz** [comment]
This has been brought up to the Cognito service team as the API should not allow registration without required fields. They will be tracking it as a bug fix. We will update this as soon as progress has been made. 

In the meantime, you can perform validation on the application side.

Thank you for submitting this feedback.
