### ISSUE TITLE
Typescript quickstart errors

### ISSUE THREAD

**Issue by revmischa** [aws-amplify/amplify-js#2655]
If you simply try to use `create-react-app --typescript` with amplify and then start a new amplify project, here is what you encounter:

https://github.com/aws-amplify/amplify-js/issues/2365
https://github.com/aws-amplify/amplify-js/issues/1028
https://github.com/aws-amplify/amplify-js/issues/2073
And https://github.com/aws-amplify/amplify-js/issues/1938 - somehow this isn't installed automatically

Just try making a new amplify project with auth and graphql with CRA/TS. You will have to google and fix these problems to get anywhere. I'm stuck on #2365 and can't move forward.

**Comment by revmischa** [comment]
Dunno, is it fixed?

**Comment by buggy** [comment]
I'd be in favor of closing this issue. It doesn't add anything that the other 4 issues don't already cover.

**Comment by jordanranz** [comment]
Closing this in favor of: https://github.com/aws-amplify/amplify-js/issues/1028
