### ISSUE TITLE
Using RespondToAuthChallenge in React Native 

### ISSUE THREAD

**Issue by zohaibahmed-22** [aws-amplify/amplify-js#2661]
** Which Category is your question related to? **
React Native, AWS-Amplify-sdk
** What AWS Services are you utilizing? **
AWS cognito service
** Provide additional details e.g. code snippets **
```
"aws-amplify": "^1.1.19"
"react": "16.7.0",
"react-native": "0.58.1",

```

## Scenario

- We created a user pool with advanced security enabled
- When a risk is reported we set to `Require MFA`
- We are able to receive the verification code in SMS but not able to apply them using any methods in `aws-amplify`
- In Response of `SignIn` method i get challengename and challengeParam how i can respond to that challenge 
- Is there a way to use the JS method `RespondToAuthChallenge ` in mobile ?

@anandwahed

**Comment by anandwahed** [comment]
We were able to resolve this issue using the `Auth.confirmSignIn` with respective parameters. This [link](https://aws-amplify.github.io/docs/js/authentication#sign-in) has more details on the same.
