### ISSUE TITLE
Authenticate ReactJS app as admin using Cognito

### ISSUE THREAD

**Issue by amirklick** [aws-amplify/amplify-js#2663]
If using Cognito for authentication, how can we have the ReactJS app make API (lambda) calls as an admin. For example if we want to secure the registration endpoint so that only the application can call it. Prior to switching to Cognito, we'd generate an admin token to include in the request and verify it using a custom authorizer.

Can we use Amplify to get/generate an "admin" token (token for a specific user)?

Currently having trouble generating a token using `jsonwebtoken` package when running code below:
`const token = jwt.sign(tokenPayload, tokenSecret, { algorithm: 'RS256' });`
(where `tokenSecret` is a public key, same one from our Cognito endpoint)

If I don't include the `algorithm` option it works, but then the server is unable to `verify` saying `invalid algorithm`. Which makes sense because algorithm on server is `RS256` and from my understanding, `jwt.sign` uses `HS256` by default.

But when I do include the `algorithm` option, `jwt.sign` throws an error saying `Cannot read property 'isZero' of undefined` caused by the `bn` package which I assume is a dependancy of dependancies of `jsonwebtoken`.

Any ideas? Is there another or better way?

**Comment by undefobj** [comment]
The recommended way to do this would be to execute the Lambda function via API Gateway or AppSync as part of the `API` category in Amplify, that way you can have user authorization to your public API and system authorization from the API->Lambda function.

It seems from your statement above you might be using API Gateway, in which case you shouldn't have to generate a token. Instead your client can retrieve either a JWT token from Cognito User Pools or AWS Credentials from Cognito Identity when leveraging the `Auth` category of Amplify, and you can set your API authorization type to either `AWS_IAM` or a Cognito User Pool Authorizer. It might be worth walking through the example here: https://aws-amplify.github.io/docs/js/api#using-rest

However, if you'd rather go an opposite direction from the best practice above you can invoke any AWS service directly from Amplify (including Lambda) as outlined in the "AWS SDK Interfaces" section here: https://aws-amplify.github.io/docs/js/start#step-5-host-your-app

The example above shows Route53 but Lambda will be similar. The client will retrieve AWS credentials from Cognito Identity Pools when `Auth.currentCredentials()` is called, so for these credentials to invoke a Lambda function you'll need to ensure that the IAM policy for that Cognito role has `"Action": "lambda:InvokeFunction"` (or whatever other actions you want to allow).

**Comment by amirklick** [comment]
@undefobj Thanks for the response. Yes I'm using API Gateway with a custom authorizer that generates a user (if valid token) or a guest (invalid or no token) policy. This setup is for a GraphQL API.

How can I get a JWT token from my Cognito User Pool? The examples I've found all show the use case of authenticating a user that has logged in and has tokens, not authenticating your app.

**Comment by undefobj** [comment]
Tokens are provided when you call `Auth.signIn` https://github.com/aws-amplify/amplify-cli/issues/766 or you can optionally use one of the React components which leverage this behind the scenes: https://aws-amplify.github.io/docs/js/authentication#using-components-in-react--react-native

**Comment by amirklick** [comment]
Using `Auth.signIn` would work but that would log the user in as an admin, at which point you could grab the token from `localStorage` and now you have admin access! Also not sure it's a good idea to have admin user and pass on the client.

The frontend just needs to generate a token that can be verified against the Cognito secret.
