### ISSUE TITLE
Amplify Console: Domain name displayed improperly

### ISSUE THREAD

**Issue by nagey** [aws-amplify/amplify-js#2666]
**Describe the bug**
On both `"All Apps > ${appName}"` and `"All Apps > ${appName} > ${branchName}"` the field for "Domain" is displaying improperly when a custom domain is configured.

**To Reproduce**
1. Go to the amplify console
2. Click on your app name
3. Scroll down to the details for any branch
4. See domain displayed as `https://${branchName}.${customDomain}` (which may or may not be correct), rather than either `https://${branchName}.${amplifyAppId}.amplifyapps.com` or `https://${customDomainMappingForBranch}`

**Expected behavior**
The branch block and branch detail both should display the domain name / link url as one of  `https://${branchName}.${amplifyAppId}.amplifyapps.com` or `https://${customDomainMappingForBranch}`

The former probably makes more sense, as it does not rely on a user having their domain properly configured yet. The appropriate links appear in `All Apps > ${appName} > App settings: Domain management`

**Comment by swaminator** [comment]
@nagey thanks for reporting. We will have a fix shortly and get back to you.

**Comment by swaminator** [comment]
We rolled out a fix last week. please verify if it works for you.

**Comment by nagey** [comment]
appears to be working now. Thank you.

**Comment by jordanranz** [comment]
I'll go ahead and close this for you. In the future please open Amplify Console issues in the AWS Forum [here](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0).

Thank you @swaminator for helping solve the issue.
