### ISSUE TITLE
React module error: Cannot find module './recorder.js'

### ISSUE THREAD

**Issue by flibbertigibbet** [aws-amplify/amplify-js#2668]
**Describe the bug**
Cannot serve React project. Get error: `Error: Cannot find module './recorder.js' from '/usr/local/src/node_modules/aws-amplify-react/dist/Interactions'`

**To Reproduce**
1. Add `aws-amplify` and `aws-amplify-react` to project dependencies
2. Configure amplify for project
3. Add imports and call to `Amplify.configure(awsmobile)` for app
4. Attempt to build and serve
5. Get server error above

**Expected behavior**
Project should serve without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/960264/52364618-aefbe600-2a13-11e9-827b-d731d2f38ea3.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: `aws-amplify` 1.1.19 `aws-amplify-react` 2.3.0

**Additional context**
When voice interactions were added, they included a [reference here](https://github.com/aws-amplify/amplify-js/commit/938d2a5a6617867f62711b97a045b7e266749750#diff-7d71ccf95ac393359ace8d610ceffd56R18) to a non-extant `recorder.js` file.

**Comment by elorzafe** [comment]
@flibbertigibbet are you using a globally installed amplify? `/usr/local/src/node_modules/aws-amplify-react/dist/Interactions` that doesnt look like a project installation.

**Comment by flibbertigibbet** [comment]
It's a project installation inside of a Docker container.

**Comment by chadgarlandscg** [comment]
Since upgrading from aws-amplify 1.1.6 and aws-amplify-react 2.0.7, I'm also seeing this issue. I've tried aws-amplify-react 2.3.0, 2.3.1, and now 2.3.2, but have faced this with each version.

I had to upgrade in order to use these changes: https://github.com/aws-amplify/amplify-js/issues/2424

For me, there is a handful of others errors also present:
```{ Error: Cannot find module './recorder.js' from '/Users/scottgarland/Documents/GitHub/booster-web/node_modules/aws-amplify-react/dist/Interactions'```
```{ Error: Cannot find module './control.js' from '/Users/scottgarland/Documents/GitHub/booster-web/node_modules/aws-amplify-react/dist/Interactions'```
```{ Error: Cannot find module './conversation.js' from '/Users/scottgarland/Documents/GitHub/booster-web/node_modules/aws-amplify-react/dist/Interactions'```
```{ Error: Cannot find module './worker.js' from '/Users/scottgarland/Documents/GitHub/booster-web/node_modules/aws-amplify-react/dist/Interactions'```
```{ Error: Cannot find module 'webworkify' from '/Users/scottgarland/Documents/GitHub/booster-web/node_modules/aws-amplify-react/dist/Interactions'```

**Comment by flibbertigibbet** [comment]
I've been able to work around this with [modular imports](https://aws-amplify.github.io/docs/js/authentication#using-modular-imports) to avoid bringing in the full library.

**Comment by sceptyk** [comment]
I see this error only when running unit tests with cypress. Integration tests and usual rendering in the browser run ok.

Error:
Cannot find module './recorder.js' from '(app_dir)\node_modules\aws-amplify-react\dist\Interactions'

Versions:
aws-amplify:  1.1.22
aws-amplify-react: 2.3.2

**Comment by flibbertigibbet** [comment]
Anything that imports `aws-amplify-react/src/Interactions/aws-lex-audio.js` would encounter these missing relative file references.
