### ISSUE TITLE
Customize amplify-react Greetings className not update to Nav #help wanted

### ISSUE THREAD

**Issue by tonginbox** [aws-amplify/amplify-js#2672]
Cognito, AWS Amplify-Js, AWS Amplify-React

I want to make MyGreetings component base on the standard Greetings. They are using the same components NavBar, Nav, NavRight from 'aws-amplify-react'. However, MyGreetings style cannot receive className from the AmplifyUI then it render differently when compare to the standard Greetings component.

This is MyGreetings
```javascript
import React, { Component } from 'react'
import { Greetings } from 'aws-amplify-react'
import { NavBar, Nav, NavRight } from 'aws-amplify-react'

export default class MyGreetings extends Greetings {
    constructor(props) {
        super(props);
    }
    render() {
        const authState  = this.props.authState || this.state.authState;
        const signedIn = (authState === 'signedIn');

        const theme = this.props.theme;
        const greeting = signedIn? this.userGreetings(theme) : this.noUserGreetings(theme);
        if (!greeting) { return null; }

        return (
            <NavBar theme={theme}>
                <Nav theme={theme}>
                    <NavRight theme={theme}>
                        {greeting}
                    </NavRight>
                </Nav>
            </NavBar>
        );
    }
}
```

After ```npm start``` then inspect the ```NavBar``` this is the html. The ```<div class='amplify-nev-bar'...>``` didn't get replace by the complied class name. Therefore, it didn't render in the correct position.

![image](https://user-images.githubusercontent.com/6760124/52400796-b7771e00-2af2-11e9-94fd-3775df144076.png)

How can I make MyGreetings to receive the className after the component build?

**Comment by jordanranz** [comment]
Hey @tonginbox,

I am bit confused with what you are asking. I understand you would like to use your own Greetings component extended from the Amplify React Greetings component. Are you trying to apply custom class names to the elements inside of your MyGreetings component? And is this in addition the the existing classes already applied to the elements.

It seems odd that the classnames of the navbar, nav, and navright are what they are in the screenshot. Which version of aws-amplify-react are you using?

**Comment by tonginbox** [comment]
@jordanranz 
this is the version
```
  "dependencies": {
    "aws-amplify": "^1.1.19",
    "aws-amplify-react": "^2.3.0",
    "aws-api-gateway-client": "^0.2.16",
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "react-router-dom": "^4.3.1",
    "react-scripts": "2.1.3"
  },
```
I don't want to customize classnames of MyGreetings and what I want is the MyGreetings should get the classnames from or similar to the Greetings component but it doesn't. As you can see in the screen short on my first post the navbar, nav and navright classnames seem to be incorrect on MyGreetings.

How can I make MyGreetings getting the right classnames generated by aws-amplify-react?

For references, the following screenshot is classnames from Greetings. Those navbar, nav and navright classnames are correct.

![image](https://user-images.githubusercontent.com/6760124/52454883-323a4a80-2b80-11e9-87c7-ca79f2f8d368.png)

**Comment by jordanranz** [comment]
Ok, I understand what you are trying to do.

Instead of:
`import { NavBar, Nav, NavRight } from 'aws-amplify-react'`

Try:
`import { NavBar, Nav, NavRight } from 'aws-amplify-react/dist/Amplify-UI/Amplify-UI-Components-React';`

We are still in the process of cleaning/migrating up our UI components for this level of customization. So this is not officially supported yet. You will soon be able to use:
`import { NavBar, Nav, NavRight } from 'aws-amplify-react'`

**Comment by tonginbox** [comment]
@jordanranz it works perfectly and noted on the official support.

Thanks a lot for your help.

**Comment by jordanranz** [comment]
Glad that worked. I am going to keep this open to be tracked by our UI Component refactor milestone.

**Comment by jordanranz** [comment]
FYI, we have started an RFC discussion for a proposed Amplify UI Component refactor to increase customizability and flexibility for our components. Please feel free to add any additional comments to the following issue:

https://github.com/aws-amplify/amplify-js/issues/3279

**Comment by ashika01** [comment]
Closing this on base of our UI component refactor being completed with greetings component and styling of the component done using CSS vars. [More info](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#greetings)

For customization improvements and other suggestion with the new UI components. Please feel free open up a new issue or feature request.
