### ISSUE TITLE
forgot_password in Cognito without send verificationCode??

### ISSUE THREAD

**Issue by apradillap** [aws-amplify/amplify-js#2676]
**Which Category is your question related to?** 
forgot_password

**What AWS Services are you utilizing?**
Cognito

**Provide additional details e.g. code snippets**
Is it possible call to forgot password flow for an authenticated user without send verificationCode?

Thanks!!

**Comment by haverchuck** [comment]
@apradillap  It is possible to call ChangePassword for authenticated users, but they need to actually know their current passwords.  If they've authenticated and THEN forgotten their password, then I believe that the verificationCode will need to be used.
