### ISSUE TITLE
Dispatch `signedIn` in custom UI with Authenticator

### ISSUE THREAD

**Issue by ngocketit** [aws-amplify/amplify-js#2683]
Hi,

I'm building a totally custom UI and wanna use it under `Authenticator` in order to capture the authState change. Basically, the code structure is like so:
```
 <Authenticator hideDefault={ true }>
    <UserSignInSignUp t={ t }
      showLoader={ showLoader }
      loader={ loader }
    />
    <Protected>
      { children }
    </Protected>
  </Authenticator>
```

Th `UserSignInSignUp` component is where all the logics for handling signin, signup, password recovery etc happens. I'm not using any of the standard Amplify components that inherit from `AuthPiece`. Instead, I use Amplify Auth APIs (such as `signIn`, `signOut` etc) on top of my custom UI. Now, inside the `UserSignInSignUp` component, when user clicks a button, I call `Auth.signIn` and capture the result. If success, I want to dispatch the `signedIn` state so that Authenticator can catch it and pass it to its child components. `Authenticator` component receives `signedIn` state if I refresh the page after a successful signin. What's the proper way of doing that right after a login success without refreshing the page?

Thank you!

**Comment by ngocketit** [comment]
Currently I'm extending `Authenticator` and overriding `onHubCapsule` and call its `checkUser` for any events in `auth` channel:

```
class CustomAuthenticator extends Authenticator {
  onHubCapsule(capsule) {
    const { channel, payload, source } = capsule;
    if (channel === 'auth') {
      this.checkUser(); 
    }
  }
}
```

And then upon the `Auth.signIn` success, I call: `Hub.dispatch('auth', { event: 'signedIn', data: user }, 'Auth');`.

**Comment by chmelevskij** [comment]
Hi @ngocketit, I had a similar question to yours. Ended up tracing back what original `SignUp` component does. So after looking at [SignUp](https://github.com/aws-amplify/amplify-js/blob/e7157dc797c76b66b79f069705428a0bc8e2d054/packages/aws-amplify-react/src/Auth/SignUp.jsx#L199) and then checking [AuthPiece](https://github.com/aws-amplify/amplify-js/blob/e7157dc797c76b66b79f069705428a0bc8e2d054/packages/aws-amplify-react/src/Auth/AuthPiece.jsx#L58) ended up calling `props.onStateChange(<state>, data)`.
