### ISSUE TITLE
Duplicate user by creating new account with capital letter.

### ISSUE THREAD

**Issue by robotlemons** [aws-amplify/amplify-js#2685]
**Describe the bug**
This may be a feature but seems like a bug. If you create a user.. 'chris@mydomain.com' and then create another user 'Chris@mydomain.com' the User Pool and Amplify allow it to go through so you end up having both users in the system.

**To Reproduce**
1. Create a user account with username@yourdomain.com
2. Create another user account with Username@yourdomain.com

**Expected behavior**
Don't allow this behavior by throwing an error or restrict the field to all lowercase.

**Desktop (please complete the following information):**
 - OS: OSX Mojave
 - Browser: Chrome
 - Version: 71.0.3578.98

**Comment by jordanranz** [comment]
It seems this is a feature implemented by Cognito. Here is a related forum post:
https://forums.aws.amazon.com/thread.jspa?threadID=257514

**Comment by OrangeDrangon** [comment]
Could I make a recommendation of just having Amplify have a option (default?) for signup / login to lowercase the email before sending it to Cognito.

Another option is to just document this concern and give people a solution such as:

```
const email = getEmailFromForm(); // A generic phrasing saying the email value should be here
const lowerCaseEmail = email.toLowerCase(); // toLowerCase() returns a lower cased string

const a = 'ABC';
a.toLowerCase(); // -> returns 'abc'
```

Note according to cursory testing in the Firefox console `toLowerCase()` is not destructive to the original string. [MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLowerCase)

**Comment by OrangeDrangon** [comment]
@robotlemons Just tagging you to make sure you have seen this.

**Comment by robotlemons** [comment]
@OrangeDrangon I saw.. was hoping an option would be available to pass autocapitalize=off so maybe the form wouldn't do it naturally on mobile and a user would be forced to put capital if they registered with capital letter email
