### ISSUE TITLE
How to catch PubSub errors if MQTT connection lost or broken?

### ISSUE THREAD

**Issue by mevert** [aws-amplify/amplify-js#2692]
** Which Category is your question related to? **
PubSub connection problems

** What AWS Services are you utilizing? **
PubSub in aws-amplify 1.1.19

** Provide additional details e.g. code snippets **
What is the best way to keep PubSub connection alive by using aws-amplify? Or is there even any way?

I am using similar code as you mention in the documentation:
`PubSub.subscribe(['myTopic1','myTopic1']).subscribe({
  next: data => console.log('Message received', data),
  error: error => console.error(error), // this never logs anything)
  close: () => console.log('Done'),  // this never logs anything)
})`

However, I have the problem that clients Internet connection can be lost for a short period of time and then these can no longer receive messages. For example, if portable Wifi router switch connection from 4G to 3G, I get the following message in console:
`
ConsoleLogger.js:88 [WARN] 14:36.405 MqttOverWSProvider - ... {
  "errorCode": 4,
  "errorMessage": "AMQJS0004E Ping timed out.",
  "uri": "wss://..."
}
`
I would like to catch these connection problems somehow in order to subscribe to topics again so that I can keep connection alive.

**Comment by manueliglesias** [comment]
Hi @mevert 

At the moment, there is no way to catch those events.

https://github.com/aws-amplify/amplify-js/blob/e7157dc797c76b66b79f069705428a0bc8e2d054/packages/pubsub/src/Providers/MqttOverWSProvider.ts#L99-L101

Which, as of today, only logs a warning:

https://github.com/aws-amplify/amplify-js/blob/e7157dc797c76b66b79f069705428a0bc8e2d054/packages/pubsub/src/Providers/MqttOverWSProvider.ts#L85-L89

If you are on a browser environment, one thing you can try is the [`Navigator online` api](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/Online_and_offline_events) to listen for connection changes and unsubscribe/re-subscribe accordingly.

I am also labeling this as a feature-request

**Comment by nayan27** [comment]
This seems closely linked to my own issue: #2007 . I believe we really need a way to handle connection status properly. I also believe that should be fairly easy to implement/test/release. After looking at the lines provided above, the only missing thing is a connection event callback which we could pass to the MqttOverWSProvider. This callback could then be called in the MqttOverWSProvider.onDisconnect method and other connection related methods.
Thank you!

**Comment by matwerber1** [comment]
+1 request for connection event handlers and methods to retrieve current status. Same for subscriptions if not already present.

**Comment by mevert** [comment]
In addition to `AMQJS0004E Ping timed out` error, `AMQJS0007E Socket error:undefined` (errorCode: 7) does not trigger the error. Despite the fact that it occurs when subscription fails. Documentation of PubSub says that error is "Triggered when subscription attempt fails". However, looks like errors are not triggered...

@manueliglesias any idea when the fix for this issue is coming?

**Comment by schaq8** [comment]
+1 request for connection event handlers and methods to retrieve current status. Same for subscriptions if not already present.

**Comment by Flora140** [comment]
+1 request to ` fix AMQJS0004E Ping timed out `. Also experiencing the same issue.

**Comment by mevert** [comment]
Dear, aws-amplify developers, could you please comment on this issue and let us know when the fix for catching PubSub errors is coming?

**Comment by elorzafe** [comment]
@mevert are you still having the issue with AMQJS0007E? That problem was fixed on pr #3376

**Comment by mevert** [comment]
@elorzafe thanks for the info. I will let you know if I face the problem again. What is the status with the connection handlers? And are we now able to know when IoT connection breaks in all of the possible cases? 

Currently, I have used PING/PONG check for websockets in order make sure that WS connection is still alive and working because I wasn't able to catch all broken connections with aws-amplify. So I have been calling backend Lambda that will send IoT message to the client and if client won't receive the message in a certain amount of time it will try to initialize Websocket connections.

**Comment by mevert** [comment]
> @mevert can your our latest unstable release. (1.1.37-unstable.10 for aws-amplify)

After updating aws-amplify version to 1.1.40 it broke our PubSub subscriptions unsubscribe funktion as described in https://github.com/aws-amplify/amplify-js/issues/3039#issuecomment-532222215 We can no longer subscribe again to topics that were unsubscribed.

From the old package-lock.json I can see that in @aws-amplify/pubsub version 1.0.30 unsubscribe used to work. However, with the current 1.1.2 we have this problem.  @elorzafe any ideas why?

**Comment by justinjoyn** [comment]
Any update on this? I always get this error when trying to subscribe to a topic after internet is restored.
``` 
     "errorCode":7,
     "errorMessage":"AMQJS0007E Socket error:undefined."
```

**Comment by escar** [comment]
> Any update on this? I always get this error when trying to subscribe to a topic after internet is restored.
> 
> ```
>      "errorCode":7,
>      "errorMessage":"AMQJS0007E Socket error:undefined."
> ```

Same here, I'm on latest version 2.2.5

**Comment by Thembelani** [comment]
Hi. Any update on this ...?

**Comment by zhenyakovalyov** [comment]
hi - is there any updates on this please?

**Comment by CiscoKidxx** [comment]
Hello, looking for an update here please!

**Comment by ericclemmons** [comment]
https://github.com/aws-amplify/amplify-js/pull/6448 should address this issue.

`error` will fire when the connection closes unexpectedly, allowing you to fire `PubSub.subscribe` again.

Please open a new issue (which includes a new bug report template) if you experience this problem again 🙏

**Comment by blacksheep--** [comment]
@ericclemmons this is wrong, as the mentioned PR #6448 covers changes to AWSAppSyncRealTimeProvider and the necessary (and also mentioned by OP) MqttOverWSProvider has not been touched since 20th March 2020. So this bug is still alive.

**Comment by stocaaro** [comment]
There are a few different issues here, which I believe are now all resolved.

1.  **How to catch PubSub connection errors** - Disconnect will [send an Observable error](https://github.com/aws-amplify/amplify-js/blob/main/packages/pubsub/src/Providers/MqttOverWSProvider.ts#L154) that you can receive and process in your application.
2. **PubSub topics can't be reconnected to** - I have tested this in a sample built on the current version and have had no trouble disconnecting and reconnecting to a topic.

For more fine grain detail about the state of the connection, you can now refer to the [connection state hub messages](https://docs.amplify.aws/lib/pubsub/subunsub/q/platform/js/#subscription-connection-status-updates).

Not requested here outright, but covered by other issues, there is [work in flight](https://github.com/aws-amplify/amplify-js/pull/10235) to automatically reconnect, which may resolve some of the underlying use-cases being investigated here.

If there are outstanding issues discussed here not resolved in the current version of Amplify that I have missed, please reopen this and draw my attention to what remains unresolved.

**Comment by LFMAKER** [comment]
@stocaaro
How can I verify that my subscription has successfully connected? I have 70+ in-app subscriptions on my mqtt client, but Hub.listen doesn't tell me specifically about each subscription.

I need to do this because I can only publish to a topic after being 100% connected with some subscriptions.

**Comment by stocaaro** [comment]
Hello @LFMAKER,

Interesting. This issue and effort has been focused around whether the server connection recovers from outages/disruptions. This recovery process will re-establish all subscriptions that existed before the connection was lost.

For monitoring subscription status to a specific topic, I'm not aware of any way to verify connection short of receiving data. If your MQTT topic has some form of regular heart beat / health check per topic, you could monitor that you receive the expected message periodically. The MQTT protocol has a health check like this for the connection.

If you are using the AWS IoT MQTT service, I believe there is a 50 topic per client subscription limit and [the team recommends](https://github.com/aws/aws-iot-device-sdk-cpp/issues/165) using wildcards to group many topic subscriptions under a single client subscription to work around this per client limit.

Feel free to capture details into a [new feature request](https://github.com/aws-amplify/amplify-js/issues/new?assignees=&labels=feature-request&template=2.feature_request.yaml) if there is behavior in the Amplify client that isn't supported today and would make your development experience better.
