### ISSUE TITLE
IAM not authorized to mutate on type

### ISSUE THREAD

**Issue by amlcodes** [aws-amplify/amplify-js#2698]
I've set IAM unauth and authorized roles with their ARNs resources as a inline policy. Somehow, while I am in the appsync query console, I get an "Unauthorized to Create on type Type"  Error while running a mutation

**Comment by undefobj** [comment]
Hi @amlcodes this repo is for the Amplify JS library and isn't run by the AppSync team. For questions related to the service operations such as the console, it's best to log an issue on their support forum: https://forums.aws.amazon.com/forum.jspa?forumID=280&start=0

I'll close this issue for now but please reopen if I misunderstand your question.
