### ISSUE TITLE
looking for a bit of guidance on code structure and plugin development

### ISSUE THREAD

**Issue by sivang** [aws-amplify/amplify-js#2700]
Hello there,

 I wish to implement Flutter support for aws-amplify. I'd like some guidance where to look to see code I can borrow or build 'on' , so I can translate it to dart and hence create a Flutter plugin for aws-amplify.

 I'd also be interested to implement the ready made UI components aws-amplify provides with other frameworks , so some pointers to where this lives and what are the dependencies would be highly appreciated!

**Comment by undefobj** [comment]
Hello @sivang this is a very nice offer. Please see the following comment for Flutter with Amplify: https://github.com/aws-amplify/amplify-js/issues/1852#issuecomment-463791682

There are certain design principles we have with Amplify including category based programming model and declarative APIs. If we were to accept contribution on Flutter we would want to stay consistent with this model, and at that time we can provide more concrete guidance. In the interim it might be prudent to learn from community feedback in the other thread to understand the MVP use cases.

**Comment by sivang** [comment]
hey there @undefobj , thank you most very much about this reply!

I am familiar with that item, as well with some of the comments there. And am familiar with the MVP's reqs as per support in VueJS (it seems most reasonable to match with that, as Vue seems to follow more closely, at least from the API standpoint, Flutter's declarative flavor ).

Is there a document somewhere for interested prospective community contributors to follow to at least read the sources where this implicit style is evident? Happy to go on and author something alike if it's missing.

Is following the VueJS flutter support can be deemed good enough to borrow on the category programming model, and the flavor of declarative apis provided?
