### ISSUE TITLE
Custom props.inGreeting is ignored by the Greetings component

### ISSUE THREAD

**Issue by schof** [aws-amplify/amplify-js#2701]
**Describe the bug**
The result of the custom function passed through `inGreeting`  property is ignored.

**To Reproduce**
See the following simple example:

```javascript
const myComponents = [
  <Greetings
    inGreeting={username => {
      console.log('Hello inGreeting!!!!')
      return 'Hello foo'
    }}
    outGreeting=""
  />,
  <SignIn />,
  <ConfirmSignIn />,
  <VerifyContact />,
  <SignUp />,
  <ConfirmSignUp />,
  <ForgotPassword />,
  <RequireNewPassword />
]

export default withAuthenticator(App, true, myComponents)
```

**Expected behavior**
We should see "Hello foo" instead of the default greeting which uses the username in the "header bar." I can confirm the function I'm passing is being called because I see "Hello inGreeting" in the console as expected. I suspect the custom value is being override at a later point (perhaps in another component?)

**Screenshots**
![screen shot 2019-02-13 at 10 32 32 am](https://user-images.githubusercontent.com/85518/52722992-b4f54800-2f7a-11e9-803e-f32fb2bde495.png)

**Comment by manueliglesias** [comment]
Hi @schof 

I think I see the problem, looks like when `includeGreetings` is true (second param or `withAuthenticator`), the Greetings component is added (a new one, not the one you passed in the `myComponents` array)

https://github.com/aws-amplify/amplify-js/blob/e7157dc797c76b66b79f069705428a0bc8e2d054/packages/aws-amplify-react/src/Auth/index.jsx#L76-L86

Can you try this and see if it still shows the one you pass in `myComponents`?

```js
export default withAuthenticator(App, false, myComponents)
```

**Comment by haverchuck** [comment]
@schof We have merged a fix into our unstable build (npm i aws-amplify-react@unstable).  It will be in the main build in the near future.
