### ISSUE TITLE
using Service Worker yields `TypeError: undefined has no properties`

### ISSUE THREAD

**Issue by blbradley** [aws-amplify/amplify-js#2703]
**Describe the bug**
Service Worker is unusable out of the box.

**To Reproduce**
```
git clone https://github.com/blbradley/amplify-vue-issue
cd amplify-vue-issue
yarn install
yarn serve
```

Then observe your browser's console.

**Expected behavior**
`TypeError: undefined has no properties`

**Screenshots**
![service-worker-error-screenshot](https://user-images.githubusercontent.com/1435085/52741102-2e506300-2f9a-11e9-8f93-c139c92d8dca.PNG)

**Desktop (please complete the following information):**
 - OS: Linux and Windows 10
 - Browser: Chrome 72 and Firefox 65

**Comment by manueliglesias** [comment]
Hi @blbradley 

Looking at
https://github.com/blbradley/amplify-vue-issue/blob/d06316c56892c61670b88d6495f61200db41a703/src/main.js#L9-L11

you need to change your code to this

```diff
console.log(myServiceWorker)

- ServiceWorker = this.serviceWorker.register('/service-worker.js', '/');
+ ServiceWorker = myServiceWorker.register('/service-worker.js', '/');
```

and provide a `service-worker.js` file (e.g. https://serviceworke.rs/strategy-network-or-cache_service-worker_doc.html)

Take a look at our docs for [ServiceWorker](https://aws-amplify.github.io/docs/js/service-workers#register)

**Comment by blbradley** [comment]
Hey @manueliglesias. Thanks for the response.

This was actually copy/paste from the docs; I should have read more deeply but did not.

I propose changing the docs to match something that would work by directly copying the doc examples.

**Comment by manueliglesias** [comment]
Thank you for the PR @blbradley !

**Comment by blbradley** [comment]
No problem; once again, thanks for the speedy response.
