### ISSUE TITLE
Device tracking call failed at login with error "Invalid device key given" for CUSTOM_AUTH flow

### ISSUE THREAD

**Issue by mHou407** [aws-amplify/amplify-js#2705]
**Describe the bug**
Error "Invalid device key given" is return when device tracking is enabled in Cognito and custom auth flow is used. This error only occurs when custom auth flow is used without password. 

**To Reproduce**
1. Set device tacking to "always" in Cognito
2. Set up lambda hooks for custom auth flow. 
3. Sign in without supplying the password 
4. Receive error "Invalid device key given"

**Expected behavior**
Device should show up as remembered device in Cognito.

**Additional context**
Further testing shows that device tracking feature works as expected if a password is supplied in the custom auth flow. In this case, the app goes through SRP_A, PASSWORD_VERIFIER and CUSTOM_CHALLENGE. And the device is correctly remembered in Cognito. 
However, if no password is provided, the app only goes through CUSTOM_CHALLENGE. It gets back JWT tokens as expected but received "Invalid device key given" error when SDK tries to remember the  device.

**Comment by manueliglesias** [comment]
This seems related to #2087

**Comment by mHou407** [comment]
#2087 seems to be about Amplify trying to track device for USER_PASSWORD_AUTH flow, which does not support device tracking, according to this comment https://github.com/aws-amplify/amplify-js/issues/2087#issuecomment-445592537. In my case, I'm using a passworless CUSTOM_AUTH flow. I guess the nature of the issue is different event though the symptoms are similar

**Comment by powerful23** [comment]
@mHou407 Hi, I tried to reproduce the steps but I didn't get errors when using passwordless login. Can you verify again it's happening in the latest version of amplify? Or can you provide more details? Also you can point out which request gives you the `Invalid device key given` error.

**Comment by mHou407** [comment]
@powerful23 Just verified that this issue has been fixed in the newest Amplify release (JavaScript, 1.1.27). Thank you for your help.
