### ISSUE TITLE
Analytics: On web there's a new session every page load

### ISSUE THREAD

**Issue by roborourke** [aws-amplify/amplify-js#2710]
**Describe the bug**
Using page view auto tracking on a website I'm seeing a new session ID for every page view. Given that this was me clicking around a site I would assume this should constitute a single session. It's difficult or impossible to query for a user's journey without a single session ID.

**To Reproduce**
1. Create a web app with a few pages that includes analytics & auth
2. Add `Analytics.autoTrack('pageView', { type: 'multiPageApp' })` to the code.
3. Navigate around a bit
4. Number of recorded "sessions" should match the number of page views

**Expected behavior**
There should be a single session ID for the user's time on the site until they become inactive or otherwise.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: 71

**Additional context**
It's hard to find info on what constitutes a session in the docs, I'm sure I saw it but can't find it now.

**Comment by haverchuck** [comment]
@roborourke What kind of application are you developing (React? Angular? Vanilla JS?), and what kind of routing mechanism are you using?

**Comment by roborourke** [comment]
@haverchuck sorry, it's vanilla JS on a standard WordPress site. No routing other than plain old links.

**Comment by readshaw** [comment]
@roborourke Did you find a resolution to this issue? I am seeing similar behavior from a web app with trivial HTML site and also on a WordPress site.  Similar to the site you described above, the site has plain old links from page to page.

Thank you in advance.

**Comment by roborourke** [comment]
@readshaw I think it must come from Cognito. I've currently worked around it with a custom attribute I'm generating using a `uuid-v4` function and `window.sessionStorage()`. So not the actual AWS session ID but I least I can query on my one.

**Comment by readshaw** [comment]
Thanks @roborourke. Our team reached a similar conclusion on the way forward for multi-page sites.

**Comment by roborourke** [comment]
@haverchuck I'll try the latest version out but wanted to check if you'd had a chance to try out amplify with a static site yet
