### ISSUE TITLE
[Auth] [Critical] Authentication cookie lockup when multiple user data exists

### ISSUE THREAD

**Issue by ffxsam** [aws-amplify/amplify-js#2711]
I've identified an edge case where "bad cookies" can cause a site to be prevented from loading (shows "pending" in Chrome DevTools Network tab) and is stuck indefinitely.

I've set Auth to use cookies for storage.

**To Reproduce**
1. (web) Create a new user
2. (web) Log in as user
3. (AWS console) Delete user in Cognito interface
4. (web) Create new user

**Expected behavior**
Website should be accessible.

**Screenshots**
![image](https://user-images.githubusercontent.com/12532733/52804443-d40edb00-3049-11e9-815f-07e41fb767c5.png)

Note the set of two credentials in the cookies. The website is totally stuck until I remove the old set. I can even spin up a _completely_ different web application that doesn't even have Cognito, and when I surf to `localhost:8080`, it's stuck due to these cookies. Once I remove the set of cookies for the user starting with `7fd32`, the issue is gone and I can surf normally.

**Why this would happen in the real world**
A user deletes their account, and then several days later, changes their mind and signs up again by creating a new account.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3
 - Browser: Chrome
 - Version: 72

**Comment by ffxsam** [comment]
Amplify config:

```js
Amplify.configure({
  Auth: {
    identityPoolId: process.env.VUE_APP_AWS_IDENTITY_POOL_ID,
    region: process.env.VUE_APP_AWS_REGION,
    userPoolId: process.env.VUE_APP_AWS_USER_POOL_ID,
    userPoolWebClientId: process.env.VUE_APP_AWS_USER_POOL_CLIENT_ID,
    mandatorySignIn: true,
    cookieStorage: {
      domain: process.env.VUE_APP_COOKIE_DOMAIN,
      path: '/',
      expires: EXPIRATION_DAYS,
      secure: process.env.NODE_ENV !== 'development',
    },
  },
});
```

**Comment by manueliglesias** [comment]
Hi @ffxsam 

I haven't been able to reproduce it (I am using `withAuthenticator` in a react app)

would it be possible to create a codesandbox or similar where I can see some more of your code?

**Comment by ffxsam** [comment]
@manueliglesias Do you mind if I create a private repo and add you to it? And I can put some instructions for you in the README.

**Comment by manueliglesias** [comment]
@ffxsam that would be great!

**Comment by ffxsam** [comment]
Great, gimme some time, I'll also put together a video demonstrating the issue, too.

**Comment by ffxsam** [comment]
@manueliglesias I've added you to my private repo. Check out issue #80 for some details.

**Comment by jgautheron** [comment]
I confirm, this is a problem we're also having in a multi-tenant app.

**Comment by ffxsam** [comment]
I worked around this by explicitly calling `Auth.logout()` when a user logs out (or the app detects their account has been deleted or suspended).

**Comment by Steinliiippp** [comment]
Is there any update on this?
