### ISSUE TITLE
Q: [Cognito] Is there any concerns with auto confirming account in pre-sign-up hook?

### ISSUE THREAD

**Issue by mHou407** [aws-amplify/amplify-js#2721]
** Which Category is your question related to? **
Cogntio auto-confirm account / best practice

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
I'm using a CUSTOM_AUTH flow to achieve password-less sign in (SMS passcode only). Here is the desired on-boarding / sign-in flow:
1)	User enters a phone number.
a)	If phone number doesn’t exist, prompt for additional information (An account will be created in the background).
b)	If phone number exist, proceed.
2)	User receives a SMS text with one-time passcode. 
3)	User enters the code to complete login.

Since auto sign-in after confirming sign-up is not available in Cognito out of the box, this creates a issue that user has to receive and enter 2 different passcode when signing in for the first time.
I'm considering to solve it by by auto-confirm the account during sign-up. Is there any concerns with this workaround? And is there a better alternative?

**Comment by jkeys-ecg-nmsu** [comment]
I think your solution is fine, and a perfect example of why the Cognito triggers exist and why Cognito provides an admin API.

**Comment by haverchuck** [comment]
@mHou407 - Your solution seems like it would work from a technical perspective, but the answer to whether you should have any concerns is a bit tricky.   It would depend on the needs of the application and your specific security requirements.
