### ISSUE TITLE
How to set API token in axios headers, after sign in (react)

### ISSUE THREAD

**Issue by BoaPi** [aws-amplify/amplify-js#2722]
**Which Category is your question related to?**
Authentication, usage of tokens

**What AWS Services are you utilizing?**
only Authentication service of AWS

**Provide additional details e.g. code snippets**
* react 16.7.0
* axios 0.18.0

Currently we are using the Authenticator Wrapper inside our App.js component. In all components inside the wrapper we are referring to the `authState` to determine which component should be rendered. 

Beside that we got an Rest API which is not hosted on AWS. For data fetching inside of the redux-sagas we are using axios. Therefore we need to set the tokens in the axios header.

Is there a common or recommended way to set the tokens. 

The problem I have is, that the components which are triggering the sagas are mounting faster, then the set of the tokens, when the `authState` changes to `signedIn`. That leads to `401` responses form the Backend.

I hope I could clarify the problem. 😃 

edit:
current implementation via Component, which is located as direct child of the Authenticator Component.
```javascript
class TokenHandler extends Component {
  async componentDidUpdate() {
    const { authState } = this.props;

    if (authState === 'signedIn') {
      const {
        accessToken: { jwtToken },
      } = await Auth.currentSession();
      setApiToken(jwtToken, 'accessToken');
    }

    if (authState !== 'signedIn') {
      unsetApiToken();
    }
  }

  componentWillUnmount() {
    unsetApiToken();
  }

  render() {
    return null;
  }
}
```

**Comment by haverchuck** [comment]
@BoaPi  -  I am not well-versed in redux-sagas,  but I would imagine there is a way to make the dependant components not mount unti lthe token is set (again, I'm not sure).  Is that not so?  If I am misunderstanding the problem can you please share some more of the relevant code?

**Comment by BoaPi** [comment]
Hi @haverchuck - thx for the quick response. 
I think the approach you describe should be work.
I thinking of extending the TokenHandler Component with render-props to decide if the components should be rendered. And as long the API token is not set render nothing or push back to '/'. 

One last question, is there a way to to extends the functionality of the Authenticator component, in a way that, the authState is only changed to `signedIn` after the tokens are set?

If not, I will go with the described approach. 
Thanks again. 👍

**Comment by haverchuck** [comment]
@BoaPi I don't believe there is an OOTB way to configure `Authenticator` in this way, but it's not a bad enhancement request if you want to make one.  I'm going to close this issue for now, but if you continue to have trouble please feel free to reopen it.
