### ISSUE TITLE
Some iOS devices does not receive Push Notifications 

### ISSUE THREAD

**Issue by kenji4569** [aws-amplify/amplify-js#2724]
My iPad Pro 11 inch does not receive Push Notifications with AWS-Amplify (The version is v 1.1.18 but I think the problem will occur in the latest master). 

After investigation, I found that an error is occurred on `updateEndpoint` with validation errors: `...Demographic.Make to be a string ... Demographic.Model to be string...`.

At this point, the input to the `updateEndpoint` was `{...Make: {}, Model: {} ...}`. Although the input was `{...Make: null, Model: null ...}` just before applying `transferKeyToUpperCase` to the input. So the input conversion makes it failed to updateEndpoint.

In `dimToMake` in `ClientDevice/ios.ts`, Make and Model are created but assigned to null for undefined screen sizes. So my iPad gets `{Make: null, Model: null}` causing the updateEndpoint error.

I temporary fixed it by changing `{Make: null, Model: null}` to `{Make: undefined, Model: undefined}` in `dimToMake` in `ClientDevice/ios.ts`, thought I'm not sure it's in an appropriate way.

Thanks in advance.

**Comment by powerful23** [comment]
@kenji4569 thanks for reporting. I have sent a pr to fix this issue.
