### ISSUE TITLE
listQuery is limited to 10 by default

### ISSUE THREAD

**Issue by benoj** [aws-amplify/amplify-js#2728]
**Describe the bug**

The default limit on the list{Model} query is 10, which means that as the table grows as more items are added by different owners - then people lose their items as not returned.
 
```
#set( $limit = $util.defaultIfNull($context.args.limit, 10) )
{
  "version": "2017-02-28",
  "operation": "Scan",
  "filter":   #if( $context.args.filter )
$util.transform.toDynamoDBFilterExpression($ctx.args.filter)
  #else
null
  #end,
  "limit": $limit,
  "nextToken":   #if( $context.args.nextToken )
"$context.args.nextToken"
  #else
null
  #end
}

```
Is there a better way to queryItems by an owner without setting limit to a really high number? If not then this should be documented..

**Comment by MathiasBerwig** [comment]
I'm facing what I believe to be the same problem. A simple list query to a 30 record DB will only return a filtered item if the limit is set greater or equal to the "position" of the row in the dataset.

For example:

Having `$filter` as `someProp eq "someStr"`,  `listEntity(filter: $filter) { items { id} }` will return []. With the same filter, `listEntity(limit: 25, filter: $filter) { items { id} }` would return the matching row.

**Comment by wizawuza** [comment]
@MathiasBerwig I don't believe you referenced the correct issue.

**Comment by MathiasBerwig** [comment]
> @MathiasBerwig I don't believe you referenced the correct issue.

You're right. I edited my previous comment with the right issue (same number, but for amplify-cli).
