### ISSUE TITLE
Storage Put Method Should Return Prefixed Key

### ISSUE THREAD

**Issue by medelman17** [aws-amplify/amplify-js#2733]
**Is your feature request related to a problem? Please describe.**
Regardless of the protection `level` specified in `opts`, Storage.put() returns the same value for `key` upon success, obfuscating the fact that the actual key value for the object differs and requiring users to imperatively set the `right` value should the user wish to persist the correct key/object location. For example: 

Call | Result | Actual Key
|--- | --- | ---  |
|`Storage.put('12345.jpg', file, { })` | `{ key: "12345.jpg"} ` | `/public/12345.jpg` |
|`Storage.put('12345.jpg', file, { level: 'protected' })` | `{ key: "12345.jpg"} ` | `/protected/<USER-SPECIFIC-ID-FROM-COGNITO>/12345.jpg` |

**Describe the solution you'd like**
`Storage.put()` should return the properly prefixed key as outline above. 

**Describe alternatives you've considered**
Given that the value returned for `key` is always the same as the first argument provided to the Put method, returning `key` in lieu of just a success code has a dubious value-add, but high propensity to confuse. Thus, a case could likely be made that, if the above solution were not acceptable, `Storage.put()` should return nothing at all. 

I'd be happy to start a pull request for further discussion, but given that this would be a breaking change, figured it would be best to start here.

**Comment by medelman17** [comment]
This is more of a `bug` than a `feature-request`... @dabit3

**Comment by stocaaro** [comment]
Related to #5737

**Comment by gardner** [comment]
If you came here looking for a woraround then you can use something like this:

```javascript
import React, { useEffect, useState } from "react";
import { useAuthenticator } from '@aws-amplify/ui-react';
import { Auth } from 'aws-amplify';

function App() {
  const { authStatus } = useAuthenticator(context => [context.authStatus]);
  const [identityId, setIdentityId] = useState('');

  useEffect(() => {
    if (authStatus === 'authenticated') {
      Auth.currentUserCredentials().then((creds) => {
        console.log('identityId', creds.identityId);
        setIdentityId(creds.identityId);
      });
    }
  }, [authStatus]);

  return (
    <span>{identityId}</span>
  );
}

export default App;
```

**Comment by cwomack** [comment]
Closing this issue as a duplicate in favor of #5737.  The [workaround](https://github.com/aws-amplify/amplify-js/issues/2733#issuecomment-1268289683) referenced by @gardner above can be utilized until a better solution is implemented that encompasses both issues/feature requests.

Thank you @gardner for providing this!
