### ISSUE TITLE
Amplify's compatibility with PhantomJS

### ISSUE THREAD

**Issue by kenziyuliu** [aws-amplify/amplify-js#2738]
**Describe the bug**
When importing the following Amplify modules (`@aws-amplify/auth` and `@aws-amplify/analytics`) into the client side of my application, the app couldn't be loaded with PhantomJS

**To Reproduce**
1. Create a web app and include references to Amplify Analytics/Auth modules
2. Before rendering the page, try creating a `new AWSKinesisProvider()` imported from `@aws-amplify/analytics`
3. Add some JS to render some text
3. Add a PhantomJS-based canary test to test that the text to be rendered actually renders
4. Run the test and it should fail

**Expected behavior**
The test should pass without the references to the amplify modules

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.13
 - Browser: PhantomJS
 - Version: 2.1.1

**Smartphone (please complete the following information):**

**Additional context**

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by haverchuck** [comment]
@kenziyuliu Would you mind posting any error output you are receiving?

**Comment by kenziyuliu** [comment]
@haverchuck Unfortunately I wasn't able to get error output from Amplify by setting `window.LOG_LEVEL = "DEBUG"`.

Another way to tell is to insert a `console.log` statement after creating a `new AWSKinesisProvider()` and use PhantomJS's `page.onConsoleMessage` to observe that the console.log isn't run. I'm using the following versions:
NodeJS-aws-amplify-analytics = 1.2.x;
NodeJS-aws-amplify-auth = 1.0.x;

**Comment by haverchuck** [comment]
@kenziyuliu off the top of my head it could be something with the window object or something, but I'm not sure.  PhantomJS is not being actively developed at this time, so we don't actively support it unfortunately.

**Comment by kenziyuliu** [comment]
@haverchuck Thanks for your response! I'll take it as this won't be fixed. The prefix is just what our Config file uses, I should have removed it before pasting.
