### ISSUE TITLE
completely  logout user from social login

### ISSUE THREAD

**Issue by supun19** [aws-amplify/amplify-js#2745]
I login with social login then logout but when I again login doesn't popup social login, directly login to the app. can I logout completely user.

**Comment by haverchuck** [comment]
@supun19  - Can you please share the code that you are using to perform the signIn and signOut, as well the social provider you are using?

**Comment by supun19** [comment]
This is log out function 
```
Auth.signOut({ global: true })
      .then(data => console.log(data))
      .catch(err => console.log(err));
```
not use custom signin function

social providers amazon,google.

**Comment by haverchuck** [comment]
@supun19 - Hmmm.... do you see localStorage being cleared out?

**Comment by supun19** [comment]
no it's not clear.

**Comment by haverchuck** [comment]
@supun19 -  Assuming you haven't set up your own custom storage of credentials, it seems like investigating why credentials aren't being cleared from local stroage is a good first step here (sorry - I should have been more precise in my earlier question and specified that user data is what should be cleared from local storage).

Try turning on the Amplify logger using the DEBUG log level, as described [here](https://aws-amplify.github.io/docs/js/logger).

**Comment by powerful23** [comment]
Closing the issue. Please let us know if you have further concern about this issue.
