### ISSUE TITLE
Empty cookieStorage object saves the tokens as cookies

### ISSUE THREAD

**Issue by sartios** [aws-amplify/amplify-js#2746]
**Describe the bug**
The Auth module stores the tokens as cookies when the cookieStorage is an empty object. If it is undefined it uses the local storage.

**To Reproduce**
Amplify.configure({
  Auth: {
    region: "AWS_REGION",
    userPoolId: "COGNITO_USER_POOL",
    userPoolWebClientId: "CLIENT_ID",
    mandatorySignIn: true,
    cookieStorage: {}
  }
})

**Expected behavior**
It should use local storage instead of cookies. If I pass `cookieStorage: undefined` then uses the local storage.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 72.0.3626.109

**Comment by coreylee33** [comment]
Clear cookies
