### ISSUE TITLE
Federated sign-in buttons have broken styles.

### ISSUE THREAD

**Issue by RodionChachura** [aws-amplify/amplify-js#2752]
When using Authenticator component:
```jsx
import { Authenticator } from 'aws-amplify-react/dist/Auth'

const federated = {
  google_client_id: '1014540554504-pn7mcbh6vp7dhm67nuo41n4n0e8ce500.apps.googleusercontent.com',
  facebook_app_id: '356315411761615' 
}

export default () => (
    <Authenticator federated={federated} />
)
```
Component looks like this:
![image](https://user-images.githubusercontent.com/17750556/53288565-ac7ee780-379a-11e9-845c-9ffc69f4faea.png)
There are problems with icons in buttons.

**Comment by jordanranz** [comment]
There seems to be global styles affecting the CSS of the federated button icons.

@RodionChachura do you have access to the computed styles for the Google icon?

In the meantime we can try and add more specific styling to the icons to try and prevent this from happening.

**Comment by RodionChachura** [comment]
@jordanranz, no - I don't.

**Comment by ron23** [comment]
Seeing the same issue, any estimate?
