### ISSUE TITLE
Merge two accounts in Cognito created with same email (email and social)

### ISSUE THREAD

**Issue by johanrin** [aws-amplify/amplify-js#2754]
**Which Category is your question related to?**
Authentication

**What AWS Services are you utilizing?**
Amazon Cognito Hosted UI

**Provide additional details e.g. code snippets**
In my app, I have Amazon Cognito Hosted UI configured to handle Authentication by email and social (facebook and google).

_The problem:_
When a user create an account by email (ex: gmail) and later sign up by social (ex: same gmail), I have two accounts created in Cognito.

_Question:_
How merge these two accounts created with the same email?

**Comment by jkeys-ecg-nmsu** [comment]
The API you need to use is [adminLinkProviderForUser](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminLinkProviderForUser.html), I believe.

I don't think Amplify currently has a built-in federation mechanism, i.e. automatically calling adminLinkProviderForUser when a Cognito-authenticated user signs in through social provider.

**Comment by undefobj** [comment]
This is potentially a candidate for Triggers or Admin Queries as part of the following RFC: https://github.com/aws-amplify/amplify-cli/issues/766

**Comment by eoghanatfacet** [comment]
This needs to be maintained open until it's properly linked to RFC: aws-amplify/amplify-cli#766

**Comment by ricky-sb** [comment]
What's the current solution to this? Is it running a Lambda using a pre-signup trigger and AdminLinkProviderForUser?

**Comment by sammartinez** [comment]
@johanrin [Cognito Lambda Triggers](https://aws-amplify.github.io/docs/cli-toolchain/cognito-triggers) are now configurable via the CLI. Closing this request as the RFC is closed and the request is complete.
