### ISSUE TITLE
appsync subscriptions not firing - Angular 6.1.1 / ionic 4 

### ISSUE THREAD

**Issue by troymclure1** [aws-amplify/amplify-js#2755]
**Describe the bug**

Appsync subscription not working with an Ionic 4 project, Angular 6.1.1.

**To Reproduce**
Cloned a new project from [here](https://github.com/ashteya/ionic4-tutorial-appsync) and then installed amplify and ran the amplify configure and amplify init, added an API and then pushed. I verified that the schema was created a long with the database etc. I then added the cognito auth and have a verified user that I can login with.

After testing some queries and mutations in the console I was able to configure a query locally. I tried to test a subscription which is not working locally at all. 

I was following the documentation [here](https://aws-amplify.github.io/docs/js/api). It seems that the subscription here would not work until I cast it as Observable (as Observable<object>;) using the `zen-observable` library

I'm not sure what I've missed here so I'm hoping that you can please assist.

**Expected behavior**
When I create a new entry for the onCreateBlog mutation I'm expecting the subscription to fire.

**Screenshots**

<img width="524" alt="screen shot 2019-02-25 at 9 55 05 pm" src="https://user-images.githubusercontent.com/16935542/53332798-52238980-3948-11e9-9c81-f98be617dc74.png">

<img width="626" alt="screen shot 2019-02-25 at 9 54 50 pm" src="https://user-images.githubusercontent.com/16935542/53332850-6bc4d100-3948-11e9-8ac9-cca507c67fad.png">

<img width="1014" alt="screen shot 2019-02-25 at 10 05 06 pm" src="https://user-images.githubusercontent.com/16935542/53333271-7f246c00-3949-11e9-853e-168d4f515334.png">

<img width="600" alt="screen shot 2019-02-25 at 9 59 57 pm" src="https://user-images.githubusercontent.com/16935542/53333043-e4c42880-3948-11e9-9299-fb03ba333b29.png">

**Desktop (please complete the following information):**
 - OS: OSX Sierra 10.12.6 (16G1212)
 - Browser: Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by troymclure1** [comment]
@haverchuck & @elorzafe After re-testing with a completely new project, new API & casting my subscription  `as Observable<object>;` its working.

**Comment by jordanranz** [comment]
@troymclure1, is this safe to close?

**Comment by powerful23** [comment]
Closing this issue. Please let us know if you still have this issue.
