### ISSUE TITLE
"Neither Email nor Phone Number selected" Message

### ISSUE THREAD

**Issue by aireater** [aws-amplify/amplify-js#2763]
**Describe the bug**
Anytime I login to my react app using withAuthenticator I get the following message: Account recovery requires verified contact information. I can click skip but when i click verify I get an error: "Neither Email nor Phone Number selected" 

**To Reproduce**
1. wrap main component with withAuthenticator
2. create an account in cognito web console
3. use temporary password to sign in
4. reset password as instructed
5. logout via Auth.logout() 
6. sign in
7. get message to verify 
8. see message "Neither Email nor Phone Number selected"

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS:macOS
 - Browser firefox (latest developer edition) and safari (latest)

**Comment by elorzafe** [comment]
@aireater what is your configuration on Cognito?

**Comment by aireater** [comment]
@elorzafe I'm not sure what you're asking for? Do you want the settings page for the cognito user group?
