### ISSUE TITLE
aws-amplify-graphql example repo does not work as expected

### ISSUE THREAD

**Issue by sakhmedbayev** [aws-amplify/amplify-js#2772]
**EDIT:** I noticed that the example repo is working only with `visibility` key set to `private`. It does not work with `public` level. I need that unauthenticated user can download files. 

**Describe the bug**
[aws-amplify-graphql](https://github.com/aws-samples/aws-amplify-graphql) example repo does not work as expected

**To Reproduce**
1. Follow instruction in [this repo](https://github.com/aws-samples/aws-amplify-graphql)
2. You should get the following error on file downloading:
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
private/eu-central-1:79c2f6d6-8d8d-4444-bb8d-0b6c866a380d/2601e9da-8dba-4e51-b5f3-cd5bfeecfd67.pdf
</Key>
<RequestId>AE62F8FC2E5DE7A5</RequestId>
<HostId>
zAicIDLK1UO4CRwyYKcFMxxzZoxG80wwLiD60QEoowYV16Hmcvmst4VKzsnW46Do7OinhzzuaW4=
</HostId>
</Error>
```

**Desktop (please complete the following information):**
 - node version v10.13.0
 - amplify cli version 1.1.2

**Comment by sakhmedbayev** [comment]
@undefobj can you please look at this issue?

**Comment by elorzafe** [comment]
@sakhmedbayev this example demonstrates the usage of uploading private files.

Do you only need a sample to upload/download shared files? Or do you need the additional information and control like aws-amplify-graphql sample but for unauth users?

**Comment by sakhmedbayev** [comment]
Thank you @elorzafe for the response. My web app have to provide a way for auth and unauth users to download files.

I have already figured out uploading mechanics. 

Basically, I need to make files publically available for downloading.

**Comment by elorzafe** [comment]
@sakhmedbayev Cool, so you already figure out the upload part and AWS_IAM auth mode on AppSync, so in order that unauth users can download the files from S3 you should do the following. 

Change this line 
https://github.com/aws-samples/aws-amplify-graphql/blob/master/src/Components/AddPhoto.js#L40
from `const visibility = 'private';` to `const visibility = 'protected';` That will upload the files in the bucket allowing every unauth/auth user of your app to download the file.

Was to complex for you to configure AWS_IAM to allow unauth users to query the list of files?

**Comment by sakhmedbayev** [comment]
Thank you @elorzafe for your help!

as for this question:

> Was to complex for you to configure AWS_IAM to allow unauth users to query the list of files?

Yes, it took me a while to figure out it. I hope that the amplify docs were more clear on the subject, at least on that time when I have been working on that issue.
