### ISSUE TITLE
Reverse proxy rewrite doesn't proxy failure status codes

### ISSUE THREAD

**Issue by JakePartusch** [aws-amplify/amplify-js#2775]
**Describe the bug**
When using a reverse proxy rewrite, as described here:
https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#reverse-proxy-rewrite
Only 200 response are successfully proxied. Failure responses are not proxied.

**To Reproduce**
1. Configure a reverse proxy as described here: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#reverse-proxy-rewrite
2. Attempt to proxy to an endpoint that returns an unsuccessful status code.
3. See that the endpoint is not proxied

**Expected behavior**
It is expected that the reverse proxy successfully proxies the matching endpoint regardless of the status code response.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: macOS 10.14
 - Browser: Chrome 72

**Smartphone (please complete the following information):**
 - NA

**Additional context**
Writing a SPA, with reverse proxies to series of API Gateways to service as the backend of the application.

**Comment by swaminator** [comment]
@JakePartusch thanks for reporting this issue. I think it isn't proxying it through because there's a conflicting 404 rule setup in your redirects. Try deleting that rule and you should see the error codes returned. Out of curiosity, what's your usecase for wanting error codes returned for the reverse proxy?

**Comment by JakePartusch** [comment]
@swaminator Thank you. It seems like the default 404 rule for `<*>` to `index.html` was causing the problem. I replaced that with the SPA redirect here:
https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa

The reverse proxy is to an API Gateway, where error codes are necessary to service the frontend effectively.
