### ISSUE TITLE
How to "upgrade" an unauthorized user to an authorized user?

### ISSUE THREAD

**Issue by mitchellsimoens** [aws-amplify/amplify-js#2776]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Cognito User Pool and Federated Identities, DynamoDB, Pinpoint

I have my Cognito User Pool and Federated Identities configured to work with an oauth/openid server. This works great and I can login just fine and get the jwt tokens as expected. However, I also want to support unauthorized identities which I can get the session token via:

```javascript
const { sessionToken } = await Auth.currentCredentials();
```

Reload the page and that token updates but is still tied to the same identity as I can see cached in localStorage too. Now when I go to login and I get back to my app and amplify sees the `code` url param it then gets the tokens. I think how I'm getting that session token may be the reason as I'm getting two identities showing up and one gets a link because in all I do this:

```javascript
    const { identityId, sessionToken } = await Auth.currentCredentials();

    if (sessionToken) {
      const config = Auth.configure();

      AWS.config.credentials = new CognitoIdentityCredentials({
        IdentityId: identityId,
        Logins: {
          [`cognito-idp.${config.region}.amazonaws.com/${config.userPoolId}`]: sessionToken,
        },
      }, {
        region: config.region,
      });
    }
```

On first page load, I execute this code and I have a new identity in Cognito (unlinked). I go to login and once redirected back to my app, this code executes and it creates a new identity but is then linked. This code is executed on body load so it may be a racing condition from when amplify handles the `code` url param or my logic needs to be made smarter. tbh I'm not sure what a linked identity really means.

We use dynamodb (among other services) and want to use the fine grained permissions that are based off Cognito user so both unauthorized and authorized users should be available to be handled and seamlessly move from unauthorized to authorized.

Thank you for any help.

**Comment by powerful23** [comment]
@mitchellsimoens is this related to #2089 ?
