### ISSUE TITLE
Custom forgotPassword 

### ISSUE THREAD

**Issue by Strenget** [aws-amplify/amplify-js#2778]
Hello! I need help with implementation custom forgotPassword, I have template and it works fine, but I have problem with change state to requireNewPassword before Auth.forgotPassword.
I get error "**Cannot read property 'requiredAttributes' of undefined**" when I call my function 

`resetPassword () {
        Auth.forgotPassword(this.state.email)
            .then(data => super.changeState("requireNewPassword"))
            .catch(err => this.error(err));
    }`
the verification code is sent to my email address.

Thank you!

**Comment by sorokinvj** [comment]
@Strenget Ola! Have found the roots of the problem and hopefully workaround? 

Experience the same with custom ForgotPassword
