### ISSUE TITLE
Enable more fields in sign up

### ISSUE THREAD

**Issue by jahirfiquitiva** [aws-amplify/amplify-js#2784]
**Which Category is your question related to?**
Authentication

**What AWS Services are you utilizing?**
Cognito

**Provide additional details e.g. code snippets**

I want to enable the `Given Name` field since I made it required in AWS.

I'm trying to do so like this:

```javascript
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

import Amplify from 'aws-amplify';
import awsmobile from './aws-exports';
import { withAuthenticator } from 'aws-amplify-react';

Amplify.configure(awsmobile);

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <p>
            Edit <code>src/App.js</code> and save to reload.
          </p>
          <a
            className="App-link"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Learn React
          </a>
        </header>
      </div>
    );
  }
}

export default withAuthenticator(App, {
  signUpConfig: {
    signUpFields: [{ key: 'given_name', required: true }]
  }
});

```

But it shows a field without a title, and when "registering" an account, it shows this error:
`A client attempted to write unauthorized attribute`

What can I do to achieve what I want to? Thanks in advance

**Comment by gerrytsui** [comment]
regarding "a field without a title", I believe you will have to specify the "label" as in:
        {
          label: 'Given Name',
          key: 'given_name',
          required: true,
          displayOrder: 1,
          type: 'string',
        },

see doc at https://aws-amplify.github.io/docs/js/react#signup-configuration

I do something similar, but in Angular, so I am not 100% sure about the syntax.

**Comment by haverchuck** [comment]
@jahirfiquitiva I believe that @gerrytsui 's answer is correct.  I'm closing this issue for now, but please feel free to reopen.

**Comment by jahirfiquitiva** [comment]
I can't reopen it @haverchuck ... 

The problem is not only about the missing title, from the op:

when "registering" an account, it shows this error:
`A client attempted to write unauthorized attribute`

**Comment by gerrytsui** [comment]
Not sure this applies to you, another common mistake is make sure custom attributes are prefixed with custom:field_name . e.g. I have "custom:company"

**Comment by jahirfiquitiva** [comment]
@gerrytsui No, `given_name` is one of the default attributes provided in cognito

![captura de pantalla 2019-03-05 a la s 3 38 23 p m](https://user-images.githubusercontent.com/10360816/53835979-c075d680-3f5c-11e9-8bf4-631fc33b44dc.png)

**Comment by jahirfiquitiva** [comment]
@haverchuck  mind opening this issue again? it isn't solved yet :/
