### ISSUE TITLE
React: SignIn captures global keydown event to submit form

### ISSUE THREAD

**Issue by phjardas** [aws-amplify/amplify-js#2791]
**Describe the bug**
The SignIn form registers a [global event handler for `keydown`](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Auth/SignIn.jsx#L53). The handler checks whether `[enter]` was pressed and then submits the form.

However, the event handler is triggered when `[enter]` is pressed _anywhere_ on the page, even in another form. That means when a user presses enter on a page where the sign-in dialog is visible, they always get a very prominent error message that the sign in has failed.

**To Reproduce**
1. Create a page where there's a regular `<form>` with an `<input>` plus an `<Authenticator>`
2. Focus the regular input and press enter --> the sign-in-form will produce an error.

**Expected behavior**
The sign-in form should instead use a regular `<form onSubmit={...}>`. The submit button then doesn't need an `onClick` handler but simply becomes `type="submit"` and hence triggers the form submit. That's what forms are for after all. No need to reinvent anything.

I'd be happy to contribute a PR if you like.

**Comment by elorzafe** [comment]
@phjardas which frontend framework are you using?

**Comment by phjardas** [comment]
@elorzafe Sorry forgot to mention: `aws-amplify-react`.

**Comment by elorzafe** [comment]
@phjardas the issue is reproduced, @jordanranz what do you think?

**Comment by elorzafe** [comment]
@phjardas Please feel free to submit a PR, if you reference it to this issue it will be great. Thanks!

**Comment by jordanranz** [comment]
Seems related to:
https://github.com/aws-amplify/amplify-js/commit/f872234f6466765b62fb7c36821ff03228f9f137

@powerful23

**Comment by phjardas** [comment]
Yeehaaw, thanks for the quick fix! 😍
