### ISSUE TITLE
API put "AccessDeniedException" does not end catch

### ISSUE THREAD

**Issue by rozhali** [aws-amplify/amplify-js#2793]
**Describe the bug**
API.put, getting "AccessDeniedException" error back but it is not ending up in the catch block

**To Reproduce**

`API.put(apiName, "/orders", myInit).then(response => {
                // Add your code here
                console.log("response: ", response);
                navigation.navigate("ConfirmReceipt");
            }).catch(error => {
                console.log("error.response from put: ", error.response)
                console.log("Navigate to error page");
            });`

**Expected behavior**
This should end up in the catch block and not the response.

**Screenshots**
![screen shot 2019-03-02 at 5 01 34 pm](https://user-images.githubusercontent.com/16752065/53689524-fde42500-3d0c-11e9-92d0-0162d3dc438d.png)

**Additional context**
This is a react native project, and the backend has been generated via the amplify CLI

**Comment by manueliglesias** [comment]
Hi @rozhali 

Looks like the [sample lambda code](https://github.com/aws-amplify/amplify-cli/blob/d7d4b3f947747bc4be5deb4cca4bea06cfff3cf5/packages/amplify-category-function/provider-utils/awscloudformation/function-template-dir/crud-app.js.ejs#L147) generated by the cli doesn't have robust error checking and therefore it doesn't set an error status (this is why your catch is not being called).

One thing you can try is to throw from your `then` if there's an `error` in the response, e.g.

```js
API.put(apiName, "/orders", myInit)
  .then(response => {
    if(response.error) {
        throw response.error;
    }
    return response;
  })
  .then(response => {
    console.log("response: ", response);
    navigation.navigate("ConfirmReceipt"); 
  }).catch(error => { 
    // this is where you handle errors from the client
    console.log("error.response from put: ", error.response) console.log("Navigate to error page"); 
  });

```

Please feel free to open a new issue if you still have problems.
