### ISSUE TITLE
cognito is checking verify email before check correct password using swift

### ISSUE THREAD

**Issue by yazoonic** [aws-amplify/amplify-js#2795]
**Describe the bug**
when user is signed up and not confirmed. and you want to sign in again 

even if you enter incorrect password, error will come as user is not verified, it should first check the if the username/password is correct before sending user is not confirmed 

unless I misunderstood the flow in cognito API  using swift 

**To Reproduce**
1. signup with email 
2. dont verify the email 
3. use the below method in your code  

AWSMobileClient.sharedInstance().signIn(username: "your_username", password: "Abc@123!") { (signInResult, error) in
    if let error = error  {
        print("\(error.localizedDescription)")
    } else if let signInResult = signInResult {
        switch (signInResult.signInState) {
        case .signedIn:
            print("User is signed in.")
        case .smsMFA:
            print("SMS message sent to \(signInResult.codeDetails!.destination!)")
        default:
            print("Sign In needs info which is not et supported.")
        }
    }
}

4. enter any dummy password 
5. error will be user not verified even if password is incorrect 

**Expected behavior**
it should check if username/password is correct before check if user verified. since in app logic, if user is not verified we will send them to verify page, 

if some one knows subscriber email, he will keep sending resend key 

**Screenshots**
NA

**Additional context**
I didnt test using Android but I guess its the same

Versions:-

The following pod updates are available:

- AWSAuthCore 2.8.4 
- AWSCognitoIdentityProvider 2.8.4 
- AWSCore 2.8.4 
- AWSMobileClient 2.8.4

**Comment by powerful23** [comment]
@yazoonic to make your issue resolved/responded more efficiently, can you submit your request/issue to the AWS Discussion Forums? https://aws.amazon.com/premiumsupport/knowledge-center/send-feedback-aws/ Thanks!

**Comment by yazoonic** [comment]
I just posted this on the forums

**Comment by powerful23** [comment]
@yazoonic thanks!
