### ISSUE TITLE
Is there any way to assign custom metadata while uploading object using Storage ?

### ISSUE THREAD

**Issue by athJ** [aws-amplify/amplify-js#2799]
I am uploading a video file to S3 using Storage , is there any way to send custom metadata along with the request .
This is my current code:
```
Storage.put(uuidv4() + ".mp4", {
    level: 'public',
    contentType: 'audio/mp4',
    x-amz-meta-xyz:''
  })
```
I am getting error when using "x-amz-meta-key" which is standard way to define custom metadata.

**Comment by jkeys-ecg-nmsu** [comment]
Is that valid JavaScript syntax? I think you might need to make that a computed property name, like this:

```
Storage.put(uuidv4() + ".mp4", {
    level: 'public',
    contentType: 'audio/mp4',
    ['x-amz-meta-xyz']:''
  })
```

See this reference for computed properties syntax. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer

**Comment by athJ** [comment]
@jkeys-ecg-nmsu Thanks , I tried using computed property but it didn't work .I am not getting an error while using computed property but the properties aren't reflected in the uploaded object either.

**Comment by powerful23** [comment]
@athJ this is a feature request since currently there is no way to do that. We will discuss it in our team meeting. Thanks!

**Comment by credator** [comment]
I may be misunderstanding, but it appears that metadata can be specified in the `config` parameter (3rd parameter) of `Storage.put`

e.g.
```javascript
Storage.put('example.txt', 'example', { metadata: { foo: 'bar' } });
```
Creates an S3 Object with metadata: `x-amz-meta-foo = bar`

At least it seems to for me.

**Comment by athJ** [comment]
<img width="655" alt="screenshot 2019-03-06 at 9 53 37 am" src="https://user-images.githubusercontent.com/16134050/53855941-c7045c80-3ff5-11e9-93ce-ceff82ce6ae7.png">
@credator The config properties that are supported are specified in this comment within the source code, metadata isn't one of them.

**Comment by credator** [comment]
The source comment may not be up to date as the source itself shows support for a lot more options (a few lines down):

https://github.com/aws-amplify/amplify-js/blob/master/packages/storage/src/Providers/AWSS3Provider.ts#L157

```javascript
const { bucket, region, credentials, level, track, progressCallback } = opt;
const { contentType, contentDisposition, cacheControl, expires, metadata, tagging } = opt;
const { serverSideEncryption, SSECustomerAlgorithm, SSECustomerKey, SSECustomerKeyMD5, SSEKMSKeyId } = opt;

...

if (cacheControl) { params.CacheControl = cacheControl; }
if (contentDisposition) { params.ContentDisposition = contentDisposition; }
if (expires) { params.Expires = expires; }
if (metadata) { params.Metadata = metadata; }
if (tagging) { params.Tagging = tagging; }
```

These are converted to the corresponding aws-sdk S3 parameter (which the Storage class uses), which are documented here: 
 https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property

I can't speak to this meaning the behaviour is subject to change by the amplify js team however.

On another note, I noticed in your original comment you were using dashes in your object key name.  Just in case it was throwing you off, you'll want to put quotes around that for it to be valid javascript.  In JS `{foo: 'bar'}` and `{'foo': 'bar'}` is equivalent.  The quotes around the key name are optional, unless the key is not a valid identifier, eg. if it has dashes, dots, or spaces.  So in the above you would want: `{'x-amz-meta-xyz': ''}`

Though I still think `{ metadata: { xyz: '' } }` will get you the behaviour you desire.

**Comment by athJ** [comment]
@credator Thanks , you got a point . I'll give it a try using metadata.

**Comment by elorzafe** [comment]
@athJ I commented [here](https://github.com/aws-amplify/amplify-js/issues/2974#issuecomment-479593590) how to use tags for S3 uploads. I hope this worked for you.

**Comment by athJ** [comment]
Gotcha , this needs to be mentioned in the Amplify docs.Thanks @elorzafe
