### ISSUE TITLE
Module not found: Can't resolve 'react-native'

### ISSUE THREAD

**Issue by mastertinner** [aws-amplify/amplify-js#2808]
Since upgrading to `@aws-amplify/auth` from `1.2.15` to `1.2.17`, I'm getting the following error from `eslint`:

```
./node_modules/@aws-amplify/auth/lib/Auth.js
Module not found: Can't resolve 'react-native' in '/opt/atlassian/pipelines/agent/build/node_modules/@aws-amplify/auth/lib'
```

**Comment by deinspanjer** [comment]
I'm getting this too.
Maybe it is related to this commit that adds react-native as a peer dependency?
https://github.com/aws-amplify/amplify-js/commit/ac4d232a8ada0fd4f2e19c2e7196a8937dc63e0e

**Comment by sc-pulsion** [comment]
Getting this as well. Worked yesterday.

**Comment by caseyrodgers** [comment]
I'm getting this too .. and, I'm trying to create an ionic app .. not react.

`[ng] WARNING in ./node_modules/@aws-amplify/auth/lib/Auth.js
[ng] Module not found: Error: Can't resolve 'react-native' in node_modules\@aws-amplify\auth\lib'
`

**Comment by powerful23** [comment]
Hi All, we are looking into this issue. Thanks for reporting!

**Comment by datoml** [comment]
I can confirm that the issue is fixed now.
Thanks!

**Comment by jadbox** [comment]
Latest version on npm is still broken
