### ISSUE TITLE
server side validation approach for cross attribute checks?  (

### ISSUE THREAD

**Issue by callagga** [aws-amplify/amplify-js#2809]
What would be the best approach to utilise for a React (typescript) single page application, using amplify to create a graphql API backend, to carry out backend validation checks on API calls?   I'm assuming the concept from a security perspective should still be validate at the backend.  

Interested in answer for:
A. new object that the "start date" is prior to the "end date" - so across different attributes
B. business logic checks (more complex)

Background: I can see the ease in which the single page app (React approach) with graphql serverless backend using amplify is great, but then got to basic validation and wondering how to implement A above - e.g. do I have to learn how to use GraphQL Transforms.  But then if the backend validation checks extend out to include B it kind of implies your domain model and more complex validations should really be modelled in the backend no, so then how do you do this with the AWS stack?

**Comment by powerful23** [comment]
Related #2826

**Comment by callagga** [comment]
More specific question here (agreed): https://github.com/aws-amplify/amplify-js/issues/2826

(I'll see if I can delete this one)
