### ISSUE TITLE
How can I get other cognito user attributes like created_at?

### ISSUE THREAD

**Issue by flybayer** [aws-amplify/amplify-js#2813]
**Which Category is your question related to?**
Authentication

**What AWS Services are you utilizing?**
Cognito

**Provide additional details e.g. code snippets**
I can get the user sub, email, and other attributes like first_name by doing this
```js
const user = await Auth.currentAuthenticatedUser()
```
However, I can't find any way to get the created_at datetime.

**Comment by powerful23** [comment]
@flybayer hi, the only way to achieve that data is to use the `AdminGetUser` API provided by Cognito team: https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminGetUser.html which is not available when using Amplify.

**Comment by jkeys-ecg-nmsu** [comment]
@flybayer you could use the admin API suggested by @powerful23 and then store the result as a custom claim in your token during the pre-token generation Cognito trigger. Then you could just access it from the token like any other claim.

**Comment by powerful23** [comment]
@flybayer I am going to close this issue. Please let us know if you want to reopen it.
