### ISSUE TITLE
[@aws-amplify/auth@1.2.17] has unmet peer dependency react-native and buffer@4.x

### ISSUE THREAD

**Issue by JustFly1984** [aws-amplify/amplify-js#2814]
I have issues with graphql dependency hell in my gatsby.js app, so I did install only Auth part of aws-amplify instead of full package.

warning " > @aws-amplify/auth@1.2.17" has unmet peer dependency "buffer@4.x".
warning " > @aws-amplify/auth@1.2.17" has unmet peer dependency "react-native@^0.44.0".

Should I install `buffer` to my direct dependencies?

I'm sure that I do not need react-native, cos my app is simple React.js.

Should react-native to be removed from peer-dependencies?

**Comment by powerful23** [comment]
@JustFly1984 this issue is related to #2808 . We are currently working on it.

**Comment by JustFly1984** [comment]
@powerful23 #2808 is related to react-native, but what should I do with buffer@4 ?

Thank you for quick response
