### ISSUE TITLE
warning " > @aws-amplify/auth@1.2.18" has unmet peer dependency "buffer@4.x".

### ISSUE THREAD

**Issue by JustFly1984** [aws-amplify/amplify-js#2816]
Should I install this `buffer@4` or leave it as it is?

**Comment by powerful23** [comment]
@JustFly1984 hi you can leave it. We are going to remove it in our next release. Thanks for reporting.

**Comment by jordanranz** [comment]
Closing this as the question is answered. Please reopen if you have any related questions or concerns.
