### ISSUE TITLE
How to achieve subscription with filters without datasource?

### ISSUE THREAD

**Issue by joseph-d-p** [aws-amplify/amplify-js#2817]
### Which Category is your question related to? 
Amplify

### What AWS Services are you utilizing?
Appsync

### Provide additional details e.g. code snippets
Is there a way for subscription to receive input filters as parameter similar to queries and mutation?

Currently, my subscription doesn't have a data source and I wanted to only receive subscriptions if this field begins with this value.

**Sample Mutation response**

    {
      taskId: "personal-<uuid>",
      name: "Personal Task 1",
      ...
    }

Basically, I only want to have one subscription to check for all task updates where  `taskId` `beginsWith` the `String` **"personal"**.

**Schema**

```
input TableStringFilterInput {
  ne: String
  eq: String
  le: String
  lt: String
  ge: String
  gt: String
  contains: String
  notContains: String
  between: [String]
  beginsWith: String
}

input TaskInput {
  taskId: ID!
  ...
}

input TaskFilterInput {
  taskId: TableStringFilterInput
}

mutation updateTask(task: TaskInput) :  Task
subscription onTaskUpdated(filter: TaskFilterInput) : Task
@aws_subscribe(mutations, ["updateTask"])
```

**Test subscription using Appsync's query console**
```
subscription TaskUpdated {
  onTaskUpdated(filter: {
    taskId : { beginsWith: "personal" },
  }) {
    taskId
    name
  }
}
```

**Others**
I know that the `filter` is more of a `DynamoDB` thing for queries and mutation.
I just wanted to know if this is possible and how to achieve such?

**Comment by jkeys-ecg-nmsu** [comment]
Have you considered making the relevant models `@searchable` and using ElasticSearch to filter your response?

Personally I don't like the idea of using an (expensive) NLP service to simulate relational queries, but I think AppSync & Amplify team will be adding features in the near future that will ameliorate this problem.

**Comment by haverchuck** [comment]
Hello @joseph-d-p  - Filtering the runtime results of a subscription is not supported today in AppSync.  However, you may be able to achieve your use case by using [subscription arguments](https://docs.aws.amazon.com/appsync/latest/devguide/real-time-data.html#using-subscription-arguments).

**Comment by krsnaa** [comment]
@joseph-d-p, you could do what you are considering using custom resolvers, performing the beginsWith check in the response mapping template. check out the approach in https://docs.aws.amazon.com/appsync/latest/devguide/security-authorization-use-cases.html#real-time-data
