### ISSUE TITLE
Access user pool configuration information and metadata (DescribeUserPool)

### ISSUE THREAD

**Issue by DJWoodZ** [aws-amplify/amplify-js#2818]
**Is your feature request related to a problem? Please describe.**

I would like to access user pool configuration information and metadata via the **amazon-cognito-identity-js** package.

**Describe the solution you'd like**

The [DescribeUserPool](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_DescribeUserPool.html) Action appears to offer the required information. A `getUserPoolData()` function could be added to [CognitoUserPool.js](https://github.com/aws-amplify/amplify-js/blob/master/packages/amazon-cognito-identity-js/src/CognitoUserPool.js) which returns the response from this action.

**Comment by Joao-Leite** [comment]
2nd that.
Does anyone know if there's a workaround to fetch the password policy from Cognito with Amplify? (which could be achieved with the getUserPoolData() you mentioned)

**Comment by undefobj** [comment]
@DJWoodZ I believe that API requires administrative permissions and as such isn't designed to be called by a client application, which is what the Amplify library is designed for. Can you give us details on your use case and why this is needed?

@Joao-Leite similar question - is there a reason you need the password policy in a client application? Is this for a particular workflow?

We are looking at adding functionality to the Amplify CLI that might meet your needs. Can you look at the "Admin Queries" section of the following RFC? https://github.com/aws-amplify/amplify-cli/issues/766

**Comment by Joao-Leite** [comment]
@undefobj The idea would be to show the password requirements on the frontend side without having to hardcode the rules on the application

**Comment by undefobj** [comment]
@Joao-Leite currently Cognito doesn't support that, and there would be questions that need to be asked on if that opens up any security concerns related to information disclosure of the policy. I think the RFC above would fit your needs for the time being.

**Comment by DJWoodZ** [comment]
@undefobj Thank you for responding. We are using the Amplify library client-side. Our current requirement is to access the `AllowAdminCreateUserOnly` value so that we dynamically enable/disable our application's sign up feature.

**Comment by DJWoodZ** [comment]
@undefobj does the use case I shared sound feasible? If not, do you have any advice for how we could react dynamically to the `AllowAdminCreateUserOnly` value, please?

**Comment by sammartinez** [comment]
@DJWoodZ I believe [Cognito Lambda Triggers](https://aws-amplify.github.io/docs/cli-toolchain/cognito-triggers) will cover this case. This work is complete. Resolving this request as complete since this work is complete.
