### ISSUE TITLE
Howto i18n translate the signin input labels of amplify-authenticator

### ISSUE THREAD

**Issue by sprucify** [aws-amplify/amplify-js#2819]
Since the latest release today, we have more i18n translate options.
But how do I control and translate the input labels of the SignIn form of the amplify-authenticator?
For SignUp I use signUpConfig to do the translation

**Comment by haverchuck** [comment]
@sprucify Assuming you installed via the unstable branch (npm i aws-amplify-angular@unstable), you should be able to do something like this:

main.ts:
```
Amplify.I18n.setLanguage('fr');

const dict = {
  'fr': {
      'Sign In': "Se connecter",
      'Username *': 'Nom d\'utilisateur'
  },
};
```

Username * is the text in the current sign in username label, so this dict object will automatically translate it to 'Nom d\'utilisateur' or whatever you enter.

You can also access the I18n module within an actual angular component using the AmplifyService provider, but for most cases the code above is probably the easiest approach.

I'm closing this for now, but feel free to reopen.

**Comment by sprucify** [comment]
Ah ok that works.
Didn't know the fields had an * behind it, since that is not showed on the signin form
