### ISSUE TITLE
Handling complex objects with GraphQL AppSync for a React Native front-end

### ISSUE THREAD

**Issue by jtaylor1989** [aws-amplify/amplify-js#2820]
** Which Category is your question related to? **

GraphQL AppSync, handling complex objects.

** What AWS Services are you utilizing? **

AWS Amplify, GraphQL AppSync, S3, and DynamoDB.

** Provide additional details e.g. code snippets **

I am trying to implement file upload to S3 and saving their references in DynamoDB using GraphQL AppSync for my React Native application.

The documentation for this is very poor and push you to swim into a GitHub repo that implements this feature for a React JS website using the AppSync SDK! 

I would like to see a detailed example of how to implement this feature with GraphQL AppSync and React Native (schema, mutations, front end code).

Much appreciated.

**Comment by powerful23** [comment]
@jtaylor1989 can you check this repo: https://github.com/aws-samples/aws-mobile-appsync-events-starter-react-native ? Hope that would help you.

**Comment by jtaylor1989** [comment]
Sadly no. My question is specific to complex objects such as pictures and videos.

**Comment by manueliglesias** [comment]
Hi @jtaylor1989

We'll be opening a PR in the docs repo to add a file upload example for react native.

For now, you can try this:

To use files in react-native, the [Amplify docs for the Storage category](https://aws-amplify.github.io/docs/js/storage#put) have sample code using `react-native-fetch-blob`.

```js
import RNFetchBlob from 'react-native-fetch-blob';

const buffer = await RNFetchBlob.fs.readFile(filePath, 'base64').then(data => new Buffer(data, 'base64'));
```

Then, you can pass the buffer to your mutation like [this](https://github.com/aws-samples/aws-amplify-graphql/blob/9fd58a12f7dd7f482d2162f9ec6c129736776728/src/Components/AddPhoto.js#L54-L66):

```js
const file = {
    bucket,
    key,
    region,
    mimeType,
    localUri: buffer,
};

// the mutation
createPicture({ name, owner, visibility, file });
```

[More info for complex objects when using `aws-appsync` in the browser](https://aws-amplify.github.io/docs/js/api#complex-objects)

**Comment by jtaylor1989** [comment]
react-native-fetch-blob is deprecated. You should update the docs with the new repo named rn-fetch-blob.
