### ISSUE TITLE
How to perform client-side validation of AWSPhone input (which requires valid / registered telephone number)

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-js#2825]
I discovered that the AWSPhone resolver, by default, only accepts valid phone numbers. That is, putting in fake numbers that satisfy a traditional phone regex (e.g. `[0-9]{3}-[0-9]{3}-[0-9]{4}`) will result in a failed GraphQL operation.

How can the phone number be validated against the AWSPhone resolver -- which I guess looks up some national directory of registered phone numbers? -- from the client, before the mutation is sent?

I suppose the error could be caught on the client, forcing a "re-signup" flow, but I'd rather be able to determine whether the entered number is valid before performing the GraphQL operation.

** Which Category is your question related to? **
API

** What AWS Services are you utilizing? **
Amplify, AppSync, { graphqlOperation }

**Comment by jkeys-ecg-nmsu** [comment]
To clarify, this is the input that fails:

`575-111-1111`, `575-222-2222`

Area code (575) -- **southern New Mexico represent!** -- does not use `111` or `222`, so the AWSPhone validation may simply be recognizing that (575) does not use `111` or `222`. (In other words, my original supposition that a national database of registered phones is conjecture, b/c a phone number can be found invalid just by checking its area code against the following three digits.)

Even still, I have no idea how this information is validated. Is it by area code compared against first three digits, or is it looking for actual registered phone numbers?

**Comment by manueliglesias** [comment]
Hi @jkeys-ecg-nmsu 

> How can the phone number be validated against the AWSPhone resolver -- which I guess looks up some national directory of registered phone numbers? -- from the client, before the mutation is sent?

We don't offer validators that complex in Amplify, but I have  suggestion for you, you could try [libphonenumber](https://github.com/googlei18n/libphonenumber/tree/master/javascript) for client side validation of phone numbers.

I hope this helps.

**Comment by jkeys-ecg-nmsu** [comment]
@manueliglesias The AWSPhone scalar type does the validation on the backend, so I'm primarily interested in what rules AppSync has to determine whether an AWSPhone type is valid input.

The library you suggested doesn't tell me how AppSync validates, so I don't know if it will catch all invalid numbers.

**Comment by manueliglesias** [comment]
@jkeys-ecg-nmsu That would be a service related question, you can try contacting the AppSync service team on their [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=280)
