### ISSUE TITLE
currentAuthenticatedUser bypassCache true, dosesn't get the latest user information 

### ISSUE THREAD

**Issue by htobenothing** [aws-amplify/amplify-js#2827]
**Describe the bug**
when assign new group to user in Cognito, and try to get group information from accessToken. The group information not update. 

```js
    Auth.currentAuthenticatedUser({
        bypassCache: true 
    }).then(authData=>{
        let groups =authData["signInUserSession"]["accessToken"]["payload"]["cognito:groups"];
    })
```

version:     "aws-amplify": "^1.1.10"

**Comment by powerful23** [comment]
@htobenothing I will mark this as bug.

**Comment by powerful23** [comment]
The root cause is that currently when setting `bypassCache` to true, the library only gets the latest user attribute which doesn't contain the user group info. Since the user group info can only be achieved from access token, we need to refresh the accessToken as well.

**Comment by luis-felipe-llamas** [comment]
@powerful23 I have the exact same issue. Is there a current workaround for this (like manually telling Amplify to refresh the accessToken)?

**Comment by nihp** [comment]
@powerful23 I am using  Auth.currentAuthenticatedUser({ bypassCache: true }) and Auth.currentSession();

Still I am facing the 401,{"message":"The incoming token has expired"}

Here Auth.currentSession will handle the token expiry and refresh tokens. Then how I am facing this error?

```

            Auth.currentAuthenticatedUser({ bypassCache: true })
                .then(u => {
                    console.log('Auth.currentAuthenticatedUser result:', u);
                }, err => {
                    console.log(err)
                });
        });


export async function get (endpoint: string, data?) {
    const currentSession = await Auth.currentSession();
    const providerId = currentSession.getIdToken().payload.sub;
    const identityJwt = currentSession.getIdToken().getJwtToken();
    return GET(endpoint, data, identityJwt, providerId);
}
```
