### ISSUE TITLE
Storage.list doesn't list contents. Though config correctly displays bucket-name.

### ISSUE THREAD

**Issue by willkara** [aws-amplify/amplify-js#2828]
**Describe the bug**
Storage.list does not list bucket contents. I've tried tons of permutations of paths, but nothing lists.

**To Reproduce**
```
    Storage.list('images/photos')
      .then(result => console.log(result))
      .catch(err => console.log(err));


    console.log(Storage);
```

**Expected behavior**
A list of keys/objects from my bucket. 

**Screenshots**

1. Example code
2. Output of code.

![storage_snip](https://user-images.githubusercontent.com/3278887/54004282-02507980-4123-11e9-8d43-f96ccb8eb35f.PNG)
![storage_snip2](https://user-images.githubusercontent.com/3278887/54004283-02507980-4123-11e9-97b3-6b990904ea9c.PNG)

**Desktop (please complete the following information):**
Chrome/FF/FF Quantum

I am trying to list the contents in one of my buckets, but nothing seems to be working. Every object is marked as public and there are no ACLs on it. I've attached images of my bucket structure below. My guess is I'm somehow messing up the paths.

![struct1](https://user-images.githubusercontent.com/3278887/54004384-5fe4c600-4123-11e9-97d8-3d56e0387ba7.jpg)
![struct2](https://user-images.githubusercontent.com/3278887/54004385-5fe4c600-4123-11e9-877c-c32d08465a08.jpg)

**Comment by powerful23** [comment]
@willkara can you provide more info like the response of `Storage.list` or any debug info? You can open the debug mode by `window.LOG_LEVEL='DEBUG'`

**Comment by willkara** [comment]
@powerful23 here's the output with debug mode enabled for listing '/'. I get the same for:

- 'images/photos'
- 'images'
- '/'

![list_pub](https://user-images.githubusercontent.com/3278887/54055698-d7feca80-41bb-11e9-94c5-aad46bac25a8.jpg)

What's curious is the line that states:

`[DEBUG] 03:19.706 AWSS3Provider - list images from public/images`

Does that mean it's trying to list something from a 'public' folder in the bucket? I also tried creating a folder named public in my bucket and put a few files in there, but nothing happened.

**Comment by jtaylor1989** [comment]
The uri of the image is surprisingly absent from the object item of the Storage.list() response. 
Only by calling Storage.get() on every item of the list that we will get the uri. 
To list content, try similar code to the one below.

<img width="579" alt="list" src="https://user-images.githubusercontent.com/26605247/54055690-bd414b80-41e5-11e9-967d-03c75b70bc99.png">

You can call your fetchImages in a lifecycle method to diplsay content.

**Comment by tmoore23** [comment]
Has there been an update on this? I am experience the same issue where my code is returning an empty array when doing the following:

```
componentWillMount(){
        console.log('Calling S3');
      	Storage.list('/', { level: "public" })
      		.then (result => console.log('Result:', result)) // {key: "test.txt"}
    		.catch(err => console.log(err));
}
```

**Comment by chai86** [comment]
@jtaylor1989 @elorzafe I'm horrified! So we have to call Storage.get() on EACH item to get the URI??? That's expensive and poorly thought out, as i could have thousands of images whose URI i need to reference. Why can't we use Storage.list() to get at these?

**Comment by GORGES** [comment]
Any progress on this problem? I updated to the latest Amplify libraries for a JavaScript project, and now I am unable to list the contents of a bucket. There is NO OTHER feedback even when logging is activated - I just get an empty set back without any error messages. This is a darn important feature.

**Comment by powerful23** [comment]
@willkara really sorry for the late response. From the debug log I can tell the path is not correct as it's `public//` rather than `images/photos`. If you want to your own customized path, please check the doc: https://aws-amplify.github.io/docs/js/storage#customization

**Comment by powerful23** [comment]
@tmoore23 @GORGES @chai86 can you open the debug mode to see if credentials are loaded and the path is correct when calling `Storage.list`? Thanks!

**Comment by tmoore23** [comment]
@powerful23 how to validate the path is correct?

**Comment by tmoore23** [comment]
@powerful23 nvm figured it out and the log says the following:

[DEBUG] 58:15.430 AWSS3Provider - list <bucket-name>/ from public/<bucket-name>/

**Comment by tmoore23** [comment]
@powerful23 After adding a public folder within my bucket, I am able to see the list of objects. Is this expected behavior?

**Comment by willkara** [comment]
I'll have to check it out. Just haven't had the time recently.

**Comment by jordanranz** [comment]
@willkara, is this safe to close?

**Comment by FBen3** [comment]
Having the same issue. Doesn't matter what I replace path variable with: `/` , `*`, `''`

```
async function listObjects() {
  Storage.list('s3://amplify-mythirdapp-dev-170201-deployment/',{level:'public'})
    .then(result => console.log(result))
    .catch(err => console.log(err));
}
```
returns `Array []`

<img width="326" alt="Screen Shot 2020-10-13 at 19 37 40" src="https://user-images.githubusercontent.com/15108826/95901684-9c5eb600-0d8b-11eb-812a-407d94979e36.png">

**Comment by ttngocthao** [comment]
i cant list items in the public folder. return 403 forbidden.I can get single image but cant use the list method. Have anyone experienced this before? What should i check/change in order to make it work?
![Screenshot 2020-10-15 at 17 36 28](https://user-images.githubusercontent.com/36475218/96159917-2a15df00-0f0d-11eb-9e49-d77988e0d608.png)

**Comment by FBen3** [comment]
@tmoore23 Unfortunately the result is the same - it makes no difference if I prefix with `s3://`. Also checking `aws s3api list-objects --bucket amplify-mythirdapp-dev-170201-deployment` it correctly lists objects.

**Comment by thecloudslayer** [comment]
This works for me 

function lists3(){
  Storage.list('', { level: 'private' })
      .then(result => console.log(result))
      .catch(err => console.log(err));
}

![Screen Shot 2020-10-26 at 8 41 30 PM](https://user-images.githubusercontent.com/8225487/97243001-ad67e800-17cb-11eb-811c-d4614250a571.png)

**Comment by ttngocthao** [comment]
> @tmoore23 Unfortunately the result is the same - it makes no difference if I prefix with `s3://`. Also, checking with `aws s3api list-objects --bucket amplify-mythirdapp-dev-170201-deployment`, it correctly lists objects.

My cause was the list bucket permission. This link below helped me to solve the problem. I hope it works for you too.
[https://github.com/aws-amplify/amplify-cli/issues/3509]

**Comment by futurebenmorris** [comment]
Did we ever get a resolution to this? 

> @powerful23 After adding a public folder within my bucket, I am able to see the list of objects. Is it necessary to create a public folder in order for this to work? Seems like a hack.

I'm having exactly the same problem. Amplify seems to be hard coded under the hood to expect 'public', 'protected' and 'private' folders in an S3 bucket. I don't want to use the Amplify CLI to build my cloud resources (I want to do that myself) but I do want to use the 'aws-amplify' library in my frontend React project to handle auth and S3 access.

Currently, if I list bucket contents to a bucket which has only a public folder, and one object inside that public folder, as below:

```
async function testS3() {
  try {
    const list = await Storage.list('')
    console.log(list)
  } catch (error) {
    logger(error)
  }
}
```

I get an array with two elements back, which are the object and the folder.

![image](https://user-images.githubusercontent.com/86962014/137125490-bc4e79f8-708c-4d5b-938c-2c456828a1e2.png)

If I make the same call as above to a bucket which has no folders and one object, I get an empty array:

![image](https://user-images.githubusercontent.com/86962014/137126272-030691f8-6ba7-49f2-95a0-0e49ad1dc923.png)

I don't want to have to reach down for the AWS SDK as Amplify provides such a nice abstraction for dealing with AWS resources in the frontend.

Can you shed some light on what might be going on here?
