### ISSUE TITLE
Token is not expiring on signOut/globalsignOut

### ISSUE THREAD

**Issue by mashraf22** [aws-amplify/amplify-js#2829]
I am using angular6 inside using this amazon-cognito-identity-js. I am also using AWS user pool with federated identities.
When I am calling singOut/globalSignOut, Token is not beign exipired/invalidated.

**Comment by powerful23** [comment]
@mashraf22 can you provide more info?

> I am also using AWS user pool with federated identities.

Are `federated identities` federated with Cognito Federated Identity Pool or Cognito User Pool?

> Token is not beign exipired/invalidated.

Is the token from the Cognito User Pool or from the federated provider?

**Comment by mashraf22** [comment]
I am using Cognito User Pool.

**Comment by powerful23** [comment]
@mashraf22 Hi, sorry but can you provide more info about this issue? 

- The code snippets you are using? 
- Why would you claim the token is expired? Did you call some certain method and it returned back the error? 
- You can provide some debugging info by putting `window.LOG_LEVEL='DEBUG'` in your code. 

This would help us a lot to reproduce this issue. Thanks!

**Comment by mashraf22** [comment]
@powerful23 
I am using following architecture that is present in link:-
https://github.com/aws-quickstart/saas-identity-cognito

For generating token I am using following steps mentioned in image:-
![TokenGenerationSteps](https://user-images.githubusercontent.com/48320609/54423538-e35f7200-4736-11e9-9308-7cb73581d985.png)

In angular6 calling the singOut/globalSignOut of amazon-cognito-identity-js.

signout() {
    if (this._cognitoUser) {
      let name = this._cognitoUser.getUsername()
      this._cognitoUser.globalSignOut({
        onSuccess: function (msg) {
         var message = msg;
        },
        onFailure: function (err) {
          var error = err;
        }
      })

      
      //this._cognitoUser['signOut']()
      this.resetCreds(true)
      this._signoutSubject.next(name)
     
    }
  }

After signOut, I am consuming the service. In service, I have checked verifyToken, which verify token is valid or not. but it returns token is valid.


function verifyJwtToken(bearerToken) {
    var clientId = "";
    var userPoolId = getUserPoolIdFromRequest(bearerToken);
    var bToken = bearerToken.substring(bearerToken.indexOf(' ') + 1);
    var decodedIdToken = jwtDecode(bToken);
    if (decodedIdToken)
        clientId = decodedIdToken['custom:tenant_id'];
    const client = jwks({
        cache: true,
        rateLimit: true,
        jwksUri: 'https://cognito-idp.us-east-1.amazonaws.com/' + userPoolId + '/.well-known/jwks.json'
    });
    const [bearer, token] = bearerToken.split(' ');
    const [headerEncoded] = token.split('.');
    const { kid } = JSON.parse(atob(headerEncoded));
    new Promise((resolve, reject) => {
        client.getSigningKey(kid, (error, signingKey) => {
            if (error) return reject(error);
            return resolve(signingKey);
        });
    }).then((signingKey) => {
        return new Promise((resolve, reject) => {
            jwt.verify(token, signingKey.rsaPublicKey, {
                audience: clientId,
                issuer: `https://cognito-idp.us-east-1.amazonaws.com/${userPoolId}`,
                algorithms: ['RS256']
            }, (error, decoded) => {
                if (error) return resolve({ "isTokenExpired": true });
                return resolve({ "isTokenExpired": false });
            });
        });
    })
}

**Comment by powerful23** [comment]
@mashraf22 

> After signOut, I am consuming the service. In service, I have checked verifyToken, which verify token is valid or not. but it returns token is valid.

I am not understanding how it will tell if the token is valid or not. As I know, the most straight-forward way to check the token is to send a request to Cognito service with that token. If the request is accepted, then it means the token is still valid.

Please also make sure you are using `globalSignOut` to revoke the token. The `signOut` method only clears the local cache and the token will still stay valid.

**Comment by StefanBuchman** [comment]
I'm seeing the same result using React Native and Expo.

I'm using Auth.SignIn, however, Auth.SignOut is not revoking the token.  Using the global flag doesn't seem to change the result.

I can't seem to revoke tokens foe my current user.

**Comment by powerful23** [comment]
@StefanBuchman does the request `GlobalSignOut` sent to Cognito throw any error? Also can you provide some debugging log when you invoke the `signOut` method? To turn on the debugging mode, put `window.LOG_LEVEL = 'DEBUG'`.

**Comment by StefanBuchman** [comment]
Don't see any errors.  Here's the debug from calling SignOut and then after:

**Calling Auth.signOut({ global: true });**
`[DEBUG] 14:26.396 AsyncStorageCache - Remove item: key is federatedInfo
[DEBUG] 14:26.427 AuthClass - no current Cognito user
[DEBUG] 14:26.428 Analytics - on hub capsule auth Object {event: "signOut", data: null}`

**Calling Auth.currentAuthenticatedUser({bypassCache: true})**
`[DEBUG] 18:45.260 AuthClass - get current authenticated userpool user
CognitoUser {username: "s****@b*****.o**", pool: CognitoUserPool, Session: null, client: Client, signInUserSession: CognitoUserSession…}`

I don't have any authentication event firing.  I would have expected this to go back to the unauthenticated role.

**Comment by altinselimi** [comment]
@StefanBuchman did you manage to solve this ?

**Comment by nihp** [comment]
Facing the same issue. How can I make the session to clear

**Comment by panindravarma** [comment]
I am also getting the same issue. Did anyone able to get it working?
