### ISSUE TITLE
Federation for Google Sign in using a Cognito User pool NOT and Identity Pool

### ISSUE THREAD

**Issue by bonillam** [aws-amplify/amplify-js#2833]
** Which Category is your question related to? **
Implementing Google Sign in using AWS cognito user pools and a CUSTOM UI

** What AWS Services are you utilizing? **
Amplify, Cognito User pool 

** Provide additional details e.g. code snippets **
Using Expo + React Native + Amplify Frameworks. 

1. I've implemented Google Signin using the Expo library; That part works and I am able to get the user info + access token + id token;
2.  Entered the Google credentials in the Cognito user pool;
3. When I try to send the Google id token to AWS, through this call:

Auth.federatedSignIn('google', { token })
        .then(credentials => {
          console.log('get aws credentials', credentials);
        }).catch(e => {
          console.log('err', e);
        });
      } catch (e) {
        console.log("error", e)
      }

I get this error back: [NotAuthorizedException: Token is not from a supported provider of this identity pool.]

I've been trying to find support for this implementation for a while.  Very confusing docs and I am lost. Is the amplify team trying to push us towards the hosted UI? Not a loaded question, just want to understand what would be easier. 

I read about the callback "GoogleSingin", although I am not sure how/where to implement this callback.  Is it the case that I have to configure the use of the HOSTED UI anyways  and only then use the callbacks to create my own CUSTOM UI?

**Comment by powerful23** [comment]
@bonillam hi, if you want to federate with the Cognito User Pool, you should use the Cognito Hosted UI: https://aws-amplify.github.io/docs/js/authentication#using-amazon-cognito-hosted-ui and https://aws-amplify.github.io/docs/js/authentication#launching-the-hosted-ui-in-react-native

**Comment by bonillam** [comment]
Thank you @powerful23. As per the docs you pointed out,  I thought the Props could be used to create a custom UI (GoogleSignin prop, for example) instead of using the hosted UI.   

Are you telling me that I must setup and  configure and launch the hosted UI and only after that process, build the custom UI?

**Comment by powerful23** [comment]
@bonillam I mean you should follow the steps in the doc to make federation with Cogntio User Pool work. But yes you can have your own custom UI.

**Comment by Vahn84** [comment]
Hi, i'm having this issue too.

I followed the doc but i can't get past this error

    let userInfo = await GoogleSignin.signIn()

    Log("GOOGLE SIGN IN", userInfo)
    if (userInfo !== null && userInfo !== undefined && userInfo.idToken !== null) {

        let token = parseJwt(userInfo.idToken)
        Log("TOKEN", token)
        if (userInfo.user !== null && userInfo.user.email !== null && userInfo.user.name !== null) {

            const federatedUser: FederatedUser = {
                name: userInfo.user.name,
                email: userInfo.user.email,
            }
            const federatedToken: FederatedResponse = {
                token: userInfo.idToken,
                expires_at: token.exp
            };
            Log("FED", federatedToken, federatedUser)
            Auth.federatedSignIn('google', federatedToken, federatedUser)
                .then(response => {
                    Log("FEDERATED RESPONSE", response)
                })
                .catch(error => {
                    Log("FEDERATED ERROR", error)
                    dispatch({
                        type: LOGIN_ERROR,
                        payload: new Payload(null, error).setErrorMessage(error)
                    });
                })

        }


    }

What am i missing? Can you help me please? This issue is blocking me from hours

**Comment by pbirsinger** [comment]
Also getting this error. Trying to login from own UI components created by federated Authenticator react component. So is it true that we need to use the hosted UI for federated sign in?

Why is the section "Using Components from aws-amplify-react" even there then if this doesn't work at all?

**Comment by nipun3560** [comment]
@bonillam i'm working on same what you asked here. but i'm working on Android, however if you find any solution please share it with me. Thanks in adavance :)
