### ISSUE TITLE
Warning messages to help with permissions/configuration issues

### ISSUE THREAD

**Issue by elorzafe** [aws-amplify/amplify-js#2839]
**Is your feature request related to a problem? Please describe.**
Currently is not easy to debug permissions/configurations problems with the library, it would be nice to find warning messages with information related to this issues while invoking it.  
**Describe the solution you'd like**
- For example #2828 for Storage category can show a message in case the list of files is empty, or an object not found, or upload error, with common configurations problems or even pointing to issues related, with this the devs can find faster answer to what they are experiencing on their apps.

- The same occurs with Auth, aws credentials that are required on different services (Storage, API, Analytics, Interactions) this categories requires identityPool to be configured, so is a common case to point out on the warning messages. #2629

I created this issue to keep track of warning messages on different categories, not just auth.

**Comment by sammartinez** [comment]
@elorzafe There was work done recently in context to Error messages being displayed to have more granularity on configurations. Resolving this as complete.
