### ISSUE TITLE
Accessing AWS_IAM resources in Incognito browsers using Appsync bypasses all restrictions

### ISSUE THREAD

**Issue by selipso** [aws-amplify/amplify-js#2840]
**Describe the bug**
This seems like a major security issue related to the auth/unauth feature of AWS_IAM with Appsync. Hopefully it has already been reported by someone else. When creating a new resource (item in a DynamoDB table), by default AWS_IAM authentication uses an Identity ID to assign that resource to the holder of that Identity ID.

However, when you switch to incognito mode, and there is no Identity ID, a new one is assigned but all resources are available to that user in Incognito mode of a web browser. I've tried this using Angular and the Ionic framework on both Chrome and Safari.

**To Reproduce**
1. Go to your app and create a new Todo as an unauthorized user
2. Go to a page that calls the ListTodos query (or a similar ListResource query) and you will see the resource you created and no other items. This part behaves as expected.
3. Now open a new browser in Incognito mode and go to the same page calling the ListTodos query
4. You will now see the resource you created when in the regular browser and all resources that are in your DynamoDB table, effectively granting you admin access to view all resources in your Incognito mode browser.

**Expected behavior**
The user accessing the resources from an Incognito browser should not see any of the items in the DynamoDB table except for the ones created by that identity.

**Desktop (please complete the following information):**
 - Browser: Chrome and Safari
 - Version
```
    "aws-amplify": "^1.1.19",
    "aws-amplify-angular": "^2.1.6",
    "aws-appsync": "~1.7.1",
```

**Comment by jordanranz** [comment]
Hi @selipso,

Could you provide a few more details about how you are using Amplify?

- Did you use the Amplify CLI to setup Appsync?
- Did you configure AWS_IAM in the Appsync console?
- Are you using the [appsync-sdk](https://github.com/awslabs/aws-mobile-appsync-sdk-js) or the [Amplify API category](https://aws-amplify.github.io/docs/js/api) to interact with you backend/Appsync api?
- Do you have a sample application that you are following to help us reproduce the issue?

**Comment by selipso** [comment]
Hi @jordanranz, I'm using the Amplify API category with customized IAM auth permissions as per the auth-unauth example here: https://github.com/dabit3/appsync-auth-and-unauth

The difference is: my IAM permissions are the same between auth and unauth roles. So an authenticated user can call any query or mutation (just not subscription). The above behavior might be expected and in regular browsers I may just be seeing the optimistic response to the mutation.

For clarification, when using appsync locally with AWS_IAM, does the Appsync library label each new item (even by unauthenticated users) with the correct user / identity before uploading to DynamoDB? Otherwise this would cause major inconsistencies and basically give every user the ability to view all resources. Any app wanting to provide meaningful levels of access to unauthenticated users wouldn't be able to do so with Appsync + Amplify Auth.

**Comment by jordanranz** [comment]
I believe the above behavior is expect when your auth and unauth roles have the same IAM permissions.

Pertaining to your question, I believe you are alluding to fine-grained access control. This use case is documented here:
https://docs.aws.amazon.com/appsync/latest/devguide/security.html#fine-grained-access-control

Hope this helps answer your question.

**Comment by selipso** [comment]
I'm sorry, but that page made zero sense to me. This is a setting I would have to edit in DynamoDB? Creating an app with Cognito already sets pretty sane defaults. With IAM it seems to require more custom setup with DynamoDB.

It looks like the `filter` Resolver Mapping Template would be the best choice for my use case where I can add a field called 'owner' to each item, store the IdentityID associated with the user who created that item, and then filter the `ListTodos` query to only include items that match the owner. 

I still have no clue where these are located or how to edit them though.

**Comment by selipso** [comment]
I found a more detailed page about attaching policies related to fine-grained access control: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/specifying-conditions.html?icmpid=docs_ddb_console

Given that this is an option, I think a better title for this issue would that AWS Amplify with Appsync and IAM doesn't attach an Identity Token to queries, subscriptions, and mutations. What do you think?

**Comment by selipso** [comment]
Did some more testing, and found that part of the issue is also the way Appsync does the caching. For some reason, the cache is not always overwritten no matter what I do. I tried to enable the `refetchQueries` option, also tried to include an `optimisticResponse`, and even change the `fetchPolicy` of all of my `client.watchQuery` methods to `'network-only'`. Still, the only way to be sure that the data being shown in the app is not old data from the cache is to use an incognito window.

**Comment by manueliglesias** [comment]
@selipso can you try clearing your cache  on login/logout?

This [comment](https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/49#issuecomment-366824731) has an example

**Comment by selipso** [comment]
I think this has to do with the way that Auth is setup, but will try the above example in the next week or so.

**Comment by elorzafe** [comment]
@selipso any updates with this?

**Comment by selipso** [comment]
With the new CLI updates, IAM seems to work much better. Closing this for now and will open another one in case I see another issue. Great progress with the updates so far!
