### ISSUE TITLE
React withAuthenticator guest user

### ISSUE THREAD

**Issue by simoneb** [aws-amplify/amplify-js#2842]
**Which Category is your question related to?**

Authentication with React's `withAuthenticator` HOC

**What AWS Services are you utilizing?**

Cognito

**Provide additional details e.g. code snippets**

I'm following the React quick start guide and implementing authentication. Using the `withAuthenticator` HOC I see that it is always shown when the user is not authenticated. I have already configured `auth` so that it allows access to unauthenticated users, but when accessing the application as a guest user I'm always shown the login UI widget. Is there a way to avoid showing it and show it only on demand, i.e. when clicking the login button in the toolbar?

**Comment by jordanranz** [comment]
Hey @simoneb,

withAuthenticator HOC should wrap the component that you want to render when a user logs in (and is authenticated). Your base application component (where guests/unauthenticated users land), should not be wrapped with the HOC.

**Comment by powerful23** [comment]
Closing the issue. Please let us know if you still have this issue.
