### ISSUE TITLE
undefined is not a function when calling updateUserAttributes

### ISSUE THREAD

**Issue by denchp** [aws-amplify/amplify-js#2848]
**Describe the bug**
When trying to update the current user's attributes I'm getting the following error:
`
undefined is not a functio n(evaluating 'Object.keys(styles)[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()')
`

This error specifically arises with the 2nd line of code listed below.

```
    const user = await getCurrentAuthenticatedUser();
    Auth.updateUserAttributes(user, { 'custom:token': token } ).then(result =>{ console.log(result)});
```

**Expected behavior**
Update the current user's attributes and return successfully.

**Screenshots**
https://ibb.co/7zNFxvc

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 1.1.22

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 9

**Comment by jordanranz** [comment]
Hey @denchp,

It may be that you are missing `Auth.` in front of `getCurrentAuthenticatedUser()`

If that is not the problem here is an example for reference:
https://aws-amplify.github.io/docs/js/authentication#working-with-user-attributes

Also, try setting this in your js:
`window.LOG_LEVEL = 'DEBUG';
`
The will give you more verbose logging in console during development.

**Comment by denchp** [comment]
The getCurrentAuthenticatedUser is actually imported from another file, which wraps the Auth call - but it does return the actual user.

**Comment by denchp** [comment]
For what it's worth, I had the log level set to debug, and it didn't give any significant output:
```
2019-03-13 08:31:18.937 25019-25057 E/ReactNativeJS: undefined is not a function (evaluating 'Object.keys(styles)[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()')
2019-03-13 08:31:18.942 25019-25057 E/ReactNativeJS: undefined is not a function (evaluating '_$$_REQUIRE(_dependencyMap[2], "pretty-format")(error)')
```

**Comment by denchp** [comment]
So I've solved this issue.

Adding a .catch to the function call resolves this issue:
```
const user = await getCurrentAuthenticatedUser();
    Auth.updateUserAttributes(user, { 'custom:token': token } )
        .then(result =>{ console.log(result)})
        .catch(err => console.log(err));
```
