### ISSUE TITLE
Update from aws-amplify 0.4.4

### ISSUE THREAD

**Issue by bonbertr** [aws-amplify/amplify-js#2852]
** Which Category is your question related to? **
@aws-amplify/pushnotification

** What AWS Services are you utilizing? **
Mobile Hub, AWS PinPoint

** Provide additional details e.g. code snippets **

Hello,
I'm using AWS Pinpoint for ios/android Push Notifications on my react native app. I have a functional setup I did about a year ago using aws-amplify 0.4.4 and aws-amplify-react-native 0.2.15. Now I want to update to the latest aws-amplify version, but so far I cannot get it to work.

Extracts from my previous (functional) setup:

aws-exports downloaded from MobileHub (did not change before and after update):
```
const awsmobile = {
  aws_app_analytics: "enable",
  aws_cognito_identity_pool_id:
    "XX-XX-XX:XXXXXXXXXXXX",
  aws_cognito_region: "XX-XX-XX",
  aws_mobile_analytics_app_id: "XXXXXXXXXXXX",
  aws_mobile_analytics_app_region: "XX-XX-XX",
  aws_project_id: "XXXXXXXXXXXX",
  aws_project_name: "XXXXXXXXXXXX",
  aws_project_region: "XX-XX-XX",
  aws_push_apns: "enable",
  aws_push_pinpoint: "enable",
  aws_resource_name_prefix: "XXXXXXXXXXXX"
};
```

```json
"dependencies": {
    "amazon-cognito-identity-js": "^3.0.3",
    "aws-amplify": "^0.4.4",
    "aws-amplify-react-native": "^0.2.15",
    "react-native": "0.55.0"
}
```

```
import { PushNotificationIOS, Platform } from "react-native";
import Amplify from "aws-amplify/lib/index";
import { PushNotification } from "aws-amplify-react-native";
import awsExports from "../aws-exports";

let isInitialized = false;

export const initPushNotif = dispatch => {
    if (isInitialized) {
        return;
    }
    isInitialized = true;

    Amplify.configure(awsExports);
    PushNotification.configure(awsExports);

    PushNotification.onNotification(notification => {
        if (Platform.OS === "ios") {
          PushNotificationIOS.getApplicationIconBadgeNumber(number =>
            PushNotificationIOS.setApplicationIconBadgeNumber(number + 1)
          );

          // required on iOS only (see fetchCompletionHandler docs: https://facebook.github.io/react-native/docs/pushnotificationios.html)
          notification.finish(PushNotificationIOS.FetchResult.NoData);
        }
    });

    PushNotification.onRegister(token => {
        dispatch({
          type: ActionEvents.user.SET_PUSH_NOTIF_TOKEN,
          pushNotifToken: token
        });
        dispatch(UserActions.updateUserDeviceData());
    });
}
```
Here the onRegister is called, as expected.

New dependencies after update:

```json
"dependencies": {
    "@aws-amplify/pushnotification": "^1.0.23",
    "aws-amplify": "^1.1.22",
    "react-native": "0.55.0"
}
```

New code after aws-amplify update (onRegister never called here):

```
import { PushNotificationIOS, Platform } from "react-native";
import Amplify from "aws-amplify";
import PushNotification from "@aws-amplify/pushnotification";
import awsExports from "../aws-exports";

let isInitialized = false;

export const initPushNotif = dispatch => {
    if (isInitialized) {
        return;
    }
    isInitialized = true;

    Amplify.configure(awsExports);
    PushNotification.configure(awsExports);

    PushNotification.onNotification(notification => {
        if (Platform.OS === "ios") {
          PushNotificationIOS.getApplicationIconBadgeNumber(number =>
            PushNotificationIOS.setApplicationIconBadgeNumber(number + 1)
          );

          // required on iOS only (see fetchCompletionHandler docs: https://facebook.github.io/react-native/docs/pushnotificationios.html)
          notification.finish(PushNotificationIOS.FetchResult.NoData);
        }
    });

    PushNotification.onRegister(token => {
        dispatch({
          type: ActionEvents.user.SET_PUSH_NOTIF_TOKEN,
          pushNotifToken: token
        });
        dispatch(UserActions.updateUserDeviceData());
    });
}
```

As I said, my problem now is that the onRegister is not called anymore. I tried various things, like importing Auth and Analytics ( @aws-amplify/auth @aws-amplify/analytics) and calling their configure functions, without much result. So far, I only tested on Android.

Thanks

**Comment by jordanranz** [comment]
Related to: #2541

**Comment by powerful23** [comment]
@bonbertr can you take a look at this? https://github.com/aws-amplify/amplify-js/issues/2541#issuecomment-456505939

**Comment by bonbertr** [comment]
Thanks for your answers, already checked #2541 , I removed the debug build from my phone, built and started again, and onRegister was not called either. I also checked the AsyncStorage following the provided link in the #2541  topic: https://github.com/aws-amplify/amplify-js/blob/master/packages/pushnotification/src/PushNotification.ts#L236 but no token is stored in AsyncStorage.

**Comment by powerful23** [comment]
@bonbertr Hmm, I agree that there is no way to retrieve the token again if the asyncStorage is cleared. I will mark this as bug and try to find a way to fix it.

**Comment by bonbertr** [comment]
Hello,

I updated aws-amplify after the provided fix, so far so good, many thanks !

**Comment by jordanranz** [comment]
@bonbertr is this issue safe to close?
