### ISSUE TITLE
How to remove a service? I can't find it in the docs

### ISSUE THREAD

**Issue by janhesters** [aws-amplify/amplify-js#2859]
** Which Category is your question related to? **
General Amplify CLI.

** What AWS Services are you utilizing? **
AWS Amplify API

** Provide additional details e.g. code snippets **
I ran `amplify add api`. How could I delete a service? `amplify remove api`? I can't find anything regarding this in the docs.

**Comment by janhesters** [comment]
Found it. Just use `amplify remove <service>`.

**Comment by janhesters** [comment]
Found it. Just use `amplify remove <service>`.

**Comment by jefelewis** [comment]
For Amplify APIs, you can run the following to delete an API:
```javascript
amplify remove api RESOURCE_NAME_HERE
```

**Comment by AshkanHovold** [comment]
Is it possible to remove connection between api/auth/hosting and the amplify app without actually deleting the resources? I have been playing around and created a new app and connected it to an existing cognito user pool. now I want to delete the app but keep the cognito user pool. How can this be accomplished?
