### ISSUE TITLE
Loading screen being shown after downtime

### ISSUE THREAD

**Issue by briantbates** [aws-amplify/amplify-js#2862]
** Which Category is your question related to? **
Amplify Auth

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
I have my Application wrapped in a custom Authenticator container and after maybe 5 minutes of not interacting with Cognito/AppSync, the web page shows 'Loading...' within a card-like element. I have searched my code for a loading indicator like that and have found nothing. I have even search through the aws-amplify-react package and couldn't find anything of that nature.

Any idea where this comes from? I would like to hide/modify it if possible.

Thanks!

**Comment by jordanranz** [comment]
Hi @briantbates,

By "custom Authenticator" do you mean an extended version of the Authenticator from aws-amplify-react?

**Comment by briantbates** [comment]
@jordanranz,

Here is my setup, sorry forgot to include in the post.
`     <Authenticator
        signUpConfig={signUpConfig}
        authData={'email'}
        amplifyConfig={myAWSExports}
        hide={[Greetings]}>
         <App />
      </Authenticator>`

**Comment by jordanranz** [comment]
Ok, great. Thanks for the code.

This is the code that is being rendered:
https://github.com/aws-amplify/amplify-js/blob/88ccc4f680d616751d679299dc9740af115332e8/packages/aws-amplify-react/src/Auth/Loading.jsx

I'll investigate why this is rendering after ~5 minutes. It sounds like some kind of session timeout and an auth state change to 'loading' is triggered.

**Comment by briantbates** [comment]
Wow how did I overlook an entire loading component. It does go away after anywhere between 300-800ms but was just wondering if I could at least customize it. I didn't see it anywhere in the docs that it was a hide-able component but I will give it a try and report back.

**Comment by jordanranz** [comment]
It looks like the Loading component is relatively new and hasn't been added to the docs [here](https://aws-amplify.github.io/docs/js/authentication#using-the-authenticator-component-directly).

I'll add it to this code snippet in the docs.

**Comment by briantbates** [comment]
I have not seen the indicator so it looks like hiding it in the Authenticator props works.

Thanks!
