### ISSUE TITLE
Text caret moves to the end when editing email field on hosted UI login form in Safari

### ISSUE THREAD

**Issue by dan-lovelace** [aws-amplify/amplify-js#2863]
**Describe the bug**
In Safari, when the user tries to edit their email during login on the hosted UI, the text cursor jumps to the end of the input. The user must make changes one character at a time.

**To Reproduce**
1. Go to the hosted UI with an email and password field in the listed Safari version
2. Enter any email address into the email field
3. Press the left arrow key a few times to reposition the text caret (or click somewhere in the input)
4. Edit the input value by pressing any character key
5. Notice the text cursor moves to the end of the textbox

**Expected behavior**
User can easily edit their email during login on all supported browsers.

**Desktop (please complete the following information):**
 - OS: OSX 10.14.3
 - Safari
 - Version 12.0.3 (14606.4.5)

**Comment by jordanranz** [comment]
Hey @dan-lovelace,

Are you using the withOAuth HOC in aws-amplify-react: https://aws-amplify.github.io/docs/js/authentication#launching-the-hosted-ui-in-react

or are you using the UI provided by Cognito in their console?

**Comment by dan-lovelace** [comment]
@jordanranz I'm using the Cognito hosted UI, not the HOC

**Comment by haverchuck** [comment]
@dan-lovelace  - This seems like an issue with Hosted UI as opposed to Amplify, so I have made them aware of it.  I am going to close this issue for now, but please feel free to open another if I've misunderstood.
