### ISSUE TITLE
React native - change user avatar

### ISSUE THREAD

**Issue by truongluong1314520** [aws-amplify/amplify-js#2867]
Hi aws-amplify team,

I want to ask about how to change the user's avatar using aws-amplify in React native app?

I look for this in your web [Authentication](https://aws-amplify.github.io/docs/js/authentication), but the is no description about how to change it.

Please guide me. Thank you in advance!

**Comment by jordanranz** [comment]
@truongluong1314520, I am not sure which avatar you are talking about. Could you elaborate or provide a screenshot of this avatar you'd like to change?

**Comment by truongluong1314520** [comment]
Hi @jordanranz , of course

![Screenshot_1552708451](https://user-images.githubusercontent.com/32918401/54470446-6ab1f180-47da-11e9-8f18-e80b825f9b63.png)

**Comment by truongluong1314520** [comment]
Hi @jordanranz , does aws-amplify support this function? if you need any information, please let me know.

**Comment by manueliglesias** [comment]
Hi @truongluong1314520 

> I want to ask about how to change the user's avatar using aws-amplify in React native app?
> does aws-amplify support this function?

This is something you can implement making use of Amplify's [`Storage`](https://aws-amplify.github.io/docs/js/storage#put) category to store the files in S3, Cognito User attributes to store a link to the file and the [`<S3Image>`](https://aws-amplify.github.io/docs/js/storage#s3image) component to display it.

**Comment by truongluong1314520** [comment]
Hi @manueliglesias , sorry for the late reply, I based on what you said and success to found the way to do it. I will close this ticket. Later on, if there are other problems related to this one. I will create a new ticket.

Thank you!
