### ISSUE TITLE
How to create or delete multiple values at a time in a batch?

### ISSUE THREAD

**Issue by janhesters** [aws-amplify/amplify-js#2873]
** Which Category is your question related to? **
API

** What AWS Services are you utilizing? **
GraphQL, Dynamo DB, Codegen

** Provide additional details e.g. code snippets **
I have the following schema:

```graphql
type Contact @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  firstName: String!
  lastName: String!
  city: String
  company: String
  position: String
  group: Group!
  tendency: Tendency!
}

enum Group {
  innerFive
  friend
  confidant
  acquaintance
  distantAcquaintance
}

enum Tendency {
  rise
  maintain
  fall
}
```

This generated the following Graphql mutations for creating and deleting:

```js
export const createContact = `mutation CreateContact($input: CreateContactInput!) {
  createContact(input: $input) {
    id
    firstName
    lastName
    city
    company
    position
    group
    tendency
  }
}
`;

export const deleteContact = `mutation DeleteContact($input: DeleteContactInput!) {
  deleteContact(input: $input) {
    id
    firstName
    lastName
    city
    company
    position
    group
    tendency
  }
}
`;
```

How can I delete or create in bulk? Let's say I have an array of ID's. What is the most efficient way to delete all users with those ID's?

**Comment by manueliglesias** [comment]
Hi @janhesters 

You can [Add a custom resolver that targets a DynamoDB table from `@model`
](https://aws-amplify.github.io/docs/cli/graphql#add-a-custom-resolver-that-targets-a-dynamodb-table-from-model)

Those docs mention writing more specific queries, but there is no reason it couldn't be adapted to do `PUT` operations / use [DynamoDB Batch Resolvers](https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-dynamodb-batch.html).

You can construct your GraphQL mutations to accept a collection of ids and then implement the associated resolvers to perform batch operations.

I hope this helps. Also, if you want, you can creeate a feature request in the [aws-amplify/amplify-cli](https://github.com/aws-amplify/amplify-cli/) repo

**Comment by janhesters** [comment]
@manueliglesias Thank you for the answer. I will do that 👍

**Comment by LucasAndrad** [comment]
@jamesiri did you succeed with this approach? If yes, could you share your solution?

**Comment by PeteDuncanson** [comment]
@LucasAndrad and anyone else who stumbles on this, @janhesters wrote up their findings in this blog https://medium.com/@jan.hesters/creating-graphql-batch-operations-for-aws-amplify-with-appsync-and-cognito-ecee6938e8ee
