### ISSUE TITLE
withAuthenticator is half french half english, 

### ISSUE THREAD

**Issue by axe-z** [aws-amplify/amplify-js#2875]
would be alot easier if we could only add attributes to OUR own forms to handle auth. 

here we speak two languages, 
and it get weird quick, by default I get both languages... on a fresh install.
started theming , but how do we change innerhtml stuff , placeholders? 

<img width="654" alt="Capture d’écran, le 2019-03-16 à 18 45 31" src="https://user-images.githubusercontent.com/27289270/54482566-f0a25c80-481b-11e9-9579-9a7dda5b60ee.png">

**Comment by manueliglesias** [comment]
Hi @axe-z 

I've labeled this as a bug so it goes into our backlog

Thanks!

**Comment by crcommons** [comment]
@axe-z You can add your own translations for any nearly any part of the amplify UI using the i18n module from Amplify https://aws-amplify.github.io/docs/js/i18n#i18n. In order to know what keys to use in you vocabulary, you can look through the source code for the UI of Amplify (for React, for example: https://github.com/aws-amplify/amplify-js/tree/master/packages/aws-amplify-react/src/Auth). The only thing that you can't translate are the error messages. I need to open up an issue to report that bug.

**Comment by manueliglesias** [comment]
Thank you @crcommons 

@axe-z Hopefully @crcommons comment helps you; I will be keeping this issue open as it seems the included translations are lacking some elements.

https://github.com/aws-amplify/amplify-js/blob/01e660df246f0faf0bcb5b5ebf604597db3ef4aa/packages/aws-amplify-react/src/AmplifyI18n.js#L15

**Comment by axe-z** [comment]
Yes tks for the guidance

**Comment by ngrosso** [comment]
Hii i don't know if you already solved but i'm leaving it for any further doubt, there are some missleading uppercases and lowercasses that make i18n miss the reference here is my handmade example for spanish:

`    'es': {
      'Sign in to your account': "Inicie sesion en su cuenta",
      'Sign In': "Iniciar sesion",
      "Sign in": "Iniciar sesion",
      'Sign Up': "Registrarse",
      "Username *": "Usuario *",
      "Username": "Usuario",
      "Password *": "Contraseña *",
      "Password": "Contraseña",
      "Enter your password": "Ingrese su contraseña",
      "No account?": "¿No tienes una cuenta?",
      "Create account": "Crear una cuenta",
      "Create Account": "Crear cuenta",
      "Have an account?": "¿Tenes cuenta?",
      "Have a code?": "¿Tiene un codigo?",
      "Code *": "Codigo",
      "Confirm": "Confirma",
      "Reset Password": "Reiniciar Contraseña",
      "Reset password": "Reiniciar Contraseña",
      "Reset your password": "Reinicie su contraseña",
      "Back to Sign in": "Volver al inicio de sesion",
      "You will receive a verification code to reset your password": "Usted recibira un codigo de verificacion para reiniciar su contraseña",
      "Submit": "Enviar",
      "Verify": "Verificar",
      "Lost your code?'": "Perdiste tu codigo?",
      "Resend": "Reenviar",
      "Forgot Password?": "Olvidaste tu contraseña?",
      "You will receive a verification code": "Usted recibira un codigo de verificacion",
    }`

**Comment by ngrosso** [comment]
I guess you find out the answer, but by grabing the text in english from the component and keeping the cases (upper and lower ones) you can make your own custom dictionary to add missing ones.
This is my example extending the one that @manueliglesias mentioned but in spanish, notice there are some duplicated ones but with different case (like "Create account" and "Create Account"), also in later updates you can change the language of error messages

`    'es': {
      'Sign in to your account': "Inicie sesion en su cuenta",
      'Sign In': "Iniciar sesion",
      "Sign in": "Iniciar sesion",
      'Sign Up': "Registrarse",
      "Username *": "Usuario *",
      "Username": "Usuario",
      "Password *": "Contraseña *",
      "Password": "Contraseña",
      "Enter your password": "Ingrese su contraseña",
      "No account?": "¿No tienes una cuenta?",
      "Create account": "Crear una cuenta",
      "Create Account": "Crear cuenta",
      "Have an account?": "¿Tenes cuenta?",
      "Have a code?": "¿Tiene un codigo?",
      "Code *": "Codigo",
      "Confirm": "Confirma",
      "Reset Password": "Reiniciar Contraseña",
      "Reset password": "Reiniciar Contraseña",
      "Reset your password": "Reinicie su contraseña",
      "Back to Sign in": "Volver al inicio de sesion",
      "You will receive a verification code to reset your password": "Usted recibira un codigo de verificacion para reiniciar su contraseña",
      "Submit": "Enviar",
      "Verify": "Verificar",
      'Verify Contact': "Verificar contacto",
      'Skip': "Omitir",
      "Lost your code?'": "Perdiste tu codigo?",
      "Resend": "Reenviar",
      "Forgot Password?": "Olvidaste tu contraseña?",
      "You will receive a verification code": "Usted recibira un codigo de verificacion",
      'Code': "Código",
      'Account recovery requires verified contact information': "La recuperación de la cuenta requiere información de contacto verificada",
      'User does not exist': "El usuario no existe",
      'User already exists': "El usuario ya existe",
      'Incorrect username or password': "Nombre de usuario o contraseña incorrecta",
      'Invalid password format': "Formato de contraseña inválido",
      'Invalid phone number format': `Formato de número de teléfono inválido. Utilice el formato de número de teléfono +12345678900`,
      "Username cannot be empty": "El nombre de usuario no puede estar vacio",
      "Custom auth lambda trigger is not configured for the user pool.": "No esta permitido el inicio de sesion sin contraseña",
      "Incorrect username or password.": "Usuario o contraseña incorrecto",
      "Password attempts exceeded": "Excedido el tiempo de reintentos, espere unos segundos"
    }`

**Comment by camilodelvasto** [comment]
I decided to build upon @ngrosso 's answer (native speaker here), I found it a little tricky (had to add a space after certain strings), so here's for the record:

```
'es': { 'Sign in to your account': "Inicia sesión en tu cuenta", 'Sign In': "Iniciar sesión", "Sign in": "Iniciar sesión", 'Sign Up': "Regístrate", "Username *": "Usuario *", "Username": "Usuario", "Password *": "Contraseña *", "Password": "Contraseña", "Enter your password": "Ingresa tu contraseña", "Enter your Username": "Ingresa tu usuario", "No account?": "¿No tienes una cuenta?", "Create account": "Crea una cuenta", "Create Account": "Crear cuenta", "Have an account?": "¿Tenes cuenta?", "Have a code?": "¿Tienes un código?", "Code *": "Codigo", "Confirm": "Confirmar", "Reset Password": "Reiniciar contraseña", "Reset password": "Reiniciar Contraseña", "Reset your password": "Reinicia tu contraseña", "Back to Sign in": "Volver al inicio de sesion", "You will receive a verification code to reset your password": "Recibirás un codigo de verificacion para restablecer tu contraseña", "Submit": "Enviar", "Verify": "Verificar", 'Verify Contact': "Verificar contacto", 'Skip': "Omitir", "Lost your code?'": "¿Perdiste tu código?", "Resend": "Reenviar", "Forgot Password?": "¿Olvidaste tu contraseña?", "You will receive a verification code": "Recibirás un codigo de verificación", 'Code': "Código", 'Account recovery requires verified contact information': "La recuperación de la cuenta requiere información de contacto verificada", 'User does not exist': "El usuario no existe", 'User already exists': "El usuario ya existe", 'Incorrect username or password': "Nombre de usuario o contraseña incorrecta", 'Invalid password format': "Formato de contraseña inválido", 'Invalid phone number format': "Formato de número de teléfono inválido. Utiliza el formato de número de teléfono +12345678900", "Username cannot be empty": "El nombre de usuario no puede estar vacio", "Custom auth lambda trigger is not configured for the user pool.": "No esta permitido el inicio de sesión sin contraseña", "Incorrect username or password.": "Usuario o contraseña incorrecto", "Password attempts exceeded": "Excedido el tiempo de reintentos, espera unos segundos", "Forget your password? ": "¿Olvidaste tu contraseña?", "No account? ": "¿No tienes una cuenta?",  "Have an account? ": "¿Ya tienes un cuenta?", "Send Code": "Enviar código", "Back to Sign In": "Regresa al inicio de sesión" }
```
