### ISSUE TITLE
aws-amplify-react: UI Container adds unwanted markup for custom Authenticator UI

### ISSUE THREAD

**Issue by lvl99** [aws-amplify/amplify-js#2877]
When creating a custom Authenticator UI, the `Authenticator` component utilises a `Container` component imported from `Amplify-UI/Amplify-UI-Components-React` which applies a theme object as a prop.

I'd like to avoid the wrapper `Container` markup, since it wraps all my custom authentication components within a `<div class="Section__container___1Gue_" style="">` element.

The `Container` usage within the `Authenticator` component is hard-coded. It would be nice to be able to feed it a different `Container` component to use. In my case I'd give it a `React.Fragment`.

**Comment by manueliglesias** [comment]
Hi @lvl99 

I am labeling this issue as a feature-request so it becomes part of our backlog

Thanks for using Amplify

**Comment by lvl99** [comment]
Hi @manueliglesias, I've already submitted a PR. Let me know if it's OK.

**Comment by emeryaa** [comment]
Please add hosting to your project before publishing your project
Command: amplify hosting add

Trying to add hosting without chances

amplify hosting add
Hosting is already fully enabled.

Error: Hosting is already fully enabled.

**Comment by jordanranz** [comment]
Closing this as it seems the PR was merged. Please reopen if you have any related questions or concerns.
