### ISSUE TITLE
The docs for 'Offline Mutations' refer to values that are not being created by CodeGen

### ISSUE THREAD

**Issue by janhesters** [aws-amplify/amplify-js#2882]
I'm using AWS Amplify for React. This bug is in the API category when all defaults are being chosen.

**Describe the ~~bug~~ mistake**
In the docs for [offline mutations](https://aws-amplify.github.io/docs/js/api#offline-mutations) under `With Helpers` `createTodo` and `CreateTodoInput` are being imported (because they are later used in `inputType: gql(CreateTodoInput),`):

```js
import { createTodo, CreateTodoInput } from './graphql/mutations';
```

But the ladder are only created in the cloud. Codegen only references the inputs but neither generates nor exports them.

```js
// In src/graphql/mutations.js
export const createTodo = `mutation CreateTodo($input: CreateTodoInput!) {
  createTodo(input: $input) {
    id
    name
    description
  }
}
`;

// No export const CreateTodoInput
```

If you copy the CreateTodoInput from the cloud and safe it to the file, it will get overwritten.

Leaving out the `inputType` key results in:

```
Uncaught TypeError: Cannot read property 'definitions' of undefined
```

**Possible fixes:**
Either alter the docs to propose a different solution, or have Codegen create the inputs, too.

**Comment by janhesters** [comment]
Just found [this issue](https://github.com/aws-amplify/amplify-cli/issues/1009) that references the same problem.

**Comment by manueliglesias** [comment]
Hi @janhesters 

Yeah, for now you have to duplicate your input declaration in your front-end code to be able to pass it to the offline helpers.

What do you think about closing this issue in favor of the existing [feature request](https://github.com/aws-amplify/amplify-cli/issues/1009)?

**Comment by janhesters** [comment]
@manueliglesias Gladly 🤗 Do you have any insights about the status of the feature request?

**Comment by manueliglesias** [comment]
@janhesters unfortunately I don't have any at the moment, you can +1 the feature request (add a 👍 in the submitter's comment) so the cli team can better gauge interest in the feature
