### ISSUE TITLE
Amplify Authenticator not returning "attributes" on inital login

### ISSUE THREAD

**Issue by sgruessinger** [aws-amplify/amplify-js#2892]
**Describe the bug**
When logging in initially via Authenticator, the auth-info coming from authStateChange$ lacks the "attributes" node, containing user info from the Cognito-Pool.
When reloading the app (the authenticator automaticall logs the user back in) the auth-info contains the "attributes" node (along with all the custom attributes set for that cognito pool)

**To Reproduce**
1. register to the authStateChange$-observable
2. login via the authenticator
3. print the incoming auth-info

**Expected behavior**
The "attributes"-node should be present right from the very first login.

**Screenshots**
First Login (see "signedOut"-state)
![initiallogin](https://user-images.githubusercontent.com/45566539/54595868-cd51fa00-4a33-11e9-88f8-57a003567267.jpg)

Browser refresh (secondary [automatic] login)
![secondarylogin](https://user-images.githubusercontent.com/45566539/54595914-e9ee3200-4a33-11e9-9a46-4339a63af47f.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 72.0.3626.121

**Sample code**
```
// AmplifyService loaded into "my" angular-session-service via DI
import { Injectable } from '@angular/core';
import { AmplifyService } from 'aws-amplify-angular';

@Injectable({
  providedIn: 'root'
})
export class SessionService {
  constructor (private amplifyService: AmplifyService) {
    this.amplifyService.authStateChange$.subscribe((authInfo) => {
      console.log(authInfo);
    });
  }
}
```

**Comment by twoolf** [comment]
If it helps with debugging this -- we had a 'required' for MFA and just switched over to 'optional' with Advanced Security on our UserPools.  With the previous settings, we had seen the 'attributes' data on initial login.  But, with the change, we are no longer seeing it on the initial login.

Does anyone have suggestions on how to work around this bug?  We had engineered data to flow from that first login based on values from the attributes.  Right now all the lambda functions are sending bad data.

I've also noted that once we move to 'optional' from 'required' that we can't return to the previous Cognito settings.

**Comment by twoolf** [comment]
Took all day, but I am now working with: aws-amplify@1.1.23-unstable.9  -- but the same error is present on our React Native App -- we can't see the 'attributes' data --

Can we reopen this for React Native?  I can file a new issue if that is better.

Any other suggestions -- are others seeing this also?

**Comment by powerful23** [comment]
@twoolf can you check the following items?
- Can you check the version of `@aws-amplify/auth` is `1.2.19-unstable.4`?
- Can you provide more info by turning on the debug mode? You can open it by putting `window.LOG_LEVEL='DEBUG'` in your code. Especially the info when signing in
- Further more,  if you go to `node_modules/@aws-amplify/auth/lib/Auth.js` line 436, this is where attributes are retrieved. You can insert some logging statement to see if it is triggered as expected

**Comment by twoolf** [comment]
@powerful23 I suspect that I'm missing something -- I continue to see the same behavior with 1.2.19-unstable.4 and even tried 1.1.23-unstable.10 

- in looking over line 436 and related, I am not seeing where the calls for the custom attributes are being collected.  This is related to the blog post by Adrian and Nader (https://aws.amazon.com/blogs/mobile/aws-amplify-adds-support-for-custom-attributes-in-amazon-cognito-user-pools/)
- here is the data on signUp (Chrome debugger for react app) where the custom-attributes are collected in our case
![Daily24_from_signUp](https://user-images.githubusercontent.com/5383308/54965453-f8ae7a80-4f46-11e9-8043-a07609b0c507.jpeg)

- currentUserInfo (line 1511), looks more similar to what I would have expected, but I don't see the triggers to call this on signIn (and currentUserInfo on line 1497 is mentioned by Adrian and Nader as the entry point)
- currentUser (line 436) doesn't look like it will have the custom attributes, should there be an additional case statement added?
- I can do more console.log and/or debug statements -- most likely at other locations?
- should authCallbacks include currentUserInfo?  I'm not seeing how this was working in the flow with MFA required and now not working with optional MFA
- line 812 with MFA for confirmSignIn would most likely have been called w/MFA required.

**Comment by powerful23** [comment]
@twoolf to be more specific, if you go to line 1036, the `getUserData` in that `currentUserPoolUser` method is called which will return the user attributes. Can you do some debug statements to see if this method is called as expected. 

Please turn on the debug mode which will also print a lot of information.

**Comment by twoolf** [comment]
I'm still in progress on this, but also looking for suggestions:
 1) I think that the DEBUG call is -- Amplify.Logger.LOG_LEVEL = 'DEBUG'; -- right?  But, with React Native, and the adb logcat I'm not seeing additional output.  Turning this on globally in the App.js should be sufficient, from the docs.  Is there another place to add the Global for debugging?
2) with console.log statements all through the lines around 1036, this is not being called, so I have no indications of those statements being reached -- I will update if I can get the global logging to work with more details.

Do you have other thoughts on what to check?

**Comment by twoolf** [comment]
Just updating -- really the power of open-source! --
 1: I did get the console.log to work -- so this was a problem with my codes not calling into the right location.  I now am getting the custom-attributes --
 2: I still don't have the global DEBUG reporting anything back, so I would be curious to understand what should be changed for that

  summary: this can remain closed; with the newest Amplify the custom:attributes are readable

**Comment by jeremydrichardson** [comment]
Can you elaborate a little more on how you solved this?

We are using Cognito with a SAML federation to Google. We're listening using Amplify Hub to the signIn event. What comes back in the payload data is a CognitoUser object, but it has no attributes.

We're trying to sync user attributes with Cognito based on the user signing in for the first time, but without having the attributes we can't make this work.

Any help would be appreciated.

**Comment by gbaron** [comment]
> Can you elaborate a little more on how you solved this?
> 
> We are using Cognito with a SAML federation to Google. We're listening using Amplify Hub to the signIn event. What comes back in the payload data is a CognitoUser object, but it has no attributes.
> 
> We're trying to sync user attributes with Cognito based on the user signing in for the first time, but without having the attributes we can't make this work.
> 
> Any help would be appreciated.

Were you able to solve this one?
