### ISSUE TITLE
Incorrect Error Message when changing password

### ISSUE THREAD

**Issue by FatimahSanni** [aws-amplify/amplify-js#2895]
Hi! 

I noticed this issue when a new user attempts to change password and the (weak) password violates the set policy in Cognito, a wrong error message is generated `Email is not associated with any account` instead of something along the lines of `Weak password or password should be at least 8 characters long` etc.

The method being called here is the `Auth.changePassword()`.

**Comment by manueliglesias** [comment]
Hi @FatimahSanni 

Can you enable logging in amplify and paste the error as you see it there?

**Comment by manueliglesias** [comment]
Here are the docs on how to do it: [Setting Logging Levels
](https://aws-amplify.github.io/docs/js/logger#setting-logging-levels)

**Comment by FatimahSanni** [comment]
Apologies @manueliglesias, it's from our code. Apparently, a team mate was unintentionally overriding the error messages from Cognito. Sorry for the inconvenience.

Thanks for the help.

**Comment by manueliglesias** [comment]
@FatimahSanni no worries, glad you found the issue!
