### ISSUE TITLE
How to ignore node_modules

### ISSUE THREAD

**Issue by RoniqueRicketts** [aws-amplify/amplify-js#2902]
I have been testing amplify to see if I can use this for an application that needs to be HIPPA compliant and I am concerned about what I see when I deploy a test web app to amplify. I see the node_modules folder and I am unable to ignore this fine. Could you please suggest so help in doing so. I am using create-React-app and I’ve tried deploying the website from the CLI and Console. I followed the Amplify’s tutorial online. Also, I thought only the build folder would be deployed to the cloud but that’s not what I see when I try to deploy a web application. It seems as if the src folder is merging in the build folder so I am not just seeing the compiled files from the build but also files found in the src folder. Click the link below to see an image of what I am talking about.
https://scontent.fktp1-1.fna.fbcdn.net/v/t1.0-9/fr/cp0/e15/q65/53918351_10216102309143840_826168664834179072_n.jpg?_nc_cat=108&efg=eyJpIjoidCJ9&_nc_eui2=AeGJtuW6tjhRaXozw8v4u5VwoEogNMSVehWiGqHa01AIVy7bT3OLsZY1QvgNRFO97btp385HE9v9QLrrUptCuUo4xpw04nmeAjniS4FABA9lLA&_nc_ht=scontent.fktp1-1.fna&oh=33dbc35d1a21c5c7dbd61bd5aaf86042&oe=5D4B3313

**Comment by jkeys-ecg-nmsu** [comment]
You want your application to work without bundling node dependencies? Or you want the client to not be able to read the code you're executing on it?

**Comment by RoniqueRicketts** [comment]
I don’t want the client to be able to read the code I am executing. They are seeing my App.js file, serviceWorker and node_modules. As mention before it’s as if amplify is merging the src directory with the build directory. Are you getting the same output?

**Comment by jkeys-ecg-nmsu** [comment]
No, I'm not. Amplify is just using the build process defined in `package.json` AFAIK. What do you get when you delete your local build folder and execute `npm run build`? Does node_modules appear in your local static folder when built manually?

**Comment by RoniqueRicketts** [comment]
I get a regular build folder without node_moduels in it 
![image](https://user-images.githubusercontent.com/17409035/54704564-fbedd480-4b08-11e9-885e-d338774a86ed.png)
. I am seeing all these folders and files in the source folder. https://github.com/RoniqueRicketts/amp/blob/master/src/Screen%20Shot%202019-03-20%20at%2012.02.30%20PM.png?raw=true

**Comment by jkeys-ecg-nmsu** [comment]
And you've checked the hosting bucket to see if they've been uploaded there?

**Comment by RoniqueRicketts** [comment]
Why would amplify send all those files including service worker to the bucket? Shouldn't it just send the build folder over to the bucket without node_modeules in it? Also, how can I prevent all these other files from being sent since they are in the hosting bucket? The node_modules bucket is not in the hosting bucket by the way.
