### ISSUE TITLE
Batch Storage.put

### ISSUE THREAD

**Issue by YikSanChan** [aws-amplify/amplify-js#2905]
** Which Category is your question related to? **
Storage

** What AWS Services are you utilizing? **
S3

** Provide additional details e.g. code snippets **
From https://aws-amplify.github.io/amplify-js/api/classes/storageclass.html#put, I am able to `Storage.put` to put 1 file to S3 at a time. I have a use case that users submit a few photos at a time, in which case I am looking for batch Storage.put alternative. Is this possible given what S3 currently provides?

**Comment by manueliglesias** [comment]
Hi @YikSanChan 

Currently this is not supported, I am labeling this issue as a feature-request.

**Comment by YikSanChan** [comment]
@manueliglesias Is it not supported by S3 or only not supported by aws amplify?

**Comment by manueliglesias** [comment]
The S3 service doesn't support it. Amplify could help a little or you could do something like:

```js
const promises = [];
for(let file of files) {
  promises.push(Storage.put(file))
}

await  Promise.all(promises);
```

**Comment by YikSanChan** [comment]
@manueliglesias Thank you

**Comment by sammartinez** [comment]
@YikSanChan Since S3 does not support this currently, I am going to close this request out. Please try the workaround above. If you would like to open up a request with S3, please do so via [S3 forums](https://forums.aws.amazon.com/forum.jspa?forumID=24).
