### ISSUE TITLE
Support file upload progress in amplify API

### ISSUE THREAD

**Issue by DavidOnGitHub** [aws-amplify/amplify-js#2911]
We are using amplify in our project and there is a need to upload file from browser to a backend API instead of directly to S3. So we need to display the progress of the upload but amplify API doesn't support the onUploadProgress listener, although it uses axios under the hood.

So should I create an PR for this or is there a better solution? Since amplify is using axios the change should be straightforward, just need to pass the onUploadProgress option through to axios.

**Comment by manueliglesias** [comment]
Hi @DavidOnGitHub 

Feel free to create a PR, we'll review it

**Comment by DavidOnGitHub** [comment]
Hi @manueliglesias , I've got permission denied when I tried to push to a feature branch. Could you please give me the permission to push? Thanks.

**Comment by 3nvi** [comment]
@manueliglesias The issue was flagged as closed but I have long submitted a PR that addresses it.

The PR itself is pending to be closed since it was never reviewed. Is there a chance we could do something about it?
