### ISSUE TITLE
Docs: wrong Cache.getItem usage

### ISSUE THREAD

**Issue by enzo-beltrami** [aws-amplify/amplify-js#2913]
I think this is a problem with the docs and not the code, when u use the Cache module to retrieve federatedInfo the docs say that it's a promise however it isn't, i got a `Cache.getItem('federatedInfo').then(...) is not a function`  then i tried to use it synchronously and it worked. 

We should change the code at https://aws-amplify.github.io/docs/js/authentication from this:
```
import { Cache } from 'aws-amplify';

// Run this after the sign-in
Cache.getItem('federatedInfo').then(federatedInfo => {
     const { token } = federatedInfo;
});
```
to this:
```
import { Cache } from 'aws-amplify';

// Run this after the sign-in
const { token } = Cache.getItem('federatedInfo')
```

I dont know if this is specifc from my config, im using a cognito identity pool with google federated login.

**Comment by manueliglesias** [comment]
Thank you @enzo-beltrami 

I'll be labeling this issue and sending a PR with the fix
