### ISSUE TITLE
Is federatedSignin (with Facebook) supposed to pop-up a window to refresh the access token?

### ISSUE THREAD

**Issue by peetss** [aws-amplify/amplify-js#2926]
** Which Category is your question related to? **

Federated Sign-in

** What AWS Services are you utilizing? **

Cognito

** Provide additional details e.g. code snippets **

Using the code examples from here (https://aws-amplify.github.io/docs/js/authentication#federated-sign-in) I find that periodically a popup will briefly appear.

- Is this to refresh the access token?
- Is there a way to extend the `expires_at`?
- Why aren't popups needed for other websites where I use Facebook to login?

This is especially troublesome if the user has popups blocked (and most do).  Is there a way to refresh the access token without needing to briefly popup a new window?

**Comment by powerful23** [comment]
@peetss yes we are refreshing the access token by using `FB.getLoginStatus()`: https://developers.facebook.com/docs/reference/javascript/FB.getLoginStatus/. 

As I know there is no way to extend the expiration time as it's defined by Facebook. I am not sure if this method will cause a popup window, will try to reproduce it. Can you tell me how often does this window pop up?

**Comment by peetss** [comment]
I would say it occurs as often as the token expires.  However, in most browsers the popup is automatically blocked, so the whole refresh flow can be blocked.

**Comment by peetss** [comment]
Any update on this? @powerful23
