### ISSUE TITLE
Aws-exports.js showing in production (major flaw)

### ISSUE THREAD

**Issue by RoniqueRicketts** [aws-amplify/amplify-js#2927]
**Describe the bug**
The Aws-exports and App.js files are showing in production. I was going through this tutorial [https://aws-amplify.github.io/docs/js/react](url) and the project was successfully built but all the secret information is visible. 

**To Reproduce**
1. Upload code to Github.
2. Deploy app from Github using the amplify console. 
3. Open the built project's website
4. Inspect the website using the google chrome dev tools.
5. Go to the Sources tab and inspect the folders.

**Expected behavior**
The folders should look like this
![Capture](https://user-images.githubusercontent.com/17409035/54936205-f7059800-4eef-11e9-9d24-d626fad2d142.JPG)

**Screenshots**
![Capture](https://user-images.githubusercontent.com/17409035/54936253-18668400-4ef0-11e9-94ce-c32df16be324.JPG)

**Desktop (please complete the following information):**
 - OS: [Win10]
 - Browser [Chrome]
 - Version [72.0.3626.121]

**Additional context**

**Sample code**
This repository will be available until the issue is fixed. [https://github.com/RoniqueRicketts/amplifytestertwo](url)
Here is a sample of the YML file provided by the online console. 
`version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
`

**Comment by emeryaa** [comment]
Please add hosting to your project before publishing your project
Command: amplify hosting add

Trying to add hosting without chances

amplify hosting add
Hosting is already fully enabled.

Error: Hosting is already fully enabled.

**Comment by emeryaa** [comment]
After crashed when publish project to aws I had init new amplify configuration
After that I don't seee any data before added to the project by amplify status

Api
Auth

I have these files at project dir

image

amplify publish still do not usable for publish project

**Comment by undefobj** [comment]
Hi @RoniqueRicketts the information contained in the `aws-exports.js` file is necessary to construct the service endpoints in order for your client to communicate with the backend and not secret information to access your AWS account. This information is acceptable for your client application and shouldn't risk inappropriate access to resources as long as you leverage the proper workflows outlined by the Amplify Framework (the Amplify CLI automatically sets these workflows up for you). For example the client apps will use the Cognito endpoint information for end users to register & login, those users will then be able to interact with services such as S3 and AppSync with the resulting credentials. None of this information could be used for accessing AWS accounts outside of a client application.
