### ISSUE TITLE
NoAuth App URL stays with SAML error till clear Browser Cache 

### ISSUE THREAD

**Issue by khirodAsurion** [aws-amplify/amplify-js#2932]
This is wrt. AWS-AMPLIFY . I am using with my react app +Cognito

I am using AWS Cognito 

When I show SSO page ( federated with Cognito) and a valid user( Authentic user
)  logs in he is able to see the application .But when a User who is not a Authentic user for the Application in my code I call Auth.signOut() , I get the SAML response as Not Authenticated. . and the URL of App changes with a SAMl error 

The Issue I see is , post this if i try to change the url manually to earlier (correct App URL) 
 and hit enter, then app does not show me the Login uRL. it again shows the Error URL . this happens till clear the cache . 

So, Question is , should i be taking of any cache/cookie at this time to get away with this issue

**Comment by powerful23** [comment]
@khirodAsurion can you describe the issue with more details?
- Are you using Cognito Hosted UI and Amplify together following this doc: https://aws-amplify.github.io/docs/js/authentication#using-amazon-cognito-hosted-ui
- What do you mean by 

> when a User who is not a Authentic user for the Application in my code I call Auth.signOut() 

If the user is not authenticated, why would you call `signOut`?

**Comment by emeryaa** [comment]
Please add hosting to your project before publishing your project
Command: amplify hosting add

Trying to add hosting without chances

amplify hosting add
Hosting is already fully enabled.

Error: Hosting is already fully enabled.

**Comment by khirodAsurion** [comment]
> @khirodAsurion can you describe the issue with more details?
> 
> * Are you using Cognito Hosted UI and Amplify together following this doc: https://aws-amplify.github.io/docs/js/authentication#using-amazon-cognito-hosted-ui
> * What do you mean by
> 
> > when a User who is not a Authentic user for the Application in my code I call Auth.signOut()
> 
> If the user is not authenticated, why would you call `signOut`?

Hi @powerful23 , 

1>I am not using Cognito Hosted UI .I am Showing Ping Federated Login UI .

2>Correct , I removed the Auth.Logout() . it was definitely a mistake . but still i see once a non Application Authenticated user tries to login ..and we show Not Authenticated Page, if I change the URL to correct App URL . It still goes to error URL without showing the Login Page .

**Comment by powerful23** [comment]
@khirodAsurion can you provide some code snippets about how you are using Amplify Auth?

**Comment by khirodAsurion** [comment]
> @khirodAsurion can you provide some code snippets about how you are using Amplify Auth?

Sure , 
I create a link to redirect the App to PINGSSO on hit of my App URL like below 

`import React from 'react';
import { withOAuth } from 'aws-amplify-react';
import Spinner from '../spinner/Spinner';
import config from '../../appconfig/config';
class Landing extends React.Component {
  componentDidMount() {
    const { domain, redirectSignIn, responseType, scope } = config.Amplify.Auth.oauth;
    const clientId = config.Amplify.Auth.userPoolWebClientId;
    const url = `https://${domain}/oauth2/authorize?identity_provider=SSODev.xxxx.com&?redirect_uri=${redirectSignIn}
                      &response_type=${responseType}&client_id=${clientId}&scope=${scope.join(
      '+'
    )}`;

    window.location.assign(url);
  }

  render() {
    return <div>We are trying to login </div>;
  }
}

export default withOAuth(Landing);
`
the config is defined in a file as below 
`{
  "Amplify": {
    "Auth": {
      "identityPoolId": "xxxxxxxx",
      "region": "us-east-1",
      "userPoolId": "xxxxxxx",
      "userPoolWebClientId": "xxxxxxx",
      "oauth": {
        "domain": "xxxxxxxx.auth.us-east-1.amazoncognito.com",
        "scope": ["openid", "profile", "aws.cognito.signin.user.admin"],
        "redirectSignIn": "http://localhost:7000/",
        "redirectSignOut": "http://localhost:7000/",
        "responseType": "code",
        "options": { "AdvancedSecurityDataCollectionFlag": true }
      },
      "mandatorySignIn": true
    }
  }
}
` 
based on the signedin or not I route the user to either Application or a static noauth page 

`
import React, { Component } from 'react';
import { withRouter, Route, Switch } from 'react-router-dom';
import Landing from '../components/Landing';
import NoAuth from '../components/Noauth';

import ApplicationContainer from '../application/ApplicationContainer';

class ApplicationRouter extends Component {
  componentDidMount() {
    this.setAppRoute(this.props);
  }

  componentDidUpdate(prevProps) {
    if (this.props.authState !== prevProps.authState) {
      this.setAppRoute(this.props);
    }
  }

  setAppRoute(props) {
    const { history } = props;
    const hasError = window.location.search.includes('error_description');

   
    const { authState } = props;

    switch (authState) {
      case 'signedIn':
        history.push('/main');
        break;

      default:
        if (hasError) {
          history.push('/noAuth');
        } else {
          history.push('/signIn');
        }
        break;
      
    }
  }

  render() {
    return (
      <Switch>
        <Route path="/signIn" component={Landing} />
        <Route path="/noAuth" component={NoAuth} />
        <Route path="/main" component={ApplicationContainer} />
      </Switch>
    );
  }
}

export default withRouter(ApplicationRouter);
`

so it does the work ..but once not authenticated scenario comes , user sees the no Auth static page ...but next time when he again hits the url of app ..same SAML error with shows up without asking for login page ..

**Comment by powerful23** [comment]
@khirodAsurion I don't think you are using amplify correctly.
- In the <Landing/> component, the url is triggered as long as the component is mounted, which means the user will be directed to the OAuth login page, in that case you don't need to use the `withOAuth` HOC

- Once you are redirected back to your app, you would need to use the `Hub` module to detect whether you are signed in or not: https://aws-amplify.github.io/docs/js/authentication#make-it-work-in-your-app. In that example we are calling`setState` but in your case it's `history.push` to go to different routes.

Can you try to reorganize your code accordingly?
