### ISSUE TITLE
AWS Pinpoint Analytics.updateEndpoint gives an invalid userId output

### ISSUE THREAD

**Issue by amilaDulanjana** [aws-amplify/amplify-js#2934]
**Describe the bug**
I want to update the `userId `using `Analytics.updateEndpoint({})`. But `userId `is not getting updated.

**Expected behavior**
I should be able to send the push notifications to a specific user using the `userId`.

**Screenshots**
![p1](https://user-images.githubusercontent.com/16540483/54987356-796a8680-4fda-11e9-99b7-339ad9be6eeb.png)

**Additional context**
There are 2 (A and B Sections in the screenshot) requests(updateEndpoint) getting fired, therefore it changes the `userId `value from the second request (B section in screenshot provided). However, if we use the second value generated for `userId `the push notification gets sent successfully.

**Sample code**

```
     import React, { Component } from 'react';
     import { Platform, StyleSheet, Text, View } from 'react-native';

     import { Logger } from 'aws-amplify';
     import Auth from '@aws-amplify/auth';
     import Analytics from '@aws-amplify/analytics';
     import PushNotification from '@aws-amplify/pushnotification';

     import config from './aws-exports'

     Auth.configure(config);
     Analytics.configure(config);
     PushNotification.configure(config);
     Logger.LOG_LEVEL = 'DEBUG';

    export default class App extends Component {

    componentDidMount() {
        PushNotification.onNotification((notification) => {
            console.log('in app notification', notification);
        });

        PushNotification.onRegister((token) => {
            console.log('in app registration', token);
            Analytics.updateEndpoint({
                address: token,
                OptOut: 'NONE',
                userId: "100"
            }).then(data => {
                console.log(data)
            }).catch(error => {
                console.log(error)
            });

        });

        PushNotification.onNotificationOpened((notification) => {
            console.log('the notification is opened', notification);
        });
    }
    render() {
        return (
            <Text>Welcome to React Native!</Text>
        );
      }
    } 
```

**Comment by powerful23** [comment]
@amilaDulanjana I am confused by this sentence:

>  However, if we use the second value generated for userId the push notification gets sent successfully.

Do you mean you get to receive the notification after the second call? Why you are saying the user id is not updated?

Also there is no need to update the endpoint with the token in your code because the `PushNotification` module will do it automatically internally. Can you give more context about what are you trying to do?

**Comment by amilaDulanjana** [comment]
I wanted to update the `userId` with a customized value(`userId` is the primary key of the user table in my database). I used the following c# code to send push notifications for specified user (using `userId`).

```
                var config = new AmazonPinpointConfig { RegionEndpoint = RegionEndpoint.USEast1 };
                var client = new AmazonPinpointClient("<Access Key>", "<Secret key>", config);
                DefaultPushNotificationMessage defaultPushNotificationMessage = new DefaultPushNotificationMessage();
                //defaultPushNotificationMessage.Action = Amazon.Pinpoint.Action.DEEP_LINK;
                defaultPushNotificationMessage.Body = "some message";
                defaultPushNotificationMessage.Title = "some title";
                DirectMessageConfiguration directMessageConfiguration = new DirectMessageConfiguration();
                directMessageConfiguration.DefaultPushNotificationMessage = defaultPushNotificationMessage;
                EndpointSendConfiguration endpointSendConfiguration = new EndpointSendConfiguration();
                SendUsersMessagesRequest sendUsersMessagesRequest = new SendUsersMessagesRequest();
                SendUsersMessageRequest sendUserMessageRequest = new SendUsersMessageRequest();
                Dictionary<string, EndpointSendConfiguration> map = new Dictionary<string, EndpointSendConfiguration>();
                map.Add("<User id>", endpointSendConfiguration);
                sendUserMessageRequest.Users = map;
                sendUsersMessagesRequest.ApplicationId = "<Application Id>";
                sendUserMessageRequest.MessageConfiguration = directMessageConfiguration;
                sendUsersMessagesRequest.SendUsersMessageRequest = sendUserMessageRequest;
                SendUsersMessagesResponse response = client.SendUsersMessagesAsync(sendUsersMessagesRequest).Result;

```
If I used `userId` in Section A (image attached above), i cannot send the push notification but if I used the `userId` in section B (image attached above) I can send the push notification.

Please note A and B sections, shows the updated endpoint value objects.
Let me know if you need more clarifications. Thank you.

**Comment by emeryaa** [comment]
After crashed when publish project to aws I had init new amplify configuration
After that I don't seee any data before added to the project by amplify status

Api
Auth

I have these files at project dir

image

amplify publish still do not usable for publish project

**Comment by powerful23** [comment]
@amilaDulanjana correct me if I'm wrong.
Is the second `updateEndpoint` request sent automatically which will then covers the change you made in the first one?

**Comment by amilaDulanjana** [comment]
@powerful23 yes, that's what I understood too

**Comment by powerful23** [comment]
@amilaDulanjana do you know that you can turn off the automatic analysis tracking by setting:
```js
Analytics.configure({
      autoSessionRecord: false
});
```
 in the begging of your code. Thus it won't send any request automatically.

**Comment by amilaDulanjana** [comment]
@powerful23 I used following code now it works as I expected

```
 Amplify.configure({
            // To get the AWS Credentials, you need to configure 
            // the Auth module with your Cognito Federated Identity Pool
            Auth: {
                identityPoolId: config.aws_cognito_identity_pool_id,
                region: config.aws_cognito_region
            },
            Analytics: {
                // OPTIONAL - disable Analytics if true
                disabled: false,
                // OPTIONAL - Allow recording session events. Default is true.
                autoSessionRecord: false,

                AWSPinpoint: {
                    // OPTIONAL -  Amazon Pinpoint App Client ID
                    appId: config.aws_mobile_analytics_app_id,
                    // OPTIONAL -  Amazon service region
                    region: config.aws_cognito_region,//'us-east-1',
                    // OPTIONAL -  Customized endpoint
                    endpointId: '100',
                    // OPTIONAL - Default Endpoint Information
                    endpoint: {
                        address: '100', 
                        optOut: 'ALL',
                        // Customized userId
                        userId: '100',
                    },
                    bufferSize: 1000,
                    flushInterval: 5000, // 5s 
                    flushSize: 100,
                    resendLimit: 5
                }
            }
        });
```

But if I used ` react-native-router-flux`, then this won't work.

**Comment by LosD** [comment]
@powerful23 Have you ever seen `autoSessionRecord: false` actually work? Looking at the code, AWSPinpointProvider seems to completely ignores it, and sets the update timer as long as it is not disabled, and has an app ID.

... Which is exactly what I have experienced it to do. I checked for a test verifying it, but there is nothing.
