### ISSUE TITLE
aws-amplify-vue: signOut event fired when cancelling signUp

### ISSUE THREAD

**Issue by Christilut** [aws-amplify/amplify-js#2935]
**Describe the bug**
I'm using the <Authenticator> component and when pressing the "Create an account" link it fires the `signUp` event as expected. But when I then click the "Sign In" link on that page the `signedOut` event triggers. This is the same event that happens when clicking the "Sign out" button.

So if I listen to the `signOut` event and redirect a user to my home page or login page, this also happens when cancelling a user sign up. I don't think this is intended.

**Expected behavior**
I expect some sort of `cancelSignUp` event to fire instead of the `signedOut`. I believe the `signedOut` should only be fired when the user actually logs out.

**Desktop (please complete the following information):**
 - OS: Linux
 - Chrome 73

**Additional context**
aws-amplify 1.1.22
aws-amplify-vue 0.2.7

**Comment by emeryaa** [comment]
Please add hosting to your project before publishing your project
Command: amplify hosting add

Trying to add hosting without chances

amplify hosting add
Hosting is already fully enabled.

Error: Hosting is already fully enabled.
