### ISSUE TITLE
refreshing federation token failed: no fb sdk available

### ISSUE THREAD

**Issue by tafelito** [aws-amplify/amplify-js#2941]
**Describe the bug**
I have an expo app that uses Facebook Login. I created a federated identity pool and after I get fb token, I'm using `Auth.federatedSignIn` to authenticate the user with amplify. Then I use S3 storage to access some images. Everything works fine until I close the app.

After I close the app, when I re-open it, I check if the user is logged in doing `await Auth.currentAuthenticatedUser()`. I get the user. But then when I try to get the credentials from `await Auth.currentCredentials()` it gives the error `refreshing federation token failed: no fb sdk available`

I need to get the credentials in order to init the appsync client with  `complexObjectsCredentials: () => Auth.currentCredentials()`

**To Reproduce**
1. Create an expo app using `expo init`
1. Login with FB using `Expo.Facebook.logInWithReadPermissionsAsync`
2. Use the token to auth with amplify `Auth.federatedSignIn`
3. Close the app
4. Get credentials with `Auth.currentCredentials()`

**Smartphone (please complete the following information):**
 - Device: iPhone XS (simulator)
 - OS: 12.1

**Additional context**
```
"aws-amplify": "^1.1.22"
"expo": "^32.0.0"
"aws-amplify-react-native": "^2.1.8"
"aws-appsync": "^1.7.2"
"aws-appsync-react": "^1.2.7"
```

**Comment by emeryaa** [comment]
Please add hosting to your project before publishing your project
Command: amplify hosting add

Trying to add hosting without chances

amplify hosting add
Hosting is already fully enabled.

Error: Hosting is already fully enabled.

**Comment by powerful23** [comment]
@tafelito Hi, when using `federatedSignIn` in React native, you need to provide your own `refreshHandler` which will be used to refresh the token: https://aws-amplify.github.io/docs/js/authentication#federated-sign-in -> refreshing JWT tokens. I noticed that the doc doesn't point out that the default handler is only working in the web environment, will send a pr to fix it.

**Comment by tafelito** [comment]
Ok good because I read that but I didn't know it didn't work for RN.  I didn't see that this is a duplicate of #1867 either 

I understand I have to provide the refreshToken myself, but isn't that function supposed to be called when the token is expired? I checked the token I received from facebook and is expires 2 months after I receive it, so why every time I refresh the app it assumes is expired?

**Comment by powerful23** [comment]
@tafelito no, it is triggered when you call `Auth.currentCredentials` or if internally, calling that function. It will then check if the token is expired or not, and if expired, use the `refreshHandler` to refresh it. So all those things is to make sure it is using a valid token to get the AWS credentials from Cognito.

**Comment by tafelito** [comment]
just to be clear, if the token is not expired, is the function refreshToken called? Because as I said, my token is not expired, and the function is still being called. if that's the case, then I'm the one that need to check if the token is expired or not, and then if it is, then refresh it, is that it?

Because from the name of the function, it seems that I would only need to provide a function that in the case the token is expired, then provide a new one. At least that's what I understood

**Comment by powerful23** [comment]
@tafelito sorry to be late. Yes this function should only be triggered if the token is expired. Could you do a check about the parameter you passed when calling `Auth.federatedSignIn`: https://aws-amplify.github.io/docs/js/authentication#facebook-example-in-react-native-expo Note the `expires_at` parameter which will be used to tell whether the token is expired or not
