### ISSUE TITLE
Cognito web. Cannot login with 2nd user without signing out the 1st user.

### ISSUE THREAD

**Issue by guanzo** [aws-amplify/amplify-js#2945]
**Describe the bug**
In the same browser, if a user previously logged in with 1 account, then tries to login with a 2nd account, the login attempt will fail.

**To Reproduce**
There are 2 users: A and B.

1. On login page, login user A with `Auth.signIn()`
2. Navigate user A to the app, where this code is called
```
AWS.config.credentials = await Auth.currentUserCredentials()
```
3. Navigate back to login page. `Auth.signOut()` is NOT called. This bug does not occur if `Auth.signOut()` is called, however you can't expect the user to always sign out before switching accounts.
4. Login user B with `Auth.signIn()`.
5. Navigate user B to the app, where this code is called
```
AWS.config.credentials = await Auth.currentUserCredentials()
```
6. Error is thrown: `Logins don't match. Please include at least one valid login for this identity or identity pool.` See screenshot

![screenshot](https://i.gyazo.com/65ce835b7c6dac2df05593fa90266c1c.png)

**Expected behavior**
User B should be able to login with no errors.

**Screenshots**
Screenshot of the console log with DEBUG enabled.

![ss](https://i.gyazo.com/3a2a251c837a68deb896b52603cecf73.png)

POST request fails with 400 code
![post](https://i.gyazo.com/57c4cb4b353e40d7f47fa063fb9b3c2e.png)

POST response
![post](https://i.gyazo.com/5d0d7632b3ba7a126df0e86a9ea1cf5a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 73.0.3683.86

**Additional context**
This bug has already been solved in `aws-sdk-js`! 

Original issue: https://github.com/aws/aws-sdk-js/issues/609

The AWS JS docs mention this situation as well: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityCredentials.html

```
// optional, only necessary when application runs in a browser
// and multiple users are signed in at once, used for caching
LoginId: 'example@gmail.com'
```

How do I set the `LoginId` parameter through `aws-amplify`?

**Comment by jkeys-ecg-nmsu** [comment]
Is this a bug or desired behavior?

**Comment by powerful23** [comment]
@guanzo I don't think this behavior is supported in Amplify.

> however you can't expect the user to always sign out before switching accounts.

Could you explain more about this? If the user is logged in, he/her should always be remembered and stayed as logged in until `signOut` is called or the session is expired.

**Comment by guanzo** [comment]
> Could you explain more about this? If the user is logged in, he/her should always be remembered and stayed as logged in until signOut is called or the session is expired.

That's working fine for me, single users are being remembered. The problem is when I try to switch accounts without signing out the first account.

When you say "remembered", do you mean client side or server side? I'm using cookie storage, and when I login User B after User A, the cookies seem to be updated correctly. The error occurs when
I call `await Auth.currentUserCredentials()` . A POST request with User B's data is sent to `https://cognito-idp.us-east-2.amazonaws.com/`, which fails with a 400 status code and the message `Logins don't match`. Data related to User A is being stored on the server and that's somehow conflicting with the POST request.

Anyways, isn't specifying the `LoginId` parameter the solution, or am I reading the description wrong? All I want to do is be able to login with multiple accounts, without first signing out.

**Comment by jkeys-ecg-nmsu** [comment]
@guanzo why can't you just add a call to `Auth.signOut()` as the first statement in your login callback?
