### ISSUE TITLE
Using i18n for angular project

### ISSUE THREAD

**Issue by hoang-innomizetech** [aws-amplify/amplify-js#2949]
I tried to modify the i18n vocabulary to change some textes but it seems on the sign in form, the test doesn't effect.

Here is the code i added to the app.component.ts
```
I18n.setLanguage('en');
const dict = {
    'en': {
        'Sign In': "Registrarse",
        'Sign Up': "Regístrate",
        'Forgot Password?': ''
    }
};

amplify.i18n().

I18n.putVocabularies(dict);

console.log('Message', I18n.get('Forgot Password?'));
```

It effected when we use i18n but the form still display old text. 

I am using latest amplify and angular verion

"aws-amplify": "1.1.22",    
"aws-amplify-angular": "2.1.9",

**Comment by powerful23** [comment]
@hoang-innomizetech can you try putting the following code in your `main.ts` file?
```js
import { I18n } from 'aws-amplify';

I18n.setLanguage('en');
      const dict = {
          'en': {
              'Sign In': "Registrarse",
              'Sign Up': "Regístrate",
              'Forgot Password?': 'abc'
          }
      };

    I18n.putVocabularies(dict);
```

**Comment by hoang-innomizetech** [comment]
Yes, I've tried on both main.ts and app.component.ts file.

However, I just upgraded to the latest version 1.1.23 and 2.1.10 and it is working now. So I will close this issue

**Comment by Muttaki-Khan** [comment]
my html heading is
<h3> Hello there! </h3>
so i want this Hello there! in chinese while loading my website
i wrote this code
I18n.setLanguage('ch');
const dict = {
  'bh': {
    'Hello there!': "Apa khabar di sana!"
  },
  'ch': {
    'Hello there!': "你好！"
  }
};

I18n.putVocabularies(dict);
I18n.get('Hello there!');

But how can i tell my html to show chinese???
how to call this I18n function
