### ISSUE TITLE
Error message should be cleared

### ISSUE THREAD

**Issue by hoang-innomizetech** [aws-amplify/amplify-js#2950]
The first time user login, they got an error say **Username and password do not match**. They updated their password and clicks login again, at this time the error message still there, but it should be cleared. 

Right now we cannot control whenever the action is fired such as before logging in we wanted to show a loading indicator. There is no such an auth state is changed before authenticating user.

**Comment by elorzafe** [comment]
@hoang-innomizetech which framework are you using?

**Comment by hoang-innomizetech** [comment]
@elorzafe sorry, I should make it clear. I am using the latest angular and amplify version.

There are a couple of scenarios we should clear the error message before executing an action:
* sign in
* sign up
* navigate between sign in and forgot password form

**Comment by hoang-innomizetech** [comment]
@jordanranz Can we add this to UI enhancement milestone?

**Comment by haverchuck** [comment]
@hoang-innomizetech I merged a fix for this into the unstable build, which can be installed via `npm i aws-amplify-angular@unstable`.  It will make it's way in the main build in due time.  Closing this issue.
