### ISSUE TITLE
Unable to apply custom theme to withAuthenticator [React Native] [Help wanted]

### ISSUE THREAD

**Issue by dhyeysejpal** [aws-amplify/amplify-js#2951]
I am passing the theme object to the withAuthenticator HOC but it doesn't seem to have any effect. I still seem to have a navbar on top of my every screen, the auth screens as well as my app home screen.

Can anyone confirm having faced this issue? Would this happen due to amplify or is this a side-effect of using react-native-navigation? Any help is appreciated!

Here is how it looks:

![54430789-a1402b80-474a-11e9-8986-f7753af03ae8](https://user-images.githubusercontent.com/5461242/55134610-41d11b00-514f-11e9-9e36-892a4b1f9e12.png)

Here is my code:

```
/**
 * Dashboard screen with Authenticator wrapper around the entire app.
 */

import React, { Component } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { ConfirmSignUp, AmplifyTheme, ForgotPassword, RequireNewPassword, withAuthenticator } from 'aws-amplify-react-native'
import MySignIn from './MySignIn';
import MySignUp from './MySignUp';
import { THEME_COLOR } from './config';

class Dashboard extends Component {
	render() {
		return (
			<View style={styles.container}>
				<Text>
					<Text style={styles.welcome}>This is Dashboard screen.</Text>
				</Text>
			</View>
		);
	}
}

const myNavBar = Object.assign({}, AmplifyTheme.navBar, { width: 0, height: 0});
const MyTheme = Object.assign({}, AmplifyTheme, { navBar: myNavBar });


const styles = StyleSheet.create({
	welcome: {
		fontSize: 30,
		color: 'black'
	},
	container: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center'
	}
});

export default withAuthenticator(Dashboard, false, [
	<MySignIn/>,
	<MySignUp />,
	<ConfirmSignUp/>,
	// <ForgotPassword/> ,
	// <RequireNewPassword/>
], null, MyTheme); 

```

**Comment by powerful23** [comment]
@dhyeysejpal hi, could you try: 
```js
const myNavBar = Object.assign({}, AmplifyTheme.navBar, { width: 0, height: 0, marginTop: 0});
```

**Comment by dhyeysejpal** [comment]
@powerful23:

Thank you for the reply. I tried it but unfortunately it doesn't work. Is anyone able to reproduce this problem?

**Comment by dhyeysejpal** [comment]
Okay, I found this https://github.com/wix/react-native-navigation/issues/3160 that talks about the navbar appearing due to react native navigation. I will try to follow the steps given there to see if I can fix it and update the thread here.

**Comment by dhyeysejpal** [comment]
I was able to get rid of that topBar by changing the options of react-native-navigation, but a problem still remains. I am still unable to apply custom theme to the components. 

I did this to get rid of the top space showing on the sign in screen but it has no effect.
```
const myNavBar = Object.assign({}, AmplifyTheme.navBar, { width: 0, height: 0 });
const mySection = Object.assign({}, AmplifyTheme.section, { marginTop: 0, padding: 0});

const MyTheme = Object.assign({}, AmplifyTheme, { navBar: myNavBar, section: mySection });
```

And the sign in component looks like this:
```
<KeyboardAvoidingView style={[theme.section, {backgroundColor: THEME_COLOR}]}>
                <Header> Sign in to your account </Header> 
```
But it still looks like this with a lot of white space up top:

![Screenshot (104)](https://user-images.githubusercontent.com/5461242/55532062-1eb3e780-56ca-11e9-838e-267a1ee0c544.png)

Is there a way to make it stretch to occupy the full screen?

I appreciate the help!

**Comment by jordanranz** [comment]
@dhyeysejpal,

In your example above you have 
```
const myNavBar = Object.assign({}, AmplifyTheme.navBar, { width: 0, height: 0 });
const mySection = Object.assign({}, AmplifyTheme.section, { marginTop: 0, padding: 0});

const MyTheme = Object.assign({}, AmplifyTheme, { navBar: myNavBar, section: mySection });
```
and not:
```
const myNavBar = Object.assign({}, AmplifyTheme.navBar, { width: 0, height: 0});
const myContainer = Object.assign({}, AmplifyTheme.container, { marginTop: 0 });

const MyTheme = Object.assign({}, AmplifyTheme, { navBar: myNavBar, container: myContainer });
```

To get rid of the margin you need `const myContainer = Object.assign({}, AmplifyTheme.container, { marginTop: 0 });`

Did you try this?

Also, could you share a code snippet for the `MySignIn` component

**Comment by dhyeysejpal** [comment]
@jordanranz:

Yes, I did try it but unfortunately it had no effect. Here is the screenshot for the result:

![Screenshot (105)](https://user-images.githubusercontent.com/5461242/55666024-f7921d00-5865-11e9-9db1-1a20c00f6468.png)

And here is the code for my SignIn component:

```
import React from 'react';
import { Auth } from 'aws-amplify';
import { SignIn, FormField, Header, LinkCell } from 'aws-amplify-react-native';
import { View, Text, Image, KeyboardAvoidingView, StyleSheet, TextInput, ScrollView, Button, Alert } from 'react-native';
import { THEME_COLOR } from './config'

export default class MySignIn extends SignIn {
    constructor(props) {        
        super(props);
        this.state = {
            username: null,
            password: null,
            error: 'none'
        }
        this.checkContact = this.checkContact.bind(this);
        this.signIn = this.signIn.bind(this);
    }

    signIn() {
        const { username, password } = this.state;
        Auth.signIn(username, password)
            .then(user => {
                if (user.challengeName === 'NEW_PASSWORD_REQUIRED') {
                    this.changeState('requireNewPassword', user);
                } else {
                    this.checkContact(user);
                }
            })
            .catch(err => this.error(err));
    }

    checkContact(user) {
        Auth.verifiedContact(user)
            .then(data => {
                logger.debug('verified user attributes', data);
                if (!JS.isEmpty(data.verified)) {
                    this.changeState('signedIn', user);
                } else {
                    user = Object.assign(user, data);
                    this.changeState('verifyContact', user);
                }
            });
    }

    showComponent(theme) {      
        return (
            <View style={[theme.container, {backgroundColor: THEME_COLOR}]}>
                <Header> Sign in to your account </Header> 
                <FormField
                    theme={theme}
                    onChangeText={(text) => this.setState({ username: text })}
                    label='Email'
                    required={true}
                />
                <FormField
                    theme={theme}
                    onChangeText={(text) => this.setState({ password: text })}
                    label='Password'
                    secureTextEntry={true}
                    required={true}
                />
                <Button
                    title='SIGN IN'
                    onPress={this.signIn }
                    disabled={!this.state.username || !this.state.password}
                    color={THEME_COLOR}
                />
                <View style={{ flexDirection: 'row' }}>
                    <LinkCell theme={theme} onPress={() => this.changeState('forgotPassword')}>
                        Forgot Password?
                    </LinkCell>
                    <LinkCell theme={theme} onPress={() => this.changeState('signUp')}>
                        Sign Up
                    </LinkCell>
                    <LinkCell theme={theme} onPress={() => this.changeState('confirmSignUp')}>
                        Confirm account
                    </LinkCell>
                </View>
            </View>
        );
    }
}
```

**Comment by dhyeysejpal** [comment]
Hi, is anyone able to solve this problem?

**Comment by sammartinez** [comment]
@dhyeysejpal Are you still experiencing this issue with a newer version of aws-amplify-react-native? We did have an issue with View and had an update that went out to add SafeAreaView. Just wanted to double check

**Comment by dhyeysejpal** [comment]
@sammartinez I can check it and let you know.

**Comment by dhyeysejpal** [comment]
@sammartinez I updated everything, including aws-amplify react-native to the latest version. Unfortunately I am not able to apply my custom theme to the components. With the latest version, I was able to get rid of  all the extra space that was there earlier, but trying to override the style for container does not work. Here is the snippet of code;

```
const myContainer = Object.assign({}, AmplifyTheme.container, { paddingTop: 0, backgroundColor: '#4CAFCD' });

const MyTheme = Object.assign({}, AmplifyTheme, { container: myContainer });

export default withAuthenticator(Dashboard, {
	includeGreetings: false,
	authenticatorComponents: [<MySignIn/>,<MySignUp />,<ConfirmSignUp/>],
	theme:{MyTheme}
});
```

The background color is not applied from above, but it shows up when I directly apply it to my view in the sign in component as follows:

```
showComponent(theme) {      
        return (
            <KeyboardAvoidingView style={[theme.container, { padding: 0, backgroundColor: '#4CAFCD', width: '100%'}]}>

```
Here is how it looks: 
![Screenshot (113)](https://user-images.githubusercontent.com/5461242/58744316-afa30700-845e-11e9-9724-c06f932f3188.png)

As seen, the paddingTop styling still shows up here

**Comment by saisaran96** [comment]
Go to AmplifyTheme.js and the the paddingTop to 0 in the container

**Comment by ptahdunbar** [comment]
@dhyeysejpal This has to do with Authenticator wrapping all components with a SafeAreaView.

@sammartinez @powerful23 @jordanranz would you accept a PR that adds a flag to swap out SafeAreaView with a View? This would fix this issue and enable support for iOS 11 <

**Comment by dhyeysejpal** [comment]
@ptahdunbar Could be possible. 

But would that also explain why I am not able to apply custom styles to the container component like background color as well? I can see that the container has the paddingTop of 20, which is causing the white strip here, and overwriting it to be 0 doesn't work.

**Comment by dhyeysejpal** [comment]
Not a stale issue. Still a problem

**Comment by GeorgeBellTMH** [comment]
I'm having this problem as well...

**Comment by KBB99** [comment]
Still having this issue.

**Comment by pperron** [comment]
A bypass (which is probably really not the best) I'm using is setting main <View> component of my custom signin page with "marginTop: -20" and "marginBottom: -20"... My app is still in development and only running in the Android simulator, so not sure if can fit all cases...

**Comment by pperron** [comment]
Ok, since previous reply was a strange fix, I took a look at the "AmplifyTheme.js" in Amplify source code and seen the "container" styling info, so I just copy pasted it into my custom theme and changed 2 things, the "paddingTop" and "marginBottom" (that one cause I had the "please sign in / signup" menu at bottom of window) to 0 and -20:

`
const MyTheme = Object.assign({}, AmplifyTheme, { 
  container: {
    flex: 1,
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'space-around',
    paddingTop: 0,
    paddingBottom: 0, 
    marginBottom: -20,
    width: '100%',
		backgroundColor: '#FFF',
  },
 });
export default withAuthenticator(App, {
	includeGreetings: false,
	authenticatorComponents: [<MySignIn/>,<MySignUp />,<ConfirmSignUp/>],
	theme:{MyTheme}
});
`
That code removed the white space header and pushed the bottom at -20 so I don't see the bottom info.

Still not sure if it's the best but try it and tell me ;)

**Comment by dhyeysejpal** [comment]
Thank you for the fix! I will try it out and update here.

**Comment by dhyeysejpal** [comment]
I can see that the theme container component is modified with the values we set, but there is still a white bar remaining on top. I will dive deeper and give it another try

**Comment by janoist1** [comment]
+1

**Comment by foxinni** [comment]
This helped me https://github.com/aws-amplify/amplify-js/issues/1949#issuecomment-577889484

**Comment by energyaustralia-coding-test** [comment]
After spending much time and using both Authenticator component and withAuthenticator HOC I have finally found something that worked, hopefully this will help others , source code below.My requirement was only to change the button and link texts and also to have a custom signup config

const AmplifyCustomTheme = Object.assign({}, AmplifyTheme, {
  button: {
    ...AmplifyTheme.button,
    backgroundColor: "#156760",
  },
  buttonDisabled: {
    ...AmplifyTheme.buttonDisabled,
    backgroundColor: "#6dbdb5",
  },
  sectionFooterLink: {
    ...AmplifyTheme.sectionFooterLink,
    color: "#156760",
  },
});

export default withAuthenticator(
  App,
  false,
  undefined,
  null,
  AmplifyCustomTheme,
  signupConfig
);

**Comment by imehra07** [comment]
After spending much time and using both Authenticator component and withAuthenticator HOC I have finally found something that worked, hopefully this will help others , source code below.My requirement was only to change the button and link texts and also to have a custom signup config

const AmplifyCustomTheme = Object.assign({}, AmplifyTheme, {
  button: {
    ...AmplifyTheme.button,
    backgroundColor: "#156760",
  },
  buttonDisabled: {
    ...AmplifyTheme.buttonDisabled,
    backgroundColor: "#6dbdb5",
  },
  sectionFooterLink: {
    ...AmplifyTheme.sectionFooterLink,
    color: "#156760",
  },
});

export default withAuthenticator(
  App,
  false,
  undefined,
  null,
  AmplifyCustomTheme,
  signupConfig
);
