### ISSUE TITLE
Auth.federatedSignIn not recycling ids

### ISSUE THREAD

**Issue by mithunkalan** [aws-amplify/amplify-js#2952]
`Auth.federatedSignIn` is not returning the same `IdentityId` for the same Google user.

I am using Amplify and Expo to sign in via google. 
`const { type, accessToken, user } = await Google.logInAsync({ clientId });`
`  if (type === "success") {`
`    Auth.federatedSignIn("google", { accessToken },  { name: user.id })`
`  }`

I am able to sign in and do what I need. But I noticed something strange. The `data.IdentityId` coming out of `Auth.federatedSignIn` keeps getting a new value for the same user. So, if I login, do stuff, log out, log in again, a new federated id gets made. There are two problems with whats going on. 

1. I keep making new Federated id's for the same user. This should be a single id per user. 
2. I cant use  `data.IdentityId` for anything because I cant trust that it will be the same. I have to resort to using `user.id` that comes from Expo. 

I do the same thing with the Expo/Amplify Facebook and the `data.IdentityId` are unchanging after multiple logins. This is the correct behaviour I am expecting.

What am I doing wrong? Or is this a real bug?

**Comment by powerful23** [comment]
@mithunkalan I think it's a service issue. Can you go to the aws forum: https://aws.amazon.com/premiumsupport/knowledge-center/send-feedback-aws/ and open an issue to the Cognito service team. We will also raise this issue to the service team but that would be more efficient if you could an issue there.

(Also can you go to the Cognito console -> your identity pool -> identity browser, and go to the identity id generated when you federated sign in with Google. If a new one is generated, then the old one will has some string like `DISABLED` showing up.)

**Comment by mithunkalan** [comment]
- I logged in via google, got a new federated ID. Made a note of it. 
- Sign out, and sign in again. Got a new Fed ID.
- Look at old Fed ID, no change. No words like disabled on it. Seems like its still active.

Interestingly I see in the identity browser that there are no Google linked logins. I must have logged in via google a few dozen times and it still shows 0 google logins. The cognito and facebook ID's have links. So I think its making unauthenticated IDs for google. 
I have 2 google API Auth provider IDs. One for the Expo app. One for the web ID with a secret. Tried both ID's and no change in result.  I have the web ID in the CognitoPool>Federation>IdentityPool because thats the only one with a secret attached to the key. The app ID is used in Expo. 

I'm busy investigating why there is no linking of the ID to the google provider. Will update.

**Comment by mithunkalan** [comment]
@powerful23 I fixed this. 
CognitoPool>Federation>IdentityPool requires the App's ID and not the Web ID.
I now get reliable Fed IDs and they are linked. 
This is the page that gives the wrong instructions that caused my problem. 
https://docs.aws.amazon.com/cognito/latest/developerguide/google.html
