### ISSUE TITLE
Publish versions more frequently to npm

### ISSUE THREAD

**Issue by lvl99** [aws-amplify/amplify-js#2953]
This is more a question than a request: I'm just wondering how often do you publish versions to NPM?

Viewing [aws-amplify-react](https://www.npmjs.com/package/aws-amplify-react) I can see that the last published version to npm was 22 days ago, and the github sidebar item says it was updated 11 hours ago (no doubt this is extra noise due to this repo being lerna-managed that some updates aren't related to the aws-amplify-react package itself).

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/238480/55152652-21a25b80-5151-11e9-975d-1ee8eda5d93b.png">

**Comment by powerful23** [comment]
@lvl99 thanks for your feedback! I will raise this issue in our team meeting.

**Comment by haverchuck** [comment]
Closing this issue for now, but it is a good point and we are actively discussing it.
