### ISSUE TITLE
Change login and password reset form labels

### ISSUE THREAD

**Issue by dave-graham** [aws-amplify/amplify-js#2954]
I've created a signup setup using cognito which requires just email to signup, which is great, and amplify is an awesome too to get up to speed quickly, but the labels for login and password reset are called 'username' rather than email.

Can there be additional parameters passed to the authenticator component that allows the "username" label to be overwritten across login and password reset as well as signup.

I'm building a react web application.

**Comment by powerful23** [comment]
Related to #104

**Comment by powerful23** [comment]
@dave-graham hi we are currently working on to enable the user to select signing up with only email/phone_number when using `Authenticator`. 

Another workaround for now is to use I18n to replace the `Username` with `Email`: https://aws-amplify.github.io/docs/js/i18n
For example:
```js
import { I18n } from 'aws-amplify';

I18n.setLanguage('en');
const dict = {
     'en': {
         'Username': 'Email'
      }
}
I18n.putVocabularies(dict);
```
This is ideal but can be used as a temporary solution.

**Comment by haverchuck** [comment]
Closing this issue for now.
