### ISSUE TITLE
Auth.forgotPassword does not work when user account status is "FORCE_CHANGE_PASSWORD"

### ISSUE THREAD

**Issue by alspdx** [aws-amplify/amplify-js#2955]
This might be a duplicate of [1182](https://github.com/aws-amplify/amplify-js/issues/1182).

When a user is created through the [JS/Node SDK](https://aws.amazon.com/sdk-for-node-js/) using [AdminCreateUser](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminCreateUser.html), they get an email with a temporary password. We have a common issue where a user does not log in before their temporary password expires or the user cannot find the email. 

When a new user is created their "Account Status" is `'FORCE_CHANGE_PASSWORD'` and we are setting `email_verified` to `true`.

It appears there is no way to reset the password using `Amplify.Auth.forgotPassword`. Unfortunately this puts us in a position where we have to resend the email through the CLI or manually reset the password in the AWS Console.

Ideally a user would be able to reset their password if their email is verified.

**Comment by powerful23** [comment]
@mithunkalan seems like it's a service issue. Can you go to the aws forum: https://aws.amazon.com/premiumsupport/knowledge-center/send-feedback-aws/ and open an issue to the Cognito service team. We will also raise this issue to the service team but that would be more efficient if you could an issue there. Thanks for reporting!

**Comment by alspdx** [comment]
@powerful23 Thanks for getting back to me on this, I'll raise my issue there.

**Comment by ebuychance** [comment]
@powerful23 It would be nice if you posted the issue link you raise.

**Comment by alspdx** [comment]
Here's a [link to the issue](https://forums.aws.amazon.com/thread.jspa?threadID=300918&tstart=0), however nobody has responded to it so far.

**Comment by elorzafe** [comment]
@alspdx according to cognito docs.
> The temporary password can only be used until the user account expiration limit that you specified when you created the user pool. To reset the account after that time limit, you must call AdminCreateUser again, specifying "RESEND" for the MessageAction parameter.

Currently there is no option for the library to do this. Is a server side problem that could implemented using a lambda function.

I will close this issue because a duplicate from #1182 

We have an open RFC for auth enhancements [here](https://github.com/aws-amplify/amplify-cli/issues/766) feel free to add this request or comments.

Thanks for your feedback!
