### ISSUE TITLE
Server side rendering is broken after versions 0.15

### ISSUE THREAD

**Issue by chengjia0807** [aws-amplify/amplify-js#2966]
Hi,

Server side rendering is broken after versions 0.15.

I gives me this error: "Error: Not supported"

I checked the source code:

```exports.default = (function (callback) {
    if (core_1.JS.browserOrNode().isBrowser && window.location) {
        var url = window.location.href;
        callback({ url: url });
    }
    else {
        throw new Error('Not supported');
    }
});
```

I guess it's because that the code is actually checking browser, it there is no "window.location" then it throws "Not supported" error.

However SSR does not have window at all.

Thanks

CJ

**Comment by elorzafe** [comment]
@chengjia0807 thanks for reporting, we are not supporting officially SSR but we will work on address this issue.

**Comment by chengjia0807** [comment]
> @chengjia0807 thanks for reporting, we are not supporting officially SSR but we will work on address this issue.

Hi Elorzafe,

Thanks for your reply.

Actually I hacked the code to solve it which is just delete "throw new Error('Not supported');".

Then it can work for me.

I am not sure about what is going to happen to other component if that line is deleted. But all basic functions are working for me without any issue.

Also I don't think this line was there before version 1.0.5.

Thanks for looking into it

Cheers
CJ

**Comment by ajhool** [comment]
@elorzafe Does this mean that Amplify React will not support SSR or that it will not even be compatible with SSR systems by deferring rendering until the component is client-side? Currently, when I just drop the component in, it breaks the web app. I have a workaround that seems to allow amplify-react to work alongside my app, but it has some rough edges that would be best solved internally.

Is there any chance that amplify will at least provide a "noSSR" flag for the Auth and Api components?

**Comment by elorzafe** [comment]
@chengjia0807 @ajhool thanks for your feedback. 

We will consider this as a feature request, we have other stuff we are working on right now, but we can add this issues into our roadmap. We are always happy to review PRs that can solve this issues 😉

**Comment by ajhool** [comment]
I'd be happy to add a PR, I added a related issue: https://github.com/aws-amplify/amplify-js/issues/3015 

Even though Amplify does not officially support SSR, would the team be willing to officially support deferring rendering to the client? Something along the lines of "We won't break SSR, but our components might not render on the server."

**Comment by chengjia0807** [comment]
Solved. Close now
