### ISSUE TITLE
Switching from 'aws-amplify' module to '@aws-amplify/auth' and '@aws-amplify/api' seems to require extra config that I cannot find

### ISSUE THREAD

**Issue by johnomalley** [aws-amplify/amplify-js#2969]
** Which Category is your question related to? **
Auth and API modules

** What AWS Services are you utilizing? **
+ Cognito Federated Identity - using Google as an IDP
+ API gateway with IAM authorizer
+ aws-amplify auth and api modules

** Provide additional details e.g. code snippets **
I was previously using the 'aws-amplify' NPM module to perform a federated login via google and to securely call a REST api via API gateway. This was in a JavaScript web app and the bundle size was way too large.  To solve the issue I tried to use the two modules individually.  This helped with the bundle size but now I cannot figure out how to get the API module to use the credentials from Auth.

I've been looking for quite a while for something in the configuration for API or docs with no luck.

Before:
``` typescript
import Amplify from 'aws-amplify'

// this worked perfectly
const region = 'xxx'
const amplifyConfig = {
  Auth: {
    region,
    identityPoolId: 'xxx'
  },
  API: {
    endpoints: [
      {
        name: 'xxx',
        endpoint: 'xxx',
        region
      }
    ]
}

Amplify.configure(amplifyConfig)

// later
Auth.federatedLogin(...)
API.get(...) // works!
```

After: 
``` typescript
import Auth from '@aws-amplify/auth'
import API from '@aws-amplify/api'

// federated login works fine now 
// but API module does not have credentials

const region = 'xxx'
const amplifyConfig = {
  Auth: {
    region,
    identityPoolId: 'xxx'
  },
  API: {
    endpoints: [
      {
        name: 'xxx',
        endpoint: 'xxx',
        region
      }
    ]
}

Auth.configure(amplifyConfig.Auth)
API.configure(amplifyConfig.API)

// this is successful!
Auth.federatedLogin(...)
// this fails with a 403!
API.get(...) // works!
```

**Comment by johnomalley** [comment]
After much investigation this appears to be an NPM issue or some other configuration problem.  The api, core, and auth modules are all bringing in their own versions of core, aws-sdk, etc.  Looking at the versions there does not appear to be any reason why NPM would not dedupe the dependencies.  Still looking into it...

![amplify-duplicated-dependencies](https://user-images.githubusercontent.com/933065/55293271-6a108200-53ba-11e9-8298-e0c15620b950.png)

**Comment by johnomalley** [comment]
`npm dedupe` fixed the problem so I suppose this is an npm issue.

**Comment by JustFly1984** [comment]
@johnomalley  More than that, after getting rid of `aws-amplify` and implementing `@aws-amplify/auth` instead, we met an issue, where error handling changed, and we were getting different kind of response. I advise you to try wrong login/password to test `auth`

**Comment by johnomalley** [comment]
@JustFly1984 Thanks for the advice - much appreciated.  Will comment if I learn anything more.

I think the problem was that I had aws-sdk as a separate dependency.  I don't know why that would cause the duplication of modules with the same version but I was unable to reproduce the issue with just the three @aws-amplify deps as depenedencies.
