### ISSUE TITLE
Add support for custom scopes to federated logins

### ISSUE THREAD

**Issue by ceich** [aws-amplify/amplify-js#297]
What is the current behavior?
> Scopes for federated logins are hardcoded:
> Facebook: 'public_profile,email'
> Google: 'profile email openid'
> Amazon: 'profile'

What is the ~~expected~~ desired behavior?
> Allow override of the defaults with new `xxx_scope` keys in the `federated` hash.

I have forked the repo and am willing to add support. Let me know if this would be welcome.

**Comment by powerful23** [comment]
@ceich yeah sure that's a really good enhancement to the library.

**Comment by dcsena** [comment]
Any update on this? Definitely something I would like added

**Comment by stephenhuh** [comment]
if no ones working on this id like to pick it up

**Comment by peetss** [comment]
If anyone has something I can NPM install that allows for this, I would be eternally grateful.

**Comment by undefobj** [comment]
@peetss @stephenhuh @dcsena @ceich we are looking at an enhancement for `Auth.federatedSignIn()` at this time which could potentially address this use case. Please see the RFC here: https://github.com/aws-amplify/amplify-js/issues/2716

I'd be interested in seeing what you expect the overloaded scope experience would look like in a more simplified API. Could you please comment in the RFC?

**Comment by peetss** [comment]
I ended up not using custom scopes as they are quite a pain to get approval for on Facebook in particular.  However, it would still be nice to pass additional scopes in optionally.  Will check out the RFC.

**Comment by undefobj** [comment]
Is this functionality still needed with the latest updates to the CLI supporting the OAuth/Hosted UI (where you can specify scopes in the OAuth config) as well as the library supporting OAuth with `federatedSignIn()` or can the issue be closed?

**Comment by ceich** [comment]
Agree it's ok to close.
