### ISSUE TITLE
React Native google auth without expiration token?

### ISSUE THREAD

**Issue by Scottyaim** [aws-amplify/amplify-js#2970]
** Which Category is your question related to? **
Authentication, Federated Login

** What AWS Services are you utilizing? **
AWS Cognito, DynamoDB, Amplify

** Provide additional details e.g. code snippets **

Hi, I just transistioned from Firebase to AWS/Amplify and I'm trying to implement Google
Authentication in my React Native app. 

I've followed the https://aws-amplify.github.io/docs/js/authentication documentation and I'm trying to combine it with https://github.com/react-native-community/react-native-google-signin
but android google login does not provide a expiration timestamp anymore. 

Is the expiration timestamp required and in that case how do I get a hold of it on android?

```
async signIn() {
        try {
            await GoogleSignin.hasPlayServices();
            const profile = await GoogleSignin.signIn();

            if (profile.idToken !== null && profile.user.email !== null && profile.user.name !== null) {
                let user = {
                    email: profile.user.email,
                    name: profile.user.name
                }

                const credentials = await Auth.federatedSignIn('google', { token: profile.idToken, expires_at: (EXPIRATION_TIMESTAMP)}, user);
                this.props.dispatch(createSession(credentials.identityId));
            }
            else
            {
                Alert.alert('Id token null');
            }
        }
        catch (error) {
            Alert.alert(error);
        }
    }
```

Thanks in advance.

**Comment by elorzafe** [comment]
@Scottyaim, yes `expires_at` is required, Amplify needs this value to refresh the tokens in case you added `refreshToken` callback. https://aws-amplify.github.io/docs/js/authentication#federated-sign-in

You have other alternatives to use google authentication with Cognito HostedUI.  https://aws-amplify.github.io/docs/js/authentication#oauth-and-hosted-ui-in-react-native

I hope this helps

**Comment by Scottyaim** [comment]
@elorzafe Thanks for your quick reply it helped a lot.
How far away is #2716 ?

**Comment by elorzafe** [comment]
@Scottyaim I know the team is working on this right now. Keep looking into that issue for news. I will close this issue but feel free to open a new one in case you have any question/suggestion. 

Thanks for your feedback
