### ISSUE TITLE
Using AWS SAM to test REST API generated using Amplify

### ISSUE THREAD

**Issue by junaidatique** [aws-amplify/amplify-js#2973]
** Which Category is your question related to? **
Trying to test  REST API that uses API gateway generated from aws amplify locally using AWS SAM CLI
** What AWS Services are you utilizing? **
I have generated serverless rest api using `Serverless express function (Integration with Amazon API Gateway)` option. the api works fine when pushed to the cloud. I am trying to use AWS SAM on local to test the api locally. 

I am using simple command `sam local start-api --template API-cloudformation-template.json` in the api folder but I get following error. 
`Error: Template does not have any APIs connected to Lambda functions`
How can I test this api locally using AWS SAM? or any other way where I can test this api locally. 
** Provide additional details e.g. code snippets **

**Comment by elorzafe** [comment]
When you have an endpoint available, you will need to configure amplify manually like this

```
Amplify.configure({
    API: {
        endpoints: [
            {
                name: "LocalAPI",
                endpoint: "https://localhost:3000" // add the endpoint you have after 
            }
            }
        ]
    }
});
```

I am not sure why `sam local` is not working properly, probably you will find more help on their repo https://github.com/awslabs/aws-sam-cli

**Comment by junaidatique** [comment]
I moved to serverless to create the rest api and it was matter of minutes that it was working. Both Amplify and SAM belongs to AWS and there should be better documentation on how to use it.
