### ISSUE TITLE
[Android] Voice recording not working

### ISSUE THREAD

**Issue by anjanaw** [aws-amplify/amplify-js#2976]
**Describe the bug**
I am following the documentation here (https://aws-amplify.github.io/docs/js/interactions) and the voice recording is not working. The record button toggles between a mic and a red dot but nothing seems to be recorded. 

**To Reproduce**
Follow everything here https://aws-amplify.github.io/docs/js/interactions
Build the apk, run on emulator or install on device (both options same issue)

**Expected behavior**
Voice clip is recorded and sent to server.

**Comment by elorzafe** [comment]
@anjanaw thanks for your feedback, I will try to reproduce the problem

**Comment by anjanaw** [comment]
any update on this please?

**Comment by AurelienLW** [comment]
I also need update on this, did you manage to make it work? 
I have a 5/Clientside error. 
The audio is being recorded, the text is in the TextInput placeholder but isn't sent.
