### ISSUE TITLE
All files uploaded using Storage.put are 13 Bytes.

### ISSUE THREAD

**Issue by michaelcuneo** [aws-amplify/amplify-js#2977]
**Describe the bug**
Not sure if this is a bug or something I've done.

All of my images uploaded using Storage.put are 13 bytes.

If I console.log the file I'm sending to Storage.put, it is a real file.

```
File {name: "AdobeStock_75570710.jpeg", lastModified: 1543812797700, lastModifiedDate: Mon Dec 03 2018 15:53:17 GMT+1100 (Australian Eastern Daylight Time), webkitRelativePath: "", size: 8448895, …}
lastModified: 1543812797700
lastModifiedDate: Mon Dec 03 2018 15:53:17 GMT+1100 (Australian Eastern Daylight Time) {}
name: "AdobeStock_75570710.jpeg"
size: 8448895
type: "image/jpeg"
webkitRelativePath: ""
__proto__: File

```

The console.log, of the result from Storage.put is a successful Key, but if I try and load the image up again with a Storage.get it's blank... so I checked my S3 Bucket, and it's full of files that are all exactly 13 bytes.

**Expected behavior**
A week ago, my files were all normal sized files that i could access.

**Comment by elorzafe** [comment]
@michaelcuneo can you add a code snippet for `Storage.put` that you are using.

**Comment by michaelcuneo** [comment]
My mistake. I just made a really stupid error. All fixed now.

**Comment by graylancome** [comment]
@elorzafe what is the error you made? I'm running into the same issue

**Comment by michaelcuneo** [comment]
@graylancome deconstructing the object out into its parts. File name, file data, and mime type. I just had an object deconstructing mistake, the file name was fine, but the file data was undefined.
