### ISSUE TITLE
object HTMLInputElement displays on the text box of reset password form

### ISSUE THREAD

**Issue by hoang-innomizetech** [aws-amplify/amplify-js#2980]
When using the latest version, I noticed that the  reset password form display **[object HTMLInputElement]**

![image](https://user-images.githubusercontent.com/43955692/55381305-05d1f780-554d-11e9-881a-ce05edcaa054.png)

Also, when I try to modify the label of both items on the Sign In form to remove unclickable span element, I got another unexpected issue that the title of the reset password form is changed as well. I expected the form title will display as **Reset your password**. I think we are using the same key for both label and form title. Can we add another key for form title?

![image](https://user-images.githubusercontent.com/43955692/55381392-40d42b00-554d-11e9-94e6-cdae15e5a30a.png)

i18n configuration
```
const dict = {
    'en': {
        'Forgot Password?': ' ',
        'Reset your password': 'Forgot Password? Reset your password.'
    }
};

I18n.setLanguage('en');
I18n.putVocabularies(dict);
```

Package info:
"@angular": "7.2.11",
"aws-amplify": "1.1.23",
"aws-amplify-angular": "2.1.10"

**Comment by jarrettj** [comment]
Hi,

Good day.

I can confirm that as well. 

Regards.

**Comment by elorzafe** [comment]
@hoang-innomizetech @jarrettj thanks for your feedback, we will try to reproduce this and find a fix.

**Comment by jarrettj** [comment]
Cool, thanks man.

**Comment by jarrettj** [comment]
Awesome! Thanks. :)
