### ISSUE TITLE
cors for cognito

### ISSUE THREAD

**Issue by Yaroslav-Zaika** [aws-amplify/amplify-js#2982]
How I can set cors for cognito? Is it possible?

**Comment by elorzafe** [comment]
@Yaroslav-Zaika what is the issue you are trying to solve?

**Comment by Yaroslav-Zaika** [comment]
@elorzafe I have a task to make access to Сognito only for the domain of the client.

**Comment by elorzafe** [comment]
@Yaroslav-Zaika currently this is not supported on Cognito. I will let this marked as feature-request for the service.

**Comment by sammartinez** [comment]
@Yaroslav-Zaika I do want to state that Amplify JS is a pass through to Cognito. Since this is specific to Cognito, please open up a [forum request](https://forums.aws.amazon.com/forum.jspa?forumID=173) with them if this is still a valid use case. Closing this request.
