### ISSUE TITLE
cannot subscribe to hasura graphql, requires websockets

### ISSUE THREAD

**Issue by binarytide** [aws-amplify/amplify-js#2984]
** Which Category is your question related to? **
api/graphql
** What AWS Services are you utilizing? **
graphql
** Provide additional details e.g. code snippets **
when using custom graphql server(hasura) I set `graphql_endpoint` to server and it works for regular queries/mutations etc, but when trying to subscribe I get `subscriptions are not supported over HTTP, use websockets instead` am I missing a config option somewhere?

**Comment by elorzafe** [comment]
@binarytide currently graphql subscriptions are only supported with appsync.

**Comment by strefethen** [comment]
@elorzafe I've been working through the hasura tutorial here:

https://learn.hasura.io/graphql/react/subscriptions/3-create-subscription

...and ran into the above error. 

Would you mind elaborating on your comment above regarding "appsync"? Google yields an AWS AppSync but I'm not familiar with it and there's nothing in the tutorial about it. Is that what you're referring to? Curious where I can learn more about this issue?

The videos in the tutorial "just work" when it comes to subscriptions.

I may be getting ahead of myself here but does this mean subscriptions in hasura generally won't work without using this service?
