### ISSUE TITLE
Amplify integrations triggers `core.js:14597 ERROR Error: Uncaught (in promise): MissingRequiredParameter: Missing required key 'userId' in params`

### ISSUE THREAD

**Issue by diosney** [aws-amplify/amplify-js#2985]
**Describe the bug**
When sending the message using the Angular Amplify integrations component, or directly the `const response = await Interactions.send('chatBot', userInput);` line, it triggers the above error, it seems that parameter `userId` is required by Lex but it don't provide the means to assign it.

When the Network tab is inspected, it shows that a query to Cognito returns the following message:

> {"__type":"ValidationException","message":"1 validation error detected: Value '244767523910' at 'identityPoolId' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\w-]+:[0-9a-f-]+"}

**To Reproduce**
Just follow any of the basic Integration documentation at:

https://aws-amplify.github.io/docs/js/interactions
https://aws-amplify.github.io/docs/js/angular#interactions

**Additional references**

* https://stackoverflow.com/questions/54148545/aws-amplify-missingrequiredparameter-userid-error

**Expected behavior**
If that parameter is required, integrations should provide an input for it both in the UI components and the `send` method.

**Desktop:**
 - OS: Kubuntu 18.04
 - Browser Chrome
 - Version73

**Comment by elorzafe** [comment]
@diosney how are you configuring the library? It seems you dont have an identityPool.

**Comment by diosney** [comment]
@elorzafe Thanks.

That was exactly the issue, sadly I I ended up using the AWS sdk directly :(
