### ISSUE TITLE
How the query limit affects the dynamodb costs

### ISSUE THREAD

**Issue by ialmoqren** [aws-amplify/amplify-js#2986]
** Which Category is your question related to? **
Dynamodb, AppSync
** What AWS Services are you utilizing? **
Amplify
** Provide additional details e.g. code snippets **

If I have a list of 200 items, will there be any difference (in term of costs) if I:
- Limit my query by 10 items and call it 20 times
- Limit my query by 50 items and call it 4 times

Please tell me if what I mean isn't clear.

Thanks a lot for your time

**Comment by elorzafe** [comment]
@ialmoqren you can find more information about AppSync pricing on [this thread](https://forums.aws.amazon.com/thread.jspa?messageID=862404&#862404). Please feel free to ask questions about AWS services on AWS Forums.
