### ISSUE TITLE
Reuse Amplify Authentication for non supported cognito operations.

### ISSUE THREAD

**Issue by damianrr** [aws-amplify/amplify-js#2988]
**Is your feature request related to a problem? Please describe.**
Sometimes I need to do some operations on Cognito that aren't supported by amplify libraries (ex: list users in pool, list groups in pool, etc). For that I could use, for example, code like this: 

```
var params = {
    UserPoolId: aws_exports.aws_user_pools_id
  };
  const AWS = require("aws-sdk");
  AWS.config.update({
    region: aws_exports.aws_cognito_region,
    accessKeyId: "MY ACCESS KEY",
    secretAccessKey: "MY SECRET KEY"
  });
  const cognitoidentityserviceprovider = new AWS.CognitoIdentityServiceProvider();
  return {
    listGroups: function() {
      cognitoidentityserviceprovider.listGroups(params, function(err, data) {
        if (err) console.log(err, err.stack);
        else console.log(data);
      });
    }

```
The problem with that is that I need to hardcode my access key and secret access key. Using a environment variable is not possible since (let me know if I'm wrong here) it would work in local env but once pushed to production won't (frontend code ends up in a S3 bucket and you cannot set env variables there AFAIK).

Any idea on how I could solve this in the meantime?

Thanks!

**Comment by undefobj** [comment]
For calling service interfaces (such as Administrative, non-client Cognito APIs above) you can always use the Amplify credentials passed through to the service interfaces as outlined here: https://aws-amplify.github.io/docs/js/start#step-5-host-your-app (see "AWS SDK Interfaces"). You will need to give the Cognito Roles appropriate IAM conditions to do this as noted in that link.

That being said a better architecture is to perform this action through an endpoint such as API Gateway or AWS AppSync. We're working on that in this RFC: https://github.com/aws-amplify/amplify-cli/issues/766

**Comment by damianrr** [comment]
Cool, I'll look into that. Thanks!
