### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by mezalejandro** [aws-amplify/amplify-js#2990]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Describe the bug**
I have react-native 0.59.3 and aws-amplify/pushnotification ^1.0.20
When I generate release apk I have a error.

**To Reproduce**
1. cd android
2. ./gradlew assembleRelease
node_modules/@aws-amplify/pushnotification/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.

node_modules/@aws-amplify/pushnotification/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.

node_modules/@aws-amplify/pushnotification/android/build/intermediates/res/merged/release/values/values.xml:2724: error: resource android:attr/fontVariationSettings not found.

**Expected behavior**

**Screenshots**
![Screen Shot 2019-04-02 at 10 49 31](https://user-images.githubusercontent.com/568141/55407810-18d8cd80-5535-11e9-98af-01af18d0f984.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X Mojave 10.14.3

**Additional context**
buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"

**Comment by vitalii** [comment]
have exactly the same issue with a similar configuration.
```
    "@aws-amplify/pushnotification": "^1.0.24",
```
```
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 18
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
```
```bash
Execution failed for task ':@aws-amplify_pushnotification:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
/node_modules/@aws-amplify/pushnotification/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
/node_modules/@aws-amplify/pushnotification/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
/node_modules/@aws-amplify/pushnotification/android/build/intermediates/res/merged/release/values/values.xml:2724: error: resource android:attr/fontVariationSettings not found.
/node_modules/@aws-amplify/pushnotification/android/build/intermediates/res/merged/release/values/values.xml:2725: error: resource android:attr/ttcIndex not found.
  error: failed linking references.
```
How it could be fixed? Mb there is some workarounds

```bash
 react-native run-android --variant=release
```
what is basically `./gradlew app:installRelease`
is working fine though...

**Comment by ciguaapp** [comment]
as a workaround: 

- check if you have install the latest version of "amazon-cognito-identity-js"
- then check "../node_modules/amazon-cognito-identity-js/android/build.gradle" file

you should find something like this:

`android {
    compileSdkVersion 28
    buildToolsVersion "28.0.3"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
    }
    lintOptions {
        abortOnError false
    }
}`

if yours is not, change to this one.

try out! Worked for me.

**Comment by nwohaibi** [comment]
try going to
`YOUR_PROJECT/node_modules/@aws-amplify/pushnotification/android/build.gradle`

edit `compileSdkVersion`, `buildToolsVersion`, and `targetSdkVersion` to 

`compileSdkVersion 28`
 `buildToolsVersion "28.0.3"`
 `targetSdkVersion 28`

**Comment by nwohaibi** [comment]
previous solution works to pass build/release, however, final apk will have lots of one-off crashes
```

 FATAL EXCEPTION: main
 Process: com.app, PID: 23638
 java.lang.IllegalAccessError: com.amazonaws.amplify.pushnotification.RNPushNotificationMessagingService
        at dalvik.system.DexFile.defineClassNative(Native Method)
        at dalvik.system.DexFile.defineClass(DexFile.java:226)
        at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
        at dalvik.system.DexPathList.findClass(DexPathList.java:338)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2859)
        at android.app.ActivityThread.-wrap4(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by sammartinez** [comment]
@mezalejandro Im going to close this issue as it seems the workaround was working correctly for people. Please reopen if you are still experiencing this issue

**Comment by santialur** [comment]
This is still not working @sammartinez none of the solutions suggested work

**Comment by santialur** [comment]
`ext {
        googlePlayServicesVersion = "+"
        firebaseVersion = "+"

        buildToolsVersion = "28.0.3"
        compileSdkVersion = 28
        minSdkVersion = 21
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }`

`> Task :@aws-amplify_pushnotification:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':@aws-amplify_pushnotification:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/santialur/dev/surebox-app/node_modules/@aws-amplify/pushnotification/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /Users/santialur/dev/surebox-app/node_modules/@aws-amplify/pushnotification/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /Users/santialur/dev/surebox-app/node_modules/@aws-amplify/pushnotification/android/build/intermediates/res/merged/release/values/values.xml:2750: error: resource android:attr/fontVariationSettings not found.
  /Users/santialur/dev/surebox-app/node_modules/@aws-amplify/pushnotification/android/build/intermediates/res/merged/release/values/values.xml:2751: error: resource android:attr/ttcIndex not found.
  error: failed linking references.`

**Comment by wellmmer** [comment]
@santialur here is happening the same as well

**Comment by mezalejandro** [comment]
My solution:
`subprojects {
    afterEvaluate {project ->
        if (project.hasProperty('android')){
            android {
                compileSdkVersion 28
                buildToolsVersion '28.0.3'
            }
        } 
    }
}`

**Comment by Dr1992** [comment]
This is still not working guys, any solutions ?

**Comment by aloknecessary** [comment]
facing the same issue, any help ?? 
RN: 0.62, 
@aws-amplify/push_notifications: ^3.1..
