### ISSUE TITLE
Allow theming for select elements

### ISSUE THREAD

**Issue by jsardid** [aws-amplify/amplify-js#2994]
**Is your feature request related to a problem? Please describe.**

Input elements can be customized using the "input" selector and passing as part of a theme object. The same way, I would expect select elements to be able to be customized, in order to avoid this kind of inconsistency: 
![image](https://user-images.githubusercontent.com/7370399/55485877-9979f580-562b-11e9-80ba-ded703719f3d.png)

**Describe the solution you'd like**

Add an inputSelect selector to the theme system, which should apply to the select elements

**Describe alternatives you've considered**

As an alternative, I would have to implement my own forms.

**Comment by jordanranz** [comment]
FYI, we have started an RFC discussion for a proposed Amplify UI Component refactor to increase customizability and flexibility for our components. Please feel free to add any additional comments to the following issue:

https://github.com/aws-amplify/amplify-js/issues/3279

**Comment by ashika01** [comment]
Closing this feature request. Since the new UI components handles theming through CSS custom properties. For more info - https://docs.amplify.aws/ui/customization/theming/q/framework/react

If there are improvement / bugs or suggestions for the new UI component feel to open up a new issue.
