### ISSUE TITLE
amplify-authenticator [hide] does not work in case of angular ui

### ISSUE THREAD

**Issue by vjindalaurea** [aws-amplify/amplify-js#2995]
I have specified :

     <amplify-authenticator [hide]="['SignUp', 'ConfirmSignUp', 'ForgotPassword', 'RequireNewPassword']"></amplify-authenticator>

in angular code , but still create account , forget password does not get hidden.

![image](https://user-images.githubusercontent.com/25425699/55491307-e1604300-5652-11e9-8eee-de1005fcff16.png)

**Comment by sammartinez** [comment]
@vjindalaurea, 

#3173 does resolve this issue. Can you please update to the latest version of aws amplify angular with:
```
npm install aws-amplify-angular@latest
```

Closing issue, please re-open if there are any further concerns or questions
