### ISSUE TITLE
Aws appsync subscriptions are slow

### ISSUE THREAD

**Issue by achutkiran** [aws-amplify/amplify-js#2996]
** Which Category is your question related to? **
Aws amplify v1.1.8

** What AWS Services are you utilizing? **
Aws Appsync api

** Provide additional details e.g. code snippets **
The subscription onUpdate, onCreate is taking 15 sec to fire up

**Comment by elorzafe** [comment]
@achutkiran can you give more details according to the region you have configured AppSync and from where you are calling the subscription. How are you testing it? Where is the mutation sent from, what data-source are you using?

**Comment by achutkiran** [comment]
AppSync region: N.virginia
I am using Amplify Appsync graphql api. and i used codegen to create mutations and subscriptions

**Comment by elorzafe** [comment]
You used amplify-cli to create the AppSync api by doing `amplify api add`?

**Comment by achutkiran** [comment]
Yup

**Comment by elorzafe** [comment]
@achutkiran more questions
Do you have latency issues for queries and mutations as well? 
Are you uploading larger files while doing the mutations that trigger the subscriptions?

**Comment by achutkiran** [comment]
Queries and mutations are quick only subscriptions are slow

**Comment by elorzafe** [comment]
@achutkiran I created this react-app and subscriptions work very fast.
- First I created an AppSync api from the console using **Event App** from sample project section.
- Then I downloaded `aws-exports.js` config file from **Integrate with your app/JavaScript** section and paste it next to my `App.js` file.
App.js
```jsx
import React, { Component } from 'react';
import './App.css';
import Amplify, { API } from 'aws-amplify';
import appsyncConfig from './aws-exports';

Amplify.configure(appsyncConfig);

const listEvents = `query ListEvents {
  listEvents {
    items {
      id
      name
    }
  }
}`;

const subscription = `subscription toCommentEvent($eventId:String!) {
  subscribeToEventComments(eventId:$eventId) {
    commentId
    content
    createdAt
  }
}`;

const addEvent = `mutation CreateEvent {
  createEvent(
    name: "My First Event"
    when: "Today"
    where: "My House"
    description: "Very first event"
  ) {
    id
    name
  }
}`;

const addComment = `mutation comment($eventId:ID!) {
  commentOnEvent(eventId: $eventId, 
    content:"test", 
    createdAt: "1554846224766") {
    eventId
    commentId
    content
    createdAt
  }
}`

class App extends Component {


  async componentDidMount() {
    await this.listEvents();

    const id = prompt("Which event id to subscribe for comments?");
    API.graphql({ query: subscription, variables: { eventId: id } }).subscribe({
      next: ({ value: { data } }) => alert(JSON.stringify(data, null, 4))
    })
  }

  addEvent() {
    API.graphql({ query: addEvent });
  }
  addComment() {
    const id = prompt("Which event id to add a comment?");
    API.graphql({ query: addComment, variables: { eventId: id } });
  }
  async listEvents() {
    const data = await API.graphql({ query: listEvents })
    console.log(JSON.stringify(data, null, 2));
  }

  render() {
    return (
      <div className="App">
        <button onClick={this.addEvent}>add event</button>
        <button onClick={this.listEvents}>list events</button>
        <button onClick={this.addComment}>add comment</button>
      </div>
    );
  }
}

export default App;

```

After adding the first event you can copy/paste the eventId from the console, then you can see the subscription working by adding a comment to with the same id as you subscribed first. I tested several times and always I got fast responses for the subscriptions.

I hope this works better for you, if you add a code snippet will be much easier to debug.

**Comment by achutkiran** [comment]
I used amplify-angular and used subscription api created by using codegen.
