### ISSUE TITLE
newPasswordRequired prompt versus form on a new page

### ISSUE THREAD

**Issue by VinayakVenkataraman** [aws-amplify/amplify-js#3014]
I am using AWS Cognito with a User Pool configured such that only an administrator can create users. As such, when a new user is created, the administrator assigns a temporary password and the user is configured into the FORCE_CHANGE_PASSWORD status requiring the user to change their password after the first login attempt.

I have successfully implemented this workflow based on the documentation available in AWS repository and github. In particular, I am using the exact representation of the authenticateuser example given in this link:
https://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-identity-user-pools-javascript-example-authenticating-admin-created-user.html

However, my currently implementation makes use of the browser prompt as described in Case 12 in the following link to grab the new password from the user:
https://github.com/aws-amplify/amplify-js/tree/master/packages/amazon-cognito-identity-js

The problem with this approach is that the browser prompt input cannot unfortunately be masked and the password is therefore out there for everyone to see. The next obvious choice is to redirect the user to a change password page, but that will reset the context and I will no longer have the parameters sent to the callback function (by that I mean I will have to recreate the arguments userAttributes, requiredAttributes being passed to the newPasswordRequired callback handler), something that is nicely being handled for me.

A solution comes to mind that in such a case, I can redirect to the reset password page while passing the username and password as parameters and repeat the login process all over again, then as the newPassword callback is called, pass the password entered by the user to complete the process.

Is this really the best way to handle this workflow or is there a better method to this madness I wonder?

**Comment by VinayakVenkataraman** [comment]
Appears Case 12 has been fixed. However still does not say how to implement this fix for Case 23, the case of FORCE_CHANGE_PASSWORD. If I redirect the user to another page to enter their new password or even display a form on the same login page, I lose the context in which I just authenticated the user.

Ideally, the authenticateUser function should also return a session or, as is the case with the InitiateAuth workflow in the following link, return a userContext object which can be directly used with the completeNewPasswordChallenge call in any subsequent workflow stage.
https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html

**Comment by elorzafe** [comment]
@VinayakVenkataraman thanks for your feedback, can you create a new issue, for case 23 you mention. This way we can keep track issue better.

Thanks again

**Comment by VinayakVenkataraman** [comment]
Yes Certainly.

**Comment by VinayakVenkataraman** [comment]
Opened Case #3043 for Case 23.
