### ISSUE TITLE
image showing for different user

### ISSUE THREAD

**Issue by totaland** [aws-amplify/amplify-js#3016]
** Which Category is your question related to? **
Image

** What AWS Services are you utilizing? **
Cognito/amplify /Storage
** Provide additional details e.g. code snippets **
![image](https://user-images.githubusercontent.com/36496259/55616571-6ecba080-57d5-11e9-954d-e46b0c5e0f01.png)
![image](https://user-images.githubusercontent.com/36496259/55616598-8145da00-57d5-11e9-9759-17050433bc09.png)
![image](https://user-images.githubusercontent.com/36496259/55616619-91f65000-57d5-11e9-8465-4ff1a8c69a74.png)
![image](https://user-images.githubusercontent.com/36496259/55616677-ad615b00-57d5-11e9-97fe-77467b5b9162.png)

So when I log in using userA the image appear like so and when I try to log in using userB the userB will have the same image with userA. How can I make sure userA and userB not seeing the same profile image? I try to use S3Album or S3Image before. S3Album work but I can't control the image size. S3Image not working even though I set level as private. Different user seeing same image. Any help or guidance would be much appreciated

**Comment by totaland** [comment]
The profile picture that you see is using Avatar component from material UI. The issue when using that is everyone seeing the same profile image until someone uploads a new one. Which is not what I one. I want a different user to be able to upload their own profile picture as FB does.

**Comment by totaland** [comment]
https://gist.github.com/totaland/fc8bfdb89cdc80fb310ac96aeb30dc0e 
for more info please see my gist

**Comment by totaland** [comment]
I made it work now using Storage to push the image in S3 then create picture table (DynamoDb) then map that with the user then query back from DynamoDB. I can close this one if you like. But if it can work only with Storage that would be nice too.

**Comment by totaland** [comment]
I made it work now using the DynamoDB and graphql as the front. I store user picture data and user information in the DynamoDb then query back that information. It still will be nice to just use Storage to get it.

**Comment by sammartinez** [comment]
@totaland I'll go ahead and close this as you were able to solve it using DynamoDB and GraphQL.
