### ISSUE TITLE
withAuthenticator HOC not sending signup code for new users 

### ISSUE THREAD

**Issue by YaswanthC** [aws-amplify/amplify-js#3019]
Hi,

I am trying to setup the basic authentication using AMPLIFY by using `withAuthenticator` HOC component in my basic react app. I am using amplify cli for pushing the authentication part. I wrapped my App component in `withAuthenticator`  using [amplify documentation](https://aws-amplify.github.io/docs/js/authentication#using-auth-components-in-react--react-native)  and even followed the exact steps as explained in [aws-tech-talks youtube video](https://www.youtube.com/watch?v=uiTQL7Ne8rY). But when i try creating a new account (means Signup) i am not receiving the code in my mobile . I doubled checked my phonenumber and the extension code, they are good. And another weird thing is, when i submitted information in signup page i can see the information is reflected in cognito users page with state as `UNCONFIRMED` . I manually confirmed the user with the help of  `confirmuser` button. After confirming the user it is allowing me to login and after i logged in , it asked for my `Account Recovery Option`(means email or mobile) when i clicked on mobile , it sent me a code which means my phone number is correct.

**Steps To Reproduce**

1. create-react-app myreact
2. amplify init --> with necessary account creds
3. amplify add auth --> went with default one
4. amplify push 
5. yarn add aws-amplify-react-native aws-amplify 
6. configured App.js file with necessary configuration
7. yarn start

This is my App.js file

```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import { withAuthenticator } from 'aws-amplify-react';
import Amplify from 'aws-amplify';
import aws_exports from './aws-exports'; 
Amplify.configure(aws_exports);

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1>
            Welcome To <code>Amplify♥♥</code> 
          </h1>
        </header>
      </div>
    );
  }
}

export default withAuthenticator(App, true);

```

Am i missing anything?

Any help is appreciated
Thanks

**Comment by YaswanthC** [comment]
The above scenario worked perfectly today but it didnt worked as expected on the day i posted this issue( 3 days ago) . Thats why i created this thread.

Since it is working now i am closing this.

Thanks

**Comment by elorzafe** [comment]
@YaswanthC sns has a limit for messages per month, maybe that is why you didnt get those messages.  

According to [this guide](https://aws.amazon.com/premiumsupport/knowledge-center/sns-sms-spending-limit-increase/)
Amazon SNS has a restriction on the number of mobile text messages that users can send using the service. By default, this limit is set to 1.00 USD, which prevents abuse or misuse of the service by spammers, scammers, and phishers. There are a few prerequisites that must be met when you request a limit increase.
