### ISSUE TITLE
Custom authData returned when using withAuthenticator and a PostAuthentication Cognito trigger

### ISSUE THREAD

**Issue by tbehunin** [aws-amplify/amplify-js#3020]
I'm leveraging the `withAuthenticator` React HOC for my authentication workflow. I've also configured my Cognito User Pool to have a `PostAuthentication` trigger to invoke a simple lambda that would generate a 3rd party API key. Currently, my lambda function looks like this:

```
module.exports.generateToken = async (event, context) => {
    event.response.hello = 'world';
    context.done(null, event);
};
```

My hope was that if I assigned custom properties to the `response` object (as shown above), those props would flow through all the way back to the `withAuthenticator` component - which then maps that data to the `authData` object and ultimately gets passed down to the wrapped `App` component. However, it looks like the custom data being returned isn't being mapped to the authData object. Is there a way to update the response via Cognito triggers before getting returned to the client?

**Comment by haverchuck** [comment]
@tbehunin Cognito does not support this functionality at the moment.  If needed, I would suggest posting a feature request in AWS forum's Cognito board.  I'm closing this issue for now, but if we've misunderstood this question please feel free to open another with clarification.  Thanks.
