### ISSUE TITLE
Android Push notification error

### ISSUE THREAD

**Issue by mezalejandro** [aws-amplify/amplify-js#3022]
**Describe the bug**
When execute react-native run-android in the console show :
@aws-amplify\pushnotification\android\libs\aws-android-sdk-core-2.6.13.jar: D8: Type `org.apache.commons.logging.LogFactory` was not found, it is required for default or static interface methods desugaring of `void com.amazonaws.metrics.AwsSdkMetrics.<clinit>()`

node_modules\@aws-amplify\pushnotification\android\libs\aws-android-sdk-cognito-2.6.13.jar: D8: Type `org.apache.commons.logging.LogFactory` was not found, it is required for default or static interface methods desugaring of `void com.amazonaws.mobileconnectors.cognito.CognitoSyncManager.<clinit>()`

node_modules\@aws-amplify\pushnotification\android\libs\aws-android-sdk-core-2.6.13.jar: D8: Type `org.apache.http.impl.client.DefaultRedirectHandler` was not found, it is required for default or static interface methods desugaring of `boolean com.amazonaws.http.HttpClientFactory$LocationHeaderNotRequiredRedirectHandler.isRedirectRequested(org.apache.http.HttpResponse, org.apache.http.protocol.HttpContext)`

node_modules\@aws-amplify\pushnotification\android\libs\aws-android-sdk-core-2.6.13.jar: D8: Type `org.apache.http.conn.scheme.PlainSocketFactory` was not found, it is required for default or static interface methods desugaring of `org.apache.http.client.HttpClient com.amazonaws.http.HttpClientFactory.createHttpClient(com.amazonaws.ClientConfiguration)`

**To Reproduce**
1. react-native run-android
2. See error

**Desktop (please complete the following information):**
 - OS: Windows
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
      Memory: 3.62 GB / 15.94 GB
    Binaries:
      npm: 6.4.1 - C:\Users\ameza\AppData\Roaming\npm\npm.CMD

**Additional context**
Android build.gradle
buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesAuthVersion = "16.0.1"

**Comment by powerful23** [comment]
Since those unused dependencies have been removed, I am going to close the issue. Feel free to reopen if you still have this issue.
