### ISSUE TITLE
_vm.orderBy is not a function in SignUp vue component

### ISSUE THREAD

**Issue by morgler** [aws-amplify/amplify-js#3032]
**Describe the bug**
I use the amplify-vue components in a Quasar web application. My "Auth" page component is pretty simple, just containing the amplify-authenticator component. The "SignIn" component displays fine and works as expected. But if I click on "Create account" to be taken to the "SignUp" component, I always get an error "_vm.orderBy is not a function" from the line https://github.com/aws-amplify/amplify-js/blob/ea93448d10dfdf2d59c9f446eda13e73ed9424b5/packages/aws-amplify-vue/src/components/authenticator/SignUp.vue#L19 .

**To Reproduce**
1. Create basic vue app (I don't know if this is limited to Quasar apps)
2. Add amplify and amplify-vue
3. Add amplify auth via amplify CLI
4. Create vue component with just the amplify-authenticator component
5. Go to page and click on "Create account"
6. See JS error "_vm.orderBy is not a function"

**Expected behavior**
The SignUp component should become visible without errors.

**Desktop (please complete the following information):**
 - OS: MacOs 10.14.1
 - Browser Chrome
 - "aws-amplify": "^1.1.24",
 - "aws-amplify-vue": "^0.2.9",

To me this looks like a dependency is missing, that would provide the "orderBy" function. But I don't know, where "orderBy" is supposed to come from.

**Comment by alebiavati** [comment]
Apparently `orderBy` used to be defined in a previous version of Vue. Now their docs shows that we should use Lodash instead: https://vuejs.org/v2/guide/migration.html#Replacing-the-orderBy-Filter

Which version of Vue are you using?

In case you wanted to submit a PR for this, we could definitely add this module:
https://www.npmjs.com/package/lodash.orderby

**Comment by morgler** [comment]
Thanks! Sounds like that could be it. I'm on Vue 2.9.6. 

I'll see if I can create a PR for this – just don't have much spare time to set up the vue dev environment in the near future. On my software I simply fell back to using the Amplify API directly.
