### ISSUE TITLE
S3Album 403 Forbidden Error -- React Component

### ISSUE THREAD

**Issue by brettbot7** [aws-amplify/amplify-js#3034]
** Which Category is your question related to? **
S3Album component for AWS-Amplify-React.

** What AWS Services are you utilizing? **
AWS Amplify with Storage/S3 and Auth/Cognito.

** Provide additional details e.g. code snippets **
I have no problem getting images from a private bucket using Storage.get() and the S3Image component; however, I keep receiving a 403 Forbidden error for S3Album. 

I have CORS and the bucket policy set up according to the Amplify docs. 

Here's the issue:

```
import React, { Component } from 'react';
import { Storage } from 'aws-amplify';
import { S3Album, S3Image } from 'aws-amplify-react';

export default class Post extends Component {
  state = {
    imageKey: '5c23fbae-6976-4208-af83-2a6b6966b3ed',
    imageUrl: '',
    path: ''
  };

  componentDidMount() {
    Storage.get(this.state.imageKey, { level: 'private' })
      .then(result => this.setState({ imageUrl: result }))
      .catch(err => console.log(err));
  }

  render() {
    const { imageUrl, imageKey, path } = this.state;
    return (
      <>
        <img src={imageUrl} alt="test" />
        <S3Image level="private" imgKey={imageKey} />
        <S3Album level="private" path={path} />
      </>
    );
  }
}
```
Please note that an image is rendered for the <img/> and <S3Image/>, but nothing shows for the <S3Album/> and I receive the following error from the debugger:

![image](https://user-images.githubusercontent.com/23198890/55674249-f66de980-587f-11e9-83e3-ed84a574f837.png)

Could you provide some guidance on where I may be going wrong?

Thank you!!

**Comment by ajhool** [comment]
Would you mind posting your Bucket Policy just to double-check it, please?
