### ISSUE TITLE
Im using AWS amplify (auth and api) on Nextjs.

### ISSUE THREAD

**Issue by anarerdene** [aws-amplify/amplify-js#3037]
AWS AppSync based on Apollo. So it means i don't need Apollo client on my Next'js project ?.
I'm really confusing with Apollo or without Apollo. Right now im using like this image.

`import App, {Container} from 'next/app';
import React, {Component} from 'react';
import {ApolloProvider, compose} from 'react-apollo';
import Link from 'next/link';
import Head from 'next/head';

// AWS Appsync Config
import AWSAppSyncClient from 'aws-appsync';
import {Rehydrated} from 'aws-appsync-react';
import Amplify, {Auth} from 'aws-amplify';
import config from '../src/aws-exports';

const client = new AWSAppSyncClient({
  url: config.aws_appsync_graphqlEndpoint,
  region: config.aws_project_region,
  auth: {
    type: config.aws_appsync_authenticationType,
    jwtToken: async () => (await Auth.currentSession()).getIdToken().getJwtToken()
  }
});

Auth.currentCredentials()
  .then(d => console.log('data: ', d))
  .catch(e => console.log('error: ', e));

// App Layout
class MyApp extends App {
  static async getInitialProps({Component, router, ctx}) {
    let pageProps = {};

    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx);
    }

    return {pageProps};
  }

  render() {
    const {Component, pageProps} = this.props;

    return (
      <Container>
        <Head>
          <meta charSet="utf-8" />
          <title>Amu Nutrition. Хүнсээр анагаах соёлыг дэлхий дахинд түгээнэ.</title>
          <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        </Head>

        <ApolloProvider client={client}>
          <Component {...pageProps} />
        </ApolloProvider>
      </Container>
    );
  }
}

export default MyApp;
`

**Comment by ericclemmons** [comment]
Keeping this open to track with #5435
