### ISSUE TITLE
SignIn Error: 1 validation error detected: Value null at 'deviceKey' failed to satisfy constraint: Member must not be null

### ISSUE THREAD

**Issue by JustFly1984** [aws-amplify/amplify-js#3040]
I have several users in my app, and I'm getting this error while trying to login in chrome canary 75 with most of my app accounts.

I can login successfully from default chrome 73 to all of my users. also can login from Safari browser

The worst thing that my other co-workers experiencing the same issue in chrome 73 on linux, he can't login in some of accounts, but can login in others. This inconsistency creeping me out.

**Comment by JustFly1984** [comment]
PS we are using @aws-amplify/auth@1.2.20

**Comment by JustFly1984** [comment]
My co-worker tried to login from Firefox on linux and had a success, but in chrome73 it failed with same `SignIn Error: 1 validation error detected: Value null at 'deviceKey' failed to satisfy constraint: Member must not be null` response

**Comment by JustFly1984** [comment]
The issue has been solved by clearing cookies and cache in troubled browsers. I can't understand why it happened.

**Comment by JustFly1984** [comment]
This issue definitely related to localStorage. I had it reproduced on my local machine, and clearing up localstorage did helped.

There is 3 records left by Cognito in LocaStorage after logout for each user. I think it could cause an issue.

**Comment by JustFly1984** [comment]
I have it reproduced several times. The issue persists. Sometimes I can't login in some of the accounts because of broken localStorage user record or some issues with parsing that record.

**Comment by JustFly1984** [comment]
I found the reason of an issue, this happens only if previous user hasn't been logged out correctly only. Trying to work around.

**Comment by khizarbajwa007** [comment]
{"1 validation error detected: Value null at 'streamingDistributionConfig.s3Origin.originAccessIdentity' failed to satisfy constraint: Member must not be null"}
Here I'm also getting same thing

**Comment by prateek-singh-wcar** [comment]
You may need to specify AuthorizationType: NONE , for your resource properties.

**Comment by ioannist** [comment]
> My co-worker tried to login from Firefox on linux and had a success, but in chrome73 it failed with same `SignIn Error: 1 validation error detected: Value null at 'deviceKey' failed to satisfy constraint: Member must not be null` response

You have to populate the device key by calling
`cognitoUser.getCachedDeviceKeyAndPassword()`

see #1355
