### ISSUE TITLE
 Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

### ISSUE THREAD

**Issue by inh556** [aws-amplify/amplify-js#3041]
**Describe the bug**
I am using Amplify in a React-Native project. After signing in with Facebook or Google, it will show this warning. I have removed the listener to avoid memory leaks. And I also have tried to add a set of "_isMounted" states as some of the instructions say, but either of them worked. 

**To Reproduce**
Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/22806630/55746777-7cf50900-59ef-11e9-8435-757341e86e56.png)

**Sample code**
![image](https://user-images.githubusercontent.com/22806630/55747370-f6d9c200-59f0-11e9-9ca0-777123f758f0.png)

**Comment by alebiavati** [comment]
Hi @inh556,

`HUB.remove` requires the original listener function to be passed as the second argument.

Have you tried modifying your code like this:

```js
class SignInScreen extends React.Component {

  onAuthChange = (data) => {
    // ...
  }

  componentDidMount() {
    Hub.listen('auth', this.onAuthChange);
  }

  componentWillUnmount() {
    Hub.remove('auth', this.onAuthChange);
  }
}
```

**Comment by inh556** [comment]
![image](https://user-images.githubusercontent.com/22806630/55915016-71dfdb80-5b9d-11e9-96c0-9256cacbb0bf.png)

@alebiavati Hi, thanks for your replay. I just refactored my code like the sample you posted, cleaned cache, and restarted my app,  but it still shows the warning. 
It actually happened in line 44 where I navigated the route to AuthLoading screen.

**Comment by alebiavati** [comment]
Hi @inh556, thanks! Looks like the WithOAuth component is setting its state without checking if it has been unmounted here:

https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react-native/src/Auth/withOAuth.js#L72

Let me know if you want to submit a PR to add `_isMounted` to that component.

**Comment by inh556** [comment]
@alebiavati I would like to open a PR. This will be my first PR 😊

**Comment by inh556** [comment]
@alebiavati I have submitted a PR. #3076 Please check it out. Thanks.

**Comment by amin79** [comment]
@alebiavati I also get the same error when try to login with 'withOAuth'. Is there any solution for that?

**Comment by zilpe786** [comment]
@alebiavati I'm getting the same error using withAuthenticator(), and I'm on the latest version. The use case is the same as in the Amplify Docs.
