### ISSUE TITLE
Double Verification in case of using newPassword Force Change with an Input Form instead of Prompt

### ISSUE THREAD

**Issue by VinayakVenkataraman** [aws-amplify/amplify-js#3043]
In Relation to Issue #3014, the implementation is extended to Case 23.

In brief, the case pertains to Admin created users, where the users are required to reset their passwords after the first successful login with the temporary password. My particular implementation uses the newPasswordRequired implementation provided here in exactly the same form and works splendidly:
https://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-identity-user-pools-javascript-example-authenticating-admin-created-user.html

The problem however comes when asking the user for a new password to reset. The example case here uses a prompt to grab this information (described in Case 12 actually, but the doc above recommends the same workflow for Case 23 also).
https://github.com/aws-amplify/amplify-js/tree/master/packages/amazon-cognito-identity-js

Now, since the browser prompt input cannot be masked, it is not a very good method to pull user secrets. Unfortunately, if I redirect the user to a Reset Password page, I lose the context returned by the authenticateuser call in the previous page.

The solution will then have to be to re-authenticate in the reset password page, retrieve the context again and then use the context to reset the password.

The problem with this approach is that the user is authenticated twice in the same workflow, which besides increasing redundancy in the process, I assume may also increase costs, given how a KMS request may be issued each time an authentication is requested.

Would it therefore be somehow possible to implement a session return similar to the case of InitiateAuth as described in this document:
https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html

This workflow returns a session string as described in the response syntax which can be subsequently used to identify the challenge case and not require authenticating a user for a second time in the same workflow.

**Comment by elorzafe** [comment]
@VinayakVenkataraman thanks for your feedback, I updated the docs with your suggesstions.

I will close the issue for now, but feel free to create a new one if you still have any concerns.

Thanks again!
