### ISSUE TITLE
Forgot Password? text should be clickable

### ISSUE THREAD

**Issue by hoang-innomizetech** [aws-amplify/amplify-js#3046]
I have mentioned this issue on #2980. However, I think raising a separate issue will be easier for tracking

We should add a click event to the **Forgot Password?** text on the sign in form like **Reset your password** text. Per our user perspective, they have reported an issue, so I think we should make this change. 

I tried to make this working by removing the forgot password text using i18n, however, I encounter another issue on the Reset password form (incorrect form title). We are using the same key for both text and form title. I would be better if we use separated keys

**Comment by jordanranz** [comment]
@hoang-innomizetech, we are working on a UI refactor that will allow more granular customization for these UI components. I'll add this enhancement to our UI refactor milestone.

**Comment by hoang-innomizetech** [comment]
@jordanranz  I followed the milestone and I cannot see any update, do you have any ETA for UI Component Refactor milestone?

**Comment by jordanranz** [comment]
Hey @hoang-innomizetech, I have referenced this issue in the RFC. Please feel free to add any additional comments to the following proposal:

https://github.com/aws-amplify/amplify-js/issues/3279

**Comment by DeniseJames** [comment]
Any updates on this issue? When using the 'reset password' link the default username is displayed:

[object HTMLInputElement] instead a blank or username

**Comment by hoang-innomizetech** [comment]
Anyone can help to fix this issue?

**Comment by tannerabread** [comment]
This should be possible now as shown [here](https://ui.docs.amplify.aws/angular/connected-components/authenticator/configuration#initial-state). Closing this issue as resolved.
