### ISSUE TITLE
Federated Identities - User Data Missing (Dataset not found) 

### ISSUE THREAD

**Issue by lucaspelloni2** [aws-amplify/amplify-js#3048]
**Which Category is your question related to?**
The identity pool works fine. Users can sign in into the app using either facebook or google (everything has been configured with the amplify CLI). 
However, even if I see in the dashboard that there are new federated identities, I am not able to retrieve their data (dataset is always empty). 

![image](https://user-images.githubusercontent.com/17781533/55797138-f2360c00-5acb-11e9-9618-d2894dbab761.png)

On the other hand, with ```Auth.currentAuthenticatedUser()``` in my app, each client is able to access its user data. 

**What AWS Services are you utilizing?**
amplify authentication (federated sign in) 

**Desired Behaviour**
Be able to retrieve the federated identity data (like the email address) in the AWS console.

**Comment by lucaspelloni2** [comment]
any news here?

**Comment by undefobj** [comment]
@lucaspelloni2 When you use Amplify's Auth methods like `currentAuthenticatedUser()` to retrieve attributes they are stored in Cognito User Pools, not Identity Pools. The dataset feature that you are referring to in Identity Pools isn't supported in Amplify. You should use User Attributes stored in User Pools and if you need syncing features per the [Cognito Documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-sync.html) on Sync you should leverage AppSync.

**Comment by lucaspelloni2** [comment]
@undefobj thanks for the answer! :)

**Comment by jordanranz** [comment]
@lucaspelloni2, is this safe to close?

**Comment by lucaspelloni2** [comment]
Yes thanks :)
