### ISSUE TITLE
nextToken Handling

### ISSUE THREAD

**Issue by lroellin** [aws-amplify/amplify-js#3049]
** Which Category is your question related to? **

AppSync SDK

** What AWS Services are you utilizing? **

Amplify, AppSync

** Provide additional details e.g. code snippets **

We're using the AppSync SDK as documented here: https://aws-amplify.github.io/docs/js/api#aws-appsync-sdk

We're using queries started like this:

```js
appSyncClient
        .query({
          query: gql(getBlog)
        })
```

The problem is that we're not getting all data. This is *not* specific to list queries (#2728), it also happens when getting a single entity that has a list of another entity attached (e.g., get a blog with all its posts).

In our application, it is not an issue if ALL posts (in the example) are received at once. We do not want to use pagination and would like to get everything at once.

How can we skip pagination and use AppSync to get everything?

**Comment by elorzafe** [comment]
@lroellin can you share the schema you are using, Check out [here](https://docs.aws.amazon.com/appsync/latest/devguide/designing-your-schema.html#advanced-relations-and-pagination) in that case you can set the `limit` to a larger number to get more data.

**Comment by lroellin** [comment]
Hmm, I think the license doesn't allow public sharing, I think it suffices to say it's the same conceptually as the Blog schema usually used in docs :) 

https://aws-amplify.github.io/docs/cli/graphql#quick-start

I did see that these parameters (limit, nexttoken) etc. are automatically generated on list queries. But if I have the GetBlog query, how can I set the limit of posts I get? Simply adding a `limit` setting, like `filter` is set? (here, https://aws-amplify.github.io/docs/cli/graphql#quick-start) 

If so, can this be done automatically when generating the queries, or do I have to manually edit the queries from then on?

**Comment by elorzafe** [comment]
@lroellin you can change the default limit value on the request mapping template or set that as you mention as another parameter on the query next to filter.

**Comment by lroellin** [comment]
Could you point me to the default limit value? I've searched for '10' (seems to be the default) in my code base, but didn't find it...

**Comment by wizawuza** [comment]
It's in the VTL Resolvers. Look in the following directory in your project:
/amplify/backend/api/_your GraphQL API name_/build/resolvers/
Then look up any of the files that start with Query.list*.req.vtl

In there you should see something like this:
```
#set( $limit = $util.defaultIfNull($context.args.limit, 10) )
{
  "version": "2017-02-28",
  "operation": "Scan",
  "filter":   #if( $context.args.filter )
$util.transform.toDynamoDBFilterExpression($ctx.args.filter)
  #else
null
  #end,
  "limit": $limit,
  "nextToken":   #if( $context.args.nextToken )
"$context.args.nextToken"
  #else
null
  #end
}
```
Note that first line. It's basically saying, if no argument named limit is given, default limit to 10.

**Comment by wizawuza** [comment]
Also note that you don't want to overwrite that file as it'll be overwritten by the next time you amplify push/etc. Instead you want to copy it to the /amplify/backend/api/_your GraphQL API name_/resolvers/ directory (note the lack of the 'build' directory). That's where you put custom resolvers.

**Comment by lroellin** [comment]
Thanks a lot! Will try it out and report back!

**Comment by lroellin** [comment]
Ok, I have found the generated file. If I copy it over to the custom resolvers, how do I make sure that my queries are using the custom resolver (with the higher limit) and not the default resolvers?

**Comment by haverchuck** [comment]
@lroellin The [CLI docs](https://aws-amplify.github.io/docs/cli/graphql#api-category-project-structure) note the project structure, including the resolvers directory.  The resolvers directory can include two files for each operation (query, mutation, etc).  One file ('req') is the request mapping template, the other ('res') is the response mapping.  You can add these files and then push.

**Comment by lroellin** [comment]
Thx for the help! I will try it out once I find the time. I'll close the issue for now.

**Comment by lroellin** [comment]
For reference: setting the value to ~2 billions (2147483647) worked as a workaround
