### ISSUE TITLE
Angular authenticator sign in fill login form

### ISSUE THREAD

**Issue by RomaricDel** [aws-amplify/amplify-js#3050]
Hello,
Currently when using the authenticator component for angular the input fields **username** and **password** don't have any name attribute. This implies that the form can't be filled automatically with username and password, and chrome won't ask if we want to save the password.

I've figured out a workaround by adding manually the name attribute afterwards like this
```
ngAfterViewInit() {
  let usernameInput = Array.from(document.getElementsByClassName("amplify-signin-username")[0].children).find(child => child.tagName === "INPUT");
  usernameInput.setAttribute('name', 'username');
  let passwordInput = Array.from(document.getElementsByClassName("amplify-signin-password")[0].children).find(child => child.tagName === "INPUT");
  passwordInput.setAttribute('name', 'password');
}
```

I think it would be nice if possible to add the name attributes to all forms in the authenticator component.

Thank you

**Comment by jordanranz** [comment]
FYI, we have started an RFC discussion for a proposed Amplify UI Component refactor to increase customizability and flexibility for our components. Please feel free to add any additional comments to the following issue:

#3279

**Comment by cwomack** [comment]
Closing this out due to the recently updated docs around using the Angular Authenticator that can be found here: https://ui.docs.amplify.aws/angular/connected-components/authenticator.
