### ISSUE TITLE
How to avoid error "Invalid state in OAuth flow"?

### ISSUE THREAD

**Issue by danludwig** [aws-amplify/amplify-js#3054]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Cognito User Pools, AWS Amplify

** Provide additional details e.g. code snippets **

Hi AWS Amplify team! Just today we started seeing a new error in fresh npm installs of `@aws-amplify/auth`:

> Invalid state in OAuth flow

Which we narrowed down to this line of code that looks like it was published to npm about a day ago: https://github.com/aws-amplify/amplify-js/blob/76cde598c30ee8049798e5988261db9165cc775e/packages/auth/src/OAuth/OAuth.ts#L216

It seems that our call to `Auth.configure({...our config})` from our cognito hosted ui CallbackURL is now hitting a code path that invokes this `_validateState`, and fails because [`window.sessionStorage['oauth_state']`](https://github.com/aws-amplify/amplify-js/blob/76cde598c30ee8049798e5988261db9165cc775e/packages/auth/src/OAuth/oauthStorage.ts#L15) is coming back as `null`.

Noteworthy is that **our app does not invoke any aws-amplify functions to initiate login with the cognito hosted UI**. Instead, our code:

1. Invokes `Auth.configure({...our config...})`
2. Invokes `Auth.currentAuthenticatedUser()` within a try/catch block
3. In the aforementioned catch block, manually constructs a url in the format `https://{our-cognito-hosted-ui-subdomain}.auth.{aws-region}.amazoncognito.com/oauth2/authorize?response_type=code&idp_identifier={idpId}&redirect_uri={callbackUrl}&clientId={clientId}&scope=&state={ourOwnCustomSamlRelayState}}`

Our user pool only has a single IdP configured, and it is a SAML provider. We do not use any other authn providers. I imagine this is why we are now seeing this error, because we do nothing to set a `window.sessionStorage` value with the key `oauth_state`, yet when our app lands back on our user pool app client's `CallbackURL` and we invoke `Auth.configure({...our config...})`, it seems to now require that the expected URL state matches.

For now we have temporarily worked around this issue by changing our npm dependency for `@aws-amplify/auth` to `1.2.20`. It is version `1.2.21` that is a breaking change for our scenario. 

**What do you recommend we do?**

Is there an aws amplify function we can invoke that will automatically write the expected oauth flow state to `window.sessionStorage['oauth_state']`? We would need one that constructs and redirects to a URL in the above format, **especially with the ability to pass in our own custom SAML relay state. (This is why we have been constructing a manual URL until now, because when the code was initially written, AWS Amplify offered no way in the API surface to pass a custom `state` querystring parameter in the `/oauth2/authorize` endpoint.)**

Or, if there is still no way for us to invoke an AWS Amplify cognito hosted UI login initiation function that accepts a custom `state` argument, should we just write our expected state to `window.sessionStorage['oauth_state']` before we do our custom redirect to the `/oauth2/authorize` endpoint? And if this is on the right track, should we file a bug in this repo?

Or, is there some third option we're not thinking of that would be better?

**Comment by manueliglesias** [comment]
Hi

I am working on a fix for this, thanks for the patience.

**Comment by manueliglesias** [comment]
Hi, can you try?

aws-amplify@1.1.26-unstable.0
aws-amplify-react@2.3.6-unstable.0

**Comment by danludwig** [comment]
@manueliglesias I am out this week, someone else from my team may be able to, otherwise I won’t be able to test until Tuesday.

Does this mean there is still no way to pass custom relay state to the authorization url via auth.federatedSignIn? We would like to take advantage of the additional security features that were added if we should. Or would you recommend we continue to construct the url manually if we want to pass our own state through cognito & our saml idp?

**Comment by undefobj** [comment]
@danludwig this is an interesting use case, and one that we could support in the future. For now you should construct the URL manually but if you'd like us to support unioning that with the state and PKCE that we construct on your behalf could you open a feature request issue with details on how the experience might look?

**Comment by mel-michael** [comment]
Hi @manueliglesias, thanks for looking into this issue. 

I have tested the latest update i.e. `aws-amplify@1.1.26-unstable.0` & `aws-amplify-react@2.3.6-unstable.0` and noticed it works after setting a timeout of about 3s+

The behaviour I notice is that it first fails the authentication and later authenticates the user.

**Comment by manueliglesias** [comment]
Hi @mel-michael 

you can try again with the @latest dist tag of the packages?, they were published to npm yesterday.

as for the issue you are seeing, when you craft you own hosted ui url, you don't have to call `Auth.federatedSignIn()` yourself. If this is not what's happening, is there a way you can share some code to look at it?

**Comment by lenarmazitov** [comment]
Hi @manueliglesias 
I have same issue with ReactNative hoc: **withOAuth**

aws-amplify@1.1.26
aws-amplify-react-native@2.1.10
