### ISSUE TITLE
code: "CodeMismatchException", message: "Invalid code or auth state for the user."

### ISSUE THREAD

**Issue by calboru** [aws-amplify/amplify-js#3066]
**SMS MFA is not working**
Following error happens when I enable “SMS MFA” for a user manually by using aws-console then try to enter authentication code for that particular user
![image](https://user-images.githubusercontent.com/26364385/55904449-d8fd9000-5b9d-11e9-896c-0e4035b23713.png)

User Pool settings as follow:
![image](https://user-images.githubusercontent.com/26364385/55904463-e3b82500-5b9d-11e9-9e82-11742c1d328c.png)

User settings as follow:
![image](https://user-images.githubusercontent.com/26364385/55904474-ee72ba00-5b9d-11e9-926b-2b072a0a2e5a.png)

Amplify Code
![image](https://user-images.githubusercontent.com/26364385/55904507-021e2080-5b9e-11e9-96c7-55fbe07f593f.png)

Cognito User passed in above code as “authenticatedUser”
![image](https://user-images.githubusercontent.com/26364385/55904532-0f3b0f80-5b9e-11e9-9788-7acb670e4179.png)

**Expected behavior**
Confirm valid authentication code via received SMS.

**Desktop (please complete the following information):**
Angular 7

**Comment by calboru** [comment]
In addition to this issue. As soon as I receive the error cognito sends another authentication code !

**Comment by calboru** [comment]
> Hi @calboru, what version of AWS Amplify are you using?

Hi I am using V 1.1.22

**Comment by calboru** [comment]
> Hi @calboru, what version of AWS Amplify are you using?

@alebiavati just tested 1.1.26 and I have the same issue.

**Comment by DannyHinshaw** [comment]
Having the same issue with v1.2.24. Only difference is it's not SMS. Has there been any fixes for this?

**Comment by hirocsingh** [comment]
Having the smae issue with v3.0.24 using SOFTWARE_TOKEN_MFA. Always getting back CodeMisMatchException

**Comment by SchulzKai** [comment]
I am experiencing the same issue. 

**React Native Project - Version:** 
    "aws-amplify": "^3.3.1",
    "aws-amplify-react-native": "^4.2.6",

**Code:** 
    const handleCodeSubmit = () => {
        Auth.signIn(props.user.username, props.user.password)
            .then((user: CognitoUser) => {
                user.sendMFACode(phoneCode,
                    {
                        onSuccess: (res) => { console.log('res', res) },
                        onFailure: (err) => { console.log('err', err) },
                    },
                    'SMS_MFA'
                )
            }).catch((err) => {
                console.error('handleCodeSubmit', err)
            })
    }

**Error:** 
err Object {
  "code": "CodeMismatchException",
  "message": "Invalid code or auth state for the user.",
  "name": "CodeMismatchException",
}
