### ISSUE TITLE
Vue Authenticator Component missing theme integration

### ISSUE THREAD

**Issue by stevensanborn** [aws-amplify/amplify-js#3068]
Im looking to customize the Authenticator component.

It would be nice to be able to theme the component as you can with react.

`<amplify-authenticator v-bind:authConfig="authConfig" theme="loginTheme"></amplify-authenticator>`

where login theme can set things like color etc

**Comment by stevensanborn** [comment]
I guess we can make use of deep selectors to override the the all the styles , though the class names are not the friendliest . IDK if this the perfered route ? 

` .signin >>> button{
    background-color:#333333
  }`

**Comment by jordanranz** [comment]
FYI, we have started an RFC to discuss a UI component refactor including flexible theming for all of our frameworks. Please feel free to comment on it if you have any further asks!

https://github.com/aws-amplify/amplify-js/issues/3279

**Comment by jordanranz** [comment]
We have added css variable theming to the [new Vue UI component library](https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue).

See: https://docs.amplify.aws/ui/customization/theming/q/framework/vue
