### ISSUE TITLE
RNAWSCognitoModule tries to override versioned host RNAWSCognitoModule in MainApplication 

### ISSUE THREAD

**Issue by Luckygirlllll** [aws-amplify/amplify-js#3071]
**Describe the bug**

RNAWSCognitoModule tries to override versioned host RNAWSCognitoModule in MainApplication 

<img width="342" alt="Screen Shot 2019-04-11 at 14 32 26" src="https://user-images.githubusercontent.com/10096433/55954538-9a340c80-5c67-11e9-8fcc-a16f4671cab3.png">

**To Reproduce**
1. I added aws push notification
2. After that I was trying to build project and got the error

**Expected behavior**

Project should work 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android

**Smartphone (please complete the following information):**
 - OS: Android

**Additional context**
I don't have duplicates in MainApplication 

**Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

```
public List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
        // Add your own packages here!
            new RNAWSCognitoPackage(),
            new RNPushNotificationPackage(),
            new WheelPickerPackage()
    );
  }
```

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by Luckygirlllll** [comment]
I did `react-native unlink amazon-cognito-identity-js` and problem disappeared

**Comment by powerful23** [comment]
@Luckygirlllll are you using Expo instead of an ejected react native app? Seems like it's conflicting with a [module](https://github.com/expo/expo/blob/master/android/versioned-abis/expoview-abi31_0_0/src/main/java/abi31_0_0/host/exp/exponent/modules/api/cognito/RNAWSCognitoModule.java) in the expo.

**Comment by Luckygirlllll** [comment]
@powerful23 I'm using ExpoKit, which is expo + native iOS/Android folders

**Comment by powerful23** [comment]
@Luckygirlllll make sense. Since Expo is included, you don't need to link the cognito module manually. I can send a pr to update the doc about this.
