### ISSUE TITLE
Authenticator React Native offline behavior

### ISSUE THREAD

**Issue by nielsmadan** [aws-amplify/amplify-js#3072]
**Describe the bug**

I have wrapped my root RN Component in `withAuthenticator`. It all works fine while online, but if I start the app after previously logging in when I don't have a network connection, I just get a white screen. Looking into the source code of `aws-amplify-react-native`, it looks like on mount, it will `checkUser` (and since I logged in previously, there will be a user), and then `checkContact`. It looks like that method is checking online whether the user has verified contact details, but when offline it will just throw a network error. Ultimately, the authState will stay in `loading` and the app just shows a blank screen without being able to get to the login even after the network connection is restored.

(`checkContact` also doesn't have a `catch` so we get an unhandled promise rejection / network error.)

**To Reproduce**

1. Use Authenticator in a React Native app.
2. Login once.
3. Stop the app.
4. Disable network (airplane mode / disable wifi / etc.)
5. Start the app again.

**Expected behavior**

Authenticator shows the app or at least is configurable, so the app can specify what it wants to happen.

**Smartphone (please complete the following information):**
 - Device: tested on Nokia 3.1 and Pixel 2 emulator
 - OS: Android

**Comment by ozanbatuhankurucu** [comment]
How we can solve this problem it throws an network error 
![image](https://user-images.githubusercontent.com/50013838/101290702-0450dc00-37d2-11eb-8dd2-987fdb44865b.png)
