### ISSUE TITLE
API graphQL transform

### ISSUE THREAD

**Issue by totaland** [aws-amplify/amplify-js#3077]
**Is your feature request related to a problem? Please describe.**
When creating the schema with @model it automatically creates the DynamoDb table with only the primary key as id and no sort key. This really frustrating me and it takes me ages to find out that is what the @model does when trying to sort the Dynamodb table. 

**Describe the solution you'd like**
The @model should have a way to allow the user to the sort key and primary key or this should be written as a guide in GraphQL transform documentation.

**Describe alternatives you've considered**
Also, it would be nice to allow this option as a default or alternative option with amplify cli

**Additional context**
![image](https://user-images.githubusercontent.com/36496259/56020336-44846080-5d4a-11e9-854d-4ceb88b31cc9.png)

This picture shows that the table created with schema @private note doesn't have sort key.

**Comment by jkeys-ecg-nmsu** [comment]
Have you looked at the `@connection` directive? Its main purpose is to enforce 1-to-many relationships and optionally create a sort key (so every connection maps to a secondary index).

My understanding of the current system is that your primary key for the table will always be a hash key (no sort key) named id, and indices and sort keys are specified with connections.

`directive @connection(name: String, keyField: String, sortField: String) on FIELD_DEFINITION`

https://aws-amplify.github.io/docs/cli/graphql?sdk=js

![image](https://user-images.githubusercontent.com/22964702/56021315-58867e80-5cc6-11e9-8f7e-89bd880959bb.png)

**Comment by totaland** [comment]
Damn, just found out about that too. Cheers man
