### ISSUE TITLE
I'm not getting push notifications from AWS Pinpoint in react native (android) project, onRegister method is never triggered

### ISSUE THREAD

**Issue by Luckygirlllll** [aws-amplify/amplify-js#3080]
**Describe the bug**

**To Reproduce**

1.My Firebase project configured correctly, I was able to receive push notification from Firebase console
2. I enabled Push notifications in AWS Pinpoint console and added API key and Sender ID there
3. I did these commands in the project:
npm install @aws-amplify/pushnotification --save react-native link @aws-amplify/pushnotification

4.Added configuration for analytics and push notifications in App.js
```
Amplify.configure({
Auth: {
    region: 'xxx',
    userPoolId: 'xxx',
    userPoolWebClientId: 'xxx',
    mandatorySignIn: true
},
API: {
    endpoints: [{
        name: "xxx",
        endpoint: "xxxx",
        custom_header: async () => ({ Authorization: await getAuthorizationToken() })
    }]
},
Analytics: {
  disabled: false,
  AWSPinpoint: {
    appId: 'xxxxxx',
   region: 'us-east-1',
  }
}
});

PushNotification.configure({
 appId: 'xxxx',
 region: 'us-east-1',
 });
```

5.Added in componentDidMount in App.js method onRegister:

```
componentDidMount(){
    PushNotification.onRegister((token) => {
        console.log('in app registration', token);
      });
  }
```
After` Sign In` added this updateEndpoint method:
```
Analytics.updateEndpoint({

         address: 'xxxx',
         channelType: 'GCM',
         userId: '1',
     }) 
```
I was trying to create Test campaign in AWS Pinpoint console, but console didn't see any devices and didn't send anything to the phones. `PushNotification.onRegister` method is never triggered. I can't get device token. 
What I'm missing? How to make it work?

**Expected behavior**
Device should receive push notification

**Desktop (please complete the following information):**
 - OS: Android

**Smartphone (please complete the following information):**
 - OS: Android

**Additional context**
I'm using `AWS Cognito` in the project already 

**Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

after adding Amplify.Logger.LOG_LEVEL = 'DEBUG'; I see this messages: 

```
AWSPinpointProvider - init clients
[DEBUG] 08:46.309 AWSPinpointProvider - no change for aws credentials, directly return from init
[DEBUG] 08:46.312 AWSPinpointProvider - record event with params
[DEBUG] 08:46.314 AWSPinpointProvider - pinpoint put events with params Object {
AWSPinpointProvider - record event success.
```

**Comment by saadq** [comment]
I am having similar issues with my device not receiving push notifications. I have an ejected Expo app where I setup Push Notifications by following the docs. I also have the PushNotification setup code, but none of the methods seem to ever get called.

From Firebase, sending a test notification worked when I passed it my device token and I received the notification on my device.

From the Pinpoint console in the "Test messaging" section, I tried Push Notifications with both an endpoint id as well as a device token:

<img width="1440" alt="Screen Shot 2019-04-13 at 12 25 25 PM" src="https://user-images.githubusercontent.com/5678694/56082479-46503180-5de7-11e9-96a3-b5985b73c453.png">

When I tried the endpoint id method by using my user's endpoint id, I got a message saying endpoints must have an address to target:

<img width="1129" alt="Screen Shot 2019-04-13 at 12 21 14 PM" src="https://user-images.githubusercontent.com/5678694/56082417-ae524800-5de6-11e9-866c-c9fc5662629f.png">

When I tried the device token method by using the same device token that I used within the Firebase console, it seemingly says it worked:

<img width="1126" alt="Screen Shot 2019-04-13 at 12 24 34 PM" src="https://user-images.githubusercontent.com/5678694/56082463-1d2fa100-5de7-11e9-8f01-1c2422095c3d.png">

However, my device never actually received any notification, not were any of the PushNotification event handlers called.

---

My setup code:

```js
Analytics.configure({
  AWSPinpoint: {
    appId: '...',
    region: 'us-east-1',
    mandatorySignIn: false
  }
})

// This is called after sign in
Analytics.updateEndpoint({
  ...
})

PushNotification.configure({
  appId: '...'
})

PushNotification.onNotification(notification => {
  console.log('in app notification', notification)
})

// get the registration token
PushNotification.onRegister(token => {
  console.log('in app registration', token)
})

// get the notification data when notification is opened
PushNotification.onNotificationOpened(notification => {
  console.log('the notification is opened', notification)
})
```

**Comment by Luckygirlllll** [comment]
@saadq Could you get device token through onRegister method? Or only thought Firebase console? 
P.S: you need to add `address` field in `updateEndpoint` as far as I understood address should be a device token.

**Comment by saadq** [comment]
I did actually try passing a hardcoded device token to the `address` of `updateEndpoint`, but it didn't seem to resolve the issue :/

To answer your question, I was actually unable to get the `onRegister` call to run either. I just looked at the logs in Android Studio Logcat to get the device, token that I used for both Firebase/Pinpoint.

I did however see [this issue](https://github.com/aws-amplify/amplify-js/issues/2541) which seems related, going to look into that.

**Comment by Luckygirlllll** [comment]
@saadq How did you find device token in Android studio, I see in LogCat only` FCM` message id: 

`Logging event (FE): notification_open(_no), Bundle[{firebase_event_origin(_o)=fcm, message_device_time(_ndt)=0, message_time(_nmt)=1555314333, message_id(_nmid)=5461448130273880619}]`

**Comment by Luckygirlllll** [comment]
@saadq I found token in Android studio logcat, however, when I'm trying to test it via AWS Pinpoint it says "Message sent. Successfully sent push message", but I don't receive any Push notification on my phone. :(

**Comment by saadq** [comment]
For anyone else who runs into this, just search for `gcm registration token` in the logs to find it.

But yeah, I basically have the same issue. I get the successful message sent message but I don't actually get any notification to my device.

**Comment by DubluDD** [comment]
I can still reproduce this 1 month later, was it fixed?

**Comment by Luckygirlllll** [comment]
@DubluDD no, I switched to OneSignal library instead.

**Comment by DubluDD** [comment]
And you managed to get it working on both ios/android?

**Comment by Luckygirlllll** [comment]
@DubluDD yes, it works like a charm! :)

**Comment by DubluDD** [comment]
@Luckygirlllll great! Thanks :D

**Comment by 1pocketaces1** [comment]
@Luckygirlllll no major issues implementing OneSignal for both iOS and Android? How does the cost compare to Pinpoint?

**Comment by Luckygirlllll** [comment]
@1pocketaces1 it works like a charm both in Android and IOS, well, as far as I remember it’s free for mobile, I think they charge only for web push notifications and extra features.

**Comment by yareyaredesuyo** [comment]
@saadq

Me too, it works in fireabase console, but not work in pinpoint.

document itself is very obsolete ( https://aws-amplify.github.io/docs/js/push-notifications ).

this does not work (firebase console).

```
 dependencies {
     compile 'com.google.firebase:firebase-core:12.0.1'
     compile 'com.google.firebase:firebase-messaging:12.0.1'
 }
```

this works (firebase console).

```
    implementation 'com.google.firebase:firebase-core:17.2.0'
    implementation 'com.google.firebase:firebase-messaging:20.0.0'
```

document is obsolete..., and implementation is blackhole...

so amplify team should make update to date documents and examples, that works well.

**Comment by schoenbl** [comment]
I've been having the same issue. I'm thinking about switching to OneSignal too; glad I found this post
