### ISSUE TITLE
authenticator in ionic is it poor?

### ISSUE THREAD

**Issue by NuruddinBadawi** [aws-amplify/amplify-js#3087]
** Which Category is your question related to? **
Ionic

I use `<amplify-authenticator framework="ionic"></amplify-authenticator>`
I see in react the documentation there are more options to customize the entry component but ionic not, 
1- I can't customize any component
2- I can change labels in signUp but I can't touch SignIn.

is it really poor or what?

**Comment by haverchuck** [comment]
@NuruddinBadawi Not all of our UI packages offer the same functionality, which is something we are actively trying to address right now.  At the moment you cannot customize the SignIn component in Ionic - but again, this is something we are actively trying to address.
