### ISSUE TITLE
Auth Question in Ionic

### ISSUE THREAD

**Issue by NuruddinBadawi** [aws-amplify/amplify-js#3088]
** Which Category is your question related to? **
IONIC

** What AWS Services are you utilizing? **
Amplify

I create custom pages for Login and SignUp, but I see there are more details comes after submitting, sometimes need to enter a new password, SMS code ...

my question is: 
I prefer to you your hosted components BUT in I see the login and register form I can't customize it well, so I go to use my own custom forms, so can I keep using my Login/Register form and use your others verification steps and components?

--> view my custom login component ---> if need to verify his credentials ----> now appear the Amplify hosted component for verifying pages.

is it make sense?

**Comment by haverchuck** [comment]
@NuruddinBadawi - Your question makes sense.

The `<amplify-authenticator>` component is a parent component which conditionally renders different children, such as `<amplify-auth-sign-in>`, `<amplify-auth-sign-up>`, etc.  You can use these children on their own if you want, provided that you pass the authState object into them like so:

```
    <amplify-auth-sign-in-ionic
    [authState]="authState"
    ></amplify-auth-sign-in-ionic>

    <amplify-auth-greetings-ionic
    [authState]="authState"
    ></amplify-auth-greetings-ionic>
```

The authState object consists of a state string and a user object:

```
  authState = {
    state: 'signIn',
    user: user,
  }
```

So for your case, you can use the confirm sign in component alongside your custom sign in component:

```
    <amplify-auth-confirm-sign-in-ionic
    [authState]="authState"
    ></amplify-auth-confirm-sign-in-ionic>
```

The auth state is an observable managed by the aws-amplify-angular package's  amplifyService, so you will need make sure that your sign in component sets the auth state appropriately, possibly using something that looks like this when sign in is triggered:

```
  onSignIn() {
    this.amplifyService.auth().signIn(this.username, this.password)
      .then(user => {
        if (user['challengeName'] === 'SMS_MFA' || user['challengeName'] === 'SOFTWARE_TOKEN_MFA') {
          this.amplifyService.setAuthState({ state: 'confirmSignIn', user });
        } else if (user['challengeName'] === 'NEW_PASSWORD_REQUIRED') {
          this.amplifyService.setAuthState({ state: 'requireNewPassword', user });
        } else {
          this.amplifyService.setAuthState({ state: 'signedIn', user });
        }
      })
      .catch((err) => {
        this._setError(err);
      });
  }
```

I am submitting a PR to our documentation to make this a little more clear.

**Comment by haverchuck** [comment]
@NuruddinBadawi I am closing this issue - if the instructions above do not work for you, please feel free to submit a new issue with details.  I have updated our documentation page (it will probably take a bit of time to actually propogate to the production site).
