### ISSUE TITLE
[I18n] Use slugs instead of English strings as keys 

### ISSUE THREAD

**Issue by ChristopheBougere** [aws-amplify/amplify-js#3092]
**Is your feature request related to a problem? Please describe.**
The current i18n system is working but:
- Need to search in the code to find missing literals to translate.
- There is no complete list of all the existing literals, so we don't know the % of translation in a specific language.
- English strings are the translation keys. If a typo is fixed in English (or just a space added), then all translations will become obsolete (they won't be used anymore, unless someone updates the key).

**Describe the solution you'd like**
Instead of using English strings as keys, we could use some slugs (no punctuation/spaces). It would also be easier to separate translations by modules (`auth.signin.username` and `auth.signin.password` would be together).
Behaviour could be inspired by [https://www.i18next.com](i18next)
I know it's a breaking change, but maybe for a major release? Or maybe at least for new translations?

**Describe alternatives you've considered**
n/a

**Additional context**
I've translated a few literals in #3091. It's difficult to find the keys, which includes spaces and punctuation. Also, there is no list of all literals which is cumbersome.

**Comment by haverchuck** [comment]
@ChristopheBougere Thanks for this request.  We will look into this as part of a future major release.

**Comment by ericclemmons** [comment]
#4979 addresses this, which adds `Translations` as key/value pairs using typed keys:

```ts
import { I18n } from "aws-amplify"
import { Translations } from "@aws-amplify/ui-components"

 I18n.putVocabulariesForLanguage('en-US', {
   [Translations.SIGN_OUT]: 'All done!',
 });
```

See: https://github.com/aws-amplify/amplify-js/blob/master/packages/amplify-ui-components/src/common/Translations.ts

We haven't ported over prior translations yet, but the foundation is there to support it now, thanks to your input @ChristopheBougere!
