### ISSUE TITLE
Amplify Auth with Angular 7 lack of documentation

### ISSUE THREAD

**Issue by pinalmdave** [aws-amplify/amplify-js#3094]
** Which Category is your question related to? ** How to implement authentication in Angular 7 Web App and Amplify Auth using Hosted UI Technique

** What AWS Services are you utilizing? ** AWS Cognito, Amplifier, Amplifier package for Angular (aws-amplify-angular)

** Provide additional details e.g. code snippets **

I am trying to implement Authentication in my Angular 7 App using newly released AWS Amplify service. I am using Hosted UI option. On click of Login button, Login/SignUp dialog box displayed and I am able to do sign up and login. However, Amplify documentation doesn't mention how to set user authenticated and access authenticated user info after successful login. There is a mention of use of Hub event on few posts but I am not sure how (and in which component) to integrate it in Angular 7 App.

**Comment by lclghst** [comment]
> Amplify documentation doesn't mention how to set user authenticated and access authenticated user info after successful login

https://aws-amplify.github.io/docs/js/angular#subscribe-to-authentication-state-changes

Please follow the link to see a code example of how to subscribe to auth changes.

**Comment by pinalmdave** [comment]
Thanks. I have seen this code sample and tried to implement it in my Angular App custom Auth Guard service. But it's not working, I think I am missing something. Is there any code sample that demonstrates complete authentication steps for Angular Apps using Amplify Angular Hosted UI

**Comment by haverchuck** [comment]
@pinalmdave  - Are you using the [Authenticator](https://aws-amplify.github.io/docs/js/angular#authenticator) component from the `aws-amplify-angular` package, or are you using the [Cognito Hosted UI](https://aws-amplify.github.io/docs/android/authentication#using-hosted-ui-for-authentication)?  These are very different things.  It sounds like you are using the Hosted UI, but I just wanted to confirm.

Assuming you are using Hosted UI, please check out [this](https://aws-amplify.github.io/docs/js/hub#authentication-events) sample.  It describes how to listen to Auth events using Hub.

**Comment by powerful23** [comment]
Closing this issue due to no further response. Please let us know if you still have this issue.

**Comment by chezhiane** [comment]
can some one please explain where am i to add the amplify hub subscription in my angular app

in main.ts or a separate comp

import { Hub, Logger } from 'aws-amplify';

const logger = new Logger('My-Logger');

const listener = (data) => {

    switch (data.payload.event) {
    
        case 'signIn':
            logger.error('user signed in'); //[ERROR] My-Logger - user signed in
            break;
        case 'signUp':
            logger.error('user signed up');
            break;
        case 'signOut':
            logger.error('user signed out');
            break;
        case 'signIn_failure':
            logger.error('user sign in failed');
            break;
        case 'configured':
            logger.error('the Auth module is configured');
            
    }
}

Hub.listen('auth', listener);

**Comment by rudyhadoux** [comment]
That is a good Angular Amplify Authentication example :

https://github.com/mjzone/amplify-user-profile
