### ISSUE TITLE
With react-native 0.59.3 cognito-identity-js triggers a warning "Async Storage has been deprecated"

### ISSUE THREAD

**Issue by millarm** [aws-amplify/amplify-js#3095]
**Describe the bug**
Logging in with Cognito-identity-js on react-native 0.59.3 triggers a yellow warning

"Async Storage has been deprecated"

**To Reproduce**
Build and run with react-native 0.59.3

**Expected behavior**
No warning

**Sample code**

The cause of this is this line of code

import { AsyncStorage } from 'react-native';

https://github.com/aws-amplify/amplify-js/blob/52e35860301847207b239211521c704b5054ea1e/packages/amazon-cognito-identity-js/src/StorageHelper-rn.js#L18

Fix is to move this to using

https://github.com/react-native-community/react-native-async-storage

**Comment by joseph-d-p** [comment]
Still seeing this issue. Suggesting to reopen @haverchuck.

**Comment by ALIKIN6** [comment]
I think it is good to have some changes for this warning

**Comment by richardtks** [comment]
This warning message still persists.
