### ISSUE TITLE
Modules not correctly marked as having side effects

### ISSUE THREAD

**Issue by nihakue** [aws-amplify/amplify-js#3097]
**Is your feature request related to a problem? Please describe.**
Amplify modules have a side effect (registration), but do not provide a [sideEffects](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free) config in their package.json. The effect of this is that when doing something like this:

```
import Amplify from '@aws-amplify/core'
import Auth from '@aws-amplify/auth'
import Analytics from '@aws-amplify/analytics'

Amplify.configure({
  Auth: {...},
  Analytics: {...},
});
```

when using tree-shaking, Auth will potentially get tree-shaken out of the bundle because it's only being imported for its side-effect.

**Describe the solution you'd like**
Add sideEffects config to package.json or make modules pure.

**Comment by jkeys-ecg-nmsu** [comment]
If you're using modular imports, why wouldn't you do this?

```
Auth.configure({...});
Analytics.configure({...});
```

**Comment by haverchuck** [comment]
@nihakue  - Did the response from @jkeys-ecg-nmsu help?

**Comment by nihakue** [comment]
That's a fine workaround, but the fact remains that Amplify modules claim to be ES6 modules (they set module in package.json) but have effectful imports. Most places in the Amplify documentations tell you to configure via `Amplify.configure`, and there are [blog posts](https://hackernoon.com/modular-imports-with-aws-amplify-daeb387b6985) high in the Google search results that tell you to do this. 

If this is not expected to work, Amplify should error when you try it. If it is expected to work, it should be supported. The way to support it is with "sideEffect" in package.json

**Comment by ChristianDavis** [comment]
This is very confusing to figure out. 
```
Auth.configure({Auth: {...}}) 
```
works, but should at least be documented.

**Comment by Amplifiyer** [comment]
We have added sideEffects config `sideEffects:false` in all of Amplify modules after removing the side effects from index files. These changes are now available in Amplify V3
