### ISSUE TITLE
How to cancel Storage file upload

### ISSUE THREAD

**Issue by pippo111** [aws-amplify/amplify-js#3098]
I cannot find it anywhere in Amplify Storage Documantation, but is there a way to cancel file upload (put) ? It will be useful to give user possibility to cancel upload of files.

I'm using Storage.put like so:
```
return Storage.vault.put(filename, buffer, {
    metadata,
    progressCallback (e) {
      // log progress
    }
  })
```
but all I get is Promise, which I cannot cancel simply by js.

**Comment by haverchuck** [comment]
@pippo111 -  I do not believe this is supported at the moment;  I will mark this as a feature request.

**Comment by pippo111** [comment]
@haverchuck Any news on that ? It is getting really problematic, when internet connection breaks and user is unable to cancel his upload. Is there any way to do it maybe via some lower level API ? Any hints on that ?

**Comment by videoAbyss** [comment]
Any idea when this might be supported ?

**Comment by nitinkaveriappa** [comment]
Will a cancel feature be added???

**Comment by juanludlf** [comment]
there is a PR in progress
https://github.com/aws-amplify/amplify-js/pull/3769

**Comment by sammartinez** [comment]
Resolving as per the above implementation has been complete

**Comment by sorokinvj** [comment]
I will open this one, because API.cancel() as mentioned [here](https://github.com/aws-amplify/amplify-js/pull/5753#issuecomment-654481080) has not solved this issue. 

But feature is very needed! In my app (but I suspect in any app), user may start upload huge file by mistake and there is no workaround to cancel it

**Comment by boggsey** [comment]
Agreed that this is very needed. I'm uploading a lot of very large files and need the ability to easily cancel in case an incorrect file is being uploaded.

**Comment by sammartinez** [comment]
All, 

Wanted to provide an update on this feature. We are planning this work out for next quarter. While we don't have a timeline on when this feature will complete, know that we have heard you and to look out for more updates on this feature in the future. 

Thanks! 

Amplify JavaScript

**Comment by sammartinez** [comment]
#7984

**Comment by enriqueavg** [comment]
@sammartinez Thanks for the update. Cancel feature for put and get are very needed.

**Comment by agileurbanite** [comment]
Our latest PR ☝️ introduces the ability to cancel put and get requests for storage.  Please let us know if this addresses your needs which will go out in the next release.
