### ISSUE TITLE
Support use of third party service for emails/SMS

### ISSUE THREAD

**Issue by tobiastornros** [aws-amplify/amplify-js#3099]
**Is your feature request related to a problem? Please describe.**
Can´t use codeParameter in Custom Message trigger event to send email or sms via third party service like Twilio or Sendgrid. 

Its very hard to customize emails and webviews for Cognito. It would be so much better if AWS allowed us to use any service we want via Lambda triggers. 

**Describe the solution you'd like**
Expose codes/tokens used for Cognito events and support it via Amplify.

**Describe alternatives you've considered**
I can´t find any way to expose the code generated by Cognito and then use it auth.confirmSignUp or auth.forgotPasswordSubmit() if we could email with our own service and then link directly to our app.

**Comment by haverchuck** [comment]
@tobiastornros We do not support this at the moment, but I am marking this as a feature request. Thanks!

**Comment by sammartinez** [comment]
@tobiastornros Does [Cognito Lamda triggers](https://aws-amplify.github.io/docs/cli-toolchain/cognito-triggers) solve this use case for you ? This was recently implemented into Amplify CLI. Please let us know.

**Comment by tobiastornros** [comment]
@sammartinez Cognito Triggers can´t be used on confirmSignUp or forgotPasswordSubmit since  these emails are saved as inline html in the under Message customizations in Cognito UserPool settings.

**Comment by mir1198yusuf** [comment]
do amplify support this trigger yet CustomSMSSender ?
https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-sms-sender.html

**Comment by maximivanov** [comment]
New `CustomEmailSender` and `CustomSMSSender` Lambda triggers in Cognito are definitely the way to use 3rd party notification services. 

Documentation and tooling still need some refinement at the moment:

- Cognito Console does not support new triggers
- AWS CLI supports new triggers
- CloudFormation docs say triggers are not supported, but in reality it works
- Terraform does not support setting new triggers yet (there's a workaround)

Not sure Amplify supports new triggers either. They can be implemented with CloudFormation and Terraform in the meantime though: [Send AWS Cognito emails with 3rd party ESPs](https://www.maxivanov.io/send-aws-cognito-emails-with-3rd-party-esps/).

**Comment by arnm** [comment]
+1

**Comment by andreish** [comment]
CustomEmailSender the event sent to lambda has no code param:   
event": {
        "version": "1",
        "triggerSource": "CustomEmailSender_ForgotPassword",
        "region": "us-west-2",
        "userPoolId": "us-west-2_bubu",
        "callerContext": {
            "awsSdkVersion": "aws-sdk-unknown-unknown",
            "clientId": "9epa1ev58pgvkcbugbug4q2ir2p1"
        },
        "userName": "4fc3971e-914c-4300-905d-5c60e14836fc",
        "request": {
            "userAttributes": {
                "cognito:user_status": "CONFIRMED",
                "email": "a@b.com",
                "email_verified": "true",
                "family_name": "S",
                "given_name": "Ai",
                "sub": "4fc3971e-914c-4300-905d-5c60e14836fc"
            },
            "codeParameter": "",
            "usernameParameter": "",
            "clientMetadata": null
        },
        "response": {
            "smsMessage": "",
            "emailMessage": "",
            "emailSubject": ""
        }
    },

**Comment by RajGoodF** [comment]
Yes facing the same issue of no attribute like `code` in  event

**Comment by blanchma** [comment]
Almost three years later and customSmsSender still not supported.

**Comment by waysnmeans** [comment]
I have cracked how to user third party service to send emails/SMS on AWS without using SNS Service. I was able to send SMS using customSmsSender and third party service. Feel free to reach me at developer@waysandmeanstechnology.com if anyone needs help. Thanks

**Comment by heikodam** [comment]
+1 Is there any update on this? I am also facing the same issue that there is no "code" in the event "CustomEmailSender" Lambda Trigger.

**Comment by waysnmeans** [comment]
> +1 Is there any update on this? I am also facing the same issue that there is no "code" in the event "CustomEmailSender" Lambda Trigger.

send me the details on the email mentioned in the above response, I will reply with the solution. Thanks

**Comment by nadetastic** [comment]
Following up on this - although the Amplify CLI doesn't have out of the box support for this, there are some steps you can take to get this working. @blanchma @maximivanov 

a. You will need to create and configure a lambda function as described at [1] depending on your SMS or Email trigger, with some reference code included. 

b. In addition to the lambda function, you will also need a KMS key, which is used by the lambda function to decrypt the code before it is sent to the end user. Be sure to set all the necessary permissions.

c. To connect them to your user pool, you can use `amplify override auth` which will generate an `override.ts` file. In this file, you can update the user pool configuration in order to add the lambda function and the KMS key. Here's a sample assuming your resources are in us-east-1:
```js
import { AmplifyAuthCognitoStackTemplate } from '@aws-amplify/cli-extensibility-helper';

export function override(resources: AmplifyAuthCognitoStackTemplate) {

    resources.userPool.lambdaConfig = {
        customEmailSender: {
            lambdaArn: 'arn:aws:lambda:us-east-1:<account_number>:function:<function_name>',
            lambdaVersion: 'V1_0',
        },
        customSmsSender: {
            lambdaArn: 'arn:aws:lambda:us-east-1:<account_number>:function:<function_name>',
            lambdaVersion: 'V1_0',
        },
        kmsKeyId: 'arn:aws:kms:us-east-1:524405517764:key/<key_id>',
    }

}
```

[1] https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-sender-triggers.html

@heikodam for your use case I haven't been able to repro, as I am getting the encrypted code. Do you have repro steps that are different from the above?

**Comment by 8maxxam8** [comment]
@nadetastic Happy to help! The general way as described above is correct. Can you please let me know what is not working exactly?
