### ISSUE TITLE
Cognito Authorization Code Flow with Social/oAuth Providers - How to?

### ISSUE THREAD

**Issue by Wintereise** [aws-amplify/amplify-js#3106]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
AWS Cognito.

** Provide additional details e.g. code snippets **

The docs at https://aws-amplify.github.io/docs/js/authentication#oauth-and-hosted-ui state that one should add onClick handlers such as `() => Auth.federatedSignIn({provider: "Facebook"})` to trigger the specific auth flow.

This goes against the current TS definition files as well as the documentation at https://aws-amplify.github.io/amplify-js/api/classes/authclass.html#federatedsignin

In fact, trying to do it simply crashes due to trying to operating on undefined 2nd / 3rd params. This function is now meant to tie in manual oAuth tokens to Amplify instead.

The withOAuth HOC likely works (I didn't try), but I'd like control over the UI (instead of using `props.OAuthSignIn` which seems to be a link to the hosted UI).

Regardless, we figured out the URLs needed, and can currently get the oAuth authorization code grant from AWS, and are being redirected back to our app.

Question is, how do we tie in this authorization code (and a resolution mechanism (i.e: calling `oauth2/token` from the backend)) with Amplify auth?

I'm able to send this code to the backend myself, and can get tokens/what not just fine, but doing so means I'll have to forego Amplify's auto token maintenance (such as auto refresh) and profile updates.

Any thoughts here?

No code snippets at this time as I'm not really sure what to even call.

**Comment by Wintereise** [comment]
After mucking about the source code, I noticed that there is a url listener which fires after configure is called with a signInRedirect URL set and reads the search string for code / error (https://github.com/aws-amplify/amplify-js/blob/d841e99db208ecc8fe2d349248d586fb941ca059/packages/auth/src/Auth.ts#L210).

There's also a deprecation warning set atop the invocation. 

Any way / plans to make this explicit currently? The user experience is less than optimal with the implicit way.

The underlying code is private (and thus cannot really be called directly in a TS environment). I can of course locally patch it, if exposing it in a future version is planned.

**Comment by haverchuck** [comment]
@Wintereise  - If you aren't using the Amplify CLI to setup oAuth, then you can manually set up the configuration as described [here](https://aws-amplify.github.io/docs/js/hub#authentication-events). 

Additionally, you shouldn't need to take any action to use the token that is returned from the provider; Amplify should cache these for you.  If you want to take some sort of action after authentication is complete (such as showing portions of your application), you can listen to the [Hub events](https://aws-amplify.github.io/docs/js/hub#authentication-events).

**Comment by Wintereise** [comment]
Hey @haverchuck - thanks for getting back to me.

Yeah, there's a urlListener that auto triggers if a queryString of `code` exists on the URL. I wanted this to become explicit, hence the question.

Regardless, the auto trigger is fine for now too. Thank you.
