### ISSUE TITLE
Analytics has not been configured

### ISSUE THREAD

**Issue by PunkHaz4rd** [aws-amplify/amplify-js#3109]
**Describe the bug**
When using an oauth configured auth(), it fires this exception. It was working fine a few days ago.

**To Reproduce**
1. aws-amplify@^1.1.26
2. configure it with oauth for a federatedSignIn
3. do the federatedSignIn, get access_token

**Expected behavior**
Using the access_token from URL, automatically creating a session.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 1.1.26

**Sample code**

```
    // REQUIRED only for Federated Authentication - Amazon Cognito Identity Pool ID
    identityPoolId: environment.cognito.identityPoolId,
    // REQUIRED - Amazon Cognito Region
    region: environment.cognito.region,
    // OPTIONAL - Amazon Cognito User Pool ID
    userPoolId: environment.cognito.userPoolId,
    // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
    userPoolWebClientId: environment.cognito.userPoolWebClientId,
    // OPTIONAL - Enforce user authentication prior to accessing AWS resources or not
    mandatorySignIn: true,
    oauth: {
        domain: "xxxxxxxxx.auth.eu-west-1.amazoncognito.com",
        scope: ['email', 'profile', 'openid'],
        redirectSignIn: encodeURIComponent(window.location.href),
        redirectSignOut: encodeURIComponent(window.location.href),
        responseType: 'token',
        options: {
            AdvancedSecurityDataCollectionFlag: false
        }
    }
```

**Comment by PunkHaz4rd** [comment]
> ERROR Error: Uncaught (in promise): Error: Analytics has not been configured
Error: Analytics has not been configured
    at AnalyticsClass.<anonymous> (Analytics.js:223)
    at step (Analytics.js:52)
    at Object.next (Analytics.js:33)
    at Analytics.js:27
    at new ZoneAwarePromise (zone.js:900)
    at push../node_modules/@aws-amplify/analytics/lib/Analytics.js.__awaiter (Analytics.js:23)
    at AnalyticsClass.push../node_modules/@aws-amplify/analytics/lib/Analytics.js.AnalyticsClass.record (Analytics.js:217)
    at authEvent (index.js:68)
    at Object.listener [as callback] (index.js:39)
    at Hub.js:122
    at resolvePromise (zone.js:821)
    at resolvePromise (zone.js:778)
    at zone.js:731
    at step (Analytics.js:26)
    at Analytics.js:27
    at new ZoneAwarePromise (zone.js:900)
    at push../node_modules/@aws-amplify/analytics/lib/Analytics.js.__awaiter (Analytics.js:23)
    at AnalyticsClass.push../node_modules/@aws-amplify/analytics/lib/Analytics.js.AnalyticsClass.record (Analytics.js:217)
    at authEvent (index.js:68)
    at Object.listener [as callback] (index.js:39)

**Comment by CaryLandholt** [comment]
I've encountered the same but using:
```
    "aws-amplify": "1.1.27-unstable.2",
    "aws-amplify-react": "2.3.6-unstable.0",
```

**Comment by CaryLandholt** [comment]
Found a way to disable Analytics and prevent that exception.

```JavaScript
import { Analytics } from 'aws-amplify'

Analytics.configure({ disabled: true })
```

**Comment by PunkHaz4rd** [comment]
I found out where my error came from. I removed aws-amplify-angular from my project and did all from aws-amplify. It's smoother too.
I guess on your side @CaryLandholt, it's coming from aws-amplify-react.
Those must be some poorly written overlay.

**Comment by normchenjk** [comment]
Had the same issue crop up with the following import statement:
 `import { Amplify, Auth } from 'aws-amplify';` 

The fix for my case was to change it to:
`import Amplify, { Auth } from 'aws-amplify';`

**Comment by Chibuzor44** [comment]
@CaryLandholt your solution rescued me, thanks
