### ISSUE TITLE
IOS deep linking handle on cold start

### ISSUE THREAD

**Issue by vitalii** [aws-amplify/amplify-js#3110]
** Which Category is your question related to? **
Push notification deep linking
** What AWS Services are you utilizing? **
push notifications, pinpoint
** Provide additional details e.g. code snippets **
When I receive notification and want to handle deep linking and redirect app, can't do it on ios when app not running. 

```javasrcipt
PushNotification.onNotification(notification => {
    handlePushNotification(notification);
    notification.finish(PushNotificationIOS.FetchResult.NoData);
});
```

`onNotification` simply never been called. I know there is also 
```javascript
PushNotification.onNotificationOpened(notification => {
  handlePushNotification(notification);
});
```
but this code works only for android https://github.com/aws-amplify/amplify-js/blob/master/packages/pushnotification/src/PushNotification.ts#L87

Linking doesn't work either
https://facebook.github.io/react-native/docs/linking#addeventlistener

Is there any other way to handle opening app with deep linking for ios?
thank you

**Comment by haverchuck** [comment]
@vitalii  - Just to confirm, you are using React Native and configuring your push notifications using Apple Push Notification service (APNs)?

**Comment by vitalii** [comment]
@haverchuck, yes, I'm using RN with APNs

**Comment by BHesseldieck** [comment]
Dear Amplify Team,

we have been waiting anxiously for the arrival of deep-linking from push notifications for 9 months already. We build and maintain apps for global OEM car manufacturers and must now – unfortunately – begin considering replacing Pinpoint/Amplify because of this.

Can you please provide an ETA for the arrival of this feature?

**Comment by powerful23** [comment]
Related to #1849

**Comment by powerful23** [comment]
@BHesseldieck hi, sorry to hear that. Can you give more details about your usage of the push notification module? As I know the notification object will contain the info of deep-linking so you can do whatever you want with that. Are you having trouble receiving the notification or you want the push notification module to handle deep linking automatically?

**Comment by BHesseldieck** [comment]
Push notifications as well as deep linking is working if the app is in memory (running in background), but when the app was killed or not used for a while it is just starting the app without navigating to the deep-linked page.

We would like to deep link into the app when the user taps on a push notification even if the app is not running in the background. Unfortunately does it seem that the callback (onNotification) is just called when the app is running in the background.

A new callback was introduced for android (onNotificationOpened), but not for iOS. We would like to know when it will be also released on iOS, which is used by the majority of our users.

So we have the same issue as the thread-starter.

thanks for your support!

**Comment by powerful23** [comment]
@vitalii @BHesseldieck Hi, sorry for the late response. After some investigation around using push notification in IOS:
1. To get the pushnotification body from cold start, you will need to use `PushNotificationIOS.getInitialNotification()`, as you can see the IOS part of Amplify Push Notification module is mainly using the `PushNotificationIOS` module from `react-native`. So as a workaround, you can directly use that module to get the notification body when the app cold starts.
2. Unfortunately `onNotificationOpened` won't work in IOS but you can change the behavior of `onNotification`. For now it will be triggered when the notification arrives. But if you unselect the `Remote notifications` in the `Background Modes` in xcode, then it will be triggered when the user taps the notification. You can find other ways to do that by checking [this](https://stackoverflow.com/questions/32061897/ios-push-notification-how-to-detect-if-the-user-tapped-on-notification-when-the)

As a conclusion, you can handle the deep linking by using `PushNotificationIOS.getInitialNotification()` when app cold starts or `onNotification` when app is in the background and the notification is tapped by the user.

We will continue investigating into this issue and provide more info in the documentation.

**Comment by denchp** [comment]
I'm having the same issue.  It appears the the onNotificationOpened is not triggered when the app is *not* in the background (i.e., Cold Boot).

With a warm boot I'm able to access the notification and handle it accordingly, with a cold boot I see the notification event: 

    I/emit: notification opened: Bundle[{pinpoint.url...

But Linking.getInitialURL() is empty, and the onNotificationOpened() is never called.

RN version 59.9
Amplify version: 1.1.28
Amplify RN version: 2.1.12
