### ISSUE TITLE
Interactions not working for angular component

### ISSUE THREAD

**Issue by vivekFAGH** [aws-amplify/amplify-js#3111]
**Describe the bug**
I am trying to use the angular component for interactions. I am able to use the auth and s3 component okay. The interactions component does not display lex bot responses for any intents backed by a lambda. Any other input responds with a standard reply and the component renders the question and response.
Note that the the same bot works as expected in a custom chat display component.

    "@angular/core": "~7.2.0",
    "aws-amplify": "^1.1.26",
    "aws-amplify-angular": "^3.0.1",

I have configured amplify manually:
    },
    Interactions: {
      bots: {
        botname1: {
          name: 'botname1',
          alias: '$LATEST',
          region: 'us-east-1',
        },
       botname2: {
          name: 'botname2',
          alias: '$LATEST',
          region: 'us-east-1',
        },
      }
    }

The angular component has this:
<amplify-interactions 
bot="botname1" 
clearComplete="true" 
welcomeMessage='Welcome to <botname>'
(complete)="onBotComplete($event)"
[conversationModeOn]="true"
[voiceEnabled]="false"
[textEnabled]="true">
</amplify-interactions>

  onBotComplete(event) {
    console.log("On Bot Complete was called"); 
  }

This is as far as the documentation talks about configuring and using the component. I might be missing something obvious here. 

**Expected behavior**
The component should display user input and responses for all user inputs

**Screenshots**
![image](https://user-images.githubusercontent.com/25539191/56220404-ed3b0480-6057-11e9-9897-4d9c36450bd9.png)
![image](https://user-images.githubusercontent.com/25539191/56220468-06dc4c00-6058-11e9-96d5-b45ebc0173ac.png)
![image](https://user-images.githubusercontent.com/25539191/56220548-25dade00-6058-11e9-877b-7741aae3f068.png)

**Comment by haverchuck** [comment]
@vivekFAGH  - I noticed that you have an empty string as the value for bot in your markup.  Is this just for posting to this issue, or is that what you're doing in your actual app?

**Comment by vivekFAGH** [comment]
Sorry, that I had removed the bot names before posting here:
    Interactions: {
      bots: {
        <botname>: {
          name: '<botname>',
          alias: '$LATEST',
          region: 'us-east-1',
        },
        <botname>: {
          name: '<botname>',
          alias: '$LATEST',
          region: 'us-east-1',
        },
      }
    }
});

**Comment by vivekFAGH** [comment]
Looks like its stripping off the placeholder:
    Interactions: {
      bots: {
        botname1: {
          name: 'botname1',
          alias: '$LATEST',
          region: 'us-east-1',
        },
        botname2: {
          name: 'botname2',
          alias: '$LATEST',
          region: 'us-east-1',
        },
      }
    }
});

**Comment by haverchuck** [comment]
@vivekFAGH Do you see anything in the lambda logs indicating that the lambda is succeeding or failing in these cases?

**Comment by vivekFAGH** [comment]
I see success in the logs. I can test the bot from the lex console with success. I can also test the same bot in a custom angular chat component that I wrote. I was trying to switch to the amplify provided component when I noticed this issue.

**Comment by haverchuck** [comment]
Is it still happening when you remove the 'complete' attribute from the markup?

**Comment by vivekFAGH** [comment]
Yes, same issue even after removing the complete attribute.

**Comment by haverchuck** [comment]
Ok, we will be looking into it.

**Comment by elorzafe** [comment]
@vivekFAGH can you try setting `conversationModeOn=false` I think that is the issue

**Comment by vivekFAGH** [comment]
Sorry that did not work either.
<amplify-interactions 
bot='botname1' 
clearComplete='true' 
welcomeMessage='Welcome to'
[conversationModeOn]='false'
[voiceEnabled]='false'
[textEnabled]='true'>
</amplify-interactions>

**Comment by vivekFAGH** [comment]
@elorzafe Anything else I can try?

**Comment by vivekFAGH** [comment]
So I found that:
when the lex  response is 
{"dialogState":"ElicitIntent", ...}

the component displays the response.
when the lex  response is 
"dialogState":"Fulfilled","intentName"....}
The component resets.

This is with the component configured with clearComplete='false'
