### ISSUE TITLE
Angular lex issue with Chatbox component aws-lex-audio.js loading blob for 5-7 second even though i am not using it

### ISSUE THREAD

**Issue by kristophor** [aws-amplify/amplify-js#3115]
Amplify angular is loading chatbox component which loading aws-lex-audio.js that is requesting 
blob:http://localhost:8777/215a834f-395d-4d2a-bbb9-b65723611 took 5-7 second in general.

**To Reproduce**
1. install amplify angular
2. import amplify module
3. start website 
4. open website
5. aws-lex-audio.js is loading blob for 5-7 seconds

**Expected behavior**
not loading chatbox component as i am not using it 

**Screenshots**
![image](https://user-images.githubusercontent.com/7058039/56256479-d7006900-6096-11e9-8c91-6b5688d5a0fb.png)

![image](https://user-images.githubusercontent.com/7058039/56256507-f3040a80-6096-11e9-9050-23d8ed9e3949.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome
 - Version 73.0.3683.103

**Comment by lluis-stage** [comment]
Problem still present in aws-amplify-angular 4.1.2
