### ISSUE TITLE
'React/RCTPushNotificationManager.h' file not found during adding AWS Pinpoint to IOS

### ISSUE THREAD

**Issue by Luckygirlllll** [aws-amplify/amplify-js#3118]
**Describe the bug**
I'm adding AWS Pinpoint IOS to my project

**To Reproduce**
1. Manually link PushNotificationIOS 
2. #import <React/RCTPushNotificationManager.h> in AppDelegate.m

**Expected behavior**
Project builds without errors

**Desktop (please complete the following information):**
 - OS: IOS

**Smartphone (please complete the following information):**
 - Device: Iphone
 - OS: IOS

**Additional context**
I don't have Libraries folder in my Xcode project, so I added  PushNotificationIOS to the root of the iOS project, but it seems that this is not a correct solution.How to make manual linking of PushNotificationIOS correctly if there is no Libraries folder in the project? That's expoKit project.

**Screenshots**
<img width="243" alt="Screen Shot 2019-04-17 at 16 45 43" src="https://user-images.githubusercontent.com/10096433/56294724-33fe2c80-6134-11e9-8f7d-4dba3b2866f2.png">

**Comment by Luckygirlllll** [comment]
This issue relates to ExpoKit, and manual libraries linking in ExpoKit,  more info can be found [here](https://forums.expo.io/t/push-notifications-with-expokit-advice/2508/39) and [here](https://stackoverflow.com/questions/48683663/react-rcteventemitter-h-file-not-found).

**Comment by haverchuck** [comment]
@Luckygirlllll -  Did you follow [these instructions](https://aws-amplify.github.io/docs/js/push-notifications#setup-for-ios)?

**Comment by Luckygirlllll** [comment]
@haverchuck Yes, I followed that instruction. However, that tutorial doesn't say anything about the fact that manual linking in `ExpoKit `should be done differently than in pure react native. That would be cool to mention about it in the tutorial  

The solution of this problem: 

First  way how to solve it: 

1.cd into your project and make sure you have a podfile (pod install)
2.You’re going to want to open up your finder then open up project-name/ios/Pods/Headers/Public 3.Your Xcode wants React/RCTPush… so drag and drop the React folder in 2. ^ into your header search path (since `RCTPushNotificationManager.h` is listed in here).
4. You can find your header search path by opening up Xcode and clicking on your project in the top left corner then opening up the Libraries folder and then opening up `RCTPushNotification.xcodeproj`.
5. Click Build Setting and type header search path in the search bar. Then open it up and drag and drop 3. ^ over.

Here is the second way:

in Podfile add the library which you need, in my case it was RCTPushNotification:

```
 pod 'React',
    :path => "../node_modules/react-native",
    :inhibit_warnings => true,
    :subspecs => [
      "Core",
      "ART",
      "RCTPushNotification"]
```

**Comment by mattdamon108** [comment]
For the reference.
I solve this issue with modifying Podfile and add below line

```
pod 'React-RCTPushNotification', :path => '../node_modules/react-native/Libraries/PushNotificationIOS'
```
