### ISSUE TITLE
Expose promisifed helper to delete attributes on Auth

### ISSUE THREAD

**Issue by lookitsatravis** [aws-amplify/amplify-js#3119]
**Is your feature request related to a problem? Please describe.**
It is preferable to always use the `Auth` namespace for interacting with Cognito users because most (all?) of the methods return promises. However, there is no wrapped method exposing the ability to delete user attributes from a Cognito user and so we're forced to use the `CognitoUser` directly which adds confusion to the workflow since it is callback-based.

**Describe the solution you'd like**
Using a similar implementation to `updateUserAttributes` (see: https://github.com/aws-amplify/amplify-js/blob/master/packages/auth/src/Auth.ts#L866), we'd like to see `deleteUserAttributes` implemented wrapping up the `deleteAttributes` method of `CognitoUser` (see: https://github.com/aws-amplify/amplify-js/blob/master/packages/amazon-cognito-identity-js/src/CognitoUser.js#L1111).

```js

// instead of doing something like...

const cognitoUser = await Auth. currentAuthenticatedUser();
cognitoUser.deleteAttributes(['phone_number'], (err) => {
    if (err) {
        throw err;
    }
});

// we'd like to do this...

const cognitoUser = await Auth. currentAuthenticatedUser();
await Auth.deleteUserAttributes(cognitoUser, ['phone_number']);

// or this which automatically uses the current authenticated user

await Auth.deleteCurrentUserAttributes(['phone_number']);
```

**Describe alternatives you've considered**
We are currently invoking `deleteAttributes` on `CognitoUser` directly, but this is not ideal as outlined above.

**Comment by VetBoard** [comment]
+1

**Comment by hideokamoto** [comment]
Hi team!
I think the feature is very good for us 👍 

So I've made a new PR to add it.
feat: delete user attributes #7342

Thanks.

**Comment by cwomack** [comment]
Closing this issue out due to #7342 and implementation of the `deleteUserAttributes`.
