### ISSUE TITLE
Log bug against aws-amplify use of componentWillReceiveProps instead of getDerivedStateFromProps

### ISSUE THREAD

**Issue by kanjiz1** [aws-amplify/amplify-js#3120]
**Describe the bug**
In reference to `aws-amplify-react-native/src/Auth/ConfirmSignUp.js`

https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react-native/src/Auth/ConfirmSignUp.js

This react component still implements `componentWillReceiveProps` whereas this has been deprecated since React 16.3. This class should be updated to use `getDerivedStateFromProps`. This probably applies to all the Auth components.

**To Reproduce**
1. Implement an Auth workflow using AWS-Amplify
2. When confirm sign up screen appears, the "username" field is blank

**Expected behavior**
The username field should be pre-filled, because the user just signed up on the previous screen.

**Actual behavior**
The field is blank.

**Smartphone:**
 - Tested on iPhone 8
 - iOS 12.1

**Comment by sonufrienko** [comment]
_React Native + TypeScript + Jest_
I got a warning:

> Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
>     
> Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
>     
> Please update the following components: ConfirmSignUp

**Comment by dantasfiles** [comment]
+1

**Comment by melodymorgan** [comment]
samsies `"react-native": "0.61.2",`

**Comment by rsahil** [comment]
+1

**Comment by SeanRenet** [comment]
how do we fix this?  I am getting it also.

Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

Please update the following components: ConfirmSignUp

expo-cli:  3.11.1
"expo": "^36.0.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
"aws-amplify": "^2.2.1",
"aws-amplify-react-native": "^2.2.3",

**Comment by yunau** [comment]
I am getting the same warning.

Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: ConfirmSignUp
- node_modules/expo/build/environment/muteWarnings.fx.js:18:23 in warn
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:5864:19 in printWarning
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:5892:25 in lowPriorityWarning
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:6135:8 in ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings

**Comment by emersonhsieh** [comment]
I have the exact same issue as well when using `Authenticator` from `aws-amplify-react-native` without Expo. Here is my `package.json`:

```
  "dependencies": {
    "amazon-cognito-identity-js": "^3.2.2",
    "aws-amplify": "^2.2.2",
    "aws-amplify-react-native": "^3.2.0",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.5.3",
    "react-native-reanimated": "^1.7.0",
    "react-native-screens": "^2.0.0-alpha.32",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^4.1.0",
    "react-navigation-tabs": "^2.7.0"
  },
```
