### ISSUE TITLE
iPhone has denied the launch request. Internal launch error: process launch failed: failed to get the task for process 7661

### ISSUE THREAD

**Issue by Luckygirlllll** [aws-amplify/amplify-js#3124]
**Describe the bug**
I was making settings for `AWS Pinpoint` IOS, when I'm trying to run the app on my real device, I got an error: "iPhone has denied the launch request.
Internal launch error: process launch failed: failed to get the task for process 7661'

**To Reproduce**
1. Follow official guide for setting up Push Notification [AWS Pinpoint](https://aws-amplify.github.io/docs/ios/push-notifications-setup-apns),
2. Uncheck automatically manage signing 
3. Import provisioning profile

**Expected behavior**
App runs on the phone

**Desktop (please complete the following information):**
 - OS: IOS 

**Smartphone (please complete the following information):**
 - Device: Iphone
 - OS: IOS

**Additional context**
When I was using "Automatically manage signing" I was able to install an app on the phone, however, I was not able to receive any push notification from AWS Pinpoint in that case, I'm not sure whether or not "manual signing" is required or not.

**Comment by Luckygirlllll** [comment]
This problem was solved by going in `Xcode` to `Product -> Scheme -> Edit Scheme -> change Executable to Ask on Launch`

**Comment by haverchuck** [comment]
@Luckygirlllll  It sounds like this issue was solved, so I am closing the ticket.

**Comment by feudadrien** [comment]
This problem was solved for me by going in Xcode to **Runner -> Signing & Capabilities -> Signing (Debug) -> Check "Automatically Manage Signing"** +Add Team

**Comment by RicardoBarroso** [comment]
For me the problem was solved following the @Luckygirlllll suggestion but selecting an option with a different description (probably it was updated on the meanwhile):

`Xcode to Product -> Scheme -> Edit Scheme -> Wait for executable to be launched`

**Comment by TunvirRahman** [comment]
For me it was signing issue. I was trying to build in device with production provisioning profile.

**Comment by RicardoBarroso** [comment]
Despite my last answer which did work for a previous app now I've seen that on a new one the solution was to check **`Automatically Manage Signing`**.

Be aware that if your build scheme is using `Debug` or `Release` the corresponding provisioning profile on `Build Settings` also must be set to **`Automatic`**.

**Comment by RicardoBarroso** [comment]
I stumbled again on this issue and now **I was able to solve it despite NOT using `Automatically Manage Signing`**:

![Screenshot 2020-10-27 at 19 26 39](https://user-images.githubusercontent.com/2791179/97352630-cedbd900-188a-11eb-910f-2cefb3a608e0.png)

Like on the image above, **on your build scheme:**
* **uncheck `Debug executable`**; and
* **select `Automatically`.**
