### ISSUE TITLE
OAuth federation: Redirect User to the last requested page after authentication

### ISSUE THREAD

**Issue by rohitspujari** [aws-amplify/amplify-js#3125]
** Which Category is your question related to? **

Amplify Auth Module

** What AWS Services are you utilizing? **

Cognito

** Provide additional details e.g. code snippets **
I'm currently using OAuth support for Amplify that was recently released. The challenge I’m running into with this new flow is redirecting a user to the last page they requested. I learned that Cognito app-client doesn’t allow for wildcard entries. 

In this instance, I'm using `Auth.federatedSignIn({ provider: 'Google' })`.When a user tries to access `https://example.com?search=<random-guid>` in the unauthenticated state, the user gets presented with google prompt, after signing in, the user is redirected back to a `redirectSignIn` url, which is a static location `https://example.com`. I would instead want the user to be redirected back to the last page they requested, which is a `https://example.com?search=<random-guid>`. I also learned that there is a way to pass a `state` variable to Cognito, but struggling to find a way to do that in the using Amplify. Can you please provide a code snippet?

I'm using the authenticator component `<Authenticator
        theme={authenticatorTheme}
        federated={federated}
        hide={[Greetings]}
      />`
What I noticed is, this component with `Auth.configure({ oauth })` adds "Sign In with AWS" button (Hosted UI) to the SignIn form. How do I hide that without hiding the whole SignIn component?

Can you please help?

Thanks,
Rohit

**Comment by rohitspujari** [comment]
Additionally, I noticed when you use Authenticator component with federated, the auth flow kicked by the 'Sign In with Google" button that gets displayed doesn't add the user to the Cognito User pool. You have to either explicitly use `Auth.federatedSignIn({ provider: 'Google' })` or use Hosted UI's google button.

**Comment by haverchuck** [comment]
@rohitspujari - We don't currently support this out of the box, but we are marking this as a feature request.   Until then, you can try storing the url locally immediately before sign in, and then use Hub to listen for the signIn even and redirect after that point.

**Comment by edpike109** [comment]
@rohitspujari I am implementing social OAuth with user pools right now. The docs are confusing because the "User Pool" Social Federated IdP is so similar in name to the "Federated Identities" Authentication Providers. The documentation for the 2 should be separated. If you are trying to have people signup and signin with Google, *and* you want to have the user created in a cognito User Pool, you need to read the docs here https://aws-amplify.github.io/docs/js/authentication#social-provider-federation. FYI, the Authenticator object does not work with social/OAuth providers. If you activate social sign in, you have to use the hosted web UI (served up by your cognito instance) or write your own interface.

**Comment by zimmelbc** [comment]
I am looking to do the same in my React application. We had a working "deep link" solution where a component sets the route as an item in Cache and after a successful Auth.signIn call it gets the item from Cache then pushes the route to props.history for the redirect. However we are implementing federatedSignIn and on the callback I found the Cache key no longer exists. I would like the ability to pass the route to the federatedSignIn call and have it returned back with the JWT to be able to fetch and redirect the user.

**Comment by quyctd** [comment]
@sammartinez Sorry, I have a question, how can I use `customState` for redirect after `federatedSignIn`. I tried putting some URLs into `customState` but not like it works?

**Comment by andriworld** [comment]
@quyctd You can pass your page as a custom state

`Auth.federatedSignIn({provider: 'Google', customState: JSON.stringify(route)})`

and get it back in an auth event

```
Hub.listen('auth', ({payload: {event, data}}) => {

  switch (event) {
    case 'signIn':
      user = data
      break

  case 'customOAuthState':
      route = JSON.parse(data)
      // go to route
      break;
  }
})
```
