### ISSUE TITLE
How to make actionable notifications with AWS Pinpoint? 

### ISSUE THREAD

**Issue by Luckygirlllll** [aws-amplify/amplify-js#3126]
** Which Category is your question related to? **
AWS Pinpoint - push notifications 

** What AWS Services are you utilizing? **
AWS Pinpoint - push notifications 

** Provide additional details e.g. code snippets **
How to make actionable notifications with AWS Pinpoint? I want to add actionable notifications with 2 buttons in react-native (IOS) project, is that possible to implement this feature with AWS Pinpoint?

**Comment by haverchuck** [comment]
@Luckygirlllll  - What precisely do you mean by actionable?

**Comment by Luckygirlllll** [comment]
I mean actionable notifications like in IOS, with buttons, where user can do actions via notifications without opening the app. https://developer.apple.com/documentation/usernotifications/declaring_your_actionable_notification_types

**Comment by jordanranz** [comment]
@Luckygirlllll, I believe this is not natively supported in Amazon Pinpoint when using the 'Standard notification'. However, I believe this functionality is possible if you use a 'Silent notification' then present a local notification when the notification is received.

There is more documentation about standard and silent notifications in the following url under 'Writing messages':
https://docs.aws.amazon.com/pinpoint/latest/userguide/campaigns-message.html

If you are using React Native:
The functionality to present a actionable notification is built into `PushNotificationIOS`:
https://facebook.github.io/react-native/docs/0.40/pushnotificationios#presentlocalnotification

The function above can be called after receiving a Pinpoint notification in the `PushNotification.onNotification` callback:
https://aws-amplify.github.io/docs/js/push-notifications#working-with-the-api

If you are not using React Native, we can transfer this issue to the ios-sdk repo.

Let me know if this helps!

**Comment by Luckygirlllll** [comment]
@jordanranz I'm using react native, I don't see how is possible via PushNotificationIOS to define two actionable buttons in notification.
