### ISSUE TITLE
How to log errors to cloudwatch?

### ISSUE THREAD

**Issue by damianrr** [aws-amplify/amplify-js#3128]
** Which Category is your question related to? **

Logging errors

** What AWS Services are you utilizing? **

Amplify, AppSync, Cloudwatch

Hello, I'm wondering how could I log errors to Cloudwatch. By errors I mean not only AppSync errors but my own. I saw this: https://aws-amplify.github.io/docs/js/logger but all it does is console.log(...)

**Comment by gitzhouxinyu1** [comment]
Any updates?

**Comment by rpostulart** [comment]
I am also very curious how to do this? 

I can I stream application specific logs and aws services logs to cloudwatch to analyze them later?

**Comment by uxtx** [comment]
I saw this as well - I'm not sure there's any other option other than extend with a 3p solution, or roll your own lambda that pushes logs to cloudwatch via `cloudwatchlog.putLogEvents` https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudWatchLogs.html#putLogEvents-property or wherever else you want them to go. Any other thoughts?

**Comment by uxtx** [comment]
There's also this thread: https://github.com/aws-amplify/amplify-js/issues/3524
