### ISSUE TITLE
Local storage Tokens not being persisted after password change

### ISSUE THREAD

**Issue by camarrone** [aws-amplify/amplify-js#3129]
Hello guys,

I'm facing the same problem reported on #2865 .

In my case, the local storage tokens stop being persisted after changing the password for the user. After some time (perhaps days), it starts to works fine. I tested this on Chrome and Firefox.

The following method is used to change the password:

```
   changePassword(oldPassword, newPassord){
        let then = Ember.RSVP.defer(),
            cognitoUser = this.get('user');

        cognitoUser.changePassword('oldPassword', 'newPassword', function(err, result) {
            if (err) {
                Ember.Logger.debug('changePassword error: ', err);
                then.reject(err);
            }
            else{
                then.resolve(result);
            }
        });            
        return then.promise;
    }

```
I'm also running on circles on this one. 

Thanks very much for the help.

Cheers!

**Comment by haverchuck** [comment]
@camarrone Can you provide a bit more detail as to what is happening when you say the local storage tokens stop being persisted?

**Comment by camarrone** [comment]
@haverchuck I created the user one month ago and during this week I am testing the "forget password" process flow. After changing the password for any user on my pool I get this behaviour. The process that I'm following is:

1 - create the user using the API,
2 - Log in to the application,
3 - Log out  from the application,
4 - Reset my password using the "forget password" button.

In my Cognito User Pool I have a trigger for "custom message". This trigger calls a lambda function that sends the email with the link so the user can reset his/her password.

This process is working fine. The problem is when I log back in, **after reseting my password**, and try a refresh. The tokens just don't get persisted.  Please refer to this video: [https://youtu.be/SPreCmYS8H0](https://youtu.be/SPreCmYS8H0)

Thanks very much for the help.

**Comment by haverchuck** [comment]
Are you using one of our frontend framework packages?

**Comment by camarrone** [comment]
@haverchuck I'm using EmberJS and the following packages:

    "aws-amplify": "^0.4.4"
    "aws-sdk": "^2.373.0"

Thanks for the help!

**Comment by camarrone** [comment]
@haverchuck I have updated the packages to the latest version but I am still having the issue. Is there any workaround for this?

Thanks for the help.

**Comment by camarrone** [comment]
@haverchuck any update on this? 

Thanks very much for the help.

**Comment by camarrone** [comment]
I'm still having this issue. 

Has anyone faced something like this?

Thanks very much for the help!
