### ISSUE TITLE
UI Component Styling issue

### ISSUE THREAD

**Issue by mim-Armand** [aws-amplify/amplify-js#3131]
Hi and thank you for the AWSome Amplify!
**Describe the bug**
This is an small but somewhat important UI bug on the **Amplify React UI Components**,
As you can see in the screenshot bellow, there is a radio button that's not entirely visible and will confuse the user.

**To Reproduce**
1. Create a user that need to verify their email
2. Using Amplify UI Components, try to log-in using above user
3. After login you can see this screen

**Expected behavior**
The radio button label need to have a `color` other than white. 

**Screenshots**
<img width="611" alt="amplify-ui-comp-bug" src="https://user-images.githubusercontent.com/1734237/56389294-cc58e780-61ee-11e9-8cd1-b4f90e50b107.png">

**Desktop (please complete the following information):**
 - OS: MAC OS
 - Browser Chrome

**Additional context**
If possible I would like to make a **PR** to solve this bug?

**Comment by jordanranz** [comment]
Hey @mim-Armand, it seems that the radio button label is inheriting the color set in one of its parents style definitions. In this case, that color is white. 

We should have a more specific style for color on the radio input here. We'll have a code fix in for this by the end of the day. Thanks for submitting this.
