### ISSUE TITLE
API headers not signed when AWS_PROFILE env var is set

### ISSUE THREAD

**Issue by mikelduffy** [aws-amplify/amplify-js#3132]
I have a local node script used for testing our AWS Amplify app. Another product that I use requires the `AWS_PROFILE` env var to be set. This causes the local profile to be picked up while calling `Auth.signIn` which then causes a call to `API.graphql` to not set the `x-amz-date` and `x-amz-security-token` headers.

1. Run `export AWS_PROFILE=...` pointing to custom profile in ~/.aws/credentials
2. `Auth.Config({ identityPoolId: XXX, region: XXX, userPoolId: XXX, userPoolWebClientId: XXX })`
3. `Auth.signIn(...)`
4. `API.graphql(...)`
5. API gateway will throw a 403 error due to missing `x-amz-date` and `x-amz-security-token` headers

 - MacOS 10.14.3
 - aws-amplify 1.1.26

The fix is quite simple, just `unset AWS_PROFILE`, but it would be great if aws-amplify would ignore this env var or if it were documented somewhere.

**Comment by mikelduffy** [comment]
Another solution from a [comment](https://github.com/aws-amplify/amplify-js/issues/685#issuecomment-419905628) in #685 also works to solve this problem:
```
Amplify.configure(config)
const AWS = require('aws-sdk')
AWS.config.credentials = null
```

**Comment by haverchuck** [comment]
@mikelduffy -  Thanks.  The aws-sdk loads the credentials from the environment variable, and this sdk is one of the Amplify dependencies.  We are reviewing this issue.
