### ISSUE TITLE
Not Authenticated after Federated sign-in, can not update state with Hub.listen

### ISSUE THREAD

**Issue by richguan** [aws-amplify/amplify-js#3133]
** Which Category is your question related to? **
After returning from authorizing with Google, Auth.currentAuthenticatedUser() returns an error of 'not authenticated'. I use Hub to listen to 'auth' events, and it does pick it up. However, I can not set the state of my values via Hub.listen. I've listed main issues below.

** What AWS Services are you utilizing? **
Auth: Federated sigin-in and Hub

** Provide additional details e.g. code snippets **
```
const App = () => {
  const [ authState, setAuthState ] = useState('pending');

  // I've tried without async, and moving Hub.listen inside useEffect.
  Hub.listen('auth', async (data) => { 
    await setAuthState('success');
    // do stuff
  });

  useEffect(() => {
    if (authState === 'pending) 
      authenticate();
  }, [authState])

  const authenticate = async () => {
    try {
      const authData = await Auth.currentAuthenticatedUser(); 
      setAuthState('success');
    } catch(e) {
      await setAuthState('failure');
      console.log(e);
    }
  }

  if (authState === 'pending') {
    return(
      <div>
        <button onClick={() => Auth.federatedSignIn({provider: 'Google'})}>Sign in</button>
      </div>
    )
  } else {  
    return (
      <div>Success Page</div>
    )
  }
}
```

Main issue:
1. Auth.currentAuthenticatedUser() errors out with error 'not authenticated'. When I refresh the page, Auth.currentAuthenticatedUser() returns without any errors.
2. Setting state inside Hub.listen does not persist the state. I've tried the following, and noticed it does log the authState to 'success' once, before changing back to 'failure'.

```
  useEffect(() => {
    console.log(authState)
    if (authState === 'pending) 
      authenticate();
    Hub.listen('auth', async (data) => { 
      await setAuthState('success');
      // do stuff
    });
  }, [authState])
```

**Comment by powerful23** [comment]
@richguan from the code you provided I am assuming you are federating with the Cognito User Pool right? If so, did you check the doc: https://aws-amplify.github.io/docs/js/authentication#oauth-and-federation-overview

When using the hub, you should listen on the `signIn` event of the `auth` channel to tell whether you are logged in or not after redirected back from the third-party provider login page.

**Comment by richguan** [comment]
@powerful23 Yes, I followed the doc for information on how to implement it. The "do stuff" comment was where I had a condition for the `signIn` event. 

```
const onAuthEvent = async (payload) => {
    if (payload.event !== 'signIn')
      return;

    setAuthState('success');
```

**Comment by powerful23** [comment]
@richguan shouldn't the `setAuthState('success')` be called if `payload.event === 'signIn'`?

**Comment by richguan** [comment]
@powerful23 yes it should. Through my debugging, I know Hub receives 4 events (two from 'signIn' and two from 'cognito-something'). The reason I have left out specifying only for 'signIn' events is because I am unable to set the state on any of the Hub listen events.

**Comment by powerful23** [comment]
> The reason I have left out specifying only for 'signIn' events is because I am unable to set the state on any of the Hub listen events.

Sorry but why you are unable to set the state based on the Hub events?

Listening on the `signIn` event is the only way to tell if the user has successfully logged into Cognito.

**Comment by richguan** [comment]
@powerful23 I'm not exactly sure why I can't set the state in the Hub events. 

Current flow:
1. Redirect back to App from federated sign in ---> calls Auth.getCurrentAuthenticatedUser(). //Fails
2. setAuthState('failure). 
3. Hub.listen('auth'), ---> catches Auth and tries to setAuthState('success')

During this flow, setAuthState only picks up the first setAuthState() call. My guess is that useState hook is asynchronous call, so the first call negates the following calls.

Do I have the correct flow? 
- Should I call Auth.getCurrentAuthenticatedUser() whenever it redirects back to my app? 
The reason I make the call is so I can leave the page and come back without having to authenticate with Google again.

**Comment by powerful23** [comment]
@richguan you can store an flag into the localStorage indicating if the user is logging through OAuth. Set the flag when user clicks on the login button and remove the flag after receiving hub events. For example:
```js
useEffect(() => {
// if pending and the user is not logging through OAuth, then check the current user 
    if (authState === 'pending && !flag) 
      authenticate();
  }, [authState])

Hub.listen('auth', async (data) => { 
    // remove the flag
    // do stuff based on the data.payload.event
  });
```

While waiting for the auth events, you could disable the login button or render a loading page so the user won't be confused.

**Comment by richguan** [comment]
@powerful23 I've tried this before but used 'useReducer' to dispatch the change. I'll give it another shot and report back to you. Thanks for your help!

**Comment by richguan** [comment]
@powerful23 before I got to try the suggested implementation, the issue went away. I did do a bunch of refactoring in the past 2 days so may have removed the problem at some point. I will keep track of this, but will close the issue for now. Thanks for your help!
