### ISSUE TITLE
best practice to use S3object image in Angular?

### ISSUE THREAD

**Issue by NuruddinBadawi** [aws-amplify/amplify-js#3136]
** Which Category is your question related to? **
Amplify + angular + ionic

** What AWS Services are you utilizing? **
Storage S3

** Provide additional details e.g. code snippets **
I'm using an image inside the angular template like this
```
 <app-image-shell [mode]="'cover'" class="category-cover" animation="spinner"
                    [src]="'https://s3.'+category.cover.region+'.amazonaws.com/'+category.cover.bucket+'/public/'+category.cover.key">
        <app-aspect-ratio [ratio]="{w:75, h:49}">'
          <a class="category-anchor" [routerLink]="['/categories/', category.id]">
            <h2 class="category-title">{{category.name}}</h2>
          </a>
        </app-aspect-ratio>
      </app-image-shell>
```

is there another way I feel this way not practical

**Comment by haverchuck** [comment]
@NuruddinBadawi  - Try using our s3 image component, which is what our album component uses under the covers:

```
<amplify-s3-image
      framework="ionic"
      path="{{s3path}}"
      (selected)="onImageSelected($event)"
    ></amplify-s3-image-core>
  </div>
```

If you don't like this component, you can look at it's source code.
