### ISSUE TITLE
Authorization of API calls from Lambda (or other backend services).

### ISSUE THREAD

**Issue by siggi84** [aws-amplify/amplify-js#3138]
** Which Category is your question related to? **
API, Auth
** What AWS Services are you utilizing? **
Lambda
** Provide additional details e.g. code snippets **

I am using a GraphQL API authorized using Cognito User pool. This works great when interacting with the API from my React web app. I am however having difficulties interacting with the API from my backend infrastructure, such as Lambda functions. For example, I have defined one custom query in the AppSync API which uses a Lambda resolver. This lambda function needs to send another query on the API to fetch some user information to be able to perform its function. I still have not found a good way to grant the lambda function access to the API. So my question is basically, what is the best way to do so?

From what I have been reading, there seems to be two options:
1) I could manually create a user and then let the lambda function generate a JWT token each time. This seems to highly inefficient, and would require significant manual effort making CI/CD way more difficult.
2) Change the auth mode of AppSync to IAM and calculate the sigv4 signature in both frontent and backend. This would largely remove the benefits of using Amplify (at least the bits I am using), as the authentication workflow in the frontend would change significantly.

Am I missing something, or is this surprisingly difficult?

This might all have to do with a limitation of the AppSync service. See: https://forums.aws.amazon.com/thread.jspa?messageID=843543

**Comment by D2KX** [comment]
Multi-Auth support for AppSync is being worked on and will resolve this (I am waiting for it aswell!), but I don't see why using IAM for the time being would be too bad. You couple your Cognito User Pools with Cognito Identity Pools, and then just use the AWS_IAM auth mode for your AppSync API with Amplify in the frontend. On the backend, you don't have to do anything in the Lambda function, just grant your function the policy for the AppSync service in the IAM console. Depending on what special features you are using, there might be more work involved, but you shouldn't have to any manual Sigv4 signing, like ever, nowadays.
