### ISSUE TITLE
who do mutate data with uploading image in Vue ?

### ISSUE THREAD

**Issue by NuruddinBadawi** [aws-amplify/amplify-js#3140]
** Which Category is your question related to? **
Amplify - Storage -Vue

** Provide additional details e.g. code snippets **
I have a sample scheme for data has s3object,
when I do mutation for this data I want also to upload the image
```
  <amplify-connect
          :mutation="createCategoryMutation"
          @done="onCreateFinished"
        >
          <template slot-scope="{ loading, mutate }">
                    <form....
          </template>
  </amplify-connect>
```
```
{
computed: {
    createCategoryMutation() {
      // this.$Storage.put(this.cover.name, this.cover); 
      return this.$Amplify.graphqlOperation(createCategory, {
        input: {
          name: this.name,
          order: this.order,
          cover: {
            bucket: awsmobile.aws_user_files_s3_bucket,
            region: awsmobile.aws_user_files_s3_bucket_region,
            key: this.cover ? this.cover.name : ""
          },
          colSize: this.colSize
        }
      });
    }
}

```

how to do this?

**Comment by haverchuck** [comment]
@NuruddinBadawi  - Couldn't you use the onCreateFinished function to do the storage.put?

**Comment by NuruddinBadawi** [comment]
Top of this form there is table show the data from subscription, so after mutate the data, the subscription load the data in the table, but the image not loaded because not uploaded yet
So if i use onCreateFinished for upload the image,
The table not show the image until refresh the table, so in this way the subscription not useful in the table otherwise if there is away to make subscription work after upload finish
