### ISSUE TITLE
SignIn failure on ie10

### ISSUE THREAD

**Issue by logabstract** [aws-amplify/amplify-js#3141]
** Which Category is your question related to? **
Usage Question

** What AWS Services are you utilizing? **
AWS Cognito

** Provide additional details e.g. code snippets **

I'm using Amplify on ie10 and I have the following sign in failure:

![Screenshot_20190421_185839](https://user-images.githubusercontent.com/1031726/56477319-eeaa6980-6469-11e9-928a-b4f07be58b4d.png)

I tought the lack of support of window.crypto.getRandomValues() on IE10 was the cause due to ie11 does not have this problem., so I used window.crypto.getRandomValues() polyfill (https://github.com/kumavis/polyfill-crypto.getrandomvalues) , but it does not have any effect, same error.

The application is a basic react application setup with Create-React-App. The polyfill is applied like this:

**index.js**

**import './polyfills';**
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';

ReactDOM.render(<App />, document.getElementById('root'));

**polyfills.js**

window.crypto = { getRandomValues: require('polyfill-crypto.getrandomvalues') }

I don't know if I'm applying the polyfill incorrectly or if there's another error that makes signIn fail. Maybe Amplify does not support ie10 at all.

Thanks in advance.

The amplify log:
[DEBUG] 54:04.374 Amplify - amplify config[object Object] 
 [DEBUG] 54:04.374 I18n - configure I18n 
 [DEBUG] 54:04.374 I18n - create I18n instance 
 [DEBUG] 54:04.374 I18nundefined 
 [DEBUG] 54:04.374 AnalyticsClass - configure Analytics[object Object] 
 [DEBUG] 54:04.374 Parser - parse config[object Object],to amplifyconfig,[object Object] 
 [DEBUG] 54:04.374 AWSPinpointProvider - configure Analytics[object Object] 
 [DEBUG] 54:04.374 Hub - Dispatching to analytics with [object Object] 
 [DEBUG] 54:04.374 Analytics - on hub capsule analytics[object Object] 
 [DEBUG] 54:04.374 AnalyticsClass - current configuration[object Object] 
 [DEBUG] 54:04.374 AuthClass - configure Auth 
 [DEBUG] 54:04.374 Parser - parse config[object Object],to amplifyconfig,[object Object] 
 [DEBUG] 54:04.375 Hub - Dispatching to auth with [object Object] 
 [DEBUG] 54:04.375 Analytics - on hub capsule auth[object Object] 
 [DEBUG] 54:04.375 Hub - Dispatching to auth with [object Object] 
 [DEBUG] 54:04.375 Storage - storage configure called 
 [DEBUG] 54:04.375 StorageClass - configure Storage 
 [DEBUG] 54:04.375 Parser - parse config[object Object],to amplifyconfig,[object Object] 
 [DEBUG] 54:04.375 AWSS3Provider - Storage Options[object Object] 
 [DEBUG] 54:04.375 AWSS3Provider - configure Storageundefined 
 [DEBUG] 54:04.375 Storage - storage vault configure called 
 [DEBUG] 54:04.375 StorageClass - configure Storage 
 [DEBUG] 54:04.375 Parser - parse config[object Object],to amplifyconfig,[object Object] 
 [DEBUG] 54:04.375 AWSS3Provider - Storage Options[object Object] 
 [DEBUG] 54:04.375 AWSS3Provider - configure Storageundefined 
 [DEBUG] 54:04.375 API - configure API[object Object] 
 [DEBUG] 54:04.375 API - create API instance 
 [DEBUG] 54:04.375 RestClient - API Options[object Object] 
 [DEBUG] 54:04.375 PubSub - configure PubSub[object Object] 
 [DEBUG] 54:04.375 Interactions - configure Interactions[object Object] 
 [DEBUG] 54:04.376 XR - configure XR[object Object] 
 [DEBUG] 54:04.376 AbstractXRProvider - configure SumerianProvider[object Object] 
 [DEBUG] 54:04.376 AuthClass - configure Auth 
 [DEBUG] 54:04.376 Parser - parse config[object Object],to amplifyconfig,[object Object] 
 [DEBUG] 54:04.377 Hub - Dispatching to auth with [object Object] 
 [DEBUG] 54:04.377 Analytics - on hub capsule auth[object Object] 
 [DEBUG] 54:04.377 Hub - Dispatching to auth with [object Object] 
SEC7118: XMLHttpRequest for https://cognito-idp.us-east-2.amazonaws.com/ required Cross Origin Resource Sharing (CORS). 
192.168.0.10:4000
SEC7119: XMLHttpRequest for https://cognito-idp.us-east-2.amazonaws.com/ required CORS preflight. 
192.168.0.10:4000
SEC7118: XMLHttpRequest for https://cognito-idp.us-east-2.amazonaws.com/ required Cross Origin Resource Sharing (CORS). 
192.168.0.10:4000
SEC7119: XMLHttpRequest for https://cognito-idp.us-east-2.amazonaws.com/ required CORS preflight. 
192.168.0.10:4000
 [DEBUG] 56:03.972 AuthClass - signIn failure[object Object] 
 [DEBUG] 56:03.972 Hub - Dispatching to auth with [object Object] 
 [DEBUG] 56:03.972 Analytics - on hub capsule auth[object Object] 
 [DEBUG] 56:03.973 Credentials - getting credentials 
 [DEBUG] 56:03.973 Credentials - picking up credentials 
 [DEBUG] 56:03.973 Credentials - getting new cred promise 
 [DEBUG] 56:03.973 Credentials - checking if credentials exists and not expired 
 [DEBUG] 56:03.973 Credentials - need to get a new credential or refresh the existing one 
 [DEBUG] 56:03.974 AuthClass - Getting current user credentials 
 [DEBUG] 56:03.975 Hub - Dispatching to auth with [object Object] 
 [DEBUG] 56:03.976 AuthClass - Getting current session

**Comment by haverchuck** [comment]
@logabstract Thanks for posting.  I'm sorry, but we don't support IE 10 at this time.

**Comment by logabstract** [comment]
Please, @haverchuck can you tell me why this error happens on IE10 ? It is about random value generation on the client? I tested this with the cognito-identity example on [https://github.com/amazon-archives/amazon-cognito-identity-js/tree/master/examples/babel-webpack](url) and it works on IE10, but its deprecated. Unfortunatelly IE10 is a requeriment in my project, do you know how can possibly make it work ? maybe with cognito custom authentication ? or triggers?

**Comment by JLWalsh** [comment]
I'm leaving this comment for people who absolutely need to support IE10 like me. The sign in fails because the second request Amplify sends (`RespondToAuthChallenge`) doesn't work as it should. I think that the problem is crypto-related, as said by @logabstract. So my workaround is fairly simple: instead of using the `USER_SRP_AUTH`, I used the `USER_PASSWORD_AUTH`, which doesn't involve the `RespondToAuthChallenge` to sign in. Note that this may not be fit to your needs, as I **think** that `USER_SRP_AUTH` encrypts the password using a key sent from Cognito, which is why it has to be done in two calls. So if you're sending this data over a plain `HTTP` connection, I don't think I'd be a good idea to switch to `USER_PASSWORD_AUTH`. In my case, the password will be sent over `HTTPS`, so I won't need this.

Here's the one-liner fix :tada::
```javascript
Auth.configure({ authenticationFlowType: "USER_PASSWORD_AUTH" });
```
