### ISSUE TITLE
Storage.list Returning Empty Array

### ISSUE THREAD

**Issue by tmoore23** [aws-amplify/amplify-js#3143]
**Describe the bug**
I have created a react native app but I am running into an issue where I am not able to list my directories and content of the directories in the my S3 bucket. I am using the following code:

```
componentWillMount(){
    console.log('Calling S3');
    console.log(Auth.currentCredentials());

    Storage.list('/', { level: "public" })
  		.then (result => console.log('Result:', result)) // {key: "test.txt"}
		.catch(err => console.log(err)});
}
```

**Expected behavior**
To see directories and contents of directories in S3 bucket.

Related issue:  #2828

**Comment by josephpaulmckenzie** [comment]
I just now figured this out as I was having the same issue. Take out the forward slash in Storage.list() and make it like  `Storage.list('', { level: "public" })
  		.then (result => console.log('Result:', result)) // {key: "test.txt"}
		.catch(err => console.log(err)});`
When you have it like  '/' it adds another / at the end of the url and breaks it. Seems like a bug to me

**Comment by tmoore23** [comment]
@josephpaulmckenzie tried that and still not able to get it working.

**Comment by tmoore23** [comment]
After turning on logs, found the following:

if path provided
`[DEBUG] 58:15.430 AWSS3Provider - list <path>/ from public/<path>`

if path not provided
`[DEBUG] 01:21.831 AWSS3Provider - list from public/`

Then after manually adding `public/` folder within bucket, things started working and able to see list of items and folders.

**Comment by jordanranz** [comment]
@tmoore23, is this issue safe to close?

**Comment by AdrianRamzes** [comment]
I had the exact same problem recently. But I didn't want to create a `public` folder in a bucket.
I've solved it by adding `customPrefix` parameter to the request configuration:
```
    const requestConfig = {
        customPrefix: {
            public: '',
            protected: '',
            private: ''
        },
        level: 'private',
        cacheControl: 'no-cache',
    };

    keys = await S3.list('', requestConfig) as any[];
```
then it works like a charm :)

**Comment by ahmed1** [comment]
@AdrianRamzes, your solution worked for me, thanks!

**Comment by vincent38wargnier** [comment]
Hi, I had a similar issue, and the solution for me is not mentioned here.
My problem was that I was trying to retrieve data readable by guests, so in public accès.
To get public data, you will need to create a "**public/**" folder inside your bucket, and Storage.list('') will return all the elements contained in this folder only.
![image](https://user-images.githubusercontent.com/33725800/147343216-b251f351-c271-48e6-a3e1-71b42eaf5afd.png)

That's why all the other files contained in the bucket outside of the "public" folder are not returned.

**Comment by bharattech** [comment]
> Hi, I had a similar issue, and the solution for me is not mentioned here. My problem was that I was trying to retrieve data readable by guests, so in public accès. To get public data, you will need to create a "**public/**" folder inside your bucket, and Storage.list('') will return all the elements contained in this folder only. ![image](https://user-images.githubusercontent.com/33725800/147343216-b251f351-c271-48e6-a3e1-71b42eaf5afd.png)
> 
> That's why all the other files contained in the bucket outside of the "public" folder are not returned.

Hi Vincent,

Your post helped me. Thanks

**Comment by conor909** [comment]
I have the same issue, I'm uploading files from a lambda function, but trying to access them by `Key` from the app fails with `NoSuchKey` `404`.  Yet I can see the files in the bucket from the console.

Lamda:
```js
      const { S3Client, PutObjectCommand } = require('@aws-sdk/client-s3')

      const s3Params = {
        Bucket: STORAGE_MY_BUCKETNAME,
        Key: 'my-folder/my-file.pdf',
        Body: newDocument
      }
      const command = new PutObjectCommand(s3Params)
      await s3.send(command)
```

App:
```js
import { Storage } from 'aws-amplify'
const file = await Storage.get('my-folder/my-file.pdf', { download: true }) // NoSuchKey
```
