### ISSUE TITLE
AWS Pinpoint - IOS app crashes when push notification is clicked (ExpoKit)

### ISSUE THREAD

**Issue by Luckygirlllll** [aws-amplify/amplify-js#3144]
**Describe the bug**
IOS app crashes when push notification is clicked (ExpoKit) and when app is closed. when app is open, app crashes immediately once  push notification is received. 

**To Reproduce**
1. Send test push notification from AWS Pinpoint console 
2. Open notification on real device 

**Expected behavior**

App is not crashing 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: IOS

**Smartphone (please complete the following information):**
 - Device: Iphone 7S

**Additional context**
That's expoKit project.

**Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

```
componentDidMount(){
    PushNotification.onNotification((notification) => {
      console.log('in app notification', notification);
      // required on iOS only (see fetchCompletionHandler docs: https://facebook.github.io/react-native/docs/pushnotificationios.html)
      notification.finish(PushNotificationIOS.FetchResult.NoData);
    });

    PushNotification.onRegister((token) => {
      console.log("token ", token)
      AsyncStorage.setItem('deviceToken', token);
      });

    PushNotification.onNotificationOpened((notification) => {
        console.log('the notification is opened', notification);
    });
  }
```

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by jordanranz** [comment]
Hey @Luckygirlllll,

Is it possible for you to provide some debug/console log information?

**Comment by Luckygirlllll** [comment]
I found the problem, [this problem](https://github.com/expo/expo/issues/3223l) relates to ExpoKit projects, the solution of this problem is to add `experienceId` inside the `data` object, it should look like this: 

```
  "message": {
   ...
    },
    "data": {
    ...
      "experienceId": "@your_community_name/your-expo-project", // for EXPO`
      "experienceId": "your-expo-project", // for DETACHED`
    }
  }
}```
```
