### ISSUE TITLE
How to use Amplify to make requests to my API Gateway Endpoint?

### ISSUE THREAD

**Issue by codecitrus** [aws-amplify/amplify-js#3149]
** Which Category is your question related to? **
- Configuration
- General Documentation
- API Gateway

** What AWS Services are you utilizing? **
- API Gateway

** Provide additional details e.g. code snippets **
We have a React Native app that wants to communicate with an API Gateway endpoint set up to use IAM as an authorization method. Our IAM role is set up to use an external OIDC IdP. Currently, I am debating between two approaches:

**Approach A**:
1. Use the `aws-sdk`'s `STS.assumeRoleWithWebidentity` method to exchange our identity token from our IdP for temporary security credentials.
2. Somehow use Amplify to sign the request to the API Gateway endpoint using the new temporary security credentials.

**Approach B**:
1. Setup endpoint in `aws_exports` file by adding the `API.endpoints` configuration value
2. Create `credentialsConfig = new AWS.WebIdentityCredentials({arn, token, ...})`
3. Somehow configure Amplify to use `credentialsConfig` **only when talking to this API**

I want to know which approach is best. I am very unclear on how to actually implement steps **A.2** as well as **B.2/B.3**. In the case of Approach B, we have the following complications:
1. We have already called `Amplify.configure`
2. So if we try to call it again, will the components we set up originally stop working. The app currently uses Amplify for other things, so I fear calling configure will screw up all that.

From the looks of the online documentation, it seems `Amplify` can only really use one set of credentials at a time. Is multiple sets of credentials within the same app a supported use case? Is calling `Amplify.configure` before every Amplify operation I need to do expensive?
I feel this more conceptual considerations are left out in the documentation in favor of a "it just does everything automatically" explanation.

**Comment by jordanranz** [comment]
Hey @codecitrus,

I am not sure I can advise you on which Approach is better as I am not very well versed in the functionality of STS. I can recommend that if you want to use Amplify you can setup an [OIDC provider for Cognito Identity Pools](https://docs.aws.amazon.com/cognito/latest/developerguide/open-id.html) then use the [Auth.federatedSignIn](https://aws-amplify.github.io/docs/js/authentication#identity-pool-federation) method on our Auth category to get the credentials used to call API Gateway (via the Amplify API category).

As for step **A.2** and **B.3** or for using another set of credentials to sign the request, this is currently not directly supported inside of the API category. I will mark this as a feature request as this seems to be a common use case. The recommended way to do this today is utilize the [Signer module inside of our Amplify core package to sign](https://github.com/aws-amplify/amplify-js/blob/master/packages/core/src/Signer.ts#L262) the request and then simply call `fetch` with that request. Here is an example of this workflow:
https://github.com/aws-amplify/amplify-js/blob/master/packages/xr/src/Providers/SumerianProvider.ts#L124-L138

Hope this helps.

**Comment by codecitrus** [comment]
Hi,

Thanks for getting back. I am going forward with using the `Signer` module. However, while I am able to make requests to my API Gateway (service: 'execute-api') endpoint using Postman, the requests from the `Signer.sign()` method return `'403` error. 

On an initial look, I see the following possible discrepancies between how SIGV4 is supposed to be implemented and the code in the Signer module.

1. In `canonical_request` method, the `sorted_queries` does not URI Encode the values of the query parameters as is required by [SIGV4](https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html) 

> To construct the canonical query string, complete the following steps: ...
> URI-encode each parameter name and value according to the following rules...

2. Also in `canonical_request` method, the path of the request is URI encoded, but is not normalized to lowercase. So if you have an mixed-case path, this would not seem to conform to SIGV4. In addition, the path is only uri-encoded once instead of twice.

> Normalize URI paths according to RFC 3986. Remove redundant and relative path components.
> Each path segment must be URI-encoded twice

**Comment by undefobj** [comment]
@codecitrus upleveling a bit, have you looked at the REST functionality in the `API` category? https://aws-amplify.github.io/docs/js/api#using-rest

This will automatically sign your requests to API Gateway using short term credentials from Cognito.
