### ISSUE TITLE
Auth.signIn gives "NetworkError" in a react application

### ISSUE THREAD

**Issue by jedkass** [aws-amplify/amplify-js#3151]
I have created one user in my user pool for this app, but keep getting the error message below (after setting `Amplify.Logger.LOG_LEVEL = 'DEBUG'`).

<img width="679" alt="Screen Shot 2019-04-23 at 2 11 47 PM" src="https://user-images.githubusercontent.com/34748050/56605279-c8074280-65d1-11e9-8ab8-8213919e6166.png">

I am configuring Amplify as follows. I have a `config.js` that looks like this (but filled in with my AWS info):
```
export default {
      cognito: {
        REGION: "XX-XXXX-X",
        USER_POOL_ID: "XX-XXXX-X_abcd1234",
        APP_CLIENT_ID: "a1b2c3d4e5f6g7h8i9j0k1l2m3",
        IDENTITY_POOL_ID: "XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab"
      }
};
```

And then this is my `Amplify.configure()` call:
```
import Amplify from "aws-amplify";
import config from "./config"

// initialize AWS Amplify
Amplify.configure({
    Auth: {
      mandatorySignIn: true,
      region: config.cognito.REGION,
      userPoolId: config.cognito.USER_POOL_ID,
      identityPoolId: config.cognito.IDENTITY_POOL_ID,
      userPoolWebClientId: config.cognito.APP_CLIENT_ID
    }
  });
```

I haven't been able to find any other questions that have assisted in resolving this. Any help would be much appreciated.

**Comment by jordanranz** [comment]
Hey @jedkass,

You should be able to gather more debug information from the browser Network tab and see which request is failing. Could you provide me a screenshot of this?

**Comment by jedkass** [comment]
Well that helped me realize the page kept reloading (I'm guessing before the async request to Cognito was done) due to the fact that I wasn't calling `event.preventDefault()` when hitting submit. It's always something stupid...thanks for your help!
