### ISSUE TITLE
Getting onClick events from the <Authenticator> component

### ISSUE THREAD

**Issue by mkondel** [aws-amplify/amplify-js#3153]
** Which Category is your question related to? **
Using aws-amplify-react's <Authenticator> component.

** What AWS Services are you utilizing? **
Cognito with both user and identity pools for login.

** Provide additional details e.g. code snippets **
This is in my render():
```
<Authenticator
  onStateChange={ respondToAuthStateChange } 
/>
```
I would like to know when a user clicks on the SignIn button. The onStateChange method only runs after the authentication attempt. I want to show a loading indicator while this is happening.

**Comment by undefobj** [comment]
Have you looked into the Hub module: https://aws-amplify.github.io/docs/js/hub
You can both listen to Auth events in Hub as well as dispatch your own custom events to a channel.

**Comment by mkondel** [comment]
That looks promising, I will try it. Thank you, @undefobj

**Comment by mkondel** [comment]
I tried the Hub events, but it does nothing when the "Sign in" button gets clicked. There is an event on the 'auth' channel that fires, but it is equivalent to `Authenticator.onStateChange()`. Meaning it fires after the authentication process completes ('signIn' event).

Any further help is much appreciated. Below is my code using Hub and react hooks:

```javascript
  const handleHubEvents = data => {
    console.log(`handleHubEvents() start.`)
    const { payload } = data;
    console.log('A new auth event has happened: ', data.payload.data.username + ' has ' + data.payload.event);
  }

  useEffect(() => {
    console.log(`useEffect() start.`)
    // set up Amplify event listeners
    Hub.listen('core', handleHubEvents)
    Hub.listen('auth', handleHubEvents)
    Hub.listen('api', handleHubEvents)
    Hub.listen('analytics', handleHubEvents)
    Hub.listen('interactions', handleHubEvents)
    Hub.listen('pubsub', handleHubEvents)
    Hub.listen('storage', handleHubEvents)
    Hub.listen('xr', handleHubEvents)

    return () => {
      console.log(`useEffect() cleanup.`)
      Hub.remove('core', handleHubEvents)
      Hub.remove('auth', handleHubEvents)
      Hub.remove('api', handleHubEvents)
      Hub.remove('analytics', handleHubEvents)
      Hub.remove('interactions', handleHubEvents)
      Hub.remove('pubsub', handleHubEvents)
      Hub.remove('storage', handleHubEvents)
      Hub.remove('xr', handleHubEvents)
    }
  })
```

And this is what i get in the console:
```
XHR POST https://cognito-idp.us-east-1.amazonaws.com/
XHR POST https://cognito-idp.us-east-1.amazonaws.com/
XHR POST https://cognito-identity.us-east-1.amazonaws.com/
XHR POST https://cognito-identity.us-east-1.amazonaws.com/
XHR POST https://cognito-idp.us-east-1.amazonaws.com/
XHR POST https://cognito-idp.us-east-1.amazonaws.com/
handleHubEvents() start. 
A new auth event has happened:  admin has signIn
```

What I am looking for is an event that would fire before any of the POST requests are made. Ideally this would be a UI event, not an XHR.

**Comment by jordanranz** [comment]
Hey @mkondel,

Looking at the code [here](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Auth/SignIn.jsx#L76), it seems there is no triggered 'loading' event you can listen to with Hub before making any XHR request. That being said, I believe your use case of showing a loading indicator is still possible. Can you elaborate on this use case some more?

- Are you attempting to modify the current loading indicator?
- Are you trying to use your own loading component?
- What is the step by step for how your UI should look?

There is a way to hide the existing default Loading component and pass your own component in. You'd probably want to extends the existing Loading component then pass it in to the Authenticator.

`<Authenticator
    hide={Loading}>
   <CustomLoading>
</Authenticator>
`

Here are relevant docs links:
https://aws-amplify.github.io/docs/js/authentication#using-the-authenticator-component
https://aws-amplify.github.io/docs/js/authentication#customize-your-own-components

**Comment by mkondel** [comment]
* _Are you attempting to modify the current loading indicator?_ 
This is a lead I need to explore, as I **don't** see any built in indicators when using `<Authenticator>`. I will investigate what that is supposed to look like and why I don't see it in my app.

* _Are you trying to use your own loading component?_
Yes, I have an indicator that is part of my SSR index.html. In my components I show/hide it when something is loading. I will attach a gif where you can see a big purple spinner. That is what I wanted to display while `<Authenticator>` is waiting for the auth request to complete.

* _What is the step by step for how your UI should look?_
 -- load /login page
 -- enter user/pass
 -- click the Signin button
 -- show a spinner
 -- wait for auth to complete
 -- hide the spinner

Please have a look at this capture. I refresh the page to show what my spinner looks like. When clicking the Signin button, nothing happens for a few seconds. This is the part that should be covered with my custom spinner. Note also how there is no loading indicator from the Amplify's components.

![Peek 2019-04-25 18-01](https://user-images.githubusercontent.com/3288757/56771352-59b6b180-6784-11e9-9e90-be3e9e4c1e91.gif)

**Comment by jordanranz** [comment]
@mkondel, Could you post the version of `aws-amplify` and `aws-amplify-react` you are using.

It is odd that you don't see the Loading on the component for the Authenticator. 

Ideally, you can override the render method of the existing Loading component (by extending it and including it as a child on the Authenticator component mentioned [here](https://aws-amplify.github.io/docs/js/authentication#customize-your-own-components)) and simply render your own UI in place of it. This would be still contained within the Authenticator component, so it would just replace the content in the section with what you define.

**Comment by mkondel** [comment]
@jordanranz, thank you for your help. I am using these versions:
```
"aws-amplify": "1.1.26"
"aws-amplify-react": "2.3.6"
```
I will set up a new vanilla react project to verify that I can see the stock loading indicator. Is it just a `<Paper>` component that says `Loading...` ?

**Comment by mkondel** [comment]
I set up a repo and a Cognito user pool with one user. Here is the code: https://github.com/mkondel/amplity-auth-test. User/pass is `admin/Password1!`, so no one has to register in my pools. This is a bare bones React project, and all I have done is add `aws-amplify-react` to it. Is there supposed to be a loading indicator when I click Signin?

**Comment by jordanranz** [comment]
@mkondel, I see. Looks the SignIn component does not make an auth state change when it is loading. Instead it just sets the internal component state of 'loading' to true (which disables the sign in button)

If additionally we triggered an auth state change, the Paper/Built-in Loading component would appear. If we were to add this triggered 'loading' auth state change, you would be able to then override/customize the Loading component provided by aws-amplify-react. With this change you would also be able to implement your own logic to listen to this auth state change. The question is should we trigger a global 'loading' state change or a component specific loading state change (e.g 'signInLoading'). 

What would you prefer in this case? I will bring this up with the team to discuss.

**Comment by jordanranz** [comment]
Correct, you could listen to the state change with Hub. It would be an API specific loading event. For example, when clicking the Sign In button exemplified above, it executes Auth.signIn and would trigger an event like `signIn-loading` on the 'auth' channel.

**Comment by LucasAndrad** [comment]
What happened with this issue @jordanranz ?
