### ISSUE TITLE
How to use local state and cognito

### ISSUE THREAD

**Issue by austinamorusocfc** [aws-amplify/amplify-js#3154]
What is the recommend way of using local state management in GraphQL and remote GraphQL calls with cognito as the auth layer? 

** Which Category is your question related to? **
AWS AppSync client / Apollo Client

** What AWS Services are you utilizing? **
AWS AppSync 
AWS Cognito

** Provide additional details e.g. code snippets **
Currently I'm using an old version of 
    "aws-appsync": "^1.3.5-link-effect.2"
    "aws-appsync-react": "^1.1.5-link-effect.2"

I'm wondering if link effect is still require?
I know the newer version of apollo has local state built in. But I am unaware if there is a way to make apollo work with cognito.

**Comment by jordanranz** [comment]
Closing this in favor of:
https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/369
