### ISSUE TITLE
Amplify Auth with Hosted UI process Stripe OAuth url

### ISSUE THREAD

**Issue by johanrin** [aws-amplify/amplify-js#3157]
**Describe the bug**
In my Angular project, I have configured AWS Amplify with [OAuth and Hosted UI](https://aws-amplify.github.io/docs/js/authentication#oauth-and-hosted-ui).

Everything is working fine. When I want to connect with Google, I am redirected back with an url like http://localhost:4200/?code=de79bfa4-xxxxxx&state=2xxxxxx which is well handled by the AWS Amplify Hub.

Now, I want to configure Stripe Connect in my project which also use an [OAuth connection flow](https://stripe.com/docs/connect/standard-accounts).

So I configure my OAuth link as defined in the documentation by adding a link as below:

    <a class="stripe-connect" href="https://connect.stripe.com/oauth/authorize?response_type=code&client_id=ca_xxxxxx&scope=read_write"><span>Connect with Stripe</span></a>

**Problem**
I am redirected back with an url like http://localhost:4200/stripe?scope=read_write&code=ac_xxxxxx

Unfortunately, **this url is also processed by Amplify** and I got the following error message :

> zone.js:1152 POST https://[domain].amazoncognito.com/oauth2/token 400
> core.js:15724 ERROR Error: Uncaught (in promise): Error: invalid_grant
> Error: invalid_grant

**To Reproduce**
1. Configure the sample repository with Amplify Auth Hosted UI
2. Edit the Stripe client_id in `stripe.component.html`
3. Start the project
4. Connect with google
5. Navigate to Settings
6. Click on the link 'Connect with Stripe'
7. On the Stripe form, click 'Ignore this account form'
8. See the error

**Expected behavior**
Amplify do not proceed the Stripe url

**Screenshots**
<img width="960" alt="Capture d’écran 2019-04-24 à 01 07 48" src="https://user-images.githubusercontent.com/13972080/56621684-b2276b00-662d-11e9-90cf-3a45a7c67c00.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave v 10.14.4
 - Browser Chrome
 - Version 73.0.3683.103

**Additional context**
N/A

**Sample code**
Sample repo available : [https://github.com/JohanRin/sample-amplify-stripe.git](https://github.com/JohanRin/sample-amplify-stripe.git)

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

> Failed to load resource: the server responded with a status of 400 ()
> ConsoleLogger.js:88 [DEBUG] 11:58.755 AuthClass - Error in cognito hosted auth response Error: invalid_grant
>     at OAuth.<anonymous> (OAuth.js:143)
>     at step (OAuth.js:52)
>     at Object.next (OAuth.js:33)
>     at fulfilled (OAuth.js:24)
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
>     at Object.onInvoke (core.js:17299)
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:390)
>     at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:150)
>     at zone.js:889
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
> ConsoleLogger.js:88 [DEBUG] 11:58.756 Hub - Dispatching to auth with  Object
> ConsoleLogger.js:88 [DEBUG] 11:58.756 Hub - Dispatching to auth with  Object
> ConsoleLogger.js:88 [DEBUG] 11:58.756 Hub - Dispatching to auth with  Object
> ConsoleLogger.js:88 [DEBUG] 11:58.756 Hub - Dispatching to auth with  Object

**Comment by undefobj** [comment]
With the OAuth flows in Amplify and the code-grant flow, once you get redirected back from the 3rd party Amplify will automatically parse the URL to retrieve the code and use this to retrieve credentials from the 3rd party /token endpoint. I'm unsure if Stripe has this flow in a similar manner to Google, Facebook, etc. If not then it would not work in the same manner.

**Comment by JohanRin** [comment]
Stripe seems to have this workflow (see below for more details).

**My question**
How to configure Amplify to process my Stripe URL?
Is there something planned with the Amplify CLI or do I need to configure it manually?

------

From the [Stripe documentation](https://stripe.com/docs/connect/standard-accounts)

<img width="778" alt="screenshot-1" src="https://user-images.githubusercontent.com/13972080/56728213-98337880-6752-11e9-999d-fd24f43ddff5.png">

Focus on:

<img width="640" alt="screenshot-2" src="https://user-images.githubusercontent.com/13972080/56728251-a71a2b00-6752-11e9-94cf-2477d37365e9.png">

<img width="646" alt="screenshot-3" src="https://user-images.githubusercontent.com/13972080/56728271-aed9cf80-6752-11e9-8bf3-3b0e170ef7f3.png">

**Comment by undefobj** [comment]
Ok I see. Amplify does not support `Auth.federatedSignIn` using a 3rd party as the federation endpoint which is what is outlined above. The token endpoint is only supported via Cognito User Pools OAuth endpoint at this time. However you can federate with User Pools using social providers like Google, Facebook, and Login with Amazon as well as a 3rd party OIDC provider, so one thing you might try is to setup Stripe as an OIDC provider in your User Pool: https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-oidc-idp.html

I cannot guarantee this would work though as it is dependent on Stripe's OIDC support.

**Comment by JohanRin** [comment]
I contacted the Stripe support who told me they do not support OIDC for now.

**My question**
Is is possible to add exceptions or even filters to Amplify for not automatically parse URL?

Stripe support answer:
> Stripe Connect's OAuth API is based upon OAuth 2.0 but it does not implement [OpenID Connect](https://openid.net/specs/openid-connect-core-1_0.html) at this time. When a user is redirected back to your endpoint after signing up or authenticating their existing account with Stripe, you will need to make a request to Stripe to complete the connection process and obtain their [account credentials](https://stripe.com/docs/connect/standard-accounts#token-request).

**Comment by JohanRin** [comment]
any update?

**Comment by undefobj** [comment]
At this time it's not possible. This is a feature request for the future.

**Comment by IVB107** [comment]
Also having this same issue. Would appreciate if this issue is addressed with the next update for aws-amplify

**Comment by rush86999** [comment]
same problem any workaround? should we just remove social provider sign in and keep regular sign in?

**Comment by rush86999** [comment]
Will amplify stop parsing url if we deactivate federated signin from amplify-cli? Anyone who could reply to this answer would be great as I m stuck right now

**Comment by ericclemmons** [comment]
Thanks everyone for the research!  Indeed, authenticating with Stripe via Cognito would be a feature request, but Amplify handling the URL because Stripe also uses `code` seems like a bug:

https://github.com/aws-amplify/amplify-js/blob/ab08e38e22801e3a212f299057ecc9670fae5633/packages/auth/src/Auth.ts#L1811-L1823

I'm going to bring this up with the team with the recommendation that we track _both_ sides of the OAuth flow (so that it works for federated sign-in with Google, but ignores Stripe).

**Comment by byronsorrells** [comment]
Running into the same issue with Intuit. 

Apparently Intuit does support OpenID "... Intuit’s OAuth 2.0 authentication implementation, which conforms to the OpenID Connect specification and is OpenID Certified. To explore this workflow interactively, experiment with the OAuth 2.0 playground."

However, I don't want to have to rely on that / cognito support for it. I want to be able to manually handle auth flows with `code` in the URL.
