### ISSUE TITLE
Storage.get with Cognito validation

### ISSUE THREAD

**Issue by muriloSanto** [aws-amplify/amplify-js#3160]
** Which Category is your question related to? **
Storage and Cognito

** What AWS Services are you utilizing? **
S3, Cognito

** Provide additional details e.g. code snippets **

I want to check if the token passed with Storage.get is still valid, or invalidate via cognito logout. 
Is it possible to avoid one user copy URL generated with Storage.get and another user open it? It can be on bucket policy, or anything.

**Comment by undefobj** [comment]
Amplify will automatically refresh tokens for you if they have expired, so a client check isn't necessary before performing a storage action. If you wish to invalidate a client session you can do a global sign-out at the service which will prevent the tokens from refreshing until the user re-signs in. If there was a reason to prevent them from signing in again you could always perform the global sign-out at the service and then disable the account.
