### ISSUE TITLE
amplify-angular: authState as BehaviorSubject in amplify.service.ts

### ISSUE THREAD

**Issue by mattiLeBlanc** [aws-amplify/amplify-js#3165]
Hi,

It would be helpful if we change the `_authState` Subject to be a BehaviorSubject @ https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-angular/src/providers/amplify.service.ts#L35

I am piping the `authStateChange$` observable in my CanActivate guard and with the subject it will only work on page load since that is when the value is emitted. When I navigate to other routes and back to a route guarded by the CanActivate, the pipe will not work since the Subject didn't emit a new value.

I am happy to make a PR for this?

**Comment by clundberg1** [comment]
This is absolutely essential for Angular apps, not only because if you subscribe after the Subject emitted a value, you won't be notified until a new value is emitted, but also because Subjects don't hold the current value, which means you can't get the value synchronously, whilst with BehaviourSubjects, you can!

**Comment by mattiLeBlanc** [comment]
I resolved it by adding my own `behaviorSubject` in my service and linking it to the stateChange:

```
 
  private authState = new BehaviorSubject<AuthState>({ state: null, user: {} }); 
  private onDestroy = new Subject(); 
  public authState$: Observable<AuthState> = this.authState.asObservable(); 

...
...
...

    this.amplifyService.authStateChange$ 
      .pipe( 
        takeUntil(this.onDestroy) 
      ) 
      .subscribe( authState => { 
        this.authState.next(authState); 
      }); 
```

**Comment by mattiLeBlanc** [comment]
@jordanranz  any update on this one?
