### ISSUE TITLE
How to implement User Authentication (SignIn) using Custom Attributes

### ISSUE THREAD

**Issue by b-tiwari** [aws-amplify/amplify-js#3175]
**Which Category is your question related to?**
User Authentication (SignIn) using Custom Attributes

### Question
My use case is, 
1. At the time of registration, we ask user to set up a PIN. We store this PIN as a custom attribute in user pool. 
2. After sing up, User signs in successfully using userId/password and logs to the app
3. Inside app, when user wants to perform some restricted action (e.g. change some sensitive settings) , we want to prompt user an additional validation UI to validate his/her PIN.

(**note:** we are not planning for MFA support as some of our users may not have cell phones)

With Amplify, once user signs in, I know we would have the PIN in the `Auth.user` available on client side and we can setup some UI for User to enter PIN and the match it with the `Auth.user.attributes.pin` . So client side PIN validation seem to be easy.

However, it would be better if this PIN validation can be done on the AWS side. Does Amplify provides any such functionality , like `Auth.signIn` authenticates with userId and password, is there any function available to authenticate user with custom attributes? Or any other recommended approach for such use case?

**What AWS Services are you utilizing?**
AWS Cognito, UserPools

**Comment by manueliglesias** [comment]
Hi @b-tiwari 

Would [Custom Authentication Challenge Lambda Triggers
](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-challenge.html) work for your use case?

**Comment by b-tiwari** [comment]
hi @manueliglesias , thanks for your reply. I am on the same path , trying to use Custom Auth Lamba triggers. While I got everything set, I am now running into [this issue](https://github.com/aws-amplify/amplify-js/issues/3159) with Amplify signIn method when using Custom_Auth

**Comment by koolkav1** [comment]
@b-tiwari did you find out the issue? I am facing a similar issue https://github.com/aws-amplify/amplify-js/issues/3215

**Comment by b-tiwari** [comment]
@koolkav1 , sorry for late reply, sorry I was moved to some other assignment and didn't get chance to further work on this after I ran into [this issue](https://github.com/aws-amplify/amplify-js/issues/3159). I would probably get back to this next week and would let you know if I find something
