### ISSUE TITLE
Forgot Password and Sign up displayed even if disabled

### ISSUE THREAD

**Issue by jitsunen** [aws-amplify/amplify-js#3186]
### Describe the bug
I had reported this issue some time back (Issue # [2238](https://github.com/aws-amplify/amplify-js/issues/2238)) it's fix did not have seemed to work. I am describing the problem here again.

I have disabled Forgot Password and Sign Up functionality by using the following code in my react app:

`export default withAuthenticator(App, true, [<SignIn />, <RequireNewPassword/>]);`

### Expected behavior
On my local server, the Forgot Password and Sign Up links don't show on login page, however, once I build the app and deploy to S3, the Forgot Password and Sign Up appear on the login page.

### Desktop (please complete the following information):

Smartphone (please complete the following information):

### Additional context
I am using aws-amplify@1.1.26, aws-amplify-react@2.3.6

**Comment by manueliglesias** [comment]
Hi @jitsunen 

I just tried your code on a fresh app created with `create-react-app` and did a `yarn build && npx serve -s build` and the production mode bundle worked as expected.

What bundler are you using?

**Comment by jitsunen** [comment]
Hi @manueliglesias , appreciate your quick response and trying out the scenario.

I am using webpack. Do I need to do any changes?

Cheers

**Comment by jitsunen** [comment]
I just deleted node_modules, did a yarn install and the code worked as expected. Thank you so much!.

Cheers
