### ISSUE TITLE
Using Hosted UI with Ionic / Cordova application

### ISSUE THREAD

**Issue by martin-slater** [aws-amplify/amplify-js#3188]
It is currently possible but difficult to integrate Ionic and Cordova based applications with Amplify Auth using HostedUI to allow social login.  The scenario I needed to implement was social authentication with Facebook and username/password authentication on Android / IOS. Where as integrating into a browser based application is relatively straightforward the documentation around mobile integration is sparse to say the least. To get the this to work with the amplify ionic integration I needed to 

* Call `Auth.federatedSignIn({provider: CognitoHostedUIIdentityProvider.Facebook })` to launch the hosted UI in the mobile browser and set a custom URL scheme for the callback (i.e. myapp://auth/)

* Use the Deeplink cordova plugin (https://github.com/ionic-team/ionic-plugin-deeplinks) to intercept custom url schemes in application

This correctly launches the hosted UI, allows facebook authentication and then returns to the application with the URL containing 'code' and 'state parameters.  Then in a deeplink handler I then can pass this return URL to complete this part of the flow using `;(Auth as any)._handleAuthResponse(deeplink.$link.url)`.

At this point it will handle the auth response and exchange the code for a token and then try to redirect to the `redirectSignIn` url as before and this will throw an exception

`Error: Failed to execute 'replaceState' on 'History': A history state object with URL 'myapp://app/auth/' cannot be created in a document with origin` from Auth.ts:1553

this can also be worked around by just catching this exception and then retrieving the user credentials.

**What would be lovely**
It would be nice to be able to 

* avoid the need to use the any cast to call into _handleAuthResponse with a first class public function on the Auth class to perform this duty.

* allow specifying a seperate URL for internal redirection after auth flow is complete that would override  `redirectSignIn` parameter for this if specified

* improve the documentation to explain how to implement this in more detail

I am happy to help contributing patches for any of these if there is agreement to improve the situation here and the best approach to it.

**Comment by manueliglesias** [comment]
Hi @martin-slater 

Thanks! These are interesting points, we'll be reviewing them and updating this issue. CC @undefobj

**Comment by undefobj** [comment]
> * avoid the need to use the any cast to call into _handleAuthResponse with a first class public function on the Auth class to perform this duty.

Unfortunately we cannot expose this for you to control the URL parsing rather than the library performing this task at this point as it would be a breaking change for existing customers who are relying on this functionality. We looked at it in depth and tried several strategies with the new OAuth functionality but it's just not possible. We're considering it for a future major release but that will be sometime out.

**Comment by martin-slater** [comment]
@undefobj  How about exposing a method to override the urlListener that detects the location has changed? This way existing behaviour could be left unchanged and we could pass in a custom urlListener that amplify can register its callback against and we can fire back at an appropriate time?

**Comment by undefobj** [comment]
I'd probably be against doing that, raising the API surface area is more complexity and opposite what we're trying to accomplish with Amplify. The better solution is to fix the existing behavior but since it would be a breaking change we'll need to do it in a future major release.

**Comment by martin-slater** [comment]
Fair enough, I am mainly interested in this use case just working and what I have does that well enough for now even if a little dirty.
