### ISSUE TITLE
Update GraphQL to 14

### ISSUE THREAD

**Issue by xenophilicibex** [aws-amplify/amplify-js#3190]
**Is your feature request related to a problem? Please describe.**
I have conflicting GraphQL versions which results in this error in production (not local dev):
```
Uncaught Error: Cannot use e "__Schema" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
```
This is because I am using `aws-amplify-react` which has `aws-amplify` as a peer-dependency. `aws-amplify` pulls in `@aws-amplify/api` which has a `graphql` dependency locked in to `0.13.0`. This release is over a year old, and `14.0` was in Aug '18, over 6 months ago.
I'm also using Apollo which requires 14.

**Describe the solution you'd like**
I would like for `@aws-amplify/api` to update its graphQL dependency version.

**Describe alternatives you've considered**
- I've tried using yarn's `resolutions`: `14.0.0` - this appears to work locally but not when it's deployed.
- Not using `aws-amplify` and instead pulling in the module we need: `@aws-amplify/core`, `@aws-amplify/auth` & `@aws-amplify/ui` (https://github.com/aws-amplify/amplify-js/wiki/Amplify-modularization) but this doesn't work because `aws-amplify-react` has a peer dependency with `aws-amplify` and even if I get around that, it uses `@aws-amplify/api` which is the part that includes `graphql`.
- I can't revert to using graphQL 0.13 because we already have a system in place built on Apollo and reverting that would be far too much work.

**Additional context**
The only thing I can think of doing now is removing our dependency on `aws-amplify-react`, and then using our own UI for the sign in. That then I can go the modular AWS approach and avoid `@aws-amplify/api`.

**Comment by manueliglesias** [comment]
Hi @xenophilicibex 

I am labeling this as a feature request, thanks!

**Comment by D2KX** [comment]
While I agree that I would like to see it updated, I don't see why this would be a problem when using Apollo. aws-mobile-appsync-sdk-js which is the package used for using AppSync with the Apollo client is also locked to GraphQL 0.13.0 (and Apollo client 2.4.x, which allows GraphQL 0.13.0).

**Comment by wjramos** [comment]
I'm also seeing this problem in non-production builds

**Comment by wjramos** [comment]
I'm also encountering issues with this and would like to see this change

**Comment by stanislav-sidorov** [comment]
same problem
aws-amplify-react-native@2.1.19 requires a peer of graphql@0.13.0
@apollo/react-hooks@3.1.0 requires a peer of graphql@^14.3.1
@apollo/react-common@3.1.0 requires a peer of graphql@^14.3.1

**Comment by ErickMwazonga** [comment]
++
same problem
@apollo/react-hooks@3.1.0 requires a peer of graphql@^14.3.1
@apollo/react-common@3.1.0 requires a peer of graphql@^14.3.1

**Comment by sammartinez** [comment]
@xenophilicibex GraphQL version is upgraded to version 14.0.0. Resolving this request as complete.
