### ISSUE TITLE
How to pass query params with oauth configuration.

### ISSUE THREAD

**Issue by anis-shaikh** [aws-amplify/amplify-js#3194]
Hello, 
I am trying to do faderatedSignin by Google/Facebook using oauth and hosted UI.
Everything is working fine but after successful signin it's redirecting back to my redirect url with no query params.

For example, I have signin page with url "http://localhost:3000/?name=xyz". In the signin component I have added two buttons for Google and Facebook and calling faderatedSignin function with provider. After that it's redirecting to google/facebook page and I am able to do signin through it. After successful signin it's redirect back to "http://localhost:3000/". But I am not able to access query param (?name=xyz). Please check the below code and do the needful.

OAuth configuration:
```
const awsmobile = {
    "aws_project_region": "XX",
    "aws_cognito_region": "XX",
    "aws_user_pools_id": "XX",
    "aws_user_pools_web_client_id": "XX",
    "oauth": {
        "domain": "XX.amazoncognito.com",
        "scope": [
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};
```
SignIn Component:
```
import React, { Component } from 'react';
import Amplify, { Auth, Hub } from 'aws-amplify';
import awsmobile from './aws-exports';
Amplify.configure(awsmobile);

class SignIn extends Component {
  
      constructor(props) {
          super(props);
  
          Hub.listen("auth", ({ payload: { event, data } }) => {
            console.log('data:---', data);
            switch (event) {
              case "signIn":
                  console.log('signin:---');
                  break;
              case "signOut":
                  console.log('signout:---');
                  break;
            }
          });
          this.state = {
             
          };
  
      }
  
  
      render() {
        
              return (
                  <div>
                      
                        <button onClick={() => Auth.federatedSignIn({provider: 'Google'})}>Open Google</button>
                        <button onClick={() => Auth.federatedSignIn({provider: 'Facebook'})}>Open Facebook</button>
                        <button onClick={() => Auth.federatedSignIn()}>Open Hosted UI</button>
                        <button onClick={() => Auth.signOut()}>Sign out</button>
                   
                  </div>
              );
          }
        
      }
  

export default SignIn;
```

**Comment by manueliglesias** [comment]
Hi @anis-shaikh 

This is because your redirectSignIn url is defined without the param:

```json
{
"redirectSignIn": "http://localhost:3000/"
}
```

You can try changing that in both your config and the user pool config

**Comment by anis-shaikh** [comment]
Hey @manueliglesias, my params is not fixed. It's dynamic, so how can we change it in the user pool config/ oauth config.

**Comment by manueliglesias** [comment]
@anis-shaikh I see, this is a good use case for the `state` param (see [AUTHORIZATION endpoint](https://docs.aws.amazon.com/cognito/latest/developerguide/authorization-endpoint.html))

Currently, Amplify generates a pseudo-random `state` for CSRF protection purposes and it is not exposed or modifiable. 

I think it would be useful to provide you own state when calling `Auth.federatedSignIn()`.

I am tagging this as a feature request.

**Comment by anis-shaikh** [comment]
@manueliglesias I tried to pass it through oauth config as state, but it's getting encoded and can't decode it after successful siginin.

`const awsmobile = {
    ---,
    ---,
    "oauth": {
       	---,
       	---,
        "state": "?name=xyz"
    }
};`

**Comment by manueliglesias** [comment]
@anis-shaikh The encoded value you are seeing is the pseudo-random state Amplify generates, currently there is no way to provide your own and that's what the feature-request is in this case: *Being able to specify the state to use in an oauth flow*

**Comment by anis-shaikh** [comment]
@manueliglesias Thanks for the information, will wait for this feature.
