### ISSUE TITLE
Using amplify-connect how do i know my query has been returned in vue?

### ISSUE THREAD

**Issue by thebspin** [aws-amplify/amplify-js#3202]
I need to know when my graphqlOperation is being complete. I am using amplify-connect and passing on the computed prop with the right call in the :query tag. Doing pagination in my vue app, i need to adjust some data with responses from that call, because now the call is always behind the actual creation of my data table.

**Comment by manueliglesias** [comment]
Hi @thebspin 

This is currently not possible, looks like you are interested in getting a custom event similar to the one emitted when a mutation is done, but for queries, is that correct?

https://github.com/aws-amplify/amplify-js/blob/47c7cfdd6308b14a1f7673e339680021c2a8764f/packages/aws-amplify-vue/src/components/api/graphql/Connect.vue#L129-L131

**Comment by thebspin** [comment]
Hi @manueliglesias 

Yes that is correct! If i knew when all my data is retrieved i could then i access the data. Currently i am doing a work around but it feels kinda dirty and hacky.

I have the call to my graphql db in a method using ``this.$Amplify.API.graphql`` and i call that method in created(). This is because this allows me to use then() on my method so that i know when my call is done. In the then() i set ``this.dataTable = res`` and i could also do other stuff like getting the number of results to use that for my pagination. And then using the vuetify data tables (but i guess any visual vue framework works like this) uses the binded dataTable var ``<v-data-table :items="dataTable">``. And i setup my pagination, that needs to know the limit, current page and how many items are there in total.

I think having an event would just allow me to listen to that event, and setup the pagination info when the event is done because that way i know my call from the computed prop is done. And i can bind the ``:items`` from ``v-data-table`` to my computed prop that has the call, just like the amplify-vue docs explain.

(I guess the docs specifically show the usage of computed props for a reason right? Or am i perfectly fine to use this from a method without any disadvantage? Still keeps the hacky workflow for me with the then() though.)

**Comment by jkeys-ecg-nmsu** [comment]
Why can't you broadcast your own event in the then() block?

**Comment by thebspin** [comment]
> Why can't you broadcast your own event in the then() block?

That's what i originally thought and tried myself. But.. https://eslint.vuejs.org/rules/no-async-in-computed-properties.html

If you read it and read the extra info it can lead to results not being shown. In theory it should happen very little but every time is 1 too many times for me.
