### ISSUE TITLE
Angular User management UI component. 

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-js#3205]
**Is your feature request related to a problem? Please describe.**
No, it is more of a feature request. At the moment it would be a lot of work to do this yourself, and it seems like something most admin type websites would need.

**Describe the solution you'd like**
It would be great if you could manage Cognito User Pool users from within your Angular app. The same way you would add users to you Cognito User Pool via the AWS Console. 

**Describe alternatives you've considered**
Write it myself, but that seems a bit much. For now I am managing the application users from within the AWS Cognito User Pool. But that won't work forever.

**Additional context**
Well the idea would be to have the same kind of UI as the Cognito User Pool. 

Thanks. 
Regards.

**Comment by manueliglesias** [comment]
Hi @jarrettj 

Please join the discussion happening at aws-amplify/amplify-cli#766 😄

**Comment by jarrettj** [comment]
Thanks @manueliglesias !
