### ISSUE TITLE
Authenticator component intermittently stuck in "loading" state on page refresh

### ISSUE THREAD

**Issue by jkeys-ecg-nmsu** [aws-amplify/amplify-js#3206]
**Describe the bug**
Sometimes, on the "first refresh" of a long-running Amplify site, the `Authenticator` component -- which we are leveraging using the higher-order component `withAuthenticator` -- gets stuck in "loading" state. This causes the default loading component to render. On the "second refresh", the loading state is successfully bypassed and the state is "signedIn".

**To Reproduce**
1. Create an Amplify project using withAuthenticator
2. Refresh the page, and observe that the Authenticator component's state is "loading"
3. If error does not happen for short-lived page, try letting the page stay open for longer before refreshing (>1 hr). 

**Expected behavior**
The session should be gracefully refreshed on reload if necessary, and the loading component should not be rendered.

**Screenshots**
![image](https://user-images.githubusercontent.com/22964702/57043727-a89d9480-6c25-11e9-887b-0b0290bbd86b.png)

**Additional context**
the authState prop for each subcomponent is also "loading".

**Comment by MTibby92** [comment]
likely related to this bug ticket: https://github.com/aws-amplify/amplify-js/issues/3195

**Comment by jordanranz** [comment]
This is fixed in the latest unstable version of `aws-amplify-react`:
https://github.com/aws-amplify/amplify-js/commit/cc75ea176e05e8c3e483317f98f8f299599117d9

We will publish this to our npm stable version early next week.
