### ISSUE TITLE
Password reset code instead of link: could the reset code contain URL-unsafe characters

### ISSUE THREAD

**Issue by ak37165** [aws-amplify/amplify-js#3208]
** Which Category is your question related to? **
reset code

** What AWS Services are you utilizing? **
AWS Cognito

** Provide additional details e.g. code snippets **
To send a password-reset link (instead of a code that the user must manually copy-paste), prior suggestions suggest embedding the reset code in a link using a custom message lambda trigger.
(such as in https://github.com/amazon-archives/amazon-cognito-identity-js/issues/360).

But this will NOT work if the reset contains characters that are not allowed in URLs or are reserved for specific uses (such as ?, &, %). Is there documentation on what characters the reset code might contain?

The documentation says the reset code follows the regex pattern [\S]+ (at https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ConfirmForgotPassword.html) but that is not sufficient.

**Comment by powerful23** [comment]
@ak37165 Hi, I have verified from Cognito team that the reset code should only contain digits.

**Comment by ak37165** [comment]
Thanks, that works perfectly!
