### ISSUE TITLE
Ract-Native(0.59+) is missing  AsyncStorage lib

### ISSUE THREAD

**Issue by gilador** [aws-amplify/amplify-js#3209]
**Describe the bug**
while running my react-native app i get this:

> Async Storage has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/async-storage' instead of 'react-native'

it seems **amplyfy-js** is dependent on a no longer exiting dependencies such as AsyncStorage in [react-native-0.59](https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#deprecated), e:g
node_modules/@aws-amplify/auth/lib/Auth.js:41 -> /node_modules/@aws amplify/core/lib/RNComponents/reactnative.js:18 
![image](https://user-images.githubusercontent.com/8309205/57088144-508c8e00-6d0a-11e9-9ba6-f09e78079655.png)

**To Reproduce**
1. build react-native app () 
2. run on device
3. connect to the react-native debugger
4. See error in the log

**Expected behavior**
the code should not break over missing  AsyncStorage 

**Smartphone:**
 - Iphone 6
 - OS: 12.2
 - xcode 10.2.1

As i understand you use  AsyncStorage  as a fall back so i would suggest you to load that lib only if needed.

**Comment by manueliglesias** [comment]
Hi @gilador 

Thank you for the report, we definitively need to discuss how we want to move forward when `AsyncStorage` is fully deprecated.

**Comment by GutteApps** [comment]
@manueliglesias we get this error even when providing our own storage class, do you know why?

**Comment by manueliglesias** [comment]
@Gautierrr I think you are getting a warning (e.g. the yellowbox), is that correct? Once you dismiss it, the app should still work

**Comment by gilador** [comment]
It iw a warning but i cant dismiss it, its persistent

**Comment by gilador** [comment]
any thoughts?

**Comment by jessedoyle** [comment]
@gilador - It's kludgy, but you can disable YellowBox notifications on a per-warning basis:

```js
// probably in App.js
import { YellowBox } from 'react-native';

YellowBox.ignoreWarnings([
  'Async Storage has been extracted from react-native core and will be removed in a future release. ',
]);
```

See the [docs](https://facebook.github.io/react-native/docs/debugging#warnings) for more details.

**Comment by gilador** [comment]
10x, but its already disabled

**Comment by jessedoyle** [comment]
@manueliglesias 

> Thank you for the report, we definitively need to discuss how we want to move forward when AsyncStorage is fully deprecated.

Should this discussion begin now?

What do you think about providing a dependency injection pattern via the configuration?

i.e.
```js
import MyAsyncStorage from '@react-native-community/async-storage';

Amplify.configure({
  ...
  Dependencies: {
    AsyncStorage: MyAsyncStorage, // would default to react-native provided AsyncStorage
  },
  ...
});
```

This could also make unit testing trivial as a reasonable double could be provided for hard dependencies during test runs.

**Comment by undefobj** [comment]
@manueliglesias and I are taking a longer look at our storage capabilities right now, including offline features, and will look at this as part of that effort. I don't have an ETA on when we'll have a new recommendation but will look at the suggestions above.

**Comment by dilantha111** [comment]
well I guess we need to open this again, 
I tried this one, but it didn't work, 
````
import MyAsyncStorage from '@react-native-community/async-storage';

Amplify.configure({
  ...
  Dependencies: {
    AsyncStorage: MyAsyncStorage, // would default to react-native provided AsyncStorage
  },
  ...
});
```
