### ISSUE TITLE
Cannot read property 'preventDefault' of undefined - Auth Library Error

### ISSUE THREAD

**Issue by adriangabardo** [aws-amplify/amplify-js#3211]
**Describe the bug**
I stayed off a company project using Cognito Auth through Amplify for about a month, and now trying to use it again, I receive an error on my authentication page.
`Cannot read property 'preventDefault' of undefined`

I went into the Amplify function in node_modules and altered the line
`event.preventDefault();` to `if (event) event.preventDefault();`
in the function `SignIn.prototype.signIn = function (event) {`
of the file `Auth/SignIn.js` and my login page is working again.

**To Reproduce**
1. Setup Cognito authentication through Amplify
2. Use the Library's SignIn function, in this way:
`import { SignIn as CognitoSignIn } from 'aws-amplify-react';`
`this.signIn()`
3. Try to login.

**Expected behavior**
Once I try to login, using the SignIn function, I should be able to login, without seeing the preventDefault error.

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.3
 - Browser: Chome
 - Version: Version 73.0.3683.103 (Official Build) (64-bit)

**Additional context**
**Sample code**
Dependencies in Package.JSON: 

```
    "aws-amplify": "^1.1.16",
    "aws-amplify-react": "^2.2.3",
    "prop-types": "^15.6.2",
    "react": "^16.6.3",
    "react-dom": "^16.6.3",
    "react-router-dom": "^4.3.1",
    "react-scripts": "^2.1.5",
```

**Comment by manueliglesias** [comment]
Hi @adriangabardo 

Thanks for the report! 😄  Is this something you'd be interested to send a contribution for?

https://github.com/aws-amplify/amplify-js/blob/47c7cfdd6308b14a1f7673e339680021c2a8764f/packages/aws-amplify-react/src/Auth/SignIn.jsx#L66-L68

**Comment by adriangabardo** [comment]
Yeah I could definitely fix this :) Can you guide me through how?

**Comment by bishonbopanna** [comment]
Ran into the same issue, can a fix be provided or work around please ?

**Comment by adriangabardo** [comment]
@bishonbopanna have a read-through my description again. The fix is already written there :)

**Comment by bishonbopanna** [comment]
Thanks @adriangabardo, missed reading it! Updating the SignIn.js in the aws-amplify-react project with the if condition resolved it - Hope it gets fixed soon and a new version gets rolled out.

**Comment by adriangabardo** [comment]
I'm fixing it now and doing a PR

**Comment by adriangabardo** [comment]
@manueliglesias I don't seem to have permission for the PR though

**Comment by Cerwym** [comment]
You can change the handler of your onClick method the pass through the event as the required argument;

`onClick={event => super.signIn(event)}`
