### ISSUE TITLE
Didn't receive subscription if using alias

### ISSUE THREAD

**Issue by joseph-d-p** [aws-amplify/amplify-js#3213]
**Describe the bug**
Subscription not working with alias

**To Reproduce**
Using two Appsync consoles (one for mutation and one for subscription), copy sample code below.

**Expected behavior**
Will be able to receive subscription using alias

**Sample code**
1st console for subscription:
```
subscription OnPutItem($id: ID!) {
  item: onPutItem(id: $id) {
    id
    data
  }
}
```
2nd console for mutation:

(with alias)
```
mutation PutItem($data: String!) {
  item: PutItem(data: $data) {
    id
    data
  }
}
```

or (without alias)

```
mutation PutItem($data: String!) {
  PutItem(data: $data) {
    id
    data
  }
}
```

**What works**
```
subscription OnPutItem($id: ID!) {
  onPutItem(id: $id) {   // without alias
    id
    data
  }
}
```
```
mutation PutItem($data: String!) {
  PutItem(data: $data) {
    id
    data
  }
}
```
This will output:
```
data: {
  onPutItem { // not using alias - this is my goal to make this `item`
    id
    data
  }
}
```

I'm using `aws-amplify` for subscriptions with the code above. For quick test, I used AppSync's console.

**Comment by ablbol** [comment]
Was this issue fixed?  I am using aliases with subscription but it does not work.
