### ISSUE TITLE
Add attribute for isSignInDisplayed to config for amplify-sign-up

### ISSUE THREAD

**Issue by moon0440** [aws-amplify/amplify-js#3216]
**Is your feature request related to a problem? Please describe.**
I have another link to SignIn. With that already displayed, it is redundant/confusing to have the signin link is still available in the UI component SignUp.vue. This is much like #1993 but for  SignUp.vue

**Describe the solution you'd like**
I would like to be able to disable the signin feature on the component
aws-amplify-vue/src/components/authenticator/SignUp.vue with a boolean 'isSignUpDisplayed'
as:
`<amplify-sign-up v-bind:signUpConfig="signUpConfig"></amplify-sign-up>`

```
export default {
  data() {
    return {
        signUpConfig: {
          isSignInDisplayed : false //default true
        }
    };
  }
} 
```
Done by adding a v-if="options.isSignInDisplayed" on wrapping span tag in SignUp.vue
```
<span v-bind:class="amplifyUI.sectionFooterSecondaryContent" v-if="options.isSignInDisplayed">
        {{$Amplify.I18n.get('Have an account? ')}}
        <a v-bind:class="amplifyUI.a" v-on:click="signIn">{{$Amplify.I18n.get('Sign In')}}</a>
</span>
```

**Comment by jordanranz** [comment]
FYI, we have started an RFC for discussing a proposed UI refactor that will allow for more flexibility inside of the components. Feel free to comment if you have any further asks on this topic.

https://github.com/aws-amplify/amplify-js/issues/3279

**Comment by tannerabread** [comment]
Closing as this issue is outdated but there have been updates to the Authenticator component for Vue which can be found [here](https://ui.docs.amplify.aws/vue/connected-components/authenticator). Any further inquiries about UI components should be directed at the [UI repo](https://github.com/aws-amplify/amplify-ui).

Thank you
