### ISSUE TITLE
Logger - Can it log to file instead of console?

### ISSUE THREAD

**Issue by YikSanChan** [aws-amplify/amplify-js#3219]
As title

**Comment by powerful23** [comment]
@YikSanChan No. I will mark this as feature request.

**Comment by YikSanChan** [comment]
What are suggested alternatives before the feature request fulfilled? Want to have reliable logging such as https://www.slf4j.org/manual.html for production

**Comment by YikSanChan** [comment]
As this is a feature request then I don't think stale bot should close this

**Comment by sammartinez** [comment]
@YikSanChan Can you provide a little more context if this is still a valid use case for you. What is the reason you would want this in a file output then a console output?

**Comment by YikSanChan** [comment]
to gain the similar experience as using log4j or slf4j
