### ISSUE TITLE
Disable sign In, enable only sign up?

### ISSUE THREAD

**Issue by avishayil** [aws-amplify/amplify-js#3226]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
Hi,

I'm looking for a way to have a "Kill Switch" (Preferably on the Cognito side) that will allow only sign ups, but not sign ins (Until I approve sign ins to the applications).

The reason i'm doing this is for a beta sign up, which I don't want to allow sign in, but I'll be able to easily allow it once the time has come.

Any suggestions?

**Comment by powerful23** [comment]
@avishayil one way you can do it is to add a pre authentication trigger in the cognito console which will run a lambda function before user signing in where you can reject all the requests.  https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html

**Comment by avishayil** [comment]
Thanks!
