### ISSUE TITLE
Default Prefix for phone number, or override?

### ISSUE THREAD

**Issue by michaelcuneo** [aws-amplify/amplify-js#3227]
** Which Category is your question related to? **

Amplify.JS Authenticator HoC

** What AWS Services are you utilizing? **

Amplify, Authenticator, Cognito Auth.

** Provide additional details e.g. code snippets **

Hey guys... Just a quick question about the aws-amplify-react Authenticator HOC... I have people signing up from within my organisation, and they're failing to remember to change the +1 to +61 because we're in Australia, and it's causing no end of hassle, because I am spending half my time deleting peoples accounts and emailing them to remind them that we're +61, not American...

Is there a way within the Authenticator HOC to push a default prefix. Or would I have to rewrite the entire component to get an override for this?

**Comment by michaelcuneo** [comment]
Problem solved. I found configuration.

**Comment by OArnarsson** [comment]
@michaelcuneo 
> Problem solved. I found configuration.

A good thing to do here is post the config you found for future reference 😉
