### ISSUE TITLE
AWS Amplify PubSub expected 2 arguments

### ISSUE THREAD

**Issue by borch84** [aws-amplify/amplify-js#3228]
** Which Category is your question related to? ** AWS Amplify PubSub

** What AWS Services are you utilizing? ** iotgateway

** Provide additional details e.g. code snippets **
Hi, I am implementing the pubsub example here: https://aws-amplify.github.io/docs/js/pubsub#publish-to-a-topic on my angular application. So far I am getting messages, however when I compile my app I get this message:

`error TS2554: Expected 2 arguments, but got 1.`

From the amplify example, pubsub only receives 1 argument, in this case the topic. However from the API reference pubsub receives a second argument `Providertoptions` 
https://aws-amplify.github.io/amplify-js/api/classes/pubsub.html#subscribe

I would like to know if I need to always include these provideroptions and what are the options I should include within providertoptions? I tried to search for more information regarding these provider options but I did not find it.

Thanks in advance.

**Comment by powerful23** [comment]
@borch84 Hi are you using the latest version of amplify? Also we have updated the doc yesterday to fix an error in the pubsub category, can you retry?

**Comment by borch84** [comment]
Hi @powerful23 I just updated aws-amplify and aws-amplify-angular:

```
$ cat package.json | grep aws-amplify
    "aws-amplify": "^1.1.27",
    "aws-amplify-angular": "^3.0.2",
```
I recompiled my app but I am getting this error:

```
ng] ERROR in src/app/home/home.page.ts(109,7): error TS2345: Argument of type '{ next: (data: any) => void; error: (error: any) => void; close: () => void; }' is not assignable to parameter of type '(value: any) => void'.
[ng]   Object literal may only specify known properties, and 'next' does not exist in type '(value: any) => void'.
[ng] 
```

**Comment by borch84** [comment]
Hi @powerful23 could this also related to: https://github.com/aws-amplify/amplify-js/issues/3212 ? 
I am working on the same project and that issue also raised.
