### ISSUE TITLE
Auto Login with OAuth without clicking on a button

### ISSUE THREAD

**Issue by marioaae** [aws-amplify/amplify-js#3232]
** Which Category is your question related to? **
Authentication

** What AWS Services are you utilizing? **
Cognito User Pools

** Provide additional details e.g. code snippets **
I'm developing a react js app in a corporate environment, that will authenticate users with cognito which ultimately is linked to a Azure AD application. I manage to do it with no problem using  a button that looks like this:

```
<Button variant="outline-secondary" onClick={this.props.OAuthSignIn();}>
</Button>
```

The snippet above works fine because I'm importing:

`import { withOAuth } from 'aws-amplify-react';`

I'm opening this question because I would like to avoid a button. My application has no meaning if the user is not authenticated instead of pressing a button I want the user to be signed in automatically when the page loads.

So far I tried to do it in the componentDidMount without success:

```
componentDidMount = () => {
    Auth.currentAuthenticatedUser()
      .then(user => {
        // Do nothing because the user is authenticated already
        }})
      .catch(err => {
        // Authenticate the user because the user is not authenticated yet
        this.props.OAuthSignIn()
        
      });
  }
```

The problem with the above way of doing it is that after the redirections triggered by signing in, and reloading this component, the Auth.currentAutheticatedUser method will catch the "not authenticated" error again even when the SignIn process has been started but probably hasn't finished yet.

I would like to know if there is a way to find out if the SignIn process has been started even when it hasn't finished yet?

Or, is there a smarter way/location to call the OAuthSignIn() without the need of clicking on a button?

Thanks!

**Comment by powerful23** [comment]
@marioaae Hi, as a work around you can set a flag in your local storage which indicating whether the user is logging in or not, for example: 
```js
componentDidMount = () => {
    const isSigningIn = localStorage.getItem('flag');
    Auth.currentAuthenticatedUser()
      .then(user => {
        // Do nothing because the user is authenticated already
        }})
      .catch(err => {
        // Authenticate the user because the user is not authenticated yet
        if (isSigningIn !== 'true') {
          this.props.OAuthSignIn();
          localStorage.setItem('flag', 'true');
         }
      });
  }
```
 And you can reset that flag based on the `oAuthUser` or `oAuthError` callback props.

**Comment by sammartinez** [comment]
@marioaae Does the above work for you?

**Comment by marioaae** [comment]
> 
> 
> @marioaae Hi, as a work around you can set a flag in your local storage which indicating whether the user is logging in or not, for example:
> 
> ```js
> componentDidMount = () => {
>     const isSigningIn = localStorage.getItem('flag');
>     Auth.currentAuthenticatedUser()
>       .then(user => {
>         // Do nothing because the user is authenticated already
>         }})
>       .catch(err => {
>         // Authenticate the user because the user is not authenticated yet
>         if (isSigningIn !== 'true') {
>           localStorage.setItem('flag', 'true');
>           this.props.OAuthSignIn();
>          }
>       });
>   }
> ```
> 
> And you can reset that flag based on the `oAuthUser` or `oAuthError` callback props.

Hi @powerful23, thanks for the recommendation.

Reading the documentation at https://aws-amplify.github.io/docs/js/authentication, it says "With React Native, you can use withOAuth HOC to launch the hosted UI experience. Just wrap your app’s main component with our HOC. Doing so, will pass the following props available to your component"...and here I can find the callback props as oAuthUser or oAuthError.

I'm using React JS and I'm not sure I can use those callbacks there but instead I'm using "Hub" (https://aws-amplify.github.io/docs/js/hub) which has simillar callbacks. Including one called "SignIn". The problem with it is still the same, it will successfully be triggered only when it is successfully signed in but during the process of "sigining in" I don't know if an attempt to sign in has been started.

So, having a flag doesn't help in this case because when the re-direction happens, all my storage is flushed (including that flag) and the callbacks are only triggered when when the signin process has finished. I still need a way to know if the signin process has been started but not finished.

**Comment by marioaae** [comment]
> 
> 
> @marioaae Does the above work for you?

Hi @sammartinez I didn't try exactly that way but in a very similar way (please see my response to @powerful23). Unfortunatelly I still have the problem.

**Comment by rawadrifai** [comment]
@marioaae - did you figure this out? I have a similar question.
I'm developing a slack clone. If the user already signed in once, then next time they open the app it should auto sign in. Still tinkering around. Let me know if you have any suggestions pls.

**Comment by rawadrifai** [comment]
This was easier than I thought.. Auth.currentSession() returns the current authenticated session after closing the app (if the user did not sign out)
