### ISSUE TITLE
Can't find Variable: Symbol

### ISSUE THREAD

**Issue by Samykills** [aws-amplify/amplify-js#3233]
**Describe the bug**
Using the library 1.1.27

**Expected behavior**
No error should occur, since this was working fine untill now.

**Screenshots**
![image](https://user-images.githubusercontent.com/18477982/57312693-afd40f00-710b-11e9-84ff-605fb5be0686.png)

**Smartphone (please complete the following information):**
 - Device: Redmi note 5 pro
 - OS: android

**Sample code**
Adding the sample code here
https://github.com/Samykills/AwsAmplifyExp

awsAmplify.js
`import Amplify, { Analytics } from "aws-amplify";
import Config from "react-native-config";
import { Platform } from "react-native";
import { AppContext } from "react-native-ss-app-core";
class AwsAmplify {
  static initalize() {
    const amplifyConfig = {
      Auth: {
        identityPoolId: Config.AWS_COGNITO_IDENTITY_POOL_ID,
        region: "us-east-1"
      }
    };
    //Initialize Amplify
    Amplify.configure(amplifyConfig);

    const analyticsConfig = {
      AWSPinpoint: {
        // Amazon Pinpoint App Client ID
        appId: Config.AWS_PINPOINT_APP_ID,
        // Amazon service region
        region: "us-east-1",
        mandatorySignIn: false
      }
    };

    Analytics.configure(analyticsConfig);
  }

  /**
   *
   * @param {String} eventName - name of the event or module - "traffic"
   * @param {String} type - Type of event- ("entry"/"exit") or anything
   * @param {String} value - Type of event- can be null or anything
   */
  static recordEvent(eventName, action, title) {
    let attributesJson = {};
    let appContext = AppContext.getAppContext();
    attributesJson["action"] = JSON.stringify(action);
    attributesJson["title"] = title;
    attributesJson["zoneSelected"] = appContext.parentZoneName;
    attributesJson["os"] = Platform.OS;
    attributesJson["version"] = Config.CODE_PUSH_VERSION;
    attributesJson["eventTimeStamp"] = new Date().getTime().toString();
    if (appContext.sessionData) {
      let sessionData = JSON.parse(appContext.sessionData);
      attributesJson["userId"] = sessionData.userId.toString();
      sessionData.tenantId
        ? (attributesJson["tenantId"] = sessionData.tenantId.toString())
        : null;
      sessionData.tenantDto
        ? (attributesJson["tenantname"] = sessionData.tenantDto.name.toString())
        : null;
    }

    Analytics.record({
      name: eventName,
      attributes: attributesJson
    });
  }
}

export default AwsAmplify;`
***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***
Adding debug log here :

Can't find variable: Symbol
<unknown>
    constants.js:19:54
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    API.js:74:18
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    index.js:15:12
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    index.js:26:12
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    SSAnalytics.js:1
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    index.js:1
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    emsLocationComponent.js:14
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    index.js:1
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    firebaseNotification.js:6
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    index.js:2
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    campusFeedbackServiceManager.js:2
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    campusFeedbackComponent.js:18
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    index.js:1
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    app-router.js:19
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    index.android.js:4
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    App.js:3
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    index.js:2
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:141:45
_require
    require.js:132:20
global code

**Comment by powerful23** [comment]
@Samykills Hi, are you using expo? Can you provide more code snippets so we can reproduce it?

**Comment by Samykills** [comment]
@powerful23 this is not an expo app, as soon as i import the library it blows up. have already added the logs and that i get when i see this error , a thing to notice is there is no error shown in metro when this happens

**Comment by Samykills** [comment]
@powerful23 added a sample

**Comment by ambeshHappiestMinds** [comment]
To those who are still facing this issue

To resolve this followed following post
https://github.com/facebook/react-native/issues/15786#issuecomment-404834632

basically this issue occurred since JavaScriptCore  might be not updated on your device or emulator your best bet will be to try jsc-android-buildscripts to provide this compatibility below is the instruction to integrate same on Android

https://github.com/react-native-community/jsc-android-buildscripts#how-to-use-it-with-my-react-native-app

**Comment by Samykills** [comment]
@ambeshHappiestMinds Does it solve the problem for you?
i started receving this error two days ago and before that all was well.
I am on target api version 27 and also i get the same on IOS

**Comment by ambeshHappiestMinds** [comment]
@Samykills  yes it did i was able to create Andorid builds properly

**Comment by Samykills** [comment]
@ambeshHappiestMinds  ios?

**Comment by ambeshHappiestMinds** [comment]
opps sry iOS i was able to create builds easily since our deployment target was greater tha 10 on this we did not got this issue i suggest you may use react-native 0.57.5and check

**Comment by dinukasal** [comment]
this worked for me. thanks @ambeshHappiestMinds

**Comment by jessedoyle** [comment]
@powerful23, @jordanranz  - This is generating an issue with our build using react-native 0.58.X on Android.

While the workaround [here](https://github.com/aws-amplify/amplify-js/issues/3233#issuecomment-490835465) may resolve the issue, I think updating to a custom JavaScriptCore version is a heavy-handed solution.

The root cause is that `aws-amplify` is referencing `Symbol` directly assuming that it's defined for every JS interpreter.

Here's the offending line: https://github.com/aws-amplify/amplify-js/blob/d8c972dff0ad4483db8a7122f5bf4952cc8a295a/packages/core/src/constants.ts#L18

In most other locations, Amplify checks the existence of `Symbol` ([example](https://github.com/aws-amplify/amplify-js/blob/8fba1a22c8e464e66fad8b6444f3a72891feb85a/packages/core/src/Hub.ts#L18)).

I believe this is definitely a bug in `aws-amplify`.

**Comment by Samykills** [comment]
@jessedoyle i replaced the code in node_modules/@aws-amplify/core/constants.ts with the one provided by you and still facing the same error, can you try the same with the sample-project i have added and verify? it would be great help :)

**Comment by jessedoyle** [comment]
@Samykills - You're right - I think the guard clause is insufficient. 

I think we'll need a condition similar to the other `Symbol` reference checks through `aws-amplify`:

```js
export const INTERNAL_AWS_APPSYNC_PUBSUB_PROVIDER = (typeof(Symbol) !== 'undefined' && typeof(Symbol.for) === 'function') ?
    Symbol.for('INTERNAL_AWS_APPSYNC_PUBSUB_PROVIDER') : '@@INTERNAL_AWS_APPSYNC_PUBSUB_PROVIDER';
```

I modified the corresponding code in `node_modules/@aws-amplify/core/lib/constants.js` and it resolves the issue for our app.

I'm going to update my PR to include this condition.

**Comment by Samykills** [comment]
Updating JSCore for android works!
