### ISSUE TITLE
create admin login rule ?

### ISSUE THREAD

**Issue by NuruddinBadawi** [aws-amplify/amplify-js#3234]
** Which Category is your question related to? **
amplify 
** What AWS Services are you utilizing? **
cognito

I have multi frontend application, one for admin pages to manage data and the other app for public users, and now any user can login into admin, 
so how create rules? or what is the best way to allow and disallow login in admin app ? and how to implemented ?

**Comment by powerful23** [comment]
@NuruddinBadawi Hi, this is quite a general question. 

From my understanding, you are trying to have two groups of users in the Cognito User: one group is the admin one and the other is the public one. When the user signs in, you want to render different views based on the user group that the user belongs to. Also you want to give different IAM policy based on that too. 

To achieve this you can create groups in the Cognito User Pool and add users into the group. You can also add different IAM roles to different groups: https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-user-groups.html

You can get the group info of per user from the payload of the access token so you can render different views based on that. For example:
```js
// after signing in
const groupInfo = await Auth.currentSession().accessToken.payload['cognito:groups'];
```

Hope this could help you.

**Comment by haverchuck** [comment]
Closing this issue as the question seems to have been answered.
