### ISSUE TITLE
Cognito - User is not authorized to get auth details

### ISSUE THREAD

**Issue by raquila** [aws-amplify/amplify-js#3238]
** Which Category is your question related to? **
SAML authentication

** What AWS Services are you utilizing? **
amazon-cognito-identity-js

** Provide additional details e.g. code snippets **
I'm getting an error when trying to authenticate using a login that is tied to a saml provider.  If I try to log in through Cognito UI login screen I don't have any issues.  I'm not sure I need to do something different since non saml provider users work fine using the code below.  I'm not able to find any detailed documentation on this.

![Capture1](https://user-images.githubusercontent.com/124973/57334759-a5574c80-70ee-11e9-8374-9650b90a4e3c.PNG)

**Comment by powerful23** [comment]
@raquila if you want to login in with a saml provider, then you have to use the Cognito Hosted UI as this is the only way for now.

**Comment by raquila** [comment]
I'm doing this within an electron application and trying to integrate an SSO solution.  There is no other way to do this without having to use the Hosted UI?

**Comment by powerful23** [comment]
@raquila you can try to use Amplify and  the `Auth.federatedSignIn({provider: ${THE_PROVIDER_NAME}})` to directly open the login page of that SAML provider.  Please take a look at this doc: https://aws-amplify.github.io/docs/js/authentication#social-provider-federation

**Comment by raquila** [comment]
@powerful23  Do you know if its possible to covert a set of users that were created in cognito already to use an identity provider?  When I test, it creates a new user in cognito with the same email address but different username.
