### ISSUE TITLE
ConsoleLogger bind console.error 

### ISSUE THREAD

**Issue by kevohagan** [aws-amplify/amplify-js#3239]
** Which Category is your question related to? **
Logger
** What AWS Services are you utilizing? **
Logger service
** Provide additional details e.g. code snippets **
why is the this line commented out? https://github.com/aws-amplify/amplify-js/blob/b65739bf9f4c3cd6898a89e0899c0dbeabc5c882/packages/core/src/Logger/ConsoleLogger.ts#L76

Im logging error logs to Cloudwatch binding the console and it works great, I would like to use Logger instead but the error level in ConsoleLogger is not binded to console.error, what's the reason for this? 

Thanks a million for your help

**Comment by powerful23** [comment]
@kevohagan not sure why is uncommented. Have sent a pr to fix this.

**Comment by kevohagan** [comment]
Brilliant! Thanks! :)
