### ISSUE TITLE
Frozen at "Loading..." when signing in and refreshing

### ISSUE THREAD

**Issue by sandrosc** [aws-amplify/amplify-js#3242]
**Describe the bug**
When signing in and refreshing the page, the loading component is shown and nothing else happens anymore. When refreshing the page again, the user is signed in automatically.

**To Reproduce**
1. Empty caches
2. Open page
3. Sign in
4. Reload
5. A loading card is shown

**Expected behavior**
If there even was a loading time it should be very short.

**Screenshots**
![image](https://user-images.githubusercontent.com/12650063/57390402-8de69500-71bc-11e9-8153-7e2763100bfd.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 74

**Additional context**

**Sample code**
```js
import Auth from '@aws-amplify/auth';
import {
  ConfirmSignIn,
  ForgotPassword,
  Loading,
  RequireNewPassword,
  SignIn,
  TOTPSetup,
  withAuthenticator,
  VerifyContact
} from 'aws-amplify-react';
// define app, etc.
const AppWithAuth = withAuthenticator(
  App,
  false,
  [
    <ConfirmSignIn />,
    <ForgotPassword />,
    <Loading />,
    <RequireNewPassword />,
    <SignIn />,
    <TOTPSetup />,
    <VerifyContact />
  ],
  null,
  AuthenticatorTheme
);
```

**Comment by jordanranz** [comment]
What version of `aws-amplify-react` are you using?

**Comment by sandrosc** [comment]
@jordanranz version 2.3.6.

**Comment by p4ul** [comment]
We are having the same issue, occasionally stuck on "loading". There also appears to be no connections in the network tab to https://cognito-idp.ap-southeast-2.amazonaws.com/ when this is happening.

**Comment by p4ul** [comment]
Still happening in 
aws-amplify-react: version 2.3.8.
@aws-amplify/auth: version 1.2.24.

But now console says "Uncaught (in promise) not authenticated"

To clarify recreate instructions above you need to refresh **before** site has fully signed in.

**Comment by sandrosc** [comment]
Bug seems to have been fixed in the latest version 🥇

**Comment by aldegoeij** [comment]
could it be that this is back in `aws-amplify@1.1.30-unstable.1` if I browser reload my static site page, I get 'loading' if I reload again, it works... Using the `withAuthenticator` HOC

**Comment by webjay** [comment]
I'm having the same issue: https://svedig.com/dashboard/

**Comment by webjay** [comment]
On a [Gatsby](https://www.gatsbyjs.com/) site which [this](https://svedig.com/dashboard/) is, it happens every time you sign in, sign out, then try to sign in again.
