### ISSUE TITLE
Social Auth not persisting in React Native

### ISSUE THREAD

**Issue by matthieunelmes** [aws-amplify/amplify-js#3245]
**Describe the bug**
I've implemented the withOAuth HOC as the documentation suggests that this is the only way that automatically refreshes tokens.

In my example, the user authenticates with Google, this then correctly creates a Federated Identity and populates a user in the User Pool. the Hub.listen correctly fires on the 'signIn' event in which I can console.log the current user.

The problem I'm having is that after 60 minutes, the session and token expires. The documentation suggests that Amplify should "magically" handle the token refresh in the background, but this does not happen.

I am able to console.log the Hub.listen event which gives `"The OAuth redirect failed to be parsed"`
 
**Sample code**
```
import React, { Component } from 'react';
import { StyleSheet, Text, ScrollView, SafeAreaView, StatusBar, Button } from 'react-native';

import { withOAuth } from "aws-amplify-react-native";
import Amplify, { Auth, Hub } from 'aws-amplify';
import config from './aws-exports'
Amplify.configure(config)

const oauth = {
  // Domain name
  domain: 'xxxxxx.amazoncognito.com',

  // Authorized scopes
  scope: ['email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],

  // Callback URL
  redirectSignIn: 'amplifyauth://', // this is name of app which correctly redirects after sign in

  // Sign out URL
  redirectSignOut: 'amplifyauth://', // this is name of app which correctly redirects after sign out

  // 'code' for Authorization code grant, 
  // 'token' for Implicit grant
  responseType: 'token',

}

Amplify.configure({
  Auth: {
    oauth: oauth
  }
});



class App extends React.Component {
  constructor(props) {
    super(props);
    Hub.listen('auth', (data) => {
      switch (data.payload.event) {
        case 'signIn':
          console.log('sign in success');
          Auth.currentAuthenticatedUser().then(user => {
            console.log(user);
            this.setState({ authState: 'signedIn' });
          }).catch(e => {
            console.log(e);
            this.setState({ authState: 'signIn' });
          });
          break;
        case 'signIn_failure':
          console.log('sign in failed');
          break;
        default:
          break;
      }
    });

    Auth.currentSession().then((session) => {
      console.log('current session')
      console.log(session.idToken.jwtToken);
    });
  }
  render() {
    const {
      oAuthUser: user,
      oAuthError: error,
      googleSignIn,
      signOut,
    } = this.props;

    return (
      <SafeAreaView style={styles.safeArea}>
        {user && <Button title="Sign Out" onPress={signOut} icon='logout' />}
        <ScrollView contentContainerStyle={styles.scrollViewContainer}>
          <Text>{JSON.stringify({ user, error, }, null, 2)}</Text>
          {!user && <React.Fragment>

            {/* Go directly to a configured identity provider */}
            <Button title="Google" onPress={googleSignIn} />

          </React.Fragment>}
        </ScrollView>
      </SafeAreaView>
    );
  }
}

const styles = StyleSheet.create({
  safeArea: {
    flexGrow: 1,
    paddingTop: StatusBar.currentHeight,
    backgroundColor: '#FFFFFF',
  },
  scrollViewContainer: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
  }
});

export default withOAuth(App);
```

**Comment by powerful23** [comment]
@matthieunelmes Hi when using the Cognito OAuth, to get the refresh token you have to use the `Authorization code grant` flow rather than `token` flow by the Cognito doc: https://aws.amazon.com/blogs/mobile/understanding-amazon-cognito-user-pool-oauth-2-0-grants/

> Only use the implicit grant when there’s a specific reason that the authorization code grant can’t be used. In an implicit grant, user pool tokens are exposed directly to the end user. As a result, the ID and access tokens have more potential to become compromised before they expire. On the other hand, if your setup doesn’t contain any server-side logic, you may want to use the implicit grant to prevent refresh tokens from being exposed to the client, as the implicit grant does not generate refresh tokens.

I will also add more info in the amplify doc.

**Comment by matthieunelmes** [comment]
Thanks @powerful23 I'm guessing it's not as simple as setting responseType to 'code' as now I'm getting error: `unauthorized_client`

**Comment by powerful23** [comment]
@matthieunelmes did you enable the flow in your web client setting?
![Screen Shot 2019-05-09 at 4 50 08 PM](https://user-images.githubusercontent.com/11042868/57493601-871e5780-727a-11e9-9f40-e60ed3ab3239.png)

**Comment by matthieunelmes** [comment]
That's it! Thank you. I can also see it's returning a refreshtoken for the cognito user now.
