### ISSUE TITLE
Build fails through Amplify Console

### ISSUE THREAD

**Issue by venkatesh-kadiyala** [aws-amplify/amplify-js#3246]
**Describe the bug**
The build fails through amplify console. It gives a schema invalidation error.

**To Reproduce**
1. Define a sample graphql api with @model and @auth as below
![a](https://user-images.githubusercontent.com/42621275/57407634-a3a28d00-71b1-11e9-8657-4e3d99d9e45b.PNG)
2. Doing `amplify push` compiles good in local and create the API in cloud.
3. When we create a CI/CD through amplify console, it provisions build environment with docker image. 
![b](https://user-images.githubusercontent.com/42621275/57407938-65599d80-71b2-11e9-8693-9be9261a160b.png)

4. And in the "Backend" section it fails saying schema is invalid.
![c](https://user-images.githubusercontent.com/42621275/57407950-6ab6e800-71b2-11e9-9131-ab7b0d0b189e.png)

**Expected behavior**

 Looks like the amplify-cli version has to be upgraded to the latest one. In provision section, you can see it is installing 1.5.1 where I had issue. But in local I am using 1.6.5 which works fine.

**Comment by venkatesh-kadiyala** [comment]
@powerful23 
Do you have any update on this ?

**Comment by VividKnife** [comment]
Hi, we already updated the CLI version in Amplify Console to "1.6.9". Can you please try again?

**Comment by venkatesh-kadiyala** [comment]
@VividKnife The build is success but still it shows as version 1.5.1.  See the below image

![Build-Image1](https://user-images.githubusercontent.com/42621275/58582354-906a6680-821f-11e9-809d-b1dbcf194c8a.PNG)

**Comment by VividKnife** [comment]
That's a documentation issue. Will notify team to fix it.

**Comment by venkatesh-kadiyala** [comment]
Thank you.
