### ISSUE TITLE
v1.1.27 Runtime error with @types/zen-observale: error TS2300: Duplicate identifier 'Subscriber'. 

### ISSUE THREAD

**Issue by adamfoerster** [aws-amplify/amplify-js#3248]
I'm trying to use AWS Amplify with an Angular APP but I get an error with the Subscriber type in zen-observable that prevents me from building it. 
--
ERROR in node_modules/@types/zen-observable/index.d.ts(33,14): error TS2300: Duplicate identifier 'Subscriber'.
node_modules/@aws-amplify/api/node_modules/@types/zen-observable/index.d.ts(32,14): error TS2300: Duplicate identifier 'Subscriber'.
--
If I go to either one of the files in the node_modules folder and comment the Subscriber type line the code the build starts working again until it crashes a couple minutes later.

This is my package.json:
--
{
  "name": "udm-nebular",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "graphql": "npm run graphql:introspect && npm run graphql:generate",
    "graphql:generate": "CODEGEN_RESOLVERS=false gql-gen --schema schema.json --template graphql-codegen-apollo-angular-template --out src/app/generated/graphql.ts",
    "graphql:introspect": "gql-gen --schema src/schema.graphql --template graphql-codegen-introspection-template --out schema.json",
    "generate": "graphql-codegen --config codegen.yml",
    "gql": "graphql-codegen --config codegen.yml"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~7.2.14",
    "@angular/cdk": "~7.3.7",
    "@angular/common": "~7.2.14",
    "@angular/compiler": "~7.2.14",
    "@angular/core": "~7.2.14",
    "@angular/forms": "~7.2.14",
    "@angular/http": "~7.2.14",
    "@angular/platform-browser": "~7.2.14",
    "@angular/platform-browser-dynamic": "~7.2.14",
    "@angular/pwa": "^0.13.9",
    "@angular/router": "~7.2.14",
    "@angular/service-worker": "~7.2.14",
    "@herodevs/lazy-af": "0.0.8",
    "@nebular/auth": "^4.0.0-beta.0",
    "@nebular/eva-icons": "4.0.0-beta.0",
    "@nebular/theme": "^4.0.0-beta.0",
    "animate.css": "^3.7.0",
    "apollo-angular": "^1.5.0",
    "apollo-angular-link-http": "^1.6.0",
    "apollo-cache-inmemory": "^1.5.1",
    "apollo-client": "^2.5.1",
    "apollo-link-error": "^1.1.10",
    "aws-amplify": "^1.1.27",
    "aws-amplify-angular": "^3.0.2",
    "core-js": "^3.0.1",
    "dayjs": "^1.8.14",
    "eslint": "^5.16.0",
    "eslint-config-airbnb-base": "^13.1.0",
    "eslint-config-prettier": "^4.2.0",
    "eslint-plugin-import": "^2.17.2",
    "eslint-plugin-prettier": "^3.0.1",
    "eva-icons": "^1.1.1",
    "graphql": "^14.3.0",
    "graphql-tag": "^2.10.1",
    "ng2-completer": "^2.0.8",
    "ng2-smart-table": "^1.4.0",
    "ngx-auto-unsubscribe": "^3.0.0",
    "prettier": "^1.17.0",
    "rxjs": "~6.5.1",
    "rxjs-compat": "^6.5.1",
    "tslint-config-prettier": "^1.18.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.13.9",
    "@angular/cli": "~7.3.9",
    "@angular/compiler-cli": "~7.2.14",
    "@angular/language-service": "~7.2.14",
    "@graphql-codegen/fragment-matcher": "1.1.3",
    "@graphql-codegen/introspection": "^1.1.3",
    "@graphql-codegen/typescript": "1.1.3",
    "@graphql-codegen/typescript-apollo-angular": "1.1.3",
    "@graphql-codegen/typescript-graphql-files-modules": "1.1.3",
    "@graphql-codegen/typescript-operations": "1.1.3",
    "@schematics/angular": "~7.3.9",
    "@types/jasmine": "~3.3.12",
    "@types/jasminewd2": "~2.0.6",
    "@types/node": "^11.13.10",
    "apollo-codegen": "^0.20.2",
    "codelyzer": "~5.0.1",
    "graphql-codegen-introspection": "^0.18.1",
    "graphql-codegen-typescript-apollo-angular": "^0.18.1",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.5",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.2",
    "ts-node": "~8.1.0",
    "tslint": "^5.16.0",
    "typescript": "^3.2.4"
  }
}

**Comment by powerful23** [comment]
Related to #1435 #1732 #1284

**Comment by Temkit** [comment]
Problem persist.
 using  "aws-amplify": "^1.1.29-unstable.1",

> ERROR in node_modules/@aws-amplify/api/node_modules/@types/zen-observable/index.d.ts(32,14): error TS2300: Duplicate identifier 'Subscriber'.
> node_modules/@types/zen-observable/index.d.ts(33,14): error TS2300: Duplicate identifier 'Subscriber'.

**Comment by satishmolletipipra** [comment]
Hi,
Anybody can help us on this blocker.
