### ISSUE TITLE
Country code Phone number picker broken on iOS react native 

### ISSUE THREAD

**Issue by illume** [aws-amplify/amplify-js#3254]
**Describe the bug**

The country code picker is broken on iOS, as shown in [this issue](https://github.com/aws-amplify/amplify-js/issues/2618#issuecomment-464516384)

Note that only +1 is shown, and no other country code can be selected. (side question, how to set a default country code?)

**To Reproduce**

Use a withAuthenticator(App) amplify app with auth on iOS.

**Expected behavior**

Should be able to select a country code.

**Screenshots**

<img alt="screen shot 2019-02-17 at 5 03 51 pm" src="https://user-images.githubusercontent.com/5934354/52920051-835fe200-32d6-11e9-8b69-7ced8097b301.png" style="max-width:100%;" width="437">

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 12.1

**Smartphone (please complete the following information):**
 - Device: iPhone 6S and Simulator (different hardware).
 - OS: 12.1

**Comment by illume** [comment]
It seems to work. Maybe the latest update fixed it. Sorry for the noise.

**Comment by hwkd** [comment]
I'm actually having the same issue and I couldn't find any solution so far.
