### ISSUE TITLE
"No current user" when trying to sign in

### ISSUE THREAD

**Issue by aequasi** [aws-amplify/amplify-js#3260]
**Describe the bug**

Trying to sign in, using `Auth.signIn(username, password)`, and get the error message "No current user".

Checking the network tab shows a `200 POST https://cognito-idp.us-east-1.amazonaws.com/` request, with what seems to be a valid user response:

```json
{"AuthenticationResult":{"AccessToken":".....","RefreshToken":"...","TokenType":"Bearer"},"ChallengeParameters":{}}
```

Configuring with: 

```typescript
Amplify.configure({
    Auth: {
        region: 'us-east-1',
        userPoolId: process.env.userPoolId,
        userPoolWebClientId: process.env.userPoolWebClientId,
        mandatorySignIn: true,
        cookieStorage,
    },
});
```

I'm *somewhat* sure that the ids are correct, but im not sure if im missing anything else

**Comment by astro21** [comment]
I had the same issue. Removing cookieStorage from the Amplify.configure() resolved the issue for me. 

I am testing on localhost and I don't have a domain. In the cookieStorage, I need to provide a domain

**Comment by aequasi** [comment]
Issue was due to using http://localhost:3000, and the default of cookieStorage.secure being true.
