### ISSUE TITLE
Is `aws-exports.js` insecure ?

### ISSUE THREAD

**Issue by jhw** [aws-amplify/amplify-js#3261]
Wondering what the thinking behind the usage of `aws-exports.js` is - isn't it somewhat "insecure" to stick your pool ids etc in there ? I mean you wouldn't put your key/secret in there presumably. So maybe pool ids don't constitute a security risk ? Maybe they are just somewhat equivalent to a URL endpoint ? Is it possible to set these values via environment variables ?

**Comment by elorzafe** [comment]
@jhw taking the response from a [this comment](https://github.com/aws-amplify/amplify-js/issues/2927#issuecomment-478166128)

> the information contained in the aws-exports.js file is necessary to construct the service endpoints in order for your client to communicate with the backend and not secret information to access your AWS account. This information is acceptable for your client application and shouldn't risk inappropriate access to resources as long as you leverage the proper workflows outlined by the Amplify Framework (the Amplify CLI automatically sets these workflows up for you). For example the client apps will use the Cognito endpoint information for end users to register & login, those users will then be able to interact with services such as S3 and AppSync with the resulting credentials. None of this information could be used for accessing AWS accounts outside of a client application.
