### ISSUE TITLE
Possible for Authenticator HOC to accept federated props with react-native

### ISSUE THREAD

**Issue by ranjeev75** [aws-amplify/amplify-js#3263]
The documentation [here](https://aws-amplify.github.io/docs/js/authentication#using-the-authenticator-component), states that react-native is not supported here and to use 
`Auth.federatedSignIn()` instead. Is there an example that shows exactly how this can be done?

Also when just rendering a FaceBook button with `Auth.federatedSignIn({provider: 'Facebook'})` this still renders the entire hoisted UI, as in this example: 

`<Button title='Login' onPress={() => Auth.federatedSignIn({provider: 'Facebook'})} />`

Is this the correct way of doing this?

**Comment by sammartinez** [comment]
@ranjeev75 Here is a guide for adding [OAuth and Hosted UI](https://aws-amplify.github.io/docs/js/authentication#oauth-and-hosted-ui). There is also a section in the [React Components](https://aws-amplify.github.io/docs/js/authentication#react-components) section on using OAuth in React Native. Unfortunately there is not a quick link to it but if you search '_To use withOAuth in your React Native application first install the appropriate dependencies_' on the page this will take you there. Also, if you are using expo you can follow this guide that will get you setup with [WebBrowser](https://aws-amplify.github.io/docs/js/authentication#a-note-for-expo-users).

Hope this helps!

**Comment by ranjeev75** [comment]
@sammartinez  Thanks for these links. I'll have a look again at using OAuth
