### ISSUE TITLE
AWS Amplify - TypeError: Cannot read property 'Stacks' of null

### ISSUE THREAD

**Issue by LucaTabone** [aws-amplify/amplify-js#3264]
Hey friends :),

I am trying to 'amplify init' my Android Project and I get stuck with the following error:

<img width="1251" alt="Bildschirmfoto 2019-05-12 um 23 52 59" src="https://user-images.githubusercontent.com/4339435/57588318-a8997080-7512-11e9-94a7-43ab01bee053.png">

I have granted 'AWSElasticBeanstalkFullAccess' to the aws profile used.

I would be immensely thankful for any help.

Thank You very much in advance.

Yours, Luca

**Comment by ashleynguyen27** [comment]
how did you end up solving this. I am having the same issue

**Comment by mudassir21** [comment]
i am having the same issue. how can i solve that?

**Comment by peterheneback** [comment]
This is caused by the IAM user not being authorised to perform the iam:CreateRole action needed  in the CloudFormation stack.

**Comment by beilusen** [comment]
> This is caused by the IAM user not being authorised to perform the iam:CreateRole action needed in the CloudFormation stack.

How should this be done?

**Comment by sarvesh05** [comment]
I was facing the same issue, here's how I resolved it.
When I was doing 'aws configure' and creating a profile, I was choosing the region incorrectly(not the one I chose when I was setting up my account).
Created another profile with right region.
Did 'amplify init', worked like charm.
