### ISSUE TITLE
Unsure about Auto Tracking Usage

### ISSUE THREAD

**Issue by janhesters** [aws-amplify/amplify-js#3271]
** Which Category is your question related to? **
Analytics

** What AWS Services are you utilizing? **
Amazon Pinpoint

** Provide additional details e.g. code snippets **
In [this question
](https://github.com/aws-amplify/amplify-cli/issues/1412) I asked about tracking with Amplify and got referred to Analytics. I'm currently teaching myself how to use these because I'm having trouble understanding the docs.

I'm using React. I have two questions. 1. Where am I supposed to add the code for the tracking? 2. Is there a way to identify which user created the event?

Here is what I'm currently trying:

```js
async function track() {
  try {
    const user = await Auth.currentAuthenticatedUser();
    const userId = user.username;
    Analytics.autoTrack('pageView', {
      enable: true,
      attributes: { userId },
      type: 'SPA',
    });
  } catch (error) {
    console.log(error);
  }
}

function useTracking() {
  useEffect(() => {
    track();
  }, []);
}

function Home() {
  useTracking();
  return <h2>Home</h2>;
}

function Notes() {
  useTracking();
  return <h2>Notes</h2>;
}

function App() {
  return (
    <Router>
      <div>
        <nav>
          <ul>
            <li>
              <Link to="/">Home</Link>
            </li>
            <li>
              <Link to="/notes/">Notes</Link>
            </li>
          </ul>
        </nav>

        <Route path="/" exact component={Home} />
        <Route path="/notes/" component={Notes} />
      </div>
    </Router>
  );
}
```

But this doesn't fully work. The route is being recorded, but not the user. Are you supposed to call `autoTrack` in `componentDidMount()` / `useEffect`? Because I tried adding it below my `config` outside of a Hook and that didn't even record any events. And do I have to track the user like I did under the `attributes` key? If yes, why could my tracking not be working? If no, how are you supposed to identify users? I'm using Amplify's Auth with Cognito User Pools.

**Comment by janhesters** [comment]
Solved it, gonna write a blog post about it and link it here.

**Comment by raelmiu** [comment]
Hows the blogpost coming @janhesters ?
