### ISSUE TITLE
PushNotification updateEndpoint optOut is defaulted to NONE

### ISSUE THREAD

**Issue by neskimoo** [aws-amplify/amplify-js#3280]
**Problem**
In [PushNotification.ts](https://github.com/aws-amplify/amplify-js/blob/master/packages/pushnotification/src/PushNotification.ts#L246) the function updateEndpoint accepts only a token which gets passed on to the analytics module. At the moment, OptOut will always be set as NONE where the Analytics module allows 'NONE' and 'ALL'. 

```
const config = {
                    Address: token,
                    OptOut: 'NONE'
                };
```

I would like to be able to specify OptOut when calling PushNotification.updateEndpoint so that I can opt a user out of notifications.

**Solution**
Add an optional parameter to updateEndpoint to specify which OptOut option you want to have. The default would be to NONE so that no current code would be impacted and if an invalid parameter is sent that NONE would also be selected.

**Additional context**
I'm happy to create a PR for this but wanted to raise it as a feature request first in case some work was planned around this or if there would be unintended consequences of adding the optional parameter.

**Comment by powerful23** [comment]
@neskimoo I think maybe we can add an option in the configuration as the default `optOut` value. If the user wants to opt out later on, he can do that by using:
```js
Analytics.updateEndpoint({
 optOut: 'All'
});
```

What do you think?

**Comment by neskimoo** [comment]
@powerful23 That should work for the solution that I am working on at the moment. It would be good to have this available in the PushNotifications library, ideally I would like to use it over the Analytics module but this is a good middle ground for now. Thanks for the response on this!

**Comment by tannerabread** [comment]
Hi @neskimoo we have recently released a rewritten Push Notification category with new features, can you try it out and let me know if it works for you?

You can follow the [migration steps here](https://docs.amplify.aws/lib/push-notifications/migrate-from-previous-version/q/platform/react-native/) or if you are starting again from scratch follow the [getting-started guide here](https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/react-native/)

To accomplish your ask, you would change the options by the [identifyUser method](https://docs.amplify.aws/lib/push-notifications/identify-user/q/platform/react-native/) and more specifically as follows:

```js
import type { AWSPinpointUserInfo } from '@aws-amplify/notifications'

const userProfile: AWSPinpointUserInfo = {
  optOut: 'ALL'
}

Notifications.Push.identifyUser('userid', userProfile)
```

**Comment by tannerabread** [comment]
Hi 👋 Closing this as resolved. This should be handled with the recent release of the rewritten Push Notification category mentioned above. 

If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with additional information so we can re-open this issue and be better able to assist you.

Thank you!
