### ISSUE TITLE
Update build container to amazonlinux:2

### ISSUE THREAD

**Issue by dpeterka** [aws-amplify/amplify-js#3281]
**Is your feature request related to a problem? Please describe.**
Build container in the AWS Console is set to utilize old release of Amazon Linux. It would be nice to have support for graphics library gtk3 which is required to run headless Chrome and utilize puppeteer for doing testing.  This is not support on RH6 variants such as amazon linux 1 as the libraries are not available in amazon, epel or redhat repos.

**Describe the solution you'd like**
Update the container to utilize amazonlinux:2

**Describe alternatives you've considered**
Ability to have chrome available within the build container

**Comment by sammartinez** [comment]
@dpeterka This seems to be non-related to Amplify and more so to EC2. Please open up a [EC2 forum](https://forums.aws.amazon.com/tags/ec2?categoryID=1) issue for this if this is still a valid use case for you. Resolving this request as this is non related to Amplify.
