### ISSUE TITLE
React Native - Use Facebooks Official SDK to meet up with updated policy 

### ISSUE THREAD

**Issue by tobiastornros** [aws-amplify/amplify-js#3289]
**Is your feature request related to a problem? Please describe.**
Facebook has updated the policy for login flows. All native apps for iOS and Android should use default login behavior defined by Facebooks SDK. 

Policy: https://developers.facebook.com/policy#login   
https://developers.facebook.com/policy#7-2-photo

**Describe the solution you'd like**
Use Facebooks SDK for login in React Native for Cognito User Pools and Cognito Identity Pools with or without Cognito hosted UI.

**Comment by haverchuck** [comment]
@tobiastornros - I think this is probably an issue that's appropriate for the Cognito service team to take a look at and evaluate.  Have you tried posting to the[ Cognito forums](https://forums.aws.amazon.com/forum.jspa?forumID=173)?

Is there something specific in the Amplify JS framework that is not adhering to Facebook's guidelines?

**Comment by tobiastornros** [comment]
@haverchuck I have no idea how AWS should handle it internally. Amplify provide Facebook as an alternative in the hosted UI login with React Native. 
It should be in Amplify's interest to offer as good a solution as possible.

**Comment by manueliglesias** [comment]
Hi @tobiastornros 

Amplify doesn't interact directly with facebook. In amplify you can use social providers by either using OAuth flows (Cognito Hosted UI) or passing a facebook token yourself (this you could do using Facebook's SDK)

See [Social Provider Federation](https://aws-amplify.github.io/docs/js/authentication#social-provider-federation) and  [Identity Pool Federation](https://aws-amplify.github.io/docs/js/authentication#identity-pool-federation) for reference.
