### ISSUE TITLE
jest-haste-map: @providesModule naming collision:

### ISSUE THREAD

**Issue by khorleyi** [aws-amplify/amplify-js#3300]
**Describe the bug**
After adding the API service to my amplify project, I received this error "jest-haste-map: @providesModule naming collision:". 

**Expected behavior**
When I do an amplify run, this error pops up. 

**Error**
(node:11494) UnhandledPromiseRejectionWarning: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: StudentsCRUDFunction
  Paths: ~/my-app/amplify/#current-cloud-backend/function/StudentsCRUD/src/package.json collides with ~/my-app/amplify/backend/function/StudentsCRUD/src/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at setModule ( ~/my-app/node_modules/jest-haste-map/build/index.js:462:17)
    at workerReply ( ~/my-app/node_modules/jest-haste-map/build/index.js:512:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)

(node:11494) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:11494) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

jest-haste-map: @providesModule naming collision:
  Duplicate module name: StudentsCRUDFunction
  Paths: ~/my-app/amplify/#current-cloud-backend/function/StudentsCRUD/src/package.json collides with ~/my-app/amplify/backend/function/StudentsCRUD/src/package.json

This error is caused by a @providesModule declaration with the same name across two different files.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version 74.0.3729.157

**Additional context**
This is meant for a react-native application.

**Comment by AlessandroAnnini** [comment]
So what do I can do if I have this issue?
