### ISSUE TITLE
Refresh unauthenticated credentials?

### ISSUE THREAD

**Issue by cliffordh** [aws-amplify/amplify-js#3310]
** Which Category is your question related to? **
Authentication

** What AWS Services are you utilizing? **
Cognito, AWS Lambda

** Provide additional details e.g. code snippets **
I am successfully getting unauthenticated guest credentials, however they are expiring after an hour. I tried this code block to refresh them but still doesn't work. Is there a right way to get/refresh unauthenticated credentials?

```
if (
        !lambda ||
        !credentials ||
        !credentials.webIdentityCredentials ||
        credentials.webIdentityCredentials.expired
      ) {
        this.$Amplify.Auth.currentCredentials().then(creds => {
          credentials = creds;
          console.info(credentials);
          lambda = new Lambda({
            region: "us-east-1",
            apiVersion: "2015-03-31",
            credentials: this.$Amplify.Auth.essentialCredentials(credentials)
          });
        });
      }
```
Thanks!

**Comment by cliffordh** [comment]
I came up with this solution in lieu of any other obvious solutions. Of note, I switched from calling Auth.currentCredentials to Auth.currentUserCredentials since it looked like the Amplify code had logic for guest sessions in the currentUserCredentials function. I'm checking that there is at least 10 minutes before token expiration otherwise I call currentUserCredentials again. This seems to work and only requests credentials when necessary saving network requests and improving app performance. If there's a better way, let me know. Thanks.

```
      var offsetTime = new Date().getTime() + 10 * 60 * 1000;
      if (
        !lambda ||
        !credentials ||
        offsetTime > credentials.expireTime.getTime()
      ) {
        this.$Amplify.Auth.currentUserCredentials().then(creds => {
          credentials = creds;
          console.info(credentials);
          lambda = new Lambda({
            region: "us-east-1",
            apiVersion: "2015-03-31",
            credentials: this.$Amplify.Auth.essentialCredentials(credentials)
          });
        });
```

**Comment by powerful23** [comment]
@cliffordh Hi the `Auth.currentCredentials` is able to handle the refreshing automatically and I did a test which works fine for me. If you turn on the debug mode(by putting `window.LOG_LEVEL='DEBUG'` in your app) and call `Auth.currentCredentials()` after one hour, you should see the following messages:
<img width="809" alt="Screen Shot 2019-05-24 at 2 04 17 PM" src="https://user-images.githubusercontent.com/11042868/58356774-4eab7b80-7e2d-11e9-9930-159fef66185d.png">
