### ISSUE TITLE
A contains filter is not matching when value is stored with capital in Dynamodb

### ISSUE THREAD

**Issue by rpostulart** [aws-amplify/amplify-js#3311]
When I use a filter on a graphql query and this filter value is lowercase: 

`name: { contains: name }`

And when the name value with a capital case has been saved to Dynamodb, there will be no match found, although the values are the same except from the Capital.

**Comment by haverchuck** [comment]
@rpostulart -  DynamoDB is case sensitive, so this is not unexpected behavior.  However, there are ways to perform the query you are attempting.  One way would be to [use Elasticsearch in conjunction with DynamoDB](https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-combining-graphql-resolvers.html) (Note: I'm assuming you're using AppSync here).

**Comment by rpostulart** [comment]
I understand! But isn’t this a simple solution? Where we now need to spin up an EC2 cluster to host Elasticsearch. This is adding extra cost to customers to do a simple contains query. Maybe it’s interesting to invest in a kind of serverless Elasticsearch which enables less cost for Elasticsearch.

**Comment by haverchuck** [comment]
@rpostulart We are going to discuss this as a team.

**Comment by haverchuck** [comment]
@rpostulart We understand what you're saying  - but I think it's more of a service-level suggestion and not necessarily we can solve via Amplify.  Have you tried posting to the[ DynamoDB forums](https://forums.aws.amazon.com/forum.jspa?forumID=131) or [AppSync forums](https://forums.aws.amazon.com/forum.jspa?forumID=280)?

I am going to close this issue but feel free to make another if you disagree.  Thanks.

**Comment by kkbava** [comment]
reminds me of age-old SQL Server SOP we had - store certain fields in both "as-typed" and also in uppercase. 
All searches would be by comparing uppercase version of user criteria, against the uppercase column. 
But the "as-typed" column would be shown.
Cant do that for EACH column though

**Comment by wongjasont** [comment]
Its now 2021 and I'm in a similar situation! Just needed one field to be searchable on my application...
