### ISSUE TITLE
Cognito multiple types of users

### ISSUE THREAD

**Issue by TemoLucky** [aws-amplify/amplify-js#3313]
** Which Category is your question related to? **
Cognito
** What AWS Services are you utilizing? **
Cognito, Amplify, DynamoDB
** Provide additional details e.g. code snippets **

**I want to have 3 types of users A,B,C.**

User A can see only his/her attributes.
User B can access his/her attributes and attributes of attached User A (can be multiple).
User C can see all users attributes( Admin user).

As I know it's not possible to implement using Cognito and Amplify directly. So I have Idea to implements this functionality using DynamoDB. we should have users Table in database.
For example-GraphQL Transform code 

Type User @model @auth(rules: [
                                  { allow: owner},
                                  { allow: owner, ownerField: "B"}, 
                                  { allow: groups, groups: ["admin"] } // for user of Type C 
                                  ]) {
    id: ID!
    email: String!
    name: String!
    owner: String
    B: [String]
    userType: A or B or C
}

After cognito signUp triggering Lambda function, we will write user attributes in DynamoDB table. 

**Any ideas ?**

**Comment by haverchuck** [comment]
@TemoLucky We currently have an [RFC](https://github.com/aws-amplify/amplify-cli/issues/766) out right now describing some possible feature enhancements  to address this type of issue.  Please feel free to comment.

In the interim, perhaps Cognito's [fine-grained Role-Based Access Control functionality](https://aws.amazon.com/blogs/aws/new-amazon-cognito-groups-and-fine-grained-role-based-access-control-2/) could be leverated?  Just something to consider.

**Comment by sammartinez** [comment]
@TemoLucky [Cognito Lambda Triggers](https://aws-amplify.github.io/docs/cli-toolchain/cognito-triggers) seems to solve this use case. Please see the link provided. Resolving as this is implemented via Amplify CLI
