### ISSUE TITLE
Cognito usage with Mobx - email attributes

### ISSUE THREAD

**Issue by springcoil** [aws-amplify/amplify-js#3315]
** Which Category is your question related to? **
Usage of Cognito
** What AWS Services are you utilizing? **
AWS Amplify, Cognito
** Provide additional details e.g. code snippets **
So I'm not sure if this is a bug or a misunderstanding of usage. 

I'm using react native and Expo.

  Expo CLI 2.15.4 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.12.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: 2.8.0 => 2.8.0
    npmGlobalPackages:
      expo-cli: 2.15.4

My code examples. 

```// Sign up user with AWS Amplify Auth
  async signUp() {
    const { username, password, email } = this.props.UserName;
    console.log(username, JSON.stringify(this.props.UserName));
    // rename variable to conform with Amplify Auth field phone attribute
    await Auth.signUp({
      username,
      password,
      attributes: { email }
    })
      .then(() => {
        console.log("email", email);
        Alert.alert(
          "",
          "Enter the confirmation code you received.",
          [
            {
              text: "OK",
              onPress: () =>
                this.props.navigation.navigate("Passcode", {
                  email: this.props.UserName.email
                })
            }
          ],
          { cancelable: false }
        );
        console.log("Username", JSON.stringify(username));
        console.log("Confirmation code sent");
      })
      .catch(err => {
        if (!err.message) {
          console.log("Error when signing up: ", err);
          Alert.alert("Error when signing up: ", err);
        } else {
          console.log("Error when signing up: ", err.message);
          Alert.alert("Error when signing up: ", err.message);
        }
      });
  }
``` 

I'm getting an error which is that email attribute is null. Should that be the case. 

My MobX store is. 

```export class UserName {
  @observable username = "";
  @observable password = "";
  @observable useremail = "";

  @action
  setUsername(name) {
    this.username = name;
  }
  @action
  setPassword(password) {
    this.password = password;
  }

  @action
  setEmail(email) {
    this.useremail = email;
  }
}

export default new UserName();
```

**Comment by haverchuck** [comment]
@springcoil Where are you deriving this.props.UserName, and what are you getting in the console logs for this value?  Can you try console logging this value and username, password and email within your .catch block?

**Comment by springcoil** [comment]
```So i logged it and got Username "testuser"
RemoteConsole.js:80 email undefined
RemoteConsole.js:80 password "password"```

``` <Item style={styles.itemStyle}>
                      <AntDesign name="mail" style={styles.iconStyle} />
                      <Input
                        style={styles.input}
                        placeholder="Email"
                        placeholderTextColor="#bcbcbc"
                        keyboardType={"email-address"}
                        returnKeyType="next"
                        autoCapitalize="none"
                        autoCorrect={false}
                        secureTextEntry={false}
                        ref="ThirdInput"
                        onSubmitEditing={event => {
                          this.refs.FourthInput._root.focus();
                        }}
                        onChangeText={value =>
                          this.onChangeText(
                            "email",
                            this.props.UserName.setEmail(value)
                          )
                        }``` no idea why this isn't being passed around but password is...

**Comment by springcoil** [comment]
The fix was this ```export class UserName {
  @observable username = "";
  @observable password = "";
  @observable email = "";

  @action
  setUsername(name) {
    this.username = name;
  }
  @action
  setPassword(password) {
    this.password = password;
  }

  @action
  setEmail(email) {
    this.email = email;
  }
}``` thanks for the help
