### ISSUE TITLE
amplify react getting started w/ simple auth, no userPool error.

### ISSUE THREAD

**Issue by johncantrell97** [aws-amplify/amplify-js#3319]
I am just following along with this tutorial: 
https://aws-amplify.github.io/docs/js/react

When I go to register a new user I am getting an error saying `no userPool`.  I read through some similar issues where it almost always was a case of duplicate auth/core modules.  I have deleted and reinstalled all modules.

  
Here are my package.json dependencies:

"dependencies": {
    "aws-amplify": "^1.1.28",
    "aws-amplify-react": "^2.3.8",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-scripts": "3.0.1"
}

If I run:

`npm ls | grep amplify`

I get:

├─┬ aws-amplify@1.1.28
│ ├─┬ @aws-amplify/analytics@1.2.16
│ │ ├── @aws-amplify/cache@1.0.27 deduped
│ │ ├── @aws-amplify/core@1.0.27 deduped
│ ├─┬ @aws-amplify/api@1.0.35
│ │ ├── @aws-amplify/auth@1.2.24 deduped
│ │ ├── @aws-amplify/cache@1.0.27 deduped
│ │ ├── @aws-amplify/core@1.0.27 deduped
│ ├─┬ @aws-amplify/auth@1.2.24
│ │ ├── @aws-amplify/cache@1.0.27 deduped
│ │ ├── @aws-amplify/core@1.0.27 deduped
│ ├─┬ @aws-amplify/cache@1.0.27
│ │ └── @aws-amplify/core@1.0.27 deduped
│ ├─┬ @aws-amplify/core@1.0.27
│ ├─┬ @aws-amplify/interactions@1.0.30
│ │ └── @aws-amplify/core@1.0.27 deduped
│ ├─┬ @aws-amplify/pubsub@1.0.28
│ │ ├── @aws-amplify/core@1.0.27 deduped
│ ├─┬ @aws-amplify/storage@1.0.30
│ │ └── @aws-amplify/core@1.0.27 deduped
│ ├── @aws-amplify/ui@1.0.19
│ └─┬ @aws-amplify/xr@0.1.17
│   └── @aws-amplify/core@1.0.27 deduped
├─┬ aws-amplify-react@2.3.8

I'm not sure what else to try to fix this? I can see the cognito user pool created in my aws account and it's id matches the information in aws-exports.js.  My aws-exports.js file is in my /src folder.

In my App.js I have code like this:

import Amplify from 'aws-amplify';
import awsExports from './aws-exports';
import { withAuthenticator } from 'aws-amplify-react';

Amplify.configure(awsExports);

function App (){
//
}
export default withAuthenticator(App, true);

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4
 - Browser Chrome
 - Version 74

**Comment by metamn** [comment]
The same error here ... should I provide more info?

**Comment by rpostulart** [comment]
I believe it's a bug with the new version of amplify, before I hadn't this issue. 

I already made an issue here and proposed a temporary solution:

https://github.com/aws-amplify/amplify-js/issues/3287

**Comment by johncantrell97** [comment]
Somehow I fixed this by moving the configure code from the App component to the main index.js file and it fixed it.  🤷‍♂
