### ISSUE TITLE
Storybook integration

### ISSUE THREAD

**Issue by ajhool** [aws-amplify/amplify-js#3327]
**Is your feature request related to a problem? Please describe.**
Storybook is a development tool for displaying and interacting with components in a standalone environment. https://storybook.js.org

**Describe the solution you'd like**
Storybook integration with amplify would include two parts:
1. Storybook integration into the project (eg. a `.storybook` directory and a `yarn storybook` command)
2. A hosted storybook environment that would allow anybody to view/interact with components without needing to download the repository and execute storybook on their own machine.

**Describe alternatives you've considered**
https://github.com/styleguidist/react-styleguidist -- it seems like storybook has better support for multiple frameworks (react + vue)

I have only ever used storybook and it seems to be more popular than the alternatives. The amplify team also indicated that they were interested in Storybook integration #3279 

**Additional context**

I have opened up a repo where I plan to do this integration, here: https://github.com/ajhool/amplify-js

**Comment by ajhool** [comment]
My first attempt to add a component to storybook resulted in:

`Module not found: Error: Can't resolve '@aws-amplify/core' in '/Users/aidan/Development/amplify-js/packages/aws-amplify-react/src'`

When importing `AmplifyUI` I used the same implementation as \__tests\__ uses, except my folder is \__stories\__ . I also tried javascript instead of typescript. See:

https://github.com/ajhool/amplify-js/blob/master/packages/aws-amplify-react/__stories__/AmplifyUI.stories.tsx

After cloning the repo, I ran: `yarn lerna bootstrap`. Are there other steps that need to be run before amplify-js can be built/tested locally?

**Comment by jordanranz** [comment]
Hey @ajhool,

You should be able to begin local development after `yarn bootstrap` with `yarn` then `yarn build` at the root of `amplify-js`. Here is a bit more information:
https://github.com/aws-amplify/amplify-js/wiki/Local-Development

I have began reviewing the commits in your fork. Keep in mind that most of, if not all of [AmplifyUI inside of our aws-amplify-react package](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Amplify-UI/Amplify-UI-Components-React.jsx) will be replaced by the work done for the Web Component RFC you commented on. 

I believe it would be more valuable to write stories for the higher level components that we expose in [each of the categories](https://github.com/aws-amplify/amplify-js/tree/master/packages/aws-amplify-react/src) that we support. For example in [Auth](https://github.com/aws-amplify/amplify-js/tree/master/packages/aws-amplify-react/src/Auth), the [Greetings component](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Auth/Greetings.jsx) or the [SignIn component](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Auth/SignIn.jsx). These components will likely remain React components built on top of the Web Components that are created and will probably not get deprecated with the new refactor. This would allow us to reuse any stories that are created in the current state of the package.

Also, thanks for creating a new thread to track this. If you have any more questions, don't hesitate to post here. I will be tracking this during the design and development for the refactor.

**Comment by danielbayerlein** [comment]
Not so popular, but very simple: https://www.docz.site/

**Comment by jordanranz** [comment]
We now have a Storybook package for the new UI components: https://github.com/aws-amplify/amplify-js/tree/master/packages/amplify-ui-storybook
