### ISSUE TITLE
Can i use 'amplify-authenticator' control from 'aws-amplify-angular' for federated SAML login ?

### ISSUE THREAD

**Issue by LiorSaadon** [aws-amplify/amplify-js#3329]
** Which Category is your question related to? **
Single sign on using 'amplify-authenticator' control from 'aws-amplify-angular'

** What AWS Services are you utilizing? **
Cognito federated SAML login

** Provide additional details e.g. code snippets **
I have an Angular 7 project that uses cognito login with  'aws-amplify-angular' control which works great.
i am trying to add SAML login using ADFS but i'm not sure if the 'aws-amplify-angular' control supports it.

I am using this versions in my package.json:
    "aws-amplify": "1.1.19",
    "aws-amplify-angular": "2.1.6"

Does the control supports SAML sign in ?
If not, will it support it in future versions?

**Comment by tartur** [comment]
Hello Guys,

I have the same question but with federated social signin.
I am using the following versions
* aws-amplify 1.2.4 and,
* aws-amplify-angular 3.1.4
* angular 7
And I cannot see how I can configure the 'amplify-authenticator' component to support federated identity providers.

Does anyone know how I can do this?

Thank you in advance

**Comment by tannerabread** [comment]
Absorbing this into #439 for better coverage/duplicate
