### ISSUE TITLE
VerifyUserAttribute with email link

### ISSUE THREAD

**Issue by jfrense** [aws-amplify/amplify-js#333]
**Do you want to request a feature or report a bug?**
Feature

**What is the current behavior?**
When calling Auth.verifyUserAttribute(username, 'email') it sends a verification code even when in the AWS cognito console  'verify with link' is the selected verification method.

**Proposed feature**
allow an option to verify with link when calling Auth.verifyUserAtrtribute()

**Comment by eknowles** [comment]
how is stuff like this not being assigned or addressed in 11 months...

**Comment by jordanranz** [comment]
I have seen a few other requests for this feature. There is some work by the Cognito service team to allow Amplify to have this functionality.

I will try and consolidate these requests and bring it up to the service team.
