### ISSUE TITLE
Implement Federated Login Support for Vue

### ISSUE THREAD

**Issue by cliffordh** [aws-amplify/amplify-js#3333]
**Is your feature request related to a problem? Please describe.**
Currently Federated Login with Facebook, Google, Amazon is not supported by Vue. 

**Describe the solution you'd like**
I would like an example of supporting social login using Vue, similar to the React implementation.

**Describe alternatives you've considered**
Reverse engineer the React code and port to Vue :-(

**Additional context**
n/a

**Comment by haverchuck** [comment]
@cliffordh This [PR](#2812 )  needs some discussion and more testing by our team, but it might be worth taking a look at it.  You could pull down the branch locally if you want to give it a try.

**Comment by haverchuck** [comment]
Related to #2812

**Comment by cliffordh** [comment]
Thanks, I think I can hack this together from the PR... but sure would be nice if this was an approved PR and part of the mainline :-) @haverchuck

**Comment by cliffordh** [comment]
I was able to get SignIn working with Facebook and it seems to work pretty smoothly... but it appears that this method of signin creates only an Identity Pool entry and not a User Pool entry. I'm assuming I need to use the Oauth flow in order to have the user created in the User Pool, correct? Is there a reason I should use one over the other? With the Identity Pool approach I don't seem to get automatic access to the Facebook, Google, Amazon customer email address and profile information. However, with User Pools that information is recorded in my User Pool...

Ultimately, I want to have private S3 storage buckets for any user accessing my service. Will the Identity Provider route satisfy that requirement, or do I need to use User Pools and the OAuth flow? And given this Use Case, what is the better option?

**Comment by cliffordh** [comment]
Ok. Closing this. I'm going to stop fighting the system by trying to roll my own auth hooks into Cognito. I'm going with OAuth User Pools (after much research) and the Hosted UI. I've gotten the Hosted UI to look quite acceptable and with a custom domain name my users should feel comfortable with the experience.
