### ISSUE TITLE
Retrieve access token from Google

### ISSUE THREAD

**Issue by richguan** [aws-amplify/amplify-js#3334]
** Which Category is your question related to? **
Auth - Federated Social Provider

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
Relating to [#402](https://github.com/aws-amplify/amplify-js/issues/402)

> @vsrivatsan89 Auth.currentCredentials() will return you a [CognitoIdentityCredentials](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityCredentials.html) object. This will contain a [WebIdentityCredentials](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/WebIdentityCredentials.html) object which you can then retrieve the [Logins] from for your identity providers i.e. google/facebook etc.
> 
> So, for example, to retrieve a google token:
> 
> ```js
> async getCreds() {
>     let credentials = await Auth.currentCredentials(),
>          token = credentials.webIdentityCredentials.params.Logins['accounts.google.com'];
>     
>     console.log(token); // here is your token
> }
> ```

@mlabieniec I am having is retrieving the access token from Google. I would like to retrieve this token so that I can make calls to Google APIs.

I am using the new Auth.federatedSignIn({provider: 'Google'}) to bypass the Hosted UI. When I retrieve the webIdentityCredentials, I can only see the Cognito login information. Does amplify provide a tool to retrieve the access token from Google?

**Comment by haverchuck** [comment]
@richguan  - In order to retrieve this token, you need to setup the attribute mapping in Cognito.  Google returns the access token, which you can map to an attribute that is part of the user in the Cognito User Pool.  In this case you will probably need to make a custom attribute on the User Pool.  You can decrypt the id token that comes back to the browser, or I *believe* you [can use Amplify](https://aws-amplify.github.io/docs/js/authentication#working-with-user-attributes) to  get the attributes directly.

**Comment by srivempati** [comment]
@haverchuck In relation to this, is there a way to extract refresh_token? Google's oauth returns refresh tokens only when access_type=offline is specified in the query. Is there a way to let cognito specify that parameter?

**Comment by lvillacin** [comment]
Any update with this? I'm trying to do the same thing here.

**Comment by Sher-V** [comment]
Any solution?

**Comment by lvillacin** [comment]
> Any solution?

I ended up using other authentication providers because of this problem.
