### ISSUE TITLE
Using our own and SAML based Identity Provider

### ISSUE THREAD

**Issue by azarboon** [aws-amplify/amplify-js#3336]
** Which Category is your question related to? ** Authentication for React

** What AWS Services are you utilizing? ** Cognito (Identity Pool)

** Provide additional details e.g. code snippets **

We would like to use AWS Cognito for authentication and authorisation. But we can't transfer our user data to AWS Cognito User Pool, instead we need to authenticate users through our own SAML based Identity Provider (IdP). 

I've created a User Pool and defined our IdP in there. Now, I would like to set up our React app to connect with Cognito and to do the authentication.  I'm using Amplify CLI v1.6.8 but as for federation, it only provides option for Facebook, Google and Amazon. I'm wondering how can I setup authentication based for a 3rd party SAML based IdP? And if Amplify cli currently doesn't  support it, can you suggest me an informative article?

Also, please note that our IdP is not publicly accessible, and it can be accessed only within our company network. When I supplied IdP's metadata to Cognito User Pool, it didn't complain. But just to make sure: should we change anything in our default settings because of it?

**Comment by haverchuck** [comment]
@azarboon  You are correct - The Amplify CLI does not currently support SAML providers. You will need to set this up in the Cognito console.  Have you looked into using SAML with the Hosted UI?  For instructions on setting this up in the console, [see these docs](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-saml-idp.html).

**Comment by anam-khalid** [comment]
Any updates on this? Does Amplify CLI still not support SAML providers? @haverchuck @azarboon @manueliglesias

**Comment by Rahul-Reddy94** [comment]
@haverchuck Does amplify support authentication for Identity provider via **google** (Open Id connect )??

**Comment by mrgoos** [comment]
@haverchuck - CLI is one thing, but how can it be accomplished with the JS lib? Angular or whatever?
