### ISSUE TITLE
Amplify API returns Network Error on post

### ISSUE THREAD

**Issue by krzysztofstudniarek** [aws-amplify/amplify-js#3341]
I use Amplify API feature. With pure generated lambda code and configuration, while calling post method in my API I receive generic Network Error

The API is configured as REST API with a DynamoDB table backend. It should save a record to dynamoDB

Code to call the API:

```javascript
await API.post("sesamum", "/reservations", {
      body: {
        id: "123123123"
      }
}).then(response => {
      alert(response);
}).catch(error => {
      alert(error);
});
```

I expect it to add the record to dynamoDB.

**Comment by haverchuck** [comment]
@krzysztofstudniarek Can you please give a bit more detail?

1. Does the 'network error' have an error code or any other content in the network tab?
2. Did you use the Amplify CLI to generate the REST API?  If so, what did you enter for the paths and the API name?
3.  Did you go through the documentation [here](https://aws-amplify.github.io/docs/js/api#using-the-api-client)?
4. Does GET or other types of calls work?

**Comment by krzysztofstudniarek** [comment]
Hey @haverchuck 

Ad 1. Not that I'm aware of. But will investigate more and come back to you.

Ad 2. Yes I have used Amplify CLI

Ad 3. Yes

Ad 4. I have only tried this post. 

Thanks for help.

**Comment by bush** [comment]
I have just encountered this error as well.
