### ISSUE TITLE
React Native FederatedSignIn() not working 

### ISSUE THREAD

**Issue by chriscraiclabs** [aws-amplify/amplify-js#3342]
** Which Category is your question related to? **
React-Native Auth - Federated

** What AWS Services are you utilizing? **
Cognito

** versions **
`"aws-amplify": "1.1.28",`
`"react-native": "0.59.1",`

** Provide additional details e.g. code snippets **

The below snippet is a common scenario for federated login. I've see this working example in multiple places so I know it `should` work. I'm able to navigate out of the app -> auth with facebook -> return to the app successfully but, it doesn't look like I am actually authenticated.

Some things I've noticed:
 - `Hub.listen()` is never triggered (it is with normal auth)
 - A new user is not created in my user pool
 - user is not authenticated

```
  useEffect(() => {
    Hub.listen('auth', (data) => {
      console.log('A new auth event has happened: ', data);
    });
    Auth.currentSession().then(session => console.log(session.getAccessToken()));
  }, []);

...

  const signInFacebook = async () => {
    Auth.federatedSignIn({ provider: 'Facebook' });
  };

...

 <Button
    onPress={signInFacebook}
    title="Sign in with facebook"
 />
```

I have also tried using the `withOAuth` HOC that's bundled with `aws-amplify-react-native`. it essentially does the same thing but the issue still persists.

I am seeing this yellowbox warning on launch of app - `Possible Unhandled Promise Rejection TypeError: Parameter 'url' must be a string, not object. AuthClass`

<img width="370" alt="Screenshot 2019-05-23 at 22 37 12" src="https://user-images.githubusercontent.com/28810867/58288486-a0132680-7dab-11e9-9d13-8e61dbc5ba7b.png">

Any ideas? 

`

**Comment by AAfify1** [comment]
Not sure if it is related but using the code below to register facebook users to my user pool but it is not working, as in I can not see the users created. I am just starting out with RN and AWS so any help would be appreciated :)
```javascript
 signin = async () => {
    try {
      const user = await Auth.federatedSignIn("facebook", {
        token: state.accessToken,
        expires_at: state.expirationTime
      });
    } catch (err) {
      console.log("error:", err);
    }
  };


  makeLoginButton(callback) {
    return (
      <LoginButton
        readPermissions={["public_profile"]}
        onLoginFinished={(error, result) => {
          if (error) {
          } else if (result.isCancelled) {
          } else {
            AccessToken.getCurrentAccessToken()
              .then(
                data => {
                  callback(data.accessToken);
                  () =>
                    this.setState({
                      accessToken: data.accessToken
                    });
                  this.signin();
                 alert(data.accessToken.toString());
                }
                // I am able to see the access token so I know i am getting it succesfully
              )
              .catch(error => {
                console.log(error);
              });
          }
        }}
      />
    );
  }```

**Comment by haverchuck** [comment]
@chriscraiclabs - Do you by any chance have the debugger attached?

**Comment by chriscraiclabs** [comment]
Hey @haverchuck, nope I didnt. Been looking at this for a few days now

**Comment by jessedoyle** [comment]
Hi @chriscraiclabs - I think the YellowBox warning you're seeing was introduced by a bugfix that I submitted previously (https://github.com/aws-amplify/amplify-js/pull/3230).

I'm going to be submitting a PR to resolve the YellowBox warning, but I don't believe the warning is the cause of your issue with `Auth.federatedSignIn`. 

I can confirm that we are using `withOAuth` on React Native with a custom Cognito Identity Provider and the flow works with the following npm versions (other than the warning on app launch as you've pointed out):

* `aws-amplify === 1.1.29-unstable.0`
* `aws-amplify-react-native === 2.1.12`

**Comment by chriscraiclabs** [comment]
Hey @jessedoyle What version of `react-native` are you using? Are you using `Hub.listen()` to pull the auth data returned? or are you getting that from somewhere else?

**Comment by jessedoyle** [comment]
@chriscraiclabs 

We have an Android-only app running `react-native === 0.58.6`. 

We're not using `Hub.listen()` explicitly in the app, but we do use `Auth.currentAuthenticatedUser()` to fetch user data.

**Comment by EmanH** [comment]
I'm having the same issue here.

**Comment by EmanH** [comment]
Render:
```
<Button full style={styles.google} onPress={this.GoogleSignIn}>
      <Text>Login with Google</Text>
</Button>
```

```
GoogleSignIn() {
   Auth.federatedSignIn({ provider: "Google" });
}
```

```
componentDidMount() {

 Hub.listen("auth", ({ payload: { event, data } }) => {
    console.log("Hub Event", event, data);
    switch (event) {
      case "signIn":
        this.setState({ user: data });
        break;
      case "signOut":
        this.setState({ user: null });
        break;
    }
  });

  Auth.currentAuthenticatedUser()
    .then(user => this.setState({ user }))
    .catch(() => console.log("Not signed in"));
}
```

Likewise I'm getting no Hub events, and user is not authenticated. :(

**Comment by iamdavidmartin** [comment]
I get the exact same yellow box warning each time the app loads. 

Error occurs because function _handleAuthResponse parameter URL is null: https://github.com/aws-amplify/amplify-js/blob/master/packages/auth/src/Auth.ts#L1531

This function is being invoked on app load when there is no genuine auth response.

Solution: change line https://github.com/aws-amplify/amplify-js/blob/master/packages/auth/src/Auth.ts#L216

from
`this._handleAuthResponse(url);`
to 
`if(url) this._handleAuthResponse(url);`

Everything continues to work normally for me, minus the annoying yellow box error.

**Comment by chriscraiclabs** [comment]
This should not be closed

**Comment by jenshandersson** [comment]
@iamdavidmartin I def think your solution should be merged in, have you created a PR? Also, how do we reopen this task? This must be happening to all RN devs?

**Comment by jessedoyle** [comment]
@iamdavidmartin - I agree that your solution should fix the root cause. Can this issue be reopened?

**Comment by rnnyrk** [comment]
Solution with changing the line doesn't work for me either. My app doesn't build anymore after adding a Facebook sign in via `amplify add auth`..
