### ISSUE TITLE
OAuth Flow doesn't set Name, Profile, etc.

### ISSUE THREAD

**Issue by cliffordh** [aws-amplify/amplify-js#3345]
**Describe the bug**
I'm successfully using OAuth login flow with Facebook, Google, LoginWithAmazon. Email is passed from the OAuth provider but I'm not getting name, and other profile data in my user pool.

Only email is set as a required attribute in my user pool... could that be why?

**Comment by cabeaulac** [comment]
I'm interested in this also.

**Comment by cliffordh** [comment]
@cabeaulac I figured this out... in Cognito there is an option in your User Pool, underneath Federation called Attribute Mapping. Here is where you can map attributes from Facebook to your User Pool. I had to explicitly add the Facebook Attributes: short_name, picture but this seems to work. I haven't tried with Google or Amazon yet, but assuming it's going to be similar.

**Comment by cabeaulac** [comment]
Thanks @cliffordh 
I'll see if I can get it to work for Google and I'll try Facebook too. Maybe somebody has a link to some AWS docs that say exactly how to do this? Because I haven't found those docs yet.
