### ISSUE TITLE
CSS should be prepackaged or not included

### ISSUE THREAD

**Issue by shicholas** [aws-amplify/amplify-js#3348]
**Describe the bug**
This comment on https://github.com/aws-amplify/amplify-js/issues/2523 has this comment: 

```
Any plans to fix this? Im using next.js for my app and this https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Amplify-UI/Amplify-UI-Components-React.jsx#L5 is causing me to get that error. Would be nice to override to exclude the styles or have them be build as part of the distribution so I didn't have to custom configure webpack for it.
```

**To Reproduce**

1. Use Amplify-React in any repo with webpack. You will need a `css` processor in order for everything to work.

**Expected behavior**

I should not need to require a `css` webpack loader because I expect this repo to only include javascript files.

**Screenshots**
n/a
**Desktop (please complete the following information):**
all

**Smartphone (please complete the following information):**
 all

**Additional context**
n/a

**Sample code**
n/a

**Comment by jordanranz** [comment]
This is being refactored in the UI Component refactor:
https://github.com/aws-amplify/amplify-js/issues/3279

**Comment by aldegoeij** [comment]
@shicholas could you point me to the right direction on how to workaround this using webpack css preprocessor?

**Comment by shicholas** [comment]
```
      {
        test: /\.css$/,
        use: [
          {
            loader: 'style-loader',
          },
          {
            loader: 'css-loader',
          },
        ],
      },
```


I've just been processing css referred to by my app
