### ISSUE TITLE
In graphql.schema, how do I pass record ownership through a connection?

### ISSUE THREAD

**Issue by rawadrifai** [aws-amplify/amplify-js#3350]
GraphQL Schema

AWS Amplify, API Gateway, DynamoDB, Lambda, Cognito

In the schema below, I am trying to implement message channels. like slack. I want to track the access of the Message type. Only the users in a channel should be able to read a message. How do I make that dynamic to the members of a channel?

```
type Channel @model @auth(rules: [
  { allow: owner },
  { allow: groups, groups: ["everyone"], operations: [read] }
]) {
  id: String!
  description: String
  members: [Member] @connection(name: "ChannelMembers") 
  messages: [Message] @connection(name: "ChannelMessages", sortField: "createdAt") 
}

type Message @model @auth(rules: [
  { allow: owner },
  { allow: owner, ownerField: "users", operations: [read] }
]) {
  id: ID!
  users: [String]
  channel: Channel @connection(name: "ChannelMessages")
}

type Member @model(queries:null) @auth(rules: [
  { allow: owner }
]) {
  id: ID!
  owner: String
  channel: Channel @connection(name: "ChannelMembers") 
}
```

**Comment by jkeys-ecg-nmsu** [comment]
Search for "Dynamic Group Authorization" in the GraphQL transformer guide: 

https://aws-amplify.github.io/docs/cli/graphql#usage-1

**Comment by rawadrifai** [comment]
@jkeys-ecg-nmsu , I tried Dynamic Groups.  Please correct me if I'm wrong, The problem is that you would need to create a Cognito security group per channel. For something like slack, with a lot of clients (and more channels), would that be a problem?

**Comment by rawadrifai** [comment]
I figured this out. I used this:
```
@auth(rules: [
  { allow: owner, ownerField: "users", operations: [read] }
])
```
and I maintained the users of a channel in the ownerField.

**Comment by jkeys-ecg-nmsu** [comment]
>Please correct me if I'm wrong, The problem is that you would need to create a Cognito security group per channel. 

No, that's static group authorization that relies on Cognito groups. Dynamic group authorization relies on a dynamic field of your model.

**Comment by rawadrifai** [comment]
@jkeys-ecg-nmsu are you sure about that? I'm under the impression from the documentation that "groups" are Cognito groups, whether static or dynamic. But assuming dynamic groups are not maintained in Cognito.. where do you maintain them? As in, how do you add/remove users from a group? and where's that stored?

**Comment by jkeys-ecg-nmsu** [comment]
>With dynamic group authorization, **each record contains an attribute specifying what groups should be able to access it. Use the groupsField argument to specify which attribute in the underlying data store holds this group information.** To specify that a single group should have access, use a field of type String. To specify that multiple groups should have access, use a field of type [String].

https://aws-amplify.github.io/docs/cli/graphql ("dynamic group authorization")

**Comment by rawadrifai** [comment]
@jkeys-ecg-nmsu  yes this is the field where you specify the group name(s). But who are the users that belong in the group? Those are specified in Cognito. The "dynamic group" must exist in Cognito as a group in the user pool you are using.
