### ISSUE TITLE
Question: Is it possible to change the console's Dockerfile env variables?

### ISSUE THREAD

**Issue by araphiel** [aws-amplify/amplify-js#3353]
**Which Category is your question related to?**

AWS Console

**Provide additional details e.g. code snippets**

Is it possible to change the console's Dockerfile env variables?
For example, updating the `VERSION_HUGO` variable?

**Comment by araphiel** [comment]
bump

**Comment by jm3** [comment]
I had the same question and found this answer; YMMV:  [Deploy newer Hugo vers/change build env vars](https://forums.aws.amazon.com/message.jspa?messageID=897427)

**Comment by araphiel** [comment]
Thanks @jm3, wish it were easier but that seems like a good approach. 
Will likely cache the tar file to reduce build times
