### ISSUE TITLE
axios 0.17.1 , 0.18.0 is showing a minor security issue 

### ISSUE THREAD

**Issue by yashwanthkumarsuruneni** [aws-amplify/amplify-js#3354]
**Describe the bug**
Running the snyk scan on my project 

**To Reproduce**
1.  Run the snyk scan on your node_modules

**Expected behavior**
 The scan shouldn't show any security vulnerabilities 

**Screenshots**

<img width="989" alt="Screen Shot 2019-05-28 at 9 42 57 AM" src="https://user-images.githubusercontent.com/20724658/58482808-1954a580-812d-11e9-98b0-945641742b20.png">

**Comment by manueliglesias** [comment]
Hi @yashwanthkumarsuruneni 

Thanks for bringing this to our attention.

I see the issue has been reported (axios/axios#1098) in the axios repo and a [fix](https://github.com/axios/axios/commit/0d4fca085b9b44e110f4c5a3dd7384c31abaf756#diff-13c4730a3365dedb3437af189b18e6a9R219) has been merged to master.

For now, we need to wait for it to be released and then adjust our dependency if needed.

**Comment by rowanu** [comment]
Great to see you guys across this 😄 

Very keen to see this dependency updated when possible, _because Security_.

**Comment by jessedoyle** [comment]
Hi @manueliglesias - It looks like version `0.19.0` of `axios` has been release: https://github.com/axios/axios/releases/tag/v0.19.0. Just FYI!
