### ISSUE TITLE
Please export BigInteger in amplify-js/packages/amazon-cognito-identity-js/src/index.js

### ISSUE THREAD

**Issue by dmks** [aws-amplify/amplify-js#3359]
**Is your feature request related to a problem? Please describe.**
I'd like to use amazon-cognito-identify-js with AdminInitialAuth, however, I need to use `BigInteger` which is not exported.  

**Describe the solution you'd like**
I'd like `BigInteger` to be exported.

**Comment by manueliglesias** [comment]
Hi @dmks 

I am labeling this as a feature request. (Making BigInteger a top level export)

Please notice that you can import just big integer like this as of today:

```ts
import { default as BigInteger } from "amazon-cognito-identity-js/lib/BigInteger"
```

**Comment by dmks** [comment]
Ah, thanks

**Comment by manueliglesias** [comment]
I'm going to close this as there is a way to import `BigInteger`
