### ISSUE TITLE
Amplify push: Ask these questions before the wait

### ISSUE THREAD

**Issue by rawadrifai** [aws-amplify/amplify-js#3363]
If you're using AppSync, and you do Amplify push, there's a wait and then there's 2 questions:

![image](https://user-images.githubusercontent.com/24530625/58612649-24f8b700-8268-11e9-9c19-54293aaa12b7.png)

Not sure if it's too silly of an ask, but would be nice if we can answer the questions before the wait, so I can push and go do something else.

**Comment by jkeys-ecg-nmsu** [comment]
`amplify push --yes`

This is a CLI question btw.
