### ISSUE TITLE
GetSession function using wrong idTokenKey

### ISSUE THREAD

**Issue by altin-selimi** [aws-amplify/amplify-js#3367]
**Describe the bug**
Because I want better security than using localStorage to keep my tokens, I decided to implement my own storage (which is in-memory).
Now this has the usual methods required for a storage to work: `setItem, getItem, removeItem, clear`. 
I was trying to implement the signOut global function when user clicks log-out, when I was receiving an error `'Local storage is missing an ID Token, Please authenticate'`. Now I was logging the setItem and getItem keys to see what was happening, and I saw that while the idToken was in the storage, the idTokenKey sent by _getSession_ in this scenario was featuring double quotes in the key it was requiring. So instead of:
`CognitoIdentityServiceProvider.1111111u5nv3sosdjqnsk5burn.5451419e-1111-1111-1111-cf07991e4502.idToken`
I was getting 
`CognitoIdentityServiceProvider.1111111u5nv3sosdjqnsk5burn."5451419e-1111-1111-1111-cf07991e4502".idToken`.

I can fix this by replacing the quotes in the getItem function but for some reason its breaking other cases.

**To Reproduce**
1) Add a simple own storage when configuring Auth module
2) Call Auth.,signUp and Auth.signIn, and check what is being set in the store by breakpoints or console logs
3) When you call Auth.signOut you should receive `'Local storage is missing an ID Token, Please authenticate'`
4) Inspect the key which is sent to the getItem storage function and you will see the extra quotes.

**Expected behavior**
Keys should be the same as the ones which were set

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Comment by manueliglesias** [comment]
Hi @altin-selimi 

Can you share your in-memory storage implementation?

I suspect it is adding the quotes

**Comment by altin-selimi** [comment]
You are right. I was doing this:
```
setItem(key, value) {
      console.log(`Going to set ${key} to `, value);
      storage[key] = JSON.stringify(value);
    },
```
After I removed the stringify part, I had it working. But I don't understand why ? Care to explain ?

**Comment by altin-selimi** [comment]
You are right, I had this implemented:
```
setItem(key, value) {
      console.log(`Going to set ${key} to `, value);
      storage[key] = JSON.stringify(value);
    },
```
Though I don't understand why it happened. How were the double quotes getting in the middle of the getItem key ... Can you help me understand that ?

**Comment by manueliglesias** [comment]
@altin-selimi  I am glad you got it working! 😄 

> How were the double quotes getting in the middle of the getItem key ... Can you help me understand that ?

This is because that's the defined behavior for `JSON.stringify`, it is better explained [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Description).
