### ISSUE TITLE
Storage: Allow global configuration

### ISSUE THREAD

**Issue by aldo-roman** [aws-amplify/amplify-js#3368]
**Is your feature request related to a problem? Please describe.**
Our S3 bucket requires to upload using Server Side Encryption (SSE) using KMS. This was made supported on Amplify on #2171.

Given this is configured on the provider, current approach requires to include the `serverSideEncryption` on **every request**:
```typescript
return Storage.put(key, file, {
    serverSideEncryption: 'aws:kms',
    contentType: file.type
});
```

This may lead to human errors, forgetting to encrypt a file on S3 if bucket is not strict.

Other AWS S3 configurations present the same problem, such as `cacheControl`. See [AWSS3Provider.ts](https://github.com/aws-amplify/amplify-js/blob/master/packages/storage/src/Providers/AWSS3Provider.ts#L184-L186).

**Describe the solution you'd like**
Prior to #2898, we could pass this configuration flag on Storage configuration and it would be used on all `put` requests. This is because configuration was extended from default config to request-specific config. See [change](https://github.com/aws-amplify/amplify-js/pull/2898/files#diff-c5937922d4eec993fdcdf55bacbe2003L105).

I would like to see Amplify to allow global configuration of attributes, as in:
```typescript
Storage.configure({
    bucket: BUCKET,
    region: REGION,
    // ...
    serverSideEncryption: 'aws:kms',
});
```

**Describe alternatives you've considered**
Continue configuring SSE KMS on every `put` request. This error only happens on runtime, when a user is already trying to upload a file, so it is hard to catch.

**Additional context**
This was a **breaking change** introduced on 1.0.27. Not published on [Changelog](https://github.com/aws-amplify/amplify-js/blob/master/packages/storage/CHANGELOG.md#1027-2019-03-28) AFAIK.

**Comment by elorzafe** [comment]
@aldo-roman this is already merge and published on npm under unstable tag. We will close this issue, but feel free to open a new one or let us know if you have any issues.
