### ISSUE TITLE
Readme.md - Angular modules link takes to AngularJS docs

### ISSUE THREAD

**Issue by jdavidhermoso** [aws-amplify/amplify-js#3370]
In readme.md, in the Angular documentation section, a link takes to AngularJS docs instead to Angular 2+ docs.

![image](https://user-images.githubusercontent.com/7687596/58689042-4b147900-8386-11e9-9e5b-bb0e1ed06985.png)

**Comment by jdavidhermoso** [comment]
I tried to create a PR, but I have no permissions. 

Correct link is: [https://angular.io/guide/architecture-modules](https://angular.io/guide/architecture-modules)

**Comment by manueliglesias** [comment]
Hi @jdavidhermoso 

> I tried to create a PR, but I have no permissions.

I've created a PR with that change. I am curious about the permissions, you should have been able to fork the repo and send a PR
