### ISSUE TITLE
How to use 'SignInComponent' in Angular

### ISSUE THREAD

**Issue by jdavidhermoso** [aws-amplify/amplify-js#3371]
**Which Category is your question related to?**
AWS Amplify Auth
**What AWS Services are you utilizing?**
Cognito
**Provide additional details e.g. code snippets**
Hi!

I am trying to use the SignInComponent in an Angular App, but the component never gets rendered. There are no console errors.
`SignUpComponent` works fine.

my-component.html
`<amplify-auth-sign-in [authState]="authState"></amplify-auth-sign-in>`

my-component.ts
`import { Component, OnInit } from '@angular/core';
import { AmplifyService } from 'aws-amplify-angular';
import { AuthState } from 'aws-amplify-angular/dist/src/providers';

@Component({
  selector: 'app-signin',
  templateUrl: './signin.component.html',
  styleUrls: ['./signin.component.scss']
})
export class SigninComponent implements OnInit {
  public authState: AuthState = {
    user: null,
    state: 'confirmSignIn'
  };

  constructor(private amplifyService: AmplifyService) {
    this.amplifyService.setAuthState(this.authState);
  }
}`

**Comment by haverchuck** [comment]
@jdavidhermoso Maybe try passing in` AuthState.state = 'signIn'` instead of `AuthState.state = 'confirmSignIn'`?

**Comment by jdavidhermoso** [comment]
Thanks for your answer.
I copied bad. 
I'm passing 'signIn'.

Sorry.

**Comment by shenshen-whitecoat** [comment]
Got the same problem just now. Figured out by using "amplify-auth-sign-in-core". Same issue is found for "sign up". But "comfirm sign in" works fine.

**Comment by ecomonestop** [comment]
I'm still facing the same issue.  As @shenshen-whitecoat  said, I had to use "amplify-auth-sign-in-core" instead of  "amplify-auth-sign-in"  .
