### ISSUE TITLE
Multiple clients can not use the same keyPrefix.

### ISSUE THREAD

**Issue by omjimehrotra** [aws-amplify/amplify-js#3372]
<img width="263" alt="Screenshot 2019-05-31 at 5 26 13 PM" src="https://user-images.githubusercontent.com/11025717/58704321-34dbdc80-83c9-11e9-8ffe-2dd8c29e4abb.png">

Previously I was getting **"Can't find variable: Symbol"** error [https://github.com/aws-amplify/amplify-js/issues/3233](url) then as per the resolution given by AWS forum I had used Core-Js library to resolve the same, but as I used Core-Js library the I started getting this error.

The keyPrefix reduxPersist: is already in use.
Multiple clients can not share the same keyPrefix. Provide a different keyPrefix in the offlineConfig object.

**Comment by manueliglesias** [comment]
Hi @omjimehrotra 

Looks like you are using multiple instances of the `AWSAppSyncClient` in your app, please take a look at [these docs](https://aws-amplify.github.io/docs/js/api#aws-appsync-multi-auth-1) for more information on what to do (if you don't need multiple instances of the client, it is better to use just one)
