### ISSUE TITLE
Multiple Auth.sendCustomChallengeAnswer() failed with InvalidParameterException

### ISSUE THREAD

**Issue by gucolin** [aws-amplify/amplify-js#3379]
**Describe the bug**
We have CUSTOM_AUTH flow with custom challenges configured. In the case when we call Auth.sendCustomChallengeAnswer() multiple times (for example, user provided the wrong challenge answer the first time and retried), Auth.sendCustomChallengeAnswer() resulted in error:

```
{
  code: "InvalidParameterException"
  message: "Only custom auth (lambda driven) is enabled for this client."
  name: "InvalidParameterException"
}
```

**NOTE**: 
- the first time calling Auth.sendCustomChallengeAnswer() works perfectly fine
- This started to happen in the last 2 days, before that everything worked fine
- I didn't change any logic nor Amplify-js version during this time period
- Can see the same behaviors using CLI `aws cognito-idp respond-to-auth-challenge  --client-id xxxx --challenge-name CUSTOM_CHALLENGE --challenge-response ANSWER=<answer>,USERNAME=<username> --session <session id>`

**To Reproduce**
- See sample code below
- Or use CLI for the same flow 

**Expected behavior**
Auth.sendCustomChallengeAnswer() should be able to run as many times as the custom auth lambda triggers permits.

**Additional context**
Technically I believe this is a change on the Cognito side, instead of an issue on the Amplify side, but would like to see if any insights you guys can provide and anything you can help with. This change is breaking our sign in flows.

**Sample code**
```
const user = await Auth.signIn(username);

user = await Auth.sendCustomChallengeAnswer(user, wrongAnswer);

user = await Auth.sendCustomChallengeAnswer(user, rightAnswer);
```

**Comment by cyberfox1** [comment]
Weird. I am trying to debug something similar and when I have "Custom Auth Only" in the userpool it comes back with "Only custom auth (lambda driven) is enabled for this client" - but when I untick "Custom Auth Only" I get a 500 server error. Any solutions?

**Comment by gucolin** [comment]
Tried again today (without making any changes on my end) and it went back to normal. Seems like the issue has been fixed on the Cognito side. Closing this issue.
