### ISSUE TITLE
Task :@aws-amplify_pushnotification:verifyReleaseResources FAILED

### ISSUE THREAD

**Issue by davidweica** [aws-amplify/amplify-js#3381]
**Describe the bug**
following steps in the link https://aws-amplify.github.io/docs/js/push-notifications#configure-your-app to create a react-native app and firebase app to test android push notification.

it seems that the document is out of sync, the last step is "expo start". however, the first step is
"react-native init myapp".

I tried to run ./gradlew assembleRelease, 
got error:

> Task :@aws-amplify_pushnotification:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':@aws-amplify_pushnotification:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/davidwei/pushandroid/node_modules/@aws-amplify/pushnotification/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /Users/davidwei/pushandroid/node_modules/@aws-amplify/pushnotification/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /Users/davidwei/pushandroid/node_modules/@aws-amplify/pushnotification/android/build/intermediates/res/merged/release/values/values.xml:2723: error: resource android:attr/fontVariationSettings not found.
  /Users/davidwei/pushandroid/node_modules/@aws-amplify/pushnotification/android/build/intermediates/res/merged/release/values/values.xml:2724: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

**Comment by EugenePizzerbert** [comment]
same error

java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  F:\amplify\psoguestUK\mobileapp\node_modules\@aws-amplify\pushnotification\android\build\intermediates\res\merged\release\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  F:\amplify\psoguestUK\mobileapp\node_modules\@aws-amplify\pushnotification\android\build\intermediates\res\merged\release\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  F:\amplify\psoguestUK\mobileapp\node_modules\@aws-amplify\pushnotification\android\build\intermediates\res\merged\release\values\values.xml:2723: error: resource android:attr/fontVariationSettings not found.
  F:\amplify\psoguestUK\mobileapp\node_modules\@aws-amplify\pushnotification\android\build\intermediates\res\merged\release\values\values.xml:2724: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

**Comment by EugenePizzerbert** [comment]
Solved just now
react-native run-android --variant=release
./gradlew app:installRelease

Worked very well

**Comment by davidweica** [comment]
tried to run react-native run-android --variant=release
I got error :
FAILURE: Build failed with an exception.

* What went wrong:
Task 'installRelease' not found in project ':app'. Some candidates are: 'uninstallRelease'.

**Comment by davidweica** [comment]
added keystore, works now. thanks!

**Comment by 1pocketaces1** [comment]
So this simply doesn't work for running in debug on simulator?

**Comment by NvIGA** [comment]
just run
