### ISSUE TITLE
console Error : 59.24.678 AWS PinpointProvider - record event failed

### ISSUE THREAD

**Issue by cullsin** [aws-amplify/amplify-js#3382]
** Which Category is your question related to? **

AWSPinpoint Provider: console error.

** What AWS Services are you utilizing? **
Init

** Provide additional details e.g. code snippets **
I do not understand what I suppose to do with this Error. Please help me.

![image](https://user-images.githubusercontent.com/5137598/58758271-c87eeb80-8536-11e9-900b-2f7e1d69bd79.png)

**Comment by sammartinez** [comment]
@cullsin Are you still experiencing this issue with the latest version of `aws-amplify-react-native` ?
