### ISSUE TITLE
URGENT @aws-amplify/ui broke after merging the TypeScript changes

### ISSUE THREAD

**Issue by buggy** [aws-amplify/amplify-js#3383]
**Describe the bug**
The component styling is missing after merging #3180. I checked out a clean project to verify it was working properly. It looks like something has screwed up and the styling is now missing from the components.

**To Reproduce**
1. Build the aws-amplify-js from source
2. Create a new react app using create-react-app
3. Add the aws-amplify and aws-amplify-react packages from aws-amplify-js built in step 1
4. Wrap the App component in withAuthenticator()

The UI should show without any styling.

**Expected behavior**
The sign in screen should appear with default styling.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser: Firefox
 - Version: 67

**Comment by buggy** [comment]
@powerful23 or @jordanranz Are you able to verify that there is a problem? If so, can you verify that the #3384 fixes it?

**Comment by jordanranz** [comment]
@buggy Checking now.

**Comment by jordanranz** [comment]
Tested both iterations. The PR seems to fix the problem.

**Comment by jordanranz** [comment]
Merged.
