### ISSUE TITLE
Is Different Email Verification type possible?

### ISSUE THREAD

**Issue by Raythode** [aws-amplify/amplify-js#3385]
**Which Category is your question related to?** 
Usage Question and possibly feature request.

 **What AWS Services are you utilizing?** 
AWS Amplify library for user authentication for both app built with react (web app) and react-native (mobile app).

 **Provide additional details e.g. code snippets** 
 I have an implementation where, user while signing up with phone or email will get an verification code to phone or email. When signing In the same. But when user signs Up with a phone verification method, email is not verified. So, my implementation is, When user logs In with unverified email, They are taken to a screen where we say an **email link** is sent to you, clicking on which email is verified. Is this possible at the moment?

**Comment by Raythode** [comment]
I mean i see only option to change it from code to link in AWS cognito console. But can we do it programmatically?

**Comment by janhesters** [comment]
@Raythode As far as I'm concerned this is the default with AWS Amplify. I stumbled upon your issue because I'm trying to figure out the opposite: Let the user sign up without email verification, but allow him to verify that email later.

**Comment by Raythode** [comment]
@janhesters I think the thing you are looking for can be done using pre-sign up lambda trigger. I see admin can confirm users without verifying the email and verify email it later. https://docs.aws.amazon.com/cognito/latest/developerguide/signing-up-users-in-your-app.html hope this helps.

**Comment by haverchuck** [comment]
@Raythode I believe the VerifyUserAttribute triggers the [CustomMessage lambda trigger](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-message.html), which you could probably use to send a verification link.

**Comment by geetika-kathuria** [comment]
@Raythode Hi Sandeep, were you able to solve this exact problem?

**Comment by Raythode** [comment]
Yes @geetika-kathuria i was able to solve this by checking if user's phone is verified and email is not on the UI. At this moment we call Auth.verifyUserAttribute('email'). Before triggering an email we can change the email content in the [Custom Lambda Trigger](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-message.html).

All you have to do is return a custom email message with a link and subject to the trigger's response. This will send out an email with a link to the user.

To Verify the user's email when they click on the link, you have to create an API gateway which will call a Lambda function when anyone clicks on it. In this new Labda function use the aws-amplify sdk included with Lambda function to call [AdminUpdateUserAttributes](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminUpdateUserAttributes.html) to update the email_verfied flag as true.

This might be messy but works.

**Comment by Raythode** [comment]
Thanks to @haverchuck for pointing me to the right direction with which i was able to come up with this work around.

**Comment by geetika-kathuria** [comment]
Thanks @Raythode . In the lambda function where you call AdminUpdateUserAttributes, how do you verify the code passed via the link to the lambda function? In the lambda function, I don't have the token to pass to getUser. As an admin with IAM permission, I do have the access to update the user attributes but how do I validate if the code passed?
Can you please share you lambda code snippet for the above?

**Comment by Raythode** [comment]
@geetika-kathuria as of now i do not think we can validate the verification code....what I did to verify if its genuine attempt to verify the request is i would send an encrypted value of the username as a query parameter in the email link and i decrypt and check on the Lambda with admin permission. Also for a custom expiration time you can send a expiration time as query parameter while sending email link. Hope this helps.
