### ISSUE TITLE
Ionic 4 redirect back to app after auth

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-js#3386]
I am using Amplify with Ionic and have built an authentication system using the amplify angular service. Authentication works great and redirects back to the app correctly in the browser. 

However when I am on the physical device (IOS) it opens the browser to login via facebook and then never redirects back to the app and tries to go back to the localhost redirect url.

Is it even possible to use the amplify service to authenticate using social auths on a device?

**Comment by sammartinez** [comment]
@oliverandersencox Can you provide a little more information on what your redirect urls are via amplify cli? Also, are you using [Deeplinks](https://ionicframework.com/blog/deeplinking-in-ionic-apps/)?

**Comment by oliverandersencox** [comment]
@sammartinez the redirect urls are localhost:8100 for ionic running in a browser and then the app url schema for IOS which is configured correctly within xcode.

> >         "redirectSignIn": "http://localhost:8100/, com.traveller.io/",
>         "redirectSignOut": "http://localhost:8100/, com.traveller.io/",`

The issue isnt the redirect itself, its the fact that once authenticated with the social provider, when redirected back, the app does not pick up the authentication at all, even when the hub has been added.

All that is needed to have the social auth system work with the user pools on ionic is for this authentication to be picked up when redirected.
