### ISSUE TITLE
Ionic social authentication redirect not detecting authentication

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-js#3389]
**Describe the bug**
When using the amplify auth service to perform a federated sign in to Facebook or google in Ionic, in a browser, all work fine.

On a device, the federated sign in opens facebook to login, and then redirects back to the application by my app schema name. However it does not detect that the user is now authenticated.  I am using the Hub module to check for the sign in, and well as a subscription to the auth state, neither of which detects the login.

`Hub.listen('auth', ({ payload: { event, data } }) => {
      console.log(event);
      switch (event) {
        case 'signIn':
          this.loading = true;
          this.cd.detectChanges();
          this.onDetectSocialAuth();
          break;
      }
    });`

```
`this.amplify.authStateChange$
      .subscribe(async authState => {

        console.log('AUTH STATE CHANGED: ' + authState.state);`
```

I have checked the returned url, which includes the token and state in the url, so I can understand why the authentication is not working.

Is there another step I need to do after the redirect?

**Expected behavior**
After the redirect, it should detect the authentication, via the subscription to the auth state, or the HUB events. 

**Desktop (please complete the following information):**
- Chrome and safari work as expected

**Smartphone (please complete the following information):**
IOS All devices, the issue occurs

**Sample code**

`
  public async loginWithFacebook(): Promise<any> {
    const result = await this.amplify.auth().federatedSignIn({ provider: 'Facebook' });
    return result;
  }`

**Comment by oliverandersencox** [comment]
@jordanranz is there a way to get this working? I have tried many many approaches to getting Facebook login working with Ionic on IOS and AWS never picks up the redirect

**Comment by jordanranz** [comment]
Hi @oliverandersencox,

Could you place a try/catch around the `federatedSignIn` call like this:
```
public async loginWithFacebook(): Promise<any> { 
  try {
    const result = await this.amplify.auth().federatedSignIn({ provider: 'Facebook' }); 
    return result; 
  } catch (error) {
    console.log(error);
  }
}
```

The error in the console may provide us more debugging information.
