### ISSUE TITLE
Someone can login to my account without knowing my password when SMS 2FA is turned on

### ISSUE THREAD

**Issue by ak37165** [aws-amplify/amplify-js#3390]
**Describe the bug**
When 2FA is turned on, and the user makes a forgot-password request, only one reset-password code is sent instead of two. Suppose I am a user a on a Cognito powered app with SMS 2FA turned on for my login. If my phone is stolen, someone can request a password reset code with just my username (and publicly known app client ID from Javascript code). They get the password reset code on my phone and reset my password. They can then login using the new password (the 2FA code will again be sent to the phone only). Just one factor needed to login to my account and not two.

**To Reproduce**
1. Create a user pool with either optional or mandatory MFA.
2. Create a user and setup MFA with SMS.
3. Make a forgot password request.

**Expected behavior**
When a user has MFA enabled, a reset password request should send TWO reset codes  - one to the user's email and another to their phone (in case of SMS MFA). For TOTP MFA, the phone code need not be sent explicitly, just the email code. 

When the user enters a new password to reset it, TWO codes should be asked: one sent to email and the other from their phone (sent from Cognito in case of SMS and generated by app in case of TOTP). 

**Desktop (please complete the following information):**
Can be reproduced on any OS and browser.

**Smartphone (please complete the following information):**
Any smartphone that lets me receive a code via SMS and has a browser.

**Additional context**
The expectation with 2FA is someone needs two factors and should not be able to login to an account with just one factor.

**Comment by ak37165** [comment]
Documentation at https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ForgotPassword.html states that only one reset code is sent, and if a verified phone number exists the code is sent to the phone (regardless of whether a verified email exists or not).

**Comment by ak37165** [comment]
To summarize the issue: **someone with just my phone can login without knowing my password** if I enable SMS MFA (or just add a verified phone).

The attacker with my phone will request a password reset code, get it on the phone (most smartphones display the SMS received even when the screen is locked) and use it to reset my password. Now they can login using the new password and the SMS MFA code sent to the same phone.

**Comment by ak37165** [comment]
Pinging again for any activity on this. To re-state: if a user has two factors enabled, Cognito lets an attacker with just one factor login.

Suppose I have SMS MFA enabled. Suppose an attacker gets access to my phone only (not my email account). The attacker will get the password reset-code on that phone and then when logging in with the newly set password, the MFA code will also arrive to the same phone. So the attacker can login.

**Comment by ak37165** [comment]
Possible solution: See the section "Reset your password when two step verification is turned on" from Microsoft https://support.microsoft.com/en-us/help/12408/microsoft-account-how-to-use-two-step-verification

They require two codes to reset the password.

**Comment by vinayskushwaha** [comment]
Recently we launched a new [setting](https://docs.aws.amazon.com/cognito/latest/developerguide/how-to-recover-a-user-account.html) to configure user account recovery mechanism. This should help you address your use case. With this setting, you can ensure that a user’s account recovery factor is different from the authentication factor.

**Comment by mlabieniec** [comment]
Closing this given the service update, please let us know if you still are experiencing the issue.
