### ISSUE TITLE
@aws-amplify/api has a vulnerable dependency, Axios:0.17.0

### ISSUE THREAD

**Issue by mrowe009** [aws-amplify/amplify-js#3394]
@aws-amplify/api current version has a vulnerable dependency Axios: 0.17.0

Vulnerable versions: <= 0.18.0
Patched version: 0.19.0

Axios up to and including 0.18.0 allows attackers to cause a denial of service (application crash) by continuing to accepting content after maxContentLength is exceeded.

upgrading to 0.19.0 fixes the issue.

**Comment by jordanranz** [comment]
Hey @mrcoles, we bumped the axios version in this pr:
https://github.com/aws-amplify/amplify-js/pull/3377

It will be published to npm latest soon. Thanks for the heads up.

**Comment by mrowe009** [comment]
how do we get this update?
