### ISSUE TITLE
Add checkboxes into cognito-hosted ui

### ISSUE THREAD

**Issue by dementiev** [aws-amplify/amplify-js#3401]
** Which Category is your question related to? **
Auth, Cognito-Hosted UI

** What AWS Services are you utilizing? **
Userpool federation (Google, Facebook)

** Provide additional details e.g. code snippets **
I wonder if it is possible to add checkboxes into cognito-hosted ui? I want to incorporate mandatory license and terms of use agreements on sign up form provided by cognito-hosted ui. Also, then I need to store the boolean value of the user's choice in user's attributes in the userpool.

**Comment by TalUser** [comment]
Hey, did you find an answer for this, I'm experiencing the same issue.

**Comment by ranganapeiris** [comment]
Hi, I am also on a very similar situation. Any answer on this please?

**Comment by sammartinez** [comment]
@dementiev Amplify JS is used as a pass through to make calls to Amazon Cognito's hosted UI component. We, as Amplify, don't have control over this feature and we recommend to open up a feature request via the [Amazon Cognito forums](https://forums.aws.amazon.com/forum.jspa?forumID=173). Resolving feature request as this use case is controlled by Amazon Cognito

**Comment by arunpatala** [comment]
Hi i need this for terms and conditions. Is anyone able to find a solution?

**Comment by garrettmaring** [comment]
@sammartinez Amplify JS does provide support to handle custom fields using `signUpFields` with `custom` set to `true`. https://github.com/aws-amplify/amplify-js/blob/ef358a761cf74d16b61172cd1a75b4bc6cfd2bdf/packages/aws-amplify-react-native/src/Auth/SignUp.tsx#L157

The behavior to add a required acceptance of a privacy policy and/or TOS is very common in application development. Amplify JS supporting this would provide value.

Rendering `signUpFields` called render `<FormField>`s with the `type`s provided. https://github.com/aws-amplify/amplify-js/blob/ef358a761cf74d16b61172cd1a75b4bc6cfd2bdf/packages/aws-amplify-react-native/src/Auth/SignUp.tsx#L258

`<FormField>` exclusively renders a `<TextInput>` but if that was expanded to support a `checkbox` type 🚀

**Comment by IvanLuchkin** [comment]
Had anyone found a solution for this case?
