### ISSUE TITLE
Federate Login not work when setting multiple URL

### ISSUE THREAD

**Issue by yareyaredesuyo** [aws-amplify/amplify-js#3411]
When setting multiple redirectSignIn and redirectSignout, it doesnt work well

This works well (Tested at http://localhost:3000/) (aws-exports.js)

```js
"redirectSignIn": "http://localhost:3000/",
"redirectSignOut": "http://localhost:3000/",
```

This doesnt work (Tested at http://localhost:3000/")  (aws-exports.js)
```js
"redirectSignIn": "http://localhost:3000/,http://localhost:3001/",
"redirectSignOut": "http://localhost:3000/,http://localhost:3001/",
```

**Comment by haverchuck** [comment]
@yareyaredesuyo Can you please elaborate on what you mean by 'doesn't work well'?
