### ISSUE TITLE
Please throw an error if the credentials are incorrect

### ISSUE THREAD

**Issue by FloStar3000** [aws-amplify/amplify-js#3419]
Hey developers,
**Describe the bug**
 `Storage.get('test.txt')...`, returns a link, that, by clicking on it, lets the browser load for some time and then shows me: "ERR_CONNECTION_REFUSED". It took me a long time to figure out that I misspelled the region :( . I like it that Auth throws an error with a message and code to describe the error

**To Reproduce**
1. Create a React App (with create-react-app)
2. Install (npm) aws-amplify and configure Auhtentication and Storage manually according to the Amplify Javascript documentation. Misspell the S3 bucket region "eu-cental-1" instead of "eu-central-1"
3. Call 
`  getDownloadLink = async () => {
    Storage.get('German-Shepherd-Puppy-Fetch.jpg')
      .then(result => console.log(result))
      .catch(err => console.log(err));
  }`
 with a button click or something. Note that the bucket has CORS configured and the Cognito Identity Pool IAM role specifies read access to the S3 bucket. The file is inside the /public folder of the bucket.
4. Click on the link logged in the console and wonder why there is no picture of a puppy on your screen.

**Expected behavior**
Throw an error like "The provided bucket does not exist" or "resource not found" when the method cannot return a link that actually leads to an existing file.

Maybe I am overreacting or do not understand how the method works but it would be nice if this improvement was possible

Much Love
Florian

**Comment by jamesaucode** [comment]
I believe this is fixed along with #8088

**Comment by abdallahshaban557** [comment]
@FloStar3000 - has your issue been resolved with the latest release of Amplify JS?

**Comment by tannerabread** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and are in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
