### ISSUE TITLE
.aws/credentials file overrides Amazon Cognito credentials when using Storage

### ISSUE THREAD

**Issue by ScubaDrew** [aws-amplify/amplify-js#3420]
**Describe the bug**
I have an application which uses Cognito authentication. After successfully signing in a user I attempt to use Storage.get and I notice that the aws-sdk configures it set up to use my other credentials located in ~/.aws/credentials and not my Cognito user I am signed in as. 

**To Reproduce**
- Setup Amplify for Cognito Authentication like:

`module.exports = {
  Auth: {
    userPoolId: 'us-east-1_YQjskyHwR',
    userPoolWebClientId: '6frt9rrsd51be3ng99k7o4oufh',
    region: 'us-east-1',
    identityPoolId: 'us-east-1:3e0ac62f-244b-442c-b577-41893cf2648c'
  },
  Storage: {
    bucket: 'cloud-ssh',
    region: 'us-east-1',
    level: 'private',
    identityPoolId: 'us-east-1:3e0ac62f-244b-442c-b577-41893cf2648c'
  },
  aws_appsync_graphqlEndpoint: "https://q6jbcdyes5dmtojv37wwytf3ea.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS"
};`

- Successfully Authenticate a user.
- Setup Storage as described in the documentation at https://aws-amplify.github.io/docs/js/storage#manual-setup
- Do a Storage.get operation and you'll notice here https://github.com/aws-amplify/amplify-js/blob/4644b432/packages/storage/src/Storage.ts#L95 a new S3 object is created which will pickup ~/.aws/credentials if they exist in preference over the Cognito user.

**Expected behavior**
Expect Storage to use the Cognito user for operations.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16
 - Browser Chrome

**Comment by haverchuck** [comment]
@ScubaDrew -  I assume that when you say Storage.get you mean Storage.put?

**Comment by haverchuck** [comment]
@ScubaDrew -  Are you running this in Node.JS or otherwise using server-side rendering of some sort?  Typically the aws-sdk has a [credentials provider chain](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CredentialProviderChain.html) which, if so configured, will use local credentials from ~/.aws/credentials.  However, it is strange that this would be happening in a client browser without SSR.
