### ISSUE TITLE
Exposing my security files

### ISSUE THREAD

**Issue by jmandivarapu1** [aws-amplify/amplify-js#3423]
** Which Category is your question related to? **
**AWS AMPLIFY PUBLISH**
** What AWS Services are you utilizing? **
**Storage and Authentication**
** Provide additional details e.g. code snippets **
I have my react website which I delpoyed to cloudfront using the aws publish -c command.
But I went to my website live in the browser In the source files I can see all the 'aws-export.js' with all my details

**So my question Is this fine and expected behaviour?
If somebody sees this can they do anything with it or it is pretty useless?
just worried whether this is a security concern or not for me?** [These files are created automatically while I setup my amplify storage and Auth]

<img width="450" alt="Screen Shot 2019-06-08 at 5 21 59 PM" src="https://user-images.githubusercontent.com/21245519/59152464-6892b400-8a12-11e9-9671-48751046674e.png">

**Comment by dancomanlive** [comment]
aws-exports is added to .gitignore

**Comment by jmandivarapu1** [comment]
> aws-exports is added to .gitignore
I have one more question.... might not be relevant here but if someone knows to answer it helps...

If I don't want my source code visible in the browser if I am deploying using CloudFront Is there any way to do it in CloudFront....
(as amplify already minifying and chunking my files then is there still need for my source files to get uploaded? can I add them to git ignore too? sounds silly but just checking )

**Comment by Defwentz** [comment]
I was looking for the solution to this as well. In your package.json file, add GENERATE_SOURCEMAP=false to the build command and your source code won't show up:
````
scripts: {
  ...,
  "build": "GENERATE_SOURCEMAP=false react-scripts build"
}
```

**Comment by jmandivarapu1** [comment]
> I was looking for the solution to this as well. In your package.json file, add GENERATE_SOURCEMAP=false to the build command and your source code won't show up:
> 
> ```
> scripts: {
>   ...,
>   "build": "GENERATE_SOURCEMAP=false react-scripts build"
> }
> ```

Adding aws-exports is added to .gitignore didn't work.

But ```  "build": "GENERATE_SOURCEMAP=false react-scripts build" ``` worked like a charm it solved all the issues no source code file and no config files only chunk files....Thank you very much for your help... (I think aws need to add this comment to their either CloudFront or code deploy document)
