### ISSUE TITLE
Documentation of the linking requirement is missing

### ISSUE THREAD

**Issue by andidev** [aws-amplify/amplify-js#3424]
**Describe the bug**
Link in documentation leads nowhere. Documentation over the react native linking requirement is missing.

reproduce
1) go to https://aws-amplify.github.io/docs/js/start#step-1-create-a-new-app
2) follow the link to the "linking requirement"
 
nothing happens cause the documentation is missing in the page. Is there no linking requirement any more?

**Comment by andidev** [comment]
Okey so I just found some documentation for how to do the linking for the authentication which is what I am looking for. It is over here https://aws-amplify.github.io/docs/js/react#add-auth

**Comment by haverchuck** [comment]
@andidev I fixed the link to the section you cited... thanks!
