### ISSUE TITLE
Delete linked user from User pool users.

### ISSUE THREAD

**Issue by lenarmazitov** [aws-amplify/amplify-js#3431]
**Describe the bug**
When I link user to existing identity via adminLinkProviderForUser, I get two users in "Users and groups" section in AWS console. It is ok, because second user is just link to original one.
But when I delete one of that I have just created, I can not reach remaining one. I get this instead: 
<img width="1225" alt="Screenshot 2019-06-11 at 21 19 04" src="https://user-images.githubusercontent.com/600133/59296412-9d12a400-8c8e-11e9-8884-1a902276053d.png">

**To Reproduce**
1. Create user in User pool.
2. Link second user to first by adminLinkProviderForUser

```
var params = {
      DestinationUser: {
        ProviderAttributeName: 'Cognito',
        ProviderAttributeValue: "1111111111",
        ProviderName: "Facebook"
      },
      SourceUser: {
        ProviderAttributeName: 'Cognito_Subject',
        ProviderAttributeValue: "222222222",
        ProviderName: "Google"
      },
      UserPoolId: event.userPoolId,
    };
    try {
      await identity.adminLinkProviderForUser(params).promise();
    } catch (e) {
      console.log(e);
      return e;
    }
```

3. Delete one of it in User pool in AWS console
4. Try to access remaining (End)

**Expected behavior**
I should have ability to remove both.

**Comment by codeitcody** [comment]
I stumbled into this too: I found I could delete the user via the Cognito API (or AWS CLI).

Whats odd is that even though linked users show the same `sub` in the Cognito console they are actually stored with different `sub` in the Cognito database. I presume that might be related to this issue.

**Comment by haverchuck** [comment]
@lenarmazitov -  Can you please clarify - do you know that the second user still exists, but just cannot be retrieved?  Or does it appear that the linked user is deleted along with its related record?

**Comment by lenarmazitov** [comment]
@haverchuck I could just suppose that user does not exists, but some link to second federated identity is still remains. And when I click on it in AWS console I can not reach original user, because it was deleted.

**Comment by gluix20** [comment]
Same here, but I can't even delete it with adminDeleteUser from JS SDK, throws a UserNotFoundException. In Cognito User Pool console the user appears though, it also appears with listUser filtered by its username.

I haven't found a way to remove that user, any thoughts?

**Comment by gluix20** [comment]
> @lenarmazitov - Can you please clarify - do you know that the second user still exists, but just cannot be retrieved? Or does it appear that the linked user is deleted along with its related record?

Hi @haverchuck, in my case the user can be retrieved by list-users (both SDK and CLI) and is listed in the console as well. However I can't geit it with admin-get-user not admin-delete-user:

"An error occurred (UserNotFoundException) when calling the AdminDeleteUser operation: User does not exist."
![image](https://user-images.githubusercontent.com/11055106/61495039-10d25b80-a975-11e9-8ac0-6f4a9090238b.png)

And if I click the user in the console gives me this:
![image](https://user-images.githubusercontent.com/11055106/61494934-c7820c00-a974-11e9-9dbf-756ce80c5b1c.png)

**Comment by gluix20** [comment]
> @lenarmazitov - Can you please clarify - do you know that the second user still exists, but just cannot be retrieved? Or does it appear that the linked user is deleted along with its related record?

Hi @haverchuck, in my case the user can be retrieved by list-users (both SDK and CLI) and is listed in the console as well. However I can't geit it with admin-get-user not admin-delete-user:

"An error occurred (UserNotFoundException) when calling the AdminDeleteUser operation: User does not exist."

And if I click the user in the console gives me this:
![image](https://user-images.githubusercontent.com/11055106/61495884-93f4b100-a977-11e9-9b0a-ace8f96f7eff.png)

**Comment by adithep** [comment]
> I stumbled into this too: I found I could delete the user via the Cognito API (or AWS CLI).
> 
> Whats odd is that even though linked users show the same `sub` in the Cognito console they are actually stored with different `sub` in the Cognito database. I presume that might be related to this issue.

How did you delete the user via aws cli? When I try all I get is:

"An error occurred (UserNotFoundException) when calling the AdminDeleteUser operation: User does not exist."

**Comment by campmdabt** [comment]
Has anyone had success with this? Still an issue, and now I've got unlinked orphaned accounts that I cannot access in the console or CLI, though the user shows in both the console `Users and Groups` page as well as in the data returned by `listUsers()`.

**Comment by MJRuskin** [comment]
If you want to delete these unlinked external/provider accounts, do the following:

- Recreate the original Cognito user account that they were linked to
- Disable the provider for this user (i.e. via the AWS CLI command _admin-disable-provider-for-user_)
- Both accounts can now be deleted successfully

**Comment by shiyaskk** [comment]
@codeitcody I'm currently running this in the pre signup trigger
If I start with a native user in the pool and then I try to sign with Google of a user with the same email. Then inside my function, I try to find a matching email in the pool and if so, I link that account with the google one.

After successful linking, I end up with two users with different sub and additionally the UserPassUser now has an "identity" field that contains the Google user data.
 
How do I link then to get the same sub?

**Comment by kiranbabu189** [comment]
@shiyaskk , I too encountered the same issue. when I pass SAML IDP user as a source user and Cognito native user as a destination user.

**Comment by ottokruse** [comment]
Note that this can also happen if you make a mistake in the link command. When linking to existing User Pool users make sure to use the "sub", not the email, of the user as username:

```
aws cognito-idp admin-link-provider-for-user --user-pool-id XXXX --source-user ProviderName=Google,ProviderAttributeName="Cognito_Subject",ProviderAttributeValue="<googleIdIsSomeNumber>" --destination-user ProviderName=Cognito,ProviderAttributeValue=<userSub>
```

@MJRuskin is right that to correct the situation you just have to create the link in a valid way again. Either to a new user (just for the purpose of throwing away again later) or to an existing one.

**Comment by tannerabread** [comment]
Related #469

**Comment by abdallahshaban557** [comment]
Cognito has recently resolved an issue with linking federated users to an existing user profile in Cognito User Pools. As a result, your Amplify application can now merge user identities from 3rd party social identity providers to a Cognito user in a user pool using the Pre sign-up Lambda trigger. You can use the `AdminLinkProviderForUser` API from Cognito to set up custom logic to determine how your user identities get merged. To learn more about the use of this feature, you can check out the following documentation pages.

- API docs: https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminLinkProviderForUser.html
- Cognito guide: https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-identity-federation-consolidate-users.html
- Pre-sign up Lambda https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-sign-up.html

We will work on resources to share with you to explain how to integrate this feature into your Amplify app.

**Comment by nadetastic** [comment]
Following up here - with the way `AdminLinkProviderForUser` currently works, it should not duplicate users but add the identitySub attribute with the IDP values to the user that already exists. Because of this, there shouldn't be a need to delete the linked user from the User pool. We are currently working to update the documentation that describes steps you can take to setup account linking. 

cc @ottokruse @kiranbabu189 @shiyaskk
