### ISSUE TITLE
[aws-amplify-react-native] Add identityId, track prop to S3Album, S3Image Storage calls

### ISSUE THREAD

**Issue by mjmaix** [aws-amplify/amplify-js#3433]
**Expected behavior**
`identityId` prop is passed on `Storage.get` to options inside S3Album, S3Image, S3Text components

This is similar to https://github.com/aws-amplify/amplify-js/pull/2459/

**Comment by ashika01** [comment]
The team is working on some react native improvements right now. This feature would become part of that development.

**Comment by ranjeev75** [comment]
In the meantime what's the best way to display another user's protected images?

**Comment by adriantomas** [comment]
@ranjeev75 using Storage.get() or Storage.list() works fine

**Comment by ranjeev75** [comment]
@adriantomas `Storage.list()` retreives the images, but how to display ie. what is the best way to obtain the url for each image from another user e.g.

`<Image
                                    style={{
                                        width: 100,
                                        height: 100,
                                    }}
                                    source={{ uri: key }} 
                                />}`

the `key` is something like `abc.jpg`, how do we get the correct url of the users image?

**Comment by ashika01** [comment]
@ranjeev75 What @adriantomas suggested. Ultimately we use storage api to achieve our goal underneath the UI.

**Comment by stocaaro** [comment]
All of the related issues are closed. Has this issue been resolved? If not, could you provide the code I would need to reproduce the issue to better understand your use case? 

Thanks!
Aaron

**Comment by stocaaro** [comment]
Closing for now. Feel free to reopen with details on which parts of this request need specific work. There is ongoing work to improve the react native support, but it's not clear to me that there is enough detail in this request to help clarify that ongoing work.

Thanks,
Aaron
