### ISSUE TITLE
NotAuthorizedException: Token is not from a supported provider of this identity pool.

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-js#3437]
Federated sign in using Ionic Angular does not work on mobile devices as it doesn't handle the redirect, so I have to use the Cordova facebook plugin to sign in and get the facebook access token. 

I then pass this to the federated sign in AS PER THE OFFICIAL AMPLIFY GUIDE, yet I am always given this error:

> NotAuthorizedException: Token is not from a supported provider of this identity pool.

`public async loginWithFacebook(): Promise<any> {

    const permissions = ['public_profile', 'email'];

    try {
      const response: FacebookLoginResponse = await this.facebook.login(permissions);
      const { accessToken, expiresIn } = response.authResponse;
      const date = new Date();
      const expires_at = expiresIn * 1000 + date.getTime();
      const userFbData = await this.facebook.api('/me?fields=first_name,last_name,email', permissions);
      console.log(userFbData);
      const user = {
        id: response.authResponse.userID,
        firstName: userFbData.first_name,
        lastName: userFbData.last_name,
        email: userFbData.email,
        picture: `https://graph.facebook.com/v3.3/${response.authResponse.userID}/picture?height=250&width=250`
      };

      console.log('ACCESS TOKEN:' + accessToken);
      console.log('EXPIRES AT: ' + expires_at);
      const federatedUser: FederatedUser = {
        name: user.firstName + ' ' + user.lastName,
        email: user.email
      };
      try {
        const fed: FederatedResponse = { token: accessToken, expires_at };
        const res = await Auth.federatedSignIn('facebook', fed , federatedUser);
        console.log('FEDERATION WORKED');
        console.log(res);
      } catch (err) {
        console.log('FEDERATION ERROR');
        console.log(err.message);
      }

    } catch (err) {
      console.error(err);
    }
  }`

>  const res = await Auth.federatedSignIn('facebook', fed , federatedUser);

This will not work no matter how I approach it and it is blocking us from going to production.

Surely there is a reason for this. I set all my cognito stuff up using the Amplify terminal console and have checked all the IDs align up. 

On desktop in the browser Facebook sign in works absolutely fine.

**Comment by haverchuck** [comment]
When you look at the network request while debugging, do you see the correct identity pool?

```
{
  "IdentityPoolId": "<aws-region:idpool>",
  "Logins": {
    "graph.facebook.com": <long token here>
   }
}
```
Does the network request look the same when made from the browser?
