### ISSUE TITLE
Bug or misuse of Auth.currentAuthenticatedUser()?

### ISSUE THREAD

**Issue by GutteApps** [aws-amplify/amplify-js#3439]
Environment: 
react-native 0.57.8
@aws-amplify/core: 1.0.22
@aws-amplify/auth: 1.2.15

Description:
Our signup flow consists of the following steps:
 1. await Auth.signUp({
      username: email,
      password: create_UUID(),
      attributes: { 'custom:devicePK': JSON.stringify([devicePublicKey]) }
    });
2. await Auth.signIn(email)
3. await Auth.sendCustomChallengeAnswer(tempUser, authenticationCode)

once a user passes this flow we create some unique data for him that we persists locally.

when the user launches the app we check for the existence of the data and call Auth.currentAuthenticatedUser().
if data exists & user exists we consider the user verified and let him in.

using analytics, we noticed that in about 6% of cases, Auth.currentAuthenticatedUser() will throw an error for previously signed in users causing them them to be sent to on-boarding flow. 
 
when these users relaunch the app, Auth.currentAuthenticatedUser() returns a user and they are signed in. 

can you explain this behaviour? is this a bug or we're misusing  Auth.currentAuthenticatedUser()?

**Comment by haverchuck** [comment]
@GutteApps What is error that is being surfaced?  Additionally, do you think it's possible that this behavior is related to a known [AsyncStorage](https://github.com/aws-amplify/amplify-js/issues/3422) issue?
