### ISSUE TITLE
Module not found: Can't resolve 'redux-persist/constants'

### ISSUE THREAD

**Issue by OlivierPT** [aws-amplify/amplify-js#3441]
**Describe the bug**

The Amplify documentation for Appsync SDK advice to use localForage for cache. But when I follow the documentation, I get the following error:

./node_modules/aws-appsync/lib/store.js
Module not found: Can't resolve 'redux-persist/constants' in '$workspace/recycling-hero/node_modules/aws-appsync/lib'

This bug is very anoying because it prevents to use this cache storage option.

There is also an issue referenced for the aw-appsync-sdk and a pull request to  to fix this [issue #410]. 

Maybe someone here could have a look to it.

**To Reproduce**
1. add localForage to dependencies
2. Add localForage to AppSyncClient
3. start the application

**Expected behavior**

No error when application start with localForage as cache.

**Comment by jordanranz** [comment]
I followed up on the AppSync SDK issue and PR. I am going to close this issue now and track this in the AppSync SDK repo.

https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/410
https://github.com/awslabs/aws-mobile-appsync-sdk-js/pull/424
