### ISSUE TITLE
API calls and responses show up in Chrome network tool

### ISSUE THREAD

**Issue by Defwentz** [aws-amplify/amplify-js#3442]
** Which Category is your question related to? **
API, Auth
** What AWS Services are you utilizing? **
Cognito, AppSync, Lambda, 
** Provide additional details e.g. code snippets **
Hello,

I'm building a react static web app, I have it in S3 and distributed by Cloudfront.

The thing is I can see all the api calls and responses in the network tool, is there anything I can do to hide them? I can see my id token, access token in the responses from https://cognito-idp.us-east-1.amazonaws.com/ as well as everything else.

Thank you.

**Comment by jiachen247** [comment]
There is no way to do this. The network tab in the dev tools record all network interactions with the web server. If you go to the big websites like Facebook, Google and Amazon you'll notice you'll be able to find your tokens there too. This is needed to maintain state across a stateless protocol like http(s). I would suggest reading up on the best practices on keeping your tokens safe. The dev console is the least of your worries! Hope this helps!

**Comment by haverchuck** [comment]
@jiachen247 Thanks for your response!  @Defwentz I'm closing this issue for now, but please feel free to open another issue if needed.  If you continue to have concerns, I would suggest taking steps such as customizing the expiration period on these tokens (which can be set for as little as one day).
