### ISSUE TITLE
How to send custom data to Cognito Lambda Trigger Custom Message?

### ISSUE THREAD

**Issue by phanviet** [aws-amplify/amplify-js#3443]
** Which Category is your question related to? **
Authentication

** What AWS Services are you utilizing? **
AWS Cognito

** Provide additional details e.g. code snippets **
I have 3 platforms: mobile, web, admin. In Admin page, we have feature: "Send Reset Password link for a user". An User (A) can login to both mobile & web platform with other roles.
So when Admin trigger "Reset" for A (with role in mobile), Cognito should send link `myapp://<code>`, when Admin trigger "Reset" for A (with role in web), Cognito should send link `https://abc.com/<code>`.
My Problem is in Cognito Hook Lambda Trigger Custom Message, I can't know which role User is (I can see the user `sub` or `email`), so can't send the link reset password exactly. Does we have a way to send custom data such as "role" to Cognito Hook Lambda Trigger Custom Message?

**Comment by haverchuck** [comment]
@phanviet - Just to clarify, the 'role' is derived from the where they execute this action (i.e. web platform, mobile platform, etc) and is not data that is associated with the user?

**Comment by phanviet** [comment]
@haverchuck 
Yes, the `role` is from our DB, not data in Cognito associated with this user.
In admin page:
```
role1 (mobile): 
  - User A     -> send Reset (should send link `myapp://<code>`)
  - User B     -> send Reset

role2 (web):
  - User A     -> send Reset (should send link `https://abc.com/<code>`)
  - User C     -> send Reset
```

**Comment by haverchuck** [comment]
@phanviet It is not possible to send data in this manner right now, but please stay tuned.

**Comment by phanviet** [comment]
@haverchuck Thanks for inform. Just would like to ask one more question: It's not possible with amplify-js or Cognito?

**Comment by sammartinez** [comment]
@phanviet I believe the documentation link will solve this use case. If so, please close this request. 

[Basic Scaffolding for a Custom Auth Challenge](https://aws-amplify.github.io/docs/cli-toolchain/cognito-triggers#basic-scaffolding-for-a-custom-auth-challenge)

**Comment by haverchuck** [comment]
@phanviet This wouldn't help when using the Cognito console as an admin, but with any Amplify app you can now send custom [client metadata](https://aws-amplify.github.io/docs/js/authentication#lambda-triggers) to the Cognito trigger.

This should help!  Closing this issue now, but feel free to open a new one if clientMetadata isn't what you need.
