### ISSUE TITLE
Use browser cache for uploaded images to S3 Storage

### ISSUE THREAD

**Issue by gurobokum** [aws-amplify/amplify-js#3449]
**Is your feature request related to a problem? Please describe.**
I would like to upload images to S3 and show them with browser cache usage. Right now cause `Storage.get` generates different urls all requests use network. I am going to generate urls by my own without custom parameters as https://bucket.s3.amazonaws.com/public/img.png, but `Storage.put` doesn't support uploading files with public access `ACL = "public-read"`

**Describe the solution you'd like**
1. Add `ACL` param to `Storage.put` config https://github.com/JIoJIaJIu/amplify-js/commit/c35299d7d9c8f17ffb58415bf1f8850c12226569
2. Add `s3:PutObjectAcl` to generated `amplify/backend/storage/xxxx/parameters.json` to `s3PermissionsAuthenticatedPublic`

**Describe alternatives you've considered**
to setup `Cloudfront` with `aws cli` which can expose my user static (custom S3)

**Comment by haverchuck** [comment]
@JIoJIaJIu Thanks - we've got this down as a feature request.

**Comment by stocaaro** [comment]
Related to #9418

**Comment by abdallahshaban557** [comment]
We are closing this issue in favor of #9418
