### ISSUE TITLE
UI is not reflective of Auth

### ISSUE THREAD

**Issue by CodySwannGT** [aws-amplify/amplify-js#3451]
**Describe the bug**
``withAuthenticator`` does not reflect the options select with ``amplify add auth``

**To Reproduce**
run ``amplify add auth`` and select email and mobile number instead of username during prompts

**Expected behavior**
``withAuthenticator`` generates sign in and signup forms reflective of the options selected

**Screenshots**
https://www.dropbox.com/s/hzcnovo5xekwtcj/Screenshot%202019-06-13%2019.06.51.png?dl=0

**Desktop (please complete the following information):**
 - OS: any
 - Browser any
 - Version any

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Browser any
 - Version any

**Additional context**

**Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by haverchuck** [comment]
@CodySwannGT - This is definitely an issue and is something we are looking at for a future project.  Thanks for posting the issue.

**Comment by ericclemmons** [comment]
Unfortunately, handling this automatically would have to happen via aws-amplify/amplify-cli#3550.

In the meantime, we've documented how to customize `usernameAlias` here:
> https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#prop-username-alias
