### ISSUE TITLE
Enable support for App Client Secret with Cognito Javascript SDK

### ISSUE THREAD

**Issue by jeff-tenovos** [aws-amplify/amplify-js#3455]
**Is your feature request related to a problem? Please describe.**
I am currently attempting to use the Cognito Javascript SDK to authenticate into an AWS App Client, and in order to do so, the App Client Secret must not be populated, per limitations noted in the Cognito documentation.  However, I would like to apply this same App Client to an AWS Application Load Balancer (ALB) HTTPS rule, which requires that the App Client have the Client Secret populated.

This causes a conflict because I therefore cannot use the Javascript SDK to authenticate into AWS and utilize the same App Client in the HTTPS ALB Rule.

**Describe the solution you'd like**
The solution I would like to see is the support for using the Javascript SDK with a Client Secret-enabled App Client.  I read a comment from 2016 saying that this feature was in progress, but it's now 2019, and the feature is still not here.

**Describe alternatives you've considered**
I do not see any alternatives if I want to use this configuration.  I would either have to use a different authentication library instead of the Javascript SDK, or not enable Authorization for the ALB rule.

**Comment by undefobj** [comment]
@jeff-tenovos can you give details on what your use case is? Amplify is a client library designed for mobile and web applications, having a client secret isn't good practice in these cases. It might make sense to look at an alternative implementation if your use case is outside this scope.

**Comment by jeff-tenovos** [comment]
@undefobj The original use case was to have users authenticate into Cognito, and then access services behind an AWS ALB which is configured with an App Client and HTTPS rules that forwards the user to the relevant service.  The ALB rule would have Cognito Authentication enabled to allow access to the authenticated users only.  However, when enabling Cognito Authentication on the ALB HTTPS Rule with a Secret key-enabled App Client (this is required in order to apply to an ALB Rule), then a user authenticating via the Javascript SDK cannot authenticate into the Secret key-enabled App Client.  Maybe a Java SDK or other mechanism maybe allow authentication?

If the Javascript SDK does not allow authentication against a Secret Key enabled App Client, then how does someone pass through an Authentication-enabled ALB HTTPS Rule?  What is the purpose of enabling authentication on the ALB Rule?

**Comment by jeff-tenovos** [comment]
@undefobj After further research, it seems that the AWS API Gateway may be more flexible with regards to Cognito user authorization, where I can authenticate into Cognito and simply pass the ID Token into an authorized API Gateway method to gain access.

**Comment by jeff-tenovos** [comment]
@undefobj Or does the ALB work similarly to the API Gateway, in that if you also pass the Client Secret in a header attribute along with the Cognito ID Token when submitting a request to the ALB, then you could pass through the ALB?

**Comment by undefobj** [comment]
If you're building a client app, the most recommended approach is to use AWS AppSync or API Gateway. Both of those services support either AWS IAM or JWT Tokens from Cognito. You could potentially use ALB as well here if you don't have all the feature needs of those services. In either case you shouldn't be using a client secret when passing your accessToken to the backend.

**Comment by jeff-tenovos** [comment]
@undefobj Thanks.  If the App Client Secret shouldn't be used when passing an access Token to the backend, then what would be a valid use case for using an App Secret-enabled ALB HTTPS Rule, assuming you are running traffic over HTTPS?

**Comment by Indexu** [comment]
Just encountered a similar use case, not sure if it's the same issue.

I have a React app served via S3 and CloudFront.
The app has its own App Client in the Cognito User Pool, but it needs to access an existing resource hosted on EC2 behind a load balancer.
The load balancer has an authentication rule which uses its own App Client in the same Cognito User Pool and that App Client requires a secret key as well as some OAuth2 settings in order to redirect to the standard AWS hosted login page UI.
The load balancer then stores the credentials in a cookie.

Is this the same issue?
If not, could someone point me in the right direction?

**Comment by jeff-tenovos** [comment]
@Indexu Is your issue that your React can't authenticate into the different App Client configured in the ALB?  My issue is more specific to the use of the AWS Javascript SDK to perform authentication into the App Client, but is not supported with an App Client that enables a Client Secret.  If you're not using AWS Javascript SDK, it's likely a different issue.

As for this issue, since I'm no longer using the ALB as an authenticated gateway, I'm going to close this issue.  It sounds like the AWS Javascript SDK will never support the use of a Cognito App Client with Client Secret, thus never being used with the ALB.

**Comment by Indexu** [comment]
@jeff-tenovos Yeah I tried first using Amplify, then tried the JS SDK in order for the React app to authenticate with the Cognito client that ALB uses.

I too have decided not to use the built-in authentication for ALB due to this.
Currently exploring API Gateway instead, sounds more promising.
