### ISSUE TITLE
PushNotification.onRegister issue at "@aws-amplify/pushnotification" never fixed yet

### ISSUE THREAD

**Issue by amigo1205** [aws-amplify/amplify-js#3460]
PushNotifcation all event handlers triggered only once when an app is installed on new android device for the fist time. After launching once on new device, even though you have app restart many times, it never trigger all events. This issue occurs still on push notification package. never closed!

**Comment by powerful23** [comment]
Related to #3080 #2852

**Comment by powerful23** [comment]
@amigo1205 Hi, about the `onRegister` listener, it will only be triggered when the device token is generated/updated in the service side, which means normally it will only be triggered when the app is installed and opened at the first time. The `PushNotification` module will keep the token in the `AsyncStorage` and send it to the Pinpoint service so the Pinpoint service can now push notification to the device. 

I will update the documentation to add more description to that event handler to make it clearer to use. If you do want to achieve that device token programatically, for now the only way is to look into the `AsyncStorage` and it's stored with the key: `push_token{your_pinpoint_application_id}`.
