### ISSUE TITLE
"No Current User"

### ISSUE THREAD

**Issue by ryanliszewski** [aws-amplify/amplify-js#3464]
**Describe the bug**
Calling `Auth.currentSession()` throws an error that says `no current user`.

**To Reproduce**
1. Open mobile app
1. persist user with `redux-persist`
1. Try to get current Cognito's user session
1. Throws error

**Expected behavior**
User is persisted on app open, cached correctly and can retrieve a valid Cognito user session

**Smartphone (please complete the following information):**
 - OS: Android + iOS
 - Version 1.1.19

**Additional context**
In our current production build, we are using the library `redux-persist` to persist the user and then am calling `Auth.currentSession()` to get the user's JWT token.

Their is another [issue](https://github.com/aws-amplify/amplify-js/issues/399) that references  this bug but with federated sign ins, which we do not use. 

**Sample code**
```js
const getCurrentUserJwtToken = async () => {
  const session = await Auth.currentSession()
  return session.getIdToken().getJwtToken()
}
```

**Comment by sammartinez** [comment]
@ryanliszewski sorry for the late response to this, there are a couple of workarounds towards the end of the issue you called out, can you see if they work for you?

**Comment by jasonwadsworth** [comment]
I'm having this same issue. Has anyone found a workaround or fix?

**Comment by mtahir08** [comment]
Same issue
