### ISSUE TITLE
AppSync subscription silently fails due to too large of an update mutation

### ISSUE THREAD

**Issue by potatopotaro** [aws-amplify/amplify-js#3465]
**Describe the bug**
Although I'm a bit ashamed to admit how I ran into this lol I suppose it'll be helpful for others in the future.

I've been building an MVP for the past few months as fast as I can, and because of my hastiness, I'm using codegen'd statements with a maximum depth of 5 (I plan on writing my queries/mutations with the exact required fields, later). At some point I realized that a subscription for one of my models was not triggering whatsoever; no errors, nada.

I looked into race conditions, compared the generated statements line by line, and couldn't figure it out until I went to the AppSync console and "dumbed down" the mutation and respective subscription. The subscription triggered, phew. I had a few more suspicions but eventually tried reducing my codegen'd statements in max-depth (to 2). This worked.

**To Reproduce**
There are many ways to repro this bug, I believe what matters is that you codegen a mutation that is similar in size, depth, etc. to the one below.

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 12.3

**Additional context**
I assume most people don't codegen with a max-depth of 5, so this probably isn't high priority. I'm leaving this issue for others that may run into this bug.

**Sample code**
The mutation that I believe is too large to trigger a subscription.
(Note: The subscription, with the exact same size and attributes as below, works as is. It appears to strictly be the mutation size which matters.)
```
mutation UpdateIdentity($input: UpdateIdentityInput!) {
  updateIdentity(input: $input) {
    id
    createdAt
    updatedAt
    stripeAccountId
    type
    deactivatedAt
    profilePicture {
      bucket
      key
      region
    }
    firstName
    lastName
    biography
    balance
    personalOrderList {
      items {
        id
        createdAt
        updatedAt
        stripeChargeId
        meal {
          id
          createdAt
          updatedAt
          cookIdentity {
            id
            createdAt
            updatedAt
            stripeAccountId
            type
            deactivatedAt
            firstName
            lastName
            biography
            balance
            placeNameHistory
          }
          orderList {
            nextToken
          }
          pricePerServing
          currency
          name
          description
          pickupAt
          pickupDelayedBy
          keywords
          numServings
          pickupPlaceName
          pickupInstructions
          images {
            bucket
            key
            region
          }
        }
        customerIdentity {
          id
          createdAt
          updatedAt
          stripeAccountId
          type
          deactivatedAt
          profilePicture {
            bucket
            key
            region
          }
          firstName
          lastName
          biography
          balance
          personalOrderList {
            nextToken
          }
          mealList {
            nextToken
          }
          placeNameHistory
        }
        cookIdentity {
          id
          createdAt
          updatedAt
          stripeAccountId
          type
          deactivatedAt
          profilePicture {
            bucket
            key
            region
          }
          firstName
          lastName
          biography
          balance
          personalOrderList {
            nextToken
          }
          mealList {
            nextToken
          }
          placeNameHistory
        }
        cancelledAt
        cancelledBy
        cancellationReason
        cookCompletedAt
        customerCompletedAt
        numServings
        notes
        review
        rating
        tip
      }
      nextToken
    }
    mealList {
      items {
        id
        createdAt
        updatedAt
        cookIdentity {
          id
          createdAt
          updatedAt
          stripeAccountId
          type
          deactivatedAt
          profilePicture {
            bucket
            key
            region
          }
          firstName
          lastName
          biography
          balance
          personalOrderList {
            nextToken
          }
          mealList {
            nextToken
          }
          placeNameHistory
        }
        orderList {
          items {
            id
            createdAt
            updatedAt
            stripeChargeId
            cancelledAt
            cancelledBy
            cancellationReason
            cookCompletedAt
            customerCompletedAt
            numServings
            notes
            review
            rating
            tip
          }
          nextToken
        }
        pricePerServing
        currency
        name
        description
        pickupAt
        pickupDelayedBy
        keywords
        numServings
        pickupPlaceName
        pickupInstructions
        images {
          bucket
          key
          region
        }
      }
      nextToken
    }
    placeNameHistory
  }
}
```

**Comment by undefobj** [comment]
AppSync has a subscription payload size limit of 128kb as outlined here: https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_appsync

Do you believe the mutation is not being triggered, or do you think that's running fine and the subscription is not being fired?

**Comment by potatopotaro** [comment]
Oh whoops, that's a huge detail I left out. I can confirm that the mutation **does** work correctly. It's the subscription that is never triggered. The subscription's error handler isn't called either.

**Comment by undefobj** [comment]
Do you know if it's above the 128kb limit?

**Comment by potatopotaro** [comment]
I can confirm that the mutation's response size is greater than 128kb (it's about 158kb). I'm not entirely sure how I can measure the subscription payload's size, but I imagine it's nearly identical to the mutation's because the schemas are nearly identical.

**Comment by undefobj** [comment]
Ok thanks then there's nothing that can be done from the Amplify side. Might be a good idea for you to open a feature request here: https://github.com/aws/aws-appsync-community

**Comment by potatopotaro** [comment]
Done!
