### ISSUE TITLE
Sumerian support on React Native apps

### ISSUE THREAD

**Issue by josezuazo** [aws-amplify/amplify-js#3480]
Sumerian with react native is currently not possible. The react native DOM concept isn't Sumerian-compatible.

**Comment by jordanranz** [comment]
It may be possible to do inside of a [WebView](https://facebook.github.io/react-native/docs/webview). As of now this is not officially supported.

**Comment by cwomack** [comment]
@josezuazo, the XR category is on a deprecation path. Please see https://github.com/aws-samples/aws-tools-for-babylonjs-editor for examples on using AWS services with Babylon.js.
