### ISSUE TITLE
Auth SignUp auto send another request and throw Error: No credentials, applicationId or region

### ISSUE THREAD

**Issue by namnh06** [aws-amplify/amplify-js#3484]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
I have 2 projects which are using the same code like this: 
 `Auth.signUp({
     username,
      password,
      attributes
    }).then(data => console.log(data)).catch(error => console.log(error)).finally(() => console.log('done'));
`
Just like this: https://aws-amplify.github.io/docs/js/authentication#sign-up
Here is the problem show out:

- In my old project, everything is ok, just 1 request is sign up send to AWS and got some data from it: https://cognito-idp.ap-southeast-2.amazonaws.com/
- In my new project, I have another request go to AWS after the sign up request. There are:
https://cognito-idp.ap-southeast-2.amazonaws.com/
And : https://cognito-identity.ap-southeast-2.amazonaws.com/ which is after the first one and its response is : 

> message: "Unauthenticated access is not supported for this identity pool."
> __type: "NotAuthorizedException"

After that, I got the error in console: Error: No credentials, applicationId or region.

Not sure why is the old project is working fine but with this one, this error show up. Is it because the different in amplify ?

Thanks.

**Comment by namnh06** [comment]
After trying and creating some new project, I notice that every new project got this issues:

> Error: No credentials, applicationId or region

I thought there are some changes in Amplify JS ?

**Comment by laurib** [comment]
Run into same problem with new project

**Comment by gerrytsui** [comment]
Same here. Starting to get this today from the  ng e2e, which tests Auth signin workflow. ( I was fine just yesterday)
"ERROR" Error: Uncaught (in promise): Error: No credentials, applicationId or region

while deployed project is working fine. Very strange.

**Comment by jdavidhermoso** [comment]
+1.

Everything seems to be working fine, but that message appears in console.

![image](https://user-images.githubusercontent.com/7687596/59776104-8da8e180-92b2-11e9-83ea-df264269aa6d.png)

**Comment by gerrytsui** [comment]
Here is what I found so far. ( in my case)
The Uncaught exception  is from AWSPinpointProvider.ts ( line 155 record function: public async record(params, handlers: PromiseHandlers) { }  )

As soon as I disabled Analytics in my project, it works fine without the error. 

I agree the app may works fine for you, but it is not passing my ng e2e testing with that exception.

The fact that there is no code change in my project. I believe it is a change on AWS Pinpoint REST API, combined with obviously, uncaught exception.

**Comment by sammartinez** [comment]
@namnh06 Can you provide a copy of your `package.json`, I want to verify which version you are experiencing this on. Even with creating a new project I would just like to see. Also, can you see about using the latest unstable version running `npm install --save aws-amplify@unstable` or `yarn add aws-amplify@unstable` depending on your build system you are using. Prior to installing the unstable version, see about doing a full removal of your `node_modules` and any lock files you have e.g. `yarn.lock` or `package-lock.json`

**Comment by laurib** [comment]
I get same error with aws-amplify@unstable. Also happens with Auth.signIn()
I have only Auth added to backend

**Comment by gerrytsui** [comment]
I found the conditions that is causing the AWSPintpointProvider.ts error.

IF I **import Analytics from '@aws-amplify/analytics';** even if I don't use it at runtime ( in our project we call analytics.record only in production mode set by **environment.prod.ts** )
AND the JSON to **Amplify.configure** is missing the **"Analytics"**  settings ( again we conditionally add the analytics json using Object.assign to add the analytics configs at runtime)

THEN the Uncaught exception will appear.

The exception start to appear today, an is likely because we upgraded to the latest amplify (stable) sometime this week.

versions details ( everything are the latest stable except TypeScript is at 3.4.5)
    "@aws-amplify/analytics": "^1.2.17",
    "@aws-amplify/api": "^1.0.36",
    "@aws-amplify/auth": "^1.2.25",
    "@aws-amplify/ui": "^1.0.20",
    "aws-amplify-angular": "^3.0.4",

Angular 8.0.3

**Comment by laurib** [comment]
My aws-exports.js file is 
```
const awsmobile = {
    "aws_project_region": "...",
    "aws_cognito_identity_pool_id": "...",
    "aws_cognito_region": "...",
    "aws_user_pools_id": "...",
    "aws_user_pools_web_client_id": "...",
    "oauth": {}
};
export default awsmobile;
```

Should there be generated `Auth: {}` ?

I kind of remember that there used to be...

**Comment by namnh06** [comment]
> @namnh06 Can you provide a copy of your `package.json`, I want to verify which version you are experiencing this on. Even with creating a new project I would just like to see. Also, can you see about using the latest unstable version running `npm install --save aws-amplify@unstable` or `yarn add aws-amplify@unstable` depending on your build system you are using. Prior to installing the unstable version, see about doing a full removal of your `node_modules` and any lock files you have e.g. `yarn.lock` or `package-lock.json`

Hi @sammartinez ,
For your information:
- New Project:
```
"aws-amplify": "^1.1.29",
"aws-amplify-angular": "^3.0.4"
```
- Old Project:
```
"aws-amplify": "^1.1.28",
"aws-amplify-angular": "^3.0.3"
```
for the whole package.json, you can look at it here: https://gist.github.com/namnh06/336b49acac9edefc4df152a6b3024c46

I tried to remove everything & install aws-amplify with the version like the old one but no luck.

> Also, can you see about using the latest unstable version running npm install --save aws-amplify@unstable or yarn add aws-amplify@unstable depending on your build system you are using. Prior to installing the unstable version, see about doing a full removal of your node_modules and any lock files you have e.g. yarn.lock or package-lock.json

Tried it, no luck either.

I thought @gerrytsui was right and wrong, because of if API, so, the old project should be affect too, but there is not.

**Comment by ilya-bmi** [comment]
I get the same error with react native after an update.
aws-amplify@1.1.29 
"react": "16.8.3",
"react-native": "0.59.9",

**Comment by arjunsk** [comment]
I had posted a question regarding the same: https://stackoverflow.com/questions/56680112/bad-request-is-returned-when-amplify-is-configured-for-hosted-ui-in-angular-6

**Comment by namnh06** [comment]
@arjunsk I got one from yesterday, but no luck till now : https://stackoverflow.com/questions/56659183/amplify-auth-signup-auto-send-another-request-and-throw-error-no-credentials-a

**Comment by arjunsk** [comment]
Got it working: https://stackoverflow.com/questions/56680112/bad-request-is-returned-when-amplify-is-configured-for-hosted-ui-in-angular-6/56685607#56685607

**Comment by jenshandersson** [comment]
I got it working by reverting `@aws-amplify/analytics` to `1.2.16`.

```
"aws-amplify": "1.1.28",
"@aws-amplify/analytics": "1.2.16",
```

**Comment by filipemcg** [comment]
I solved this by only setting:

`"aws-amplify": "1.1.28"`

Can confirm this works

**Comment by filipemcg** [comment]
Just noticed that the console error persists, but the signUp flow is unblocked by setting:

`"aws-amplify": "1.1.28"`

The error remains:
![image](https://user-images.githubusercontent.com/24497198/59874137-7858b380-9395-11e9-8ed4-3ba98ac52fdc.png)

Still needs a bit of tweaking so that we can surpass this.

**Comment by mahcr** [comment]
I'm experiencing the same issue but I'm not using `@aws-amplify/analytics`.

**Comment by filipemcg** [comment]
> I'm experiencing the same issue but I'm not using `@aws-amplify/analytics`.

Are you sure you have not imported the whole aws-amplify package?

**Comment by mahcr** [comment]
@filipemcg  oh oh oh. Thanks for the tip! using only `@aws-amplify/core` `@aws-amplify/auth` fixed the problem!

**Comment by adnan333bd** [comment]
we are not using analytics, but updating all imports like the following [no aws-amplify] solved the issue .. 
import Amplify from '@aws-amplify/core';
import Auth from '@aws-amplify/auth';
import { Hub } from '@aws-amplify/core';

**Comment by WhatIsHeDoing** [comment]
Disabling as per the [docs](https://aws-amplify.github.io/docs/js/analytics) fixed this for me.

**Comment by jordanranz** [comment]
#3614 should prevent "Error: No credentials, applicationId or region." from occurring when Analytics is not be used or configured.

**Comment by pwfcurry** [comment]
> Disabling as per the [docs](https://aws-amplify.github.io/docs/js/analytics) fixed this for me.

Thanks, this worked!

You can also suppress the warning if disabling analytics doesn't fix the issue:

```
YellowBox.ignoreWarnings(["No credentials, applicationId or region"]);
```

**Comment by nihp** [comment]
I am also facing this issue now.

I am using the below versions.

```
  "aws-amplify": "^2.2.5",
    "aws-amplify-react-native": "^3.2.2",
```

**Comment by sanyashvets** [comment]
In your configs:
```
{
  Auth: {
    identityPoolId: 'REGION_STR:xxxxxxxxxxxxxx', 
    region: 'REGION_STR',
  },
  Analytics: {
    AWSPinpoint: {
      // Amazon Pinpoint App Client ID
      appId: 'xxxxxxxxxxx',
      // Amazon service region
      region: 'us-east-1'
    }
  }
};
```

* MAKE SURE THAT `identityPoolId` starts from `i`, NOT FROM `I` * (thanks for incorrect docs and examples)

**Comment by nihp** [comment]
> we are not using analytics, but updating all imports like the following [no aws-amplify] solved the issue ..
> 
> ```
> import Amplify from '@aws-amplify/core';
> import Auth from '@aws-amplify/auth';
> import { Hub } from '@aws-amplify/core';
> ```



> @filipemcg oh oh oh. Thanks for the tip! using only `@aws-amplify/core` `@aws-amplify/auth` fixed the problem!

Above solutions not worked for me

I am using aws-amplify and aws-amplify-react-native

**Comment by aleckzts** [comment]
> > we are not using analytics, but updating all imports like the following [no aws-amplify] solved the issue ..
> > ```
> > import Amplify from '@aws-amplify/core';
> > import Auth from '@aws-amplify/auth';
> > import { Hub } from '@aws-amplify/core';
> > ```
> 
> > @filipemcg oh oh oh. Thanks for the tip! using only `@aws-amplify/core` `@aws-amplify/auth` fixed the problem!
> 
> Above solutions not worked for me
> 
> I am using aws-amplify and aws-amplify-react-native

The following solution is working for me. Have to manually disable Analytics when using with React Native:

```
import awsconfig from './aws-exports';
Amplify.configure({
    ...awsconfig,
    Analytics: { 
      disabled: true
    }
});
```

**Comment by gruckionvit** [comment]
This is still an issue, disabling the analytics is not the right solution. Are there any status updates on this? Did anyone figure out what's causing it
