### ISSUE TITLE
Server error when trying to login with Facebook federatedSignIn

### ISSUE THREAD

**Issue by anuradhawick** [aws-amplify/amplify-js#3488]
### Description
I had successfully setup Facebook and Google sign in using federatedSignIn method in the Auth module. However, recently the flow breaks returning a server error.

### My Config
```js
aws_config: {
    Auth: {
      identityPoolId: 'ap-southeast-1:my id',
      region: 'ap-southeast-1',
      userPoolId: 'ap-southeast-my id',
      userPoolWebClientId: 'my client id',
      mandatorySignIn: false,
    },
  },
  oauth: {
    domain: 'my domain.auth.ap-southeast-1.amazoncognito.com',
    scope: ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
    redirectSignIn: 'http://localhost:4200/',
    redirectSignOut: 'http://localhost:4200/',
    responseType: 'code'
  }
```
### Steps to reproduce the behavior:
In my authenticator service (As I am using angular) the method is as follows
```js
  loginFacebook() {
    Auth.federatedSignIn({customProvider: 'Facebook'}).then(() => {

    }).catch(e => {
      console.log(e);
    });
  }
```

### Expected behaviour
The redirect after user authorization should come with access code followed by login success event in the following handler.
```js
Hub.listen('auth', (data) => {
        switch (data.payload.event) {
          case 'signIn':
            console.log('Login success');
            Auth.currentAuthenticatedUser().then((u) => {
              this.processUser(u);
              resolve(true);
            }).catch((e) => {
            });
            break;
          case 'signOut':
            console.log('Logout success');
            this.isLoggedIn = false;
            this.user = null;
            this.autoLogin = false;
            resolve(false);
            break;
        }
      });
```
### Current behaviour

The user gets redirected to 
`https://www.vinyl.lk/?error_description=Exception%20processing%20authorization%20code&state=GiFNGdcwLTaut52DH6qsZWuSoMaQWPVH&error=server_error#_=_`

Apparently, the code is retrieved. However, it is not processed by cognito for some reason. Google login works perfect and Facebook login tend to fail like this. (In rare cases the login happens as expected.)

### The network calls relevant to the use case
![image](https://user-images.githubusercontent.com/9621844/59759419-5e569c80-92d3-11e9-9b36-c21b2b984a85.png)

### Versions of SDK used
 ```
    ...
    "amazon-cognito-identity-js": "^3.0.12",
    "aws-amplify": "^1.1.29-unstable.0",
    "aws-sdk": "^2.466.0",
    ...
```
Note: I tried with stable version "1.1.29" still not luck (which used to work perfectly on either of version before sometime.

**Comment by malithjkmt** [comment]
Same observation on react native project.
Facebook login worked well last week. But now it fails sometimes with `Error: Exception+processing+authorization+code` while Google login works 100%
@powerful23  any idea about this?

**Comment by Damith2323** [comment]
I am having the same issue

**Comment by cliffordh** [comment]
Same issue... tbh, I'm glad it's not just me! Looking forward to a solution.

**Comment by iamdavidmartin** [comment]
I get this error when using a custom urlOpener on expo, but I don't get the error with the default config that has app switching. Below is my urlOpener code:
````const urlOpener = async (url, redirectUrl) => {
  // On Expo, use WebBrowser.openAuthSessionAsync to open the Hosted UI pages.
  const { type, url: newUrl } = await WebBrowser.openAuthSessionAsync(
    url,
    redirectUrl
  );

  if (type === "success") {
    await WebBrowser.dismissBrowser();

    if (Platform.OS === "ios") {
      console.log(newUrl);
      return Linking.openURL(newUrl);
    }
  }
};```

**Comment by cliffordh** [comment]
any update? We're close to launching our site and this core functionality is broken.

**Comment by powerful23** [comment]
@cliffordh I think it's a server side error, will bring it to the service team. In the meantime, can you try using `token` as the `responseType` and enable `Implicit grant` in `Allowed OAuth Flows` in the app client setting? It's not going to fix the issue but if you can login with that flow, it could be a temporary work around for you.

**Comment by mmieszek** [comment]
This might be the same issue as https://forums.aws.amazon.com/thread.jspa?messageID=904500

I am getting it each time when using OpenID Connect Identity Provider defined in my Amplify User Pool.

@powerful23 I am not sure if I can change the responseType to token as the endpoints are called by Cognito with `code` response type even when I set it to `token` for Cognito OAuth configuration. Please let me know if there is a way to do it differently.

**Comment by gdsoumya** [comment]
Getting the same error with Hosted UI. I am using Google and Facebook federated login with the userpool. Surprisingly previous users are getting the access tokens when the login in with google/facebook but the new ones who are just signing up aren't.  Please look into it asap.

**Comment by deak-s** [comment]
I had the same error but it turns out I had tried to map attributes that Google wasn't returning. 

I found this helpful https://stackoverflow.com/a/56979795/10929504

**Comment by MatteoGioioso** [comment]
Same error here with hosted UI, `error_description=Exception+processing+authorization+code&error=server_error`

**Comment by d0utone** [comment]
Weirdly, I am getting this error only if I have a trailing / in the path. If I remove it from the url in the aws-exports.js and from the redirect_url parameter, the error does not occur.

Unfortunately in the amplify-cli the "/" is mandatory.
