### ISSUE TITLE
Using Cognito authorizers with API-Gateway

### ISSUE THREAD

**Issue by kay-is** [aws-amplify/amplify-js#3491]
**Which Category is your question related to?**
Cognito

**What AWS Services are you utilizing?**
Lambda, API-Gateway, and Cognito via SAM. I'm posting this here because as far as I know, Cognito is part of Amplify.

**Provide additional details e.g. code snippets**
I wanted to add a Cognito authorizer to my API.

I use a Lambda with two API endpoints to handle sign in and signup.

The sign in endpoint returns an ID token to the client.

When I use the AWS Console (API-Gateway -> My API -> Authorizers -> Cognito Authorizer -> Test) I can paste the ID token I received in my Lambda and it works.

When I add the token to a browser request header, it doesn't work.

Also, it takes like 7 seconds to receive the token in my function.

This is the code I use to get a token from Cognito:

```javascript
const signIn = (username, password) => {
  const authenticationDetails = new Cognito.AuthenticationDetails({
    Username: username,
    Password: password
  });
  
  const cognitoUser = new Cognito.CognitoUser({
    Username : username,
    Pool: userPool
  });

  return new Promise((resolve, reject) =>
    cognitoUser.authenticateUser(authenticationDetails, {
      onSuccess: result => {
        const token = result.getIdToken().getJwtToken();
        resolve(token);
      },
      onFailure: error => {
        console.log(error);
        reject(error);
      }
    })
  );
};
```
And I add the token to my headers with:

```javascript
fetch(API_ENDPOINT, {
  headers: {
    Authorization: token
  }
})
```

cc @dabit3

**Comment by sammartinez** [comment]
@kay-is We do use Cognito for our [Authentication](https://aws-amplify.github.io/docs/js/authentication) piece of our library, however, Cognito is it's own team within AWS. For this question, I feel that you would have a better explanation from the Cognito team themselves which you can contact them via their [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=173). Ill leave this open for now if you do want to explore Amplify and have any further questions regarding Amplify.

**Comment by kay-is** [comment]
Okay, I posted it in the [Cognito AWS Forums](https://forums.aws.amazon.com/thread.jspa?threadID=305004)
