### ISSUE TITLE
Multiple tab login using different logins

### ISSUE THREAD

**Issue by VamsiDharmaji** [aws-amplify/amplify-js#3492]
** Which Category is your question related to? **
Authentication

** What AWS Services are you utilizing? **
AWS Cognito

** Provide additional details e.g. code snippets **
We are using AWS Amplify with Angular using the default options for storage ( Local Storage ), I am trying to find a clean way to support multiple tab login scenario. 

Amplify creates 5 local storage keys on each successful login 

1. Access Token
2. Id Token
3. Refresh Token
4. Clock Drift
5. User Data

Along with the 5 items Amplify uses **LastAuthUser** to keep track of the last logged in user.

Is User1 logs in Tab1 and User 2 logs in Tab2, whrn you go back to tab1 and try triggering the behavior to call the API and see that the User 2 id token is being passed. 

_FYI , I am using the cache to avoid any performance issues_ ( byPassCache:false)

Is there any code samples to demonstrate the recommended way to handle this scenario.

 The only option I see so far is to track changes on the **LastAuthUser** and if there is any change then log out all the tabs irrespective of the logged in user.

Appreciate  any help on this.

**Comment by ericclemmons** [comment]
@VamsiDharmaji This is an interesting dilemma! I'd like to understand more the use-case behind having different users logged in under different accounts on the same machine.  Could you share more on that?

In the meantime, `Auth` storage currently defaults to `window.localStorage`, but you can change it based on the instructions here:
> https://aws-amplify.github.io/docs/js/authentication#manual-setup

For example, I was able to switch to `window.sessionStorage` which differs from `window.localStorage` in that each tab is a new session:
> https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API

```diff
--- a/src/App.js
+++ b/src/App.js
@@ -14,6 +14,13 @@ import Amplify from 'aws-amplify';
 import awsconfig from './aws-exports';

+awsconfig.Auth = {
+  ...awsconfig.Auth,
+  storage: window.sessionStorage
+};
+
 Amplify.configure(awsconfig);
```

We have some work to do to differentiate `localStorage` sessions, but let me know if this small change addresses your problem in the meantime.
