### ISSUE TITLE
Passwordless Magic Sign In with Email Link - A working workaround

### ISSUE THREAD

**Issue by cliffordh** [aws-amplify/amplify-js#3500]
So I spent a lot of time trying to use the Auth Challenge solution to implement a passwordless signin and eventually took a completely different approach. I hope this information is useful to someone, and/or someone tells me I'm crazy for doing auth like this :-)

At a high level here's how it works:

One component which handles both signin/up with a single email input address field.
One component that handles confirmation, no user interface except "Please wait...".
One lambda handling pre-signup and custom message triggers.

In the signin component I randomly generate a password.

Call Auth.signUp(username,random_password);
The user is auto confirmed due to the lambda trigger.

Upon returning from Auth.signUp go down two separate paths depending on the return:

```
this.$Amplify.Auth.signUp(user)
        .then(data => {
          this.resetPassword(data);
        })
        .catch(e => {
          if (e.code && e.code === "UsernameExistsException") {
            this.resetPassword();
          } else {
            this.setError(e);
          }
        });
    },
    resetPassword: function(data) {
      this.$Amplify.Auth.forgotPassword(this.email)
        .then(() => {
        })
        .catch(err => {
        });
    },
```

Basically, signup a user. If the signup is successful call forgotPassword. Otherwise, if the user already exists, call forgotPassword. 

And, here's the Lambda code which is invoked on signup and on forgot password.

```
exports.handler = async(event, context, callback) => {
  console.log(event.triggerSource);
  console.log(event);

  if (event.triggerSource === "PreSignUp_SignUp") {
    event["response"] = {
      autoConfirmUser: true,
      autoVerifyEmail: true,
      autoVerifyPhone: false
    };
  }
  
  if (event.triggerSource === "CustomMessage_ForgotPassword") {
    const { codeParameter } = event.request;
    const { userName, region } = event;
    const { clientId } = event.callerContext;
    const { email } = event.request.userAttributes;

    const url = 'http://localhost:8080/confirm/';
    const link = `<a href="${url}?validation=${codeParameter}&email=${email}" target="_blank">here</a>`;
    event.response.emailSubject = "Magic Sign In";
    event.response.emailMessage = `We received a request to Sign In. Click ${link} to Sign In, otherwise, ignore this email.`;
  }

  callback(null, event);
};
```
The above lambda triggers an email with a link to a confirmation route in my app. Here's how I'm handling the confirmation in the app:

```
    let validationcode = this.$route.query.validation;
    let email = this.$route.query.email;
    let password = ** generate your random password here **

    this.$Amplify.Auth.forgotPasswordSubmit(email, validationcode, password)
      .then(() => {
        this.$Amplify.Auth.signIn(email, password)
          .then(user => {
            this.$router.push({ name: "home" });
          })
          .catch(err => console.log(err));
      })
      .catch(err => {
        this.setError(err);
      });
```
The above code extracts the forgot password validation code from the URL and calls Auth.forgotPasswordSubmit with the email, code and a newly generated password.

At this point, the user is signed in. Note, I do make an additional call to Auth.signIn with the new information. This step may be unnecessary as forgotPasswordSubmit seems to give you an authenticated user. However, I want accurate signin metrics and I'm not sure forgot password gives me that (it doesn't appear to fire the authentication triggers).

I've got this flow working quite well alongside Google and Facebook social signin.

My client-side random password generator code:

```
let password =
      randomCharGenerator(8, "lower") +
      randomCharGenerator(8, "upper") +
      randomCharGenerator(8, "number") +
      randomCharGenerator(8, "symbol");

export function randomCharGenerator(len, codeType) {
  var text = "";
  // *TODO*: replace with more secure password generation
  var charset = "abcdefghijklmnopqrstuvwxyz";
  switch (codeType) {
    case "upper":
      charset = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
      break;
    case "number":
      charset = "01234567890";
      break;
    case "symbol":
      charset = "!@#$^&*()";
      break;
  }

  for (var i = 0; i < len; i++)
    text += charset.charAt(Math.floor(Math.random() * charset.length));

  return text;
}
```

I'm open to critiques, suggestions, etc. I'm sharing this authentication code and flow in the hopes that it is helpful to someone else and for review by other developers. I'm aware that Math.random is not "cryptographically" secure and I may end up generating the password in a Lambda triggered via API gateway (I've tried it, it works)... but I'm not sure the added complexity buys me a whole lot and will likely stick to a client-side password generator.

Thanks,
Cliff

**Comment by farminf** [comment]
Hi @cliffordh,
very cool solution comparing to https://aws.amazon.com/blogs/mobile/implementing-passwordless-email-authentication-with-amazon-cognito/
the only issue I see is that cognito has a limitation on number of time you can do forgotPassword I guess. have you ever had any issue related to this?

**Comment by cliffordh** [comment]
From what I can tell the ForgotPassword soft limit is 5 resets within a non-disclosed timeframe, likely an hour or so. There doesn't seem to be a global ForgotPassword limit for a user pool. I have de-emphasized passwordless email login on our signin/up pages and am primarily receiving social logins. You can view a pre-production site live here: https://www.jspell.com/checker/ The passwordless email signin option is on the "sign in" flow, not on the "get started" flow where social is the only login method. This flow is heavily modeled after Medium.com (feedback appreciated!)

**Comment by farminf** [comment]
@cliffordh We've also implemented a product with this approach, and this is only option to sign in... I can say it works really good by now. The only thing I don't like is the fact that now we have some users in the pool which are mistaken because users misspelled their email. I'm storing a user record also in a dynamodb table with verification column (I make it true after PostConfirmation_ConfirmForgotPassword) to understand who is a verified user.

**Comment by cliffordh** [comment]
@farminf I was considering a silent recaptcha (Recaptcha v3) for this case but might do as you suggest to not affect signup abandonment. Thanks for the feedback!

**Comment by waydelyle** [comment]
I managed to get it working and left a comment
https://github.com/aws-amplify/amplify-js/issues/1896#issuecomment-539452876

**Comment by nadetastic** [comment]
https://github.com/aws-amplify/amplify-js/issues/1896

**Comment by nadetastic** [comment]
Closing this issue out in favor of #1896
