### ISSUE TITLE
Auth.signOut() doesn't redirect to the Cognito Hosted UI logout endpoint

### ISSUE THREAD

**Issue by ottokruse** [aws-amplify/amplify-js#3501]
This is an OAuth scenario with the Cognito hosted UI

See sample code below. When clicking the signOut button I see that cookies get cleared, but the browser is not redirected to the /logout endpoint which I think it should be doing. Because it doesn't do that, the user remains logged in at Cognito.

```javascript
import React, { useState, useEffect } from 'react';
import Amplify, { Auth, Hub } from 'aws-amplify';

Amplify.configure({
  Auth: {
    region: 'us-east-1',
    userPoolId: 'xxx',
    userPoolWebClientId: 'xxx',
    cookieStorage: {
      domain: 'xxx',
    },
    oauth: {
      domain: 'xxx.us-east-1.amazoncognito.com',
      scope: ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
      redirectSignIn: 'xxx/parseauth',
      redirectSignOut: 'xxx/',
      responseType: 'code',
    },
  }
});


function App() {
  const [user, setUser] = useState(null);

  useEffect(() => {
    const subscribeToHub = async () => {
      Hub.listen("auth", ({ payload: { event, data } }) => {
        switch (event) {
          case "signIn":
            setUser(data);
            break;
          case "signOut":
            setUser(null);
            break;
          default:
            break;
        }
      });
    };
    subscribeToHub();
  }, []);

  useEffect(() => {
    Auth.currentAuthenticatedUser()
    .then(setUser)
    .catch(console.error);
  }, []);

  return (
    <div>
      <header>
          {user && <p>Hi {user.username}!!</p>}
          {!user && <p>You are not signed in</p>}
          <button onClick={() => Auth.federatedSignIn()}>Open Hosted UI</button>
          <button onClick={() => Auth.signOut()}>Sign Out</button>
      </header>
    </div>
  );
}

export default App;
```

**Comment by ottokruse** [comment]
I figured out what it is. I was using an approach where I set auth cookies server side. I based that implementation on amazon-cognito-auth-js. But Amplify also needs another cookie to be set: 'amplify-signin-with-hostedUI'. After setting that to true, Auth.signOut() works again as expected.

**Comment by charleswduk** [comment]
I'm struggling with this one too...I've configured Amplify to use cookie storage for auth, but using Auth.signOut() doesn't work properly. Clicking on Auth.federatedSignIn() signs users straight in again because the cookies set by cognito remain. 

I tried adding the cookie @ottokruse suggested, but this did not work.

Does anyone have a working implementation using Amplify, Cognito Hosted UI and cookie storage? 

The Cognito Hosted UI seems to have disappeared from v2 of the JS Amplify docs...I hope it's still being supported.

Any help much appreciated - thanks!

**Comment by kennethesguerra** [comment]
> I'm struggling with this one too...I've configured Amplify to use cookie storage for auth, but using Auth.signOut() doesn't work properly. Clicking on Auth.federatedSignIn() signs users straight in again because the cookies set by cognito remain.
> 
> I tried adding the cookie @ottokruse suggested, but this did not work.
> 
> Does anyone have a working implementation using Amplify, Cognito Hosted UI and cookie storage?
> 
> The Cognito Hosted UI seems to have disappeared from v2 of the JS Amplify docs...I hope it's still being supported.
> 
> Any help much appreciated - thanks!

@charleswduk same situation also. Have you already found the workaround on this? This has been an issue a year ago though in amplify https://github.com/aws-amplify/amplify-js/issues/3435

**Comment by charleswduk** [comment]
@kennethesguerra Didn't find a solution. I'm thinking about integrating with Cognito directly, but haven't investigated whether this will help yet... If anyone finds a solution that works with Amplify, please let me know, as I would much rather stick with it!
