### ISSUE TITLE
Unable to resolve "aws-sdk/clients/personalizeevents"

### ISSUE THREAD

**Issue by nicksmithr** [aws-amplify/amplify-js#3504]
**Describe the bug**

Adding Amplify to React Native, even when disabling analytics, tries to use analytics and fails from the aws-sdk.

Adding the aws-sdk helps, but that duplicates having the dependency.

**To Reproduce**
Adding amplify to a React Native project generate
Configuring manually amplify.
```
Amplify.configure({
  Auth: {
    // REQUIRED - Amazon Cognito Identity Pool ID
    identityPoolId: Cognito.IDENTITY_POOL_ID,
    // REQUIRED - Amazon Cognito Region
    region: Cognito.REGION,
    // OPTIONAL - Amazon Cognito User Pool ID
    userPoolId: Cognito.USER_POOL_ID,
    identityPoolRegion: Cognito.REGION,
    // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
    userPoolWebClientId: Cognito.APP_CLIENT_ID
    // OPTIONAL - Enforce user authentication prior to accessing AWS resources or not
    // mandatorySignIn: true
  },
  Analytics: {
    disabled: true
  }
});
```

React Native won't start — 

```
Unable to resolve "aws-sdk/clients/personalizeevents" from "node_modules/@aws-amplify/analytics/lib/Providers/AmazonPersonalizeProvider.js"
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by powerful23** [comment]
@nicksmithr the `aws-sdk/clients/personalizeevents` exists in the `aws-sdk` version `2.474.0` and when you install amplify, it will install that version for you. Please check your `package.json` and `node_modules` to make sure no other versions of `aws-sdk` exist. It would help a lot if you can paste the `dependencies`  and `devdependencies` of your `package.json` here.

**Comment by nicksmithr** [comment]
Hi @powerful23 , I removed another duplicate of `aws-sdk` and the error persisted.
It seemed to be caused by the fact I was doing:

`import Amplify from "amplify";`
Instead of:
`import Amplify from "@aws-amplify/core";`

**Comment by mayankrungta** [comment]
> Hi @powerful23 , I removed another duplicate of `aws-sdk` and the error persisted.
> It seemed to be caused by the fact I was doing:
> 
> `import Amplify from "amplify";`
> Instead of:
> `import Amplify from "@aws-amplify/core";`

This did not help in my case. Is it some recommended practice as the documents all recommend -

import Amplify from "amplify";

For example check this - 

https://aws-amplify.github.io/docs/js/start?platform=angular#step-4-integrate-aws-resources

I am not able to across this problem. Kindly advise.

**Comment by mayankrungta** [comment]
> @nicksmithr the `aws-sdk/clients/personalizeevents` exists in the `aws-sdk` version `2.474.0` and when you install amplify, it will install that version for you. Please check your `package.json` and `node_modules` to make sure no other versions of `aws-sdk` exist. It would help a lot if you can paste the `dependencies` and `devdependencies` of your `package.json` here.

It is difficult to track upgrades but Amplify was not working so I had to update it and once I upgraded I started getting this error. The details of the upgrade can be seen in the image below -

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/1388979/60988813-12db5f80-a362-11e9-9bfd-bc3e7adb2767.png">

@powerful23 kindly advise how to go about this. Am I missing something?

**Comment by mackattack3k** [comment]
I resolved this by adding `aws-sdk` to my installation. Does anyone have another solution?

**Comment by emaildano** [comment]
> I resolved this by adding `aws-sdk` to my installation. Does anyone have another solution?

This resolved it for me as well.

**Comment by tncbbthositg** [comment]
> I resolved this by adding `aws-sdk` to my installation. Does anyone have another solution?

@mackattack3k, what do you mean you added it to your installation?

**Comment by mackattack3k** [comment]
@tncbbthositg With my packet manager e.g. `yarn add aws-sdk` or `npm i aws-sdk`
