### ISSUE TITLE
Add user to UserPool not IdentityPool after using Auth.federateSignIn

### ISSUE THREAD

**Issue by uchar** [aws-amplify/amplify-js#3515]
**Which Category is your question related to?**
Amplify,Authentication

**What AWS Services are you utilizing?**
Cognito

**Provide additional details e.g. code snippets**
I'm using RN-google-sign-in plugin in react native, after login I pass it's token to `Auth.federateSignIn `

It works find and login finish successfully but the problem is the user does not show up in Cognito user pool and it seems that it's using Identity pool. How can I add this user to the User pool instead of Identity pool ?

    await GoogleSignin.hasPlayServices();
    await GoogleSignin.signIn();
    var userData = await GoogleSignin.getCurrentUser();
    const { idToken, user } = userData;
    const {email,name}=user;
    const credentials =
    await Auth.federatedSignIn('google', { token: idToken, expires_at: null }, userData);

    if (credentials.authenticated) {
      console.log("Authentication succeed")
      //What should I do next to add this user to UserPool?
    }

**Comment by haverchuck** [comment]
@uchar Could you try following the documentation [here](https://aws-amplify.github.io/docs/js/authentication#oauth-and-hosted-ui)?
