### ISSUE TITLE
Auth Using withAuthenticator HOC 

### ISSUE THREAD

**Issue by jeffxor** [aws-amplify/amplify-js#3518]
** Which Category is your question related to? **
Auth Using withAuthenticator HOC 
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **

I have followed the basic setup with Google Sign Up following the Amplify documentation.
 
Adding `amplify add auth` everything seems correct and works when using the url provided at the end of the auth set up. It will take me through auth flow and redirects to my app correctly and also adds a new user into my user pool.

`https://<domain>.us-east-1.amazoncognito.com/login?response_type=code&client_id=<client id>&redirect_uri=http://localhost:3000/auth/signin/`

When I attempt to run locally by wrapping my app withAuthenticator

`ReactDOM.render(<AppWithAuth includeGreetings={true} federated={myFederatedConfig}/> , document.getElementById('root'));` 

I get the Amplify sign in screen as expected and can see the google login option. Upon correct login with google, I get errors in the flow and get stuck on the amplify login screen. 

`POST https://cognito-identity.us-east-1.amazonaws.com/ 400`
`json.js:54 Uncaught (in promise) NotAuthorizedException: Token is not from a supported provider of this identity pool.`

I am assuming I am doing something wrong here or am unsure of how this is meant to work. From reading the documentation, I would expect after approving through Google, I would have a user created in my identity pool, my application would display and the user would be available to my application.

**Comment by uchar** [comment]
It seems that your code is using the identity pool, not UserPool which is a different thing

**Comment by powerful23** [comment]
@jeffxor please check the doc about the `federation` in Amplify: https://aws-amplify.github.io/docs/js/authentication#aws-auth and https://aws-amplify.github.io/docs/js/authentication#oauth-and-federation-overview

**Comment by ltankey** [comment]
What version of RN are you using? Do you see errors up the stack (if you enable debugging) about an invalid_request?
