### ISSUE TITLE
No longer getting Facebook picture attribute

### ISSUE THREAD

**Issue by cliffordh** [aws-amplify/amplify-js#3519]
**Describe the bug**
A couple of weeks ago I was definitely getting Facebook picture urls when using federatedSignin. However, I am no longer getting these pictures

**To Reproduce**
Use 
      this.$Amplify.Auth.federatedSignIn({ provider: "Facebook" });
With attribute mapping in user pool for Facebook, picture -> picture.

**Expected behavior**
Receive URL of user profile picture.

**Comment by powerful23** [comment]
@cliffordh Hi, did you change anything in your app client settings like the `scopes`? Is this issue happening after you upgraded the amplify version?

**Comment by cliffordh** [comment]
I'm pretty certain this was working a couple of weeks ago. I confirmed I have attribute mapping specified, for Facebook that is "cover"->"picture". The picture does come through when logging in with Google. The scope hasn't changed, in fact when I get the FB permissions screen it says the picture will be shared... it seems more of a backend issue than front end.

**Comment by powerful23** [comment]
@cliffordh we can bring this up to the service team but in the meanwhile you can also submit this issue in the [aws forum](https://forums.aws.amazon.com/forum.jspa?forumID=173) to get direct contact with the service team.

**Comment by powerful23** [comment]
@cliffordh the attributes mapping should stays to be `picture -> picture` as the `picture` is still in the default data: https://developers.facebook.com/docs/facebook-login/permissions/

**Comment by cliffordh** [comment]
Ok, it's working now... not sure why I was mapping cover->picture. I manually added the mapping and that fixed the problem. Question, when, if ever are the picture attributes updated or is that handled on the Facebook side?

**Comment by jordanranz** [comment]
@cliffordh, this is handled on the Facebook side. I am going to close this issue for now as it seems the issue was resolved. Please open a new issue if you experience any related problems.
