### ISSUE TITLE
react native not authenticated after return from hosted ui 

### ISSUE THREAD

**Issue by uchar** [aws-amplify/amplify-js#3520]
**Which Category is your question related to?**
Authentication

**What AWS Services are you utilizing?**
Amplify,Cognito

**Provide additional details e.g. code snippets**
I'm using `Auth.federatedSignIn({provider: 'Google'});` in my `react-native `application . 
After redirecting back from google what should I do with the code that it returns ?!

```
//out put of this code is : 
// Initial url is: myapp://signin?code= .......
// not authenticated
  componentWillMount() {
    Linking.getInitialURL().then((url) => {
      if (url) {
        console.log('Initial url is: ' + url);
        if(url.includes("myapp://signin")){
          Auth.currentAuthenticatedUser()
            .then(user => {
              console.log(user);
              context.setUser(user.username);
            })
            .catch(err => console.log(err));
        }
      }
    }).catch(err => console.error('An error occurred', err));
  }
```

**Comment by powerful23** [comment]
@uchar when using the Hosted UI and get redirected back, you need to listen on the auth event `signIn`. The `signIn` event will be triggered when your app gets the tokens back from the Cognito Service. Please check the doc here: https://aws-amplify.github.io/docs/js/authentication#oauth-and-hosted-ui

If there is any error happened during that process, the `signIn_failure` should be triggered so you can listen on that as well.

You can also open the debug mode by putting `window.LOG_LEVEL='wndow'` in your app.

**Comment by uchar** [comment]
@powerful23  Thanks It seems that there was a problem in my manifest.xml file which causes amplify to fail.
the AndroidManifest.xml should be something like this :

```
<activity
      android:name=".MainActivity"
      android:label="@string/app_name"
      android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
      android:windowSoftInputMode="adjustResize"
      android:launchMode="singleTask">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="myapp"
              android:host="signin" />
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="myapp"
              android:host="signout" />
      </intent-filter>
//....
```
