### ISSUE TITLE
I get Unauthorized and the data back I'm requesting in the error data

### ISSUE THREAD

**Issue by rawadrifai** [aws-amplify/amplify-js#3521]
**Describe the bug**
I have a dynamo database and a graphql api generated using amplify.
For user sign ups, I insert a new user in the database using a lambda trigger in cognito.
When I try to retrieve the user record after I've signed in, it returns the data and gives me unauthorized at the same time. The data is returned in the error message.

**To Reproduce**
1. Insert a record in the dynamo from a lambda
2. query the record using generated graphql 

**Expected behavior**
To get the data back without any unauthorized error.

**Screenshots**
![image](https://user-images.githubusercontent.com/24530625/59999123-0e027600-9616-11e9-8983-f5b40a82874a.png)
![image](https://user-images.githubusercontent.com/24530625/59999322-8e28db80-9616-11e9-82b8-e3dce3587177.png)
![image](https://user-images.githubusercontent.com/24530625/59999415-c29c9780-9616-11e9-9e63-0f3ee169ebc9.png)

**Comment by powerful23** [comment]
@rawadrifai Hi, can you provide more details about this issue? Like the code snippets about how you are using Amplify and the error message returned by Graphql. From your description you are using `AWS Appsync` right?

**Comment by rawadrifai** [comment]
@powerful23 I fixed this by deleting my whole amplify project and redeploying everything. Luckily I'm still in dev. I think there might have some drift between what I had in my amplify couldformation templates and the actual configs in Cognito potentially. Still odd that it returned the data in the error message.

**Comment by rawadrifai** [comment]
Side note for anyone inserting data with lambda's, do *not* use dynamodb documentclient in the sdk. Use aws.DynamoDB, otherwise many things don't work downstream.
