### ISSUE TITLE
Force reset password allows current password when resetting

### ISSUE THREAD

**Issue by alastair-todd** [aws-amplify/amplify-js#3522]
** Which Category is your question related to? **

Forcing a user to reset their password

** What AWS Services are you utilizing? **

Amplify Auth

** Provide additional details e.g. code snippets **

When we force a password reset through the cognito console or auth lambda, the documentation says this calls `admin-reset-user-password` "which should use the forgot password flow"

This flow allows the user to reset their password, however the new password accepts their current password without error.

If we wanted to implement our own password expiry policy given the above, which would require not to use the same password as last time, is it going to be possible?

**Comment by powerful23** [comment]
@alastair-todd Hi unfortunately there is no way to check if the current password is the same as the previous one. The Cognito team has marked this as feature request and will be tracking in their backlog.
