### ISSUE TITLE
React Authenticator form errors not showing up

### ISSUE THREAD

**Issue by pbirsinger** [aws-amplify/amplify-js#3528]
**Describe the bug**
I am using the latest React (16.8.6) and aws-amplify-react (2.3.9). I wrap my `App` component with Authenticator in the most basic way:

```
export default withAuthenticator(App, true);
```

Everything works more or less - can create account, login, etc. However, no form errors show (on incorrect credentials, missing signup field, etc).

Here is a screenshot of me signing in with an incorrect password (registered email), having the request fail, yet the form fields not showing any error messages. Same thing happens for all other errors i can induce in the form (no error message shown in UI). 

![Screen Shot 2019-06-25 at 9 26 52 AM](https://user-images.githubusercontent.com/852331/60102533-e3a2dc80-972b-11e9-95f8-5dd5c7d37777.png)

I would expect the error messages to be displayed next to the form field. Is this something that we're responsible for? Seems like something is wrong.

**Desktop (please complete the following information):**
 - OS:mac os latest
 - Browser chrome lastest

**Comment by powerful23** [comment]
@pbirsinger the error message will be rendered at the top like this:
<img width="1280" alt="Screen Shot 2019-06-25 at 1 24 02 PM" src="https://user-images.githubusercontent.com/11042868/60130692-97b45f80-974c-11e9-9680-fb45293ea2e7.png">

**Comment by pbirsinger** [comment]
Ahhh - it was hidden beneath my header. Much appreciated!
