### ISSUE TITLE
Cognito Hosted UI and IE11

### ISSUE THREAD

**Issue by dementiev** [aws-amplify/amplify-js#3532]
**Describe the bug**
Cognito hosted UI sing in/sign up form throws error in IE11. 
Error decares 'Promise undefined' and happens in GoogleOauth.js var waitForInit = new Promise(function (res, rej) { (line 53). 
Adding of babel-polyfill in my React project didn't help. Ob

**To Reproduce**
Use cognito-hosted ui in IE-11.
    "aws-amplify": "^1.1.29",
    "aws-amplify-react": "^2.3.9",

**Desktop (please complete the following information):**
 - Windows 10 Pro
 - Browser IE 11

Possible fix - import polyfill library right into https://github.com/aws-amplify/amplify-js/blob/ebb9c9e965d20c03b4ca10ee5476eb9a822cc5e1/packages/core/src/OAuthHelper/GoogleOAuth.ts  and do the same for FacebookOauth.

**Comment by powerful23** [comment]
@dementiev Hi, can you try installing this package: https://www.npmjs.com/package/promise-polyfill and add `import 'promise-polyfill/src/polyfill';` in the beginning of your index file.

**Comment by dementiev** [comment]
@powerful23 thanks, it works! After I applied proposed polyfill I had an error regarding assign method, but it is also fixable.
