### ISSUE TITLE
AWS_IAM Authentication works with Post and not Get

### ISSUE THREAD

**Issue by Artin-ST** [aws-amplify/amplify-js#3534]
This is regarding use AWS Amplify Auth.

We've build a serverless application that uses an angular front end with API Gateway and Lambda. We're using Cognito User Pool and Identity Pool with 'choose role from token'  

The API Gateway is using AWS_IAM authorization and has CORS enabled. 
Option headers :
- AllowMethods: POST,GET,PUT,DELETE,OPTIONS
- AllowHeaders: Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token
- AllowOrigin: *

The lambda functions do return 
- Access-Control-Allow-Origin: *
- Access-Control-Allow-Credentials: true

The angular app is configured as follows:

```
  Auth: {
    identityPoolId: 'ca-central-1:xxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    region: 'ca-central-1',
    userPoolId: 'ca-central-xxxxxxxxxx',
    userPoolWebClientId: 'xxxxxxxxxxxxxxxxxxxxx',
  },
  API: {
    endpoints: [
      {
        name: 'ApiGateway',
        endpoint: 'https://xxxxxxxxxx.execute-api.ca-central-1.amazonaws.com/Dev/',
        region: 'ca-central-1'
      }
    ]
  }
```

When we call a resource with GET there is a 403 error however when I call a POST on the same resource it works without issue. The GET does show a CORS error after however I think thats because it's not getting to the Lambda so the header isn't being returned.

```
  init(body?) {
    const output = {
      headers: { },
      queryStringParameters: {},
      body: {}
    };

    if (body !== undefined) {
      output.body = body;
    }
    return output;
  }

  createResource(body) {
    return API.post(this.apiName, `resource`, this.init(body));
  }

  readResource() {
    return API.get(this.apiName, `resource`, this.init());
  }
```

Everything works fine when I use the same Identity Pool Credentials in Postman. Not sure where else to look to resolve this.

**Comment by gerrytsui** [comment]
In our code, when we do a API.get, we set body: null ( instead of an empty object). That's all I can think of that is different from what you are doing.

**Comment by Artin-ST** [comment]
> In our code, when we do a API.get, we set body: null ( instead of an empty object). That's all I can think of that is different from what you are doing.

That solved my problem, I would never have caught that, thank you very much.
