### ISSUE TITLE
Amplify Console and aws-exports

### ISSUE THREAD

**Issue by emaddoma** [aws-amplify/amplify-js#3536]
** Which Category is your question related to? **
All

** What AWS Services are you utilizing? **
Amplify, Cognito, Personalize

** Provide additional details e.g. code snippets **
Our project is a GatsbyJS site and we started by using the AWS Amplify Console for CI.  As we continued to build out the project we realized the only way we were going to easily integrate Analytics, Auth and Personalize was to make use of the Amplify CLI.  Per instructions for Amplify CLI, we are git ignoring the aws-exports file, so when the Console app tries to build it fails because the file hasn't been generated by the CLI.

Is there a way to continue to use the AWS Amplify Console with Git integration as well as the CLI for management of the resources needed?

**Comment by emaddoma** [comment]
I figured it out.  I had to modify the console's Build setting's amplify.yml to include backend...

```
backend:
  phases:
    build:
      commands:
        - amplifyPush --simple
```

**Comment by masapasa** [comment]
Module not found: Can't resolve '../aws-exports' in '/codebuild/output/src240068493/src/nnews/next/pages'
build:
      commands:
        - echo Amplify build...
        - amplifyPush --simple
While deploying through the console with an ECR image
