### ISSUE TITLE
Support for AppSync multi auth (authMode)

### ISSUE THREAD

**Issue by pippo111** [aws-amplify/amplify-js#3543]
** Which Category is your question related to? **
GraphQL API

** What AWS Services are you utilizing? **
AppSync, Cognito, IAM

** Provide additional details e.g. code snippets **
Regarding to the documentation https://aws-amplify.github.io/docs/js/api#aws-appsync-multi-auth amplify supports multiauth mode. Unfortunately, when setting additional authMode in Typescript there is an error with typings:

```
Argument of type '{ query: string; variables: {}; authMode: string; }' is not assignable to parameter of type 'GraphQLOptions'.
  Object literal may only specify known properties, and 'authMode' does not exist in type 'GraphQLOptions'.  TS2345
```
when using it like this:
```
API.graphql({
     query: queries.createTodo,
     variables: {input: todoDetails},
     authMode: 'AMAZON_COGNITO_USER_POOLS'
})
```
and even when I change typings to accept `authMode` there is no response from the server - I'm still unauthorize to get the results.

All I'm trying to accomplish is to authenticate through Cognito and this way get Cognito user details in my resolver. Is it even possible ?

**Comment by powerful23** [comment]
@pippo111 Hi, can you provide the request headers when calling `API.graphql()`? If the `authMode` is `AMAZON_COGNITO_USER_POOLS`, then the `access token` from the Cognito service should be added into the headers.

**Comment by ajhool** [comment]
@pippo111 are you still having this issue?

**Comment by dabit3** [comment]
I'm having the same issue. I've tested this in the AppSync console and everything works fine.

Here is my API call:
```javascript
const data = await API.graphql({
  query: listPosts,
  authMode: 'AWS_IAM'
})
```

Here is what my headers look like:

```
Authorization: AWS4-HMAC-SHA256 Credential=undefined/20191017/eu-central-1/appsync/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-user-agent, Signature=eb81fd2ffe9334522fd041cc5b89f2dc0c5741391d643626b8d315428ecf5620
```

I see that there is an `undefined` parameter in my headers. Could that be causing the issue? If so, any ideas around what I could do?

**Comment by dabit3** [comment]
Ok, this issue was because I did not have Cognito properly configured to use `unauthenticated` access. For me the solution was this:

```
amplify update auth

# walk through the steps for a custom flow, allowing unauthenticated access

amplify push
``

**Comment by dabit3** [comment]
Follow up: comment from @undefobj cc @kaustavghosh06:

This should actually be configured automatically or the schema compilation should throw a warning - e.g. if public using provider with IAM, and unauth wasn’t enabled in auth category we should enter the auth flow to either enable it or automatically do it under the covers
