### ISSUE TITLE
Allow for Admin-only confirmation in the Cognito Hosted UI

### ISSUE THREAD

**Issue by uforiginal** [aws-amplify/amplify-js#3544]
**Is your feature request related to a problem? Please describe.**
I don't want users to be able to sign up for access to my website without admin intervention. Right now, Cognito is set up so users can confirm their accounts themselves using their phones/email. But if we turn this verification off so that users can only be confirmed by admins, they are redirected to a confusing error page after they hit sign up. This error page is misleading because Cognito is doing exactly what I want it to do: registering the user profiles in UNCONFIRMED status. This creates a difficult user experience.  
![Screen Shot 2019-06-27 at 2 19 13 PM](https://user-images.githubusercontent.com/29385897/60294246-9323ae80-98e6-11e9-84be-d435180d69e2.png)

**Describe the solution you'd like**
I would like either an admin-only verification option in "MFA and verifications" menu, OR for the pre-sign-up/all the other lambda triggers to accept some kind of redirect value so that we can redirect users away from that confusing error screen and onto custom pages that explain they need to wait for admin approval, OR for that error page to be replaced with a message stating to await admin approval, since thats all they need to do, there is nothing wrong with Cognito. 

**Describe alternatives you've considered**
I've tried using the Pre-sign-up lambda trigger to trigger a redirect to a different page after the user hits sign up, but the trigger does not understand the request and I'm given a 'unrecognizable lambda output' error. I've also tried adjusting the verification email to simply say 'please wait for admin approval', and not contain a verification code, but the message will not accept my changes unless I include a verification code.

**Additional context**
I've already put so much effort into setting up the Cognito Hosted UI for my site, its extremely frustrating that I'm going to have to scrap a lot of it in favor of hard coding several sign in/out pages with Amplify, simply to avoid this one error. This seems like a common sense feature to me and I'm confused as to why it's not/never has been a part of the Cognito Hosted UI.

**Comment by powerful23** [comment]
@uforiginal Hi we will bring this issue to Cognito team. Alternatively You can also post it in the [aws forum](https://forums.aws.amazon.com/forum.jspa?forumID=173) where you can talk to the service team directly.

**Comment by cburkins** [comment]
This is a shame, as I have a similar/same request.  I'm essentially creating a family-only website, and as such, want to have admin approval required on any new accounts.
