### ISSUE TITLE
Vue: Writing a wrapper around Amplify Storage?

### ISSUE THREAD

**Issue by cliffordh** [aws-amplify/amplify-js#3545]
I want to centralize the logic for S3 interactions in my own .js utility file. I am able to create functions and export the functions, but, I can't access this.$Amplify.

Simply my utility class is:

```
function getS3Documents() { 
  this.$Amplify.Storage.list()
  ... 
}
export {getS3Documents};
```
I'm sure this is just a problem with my lack of how to build a reusable class. I could pass the instance of $Amplify into these functions but I'd rather that the reusable functions just had direct access to Amplify.

Ideas?

**Comment by iparrabb** [comment]
Hi @cliffordh, just do:

```js
import { Storage } from "aws-amplify";

function getS3Documents() { 
  Storage.list()
}
export {getS3Documents};
```
