### ISSUE TITLE
Substitute hosted UI with custom amplify project

### ISSUE THREAD

**Issue by rreiser-auti** [aws-amplify/amplify-js#3546]
** Which Category is your question related to? **
Oauth Provider
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
First of all, amplify is an awesome platform, give us an outstanding agility in our jobs. 
I just want some help, because in my researches i didnt realize how it can be done
I need to handle requests like this :
```
https://<your_domain>/login?response_type=code&client_id=<your_app_client_id>&redirect_uri=<your_callback_url>

```
in my amplify project. is this possible? am i missing something? I really wanted to use the hosted ui, it works perfectly, except the fact that i cant translate it. Thanks in advance

**Comment by powerful23** [comment]
@rreiser-auti Hi, when using Amplify we will handle the oauth flow automatically. You just need to call `Auth.federatedSignIn` to initiate the flow and after getting redirected back, listen on the `Hub` events which will tell you if you are logged in or not. For details please check the doc: https://aws-amplify.github.io/docs/js/authentication
