### ISSUE TITLE
Ability to add Tagging support on files get

### ISSUE THREAD

**Issue by bneigher** [aws-amplify/amplify-js#3547]
Similar to #2594

According to AWS documentation there is a possibility to get object tagging support with method getObjectTagging.
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getObjectTagging-property

But aws-amplify doesn't support this option, or at least the options in the Storage.get don't leverage it.

Thoughts?  It could even be acceptable for a separate method from get `getTagging` if that works.
https://github.com/aws-amplify/amplify-js/blob/master/packages/storage/src/Providers/AWSS3Provider.ts#L115-L142
Essentially if `tagging = true` was supplied, instead of `getObject`, it would be `getObjectTagging`

Seems like the only tagging options are on PUT.

**Comment by sammartinez** [comment]
This work has been implemented. Resolving this request since work is complete.
