### ISSUE TITLE
Integrating Social Login (Google, Facebook) with Cognito in an Expo App (CUSTOM UI)

### ISSUE THREAD

**Issue by jmzwar** [aws-amplify/amplify-js#3550]
** Which Category is your question related to? **
AWS Amplify, Auth, Social sign in

** What AWS Services are you utilizing? **
AWS Federated Login

** Provide additional details e.g. code snippets **
I'm running into some problems trying to get social sign in working in an expo app.

I'm using the Auth.federatedSignIn method calling the Facebook and Google providers.

The current work flow is:

User clicks login through facebook/google - WORKING
Browser opens with FB/Google oAuth sign in page - WORKING
User logs in with credentials - WORKING
Browser window redirect back to Expo app - WORKING

Here is where the issue arises - I have configured the Hub to listen to auth events and it is receiving data. I'm receiving a signIn_failure and a cognitoHostedUI_failure. 

I should add that I am not using the Hosted UI - unfortunately this is not an option for us.

**Comment by powerful23** [comment]
@jmzwar Hi what's the error you are getting in that event payload?

**Comment by jmzwar** [comment]
@powerful23 Thanks for the quick reply but I found a solution integrating social sign in with user pools.

**Comment by iamdavidmartin** [comment]
@jmzwar can you share which solution you're using? looking for something better than the Hosted UI. Thanks!

**Comment by dineshmatta** [comment]
@jmzwar Can you share your solution, because I am also getting the same error with your setup

**Comment by jmzwar** [comment]
@iamdavidmartin @dineshmatta Are you using User pools or Federation? I had some initial confusion regarding the difference between the two.

**Comment by dineshmatta** [comment]
@jmzwar I am using Federation login using social providers - https://aws-amplify.github.io/docs/js/authentication#oauth-and-federation-overview

**Comment by iamdavidmartin** [comment]
@jmzwar both. for each new user who authenticates with federated social providers, a new user gets put into a user pool.

**Comment by jordanranz** [comment]
@jmzwar, it looks like the original issue posted is solved correct?

@dineshmatta @iamdavidmartin, did you guys make any progress or are you guys still stuck?

**Comment by iamdavidmartin** [comment]
i'm not stuck. i'm using the hosted UI with Expo and that's a good option because the user doesn't leave the app - the auth browser window overlays the app and the user comes right back. 

but, if i could make a wish, i would get rid of the hosted UI and have a tighter integration with the social login buttons. amplify has the nice withAuthenticator react-native component that allows a user to auth with amazon. wouldn't it be nice if it were so nicely packaged with facebook/google/(and we hope soon to be apple)? that would make for a better user experience.

**Comment by dineshmatta** [comment]
I'm too using hosted UI with Expo, so at this moment I am not blocked, but I agree with @iamdavidmartin that there should be tighter integration with social login buttons

**Comment by sammartinez** [comment]
Flipping this to a Feature Requests based on the above feedback on this.
