### ISSUE TITLE
User login give 'rate exceeded' error

### ISSUE THREAD

**Issue by simonrp84** [aws-amplify/amplify-js#3554]
Hello,
I am trying to setup a login via aws-amplify/auth in a react/JS app. I have this line in my code, which is activated on a 'login' button click.
`await Auth.signIn(this.state.email, this.state.password);`
Yesterday, this line worked fine. But when I got to the office this morning (having not touched the code or tried to log in for over 10 hours) I get this error when hitting the login button:
`{code: "TooManyRequestsException", name: "TooManyRequestsException", message: "Rate exceeded"}`

I am the only user on the userpool behind this request (in fact, the only user of the entire AWS account) so I can't figure out why the rate is being exceeded. Trying to log in once every 10 hours must be OK, right?

Does anyone know what could be happening here? I probably forgot to click the logout button yesterday, could that cause the problem? If so, how to get around it in the code (I presume lots of users will forget to logout)?

**Comment by powerful23** [comment]
@simonrp84 Hi we will bring this issue to Cognito team. Alternatively You can also post it in the [aws forum](https://forums.aws.amazon.com/forum.jspa?forumID=173) where you can talk to the service team directly.

**Comment by simonrp84** [comment]
Hi @powerful23, thanks for the reply and sorry if I put this issue in the wrong place. I had already posted on the forum :-)
But I see that someone else on the forum posted a similar question...so I suspect that this was a temporary problem at AWS/Cognito rather than a library / coding issue.
My code is working again now so I will close this issue.

**Comment by luliandro** [comment]
Hi @simonrp84 we've also had the same issue out of the blue 4 days ago... have you confirmed this was a temporary problem at AWS Cognito? thanks

**Comment by simonrp84** [comment]
@luliandro No, I have had no response from AWS at all. Neither, as far as I can see, has anyone else. Pretty poor customer service.
But it definitely isn't a problem with amplify-js, hence why I closed this issue.
