### ISSUE TITLE
CognitoIdentity not respecting expires_at from Federated Identity

### ISSUE THREAD

**Issue by xcskier56** [aws-amplify/amplify-js#3557]
**Describe the bug**
When using `Auth.federatedSignIn` the credentials returned do not respect the `expires_at` passed into the method. 

**To Reproduce**
Use the method, `Auth.federatedSignIn` to sign in with a custom identity and notice that the cognito credentials do not respect the `expires_at` of the `id_token`

**Expected behavior**
The Cognito crednetials are only valid for as long as the `id_token` is valid for. 

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome, Safari

**Smartphone (please complete the following information):**
 - Device: iOS
 - OS: iOS 12.3.2
 - Browser Cordova

**Additional context**
This seems to happen on all devices that I've tested

**Sample code**

    // We want the token to expire in 10 minutes
    var tokenData = {
      expires_in: 60,
      id_token: "..."
    }

    var user = {
      patient_id: 'id',
      name: 'Name'
    }

    signInData = {
      expires_at: (tokenData.expires_in * 1000 + (new Date()).getTime()),
      token: tokenData.id_token
    }

    Auth.federatedSignIn(
      ENV.idpProviderName,
      {
        token: result.fhirAccessToken,
        expires_at
      },
      user
    ).then((credentials) => {
      actualExpiration = credentials.expireTime.getTime()
      console.log(actualExpiration === signInData.expires_at) // FALSE
      console.log(actualExpiration - signInData.expires_at) // 3315221 or ~ 50min
    });

**Comment by powerful23** [comment]
@xcskier56 Hi, the `expires_at` indicates when the `id_token` is expired, which has nothing to do with the `aws credentials`. The `aws credentials` will live for 60 minutes and after that you need a valid `idToken` to get a new one.

**Comment by xcskier56** [comment]
@powerful23, thank you for the clarifying response. We are using amplify/Cognito for apps in regulated environments and may need expiration times less than 1 hour. Is there a way to configure amplify/cognito to respect the lower expiration time? We are only using custom OpenID connect providers & identity pools. Thanks!

**Comment by powerful23** [comment]
@xcskier56 unfortunately there is no way for now to configure the expiration time of the `aws credentials` or to revoke the issued credentials.

**Comment by xcskier56** [comment]
Huh, that seems like a oversight. @powerful23, thank you for the help

**Comment by safinn** [comment]
Is it still the case identity pools cannot configure access duration and is fixed to 1 hour?
