### ISSUE TITLE
Get all Items using the Query API through AWS Amplify ('LastEvaluatedKey')

### ISSUE THREAD

**Issue by stayingcool** [aws-amplify/amplify-js#3566]
** Which Category is your question related to? **
AWS Amplify GET API
** What AWS Services are you utilizing? **
Amplify, NodeJS
** Provide additional details e.g. code snippets **

**How can we get all the items by invoking dynamodb.query?**

The documentation states that we need to look for the presence of '**LastEvaluatedKey**'. Just wondering **how we could aggregate all the Items in an efficient way?**

```
app.get(path, function (req, res) {
    var allItems = [];
    var params = {
        TableName: tableName,
        "IndexName": "status-index",
        "KeyConditionExpression": "#attrib_name = :attrib_value",
        "ExpressionAttributeNames": { "#attrib_name": "status" },
        "ExpressionAttributeValues": { ":attrib_value": req.query.status },
        "ScanIndexForward": false
    }

    dynamodb.query(params, onQuery);

    function onQuery(err, data) {
        if (err) {
            res.json({ error: 'Could not load items: ' + err });
        } else {
            // Should I be aggregating all the items like this?
            allItems = allItems.concat(data.Items);

            // Then should I set it to res like this to return all the items?
            res.json(allItems);

            if (typeof data.LastEvaluatedKey != 'undefined') {
                params.ExclusiveStartKey = data.LastEvaluatedKey;
                dynamodb.query(params, onQuery);
            }
        }
    }
});
```

Please look at **comments** within the code. That is where I think we **need to have the appropriate code to aggregate all the items and return back the response.**

I have written NodeJS code to insert items good enough to see that LastEvaluatedKey is returned in the response. However, I have not found a way to debug this over the DynamodDB on AWS online yet as I'm fairly new to DynamoDB and AWS Amplify. Let me as well know if there is an easier way to debug this in an AWS amplify backed up GET API. Not sure how to point the amplify app to local DynamoDB to test locally with it. How do you folks debug in general? 

Please ignore the above paragraph if it is digressing from the main issue. Just need some immediate help with the query part though!

**Comment by stayingcool** [comment]
Can someone who has already implemented this help?

All that I'm wanting to know is how to aggregate all the items from repeated query operation (due to the presence of LastEvaluatedKey):

> 1.

```
            // Should I be aggregating all the items like this?
            allItems = allItems.concat(data.Items);
            res.json(allItems);
```

**Or**

> 2. 

```
        // Will this be good enough? will the below code result in having all the records?
            res.json(data.Items);
```

**Comment by stayingcool** [comment]
Please don't close. I'm expecting feedback from someone who knows about it.

**Comment by sammartinez** [comment]
@stayingcool Sorry for the late response, for documentation you are referring to, are you talking about our [API REST](https://aws-amplify.github.io/docs/js/api#using-rest) documentation?

I do want to state as well, that NodeJS is not officially supported for Amplify but we do want to help out where we can. Im also curious if using [AWS AppSync](https://aws-amplify.github.io/docs/js/api#using-aws-appsync) would help what you're looking to solve since there are [GraphQL Transformers](https://aws-amplify.github.io/docs/js/api#using-graphql-transformers) that can be configured in order to do CRUD operations for dynamoDB.

To answer your above question, I don't see an issue with using option 1 since this will give you everything you need from those items and converting to JSON so it can be read as that.

Hope this helps!

**Comment by stayingcool** [comment]
@sammartinez Yes I'm using REST APIs created through Amplify. GraphQL wasn't there when I started with Amplify.

Thank you for your suggestions on aggregating the dynamodb items, I'll go with option 1.

I'm surprised when you say NodeJS is not officially supported for Amplify. The Amplify CLI for RESTful APIs creates the NodeJS code, isn't it? Where can I find the supportability matrix for Amplify JS?
