### ISSUE TITLE
Query strings are not sorted correctly when signing requests

### ISSUE THREAD

**Issue by bonnici** [aws-amplify/amplify-js#3582]
**Describe the bug**
In the canonical request used when a request is signed, the query strings are sorted using a string comparison of the key+value instead of the key. This means that for some requests the order is incorrect because the expected ordering is by key only. 

For example, when searching CloudSearch, you pass the `q=x` parameter as well as the `q.parser=x` parameter, and if this is sorted by key+value, `q.parser=x` is sorted before `q=x` because of the comparison between `.` and `=`, but the correct order is with `q=x` first. If a signature signed with the wrong order is passed to AWS, I get a 403 error with the message "The request signature we calculated does not match the signature you provided.".

**To Reproduce**
1. Using @aws-amplify/api, make a signed request with the query string parameters 'q=x' and 'q.parser=y'
3. "The request signature we calculated does not match the signature you provided" error is returned.

**Expected behavior**
Correct signature should be generated and request should not be rejected by AWS.

**@aws-amplify/core versions tested**
 - 1.0.23
 - 1.0.28

**Sample code**
```
import API from '@aws-amplify/api';
...
await API.get('name', 'cloudsearch path', { queryStringParameters: { q: 'matchall', 'q.parser': 'structured' } });
```

**Suggested fix**
See PR https://github.com/aws-amplify/amplify-js/pull/3583

**Comment by bonnici** [comment]
Any updates on this? Until this is fixed we will need to use a branch of amplify-js, otherwise we can't make requests to CloudSearch.

**Comment by manueliglesias** [comment]
Thanks @bonnici 
We'll be reviewing this today

**Comment by sammartinez** [comment]
Closing this issue as the fix is now done and merged
