### ISSUE TITLE
React Authenticator component authData improperly updated on Auth.FederatedSignIn

### ISSUE THREAD

**Issue by jukkahuuskonen** [aws-amplify/amplify-js#3586]
**Describe the bug**
This is related to issues #3570, #3195

When signing in with Auth.federatedSignIn the userSession object received (authData prop in Authenticator) has initially 
```authData.signInUserSession === null```
This get's updated in a few tens of milliseconds into the correct signInUserSession, but React state management doesn't see it happening. In componentDidUpdate-function comparing with prevProps doesn't tell anything has changed. This mean's that authData in Authenticator state has probably been directly changed without using setState()-function.

This causes problems when using authData.signInUserSession.

**To Reproduce**
1. Use create-react-app to create your app
2. Configure aws as needed
3. Configure hostedUiprovider as needed
4. replace and add files from 'Sample code'-section
5. Click 'Open facebook'-button

**Expected behavior**
When the Authenticator sets the authData after returning back to app, it should already have the signInUserSession-property with correct value instead of 'null'.

**Desktop (please complete the following information):**
 - OS: windows (10)
 - Browser Chrome
 - Version 75.0.3770.100 (Official Build) (64-bit)
 - Browser Firefox
 - Version 75.0.3770.100 (Official Build) (64-bit)

**Additional context**
This could be related:
Often, if the browser is closed and re-opened, the Authenticator fails to check user authentication. AuthState remains in initial 'loading' state. Page needs to be reloaded to start working again.

More specifically, if the user is logged in in a browser, and a new browser/browser window is opened, then the Authenticator may be stuck (=not every time) on 'loading'-state failing to authenticate the user.

**Sample code**
App.js
```
import React, {Component} from 'react';
import { Hub } from 'aws-amplify';
import { Authenticator } from 'aws-amplify-react/dist/Auth';
import awsconfig from './aws-exports';
import SignInButtons from './SignInButtons';
import SignOutButton from './SignOutButton';

class App extends Component {
  render() {
    return (
			<Authenticator
				amplifyConfig={awsconfig}
				hideDefault={true}
			>
				<SignInButtons/>
				<SignOutButton/>
			</Authenticator>
      
    );
  }
}

export default App
```

SignInButtons.js
```
import React, { Component } from 'react';
import { Auth } from 'aws-amplify';

class SignInButtons extends Component {

	render() {
		const { authState } = this.props;

		if (['signIn', 'signedOut', 'signedUp'].indexOf(authState) < 0) return null;
		return (
			<div className="signInButtons">
				<button onClick={() => Auth.federatedSignIn({ provider: 'Facebook' })}>Open Facebook</button>
				<button onClick={() => Auth.federatedSignIn({ provider: 'HOSTEDLOGINPROVIDER' })}>Open HOSTEDLOGINPROVIDER</button>
				<button onClick={() => Auth.federatedSignIn()}>Open Hosted UI</button>
			</div>
		);
	}
}

export default SignInButtons
```

SignOutButton.js
```
import React, { Component } from 'react';
import { Auth } from 'aws-amplify';

class SignOutButton extends Component {

	state = {
		counter: 0,
	};

	componentDidUpdate(prevProps, prevState){
		const { counter } = this.state;
		const { authState, authData } = this.props;
		const { authState: authStatePrev, authData:authDataPrev } = prevProps;
		console.log('CDU: COUNTER, authData', counter, authData, authData !== authDataPrev);
		if (authData) console.log('CDU authData.signInUserSession', authData.signInUserSession);
		if (authDataPrev) console.log('CDU authDataPrev.signInUserSession', authDataPrev.signInUserSession);
		if (authData && authState !== authStatePrev) this.addCounter();
	}
	
	addCounter = () => {
		const { counter } = this.state;
		this.setState({counter: counter + 1}, () => {
			setTimeout(() => {
				if(counter < 10) this.addCounter();
			}, 50);
		});
	}

	render() {
		const { authState } = this.props;
		if (authState !== 'signedIn') {
			console.log('[SIGNOUTBUTTONS, authState]:', authState);
			return null;
		}
		return (
			<div className="signOutButton">
				<button onClick={() => Auth.signOut()}>Sign Out</button>
			</div>
		);
	}
}

export default SignOutButton
```

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

---------------
edited additional context

**Comment by jukkahuuskonen** [comment]
Hi,
Anything happening to this? This bug is still in the code.

**Comment by ashika01** [comment]
This PR #4258 would solve the bug thats happening here. Have verified this locally.

**Comment by ashika01** [comment]
Closing the issue since the PR has been merged. Please verify and close the issue.

**Comment by jukkahuuskonen** [comment]
Good to hear it should be fixed, unfortunately I'm unable to verify it myself for now. I'm closing the issue anyways. When I'm able to verify it, I'll reopen the issue, if necessary.
