### ISSUE TITLE
Manual setup with Cognito user pool, which token should be used?

### ISSUE THREAD

**Issue by jacktuck** [aws-amplify/amplify-js#3587]
I have APIGW setup with a Cognito user pool Authorizer, which is created by serverless.

I configure Amplify manually as described below with the Authorizer header set to the `accessToken`. But when using the `accessToken` JWT I get 401's back (not sure how to get more detailed logs) and if i switch to using `idToken` I no longer get 401s, it works!. 

In what circumstances should `accessToken` be used rather than `idToken`, does it relate to the client app settings? Is using `idToken` correct?

```
Amplify.configure({
  API: {
    endpoints: [
      {
        name: "sampleCloudApi",
        endpoint: "https://xyz.execute-api.us-east-1.amazonaws.com/Development",
        custom_header: async () => { 
          return { Authorization : 'token' } 
          // Alternatively, with Cognito User Pools use this:
          // return { Authorization: `Bearer ${(await Auth.currentSession()).accessToken.jwtToken}` }
        }
      }
    ]
  }
});
```

**Comment by tbehunin** [comment]
@jacktuck I have the exact same scenario. Sending `idToken` returns 200's, whereas sending `accessToken` returns 401's. The docs seem to indicate we should be sending the `accessToken`. Maybe we should be sending more in the header when using `accessToken`..? 🤷‍♂
