### ISSUE TITLE
Auth.signOut does not sign out the user in React Native

### ISSUE THREAD

**Issue by Benassou** [aws-amplify/amplify-js#3590]
**Describe the bug**
Using `Auth.signOut();` per the documentation does not sign the user out in a React Native application i.e. `Auth.currentAuthenticatedUser();` still returns the same user as before while the then callback receives `undefined` as parameter. Instead `Auth.currentAuthenticatedUser().then(user => user.signOut());` does work as expected.

**To Reproduce**
Create a fresh install using the official Amplify documentation for React Native (https://aws-amplify.github.io/docs/js/start?platform=react-native). Then 
1) Sign up a new user.
2) Verify this user.
3) Sign this user in.
4) Run `Auth.currentAuthenticatedUser();`, this will return the user.
5) Run `Auth.signOut();`, this will return undefined.
6) Run `Auth.currentAuthenticatedUser();`, this will **still** return the user.

**Expected behavior**
I would expect `Auth.signOut();` to automatically sign out the currently authenticated user.

**Smartphone (please complete the following information):**
 - Device: Samsung s4
 - OS: Android 7

**Comment by LucianGalea** [comment]
Any updates on this? This issue prevents me from using the Amplify Library in production.

**Comment by Benassou** [comment]
I just used `Auth.currentAuthenticatedUser()` to get the current user. You can then sign out the user using the returned user object.

**Comment by LucianGalea** [comment]
> I don't think the problem is solved yet, at least not for me. I just used `Auth.currentAuthenticatedUser()` to get the current user. You can then sign out the user using the returned user object.

Thank you, this is a good workaround.

**Comment by sammartinez** [comment]
@Benassou Do you have a code snippet you could share with us? We wanted to know if you are using the Authenticator component from `aws-amplify-react-native` or your own hand rolled component. But also wanted to double check if the workaround you found resolved this issue. Please let us know
