### ISSUE TITLE
Error message typo

### ISSUE THREAD

**Issue by finnbear** [aws-amplify/amplify-js#3595]
**Describe the bug**
Clicking the register link in a verification email for a second time leads to this error page, which contains a typo
```
User cannot be confirm. Current status is CONFIRMED
```

**To Reproduce**
1. Send a verification email
2. Click it once and verify the new account
3. Click it again

**Expected behavior**
```
User cannot be confirmed. Current status is CONFIRMED
```

**Comment by jordanranz** [comment]
Thanks for reporting this typo. We will bring this up with the Cognito team.

**Comment by manueliglesias** [comment]
I got confirmation from the Cognito Team that this has been fixed
