### ISSUE TITLE
[Error] AWSPinpointProvider - record event failed. , [CredentialsError: Missing credentials in config]

### ISSUE THREAD

**Issue by QinkangLu** [aws-amplify/amplify-js#3600]
** Which Category is your question related to? **
Missing Credential

** What AWS Services are you utilizing? **
I am using AWS Amplify CLI and I added analytics, api, function, and storage

** Provide additional details e.g. code snippets **
<img width="324" alt="Screen Shot 2019-07-05 at 2 00 22 PM" src="https://user-images.githubusercontent.com/32942797/60748570-1e82ec80-9f44-11e9-91c6-3778853692ea.png">

I was using AWS API, DynamoDB, and Lambda and it was working without this error yesterday but it suddenly just crashed like this when I opened the app. I have no idea how to fix this. (I have read other posts related but I still did not find the solution for this one)

**Comment by bneigher** [comment]
@QinkangLu Yea I have this issue too.  In production it doesn't cause any issues (that I'm aware of) as amplify should re-authenticate (at least in my configuration), but it's quite annoying in my Sentry error logs.  Wondering if it is just that the error isn't being handled correctly.

Does this only happen after a cognito auth session has expired?

**Comment by QinkangLu** [comment]
> @QinkangLu Yea I have this issue too. In production it doesn't cause any issues (that I'm aware of) as amplify should re-authenticate (at least in my configuration), but it's quite annoying in my Sentry error logs. Wondering if it is just that the error isn't being handled correctly.
> 
> Maybe its a race condition when booting Amplify?

Yes, it is just this error that isn't being handled and I highly doubt there is a race condition since it was working perfectly fine yesterday and I did not even make any changes to my code

**Comment by EugeneDraitsev** [comment]
I have same issue. Looks like pinPoint doesn't work at all. Every attempt to call `Analytics.record()` fails with:

```
ExceptionsManager.js:82 [ERROR] 31:56.362 AWSPinpointProvider - record event failed.  CredentialsError: Missing credentials in config
    at credError (blob:http://localhost:8081/bbf99c2d-4de6-458a-a4c5-cefe82c2c494:133025:46)
    at getStaticCredentials (blob:http://localhost:8081/bbf99c2d-4de6-458a-a4c5-cefe82c2c494:133047:21)
    at Config.getCredentials (blob:http://localhost:8081/bbf99c2d-4de6-458a-a4c5-cefe82c2c494:133057:15)
    at Request.VALIDATE_CREDENTIALS (blob:http://localhost:8081/bbf99c2d-4de6-458a-a4c5-cefe82c2c494:133446:32)
    at Request.callListeners (blob:http://localhost:8081/bbf99c2d-4de6-458a-a4c5-cefe82c2c494:132229:24)
    at Request.emit (blob:http://localhost:8081/bbf99c2d-4de6-458a-a4c5-cefe82c2c494:132206:16)
    at Request.emit (blob:http://localhost:8081/bbf99c2d-4de6-458a-a4c5-cefe82c2c494:135100:22)
    at Request.transition (blob:http://localhost:8081/bbf99c2d-4de6-458a-a4c5-cefe82c2c494:134841:18)
    at AcceptorStateMachine.runTo (blob:http://localhost:8081/bbf99c2d-4de6-458a-a4c5-cefe82c2c494:135201:18)
    at Request.runTo (blob:http://localhost:8081/bbf99c2d-4de6-458a-a4c5-cefe82c2c494:134913:23)
```
Obviously I have setuped credentials and same code worked couple of days ago. 
I hope someone will respond on this issue

**Comment by QinkangLu** [comment]
Now I am very sure it is due AWS Analytics since after I remove analytics from Amplify CLI and everything else starts working fine. But since I wish to add analytics eventually I hope someone from the amplify dev team can take a look.

**Comment by bneigher** [comment]
@QinkangLu I mean i believe it's something to do with handling the condition in which your token has expired and upon fetching a new one this error occurs - specifically on application boot.  Race condition or not - it's quite annoying but it is silent (at least with my implementation)

@EugeneDraitsev if it happens for all events - make sure you've got the correct payload in `Analytics.configure({ ... })`, and / or `Auth.updateEndpoint({ ... })` as these two play together

**Comment by EugeneDraitsev** [comment]
@bneigher I just figured out that I used wrong region in `Auth` section. Moreover somehow it worked couple of days ago. Simple changing of region to correct one solved my problem
