### ISSUE TITLE
Amplify.configure(awsconfig) public?

### ISSUE THREAD

**Issue by yeukhon** [aws-amplify/amplify-js#3602]
** Which Category is your question related to? **
Auth, config, question

** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
According to the doc example:

```
Amplify.configure(awsconfig);
```

My use case is to leverage the Amplify Auth component and build a ReactJS web app backed by Flask (unfortunately API Gateway is not suitable for our need at the moment).

So I was looking at the doc and was wondering whether these configurations are safe to be public (well I assume yes since they are just IDs).

**Comment by manueliglesias** [comment]
Hi @yeukhon 

Yes, it is safe, see https://github.com/aws-amplify/amplify-js/issues/3108#issuecomment-497516442 for more context and detailed explanation
