### ISSUE TITLE
How to make sure the user token is invalid when user logout from any of the sites that are configured on same cognito user pool?

### ISSUE THREAD

**Issue by jani937** [aws-amplify/amplify-js#3603]
**Describe the bug**
I have a user pool group which is used to access two seperate environments such as dev/stage/uat on the same user pool group. Now, when the same user is logged in dev and stage same time and logout from stage, then go and check the dev site which is still considering the user token is valid. Now, make any api call from the site which throws 401 error from aws api gateway saying that token / refresh token is not valid.

**To Reproduce**
1. Go to 'dev site-> Login', go to 'stage site ->login'
2. go to 'stage site -> logout'
3. go to dev site ' check if user is valid --> is valid', now make an api call with the same token and see the error
4. See error - 401 status code

**Expected behavior**
User should be validated on dev site and  force him to logout.

**Comment by manueliglesias** [comment]
Hi @jani937 

You can verify that a session is still valid by doing a `Auth.currentSession()`, the promise is rejected when it is not valid.

I hope that helps

**Comment by haverchuck** [comment]
Closing this issue as it appears the question is answered and due to inactivity.
