### ISSUE TITLE
Hide/supress Strike component in FederatedSignIn component?

### ISSUE THREAD

**Issue by sopranolinist** [aws-amplify/amplify-js#3604]
Is there any way to hide or suppress the Strike component that is rendered inside of the [FederatedSignIn component](https://github.com/aws-amplify/amplify-js/blob/5de7a817bc7b68be90450d71fa1644ffb581a58a/packages/aws-amplify-react/src/Auth/FederatedSignIn.jsx)? If i'm only allowing federated sign in with no signin form then it looks really weird to render a separator beneath which is blank space (which is where the signin form would usually go). The separator is generated by the Strike component:

`<Strike theme={theme}>{I18n.get('or')}</Strike>` 

and it makes my login screen look like this when I include `<FederatedSignIn />` in my app:

![image](https://user-images.githubusercontent.com/42662464/60775389-65edb200-a0d7-11e9-91b7-b89717c6387a.png)

**Comment by jordanranz** [comment]
Hi @sopranolinist, check out this [guide for applying custom styling to components](https://aws-amplify.github.io/docs/js/authentication#customize-ui-theme).

Your code would look something like this:
```
const MyTheme = {
    strike: { 'display': 'none' }
}

<Authenticator theme={MyTheme} />
```

We are currently working on making the customization of UI component simpler per [this RFC](https://github.com/aws-amplify/amplify-js/issues/3279). Feel free to add comments if you'd like to add feedback about this experience.

**Comment by sopranolinist** [comment]
Thanks, that answers my question.
