### ISSUE TITLE
Best practice for caching user credentials?

### ISSUE THREAD

**Issue by kwhitejr** [aws-amplify/amplify-js#3606]
** Which Category is your question related to? **
Authentication, Security

** What AWS Services are you utilizing? **
Amplify, Cognito, Appsync

** Provide additional details e.g. code snippets **
Context: using Amplify to build React App SPA backed by an Appsync api and Cognito authentication.

Question: what is the recommended best practice for (1) how frequently the application should authenticate a user; and (2) if less than every api call, how best to store credentials?

If storing credentials (e.g., a `user` blob returned from `Auth.currentAuthenticatedUser()`) is not terrible, then I'm wondering if people have had success with any of the following:

- Redux. Tried and true but seems heavy-handed to implement just for retaining auth credentials.
- Amplify Cache. I've never used it, but seems straightforward.
- Other recommendations?

**Comment by manueliglesias** [comment]
Hi @kwhitejr 

When using Amplify with Cognito User Pools, Amplify takes care of caching the tokens needed to get AWS credentials (in localStorage by default). Credentials are not cached, only kept in memory and they are requested as needed using the tokens provided by Cognito.

Take a loot at https://aws-amplify.github.io/docs/js/authentication#managing-security-tokens for more info
