### ISSUE TITLE
AmazonPersonalizeProvider Analytics is not working

### ISSUE THREAD

**Issue by venkatesh-kadiyala** [aws-amplify/amplify-js#3609]
Hi,

I was on the latest CLI version 1.7.8 and I was trying to implement AWS personalize recommendations using amplify analytics. But when I try to configure it as shown in below images it gives an error saying "AmazonPersonalizeProvider is not a constructor". When I try to add AWSKinesisProvider it works fine.

![Screen Shot 2019-07-08 at 3 17 31 PM](https://user-images.githubusercontent.com/42621275/60836431-a4e13d80-a193-11e9-8601-5b5e359ba43b.png)

**Comment by manueliglesias** [comment]
Hi @venkatesh-kadiyala 

can you do a 

```sh
yarn list --pattern "aws-"
```

or

```sh
npm list | grep "aws-"
```

Specifically, what version of analytics are you using?

**Comment by venkatesh-kadiyala** [comment]
Hi @manueliglesias 
Please see below.
$ npm list | grep "aws-"
├─┬ aws-amplify@1.1.27
│ ├─┬ @aws-amplify/analytics@1.2.15
│ │ ├── @aws-amplify/cache@1.0.26 deduped
│ │ ├── @aws-amplify/core@1.0.26 deduped
│ ├─┬ @aws-amplify/api@1.0.34
│ │ ├── @aws-amplify/auth@1.2.23 deduped
│ │ ├── @aws-amplify/cache@1.0.26 deduped
│ │ ├── @aws-amplify/core@1.0.26 deduped
│ ├─┬ @aws-amplify/auth@1.2.23
│ │ ├── @aws-amplify/cache@1.0.26 deduped
│ │ ├── @aws-amplify/core@1.0.26 deduped
│ ├─┬ @aws-amplify/cache@1.0.26
│ │ └── @aws-amplify/core@1.0.26 deduped
│ ├─┬ @aws-amplify/core@1.0.26
│ │ ├─┬ aws-sdk@2.329.0
│ ├─┬ @aws-amplify/interactions@1.0.29
│ │ └── @aws-amplify/core@1.0.26 deduped
│ ├─┬ @aws-amplify/pubsub@1.0.27
│ │ ├── @aws-amplify/core@1.0.26 deduped
│ ├─┬ @aws-amplify/storage@1.0.29
│ │ └── @aws-amplify/core@1.0.26 deduped
│ ├── @aws-amplify/ui@1.0.19
│ └─┬ @aws-amplify/xr@0.1.16
│   └── @aws-amplify/core@1.0.26 deduped
├─┬ aws-amplify-react@2.3.7
npm ERR! missing: history@latest, required by vcms-clips@0.1.0
npm ERR! peer dep missing: eslint@^4.1.1, required by eslint-config-react-app@2.1.0
npm ERR! peer dep missing: eslint@>=1.6.0 <5.0.0, required by eslint-loader@1.9.0
npm ERR! peer dep missing: eslint-plugin-jsx-a11y@^5.1.1, required by eslint-config-react-app@2.1.0
│ │   │   │ ├── aws-sign2@0.7.0

**Comment by manueliglesias** [comment]
Thanks @venkatesh-kadiyala 

The `AmazonPersonalizeProvider` was added in `@aws-amplify/analytics@1.2.17`, please upgrade your `aws-amplify` package to `1.1.29`
