### ISSUE TITLE
Already existing AppSync problem

### ISSUE THREAD

**Issue by Xocix** [aws-amplify/amplify-js#3610]
** Which Category is your question related to? **
Graphql
** What AWS Services are you utilizing? **
Amplify, AppSync

** Provide additional details e.g. code snippets **
I have used codegen to generate existing graphql schema and querys. The AppSync was created outside the Amplify project.
In my aws-exports.js file i have following:
```
aws_appsync_graphqlEndpoint
aws_appsync_region
aws_appsync_authenticationType
aws_appsync_apiKey

```
When i try to call the graphql endpoint like this:
```
import { API, graphqlOperation } from 'aws-amplify';
import * as queries from '../../graphql/queries';
const test = async () => {
   return await API.graphql(graphqlOperation(queries.TestMethod));
};

console.log(test());
```

i get following error back:
`Unhandled promise rejection Error: "No credentials"`

I tried searching for it but cannot find anything. Am i missing something?

Also i am running these versions on the front end:  
```
"aws-amplify": "^1.1.29",
"aws-amplify-react":` "^2.3.9"
```

**Comment by manueliglesias** [comment]
Hi @Xocix 

If your AppSync API's authentication mode is `AWS_IAM`, requests to the API need to be signed using IAM credentials.

Typically, Amplify takes care of this when using the Auth category.

Take a look at https://aws-amplify.github.io/docs/js/authentication#configure-your-app and let us know if you run into problems.

**Comment by Xocix** [comment]
Hi @manueliglesias, my authentication mode is set to API_KEY. Sorry for not writing that down. The api key is also specified in the aws-exports.js file so everything should be there. 

I have also tried now to add mandatorySignIn: false to the Auth object but still no success.
