### ISSUE TITLE
getSession in amazon-cognito-identity-js returning undefined sporadically 

### ISSUE THREAD

**Issue by gilesbutler** [aws-amplify/amplify-js#3613]
**Describe the bug**
We're using `cognitoUser.getSession` to check whether a user is logged in but we've noticed that it occasionally returns `undefined`. The user then gets kicked out to our login screen but if we refresh the page without entering credentials they're still logged in.

**To Reproduce**
We haven't found a way to reproduce the issue as it happens randomly.

**Expected behavior**
Call `cognitoUser.getSession` and it returns either `null` or the session object if a user is signed in.

**Desktop (please complete the following information):**
 - OS: OSX Mojave 10.14.5
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max
 - OS: iOS 12
 - Browser: Chrome
 - Version: latest

**Sample code**
```
const isSessionValid = (cognitoUser) => {
  return cognitoUser.getSession((err, session) => {
    if (err) {
      CustomError(err);
      return false;
    }

    // Return whether the session is valid
    if (session.isValid()) {
      return true;
    }

    return false;
  });
}
```

```
export const isAuthenticated = () => {
  // Get the current user
  const cognitoUser = userPool.getCurrentUser();

  // Check there is an actual user object
  if (!cognitoUser) return false;

  // Get the current session
  return isSessionValid(cognitoUser);
};
```

**Comment by pl-synth** [comment]
amazon-cognito-identity-js => v3.0.14

Getting same thing, am able to reproduce it on our app. getSession is returning undefined.
This happens only on very first load, once every 30 min. Reloading helps.
Workaround is to call it again, not ideal ofc! There're no errors or anything, just undefined.

**Comment by iartemiev** [comment]
@gilesbutler @pl-synth are you guys still experiencing this issue?

I attempted to reproduce this issue programmatically by retrieving the session every 5 seconds with the following code:

```javascript
let interval;
const getSessionLoop = () => {
  console.log(`Started loop at: ${Date()}`);

  interval = setInterval(() => {
    const cognitoUser = userPool.getCurrentUser();

    cognitoUser.getSession((err, session) => {
      if (err) {
        clearInterval(interval);
        console.log(err);
      }

      if (session === undefined) {
        clearInterval(interval);
        console.log(`session is undefined at: ${Date()}`);
        console.log(cognitoUser);
      }

      if (!session.isValid()) {
        console.log(`session is invalid at: ${Date()}`);
        console.log(cognitoUser);
        console.log(session);
      }
    });
  }, 5000);
};
```

I executed the function and left it running simultaneously in Chrome and FF (both on macOS) for 4 hours but `session` never came back as `undefined` throughout that time.

I used the same version of the library as @pl-synth (3.0.14).

If you're still experiencing this issue, could you please create and share a minimal app that demonstrates the problem?

**Comment by gilesbutler** [comment]
Thanks for following up on this @iartemiev, really appreciate your effort. We refactored our login system recently and we're not seeing this anymore. That leaves me to believe it was an issue on our end. Please feel free to close this issue if @pl-synth isn't seeing it anymore. Thanks again.
