### ISSUE TITLE
1.1.30 - (ReferenceError: window is not defined) node_modules/@aws-amplify/ui/dist/aws-amplify-ui.js:1:289

### ISSUE THREAD

**Issue by anarerdene** [aws-amplify/amplify-js#3615]
1.1.30 - (ReferenceError: window is not defined) node_modules/@aws-amplify/ui/dist/aws-amplify-ui.js:1:289

**Comment by csatterlee** [comment]
I'm havingthe same issue with next.js, but having no issues with vanilla react. This is after using the solution here: https://github.com/aws-amplify/amplify-js/issues/1535 to fix a similar error with the style.css file. The only amplify I'm using is withAuthenticator.

**Comment by tuliohc** [comment]
Same here with version 1.1.28

**Comment by mkondel** [comment]
Possible quick fix is to add 'resolutions' to your package.json. Found in https://github.com/aws-amplify/amplify-js/issues/3477.
```json
  "resolutions": {
    "@aws-amplify/ui": "1.0.19"
  },
```

**Comment by BramDecuypere** [comment]
Here is what I had to do to get it fixed asap in my project:

Step 1: remove all the current packages + package-lock.json (i'm using npm instead of yarn, for yarn, I guess the answer above works best)

**Comment by aldegoeij** [comment]
Same issue on Gatsby build, related tickets: https://github.com/aws-amplify/amplify-js/issues/3486, https://github.com/aws-amplify/amplify-js/issues/3015, https://github.com/aws-amplify/amplify-js/issues/876, https://github.com/aws-amplify/amplify-js/issues/3477

**Comment by aldegoeij** [comment]
Version 1.0.21-unstable.0 PR: https://github.com/aws-amplify/amplify-js/pull/3512

**Comment by aldegoeij** [comment]
> Possible quick fix is to add 'resolutions' to your package.json. Found in #3477.
> 
> ```json
>   "resolutions": {
>     "@aws-amplify/ui": "1.0.19"
>   },
> ```

Actually `1.0.21-unstable.0` did the trick for me (with amplify/core on `1.1.30`

**Comment by ajhool** [comment]
A quick version push to just resolve this issue would be appreciated immensely

**Comment by exoego** [comment]
Is this resolved by #3512 ?

**Comment by sammartinez** [comment]
This issue is resolved. Closing issue as fix is completed.
