### ISSUE TITLE
No matching version found for @aws-amplify/analytics@^1.2.18

### ISSUE THREAD

**Issue by bossley9** [aws-amplify/amplify-js#3616]
**Describe the bug**

Attempting to install aws-amplify via npm produces the following error:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-amplify/analytics@^1.2.18
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'aws-amplify'
npm ERR! notarget
```
It appears that a non-existent version of aws-amplify analytics is being referenced.
 
**To Reproduce**

Following the [AWS Amplify "getting started" tutorial](https://aws-amplify.github.io/docs/js/start) produces the error.

1. run `mkdir aws-test && cd aws-test`
2. run `npm i aws-amplify`

**Additional context**
I tried installing via `yarn add aws-amplify` as well but with no success

**Comment by Elijen** [comment]
Same issue here. Seems that publish of new version is in progress.

https://github.com/aws-amplify/amplify-js/commit/ad41f869e6dd5ef7870d2b76ef99e8829a96061c

**Comment by BadAsstronaut** [comment]
Hard-wiring the aws-amplify version to a previous release (1.1.29 or 1.1.28) still throws the same errors.

**Comment by easydonny** [comment]
Now `npm install --save aws-amplify` works without any error.
