### ISSUE TITLE
Using Federated ID to sign up a Google user times out while logging in with a Google user succeeds

### ISSUE THREAD

**Issue by wmcbain** [aws-amplify/amplify-js#3622]
**Describe the bug**
In our app we're using federated identities to sign up and login users with Google. How we've had this setup has been working until very recently when we got a report from a user that they couldn't sign up. Oddly, login works but sign up does not.

Using `window.LOG_LEVEL = 'DEBUG';` does not provide any additional information.

In our app we:

1. Initialize the Google API with `client:auth2`
1. Popup Google auth when the user clicks a button
1. Deconstruct the attributes to pass to `federatedSignIn`
1. Upon success log the user in.

Sign up code:
```
const {
    El, // id
    Zi: { id_token, expires_at },
    w3: { 
      U3, // email
      ofa, // first name
      wea // last name
    }
} = user;

await Auth.federatedSignIn('google', { token, expires_at: expiry }, { name: email });
```

**To Reproduce**
1. Attempt to sign a user up using the Google API to get their tokens and credentials
2. Pass that information to 
```
await Auth.federatedSignIn('google', { token, expires_at: expiry }, { name: email });
```
3. Wait for timeout error

**Expected behavior**
Federated sign in signs up the user. (Worked until recently with no changes to the underlying code)

**Screenshots**

Error message:
```
TimeoutError: Timeout
    at XMLHttpRequest.<anonymous> (http://localhost:3000/static/js/1.chunk.js:68472:34)
    at XMLHttpRequest.fn.___hb (http://localhost:3000/static/js/1.chunk.js:227000:25)
index.js:6105 {
  "message": "Timeout",
  "code": "TimeoutError",
  "time": "2019-07-10T23:07:33.515Z",
  "region": "us-east-2",
  "hostname": "cognito-identity.us-east-2.amazonaws.com",
  "retryable": true
}
```

**Comment by mlabieniec** [comment]
@wmcbain is this app you are seeing this on an Angular app? Otherwise, what does your stack look like? This looks like a network timeout ultimately, but i've seen this in an angular app recently as well, specifically on Ubuntu OS and Angular 7

**Comment by manueliglesias** [comment]
Hi @wmcbain 

Can you provide a request id for the request that timed out? (You can find it as a response header in the network tab of the developer tools)

**Comment by mauerbac** [comment]
@wmcbain - closing since we haven't heard back. Please create a new issue if you have further questions!
