### ISSUE TITLE
`Auth.confirmSignIn` throws `UserNotFoundException` upon SMS code confirm

### ISSUE THREAD

**Issue by cboar** [aws-amplify/amplify-js#3623]
**Describe the bug**
I am attempting to implement SMS MFA with the API directly (not `aws-amplify-react-native` Components). After setting up the MFA as described below, I sign out of the User, sign back in, receive the SMS code, and try to confirm it. Instead of succeeding, `Auth.confirmSignIn` throws a `UserNotFoundException`.

**To Reproduce**
1. Sign into a Cognito account that does not yet have MFA set up.
~~~
const user = await Auth.signIn(username, password);
~~~
2. We have signed into the user. Our tokens are there, our account shows up in the User pool list. The user absolutely exists.
3. Get 10-digit phone number from input, set up MFA with
~~~
const phone = '5553334444';
const user = await Auth.currentAuthenticatedUser();
const result = await Auth.updateUserAttributes(user, {
    phone_number: `+1${phone}`,     
});
await Auth.setPreferredMFA(user, 'SMS');
~~~
4. Sign out
~~~
Auth.signOut();
~~~
5. Sign back in
~~~
const user = await Auth.signIn(username, password);
~~~
6. Ding ding ding! We get `user.challengeName === 'SMS_MFA'`.
7. Ring ring ring! Code shows up via SMS.
8. Let's confirm sign in.
~~~
await Auth.confirmSignIn(user, code, 'SMS_MFA');
~~~
9. Boom! An error object is thrown:
~~~
Object { code: "UserNotFoundException", name: "UserNotFoundException", message: "User does not exist." }
~~~
10. We are not signed in.

**Expected behavior**
Confirm SMS code, sign into User.

**Screenshots**
None

**Smartphone (please complete the following information):**
 - OS: Android 8.0
 - Platform: `react-native`
 - Versions: `react-native@0.59.5`, `aws-amplify@1.1.29`

**Additional context**
Here is some Auth related configuration relevant to our user pool:
* MFA is set to Optional.
* We are using a `UserMigration` Lambda, and therefore use `authenticationFlowType: 'USER_PASSWORD_AUTH'`
* The Lambda imports relevant attributes, but NOT `phone_number` and `phone_number_verified` remains `false` throughout.
* Users have `phone_number` write permissions for all App clients.

**Comment by manueliglesias** [comment]
Hi @cboar 

I don't have a clear answer for you today, but, can you take a look at this [AWS Forums thread](https://forums.aws.amazon.com/thread.jspa?threadID=275106) and see if the suggestions there work for you?

**Comment by cboar** [comment]
Hello @manueliglesias. Our `UserMigration` lambda has full `cognito-idp` permissions, and we're not having any issues with the migration itself (unless this is related?). Migrated users show up in the User pool, they can login, get tokens, reset password, and so on. The only issue I've come across so far is the confirming the SMS code I receive.

**Comment by cboar** [comment]
Could this be re-labeled as a bug? Considering the User certainly exists in the User pool.

**Comment by EJRosie** [comment]
For anyone else who has this issue, for me, I had a random user sub set as the username in my userpool, but email login.
`Auth.signIn()` returns an object with a username of the email, instead of the sub. I fixed this problem by explicitly setting the `username` of the signIn response to the actual username of the user, which happens to be contained within `challengeParam.USER_ID_FOR_SRP`

Essentially:
`var user = await Auth.signIn(email, password);`
`user.username = user.challengeParam.USER_ID_FOR_SRP;`
`await Auth.confirmSignIn(user, code, "SMS_MFA");`

**Comment by bojantv** [comment]
Thanks @EJRosie, I think this should work without the trick.

**Comment by steveevers** [comment]
@EJRosie this also resolved it for me. Thank you!
