### ISSUE TITLE
Add custom domain to Cognito user pool

### ISSUE THREAD

**Issue by kimfucious** [aws-amplify/amplify-js#3624]
I've created an app using Amplify Init, provisioned back-end resources with the `Amplify CLI`, and published the front end by connecting a repo in the `Amplify Console`.  I did not create a new environment when connecting the app in the console.

The app is configured with a `custom domain`.

In looking at the `Cognito user pool`, I see there are some UI customizations possible; however, they require a domain to be configured, which in turn requires a cert to be provisioned.

I created the cert, using `ACM`, for the domain that matches the app's domain in the same region where the app and all related services were created.  I did this because, I have no idea how/where to access the cert that was provisioned via the `Amplify console` when adding a `custom domain`.

The `Cognito console` / user pool / App Integration / domain name tab does not recognize the cert, showing the message: 

```console
We didn’t find any AWS managed certificates for this region. To add one, click here.
```

**Questions**
Am I barking up the wrong tree here?  
Is there a preferred, or better, way to be customizing the UI on the `Amplify Auth` components/elements?

I **can** modify things using targeted CSS selectors, like the below, but it's seems tedious and that I am somehow not seeing a better way.

```js
/* Adjusts the styles for Amplify greetings bar */
div[class^="Nav__navBar"] {
  background-color: transparent;
  border-color: transparent;
}
```

Any thoughts would be most appreciated.  Thanks.

**Comment by manueliglesias** [comment]
Hi @kimfucious 

> Is there a preferred, or better, way to be customizing the UI on the Amplify Auth components/elements?

What kind of front-end do you have? (iOS, Android, react, react-native, vue, etc)

For example, with react you could follow this to have an OAuth flow where you have full control of the UI
https://aws-amplify.github.io/docs/js/authentication#react-components

**Comment by kimfucious** [comment]
Hi @manueliglesias 

Thanks for following up on this.  I'm using Amplify in a create-react-app.

What I've wound up doing, is creating my own custom sign-in form, backing it with Amplify Auth methods, such as `Auth.signIn()` and `Auth.signUp()`.

I've then created my own "greetings bar" which shows a sign in or sign out button based on the Auth state.  The sign in button launches a modal with the sign-in form, and signout simply calls Auth.signOut().

I'm using a React Effect hook to update the UI based on the Auth status, while access to the backend API is controlled via IAM roles for auth and nonAuth users.

Not sure if this is best practice, but this seems to give me full control over the UI and avoids using the `withAuthenticator HOC`, which doesn't seem to allow non-authenticated users to access the site.

**Comment by haverchuck** [comment]
@kimfucious  - It sounds like you are up and running, so I'm closing this issue.  Please open another if you have additional questions.
