### ISSUE TITLE
API access in Lambda using AWS.config.credentials

### ISSUE THREAD

**Issue by oste** [aws-amplify/amplify-js#3626]
** Which Category is your question related to? **
API

** What AWS Services are you utilizing? **
Lambda

** Provide additional details e.g. code snippets **
I am trying to access my AppSync api from within Lambda. When creating my lambda function I gave it permission to access the AppSync api and I see the IAM role inside the Lambda designer.

I thought something like this should work for an s3 event notification:

```
global.fetch = require('node-fetch');

const gql = require('graphql-tag')
const AWS = require('aws-sdk')
const AWSAppSyncClient = require('aws-appsync').default;
const AUTH_TYPE = require('aws-appsync').AUTH_TYPE



exports.handler = function (event, context) { //eslint-disable-line


  const client = new AWSAppSyncClient(
    {
      url: process.env.API_GRAPHQLAPIENDPOINTOUTPUT,
      region: process.env.REGION,
      auth: {
        type: AUTH_TYPE.AWS_IAM,
        credentials: AWS.config.credentials,
      },
      disableOffline: true,
    },
    {
      defaultOptions: {
        query: {
          fetchPolicy: 'network-only',
          errorPolicy: 'all',
        },
      },
    },
  )

  client.mutate({
    mutation: gql(`mutation{
      createMedia(createMediaInput: {
        User_id: 1
        name: "testing"
      }){
        id,
        name
      }
    }`)
  }).then(result => {
    console.log(result);
  })
```

However I am seeing `Error: GraphQL error: Not Authorized to access createMedia on type Mutation`. Am I missing something? I was hoping that `AWS.config.credentials` would pick up the attached AWS AppSync IAM role with create/update permissions allowed.

**Comment by undefobj** [comment]
You probably need an additional Authorization type. We recently released documentation for this use case with a Lambda that doesn't require external dependencies. Can you try to follow this guide: https://aws-amplify.github.io/docs/cli-toolchain/quickstart#graphql-from-lambda

**Comment by oste** [comment]
@undefobj thanks for the advice. Unfortunately I am seeing the following error when trying to use `@aws_iam`

```
? Are you sure you want to continue? Yes
✖ An error occurred when pushing the resources to the cloud

Schema Errors:
Unknown directive "aws_iam".
GraphQL request (30:59)
29:   deleteMedia(id: Int!): Media
30:   createMedia(createMediaInput: CreateMediaInput!): Media @aws_iam
                                                              ^
```

**Comment by undefobj** [comment]
As outlined in the documentation, the `@aws_iam` directive is not supported in the CLI at this time. You need to use the console per the steps in the link above.

**Comment by oste** [comment]
Great, that works but won't this prevent me from using `amplify push` for the api? From what I understand it would overwrite the change made in the console.

Is there an open issue for this or pending PR? If not maybe I can find some time to dig in.

**Comment by oste** [comment]
https://github.com/aws-amplify/amplify-cli/issues/624 and https://github.com/aws-amplify/amplify-cli/issues/1386 both seem to be related
