### ISSUE TITLE
Unauthenticated identity is not removed from localstorage at sign out

### ISSUE THREAD

**Issue by sjohnston88** [aws-amplify/amplify-js#3627]
**Describe the bug**
We have both unauthenticated and authenticated users. When an unauthenticated user signs in, their unauthenticated identity is disabled in the identity pool and merged with their authenticated one. However, if the users now signs out they are reassigned the unauthenticated identity they had before, which is now disabled, we would expect them to be given a brand new unauthenticated identity.

**To Reproduce**

1. As an unauthenticated user, get some credentials:
```
Auth.currentCredentials()
> data: { authenticated: false, _identityId: eu-west-1-UNAUTHENTICATED-identity } 
```
2. Sign in as an authenticated user:
```
Auth.signIn(username, password)
```
3. As an authenticated user, get some credentials:
```
Auth.currentCredentials()
> data: { authenticated: true, _identityId: eu-west-1-AUTHENTICATED-identity }
 ```
4. Sign out
```
Auth.signOut()
```
5. Check the credentials again:
```
Auth.currentCredentials()
> data: { authenticated: false, _identityId: eu-west-1-UNAUTHENTICATED-identity } 
```

**Expected behavior**
1. Repeat steps 1-4
5. Check the credentials again:
```
Auth.currentCredentials()
> data: { authenticated: false, _identityId: eu-west-1-NEW-UNAUTHENTICATED-identity } 
```

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version [75.0.3770.100]

**Additional context**
This seems to be caused by the unauthenticated identity not being removed from localstorage when the user signs out. Removing it manually, forces amplify to get a new identity.

**Comment by Amplifiyer** [comment]
Hi @sjohnston88, apologies for coming back to this issue so late. I just tried to reproduce with your steps and I was able to confirm that after signing out the old identity id is still saved in the local storage. However I was still able to make all the unauthenticated allowed AWS calls (API, pinpoint, S3 etc)

Can you let us know if you are still facing this issue?
