### ISSUE TITLE
aws-amplify-react Authenticator component issue

### ISSUE THREAD

**Issue by johnbowdenatfacet** [aws-amplify/amplify-js#3636]
**Describe the bug**
aws-amplify-react@2.3.10 Authenticator component doesn't correctly update authState in child components.

**To Reproduce**
1. yarn add aws-amplify-react@2.3.10
2. import { Authenticator } from 'aws-amplify-react';
3. Child components stuck at 'loading' authState

**Expected behavior**
aws-amplify-react@2.3.9 was passing correct authState to children

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

With no user session:
...
[DEBUG] 04:47.609 AuthClass - Getting current session
ConsoleLogger.js:101 [DEBUG] 04:47.610 AuthClass - Getting current session
ConsoleLogger.js:101 [DEBUG] 04:47.614 AuthClass - Getting current session
3ConsoleLogger.js:101 [DEBUG] 04:47.616 AuthClass - Failed to get user from user pool
3ConsoleLogger.js:111 [DEBUG] 04:47.616 AuthClass - Failed to get the current user No current user
helpers.js:18 No current user
ConsoleLogger.js:101 [DEBUG] 04:47.617 AuthClass - getting current authenticted user
2ConsoleLogger.js:101 [DEBUG] 04:47.618 AuthClass - Getting current session
2ConsoleLogger.js:101 [DEBUG] 04:47.618 AuthClass - Failed to get user from user pool
ConsoleLogger.js:101 [DEBUG] 04:47.619 AuthClass - cannot load federated user from auth storage
ConsoleLogger.js:101 [DEBUG] 04:47.619 AuthClass - get current authenticated userpool user
2ConsoleLogger.js:111 [DEBUG] 04:47.619 AuthClass - Failed to get the current user No current user
ConsoleLogger.js:101 [DEBUG] 04:47.619 AuthClass - Failed to get user from user pool
ConsoleLogger.js:111 [DEBUG] 04:47.619 AuthClass - The user is not authenticated by the error No current user

With user session:
...
[DEBUG] 03:26.515 Parser - parse config (3) [{…}, "to amplifyconfig", {…}]
ConsoleLogger.js:111 [DEBUG] 03:26.516 Hub - Dispatching to auth with  {event: "parsingCallbackUrl", data: {…}, message: "The callback url is being parsed"}
ConsoleLogger.js:111 [DEBUG] 03:26.517 Analytics - on hub capsule auth {event: "parsingCallbackUrl", data: {…}, message: "The callback url is being parsed"}
ConsoleLogger.js:111 [DEBUG] 03:26.517 Hub - Dispatching to auth with  {event: "parsingCallbackUrl", data: {…}, message: "The callback url is being parsed"}
ConsoleLogger.js:111 [DEBUG] 03:26.517 Hub - Dispatching to auth with  {event: "parsingCallbackUrl", data: {…}, message: "The callback url is being parsed"}
ConsoleLogger.js:111 [DEBUG] 03:26.518 Hub - Dispatching to auth with  {event: "parsingCallbackUrl", data: {…}, message: "The callback url is being parsed"}
ConsoleLogger.js:111 [DEBUG] 03:26.519 Hub - Dispatching to auth with  {event: "configured", data: null, message: "The Auth category has been configured successfully"}
ConsoleLogger.js:111 [DEBUG] 03:26.519 Analytics - on hub capsule auth {event: "configured", data: null, message: "The Auth category has been configured successfully"}
ConsoleLogger.js:111 [DEBUG] 03:26.519 Hub - Dispatching to auth with  {event: "configured", data: null, message: "The Auth category has been configured successfully"}
ConsoleLogger.js:111 [DEBUG] 03:26.520 Hub - Dispatching to auth with  {event: "configured", data: null, message: "The Auth category has been configured successfully"}
ConsoleLogger.js:111 [DEBUG] 03:26.520 Hub - Dispatching to auth with  {event: "configured", data: null, message: "The Auth category has been configured successfully"}

**Comment by iartemiev** [comment]
@johnbowdenatfacet are you still experiencing this issue? Have you had a chance to try it with the latest versions of `aws-amplify` and `aws-amplify-react`?

If you are still having the same problem, would you mind posting some sample code of the parent and child components?
