### ISSUE TITLE
Why does the private storage path not match the Cognito user ID?

### ISSUE THREAD

**Issue by ffxsam** [aws-amplify/amplify-js#364]
I noticed that when I used `Storage.put` to put a private file, the uuid in the folder name doesn't match my Cognito user ID. What is the uuid used in the S3 path?

This might be an issue in some scenarios. For instance, an admin user might want to look at all of a user's files in S3. Their Cognito uuid is easy enough to ascertain and use in an S3 method call. But how do we obtain this other uuid that `Storage` is using?

**Comment by mlabieniec** [comment]
The path is the cognito identity id from cognito federated identities. This is a uuid that is linked to your identity and will be the same no matter what you login with i.e. User Pools or social federation.

**Comment by ffxsam** [comment]
Ok. So let's say an admin user wanted to list all users in the system, and access their files on S3. How would I go about fetching those federated IDs?

**Comment by mlabieniec** [comment]
We currently don't have support for admin / user functionality in the library yet (via user pools). We do have this in the backlog. There is a thread in this issue we are tracking: https://github.com/aws/aws-amplify/issues/54

With User Pools though, you could place the IdentityID, on a custom attribute for you cognito user pools user, and/or store a mapping in dynamodb or similar key/value store.

**Comment by ffxsam** [comment]
That's a good idea. Though I'm not using all of Amplify's pieces (like `Storage`, until it supports upload progress reporting), I want to stick to its conventions as much as I can since I'll likely be using it long-term.

**Comment by Jun711** [comment]
@mlabieniec does aws amplify storage support access to dynamodb? Do I have to use aws js sdk: [aws-sdk](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)?

**Comment by mlabieniec** [comment]
Added docs for this:
https://aws.github.io/aws-amplify/media/quick_start#working-with-aws-service-interface-objects

**Comment by rpgreen** [comment]
Where would one get the value for this user ID? I don't see it exposed anywhere in the client session, or even in the Cognito APIs? My auth role defines this as "${cognito-identity.amazonaws.com:sub}" but the value used by amplify doesn't match any value of "sub" as shown by Cognito.

FWIW, the current storage model is too restrictive for my use-case. I want to allow users to PutObject but use a custom authorization strategy for GetObject, which requires me to store the S3 url in my backend.

At a minimum, it would be a lot easier to work with if put() just returned the actual full S3 key or URL

**Comment by byennen** [comment]
I agree with @rpgreen, we're running into an issue where we PUT a file into a protected folder and we're trying to build the URL for that protected folder with the key returned. 

As @rpgreen pointed out the `"cognito-identity.amazonaws.com:sub` does not match the folder created by the PUT.

```
From the docs:
Protected: Readable by all users, but writable only by the creating user. Files are stored under protected/{user_identity_id}/ where the user_identity_id corresponds to the unique Amazon Cognito Identity ID for that user.
```

I also agree, that the PUT should return the actual URL and not just the key.

I have to do a GET on the S3 file to get the correct URL back after the PUT right now.

This should be reopened.

**Comment by byennen** [comment]
@dabit3 can you review the comment above and let me know if I'm missing something or is this a bug with amplify-js? TY!!

**Comment by dabit3** [comment]
@byennen I'm not sure about the answer to this one. cc @mlabieniec any ideas on how to accomplish this?

**Comment by mlabieniec** [comment]
This is working as intended e.g. returning the key not the URL. The key can be used to say, store into a database etc. whereas the url would/could be a signed/temporary url that could expire, so it would not be something you’d generally store but generate on the fly as above, hence returning the key from out, then needing to generate a url. We can take this as a feature request though and review, perhaps with arguments to only receive key or url? cc @sammartinez

**Comment by ricobanga** [comment]
Hello, Has someone found out how to solve this issue ? 
Event from backend, I could find no way to get the identitySub/foldeNamer where PUT uploaded the file.

**Comment by harrysolovay** [comment]
The ambiguity of the latter half of this issue seems to be consistency of identity ID (no matter whether you've logged in solely with user pools, or with multiple federated identities).

Like @mlabieniec mentioned...

> With User Pools though, you could place the IdentityID, on a custom attribute for you cognito user pools user, and/or store a mapping in dynamodb or similar key/value store.

Aka., you could maintain the mappings yourself.

Or, you could set up a [post confirm trigger](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-post-confirmation.html) to link accounts, thereby ensuring a consistent identity ID upon login (aka. the bucket will remain the same between differently-logged-in sessions).

Please let me know if this doesn't answer the left-over questions––in which case, please provide some more details about the use case.
