### ISSUE TITLE
Is there a simple way to check if the user is logged in or not (in code)?

### ISSUE THREAD

**Issue by ajhool** [aws-amplify/amplify-js#3640]
**Is your feature request related to a problem? Please describe.**
A user navigates to my webapp. I have a header on the webapp that depends on the user's login state (eg. a button says "Account" if the user is logged in or "Sign Up" if the user is not logged in). I don't want to use the Authenticator component because I don't want to force the user to login immediately.

**Describe the solution you'd like**
In my header's render function, something like:

```
// header.tsx
import Auth from '@aws-amplify/auth';
const header = () => (Auth.isUserLoggedIn()) ? <div>Account</div> : <div>Sign In</div>;

```

**Describe alternatives you've considered**

I believe that this code is close, but I think that it forces the user to login in order to view the header, which not necessary

```
const header = ({authState}) => (
      (authState === `signedIn`) ? <div>Account</div> : <div>Sign In</div>;
)

return withAuthenticator(header);
```

**Additional context**

**Comment by all-iver** [comment]
@ajhool judging from this and your other recent issue I think you're at the same point I'm at, going through the tutorials and slowly realizing the intended workflow doesn't apply to you.  All the methods I could find to do this are async, so there was no obvious way to do this just from a render function.  I ended up using the Authenticator component manually (i.e. don't use withAuthenticator unless you're forcing the user to log in), and I have my top-level component provide the user to children as React context.

```
  let [user, setUser] = useState(null)
  useEffect(() => {
    let updateUser = async authState => {
      try {
        let user = await Auth.currentAuthenticatedUser()
        setUser(user)
      } catch {
        setUser(null)
      }
    }
    Hub.listen('auth', updateUser) // listen for login/signup events
    updateUser() // check manually the first time because we won't get a Hub event
    return () => Hub.remove('auth', updateUser) // cleanup
  }, []);

```

This code is in my top level component's render function (using React hooks), and then it uses React context to provide the user to its children.  This seems to work, although there is probably a small window where you render without having the user, so there's a flash when it updates.  I'm just learning Amplify so I don't know if this is the best way to do it.

**Comment by ajhool** [comment]
Thanks, again, @all-iver ! I'm also using Authenticator manually, but with the added complication that Authenticator breaks SSR **at import time**, so I have a pretty heavy workaround just to get Authenticator to defer import to client side and still connect to the rest of Amplify; I try to use it sparingly and might eject completely

I assume you've looked at the source of Authenticator, but it looks like your strategy eliminates all of the fluff to achieve the desired isSignedIn flag. Nice job, it looks great!
https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Auth/Authenticator.jsx

**Comment by all-iver** [comment]
Ah, yeah I ran into that problem with breaking imports too. :)  For me just importing Auth from @aws-amplify/auth (and Hub from @aws-amplify/core) fixed my build, and I have to configure it with Auth.configure() instead of Amplify.configure().  I think those are the only changes I had to do to get it working iirc...  I'm only using Authenticator though, nothing else in Amplify yet.

**Comment by all-iver** [comment]
Oh yeah, I also had to import Authenticator like this:

```
import { Authenticator } from 'aws-amplify-react/dist/Auth'
import { AmplifyTheme } from 'aws-amplify-react/dist/AmplifyTheme'
```

**Comment by ajhool** [comment]
The Authenticator issue became more problematic when I started using API and Storage. I found that the Authenticator component (when dynamically imported) was not properly connected to API and Storage, also the aws-amplify-react package wasn't properly hiding components. At the time, I was fairly sure that I isolated the behavior but it's possible that the problem was actually caused by having multiple versions of amplify installed in the various dependencies.

```
   // This import breaks code
   // import { Authenticator, Greetings, Loading } from 'aws-amplify-react';

    let _Authenticator;
    let _Greetings;
    let _Loading;
    let isServer = true;

    componentDidMount() {
      ...
      // Dynamically load the components client-side.
      const { Authenticator, Greetings, Loading } = await import('aws-amplify-react'); 
      let _Authenticator = Authenticator;
      let _Greetings = Greetings;
      let _Loading = Loading;
      isServer = false;
      ...
    }

    render(){
      {
        !isServer && (<_Authenticator hide={[_Greetings, _Loading]} >
             .....
          <_Authenticator/>)

        isServer && <div />
    }

```

This is what I'm currently using and it is working, so I haven't tried moving to something more simple. But at the time, this was quite a pain to figure out. -- if your solution works, just stick with it. Definitely expect a lot of bumps in the road as you add more components


----

Per your second post, that's smart. Nice find

**Comment by ajhool** [comment]
Tested out @all-iver 's answer and it's great. Also amazed by React hooks -- hadn't gotten around to learning them, but they're really useful and backwards compatible. Just to extend @all-iver 's example, here is what your code should look like, all together:

Two remaining issues:
1. Because the initial call to `updateUser()` is not `await updateUser()`, there will be a ~1.5 ( #2154) second flash of webpage where the user is presumed not to be logged in. This could be resolved by using a localStorage `isLoggedIn` flag that can make a much faster guess. That flag management could also live inside `useUserStatus`. Maybe there's an Amplify field that could serve as a quick guess, too.

Another solution would be to set the initial state of `user` to be undefined or something like that -- then the three states are: undefined (still waiting for an answer from the server -> display splash screen), null (server says nobody is logged in), CognitoUser (sever says somebody is logged in).

```
// useuserstatus.ts
'use strict'

import React, { useState, useEffect } from 'react';
import Auth from '@aws-amplify/Auth';
import { Hub } from '@aws-amplify/core';

/**
 * userUserStatus is a react hook that tracks the user's login status and provides a "isLoggedIn" flag that can be checked in code.
 */

function useUserStatus() {
  let [user, setUser] = useState(null)
  
  useEffect(() => {
    let updateUser = async () => {
      try {
        let user = await Auth.currentAuthenticatedUser()
        setUser(user)
      } catch {
        setUser(null)
      }
    }
    Hub.listen('auth', updateUser) // listen for login/signup events

   // we are not using async to wait for updateUser, so there will be a flash of page where the user is assumed not to be logged in. If we use a flag 
    updateUser() // check manually the first time because we won't get a Hub event
    return () => Hub.remove('auth', updateUser) // cleanup
  }, []);

  return user;
}

export default useUserStatus;
```

```
// header.tsx
import useUserStatus from './useuserstatus';

// I'm using a functional component, but you can also use react hooks in a React Component Class
const Header = () => {
  const userStatus = useUserStatus();
 
  const isLoggedIn = (null !== userStatus);

  return (isLoggedIn) ? 
    (<div>
      <a href='/signin'>
        <button>Login</button>
      </a>
     </div>) : <div>Hello {user.attributes.email} <button>Sign Out</button></div>
}

```

I also named the component "useUserStatus", but it's really more of a "useCurrentUser" component... if you just want a simple "isLoggedIn" flag, then you should:
  1. Change the `user` and `setUser` variables to `isLoggedIn` and `setIsLoggedIn`
  2. replace `setUser(user)` with `setIsLoggedIn( (null === user) );

This component will automatically update when the user logs in or logs out. Might be related to #

**Comment by ajhool** [comment]
I haven't tested this code, but this would be my initial guess about how to use `localStorage` to do this. If you're using SSR, you might need to check a request header instead of checking the localStorage:

// useuserstatus.ts
'use strict'

import React, { useState, useEffect } from 'react';
import Auth from '@aws-amplify/Auth';
import { Hub } from '@aws-amplify/core';

/**
 * userUserStatus is a react hook that tracks the user's login status and provides a "isLoggedIn" flag that can be checked in code.
 */

const _guessInitialLoginStatus = (): boolean => {
   if( isServer() ){
      // Not sure how to do this on the server. Maybe check a header flag??
   } else {
      const flagValue = localStorage.getItem(`isUserLoggedIn`);

      // If the flag is null, then the user probably isn't logged in (if you add this to your code, the user will experience a one-time-only bad guess). Otherwise, check the flag's value.
      const isLoggedIn = (null !== flagValue) && flagValue;

      return isLoggedIn;
   }
}

const _setFlag = (value: boolean) => {
  localStorage.setItem('isUserLoggedIn', value);
}

function useUserStatus() {
  const initialGuess = _guessInitialLoginStatus();
  let [isLoggedIn, setIsLoggedIn] = useState(initialGuess)

  const _updateLoggedInState = (value: boolean) => {
    setIsLoggedIn(value);
    setFlag(value);
  }
  
  useEffect(() => {
    let updateUser = async () => {
      try {
        await Auth.currentAuthenticatedUser()
        _updateLoggedInState(true);
      } catch {
        _updateLoggedInState(false);
      }
    }
    Hub.listen('auth', updateUser) // listen for login/signup events

   // we are not using async to wait for updateUser, so there will be a flash of page where the user is assumed not to be logged in. If we use a flag 
    updateUser() // check manually the first time because we won't get a Hub event
    return () => Hub.remove('auth', updateUser) // cleanup
  }, []);

  return user;
}

export default useUserStatus;

**Comment by jdavidhermoso** [comment]
Auth.currentSession()?

**Comment by ajhool** [comment]
Keeping open for auth v2 milestone

**Comment by ajhool** [comment]
Keeping open for auth v2 milestone round 2

**Comment by ajhool** [comment]
Keeping open for auth v2 milestone round 2

**Comment by sw-yx** [comment]
I've received another request for amplify auth react hooks today from https://twitter.com/PipoPeperoni

**Comment by ajhool** [comment]
Not stale, please reopen

**Comment by ChihweiLHBird** [comment]
> I've received another request for amplify auth react hooks today from https://twitter.com/PipoPeperoni

Is there any plan for implementing it in Amplify framework?

**Comment by noobling** [comment]
.

Heres what im using in my application. Please make suggestions so we can come up with a better solution

```js
import { Auth, Hub } from 'aws-amplify';
import { useEffect } from 'react';
import { useRecoilState } from 'recoil';
import { currentUserState } from 'src/globalState';

export default () => {
  const [currentUser, setCurrentUser] = useRecoilState(currentUserState);
  useEffect(() => {
    async function getData() {
      setCurrentUser((prev) => ({ ...prev, authenticating: true }));
      let session;
      try {
        session = await Auth.currentSession();
      } catch (err) {
        console.info(err);
        return;
      }
      const groups = session.getAccessToken().payload['cognito:groups'] || [];
      const isAdmin = groups.includes('Admins');

      setCurrentUser({
        groups,
        loading: false,
        isAdmin,
        isAuthenticated: true,
      });
    }

    // Action
    Hub.listen('auth', getData);
    getData();

    // Cleanup
    return () => Hub.remove('auth', getData);
  }, []);

  return currentUser;
};

```

I am using https://recoiljs.org/ instead of react context because its more performant. Simply call this hook once somewhere at the top level. And reference the data with its recoil state.

**Comment by nielsboecker** [comment]
I've put together a simple custom hook based on the code from @all-iver :)

```typescript
import Auth from "@aws-amplify/auth";
import { Hub } from "@aws-amplify/core";
import { CognitoUser } from "amazon-cognito-identity-js";
import { useEffect, useState } from "react";

export interface UseAuthHookResponse {
  currentUser: CognitoUser | null;
}

const useAuth = (): UseAuthHookResponse => {
  const [currentUser, setCurrentUser] = useState<CognitoUser | null>(null);
  useEffect(() => {
    const updateUser = async () => {
      try {
        const user = await Auth.currentAuthenticatedUser();
        setCurrentUser(user);
      } catch {
        // currentAuthenticatedUser throws an Error if not signed in
        setCurrentUser(null);
      }
    };
    Hub.listen("auth", updateUser); // listen for login/signup events
    updateUser(); // check manually the first time because we won't get a Hub event
    return () => Hub.remove("auth", updateUser);
  }, []);

  return { currentUser };
};

export default useAuth;
```

**Comment by CR1AT0RS** [comment]
@nielsboecker How am I supposed to import this in App.js? I am trying this way but it doesn't seem to work:

App.js
```
export default function App() {
  const [authState, setAuthState] = React.useState();
  const [user, setUser] = React.useState();
  const signedIn = useAuth;

  useEffect(() => {
    console.log(signedIn);
    onAuthUIStateChange((nextAuthState, authData) => {
      setAuthState(nextAuthState);
      setUser(authData);
    });
  }, []);
```

Trying to import this in my components and see if a user is logged in. Since useAuth has "Hub" attached. All of components would know as soon as a user is logged out.

**Comment by nielsboecker** [comment]
@CR1AT0RS, my code snippet is using TypeScript. In TS, `useState` can receive generic parameters to specify which type the returned value of the state will be. In our case, it's first going to be `null`, and then it will be a `CognitoUser`. In other words, `<CognitoUser | null>`. If you want to use this in JavaScript, just remove the type information.

In order to consume this hook, you can just destructure `currentUser` and don't have to duplicate the low-level state handling in other components:

```typescript
  const { currentUser } = useAuth();
```

**Comment by MohittPattel** [comment]
hey I'm getting this error

Failed to compile.

./src/contexts/UserContext.js
Syntax error: C:/Users/Hp/Desktop/12may/client/src/contexts/UserContext.js: Unexpected token (61:19)

This is my cod

 return (
    <UserContext.Provider
      value={{
        state,
        isUserLoggedIn: state.isUserLoggedIn,
        uid: state?.user._id,
        dispatch,
      }}
    >
      {children}
    </UserContext.Provider>
  );

**Comment by bronislav** [comment]
@nielsboecker It seems that `useEffect` implicitly use `currentUser` as dependency and continuously looping. I had to specify empty array to prevent this behavior but not sure if this is a good approach.

**Comment by tyler-morales** [comment]
@nielsboecker When I try to use the useAuth() in a component and call current.username for example, after a page refresh, I get an error of `TypeError: currentUser is null`. I know I am signed in because I just signed in and in the local storage tab, my user's information is there. Do you have an idea why this error is occurring?

**Comment by nielsboecker** [comment]
@bronislav Not sure whether I understand your point. In my code snippet, I have already provided the empty array `[]` as dependency for the `useEffect` call?

@tyler-morales Hmm, I have an intuition. Are you using this in TypeScript or JavaScript? Note how the type of `currentUser` is `CognitoUser | null>`. That's because, for a brief moment, the variable will be `null`. Even if you refresh the page in an authenticated state, your React code may will run again and initially set the variabe to null:

```tsx
const [currentUser, setCurrentUser] = useState<CognitoUser | null>(null);
```

It's only after that that Amplify can kick in, parse the local storage and call the library callbacks that will eventually trigger the hook to see that the user is signed in. It is expected that `currentUser` is `null` for a little while, so your code should check whether it's `null` or not.

Hope that helped.

**Comment by tyler-morales** [comment]
I am using JavaScript. When I edited your code, this is what I got: 
````
// useAuth.js
import Auth from '@aws-amplify/auth'
import { Hub } from '@aws-amplify/core'
import { useHistory } from 'react-router-dom'
// import { CognitoUser } from 'amazon-cognito-identity-js'
import { useEffect, useState } from 'react'

const getCurrentUser = async () => {
  try {
    return await Auth.currentAuthenticatedUser()
  } catch {
    // currentAuthenticatedUser throws an Error if not signed in
    return null
  }
}

const useAuth = () => {
  let history = useHistory()

  const [currentUser, setCurrentUser] = useState(null)
  useEffect(() => {
    const updateUser = async () => {
      setCurrentUser(await getCurrentUser())
    }
    Hub.listen('auth', updateUser) // listen for login/signup events
    updateUser() // check manually the first time because we won't get a Hub event
    return () => Hub.remove('auth', updateUser)
  }, [])

  const signIn = () => Auth.federatedSignIn()

  const signOut = () => {
    Auth.signOut()
    history.push('/login')
  }

  return { currentUser, signIn, signOut }
}

export default useAuth

export { getCurrentUser }
````

In my Dashboard component:
````
import useAuth from '../hooks/useAuth'
export const Dashboard = () => {
  const { currentUser } = useAuth()
  console.log(currentUser.user)

return(
   <div>{currentUser.username}</div>
  )
}

````

Should the check for the null value occur in the useAuth hook or in each component?

**Comment by nielsboecker** [comment]
I see, thanks for providing the code :). So yeah you would want to perform the null check in your components that consume the hook. Because the `currentUser` returned will be either the user object, or `null`. 

```tsx
// Dashboard
return currentUser === null ? (
  <div>Loading...</div>
) : (
  <div>{currentUser.username}</div>
)
```

**Comment by srianbury** [comment]
This seems to be the solution (below), but it's not posted here and the implementation is not well advertised.  Check the [docs here](https://ui.docs.amplify.aws/components/authenticator).

Overview/Summary:
1. Wrap your app in the Authenticator Provider
```
import { Authenticator } from '@aws-amplify/ui-react';

export default () => (
  <Authenticator.Provider>
    <App />
  </Authenticator.Provider>
);
```

2. Get access to the user with useAuthenticator
```
import { useAuthenticator } from '@aws-amplify/ui-react';

const App = () => {
  const { user, signOut } = useAuthenticator((context) => [context.user]);
  // ...
};
```

**Comment by palyvodaBoi** [comment]
@srianbury `user = undefined` when the page refreshed

**Comment by arisingco** [comment]
I am struggling with this very thing. I checked the docs and found this in a 2021 blog (https://aws.amazon.com/blogs/mobile/amplify-uis-new-authenticator-component-makes-it-easy-to-add-customizable-login-pages-to-your-react-angular-or-vue-app/)
(to be more specific, its in the sample: https://codesandbox.io/s/change-your-layout-rh4z9?file=/src/App.js): 

```
import { useAuthenticator} from "@aws-amplify/ui-react";
import { Amplify } from "aws-amplify";

import { Home } from "../components/Home";
import { Login } from "../components/Login";
import '@aws-amplify/ui-react/styles.css';
import awsExports from "../aws-exports";
Amplify.configure(awsExports);

export default function App() {
const { user } = useAuthenticator();

if (user) {
return <Home />;
}

return <Login />;
}
```
But when I test this out, I get a **_TypeError: Cannot read properties of undefined (reading 'send')_** in useAuthenticator()
Anyone have any idea how I can fix this? Simply want to detect if user is logged in and if so, show them their dashboard instead of the home screen.

**Comment by srianbury** [comment]
@palyvodaBoi I added an update to my answer.  I've been using this implementation and it's been working for me.

**Comment by samscarsella** [comment]
I'm running up against this as well. I've tried checking for `route === authenticated` and for the truthiness of `user`, but the results are unpredictable. My verified user's state is sometimes 'signIn', sometimes 'setup' and sometimes 'authenticated' after signing in successfully. The useAuthenticator's context doesn't seem to get updated in my other components that use it either. Has there been an update that broke this?

**Comment by joshbedo** [comment]
Anyone have a fix for this using currentUser in useAuth creates a page flash/loop if you're trying to check the users before displaying a route

**Comment by joshbedo** [comment]
I did these together to stop the page from flashing or looping between redirect.

useAuth.js
```
etCurrentUser = async () => {
    try {
        return await Auth.currentAuthenticatedUser();
    }
    catch (_a) {
        // currentAuthenticatedUser throws an Error if not signed in
        return null;
    }
};
const useAuth = () => {
    const [currentUser, setCurrentUser] = useState(null);
    const [loading, setLoading] = useState(true);
    useEffect(() => {
        const updateUser = async () => {
            setCurrentUser(await getCurrentUser());
            setLoading(false);
        };
        Hub.listen("auth", updateUser); // listen for login/signup events
        updateUser(); // check manually the first time because we won't get a Hub event
        return () => Hub.remove("auth", updateUser);
    }, []);
    const signIn = () => Auth.federatedSignIn();
    const signOut = () => Auth.signOut();
    return { currentUser, signIn, signOut, loading };
};

export default useAuth;
export { getCurrentUser };
```

```
function RequireAuth({ children }) {
  const { currentUser, signOut, loading } = useAuth();

  if (!loading && currentUser === null) {
    return <Navigate to="/login" replace />;
  } else {
    return children;
  }
}
```
