### ISSUE TITLE
How to make API request send Cognito user data?

### ISSUE THREAD

**Issue by ilyador** [aws-amplify/amplify-js#3644]
I want to authenticate a user can access certain records in the Dyanamodb, and for some reason the API request sends no user data:

```
"identity": {
  "cognitoIdentityPoolId": null,
    "accountId": null,
    "cognitoIdentityId": null,
    "caller": null,
    "sourceIp": ".....................",
    "principalOrgId": null,
    "accessKey": null,
    "cognitoAuthenticationType": null,
    "cognitoAuthenticationProvider": null,
    "userArn": null,
    "userAgent": ".....................",
    "user": null
}
```

Also, there is a default variable created on the lambda function called `userIdPresent` and is simply set to `false`. I'm not sure if it is related.

Am I doing the authentication correctly?

**Comment by haverchuck** [comment]
@ilyador How are you authenticating the user in your application?

**Comment by ilyador** [comment]
With Cognito user pool.
