### ISSUE TITLE
OAuth authenticate code is lost from the redirect url for Android

### ISSUE THREAD

**Issue by alexyurepercept** [aws-amplify/amplify-js#3647]
**Describe the bug**
When using the hosted cognito UI to perform the federated signin, the authenticate code is lost from the redirect url when opening the App. This only happens to Android platform due to the following code:
https://github.com/aws-amplify/amplify-js/blob/1f2ea54d5ff6d53ccb75dfdd147fab3ab61bae44/packages/auth/src/urlListener.native.ts#L42-L52

The above code caused the authentication flow to stuck at "parsingCallbackUrl". As in stead of returning the url=exp://xxx.xx.xx.xx:19000?code=authentication_code&state=state, it returns url=exp://xxx.xx.xx.xx:19000

**To Reproduce** 
1. Call Auth.federatedSignIn({ provider });
2. Sign in to social account
3. Redirect back to the mobile app
4. App stuck at "parsingCallbackUrl"

**Expected behavior**
Authentication should proceed to use the authentication code to get the access token

**Smartphone (please complete the following information):**
 - Device: MHA-L09
 - OS: Android 8.0.0
 - Browser: Chrome
 - Version: 74.0.3729.157

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

[DEBUG] 58:29.626 urlListener - addEventListener Object {
  "url": "exp://192.168.1.185:19000",
}
[DEBUG] 58:29.627 Hub - Dispatching to auth with  Object {
  "data": Object {
    "url": "exp://192.168.1.185:19000",
  },
  "event": "parsingCallbackUrl",
  "message": "The callback url is being parsed",
}
[DEBUG] 58:29.627 Analytics - on hub capsule auth Object {
  "data": Object {
    "url": "exp://192.168.1.185:19000",
  },
  "event": "parsingCallbackUrl",
  "message": "The callback url is being parsed",
}
[DEBUG] 58:29.627 Hub - Dispatching to auth with  Object {
  "data": Object {
    "url": "exp://192.168.1.185:19000",
  },
  "event": "parsingCallbackUrl",
  "message": "The callback url is being parsed",
}

**Comment by haverchuck** [comment]
@alexyurepercept Which version of aws-amplify are you using?

**Comment by alexyurepercept** [comment]
@haverchuck I was using aws-amplify@1.1.31-unstable.5

**Comment by alexyurepercept** [comment]
Any update on this issue? @haverchuck

**Comment by martinvillaf** [comment]
Facing same issue here.
Is there a workaround?

**Comment by martinvillaf** [comment]
i just found out that this was fixed with this commit:
https://github.com/aws-amplify/amplify-js/commit/799a1cfe59f7244f1cc51bdc0220a6c4ebf81455
which is available on version 1.1.31-unstable.19

**Comment by haverchuck** [comment]
@alexyurepercept As noted by @martinvillaf , I believe this issue should be resolved now.  Please install a current version of Amplify.  If you are still experiencing the issue, please repost but specify the new version of Amplify that you have installed.
