### ISSUE TITLE
Atomic Transactions

### ISSUE THREAD

**Issue by gkpty** [aws-amplify/amplify-js#3649]
**Is your feature request related to a problem? Please describe.**
I need to implement atomic transactions in my application. I have a table that stores payments and another table with reservations which have a balance field. Sometimes payments go through but the balance on the reservation fails to update because of a network error or for whatever other reason.

**Describe the solution you'd like**
Would be helpful to be able to run transactions directly from graphQL. A graphQL transaction could include various graphQL mutations and would reverse the other mutations if one fails.

**Describe alternatives you've considered**
Ive seen theres a transactWriteItems operation for the DynamoDB SDK, wondering if this could be implemented into AppSync or directly into the graphQL API somehow...

**Additional context**
As a temporary solution im thinking of deploying a lambda function with a REST API that will execute the transactWriteItem operation; however this is definitely not the most convenient..

**Comment by haverchuck** [comment]
@gkpty This is an interesting request - I think you would probably have more luck posting it to the [AppSync forums](https://forums.aws.amazon.com/forum.jspa?forumID=280), where it can be seen by the AppSync service team.
