### ISSUE TITLE
[Auth] Sub: "undefined"

### ISSUE THREAD

**Issue by kalzoo** [aws-amplify/amplify-js#3651]
**Describe the bug**
multiple `Auth` methods return a `sub` value of `'undefined'` (yes, a string value) without any errors

**To Reproduce**

```

const user = await Auth.signIn(username, password).catch(err =>
        console.error('error in signin:', err)
      );
      console.log('User Signed In:', user);

```
prints this value to console as `user`. There is no error.

```
{ 
  signInUserSession: { 
    idToken: {
     payload: {
        sub: "undefined" 
      }
   }
}
```

This happens both with usernames known to be in the user pool and those known not to be.

`Auth.currentAuthenticatedUser()` shows similar behavior, returning that same object.

**Expected behavior**
It should work, returning the actual `sub` value or throwing an error if something went wrong.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] OSX
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] latest

**Comment by haverchuck** [comment]
@kalzoo - I was unable to reproduce this behavior.  For me, the value is being returned correctly.  Can you share any details about how you have configured auth in your application?

**Comment by kalzoo** [comment]
@haverchuck, thanks for the quick response! While building a simple repro I discovered this was actually an artifact of a utility that added offline auth by overriding Amplify methods, and a mistake in my webpack variable injection was causing it to inject `undefined` when not being used offline. Hopefully this helps someone else down the road. Good to go!
