### ISSUE TITLE
React Native: "AMQJS0007E Socket error:undefined."

### ISSUE THREAD

**Issue by vishalavalani** [aws-amplify/amplify-js#3653]
**Describe the bug**
I am using AWS Amplify to connect to AWS IoT Core and getting error "AMQJS0007E Socket error:undefined." I have integrated aws amplify in expo app.

**Sample code**
```
import React from "react";
import { StyleSheet, Text, View } from "react-native";
import Amplify, { PubSub, Auth } from "aws-amplify";
import { AWSIoTProvider } from "@aws-amplify/pubsub/lib/Providers";

Amplify.configure({
  Auth: {
    identityPoolId: "ap-south-1:xx-xx-xx-xx-xx",
    region: "AP_SOUTH_1",
    userPoolId: "ap-south-1_xx",
    userPoolWebClientId: "xxx"
  }
});
Amplify.addPluggable(
  new AWSIoTProvider({
    aws_pubsub_region: "ap-south-1",
    aws_pubsub_endpoint: "wss://xx.iot.ap-south-1.amazonaws.com/mqtt"
  })
);
class App extends React.Component {
  async componentDidMount() {
    Auth.configure();
    const sub1 = PubSub.subscribe("$aws/things/xxx/shadow/update").subscribe({
      next: data => console.log("Message received", data),
      error: error => console.error(error),
      close: () => console.log("Done")
    });
  }
  render() {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center"
  }
});

export default App;
```

**Error details**

- errorCode: 7
- errorMessage: "AMQJS0007E Socket error:undefined."
- invocationContext: undefined

**Comment by haverchuck** [comment]
@vishalavalani - Can you try adding the following policies to your auth IAM role?

`AWSIoTDataAccess` and `AWSIoTConfigAccess`

This is mentioned in our documentation, but we are currently working to make it more clear.

**Comment by vishalavalani** [comment]
Policies were already in place. Still get same error. With the same configuration it works in Native iOS App but doesn't work with Amplify JS.

**Comment by jordanranz** [comment]
Can you try removing `Auth.configure();`. 
```
Amplify.configure({
  Auth: {
    identityPoolId: "ap-south-1:xx-xx-xx-xx-xx",
    region: "AP_SOUTH_1",
    userPoolId: "ap-south-1_xx",
    userPoolWebClientId: "xxx"
  }
});
```
Should handle Auth configuration.

**Comment by vaibhavtupe** [comment]
@vishalavalani did you get any solution/fix on this?

**Comment by benariamir** [comment]
We (@cayce) are running into the same issue.
The AWS IoT CloudWatch logs are showing this:
{
    "timestamp": "2019-08-05 14:00:01.688",
    "logLevel": "ERROR",
    "traceId": "4f37a2d5-0d10-6ad6-239c-91f247358152",
    "accountId": "771585994482",
    "status": "Failure",
    "eventType": "Connect",
    "protocol": "MQTT",
    "clientId": "856e9f8b-cac6-42c4-988d-d837339e6a4e",
    "principalId": "AROA3HJQ353ZD67RJBGBT:CognitoIdentityCredentials",
    "sourceIp": "62.219.214.242",
    "sourcePort": 25160,
    "reason": "AUTHORIZATION_FAILURE",
    "details": "Authorization Failure"
}

We've also done the following:
We coded a small NodeJS app that uses aws-iot-device-sdk:

```
var awsIot = require('aws-iot-device-sdk');
let device = awsIot.device({
    clientId: '<MQTT client Id from Amplify debug log>',
    host: '<endpoint>.iot.us-east-1.amazonaws.com',
    protocol: 'wss',
    accessKeyId: '< The access key Id provided by Cognito from Auth.currentCredentials()>',
    secretKey: '<The secret key provided by Cognito from Auth.currentCredentials()>',
    sessionToken: '<The session token provided by Cognito from Auth.currentCredentials()>'
});
device.on('connect', () => {
    console.log('connected');
});
device.on('error', (e) => {
   console.log(e);
});
device.on('close', () => {
    console.log('closed');
});
device.on('reconnect', () => {
   console.log('reconnected');
});
device.on('offline', () => {
    console.log('offline');
})
```

We got the following output:
offline
closed
reconnected
closed
reconnected
closed
reconnected
closed
reconnected
closed
reconnected
closed
reconnected
closed
reconnected
closed
reconnected
closed

And saw the same error in the CloudWatch logs.

If we ran our small test app with my Admin credentials -> it was connected and publishing.

**Comment by Cayce** [comment]
Want to add to @benariamir comment above, that we do have those policies in our authenticated role in identity pool:
AWSIoTDataAccess and AWSIoTConfigAccess
Also, we attached this pool id to IOT Policy as Certificate.

**Comment by vishalavalani** [comment]
I have created custom module in native and have decided to go against library. It gives me much more control to tweak as per custom requirement.

**Comment by Cayce** [comment]
Attaching identity Id from the identity pool that needs to be connected to the iot policy as principal/certificate solved the problem. Actually, this is what DOCS says:
https://aws-amplify.github.io/docs/js/pubsub
Wrongly understood that it should be the identity pool id and not identity id.

**Comment by naseemrafique** [comment]
@Cayce How did you attach identity id for each logged in user?

**Comment by tejas1106** [comment]
Attach Identity pool Id of user to the AWS IOT policy.

**Comment by tejas1106** [comment]
@naseemrafique  use AWS IOT console for that:
1. Set up AWS IOT console using **aws configure**
2. **aws iot attach-principal-policy --policy-name myIoTPolicy --principal USER COGNITO IDENTITY POOL ID**

**Comment by Cayce** [comment]
@naseemrafique 
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Iot.html#attachPrincipalPolicy-property
With aws SDK, by calling this method for each user that logins, server-side.

**Comment by githubflub** [comment]
Another possible cause of this issue, especially when you've done everything else right, is having multiple versions of @aws-amplify/core in node_modules. So, you think you set everything up perfectly, but then internally the code uses a different version of Amplify that didn't get set up, and you get a seemingly unexplainable error. 

You can try to fix this by deleting package-lock.json and node_modules and doing npm install again. More on my experience with this issue here. https://github.com/aws-amplify/amplify-js/issues/6244

**Comment by andyautida14** [comment]
I had the same problem, but I solved mine by using 'iot:Data-ATS' endpoint type instead of 'iot:Data'. Basically, use 'wss://xx-ats.iot.ap-south-1.amazonaws.com/mqtt' (notice the added '-ats') for your aws_pubsub_endpoint.

**Comment by dotnexttech** [comment]
> I had the same problem, but I solved mine by using 'iot:Data-ATS' endpoint type instead of 'iot:Data'. Basically, use 'wss://xx-ats.iot.ap-south-1.amazonaws.com/mqtt' (notice the added '-ats') for your aws_pubsub_endpoint.

can you describe your solution more?

**Comment by jwoehrle** [comment]
> can you describe your solution more? it:Data-ATS is not clear

@dotnexttech 
The -ats endpoints use a different certificate (signed by a different CA). This was done because the old CA (Symantec root CA) is not trusted anymore by many clients.
See [How AWS IoT Core is Helping Customers Navigate the Upcoming Distrust of Symantec Certificate Authorities](https://aws.amazon.com/blogs/iot/aws-iot-core-ats-endpoints/) for details.
