### ISSUE TITLE
Amplify React-Native "Parameter 'url' must be a string, not object" with federated sign in

### ISSUE THREAD

**Issue by rnnyrk** [aws-amplify/amplify-js#3657]
**Describe the bug**
Can't build app after using connection Facebook via `amplify add auth`.

**To Reproduce**
1. Follow the installation docs as on: https://aws-amplify.github.io/docs/js/start?ref=amplify-rn-btn&platform=react-native
2. Run `amplify init` and `amplify add auth` (Facebook)
3. Build the project

**Expected behavior**
Project builds and can use without errors.

**Screenshots**
<img width="784" alt="Screenshot 2019-07-15 at 17 21 37" src="https://user-images.githubusercontent.com/4519142/61227681-0cafff00-a725-11e9-9265-272244029cd6.png">

**Smartphone (please complete the following information):**
 - Tried on iPhone Xr and X simulator. Latest stable OS and Xcode

**Additional context**
Can't seem to find anything on the internet related to this issue except from this issue: https://github.com/aws-amplify/amplify-js/issues/3342 

But this isn't solved and the solution in there doesn't work for me. This made my stuck on implementing AWS amplify now for days already.

**Comment by haverchuck** [comment]
@rnnyrk -  Which versions of aws-amplify are you using?  Could you try 'npm i aws-amplify@latest`?  

We merged a bug fix last friday which I believe addresses this.

**Comment by rnnyrk** [comment]
@haverchuck Yes, I'm facing this issue with the latest version `"aws-amplify": "1.1.30",` installed.

**Comment by haverchuck** [comment]
@rnnyrk Ok, apologies -it looks like we haven't merged this fix into our primary branch.  You could give version 1.1.31-unstable.5 until we are able to do so.  I believe this should unblock you.

**Comment by rnnyrk** [comment]
This indeed seems to work. Thanks for your quick reply. Should have asked it earlier instead of trying to figure it out for 2 days haha. Any idea how I can get updated as soon this gets stable?

**Comment by haverchuck** [comment]
@rnnyrk In Github, you can try using Watch -> Releases Only in the amplify-js repo.  I've never used this feature myself, but I think that's what it is for.
