### ISSUE TITLE
Does amplify vue Authentication Components support Authorization Code Flow with PKCE?

### ISSUE THREAD

**Issue by hanslai** [aws-amplify/amplify-js#3659]
I would like to use Authorization Code Flow with PKCE for our SPA (Vue) and Mobile APP. 

but it seems to me that the **Amplify Vue SignIn component** use SRP to login the user and get the tokens?  Is this less secure then use "Hosted UI" by Cognito which follow the Open ID Connect standard?

So, **does amplify vue Authentication Components support Authorization Code Flow with PKCE?**
or should I just use the **Amplify Authentication api** https://aws-amplify.github.io/docs/js/authentication#working-with-the-api if I want to follow the Open ID Connect standard?

 **Which Category is your question related to?** 
amplify vue component with Authorization Code Flow with PKCE support

**What AWS Services are you utilizing?** 
Cognito User Pool

**Comment by juancpgo** [comment]
> I would like to use Authorization Code Flow with PKCE for our SPA (Vue) and Mobile APP.
> 
> but it seems to me that the **Amplify Vue SignIn component** use SRP to login the user and get the tokens? Is this less secure then use "Hosted UI" by Cognito which follow the Open ID Connect standard?
> 
> So, **does amplify vue Authentication Components support Authorization Code Flow with PKCE?**
> or should I just use the **Amplify Authentication api** https://aws-amplify.github.io/docs/js/authentication#working-with-the-api if I want to follow the Open ID Connect standard?
> 
> **Which Category is your question related to?**
> amplify vue component with Authorization Code Flow with PKCE support
> 
> **What AWS Services are you utilizing?**
> Cognito User Pool

I'm currently facing the same dilemma. If you don't mind sharing, how did you end up deciding between SRP and PKCE, in terms of security and Amplify support?
