### ISSUE TITLE
Counting records

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-js#3664]
** Which Category is your question related to? **
API - AWS AMPLIFY

** What AWS Services are you utilizing? **
DynamoDB

I have read through the docs many times and can't see anywhere how we can return a count of all the records that match a filter for records in the API.

How do I simply return a count of records within one of my tables using the API?

**Comment by haverchuck** [comment]
@oliverandersencox - Are you using a REST API or AppSync?

**Comment by oliverandersencox** [comment]
Im using the app sync

**Comment by oliverandersencox** [comment]
@haverchuck would I be able to write custom resolver that adds 1 to a field in an aggregation table for this?

**Comment by haverchuck** [comment]
@oliverandersencox - I don't think you would need a custom resolver... you could utilize DynamoDB streams to perform real time aggregation when events occur in the database.  [This article](https://medium.com/signiant-engineering/real-time-aggregation-with-dynamodb-streams-f93547cfb244) might be a good place to start.
