### ISSUE TITLE
Need to npm install aws-amplify --save repeatedly

### ISSUE THREAD

**Issue by evanlarkin10** [aws-amplify/amplify-js#3668]
** Which Category is your question related to? **
Installation/Usage

** What AWS Services are you utilizing? **
Auth, API

** Provide additional details e.g. code snippets **

Any idea why I get the error `Cannot find module 'aws-amplify'` in src/App.tsx consistently. I run npm install, then npm start and my project compiles fine. Every few hot loads or on another npm start it throws the error again not finding aws-amplify.

**Comment by haverchuck** [comment]
Hi @evanlarkin10  - What did you use to spin up the project?  Did you use a tool like create-react-app?  Would you mind posting your package.json?

**Comment by evanlarkin10** [comment]
Hi @haverchuck ,
Here is the package.json. I used create-react-app and typescript with some modifications, react-app-rewired mainly for hot reloading. I also included the config-overrides.js which I used to set it up.  
`{
  "name": "react-boilerplate",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@hot-loader/react-dom": "^16.7.0",
    "@types/react-grid-layout": "^0.16.7",
    "@types/redux-saga": "^0.10.5",
    "aws-amplify-react": "^2.3.9",
    "babel-loader": "^8.0.6",
    "babel-plugin-emotion": "^10.0.14",
    "classnames": "^2.2.6",
    "clsx": "^1.0.4",
    "history": "^4.9.0",
    "i18next": "^17.0.4",
    "i18next-xhr-backend": "^3.0.0",
    "immutable": "^3.8.2",
    "js-cookie": "^2.2.0",
    "lodash": "^4.17.14",
    "moment": "^2.24.0",
    "querystring": "^0.2.0",
    "randomcolor": "^0.5.3",
    "react": "^16.8.0",
    "react-app-rewire-hot-loader": "^2.0.1",
    "react-app-rewired": "1.6.2",
    "react-dom": "^16.8.0",
    "react-grid-layout": "^0.16.6",
    "react-hot-loader": "^4.11.1",
    "react-i18next": "8.1.2",
    "react-mobx": "0.0.3",
    "react-redux": "^5.1.1",
    "react-router-dom": "^4.3.1",
    "react-scripts-ts": "2.16.0",
    "recharts": "^1.4.2",
    "redux": "^4.0.1",
    "redux-auth-wrapper": "^2.0.3",
    "redux-devtools-extension": "^2.13.7",
    "redux-form": "^8.2.4",
    "redux-rest-resource": "^0.18.0",
    "redux-saga": "^1.0.5",
    "redux-thunk": "^2.3.0",
    "requirejs": "^2.3.6",
    "reselect": "^3.0.1",
    "typescript-fsa": "^3.0.0-beta-2",
    "typescript-fsa-reducers": "^1.2.1"
  },
  "scripts": {
    "start": "react-app-rewired start --scripts-version react-scripts-ts",
    "build": "react-scripts-ts build",
    "test": "react-scripts-ts test",
    "eject": "react-scripts-ts eject"
  },
  "devDependencies": {
    "@material-ui/core": "^4.0.0",
    "@material-ui/icons": "^3.0.1",
    "@types/classnames": "2.2.6",
    "@types/history": "4.7.0",
    "@types/i18n": "0.8.3",
    "@types/i18next": "11.9.2",
    "@types/i18next-xhr-backend": "1.4.1",
    "@types/immutable": "^3.8.7",
    "@types/jest": "23.3.1",
    "@types/js-cookie": "2.2.0",
    "@types/lodash": "4.14.116",
    "@types/moment": "2.13.0",
    "@types/node": "^12.0.10",
    "@types/react": "16.4.12",
    "@types/react-big-calendar": "0.20.1",
    "@types/react-dnd": "3.0.2",
    "@types/react-dom": "16.0.7",
    "@types/react-i18next": "8.1.0",
    "@types/react-redux": "^6.0.13",
    "@types/react-router-dom": "^4.3.1",
    "@types/react-select": "2.0.4",
    "@types/react-virtualized": "9.18.7",
    "@types/recharts": "^1.1.6",
    "@types/redux": "^3.6.31",
    "@types/redux-auth-wrapper": "^2.0.9",
    "@types/redux-devtools-extension": "^2.13.2",
    "@types/redux-form": "7.4.6",
    "@types/redux-thunk": "^2.1.32",
    "@types/reselect": "^2.2.0",
    "@types/webpack-env": "1.13.6",
    "aws-amplify": "^1.1.32",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "tslint": "5.11.0",
    "tslint-config-airbnb": "5.10.0",
    "tslint-config-prettier": "1.15.0",
    "tslint-webpack-plugin": "1.2.2",
    "typescript": "3.5.2"
  },
  "babel": {
    "plugins": [
      "transform-decorators-legacy"
    ],
    "presets": [
      "react-app"
    ]
  }
}`

Config Overrides

`const rewireReactHotLoader = require('react-app-rewire-hot-loader');

const resolve = require("path").resolve;
const {
  injectBabelPlugin,
  getBabelLoader,
  getLoader,
  loaderNameMatches
} = require("react-app-rewired");

module.exports = function override(config, env) {

  const removeLoader = (rules, loader) => {
    const LoaderMatcher = function(rule) {
      return loaderNameMatches(rule, loader);
    };
    let loaderObj = getLoader(rules, LoaderMatcher)

    const removeLoaderRecursive = (rules) => {
      rules.forEach((rule,index) => {
        if(rule.loader){
          if(loaderObj.loader == rule.loader){
            rules.splice(index,1)
          }
        }else if(rule.use){
          removeLoaderRecursive(rule.use)
        }else if(rule.oneOf){
          removeLoaderRecursive(rule.oneOf)
        }
      })
    };

    removeLoaderRecursive(rules)
  }

  //remove default ts-loader
  removeLoader(config.module.rules, "ts-loader");

  // Emotion babel plugin
  config = injectBabelPlugin(
    [
      "emotion",
      {
        autoLabel: true,
        sourceMap: true
      }
    ],
    config
  );

  //Get babelLoader and modify to use on all filetypes and run ts-loader afterwards.
  let babelLoader = getBabelLoader(config.module.rules);
  babelLoader.test = /\.(js|jsx|mjs|ts|tsx)$/;
  babelLoader.use = [
    {
      loader: babelLoader.loader,
      options: babelLoader.options
    },
    {
      loader: require.resolve("ts-loader"),
      options: {
        // disable type checker - we will use it in fork plugin
        transpileOnly: true
      }
    }
  ];
  delete babelLoader.loader;
  delete babelLoader.options;

  if (env === 'development') {
    config.resolve.alias['react-dom'] = '@hot-loader/react-dom';
  }
  config = rewireReactHotLoader(config, env);
  return config;
};`

**Comment by haverchuck** [comment]
@evanlarkin10  - Why is aws-ampliy a devDependency instead of a dependency?

**Comment by evanlarkin10** [comment]
@haverchuck Oh right, moved it in an effort to try everything to get it fixed. It's a dependency now and still causing the same issue.
