### ISSUE TITLE
Unused variable in amplify-js

### ISSUE THREAD

**Issue by Gringox** [aws-amplify/amplify-js#3669]
** Which Category is your question related to? **

amazon-cognito-identity-js

** What AWS Services are you utilizing? **

Cognito

** Provide additional details e.g. code snippets **

Hi team,

In the code for [amazon-cognito-identity-js](https://github.com/aws-amplify/amplify-js/blob/master/packages/amazon-cognito-identity-js/src/Client.js#L10) there is a line that specifies the following:

```
this.endpoint = endpoint || `https://cognito-idp.${region}.amazonaws.com/`;
```

This implies that the endpoint can be something else, however according to the [documentation of the library](https://github.com/aws-amplify/amplify-js/tree/master/packages/amazon-cognito-identity-js#network-configuration):

```
The Amazon Cognito Identity JavaScript SDK will make requests to the following endpoints

For Amazon Cognito User Pool service request handling: "https://cognito-idp.us-east-1.amazonaws.com"
This endpoint may change based on which region your Cognito User Pool was created in.
For most frameworks you can whitelist the domain by whitelisting all AWS endpoints with "*.amazonaws.com".
```

The above suggests that the only endpoint would be `https://cognito-idp.<REGION>.amazonaws.com`.

Speaking from an ignorant/uninformed point of view, is this "endpoint" parameter being used for something? If so, is it documented somewhere? What are the possible values?

Best regards!

**Comment by haverchuck** [comment]
@Gringox -  This variable can be used to register a custom endpoint like so:
```
const userPool = new AmazonCognitoIdentity.CognitoUserPool({
    UserPoolId: myUserPool
    ClientId: myClient
    endpoint: 'https://cognito.mysite.com'
})
```
The custom endpoint can then redirect to the default cognito enpdoint.  I do not believe the Amplify framework uses this functionality, but others who are using the aws-sdk and cognito-identity sdk may be using it in this fashion.
