### ISSUE TITLE
Signing in on a public computer? 

### ISSUE THREAD

**Issue by msurguy** [aws-amplify/amplify-js#3670]
** Which Category is your question related to? **
Amplify Auth

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
Hi! 

We'd like to use Amplify Auth but with a slight departure from your default examples outlined in https://aws-amplify.github.io/docs/js/authentication#manual-setup and https://aws-amplify.github.io/docs/js/authentication#sign-in. 

We'd like to provide an option fo the user to "Remember me" and also a single-session option where if the browser window is closed, they would not be signed in if the site is visited again. We have a hard time finding a way to do the latter and would like more details about how to implement such functionality. Thank you!

**Comment by haverchuck** [comment]
@msurguy - I don't think we have the ability OOTB to sign someone out when a browser window closes, but have you read about[ device tracking](https://aws.amazon.com/blogs/mobile/tracking-and-remembering-devices-using-amazon-cognito-your-user-pools/)?

**Comment by craigtsmith** [comment]
@msurguy I'm exploring this at the moment and, if I think you can do something like this just before you initiate auth sign in:

```javascript
Auth.configure( { storage: rememberMe ? localStorage : sessionStorage })
```

Where `rememberMe` is some boolean input from your user

**Comment by tannerabread** [comment]
Hi @msurguy the library now allows the ability to customize where the tokens are stored https://docs.amplify.aws/lib/auth/manageusers/q/platform/js/#managing-security-tokens

I think this plus a combination of some frontend work like @craigtsmith suggested would be a viable solution for this.

Are you still looking for this functionality or a solution for this issue?
