### ISSUE TITLE
amazon-cognito-identity-js + proxy

### ISSUE THREAD

**Issue by tarinitorpe** [aws-amplify/amplify-js#3674]
I need to use the amazon-cognito-identity-js module on server side (nodeJS) to manage userpools behind a proxy. I searched a lot about this, but I can't figured out how can I do this, how can I configure it to using http/https proxies for authenticating and other userpool operations. Please give me a hint! 
thx

**Comment by sammartinez** [comment]
@tarinitorpe We currently don't officially support nodeJS for this library. Please open up a forum question in regards to this on [Cognito AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=173).
