### ISSUE TITLE
Invalid login token. Token expired: 1563259261 >= 1563256680

### ISSUE THREAD

**Issue by ParshantAroras** [aws-amplify/amplify-js#3675]
**Describe the bug**
Invalid login token. Token expired: 1563259261 >= 1563256680 getting this error when i left the app for some time 

We have integrated the chatbot using the aws-amplify package with react-native. Every thing goes smooth if we left the app for sometime and then again hit the bot (Interaction.send() ) then 
Invalid login token. Token expired: 1563259261 >= 1563256680"}
this error come. I have done a-lot of Research and Development but no solution works 
This is the session timeout Please help us how we can increase the timeout or give some method to refresh the token before hitting the bot

**Comment by haverchuck** [comment]
@ParshantAroras -  The Interactions.send() function should ultimately call [this line of code](https://github.com/aws-amplify/amplify-js/blob/d8b42397906ad87e125f9480240b1c9049717365/packages/interactions/src/Providers/AWSLexProvider.ts#L73), which should result in expired tokens being refreshed.   Could you try opening the debugger and seeing if this line is getting called?

**Comment by ParshantArora** [comment]
Yes sure @haverchuk I will check it by tommorow morning and let you know Thanks for your response appreciated

**Comment by ParshantAroras** [comment]
Hi @haverchuck 
path : aws-sdk/lib/cognitoIdentityCredentials.js

  /**
   * @api private
   */
  getCredentialsForIdentity: function getCredentialsForIdentity(callback) {
    var self = this;
    self.cognito.getCredentialsForIdentity(function(err, data) {
      console.log("datadatadatadata",err, data)
      if (!err) {
        self.cacheId(data);
        self.data = data;
        self.loadCredentials(self.data, self);
      } else {
 self.clearIdOnNotAuthorized(err);
      }
      callback(err);
    });
  },
this is the aws-sdk function which causes
Errror  Invalid login token. Token expired: 1563259261 >= 1563256680 

and this method self.cognito.getCredentialsForIdentity
is calling api which gives the error 
are in clients/cognitoIdentity.js

 getCredentialsForIdentity(params: CognitoIdentity.Types.GetCredentialsForIdentityInput, callback?: (err: AWSError, data: CognitoIdentity.Types.GetCredentialsForIdentityResponse) => void): Request<CognitoIdentity.Types.GetCredentialsForIdentityResponse, AWSError>;
  /**
   * Returns credentials for the provided identity ID. Any provided logins will be validated against supported login providers. If the token is for cognito-identity.amazonaws.com, it will be passed through to AWS Security Token Service with the appropriate role for the token. This is a public API. You do not need any credentials to call this API.
   */
  getCredentialsForIdentity(callback?: (err: AWSError, data: CognitoIdentity.Types.GetCredentialsForIdentityResponse) => void): Request<CognitoIdentity.Types.GetCredentialsForIdentityResponse, AWSError>;
  /**
   * Generates (or retrieves) a Cognito ID. Supplying multiple logins will create an implicit linked account. This is a public API. You do not need any credentials to call this API.
   */ 

these are the api which gives the error

**Comment by haverchuck** [comment]
@ParshantArora - In the entry point of your application, can you do:
import AWS from 'aws-sdk'
...and then, after you call Amplify.configure, do
AWS.config.correctClockSkew = true?

Please respond with whether or not that has any effect.

**Comment by ParshantAroras** [comment]
Solved that issue just we have set the new Login Token inside the Aws library

**Comment by haverchuck** [comment]
@ParshantAroras   I'm sorry - did the clockSkew configuration solve the issue or did you have some sort of other fix?

**Comment by EnanlyPay** [comment]
> @ParshantAroras I'm sorry - did the clockSkew configuration solve the issue or did you have some sort of other fix?

Hi @haverchuck your solution is not working with aws-appsync, can you please help me out with that ?

**Comment by ParshantAroras** [comment]
After 1 hour the login token is expired then refresh token wont work at that time. What you have to do is to generate new Login token and then you need to reset the login token inside the aws-sdk library . It works for me
