### ISSUE TITLE
http timeout configuration?

### ISSUE THREAD

**Issue by ryaa** [aws-amplify/amplify-js#368]
Do you want to request a feature or report a bug?
>>
I have a question.
Is it possible to configure http timeout for the lib.
Smth like httpOptions: {timeout: 500}?

**Comment by mlabieniec** [comment]
@ryaa do you mean for the API calls or S3 / Storage ?

**Comment by ryaa** [comment]
API calls.. For example for Auth.signIn method call

**Comment by JohnnyMinty** [comment]
+1 for this issue - looking at the source code i can't see a way to add or set the TIMEOUT.

**Comment by JohnnyMinty** [comment]
> +1 for this task- looking at the source code i can't see a way to add or set the TIMEOUT.

For feference to anyone looking to set the timeout or any other configuration option prior to sending a request- use an AXIOS request interceptor: 

import axios from "axios";

axios.interceptors.request.use((config) => {
   config.timeout = 5000;
});

**Comment by clem91** [comment]
Hi,

Any update on this?
I don't find any information in the docs =/

**Comment by PunkHaz4rd** [comment]
Any news on that ?

**Comment by PunkHaz4rd** [comment]
Bump

**Comment by luisvsm** [comment]
I've attempted to add timeout support for API calls, eg API.[get/post/put/patch/del/head]. 

Usage is like so:
```
let params = {
   timeout: 2500 // OPTIONAL
};
API.get('apiName', '/path', params);
```

It sounds like some people here also wanted a timeout option for the Auth library, but that's a bit beyond my current understanding of Amplify and beyond my use case so someone else more appropriate should tackle that.

Cheers

**Comment by luisvsm** [comment]
In case the feature is rejected, or if you need a solution right now you can also set a timeout by changing the default timeout of axios.

`
// Put this code somewhere in your codebase to change Axios' default timeout
const axios = require('axios');
axios.defaults.timeout = 2500; // 2.5 seconds etc
`

**Comment by Theofilos-Chamalis** [comment]
Hello, I found that the proposed solution from @JohnnyMinty is working for me but with some slight changes. To be more precise, what has worked in my RN project is:

import axios from 'axios';

axios.interceptors.request.use((config) => {
  config.timeout = 5000;
  return config;
}, (error) => {
  return Promise.reject(error);
});

Hope this helps more people and that features like this get integrated in the library itself in the future!

**Comment by zcgit** [comment]
But that is global settings, but we need a single config for every Api.get().

**Comment by zcgit** [comment]
I think it will be a good choice if we could set all params to axios by API/RestClient in aws lib.

**Comment by jfaq89** [comment]
I also find that this feature would be very useful.
