### ISSUE TITLE
Hub Auth event, doesnt trigger after signIn with facebook/google for the second time

### ISSUE THREAD

**Issue by rreiser-auti** [aws-amplify/amplify-js#3681]
**Describe the bug**
I'm having some issues with withOauth HOC, I'm using facebook and google authentication via provider directly passing through hostedUI. The first time i can complete and login without any problems, but if i logout and then i log in again, the hub doesnt trigger, and the user is not authenticated. Am i missing something?

**Smartphone (please complete the following information):**
 - Device: Iphone 8
 - OS: IOS 12.2

**Comment by haverchuck** [comment]
@rreiser-auti -  Are you using the HOC for aws-amplify-react or aws-amplify-react-native?

**Comment by rreiser-auti** [comment]
@haverchuck Ty for your fast response, its aws-amplify-react-native version:  2.1.10

**Comment by sammartinez** [comment]
@rreiser-auti Can you please update to the latest version, [version 2.1.15](https://www.npmjs.com/package/aws-amplify-react-native) then report back

**Comment by rreiser-auti** [comment]
@sammartinez ty, update both aws-amplify 1.1.32 and aws-amplify-react-native 2.1.15. It Doesn't take any effects =/, still not working after logout. i'm also having issues with this lib in android. it never gets signIn by facebook and google. Ios works fine in the first time.

**Comment by rreiser-auti** [comment]
This is the log from android, the event dispatchs but nothing happens. 
```
channel: "auth"
patternInfo: []
payload:
data:
url: null
__proto__:
constructor: ƒ Object()
hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()
toString: ƒ toString()
valueOf: ƒ valueOf()
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
get __proto__: ƒ __proto__()
set __proto__: ƒ __proto__()
event: "parsingCallbackUrl"
message: "The callback url is being parsed"
__proto__: Object
source: "Auth"
__proto__: Object
```
Also it is executing twice

**Comment by rreiser-auti** [comment]
@manueliglesias Ty for the fix, do you have any prevision to merge this PR? I've also tried to apply the changes by myself, to see if it resolves, but i didn't figure out how to build. I'm getting a bunch of ts erros and i'm not very familiar with ts too. xD
