### ISSUE TITLE
AWS-Amplify Getting undefined in Auth.forgotPasswordSubmit api ReactNative

### ISSUE THREAD

**Issue by MTajuddin96** [aws-amplify/amplify-js#3685]
When i use Auth.forgotPasswordSubmit(username,verificationCode,newPassword) my new password is successfully changed but in response i am getting undefined. However in the documentation it is stated that it will return data.

https://aws-amplify.github.io/docs/js/authentication#forgot-password

Auth.forgotPasswordSubmit(username, code, new_password)
    .then(data => console.log(data))
    .catch(err => console.log(err));

**Comment by haverchuck** [comment]
@MTajuddin96 Which version of RN are you using?

**Comment by MTajuddin96** [comment]
@haverchuck RN v0.59.9

**Comment by viniciusfont** [comment]
@MTajuddin96 I'm having the same issue with v0.59.9. But I think its a problem with the Amplify API.

**Comment by lokeshsharma596** [comment]
this issue is still exist.. in response i am getting undefined  not data

Auth.forgotPasswordSubmit(username, code, new_password)
.then(data => console.log(data))
.catch(err => console.log(err));

**Comment by BernhardSmuts** [comment]
Same here.

React web app

Auth.forgotPasswordSubmit(username, code, new_password)
.then(data => console.log(data))
.catch(err => console.log(err));

**Comment by mkaschke** [comment]
same here!

**Comment by SergiiNikolayev** [comment]
same ¯\_(ツ)_/¯
