### ISSUE TITLE
Caching the response from API on Vue with amplify-connect

### ISSUE THREAD

**Issue by iparrabb** [aws-amplify/amplify-js#3687]
** Which Category is your question related to? **
GraphQL

** What AWS Services are you utilizing? **
Cognito and AppSync

** Provide additional details e.g. code snippets **
I have this component using amplify-connect with Vuejs:

```js
<v-container fluid>
    <amplify-connect
      :query="listDaataForUserQuery"
      :subscription="delete"
      :onSubscriptionMsg="onDelete"
    >
      <template slot-scope="{ loading, data, errors }">
        <v-container ma-0 pa-0 fluid fill-height v-if="loading">
          loading...
        </v-container>

        <v-layout row wrap v-if="errors.length">
          {{ errors }}
        </v-layout>

        <div v-else-if="data">

        </div>
      </template>
    </amplify-connect>
</v-container fluid>
```
Exists any way for caching the response like this using amplify-connect component?

 ```js
import { Cache } from "aws-amplify";
export default class CacheGraphQL {
  get(key) {
    return Cache.getItem(key);
  }

  async set(key, api) {
    if (!this.get(key)) {
      Cache.setItem(key, api);
    }
    return this.get(key);
  }
}
```

Thanks!

**Comment by manueliglesias** [comment]
Hi @iparrabb 

> Exists any way for caching the response like this using amplify-connect component?

There is currently no way to do that in the amplify-connect component. What is your use case? How would you like a feature like this to work?

**Comment by iparrabb** [comment]
Thanks for your quick reply @manueliglesias.
My case is exactly like says the documentation: 

> For instance, you may wish to cache all JSON responses from the API module for the next 10 minutes, but like to store user input values or preferences for a month.

I know that I can do:

```js
const {data} = await API.graphql(graphqlOperation(this.actions.list, {}));
this.privateNotes = CacheGraphQL.set("PrivateNotes", data.listPrivateNotes.items);
```
Instead I like would to use the amplify-connect component, but then I lose all benefits, subscriptions for example.
