### ISSUE TITLE
ConfirmSignUp does not work for Confirmation Link

### ISSUE THREAD

**Issue by Erlix322** [aws-amplify/amplify-js#3690]
**Describe the bug**
Hey Guys! So far the React-Native Component does only show the field for confirmation code, but when I configured my cognito to send confirmation links this won't work. Is there any option I missed or is this not implemented yet?

**Comment by haverchuck** [comment]
@Erlix322  - You can configure your Authenticator component to not display the confirmation component, and instead display a custom component (perhaps with a message telling the user to check their email).  

You can find an example for vanilla react [here](https://aws-amplify.github.io/docs/cli-toolchain/cognito-triggers#react-sample-1).

**Comment by Erlix322** [comment]
@haverchuck Thanks a lot!

Rather than using AuthPiece in that link docs suggest, you should override the Components directly (SignUp, ConfirmSignUp, etc)  

e.g.  
**CustomSignUp**  
`class CustomConfirmation extends ConfirmSignUp {

    constructor(props){
        super(props)
    }
    
    showComponent(theme) {
      if (this.props.authState === 'confirmSignUp') {
        return (
            <View>                
                <Text>Check your email for a confirmation link.</Text>              
          </View>
        );
      } else {
        return null;
      }
    }
}`

**Customized SignUp Screen** 

`class SignUpScreen extends Component {

    
    render() {
        return (  
          <View>
                <Authenticator hideDefault={true} authState='signUp' >
                    <SignUp signUpConfig={
                    {
                        hideAllDefaults: ["phone_number","username","email"],
                        defaultCountryCode: '1',
                        signUpFields:[
                            {label:"Email",key:"username"},
                            {label:"Name",key:"name"},
                            {label:"Family name",key:"family_name"},
                            {label: 'Password',key: 'password',type: 'password'}
                        ]                    
                    }}  />
                    <CustomConfirmation override={ConfirmSignUp}{...this.props} />
                           
                </Authenticator> 
            </View>
                
            
        );
    }
 
}`
