### ISSUE TITLE
Are there any security considerations for using the API component, which does not have a way to clean data before putting it into the database?

### ISSUE THREAD

**Issue by ajhool** [aws-amplify/amplify-js#3692]
** Which Category is your question related to? **
API (or Storage)

** What AWS Services are you utilizing? **
API, Storage, Analytics, Lambda, AppSync,

** Provide additional details e.g. code snippets **
As we prepare to go live in production, are there any security considerations that we might have overlooked? One particular area of uncertainty is the API package, which does not provide a way to clean data before persisting it. In traditional rest services, I would perform tasks like `limitSize(input)`, `removeHTML(input)`, etc.

If Attacker were to persist `<script>window.alert('ATTACK')</script>` or `<DIV STYLE="background-image: url(javascript:alert('Injected'))">` as the name of a Book object, and my react code looks something like:

```
const { getBook } = await API.getBook(id);

return (<div>{getBook.data.name}</div>);
```

Will that attack succeed? Additionally, because I'm using SSR, does that increase the risk of malicious code executing in the browser because all of the HTML is printed on the server?

**Comment by mlabieniec** [comment]
It depends on the framework you are using. If you use Angular there is some built in mechanisms that will sanitize the values before display:
https://angular.io/guide/security

Other frameworks handle it differently i.e. React etc. You can also use a [library](https://dev.to/jam3/how-to-prevent-xss-attacks-when-using-dangerouslysetinnerhtml-in-react-1464) to sanitize the inputs before displaying which is best practice.
