### ISSUE TITLE
Unable to get http error response code: 4XX

### ISSUE THREAD

**Issue by Jun711** [aws-amplify/amplify-js#3693]
**Describe the bug**
When Api fails with network error, for example 413, the error object doesn't contain error response code. Error is caught but not enough information such as error response code is provided by error object.

**To Reproduce**
When I uploaded with payload over lambda size limit, I expected to get 413 error code but I couldn't retrieve 413 from the error code.
```
public put() {
  const apiName = 'myApi';
  const init = {
    headers: {
      'Content-Type': 'application/json'
    },
    body: {
      data: 123  
    },
    response: true
  };

  API.put(apiName, '/get', config)
  .then(res => {
    return res;
  }
  .catch(error => {
    console.error('error: ', error);
    console.error('error.response: ', error.response); // undefined
    console.error('error.name: ', error.name); // Error
    console.error('error.message: ', error.message); // Network Error
  }
}
```

**Expected behavior**
Expected to be able to retrieve error response code

**Screenshots**
![aws-amplify-not-showing-error-code](https://user-images.githubusercontent.com/6880939/61565632-89e1b980-aa2e-11e9-9895-aa5d08c54f9f.png)

**Desktop (please complete the following information):**
 - OS: OSX 10.13.6
 - Browser: Chrome 75
 - Version: 75.0.3770.142 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
It could be just an issue with Axios 
https://github.com/axios/axios/issues/1427

**Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

Let me know if I use Amplify API incorrectly or you need more information. Thank you.

**Comment by Jun711** [comment]
bump

**Comment by Jun711** [comment]
bump

**Comment by Aelaiig** [comment]
Did you resolve your issue ?

Unless you have cors problem, I think you have to catch your error in your lambda and send it with headers. You did use amplify API correctly.
