### ISSUE TITLE
AWS Amplify/Appsync - setting limit on rows returned from a list query

### ISSUE THREAD

**Issue by blairtaylor** [aws-amplify/amplify-js#3694]
I want to increase the number of rows returned on a List... query greater than the default 10. Using the limit parameter does not seem to work.

I have tried passing the limit in several different ways but I always receive only the default 10 rows returned. There should be 12 rows returned which match the filter criteria.

  const filter = {
    or: [
      { firstname: { contains: searchValue } },
      { lastname: { contains: searchValue } },
      { emailaddress: { contains: searchValue } },
      { phone: { contains: searchValue } }
    ]

  };

  const limit = {limit: 50};
  // const limit = 50; // this does not work either

  const result = await API.graphql(
    graphqlOperation(listProviders, {filter}, {limit})
  );

I expect to receive true number of rows which match the filter criteria. Only receive 10 rows back.
When I run the query in AWS Appsync, it returns the 12 rows correctly.
 What am I doing incorrectly?

**Comment by blairtaylor** [comment]
To answer my own question, it should be:

const limit = 50; 
const result = await API.graphql(
graphqlOperation(listProviders, {filter, limit)
);

This works correctly.

**Comment by Jenpaulino3** [comment]
> To answer my own question, it should be:
> 
> const limit = 50;
> const result = await API.graphql(
> graphqlOperation(listProviders, {filter, limit)
> );
> 
> This works correctly.

This worked for me! Thank you so much 🙌
