### ISSUE TITLE
Analytics/Push Endpoint Address format constraint?

### ISSUE THREAD

**Issue by bneigher** [aws-amplify/amplify-js#3695]
**Which Category is your question related to?**
Amplify Analytics / Push Notifications.

**What AWS Services are you utilizing?**
AWS Pinpoint Push Notifications

**Provide additional details e.g. code snippets**
When testing a push notification campaign - I'm seeing an error which is curious...
<img width="1291" alt="Screen Shot 2019-07-19 at 6 21 50 PM" src="https://user-images.githubusercontent.com/4627728/61572439-87915680-aa52-11e9-9ef3-40429c59a990.png">

When looking into the difference between testing sending events to endpoints that don't show this error in the console, I am noticing that indeed when the endpoint.address value that I set in updateEndpoint is an even length string - I don't see this error, but when it is odd it's throwing this.

Is there a constraint on the format of the address value?  If so - this should be reflected in the docs!  All it says in the setup is:
```
address: 'xxxxxxx', // The unique identifier for the recipient. For example, an address could be a device token, email address, or mobile phone number.
```

**Comment by bneigher** [comment]
Looks like UUID also is not acceptable.
<img width="1295" alt="Screen Shot 2019-07-19 at 7 55 34 PM" src="https://user-images.githubusercontent.com/4627728/61573192-32a80d00-aa5f-11e9-9d2b-54d37016f902.png">

**Comment by bneigher** [comment]
My solution has been to set the address to the push_token that is in local storage.
```
const deviceToken = await AsyncStorage.getItem(
  "push_token" + Config.AWS_ANALYTICS_ID
);
await Analytics.updateEndpoint({ address: deviceToken });
```
If this correct when ever setting manually the address - it is for sure not documented in the aws amplify setup docs. Hopefully this helps someone out there.


```

**Comment by rawadrifai** [comment]
Amplify team - I second this. The documentation provided does not work. I tried it many times. The updateEndpoint function returns accepted always.. but I cannot reach my devices through the endpoint ids (which I am not sure if the same thing as the "address").

@haverchuck can you helps get some answers pls?

**Comment by idanlo** [comment]
This should be re-opened
