### ISSUE TITLE
Persistent Login not Returning Updated User Attributes

### ISSUE THREAD

**Issue by AENeuro** [aws-amplify/amplify-js#3697]
**Is your feature request related to a problem? Please describe.**
There's a use case when the user attributes of user A were changed by an admin user. And when user A logs in through persistent login, the attributes were not reflecting the updated attributes. Changes will only take effect after the user logs out and log back in.

Is this a designed mechanism? How do I make sure the user attributes are updated even when the user logs in through persistent login?

**Comment by haverchuck** [comment]
@AENeuro It depends a bit on what you mean by persistent login, but most likely you need to use the [bypassCache](https://aws-amplify.github.io/docs/js/authentication#retrieve-current-authenticated-user) option to get the updated user info.

**Comment by AENeuro** [comment]
Appreciate the reply. What I meant by persistent login was that second time
the user visits a site, he was automatically logged in without having to
type the password.

Will disabling the cache disable this persistent login entirely?

**Comment by haverchuck** [comment]
@AENeuro  - I don't believe so.  bypassCache should simply force the app to make another call to Cognito to retrieve the user attributes, as opposed to using what may be cached in the browser.

**Comment by haverchuck** [comment]
Closing this issue; please open another if the provided answer is insufficient.
