### ISSUE TITLE
Analytics.record throws  ExpiredTokenException and InvalidSignatureException

### ISSUE THREAD

**Issue by libeanim** [aws-amplify/amplify-js#3699]
**Which Category is your question related to?**
Amplify Analytics in combination with React Native (Expo)

**What AWS Services are you utilizing?**

- Amplify Analytics (Pinpoint)
- Amplify Auth (Cognito)
- Amplify Api (Appsync)

**Provide additional details e.g. code snippets**
Hi guys, thanks for your work! :)
I recently added analytics to our productions system and since then I receive errors via our bug tracking service that seem to come from the `Analytics.record` function when I record custom events in our app.
I received following two errors which seem to be outside of my control:
- `AWSPinpointProvider - record event failed.  ExpiredTokenException: The security token included in the request is expired`.
As far as I understand, keeping the authentication token (which is issued by cognito) up to date is the responsibility of the sdk? There haven't been any issues with AppSync which we use as backend via 'Amplify Api'.

- `[ERROR] 16:45.276 AWSPinpointProvider - record event failed.  InvalidSignatureException: Signature not yet current: 20190721T181644Z is still later than 20190721T180702Z (20190721T180202Z + 5 min.)` Well maybe one of the users changed the clock on their phone manually? Why does this cause a signature exception?

Did I miss something in the documentation that would prevent this from happening or is that expected behaviour and I have to wrap the `Analytics.record` function calls in a `try-catch-block`?

_I am a bit scared that these exceptions actually cause the main thread of the app to crash._

**Comment by libeanim** [comment]
Ok I can confirm that the `InvalidSignatureException` happens when someone changes the phone clock to a time in the future. Also it causes a react-native app to crash when this error occurs.

- Wrapping the `Analytics.record` function in a try-catch-block doesn't change anything, it still crashes.
- Setting `autoSessionRecord` to `false` doesn't have an effect.
- Disabling the Analytics entirely  doesn't have an effect either.

Only removing the entire analytics part from the app solves it. As a consequence I cannot use Amplify Analytics and Pinpoint. This seems like a serious bug.

I could not reproduce the ` ExpiredTokenException` but I assume it also causes the app to crash.

**Comment by haverchuck** [comment]
@libeanim Are you seeing this on both iOS and Android?  I have been unable to reproduce on an Android emulator.

**Comment by haverchuck** [comment]
@libeanim In the entry point of your application, can you do:
import AWS from 'aws-sdk'
...and then, after you call Amplify.configure, do
AWS.config.correctClockSkew = true?

Please respond with whether or not that has any effect.

**Comment by libeanim** [comment]
@haverchuck Thanks!
I can confirm that `AWS.config.correctClockSkew = true` apparently solves the ` InvalidSignatureException` :+1: 

Give me some time tomorrow to see if I can reproduce the `ExpiredTokenException` and provide a simple demo.

**Comment by haverchuck** [comment]
@libeanim It's possible that both errors can be solved by this workaround.  We are discussing ways to obviate the need for it.

**Comment by libeanim** [comment]
@haverchuck Thanks, yes it seems like your suggested fix also solves the `ExpiredTokenException`. :+1: 
I will reactivate analytics in our production system and let you know if something comes up in this bigger sample set.

Cheers and have a great Monday 😊

**Comment by libeanim** [comment]
@haverchuck Just received the first error message from one of our production systems :(
Sorry bro.
 `AWSPinpointProvider - record event failed.  ExpiredTokenException: The security token included in the request is expired`

**Comment by EnanlyPay** [comment]
>  AWS.config.correctClockSkew = true?

Hi @haverchuck this does not work with aws-appsync, I'm still getting 403 errors. Do you have another solution ?

**Comment by elorzafe** [comment]
@EnanlyPay what is your auth mode on your AppSync API?

@libeanim did you configure `flushInterval` for `AWSPinpoint`?

**Comment by EnanlyPay** [comment]
> @EnanlyPay what is your auth mode on your AppSync API?
> 
> @libeanim did you configure `flushInterval` for `AWSPinpoint`?

AWS_IAM

**Comment by bneigher** [comment]
> AWS.config.correctClockSkew = true

this doesn't seem to fix pinpoint either

issue is making Sentry treat each ExpiredToken error as a crash on react-native :(

**Comment by libeanim** [comment]
@elorzafe 

> @libeanim did you configure flushInterval for AWSPinpoint?

No, I only added this to my `aws-exports` file:

```js
  Analytics: {
    disabled: false,
    autoSessionRecord: true,
    AWSPinpoint: {
      appId: '...',
      region: '...',
      endpointId: deviceId,
    },
  },
}
```

**Comment by bneigher** [comment]
This can easily be reproduced by an inactive react native app (> 1hr), open the app, and have an Analytics event fire before the Auth (federated in my case) can attempt to refresh itself.

Is the issue that the Analytics tracking isn't waiting until a new token is issued?

**Comment by sandaruny** [comment]
![Uploading image.png…]()
Can confirm @bneigher scenario. Since it can be retry, is there a way to catch it and retry?

**Comment by elorzafe** [comment]
@iartemiev can you update this issue when you have your fix. Thanks!

**Comment by iartemiev** [comment]
@elorzafe will do 👍🏻

**Comment by chai86** [comment]
@elorzafe Could you please see this similar issue on #5738

**Comment by ericclemmons** [comment]
I've done some research into this here: https://github.com/aws-amplify/amplify-js/pull/5869#issuecomment-634932879

At least on web, you can reproduce by changing the system clock to 1+ hours ahead and making an `Analytics.record` call (it will fail with signature errors).

**Comment by sammartinez** [comment]
@libeanim can you confirm with the changes that were merged that this resolved your issue? Please let us know

**Comment by libeanim** [comment]
Hi all thanks for looking into this!
We are actually not using amplify analytics at the moment, so I can't immediately check if it's resolved but I'd close this issue for now :+1:
