### ISSUE TITLE
API Custom Request Headers

### ISSUE THREAD

**Issue by tasos-eft** [aws-amplify/amplify-js#3706]
** Which Category is your question related to? **
API request headers for authorization purposes

** What AWS Services are you utilizing? **
Amplify API & AUTH

** Provide additional details e.g. code snippets **
We're consuming an AWS REST API that uses Cognito User Pools for Authorization. via an angular 7 client that uses the Amplify framework. 

On our client we set request headers to  authorization the API calls by passing a custom_header function into the Amplify API configuration: 

Following the documentation 
https://aws-amplify.github.io/docs/js/api#custom-request-headers

we should achieve authorization via this function call 

```
custom_header: async () => { 
    return { Authorization: `Bearer ${(await Auth.currentSession()).getAccessToken().getJwtToken()}` 
}
```
using the access token returns a 401 error. 

on the other hand the following modification  

```
custom_header: async () => {           
   Authorization: `Bearer ${(await Auth.currentSession()).getIdToken().getJwtToken()}`
}
```
that uses the Id token works. 

Is this an error on the documentation? 

Many thanks
Tasos

**Comment by haverchuck** [comment]
@tasos-eft  - Out of curiosity - what error message do you receive if you remove the custom header entirely?

**Comment by tasos-eft** [comment]
@haverchuck I think it returns an authentication error
