### ISSUE TITLE
API calls return 403 after inactivity in the app

### ISSUE THREAD

**Issue by jayalog** [aws-amplify/amplify-js#3709]
Hi,

I am using aws amplify with angular. Once the user is signed in the api calls working perfect. After some inactivity, if the user tries to do some operation the api calls failing with 403. After refresh everything working fine again. Before each api calls whether i have to refresh any token?? What im missing??

This is how i configure aws amplify in app.module.ts

const amplifyConfig = {
  Auth: {
    identityPoolId: Config.IDENTITY_POOL_ID,
    region: Config.REGION,
    userPoolId: Config.USER_POOL_ID,
    userPoolWebClientId: Config.CLIENT_ID,
    mandatorySignIn: true, // Enforce user authentication prior to accessing AWS resources or not
  },
  API: {
    endpoints: [
      {
        name: Config.API_NAME,
        endpoint: Config.API_ENDPOINT
      },
      {
        name: Config.API_DEV_NAME,
        endpoint: Config.API_DEV_ENDPOINT
      }
    ]
  }
};

This my api call in api.service.ts
const path = '/****/' + this.id;
    this.init = {};
    return new Promise((resolve, reject) => {
      API.get(this.apiName, path, this.init).then(response => {
        console.log(response);
        resolve(response);
      }).catch(error => {
        console.log(error.response);
        reject(error);
      });
    });

**Comment by haverchuck** [comment]
@jayalog This does seems like an issue with the refresh token - we will investigate.

**Comment by jayalog** [comment]
Hi,
It seems amplify will handle refreshing tokens during api calls. Whether we need to refresh the user session before each and every API calls!!!

In my response header i can see x-amzn-errortype: ExpiredTokenException. Any solutions..

**Comment by haverchuck** [comment]
You shouldn't need to manually refresh anything.  Can you try [setting the amplify logger level](https://aws-amplify.github.io/docs/js/logger#setting-logging-levels) to VERBOSE and post any releven output here?

**Comment by bneigher** [comment]
I believe the tokens are not being automatically refreshed in react-native.  As a workaround, each time either Analytics, or Storage throws `ExpiredTokenException` - I have a routine that will manually re-login the user - but this doesn't behave smoothly at all:

```
export const cognitoLogin = async user => {
  await Auth.federatedSignIn(
    Config.AUTH0_DOMAIN, // The Auth0 Domain,
    {
      token: user.idToken, // The id token from Auth0
      expires_at: jwtDecode(user.idToken).exp * 1000,
    },
    {
      userId: user.user_id,
      email: user.email,
    },
  );
  const endpoint = await endpointDecorator(user);
  await Analytics.updateEndpoint(endpoint);
};

export const cognitoAuthenticate = async user => {
  try {
    await Auth.currentAuthenticatedUser();
  } catch (err) {
    await cognitoLogin(user);
  }
  return user;
};
```

Ideally each API call from the amplify services should refresh the token gracefully and retry before throwing.
