### ISSUE TITLE
Filter between using Connect component not returning all data

### ISSUE THREAD

**Issue by watanabethais** [aws-amplify/amplify-js#3712]
I have the following schema in my project:

```
type Report @model {
  id: ID!
  alarmTime: AWSDateTime!
  ...
}
```

When I execute the following query in AWS AppSync console, I get the expected results.

```
query listReports {
  listReports(filter: {alarmTime: {between: ["2019-07-22T23:00:00Z","2019-07-23T22:59:59Z"]}}, limit: 100) {
    items {
      id
      alarmTime
      ...
    }
  }
}
```

The results in AWS AppSync queries console:

```
{
  "data": {
    "listReports": {
      "items": [
        {
          "id": "17a8158e-e0d4-4f48-aca9-526eea0e8c6b",
          "alarmTime": "2019-07-23T04:24:50.624Z"
          ...
        },
        {
          "id": "48964d94-2165-4b22-b141-ea1de5d489f7",
          "alarmTime": "2019-07-23T01:05:32.308Z"
          ...
        },
        {
          "id": "be328d11-9e64-4040-bfcc-3f71ce1c4003",
          "alarmTime": "2019-07-23T04:24:50.624Z"
          ...
        },
        {
          "id": "0f35f969-2abc-4fb8-8ef9-e33cfce5a453",
          "alarmTime": "2019-07-23T01:05:32.308Z"
          ...
        },
        {
          "id": "0380aa3b-6139-4bb8-a1c9-bad603f9c613",
          "alarmTime": "2019-07-23T01:05:32.308Z"
          ...
        },
        {
          "id": "6ff33fa4-5ee8-406d-9391-ff0acb1e483b",
          "alarmTime": "2019-07-23T01:05:32.308Z"
          ...
        }
      ]
    }
  }
}
```

But when I execute the same query using the Connect component in my project, It returns less data than expected.

```
<Connect
              query={graphqlOperation(queries.listReports,
                { filter: { alarmTime: { between: this.handleDateInput(this.state.selectedDate) } } }, { limit: 100 })}>
              {({ data: { listReports }, loading, error }) => {
                if (error) return (<h3>Error</h3>);
                if (loading || !listTodos) return (<h3>Loading...</h3>);
                console.log(listReports.items);
                return <ReportView reports={listReports.items} />;
              }}
            </Connect>
```

The results using Connect component:

```
(2) [{…}, {…}]
0: {id: "48964d94-2165-4b22-b141-ea1de5d489f7", alarmTime: "2019-07-23T01:05:32.308Z", …}
1: {id: "17a8158e-e0d4-4f48-aca9-526eea0e8c6b", alarmTime: "2019-07-23T04:24:50.624Z", …}
length: 2
__proto__: Array(0)
```

Dependencies:

- "aws-amplify": "^1.1.32",
- "aws-amplify-react": "^2.3.11",
- "react": "^16.8.6",

Am I missing something?

**Comment by haverchuck** [comment]
@watanabethais - In this line:
`                { filter: { alarmTime: { between: this.handleDateInput(this.state.selectedDate) } } }, { limit: 100 })}>
`
... have you tried hard coding the date range as you do in the query you're running in the console?  Just to eliminate the possibility that there is something going on with the selected state?

**Comment by watanabethais** [comment]
Yes! I've tried hard coding the date range like this, but no success:

```
<Connect
              query={graphqlOperation(queries.listReports,
                { filter: { alarmTime: { between: ["2019-07-22T23:00:00Z","2019-07-23T22:59:59Z"] } } }, { limit: 100 })}>
              {({ data: { listReports }, loading, error }) => {
                if (error) return (<h3>Error</h3>);
                if (loading || !listTodos) return (<h3>Loading...</h3>);
                console.log(listReports.items);
                return <ReportView reports={listReports.items} />;
              }}
            </Connect>
```

Then, I tried using the API.graphql... returns less data too:

```
const query = API.graphql(graphqlOperation(queries.listReports,
      { filter: { alarmTime: { between: ["2019-07-22T23:00:00Z","2019-07-23T22:59:59Z"] } } }, { limit: 100 }));
    console.log(query);
```

**Comment by haverchuck** [comment]
@watanabethais - I reproduced your code and your values, and it seems to work as expected.  Can you post an example of how you performed these mutations... ie. how you inserted them into the database?

A couple of things to note (which probably aren't causing your issue):
 `if (loading || !listTodos) return (<h3>Loading...</h3>);` should probably be ` if (loading || !listRepots) return (<h3>Loading...</h3>);`
And also..
`query={graphqlOperation(queries.listReports,
                { filter: { alarmTime: { between: ["2019-07-22T23:00:00Z","2019-07-23T22:59:59Z"] } } }, { limit: 100 })}>`
should be 
`query={graphqlOperation(queries.listReports,
                { filter: { alarmTime: { between: ["2019-07-22T23:00:00Z","2019-07-23T22:59:59Z"] } }, limit: 100 })}>`

**Comment by watanabethais** [comment]
The problem was actually this! I've corrected my query and the result comes as expected.
Omg! I didn't notice the braces in limit was the problem... sorry for that.

Thank you so much for your help @haverchuck !
