### ISSUE TITLE
Cognito hosted UI double submit bug

### ISSUE THREAD

**Issue by mrcoles** [aws-amplify/amplify-js#3716]
**Describe the bug**

I am using the Cognito hosted UI with my AWS Amplify React app. I have it set up to only ask for email and a password.

On the signup page in the hosted UI, I am able to submit the form twice before it finishes loading after the first submit, and this is causing it to show the error: “Alias entry already exists for a different username”

**To Reproduce**

1. Go to the signup page in the Cognito hosted UI
2. Enter the required info
3. With the focus in the final form field, e.g., password in my screenshot, hit Return to submit the form
4. Immediately click the "Sign up" button too (this will create a second request to sign up the user)

**Expected behavior**

I expect the form to block the second submit (using JavaScript) as the first submit is already happening.

**Screenshots**

![cognito-alias-already-exists-double-submit](https://user-images.githubusercontent.com/136651/61733207-41d3d700-ad4d-11e9-9330-5c6613e8a6b5.png)

**Desktop (please complete the following information):**

 - OS: Mac OSX 10.14
 - Browser Chrome 75.0.3770.100

**Additional context**

Preventing additional form submits is a fundamental design pattern with websites. Perhaps it was overlooked here because the form appears to do a direct HTTP POST without AJAX?

Something that could prevent this would look like the following (obviously needing polyfills/transpilation to support older browsers):

```javascript
document.querySelectorAll(".cognito-asf").forEach(form => {
  let isSubmitting = false;

  form.addEventListener(
    "submit",
    evt => {
      if (isSubmitting) {
        evt.preventDefault();
      }
      isSubmitting = true;
    },
    false
  );
});
```

**Comment by haverchuck** [comment]
@mrcoles  - This appears to be an issue with the Hosted UI and not the Amplify framework.  I have notified the service team, and am closing this issue.

**Comment by mrcoles** [comment]
@haverchuck thanks! Is this the only way to report issues to the service team?
