### ISSUE TITLE
Cognito Signature expired

### ISSUE THREAD

**Issue by mezalejandro** [aws-amplify/amplify-js#3719]
**Describe the bug**
After login with cognito i have the following error:
{"message":"Signature expired: 20190723T172834Z is now earlier than 20190723T201503Z (20190723T203003Z - 15 min.)","code":"InvalidSignatureException","time":"2019-07-23T17:28:34.586Z","requestId":"6GQQCIH6BKQ8UK7035CLUUI44FVV4KQNSO5AEMVJF66Q9ASUAAJG","statusCode":400,"retryable":true,"line":122002,"column":42,"sourceURL":"http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false"}

**To Reproduce**
1. LogIn user and password

**Additional context**
React Native 0.59.9

**Comment by haverchuck** [comment]
@mezalejandro - In the entry point of your application, can you do:
`import AWS from 'aws-sdk'`
...and then, after you call Amplify.configure, do
`AWS.config.correctClockSkew = true`?

Please respond with whether or not that has any effect.

**Comment by mezalejandro** [comment]
> @mezalejandro - In the entry point of your application, can you do:
> `import AWS from 'aws-sdk'`
> ...and then, after you call Amplify.configure, do
> `AWS.config.correctClockSkew = true`?
> 
> Please respond with whether or not that has any effect.

Hello,

for now it is working fine with AWS.config.correctClockSkew = true

Thank you

**Comment by willdady** [comment]
@haverchuck your solution requires explicitly adding `aws-sdk` as a dependency yes? It would be great if `correctClockSkew` was exposed via Amplify's config rather than having to install aws-sdk since it's already a dependency of Amplify. Personally I feel this should simply be **true by default**. My team sees this error logged to Sentry several times a day for our React Native app. We've had to resort to explicitly asking our users to check their device time in our error messages because of this.

**Comment by ericclemmons** [comment]
With the latest release of Amplify, we leverage https://github.com/aws/aws-sdk-js-v3 which automatically accounts for clock drift by default: https://github.com/aws/aws-sdk-js-v3/pull/459 

Can you share if you're still experiencing issues and, if so, steps to reproduce?

**Comment by ericclemmons** [comment]
I tested this flow with a +5 hour clock drift and confirmed that username + password logins work, thanks to aws-sdk-v3's auto-drift correction.

For anyone affected, be sure to upgrade to the latest `aws-amplify` (v3) and let me know if you still experience any issues!

**Comment by amirhajimirsadeghi** [comment]
Hey, @ericclemmons I'm experiencing this issue with version `3.3.21`. getting the following error from API Gateway:
```
"message": "Signature expired: 20210305T222507Z is now earlier than 20210305T222511Z (20210305T223011Z - 5 min.)"
```


Do I need to manually import `aws-sdk-js-v3` for the automatic handling of clock skew to be done?

**Comment by amirhajimirsadeghi** [comment]
Created this issue

https://github.com/aws-amplify/amplify-js/issues/7913
