### ISSUE TITLE
Facebook auth, not correctly working

### ISSUE THREAD

**Issue by Sheleya** [aws-amplify/amplify-js#3722]
I have a problem, that when I try to logIn via Facebook, the app redirects me to browser trying to upload the page and then immediately shows me a popup asking  "Open in "<app-name>"?". But it should be after i confirm facebook login and enter credentials. I don't see the facebook page, but it should redirect me to facebook page.
And in console i see the error : "Unhandled Promise Rejection (id: 0):
Error: invalid_grant ..."

"react-native": "0.59.5",
"aws-amplify": "^1.1.32",

Any suggestions why is it working in that way?

**Comment by haverchuck** [comment]
@Sheleya Are you using Cognito Hosted UI?
