### ISSUE TITLE
forgotPasswordSubmit password policy error handling

### ISSUE THREAD

**Issue by malcomm** [aws-amplify/amplify-js#3723]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Cognito, appsync

** Provide additional details e.g. code snippets **

Implementing the forgot password and I am calling this:

```Auth.forgotPasswordSubmit(username, code, password);```

What happens if the user doesn't conform to the password policy? Right now `Auth.forgotPasswordSubmit` returns a Promise<void>. The error coming back just is a plain 400 when the user doesn't conform ...

Am I missing something? Shouldn't this return information about if the user entered the correct code in and if they conformed to the password policy?

**Comment by haverchuck** [comment]
@malcomm  - If you want to catch an error based on the password policy, you could do this...
```
Auth.forgotPasswordSubmit(username, code, password)
   .then((res) => console.log('success', res))
   .catch((err) => console.log('fail', err))
```
... in which 'err' would be formed like so:
```
{
   "code":"InvalidParameterException",
   "name":"InvalidParameterException",
   "message":"1 validation error detected: Value at 'password' failed to satisfy constraint: Member must 
     have length greater than or equal to 6"
}
```

**Comment by malcomm** [comment]
@haverchuck - Thank you! I must have just been tired when doing this ... I thought I was catching that error correctly, I was not. All good now.
