### ISSUE TITLE
Amplify Storage.get returns differently depending on the promise method used

### ISSUE THREAD

**Issue by bakeruk** [aws-amplify/amplify-js#3725]
If I use `Storage.get` to retrieve an image using the Bluebird methodology of a promise,

```
Storage.get(s3Key, {
  level
})
  .then(data => {
    console.log("data", data);
  })
  .catch(error => console.error(error));
```

`data` is a URL to for the image.

However, if I make `Storage.get` use the `async /await` methodology then the data return is an object with a `blob` or `Buffer` etc.

It is confusing especially as the documentation for this is unclear. Is there a way to select what type of response I want to return rather than using the different promise methodologies? 

Cheers!

**Comment by haverchuck** [comment]
@bakeruk - Are you passing in any options other than 'level'?

**Comment by bakeruk** [comment]
I have done but it still returns the same type of response. 

What options should effect this response?
