### ISSUE TITLE
Cognito Password Expiration

### ISSUE THREAD

**Issue by malcomm** [aws-amplify/amplify-js#3729]
**Is your feature request related to a problem? Please describe.**

I'm using amplify with Cognito and I do not see a way to set a password expiration. I know this feature request doesn't fit here exactly ... I just don't have any other avenue to report this. 

**Describe the solution you'd like**

Cognito should have a way to set a password expiration policy.

**Describe alternatives you've considered**

Another service?

**Additional context**

I know there's a half baked idea when doing a search about the `passwordUpdatedAt` being used ... but that doesn't seem right.

**Comment by haverchuck** [comment]
@malcomm - I can see the value in this feature request.  I think it would be good to post it in the [Cognito developers forum,](https://forums.aws.amazon.com/forum.jspa?forumID=173) which should be monitored by the Cognito team (and you might get good input from other users).
