### ISSUE TITLE
Is addPluggable with AWSIoTProvider really Async?

### ISSUE THREAD

**Issue by jmazala** [aws-amplify/amplify-js#3737]
** Which Category is your question related to? **
AWS IoT Subscribing

** What AWS Services are you utilizing? **
AWS IoT

** Provide additional details e.g. code snippets **

I'm wondering if connecting to the AWS IoT broker using Amplify is really async.  I have to hack timeouts into my code before subscribing or publishing because I don't think that function actually returns a Promise.
````
/**
     * add plugin into Analytics category
     * @param {Object} pluggable - an instance of the plugin
     */
    public async addPluggable(pluggable: PubSubProvider) {
        if (pluggable && pluggable.getCategory() === 'PubSub') {
            this._pluggables.push(pluggable);

            const config = pluggable.configure(this._options);

            return config;
        }
    }
````

Maybe someone can advise on how this is supposed to be used?  I want to ensure I'm connected before doing other work.  Here is my code:

```
`export const connect = async () => {
  if (CONNECTED) {
    return;
  }
  const { identityPoolId, region, userPoolId, userPoolWebClientId, awsPubsubEndpoint } = OPTIONS;
  Amplify.configure({
    Auth: {
      identityPoolId,
      region,
      userPoolId,
      userPoolWebClientId,
    },
  });

  await Amplify.addPluggable(
    new AWSIoTProvider({
      aws_pubsub_region: region,
      aws_pubsub_endpoint: awsPubsubEndpoint,
    })
  );

  CONNECTED = true;
};`
```

Thanks,
Jonathan
mazala.2@osu.edu

**Comment by jkeys-ecg-nmsu** [comment]
The keyword `async` basically wraps your function into a Promise and your return into a resolve. So the code is being transpiled to this:

`
/**
     * add plugin into Analytics category
     * @param {Object} pluggable - an instance of the plugin
     */
    public addPluggable(pluggable: PubSubProvider) {
        if (pluggable && pluggable.getCategory() === 'PubSub') {
            this._pluggables.push(pluggable);

            const config = pluggable.configure(this._options);

            return config;
        }
    }
`

**Comment by jmazala** [comment]
it looks like the `Amplify.configure` function is synchronous and doesn't contain any operations outside of modifying memory.  no promise or callback there.. still a little confused on why it doesn't seem to actually wait for a connection before returning from that function

**Comment by jordanranz** [comment]
To clarify it seems like we need an onConnect callback function implemented and exposed to you so that you can determine when the connection to AWS IoT has been made. Is that correct? If so, this would probably live independently from `addPluggable` as that function is for configuring a plugin on the category.

**Comment by jmazala** [comment]
I think that’s exactly right Jordan. Unless there’s already a way to tell when it connects, especially because it doesn’t seem like the add pluggable returning a promise accomplished that, to the best of my knowledge.

________________________________

**Comment by Thembelani** [comment]
Hi guys, any update to this? @jmazala did you find a workaround for this?
Thanks

**Comment by jmazala** [comment]
I haven’t but I can review the code again

________________________________

**Comment by mufarrah** [comment]
Any update on this ?

**Comment by stocaaro** [comment]
Two things. Reading over the code, I don't see anything happening related to `addPluggable` that needs to be async. This may be an artifact of other `addPluggable` interfaces on other categories being `async` where this was marked `async` for consistency. (This is a theory that I haven't chased down to validate). The team is migrating away from the pluggable pattern in the next version of the library, so this will go away more than it will be fixed.

From the conversation, it sounds like the need is related to tracking when the connection is formed. The team has added [Hub events corresponding the PubSub connection state changes](https://docs.amplify.aws/lib/pubsub/subunsub/q/platform/js/#subscription-connection-status-updates) as part of introducing reconnection. 

Based on both of these points, can we close this issue out or are there aspects of this issue that aren't met by the Hub connection states and the coming migration away from plugins?

**Comment by cwomack** [comment]
Closing this issue as we have not heard back. If you are still experiencing this, please review the [comment above](https://github.com/aws-amplify/amplify-js/issues/3737#issuecomment-1692208862) from @stocaaro first and reply back with any additional information or context that may be relevant.  We'd be happy to re-open the issue if needed.  

Thank you!
