### ISSUE TITLE
Amplify caches old user attributes - currentAuthenticatedUser

### ISSUE THREAD

**Issue by giulioambrogi** [aws-amplify/amplify-js#3739]
## Categories
Amplify, Cognito, front-end, user authentication, currentAuthenticatedUser.

## Issue

We've noticed that `currentAuthenticatedUser` was returning wrong user attributes, specifically `email_verified` was returned as `false` instead of `true`. 

Checking in the AWS console or querying Cognito via AWS CLI gave us the right attribute value instead.

## How our app works

Our app works in this way

1. Sign up via amplify in the front-end (at this stage `email_verified` will be false)
2. immediately after, the front-end calls our backend that sets the `email_verified` attribute to `true`. (Omitting the why and the countermeasures for brevity)
3. if we call `Auth.currentAuthentifcatedUser()` now we get `email_verified=false` (*unexpected behavior*)
4. if we call it bypassing the cache`Auth.currentAuthenticatedUser({ bypassCache: false })` we get `true` which is the *expected behavior*

### How we initialize Amplify

```js
Amplify.configure({
    Auth: {
      identityPoolId: process.env.CUSTOMER_ACCOUNT_IDENTITY_POOL_ID,
      region: process.env.CUSTOMER_ACCOUNT_COGNITO_REGION,
      userPoolId: process.env.CUSTOMER_ACCOUNT_USER_POOL_ID,
      userPoolWebClientId: process.env.CUSTOMER_ACCOUNT_WEB_CLIENT_ID,
    },
    Analytics: {
      disabled: true,
    },
  });
```

# Questions

1. Am I right saying that Amplify caches the user attributes (just those?) by default?
2. Does `currentUserInfo` has the same behavior
3. Is this cache stored somewhere in the browser correct?
4. Can you recommend a better way of getting those attributes? given the way our app works (see above)
5. Does the cache expire after some time or in case of some other event?

Tagging @powerful23  since I've seen a slightly similar issue (https://github.com/aws-amplify/amplify-js/issues/2389) you were involved in.

**Comment by haverchuck** [comment]
1. Yes, user attributes are cached.
2. I believe currentUserInfo will use the cache.
3.  Local storage.
4.  There is a function on the CognitoUser called getUserData which you may be able to use with the bypassCache option.  I believe that it will get the updated attributes, cache them, or clear the cache if the session is expired.
5.  Yes, there are scenarios in which cached attributes are removed.

**Comment by giulioambrogi** [comment]
Thanks for your answer @haverchuck . Could you be more specific on 5. please? What are the scenarios?

**Comment by imhashir** [comment]
Any update on this issue?
I am also facing this in an angular app I am working on.

**Comment by pmirandaarias** [comment]
Me too, users has to logout and login to get the updated values from Cognito
