### ISSUE TITLE
Android: onNotificationOpened not called from cold boot

### ISSUE THREAD

**Issue by denchp** [aws-amplify/amplify-js#3742]
**Describe the bug**
It appears the the onNotificationOpened is not triggered when the app is not in the background (i.e., Cold Boot).

With a warm boot I'm able to access the notification and handle it accordingly, with a cold boot I see the notification event:

I/emit: notification opened: Bundle[{pinpoint.url...
But Linking.getInitialURL() is empty, and the onNotificationOpened() is never called.

RN version 59.9
Amplify version: 1.1.28
Amplify RN version: 2.1.12

**Expected behavior**
onNotificationOpened is called with the notification object - even from a cold boot.
or
getInitialURL() returns the URL of the notification (currently in notification[pinpoint.url])

**Comment by ferhatbilgic** [comment]
Hi, 

Could you be able to solve this issue? @denchp
