### ISSUE TITLE
Amplify.API lambda "No Current User" crash

### ISSUE THREAD

**Issue by jadbox** [aws-amplify/amplify-js#3746]
**Describe the bug**
In the browser, when I used the `Cognito Unauthorized` 'guest' login authentication type, most things seem to work, except when calling Amplify.API to call a lambda function. The lambda function is allowed to be invoked from the IAM Unauthorized Role.

**To Reproduce**
1. Authenticate as an unauthorized cognito pool user
2. Try to call a lambda function that is allowed to be invoked from the unauth'ed role
3. Error is shown `No current user`. However there's no stack trace (for some async reason).

**Expected behavior**

**Screenshots**
n/a

**Additional context**
I noticed for AppSync, there's an option for IAM authentication type that allows for cognito unauth'ed access. Maybe it's also needed for the Rest API?

**Sample code**
N/a

Debug log:
```
[DEBUG] 34:57.993 AuthClass - Getting current session
ConsoleLogger.ts:82 [DEBUG] 34:57.999 AuthClass - Failed to get user from user pool
ConsoleLogger.ts:88 [DEBUG] 34:57.999 AuthClass - Failed to get the current user No current user
```

**Comment by jadbox** [comment]
I've seen a fix for appsync using this config, although it doesn't seem to apply to the Rest API.

 'aws_appsync_authenticationType': 'AWS_IAM',
Referenced here: https://github.com/aws-amplify/amplify-js/issues/2967

**Comment by jadbox** [comment]
Closing... my original code was adding the header:
`Authorization: ((await Auth.currentSession()) as any).idToken.jwtToken`
which is no longer needed as I'm switching to IAM authentication type on API gateway. Removing this header fixed the issue.

**Comment by undefobj** [comment]
@jadbox I've seen a few people stumble with this issue in the past. Is there any further documentation or clearer explanation we could add to the REST section to avoid this in the future? https://aws-amplify.github.io/docs/js/api#custom-request-headers
