### ISSUE TITLE
Email address updates without verifying it

### ISSUE THREAD

**Issue by Christilut** [aws-amplify/amplify-js#3749]
**Describe the bug**
I'm letting the user change his email using the code below. The user gets a verify email but even if they ignore it, the email address seems updated.
The user can login with the new email address and the old email address doesn't exist according to the Cognito error message.

In my user pool the verify attributes radio button is set to "Email".

Maybe I'm doing something wrong but I can't see what.

**Expected behavior**
User should be able to login with old email address if no verifycation action was taken.

`Auth.currentAuthenticatedUser()` should return the old email address.

**Additional context**
```
    "@aws-amplify/auth": "1.2.24",
    "@aws-amplify/cache": "^1.0.27",
```

**Sample code**
```ts
const user = await Auth.currentAuthenticatedUser()

      await Auth.updateUserAttributes(user, {
        'email': this.email,
        'custom:firstName': this.firstName,
        'custom:lastName': this.lastName,
        'custom:countryCode': this.countryCode
      })
      this.$store.commit('auth/setUser', await Auth.currentAuthenticatedUser({ bypassCache: true }))

```

**Comment by diosney** [comment]
https://github.com/aws-amplify/amplify-js/issues/987

**Comment by Christilut** [comment]
Not stale
