### ISSUE TITLE
how to use aws amplify react 

### ISSUE THREAD

**Issue by cullsin** [aws-amplify/amplify-js#3750]
** Which Category is your question related to? **

aws amplify react

** What AWS Services are you utilizing? **
auth

** Provide additional details e.g. code snippets **

Hello, 

I am new to aws amplify react implementation. I have the following question. 

1. How do I embed as a  login page, instead of it occupy the entire screen. How do I add logo and header ?

2. How do I differentiate production configuration as well as development configuration ?

3. How do I access all the logged in credentials across the application ?

Raja K

**Comment by jordanranz** [comment]
@cullsin,

1. You can use the [`Authenticator` component](https://aws-amplify.github.io/docs/js/authentication#using-the-authenticator-component). We are working on creating a better system for customization in [this RFC](https://github.com/aws-amplify/amplify-js/issues/3279). In the meantime you can use [these docs](https://aws-amplify.github.io/docs/js/authentication#customize-your-own-components) to add customized component render logic.
2. This seems like more of an app specific question. Can you elaborate what you mean from an Amplify perspective?
3. I am not sure what you mean by "all logged in credentials across the application"? Do you mean all users logged into the application at any given time or just the credentials of the logged in user? If the latter, you can use `Auth.currentAuthenticatedUser()` to retrieve the current authenticated user and `Auth.currentCredentials()` to get the current user credentials.

**Comment by Lucas-Geitner** [comment]
@cullsin you may have a look to this repository by @jpeddicord 💯  

https://github.com/aws-samples/aws-amplify-auth-starters

**Comment by jpeddicord** [comment]
Not mine, FYI. I only initialized the repository for our developers that needed it. :)
