### ISSUE TITLE
Updating @aws-amplify/storage from 1.0.31 to 1.0.33 gives an "AccessDenied: Access Denied" error on `.put`

### ISSUE THREAD

**Issue by philiiiiiipp** [aws-amplify/amplify-js#3752]
**Describe the bug**

It seems as #3051 is happening again.

The custom prefixes are getting ignored.

**Comment by sammartinez** [comment]
Seems to be a bug related issue, will look into this and report back

**Comment by sammartinez** [comment]
@philiiiiiipp Just want to make sure, from the [customization section in Storage](https://aws-amplify.github.io/docs/js/storage#customization) are your IAM policies up to date?

**Comment by jordanranz** [comment]
Closing in favor of https://github.com/aws-amplify/amplify-js/issues/3759
