### ISSUE TITLE
Missing required parameter Session MFA.

### ISSUE THREAD

**Issue by drodriguez56** [aws-amplify/amplify-js#3756]
** Which Category is your question related to? **
**Authentication**
Amplify [Authentication](https://aws-amplify.github.io/docs/js/authentication#authentication).

** What AWS Services are you utilizing? **
AUTH with MFA enable.

** Provide additional details e.g. code snippets **

MFA setup with: SOFTWARE_TOKEN_MFA

In some cases a user that has MFA enabled and has been able to login in the past gets a null session error and is not able to perform the user challenge for MFA anymore.

The MFA process fails on the confirmSignIn helper.

``` 
const loggedInUser = await Auth.confirmSignIn(
      user,
      creds.code,
      'SOFTWARE_TOKEN_MFA',
);
token = loggedInUser.signInUserSession.idToken.jwtToken;
```

Response 400: 
```
  message: "Missing required parameter Session"

  __type: "InvalidParameterException"
```
I can see in the request payload that session is null:
```
{ChallengeName: "SOFTWARE_TOKEN_MFA",…}
ChallengeName: "SOFTWARE_TOKEN_MFA"
ChallengeResponses: {USERNAME: "00bc7658-19fb-4a9a-a919-03070244a1e5", SMS_MFA_CODE: "229077",…}
SMS_MFA_CODE: "229077"
SOFTWARE_TOKEN_MFA_CODE: "229077"
USERNAME: "00bc7658-19fb-4a9a-a919-03070244a1e5"
ClientId: "3c7q9ak9d95ebssd8brmbabri7"
Session: null
```

I cannot replicate this issue but it has happen to 2 of the active accounts that have MFA enabled. They worked at some point but then the confirmSignIn function started returning a Session null error.

We were able to reenable MFA  by deleting the account on the cognito pool and setting it up again.

**Comment by elorzafe** [comment]
@drodriguez56 I was able to reproduce your concern. 

If  the user has No MFA selected  and is trying to do `Auth.confirmSignIn`  the attribute `Session` will be `null`. Let me know if you have any other concerns otherwise I will close the issue.

Thanks for your question

**Comment by elorzafe** [comment]
We will mark this as feature-request to improve error messages when `Auth.confirmSignIn` is invoked but No MFA was configured for that user.

**Comment by elorzafe** [comment]
@drodriguez56 You can follow [this guide](https://aws-amplify.github.io/docs/js/authentication#sign-in) to configure confirmSignIn on your app

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), we highly recommend updating to the most recent version. Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
