### ISSUE TITLE
Storage global configuration does not accept `customPrefix`

### ISSUE THREAD

**Issue by aldo-roman** [aws-amplify/amplify-js#3759]
**Describe the bug**
A check on configuration is preventing `customPrefix` attribute to be included in Storage global configuration:

https://github.com/aws-amplify/amplify-js/blob/799a1cfe59f7244f1cc51bdc0220a6c4ebf81455/packages/storage/src/Storage.ts#L121

According to `storageArrayKeys`, `customPrefix` is expected, and is an object according to docs. See also #3368

**To Reproduce**
1. Config Amplify as:
```ts
Storage.configure({
    ...
    level: 'public',
    customPrefix: {
        public: ''
    }
});
```
2. Run app
3. Upload a file to S3
4. File gets uploaded to `/public` dir

**Expected behavior**
File gets uploaded to root dir

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Version: `"@aws-amplify/storage": "^1.0.33"`

**Comment by jordanranz** [comment]
Related: https://github.com/aws-amplify/amplify-js/issues/3752

**Comment by sammartinez** [comment]
@aldo-roman  Working on a fix now, should be up shortly
