### ISSUE TITLE
aws-amplify-react: Handle withOAuth errors when using other OAuth providers

### ISSUE THREAD

**Issue by zjullion** [aws-amplify/amplify-js#3763]
**Is your feature request related to a problem? Please describe.**
In `aws-amplify-react`, when using the `withOAuth` HOC to wrap a component, logging in to other OAuth providers throws an uncatchable error (this error occurs outside of the React lifecycle). This happens because `withOAuth` tries to use any `access_token` passed in the URL, which obviously doesn't work when that token is not an AWS Cognito token.

**Describe the solution you'd like**
There are a few options here (and multiple of them could be implemented at the same time):
1. Set some variable in local storage so that amplify knows when the "current login" is a Cognito login, and only tries to parse out the `access_token` in that case. Otherwise, ignore any `access_tokens`s passed in the URL.
2. Provide a hook into `withOAuth` such that errors like these can be handled.

**Describe alternatives you've considered**

**Additional context**
It may seem strange that we're using multiple OAuth providers in our application, but we need access to multiple unrelated services. As such, we're using AWS Cognito (with SAML on the back-end) for the "primary" login to our application, and then grabbing `access_tokens` for other services as we need them.
Additionally, the error thrown looks like this:
```
Uncaught (in promise) TypeError: Cannot read property 'accessToken' of undefined
    at AuthClass.<anonymous> (Auth.js:2178)
    at step (Auth.js:137)
    at Object.next (Auth.js:67)
    at fulfilled (Auth.js:19)
```

**Comment by sammartinez** [comment]
Thanks @zjullion for the feedback. I can understand your use case for this, gonna mark this as a feature request

**Comment by tannerabread** [comment]
Hi 👋 Closing this as resolved. This package is now deprecated. We recommend that you migrate to the new amplify UI library.

Thank you!
