### ISSUE TITLE
How to store data in RDS after a User/Media item have been successfully created through Cognito/S3

### ISSUE THREAD

**Issue by packerfan626** [aws-amplify/amplify-js#3764]
Currently, I am building a React Native project and I am using AWS Amplify as the main source of communication to AWS. I have Cognito and S3 set up and I am able to successfully create Users (Cognito) and Videos (S3); however, when an user/media item is successfully created I want to store their reference within the MySQL database that we have created. I explored the idea about using triggers to store the data, but those do not send a response back to the front-end and I want the frontend to behave appropriately depending on if the user/media item was successfully inserted into both cognito/s3 AND the database. For example, if a user is created in cognito but for some reason is not created in the database I want to be able to detect that and display an error message on the front-end and remove the account from cognito.

This could potentially be the wrong way to do this so any type of guidance is appreciated.

**Comment by packerfan626** [comment]
Would love some feedback on this

**Comment by manueliglesias** [comment]
Hi @packerfan626 

Can you elaborate a little bit more on your use case? Also, which triggers did you explore? the [Cognito ones](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html) or the [S3 ones](https://docs.aws.amazon.com/lambda/latest/dg/with-s3.html)?

**Comment by packerfan626** [comment]
> Hi @packerfan626
> 
> Can you elaborate a little bit more on your use case? Also, which triggers did you explore? the [Cognito ones](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html) or the [S3 ones](https://docs.aws.amazon.com/lambda/latest/dg/with-s3.html)?

Hey @manueliglesias , thanks for the reply!

Basically, let's say I have a new user on the application and I am using Cognito to login, register, etc. I have a User table in my RDS database where I store basic information about the user including their Cognito ID as the primary key. I use this ID as a variable in many different spots too, like in a 'BlogPosts' table, where I'll have the CognitoID as the author. My goal was to, upon signup, that I would store the newly user in my User table with their CognitoID. I originally tried the Cognito post-signup trigger; however, I noticed that with the triggers it does not return a pass/fail to the front-end when a user gets signed up successfully. This makes it complicated because if for whatever reason the trigger fails, I want to be able to handle that appropriately on the front-end (i.e display an error).  This is to just ensure that every user that has signed up, had a record successfully created in my database as well.

Same applies to S3; however, we had that resolved in this thread.[#3794](https://github.com/aws-amplify/amplify-js/issues/3794)

Please let me know if my use case was not clear enough.

**Comment by packerfan626** [comment]
@manueliglesias , hope you had a great weekend! Do you happen to have any feedback on this?

**Comment by haverchuck** [comment]
@packerfan626 Is there any reason why you could not write the post-signup trigger to wait for the insertion of the record into the database before responding, and then send an error in the event of failure (I'm assuming that the database can respond with an error)?  

For example, here is the template that the[ Amplify CLI ](https://aws-amplify.github.io/docs/cli-toolchain/quickstart#adding-a-lambda-trigger) uses for an [email-blacklist PreSignUp trigger](https://aws-amplify.github.io/docs/cli-toolchain/cognito-triggers#email-domain-filtering-blacklist-and-email-domain-filtering-whitelist) that responds with an error if the user tries to sign up with an invalid domain:

```
exports.handler = (event, context, callback) => {
  // blacklisted domains
  const bld = process.env.DOMAINBLACKLIST.split(',').map(d => d.trim());
  const { email } = event.request.userAttributes;
  const domain = email.substring(email.indexOf('@') + 1);

  if (bld.includes(domain)) {
    callback(new Error(`Invalid email domain: ${domain}`), event);
  } else {
    callback(null, event);
  }
};
```
The call to Cognito responds with this...
![image](https://user-images.githubusercontent.com/10621276/66146901-905de700-e5c2-11e9-8d40-5493df4b59f6.png)

...and I am able to surface the error in my app like so:
![image](https://user-images.githubusercontent.com/10621276/66146947-a4a1e400-e5c2-11e9-8b69-f9372fefc712.png)
