### ISSUE TITLE
Erro with I18n when opening react-native app on the web

### ISSUE THREAD

**Issue by rodhoff** [aws-amplify/amplify-js#3766]
**Describe the bug**
I18n is raising an exception because of unexistent dict when opening the project with expo on the web -  but it does not happen on Android. 

**To Reproduce**
Run app on web mode

**Expected behavior**
App to work properly

**Screenshots**
![image-5](https://user-images.githubusercontent.com/13082760/62155436-42d1af00-b2df-11e9-866f-67aedc4cd6df.png)

**Comment by sammartinez** [comment]
@rodhoff Can you clarify for what you mean by `web mode` ? For expo, I know there is a iOS simulator that you would use and Android Studio. I wasn't aware of a `web mode` for expo minus the locahost port that is opened so wanted to understand more on this.

**Comment by sammartinez** [comment]
Also, please provide what version of `aws-amplify-react-native` and `expo` version you are using.

**Comment by rodhoff** [comment]
Hi @sammartinez, basically its when you use the "w" option in expo to make the app available in a web port - just hit "w" when it finishes bundling. Aws-amplify-react-native is 2.1.16 and expo-cli is 3.0.6

**Comment by sammartinez** [comment]
@rodhoff 
From looking that the screenshot, I am seeing that the code is slightly different then what we have in our [code base](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react-native/src/AmplifyI18n.js#L14). Can you look to wipe out your `node_modules` and reinstall

**Comment by rodhoff** [comment]
Ok but basically you mean uninstalling amplify and reinstalling once again?

**Comment by sammartinez** [comment]
@rodhoff yes via the `node_modules`. You can do `rm -rf node_modules` from your `src` folder or depending on where your `node_modules` are located and then a `npm install` or a `yarn` command depending on your build process.
