### ISSUE TITLE
Confirm sign up empty code

### ISSUE THREAD

**Issue by springcoil** [aws-amplify/amplify-js#3771]
**Describe the bug**
When using email and password with amplify the `auth.ConfirmSignUp` part doesn't work as part of the workflow. 

**To Reproduce**

My logs.
email x@googlemail.com
authCode_passcodescreen 716541
Authcode before signin 716541
Error when entering confirmation code:  Code cannot be empty
authCode 716541
email px@googlemail.com
authCode_passcodescreen 111111
Authcode before signin 111111
Error when entering confirmation code:  Code cannot be empty
authCode 111111

Here is the authentication piece of code. 
```export const confirmSignUp = (email, authCode, navigation) => async () => {
  console.log("Authcode before signin", authCode);
  await Auth.confirmSignUp({ username: email, authCode: parseInt(authCode) })
    .then(data => {
      console.log("data", data);
      navigation.navigate("SignIn");
      console.log("Confirm sign up successful");
    })
    .catch(err => {
      if (!err.message) {
        console.log("Error when entering confirmation code: ", err);
        console.log("authCode", authCode);
        Alert.alert("Error when entering confirmation code: ", err);
      } else {
        console.log("Error when entering confirmation code: ", err.message);
        Alert.alert("Error when entering confirmation code: ", err.message);
      }
    });
};```
And the pertinent code from the Passcode part of the screen.

``` async confirmSignUp() {
    if (
      this.state.passCode1 == -1 ||
      this.state.passCode2 == -1 ||
      this.state.passCode3 == -1 ||
      this.state.passCode4 == -1 ||
      this.state.passCode5 == -1 ||
      this.state.passCode6 == -1
    ) {
      Alert.alert("Please enter 6 digit passcode.");
    } else {
      //let { state } = this.props.navigation;
      //   console.error();
      //const {username, authCode} = this.state
      //const { username } = this.state;
      let email = this.state.email;
      console.log("email", email);
      let authCode =
        this.state.passCode1 +
        "" +
        this.state.passCode2 +
        "" +
        this.state.passCode3 +
        "" +
        this.state.passCode4 +
        "" +
        this.state.passCode5 +
        "" +
        this.state.passCode6;
      //let authCode2 = parseInt(authCode);
      console.log("authCode_passcodescreen", authCode);
      this.props.confirmSignUp({ username: email }, authCode, this.props.navigation);
    }
  }
```

**Expected behavior**
Previously when I was using username, this code worked. I'm confused why the authCode is printed to the logs but isn't being passed around. 

https://github.com/aws-amplify/amplify-js/issues/1924 seems to be a similar issue. 
**Screenshots**
<img width="391" alt="Screenshot 2019-07-30 15 32 19" src="https://user-images.githubusercontent.com/983944/62209075-7587b000-b390-11e9-9e45-9681be629116.png">

Using the IPhone simulator with Iphone 7. On my Mac OSX. 
   ``` "Demographic": Object {
      "AppVersion": "ios/12.2",
      "Make": "iPhone",
      "Model": "iPhone 6/7/8 plus",
      "ModelVersion": "12.2",
      "Platform": "ios",
    }
```
***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by dabit3** [comment]
Not sure if I'm reading this wrong, but I think that Auth.confirmSignup needs to have just the strings passed in as args, i.e. instead of:

```
Auth.confirmSignUp({ username: email, authCode: parseInt(authCode) })
```

Try 
```
Auth.confirmSignUp(email, parseInt(authCode))
```

**Comment by springcoil** [comment]
Ok thanks.

**Comment by sammartinez** [comment]
@springcoil Does @dabit3 answer solve your issue? Just want to confirm prior to closing this issue out. Let us know

**Comment by springcoil** [comment]
So it's a bit strange I don't think his code solution fixed my issue, however I do think just time fixed the issue. Is that possible? Was there some sort of Cognito update?

**Comment by dabit3** [comment]
Hey @springcoil, re: __just time fixed the issue__, can you elaborate? Thanks,

**Comment by springcoil** [comment]
Well the bug seemed to disappear. Maybe a caching issue or something?

**Comment by dabit3** [comment]
Ah ok got it. No, I'm not sure why it would start working now when it did not before.

For anyone here with similar issues in the future, check out the API for confirmSignUp [here](https://aws-amplify.github.io/amplify-js/api/classes/authclass.html#confirmsignup).

**Comment by rajinonnet** [comment]
Hey @springcoil, I am also getting the same error, I converted the **verification code** in to **int** before call, still no luck ? 

Guys anyone still getting the same error ? 

![image](https://user-images.githubusercontent.com/64529654/91761271-3ad6f380-ebf2-11ea-92bd-c46e3f0ad7d0.png)



```
        try { 
          console.log("........2.....handleVerificationCode. : ");
          console.log(parseInt(this.state.verificationCode));

          let codeInt = parseInt(this.state.verificationCode);
          const confirmSignUpResponse = await Auth.confirmSignUp(
                    {
                        username:this.state.email,
                        code:codeInt 
                    } 
               );
                console.log(confirmSignUpResponse);
        } catch (error ) {
            console.log("ERROR OCCURRED !!! ! ! !  ! ");
            this.setState({
              errors: { ...this.state.errors,cognito:error }
            });
        }

```

**Comment by s-g-r** [comment]
@rajinonnet I have also come across this issue, I have not parsed to int for verification codes when a user originally signs up, however custom auth flows that need to access to forgot password functionality giving the same error.

**Comment by rajinonnet** [comment]
@s-g-r 

You should not convert into INT. If the verification code entered by user is "000891" it will be converted into 891 and authentication will fail ultimately.

Just take the input from UI as it is and send it exactly as follows. It works like a charm.

`const confirmSignUpResponse = await Auth.confirmSignUp(this.state.email,this.state.verificationCode) ;`
