### ISSUE TITLE
Provide compatibily and examples for Rollup

### ISSUE THREAD

**Issue by artecoop** [aws-amplify/amplify-js#3773]
Hello Amplify team,
I'd love to see support for rollup bundler and similar software, beside webpack. Although the examples with angular or react are great, I'm trying to achieve integration with a simple vanilla javascript + rollup.
Consider this for the upcoming release of version 2.0.0

**Comment by sammartinez** [comment]
@artecoop I did want to link the [RFC](https://github.com/aws-amplify/amplify-js/issues/3365) for our modularization where you can call this out as well. Going to mark this as a feature request, feel free to close this if you add your thoughts to the RFC.

**Comment by artecoop** [comment]
@sammartinez Thanks!

**Comment by sw-yx** [comment]
for those finding this from the future, the modularization effort shipped in April 2020 and you can use Amplify with Rollup with a few small tweaks: https://dev.to/swyx/making-aws-amplify-work-with-rollup-2d9m
