### ISSUE TITLE
How to refresh access and identity tokens with implicit grant type

### ISSUE THREAD

**Issue by colehendo** [aws-amplify/amplify-js#3774]
** Which Category is your question related to? **

Refreshing access and identity tokens after authenticating through Cognito with Implicit Grant type using Google

** What AWS Services are you utilizing? **

Cognito with Implicit Grant type

** Provide additional details e.g. code snippets **

I have found no way to refresh the access and identity tokens provided by authenticating using Cognito with an Implicit Grant type while using a Google. I know the Authorization Code Grant type returns a refresh token, but that is not an option for me as I am building an SPA. I was hoping either there was a way to get a refresh token or to do a silent refresh with Implicit Grant type as I have found none yet. Having my users log in every hour is fairly annoying for them.

**Comment by sammartinez** [comment]
@colehendo Can you share your `package.json` with us? Just want to see what version of amplify you are using and what framework

**Comment by colehendo** [comment]
I am only using auth and core. Here are the versions:

```
"@aws-amplify/auth": "^1.2.28"
"@aws-amplify/core": "^1.0.29"
```

**Comment by manueliglesias** [comment]
Hi @colehendo 

As of today, Cognito doesn't support silent auth. We'll be talking to the Cognito team about this feature request

**Comment by niklr** [comment]
Can you provide some sort of timeline when this is gonna happen @manueliglesias ? Thanks!
