### ISSUE TITLE
Customize Error Messages amplify-authenticator ionic angular v4

### ISSUE THREAD

**Issue by togro** [aws-amplify/amplify-js#3782]
** Which Category is your question related to? **

Authentication

** What AWS Services are you utilizing? **

cognito using amplify angular-ionic

** Provide additional details e.g. code snippets **

How i can use this  :

https://aws-amplify.github.io/docs/js/authentication#customize-error-messages
-----------------------------------------------
_Customize Error Messages
During authentication flows, Amplify handles error messages returned from the server. Amplify provides a simple way of customizing those error messages with a messageMap callback.

The function takes the original message as arguments and then outputs the desired message. Check AmplifyMessageMap.js file to see how Amplify makes the map function.

const map = (message) => {
    if (/incorrect.*username.*password/i.test(message)) {
        return 'Incorrect username or password';
    }

    return message;
}

<Authenticator errorMessage={map} />
You may notice in AmplifyMessageMap.js it also handles internationalization. This topic is covered in our I18n Guide._
-----------------------------------------------

### Example :

**<amplify-authenticator framework="ionic" [errorMessage]="map"></amplify-authenticator>**

But that not is working on ionic-angular v4

I see on : 

https://github.com/aws-amplify/amplify-js/tree/master/packages/aws-amplify-angular/src/components/authenticator

But not exists an input Decorator for : errorMessage={map}

**Comment by satishmolletipipra** [comment]
Still the issue is there but i don't know why it is closed without solution.
