### ISSUE TITLE
Cannot use some characters in OAuth custom state

### ISSUE THREAD

**Issue by stevearoonie** [aws-amplify/amplify-js#3783]
**Describe the bug**

Release: 1.1.34

When using OAuth custom state the Amplify code is comparing an unencoded stored state with an incoming encoded state so validateState fails, causing login to fail.  

**To Reproduce**
1. Call Auth.federatedSign with a customState parameter that contains characters that would be encoded in a query parameter (e.g. Auth.federatedSignIn({ provider, customState: '/activities' })).
2. Attempt to log in using OAuth
3. Log in fails with Error: Invalid state in OAuth flow

**Expected behavior**
Log in is successful and the custom state is available to be used

**Desktop (please complete the following information):**
 - OS: Mac OS/X
 - Browser: Chrome

**Additional context**
When adding a customState of '/activities' to use as a redirect after login, validateState ends up comparing the incoming '%2Factivities' from the sign-in redirect with '/activities' from oAuthStorage. I tried passing in '%2Factivities' as the customState instead but this just ended up getting encoded twice. The fix that worked was to change OAuth.authSignIn to encode the state when storing it in oAuthStorage, e.g. oAuthStorage.setState(encodeURIComponent(state));

**Comment by manueliglesias** [comment]
Thanks for the contribution @stevearoonie 😃 I'll be taking a look at the PR

**Comment by manueliglesias** [comment]
Closed by #3784
