### ISSUE TITLE
Error when trying to save any changes to my userpool

### ISSUE THREAD

**Issue by ZalgirisKaunas** [aws-amplify/amplify-js#3787]
When I try to save any changes to my user pool I always get an error that says Your roles are still being created. Please wait and try again. I have a grayed out role in the bottom of MFA settings but MFA is turned off so I'm not sure how it's related.

I've also tried creating dummy pool with the same mfa role name as the grayed out role in my primary pool and I've also extracted externalId from the current pool using this command:

> aws cognito-idp get-user-pool-mfa-config --user-pool-id=XXXX

I'm just not sure where to put that ID

**Comment by elorzafe** [comment]
@ZalgirisKaunas thanks for your question, but this repo is for Amplify related questions. For the issue you mention I suggest you to create on [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=173)
