### ISSUE TITLE
Pub/Sub - "Pluggable being added is not one of the Predictions Category"

### ISSUE THREAD

**Issue by jbesw** [aws-amplify/amplify-js#3791]
**Describe the bug**
Since the Predictions feature was released, if you run the steps on https://aws-amplify.github.io/docs/js/pubsub to run Pub/Sub, you get an error in the console: "Predictions.js?c999:49 Uncaught Error: Pluggable being added is not one of the Predictions Category."

**To Reproduce**
1. Create a new project, then npm i amplify.

2. In a new JS file, enter:
import Amplify, { PubSub } from 'aws-amplify';
import { AWSIoTProvider } from '@aws-amplify/pubsub/lib/Providers';
// Apply plugin with configuration
Amplify.addPluggable(new AWSIoTProvider({
     aws_pubsub_region: '<YOUR-AWS-REGION>',
     aws_pubsub_endpoint: 'wss://xxxxxxxxxxxxx.iot.<YOUR-AWS-REGION>.amazonaws.com/mqtt',
   }));

(add valid endpoints)

2. Run the code, and you get the "Pluggable being added is not one of the Predictions Category" error in the browser console.

**Expected behavior**
This should configure and connect the Pub/Sub library as before.

**Screenshots**
![image](https://user-images.githubusercontent.com/24660852/62326126-5e71bc80-b47b-11e9-8ad6-54b2dd39f9ec.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 75.0.3770.142

**Comment by elorzafe** [comment]
@jbesw thanks for reporting, This issue was solved with latest release aws-amplify (1.1.35)
