### ISSUE TITLE
Access denied in storage get request with download true.

### ISSUE THREAD

**Issue by abhilashbr92** [aws-amplify/amplify-js#3795]
Hello,
I am using Amplify in my Angular project. I have followed the steps in this [document](https://aws-amplify.github.io/docs/js/angular) to upload the files in S3.
Using Amplify I am able to:
1. Upload file to S3.
2. List all files uploaded.
3. Delete file in S3

But when I try to download the file, the error I get is:
`
https://XXXX.s3.XXXX.amazonaws.com/public/angular.png 403 (Forbidden)
`
`error => AccessDenied: Access Denied`

Below is the code I am using to download the file:
`
      Storage.get('angular.png', { download: true,  level: 'public' })
        .then((result) => {
          console.log('success =>', result);
        })
        .catch((err) => {
          console.log('error =>', err);
        });
`

If I make request as `Storage.get('angular.png', { download: false,  level: 'public' })` then I get a successful response as :

 `success => https://XXXX.s3.XXXX.amazonaws.com/public/angular.png?X-Amz.......`

How can I download the file from S3 using amplify? 

Can somebody please help me out. 

Thanks,
Abhilash

**Comment by elorzafe** [comment]
@abhilashbr92 can you see the file on the s3 bucket on that specific path `public/angular.png`

if you use `S3Image` and use the same key is not showing the image?
