### ISSUE TITLE
Federated sign in with organization's email only

### ISSUE THREAD

**Issue by dzeno** [aws-amplify/amplify-js#3796]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
Hi, 

I have an IdentityPool already created with AWS Cognito and Google client ID. The sign-in should only work with the company's email. Also, users should only be able to do `sing in`, not sign up. This works with the company's email as expected, but I am able to sign in with a `regular gmail as well` which definitely should not happen. Here is my code:

```
import Amplify from 'aws-amplify';
import { withAuthenticator, SignIn } from 'aws-amplify-react';

Amplify.configure({
    Auth: {
        identityPoolId: 'eu-west-xxx:xxxxxxxxxxx-xxx-x',
        region: 'eu-west-xxx',
    }
});



const federated = {
  google_client_id: 'xxxxxxxxxxxx.apps.googleusercontent.com',
};
const withAuthApp = withAuthenticator(App, false, [<SignIn federated={federated}/>])

export default withStyles(styles)(withAuthApp);
```

**Comment by haverchuck** [comment]
@dzeno It sounds like there are a couple of separate issues here:
1.  You want to hide the SignUp component, and 
2.  You want to implement an email domain white list, in which only whitelisted email domains are allowed to sign in.

Regarding 1, you should be able to do this with the Authenticator components (see docs [here](https://aws-amplify.github.io/docs/js/authentication#using-the-authenticator-component)).

Example: 
```
import { Authenticator, SignUp } from 'aws-amplify-react'
...
<Authenticator
   hide={[SignUp]}
/><Authenticator>
```

Regarding number 2, how are you expecting the 'gmail' domains to be rejected upon SignIn?  What configuration/implementation have you setup which would lead you to expect this?
