### ISSUE TITLE
aws-amplify-react federatedSignIn with custom provider not working?

### ISSUE THREAD

**Issue by elsenhuc** [aws-amplify/amplify-js#3797]
**Describe the bug**
When using the withOAuth(component) in packages/aws-amplify-react/src/Auth/Provider/withOAuth.jsx I am unable to use the "customProvider" option, which would be possible when looking at the code of Auth.ts of the underlying aws-amplify package (Auth.FederatedSignIn).

It seems that the line 
signIn(_e, provider) {
            Auth.federatedSignIn({ provider });
        }
causes the underlying Auth class to hand over a key-value pair with "provider" as key, which in turn always used the "FederatedSignInOptions " option and never allows for the "FederatedSignInOptionsCustom", as the check in "isFederatedSignInOptionsCustom" checks for the key "customProvider" to be present. I haven't found a way to override it no matter what you pass to "Auth.federatedSignIn".

any help appreciate.
Underlying Auth - types code:

```
export type FederatedSignInOptions = {
    provider: CognitoHostedUIIdentityProvider,
    customState?: string
};

export type FederatedSignInOptionsCustom = {
    customProvider: string,
    customState?: string
};

export function isFederatedSignInOptions(obj: any): obj is FederatedSignInOptions  {
    const keys: (keyof FederatedSignInOptions)[] = ['provider', 'customState'];
    return obj && !!keys.find((k) => obj.hasOwnProperty(k));
}

export function isFederatedSignInOptionsCustom(obj:any): obj is FederatedSignInOptionsCustom  {
    const keys: (keyof FederatedSignInOptionsCustom)[] = ['customProvider', 'customState'];
    return obj && !!keys.find((k) => obj.hasOwnProperty(k));
}
```

**Comment by manueliglesias** [comment]
Hi @elsenhuc 

can you try something like:

```typescript
class MyApp extends Component {
    // ...
    render() {
        return(
            <button onClick={e => this.props.OAuthSignIn(e, 'YOUR_CUSTOM_PROVIDER')}>
                Sign in with AWS
            </button>
        )
    }
}

export default withOAuth(MyApp);
```
