### ISSUE TITLE
Two userpool in same web page

### ISSUE THREAD

**Issue by reckinam** [aws-amplify/amplify-js#3802]
I have building web page for shop owners and customer .Each of them has one user pool .The reason iam using two userpool  is that owner and customer has different custom attributes.What is my problem is how to authenticate between two in same page?Someone help to figure it out.iam new to this?

**Comment by elorzafe** [comment]
@reckinam 

You have two options:
- You could call `Amplify.configure` with the userpool you want to use (Be sure user was already signed out). 

`Auth.configure({ userPoolID: '....', identityPoolId: '...' ,... } );`

- You can have a super set of custom attributes to include what is required for owner and custoemer. And use groups to give permissions (Maybe should have to do the same for first case, if you want to give certain permissions to owner a customer)
