### ISSUE TITLE
Auth.verifyUserAttributeSubmit Lambda trigger

### ISSUE THREAD

**Issue by ghariosk** [aws-amplify/amplify-js#3804]
**Is your feature request related to a problem? Please describe.**
I am frustrated by the fact Auth.verifyUserAttributeSubmit does not trigger a lambda function.

**Describe the solution you'd like**
It would be great if calling Auth.verifyUserAttributeSubmit would trigger a function like PostVerification lambda function in order to save either email or phone number into an RDS or DynamoDB

**Describe alternatives you've considered**
For now, I will have to handle saving the number in a db by calling a lambda myself which is a bit of a hassle and could be made much simpler

**Comment by elorzafe** [comment]
@ghariosk thanks for your feedback, I will mark this as a service-team feature request.

**Comment by ghariosk** [comment]
Great, thanks!

**Comment by andrmoel** [comment]
Any news? I do need the same functionality.

**Comment by haverchuck** [comment]
@ghariosk According to the [Cognito documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-message.html), the `CustomMessage` Lambda trigger has two sources: `CustomMessage_UpdateUserAttribute ` and `CustomMessage_VerifyUserAttribute`. Have you experimented with either of these to see if they suit your use case?  The parameters of userAttributes, so I assume you can get the email or phone from their?

**Comment by nadetastic** [comment]
Following up here - @ghariosk @andrmoel does the solution mentioned by @haverchuck above meet your needs? Do let me know if not, otherwise I'll go ahead and mark this issue closed.

Thanks!
