### ISSUE TITLE
How to prevent on Auth.signOut browser redirect callback

### ISSUE THREAD

**Issue by usmansbk** [aws-amplify/amplify-js#3808]
**Which Category is your question related to?**
Auth, React-Native

**What AWS Services are you utilizing?**
Cognito User Pools with Social Federation
 
**Provide additional details e.g. code snippets**
`import { Auth } from 'aws-amplify';`
`Auth.signOut()` causes the app to open a browser after logging in with ` Auth.federatedSignIn({ provider: "Google" });`. The browser forces a login again.

**Dependencies**
> 
    "aws-amplify": "^1.1.36",
    "aws-appsync": "^1.8.1",
    "aws-appsync-react": "^1.2.9",
    "react-native": "^0.60.4",

**Comment by manueliglesias** [comment]
Hi @usmansbk 

When signing in with Cognito User Pools with Social Federation, you are creating a new session with Cognito User Pools, and the Cognito User Pools Hosted UI takes care of part of the OAuth flow with the social provider. This means that you have a session with the Hosted UI that needs to be terminated when you sign out, that's the purpose of that browser window when calling `Auth.signOut()`

Please take a look at #2115 for more context on this
