### ISSUE TITLE
Authenticator.jsx

### ISSUE THREAD

**Issue by abFx** [aws-amplify/amplify-js#3809]
Authenticator component is triggering a sign out event after coming from HostedUI Google provider, which causes to loose session and a page refresh

**Description**

When we click the google sign in button, we create the oauth URL, and change the webapp location to the prevent opening a popup.

After a successful log in, we get redirected back to the web app, with a session from google.
The hub triggers a signed in state, but after a few miliseconds a signout is triggered.

This might be caused by a logic placed in the component did mount of the Authenticator component.

**Comment by abFx** [comment]
We were doing some tests with a manual confgiration file for amplify.

If the **redirectURLs** and the **responseType** inside the **oauth** property, are inside an array, the issue above can be replicated.

Maybe its not intended, but the code should give some additional feedback on this or do some pre validations before actually loading the config file.

``` 
{
oauth: {
    scope: ["email", "openid", "profile"],
    redirectSignIn: "http://localhost:3000",
    redirectSignOut: "http://localhost:3000",
    responseType: "code",
    domain: "google-so-test-2.auth.eu-west-1.amazoncognito.com"
  }
}
```

**Comment by manueliglesias** [comment]
Hi @abFx 

I think the issue is that you are constructing the url manually. Can you use `Auth.federatedSignIn` instead? Amplify has some CSRF protections (that you won't have if building the url yourself) that I suspect are triggering the sign out
