### ISSUE TITLE
Amplify Auth method for updating device remembered status to suppress MFA.

### ISSUE THREAD

**Issue by cezarcarvalhaes** [aws-amplify/amplify-js#3810]
**Is your feature request related to a problem? Please describe.**
If using a user pool with MFA required and users opt-in for device remembering, there's currently no method in Amplify's Auth class for a device's remembered status in order to toggle suppression of MFA.

**Describe the solution you'd like**
Auth methods for updating device remembered statuses. 

**Describe alternatives you've considered**
I've created a serverless endpoint that uses theCognitoIdentityServiceProvider.updateDeviceStatus method from aws-sdk. It's just that given everything else Amplify can do, it seems odd that these methods aren't already included. For example, Amplify Auth already has setPreferredMFA and getPreferredMFA methods. 

**Additional context**
aws-amplify for javascript.

**Comment by manueliglesias** [comment]
Hi @cezarcarvalhaes 

I am labeling this as a feature request. For now you can try:

```typescript
const user = await Auth.currentUserPoolUser();

await new Promise((resolve, reject) => {
  user.setDeviceStatusRemembered({ // or setDeviceStatusNotRemembered
    onSuccess: resolve,
    onFailure: reject
  })
});
```

Let us know if this helps for now

**Comment by cezarcarvalhaes** [comment]
This is great, thanks @manueliglesias ! I wasn't aware the object returned from currentUserPoolUser had useful methods attached to it. Where would I find this documentation?

**Comment by belgac** [comment]
Is this feature implemented anywhere or is the above snippet still the recommended way to do this?
