### ISSUE TITLE
Auth validation doesn't give -- Attribute value for email must not be null --  error on email ""(empty string)

### ISSUE THREAD

**Issue by imoark** [aws-amplify/amplify-js#3813]
**Is your feature request related to a problem? Please describe.**
Looking at the the sample code provided below, if `email` is "" (empty string), it pass through the Auth validation. Currently, it is only when it's a null, then it won't pass the Auth validation and throws an error of  "Attribute value for email must not be null"
I don't know whether it is a bug, or intended feature that is just lacking of further error handling.

**Describe the solution you'd like**
Should not pass "" (empty string) for email. Just `null` is not adequate for a simple e-mail validation.

**Describe alternatives you've considered**
- "" (empty string) THROW ERROR
- validate e-mail syntax abcde@abc.com

**Sample Code**
```js
import Auth from "@aws-amplify/auth";

const {
      username,
      password,
      email,
} = this.inputs;

if (!Auth || typeof Auth.signUp !== "function") {
      throw new Error("No Auth module found, please ensure @aws-amplify/auth is imported");
    }

const signup_info = {
      username,
      password,
      attributes: {
        email
      }
    };

Auth.signUp(signup_info)
      .then(() => this.changeState("confirmSignUp", username))
      .catch(err => {
        console.log("err", err);
        this.error(err);
      });
```

**Version**
> "aws-amplify": "1.1.36",

**Comment by Amplifiyer** [comment]
@imoark. shouldn't these validations happen in the frontend code? For instance if you are using aws-amplify-react package, there are few validations done on the input type.
I'll follow up with the cognito service team to see if they want to add these validations in the service as well.
