### ISSUE TITLE
Field Level @auth declarations throw errors? 

### ISSUE THREAD

**Issue by CodySwannGT** [aws-amplify/amplify-js#3814]
** Which Category is your question related to? **
API
** What AWS Services are you utilizing? **
AppSync
** Provide additional details e.g. code snippets **

````
type User 
@model 
{
  name: String
  balance: Int @auth(rules: [
    {allow: groups, groups: ["Admins"], operations: [update, create, read]},
    {allow: owner, ownerField: "id", operations: [read]},
  ])
}
````

It appears I get an error if I issue a graphql query for name and balance.

Meaning, I have to issue two different queries depending on whether the logged in user is an admin or not.

Seems to me that if I try to read a particular field and don't have permissions, it should just return null.

**Comment by CodySwannGT** [comment]
Thanks.

Since we're on topic.

Assuming I have an input:

````
input CreateActivityInput {
  id: ID
  createdAt: String
  updatedAt: String
  model: String!
  modelId: ID!
  owner: String
  title: String
  data: String
}
````

And I try to create an activity with a "foo" field - right now the request errors without creating the activity since "foo" was not a valid input field.

Is that the expected behavior?

Likewise, imagine only an "Admins" could set the "data" property above.

Right now, we see an error if a non "Admins" tries to set that property (instead of making the update and ignoring that property).

Is that the expected behavior?

I imagine the answer is "yes" in both cases, but this issue has me questioning myself.

**Comment by manueliglesias** [comment]
Hi @coderbyheart 

Have you tried without the `useQuery` hook? I suspect it might not be working correctly with partial data (try e.g. with plain `client.query(...)` or the [`graphql(...)`](https://www.apollographql.com/docs/react/api/react-apollo/#graphqlquery-configcomponent) HOC)

**Comment by CodySwannGT** [comment]
I have tried it with the client directly with the same results:

````
 apolloClient.query({
      query: gql(getUser),
      variables: {id: cognitoUser.username},
      fetchPolicy: "network-only"
    }),
````

**Comment by CodySwannGT** [comment]
Any joy here? This one is killing us.

**Comment by undefobj** [comment]
What is the error that you're getting? Is it an uncaught promise? If so then you'll need to do something like this:

```
  async function getData() {
    try {
      const results = await API.graphql(graphqlOperation(listPosts))
      dispatch({ type: 'QUERY', todos: results.data.listPosts.items });
    } catch (err){
      if(err.errors[0].errorType === 'Unauthorized' &&
        (err.errors[0].path.indexOf("ssn") > -1)
      ){
        dispatch({ type: 'QUERY', todos: err.data.listPosts.items });
      }
    }
  }
```

This assumes I'm doing field level auth on the `ssn` field, but in general if you're getting an Authorization error which is expected behavior you'll need to catch the promise and then continue on depending on what your business logic dictates (in this case I'm ok with it failing on `ssn` as that's a partial failure).

**Comment by CodySwannGT** [comment]
my results object is an empty object when there is an error.

As stated above, I'm not using the simplified Amplify GraphQL - but AppSync-suggested Apollo package.

[The error is further shown here](https://github.com/aws-amplify/amplify-js/issues/3814#issuecomment-518898452)

**Comment by CodySwannGT** [comment]
Any action here?
