### ISSUE TITLE
ReactNative API Request through Amplify gives wrong Authorization header

### ISSUE THREAD

**Issue by dionsnoeijen** [aws-amplify/amplify-js#3816]
**Describe the bug**
The authorization header contains an undefined parameter resulting in a 403 response from API Gateway.

The endpoint can be called any other way without any issues, only through Amplify it goes wrong.

**To Reproduce**
Create a new API in API Gateway that requires not authorization. Add this code to your react native application:

```
let apiName = 'movieproject';
let path = '/test/products';
let myInit = {
  headers: {},
  response: true,
  queryStringParameters: {}
};

API.get(apiName, path, myInit).then(response => {
  console.log(response);
}).catch(error => {
  console.log(error.response)
});
```

This gives the following header:
```
Authorization: "AWS4-HMAC-SHA256 Credential=undefined/20190807/eu-central-1/execute-api/aws4_request, SignedHeaders=host;user-agent;x-amz-date;x-amz-date, Signature=2b83878b03f57f80d75600f2e3d17e79e6416d97be853b88137f6a7c1515d9fb"
```
Notice the Credential=undefined

This produces a 403 response:
`data: {message: "The security token included in the request is invalid."}`
```
headers:
content-length: "68"
content-type: "application/json"
date: "Wed, 07 Aug 2019 12:36:01 GMT"
via: "1.1 d00e6ccb045db62e301eb5e1415cca17.cloudfront.net (CloudFront)"
x-amz-apigw-id: "eDPTwGbDFiAFs8w="
x-amz-cf-id: "HYanK4XptwH1VI-t1SG1FWu6ZbOKudWyaaIH6fpBzVH9SQudYo2M0Q=="
x-amz-cf-pop: "AMS50"
x-amzn-errortype: "UnrecognizedClientException"
x-amzn-requestid: "ea396a81-b90f-11e9-8292-91f46137cf65"
x-cache: "Error from cloudfront"
```

**Expected behavior**
200 response from the api

**Comment by manueliglesias** [comment]
Hi @dionsnoeijen 

Thanks, this's might be a bug in the library, I'll label it as such as soon as we confirm the behavior.

For now, can you try like this:

```diff
let apiName = 'movieproject';
let path = '/test/products';
let myInit = {
-  headers: {},
+  headers: { Authorization: '' },
  response: true,
  queryStringParameters: {}
};

API.get(apiName, path, myInit).then(response => {
  console.log(response);
}).catch(error => {
  console.log(error.response)
});
```

**Comment by manueliglesias** [comment]
I think this is expected behavior but we could clearly call it out in the docs

https://github.com/aws-amplify/amplify-js/blob/b7d2eb97ca4e6023da2253821cf2d26a90773bfb/packages/api/src/RestClient.ts#L119-L120

**Comment by dionsnoeijen** [comment]
Great! Thank you, this works! I think it would be great if this was in the docs.
