### ISSUE TITLE
Using withAuthenticator HOC produces missing font error

### ISSUE THREAD

**Issue by dionsnoeijen** [aws-amplify/amplify-js#3817]
**Describe the bug**
Missing font error

**To Reproduce**
As documented here: https://aws-amplify.github.io/docs/js/authentication#using-withauthenticator-hoc

Try to sign in to the application with the sigh in form that appears. After clicking sign-in this error occurs:
`Unrecognized font family 'Material Icons'`

**Expected behavior**
No error, just continue.

**Screenshots**
![Schermafbeelding 2019-08-07 om 15 43 37](https://user-images.githubusercontent.com/181423/62627681-2b6f7300-b92a-11e9-8828-1b060b92c5fa.png)

**Desktop (please complete the following information):**
 - iOS Simulator Version 10.3 (SimulatorApp-880.5 CoreSimulator-587.35)

**Comment by dionsnoeijen** [comment]
So, this can be solved by adding this lib to your pacakge.json:

`npm i react-native-vector-icons --save`
`react-native link react-native-vector-icons`
`react-native run-ios`

I suppose it would help if this is documented somewhere.

**Comment by manueliglesias** [comment]
Thank you for the report @dionsnoeijen

**Comment by Ashish5591** [comment]
I was able to repro the issue and can confirm linking react-native-vector-icons using the commands below fixes it as @dionsnoeijen suggested. I will update the docs.

```
react-native link react-native-vector-icons
react-native run-ios
```

**Comment by Ashish5591** [comment]
I've merged a PR to update the docs, so going to go ahead and close this issue.
