### ISSUE TITLE
Send test Push notification using Endpoint ID

### ISSUE THREAD

**Issue by rawadrifai** [aws-amplify/amplify-js#3819]
** Which Category is your question related to? **
Push

** What AWS Services are you utilizing? **
Pinpoint, Amplify

** Provide additional details e.g. code snippets **
Hi - I am able to send test messages from pinpoint using my test device token. I would like to send using the endpoint ID. How do I know what's the device's endpoint ID?

I tried using Analytics.updateEndpoint, and it works, but there is no `id` field in the body.. it's `address` instead. Can my address be any value I want it to be? Do I use the address in the `test messaging` endpoint id field in pinpoint?

**Comment by bneigher** [comment]
What I did is I set the endpoint address to the deviceToken.
```
const deviceToken = await AsyncStorage.getItem(
    "push_token" + Config.AWS_PINPOINT_ANALYTICS_ID
  );
Analytics.updateEndpoint({
   ...,
   address: deviceToken
      ? deviceToken
      : DeviceInfo.getUniqueID().replace(/[-]/g, ""), //fallback (even character length enforcement)
   ...
})
```

That way - you can find the user's device token as easily as you can find their active endpoint
For example:
```
aws pinpoint get-user-endpoints --application-id <Pinpoint_App_id> --user-id <userId>
```

**Comment by rawadrifai** [comment]
Thanks @bneigher! 
I actually did the same. I set the address to be the device token. But when I test messaging from pinpoint console (attached), it's unable to detect the endpoint id (device token). If I choose the device token radio button, and put the device token, it works. 

The whole point of this is so I don't have to save the device token, and I can just go by user ids when sending push notifications.

What are your thoughts?

![image](https://user-images.githubusercontent.com/24530625/62660383-c401f500-b922-11e9-99a7-ce90e6621936.png)

**Comment by rawadrifai** [comment]
btw I am using: `aws-cli/1.12.1 Python/2.7.10 Darwin/18.6.0 botocore/1.8.1` and there is no `get-user-endpoints` command available.

**Comment by rawadrifai** [comment]
not stale

**Comment by idanlo** [comment]
Any updates on this?

**Comment by dantasfiles** [comment]
I wrote up my experiences using endpoints for verification and testing in [Testing Push Notifications with AWS Amplify](https://medium.com/@dantasfiles/testing-push-notifications-with-aws-amplify-9126bd621d3a)

**Comment by ashika01** [comment]
@rawadrifai does @dantasfiles's answer your question?
