### ISSUE TITLE
Server error when trying to login with custom provider federatedSignIn

### ISSUE THREAD

**Issue by MatteoGioioso** [aws-amplify/amplify-js#3824]
**Describe the bug**
Trying to log in with LINE provider and hosted UI, but in the callback I am consistently getting this error: `http://localhost:3000/my_callback?error_description=Exception+processing+authorization+code&state=JjkldwoeuLvp9lvMqevHiEeE8ueTSP6L9&error=server_error`

I have been trying pretty much everything 
- change attributes mapping
- change Allowed OAuth Flows 
- try with different type of scopes
- different responseType

**To Reproduce**
This is my config

```
Amplify.configure({
  Auth: {
    // OPTIONAL - Amazon Cognito User Pool ID
    userPoolId: process.env.REACT_APP_USER_POOL_ID,

    // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
    userPoolWebClientId: process.env.REACT_APP_USER_POOL_CLIENT_ID,

    // OPTIONAL - Enforce user authentication prior to accessing AWS resources or not
    mandatorySignIn: false,

    // OPTIONAL - Manually set the authentication flow type. Default is 'USER_SRP_AUTH'
    authenticationFlowType: "USER_SRP_AUTH"
  }
});
```

```
const oauthConfig = {
  domain: "my-domain.ap-northeast-1.amazoncognito.com",

  // Authorized scopes
  scope: ["email", "openid"],

  redirectSignIn: "http://localhost:3000/login/callback/line",

  redirectSignOut: "http://localhost:3000/logout/callback/line",

  responseType: "code",
};
```

and then I call it from `amplify`
`Auth.federatedSignIn()`

Everything is set according to the instructions and everything is working but then the callback gave me back that error 

**Expected behavior**
Should not get an error

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - Browser Chrome 76
 -  aws-amplify: 1.1.6,

Thanks

**Comment by haverchuck** [comment]
@MatteoGioioso Does it make a difference if you add a trailing slash to the end of the redirect and signout urls in your config and in your live resources?
