### ISSUE TITLE
Focus loss on username/password in expo web

### ISSUE THREAD

**Issue by GeorgeBellTMH** [aws-amplify/amplify-js#3827]
I'm using Authenticator

Focus is being lost on the SignIn and ForgotPassword screens when using expo web (all fields).
Focus is *not* being lost on the SignUp screen when using expo web (all fields).

Happens in Safari, Chrome, Firefox (not able to test any others). Everything works fine in expo android/ios.

From what I can tell the input boxes get focus, but immediately the focus is taken by the text field above them - (not the input above, but the text). This is happening from a global event on body, which if I turn off (in safari's elements->node->focus section) everything is fine...

End result is you can't login on expo web, but you can create a user....

There doesn't appear to be any difference in the creation of the fields between the pages...

**Comment by jordanranz** [comment]
Hey @GeorgeBellTMH,

Could you provide us steps or documentation to spin up an application similar to yours to assist in reproducing this issue. I don't believe expo web is something that we have explored in the past, but I'd like to dig in to whether or not this is something we can support.

Can you also post which versions of Amplify modules you are using?
