### ISSUE TITLE
React Native - Screens showing halfway

### ISSUE THREAD

**Issue by eyalabadi98** [aws-amplify/amplify-js#3829]
**Describe the bug**
I am trying to use flex: 1 to display the custom signin page fully expanded on the screen. It only shows it half way

**To Reproduce**
1. Create custom SignIn Component

**Expected behavior**
I'd like to have full access to the screen. I have disabled greeting just in case that was the issue

**Screenshots**

![image](https://user-images.githubusercontent.com/3536706/62827086-447c5c00-bb96-11e9-9120-eb92f3333c29.png)

**Desktop (please complete the following information):**
 - OS: Max
 - Browser - React Native

**Smartphone (please complete the following information):**
 - Device: Iphone XR
 - OS: 12

**Sample code**

App: 
```
return (
        <Provider store={store}>
          <RootNB>
          <Authenticator
                  onStateChange={(authState) => console.log("State Change", authState)}
                  theme={Theme}
                  includeGreetings={false}
                  hideDefault={true}
                >
                  <SignIn/>
                  <ConfirmSignIn/>
                  <RequireNewPassword/>
                  <SignUp/>
                  <ConfirmSignUp/>
                  <VerifyContact/>
                  <ForgotPassword/>
                  <Loading/>
            </Authenticator> 
            <AppWithNavigationState />
          </RootNB>
        </Provider>
```

**Comment by rajkharvar** [comment]
I can work on it @jordanranz

**Comment by sammartinez** [comment]
@eyalabadi98 Are you still experiencing this issue? Please let us know.
