### ISSUE TITLE
Ionic Authenticator signin fails when browser auto-fills inputs

### ISSUE THREAD

**Issue by david-wallace-croft** [aws-amplify/amplify-js#3831]
**Describe the bug**
Ionic Authenticator signin fails when browser auto-fills inputs.  Error messages include "Username cannot be empty" and "null failed with error Generate callenges lambda cannot be called".

**To Reproduce**
1. Successfully log in.  If browser asks if you want it to memorize input, say yes.
2. Log out.
3. Go back to log in.  Let browser fill in inputs automatically for you.
4. Click on "SIGN IN".
5. See error message "Username cannot be empty"
6. Modify username input by doing at least one keyup event such as retyping first letter of username
7. Click on "SIGN IN".
8. See error message "null failed with error Generate callenges lambda cannot be called"
9. Modify password input by doing at least one keyup event such as retyping first letter of password
10. Click on "SIGN IN"
11. Verify that you have been successfully logged in after doing at least one keyup event in each of the two input fields

**Expected behavior**
Authentication input field values that are pre-filled by the browser should be transferred into the SignInComponentCore component properties "username" and "password" when the "SIGN IN" button is clicked.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Mozilla Firefox

**Additional context**
It looks like the issue is due to the SignInComponentCore code requiring at least one keyup event to transfer input field values to the component properties.  The "SIGN IN" button click event should also transfer the field values to the component properties since there might not be a user keyup event if the field values are automatically filled in by the browser.

![post-signin-error-message](https://user-images.githubusercontent.com/3690308/62839570-33445580-bc51-11e9-9936-2c1baa5037b6.png)

**Comment by jeromeheissler** [comment]
Also with aws-amplify-vue plugin.

**Comment by lapair** [comment]
Also applies to 1password filling out the login details on Chrome on a Mac (on vue plugin)

**Comment by lapair** [comment]
This is still an issue!

**Comment by ranguard** [comment]
This is still an issue please reopen

**Comment by ranguard** [comment]
@jordanranz please could you reopen - thanks

**Comment by david-wallace-croft** [comment]
+1 to reopen

**Comment by PeterBurner** [comment]
+1 to reopen

**Comment by PeterBurner** [comment]
duplicate of https://github.com/aws-amplify/amplify-js/issues/4374
