### ISSUE TITLE
User does not exist

### ISSUE THREAD

**Issue by bartvollebregt** [aws-amplify/amplify-js#3836]
**Describe the bug**
(Using the Authenticator component from aws-amplify-vue)

At first I had this issue: https://github.com/aws-amplify/amplify-js/issues/3484
Which I "fixed" by disabling analytics and using modular imports (not importing 'aws-amplify')

Then I had this weird issue that **sometimes**, when trying to login, it says "User does not exist".
When I remove the last character from the email and type it again it works...
I've double checked the cognito user pool in the aws-exports file with the id in the AWS Console.
The email also matches 100% with the email in cognito.
(also see the gif under screenshots)

This also occurs in Chrome. Both hosted on cloudfront + S3 and locally using vue-cli-service serve (same cognito backend though).

**Expected behavior**
I expect to be signed in and redirected instead of receiving the "User does not exist" message.

**Screenshots**
https://imgur.com/a/fwwZvkI

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Browser Firefox 68

**Sample code**
I'm using the authenticator in the Vue router:

```
import { components, AmplifyEventBus } from 'aws-amplify-vue';
...

const router = new Router({
  mode: 'history',
  routes: [
    {
      path: '/auth',
      name: 'Authenticator',
      component: components.Authenticator,
      props: {
        authConfig,
      },
    },
  ],
});

**Comment by bartvollebregt** [comment]
I've enabled debugging with `window.LOG_LEVEL = 'DEBUG';` 
In the console it now says this (notice the missing last `m` in the email). While clearly there's an `m` in the input field.
```
[DEBUG] 05:50.694 Hub - Dispatching to auth with  
{
  "data": {
    "code": "UserNotFoundException",
    "message": "User does not exist."​,
    "name": "UserNotFoundException"
  },
  "event": "signIn_failure",
  "message": "XXXXXXX@hotmail.co failed to signin"
}
```

**Comment by bartvollebregt** [comment]
I think I have solved the mystery!

When I enter my credentials I tend to use TAB to change to the password field after typing.
This means that I sometimes haven't released the letter `m` yet while pressing TAB.
Now, in the browser, it enters the letter into the input field on `keydown` (or `keypress`).

In the `aws-amplify-vue` `UsernameField` component (`aws-amplify-vue/src/components/authenticator/UsernameField.vue`) it triggers the `usernameChanged` on `keyup`:
```
v-on:keyup="usernameChanged" 
```

Which means that the `signInUsername` data property in the `SignIn` component isn't updated.

This should probably be changed to a Vue native event handler like `@change="onInputChange"` or `@input="onInputChange"`

**Comment by romslf** [comment]
Still not fixed ?
I got the same issue

**Comment by easiruwa** [comment]
Hi, I'm having this same issue. Any updates or fixes?

**Comment by romslf** [comment]
Yes currently using this, hope it can help you:
```javascript 
function patchSignIn () {
	let usernameComponent = Vue.component('amplify-username-field')
	let watches = usernameComponent.options.watch = usernameComponent.options.watch || {}
	watches.username = function () {
	  this.usernameChanged()
	}
	watches.email = function () {
	  this.emailChanged()
	}
  }
  patchSignIn()
```

**Comment by ashika01** [comment]
Could you all try the new UI component - `@aws-amplify/ui-vue` and let us know if you are facing this issue? https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue

**Comment by ashika01** [comment]
We are soon to go into maintenance mode for `aws-amplify-vue` and working on getting `@aws-amplify/ui-vue`. If this is a bug in new UI as well, we are actively making changes to that now.

**Comment by finalwombat** [comment]
Still having this issue with the latest version 0.2.34. @romslf's hack is a good fix for now though
