### ISSUE TITLE
Multiple Authentications do not work

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-js#3840]
I have been using the various docs online about setting up multiple authentications.

I have set the defauly appsync to IAM auth so as I can allow unauthenticated access to my Ionic app.

I also need to use user pools for the angular app I am creating. 

Following the guides online I have set the authh to the user pools within the exports.js file, and checked all endpoints are correct.

Then as per the guide:

```
`const result = await this.amplify.api().graphql({
        query: getPublisherByEmail,
        variables: { email },
        authMode: GRAPHQL_AUTH_MODE.AMAZON_COGNITO_USER_POOLS
      });`
```

However it is still returning an error saying :

```
data: null
errorInfo: null
errorType: "Unauthorized"
locations: [{…}]
message: "Not Authorized to access getPublisherByEmail on type Query"
path: ["getPublisherByEmail"]
```

I also noticed that the guide says that you should add the authentication difective in the Schema as follows:

```
type Publisher @aws_cognito_user_pools @model  
@key(name: "PublisherByEmail", fields: ["email"], queryField: "getPublisherByEmail"){
  id: ID!
  role: String
  firstName: String
  lastName: String
  email: String!
  address: Address
  entities: [Entity] @connection(name: "PublisherEntities")
  profilePicture: String
  createdAt: Float!
  updatedAt: Float!
}
```

> Schema Errors:
> 
> Unknown directive "aws_cognito_user_pools".

I have even tried adding this to my main.ts:

```
const client1 = new AWSAppSyncClient({
  url: awsconfig.aws_appsync_graphqlEndpoint,
  region: awsconfig.aws_appsync_region,
  auth: {
    type: AUTH_TYPE.AMAZON_COGNITO_USER_POOLS,
    jwtToken: async () => (await Auth.currentSession()).getIdToken().getJwtToken(),
  },
  disableOffline: true,
});


```

Nothing I have tried every changes the outcome. It is always unauthorised.

I am doing this in an Angular project which works fine with IAM authentication.

If I switch the main authentication type to user pools everything works as it should do. However I need the authentication type to be IAM for my Ionic app.

**Comment by jordanranz** [comment]
Hey @oliverandersencox, can you link the guide you are following for this?

**Comment by oliverandersencox** [comment]
sure- https://aws.amazon.com/blogs/mobile/using-multiple-authorization-types-with-aws-appsync-graphql-apis/

- https://aws-amplify.github.io/docs/js/api#aws-appsync-multi-auth-1

- https://github.com/aws-amplify/amplify-js/issues/1252#issuecomment-459920695

**Comment by AlessandroAnnini** [comment]
@oliverandersencox have you found a solution? I have the same problem with subscriptions

**Comment by sonufrienko** [comment]
Right now, multiple authentications don't work only on **Amplify Console**.

> SchemaValidationError: Schema Errors:
> Unknown directive "aws_cognito_user_pools".

**Amplify CLI** works well.

**Comment by abdallahshaban557** [comment]
Hi @oliverandersencox - can you try upgrading the CLI and Amplify JS library and trying this again? I do not see this issue in the newest versions

**Comment by tannerabread** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and are in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
