### ISSUE TITLE
Better typing for variables/data with API.graphql()

### ISSUE THREAD

**Issue by buggy** [aws-amplify/amplify-js#3842]
**Is your feature request related to a problem? Please describe.**

The `variables` passed into and `data` returned from `API.graphql()` are `any`'s.

Tools like Apollo code gen can generate and maintain type definitions from `.graphql` files. By changing the type definition for `API.graphql` we can take advantage of this to make sure developers are passing in correct variables and only using data actually requested.

**Describe the solution you'd like**

I'd like to change the definition to something like:

```typescript
graphql<TData extends object, TVariables = OperationVariables>(opts: GraphQLOptions<TVariables>): Promise<GraphQLResult<TData>> | Observable<TData>
```

This allows us to set the shape for the variables and data when calling graphql().

For example:

```typescript
interface IMyData {
  string: name;
}

interface IMyVariables {
  id: number;
}

const result = graphql<IMyData, IMyVariables>(graphqlOperation(queries.getTodo, { id: 1234 });
```

Both interfaces would be generated and maintained by a tool like Apollo codegen to keep them in sync with the actual GraphQL queries.

**Describe alternatives you've considered**

You can use `const data = result.data as IMyData` to apply an interface to the `data`. Similarly you can use `const variables: IMyVariables = {}` to make sure variables is set correctly then pass that to `API.graphql()`.

**Additional context**

This is how the Apollo client works to provide strong type checking for application code.

**Comment by idanlo** [comment]
Not stale

**Comment by buggy** [comment]
Not stale

**Comment by idanlo** [comment]
Not stale

**Comment by idanlo** [comment]
Not stale

**Comment by camin-mccluskey** [comment]
definitely not stale
