### ISSUE TITLE
setPreferredMfa: User has not set up software token mfa

### ISSUE THREAD

**Issue by Xander567** [aws-amplify/amplify-js#3844]
**Describe the bug**
If you have Totp enabled and setup, then make another call to Auth.setupTotp but never verify it, you can't change the preferred Mfa, as it keeps returning "User has not set up software token mfa"

**To Reproduce**
1. Auth.SetupTotp();
2. Auth.verifyTotpToken();
3. Auth.setPreferredMfa(totp);
4. Auth.setupTotp();
5. Auth.setPreferredMfa(NOMFA);

**Expected behavior**
I should be able to still disable the MFA, even if the user hasn't finished setting up totp. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: Latest

**Additional context**
I'm having to do this because of another issue. If the user sets up TOTP to completion (including setPreferredMfa to TOTP), and calls Auth.setupTotp() again, it seems to disable TOTP for the user, but never changed the preferred mfa. So while getPreferredMfa is still returning TOTP, it's never actually being used and is defaulting to SMS (if previously setup) or NOMFA.

**Comment by mousedownmike** [comment]
I'm running into the same issue.  I appear to be able to modify the preferred MFA (to get out of TOTP) by setting a verified phone_number and then call Auth.setPreferredMfa(SMS).

The documentation does not make it clear that that the setupTotp process starts to make changes to the user.  

If you [check out the Enabling TOTP docs](https://aws-amplify.github.io/docs/js/authentication#enabling-totp), it reminds you to set the preferred MFA to TOTP (aka SOFTWARE_TOKEN_MFA).  Based on my experience, it appears to be getting set when setupTotp is getting called.

**Comment by mousedownmike** [comment]
I think this is the same as #1226.

**Comment by KarimIbrahim** [comment]
Is there any updates on this issue?

**Comment by zirkelc** [comment]
Running into the same issue

**Comment by jamesaucode** [comment]
The Cognito team has rolled out a change around last week that has solved this issue.
