### ISSUE TITLE
Translations are consistent or complete

### ISSUE THREAD

**Issue by moneyatbo** [aws-amplify/amplify-js#3849]
**Describe the bug**
Looking at /packages/aws-amplify-react-native/src/AmplifyI18n.js ./packages/aws-amplify-react/src/AmplifyI18n.js the translations are not consistent in both implementations and the Spanish translation does include all key/value pairs
**To Reproduce**
1. diff ./packages/aws-amplify-react-native/src/AmplifyI18n.js ./packages/aws-amplify-react/src/AmplifyI18n.js

**Expected behavior**
Except in cases where there are any specific needs for mobile or web the translations should be the same and the key/pairs should be complete for every language.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 - Version All

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser All
 - Version All

**Additional context**

diff ./packages/aws-amplify-react-native/src/AmplifyI18n.js ./packages/aws-amplify-react/src/AmplifyI18n.js

```

 2c2
 <  * Copyright 2017-2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 ---
 >  * Copyright 2017-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 16d15
 <         'Loading...': "Lädt...",
 67d65
 <         'Loading...': "S'il vous plaît, attendez",
 117d114
 <         'Loading...': "Espere por favor",
 151,152c148
 <     'it': {
 <         "Loading": "Caricamento in corso",
 ---
 >     'it': {    
  155c151
 <          "Back to Sign In": "Torna alla Login",
 ---
 >         "Back to Sign In": "Torna alla Accesso",
 200d195
 <         'Loading...': "请稍候",

```

Spanish has 29 items where Italian has over 40
`
   'es': {
        'Loading...': "Espere por favor",
        'Sign In': "Registrarse",
        'Sign Up': "Regístrate",
        'Sign Out': "Desconectar",
        'Forgot Password': "Se te olvidó tu contraseña",
        'Username': "Nombre de usuario",
        'Password': "Contraseña",
        'Change Password': "Cambia la contraseña",
        'New Password': "Nueva contraseña",
        'Email': "Email",
        'Phone Number': "Número de teléfono",
        'Confirm a Code': "Confirmar un código",
        'Confirm Sign In': "Confirmar inicio de sesión",
        'Confirm Sign Up': "Confirmar Registrarse",
        'Back to Sign In': "Volver a Iniciar sesión",
        'Send Code': "Enviar código",
        'Confirm': "Confirmar",
        'Resend a Code': "Reenviar un código",
        'Submit': "Enviar",
        'Skip': "Omitir",
        'Verify': "Verificar",
        'Verify Contact': "Verificar contacto",
        'Code': "Código",
        'Account recovery requires verified contact information':
        'User does not exist': "el usuario no existe",
        'User already exists': "El usuario ya existe",
        'Incorrect username or password': "Nombre de usuario o contraseña incorrecta",
        'Invalid password format': "Formato de contraseña inválido",
        'Invalid phone number format':

`
**Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by jordanranz** [comment]
This is due to contributions from the community being made over time to improve individual languages. The i18n module is extendable if your solution requires an additional set of these translations.

**Comment by artemkv** [comment]
Hi,
while testing the localization, I discovered extra strings that were not present in AmplifyI18n.tsx (https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/AmplifyI18n.tsx):

```
        'The following fields need to be filled out: Email': '...',
        'The following fields need to be filled out: Email, Password': '...',
        'The following fields need to be filled out: Password': '...',
        'Custom auth lambda trigger is not configured for the user pool.': '...',
        'Resend Code': '...',
        'Confirmation code cannot be empty': '...',
        'Password cannot be empty': '...',
        'Invalid verification code provided, please try again.': '...',
        'Confirmation Code': '...',
        'Lost your code? ': '...'
```

I added them to my app dictionary, however I feel very uncomfortable about the process:
- I needed to test EVERY step in the registration and password recovery flow to detect those missing labels;
- I have a feeling that some of the labels were changed ('Resend a Code' -> 'Resend Code'?). This kind of change should not be done, since it's going to silently break all the localizations in the world.

Thank you,
Artem

**Comment by evcodes** [comment]
I am working on other translation related issues and will provide more translations for spanish. We will work on making the translations more consistent for every language.
