### ISSUE TITLE
Amplify.configure does not honour all required options for Auth config.

### ISSUE THREAD

**Issue by rheinardkorf** [aws-amplify/amplify-js#3855]
**Describe the bug**
Importing the config file generated by `amplify init` and passing it as the object to `Amplify.configure()` fails for Amplify Auth.

The core Parser is not including `identityPoolRegion`.  See https://github.com/aws-amplify/amplify-js/blob/master/packages/core/src/Parser.ts#L21-L28

Documentation states:

```
 // OPTIONAL - Amazon Cognito Federated Identity Pool Region 
 // Required only if it's different from Amazon Cognito Region
 identityPoolRegion: 'XX-XXXX-X',
```

However, this does not seem to be the case and has to be provided in the Parser to work.

**To Reproduce**
1. New project.
2. `amplify init`
3. `amplify add auth`
4. `amplify push`
5. Include and configure Amplify Auth in project:

```
import Amplify, { Auth } from 'aws-amplify'
import awsconfig from './src/aws-exports'
Amplify.configure(awsconfig)
```

6. Attempt to use Authenticator HOC.

**Expected behavior**
Authentication works.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Current Chrome, Safari, FireFox

**Additional context**

See gist: https://gist.github.com/rheinardkorf/b26340f0ba2bafc0ac9125d2d4d12619

Making the following modification to https://github.com/aws-amplify/amplify-js/blob/master/packages/core/src/Parser.ts resolves the problem:

```
        // Auth
        if (config['aws_cognito_identity_pool_id'] || config['aws_user_pools_id']) {
            const Auth = {
                userPoolId: config['aws_user_pools_id'],
                userPoolWebClientId: config['aws_user_pools_web_client_id'],
                region: config['aws_cognito_region'],
                identityPoolId: config['aws_cognito_identity_pool_id'],
                identityPoolRegion: config['aws_cognito_region'],
                mandatorySignIn: config['aws_mandatory_sign_in'] === 'enable'? true: false
            };
            amplifyConfig.Auth = Auth;
        }
```

**Comment by jordanranz** [comment]
Hey @rheinardkorf,

Thanks for submitting this issue. Had a few questions for triage:
- Does the identity pool region and the project region (set up during `amplify init`) differ?
- Is this application server-side rendered?
- What failures are you seeing? Error messages or something else?

**Comment by rheinardkorf** [comment]
Hey @jordanranz,

1) During init it asks for an AWS profile. My profile is `ap-southeast-2`. So I expect that this is the region that Amplify will use for all provisioning. 

2) The application is client-side rendered. 

3) When I use the `amplify-js` `Authenticator` HOC the app appears to work. I get the login/signup forms, but when attempting to create a new user I get a blue banner saying “User pool not found.”

3b) When I have a working user and revert my changes the same error occurs. 

The above takes place when I simply pass the config file to Amplify.configure() as the object. 

To fix it I have to manually describe the object. So I use the exact same object as in the Parser. It still fails. Then I add the identityPool and the App works again. 

Next, I change to use the just assign the config file and make the change in the Parser… then it works as expected. 

The region was my first guess too. Perhaps the default region for identityPool is not the same as the project region. So setting it from the Parser works. 

I hope this makes sense. 

Cheers.

**Comment by rheinardkorf** [comment]
@jordanranz is it possible that it was something on the actual AWS services?  I've had this problem for a couple of days and this morning I wanted to do a screencast to show you my issue... and it went away ¯\_(ツ)_/¯

**Comment by jordanranz** [comment]
@rheinardkorf, your explanation definitely makes sense. Thank you for explaining the process so thoroughly!

To follow up on your last post, are you saying that `User pool not found` is no longer showing up and the configuration you posted above is now working without the changes that you submitted a PR for?

**Comment by rheinardkorf** [comment]
@jordanranz its in consistent.  With the patch applied it works. Without the patch I just got the `User pool not found` error again.  Will attempt to capture it if it happens again.
