### ISSUE TITLE
New user registration flow drops + in email addresses when autofilling after confirming

### ISSUE THREAD

**Issue by scottjanssen** [aws-amplify/amplify-js#3857]
**Describe the bug**
When registering a new user, if you put a + in the email while registering, it doesn't show up when the email attempts to be pre-filled on the login screen.

**To Reproduce**
Register as a new user using a + in your email address
follow steps to confirm registration
notice the email that pre-fills on your new login screen doesn't include the +

**Expected behavior**
Email is expected to be pre filled on the login screen correctly (with the plus sign)

**Screenshots**
If applicable, add screenshots to help explain your problem. See below

**Desktop (please complete the following information):**
 - OS: Mac
 - Chrome
 - OS Version 10.14.16
Screenshots:
![bd245f57-ef20-4501-9b76-7f0777be14b9](https://user-images.githubusercontent.com/29414662/63117975-db686000-bf6a-11e9-9289-561ce5fbbb63.png)
![9825943b-e046-4152-8e4c-d3ec71cf8713-1](https://user-images.githubusercontent.com/29414662/63117982-ddcaba00-bf6a-11e9-8bbb-b555dd8257fd.png)

**Comment by jordanranz** [comment]
@scottjanssen how are you using Amplify in this scenario? The screenshots posted don't look Amplify UI related.
