### ISSUE TITLE
Analytics Event Batching leads to Events not being reported

### ISSUE THREAD

**Issue by zjullion** [aws-amplify/amplify-js#3860]
**Describe the bug**
When recording multiple events with `Analytics.record()`, the batching behaviour of `packages/analytics/src/Providers/AWSPinpointProvider.ts` leads to event 'collisions' that results in only a single event in a batch being recorded.

**To Reproduce**
We're running the following code:
```
const promises = []
items.forEach(async (item) => {
  promises.push(Analytics.record({
    name: '_monetization.purchase',
    attributes: {
      _currency: 'USD',
      _product_id: item.productCode,
      productCode: item.produceCode,
      productName: item.name
    },
    metrics: {
      _item_price: item.price,
      _quantity: item.quantity
    }
  }))
})
await Promise.all(promises)
```

For each 'batch' of items sent, regardless of whether `item.productCode` is unique per item, and regardless of what we set `flushInterval` and `flushSize` to in `Analytics.configure()`, only a single `_monetization.purchase` in the batch will be recorded.

**Expected behavior**
I would expect that multiple events sent to `Analytics.record()` simultaneously would result in separate events being recorded in Pinpoint.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 76.0.3809.100

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***
With DEBUG logging on, you can see that multiple events submitted to `Analytics.record` at the same time are batched like so:
```
EventsRequest:
BatchItem:
2a2b64d0-be0d-11e9-baf4-9bb171fe051e:
Endpoint: {}
Events:
db75f8e3-c04c-11e9-9732-4565f51db7a6:
Attributes: {_currency: "USD", _product_id: "out_inv", productName: "Outstanding Invoice"}
EventType: "_monetization.purchase"
Metrics: {_item_price: 4, _quantity: 1}
Session: {Id: "d68049d2-c04c-11e9-9732-4565f51db7a6", StartTimestamp: "2019-08-16T17:39:46.029Z"}
Timestamp: "2019-08-16T17:39:54.350Z"
```
Every item has the same 'BatchItem id' and the same 'Events id', which I think is what causes the collisions.

**Comment by zjullion** [comment]
After some digging on our end, it appears this is a fundamental issue with the Pinpoint service, and not with amplify-js. When passing multiple events to Pinpoint in a single batch, even if those events were assigned different ids, they will still 'collide', resulting in only a single one of the events being recorded. In order to successful record multiple events in a single call to Pinpoint, each event needs to be in it's own batch.

**Comment by jordanranz** [comment]
Hey @zjullion, 

This seems like a bug with how the batching is handled. By default batching uses a buffer to handle the array of events and sends the batch of events after the buffer is either filled or at the end of a timeout.

There is a way to immediately send the batch of events. Can you try putting `immediate: true` inside of the event object like: 
```
promises.push(Analytics.record({
    name: '_monetization.purchase',
    immediate: true,
    ...
}))
````

I'll add this item to our backlog to investigate further.

**Comment by iartemiev** [comment]
Hey @zjullion, we've changed the way event batching works with Pinpoint. 
Could you please try the latest version by installing it via `yarn add aws-amplify@unstable` and then letting us know here if you're still experiencing issues?

**Comment by zjullion** [comment]
@iartemiev, I should let you know that we're not actively working on the analytics portion of our application anymore, and as such, it's unlikely I will be able to confirm the fix anytime soon. My apologies.

**Comment by iartemiev** [comment]
@zjullion thanks for the response! I’ll close this issue
