### ISSUE TITLE
User friendly invalid username error

### ISSUE THREAD

**Issue by finnbear** [aws-amplify/amplify-js#3862]
**Describe the bug**
When a username does not meet formatting requirements, for example by having spaces in it, the following error message is displayed to the user
```
1 validation error detected: Value at 'username' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{M}\p{S}\p{N}\p{P}]+
```

**To Reproduce**
1. Go to user pool sign up page
2. Type a valid email and password, along with a username that includes spaces

**Expected behavior**
A user friendly error message should be displayed
```
Username cannot contain spaces
```
All possible errors should have a user friendly message. The regular expression message should be reserved for documentation.

**Comment by kennu** [comment]
I see the same problem when a user tries to sign in and accidentally types a trailing space after their email address:

```
2 validation errors detected: Value 'user@example.org ' at 'userName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{M}\p{S}\p{N}\p{P}]+; Value 'user@example.org ' at 'userAlias' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{M}\p{S}\p{N}\p{P}]+
```

My proposal to make it better:
1. Make the error message friendlier as suggested above.
2. Automatically trim leading and trailing whitespaces away from usernames and emails by default.
3. Maybe add an option to NOT trim whitespace if someone really needs it.

**Comment by Graham-Stein** [comment]
**Describe the bug**
I am still seeing the behaviour described by kennu when a user leaves a trailing space after their user name.
**To Reproduce**
Attempt to log in using Amplify UI with a trailing space after username.
**Desired behaviour**
Present the user with a more user friendly error message.


![image](https://user-images.githubusercontent.com/39591264/92379938-32098480-f100-11ea-8484-671d71b00a3a.png)
