### ISSUE TITLE
Add Loading indicator to Sign In button

### ISSUE THREAD

**Issue by jordanranz** [aws-amplify/amplify-js#3863]
Related to #3820, #3753

Add a loading indicator to the 'Sign In' button while the Sign In request processing is executing. The solution will utilize either 'Loading...' text or an animated loading spinner icon. The solution should be built in each of our supported frameworks for parody.

**Comment by hlynurlogi** [comment]
Awesome @jordanranz ! 
Great to see you are working on this 😄

**Comment by Haegin** [comment]
@jordanranz is there an estimate for when this will happen? I'd also like this feature.

**Comment by jordanranz** [comment]
This is now built into the [new UI components](https://docs.amplify.aws/ui)
