### ISSUE TITLE
invalid phone number

### ISSUE THREAD

**Issue by idkjs** [aws-amplify/amplify-js#3868]
** Which Category is your question related to? **
invalid phone number input in `aws-amplify-react`

** What AWS Services are you utilizing? **
Aws Amplify Console auth starters here: https://github.com/aws-samples/aws-amplify-auth-starters

** Provide additional details e.g. code snippets **

I have deployed using the `click to deploy` button.

While trying to sign in I get this error:

```json
error signing up:  
Object { code: "InvalidParameterException", name: "InvalidParameterException", message: "Invalid phone number format." }
```

I get this whether the format is `+1 999-999-9999` or `999-999-999` which should work if I am reading the following correctly:
```js
    composePhoneNumber(dial_code, phone_line_number) {
        return `${dial_code || '+1'}${phone_line_number.replace(/[-()]/g, '')}`;
    }
```

https://github.com/aws-amplify/amplify-js/blob/ece0b229441357b754615052393e09bf8ecf6894/packages/aws-amplify-react/src/Auth/PhoneField.jsx#L25-L27

<img width="1392" alt="Screen Shot 2019-08-18 at 12 35 07 PM" src="https://user-images.githubusercontent.com/2370391/63227447-ae0ef280-c1b4-11e9-9aeb-de4fc689f654.png">

What is the correct format for inputting a phone number?

I have noticed that you can bypass this by leaving the phone number blank, but that does not answer the question, obviously.

Thank you.

**Comment by dabit3** [comment]
I am actually not using the `composePhoneNumber` method, but maybe I should be using it or something like it. Instead, you would have to add the phone number manually:

```js
+19045555555
```

Or something like it. You could also add the helper method locally, something like just adding the function and processing the user input:

```js
composePhoneNumber(dial_code, phone_line_number) {
  return `${dial_code || '+1'}${phone_line_number.replace(/[-()]/g, '')}`;
}
```

**Comment by idkjs** [comment]
@dabit3 ok. Any docs on how to not show an unused field using `withAuthenticator`? In this case, lets you input the info then throws an error and doesn't do anything. Must be in options somewhere.
