### ISSUE TITLE
Feature Request:- Include Global Attributes while sending standard events to pinpoints analytics via AWS SDK for JavaScript

### ISSUE THREAD

**Issue by praneethreddytekula-amazon** [aws-amplify/amplify-js#3871]
**Is your feature request related to a problem? Please describe.**
Need a feature/method to include global attributes while sending standard events to pinpoint analytics via AWS SDK for javascript just like here, which is for AWS mobile SDK:- https://aws-amplify.github.io/aws-sdk-android/docs/reference/com/amazonaws/mobileconnectors/pinpoint/analytics/AnalyticsClient.html

**Additional context**
As of now, we can include global attributes for standard events like session events (startsession, stopsession etc.,) only through AWS Mobile SDK (Android or IOS). 

pinpointManager.getAnalyticsClient().addGlobalAttribute("globalVariable", "API-KEY");
        pinpointManager.getSessionClient().startSession();
        pinpointManager.getAnalyticsClient().submitEvents();

**Comment by elorzafe** [comment]
@praneethreddytekula-amazon are you using Amplify or just aws-sdk?

**Comment by praneethreddytekula-amazon** [comment]
@elorzafe, yes I am using aws-amplify javascript library. 

Let me know, if you require more information.

**Comment by elorzafe** [comment]
@praneethreddytekula-amazon have you tried autotracking feature? https://aws-amplify.github.io/docs/js/analytics#session-tracking

**Comment by tannerabread** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and are in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
