### ISSUE TITLE
Confirm password field on withAuthenticator signUp form

### ISSUE THREAD

**Issue by damianrr** [aws-amplify/amplify-js#3872]
**Is your feature request related to a problem? Please describe.**
The withAuthenticator signUp from doesn't have the possibility of adding a "confirm password" field so that the user needs to type it twice, thus preventing creating an account with a wrong, hence unknown password.

**Describe the solution you'd like**
Allow me to configure/add a "confirm password" input in withAuthenticator SignUp form.

**Comment by elorzafe** [comment]
@damianrr thanks for your feedback. This is duplicate from #3853 I will close this issue to only keep tracked

**Comment by claym** [comment]
Can we revisit this?

My app requires only the email and name. I create the account, they get the invite, and once they login, they are prompted for their name and a new password. 

Unfortunately, most users see a prompt for a new password and expect to it to be combined with a confirmation, meaning their password is set as their password. 

This is a huge problem. 

Yes, the user should be more careful, but this is a terrible user experience and there’s nothing on my end I can do about it. 

Please revisit this ASAP.
