### ISSUE TITLE
verifyTotpToken works with expired token

### ISSUE THREAD

**Issue by antonleviathan** [aws-amplify/amplify-js#3873]
**Describe the bug**
When using `Auth.verifyTotpToken` I am able to use a code which has expired in my token generating app (in this case google authenticator). 

**Expected behavior**
The previous token should no longer work once a new code has been generated.

**Sample code**
```
  Auth.currentAuthenticatedUser()
      .then(user => {
        Auth.verifyTotpToken(user, totpCode)
          .then(() => {
             // ...
```

**Comment by elorzafe** [comment]
@antonleviathan how are you enabling TOTP on your app? Did you follow [this guide](https://aws-amplify.github.io/docs/js/authentication#enabling-totp)

**Comment by antonleviathan** [comment]
@elorzafe Yeah, more or less. The one thing I do differently is that I do the MFA preference update server-side instead of using Amplify. It does work, and the code eventually expires, but it doesn't expire when I expect it to.

**Comment by timwhunt** [comment]
Hi @antonleviathan,

Thanks for asking about this. It is by design that each TOTP code is accepted for a short time after its defined time window. The TOTP RFC (https://tools.ietf.org/html/rfc6238#section-5.2) discusses this to account for delays in sending the code.

Regards,
Tim

**Comment by ashika01** [comment]
Docs in Cognito mentions time window here as well.
https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-mfa-totp.html

**Comment by ashika01** [comment]
Please feel free to reopen this issue if there is an issue here.
