### ISSUE TITLE
After successful registration and confirmation, how can we login the user automatically?

### ISSUE THREAD

**Issue by damianesteban** [aws-amplify/amplify-js#3882]
**Is your feature request related to a problem? Please describe.**
This feature was requested in the original Cognito SDK for JavaScript over three years ago:

https://github.com/amazon-archives/amazon-cognito-identity-js/issues/186

**Describe the solution you'd like**
We would like the user to be able to automatically sign in after confirming the user’s email. 

**Describe alternatives you've considered**
There are a number of solutions that could be implemented but seeing as how Cognito is an identity provider it should provide this functionality. 

**Additional Context:**

Again, this was requested over three years ago. It’s great that Amplify can interface with Polly and Sumerian and everything else, but the identity provider portion is severely lagging behind the competition (not only Auth0, but even Firebase). 

Had this been brought up at all in discussions about features?

**Comment by potatodepaulo** [comment]
This seems like it could be prioritized higher! Pretty common pattern, right?

**Comment by abdallahshaban557** [comment]
We agree! We are definitely working on enabling this in the near future. Once we have exact timelines, we will share our updates on Github.

**Comment by elorzafe** [comment]
@damianesteban @potatodepaulo 

Today we released `autoSignIn` feature on Amplify JS. We will be updating the docs tomorrow, but the feature is available now on version `aws-amplify@4.3.29`

If you are using code verification for new users you only have to do.

```javascript
 Auth.signUp({
      username: 'xxxxxx',
      password: '*********,
      attributes: {
        email: 'xxxxxxxxxx'
      },
      autoSignIn: {
        enabled: true
      }
    })
````

The library will login in the user automatically after the user is confirmed on the App when doing `Auth.confirmSignUp`


If you are using link verification the library also handle that case but you need to configure the library is using `link` verification on `Amplify.configure` like this

```javascript
Amplify.configure({
    Auth: {
       // OPTIONAL
       signUpVerificationMethod: 'link'

        // REQUIRED only for Federated Authentication - Amazon Cognito Identity Pool ID
        identityPoolId: 'XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab',
        
        // REQUIRED - Amazon Cognito Region
        region: 'XX-XXXX-X',

        // OPTIONAL - Amazon Cognito Federated Identity Pool Region 
        // Required only if it's different from Amazon Cognito Region
        identityPoolRegion: 'XX-XXXX-X',

        // OPTIONAL - Amazon Cognito User Pool ID
        userPoolId: 'XX-XXXX-X_abcd1234',

        // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
        userPoolWebClientId: 'a1b2c3d4e5f6g7h8i9j0k1l2m3',

        // OPTIONAL - Enforce user authentication prior to accessing AWS resources or not
        mandatorySignIn: false,

    }
});
```

Also if the user is autoConfirmed the library will sign in the user as well automatically.

Amplify will emit the event that the user is signed in, or in case you have to use MFA you can use it as well.

```javascript
Hub.listen('auth', ({ payload }) => {
     const { event } = payload;
     if (event === 'autoSignIn') {
          const user = payload.data;
     }
    // ...
})
```

**Comment by abdallahshaban557** [comment]
We also have documentation available here now! https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js/#auto-sign-in-after-sign-up

**Comment by mfukano** [comment]
Hey @abdallahshaban557, sorry to comment on a closed issue but we have recently worked through implementation of autoSignIn and the listener function into our code. 

The feature itself works great, but catching the message with the Hub listener call ends up being sort of clunky in scenarios where the user session is required directly after the user is confirmed, requiring blocking behavior. The Hub listener function, as far as I can tell, doesn't return anything, which requires us to implement the listener function and subsequent routing logic within the page instead of being able to modularize this code. Is there a recommendation for handling events like this?

`const listenToAutoSignInEvent = () => {
    Hub.listen('auth', ({ payload }) => {
      const { event } = payload
      if (event === 'autoSignIn') {
        setUser(payload.data)
        navigate('../pageRequiringUserSessionInfo')
      } else if (event === 'autoSignIn_failure') {
        setAutoSignIn(false)
        setMessage("We had trouble signing you in. Please log in on the following page!")
        setTimeout(() => {
          navigate('../login')
        }, 2000)
      }
    })
  }`

**Comment by israx** [comment]
Hi @mfukano , sorry to hear that. I'd just like to get some context. How are you using the `listenToAutoSignInEvent` function?

**Comment by israx** [comment]
Hi @mfukano. I was able to replicate the usage of autoSign. On my end, I do get the authenticated user on the payload of "autoSignIn" event. However, if you wanna perform any operations right after that event resolves, I'd suggest to doing it synchronously. e.g using useRef (if using React) or performing any conditional rendering before using the authenticated user.
