### ISSUE TITLE
Full Pinpoint API support in Amplify

### ISSUE THREAD

**Issue by rpostulart** [aws-amplify/amplify-js#3886]
Through AWS Amplify a small set of the Pinpoint API's are available. 

Is there a was to access all the pinpoint API's  (createCampaign, CreateSegment, etc.) or can it be added to to AWS amplify?

**Comment by haverchuck** [comment]
@rpostulart Is this something you'd expect to be able to do from the Amplify CLI?

**Comment by rpostulart** [comment]
Yes, that would be great. Now I have limited API's available. 

For example: I would like to make a project, then updateEndpoints, create a segment and then plan messages for a segment with createCampaign.

For now I created a Lambda function and added the AWS CLI and expose an endpoint via the api gateway, which in the end also works fine.
