### ISSUE TITLE
AppSync Limit

### ISSUE THREAD

**Issue by wh1terose** [aws-amplify/amplify-js#3887]
I have a DynamoDB table which contains 5100 records and currently have a storage size of 1.82MB, and I use appsync to query and mutate. I've been trying to display all those records (ListRecords) function and I've been only receiving 3000+ records.. And i've read that i should use pagination? Could you guys help me how to paginate through those records, cause im only getting the first "scan" , i think? 

Thanks in advance

**Comment by sammartinez** [comment]
@wh1terose This may be some use on [Paginating](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html#Query.Pagination) through the DynamoDB records. If anything, I have added the label of `help-wanted` to see if someone from the community has done this in the past.

Hope the link helps!

**Comment by wh1terose** [comment]
@sammartinez Thanks, Sam! Will look into it.
