### ISSUE TITLE
Cognito log out for all browser tabs

### ISSUE THREAD

**Issue by chengjia080787** [aws-amplify/amplify-js#3888]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
How could I write the code to trigger cognito logout from all browser tabs?

For example, the user logout from one browser tab then the user should be kicked out from all other browser tabs at the same time.

**Comment by haverchuck** [comment]
@chengjia080787 - You might want to consider the [BroadcastChannel API](https://blog.arnellebalane.com/sending-data-across-different-browser-tabs-6225daac93ec) or [Service Workers](https://www.loxodrome.io/post/tab-state-service-workers/).
