### ISSUE TITLE
[VueJS] Missing i18n translations in components

### ISSUE THREAD

**Issue by DanielMuller** [aws-amplify/amplify-js#3892]
**Describe the bug**
Translation of texts used in components is missing. aka, there is no default dict existing

**To Reproduce**
1. Start a new Vue project and install aws-amplify and aws-amplify-vue as per the documentation
```js
import Amplify, * as AmplifyModules from 'aws-amplify'
import { AmplifyPlugin } from 'aws-amplify-vue'
Vue.use(AmplifyPlugin, AmplifyModules)
```
2. On App.vue load, set the language to french
```js
created() {
  this.$Amplify.I18n.setLanguage('fr')
}
```
3. Display a translation on the page
```
{{ $Amplify.I18n.get('Sign In') }}
```

The text is not translated

**Expected behavior**
All texts used in components, and other places used via aws-amplify, aws-amplify-vue, @aws-amplify/core, should have existing translations in the languages supported by the AWS console.

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Version: All

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser All
 - Version All

**Additional context**
When adding manually a dict with the key/values for translation, the expected translation is shown. Meaning that `I18n` is loaded and works correctly, but that the default translations are missing.

This issue can be related to #3849. There should be a default dict in @amplify/core with additional dicts for each package (for texts only available in a particular package). And then could even me overwritten in our code.
This would simplify the maintainability of the translations for i18n and perhaps also address part of #3092

**Comment by sammartinez** [comment]
@DanielMuller Thanks for the feedback, as called out on the other issues open related to this I will mark this as a feature request to to sync all of the base i18n translations. I do want to state that we are open to PRs related to this if you feel you would like to provide one for us.

**Comment by DanielMuller** [comment]
Not sure if I am able to do a PR, I am pretty new to Amplify and VueJS. But I can try.

If I understand correctly, the 2 existing translation dictionaries in React and ReactNative aren't loaded automatically, they just exist for whoever wants to load them?

Does centralizing the translations in @amplify/core make sense? Is `core` used by all the packages?

**Comment by tannerabread** [comment]
Closing as this should now be possible with the [Vue Authenticator component](https://ui.docs.amplify.aws/vue/connected-components/authenticator/customization#internationalization-i18n)
