### ISSUE TITLE
How to handle NetworkingError in Auth.currentCredentials()?

### ISSUE THREAD

**Issue by taschik** [aws-amplify/amplify-js#3896]
### Which Category is your question related to?
Auth in aws-amplify in an react-native app

### What AWS Services are you utilizing?
Cognito

### Provide additional details e.g. code snippets  ###

I am often seeing the following errors in my Crashlytics:

```
"{
    "code": "NetworkingError",
    "message": "Network Failure",
    "time": "2019-08-22T05:18:05.148Z",
    "region": "eu-central-1",
    "hostname": "cognito-identity.eu-central-1.amazonaws.com",
    "retryable": true,
    "line": 560,
    "column": 933,
    "sourceURL": "/var/containers/Bundle/Application/6A13A65B-19A3-48EB-8165-E05C6FB1ED54/app.app/main.jsbundle"
}
```

and I was wondering what the best practice is to handle network errors. I am surprised the library itself doesn't do it because it makes sense and should be handled their esp. if it is `retryable: true` but maybe I misconfigured something. I am sure I am not the only one experiencing this and would love to hear what your best practices are to deal with it.

### My Setup: ###

```
    "aws-amplify": "^1.1.36",
```

```
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 139.04 MB / 32.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 26, 27, 28
      Build Tools: 23.0.1, 25.0.0, 26.0.3, 27.0.3, 28.0.1, 28.0.2, 28.0.3
      System Images: android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.8.6 => 16.8.6
    react-native: ^0.60.5 => 0.60.5
  npmGlobalPackages:
    eslint-plugin-react-native: 3.5.0
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

**Comment by pravgupt** [comment]
`NetworkingError` is typically [thrown](https://github.com/aws/aws-sdk-js/blob/cc29728c1c4178969ebabe3bbe6b6f3159436394/lib/http/xhr.js#L53) by the underlying aws js sdk and amplify library just passes it through to the client.

**Comment by pravgupt** [comment]
@taschik , can you create a new issue to the sdk team https://github.com/aws/aws-sdk-js/issues/new/choose
