### ISSUE TITLE
Cognito usage

### ISSUE THREAD

**Issue by shauny1** [aws-amplify/amplify-js#3898]
Cognito via amplify works nicely. It’s hard to tell from the docs if Cognito is ONLY intended to be used for Web and Mobile auth. Is it OK to use it to also auth third party developers consuming my API from non-Web apps?

Ideally I’d like to use Cognito for all my auth requirements.

**Comment by sammartinez** [comment]
@shauny1 This seems better suited to ask Cognito about this via [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=173). Please create a forum question there for this question.
