### ISSUE TITLE
Duplicate email due to identity provider

### ISSUE THREAD

**Issue by finnbear** [aws-amplify/amplify-js#3899]
**Describe the bug**
It is possible to create two accounts with the same username, one of which being a standard email/password account and another being an identity provider account

**To Reproduce**
1. Create user pool with only email as username attribute (sometimes referred to as option 2)
2. Add google as an identity provider
3. Use attribute mapping to map google "email" to cognito "Email"
4. Sign up with username equal to the email address of a google account and an arbitrary password
5. Sign up with google, using the same google account
6. You now have two users with the same "email"

**Expected behavior**
Step 5 should fail due to a duplicate email

**Notes**
- Step 4 was performed with admin-create-user, but this probably doesn't matter
- Aliases are not applicable.
- This bug has interesting implications to the admin user update api inwhich a username (the email in this case) is used as a reference to the user

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chromium
 - Version ?

**Comment by huihe** [comment]
Where can we find more documents about how Cognito link(merge) federated account and standard account? For this case, as @finnbear described, it ends up two accounts with the same email address.

**Comment by turakvlad** [comment]
Guys, any update on this? I have faced with the same issue.
