### ISSUE TITLE
Missing credentials in config

### ISSUE THREAD

**Issue by ricardoribas** [aws-amplify/amplify-js#3903]
**Describe the bug**
While i am using Analytics module, every time i enter the application i receive an error regarding missing credentials. After some research it could be that as i don't have any user logged in it will trigger this error. I saw some issues related (for instance this one [issues/405](https://github.com/aws-amplify/amplify-js/issues/405). As i am using withAuthenticator HOC in order to manage the authentication process, i assume that, whenever an user is not logged in, this error would not appear.

Additionally, i activated analytics for unauthenticated users so i can the behavior of the end users during authentication.

Do i need to make any modification of the code to prevent this error to happen? 

**To Reproduce**
1. Enter the app for the first time;
2. Wait a few seconds for the pinpoint request to be made;

**Expected behavior**

**Screenshots**
![File](https://user-images.githubusercontent.com/47744087/63585068-8fd33900-c59e-11e9-9279-7fc264f992c4.jpg)

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by sammartinez** [comment]
@ricardoribas Can you provide what versions of `aws-amplify` / `aws-amplify-react-native` you are using within your app? Just want a little more information

**Comment by ricardoribas** [comment]
The version of amplify is 1.1.36 and the amplify react native is ^2.1.17-unstable.18. I have the unstable version due to a problem with dial codes on the with authenticator hoc.

**Comment by Ashish5591** [comment]
Hey,
I am trying to reproduce the issue. Could you let me know how you configured the application? Did you use the cli, and what all did you add and in what order?

**Comment by ricardoribas** [comment]
For this application I added Auth, Api, Storage and Analytics (in this order). I accepted non authenticated events as I want to track the behavior of the users during the authentication process.

While I configured cognito, I disabled the option of allowing guest logins. Also, I have added analytics configuration in the cognito dashboard.

**Comment by ricardoribas** [comment]
@Ashish5591 this kind of error is happening in your case? If not, perhaps you can describe me the steps that you have followed. I used the documentation as a reference. Maybe there is a tiny detail missing on my part.

**Comment by bneigher** [comment]
I've been experiencing this for months now and just been handling this myself with calls to `Auth.federatedSignIn` each time any of my Storage calls fail (the only service that correctly throws the errors)

I don't think this is the correct strategy as I have weird effects with multiple pinpoint session_stop and start events stacking up.

But yea it seems that whenever I open the app after an hour of inactivity the Analytics.track event fires before whatever logic has refreshed my cognito token which throws this error.

**Comment by chriswiesner** [comment]
I'm experiencing the same issue.
Was working fine before, but since a react native upgrade (0.59 -> 0.61) i'm getting that.
I do not have a duplicate dependency to aws-sdk or so, which was mentioned in other places as a cause for that.
happens also only when users are not authenticated (i.e. before login)
Do I need to check a policy for that?
