### ISSUE TITLE
Stop amplify pubsub to publish message after regaining internet connection.

### ISSUE THREAD

**Issue by abhishek125** [aws-amplify/amplify-js#3904]
I am using amplify pubsub with react. This react app has a button and clicking on it publishes a messages to aws iot. But if the user clicks without internet connection amplify queue this request for some time and publishes message when internet connection regains. how can I stop this behaviour. I don't want it to retry/queue message publish requests.

**Comment by sammartinez** [comment]
@abhishek125 This is expected behavior when using our PubSub category that it will queue and redrive the request once back in internet connection. Currently, there is not a way to stop this from occurring. I will mark this as a feature request.

**Comment by abhishek125** [comment]
is there any workaround to this issue? It's really important to stop this behaviour for my use case.

**Comment by sammartinez** [comment]
I marked this as `Help Wanted` to see if someone in the community has done something similar. Hope that helps

**Comment by abhishek125** [comment]
No update so far. any suggestion is highly appreciated otherwise I would need to re-implement whole app using other library.

**Comment by mtliendo** [comment]
@abhishek125 can you describe a bit more about your use case?

**Comment by stocaaro** [comment]
Hello @abhishek125 ,

The library still sends all messages on network re-enable. An option for a use-case like this would be to monitor network availability and keep a queue before sending messages to the PubSub interface.

```
import { Reachability } from '@aws-amplify/core';
let networkOnline = false;
const reachability = new Reachability();
reachability.networkMonitor().subscribe(({online}) => {
    networkOnline = online;
    sendMessagesFromCustomQueue(); // Assuming you would implement this to meet your needs
});

if (networkOnline) {
   Pubsub.send('topic', message);
} else {
    customEnqueue(message); // Custom code to manage a queue
}
```

I haven't tested this and there's a bit of custom implementation that would have to work in the framework your working in.

Closing this out with this additional context.

Thanks,
Aaron
