### ISSUE TITLE
API Not Configured Error Condiiton

### ISSUE THREAD

**Issue by darnmark64** [aws-amplify/amplify-js#3905]
We currently have Project A in production and working as expect for customer A. We were asked to clone Project A for a new customer and remove any references from customer A in the cloned project. We created a fork of our Project A Git repository into a new repository called Project B. We removed all of Project A's amplify directory and started with a fresh 'amplify init' with a new AWS account. Our Angular 7 application is identical between the two projects other than the API names. However, we an unable to get Project B's API to configure properly. Every call to an API results in the error condition 'API not configured'. We have completed removed our node_modules and reinstalled using 'npm install' to no avail. We are beyond frustrated that we can't seem to get Amplify to work correctly in Project B. 

Our package.json for Project B:
`{
  "name": "xxxxx-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod --configuration=\"production\"",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.2.15",
    "@angular/cdk": "^7.2.11",
    "@angular/common": "^7.2.15",
    "@angular/compiler": "^7.2.15",
    "@angular/core": "^7.2.15",
    "@angular/forms": "^7.2.15",
    "@angular/platform-browser": "^7.2.15",
    "@angular/platform-browser-dynamic": "^7.2.15",
    "@angular/router": "^7.2.15",
    "@fortawesome/angular-fontawesome": "^0.3.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.19",
    "@fortawesome/free-regular-svg-icons": "^5.9.0",
    "@fortawesome/free-solid-svg-icons": "^5.9.0",
    "@ng-bootstrap/ng-bootstrap": "^4.2.1",
    "angular-google-charts": "^0.1.6",
    "aws-amplify": "^1.1.29",
    "aws-amplify-angular": "^3.0.4",
    "bootstrap": "^4.3.1",
    "core-js": "^2.6.9",
    "ng": "0.0.0",
    "ng-lists": "0.0.7",
    "ngx-spinner": "^7.1.4",
    "package.json": "^2.0.1",
    "rxjs": "~6.3.3",
    "rxjs-compat": "^6.5.2",
    "service": "^0.1.4",
    "tslib": "^1.10.0",
    "util": "^0.11.1",
    "zone.js": "^0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.9",
    "@angular/cli": "^7.3.9",
    "@angular/compiler-cli": "^7.2.15",
    "@angular/language-service": "^7.2.15",
    "@schematics/angular": "^7.3.9",
    "@types/jasmine": "^3.3.13",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^10.14.10",
    "codelyzer": "~4.5.0",
    "eslint": "^6.0.1",
    "jasmine-core": "~3.3.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.5",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.0",
    "ts-node": "^8.3.0",
    "tslint": "~5.12.1",
    "tslint-sonarts": "^1.9.0",
    "typescript": "~3.2.4",
    "webpack-dev-server": "^3.7.2"
  }
}
`

Our aws-exports.js for Project B:
`const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:XXXXXXX",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_XXXXXXX",
    "aws_user_pools_web_client_id": "XXXXXXXX",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "LogTable-casoprod",
            "region": "us-east-1"
        },
        {
            "tableName": "AlertClientConnections-casoprod",
            "region": "us-east-1"
        },
        {
            "tableName": "AlertHistory-casoprod",
            "region": "us-east-1"
        },
        {
            "tableName": "Tokens-casoprod",
            "region": "us-east-1"
        },
        {
            "tableName": "UserHistory-casoprod",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "NcsBrokerApi",
            "endpoint": "https://XXXXXXX.execute-api.us-east-1.amazonaws.com/casoprod",
            "region": "us-east-1"
        },
        {
            "name": "DatabaseBrokerApi",
            "endpoint": "https://XXXXXXX.execute-api.us-east-1.amazonaws.com/casoprod",
            "region": "us-east-1"
        },
        {
            "name": "ApplicationApi",
            "endpoint": "https://XXXXXXX.execute-api.us-east-1.amazonaws.com/casoprod",
            "region": "us-east-1"
        },
        {
            "name": "WebhookBrokerApi",
            "endpoint": "https://XXXXXXX.execute-api.us-east-1.amazonaws.com/casoprod",
            "region": "us-east-1"
        }
    ]
};
export default awsmobile;
`

Our main.ts for Project B:
` import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

import Amplify, { API } from 'aws-amplify';
import awsmobile from './aws-exports';
Amplify.configure({
  ...awsmobile,
  Analytics: {
      disabled: true
  }
});

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));
`

Here is an API call for Project B:
`    const response = await this.amplifyService.api().get('ApplicationApi', path, init)
      .catch((err) => {
        console.error('ApplicationApi: ' + path + ' threw error: ' + err);
        throw err;
      });
`

And here is the result of that API call:
ApplicationApi: /userSettings/XXXXXX/autoDelete threw error: API not configured

This error happens for every one of our API calls.

We're not sure what else to do or try. Any thoughts?

**Comment by darnmark64** [comment]
I updated the aws-amplify and aws-amplify-angular to the latest versions and now the APIs are being configured properly. I'm still completely baffled as to why Project A still runs quite well with the older version of those modules but Project B required an upgrade.

**Comment by sammartinez** [comment]
@darnmark64 Based on the above comment from 6 hours ago, seems this is resolved. Without further information on what versions of Amplify Project A was on, I'm not positive we can give you a concrete answer on why this occurred. If you can provide similar information you provided from Project B, great, cause that will help us help you dive deeper into why this happened. If not, totally understandable and feel free to close this issue.

**Comment by darnmark64** [comment]
@sammartinez The configuration for Project A was identical to Project B. Everything I provided for Project B was exactly as it came from Project A. Since I've upgrade the aws-amplify and aws-amplify-angular modules on Project B that is the only difference between the two.

**Comment by gerrytsui** [comment]
Is your Project B using the package-lock.json from Project A ?  if not, please try copy the package-lock.json over to project B , rm -r node_modules, and then npm install

Exact same config ( in package.json), doesn't means the dependency tree is "Identical".
