### ISSUE TITLE
[Pinpoint] resendLimit seems to be ignored

### ISSUE THREAD

**Issue by cmckni3** [aws-amplify/amplify-js#3906]
**Describe the bug**

I have set `resentLimit: 1` in my Amplify pinpoint configuration but the send is retried 3-4 more times.

**To Reproduce**

Easiest way to reproduce is have IAM role that is setup incorrectly. Then setting the `resendLimit` to `1`. Amplify configuration provided below.

It should be documented that the Cognito Auth and Unauth roles need to have the mobiletargeting:PutEvents, mobiletargeting:UpdateEndpoint,  and mobileanalytics:PutEvents permissions attached.

**Expected behavior**

I expect the `resendLimit` to be respected so the browser isn't flooded with network requests.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 73

**Smartphone (please complete the following information):**
N/A

**Sample code**

```typescript
      Amplify.configure({
        Analytics: {
          disabled: false,
          autoSessionRecord: true,
          AWSPinpoint: {
            resendLimit: 1,
            appId: environment.pinpointAppId,
            region: environment.pinpointRegion,
            mandatorySignIn: false,
          },
        },
      });

      Analytics.autoTrack('session', {
        enable: true,
      });
      Analytics.autoTrack('pageView', {
        // REQUIRED, turn on/off the auto tracking
        enable: true,
        type: 'SPA',
      });

      Analytics.autoTrack('event', {
        enable: true,
        events: ['click'],
        selectorPrefix: 'data-amplify-analytics-',
      });
```

**Comment by pravgupt** [comment]
@cmckni3 , Hi Chris, I tried to reproduce your issue but was unable to. When I set the resendLimit, it was indeed respected by the retry logic here https://github.com/aws-amplify/amplify-js/blob/master/packages/analytics/src/Providers/AWSPinpointProvider.ts#L309-L321

Can you enable debug logs in your app (add right after the imports in your main app Amplify.Logger.LOG_LEVEL = "DEBUG";) and let us know the contents of your console?

**Comment by cmckni3** [comment]
Ok, I will turn on DEBUG and check back.

Is there some other kind of retry when a CORS error happens?

**Comment by cmckni3** [comment]
Attached is a redacted log

[Uploading pinpoint-log.txt…]()

**Comment by cmckni3** [comment]
Attached is a redacted log with debug 

[pinpoint-log.txt](https://github.com/aws-amplify/amplify-js/files/3586917/pinpoint-log.txt)

**Comment by cmckni3** [comment]
Here's a screenshot of the console

![image](https://user-images.githubusercontent.com/735717/64478830-e8e0c680-d173-11e9-8f8c-6c46dd1293e5.png)

**Comment by cmckni3** [comment]
Everything seems to work with correct IAM credentials but I see those requests happen multiple times when permission is denied.

Permission denied result in CORS headers not being returned. I found the issue by using curl.

**Comment by cmckni3** [comment]
Any updates? I have resolved this by fixing my IAM role.

**Comment by pravgupt** [comment]
There are no retries when CORS error happens in Amplify library. I'm thinking is your application is trying to track multiple events (pageviews, sessions, clicks etc.) and each request is failing once and so you see multiple requests made in the browser.

**Comment by cmckni3** [comment]
Would a demo URL help?

I think you may be onto something about multiple events. Seems like the `scroll` and `click` events fire. It's touch to track down.

I'll see if I have time to investigate some more.

**Comment by haverchuck** [comment]
@cmckni3  - A demo URL would definitely help.

**Comment by cmckni3** [comment]
AWS Support responded saying they reproduced it in an amplify sample project.

**Comment by cmckni3** [comment]
Should this issue be closed?

**Comment by Amplifiyer** [comment]
@cmckni3 are you also following up with AWS support and Pinpoint service? If yes, this issue can be closed.

**Comment by cmckni3** [comment]
I believe the support ticket is closed.

From my side it has been fixed after I added the appropriate permissions to the cognito auth and unauth roles.
