### ISSUE TITLE
Auth.federatedSignIn error in Edge 17: Unauthenticated access is not supported for this identity pool

### ISSUE THREAD

**Issue by sopranolinist** [aws-amplify/amplify-js#3909]
**Describe the bug**
HTTPS POST to https://cognito-identity.us-west-2.amazonaws.com/ for `AWSCognitoIdentityService.GetId` in Microsoft Edge 17.17134 produces error: `HTTP400: BAD REQUEST - The request could not be processed by the server due to invalid syntax.(XHR)POST - https://cognito-identity.us-west-2.amazonaws.com/`. Examination of the response revealed further details: `Unauthenticated access is not supported for this identity pool.` This does NOT occur in Edge 16 or Edge 18, or in Firefox, Safari, and Chrome.

Sign in button has the following code configured for the click handler:
```
  const handleSignIn = () => {
    Auth.federatedSignIn({
      provider: CognitoHostedUIIdentityProvider.Google
    });
  };
```
Auth was configured with the Amplify CLI. I am using `Amplify.configure(myconfig)` with the following parameters (some are obfuscated):
```
const myconfig = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:XXXXXXXX",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_XXXXXXXX",
    "aws_user_pools_web_client_id": "XXXXXXXXXXXX",
    "oauth": {
        "domain": "MYAPP.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge 17.17134
- aws-amplify: 1.1.28
- aws-amplify-react: 2.3.8

**Comment by pravgupt** [comment]
@sopranolinist can you [enable the debug logs](https://aws-amplify.github.io/docs/js/logger) for both edge 17 and edge 18 and paste the corresponding logs to this issue?

**Comment by sopranolinist** [comment]
Yes, I'll try to do that this week, thanks for responding!
