### ISSUE TITLE
How to update aws-sdk dependency from 2.474.0 to 2.518.0?

### ISSUE THREAD

**Issue by matwerber1** [aws-amplify/amplify-js#3923]
** Which Category is your question related to? **
Amplify, Aurora Serverless

** What AWS Services are you utilizing? **
Amplify, Aurora Serverless

** Provide additional details e.g. code snippets **

When attempting this: 
```
var AWS = require('aws-sdk');
var rdsdataservice = new AWS.RDSDataService({apiVersion: '2018-08-01'});
```

I receive this error: `TypeError: AWS.RDSDataService is not a constructor`

a `console.log(AWS.VERSION)` shows `2.474.0`, which does not contain the RDSDataService; I'm trying to force a dependency update to `2.518.0`. 

In my project root, I navigate to `./node-modules/@aws-amplify/core/package.json` and update dependencies to: 

```
"dependencies": {
    "aws-sdk": "2.518.0",
    "url": "^0.11.0"
  },
```

Then I run `npm install` in that directory. I then navigate to the project root, delete the root `./package.json`, and run `npm shrinkwrap`, which creates `npm-shrinkwrap.json` and verify it contains: 

```
"@aws-amplify/core": {
      "version": "1.1.0",
     ....
      },
      "dependencies": {
        "aws-sdk": {
          "version": "2.518.0",
```

My understanding is that this should work, but my project continues to show `2.474.0` from `console.log(AWS.VERSION)`.

Can you advise on how I can force a newer aws-sdk version? Understood that I could use GraphQL/AppSync to interact with Aurora Serverless but for the project I'm working on I'd like to make the API call directly from the browser using Cognito federated identities.

**Comment by jkeys-ecg-nmsu** [comment]
@sammartinez is there a simple way of forcing a newer version of the SDK?

**Comment by sammartinez** [comment]
@jkeys-ecg-nmsu are you looking for an SDK version higher than [2.518.0](https://github.com/aws-amplify/amplify-js/blob/master/packages/core/package.json#L44)? We do pin it based on breaking changes that can cause issues to Amplify. But Im going to cut an issue to see about updating the aws-sdk version in our core package.

**Comment by jkeys-ecg-nmsu** [comment]
@sammartinez yes, we would like to use the Kinesis Video Streams WebRTC integration, which requires at least 2.585.0. 

Thank you for tagging the request.
