### ISSUE TITLE
aws-export.js responseType

### ISSUE THREAD

**Issue by saaniaki** [aws-amplify/amplify-js#3924]
**Describe the bug**
By adding or updating "auth" using amplify and setting the OAuth flow to "implicit" option, and pushing it using "amplify push", aws-export.js file would be generated with a wrong parameter in the responseType of oauth section. This parameter can only have values of "code" or "token", but amplify cli would put "implicit" as the value, causing the oauth endpoints to return 400 response code.

**Comment by ashika01** [comment]
@saaniaki : Are you still having this issue? With the current version of amply-cli, `aws-export.js` has `"responseType": "token"`. Could you verify with a newer version?

**Comment by saaniaki** [comment]
Amplify Cli @1.8.1 was what I was using. Currently we have migrated from Cognito so I can't confirm if the bug still exists on the latest version or not.
