### ISSUE TITLE
nextToken float not working

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-js#3925]
When running a search query with the sort done by the field 'score' of type Float, the next token returned is always a string version of the foat. 

This returned nextToken value will always return an empty result set when used to fetch the next result. 

I have tried co converting it to a float and tried altering the limit size for the query, and it still always returns an empty result set.

If all my results are 0.0 score values, then the nexttoken will return the same results every-time its called

Next token works for other formats, just not the float in this case.

**Comment by oliverandersencox** [comment]
Sure thing @sammartinez 

 "aws-amplify": "^1.1.36",
  "aws-amplify-angular": "^3.0.11",

**Comment by oliverandersencox** [comment]
and for the cli version I am on '1.12.0'

**Comment by oliverandersencox** [comment]
to give you some more context, It seems that from looking at the resolvers, that it takes the value of the score field and uses that as the next token.

In which case, if there are ever scores of the same value, it will cause the same results to be fetched, which is happening in my case.

I need the sort order to be done by 'score' so that I can effectively rank my results. There will often be times when the results are equal. 

Is there another way to set the resolvers to use another field as the nexttoken?

**Comment by oliverandersencox** [comment]
@sammartinez any update on this. It is a real blocker for my ranking system

**Comment by sammartinez** [comment]
@oliverandersencox I apologize that I never circled back on this issue. Is this still a use case you are looking to use ? If so, this seems to be related to Amplify CLI but wanted to touch base on this prior to transferring the issue

**Comment by dogsonacid** [comment]
still an issue
