### ISSUE TITLE
Uncaught Error: More than one or no providers are configured

### ISSUE THREAD

**Issue by 24jr** [aws-amplify/amplify-js#3928]
I'm trying to use text translation from amplify predictions in vue and while following docs I'm getting error 

"Uncaught Error: More than one or no providers are configured, Either specify a provider name or configure exactly one provider"

I do have other stuff going on which may be influencing issue such as analytics. Trying to just call as basic as possible to get working here. Also not sure if I'm posting this issue as I'm supposed or not this is my first time doing this.

```import Vue from "vue";
import "./plugins/vuetify";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import "./registerServiceWorker";
import Amplify, * as AmplifyModules from "aws-amplify";
import { AmplifyPlugin } from "aws-amplify-vue";
import awsmobile from "./aws-exports";
import Vuetify from "vuetify";
import Analytics from '@aws-amplify/analytics';
import Predictions, { AmazonAIPredictionsProvider } from '@aws-amplify/predictions';
Amplify.addPluggable(new AmazonAIPredictionsProvider());
import awsconfig from './aws-exports';
Amplify.configure(awsconfig);

  Predictions.convert({
  translateText: {
    source: {
      text: 'hello',
      language : "en" // defaults configured on aws-exports.js
      // supported languages https://docs.aws.amazon.com/translate/latest/dg/how-it-works.html#how-it-works-language-codes
    },
    targetLanguage: "fr"
    }
  }).then(result => console.log(JSON.stringify(result, null, 2)))
    .catch(err => console.log(JSON.stringify(err, null, 2)))
Analytics.configure();
Analytics.autoTrack('session', {
  enable: true,
  attributes: {
      attr: 'attr'
  },
});
Analytics.autoTrack('pageView', {
  enable: true,
  eventName: 'pageView',
  attributes: {
      attr: 'attr'
  },
  type: 'SPA',
});
Amplify.configure(awsmobile);
Vue.use(AmplifyPlugin, AmplifyModules);
Vue.config.productionTip = false;
Vue.use(Vuetify, {
  theme: {
    primary: "#00f",
    secondary: "#000",
  }
}),
  new Vue({
    router,
    store,
    render: h => h(App)
  }).$mount("#app");
```

**Comment by elorzafe** [comment]
@24jr I can confirm the issue is that you can multiple instances of @aws-amplify/core on your `node_modules` directory.  can you changing your packages.json and re-install again? (`npm install` or `yarn`)

**Comment by 24jr** [comment]
sorry this may be obvious how to do for most people but I don't know how to do that. What am I changing in package.json? when I upgrade I usually just run `npm install -g @aws-amplify/cli` and assumed that would overwrite old stuff. Should I run `npm uninstall -g @aws-amplify/cli` or something like that first. Is that what I should be doing right now?

**Comment by elorzafe** [comment]
@24jr No worries, try replacing the whole package.json file with this

```
{
  "name": "roze",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "aws-amplify": "^1.1.36",
    "aws-amplify-vue": "^0.2.14",
    "core-js": "^2.6.5",
    "register-service-worker": "^1.6.2",
    "vue": "^2.6.10",
    "vue-router": "^3.0.3",
    "vuetify": "^1.5.18",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.7.0",
    "@vue/cli-plugin-eslint": "^3.7.0",
    "@vue/cli-plugin-pwa": "^3.7.0",
    "@vue/cli-service": "^3.7.0",
    "@vue/eslint-config-prettier": "^4.0.1",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "node-sass": "^4.9.0",
    "sass-loader": "^7.1.0",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.1",
    "vue-cli-plugin-vuetify": "^0.5.0",
    "vue-template-compiler": "^2.5.21",
    "vuetify-loader": "^1.0.5"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "@vue/prettier"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ]
}
```

**Comment by 24jr** [comment]
Still getting same errors after doing this

**Comment by elorzafe** [comment]
@24jr I did this to make it work Predictions on a Vue App.

- First I created an app called hello-vue using vue cli `vue create hello-vue`
- Inside of `hello-vue` directory I did `amplify init` and then `amplify predictions add` and select `Convert` and then `Translate text into a different language` as you did
- on `main.js` file I have this

```javascript
import Vue from 'vue'
import App from './App.vue'
import Amplify, * as AmplifyModules from 'aws-amplify'
import { AmplifyPlugin } from 'aws-amplify-vue'
import awsconfig from './aws-exports'
import { AmazonAIPredictionsProvider } from '@aws-amplify/predictions';

Vue.config.productionTip = false
Amplify.configure(awsconfig)
Amplify.addPluggable(new AmazonAIPredictionsProvider());
Vue.use(AmplifyPlugin, AmplifyModules)

new Vue({
  render: h => h(App)
}).$mount('#app')
```

- On `App.vue` file I have this

```vue
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
    <HelloWorld msg="Welcome to Your Vue.js App"/>
  </div>
</template>

<script>
import HelloWorld from './components/HelloWorld.vue'
import { components } from 'aws-amplify-vue'
export default {
  name: 'app',
  components: {
    HelloWorld,
    ...components
  }
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
``` 
- Finally on `components/HelloWorld.vue` I have this

```vue
<template>
  <div class="hello">
    <div id="app-5">
      <button v-on:click="convertText">Convert text</button>
    </div>
    <h1>{{ msg }}</h1>
  </div>
</template>

<script>

export default {
  name: "HelloWorld",
  props: {
    msg: String
  },
  methods: {
    convertText: function() {
      this.$Amplify.Predictions.convert({
        translateText: {
            source: {
              text: 'hello'
            }
          } 
      }).then(result => console.log({result}));
    }
  }
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
a {
  color: #42b983;
}
</style>

```

I hope this helps

**Comment by 24jr** [comment]
I still get same error. I'm sure it works fine by itself but prob problem with having all the amplify stuff run collectively

**Comment by rpostulart** [comment]
I have the same issue after upgrading from 2.7 to the latest 3.x

**Comment by thomasdowell** [comment]
Updating from version 3.1.21 to 3.1.22 and the latest 3.1.23 resulted in this error.

**Comment by Paulo-W** [comment]
I had the same problem with the new version. Adding the following to my `main.ts` this seemed to fix it for me.
```
Amplify.configure(awsconfig);

Amplify.register(Predictions);
Predictions.addPluggable(new AmazonAIPredictionsProvider());
```

**Comment by InheritxSolution** [comment]
I am still facing this issue.

**Comment by adi518** [comment]
I've just spent almost 5 hours debugging this and still no solution.

**Comment by Yuanyuan-Shen** [comment]
> I had the same problem with the newest 3.* version. Adding the following to my `main.ts` seemed to fix it for me.
> 
> ```
> Amplify.configure(awsconfig);
> 
> Amplify.register(Predictions);
> Predictions.addPluggable(new AmazonAIPredictionsProvider());
> ```

Where to find main.ts?

**Comment by Yuanyuan-Shen** [comment]
I followed the tutorial to create a web app with language translation and text-to-speech function, and met `Error: More than one or no providers are configured, Either specify a provider name or configure exactly one provider`
![Error- More than one or no providers](https://user-images.githubusercontent.com/80495585/141215828-9de68694-d586-4170-9dad-c67959257624.JPG)

Has anyone found the solution?

**Comment by thomasdowell** [comment]
Amplify (`^4.3.20`) was throwing the error when my code was as follows:

```
import { AmazonAIPredictionsProvider } from "@aws-amplify/predictions";
import { Amplify, API, Auth } from "aws-amplify";
import awsExports from "./aws-exports";

Amplify.configure(amplifyConfig);
Amplify.addPluggable(new AmazonAIPredictionsProvider());
API.configure(amplifyConfig);
Auth.configure(amplifyConfig);
```

Simply moving `Amplify.addPluggable(new AmazonAIPredictionsProvider());` under the three .configure methods fixed the issue:

```
Amplify.configure(amplifyConfig);
API.configure(amplifyConfig);
Auth.configure(amplifyConfig);
Amplify.addPluggable(new AmazonAIPredictionsProvider());
```

**Comment by Manas-E** [comment]
> I had the same problem with the newest 3.* version. Adding the following to my `main.ts` seemed to fix it for me.
> 
> ```
> Amplify.configure(awsconfig);
> 
> Amplify.register(Predictions);
> Predictions.addPluggable(new AmazonAIPredictionsProvider());
> ```

Thanks man! It fixed my issue, you're awesome : )

**Comment by apple-blossom** [comment]
I have same issue while working with react native and aws-amplify 5
