### ISSUE TITLE
AppSync upload to S3 not working

### ISSUE THREAD

**Issue by joebernard** [aws-amplify/amplify-js#3929]
** Which Category is your question related to? **
API / AppSync

** What AWS Services are you utilizing? **
AppSync and S3

** Provide additional details e.g. code snippets **
I'm trying to utilize automatic uploads from AppSync to S3 using Amplify. It seems like it is creating a nearly empty object in S3. The resulting object only contains 234.0 B. Here are the relevant bits of my schema.

```
input S3ObjectInput {
  bucket: String!
  key: String!
  region: String!
  localUri: String
  mimeType: String
  visibility: Visibility
}

enum Visibility {
  public
  private
}

input PostInput {
  id: ID
  file: S3ObjectInput
}

type Mutation { 
capturePostContent(input: PostInput): PostConnection!
}
```

I've also added `complexObjectsCredentials: () => Auth.currentCredentials()` to my `AWSAppSyncClient` creation.

It seems to have the needed access as it creates an object with the correct key, but it doesn't seem to include the object data. That file should be +300 KB, not 234 B. What am I doing wrong?

**Comment by joebernard** [comment]
Is there any further info I can provide?

![image](https://user-images.githubusercontent.com/1540653/64440611-46a0e000-d09a-11e9-8c22-7e93dbfb0299.png)

**Comment by joebernard** [comment]
Well I see some of the problem now. It is writing the `localUri` string as the contents of the file stored in S3 instead of the binary data of the image. What is causing this?

**Comment by joebernard** [comment]
Note that I did not set this up using the Amplify CLI. I created my schema manually and am using the following two packages:
```
"aws-appsync": "^2.0.0",
"aws-appsync-react": "^2.0.0",
```

Request mapping:
```
{
    "version": "2017-02-28",
    "operation": "Invoke",
    "payload": {
        "arguments":  $utils.toJson($context.arguments),
        "identity": $utils.toJson($context.identity)
    }
}
```

Response mapping:
```
$util.toJson($context.result)
```

Here is a sample of the data I'm pasing for the `S3ObjectInput` (file):
```
{"bucket":"my-bucket","key":"7d16070e-1e9d-4872-a19c-e7163460a242.jpg","region":"us-east-1","mimeType":"image/jpeg","localUri":"file:///Users/joebernard/Library/Developer/CoreSimulator/Devices/2F2F4FD3-574E-40D7-BE6B-7080E926E70A/data/Containers/Data/Application/DFBDFDCE-7FBD-4A33-9D40-51D0FBEFAE42/Library/Caches/Camera/F6F16308-180B-4423-9613-495E614968B5.jpg","visibility":"private"}
```
`7d16070e-1e9d-4872-a19c-e7163460a242.jpg` is created in my bucket. If I open that file in a text editor, the contents are:

`file:///Users/joebernard/Library/Developer/CoreSimulator/Devices/2F2F4FD3-574E-40D7-BE6B-7080E926E70A/data/Containers/Data/Application/DFBDFDCE-7FBD-4A33-9D40-51D0FBEFAE42/Library/Caches/Camera/F6F16308-180B-4423-9613-495E614968B5.jpg`

It will write whatever the literal value of `localUri` is into the contents of the file instead of the file specified in that path.

**Comment by joebernard** [comment]
My understanding of this feature is evolving. I took a look at the [sample React app](https://github.com/aws-samples/aws-amplify-graphql). In it, the `localUri` field is being set to the file object returned from the form `<input type="file"/>`. I believe that implements `blob` and has a couple additional properties.

My app is built in React Native, and I'm attempting to save an image from `react-native-camera`. I don't receive a `file` type like what is shown in the sample app. It seems `localUri` should be passed actual binary data, NOT just the uri of the file on the device (the name of this property seemed to indicate it wanted an actual local uri to the file on the device).

Do I have to manually build a file object (`blob`) to pass into `localUri`? Is this feature compatible with React Native? The [documentation](https://aws-amplify.github.io/docs/js/api) isn't clear here.

**Comment by dabit3** [comment]
@joebernard Can you also show the API call that you are attempting to make?

**Comment by joebernard** [comment]
@dabit3 Here are the main components of my API call. This is spread out over several files (I'm using `compose`).

```javascript
const capturePostContentGQL = gql`
  mutation CapturePostContent($input: PostInput!) {
    capturePostContent(input: $input) {
      post {
        ...Post
      }
    }
  }
  ${fragments.post}
`;

// This is composed into my RN component
CapturePostContent = graphql(capturePostContentGQL, {
  props: props => ({
    ...props,
    capturePostContent: async ({ id, file }) => {
      await props.mutate({
        variables: { input: { id, file } }
      });
    }
  })
}

// In the RN component
capturePostContent({
  id: 123,
  file:  {
    bucket: "my-bucket",
    key: "postImage.jpg",
    region: "us-east-1",
    mimeType: "image/jpeg",
    localUri: "file:///Users/joebernard/Library/Developer/CoreSimulator/Devices/2F2F4FD3-574E-40D7-BE6B-7080E926E70A/data/Containers/Data/Application/DFBDFDCE-7FBD-4A33-9D40-51D0FBEFAE42/Library/Caches/Camera/F6F16308-180B-4423-9613-495E614968B5.jpg",
    visibility: "public"
  }
})
```

**Comment by joebernard** [comment]
Solved with a `fetch` to read the content as a `blob` then uploading that blob with `Storage`.

```javascript
const blob = await fetch(localUrl).then(response =>
  response.blob(),
);
Storage.put(myKey, blob, {
  bucket,
})
```
