### ISSUE TITLE
Amplify Manual Auth.signUp function doesn't triggering for lambda

### ISSUE THREAD

**Issue by anarerdene** [aws-amplify/amplify-js#3939]
** Which Category is your question related to? **

** What AWS Services are you utilizing? **
Cognito, Lambda
** Provide additional details e.g. code snippets **

**Comment by sammartinez** [comment]
@anarerdene Can you provide more detail? Which version of `aws-amplify` are you using. Also, which framework/version you are seeing this issue on. Want to see if we can narrow this down

**Comment by anarerdene** [comment]
hi @sammartinez ,

1.
I'm using amplify manual auth.signup function like this...
![image](https://user-images.githubusercontent.com/2210568/64014978-14e9bf80-cb56-11e9-92d4-906d55d2c005.png)

(it means i'm not using Cognito Hosted UI for Sign-Up and Sign-In ...)

2. Then i created lambda function like this.

`var aws = require('aws-sdk');
var ddb = new aws.DynamoDB({apiVersion: '2012-10-08'});

exports.handler = async (event, context) => {
    console.log(event);

    let date = new Date();

    const tableName = process.env.TABLE_NAME;
    const region = process.env.REGION;
    const defaultAvi = 'https://YOUR/DEFAULT/IMAGE';
    
    console.log("table=" + tableName + " -- region=" + region);

    aws.config.update({region: region});

    // If the required parameters are present, proceed
    if (event.request.userAttributes.sub) {

        // -- Write data to DDB
        let ddbParams = {
            Item: {
                'id': {S: event.request.userAttributes.sub},
                '__typename': {S: 'User'},
                'picture': {S: defaultAvi},
                'username': {S: event.userName},
                'name': {S: event.request.userAttributes.name},
                'skillLevel': {N: '0'},
                'email': {S: event.request.userAttributes.email},
                'createdAt': {S: date.toISOString()},
            },
            TableName: tableName
        };

        // Call DynamoDB
        try {
            await ddb.putItem(ddbParams).promise()
            console.log("Success");
        } catch (err) {
            console.log("Error", err);
        }

        console.log("Success: Everything executed correctly");
        context.done(null, event);

    } else {
        // Nothing to do, the user's email ID is unknown
        console.log("Error: Nothing was written to DDB or SQS");
        context.done(null, event);
    }
};`


lambda test is working ok.
