### ISSUE TITLE
Adding a validationData support for Auth.signIn?

### ISSUE THREAD

**Issue by id-kemo** [aws-amplify/amplify-js#394]
I have noticed that very recently  #175 you have added validationData support for Auth.signUp, any chance you could add support for Auth.signIn as well?

I believe this could be beneficial for many developers since this part of application can be targeted by robots as well so for example reCaptcha response could be send to Lambda via validationData... 

Thank you for considering this feature!

**Comment by manueliglesias** [comment]
Hi @id-kemo 

This is a good suggestion, thanks!

**Comment by manueliglesias** [comment]
Closed by #2284
