### ISSUE TITLE
Authentication control shows error when signing in

### ISSUE THREAD

**Issue by gsans** [aws-amplify/amplify-js#3940]
**Describe the bug**
When trying to sign in using my phone I enter the login details but it shows the error: "Username cannot be empty".

**To Reproduce**
1. Open https://master.dly6upmcbfr8l.amplifyapp.com
2. Enter gsans/Pa55w0rd on android Huawei P20

**Expected behavior**
User logs in normally and application loads.

**Screenshots**
Screenshot available
![Screenshot_20190829-193848](https://user-images.githubusercontent.com/4660316/63963531-89a8f500-ca95-11e9-997d-6adb24d981b5.jpg)

**Smartphone**
 - Device: Huawei P20
 - OS: android v8
 - Browser: Chrome
 - Version: 75.0.3770.101

**Context**
Using aws-amplify-vue version of the authentication control without any special configuration.

**Comment by gsans** [comment]
I think this may could related to using a pre-stored password selection shown in the phone. Usually this would trigger the change detection on the input and update the username field but it seems is missing that type of event.

**Comment by gerrytsui** [comment]
Yes, I tracked down where the username is being "blanked"  back in June . and we have been patching the sign-in.component.core.js with the following ( at around line #45 )


 node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-in-component/sign-in.component.core.js


            this._show = includes(['signIn', 'signedOut', 'signedUp'], authState.state);
            //if (typeof authState.user === 'string' ) this.username = authState.user ? authState.user.username || '' : '';
            this.username = authState.user ? authState.user.username || (this.username  || '') :    this.username || '';
            this.email = authState.user ? authState.user.email || '' : '';

**Comment by gerrytsui** [comment]
Also,in additional to the .js patch in my last post. Here is the TypeScript fix that I fixed in my fork
https://github.com/gerrytsui/amplify-js/blob/master/packages/aws-amplify-angular/src/components/authenticator/sign-in-component/sign-in.component.core.ts

I was going to ask for a PR, but been too busy to full test it.

**Comment by ericclemmons** [comment]
@gsans We've pulled this fix into `@aws-amplify/ui-vue`.  Can you give that a go and let us know if you're still experiencing issues?
> https://docs.amplify.aws/ui/q/framework/vue

**Comment by gsans** [comment]
Great. It's working now. Thanks!
