### ISSUE TITLE
[Analytics] Kinesis pageView autotrack data empty

### ISSUE THREAD

**Issue by goatandsheep** [aws-amplify/amplify-js#3942]
**Bug Description**

When using Kinesis as an analytics provider, the Data attribute is not being populated for autotrack, causing it to error and not get sent at all.

```
[DEBUG] AWSKineisProvider - putting records to kinesis with records 
{
    0: {
        Data: undefined
        PartitionKey: "partition-us-east-1:905799a4-bc0c-4af1-814b-b30ecb370dba"
    }
}
[DEBUG] AWSKineisProvider - Failed to upload records to Kinesis MissingRequiredParameter: Missing required key 'Data' in params.Records[0]
```

**To Reproduce**
1. Setup Kinesis
2. Setup autotrack on `pageView`
3. Change page

**Expected behavior**
`pageView` event is uploaded to Kinesis

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 1.1.36
 - Framework: Vue

**Additional context**
[Code](https://gist.github.com/goatandsheep/9c3cd6c57ad91cc286405749be51dcdb)

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by goatandsheep** [comment]
Same issue for `MediaAutoTrack`

**Comment by jordanranz** [comment]
May be related to: https://github.com/aws-amplify/amplify-js/issues/4151

**Comment by goatandsheep** [comment]
It very likely is. Let's close this out marking this as duplicate as that one

**Comment by jordanranz** [comment]
Closing in favor of #4151
