### ISSUE TITLE
Styles for create new account phone number select element for Vue are broken

### ISSUE THREAD

**Issue by gsans** [aws-amplify/amplify-js#3944]
**Describe the bug**
Style is broken for country code drop down for telephone during create account flow for authentication component.

**To Reproduce**
1. Use authenticator component
2. Create new user

**Expected behavior**

**Screenshots**
Broken vs Fixed
![BeFunky-collage (4)](https://user-images.githubusercontent.com/4660316/63981934-482e3f00-cac1-11e9-9d2e-52ecaeb8bbc8.jpg)

**Desktop (please complete the following information):**
- OS: macOS 10.13.6
- Browser: Chrome 76.0.3809.100 (Official Build) (64-bit)
- aws-amplify-vue: ^0.2.14

**Additional context**
It may be caused for the font type used by default by Vue CLI.

**Sample code**
CSS that fixes the issues:

```CSS
.SelectInput__selectInput___1I_W8>select {
  margin-top: 10px;
  margin-right: -10px;
  padding: 16px 20px 16px 16px;
  background-position: calc(100% - 10px) calc(1em + 8px),calc(100% - 4px) calc(1em + 8px),calc(100% - 2.5em) .5em !important;
```

**Comment by sammartinez** [comment]
@gsans thanks for the code snippet on this, we are tracking this internally. We do accept PRs as well if you had time to fix this bug

**Comment by ericclemmons** [comment]
@gsans I created a demo here to reproduce using the latest CLI/Vue/Amplify:
https://github.com/aws-amplify/amplify-js/issues/3944

It's not quite matching up with what you're seeing:

> ![Screen Shot 2020-01-21 at 1 17 32 PM](https://user-images.githubusercontent.com/15182/72843972-766b1180-3c50-11ea-9dbd-80a273a15f33.png)

Can you visit the sandbox and screenshot what you see?

I'm also interested to see what the computed properties are, especially if there's a font difference:
> ![Screen Shot 2020-01-21 at 1 20 10 PM](https://user-images.githubusercontent.com/15182/72844174-d792e500-3c50-11ea-9e09-26a290052d98.png)

**Comment by ericclemmons** [comment]
I was primarily looking at the weird height differences, but I did confirm that adjusting `padding` and `background-position` to match your code the caret doesn't overlap as much:

> ![Screen Shot 2020-01-21 at 1 23 23 PM](https://user-images.githubusercontent.com/15182/72844426-57b94a80-3c51-11ea-8ef1-57e87194e933.png)

```css
padding: 16px 20px 16px 16px;
  background-position: calc(100% - 10px) calc(1em + 8px),calc(100% - 4px) calc(1em + 8px),calc(100% - 2.5em) .5em !important;
```

The `margin` changes must be for the height bugs you're seeing, but I need your help to reproduce it.

**Comment by ericclemmons** [comment]
Confirmed the caret padding issue exists across multiple browsers:
> https://www.browserstack.com/screenshots/5bd57d5d40d9788add4733f69e3010ec3eaab064

I could not reproduce the vertical padding screenshot provided by @gsans. (It may have been addressed since)

**Comment by gsans** [comment]
Thanks for the follow up.

It seems the input field total width issue that I missed initially was
fixed as well.

Once the caret is fixed is good to go.

Cheers!
Gerard.
