### ISSUE TITLE
Amplify API returns Network Error with authRole but works without authentication

### ISSUE THREAD

**Issue by rfdc** [aws-amplify/amplify-js#3947]
**Describe the bug**
I'm currently making 2 apps. I've implemented `API.post` on the first one and it worked as expected. But few weeks later I have created a second app, done everything exactly the same and the `API.post` with Authentication (`Restrict API access Yes`) does not work, but it work if I do not `Restrict API access `. 

**Dependencies**
```
"dependencies": {
....
  "aws-amplify": "^1.1.36",
  "aws-amplify-react": "^2.3.12",
  "react": "^16.8.6",
...
}
```
**Network Error**
The picture below shows the API working on the first try then once I add Auht, it stop working. 
![amply-api-network-error](https://user-images.githubusercontent.com/32999759/63997964-93346a80-cb32-11e9-97f2-f6b0e1b71fba.jpeg)

**Cloudwatch log for API**
![image](https://user-images.githubusercontent.com/32999759/63998497-d80cd100-cb33-11e9-97c9-2f5de02ea4dd.png)

**Sample code**
```
  testApi = async () => {
    console.log('in testApi');
    try {
      const response =  await API.post('rybwAdminSendEmailApi', '/sendEmailWhenClientIsApproved', {
        body: {
          status: "Approved"
        }
      });      
      console.log('testApi:', response);
    } catch (error) {
      console.log('testApi-ERROR:', error);
      const logger = new Logger();
      logger.error('Logger-ERROR:', error);
    }    
  }
```
***Screenshot of debug mode***
![image](https://user-images.githubusercontent.com/32999759/63998342-78aec100-cb33-11e9-8d16-ddf736076b1b.png)

***AIM Role***
I've compared both authRole and they look similar.

Anything else that I can do to fix this error?

Thanks

**Comment by sammartinez** [comment]
@rfdc Can you paste the roles to us and comment out the account information?

**Comment by rfdc** [comment]
Hi @sammartinez, Thanks for your fast response:
This is the `AuthRoleArn` for the app that is not working:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "execute-api:Invoke"
            ],
            "Resource": [
                "arn:aws:execute-api:ap-southeast-2:000:000/ENVIROMENT/POST/ENDPOINT/*",
                "arn:aws:execute-api:ap-southeast-2:000:000/ENVIROMENT/POST/ENDPOINT",
                "arn:aws:execute-api:ap-southeast-2:000:000/ENVIROMENT/POST/ENDPOINT/*",
                "arn:aws:execute-api:ap-southeast-2:000:000/ENVIROMENT/POST/ENDPOINT",
                "arn:aws:execute-api:ap-southeast-2:000:000/ENVIROMENT/POST/ENDPOINT/*",
                "arn:aws:execute-api:ap-southeast-2:000:000/ENVIROMENT/POST/ENDPOINT"
            ],
            "Effect": "Allow"
        }
    ]
}
```
It is similar to the app that is working.

BTW, should I delete any information from the previous post?

Thanks in advance.

**Comment by rfdc** [comment]
Hi @sammartinez , Any updates on this?
Thanks

**Comment by haverchuck** [comment]
@rfdc Have you tried clearing your localstorage and re-signing into the app that isn't working?

**Comment by rfdc** [comment]
Hi @haverchuck, yeap, I have cleared the localstorage and also stopped and re-started the app

**Comment by rfdc** [comment]
Hi @haverchuck @sammartinez , I've made a new endpoint on both apps and started them on Chrome. One of them still working fine but the other still giving the same issue but Chrome gave me more info:
`POST https://ENDPOINT.execute-api.ap-southeast-2.amazonaws.com/APPNAME/sendEmailWhenClientStatusIsUpdated 403`
`Access to XMLHttpRequest at 'https://ENDPOINT.execute-api.ap-southeast-2.amazonaws.com/APPNAME/sendEmailWhenClientStatusIsUpdated' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Both apps use the exactly same boilerplate. 

Hope that points us to the right direction.
Thanks

**Comment by rfdc** [comment]
Hi @powerful23, can you help with this? thanks

**Comment by danmight** [comment]
I'm facing something identical. Anyone figure this out. I keep getting 403 errors trying to use amplify to put something to S3 or use an API I chose to be for authenticated users. If I make the S3 buck public I can put and get just fine. To get around the issue on the API endpoint I mad a cognito authorizer and skipped the IAM role usage but I can't do that with s3 calls that I know of. Also, it shows the roles have "no last activity" on the IAM console, so it's like they are not being invoked properly.
