### ISSUE TITLE
[AUTH/COGNITO] Email Address Case Sensitivity

### ISSUE THREAD

**Issue by JupiterSymphony** [aws-amplify/amplify-js#3949]
**Describe the bug**
This is a bug for the service team. Email addresses are case sensitive, so john@example.com is different from John@example.com. While this does meet RFC5321, it is not the standard expected practice nowadays though as any user would expect to be able to login with whatever case including, believe it or not, on amazon.com (try for yourself). Additionally, users can use it maliciously to impersonate other users by simply changing a letter case and hoping no one notices it. 

**To Reproduce**
1. Create a user in a cognito user pool using an email login setup.
2. Try to sign in with the same email though change a case on a letter in the local part of the email.
3. Doesn't work. Read many other unanswered AWS forum threads years old. 

**Expected behavior**
Emails should be case insensitive for login, though case should maybe be respected on sign up (as some servers do still strictly follow RFC5321)?

**Comment by haverchuck** [comment]
@JupiterSymphony - I have brought this to the service team's attention.

**Comment by bijanmmarkes** [comment]
Agreed @JupiterSymphony - this is annoying and required additional code just to work around it, this should be optional or fixed. Why would the same username be allowed to be created more than once by simply uppercasing or lowercasing a letter, this doesn't make sense and I haven't seen a single website that operates in that way.

**Comment by pbirsinger** [comment]
This is a large issue. Not only is it not expected and took us awhile to track down the issue, it doesn't make sense when this is not how things work almost everywhere else on the web.

**Comment by gavin771** [comment]
Willing to work on a pr for this as this is a high priority for my team.

**Comment by pbirsinger** [comment]
@gavin771 you’d be a hero

**Comment by gakinson** [comment]
Any update on this, we need this feature as well.

**Comment by elorzafe** [comment]
@JupiterSymphony @gakinson from today new User Pools can be created with case insensitivity for username input
More info [here](https://aws.amazon.com/about-aws/whats-new/2020/02/amazon-cognito-user-pools-service-now-supports-case-insensitivity-for-user-aliases)
