### ISSUE TITLE
aws-amplify-react Picker component input overflows

### ISSUE THREAD

**Issue by rogerchi** [aws-amplify/amplify-js#3950]
**Describe the bug**
The Picker component has an input field which overflows because the parent div does not have "position: relative" in its styling.  A previous commit removed this styling.

**To Reproduce**
Use <Picker> component.  See that the clickable input area overflows.

**Expected behavior**
The clickable area is restrained to the button area.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Web
 - Browser: Chrome
 - Version: 76.0.3809.132

**Comment by rahulbaisla** [comment]
I found the same behavior.

Added following to my  project's theme  and exporting it works for me .

--------------------------------------------------------
 export const pickerPicker = {
    position: 'relative'
 };

const AppTheme = {
    pickerPicker: pickerPicker
}

export default AppTheme;
--------------------------------------------------------

**Comment by ashika01** [comment]
Closing the issue on back of the merged PR. Thank you for brining the issue up.
