### ISSUE TITLE
Is it possible to upload multiple images at the same time and resize with react PhotoPicker?

### ISSUE THREAD

**Issue by thenderson55** [aws-amplify/amplify-js#3953]
** Which Category is your question related to? **
Photo uploading

** What AWS Services are you utilizing? **
aws-amplify-react PhotoPicker UI component

** Provide additional details e.g. code snippets **
Is it possible to upload multiple images at the same time with react PhotoPicker?

Also, is there a simple way to resize images before upload or in AWS console?

**Comment by haverchuck** [comment]
@thenderson55 This isn’t currently possible, so I’m labeling this issue as a feature request.

**Comment by iartemiev** [comment]
@thenderson55 as far as resizing, you could do that with a Lambda trigger

Check out:

https://aws-amplify.github.io/docs/cli-toolchain/quickstart#storage-examples

And: 

https://aws.amazon.com/blogs/compute/resize-images-on-the-fly-with-amazon-s3-aws-lambda-and-amazon-api-gateway/

**Comment by sammartinez** [comment]
Resolving this request as per @iartemiev's recommendation. This is what we recommend as a solution.
