### ISSUE TITLE
Using Cognito groups to control access to API Gateway methods

### ISSUE THREAD

**Issue by udkyo** [aws-amplify/amplify-js#3954]
** Which Category is your question related to? **
Limiting access to API Gateway methods to specific cogito groups.

** What AWS Services are you utilizing? **
Cognito, API Gateway, Lambda

** Provide additional details e.g. code snippets **
I have created a user pool and identity pool in Cognito. In the identity pool I have auth and unauth roles configured, I also enable access to unauthenticated identities, and in the cognito authentication provider I choose role from token and use the default role for resolution. In the user pool there is an app client with ADMIN_NO_SRP_AUTH enabled, I also have users and groups, the groups have roles attached and these roles are referenced within the API Gateway resource policy: e.g.

````
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::xxxxxx:role/_yyyyyyy_admins"
            },
            "Action": "execute-api:Invoke",
            "Resource": "arn:aws:execute-api:us-east-1:xxxxxxx:nnnnnn/*/PUT/*"
        },
````

The roles have a trusted entity provided: cognito-identity.amazonaws.com with the following conditions:

StringEquals | cognito-identity.amazonaws.com:aud  | (my_idpool)
ForAnyValue:StringLike | cognito-identity.amazonaws.com:amr | authenticated

I'm using API.get and API.put from the Amplify library and passing Auth.currentAuthenticatedUser().signInUserSession.idToken.jwtToken in the "Authorization" header field.

I think that's everything relevant in terms of background info... The problem I'm having with this setup is that the roles don't seem to be being used for communicating when I make the API.get and API.put calls. If I put my valid, unexpired jwtToken into postman and call one of the methods I've granted the cognito group access to, I get the following response:

````
"Message": "User: anonymous is not authorized to perform: execute-api:Invoke on resource: arn:aws:execute-api:us-east-1:***********:xxxxxxx/api/GET/post"
````

I can't do anything with the API unless I add in a "Principal: *" component in the API GW resource policy, which seems wrong to me - I'm under the impression my unauth users should be using the unauth role, auth users should be using the auth role, and anybody in groups should be getting permissions granularly from statements I've added relating to those groups. However, it seems that none of the roles are being used at all and it's only when I open it up for * that I can do anything at all.

I've been banging my head against a brick wall on this one for a few days now. I've seen some people mention using AWS_IAM for the method request authorizer (rather than the Cognito authorizer I'm using just now) but if I switch to that, the response that comes back is:

````
"message": "Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. 
````

Am I doing something stupid here? Can anybody who has something similar working point out where I've gone wrong? I can obviously validate the token in my code, check the groups and handle what they have access to there, but that's a much messier way of doing it, I'd rather control it all with IAM roles and policies if possible.

**Comment by udkyo** [comment]
It turns out I'd done a number of things wrong. Here are all my learnings for the benefit of anyone who finds themself in a similar situation and arrives here from a search:

Changing the gateway methods from using the Cognito authorizer to AWS_IAM was the correct play, but I continued passing an Authorizer header in the API.get/put calls, wrongly assuming this still required. By switching to AWS_IAM and **removing the header** role assumption began working correctly. 

Another thing I'd done wrong was using Federated for the Principal key. "AWS" was instead the correct choice (I'd originally used AWS, but had gone back and forth between that and Federated when things weren't working correctly to troubleshoot)

Finally, in my API GW resource policy I needed a Principal "*" with execute-api:Invoke on my options methods to let anonymous users browse correctly.

**Comment by chai86** [comment]
Hi @udkyo , would you be able to share your bucket policy please? I believe the "Principal" key is tripping me up and i don't want to use "*" as my bucket will be public!! Also I have a user pool which is authenticated with Amazon Cognito, but i'd like to allow users to DeleteObjects from S3, which they aren't able to at the moment

**Comment by Zilvinaskli** [comment]
I'm wondering if there's a simple way to restrict some endpoints for some user groups when users are already authenticated through Cognito.

**Comment by caoheyang** [comment]
When one of my users belongs to multiple user groups, I want the user to have a collection of multiple group permissions. Can you give me ideas about this knowledge? Thanks a lot , I have been troubled for a long time.
