### ISSUE TITLE
Predictions Image labeling from React Native / Expo

### ISSUE THREAD

**Issue by dabit3** [aws-amplify/amplify-js#3958]
** Which Category is your question related to? **
Predictions

** What AWS Services are you utilizing? **
Rekognition

** Provide additional details e.g. code snippets **
When trying to call the following predictions method:

```
  Predictions.identify({
    labels: {
      source: {
        file: blob
      },
      type: "ALL"
    }
  })
```

I've been running into various errors, depending on the file type I pass in. I've tried passing in blob, uri, and base64.

[Here](https://gist.github.com/dabit3/84c7e90743e59a272cd41c3150b1b289
) is my code.

Here is where I think the problem is. In `configureSource` [here](https://github.com/aws-amplify/amplify-js/blob/50f697bc4075ea719b692fba8426006766300d69/packages/predictions/src/Providers/AmazonAIIdentifyPredictionsProvider.ts#L33), the code is referencing `blobToArrayBuffer` in [this file](https://github.com/aws-amplify/amplify-js/blob/master/packages/predictions/src/Providers/Utils.ts#L30)

I don't think this will work in React Native or Expo.

The error I'm getting with the above code is:

```
Error: FileReader.readAsArrayBuffer is not implemented
```

**Comment by stevelizcano** [comment]
Just to add, this is also occurring for Text Identification (OCR) from an Image.

The input TS types are listed as: 
`bytes: Buffer | ArrayBuffer | Blob | string;`

No matter what is put in, the `configureSource` function will always call FileReader.readAsArrayBuffer

However RN now supports in fetch converting a response to an array buffer with ex:

`   const response = await fetch(photo.uri);`

   ` const arrayBuffer = await response.arrayBuffer()`

In TS this returns type ArrayBuffer, which is the format that Predictions is sending after conversion for all non-S3 types.

This _should_ work if the code can be updated to check if the input type is already an ArrayBuffer, and requiring ArrayBuffer ONLY (or S3) for RN image predictions.

I can do a pull request for this also and test.

**Comment by dabit3** [comment]
Hi @stevelizcano, thanks for the valuable insight. If you feel like giving it a shot, that would be great and I would be happy to test along with you.

**Comment by dabit3** [comment]
Ok, [here's](https://gist.github.com/dabit3/5061789aa0565410b043d3ff96351555) an initial implementation that we can test.

**Comment by dabit3** [comment]
@stevelizcano -> Update: We've tested the above implementation and it works.

The only nuance is when passing the array buffer to the Rekognition service, the buffer has to be 5242880 bytes or smaller.

In the documentation we should mention this, and in library we should return an error if the image is too large, and recommend resizing the image before sending the image.

In my testing, most of the images on my camera roll that were downloaded from the internet worked fine, but because the images taken from my iPhone X are so high resolution, they were too large. I used the Expo [Image Manipulator](https://docs.expo.io/versions/latest/sdk/imagemanipulator/) API to resize the image before sending it over the wire (resize the width & height to be 1/2 or 1/2) and that worked great.

**Comment by matapo** [comment]
Hi guys, any updates on that?

**Comment by kneekey23** [comment]
hey @matapo just use storage to upload your image to s3 first. Example [here](https://github.com/kneekey23/WebSummitPredictions/blob/master/screens/IdentifyScreen.js)

**Comment by matapo** [comment]
> hey @matapo just use storage to upload your image to s3 first. Example [here](https://github.com/kneekey23/WebSummitPredictions/blob/master/screens/IdentifyScreen.js)

I am using this at the moment. However, I would like to avoid this extra step.

**Comment by matapo** [comment]
> @stevelizcano -> Update: We've tested the above implementation and it works.
> 
> The only nuance is when passing the array buffer to the Rekognition service, the buffer has to be 5242880 bytes or smaller.
> 
> In the documentation we should mention this, and in library we should return an error if the image is too large, and recommend resizing the image before sending the image.
> 
> In my testing, most of the images on my camera roll that were downloaded from the internet worked fine, but because the images taken from my iPhone X are so high resolution, they were too large. I used the Expo [Image Manipulator](https://docs.expo.io/versions/latest/sdk/imagemanipulator/) API to resize the image before sending it over the wire (resize the width & height to be 1/2 or 1/2) and that worked great.
> 
> We'll be adding this update to the library as soon as possible.
> 
> In the meantime, if anyone needs to use Predictions with images they will need to upload to S3 first and the pass in the Amazon S3 key from project bucket.

Did you add this update?

**Comment by dherbig** [comment]
I'm also trying to make it so that I pass an image directly from my phone (Expo / React Native) to Rekognition. I've been trying to circumvent this by sending my requests through Lambda 

> In the meantime, if anyone needs to use Predictions with images they will need to 
> upload to S3 first and the pass in the Amazon S3 key from project bucket.

[Documentation **explicitly** states that this is not only possible, but recommended. (Bullet point 2)](https://docs.aws.amazon.com/rekognition/latest/dg/operation-latency.html).  When will you fix this problem?
