### ISSUE TITLE
Object.assign is not a function

### ISSUE THREAD

**Issue by BardiaN** [aws-amplify/amplify-js#3960]
**Describe the bug**
TypeError · Object.assign is not a function
../node_modules/@aws-amplify/cache/lib/StorageCache.js:37t.e

* @param config - the configuration of the cache
--
  | */
  | function StorageCache(config) {
  | this.config = Object.assign({}, config);
  | this.cacheCurSizeKey = this.config.keyPrefix + 'CurSize';
  | this.checkConfig();
  | }

**To Reproduce**
Not sure how it happens, but we have used aws-amplify in our project and this error has been happening quite often.

**Expected behavior**
Works normally.

**Screenshots**
<img width="1280" alt="Screenshot 2019-09-02 at 11 13 54" src="https://user-images.githubusercontent.com/1978153/64103762-307de180-cd73-11e9-815b-9edb99b74ffa.png">

**Smartphone (please complete the following information):**
 - Device: Android Smartphones 
 - OS: Android 5.1 or Android 6
 - Browser Chrome Mobile(39.0.0)/ Chrome Mobile WebView(43.0.0)/ Samsung Internet (3.3)

**Additional context**
It seems that it's only happening in Android 5.1 & 6 OS

**Comment by sammartinez** [comment]
@BardiaN In looking at the versions you are using for Chrome, I am seeing that its earlier versions of Chrome. As for Amplify, we do support the [latest versions of browsers](https://aws.amazon.com/premiumsupport/knowledge-center/browsers-management-console/) up to the last three versions. Are you dependent on using these versions of chrome for your application?
