### ISSUE TITLE
AWS IOT Principal attachment

### ISSUE THREAD

**Issue by naseemrafique** [aws-amplify/amplify-js#3962]
I am using iot and created a policy. Now I have three identity pools for each stage(dev, qa, prod),
how do I attach all three principals to policy:

1. Should I attach three principals to a single policy
2. Should I create three policy and attach principal to each policy for each stage.

**Comment by haverchuck** [comment]
@naseemrafique -  I think this question would get a better reponse in the [AWS IoT developer forums](https://forums.aws.amazon.com/forum.jspa?forumID=210).  I am closing this issue for now, but if you feel that your question is specific to AWS Amplify feel free to open another issue with a bit more detail.
