### ISSUE TITLE
Deleting record causes nullable error - api connection

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-js#3964]
** Which Category is your question related to? **
API

I have created a pretty large app with Amplify and am testing the removal on records from the user dashboard.

The delete call works great and removes the records from their requested tables.

However I have noticed that if I delete a record which has connections to other records, pulling the records with subsequent connections will now give this error:

Cannot return null for non-nullable type

or in a specific example :

Cannot return null for non-nullable type: 'Entity' within parent 'Subscriber'

Now I understand why this is happening as the Subscriber record has a connection to an entity which has now been deleted.

Is there a way to ensure the connection die with the deleted record? I don't want to use a deleted field to deal with deletion as the database will grow very very fast.

Is there a best practice for deal with deleting records in amplify and their subsequent connections?

**Comment by haverchuck** [comment]
@oliverandersencox -  Is the field in question absolutely mandatory?  Could you try updating the schema so that the field is optional, which would ostensibly resolve this error?  

If that isn't a valid solution for you, can you please post your schema?

**Comment by oliverandersencox** [comment]
`type User @model 
@auth(rules: [
  { allow: owner, operations: [update, delete, create] },
  { allow: groups, groups: ["admin"], operations: [update, delete, create] }
])
@searchable {
  id: ID!
  role: UserRole
  firstName: String
  lastName: String
  email: String
  phone: String
  city: String
  allowNotifications: Boolean
  allowLocation: Boolean
  allowPersonalisation: Boolean
  profilePicture: String
  subscibedToEmails: Boolean
  token: PushToken
  locale: String
  categories: [String!]!
  subscriptions: [Subscriber] @connection(name: "EntitySubscriber")
  social: SocialItems
  createdAt: Float!
  updatedAt: Float!
}`

`type Subscriber @model {
  id: ID!
  userId: String!
  entityId: String!
  user: User @connection(name: "EntitySubscriber")
  subscriptionArn: String
  status: String!
  createdAt: Float!
  updatedAt: Float!
}`

If I remove a 'Subscriber' record from the database, The error is produced if I try and fetch a user which had a connection to that subscriber

**Comment by oliverandersencox** [comment]
@haverchuck - you're commented outlined the issue. The connection had required flags on them and once removed, this error no longer occurred. Thanks!

**Comment by ajhool** [comment]
This is clearly not a resolution to this bug and it is a bad workaround. The delete resolver for a connection should delete the pointer on the other side of the connection (obviously). Simply setting the connection to be nullable is not an appropriate fix and this should be considered to be a bug in how @connection works. Everytime somebody calls Amplify's `deleteItem` resolver, they are orphaning the children/parents and that is precisely the type of complexity that Amplify should be reducing not obfuscating by "just making it nullable"...

If the `create` and `update` resolvers correctly update fields on the connection, why wouldn't delete do the same thing?
