### ISSUE TITLE
Amplify JS Analytics for React Native has OS version not app version in application.version_name

### ISSUE THREAD

**Issue by paddlefish** [aws-amplify/amplify-js#3965]
**Describe the bug**
Set up amplify analytics and configure pinpoint to send events to S3 via a firehose. When you look at the event JSON documents, the application.version_name field has been populated with the OS version (e.g 'ios/12.4') not the version of the application from the app's main bundle plist file.

**To Reproduce**
1. New amplify react native project
2. Add analytics
3. In pinpoint configure stream data to S3 via firehose
4. Look at JSON document

**Expected behavior**
application.version_name and also application.version_code matches the key CFBundleShortVersionString in the Info.plist for the main bundle, just like AWS Amplify for Obj C.

Also missing:     "package_name": "co.myapp.bundle.identifier",
"sdk" name and version

**Actual Result**

```
{
  "event_type": "...",
  "event_timestamp": 1567522601546,
  "arrival_timestamp": 1567522602067,
  "event_version": "3.1",
  "application": {
    "app_id": "...",
    "cognito_identity_pool_id": "us-east-1:...",
    "sdk": {},
    "version_name": "ios/12.4"
  },
  "client": {
    "client_id": "...",
    "cognito_id": "us-east-1:..."
  },
  "device": {
    "make": "iPhone",
    "model": "iPhone 6/7/8",
    "platform": {
      "name": "ios"
    }
  },
  "session": {
    "session_id": "...",
    "start_timestamp": 1567522597204
  },
  "attributes": {
  },
  "endpoint": {
    "EndpointStatus": "ACTIVE",
    "OptOut": "ALL",
    "RequestId": "...",
    "Location": {},
    "Demographic": {
      "Make": "iPhone",
      "Model": "iPhone 6/7/8",
      "ModelVersion": "12.4",
      "AppVersion": "ios/12.4",
      "Platform": "ios"
    },
    "EffectiveDate": "2019-09-03T14:56:42.060Z",
    "Attributes": {},
    "Metrics": {},
    "User": {
      "UserId": "us-east-1:..."
    },
    "ApplicationId": "...",
    "Id": "015dcbbf-a9ba-4a61-b958-d669ae99f569",
    "CohortId": "18",
    "CreationDate": "2019-09-03T14:42:41.388Z"
  },
  "awsAccountId": "..."
}

```

Here's an example from the iOS SDK, which we can call the expected result:

```
{
  "event_type": "...",
  "event_timestamp": 1567504774455,
  "arrival_timestamp": 1567504775334,
  "event_version": "3.1",
  "application": {
    "app_id": "...",
    "cognito_identity_pool_id": "us-east-1:...",
    "package_name": "...",
    "sdk": {
      "name": "aws-sdk-iOS",
      "version": "2.9.10"
    },
    "title": "Unknown",
    "version_name": "3.11.0",
    "version_code": "3.11.0"
  },
  "client": {
    "client_id": "...",
    "cognito_id": "us-east-1:..."
  },
  "device": {
    "locale": {
      "code": "en_US",
      "country": "US",
      "language": "en"
    },
    "make": "apple",
    "model": "iPhone",
    "platform": {
      "name": "ios",
      "version": "12.2"
    }
  },
  "session": {
    "session_id": "...",
    "start_timestamp": 1567504774425
  },
  "attributes": { ...  },
  "endpoint": {
    "ChannelType": "APNS",
    "EndpointStatus": "ACTIVE",
    "OptOut": "ALL",
    "Location": {
      "Country": "US"
    },
    "Demographic": {
      "Make": "apple",
      "Model": "iPhone",
      "Timezone": "America/Los_Angeles",
      "Locale": "en_US",
      "AppVersion": "3.11.0",
      "Platform": "ios",
      "PlatformVersion": "12.2"
    },
    "EffectiveDate": "2019-09-03T09:59:34.461Z",
    "Attributes": {
      "ASIdentifierManager_advertiserId": [
        "..."
      ]
    },
    "Metrics": {},
    "ApplicationId": "...",
    "Id": "...",
    "CohortId": "59",
    "CreationDate": "2019-09-03T09:59:34.461Z"
  },
  "awsAccountId": "..."
}
```

**Comment by paddlefish** [comment]
This might help you visualize the issue better:

![Screen Shot 2019-09-04 at 10 39 09 AM](https://user-images.githubusercontent.com/535096/64270022-7caa5c80-cf00-11e9-9229-47d52f7e00c5.png)
![Screen Shot 2019-09-04 at 10 38 21 AM](https://user-images.githubusercontent.com/535096/64270023-7caa5c80-cf00-11e9-966f-9d30497d13b3.png)

**Comment by paddlefish** [comment]
This is not stale. Your backlog is too big relative to your staleness bot’s configuration.

**Comment by paddlefish** [comment]
This is not stale.  Bread goes stale.  Bugs don't. They don't just magically go away because time has passed.

**Comment by sammartinez** [comment]
@paddlefish Apologize for the not responding on this sooner. Im looking into this issue. Can you provide the amplify versions (`aws-amplify`, `aws-amplify-react-native`) you are using with your React Native application?

**Comment by sammartinez** [comment]
@paddlefish I did find the [code](https://github.com/aws-amplify/amplify-js/blame/40f9a4dd6613004b2b94e0f06612331bfad9c92a/packages/core/src/ClientDevice/ios.ts#L25-L31) in question that you are referring to. Please see the link. I am going to track this internally so we can have someone pick it up but I do want to state we are open to PRs if you wanted to contribute. Thanks for bringing it to our attention!

**Comment by paddlefish** [comment]
Hi @sammartinez thanks -- is it okay to fix this by bringing in new dependencies? The way I'd approach this is to use react-native-device-info, and via that read the app version info from the Info.plist of the main bundle.

(In fact the whole `dimToMake` function in the code you point to is downright scary and unnecessary when you can actually find out what the device is without inferring it from screen dimensions.  Does this technique properly take into consideration split-screen mode on iPads? What about TVOS? iPhone XS Max?)

**Comment by sammartinez** [comment]
@paddlefish After discussing internally, we are looking to not add a new dependency if possible. We are exploring a solution on how to solve this with the package you recommended for it but more of a peer dependency approach or possibly moving React Native specific code to a separate part of the library. 

If you still want to put a Pull Request up, more then welcome to but it may be that you will have to see about not making a physical dependency on `react-native-device-info` in the core package.

**Comment by paddlefish** [comment]
Ok so what if it had some kind of support for injecting a different metadata provider. 

Option 1
======

Modify aws-amplify-react-native  (https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react-native/package.json) so that it has a dependency on `react-native-device-info`.  When react-native-device-info is imported, it constructs a better version of the metadata provider `export const clientInfo = () => {` that currently resides in `https://github.com/aws-amplify/amplify-js/blob/master/packages/core/src/ClientDevice/ios.ts`).  `aws-amplify-react-native` then takes this new metadata provider and passes it into a new api o Amplify-JS.  Thus if you're on react-native and you use aws-amplify-react-native then the analytics `clientInfo`.

Option 2
======

We spin up a new npm module that's just the metadata provider for react-native that uses `react-native-device-info` and to use would be something like this in your App.tsx (code written in browser forgive me if it's not perfect):

```
import { ReactNativeAnalyticsProvider } from 'aws-amplify-react-native-analytics'
import Amplify from 'aws-amplify'

Amplify.Analytics.setMetadataProvider(ReactNativeAnalyticsProvider)
```

then the dependency on `react-native-device-info` is outside amplify-js entirely.  instead of the built-in `clientInfo` function, after calling `Amplify.Analytics.setMetadataProvider` it uses the one from our new package `aws-amplify-react-native-analytics`

Option 3
======

Support someone injecting react-native-device-info directly into amplify in their App.tsx:

```
import DeviceInfo from 'react-native-device-info'
import Amplify from 'aws-amplify'

Amplify.Analytics.setReactNativeDeviceInfo(DeviceInfo)
```

... and add the logic to the existing `clientInfo` function in amplify-js to leverage device info, falling back to the current (broken) implementation if it hasn't been provided.

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
