### ISSUE TITLE
How to Attach policy to Amazon Cognito Identity

### ISSUE THREAD

**Issue by naseemrafique** [aws-amplify/amplify-js#3966]
Hello,

In following Guide it is mention to attach Cognito Identity with Policy, Can any guide me that how is it Identity Pool ID or User Identity id created in Identity Pool.

`https://aws-amplify.github.io/docs/js/pubsub`

Currently I am tying to attach Identity Pool Id with iot policy as certificate, am I doing it right way?

also there Following call doesn't return any thing, it doesn't work.

`Auth.currentCredentials().then((info) => {
      const cognitoIdentityId = info.data.IdentityId;
    });`

**Comment by haverchuck** [comment]
@naseemrafique -  Does `Auth.currentCredentials()` return anything at all?

**Comment by naseemrafique** [comment]
@haverchuck no it is returning undefine. I am using Amplify version 1.1.36

**Comment by haverchuck** [comment]
@naseemrafique But your user has logged in correctly and local storage is populated w/ tokens?

**Comment by naseemrafique** [comment]
@haverchuck Yes after sign inI received IdToken, AccessToken and RefreshToken.

**Comment by haverchuck** [comment]
@naseemrafique What about Auth.currentAuthenticatedUser or other Auth methods?

**Comment by naseemrafique** [comment]
@haverchuck it returns Cognito User info.

**Comment by sammartinez** [comment]
@naseemrafique Make sure you are logged in (Authenticated) and see about just console logging out the response without the destruct happening. With the below code, I can see under the data response `IdentityId`. There should also be an `_ IdentityId` in that console log that is the same within the data response.

e.g. for React (not sure what you are using)

```
...
componentDidMount() {
    Auth.currentCredentials().then((response) => console.log(response));
  }
...
```

Hope this helps!

**Comment by naseemrafique** [comment]
@haverchuck  @sammartinez 
It works for ReactJS but I am using it on React Native.

**Comment by sammartinez** [comment]
@naseemrafique Do you have a coding sample we can look at?

**Comment by elorzafe** [comment]
@naseemrafique are you still having this issue? If that is the case can you paste a code snippet and the amplify versions you are using?

**Comment by naseemrafique** [comment]
@elorzafe 
I'll paste code snippet tomorrow, but for now I am facing an issue where I got following error while I try to connect to iot topic on page refresh

`{invocationContext: undefined, errorCode: 8, errorMessage: "AMQJS0008I Socket closed."}`

It connect fine on login I receive notifications fine but on refresh it give this error.
