### ISSUE TITLE
how to add Cognito users into dynamodb

### ISSUE THREAD

**Issue by anarerdene** [aws-amplify/amplify-js#3968]
** Which Category is your question related to? **
Appsync, Cognito
** What AWS Services are you utilizing? **

** Provide additional details e.g. code snippets **

I created named userTable on DynamoDB. I want to insert new/registered users attribute into userTable.

**Comment by haverchuck** [comment]
@anarerdene  - There several ways to do this.  One way would be to use [Cognito Lambda triggers](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html) to insert the user information into a table at the desired point in time.  I have not read the entirety of [this article](https://medium.com/hackernoon/how-to-add-new-cognito-users-to-dynamodb-using-lambda-e3f55541297c) (so I can't fully endorse it), but at first glance it looks like exactly what you need.  

The Amplify CLI [can assist you in setting up and maintaining](https://aws-amplify.github.io/docs/cli-toolchain/quickstart#adding-a-lambda-trigger) such a trigger, but you can also do it directly in the Cognito/Lambda consoles. 

I would advise you to exercise caution in duplicating data between the userpool and another database. User records in the userpool are not immutable, and thus there is the distinct possibility of the two data sources growing out of sync.  You could potentially use triggers to sync the data if needed.
