### ISSUE TITLE
Auth.federatedSignIn() - Invalid Request

### ISSUE THREAD

**Issue by codeinaire** [aws-amplify/amplify-js#3972]
**Background**
I've been testing whether or not I want to use AWS Cognito for my app. I previously asked some questions about functionality [here](https://github.com/aws-amplify/amplify-js/issues/3959), but decided to give Amplify a go to see if I could understand the Federated Identity process myself and fix it.

**Describe the bug**
My set up is with the default Amplify settings with Facebook as the social media identity provider. I pushed that to AWS and followed the instructions [here](https://aws-amplify.github.io/docs/js/authentication#oauth-and-hosted-ui) to test Federation. I click on the Facebook button and get the error.

**To Reproduce**
1. Follow the set up instructions [here](https://aws-amplify.github.io/docs/js/authentication#oauth-and-hosted-ui) and run local server.
2. Click Facebook button.
3. See error

**Expected behavior**
I expect to sign-in to Facebook and get redirected back to http://localhost:3000

**Screenshots**
I highlighted what I believe the issue is in the bottom right corner of the screenshot.

I was able to get a successful request when setting up Federation with `implicit` grant OAuth flow and changing `response_type` to  `token`. 

I also checked the [Cognito docs](https://docs.aws.amazon.com/cognito/latest/developerguide/authorization-endpoint.html) and the only two values allowed for `response_type` are `token` and `code`. Why is it that `implicit` is being used? Is this going to be a third accepted value in the future? The docs appear to be correct for the moment.
[Error screenshot](https://i.imgur.com/sAZn12d.png)

The default setup. I removed entering my Facebook creds.
[Amplify setup screenshot](https://i.imgur.com/tRLFGeB.png)

**Desktop (please complete the following information):**
 - OS: Mojave 10.14.6
 - Browser: Firefox Dev Ed 70

**Sample code**
I followed the code as per the instructions in the link above.

**Comment by haverchuck** [comment]
@codeinaire I think this is actually an issue with the CLI, which we are going to be fixing.  Please stay tuned.

**Comment by haverchuck** [comment]
@codeinaire We have merged a fix into the CLI.  It will be available in the general release branch in the near future.  If you are configuring via an aws-exports file, you can trying changing the responseType value from 'implicit' to 'token' to test out the fix (I can't necessarily advise altering this file in production).

**Comment by codeinaire** [comment]
Okay, thanks.

I'm currently prototyping other auth systems as I've been focusing a lot on prototyping with Cognito and it hasn't really been able to do exactly what I'm want. I'll keep the aws-export file fix in mind if I go back to prototyping with Amplify.
