### ISSUE TITLE
Forgot Password when user has verified email address and phone number [AWS Cognito]

### ISSUE THREAD

**Issue by NoraBo** [aws-amplify/amplify-js#3973]
- Cognito user pool is configured to require email or phone number

- User signs up by providing a phone number and an email address

- The phone number and the email address are then verified

In the above case, which **contact method** is used to send the **confirmation code** that is required to change the user's password when the user forgets his password?

If the confirmation code is only sent to the phone number, what is the point of signing up using phone number and email?

**Comment by huihe** [comment]
As I know, when only email verified, the code will be sent to email, when both email and phone verified, the code will be sent to the phone. Unfortunately, Cognito doesn't give an option to config the delivery method.
