### ISSUE TITLE
Can I hide the Authenticator's 'Loading...' Text

### ISSUE THREAD

**Issue by torigeorge** [aws-amplify/amplify-js#3979]
I am using aws-amplify-react-native with oAuth and customizing the UI. When logging it still shows the 'Loading...' indicator in the top left corner of the phone. I've tried editing Authenticator and Loading files inside node_modules and Loading... still persists. Is there a way in which to at least hide the activity indicator?

**Comment by haverchuck** [comment]
@torigeorge Did you try using the[ 'hide' prop](https://aws-amplify.github.io/docs/js/authentication#using-the-authenticator-component) in the Authenticator component?

**Comment by haverchuck** [comment]
@torigeorge Did you try using the 'hideDefault' prop in the Authenticator component, and then passing in the specific components you want (as shown in the docs [here](https://aws-amplify.github.io/docs/js/authentication#using-the-authenticator-component))?

**Comment by torigeorge** [comment]
@haverChuck Thanks for the quick response. Appreciate it. I'm not using Authenticator like the link you showed but oAuth. I can't seem to get rid of the loading there. You can see it in the picture attached in the top upper left hand corner. I've dug all through node modules and tried to manually get rid of any 'Loading...' I can find to no avail. 

Trying to use Authstate in a switch case to show my custom loader exactly like this [here]

(https://aws-amplify.github.io/docs/js/authentication#oauth-and-hosted-ui).
![Simulator Screen Shot - iPhone X - 2019-09-06 at 09 55 12](https://user-images.githubusercontent.com/43757817/64438063-06873080-d08d-11e9-8999-84d5fe578c35.png)

**Comment by haverchuck** [comment]
@torigeorge  - Can you post a sample of your code?

**Comment by torigeorge** [comment]
@haverchuck 

  render() {
    const { authState } = this.state;
    const { navigation } = this.props;
    const { push } = navigation;
    console.log(authState);
    // Display loader while authentication is being checked for current user

    switch (authState) {
      case 'signIn':
        push('AuthMethods');
        return <LottieLoader showLoader />;
      case 'signedIn':
        push('PropertiesContainer');
        return <LottieLoader showLoader />;
      case 'loading':
        return <LottieLoader showLoader />;
      default:
        return (
          <View style={{ flex: 1 }}>
            <LottieLoader showLoader />
          </View>
        );
    }
  }

**Comment by torigeorge** [comment]
@haverchuck 

async componentDidMount() {
    let user = {
      attributes: {
        sub: '',
      },
    };
    try {
      user = await Amplify.Auth.currentAuthenticatedUser();
      console.log('current user: ', user);
      const currentSesh = await Amplify.Auth.currentSession();
      await user.refreshSession(currentSesh.refreshToken);
      client.reFetchObservableQueries();
      this.setGlobal({
        userCognitoId: user.attributes.email,
      });
      const { navigation } = this.props;
      const { push } = navigation;
      push('PropertiesContainer');
    } catch (e) {
      this.setGlobal({ HEADER_inAuth: true });
    }
  }

  componentDidUpdate() {
    const { navigation, loading } = this.props;
    const { push } = navigation;

    if (loading) return <LottieLoader showLoader />;

    Amplify.Auth.currentAuthenticatedUser()
      .then(user => {
        console.log('currentAuthenticatedUser user', user);
        this.setGlobal({ userCognitoId: user.attributes.email });
        push('PropertiesContainer');
      })
      .catch(err => console.log('currentAuthenticatedUser', err));
  }

  render() {
    const {
      oAuthUser: user,
      oAuthError: error,
      customProviderSignIn,
      navigation,
      loading,
    } = this.props;
    console.log('user', user);
    console.log('user error', error);
    const { navigate } = navigation;

    if (loading) return <LottieLoader showLoader />;

    return (
      <SafeAreaView style={styles.safeArea}>
        <Image
          source={require('./CORELogo.png')}
          style={Platform.isPad ? styles.imagePad : styles.image}
        />
        <View>
          {error && <Text>{JSON.stringify({ user, error }, null, 2)}</Text>}

          <React.Fragment>
            <TouchableOpacity
              style={[styles.loginButton, styles.loginButtonSub]}
              onPress={() => navigate('Login')}
            >
              <Text style={[styles.loginButtonText, styles.loginButtonTextSub]}>
                Subcontractor Login
              </Text>
            </TouchableOpacity>
            {/* e.g. for OIDC providers */}
            <TouchableOpacity
              style={styles.loginButton}
              onPress={() => {
                customProviderSignIn('Azure');
              }}
            >
              <Text style={styles.loginButtonText}>CORE Employee Login</Text>
            </TouchableOpacity>
          </React.Fragment>
        </View>
      </SafeAreaView>
    );
  }
}
export default withOAuth(withNavigation(AuthMethods));

**Comment by torigeorge** [comment]
@haverchuck it seems to appear as soon as it hits  ' await Auth.currentAuthenticatedUser()'. Do you have any suggestions? New to aws and amplify.
