### ISSUE TITLE
Error thrown if only using Identity Pool

### ISSUE THREAD

**Issue by justinwaite** [aws-amplify/amplify-js#3983]
**Describe the bug**
When using Amplify Auth with only an identity pool ID (no user pool), the following error is thrown:

**To Reproduce**

**Expected behavior**
It is expected that the user pool is optional and that simply an identity pool Id would suffice.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 76

**Additional context**
Looking at the source, it seems that this line needs to be updated:
https://github.com/aws-amplify/amplify-js/blob/632064e165656bafe224c67d99d91a7a069c632b/packages/auth/src/Auth.ts#L1700

According to the docs, only an identity pool ID is required. ~Therefore, the line should probably read:~
```javascript
if (!config.userPoolId && !config.identityPoolId) {
``` 
~(updated from `||` to `&&`).~

Edit: Looking into the source further this is not the solution.

**Comment by jordanranz** [comment]
@justinwaite, Can you post a link to the documentation you are referring to. This does indeed seem odd.

**Comment by justinwaite** [comment]
Sure thing, it's all over the docs, but here's one example in particular:
https://aws-amplify.github.io/docs/js/authentication#manual-setup

**Comment by justinwaite** [comment]
To remedy right now I simply put in a fake `userPoolId` and `userPoolWebClientId` so that the error isn't thrown.

**Comment by justinwaite** [comment]
The error seems to be gone now, and I'm not sure why... I wasn't calling any auth methods that would have thrown this error. It could have been a change in the way I did some stuff with the Storage API (maybe storage API was trying to sign in automatically?).

**Comment by justinwaite** [comment]
The error isn't thrown until I use the Storage API to try and upload a file. Maybe the Storage API is trying to call one of the authentication methods that would throw this error?

**Comment by elorzafe** [comment]
Hi @justinwaite I reproduced the problem, we are going to send a fix for this soon. Thanks for pointing out!

**Comment by justinwaite** [comment]
Thanks!

**Comment by justinwaite** [comment]
Looks like that did it. Thank you for the quick update!
