### ISSUE TITLE
Chatbot component does not display lex responses on both text and voice mode. How to use it correctly so that it does?

### ISSUE THREAD

**Issue by saurabhpati** [aws-amplify/amplify-js#3984]
** Which Category is your question related to? **
* aws-amplify-react
* Chatbot.js

** What AWS Services are you utilizing? **
* Lex

** Provide additional details e.g. code snippets **
* I am new to lex and amplify. I want to integrate a chatbot into a website.
* This is a sample Bot.js which is rendered from App.js
```import React from 'react';
import Amplify from 'aws-amplify';
import { ChatBot, AmplifyTheme } from 'aws-amplify-react';
import awsconfig from './aws-exports';

Amplify.configure(awsconfig);

// Imported default theme can be customized by overloading attributes
const myTheme = {
  ...AmplifyTheme,
  sectionHeader: {
    ...AmplifyTheme.sectionHeader,
    backgroundColor: '#ff6600'
  }
};

export const Bot = () => {

  const handleComplete = (err, confirmation) => {
    if (err) {
      alert('Bot conversation failed')
      return;
    }

    alert('Success: ' + JSON.stringify(confirmation, null, 2));
    return 'Trip booked. Thank you! what would you like to do next?';
  }

  return (
    <div className="App">
      <header className="App-header">
        <h1 className="App-title">Welcome to ChatBot Demo</h1>
      </header>
      <ChatBot
        userInput="I want to pick up some flowers"
        title="My Bot"
        theme={myTheme}
        botName="OrderFlowers_dev"
        welcomeMessage="Welcome, how can I help you today?"
        onComplete={handleComplete}
        clearOnComplete={true}
        voiceEnabled={true}
        textEnabled={true}
        conversationModeOn={true}
      />
    </div>
  );
}
```

The utterances I type are displayed on the Chatbot screen but the response from lex is not displayed. 

Although, I do notice a successfull network call to lex service that takes the user utterance and fetches the response as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/20544414/64403187-494d0680-d095-11e9-98d6-5468080da98a.png)

Url: https://runtime.lex.us-east-1.amazonaws.com/bot/OrderFlowers_dev/alias/%24LATEST/user/us-east-1%3A82681ff8-5882-4d02-bf03-057a5d37bebf/text
Payload: ```{"inputText":"I want to pick some flowers"}```

* Also I find it really wierd that there is no event in the props of ```Chatbot.js``` that should execute on response from lex.

* I tried to look into the source code and found this
![image](https://user-images.githubusercontent.com/20544414/64403548-9b425c00-d096-11e9-9b40-3286c6640837.png)

![image](https://user-images.githubusercontent.com/20544414/64403732-510daa80-d097-11e9-9080-c1acf8ec4a97.png)

Package versions:
```
{
  "name": "grappy-amplified",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@aws-amplify/api": "^1.0.42",
    "@aws-amplify/pubsub": "^1.1.0",
    "aws-amplify": "^1.1.36",
    "aws-amplify-react": "^2.4.2",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-scripts": "3.1.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

* Code Editor: VS Code v1.38
* Browser: Chrome v76.0.3809.132
Same observed on firefox too.

Am I doing something fundamentally wrong? Please help.

**Comment by saurabhpati** [comment]
I have a github repo if you want to take a full look:
https://github.com/saurabhpati/grappy-amplified

**Comment by saurabhpati** [comment]
Any thoughts, anyone?

**Comment by elorzafe** [comment]
@saurabhpati I think the dialog is there but the text is the same color as background. If you try to select the text you should see it

**Comment by saurabhpati** [comment]
@elorzafe Well, I think I made a mockery of myself and even logged it by opening an issue for everyone to see for times to come. 

Thank you very much for the help much appreciated.

**Comment by saurabhpati** [comment]
I think we can include something like this in index.css (or less or scss). Just a suggestion

div.amplify-section-body > div >div:nth-child(2n+1) {
  color: red;
}
