### ISSUE TITLE
Push notification tokens are not generated for react-native version 0.60.5 with production certs

### ISSUE THREAD

**Issue by sandaruny** [aws-amplify/amplify-js#3995]
**Describe the bug**
I experienced that the PushNotification.onRegister is not called when using react-native version 60.5 with production Apple Push Services certs. This might be an issue arising with the deprecation of the PushNotificationIOS native module. ([https://facebook.github.io/react-native/docs/pushnotificationios](https://facebook.github.io/react-native/docs/pushnotificationios))

**To Reproduce**
1. Create env with the react-native 0.60.5 version. 
2. Check PushNotification.onRegister for a production build

**Expected behavior**
The token should be generated

This was working for the previous react-native version (0.55.0) and generating token successfully.

But it was able to fix by patching the module. When the library code was modified to use the "@react-native-community/push-notification-ios", the tokens were generating properly.

**Comment by elorzafe** [comment]
@sandaruny there was a bunch of breaking changes on react-native 0.60, we will take this a feature-request that we want to support soon.

Thanks for pointing this out!

**Comment by nikhil-dabhade** [comment]
@Ashish5591 : Any insights in this issue?

**Comment by matamicen** [comment]
@elorzafe 
It works for us in TestFlight ... we didn't launch production. @sandaruny  @nikhil-dabhade  it works for you on TestFlight also? 

Thanks for the info.
Matt.

**Comment by sammartinez** [comment]
Resolving as the reference issue above from @Ashish5591 resolves this.

**Comment by Ashish5591** [comment]
Hi  @sandaruny and @matamicen  
We just did a release to the @unstable tag with the changes.
Please take a look at this [comment](https://github.com/aws-amplify/amplify-js/issues/4089#issuecomment-559333746) for the instructions and let us know if it works for you.
