### ISSUE TITLE
amazon-cognito-identity-js verifyAttribute returns NetworkError

### ISSUE THREAD

**Issue by zamirkhan** [aws-amplify/amplify-js#3997]
First, I know that `amazon-cognito-identity-js` is archived/deprecated, but migrating from that is a larger effort that we're not ready to tackle yet. The older library mostly works for our needs, but this bug is an issue for us. Also, since as I understand it, Amplify wraps the original library, I'm not sure this would work in that.

We have a workflow that allows the user to change their e-mail address. We update this attribute using `updateAttributes` and that works as expected. Changing the email attributes automatically sends a verification code to the user, so we prompt them for this code and attempt to verify the address using `verifyAttribute`. Here's the strange thing, no matter what code we put in, correct or not, the `onFailure` callback is invoked with a generic `NetworkError`. However, if the code is correct, we can confirm that `email_verified` is properly updated to `true`. So the call is working, but the callback part appears broken and we are unable to detect whether it succeeded or not. Anyone run into something like this? Here's the code snippet:

```
        // getSession must be called to authenticate user
        // before verifyAttribute is called.
        currentUser.getSession((err, session) => {
          currentUser.verifyAttribute("email", this.state.verificationCode, {
            onFailure: err => {
              this.setState({
                isUpdating: false
              });

              this.props.setErrorMessage("Email verification failed: " + err);
            }.bind(this),
            onSuccess: success => {
              console.log(success);
              this.setState({
                emailVerified: true,
                isUpdating: false,
                requestEmailVerification: false
              });

              this.props.setSuccessMessage("Email has been verified!");

              this.props.history.push("/");
            }
          });
        }); 
```

One last annoyance is that setting `window.LOG_LEVEL = 'debug'` does not appear to produe any debug logging for us.

**Comment by elorzafe** [comment]
@zamirkhan thanks for your feedback. Do you see any error on network tab?

**Comment by zamirkhan** [comment]
Thank you for that suggest @elorzafe, it helped me indirectly discover the issue, which was on my end. I was making the `verifyAttribute` call after a form submit (the verification code) and by looking at the network tab, I noticed that this was resulting in a page reload (the requests from the previous load would clear). In this particular form submit handler I had forgotten to use `event.preventDefault()` to prevent this reload from happening. Once I did that, `verifyAttribute` behaved as I expected. I suspect the page reload due to the form submit did not give the `verifyAttribute` request time to complete, resulting in the generic `NetworkError`. Thanks again, you can close this.

**Comment by RoniFinTech** [comment]
Hi,
Where do you see `amazon-cognito-identity-js` has been deprecated? what is the recommended library to interact with AWS Cognito User Pool?
