### ISSUE TITLE
Wrong error reported from signIn_failure on 1.1.39-unstable.4

### ISSUE THREAD

**Issue by rabellino12** [aws-amplify/amplify-js#4004]
Hi amplify team, I participated in this issue #3932 a few days ago.
I created this new issue because the previous one was closed by this pr # 3993.

**Describe the bug**
I'm testing the 1.1.39-unstable.4 version of the aws-amplify package and the bug is kind of fixed, because there is no longer a react white screen for unhandled rejection, but the catch on OAuth/OAuth.ts on handleAuthResponse method is not throwing the error, just logging. 
What happens there is that the method returns undefined on Auth.ts line 1564 and that triggers the catch on private _handleAuthResponse method on Auth.ts with a new error (because javascript can't get accessToken from undefined). That's the error we get on signIn_failed event, so we lose the proper error_description that comes in the URL.

**To Reproduce**
1. Enter the amplify react app with a URL like: http://localhost:3000/somePage#error_description=PreSignUp+failed+with+error+SOME_CUSTOM_ERROR_FROM_PRE_SIGNUP_TRIGGER.+&state=someStateHash&error=invalid_request
2. Catch signIn_failure event, the data.message there is: "Cannot read property 'accessToken' of undefined"
3. The console logs the correct error, the same as error_description.

**Expected behavior**
I think the proper behavior should be to log the error on OAuth.ts handleAuthResponse but also throw it, so Auth.ts private _handleAuthResponse gets it in the catch and triggers the failure events with the proper error, that way I can catch it and give some feedback to the user regarding that custom error. That would also prevent the undefined return.

**Additional context**
Same as #3932 but with aws-amplify@1.1.39-unstable.4

**Comment by rabellino12** [comment]
Hi @elorzafe and amplify team, I just saw that the 1.1.40 release has this issue, is very dangerous as this bug practically ignores authentication errors, several production builds can suffer a lot from this. A `throw e` on handleAuthResponse's catch should do the trick

**Comment by Alex-Burgess** [comment]
+1 for this issue.  I have a pre-sign up trigger which throws an exception in certain situations to prevent the signup process from completing.

When using the federated signin, (e.g. Auth.federatedSignIn({provider: 'Google'})) and a pre sign up trigger throws a custom exception, I get the following instead:

Auth.js:2186 Uncaught (in promise) TypeError: Cannot read property 'accessToken' of undefined
    at AuthClass.<anonymous> (Auth.js:2186)
    at step (Auth.js:138)
    at Object.next (Auth.js:69)
    at fulfilled (Auth.js:23)


Interesting, Auth.signUp() which I use to sign up users who choose username and password, fails gracefully in the same pre-trigger exception scenario, allowing me to catch error and print it back to the user. 

It would be good if whether using Auth.federatedSignIn() or Auth.signUp(), the pre-trigger failed gracefully in the same way.

**Comment by adgrace** [comment]
+1 Experiencing same issue

**Comment by perunthagai-memorang** [comment]
+1 Experiencing same issue

**Comment by martrik** [comment]
Same here. Really annoying bug as it doesn't allow us to show the actual error message returned by the `pre signup` Cognito Lambda Trigger.

**Comment by ericclemmons** [comment]
This is interesting! In attempt to get visibility into #4375 I made the fix in https://github.com/aws-amplify/amplify-js/pull/4679.

I'll approve #4399 to give credit to your contribution & help :)
