### ISSUE TITLE
Input type="tel"

### ISSUE THREAD

**Issue by mcvicar** [aws-amplify/amplify-js#4009]
**Describe the bug**
Should input fields taking phone numbers be `input type="tel"` rather than just `input type="text"` inputs?

**To Reproduce**
Render a phone_number input. The output is like below;
`<input type="text" placeholder="Phone Number">`

**Expected behavior**
Expected to happen would be;
`<input type="tel" placeholder="Phone Number">`

**Desktop (please complete the following information):**
 - OS: Any
 - Browser All

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: All
 - Browser All

**Additional context**
This might be by design, but something I noticed digging around the codebase. 
Happy to provide a pull request if this is something that should be fixed.

**Comment by sammartinez** [comment]
Closing this issue since the PR was approved and merged
