### ISSUE TITLE
Can't bind to 'usernameAttributes' since it isn't a known property of 'amplify-authenticator'.

### ISSUE THREAD

**Issue by tomaszs** [aws-amplify/amplify-js#4014]
According to the documentation:

https://aws-amplify.github.io/docs/js/angular

If the user pool is set to allow email addresses/phone numbers as the username, you can then change the UI components accordingly by using usernameAttributes.

<amplify-authenticator [usernameAttributes]="usernameAttributes"></amplify-authenticator>

But when doing so an error occurs:

Can't bind to 'usernameAttributes' since it isn't a known property of 'amplify-authenticator'.

**Comment by mbejda** [comment]
@tomaszs  I ran the following the issue went away. 
```
npm install aws-amplify@latest aws-amplify-angular@latest
```

**Comment by haverchuck** [comment]
@tomaszs Is this still a problem with the latest version of amplify-angular?
