### ISSUE TITLE
Appsync and creating group cognito

### ISSUE THREAD

**Issue by TanKenny** [aws-amplify/amplify-js#4020]
** Which Category is your question related to? **
Appsync
** What AWS Services are you utilizing? **
Appsync, Cognito, S3, Dynamodb
** Provide additional details e.g. code snippets **
``` javascript
type Project @model @auth
(rules: [ {allow:owner},  { allow: groups, groups:["Admin"], queries:[get, list], mutations:[ update]}, {allow:groups, groups:["Members"], queries:[get]} ]) {
  id: ID!
  name_of_compass: String!
  description_of_compass: String!
  sessions: [Session] @connection(name: "ProjectSessions")
}
```
As shown above, we are trying to create an application were professors/teachers can view and update a student's project and existing members can only view it. We have the @auth directive we would like to use but the "groups" are never created in cognito. This our first time using appsync any help would be appreciated thank you in advance.

**Comment by mauerbac** [comment]
Hello @TanKenny - this workshop goes through adding groups with Auth: https://github.com/dabit3/aws-appsync-react-workshop. Let me know if it helps!
