### ISSUE TITLE
Exceed the size of analytics events buffer

### ISSUE THREAD

**Issue by bneigher** [aws-amplify/amplify-js#4021]
**React Native:** 
Need help understanding how to avoid getting: `Exceed the size of analytics events buffer` errors

Culpable Services
> Amplify.Analytics

Others include:
> Amplify.Auth
Amplify.Storage
Amplify.pushnotifications

I'm using Analytics.record whenever a whitelisted redux event fires, and upon doing so send a lightweight payload (typically one or two properties) in the attributes.
For Example:
```javascript
Analytics.record({ name: "SCENE", attributes: {
    "componentName": "Signup",
    "value": "Signup"
}, metrics: {} });
```

I'm noticing that now whenever I use the app - (a flood of errors are being thrown from Amplify.Auth namely `Exceed the size of analytics events buffer`)

My amplify config:
```
{
  refreshHandlers: {
    [Config.AUTH0_DOMAIN]: refreshToken,
  },
  Auth: {
    auth0: {
      domain: Config.AUTH0_DOMAIN,
      clientID: Config.AUTH0_CLIENT_ID,
      redirectUri: '/',
      audience: `${Config.AUTH0_AUDIENCE}/userinfo`,
      responseType: 'token id_token', // for now we only support implicit grant flow
      scope: 'openid offline_access profile email', // the scope used by your app
      returnTo: '/',
    },
    mandatorySignIn: false,
    region: Config.AWS_REGION,
    identityPoolRegion: Config.AWS_REGION,
    identityPoolId: Config.AWS_COGNITO_ID_POOL,
    userPoolId: Config.AWS_USER_POOL,
    userPoolWebClientId: Config.AWS_USER_POOL_CLIENT,
  },
  Analytics: {
    disabled: false,
    AWSPinpoint: {
      bufferSize: 10000,
      flushInterval: 10000, // 10s
      flushSize: 100,
      resendLimit: 5,
      appId: Config.AWS_ANALYTICS_ID,
      region: Config.AWS_REGION,
      endpointId: DeviceInfo.getUniqueID(),
      endpoint: {}, // load this dynamically
    },
  },
  Storage: {
    region: Config.AWS_REGION,
    bucket: Config.AWS_MEDIA_BUCKET,
    identityPoolId: Config.AWS_COGNITO_ID_POOL,
  },
};
```

Question 1:
What is this error mean?  The event payload is too large?  Does it get stuck with the events that don't get sent to pinpoint?

Question 2:
How do I fix this?  Is this operator error, misconfigure?

Would appreciate the help - reading the code doesn't really help me much without understanding the lot of it

**Comment by sammartinez** [comment]
@bneigher I apologize not getting back to you sooner, is this still a use case you are using? If so, could you provide a sample of your code to accompany the above config?
