### ISSUE TITLE
Module `@aws-amplify/core/lib/constants` does not exist in the Haste module map

### ISSUE THREAD

**Issue by emilcardell** [aws-amplify/amplify-js#4023]
**Describe the bug**
Can't get a new react native project working with AWS amplify.

**To Reproduce**
1. react-native init MyAwesomeProject
2. cd MyAwesomeProject
3. yarn add aws-amplify
4. yarn add aws-amplify-react-native
5. react-native run-android

**Expected behavior**
Development server crashes with a 500.

**Screenshots**
```error: bundling failed: Error: Unable to resolve module `@aws-amplify/core/lib/constants` from `C:\repo\JAPP\node_modules\@aws-amplify\api\lib\API.js`: Module `@aws-amplify/core/lib/constants` does not exist in the Haste module map```

package.json
```
{
  "name": "MyAwesomeProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "aws-amplify": "^1.1.40",
    "aws-amplify-react-native": "^2.1.19",
    "react": "16.8.6",
    "react-native": "0.60.5"
  },
  "devDependencies": {
    "@babel/core": "^7.6.0",
    "@babel/runtime": "^7.6.0",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.4.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

Have the same problems on my Mac and IOS emulator setup as well.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
 - Device: Android Emulator

**Sample code**
The problems occurs the second I import anything from aws-amplify.
```import Amplify from 'aws-amplify';```

I have clear caches, reinstalled and done all instructions shown in the error.

The problems seem to be similar to this issue https://github.com/aws-amplify/amplify-js/issues/3776

**Comment by PerfectedApp** [comment]
Are you using Yarn or NPM?

**Comment by emilcardell** [comment]
My main project is using Yarn.
I think I have tested NPM when I recreated the problem, did it a couple of times.

Let me get back.

**Comment by emilcardell** [comment]
Using NPM works. 👍 

Using YARN on both OSX/IOS and Windows/Android fails. Hope it helps someone else.

**Comment by ckedar** [comment]
To make it work with yarn, pin the version of `@amplify/core` to `1.1.2` in your `package.json`

    "resolutions": {
         "@aws-amplify/core": "1.1.2"
    }
