### ISSUE TITLE
Refresh Identity Pool session in React Native using native SDKs

### ISSUE THREAD

**Issue by district-michael** [aws-amplify/amplify-js#4024]
**Which Category is your question related to?**
Authentication (Cognito)

**What AWS Services are you utilizing?**
Cognito Identity Pools through AWS Amplify

**Provide additional details e.g. code snippets**
We're trying to get social sign on working from our React Native application.  We would like to avoid using the OAuth flow and instead use the native login SDKs, as they provide a much better user experience rather than sending the user out to their browser and back.  I am able to sign in using the native SDKs (`react-native-fbsdk` and `react-native-google-signin`), and I can then pass the access tokens directly to `Auth.federatedSignIn`, and I get an authenticated session, and `Auth.currentAuthenticatedUser` gives me the session information back.  However, when I restart my app, `Auth.currentAuthenticatedUser` returns "not authenticated", even though `Auth.currentCredentials` gives me my Identity Pool credentials.  This causes requests to other Amplify services like Storage to fail.

How am I supposed to go about refreshing my Identity Pool session in Amplify?  Do I have to call `Auth.federatedSignIn` on app launch every time?

**Comment by district-michael** [comment]
So, it _looks_ like the Async Storage instance is intermittently losing some of the cached tokens on app restarts.  I had a little look, and it looks like Amplify is still using the old deprecated version of the AsyncStorage instead of the new react-native-community package.  I implemented a new storage provider using the new Async Storage and it _seems_ to be working much more reliably now.  Will see how things go.

**Comment by streppa** [comment]
Trying to solve a (maybe?) similar problem ( #4213 ). My AppSync calls are failing silently in the refresh handler on page reload. Is the failed call to Async Storage happening in your app's refresh handler? When you say fail do you get an error or is it silent?

**Comment by district-michael** [comment]
Working reliably.  My new storage provider code can be found here:

[#4351](https://github.com/aws-amplify/amplify-js/issues/4351#issuecomment-550538532)
