### ISSUE TITLE
Subscription returns id and typename fields only

### ISSUE THREAD

**Issue by AlessandroAnnini** [aws-amplify/amplify-js#4029]
**Describe the bug**
I use a subscription like onCreateSomething. It correctly fires when Something is created but it returns only the `id` and the `typename` fields of the new node even when I try to get other properties and nested nodes.

**To Reproduce**
I am using this subscription query:
```js
const onCreateAppointment = `subscription OnCreateAppointment {
  onCreateAppointment {
    id
    client {
      id
    }
    availability {
      id
    }
    start
    end
  }
}
`;
```

**Expected behavior**
I expect to read all the fields on the result but I only get id and typename

**Screenshots**
![image](https://user-images.githubusercontent.com/3852307/65053111-be5ced80-d96b-11e9-8eb2-deb5ce1a013a.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser brave
 - Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)

**Additional context**
I had problems with [subscriptions auth](https://aws-amplify.github.io/docs/cli-toolchain/graphql#authorizing-subscriptions) so I am using 
```graphql
@model(subscriptions: { level: PUBLIC })
```
on my node

**Comment by jordanranz** [comment]
Hey @AlessandroAnnini, are you experiencing this problem in the AppSync console or inside of an app using amplify-js?

**Comment by AlessandroAnnini** [comment]
Hi @jordanranz, I experience this issue in both AppSync console and inside a React application using amplify-js

**Comment by jordanranz** [comment]
I believe that data that you are expecting to be returned by the subscription must also be contained within the mutation triggering the subscription. What is the result set of the mutation that you are firing?

**Comment by AlessandroAnnini** [comment]
In the subscription I ask just the same data that I ask in the mutation because it's feeding the same react component. Moreover I think it could be like you say but it shouldn't: that way the query requested in the subscription is useless

**Comment by afanslau** [comment]
I'm also facing this same issue. Any updates?
