### ISSUE TITLE
Auth with federation not working

### ISSUE THREAD

**Issue by ajhool** [aws-amplify/amplify-js#4032]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Auth (cognito userpools & identity pools), Storage (S3), API (AppSync)

** Provide additional details e.g. code snippets **
My goal is to use federation without using the hosted UI. I have a "mysite.com\/login" page with the federation buttons (Facebook, Amazon, Google). I'm using the code provided under Facebook/Google/Amazon React Samples: https://aws-amplify.github.io/docs/js/authentication#oauth-and-federation-overview , and have been through `amplify update auth` + `amplify push` to add the social login provider info.

When configuring the provider apps, I used my website as the redirect url (mysite.com) instead of `https://<your-user-pool-domain>/oauth2/idpresponse`. It's unclear on `https://aws-amplify.github.io/docs/js/cognito-hosted-ui-federated-identity#facebook-instructions-1` whether those instructions only work for the hosted-ui flow of if that also works when including the login component directly on the site.

When I click on the social login buttons, the respective provider's page does pop up and allow me to login on those accounts. A "SignedIn" auth hub event fires and my user is granted access to the site. However, the user is unable to actually access API or Storage resources, so those requests fail.

**Comment by haverchuck** [comment]
@ajhool Why did you make the redirect for the identity provider the url your site?  Basically, the redirect for the social provider (i.e. Facebook, Google, Amazon) should be the hosted ui endpoint, while the redirect for the hosted ui should be your application (this applies even if your bypassing the actual interface for the hosted ui).  Have you tried chaning your provider app to use `https://<your-user-pool-domain>/oauth2/idpresponse`?

PS: If I remember correctly, some id providers might require you to enter both `https://<your-user-pool-domain>/oauth2/idpresponse` as well as `https://<your-user-pool-domain>`.

**Comment by ajhool** [comment]
Does the hosted endpoint mean that the user will need to interact with the interface provided by AWS / Cognito? My goal is just to have the user interact with my custom signup form on my website -- and my understanding of the hosted UI is that the user is redirected to a UI designed by Amazon and mildly configurable

**Comment by haverchuck** [comment]
@ajhool - You can actually using Hosted UI's functionality without using their user interface.  With amplify, you can call the federatedSignIn function with a 'provider' parameters in the options,  which will direct the user's browser straight through hosted ui to the selected provider.  For example:
```
        <button onClick={() => Auth.federatedSignIn({provider: 'Facebook'})}>Open Facebook</button>
```
This will return tokens as if you had used the Hosted UI interface, but the user will only actually see the facebook sign in screen. You can use this functionality to build your own custom login form.
