### ISSUE TITLE
Support for MaxKeys / params in storage list

### ISSUE THREAD

**Issue by robmoorman** [aws-amplify/amplify-js#4033]
**Is your feature request related to a problem? Please describe.**
Listing content from s3 gives a response of max 1000 entries. I want less. Response is too large.

**Describe the solution you'd like**
Ability to pass through params to the listObjects method, like MaxKeys.

https://github.com/aws-amplify/amplify-js/blob/master/packages/storage/src/Providers/AWSS3Provider.ts#L321-L323
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjects-property

**Comment by ericclemmons** [comment]
https://github.com/aws-amplify/amplify-js/pull/4099 has been merged addressing this.
