### ISSUE TITLE
Showing loader after redirect from OAuth page.

### ISSUE THREAD

**Issue by mdsadique2** [aws-amplify/amplify-js#4036]
So, after the successful Google auth login, the app is redirected to login page again and some data is being downloaded (mostly it is the Token). 
Once the download is complete, the controller moves to Hub listener, from where I am able to set the spinner state as login in progress.

But during, this brief period of download, I want to show some kinda spinner or message to the user. How can I do that?

It relates to point 02 in the comment linked below:
[Comment link here](https://github.com/aws-amplify/amplify-js/issues/1386#issuecomment-532549412)

**Comment by hp0210** [comment]
@mdsadique2 We work around this issue by manually detect the code param in the URL then temporary display the spinner icon until the auth state is updated
`
const params = new URLSearchParams(location.search);
if (params.has('code')) {
    isAuthenticating = true;
}
`

**Comment by mdsadique2** [comment]
> @mdsadique2 We work around this issue by manually detect the code param in the URL then temporary display the spinner icon until the auth state is updated
> `const params = new URLSearchParams(location.search);`
> `if (params.has('code')) {`
> ` isAuthenticating = true;`
> `}`

Thanks a lot, was able to fix the user experience with this :)
