### ISSUE TITLE
Custom Cognito Endpoint override not persisted

### ISSUE THREAD

**Issue by justcompile** [aws-amplify/amplify-js#4037]
**Describe the bug**
When setting the endpoint property for the CognitoUserPool, the initial request(s) correctly use the configured endpoint, but there are then subsequent requests which use the default https://cognito-idp..... URLs.

The purpose for overriding the endpoint is to provide region based proxies/CDN in order to speed up authentication in regions other than which the UserPool resides.

The application I'm using is created by following the Getting started steps: https://aws-amplify.github.io/docs/js/react

**To Reproduce**
1. Configure your Amplify auth to use a custom endpoint for the UserPool (see Sample code)
2. Setup a local reverse proxy (such as nginx) using the steps in "Sample code".
3. Run your Web Application & navigate to the login page.
2. Open your Browser's DevTools & view the Network Tab
3. Enter your username/email & password or register for an account
4. Sign In
5. See in the Network tab that despite a number of requests being sent to localhost (the proxy), some requests are still sent to the cognito-idp URL.

**Expected behavior**
With a custom endpoint set for the UserPool, I would expect all requests to the UserPool to be sent via the proxy rather than some still being sent to the cognito-url.

**Screenshots**
![Screenshot 2019-09-18 at 09 37 24](https://user-images.githubusercontent.com/12406491/65132468-e8a8bc80-d9f8-11e9-895e-bed0564bcc39.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 76

**Additional context**

**Sample code**
```
# Example nginx.conf
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    server {
        listen 80;
        listen [::]:80;

        location / {
            proxy_pass https://cognito-idp.<USERPOOL_REGION>.amazonaws.com/;
        }
    }
}
```

```
# docker-compose.yml
version: '3.7'
services:
  proxy:
    image: nginx:alpine
    ports:
      - 9999:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

```

```
// Hacky Javascript because I'm not a Javascript dev & the endpoint cannot _currently_ be passed in via provided `configure` methods.

Amplify.configure(awsconfig);

Amplify.Auth.userPool = new CognitoUserPool({
  UserPoolId: awsconfig.aws_user_pools_id,
  ClientId: awsconfig.aws_user_pools_web_client_id,
  endpoint: awsconfig.aws_cognito_endpoint,
  Storage: Amplify.Auth.userPool.storage
});
```

**Comment by haverchuck** [comment]
@justcompile Is your application using an identity pool to provision credentials?  Have you verified that the cognito requests you're seeing aren't actually going to the identity pool?

I believe that requests to the identity pool are typically named something like this...
`cognito-identity.${region}.amazonaws.com`
...while calls to the user pool are typically named something like this:
`cognito-idp.${region}.amazonaws.com`.

The sample network calls you posted seem to only show requests to the identity pool, unless I'm missing something.

**Comment by ottokruse** [comment]
(nitpick) A more proper way to configure the custom endpoint in Amplify would be:

```typescript
import { Auth } from "@aws-amplify/auth";
Auth.configure({
  region: "your region",
  userPoolId: "your user pool id",
  userPoolWebClientId: "your client id",
  endpoint: "https://your.custom.endpoint/",
});
```
