### ISSUE TITLE
QoS level for subscriptions

### ISSUE THREAD

**Issue by IshanEyepax** [aws-amplify/amplify-js#4041]
I assume MQTT is used for appsync graphql subscriptions. If so what is the QoS level of the latest amplify version?

**Comment by stocaaro** [comment]
Hello @IshanEyepax,

The Amplify PubSub category used to connect to the AWS IoT interface uses MQTT.  AppSync [uses pure websockets without MQTT](https://docs.aws.amazon.com/appsync/latest/devguide/aws-appsync-real-time-data.html). In the AppSync usecase, with pure websockets, there isn't a QoS setting.

Thanks!
Aaron
