### ISSUE TITLE
Use Amplify from lambda and send a subscription event

### ISSUE THREAD

**Issue by rawadrifai** [aws-amplify/amplify-js#4048]
** Which Category is your question related to? **
Subscriptions

** What AWS Services are you utilizing? **
Lambda, AppSync, Dynamo

** Provide additional details e.g. code snippets **
The goal is to insert data through a lambda function and have it send a subscription event. When using the client side library to insert using a graphql mutation, a subscription is sent to those listening. But if you insert from a lambda using the sdk libraries, it won't. 

I have not tried it but I assume we can use Amplify in lambda. Is there a way to inherit the user login? or do we need to create a cognito user? Maybe there's a different way to fire an event?

**Comment by manueliglesias** [comment]
Hi @rawadrifai 

You can find an example on how to do this in the docs ([GraphQL from Lambda
](https://aws-amplify.github.io/docs/cli-toolchain/quickstart#graphql-from-lambda))

Please note that using Amplify in node is not fully supported but some use cases work (YMMV). This specific one, it is better to use the lambda provided in the docs.

I hope this helps

**Comment by rawadrifai** [comment]
Does help @manueliglesias. Thank you.

**Comment by rawadrifai** [comment]
@manueliglesias question: if I am using a lambda as a custom resolver, i.e. `type Mutation`, to insert data in a dynamo table, do you know how I can have it also generate the necessary events like `onCreateTodo`? I'm using the dynamodb sdk to insert the data.

**Comment by sorokinvj** [comment]
@manueliglesias @rawadrifai  hey guys, did you make it work? I followed an article in the docs and I managed to run mutation but my front-end never received a subscription event connected to this mutation I run in Lambda. How do I debug this?

**Comment by alexkates** [comment]
Running into the same issue @sorokinvj have you heard anything or figured this out yet?

**Comment by sorokinvj** [comment]
> Running into the same issue @sorokinvj have you heard anything or figured this out yet?

I did! Basically, followed advices on the bottom of the comments in this issue 
https://github.com/aws-amplify/amplify-cli/issues/1678#issuecomment-589268180
