### ISSUE TITLE
Application crashes when signing up without touching the form fields

### ISSUE THREAD

**Issue by ricardoribas** [aws-amplify/amplify-js#4049]
**Describe the bug**
If a user trieds to sign up a form **containing only mandatory fields (standard and custom ones)** without touching any of the form fields, the application will crash. The application will not crash anymore after filling the fields. **However**, the validation will pass even if i put custom attributes that are marked as mandatory.

Another thing that i've noticed and i don't know if make sense or not to you guys is the fact that you are passing `isValid` method (inside signUp) as a reference to a button (named as `AmplifyButton`) that is expecting a boolean prop.

**To Reproduce**
#### Case one
1. Add signUpConfig to have three standard fields (username as phone number, name and password), but also two custom fields (for instance age and city)-
2. Go to 'sign up' screen
3. Click on 'sign up'

#### Case two
1. Add signUpConfig to have three standard fields (username as phone number, name and password), but also two custom fields (for instance age and city)-
2. Go to 'sign up' screen
3. Fill the name, username and password fields
4. Click on 'sign up'
5. The form will pass, but there are two extra custom fields (custom:age and custom:city)

**Expected behavior**
The application should not crash on standard fields and should not pass if the custom fields are not filled.

***You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app.***

**Comment by ricardoribas** [comment]
The fix for this issue is to add two changes in the `SignUp.js`:
1 - in the isValid method 
2 - make the **AmplifyButton** to execute the method and not passing it as reference.
How can i create a PR for this issue? I followed all the steps to contribute to this project [here](https://github.com/aws-amplify/amplify-js/blob/master/CONTRIBUTING.md) but i am not allowed to push my code (😄). Maybe i am doing something wrong. The commit hooks are executing successfully.

**Comment by ricardoribas** [comment]
@jordanranz i wonder if there is any progress on this topic. 🤓

**Comment by ericclemmons** [comment]
@ricardoribas Can you share a snippet of your component code?  I'm unsure if you're using `aws-amplify-react`'s `<Authenticator>`, `withAuthenticator`, or another library.

**Comment by sammartinez** [comment]
@ricardoribas As Erics ask above, can you please share your code snippets of your implementations? This will help us further narrow down this issue for you. Thanks ahead of time!
