### ISSUE TITLE
React Native Google Auth

### ISSUE THREAD

**Issue by ilrein** [aws-amplify/amplify-js#4053]
Can the team update the docs to show us how to use Expo + Google + Cognito? There is a good example for Facebook + Expo but not Google.

1) Should you use `Google.logInAsync` from `'expo-google-app-auth'`?
2) How do you get `expires_at` and the `accessToken`?
3) How do you write a refresh handler for Google?

**Comment by correasebastian** [comment]
@ilrein can you share the facebook example please
