### ISSUE TITLE
React-Native Authenticator w/ Custom SignOut button fails to update the authState

### ISSUE THREAD

**Issue by ChrisLFieldsII** [aws-amplify/amplify-js#4057]
**Describe the bug**
Using the drop-in `withAuthenticator` HOC and a custom Sign Out button within the App that calls `Auth.signOut()` fails to change the Authenticators `authState` causing the User to appear as if they are still signed in.

**To Reproduce**
I have created a [repo](https://github.com/ChrisLFieldsII/amplify-auth-test) as well as a [video](https://drive.google.com/file/d/1-CUNuEOtsuKdPhyNOnGkidy9QZ-UB1-q/view?usp=sharing) to show the bug. 

**Expected behavior**
Anytime signOut is called the User is redirected to the Sign In screen without each developer having to hack a solution together 

**Desktop (please complete the following information):**
N/A. Based off the [code](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Auth/Authenticator.tsx#L151) for the aws-amplify-react Authenticator I don't think its a problem there.

**Smartphone (please complete the following information):**
Any React-Native project

**Sample code**
 [repo](https://github.com/ChrisLFieldsII/amplify-auth-test)
[video](https://drive.google.com/file/d/1-CUNuEOtsuKdPhyNOnGkidy9QZ-UB1-q/view?usp=sharing)

**Comment by manueliglesias** [comment]
Hi @ChrisLFieldsII 

Thank you for the very detailed repo and video. After a quick look, seems like our react native `Authenticator` component is not listening for auth events using the `Hub` [the way the react version does](https://github.com/aws-amplify/amplify-js/blob/33be94c3302985f0d84ce275dfdf8e6b3ca69e98/packages/aws-amplify-react/src/Auth/Authenticator.tsx#L137-L163)

I don't have a good workaround for you today (one that isn't super hacky), but we'll look into this issue

**Comment by scharissis** [comment]
I am experiencing this exact issue as well. Using react-native + Expo + amplify auth (default settings) via the withAuthenticator() HOC. My code is almost the same as @ChrisLFieldsII, except I'm using class Components.

```
    "@aws-amplify/api": "^2.1.3",
    "@aws-amplify/pubsub": "^1.3.3",
    "aws-amplify": "^2.2.2",
    "aws-amplify-react-native": "^3.2.0",
    "expo": "^36.0.0",
    "react": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz",
```
