### ISSUE TITLE
POSSIBLE BUG: 401 error with Amplify GraphQL Subscription

### ISSUE THREAD

**Issue by cyrfer** [aws-amplify/amplify-js#4067]
** Which Category is your question related to? **
AppSync Subscription

** What AWS Services are you utilizing? **
AppSync

** Provide additional details e.g. code snippets **

I am using the small snippet of code here to make a subscription. It fails with 401.
https://aws-amplify.github.io/docs/js/api#subscriptions

I would like to see a demo of `Subscriptions` working with the Amplify client library.

How can I avoid this error in my React web app?
```
[DEBUG] 03:21.410 RestClient Error: Request failed with status code 401
    at createError (createError.js:17)
    at settle (settle.js:19)
    at XMLHttpRequest.handleLoad (xhr.js:60)```

**Comment by manueliglesias** [comment]
Hi @cyrfer 

What auth mode is your AppSync graphql api using?
Are queries/mutations working for you?

**Comment by cyrfer** [comment]
@manueliglesias We can close this ticket. I got a subscription to work finally. However, I can see the community really needs a demo using the latest versions of libraries in order to support Hooks for GraphQL queries.

I am using IAM auth, and my Cognito UserPool had multiple Groups.

My problem was that I had overlooked the necessary `appsync:*` or `iot:*` permissions required on the Group my Cognito User was assigned due to Group Precedence. I had applied the permissions to other Roles (Authorized & Unauthorized).

In my attempts to get it to work, I evolved my code from the simple Amplify API module to the more sophisticated Apollo client `AWSAppSyncClient`. 

My dependencies look like, and the version for `react-apollo` is important to note:
```
"aws-appsync": "^2.0.0",
"aws-appsync-react": "^2.0.0",
"graphql-tag": "^2.10.1",
"react-apollo": "^2.5.8",
```

**Comment by manueliglesias** [comment]
I am glad you got it working, thanks for posting your solution so other users can benefit from it.

Thank you for the feedback around a demo using hooks, @dabit3 has a very good [medium post](https://medium.com/open-graphql/react-hooks-for-graphql-3fa8ebdd6c62) showing this, hopefully it helps.
