### ISSUE TITLE
React Native Subscription

### ISSUE THREAD

**Issue by IonutRealDevs** [aws-amplify/amplify-js#4070]
** Which Category is your question related to? **
Subscriptions

** What AWS Services are you utilizing? **
AppSync, Dynamo

** Provide additional details e.g. code snippets **
I have two components in my app, one is used to create a group, the other is used to list all the groups. How can i do to display groups in real time? If I use one single component to create and display groups, it works, but i need to know how to do this with multiple components.

I use `` API.grapqhl(graphqlOperation( ... )) `` to use queries, mutations or subscriptions.

**Comment by manueliglesias** [comment]
Hi @IonutRealDevs 

are you using the [Connect](https://aws-amplify.github.io/docs/js/api#connect) component? If so, you'll find a code sample in the docs I linked to show you how to use subscriptions.

Let us know how it goes

**Comment by IonutRealDevs** [comment]
Subscription still doesn't work... I don't know i'm doing wrong. Here is my code if you can check it.

List.js
```
import React from 'react'
import { View, Text } from 'react-native'
import { graphqlOperation } from 'aws-amplify'
import { Connect } from 'aws-amplify-react-native'

import Create from './Create'

import * as queries from '../graphql/queries'
import * as subscriptions from '../graphql/subscriptions'
import * as mutations from '../graphql/mutations'

class List extends React.Component {
  render() {

    const ListView = ({ items }) => (
      <View>
        {
          items.map(item => (
            <Text key={ item.id }>{ item.name }</Text>
          ))
        }
      </View>
    )
    
    return(
      <View>
        <Connect 
          mutation={ graphqlOperation(mutations.createForTest) }
        >
          {
            ({mutation}) => (
              <Create onCreate={ mutation } />
            )
          }
        </Connect>
        <Connect
          query={ graphqlOperation(queries.listForTests) }
          subscription={ graphqlOperation(subscriptions.onCreateForTest) }
          onSubscriptionMsg={(prev, { onCreateForTest }) => {
              console.log('Data', prev, onCreateForTest)
              return prev
            }
          } 
        >
          {
            ({ data: { listForTests }, loading, error }) => {
              console.log(listForTests)
              if(error) return <Text>Error</Text>
              if(loading || !listForTests) return <Text>Loading...</Text>
              if(!listForTests.items.length) return <Text>No data</Text>
              return (
                <ListView items={ listForTests ? listForTests.items : [] } />
              )
            }
          }
        </Connect>
      </View>
    )
  }
}

export default List
```

Create.js
```
import React from 'react'
import { View, Text, TextInput, TouchableOpacity } from 'react-native'
import uuid from 'uuid/v1'

class Create extends React.Component {

  state = { 
    name: null
  }

  handleChange = text => {
    this.setState({
      name: text
    })
  }

  add = async () => {
    const { onCreate } = this.props
    const input = {
      id: uuid(),
      name: this.state.name
    }
    try {
      await onCreate({input})
    } catch(err) {
      console.log(err)
    }
  }
  
  render() {
    return(
      <View>
        <TextInput onChangeText={ text => this.handleChange(text) } />
        <TouchableOpacity onPress={ this.add }>
          <Text>Add</Text>
        </TouchableOpacity>
      </View>
    )
  }
}

export default Create
```

Also, i want to insert data from Create component. I don't want that Create component to be rendered in List component if is possible.

**Comment by manueliglesias** [comment]
> I make subscription to work, but i'm not sure if this is the correct way.

That looks good to me :D I am happy you got it working

**Comment by alvaroPazosDEV** [comment]
> Subscription still doesn't work... I don't know i'm doing wrong. Here is my code if you can check it.
> 
> List.js
> 
> ```
> import React from 'react'
> import { View, Text } from 'react-native'
> import { graphqlOperation } from 'aws-amplify'
> import { Connect } from 'aws-amplify-react-native'
> 
> import Create from './Create'
> 
> import * as queries from '../graphql/queries'
> import * as subscriptions from '../graphql/subscriptions'
> import * as mutations from '../graphql/mutations'
> 
> class List extends React.Component {
>   render() {
> 
>     const ListView = ({ items }) => (
>       <View>
>         {
>           items.map(item => (
>             <Text key={ item.id }>{ item.name }</Text>
>           ))
>         }
>       </View>
>     )
>     
>     return(
>       <View>
>         <Connect 
>           mutation={ graphqlOperation(mutations.createForTest) }
>         >
>           {
>             ({mutation}) => (
>               <Create onCreate={ mutation } />
>             )
>           }
>         </Connect>
>         <Connect
>           query={ graphqlOperation(queries.listForTests) }
>           subscription={ graphqlOperation(subscriptions.onCreateForTest) }
>           onSubscriptionMsg={(prev, { onCreateForTest }) => {
>               console.log('Data', prev, onCreateForTest)
>               return prev
>             }
>           } 
>         >
>           {
>             ({ data: { listForTests }, loading, error }) => {
>               console.log(listForTests)
>               if(error) return <Text>Error</Text>
>               if(loading || !listForTests) return <Text>Loading...</Text>
>               if(!listForTests.items.length) return <Text>No data</Text>
>               return (
>                 <ListView items={ listForTests ? listForTests.items : [] } />
>               )
>             }
>           }
>         </Connect>
>       </View>
>     )
>   }
> }
> 
> export default List
> ```
> 
> Create.js
> 
> ```
> import React from 'react'
> import { View, Text, TextInput, TouchableOpacity } from 'react-native'
> import uuid from 'uuid/v1'
> 
> class Create extends React.Component {
> 
>   state = { 
>     name: null
>   }
> 
>   handleChange = text => {
>     this.setState({
>       name: text
>     })
>   }
> 
>   add = async () => {
>     const { onCreate } = this.props
>     const input = {
>       id: uuid(),
>       name: this.state.name
>     }
>     try {
>       await onCreate({input})
>     } catch(err) {
>       console.log(err)
>     }
>   }
>   
>   render() {
>     return(
>       <View>
>         <TextInput onChangeText={ text => this.handleChange(text) } />
>         <TouchableOpacity onPress={ this.add }>
>           <Text>Add</Text>
>         </TouchableOpacity>
>       </View>
>     )
>   }
> }
> 
> export default Create
> ```
> 
> Also, i want to insert data from Create component. I don't want that Create component to be rendered in List component if is possible.
> 
> **Edit:**
> 
> I make subscription to work, but i'm not sure if this is the correct way.
> 
> ```
>        <Connect
>           query={ graphqlOperation(queries.listForTests) }
>           subscription={ graphqlOperation(subscriptions.onCreateForTest) }
>           onSubscriptionMsg={(prev, { onCreateForTest }) => {
>             console.log('Data', prev, onCreateForTest)
>             prev.listForTests.items.push(onCreateForTest)
>             return prev
>           }}
>         >
> ```

I also need subscriptions with amplify in my project. Please, tell me what version of **aws-amplify** and **aws-amplify-react-native** did you use and also, in config object do you have the amplify values under API?
