### ISSUE TITLE
Auth.signUp. getting token

### ISSUE THREAD

**Issue by Qunkero** [aws-amplify/amplify-js#4073]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Auth (cognito userpools)
** Provide additional details e.g. code snippets **
My question is **How to get token after user signup.**

In my application Frontend have to pass the token on each request. For communication with AWS we use **aws-amplify**. For _signIn_ , I invoke Auth.signIn(username, password), and on success I can get token with Auth.currentSession().

For _signUp_, I invoke Auth.signUp(), and Auth.confirmSignUp() to confirm, and on success, I have nothing(I only know that user is created) and attempt to get token with  Auth.currentSession() say "No current user". 
As a workaround, after Auth.signUp and Auth.confirm I also invoke Auth.signIn, that is not very comfortable as I need to save a password somewhere. Is this logic correct, or there are exist another way?

**Comment by manueliglesias** [comment]
Hi @Qunkero 

I think your approach is sound, ideally, the password is kept in memory only for a brief period between the `confirm` and `signIn` calls

As of today, I think that's the only option. I'll bring this up to the team for discussion.

Thanks for using Amplify!
