### ISSUE TITLE
Angular 6 federatedSignIn buttons not showing

### ISSUE THREAD

**Issue by ashish-dirkmedia-de** [aws-amplify/amplify-js#4082]
I am using Angular 6. Have done all as in the doc. Userpool login works but the social login like facebook, google is not showing in my form.

**Comment by manueliglesias** [comment]
Hi @ashish-dirkmedia-de 

This should be addressed by #2900

**Comment by ashish-dirkmedia-de** [comment]
I checked recommended link. It says to add components. Can you please guide me more on it like how to copy whole of this as a new module in my angular app.

**Comment by Amplifiyer** [comment]
Closing this as duplicate of #4231. Please add your communication directly in the PR you want it to get merged to master
