### ISSUE TITLE
Does `Auth.forgotPassword()` have a `Hub` event associated with it?

### ISSUE THREAD

**Issue by evanemolo** [aws-amplify/amplify-js#4083]
** Which Category is your question related to? **
Using `Hub` with `Auth`-related methods

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
Calling [`Auth.forgotPassword(<some value>)`]() has no associated `Hub` event on the `auth` channel. Is this intentional or a bug? Considering forgetting a password is an auth-related method, one might expect there to be an event associated with it.

**Comment by manueliglesias** [comment]
Hi @evanemolo 

`forgotPassword` is missing its associated Hub event, thanks for reporting this

**Comment by haverchuck** [comment]
A fix for this has been merged into the unstable build (`npm i aws-amplify@unstable`).  It will be in the build build shortly.
