### ISSUE TITLE
FILTER OFFLINE CACHE - ALTERNATE RESOLVERS FOR OFFLINE

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-js#4085]
**Is your feature request related to a problem? Please describe.**

Any query that is made is cached and available for offline access. So if I'm online and query for all assets in a facility all of those records will be cached. When I'm offline I can repeat the query for all assets in the facility and see those records. However, if I would like to filter that offline cache by modifying the query (ie. query for all assets in a facility that are of type transmitter) then I will get 0 records returned - even though all those records I want to get are actually in the offline cache.

**Describe the solution you'd like**

I'd like to see an alternate resolver deployed when offline status is detected and that specific query is not cached. So if my new query of all assets in a facility that are of type transmitter has not been previously cached, rather than return 0 records, execute a new query with a new resolver (SQLite query rather than DynamoDB/ElasticSearch Query).

The type of query that is available offline will be different to that when it is on-line or cached - so that is why a secondary resolver would be required.

**Describe alternatives you've considered**

We have to determine the network is offline, read all records into memory, then perform our own query in our code. That is a lot of code and a lot of opportunity for things to break and for performance to significantly degrade with larger data sets. 

**Additional context**

Without the ability to easily filter the offline cache then a true offline experience is very difficult to achieve. All the basic building blocks are present, just needs to be assembled to provide that real offline experience.

**Comment by manueliglesias** [comment]
Hi @sacrampton 

Are you using https://github.com/awslabs/aws-mobile-appsync-sdk-js/ ?

I am a little confused about your use case, could you elaborate a little bit more? specially around the resolvers aspect.

It is my impression that you are somehow providing "local resolvers"to the apollo client, is that correct?

**Comment by sacrampton** [comment]
Hi @manueliglesias 

Yes using the sdk for a react native app. Let me try explain my use case.

I have a custom searchable resolver for executing fuzzy full text queries against ElasticSearch and sorting them by multiple conditions. So when I'm on-line I can use the full capabilities of ElasticSearch. When I'm offline I can retrieve any query that I've previously executed as it is cached.

For example, lets say I have a simple type called an Asset with attributes/connections as follows

type Asset{
  id: ID
  type: String
  plant: String
}

If my online query is "select assets where plant="AA-001"" it will populate the off-line cache with all assets in plant AA-001. If I repeat exactly that query when I'm offline then I will get identical results.

The problem comes when I'm offline and add an additional filter to data in the cache - for example "select assets where plant="AA-001" and type="TRANSMITTER" - there will be 0 results returned.

At the moment the only option we have is to use "cache.readQuery" to read the entire original cache and then perform filtering of that data in a JavaScript function and write the result back to the cache.

I have not done anything with "local resolvers" - I was merely suggesting that this might be a good optione for appsync to implement. At the moment it is really difficult to get this cache filtering to work. You have to work out that the device is offline, that the filter you want hasn't been cached, then load everything (ie. if I have 100K records in my cache and I only want to retrieve 1 record it is not really efficient to have to read all 100K records then filter that with JavaScript), execute filtering in JavaScript, write back to cache.

My online resolver has extensive search / sort capabilities via ElasticSearch - so I don't expect offline filtering is anywhere near as powerful as that. So if we had a local SQLite resolver set up to query the offline cache that could kick in when we determine that the cache doesn't have our new filter and we are offline. If you have another method to achieve this without a secondary resolver that's fine - I don't care how we solve it - but it would seem like it might work.

At the moment the "cache.readQuery" method is really not viable for doing this reliably and efficiently.

Hope that helps clarify.

**Comment by manueliglesias** [comment]
Thanks @sacrampton 

That's a very interesting use case!

Not being able to freely query previously fetched results is an issue derived from the fact that Apollo uses a *cache* and not a *database/datastore*.

We've been thinking about this lately, what would you think of a datastore that stores data locally and give you the option to query it with some sort of predicates?

e.g.

```
const transmitters = datastore.query('Assets', 'type = "TRANSMITTER"');
```

Imagine the query being run locally if you're offline or against your API if online

**Comment by sacrampton** [comment]
Hi @manueliglesias 

My app is used in really remote places (offshore oil rigs, remote mining camps, etc.) and my users can be offline for days or weeks. Before they go to site they download all assets they need to work on. Then they can filter for the assets they need. A large facility could have 200K assets. At the moment I can get those 200K records onto the device - but I can't really do much with it when its there (unless I do it all outside appsync).

What you outline looks exactly like what I'm after - being able to have some additional filtering if the device is offline and have that query executed against the local data store when you are offline.

You'd want to have some defined filtering capabilities (ie. type= "TRANS*) - its understood that the query capabilities against the local data store won't be at the same level as online ElasticSearch queries - but at the moment we have nothing.

**Comment by sacrampton** [comment]
Hi @manueliglesias - just checking back in after your initial input whether this is something that is looking likely to get implemented?

**Comment by sacrampton** [comment]
Hi @manueliglesias - just checking back in after your initial input whether this is something that is looking likely to get implemented?

**Comment by sacrampton** [comment]
Hi @manueliglesias  - is there any movement on something like this?

**Comment by sacrampton** [comment]
Hi @manueliglesias - this is a really important capability - any updates?

**Comment by manueliglesias** [comment]
Hey @sacrampton 

We just launched the Amplify DataStore at re:Invent 2019 😄 Please take a look at it and let us know what do you think 

https://aws.amazon.com/blogs/aws/amplify-datastore-simplify-development-of-offline-apps-with-graphql/

**Comment by sacrampton** [comment]
Hi @manueliglesias  - this looks awesome. I'll close this issue now and if I get stuck with DataStore will log something separately there. Thanks. Stephen
