### ISSUE TITLE
Single API request makes 2 requests

### ISSUE THREAD

**Issue by Fawwad-Khan** [aws-amplify/amplify-js#4088]
** API Requests **

** Lambda **

When making http requests using the API module, and noticed that upon calling the function once APP.get() for example, it makes 2 requests, 1 with OPTIONS method and it makes the original request after the first ones response. Im looking to improve the performance of My application and this is really getting in the way.

Please help me understand why is it so, any work arounds or how to disable it completely !?
Thanks in advance :smile:

**Comment by jkeys-ecg-nmsu** [comment]
That's standard HTTPS practice, you'll see the same thing if you use axios to invoke your AppSync endpoint directly.

**Comment by manueliglesias** [comment]
Hi @Fawwad-Khan 

Yeah, as @jkeys-ecg-nmsu mentioned, this is standard practice in web browsers.

If you'd like more info about it, take a look at [Preflight request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request)

**Comment by Fawwad-Khan** [comment]
@jkeys-ecg-nmsu, @manueliglesias Thanks a lot for clearing it up, oddly enough I didn't find anything on it while I was google, maybe I didnt phrase it right :sweat_smile: , Thanks again :smiley:
