### ISSUE TITLE
signIn_failure error when user logging with Oauth - SAML provider

### ISSUE THREAD

**Issue by hp0210** [aws-amplify/amplify-js#4095]
**Describe the bug**
Several of our users that reported they can no login via the SSO flow (oauth flow via hosted ui to SAML provider) after we upgrade aws-amplify library. Aws-amplify dispatch signIn_failure event

**Additional conext**
We recently upgraded our aws-amplify library from 1.1.9 to 1.1.36 and aws-amplify-react from 1.0.19 to 2.3.12:
* In this update we also replaced the way we initialise the federation login process for SAML provider via hosted UI (oauth login)
* Instead of manually construct the url and redirect the user to that like this:
```javascript
let adfsLunchUrl = 'https://'+USERPOOL_HOSTED_DOMAIN+'.auth.'+REGION+'.amazoncognito.com/authorize?redirect_uri='+USERPOOL_ADFS_CALLBACK_URL+'&response_type=code&client_id='+this.APP_CLIENT_ID+'&identity_provider=SAML_PROVIDER_NAME';
```
* We now just use Auth.federatedSignIn method to do that
```javascript
Auth.federatedSignIn({provider: Config.samlProvider.NAME});
```
Everything tested out perfectly until we deployed it to production last Saturday. We got several users that reported they can no login via the SSO flow (oauth flow via hosted ui to SAML provider):
* These users loggin successfully via the hosted ui 
* But when these users are redirected back to us with granted code and the state value. 
```javascript
?code=5b6218f4-7049-4287-ac47-ea9822a08c68&state=rA9PRR669UJDJ0472AuBNnKfSEEuAWlz
```
* aws-amplify dispatched signIn_failure event (The OAuth response flow failed)
* the request to **/oauth2/token** endpoint failed it return invalid_grant error 
```javascript
{"error":"invalid_grant"}
```
<img width="1282" alt="Screen Shot 2019-09-27 at 6 36 46 pm" src="https://user-images.githubusercontent.com/3418775/65756428-6c307f00-e158-11e9-8fd7-707728cf8e23.png">

We also try to upgrade aws-amplify version to the latest stable version atm (1.1.40), but these users still got the same issue. Some of them get a slightly different error response from the /oauth2/token.
* Instead of getting {"error":"invalid_grant"} they get {"error":"invalid_request"}
* This doesn't happen with all of our SSO user. **Is there any possible causes for this issue?**

**Additional context:**
* aws-amplify version 1.1.36
* aws-amplify-react version 2.3.12 
* We can't replicate this locally
* All user reported issue using IE11 (we can't change this as this is our client infrastructure setup)

**Our aws-amplify config**
```javascript
let amplifyConfig = {
  Auth: {
    identityPoolId: Config.cognito.IDENTITY_POOL_ID,
    region: Config.cognito.REGION,
    userPoolId: Config.cognito.USER_POOL_ID,
    userPoolWebClientId: Config.cognito.APP_CLIENT_ID,
    mandatorySignIn: true,
    cookieStorage: {
      domain: Config.reactApp.COOKIE_DOMAIN,
      path: '/',
      expires: 1,
      secure: Config.reactApp.SECURE_PROTOCOL
    },
    oauth: {
      domain : Config.cognito.USERPOOL_HOSTED_DOMAIN+'.auth.'+Config.cognito.REGION+'.amazoncognito.com',
      scope : [ 'openid', 'email' ],
      redirectSignIn : Config.cognito.USERPOOL_ADFS_CALLBACK_URL,
      redirectSignOut : Config.cognito.USERPOOL_ADFS_LOGOUT_URL,
      responseType: 'code',
    }
  },
  Analytics: {
    disabled: true,
    autoSessionRecord: false,
  }
};

Amplify.configure(amplifyConfig)
```

**Comment by manueliglesias** [comment]
Hi @hp0210 

I've seen `{"error":"invalid_grant"}` in the past when for some reason `/oauth2/token` is called twice. Is this the case?

**Comment by hp0210** [comment]
Hi @manueliglesias, from our the investigation session with an impacted user, we can confirm that there was only a single call to the token endpoint. We don't have any access to the logging of cognito hosted UI logging for that endpoint, so it is really hard to see what went wrong there. 

Do you know anything else that could cause this?

**Comment by hp0210** [comment]
In the meantime, we have reverted the solution back to manually construct the hosted UI URL and redirect user to that instead of using Auth.federatedSignIn method. 

We suspect that something in our application logic (maybe sth to do with cookies/localStorage) that may conflict with the way aws-amplify generate and handle the random state but we are not really sure

**Comment by haverchuck** [comment]
@hp0210 According to the [Cognito documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/token-endpoint.html), this error can be caused by the following:

- Refresh token has been revoked.

- Authorization code has been consumed already or does not exist.

**Comment by rabellino12** [comment]
Hi, looking at the console screenshot, the last error in Auth.js 2208 `cannot read property accessToken of undefined` might be related to this error reporting bug i issued here #4004

**Comment by hp0210** [comment]
Hi @rabellino12, I think it is just a part of the problem. The main issue of this is that aws-amplify failed to resolve the granted code (oauth2/token endpoint return error in this case for some reason)

**Comment by rabellino12** [comment]
> Hi @rabellino12, I think it is just a part of the problem. The main issue of this is that aws-amplify failed to resolve the granted code (oauth2/token endpoint return error in this case for some reason)

@hp0210 I know, I just wanted to state that the screenshot error is related to that other issue, and is a big problem, the current version won't catch the correct error for the frontend.

**Comment by byronsorrells** [comment]
I'm seeing the same error. For me, it's happening after a user authenticates in an oAuth flow and they're redirected back to my React SPA. My app is wrapped with an Amplify higher order component for authentication purposes: `export default withAuthenticator(App);`

I log in. Everything is fine. I can browse around. I can log out. I can log back in. I click the URL to authenticate with a provider (Intuit, in this case) and I'm taken to the provider's site. I allow/authorize and I'm redirected back to my app. When redirected, there are URL params for me to use to exchange for an access token: `code=AB11588125966CEYwagFtzGymLY7RK74QJqo6gGHkvcSPjNIwt&state=testState&realmId=4620816365045343910`

This is interfering with the AWS Amplify authentication. I see an error in the console: `OAuth - Error handling auth response. Error: invalid_grant` and I see the sign in screen (giving the impression that I'm logged out). If I remove the query params from the URL, I'm back in my app and things are as they should be.

**Comment by NikolaBo** [comment]
I am seeing the same issue with Auth.federatedSignIn on latest amplify, amplify not resolving granted code
