### ISSUE TITLE
Get username when authenticating with email alias.

### ISSUE THREAD

**Issue by martin19** [aws-amplify/amplify-js#4104]
I'm trying to get the username for a user who logs in via email alias. 

The following call does send a getUser call to cognito which contains the username and attributes. 
```
await user = Auth.currentAuthenticatedUser({
   bypassCache: true
});
```
However calling user.getUsername() will return the email alias instead of the username. 
My current workaround gets the somehow cached response from the storage:

```
let username = JSON.parse((user as any).storage.getItem((user as any).userDataKey)).Username;
```

I feel this is a bug and the real user name should be returned by the function. 
Is there another way to get the username when logging in via email?

**Comment by haverchuck** [comment]
@martin19  - I was unable to reproduce this.  How exactly have you configured your userpool?  Is it like this?

![image](https://user-images.githubusercontent.com/10621276/65991419-2ae2ec80-e442-11e9-8987-a633331b1f32.png)

**Comment by martin19** [comment]
@haverchuck Thanks for your feedback. The pool is configured like this:
![image](https://user-images.githubusercontent.com/4746984/65993519-b3d54480-e491-11e9-8fc2-7f7b12d6bc13.png)

Here is a session that shows the email being returned as username:
![image](https://user-images.githubusercontent.com/4746984/65994492-b20c8080-e493-11e9-8b75-1be58f9bb231.png)
Sending a request to cognito via aws-sdk yields the real username.

Any ideas?
Thanks a lot.

**Comment by haverchuck** [comment]
@martin19 I've matched your configuration in my user pool, and I'm still unable to reproduce this.  I will try bringing this up with the service team.

Have you customized the storage of auth data at all, or are you using the default local storage?

**Comment by martin19** [comment]
@haverchuck The local storage configuration is left to defaults. Thanks for helping.

**Comment by haverchuck** [comment]
@martin19 - When you look at local storage after signIn, what do you see for `CognitoIdentityServiceProvider.<id>.LastAuthUser`?

**Comment by martin19** [comment]
@haverchuck 
When logging in with email address, the value in local storage is the email address.
When logging in with username, the value in local storage is the username.
