### ISSUE TITLE
"; charset=UTF-8" appended when Storage.put with react native for a specific file.

### ISSUE THREAD

**Issue by DIGITALSQUAD** [aws-amplify/amplify-js#4108]
When put a specific movie file, the 'Content-Type' becomes **video/mp4; charset=UTF-8.**
The contentType option of put method seems to be ignored.
`Storage.put('uplload_path', buffer, { level: 'public', contentType: 'video/mp4' })`
Related to this issue? aws/aws-sdk-js#1011

I've tested some movie files recorded by an iOS real device, and some of them are appended '; charset=UTF-8' and some of them are not.

Additionally AWS Lambda does not run by a trigger ObjectCreatedByPut only when '; carset-UTF-8' was appended.

**Comment by elorzafe** [comment]
This is an issue with aws-sdk, there is an open issue there https://github.com/aws/aws-sdk-js/issues/2510 for this. I will ping aws-sdk about this.

Thanks for your feedback
