### ISSUE TITLE
Persist and expose AuthErrorType in AuthError. Also, allow AuthErrorTypes to be referenced.

### ISSUE THREAD

**Issue by clearwaterstream** [aws-amplify/amplify-js#4112]
**Is your feature request related to a problem? Please describe.**

I need to check the error type for my flow. If I call `Auth.signup()`, for example, in the `catch(err)` block I need to do something like:

```javascript
import { Auth } from 'aws-amplify';

Auth.signUp(/*blah*/)
.catch(err => {
	if(err.errorType === AuthErrorTypes.emptyUsername) {
          // blah
	}
});
```

I think checking for errorType vs the actual error message (which can vary by locale) creates a cleaner and more readable code.

**Describe the solution you'd like**

The `type` is already being passed in to the constructor of `AuthError` class. It is simply used to resolve the error messages from `authErrorMessages` dictionary. So the `message` is available in the instance of AuthError class, the `type` however is lost once the constructor ran its course. 

```javascript
export class AuthError extends Error {
    public log: string;
    constructor(type: AuthErrorTypes) {
        const { message, log } = authErrorMessages[type];
        super(message);

        // Hack for making the custom error class work when transpiled to es5
        // TODO: Delete the following 2 lines after we change the build target to >= es2015
        this.constructor = AuthError;
        Object.setPrototypeOf(this, AuthError.prototype);

        this.name = 'AuthError';
        this.log = log || message;

        logger.error(this.log);
    }
}
```

**Can we add `errorType` public field to store the passed in `errorType` so that we can access it later?**

Also, how can I reference `AuthErrorTypes` in my code? I tried

```javascript
import { AuthErrorTypes } from 'aws-amplify';
```
and it did not work.

**Describe alternatives you've considered**

I tried  doing error message (vs type) comparison by trying to reference this class:

```javascript
export const authErrorMessages: AuthErrorMessages = { /* ... */
```

via

```javascript
import { authErrorMessages } from 'aws-amplify'
```

but that did not work. I'm running this in a React app btw, js.

**Additional context**
THANK YOU!!

P.S. The concept of "error type" or "error code" is probably used everywhere in Amplify framework, in one form another. I would consider adding "errorType" or "errorCode" to the base Error class. I think for multi-lingual apps having error code is helpful.

**Comment by dohomi** [comment]
@haverchuck is there any workaround? Its quite common to have some error specific code and I don't understand why the AuthErrorTypes aren't re-exported?

**Comment by jimblanc** [comment]
We have published an RFC on our plan for improving TypeScript support in Amplify JS & would love to get your feedback & suggestions!

[RFC: Amplify JS TypeScript Improvements](https://github.com/aws-amplify/amplify-js/issues/11113)

**Comment by AndyMeagher** [comment]
Any updates on this request? I also would love to have insight into the Errors being thrown by Amplify via codes or types.

**Comment by cwomack** [comment]
The developer preview for v6 of Amplify has officially been released with TypeScript improvements and much more! Please check out our [announcement](https://aws.amazon.com/blogs/mobile/aws-amplify-javascripts-new-developer-preview-with-reduced-bundle-sizes-improved-typescript-and-next-js-support/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=238088647) and updated [documentation](https://docs.amplify.aws/lib-v1/project-setup/create-application/q/platform/js/) to see what has changed.  

This issue should be resolved within the dev preview and upcoming General Availability for Amplify v6, but let us know with a comment if there are further issues.

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
