### ISSUE TITLE
Compatibility with Relay

### ISSUE THREAD

**Issue by neoPix** [aws-amplify/amplify-js#4117]
** Which Category is your question related to? **
- Relay
- Schema

** What AWS Services are you utilizing? **
- Amplify with GraphQL

** Provide additional details e.g. code snippets **

I'm currently trying to make Amplify work with relay.js. This graphQL client requires a  standard way of organizing the GQL schema which is not the way Amplify does things.

https://relay.dev/docs/en/graphql-server-specification.html

The pagination system does not match the edges/node requirements of Relay. Is there an easy way around ?

**Comment by beeto** [comment]
@neoPix Any success integrating Amplify with Relay?  I'm working on a project now, and checking if there any any lessons to share on the integration.

**Comment by totaland** [comment]
Would love to know too. @neoPix @beeto

**Comment by danaugrs** [comment]
Also very interested in this.

**Comment by jufemaiz** [comment]
👀

**Comment by neoPix** [comment]
The short answer to this question is no. They're no easy way around.
One solution would have been to manage this manually using directly AWS AppSync and Lambda doing your own implementation.
I finally used a more classical and implementation limit free approach with Apollo.
