### ISSUE TITLE
How do i properly unmount Auth tasks? Error: cancel all subscriptions and asynchronous tasks in the componentWillUnmount method

### ISSUE THREAD

**Issue by chai86** [aws-amplify/amplify-js#4119]
How do i properly unmount after using Auth? 

```
 componentDidMount = async () => {
    await Auth.currentAuthenticatedUser()
    .then(user => {
      this.setState({userToken: user.signInUserSession.accessToken.jwtToken})
    })
 }

 componentWillUnmount(){
    //??????
  }
```

**Comment by haverchuck** [comment]
@chai86 What exactly needs to be 'unmounted'?  In the code above, it looks like a function is being called once in the lifecycle method.  If my understanding is correct, the componentWillUnmount lifecycle method would be used to do things like clean up the DOM, destroy an Observable subscription, etc.
