### ISSUE TITLE
is there facebookSignUp method in withFederated component methods?

### ISSUE THREAD

**Issue by sorokinvj** [aws-amplify/amplify-js#4122]
** Which Category is your question related to? **
Authentication with Social Buttons

** What AWS Services are you utilizing? **
Amplify, Cogntio

** Provide additional details e.g. code snippets **

Hey guys, sorry if this was answered in the past, but I couldn't find anything related. 

My goal is to make custom SignUp component and I want my users to have an ability for signing up with Facebook, Google. How do I achieve that? Is there a method in withFederated component that I want to use?

**Comment by haverchuck** [comment]
@sorokinvj - 

At a high level there are two primary means of achieving this:

1. Federating with Cognito Identity Pools
2. Federating with Cognito User Pools

You can use option 1 if you don't particularly care about using Cognito to persist information about the users who are logging in; it is simply a means of provisioning temporary credentials for AWS resources to users who have authenticated with an identity providers such as Facebook (although you can use it to create a merged id for users who are logging in with different providers).  If you are using React/React Native we have UI components that support this.  If you are using Angular or Vue we have open pull requests that support this functionality but they are not yet merged.  In any case, you can always create your own components.  Information can be found [here](https://aws-amplify.github.io/docs/js/authentication).

You can use option 2 if you want to persist user records in user pools even when users are signing in with Google, Facebook, etc.  This option uses the OAuth2 standard along with Cognito's Hosted UI, which provides a customizable interface for users to sign in.  You can alternatively bypass hosted UI using your own components while still using Congito's OAuth2 flow.  With this options, the browser will navigate away from your app briefly, but when it returns it will contain OAuth2 data in the url which Amplify will automatically parse and use to provision your user with credentials (assuming you are using this in conjunction with an identity pool).  Again, Amplifiy's React and React Native packages provides a out-of-the-box button that says 'Signin with AWS' which will direct to Hosted UI, but you don't have to use this.  More information can be found [here](https://aws-amplify.github.io/docs/js/authentication#oauth-and-federation-overview).

Hope this helps.

**Comment by sorokinvj** [comment]
@haverchuck Dustin, thanks for the quick reply!

The problem is that all the examples you mentioned use 'SignIn' case but not 'SignUp', so I'm struggling to understand the whole process. Could you please clarify step by step what do I need to for signin up users with Facebook/Google? 

Shall I first call Auth.federatedSignIn then collect email and send it to Cognito User Pool? 

Sorry, I confused and don't know how to proceed

**Comment by sorokinvj** [comment]
oh enlightenment! 

Maybe I don't need at all a "Sign Up with Facebook"?  Is it possible to sign in user with his Facebook/Google without even creating the user in the Pool?  – it would be awesome!!!

**Comment by haverchuck** [comment]
@sorokinvj  - If you are using Hosted UI (i.e. federation with User Pools), then a user pool record will be created for you.  Federated sign_up_ is not needed.

**Comment by haverchuck** [comment]
Closing this issue, as I think the question has been answerd.
