### ISSUE TITLE
Manage Cognito User Pool using JWT

### ISSUE THREAD

**Issue by vinyoliver** [aws-amplify/amplify-js#4124]
** Cognito **

I have a Node.js lambda API that's called by an authenticated user. The user is able to access the API passing a valid JWT token. Now I'd like to interact with Cognito User Pool to change the user's email, password and etc but I haven't figured out how to achieve this using just the JWT.

I've made several tests using amplify-js and amazon-cognito-identity-js

**Comment by haverchuck** [comment]
Hi @vinyoliver 

Is this a [token](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html) that has been returned by the Cognito User Pool?  If so, it should have an access token.  This access token is what would typically be passed in authenticated calls to User Pool API methods such as [Change Password ](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ChangePassword.html).

I should note that Amplify does not officially support Node, and for calls such as Auth.changePassword it retrieves the access token for an authenticated user from browser storage, so you might encounter issues running it in Node.  You could try [configuring Amplify's storage](https://aws-amplify.github.io/docs/js/authentication#managing-security-tokens) to store these values in memory.

**Comment by vinyoliver** [comment]
Hi @haverchuck 

Tks for the fast response! I was not aware that there's an admin API. I looked at the documentation but I couldn't find to which endpoint should I send my requests and what config is necessary; If by any chance do you know this and could point me in the right direction I'd be grateful.
