### ISSUE TITLE
Amplify - Database like Tinder -  best practice

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-js#4126]
I am currently using a Lambda function for a principle similar to Tinder.
The user swiped cards, the wiped cards I save in an extra table. 
In a lambda function I query all cards and delete the wiped ones. 
I can do this because the total number of cards will be 1400. I think the performance is sufficient here. 

The question is now, if I would want to build the same system without limiting the cards, i.e., I don't know before how many cards I will get total from the table and how many there will be which I have already wiped. What is the best way to build this with Amplify? 

I thought up to work with ElasticSearch because I also have to query geospital in the future.

**Comment by dabit3** [comment]
Hey @davidbiller, are you wanting to still continue using only Lambda or are you open to using AppSync / GraphQL / DynamoDB?

**Comment by davidbiller** [comment]
@dabit3 Thanks for help. Would be nice if we find a good solution... 

Okay now it gets a bit more complex, but so that other people might find a setting here as well, I'll make it more detailed. Since I have already tested a few things.

So what i have:

GraphQL:
--------------------------------------------------------------
```
type User @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  owner: String!
...
}

type Career @model {
  id: ID!
  name: String
}

type Careerinteract
  @model
  @auth(rules: [{ allow: owner }])
  @key(
    name: "ByOwnerByDecision"
    fields: ["owner", "decision"]
    queryField: "careerInteractByOwnerByDecision"
  ) {
  id: ID!
  owner: String!
  career_id: String!
  career: Career! @connection(name: "interactcareer")
  decision: Int!
}

```
----------------------------------------------------------------------

Lambda:
----------------------------------------------------------------------

```
1. get all CareerCards (current 1400)
2. get all Careerinteracts (current max 100)

CareerCards - CareerInteracts = my result
```

**For max 1400 Cards, this is fine i guess.** 


So in the future, there will be
- a geospital search too. 
- many more cards.
- find cards by Career Id´s.

So i search a better way to check if a card is seen, to dont show this card again. (User swiped it already)


#My Plan
So now i thought about something like this:
Use ElasticSearch to: give me all UnseenCareerCardsWithTheIDs [1,2,3]withMaxDistance(20km)

1. I could give the User Model a countNumber (cNumber) 
2. if a new CareerCard is added to the DB, there is a continuous count Number. 

My thoughts:
ElasticSearch Custom Resolver like this:


## Query.nearbyJobs.req.vtl

```
#set( $indexPath = "/job/doc/_search" )
#set( $distance = $util.defaultIfNull($ctx.args.km, 30) )
{
    "version": "2017-02-28",
    "operation": "GET",
    "path": "$indexPath.toLowerCase()",
    "params": {
      "body": {
        "size": 30,
        "sort": [
          {
           "countNumber": {
           "order": "asc"
          }
         },
         {
          "createdAt": {
            "order": "desc"
            }
         }
        ],
        "query": {
          "bool": {
            "must": [
             {
                "range": {
                "countNumber": {
                "gte": $ctx.args.countNumber
                }
              }
             },
              {
                "range": {
                  "createdAt": {
                    "gte": "now-30d/d"
                  }
                }
              },
              {
                "terms": {
                  "careerID": $util.toJson($ctx.args.professionslist)
                }
              }
            ],
            "filter": {
              "geo_distance": {
                 "distance" : "${distance}km",
                 "location" : $util.toJson($ctx.args.location)
              }
            }
          }
        }
     }
  }
}
```


So elasticSearch would only give me the unseen Cards. In my theory.

3 Problems i see here:

1. I have to manage ElasticSearch (scaling) by myself
2. When a user swipes a card there are some calls: 
 - createCareerInteract (to save the decision)
 - CountNumber++ for the CareerID
3. I have to add a CNumber in an array for every CareerID


So - feel free to be creative! :D

**Comment by davidbiller** [comment]
@dabit3 Do you have an Idea here? Or a recommendation who can help me here? 
Thanks

**Comment by dabit3** [comment]
I see you have the Decision set as an `Int`, is this basically going to be 0 or 1 depending if the person has seen it?

Also, I think you may want to dive a little deeper into data modeling with DynamoDB because I think this is entirely possible without elasticsearch if you use composite keys.

Check out this talk (disregard the evangelism around a single table, most importantly around data modeling imo): https://www.youtube.com/watch?v=HaEPXoXVf2k

Also, check out these docs: https://aws.amazon.com/blogs/database/choosing-the-right-dynamodb-partition-key/

**Comment by davidbiller** [comment]
@dabit3 

> I see you have the Decision set as an `Int`, is this basically going to be 0 or 1 depending if the person has seen it?

Nope. This is if a user liked it our disliked the card.
Careerinteract is table for the saved swipes. If there is a entry with UserID and CareerID, the user has seen this card already. 


> Also, I think you may want to dive a little deeper into data modeling with DynamoDB because I think this is entirely possible without elasticsearch if you use composite keys.

Mhhh with a geospital search too? 

I need a query like this:
Give me all unswiped cards in radius of 20 km.

**Comment by davidbiller** [comment]
@dabit3 
I've been looking at your links. Thank you. 

As far as I understand it now, you recommend to use the SortKey, something like this:

There is a table with open jobs. PrimaryKey = UDID.
SortKey could be something like that: 
userID1#userID3#UserID202

Then I can query something like that:
Gives me all jobs that don't contain userID1.

A few questions:
1. if this job was viewed by 100k users, then the field "SortKey" is quite big?! Doesn't matter? Because I don't have to request it via GraphQL?
1.1 In the video I understood that there is a way to build the update of the SortKey so that adding a new UserID does not make any data disappear. 2 users wipe a card at the same time. Both UserID´s would then be added to the SortKey. Probably about an append solution in a CusomResolver for Appsync right?

2. if I want to display a list with all jobs. But I want to mark which jobs have already been seen. Then I still need the field SortKey in my answer? Would then be a lot of traffic. 

3. can I combine this with a geospital search? Within a radius. 
So i found this: https://github.com/rh389/dynamodb-geo.js#readme

**Comment by davidbiller** [comment]
@dabit3 

I looked again. 
I didn't find a way to combine that with a geo search. 
An item is viewed by a maximum of 5,000 users. Therefore a concat solution would be fine I think. What does your experience say? 
 

Otherwise I looked at the has_Child function of ElasticSearch. Maybe it would be a solution, too. But of course I would like to stay serverless, if that works.

**Comment by davidbiller** [comment]
@dabit3 Any news here? Else we can check if its easier to talk about that per mail?

**Comment by pwnreza** [comment]
Hey there,
Just wanted to ask if there was any additional information regarding the eleastic search integration you guys have exchanged you might wanna share. I'm basically going thru the assembly of a similar stack.

thank you in advance
