### ISSUE TITLE
Filter article by categories - possibilities

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-js#4127]
The user specifies categories and I would like to get suitable articles from the DB over AppSync GraphQL.

What is the best way to do this with Amplify?

Using AppSync filter is lala, because I can't query all articles. Let's say there is no topic X in the first 20 items, then the first call would be with an empty array as answer and i have to use the nextToken.

I can go via a SortKey, but this way I only get one topic per call if i sort by categories.

Alternatively I can go here only over ElasticSearch or?

**Comment by dabit3** [comment]
I would suggest creating a GSI for the category fields so when creating a new article you can concatenate the categories and save them for each article which will make them searchable, i.e. a category field may look like: `automotive#home#sports`. Then you can query on the category:

```
type Article @model
    @key(name: "bycategory", fields: ["type", "category"], queryField: "itemsByCategory") {
  id: ID!
  name: String!
  type: String!
  categories: String
}

mutation createArticle {
  createArticle(input: {
    name: "Great football games"
    type: "Article"
    categories: "football#sports#europe"
  }) {
    id name type categories
  } 
}

query ItemsByCategory {
  itemsByStatus(type: "Article", category: {contains:"sports"}) {
    id
    name
    type
    categories
  }
}
```

**Comment by davidbiller** [comment]
Thx @dabit3 

That would actually be a possibility as well, that's true. I didn't have that in my head. Thanks for that first of all. 

As soon as I need a geospital search, would I still need to use ElasticSearch correct?

But first start with your suggestion :)

**Comment by davidbiller** [comment]
@dabit3 
We can query only for one category here until appsync supports the IN operator. Any thoughts?
