### ISSUE TITLE
FederatedSigin for Social Signin returns 'No current user' or  'not authenticated'

### ISSUE THREAD

**Issue by pepemiso16** [aws-amplify/amplify-js#4132]
**Describe the bug**
Using AWS Amplify and VueJS, I have successfully configured AWS Cogntio, Facebook and Google. I am using Auth.federatedSignIn({provider: 'Facebook'}) and Auth.federatedSignIn({provider: 'Google'}) for their respective sign-in pages. However, after successful sign-in and once redirected to the web app the result shows the error message 
'No current user' or  'not authenticated' but if I refresh the page it will then show the cognito detials.

**To Reproduce**

1. Use vuejs for front-end
2. Install this plugins: 
"aws-amplify": "^1.1.40",
"aws-amplify-vue": "^0.2.17",
3. Configure Facebook and Google developer
4. Sign In using Auth.federatedSignIn({provider: 'Facebook'}) and Auth.federatedSignIn({provider: 'Google'})

**Expected behavior**
Once redirected to the main web app, the user should be logged-in automatically and dashboard will show together with user details from cognito

**Screenshots**
![Screenshot_34](https://user-images.githubusercontent.com/35057503/66167997-6aa31180-e698-11e9-8c79-e1c5015e64a3.png)

**Comment by haverchuck** [comment]
@pepemiso16 -  Just to be clear, are you federating via the User Pool (hosted UI) or the Identity Pool?  I have a very simple Vue app which just performs login via User Pool federation w/ Facebook, and I cannot reproduce the error:

```
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
    <button v-on:click="signIn">sign in w/ facebook</button>
  </div>
</template>

<script>
import HelloWorld from './components/HelloWorld.vue'
import Amplify, { Auth, Hub } from 'aws-amplify';
import awsconfig from './aws-exports';
Amplify.configure(awsconfig);

export default {
  name: 'app',
  components: {
    HelloWorld
  },
  methods: {
    signIn: async function() {
      let res = await Auth.federatedSignIn({provider: 'Facebook'});
    }
  }
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
```

I wonder if perhaps your application is trying to actually make a request of an AWS resource upon redirect, and maybe there is some sort of race condition where this request is being dispatched before the authenication process has completed?

Perhaps you could try enabling [logging](https://aws-amplify.github.io/docs/js/logger) and seeing if there is any helpful output.

**Comment by pepemiso16** [comment]
@haverchuck I am using federating via User Pool (hosted UI). On my scenario, I have a login page and a dashboard page and I am working on it locally. I have configured everything at AWS and when I login using Facebook (same code as yours), my configured link for redirection will be the Dashboard page (http://localhost:8080/). However when gmail or facebook redirect to the Dashboard (http://localhost:8080/) it indicates that the user is not authenticated or there is no current user. I am using Auth.currentSession and Auth.currentAuthenticatedUser. 

On your end, can you be able to determine that the user was logged in already on your web app after signing in to facebook?

**Comment by ericclemmons** [comment]
@pepemiso16 Thanks for your additional details!

This sounds similar to a bug I researched here:
> https://github.com/aws-amplify/amplify-js/issues/3841#issuecomment-543338595

Basically, `Auth.currentAuthenticatedUser()` resolves initially based on what's in local state, but the OAUTH redirect flow is still in flight. 

Try adding an `AmplifyEventBus.$on('authState', info => {...})` listener (see the example below) and let us know if that helps!

(In the meantime, we're investigating how to have `Auth` wait for the redirect flow's resolution before returning)


```vue
<template>
  <div id="app">
    <div v-if="!signedIn">
      <amplify-authenticator></amplify-authenticator>
    </div>
    <div v-if="signedIn">
      <amplify-sign-out></amplify-sign-out>
      <img alt="Vue logo" src="./assets/logo.png">
      <HelloWorld msg="Welcome to Your Vue.js App"/>
    </div>
  </div>
</template>

<script>
import { AmplifyEventBus } from 'aws-amplify-vue'
import HelloWorld from './components/HelloWorld.vue'
import { components } from 'aws-amplify-vue'

export default {
  name: 'app',
  components: {
    HelloWorld,
    ...components
  },
  beforeCreate() {
    AmplifyEventBus.$on('authState', info => {
      if (info === 'signedIn') {
        this.signedIn = true
      } else {
        this.signedIn = false
      }
    })
  },
  data() {
    return {
      signedIn: false
    }
  }
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}

body {
  margin: 0
}
</style>

```

**Comment by jcardus** [comment]
I'm still having this issue
