### ISSUE TITLE
How to get Channel-type in Lex Request

### ISSUE THREAD

**Issue by vsatyav007** [aws-amplify/amplify-js#4133]
I'm Using ChatBot react component from aws-amplify react to build the frontend.ChatBot communicates with lex and sends a request to lambda. In Lex, I connected it with facebook and Twilio. In Lambda I'm able to access the sessionAttributes.Is there a way to get the channel-type?

Lambda index.js
exports.handler = async (event, context, callback) => {
    try {
        // 1. Gather information from the current session.
        let sessionAttributes = event.sessionAttributes || {};
        }
}
Web Application: 
<ChatBot
          title="Demo Assistant"
          theme={myTheme}
          botName="DemoBot"
          onComplete={this.handleComplete.bind(this)}
          welcomeMessage={"Welcome! How may I assist?"}
          clearOnComplete={true}
          voiceEnabled={false}
          conversationModeOn={false}
        />

Thanks,
Satya Veera

**Comment by vsatyav007** [comment]
can anyone update me on this?

**Comment by jkeys-ecg-nmsu** [comment]
@vsatyav007 I think you'll need to take this up with the Lex service team. If the event sent to your validation/fulfillment lambda doesn't contain the attribute you need, there's nothing the Amplify team can do about it until the service team updates the API to include the channel-type in the event.

That being said, is there any reason you can't store the channel-type as a sessionAttribute?

**Comment by ashika01** [comment]
@vsatyav007 : Looks like there is much amplify could do here. as @jkeys-ecg-nmsu mentioned, is there a reason for not using sessionAttribute for this?

Do you feel Amplify team could do something more here?
