### ISSUE TITLE
AuthClass configure fire twice

### ISSUE THREAD

**Issue by hagaigold** [aws-amplify/amplify-js#4136]
**Describe the bug**
Auth configuration execute more the once which can be observed by Auth._handleAuthResponse.
This creates unexpected results for the login process with "Authorization code grant".

**To Reproduce**

this behavior happen when using **Amplify.configure** (e.g. to configure API in different module) after Auth.configure. 
replacing the order of execution or using API.configure will work as expected.

1. configure auth with `Auth.configure({...})` with `responseType: 'code'`
2. configure API with `Amplify.configure({ API: {..} })`
3. configure the user pool to accept Authorization code grant
4. add a breakpoint in Auth._handleAuthResponse  or in Auth.js
```
urlListener(({ url }) => {
    this._handleAuthResponse(url);
});

```
**Expected behavior**
While I think I understand why this happening, a warning or error from the framework will be appreciated ;)
 
**Desktop**
- OS: Win10
- Browser: chrome v77

**Sample code**
```
import Amplify from 'aws-amplify'
import Auth from '@aws-amplify/auth'
import API from '@aws-amplify/api'

Auth.configure({...})

Amplify.configure({
  API: {
    endpoints: [
      {
        name: 'MyAPI',
        endpoint: 'abcde.execute-api.eu-west-1.amazonaws.com/dev',
        region: 'eu-west-1'
      }
    ]
  }
})

//
// this will work fine...
//
// API.configure(
//   {
//     endpoints: [
//       {
//         name: 'MyAPI',
//         endpoint: 'https://abcde.execute-api.eu-west-1.amazonaws.com/dev',
//         region: 'eu-west-1'
//       }
//     ]
//   })
```

**Comment by sammartinez** [comment]
@hagaigold I do want to let you know that under `Amplify.configure` both Auth and API are [automatically](https://aws-amplify.github.io/docs/js/authentication#configure-your-app) configured when passing the awsconfig via `aws-exports` which I believe that is what you mean by your understanding. However, I can mark this as a feature request for the documentation call out that we can either pass a warning or error message.

**Comment by tannerabread** [comment]
Hi 👋 Closing this as resolved. 

Configuring most category outside of Auth is going to re-configure Auth and cause this error. The docs are pretty clear to use `Amplify.configure` now. We recommend using `Amplify.configure` to configure all of your categories at the same time or doing each category individually.

Thank you!
