### ISSUE TITLE
Safari cannot open the page because the address is invalid

### ISSUE THREAD

**Issue by gHashTag** [aws-amplify/amplify-js#4141]
**Describe the bug**
I go into the application through Facebook authentication, but after all the steps in the tutorial, I get an error.
`Safari cannot open the page because the address is invalid`

``` 
 LOG  [DEBUG] 40:45.261 OAuth - Redirecting to https://messagae88c11c5-e88c11c5-dev.auth.eu-west-1.amazoncognito.com/oauth2/authorize?redirect_uri=messaga%3A%2F%2F&response_type=code&client_id=3slv66ufo1geciv83bbb8h4pt9&identity_provider=Facebook&scopes=phone%2Cemail%2Copenid%2Cprofile%2Caws.cognito.signin.user.admin&state=MgoxvOgPFmD9gJk0IJCzIOmrOPhsq21L&code_challenge=1dNbs_qn-jIkmhMPHR5HraVHL44WBiHKZI4VihlKsgg&code_challenge_method=S256
 LOG  [DEBUG] 40:48.322 urlListener - urlListener {"url": null}
 LOG  [DEBUG] 40:48.338 Hub - Dispatching to auth with  {"data": {"url": null}, "event": "parsingCallbackUrl", "message": "The callback url is being parsed"}
 LOG  [DEBUG] 40:48.339 Analytics - on hub capsule auth {"data": {"url": null}, "event": "parsingCallbackUrl", "message": "The callback url is being parsed"}
 LOG  [DEBUG] 40:48.339 Hub - Dispatching to auth with  {"data": {"url": null}, "event": "parsingCallbackUrl", "message": "The callback url is being parsed"}
```

**To Reproduce**
## 1. I call the provider of Facebook in react-native app
```Auth.federatedSignIn ({provider: 'Facebook'})```

## 2. Window opens Facebook
![IMG_0789](https://user-images.githubusercontent.com/6774813/66322755-4c087900-e92b-11e9-80c2-7599b431f284.PNG)

## 3. After I choose next
![Simulator Screen Shot - iPhone SE - 2019-10-07 at 17 11 44](https://user-images.githubusercontent.com/6774813/66322874-807c3500-e92b-11e9-8807-2803b703b857.png)

**Expected behavior**
I look forward to entering the application

**Screenshots**
<img width="1440" alt="Screenshot 2019-10-07 at 17 56 20" src="https://user-images.githubusercontent.com/6774813/66323051-dc46be00-e92b-11e9-98df-753fa723735d.png">

**Desktop (please complete the following information):**

- OS: iOS

**Smartphone (please complete the following information):**

- OS: iOS 12.1.4
- Browser Safari

**Additional context**

**Sample code**
[ Repo ](https://github.com/react-native-village/messaga)

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by sammartinez** [comment]
@gHashTag Are you still experiencing this issue on the latest version of Amplify?

**Comment by rahulje9** [comment]
@sammartinez  I'm having the same issue, I tried with the latest version of Amplify

**Comment by amhinson** [comment]
@gHashTag Based on the repo you provided, it doesn't look like you've setup the redirect URIs in your iOS app yet.
https://docs.amplify.aws/lib/auth/social/q/platform/js#sign-in-redirect-uris

You'll need to add this to `AppDelegate.m`:
```obj-c
#import <React/RCTLinkingManager.h>

- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}
```

and then add something like this to `Info.plist`:
```xml
<key>CFBundleURLTypes</key>
<array>
	<dict>
		<key>CFBundleURLSchemes</key>
		<array>
			<string>myapp</string>
		</array>
	</dict>
</array>
```

**Comment by rahulje9** [comment]
> @gHashTag Based on the repo you provided, it doesn't look like you've setup the redirect URIs in your iOS app yet.
> https://docs.amplify.aws/lib/auth/social/q/platform/js#sign-in-redirect-uris
> 
> You'll need to add this to `AppDelegate.m`:
> 
> ```objc
> #import <React/RCTLinkingManager.h>
> 
> - (BOOL)application:(UIApplication *)application
>    openURL:(NSURL *)url
>    options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
> {
>   return [RCTLinkingManager application:application openURL:url options:options];
> }
> ```
> 
> and then add something like this to `Info.plist`:
> 
> ```
> <key>CFBundleURLTypes</key>
> <array>
> 	<dict>
> 		<key>CFBundleURLSchemes</key>
> 		<array>
> 			<string>myapp</string>
> 		</array>
> 	</dict>
> </array>
> ```

Hey Thanks for the reply, I found these after posting the comment.

I also have a question if you know please answer this 

https://github.com/aws-amplify/amplify-js/discussions/5538
