### ISSUE TITLE
Auth.signIn always throwing NotAuthorizedException error after changing to new userpool.

### ISSUE THREAD

**Issue by kfwebdev** [aws-amplify/amplify-js#4147]
** Which Category is your question related to? **
Auth.signIn()

** What AWS Services are you utilizing? **
AWS Amplify

** Provide additional details e.g. code snippets **
Auth.signIn() was working properly with a pervious userpool. I created a new userpool to perform[ email and phone_number alias checks](https://github.com/aws-amplify/amplify-js/issues/1067#issuecomment-436492775) with Auth.confirmSignup(). However, on this new userpool, Auth.signIn() only returns NotAuthorizedException with message: "Incorrect username or password." when signing in with any confirmed users.

Things I tried/checked:
* Triple confirmed userpool id, userpool client id and identity pool id in the Amplify.configure() call
* Confirmed credentials are correct by logging into Elasticsearch Kibana with identity pool role
* Auth.signUp() works correctly and users show up confirmed in the new user pool
* Auth.forgotPassword() is recognizing user pool users and sending confirmation code emails

Any suggestions as to what could be causing Auth.signIn() to return errors when with another user pool it was working correctly?

Update: My user pool id was being set incorrectly. One of the config files was passing a string and not the global constant so it did was referring to an old user pool id. Other functions like Auth.signUp and Auth.forgotPassword still worked but Auth.signIn did not. After updating to the global constant containing the new user pool id, all is working properly now.

**Comment by sammartinez** [comment]
@kfwebdev Can you provide the versions of `aws-amplify` you are using? Also, are you using a framework with this such as React / Vue / Angular ?

**Comment by kfwebdev** [comment]
@sammartinez thanks for your response Sam! I was using ```
"aws-amplify": "1.1.36",
"aws-amplify-react": "2.3.12"
```
I upgraded to the latest ```
"aws-amplify": "^1.1.40",
"aws-amplify-react": "^2.4.4",
```
to see if that changed anything but so far the result still seems to be the same.

**Comment by kfwebdev** [comment]
Update: My user pool id was being set incorrectly. One of the config files was passing a string and not the global constant so it did was referring to an old user pool id. Other functions like Auth.signUp and Auth.forgotPassword still worked but Auth.signIn did not. After updating to the global constant containing the new user pool id, all is working properly now.

**Comment by sammartinez** [comment]
Great! Glad it got worked out :)
