### ISSUE TITLE
Auth.federatedSignIn with customProvider and customState do not work as intended.

### ISSUE THREAD

**Issue by haolinj** [aws-amplify/amplify-js#4155]
**Describe the bug**
Hi, I'm trying to use `Auth.federatedSignIn` with both `customProvider` and `customState`:
```
Auth.federatedSignIn({ customProvider: 'my-provider', customState: '?mystate=xxx' })
```
The above should construct a URL to `/oauth2/authorize` with param `identity_provider=my-provider`, instead it creates with URL with param `identity_provider=COGNITO` (I believe this is the default value when `provider` is undefined). 

If I remove the `customState` in the call: `Auth.federatedSignIn({ customProvider: 'my-provider' })`, it works as expected.

**To Reproduce**

1. Configure custom IdP provider for the Cognito.
2. Call Amplify with `Auth.federatedSignIn({ customProvider: 'my-provider', customState: '?mystate=xxx' })`
3. Open you Network Dev tool of your browser and preserve the log (to see the redirects)
4. Check the redirect URL for `/oauth2/authorize`

**Expected behavior**
The redirect URL should have query param `identity_provider=my-provider`

**Desktop (please complete the following information):**

- OS: Windows 10 Home 
- Browser Chrome
- Version 77.0.3865.90 

**Additional context**
I thinks this is caused by [Auth.ts#L1643](https://github.com/aws-amplify/amplify-js/blob/c28851a6379f3ba05c4fef529bb5be7f18ebe316/packages/auth/src/Auth.ts#L1643) and [types/Auth.ts#L81](https://github.com/aws-amplify/amplify-js/blob/c28851a6379f3ba05c4fef529bb5be7f18ebe316/packages/auth/src/types/Auth.ts#L81) which the check for `isFederatedSignInOptions` will return `true` if a `customState` specified, this makes `provider = undefined` since I only specified `customerProvider` and `options.provider` is undefined. I'm not sure if this is intended, but it makes `{ customerProvider, customState }` never work as expected. 

Currently I can workaround with `Auth.federatedSignIn({ provider: 'my-provider', customState: '?mystate=xxx' })` with `@ts-ignore`, since `provider` only supports few provider in the type definition.

**Comment by mauerbac** [comment]
This issue has been fixed here https://github.com/aws-amplify/amplify-js/issues/5860
