### ISSUE TITLE
Optionally use SMS MFA vs. Custom Auth

### ISSUE THREAD

**Issue by Audace** [aws-amplify/amplify-js#4157]
**Which Category is your question related to?**
Usage

**What AWS Services are you utilizing?**
Cognito, Lambda, Amplify

**Provide additional details e.g. code snippets**
Hi there, we'd like to differentially route users through a passwordless SMS MFA or a custom challenge. We want to do this to allow QA testers to not have to receive an MFA SMS and instead have a hard-coded token they can always use for their number.

With that in mind, we've set MFA to optional on the entire cognito pool. We've created 4 triggers. A Pre sign-up trigger that auto verifies users. A Define Auth Challenge trigger that determines whether to show the SMS MFA or the cusotm challenge. A Create Auth Challenge trigger that creates the auth challenge for the custom challenge. A Verify Auth Challenge Response trigger that verifies the auth challenge for the custom challenge.

In the Define Auth Challenge trigger, we either return the challenge after `SRP_A` and `PASSWORD_VERIFIER` to be `SMS_MFA` or `CUSTOM_CHALLENGE`. When we only return `CUSTOM_CHALLENGE`, the system bypass works like a charm. However, we cannot figure out how to integrate returning the `SMS_MFA` with the SMS texts previously sent and verified under the hood when MFA was set to ON for the entire pool.

A few questions:
1. How do we achieve this functionality?
2. Is there an easier way by which we can set MFA to be enabled for certain users using one of the triggers?

**Comment by haverchuck** [comment]
@Audace  I am not quite sure I understand what you mean by this:

> However, we cannot figure out how to integrate returning the SMS_MFA with the SMS texts previously sent and verified under the hood when MFA was set to ON for the entire pool.

Can you elaborate a bit - is your issue in the Lambda trigger code itself or in the Amplify library?
