### ISSUE TITLE
Token not invalidated when changing password on different browsers

### ISSUE THREAD

**Issue by Jun711** [aws-amplify/amplify-js#4168]
**Describe the bug**
JWT tokens aren't invalidated when users change password.

**To Reproduce**

1) login the same account on browser A and browser B 
2) change password on browser A
3) use Auth.currentAuthenticatedUser() to check user object on browser B
4) session is still valid

**Expected behavior**
Expect session to be invalidated and thus, we can show login UI to ask users to re-login.

**Desktop (please complete the following information):**
all

**Smartphone (please complete the following information):**
all

**Comment by madmed88** [comment]
you can use Auth.signOut({ global: true }) after changing the password to make sure the tokens are invalidated

**Comment by Jun711** [comment]
@madmed88 
ok, I will try that.

Does doing this means when a user changes password, the user has to re-logs in?

**Comment by Jun711** [comment]
@madmed88 

I tried `Auth.signOut({ global: true })` but `Auth.currentAuthenticatedUser()` still returns authenticated user on the other browser.

**Comment by madmed88** [comment]
try Auth.currentAuthenticatedUser({ bypassCache: true })

**Comment by Jun711** [comment]
ok. will try that. 

on the other issue, you mentioned you use `Auth.signOut({ global: true })` when users change their password. How does your app opened on other browsers detect whether the token is still valid? What do you use?

**Comment by madmed88** [comment]
I did not figure that out yet, I have a similar issue open regarding that #4164

**Comment by madmed88** [comment]
As a workaround I run this code whenever a user interacts with the page:
```
            user.getUserData(
                err => {
                  if (err) {
                    Auth.signOut();
                  }
                },
                {
                  bypassCache: true,
                }
              )
```

**Comment by hckr** [comment]
@Jun711 @madmed88 Did you maybe figure it out by now? I also need to detect this.

**Comment by hckr** [comment]
I run the following check at the interval, but it's a nasty hack, not a solution:

```js
setInterval(() => {
    Auth.currentAuthenticatedUser({ bypassCache: true }).catch(() => Auth.signOut());
}, LOGIN_STATE_CHECK_INTERVAL_MS)
```

**Comment by shadycuz** [comment]
Make sure you are sending them to the signout endpoint. 

https://docs.aws.amazon.com/cognito/latest/developerguide/logout-endpoint.html

**Comment by mauerbac** [comment]
It looks like there might be follow-up issues. Let's continue the convo on Issue #4164. Will close this out.
