### ISSUE TITLE
Is there a way to allow any User to add only themselves to an array of Users?

### ISSUE THREAD

**Issue by aej11a** [aws-amplify/amplify-js#4171]
** Which Category is your question related to? **
API (GraphQL Transform), Auth
** What AWS Services are you utilizing? **
DynamoDB, Cognito User Pools
** Provide additional details e.g. code snippets **
For example, I want to add a list of Users called "Fans" to a "Movie" type. Authenticated users should be able to add themselves to this "Fans" array of Users, but shouldn't be able to add/remove other users from the list.

How would I set this up in GraphQL Transform Auth directives?

**Comment by mauerbac** [comment]
Hey @aej11a - here are our [docs](https://aws-amplify.github.io/docs/cli-toolchain/graphql#auth). If you still need assistance on this, can you send over a code snippet?
