### ISSUE TITLE
Auth - computeModPow - React Native 0.61

### ISSUE THREAD

**Issue by paul-doherty** [aws-amplify/amplify-js#4172]
**Describe the bug**
How am I supposed to use Amplify auth with RN 0.60+?
I am in the process of upgrading RN versions but Amplify is not playing ball and is throwing when I run `Auth.signIn`.

I am on `"aws-amplify": "^1.2.2"` and when I attempt to login I get the computeModPow 
 issue [https://github.com/aws-amplify/amplify-js/issues/563](https://github.com/aws-amplify/amplify-js/issues/563)

Following that thread I installed `amazon-cognito-identity-js` and let it autolink this yields the error 
```
{"code": "SerializationException", "message": "Start of structure or map found where not expected.", "name": "SerializationException"}
```

I manually linked `amazon-cognito-identity-js` but that isn't it either as than complains that `amazon-cognito-identity-js` is already linked. How exactly is it supposed tobe setup?

**To Reproduce**
Install Amplify on RN 0.60+ (not using `aws-amplify-react-native`) and  attempt to signin to 
```
Auth.signIn(username, password)
      .then(async (user: CognitoUser | any) => {
        this.onSuccessfulLogin(user);
      })
      .catch((error: any) => {
        this.setState({ requestInProgress: false }, () => this.loginErrorMessage(error));
      });
```

**Expected behavior**
Amplify auth allows login in 0.60 React Native apps

**Smartphone (please complete the following information):**

- Device: Android
- OS: 9

**Additional context**

``` LOG  [DEBUG] 42:15.102 AuthClass - signIn failure {"code": "SerializationException", "message": "Start of structure or map found where not expected.", "name": "SerializationException"}
 LOG  [DEBUG] 42:15.105 Hub - Dispatching to auth with  {"data": {"code": "SerializationException", "message": "Start of structure or map found where not expected.", "name": "SerializationException"}, "event": "signIn_failure", "message": "9a695ac0-c4a1-4c51-8ff0-33fc1fa27e06 failed to signin"}
 LOG  [DEBUG] 42:15.107 Analytics - on hub capsule auth {"data": {"code": "SerializationException", "message": "Start of structure or map found where not expected.", "name": "SerializationException"}, "event": "signIn_failure", "message": "9a695ac0-c4a1-4c51-8ff0-33fc1fa27e06 failed to signin"}
```

**Comment by sammartinez** [comment]
@paul-doherty Have you gotten a chance to look at React Native [documentation](https://aws-amplify.github.io/docs/js/start#option-2-use-react-native-cli-recommended-if-you-have-mobile-development-experience)?

**Comment by sammartinez** [comment]
#4148

**Comment by paul-doherty** [comment]
@sammartinez yep, I've read the documentation but it doesn't seem correct

It suggests
```
yarn add aws-amplify aws-amplify-react-native
react-native link amazon-cognito-identity-js 

If you are using React Native 0.60.0+, iOS and using Auth methods e.g. Auth.signIn, Auth.signUp, etc., please run the following commands **instead** of linking:

yarn add amazon-cognito-identity-js
cd ios
pod install --repo-update

```

The issue you linked to is for RN 0.59 and so linking is ok there. As I said I am on RN 0.60 and so amazon-cognito-identity-js should be autolinked on Android and indeed I do see it pulled in by a gradle sync in Android studio after I add it yarn add it.

Debugging further I see this is a direct response from Cognito
<img width="1156" alt="Screenshot 2019-10-12 at 12 18 37" src="https://user-images.githubusercontent.com/5806615/66700641-b1bd8200-ecea-11e9-82f0-acd416f9fee0.png">

**Comment by jimbol** [comment]
I'm also having this issue.
```
"aws-amplify": "^1.2.2",
"aws-amplify-react-native": "^2.2.2",
"react-native": "0.60.5",
```

This fix worked for me - https://github.com/aws-amplify/amplify-js/issues/563#issuecomment-377733312

**Comment by paul-doherty** [comment]
@jimbol that fix is for iOS. Were you able to get it working on Android?

**Comment by Ashish5591** [comment]
> @sammartinez yep, I've read the documentation but it doesn't seem correct
> 
> It suggests
> 
> ```
> yarn add aws-amplify aws-amplify-react-native
> react-native link amazon-cognito-identity-js 
> 
> If you are using React Native 0.60.0+, iOS and using Auth methods e.g. Auth.signIn, Auth.signUp, etc., please run the following commands **instead** of linking:
> 
> yarn add amazon-cognito-identity-js
> cd ios
> pod install --repo-update
> ```
> 
> The issue you linked to is for RN 0.59 and so linking is ok there. As I said I am on RN 0.60 and so amazon-cognito-identity-js should be autolinked on Android and indeed I do see it pulled in by a gradle sync in Android studio after I add it yarn add it.
> 
> Debugging further I see this is a direct response from Cognito
> <img alt="Screenshot 2019-10-12 at 12 18 37" width="1156" src="https://user-images.githubusercontent.com/5806615/66700641-b1bd8200-ecea-11e9-82f0-acd416f9fee0.png">

Hi @paul-doherty, If I understand correctly,  I think the issue in your title is not the problem you are actually facing. 

It seems initially you got the computeModPow issue, but once you added `amazon-cognito-identity-js` as per the docs, that particular issue went away as expected. 
You are correct that it should autolink on Android, and it does which is why you dont see that issue anymore. The documentation that you quoted states the same, where we give the extra `pod install` step for ios but nothing in the case of android (as everything should be autolinked). Please let us know if we can improve this further.

The `SerializationException` error you are getting is coming directly from the cognito service, so you have successfully setup the app and are able to talk to cognito. The error message and `400` status code suggests that the request you sent was probably malformed and could not be understood by the server. 

Could you check to see that your request format matches what is expected in the docs?

**Comment by paul-doherty** [comment]
@Ashish5591 you are correct I have moved past the issue and am experiencing the `SerializationException`

This app is being upgraded and the call used to work. The app code hasn't changed `Auth.signIn(username, password)` but it is still giving me that issue

**Comment by paul-doherty** [comment]
I am going to close this issue out. I found my problem was my own fault. As part of updating to RN 0.60 I added my own storage class to work around the AsyncStorage issue https://github.com/aws-amplify/amplify-js/issues/3422 and there was an issue with my implementation. 

Thanks for the assistance

**Comment by Ashish5591** [comment]
Glad you were able to isolate the issue and fix it!
