### ISSUE TITLE
Enabling MFA in code and then remembering the device does not suppress MFA

### ISSUE THREAD

**Issue by oystagoymp** [aws-amplify/amplify-js#4174]
**Describe the bug**

Does not suppress MFA when device is remembered if MFA is set to optional and enabled in code. 

**To Reproduce**
1. In Cognito set MFA to optional in the "MFA and verifications" tab. Set User Opt in and Yes to supress MFA in the "Devices" tab.
2. Create a new user and retrieve it: 
`const user = await Auth.currentAuthenticatedUser({bypassCache:true});`
3. Enable MFA for that user:
`await Auth.setPreferredMFA(user, "SMS");`
3. Remember the device for the user: 
```
user.setDeviceStatusRemembered({
          onSuccess: function(result) {
            console.log("call result: " + result);         
          },

          onFailure: function(err) {
            alert(err);
          }
        });
```
4. Navigate to Cognito and notice that the device key is remembered and the phone number is verified.

5. call Auth.signIn(username, password) and notice the challengeName is SMS_MFA

**Expected behavior**
The challengeName should be undefined as the device is remembered and MFA should  be suppressed.

If there is a log out and login and MFA code is passed to Auth.confirmSignIn and then the device is remembered by calling Auth.setDeviceStatusAsRemembered. It successfully suppresses MFA.

- OS: Windows 10
- Browser Chrome

**Additional context**
Nothing changes in Cognito when it works and when it doesn't.

**Comment by elorzafe** [comment]
@oystagoymp just to clarify, after step 4 you are trying to signIn without signOut first?

**Comment by jordanranz** [comment]
I believe `Auth.setPreferredMFA` will re-enable MFA which will take precedence over step 1 where you suppress MFA.

**Comment by jordanranz** [comment]
I believe `Auth.setPreferredMFA` will re-enable MFA and force the challenge name of `SMS_MFA` to be returned. I am curious why `Auth.setPreferredMFA` is being called in this call flow?

**Comment by nihp** [comment]
I am using Auth.signUp to register in my app (aws-amplify-react-native).

Here I not received code, so i have checked the cognito it shows the need to enable MFA. How can I enable this MFA if the user not received code and how can I handle this while Auth.signUp?
