### ISSUE TITLE
withAuthenticator with usernameAttributes not working

### ISSUE THREAD

**Issue by jasper72** [aws-amplify/amplify-js#4175]
My cognito pool is set up to use email as my username.

![image](https://user-images.githubusercontent.com/939156/66704426-daa63d00-ed13-11e9-9a04-966e4a619c8d.png)

And I am using withAuthenticator with usernameAttributes:

![image](https://user-images.githubusercontent.com/939156/66704483-2b1d9a80-ed14-11e9-889a-aa9b3fab5274.png)

But I still get validation errors in the browser complaining about the username:

![image](https://user-images.githubusercontent.com/939156/66704500-4f797700-ed14-11e9-9d0f-c1a499b72ac0.png)

I'm using the latest version of aws-amplify. Any tips gratefully received.

**Comment by elorzafe** [comment]
Thanks @jasper72 we will take a look at this

**Comment by elorzafe** [comment]
@jasper72 I just tried it and is working for me, are you sure that username does not exist on the userpool?

**Comment by jasper72** [comment]
username is a confusing word in this context so I shall carefully say that the email is unique (its an empty pool).

Even if that was not true it would still be a bug because the error message is not that it is not unique but that the format is wrong.

I have also tried this using Auth.signup with the same error message although I can't find an example of the syntax so I may have this wrong.

**Comment by jasper72** [comment]
I'll make a general comment about amplify: why am I configuring this at all? It should configure itself on the basis of the pool it is attached to just as the default signup page does for the pool.

**Comment by jasper72** [comment]
Random thought: could the difference between our environments be because I use Amplify.configure() to establish the pool rather than using a pool generated by Amplify?

**Comment by elorzafe** [comment]
@jasper72 the issue is that you have `name` attribute required but that is not part of the signUp form. You can customized your signUp form like this

```javascript
const signUpConfig = {
  header: 'My Customized Sign Up',
  hideAllDefaults: true,
  defaultCountryCode: '1',
  signUpFields: [
    {
      label: 'Name',
      key: 'name',
      required: true,
      displayOrder: 1,
      type: 'string'
    },
    {
      label: 'Email',
      key: 'email',
      required: true,
      displayOrder: 2,
      type: 'string'
    },
    {
      label: 'Password',
      key: 'password',
      required: true,
      displayOrder: 3,
      type: 'password'
    },
    // and other custom attributes
  ]
};

export default withAuthenticator(App, { usernameAttributes: 'email', signUpConfig, includeGreetings: true });
```

Attribute `name` will be sent to Cognito. The bug from the library is that the error message is not helping you to discover that. I will mark this as a bug and I will sent a PR to fix this.

Thanks for pointing this out!

**Comment by jasper72** [comment]
Sorry but this isn't true. I had, of course, already tried that but just for kicks tried your config which also doesn't work for me,

**Comment by elorzafe** [comment]
@jasper72  sorry to hear that, can you share the error you are getting from Network request?

**Comment by jasper72** [comment]
Retested, to get network error, and it actually worked. Which is great. I must have messed up in test earlier, or it cached. You can close and If it turns out to be intermittent I can always reopen. Many thanks.

**Comment by geoffnewton** [comment]
For what it's worth, I stumbled across this thread whilst looking into a similar problem. My Cognito setup triggered by withAuthenticator has only Email and Password. I get that error message when the email is valid (not already in the pool) but the password fails the pool complexity requirements (mixed case, has number etc.) So in my case the error should be that the password is not valid rather than the error message implying the username (or email) is incorrect. Supply a compliant password string and the Cognito user is created successfully.

**Comment by codeglider** [comment]
Hi, I've been working with react native and seemed to have been having a similar issue. I've fixed it. Works for me in all cases. Now you can toggle between email and username signin and signup pages with configuration.
[PR-5491](https://github.com/aws-amplify/amplify-js/pull/5491)

```
authConfig: {
    usernameAttributes: 'email',
},
```
putting this in the signUpConfig will impact both the signin and signup pages.

**Comment by codeglider** [comment]
![awsreactnativeattributeissue](https://user-images.githubusercontent.com/1178161/79943721-a7b5d200-8437-11ea-94be-e09bc5dc86aa.gif)
