### ISSUE TITLE
Updating User Attributes in Auth.updateUserAttributes() gives error with certain area codes

### ISSUE THREAD

**Issue by mcg5de** [aws-amplify/amplify-js#4176]
**Description**
When using the Auth.updateUserAttributes() call as part of an "Edit Profile" page on my website, a certain subset of phone number area codes results in an "InvalidParameterException" saying that the phone number format is invalid, despite following the +XXXXXXXXXX format that is specified. The area codes that it doesn't seem to work for are 857, 858, & 859. There have been no issues with other area codes that I have found so far, and it does not seem to be an input error when parsing the user input.

The returned error is:
{code: “InvalidParameterException”, name: “InvalidParameterException”, message: “Invalid phone number format.”}

**To Reproduce**

1. Call Auth.updateUserAttributes() and attempt to update a user's phone number with an area code listed above. 
2. Observe error

**Desktop/ Mobile**
- OS: Tested on various devices (macOS Mojave/ Windows 10/ iOS)
- Browser: Tested on chrome and safari

**Comment by elorzafe** [comment]
@mcg5de the phone number starts with +1?

**Comment by mcg5de** [comment]
Ah yes, thank you very much. That would be the thing I missed.
