### ISSUE TITLE
Refreshing Auth Token for Unauthenticated Cognito Users during storage.put

### ISSUE THREAD

**Issue by DoctahPopp871** [aws-amplify/amplify-js#4179]
** Which Category is your question related to? **
Auth/Storage
** What AWS Services are you utilizing? **
Cognito, s3
** Provide additional details e.g. code snippets **
We are able to successfully authenticate and initiate uploads to s3. We have added transfer acceleration to the storage module and it works very well. Our current issue is that the auth token expires after 1 hour, and our uploads stop, and fail due to the expired token. Ive seen many examples and "solutions" in other issues but they just dont fit our use-case. 
https://github.com/aws-amplify/amplify-js/issues/446#issuecomment-373904697
https://github.com/aws-amplify/amplify-js/issues/3310
#6408 

Does amplify support storage puts that last for longer than an hour, when using Cognito Identity pools ? 

If so, how ? Ive attached a snippit of code from our file upload attempt, where we have tried to refresh the token prior to the hour mark. We seem to be able to do so, however, that token is not used during the s3 upload. help!

[s3client.txt](https://github.com/aws-amplify/amplify-js/files/3722577/s3client.txt)

**Comment by elorzafe** [comment]
@DoctahPopp871 how large are your files? or is because is a slow connection? We may need to consider this use case @pravgupt

**Comment by DoctahPopp871** [comment]
Hello @elorzafe,

These are large genomic files, 100GiB. Our use-case, is unique, but we have high speed low latent connections we are utilizing when moving these large files. We can move 60-70GiB files under the hour mark easily. ~100GiB seems to be when we reach the hour token timeout threshold. 
As mentioned, we ensured the fastest transmission by enabling transfer acceleration on our buckets, and adding that functionality to our forked version of the storage module. 

This feature would be a boon for us, and assist in helping solve a tricky health problem. Thanks!

**Comment by DoctahPopp871** [comment]
I started looking into where this change might be implemented, and notice there already seems to be a function handling the refresh of tokens in the storage provider https://github.com/aws-amplify/amplify-js/blob/master/packages/storage/src/Providers/AWSS3Provider.ts#L195 

Which leverages the core credentials file, and this function `_pickupCredentials` https://github.com/aws-amplify/amplify-js/blob/master/packages/core/src/Credentials.ts#L59

Im assuming that somewhere within this try block that the attempt to refresh credentials needs to be made : https://github.com/aws-amplify/amplify-js/blob/master/packages/storage/src/Providers/AWSS3Provider.ts#L261-L273

Any guidance is welcome and much appreciated.

**Comment by DoctahPopp871** [comment]
Any additional guidance here ?

**Comment by DoctahPopp871** [comment]
Is this issue being considered or is it dead ?

**Comment by patelvarun** [comment]
I am also facing the same problem - https://github.com/aws-amplify/amplify-js/issues/6408

**Comment by iartemiev** [comment]
This feature has been released as part of aws-amplify@3.0.23 / @aws-amplify/storage@3.2.12
