### ISSUE TITLE
Auto filled username and password on login shows "Username cannot be empty" in firefox

### ISSUE THREAD

**Issue by ashish-dirkmedia-de** [aws-amplify/amplify-js#4180]
I am using angular 6 with amplify. All works but in firefox when username and password are autofill shows username and password cannot be empty. Only works when edited.
Can you please help I tried lots of things.

**Comment by ashish-dirkmedia-de** [comment]
Please give me some idea to fix the issue. Just to brief the issue:
When the username and password are already saved in browser so we dont actually enter these fields it is automatic when we go to login page. I get username and password null.
If I type in then allworks.
Please help

**Comment by sammartinez** [comment]
@ashish-dirkmedia-de Do you have a code example by chance for this you can link us? Also can you provide the amplify versions you are using and which version of `aws-amplify-angular` you are using?

**Comment by ashish-dirkmedia-de** [comment]
"@aws-amplify/ui": "^1.0.25"
"aws-amplify": "^1.1.40",
"aws-amplify-angular": "^3.0.15",

**Comment by ashish-dirkmedia-de** [comment]
Is it related with ChangeDetectionStrategy.OnPush set in my application at the app component?

**Comment by ashish-dirkmedia-de** [comment]
Used the directive way to resolve the issue

**Comment by satishmolletipipra** [comment]
@ashish-dirkmedia-de  I'm facing the same issue, any code change we need to do for this. if yes can you please help me to fix this.

**Comment by satishmolletipipra** [comment]
@ashish-dirkmedia-de Can you please help me on this.

**Comment by satishmolletipipra** [comment]
@sammartinez @elorzafe @ashish-dirkmedia-de Please help me on this. this is a show stopper for us.
