### ISSUE TITLE
Memory Leak. 

### ISSUE THREAD

**Issue by njdullea** [aws-amplify/amplify-js#4181]
**Describe the bug**

aws-amplify-react-native 2.2.2 (current) is using react-native-vector-icons 5.0.0, which is using yargs 8.0.2, which is using os-locale 2.0.0, which is using mem 1.1.0 which has a memory leak. 

Please upgrade to the most recent react-native-vector-icons version to remove this memory leak.

**Comment by elorzafe** [comment]
@njdullea thanks for pointing this out
