### ISSUE TITLE
Querying AWS IoT Thing registry/thing shadow using GraphQL

### ISSUE THREAD

**Issue by elgutierrez** [aws-amplify/amplify-js#4182]
** Which Category is your question related to? **
GraphQL API

** What AWS Services are you utilizing? **
AWS IoT

** Provide additional details e.g. code snippets **
I would like to use Amplify with AWS IoT. Is it possible to integrate the thing registry and thing shadow? How could I map it to a GraphQL schema and use the queries, mutations and other resources generated by Amplify?

**Comment by elorzafe** [comment]
Hi @elgutierrez, What problem are you trying to solve? You want to send data from a thing to AppSync and then query that data?

**Comment by elgutierrez** [comment]
Hey @elorzafe, yes that's it, I would like sending data from a thing, applying rules, etc using AWS IoT and querying (current and past data) on my frontend using the default GraphQL API. Also, is it possible to query the things registry from GraphQL?

**Comment by jkeys-ecg-nmsu** [comment]
>Also, is it possible to query the things registry from GraphQL?

AppSync supports Lambda resolvers so you can always implement this logic in a Lambda. Not sure how to get started beyond writing the lambda tho.
