### ISSUE TITLE
API.graphql Filter over same attribute with different values

### ISSUE THREAD

**Issue by santi8194** [aws-amplify/amplify-js#4195]
**Describe the bug**
It is not possible to use a query with a filter that has the same attribute more than once. Javascript doesn't allow having duplicate properties on an object.

**Expected behavior**
I would expect to be able to pass a list of attribute filter objects (`{endTime: { ge: "2019-10-01T00:00Z" }}`) to the filter object

  ``` javascript
// filter entities with endDate outside of range
const filter = {
      restrictions: [
         { endTime: { lt: "2019-10-01T00:00Z" }},
         { endTime: { gt: "2019-11-01T00:00Z" }}
      ]
    };
const res = await API.graphql(
    graphqlOperation(listEntityQuery, { filter })
  );
```

**Desktop (please complete the following information):**

- Any javascript version

**Amplify context**
- React Native
- "aws-amplify": "^1.1.36"

**Sample code**

  ``` javascript
const filter = {
      endTime: { ge: "2019-10-01T00:00Z" },
      endTime: { lt: "2019-11-01T00:00Z" }
    };
const res = await API.graphql(
    graphqlOperation(listEntityQuery, { filter })
  );
```
which is invalid in javascript. the second endTime would just rewrite the first.

**Comment by ijavierTek** [comment]
Try including them as 1 attribute:
```
const filter = {
endTime: { ge: "2019-10-01T00:00Z" lt: "2019-11-01T00:00Z" }
};
```

**Comment by santi8194** [comment]
Thanks @ijavierTek, I didn't know how to use the filter properly.

Closing
