### ISSUE TITLE
Amplify currentUserinfo returns null

### ISSUE THREAD

**Issue by jmandivarapu1** [aws-amplify/amplify-js#4197]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
When I used ```authenticationFlowType: 'USER_PASSWORD_AUTH'``` in my configuration of amplify. After I signin with my usrname and password then Auth.currentUserInfo() is returning null.

I doubled checked it. If I remove authenticationFlowtype it shows all the user properties

**To Reproduce**
1. Go to 'config file and add authenticationFlowType: 'USER_PASSWORD_AUTH''
2. check on '.Auth.currentUserInfo()'
3. See Null

**Expected behavior**
It should return user attributes

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jkeys-ecg-nmsu** [comment]
@jmandivarapu1 as a temporary patch, can you see if you can use this to replace currentUserInfo?

```
//inside async function
const attributes = await Auth.currentSession().getIdToken().payload
```

(that's the syntax off the top of my head, you may need log currentSession() to see how to get the idToken payload if that doesn't work)

**Comment by jkeys-ecg-nmsu** [comment]
@jmandivarapu1 did that put you back into prod?

**Comment by jmandivarapu1** [comment]
> @jmandivarapu1 did that put you back into prod?

Nope Unfortunately because I am using the ```Auth.currentUserInfo()```  to get all the custom variables.

Hoping from someone AWS will reply. But they transferred the issue.

**Comment by jkeys-ecg-nmsu** [comment]
@jmandivarapu1 run the command I gave you to get the custom attributes...

**Comment by jmandivarapu1** [comment]
> @jmandivarapu1 run the command I gave you to get the custom attributes...
> 
> `const attributes = (await Auth.currentSession()).getIdToken().payload`
> 
> The id token's payload includes all token attributes. `currentUserInfo` is probably only provided as an optimization or convenience function, assuming it checks locally before sending a network request.

Yeah I like the idea.  But don't know what's happening why session is null and all.

But it's throwing error **No current user**.

But when I did  var cognito_resp= await Auth.signIn(this.state.email, this.state.password);

<img width="530" alt="Screen Shot 2019-10-17 at 10 30 21 PM" src="https://user-images.githubusercontent.com/21245519/67061264-cd32ed80-f12d-11e9-95b3-a828320310a3.png">

**Comment by jkeys-ecg-nmsu** [comment]
Have you tried updating `aws-amplify` and `aws-amplify-react` to the latest build to see if that resolves the issue with `No current user`? `npm install aws-amplify aws-amplify-react`

Still, I think you can grab the tokens from `signInUserSession` which looks like it has a valid session. I've never noticed that Session prop in the CognitoUser type. Did you look at `signInUserSession` to see if it has valid tokens?

**Comment by elorzafe** [comment]
@jmandivarapu1 Can you share the `package.json` file of your App?

**Comment by jmandivarapu1** [comment]
This Stack deletion proved to be a never ending night mare for me. Everything feels like interrelated.

> @jmandivarapu1 Have you tried updating `aws-amplify` and `aws-amplify-react` to the latest build to see if that resolves the issue with `No current user`? `npm install aws-amplify aws-amplify-react`
> 
> Still, I think you can grab the tokens from `signInUserSession` which looks like it has a valid session. I've never noticed that Session prop in the CognitoUser type. Did you look at `signInUserSession` to see if it has valid tokens?
> 
> @jordanranz is it possible OP is experiencing the delayed `Amplify.configure` problem that you helped me resolve a while back?

Yeah I just update but still the same
<img width="487" alt="Screen Shot 2019-10-17 at 11 04 19 PM" src="https://user-images.githubusercontent.com/21245519/67062862-a7f4ae00-f132-11e9-9a18-747392c89720.png">
<img width="530" alt="Screen Shot 2019-10-17 at 10 59 47 PM" src="https://user-images.githubusercontent.com/21245519/67062863-a7f4ae00-f132-11e9-9f62-78c70fc94363.png">

**Comment by jmandivarapu1** [comment]
> @jmandivarapu1 Can you share the `package.json` file of your App?

Yeah sure.

{
  "name": "@coreui/root-react-admin-template",
  "version": "2.1.0",
  "description": "Root React Admin Template",
  "author": {
    "name": "Łukasz Holeczek",
    "url": "http://holeczek.pl",
    "github": "https://github.com/mrholek",
    "twitter": "https://twitter.com/lukaszholeczek"
  },
  "contributors": [
    {
      "name": "Andrzej Kopański",
      "url": "https://github.com/xidedix"
    }
  ],
  "homepage": ".",
  "copyright": "Copyright 2018 creativeLabs Łukasz Holeczek",
  "license": "https://coreui.io/pro/license/",
  "private": true,
  "dependencies": {
    "@coreui/coreui-plugin-chartjs-custom-tooltips": "^1.2.0",
    "@coreui/coreui-pro": "^2.1.0",
    "@coreui/icons": "^0.3.0",
    "@coreui/react": "^2.1.0",
    "@material-ui/icons": "^3.0.2",
    "@opuscapita/react-filemanager": "1.1.0-beta.6",
    "@progress/kendo-react-animation": "^2.11.0",
    "@progress/kendo-react-treeview": "^2.11.0",
    "@progress/kendo-theme-default": "^3.6.1",
    "@react-schema-form/bootstrap": "^2.1.1-alpha.0",
    "aws-amplify": "^1.2.2",
    "aws-amplify-react": "^2.5.2",
    "bootstrap": "^4.1.3",
    "can-ndjson-stream": "^1.0.0",
    "chart.js": "^2.7.3",
    "chartjs-plugin-datalabels": "^0.6.0",
    "classnames": "^2.2.6",
    "core-js": "^2.5.7",
    "enzyme": "^3.7.0",
    "enzyme-adapter-react-16": "^1.7.0",
    "firebase": "^5.10.0",
    "flag-icon-css": "^3.2.1",
    "font-awesome": "^4.7.0",
    "formik": "^1.3.1",
    "fuzzy-search": "^3.0.1",
    "has-flag": "^4.0.0",
    "history": "^4.9.0",
    "immutable": "^4.0.0-rc.12",
    "medium-editor": "^5.23.3",
    "megadraft": "^0.6.5",
    "mgr-pdf-viewer-react": "^1.0.3",
    "node-sass": "^4.10.0",
    "prop-types": "^15.6.2",
    "quill-better-table": "^1.1.13",
    "quill-image-drop-module": "^1.0.3",
    "quill-image-resize-module-react": "^3.0.0",
    "react": "^16.6.1",
    "react-ace": "^6.5.0",
    "react-app-polyfill": "^0.1.3",
    "react-bootstrap-table": "^4.3.1",
    "react-bootstrap-table-next": "^3.1.1",
    "react-bootstrap-table2-paginator": "^2.0.6",
    "react-bootstrap-table2-toolkit": "^1.4.1",
    "react-chartjs-2": "^2.7.4",
    "react-circular-progressbar": "^2.0.1",
    "react-dates": "^18.2.2",
    "react-dom": "^16.6.1",
    "react-dropdown": "^1.6.4",
    "react-dropzone": "^10.1.4",
    "react-full-screen": "^0.2.4",
    "react-grid-layout": "^0.16.6",
    "react-image-picker": "^1.1.1",
    "react-ladda": "6.0.0",
    "react-loadable": "^5.5.0",
    "react-loading": "^2.0.3",
    "react-panelgroup": "^1.0.7",
    "react-pricing-table": "^0.3.0",
    "react-quill": "1.3.2",
    "react-router": "^5.0.0",
    "react-router-config": "^4.4.0-beta.6",
    "react-router-dom": "^4.3.1",
    "react-schema-form": "^0.6.12",
    "react-select": "^1.3.0",
    "react-stripe-checkout": "^2.6.3",
    "react-stripe-elements": "^4.0.0",
    "react-sweet-progress": "^1.1.2",
    "react-table": "^6.10.0",
    "react-tagsinput": "^3.19.0",
    "react-test-renderer": "^16.6.1",
    "react-text-mask-hoc": "^0.11.0",
    "react-toastify": "^4.4.1",
    "react-treebeard": "^3.2.3",
    "react-widgets": "^4.4.11",
    "react-widgets-moment": "^4.0.27",
    "reactstrap": "^6.5.0",
    "simple-line-icons": "^2.4.1",
    "spinkit": "1.2.5",
    "yup": "^0.26.6"
  },
  "devDependencies": {
    "react-scripts": "3.0.0"
  },
  "scripts": {
    "start": "react-scripts start --max_old_space_size=4096 start",
    "build": "GENERATE_SOURCEMAP=false react-scripts build",
    "test": "react-scripts test",
    "test:debug": "react-scripts --inspect-brk test --runInBand",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 10",
    "not op_mini all"
  ]
}

**Comment by elorzafe** [comment]
@jmandivarapu1 for getting user attributes I used this:

```javascript
let { attributes } = await Auth.currentAuthenticatedUser();
```

**Comment by jmandivarapu1** [comment]
> ```js
> ```js
> let { attributes } = await Auth.currentAuthenticatedUser();
> ```
> 
> 
>       
> ```

Thank you for your reply. But,I tried that too. But it's throwing Not Authenticated error. Even though you can see clearly that I am authenticated in the before line

<img width="497" alt="Screen Shot 2019-10-17 at 11 19 53 PM" src="https://user-images.githubusercontent.com/21245519/67063406-b47a0600-f134-11e9-965d-4add4a358bd5.png">

**Comment by jmandivarapu1** [comment]
I am also surprised by the effect of these below lines in my aws_export.js on my overall application. I added these lines for transferring my users between pools. But Once I add these all my authentication and workflows are spoiled. **If I comment these lines then everything works like a magic.**

"Auth": {
        "identityPoolId": "XX",
        userPoolId:  "us-wes",
        userPoolWebClientId: "XXXX",
        region: 'us-west-2',
        "authenticationFlowType": 'USER_PASSWORD_AUTH'
    }

**Comment by elorzafe** [comment]
You have on your exports file both userpool?

**Comment by jmandivarapu1** [comment]
> You have on your exports file both userpool?

No. Only one Userpool Current one.

**Comment by elorzafe** [comment]
Can you share your aws-exports (XXXX the endpoints)?

**Comment by jmandivarapu1** [comment]
> Can you share your aws-exports (XXXX the endpoints)?

let me know if you need any variable values?
```

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_content_delivery_bucket": "XXXXXX",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "XXXXXXX",
    "aws_cognito_identity_pool_id": "XXXXX",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "XXXX",
    "aws_user_pools_web_client_id": "XXX",
    "oauth": {},
    "aws_user_files_s3_bucket": "XXX",
    "aws_user_files_s3_bucket_region": "us-west-2",

    "Auth": {
        "identityPoolId": "XXXX",(same as above)
        userPoolId:  "XXXX",(same as above)
        userPoolWebClientId: "XXXX",(same as above)
        region: 'us-west-2',
        "authenticationFlowType": 'USER_PASSWORD_AUTH'
    }
};
```

**Comment by jkeys-ecg-nmsu** [comment]
Related to #2480? (Which I think may be undocumented, I should probably submit a pull request on documenting that b/c a lot of that conversation took place over Slack with @jordanranz )

**Comment by jkeys-ecg-nmsu** [comment]
>One more thing is I can get my attribute but I used the currentuserinfo(),currentauthenticateduser() like 39 times in my project. Don't want to change those many because of indirect sideeffects.

@jmandivarapu1 maybe I overestimated how important your fire was, but you could just create a `temp/session` branch, make your changes in that branch, and publish from there until this issue is resolved.

Personally if this were happening to me in realtime I wouldn't say no to a temporary patch because it would mess up my mainline.

**Comment by elorzafe** [comment]
@jmandivarapu1 why do you need `USER_PASSWORD_AUTH` instead of `USER_SRP_AUTH`?

**Comment by jmandivarapu1** [comment]
> > One more thing is I can get my attribute but I used the currentuserinfo(),currentauthenticateduser() like 39 times in my project. Don't want to change those many because of indirect sideeffects.
> 
> @jmandivarapu1 maybe I overestimated how important your fire was, but you could just `git checkout -b temp/session` branch, make your changes in that branch, and publish from there until this issue is resolved.
> 
> Personally if this were happening to me in realtime I wouldn't say no to a temporary patch because it would mess up my mainline.

Thank you for your suggestions.

I kept one of my server up. But unfortunately it's a dependency issue if I remove the "AUTH" in 'exports.js" then I can't export the User and if I comment it then the user need to signup which I don't want in the first case. So, i basically now doing trail and error and hoping someone will throw in a solution after my **"Amplify analytics mess"**

**Comment by jmandivarapu1** [comment]
> @jmandivarapu1 why do you need `USER_PASSWORD_AUTH` instead of `USER_SRP_AUTH`?

i am glad you used. It all started with the crazy amplify.

https://github.com/aws-amplify/amplify-cli/issues/2593

**Comment by elorzafe** [comment]
@jmandivarapu1 can you try this.

```
const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_content_delivery_bucket": "XXXXXX",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "XXXXXXX",
    "oauth": {},
    "aws_user_files_s3_bucket": "XXX",
    "aws_user_files_s3_bucket_region": "us-west-2",

    "Auth": {
        "identityPoolId": "XXXX",(same as above)
        userPoolId:  "XXXX",(same as above)
        userPoolWebClientId: "XXXX",(same as above)
        region: 'us-west-2',
        "authenticationFlowType": 'USER_PASSWORD_AUTH'
    }
};
```

**Comment by jmandivarapu1** [comment]
> @jmandivarapu1 can you try this.
> 
> ```
> const awsmobile = {
>     "aws_project_region": "us-west-2",
>     "aws_content_delivery_bucket": "XXXXXX",
>     "aws_content_delivery_bucket_region": "us-west-2",
>     "aws_content_delivery_url": "XXXXXXX",
>     "oauth": {},
>     "aws_user_files_s3_bucket": "XXX",
>     "aws_user_files_s3_bucket_region": "us-west-2",
> 
>     "Auth": {
>         "identityPoolId": "XXXX",(same as above)
>         userPoolId:  "XXXX",(same as above)
>         userPoolWebClientId: "XXXX",(same as above)
>         region: 'us-west-2',
>         "authenticationFlowType": 'USER_PASSWORD_AUTH'
>     }
> };
> ```

Thankyou for the response.
Just Tried it returned the same response "not authenticated"

**Comment by jkeys-ecg-nmsu** [comment]
@elorzafe Also,

>why do you need USER_PASSWORD_AUTH instead of USER_SRP_AUTH?

Because the migration lambda requires it and once you've got a business use case where you need to migrate old users, it's tough to disable. 

This is yet another case of Amplify working around service limitations that make it hard to provide plug-n-play solutions. In the use case of user pool -> user pool migration, it should be possible to migrate with SRP auth because you don't need the password to authenticate against a legacy database.

**Comment by jmandivarapu1** [comment]
> @jmandivarapu1 can you post the log files from DevTools (right click on the failed request in the network tab and save as HAR file and upload it) or at least take screenshots of the failed request in DevTools that show the request headers/body and the response?

Yeah I can do that. But here is the thing I found out when I add 
```
    "Auth": {
        "identityPoolId": "XXXX",
        userPoolId:  "XXX",
        userPoolWebClientId: "XXX",
        region: 'us-west-2',
        "authenticationFlowType": 'USER_PASSWORD_AUTH'
    }
```

and I basically looked at the localstorage where the amplify actually log information and something happening there. After I login before I reach to get the variables and login information. amplify automatically clearing the login information in the localstorage


![error](https://user-images.githubusercontent.com/21245519/67108442-85977a80-f19c-11e9-8866-7805d814d943.gif)

**Comment by jkeys-ecg-nmsu** [comment]
How are you configuring Amplify, and where in your project are you doing it? Move it to the top of your app entry point if it's anywhere besides that. Then, can you try adding this underneath `Amplify.configure(awsmobile)`:

`Auth.configure(awsmobile)`

If that still doesn't work, can you add this in your app's entry point if you haven't already and post the [Auth] logs?

`window.LOG_LEVEL = 'DEBUG';`

**Comment by jmandivarapu1** [comment]
> @jmandivarapu1 How are you configuring Amplify, and where in your project are you doing it? Move it to the top of your app entry point if it's anywhere besides that. Then, can you try adding this underneath `Amplify.configure(awsmobile)`:
> 
> `Auth.configure(awsmobile)`
> 
> If that still doesn't work, can you add this in your app's entry point if you haven't already and post the [Auth] logs?
> 
> `window.LOG_LEVEL = 'DEBUG';`

Thank you for u r reply. I tried it It didn't work. Here is my 


<img width="521" alt="Screen Shot 2019-10-18 at 4 12 30 PM" src="https://user-images.githubusercontent.com/21245519/67125183-349a7d00-f1c2-11e9-978a-792496f28b4a.png">
<img width="535" alt="Screen Shot 2019-10-18 at 4 12 43 PM" src="https://user-images.githubusercontent.com/21245519/67125194-3b28f480-f1c2-11e9-93e5-6675e5acf365.png">

**Comment by jkeys-ecg-nmsu** [comment]
That `Invalid Refresh Token` error message is a bit eyebrow raising. 

Can you try temporarily replacing your login flow with the Amplify login flow provided by `withAuthenticator` in `aws-amplify-react` and see if that fixes it?

**Comment by jmandivarapu1** [comment]
> @jmandivarapu1 That `Invalid Refresh Token` error message is a bit eyebrow raising.
> 
> Can you try temporarily replacing your login flow with the Amplify login flow provided by `withAuthenticator` in `aws-amplify-react` and see if that fixes it?

Do you mean removing below from aws_exports.js. If I remove it then it works but then the user's wont be migrate from my old pool to the new one.
```
 "Auth": {
        "identityPoolId": "XXXX",
        userPoolId:  "XXX",
        userPoolWebClientId: "XXX",
        region: 'us-west-2',
        "authenticationFlowType": 'USER_PASSWORD_AUTH'
    }```

**Comment by jkeys-ecg-nmsu** [comment]
No, I'm saying can you try replacing your login screen with the login screen provided by `aws-amplify` and `aws-amplify-react` HOC to see if the problem could be in how you've implemented your login page.

https://aws-amplify.github.io/docs/js/authentication#using-withauthenticator-hoc

**Comment by jmandivarapu1** [comment]
> No, I'm saying can you try replacing your login screen with the login screen provided by `aws-amplify` and `aws-amplify-react` HOC to see if the problem could be in how you've implemented your login page.
> 
> https://aws-amplify.github.io/docs/js/authentication#using-withauthenticator-hoc

I am not open to changing my signin screen at this point. Because I already messed a lot of code for this.
My SIgnin is working well from 1 year. Only thing is that my  I added auth according to what mentioned in the aws documents. So, I am thinking it's the aws bug in handling the ``` authenticationFlowType: 'USER_PASSWORD_AUTH'```

**Comment by jkeys-ecg-nmsu** [comment]
Okay, I understand. I wasn't asking you to permanently change your login screen, I was asking you to conduct an experiment.

It's hard to be helpful when you won't accept a temporary patch, won't try to debug it by comparing your login flow against the provided flow, haven't provided any sample source code, etc. 

I'll leave it to the Amplify team to fix the issue. Good luck, I hope you find a way to remediate your site into a new stack and get this issue sorted.

**Comment by jmandivarapu1** [comment]
> Okay, I understand. I wasn't asking you to permanently change your login screen, I was asking you to conduct an experiment.
> 
> It's hard to be helpful when you won't accept a temporary patch, won't try to debug it by comparing your login flow against the provided flow, haven't provided any sample source code, etc.
> 
> I'll leave it to the Amplify team to fix the issue. Good luck, I hope you find a way to remediate your site into a new stack and get this issue sorted.

Thank you for your reply. But I did everything from my  creating new pools,resources, environment ,contact aws support..etc and spent lot of time on this. But changing the source is something I don't want to do at this point. Because if i comment the 'Auth' it's work which means the aws flow is working according to me.

**Comment by jmandivarapu1** [comment]
any aws team can help me on this?

**Comment by jkeys-ecg-nmsu** [comment]
@jmandivarapu1 have you tried downgrading your `aws-amplify` package to the oldest version containing your dependencies to see if the problem still persists?

Also, please answer these two questions: (1) what is the name of the file that is the entry point of your program (as defined by webpack or whatever), and (2) what is the name of the file that you run `Amplify.configure` or `Auth.configure`?

It seems like you're hesitant to experiment, but if you've got a backup of your site working but your development is down, you should just be trying stuff at this point and be proactive.

**Comment by jmandivarapu1** [comment]
> you're hesitant to experimen



> @jmandivarapu1 have you tried downgrading your `aws-amplify` package to the oldest version containing your dependencies to see if the problem still persists?
> 
> Also, please answer these two questions: (1) what is the name of the file that is the entry point of your program (as defined by webpack or whatever), and (2) what is the name of the file that you run `Amplify.configure` or `Auth.configure`?
> 
> It seems like you're hesitant to experiment, but if you've got a backup of your site working but your development is down, you should just be trying stuff at this point and be proactive.

Both my start of the application and all the configuration is in my APP.js which is my start of the application.

I did downgraded the amplify but that doesn't seem to work too.

I did as much experiment's as possible because of this amplify analytics issues which messed my project. If I started doing more experimentation than this it will be like me building whole application again. [There is a team of 10 people who are not willing too.]

We didn't got any backup when this issue occurred. But we made a temporary fix by writing lot of function's to change user's from one pool to other and making them verified by default. 

But we are looking for what might be the actual issue. 

Our Team Opinion: 
After this long debug and support process of AWS Amplify. We as a team beginning to think is it really worth to try these buggy AWS amplify for all these things (except hosting) instead of using my own database for login and one s3 bucket for storage.

As most of the time amplify team either replies very late or never bother's and leaves the issues. Then they close the issue saying it's not active and never bother whether it fixed or not. It happened with us for the amplify storage functions.

**Comment by jkeys-ecg-nmsu** [comment]
@elorzafe can you address OP's concerns?

**Comment by mlabieniec** [comment]
@jmandivarapu1 have you run any updates via the CLI or cloudformation directly on your user pool? Can you verify in your user pool console - > app clients - > show details -> Enable username-password (non-SRP) flow for app-based authentication (USER_PASSWORD_AUTH) is enabled?

**Comment by jmandivarapu1** [comment]
> @jmandivarapu1 have you run any updates via the CLI or cloudformation directly on your user pool? Can you verify in your user pool console - > app clients - > show details -> Enable username-password (non-SRP) flow for app-based authentication (USER_PASSWORD_AUTH) is enabled?

Yes It's enables I double checked it.

**Comment by DavitVosk** [comment]
Any update?

**Comment by jmandivarapu1** [comment]
> Any update?
Nothing Much happened. As expected nobody from amplify team responded whether it's a bug or not.

But that's not the end of the world.  Some of the team member's came up with some nice solution. (It's temporary)

**Comment by kevin-renier** [comment]
> > Any update?
> > Nothing Much happened. As expected nobody from amplify team responded whether it's a bug or not.
> 
> But that's not the end of the world. Some of the team member's came up with some nice solution. (It's temporary)

Hello @jmandivarapu1 , we are having the same issue (cannot retrieve user/token after successfully sign in, using USER_PASSWORD_AUTH), could you please share you solution ?

**Comment by jmandivarapu1** [comment]
> > > Any update?
> > > Nothing Much happened. As expected nobody from amplify team responded whether it's a bug or not.
> > 
> > 
> > But that's not the end of the world. Some of the team member's came up with some nice solution. (It's temporary)
> 
> Hello @jmandivarapu1 , we are having the same issue (cannot retrieve user/token after successfully sign in, using USER_PASSWORD_AUTH), could you please share you solution ?

 I think it's a bug in AWS amplify. But the way we dealt with is that we decided that we can't do anything in the front end. So I created a lambda function to handle that when he login it checks if their user is there in a pool or not. If not the user gets copied from the old pool to the current one and login goes as regularly. I know it's not a perfect solution but I didn't find any other possible solution.

**Comment by kevin-renier** [comment]
@jmandivarapu1 thanks for the answer, we though about the same workaround. 
But we just found the `DeviceOnlyRememberedOnUserPrompt` property in the user pool : https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_DeviceConfigurationType.html 
It was set to `true`, setting it to `false` makes it work again. Don't know if that can help in you case.

**Comment by paulsocal** [comment]
> @jmandivarapu1 thanks for the answer, we though about the same workaround.
> But we just found the `DeviceOnlyRememberedOnUserPrompt` property in the user pool : https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_DeviceConfigurationType.html
> It was set to `true`, setting it to `false` makes it work again. Don't know if that can help in you case.

@kevin-renier Where is that setting? I'm unable to find it in the console. How do you update it?

**Comment by quorth0n** [comment]
Also experiencing this issue on Amplify web.

**Comment by ajitgoel** [comment]
I am also facing the same issue on Amplify web. Would the amplify team have an update for this issue?

**Comment by katrinacrisostomo** [comment]
Was experiencing the same issue and found that bumping my `history` package from `v4.9.0` to `v5.0.0` fixed the issue. I don't quite understand why though. (I am on `aws-amplify` version `3.0.17`)

**Comment by jvsteiner** [comment]
#6555

**Comment by amhinson** [comment]
@jmandivarapu1 Are you still experiencing this issue? I've tried to reproduce it by doing the following: 
- create new React app with `create-react-app`
- `amplify init`
- `amplify add auth` & `amplify push`
- wrap `App` with `withAuthenticator` from `@aws-amplify/ui-react`
- add `authenticationFlowType: 'USER_PASSWORD_AUTH'` to Amplify config
- enable username/password authentication in Cognito for app client (web)
![image](https://user-images.githubusercontent.com/17091790/96934061-6d74ce00-1476-11eb-8f4d-1018f3a3d2d6.png)
- create new user & login
- run `Auth.currentUserInfo().then(user => console.log(user))` inside `App` component

With that I am correctly seeing my authenticated user's information.

It seems like I am following the same steps as you are. Do you see anything missing?
