### ISSUE TITLE
How to deal with application logs with AWS Amplify?

### ISSUE THREAD

**Issue by rpostulart** [aws-amplify/amplify-js#4198]
Is there a way to stream (client side) application logs (errors) to Cloudwatch so you can analyse your app behaviour for improvements of your app?

**Comment by blairtaylor** [comment]
Similar question was posted here https://github.com/aws-amplify/amplify-js/issues/3524

We all seem to be looking for a CloudWatch appender for the Amplify logger.

**Comment by elorzafe** [comment]
@rpostulart @blairtaylor thanks for the feedback. I will close the issue as mention is duplicated from #3524 feel free to +1 to that issue.

Thanks!
