### ISSUE TITLE
Typescript Compiler errors from @aws-amplify/auth

### ISSUE THREAD

**Issue by Jeff-Duke** [aws-amplify/amplify-js#4200]
**Describe the bug**
After adding `@aws-amplify/auth` to a project, and using `federatedSignIn` I'm getting multiple errors from Typescript stating:
```
Cannot use namespace 'ICredentials' as a type.
```
These errors are coming from
`node_modules/@aws-amplify/auth/lib/Auth.d.ts`

**To Reproduce**
Install `@aws-amplify/auth` and add it to a typescript project.

**Expected behavior**
We should not get any TS compiler warnings about `.../node_modules/@aws-amplify/auth`

**Screenshots**
![Screen Shot 2019-10-17 at 10 26 44 AM](https://user-images.githubusercontent.com/17116730/67018196-e2296580-f0c8-11e9-8db3-32889e3bbac1.png)
![Screen Shot 2019-10-17 at 10 26 54 AM](https://user-images.githubusercontent.com/17116730/67018213-e5bcec80-f0c8-11e9-9726-f68f9837f0ba.png)
![Screen Shot 2019-10-17 at 10 27 02 AM](https://user-images.githubusercontent.com/17116730/67018249-f40b0880-f0c8-11e9-8a91-a4295df22918.png)
![Screen Shot 2019-10-17 at 10 27 15 AM](https://user-images.githubusercontent.com/17116730/67018282-01c08e00-f0c9-11e9-990b-da926c4da379.png)

**Amplify context**
- Framework: Vue
- Versions of Amplify you are using: `@aws-amplify/auth: 1.3.3`

**Comment by Amplifiyer** [comment]
@Jeff-Duke, can you check if you are not adding a declare line anywhere for ICredentials as per https://github.com/Microsoft/TypeScript/issues/27311#issuecomment-484160104?
If that doesn't help, can you try cleaning your project and building fresh?

**Comment by Jeff-Duke** [comment]
I was able to re-create this in a separate project. 
The steps I took were:
created a fresh install of a Vue app with Typescript support 
added `@aws-amplify/core` and `@aws-amplify/auth`
added a shims file declaring
```
declare module '@aws-amplify/core';
declare module '@aws-amplify/api';
```

**Comment by Amplifiyer** [comment]
@Jeff-Duke, any reasons you are not using ES6 style imports (for instance `import API from '@aws-amplify/api'`) but using declare module?

**Comment by Jeff-Duke** [comment]
my mistake, I was adding a shim for this where I didn't need to. I removed the module declaration in the shims file and the errors have gone away.
