### ISSUE TITLE
Amplify hosted React app throws generic "Network Error" for everything

### ISSUE THREAD

**Issue by potatopotaro** [aws-amplify/amplify-js#4208]
**Describe the bug**
My "hosted" website (using hosting category) always throws the following error for virtually every `aws-amplify` submodule/method I use:

`{code: "NetworkError", name: "Error", message: "Network error"}`

In particular, I want to use the Auth module's `signUp` method (I don't want to use any of the pre-made Auth UI), however this error appears to also apply in the API category and probably more.

**To Reproduce**

1. Create a generic React app using `create-react-app` (e.g. `yarn create react-app <name>`)
2. Add the minimum input fields and one button for calling `Auth.signUp`
3. `amplify add auth` and set up a minimum configuration (i did manual + email signin + custom lambda trigger for pre-signup, but I don't think it matters for repro)
4. run app locally and ensure it works (it should)
5. `amplify add hosting` and select the dev option
6. visit the hosted link and witness the following error:

<img width="540" alt="Screen Shot 2019-10-18 at 9 40 14 AM" src="https://user-images.githubusercontent.com/16728256/67103736-5298bb00-f18b-11e9-8701-b658bda5bc01.png">

<img width="878" alt="Screen Shot 2019-10-18 at 9 41 11 AM" src="https://user-images.githubusercontent.com/16728256/67103802-73f9a700-f18b-11e9-8528-6d26a310144e.png">

<img width="996" alt="Screen Shot 2019-10-18 at 9 40 55 AM" src="https://user-images.githubusercontent.com/16728256/67103814-7a881e80-f18b-11e9-8264-6400c72b770e.png">

<img width="998" alt="Screen Shot 2019-10-18 at 9 41 05 AM" src="https://user-images.githubusercontent.com/16728256/67103824-7eb43c00-f18b-11e9-8b7e-4c64058222a5.png">

**Expected behavior**
I expect the hosted app to successfully work, as it does locally.

**Desktop (please complete the following information):**

- OS: OS X
- Browser: Chrome
- Version: Version 77.0.3865.120 (Official Build) (64-bit)

**Amplify context**
- Framework: React@16.10.2
- Versions of Amplify you are using: aws-amplify@1.2.2, @aws-amplify/cli@3.15.0

**Additional context**
I'm trying to build a landing page with a 2-field form to register for a waitlist. Ideally, I want to use Next.js's pre-rendered/static-export feature.

However, this error applies to both SSR apps and pure client-side React apps. I've tested in both.

**Sample code**
[Example hosted react app](http://testingmplify-20191018092240-hostingbucket-dev.s3-website.us-east-2.amazonaws.com)

Signup fields in the above app are:
1. Name
2. Email

**Comment by Amplifiyer** [comment]
@potatopotaro I just tried to use your hosted react app and I was able to signup properly and get the response back with confirmed user.
Can you test again and let us know if you are still facing the issue?

**Comment by potatopotaro** [comment]
Yep, it looks like one of my chrome extensions is causing this. Feel like an idiot now haha thanks for the help though, cheers.

**Comment by ashleyoldershaw** [comment]
> Yep, it looks like one of my chrome extensions is causing this. Feel like an idiot now haha thanks for the help though, cheers.

Hi @potatopotaro! Do you remember which extension was causing this issue? I realise it was a while ago now :')
