### ISSUE TITLE
Consecutive logins with different social providers fail

### ISSUE THREAD

**Issue by warrify** [aws-amplify/amplify-js#4210]
**Describe the bug**
I set up google and facebook social providers and was able to log in with both of them, even multiple times. But once I logged in one of them the other won't work.

**To Reproduce**

1. Sign in with Facebook using `withOAuth` and `facebookSignIn`
2. Sign out with `Auth.signOut`
3. Try to sign in with Google using `withOAuth` and `googleSignIn`
4. See error: 
```
message: "Logins don't match. Please include at least one valid login for this identity or identity pool."
__type: "NotAuthorizedException"
```

**Expected behaviour**
After logging in with Facebook and logging out again a login with any social provider should work.

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy S6 edge 
- OS: Android
- Version: 9

**Amplify context**
- Framework: React Native 0.61.2
- Amplify versions: aws-amplify-react-native: 2.2.2

**Additional context**
I fixed it by clearing the federated-info-cache: 
```javascript
AuthStorage.removeItem('aws-amplify-federatedInfo');
```
where AuthStorage is the Storage I pass into the config as `storage`

**Comment by Amplifiyer** [comment]
@Matthias-Pichler, I couldn't reproducing it with facebook and google OAuth providers and a custom storage. Can you paste the output of the following command in your app here `yarn list | grep amplify` (switch to npm if applicable)

**Comment by Matthias-Pichler** [comment]
@Amplifiyer 
```bash
→ npm list | grep amplify                                                                                                                                                                                  [8578c6b]
├─┬ @aws-amplify/analytics@1.3.2
│ ├─┬ @aws-amplify/cache@1.1.2
│ │ └── @aws-amplify/core@1.2.2 deduped
│ ├── @aws-amplify/core@1.2.2 deduped
├─┬ @aws-amplify/auth@1.4.2
│ ├── @aws-amplify/cache@1.1.2 deduped
│ ├── @aws-amplify/core@1.2.2 deduped
├─┬ @aws-amplify/core@1.2.2
├─┬ @aws-amplify/pushnotification@1.1.2
│ └── @aws-amplify/core@1.2.2 deduped
├─┬ @aws-amplify/storage@1.2.2
│ └── @aws-amplify/core@1.2.2 deduped
├─┬ aws-amplify@1.2.2
│ ├── @aws-amplify/analytics@1.3.2 deduped
│ ├─┬ @aws-amplify/api@1.2.2
│ │ ├── @aws-amplify/auth@1.4.2 deduped
│ │ ├── @aws-amplify/cache@1.1.2 deduped
│ │ ├── @aws-amplify/core@1.2.2 deduped
│ ├── @aws-amplify/auth@1.4.2 deduped
│ ├── @aws-amplify/cache@1.1.2 deduped
│ ├── @aws-amplify/core@1.2.2 deduped
│ ├─┬ @aws-amplify/interactions@1.1.2
│ │ └── @aws-amplify/core@1.2.2 deduped
│ ├─┬ @aws-amplify/predictions@1.1.2
│ │ ├── @aws-amplify/core@1.2.2 deduped
│ │ ├── @aws-amplify/storage@1.2.2 deduped
│ ├─┬ @aws-amplify/pubsub@1.2.2
│ │ ├── @aws-amplify/core@1.2.2 deduped
│ ├── @aws-amplify/storage@1.2.2 deduped
│ ├── @aws-amplify/ui@1.1.2
│ └─┬ @aws-amplify/xr@0.2.2
│   └── @aws-amplify/core@1.2.2 deduped
├─┬ aws-amplify-react@2.5.2
├─┬ aws-amplify-react-native@2.2.2
```

**Comment by Matthias-Pichler** [comment]
@Amplifiyer its basically just a reimplementation of the amplify react native memory storage just using the new `@react-native-community/async-storage`

```javascript
import MemoryStorage from '@util/storage';
import Config from 'react-native-config';

export const AuthStorage = new MemoryStorage();

export default {
  identityPoolId: Config.COGNITO_IDENTITY_POOL_ID,
  region: Config.COGNITO_REGION,
  mandatorySignIn: false,
  userPoolId: Config.COGNITO_USER_POOL_ID,
  userPoolWebClientId: Config.COGNITO_USER_POOL_WEB_ID,
  authenticationFlowType: Config.COGNITO_USER_POOL_AUTH_FLOW,
  oauth: {
    domain: Config.COGNITO_DOMAIN, //Domain from cognito user pool
    scope: [
      'profile',
      'email',
      'phone',
      'openid',
      'aws.cognito.signin.user.admin'
    ],
    redirectSignIn: '****',
    redirectSignOut: '***',
    // 'code' for Authorization code grant,
    // 'token' for Implicit grant
    // Note that REFRESH token will only be generated when the responseType is code
    responseType: 'code'
  },
  storage: AuthStorage
};

```

**Comment by mynameisguy** [comment]
Having the exact same issue with google and apple logins.
After I log in to one of the options and then logout, on the first time I try to login to the second option I see the same error:
`{ event: 'signIn_failure',
  data: [NotAuthorizedException: Logins don't match. Please include at least one valid login for this identity or identity pool.] }`
For me, clearing the AuthStorage (used it as the storage for Auth and verified I actually cleared it) didn't help.

**Comment by mauerbac** [comment]
HI @warrify - it looks like this issue has been fixed. It has been verified. If you experience an issue related to this please open a new issue. Thank you
