### ISSUE TITLE
Amplify developer authentication identity provider refresh handler fails silently

### ISSUE THREAD

**Issue by streppa** [aws-amplify/amplify-js#4213]
** Which Category is your question related to? **
Amplify, React Single Page App

** What AWS Services are you utilizing? **
Cognito, Appsync

We're trying to refresh the session on page reload.

In the cognito federated identity pool  both the `unauthorized` and `authorized` roles have complete access to the AppSync API (while we're developing). 

The identity pool has the custom authentication provider configured.

It's a Single Page App but we're using two graphql mutations for login and refresh. The developer authentication provider is the legacy API that backs the AppSync GraphQL API. 

In the `login` mutator a `username` and `password` are checked against the legacy api and it generates a token which is saved to a DynamoDB table with the cognitoIdentityId. Then it authenticates the cognito session with `getOpenIdTokenForDeveloperIdentity` and sends that back to the app.

This process works fine.

When the page loads `Auth.currentCredentials()` is run. After authenticating if we reload the page `Auth.currentCredentials()` attempts to refresh the developer authentication. With `window.LOG_LEVEL = 'DEBUG'` set I can see the cached federated info before it does so. It looks correct.

I thought when we first implemented this solution that the refresh handler received data, but I can't verify this and the examples in the documentation seem to indicate that nothing is passed and we do in fact get nothing.

When the refresh handler is called it's written to call the graphql `refresh` mutation. The mutation does nothing. No exceptions, no warnings. Attaching `.then`, `.catch`, or `.finally` to the `API.graphql` promise do nothing. I can't seem to get any feedback as to what did or didn't happen. A walk through the call stack doesn't reveal anything interesting as far as I can tell.

In the developer console in the browser the client never even makes an attempt to run the request. No outbound requests get made.

I'm stuck.

    Amplify.configure({
      ...aws_mobile,
      Auth: {
        identityPoolId: "us-east-2:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        region: "us-east-2",
        mandatorySignIn: false,
        refreshHandlers: {
          'developer': Session.refresh
        }
      }
    })

   
    class Session {
        static async refresh() {
            let federatedInfo = Cache.getItem('federatedInfo')

            const params = {
                identityId: federatedInfo['identity_id'],
                token: federatedInfo['token'],
                email: federatedInfo['user']['email']
            }

            let data = await API.graphql(graphqlOperation(mutations.refresh, {input: params}))
            return new Promise((resolve, reject) => {
                if (data) {
                resolve(data)
                } else {
                reject(new Error('mutations.refresh failed, [no error]'))
                }
            })
        }
    }

I have no way to verify this since I can't get any feedback from the browser but it's like while I'm in this limbo when refreshing AppSync loses the credentials. But then doesn't error out? I'm totally confused.

Let me know if you need more information.

**Comment by streppa** [comment]
I should mention that I've run the graphql mutation outside the refresh handler and it works fine.

**Comment by streppa** [comment]
I've come up with a work around for now.

The API Amplify module definitely doesn't have credentials when the refresh handler is running.

**Comment by whatsthebeef** [comment]
@streppa what's the work around?

I was having to set refresh handlers with functions that pull the id and token from localstore but it still only lasts one hour

```
function hackTokenInsteadOfRefresh() {
  const storage = JSON.parse(window.localStorage['aws-amplify-federatedInfo']);
  // Code to retrieve your data
  return new Promise((resolve, reject) => {
    return resolve({
      token: storage.token,
      identity_id: storage.identity_id,
      expires_at: 0
    });
  });
}

Amplify.configure({
  Auth: {
    refreshHandlers: {
      'developer' : hackTokenInsteadOfRefresh,
      'accounts.google.com': hackTokenInsteadOfRefresh,
    },
```

**Comment by streppa** [comment]
@whatsthebeef 

It's kinda ugly.

Essentially I preempt `Auth.currentCredentials()`. For both initial page load (this is an SPA, sorta) and refresh I call my own `Session.init()` / `Session.refresh()` which return a promise. Once the promise resolves it calls `Auth.currentCredentials()` which in turn calls a very simple refresh handler. 
\
In the top-most component with access to the App context I have some use hooks.
```javascript
const MyTopComponent = () => {
  const [App, appDispatch] = useContext(AppContext)

  useInterval(() => {
    Session.refresh(App.session).then(session => {
      Auth.currentCredentials().then(credentials => {
        appDispatch({ type: 'authenticated', payload: credentials.authenticated })
        appDispatch({ type: 'session', payload: session })
      })
    })
  }, 3600000)

  useEffect(() => {

    Session.init().then(session => {

      Auth.currentCredentials()
          .then((credentials) => {
            appDispatch({ type: 'authenticated', payload: credentials.authenticated })
          })
          .finally(() => {
            appDispatch({ type: 'ready', payload: true })
            appDispatch({ type: 'session', payload: session })
          })

    })
  }, [appDispatch])

  useEffect(() => {
    const authHubHandler = Session.authHubHandler(appDispatch)
    Hub.listen('auth', authHubHandler)
    return () => Hub.remove('auth', authHubHandler)
  }, [appDispatch])

  ...
}
```
\
So by the time `Auth.currentCredentials()` does it's thing we've already handled the init/refresh with our authorization provider.
```javascript
  // All this is because I can't run graphql requests with authentication in the refresh handler
  // https://github.com/aws-amplify/amplify-js/issues/4213
  static async refresh(session) {
    return Session.init(session)
  }

  static async init(currentSession = undefined) {
    const session = currentSession || Cache.getItem('session') || undefined

    return new Promise((resolve, reject) => {

      if ( !session ) {
        logger.debug('no existing session')
        return resolve(new Session())
      }

      if ( parseInt(session.expiresAt) < new Date().getTime() ) {
        logger.debug('identity is expired')
        this.myAuthenticationProviderCall(session)
            .then(({data: refreshResponse}) => {
              const session = new Session(refreshResponse.refresh)
              resolve(session)
            })
            .catch(error => reject(error))
      } else {
        logger.debug('identity is acceptable')
        resolve(new Session(session))
      }

    })
  }
```
\
In the constructor to my `Session` I configure the refresh handler.
```javascript
  constructor ({ email, expiresAt, identityId, token } = {}) {
    ...
    Amplify.configure({ Auth: { refreshHandlers: { 'developer': Session.cognitoRefresh(this) }}})
  }
```
\
`Session.cognitoRefresh()` just passes the current values for `identityId` and `token`. 
```javascript
  static cognitoRefresh(session) {
    return () => {
      const params = {
        identityId: session.identityId,
        token: session.token,
      }
      return Promise.resolve(params)
    }
  }
```
\
So far this works pretty well. What I'm working on is a prototype though and not a production system. Yet.

**Comment by streppa** [comment]
@whatsthebeef 

The token from cache is still just the token that was given on the initial authentication. If it's expired then giving it back won't help. At some point `cognitoIdentity.getOpenIdTokenForDeveloperIdentity()` has to get called so you can get a new token.

In my case I call it in a lambda that is the resolver for the init and refresh mutations. I don't go through a refresh process either, I just get a new token.

**Comment by omkarv-amazon** [comment]
Using @aws-amplify/auth ^1.4.2, @aws-amplify/core ^1.2.2, in package.json.

I'm also seeing a silent failure while using the `Auth.currentCredentials()` API which I suspect is related to the refresh handler failing silently.  See below for the context in which I was using the API

```javascript
const credentials = await Auth.currentCredentials();
const { IdentityId, Logins } = credentials.params;
const { Token = '' } = await cognitoIdentity
    .getOpenIdToken({
      IdentityId,
      Logins
    })
    .promise();
```

For the most part the Call to Get OpenID Token would succeed, however there were situations were this API call failed. 

Digging into the issue I noticed that the `Auth.currentCredentials()` method occasionally returns a `Logins` object that contains a references an outdated ID token (recall that the `Logins` object is a structure which contains a mapping between the cognitoUserPoolUrl : theSessionIDToken), which causes the subsequent ID Token call to fail.

Given that `Auth.currentCredentials` is an async API I would always expect this to return valid credentials.

My workaround for anyone interested is as follows:

```javascript
const session = await Auth.currentSession();
const Logins = {
   [config.env.cognito.userPoolUrl]: session.getIdToken().getJwtToken()
};
const {
   params: { IdentityId }
 } = await Auth.currentCredentials();
const { Token = '' } = await cognitoIdentity
    .getOpenIdToken({
      IdentityId,
      Logins
    })
    .promise();
```

**Comment by sammartinez** [comment]
@streppa Are you still experiencing this issue on the latest versions of Amplify? Please let us know.

**Comment by MetodiYanev** [comment]
Yes, this still happens with the latest version of amplify (3.0.10). We were using a public http endpoint in our token refresh handler, but when we switched to using an AppSync operation, it just fails to refresh silently, no errors, nothing, and every other Auth.* call goes into nothing.
