### ISSUE TITLE
Amplify GraphQL client or  AWS AppSync SDK

### ISSUE THREAD

**Issue by anarerdene** [aws-amplify/amplify-js#4221]
Im new on AWS Amplify. 
I have to choose Amplify GraphQL client or AWS AppSync SDK. I want to know biggest difference.
Now im using "AWS AppSync SDK" with "Apollo" on NextJS.  But it's hard for me "Because NextJs & Apollo has changed every month".

**Comment by Amplifiyer** [comment]
@anarerdene, if you need offline capabilities then your only option is to use AppSync SDK but if you are not, you can use Amplify GraphQL client as well which might be slightly simpler to use as well.

Amplify does not yet officially support SSR, however if your only use case is to use graphql with authentication, you should be able to use it without any issues.
