### ISSUE TITLE
ServiceWorker enablePush is not a function

### ISSUE THREAD

**Issue by Pijuli** [aws-amplify/amplify-js#4222]
Totally noob on SW here!
I'm trying, [as the docs says](https://aws-amplify.github.io/docs/js/service-workers), to register a service worker and enable push notifications to use it with the PinPoint service.
My setup is nuxt with aws-amplify installed (also tried aws-amplify/core as I read somewhere that there's no need to install the full library)
Library version is 1.2.2

Code is as simple as follows:
```
const serviceWorker = new ServiceWorker()
const registeredServiceWorker = await serviceWorker.register('mySW.js', '/')
registeredServiceWorker.enablePush('PinpointID')
```

and it's executed after the login happens.

Error I get:
```
index.js:174 Uncaught (in promise) TypeError: registeredServiceWorker.enablePush is not a function
    at VueComponent._callee$ (index.js:174)
    at tryCatch (commons.app.js:7744)
    at Generator.invoke [as _invoke] (commons.app.js:7970)
    at Generator.prototype.<computed> [as next] (commons.app.js:7796)
    at asyncGeneratorStep (commons.app.js:73)
    at _next (commons.app.js:95)
```

I'm absolutely stuck. Any ideas?
Thank you!

**Comment by Amplifiyer** [comment]
@Pijuli, it looks like a bug in our documentation, `enablePush` should be called on `serviceWorker` and not on the registered object. can you try the following code and let me know if it works for you

```
const serviceWorker = new ServiceWorker()
const registeredServiceWorker = await serviceWorker.register('mySW.js', '/')
serviceWorker.enablePush('PinpointID')
```

**Comment by Pijuli** [comment]
Hi Amp,
Just found it digging on the source code finally. Thank you anyway. I'll try to make a PR to fix that.
Also, enablePush requires a public_key but if you use the react native it uses the appId from pinpoint (my guess). So I don't see how it matches with pinpoint. I can not see where to get that public key. So I can't see how to send push notifications to my pwa with nuxt.
Any light would be appreciated. I feel like falling in a rabbit hole...

**Comment by Amplifiyer** [comment]
@Pijuli, I'm not sure I completely understand your question. You need a applicationServerKey as mentioned here in this [article](https://developers.google.com/web/fundamentals/codelabs/push-notifications#subscribe_the_user) to send push notifications from a server (public key is assigned to applicationServerKey in the library)

Analytics(pinpoint) doesn't use this public_key. It just sends/records an analytic event whenever the service worker state is changed.
