### ISSUE TITLE
amplify-signin-with-hostedUI is loosing value when you navigate to other components in React JS

### ISSUE THREAD

**Issue by webuser17** [aws-amplify/amplify-js#4225]
**Describe the bug**
As soon as logged in, amplify-signin-with-hostedUI is going to be true, when you navigate to other components, this key is getting removed from the localstorage, hence Auth.logout() is not working.

**To Reproduce**
create multiple Single Page applications using ReactJS. And and see if you navigate from one app to other app, from the local storage variable amplify-signin-with-hostedUI is getting remove.

refer the ticket AWS case 6508461831 for more information.

**Comment by Amplifiyer** [comment]
@webuser17, are you expecting different apps to share the local storage? Local storage is not shared among different apps.

**Comment by webuser17** [comment]
localhost:3000/Home, localhost:3000/mainpage, localhost:3000/LandingPage, all three pages are considered as 3 singe page applications in One big application, with cognito i did setup for localhost:3000/home as my home page, but all other routes are as part of one React application. Localstorage is being shared upon authentication and key/values coming from AUTH api for all the pages mentioned above, but accept this key - amplify-signin-with-hostedUI

**Comment by Amplifiyer** [comment]
@webuser17, the purpose of the key `amplify-signin-with-hostedUI` is really to identify if user has arrived on the home page from the hosted UI or from a different page and appropriately check the user state. It is supposed to be cleared as soon as user navigate away from the home page (where user landed after signing in from hosted UI).

Can you let us know what issue you are encountering during signOut? Looking at the code, signout does not depend on this key `amplify-signin-with-hostedUI`

**Comment by webuser17** [comment]
The Key amplify-signin-with-hostedUI key has dependency with Auth.signout() method, on localhost:3000/Homepage - Auth.logout works perfectly, as soon as we navigate to different component like localhost:3000/landingpage, Auth.logout() is not working, it is because the key - amplify-signin-with-hostedUI is getting removed from the local storage.

My Auth.logout function is being called from the Header.js file.

**Comment by Amplifiyer** [comment]
@webuser17, can you share with me your code sample so I can reproduce it (especially how and where you are calling `Auth.signout()` and `Auth.signIn()`)

I think I have some understanding of what's happening. During signout, the library always clear out the localStorage but if the key `amplify-signin-with-hostedUI` is not present, it doesn't logout from the hostedUI.
