### ISSUE TITLE
Analytics autoTracker stopSession error in React Native 

### ISSUE THREAD

**Issue by Sytree** [aws-amplify/amplify-js#4232]
**Describe the bug**
I got this error when close the app
`navigator.sendBeacon is not a function. (In 'navigator.sendBeacon(y,l)', 'navigator.sendBeacon' is undefined)`
it happened when call @aws-amplify/analytics/lib/Providers/AWSPinpointProvider._pinpointSendStopSession
it seems react-native environment doesn't support `navigator.sendBeacon(y,l)`

**To Reproduce**
1.setup analytics
2.turn on auto track
3.run the app and then close it

- OS:Android & IOS
- ReactNative 0.59.10

**Amplify context**
- React Native
- "@aws-amplify/analytics": "^1.2.25"

**Comment by iartemiev** [comment]
@Sytree this should be fixed now in the latest unstable version (install `@aws-amplify/analytics@unstable` through your package manager if you'd like to try it before it's officially released).

Please let us know if this fixes the bug you are experiencing.
