### ISSUE TITLE
AMQJS0008I socket closed error on subscription 

### ISSUE THREAD

**Issue by malaci** [aws-amplify/amplify-js#4233]
Hi,

We're using Ionic Framework 4 ( Angular 7 ) with amplify-js 1.1.28 & aws-appsync 2.0.1
Some times we get 'socket closed' error from our subscriptions.
The issues occurs for both browser and mobile (Android & iOS) builds.

1. Subscribe to mutation 
2. After a while the socket is closed with AMQJS0008I error 

The code :
```javascript
export const listNotifications = gql`query getCaregiver(
    $id: Int!
) {
    caregiver(id: $id) {
        ....
        }
    }
}
`;

private readonly networkOnly: string = 'network-only';

   public listPastNotifications() {
        const res = this.client.query({ query: listNotifications , variables: {id: this.id}, fetchPolicy: this.networkOnly});
        return from(res);
    }


private preloadNotifications() {
        this.listPastNotifications().subscribe((res: any) => {
            if (res && res.data && res.data.caregiver && res.data.caregiver.notifications) {
                const items: NotificationMeta[] = (res.data.caregiver.notifications as NotificationMeta[]) || [];
                this.storeService.setPastNotifications(items);
                
            }
        });
    }
```

![subscriptionsFailureExtand (1)](https://user-images.githubusercontent.com/3204125/67264391-a10fc780-f4b3-11e9-942c-91ce49291e0a.PNG)

**Comment by Amplifiyer** [comment]
@malaci, can you try with the newer major versions of aws-amplify@2.x and aws-appsync@3.x and see if that resolves your issue? We have changed the subscription provider from IoT to AppSyncRealTimeSubscription provider.
