### ISSUE TITLE
Help Understanding Billing for Cognito

### ISSUE THREAD

**Issue by cliffordh** [aws-amplify/amplify-js#4234]
** Which Category is your question related to? **
Cognito
** What AWS Services are you utilizing? **
Cognito, Social Sign In
** Provide additional details e.g. code snippets **
I need help understanding billing on my Cognito account. The vast majority of my users are executing Lambdas as unauthCognito users. It seems that these unauth users count towards my Cognito bill as individual identities. Is that correct? Also, I'm seeing Amazon Key Management Service charges starting to accumulate... but I'm not sure why? 

Anything to look out for here? I'm wondering if I should rewrite my code to call my Lambda for unauth users via API Gateway... right now I'm invoking the Lambda directly for unauth users but with unauth cognito credentials.

**Comment by Amplifiyer** [comment]
Hi @cliffordh, you can find more details about cognito pricing [here](https://aws.amazon.com/cognito/pricing/) You can also create a new support ticket in the [forum](https://forums.aws.amazon.com/forum.jspa?forumID=173)
