### ISSUE TITLE
Use a separate IdentityPool for Analytics

### ISSUE THREAD

**Issue by XinruiWu** [aws-amplify/amplify-js#4240]
** Which Category is your question related to? **
Auth, Analytics
** What AWS Services are you utilizing? **
Cognito, Pinpoint
** Provide additional details e.g. code snippets **
Hi, our static website use `Auth` to do user login/logout and `Analytics` to collect analytics data. Can we use one IdentityPool for Auth and another one for Analytics? Since our current IdentityPool for Auth is not in the same AWS account with the Pinpoint that we will use to collect analytics data, so It cannot correctly sign our putEvent request for that Pinpoint.

**Comment by XinruiWu** [comment]
The root cause of this issue is the IdentityPool for Auth and the Pinpoint for Analytics are in two different AWS account, is there any way to bridge these two?

**Comment by Amplifiyer** [comment]
@XinruiWu, It would mean signing account2's analytics requests from account1's credentials which I don't believe it's possible to do.

**Comment by XinruiWu** [comment]
> @XinruiWu, It would mean signing account2's analytics requests from account1's credentials which I don't believe it's possible to do.

Thanks for reply, that is why I was wondering if Amplify allows connecting to multiple identityPool then modules can chose one based on its purpose. And I think it is also doable through assumeRole.
