### ISSUE TITLE
Using AsyncStorage overwrites Amplify JWT's

### ISSUE THREAD

**Issue by yoursweater** [aws-amplify/amplify-js#4245]
Bug: using AsyncStorage from @react-native-community/async-storage causes the Cognito JWT's that were being retrieved by Auth.currentSession(). 

Behavior without AsyncStorage: Auth.signIn() returns a Cognito session that persists on the emulator through reload.

Behavior after adding the following code:

```
      try {
        let temporaryPassword = await AsyncStorage.getItem('@temporaryPassword')
        console.log(temporaryPassword)
        if(temporaryPassword !== null) {
          console.log('not null')
          this.setState({ temporaryPassword: temporaryPassword})
        } else {
          temporaryPassword = Math.random().toString(36).substr(2, 8) 
          await AsyncStorage.setItem('@temporaryPassword', temporaryPassword)
          console.log('setting: ', temporaryPassword)
          this.setState({ temporaryPassword: temporaryPassword})
        }
      } catch(e) {
        console.log(e)
      }
```

After implementing this code, the JWT's are overwritten on refresh for no apparent reason. Auth.currentSession() accordingly fails with no current session.

What the behavior should be: Writing to AsyncStorage should leave Auth.currentSession() intact and returning values. The user should be able to AsyncStorage.setItem('x', 'y'), reload the device, and then still see a response from Auth.currentSession().

Versions:
    "aws-amplify": "^1.1.36",
    "aws-amplify-react": "^2.3.12",

**Comment by yoursweater** [comment]
I'll note that creating a new storage class (such as the MyStorage example shown in the docs) fixes this issue, but it's still a poor experience (and certainly what I would consider a bug) that the default use of AsyncStorage overwrites the JWT's.

Doing `AsyncStorage.setItem('@banana', 'totallyShouldNotOverwriteJWTs')` should have zero bearing on whether or not Cognito's Auth breaks, unless '@banana' is literally the exact key that Cognito uses for its own AsyncStorage item.

**Comment by adamsythe** [comment]
I updated to react-native "^0.60.6", and my session is being lost on every reload of the simulator.  Could this be related to using redux persist?

**Comment by joebernard** [comment]
I'm seeing the same issue on the emulator and device. Happens in debug and release mode. It also happens on device when the app is manually killed/restarted (vs reloaded by the CLI). This started occurring after I recently upgraded Amplify. I'm  not using redux. I have only tested on iOS.

```
"react-native": "0.61.3",
"@aws-amplify/core": "^1.2.4",
"@aws-amplify/auth": "^1.5.0",
```

**Comment by district-michael** [comment]
See my comment on issue [#4351](https://github.com/aws-amplify/amplify-js/issues/4351#issuecomment-550538532), I fixed this temporarily by implementing a custom storage class.

**Comment by AakashPat** [comment]
Has anyone been able to find a permanent solution to this problem?

**Comment by yagiraldo62** [comment]
Any solution for this?

**Comment by yoursweater** [comment]
@yagiraldo62 - yup, the solution is to write your own storage class, like so:

```
import AsyncStorage from '@react-native-community/async-storage'
import Amplify, {Auth} from 'aws-amplify'

const MEMORY_KEY_PREFIX = '@MyStorage:'
let dataMemory = {}

class MyStorage {
  static syncPromise = null

  static setItem(key, value) {
    AsyncStorage.setItem(MEMORY_KEY_PREFIX + key, value)
    dataMemory[key] = value
    return dataMemory[key]
  }

  static getItem(key) {
    return Object.prototype.hasOwnProperty.call(dataMemory, key) ? dataMemory[key] : undefined
  }

  static removeItem(key) {
    AsyncStorage.removeItem(MEMORY_KEY_PREFIX + key)
    return delete dataMemory[key]
  }

  static clear() {
    dataMemory = {}
    return dataMemory
  }

  static sync() {
    if (!this.syncPromise) {
      this.syncPromise = new Promise((res, rej) => {
        AsyncStorage.getAllKeys((errKeys, keys) => {
          if (errKeys) rej(errKeys)
          const memoryKeys = keys.filter(key => key.startsWith(MEMORY_KEY_PREFIX))
          AsyncStorage.multiGet(memoryKeys, (err, stores) => {
            if (err) rej(err)
            stores.map((result, index, store) => {
              const key = store[index][0]
              const value = store[index][1]
              const memoryKey = key.replace(MEMORY_KEY_PREFIX, '')
              dataMemory[memoryKey] = value
            })
            res()
          })
        })
      })
    }
    return this.syncPromise
  }
}

Auth.configure({
  storage: MyStorage,
})
```

Pretty lame that this hasn't been fixed yet, but if you do this it should work correctly.
