### ISSUE TITLE
GraphQLResult and Observable<object> incorrect types for API.graphql

### ISSUE THREAD

**Issue by selipso** [aws-amplify/amplify-js#4257]
```
Type 'GraphQLResult | Observable<object>' is not assignable to type '{ data: CreateDocumentMutation; }'.
  Type 'GraphQLResult' is not assignable to type '{ data: CreateDocumentMutation; }'.
    Types of property 'data' are incompatible.
      Type 'object | undefined' is not assignable to type 'CreateDocumentMutation'.
        Type 'undefined' is not assignable to type 'CreateDocumentMutation'.  TS2322
```
Getting the above error using typescript after the new Amplify js version.

It would be better to use `Observable<any>` in this case because using type `object` is incompatible. In TypeScript the type `object` is the opposite of `any` and is not assignable to anything.

**Comment by Amplifiyer** [comment]
@selipso, can you share your code sample where you are getting this error?

**Comment by selipso** [comment]
```ts
async deleteDocument(id: string): Promise<{data:DeleteDocumentMutation}> {
    return API.graphql(graphqlOperation(deleteDocument, { input: { id } }));
}
```
Fairly simple wrapper function around the graphQL operation

**Comment by ffxsam** [comment]
Agreed, I don't see how `Observable` applies here. `API.graphql()` should return a `GraphQLResult` only.

**Comment by ffxsam** [comment]
Also, this:

```ts
export interface GraphQLResult {
    data?: object;
    errors?: [object];
    extensions?: {
        [key: string]: any;
    };
}
```

I would probably change the `data` line to:
```ts
data?: Record<string, any>;
```

**Comment by buggy** [comment]
@ffxsam It's complaining about `result.data.createFolder` because `result.data` is optional. Once TypeScript 3.7 is release this will be much easier

```typescript
return result.data?.createFolder;
```

There's a PR to add support for generics to the API's which helps with some of the stuff mentioned here. See #3748 

There's been much discussion about the return type of `API.graphql()`. Basically it's a `GraphQLResult` if you're performing a `query`/`mutation` and an `Observable` if you're performing a `subscription`

**Comment by ffxsam** [comment]
@buggy That's actually not true, as you can see above I'm checking for falsey values for `result` and `result.data` (which is partially blocked by the popup message).

It still gives me that error. And yeah, I haven't started using subscriptions yet, so your comment about `Observable` makes sense to me now.

**Comment by buggy** [comment]
@ffxsam I couldn't see the code behind the popup :(

The PR that I mentioned above should solve your problem once it's merged. It uses generics allowing your define the structure of the variables passed and data returned.

Something like:
```typescript
API.graphql<{createFolder: SOMETYPE}>(...)
```

Would allow you to access
```typescript
result.data?.createFolder
```

**Comment by selipso** [comment]
Thanks for the feedback and updates. Because of the convenient wrapper provided by API.graphql I am very happy with type ‘any’ and referring to the documentation for the data structure.

The generics solution is also fine or even `Promise<{data:any}> | Observable<{data:any}>`

**Comment by YangMann** [comment]
![image](https://user-images.githubusercontent.com/4034481/67640981-62b34780-f8bb-11e9-84a6-b06711f5976c.png)
I'm seeing a similar issue with API.graphql

**Comment by YangMann** [comment]
I'm seeing a similar issue with `await API.graphql()`. When trying to access `data` from the returned result:
```
TS2339: Property 'data' does not exist on type 'GraphQLResult | Observable<object>'.
  Property 'data' does not exist on type 'Observable<object>'.
```

**Comment by MatthieuLab** [comment]
we've solved this by adding an 'as unknown'.
If you have a better way to type, do not hesitate to share.

```
	(API.graphql(graphqlOperation(createAttributeMutation, { input: payload })) as unknown) as {
		data: CreateAttributeMutation
	}
```

**Comment by ffxsam** [comment]
I would use TS function overloading to achieve smarter return values so we don't have to bother with typecasting:

See [example here](https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=30&pc=1#code/JYOwLgpgTgZghgYwgAgIoFdoE8Cy6xxjAD2IA8gA5GkDOyA3gFDIvICOmUWAXMjWFFABzANzNWANziC4AIwA2EGgH5eAJQgJiUACYAefoJBCANMjggsAPjEBfRo1CRYiFAGV0smgkFUS5P1oGcRYaT29fahBeQ2ExVmQpGQUlVWQNLV0DAWEzC2s7Bxh0EAQo5CEoOAoACzZ5AAp6dk4sMyTgOUU6W14MbDwCKMoomgBKGJzjMWLS8srqusbmsK8fYECQdulOlJ7eDzXI-xH-cd4QdABbWWgZkrL-Cqra+obiTZpefInzSwZkCFkMAYMh3p8AHQcbBjYIJBIAegRyB0xD4YHQMBgQISUAgGKgIGQAHJUSAIMT4qxbMgIPIaCgQWCPqMIasIhsorCmPDWEiUWj+JjsbyWHiCUSAJwABipLHs9kYWhA-GQeLC8jAAEZkABeZ6LN481jQri8YmmrDIAAqAAkAJJuYkmIEdLpKXjNYA6XiS5C2F22MZiZWq9XoTUAJj1BteyyB7PWm3NieOpAYtmdjCDYiAA), and mouse over `result1` and `result2` to see that the types are different.

I realize this is a breaking change due to the parameters, but IMO this is better DX (developer experience).

**Comment by arnm** [comment]
any updates? seems like I always get a Promise and not Observable. It is a little annoying

**Comment by juniarz** [comment]
Here's how I did it!

API.graphql() declaration:
`
...
    graphql<T>({ query: paramQuery, variables, authMode }: GraphQLOptions): Promise<GraphQLResult<T>> | Observable<T> & { [key: string]: any };
...
`

GraphQLResult declaration:
`
...
export interface GraphQLResult<T> {
    data?: T;
    errors?: [object];
    extensions?: {
        [key: string]: any;
    };
}
...
`
1) Added `graphql<T>` for more flexible response data type.
2) I unioned `Observable<T>` with `{ [key: string]: any }` declaration to the `.graphql<T>(...)` return type instead of adding `{ data?: any }` which Observable will never have.

**Comment by michalmikolajczyk** [comment]
This problem popped up for me during the React Amplify tutorial https://docs.amplify.aws/start/getting-started/data-model/q/integration/react#connect-frontend-to-api

Line 24:
```
const todos = todoData.data.listTodos.items
```

The error is:
```
Property 'data' does not exist on type 'GraphQLResult<object> | Observable<object>'.
  Property 'data' does not exist on type 'Observable<object>'.ts(2339)
```

**Comment by selipso** [comment]
^ This is the workaround I've been using too

**Comment by chernando** [comment]
@michalmikolajczyk @selipso as you know using `any` disables type checking.

Until #5208 or #3748 gets through, try something like this:

```typescript
import { GraphQLResult } from "@aws-amplify/api";
import { ListTodosQuery } from "./api";

// ...

const todoData = (
  await API.graphql(graphqlOperation(listTodos))
) as GraphQLResult<ListTodosQuery>;

const todos = todoData.data.listTodos.items
```

**Comment by vanceingalls** [comment]
> @michalmikolajczyk @selipso as you know using `any` disables type checking.
> 
> Until #5208 or #3748 get through, try something like this:
> 
> ```ts
> import { GraphQLResult } from "@aws-amplify/api";
> import { ListTodosQuery } from "./api";
> 
> // ...
> 
> const todoData = (
>   await API.graphql(graphqlOperation(listTodos))
> ) as GraphQLResult<ListTodosQuery>;
> 
> const todos = todoData.data.listTodos.items
> ```

This results in todoData possibly 'undefined'

**Comment by chernando** [comment]
> > @michalmikolajczyk @selipso as you know using `any` disables type checking.
> > Until #5208 or #3748 get through, try something like this:
> > ```ts
> > import { GraphQLResult } from "@aws-amplify/api";
> > import { ListTodosQuery } from "./api";
> > 
> > // ...
> > 
> > const todoData = (
> >   await API.graphql(graphqlOperation(listTodos))
> > ) as GraphQLResult<ListTodosQuery>;
> > 
> > const todos = todoData.data.listTodos.items
> > ```
> 
> This results in todoData possibly 'undefined'

Probably because you're using `strict: true` in your `tsconfig.json`. Try something like:

```typescript
const todos = todoData?.data?.listTodos?.items
```

But be aware that `items` may be `null`, or even `null[]`, (check the generated type definition). You have to handle this, in any way makes sense for your project, to keep type consistency.

**Comment by deldrid1** [comment]
I'm also trying to follow along with https://docs.amplify.aws/start/getting-started/data-model/q/integration/react-native#connect-frontend-to-api with Typescript by trying to add a new screen inside of https://github.com/ethanneff/react-native-web-typescript.

My issue is with the type to useState

```
src/screens/Amplify/index.tsx:33:18 - error TS2345: Argument of type '({ __typename: "Todo"; id: string; name: string; description: string | null; createdAt: string; updatedAt: string; } | null)[]' is not assignable to parameter of type 'SetStateAction<never[]>'.
  Type '({ __typename: "Todo"; id: string; name: string; description: string | null; createdAt: string; updatedAt: string; } | null)[]' is not assignable to type 'never[]'.
    Type '{ __typename: "Todo"; id: string; name: string; description: string | null; createdAt: string; updatedAt: string; } | null' is not assignable to type 'never'.
      Type 'null' is not assignable to type 'never'.

33         setTodos(todos);
```

I've solved it by for now by passing `<any[]>` and putting a guard around `setTodos` but that doesn't feel quite right here...
```
  const [todos, setTodos] = useState<any[]>([]); //TODO: Fix the type here

...

      if (todos) {
        setTodos(todos);
      }
```
Any experts with a better fix?

**Comment by grifin85** [comment]
It's because need using **Observable** not from **rxjs**, but **zen-observable-ts**

**Comment by locnesse** [comment]
im getting this do any one have solution for this

"Property 'data' does not exist on type 'GraphQLResult<object> | Observable<object>'.\n  Property 'data' does not exist on type 'Observable<object>'.",
code:
if(userInfo) {
      // Check if user already exists in database
      const userData = await API.graphql(graphqlOperation(getUser, {id: userInfo.attributes.sub})); 
      console.log (userData)
      if (!userData.data.getUser) {
        const user = {
          id : userInfo.attributes.sub,
          username : userInfo.username,
          name : userInfo.username,
          email : userInfo.attributes.email,
          image : getRandomImage(),
        }
        await saveUserToDB(user);
      } else {
        console.log('user already exists');
      }
       }

**Comment by seanvm** [comment]
@mauerbac I fail to see how this is a feature request. The codegen feature shouldn't produce code that needs to be manually modified/overridden for it to work..

Changing the imports in the generated api.service.ts from `zen-observable` to `zen-observable-ts` does fix the errors for me, though.

**Comment by locnesse** [comment]
i add any: and it fixed my problem

**Comment by locnesse** [comment]
but i still have this problem do you know how to solve it

**Comment by sanyashvets** [comment]
any updates on it?
I don't like to have `any` type in code

**Comment by cybercussion** [comment]
I ran into something like this with @connection .. it doesn't write out the connected data types only a subset.

```
type Asset @model
    @key(name: "assetTitleIndex", fields: ["title"], queryField: "assetsByTitle")
    @key(name: "assetFolderIndex", fields: ["folder", "owner"], queryField: "assetsByFolder")
    @key(name: "assetOwnerIndex", fields: ["owner", "folder"], queryField: "assetsByOwner")
{
    id: ID!
    owner: ID!
    attempts: [Attempt] @connection(keyName: "attemptByAssetIndex", fields: ["id", "owner"])
    folder: String!
    title: String!
    description: String
    size: Int!
    manifest: AWSJSON!
    version: String!
    public: Boolean
    editors: [ID]
    createdAt: AWSDateTime
    updatedAt: AWSDateTime
}


type Attempt @model
    @key(name: "attemptByOwnerIndex", fields: ["owner"], queryField: "attemptByOwner")
    @key(name: "attemptByAssetIndex", fields: ["asset", "owner"], queryField: "attemptByAsset")
{
    id: ID!
    owner: ID!
    asset: ID!
    satisfied: Boolean!
    progress: Boolean!
    completion: Boolean
    score: Int!
    data: AWSJSON!
    attempts: Int!
    exitType: String!
    createdAt: AWSDateTime
    updatedAt: AWSDateTime
}
```
Results in a API.service.ts:

```
  OnCreateAssetListener: Observable<
    SubscriptionResponse<OnCreateAssetSubscription>
  > = API.graphql(
    graphqlOperation(
      `subscription OnCreateAsset {
        onCreateAsset {
          __typename
          id
          owner
          attempts {
            __typename
            // THIS PART IS MISSING
            items {
              __typename
              id
              owner
              asset
              satisfied
              progress
              completion
              score
              data
              attempts
              exitType
              createdAt
              updatedAt
            }
            // PART MISSING
            nextToken
          }
          folder
          title
          description
          size
          manifest
          version
          public
          editors
          createdAt
          updatedAt
        }
      }`
    )
  ) as Observable<SubscriptionResponse<OnCreateAssetSubscription>>;
```
And any section that needs it.  I manually put it back in but if I touch the schema it wipes it out again.

**Comment by benm5678** [comment]
Same issue... changing to <any> doesn't fix it.  
The code should be generate without needing to edit it.  
Any solutions?

**Comment by mariusbutuc** [comment]
Related? https://github.com/aws-amplify/amplify-js/issues/5741

**Comment by undefobj** [comment]
@elorzafe lets track this for next major version

**Comment by ZYinMD** [comment]
My temporary solution might be cleaner than the ones mentioned above:

You could change this:
```ts
const result = await API.graphql(graphqlOperation(listTodos));
```
to this:
```ts
import { GraphQLQuery } from '@aws-amplify/api';

const result = await API.graphql<GraphQLQuery<typeof listTodos>>(graphqlOperation(listTodos));
```

If the import has errors, you may need to add `@aws-amplify/api` as a dependency in your package.json.

**Comment by rudyhadoux** [comment]
Hello.
@michalmikolajczyk Your solution is the good one. 
Thanks.

**Comment by kaili-kameoka** [comment]
@ZYinMD How do you then access the data. I have the following code:
```
const toDoData = await API.graphql<GraphQLQuery<typeof listToDos>>(graphqlOperation(listToDos));
const toDos = toDoData.data.listTodos;
```
It's based on the documentaion from here:
https://docs.amplify.aws/start/getting-started/data-model/q/integration/react/#connect-frontend-to-api
When I try to access the data, it gives the following error:
```
TS2339: Property 'listTodos' does not exist on type 'GraphQLQuery"\n query ListTodos(\n $filter: ModelTodoFilterInput\n $limit: Int\n $nextToken: String\n ) {\n listTodos(filter: $filter, limit: $limit, nextToken: $nextToken) {\n items {\n id\n name\n description\n createdAt\n updatedAt\n }\n nextToken\n...'.
```

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
