### ISSUE TITLE
S3 is not a constructor & Observable is not a constructor ERRORS

### ISSUE THREAD

**Issue by orcunorcun** [aws-amplify/amplify-js#4259]
### Problem:
I was using Storage and subscription well on React Native, but now it doesn't work with same codes. It rejects with 

> _S3 is not a constructor_

 for Storage,  

> _Observable is not a constructor_

for Subscription (Queries and mutations working well.)

### Packages:
```
  "react": "16.9.0",
  "react-native": "0.61.2",
  "amazon-cognito-identity-js": "3.1.3",
  "aws-amplify": "1.2.3",
  "aws-amplify-react-native": "2.2.3",
```
### Codes:
```
import awsconfig from './aws-exports';
import Amplify, {Storage} from 'aws-amplify';

Amplify.configure(awsconfig);

export const ImageDownloader = fileName => {
  return Storage.get(fileName, {track: true});
};
```

**Comment by Nitheesh-u** [comment]
Same error for me "Object is not a constructor (evaluating 'new S3')"

**Comment by rarira** [comment]
same error @aws-amplify/storage.. v1.2.2 is fine.

**Comment by Amplifiyer** [comment]
@orcunorcun @Nitheesh-u @rarira I pushed a quick fix for that which is now published to unstable, can you please test it with this version(unstable tag) and let us know if that solved this issue?

**Comment by itsgitz** [comment]
@Amplifiyer well, I've changed the version with unstable tag:
 `"aws-amplify": "^1.2.3-unstable.0"`

And then new warning has occured:
`[Unhandled promise rejection: Error: No credentials, applicationId or region]`

So, I disable `Analytics` like this:
`Amplify.configure({
  Analytics: {
    disabled: true
  }
})`

And it works for both S3 and Subscriptions.

**Comment by adamsythe** [comment]
why is this closed?

**Comment by itsgitz** [comment]
@adamsythe  I don't why, but I'm still waiting for update. My application can't `subscribe` using `aws-amplify` with unstable version

**Comment by Amplifiyer** [comment]
@itsgitz @adamsythe, can you please post your error messages and code samples here that is causing the issue? Please also verify the unstable version of aws-amplify packages you are consuming in the node_modules folder.

**Comment by itsgitz** [comment]
@Amplifiyer for now, there's no problem with S3 but I got this error/warning messages, `and` I can't publish message using MQTT:
![ss](https://user-images.githubusercontent.com/20938898/67733314-995e9e80-fa30-11e9-8fd0-ecad3b418cbb.png)

And this is my sample codes:
```javascript
PubSub.publish(topic, {
    command: 'open',
});
```

I'm using `"aws-amplify": "^1.2.4-unstable.5"`.

Thank you :)

**Comment by adamsythe** [comment]
^1.2.4-unstable.5 seems to be working from me but surely this should stay live at least until the fix goes into an official release?

**Comment by Amplifiyer** [comment]
The fix has reached into a stable release. @adamsythe, github automatically closes the issue when tagged with `fixes` directive, and our master commits go to unstable release (automatically) but not to stable releases

**Comment by itsgitz** [comment]
@Amplifiyer thanks! It solved with latest stable version `"aws-amplify": "^1.2.4"`

**Comment by sammartinez** [comment]
Resolving as the [release](https://www.npmjs.com/package/aws-amplify/v/1.2.4) was completed yesterday as @Amplifiyer called out. Please feel free to reopen if you are still experiencing this issue.
