### ISSUE TITLE
RN [Auth] [API] Refresh token not working - "No current user"

### ISSUE THREAD

**Issue by usmansbk** [aws-amplify/amplify-js#4260]
**Describe the bug**
I keep getting ` WARN  Possible Unhandled Promise Rejection (id: 3):
"No current user"`
```
 LOG  [DEBUG] 47:44.474 AuthClass - Getting current session
 LOG  [DEBUG] 47:44.571 AuthClass - Failed to get user from user pool
 LOG  [DEBUG] 47:44.581 AuthClass - Getting current session
 LOG  [DEBUG] 47:44.592 AuthClass - Failed to get user from user pool
 LOG  [DEBUG] 47:44.600 AuthClass - Failed to get the current user No current user
 LOG  [DEBUG] 47:44.614 AuthClass - Failed to get the current user No current user
```

calling `Auth.currentAuthenticatedUser()` after restarting the app returns `"not authenticated"`

**To Reproduce**

1. Login using federatedSignin or signIn
2. Make a query with ApolloClient
3. Close and Reopen app
4. No query or mutation works anymore.
5. Log out and Login again
6. Queries work but Mutations dont

**Smartphone (please complete the following information):**
```

    "aws-amplify": "1.2.4-unstable.5",
    "aws-amplify-react-native": "2.2.4-unstable.5",
    "aws-appsync": "^2.0.1",
    "aws-appsync-react": "^2.0.1",
    react: ^16.11.0 => 16.11.0
    react-native: ^0.61.2 => 0.61.2
```

**Comment by rarira** [comment]
same error after upgrading @aws-amplify/auth v1.2.3.
there seems to be so many bugs in v1.2.3 in almost every packages included

**Comment by Amplifiyer** [comment]
@usmansbk, can you test your code with latest unstable release and let us know if you are still facing the issue?

**Comment by usmansbk** [comment]
@Amplifiyer  This bug still persist.

**Comment by Nitheesh-u** [comment]
am facing the same issue

**Comment by usmansbk** [comment]
I solved it by using [custom storage](https://aws-amplify.github.io/docs/js/authentication#managing-security-tokens)
```js
Amplify.configure(aws_config);
Auth.configure({
    storage: AmplifyStorage
});
```
