### ISSUE TITLE
RN [Analytics] multiple bugs - updateEndpoint, callable, putEvents

### ISSUE THREAD

**Issue by usmansbk** [aws-amplify/amplify-js#4261]
**Describe the bug**
I keep getting this errors while using analytics
`TypeError: Cannot read property 'updateEndpoint' of undefined`
`TypeError: constructor is not callable`
`TypeError: Cannot read property 'putEvents' of undefined`

**To Reproduce**
```js
Analytics.record({
  name: 'GraphQLError',
  attributes: {
    errorName: error.name,
    errorMessage: error.message,
    errorPath: error.path,
  }
})
```
```js
Analytics.updateEndpoint({
    userId: xxx-xxx-xxx,
    address: token,
    optOut: 'NONE',
    channelType
})
```

**Smartphone (please complete the following information):**
```json
    "aws-amplify": "^1.2.3",
    "aws-amplify-react-native": "^2.2.3",
    "aws-appsync": "^2.0.1",
    "aws-appsync-react": "^2.0.1",
    "react": "^16.11.0",
    "react-native": "^0.61.2",
```

**Comment by Amplifiyer** [comment]
@usmansbk, I pushed a quick fix for this which is now published to unstable, can you please test it with this version(unstable tag) and let us know if it solved this issue?

**Comment by usmansbk** [comment]
@Amplifiyer now it's working as expected. Thanks.

**Comment by rainflute** [comment]
@usmansbk Can you please show us how to pull the unstable branch with npm install?

**Comment by usmansbk** [comment]
`yarn add aws-amplify@1.2.4-unstable.5` or `npm install aws-amplify@1.2.4-unstable.5`

**Comment by rainflute** [comment]
> @rainflute `yarn add aws-amplify@1.2.4-unstable.5` or `npm install aws-amplify@1.2.4-unstable.5`

Thanks. It's working now. This bug got me so frustrated for the last two days. I thought it was something wrong with my AWS setup
