### ISSUE TITLE
Authenticator component only shows 'Loading...' with a basic setup

### ISSUE THREAD

**Issue by YahngSungho** [aws-amplify/amplify-js#4271]
**Describe the bug**

![2019-10-28 00 12 35 LearnObit - Chrome](https://user-images.githubusercontent.com/29212791/67636941-f36c4080-f918-11e9-8d6d-fde11320ca7e.png)

If I don't provide the amplifyConfig prop, it will render normally (of course it can't actually sign in / up).

But if I put amplifyConfig prop, only Loading ... appears.

When hiding the loading component it shows nothing.

I only configured the social provider with the default auth configuration and the same is true even if there is no federated prop.

How can I make the Authenticator component work normally? I would like a keyword to search for.

**Desktop (please complete the following information):**

- OS: Windows 7
- Browser: chrome
- Version: latest 

**Amplify context**
- Framework: React
- Versions of Amplify you are using: latest

**Additional context**
withAuthenticator HOC works. However, even withAuthenticator, when I configure federated prop the buttons for each provider do not work for unknown reasons.

**Sample code**
My code is roughly like this

```
function App ({ authState }) {
  return (
  authState === 'signedIn' ? (
    <div>
      {something}
    </div>
  ) : <div />
  )
}

const federated = {
  google_client_id: '<google-id>',
  facebook_app_id: '<fb-id>',
  amazon_client_id: ''
}

class AppWithAuth extends Component {
  render () {
    return (
      <Authenticator
        amplifyConfig={awsconfig}
      >
         <App />
      </Authenticator>
    )
  }
}

// export default withAuthenticator(FullWindow, true, [], federated, {})
// export default FullWindow
export default AppWithAuth

```

my awsconfig
```
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "<idp-id>",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "<up-id>",
    "aws_user_pools_web_client_id": "<upwc-id>",
    "oauth": {
        "domain": "<oa-domain>",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:5000/",
        "redirectSignOut": "http://localhost:5000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;

```

**Comment by YahngSungho** [comment]
Although it's not a direct solution to this problem, can I know where I should look? I would be grateful if anyone gave me a hint.

**Comment by YahngSungho** [comment]
Some observation

* with debug tool, I detected that authState is just 'loading'
* When I did Auth.signOut(), it seems work. But that case whenever user come to the app use will be forced to sign out. So it's not reliable.

**Comment by jordanranz** [comment]
In the meantime, I am looking into reproducing this. This may be related to the following PR: https://github.com/aws-amplify/amplify-js/pull/4258

**Comment by YahngSungho** [comment]
@jordanranz Thank you. It works. I thought I've tried that but maybe... I was wrong
