### ISSUE TITLE
AsyncStorage wrong import - removed from react-native and moved to different package

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-js#4272]
**Describe the bug**
AsyncStorage has been removed from `react-native` and moved to a new package `@react-native-community/async-storage` which means developers that have `react-native` version >=0.60 doesn't have the functionality that is related to async storage. So for example when users exit the app the login data is not saved and they need to login again, which is very frustrating. I have looked at your code and there are many files that use `AsyncStorage` from `react-native`, this needs to be changed to the new package `@react-native-community/async-storage`

**Comment by idanlo** [comment]
There is PR open for this already #4027

**Comment by usmansbk** [comment]
@Amplifiyer  I believe this is the source of the Auth bug. Please release an unstable version as it's a major blocker.

**Comment by alisherakb** [comment]
Kindly ask maintainers to accept the PR. We can't move on with two projects.

> There is PR open for this already #4027

**Comment by usmansbk** [comment]
@alisherakb  you can configure a [custom storage](https://aws-amplify.github.io/docs/js/authentication#managing-security-tokens). It's quite easy
```js
Amplify.configure(aws_config);
Auth.configure({
    storage: AmplifyStorage
});
```

**Comment by alisherakb** [comment]
@usmansbk Thanks for the suggestion. I copied your code snippet to App.js and created custom Storage class and received this error:
<img width="347" alt="Screenshot 2019-10-29 at 12 32 50" src="https://user-images.githubusercontent.com/26904008/67759503-3a0c8880-fa48-11e9-8c0e-2df82e71f4ec.png">

Here is the gist with custom storage class:
https://gist.github.com/alisherakb/1d5f51f3673806e429f36cb58ed1052f

**Comment by usmansbk** [comment]
@alisherakb  did you call `Auth.configure` at startup?

**Comment by alisherakb** [comment]
@usmansbk Yes, I’ve added Auth.configure with custom storage within it right below Amplify.configure.

**Comment by JamieLivi** [comment]
This is what finally worked for me in my App.tsx -

[https://gist.github.com/JamieLivi/fc14460735b49b291fd62862df432752](url)

With the following in package.json:  

    "amazon-cognito-identity-js": "^3.1.3",
    "aws-amplify": "^1.2.3",
    "aws-amplify-react-native": "^2.2.3",
    "aws-appsync": "^2.0.1",
    "aws-appsync-react": "^2.0.1",

Hope this helps mate, was stuck on this for fracking ages.

**Comment by usmansbk** [comment]
@alisherakb you should try the unstable versions. That's the version I'm using.

**Comment by alisherakb** [comment]
@usmansbk I changed dependencies to unstable ones:
  ```
    "aws-amplify": "^1.2.4-unstable.5",
    "aws-amplify-react-native": "2.2.4-unstable.5" 
```

 **But the situation hasn't changed for me**

**Comment by johnny-minty** [comment]
The amplify documentation covers how to set the storage provider for AUTH (https://aws-amplify.github.io/docs/js/authentication#managing-security-tokens) and provides an example with ASYNC storage. 

A short term fix for those affected should take that example but import "@react-native-community/async-storage" - there's no API changes between the old bundled DEP and the new community version. 

Very easy and works. 

Cheers

**Comment by sammartinez** [comment]
Resolving issue as the above PR was merged in order to resolve the Async Storage community edition

**Comment by belal-mazlom** [comment]
If user has challenge to change password, Amplify will consider user as not logged in, Lol
I just spend hours thought it's AsyncStorage issue, but found user just need to change password....
https://github.com/aws-amplify/amplify-js/issues/1715

**Comment by benjaminfiliatrault** [comment]
> Resolving issue as the above PR was merged in order to resolve the Async Storage community edition

The PR was not merged

**Comment by professorkolik** [comment]
> Resolving issue as the above PR was merged in order to resolve the Async Storage community edition

Issue still exists [here](https://github.com/aws-amplify/amplify-js/blob/main/packages/core/src/StorageHelper/reactnative.ts)

**Comment by Ashish-Nanda** [comment]
The PR #8250 to migrate to the community version of AsyncStorage has just been merged to `main`.
Please refer https://github.com/aws-amplify/amplify-js/issues/6031#issuecomment-837332785 for latest updates on the release.

**Comment by andidev** [comment]
@Ashish-Nanda this is great but unfortunately you need to upgrade aws-appsync as well. 
https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/654

aws-appsync uses `@react-native-community/async-storage` while it should use `react-native-async-storage/async-storage`. For some reason they changed the package name.

I have been waiting 2 years on updating our react native app because of the breaking changes in react native 0.60 and it looks like it is still not possible.

I would create an issue in `aws-mobile-appsync-sdk-js` but I have seen to many issues being ignored there.
