### ISSUE TITLE
Object is not a constructor (evaluating 'new S3')

### ISSUE THREAD

**Issue by michalgarcarz** [aws-amplify/amplify-js#4273]
** Which Category is your question related to? **
Storage
** What AWS Services are you utilizing? **
Cognito, AWS AppSync
** Provide additional details e.g. code snippets **
I have provisioned storage as per doc, but can not put any file to S3, when trying:

import { API, graphqlOperation, Storage, Auth } from 'aws-amplify';
//amplify configured, other services like cognito or app sync working fine, aws-exports having //bucket+region for S3

Storage.put('test.txt', 'Private Content', {
        level: 'private',
        contentType: 'text/plain'
    })
    .then (result => console.log(result))
    .catch(err => console.log(err));

Got error: [TypeError: Object is not a constructor (evaluating 'new S3')]

None of the Storage.put() examples works for me (from https://aws-amplify.github.io/docs/js/storage).

What am i missing ? 
It needs to be something super simple/obvious...

"aws-amplify": "^1.2.3",
"aws-amplify-react-native": "^2.2.3",
'react-native': '0.59.8',
npm: '6.9.0',
expo: 3.4.1

Thanks,

**Comment by michalgarcarz** [comment]
Great, thanks, what would be the workaround in the meantime ?
Since Storage is unusable i wanted to:
1. Use Auth.currentCredentials() and get identity aws credentials for my currently logged in Cognito user
2. Get access+secret key from result of #1 and use it with https://www.npmjs.com/package/react-native-s3-upload to upload securely images to S3. Would that work ? Any other recommendation ?

Thanks,
Michal

**Comment by sammartinez** [comment]
@michalgarcarz We did do a release yesterday `1.2.4` now has this change. Please let us know if you are still experiencing this issue with the latest version released.

**Comment by michalgarcarz** [comment]
Yep, confirmed working fine with 1.2.4, thanks @sammartinez !

**Comment by sammartinez** [comment]
Absolutely ! Resolving this issue.
