### ISSUE TITLE
Authentication errors are swallowed by handleAuthResponse.

### ISSUE THREAD

**Issue by navilan** [aws-amplify/amplify-js#4274]
**Describe the bug**

An unfortunate side effect of PR #3993 is that errors are now swallowed. We use `Hub.listen` to listen on errors and handle them, this change has prevented that. Can we revert this change please or remove lines 199 - 201?

https://github.com/aws-amplify/amplify-js/pull/3993#issuecomment-546846851

**Comment by jordanranz** [comment]
Hey @navilan, can you post a code snippet for the `Hub.listen` code you mentioned using. We may be able to reconcile this by dispatching the error as a Hub event so you can still listen for it.

**Comment by perunthagai-memorang** [comment]
@jordanranz  It would be great if we can catch this error in Hub.listen.
Our Hub.listen code is as follows

     ```
  Hub.listen('auth', (data) => {
      if (data.payload.event === 'signUp_failure' || data.payload.event === 'customState_failure') {
        
        //This erro is custom message which we throw from Pre-signup trigger in Cogntio.
        const message = decodeURIComponent(data.payload.data.message);
        const parsedData = message.substring(
          message.lastIndexOf('[') + 1,
          message.lastIndexOf(']') - 1,
        );
        if (!parsedData) {
          return;
        }
        const { username: usernameToMerge, migratedUser: migratedUserFlag, error } = JSON.parse(parsedData);
        if (error === 'userAlreadyExistsException') {
          return;
        }
        
        //Prompt Dialog to User to do specififc action
        showDialog();
        }
    });
```

**Comment by elorzafe** [comment]
@navilan I think this issue should be fixed with pr #4679. Can you try installing amplify on @unstable tag.

**Comment by navilan** [comment]
Thank you @elorzafe

**Comment by elorzafe** [comment]
@navilan did you tried the @unstable package?

**Comment by navilan** [comment]
@elorzafe - I am not involved with this project anymore.  @perunthagai-memorang should be able to respond to this.

**Comment by elorzafe** [comment]
@perunthagai-memorang let me know how it goes.
