### ISSUE TITLE
Public Auth not working with Cognito UserPool

### ISSUE THREAD

**Issue by anarerdene** [aws-amplify/amplify-js#4275]
**Describe the bug**

Public Auth not working with Cognito UserPool
**Expected behavior**

**Amplify context**
- Framework (e.g. React, Angular, Vue, React Native)
- Versions of Amplify you are using
React, Nextjs

My main auth is Cognito UserPool. Some queries are public then i used multi auth and i created secondary API using amplify CLI. 

But {allow:public} not working on me. 
Do i need multiple Apollo client  ?

```javascript
@auth(rules: [{allow: public, provider: apiKey, operations: [read]}]) 
```

also im using AppsyncSDK

here is my client code.

```javascript
const client = new AWSAppSyncClient(
    {
      url: config.aws_appsync_graphqlEndpoint,
      region: config.aws_appsync_region,
      auth: {
        type: config.aws_appsync_authenticationType,
        jwtToken: async () => (await Auth.currentSession()).getIdToken().getJwtToken()
      },
      disableOffline: true
    },
    {
      cache: new InMemoryCache().restore(initialState || {}),
      ssrMode: true,
      connectToDevTools: true
    }
  );
```
**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

Uncaught (in promise) No current user

**Comment by sammartinez** [comment]
@anarerdene are you still experiencing this issue? Please let us know
