### ISSUE TITLE
Modular import of aws-amplify-react

### ISSUE THREAD

**Issue by leosoaivan** [aws-amplify/amplify-js#4279]
** Which Category is your question related to? **
aws-amplify-react
** What AWS Services are you utilizing? **
N/A
** Provide additional details e.g. code snippets **

Following the discussion in #2781, I've imported various bits of aws-amplify-react like so:
```
import { Authenticator } from 'aws-amplify-react/dist/Auth';
```

This worked, initially. As of today, the import path is not able to resolve successfully, with my linter throwing `Unable to resolve path to module 'aws-amplify-react/dist/Auth'`. 

This seems to work:
```
import { Authenticator } from 'aws-amplify-react/lib/Auth';
```

Was there a recent change I should be aware of, or are there any other alternative to importing modules?

**Comment by jordanranz** [comment]
Hey @leosoaivan, 

Unfortunately modularly importing UI components (by category) from `aws-amplify-react` is currently not officially supported. The comment you mentioned in the issue description was a temporary workaround/hack for what you are trying to achieve.

That being said, modularly importing UI Components is something that are evaluating for the UI Component library refactor: https://github.com/aws-amplify/amplify-js/issues/3279

The change that affected you happened in this PR: https://github.com/aws-amplify/amplify-js/pull/4007
per this RFC: https://github.com/aws-amplify/amplify-js/issues/3365

Using:
```
import { Authenticator } from 'aws-amplify-react/lib/Auth';
```
will work for the time being but the official support will come as a pahse of the UI component refactor.

**Comment by leosoaivan** [comment]
@jordanranz 

Thanks for the input. I figured it there was a minor version bump that caused the issue. For the time being, I've locked my version to the one where the `/dist/` import works, since it's really been helpful for our build sizes.

I'll continue following the modularization issue for the proper implementation, whenever it comes. Closing this issue!

**Comment by andy-hammond** [comment]
@leosoaivan which version did you have to lock it down to? Could do with this same fix myself. Thanks in advance

**Comment by andy-hammond** [comment]
> @jordanranz
> 
> Thanks for the input. I figured it there was a minor version bump that caused the issue. For the time being, I've locked my version to the one where the `/dist/` import works, since it's really been helpful for our build sizes.
> 
> I'll continue following the modularization issue for the proper implementation, whenever it comes. Closing this issue!

@leosoaivan which version did you have to lock it down to? Could do with this same fix myself. Thanks in advance

**Comment by leosoaivan** [comment]
@andy-hammond     

"aws-amplify-react": "2.3.10"
