### ISSUE TITLE
Unable to compile project in Windows

### ISSUE THREAD

**Issue by thundermiracle** [aws-amplify/amplify-js#4282]
**Describe the bug**
Unable to compile the project in Windows10 by following the [wiki]((https://github.com/aws-amplify/amplify-js/wiki/Local-Development) ).

As Windows file system's slash is \\ instead of /.

**To Reproduce**
run ```yarn && yarn build``` in Windows10.

**Expected behavior**
Able to compile and test in Windows system.

**Desktop (please complete the following information):**

- OS: Windows10

**Additional context**
It's more readable and maintain to resolve path by using nodejs' path library instead of using .indexOf & .slice().
For example:
```diff
 'use strict';

+const path = require('path');
 const utility = require('./utility');
 const ts = require('typescript');
 const externals = require('./rollup-externals');

-const currentPath = process.argv[1].slice(0, process.argv[1].lastIndexOf('/'));
-const tscES5OutDir = `/lib`;
-const tscES6OutDir = `/lib-esm`;
+const currentPath = process.cwd();
+const tscES5OutDir = `./lib`;
+const tscES6OutDir = `./lib-esm`;
 const packageInfo = require(`${currentPath}/package`);

 async function buildRollUp() {
@@ -16,10 +17,9 @@ async function buildRollUp() {
        const sourceMaps = require('rollup-plugin-sourcemaps');
        const json = require('rollup-plugin-json');

-       const input = `${currentPath}${tscES5OutDir}/index.js`;
-       const file = `${currentPath}${packageInfo.main.slice(
-               packageInfo.main.indexOf('/')
-       )}`;
+       const input = path.resolve(currentPath, tscES5OutDir, 'index.js');
+       const file = path.resolve(currentPath, path.basename(packageInfo.main));
+
        // For more info see: https://github.com/rollup/rollup/issues/1518#issuecomment-321875784
        const onwarn = warning => {
                if (warning.code === 'THIS_IS_UNDEFINED') {
```

**Comment by sammartinez** [comment]
@thundermiracle Thanks for cutting the PR with this as well! We will be taking a look at the PR and will get back to you as needed.

**Comment by jordanranz** [comment]
Merged your PR. Thanks for contributing. Please open a new issue if you experience any related problems.
