### ISSUE TITLE
JS.browserOrNode() causes Amplify.configure() to fail on Lambda

### ISSUE THREAD

**Issue by mdw2000** [aws-amplify/amplify-js#4283]
The `JS.browserOrNode()` function from `@aws-amplify/core` does not return the correct `isNode` value when executing on AWS Lambda, which causes the `Amplify.configure(config)` function to fail.  Ultimately any use of the API (e.g. query or mutation) returns the `API not configured` error.

This only happens only when executed on AWS Lambda, when running locally on `node 10` it executes correctly.

`JS.browserOrNode()` is called from `aws-amplify/auth/dist/urlListener.js` when initialising the Auth config, but because the `isNode` is not returned correctly the function throws a `Not supported` exception.

This is reproducible with the following code snippet running on a node10.x Lambda:
```
 const browserOrNode = JS.browserOrNode();
 logger.info(` JS.browserOrNode() = ${JSON.stringify(browserOrNode, null, 2)}`);
```
prints the following:
```
 JS.browserOrNode() = {
  "isBrowser": false,
  "isNode": false
}
```

Interestingly on the same runtime if I directly execute the code from `JS.browserOrNode()` it returns the correct values.

```
const isBrowser = typeof window !== 'undefined' && typeof window.document !== 'undefined';
const isNode = typeof process !== 'undefined' &&
                process.versions != null &&
                process.versions.node != null;
 logger.info(` isBrowser = ${isBrowser}`);
 logger.info(` isNode = ${isNode}`);
```
produces:
```
 isBrowser = false
 isNode = true
```

Environment:
Lambda Node 10.x (happens on 8.10 runtime as well)
aws-amplify 1.2.3

## EDIT

Rolling back to the previous release versions of these packages solved the issue - so limited to `aws-amplify@1.2.3 release`
```
"dependencies": {
    "@aws-amplify/analytics": "1.3.2",
    "@aws-amplify/api": "1.2.2",
    "@aws-amplify/auth": "1.4.2",
    "@aws-amplify/core": "1.2.2",
    "aws-amplify": "1.2.2",
    ...
}
```

**Comment by sammartinez** [comment]
@mdw2000 Amplify doesn't officially support NodeJS, however, we did find a [bug](https://github.com/aws-amplify/amplify-js/pull/4255) where customers were experiencing issues with their node environments and was resolved last week in our unstable versions and release was done yesterday, version `1.2.4`. Please let us know if you are still experiencing this issue with the latest version of `aws-amplify`.
