### ISSUE TITLE
AppSync Subscriptions: Object is not a constructor - new Observable

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-js#4286]
**Describe the bug**
If i set subscriptions, i get this error:

![Simulator Screen Shot - iPhone 11 - 2019-10-29 at 14 59 27](https://user-images.githubusercontent.com/7137361/67775158-ce81e580-fa5e-11e9-9b29-3e7120933797.png)

```
"aws-amplify": "^1.2.3",
"aws-amplify-react": "^2.5.2",
"aws-amplify-react-native": "^2.1.12",
```

```
export const subscription = async (ressource, doThan) => {
  try {
    API.graphql(graphqlOperation(subscriptions[ressource])).subscribe({
      next: data => doThan(data)
    });
  } catch (e) {
    alert(e);
    return { error: e };
  }
};
```

```
 EventStore.subscriptionToEvent("onCreateEvent", data =>
      this.doThanEvent(data)
    );
```

**Comment by Zillaine** [comment]
I have same problem, could be "aws-amplify" version? (1.2.3) Was updated recently.

**Comment by Amplifiyer** [comment]
@davidbiller this has been fixed in the new stable release, please try and let us know if that works.

**Comment by davidbiller** [comment]
> @davidbiller this has been fixed in the new stable release, please try and let us know if that works.

Good Work :)
