### ISSUE TITLE
Kinesis Firehose

### ISSUE THREAD

**Issue by vincekd** [aws-amplify/amplify-js#4287]
** Which Category is your question related to? **
Analytics
** What AWS Services are you utilizing? **
Cognito, Kinesis
** Provide additional details e.g. code snippets **
versions:
```
"aws-amplify": "^1.1.36",
"aws-amplify-angular": "^3.0.11",
```

I'm attempting to send user analytics to a firehose stream from an angular app (running in a browser). However, after creating/setting the IAM policy and configuring amplify, I get the following error in the console when calling `this.amplify.analytics().record(record, "AWSKinesis")`:
```
 [DEBUG] 36:45.265 AWSKineisProvider - Failed to upload records to Kinesis 
ResourceNotFoundException: "Stream test-data under account 0000000000000 not found."
```
The firehose exists and is named correctly. Not sure what the issue is here, except maybe that it's looking for a stream rather than a firehose?

**Comment by jordanranz** [comment]
Hey @vincekd,

Kinesis Firehose is currently not supported in Amplify JS. There is however a PR open for adding support. Here is the PR: https://github.com/aws-amplify/amplify-js/pull/2823

I'll sync with the team to understand what is needed to get this merged in.

**Comment by vincekd** [comment]
Hi Jordan,

Thanks for the response. What's the recommended way to use firehose in the meantime?

**Comment by bonisb** [comment]
@jordanranz I tried to merge this in for months... without any luck. However it's not even my PR, I kept it up to date, so it was mergeable. not anymore tho...

@vincekd It works if you send the events to Kinesis, and create a Firehose with a Kinesis source... that's the workaround

**Comment by jordanranz** [comment]
Hey @bonisb, apologies for the delay here. I'll make sure this is picked up and merged asap.

**Comment by vincekd** [comment]
@jordanranz is there a workaround that doesn't require paying for two aws services?

**Comment by vincekd** [comment]
@jordanranz What is the status on the merge?

**Comment by iartemiev** [comment]
@vincekd The PR has been merged and is currently available in the unstable release, which can be installed with: `yarn add aws-amplify@unstable`

**Comment by jordanranz** [comment]
This has been merged and the docs are [available here](https://aws-amplify.github.io/docs/js/analytics#using-amazon-kinesis-firehose). Closing this issue now. Please open a new issue if you are experiencing any related problems.
