### ISSUE TITLE
Can't find variable: window - aws-amplify-angular with nativescript

### ISSUE THREAD

**Issue by nirmay** [aws-amplify/amplify-js#4288]
**Describe the bug**
I have a simple nativescript app that I am now migrating to use Amplify (auth, storage, interactions). I am following the docs for aws-amplify-angular for angular+nativescript project I am working on.
As the 'aws-amplify-angular' module is loaded, I see following error:

JavaScript error:
file:///node_modules/aws-amplify-angular/dist/src/components/interactions/chatbot/aws-lex-audio.js:549:0: JS ERROR ReferenceError: Can't find variable: window
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: ReferenceError: Can't find variable: window

**To Reproduce**
1. create a simple nativescript [project](https://github.com/nirmay/tns-amplify-angular)
2. follow instruction here to setup amplify-angular.

**Expected behavior**
no error seen.

**Screenshots**
-na-

**Desktop (please complete the following information):**
OS: iOS

**Smartphone (please complete the following information):**

- Device: all

**Amplify context**
- Angular
    "aws-amplify": "^1.2.3",
    "aws-amplify-angular": "^3.1.3",

**Additional context**
none

**Sample code**
-na-

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by jordanranz** [comment]
Amplify JS does not currently support NativeScript. The following issue is tracking this as a feature request: https://github.com/aws-amplify/amplify-js/issues/1035

I will close this issue in favor of the feature request above.

**Comment by arpit2438735** [comment]
As a workaround you can use https://github.com/EddyVerbruggen/nativescript-nodeify library and need to override window value and it will start working.

**Comment by nirmay** [comment]
Thanks @arpit2438735 
but it turns out nativescript-nodeify is broken for latest versions. I tried that first, also attempted to fix it, but that didnt help. Coming back here as relying on tns specific aws-amplify makes more sense for my project.
see [here](https://github.com/EddyVerbruggen/nativescript-nodeify/issues/65),
Thanks anyway,

**Comment by arpit2438735** [comment]
Ahh I see.Actually long back I integrated `aws-amplify` with `nativescript` and it was working perfect but I feel we should have separate plugin for `nativescript` with good support
