### ISSUE TITLE
React Native Auth: sign up with mobile as username fails on Android

### ISSUE THREAD

**Issue by michalgarcarz** [aws-amplify/amplify-js#4290]
**Describe the bug**
Using default authentication with cognito with option: 
How do you want users to be able to sign in? Phone Number
When creating account and providing text instead of phone number on IOS we have a nice error message, on Android simulator / phone we have nothing, end user does not know why account creation does not work.

**To Reproduce**
It's easy:
1. Deploy new react native project (i use expo init) with amplify
2. amplify add auth with default settings and option:
"How do you want users to be able to sign in? Phone Number"
3. On Android simulator (tested version 9, 10) or phone (tested 6,7) launch app and try to sign up, type in username "text", fill in other fields and click sign up button: nothing happens. If you look very closely you will see 1 red pixel near the bottom.

**Expected behavior**
On IOS nice error message is displayed: "Username should be a phone number"

**Screenshots**

**Desktop (please complete the following information):**
It's mobile, react native

**Smartphone (please complete the following information):**
- Device: [android 6 and 7, android simulator 10]

**Amplify context**
    "aws-amplify-react": "^2.5.3",
    "aws-amplify-react-native": "^2.2.3",
    "expo": "^35.0.0",
    "react": "16.8.3",
     Node: 10.16.3 
      npm: 6.9.0 

- Framework (e.g. React, Angular, Vue, React Native)
React Native

- Versions of Amplify you are using
3.15.0 

**Sample code**
```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { withAuthenticator, AmplifyTheme } from 'aws-amplify-react-native';

import Amplify from 'aws-amplify';
import awsExports from './src/aws-exports';

Amplify.configure({
  ...awsExports,
  Analytics: {
    disabled: true
  }
});

const theme = {
  ...AmplifyTheme,
  button: {
    ...AmplifyTheme.button,
    backgroundColor: '#1ab'
  },
  navBar: {
    ...AmplifyTheme.navBar,
    backgroundColor: "#ffc0cb"
  }
};

export default withAuthenticator(function App() {
//export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app4!</Text>
    </View>
  );
}, true, [], null, theme)

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by amhinson** [comment]
@michalgarcarz Are you still experiencing this issue? Would you be able to retry this with the latest version of `aws-amplify-react-native`?
