### ISSUE TITLE
Auth: Cognito UI - lock mobile phone number for a single country

### ISSUE THREAD

**Issue by michalgarcarz** [aws-amplify/amplify-js#4291]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
It's react native app with amplify and cognito user pools. I am using mobile for login and also verification (SMS text message). I would like to lock mobile phone numbers to a single/specific country, so those are not sent to any country (users should be forced to provide single +XX code). Could not find it in Cognito settings nor Amplify UI customisation. Is it correct ? Or maybe it is possible ?
Thanks,

**Comment by jordanranz** [comment]
If you are using Amplify React Native UI components, this is currently not supported. I will go ahead and add this to our React Native improvements backlog. PRs are welcome in the meantime.

**Comment by tannerabread** [comment]
@michalgarcarz Would supporting this through the UI component <Authenticator> for React Native support your use case?

**Comment by tannerabread** [comment]
Hi 👋 Closing this as we have not heard back from you. I think this would be a better question from the UI team, so if you are still experiencing this issue and are in need of assistance, please feel free to open a new issue in [their repo](https://github.com/aws-amplify/amplify-ui).

Thank you!
