### ISSUE TITLE
React Native Hooks - Auth SignIn customisation form - supported ?

### ISSUE THREAD

**Issue by michalgarcarz** [aws-amplify/amplify-js#4293]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito and react native app with hooks
** Provide additional details e.g. code snippets **

In my react native apps with hooks (function based) i already customise UI stylesheet (theme). Now i wanted to customise fields displayed on signUp form:

```
import { withAuthenticator, AmplifyTheme } from 'aws-amplify-react-native';
import Amplify from 'aws-amplify';

const theme = {
  ...AmplifyTheme,
  button: {
    ...AmplifyTheme.button,
    backgroundColor: '#1ab'
  },
  navBar: {
    ...AmplifyTheme.navBar,
    backgroundColor: "#ffc0cb"
  }
};

const signUpConfig = {
  hideAllDefaults: true,
  signUpFields: [
    {
      label: 'Email',
      key: 'username',
      required: true,
      placeholder: 'Email',
      type: 'email',
      displayOrder: 1,
    },
    {
      label: 'Password',
      key: 'password',
      required: true,
      placeholder: 'Password',
      type: 'password',
      displayOrder: 2,
    },
  ],
}

export default withAuthenticator(function App() {
//export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app4-1!</Text>
    </View>
  );
}, true, [{signUpConfig}], null, theme)
```
After adding "[{signUpConfig}]" as argument (last line) i started to get errors:

Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:5716:10 in createFib

Is it supported ? How to customize it for react native hooks app ? (it's easy for react app).

Thanks,

**Comment by jordanranz** [comment]
Hey @michalgarcarz,

Can you try:
```
export default withAuthenticator(function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app4-1!</Text>
    </View>
  );
}, true, null, null, theme, signUpConfig);
```

There seems to be a slight difference in the signature of the `withAuthenticator` for `react` and `react-native`.
