### ISSUE TITLE
Pinpoint CredentialsError when user not logged in

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-js#4295]
I get this error: 
![Simulator Screen Shot - iPhone 11 - 2019-10-30 at 12 14 31](https://user-images.githubusercontent.com/7137361/67853467-e3b64d00-fb0e-11e9-8a4c-f5bd1517b465.png)

So i am on the last stable version of 
 "aws-amplify": "^1.2.4",
 "aws-amplify-react-native": "^2.2.3",

I had this error 6 months ago, there, this message throws only if i was offline. 
So a check if the phone is offline helped me there:

`initAWSServices(isOffline) {
    if (isOffline) {
      Amplify.configure(aws_exports);
      Amplify.configure({
        Analytics: {
          disabled: true
        }
      });
    } else {
      Amplify.configure(aws_exports);
    }
  }`

So, now i updated auth and api. 

So, this is not a user event tracking problem.

i guess this is the startSession event from amplify itself. 
**I only get this error when i am not logged in.** 
When i am not logged in and refresh my simulator, i get this error. 
If i am logged in, and refresh, not. 

So my fix for now is:
```
Amplify.configure({
        Analytics: {
          disabled: true
        }
      });
```

and after singIn

```
Amplify.configure({
        Analytics: {
          disabled: false
        }
      });
```

I guess i cant track all informations about SessionStart than.

**Comment by sammartinez** [comment]
@davidbiller I am unable to reproduce your issue under the newer versions of Amplify. Here is the [gist](https://gist.github.com/sammartinez/0cbb38a7c08e523bf4b8cb5aaa5d56ba) of the Sample App I created to test this. Do you have a hard dependency on needing to use Amplify v1 or can you upgrade to newer versions of Amplify?
