### ISSUE TITLE
Can't reexport the named export 'BREAK' from non EcmaScript module

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-js#4299]
```
node_modules/@aws-amplify/api/node_modules/graphql/index.mjs 49:0-53:205
Can't reexport the named export 'BREAK' from non EcmaScript module (only default export is available)

```

I saw this old issue:
https://github.com/aws-amplify/amplify-js/issues/761

So i tried this with the last expo web version. 

So should it be fixed here or on expo side? 

So i can see that mjs files are allowed at expo webpack config.
https://github.com/expo/expo-cli/pull/1075

**Comment by ashika01** [comment]
@davidbiller Looks like this is something to be handled in consumer webpack config file. https://github.com/graphql/graphql-js/issues/1272#issuecomment-377384574.
