### ISSUE TITLE
Amplify Auth error "null invocation failed due to configuration"

### ISSUE THREAD

**Issue by fzlrhmn** [aws-amplify/amplify-js#4300]
**Which Category is your question related to?**
Auth
**What AWS Services are you utilizing?**
Cognito
**Provide additional details e.g. code snippets**
I am trying to use Auth signin with `aws-exports` configuration. This code is based on the [docs](https://aws-amplify.github.io/docs/js/authentication#configure-your-app)

```js
import Amplify, {Auth} from 'aws-amplify'
import awsconfig from './aws-exports'

Amplify.configure(awsconfig)

Auth.signIn(username)
.then(user => console.log('user: ', user))
.catch(err => console.log('err: ',err));
``` 

I got this error from the code above.
```json
{
    code: "UnexpectedLambdaException",
    name: "UnexpectedLambdaException",
    message: "null invocation failed due to configuration."
}
```

I am not sure what has happened here as I already follow the instruction from the docs. From my understanding, the error came from configuration that is not well configured. I already removed all triggers in Cognito but still no luck.

**Comment by haverchuck** [comment]
@fzlrhmn  It looks like you aren't passing in a password to the signIn function. Are you trying to attempt passwordless login?  If so, how are you attempting this?  If not, have you tried passing in a password?

**Comment by fzlrhmn** [comment]
It is solved, thanks all

**Comment by russelldavis** [comment]
For anyone else finding this and wondering what causes the "null invocation failed due to configuration" error: for me, it was calling `sendCustomChallengeAnswer` (as part of a CUSTOM_AUTH signin flow) without having a `verifyAuthChallengeResponse` lambda trigger set up in the user pool.
