### ISSUE TITLE
Having an error with federated auth and response type as code

### ISSUE THREAD

**Issue by vgaltes** [aws-amplify/amplify-js#4301]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito and Google
** Provide additional details e.g. code snippets **
I'm trying to set up manually a federated auth with Cognito and Google, and to make a custom website for the authentication. If I set up my user pool with an implicit grant and I set up the amplify client with a `responseType="token"` everything works ok. But if I set up the user pool with an Authorization code grant and I set up the amplify client with a `responseType="code"` it doesn't work.

Why is that?

**Comment by sammartinez** [comment]
@vgaltes Do you have a code snippet we can look at? Also, can you provide the versions of Amplify you are using?

**Comment by vgaltes** [comment]
Sure,

I'm configuring Amplify oath like this:
```
,
    oauth: {
      domain: "mydomain.auth.eu-west-1.amazoncognito.com",
      scope : ['phone', 'email', 'profile', 'openid','aws.cognito.signin.user.admin'],
      redirectSignIn: "http://localhost:8080",
      redirectSignOut: "http://localhost:8080",
      responseType: "token"
  }
```
Auth version is 1.4.3, Core version is 1.2.3

**Comment by haverchuck** [comment]
@vgaltes What is the error?

**Comment by ashika01** [comment]
Closing the issue due to inactivity on the issue. If you still have this error, feel free to open a new issue.
