### ISSUE TITLE
callback.associateSecretCode is not a function

### ISSUE THREAD

**Issue by shobhit09** [aws-amplify/amplify-js#4302]
** Which Category is your question related to? **
amazon-cognito-identity-js
** What AWS Services are you utilizing? **
Cognito User Pool
** Provide additional details e.g. code snippets **
I am attempting to get TOTP MFA working with my User Pools.  I am running into the issue " callback.associateSecretCode is not a function" when calling associateSoftwareToken.

**Describe the bug**
MFA is set to ON for the user pool. When a user logs in with username and password, code routes to MFASetup and then calls associateSoftwareToken which in turn return callback.associateSecretCode. The issue is that this callback.associateSecretCode is not defined on the interface IAuthenticationCallback and therefore returns an error

**Sample code**
```
mfaSetup: function(challengeName, challengeParameters) {
		cognitoUser.associateSoftwareToken(this);
	},

	associateSecretCode: function(secretCode) {
		var challengeAnswer = prompt('Please input the TOTP code.', '');
		cognitoUser.verifySoftwareToken(challengeAnswer, 'My TOTP device', this);
	},
```
**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by vanditamathur** [comment]
We are also having this same problem.
Object literal may only specify known properties, and 'associateSecretCode' does not exist in type 'IAuthenticationCallback'

**Comment by sammartinez** [comment]
@shobhit09 I apologize for the late response. Are you still experiencing this issue? Could you provide a code snippet or sample? I'm also curious on why not use the Auth category within `aws-amplify` because we do provide a method, [setupTOTP](https://aws-amplify.github.io/amplify-js/api/classes/authclass.html#setuptotp), in order to get the secret code.
