### ISSUE TITLE
GraphQL mutation with IAM auth from Cognito ID Pool with Google/Facebook

### ISSUE THREAD

**Issue by michalgarcarz** [aws-amplify/amplify-js#4304]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Cognito, AWS AppSync

** Provide additional details e.g. code snippets **
I do use Amplify Identity Pool with Facebook and Google. For authentication to Facebook + Google i do use expo modules (yes - it's react native for Android/IOS).

- once Facebook auth is success i do pass idToken to Auth.federatedSignIn() and got AWS credentials
- once Google auth is success (i need to use openconnct id because of multiple app id) i do pass idToken to AWS.CognitoIdentityCredentials() and again got AWS credentials

Now how can i use those credentials to call my graphql mutation ?

I have created mutation like this:
```
type Car @model @auth(rules: [{allow: private, provider: iam}]) {
  id: ID!
  description: String
}
```

I've made sure that my IAM role which was created by Amplify automatically (used IAM auth model) and having AppSync permissions is assumed automatically for my Cognito identity pool users:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "cognito-identity.amazonaws.com"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "cognito-identity.amazonaws.com:aud": "eu-central-1:de11aea1-6ca6-4f74-9953-97b0f7xxxxx"
        },
        "ForAnyValue:StringLike": {
          "cognito-identity.amazonaws.com:amr": "authenticated"
        }
      }
    }
  ]
}
```

So every time my identity pool users which have authenticated correctly with google/facebook should assume above role and have the right to call AppSync(mutation). Confirmed that role is having AppSync permissions:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "appsync:GraphQL"
            ],
            "Resource": [
                "arn:aws:appsync:eu-central-1:668493088669:apis/xhwqx3cgj5hzdetqlz25vayx7q/types/Car/*",
                "arn:aws:appsync:eu-central-1:668493088669:apis/xhwqx3cgj5hzdetqlz25vayx7q/types/Mutation/fields/createCar",
           <subsequent arns removed for clarity>
            ],
            "Effect": "Allow"
        }
    ]
}
```
But i do receive error 401 when calling my mutation.

What am i missing ?

Should i activate received AWS credentials in my session somehow to make sure i am sending right headers when calling that mutation ?

Some pieces of the code:
```
//auth with Google via expo
const { type, idToken, accessToken, user } = await Google.logInAsync(GoogleConfig);

//getting AWS credentials using received idToken
AWS.config.region = 'eu-central-1';
        AWS.config.credentials = new AWS.CognitoIdentityCredentials({
          IdentityPoolId: awsmobile.aws_cognito_identity_pool_id,
          Logins: {
            'accounts.google.com': idToken 
          }
        })

//a bit later just calling my mutation:
const result = await API.graphql(graphqlOperation(createCar, { input: Car }));
```

Thanks,
Michal

**Comment by Graig123git** [comment]
was this issue resolved and if so where can i find the proposed solution ?

**Comment by mauerbac** [comment]
hi @Graig123 & @michalgarcarz -- was this issue resolved?
