### ISSUE TITLE
Amplify Auth and user's groups

### ISSUE THREAD

**Issue by artecoop** [aws-amplify/amplify-js#4306]
** Which Category is your question related to? **
Authentication via Cognito

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
Create a new project with amplify and add auth. Be sure to select cognito as authentication method. Once deployed with `amplify push` go to the Cognito console, select the newly created user pool and create a user and a group. Now add the user to your group.

Back on your app, import amplify-js and do the ritual setup of framework of your choice.
How to retrieve the group a logged in user is in?

```
import { Auth } from 'aws-amplify';
...
const user =  await Auth.currentAuthenticatedUser();
```
does not contain such information

Thanks in advance!

**Comment by sammartinez** [comment]
In seeing the above callout, I am going to resolve this since you were able to resolve your issue.

**Comment by arhoy** [comment]
During sign up I am trying to sign users up into different groups.
How can I do this in aws amplify?

Thank you!

**Comment by TheSilentDev** [comment]
@arhoy this can be done with a post confirmation trigger:

```
export function postConfirmationTrigger(event, context, callback) {
  const params = {
    GroupName: "BasicUsers",
    UserPoolId: event.userPoolId,
    Username: event.userName
  };

  CognitoIdentityServiceProvider.adminAddUserToGroup(params)
    .promise()
    .then(res => callback(null, event))
    .catch(err => callback(err, event));
}
```

**Comment by LucasAndrad** [comment]
Shouldn't this be documented somewhere?

**Comment by wbrijesh** [comment]
> During sign up I am trying to sign users up into different groups.
> How can I do this in aws amplify?
> 
> Thank you!

run amplify update auth
select walkthrough all options
add group here and configure add users to group for that group

**Comment by SalahAdDin** [comment]
> Shouldn't this be documented somewhere?

Was it?

**Comment by wbrijesh** [comment]
If it was I couldn't find it, anyways this creates the lambda function to add new users to a group
