### ISSUE TITLE
NotConfirmedException instead of UserNotFoundException while login

### ISSUE THREAD

**Issue by ricardoribas** [aws-amplify/amplify-js#4307]
**Describe the bug**
Based on the documentation of [authentication module](https://aws-amplify.github.io/docs/js/authentication), if a user sign up with some attributes and didn't confirm the account, the next time he tries to login with wrong credentials, you should get an **UserNotFoundException** error instead of a **NotConfirmedException**. 

**To Reproduce**
1. Create an account with `Auth.signUp`
2. After a successful response, you are redirected to the **ConfirmUser** screen don't confirm the account (by mistake, and so on...)
3. Go to the **SignUp** screen
4. Put the right username **BUT** the wrong password
5. You get a not confirmed error instead of wrong credentials

**Expected behavior**
Return wrong credentials error instead of a not confirmed error.

**Additional context**
I am using the following amplify versions:
"amazon-cognito-identity-js": "^3.0.15",
"aws-amplify": "^1.1.40",
"aws-amplify-react-native": "^2.1.19",

**Comment by Amplifiyer** [comment]
@ricardoribas, what is the latest amplify version have you tried that failed with the same error? We have recently fixed this issue. Can you paste your package.json here?

**Comment by ricardoribas** [comment]
I am using the following amplify versions:
"amazon-cognito-identity-js": "^3.0.15",
"aws-amplify": "^1.2.4",
"aws-amplify-react-native": "^2.2.3

**Comment by Amplifiyer** [comment]
@ricardoribas, I just tried and I was able to get the right exception with the same username and correct or incorrect password where the username was never confirmed.
```
{code: "UserNotConfirmedException", name: "UserNotConfirmedException", message: "User is not confirmed."}
```

Can you post your code samples and network request/responses for us to debug better? Please also enable **debug** logs in Amplify with https://aws-amplify.github.io/docs/js/logger and paste the logs here as well.

**Comment by ricardoribas** [comment]
Perhaps was a decision that you guys have made. For the same scenario, but with a wrong password, make sense to return a not confirmed exception? Cause afterall, if you put wrong credentials, this kind of error should have more priority than the other one. Make sense to you?

**Comment by Amplifiyer** [comment]
@ricardoribas, I didn't understand you completely. As mentioned in the [documentation](https://aws-amplify.github.io/docs/js/authentication#common-authentication-use-cases) if a username/email is not confirmed, the next time user tries to log in with that user name (irrespective of the password since the account is not yet active) will get the exception UserNotConfirmedError.

**Comment by ricardoribas** [comment]
So, regardless of right or wrong credentials, you get that exception. Alright, thank you so much for you support.
