### ISSUE TITLE
As of @aws-amplify/core@1.2.3, React Native-specific source files are not being used.

### ISSUE THREAD

**Issue by dubchoi** [aws-amplify/amplify-js#4309]
**Describe the bug**
Build system changes seem to have broken "React Native"-specific source files from being used.
For example, I can confirm https://github.com/aws-amplify/amplify-js/blob/master/packages/core/src/StorageHelper/index.ts (Incorrect) is being used instead of https://github.com/aws-amplify/amplify-js/blob/master/packages/core/src/StorageHelper/reactnative.ts (Correct)

Seems to affect many other files.

**To Reproduce**

1. Open an expo react native project.
2. Depend on amplify core version 1.2.3 or greater.
3. Build and run (I used iOS simulator), debug source code and find that **/reactnative.ts files are not being included.

4. Depend on amplify core version 1.2.2 or lower.
5. Build and run, debug source code and find that **/reactnative.ts files are used. 

**More details**
Seems to cause, among other things, https://github.com/aws-amplify/amplify-js/issues/4272
The solution presented there of using a custom storage (obviating the incorrect selection of source file above) only seems to mask the bigger build issue.

I'm not familiar with web / react native build system to pinpoint the problem, but would guess something in https://github.com/aws-amplify/amplify-js/pull/4007 caused this.

**Comment by ChrisLFieldsII** [comment]
I am noticing this problem as well. My project is now erroring out on a `Cache.setItem().then()` call in react-native and I noticed the BrowserStorage is used instead of AsyncStorage which returns a Promise.
