### ISSUE TITLE
Occasional 504 and 403(service worker) errors when using Api with Signature V4

### ISSUE THREAD

**Issue by Jun711** [aws-amplify/amplify-js#4312]
**Describe the bug**
I am using `API.post('apiPath', path, init)` to sign requests with Signature V4 and send to an Edge optimized API endpoint created using API Gateway(AWS_IAM authorization).

When this error happens, the request ends up with 504 error. And on Chrome Network tab, the same request that has a gear next to it(I assume it is managed by a service worker) has 403 error. 

For the same user, it may happen on one of his devices but works on other devices. So, the user is definitely not disabled on Cognito. 

**To Reproduce**
I don't have specific steps to reproduce it as it happens to some of my users. It works most of the time for most users thus, the code is ok. 

I opened this issue to see if anyone else experiences the same. 

**Expected behavior**
Expected api requests to complete successfully every time

**Devices Affected**
Mostly Chrome 77 on Windows 10
but it happens on Chrome 77 on Mac OS too

**Comment by ericclemmons** [comment]
This should be fixed via https://github.com/aws-amplify/amplify-js/pull/5869!
