### ISSUE TITLE
Storage upload progress callback not called

### ISSUE THREAD

**Issue by michalgarcarz** [aws-amplify/amplify-js#4316]
** Which Category is your question related to? **
Storage
** What AWS Services are you utilizing? **
Storage
** Provide additional details e.g. code snippets **
This is react native app, i use Storage.put() to upload files which are ~500KB in size (and it takes 4-5 seconds to upload those). I have never seen callback function executed for progress, code:

```
response = await Storage.put(filename, blob, {
                    level: 'private',
                    contentType: 'image/png'
                }, {
                    progressCallback(progress) {
                        console.log(`Uploading progress: ${progress.loaded}/${progress.total}`);
                    }
                });
```

Amplify 1.2.4.

When/how often should the callback be executed ?
I have never seen it running....
Please confirm  plus provide the details.

Thanks,

**Comment by juuyan** [comment]
Any update? I have the same issue now... The callback is only executed after finishing the uploading.

**Comment by amhinson** [comment]
This should be fixed in the latest release (v3) of `aws-amplify`. Would you be able to test it out and see you're seeing the same issue?
