### ISSUE TITLE
The documentation theme is hard to read and look at, light orange and white are not a great color combo.

### ISSUE THREAD

**Issue by ajhool** [aws-amplify/amplify-js#4318]
**Is your feature request related to a problem? Please describe.**
The documentation is hard to read due to the theme (white text on light orange). Links are light orange on a white background. 

**Describe the solution you'd like**
Not light orange. Dark orange. Dark blue, black, normal high-contrast documentation colors. The new scheme in the other AWS documentation is nice.

**Describe alternatives you've considered**
Firebase

**Additional context**

**Comment by Ashish5591** [comment]
@nikhil-dabhade Some feedback to consider when updating the docs site.

**Comment by jordanranz** [comment]
The documentation site has been updated: https://docs.amplify.aws/

Feel free to open a new issue on the docs repo if you have any further questions or concerns:
https://github.com/aws-amplify/docs/issues

**Comment by ajhool** [comment]
@jordanranz Looks great and is incredibly fast.
