### ISSUE TITLE
Catch Error during federatedSignIn (handleAuthResponse) in Angular

### ISSUE THREAD

**Issue by adgrace** [aws-amplify/amplify-js#4319]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **

I am using Amplify within Angular.
I have implemented a pre-sign up hook that declines certain users. When this hook is triggered during the federatedSignIn flow it redirects to google/facebook and then on the return the url is:
http://localhost:4200/auth-return?error_description=PreSignUp%20failed%20with%20error%cognito_presignup_custom_error.%20&state=state_code&error=invalid_request

And I have the following error message:
Unhandled Promise rejection: PreSignUp+failed+with+error+cognito_presignup_custom_error.+ ; Zone: <root> ; Task: Promise.then ; Value: Error: PreSignUp+failed+with+error+cognito_presignup_custom_error.+
at OAuth.<anonymous> (OAuth.js:201)
    at step (OAuth.js:52)
    at Object.next (OAuth.js:33)
    at OAuth.js:27
    at new ZoneAwarePromise (zone-evergreen.js:876)
    at push../node_modules/@aws-amplify/auth/lib/OAuth/OAuth.js.__awaiter (OAuth.js:23)
    at OAuth.push../node_modules/@aws-amplify/auth/lib/OAuth/OAuth.js.OAuth.handleAuthResponse (OAuth.js:181)
    at AuthClass.<anonymous> (Auth.js:1631)
    at step (Auth.js:44)
    at Object.next (Auth.js:25) Error: PreSignUp+failed+with+error+cognito_presignup_custom_error.+
    at OAuth.<anonymous> (http://localhost:4200/vendor.js:111247:35)
    at step (http://localhost:4200/vendor.js:111098:23)
    at Object.next (http://localhost:4200/vendor.js:111079:53)
    at http://localhost:4200/vendor.js:111073:71
    at new ZoneAwarePromise (http://localhost:4200/polyfills.js:3920:29)
    at push../node_modules/@aws-amplify/auth/lib/OAuth/OAuth.js.__awaiter (http://localhost:4200/vendor.js:111069:12)
    at OAuth.push../node_modules/@aws-amplify/auth/lib/OAuth/OAuth.js.OAuth.handleAuthResponse (http://localhost:4200/vendor.js:111227:16)
    at AuthClass.<anonymous> (http://localhost:4200/vendor.js:110809:65)
    at step (http://localhost:4200/vendor.js:109222:23)
    at Object.next (http://localhost:4200/vendor.js:109203:53)

Any thoughts on how I can catch this error?

**Comment by rafaponieman** [comment]
I'm having the exact same problem in React.

**Comment by calarconpieriz** [comment]
Same problem in angular. I've tried lots of different configurations and still not able to make it work.

**Comment by ianmartorell** [comment]
Wow, no answers? :(

**Comment by ianmartorell** [comment]
Apparently you can catch the error with `Hub.listen`, but you have to register the callback before the `Auth` module processes the result from the redirect. Calling `Hub.listen` before `Amplify.configure` and logging the payload I got this in the console:

```javascript
{
  "event":"parsingCallbackUrl",
  "data":{
    "url":"http://localhost:19006/dash/?error_description=PreSignUp+failed+with+error+LINKED_EXTERNAL_USER%3A+Google.+&state=KustOP4fqhIPA9ckz226D9Qk7Wt27zr5&error=invalid_request"
  },
  "message":"The callback url is being parsed"
}

[ERROR] 19:26.131 OAuth - Error handling auth response. Error: PreSignUp+failed+with+error+LINKED_EXTERNAL_USER%3A+Google.+
    at OAuth.<anonymous> (OAuth.js:236)
    at step (OAuth.js:55)
    at Object.next (OAuth.js:36)
    at OAuth.js:30
    ...

{
  "event":"configured",
  "data": null,
  "message":"The Auth category has been configured successfully"
}

{
  "event":"signIn_failure",
  "data":{ // Error object
    message: "PreSignUp+failed+with+error+LINKED_EXTERNAL_USER%3A+Google.+",
    stack: "Error: PreSignUp+failed+with+error+LINKED_EXTERNAL_USER%3A+Google..."
  },
  "message":"The OAuth response flow failed"
}

{
  "event":"cognitoHostedUI_failure",
  "data":{ // Error object
    message: "PreSignUp+failed+with+error+LINKED_EXTERNAL_USER%3A+Google.+",
    stack: "Error: PreSignUp+failed+with+error+LINKED_EXTERNAL_USER%3A+Google..."
  },
  "message":"A failure occurred when returning to the Cognito Hosted UI"
}

{
  "event":"customState_failure",
  "data":{ // Error object
    message: "PreSignUp+failed+with+error+LINKED_EXTERNAL_USER%3A+Google.+",
    stack: "Error: PreSignUp+failed+with+error+LINKED_EXTERNAL_USER%3A+Google..."
  },
  "message":"A failure occurred when returning state"
}
```

**Comment by danielvouch** [comment]
Is there any update on this issue?

**Comment by kennedyjustin** [comment]
For anyone trying to get this to work with Next.js:

`_app.js`
```
import "../styles/globals.css";
import type { AppProps } from "next/app";
import type { ReactElement, ReactNode } from "react";
import type { NextPage } from "next";
import { AuthProvider } from "../hooks/auth";

type NextPageWithLayout = NextPage & {
  getLayout?: (page: ReactElement) => ReactNode;
};

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
};

function MyApp({ Component, pageProps }: AppPropsWithLayout) {
  const getLayout = Component.getLayout ?? ((page) => page);
  return getLayout(
    <AuthProvider>
      <Component {...pageProps} />
    </AuthProvider>
  );
}

export default MyApp;
```

In your AuthProvider:
```
// Note: must be a global var so Amplify is configured once
let amplifyConfigured = false;

export function AuthProvider({ children }: { children: ReactNode }) {
  ...

  useEffect(() => {
    if (!amplifyConfigured) {
      Amplify.configure(<config>);
      amplifyConfigured = true;
    }
    const unsubscribe = Hub.listen("auth", ({ payload: { event, data } }) => {
      switch (event) {
        case "signIn":
          router.push("/");
          break;
        case "cognitoHostedUI_failure":
          setLoginWithAmazonError("Error using Login with Amazon.");
          break;
      }
    });

    return unsubscribe;
  });
```

**Comment by nuwans** [comment]
Did anyone find a solution yet?

**Comment by nadetastic** [comment]
Hi @nuwans,

As described by @ianmartorell, using Hub here will allow you to catch this error and perform the action you would like.

For example, if I want to display an alert:
```js
import { Hub } from 'aws-amplify'

Hub.listen('auth', (data) => { 
    if (data.payload.event === 'signIn_failure') {
        alert(data.payload.data.message);
    }
})

**Comment by nadetastic** [comment]
The documentation has been updated to show to reflect the above:
- https://docs.amplify.aws/lib/auth/social/q/platform/js/#catching-errors
