### ISSUE TITLE
Unable to make an authenticated call using OAuth scopes

### ISSUE THREAD

**Issue by vgaltes** [aws-amplify/amplify-js#4320]
**Describe the bug**
I have a user pool configured with a resource server and using Google as federated identity provider. I'm able to login and make a call to a secured endpoint using the IdToken. But when I switch to AccessToken the call returns a 401.

**To Reproduce**
Create a User Pool using Google as federated identity provider.
Create a Resource Server there, in my case the identifier is product-api and the scope read_product.
Configure the app client settings to use google, use oauth, use the custom scopes, and use implicit grant.
Configure the API Gateway so that the authoriser has the scopes configured
Create an amplify client (manually, no CLI) that connects to that user pool and authenticates via Google. I get back an access token with the right scopes, including the custom one.
Make a call to the endpoint using the AuthToken (I've checked that the token has the right scopes)

![image](https://user-images.githubusercontent.com/862679/68019195-fbb6d980-fc92-11e9-9fcf-530e8df8a8cf.png)

![image](https://user-images.githubusercontent.com/862679/68019229-096c5f00-fc93-11e9-998d-1f2bd1718b17.png)

![image](https://user-images.githubusercontent.com/862679/68019271-29038780-fc93-11e9-8488-9b518cca6092.png)

This is the token used by Amplify making the call:
```
{
  "sub": "6e1c82ca-b7d7-4bc5-9ae2-873aadf3656c",
  "cognito:groups": [
    "eu-west-<userPoolId>_Google"
  ],
  "token_use": "access",
  "scope": "aws.cognito.signin.user.admin product-api/delete_product openid product-api/read_product email",
  "auth_time": 1572602140,
  "iss": "https://cognito-idp.eu-west-1.amazonaws.com/<userPoolId>",
  "exp": 1572605740,
  "iat": 1572602140,
  "version": 2,
  "jti": "<jti>",
  "client_id": "<client_id>",
  "username": "Google_117107248650209375973"
}
```

This is how I configure Amplify (the oauth bits):
```
oauth: {
  domain: "<mydomain>.auth.eu-west-1.amazoncognito.com",
  scope : ['phone', 'email', 'profile', 'openid','aws.cognito.signin.user.admin', 'product-api/read_product'],
  redirectSignIn: "http://localhost:8080",
  redirectSignOut: "http://localhost:8080",
  responseType: "token"
}
```

This is how I make the call:
```
RequestToSecuredEndpointButton.addEventListener('click', async evt => {
  let myInit = { 
    headers: { Authorization: `Bearer ${(await Auth.currentSession()).getAccessToken().getJwtToken()}` }
  }
  
  await API.get("MyAPIGatewayAPI", '/dev/api/helloWorldSecured', myInit).then(response => {
      console.log(response);
  }).catch(error => {
      console.log(JSON.stringify(error))
  });
});
```

**Expected behavior**
I expect the call to success

<details>
  <summary><strong>Environment</strong></summary>System:
    OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 1.94 GB / 15.54 GB
    Container: Yes
    Shell: 5.4.2 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
  npmPackages:
    aws-amplify: ^1.2.2 => 1.2.3 
    copy-webpack-plugin: ^4.5.2 => 4.6.0 
    webpack: ^4.17.1 => 4.41.2 
    webpack-cli: ^3.1.0 => 3.3.9 
    webpack-dev-server: ^3.1.5 => 3.9.0 
  npmGlobalPackages:
    @aws-amplify/cli: 3.12.0
    npm: 6.12.0
</details>

**Comment by elorzafe** [comment]
@vgaltes what is your api config on Amplify (specially the end of the url). I think the path that you are specifying can have some overlapping with the endpoint.

I followed the same steps you mention and it works for me using access token. That is why I think it could be an issue with the endpoint that is configured on Amplify.
