### ISSUE TITLE
callback.totpRequired is not a function

### ISSUE THREAD

**Issue by AlpacaGoesCrazy** [aws-amplify/amplify-js#4321]
**Describe the bug**
Authenticator crashes when user is trying to complete reset password with MFA enabled

**To Reproduce**

1. Has MFA enabled
2. Has `FORCE_CHANGE_PASSWORD` state
3. Using `withAuthenticator` from aws-amplify-react try to log in
4. Enter new password
5. Observe error

**Expected behavior**
MFA triggers after reseting password, and after entering valid MFA code user logs in.
(Or maybe MFA should trigger before reseting password?)

**Screenshots**
![Screen Shot 2019-11-01 at 4 06 24 PM](https://user-images.githubusercontent.com/17003704/68030245-ab0aa500-fcc1-11e9-86bf-ba3a8d067983.png)

<details>
  <summary><strong>Environment</strong></summary>
```
aws-amplify: 1.2.4
aws-amplify-react: 2.5.4
```
</details>

**Comment by anands-gr** [comment]
I'm also having this issue using the `amazon-cognito-identity-js` package. It's currently not possible for users to reset their MFA after resetting their password.

**Comment by ericclemmons** [comment]
This is interesting.  I'm attempting to reproduce this based on https://aws-amplify.github.io/docs/js/authentication#letting-user-select-mfa-type and when I go through the reset password steps I also receive the _New Password_ prompt alongside the MFA code prompt:

> <img width="489" alt="Screen Shot 2020-01-28 at 8 34 22 AM" src="https://user-images.githubusercontent.com/15182/73284378-559f4080-41a9-11ea-9919-64c8c1942024.png">

Can you share how the MFA is set for users?  Or is MFA optional?

**Comment by ericclemmons** [comment]
@AlpacaGoesCrazy Can you share steps on how the user got created & into the `FORCE_CHANGE_PASSWORD` state?

**Comment by sammartinez** [comment]
Resolving as this fixed within our new UI Component implementation. Please let us know if you are still experiencing this issue and we can reopen. Thanks!

**Comment by BatelLuzon** [comment]
Hi
We use Cognito without the UI component, and having this issue (2fa required, user can't reset their passwords). Any chance this will be fixed in Cognito server and not the UI component?
