### ISSUE TITLE
AWS Amplify + Ionic React + Push Notification

### ISSUE THREAD

**Issue by olavocarvlho** [aws-amplify/amplify-js#4337]
** Which Category is your question related to? **
Push
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
Is that possible to integrate aws amplify with ionic react to use push notifications?

**Comment by Ashish5591** [comment]
As of right now amplify-js supports push notifications for react native only. 

However if you think this is a feature we should support, you can open a  [feature request](https://github.com/aws-amplify/amplify-js/issues/new?assignees=&labels=feature-request&template=feature_request.md&title=) for it using the template provided. This will allow people from the community to weigh in as well and we can prioritize it accordingly.
