### ISSUE TITLE
Authenticator Form is not accessible

### ISSUE THREAD

**Issue by iamstratos** [aws-amplify/amplify-js#4338]
**Describe the bug**
The links in the React's Authenticator form are not accessible. The user cannot navigate in the form links using the keyboard's `tab` button.
For example, on the Sign In, the links `Reset password` or `Create account` are not accessible.

**Expected behavior**
The user should be able to access all the links in the form with the `tab` button.

**Screenshots**
<img width="500" alt="Screenshot 2019-11-04 at 16 53 55" src="https://user-images.githubusercontent.com/5058640/68135787-83674700-ff24-11e9-9c09-54ee7fcbdb1b.png">

**Additional context**
Added an `href=""` to the links will make them accessible.

**Comment by Ashish5591** [comment]
Hi

Could you share which framework's authenticator component you encountered this issue with (eg. React, Angular)?

**Comment by iamstratos** [comment]
> Hi
> 
> Could you share which framework's authenticator component you encountered this issue with (eg. React, Angular)?

Hey, I'm using React!

**Comment by iamstratos** [comment]
No solutions found so far and it's a critical issue. We cannot continue using Amplify if it's not fixed :/

**Comment by sammartinez** [comment]
@iamstratos We are looking to get this prioritize, I will let you know that we are open to Pull Requests if you wanted to create one for this. In the meantime, know this is in our backlog with high priority.

**Comment by sammartinez** [comment]
Resolving issue as this is now part of our new UI Components. Please let us know if you are experiencing any issues with the newer implementation and we can reopen this issue. Thanks!

**Comment by sawyerh** [comment]
@sammartinez It would be great if a fix could still be published for `aws-amplify-react` for projects that aren't yet able to migrate to `@aws-amplify/ui-components`, which isn't 1:1 in terms of feature parity. It _looks_ like #4692 would fix the issue described here. I'd also be happy to open up a separate, smaller PR that only changes `aws-amplify-react` if that would get this fixed sooner.
