### ISSUE TITLE
Subscriptions do not work while using authmode

### ISSUE THREAD

**Issue by emmafass** [aws-amplify/amplify-js#4350]
### Which Category is your question related to? 
API

### What AWS Services are you utilizing?
AppSync

### Provide additional details e.g. code snippets 
I am following the documentation [here](https://aws-amplify.github.io/docs/js/api#aws-appsync-multi-auth) to perform `createTodo` using authmode. 

```
const createdTodo = await API.graphql({
  query: queries.createTodo,
  variables: {input: todoDetails},
  authMode: 'AWS_IAM'
});
```

This works. However, my subscriber is not recognizing that a `createTodo` event occurred. 

```
this.createTodoListener = API.graphql(graphqlOperation(onCreateTodo, {owner: this.state.user.username})).subscribe({
            next: todoData => {
                console.log(todoData);
            } 
});
```

Does this have to do with using `graphql()` with and without the `graphqlOperation` function?

When I tried to change the mutation's authmode to AMAZON_COGNITO_USER_POOLS, I get

`Not Authorized to access createTodo on type Todo`

I set up my auth modes through the CLI `amplify auth update` command. The default mode is Cognito User Pools and the additional mode is API Key.

<img width="860" alt="Screen Shot 2019-11-05 at 6 04 00 PM" src="https://user-images.githubusercontent.com/13208951/68253798-e3c6b900-fff6-11e9-808c-56a5150468dd.png">

<img width="851" alt="Screen Shot 2019-11-05 at 6 04 09 PM" src="https://user-images.githubusercontent.com/13208951/68253802-e75a4000-fff6-11e9-9733-0290eac55e22.png">

**Comment by emmafass** [comment]
@Ashish5591 wondering if you have any insight into this?

**Comment by tfendt** [comment]
I am also having an issue subscribing.

`useEffect(() => {
    try {
      const subscription = API.graphql(graphqlOperation(onCreateUser, {owner: Auth.currentAuthenticatedUser()})).subscribe({
        next: data => {
          const user = data.value.data.onCreateUser;
          dispatch({type:'SUBSCRIPTION', user});
        },
        error: error => {
          console.log(error);
        }
      })
      return () => subscription.unsubscribe();
    } catch(error) {
        console.log(error);
    }
  }, []);`

**Comment by tfendt** [comment]
I got it to work with the following but it doesn't feel like the proper solution:
```
let loggedInUser = "";
  const fetchUser = async () => {
    try {
      loggedInUser = await Auth.currentAuthenticatedUser();
    } catch(error){
      console.error(error)
    }
  }
  fetchUser();

const subscription = API.graphql(graphqlOperation(onCreateUser, {owner: loggedInUser.username})).subscribe({
        next: data => {
          const user = data.value.data.onCreateUser;
          dispatch({type:'SUBSCRIPTION', user});
        },
        error: error => {
          console.log(error);
        }
      })
```

**Comment by undefobj** [comment]
This should be fine. Essentially when doing a subscription you're asking for events on a "channel" which is defined by the arguments which are passed in, and validation is done in the service against the authentication data in the JWT (which is digitally signed to prevent tampering). So if "Suzy" passes in an owner of "Joe" the subscription resolver will fail that server side check while if she passes in her correct username it will validate.
