### ISSUE TITLE
Unable to resolve module ../vendor/paho-mqtt

### ISSUE THREAD

**Issue by daanoz** [aws-amplify/amplify-js#4352]
**Describe the bug**
Missing file reference when bundeling the code. Bundling is done by React Native on the latest version.

```
error: bundling failed: Error: Unable to resolve module ../vendor/paho-mqtt from node_modules/@aws-amplify/pubsub/lib/Providers/MqttOverWSProvider.js:

None of these files exist:

node_modules/@aws-amplify/pubsub/lib/vendor/paho-mqtt(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
node_modules/@aws-amplify/pubsub/lib/vendor/paho-mqtt/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
```

Started happening from version `1.2.4`, version `1.2.3-unstable.0` is fine.

**Comment by Amplifiyer** [comment]
@daanoz, can you try deleting your node_modules and lock file and trying again? paho library is now consumed as an npm package and the cached file `../vendor/paho-mqtt` has been removed in favor of it. Please ensure you are using latest version of `@aws-amplify/pubsub`

**Comment by daanoz** [comment]
Ah, clear! Thx for the support. I removed the `node_modules` before, but not the `package-lock.json`, that proved to be the culprit.
Everything ok now.
