### ISSUE TITLE
Offline cache not authorized

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/amplify-js#4356]
**Describe the bug**
I have enabled offline access with cache storage with amplify & appsync. And only owner can access their own records not other users records. But after changing user by loggin out & logging in. Every user can access cached records even if they are not authorized to view those records. Also I am using withAuthenticator for login.

**To Reproduce**

1. Create React App
2. Amplify init
3. Amplify add api (with cognito auth) with following schema
```
type Todo @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  name: String!
}
```
4. Setup client
```
const client = new AWSAppSyncClient({
  url: awsconfig.aws_appsync_graphqlEndpoint,
  region: awsconfig.aws_appsync_region,
  auth: {
    type: AUTH_TYPE.AMAZON_COGNITO_USER_POOLS,
    jwtToken: async () => (await Auth.currentSession()).getAccessToken().getJwtToken()
  },
  disableOffline: false,
  offlineConfig: {
    storage: localForage
  }
})
```
5. Setup Query
```
 await client.query({ query: gql(listTodos) })
```
**Expected behavior**
Every user can only access their own records. Not other people's records.

**Comment by jkeys-ecg-nmsu** [comment]
Yikes.

**Comment by undefobj** [comment]
@apoorvmote Apollo cache is just a cache, the authorization has already happened at the service layer and is global to the client and is how the Apollo client stores it's records keyed by query. If you'd like to have multiple users logging in you should clear the cache on logout (or new user login, depending on your business logic) and have it rehydrate using the new credentials.

Here is an example of doing this: https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/49#issuecomment-366824731

It also looks like Apollo has `client.clearStore()` which might work as well.
