### ISSUE TITLE
AppStorage and NetInfo deprecated if imported from 'react-native'

### ISSUE THREAD

**Issue by RadoAz** [aws-amplify/amplify-js#4359]
**Describe the bug**

**To Reproduce**

-- or --

Link to sample code

**Expected behavior**

**Screenshots**

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

</details>

**Smartphone (please complete the following information):**

**Additional context**

**Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by sammartinez** [comment]
@RadoAz Can you please provide your `package.json` so we can verify which versions of `aws-amplify` you are experiencing this on. Also can you please fill in the template above with steps to reproduce and screenshots of the messages you may be receiving. Thanks ahead of time!
