### ISSUE TITLE
please update amplify modules to be adapted with new versions of react-native, android and ios because there are issues that is solved by changing in the module itself

### ISSUE THREAD

**Issue by AhmedMesawer** [aws-amplify/amplify-js#4360]
When I want to build signed APK it gives me this error
```
> Task :@aws-amplify_pushnotification:verifyReleaseResources FAILED
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':@aws-amplify_pushnotification:verifyReleaseResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
```

I found that when I change SDK version in node_modules\@aws-amplify\pushnotification\android\build.gradle from 26 to 28
```
compileSdkVersion 26 -> 28
    buildToolsVersion "26.0.3" -> "28.0.3"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 26 -> 28
        versionCode 1
        versionName "1.0"
    }
```

**Comment by sammartinez** [comment]
@AhmedMesawer Can you please fill out the request within the issue itself? I'm seeing the placeholder information within the issue itself. Thanks ahead of time!

**Comment by bneigher** [comment]
I've been having to do this manually for the past 4 months every time I update my node_modules.  Why isn't aws testing against the current RN version?

**Comment by AhmedMesawer** [comment]
This issue is urgent because it is failing our ci build process for android apps

**Comment by amhinson** [comment]
Closing this issue, as it has been addressed in https://github.com/aws-amplify/amplify-js/pull/5475.
