### ISSUE TITLE
Does aws-amplify-angular have <amplify-set-mfa>UI component for Angular projects?

### ISSUE THREAD

**Issue by andrew-aernos** [aws-amplify/amplify-js#4362]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
aws-amplify-angular
** Provide additional details e.g. code snippets **
Spotted <amplify-set-mfa>for Vue project Just wondering if there is a equivalent one in aws-amplify-angular

**Comment by jordanranz** [comment]
Hey @andrew-aernos,

There is currently no `amplify-set-mfa` or `amplify-select-mfa` components for Angular. This will most likely come with our UI component refactor explained in [this RFC](https://github.com/aws-amplify/amplify-js/issues/3279).

**Comment by jordanranz** [comment]
There is now a select mfa component in Angular:
https://docs.amplify.aws/ui/auth/select-mfa-type/q/framework/angular

Please open a new issue if you have any related questions or concerns.
