### ISSUE TITLE
How to call lambda after logged-in by Cognito

### ISSUE THREAD

**Issue by thundermiracle** [aws-amplify/amplify-js#4363]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Cognito, Lambda

** Provide additional details e.g. code snippets **
I want to call lambda functions if the logged-in user is in the right Cognito group.
So I created a group in Cognito which has lambda:invoke role.
And I added the relative users to the group too.
But I can't find out how to get the proper credentials to invoke the lambda functions.
And no document can be found.

Would you please tell me how to do this?  😢

**Comment by thundermiracle** [comment]
It seems that I can only bind user pool with identity pool and use ```Auth.currentCredentials()``` to get the credentials.
Am I right?

**Comment by haverchuck** [comment]
@thundermiracle Is there a problem with using Auth.currentCredentials()?

**Comment by thundermiracle** [comment]
@haverchuck 
I’m not familiar with the definition of group in Cognito and thought that Auth.currentCredential() can get permissions after adding a user to a group.

I didn’t figure it out yet, but that’s ok.
Thanks for your time.
