### ISSUE TITLE
Get Auth Code on User Pool Sign In when hosted UI is NOT used

### ISSUE THREAD

**Issue by gauravchaddha** [aws-amplify/amplify-js#4366]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito

I have a custom Auth UI for my app and am not using hosted UI.
When user authenticates with Social IdPs then the **auto code** is returned in the URL fragment in the redirect. 
However, if user is authenticated programmatically (without hosted UI), then **auth code** is not received on successful login. Instead tokens (id, access and refresh) are received. 

There is no option to authenticate the user programmatically and get auth token and then subsequently use auth code to hit the token end point and get tokens (Auth Code Grant workflow).

**Comment by VeegY** [comment]
Hey, I hit the same roadblock and did some digging. 
Please see [here](https://stackoverflow.com/a/55120568) and [here](https://forums.aws.amazon.com/thread.jspa?messageID=832982&#832982l)

**Comment by sammartinez** [comment]
Resolving this issue as it seems the above workaround provided what you were looking for @gauravchaddha
