### ISSUE TITLE
Could I use all languages in Predictions/Transcribe?

### ISSUE THREAD

**Issue by sorokinvj** [aws-amplify/amplify-js#4367]
** Which Category is your question related to? **
Predictions
** What AWS Services are you utilizing? **
Cognito, Amplify, Auth

Hey guys, I need to use the Russian language to transcribe audio, but in the docs, there are only "en-US", "en-GB", "fr-FR", "fr-CA", "es-US". Is it a constraint for me? Or it's not just documented yet (because Russian was added to AWS only in August 2019)?

**Comment by sammartinez** [comment]
@sorokinvj Sorry for the late response. Currently, this is not implemented inside of Amplify. I am marking this as a feature request.

**Comment by sorokinvj** [comment]
> @sorokinvj Sorry for the late response. Currently, this is not implemented inside of Amplify. I am marking this as a feature request.

so Amplify has its own Transcribe service? Or how could it be, that from Amplify you can't transcribe those audios you can from just Javascript SDK?

**Comment by tannerabread** [comment]
Closing this as resolved from the above mentioned PR.

Thank you again for bringing this to our attention!
