### ISSUE TITLE
Should API.graphql() throw an actual Error instead of a plain object?

### ISSUE THREAD

**Issue by ffxsam** [aws-amplify/amplify-js#4376]
`API.graphql()` seems to be throwing a plain object when an error occurs, rather than an actual instance of an `Error` object. This isn't a huge deal, except that I can't get a stack trace when something goes wrong.

Since the response payload from GraphQL is important in determining what went wrong, maybe `Error` could be extended to allow for a payload:

```js
class GraphQLException extends Error {
  constructor(message, data) {
    super(message);

    if (Error.captureStackTrace) {
      Error.captureStackTrace(this, Exception);
    }

    this.data = data;
  }
}

try {
  throw new GraphQLException('Ya done messed up!', {
    bad: true,
    reason: 'because',
  });
} catch (e) {
  console.log(e.data);
}
```

**Comment by ericclemmons** [comment]
I agree, throwing should pass `instanceof Error` checks.

**Comment by danielblignaut** [comment]
I use this... 

```typescript

export class GraphQLResultError<T extends object> extends Error {

	public errors: Array<{
		errorInfo?: string
		errorType?: string
		message: string
		path?: string[]
		locations?: Array<{
			column: number
			line: number
			sourceName?: string
		}>
	}>

	public data?: T

	public constructor(message: string) {
		super(message)
		this.name = 'GraphQLResultError'

		// Maintains proper stack trace for where our error was thrown (only available on V8)
		if (Error.captureStackTrace) {
			Error.captureStackTrace(this, GraphQLResultError)
		}

		Object.setPrototypeOf(this, GraphQLResultError.prototype)
	}

	static [Symbol.hasInstance](obj): boolean {
		if (obj.errors != null ) return true
	}
	
}


```

then usage

```typescript

try {
//perform api query with amplify api client
}
catch(err) {
if(err instanceof GraphQLResultError) {
//manage API failure errors here
}
}

```

FWIW: not fully tested on the object properties

**Comment by BoltsJ** [comment]
This also affects Auth, which seems to throw plain `Object`s instead of Errors

**Comment by chrisbonifacio** [comment]
Closing this as the API for graphql queries and errors has changed.

Please refer to our documentation on how to manipulate data with Amplify Gen 2's type-safe `client.models` API.

Here's an example of the error type and how to handle:

![Image](https://github.com/aws-amplify/amplify-js/assets/16952986/672f646c-65ea-4368-85d9-e68f851dc4b5)
