### ISSUE TITLE
Best practices for data syncing between environments (DynamoDB and Cognito)

### ISSUE THREAD

**Issue by CodySwannGT** [aws-amplify/amplify-js#4379]
** Which Category is your question related to? **
Auth and API
** What AWS Services are you utilizing? **
Cognito, AWS AppSync, DynamoDB.
** Provide additional details e.g. code snippets **
n/a

This might not be the appropriate place for this question, but I'm striking out everywhere.

Here's the scenario.

We have 2+n amplify environments spread across that same number of AWS accounts. i.e. each environment belongs to it's own AWS account. Production, Staging and a sandbox environment for each developer on the project

When we create a new environment (or even when we want to update one), we want to copy all the data from production to staging or n.

We wrote some scripts to sync the dynamo tables across environments/accounts, but can't do it with the cognito pool.

We are using email as the username, which causes cognito to set the actual Username field equal to the auto generated "sub" property.

So when we try to copy all users in Production userpool to Staging userpool, the copied user's have different Usernames and Subs.

This is a problem because we are using username/sub as keys in our dynamodb tables.

Any advice on this would be hugely appreciated. It's always a common requirement on our projects, so I imagine others have encountered it.

**Comment by undefobj** [comment]
I don't think you'll be able to solve the sub problem those are uniquely generated. I'd suggest looking at a different partitioning scheme or use some other Identifier as a custom attribute which you can control assignment across the User Pools.

**Comment by CodySwannGT** [comment]
So that's kinda weird though, right?

I think what you're saying is create a custom attribute for the pool called like custom:uuid and allow the application to set that value.

Then on the dynamo side, for say, the User table, create an index on a field like cognitoId.

That works fine, but the cognito api does not allow querying by custom attributes so there would be no way to retrieve the cognito record from the data in the dynamo record.

**Comment by undefobj** [comment]
I'm not sure if it's weird or not weird, more of an option to your question around having a consistent identifier between different setup. Subs are by design unique to that system, so if you are explicitly choosing to index using this attribute and migrate data across datastores then you'll need some way to perform a mapping. 

Environments are isolated units for rolling changes and what you're hitting on is trying to migrate data from one to another. That's a big challenge and really it needs either a bit of architecture that you'll need to enforce or we could turn this into a feature request for the future in Amplify and see what the demand is. Fair warning though this is non-trivial and would take a lot of design and iteration.

**Comment by CodySwannGT** [comment]
I definitely think it's critical to be able to copy data between environments and keep it consistent. With a single traditional data source (MySQL, Postgres, Mongo) or Framework (Rails, Django, etc) this is obviously trivial. Amplify's lack of import/export puts it at a severe disadvantage. 

I honestly can't think of a project where that hasn't been a requirement. QA can't really function without working with a real data set in an isolated environment.

The biggest problem is that it currently can't be accomplished at all (at least that I'm aware of) because of the issues outlined in our thread.

I wouldn't mind writing migration/import/export tools to accomplish this, but my hesitation in starting on such a project is that I think it's an actual impossibility currently, given our requirements.

One solution I thought of was to use the cognito email address as the dynamo index key, but that's obviously fraught with PII issues.

**Comment by mauerbac** [comment]
This seems like a great discussion question. If there's further follow-up, let's start a new discussion in the Discussion tab.
