### ISSUE TITLE
Upgrading Amplify packages stops remembering Auth session in React Native

### ISSUE THREAD

**Issue by rnnyrk** [aws-amplify/amplify-js#4380]
**Describe the bug**
Yesterday I've updated my React Native app to the latest version of `amazon-cognito-identity-js`, `@aws-amplify/auth` and `@aws-amplify/core`. Unfortunately after updating the packages my app didn't remembered the Cognito session anymore after killing the app (so swiping it up on iOS).

It happens on both development and production mode.

- `@aws-amplify/auth` from 1.4.2 to 1.5.0
- `@aws-amplify/core` from 1.2.2 to 1.2.4
- `amazon-cognito-identity-js` from 3.1.2 to 3.2.0

I'd read the change log and commit messages of both packages, but couldn't find anything that might be related to the issue. Is this a known bug, or did I miss anything in the change log?

<details>
  <summary><strong>Environment</strong></summary>
```
  System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 50.67 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 70.0
    Safari: 13.0.3
  npmGlobalPackages:
    npm: 6.12.0
    react-native-cli: 2.0.1```
</details>


**Smartphone (please complete the following information):**
- Device: iPhoneX
- OS: 13.1.3

**Sample code**
After I've re-opened the app I run `Auth.currentAuthenticatedUser()` on `componentDidMount`, which returns a "not authenticated".

**Comment by davidbiller** [comment]
You have to create your own Store. 
AsyncStorage is not in react native anymore.

**Comment by rnnyrk** [comment]
@davidbiller I don’t think this has anything to do with React Native since I already was on the latest version. I happend only because I’d update to the most recent AWS packages

**Comment by davidbiller** [comment]
https://github.com/aws-amplify/amplify-js/pull/3991

**Comment by Ashish5591** [comment]
Hi @rnnyrk  could you share the version of react native you are using? Also were you using the same version before the upgrade?

**Comment by rnnyrk** [comment]
@Ashish5591 I do run react-native `0.61.4`. This works with the old versions of the AWS packages mentioned in the first post, but after upgrading the AWS packages I encounter the described issues with the the same react-native version.

**Comment by Luckygirlllll** [comment]
I'm experiencing similar issue, `Auth.currentAuthenticatedUser()` throws an error `not authenticated `after the app refresh. Any updates about this issue? 
https://github.com/aws-amplify/amplify-js/issues/4420

**Comment by rafauke** [comment]
@Luckygirlllll do you encounter the same issue if you provide custom storage in you amplify configuration for Auth?

**Comment by Luckygirlllll** [comment]
@rafauke I just have updated AsyncStorage and I see the same problem.

**Comment by davidbiller** [comment]
> @rafauke I just have updated AsyncStorage and I see the same problem.

It’s not necessary to update the asyncStorage. You have to provide the storage to the aws amplify config.

**Comment by Luckygirlllll** [comment]
@davidbiller I'm doing it like this: 

```
import AsyncStorage from '@react-native-community/async-storage';

const persistConfig = {
    key: 'root',
    timeout: null,
    storage: AsyncStorage,
  }
```

**Comment by Luckygirlllll** [comment]
@davidbiller Got it, I used the answer from this [issue](https://github.com/aws-amplify/amplify-js/issues/4351), after the adding storage to amplify config it started work correctly,

**Comment by dantasfiles** [comment]
See https://github.com/aws-amplify/amplify-js/issues/4351#issuecomment-557711904

**Comment by Ashish5591** [comment]
Could you delete your node_modules and do:
npm install @aws-amplify@next

Let us know if this resolves your issue. We will add the fix to @latest early next week.

**Comment by rnnyrk** [comment]
Thank you! Unfortunately I can’t try it out until Monday.

**Comment by lzbikowski-opensource** [comment]
Awesome, it worked after updating to aws-amplify@next
Thanks!

**Comment by rnnyrk** [comment]
@Ashish-Nanda Confirmed that it works again after updating to `@aws-amplify/auth@next` and `@aws-amplify/core@next`. Both running `2.1.0` now. Any idea when this will get stable?

**Comment by Ashish-Nanda** [comment]
Hi @rnnyrk and @Izbikowski-opensource the fix is in @latest now. 

If you can confirm its working, I'll go ahead and close the issue.

**Comment by Ashish-Nanda** [comment]
Since this [comment](https://github.com/aws-amplify/amplify-js/issues/4351#issuecomment-563934960) as well as a few others on that thread were able to confirm that the fix in `@latest` resolves the problem, I'm going to go ahead and close this issue.
