### ISSUE TITLE
Ionic Sign Up Component Missing Hide Check For Sign In

### ISSUE THREAD

**Issue by Spat915** [aws-amplify/amplify-js#4381]
**Describe the bug**
The file located at src/components/authenticator/sign-up-component/sign-up.component.ionic.ts is missing a check for a passed hide=['SignIn'] similar to the core component that includes a check for hide=['SignIn'] to hide a link at the bottom of the form to set the sign in component's state. This check is included in the sign-up.component.core.ts which is why I believe it was left out in error.

**To Reproduce**
1. Create a component in your ionic page like so:
`<amplify-auth-sign-up-ionic [authState]="authState" [signUpConfig]="signupConfig" [hide]="hide"></amplify-auth-sign-up-ionic>`
2. In the page's .ts file, define hide:
`hide = [ 'SignIn' ];`
3. Load page in browser - the component will display the "Have an account? Sign In" div when it shouldn't.

**Expected behavior**
When passing 'SignIn', the link to sign in should be hidden in the ionic component the same way as it is in the core component.

**Screenshots**
Below screen shows the ionic (top) and core (bottom) components built into 1 page with same hide being passed. Highlighted are the locations of what's wrong and right.
![Annotation 2019-11-12 095834](https://user-images.githubusercontent.com/15917023/68687676-2cb8c900-0533-11ea-84f0-5a5a156b0f16.png)

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
    Memory: 21.88 GB / 31.89 GB
  Binaries:
    Node: 10.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.387.0
    Internet Explorer: 11.0.18362.1
    (tested on Chrome - not detected)
  npmPackages:
    aws-amplify: ^1.2.4 => 1.2.4
    aws-amplify-angular: ^3.1.4 => 3.1.4
    ... [omitted]
```

</details>

**Comment by ashika01** [comment]
@Spat915 I am closing this issue as this should be fixed with the new UI components changes. For more info check here - https://docs.amplify.aws/ui/auth/authenticator/q/framework/ionic. 

The live example on page shows this is fixed. If you still face any issue or have any feedback for with the new UI. Please feel free to open up new issue.
