### ISSUE TITLE
Facebook Federation using too many API calls with React Native

### ISSUE THREAD

**Issue by mithunkalan** [aws-amplify/amplify-js#4383]
**Describe the bug**
I get the Facebook.logInWithReadPermissionsAsync from EXPO, then use it with Auth.federatedSignIn. My API counter on facebook jumped from 444 to 573 for gr:get:User.

So now with the AsyncStorage shenanigans, I need to test my code. High consumption of API rate limits means I can log into facebook maybe 2 or 3 times an hour. 

Expo-cli, amplify cli, node, npm are all latest as at Nov 10, 2019. 

I'm not sure if the bug is AWS or EXPO. 
My setup: 
```

"dependencies": {
    "@react-native-community/async-storage": "^1.6.2",
    "aws-amplify": "^1.2.4",
    "aws-amplify-react-native": "^2.2.3",
    "expo": "^35.0.0",
    "expo-constants": "~7.0.0",
    "expo-facebook": "~7.0.0",
    "expo-google-app-auth": "^7.0.0",
    "expo-google-sign-in": "~7.0.0",
    "expo-permissions": "~7.0.0", ...}
```

then in App.js
```
Auth.configure({
  refreshHandlers: {
    google: refreshToken,
    facebook: refreshToken
  },
  storage: MemoryStorage
});
Amplify.configure(awsconfig); 

```
MemoryStorage & refreshToken are from [issue 4351](https://github.com/aws-amplify/amplify-js/issues/4351)

**Expected behavior**
Maybe 2 or 3 calls are consumed like "public_profile" and "email"

My question: 
Anyone else experience this high facebook API use? 
How did you fix it?

**Comment by ericclemmons** [comment]
@mithunkalan I haven't been able to validate this with calls to `Amplify.federatedSignIn` alone.  The API calls to `gr:get:User` go up by 1 with each sign-in attempt.

Could you help me understand why both `Amplify.federatedSignIn` and `Facebook.logInWithReadPermissionsAsync` are being used together? I assume it's so you can access Facebook's API, so you're using Amplify for the sign-in portion?

When you comment out the calls to `Facebook.logInWithReadPermissionsAsync` (or any of the Facebook API calls), do you see the API consumption still tick up?

**Comment by mithunkalan** [comment]
Hi @ericclemmons . This issue has gone away. The problem was with the Hosted UI. It is requesting 2 tokens and causes failure. Each failure added 40+ calls to FB's counter. I still have no idea why. https://github.com/aws-amplify/amplify-js/issues/4388#issuecomment-559472049 Solves the token issue & now the FB calls are single digits.

**Comment by ericclemmons** [comment]
@mithunkalan Thanks for the update!  I added a comment (https://github.com/aws-amplify/amplify-js/issues/4388#issuecomment-569961465) to better understand what changes we should consider to make this more resilient.

We can re-open this issue if there is more to investigate here specifically.
