### ISSUE TITLE
Social logins not work with exp://127.0.0.1:19000

### ISSUE THREAD

**Issue by esuarezz** [aws-amplify/amplify-js#4384]
We are using social login , in the aws-export.js we have:
        "redirectSignIn": "exp://127.0.0.1:19000/",
        "redirectSignOut": "exp://127.0.0.1:19000/",

this is not working correctly and I have to change that for my local IP: exp://192.168.1.40:19000

if not is not working .
So we have to change the IP in the console and in the aws-export depending the dev is working in that time :S
--- 

Also is not working the multiple Callback URL(s) into the console in appclientsettings(This would fix it because I would add my ip and the another dev ip).

**Comment by iartemiev** [comment]
Please provide the following:
* A code sample (i.e. App.js) and aws-exports.js (with any sensitive information removed)
* Dependencies from package.json
* Steps you are taking to add Federated Sign-In to your app

**Comment by iartemiev** [comment]
Also, what do you mean by "this is not working correctly"? What behavior are you experiencing? Is there an error message?

**Comment by esuarezz** [comment]
```
const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_content_delivery_bucket": "hapstoapp...",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://hapsto.....s3-website-eu-west-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "eu-west-1:...",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_...",
    "aws_user_pools_web_client_id": "6j2pdafpalip0m...",
    "oauth": {
        "domain": ".....auth.eu-west-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "exp://127.0.0.1:19000/",
        "redirectSignOut": "exp:/exp://127.0.0.1:19000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",   
};
export default awsmobile;

```
```

"dependencies": {
    "@aws-amplify/api": "^1.2.4",
    "@aws-amplify/pubsub": "^1.2.4",
    "aws-amplify": "^1.2.4",
    "aws-amplify-react-native": "^2.2.3",
    "expo": "^35.0.1",
    "expo-app-auth": "latest",
    "expo-facebook": "~7.0.0",
    "expo-google-app-auth": "latest",
    "expo-localization": "~7.0.0",
    "formik": "^2.0.3",
    "i18next": "^19.0.0",
    "react": "16.11.0",
    "react-dom": "16.11.0",
    "react-i18next": "^11.1.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-paper": "^3.2.1",
    "react-native-reanimated": "~1.4.0",
    "react-native-status-bar-height": "^2.4.0",
    "react-native-web": "^0.11.7",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3",
    "react-redux": "^7.1.3",
    "redux": "^4.0.4",
    "redux-saga": "^1.1.3"
  },
  "devDependencies": {
    "@react-native-community/eslint-config": "^0.0.5",
    "@types/react": "^16.9.11",
    "@types/react-native": "^0.60.22",
    "@types/react-redux": "^7.1.5",
    "@typescript-eslint/eslint-plugin": "^2.6.1",
    "@typescript-eslint/parser": "^2.6.1",
    "babel-preset-expo": "^7.1.0",
    "eslint": "^6.6.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-react": "^7.16.0",
    "eslint-plugin-react-native": "^3.8.1",
    "prettier": "1.19.1",
    "typescript": "^3.7.2"
  },
```

**Comment by iartemiev** [comment]
Thank you for providing context, @esuarezz 

I believe this is the same issue as https://github.com/aws-amplify/amplify-js/issues/4003

We're currently investigating solutions to the problem and will keep that issue updated as we make progress.

**Comment by esuarezz** [comment]
do you think?
I dont think is the case because here is about the login in expo(social) is not hitting localhost or 127....

**Comment by iartemiev** [comment]
If you're running the app on a physical phone (not in a Simulator), then you would need to use the local IP, that is exp://192.x.x.x:19000. To my best understanding, that is how Expo works.

However, in the AWS console for Cognito, you should be able to set multiple callback and signout URLs with a comma in between, i.e. `exp://192.168.1.1:19000, exp://192.168.1.2:19000`

![image](https://user-images.githubusercontent.com/29709626/68862109-dd9da000-06ba-11ea-9cce-b253928b031a.png)

What happens when you do that?

**Comment by esuarezz** [comment]
We tried that, that was a good idea , but it is like getting just the first one, it is not taking the second and the 3 option you write in the callback URL's.
If we fix that, and we get more than the first one, that would "fix" this issue

**Comment by iartemiev** [comment]
What happens when you try to enter a second callback URL? Do you get an error?

**Comment by esuarezz** [comment]
it is like you are not introducing it, so the same if you dont introduce than you are introducing it.
it is working just for the first URL

**Comment by iartemiev** [comment]
Are you adjusting the aws-exports file on the 2nd developer's machine?

For example, if you have these 2 Callback URLs configured in Cogntio via the Console `exp://192.168.1.1:19000, exp://192.168.1.2:19000`

Your aws-exports files should contain

**Developer 1:**
```
oauth: {
  redirectSignIn: "exp://192.168.1.1:19000",
  redirectSignOut: "exp://192.168.1.1:19000",
...
}
```

**Developer 2:**
```
oauth: {
  redirectSignIn: "exp://192.168.1.2:19000",
  redirectSignOut: "exp://192.168.1.2:19000",
...
}
```

**Comment by esuarezz** [comment]
Hi! I will give it a try this week and I will answer, thanks!

**Comment by annjawn** [comment]
Is there a solution for this yet? Quite unsure how multiple devs can work on a project this way. I am trying to use `exp://127.0.0.1:19000` as well and using simulator but the Google federation doesn't work. If I switch to LAN connection on the Metro bundler console and then update Cognito console callback URLs and aws_exports it works with physical device as well as simulator. But using LAN isn't a great idea when multiple devs are going to be working on the project.
