### ISSUE TITLE
API (GraphQL) - How do you create many connections to one Photo schema object?

### ISSUE THREAD

**Issue by VicFrolov** [aws-amplify/amplify-js#4386]
Let's say you have a Product and a Brand. Product has an array of photos, and brand has both a "cover" photo, and then also another array of photos:
```
type Product {
  id: ID!
  photos: [Photo] @connection(name: "ProductPhotos")
}

type Brand {
  id: ID!
  coverPhoto: Photo @connection(name: "BrandCoverPhoto")
  photos: [Photo] @connection(name: "BrandPhotos")
}

type Photo {
  id: ID!
  bucket: String!
  fullsize: PhotoS3Info!
  thumbnail: PhotoS3Info!
  brandCoverPhoto: Brand @connection(name: "BrandCoverPhoto")
  brandPhotos: Brand @connection(name: "BrandPhotos")
  productPhotos: Product @connection(name: "ProductPhotos")
}
```

If this is correct, this feels like Photo will become pretty bloated, especially if you have a bunch of other models that require photos, but perhaps this is the best practice approach?

If this is not correct, how would you make one type of Photo, that can be shared by a large list of types, e.g. Product, Brand, User, Seller, Buyer, etc, that only have access to their respective photos in the schema?

**Comment by mauerbac** [comment]
Hi @VicFrolov - this seems like a great GraphQL general question. I'll convert this to a discussion.
