### ISSUE TITLE
@aws-amplify/api: export 'GraphQLError' was not found in 'graphql'

### ISSUE THREAD

**Issue by piraka9011** [aws-amplify/amplify-js#4387]
**Describe the bug**
When I try to build my typescript react app, I get the following error:
```
ERROR in ./node_modules/@aws-amplify/api/lib-esm/API.js 543:40-52
"export 'GraphQLError' was not found in 'graphql'
 @ ./node_modules/@aws-amplify/api/lib-esm/index.js
 @ ./node_modules/aws-amplify/lib/index.js
 @ ./src/pages/ForgotPassword/index.tsx
 @ ./src/routes.ts
 @ ./src/components/Routes.tsx
 @ ./src/App.tsx
 @ ./src/client/index.tsx
 @ multi regenerator-runtime/runtime ./src/client/index.tsx

ERROR in ./node_modules/@aws-amplify/api/lib-esm/API.js 560:41-53
"export 'GraphQLError' was not found in 'graphql'
 @ ./node_modules/@aws-amplify/api/lib-esm/index.js
 @ ./node_modules/aws-amplify/lib/index.js
 @ ./src/pages/ForgotPassword/index.tsx
 @ ./src/routes.ts
 @ ./src/components/Routes.tsx
 @ ./src/App.tsx
 @ ./src/client/index.tsx
 @ multi regenerator-runtime/runtime ./src/client/index.tsx

ERROR in ./node_modules/@aws-amplify/api/lib-esm/API.js 607:65-77
"export 'GraphQLError' was not found in 'graphql'
 @ ./node_modules/@aws-amplify/api/lib-esm/index.js
 @ ./node_modules/aws-amplify/lib/index.js
 @ ./src/pages/ForgotPassword/index.tsx
 @ ./src/routes.ts
 @ ./src/components/Routes.tsx
 @ ./src/App.tsx
 @ ./src/client/index.tsx
 @ multi regenerator-runtime/runtime ./src/client/index.tsx
```
It looks like aws-amplify can't find graphql components.

**To Reproduce**

1. `npm run install`
2. `npm run dev` (`ts-node -T -O '{\"module\": \"commonjs\"}' --transpileOnly internal/scripts/build -- --optimize`)

**Comment by RyanWarner** [comment]
Hey @piraka9011 have you made any progress figuring this out? I've been blocked by this for a few days and nothing I've tried has helped.

**Comment by piraka9011** [comment]
@RyanWarner No I have not. I have tried using an older version of `aws-amplify` but it looks like the issue is related to the version of `GraphQL` and @BennettDixon has provided a potential fix. 

Using his fix probably means you will have to have your own version of amplify in a `node-modules` folder until it is merged.

**Comment by elorzafe** [comment]
@RyanWarner @piraka9011 I am taking a look now.

**Comment by RyanWarner** [comment]
Update: I solved this by updating my webpack config.
I move `.mjs` to come before `.js` in my resolve extensions, and I also did not have `.mjs` files ignored in my file-loader config
```
resolve: {
  extensions: ['.mjs', '.js', '.json', '.jsx', '.css']
}
```

and my file loader:
```
const fileLoader = {
  exclude: [/\.(js|jsx|ts|tsx|css|mjs|html|ejs|json)$/],
  use: [
    {
      loader: require.resolve('file-loader'),
      options: {
        name: 'assets/[name].[hash:8].[ext]'
      }
    }
  ]
}
```

Hope this helps!

**Comment by elorzafe** [comment]
@RyanWarner thanks for your comment, for me is not failing probably because I have a different webpack config. I am using standard `create-react-app` with typescript

**Comment by Amplifiyer** [comment]
@piraka9011 Did you try the fix above from RyanWarner? Let us know if you are still facing this issue.

**Comment by piraka9011** [comment]
It appears this is resolved. Thanks!

**Comment by rudyhadoux** [comment]
Same problem with Angular.

**Comment by damogallagher** [comment]
@rudyhadoux was this problem introduced for you when you upgraded to Angular 12?
For me this was all working fine before I did the Angular upgrade so any help with resolving this would be much appreciated

**Comment by rudyhadoux** [comment]
Yes indeed.
Angular developer gave me this answer :
**In .mjs files or .js files with a package.json with "type": "module" imports need to be specified with an extension.
In Webpack 4, this was not enforced since this was still an experimental feature in Node.JS, however since now this is a standard it is being enforced and error out when encountered incorrect packages.**

**Comment by rudyhadoux** [comment]
This issue should not be closed.
No webpack config in an Angular 12 web app.
It is a problem of library, like aws-amplify.

**Comment by rudyhadoux** [comment]
The only workaround yet is to downgrade.
npm i -g @angular/cli@11.2.13

**Comment by damogallagher** [comment]
@rudyhadoux yes it looks like the amplify libs use version 4 of webpack and the webpack config hasnt been touched in 2 years - https://github.com/aws-amplify/amplify-js/tree/main/packages/api

**Comment by rudyhadoux** [comment]
@damogallagher Exact.

**Comment by rudyhadoux** [comment]
The problem is here :
https://github.com/graphql/graphql-js/issues/2721

**Comment by damogallagher** [comment]
> The problem is here :
> [graphql/graphql-js#2721](https://github.com/graphql/graphql-js/issues/2721)

I know in graphql is where the error is manifesting itself but this lib was working 100% up until the Angular 12 upgrade. Should it be on angular to provide a way to override the webpack configuration so that the workaround does indeed work?

**Comment by rudyhadoux** [comment]
They could provide a workaround but it seems that it is not their problem.
Graphql-js should adapt their configuration for Webpack 5.

**Comment by edoardo849** [comment]
A possible workaround is to use the `@angular-builders/custom-webpack` extension which uses webpack 4

**Comment by rudyhadoux** [comment]
Is it possible with Angular 12 ?
And how ?
Documentation would be appreciated.

**Comment by edoardo849** [comment]
> Is it possible with Angular 12 ?
> And how ?
> Documentation would be appreciated.

Yes, I've tested it and it works... at the moment. The documentation for `custom-webpack` mentions that only Angular CLI 11 is supported but it seems compatible with Angular 12.

Steps:

```
yarn install @angular-builders/custom-webpack
```

Edit `angular.json`

```json
"architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
         ...
         },
         ...
         "serve": {
            "builder": "@angular-builders/custom-webpack:dev-server",
         ...
        }
```
No need to actually add a custom webpack config file, but if you do want it, follow  [the documentation](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack)

**Comment by rudyhadoux** [comment]
Thanks.

**Comment by cybercussion** [comment]
Thanks @rudyhadoux  and everyone for running this down.

**Comment by damogallagher** [comment]
@cybercussion I have those errors also with ngx-device-detector

**Comment by cybercussion** [comment]
@damogallagher I attempted ```npm ci``` or just straight up removing node_modules but that didn't do it either.  I'm now wondering if this is the "ivy first" issue related to Angular 12 and I have to wait for these projects to patch.

**Comment by edoardo849** [comment]
The custom webpack doesn't work when compilng for production because it's version 4, so this is what's working for me now.

1. Install `@angular-builders/custom-webpack@12.0.0-beta.0` - this includes webpack 5
2. create `custom-webpack.config.js` in your root folder with the following in it:

```json
module.exports = {

    // This has been included because of graphql
    module: {
        rules: [

            {
                test: /\.m?js/,
                resolve: {
                    fullySpecified: false,
                },
            }
        ]
    }
}

```
3. In `angular.json`, replace the following:

```
architect.build.builder: "@angular-builders/custom-webpack:browser"

configurations.production.aot: true

architect.serve.builder: "@angular-builders/custom-webpack:dev-server"

```

**Comment by rudyhadoux** [comment]
This issue should not be closed.
It seems that last graphql-js packages are well configured for webpack 5.
Does Amplify use those last graphql-js packages ???

**Comment by cybercussion** [comment]
Staying on Angular 11.x.x for now.  The custom-webpack v11.1.1 just leads to a cascade of build/serve issues. 
Everything from "ɵngcc0.ɵɵFactoryDef" and "ɵngcc0.ɵɵNgModuleDefWithMeta"not exported to a prod build of "An unhandled exception occurred - which seems to only have a "delete node_modules and reinstall"  - and that didn't fix it.

Attempting to build prod resulted in:
The 'buildOptimizer' option cannot be used without 'aot'."
