### ISSUE TITLE
Amplify React, SignIn Auth Component, password field not required

### ISSUE THREAD

**Issue by plumdog** [aws-amplify/amplify-js#4390]
**Describe the bug**
In the default SignIn Auth component, the password field is marked as required (with a *), but no such validation happens. Further, because this does get submitted, the `Auth` library thinks you're trying to do a `CUSTOM_AUTH` passwordless login, so you get a "Custom auth lambda trigger is not configured for the user pool." error displayed.

**To Reproduce**
I can't find an example anywhere of the default auth components being used, but if you enter a username but no password and submit, that should reproduce.

The best I can find is https://www.amplifyauth.dev/ which I think uses customised components, but still exhibit this behaviour (only hidden a little bit):
- Click "Sign in with email"
- Then "Sign in"
- Open the browser console
- Enter a username, but not password
- See a "Custom auth lambda trigger is not configured for the user pool." message in the browser console - note that the default SignIn component displays this error to the user as a message at the top of the screen.
- Also, see in the network requests a request like:
```
{
  "AuthFlow":"CUSTOM_AUTH",
  "ClientId":"...",
  "AuthParameters":{"USERNAME":"plumdog"},
  "ClientMetadata":{}
}
```
with 400 response like
```
{
  "__type":"InvalidParameterException",
  "message":"Custom auth lambda trigger is not configured for the user pool."
}
```

**Expected behavior**
If the password field is marked as required, it should validate accordingly. I don't think I would ever expect a "SignIn" form to accept no password.

I don't really understand the CUSTOM_AUTH passwordless stuff, but I think that by default this should do the simple thing and require a password to be entered. Certainly, the validation and whether a * is displayed should match up.

**Screenshots**

![required](https://user-images.githubusercontent.com/2348591/68765421-aa083a80-0614-11ea-87ae-741a25801b6b.png)

![not_validated](https://user-images.githubusercontent.com/2348591/68765428-ac6a9480-0614-11ea-89b0-80173e2449a5.png)

**Comment by plumdog** [comment]
This behaviour looks to be governed by the auth library - see https://github.com/aws-amplify/amplify-js/blob/023f4960d80c9774d85cbc7593175d7380fcbed2/packages/auth/src/Auth.ts#L451-L455

That method considers the password to be optional (which makes sense given that it handles passwordless login) but that method is also used to handle validation for the form (and so its treating password as optional doesn't make sense for this form).

**Comment by mrichman** [comment]
Same issue with Vue.js.
<img width="489" alt="image" src="https://user-images.githubusercontent.com/11228/80644384-8eb0b080-8a37-11ea-8855-57c80e7f6a26.png">

**Comment by mrichman** [comment]
Looks like they are aware: https://github.com/aws-amplify/amplify-js/issues/5623

**Comment by Lionel1232** [comment]
Same thing is happening for us, we are using Angular

**Comment by santuvytla** [comment]
maybe we have to also set password to be mandatory..so system knows passwordless login is not permitted

**Comment by ashika01** [comment]
Closing this issue as duplicate since we would be tracking this issue in the new UI components `@aws-amplify/ui-components` . Look at https://github.com/aws-amplify/amplify-js/issues/5623 for updates.
