### ISSUE TITLE
Non pinpoint push message crashes android react-native app 

### ISSUE THREAD

**Issue by millarm** [aws-amplify/amplify-js#4398]
**Describe the bug**

If a push message is received on Android from a non-pinpoint source (e.g. someone is using Intercom with push notification alongside Pinpoint)

**To Reproduce**

Send any push notification not using AWS Pinpoint to an android device.

The root cause here is that

parseMessagefromAndroid

can return null as the message, this is then the rawMessage that is passed into 

handleCampaignPush

if (Platform.OS === 'android') {
			const { data } = rawMessage;
			campaign = {
				campaign_id: data['pinpoint.campaign.campaign_id'],
				campaign_activity_id: data['pinpoint.campaign.campaign_activity_id'],
				treatment_id: data['pinpoint.campaign.treatment_id'],
			};
		}

if rawMessage is null, this will crash.

Most satisfying fix might actually to be to change 

addEventListenerForAndroid

to pass in the raw data (as iOS) then call parseMessagefromAndroid there, allowing the unparsed data to be handled elsewhere, but this would be a subtle behaviour change.

Workaround for anyone that hits this is to override the functionality and check it which can be done without forking.  I have:

```
PushNotification.oldHandleCampaignPush = PushNotification.handleCampaignPush;

PushNotification.handleCampaignPush = rawMessage => {
  // workaround bug
  if (Platform.OS === 'android' && !rawMessage) {
    return;
  }
  return PushNotification.oldHandleCampaignPush(rawMessage);
};

PushNotification.configure({
  ...config,
  requestIOSPermissions: false, // OPTIONAL, defaults to true
});
```

To avoid this issue (thus hopefully helping anyone that gets here from a search before the underlying bug is fixed)

**Comment by ashika01** [comment]
@millarm We have made some upgrades and non pinpoint push messages crashes has been corrected. https://github.com/aws-amplify/amplify-js/pull/4845

If you are still seeing issues in our newer version please open up a new issue.
