### ISSUE TITLE
Have .currentAuthenticatedUser() not throw uncaught exceptions when there is no current user and catch()

### ISSUE THREAD

**Issue by j0b0sapi3n** [aws-amplify/amplify-js#4403]
**Is your feature request related to a problem? Please describe.**
I'm currently creating pages that can be viewed even when unauthenticated, but I check on `componentDidMount` whether a user is logged in using `Auth.currentAuthenticatedUser()` to show a different state for a component if they are logged in. Even with using `catch`, it still throws an error message saying `Uncaught (in promise) No current user` even though I do catch the error.

Here's the full block:
`Auth.currentAuthenticatedUser().then(resp => {
      this.setState({
        authState: 'LOGGED_IN'
      })
    }).catch(err => {
      // Don't do anything with error
    });`

**Describe the solution you'd like**
Have it return a normal error message that is caught in `catch` without throwing other errors

**Comment by AlessandroAnnini** [comment]
I have the same exact problem!

**Comment by davegariepy** [comment]
also trying to use `Auth.currentAuthenticatedUser()` to detect whether a user is signed in or not.

I'd like to return false if no user, but an error is thrown regardless of `catch` being used.

**Comment by j0b0sapi3n** [comment]
@davegariepy Yeah, I agree if it could just return true/false or if that could be a separate function that'd be nice.

**Comment by davegariepy** [comment]
@j0b0sapi3n the way I worked around this was to call:

`localStorage.getItem("amplify-signin-with-hostedUI")

Its the only standard name field from Amplify in local storage and seems to only be present when the user is logged. Obviously, would rather have an official way to do this but this is what I came up with for the time. 

Have you tried anything similar?

**Comment by sammartinez** [comment]
I'll keep this marked as a feature request to have the API or a new API return a true or false statement in the future. Thanks for the input everyone!

**Comment by jamesaucode** [comment]
hi @j0b0sapi3n , can you try the latest version of `aws-amplify` and if this is still an issue ?
