### ISSUE TITLE
Navigator is not defined

### ISSUE THREAD

**Issue by lambda0xff** [aws-amplify/amplify-js#4406]
**Describe the bug**
Creating this bug because #4243 was closed without a proper fix and wasn't reopend since

**To Reproduce**
See #4243

**Comment by iartemiev** [comment]
Which version of amplify are you using? This issue is fixed in the latest unstable (`aws-amplify@unstable`), as well as in the "next" version (`aws-amplify@next`)

**Comment by lambda0xff** [comment]
Hello,

using "aws-amplify" : "^1.2.4" fails with "navigator is not defined" error.

using `aws-amplify@next` installs "^2.1.0" and gets rid of the crash 👍 
however, there are some very annoying Typescript errors:

```
 ERROR  ERROR in xxx/node_modules/@aws-amplify/api/lib-esm/types/index.
d.ts(45,21):
45:21 Cannot use namespace 'DocumentNode' as a type.
    43 | }
    44 | export interface GraphQLOptions {
  > 45 |     query: string | DocumentNode;
       |                     ^
    46 |     variables?: object;
    47 |     authMode?: GRAPHQL_AUTH_MODE;
    48 | }


 ERROR  ERROR in xxx/node_modules/@aws-amplify/pubsub/lib-esm/PubSub.d.ts(17,17):
17:17 Property 'awsAppSyncProvider' implicitly has type 'any', because its get accessor lacks a return type annotation.
    15 |      * Lazy instantiate AWSAppSyncProvider when it is required by the API category
    16 |      */
  > 17 |     private get awsAppSyncProvider();
       |                 ^
    18 |     /**
    19 |      * Lazy instantiate AWSAppSyncRealTimeProvider when it is required by the API category
    20 |      */


 ERROR  ERROR in xxx/node_modules/@aws-amplify/pubsub/lib-esm/PubSub.d.ts(21,17):
21:17 Property 'awsAppSyncRealTimeProvider' implicitly has type 'any', because its get accessor lacks a return type annotation.
    19 |      * Lazy instantiate AWSAppSyncRealTimeProvider when it is required by the API category
    20 |      */
  > 21 |     private get awsAppSyncRealTimeProvider();
       |                 ^
    22 |     /**
    23 |      * Initialize PubSub with AWS configurations
    24 |      *

```
The last two errors disappear if I set 'strict: false' and/or 'noImplicitAny: false' in my `tsconfig.json` file but that is not something I would like to do ... and the first error re `DocumentNode` remains in all cases.

So I guess it's now more of a Typescript compatibility issue

**Comment by iartemiev** [comment]
Thank you for trying that. Could you please create a new issue with the Typescript errors? If you want to avoid them for now, please use the unstable (`@unstable`)

**Comment by lambda0xff** [comment]
👍
