### ISSUE TITLE
Typescript issues re DocumentNode and amplify pub-sub

### ISSUE THREAD

**Issue by lambda0xff** [aws-amplify/amplify-js#4409]
**Describe the bug**
When setting up aws amplify inside a NuxtJS application, we get the following Typescript errors: 
```
 ERROR  ERROR in xxx/node_modules/@aws-amplify/api/lib-esm/types/index.
d.ts(45,21):
45:21 Cannot use namespace 'DocumentNode' as a type.
    43 | }
    44 | export interface GraphQLOptions {
  > 45 |     query: string | DocumentNode;
       |                     ^
    46 |     variables?: object;
    47 |     authMode?: GRAPHQL_AUTH_MODE;
    48 | }


 ERROR  ERROR in xxx/node_modules/@aws-amplify/pubsub/lib-esm/PubSub.d.ts(17,17):
17:17 Property 'awsAppSyncProvider' implicitly has type 'any', because its get accessor lacks a return type annotation.
    15 |      * Lazy instantiate AWSAppSyncProvider when it is required by the API category
    16 |      */
  > 17 |     private get awsAppSyncProvider();
       |                 ^
    18 |     /**
    19 |      * Lazy instantiate AWSAppSyncRealTimeProvider when it is required by the API category
    20 |      */


 ERROR  ERROR in xxx/node_modules/@aws-amplify/pubsub/lib-esm/PubSub.d.ts(21,17):
21:17 Property 'awsAppSyncRealTimeProvider' implicitly has type 'any', because its get accessor lacks a return type annotation.
    19 |      * Lazy instantiate AWSAppSyncRealTimeProvider when it is required by the API category
    20 |      */
  > 21 |     private get awsAppSyncRealTimeProvider();
       |                 ^
    22 |     /**
    23 |      * Initialize PubSub with AWS configurations
    24 |      *
```

Switching between `aws-amplify@next (^2.1.0)` and `aws-amplify@unstable (^1.2.5-unstable.13)` doesn't seem to make any difference and the issues appear in both cases.

**To Reproduce**

1. create basic nuxtjs application
2. set up aws-amplify
3. run app (`yarn dev`)
4. see errors in terminal

Issue linked with #4406 and #4243

**Comment by lambda0xff** [comment]
This issue is still present with the latest version (2.2.1)

**Comment by Amplifiyer** [comment]
@lambda0xff, can you share your Nuxt project setup? As well as output of the following command `yarn list | grep graphql` (Replace yarn with npm as applicable)

My guess is that package `@types/graphql` and `graphql` that are installed are incompatible with each other and hence causing this errors.

**Comment by lambda0xff** [comment]
This is my current dependencies:
```json
 "dependencies": {
    "@nuxtjs/axios": "^5.3.6",
    "@nuxtjs/toast": "^3.3.0",
    "@types/uuid": "^3.4.6",
    "aws-amplify": "1.1.36",
    "cookie-universal-nuxt": "^2.0.19",
    "jsonwebtoken": "^8.5.1",
    "jwk-to-pem": "^2.0.1",
    "nuxt": "^2.0.0",
    "nuxt-mq": "^2.0.1",
    "uuid": "^3.3.3",
    "vue-infinite-loading": "^2.4.4"
  },
  "devDependencies": {
    "@nuxt/typescript-build": "^0.3.4",
    "@nuxtjs/dotenv": "^1.4.1",
    "@nuxtjs/tailwindcss": "^1.0.0",
    "@types/graphql": "^14.5.0",
    "@types/jest": "^24.0.23",
    "@types/zen-observable": "^0.8.0",
    "@vue/test-utils": "^1.0.0-beta.27",
    "amplify-graphql-docs-generator": "^1.28.0",
    "amplify-graphql-types-generator": "^1.24.0",
    "babel-jest": "^24.1.0",
    "jest": "^24.1.0",
    "pug": "^2.0.4",
    "pug-plain-loader": "^1.0.0",
    "ts-jest": "^24.1.0",
    "vue-jest": "^4.0.0-0",
    "vue-property-decorator": "^8.3.0",
    "vue-svg-loader": "^0.15.0"
  },
  "resolutions": {
    "@aws-amplify/analytics": "1.2.23",
    "@aws-amplify/api": "1.0.42",
    "@aws-amplify/auth": "1.2.31",
    "@aws-amplify/cache": "1.0.32",
    "@aws-amplify/core": "1.1.0",
    "@aws-amplify/interactions": "1.0.35",
    "@aws-amplify/predictions": "1.0.3",
    "@aws-amplify/pubsub": "1.1.0",
    "@aws-amplify/storage": "1.1.0"
  }
```

`yarn list | grep graphql` gives the following:
warning Resolution field "@aws-amplify/core@1.1.0" is incompatible with requested version "@aws-amplify/core@^1.1.2"
│  ├─ graphql@0.13.0
│  ├─ graphql@0.13.0
├─ @types/graphql@14.5.0
│  ├─ graphql@*
│  └─ graphql@14.5.8
├─ amplify-graphql-docs-generator@1.28.0
│  ├─ graphql@^0.13.2
├─ amplify-graphql-types-generator@1.24.0
│  ├─ graphql@^0.13.2
├─ graphql@0.13.2

**Comment by Amplifiyer** [comment]
@lambda0xff thanks. I think the issue is multiple `graphql` packages and `@types/graphql`. Can you update aws-amplify to the latest version and also install `@types/graphql@14.0.0` so that both packages are at 14.0.0 version?

**Comment by lambda0xff** [comment]
Using latest aws-amplify (^2.2.1), added @types/zen-observable, @types/graqphql@14.0.0
`yarn list | grep graphql` gives:

│  ├─ graphql@14.0.0
│  ├─ graphql@14.0.0
├─ @types/graphql@14.0.0
├─ graphql@14.0.0

Still have the following error:
```
ERROR in xxx/node_modules/@aws-amplify/api/lib-esm/types/index.d.ts(45,21):
45:21 Cannot use namespace 'DocumentNode' as a type.
    43 | }
    44 | export interface GraphQLOptions {
  > 45 |     query: string | DocumentNode;
       |                     ^
    46 |     variables?: object;
    47 |     authMode?: GRAPHQL_AUTH_MODE;
    48 | }
```

**Comment by Amplifiyer** [comment]
@lambda0xff I'm curious how you are able to work around this issue #4311 When I'm trying to reproduce, I'm not able to run the app because of this issue, but when I change the library's main entry point to CJS modules, the app works fine.

**Comment by lambda0xff** [comment]
@Amplifiyer : I wasn't able to work around it ... Right now, I've reverted back to `aws-amplify@1.1.36` which is a version that "works" for me: it still gives me the DocumentNode issue but at least I don't have #4311 (which is a deal-breaker for SSR)

**Comment by Amplifiyer** [comment]
thanks @lambda0xff, I think we need to first fix #4311 and then try to reproduce this. I believe I have a fix for that. 
Based on your last comment about Using latest aws-amplify (^2.2.1), I was a little confused.

**Comment by Amplifiyer** [comment]
@lambda0xff, can you try after upgrading the aws-amplify version to unstable @aws-amplify@unstable and see if this error still persists? Also keep all the graphql packages at v14.0.0

**Comment by lambda0xff** [comment]
Using `@unstable` seems to fix #4311 for me, but I now get this `DocumentNode` error ('Cannot use namespace 'DocumentNode' as a type') for two files: 

xxx/node_modules/@aws-amplify/api/lib-esm/types/index.d.ts
xxx/node_modules/@aws-amplify/api/lib/types/index.d.ts

I've kept all the graphql packages at v14.0.0

**Comment by Amplifiyer** [comment]
I'm out of ideas, looking at similar issues faced by others, there is one of the two root causes. Either the @types/graphql is not installed or mismatched with the graphql version or skipLibCheck:false is added in the tsconfig.json

Can you turn the following commands in your package root and let me know the results
```console
stat node_modules/@types/graphql/language/ast.d.ts
head -n 4 node_modules/@types/graphql/package.json
head -n 4 node_modules/graphql/package.json
```

I don't believe that skipLibCheck:false is required for Amplify, but it doesn't hurt to try it. You can try with adding `skipLibCheck:true` in your tsconfig.json and see if it changes anything.

If we still can't reproduce, can you provide a minimal app in a repository where you can reproduce it, I will run it locally to reproduce.

**Comment by lambda0xff** [comment]
@Amplifiyer : here's an app that reproduces the bug on my end.
Look at the commit messages to reproduce all steps.

Hope this helps. 
[bug.zip](https://github.com/aws-amplify/amplify-js/files/4039351/bug.zip)

**Comment by Amplifiyer** [comment]
@lambda0xff thank you for the app and for having the patience 🙏 

I ran it locally and was able to successfully reproduce the issue you are getting. I believe the error is with the line `declare module 'graphql/language/ast'` in vue-shim.d.ts which effectively overrides the `@types/graphql` declarations. Removing that line and adding @types/grpahql@14.0.0 fixed the issue for me. Can you try these two steps in your project and let me know if it works?

**Comment by lambda0xff** [comment]
Yes, it looks like the underlying issue is that @types/graphql version 14.5.0 is listed in npm/yarn as the latest available version but is right now and empty repo without any definition files. So typing `yarn add @types/graphql` will download an empty repo ...

It looks like the latest working version is 14.2.3.

Thanks @Amplifiyer

**Comment by lambda0xff** [comment]
@Amplifiyer : Hello, I just noticed that the latest version of aws-amplify (2.2.4) is still using graphql version 14.0.0 which is the root cause of this issue.  Any reason why ?  Should we expect amplify-api to move on to the latest stable Graphql soon (maybe when v15 is released)?
