### ISSUE TITLE
@connection to table with composite index

### ISSUE THREAD

**Issue by ReeMii** [aws-amplify/amplify-js#4410]
** Which Category is your question related to? **
GraphQL
** What AWS Services are you utilizing? **
DynamoDB, AWS AppSync
** Provide additional details e.g. code snippets **

I have table with composite index

```
type Keyword @model @key(fields: ["name","lang" ]) {
  lang: String!
  name: String!
}
```
and table when I want to make connection to first table

```
type KeywordLog @model  @key(fields: ["sessionId", "createdAt"]) {
  sessionId: ID!
  createdAt: String!
  keyword : Keyword @connection
}
```

after pushing to cloud DynamoDB table and mutation input has a field `KeywordLogKeywordId: ID`

assuming that I have a `Keyword` record with lang = "en" and name = "test" what value I have to put to `KeywordLogKeywordId` to see connected record querying KeywordLog ?

**Comment by dantasfiles** [comment]
You could modify [the Project-Team example in the docs](https://aws-amplify.github.io/docs/cli-toolchain/graphql#connection)
```
type Keyword @model @key(fields: ["name", "lang"]) {
  lang: String!
  name: String!
}
type KeywordLog @model @key(fields: ["sessionId", "createdAt"]) {
  sessionId: ID!
  createdAt: String!
  name: String!
  lang: String!
  keyword: Keyword! @connection(fields: ["name", "lang"])
}
```

**Comment by amhinson** [comment]
@ReeMii Did that ^ answer your question?

**Comment by ReeMii** [comment]
I'm not on that project anymore, so I can't test it, but it looks like answer to my question.
