### ISSUE TITLE
tap PushNotification can not open the app

### ISSUE THREAD

**Issue by Sytree** [aws-amplify/amplify-js#4415]
Describe the bug
when receive a pushNotification after the app is killed, and keep it for more than a hour,  the app can not start when I tap it 

Follow the steps of Amplify Push Notifications: https://aws-amplify.github.io/docs/js/push-notifications
Killed the App
Send a test message from Pinpoint in the AWS console.
Receive the message
Tap on the message after more than a hour

I run the app on Pixel 2 XL, Android Version : 10

and I've got this logcat:
`W/BroadcastQueue: Background execution not allowed: receiving Intent { act=com.amazonaws.amplify.pushnotification.NOTIFICATION_OPENED flg=0x10 (has extras) } to `

**Comment by Sytree** [comment]
@powerful23

**Comment by dylan-westbury** [comment]
I am receiving the same also, can't open app from push notification on android with the same error

```
Background execution not allowed: receiving Intent { act=com.amazonaws.amplify.pushnotification.NOTIFICATION_OPENED flg=0x10 (has extras) } to xxxx/com.amazonaws.amplify.pushnotification.modules.RNPushNotificationBroadcastReceiver
```

**Comment by haverchuck** [comment]
@Sytree - Which version of react-native and aws-amplify-react-native are you using?

**Comment by atsneves** [comment]
Hello, the bug occurred for me as well.
My version is: 
react-native-cli: 2.0.1
react-native: 0.59.5
aws-amplify/pushnotification": "^1.1.4"

**Comment by Yuvi7447** [comment]
+1
Facing the same issue,
Here are my version details:
"react": "16.6.3",
"react-native": "^0.59.8",
"@aws-amplify/pushnotification": "^1.0.27",
"aws-amplify": "^1.1.36",
"aws-amplify-react-native": "^2.1.16"

Can anyone help me out to understand the issue?

**Comment by Ashish-Nanda** [comment]
Hi @dylan-westbury @Yuvi7447 
Is the issue when trying to open any notification your receive? 
Or does it only happen if the app is in the background for a while (> 1hr)
Could you share your Android versions?

**Comment by Yuvi7447** [comment]
@Ashish-Nanda Let me elaborate for you, 
Scenarios:
1) When the app is in the background and you receive the push notification, if you tap on the notification within some time you get into the app, if you kill the application and tap on the notification it won't open.
2) When the app receives the notification and if you open it after a long time(e.g., more than 1 hr), the app won't open!
Note: This issue is coming on every android device.
Android Version: 9

**Comment by ashika01** [comment]
@Sytree : I am unable to reproduce the issue. I will post a gif shortly, when I kill the background app and tap the notification , the app opens up.

**Comment by shubham234** [comment]
I'm also facing same issue with below dependencies:
"react-native": "0.59.8",
"@aws-amplify/pushnotification": "3.0.9"

**Device Details**
Model: OnePlus A6000
Android Version: 10

**Actual Error**
```
2020-06-04 04:12:44.898 1332-1426/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=com.amazonaws.amplify.pushnotification.NOTIFICATION_OPENED flg=0x10 (has extras) } to com.myapp.myappname.android.app.beta/com.amazonaws.amplify.pushnotification.modules.RNPushNotificationBroadcastReceiver
2020-06-04 04:12:44.899 1332-1426/? W/BroadcastQueue: Permission Denial: broadcasting Intent { act=com.amazonaws.amplify.pushnotification.NOTIFICATION_OPENED flg=0x10 (has extras) } from com.myapp.myappname.android.app.beta (pid=-1, uid=10476) is not exported from uid 10470 due to receiver com.myapp.myappname.android.app.prod/com.amazonaws.amplify.pushnotification.modules.RNPushNotificationBroadcastReceiver
```

I'm able to reproduce the issue using below steps:
1. Kill the App. Send yourself a notification.
2. Open the App by clicking on the App Icon (Not Notification).
3. Kill the App again.
4. Tap on the notification.
5. You'll see that notification closes but App doesn't open.

**Comment by shubham234** [comment]
@Sytree @dylan-westbury @atsneves @Yuvi7447 

Were you able to solve this issue?
