### ISSUE TITLE
Pinpoint: User automatically set OptOut ALL in Android

### ISSUE THREAD

**Issue by schoenbl** [aws-amplify/amplify-js#4419]
** Which Category is your question related to? **
Push notification
** What AWS Services are you utilizing? **
Pinpoint
** Provide additional details e.g. code snippets **
I cannot figure out how to get push notifications to work in my react native app for android.

My different aws versions in package.json:
```
    "@aws-amplify/pushnotification": "^1.1.4",
    "amazon-cognito-identity-js": "^3.0.14",
    "aws-amplify": "^1.1.40",
    "aws-amplify-react-native": "^2.1.19",
```

I had this implementation in my App.js; this works for iOS:
```
Analytics.configure(aws_exports);
Amplify.configure(aws_exports)
PushNotification.configure(aws_exports);

  componentDidMount(){
    // get the notification data when notification is received
    PushNotification.onNotification((notification) => {
      // Note that the notification object structure is different from Android and IOS
      console.log('in app notification', notification);

      // required on iOS only (see fetchCompletionHandler docs: https://facebook.github.io/react-native/docs/pushnotificationios.html)
      notification.finish(PushNotificationIOS.FetchResult.NoData);
    });
    // get the registration token
    // This will only be triggered when the token is generated or updated.
    PushNotification.onRegister((token) => {
      console.log('in app registration', token);
    });
  }
```

The issue is that, for Android, It was setting OptOut to ALL for the user.

Because of that, I moved the setup for push notifications to my main compnent after authentication.

This is my implementation:
```
  componentDidMount() {

    Analytics.configure(aws_exports);

    console.log('did mount')
    this.callCards('', null, null, null, false)

    Auth.currentAuthenticatedUser()
    .then((data) => {
        console.log('currentUser', data)

        Analytics.configure(aws_exports);
        PushNotification.configure(aws_exports);

        PushNotification.onRegister((token) => {
          //alert(token) 
          console.log('in app registration', token);
          Analytics.updateEndpoint({
              address: token, // The unique identifier for the recipient. For example, an address could be a device token, email address, or mobile phone number.
              userId: data.attributes.sub,
              optOut: 'NONE'
          }).then((data) => {
              console.log(data)
          }).catch(error => {
              console.log(error)
          })
        });
    })
  }
```
I can see that currentAuthenticatedUser fires, but` PushNotification.onRegister` does not give a token.

I'm testing my implementation in Android simulator with google apis and google playstore implemented.

Is there some specific way that you need to setup push notifications in Android that I have missing?

**Comment by dantasfiles** [comment]
If you add `Amplify.Logger.LOG_LEVEL = 'DEBUG';`
what `updateEndpoint` log lines do you see?

**Comment by dantasfiles** [comment]
I wrote up [my experiences setting up push notifications in Android](https://medium.com/@dantasfiles/setting-up-android-push-notifications-with-aws-amplify-e6334c6356d8). See if the way you set it up diverges from the way I did.
Also, there's currently a [weird endpoint bug](https://github.com/aws-amplify/amplify-js/issues/4711) that might be causing some of your problems.

**Comment by mauerbac** [comment]
Hi @schoenbl - curious if you still need assistance here ? Let us know!
