### ISSUE TITLE
Auth.currentAuthenticatedUser() returns not authenticated error after app refresh

### ISSUE THREAD

**Issue by Luckygirlllll** [aws-amplify/amplify-js#4420]
**Describe the bug**

**To Reproduce**

1. Close app 
2. Open app 
3. See not authenticated  from Auth.currentAuthenticatedUser() 

-- or --

Link to sample code

**Expected behavior**

**Screenshots**

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

</details>

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6]: Iphones and Android
- OS: [e.g. iOS8.1] all
- Version:  "aws-amplify": "^1.2.4",
**Additional context**

**Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by anthonyhumphreys** [comment]
Please see the associated issue #4351

**Comment by ericclemmons** [comment]
@Luckygirlllll After reading through #4351, it sounds very similar to what you're describing.

If it is different, please let us know in more detail how we can replicate your issue.

**Comment by Showcase-Joz** [comment]
hey @Luckygirlllll did you resolve this issue??

I am experiencing the same/similar in a Vue project.
So, for me, I can mitigate this problem like this...

`async beforeCreate() {
    try {
	await Auth.currentAuthenticatedUser()
		.then(user => {
    		    if (user) {
			user = this.$store.state.user = user;
			this.$store.state.signedIn = !!user;
			this.signedIn = !!user;
		}
	})
	.catch(err => {
		console.log(err);
	});
    } catch (err) {
        console.log(err);
    }
},`

**Comment by Luckygirlllll** [comment]
@Showcase-Joz yeah, in my case it was a problem with `AsyncStorage`, I migrated to new  `AsyncStorage` and it started working fine.

**Comment by Rolando-Barbella** [comment]
Anyone knows who to solve this?

**Comment by ericclemmons** [comment]
#4351 should resolve the "refresh" problem with AsyncStorage, so be sure to update your dependencies and give it another go.

You can also monitor the `signIn` events for getting access to `user`, as seen here:
> https://docs.amplify.aws/lib/auth/social/q/platform/js#setup-frontend

If you're still experiencing problems, feel free to open up a new issue with your specifics so we can investigate 🙏

**Comment by lucasrosa** [comment]
I was having this issue, but it was because the user was in the "NEW_PASSWORD_REQUIRED". After setting the new password it worked. Please refer to: https://docs.amplify.aws/lib/auth/manageusers/q/platform/js#complete-new-password
