### ISSUE TITLE
SAML Login without Hosted UI

### ISSUE THREAD

**Issue by anthonyhumphreys** [aws-amplify/amplify-js#4424]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
is it possible to use a SAML Provider to login without using the hosted login UI? This is really detrimental to user experience.

**Comment by cinder92** [comment]
same question here, @anthonyhumphreys did you find a solution?

**Comment by carl0shd** [comment]
Hi, is possible to login with SAML without Hosted UI, simply the provider will be the name of the provider configured in identity providers.

Example:

Auth.federatedSignIn({ provider: '<your saml name provider>' })

this bypass the Hosted UI and open your SAML directly.

**Comment by anthonyhumphreys** [comment]
Hi, sorry I forgot I'd opened this. Can confirm this works in our React Native application using a SAML provider - passing in the name of that provider takes us to our corporate SSO portal.
