### ISSUE TITLE
invalid_client error using authorization_grant flow

### ISSUE THREAD

**Issue by anthonyhumphreys** [aws-amplify/amplify-js#4426]
**Describe the bug**
Using amplify hosted UI I get an 'invalid_client' error from cognito when trying to login using a SAML provider.

**To Reproduce**

1. Configure a SAML provider for a user pool
2. Set up amplify for react native
3. Login using hostedUISignIn()

**Expected behavior**
Successful login

I get an invalid_client error which suggests, from experience/docs, that the clientId is mismatched with that configured in cognito.

**Smartphone (please complete the following information):**

- Device: iPhone 11 Pro
- OS: iOS 13.2
- Browser Safari

**Additional context**
Using token as the response type works, but then i don't get a refresh token.

**Comment by anthonyhumphreys** [comment]
Turns out this was a problem because the user pool pp client had been created (in terraform) using a client secret. Changing this to false fixed the issue. Could this be made clearer in the docs?

**Comment by simlmx** [comment]
Because I looked for it for a while!
![User_Pools_-_Amazon_Cognito](https://user-images.githubusercontent.com/1105380/94715615-b4f6b700-031b-11eb-9587-fd5ba2392e69.png)
