### ISSUE TITLE
aws-amplify-react-native: update dependency react-native-elements/react-native-vector-icons or make it less strict

### ISSUE THREAD

**Issue by t-ricci-enhancers** [aws-amplify/amplify-js#4429]
There are a lot of react-native libraries that require `react-native-elements` and `react-native-vector-icons` and managing multiple versioning of it is an hassle...

I see the `aws-amplify-react-native` package requires an explicit dependency of an old version of  `react-native-elements@^0.19.1` and `react-native-vector-icons@^5.0.0` (this should at least be less restrictive like, for example: `@>=5.0.0`).

The `react-native-vector-icons` dependency isn't needed directly by `aws-amplify-react-native` but it's a peer-dependency of `react-native-vector-icons`, so it should be removed as a dependency (it's a responsibility of developers using `aws-amplify-react-native` to install peer dependencies).

Also, `react-native-vector-icons` requires `yargs` (for command line options of some of its scripts, which is a mistake https://github.com/oblador/react-native-vector-icons/issues/1099) that is also required by a lot of other libraries (normally as a devDependency). Outdated dependencies of `yargs` often have vulnerability problems with `npm audit` (see: https://github.com/oblador/react-native-vector-icons/issues/918).

Another thing, it's completely useless to require `react-native-elements` only to use this one line in the project (amplify-js/packages/aws-amplify-react-native/src/AmplifyUI.js, line 148):
```
<Icon name="warning" color={errorIconColor} />
```
react-native-elements has a lot of components, but this one (that is the only one used) is not part of `react-native-elements` itself, but is declared in `react-native-vector-icons`. So we should drop the `react-native-elements` dependency and only require `react-native-vector-icons` instead

I'll update the package.json of `aws-amplify-react-native` to remove:
```
  "dependencies": {
    "babel-preset-es2015": "^6.24.1", // this is a devDependency!! (also use @babel/preset-env)
    "react-native-elements": "^0.19.1", // not needed
    "react-native-vector-icons": "^5.0.0" // update and/or me less specific using >=
  }
``` 
this is what I would do instead:
```
  "dependencies": {
    //...
  }, // not the three deps above, maybe just "buffer"
  "devDependencies": {
    "@babel/preset-env": "{pick a version}",
    //...
  },
  "peerDependencies": {
    "react-native-vector-icons": ">=5.0.0" // note the >= and that react-native-elements is not needed
  }
```

**Comment by amhinson** [comment]
Closing because we are removing `react-native-elements` & `react-native-vector-icons` as dependencies: https://github.com/aws-amplify/amplify-js/pull/6817
