### ISSUE TITLE
Is it possible to obtain an authorization token, server side, for the currently logged in user?

### ISSUE THREAD

**Issue by AdonousTech** [aws-amplify/amplify-js#4433]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
I am asking this question based on the documentation here: https://developer.amazon.com/docs/account-linking/app-to-app-account-linking.html#step-6

Specifically:
"The security provider that you use must authorize calls from the app to the app's backend server and provide a server-side API to get the authorization code for the user who is currently logged in to your app. (That is, it needs to provide the authorization code for the user's account in your service.) Alexa will exchange this code for your user's access token to access the user's resources."

I have never heard or used a authentication service that allows retrieving an authorization code for a currently logged in user, outside of the Authorization Code Grant Flow. According to the link above, this would need to be handled server-side. 

So I have 2 questions:
1) Is there some hidden call to get an auth code for a logged in user using the Cognito APIs;
2) If not, has anyone heard of a "security provider" or configured a "security provider" that allows this?

**Comment by harrysolovay** [comment]
> 1. Is there some hidden call to get an auth code for a logged in user using the Cognito APIs?

Yes: if the user has previously logged in, there is a persisted refresh token and device key, which are used to go through an [`InitiateAuth`](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html) handshake and get fresh tokens. This is safe.

> 2. If not, has anyone heard of a "security provider" or configured a "security provider" that allows this?

Voided by the response to `1`?

As for your question about making calls on the server-side: you can absolutely use the admin APIs to log a user in and return tokens / credentials to the front-end / session-tracker / [...xyz]... of course the security of this depends on your implementation.

**Comment by AdonousTech** [comment]
> > 1. Is there some hidden call to get an auth code for a logged in user using the Cognito APIs?
> 
> Yes: if the user has previously logged in, there is a persisted refresh token and device key, which are used to go through an [`InitiateAuth`](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html) handshake and get fresh tokens. This is safe.
> 
> > 1. If not, has anyone heard of a "security provider" or configured a "security provider" that allows this?
> 
> Voided by the response to `1`?
> 
> As for your question about making calls on the server-side: you can absolutely use the admin APIs to log a user in and return tokens / credentials to the front-end / session-tracker / [...xyz]... of course the security of this depends on your implementation.

Sorry for the delay @harrysolovay . 

I meant to say "THANK YOU" for clarifying #1 above. I really appreciate it!
