### ISSUE TITLE
TypeError on Auth.resendSignUp()

### ISSUE THREAD

**Issue by jakobpack** [aws-amplify/amplify-js#4435]
Receiving following error after calling `Auth.resendSignUp()` in a React app:

`TypeError: JSON.stringify cannot serialize cyclic structures.`

I'm importing `Auth` via `import { Auth }  from 'aws-amplify'` and calling it with a valid string as a username parameter.
(I get the same error with an invalid username)

**Package versions:**
```
aws-amplify: ^1.2.4 => 1.2.4 
aws-amplify-react: ^2.5.4 => 2.5.4 
aws-appsync: ^1.8.1 => 1.8.1 
aws-appsync-react: ^1.2.9 => 1.2.9 
```

**Additional context**
All other `Auth` methods are working fine.

**Comment by haverchuck** [comment]
@jakobpack I am unable to reproduce this.  The test app I'm using is not using appsync, but it is using the exact versions of amplify and amplify-react which you've cited.  

Can you post a code snippet showing how you're calling the resendSignUp method?

**Comment by jakobpack** [comment]
@haverchuck It was indeed a error on my site.
After going through the code, I saw that I set the `button click event` as first parameter of my `resend` method, but didn't use it in the method declaration...
