### ISSUE TITLE
Poor login performance on IE Edge

### ISSUE THREAD

**Issue by kqumsieh** [aws-amplify/amplify-js#4437]
**Describe the bug**
Login performance is much slower ~6-9 seconds on IE Edge vs almost instantaneous on Chrome and Firefox.
We are using the authenticator module in Vue app.

**To Reproduce**
Create a Vue app and add amplify and amplify-vue latest (1.2.4 and 0.3.3).  Create authentication using the "amplify-authenticator" module.

**Expected behavior**
almost instantaneous on [AWS supported browsers](https://aws.amazon.com/premiumsupport/knowledge-center/browsers-management-console/)

I attached the network calls from Edge vs Chrome.  Edge is doing a lot more calls for some reason.

Edge:
![edge_network_calls](https://user-images.githubusercontent.com/37556705/69362162-fc240e00-0c5b-11ea-9215-b94ca6e0f8e0.png)

Chrome:
![chrome_network_calls](https://user-images.githubusercontent.com/37556705/69362163-fc240e00-0c5b-11ea-82e7-70bee6853a0e.png)

**Comment by ronwarner1231** [comment]
I am experiencing the same slow amplify-authenticator authentication but Edge is taking about 15 seconds while Chrome is taking less than 2 seconds.

**Comment by kqumsieh** [comment]
After more research into this.  I found the root cause of the issue to be related to Vue "vue-cli-service build" because when we run the Vue app locally using "vue-cli-service serve" the application runs as expected.  Looking more into "vue-cli-service build" vs "vue-cli-service serve" and trying multiple option like "--mode production" and update Babel and polyfills did not take us anywhere.

Having this said, I do not think this is an Amplify issue but more of Vue/Webpack issue.

**Comment by Amplifiyer** [comment]
@kqumsieh Were you able to dive deep more into the issue?
