### ISSUE TITLE
Error Using Analytics Module 

### ISSUE THREAD

**Issue by uttam23** [aws-amplify/amplify-js#4448]
Hi 
Below is the code base for using analytics in module way .
But we are getting error :
**[Error: No credentials, applicationId or region](url
<img width="520" alt="Screenshot 2019-11-22 at 5 35 05 PM" src="https://user-images.githubusercontent.com/6542709/69424392-7fbe2780-0d4e-11ea-9151-95e3907e7645.png">
)**

Below is the code for the same  : 
import Amplify from "@aws-amplify/core";
import Analytics  from "@aws-amplify/analytics";
import aws_exports from "../config/aws-exports";
Amplify.configure(aws_exports);
Analytics.record({name:'test'});

**Comment by sammartinez** [comment]
@uttam23 Can you provide more information, such as your `package.json`, framework you are using with Amplify. Thanks ahead of time.

**Comment by uttam23** [comment]
@sammartinez we are using react  Version 16.8.0 .
Please find the package.json details .
{
  "homepage": "/xxxx,
  "name": "XXXXX",
  "version": "X.X.X",
  "private": true,
  "dependencies": {
    "@aws-amplify/analytics": "^1.3.4",
    "@aws-amplify/core": "^1.2.4",
    "@babel/core": "^7.0.0",
    "@date-io/moment": "1.0.2",
    "@material-ui/codemod": "^4.5.0",
    "@material-ui/core": "^4.0.0",
    "@material-ui/icons": "^3.0.1",
    "@material-ui/lab": "^3.0.0-alpha.13",
    "@syncfusion/ej2-react-circulargauge": "^16.2.50",
    "ajv": "^6.5.2",
    "aws-amplify": "^1.1.5",
    "axios": "^0.18.0",
    "classnames": "latest",
    "device-uuid": "^1.0.4",
    "eslint-config-react-app": "^3.0.3",
    "file-loader": "^2.0.0",
    "hoek": "^6.0.0",
    "inline-source": "^6.1.8",
    "inline-source-cli": "^2.0.0",
    "lodash": "^4.17.11",
    "material-ui-pickers": "2.2.4",
    "moment": "^2.24.0",
    "prop-types": "latest",
    "query-string": "^6.2.0",
    "react": "^16.8.0",
    "react-copy-to-clipboard": "^5.0.1",
    "react-dom": "^16.8.0",
    "react-google-login-component": "^0.9.3",
    "react-lazy-load-image-component": "^1.1.5",
    "react-lottie": "^1.2.3",
    "react-pure-lifecycle": "^3.0.0",
    "react-redux": "^7.1.0",
    "react-router-dom": "^5.0.1",
    "react-scripts": "^3.2.0",
    "react-spinners": "^0.4.8",
    "react-swipeable-views": "^0.13.1",
    "react-swipeable-views-utils": "^0.13.1",
    "react-text-mask": "^5.4.3",
    "redux": "^4.0.0",
    "redux-thunk": "^2.3.0",
    "source-map-explorer": "^2.1.1",
    "sw-precache-webpack-plugin": "^0.11.5"
  },
  "scripts": {
    "analyze": "source-map-explorer 'build/static/js/*.js'",
    "test": "react-scripts test --env=jsdom",
    "eject": "set HTTPS=true&&react-scripts eject"
  },
  "devDependencies": {
    "babel-plugin-transform-imports": "^2.0.0",
    "customize-cra": "^0.9.1",
    "react-app-rewired": "^2.1.5",
    "uglify-js-brunch": "^2.10.0"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11"
  ]
}

**Comment by haverchuck** [comment]
@uttam23 Are your analytics events being recorded despite this error?

**Comment by uttam23** [comment]
Thank you for the help.It is working now and events are getting logged .

**Comment by mhopey** [comment]
I am also having a similar issue where my analytics events are not being recorded. I've updated my unauth role for identity pool to include the policy as outlined in the amplify docs. Is there any documentation that shows the aws-exports fields needed for this analytics config? I'm using a manually created aws-exports file with this set up:
{
    "aws_project_region": "xxx",
    "aws_cognito_identity_pool_id": "xxx",
    "aws_cognito_region": "xxx",
    "aws_user_pools_id": "xxx",
    "aws_user_pools_web_client_id": "xxx",
    "aws_appsync_region": "xxx",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "xxx",
    'aws_app_analytics': 'enable',
    "aws_mobile_analytics_app_id": "xxx",
    'aws_mobile_analytics_app_region':"xxx"
}

It is a react native app, and uses the same imports/config as @haverchuck has described. I've also tried using Analytics.configure() with the appId, and region. Any help getting this up and running would be greatly appreciated! Thanks

**Comment by evanlarkin10** [comment]
Has anyone found a solution for this? I am getting the same issue.

"@aws-amplify/analytics": "~3.2.1",
"@aws-amplify/api": "~3.1.9",
"@aws-amplify/auth": "~3.2.5",
"@aws-amplify/core": "~3.2.5",
"@aws-amplify/storage": "~3.2.0",
Expo SDK 37 => react-native 0.61

const awsmobile = {
 "aws_project_region": "us-east-1",
 "aws_cognito_identity_pool_id": "us-east-1:xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
 "aws_cognito_region": "us-east-1",
 "aws_user_pools_id": "us-east-1_xxxxxxxxx",
 "aws_user_pools_web_client_id": "xxxxxxxxxxxxxxxxxxxxx",
 "oauth": {},
 "aws_user_files_s3_bucket": "dinnerbellxxxxxx-dev",
 "aws_user_files_s3_bucket_region": "us-east-1",
 "aws_mobile_analytics_app_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
 "aws_mobile_analytics_app_region": "us-east-1"
}
