### ISSUE TITLE
Create Account button is disabled after validate missing fields

### ISSUE THREAD

**Issue by christopherABM** [aws-amplify/amplify-js#4449]
When the user is creating a new account in the sign up form, if the user miss some field such as the email the library displays a toast with message "The following fields need to be filled out: Email"
that is ok but once that the user fill the input and tries again to click in the button "create account" the button is disabled
![Screenshot from 2019-11-22 09-14-02](https://user-images.githubusercontent.com/27704876/69437435-eb7da180-0d08-11ea-82d2-0b3a4e793e78.jpg)

**Comment by haverchuck** [comment]
@christopherABM  - Which framework package are you using (e.g. aws-amplify-angular, aws-amplify-react, etc)?

**Comment by christopherABM** [comment]
I'm using aws-amplify-react and I am using the default config no custom components 

> export default withAuthenticator(Login, false)

**Comment by haverchuck** [comment]
@christopherABM I've submited[ a PR to fix this](https://github.com/aws-amplify/amplify-js/pull/4480).

**Comment by jordanranz** [comment]
Reopening. We can close when the PR has been merged.

**Comment by haverchuck** [comment]
@christopherABM We have merged a PR to our master branch.  It should be on the unstable NPM tag shortly.
