### ISSUE TITLE
PubSub Javascript: How to detect websocket closed and reconnect?

### ISSUE THREAD

**Issue by markmacau** [aws-amplify/amplify-js#4459]
** Which Category is your question related to? **
PubSub Javascript(vue)

** What AWS Services are you utilizing? **
PubSub, IoT, Cognito(Unauth)

** Provide additional details e.g. code snippets **
Somehow my MQTT connection drops even after successfully subscribed a topic and send/receive messages.

1) How can I detect/monitor MQTT connection status? In other word, How can I access AWSIoTProvider created by Amplify.addPluggable?

2) After MQTT disconnect and even I unsubscribe then subscribe topic again, I cannot publish message any more with error "AMQJS0011E Invalid state not connected". 

So far only solution is to reload page. Is there any better way to recover session?

3) Above "AMQJS0011E Invalid state not connected." error can be a trigger to reconnect socket. How to set eventlisteners on such errors?

**Comment by escar** [comment]
Having this issue too, any way to overcome this problem?

**Comment by houmark** [comment]
It's really starting to become a problem for us, that we cannot in any way check the current connection status and reconnect in any reliable way.

The simplest use case is a browser tab staying open while the user putting her computer to sleep, then resumes work without refreshing the UI/tab. The UI will stop providing realtime updates, and there's no way we have found, where we can even request a connection status.

**Comment by kevin-mitchell** [comment]
Also interested in tracking this!

**Comment by dcoellarb** [comment]
any updates on this?

**Comment by nitindatta** [comment]
anyone found workaround for this.

**Comment by pieterbergmans** [comment]
This seems to happen quite often.  Any solutions?

**Comment by stocaaro** [comment]
Some good news. Detecting socket status changes [just got a whole lot easier](https://www.google.com/maps/d/edit?mid=1R7JcHfuNwVnet-g6OBs1XdMU5h7s8Rw&usp=sharing) with new Hub messages.

Work is inflight to [add automated reconnection](https://github.com/aws-amplify/amplify-js/pull/10235).

**Comment by nubpro** [comment]
> Some good news. Detecting socket status changes [just got a whole lot easier](https://www.google.com/maps/d/edit?mid=1R7JcHfuNwVnet-g6OBs1XdMU5h7s8Rw&usp=sharing) with new Hub messages.
> 
> Work is inflight to [add automated reconnection](https://github.com/aws-amplify/amplify-js/pull/10235).

might want to check on the link you posted...

**Comment by stocaaro** [comment]
Good catch. Thanks to @abdallahshaban557 for proactively fixing this!

**Comment by stocaaro** [comment]
Reconnection is now staged on the `next` tag in preparation for release in aws-amplify v5. To test against this update install the `next` tag version of the aws-amplify packages your project is using. eg `yarn add aws-amplify@next`.

With this change any disrupted connection will attempt to reconnect when possible. Reconnection can be expected to trigger 5 seconds after the resources to reconnect are available. If the network is disrupted in a way that can't be detected, reconnection will be attempted every minute until the connection is recovered.

Note that missed messages will not backfill on recovery. If you need to trigger behavior to catch up missed messaged on recovery, this should be possible to implement using the [connection state Hub messages](https://docs.amplify.aws/lib/pubsub/subunsub/q/platform/js/#unsubscribe) released last month.

**Comment by stocaaro** [comment]
Good news. Automated Reconnection is now available on the latest `aws-amplify` release! Review the [updated subscription docs](https://docs.amplify.aws/lib/pubsub/subunsub/q/platform/js/#connection-issues-and-automated-reconnection) and consider any application behavior you may want to add to best meet your users needs when subscriptions reconnect.

Please review our [breaking change guidance](https://github.com/aws-amplify/amplify-js#notice) before upgrading your application.

To upgrade Amplify to version 5, run the following in your project folder:
```
yarn add aws-amplify@latest
```

Check `package.json` to see if your project uses other `@aws-amplify/*` packages directly and upgrade them to latest as well.

With this behavior released, I am closing this issue as resolved.
