### ISSUE TITLE
How to refresh Cognito tokens

### ISSUE THREAD

**Issue by nomadus** [aws-amplify/amplify-js#446]
There is a similar issue in https://github.com/aws/aws-amplify/issues/405, but the OP uses old approach, I would like to know how to refresh tokens based on aws-amplify library?
Also, this is probably related, how could I make sure that the user is always logged in?

**Comment by tipsfedora** [comment]
i literally tried **everything**  
wait 1hr
refresh (works fine)
wait 1hr
refresh (error login token expired)

**Comment by nomadus** [comment]
I would like to achieve the same with amplify library.

**Comment by nomadus** [comment]
I had used 
`// for automatic signin of a user (so they don't have to login each time)
export function retrieveUserFromLocalStorage() {
	return new Promise((success, failure) => {
		// grab the `cognitoUser` object from `userPool`
		// this is possible without login because we had already logged in before (whereas verifyPIN and resetPassword have not)
		const cognitoUser = userPool.getCurrentUser();
		if (cognitoUser != null) {
			// get the latest session from `cognitoUser`
			cognitoUser.getSession(function (error, session) {
				// if failed to get session, reject the promise
				if (error) {
					console.log('Error occurred while retrieving user account', error);
					failure(error);
					return;
				}
				// check that the session is valid
				console.log('Is session still valid?: ' + session.isValid());
				// save to localStorage the jwtToken from the `session`
				localStorage.setItem('idToken', session.getIdToken().getJwtToken());

				// Edge case, AWS Cognito does not allow for the Logins attr to be dynamically generated. So we must create the loginsObj beforehand
				const loginsObj = {
					// our loginsObj will just use the jwtToken to verify our user
					[USERPOOL_ID]: session.getIdToken().getJwtToken()
				}
				// create a new `CognitoIdentityCredentials` object to set our credentials
				// we are logging into a AWS federated identity pool
				AWS.config.credentials = new AWS.CognitoIdentityCredentials({
					IdentityPoolId: IDENTITY_POOL_ID, // your identity pool id here
					Logins: loginsObj
				})
				// refresh the credentials so we can use it in our app
				AWS.config.credentials.refresh(function () {
					// resolve the promise by again building the user object to be used in our React-Redux app
					success(buildUserObject(cognitoUser))
				})
			});
		} else {
			// if failure, reject the promise
			failure('Failed to retrieve user from localStorage');
		}
	`
To refresh user session, are you using the same?

**Comment by tipsfedora** [comment]
Yes, i'm pretty much doing the same thing. I've tried many variations. There seems to be a bug because i can successfully refresh after 1 hr, but after 2hrs i suddenly receive an error, although the login token should still be valid.

**Comment by nomadus** [comment]
If this is a bug, could you try with different version of aws cognito packages?

**Comment by tipsfedora** [comment]
I was using a ~ 1 year old version, than updated to the latest version of cognito and cognito identity, both didn't work.

**Comment by retwedt** [comment]
I am also trying to figure this out, anyone have any luck?

**Comment by tipsfedora** [comment]
No. Since i can only refresh successfully once i'm doing it like this now:

```
    if(AWS.config.credentials.expired) {
      confirm("Session is expired, Page needs to be refreshed!");
      if((confirm()) == true) {
        location.reload();
      }
    }
```

**Comment by Legym** [comment]
```
import { Auth } from 'aws-amplify';

        // Async call to Cognito to check for token
        // This will be checked every time a protected route is loaded
        Auth.currentSession()
            .then((response) => {

                Axios.defaults.headers.common = {
                    authToken: response.idToken.jwtToken,
                };

            })
            .catch((error) => {
                console.log(error);
            });
```

**Comment by nomadus** [comment]
How about this?
`export const keepAlive = () => {
    if (!Auth.credentials) { Auth.setCredentialsForGuest(); }

    const ts = new Date().getTime();
    const delta = 10 * 60 * 1000; // 10 minutes
    let credentials = Auth.credentials || {};
    const { expired, expireTime } = credentials;

    if (!expired && expireTime > ts + delta) {
        return Promise.resolve(credentials);
    }

    return new Promise((resolve, reject) => {
        Auth.currentUserCredentials()
            .then(() => {
                credentials = Auth.credentials;
                credentials.refresh(error => {
                    _Logger.debug('Credentials are changed from previous');
                    if (error) {
                        _Logger.debug('Credentials refresh error', error);
                        resolve(null);
                    } else {
                        _Logger.debug('Credentials has been refreshed', credentials);
                        resolve(credentials);
                    }
                });
            })
            .catch(() => resolve(null));
    });
}`

**Comment by bbernays** [comment]
I have the same issue. I have taken to forcing the user to do a page reload.

**Comment by bbernays** [comment]
There seems to be a lot of questions on how to do this. Could it be possible that an example of this be added to the documentation?

**Comment by tipsfedora** [comment]
**yeeeeeeeeeeeeeeeeeeeeeeeeeeeah, after almost 2 weeks i finally solved it.**

you need the refresh token to receive a new id token. update the aws.config.credentials object now with this new token.

here is an example of my code, which runs smoothly!

```

      refresh_token = session.getRefreshToken();   // you'll get session from calling cognitoUser.getSession()
      if (AWS.config.credentials.needsRefresh()) {
        clearInterval(messwerte_updaten);
        cognitoUser.refreshSession(refresh_token, (err, session) => {
          if(err) {
            console.log(err);
          } 
          else {
            AWS.config.credentials.params.Logins['cognito-idp.eu-central-1.amazonaws.com/eu-central-XXX']  = session.getIdToken().getJwtToken();
            AWS.config.credentials.refresh((err)=> {
              if(err)  {
                console.log(err);
              }
              else{
                console.log("TOKEN SUCCESSFULLY UPDATED");
                mainPoll();
              }
            });
          }
        });
      }
```

**Comment by bbernays** [comment]
@tipsfedora thank you very much for this! I will definitely check it out!!

**Comment by powerful23** [comment]
Closing the issue. Feel free to reopen it if necessary.

**Comment by retwedt** [comment]
It would be nice to get some guidance on how to do this with the Amplify lib.  It appears to me that the session is automatically refreshed if expired, but there is no way to refresh the token early.  Is that the case?

**Comment by mlabieniec** [comment]
@retwedt that's correct, the session is automatically refreshed, you could technically refresh the token yourself however by doing this same approach since the amplify lib uses the cognito lib under the covers. We are working on giving more flexibility / simplifying this as well (in our backlog) to both refresh and also disable automatic refresh.

**Comment by retwedt** [comment]
Great thanks!

**Comment by Jasminou** [comment]
I wasn't sur about how to manage the refresh token and how to ask for id and access tokens, so if we are using aws amplify, all this is happened under cover, I don't have to ask for new id token or access token right ?

**Comment by powerful23** [comment]
@Jasminou yes aws amplify will refresh your session automatically if expired.

**Comment by jamesoflol** [comment]
It will refresh if you call the API for it, e.g., with Auth.currentSession(), and it finds an expired token + a valid refresh token.

AFAIK there's no timing mechanism to update your localStorage for you in the background. (Auth0's JS SDK uses setTimeout to update localStorage, but that's got its own issues.) If like me you're using Amplify just for the auth, and doing the rest with REST, then you'll want to call Auth.currentSession() before every API call, to get the latest access token. E.g. using Axios HTTP request framework:

    // Add latest auth access token to every http request
    axios.interceptors.request.use(function (config) {
      return Auth.currentSession()
        .then(resp => {
          config.headers.Authorization = 'Bearer ' + resp.accessToken.jwtToken
          return Promise.resolve(config)
        })
    })

**Comment by powerful23** [comment]
@jamesiri yes. The session will be refreshed when calling `Auth.currentSession()` and Amplify will also call `Auth.currentCredentials()` before sending any request to AWS services like S3, Pinpoint so the credentials get automatically refreshed.

**Comment by StevenDufresne** [comment]
@jamesoflol It's probably a good idea to catch `Auth.currentSession()` and resolve in case you make unauthenticated calls.

**Comment by jamesoflol** [comment]
@StevenDufresne Agreed. I'll update my example as it seems this issue gets some traffic

**Comment by nihakue** [comment]
Hey, it seems as though Amplify only handles credential refresh if we are using the 'code' / Auth flow. What is the guidance for automatically refreshing tokens if we are using 'token' / implicit flow, and have no refresh token? At the moment, Amplify just falls back to making unauthenticated requests (https://github.com/powerful23/aws-amplify/blob/5b67de9bff7797efe7262e6f600889310450c6ae/packages/amazon-cognito-identity-js/src/CognitoUser.js#L1157). I would love to be able to use implicit flow and not have to worry about my session expiring.

Ideally I would like to be able to do this silently without interrupting the user's workflows /refreshing the page. Is that something that is possible? I've found it very difficult to answer these questions, but would be happy to contribute to documentation if I could come up with a sanctioned solution.

For reference, my setup is:

- Cognito User pool with federated identities (Using a company internal SAML federated idp)
- Using Cognito Federated Identity Pool with User pool set as IdP
- Using @aws-amplify/auth@1.0.2 with oauth setup with the following call when `Auth.currentAuthenticatedUser` throws:
```js
const url = `https://${domain}/oauth2/authorize?client_id=${clientId}&redirect_uri=${redirectSignIn}&response_type=${responseType}&prompt=none`;

  window.location.assign(url);
```
- Using @aws-amplify/api@1.0.2 to call API Gateway + Lambda (not using custom headers, since API gateway is using AWS_IAM authentication instead of User Pool)

I'm seeing that after my session expires, amplify tries to refresh my access token using the refresh token, but there isn't one since I'm using token / implicit flow. Failing that, it seems to give up and use guest user instead, which my identity pool doesn't (and won't) support.

Thanks for your help!

**Comment by kevlarr** [comment]
It would definitely be helpful if [the documentation](https://aws-amplify.github.io/docs/js/authentication#retrieve-current-session) actually mentioned that behavior for `currentSession()`. We are only using Auth, so we aren't using other modules that will automatically refresh, and we'd opted for the "set timeout to refresh tokens manually" approach until finding this thread.

**Comment by powerful23** [comment]
@kevlarr hi, thanks for your feedback. I have sent a pr accordingly: https://github.com/aws-amplify/docs/pull/535

**Comment by kevlarr** [comment]
Whoa, seriously @powerful23? You are a rockstar! Apologies for not doing that myself.

**Comment by powerful23** [comment]
@kevlarr No problem! It's great to have those feedbacks that would gradually improve the docs.

**Comment by JLee21** [comment]
In case I'm not too late to the party, I noticed that [Amplify's API docs](https://aws-amplify.github.io/docs/js/api#custom-request-headers) suggest setting a custom header when you first configure the Amplify settings.

```javascript
Amplify.configure({
  API: {
    endpoints: [
      {
        name: "sampleCloudApi",
        endpoint: "https://xyz.execute-api.us-east-1.amazonaws.com/Development",
        custom_header: async () => { 
          // With Cognito User Pools use this:
          return { Authorization: (await Auth.currentSession()).idToken.jwtToken } 
        }
      }
    ]
  }
});
```

I like this approach because now every request is syntatically simple

```javascript
API.get('myRestEndpoint', "/mystuff")
```

**Comment by kevlarr** [comment]
@JLee21 Oh that's excellent, thank you. We have only been using the `Auth` module so had not seen that regarding the `API` module. Looks like it might be worth using instead of rolling our own mini-lib to handle refreshing tokens.

**Comment by justingrant** [comment]
FYI, for any others who end up here from Google, if you're using Cognito Identity Pools without Cognito User Pools, then @JLee21's sample above can be adapted as follows: 

```javascript
Amplify.configure({
  API: {
    endpoints: [
      {
        name: "sampleCloudApi",
        endpoint: "https://xyz.execute-api.us-east-1.amazonaws.com/Development",
        custom_header: async () => {
          // fetch the user that was previously authenticated with Facebook via a call
          // to `await Auth.federatedSignIn()`
          const user = await Auth.currentAuthenticatedUser();
          console.log (`will authenticate to AWS with this user: ${JSON.stringify(user)}`);
          return { 'cognito-identity-id' : user.id } 
          // With Cognito User Pools use the code below instead
          // return { Authorization: (await Auth.currentSession()).idToken.jwtToken } 
        }
      }
    ]
  }
}); 
```

**Comment by mzohaibqc** [comment]
Unfortunately, Amplify docs do not mention how to refresh token on demand but they always keep saying that Amplify will refresh when required but what if I want to refresh token now, I need to refresh due to some reason, they had not told us. Let's come to the point, here is now you can refresh token on demand.

```
   import { Auth } from 'aws-amplify';

    try {
        const cognitoUser = await Auth.currentAuthenticatedUser();
        const currentSession = await Auth.currentSession();
        cognitoUser.refreshSession(currentSession.refreshToken, (err, session) => {
          console.log('session', err, session);
          const { idToken, refreshToken, accessToken } = session;
          // do whatever you want to do now :)
        });
      } catch (e) {
        console.log('Unable to refresh Token', e);
      }
```

**Comment by AndriiShtoiko** [comment]
@mzohaibqc works like magic. thanks!

**Comment by dcsena** [comment]
@justingrant @JLee21 

How would this be done in an app that uses both cognito user pools and federated fb/google sign in? Do you have an easy way to combine the two that you have proposed?

**Comment by harsh-softvan** [comment]
if you are using amplifyJS than this will helpful for you>>>>>
https://aws-amplify.github.io/docs/js/authentication#retrieve-current-session

**Comment by bradennapier** [comment]
I keep running into cases where when passing the token to our api it says token expired.  Not sure whats up as we are definitely calling `Auth.currentSession()` before every request.

**Comment by rawadrifai** [comment]
Amplify does not allow refreshing your tokens directly for good reasons.
Long story short, you can retrieve a "CognitoUser" object from Amplify AuthClass using the `currentAuthenticatedUser` and from there you can do what a CognitoUser can do.

**Comment by b0morris** [comment]
I ran into a situation where my Cognito JWT token was expiring on long-running S3 uploads (fails at the 1 hour mark). I couldn't find anything that gave a solution as to how you refresh the token in the middle of a request, so after hours of digging through the Amplify lib and AWS SDK, I finally figured out a solution. You do have to use the AWS SDK directly (sorry Amplify Storage), but I was already doing that so I could pass in the queueSize option to fix the other timeout issue.

When using the AWS SDK, you basically have two options for passing in credentials: 1) the S3 constructor, and 2) the global AWS config. Amplify seems to always pass them in through the constructor, and I'm not sure you can update them that way; however, if you just set the credentials in the global AWS config, you can update the JWT token directly every time you refresh it.

So first I grab the current user's credentials and store it in AWS.config.credentials:
```javascript
import {Credentials} from '@aws-amplify/core'

Credentials.get().then(creds => {
   AWS.config.credentials = creds
})
```

Then you can instantiate a S3 object without passing in credentials and start your upload. 

```javascript
const s3 = new S3({
  apiVersion: '2006-03-01',
  signatureVersion: 'v4',
  region: 'us-west-2',
  params: {Bucket: bucket}
})
// Upload params and opts here.
const upload = s3.upload(params, opts).on('httpUploadProgress', progress => {...}).promise()
```

Then what I do is use `setInterval()` to call a refresh method every so often. Technically the Cognito token last for an hour, so you can refresh it every 50 minutes or use `AWS.config.credentials.needsRefresh()` to keep it more generic.

```javascript
const refreshToken = async () => {
    var session = await Auth.currentSession() //Will refresh token if needed.
    const region = Amplify._config.aws_project_region
    const user_pool_id = Amplify._config.aws_user_pools_id
    AWS.config.credentials.params.Logins['cognito-idp.'+region+'.amazonaws.com/'+user_pool_id] = session.getIdToken().getJwtToken()
    AWS.config.credentials.refresh((err) => {
        if(err)
            console.log("Error updating token")
        else
            console.log("Token updated")
    })
}

const cRef = setInterval(refreshToken, 50*60*1000)
```

I'm sure I'm violating some best practices here but it works. Just don't forget to `clearInterval()` when the upload finishes or catches an error.

And the code that @david114 posted earlier definitely sent me down the right path. I just added in the Amplify way of refreshing the JWT token instead of doing it manually just to keep Amplify in sync with S3. That code can be found in the `amplify-js` lib [here under Use Case 32](https://github.com/aws-amplify/amplify-js/blob/master/packages/amazon-cognito-identity-js/README.md)

Really hope this helps someone. Spent way too long trying to figure it out. :P

**Comment by mzohaibqc** [comment]
@b0morris Thanks a lot for sharing your solutions. A few months ago, actually in April, I faced the same issue that S3 uploads were failing if file upload took more than 1 hour so even after a lot of struggle, I could not find the right solution to refresh token that is being used by S3 upload. So I finally had to use custom `temporary credentials` from backend API to upload large files. 

Amplify needs to handle this scenario but they always keep saying, it will automatically refresh the token but it's will not in such case.

Another issue or limitation with Cognito based credentials is that we can't restrict uploads on an s3 path based on some custom usepool attribute e.g. role or TenantID. but anyway, Thanks for sharing :)

**Comment by ripundeep** [comment]
@david114 the solution that you proposed actually giving me an exception repeatedly:
 _TypeError: Cannot read property 'Logins' of undefined_
Please suggest what could be the issue because in credentials there is no key exists named as 'params'.

**Comment by david114** [comment]
@ripundeep 

What Libaries are you using? Our Website is quite old now and we are not using AWS Amplify at all.

We're using:
aws-sdk-2.172.0.min.js
aws-cognito-sdk.min.js
amazon-cognito-identity.min.js

Using these files, I can call AWS.config.credentials.params.Logins without any problems

**Comment by ripundeep** [comment]
@david114  thanks for the reply. I am working on node-js and using amazon-cognito-identity-js. I guess you have utilized in another JavaScript.

**Comment by david114** [comment]
@ripundeep we're using plain client-sided javascript

**Comment by jeffsheets** [comment]
FWIW in case it helps anyone else, I was initially thinking that `Auth.currentSession()` was not refreshing the token. But in my case we are listening for auth changes with `Hub` to store our token and make api calls outside of the amplify api library by using axios direct. But when `Auth.currentSession()` refreshes the token it does not fire a `Hub` event so our application did not know that a token was updated.

Feels like a bug that no event is fired when a refresh token happens. So for now I've added an axios interceptor to insert the token from `Auth.currentSession()` into every axios call.

**Comment by justingrant** [comment]
@jeffsheets - care to share the code you used for that interceptor in case it might be useful to others?

**Comment by jeffsheets** [comment]
@justingrant Oh yep, here you go! This uses the Axios Interceptors setup to inject the Auth token on every call. I can't remember why our app uses idToken instead of accessToken, so depending on the app that might have to change, but here's the general idea. https://github.com/axios/axios#interceptors

```javascript
export const axiosRequestInterceptor = async config => {
  //This will get the cached session, or refresh the token first if it has expired
  const session = await Auth.currentSession();

  if (session && session.idToken) {
    config.headers.Authorization = session.idToken.jwtToken;
  }
  return config;
};
axios.interceptors.request.use(axiosRequestInterceptor, e => Promise.reject(e));
```

**Comment by Christilut** [comment]
This is what I do with axios on every request:
```ts
axios.interceptors.request.use(async function (config: AxiosRequestConfig) {
  const session = await Auth.currentSession()

  try {
    const token = session.getAccessToken().getJwtToken()

    config.headers.authorization = token
  } catch (error) {
    log.error(error)

    await store.dispatch('auth/logout')

    await router.push({
      name: 'login'
    })
  }

  return config
}, async function (error: AxiosError) {
  return Promise.reject(error)
})
```

And because sometimes my users get logged out randomly, I refresh the token manually on an interval (still experimenting with this):
```ts
let cognitoKeepaliveInterval: any = null

function startCognitoKeepaliveInterval() {
  if (cognitoKeepaliveInterval) clearInterval(cognitoKeepaliveInterval)

  cognitoKeepaliveInterval = setInterval(async () => {
    const session = await Auth.currentSession()
    const user = await Auth.currentAuthenticatedUser()

    user.refreshSession(session.getRefreshToken(), () => {
      log.info('refreshed auth session')
    })
  }, 30 * 60 * 1000) // 30 minutes
}
```

**Comment by artuska** [comment]
Well, i don't understand — if i console.log session token it remains the same:

```let session = await Auth.currentSession();
let token = session.getAccessToken().getJwtToken();
console.log(token); // this token is always the same...```

So... what is the point of running the `currentSession`?

**Comment by ahallora** [comment]
@artuska , from the documentation: https://aws-amplify.github.io/docs/js/authentication#retrieve-current-session

> This method will automatically refresh the accessToken and idToken if tokens are expired and a valid refreshToken presented. So you can use this method to refresh the session if needed.

**Comment by norbertdurcansk** [comment]
> I ran into a situation where my Cognito JWT token was expiring on long-running S3 uploads (fails at the 1 hour mark). I couldn't find anything that gave a solution as to how you refresh the token in the middle of a request, so after hours of digging through the Amplify lib and AWS SDK, I finally figured out a solution. You do have to use the AWS SDK directly (sorry Amplify Storage), but I was already doing that so I could pass in the queueSize option to fix the other timeout issue.
> 
> When using the AWS SDK, you basically have two options for passing in credentials: 1) the S3 constructor, and 2) the global AWS config. Amplify seems to always pass them in through the constructor, and I'm not sure you can update them that way; however, if you just set the credentials in the global AWS config, you can update the JWT token directly every time you refresh it.
> 
> So first I grab the current user's credentials and store it in AWS.config.credentials:
> 
> ```js
> import {Credentials} from '@aws-amplify/core'
> 
> Credentials.get().then(creds => {
>    AWS.config.credentials = creds
> })
> ```
> 
> Then you can instantiate a S3 object without passing in credentials and start your upload.
> 
> ```js
> const s3 = new S3({
>   apiVersion: '2006-03-01',
>   signatureVersion: 'v4',
>   region: 'us-west-2',
>   params: {Bucket: bucket}
> })
> // Upload params and opts here.
> const upload = s3.upload(params, opts).on('httpUploadProgress', progress => {...}).promise()
> ```
> 
> Then what I do is use `setInterval()` to call a refresh method every so often. Technically the Cognito token last for an hour, so you can refresh it every 50 minutes or use `AWS.config.credentials.needsRefresh()` to keep it more generic.
> 
> ```js
> const refreshToken = async () => {
>     var session = await Auth.currentSession() //Will refresh token if needed.
>     const region = Amplify._config.aws_project_region
>     const user_pool_id = Amplify._config.aws_user_pools_id
>     AWS.config.credentials.params.Logins['cognito-idp.'+region+'.amazonaws.com/'+user_pool_id] = session.getIdToken().getJwtToken()
>     AWS.config.credentials.refresh((err) => {
>         if(err)
>             console.log("Error updating token")
>         else
>             console.log("Token updated")
>     })
> }
> 
> const cRef = setInterval(refreshToken, 50*60*1000)
> ```
> 
> I'm sure I'm violating some best practices here but it works. Just don't forget to `clearInterval()` when the upload finishes or catches an error.
> 
> And the code that @david114 posted earlier definitely sent me down the right path. I just added in the Amplify way of refreshing the JWT token instead of doing it manually just to keep Amplify in sync with S3. That code can be found in the `amplify-js` lib [here under Use Case 32](https://github.com/aws-amplify/amplify-js/blob/master/packages/amazon-cognito-identity-js/README.md)
> 
> Really hope this helps someone. Spent way too long trying to figure it out. :P

Thank you for your solution. We had the same issue with large uploads.  We tried many solutions but none of them worked for us. 

A good start is to check `AWSS3Provider` implementation:
https://github.com/aws-amplify/amplify-js/blob/a047ce73/packages/storage/src/Providers/AWSS3Provider.ts#L62

We created a custom `Storage` class according to `AWSS3Provider` but with authentication refresh.
```jsx
import { AWS } from "@aws-amplify/core";
import { Auth } from "aws-amplify";

export default class Storage {
  private _refreshTimeout;
  // Token expiration is 60 min
  private readonly REFRESH_INTERVAL = 50 * 60 * 1000; // 50 min
  private readonly MIN_REFRESH_INTERVAL = 30 * 1000; // 30 sec
  private readonly COGNITO_IDP_URL;

  constructor({ region, userPoolId }) {
    this.COGNITO_IDP_URL = `cognito-idp.${region}.amazonaws.com/${userPoolId}`;
  }

  private _clean = () => {
    if (this._refreshTimeout) {
      clearTimeout(this._refreshTimeout);
      this._refreshTimeout = null;
    }
  };

  private _scheduleCredentialsRefresh = (interval = this.REFRESH_INTERVAL) => {
    this._refreshTimeout = setTimeout(async () => {
      const session = await Auth.currentSession();

      // @ts-ignore
      AWS.config.credentials.params.Logins[
        this.COGNITO_IDP_URL
      ] = session.getIdToken().getJwtToken();
      // @ts-ignore
      AWS.config.credentials.refresh(async error => {
        if (this._refreshTimeout) {
          this._scheduleCredentialsRefresh(
            error ? this.MIN_REFRESH_INTERVAL : this.REFRESH_INTERVAL
          );
        }
      });
    }, interval);
  };

  private _createS3 = ({ bucket, region, ...restParams }) => {
    // @ts-ignore
    return new AWS.S3({
      apiVersion: "2006-03-01",
      signatureVersion: "v4",
      params: { Bucket: bucket },
      region,
      ...restParams,
    });
  };

  private _initCredentials = async () => {
    try {
      const credentials = await Auth.currentUserCredentials();
      AWS.config.credentials = credentials;

      return credentials;
    } catch (e) {
      return null;
    }
  };

  private _getParams = ({ credentials, level = "public", key, object }) => {
    if (!credentials && level !== "public") {
      throw new Error("Missing credentials");
    }

    let prefix;
    const identityId = credentials.identityId;

    switch (level) {
      case "public":
        prefix = "public";
        break;
      case "protected":
        prefix = `protected/${identityId}`;
        break;
      case "private":
        prefix = `private/${identityId}`;
        break;
    }

    return {
      // @ts-ignore
      Key: `${prefix}/${key}`,
      Body: object,
      ContentType: "binary/octet-stream",
    };
  };

  public put = (
    key,
    object,
    { progressCallback, level, bucket, region, ...restParams }
  ) =>
    new Promise(async (resolve, reject) => {
      try {
        const credentials = await this._initCredentials();

        const s3 = this._createS3({ bucket, region, ...restParams });
        const params = this._getParams({ credentials, level, key, object });

        if (credentials) {
          this._scheduleCredentialsRefresh();
        }

        s3.upload(params)
          .on("httpUploadProgress", progressCallback)
          .promise()
          .then(data => {
            this._clean();
            resolve(data);
          })
          .catch(error => {
            this._clean();
            reject(error);
          });
      } catch (error) {
        this._clean();
        reject(error);
      }
    });
}

export const MyStorage = new Storage({
  region: "your-region",
  userPoolId: "your-user-pool-id",
});

```

U can use `Storage` in the same way like u use Amplify `Storage`

```jsx
 MyStorage.put(`fileName`, file, {
        progressCallback: onProgress,
        level: "private",
        bucket: "bucket",
        region: "region",
      })
        .then(onSuccess)
        .catch(onFailure);
```


The token is refreshed every 50 min (*REFRESH_INTERVAL*). If the refresh fails for some reason we are still trying to refresh the token every 30 sec (*MIN_REFRESH_INTERVAL*).

**Comment by tigran10** [comment]
@nomadus trying your custom storage class now as a shortcut, If it works, I will buy you a coffee after the pandemic :)

**Comment by carlos357** [comment]
After some trial an error I have found that the answer from @jamesoflol is the most correct.
Here it is the code that worked for me, adapted to Angular HttpClient:



```typescript

/**
 * As AWS Amplify SDK does not notify when the current access token expires
 * we have to do the token refresh check on every HTTP call. This class
 * implements an HTTP request interceptor for the Angular HttpClient
 */
@Injectable()
export class AddAccessTokenToHttpHeader implements HttpInterceptor
{
    service_hub: ServiceHub;
    public aws_cognito_access_token: string = "";


    constructor(service_hub: ServiceHub)
    {
        this.service_hub = service_hub;
    }

    intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>>
    {
        // Amplify AuthClass.currentSession() checks the access token and refreshes it if required.
        return (from((this.service_hub.amplify_service.auth() as AuthClass).currentSession()).pipe(
            switchMap(cognito_session =>
            {
                let auth_header: string = 'Bearer ' + cognito_session.getAccessToken().getJwtToken()
                let new_request: HttpRequest<any> = request.clone({
                    setHeaders: {
                        Authorization: auth_header
                    }
                });

                return (next.handle(new_request));
            })
        ));
    }

}```

I hope it helps!

**Comment by nullptrerror** [comment]
> After some trial and error I have found that the answer from @jamesoflol is the most correct.
> Here it is the code that worked for me, adapted to the Angular HttpClient:
> 
> ```ts
> /**
>  * As the AWS Amplify SDK does not notify when the current access token expires
>  * we have to check the current token on every HTTP call. This class
>  * implements an HTTP request interceptor for the Angular HttpClient
>  */
> @Injectable()
> export class AddAccessTokenToHttpHeader implements HttpInterceptor
> {
>     constructor(protected amplify_service: AmplifyService)
>     {
>     }
> 
>     intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>>
>     {
>         // Amplify AuthClass.currentSession() checks the
>         // access token and refreshes it if required.         
>         return (from((this.amplify_service.auth() as AuthClass).currentSession()).pipe(
>             switchMap(cognito_session =>
>             {
>                 let auth_header: string = 'Bearer ' + cognito_session.getAccessToken().getJwtToken()
>                 let new_request: HttpRequest<any> = request.clone({
>                     setHeaders: {
>                         Authorization: auth_header
>                     }
>                 });
> 
>                 return (next.handle(new_request));
>             })
>         ));
>     }
> 
> }```
> ```

How would you re-route the request on an unauthorized request?
