### ISSUE TITLE
Recreate the Hosted UI grant code flow with own React UI

### ISSUE THREAD

**Issue by damonmiller** [aws-amplify/amplify-js#4462]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
Hi, I am trying to create an SSO solution using Cognito User Pools.  The Hosted UI does exactly what we need, functionality wise, however, it does not allow enough UI customization for our requirements.  Basically, we want to create a "Login with mydomain" for our own apps, which span multiple unrelated domains.

What I want to do is setup https://auth.mydomain.com/login?response_type=code&client_id=<my client id>&redirect_uri=https://app1.mydomain.com/ as a custom React app with our own UI but following the identical auth flow as the Hosted UI provides.  Once authenticated, I want to redirect back to redirect_uri passing the ?code= url param.

I have googled for days and read through all the docs at https://aws-amplify.github.io/docs/js/authentication and I do not see how to accomplish this - I may simply be missing it.  I see mention of using a "Login with Cognito" button which just sends you to the Hosted UI - this is NOT what I want.  I do not want our users to see the unstyled Hosted UI at all.

Is this possible with Amplify currently?  If so, could you provide examples and along with the relevant documentation links?  If this is not currently possible, what are the chances of getting this added?

Thank in advance!

**Comment by haverchuck** [comment]
@damonmiller Have you tried the instructions for bypassing the hosted UI [here](https://aws-amplify.github.io/docs/js/authentication#oauth-and-hosted-ui)? This should allow you to use the Hosted UI functionality and flow in Amplify without actually displaying the Hosted UI but instead passing through Hosted UI directly to the provider (ie. facebook, google, etc).

**Comment by damonmiller** [comment]
@haverchuck I have looked at those docs and when I see this line...
`<button onClick={() => Auth.federatedSignIn()}>Open Hosted UI</button>`
...I get the feeling this is giving the user the unstyled Hosted UI that I do not want them to see.  Am I misinterpreting this?

**Comment by leosoaivan** [comment]
@damonmiller I'm facing issues relating to the HostedUI/Social provider logins as well, but in this case, I believe the example is meant to illustrated that can use `Auth.federatedSign({ provider: provider })` for individual login buttons/links, and/or also use `Auth.federatedSign()` without any arguments to call the HostedUI.

**Comment by haverchuck** [comment]
@damonmiller  -  @leosoaivan is correct; calling Auth.federatedSignIn will take you to the OOTB Hosted UI when you have OAuth enabled.  If you want to roll your own OAuth login screen, you can do something like this:
```
 <button onClick={() => Auth.federatedSignIn({provider: 'Facebook'})}>Open Facebook</button>
```

**Comment by rspuler** [comment]
Nobody seems to understand the question problem:

We want to have the option to sign-in with OAuth/OIDC workflow with the following options on the login screen:

- Cognito User Pools (with a custom UI and **NOT** the hosted UI)
- Facebook
- Google
- Any other compatible IdP.

All the solutions is saw in this thread and others are always involving the **hosted UI**  if logging in through Cognito User Pool.  The hosted UI is a useless product if you need to have an international website as it doesn't support localization (apart from very limited styling options).

**Comment by damonmiller** [comment]
> Nobody seems to understand the question problem:
> 
> We want to have the option to sign-in with OAuth/OIDC workflow with the following options on the login screen:
> 
> * Cognito User Pools (with a custom UI and **NOT** the hosted UI)
> * Facebook
> * Google
> * Any other compatible IdP.
> 
> All the solutions is saw in this thread and others are always involving the **hosted UI** if logging in through Cognito User Pool. The hosted UI is a useless product if you need to have an international website as it doesn't support localization (apart from very limited styling options).

This is exactly correct! The customization options available for Hosted UI are very limited.  And there is no way to recreate the OAuth/OIDC flow of the Hosted UI in you own custom implementation.
