### ISSUE TITLE
[ERROR] 44:01.102 AWSPinpointProvider - record event failed.  CredentialsError: Missing credentials in config

### ISSUE THREAD

**Issue by rjjlucy** [aws-amplify/amplify-js#4464]
**Describe the bug**
My app runs very well in last few weeks. We did not change anything related to Amplify recently. But the console of our App starts to print this error.
```
[ERROR] 44:01.102 AWSPinpointProvider - record event failed.  CredentialsError: Missing credentials in config
```

Check out alpha/beta/gamma stage app, which has the same codebase as prod. No issue on non-prod stage

**To Reproduce**

1. Open our web app and web console
2. See the error when app is bootstrapped.

Link to sample code
Ping me on AmazonChime renjingy@. I can show you the code in Amazon GitFarm.

**Expected behavior**
No error log.

The interesting thing is the printed error message is not red error, it's regular info message.

**Comment by haverchuck** [comment]
@rjjlucy  - Which version of amplify are you currently on?

**Comment by rjjlucy** [comment]
We use Amplify in our web worker package, which is not an npm package. So we use the Amazon internal NodeJS-aws-amplify = 1.1.x;

**Comment by rjjlucy** [comment]
Another interesting observation is the event is actually sent out by pinpoint provider. I am also able to see the event in the Kibana, which is our metric event final destination.

**Comment by haverchuck** [comment]
@rjjlucy This error can sometimes occur when their are multiple versions of the AWS SDK in the dependency graph.

**Comment by yonatanganot** [comment]
@haverchuck 
We have the same issue.

Mentioned here also:
https://github.com/aws-amplify/amplify-js/issues/4295

Yarn's [Selective dependency resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) might help for temporary solution.
