### ISSUE TITLE
signin/signup pages using withAuthenticator for do not match AWS App Client Settings

### ISSUE THREAD

**Issue by azadbolour** [aws-amplify/amplify-js#4466]
** Which Category is your question related to? ** Auth
** What AWS Services are you utilizing? ** Cognito
"aws-amplify": "^1.2.4"
"aws-amplify-react": "^2.5.4"

I am using Amplify withAuthenticator for Cognito authentication in my React web UI. The signin/signup pages I get when I run my application are different from those shown in the AWS user pools UI (in App client setting via Launch Hosted UI). 

In the signup page, the discrepancy is an unexpected phone number field in my withAuthenticator app. No phone number is required in my settings, and none is asked for in the App client settings when I Launch Hosted UI.

In the signin page, the discrepancy is an unexpected option to login with AWS.  No such option has been configured, and none is shown in the App client settings - Launch Hosted UI.

One reason for these issues may be the configuration specified in my aws-exports.js.  A correct sample aws-exports.js file with the required parameters spelled out (other than the values of identifying information) would really help out.

I am also wondering if there is a sample React application with complete and officially-sanctioned source code illustrating how to use hosted authentication (with signin/signup pages as shown in the AWS cognito UI under App client settings - Launch Hosted UI).

I have checked out this forum (including https://github.com/aws-amplify/amplify-js/issues/1980) and also looked at the documentation and blogs on using withAuthenticator, but have so far been unsuccessful in resolving this issue.

Any hints as to how to go about troubleshooting the problem would be greatly appreciated.

Many thanks.

Azad

**Comment by haverchuck** [comment]
@azadbolour We do not yet have the functionality which automatically displays the fields specified for your user pool (it currently just shows defaults).  You can however [customize your signup and signin component](https://aws-amplify.github.io/docs/js/react#signup-configuration) in react to only show the required fields.

You can find documentation about integrating Amplify with the Cognito Hosted UI [here](https://aws-amplify.github.io/docs/js/authentication#oauth-and-federation-overview).

**Comment by azadbolour** [comment]
Thanks for clarifying that and pointing to the documentation for signupConfig. Two follow-ups:

Is there also a signinConfig that I can use to include only email and password on the signin page? Is there documentation on how to do that similarly to signup?

Am I correct in assuming that the key for the attribute given name is 'given name', and for attribute family name is 'family name'. Are the keys the labels of attributes listed in the Attributes section of the AWS Cognito user pool UI?

Many thanks.

Azad

**Comment by haverchuck** [comment]
@azadbolour For configuration of the signin component to use email/phone number in place of username, see [these docs](https://aws-amplify.github.io/docs/js/react#sign-upin-with-emailphone-number).

As far as attribute keys, I believe that Cognito under the covers uses the keys as cited in the [OIDC specification](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims). So... 'given name' = 'given_name'.

**Comment by azadbolour** [comment]
Thanks for the info. 

I fixed my keys, and used email as user name as per your recommendation as follows:

const signUpConfig = {
  header: 'eagerwords signup',
  hideAllDefaults: true,
  signUpFields: [
    emailField,
    givenNameField,
    familyNameField,
    passwordField
  ]
};

const authenticationParams = {
  includeGreetings: true,
  signUpConfig,
  usernameAttributes: 'email'
};

export default withAuthenticator(GameComponent, authenticationParams);

The signup fields now work as expected. 

In the signin page I get email and password as expected, but at the top I also get "Sign in with AWS". Is there a way to remove the AWS signin?

Checking the source code, aws-amplify-react/src/Auth/index.tsx, I see the
following in the constructor:

			this.authConfig = {};

			if (typeof includeGreetings === 'object' && includeGreetings !== null) {
				this.authConfig = Object.assign(this.authConfig, includeGreetings);
			} else {
				this.authConfig = {
					includeGreetings,
					authenticatorComponents,
					federated,
					theme,
					signUpConfig,
				};
			}

No mention of usernameAttributes.

But the render function uses it:

  usernameAttributes={this.authConfig.usernameAttributes}

Not sure how usernameAttributes provided as a parameter to withAuthenticator is
passed to where it needs to go to be used internally.

I am thinking before pursuing the withAuthenticator approach much further I should ask a higher level question:

I started the process by manually creating my user pool and client specifications through AWS's Cognito user interface, and then trying to use my setup from Amplify. Is that a supported use case for Amplify authentication? 

What would be the fastest way to get up and running with Cognito authentication (front-channel oidc flow to start with) given that I'd like to use an existing user pool and client created through the AWS user interface?  

Many thanks.

Azad

**Comment by haverchuck** [comment]
@azadbolour  Yes, you can use an existing user pool with Amplify - the [Manual Setup section ](https://aws-amplify.github.io/docs/js/authentication#manual-setup)of the documentation has details.

What exactly do you mean by 'front channel OIDC flow'?  In general I would suggest using [Cognito Hosted UI](https://aws-amplify.github.io/docs/js/authentication#oauth-and-federation-overview) if you want to do OIDC in Amplify.

**Comment by azadbolour** [comment]
I have an application with a Web UI and a backend server. By front-channel flow I mean I just need authentication of users in the Web UI. Later I may also need to do authorization of backed functions using the client secret from my server. But initially I just need to get up and  running with a hosted solution for authentication in the UI with as little development effort as possible. 

I will take your advice and pursue the Cognito Hosted solution. Hopefully that will address my needs. So I'll go ahead and close this ticket. 

Thanks again.

Azad
