### ISSUE TITLE
Accelerated transfer feature in Storage

### ISSUE THREAD

**Issue by Amaanuddin** [aws-amplify/amplify-js#4468]
**Is your feature request related to a problem? Please describe.**
I've enabled the accelerated transfer feature of my s3 bucket and I want to use its endpoint to read and write in that bucket

**Comment by ChristopheBougere** [comment]
I'd love to see this feature as well available Amplify.
My current use case is to let users upload raw video files (possibly in GB) from the frontend, so the faster the better.
I could possibly have a look and submit a PR, is there any current plan?

**Comment by tommedema** [comment]
What's the status on this?

**Comment by miniman13** [comment]
Would love to have this feature to upload video files mentioned above!

**Comment by zach-lum-fm** [comment]
Also would love this!

**Comment by bigzidane** [comment]
Yes, totally love to having this

**Comment by cespin** [comment]
Why don't you give the option to the client to pass the s3 client as an optional argument? like this the clients would be able to enable transfer acceleration themselves and any other configuration that's needed.

**Comment by cespin** [comment]
I just tested this using the ```build aws-amplify@4.2.5-unstable.1``` and it works.

**Comment by jamesaucode** [comment]
This feature should now be enabled through #8750

**Comment by mkrn** [comment]
Sorry for the late comment, this option doesn't work with the new `resumable` option in `Storage.put`. *(Due to how new S3 client is created) 
Will file a new issue.

**Comment by lnxct** [comment]
@mkrn may i know in which release this solution you have put related Accelerated transfer?
