### ISSUE TITLE
Connection between federated signed-up users and existing users in the User Pool.

### ISSUE THREAD

**Issue by saniaky** [aws-amplify/amplify-js#4469]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **

I apologize if someone already asked such question, but I couldn't find out any information on how to handle connection between 2 types of Cognito accounts - regular one created through amplify API and the ones created using federated identities.  

For example: user created new account using email/password after after some time he tried to sign-in using their Google account that has the same email. Common sense says that he should be able to log in into his existing account, but instead Cognito creates a new user.

Step-by-step process:
1. User signed up using email/password:
```
Auth.signUp({
        username: user.email,
        password: user.password,
        attributes: {...}
}).then(...)
```

2. Cognito creates account in User Pool with random username (for example: `115cda94-9d69-4c2a-9998-f11cfa50913d` and provided email.

3. After some time user tries to log-in using his Google account.
```
Auth.federatedSignIn({provider: 'Google'}).then(...)
```

4. User redirected to federated identity (google webpage) and then to hosted Cognito page.

5. Hosted Cognito UI creates new account in User Pool with user name like `Google_111354911418729561216` and the SAME email that we already have in this User Pool and redirects to my website.

6. On the website user is treated like just registered.

What is the official way of handling such situations? Usually websites manage single account using key (email) and then connect/disconnect "social" accounts in their profile. How it supposed to work in Cognito? How can I link social account to existing user and vice versa?

Thank you.

**Comment by ajhool** [comment]
I believe that the official way to handle this is to use an AWS lambda function for the pre-signup trigger ( https://forums.aws.amazon.com/thread.jspa?threadID=261470 ) that links the two accounts. There is no native way to prevent this duplication with cognito.

Others _ have _ asked this question before, but it has never been sufficiently answered by the cognito team, which is one of the least responsive teams of AWS ( #3495 ).

**Comment by haverchuck** [comment]
@saniaky  We have contacted the Cognito team about this issue.

**Comment by haverchuck** [comment]
@saniaky Cognito is considering this use case as a feature request, but I have no further information at this time.  However, you might want to take a look [at this documentation](https://docs.aws.amazon.com/cli/latest/reference/cognito-idp/admin-link-provider-for-user.html) as a workaround.

**Comment by haverchuck** [comment]
@saniaky The Cognito team is considering this as a feature request, but I have no further information at this time.  For the time being, you may want to take a look at [this documentation ]( https://docs.aws.amazon.com/cli/latest/reference/cognito-idp/admin-link-provider-for-user.html)as a workaround (although I cannot speak to whether there are any side effects or pitfalls to this approach).  I am closing this issue for now, but feel free to weigh in on this in the [Cognito forums](https://forums.aws.amazon.com/forum.jspa?forumID=173&start=0).
