### ISSUE TITLE
Google login bypassing Hosted UI

### ISSUE THREAD

**Issue by leosoaivan** [aws-amplify/amplify-js#4472]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito User Pool with Google as external federated identity provider
** Provide additional details e.g. code snippets **
Using aws-amplify@1.2.2.

I've looked through a few similar issues for hints, but it appears I am stuck authenticating with Google via User Pool. This may be partly due to manual configurations we've made (e.g., provisioning a User Pool via Terraform) that ultimately limit our use of Amplify's CLI. Nonetheless, our User Pool configurations look correct, so I thought I'd ask here.

For context, login via username (i.e., email) works correctly. We've also configured LinkedIn logins via an AWS Lambda and a Cognito Identity Pool.

First, I've configured a Google project using the generic User Pool domain (amazoncognito.com) and created two sets of credentials: Web client (Auto-created for Google Sign-in) and OAuth client, the latter of which was used to configure Google login in the User Pool.

In our app, I'm using the following oauth configuration:
```javascript
    const oauth = {
      domain: 'project-dev.auth.us-east-1.amazoncognito.com',
      redirectSignIn: 'http://localhost:8080/project/oauth2/idpresponse',
      responseType: 'code',
      scope: ['email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
    };
```

When calling `Auth.federatedSign({ provider: 'Google' })`, I'm able to hit the Google login-flow *and* a user gets created in our User Pool. On redirecting back to localhost, however, there does not appear to be an authenticated user. `Auth.currentAuthenticatedUser()` and `Auth.currentSession()` both return errors, and the authState in LocalStorage remains as 'signIn'.

Any ideas on where else I should be looking would be appreciated.

**Comment by leosoaivan** [comment]
Adding some screenshots of Logger for info:
<img width="1680" alt="Screen Shot 2019-11-26 at 3 40 36 PM" src="https://user-images.githubusercontent.com/13614862/69670979-1e0a0000-1063-11ea-9e80-eaaabf3c6fb7.png">

<img width="1680" alt="Screen Shot 2019-11-26 at 3 39 12 PM" src="https://user-images.githubusercontent.com/13614862/69670945-0fbbe400-1063-11ea-9724-f8020b34bcc0.png">

**Comment by haverchuck** [comment]
@leosoaivan How are you passing that OAuth config to amplify.configure?

**Comment by leosoaivan** [comment]
@haverchuck Thanks for checking in.

It seems I was able to figure it out. I can't even pinpoint exactly what was the fix, since I tried a bunch of things. I'll leave a comment when I have some time over the weekend with a few more details. Just wanted to check back in for now.

**Comment by haverchuck** [comment]
@leosoaivan Thanks for keeping us posted!

**Comment by leosoaivan** [comment]
@haverchuck 

Looks like the issue may have been due to trying to configure Auth within the button's onClick listener, before calling `Auth.federatedSignIn()` right after. Asynchronous mishaps, I assume 😬.

**Comment by haverchuck** [comment]
@leosoaivan Thanks!
