### ISSUE TITLE
Storage.Remove('directoryName') Support

### ISSUE THREAD

**Issue by furlifeco** [aws-amplify/amplify-js#4475]
** Which Category is your question related to? **
Storage
** What AWS Services are you utilizing? **
S3
** Provide additional details e.g. code snippets **
Is there support for 

Storage.remove('directory')
          .then(result => console.log(result))
          .catch(err => console.log(err));

Or do I need to pull the list of files and call remove 1 by 1?

**Comment by haverchuck** [comment]
@furlifeco `Storage.remove()` will indeed delete a directory in s3, but only if the directory is empty (see [this thread](https://github.com/aws/aws-sdk-php/issues/1553)).  If you want to use the method to delete an empty directory, you will need to append a trailing slash to the key parameter:

```
  async removeTest() {
    const res = await Storage.remove('test/');
    console.log('res', res)
  }
```

**Comment by haverchuck** [comment]
@furlifeco
