### ISSUE TITLE
How to: Push notifications to web client

### ISSUE THREAD

**Issue by damianrr** [aws-amplify/amplify-js#4476]
** Which Category is your question related to? **
Analytics
** What AWS Services are you utilizing? **
Pinpoint
Hello, I'm adding analytics to my React.js application (I do NOT have a mobile app) and I want to leverage the possibility of sending push notifications. I know it's not currently supported by the amplify cli but documentation implies that there should be possible a workaround using the Amplify's ServiceWorker class (https://aws-amplify.github.io/docs/js/service-workers#handling-a-push-notification). I didn't understand very well the documentation, could someone share with me a code snippet showing me how to do this?

Thanks.

**Comment by ericclemmons** [comment]
This is a great question!  The docs cater to Native (https://aws-amplify.github.io/docs/js/push-notifications), and how to _receive_ a notification (per the link you mentioned), but I had to do some research myself to see how others are doing it.

I assume you're using `create-react-app` for your React.js app?

Have you seen https://medium.com/founding-ithaka/implementing-push-notifications-with-create-react-app-bf35cd25d870 & https://developers.google.com/web/ilt/pwa/introduction-to-push-notifications#push_api?

I'm hoping that one of those resources helps close the gap in the meantime while we investigate supporting push notifications for the web client, from both a documentation & API stand-point.

**Comment by damianrr** [comment]
Hey @ericclemmons thanks! I’ll look into this!

**Comment by ericclemmons** [comment]
Let me know if this works out!

If so, there's an opportunity for us to at least point to these resources within our docs 👀

**Comment by utkarsh4321** [comment]
When this feature will available with amplify ?
