### ISSUE TITLE
Execute custom code on campaign run.

### ISSUE THREAD

**Issue by damianrr** [aws-amplify/amplify-js#4477]
** Which Category is your question related to? **
Analytics
** What AWS Services are you utilizing? **
Pinpoint

Hi,

I'm trying to implement a feature in which I can update the state of my app (ex: showing a notification) on a pinpoint campaign run.
For example: I've graphql subscriptions so that when certain values changes in dynamodb I reproduce those changes on each client's browser; what I'm looking is something very similar to this; push notifications seems too complex to setup (also, don't support web client yet).

Any idea how I might be able to do this?

Thanks.

**Comment by haverchuck** [comment]
@damianrr Have you explored [PubSub](https://aws-amplify.github.io/docs/js/pubsub)? I'm not super familiar with pinpoint campaigns, but this might be worth a look.

**Comment by damianrr** [comment]
This is interesting @haverchuck, I'll look into it. Thanks!
