### ISSUE TITLE
Which Amplify Library Version should I install?

### ISSUE THREAD

**Issue by Jun711** [aws-amplify/amplify-js#4487]
When I run `npm install @aws-amplify/auth` and `npm install @aws-amplify/api`, it installs these. Is version 2.1.0 stable? 
```
 "@aws-amplify/api": "^1.2.4",
 "@aws-amplify/auth": "^1.5.0",
```

On github
![Screen Shot 2019-11-29 at 12 07 22 PM](https://user-images.githubusercontent.com/6880939/69888460-cfe24000-12a0-11ea-9916-2d408d7e081e.png)

On https://www.npmjs.com/package/aws-amplify
<img width="1161" alt="Screen Shot 2019-11-29 at 12 06 59 PM" src="https://user-images.githubusercontent.com/6880939/69888449-c22cba80-12a0-11ea-8391-b4f47a86bc67.png">

```
** Which Category is your question related to? **
E.g. Auth, Predictions, Storage, etc.
** What AWS Services are you utilizing? **
E.g. Cognito, AWS AppSync, etc.
** Provide additional details e.g. code snippets **
E.g. Sample code, versions of Amplify you are using
```

**Comment by Jun711** [comment]
I figured it out that 2.1.0 is the next version to be released but is probably still unstable.

**Comment by bneigher** [comment]
Why are there 2.x.x versions without any changelog or... any update as to what developers are supposed to use?
