### ISSUE TITLE
signUp error message misleading when domain is not set up in the App Integration tab

### ISSUE THREAD

**Issue by fabiosalvi** [aws-amplify/amplify-js#4489]
**Describe the bug**
When user try to sign up and email verification type is set as "Link" then it's
also necessary to setup a domain in the  App Integration tab, like
explained here:
https://forums.aws.amazon.com/thread.jspa?threadID=262811

But if the domain is not set then the error message in Authenticator is:
"Username could not be created. Please make sure that the username you have entered is between 1 and 128 characters."

which is misleading.

The api response is:
`{"__type":"InvalidParameterException","message":"Cannot perform specific action because there does not exist a valid use pool domain associated with the user pool"}`

Which is not much help anyway.

**Comment by ericclemmons** [comment]
@fabiosalvi It sounds like there are two improvements to be made here:

1. Documentation, making it clear that "Link" verifications require a domain to be added.
1. Improve the errors from the Authenticator so that it is clearer that the problem is with service configuration, rather than with the username itself.

Could you point me to what documentation URLs you have been referencing for both Auth and setting up the Authenticator?

**Comment by fabiosalvi** [comment]
I have not specific URLs because for this part I have been going through StackOverflow and tutorials on Medium.

I think this is first and foremost a matter with Auth and of a substantial relevance, so I would put explanations as soon as the `amplify add auth` command is introduced. Namely around here:
https://aws-amplify.github.io/docs/js/authentication#simple-auth

with a paragraph about "User confirmation".

As for improving the Authenticator I think it's just a matter of expanding on this:
https://github.com/aws-amplify/amplify-js/issues/4177
https://github.com/aws-amplify/amplify-js/commit/94b7181d0c37fa9dbfaec8d09b93c0c9f1246ec3#diff-1cf5b10c87e919f81d5f1ea503f15074

Truth be said, after posting the issue here I discovered that there is another bug on Cognito because it was sending confirmation emails without the link contained therein.
However I've not thoroughly inspected this so I havent' reported yet.
Just a warning for now.

**Comment by ericclemmons** [comment]
Do you have some of those StackOverflow or Medium tutorial URLs?  I have a local authentication app, and I want to replicate your experience as much as possible.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
