### ISSUE TITLE
InvalidParameterException during sign in

### ISSUE THREAD

**Issue by MadsBogeskov** [aws-amplify/amplify-js#4491]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
I have created a new Cognito user pool that have set e-mail as the username. In this pool I created an app client, without a client secret, and then configured the pool in my React client as such:
```js
Amplify.configure({
			Auth: {
				region: 'REGION,
				userPoolId: 'POOL_ID',
				userPoolWebClientId: 'APP_CLIENT_ID'
			}
});
```

However when I try to sign in with an account with the `Auth.signIn` method I just get a `{code: "InvalidParameterException", name: "InvalidParameterException", message: "Invalid input given"}` message. I can't figure out whether it is telling me that my configuration is wrong on the client, or server side, or perhaps if the user account info is wrong. However the user has just been created in Cognito, so I would have expected to get a reset required exception back.

Is there something I am not seeing?

**Comment by MadsBogeskov** [comment]
For any one that stumbles in here, it seems that the problem resolved itself. My theory is that the user pool needed some time to be fully initialized. I have waited around 5 hours.

**Comment by MadsBogeskov** [comment]
The error message could be better though :)

**Comment by anjananeema1102** [comment]
Anyone have any idea how to resolve this issue? I am also facing same problem while Sign up. I am following this tutorial : https://itnext.io/aws-amplify-react-native-authentication-full-setup-7764b452a138
