### ISSUE TITLE
Duplicate amazon-cognito-identity-js packages . One in Amplify and one in separate repo.

### ISSUE THREAD

**Issue by ajhool** [aws-amplify/amplify-js#4497]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
There appear to be two codebases for the `amazon-cognito-identity-js` packages.

One is in the Amplify repo: https://github.com/aws-amplify/amplify-js/tree/master/packages/amazon-cognito-identity-js

One is in a separate repo: https://github.com/aws/amazon-cognito-auth-js

These appear to be the same package but with different names. The package in the indepedent repository also appears to be dead: https://github.com/aws/amazon-cognito-auth-js/issues/214

**Comment by Amplifiyer** [comment]
@ajhool, the package in aws-amplify is the one that is used in Amplify and we recommend users to use. Are you having any trouble due to the standalone repo https://github.com/aws/amazon-cognito-auth-js

**Comment by ajhool** [comment]
@Amplifiyer Thank you. Yes, I think it's confusing and the standalone repo should be marked as deprecated and point to this repo. Additionally, there are numerous issues there that have gone unanswered because there is no indication that the repo has been deprecated.

**Comment by ashika01** [comment]
Closing this issue since we have archived the repo and there is note on the repo now indicating we have archived the repo.
