### ISSUE TITLE
Pinpoint Revenue Charts

### ISSUE THREAD

**Issue by Jun711** [aws-amplify/amplify-js#450]
Do you want to request a feature or report a bug?
feature request. not sure if aws-amplify supports populating Revenue charts data. 

What is the current behavior?
On the documentation that I found, aws-amplify AnalyticsClass doesn't seem to support populating of Revenue charts.
https://aws.github.io/aws-amplify/api/classes/analyticsclass.html
https://aws.github.io/aws-amplify/media/analytics_guide.html

If it does, could you please point me to the right direction? thanks!

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
aws-amplify 0.2.9

**Comment by abadillaml** [comment]
I found this that there is standard event `_monetization.purchase` on [Standard App Event Types](https://github.com/awsdocs/amazon-pinpoint-developer-guide/blob/master/doc-source/analytics-streaming.md#standard-app-event-types) maybe this is still valid for aws-amplify as `Analytics.record('_monetization.purchase')`

what should be the JSON object passed for the event?

@mlabieniec can you confirm?

**Comment by ldgarcia** [comment]
@abadillaml Checkout this link: https://docs.aws.amazon.com/mobileanalytics/latest/ug/migrate-api.html#migrate-api-query-example-events

You need to do something like:

````javascript
      Analytics.record('_monetization.purchase', {
        _currency: 'USD',
        _product_id: 'XYZ',
      }, {
        _item_price: 5.00,
        _quantity: 1.0,
      })
````

**Comment by abadillaml** [comment]
@ldgarcia thank you :)

**Comment by jordanranz** [comment]
I am going to close this issue due to inactivity. Please reopen if there are any related question or concerns.
