### ISSUE TITLE
Reusing the VerifyContact component

### ISSUE THREAD

**Issue by camilobern** [aws-amplify/amplify-js#4503]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
* "aws-amplify": "^1.2.3"
* "aws-amplify-react": "^2.5.3"

Is there anyway to reuse the VerifyContact component while the user is logged in?
My use-case is a user updating their required info (email, phone number) while they are logged in. In this case I'd like to pop-up the Authenticator using the "verifyContact" as the initial state in order to have the user go through the contact verification steps.

I have not been able to do this. I believe it's because you can't just create a new instance of the authenticator with its own initial state. It seems to me that the authState is shared among all instances of the authenticator.

However, I'm wondering if there is a workaround to this. I would really like to be able to reuse the VerifyContact component so I don't have to implement my own from scratch.

**Comment by ericclemmons** [comment]
Great question @camilobern.  So far, this looks like a bug.

In my example app, I added the following:

```diff
diff --git a/samples/react/multi-category/photo-albums-e2e/src/App.js b/samples/react/multi-category/photo-albums-e2e/src/App.js
index fc54351..b042747 100644
--- a/samples/react/multi-category/photo-albums-e2e/src/App.js
+++ b/samples/react/multi-category/photo-albums-e2e/src/App.js
@@ -3,6 +3,8 @@ import { BrowserRouter, NavLink, Route } from 'react-router-dom';
 import { Grid } from 'semantic-ui-react';
 import 'semantic-ui-css/semantic.min.css';

+import { Authenticator } from 'aws-amplify-react';
+
 import AlbumList from './components/AlbumList';
 import AlbumDetails from './components/AlbumDetails';
 import Login from './components/Login';
@@ -22,6 +24,8 @@ export default function App(props) {
     <BrowserRouter>
       <Navigation />

+      <Authenticator authState="verifyContact" />
+
       <Route component={Login} path="/login" />

       <Grid padded>
```

But, the Authenticator only shows the `signOut` experience:

> <img width="831" alt="Screen Shot 2019-12-03 at 9 59 57 AM" src="https://user-images.githubusercontent.com/15182/70076524-d0861980-15b3-11ea-8202-34ff7cf69430.png">

I can manually display `VerifyContact` via:

```diff
diff --git a/samples/react/multi-category/photo-albums-e2e/src/App.js b/samples/react/multi-category/photo-albums-e2e/src/App.js
index fc54351..7d72b47 100644
--- a/samples/react/multi-category/photo-albums-e2e/src/App.js
+++ b/samples/react/multi-category/photo-albums-e2e/src/App.js
@@ -3,6 +3,8 @@ import { BrowserRouter, NavLink, Route } from 'react-router-dom';
 import { Grid } from 'semantic-ui-react';
 import 'semantic-ui-css/semantic.min.css';

+import { VerifyContact } from 'aws-amplify-react';
+
 import AlbumList from './components/AlbumList';
 import AlbumDetails from './components/AlbumDetails';
 import Login from './components/Login';
@@ -22,6 +24,8 @@ export default function App(props) {
     <BrowserRouter>
       <Navigation />

+      <VerifyContact authState="verifyContact" />
+
       <Route component={Login} path="/login" />

       <Grid padded>
```

But this doesn't function when clicked:

> <img width="830" alt="Screen Shot 2019-12-03 at 10 05 44 AM" src="https://user-images.githubusercontent.com/15182/70076876-8ea9a300-15b4-11ea-9902-339233153745.png">

@camilobern 👆 Is this what you're looking to accomplish?

**Comment by camilobern** [comment]
@ericclemmons It's close to what I was expecting. 
At the moment I'm only seeing the signout and greeting components.
I'd like to see this:
![image](https://user-images.githubusercontent.com/53054042/70094006-98043100-15ef-11ea-8d6c-8a3b8dd728c0.png)

**Comment by camilobern** [comment]
More specifically I would like to show the component above as a pop-up while the user is logged in after they change both their email and phone number.

**Comment by ericclemmons** [comment]
Ah, that's helpful!  Can you share what props or configuration you're passing into `<Authenticator>` or `withAuthenticator(...)` currently?

I'm able to replicate this a bit, but want to make sure I fix it for how you're actually using it :)

**Comment by camilobern** [comment]
Thanks for following up @ericclemmons.

At the moment I'm just trying to get it to work with a minimal set of props so it's basically just like the example you have:
```<VerifyContact authState="verifyContact"></VerifyContact>```

I do have the component showing up now without any styling:
![image](https://user-images.githubusercontent.com/53054042/70155586-874fcb80-1680-11ea-9410-6141b0cbf0aa.png)

However, the component is not functional. It should display the different methods to verify contact information and lead me through the verification process.

**Comment by camilobern** [comment]
Just a follow up:

I was originally trying to use the `Authenticator` as such:

```<Authenticator authState="verifyContact"></Authenticator>````
I just get the sign-out experience as you did.

**Comment by ericclemmons** [comment]
@camilobern Great, we're at least seeing the same behavior!  This bug should ideally be addressed with the `<Authenticator authState="verifyContact">` usage, as to avoid you having to wire up click-handlers for `<VerifyContact />` yourself.

I'll look into this some more, and at the very least group it with #3279 so we don't bring this bug forward.

**Comment by camilobern** [comment]
@ericclemmons sure thanks!

**Comment by ericclemmons** [comment]
@jordanranz What's your take on this?  From my research, the `authState` prop is only used when `Auth.currentAuthenticatedUser()` throws an error:

https://github.com/aws-amplify/amplify-js/blob/8d2ba6e85031a7880d2b573e1f68108d22a7de54/packages/aws-amplify-react/src/Auth/Authenticator.tsx#L116-L129

Which means that, if the `user` is logged in, the requested `authState` is overridden with `signedIn`:

https://github.com/aws-amplify/amplify-js/blob/8d2ba6e85031a7880d2b573e1f68108d22a7de54/packages/aws-amplify-react/src/Auth/Authenticator.tsx#L103-L114

I can't say in what situations `authState` works as intended.

**Comment by jordanranz** [comment]
@ericclemmons I believe `authState` passed in to the Authenticator represents the initial auth state if a user is not logged in. A common use case for this is if you would like to show `signUp` instead of `signIn` for the initial auth state. Do you think this should behave differently?

**Comment by ericclemmons** [comment]
@camilobern We've done some research and `authState` is being overridden once the `user` session is initialized.  Currently, `authState` only works when a user _isn't_ logged in, but you already know this :)

Can you try the following in your render function & share your screenshot?

```js
     <VerifyContact
        authData={user}
        authState="verifyContact"
        onAuthEvent={(...args) => console.log('onAuthEvent', ...args)}
        onStateChange={(...args) => console.log('onAuthEvent', ...args)}
      />
```

(Where `user` comes from `await Auth.currentAuthenticatedUser()`, or wherever you're currently tracking the logged in state)

My hope is that, in your circumstance, explicitly rendering the `VerifyContact` component will give you what you need today.

If not, we'll need to plan for the following changes:

1. Update `Authenticator`'s `authState` to behave like a "controlled component":
  > https://reactjs.org/docs/forms.html#controlled-components

1. Ensure #3279 supports independently-rendered auth states.

**Comment by camilobern** [comment]
Thanks @ericclemmons, I'll try this once I get a chance and report back.

**Comment by jordanranz** [comment]
Per the discussion above, I do not believe this is a bug but rather an undocumented use case. Let us know if @ericclemmons' solution worked for you @camilobern
