### ISSUE TITLE
JKBigInteger.h' file not found

### ISSUE THREAD

**Issue by Luckygirlllll** [aws-amplify/amplify-js#4509]
**Describe the bug**

**To Reproduce**

1.Try to build IOS project
2.See error: JKBigInteger.h' file not found

-- or --

Link to sample code

**Expected behavior**
I can build IOS project

**Screenshots**

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

</details>

**Smartphone (please complete the following information):**

- Device: Iphones
- OS: latest

**Additional context**

Library was working fine, suddenly today I have started getting this error.

**Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by ericclemmons** [comment]
@Luckygirlllll I'm having a hard time reproducing this issue.

Can you share the tutorial or documentation URLs you were following?

Also, can you run the following command in your terminal so we have more information on what packages you're using?

```shell
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

**Comment by ericclemmons** [comment]
@Luckygirlllll Let us know if you're still having this problem & provide some additional information so we can better triage & reproduce this. 🙏

Thanks!

**Comment by Luckygirlllll** [comment]
I deleted` Pods` and `workspace` and installed `pods` once again, that solved  the problem.

**Comment by ericclemmons** [comment]
😌 That's good news!  Thanks for following up!
