### ISSUE TITLE
How to pass an Amplify Cognito session from react native to webview?

### ISSUE THREAD

**Issue by kevzettler** [aws-amplify/amplify-js#4514]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
E.g. Cognito, 
** Provide additional details e.g. code snippets **
I have a react native app that renders a WebView of a Web app

The react native app uses Cognito and Amplify for authentication. The web app also uses the same Cognito and Amplify for authentication.

I have a login flow built with in the react native that has email/password login and social media federated Oauth logins. Both these login flows successfully work in the react native space and return a cognito session. I then take this cognito session and inject it into the webview and use it to execute a `mobileLogin` function

My current attempt looks like
```
import Amplify, { Auth } from 'aws-amplify';
import {
  CognitoUser,
  CognitoUserSession,
  CognitoIdToken,
  CognitoRefreshToken,
  CognitoAccessToken,
} from 'amazon-cognito-identity-js';

window.mobileLogin = async function(mobileSession) {
  amplify = Amplify.configure({
    ...config().amplify,
    userPoolWebClientId: '', //switch to mobile client
  });

const localSession = new CognitoUserSession({
  IdToken: new CognitoIdToken({ IdToken: mobileSession.idToken.jwtToken }),
  RefreshToken: new CognitoRefreshToken({ RefreshToken: mobileSession.refreshToken }),
  AccessToken: new CognitoAccessToken({ AccessToken: mobileSession.accessToken.jwtToken }),
});

const localUser = new CognitoUser({
  Username: mobileSession.accessToken.payload.username,
  Pool: Auth.userPool,
  Storage: Auth.userPool.storage,
});
localUser.setSignInUserSession(localSession);

// this seems like a hack
Auth.currentCredentials = async () => localSession;

try {
  await Auth.currentSession();
  console.warn(`mobile login current session!!`);
  store.dispatch(silentReloginAction())
} catch (ex) {
  console.warn(`mobile login ${ex}`);
}
 };
}
```
This seems to work initially however I am trying to refresh the session using `CognitoUser.refreshSession` and it throws an exception `invalid refreshToken`;

**Comment by dcsena** [comment]
+1

**Comment by iartemiev** [comment]
It seems that the problem is due to your using a different Client ID in the web view. Could you try utilizing the Client ID from your native app in the web view?
