### ISSUE TITLE
Connect multiple identities to same user

### ISSUE THREAD

**Issue by AlessandroAnnini** [aws-amplify/amplify-js#4522]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito, AWS AppSync

How can I connect multiple identities to the same user?
Example:

I signup with my email, then I "_connect_" my Google and Facebook accounts to my current user so if the next time I want to login with Google of Facebook I won't create another user but login to my old account.
The same should happen if I signup federated at first and then I want to add another federated account or an email.

Could be related to the unsolved #1931

**Comment by CarlosBalladares** [comment]
It would be helpful if anyone could provide an example

**Comment by ashika01** [comment]
We do not currently support this. We will mark this as feature request and will take this up with the cognito service team.

**Comment by Jun711** [comment]
@ashika01 
This issue has been around since maybe 2017 or earlier based on Cognito discussion forum, do you think it can be resolved in 2020?

**Comment by AlessandroAnnini** [comment]
Something good must happen in 2020

**Comment by tannerabread** [comment]
Closing as a duplicate of #5104. I realize this one is older but there is much more context in that issue so we will track any progress there.
