### ISSUE TITLE
using this.$Amplify in aws-amplify-vue with TS throws error

### ISSUE THREAD

**Issue by jonCliq** [aws-amplify/amplify-js#4526]
I'm working on implement AWS Amplify in a vue project, I am getting the error below when trying to use this.$Amplify

``Property '$Amplify' does not exist on type '{ name: string; created(): void; data(): { model: { email: null; }; validFields: { email: boolean; }; }; }'.``

My current implementation looks like this: 

```import Vue from 'vue';
import Amplify, * as AmplifyModules from 'aws-amplify';
import { AmplifyPlugin } from 'aws-amplify-vue';
import awsconfig from './aws-exports';
import App from './App.vue';
import router from './router';
import store from './store';

Vue.config.productionTip = false;

Amplify.configure(awsconfig);
Vue.use(AmplifyPlugin, AmplifyModules);

new Vue({
  router,
  store,
  render: (h) => h(App),
}).$mount('#app');```

**Comment by jonCliq** [comment]
I've attempted to create a amplify.d.ts file to allow me to not get errors using this.$Amplify.

```declare module 'aws-amplify-vue' {
  import { PluginFunction } from "vue";
  export const install: PluginFunction<{}>;

  module "vue/types/vue" {
    interface Vue {
      $Amplify: any
    }
  }
}```

Is this the piece I'm missing?

**Comment by jordanranz** [comment]
Hey @jonCliq, which component from `aws-amplify-vue` are you trying to use?
