### ISSUE TITLE
Connecting to AppSync Real-Time Directly

### ISSUE THREAD

**Issue by sirsavary** [aws-amplify/amplify-js#4528]
** Which Category is your question related to? **
PubSub, Auth

** What AWS Services are you utilizing? **
Cognito, AppSync

** Provide additional details e.g. code snippets **
I am attempting to use [mst-gql](https://github.com/mobxjs/mst-gql/tree/master/examples/3-twitter-clone/src/app/components) with AppSync's new real-time websockets but unfortunately I cannot find any solid documentation on how I should go about connecting to AppSync "without" Amplify.

I understand that this makes the question seem off topic but it's important that we're able to tie the Auth module into this setup. Right now I'm thinking of using pieces of [AWSAppSyncRealTimeProvider.ts](https://github.com/aws-amplify/amplify-js/blob/7bd8843ad3c71c34c4f40684cd3c986976870c21/packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts) but I was wondering if there was a simpler way, or even documentation on what "header" AppSync needs to allow a connection.

This issue is important to our project and any help is appreciated. If I'm unable to connect directly to AppSync (using [subscriptions-transport-ws](https://www.npmjs.com/package/subscriptions-transport-ws)) I imagine that I'll either need to find a way to plug PubSub into `mst-gql` or I'll need to use PubSub/Amplify directly to interface with AppSync.

**Comment by elorzafe** [comment]
Hi @sirsavary 

I dont understando what do you mean by tie the Auth module?
[Here](https://github.com/aws-amplify/amplify-js/blob/7bd8843ad3c71c34c4f40684cd3c986976870c21/packages/api/src/API.ts#L469) you can check how is invoked `PubSub`. I can help you to use `AWSAppSyncRealTimeProvider`
