### ISSUE TITLE
Location Not Capture for Cognito with Amplify in Pinpoint

### ISSUE THREAD

**Issue by prasadkesarkar** [aws-amplify/amplify-js#4530]
**Describe the bug**
Using Cognito Integration with Pinpoint and applications in React Native and React, the location data is not available to target users in a particular location where the last location was tracked. Location permissions are provided but no location data is available to filter a segment by the country of the location.

**Comment by sammartinez** [comment]
@prasadkesarkar Are you still looking for this use case? Please let us know.

**Comment by mauerbac** [comment]
Hi @prasadkesarkar , we haven't heard back so I will close this out. Let us know via a new issue if you have questions. Thanks
