### ISSUE TITLE
DataStore unable to work. 

### ISSUE THREAD

**Issue by ykbryan** [aws-amplify/amplify-js#4535]
**Describe the bug**
Unable to get DataStore save data.

**To Reproduce**

1. create a new reactjs app `create-react-app newapp`
2. add amplify and graphql api with the following schema
```
enum PostStatus {
  ACTIVE
  INACTIVE
}

type Post @model {
  id: ID!
  title: String!
  rating: Int!
  status: PostStatus!
}
```
3. run `amplify codegen models`
4. run `amplify push` and wait for it to finish
5. refer to the create datastore in the [documentation](https://aws-amplify.github.io/docs/js/datastore#save-data) and create a function `onCreatePost`
6. run `yarn start`
7. see the reactjs page, open chrome console. wait for the waiting 
```
[WARN] 44:02.180 DataStore - Sync error subscription failed Connection failed: {"errors":[{"message":"Validation error of type FieldUndefined: Field '_lastChangedAt' in type 'Post' is undefined @ 'onCreatePost/_lastChangedAt'"},{"message":"Validation error of type FieldUndefined: Field '_version' in type 'Post' is undefined @ 'onCreatePost/_version'"},{"message":"Validation error of type FieldUndefined: Field '_deleted' in type 'Post' is undefined @ 'onCreatePost/_deleted'"},{"message":"Validation error of type FieldUndefined: Field '_version' in type 'Post' is undefined @ 'onCreatePost/_version'"},{"message":"Validation error of type FieldUndefined: Field '_lastChangedAt' in type 'Post' is undefined @ 'onCreatePost/_lastChangedAt'"},{"message":"Validation error of type FieldUndefined: Field '_deleted' in type 'Post' is undefined @ 'onCreatePost/_deleted'"}]}
```
and the error:
```
Uncaught TypeError: Cannot read property 'observer' of undefined
    at AWSAppSyncRealTimeProvider._timeoutStartSubscriptionAck (AWSAppSyncRealTimeProvider.ts:506)
    at AWSAppSyncRealTimeProvider.ts:318
```

**Expected behavior**
DataStore and new Post should be created.

**Screenshots**
  
![Screenshot 2019-12-09 21 32 19](https://user-images.githubusercontent.com/1001146/70440474-3fd89d80-1acd-11ea-9641-320933ef394f.png)
![Screenshot 2019-12-09 21 35 24](https://user-images.githubusercontent.com/1001146/70440480-42d38e00-1acd-11ea-94ab-c4934cd9ea2f.png)

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
npx: installed 1 in 1.428s

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 167.82 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.16.0 - ~/.nvm/versions/node/v8.16.0/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.13.2 - ~/.nvm/versions/node/v8.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 68.3.0
    Safari: 13.0.3
  npmPackages:
    @aws-amplify/core: ^2.2.0 => 2.2.0 
    @aws-amplify/datastore: ^1.0.2 => 1.0.2 
    @testing-library/jest-dom: ^4.2.4 => 4.2.4 
    @testing-library/react: ^9.3.2 => 9.3.2 
    @testing-library/user-event: ^7.1.2 => 7.1.2 
    react: ^16.12.0 => 16.12.0 
    react-dom: ^16.12.0 => 16.12.0 
    react-scripts: 3.3.0 => 3.3.0 
  npmGlobalPackages:
    @aws-amplify/cli: 4.5.0
    aws-cdk: 1.18.0
    create-react-app: 3.3.0
    create-react-native-app: 2.0.2
    eslint-config-airbnb: 18.0.1
    expo-cli: 3.9.1
    expo: 35.0.1
    firebase-tools: 7.9.0
    gatsby-cli: 2.8.16
    jsforce: 1.9.3
    mocha: 6.2.2
    npm: 6.13.2
    react-devtools: 4.2.1
    react-native-git-upgrade: 0.2.7
    react-native-rename: 2.4.1
    react-native: 0.61.2
    serve: 11.2.0
    serverless: 1.59.1
```

</details>

**Smartphone (please complete the following information):**

- Device: MacBook Pro (15-inch, 2017)
- OS: macOS Mojave 10.14.6
- Browser Chrome
- Version 78.0.3904.108

**Additional context**
-
**Sample code**
-

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by undefobj** [comment]
Do you have an `aws-exports.js` file in your project?

**Comment by ykbryan** [comment]
> Do you have an `aws-exports.js` file in your project?

Yes. It includes `aws_project_region`, `aws_appsync_graphqlEndpoint`, `aws_appsync_region`, `aws_appsync_authenticationType` and `aws_appsync_apiKey`

**Comment by undefobj** [comment]
For your step #2 above:

> add amplify and graphql api with the following schema

How did you do this? Was it with `npx amplify-app`?

**Comment by ykbryan** [comment]
> For your step #2 above:
> 
> > add amplify and graphql api with the following schema
> 
> How did you do this? Was it with `npx amplify-app`?

i tried both `npx amplify-app` and `amplify add api` and do the `codegen models` later on.

**Comment by undefobj** [comment]
It sounds like you don't have a syncable API setup. Can you do the following:
- Create react app
- Inside that directory run `npx amplify-app` with the schema above
- `npm run amplify-modelgen` inside that directory
- `npm i @aws-amplify/core @aws-amplify/datastore`
- `npm run amplify-push`
- Run your app code

**Comment by ykbryan** [comment]
> It sounds like you don't have a syncable API setup. Can you do the following:
> 
> * Create react app
> * Inside that directory run `npx amplify-app` with the schema above
> * `npm run amplify-modelgen` inside that directory
> * `npm i @aws-amplify/core @aws-amplify/datastore`
> * `npm run amplify-push`
> * Run your app code

Ok, now i got no error from here but the new Post still does not appear in the dynamoDB.

![Screenshot 2019-12-10 01 39 54](https://user-images.githubusercontent.com/1001146/70458891-08c6b400-1aee-11ea-8c75-d9765dddecc9.png)

**Comment by ykbryan** [comment]
Ok, i got it to work after I move the trigger to `onClick={onCreatePost}` instead of calling the method in the App() directly.

<details><summary>Here's the source code for testing</summary>

<p>

```

import React, { useEffect } from 'react';
import logo from './logo.svg';
import './App.css';

import Amplify from '@aws-amplify/core';
import { DataStore, Predicates } from '@aws-amplify/datastore';
import { Post, PostStatus } from './models';

import awsconfig from './aws-exports';
Amplify.configure(awsconfig);

function App() {
  async function onCreatePost() {
    const result = await DataStore.save(
      new Post({
        title: `My First Post`,
        rating: 10,
        status: PostStatus.ACTIVE
      })
    );
    console.log(result);
  }

  useEffect(() => {
    const subscription = DataStore.observe(Post).subscribe(msg => {
      console.log(msg.model, msg.opType, msg.element);
    });

    return () => {
      subscription.unsubscribe();
    };
  });

  return (
    <div className='App'>
      <header className='App-header'>
        <img src={logo} className='App-logo' alt='logo' />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className='App-link'
          href='https://reactjs.org'
          target='_blank'
          rel='noopener noreferrer'
        >
          Learn React
          <input type='button' value='NEW' onClick={onCreatePost} />
        </a>
      </header>
    </div>
  );
}

export default App;

```

</p>
</details>

**Comment by undefobj** [comment]
@ykbryan great to hear! Is there anything in the docs that we could improve that would've made this easier for you?

**Comment by ykbryan** [comment]
> @ykbryan great to hear! Is there anything in the docs that we could improve that would've made this easier for you?

@undefobj Can you maybe add/share how will I know if i have setup my syncable API correctly and how to test it locally as well?

**Comment by undefobj** [comment]
Thanks @ykbryan I've added this as a backlog item in the CLI repo

**Comment by kevinold** [comment]
I ran into this issue when adding DataStore to an existing API.

Ultimately I needed to run `amplify update api` and follow the prompts to update the conflict resolution strategies (https://aws-amplify.github.io/docs/js/datastore#conflict-resolution) so that the API had this support and my mutations were updated to have these fields:

```
_version
 _deleted
_lastChangedAt
```

**Comment by rakannimer** [comment]
Hey @kevinold 

I'm getting the same error here, missing _version _deleted and _lastChangedAt. 

What did you set the conflict resolution to to fix it ?

**Comment by kevinold** [comment]
@rakannimer I selected optimistic concurrency per the conflict resolution docs on the DataStore page.  Do that and run `amplify push` and it will update your mutations to include those fields.

I will also add the note here that I've filed an issue with being able fully use the DataStore after upgrading the API.  That issue is being tracked here: https://github.com/aws-amplify/amplify-js/issues/4588

**Comment by rakannimer** [comment]
Thanks for the reply ! 

It did not work for my case, I'll try to setup a simple repro and maybe open another issue, or I'll stick to using vanilla GraphQL.

**Comment by pubkey** [comment]
@kevinold thanks, this worked in my case

**Comment by simalexan** [comment]
@undefobj I think the point missed for the case of @ykbryan was that, since this is a functional React component, it should mention that invoking DataStore should be either within a `useEffect` hook or as an event handler function, as the component needs to mount.

**Comment by simontegg** [comment]
Running `update` and adding conflict resolution did not work in may case. `_version` was added but not `_lastUpdatedAt` or `_deleted`

**Comment by phishy** [comment]
I'm pretty sure DataStore.save does not like to be invoked upon immediate page load. I can't quite pin it down, but as @ykbryan pointed out, it worked better when another function calls it.

For me, this does not work:
```
window.LOG_LEVEL = "DEBUG";

async function main() {
  let session = await DataStore.save(
    new Session({
      user: `Hello`
    })
  );
}

main();
```

**Comment by apoorvmote** [comment]
> I selected optimistic concurrency per the conflict resolution docs on the DataStore page. Do that and run `amplify push` and it will update your mutations to include those fields.
> 

@kevinold your advice/trick did work for my fresh/new project. I can't believe they didn't mention this issue in documentation with the trick. Thank god I found this page.

But it also created 2 different tables in Dynamodb(cloud) for same Todo type. Following are names for both tables
1) Todo-xxxxx
2) Amplify-Datastore-xxxxx

And every data from Todo table is replicated into the Amplify-Datastore table. 
I don't understand datastore much. To me it works on witchcraft magic.  
Is data replication an expected behaviour?

**Comment by chufgard** [comment]
> I ran into this issue when adding DataStore to an existing API.
> 
> Ultimately I needed to run `amplify update api` and follow the prompts to update the conflict resolution strategies (https://aws-amplify.github.io/docs/js/datastore#conflict-resolution) so that the API had this support and my mutations were updated to have these fields:
> 
> ```
> _version
> _deleted
> _lastChangedAt
> ```

You could also add this you the transform.conf.json directly:
`{
    "Version": 5,
    "ResolverConfig": {
        "project": {
            "ConflictHandler": "AUTOMERGE",
            "ConflictDetection": "VERSION"
        }
    }
}`

This information must be included to the documentation! It's pretty hard to guess... Or "@versioned" should generate it.

**Comment by cnwork** [comment]
> DataStore.save does not like to save the first record.
> 
> For me, this saves 1 record:
> 
> ```
> window.LOG_LEVEL = "DEBUG";
> 
> async function main() {
>   await DataStore.save(
>     new Session({
>       user: `Hello`
>     })
>   );
>   await DataStore.save(
>     new Session({
>       user: `Hola`
>     })
>   );
> }
> 
> main();
> ```

Same thing for me in a Quasar project. I have a form that triggers a Datastore.save() and the first entry gets saved locally but not in the DynamoDB. From second on onwards they all get saved properly. Why is the first one not being synced to the backend?

**Comment by undefobj** [comment]
> > DataStore.save does not like to save the first record.
> > 
> > For me, this saves 1 record:
> > 
> > ```
> > window.LOG_LEVEL = "DEBUG";
> > 
> > async function main() {
> >   await DataStore.save(
> >     new Session({
> >       user: `Hello`
> >     })
> >   );
> >   await DataStore.save(
> >     new Session({
> >       user: `Hola`
> >     })
> >   );
> > }
> > 
> > main();
> > ```
> 
> Same thing for me in a Quasar project. I have a form that triggers a Datastore.save() and the first entry gets saved locally but not in the DynamoDB. From second on onwards they all get saved properly. Why is the first one not being synced to the backend?

@cnwork could you open up a new issue with all the details of your project setup

**Comment by cnwork** [comment]
> @cnwork could you open up a new issue with all the details of your project setup

@undefobj sure, what kind of details are needed?

**Comment by ryanweaver718** [comment]
@ykbryan I also am having the same issue as you are and I put the function call in an onClick handler as well but still am getting the issue of the first record not being saved an all future ones being saved.

**Comment by blydewright** [comment]
Hi :) I'm experiencing the same issue of the first object not being synced upon a DataStore.save(). Subsequent DataStore.save()'s correctly sync. I am executing these saves within a click handler. This happens in both mock environment, and cloud using the auto-generated schema (Blog, Post, Comment). It's almost like the first save() method bootstraps something to allow further saves to work, but the first object is never synced.

**Comment by mdegrees** [comment]
Fixed the issue with: 
. Amplify update API
. Enable Datastore for the whole API

**Comment by ykbryan** [comment]
> @cnwork @undefobj @ykbryan I also am having the same issue as you are and I put the function call in an onClick handler as well but still am getting the issue of the first record not being saved an all future ones being saved.
> Was there nothing else you did to get it to work? Has there been any resolution to this?

Do you have a link to your repo/source code that does this?

**Comment by IsaacTrevino** [comment]
> > I ran into this issue when adding DataStore to an existing API.
> > Ultimately I needed to run `amplify update api` and follow the prompts to update the conflict resolution strategies (https://aws-amplify.github.io/docs/js/datastore#conflict-resolution) so that the API had this support and my mutations were updated to have these fields:
> > ```
> > _version
> > _deleted
> > _lastChangedAt
> > ```
> 
> You could also add this you the transform.conf.json directly:
> `{ "Version": 5, "ResolverConfig": { "project": { "ConflictHandler": "AUTOMERGE", "ConflictDetection": "VERSION" } } }`
> 
> This information must be included to the documentation! It's pretty hard to guess... Or "@versioned" should generate it.


So once I updated via amplify-cli `amplify update api` , then `enable DataStore for entire GraphQL` ,
I had to remove my items from the dynamo db table and reinsert them via DataStore instead of GraphQL, the Fields were now included and ready to roll. Thanks

**Comment by solisarg** [comment]
Just a warning: don't forget to update your models when adding the Datastore, otherwise you get errors saying that version doesn't exist (because your models need to be updated)

I skip the model update so get the error, need to run again amplify update API to take care of my models, below an example from the todolist example

![datastore](https://user-images.githubusercontent.com/3658786/88380896-acc34e00-cda5-11ea-9fad-32fe9803c349.png)

You select interactively which models to update (all of them), then your schema.graphql (if you use graphql) will have all the necessary to run flawlessly

And as IssacTrvino mention: think in advance if you will use DataStore, because if you add later, you need to clean the table and reinsert all of the items again

**Comment by ricsirigu** [comment]
Hi everyone, 
I'm experiencing the same issue, datastore doesn't sync with the cloud when inserting new items.

I added datastore to an existing api, enabling conflict detection.
I also generated the model with amplify-modelgen

The items gets inserted correctly in the browser storage, but there are no outbound connection to sync with the cloud.

The developer console shows a bunch of these errors 

`{"data":null,"errors":[{"path":null,"locations":[{"line":21,"column":5,"sourceName":null}],"message":"Validation error of type FieldUndefined: Field 'startedAt' in type 'ModelAlertConnection' is undefined @ 'syncAlerts/startedAt'"}]}`

When the following POST request is executed

`{"query":"query operation($limit: Int, $nextToken: String, $lastSync: AWSTimestamp, $filter: ModelAlertFilterInput) {\n  syncAlerts(limit: $limit, nextToken: $nextToken, lastSync: $lastSync, filter: $filter) {\n    items {\n      id\n      status\n      groupCanAccess\n      owner\n      seen\n      title\n      dateTime\n      description\n      kinds\n      impact\n      notes\n      isInternal\n      _version\n      _lastChangedAt\n      _deleted\n    }\n    nextToken\n    startedAt\n  }\n}\n","variables":{"limit":1000,"nextToken":null,"lastSync":0,"filter":null}}`

What am I missing?

Thank you in advance

**Comment by abhimanusharma** [comment]
> It sounds like you don't have a syncable API setup. Can you do the following:
> 
> * Create react app
> * Inside that directory run `npx amplify-app` with the schema above
> * `npm run amplify-modelgen` inside that directory
> * `npm i @aws-amplify/core @aws-amplify/datastore`
> * `npm run amplify-push`
> * Run your app code

I am using yarn. any suggestions.
