### ISSUE TITLE
Analytics events not being recorded

### ISSUE THREAD

**Issue by mhopey** [aws-amplify/amplify-js#4536]
Related to closed issue : #4448 

** Which Category is your question related to? **
Analytics
** What AWS Services are you utilizing? **
Cognito, AWS AppSync, Pinpoint
** Provide additional details e.g. code snippets **

I am also having a similar issue where my analytics events are not being recorded. I've updated my unauth role for identity pool to include the policy as outlined in the amplify docs. Is there any documentation that shows the aws-exports fields needed for this analytics config? I'm using a manually created aws-exports file with this set up:
{
"aws_project_region": "xxx",
"aws_cognito_identity_pool_id": "xxx",
"aws_cognito_region": "xxx",
"aws_user_pools_id": "xxx",
"aws_user_pools_web_client_id": "xxx",
"aws_appsync_region": "xxx",
"aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
"aws_appsync_graphqlEndpoint": "xxx",
'aws_app_analytics': 'enable',
"aws_mobile_analytics_app_id": "xxx",
'aws_mobile_analytics_app_region':"xxx"
}

It is a react native app, and uses the same imports/config as @haverchuck has described in #4448. I've also tried using Analytics.configure() with the appId, and region. Any help getting this up and running would be greatly appreciated! Thanks

**Comment by elorzafe** [comment]
Can you check the logs for the app by adding this
```javascript
import Amplify from '@aws-amplify/core';
//...
Amplify.Logger.LOG_LEVEL = 'DEBUG';
```
