### ISSUE TITLE
User does not exist in SignUp. [React Native]

### ISSUE THREAD

**Issue by YIPG** [aws-amplify/amplify-js#4537]
**Describe the bug**
You cannot signup using withAuthenticator HOC in Expo.

`User does not exist` error happened.

**To Reproduce**

1. Create new app by `expo init test`
2. Following [docs](https://aws-amplify.github.io/docs/js/react) and introduce Amplify `amplify init && amplify add auth && amplify push && yarn add ...`
3. Using withAuthenticator in app.js

**Expected behavior**
Successfully signed up same as react in a browser.

**Screenshots**
<img width="506" alt="スクリーンショット 2019-12-10 4 45 24" src="https://user-images.githubusercontent.com/19145527/70467474-a16a2d80-1b08-11ea-9bd7-c39bbac28f36.png">

<details>
  <summary><strong>Environment</strong></summary>

```

  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 110.69 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Safari: 12.1.1
  npmPackages:
    @aws-amplify/api: ^2.1.1 => 2.1.1 
    @aws-amplify/pubsub: ^2.1.1 => 2.1.1 
    @react-native-community/async-storage: ^1.6.3 => 1.6.3 
    @react-native-community/masked-view: ^0.1.5 => 0.1.5 
    @react-navigation/bottom-tabs: ^5.0.0-alpha.22 => 5.0.0-alpha.22 
    @react-navigation/core: ^5.0.0-alpha.25 => 5.0.0-alpha.25 
    @react-navigation/drawer: ^5.0.0-alpha.23 => 5.0.0-alpha.23 
    @react-navigation/native: ^5.0.0-alpha.16 => 5.0.0-alpha.16 
    @react-navigation/stack: ^5.0.0-alpha.39 => 5.0.0-alpha.39 
    @types/react: ^16.8.23 => 16.9.14 
    @types/react-native: 0.57.65 => 0.57.65 
    aws-amplify: ^2.2.0 => 2.2.0 
    aws-amplify-react-native: ^2.2.3 => 2.2.3 
    babel-preset-expo: ^7.1.0 => 7.1.0 
    expo: ^35.0.0 => 35.0.1 
    react: 16.8.3 => 16.8.3 
    react-dom: 16.8.3 => 16.8.3 
    react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
    react-native-gesture-handler: ~1.3.0 => 1.3.0 
    react-native-reanimated: ~1.2.0 => 1.2.0 
    react-native-safe-area-context: ~0.3.6 => 0.3.6 
    react-native-screens: ~1.0.0-alpha.23 => 1.0.0-alpha.23 
    react-native-web: ^0.11.7 => 0.11.7 
    typescript: ^3.6.3 => 3.7.3 
  npmGlobalPackages:
    @aws-amplify/cli: 4.5.0
    expo-cli: 3.9.1
    npm: 6.12.0


```

</details>

**Smartphone (please complete the following information):**

- Device: iphone 11 Pro Max
- OS: iOS13.2.2

**Comment by Amplifiyer** [comment]
@YIPG I just tried to reproduce this with the same amplify package version as yours and it's working fine for me. Can you enable debug logs in your application 

```
import Amplify from '@aws-amplify/core';
//...
Amplify.Logger.LOG_LEVEL = 'DEBUG';
```

and also provide the code sample of your app?

**Comment by RedionK** [comment]
I'm having the same issue. Is there a solution?

**Comment by darkrider88** [comment]
I am having the same issue again. First time when it occured I was not having the admin access in my IAM account so I changed the access and the error was resolved. Now I do have admin access but this error is poping.!!
