### ISSUE TITLE
Release Notes...

### ISSUE THREAD

**Issue by danhumphrey** [aws-amplify/amplify-js#4538]
**Is your feature request related to a problem? Please describe.**

I have no idea what has been included in (for example) @aws-amplify/auth between my current version (1.5.0) and the current release. Should I blindly update and *hope* there are no breaking changes?

**Describe the solution you'd like**

An obvious list of release notes under https://github.com/aws-amplify/amplify-js/releases

**Describe alternatives you've considered**

I don't want to have to trawl commit messages, but if I've missed something please let me know...

**Comment by ahallora** [comment]
I'm not sure if this is what you need, but the changelog are package-specific and can be found within each package here: https://github.com/aws-amplify/amplify-js/tree/master/packages 

E.g. the changelog for Auth is here: https://github.com/aws-amplify/amplify-js/blob/master/packages/auth/CHANGELOG.md

**Comment by danhumphrey** [comment]
That's helpful, thanks @ahallora

**Comment by Amplifiyer** [comment]
There is another issue opened to make the release notes better #3974 Please +1 over there. Closing this as duplicate
