### ISSUE TITLE
How to use Auth react HOC props

### ISSUE THREAD

**Issue by groundswel** [aws-amplify/amplify-js#4541]
Referring to amplify documentation : https://aws-amplify.github.io/docs/js/authentication#oauth-and-hosted-ui says that it will pass props to the component like oAuthUser or oAuthError. Can someone please provide some simple examples on how they can be used in different components used throughout a react web application?  When I tried to call it in my header component like `<Header ouruser=oAuthUser>` I got a JSX error that props should be either expression or string.

**Comment by manueliglesias** [comment]
Hi @groundswel 

Can you try with: (notice the curly braces)

```jsx
<Header ouruser={oAuthUser}>
```

**Comment by groundswel** [comment]
it gives an error saying "'oAuthUser' is not defined  no-undef" 

I have pretty standard App.js defined wrapped with the Amplify Auth react HOC. My sign up and login works without any issues but when I try to pass oAuthUser as props to my Header component I get this error. 

`function App() {
  
  return (
    <div className="App">
      <Header userdetails = {oAuthUser}> </Header>
      </header>
    </div>
  );
}
export default withAuthenticator(App);`

**Comment by groundswel** [comment]
What worked for me is this 
```
function App(props) {
return (
    <div className="App">
      <Header userdetails = {props.authData}> </Header>
      </header>
    <p>
    .......
   </p>
    </div>
  );
}

```
and then in the Header component ..

```
class Header extends React.Component {


constructor(props){
   super(props);
   console.log(props.userdetails.username);
   this.state = {
   	username : props.userdetails.username
   }

   
}
```

However I wonder why oAuthUser is not passed in the props as promised in the documentation?

**Comment by jordanranz** [comment]
Hey @groundswel, the docs that mention using the props `oAuthUser` or `oAuthError` are available when using the `withOAuth` HOC for `aws-amplify-react-native`. It seems you are trying to use them in the `withAuthenticator` HOC for `aws-amplify-react`. This is most likely the reason for the discrepancy.

**Comment by c0deWookiee** [comment]
Hi there, I can confirm that withOAuth is not passing props to my react native application:

TypeError: props.facebookSignIn is not a function
App.js:
`
import { withOAuth } from "aws-amplify-react-native";
function App() {
  const [fontLoaded, setFontLoaded] = useState(false);

  if (!fontLoaded) {
    return (
      <AppLoading
        startAsync={fetchFonts}
        onFinish={() => setFontLoaded(true)}
      />
    );
  }

  return (
    <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        <HashNavigator />
      </PersistGate>
    </Provider>
  );
}

export default withOAuth(App);
`

inside of LoginScreen.js:

` 
<MyButton
            style={{ elevation: 3.4, backgroundColor: colors.lightBlue }}
            title="Login with Facebook"
            onPress={() => props.facebookSignIn()}
>
`

**Comment by mauerbac** [comment]
hi @c0deWookiee - following up on this. Do you still need assistance here?
