### ISSUE TITLE
Missing "." in /auth/src/Auth.ts

### ISSUE THREAD

**Issue by marcpaskell** [aws-amplify/amplify-js#4544]
**Describe the bug**
The currentUserPoolUser method does not throw because its checking the err string incorrectly!

```err.message === 'User is disabled'```

should be

```err.message === 'User is disabled.'``` (notice the fullstop/period)

This means that  `Auth.currentAuthenticatedUser` never throws is a user has been disabled from the console.

**Comment by marcpaskell** [comment]
Tried to open this issue from the code, but can't see a link anywhere... 

https://github.com/aws-amplify/amplify-js/blob/73bf46e161cf35114cdf6a791a6ea248c469064d/packages/auth/src/Auth.ts#L1132

**Comment by manueliglesias** [comment]
Hi @marcpaskell 

I've verified this issue and see the problem, thanks for reporting it! 😃

**Comment by marcpaskell** [comment]
thanks @manueliglesias - any ideas when the next release is going out?
