### ISSUE TITLE
Using Cognito Federated Identities (Google) with multiple front ends

### ISSUE THREAD

**Issue by wmcbain** [aws-amplify/amplify-js#4545]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

Auth

**Amplify CLI Version** 

4.2.0

**What AWS Services are you utilizing?**

- Cognito
- Cognito Federated Identities
- S3

**Provide additional details e.g. code snippets**

_The Issue_

- We're using Cognito Federated Identities to log users in with Google, however it's not clear in the docs how to make this work with differing React and React Native targets.

_Code_

We're trying to use [@react-native-community/google-signin](https://github.com/react-native-community/react-native-google-signin) to authenticate with Google, get the `userInfo` object and then use `Auth.federatedLogin` to authenticate our user:

```ts
import React from 'react';
import { View } from 'react-native';
import { GoogleSignin, statusCodes } from '@react-native-community/google-signin';
import { Auth } from 'aws-amplify';
import GoogleSignInButton from './GoogleSignInButton';

const signIn = async () => {
  try {
    await GoogleSignin.hasPlayServices();
    const userInfo = await GoogleSignin.signIn();
    const user = await GoogleSignin.getCurrentUser();

    Auth.federatedSignIn(
      'google',
      { token: userInfo.idToken, expires_at: null },
      { name: user.user.givenName, email: user.user.email }
    )
      .then(credentials => {
        console.warn(credentials);
        console.log('got aws credentials!!!!');
      })
      .catch(e => {
        console.log(e);
      });
  } catch (error) {
    console.log(error);
    if (error.code === statusCodes.SIGN_IN_CANCELLED) {
      // user cancelled the login flow
    } else if (error.code === statusCodes.IN_PROGRESS) {
      // operation (e.g. sign in) is in progress already
    } else if (error.code === statusCodes.PLAY_SERVICES_NOT_AVAILABLE) {
      // play services not available or outdated
    } else {
      // some other error happened
    }
  }
};

GoogleSignin.configure({
  iosClientId: 'the-client-id.apps.googleusercontent.com'
});

const SignUpScreen = () => {
  return (
    <View>
      <GoogleSignInButton
        onAuth={async () => {
          await signIn();
        }}
      ></GoogleSignInButton>
    </View>
  );
};

export default SignUpScreen;

```

We've generated a new Google Auth token using the "Other" option as a web token is unsupported in a WebView as shown by this error. This is attempting to use the existing React project OAuth credential:

<img width="416" alt="Screen Shot 2019-12-02 at 8 44 18 PM" src="https://user-images.githubusercontent.com/7080654/70073334-abe76d00-15c6-11ea-8a46-6b30e373f276.png">

However using an "Other" credential emits the following error:

```
Error: RNGoogleSignInError: A problem reading or writing to the application keychain., Error Domain=org.openid.appauth.oauth_token Code=-2 "invalid_request: client_secret is missing." UserInfo={OIDOAuthErrorResponseErrorKey={
    error = "invalid_request";
    "error_description" = "client_secret is missing.";
}, NSLocalizedDescription=invalid_request: client_secret is missing., NSUnderlyingError=0x600003f451d0 {Error Domain=org.openid.appauth.remote-http Code=400 "{
  "error": "invalid_request",
  "error_description": "client_secret is missing."
}" UserInfo={NSLocalizedDescription={
  "error": "invalid_request",
  "error_description": "client_secret is missing."
}}}}
    at Object.fn [as signIn] (NativeModules.js:99)
    at GoogleSignin.signIn$ (GoogleSignin.js:20)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:271)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at tryCatch (runtime.js:45)
    at invoke (runtime.js:135)
    at runtime.js:145
    at tryCallOne (core.js:37)
    at core.js:123
```

I understand that this error relates to the `google-signin` framework but I'm not seeing any documentation that sets a best practice in this scenario. It seems like having differing Google OAuth credentials per project is currently unsupported?

Has the Amplify team or anyone in the community run into this before and how did you solve it?

_Project Details_

- Our project is a monorepo using lerna and yarn workspaces
- We have two web React frontends sharing the same amplify configuration, i.e multiple frontends
- We're adding a new React Native target and would like to use the existing configuration

**Comment by wmcbain** [comment]
Is there any way to get additional support for this Issue. We're still unable to solve and this is blocking federated identities for our app launch.

**Comment by sarahgriffis** [comment]
Can someone please look into this?
