### ISSUE TITLE
Using customState (URL encoding) with Hosted UI and federatedSignIn - OAuth throws Error: Invalid state in OAuth flow

### ISSUE THREAD

**Issue by sniperman23** [aws-amplify/amplify-js#4550]
**Describe the bug**
```
Auth.federatedSignIn({
          customState: encodeURIComponent(URL)
        });
```
This causes amplify to redirect to a Cognito Hosted UI, after logging in, amplify throws Error: Invalid state in OAuth flow. 

After debugging in my chrome console, I found the root cause is because Amplify is performing double encoding on the "URL", and checking against a single encoded URL. See here for details:
https://github.com/aws-amplify/amplify-js/blame/023f4960d80c9774d85cbc7593175d7380fcbed2/packages/auth/src/OAuth/OAuth.ts#L239

**To Reproduce**
First have a Hosted UI set up with Cognito, and then use federatedSignIn with a customState parameter.

```
Auth.federatedSignIn({
          customState: encodeURIComponent(URL)
        });
```
OR

```
Auth.federatedSignIn({
          customState: URL
        });
```

It doesn't matter if you encode here or not, because amplify does incorrect encoding on their side.

**Expected behavior**
For an error to not be thrown, and Auth Hub to publish a customState message with the URL state.

**Screenshots**
Google chrome debugger of OAuth throwing error:
![image](https://user-images.githubusercontent.com/22869378/70575112-96d88400-1b5a-11ea-92c1-0531834254ab.png)
In the screenshot, you can see that the savedState is encoded twice, and returned state only once.

**Workaround Hack**
You are able to work around this, by not using any special encoding characters inside the customState parameter.

**Similar Github Issue**
If you look at this issue, it looks like these commits  in this PR, caused this issue:
Issue:
https://github.com/aws-amplify/amplify-js/issues/3783
PR:
https://github.com/aws-amplify/amplify-js/pull/3784

**Proposed solution**
Inside the _validate function:
Decoding both URL many times, until both are not encoded.
Example:
https://stackoverflow.com/questions/17564837/how-to-know-if-a-url-is-decoded-encoded

Ideally a URL should only be encoded "once" through its lifecycle as a string, and then you'd only have to decode once, but universal standards are not always easily followed across the web.

**Comment by Amplifiyer** [comment]
@sniperman23 I'm trying to understand where in Amplify is doing incorrect encoding. It seems you are passing already encoded URL in the custom state and Amplify is doing another encoding (hence twice encoded), but in the redirected URL, it's only encoded once.

What happens when you pass non encoded URL in the customState?

**Comment by Gabiras12** [comment]
@Amplifiyer 
first encode for customState: https://github.com/aws-amplify/amplify-js/blame/023f4960d80c9774d85cbc7593175d7380fcbed2/packages/auth/src/OAuth/OAuth.ts#L76
second encode for customStae: https://github.com/aws-amplify/amplify-js/blame/023f4960d80c9774d85cbc7593175d7380fcbed2/packages/auth/src/OAuth/OAuth.ts#L94
