### ISSUE TITLE
Is there a way to list all versions of the current file?

### ISSUE THREAD

**Issue by Zilvinaskli** [aws-amplify/amplify-js#4554]
** Which Category is your question related to? **
Storage

Hello, is there any way or maybe anyone has a custom function to list all file versions of a file in a bucket that has versioning enabled?

**Comment by elorzafe** [comment]
@Zilvinaskli you should use `aws-sdk` to do that operation, Amplify doesn't support that feature.

More info for list versions of a file [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjectVersions-property)
