### ISSUE TITLE
Hosted UI Social Auth does not present TOTP challenge

### ISSUE THREAD

**Issue by ztnark** [aws-amplify/amplify-js#4555]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
Vanilla Cognito auth in my hosted UI challenges the user to verify their TOTP, but Social Auth (Google) does not, and authorizes the user. Is this is Cognito configuration issue, or a client side implementation issue?

**Comment by elorzafe** [comment]
@ztnark I haven't seen that use case before. I can confirm with cognito team.

**Comment by harrysolovay** [comment]
This is a service-team issue: managing the relationship between user pool TOTP & federated auth requires more custom logic than is built into the hosted UI flow.
