### ISSUE TITLE
Call Amplify API.get in React Got 403

### ISSUE THREAD

**Issue by gaohongwei** [aws-amplify/amplify-js#4556]
** Which Category is your question related to? **
Amplify API Gateway
** What AWS Services are you utilizing? **
Use Cognito, IAM
** Provide additional details e.g. code snippets **
        "@aws-amplify/api": "^1.2.4",
        "@aws-amplify/auth": "^1.3.3",

We make API.get in React
It works fine without Authorization

After we enabled Authorization:AWS_IAM
1. We got 403
2. OPTIONS call in network succeeded
3. The testing on AWS Method Test Page works without any problem

Here is the details
        Amplify.configure({
            Auth: {
                mandatorySignIn: true,
                region: config.cognitoPasswordless.REGION,
                userPoolId: config.cognitoPasswordless.USER_POOL_ID,
                identityPoolId: config.cognitoPasswordless.IDENTITY_POOL_ID,
                userPoolWebClientId: config.cognitoPasswordless.APP_CLIENT_ID
            },
            API: {
                endpoints: [
                  name: 'myAPI',
                  endpoint: `https://xxx.us-west-1.amazonaws.com/prod`,
                  region: "us-west-1"

                ]
            }
        });

API call
  API.get('myAPI',"/api/v2/dashboard/stats/recent")

It returned 403.

Here is the log:
General:
  Request URL: https://xxx/prod/api/v2/dashboard/stats/recent
  Request Method: GET
  Status Code: 403 
  Remote Address: 54.177.243.40:443
  Referrer Policy: no-referrer-when-downgrade

Reponse Header:
  content-length: 139
  content-type: application/json
  date: Wed, 11 Dec 2019 18:19:05 GMT
  status: 403
  x-amz-apigw-id: EjTsDHfSyK4Fuhw=
  x-amzn-errortype: IncompleteSignatureException
  x-amzn-requestid: 639d08dc-ae4b-4c69-94db-4c4971524e77

Request Header:
  :authority:xxx.us-west-1.amazonaws.com
  :method: GET
  :path: /prod/api/v2/dashboard/stats/recent
  :scheme: https
  accept: application/json
  accept-encoding: gzip, deflate, br
  accept-language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7,zh-TW;q=0.6
  authorization: AWS4-HMAC-SHA256 Credential=xxxx/20191211/us-west-1/execute-api/aws4_request, SignedHeaders=accept;host;x-amz-date;x-amz-security-token, Signature=cd235fbe46b8712afbf9902d14f56428a81a8f8495c9ded8d14d900a6c73c68b
  cache-control: no-cache
  origin: http://localhost:3001
  pragma: no-cache
  referer: http://localhost:3001/
  sec-fetch-mode: cors
  sec-fetch-site: cross-site
  user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
  x-amz-date: 20191211T181905Z, 20191211T181905Z
  x-amz-security-token: xxx

**Comment by elorzafe** [comment]
@gaohongwei did you signIn before making the API call? It seems you have mandatory signIn

**Comment by gaohongwei** [comment]
@elorzafe Thanks for following up.  Yes for both
We signed in the our app as cognito user. And the call is in our app 
we have policy: AmazonAPIGatewayInvokeFullAccess

**Comment by elorzafe** [comment]
@gaohongwei 

Did you created the API and Cognito Identity pool on the same account?

**Comment by elorzafe** [comment]
@gaohongwei 

Can you share your API config more in detail? Are you using proxy+ or you have the path you mentioned configured?

**Comment by sammartinez** [comment]
Resolving as above fix is in unstable and looking to do a release shortly

**Comment by gaohongwei** [comment]
We have found out the problem. We use  axios and amply both.  And we have added some global setting to axios, and it polluted amply call. Once we clean up global setting on axios. it works well. Thanks.

**Comment by ericclemmons** [comment]
@gaohongwei May I ask what specific clean up resolved this for you? Thanks!

**Comment by gaohongwei** [comment]
We have used some signed  axios request. and set accessKey etc on axios global level. It polluted the Amply API call. So We have cleaned up all global setting on axios.
