### ISSUE TITLE
No current user when I try federated Signup and graphql operation

### ISSUE THREAD

**Issue by AlessandroAnnini** [aws-amplify/amplify-js#4557]
**Describe the bug**
When I try a federated signup I try to check if the user is already registered on the db with a `graphqlOperation` query I get a `No current user` error.

**To Reproduce**

1. amplify add auth with federated, add name as field, add facebook and google as federated authentication
2. use signup/login with
`import { Authenticator } from 'aws-amplify-react';`
using federated attribute
3. try to login with facebook or google
4. use `Hub.listen('auth', onHubCapsule);` and try to query the db with a user with the id given by federated signup object or try to call `const user = await Auth.currentAuthenticatedUser();`

**Expected behavior**
I expect to be able to use graphqlOperation and check if the user already exists on my db and if not to mutate it in

**Additional context**
I am quite to have correctly set up Identity pool with the right `Authentication Providers` data

**Sample code**
```js
const registerNewUser = async signInData => {
      const isFederated = !signInData.signInUserSession;
      const id = isFederated
        ? signInData.id
        : signInData.signInUserSession.idToken.payload.sub;

      const getUserInput = { id };
      const { data } = await API.graphql(
        graphqlOperation(getUser, getUserInput)
      );
      // if we can't get a user (meaning the user hasn't been registered before), then we execute registerUser
      if (!data.getUser) {
        const input = {
          id,
          name: isFederated ? signInData.name : signInData.attributes.name,
          email: isFederated ? signInData.email : signInData.attributes.email
        };
// ERROR ON THE NEXT LINE
        const { data } = await API.graphql(
          graphqlOperation(createUser, { input })
        );
        updateUser(data.createUser);
      } else {
        updateUser(data.getUser);
      }
    };

Hub.listen('auth', async ({ payload: { event, data } }) => {
      switch (event) {
        case 'signIn':
          await registerNewUser(data);
          break;
        case 'signOut':
          updateUser(null);
          break;
        default:
          break;
      }
    });
```

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

`[DEBUG] 17:44.296 AuthClass - Failed to get user from user pool`
`[DEBUG] 17:44.297 AuthClass - Failed to get the current user No current user`
the other messages seems to be right

**Comment by elorzafe** [comment]
@AlessandroAnnini what are the props you are using with the `Authenticator` component.

**Comment by AlessandroAnnini** [comment]
Hi @elorzafe,
I am using the `Authenticator` like this:

```js
import { Authenticator } from 'aws-amplify-react';

<Authenticator
  signUpConfig={{
    hideAllDefaults: true,
    signUpFields: [
      {
        label: 'Name',
        key: 'name',
        required: true,
        displayOrder: 1,
        type: 'string'
      },
      {
        label: 'Email',
        key: 'email',
        required: true,
        displayOrder: 2,
        type: 'string'
      },
      {
        label: 'Password',
        key: 'password',
        required: true,
        displayOrder: 3,
        type: 'password'
      }
    ]
  }}
  federated={{
    google_client_id: '<myClientId>',
    facebook_app_id: '<myAppId>'
  }}
  theme={{
    formContainer: { margin: 0 },
    formSection: { margin: 0 }
  }}
  usernameAttributes="email"
/>
```

**Comment by elorzafe** [comment]
Hi @AlessandroAnnini 

I think your AppSync API has Cognito User Pools as authorization mode (correct if I am wrong please). In this case Amplify library try to get session credentials (Cognito User Pool token) in order to have access to the AppSync endpoint. 

To get a Cognito User Pool token you some options
- Login with username and password (Cognito User Pool user)
- Federate a user with third party provider like google or facebook

In order to federate a user with Cognito User Pool you have to enable OAuth flow. (more info [here](https://aws-amplify.github.io/docs/js/authentication#social-provider-federation)) and on your App  you have to use  `withOAuth` HOC.

You can use `Authenticator` when to use AWS IAM as authorization mode. That flow is slightly different because your third party provider (Google, Facebook, etc) is federating with identity pools.

Hope that helps

**Comment by AlessandroAnnini** [comment]
Hi @elorzafe,
thank for your response, I can confirm you that I am using Cognito User Pool as authorization mode of my AppSync API.
Now it is more clear, I will try to use OAuth flow.

Is there another way to accomplish this result (signup email+fb+googlel) or this is the only possible flow?

**Comment by elorzafe** [comment]
> Is there another way to accomplish this result (signup email+fb+googlel) or this is the only possible flow?

That is correct, you will need to enable Hosted UI on your Cognito userpool to achieve this. Are you using Amplify CLI to create resources?

**Comment by AlessandroAnnini** [comment]
Yes, I am using Amplify CLI whenever possible

**Comment by AlessandroAnnini** [comment]
Fixed following your advice and this: [Complete Guide to User Authentication with the Amplify Framework](https://dev.to/dabit3/the-complete-guide-to-user-authentication-with-the-amplify-framework-2inh) by Nader Dabit

Thanks!
