### ISSUE TITLE
Federated Apple login - Invalid State/RelayState provided.

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-js#4562]
I have implemented apple login to my Ionic project, and followed the guides on setting up on Apple's side and in the cognito condole.

I call the login:

```
  public async loginWithApple(): Promise<any> {
    this.amplify.auth().federatedSignIn({ provider: 'SignInWithApple' });
  }
```

However once i get through apples OAuth process and just before redirection I get the cognito error page saying:

> An error was encountered with the requested page.

followed by:

>  Invalid State/RelayState provided.

Any ideas on why this is happening?

**Comment by markmckim** [comment]
@oliverandersencox I wonder if this is the same issue here? https://github.com/aws-amplify/amplify-js/issues/4580

Could you try the steps I outlined on the other ticket (deleting your sign in with apple permission and trying from a simulator)?

**Comment by iartemiev** [comment]
@oliverandersencox just want to make sure, have you enabled "Sign in with Apple" in the Enabled Identity Providers section for the client(s) you're using in your Amplify app? (in the AWS Console: Cognito -> User Pool -> App Integration -> App client settings -> Enabled Identity Providers). 

Also, have you configured Attribute mapping for the Apple IDP?

**Comment by avlonder** [comment]
Same issue here (on Android device)
