### ISSUE TITLE
React Native FBSDK Login

### ISSUE THREAD

**Issue by IonutRealDevs** [aws-amplify/amplify-js#4565]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
Hi.
I work on a react-native application and i implemented login and register using email and password, all good, but now i want to implement login with Facebook/Google and i have some questions about that. I used Hosted UI, but this method opens the browser and i don't want that, i want a modal to popup, so i found react-native-fbsdk. Now, my question is, how can i use react-native-fbsdk with cognito so i can login users this way? Also, is there a way that my current registered users can login with facebook/google which they are already registered with same email address?

This is my function until now.

```
LoginManager.logInWithPermissions(['public_profile', 'email']).then(function(result) {
      if(result.isCancelled) {
        console.log('Cancelled')
      } else {
        AccessToken.getCurrentAccessToken().then(async data => {
          let token = data.accessToken
          let expires_at = data.expirationTime
          let user = data;

          let graphParams = { 
            accessToken: token,
            parameters: {
              fields: {
                string: 'email,first_name,last_name'
              }
            } 
          }

          let infoRequest = new GraphRequest('/me', graphParams, (error, result) => {
            if(error) {
              console.log('error', error)
            } else {
              let params = {
                body: {
                  user: result
                }
              }

              console.log(result)

              Auth.federatedSignIn('facebook', {token, expires_at}, user).then(result => {
                //WHAT SHOULD I DO HERE
              }).catch(error => {
                console.log(error)
              })
            }
          })

          new GraphRequestManager().addRequest(infoRequest).start()
        })
      }
    }, function(error) {
      console.log('Login failed' + error)
    })
```

**Comment by elorzafe** [comment]
@IonutRealDevs are you trying to do [OAuth Federation](https://aws-amplify.github.io/docs/js/authentication#oauth-and-federation-overview) or [Identity Pool Federation](https://aws-amplify.github.io/docs/js/authentication#oauth-and-federation-overview)

**Comment by IonutRealDevs** [comment]
OAuth Federation, sorry for late response.

**Comment by Amplifiyer** [comment]
@IonutRealDevs the way to use FB SDK (or any other federation provider's SDK), is to use identity federation. Please however note that amplify recommends using OAuth flow for federated authentication. If you only use Facebook, you can also pass the federation Provider directly in the OAuth signin call which will skip the hosted UI and go directly to the provider's login page. such as `Auth.federatedSignIn({provider: 'Facebook'})`

Please see https://aws-amplify.github.io/docs/js/authentication#social-provider-federation and https://aws-amplify.github.io/docs/js/authentication#identity-pool-federation
