### ISSUE TITLE
Optimization: replace div with good tags for more accessibility

### ISSUE THREAD

**Issue by m8schmit** [aws-amplify/amplify-js#4566]
Hi, ok it's not really a bug, more an optimization, in `aws-amplify-vue`  to gain in accessibility, it will be great to change the labels in `div` by real label:
```
<div v-bind:class="amplifyUI.inputLabel">{{$Amplify.I18n.get('Password')}} *</div>
        <input  v-bind:class="amplifyUI.input" v-model="password" type="password" :placeholder="$Amplify.I18n.get('Enter your password')" v-on:keyup.enter="signIn" v-bind:data-test="auth.signIn.passwordInput" />
```
to something like: 
```
<label for="password" v-bind:class="amplifyUI.inputLabel">{{$Amplify.I18n.get('Password')}} *</label>
        <input  id="password" v-bind:class="amplifyUI.input" v-model="password" type="password" :placeholder="$Amplify.I18n.get('Enter your password')" v-on:keyup.enter="signIn" v-bind:data-test="auth.signIn.passwordInput" />
```
 in child components of `Authentication`. 

So the components would be more usable by the visually impaired.

Thanks !

**Comment by elorzafe** [comment]
@michelschmit thanks for your suggestion I will mark this as a feature-request

**Comment by tannerabread** [comment]
Closing this as resolved, this should be handled better by the UI library for Vue than it was in `aws-amplify-vue`. Any new problems with that library should be opened in [that repo](https://github.com/aws-amplify/amplify-ui)
