### ISSUE TITLE
withAuthenticator HOC occasionally hangs on "Loading..." bug - Encountered on latest version

### ISSUE THREAD

**Issue by paulbartocillo** [aws-amplify/amplify-js#4569]
Same exact scenario with this bug reports: 

1. https://github.com/aws-amplify/amplify-js/issues/3471
2. https://github.com/aws-amplify/amplify-js/issues/3206

I browse all issues filed related to this topic and there were no open issues. Was this already fixed or there's still some workaround needed to be done? 

Thanks in advance!

**Comment by paulbartocillo** [comment]
I was able to implement a workaround: I'll just leave it here for reference.

What I ended up doing is check the authState of amplify authenticator on localStorage `amplify-authenticator-authState` and to determine if I'll use `withAuthenticator` or not.

```
let App = withAuthenticator(AppComponent, false, [<LoginPage />], null, {})

const authState = localStorage.getItem('amplify-authenticator-authState')

if (authState && authState === 'signedIn') {
  App = AppComponent
}

export default App
```

**Comment by sammartinez** [comment]
Resolving this issue as your above work around.
