### ISSUE TITLE
aws-amplify-react: Custom SectionHeader component

### ISSUE THREAD

**Issue by darrenfurr** [aws-amplify/amplify-js#4570]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'm just looking to add an image to the SectionHeader. It would be nice to provide a custom react component as SectionHeader for the SignIn or even SignUp components without having to build a full SignIn or SignUp component.

**Describe alternatives you've considered**
Tried inheriting SignIn in a new component & then using the Amplify-UI-Components-React, but all of them are not exported into the dist of aws-amplify-react.

**Additional context**

**Comment by tannerabread** [comment]
Closing as this package has been deprecated. The UI team is creating a new Authenticator component listed on the roadmap [here](https://ui.docs.amplify.aws/react-native/getting-started/introduction#roadmap). For any other feature requests dealing with UI components, please open up a new request [here](https://github.com/aws-amplify/amplify-ui/issues/new?assignees=&labels=feature-request&template=2.feature_request.yaml).

Thank you!
