### ISSUE TITLE
PushNotifications requestIOSPermissions not working in @latest (2.1.1)

### ISSUE THREAD

**Issue by joebernard** [aws-amplify/amplify-js#4574]
**Describe the bug**
The push notifications configuration [`requestIOSPermissions`](https://aws-amplify.github.io/docs/js/push-notifications) seems to have stopped working. The app prompts for push notification permissions on app load even if this config is `false`.  If I switch to the `@unstable` release (2.1.2-unstable.6) it does seem to work, and it did work in versions prior to 2.1.1.

This is a React Native project v0.61.5

The feature was introduced in #1781 

**To Reproduce**
`yarn add @aws-amplify/pushnotification@latest`

**Expected behavior**
Should respect `requestIOSPermissions` configuration.

<details>
  <summary><strong>Environment</strong></summary>

```
System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 1.16 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v10.15.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 70.0.1
    Safari: 13.0.3
  npmPackages:
    @aws-amplify/analytics: ^2.2.0 => 2.2.0 
    @aws-amplify/auth: ^2.1.1 => 2.1.1 
    @aws-amplify/cache: ^2.1.1 => 2.1.1 
    @aws-amplify/core: ^2.2.0 => 2.2.0 
    @aws-amplify/pushnotification: ^2.1.2-unstable.6 => 2.1.2-unstable.6+86741203 
    @aws-amplify/storage: ^2.1.1 => 2.1.1 
    @babel/core: ^7.6.0 => 7.6.0 
    @babel/runtime: ^7.6.0 => 7.6.0 
    @react-native-community/async-storage: ^1.7.0 => 1.7.0 
    @react-native-community/eslint-config: ^0.0.5 => 0.0.5 
    @react-native-community/netinfo: ^4.6.1 => 4.7.0 
    @react-native-community/push-notification-ios: ^1.0.3 => 1.0.3 
    amazon-cognito-identity-js: ^3.2.0 => 3.2.0 
    apollo-cache-inmemory: ^1.6.3 => 1.6.3 
    apollo-client: ^2.6.4 => 2.6.4 
    aws-appsync: ^3.0.2 => 3.0.2 
    aws-appsync-react: ^3.0.2 => 3.0.2 
    babel-jest: ^24.9.0 => 24.9.0 
    bugsnag-react-native: ^2.23.3 => 2.23.3 
    eslint: ^6.4.0 => 6.4.0 
    eslint-plugin-prettier: ^3.1.0 => 3.1.1 
    graphql: ^14.5.8 => 14.5.8 
    graphql-tag: ^2.10.1 => 2.10.1 
    jest: ^24.9.0 => 24.9.0 
    lodash.clonedeep: ^4.5.0 => 4.5.0 
    lodash.debounce: ^4.0.8 => 4.0.8 
    lodash.flowright: ^3.5.0 => 3.5.0 
    lodash.uniqby: ^4.7.0 => 4.7.0 
    metro-react-native-babel-preset: ^0.56.0 => 0.56.0 
    moment: ^2.24.0 => 2.24.0 
    moment-timezone: ^0.5.27 => 0.5.27 
    native-base: ^2.13.8 => 2.13.8 
    prettier: 1.19.1 => 1.19.1 
    prop-types: ^15.7.2 => 15.7.2 
    react: 16.9.0 => 16.9.0 
    react-apollo: ^2.5.8 => 2.5.8 
    react-native: 0.61.5 => 0.61.5 
    react-native-animatable: ^1.3.3 => 1.3.3 
    react-native-camera: ^3.15.0 => 3.15.0 
    react-native-circular-progress: ^1.3.4 => 1.3.4 
    react-native-config: luggit/react-native-config#master => 0.11.7 
    react-native-country-picker-modal: ^1.9.8 => 1.9.8 
    react-native-fast-image: ^7.0.2 => 7.0.2 
    react-native-fs: ^2.16.2 => 2.16.2 
    react-native-gesture-handler: ^1.5.2 => 1.5.2 
    react-native-haptic-feedback: ^1.8.2 => 1.8.2 
    react-native-orientation-locker: file:/opt/projects/thirdparty/react-native-orientation-locker => 1.1.7 
    react-native-permissions: ^2.0.8 => 2.0.8 
    react-native-phone-input: ^0.2.4 => 0.2.4 
    react-native-radial-context-menu: ^0.0.2 => 0.0.2 
    react-native-reanimated: ^1.4.0 => 1.4.0 
    react-native-safe-area-context: ^0.6.1 => 0.6.1 
    react-native-safe-area-view: ^1.0.0 => 1.0.0 
    react-native-screens: ^2.0.0-alpha.19 => 2.0.0-alpha.19 
    react-native-share: 2.0.0 => 2.0.0 
    react-native-svg: ^9.13.6 => 9.13.6 
    react-native-tab-view: ^2.11.0 => 2.11.0 
    react-native-vector-icons: ^6.6.0 => 6.6.0 
    react-native-video: ^5.0.2 => 5.0.2 
    react-native-webview: ^7.6.0 => 7.6.0 
    react-navigation: ^4.0.10 => 4.0.10 
    react-navigation-props-mapper: ^1.0.1 => 1.0.1 
    react-navigation-stack: ^1.10.3 => 1.10.3 
    react-navigation-tabs: ^2.6.2 => 2.6.2 
    react-test-renderer: 16.8.6 => 16.8.6 
    rn-fetch-blob: 0.11.2 => 0.11.2 
    uuid: ^3.3.3 => 3.3.3 
  npmGlobalPackages:
    @aws-amplify/cli: 1.6.8
    gatsby-cli: 2.8.18
    npm: 6.11.3
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    serverless: 1.59.3
```

</details>

- Device: iPhone Xs Max
- OS: 13.2.3

**Comment by Amplifiyer** [comment]
@joebernard I don't see any difference between `2.1.2-unstable.6` and `2.1.1` from push notifications perspective (We launch a new unstable version when anything in the monorepo changes and nothing was changed in push notifications between these versions) Have you tried completely cleaning the workspace (deleting lock files and node modules once? This is because we have added a new dependency `"@react-native-community/push-notification-ios": "^1.0.2"` to decouple from `react-native` package.

Please also provide a verbose code sample or a test app where we can try to reproduce this.

Tagging @Ashish-Nanda to have additional 👀

**Comment by joebernard** [comment]
I think I figured out the issue. Up until `2.1.1` I have been configuring Amplify with two separate calls.

```javascript
Amplify.configure({...myAmplifyConfig})
PushNotification.configure({
  appId: "my app id",
  requestIOSPermissions: false,
})
```

This worked fine on the `@unstable` release and is what the [docs](https://aws-amplify.github.io/docs/js/push-notifications) say. However on `2.1.1` I'm able to get `requestIOSPermissions` working only if it is passed into `Amplify.configure`.

```javascript
Amplify.configure({
  ...myAmplifyConfig,
  PushNotification: {
    requestIOSPermissions: false
  }
})
```
Trying to configure these separately causes `requestIOSPermissions` to be ignored. Seems like either a bug or the docs need to be updated.

**Comment by lissau** [comment]
I encountered the same problem on "@aws-amplify/pushnotification": "^2.1.6", "aws-amplify": "^2.2.6",

Setting the `requestIOSPermissions` in `Analytics.configure` works as well

`Analytics.configure({
		...config,
		PushNotification: {
			requestIOSPermissions: false
		}
	});`

**Comment by lissau** [comment]
Just updated to "@aws-amplify/pushnotification": "^3.0.5", "aws-amplify": "^3.0.5"

and this is again not working, neither configuring though `Analytics.configure` or PushNotification.configure`

By downgrading to `aws-amplify": "^2.2.6"` I can again configure through `Analytics.configure`

Should I open a new issue with this?

**Comment by lissau** [comment]
Just updated to "@aws-amplify/pushnotification": "^3.0.5"

and this is again not working, neither configuring though Analytics.configure or PushNotification.configure

By downgrading to `@aws-amplify/pushnotification": "^2.1.6"` I can again configure through `Analytics.configure`

Should I open a new issue with this?

**Comment by Amplifiyer** [comment]
@lissau yes, please create a new issue?
