### ISSUE TITLE
Access to Cognito user attributes inside AppSync Resolvers 

### ISSUE THREAD

**Issue by c0dingarchit3ct** [aws-amplify/amplify-js#4575]
**Is your feature request related to a problem? Please describe.**
I am trying to access custom fields inside the user profile that will help me filter responses back from AppSync resolvers.
For example 
$util.qr($context.args.input.put("org_id", $context.identity.claims.email))
will return 'true' as the claims object does not have the email or any custom attributes

**Describe the solution you'd like**
I would like to be able to do something like this
$util.qr($context.args.input.put("org_id", $context.identity.claims.custom:org))
or read any other attributes

**Describe alternatives you've considered**
Other alternatives will be to move to pipeline resolvers which are not supported by the CLI

**Additional context**
I am trying to create Multi-Tenant solutions where multiple users belonging to different organizations do not see other organizations data without creating a separate infrastructure for every organization

I am willing to work on the code if someone guides me in the right direction!

**Comment by dantasfiles** [comment]
I have some example code doing something similar to you.
https://github.com/dantasfiles/AmplifyMultiTenant

**Comment by c0dingarchit3ct** [comment]
That was brilliant Daniel!

**Comment by c0dingarchit3ct** [comment]
I can confirm that the sample @dantasfiles  provided worked like a charm, I am on now to handling the migration of my existing data.
I will close this feature request.
