### ISSUE TITLE
Datastore: DOMException in Chrome, Sync error  in Firefox

### ISSUE THREAD

**Issue by benjamin79** [aws-amplify/amplify-js#4577]
**Describe the bug**
When i use Datastore.save i get the following error:
 Chrome: 

> datastore.js?2948:16 Uncaught (in promise) DOMException | rejected | @ | datastore.js?2948:16

Firefox: 
> Sync error subscription failed Connection failed: {"errors":[{"message":"Validation error of type FieldUndefined: Field '_version' in type 'Post' is undefined @ 'onUpdatePost/_version'"},{"message":"Validation error of type FieldUndefined: Field '_lastChangedAt' in type 'Post' is undefined @ 'onUpdatePost/_lastChangedAt'"},{"message":"Validation error of type FieldUndefined: Field '_deleted' in type 'Post' is undefined @ 'onUpdatePost/_deleted'"}]}

**To Reproduce**

1. vue create xxx
2. amplify init
3. npm i @aws-amplify/core @aws-amplify/datastore
4. amplify add api
5. amplify codegen models

Code: https://gist.github.com/benjamin79/385351867a8c649ba5f4322169266b79
Schema: https://gist.github.com/benjamin79/79f044287b90df681666750683b6515f

<details>
  <summary><strong>Environment</strong></summary>

  System:
    OS: Windows 10 10.0.18362
    CPU: (16) x64 AMD Ryzen 7 1700X Eight-Core Processor
    Memory: 3.90 GB / 15.93 GB
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.0 - C:\Users\benja\AppData\Roaming\npm\npm.CMD
  Browsers:
    Chrome 78.0.3904.108
    Edge: 44.18362.449.0
    Internet Explorer: 11.0.18362.1
  npmPackages:
    babel-eslint: ^10.0.3 => 10.0.3
    core-js: ^3.4.3 => 3.5.0
    eslint: ^5.16.0 => 5.16.0
    eslint-plugin-vue: ^5.0.0 => 5.2.3
    vue: ^2.6.10 => 2.6.11
    vue-template-compiler: ^2.6.10 => 2.6.11
</details>

**Additional context**
In another issue i read that syncable needs to be active. But i don´t know where to look for or activate if this might have something to do with the error.

**Comment by elorzafe** [comment]
@benjamin79 which version of the cli are you using, can you try the latest?

**Comment by benjamin79** [comment]
@elorzafe 
thanks for your response.

Updated to 4.1.1 (latest) and did a new project. Now i get the same error like in firefox:

![image](https://user-images.githubusercontent.com/8600555/71077200-44fdb280-2187-11ea-9246-c6f452d71813.png)

The red one pops up after about 10 seconds.

**Comment by kevinold** [comment]
@benjamin79 See https://github.com/dabit3/amplify-datastore-example#adding-datastore-to-an-existing-graphql-api

Ultimately you need to run `amplify update api` and follow the prompts to add conflict detection to your api.

**Comment by benjamin79** [comment]
@kevinold thank you, that solved it.
