### ISSUE TITLE
IOS Rejected Ionic social auth

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-js#4585]
I went to push my application apple yesterday and it was rejected due to the way Amplify handles authentication of social providers:

> We recommend implementing the Safari View Controller API to display web content within your app. The Safari View Controller allows the display of a URL and inspection of the certificate from an embedded browser in an app so that customers can verify the webpage URL and SSL certificate to confirm they are entering their sign in credentials into a legitimate page.

This stops my project dead. Is there any way around this, or any plans to enable social authentication in an ionic app using a web URL in which i can open within using the ionic pop over browser?

**Comment by elorzafe** [comment]
@oliverandersencox Can you give us more details about your project. 
- Which social providers are you using?.
- Are you doing OAuth federation or Identity pools federation?
- Which version of Ionic?

**Comment by oliverandersencox** [comment]
@elorzafe  I'm using FB, Google and apple. All against user pools and they work great. The issue is, that being ionic, it will switch over to safari to do the authentication and then navigate back to the app, which is not a pretty UX. 

Im on the latest Ionic.

What I wish to do is use the Ionic capcitor pop over browser to the do the Oauth, and then authenticate once the browser is closed, however I dont see that as being possible.

Unless there is a way to take the token and state and pass it to amplify without calling window.load etc

**Comment by camin-mccluskey** [comment]
@oliverandersencox not sure if this is applicable to you as it's react native but this is how we fixed the issue #4622. Perhaps you could try something similar? As an aside, can I ask, is your Sign in with Apple still working? A few of us are having issues with it recently, when it was working when you raised this issue - issue is here if you wouldn't mind taking a look #4580

**Comment by sammartinez** [comment]
@oliverandersencox Does the above callout work for your use case? Please let us know.

**Comment by oliverandersencox** [comment]
@sammartinez social logins stopped working out of no where, it seems now the window refresh main url being different to the redirect url (has to be as the app is opened using app.bal.. but in order to trigger amplify authentication check we have to reload the actual window.

Why is this now happenning?

how can we use the urlOpener function feature in angular as we cant add it in the main.ts where the amplify config is called. Or is there a way to add the url opener from the actual app.component.ts?
