### ISSUE TITLE
Amplify for Angular takes 5 MB of a build bundle in production

### ISSUE THREAD

**Issue by tomaszs** [aws-amplify/amplify-js#4587]
Hello,

I am using Amplify for Angular library. On production it occurs to take 5 MB of data:

![bundle](https://user-images.githubusercontent.com/834977/71001114-d82dde00-20dc-11ea-85c1-a27e2fb651d8.jpg)

Versions used are:

"@aws-amplify/ui": "^1.0.19",
"aws-amplify": "^1.2.4",
"aws-amplify-angular": "^3.1.4",

Angular: 7.3.9

My questions are:

1. Is such big size something to be expected?
2. Were there any improvements in latest releases?
3.  Does Amplify need whole AWS_SDK?
4. Is it possible to remove unused SDK parts?
5. Is there any way to lower the Amplify size in the production bundle? Even after GZIPPING it's too much for users in regions with slow mobile connection.

**Comment by haverchuck** [comment]
@tomaszs Have you tried configuring your module to only use the portions of Amplify that are needed?

https://aws-amplify.github.io/docs/js/angular#option-2-configuring-the-amplify-provider-with-specified-amplify-js-modules

**Comment by tomaszs** [comment]
@haverchuck thanks i will check it out and let know about the results. @elorzafe thanks for tagging

**Comment by tomaszs** [comment]
@haverchuck It didn't help.

in main.ts i have:

```
import Amplify from '@aws-amplify/core';
import amplify from './aws-exports';
```

in app.module.ts:

import { AmplifyAngularModule, AmplifyService, AmplifyModules } from 'aws-amplify-angular';
import Auth from '@aws-amplify/auth';
...
providers: [
      {
         provide: AmplifyService,
         useFactory:  () => {
           return AmplifyModules({
             Auth
           });
         }
      },

And still i includes whole aws_sdk

**Comment by tomaszs** [comment]
Solved,

I had to change:

import { Auth } from 'aws-amplify';

to:

import Auth from '@aws-amplify/auth';

And this means that here:

https://aws-amplify.github.io/docs/js/authentication

Documentation is wrong, because it tells to use wrong import.

And also here:

https://aws-amplify.github.io/docs/js/angular#importing-the-amplify-angular-module-and-the-amplify-provider

There should be a line about it

in one source file...
