### ISSUE TITLE
Updating a column in Dynamo DB. examples needed. using update expressions

### ISSUE THREAD

**Issue by 29er** [aws-amplify/amplify-js#459]
In order to update a record in a Dynamo table, I need to know how to update only certain columns in that record.
IE:  Update MyTable set Title = "my title" where id=12345
How can I achieve this with amplify? 

**without** Amplify,  and just using the AWS SDK, that would be done like this:
```
const docClient = new AWS.DynamoDB.DocumentClient();
let params = {
        TableName:table,
        Key:{
            "year": year,
            "title": title
        },
        UpdateExpression: "set info.rating = :r, info.plot=:p, info.actors=:a",
        ExpressionAttributeValues:{
            ":r":5.5,
            ":p":"Everything happens all at once.",
            ":a":["Larry", "Moe", "Curly"]
        },
        ReturnValues:"UPDATED_NEW"
    };

    docClient.update(params, function(err, data) { ....

```
I set up a backend/api using the docs here to ( enable cloud API to do CRUD operations)
https://docs.aws.amazon.com/aws-mobile/latest/developerguide/web-access-databases.html

using Amplify,  'put' method works just fine in creating the initial record. 

```
import Amplify, { API } from 'aws-amplify';
....
const path = '/MyTable';
const newRecord = {.......}
const apiResponse = await API.put('MyTableCRUD', path, newRecord);
```

The Amplify CRUD API does not have an 'update' method, only post/put/get/delete.
So how can I achieve this??

Thanks for the guidance!

**Comment by richardzcode** [comment]
Hey @29er PUT is meant for update, although it would create too if record does not exist. We will update documentation with examples.

**Comment by 29er** [comment]
great ! thanks @richardzcode . so will it support the Update Expression Logic as well ?
ie: 
```
let params = {
        TableName:table,
        Key:{
            "year": year,
            "title": title
        },
        UpdateExpression: "set info.rating = :r, info.plot=:p, info.actors=:a",
        ExpressionAttributeValues:{
            ":r":5.5,
            ":p":"Everything happens all at once.",
            ":a":["Larry", "Moe", "Curly"]
        },
        ReturnValues:"UPDATED_NEW"
    };

```

**Comment by 29er** [comment]
By the way, if I follow the documentation so far,  and lets say I send params like this:
```
const params = {
	body: {
		SettingId: '12345',
		Description: ' update description'
	}
}
const apiResponse = await API.put('MyTableCRUD', myTable, params);
```

That saved the 'Description' field for that record just fine , but the other columns in the table get wiped out. Which is why I am wondering about where to put Update Expressions like above...

**Comment by jordanranz** [comment]
Hi @29er, the put method should work for what you are trying to achieve. When using put you must include all other columns you would like in that db entry. Put essentially replaces the instance of the id passed in with a new representation. In your case the entry with SettingId: '12345' would be replaced by whatever you pass with the request params.

I am going to close this issue. Please reopen if you are still having issues or have any related questions.
