### ISSUE TITLE
React Native - Valid email/username with invalid password returns RNAWSCognito error

### ISSUE THREAD

**Issue by ericclemmons** [aws-amplify/amplify-js#4592]
**Describe the bug**

Related to my testing in https://github.com/aws-amplify/amplify-js/pull/4520#issuecomment-566778280, using `withAuthenticator` and signing in with a **valid** username and **invalid** password results in a `null` error, vs. a user-centric error.

**To Reproduce**

1. Perform Step 1 of https://aws-amplify.github.io/docs/js/start#option-2-use-react-native-cli-recommended-if-you-have-mobile-development-experience
2. Update `App.js` to use `withAuthenticator` (see below)
3. Update `Amplify.configure()` with valid auth settings.
4. Type in a valid username/email.
5. Type in an invalid password.
6. Click the submit button.
7. You should see the errors below.

**Expected behavior**

Expected a user-centric error (e.g. "Invalid login") to get returned.

**Screenshots**

> <img width="336" alt="Screen Shot 2019-12-17 at 3 20 18 PM" src="https://user-images.githubusercontent.com/15182/71046992-f43a7b00-20ee-11ea-8e78-c0add55ee1c1.png">
>
> <img width="914" alt="Screen Shot 2019-12-17 at 3 04 48 PM" src="https://user-images.githubusercontent.com/15182/71046995-f7356b80-20ee-11ea-9609-bb254859a1c5.png">

<details>
  <summary><strong>Environment</strong></summary>

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 154.38 MB / 16.00 GB
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.13.1 - ~/.config/nvm/12.13.1/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.12.1 - ~/.config/nvm/12.13.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 79.0.3945.79
    Firefox: 68.3.0
    Safari: 13.0.4
  npmPackages:
    @babel/core: ^7.6.2 => 7.7.5
    @babel/runtime: ^7.6.2 => 7.7.6
    @react-native-community/eslint-config: ^0.0.5 => 0.0.5
    aws-amplify: ^2.2.0 => 2.2.0
    aws-amplify-react: ^3.1.1 => 3.1.1
    aws-amplify-react-native: ^2.2.3 => 2.2.3
    babel-jest: ^24.9.0 => 24.9.0
    eslint: ^6.5.1 => 6.7.2
    jest: ^24.9.0 => 24.9.0
    metro-react-native-babel-preset: ^0.56.0 => 0.56.3
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
    react-test-renderer: 16.9.0 => 16.9.0
  npmGlobalPackages:
    npm: 6.12.1

```

</details>

**Sample code**

```diff
diff --git a/App.js b/App.js
index bb77580..5629043 100644
--- a/App.js
+++ b/App.js
@@ -6,6 +6,9 @@
  * @flow
  */

+import Amplify from "aws-amplify"
+import { withAuthenticator } from "aws-amplify-react-native";
+
 import React from 'react';
 import {
   SafeAreaView,
@@ -24,6 +27,28 @@ import {
   ReloadInstructions,
 } from 'react-native/Libraries/NewAppScreen';

+Amplify.configure({
+  ...
+})
+
 const App: () => React$Node = () => {
   return (
     <>
@@ -111,4 +136,4 @@ const styles = StyleSheet.create({
   },
 });

-export default App;
+export default withAuthenticator(App);
```

The culprit seems to be this code:
https://github.com/aws-amplify/amplify-js/blob/867412030de57fd74078b609252de6f7f81ad331/packages/amazon-cognito-identity-js/enhance-rn.js#L13-L14

**Comment by sammartinez** [comment]
Resolving as based on the above PR
