### ISSUE TITLE
Internet Explorer 11 InvalidSignatureException Error from API Gateway

### ISSUE THREAD

**Issue by NKHenry** [aws-amplify/amplify-js#4601]
**Describe the bug**
When using Internet explorer, calling API.get results in an InvalidSignatureException from API Gateway. We're using Cognito User Pools and and AWS_IAM authentication behind API Gateway.

Things are working fine on Safari and Chrome.

The format of the Authorization header appears correct, it looks like the signature is the primary issue. I've tried taking the AccessId, SecretKey, and SessionToken from the failed request and plugged them into Postman which succeeds. This implies that the credentials are valid, something is just going wrong calculating the signature. 

We've also tried importing the signer directly from @aws-amplify/core and calling our API using both axios and fetch. Once again, chrome succeeds and Internet Explorer results in an InvalidSignatureException.

Our app is using Next js with typescript.

**To Reproduce**
It's difficult to replicate as you need to set up both API and FE. I'll see if I can replicate the behaviour using some templates though.

**Expected behavior**
Amplify to correctly sign the API requests in the AWS v4 format.  

**Screenshots**

**Environment**
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 3.04 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.7.0 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.2.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 79.0.3945.79
    Safari: 13.0.4
    Safari Technology Preview: 13.1
  npmPackages:
    webpack: ^4.39.2 => 4.41.3 
  npmGlobalPackages:
    ios-deploy: 1.9.3
    lerna: 3.18.4
    next: 8.1.0
    now: 16.5.2
    npm: 6.2.0
    typescript: 3.7.3
```

**Additional context**
Error message returned from API Gateway:
'The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method.'

AWS Config
```
export default {
  Auth: {
    identityPoolId: 'ap-southeast-2:******',
    region: 'ap-southeast-2',
    userPoolId: 'ap-southeast-2_*******',
    userPoolWebClientId: '**********',
  },
  API: {
    endpoints: [
      {
        name: 'api-service',
        endpoint:
          'https://**********.execute-api.ap-southeast-2.amazonaws.com/dev/',
      },
    ],
    region: 'ap-southeast-2',
  },
 Storage: {
    bucket: '*******',
    region: 'ap-southeast-2',
 },
};
```

**Sample code**
Example of how we are using the API module.
```
const makeGetRequest = async (id: string) => {
  const path = 'foo/${id}';

  try {
    const response: IResponse = await API.get(API.name, path, {});

    return response;
  } catch (error) {
    throw error;
  }
};
```

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by ericclemmons** [comment]
@NKHenry Can you help answer a few questions for me?  I'm working on replicating this and want to ensure I'm following along exactly:

- Can you clarify what you mean by setting up both API & _FE_? 
- I don't see `aws-amplify` or `@aws-amplify/core` listed in your environment's dependencies. (`next` appears to be installed globally)  Did run the command in the issue template within your Next.js project (or sub-package)?
- Can you provide a larger code sample?  Specifically, how are you running `Amplify.configure` (since your AWS config is different than `aws-exports.js` creates), and how are you importing & configuring `API`?

**Comment by NKHenry** [comment]
@ericclemmons 

By FE I just meant a front end app that used Amplify. By API I meant an API gateway endpoint that requires an awsv4 signature.

Since the behaviour only appears on Internet Explorer we need to call an API from an application running in the browser.

Here are the dependencies from the root of our lerna project. I originally ran the command from one of the sub-packages.
We are currently testing with an older version of amplify but we have replicated the behaviour with an up to date version.
``` 
 System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 239.38 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.7.0 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.2.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 79.0.3945.88
    Safari: 13.0.4
    Safari Technology Preview: 13.1
  npmPackages:
    @aws-amplify/api: 1.2.4-unstable.3 => 1.2.4-unstable.3+be6d5400 
    @aws-amplify/auth: 1.4.4-unstable.3 => 1.4.4-unstable.3+be6d5400 
    @babel/core: ^7.5.5 => 7.7.7 
    @babel/preset-env: ^7.5.5 => 7.7.7 
    @babel/preset-react: ^7.0.0 => 7.7.4 
    @babel/preset-typescript: ^7.3.3 => 7.7.7 
    @types/react: ^16.8.25 => 16.9.16 
    @types/styled-components: ^4.1.18 => 4.4.1 
    babel-jest: ^24.9.0 => 24.9.0 
    babel-plugin-styled-components: ^1.10.6 => 1.10.6 
    dayjs: ^1.8.17 => 1.8.18 
    lerna: ^3.16.4 => 3.19.0 
    prettier: ^1.18.2 => 1.19.1 
    react: ^16.9.0 => 16.12.0 
    react-dom: ^16.11.0 => 16.12.0 
    styled-components: ^4.3.2 => 4.4.1 
    tslint: ^5.18.0 => 5.20.1 
    tslint-config-airbnb: ^5.11.1 => 5.11.2 
    tslint-config-prettier: ^1.18.0 => 1.18.0 
    tslint-plugin-prettier: ^2.0.1 => 2.0.1 
    typescript: ^3.6.4 => 3.7.3 
  npmGlobalPackages:
    @aws-amplify/cli: 4.6.0
    graphql: 14.5.8
    ios-deploy: 1.9.3
    lerna: 3.18.4
    next: 8.1.0
    now: 16.5.2
    npm: 6.2.0
    typescript: 3.7.3
```

We are calling API.configure in our _app.tsx file of the next project. Just to reiterate though the project works perfectly on modern browsers (Chrome, Safari, etc.). So the way we are configuring the API module has been shown to work in at least some situations.

```
import React, { createContext } from 'react';
import App from 'next/app';
import Auth from '@aws-amplify/auth';
import API from '@aws-amplify/api';

import Main from './layouts/Main';

const  AWSExports = {
   Auth: {
       identityPoolId: 'ap-southeast-2:******',
       region: 'ap-southeast-2',
       userPoolId: 'ap-southeast-2_*******',
       userPoolWebClientId: '**********',
     },
     API: {
       endpoints: [
         {
           name: 'api-service',
           endpoint:
             'https://**********.execute-api.ap-southeast-2.amazonaws.com/dev/',
         },
       ],
       region: 'ap-southeast-2',
     },
    Storage: {
       bucket: '*******',
       region: 'ap-southeast-2',
    },
};

export const AppShellFactory = (): any => {
  return class AppShell extends App {
    render() {
      Auth.configure(AWSExports);
      API.configure(AWSExports);

      const { Component, pageProps } = this.props;

      const AuthWrapper = Main(Component, pageProps);

      return (
         <AuthWrapper />
      );
    }
  };
};

```

**Comment by ericclemmons** [comment]
This helps a bunch!  I'm going to continue working on reproducing this...

**Comment by ericclemmons** [comment]
@NKHenry I'm still working on reproducing this locally, but the biggest difference between our projects is the version of the packages:

```json
@aws-amplify/api: 1.2.4-unstable.3 => 1.2.4-unstable.3+be6d5400 
@aws-amplify/auth: 1.4.4-unstable.3 => 1.4.4-unstable.3+be6d5400 
```

Can you verify the behavior against `1.6.3` (the last `1.x` release) and `2.1.3` (latest)?

**Comment by NKHenry** [comment]
@ericclemmons Tried against the lastest 1.x.x versions and experienced the same behaviour (modern browsers behave normally, IE breaks).

Interestingly with the 2.1.3 versions the app broke on modern browsers as well. On chrome the authorization header wasn't being included at all and the API responded with a "missing authentication token" 403 error

**Comment by ericclemmons** [comment]
This helps a bit.  Ideally, your app works in modern browsers with the latest version (including bug fixes), as well as IE11 (with polyfills).

I've been able to successfully make API calls in a local project using the latest versions in all browsers, but that project is using `aws-exports.js` from the Amplify CLI:

```js
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id: "us-east-1:••••••••••••",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-••••••••••••",
  aws_user_pools_web_client_id: "••••••••••••",
  oauth: {
    domain: "••••••••••••.auth.us-east-1.amazoncognito.com",
    scope: [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin"
    ],
    redirectSignIn: "http://localhost:3000/",
    redirectSignOut: "http://localhost:3000/",
    responseType: "code"
  },
  federationTarget: "COGNITO_USER_POOLS",
  aws_appsync_graphqlEndpoint:
    "https://••••••••••••.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
  aws_user_files_s3_bucket: "••••••••••••",
  aws_user_files_s3_bucket_region: "us-east-1",
  aws_content_delivery_bucket: "••••••••••••",
  aws_content_delivery_bucket_region: "us-east-1",
  aws_content_delivery_url: "https://••••••••••••.cloudfront.net",
  predictions: {
    identify: {
      identifyLabels: {
        proxy: false,
        region: "us-east-1",
        defaults: {
          type: "LABELS"
        }
      }
    }
  }
};


export default awsmobile;
```

Is your project setup with the Amplify CLI, or are forced to configure it manually?
> https://aws-amplify.github.io/docs/js/authentication#manual-setup

**Comment by NKHenry** [comment]
We started this project with aws-amplify a long time ago, before the CLI existed. I think amplify was at version 0.2.3 back then.

We chose to continue with the manual configuration as we only needed some parts of the AUTH and API modules and wanted to avoid bloat.

I'll try using the CLI to generate the environment.

**Comment by ericclemmons** [comment]
From what I've been able to reproduce, it may be a difference in configuration from when you started and what exists today (which is streamlined to match the CLI `aws-exports.js` artifact).

For example, I see that you specify `API.endpoints` like our docs indicate for custom headers:
> https://aws-amplify.github.io/docs/js/api#custom-request-headers

But docs for AppSync indicate using `Amplify.configure`: 
> https://aws-amplify.github.io/docs/js/api#custom-request-headers

For next steps, using the latest versions, could you try & let me know if configuring only Auth (via https://aws-amplify.github.io/docs/js/authentication#manual-setup) works in Chrome?

Hopefully narrowing configuring down to a single category will help get things partially functional again before we move onto the API.

I've been able to validate that IE11 does work for a Auth & API (GraphQL), but that application was bootstrapped with the CLI...

**Comment by makeitraina** [comment]
@NKHenry did you ever resolve this issue? Im also seeing this happen
