### ISSUE TITLE
How to auto-select corporate id on hostedUISignIn?

### ISSUE THREAD

**Issue by cinder92** [aws-amplify/amplify-js#4603]
** Which Category is your question related to? **
Sign In
** What AWS Services are you utilizing? **
Push, Pubsub, Analytics
** Provide additional details e.g. code snippets **

![Captura de Pantalla 2019-12-19 a la(s) 1 52 49](https://user-images.githubusercontent.com/4725556/71154923-461ff580-2202-11ea-862a-60bbaa73d84e.png)

How can i auto-select the only result on screen after calling `hostedUISignIn()`?

Thanks

**Comment by haverchuck** [comment]
@cinder92  - Once your user has been routed to the Hosted UI, Amplify no longer has control over what occurs.  However, if you know in advance that this is going to be the only option, you can pass a 'customProviderprovider' parameter to Auth.federatedSignIn which will cause Hosted UI to immediately redirect to the specified provider.
