### ISSUE TITLE
DataStore API Documentation link is broken

### ISSUE THREAD

**Issue by stevensacks** [aws-amplify/amplify-js#4604]
**Describe the bug**
https://aws-amplify.github.io/docs/js/datastore#api-reference

> For the complete API documentation for DataStore, visit our API Reference

The URL of that link is:
https://aws-amplify.github.io/amplify-js/api/classes/DataStoreclass.html

That link does not exist and automatically redirects to:
https://aws-amplify.github.io/docs/js/start

I checked here:
https://aws-amplify.github.io/amplify-js/api/index.html

And there's no mention of DataStore whatsoever anywhere in the API docs.

Is this a placeholder for later when the API docs are ready, or is the page legitimately missing?

**Comment by Amplifiyer** [comment]
@stevensacks Thanks for catching the error. Typedocs for datastore category haven't been generated yet. I'll see if I can get the docs generated this week.

https://aws-amplify.github.io/amplify-js/api/index.html is a link to docs to the `API` category, however the link here is for the API reference (not to be confused with Amplify API category) for the `datastore` category.
