### ISSUE TITLE
amplify API.post Cloudfront 504 Error & Timeout settings

### ISSUE THREAD

**Issue by Akiren** [aws-amplify/amplify-js#4607]
This issue / question is related to using the Amplify API / VueJS

I have everything working perfectly.. I am using a backend lambda function with an api endpoint and I call it via amplify

When the backend returns a small number of items in an array I get them back no problem.... When the data is larger I get a generic error

I am using

import API from "@aws-amplify/api";
import config from "../aws-exports";
API.configure(config);

APi.post // Get data

I have updated to the latest version of the Amplify API v2.1.2

The backend is returning an array with 78 items with 10 subitems with 5 attributes each... not alot of data.

My lambda logs return without error and log everything perfectly before sending...the CORS issue is a generic issue that only happens when my backend returns the 78 items.... If I do a simple array split and make the payload smaller it returns without error. There are no payload or simple code errors.

The frontend returns 
xxxxxxxxxxxxx-api.us-east-1.amazonaws.com/dev/calculate:1 Failed to load resource: the server responded with a status of 504 ()
:8080/#/:1 Access to XMLHttpRequest at 'https://xxxxxxxxxxxxx.execute-api.us-east-1.amazonaws.com/dev/calculate' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
Home.vue?76f2:1623 Error: Network Error
    at createError (createError.js?994a:16)
    at XMLHttpRequest.handleError (xhr.js?a6eb:81)

**Comment by Amplifiyer** [comment]
@Akiren Can you share your request and response headers for both the requests, one that works and one that doesn't. Also see if there is any OPTIONS request made prior to POST and share it's contents too. Thank you!

**Comment by Akiren** [comment]
No request headers, 

the response headers are the default templated when using amplify

app.use(function(req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header(
        "Access-Control-Allow-Headers",
        "Origin, X-Requested-With, Content-Type, Accept"
    );
    next();
});

**Comment by Amplifiyer** [comment]
@Akiren, sorry for the confusion, I meant to share the headers from the actual request and response made by the browser from the Network tab in the developer console.

**Comment by Akiren** [comment]
Ok here are the 2 headers that come back... one is successful and one is fail... the ONLY difference is the failed response returns 75 items and the successful response returns only 40. Both come back within 40 seconds or so.

**Comment by Akiren** [comment]
FAILED HEADER ( with 75 items on the backend )

Request URL: https://xxxxxxxx.execute-api.us-east-1.amazonaws.com/dev/calculate
Request Method: POST
Status Code: 504 
Remote Address: xx.xx.xx.xx:443
Referrer Policy: no-referrer-when-downgrade
content-encoding: gzip
content-length: 61

content-type: application/json
date: Tue, 24 Dec 2019 18:44:17 GMT
status: 504
via: 1.1 xxxxxxxxxxxx.cloudfront.net (CloudFront)
x-amz-apigw-id: FONfxFjRoAMFjDw=
x-amz-cf-id: z3reiJBsQQ0RDznLkC2_vkAZwBDOyWKBAp0TiGnFOM8gs8I9w2siQA==
x-amz-cf-pop: ORD52-C2
x-amzn-requestid: f533db32-7f4c-4ec2-89ab-2ecec5894de8
x-cache: Error from cloudfront
:authority: xxxxxxxx.execute-api.us-east-1.amazonaws.com
:method: POST
:path: /dev/calculate
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
content-length: 1135
content-type: application/json; charset=UTF-8
dnt: 1
origin: http://localhost:8080
referer: http://localhost:8080/
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36

**Comment by Akiren** [comment]
SUCCESS ( same code, same payload return... but only 40 items )

Request URL: https://xxxxxxxxx.execute-api.us-east-1.amazonaws.com/dev/calculate
Request Method: POST
Status Code: 200 
Remote Address: 99.84.167.121:443
Referrer Policy: no-referrer-when-downgrade
access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept
access-control-allow-origin: *
content-encoding: gzip
content-length: 4768

content-type: application/json; charset=utf-8
date: Tue, 24 Dec 2019 18:46:48 GMT
etag: W/"19e5e-8r9uL8AgBl+CiiBUHkstgP3MONU"
status: 200
via: 1.1 xxxxxxxxxxx.cloudfront.net (CloudFront)
x-amz-apigw-id: FON5rEvLoAMFkZw=
x-amz-cf-id: aF7CMQerR4QBgnFhbIvqnqRW7ZwBL_06fpmdVrAh6mmKRPE8WQZFNA==
x-amz-cf-pop: ORD52-C2
x-amzn-remapped-connection: close
x-amzn-remapped-content-length: 106078
x-amzn-remapped-date: Tue, 24 Dec 2019 18:46:48 GMT
x-amzn-requestid: 9db80559-5c64-48cd-ba0c-a3a67a8aa20b
x-amzn-trace-id: Root=1-5e025d0a-c7bef33cc5ad76d272e56f40;Sampled=0
x-cache: Miss from cloudfront
x-powered-by: Express
:authority: xxxxxxxxx.execute-api.us-east-1.amazonaws.com
:method: POST
:path: /dev/calculate
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
content-length: 1137
content-type: application/json; charset=UTF-8
dnt: 1
origin: http://localhost:8080
referer: http://localhost:8080/
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36

**Comment by Akiren** [comment]
When I look @ the lambda logs, both responses are successful as a res.json using the template express middleware....  Both respond within 20-30 seconds without error

**Comment by Akiren** [comment]
I feel like this is my issue
https://aws.amazon.com/premiumsupport/knowledge-center/resolve-http-504-errors-cloudfront/

But amplify doesnt give me access to cloudfront... how can I change this setting @Amplifiyer
