### ISSUE TITLE
Authenticator Angular not using copy/paste values on mobile devices

### ISSUE THREAD

**Issue by hfahlbusch** [aws-amplify/amplify-js#4613]
**Describe the bug**
Using the authenticator component normal version in an angular application.
If the SignIn form is used on a mobile device (ios, android) e.g. iPhone X and the value for username or password is copied into the input field without hitting additional keys, then the values are not used.

Workaround found: if a character is added to the password by keypress and deleted and again, it works.

**To Reproduce**
1. Open SignIn Form in an angular app on a mobile device (iPhone X).
2. Type in a registered username and just copy the password into the passwort field.
3. Then submit form.

**Expected behavior**
Copied values should be used by the authenticator (like in the desktop browsers)

**Screenshots**
<img width="481" alt="Bildschirmfoto 2019-12-20 um 13 22 27" src="https://user-images.githubusercontent.com/39269362/71254611-d3ab3480-232b-11ea-8f32-71c22b75e73e.png">

**Smartphone (please complete the following information):**

- Device: iPhoneX, Samsung Galaxy Fold 2, Apple MGL12B/A iPad Air 2
- OS: [iOS13.3, Android 9, iOS12.13]
- Browser [chrome/safari, chrome, safari]

**Comment by Amplifiyer** [comment]
Possibly related #3553

**Comment by hfahlbusch** [comment]
@Amplifiyer Yes, absolutely. 
I had the same issue, when copying the username too. Because the pasted value is not recognized, the missing username error is thrown.

**Comment by hfahlbusch** [comment]
I had a look at the source code. It's not only broken for mobile devices, it's also broken on desktop. On desktop I was using CTRL+P shortcut, but when only using the mouse with context menu it's broken too. The input fields are only listening to the keyup event.

This could be solved with using angular form model data binding.

**Comment by ashika01** [comment]
@hfahlbusch - Looks like this is fixed with new UI when testing on desktop. I am working on testing this on mobile

**Comment by sammartinez** [comment]
@hfahlbusch This is resolved in the new UI Implementations, please verify that this is resolved for you and works as expected.
