### ISSUE TITLE
Failed to execute 'get' on 'IDBObjectStore' when using Datastore.save on child element

### ISSUE THREAD

**Issue by benjamin79** [aws-amplify/amplify-js#4619]
**Describe the bug**
When i use Datastore.save for a child element i get the following error:

>  Failed to execute 'get' on 'IDBObjectStore': No key or key range specified.

```
     const post =  await DataStore.save(
          new Post({
            title: `New title`,
            rating: 2,
            status: PostStatus.ACTIVE
          })
        )
     console.log(post);
      const comment  = await DataStore.save(
        new Comment({
          content: "Loving Amplify DataStore!",
          post
        })
      );
```
post insert itself works

Update: Got it to work when using a query for the new post and inserting this one instead the return from the post save. Seems new Posts returns an Array instead of an Object. Don´t know why. Followed the example from: https://aws-amplify.github.io/docs/js/datastore

**To Reproduce**

1. vue create xxx
2. amplify init
3. npm i @aws-amplify/core @aws-amplify/datastore
4. amplify add api
5. amplify codegen models

Code: https://gist.github.com/benjamin79/385351867a8c649ba5f4322169266b79
Schema: https://gist.github.com/benjamin79/79f044287b90df681666750683b6515f

<details>
  <summary><strong>Environment</strong></summary>

  System:
    OS: Windows 10 10.0.18362
    CPU: (16) x64 AMD Ryzen 7 1700X Eight-Core Processor
    Memory: 3.90 GB / 15.93 GB
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.0 - C:\Users\benja\AppData\Roaming\npm\npm.CMD
  Browsers:
    Chrome 78.0.3904.108
    Edge: 44.18362.449.0
    Internet Explorer: 11.0.18362.1
  npmPackages:
    babel-eslint: ^10.0.3 => 10.0.3
    core-js: ^3.4.3 => 3.5.0
    eslint: ^5.16.0 => 5.16.0
    eslint-plugin-vue: ^5.0.0 => 5.2.3
    vue: ^2.6.10 => 2.6.11
    vue-template-compiler: ^2.6.10 => 2.6.11
</details>

**Comment by djom202** [comment]
I facing the same issue right now. There is any workaround?
