### ISSUE TITLE
Amplify failing to built React App!

### ISSUE THREAD

**Issue by hndfaw** [aws-amplify/amplify-js#4620]
I have a React application deployed to AWS Amplify, and every day I'm having couple of changes and push to GitHub which it re-builds on Amplify, Today I am having this issue which I don' t see anything wrong with my React build. any ideas about how to solve this?

                                 16 verbose Linux 4.14.152-98.182.amzn1.x86_64
                                 17 verbose argv "/root/.nvm/versions/node/v10.16.0/bin/node" "/root/.nvm/versions/node/v10.16.0/bin/npm" "run" "build"
                                 18 verbose node v10.16.0
                                 19 verbose npm  v6.9.0
                                 20 error code ELIFECYCLE
                                 21 error errno 1
                                 22 error hindreen@0.1.0 build: `react-scripts build`
                                 22 error Exit status 1
                                 23 error Failed at the hindreen@0.1.0 build script.
                                 23 error This is probably not a problem with npm. There is likely additional logging output above.
                                 24 verbose exit [ 1, true ]
2019-12-21T20:57:40.959Z [ERROR]: !!! Build failed
2019-12-21T20:57:41.017Z [ERROR]: !!! Non-Zero Exit Code detected
2019-12-21T20:57:41.018Z [INFO]: # Starting environment caching...
2019-12-21T20:57:41.018Z [INFO]: # Environment caching completed
Terminating logging...

**Comment by saulscs** [comment]
Hi, I have the same issue,  How did you resolve it ?
