### ISSUE TITLE
Using a Webview to complete federated login (React Native)

### ISSUE THREAD

**Issue by camin-mccluskey** [aws-amplify/amplify-js#4622]
### Which Category is your question related to? 
Auth
### What AWS Services are you utilizing? 
Cognito
### Provide additional details e.g. code snippets 
Is it possible to use a Webview to open the federated login pages in a bare (not expo) react native app? Our application has been rejected from the app store because the redirect happens in Safari when we call `Auth.federatedSignIn({provider: 'Facebook'})` for example. As an aside my `aws-exports.js` file does not have the same structure as suggested in the docs but rather looks like
```
awsmobile = {
    ...
    oauth: {
        ...
    }
}
```
Any help would be greatly appreciated!

**Comment by Amplifiyer** [comment]
@camin-mccluskey I believe you are looking for something like (or alternative of) [`WebBrowser.openAuthSessionAsync`](https://docs.expo.io/versions/latest/sdk/webbrowser/#webbrowseropenauthsessionasyncurl-redirecturl) which opens the Auth session in a model view.

There is nothing out of the box supported by Amplify, however if you do find any way to do this in bare react native app, Amplify provides you a escape hatch to plug in your own url opener using as mentioned here https://aws-amplify.github.io/docs/js/authentication#a-note-for-expo-users

Regarding possibly wrong docs, can you link us the doc snipper or URL which has the wrong information? The config example you mentioned is correct. In case there is another level `Auth` in there like below, that is also correct and amplify library is capable of handling both.

```javascript
Amplify.configure({
    Auth: {
        // other configurations...
        // ....
        oauth: oauth
    },
    // ...
});

**Comment by camin-mccluskey** [comment]
Thanks @Amplifiyer, really appreciate the help! This works perfectly but myself (and it seems quite a few others) are having a major problem with Sign in With Apple using the federated login. As you might know, Apple required this for approval to the app store and our app got recently approved then Apple login broke and we cannot push any updates as it remains broken. The issue is here #4580 and I'd really appreciate a reply from someone involved in this project there, as I said this is currently breaking in production with seemingly no way to fix it. Thanks!

**Comment by Amplifiyer** [comment]
thanks @camin-mccluskey for the update. I'll let the team know about the Sign in with apple issue and we will look into it as soon as possible.

**Comment by ahtokca** [comment]
@camin-mccluskey Did you find a way to use a web-view?

**Comment by ahtokca** [comment]
My app just got rejected by Apply because of redirect to browser for login

**Comment by rjuevesano** [comment]
Hello. Is it possible to show the apple sign in without showing the in-app browser? And how to do that?
