### ISSUE TITLE
on clicking pushnotification, onNotificationOpened is not triggered in android when app is killed.

### ISSUE THREAD

**Issue by akashnsmahaswami** [aws-amplify/amplify-js#4627]
**Describe the bug**
onNotificationOpened is not triggered in android when app is killed before receiving notification.

**To Reproduce**
1.Kill the App before receiving push notification.
2.Once you receive the notification, click on it.
3. application opens, but neither **onNotificationOpened** nor **onNotification** is triggered.

**Additional context**
Works fine in ios.
Works fine in android when app is kept in background without killing.

**package versions**
    aws-amplify : 1.1.40
   react-native : 0.59.10

**Adb log on click of notification**

12-24 14:37:36.850 28645 28645 I RNPushNotificationBroadcastReceiver: broadcaster received
12-24 14:37:36.854 28645 28645 I emit    : notification opened: Bundle[{userInteraction=false, pinpoint.notification.title=Test demo, pinpoint.notification.body=my demo description..., id=-64503234, pinpoint.campaign.campaign_id=_DIRECT, pinpoint.deeplink=mydemoapp://term/root/app/page1/0abdd75d-b91b-4e3b-a667-e07hg764ug, pinpoint.notification.silentPush=0}]
12-24 14:37:36.864  2416 16283 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@694b46d attribute=null, token = android.os.BinderProxy@c1100d1
12-24 14:37:36.872  2416 19666 I ActivityManager: START u0 {flg=0x10200000 cmp=com.mydemoapp/.MainActivity} from uid 10525 on display 0
12-24 14:37:36.891 28645 28645 I RNPushNotificationBroadcastReceiver: broadcaster received
12-24 14:37:36.892 28645 28645 I emit    : notification opened: Bundle[{userInteraction=false, pinpoint.notification.title=Test demo, pinpoint.notification.body=my demo description..., id=-64503234, pinpoint.campaign.campaign_id=_DIRECT, pinpoint.deeplink=mydemoapp://term/root/app/page1/0abdd75d-b91b-4e3b-a667-e07hg764ug, pinpoint.notification.silentPush=0}]
12-24 14:37:36.893  3139  9775 D ProcSpeedReader: Failed to read freq stats from null
12-24 14:37:36.897  2416  3749 I ActivityManager: START u0 {flg=0x10200000 cmp=com.mydemoapp/.MainActivity} from uid 10525 on display 0
12-24 14:37:36.913  3139  9775 D ProcSpeedReader: Failed to read freq stats from null
12-24 14:37:37.059  4279  4336 I MicroDetectionState: Should stop hotword detection immediately - false
12-24 14:37:37.060  4279  4336 I MicroDetector: Keeping mic open: false
12-24 14:37:37.063  4279  4336 I RecognitionAudioControl: #shutdownAudio [requestId: -4262453910631879354, keepAudioOpen: false, forced: true]
12-24 14:37:37.063  4279  4336 I RecognitionAudioControl: #internalShutdownAudio [requestId: -4262453910631879354]
12-24 14:37:37.064  4279  4336 I RecognitionAudioControl: #internalShutdownAudio [keepAudioOpen: false, forced: true]
12-24 14:37:37.064  4279  4336 I RecognitionAudioControl: #actualShutdownAudio
12-24 14:37:37.064  4279  4336 I AudioController: #shutdown [requestId=-4262453910631879354]
12-24 14:37:37.064  4279 28582 I AudioController: internalShutdown
12-24 14:37:37.066  4279 28841 I MicroRecognitionRunner: Stopping hotword detection.
12-24 14:37:37.069   372 28598 D audio_hw_primary: in_standby: enter: stream (0xb29b5500) usecase(7: audio-record)
12-24 14:37:37.085  4279 28594 E DeviceStateChecker: DeviceStateChecker cancelled
12-24 14:37:37.106   372 28598 D hardware_info: hw_info_append_hw_type : device_name = voice-rec-mic
12-24 14:37:37.108   372 11976 D APM_AudioPolicyManager: stopInput() input 1102
12-24 14:37:37.110   372 28598 D audio_hw_primary: in_set_parameters: enter: kvpairs=routing=0
12-24 14:37:37.124   372   683 D audio_hw_primary: adev_close_input_stream: enter:stream_handle(0xb29b5500)
12-24 14:37:37.124   372   683 D audio_hw_primary: in_standby: enter: stream (0xb29b5500) usecase(7: audio-record)
12-24 14:37:37.125  4279 28582 I MicrophoneInputStream: mic_close  SR : 16000 CC : 16 SO : 1999
12-24 14:37:37.126  4279 28582 E AudioSource: Stop listening is called on already closed AudioSource

**Comment by Amplifiyer** [comment]
Related #2975

**Comment by ashika01** [comment]
@akashnsmahaswami : Hi, I am unable to reproduce this bug. I tried on android device and I am able to change the state value in my react native app based of `onNotification`. Could you provide with sample code and give us context on how you setup your app?

**Comment by ashika01** [comment]
I see what you are saying here. I am doing some investigating on this.

**Comment by angadp** [comment]
I'm not seeing console logs from onnotificationopened. I can see the notification and the console logs of onnotification.
