### ISSUE TITLE
different URLs for Authenticator component's states?

### ISSUE THREAD

**Issue by damianrr** [aws-amplify/amplify-js#4628]
** Which Category is your question related to? **
E.g. Auth
** What AWS Services are you utilizing? **
E.g. Cognito
** Provide additional details e.g. code snippets **

Hello,

Is there a way of having different URLs for Authenticator components? Meaning mywebsite/login would open the component with the "signIn" authState and mywebsite/signup on the "signUp"?

Thanks.

**Comment by Amplifiyer** [comment]
@damianrr you should be able to do it with the frontend framework you are using and configuring withAuthentication or Authenticator component to only render certain parts of the component https://aws-amplify.github.io/docs/js/authentication#using-the-authenticator-component

you can also [override](https://aws-amplify.github.io/docs/js/authentication#customize-your-own-components) these components to better suit your needs.

Finally if this also doesn't solve your use case, you can use Amplify auth APIs to fully customize the auth flow in your app.

**Comment by damianrr** [comment]
I tried by tweaking the authState based on the pathname of the url and it's working. Thanks @Amplifiyer
