### ISSUE TITLE
withAuthenticator(App) doesn't refresh on Auth.signOut()

### ISSUE THREAD

**Issue by evah88** [aws-amplify/amplify-js#4643]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
I'm using the withAuthenticator HOC as a wrapper around my react native app component. The sign in screen shows up correctly on app reload, then routes correctly to the home screen after sign in. However, on calling `Auth.signOut()` the screen doesn't reload, leaving me in a signed out state on a screen that should only be shown to authenticated users.

App.js code:
```
export default withAuthenticator(function App(props) {
  const [isLoadingComplete, setLoadingComplete] = useState(false);

  if (!isLoadingComplete && !props.skipLoadingScreen) {
    return (
      <AppLoading
        startAsync={loadResourcesAsync}
        onError={handleLoadingError}
        onFinish={() => handleFinishLoading(setLoadingComplete)}
      />
    );
  } else {
    return (
      <View style={styles.container}>
        {Platform.OS === 'ios' && <StatusBar barStyle="default" />}
        <AppNavigator />
      </View>
    );
  }
})
```

Code that calls `Auth.signOut()`:
```
...
        <Icon
          name="menu"
          onPress={() => {
            Auth.signOut();
          }}
        />
...
```

**Comment by jordanranz** [comment]
In the current state of the React Native `withAuthenticator`, calling `Auth.signOut();` on a custom UI element does not hook into the `authState` of the Authenticator component wrapping your app. If you would like to use a built in method you can set `includeGreetings: true`:
```
export default withAuthenticator(function App(props) {
  const [isLoadingComplete, setLoadingComplete] = useState(false);

  if (!isLoadingComplete && !props.skipLoadingScreen) {
    return (
      <AppLoading
        startAsync={loadResourcesAsync}
        onError={handleLoadingError}
        onFinish={() => handleFinishLoading(setLoadingComplete)}
      />
    );
  } else {
    return (
      <View style={styles.container}>
        {Platform.OS === 'ios' && <StatusBar barStyle="default" />}
        <AppNavigator />
      </View>
    );
  }
}, { includeGreetings: true } )
```
Scroll down in [these docs](https://aws-amplify.github.io/docs/js/authentication#using-auth-components-in-react--react-native) for my detail.

If you would like to use your own UI, you can either customize the Greetings component in the withAuthenticator HOC or manually refresh the app after awaiting `Auth.signOut`

**Comment by evah88** [comment]
Thanks. I ended up creating a custom navigator that passes the `onStateChange` hook down to the sign out button. Then the button invokes the hook with the `SignOut` state. For reference including my code for the navigator and the invocation of `onStateChange` here:
Custom navigator:
```
import MainTabNavigator from './MainTabNavigator';

class CustomReactNavigationNavigator extends React.Component {
  static router = MainTabNavigator.router

  state = {}

  componentDidMount = () => {
    const { navigation } = this.props

    navigation.addListener('didFocus', this.incrementTimesTabbed)
  }


  render() {
    const { navigation } = this.props

    return (
      <MainTabNavigator
        navigation={navigation}
        screenProps={{
          authState: this.props.authState, 
          onStateChange: this.props.onStateChange
        }}
      />
    )
  }
}

export default createAppContainer(CustomReactNavigationNavigator)
```

Then invoke the `onStateChange` hook like this:
```
const signOutFunc = async props => {
  await Auth.signOut()
    .then(data => {
      console.log("signed out...");
      props.screenProps.onStateChange("signedOut", null);
    })
    .catch(e => console.log("error: ", e));

  return <View style={styles.container}></View>;
};

export default function SignOut(props) {
    signOutFunc(props);
    return (
        <View>

        <ScrollView>

        </ScrollView>
      </View>
    );
}
```

**Comment by GantMan** [comment]
I just ran into this issue as well.   Is there any update on how to get withAuthenticator to log out?

**Comment by Stvad** [comment]
Is there still no better way? It seems like a bug that signOut does not trigger state refresh =\

**Comment by Stvad** [comment]
Ok, found a better way by looking at `AmplifySignOut` component implementation. It does the following 

```javascript
    Hub.dispatch('UI Auth', {
      event: 'AuthStateChange',
      message: AuthState.SignedOut,
    });
```

From https://github.com/aws-amplify/amplify-js/blob/df95ea3724eb6406f64b03f25086cd3e8644cb5f/packages/amplify-ui-components/src/components/amplify-sign-out/amplify-sign-out.tsx and https://github.com/aws-amplify/amplify-js/blob/df95ea3724eb6406f64b03f25086cd3e8644cb5f/packages/amplify-ui-components/src/common/helpers.ts#L34

**Comment by jakubknejzlik** [comment]
@Stvad thanks for Your hint, just small note regarding the `AuthState.SignedOut` as I've not been able to import it. So this was the final hacky solution (basically replacing the AuthState.SignedOut with string 'signedout'):

```
import { Hub } from "@aws-amplify/core";

Hub.dispatch("UI Auth", {
  event: "AuthStateChange",
  message: "signedout",
});
```

Also I'm really confused why this issue is closed as there is no proper solution to this one. And refreshing page or using hardcoded string for dispatching internal events does not feel very satisfying :-/

**Comment by cat-turner** [comment]
this works for me:
https://gist.github.com/dabit3/6c4f0a06b5e39fd53567a4a521143efa
