### ISSUE TITLE
DataStore | Not working with NextJS or Gatsby

### ISSUE THREAD

**Issue by giovas94** [aws-amplify/amplify-js#4644]
We are trying to use Datastore with NextJS & Gatsby. It works without error but never sync the data to the cloud only works with the local IndexedBD (offline).

**Comment by giovas94** [comment]
Is not a problem with SSR. The issue is that datastore not retrieves warnings or errors of the cloud sync. And the problem that we had is that we add  a "**createdAt**" field to our models but like **AWSTimestamp** and the generated resolver adds createdAt and updatedAt by default but as **AWSDateTime**. Thats the problem a missmatch with the types but Datastore does not return any warning or error just not sync the data.

**Comment by HerrBertling** [comment]
I've got the same issue with a Vue app. I initially generated the API before the DataStore was published. Now I added it (which works seamlessly until syncing 😄:+1: ) and the local IndexedDB is written. Syncing does not happen, though.

This has nothing to do with SSR in my case, as far as I can see.

**Comment by elorzafe** [comment]
@giovas94 thanks for pointing this, we are going to dive deep into this.

**Comment by ashika01** [comment]
@giovas94 : How does your setup for Datastore look like? I just created a sample nextJS app and implemented Datastore in it. Since Datastore uses indexedDB for offline storage, I used [noSSR](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr) to set it up. And once that is set, I was able to use Datastore as usual completely synced with cloud.

Could you provide more details or sample of your repo?

**Comment by m5r** [comment]
> @giovas94 : How does your setup for Datastore look like? I just created a sample nextJS app and implemented Datastore in it. Since Datastore uses indexedDB for offline storage, I used [noSSR](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr) to set it up. And once that is set, I was able to use Datastore as usual completely synced with cloud.
> 
> Could you provide more details or sample? So I can help you unblock.

Amplify is all about enhancing the developer experience to let the developers focus on business requirements & deliver apps with great user experience and having to forego SSR, one of the key features to deliver better user experience, to use DataStore is kind of off putting.
