### ISSUE TITLE
How to add Auth for a custom API backend?

### ISSUE THREAD

**Issue by namgk** [aws-amplify/amplify-js#4648]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
I'm running an EC2 instance that hosts my REST API, how can I use Amplify with Cognito to add an authentication gate in front of this API server of my own?

**Comment by Amplifiyer** [comment]
Hi @namgk, were you able to follow https://aws-amplify.github.io/docs/js/api#manual-setup for a manual setting up your own custom API? How are you protecting your custom API?

The API gateway used by the automated setup in Amplify CLI is protected with cognito user pools and you can specify whether just authenticated or unauthenticated users as well should have permissions and for which APIs.

**Comment by namgk** [comment]
What I'm looking at is to have my api behind an ELB, the ELB is authed with cognito, therefore I don't need to build auth into my api anymore.

I can achieve this on the web basis (e.g. with an api-powered web app behind ELB): User go to my web app, ELB intercept and ask for login, user login with Cognito and ELB let them through. All subsequent requests to my server are automatically authed with ELB (via cookie I supposed?).

Can this be achieved on a mobile app instead?

Thanks

**Comment by Amplifiyer** [comment]
Amplify is not integrated with ELB out of the box, if you have configured ELB to work with Cognito and you have custom API end points configured, then you can take one of the following options.

* Provide `Authorization` header which ELB/Your API will use for authentication and in this case Amplify will completely [skip signing your request](https://github.com/aws-amplify/amplify-js/blob/master/packages/api/src/RestClient.ts#L133-L144) and you will be responsible for authentication. 
* If you are using Amplify with cognito and want your requests signed with those credentials, then you can skip adding authorization header and Amplify will [sign your request](https://github.com/aws-amplify/amplify-js/blob/master/packages/api/src/RestClient.ts#L146-L153) with the cognito credentials

**Comment by namgk** [comment]
Thanks Praveen,

    "want your requests signed with those credentials"

This is the part that I don't know how to do. Because with custom API, what
I'm having is a simple plain Javascript fetch.

**Comment by namgk** [comment]
Further if I want to put in an Authorization header to make ELB happy, what's its content?

Thanks

**Comment by Amplifiyer** [comment]
> This is the part that I don't know how to do. Because with custom API, what I'm having is a simple plain Javascript fetch.

You'll be using API.get() in this case and Amplify will pick up the (cognito) credentials and sign your request with them. To configure amplify with your custom API, check my previous link https://aws-amplify.github.io/docs/js/api#manual-setup

**Comment by Amplifiyer** [comment]
> Further if I want to put in an Authorization header to make ELB happy, what's its content?
> 
> Thanks

In that case, it will be completely driven by your Auth implementation and Amplify will not interfere and will behave simply as an http client (using axios as provider)

**Comment by namgk** [comment]
For API.get(), would ELB be able to authenticate such signed request with
the Cognito user?

**Comment by Amplifiyer** [comment]
That's something you'll have to try and verify. Amplify only supports API gateway out of the box with cognito authorization. 

But I can't see why you shouldn't be able to do that. You may have to configure IAM roles in ELB

**Comment by namgk** [comment]
Thank you very much Praveen, that's the main purpose of this issue, I
wanted to make sure it works that way before implementing.

I'll test it myself then.
