### ISSUE TITLE
How to link aws-amplify-react-native

### ISSUE THREAD

**Issue by code-matt** [aws-amplify/amplify-js#4653]
** Which Category is your question related to? **
React Native

** Provide additional details e.g. code snippets **
```
npm install aws-amplify aws-amplify-react-native --save
cd ios
pod install
```

There is no podspec file in aws-amplify-react-native. How is it ever supposed to autolink in a 0.60+ project ?

**Comment by Amplifiyer** [comment]
@code-matt What errors are you getting while trying to use `aws-amplify-react-native` package in your RN app?

**Comment by code-matt** [comment]
None yet. The instruction here mention for a 0.60+ project to use autolinking. https://aws-amplify.github.io/docs/js/start?platform=react-native

For that to work there needs to be a podspec file somewhere within the package for react-native to scan and recognize it as a native module to link. I am not seeing that for either package above and wanted to make sure there was not something missed in the instructions. In fact, I do not even see xcodeproj or xcworkspace in either of those packages.

**Comment by code-matt** [comment]
Sorry I see now these core ones do not link, closing !
