### ISSUE TITLE
How to pass variables to graphqlOperation query in aws-amplify

### ISSUE THREAD

**Issue by groundswel** [aws-amplify/amplify-js#4654]
Hi,

It would be great to have some examples on how to create a graphql query and pass a variable to it . For example I am trying to find books by certain user and the username is passed to the corresponding function as parameter selected at runtime:

```
import Amplify, { API, graphqlOperation } from 'aws-amplify';

getbooksbyUser('John')

async function getbooksbyUser(user_name) {
const getbooksforuser = `query getbooksforuser($user: String) {
           BooksBorrowed(username: $user){
                        Book
          }
}

const booklist = await API.graphql(graphqlOperation(getbooksforuser))
console.log(booklist)
}
```

But I keep getting various errors including "Validation error of type FieldUndefined: BooksBorrowed". An example would be great if someone can provide it.

**Comment by groundswel** [comment]
I see https://aws-amplify.github.io/amplify-js/api/globals.html#graphqloperation .. But I wonder for above example what would be the correct way to pass the variable?

**Comment by groundswel** [comment]
Ok so to pass variables you have to 1) Define the query itself in schema.graphql file and 2) pass the variables in the form of a JS object ie graphqlOperation(getbooksforuser,{username:user}) .. BUT that is only the beginning .. for me it returns null and I am suspecting now I have to create a custom resolver .... In the risk of sounding frustrated  I wonder if all the complexity is really worth it specially when the documentation is helpful only to a bare minimum point and something simple like writing a custom query to fetch the data is a solved problem in many other ways. It would be great if the AWS amplify team can spend some time simplifying writing custom graphql queries , which I suspect is a must for all real world applications.

**Comment by dantasfiles** [comment]
For custom queries, a lot of people use lambda functions as they're easier than custom resolvers. There's a good discussion here:
https://github.com/aws-amplify/amplify-cli/issues/3221

**Comment by undefobj** [comment]
@groundswel The best place to start is with the autogenerated schemas by the GraphQL Transformer which you can see in the Getting Started guide: https://aws-amplify.github.io/docs/js/start?platform=purejs

That guide shows custom variables using mutations, but as you note queries are similar. Additionally you could also look at DataStore which handles all this behind the scenes for you: https://aws-amplify.github.io/docs/js/datastore
