### ISSUE TITLE
amazon-cognito-identity-js Resend Confirmation Email Link

### ISSUE THREAD

**Issue by brycedeneen** [aws-amplify/amplify-js#4655]
I'm in a situation where I have users that don't click the confirmation link within 24 hours, but I'm not able to generate and send them a new verification link. I tried resendConfirmationCode and the result shows the right information (Attribute Name (email), Delivery Medium (email), and destination which is the correct email address) but no email is sent. Thanks for any help!

**Comment by Amplifiyer** [comment]
@brycedeneen Are you trying to use [Amplify Auth category](https://github.com/aws-amplify/amplify-js/blob/510f86ef39bae3fba9a17deb630237a64c9dc7dc/packages/auth/src/Auth.ts#L379-L384) to resent the verification code or directly using the [cognito sdk ](https://github.com/aws-amplify/amplify-js/blob/ac34816df326331cfe04474fdf35790c52f4a1d3/packages/amazon-cognito-identity-js/src/CognitoUser.js#L1280-L1286)? If later, can you try using the Auth category or if you are not using the Auth category then call `createCognitoUser` as per [this](https://github.com/aws-amplify/amplify-js/blob/510f86ef39bae3fba9a17deb630237a64c9dc7dc/packages/auth/src/Auth.ts#L396)

**Comment by brycedeneen** [comment]
Hey @Amplifiyer thanks for the response! I am not using Amplify Auth Category, I'm directly using the cognito SDK. I believe I'm doing exactly what you recommended. Here is my code, could you tell me if I'm doing something incorrectly (also thanks for the response!!!):

`
    resendConfirmationCode(userName: string): Promise<any> {

        return new Promise((resolve, reject) => {

            const cognitoUser = this.getUserByUsername(userName);

            // cognitoUser.resendSignUp((error: any, result: any) => {
            cognitoUser.resendConfirmationCode((error: any, result: any) => {
                if (error) {
                    console.log('error');
                    console.log(error);
                    reject(error);
                } else {
                    console.log('result');
                    console.log(result);
                    resolve(result);
                }
            });

        });
    }
`

and 

`

    private getUserByUsername(userName) {
        const userData = {
            Username: userName.toLowerCase(),
            Pool: this.userPool,
        };

        const cognitoUser = new this.AmazonCognitoIdentity.CognitoUser(userData);
        return cognitoUser;
    }
`

**Comment by Amplifiyer** [comment]
@brycedeneen I believe the issue is with using the existing user instead of creating again with the same username. Some community members also mentioned this on the [stackoverflow](https://stackoverflow.com/questions/53194794/cant-resend-verification-code-through-aws-cognito-api) though I agree it's counter intuitive.

For now try with `const user = this.createCognitoUser(username);` instead of CognitoUser and let us know if it changes anything.

**Comment by brycedeneen** [comment]
@Amplifiyer I looked through the documentation and tried it but there is no createCognitoUser method in the amazon-cognito-identity-js library, could you help me out?

**Comment by haverchuck** [comment]
@brycedeneen The Auth category has a private createCognitoUser method which you can't call directly, but I think you can look at it to see how to use the constructor from amazon-cognito-identity-js (you won't need everything in this function):
```
import { CognitoUser, ICognitoUserData } from 'amazon-cognito-identity-js';
	private createCognitoUser(username: string): CognitoUser {
		const userData: ICognitoUserData = {
			Username: username,
			Pool: this.userPool,
		};
		userData.Storage = this._storage;

		const { authenticationFlowType } = this._config;

		const user = new CognitoUser(userData);
		if (authenticationFlowType) {
			user.setAuthenticationFlowType(authenticationFlowType);
		}
		return user;
	}
```

**Comment by brycedeneen** [comment]
@haverchuck Thanks for the response but my method "getUserByUserName" in a previous response recreates that private method (I didn't need to use the storage or auth flows). 

I just figured out the issue and its strange:

- If I use my above method "getUserByUsername" and use an email (which is a login alias not the actual username) I get a valid CognitoUser object. When I call resendConfirmationCode, it returns the right information, however the link is not sent!
- If I use my above method "getUserByUsername" and use the actual username which is a guid I alsoo get a valid CognitoUser object. When I call resendConfirmationCode it does resend the link!

Is this a bug/intended functinoality?

For now I'll add a second method for getUserByEmail and I have a workaround. Thanks so much for everyones help as well!

**Comment by brycedeneen** [comment]
FYI I may be wrong it seems that it creates a valid object, but the object isn't actually getting the user. I think we can close this issue. Thanks all!
