### ISSUE TITLE
progressCallback only gets executed when the upload is finished

### ISSUE THREAD

**Issue by juuyan** [aws-amplify/amplify-js#4657]
**Describe the bug**
progressCallback only gets executed when the upload is finished

**To Reproduce**
```
const stored = await Storage.put(filename, file, {
    contentType: file.type,
    customPrefix: customPrefix,
    progressCallback(progress) {
      console.log(progress)
    },
  })
```
The log only gets observed once. ( when the uploading is finished )

**Expected behavior**
I expect it to run several times to log the progress of uploading.

**Screenshot**
![image](https://user-images.githubusercontent.com/48427014/71608822-eb51ab00-2bbe-11ea-95e6-b970e604fac5.png)

```
  System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 135.89 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 60.0.1
    Safari: 13.0.3
  npmPackages:
    @fortawesome/fontawesome-svg-core: ^1.2.25 => 1.2.25 
    @fortawesome/free-brands-svg-icons: ^5.11.2 => 5.11.2 
    @fortawesome/free-solid-svg-icons: ^5.11.2 => 5.11.2 
    @fortawesome/react-fontawesome: ^0.1.7 => 0.1.7 
    @zeit/next-css: ^1.0.1 => 1.0.1 
    autoprefixer: ^9.7.0 => 9.7.0 
    aws-amplify: ^2.2.1 => 2.2.1 
    aws-amplify-react: ^3.1.1 => 3.1.1 
    formik: ^2.0.3 => 2.0.3 
    getstream: ^4.3.0 => 4.3.0 
    next: 9.1.1 => 9.1.1 
    prop-types: ^15.7.2 => 15.7.2 
    react: 16.11.0 => 16.11.0 
    react-activity-feed: ^0.9.24 => 0.9.24 
    react-dom: 16.11.0 => 16.11.0 
    tailwindcss: ^1.1.3 => 1.1.3 
    yup: ^0.27.0 => 0.27.0 
  npmGlobalPackages:
    @aws-amplify/cli: 3.13.0
    gatsby-cli: 2.7.47
    live-server: 1.2.1
    npm: 6.11.3
    serverless: 1.51.0
    strapi: 3.0.0-next.11
```

Sample code:
Click a button would trigger the onSubmitHandler, to upload the added file and store the data into db. (fyi I use formik)
```
  const projectFile = useRef(null)

  const createProject = project => {
    return API.post('improve', '/projects', {
      body: project,
    })
  }

  const onSubmitHandler = async (values, actions) => {
    // check the size of the attachment
    if (projectFile.current && projectFile.current.size > 1000000 * 10) {
      alert(`Please pick a file smaller than 10MB.`)
      return
    }

    try {
      const attachment = projectFile.current ? await s3Upload(projectFile.current, state.user.sub) : null
      const project = {
        title: values.title,
        description: values.description,
        tags: values.tags,
        thumbnail: [attachment],
        attachments: [attachment],
      }
      const response = await createProject(project)
      const newProjectPath = `/projects/${response.path}`
      Router.push('/projects/[pid]', newProjectPath)
    } catch (e) {
      alert(e)
      actions.setSubmitting(false)
    }
  }
```

**Comment by Amplifiyer** [comment]
@juuyan I just tried to reproduce this with a 4MB file upload and I am able to get multiple (about 50) progress report callbacks. Have you tried with a different browser? Can you also share your complete sample app code where you can reproduce this?

**Comment by juuyan** [comment]
@Amplifiyer Hey I updated. Thanks~

**Comment by Amplifiyer** [comment]
@juuyan I have tested this in Chrome as well and not able to reproduce with a simple react app. It seems you are running in NextJs environment. Are you running server side or client side? You can also turn on the debug logs for better troubleshooting https://aws-amplify.github.io/docs/js/logger

**Comment by juuyan** [comment]
@Amplifiyer The page is static and prerendered. I have turn on the debug logs but did not find any clues. Do you have any idea about what might lead to such behavior?

**Comment by Amplifiyer** [comment]
@juuyan I again tried with NextJs prerendered pages and I still couldn't reproduce what you are observing. 

Will you be able to host your sample app so I can see that in action? If not, can you provide a minimal app in a repository where you can reproduce it, I will run it locally to reproduce it.

**Comment by juuyan** [comment]
@Amplifiyer thanks. I will try to make one sample repo this weekend.

**Comment by juuyan** [comment]
@Amplifiyer Thanks. I've solved it. The reason is bit silly...: the file is too small (1mb).. I got more updates when uploading bigger files...
