### ISSUE TITLE
Passing clientMetadata to Lambda trigger when using federatedSignIn

### ISSUE THREAD

**Issue by HMilbradt** [aws-amplify/amplify-js#4662]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **

We currently do something like the following for registration:

```
        await Auth.signUp({
          username: this.email,
          password: this.password,
          attributes: {
            given_name: this.firstname,
            family_name: this.lastname
          },
          clientMetadata: {
            key: value
          }
        })
```

We use the clientMetadata in our trigger to do some extra processing.  However, now we'd like to use social providers and I cannot find how to pass this in when using the `federatedSignIn` methods.

I looked at using customState, but I cannot seem to find any documentation on this.

Is it possible to use clientMetadata alongside Auth.federatedSignIn?

**Comment by Amplifiyer** [comment]
@HMilbradt customState is different and is not sent to Cognito. I'm not sure if it's possible to send the clientMetadata to Cognito Service with `federatedSignIn` 

* If you are using cognito user pool federation, then the sign in happens in the hostedUI after being redirected from the federated providers and not in the client library.
* If you are using identity pool federation, then there is no concept of triggers at all there.

**Comment by HMilbradt** [comment]
We are using user pool federation, but I suppose we'll need to rethink how to handle this case.  Thanks for the quick reply!

**Comment by JacksonGariety** [comment]
@HMilbradt how did you end up doing this?

**Comment by HMilbradt** [comment]
@JacksonGariety We ended up reworking how we handled our signin to remove the need for `clientMetadata`, and now do all the fetching/processing in a lambda trigger during signup.

**Comment by dentonmwood** [comment]
@HMilbradt did you all consider any other alternatives that might help? We're trying to pass client metadata to do impersonation since Cognito doesn't support it for the hosted UI.

**Comment by theogravity** [comment]
We have to do this awful hack where we use `Auth.updateUserAttributes` to add in the custom attribute to the JWT, but this is called on the page we are loading.

This kind of issue makes me urge people to use an alternative provider such as Auth0 instead.

**Comment by jay3dec** [comment]
Did any one find any way to pass data to `federatedSignIn`. I need to put some validation check before social sign in based on passed in data. Any help would be appreciated. thanks

**Comment by LuisSaybe** [comment]
Commenting here to see if anyone found out a way to do this, it's a bit annoying not being able to pass clientMetadata in both the federated and non-federated cases.

**Comment by theogravity** [comment]
Unfortunately no. I really recommend against using Cognito at all, this will be the first of many issues and features that are lacking you'll discover with it.

I personally recommend FusionAuth as it has solved all our use-cases without hacks like with Cognito and the SDK isn't a monster to work with either.

Also this issue has been opened for around three years here and it's clear they don't care.

**Comment by iyobo** [comment]
> clientMetadata

You can pass clientMetadata in non-federated signIn only and it will show up in the payload sent to your user pool hooks e.g preTokenGeneration hook.

It is, so far, not possible to pass anything into the federated signIn method.

**Comment by iyobo** [comment]
> Commenting here to see if anyone found out a way to do this, it's a bit annoying not being able to pass clientMetadata in both the federated and non-federated cases.

You can pass clientMetadata in non-federated signIn only and it will show up in the payload sent to your user pool hooks e.g preTokenGeneration hook.

It is, so far, not possible to pass anything into the federated signIn method.

**Comment by your-diary** [comment]
Related:

- #5522
