### ISSUE TITLE
Angular 8 and onCreate subscriptions

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-js#4664]
I have the most recent Angular and amplify and have been trying to get subscriptions set up for realtime booking streams, however I cannot get the subscription to poroduce the data when I create a new booking item. 

I have tried the standard RXJS subscriber:

```
      this.amplify.api().graphql(graphqlOperation(onCreateBooking))
        .subscribe(data => console.log(data)
```

And the zen obvservabkle approach:

```
      this.amplify.api().graphql(graphqlOperation(onCreateBooking))
        .subscribe({ next: (eventData) => console.log(eventData)})
```

Both never produce a console log when I create a new booking.

The booking has the owner set to the ID of the currently logged into user.

The subscription TS file generated by amplify contains the subscription query:

```
export const onCreateBooking = `subscription OnCreateBooking {
  onCreateBooking {
    id
    userName
    userId
    publisher
    entityId
    entityTitle
    dateTime
    dateTimestamp
    people
    notes
    status
    ttl
    createdAt
    updatedAt
  }
}
`;
```

and the graphql file:

```
type Booking @model
@key(name: "bookingsByEntity", fields: ["entityId", "createdAt"], queryField: "listBookingsForEntity") 
@key(name: "bookingByBookDate", fields: ["entityId", "dateTimestamp"], queryField: "listBookingByBookDate") 
@key(name: "userBookings", fields: ["userId", "dateTimestamp"], queryField: "listUserBookings")  {
  id: ID!
  userName: String!
  userId: String!
  publisher: String
  entityId: String!
  entityTitle: String
  dateTime: AWSDateTime!
  dateTimestamp: Float!
  people: Int!
  notes: String
  status: String!
  ttl: Float
  createdAt: Float!
  updatedAt: Float!
}
```

**Comment by oliverandersencox** [comment]
someone on the Amplify team must be able to shed some light here!?

**Comment by amhinson** [comment]
@oliverandersencox Sorry for the delay! Were you able to solve your issue?

**Comment by oliverandersencox** [comment]
@amhinson nope! Gave up in the end

**Comment by amhinson** [comment]
Ok. I will close this issue for now, but if you happen to come across it again, feel free to open it back up!

**Comment by michaelvobejda** [comment]
I'm coming across this issue -- can you please elaborate on this page? The codegen doesn't work how it's described in the docs here: https://docs.amplify.aws/guides/api-graphql/subscriptions-by-id/q/platform/js

Thanks in advance!
