### ISSUE TITLE
Ask for upgrade NodeJS-aws-amplify version inside of Amazon

### ISSUE THREAD

**Issue by rjjlucy** [aws-amplify/amplify-js#4665]
I am sorry that this question seems not very appropriate to ask here. But I found Amplify team paid much more attention in this Github issues than other contact ways.

 Our team needs to consume the latest version of Amplify but our package is not npmpm which cannot directly import the external third-party-library directly. Currently we still use the NodeJS-aws-amplify=1.1.40. Could you help upgrade the NodeJS-aws-amplify version to the latest 2.2.1 inside Amazon GitFarm so we can consume it?

Ping me directly renjingy@ if you need more info.

**Comment by Amplifiyer** [comment]
Talked offline and directed OP to the right contact.
