### ISSUE TITLE
Auth.currentUserCredentials() delivers new user credentials on each call

### ISSUE THREAD

**Issue by vtbs** [aws-amplify/amplify-js#4672]
**Describe the bug**
After successful user login with Cognito user pools, Auth.currentUserCredentials() (and also Auth.currentCredentials()) deliver new user credentials on each call when using Cognito Federate Identities. This means, for each call of these functions, a different secretKey and accessKey are outputted. Also the expiration date of the new credentials is updated, meaning for each call, new credentials with a new expiration date is generated.

**To Reproduce**
1. Sign in with Auth.signIn("username", "password"); with a Cognito User pool and Cognito Federate Identity Pool set in the configuration (e.g. by click on a button login).
2. Successful login: User info, accessToken, idToken, etc. are available.
3. Call Auth.currentUserCredentials() e.g. by button click and output the result.
4. secretKey, accessKey, expiration date, sessionToken are different on each call of Auth.currentUserCredentials().

**Expected behavior**
Auth.currentUserCredentials() should not deliver new credentials after the first invocation as long as the first credentials are valid. This means, after the first call of Auth.currentUserCredentials(), the credentials should be stored and Auth.currentUserCredentials() should output the stored credentials as long as they are valid. Only after expiration, new credentials should be provided.

**Additional context**
Observed with Amplify 4.9.0, JavaScript API

**Comment by Amplifiyer** [comment]
@vtbs, can you try with `Auth.currentCredentials` instead of `Auth.currentUserCredentials` which seems to be refreshing the credentials on every call.
