### ISSUE TITLE
Cognito user registration validation errors - add specific codes per error or modify the message

### ISSUE THREAD

**Issue by ashleywnj** [aws-amplify/amplify-js#468]
Feature Request for Amazon Cognito user registration validation errors

**Current behaviour:**

The omission of _username, or password_ on sign-up form provides an end user readable error based on the following: 

`signUp() {
  Auth.signUp({
    username: this.state.username,
    password: this.state.password,
    email: this.state.email
  })
    .then(() => this.setModalVisible(true))
    .catch(err => {
          console.log("this is an example: ", err);
    });
}`

This is easy to read and pass into the application - **however** if the password or email fields have data, but not in a format that meets the requirements, the messages are passed back as an object with three key, value pairs: "code", "message" & "name". With the current object and values, it is not possible to identify the issue easily or pass the message to the end user.

<img width="830" alt="screen shot 2018-03-17 at 10 13 40 am" src="https://user-images.githubusercontent.com/4009903/37556414-f0d2eae0-29cb-11e8-8142-a6832dd1edc0.png">

**Recommendation** use a unique "code" or "name" to capture the specific error type - this will allow identifying the specific issue and passing a custom message - alternatively, develop a message that can be passed directly to the end user.

**Comment by sammartinez** [comment]
Resolving as #3897 adds messaging for this.

**Comment by Jay2113** [comment]
Feature request:
The objective is to customize the validation error messages in Cognito. I have built a custom UI and I am using an Amplify UI component which uses the Amplify auth category to display the message. Following the above described request, it looks like the mapping of an error code to their custom message does exist in the Amplify Auth category. However, at this point in time the mapping is not customizable for a customer.

The use case would be to provide simplified error messages to the end user during the authentication process. Internationalization of the error messages would also be unblocked if the mapping is exposed.

Please consider the above mentioned request. Thank you!
