### ISSUE TITLE
Auth hosted UI create user button is permanently disabled

### ISSUE THREAD

**Issue by dbroadhurst** [aws-amplify/amplify-js#4680]
Using the standard browser react auth example the create user button becomes disabled when the phone number is missing. The create button becomes permanently disabled.

Create a standard react auth app and create a user with the hosted UI

**Comment by sammartinez** [comment]
@dbroadhurst Can you provide the link to the documentation you are calling out? This is by default that we do use CSS in order to disable the button until all form fields are filled in.
