### ISSUE TITLE
after update aws-amplify "Object prototype may only be an Object or null: undefined" issue

### ISSUE THREAD

**Issue by ulpsilva** [aws-amplify/amplify-js#4687]
i update my react project aws-amplify to version 2.2.1 from version 0.3.4 and after i am getting this error
![Annotation 2020-01-09 104414](https://user-images.githubusercontent.com/6129644/72039982-0d3ce300-32cd-11ea-93f7-9358c5411b9c.png)

**Comment by iartemiev** [comment]
Hi @ulpsilva, please provide a code sample of how you're using Amplify, as well as your config (aws-exports.js file with any sensitive information removed)

**Comment by kaybee99** [comment]
I'm facing the same issue.

Managed to get it working by only importing the modules I needed. I'm using Vue, but I've basically done [this](https://stackoverflow.com/questions/53925177/aws-amplify-modular-imports-with-vue)

**Comment by ulpsilva** [comment]
> Hi @ulpsilva, please provide a code sample of how you're using Amplify, as well as your config (aws-exports.js file with any sensitive information removed)

this is my aws-export.js
`const awsExports = {
  Auth: {
    // REQUIRED - Amazon Cognito Identity Pool ID
    identityPoolId: config.identityPoolId,
    // REQUIRED - Amazon Cognito Region
    region: config.region,
    // OPTIONAL - Amazon Cognito User Pool ID
    userPoolId: config.userPoolId,
    // OPTIONAL - Amazon Cognito Web Client ID
    userPoolWebClientId: config.userPoolWebClientId,
  },
  API: {
    endpoints: [
      {
        name: 'ConsultantApi',
        endpoint: config.ConsultantApi,

        service: 'lambda',
        region: config.region,
      },
    ],
  },
  Storage: {
    bucket: config.bucket, // REQUIRED -  Amazon S3 bucket
    region: config.region, // OPTIONAL -  Amazon service region
    identityPoolId: 'xxxxxxxxxxxx',
    level: 'public',
  },
};
export default awsExports;`

this is how i am using it
`import React, { Component } from 'react';
import { Col } from 'reactstrap';
import { Redirect } from 'react-router-dom';
import Amplify from '@aws-amplify/core';
import { withAuthenticator, VerifyContact, RequireNewPassword } from 'aws-amplify-react';

// aws cognito configuration
import awsExports from '../../../../aws_exports';

// Custom Sign Up Ui
import CustomSignIn from '../../../containers/AuthenticationFormContainer/CustomSignInContainer';
import CustomSignUp from '../../../components/AutheticationForm/CustomSignUp';
import CustomConfirmSignUp from '../../../components/AutheticationForm/CustomConfirmSignUp';
import CustomForgetPassword from '../../../components/AutheticationForm/CustomForgetPassword';

Amplify.configure(awsExports);

class Login extends Component {
  constructor() {
    super();
    this._validAuthStates = ['signUp'];
  }
  render() {
    return (
      <Col>
        <Redirect to="/dashboard" />
      </Col>
    );
  }
}
export default withAuthenticator(Login, false, [
  <CustomSignIn />,
  <CustomSignUp />,
  <CustomConfirmSignUp />,
  <CustomForgetPassword />,
  <VerifyContact />,
  <RequireNewPassword />,
]);
`

**Comment by ulpsilva** [comment]
> Hi @ulpsilva, please provide a code sample of how you're using Amplify, as well as your config (aws-exports.js file with any sensitive information removed)

**this is my aws-export.js**

```javascript
import { config } from './config/config';

const awsExports = {
  Auth: {
    // REQUIRED - Amazon Cognito Identity Pool ID
    identityPoolId: config.identityPoolId,
    // REQUIRED - Amazon Cognito Region
    region: config.region,
    // OPTIONAL - Amazon Cognito User Pool ID
    userPoolId: config.userPoolId,
    // OPTIONAL - Amazon Cognito Web Client ID
    userPoolWebClientId: config.userPoolWebClientId,
  },
  API: {
    endpoints: [
      {
        name: 'ConsultantApi',
        endpoint: config.ConsultantApi,

        service: 'lambda',
        region: config.region,
      },
      {
        name: 'UserApi',
        endpoint: config.UserApi,
        service: 'lambda',
        region: config.region,
      },
    ],
  },
  Storage: {
    bucket: config.bucket, // REQUIRED -  Amazon S3 bucket
    region: config.region, // OPTIONAL -  Amazon service region
    identityPoolId: 'xxxxxxx',
    level: 'public',
  },
};
export default awsExports;

```

**this is how I am using it**
```javascript
import React, { Component } from 'react';
import { Col } from 'reactstrap';
import { Redirect } from 'react-router-dom';
import Amplify from '@aws-amplify/core';
import { withAuthenticator, VerifyContact, RequireNewPassword } from 'aws-amplify-react';

// aws cognito configuration
import awsExports from '../../../../aws_exports';

// Custom Sign Up Ui
import CustomSignIn from '../../../containers/AuthenticationFormContainer/CustomSignInContainer';
import CustomSignUp from '../../../components/AutheticationForm/CustomSignUp';
import CustomConfirmSignUp from '../../../components/AutheticationForm/CustomConfirmSignUp';
import CustomForgetPassword from '../../../components/AutheticationForm/CustomForgetPassword';

Amplify.configure(awsExports);

class Login extends Component {
  constructor() {
    super();
    this._validAuthStates = ['signUp'];
  }
  render() {
    return (
      <Col>
        <Redirect to="/dashboard" />
      </Col>
    );
  }
}
export default withAuthenticator(Login, false, [
  <CustomSignIn />,
  <CustomSignUp />,
  <CustomConfirmSignUp />,
  <CustomForgetPassword />,
  <VerifyContact />,
  <RequireNewPassword />,
]);

```

**Comment by ulpsilva** [comment]
> I'm facing the same issue.
> 
> Managed to get it working by only importing the modules I needed. I'm using Vue, but I've basically done [this](https://stackoverflow.com/a/53948673/2216929)

I did this. didn't work for me

**Comment by prabhatsharma** [comment]
Still facing this.

**Comment by ulpsilva** [comment]
"node_modules\@aws-amplify\analytics\lib-esm\Providers\AWSKinesisFirehoseProvider.js" remove the "()" in line number 25

**Comment by prabhatsharma** [comment]
I was using vue. Created a new vue project and ported the code manually. This seems to have fixed the error.
