### ISSUE TITLE
Amplify with Apple Sign in using Expo: NotAuthorizedException: Invalid login token. Issuer doesn't match providerName

### ISSUE THREAD

**Issue by rmaroun** [aws-amplify/amplify-js#4689]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito, AWS Amplify
** Provide additional details e.g. code snippets **
Hi I am trying to use Amplify SignInWithApple together with Expo SDK v36 for my react-native app and I am getting 

> NotAuthorizedException: Invalid login token. Issuer doesn't match providerName

 when trying to authenticate.

I am currently using Amplify  "aws-amplify": "2.2.0", "aws-amplify-react-native": "2.2.3" and "expo": "36.0.0", "expo-apple-authentication": "2.0.0".

this is the code I am using to authenticate wit expo apple authentication then pass it to amplify to avoid using the Hosted UI as the user experience is not that good with the Hosted UI.

```
              async () => {
                try {
                  const result = await AppleAuthentication.signInAsync({
                    requestedScopes: [
                      AppleAuthentication.AppleAuthenticationScope.FULL_NAME,
                      AppleAuthentication.AppleAuthenticationScope.EMAIL
                    ]
                  });
                  const { exp } = jwt_decode(result.identityToken);
                  try {
                    await Auth.federatedSignIn(
                      "SignInWithApple",
                      {
                        token: result.identityToken,
                        expires_at: exp * 1000 + new Date().getTime()
                      },
                      {
                        name: `${result.fullName.givenName} ${result.fullName.familyName}`,
                        firstName: result.fullName.givenName,
                        lastName: result.fullName.familyName,
                        email: result.email
                      }
                    );
                    this.props.navigation.navigate("Home");
                  } catch (e) {
                    console.log("Amplify apple login error => ", e);
                  }
                  // signed in
                } catch (e) {
                  if (e.code === "ERR_CANCELED") {
                    // handle that the user canceled the sign-in flow
                    console.log("user canceled apple sign in => ", e);
                  } else {
                    // handle other errors
                    console.log("error during sign in with Apple via expo => ", e);
                  }
                }
              }
```
The Expo auth with Apple works perfectly and returns the identityToken that is then passed to Amplify.
I have configured Apple provider in User pool but still getting the error message. Can someone help?

**Comment by rmaroun** [comment]
@dabit3 any idea how to solve this? thanks

**Comment by chetankumar01** [comment]
@rmaroun, did you figure this out?

**Comment by rmaroun** [comment]
@chetankumar01 nope, do you have any idea  why is this happening?

**Comment by chetankumar01** [comment]
@rmaroun @iartemiev could this issue occur because the app id is different than the service id created for cognito during setup?

**Comment by alisherakb** [comment]
@rmaroun I'm facing the same amplify issue on react-native-cli project. Did you manage to solve it?

**Comment by rmaroun** [comment]
> @rmaroun @iartemiev could this issue occur because the app id is different than the service id created for cognito during setup?

Yes this was the issue the client Ids were not matching.

**Comment by alisherakb** [comment]
> > @rmaroun @iartemiev could this issue occur because the app id is different than the service id created for cognito during setup?
> 
> Yes this was the issue the client Ids were not matching.

What did solve your issue? I'm stuck.

**Comment by warrioru** [comment]
@rmaroun Could you please explain how you solved it? which ids did not match?

**Comment by rmaroun** [comment]
The client Id in the Amplify config file on my react native client was not matching the client id in cognito therefore the error. @warrioru and @alisherakb does this help?

**Comment by JayMehta97** [comment]
@rmaroun 
My Amplify config file properties match the Cognito dashboard and I have implemented the same code as yours but I still get this error. Did you make any other changes to code or configuration?

Thanks

**Comment by edvinasbartkus** [comment]
I am hitting the same issue. @rmaroun any chance you would be able to share more details how did you get it working? 

Anyone has seen working example of custom federated Sign In with Apple?

**Comment by jordmax12** [comment]
We seem to be having this SAME issue. Not sure why this is closed lol.

https://stackoverflow.com/questions/62054475/amplify-federated-saml-sign-in-not-authenticated

I documented my issues here. Can this get looked into?

**Comment by Yallan** [comment]
I have the same issue.  My client_id match both side. 
It's work with **appleid.apple.com** instead of **SignInWithApple** but I would like to have Apple user in User Pool instead of Identity Pool, is it possible ?

**Comment by dmgallardo** [comment]
Hi anyone can share their insights about this issue, we are having the same problem.
Which is the correct code configuration in order to make it work.

We are using this one and having the same issue:

`              async () => {
                try {
                  const result = await AppleAuthentication.signInAsync({
                    requestedScopes: [
                      AppleAuthentication.AppleAuthenticationScope.FULL_NAME,
                      AppleAuthentication.AppleAuthenticationScope.EMAIL
                    ]
                  });
                  const { exp } = jwt_decode(result.identityToken);
                  try {
                    await Auth.federatedSignIn(
                      "SignInWithApple",
                      {
                        token: result.identityToken,
                        expires_at: exp * 1000 + new Date().getTime()
                      },
                      {
                        name: `${result.fullName.givenName} ${result.fullName.familyName}`,
                        firstName: result.fullName.givenName,
                        lastName: result.fullName.familyName,
                        email: result.email
                      }
                    );
                    this.props.navigation.navigate("Home");
                  } catch (e) {
                    console.log("Amplify apple login error => ", e);
                  }
                  // signed in
                } catch (e) {
                  if (e.code === "ERR_CANCELED") {
                    // handle that the user canceled the sign-in flow
                    console.log("user canceled apple sign in => ", e);
                  } else {
                    // handle other errors
                    console.log("error during sign in with Apple via expo => ", e);
                  }
                }
              }`


But we are not sure, if is a problem with the name of the provider **SignInWithApple** or **appleid.apple.com**, or a misconfiguration on AWS Cognito side.

We have all the client id and configurations right.

**Comment by kevinpiske** [comment]
Same problem as @dmgallardo

**Comment by dovelive** [comment]
@kevinpiske 
Are there anybody that have implemented the apple login on amplify-auth?

**Comment by leaky** [comment]
This is still very much an issue, this should not be closed.

**Comment by mawais78** [comment]
> appleid.apple.com

This worked for me. Thank you

**Comment by iqordev2** [comment]
Is this already solved ? I am also having this issue

**Comment by rapgithub** [comment]
never resolved amplify does not show any documentation for signinWithApple even if it says it is supported! :(

**Comment by rapgithub** [comment]
> I have the same issue. My client_id match both side.
> It's work with **appleid.apple.com** instead of **SignInWithApple** but I would like to have Apple user in User Pool instead of Identity Pool, is it possible ?

can you show your code working without this issue "Invalid login token. Issuer doesn't match providerName" with signinWithApple in my case the everything it setup correctly but still the error shows"

**Comment by DatMoser** [comment]
I have no idea why this issue is closed even though it seems that the problem still persists half a year later. I am currently facing the same issue, and I am wondering if nobody in the world uses Apple Auth with Amplify, or if everybody is just fine with the mediocre user experience offered by the Cognito Hosted UI, or if I just got something very wrong. My current approach is very similar to what @dmgallardo used back then, but when I use "SignInWithApple" as the provider name, I get the same error mentioned above. When switching it to "appleid.apple.com" it returns:

`Error [NotAuthorizedException: Token is not from a supported provider of this identity pool.]`

Even though I have set up Apple Auth correctly and it also works via HostedUI, it is apparently not intended to be called silently like with Google or Facebook APIs. I don't understand why Amplify makes it so ridiculously hard to set up a transparent authentication flow like Firebase.

**Comment by abdallahshaban557** [comment]
@DatMoser  - can you please submit a new Github issue so that we can investigate this further?

**Comment by pjsandwich** [comment]
> Hi everyone, we are facing the same issue, can anyone share their insights about this issue. Which is the correct code configuration in order to make it work.
> 
> We are using this one and having the same issue:
> 
> ```
> async () => {
>                 try {
>                   const result = await AppleAuthentication.signInAsync({
>                     requestedScopes: [
>                       AppleAuthentication.AppleAuthenticationScope.FULL_NAME,
>                       AppleAuthentication.AppleAuthenticationScope.EMAIL
>                     ]
>                   });
>                   const { exp } = jwt_decode(result.identityToken);
>                   try {
>                     await Auth.federatedSignIn(
>                       "SignInWithApple",
>                       {
>                         token: result.identityToken,
>                         expires_at: exp * 1000 + new Date().getTime()
>                       },
>                       {
>                         name: `${result.fullName.givenName} ${result.fullName.familyName}`,
>                         firstName: result.fullName.givenName,
>                         lastName: result.fullName.familyName,
>                         email: result.email
>                       }
>                     );
>                     this.props.navigation.navigate("Home");
>                   } catch (e) {
>                     console.log("Amplify apple login error => ", e);
>                   }
>                   // signed in
>                 } catch (e) {
>                   if (e.code === "ERR_CANCELED") {
>                     // handle that the user canceled the sign-in flow
>                     console.log("user canceled apple sign in => ", e);
>                   } else {
>                     // handle other errors
>                     console.log("error during sign in with Apple via expo => ", e);
>                   }
>                 }
>               }
> ```
> 
> But we are not sure, if is a problem with the name of the provider **SignInWithApple** or **appleid.apple.com**, or a misconfiguration on AWS Cognito side.
> 
> We have all the client id and configurations right.

@dmgallardo I see you're using Expo, is this compatible with [the docs](https://docs.amplify.aws/lib/auth/social/q/platform/react-native/#oauth-and-federation-overview) guide for implementing Apple Sign In?
