### ISSUE TITLE
Allow of Custom Providers For Interactions.

### ISSUE THREAD

**Issue by hookercookerman** [aws-amplify/amplify-js#4690]
_This issue is a Request For Comments (RFC). It is intended to elicit community feedback regarding a proposed change to the library. Please feel free to post comments or questions here._

## Summary

`Interactions Package`

Allow for exporting the abstract provider and the types so pluggable providers can be provided for bots, at present only LexProvider is exported. 

https://github.com/aws-amplify/amplify-js/blob/master/packages/interactions/src/index.ts#L31

this should be 

```typescript
export * from './Providers';
export * from './types';
```

## Motivation

Allow to create custom provider for interactions

## Basic Example

Already given

## Detailed Design

Design is already there, just needs exposing

## Drawbacks

none

## Related Issues

none

## References

none

**Comment by thefat32** [comment]
InteractionsProvider should be exported from `@aws-amplify/interactions`. Got problem with this when implementing Lex 2 Provider. I copy it from source as a workaround.
