### ISSUE TITLE
Wrong country code for Czech Republic in aws-amplify-angular and aws-amplify-vue

### ISSUE THREAD

**Issue by rychtation** [aws-amplify/amplify-js#4693]
In aws-amplify-angular and aws-aplify-vue packages wrong phone country code is defined for Czech Republic. The correct code is '+420', not '+42'. 

Here are links to the respective source files to be fixed:

Angular:
https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-angular/src/assets/countries.ts

Vue:
https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-vue/src/assets/countries.js

**Comment by iartemiev** [comment]
@rychtation thank you for letting us know! The fix has been deployed to @unstable and will be in the next stable release
