### ISSUE TITLE
Auth.forgotPassword() does not throw proper exception if user does not exist

### ISSUE THREAD

**Issue by MihirGosai** [aws-amplify/amplify-js#4699]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito.
** Provide additional details e.g. code snippets **
Using https://www.npmjs.com/package/aws-amplify

```
Auth.forgotPassword("nonexistingemail@domain.com").then((data) => {
     // process if success (it sends success even if email does not exist)
})
.catch((err) => {
      //handle exception
});
```
Is there any way to check if user does not exist?

**Comment by manueliglesias** [comment]
Hi @MihirGosai 

I understand this has implications for the UX, but I think this is intentional in the Cognito Service, it is a best practice to not make that kind of information available as it can be used to attack apps. 

e.g. take a look at the [OWASP Authentication cheat sheet](https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#password-recovery)

> Using any of the authentication mechanisms (login, password reset or password recovery) an application must respond with a generic error message regardless of whether:
> 
> The user ID or password was incorrect.
The account does not exist.
The account is locked or disabled.

I hope this helps in understanding why that information is not available when calling `Auth.forgotPassword`

**Comment by Amplifiyer** [comment]
@MihirGosai, can you share your aws_exports file which is auto-generated by Amplify CLI (please obfuscate any AWS account or other sensitive information)

**Comment by manueliglesias** [comment]
@MihirGosai 

@Amplifiyer and I tried your code on a brand new app and couldn't get the behavior you mention.

And regarding my previous comment, the advice is sound, but please note that Cognito **DOES** return a non-generic message for the scenario you describe and you should be getting an exception when calling `Auth.forgotPassword`:

```json
{
  "__type":"UserNotFoundException",
  "message":"Username/client id combination not found."
}
```

We might need more information, or even better, a [codesandbox](https://codesandbox.io) or similar showing the problem.

**Comment by MihirGosai** [comment]
This is what I get on passing non-existent username and password to Auth.forgot
![image](https://user-images.githubusercontent.com/7599834/72522996-db0b2280-3884-11ea-8876-e686a64ff31b.png)

**Comment by Amplifiyer** [comment]
@MihirGosai, we are not seeing this behavior based on the reproduction steps you mentioned. As Manuel asked, can you provide a very minimal sample repo or a [codesandbox](https://codesandbox.io/) where we can easily reproduce the exact issue you are seeing?

**Comment by joetancy** [comment]
You probably have Prevent User Existence Errors turned to Enabled.
Read more about it here
https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-managing-errors.html

change it to legacy if you want Cognito to throw an error if its not found.

**Comment by vipulJain05** [comment]
![Screenshot from 2020-10-12 12-47-27](https://user-images.githubusercontent.com/47937063/95716518-3a1d8c80-0c89-11eb-88e2-96d543822467.png)
Getting this response even if the email provided to "auth.forgotpassword" is wrong and doesn't exists in my pool.
