### ISSUE TITLE
Registration w/ Formik

### ISSUE THREAD

**Issue by Rafcin** [aws-amplify/amplify-js#4707]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
I'm trying to create a registration form from scratch. Using Formik i've been able to check if users are entering info correctly and so on. The issue I can't figure out is how to check if a user already exists or if the username or password is incorrect when logging in. It would be neat if a function for this existed. I think you could use try catch and return based on errors, i'm not sure.

**Comment by manueliglesias** [comment]
Hi @Rafcin 

> I think you could use try catch and return based on errors, i'm not sure.

Yes, this would be the way to do it, in fact this is the way it is currently implemented in our react helpers/components:

https://github.com/aws-amplify/amplify-js/blob/7154314496360f2dc6614300184cf778bf338b64/packages/aws-amplify-react/src/Auth/SignIn.tsx#L93-L127

I hope this helps
