### ISSUE TITLE
Analytics creates a new AWS Pinpoint endpoint every time the app is run, because it never finds an existing endpoint in the cache

### ISSUE THREAD

**Issue by dantasfiles** [aws-amplify/amplify-js#4711]
**Describe the bug**
I ran into this issue while trying to set up Push Notifications, which rely on the Analytics service.
Analytics creates a new AWS Pinpoint endpoint every time the React Native app is run, because it never finds an existing endpoint in the cache

**To Reproduce**
- Run `npx react-native init EndpointTest`
- Run `amplify init`
- Run `amplify add analytics`
```
Using service: Pinpoint, provided by: awscloudformation
? Provide your pinpoint resource name: endpointtest
Adding analytics would add the Auth category to the project if not already added.
? Apps need authorization to send analytics events. Do you want to allow guests and unauthenticated users to send analytics events? (we recommend you allow this when getting started) Yes
Successfully added auth resource locally.
Successfully added resource endpointtest locally
```
- Run `amplify push`
- Add the following lines to `index.js`
```javascript
import Amplify from 'aws-amplify';
import config from './aws-exports';
Amplify.configure(config);
```
- Add the following lines to `App.js` to print the AWS Pinpoint endpoint
```javascript
  React.useEffect(() => {
    console.log(
      'endpointId',
      Analytics.getPluggable('AWSPinpoint')._config.endpointId,
    );
  }, []);
```
_There may be an easier way to get the AWS Pinpoint endpoint, but I don't know it._

Every time you execute `npx react-native run-android`, a new `endpointId` will be created, instead of using the same one from the cache each time.

**Expected behavior**
[`AWSPinpointProvider.configure`](https://github.com/aws-amplify/amplify-js/blob/master/packages/analytics/src/Providers/AWSPinpointProvider.ts#L114) should call [`AWSPinpointProvider._getEndpointId`](https://github.com/aws-amplify/amplify-js/blob/master/packages/analytics/src/Providers/AWSPinpointProvider.ts#L665).

`AWSPinpointProvider._getEndpointId` should call `Cache.getItem`, using as a key `AWSPinpoint_XXXXXXX` where `XXXX` is the appId. If there's an endpoint already in the cache, use it, otherwise create a new endpoint with `uuid.`

What is happening is that it never finds an endpoint in the cache and always creates a new endpoint with `uuid` each time the app is run.

When I examined the [`Cache`](https://github.com/aws-amplify/amplify-js/tree/master/packages/cache) object, it appears to be an instance of [`BrowserStorageCache`](https://github.com/aws-amplify/amplify-js/blob/master/packages/cache/src/BrowserStorageCache.ts), which I don't believe should happen.
For example, `console.log(Cache.constructor)` prints `[Function BrowserStorageCache]`

A possibility is that it's related to [this closed issue](https://github.com/aws-amplify/amplify-js/issues/4309) 

<details>
  <summary><strong>Environment</strong></summary>

```
  System:
    OS: Windows 10 10.0.18363
    Memory: 1.74 GB / 7.85 GB
  Binaries:
    Node: 13.6.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
    Internet Explorer: 11.0.18362.1
  npmPackages:
    aws-amplify: ^2.2.2 => 2.2.2
    babel-jest: ^24.9.0 => 24.9.0
    eslint: ^6.5.1 => 6.8.0
    jest: ^24.9.0 => 24.9.0
    metro-react-native-babel-preset: ^0.56.0 => 0.56.4
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
    react-test-renderer: 16.9.0 => 16.9.0
```

</details>

**Smartphone:**

- OS: Android
- Version 10

**Comment by iartemiev** [comment]
Hi @dantasfiles, thank you for the detailed repro steps and analysis. As you pointed out the issue appears to be related to the Cache package implementation in RN specifically. I was able to reproduce this in React Native on iOS as well. 

I also tried this on web with React and there the `endpointId` was being retrieved successfully from cache, therefore further supporting this bug being RN-specific.

We'll be working on a bug fix and will update this issue with any developments.
