### ISSUE TITLE
Using Amplify Auth with SAML SSO

### ISSUE THREAD

**Issue by yuvsc** [aws-amplify/amplify-js#4714]
### Question related to
Auth
### Services utilizing
Cognito, Amplify, SSO
### Summary
I have set up an AWS solution from CloudFormation template in https://github.com/awslabs/aws-media-insights-engine
This solution sets up a Cognito User Pool to allow users to authenticate using a username and password. I am trying to enhance this solution to allow users to use SSO to authenticate to the solution.
### Expectation
After I created a new AWS SSO application using Custom SAML to Authenticate, and linked it up to my Cognito User Pool created by the CloudFormation template linked above; I expect to be able to log into the AWS SSO console, click on my application, and have SSO authenticate me to the application.
For some reason, Amplify does not handle the SAML tokens passed by Cognito correctly.

Is there anything I need to do in my solution application to be able to handle this type of authentication?

**Comment by manueliglesias** [comment]
Hi @yuvsc 

Amplify uses Cognito Uer Pools' Hosted UI OAuth flow, this flow uses JWT tokens.

Can you try with [these instructions](https://aws-amplify.github.io/docs/js/authentication#oauth-and-hosted-ui)?
