### ISSUE TITLE
Trigger GraphQl query with federation identity credentials

### ISSUE THREAD

**Issue by tomasyaya** [aws-amplify/amplify-js#4716]
** Which Category is your question related to? **
E.g. Auth, Predictions, Storage, etc.
** What AWS Services are you utilizing? **
E.g. Cognito, AWS AppSync, etc.
** Provide additional details e.g. code snippets **
E.g. Sample code, versions of Amplify you are using

Hi everybody, thank you in advance for you time and patience.

I have a federation sign in in place working correctly with salesforce.

The Auth.currentAuthenticatedUser() returns the expected user.

However when I want to dispatch a GraphQl query such as: API.graphql(graphqlOperation(queries.myquery));

It gives me the error "No current user".

For testing purposes I have try the query logged in with the HOC withAuthenticator and the query works fine.

How can I setup GraphQl to work with the Federated Users (I know they are not a Cognito User)

Thank you!!!

**Comment by dantasfiles** [comment]
Have you tried setting the aws_appsync_authenticationType?
https://aws-amplify.github.io/docs/js/api#using-openid_connect

**Comment by manueliglesias** [comment]
Hi @tomasyaya 

I've seen similar behavior when for some reason you have more than one version of the `@aws-amplify/auth` or `@aws-amplify/core` packages

Can you verify if that's what's happening here?

e.g.
`npm ls | grep @aws-amplify`

or

`yarn list --pattern @aws-amplify`

**Comment by tomasyaya** [comment]
Thank you both of you.
The issue was with the app sync authorization being cognito and not open id.
