### ISSUE TITLE
Aws Amplify Lambda File modification for long running process.

### ISSUE THREAD

**Issue by Neuroforge** [aws-amplify/amplify-js#4718]
** Which Category is your question related to? **
Lambda, Auth and Storage

** What AWS Services are you utilizing? **
Lambda, S3 and GraphQL

** Provide additional details e.g. code snippets **

I am working from 'Serverless React with AWS Amplify - The Complete Guide' from Packt Publishing. It's great and has been an amazing springboard into using Amplify and amplify-react for the first time. So far i can create a GraphQL schema for saving the details of an object that was uploaded to S3. Great start! The guide also shows how to make a lambda that is a node express API service.

The model is created using the GrpahQL schema in the API. Apparently, another auth rule can be added to allow an IAM user to access the stored object.

```
type Project @model @auth(rules: [{ allow: owner, identityField: "sub" }, **{ allow: private, provider: iam }**]) {
  id: ID!
  name: String!
  description: String!
  file1: S3Object
  file2: S3Object
  createdAt: String
}

type S3Object {
  bucket: String!
  region: String!
  key: String!
}
```

In an AWS Lambda i'd like to access this object from the API and then retrieve the 'file1' object from S3 and then modify it, and save it to S3 and update the API as file2. 

Also, this process could be long-running.. what is the best way to handle this scenario.  Is this the correct way to do this? Are there any examples? If it is a long-running process i.e. >5mins, is REST really the best way to do this?

- How to access API objects in the lambda that were stored by the user on the frontend.
- How to download the file from S3 within the lambda. (aws-sdk??)
- Save a modified version of the file back to S3 from the lambda. (aws-sdk??)
- Modification could take some time, so fire and forget lambda.
- Update the API object with details of the new S3 object. (aws-sdk??)
- User can see details of new file details when requesting API objects from the frontend (perhaps from subscription onUpdateProject).

Only the owner and the lambda should be able to access the API object and the S3 object.

Are there any examples of this?

Green - Known
Red - Not sure how to implement it.

![Untitled Diagram (2)](https://user-images.githubusercontent.com/1474186/72402052-f6513180-37a1-11ea-8c6f-14fa20e6bdcc.png)

Alternatively, is it possible to trigger the lamdbda from the api update? Can the creation/update of an api object trigger a lambda?

**Comment by Neuroforge** [comment]
It appears there is some documenatation that appears to have a dynamoDB lambda trigger, and examples of GraphQL here....

https://aws-amplify.github.io/docs/cli-toolchain/quickstart#graphql-from-lambda

**Comment by harrysolovay** [comment]
You'd need to implement much of this behavior using the low-level SDK within your lambda. If your front-end user is authenticated via Amplify, they can make an authenticated request to your endpoint, which can then check whether they have access to the resource, and execute the operations necessary to implement the flow you've described above.

If you believe that the CLI should be able to provision this flow or a generic building block of this flow, please [submit a feature request](https://github.com/aws-amplify/amplify-cli/issues/new?template=feature_request.md).
