### ISSUE TITLE
User can sign in automatically even after signing out from the app and social IdP layer (Google)

### ISSUE THREAD

**Issue by leosoaivan** [aws-amplify/amplify-js#4720]
Currently, I have an app setup with Google login in conjunction with Cognito User Pools, bypassing the Cognito Hosted UI via `Auth.federatedSignIn({ provider: 'Google' })` attached to an `onClick` event on a button.

The sign out functionality simply calls `Auth.signOut()`, which successfully clears localStorage:

<img width="745" alt="Screen Shot 2020-01-15 at 9 50 35 AM" src="https://user-images.githubusercontent.com/13614862/72443618-91371500-377c-11ea-907e-14d1301570f2.png">

The issue I'm finding is that if a user signs out of their Google account, such as by navigating to https://myaccount.google.com/ and signing out manually, they are **still** able to log back into my Amplify app automatically (i.e., without signing in with their email and password).

Clearing cookies doesn't appear to do the trick either, and neither does closing the browser. This is likely not an Amplify issue, to be frank, but any ideas on where I might start debugging this is immensely appreciated.

## Versions
"@aws-amplify/api": "^1.2.2",
"@aws-amplify/auth": "^1.4.2",
"@aws-amplify/core": "^1.2.2",
"aws-amplify": "^1.2.2",
"aws-amplify-react": "2.3.10",

**Comment by manueliglesias** [comment]
Hi @leosoaivan 

This is expected behavior of a federated sign in.

This SO answer might be useful to understand the details:

https://stackoverflow.com/a/12909563/194974

(Specially the `When you logout of your app, you're logging out of your app:` part)

**Comment by leosoaivan** [comment]
@manueliglesias Thanks for the quick reply.

I did come across that SO post after making the issue, so I figured there wouldn't be any user-friendly solution.

My main concern is with security, especially if a user were to access my app on a public computer or walk away. Would revoking all tokens via `Auth.signOut({ global: true })` help with this?

**Comment by leosoaivan** [comment]
@manueliglesias I gave more thought to the issue to better explain what I'm seeing.

Indeed, logging out of Google will not log me out of Cognito. However, after logging out of Google **and** my app, I expect that a federated sign-in process on my app would ask me to re-authenticate against Google's authentication servers, thereby forcing me to manually sign in again. In fact, this is the behavior I'm seeing when using the hosted UI.

Bypassing the hosted UI doesn't do this, and it seems like a bug. I am still able to log back into my app by bypassing the hosted UI, even after signing out everywhere, clearing data/local storage, and closing the browser.

**Comment by leosoaivan** [comment]
Apparently fixed by upgrading `aws-amplify-react` to 3.1.5. 

Logging out of Google accounts now lead to a re-authentication request with Google's servers when attempting to sign in with a Google account from my app.

**Comment by leosoaivan** [comment]
Re-opening, because I'm still seeing the issue described in my 1/22/2020 comment https://github.com/aws-amplify/amplify-js/issues/4720#issuecomment-577464777.

**Comment by xai1983kbu** [comment]
@leosoaivan check out my comment [here](https://github.com/aws-amplify/amplify-js/issues/3933) please.

**Comment by leosoaivan** [comment]
@xai1983kbu I've figured out my particular issue, at last. In my case, we were not properly handling the promise returned by Auth.signOut().

Again, this was causing an issue where even if a user signed out of their Google account, they would be able to sign in automatically into our Amplify app after signing out. By properly handling the promise, users signed out of their Google accounts AND our app are now asked to re-authenticate against Google's servers.

**Comment by xai1983kbu** [comment]
@leosoaivan sorry, misunderstood your needs.

**Comment by Jun711** [comment]
@leosoaivan 
what did you do to properly handle the promise returned by Auth.signOut()? Could you provide  more information? Thanks

**Comment by Jun711** [comment]
@manueliglesias
```
User can sign in automatically even after signing out from the app and social IdP layer
```
Do you know how I can resolve this issue?

Note that the question is NOT about signing out from app should sign out from social IdP such as Google. 

The situation is user signing out from social IdP AND also from the app. After that, the user can log in automatically by using federatedSignIn via Amplify without requiring social IdP login again.

@leosoaivan 
It seems that Cognito hosted UI behaves the same. Instead of showing signIn UI, hosted UI only shows `Continue with Google` and `Sign in as a different user`. If I click `Continue with Google`, it wouldn't prompt me to login via social IdP again even though I am not logged in with social IdP at that moment. It would just redirect to my landing page directly.

**Comment by leosoaivan** [comment]
@Jun711 As I mentioned above, `Auth.signOut()` returns a promise that needs to be properly resolved, either with `await` or `then/catch`. 

Our problem was we were doing a lot of logic on our logout, like so:

```javascript
Auth.signOut();
/** Other logic **/
```

We switched to the following, which somehow resolved our issue:

```javascript
Auth.signOut()
  .then(() => {
    /** Other logic **/
})
  .catch(() => {
    /** Catch logic **/
})
```

Hope this helps.

**Comment by Jun711** [comment]
@leosoaivan 
Mine is already with `then/catch` and I printed out the response from the promise and it is undefined. 
Even though mine is already `then/catch`, the issue `User can sign in automatically even after signing out from the app and social IdP layer (Google)` still happens. 
same with the hosted UI, could you double check hosted ui?

```
Auth.signOut()
  .then(res => {
    console.log('res ', res) // would be undefined
    /** Other logic **/
})
  .catch(() => {
    /** Catch logic **/
})
```

**Comment by aibrahim3546** [comment]
@manueliglesias Hi, This issue is still occuring for my react native app.

I don't have any hosted UI, I am using the federate sign in.

Here is my issue
- My user signin using google acc for firs time. He get to select an account.
- My user logout from app and want to sign in with another account. He can't, aws auto log in the user with prevs credentials.
- My user logout from both app and logout from google account in his browser. He still can't choose new google acc, aws auto log in him again.
- The only way to let the user to choose back a google acc is to, clear the browser data. Which is not a proper solution.

Will appreciate if you can help with this issue.

**Comment by jacdx** [comment]
@aibrahim3546 Did you find a solution yet?

**Comment by aajinkya1203** [comment]
Anyone got a solution for this?

**Comment by MuhammadAbdullah54321** [comment]
> @manueliglesias Hi, This issue is still occuring for my react native app.
> 
> I don't have any hosted UI, I am using the federate sign in.
> 
> Here is my issue
> 
> * My user signin using google acc for firs time. He get to select an account.
> * My user logout from app and want to sign in with another account. He can't, aws auto log in the user with prevs credentials.
> * My user logout from both app and logout from google account in his browser. He still can't choose new google acc, aws auto log in him again.
> * The only way to let the user to choose back a google acc is to, clear the browser data. Which is not a proper solution.
> 
> Will appreciate if you can help with this issue.

I am facing exactly same issue

**Comment by kewur** [comment]
clearing local caches doesn't help eirher

```
  public clearCognitoTokens(): void {
    const removeTokens: string[] = [];
    for (let i = 0; i < localStorage.length; i++){
      if (localStorage.key(i).startsWith('CognitoIdentityServiceProvider')) {
        removeTokens.push(localStorage.key(i));
      }
    }


    removeTokens.forEach(item => {
      localStorage.removeItem(item);
    });
  }
  ```

**Comment by Baghel-sumit** [comment]
same issue described by @aibrahim3546

**Comment by kewur** [comment]
same, just upgraded to the latest version from v1, still happening

**Comment by MoeKanan** [comment]
@manueliglesias any updates on this issue? lots of users are stuck and can't switch Google accounts

**Comment by kewur** [comment]
who do we have to SEV2 to get some eyes on this?

**Comment by anuradhawick** [comment]
Any update on this issue?
