### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource for Pinpoint enpoint

### ISSUE THREAD

**Issue by rjjlucy** [aws-amplify/amplify-js#4721]
**Describe the bug**
```
Access to XMLHttpRequest at 'https://pinpoint.us-east-1.amazonaws.com/v1/apps/7a5a3670f5d044308ed4e5d8a44e3ab8/users/unknown' from origin 'https://a.app.chime.aws' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
**To Reproduce**
1. Open our web app in Chrome.
2. Open the developer console.
3. See the error

**Expected behavior**
No error

- Device: OSX Mojave 
- Browser: Chrome 
- Amplify version: 2.2.1

**Sample code**
Ping me through Chime renjingy@ and I can show you the codes.

**Comment by rjjlucy** [comment]
Inside Amplify SDK, when you make calls to pinpoint, you need to trigger a CORS preflight OPTION request. With this preflight request, the response header will include `Access-Control-Allow-Origin: *`  and the problem should be solved.

**Comment by manueliglesias** [comment]
Hi @rjjlucy 

The CORS preflight is done automatically by the browser, is this not happening?

**Comment by rjjlucy** [comment]
No. From [this post](https://stackoverflow.com/questions/20035101/why-does-my-javascript-code-get-a-no-access-control-allow-origin-header-is-pr), I think CORS headers has to be added to the backend server to allow cross origin access. So I think this has to be fixed by Amplify side.

**Comment by sorokinvj** [comment]
hey guys, having a similar issue, and because of the internal auth, I can't even debug API with Postman. My Lambda function set cors and in API Gateway I test the function and see that all access headers are set up. But Chrome said – no no headers in preflight requests. So how to solve it?

**Comment by keithdmoore** [comment]
I am having a similar issue but its with a HTTP POST request using API gateway.  My GET requests work fine.

**Comment by voojo** [comment]
Hey, Any updates on how to solve that issue? I am facing the same problem that blocks my projects as sending emails using SES via Lamda (using Amplify) is a big part of it.
