### ISSUE TITLE
Subscriptions sometimes fail, no error, no way to detect

### ISSUE THREAD

**Issue by houmark** [aws-amplify/amplify-js#4733]
**Describe the bug**
We are seeing random fails when connecting to a subscription. There are no errors, looking at Chrome dev tools WS socket, it looks like the socket connects, but no data/messages are sent back.

The subscription is a standard subscription to GraphQL.

**To Reproduce**
I'm afraid this one is somewhat hard to reproduce. We are using the very latest version of `amplify-js` and the most recent changes to subscriptions in the library has not changed anything in relation to this.

I know this does not make it easy to debug on, but my hope is to get pointers on how to track any message sent back and use that to better understand when the socket fails. I have studied the source code and cannot find anything in there that was helpful (probably due to my lack of understanding the related code) but we do have `error` configured, though as mentioned, no error is thrown.

Maybe others have seen similar behavior?

**Expected behavior**
That the library connects without issues and at least throws an error if it does not have a stable connection so that we can attempt to re-connect.

**Update:**
I was able to catch messages sent in the console when this happened again.

1. The client sends the GraphQL query to start the subscription.

![Broken subscription](https://user-images.githubusercontent.com/467330/72658679-3ff87280-3982-11ea-97a4-a529654c1363.png)

2. The client receives `start_ack` and after that silence.
![Image 2020-01-17 at 11 37 10 PM](https://user-images.githubusercontent.com/467330/72658686-69b19980-3982-11ea-914a-1e3f1bacaa2e.png)

Nothing is changed in the code for things to break. The component is otherwise stable and this is just happening randomly once in n times. This happens across all our components and for multiple users. We feel like it was more stable in the past, but we can't say as this is as mention hard to monitor on.

**Comment by elorzafe** [comment]
@houmark can you try @unstable version published on npm of Amplify?

You can see the messages on Chrome dev tools on network tab look for `graphql?header=...` request, there you will be able to WebSocket messages sent to AppSync

**Comment by houmark** [comment]
Yeah, I will try it out.

If a subscription fails, there seems to be no real way of detecting that, even on errors. That means it's hard on the UI side to detect a problem and attempt a reconnection.

**Comment by elorzafe** [comment]
@houmark  can you also try this version on your app as well? We are adding a new mechanism for error notifications there.
`npm i -E aws-amplify@2.2.5-rn-datastore.4`

**Comment by houmark** [comment]
I can if you can tell me more about how I detect errors in my code and if you would merge back unstable fix into that branch?

**Comment by houmark** [comment]
Also, that looks to be React Native related? I am running a normal React web app.

**Comment by elorzafe** [comment]
When subscribing it should notify the error on the `error` callback on the observer

**Comment by elorzafe** [comment]
> Also, that looks to be React Native related? I am running a normal React web app and I'm not using offline sync (yet).

Yes we are working on DataStore support for react-native, but that also has changes related to the problem you mention

**Comment by houmark** [comment]
So that means something like this should work?

```javascript
next: n => {
  // ... code
},
error: error => {
      // ... error handling here
}
```

**Comment by houmark** [comment]
I see master is already merged back, so I will test this out.

**Comment by elorzafe** [comment]
@houmark you are correct, how did it go?

**Comment by houmark** [comment]
It feels way more stable, but I am still struggling to understand which callbacks are sent back, so I'll look into the sources to figure out which positive (subscription success for example) and negative events I can catch to somehow retry or handle that situation.

Today I slept my Mac, went to a new location, connected using my phone connection, all while being on a page that had a subscription. I then pushed a change that should deliver a subscription message, which it actually did, so even reconnects seems to be pretty decent (which is one of the things I'd like to be able to listen/detect so that the UI can react if there's no working subscription to the platform). Being able to know if the socket is fully connected and working at all times is becomes more and more important as we are not updating the UI after a mutation, we simply rely on the socket update coming back to update, which means the UI really breaks for the user if the socket is not stable/working.

**Comment by sammartinez** [comment]
Im marking this as a feature request as we do not have a listening event in Hub today for Web socket statuses. Also want to put the label on for improving the documentation on this.

**Comment by houmark** [comment]
Thank you. Hope to see that added soon, as sockets are really the basics of many web/native apps these days. I wonder why others don't have problems with this.

**Comment by jstorm31** [comment]
I have also faced this issue. We use AppSync for realtime subscriptions with a custom Pipeline Authorizer Resolver. A subscription works fine, but when an error event is sent to the subscription (when creating the subscription), the SDK does not send it in the error callback of the subscription. Though the error is visible in network devtools for the socket.

Is there any progress on the issue? Right now, it isn't possible to display a UI message when the subscription fails. 😕 

```js
    appSyncClient
        .subscribe({
            query: gql(subscriptions.onIoTElevatorStatePublish),
            variables: { elevatorId },
        })
        .subscribe({
            next: data => {
                console.log({ data });
            },
            error: error => {
                console.log({ error }); // <- not called when the subscription is created and immediate error is sent
            },
        });
```

![Screenshot 2021-04-07 at 12 02 43](https://user-images.githubusercontent.com/16023539/113848867-316dc500-9799-11eb-80a9-8f03f5a47482.png)

**Comment by stocaaro** [comment]
Reading through the history on this one. It sounds like the original issue was that there was instability that was improved upon in 2020, however, a secondary issue of not having any feedback on the health of the connection kept this open as a feature request.

We shipped a change with the release this past Monday that adds Hub messages for AppSync subscription connection state changes. Here's [a link to the related documentation](https://github.com/aws-amplify/docs/pull/4505) that is in PR at present.

I'm going to close this. If there is an aspect of this troubleshooting effort that hasn't been addressed at this point, please reopen this request with clarification about what remains to be resolved.

Thanks!
