### ISSUE TITLE
Storage.get - Download progress tracking

### ISSUE THREAD

**Issue by jayalog** [aws-amplify/amplify-js#4734]
** Which Category is your question related to? **
 Storage.
** What AWS Services are you utilizing? **
Cognito, Auth, Storage.

I am using aws amplify Auth and storage in web application. I am using Storage.get to download a file from S3 bucket. How to track progress of the download?

**Comment by sw-yx** [comment]
maybe get the file metadata to see the size of the file, and then track bytes downloaded to calculate the %?

**Comment by jayalog** [comment]
@sw-yx Thank you. How to track bytes downloaded since we don't have control over http call, amplify is handling it.

**Comment by sw-yx** [comment]
good question. amplify probably needs to expose a callback for that, or you need to hack it in yourself.

**Comment by sammartinez** [comment]
@jayalog This is something that we would need to implement on our side as @sw-yx has called out. I am marking this as a feature request and will discuss this internally to verify if this is a use case we are looking to support within the library. Thanks!

**Comment by jayalog** [comment]
Thank u @sammartinez.

**Comment by enriqueavg** [comment]
Any updates of this? The progress download feature is so important for ux.

**Comment by jamesaucode** [comment]
Hello @enriqueavg , there's a PR currently being reviewed that will add support to this feature.
