### ISSUE TITLE
Open FB app directly instead of using the browser during federated auth flow

### ISSUE THREAD

**Issue by mguay22** [aws-amplify/amplify-js#4735]
** Which Category is your question related to? **
Authentication
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **

It looks the URL used to launch the federated OAuth flow is hardcoded with `http`
https://github.com/aws-amplify/amplify-js/blob/9fc0e596/packages/auth/src/OAuth/OAuth.ts#L91

It would be a more ideal UX to open the FB app directly to complete the auth flow if the user has it installed, instead of going through a mobile browser. If we were able to supply the protocol, we could utilize FB deep links to complete the auth flow in the app.

**Comment by iartemiev** [comment]
Have you tried federating with Identity Pools utilizing Facebook Login directly? (Instead of using Hosted UI) i.e., https://aws-amplify.github.io/docs/js/authentication#facebook-example-in-react-native-expo

Are you using React Native or Ionic?
