### ISSUE TITLE
PubSub throws error suggesting identityPoolId is not set, when in fact it is.

### ISSUE THREAD

**Issue by pranaypratyush** [aws-amplify/amplify-js#4736]
Auth.currentCredentials() shows correct identityPoolId but when I try to publish or subscribe it throws the error
```
[Unhandled promise rejection: TypeError: Cannot read property 'identityPoolId' of undefined]
- node_modules/@aws-amplify/pubsub/node_modules/@aws-amplify/core/lib/Credentials.js:198:37 in __generator$argument_1
* http://192.168.1.128:19003/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:503494:21 in step
- node_modules/@aws-amplify/pubsub/node_modules/@aws-amplify/core/lib/Credentials.js:25:30 in <anonymous>
* http://192.168.1.128:19003/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:503396:69 in <unknown>
- node_modules/promise/setimmediate/core.js:45:4 in tryCallTwo
- node_modules/promise/setimmediate/core.js:200:12 in doResolve
- node_modules/promise/setimmediate/core.js:66:2 in Promise
* http://192.168.1.128:19003/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:503375:12 in __awaiter
- node_modules/@aws-amplify/pubsub/node_modules/@aws-amplify/core/lib/Credentials.js:190:4 in <anonymous>
- node_modules/@aws-amplify/pubsub/node_modules/@aws-amplify/core/lib/Credentials.js:399:17 in prototype.set

```

I was working on a project from scratch and had simply added default auth config with phone number as username, nothing custom. I didn't implement the signUp confirmation yet so I manually verified the test user from AWS console.

**Expected behavior**
SignIn works perfectly so it's expected that pubsub would also work correctly given the right permissions are set. 

<details>
  <summary><strong>Environment</strong></summary>

```
System:
    OS: Linux 5.3 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 3.79 GB / 31.33 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 13.6.0 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.13.4 - /usr/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 72.0.1
  npmPackages:
    expo-cli: ^3.11.5 => 3.11.5 
    global: ^4.4.0 => 4.4.0 
    react-dev-tools: ^0.0.1 => 0.0.1 
    react-devtools: ^4.4.0 => 4.4.0 
  npmGlobalPackages:
    npm: 6.13.4
    serverless-appsync-plugin: 1.1.2

```

</details>

**Smartphone (please complete the following information):**

- Device: OnePlus6T
- OS: Android 10

**Comment by pranaypratyush** [comment]
So it seems like it's trying to log me in as `guest` even though it should be `session`

**Comment by tanguy2508** [comment]
I am facing the same problem, did you find a way to make it work ?

**Comment by pranaypratyush** [comment]
No. Still working on it. The problem it seems is that amplify credentials is running the `guest` login code for my case but it should run the `session` case. Check `@aws-amplify/core/lib/Credentials.js:392`

**Comment by tanguy2508** [comment]
i did an upgrade of aws-amplify dependency and it seams to work now, which version of it do you have in your package.json? i'm now with version 2.2.2

**Comment by pranaypratyush** [comment]
Also on 2.2.2

**Comment by tanguy2508** [comment]
how is your Amplify.configure( ... ) ?

**Comment by pranaypratyush** [comment]
I am doing the configure in my root App file. My `aws-exports.js` looks like the following.
```
const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:3b2...",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_BB...",
    "aws_user_pools_web_client_id": "2b5...",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https:/zamby....appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};
```

**Comment by tanguy2508** [comment]
was doing this too but for PubSub to work it seems you had to had it this way :

`const awsmobile = {
   ... 
   Auth: {
       identityPoolId: 'us-east-1:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx',
       region: 'us-east-1',
       userPoolId: 'us-east-1_xxxxxxxxxx',
       userPoolWebClientId: 'xxxxxxxxxxxxxxxxxxxx',
   },
   ...
  },`

**Comment by pranaypratyush** [comment]
Hmm... Let me try that.

**Comment by pranaypratyush** [comment]
Now get a slightly different error 
```
[Unhandled promise rejection: TypeError: Cannot read property 'identityPoolId' of undefined]
- node_modules/@aws-amplify/pubsub/node_modules/@aws-amplify/core/lib/Credentials.js:198:37 in __generator$argument_1
* http://192.168.1.128:19003/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:503593:21 in step
- node_modules/@aws-amplify/pubsub/node_modules/@aws-amplify/core/lib/Credentials.js:25:30 in <anonymous>
* http://192.168.1.128:19003/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:503495:69 in <unknown>
- node_modules/promise/setimmediate/core.js:45:4 in tryCallTwo
- node_modules/promise/setimmediate/core.js:200:12 in doResolve
- node_modules/promise/setimmediate/core.js:66:2 in Promise
* http://192.168.1.128:19003/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:503474:12 in __awaiter
- node_modules/@aws-amplify/pubsub/node_modules/@aws-amplify/core/lib/Credentials.js:190:4 in <anonymous>
- node_modules/@aws-amplify/pubsub/node_modules/@aws-amplify/core/lib/Credentials.js:399:17 in prototype.set
```

**Comment by pranaypratyush** [comment]
I had initially assumed that the error is a result of me manually verifying the user from the console and that's why Amplify is probably treating this signin as guest (which would still be a bug).

**Comment by tanguy2508** [comment]
looks like the error you sent here is the same

**Comment by pranaypratyush** [comment]
Oh yes. Exactly the same error. Apparently, this config format didn't help.

**Comment by pranaypratyush** [comment]
Anything new on this?

**Comment by tanguy2508** [comment]
I got my PubSub to work following this article, maybe you should try this exemple, and then if works, integrate it to your code
[https://medium.com/serverlessguru/serverless-real-time-reactjs-app-aws-iot-mqtt-17d023954045](url)

**Comment by pranaypratyush** [comment]
I got it mate. I set `Amplify.configure({Auth:{madatorySignIn:true}})`. Amplify had generated it as false. My hypothesis is that now Amplify is logging in as `session` instead of `guest`.

**Comment by pranaypratyush** [comment]
It seems the issue was caused by me installing both `aws-amplify` and `@aws-amplify/pubsub`. I removed the latter and the issue disappeared but now I get `AMQJS0007E Socket error:undefined.` when I try to publish even though all my auth roles are in place.

**Comment by 0x6c23** [comment]
Check your stack in CloudFormation and look for the AuthRole. This should be the authRole from your federated identity pool. Attach `AWSIoTDataAccess` to it. Also you should attach the IoT policy (created in IoT Core) to your user. You can do so with:

`aws iot attach-principal-policy --policy-name 'myIoTPolicy' --principal '<YOUR_COGNITO_IDENTITY_ID>'`

**Comment by pranaypratyush** [comment]
Both are done in my case. Also how do I make it so that all users in a cognito user pool/group can access some or all of my iot topics.

**Comment by pranaypratyush** [comment]
Also, I think access denied should have some other error code.

**Comment by pranaypratyush** [comment]
This problem was finally resolved by downgrading all amplify packages to `2.1.0`. Still unsure what was the peculiar case causing this problem for me.

**Comment by sammartinez** [comment]
@pranaypratyush Are you still pinned to this version of `aws-amplify` or are you still experiencing this with the latest version of Amplify. Please let us know.
