### ISSUE TITLE
SerializationException: Expected map or null

### ISSUE THREAD

**Issue by intagen** [aws-amplify/amplify-js#4738]
When enrolling MFA device in AWS Cognito under UserPool with SOFTWARE_TOKEN_MFA and then trying to confirm signIn, I'm getting an error that I haven't had months back (code hasn't changed).

`{"__type":"SerializationException","Message":"Expected map or null"}`

Typical Amplify confirmSignIn is in place.

`await Auth.confirmSignIn(user, code, SOFTWARE_TOKEN_MFA);`

Always worked, ideas?

**Comment by intagen** [comment]
@Ashish-Nanda, still got this, any ideas?

**Comment by sammartinez** [comment]
@intagen Can you provide some code snippets or a gist if possible of your setup?
