### ISSUE TITLE
SSL Pinning and potential thread when not in place

### ISSUE THREAD

**Issue by g-ioannidi5** [aws-amplify/amplify-js#4740]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
This is more of a concern that arises from the fact that SSL Pinning is not yet supported by amplify-js. 

We are implementing a React Native mobile application. Would a potential man-in-the-middle attack obtain access and retrieve the user's credentials (username and password) during signin? We are using amplify-js for sign-in.

If the answer is yes would SSL Pinning help prevent that in any way?

Thank you,
Giorgos

**Comment by ericclemmons** [comment]
We'll have to look into it more with input from security, but I can say that apps from companies like Starbucks _do_ use certificate pinning as an additional layer of security to their gateway.

Since you're using React Native, there's a great article on the subject here that you can try out:
> https://hackernoon.com/strengthen-tls-in-react-native-through-certificate-pinning-e6e8d53e8254

**Comment by ericclemmons** [comment]
Sorry for not following up sooner. There's a great deal of internal documentation that I went through, but it ultimately points to, at AWS' scale, customers pinning certificates has unintentionally broken users' apps when underlying certificates were renewed.

> The first problem is that when you pin to a reduced set of CAs, you are taking on the management of a root program, just like the browsers do. You have to decide who's in and who's out -- not just at launch, but over time. As we've seen, CAs can be distrusted and go out of business, and new ones can eventually take their place. It's actually an easy problem for Google, because they also own a publicly trusted CA. [9] That's who they trust to issue their domains. But if you don't own your own CA, or if you're dealing with clients that are difficult to update in a guaranteed way (e.g. IoT, mobile, Kindles), you have to think very hard about the choices you will make and live with over years, if not decades.

It's better to not run a CA, but https://aws.amazon.com/certificate-manager/private-certificate-authority/ can handle it if you so choose.
