### ISSUE TITLE
signUpConfig not updating fields

### ISSUE THREAD

**Issue by waqas-syed** [aws-amplify/amplify-js#4741]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide Additional Details **
I am following the [tutorial](https://aws-amplify.github.io/docs/js/angular#signup-configuration) exactly as it is but my fields don't update and remain as they should without the signUpConfig parameter.
Referring to issue #2897, I added public to the signUpConfig variable but even that is not fixing it.
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css']
})
export class SignupComponent {

  public signUpConfig = {
    header: 'My Customized Sign Up',
    hideAllDefaults: true,
    defaultCountryCode: '1',
    signUpFields: [
      {
        label: 'My user name',
        key: 'username',
        required: true,
        displayOrder: 1,
        type: 'string',
      },
      {
        label: 'Password',
        key: 'password',
        required: true,
        displayOrder: 2,
        type: 'password'
      },
      {
        label: 'PhoneNumber',
        key: 'phone_number',
        required: true,
        displayOrder: 3,
        type: 'string'
      },
      {
        label: 'Custom Attribute',
        key: 'custom_attr',
        required: false,
        displayOrder: 4,
        type: 'string',
        custom: true
      }
    ]
  }

  constructor(){
  }
}
```
**OS**: MacOS
**Amplify Version**: 2.2.2
**Amplify Angular Version**: 4.1.3

**Comment by sammartinez** [comment]
@waqas-syed Can you provide us a gist or a code snippet of your code you are working with? Thanks ahead of time.
