### ISSUE TITLE
Racing Condition: Auth events dispatched before Hub.listen() are lost

### ISSUE THREAD

**Issue by JulianKl** [aws-amplify/amplify-js#4743]
**Describe the bug**

In my React application that is using Amplify Auth I noticed that signing in is flakey and sometimes just does not work. 

After investigation, I found that the Function "_handleAuthRespons" in Auth.ts is sometimes dispatching the 'signIn' event before my application is able to call Hub.listen(). In cases where my application runs the Hub.listen() first, the events are processed normally by the callback function I pass to Hub.listen(). If the 'signIn'-Event is dispatched before Hub.listen(), nothing happens. 

Moving up Hub.listen() to the very start of my React application has increased the likelihood of a successful sign in, but this approach does not solve the underlying issue of a racing condition. Additionally, the 'signIn_Failure' event is always dispatched before my application is able to run Hub.listen().

**Expected behavior**

I expect Hub.listen() to pick up events that have occurred before initialising.

**Comment by sammartinez** [comment]
@JulianKl Do you have any sample code that you could share with us to help with looking into your issue? Also, could you provide the versions you are seeing the race condition occur on? Thanks ahead of time.

**Comment by JulianKl** [comment]
@sammartinez I am using Version 1.2.4.

The Hub code looks as follows: 

```
useEffect(() => {
    const authListener = async ({ payload }) => {
      switch (payload.event) {
        case 'signIn':
          await UserService.logIn();
          track('signIn');
          break;
        case 'signIn_failure':
          setSignInFailure();
          track('signIn_failure');
          break;
        case 'signUp':
          track('signUp');
          break;
      }
    };
    Hub.listen('auth', authListener);

    return () => {
      Hub.remove('auth', authListener);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
```

The Hub.listen() is executed through useEffect on the first rendering of the Login Page. It is used to change the application UI to the logged-in state and to track a couple of events. Federated Logins are used (Facebook). If you need anything else, please let me know!

**Comment by camin-mccluskey** [comment]
This is still an issue
