### ISSUE TITLE
GET/LIST specific version of an object from s3

### ISSUE THREAD

**Issue by arnab-roy-13** [aws-amplify/amplify-js#4746]
I want to get a specific version of an object from s3. But I haven't seen any way to pass the specific `versionId` to my `get` request of `amplify-storage`. Is there any way around to do that?

detailed question can be found [here](https://stackoverflow.com/questions/59836539/get-put-specific-version-of-an-object-via-aws-amplify).

The gist is - 

When I am calling - 
```
Storage.get(key, {
    // options
  });
```
I want to pass a `versionId` params to this as well, so that I can get that specific version of that object.

Is that even possible? While we are at it, Is there any way to get all the `versionId`s for a specific key?

**Comment by Amplifiyer** [comment]
Hi @arnab-roy-13, it is currently not possible to specify a version in Amplify, it is same as #2131 which we have marked it as a feature request. Please +1 or add comment to #2131. If you would like to take a shot at adding this feature in amplify, we will be happy to help you and prioritize your PRs. Closing this in favor of #2131
