### ISSUE TITLE
AuthError on deploy but not locally

### ISSUE THREAD

**Issue by richAtreides** [aws-amplify/amplify-js#4747]
**Describe the bug**
Hi when I run my app locally using NPM start it works fine and I can sign in. However when I deploy to a feature branch for testing I get the following error:

"Cannot read property 'clientMetadata' of undefined"

The logs state the following:

"[ERROR] 28:45.925 AuthError - 
            Error: Amplify has not been configured correctly.
            This error is typically caused by one of the following scenarios:

            1. Make sure you're passing the awsconfig object to Amplify.configure() in your app's entry point
                See https://aws-amplify.github.io/docs/js/authentication#configure-your-app for more information
            
            2. There might be multiple conflicting versions of aws-amplify or amplify packages in your node_modules.
                Try deleting your node_modules folder and reinstalling the dependencies with `yarn install`"

**To Reproduce**
My app.js file has the following:

`import Amplify from "aws-amplify";
import awsmobile from "./aws-exports";'

Amplify.configure(awsmobile);` so I know that isn't the issue.

I have run amplify push and am on the latest version of node. The build file is as follows:

version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
        - npm install aws-amplify
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

so I don't really see the issue. Can someone help?

**Comment by Ashish-Nanda** [comment]
Can you tell us a bit more about the app you have built? If you could share some sample code for how you are implementing the login usecase we can try and reproduce it.

**Comment by richAtreides** [comment]
I fixed it. For some reason amplify added conflicting requirements in the package.json. I deleted them manually and now it works.

Thanks!

**Comment by sammartinez** [comment]
Resolving as above statement. Glad you were able to solve your issue!
