### ISSUE TITLE
[VueJS] Firefox autofill don't work

### ISSUE THREAD

**Issue by michelschmit** [aws-amplify/amplify-js#4748]
**Describe the bug**
On Firefox with `amplify-js-vue`. Since the only trigger event of `UserNameField` inputs is `v-on:keyup`, select a  value from the firefox autofill dropdown only with mouse doesn't call the `usernameChanged` function.

**To Reproduce**

1. Click in username input
2. Click on a saved username from the Firefox autofill dropdown

Link to sample code

https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-vue/src/components/authenticator/UsernameField.vue#L23

**update** adding a `@blur` trigger seem to fix the issue.

**Comment by Andrei94** [comment]
This issue happens with the angular version as well. If after using the auto fill functionality the user presses the up key for each of his fields, then amplify detects the values. However this is counterintuitive for the average user

**Comment by ericclemmons** [comment]
Can you share your experience with using https://docs.amplify.aws/ui/q/framework/vue?

We've pulled forward fixes for this (and others) into our `@aws-amplify/ui-components` project and want to confirm it's resolved. 🤞

**Comment by BeagleTechno** [comment]
Hi, I have aws s3 provisioned to my app. I can upload and delete files to my bucket, but I cannot see them on the app (method GET returns an error?). Ideas?

**Comment by ericclemmons** [comment]
@BeagleTechno Your question sounds unrelated to OP's. Would you mind creating a new issue?
> https://github.com/aws-amplify/amplify-js/issues/new/choose
