### ISSUE TITLE
2 redirects needed to Hosted UI to authenticate user

### ISSUE THREAD

**Issue by heitorseesdragons** [aws-amplify/amplify-js#4761]
I am using amplify with Angular, and in my AuthGuard file, the currentAuthenticatedUser method fails in the first redirect from the hosted UI, redirecting BACK to the hosted UI. This is the flow:

1. I try to access a protected route in my app

2. I get redirected to the hosted UI page, as expected

3. I sign in and get redirected back to the app by the hosted UI, with the "code" parameter properly set. The 'amplify-redirected-from-hosted-ui' flag is set on my local storage, but not the cognito keys and  the ' 'amplify-signin-with-hostedUI' that are set by amplify after the redirect.

![image](https://user-images.githubusercontent.com/26798171/72955618-7ef74100-3d51-11ea-884b-0945ac5d1a3e.png)

4. for whatever reason (I guess Amplify never set the keys needed after the redirect from hosted UI) the Auth.currentAuthenticatedUser() method (see below) fails and I get redirected back to the hosted UI

```
@Injectable()
export class AuthGuard implements CanActivate {
	constructor(private router: Router) {}

	canActivate(
		next: ActivatedRouteSnapshot,
		state: RouterStateSnapshot
	): Observable<boolean> | Promise<boolean> | boolean {
		return Auth.currentAuthenticatedUser()
			.then(data => {
				return true;
			})
			.catch(err => {
				location.assign(
					'https://' +
						environment.cognitoHostedURL +
						'/login?response_type=code&client_id=' +
						environment.currentCognitoClientID +
						'&redirect_uri=' +
						environment.currentCognitoCallbackURL
				);
				return false;
			});
	}
}

```

5. I am back at the hosted UI page, and it now has the "Sign in as Heitor" or "Sign in with another user" option.

![image](https://user-images.githubusercontent.com/26798171/72955855-6a677880-3d52-11ea-99a2-1eb5f79bffc4.png)

6. I click the "Sign in as Heitor" option

7. the hosted UI redirects back to the app, and this time the same Auth.currentAuthenticatedUser() retrieves the data. Looking at localStorage now. All variables are set.

![image](https://user-images.githubusercontent.com/26798171/72955906-ac90ba00-3d52-11ea-9eb2-bf7bba77f823.png)

This flow happens 100% of the time. Fails on the first time, successful on the second. Any ideas of why it is not working (needing two trips instead of one)?

Thank you,

Heitor

**Comment by sammartinez** [comment]
@heitorseesdragons Can you provide insight into your Auth Guard and using location.assign(), this could potentially cause the race condition you are experiencing. We do recommend to to use [Auth.federatedSignIn()](https://aws-amplify.github.io/docs/js/authentication#oauth-and-hosted-ui) for the above approach.
