### ISSUE TITLE
How to make a relationship of data from user pool to aws appsync model

### ISSUE THREAD

**Issue by yvescoinpass** [aws-amplify/amplify-js#4763]
** Which Category is your question related to? **
  Auth, API

** What AWS Services are you utilizing? **
Cognito, AWS AppSync

** Provide additional details e.g. code snippets **
    aws-amplify: "^2.2.1",
    aws-amplify-react: "^3.1.2",

I am new to amplify and appsync. I am trying to create a Post model that needs to have a relationship of the user who is creating the Post. The problem is my user is from cognito user pool.

What I want is the user from cognito I don't want to create new user table on dynamo db because cognito user pool already has its information I just want to get the user info that is creating that Post if I query the post.

How should I create a relationship of this?

I create amplify API like this

```
? Please select from one of the below mentioned services: GraphQL
? Choose the default authorization type for the API API key
? Enter a description for the API key: 
? After how many days from now the API key should expire (1-365): 7
? Do you want to configure advanced settings for the GraphQL API Yes, I want to make some additional changes.
? Configure additional auth types? Yes
? Choose the additional authorization types you want to configure for the API Amazon Cognito User Pool
Cognito UserPool configuration
Use a Cognito user pool configured as a part of this project.
? Configure conflict detection? No
```
Here is my current schema.graphql

```
type Post
    @model
    @versioned
    @aws_cognito_user_pools
    @auth(rules: [{ allow: owner, queries: null }, { allow: public }]) {
    id: ID!
    title: String!
    content: String
    thumb: String
    slug: String!
    allow_comments: Boolean
    owner: String!
    post_type: String!
    add_to_nav: Boolean!
    version: Int!
    comments: [Comment] @connection(name: "PostComments")
}

type Comment
    @model
    @versioned
    @aws_cognito_user_pools
    @auth(rules: [{ allow: owner, queries: null }]) {
    id: ID!
    content: String
    version: Int!
    post: Post @connection(name: "PostComments")
}
```

I can't find any documentation how to build something like this.

**Comment by sammartinez** [comment]
Resolving as a duplicate to https://github.com/aws-amplify/amplify-cli/issues/3251
