### ISSUE TITLE
Is there a way to logout from the pool, or multiple app clients at once?

### ISSUE THREAD

**Issue by heitorseesdragons** [aws-amplify/amplify-js#4764]
I have a cognito pool setup with two clients (lets call them client 1 and client 2). The two clients are angular apps and you can navigate between them. Similar to a google "Single Sign On" where once you are logged in to any of their apps (like mail.google.com) you are logged in to all of their apps (like calendar.google.com). The same is true for logout. Once you logout from one you logout from all.

In my implementation, when the user is signed in to client 1 and I click a link to the client 2, I am able to authenticate that user seamlessly, by redirecting to the hosted UI with the "?authorize" method.

However, I want to logout from client 1 and automatically logout from client 2 too (or vice-versa). Is there a way to do this? Something like a "pool" logout instead of a specific client logout? Currently I am just calling the hosted UI with the "?logout" method, but it just logs out of that specific client.

**Comment by ericclemmons** [comment]
For that single user, you should be able to do a global sign-out:
> https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js#sign-out

The caveat is that the tokens are still valid until they expire, usually an hour, but won't refresh like usual:
> https://github.com/aws-amplify/amplify-js/issues/3435

Things are a little tricky when you're effectively syncing state between two apps (`sub1.example.com` and `sub2.example.com`), but your different domains can call `Auth.currentAuthenticatedUser({ bypassCache: true })` and listen to `Hub`'s `signIn`/`signOut` events to help keep things in sync:
> https://docs.amplify.aws/lib/auth/social/q/platform/js#setup-frontend
