### ISSUE TITLE
Datastore: Uncaught (in promise) DOMException issue when logging into SECOND concurrent session

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/amplify-js#4765]
Code repro: https://github.com/sw-yx/svelte-amplify-auth-demo
Deployment repro: https://d1tdmagl19vwso.cloudfront.net/

**Describe the bug**

```bash
datastore.js:16 Uncaught (in promise) DOMException
rejected @ datastore.js:16
Promise.then (async)
step @ datastore.js:17
(anonymous) @ datastore.js:18
./node_modules/@aws-amplify/datastore/lib-esm/datastore/datastore.js.__awaiter @ datastore.js:14
start @ datastore.js:504
observe @ datastore.js:328
./src/stores/data.js @ data.js:11
__webpack_require__ @ bootstrap:19
./src/Main.svelte @ bundle.js:77762
__webpack_require__ @ bootstrap:19
./src/App.svelte @ bundle.js:76931
__webpack_require__ @ bootstrap:19
./src/main.js @ main.js:1
__webpack_require__ @ bootstrap:19
1 @ data.js:60
__webpack_require__ @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83

```

I know that #4577 has the same title, but i have checked and verified i don't have that issue. I'm also not SURE it is a SECOND concurrent session issue, but that is how it is presenting to me right now.

Link to sample code: https://github.com/sw-yx/svelte-amplify-auth-demo

in my first session, i can do CRUD fine: https://d1tdmagl19vwso.cloudfront.net/
![image](https://user-images.githubusercontent.com/6764957/73023262-25e2e800-3df9-11ea-8dad-2ec4dc9d324d.png)

However if I log in in another session (eg in an incognito window), i get this weird error:

![image](https://user-images.githubusercontent.com/6764957/73023414-7a866300-3df9-11ea-91ad-7cd4226142da.png)

It's minimized, so its not very helpful, so I can also replicate this in local dev:

![image](https://user-images.githubusercontent.com/6764957/73023455-938f1400-3df9-11ea-83a8-df84ddee836d.png)

The relevant user code (`./src/stores/data.js @ data.js:11`) is

```js
const subscription = DataStore.observe(Note)
```

so hopefully that helps track it down

**Expected behavior**

datastore apps should work with multiple concurrent logged in sessions

<details>
  <summary><strong>Environment</strong></summary>

```

  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 161.79 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.17.0/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 71.0
    Firefox Nightly: 73.0a1
    Safari: 13.0.4
  npmPackages:
    @aws-amplify/auth: ^2.1.3 => 2.1.3 
    @aws-amplify/core: ^2.2.2 => 2.2.2 
    @aws-amplify/datastore: ^1.0.4 => 1.0.4 
    aws-amplify: ^2.2.2 => 2.2.2 
    bootstrap: ^4.4.1 => 4.4.1 
    cross-env: ^5.2.0 => 5.2.1 
    css-loader: ^2.1.1 => 2.1.1 
    inquirer: ^7.0.3 => 7.0.3 
    mini-css-extract-plugin: ^0.6.0 => 0.6.0 
    serve: ^11.0.0 => 11.3.0 
    sirv-cli: ^0.4.4 => 0.4.5 
    style-loader: ^0.23.1 => 0.23.1 
    svelte: ^3.0.0 => 3.17.2 
    svelte-loader: 2.13.3 => 2.13.3 
    webpack: ^4.30.0 => 4.41.5 
    webpack-cli: ^3.3.0 => 3.3.10 
    webpack-dev-server: ^3.3.1 => 3.10.1 
  npmGlobalPackages:
    @aws-amplify/cli: 4.12.0
    diff-so-fancy: 1.2.7
    egghead-cli-course-abcd1: 1.0.0
    eslint: 6.7.1
    netlify-cli: 2.29.0
    now: 16.7.3
    npm: 6.13.4
    rincewind: 3.0.5
    serve: 11.2.0

```

</details>

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by manueliglesias** [comment]
Hi @sw-yx 

I can't reproduce the behavior you are seeing, I've cloned your repo and also tried from your cloudfront distribution.

Are you still having the problem?

**Comment by sw-yx** [comment]
yes, i am. to be clear, first login on https://d1tdmagl19vwso.cloudfront.net/ is fine, and then i open up incognito and login on https://d1tdmagl19vwso.cloudfront.net/ and get the error in incognito (so it is not due to any extensions). any other way i can help you reproduce?

**Comment by sammartinez** [comment]
@sw-yx @manueliglesias Im curious if its an issue with Svelte and Amplify playing nicely together as we haven't done a deep dive into support for Svelte.

**Comment by sw-yx** [comment]
im pretty sure its not svelte related, but dont have time to repro right now. will redo in react to see if can repro.
