### ISSUE TITLE
undefined is not an object (evaluating 'o.accessToken')

### ISSUE THREAD

**Issue by HMilbradt** [aws-amplify/amplify-js#4770]
**Describe the bug**
This bug occurs when a "Pre Sign Up" lambda trigger returns an error when using `Auth.federateSignIn({ provider: social_provider })`.  Just before it is thrown, another error is thrown: `OAuth - Error handling auth response. Error: PreSignUp+failed+with+error-Error-message-here` internally.

**To Reproduce**
Steps to reproduce the behaviour:

1. Add a Pre sign up trigger that returns an error
2. Attempt to sign in with a Social provider
3. See error

**Expected behaviour**
The error message from the pre sign up trigger should be emitted on the event bus, while the other error should not be thrown.

**Comment by elorzafe** [comment]
@HMilbradt I reproduced the problem you mention, we will be working on fix. Thanks for your feedback.
