### ISSUE TITLE
withAuthenticator refresh token

### ISSUE THREAD

**Issue by kuklinm** [aws-amplify/amplify-js#4779]
Auth, Cognito

I am using withAuthenticator with federatedSignIn:
`withAuthenticator(hot(module)(App),
  false,
  [<FederatedSignIn federated={{google_client_id: AppConfig.GOOGLE_CLIENT_ID}}/>],
  null,
  {
    oAuthSignInButton: {
      display: 'none'
    },
    strike: {
      display: 'none'
    }
  });`

After session set, I got aws-amplify-federatedInfo key in local storage. I work with token from this object. But after one hour it expires and doesn't refresh. How I could get session to refresh token?

**Comment by tomasyaya** [comment]
I think that if you call Auth.currentSession() it Amplify refresh the tokens it self.

**Comment by kuklinm** [comment]
> I think that if you call Auth.currentSession() it Amplify refresh the tokens it self.

I think federatedSignIn has  no relation with Auth.currentSession so it will return 'No current user'.

**Comment by ashika01** [comment]
@kuklinm : Could you provide us more information on your use case specifically around getting `aws-amplify-federatedInfo`? If you are using `withAuthenticator` it should handle refreshing the token for you.
