### ISSUE TITLE
Authenticator HOC and authentication codes

### ISSUE THREAD

**Issue by nissane** [aws-amplify/amplify-js#4783]
I am using Cognito with amplify JS.  The workflow I am trying to accomplish is:

- authorize via cognito
- receive back an authentication code
- convert it to an authorization token

when I use the Authenticator HOC, I am not able to get back a authentication code, I immediately get back an authorization_token, and refresh_token. This is the case even when I set the responseType: 'code'. 

How can I accomplish this?  I prefer not to have to implement a custom UI.  I see that withOAuth returns back an authentication code, but that UI is unusable (look and feel).

** so my questions are: **
1.  how do i get back a authentication code from the Authenticator HOC?
2.  if the Authenticator only returns back an authorization token and a refresh token, how are we expected to securely use it?
3.  Are there any other alternatives besides using the Hosted UI.

Many Thanks,
Eric

**Comment by harrysolovay** [comment]
If you've already completed the MFA flow once, the device is remembered. During testing, you can get the current user pool user and forget that user:

```ts
const userPoolUser = await Auth.currentUserPoolUser({bypassCache: true});
const forgetResponse = await new Promise((resolve, reject) => {
  userPoolUser.forgetDevice({
    onFailure(e) {
      return reject(e);
    },
    onSuccess(result) {
      return resolve(e);
    },
  });
]);
```

And to answer your other question, yes!: there are alternatives to the hosted UI. You can [utilize the `Auth` category's MFA features](https://docs.amplify.aws/lib/auth/mfa/q/platform/js#setup-totp) directly in your own components.
