### ISSUE TITLE
Storage issues after update to aws-amplify 2.2.2.

### ISSUE THREAD

**Issue by michaelcuneo** [aws-amplify/amplify-js#4784]
** Which Category is your question related to? **
Storage
** What AWS Services are you utilizing? **
Storage
** Provide additional details e.g. code snippets **

I have these two functions that used to work pre aws-amplify 2.2.2.

I've just started a new project with my old functions, and whenever I use putS3 or getS3, I now come across an error that I never used to see... 

`[DEBUG] 17:32.807 Storage.S3Image TypeError: Cannot read property 'get' of undefined`

and then, 

`Storage.js?7185:212 Uncaught (in promise) No plugin found in Storage for the provider`

```
export async function putS3(filename, file, type) {
  return Storage.put(filename, file, {
    contentType: type,
  })
    .then(response => response)
    .catch(error => error);
}

export function getS3(name, access) {
  return Storage.get(name, access)
    .then(response => response)
    .catch(error => error);
}

```

Not sure what's happening, it's a brand new setup, with hosting, cognito and storage. Hosting is set to Dev, cognito is set to default username, storage is set to authenticated read/write/edit/delete, and guest read/write/edit/delete.

I noticed now also that since my update to 2.2.2 I now get a project listing in the AWS Amplify online console, which never used to happen before.

**Comment by alexofob** [comment]
I am facing same issue when using Storage.put api.

**Comment by VincentDevelopment** [comment]
Any updates yet?

**Comment by VincentDevelopment** [comment]
FYI: Reinstalling fixed everything for me...

**Comment by sammartinez** [comment]
@michaelcuneo Are you still experiencing this issue? Please let us know.

**Comment by michaelcuneo** [comment]
Same with @VincentDevelopment a few days later it just started working. I think an update somewhere fixed it.
