### ISSUE TITLE
[WARN] AuthClass - No AWS.config even if Amplify is configured

### ISSUE THREAD

**Issue by Gautierrr** [aws-amplify/amplify-js#4787]
**Describe the bug**
The warning `[WARN] AuthClass - No AWS.config` appears in my console during app initialization even if Amplify is configured and functional. Everything works fine! But I have this warning...

![image](https://user-images.githubusercontent.com/16082250/73272487-bf880c00-41e2-11ea-951d-d0c7841e53bc.png)

**To Reproduce**

Launch the application with this `main.js`:

```js
import React from "react";
import { render } from "react-dom";
import Amplify from "aws-amplify";

Amplify.configure({ ... });

render(
  <div>Hello World!</div>,
  document.getElementById("react")
);
```

**Expected behavior**
Not having this warning message printed in the console.

**Additional context**
```json
"aws-amplify": "~2.2.2",
"aws-amplify-react": "~3.1.3",
```

My real use case is the following, but I have the same warning:

```js
import React from "react";
import { render } from "react-dom";
import { Authenticator } from "aws-amplify-react";
import App from "./App";

render(
  <Authenticator
    hideDefault
    amplifyConfig={{ ... }}
  >
    <App />
  </Authenticator>,
  document.getElementById("react")
);
```

**Comment by sammartinez** [comment]
@Gautierrr Have you configured Amplify CLI with this? From the code snippets you're providing, I am not seeing an `import awsconfig from './aws-exports';` which could cause this issue. Please verify the [pre-reqs](https://aws-amplify.github.io/docs/js/start#prerequisites) needed to use our React package

**Comment by Gautierrr** [comment]
No, I wrote my config thanks to the documentation. See:
- https://aws-amplify.github.io/docs/js/start#next-steps
- https://aws-amplify.github.io/docs/js/authentication#manual-setup

So my config looks something like this:

```js
{
  Auth: {
    // REQUIRED - Amazon Cognito Identity Pool ID
    identityPoolId: 'XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab', 
    // REQUIRED - Amazon Cognito Region
    region: 'XX-XXXX-X', 
    // OPTIONAL - Amazon Cognito User Pool ID
    userPoolId: 'XX-XXXX-X_abcd1234',
    // OPTIONAL - Amazon Cognito Web Client ID
    userPoolWebClientId: 'XX-XXXX-X_abcd1234',
    ...
  }
}
```

**Everything works fine**! Except i get this warning 🤔 

**Note**: I only use Amplify for authentication with Cognito.

**Comment by Gautierrr** [comment]
No more warning since the upgrade of aws-amplify from the v2.2.7 to the v3.0.9 and aws-amplify-react from the v3.1.8 to v4.1.8. 🤷‍♂️
