### ISSUE TITLE
Created a lambda in console and try to apply to dynamo and get

### ISSUE THREAD

**Issue by esuarezz** [aws-amplify/amplify-js#4793]
**Describe the bug**
Cannot access stream arn:aws:dynamodb:eu-west-1:317290818279:table/DietsTable-t62bsuje4vee7lnunwdyk3cs7a-hapstodev/stream/2020-01-06T05:01:31.321. Please ensure the role can perform the GetRecords, GetShardIterator, DescribeStream, and ListStreams Actions on your stream in IAM. (Service: AWSLambda; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 838ca002-d626-4e57-a53d-ecf757896d17)

**To Reproduce**
1) Created a lambda function from aws console
2) assign to one table created in dynamo that is on my app and wheious error I finish the form and click in "Agregar" I guess in english add, y get the prev.

**Comment by ashika01** [comment]
@esuarezz are using aws amplify in this app?

**Comment by esuarezz** [comment]
Yes, suee

**Comment by ashika01** [comment]
@esuarezz could you provide some sample code and explain the use case you are trying to achieve?

Also looking at this, it looks like you might be missing some IAM permissions?
> Please ensure the role can perform the GetRecords, GetShardIterator, DescribeStream, and ListStreams Actions on your stream in IAM.
