### ISSUE TITLE
Unable to use complex object S3Object in in appsync

### ISSUE THREAD

**Issue by kian-barba** [aws-amplify/amplify-js#4796]
**Describe the bug**

Hello, I suspect there is a step missing, or something otherwise wrong with this project: https://github.com/aws-samples/aws-amplify-graphql

After following the setup steps and trying to run the app, here is the error I see:

Error: The parameters: App client Id, App web domain, the redirect URL when you are signed in and the redirect URL when you are signed out are required.

**To Reproduce**

1. follow this example https://github.com/aws-samples/aws-amplify-graphql
2. After the last step "npm run start" you get the error

**Expected behavior**
see the cognito login screen

**Screenshots**

<img width="1680" alt="Screen Shot 2020-01-28 at 22 32 03" src="https://user-images.githubusercontent.com/6806582/73328063-09421800-421e-11ea-9744-151d457deea2.png">

**Comment by ashika01** [comment]
@kian-barba could you post the just the keys of your `awsConfig` ? Looks like backend might not configured correctly.

**Comment by kian-barba** [comment]
We fixed the problem bby running `npm update` and update "aws-amplify" package to the latest version (v1.3.3 at this time).

**Comment by jordanranz** [comment]
Closing this issue as it seems to be fixed now. Please open a new issue if you experience any related problems
