### ISSUE TITLE
Expo federated login redirect error

### ISSUE THREAD

**Issue by JSDevelopment17** [aws-amplify/amplify-js#4800]
![fullsizeoutput_1f29](https://user-images.githubusercontent.com/33499076/73388274-d7868b00-42c9-11ea-9c47-60f1c62bddef.jpeg)
I've configured my Expo React Native project to use Federated login with Facebook according to this great tutorial: https://dev.to/dabit3/the-complete-react-native-guide-to-user-authentication-with-the-amplify-framework-ib2

On my simulator all works as planned. However, when I run via the expo app on a physical device, or publish to TestFlight, I click on my Facebook login button and am correctly sent to login with facebook but once I have done this and the redirect to expo app happens I receive the error in the attached.

Section from aws-exports.js
    "oauth": {
        "domain": "xxx.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "exp://127.0.0.1:19000/--/",
        "redirectSignOut": "exp://127.0.0.1:19000/--/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS"

I have also added to my app.json:
    "scheme": "myapp",

**Comment by JSDevelopment17** [comment]
Can anyone help on this?

**Comment by Graig123git** [comment]
I am facing the same error was this resolved ?

**Comment by Graig123git** [comment]
look at what port Expo app is running on turns out mine was on exp://192.168.2.135:19000
so i updated the urls to reflect this.

**Comment by rahulje9** [comment]
I'm having the same error, But not with expo.

**Comment by amhinson** [comment]
@JSDevelopment17 Does @Graig123git's answer fix your issue?
