### ISSUE TITLE
Incorrect username/password error is not displayed when using <amplify-authenticator> tag in Angular

### ISSUE THREAD

**Issue by Andrei94** [aws-amplify/amplify-js#4801]
**Describe the bug**
When trying to login as an nonexistent user using the <amplify-authenticator> tag in Angular, the error message is not displayed and the <amplify-authenticator> tag disappears from the view.

**To Reproduce**

1. Configure a user pool with hosted UI
2. Use the <amplify-authenticator> tag for sign in
3. Try to login with an incorrect user and/or password

**Additional context**
This seems to come from the fact that inside the aws-ampligy-angular module/sign-in-component-core.ts there the logic
```
this._show = includes(
			['signIn', 'signedOut', 'signedUp'],
			data.authState.state
		);
```
When an nonexistent user tries to login, a ```signIn_failure``` is returned for authState and hence the <amplify-authenticator> tag disappears. 
A solution that comes to mind would be to also add this state to the code above.

**Comment by jordanranz** [comment]
Hey @Andrei94, can you elaborate a bit more on the usage of Amplify or `aws-amplify-angular` in your Angular code?

Are you using the `<amplify-authenticator>` tag or a different tag?

I attempted to reproduce with an app using  `<amplify-authenticator></amplify-authenticator>` and see the following when trying to sign in with a nonexistent user:

<img width="524" alt="Screen Shot 2020-02-05 at 12 38 47 PM" src="https://user-images.githubusercontent.com/3868826/73881157-b1567300-4814-11ea-98ad-361bd6f2819b.png">

**Comment by Andrei94** [comment]
Sure. 
I am using the amplify `<amplify-authenticator>` tag with the signUp config from the docs.
I tried with Chrome Version 80.0.3987.87 (Official Build) (64-bit) and Firefox 72.0.2 (64-bit) on Windows 10.

This is my sign in page
![signIn](https://user-images.githubusercontent.com/8221614/74083110-1bffec80-4a69-11ea-9454-36ea7476ceed.jpg)

This is what happens when I try to sign in when I change the password to be incorrect. The same thing happens when the user doesn't exist

![signInFailure](https://user-images.githubusercontent.com/8221614/74083109-173b3880-4a69-11ea-997b-4a14e71a93de.jpg)
