### ISSUE TITLE
Cognito Lambda Triggers Cold Start Fires Multiple Times

### ISSUE THREAD

**Issue by mikedizon** [aws-amplify/amplify-js#4805]
**Describe the bug**

I am using SNS to dispatch a SMS message to suppport passwordless authentication for my users. On a cold start, the lambda function fires three times, sending three different codes to the user.

**To Reproduce**

Call Auth.signup();

Link to sample code

**Expected behavior**

**Screenshots**

<details>
  <summary><strong>Environment</strong></summary>

```

  System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Memory: 275.54 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.5.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 71.0
    Safari: 13.0.4
  npmGlobalPackages:
    @angular/cli: 6.2.3
    @aws-amplify/cli: 4.13.1
    @vue/cli: 3.5.3
    amplify-typescript: 1.0.5
    babel-minify: 0.5.0
    babel-preset-es2015: 6.24.1
    babel-preset-stage-2: 6.24.1
    bower: 1.8.0
    coffee-script: 1.12.7
    cordova: 8.0.0
    create-react-native-app: 2.0.2
    decaffeinate: 4.8.8
    expo-cli: 2.1.3
    firebase-tools: 7.3.2
    ganache-cli: 6.3.0
    gulp-cli: 1.3.0
    gulp: 3.9.1
    jscs: 3.0.7
    lerna: 3.19.0
    n: 3.0.1
    netlify-cli: 2.20.2
    node-gyp: 3.8.0
    nodemon: 1.18.10
    npm-check-updates: 2.14.2
    npm: 6.13.4
    pkglink: 0.7.9
    postcss-cli: 6.1.1
    react-devtools: 3.4.0
    react-native-cli: 2.0.1
    react-native-rename: 2.2.2
    rnpm: 1.9.0
    serverless: 1.54.0
    truffle: 5.0.2
    tsc: 1.20150623.0
    typescript: 2.8.3
    vue-cli: 2.9.3
    wml: 0.0.83
    yarn: 1.12.3
    yo: 2.0.2
    zos: 2.2.0

```

</details>

**Additional context**
It would be great if we were able to control the timeout setting or set the amount of retries that amplify makes when calling the authentication methods.

**Comment by Jobel91** [comment]
Hello,

Cognito Lambda triggers are limited, see the docs : https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html#important-lambda-considerations 

> Amazon Cognito invokes Lambda functions synchronously. When called, your Lambda function must respond within 5 seconds. If it does not, Amazon Cognito retries the call. After 3 unsuccessful attempts, the function times out. This 5-second timeout value cannot be changed. For more information see the Lambda programming model.

**Comment by mikedizon** [comment]
Found the source of the issue. Moved the require outside of the function and the issue went away.

https://github.com/aws-amplify/amplify-cli/issues/3212

**Comment by ericclemmons** [comment]
Thanks for the update @mikedizon!  Should we close https://github.com/aws-amplify/amplify-cli/issues/3212 as well, based on:
> Found the source of the issue. Moved the require outside of the function and the issue went away.
?

**Comment by mikedizon** [comment]
@ericclemmons the generator could be refactored to not out the require inside of the function :)

**Comment by ericclemmons** [comment]
@mikedizon Of course!  The generator's the problem.  Great, let's keep it open so that gets addressed 👍.
