### ISSUE TITLE
Datastore - observe - only local data are seen

### ISSUE THREAD

**Issue by mlecoq** [aws-amplify/amplify-js#4810]
I have the following code to be able to list projects in my react component. 

```
  const [projects, setProjects] = useState<Project[]>();

  useEffect(() => {
    (async () => {
      const projects = await DataStore.query(Project);

      setProjects(projects);
    })();
  }, []);

  useEffect(() => {
    const subscription = DataStore.observe(Project).subscribe(async msg => {
      const projects = await DataStore.query(Project);
      setProjects(projects);
    });

    return () => {
      subscription.unsubscribe();
    };
  }, []);
```

I have a form to create new projets: 

```
 <Formik
      initialValues={{ title: "" }}
      validate={values => {
        const errors: { title?: string } = {};
        if (!values.title) {
          errors.title = "Required";
        }

        return errors;
      }}
      onSubmit={async (values, { setSubmitting }) => {
        await DataStore.save(new Project(values));
        setSubmitting(false);
      }}
    >
```

Here is my model 

```
type Project @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  """
  Title of the project.
  """
  title: String!
  """
  Description of the project
  """
  description: String
  """
  Reports of the project
  """
  reports: [Report] @connection(name: "ProjectReports")
}

type Report @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  """
  Number of the report.
  """
  number: String
  """
  Title of the report
  """
  title: String
  """
  Project
  """
  project: Project @connection(name: "ProjectReports")
}
```

I have opened 2 browsers and opened the same page to check that if I create a project in one browser, It pops up in the second. But I have to refresh the second page to see it 

Reading the docs of observe method :

_You can subscribe to changes on your Models by using observe in the DataStore API. This reacts dynamically to updates of data to the underlying Storage Engine, which could be the result of GraphQL Subscriptions as well as Queries or Mutations that run against the backing AppSync API if you are synchronizing with the cloud._

I understand that It should observe remote data.

I am using @amplify/datastore@1.0.4 - I have tried 1.0.5.unstable.12 but the behavior is not better (data are no more stored in my DynamoDB table).

I also have remarked that all data created with 1.0.5 are never sent to backend after putting back 1.0.4 - It would be great if Datastore could retry all data that have never been sent (I am afraid to have cases where data is stuck on device indefinitely)

**Comment by elorzafe** [comment]
@mlecoq did you make a change on the `schema.graphql` file and run `npm run amplify-modelgen` without running `npm run amplify-push`?

**Comment by mlecoq** [comment]
Yes I run `amplify model codegen` and `amplify push` after every changes.

Here is my was-export.js (generated by amplify cli, I have made no customization)


```
const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:xxxxx",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_xxxx",
    "aws_user_pools_web_client_id": "xxxxj",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xxxx.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
```

**Comment by mlecoq** [comment]
Ok I have found the cause of the issue while comparing my project with this one: https://github.com/awsed/AppSyncGraphQLNotes

We should have a warning somewhere during schema compilation. I make a separate issue in amplify cli

**Comment by XC3S** [comment]
After I ran into the same problem, I would like to point out that just the `owner `field is missing in the schema.

**Comment by mlecoq** [comment]
@XC3S FYI I have made a feature request here : https://github.com/aws-amplify/amplify-cli/issues/3325
