### ISSUE TITLE
DataStore - authorization breaks sync

### ISSUE THREAD

**Issue by mlecoq** [aws-amplify/amplify-js#4811]
Hi,

I have modified my model from 

```
type Project
  @model
  @auth(
    rules: [
      { allow: owner }
    ]
  ) {
  id: ID!
  """
  Title of the project.
  """
  title: String!
  """
  Description of the project
  """
  description: String
  """
  Reports of the project
  """
  reports: [Report] @connection(name: "ProjectReports")


  createdAt: AWSDateTime
  updatedAt: AWSDateTime
}
```

to 

```
type Project
  @model
  @auth(
    rules: [
      { allow: owner }
      {
        allow: owner
        ownerField: "editors"
        operations: [read, update, delete]
      }
    ]
  ) {
  id: ID!
  """
  Title of the project.
  """
  title: String!
  """
  Description of the project
  """
  description: String
  """
  Reports of the project
  """
  reports: [Report] @connection(name: "ProjectReports")

  editors: [String] @auth(rules: [{ allow: owner, ownerField: "owner" }])

  createdAt: AWSDateTime
  updatedAt: AWSDateTime
}
```

Then it works fine with Appsync console but Datastore does not call Appsync anymore. Data are local only. I have tried to find something in the logs and I have just some info on Subscriptions 

```
[WARN] 11:12.603 DataStore - Sync error subscription failed Connection failed: {"errors":[{"message":"Validation error of type MissingFieldArgument: Missing field argument owner @ 'onUpdateProject'"}]}

[DEBUG] 11:12.613 AWSAppSyncRealTimeProvider - subscription message from AWS AppSync RealTime: {"type":"error","id":"eaa34d4d-27bf-4222-ad16-62049d8fd677","payload":{"errors":[{"message":"Validation error of type MissingFieldArgument: Missing field argument editors @ 'onDeleteProject'"}]}}
```

Is there something special to do at Datastore level ?

**Comment by mlecoq** [comment]
I am using amplify-cli 4.13.1 and amplify-datastore 1.0.4

**Comment by elorzafe** [comment]
@mlecoq thanks for your feedback, if you try all operations enabled is it working? 

it Is not possible for `owner` authorization in case you don't allow `create` operation to perform any changes for that type. We will have an internal team discussion and have posted here.

I would use `group` authorization rather than `owner` for this case, so a group can create projects an another can make changes.

**Comment by mlecoq** [comment]
I will create another type to check. What surprises me is that all works fine when I directly make a graphql mutation. So I do not understand what prevents Datastore to make it

**Comment by mlecoq** [comment]
I prefer owner authorization because in the app I want to build users can give access to their own data to other users directly (so using groups will make me generates dynamically many groups)

**Comment by mlecoq** [comment]
I have added a third type Post 

```

type Post @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  """
  Number of the remark.
  """
  number: String
  """
  Title of the remark
  """
  title: String
}
```

And created post are also not sent to backend

**Comment by mlecoq** [comment]
I have tried to set authorized operations explicitly:

```
type Project
  @model
  @auth(
    rules: [
      { allow: owner, operations: [create, read, update, delete] }
      {
        allow: owner
        ownerField: "editors"
        operations: [read, update, delete]
      }
    ]
  ) {
  id: ID!
  """
  Title of the project.
  """
  title: String!
  """
  Description of the project
  """
  description: String
  """
  Reports of the project
  """
  reports: [Report] @connection(name: "ProjectReports")

  editors: [String] @auth(rules: [{ allow: owner, ownerField: "owner" }])

  createdAt: AWSDateTime
  updatedAt: AWSDateTime
}
```

and I have the same result (works only on Appsync side)

**Comment by mlecoq** [comment]
Same issue as https://github.com/aws-amplify/amplify-js/issues/4810

Missing `owner` field breaks datastore

**Comment by mlecoq** [comment]
An error is raised when I store new items: 

Error: Field editors should be of type string[], object received. null datastore.ts:262

**Comment by mlecoq** [comment]
I have modified locally Datastore code locally to support 2 owner auths. It works fine for querying but not for subscriptions : generated subscriptions requires 2 parameters (owner and editors) so setting both when you’re not the owner leads to having a subscription that never sents anything

**Comment by mlecoq** [comment]
Pb explained here: https://github.com/aws-amplify/amplify-cli/issues/1043 (proposal 3)
