### ISSUE TITLE
Passing code challenge to Cognito Federated Identiy via Amplify [Okta]

### ISSUE THREAD

**Issue by arjunsk** [aws-amplify/amplify-js#4814]
I Integrated Cognito Userpool with Federated Identity [Okta - As Secure Web Authentication]. The flows works fine with Authorization Code Flow without PKCE (Using Amplify with Angular).

Created a similar app as SPA(in Okta), to enable PKCE and integrated with Cognito federated identities. When we redirect to Hosted UI, the challenge is getting passed to hosted UI in the URL.

![image](https://user-images.githubusercontent.com/9638314/73541197-ce2b2900-4457-11ea-81f7-b281a74d6f96.png)

Cognito Hosted UI URL Challenge
But after it redirects to okta, it is throwing this error.

_

> _pkce code challenge is required when the token endpoint authentication method is 'none'_

_

Is there any additional configuration required in Cognito to pass code-challenge to Okta.

I am using Authorization Code flow in Cognito and Okta.

Attaching the configuration in Okta. Okta Configuration for Login Redirect
![image](https://user-images.githubusercontent.com/9638314/73541223-e1d68f80-4457-11ea-961e-dbcbc9d7e110.png)

Attaching the configuration in Cognito Cognito Configuration
![image](https://user-images.githubusercontent.com/9638314/73541238-ea2eca80-4457-11ea-8561-351eb034f0c2.png)

**Comment by lakersr8ers** [comment]
Any update on this? I'm also seeing a similar issue.

**Comment by arjunsk** [comment]
Cognito to Okta, is a service to service authentication. So we don’t enable PKCE flow in Okta.

Full Post: https://medium.com/@arjunsk/configuring-cognito-user-pool-federated-identity-okta-1349d4aec1f
