### ISSUE TITLE
RedirectUri not registered 

### ISSUE THREAD

**Issue by kiitos-smasri** [aws-amplify/amplify-js#4816]
Once i log in using Google federated sign in 
app opens and directly error appears 

console.error: "[ERROR] 59:27.380 OAuth - Error handling auth response.", Error: RedirectUri+is+not+registered+with+the+client+

prototype._log
    ConsoleLogger.js:96:12
prototype.error
    ConsoleLogger.js:152:18
__generator$argument_1
    OAuth.js:231:31
step
    OAuth.js:56:22
<anonymous>
    OAuth.js:37:52
<anonymous>
    OAuth.js:31:70
tryCallTwo
    core.js:45:4
doResolve
    core.js:200:12

any ideas ?

**Comment by tomasyaya** [comment]
Dont know if its my place to cheap in but, did you register the callback url?

**Comment by kiitos-smasri** [comment]
actually i did but it was a spelling mistake in callback url :S

**Comment by ericclemmons** [comment]
@kiitos-smasri Glad to hear that you got this resolved!  Let us know if there's something else going on.

(I ran through our internal federated sign in sample and confirmed things are working there, at least 👍)
