### ISSUE TITLE
Facebook token is not automatically refreshing

### ISSUE THREAD

**Issue by aschimmel** [aws-amplify/amplify-js#4819]
**Describe the bug**
We are logging in users with `Auth.federatedSignIn({ provider: "Facebook" });` and the login expires after 60 minutes. AWS Cognito is configured for 3650 days for refresh token validity. This issue was not happening on earlier versions of amplify.

This is specifically with the React package.

**To Reproduce**

Setup authentication via the federatedSignIn functionality and wait 60 minutes.

**Expected behavior**
The user should be automatically refreshed per the documentation. 

> By default, AWS Amplify will automatically refresh the tokens for Google and Facebook when the app is in the web environment, so that your AWS credentials will be valid at all times.

<details>
  <summary><strong>Environment</strong></summary>

  System:
    OS: Windows 10 10.0.19041
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 15.31 GB / 31.92 GB
  Binaries:
    Node: 12.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.19041.1.0
    Internet Explorer: 11.0.19041.1
  npmPackages:
    aws-amplify: ^2.2.2 => 2.2.2
    aws-amplify-react: ^3.1.3 => 3.1.3
    aws-sdk: ^2.606.0 => 2.606.0
    create-react-class: ^15.6.3 => 15.6.3
    history: ^4.10.1 => 4.10.1
    is-buffer: ^2.0.4 => 2.0.4
    node-sass: ^4.13.1 => 4.13.1
    prop-types: ^15.7.2 => 15.7.2
    query-string: ^6.10.1 => 6.10.1
    react: ^16.12.0 => 16.12.0
    react-app-polyfill: ^1.0.5 => 1.0.5
    react-dom: ^16.12.0 => 16.12.0
    react-ga: ^2.7.0 => 2.7.0
    react-router: ^5.1.2 => 5.1.2
    react-router-dom: ^5.1.2 => 5.1.2
    react-scripts: ^3.3.0 => 3.3.0
    react-stripe-elements: ^6.0.1 => 6.0.1
    regenerator: ^0.14.2 => 0.14.2
</details>

**Additional context**
The value in local storage for `CognitoIdentityServiceProvider.xxx.Facebook_xxx.refreshToken` is empty.

**Comment by ericclemmons** [comment]
Noting that this sounds related to #4825...

**Comment by sammartinez** [comment]
@aschimmel To @ericclemmons above callout on this issue being related to issue [#4825](https://github.com/aws-amplify/amplify-js/issues/4825#issuecomment-628188140), we have resolved issues with federated sign in within our new UI Components. Can you try with the newer implementations and verify if this works for you? Thanks ahead of time
