### ISSUE TITLE
Uncaught (in promise) Error: No credentials, applicationId or region at AWSPinpointProvider.js:349

### ISSUE THREAD

**Issue by WinstonN** [aws-amplify/amplify-js#4824]
Fresh install of amplify with versions

```
    "aws-amplify": "^2.2.2",
    "aws-amplify-react": "^3.1.3",
```
Auth.signIn succeeds but throws console error

```
Uncaught (in promise) Error: No credentials, applicationId or region
    at AWSPinpointProvider.<anonymous> (AWSPinpointProvider.js:349)
    at step (AWSPinpointProvider.js:137)
    at Object.next (AWSPinpointProvider.js:67)
    at fulfilled (AWSPinpointProvider.js:19)
```

![image](https://user-images.githubusercontent.com/1143789/73583477-5c0a2100-44f7-11ea-962f-36009f5e91a9.png)
![image](https://user-images.githubusercontent.com/1143789/73583489-7217e180-44f7-11ea-995f-57af3d2135a9.png)

**Comment by ashika01** [comment]
@WinstonN : Could you provide us with steps to reproduce this? How are you adding auth and analytics?

**Comment by laygir** [comment]
I'm having a similar problem with following packages;

**Comment by WinstonN** [comment]
@ashika01 

Steps to reproduce

1. npm install aws-amplify aws-amplify-react
2. Create IAM user with policy https://aws-amplify.github.io/docs/cli-toolchain/usage#iam-policy-for-the-cli  
3. amplify configure
4. amplify init
5. amplify auth add
6. amplify push
7. add amplify
```
// amplify
import AmplifyAuth from '@aws-amplify/auth';
```
8. use code here for signIn https://aws-amplify.github.io/docs/js/authentication#sign-in

Console error will be produced

**Comment by GGonryun** [comment]
@WinstonN  did you find a way around this? 

I'm getting the same console error when trying to follow the instructions under Analytics for the Amplify docs.

**Comment by ashika01** [comment]
@WinstonN : could you check if your policy is properly linked to your auth accounts in console? we will work on reproducing this.

**Comment by nihp** [comment]
I am also facing the same issue. But I am using aws-amplify-react-native 

  "aws-amplify": "^2.2.5",
  "aws-amplify-react-native": "^3.2.2",

**Comment by gmfinear** [comment]
@nihp I am also using aws-amplify-react-native and experiencing this issue

**Comment by ashika01** [comment]
@gmfinear what versions are you using?

**Comment by ashika01** [comment]
Could anyone try with the latest versions? and let me know if it still an issue? 
```
"aws-amplify": "3.0.9",
"aws-amplify-react-native": "4.1.0",
```

**Comment by gmfinear** [comment]
@ashika01 
"aws-amplify": "^3.0.8",
"aws-amplify-react-native": "^4.0.4",

**Comment by ashika01** [comment]
@gmfinear : Would it possible to share some code? Also, what are using analytics category for?

**Comment by gmfinear** [comment]
@ashika01  My code is superrr simple right now... I basically just ran expo init, and then followed instructions from https://aws-amplify.github.io/docs/js/tutorials/building-react-native-apps/  all the way up through Add Auth / User Sign-in.
![Screen Shot 2020-04-29 at 3 54 17 PM](https://user-images.githubusercontent.com/24783297/80654691-ba309c80-8a31-11ea-8b10-60e1ac712571.png)

**Comment by ashika01** [comment]
@gmfinear Let me just reproduce this.

**Comment by ashika01** [comment]
@gmfinear : I just followed the same steps. In my case its just a warning. Nevertheless, it shouldn't be happening. Will do some investigation

**Comment by gmfinear** [comment]
@ashika01 it's just a warning for me too, but really annoying :( thank you for investigating!!

**Comment by ashika01** [comment]
@nihp @gmfinear  This seems to be a bug in react-native. I have opened up the PR #5629 

@WinstonN - we have moved into new UI components. Please open a new issue if you are facing this issue with the new component. Docs - https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue

**Comment by sanyashvets** [comment]
https://github.com/aws-amplify/amplify-js/issues/3484#issuecomment-625790964

**Comment by SJI-ParthaSarathi** [comment]
I am getting this error! Is there anyone help me out please!
`Unhandled Runtime Error
Error: No credentials

Call Stack
GraphQLAPIClass.eval
node_modules/@aws-amplify/api-graphql/lib-esm/GraphQLAPI.js (193:0)
step
node_modules/@aws-amplify/api-graphql/lib-esm/GraphQLAPI.js (43:0)
Object.eval [as next]
node_modules/@aws-amplify/api-graphql/lib-esm/GraphQLAPI.js (24:44)
fulfilled
node_modules/@aws-amplify/api-graphql/lib-esm/GraphQLAPI.js (15:41)`
