### ISSUE TITLE
Datastore - Typescript - Predicates

### ISSUE THREAD

**Issue by mlecoq** [aws-amplify/amplify-js#4827]
Hi, 

I am using Create React App with typescript template.

When I write this line:

` const posts = await DataStore.query(Post, Predicates.ALL);`

I have the following error:

```
No overload matches this call.
  Overload 1 of 2, '(modelConstructor: PersistentModelConstructor<Post>, id: string): Promise<Post>', gave the following error.
    Argument of type 'ProducerModelPredicate<any>' is not assignable to parameter of type 'string'.
  Overload 2 of 2, '(modelConstructor: PersistentModelConstructor<Post>, criteria?: ProducerModelPredicate<Post> | undefined, pagination?: PaginationInput | undefined): Promise<...>', gave the following error.
    Argument of type 'ProducerModelPredicate<any>' is not assignable to parameter of type 'ProducerModelPredicate<Post>'.
      Types of parameters 'condition' and 'condition' are incompatible.
        Type 'ModelPredicate<Post>' is not assignable to type 'ModelPredicate<any>'.
          Type 'ModelPredicate<Post>' is not assignable to type '{ [x: string]: (operator: never, operand: never) => ModelPredicate<any>; }'.
            Index signature is missing in type 'ModelPredicate<Post>'.ts(2769)
```

I have to write 

```
const posts = await DataStore.query(
        Post,
        (Predicates.ALL as unknown) as ProducerModelPredicate<Post>
      );
```

**Comment by mlabieniec** [comment]
@mlecoq which typescript version are you using?

**Comment by mlecoq** [comment]
@mlabieniec typescript 3.7.5

**Comment by sammartinez** [comment]
@mlecoq We do have our Typescript version set to [3.6.4](https://github.com/aws-amplify/amplify-js/blob/master/package.json#L74). Can you verify if using this Typescript version will resolve your issue?

**Comment by mlecoq** [comment]
@sammartinez I have tried with 3.6.4, and unfortunately I have the same error

**Comment by apoorvmote** [comment]
I am also facing the same problem. I am using Typescript 3.7.5 and don't want to downgrade

@mlecoq thanks for workaround solution

**Comment by apoorvmote** [comment]
React has new update 16.13 that comes with Typescript 3.8.2

So eventually will require support for Typescript 3.8.2
