### ISSUE TITLE
How to recover account on failed MFA or phone is lost

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/amplify-js#4828]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito, Amplify
** Provide additional details e.g. code snippets **
I am using TOTP as MFA. If user deletes the google authenticator app then how to recover account?

Also in that case if I was using SMS MFA and user changed their phone number then how to recover account?

**Comment by apoorvmote** [comment]
I guess TOTP is not priority for cognito. But same is applied if we change our phone number and no longer have access to old phone number.

**Comment by jellydn** [comment]
Hello there,

I am sorry to bring this topic again. I am working on the same issue. How we could recover the account if lost TOTP or change phone number? Thank you very much.

**Comment by jellydn** [comment]
By the way, from the documentation, I could see the guideline for how to remove the TOTP token

https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-mfa-totp.html

![image](https://user-images.githubusercontent.com/870029/90353688-76fa4800-e079-11ea-9b70-0d08c5607e33.png)

Is that API ready to use or still in-plan? Thanks.

**Comment by porquelaquiero** [comment]
> By the way, from the documentation, I could see the guideline for how to remove the TOTP token
> 
> https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-mfa-totp.html
> 
> ![image](https://user-images.githubusercontent.com/870029/90353688-76fa4800-e079-11ea-9b70-0d08c5607e33.png)
> 
> Is that API ready to use or still in-plan? Thanks.

Did you find any solution? the more time I spend looking for any solution for mfa recovery issue, more negative i get about it.. If you found any, please share your wisdom.
