### ISSUE TITLE
Error in amplify-js Auth module bundle (aws-amplify-auth.js) - TypeError: Cannot read property 'ConsoleLogger' of undefined

### ISSUE THREAD

**Issue by martinlytics** [aws-amplify/amplify-js#4829]
**Describe the bug**
Error in amplify-js Auth module bundle (aws-amplify-auth.js) - TypeError: Cannot read property 'ConsoleLogger' of undefined

**To Reproduce**
(1) Download / clone Amplify JS from https://github.com/aws-amplify/amplify-js 
(2) NPM install required dependencies
(3) Build bundle under amplify-js\packages\auth: npm run build
(4) Load the bundle file (amplify-js\packages\auth\dist\aws-amplify-auth.js)  in a vanilla HTML file using <script> tag.

**Expected behavior**
The bundle aws-amplify-auth.js loads and runs without any errors. Amplify Auth APIs available in the web app.

** Actual behavior**
The bundle aws-amplify-auth.js hit the following error. Amplify Auth APIs not available to use. 

Please advise if I'm missing anything or if there is a workaround. Thanks!

OAuth.ts:38 Uncaught TypeError: Cannot read property 'ConsoleLogger' of undefined
    at Module../lib-esm/OAuth/OAuth.js (OAuth.ts:38)
    at __webpack_require__ (bootstrap:19)
    at Module../lib-esm/Auth.js (module.js:22)
    at __webpack_require__ (bootstrap:19)
    at Module../lib-esm/index.js (index.ts:1)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
    at bootstrap:83
    at webpackUniversalModuleDefinition (universalModuleDefinition:9)
    at universalModuleDefinition:10

**Screenshots**

<details>
  <summary><strong>Environment</strong></summary>

```
  System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 2.65 GB / 15.84 GB
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Users\mli\AppData\Roaming\npm\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.831.0
    Internet Explorer: 11.0.17763.771
  npmPackages:
    amazon-cognito-identity-js: ^3.2.2 => 3.2.2
    crypto-js: ^3.1.9-1 => 3.1.9-1
    react-native: ^0.61.5 => 0.61.5
```

</details>

**Smartphone (please complete the following information):**

**Additional context**

**Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by ericclemmons** [comment]
@martinlytics Thanks for reaching out!  It looks like you'd like to use Amplify's Auth category without a build-process (e.g. Webpack, Rollup, Parcel, etc.).

Can you share more about your use-case so we can address that need?

**Comment by martinlytics** [comment]
@ericclemmons Thank you for helping out. We have a legacy app that was created using ExtJS framework. It's not organized with NPM or any of the modern package managers. The only way I thought of to use the Amplify Auth module in our app (for integration with Cognito identity service) was to build a JS bundle and include it using <script></script> tags. That's how I hit the issue described above.

**Comment by martinlytics** [comment]
@ericclemmons What's the target release date for the "Standalone Bundles" milestone?

**Comment by ericclemmons** [comment]
@martinlytics We don't have a target release date yet, but have begun looking into what that solution would mean.

What did your `<script src="...">` look like in your situation?  (I'm interested if you were trying with a CDN, local `node_modules`, etc.)

**Comment by martinlytics** [comment]
Sure, Eric. I built the auth module under amplify-js\packages\auth. Then I created a sample html under amplify-js\packages\auth\dist that includes the aws-amplify-auth.js bundle:

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Sample App</title>
  </head>
  <body>
  <script type="text/javascript" src="aws-amplify-auth.js"></script></body>
</html>

Finally, I open the html in Chrome and try to access the Amplify Auth module in the console tab of Chrome development tools. They are not available, I assume due to the error described in this issue.

**Comment by ericclemmons** [comment]
My mistake! I misunderstood that the build step your using is our package-specific `build` command.

Unfortunately, that command won't fit your needs, as it builds the Amplify project for use by app bundlers (e.g. `webpack`, `parcel`, Vue/Angular CLI, Next.js, Create React App, React Native, etc.).

Until we can get a true stand-alone build working, here's something I was able to do based on the guide here:
> https://aws-amplify.github.io/docs/js/start?platform=purejs

**See code here: https://codesandbox.io/s/amplify-jsissues4829-z4qzb**

1. I created a `package.json` in my project like this:

	```json
	{
	  "name": "amplify-js-app",
	  "version": "1.0.0",
	  "description": "Amplify JavaScript Example",
	  "dependencies": {
	    "@aws-amplify/auth": "latest"
	  },
	  "devDependencies": {
	    "webpack": "^4.17.1",
	    "webpack-cli": "^3.1.0",
	    "copy-webpack-plugin": "^4.5.2",
	    "webpack-dev-server": "^3.1.5"
	  },
	  "scripts": {
	    "start": "webpack && webpack-dev-server --mode development",
	    "build": "webpack"
	  }
	}
	```

	Notice that I only have `@aws-amplify/auth` in `dependencies`.  If you use `@aws-amplify/storage`, or `@aws-amplify/analytics`, you'll need to add those via `npm install @aws-amplify/storage --save`.

1. `npm install` these dependencies.

1. I updated `webpack.config.js` to export a standalone version of Amplify to an `Amplify.bundle.js`, accessible as `window.Amplify` in the browser:

	```js
	const CopyWebpackPlugin = require("copy-webpack-plugin");
	const webpack = require("webpack");
	const path = require("path");
	
	module.exports = {
	  mode: "development",
	  entry: {
		// 👇 This is makes Amplify's NPM modules available
	    Amplify: "./src/Amplify.js"
	  },
	  output: {
	    filename: "[name].bundle.js",
	    globalObject: "this",
	    library: "Amplify",
	    libraryTarget: "umd",
	    path: path.resolve(__dirname, "dist")
	  },
	  module: {
	    rules: [
	      {
	        test: /\.js$/,
	        exclude: /node_modules/
	      }
	    ]
	  },
	  devServer: {
	    contentBase: "./dist",
	    overlay: true,
	    hot: true
	  },
	  plugins: [
	    new CopyWebpackPlugin(["index.html"]),
	    new webpack.HotModuleReplacementPlugin()
	  ]
	};
	```

1. Create `src/Amplify.js`:

	```js
	import Auth from "@aws-amplify/auth";
	import config from "./aws-exports";
	
	Auth.configure(config);
	
	// 👇 Everything exported here ends up on `window.Amplify.*`
	export { Auth };
	```

	This is configuring Auth with my project-specific settings, from `src/aws-exports.js` file created by the Amplify CI.  You're using the Amplify CLI, correct?

1. Next, I updated my `index.html` to use `Amplify.Auth` from the standalone bundle when the <kbd>button</kbd> is clicked:

	```html
	<body>
	  <div class="app">
	    <div class="app-header">
	      <div class="app-logo">
	        <img src="https://aws-amplify.github.io/images/Logos/Amplify-Logo-White.svg" alt="AWS Amplify" />
	      </div>
	      <h1>Welcome to the Amplify Framework</h1>
	    </div>
	    <div class="app-body">
	      <button onClick="javascript:Amplify.Auth.federatedSignIn()">
	        Log In
	      </button>
	    </div>
	  </div>
	  <script src="Amplify.bundle.js"></script>
	</body>
	```

1. `npm run build` creates `Amplify.bundle.js` from `./src/Amplify.js`.

	```console
	❯ npm run build
	
	> amplify-js-app@1.0.0 build /private/tmp/vanilla-auth
	> webpack
	
	Hash: 8c4a99b047ffd921fe7b
	Version: webpack 4.41.6
	Time: 1117ms
	Built at: 02/11/2020 10:18:20 AM
	            Asset      Size   Chunks             Chunk Names
	Amplify.bundle.js  1.17 MiB  Amplify  [emitted]  Amplify
	       index.html   1.5 KiB           [emitted]
	Entrypoint Amplify = Amplify.bundle.js
	[0] fs (ignored) 15 bytes {Amplify} [built]
	[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {Amplify} [built]
	[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {Amplify} [built]
	[./src/Amplify.js] 117 bytes {Amplify} [built]
	[./src/aws-exports.js] 794 bytes {Amplify} [built]
	    + 167 hidden modules
	```

**Comment by martinlytics** [comment]
Awesome, @ericclemmons ! This appears exactly what we need. I'll give it a shot and let you know how it goes.

**Comment by martinlytics** [comment]
@ericclemmons Just want to let you know that the solution you suggested above worked well for our project. Thanks again!

**Comment by ericclemmons** [comment]
@martinlytics That's really awesome news!

I'll keep this issue open because we should address the standalone issues problem formally:

- [unpkg.com](https://unpkg.com/)-friendly standalone bundles that work with `<script>` tags.
- Documentation for standalone builds (like in this thread).
