### ISSUE TITLE
Soak test : Left app running overnight and got TypeError undefinded is not an object

### ISSUE THREAD

**Issue by jitendra-koodo** [aws-amplify/amplify-js#4835]
To Reproduce
https://aws-amplify.github.io/docs/js/start?ref=amplify-rn-btn&platform=react-native

Followed this guide and left it running...

*Additional context
Windows 10

"dependencies": {
"aws-amplify": "^2.2.2",
"aws-amplify-react-native": "^3.2.0",
"react": "16.9.0",
"react-native": "0.61.5"
},

![soak_test](https://user-images.githubusercontent.com/47494921/73716556-56058180-473d-11ea-898e-1d4786772c5b.jpg)

**Comment by amhinson** [comment]
Hey @jitendra-koodo, I've got a few follow-up questions:

- It looks like this happened with a debug build. Would you be able to reproduce this with a production build as well, just to confirm?
- Could you post some sample code or a repo we could try to reproduce the issue on our side as well?
