### ISSUE TITLE
Allow external AppSync API to use DataStore

### ISSUE THREAD

**Issue by SebSchwartz** [aws-amplify/amplify-js#4841]
**Is your feature request related to a problem? Please describe.**
We are using an external appsync api and want to use it with Datastore (since appsync offline mode doesn't seems to be updated any day soon with the new Apollo client version -> https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/448). But it's right now not possible to do it with this configuration. I cannot generate the codegen models that are required by Datastore.

**Describe the solution you'd like**
Being able to use datastore even with an external appsync api. It may require some schema configuration to be compatible with models.

**Describe alternatives you've considered**
Something easy to add and manage an existing appsync api with amplify (even if it means, it cannot be managed with the previous stuffs). For example: importing an entire existing appsync api inside amplify (with existing datasources, existing resolvers,...).

**Additional context**
We have started using amplify in Sept 2018 and at that time, there was no good support of AWS AppSync. So we created our appsync application with a serverless stack using the good (serverless-appsync-plugin). We are using a lambda function as datasource (based on https://github.com/aws-samples/aws-appsync-rds-aurora-sample). The lambda was improved a lot since then and it is dealing with multi tenant datas based on multiple field. Our DB is an Aurora Serverless inside a vpc so is the lambda. Everything is created in the serverless with some cloudformation too (DB, Network, appsync, lambda,...). This is said to explain more our actual setting.
We are not afraid of some refactoring to allow to use the Datastore but off-course we are not willing to refactor everything ;)

**Comment by ashika01** [comment]
@SebSchwartz : Thanks for opening this FR and understand your use case. Right now, Datastore relies on having DynamoDB as backend datasource as well as on presence of some specific queries, mutation, subscriptions generated by amplify cli codegen/modelgen.

It is not possible to use aurora at this point because of the delatsync we do for Datastore. Some work need to be done from internal sister teams to support this. We will close this request and pool in the information. 

We are still would like to keep this open, feel free to comment it here and we will leave it open :)

**Comment by SebSchwartz** [comment]
And is this possible to use it with a lambda resolver? Or only with simple dynamo resolver?

If I want to change almost all resolvers and datasource to dynamo but I still want to have some lambda function for some resolvers as they are more advanced, will Datastore be compatible with it? Or it will only work with other simple dynamo datasource and ignore those?

Thanks,
Sebastien

**Comment by TLaue** [comment]
@ashika01 I would really appretiate if the Amplify Data Store could be used with an external AppSync Api even if the supported backend data sources would be limited to DynamoDB (we are using no other datasource in our project). 

+ 100
