### ISSUE TITLE
S3Image component aws-amplify-react not able to distinguish a successful upload 

### ISSUE THREAD

**Issue by dudenamedjune** [aws-amplify/amplify-js#4847]
**Describe the bug**
I'm not sure this is a bug or if this is the expected behavior. If it is the latter I can open a feature request. 

**To Reproduce**
Refresh the page and you can see that onLoad has been called due to the image being loaded. 

1. Consume <S3Image />
2. pass the prop onLoad 
3. notice on component mount onLoad is called

**Expected behavior**
I would expect the behavior to differentiate between a successful load of S3Images vs the transparent initial src loaded in the image tag.

**Comment by jordanranz** [comment]
Closing this issue as the PR for this was merged :) Please open a new issue if there are any related questions or concerns.
