### ISSUE TITLE
Convert an oAuth/cognito account to a cognito/oAuth account

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-js#4849]
If a user has already registered with a mail address, but then uses Login with Facebook, cognito will create a separate account. 
This means that the data will be lost. 

Is it possible to change this?
Like this:
https://firebase.google.com/docs/auth/web/anonymous-auth?hl=de#convert-an-anonymous-account-to-a-permanent-account

**Comment by sammartinez** [comment]
@davidbiller Amplify acts as a pass through to Amazon Cognito when we do registration (Sign In, Sign Up, etc.) or Hosted UI logins. Please look to ask this question to Amazon Cognito via their [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=173) as this seems to be directly related to Amazon Cognito.
