### ISSUE TITLE
Quasar Framework SSR Support

### ISSUE THREAD

**Issue by marcelo-gondim** [aws-amplify/amplify-js#4851]
Amplify CLI and Quasar Framework projects should support Server Side Rendering. For SEO purposes we need SSR. I would prefer to use the Amplify tooling so I do not have to mix and match various tool chains.

[https://github.com/quasarframework/quasar](https://github.com/quasarframework/quasar)

Thanks

**Comment by ericclemmons** [comment]
SSR support has been addressed as part of #6146!

Please see my synopsis on changes here: https://github.com/aws-amplify/amplify-js/issues/5435#issuecomment-692990722

I haven't personally tested Quasar, but `withSSRContext` (and underlying changes to work for SSR) apply to Next.js, Gatsby, Nuxt.js, and several others.

If your experience differs, please open a new issue with a specific example(s) so we can better address those use-cases 🙏
