### ISSUE TITLE
Authentication Federated SignIn stuck at parsing call back URL

### ISSUE THREAD

**Issue by qmau94** [aws-amplify/amplify-js#4854]
**Describe the bug**
When using the Hosted UI to perform the federated sign in, the authenticate code stuck in parsing call back URL when redirecting to the App. This only happens to the iOS platform.

**To Reproduce**

1. Call Auth.federatedSignIn({ provider });
2. Sign in to social account
3. Redirect back to the mobile app
4. App stuck at "parsingCallbackUrl"

**Expected behavior**
Authentication should proceed to use the authentication code to get the returned user info and token.

<details>
  <summary><strong>Environment</strong></summary>

```
  System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 20.46 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox Developer Edition: 71.0
    Safari: 12.1.1
  npmPackages:
    @babel/core: ^7.6.2 => 7.8.3 
    @babel/plugin-external-helpers: ^7.8.3 => 7.8.3 
    @babel/runtime: ^7.6.2 => 7.8.3 
    @react-native-community/async-storage: ^1.7.1 => 1.7.1 
    @react-native-community/eslint-config: ^0.0.5 => 0.0.5 
    @react-native-community/masked-view: ^0.1.6 => 0.1.6 
    @react-navigation/bottom-tabs: ^5.0.0-alpha.37 => 5.0.0-alpha.37 
    @react-navigation/core: ^5.0.0-alpha.35 => 5.0.0-alpha.35 
    @react-navigation/drawer: ^5.0.0-alpha.41 => 5.0.0-alpha.41 
    @react-navigation/native: ^5.0.0-alpha.27 => 5.0.0-alpha.27 
    @react-navigation/stack: ^5.0.0-alpha.61 => 5.0.0-alpha.61 
    aws-amplify: ^2.2.2 => 2.2.2 
    aws-amplify-react-native: ^3.2.0 => 3.2.0 
    babel-eslint: ^10.0.3 => 10.0.3 
    babel-jest: ^24.9.0 => 24.9.0 
    babel-preset-react-native: ^4.0.1 => 4.0.1 
    eslint: ^6.8.0 => 6.8.0 
    eslint-config-airbnb: ^18.0.1 => 18.0.1 
    eslint-config-prettier: ^6.9.0 => 6.9.0 
    eslint-plugin-import: ^2.20.0 => 2.20.0 
    eslint-plugin-jsx-a11y: ^6.2.3 => 6.2.3 
    eslint-plugin-prettier: ^3.1.2 => 3.1.2 
    eslint-plugin-react: ^7.18.0 => 7.18.0 
    eslint-plugin-react-hooks: ^2.3.0 => 2.3.0 
    eslint-plugin-react-native: ^3.8.1 => 3.8.1 
    husky: ^4.0.10 => 4.0.10 
    i18next: ^19.0.3 => 19.0.3 
    jest: ^24.9.0 => 24.9.0 
    metro-config: ^0.58.0 => 0.58.0 
    metro-react-native-babel-preset: ^0.56.0 => 0.56.4 
    prettier: ^1.19.1 => 1.19.1 
    prop-types: ^15.7.2 => 15.7.2 
    react: 16.9.0 => 16.9.0 
    react-i18next: ^11.3.1 => 11.3.1 
    react-native: 0.61.5 => 0.61.5 
    react-native-date-picker: ^2.7.5 => 2.7.5 
    react-native-device-info: ^5.4.1 => 5.4.1 
    react-native-elements: ^1.2.7 => 1.2.7 
    react-native-gesture-handler: ^1.5.3 => 1.5.3 
    react-native-image-picker: ^2.2.0 => 2.2.0 
    react-native-maps: 0.26.1 => 0.26.1 
    react-native-picker-select: ^6.3.4 => 6.3.4 
    react-native-reanimated: ^1.7.0 => 1.7.0 
    react-native-safe-area-context: ^0.6.2 => 0.6.2 
    react-native-screens: ^2.0.0-alpha.29 => 2.0.0-alpha.29 
    react-native-svg: ^11.0.1 => 11.0.1 
    react-native-svg-transformer: ^0.14.3 => 0.14.3 
    react-native-vector-icons: ^6.6.0 => 6.6.0 
    react-test-renderer: 16.9.0 => 16.9.0 
  npmGlobalPackages:
    @aws-amplify/cli: 4.13.1
    aglio: 2.3.0
    apidoc: 0.17.7
    bootprint: 1.0.2
    create-react-app: 3.3.1
    docusaurus-init: 1.0.2
    dynamodb-admin: 3.2.0
    elasticsearch: 15.1.1
    eslint: 5.2.0
    expo-cli: 3.11.7
    gatsby-cli: 2.7.2
    generator-keystone: 0.5.1
    ghost-cli: 1.5.2
    gitbook-cli: 2.3.2
    google-translate-api: 2.3.0
    gulp: 3.9.1
    hexo-cli: 1.1.0
    localtunnel: 1.9.1
    n: 4.1.0
    neovim: 4.5.0
    nodemon: 1.18.4
    npm: 6.4.1
    pm2: 3.0.0
    react-devtools: 4.4.0
    react-native-cli: 2.0.1
    react-static: 5.9.5
    serverless-dynamodb-local: 0.2.30
    serverless-offline: 3.23.1
    serverless: 1.27.3
    strapi: 3.0.0-alpha.25.2
    terminalizer: 0.6.1
    yarn: 1.16.0
    yo: 2.0.5
```

</details>

**Smartphone (please complete the following information):**

- Device: iphone11
- OS: iOS 13.1
- Browser: safari

**Sample code**
https://aws-amplify.github.io/docs/js/authentication#oauth-and-hosted-ui
I used the same code in the example above 

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**
```
 LOG  [DEBUG] 16:30.124 urlListener - urlListener {"url": null}
 LOG  [DEBUG] 16:30.124 Hub - Dispatching to auth with  {"data": {"url": null}, "event": "parsingCallbackUrl", "message": "The callback url is being parsed"}
 LOG  [DEBUG] 16:30.125 Analytics - on hub capsule auth {"data": {"url": null}, "event": "parsingCallbackUrl", "message": "The callback url is being parsed"}
 LOG  [DEBUG] 16:30.125 Hub - Dispatching to auth with  {"data": {"url": null}, "event": "parsingCallbackUrl", "message": "The callback url is being parsed"}
 LOG  [DEBUG] 16:30.125 Hub - Dispatching to auth with  {"data": {"url": null}, "event": "parsingCallbackUrl", "message": "The callback url is being parsed"}
```

**Comment by qmau94** [comment]
https://facebook.github.io/react-native/docs/linking
I forgot to config the React Native Linking part and after fixing it, it worked like a charm. Sorry for the

**Comment by rahulje9** [comment]
@qmau94 can you please help me with the linking part?

**Comment by rahulje9** [comment]
@qmau94 In my case my app is not getting redirected back, can you please help me with this. Also, I haven't done the linking part too.

**Comment by qmau94** [comment]
@rahulje9  make sure you follow the instruction from amplify webpage and everything will be fine. In case you haven't done the linking part, amplify will not able to redirect to your app.

**Comment by rahulje9** [comment]
> @rahulje9 In case you haven't done the linking part, amplify will not able to redirect to your app. Make sure you follow the instruction from amplify webpage and everything will be fine.

Hi it was due to that and I had fixed that, now it's a new error
`signIn_failure [NotAuthorizedException: Identity pool - * poolid * does not 
have identity providers configured.]`

**Comment by timorss** [comment]
> @qmau94 In my case my app is not getting redirected back, can you please help me with this. Also, I haven't done the linking part too.

can you show what you did?
It works for me on android, but not on ios.

**Comment by timorss** [comment]
ok i added // iOS 9.x or newer
#import <React/RCTLinkingManager.h>

- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}

like mentioned in https://facebook.github.io/react-native/docs/linking

**Comment by jsnavarroc** [comment]
**I have the same situation when it makes sign-out in the _parsingCallbackUrl_ event:**
```
payload:{
   data: {url: 'app://SignIn/'}
  event: "parsingCallbackUrl"
  message: "The callback url is being parsed"
}
```
In React Native, I don't know what configuration I need to set because inside the aws-exports I have this:
```
. . . {
.
.
.
   "redirectSignIn": "app://SignIn/",
   "redirectSignOut": "app://SignIn/",
}
```
And the sign-in is working, but when trying to make a sign-out, not working. And the deep link SignIn is a screen where I have the function where checks all the events, is where I handle the status of the component.

If could you help me I'll be grateful to you, thanks.

**Comment by VanDinh18** [comment]
@qmau94 i have the same issue. i followed docs https://facebook.github.io/react-native/docs/linking
`// iOS 9.x or newer
#import <React/RCTLinkingManager.h>

(BOOL)application:(UIApplication *)application
openURL:(NSURL *)url
options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
return [RCTLinkingManager application:application openURL:url options:options];
}`
it works on Android, but not IOS

**Comment by sneas** [comment]
Hey @qmau94, I'm new to React Native and struggling with a similar issue. For some reason, adding

```
// iOS 9.x or newer
#import <React/RCTLinkingManager.h>

- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}
```

into my `AppDelegate.mm` doesn't take any effect. Do I need to do something else?

**Comment by tannerabread** [comment]
@sneas if you are running newer version of React Native, make sure you include the import and other code _outside_ of the `#if RCT_NEW_ARCH_ENABLED` statement

**Comment by franky358** [comment]
For anyone else having trouble with urlListener {"url": null} 
Make sure your are adding 

`- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}`

inside `@implementation AppDelegate` above `@end`:

Thanks @tannerabread
