### ISSUE TITLE
Web app integrates with IoT got websocket connection error and 'AMQJS0007E Socket error:undefined'

### ISSUE THREAD

**Issue by kaaaren** [aws-amplify/amplify-js#4860]
**Describe the bug**
I am working on a web demo app to create connection with AWS IoT using Amplify. I had simply added auth config and subscribed to topic. I basically followed the [PubSub instruction](https://aws-amplify.github.io/docs/js/pubsub) and instrucion of a [sample app](https://medium.com/serverlessguru/serverless-real-time-reactjs-app-aws-iot-mqtt-17d023954045) to set up aws services:
1)create IoT thing, create cert, attach policy to cert
2)create cognito identity pool and attach policy to cognito identity id

I'm getting websocket connection error and also 'AMQJS0007E Socket error:undefined.` error

**Sample code**
const AWS_CONFIGS = {
  identityPoolId: 'us-east-1:xxxxx',
  host: 'xxxxxx.iot.us-east-1.amazonaws.com',
  region: 'us-east-1',
};

Amplify.configure({
  Auth: {
    identityPoolId: AWS_CONFIGS.identityPoolId,
    region: AWS_CONFIGS.region,
  }
});

 Amplify.addPluggable(new AWSIoTProvider({
    aws_pubsub_region: AWS_CONFIGS.region,
    aws_pubsub_endpoint: `wss://${AWS_CONFIGS.host}.iot.${AWS_CONFIGS.region}.amazonaws.com/mqtt`,
  }));

Amplify.PubSub.subscribe('MyIotThing').subscribe({
      next: (data: string) => console.log('IOT Message received', data),
      error: (error: string) => console.error("IOT error", error),
      close: () =>  console.log('IOT Done')
    });

**Error details**
vendors.undefined.js:193277 WebSocket connection to 'wss://xxxxx.com.iot.us-east-1.amazonaws.com/mqtt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=xxxxxxxxx%2F20200207%2Fus-east-1%2Fiotdevicegateway%2Faws4_request&X-Amz-Date=20200207T003719Z&X-Amz-SignedHeaders=host&X-Amz-Signature=xxxxxX-Amz-Security-Token=xxxxx' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED

And error in subscribe to topic:
invocationContext: undefined
errorCode: 7
errorMessage: "AMQJS0007E Socket error:undefined."

**Comment by elorzafe** [comment]
@kaaaren thanks for your feedback, I haven't tried that guide you mention, can you try the [following](https://aws-amplify.github.io/docs/js/pubsub)

 I think the problem is that PubSub is not configured on Amplify

**Comment by kaaaren** [comment]
Thanks elorzafe for helping out! There is a mis-config in my code- since I have host as 'xxxxxx.iot.us-east-1.amazonaws.com', aws_pubsub_endpoint can just be wss://${AWS_CONFIGS.host}/mqtt

**Comment by justinjoyn** [comment]
Any update on this? I always get this error when trying to subscribe to a topic after internet is restored.
``` 
     "errorCode":7,
     "errorMessage":"AMQJS0007E Socket error:undefined."
```
