### ISSUE TITLE
How do I fork the package aws-amplify-react?

### ISSUE THREAD

**Issue by brianarpie** [aws-amplify/amplify-js#4863]
I want to fork the aws-amplify-react package to modify some of the components.

How do I fork just that package and include it in my project? I'm confused

**Comment by sammartinez** [comment]
@brianarpie There is currently not a way just to fork the `aws-amplify-react` package, you'll will need to fork the entire repo and make the changes needed inside of the `aws-amplify-react` package. However, I am curious on what changes you are looking for. Could you provide some insights into what you are looking to change? Im curious of [UI Component Refactor](https://github.com/aws-amplify/amplify-js/issues/3279) will help you. Please let us know.

**Comment by brianarpie** [comment]
@sammartinez thanks for the reply! Right now I have "aws-amplify" and "aws-amplify-react" entries in my package.json. If I fork "aws-amplify" and replace the package.json to point to my forked git repo, how do I correct the "aws-amplify-react" entry so that I can still import components, e.g. `import { SignIn } from 'aws-amplify-react';`?

I just want to modify the link in the SignIn component that says "No account? Create account". I'm not sure if the issue you referenced would solve that.

Thanks

**Comment by jordanranz** [comment]
Hey @brianarpie, what are you trying to change that link to? With the [new UI Component library](https://docs.amplify.aws/ui/auth/authenticator?framework=react#sign-in) @sammartinez mentioned above this may be possible depending on what you are trying to change the link to.

**Comment by brianarpie** [comment]
@jordanranz thanks for replying. I've ultimately stepped away from aws-amplify-react and am using aws-amplify with my own custom forms now. Thanks anyways!
