### ISSUE TITLE
Stripe recurrent payment integration in Amplify

### ISSUE THREAD

**Issue by docduo** [aws-amplify/amplify-js#4868]
Dear Amplify contributors,

Is it planned to have a feature to add payment to Amplify Auth form or it is out of scope and we should consider to implement this ourselves ?

<img width="754" alt="Capture d’écran 2020-02-08 à 16 15 19" src="https://user-images.githubusercontent.com/56165819/74087601-3bf5d700-4a8e-11ea-9a20-3580ecd6c9ed.png">

Best, A.

**Comment by docduo** [comment]
I found a solution 👍 no need for that feature request. A.

**Comment by nouredu** [comment]
What was the solution @docduo ?

**Comment by docduo** [comment]
@nouredu to use Stripe API...
