### ISSUE TITLE
In aws-amplify-react-native, "Sign In," "Sign Up," and "Resend code" all red-screen instead of disabling the submit button if required elements are missing

### ISSUE THREAD

**Issue by dantasfiles** [aws-amplify/amplify-js#4870]
**Describe the bug**
In aws-amplify-react-native, `Sign In`, `Sign Up`, and `Resend code` all RedBox error instead of disabling the submit button if required elements are missing

**To Reproduce**
- Setup Amplify for React Native with default authentication
- Use `withAuthenticator` HOC in `App.js`
```
const App = withAuthenticator(Home);
```
1) Click `Sign In` button without entering anything
2) Click `Sign Up` link, then `Sign Up` button without entering anything
3) Click `Sign Up` link, then `Confirm a code` link, then `Resend code` button without entering anything

In all three cases, for different reasons, the app red-screens with an `[ERROR] AuthError - Username cannot be empty`

**Possible Source**
1) I believe the **`Sign In`** red-screen occurs because the `disabled` logic doesn't look correct
https://github.com/aws-amplify/amplify-js/blob/87f4c0862a5cd4a6392aad8395c6ec258bd73220/packages/aws-amplify-react-native/src/Auth/SignIn.js#L82
It should probably be something like `!this.getUsernameFromInput() || !this.state.password`

2) I believe the **`Sign Up`** red-screen occurs because the `for` loop in the  `isValid` function doesn't look right
https://github.com/aws-amplify/amplify-js/blob/87f4c0862a5cd4a6392aad8395c6ec258bd73220/packages/aws-amplify-react-native/src/Auth/SignUp.js#L69
It should probably be something like `for (const el of this.signUpFields)`

3) I believe the **`Resend Code`** red-screen occurs because the `Resend Code` button is a `LinkCell` component that is disabled if the user has not yet entered a username
https://github.com/aws-amplify/amplify-js/blob/87f4c0862a5cd4a6392aad8395c6ec258bd73220/packages/aws-amplify-react-native/src/Auth/ConfirmSignUp.js#L98
But `LinkCell` components don't pass their `disabled` prop to the `TouchableHighlight` inside.
[amplify-js/packages/aws-amplify-react-native/src/AmplifyUI.js](https://github.com/aws-amplify/amplify-js/blob/87f4c0862a5cd4a6392aad8395c6ec258bd73220/packages/aws-amplify-react-native/src/AmplifyUI.js#L124)
`  <TouchableHighlight onPress={props.onPress} underlayColor={linkUnderlayColor}>`
So the `TouchableHighlight` component is never disabled and the app red-screens.

**Expected behavior**
The `Sign In`, `Sign Up` and `Resend code` buttons should be disabled if required fields are missing.

**Screenshots**
 ![Screenshot_20200208-165545](https://user-images.githubusercontent.com/9329599/74092743-313f4000-4a96-11ea-9de6-9277e632f791.png)

<details>
  <summary><strong>Environment</strong></summary>

```
  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 13.8.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    amazon-cognito-identity-js: ^3.2.4 => 3.2.4
    aws-amplify: ^2.2.4 => 2.2.4
    aws-amplify-react-native: ^3.2.2 => 3.2.2
    babel-jest: ^24.9.0 => 24.9.0
    eslint: ^6.5.1 => 6.8.0
    jest: ^24.9.0 => 24.9.0
    metro-react-native-babel-preset: ^0.56.0 => 0.56.4
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
    react-test-renderer: 16.9.0 => 16.9.0
```

</details>

**Smartphone (please complete the following information):**
- OS: Android 10

**Comment by preethypt** [comment]
Any option to customize the error message which was shown in the UI using aws-amplify-react-native?

**Comment by nihp** [comment]
Any option to customize the error message using aws-amplify-react-native?

**Comment by Saqlain-Piecyfer** [comment]
This error is still happening after the update, empty username/password throws exception

**Comment by amhinson** [comment]
@Saqlain-Piecyfer The red screen is just coming from [the use](https://github.com/aws-amplify/amplify-js/blob/master/packages/core/src/Logger/ConsoleLogger.ts#L82) of `console.error` when `signIn` is not successful to make it more visible, but there isn't actually an error happening.

Also, the `SignIn` button isn't disabled because it still needs to handle the use-case of passwordless sign in.

With that said, this is something we are looking to improve in the future, so your feedback is absolutely welcomed here.
