### ISSUE TITLE
Socket closed (subscription)

### ISSUE THREAD

**Issue by vitali-yablonski** [aws-amplify/amplify-js#4871]
**Describe the bug**

I have created a react & redux application with aws-amplify version 1.1.29 and graphql version 0.13.0. I am using subscription, and  It keeps breaking after 25-30 mins when user does not act with application. 

```
error:
    errorMessage: "AMQJS0008I Socket closed."
    reconnect: undefined
```

Can I somehow reconnect? If yes, then how do it properly?

**Comment by elorzafe** [comment]
@vitali-yablonski what are you using? Can you share your `aws-exports.js` file (feel free to mask the endpoints)?

**Comment by vitali-yablonski** [comment]
Hi @elorzafe, 
I am not using aws-amplify/cli. App has configuration like this

import Amplify from 'aws-amplify';

Amplify.configure({

    Auth: {
        identityPoolId: 'my_identityPoolId',
        region: 'us-west-2',
        userPoolId: 'my_userPoolId',
        userPoolWebClientId: 'my_userPoolWebClientId',
        mandatorySignIn: true,
        oauth: cognitoHostedoauth,
    },

    Api: {
        domain: 'my_domain',
    },

    aws_appsync_graphqlEndpoint: 'my_aws_appsync_graphqlEndpoint',
    aws_appsync_region: 'us-west-2',
    aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
    aws_appsync_apiKey: 'my_aws_appsync_apiKey',

});

**Comment by jordanranz** [comment]
Hey @vitali-yablonski, could you try using the latest version of `aws-amplify`. There has been some work done on the reconnections and timeouts in the latest.
