### ISSUE TITLE
DataStore TypeScript Typing Issue

### ISSUE THREAD

**Issue by seang96** [aws-amplify/amplify-js#4878]
**Describe the bug**
DataStoreConfig type is incorrect due to it missing the information from aws-exports. Since the type is missing this information it will not sync to the backend. The code segment can be found below

https://github.com/aws-amplify/amplify-js/blob/a047ce73abe98c3bf82e888c3afb4d2f911805f3/packages/datastore/src/types.ts#L356-L367

**To Reproduce**
Load any TypeScript project with DataStore

**Expected behavior**
The typing to include aws-exports in order for it to add the configurations for the backend.

**Additional context**

Quick Fix:
Create a .d.ts file and include the code below:
```
// @ts-ignore
Datastore.configure({...awsconfig});
```

**Comment by sammartinez** [comment]
@seang96 What version of Typescript are you using? We do have our current TypeScript support at [3.6.4](https://github.com/aws-amplify/amplify-js/blob/master/package.json#L74). Can you verify if this version of TypeScript works for you?

**Comment by seang96** [comment]
@sammartinez I've been doing 3.7.5. I still get the error:
"TS2559: Type '{ "aws_project_region": string; "aws_cognito_identity_pool_id": string; "aws_cognito_region": string; "aws_user_pools_id": string; "aws_user_pools_web_client_id": string; "oauth": {}; "aws_appsync_graphqlEndpoint": string; "aws_appsync_region": string; "aws_appsync_authenticationType": string; "aws_cloud_logic_custo...' has no properties in common with type 'DataStoreConfig'."

The type is incorrect in DataStoreConfig since it misses those properties.

**Comment by ashika01** [comment]
@seang96 : Hi, thank you for bringing this up. So the right way to configure would be

```ts
import awsconfig from "./aws-exports";
import Amplify from "@aws-amplify/core";
import { DataStore } from "@aws-amplify/datastore";

// This is the top level amplify config 
Amplify.configure(awsconfig);

DataStore.configure({
  // DataStore specific config
});
```

For Reference: 
https://aws-amplify.github.io/docs/js/datastore#connect-your-app
https://aws-amplify.github.io/docs/js/datastore#config

**Comment by victoryurkin** [comment]
Was this resolved? I tried a number of ways (including the one mentioned above) to configure DataStore to sync with remote, but getting:
`Possible Unhandled Promise Rejection (id: 20):
TypeError: null is not an object (evaluating '_b.aws_appsync_region')`

**Comment by valtrem** [comment]
I have a similar problem using DataStore with Typescript. 

Everything works fine in dev environement.

But when  building for production Amplify.configure(awsconfig) is not applied and therefore the app won't sync with the backend.

A quick fix
```
DataStore.configure({
  aws_appsync_graphqlEndpoint:
    "https://l2yacdp64zev7ol3hvkcniiusa.appsync-api.us-east-1.amazonaws.com/graphql"
});
```
