### ISSUE TITLE
Storage.get for protected failing on retrieving other user

### ISSUE THREAD

**Issue by 24jr** [aws-amplify/amplify-js#4894]
I've got a protected storage setup for users to add and get photos. I have had a user be able to add and get their own photo successfully using 
```
Storage.get(key, { level: 'protected' })
    .then(result => console.log(result))
    .catch(err => console.log(err));
```
but when I login as a different user and use the suggested

```
Storage.get(key, { 
    level: 'protected', 
    identityId: message.fromUserID // the identityId of that user
})
.then(result => console.log(result))
.catch(err => console.log(err));
```
I get the URL back which just says 

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
protected/315adace-3d50-4ecf-9eb1-88b686335da3/1581480835371testphoto
</Key>
<RequestId>503576257A026AE7</RequestId>
<HostId>
7V6bYrbtYrdFDLv+mQZB2VzmF9SKtCZoROQ0SMHZjPXVywDP41u1Ia6OGH8DwWrHwKh9WINIPBQ=
</HostId>
</Error>
```
Im using the other users Cognito sub Id there which is definitely what its asking for there or at least idk any other id it would want there. 

I see it shows protected/315adace-3d50-4ecf-9eb1-88b686335da3/1581480835371testphoto in this error but when I go onto s3 and click on the protected folder the next thing is us-east-1:7e2cfeeb-b1dc-4039-a9b0-bf3757d71750 and then 1581480835371testphoto so idk if instead of the userID I need the region and whatever that other number is. 

Let me know what I'm missing here or if there's a potential issue with it. Thanks!

**Comment by elorzafe** [comment]
@24jr that sub is from federated identities not user pools. Is the same identity id that is part of AWS  Credentials.

**Comment by 24jr** [comment]
You're right. I realized many other people had this problem too...and don't really have a solution #1847 and #2203 didn't mean to post duplicate
