### ISSUE TITLE
Cannot signIn using USER_SRP_AUTH, documentation/defaults are misleading

### ISSUE THREAD

**Issue by bodokaiser** [aws-amplify/amplify-js#4900]
**Describe the bug**
The [documentation](https://aws-amplify.github.io/docs/js/authentication#manual-setup) states that the default `authenticationFlowType` is `USER_SRP_AUTH`, however, it is not possible to sign-in using `USER_SRP_AUTH` as this will raise a `NotAuthorizedException` regardless if the email and password combination is correct or not.

**To Reproduce**

1. Create a new user pool with email address for sign-in
2. Create an app client with `USER_SRP_AUTH` enabled and uncheck generate a client secret
3. Use `Auth.configure({ ... })` to pass the user pool configuration
4. Use `await Auth.signIn(email, password)` and get `NotAuthorizedException`

```typescript
import Auth from "@aws-amplify/auth"

Auth.configure({
  userPoolId: "eu-central-1_XX",
  userPoolWebClientId: "XX",
  authenticationFlowType: "USER_SRP_AUTH",
})

Auth.signIn("my email", "my password").then(...)
```

```javascript
{
  // ...
  "dependencies": {
    "@aws-amplify/auth": "^2.1.5",
    "@aws-amplify/core": "^2.2.4",
    //...
  },
 // ...
}
```

![](https://aws-amplify.github.io/docs/js/images/cognito_user_pool_settings.png)

**Expected behavior** 

No error after sign-in with correct credentials. Signed-in user should be available via `Auth.currentAuthenticatedUser()`

**Present workaround**

Change `authenticationFlowType` to `USER_PASSWORD_AUTH` and create new app client in the AWS cognito user pool interface that allows `USER_PASSWORD_AUTH`.

**Suggested fix**

It appears to me that `USER_SRP_AUTH` is currently not supported by amplify (or at least not for the eu-central-1 region?), however, the documentation suggests that it is supported which is misleading.

**Comment by michaelcuneo** [comment]
I have the same issue, I have had to force the User Pool devices to use USER_PASSWORD_AUTH for now, my entire production project was broken after an update and it took me a few days to realise that it wasn't just me.

**Comment by elorzafe** [comment]
@bodokaiser `USER_SRP_AUTH` is supported on `eu-central-1` I created a UserPool with the same configuration as you mentioned. Can you give more details? Did you enable case insensitivity?

**Comment by bodokaiser** [comment]
@elorzafe Where do I enable case-insensitivity? Which details would be of help to you? I could send you my cognito user pool id's on a private channel.

**Comment by elorzafe** [comment]
@bodokaiser for new Userpools you can enable case-insensitivity when creating a new one on Cognito console, but that setting is not allowed to be changed after its creation. 

Can you try creating the userpool with amplify cli?

**Comment by bodokaiser** [comment]
@elorzafe Signing-in using the amplify-created userpool indeed uses `USER_SRP_AUTH`.

It's a good insight of yours, to compare the settings of the amplify userpool and app client and the one I created in the web console (see attachments).

I will do some more experiments tomorrow. Let me know if you have any further remarks.

<img width="1440" alt="Screen Shot 2020-02-18 at 20 00 41" src="https://user-images.githubusercontent.com/1780466/74768719-59deeb00-5289-11ea-8600-fbc5cb846488.png">

<img width="1440" alt="Screen Shot 2020-02-18 at 19 59 26" src="https://user-images.githubusercontent.com/1780466/74768620-2bf9a680-5289-11ea-80c7-662aa4c8f8ca.png">

**Comment by bodokaiser** [comment]
@elorzafe I created a new user pool from the aws console and am not able to reproduce to the issues. That said I am still not able to use `USER_SRP_AUTH` with the user pool I initially created. There might be some internal state in that user pool that breaks the use of `USER_SRP_AUTH`.

Maybe someone from the AWS Cognito backend team would like to check the internal state of said user pool? Otherwise, I think we can close this issue as it is not related to amplify.

**Comment by elorzafe** [comment]
@bodokaiser I agree that this is something related to the service, I will close this issue but feel free to open a new one if you experience this again.

Meanwhile you can cut a ticket on [AWS Support](https://console.aws.amazon.com/support/home?#/)

**Comment by khanson98** [comment]
This issue exists for me, I have remade the User Pool multiple times and can't determine a particular cause

**Comment by craig-z** [comment]
Ran into this issue where Amplify would not authenticate with a user pool that we created using the web console. Created a new user pool using the aws cli (`aws cognito-idp create-user-pool`) and THEN it worked.
