### ISSUE TITLE
How to resend verification code while verifying/updating email/phone  attribute in aws-amplify/ aws-cognito?

### ISSUE THREAD

**Issue by Luckygirlllll** [aws-amplify/amplify-js#4908]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
How to resend verification code while verifying/updating email/phone attribute in aws-amplify/ aws-cognito, I'm using this code, to verify email/phone:

`const responce = await Auth.verifyCurrentUserAttributeSubmit("email", confirmationCode)`
Is there a possibility to resend the code?

**Comment by manueliglesias** [comment]
Hi @Luckygirlllll 

I've been digging around and found this related issue #1614 and feature request #2010

Looks like at the moment the way to have the code sent again is to try the `updateUserAttribute` operation again.

Please let us know if this works for you

**Comment by Luckygirlllll** [comment]
@manueliglesias I have already found a solution I used `verifyCurrentUserAttribute()` method to resend a code.

`updateUserAttributes` doesn't resend code to the same email/phone number.

**Comment by manueliglesias** [comment]
@Luckygirlllll Thank you for posting your solution for other users to see!

**Comment by richmondu** [comment]
This is not applicable to MFA scenario so please remove link to feature 2010.

**Comment by novusli** [comment]
Don't know if this would help. This actually solved my problem: 
```
import { Auth } from 'aws-amplify';

async function resendConfirmationCode() {
    try {
        await Auth.resendSignUp(username);
        console.log('code resent successfully');
    } catch (err) {
        console.log('error resending code: ', err);
    }
}
```

Source Link: https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js#re-send-confirmation-code

**Comment by koko67** [comment]
@novusli according to your answer, what should be the status of the user in the Pool in Cognito NEW_PASSWORD_REQUIRED or CONFIRMED?
Because I tried with both cases without success.

**Comment by deekshith4450** [comment]
> Don't know if this would help. This actually solved my problem:
> 
> ```
> import { Auth } from 'aws-amplify';
> 
> async function resendConfirmationCode() {
>     try {
>         await Auth.resendSignUp(username);
>         console.log('code resent successfully');
>     } catch (err) {
>         console.log('error resending code: ', err);
>     }
> }
> ```
> 
> Source Link: https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js#re-send-confirmation-code

If the user logged in or authenticated, then this will throw an error.

Object {
  "code": "InvalidParameterException",
  "message": "User is already confirmed.",
  "name": "InvalidParameterException",
}

**Comment by peter-greekbase** [comment]
Hello, my question is more related to which Auth method I would use to specify to differentiate sending a phone or e-mail verification in the case the user would like to specify the method of verification. Does anyone know how an e-mail could be sent if desired, or a phone verification if desired, based on say some attribute? What method exactly calls this verification code to be sent, and how might it customised?

**Comment by KristianLake** [comment]
Hi, Can you resend sign up using email instead of username somehow?
