### ISSUE TITLE
React native subscriptions not working

### ISSUE THREAD

**Issue by dabit3** [aws-amplify/amplify-js#4910]
**Describe the bug**
When trying to initialize a subscription on React Native, error is thrown 

![Screen Shot 2020-02-13 at 1 32 17 PM](https://user-images.githubusercontent.com/1857282/74480166-471d7e00-4e65-11ea-95b3-f59b7af3d944.png)

**To Reproduce**
1. create a new React Native project and install amplify
```sh
$ npx react-native init rnamplify
$ cd rnamplify
$ yarn add aws-amplify
```

2. Initialize a new Amplify project
```sh
$ amplify init
```

3. Add an API with a basic schema
```sh
$ amplify add api
```

Schema
```graphql
type Todo @model {
  id: ID!
  name: String!
  description: String
}
```

4. Try to initialize a subscription

See [this snippet](https://gist.github.com/24HourDeveloper/9cd6fc3e89f889743538978e23769572) or similar for code example.

**Expected behavior**
subscriptions work

__Details__
 Reported by customer [here](https://twitter.com/UNCODED_LS/status/1227809611564093441). Tested with Amplify 2.2.2 and 2.2.4. Tried a lot of stuff before filing this bug to be sure it wasn't something on mine or the customer's machine or env.

**Smartphone (please complete the following information):**

- Device: iPhone 10

**Additional context**
Works fine on a web project

**Comment by callaars** [comment]
This also fails on an Android device. By simply following the documentation, it occurs immediately.

**Comment by callaars** [comment]
What I am seeing is that it fails on [this line](https://github.com/aws-amplify/amplify-js/blob/master/packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts#L571) with the error `Buffer is not defined`. I resolved this by adding the following at the start of my react-native app:

```
global.Buffer = require('buffer').Buffer;
```

**Comment by dabit3** [comment]
Nice find @callaars, thanks for the heads up and update. We're looking at a native fix for this now.

**Comment by callaars** [comment]
My pleasure, you're doing great work here!

**Comment by sammartinez** [comment]
Starting to dig into this with the team

**Comment by elorzafe** [comment]
Thanks @dabit3, the issue is confirmed and I am working on a fix right now

**Comment by elorzafe** [comment]
Fix published into `unstable` tag tomorrow it will be published into `latest` tag

**Comment by dabit3** [comment]
Thanks @elorzafe @sammartinez !!
