### ISSUE TITLE
"No Current User" for AWS_IAM unauthenticated role

### ISSUE THREAD

**Issue by rush86999** [aws-amplify/amplify-js#4911]
**Describe the bug**

I am getting 'no authenticated user' for an unauthenticated AWS_IAM role with cognito groups following the docs.

**To Reproduce**

I tried using multi-auth with amplify js. I also followed https://github.com/aws-amplify/amplify-cli/issues/2373 but did not work. 

here are the things I tried:
1. amplify update api and added iam for pubic auth
2. followed the docs and passed an object with authMode:

```
const hostData = await API
        .graphql({
          query: CheckProfileId,
          variables: params,
          authMode: 'AWS_IAM',
        });
```

in the schema i have
```
@auth(rules: [
  {allow: public, provider: iam, operations: [read]},
  {allow: private}
])
```
any help? should I switch to API_KEY?

note: also when i did amplify update api for adding iam as additional authentication it asked for conflict resolution and i selected automerge
-- or --

Link to sample code

**Expected behavior**

**Screenshots**

<details>
  <summary><strong>amplify cli using "aws-amplify": "^1.3.3",</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

</details>

**Smartphone (please complete the following information):**

**Additional context**

**Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by HamzaLJ** [comment]
Same issue, any solutions?

**Comment by naedx** [comment]
I configured _multiple authentication modes_ on my `@model` as described [here](https://aws.amazon.com/blogs/mobile/using-multiple-authorization-types-with-aws-appsync-graphql-apis/) but requests would be authenticated using only the _default_ authentication mode as specified using `amplify api configure`.  

As show below, I had tried specifying the auth mode inside my service class, but this would be overwritten every time I updated my schema.

```javascript
//MyAppAPI.service.ts 
const response = (await API.graphql(
  {
    query: statement, 
    variables: gqlAPIServiceArguments,
    authMode: GRAPHQL_AUTH_MODE.API_KEY
  });
````

I eventually found that I could instead change the auth mode programatically by doing the following: 

```javascript
// import { AmplifyService } from 'aws-amplify-angular';
// import Amplify from '@aws-amplify/core';
// ...
// ...
  
this.amplifyService.authStateChange$
  .subscribe(authState => {
      
  this.isLoggedIn = authState.state === 'signedIn';
  this.user = authState.user;

  if(this.isLoggedIn)
  {       
    Amplify.configure({
      "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS", 
    });
  }
  else
  {
    Amplify.configure({
      "aws_appsync_authenticationType": "API_KEY", 
    });
  }

});
  
  
// ...
```

I hope this helps someone.

**Comment by sammartinez** [comment]
@rush86999 We do recommend to use the latest version of Amplify CLI, seeing that you are on `amplify-cli@1.3.3` and current version is `4.21.1`, but we also wanted to confirm if you were still experiencing this issue with the above work arounds. Please let us know.

**Comment by rush86999** [comment]
I abandoned the current project for this issue. I will try this on a future project. Thanks for your help. I m leaving this open so someone else can confirm that this problem is in fact resolved.

**Comment by amlcodes** [comment]
running into this, is programmatically changing the config the only way to support unauthenticated users? currentSession() errors with no current user. I remember this working back in the day without a programmatic if else
