### ISSUE TITLE
How to test expired session scenarios proeperly? (Suggestions/recommendations) 

### ISSUE THREAD

**Issue by giulioambrogi** [aws-amplify/amplify-js#4914]
Hi there,

My app uses  `@aws-amplify/auth`  to talk to `Cognito` to authenticate users.
I would like to **replicate/test** the scenario **when the session expires**, example:
1. User logs in
2. User leaves browser open for > 7 days (current expiration for jwt tokens)
3. User comes back to the page 

# Question
How would you suggest to reproduce this scenario?

# What I've tried so far
* changing the clock of the laptop but its too extreme as it breaks other services used by my app.
* clearing the `localStorage` (where amplify stores auth data), I don't think this is accurate, as it wipes out all the data ending up into a different scenario IMO.

**Comment by manueliglesias** [comment]
Hi @giulioambrogi 

One thing that comes to my mind is to change the expiration of the jwt tokens only:

https://github.com/aws-amplify/amplify-js/blob/832c0ea73d03acc63bb7300d7bb56eecf56030be/packages/amazon-cognito-identity-js/src/CognitoUserSession.js#L85-L93

For this you can try to replace the items in localStorage, these are the keys:

https://github.com/aws-amplify/amplify-js/blob/832c0ea73d03acc63bb7300d7bb56eecf56030be/packages/amazon-cognito-identity-js/src/CognitoUser.js#L1323-L1329

As of the JWT format and spec, take a look at: https://jwt.io/introduction/

Let me know if this helps, or if we need to re-open the issue
