### ISSUE TITLE
What's the best way to account for pagination, robust search/filter/sort, and instant updates with react?

### ISSUE THREAD

**Issue by midimurphdesigns** [aws-amplify/amplify-js#4916]
** Which Category is your question related to? **
gql queries and subscriptions

** What AWS Services are you utilizing? **
AppSync, DynamoDB, ElasticSearch

** Provide additional details e.g. code snippets **
Given that dynamo queries don't return total results, don't have the same querying capabilities as elasticsearch, and there are no subscriptions created for elasticsearch, how does the developer best account for pagination, search, robust filtering, and instant updates on create/edit/delete/delete multiple feature requests? 

I have a decent pagination system where I keep track of next tokens from search queries, although the logic isn't the most simple thing. Similar story with search/filter/sort. But what is really throwing me for a loop is instant updates. There is a 2-3 sec. delay between when the crud operation happens and when elasticsearch registers the change. I am currently just recursively refetching data until the data matches expected data. This causes a lot of bugs and isn't as simple as I would have hoped. There must be a better way.

If there were subscriptions for elasticsearch queries, I think I could manage. Why aren't there subscriptions for search queries?

**Comment by elorzafe** [comment]
@midimurphdesigns 
Why subscribing to changes like create/update/delete doesnt work for you? Have you tried Amplify DataStore?, that deals with those kinds of problems because is internally syncing everything (and also is offline first)

**Comment by midimurphdesigns** [comment]
> @midimurphdesigns
> Why subscribing to changes like create/update/delete doesnt work for you? Have you tried Amplify DataStore?, that deals with those kinds of problems because is internally syncing everything (and also is offline first)

Amplify sets up subscriptions for dynamo queries but not elasticsearch queries. I need to use elasticsearch queries b/c it returns total results, a next token, and has decent filter and sort capabilities. I'll look into datastore, I remember hearing about it at reinvent.

**Comment by manueliglesias** [comment]
Hi @midimurphdesigns 

How did you set up your API? was it from an annotated schema? (e.g. using the `@searchable` directive)

When using the `@searchable` directive together with `@model`, Amplify will create all the machinery needed to make your writes to DynamoDB flow to both Subscriptions and ElasticSearch
