### ISSUE TITLE
Query: Nested List Items Return Empty

### ISSUE THREAD

**Issue by anarerdene** [aws-amplify/amplify-js#4918]
** Which Category is your question related to? **
@key with @connection.
** What AWS Services are you utilizing? **
AWS AppSync
** Provide additional details e.g. code snippets **
Im Using @key but nested list return empty ?

this is my schema:

![image](https://user-images.githubusercontent.com/2210568/74571199-755fa280-4fb8-11ea-88c4-79ba09d18fe5.png)

and this is result:

![image](https://user-images.githubusercontent.com/2210568/74571300-988a5200-4fb8-11ea-9472-11f22dd6b006.png)

PS: I also tested with filters.

**Comment by elorzafe** [comment]
Duplicate of #4919
