### ISSUE TITLE
When importing Angular AmplifyService it introduces ERROR in Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by fireflysemantics** [aws-amplify/amplify-js#4920]
**Describe the bug**
When importing Angular AmplifyService it introduces ERROR in Cannot read property 'length' of undefined

If I comment out:

```
//import { AmplifyService }  from 'aws-amplify-angular';
```

The project runs fine.
 
**To Reproduce**

```
npm i -S aws-amplify-angular
And in the auth service import:
import { AmplifyService }  from 'aws-amplify-angular';

```

![Screenshot from 2020-02-14 18-10-27](https://user-images.githubusercontent.com/25155787/74577582-8d520a80-4f55-11ea-80c0-29aca79bb74f.png)
![Screenshot from 2020-02-14 18-10-35](https://user-images.githubusercontent.com/25155787/74577587-92af5500-4f55-11ea-84b6-593ac6465201.png)

**Comment by fireflysemantics** [comment]
Using `Hub` instead works:

```
    Hub.listen('auth',(data) => {
      const { channel, payload } = data;
      if (channel === 'auth') {
        console.log(`Current authstate payload event ${payload.event}`)

        if (payload.event == AuthService.SIGN_IN) {
          this.os.put(AUTHENTICATED, true)
        }
        else if ( payload.event==AuthService.SIGN_OUT ) { 
          this.os.put(AUTHENTICATED, false)
        }    
      }
    })


```

**Comment by sammartinez** [comment]
@fireflysemantics I apologize that we haven't had a chance to dig into this on your behalf. For [dependency injections](https://aws-amplify.github.io/docs/js/angular#using-dependency-injection) we do call out that you should inject this into your constructor of your top level App component. Are you following the guide on this? Also, did you follow the [getting started guide](https://aws-amplify.github.io/docs/js/start?platform=angular) for Angular? Could you also provide a code snippet or a gist of your code you are using from the above error messages?

**Comment by fireflysemantics** [comment]
Hello @sammartinez ,
I just noticed that Angular 9 is not supported and I'm using : 

```
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.8
@angular-devkit/build-angular     0.900.0-rc.8
@angular-devkit/build-optimizer   0.900.0-rc.8
@angular-devkit/build-webpack     0.900.0-rc.8
@angular-devkit/core              9.0.0-rc.8
@angular-devkit/schematics        9.0.0-rc.8
@angular/cdk                      8.2.3
@angular/material                 8.2.3
@ngtools/webpack                  9.0.0-rc.8
@schematics/angular               9.0.0-rc.8
@schematics/update                0.900.0-rc.8
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2


```

I think that's the problem.  I'll just stick with Hub for now until Angular 9 is supported.
