### ISSUE TITLE
Analytics.updateEndpoint fails - no address

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-js#4922]
**Describe the bug**
When calling `Analytics.updateEndpoint` I get an error saying `Missing Address`. I have a `PushNotification.onRegister` event listener and I can see that I do have a notification token. I saw some guides mentioning that I should not set do 
```
Analytics.updateEndpoint({
      address: token
});
```
when receiving the notification token because Amplify does that automatically. But it doesn't work for me.

**To Reproduce**
Try to use `Analytics.updateEndpoint` to update endpoint with user data, and get the error `Missing Address`

**Expected behavior**
endpoint should be automatically updated with the notification token and I should be able to use `updateEndpoint` with no problems.

**Smartphone (please complete the following information):**

- Device: All
- OS: All

**Comment by ashika01** [comment]
@idanlo : could you provide us with what version of aws-amplify and analytics you are using?

**Comment by idanlo** [comment]
@ashika01 
```
"@aws-amplify/analytics": "^2.2.5",
"aws-amplify": "^2.2.5"
```

**Comment by ashika01** [comment]
@idanlo : could you gimme some sample code ? also, are you using push notification and update endpoint? whats the use case for update endpoint here?

**Comment by idanlo** [comment]
@ashika01 I don't have the `updateEndpoint` for updating the address using the notification token anymore, as I said I read somewhere that it is already done automatically by Amplify.
I use the `updateEndpoint` to set the user data in the endpoint - user id, and other attributes, so that I can later target the user and send a notification to the user's endpoint

**Comment by ashika01** [comment]
@idanlo Could you provide me with some sample code ? Would help me debug this faster.. Also, even without PushNotification just using Analytics do u still get this error?

**Comment by idanlo** [comment]
@ashika01 you mean I should give it a static address? Because the address should be set automatically by the PushNotification package, the code I'm using is what exists in the issue. I'm calling `Analytics.updateEndpoint` but not passing the `address` (as I said it should be automatically passed).
So for example - 
```js
Analytics.updateEndpoint({
  userId: "xxxx"
});
```

**Comment by ashika01** [comment]
@idanlo I will need to completely setup a push notification sample with your use case to test this out. Our official doc on Push Notification is [here](https://aws-amplify.github.io/docs/js/push-notifications) following this should let you send a successful push notification.

However, I have not tried setting user data like you have. My guess would be Analytics.updateEndpoint having conflicts with the one internal to that of Push Notifications's.

**Comment by harrysolovay** [comment]
Similar to / suggestion contained within #5162
