### ISSUE TITLE
`confirmSignUp` callback is passed different `authData` after signUp than after signIn

### ISSUE THREAD

**Issue by edgarjs** [aws-amplify/amplify-js#4923]
**Describe the bug**
> Not sure if this is intentional but I would expect a consistent interface in the `authData` parameter of the `onStateChange` callback.

When signing up the [`SignUp` component is calling `this.changeState('confirmSignUp', data.user.username)`](https://github.com/aws-amplify/amplify-js/blob/a047ce73ab/packages/aws-amplify-react/src/Auth/SignUp.tsx#L271). However when signing in and getting a `UserNotConfirmedException`, the [`SignIn` component is calling `his.changeState('confirmSignUp', { username })`](https://github.com/aws-amplify/amplify-js/blob/a047ce73ab/packages/aws-amplify-react/src/Auth/SignIn.tsx#L121).

The former is a string while latter is an object.

**To Reproduce**

1. Sign up and confirm without reloading the page
2. The `onStateChange` callback is called with a string as the `authData` parameter.

1. Sign up and leave the page or reload
2. Sign in with the recently signed up credentials
3. The `onStateChange` callback is called with an object as the `authData` parameter.

-- or --

https://github.com/aws-amplify/amplify-js/blob/a047ce73ab/packages/aws-amplify-react/src/Auth/SignUp.tsx#L271

https://github.com/aws-amplify/amplify-js/blob/a047ce73ab/packages/aws-amplify-react/src/Auth/SignIn.tsx#L121

**Expected behavior**
A consistent interface of the `authData` parameter for the `confirmSignUp` auth state.

**Comment by ashika01** [comment]
@edgarjs - Could you try using `@aws-amplify/ui-react`? This shouldn't be happening in the components now.  We are moving away from `aws-amplify-react` usage to `@aws-amplify/ui-react`. 

For more info, refer this docs for implementation - https://docs.amplify.aws/ui/auth/authenticator/q/framework/react

Feel free open up a new issue, if you have any feedback, bug or feature request with respect to the new UI components.
