### ISSUE TITLE
TypeScript types are incorrect

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-js#4927]
**Describe the bug**
I am calling `Auth.currentAuthenticatedUser()` to get the current users data, attributes, and sub. The function states that it returns a `CognitoUser`, which I import like this `import { CognitoUser } from '@aws-amplify/auth'`. And it says that `CognitoUser` does not have an `attributes` property, but if I `console.log` the result from `Auth.currentAuthenticatedUser()` I can clearly see an `attributes` property. On `CognitoUser` there is a method `getUserAttributes` but it is async and receives a callback which is very weird.
Are the types wrong? Or I shouldn't access the `attributes` directly and through the function that it provides?

**To Reproduce**

1. `import { Auth } from 'aws-amplify'`
2. `import { CognitoUser } from '@aws-amplify/auth'`
3. `const user: CognitoUser = await Auth.currentAuthenticatedUser()`
4. try to access `user.attributes.something`
5. Get TypeScript error

**Expected behavior**
TypeScript types include all of the properties that are returned from the specific function.

**Comment by sammartinez** [comment]
@idanlo Can you provide the TypeScript error you are receiving? Also, can you provide a code snippet of your code along with the `package.json`, this helps us with understanding what is currently being used.

**Comment by idanlo** [comment]
@sammartinez The error I'm getting - `Property 'attributes' does not exist on type 'CognitoUser'.ts(2339)`.
The code snippet exists in the reproduction I gave, as simple as that. version - `aws-amplify: "^2.2.5"`

**Comment by danawoodman** [comment]
Yes, the types in Cognito are messed up. They don't match actual response objects and thus if you use them your app breaks but if you don't use them, then passing the cognito user around into other Cognito methods breaks things too. It's quite a mess.

**Comment by mtscsoftware** [comment]
The way I did to overcome this problem (at least temporary) was to create a new custom type like that extends the base CognitoUser type like following:

`
type MyCognitoAttributes = {
   'custom:xxx': string;
   ...
}

type MyCognitoUser = CognitoUser & {
    attributes: MyCognitoAttributes;
}
`

This way I am covering my custom attributes also

**Comment by dorontal** [comment]
Here's my temporary fix, which also extends the `CognitoUser` type, but does so via a Typescript `inteface` declaration:

[ Note: First, I define a custom `UserAttributes` type to only have the fields used in my app, since those could be anything. ]

```typescript
import { CognitoUser } from '@aws-amplify/auth';

...

/*
 * Custon attributes type defined according to the attributes used in this app
 */
export interface UserAttributes {
    sub: string;
    email: string;
    email_verified: string;
    name: string;
    updated_at: string;
    'custom:bytesQuota': string;
    'custom:bytesUsed': string;
}

...

/*
 * The following interface extends the CognitoUser type because it has issues
 * (see github.com/aws-amplify/amplify-js/issues/4927). Eventually (when you
 * no longer get an error accessing a CognitoUser's 'attribute' property) you
 * will be able to use the CognitoUser type instead of CognitoUserExt.
 */
interface CognitoUserExt extends CognitoUser {
    attributes: UserAttributes;
}

...

// usage, in the code:

        this.user = await Auth.currentAuthenticatedUser();
        return this.user ? this.user.attributes : null;

```

**Comment by CompleteScone** [comment]
Just noting that a similar thing occurs with challengeName (as has been noted) and was brought up almost a year ago but then closed (#3733).

**Comment by assemblethis** [comment]
> Just noting that a similar thing occurs with challengeName (as has been noted) and was brought up almost a year ago but then closed (#3733).

Same here. 'Property 'challengeName' does not exist on type 'CognitoUser'.Vetur(2339)
The types need to be fixed.

**Comment by igorborgest** [comment]
Meanwhile I was able to work around following some internal code [[1]](https://github.com/aws-amplify/amplify-js/blob/528466e8000cffc3ee4340a03798f4a01ace0022/packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx#L105) and [[2]](https://github.com/aws-amplify/amplify-js/blob/528466e8000cffc3ee4340a03798f4a01ace0022/packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx#L67).

Basically importing `import { CognitoUserInterface } from '@aws-amplify/ui-components';` and using it to declare variables and also for type assertions `as CognitoUserInterface`.

e.g.

```typescript
const AuthStateApp: React.FunctionComponent = () => {
  const [authState, setAuthState] = React.useState<AuthState>();
  const [user, setUser] = React.useState<CognitoUserInterface | undefined>();

  React.useEffect(() => {
    return onAuthUIStateChange((nextAuthState, authData) => {
      setAuthState(nextAuthState);
      setUser(authData as CognitoUserInterface);
    });
  }, []);

  return authState === AuthState.SignedIn && user ? (
    <div className="App">
      <div>Hello, {user.username}</div>
      <AmplifySignOut />
    </div>
  ) : (
      <AmplifyAuthenticator />
    );
}
```

**Comment by 8brandon** [comment]
I noticed that when I log the return value, it's the class instance of CongnitoUser, and you can call the class methods on it like such. 
 ```
if (response && response instanceof CognitoUser) {
    return <div>{response.getUsername()}</div>;
  }
```

**Comment by armenr** [comment]
> import { CognitoUserInterface } from '@aws-amplify/ui-components';

I came here just to say THANK YOU BECAUSE I hadn't even THOUGHT to look in ui-components for exported interfaces/types for this! I'd been struggling/fighting/using `// import { CognitoUser } from 'amazon-cognito-identity-js'` instead.

Lack of documentation, info on this hurts...but thank goodness for this thread!

**Comment by armenr** [comment]
Here's a fun one, in case anyone has any ideas:

Snippet:

```
import { VuexModule, Module, Mutation, Action } from 'vuex-module-decorators'
import { CognitoUserInterface } from '@aws-amplify/ui-components'

@Module
export default class AuthModule extends VuexModule {
  user: CognitoUserInterface = {}
}

```

All I wanna do is shove my Auth state into Vuex. No big deal, right? So, when I import `CognitoUserInterface`, typescript complains, stating: **_Type '{}' is missing the following properties from type 'CognitoUserInterface': challengeName, challengeParamts(2739)_**

So, I need to initialize state this way:

```
@Module
export default class AuthModule extends VuexModule {
  user: CognitoUserInterface = {
    challengeName: '',
    challengeParam: {}
  }
}
```

Not a huge pain, but _**why**_? When I look at the typing for CognitoUserInterface, it looks like practically everything is optional, EXCEPT for challengeName and challengeParam.

```
export interface CognitoUserInterface {
    Session?: string | null;
    authenticationFlowType?: string;
    client?: {
        endpoint?: string;
        userAgent?: string;
    };
    keyPrefix?: string;
    pool?: {
        advancedSecurityDataCollectionFlag?: boolean;
        clientId?: string;
        userPoolId?: string;
    };
    username?: string;
    userConfirmed?: boolean;
    userSub?: string;
    challengeName: string;
    challengeParam: {
        [key: string]: any;
    };
    unverified?: {
        email?: string;
        phone_number?: string;
    };
    [attributes: string]: any;
}
```
Why tho? Could someone explain to me if initializing the state object as type `CognitoUserInterface` with empty string + object for those two properties is a bad idea? If so, why? :)

Thank you!

**Comment by pgbradbury** [comment]
Thanks for the thread, still looking for a solution on this

**Comment by torgeadelin** [comment]
This is still an issue.

**Comment by jlapier** [comment]
Based on other suggestions above, I was able to just assign the auth data to type CognitoUserInterface and use it that way, e.g.

```
import { Auth } from '@aws-amplify/auth';
import { CognitoUserInterface } from '@aws-amplify/ui-components';

// ...

Auth.currentAuthenticatedUser().then((authData: CognitoUserInterface) => {
    this.setState({userData: authData});
});
```

**Comment by ziw** [comment]
Still seeing this issue in the latest `"aws-amplify": "^4.2.6"`. It's really frustrating. Can amplify team take a look? How can TypeScript definition not matching the public API and the response object?

**Comment by howieweiner** [comment]
Just hit this issue. getUsername() is defined in the type definition, but returns undefined;  the username property is populated, but not defined in the type definition :(

CognitoUserInterface is not a solution as I"m not using thr UI library, mjust the Auth library

**Comment by KMathisGit** [comment]
Also affected by this. Really off-putting that this is still an ongoing issue. I mean we're not asking for anything crazy just give us type definitions that actually match responses..

**Comment by daveharig** [comment]
Same issue here.  .challengeName 

Property 'challengeName' does not exist on type '{ challengeName: string; } | { challengeResult: boolean; }'.
  Property 'challengeName' does not exist on type '{ challengeResult: boolean; }'.ts(2339)

**Comment by MadaShindeInai** [comment]
import { CognitoUserAmplify } from '@aws-amplify/ui-react/node_modules/@aws-amplify/ui';
Looks like that works for me.

**Comment by mcanvar** [comment]
Hi there, looks like this is still an issue on `^4.3.22`

**Comment by abdallahshaban557** [comment]
@mcanvar  - can you please submit a new Github issue so that we can collect the needed information from you and properly track this?

**Comment by mcanvar** [comment]
@abdallahshaban557 Sure, will going to add here.

**Comment by MadaShindeInai** [comment]
Maybe my solution will be helpful for someone.
Step 1. Extending type of User.
```
import { CognitoUserAmplify } from '@aws-amplify/ui-react/node_modules/@aws-amplify/ui';
export enum Test {
  TEST1 = 'test1',
  TEST2 = 'test2',
}
export interface AppUser extends CognitoUserAmplify {
  'custom:test': Plan;
}
```
Step 2. Making custom hook with overriding type of user.

```
import { useAuthenticator } from '@aws-amplify/ui-react';
import { AppUser } from 'types';

export const useAuthentication = () => {
  const { ...rest } = useAuthenticator((context) => [context.user]);
  return { ...rest, user: rest.user as AppUser };
};

```
Step 3. Using this hook instead useAuthenticator across the app.

**Comment by mkbctrl** [comment]
![Screenshot 2022-10-11 at 09 18 02](https://user-images.githubusercontent.com/10107362/195022455-1073ba1e-be5f-41c4-8d8c-03fd8dad1922.png)
![Screenshot 2022-10-11 at 09 18 11](https://user-images.githubusercontent.com/10107362/195022463-80a305f9-6922-46cb-ab21-282e1286b26c.png)


For those who end up here looking for a proper interface for `Auth.SignIn` method... The differences in shape of response are significant

**Comment by daveharig** [comment]
That's it!  It's a little scarry how Bush-league AWS looks under the hood.

**Comment by abdallahshaban557** [comment]
We are currently working on re-writing our Auth category, and consolidating our TS types, and exposing them more elegantly. It has been long overdue, but we are working on this as our highest priority to simplify the experience of using our library, and making it as seamless as possible.

**Comment by olsommer** [comment]
@abdallahshaban557 Could you please keep us up to date here? Would be great since I'm facing the same issue. 

My workaround for username + attributes is: 
`import { AmplifyUser } from '@aws-amplify/ui';`

**Comment by abdallahshaban557** [comment]
Hi @olsommer  - our journey with re-writing the Auth category is still underway. We have introduced incremental enhancements to some of our other feature sets, but Authentication will come later. I do not have a concrete timeline yet - but that will be shared more broadly on Github/Discord/Twitter when our initial version is available for developers to try.

**Comment by cjsilva-umich** [comment]
This has been an issue for 3 years and still isn't fixed? How is that possible? Just provide the types!

**Comment by rafaelfaria** [comment]
Now that ui-components is deprecated, how do we import the `CognitoUserInterface` type?

**Comment by ebisbe** [comment]
Seeing a reaction from myself in a comment made 3 years ago is sad. Is there a deadline?

**Comment by abdallahshaban557** [comment]
Hello - we are currently working on improving our TypeScript coverage, and we have this RFC proposal open that we would love to get feedback on.

https://github.com/aws-amplify/amplify-js/issues/11113

**Comment by mkbctrl** [comment]
@AgoraRich until this happens you can use `as unknown as YourTSinterface` to overwrite the clunk ones. Not perfect but better than `any`

**Comment by abdallahshaban557** [comment]
Hi @vehm  - we would really appreciate your feedback on the RFC for the TypeScript types we want to introduce in our next major version here. https://github.com/aws-amplify/amplify-js/issues/11113

**Comment by 5t33** [comment]
why is this closed?
