### ISSUE TITLE
Datastore with custom claims seems not ok

### ISSUE THREAD

**Issue by SebSchwartz** [aws-amplify/amplify-js#4928]
**Describe the bug**
I configured amplify with custom authorization header to pass idToken with datastore. I configured my schema to work with it but i'm receiving the same error with all models:
0: {errorType: "Unauthorized", message: "Not Authorized to access onUpdateAddress on type Subscription"}.
When I create a new address, i can see it in my indexDB but it's not sent to dynamodb...

**To Reproduce**
I checked out a new projet with datastore following the docs (to test it out). My cognito user pool does have the custom attribute and my signed in user has a value "1" for it.

Amplify config:
```javascript
Amplify.configure(awsconfig);

Amplify.configure({
  API: {
    graphql_headers: async () => {
      const session = await Auth.currentSession();
      return {
        Authorization: session.getIdToken().getJwtToken()
      };
    },
  },
});

```

schema.graphql:
```graphql
type Address
  @model
  @auth(rules: [{ allow: owner, identityClaim: "custom:clientId" }]) {
  id: ID!
  street: String
}
```

**Expected behavior**
Should work and no error should be raised ;)

**Screenshots**

<details>
  <summary><strong>Environment</strong></summary>

```
  System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 1.05 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 62.0
    Safari: 13.0.4
  npmPackages:
    @aws-amplify/analytics: ^2.2.4 => 2.2.4 
    @aws-amplify/core: ^2.2.4 => 2.2.4 
    @aws-amplify/datastore: ^1.0.6 => 1.0.6 
    @testing-library/jest-dom: ^4.2.4 => 4.2.4 
    @testing-library/react: ^9.4.0 => 9.4.0 
    @testing-library/user-event: ^7.2.1 => 7.2.1 
    aws-amplify: ^2.2.4 => 2.2.4 
    aws-amplify-react: ^3.1.5 => 3.1.5 
    ini: ^1.3.5 => 1.3.5 
    inquirer: ^6.5.1 => 6.5.2 
    react: ^16.12.0 => 16.12.0 
    react-dom: ^16.12.0 => 16.12.0 
    react-scripts: 3.3.1 => 3.3.1 
  npmGlobalPackages:
    @aws-amplify/cli: 4.13.3
    apollo: 1.9.2
    aws-appsync-codegen: 0.17.5
    awsmobile-cli: 1.1.5
    expo-cli: 3.11.9
    lerna: 3.13.3
    npm: 6.13.4
    serverless: 1.53.0
    typescript: 3.4.5
    watchman: 1.0.0
    yarn: 1.9.4
```

</details>

**Comment by SebSchwartz** [comment]
Here is the message sent for the subscription:
```javascript
{
id: "5c49fe65-5481-4009-8216-45684ace19fa",
payload: {
data: "{"query":"subscription operation($owner: String!) {\n  onUpdateAddress(owner: $owner) {\n    id\n    street\n    _version\n    _lastChangedAt\n    _deleted\n  }\n}\n","variables":{"owner":"1"}}",
extensions: {
authorization: {
Authorization: "Access TOKEN",
host: ".com",
x-amz-user-agent: "aws-amplify/2.2.4 js"
}}}
type: "start"
}
```

**Comment by SebSchwartz** [comment]
I also tried with `ownerField: "clientId"`in the auth config and adding the field in the schema but got the same error :/

**Comment by SebSchwartz** [comment]
I also updated some package version to:
```json
"@aws-amplify/datastore": "^1.0.7",
        "aws-amplify": "^2.2.5",
        "aws-amplify-react": "^3.1.6",
```
But error is still there with those versions.

**Comment by SebSchwartz** [comment]
It is working with simple key-value header but it's not waiting the result when calling it with async method -> https://github.com/aws-amplify/amplify-js/blob/e03dd517e09280349f2fb3501f43b90fec741895/packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts#L244

In the API packages, it's awaited and called after the basic one so we can override it: https://github.com/aws-amplify/amplify-js/blob/86597db2b0704d7aff5b612557536142b82e1731/packages/api/src/API.ts#L403

**Comment by amin79** [comment]
@SebSchwartz Did you find any solution? I have the same problem.

**Comment by SebSchwartz** [comment]
We don't use it anymore :p But solution should have been merged so it should work :/

**Comment by amin79** [comment]
But it does not work. Any problem I face using AWS amplify and google for it, I see the people had that problem long time ago and it's not solved yet. It seems the only project that really works perfectly with amplify is TODO project.
