### ISSUE TITLE
Support OIDC address claim per the spec

### ISSUE THREAD

**Issue by ggriffin** [aws-amplify/amplify-js#4935]
**Describe the bug**
The OIDC specification for Address Claim defines it to be a JSON object that contains either a `formatted` value, all other address sub values, or both. The cognito `signUp` and `admin-update-user-attributes` APIs define the address input as a string. This string is then used to populate the OIDC address "formatted" claim.

**To Reproduce**

1. Create a cognito user pool and sign up a user
2. Attempt to update the user address attribute for the created user:

```
aws cognito-idp admin-update-user-attributes --region us-east-2 --user-pool-id us-east-2_********* --username ********-****-****-****-************ --user-attributes '[{"Name":"address","Value":"{\"street_address\": \"13 Main St\"}" }]'
```
3. Inspect the address claim via an AppSync vtl resolver using `$ctx.identity.claims`:

```
{
  "claims": {
    "address": {
      "formatted": "{\"street_address\": \"13 Main St\"}"
    },
    ...
```

**Expected behavior**
I expect Cognito to take an address JSON object or stringified JSON object, and populate the OIDC address claim as either:

```
{
  "street_address": "13 Main St"
}
```
or:
```
{
  "formatted": "13 Main St",
  "street_address": "13 Main St"
}
```

<details>
  <summary><strong>Environment</strong></summary>

```
$ npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages

npx: installed 1 in 1.511s

  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Memory: 19.72 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    npm: 6.13.6 - ~/.nvm/versions/node/v12.14.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 80.0.3987.106
    Safari: 13.0.5
  npmPackages:
    @typescript-eslint/eslint-plugin: ^2.16.0 => 2.16.0
    @typescript-eslint/parser: ^2.16.0 => 2.16.0
    eslint: ^6.8.0 => 6.8.0
    eslint-config-prettier: ^6.9.0 => 6.9.0
    eslint-plugin-import: ^2.20.0 => 2.20.0
    eslint-plugin-prettier: ^3.1.2 => 3.1.2
    prettier: ^1.19.1 => 1.19.1
    prettier-standard: ^16.1.0 => 16.1.0
    typescript: ^3.7.5 => 3.7.5
  npmGlobalPackages:
    inthash: 1.1.0
    npm: 6.13.6
    pnpm: 4.7.2
```
</details>

**Comment by sammartinez** [comment]
@ggriffin This seems to be specific to Amazon Cognito and not Amplify, are you using Amplify? If not, I believe this can be better suited to ask Amazon Cognito via [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=173).
