### ISSUE TITLE
Upgrade aws-sdk version in core

### ISSUE THREAD

**Issue by sammartinez** [aws-amplify/amplify-js#4936]
**Which Category is your question related to?** 
Core

Customers are asking in regards to updating our `aws-sdk` version, currently `2.518.0`, within our core package in Amplify. We need to see if having our package take the latest will cause any issues to Amplify.

#### Related Issues
Helps #3923

**Comment by jkeys-ecg-nmsu** [comment]
@sammartinez presumably this will not be an issue when v3 of the JS SDK goes live -- one of my first attempts at circumventing this problem was to install the relevant V3 package, but it has not been published recently and doesn't expose the recent APIs that we need.

**Comment by jkeys-ecg-nmsu** [comment]
Any update on this, or steps on how to manually pin and test a version of the SDK?

**Comment by jordanranz** [comment]
We have upgraded `aws-amplify` to v3. Closing this.
