### ISSUE TITLE
IOS rejection due to app redirect with Ionic

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-js#4950]
I have commented on this before and had no useful answers, and this is really frustrating.

Amplify is supposed to support ionic however the social integration is not properly integrated.

My login code:

```
  public async loginWithFacebook(): Promise<any> {
    this.amplify.auth().federatedSignIn({ provider: 'Facebook' });
  }

  public async loginWithGoogle(): Promise<any> {
    this.amplify.auth().federatedSignIn({ provider: 'Google' });
  }

  public async loginWithApple(): Promise<any> {
    // console.log(result);
    this.amplify.auth().federatedSignIn({ provider: 'SignInWithApple' });
  }

```

This takes the user off the app and opens in safari, the redirect then works, however as apple point out it is a horrible use experience as apposed to popping up an in app browser.

Apple state:

> Guideline 4.0 - Design
> 
> 
> We noticed that the user is taken to Safari to sign in or register for an account, which provides a poor user experience.

Now ideally could an Amplify developer @mikeparisstuff @kaustavghosh06  etc either point me in the direction of how I would be able to do the authentication using the in app browser or update the angular/Ionic code to cater to this.

I have tried using the ionic capacitor in app browser:

` const result = await this.utils.openBrowser('https://cultureappauth.auth.eu-west-1.amazoncognito.com/oauth2/authorize?redirect_uri=com.app.myapp://welcome/&response_type=code&client_id=myid&identity_provider=SignInWithApple')`

However due to the redirect, it tries to redirect to the app which is cannot do as its in the capacitor browser: [capacitor](https://capacitor.ionicframework.com/docs/apis/browser)

On another note, even using the ionic amplify social methods I still had to create a VERY hacky approach in order for it to work:

[3537](https://github.com/aws-amplify/amplify-js/issues/3537)

Amplify has advanced to be utterly fantastic, but this is the one thing really limiting my Ionic application

**Comment by sammartinez** [comment]
#3537 

@oliverandersencox I made a comment in issue #3537 about the updates and having oncall dig into your issue

**Comment by oliverandersencox** [comment]
@sammartinez I managed to set it up to use the in app browser with this:

const result = await this.utils.openBrowser('https://cultureappauth.auth.eu-west-1.amazoncognito.com/oauth2/authorize?redirect_uri=com.app.myapp://welcome/&response_type=code&client_id=myid&identity_provider=Facebook')

And everything works fine, however there is no state returned once the auth completes, and so when i try and authorise it fails. If i add 'state=1234' to the url above it also fails.

Can you help explain what i need to do to authenticate using the url approach. This is the only way to get it working on Ionic whereby it will pass app store checks.

The whole authentication process works using the auth url approach, however something is missing when i try and authenticate with an app reload and the code + state in the reload url.

Someone on the amplify team must be able to help here.. I have heard nothing from the on call team.

**Comment by oliverandersencox** [comment]
@sammartinez is there a specific string i need to use for status? Apple rejected it again because of the redirect and I have got it so close to working using the in app browser. I simply need answers to manual authentication using a URL

**Comment by ahtokca** [comment]
My app just got rejected with the same reason
```
From Apple
    2. 1 Performance: App Completeness
    4. Design: Preambl
Guideline 2.1 - Performance - App Completeness

We discovered one or more bugs in your app. Specifically, sign in with Apple exited to Safari.
```

Is there any easy way to comply with Apple requirements using amplify Auth?

**Comment by nadetastic** [comment]
Related to #10507

**Comment by nadetastic** [comment]
#7373

**Comment by nadetastic** [comment]
HI @oliverandersencox @ahtokca following up on this issue here. After some discussion with the team, this issue is similar to #7373. I will consolidate this issue into it and close this one out. Please follow and subscribe to #7373 for updates or any comments you may have.
