### ISSUE TITLE
Missing configuration in React-native for Analytics and S3 bucket. 

### ISSUE THREAD

**Issue by birken92** [aws-amplify/amplify-js#4953]
**Describe the bug**
Auth.currentAuthenticatedUser() works fine and returns the objects. 

However, when trying to implement pinpoint and S3 there are credentials issue. Where the credentials are not set in React-native. 

The debug form is like this: 
[DEBUG] 18:19.748 AuthClass - getting session success {some session object}
[DEBUG] 18:19.749 Credentials - set credentials from session
[DEBUG] 18:20.10 Credentials - Failed to load credentials {credentials error object}
[DEBUG] 18:20.13 AuthClass - getting session failed [NotAuthorizedException: Token is not from a supported provider of this identity pool.]
[DEBUG] 18:20.14 Credentials - setting credentials for guest
[DEBUG] 18:20.47 Credentials - Failed to load credentials

**To Reproduce**
    "amazon-cognito-identity-js": "^3.2.4",
    "aws-amplify": "2.2.5",
    "aws-amplify-react-native": "^3.2.2",

    "react-native": "^0.61.5",
    "react": "16.9.0",

**Screenshots**
<img width="420" alt="Screen Shot 2020-02-20 at 2 30 35 pm" src="https://user-images.githubusercontent.com/45704978/74898291-9592c580-53ed-11ea-825b-e2a4d76ca5bd.png">

**Comment by birken92** [comment]
@sammartinez any updates?

**Comment by BabyDino** [comment]
Same issue here. We are trying to implement pinpoint and it seems that the `credentials` var is null.

**Comment by amhinson** [comment]
@birken92 Could you provide your `aws-exports` file and/or any manual configuration you've added?

_Be sure to remove any sensitive data_, i.e.:
```
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:xxx-xxxx-xxxx-xxxx-xxxxxxxx",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xxx",
    "aws_user_pools_web_client_id": "xxxx",
    "oauth": {}
};
```

**Comment by birken92** [comment]
@amhinson 

  Auth: {
    storage: AmplifyStorage,
    identityPoolId: 'ap-southeast-2:xxxxxxxx',
    region: 'ap-southeast-2',
    userPoolId: 'ap-southeast-2_xxxxxx',
    userPoolWebClientId: 'xxxxxxx',
    authenticationFlowType: 'USER_PASSWORD_AUTH',
  },
  Storage: {
    AWSS3: {
      bucket: 'some-bucket', //REQUIRED -  Amazon S3 bucket
      region: 'ap-southeast-2', //OPTIONAL -  Amazon service region
    },
  },
  Analytics: {
    AWSPinpoint: {
      appId: 'xxxxxx',
      region: 'ap-southeast-2',
    },
  },
};

here are my configuration file.

**Comment by amhinson** [comment]
> [DEBUG] 18:20.13 AuthClass - getting session failed [NotAuthorizedException: Token is not from a supported provider of this identity pool.]

@birken92 Based on this error message, could you check the identity pool via the Cognito Console -> Manage Identity Pools -> (select Identity Pool for your app) -> Edit Identity Pool -> Authorization Providers. Do you see the user pool info in the Cognito tab?
