### ISSUE TITLE
Can't get data from database: Possible Unhandled Promise Rejection Object

### ISSUE THREAD

**Issue by dimonchik-com** [aws-amplify/amplify-js#4954]
Hi, all! Each day I try use amplify-js and each day I encounter with diff problem. Today I try run next ease code

```
  useEffect(() => {
    getData()
  }, []);

  async function getData() {
    const todoData = await API.graphql(graphqlOperation(listWords));
    console.log(todoData);
  }
```

and got next error Possible Unhandled Promise Rejection Object {} https://prnt.sc/r531vq
Code https://github.com/dimonchik-com/newbugamplify
Maybe someone can tell me where error?

**Comment by manueliglesias** [comment]
Hi @dimonchik-com 

Is the *warning* you see related to the `API.graphql` call? (e.g., if you comment it out, does it go away?)

If it is related, can you try going to the AppSync console and run your `listWords` query from there and see if you get data back?

Also, can you copy/paste and anonymize your `aws-exports.js`?

**Comment by dimonchik-com** [comment]
@manueliglesias thx for you answer I try create new project from scratch https://github.com/aws-amplify/amplify-js/issues/4962 and anonymise my aws-exports.js

**Comment by manueliglesias** [comment]
Closing in favor of #4962

**Comment by igorkosta** [comment]
@dimonchik-com I know it was a long time ago but, in case you remember, could you share with me how you fixed the issue or at least what was the problem in your case?
I'm having the same problem and have no freaking idea how to fix it or what exactly fails.
