### ISSUE TITLE
Auth.federatedSignIn does not emit signIn event and Promise resolves instantly with undefined credentials

### ISSUE THREAD

**Issue by r301** [aws-amplify/amplify-js#4955]
**Describe the bug**
In an Electron app (without React), `Auth.default.federatedSignIn({provider: 'Google'})` does not emit the `signIn `event on the `auth `channel even though authentication is successful. Furthermore, the Promise returned is resolved instantly (while the Google login page is still loading) and credentials are undefined (rightfully as the user hasn't logged in yet). 
This behavior happens although `Auth.default.signIn(email, password)` works totally fine and gives the expected results (Hub catches the `signIn` event).

**To Reproduce**

1. In an Electron app, import the '@aws-amplify/core' and '@aws-amplify/auth' npm modules.
2. Manually configure the Amplify object (provide identityPoolId, region, userPoolId, oauth, etc).
3. Get the Hub object from '@aws-amplify/core' and listen to the 'auth' channel.
4. Call `
Auth.default.federatedSignIn({provider: 'Google'}).then(cred=>{
            console.log(cred);
        }).catch(e => {
            console.log(e);
        });
`
5. Results: .`then()` is called, `cred` is logged (undefined), the Google sign in page loads.
6. Authenticate with your Google account credentials. OAuth messages should look normal.
7. You should be redirected to the `redirectURI` you've provided with the `code` and `state ` URL parameters. 

**Expected behavior**
Upon authentication with a Google account, the Hub should catch a `signIn` event or the Promise should be resolved/rejected only once the authentication is a success or a failure. 

**Screenshots**

<details>
  <summary><strong>Environment</strong></summary>

```
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 25.98 GB / 31.96 GB
  Binaries:
    Node: 10.16.0 - D:\Programs\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.11.2 - D:\Programs\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
    Internet Explorer: 11.0.18362.1
  npmPackages:
    aws-sdk: ^2.622.0 => 2.622.0
    bootstrap: ^4.4.1 => 4.4.1
    electron: ^5.0.13 => 5.0.13
    electron-builder: ^21.2.0 => 21.2.0
    firstline: ^2.0.2 => 2.0.2
    jquery: ^3.4.1 => 3.4.1
    mkdirp: ^0.5.1 => 0.5.1
    net: ^1.0.2 => 1.0.2
    popper.js: ^1.16.1 => 1.16.1
    request: ^2.88.2 => 2.88.2
    request-progress: ^3.0.0 => 3.0.0
    rimraf: ^2.7.1 => 2.7.1
    yauzl: ^2.10.0 => 2.10.0

  "@aws-amplify/auth": "^2.1.5",
  "@aws-amplify/core": "^2.2.4",
```

</details>

**Sample code**
```
"use strict";

const Amplify = require('@aws-amplify/core');
const { Hub } = require('@aws-amplify/core');
const Auth = require('@aws-amplify/auth');

Amplify.default.configure({
    Auth: {

        // REQUIRED only for Federated Authentication - Amazon Cognito Identity Pool ID
        identityPoolId: [my cognito useridentitypool id],
        
        // REQUIRED - Amazon Cognito Region
        region: [my aws region],

        // OPTIONAL - Amazon Cognito User Pool ID
        userPoolId: [my cognito userpool id],

        // Your client id here
        userPoolWebClientId : [my cognito app id], 

        // OPTIONAL - Enforce user authentication prior to accessing AWS resources or not
        mandatorySignIn: true,
       
        // OPTIONAL - Manually set the authentication flow type. Default is 'USER_SRP_AUTH'
        authenticationFlowType: 'USER_SRP_AUTH',

        oauth: {
            domain: [my cognito domain],
            scope: ['email', 'openid'],
            redirectSignIn: 'http://localhost:8000',
            redirectSignOut: 'http://localhost:8000',
            responseType: 'code' 
        }
    }
});

Hub.listen('auth', (data) => {
    console.log('Hub event');
    switch (data.payload.event) {
        case 'signIn':
            console.log('Hub: now the user is signed in');
            break;
        case 'signIn_failure':
            console.log('Hub: the user failed to sign in');
            console.log('the error is', data.payload.data);
            break;
        case 'signOut':
            console.log('Hub: the user signed out');
            break;
        default:
            console.log('Hub default');
            break;
    }
});

//HTML, Javascript to call one of these methods

Auth.default.federatedSignIn({provider: 'Google'}
        ).then(cred=>{
            console.log("federatedSignIn then");
            console.log(cred);
        }).catch(e => {
            console.log("federatedSignIn catch");
            console.log(e);
 });

Auth.default.signIn(email, password
   ).then(user => console.log(user)
   ).catch(err => console.log(err));
```
When callling `signIn`:
![signin](https://user-images.githubusercontent.com/61284929/74959571-1e6c2a00-540b-11ea-8454-3dbe725da3fd.JPG)

When callling `federatedSignIn`:
![federatedSignin](https://user-images.githubusercontent.com/61284929/74958998-224b7c80-540a-11ea-8819-421f52506a48.JPG)

And once signed in:
![federatedSignedIn](https://user-images.githubusercontent.com/61284929/74959763-7c990d00-540b-11ea-99cf-bb5d23ea86a6.JPG)

**Comment by sammartinez** [comment]
@r301 Currently, Amplify does not support Electron within our project. I am marking this as a feature request so we can evaluate supporting this in the future. Im also marking this as a good first issue/help wanted to see if the community of Amplify have use cases similar to yours.

**Comment by r301** [comment]
Sounds good, thanks a lot. I've had a look at the implementation of the auth events. It looks like the implementation of the urlListener doesn't really suit the Electron architecture right now. In the meantime, I've found a workaround. I simply manually call `Auth.handleAuthResponse(authResponseUri);` when the login process is complete (whether it's a success or a failure). How you handle the redirects (in a new or the BrowserWindow) doesn't really matter, as long as you catch the response url (to be parsed in `handleAuthResponse`) with something like `myBrowserWindow.webContents.session.webRequest.onBeforeRequest()`.

**Comment by cwardcode** [comment]
So that people of the future may know what to do. `Auth.default._handleAuthResponse(authResponseUri);` is now private, and the class is no longer exported as default. To actually use this function now, you need to first cast Auth as an 'any' type, then call _handleAuthResponse(), like this:

`(Auth as any)._handleAuthResponse(authResponseUri)`
