### ISSUE TITLE
CookieStorage should handle the "SameSite" attribute.

### ISSUE THREAD

**Issue by guanzo** [aws-amplify/amplify-js#4958]
**Is your feature request related to a problem? Please describe.**
Cookies are going to be `samesite=lax` by default in Chrome 80. aws-amplify should allow users to set the samesite value.

**Describe the solution you'd like**
The [CookieStorage class](https://github.com/aws-amplify/amplify-js/blob/c28851a6379f3ba05c4fef529bb5be7f18ebe316/packages/amazon-cognito-identity-js/src/CookieStorage.js) should handle the `samesite` attribute. Currently it only handles `domain`, `path`, `expires`, and `secure`. 

**Additional context**
aws-amplify uses js-cookie. js-cookie already supports the samesite attribute, so aws-amplify should too. 

EDIT: This change should take 5 minutes at most. It's simply a matter of adding another property to check for, since you just forward them to js-cookie anyways. I get that this library is drowning in issues and technical debt, but this is a rather simple change that doesn't affect other areas of the code base.

**Comment by ismyrnow** [comment]
We're in need of this as well. Our use case is that some customers iframe parts of our app into their portals and internal websites. This functionality breaks in the latest stable version of Chrome unless we add the `samesite` attribute.

I'm willing to open a pull-request for this, following the contribution guidelines, if I can get the go ahead from a repo owner.

**Comment by meddjelaili** [comment]
> We're in need of this as well. Our use case is that some customers iframe parts of our app into their portals and internal websites. This functionality breaks in the latest stable version of Chrome unless we add the `samesite` attribute.
> 
> I'm willing to open a pull-request for this, following the contribution guidelines, if I can get the go ahead from a repo owner.

I needed this too on a Shopify app, So I used this workaround after calling the signIn method
`
document.cookie.split(';').forEach((cookie) => {
    // delete existing
    document.cookie = cookie.split('=')[0] + '=; expires=Thu, 01 Jan 1970 00:00:00 UTC;';
    // create new one
    document.cookie = cookie + '; path=/; max-age=2592000‬; sameSite=None; secure';				});
`

**Comment by ismyrnow** [comment]
I should add that we went ahead and implemented our own CookieStorage class, copying the existing one and adding samesite support. The solution works well until #5726 gets approved.

**Comment by ericclemmons** [comment]
Fixed via #5726 

This will be released soon!

**Comment by meddjelaili** [comment]
> Fixed via #5726
> 
> This will be released soon!

why only Lax and Strict? None should be a valid value too

**Comment by meddjelaili** [comment]
@ericclemmons can you please check this; It's critical for a project I'm working on

**Comment by ericclemmons** [comment]
@meddjelaili Merged and released!

**Comment by meddjelaili** [comment]
legend

**Comment by guanzo** [comment]
Is this only released for `@aws-amplify/auth` v3? If so, could you also release it for v2? v3 has major breaking changes, and I can't upgrade yet, but I need to be able to configure the same site setting now, with v2.

**Comment by roy-sa** [comment]
Is this issue actually fixed?
from my testing, I could not set the sameSite=None and Secure.

`cookieStorage: {
      domain: "somedomain.com"
      path: "/",
      expires: 1,
      secure: true,
      sameSite: "none"
    }`

dependency:
"aws-amplify": "~4.2.2",
"aws-amplify-react": "~5.0.8
