### ISSUE TITLE
Userpool Signup clientMetadata Type is missing

### ISSUE THREAD

**Issue by rakesh0r** [aws-amplify/amplify-js#4960]
Signup method clientMetadata parameter type is missing in `index.d.ts`.

<img width="1624" alt="Screen Shot 2020-02-21 at 2 12 15 PM" src="https://user-images.githubusercontent.com/3204611/75018029-3f3c8a00-54b4-11ea-9e7c-6354b4895e42.png">

**Comment by dragulescu** [comment]
we also ran into this issue. just adding some support for this PR which only requires a line change in the TS type declaration. thanks!  🙏  @elorzafe
