### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0): Object {}

### ISSUE THREAD

**Issue by dimonchik-com** [aws-amplify/amplify-js#4962]
Guys i really don't know what happen but at the current moment i event can't run simple example from you documentation. I upload my all code on github https://github.com/dimonchik-com/TestAmplify with open aws-exports.js I hope this helps somehow resolve the problem

First step I create a blank project
npx react-native init TestAmplify --template react-native-template-typescript
Then install all dependencies
npm install aws-amplify
npm install aws-amplify-react-native
cd ios && pod install && cd ..
npm install aws-amplify-react

And then try run you code from documentation and i got next error Possible Unhandled Promise Rejection (id: 0): Object {} https://prntscr.com/r5n7ks
I try to run any code with lates amplufy-js third day and unfortunately nothing does not work. I will really very appreciate if you say me what I'm did wrong.

**Comment by manueliglesias** [comment]
Thank you for the steps to reproduce! 😃 
I am taking a look at it

**Comment by dimonchik-com** [comment]
Hi @manueliglesias !
Any news about this problem. Can I remove the aws-exports.js because if I right understand it not security for my account?

**Comment by ashika01** [comment]
@dimonchik-com You should definitely remove your aws-exports and expire any token exposed. It sure is a security risk.

**Comment by amhinson** [comment]
@dimonchik-com I see that your sample repo is no longer available. Are you still having issues?

**Comment by igorkosta** [comment]
@manueliglesias @amhinson  I know it was a long time ago but, in case you remember, could you share with me how you fixed the issue or at least what was the problem?
I'm having the same problem and have no freaking idea how to fix it or what exactly fails.

**Comment by amhinson** [comment]
@igorkosta Do you have a sample repo we could take a look at and reproduce the issue you are seeing?

**Comment by igorkosta** [comment]
For everyone who's potentially experiencing the same issue. I had to update the `aws-amplify` package to the latest version and `nuke` and reinstall everything. I also removed the unused `@aws-amplify/api` and `@aws-amplify/pubsub`  but I don't think it had any effect.

So, in a nutshell what I did was:

```sh
npm i -S aws-amplify@latest
rm -rf node_modules/ && rm -f package-lock.json && rm -f yarn.lock && npm cache verify && npm install && expo r -c
```
