### ISSUE TITLE
Normalize the Import Structure for API, Auth, etc.

### ISSUE THREAD

**Issue by fireflysemantics** [aws-amplify/amplify-js#4964]
**Is your feature request related to a problem? Please describe.**
IIUC Amplify uses default exports for `Auth`, etc.  Ideally we would import `Auth` the same way we import `API`.  Current:

```
import Auth from '@aws-amplify/auth';
import { API } from 'aws-amplify'
```
Ideal:

```
import { Auth, API } from '@aws-amplify'
```
## Update

Just noticed that `@angular/material` makes us import each module from it's specific path.  So for the button module we need to import `@angular/material/button`.  IIUC this is in order to make tree shaking work optimally.  So perhaps to import `Auth` we need:

`import { Auth } from '@aws-amplify/auth`

And for API:

`import { API } from '@aws-amplify/api`

Also see [Why we have banned default exports in Javascript and you should do the same](https://blog.neufund.org/why-we-have-banned-default-exports-and-you-should-do-the-same-d51fdc2cf2ad)

I also just realized that the `API` import does not use the `@` in front of `aws-amplify` ...

**Comment by sammartinez** [comment]
@fireflysemantics In our version 3 of Amplify JS we do have the ability to import as the ideal. Please see our [`index.js`](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify/src/index.ts) file for our `aws-amplify` package for more information on this. I'm going to resolve this feature request as the above. Please let me know if this not what you were looking for and we can reopen.
