### ISSUE TITLE
Changing language and adding more target languages in amplify predictions

### ISSUE THREAD

**Issue by KhalidBhyan** [aws-amplify/amplify-js#4968]
I'm using aws-amplify predictions with NodeJS for my back-end i18n, everything is working fine but I faced two problems:
- How to change the target language in runtime?
- How to add more target languages?

**Edit:**
solved using this implementation:
```
Predictions.convert({
    translateText: {
      source: {
        text: yourTextToTranslate,
        language : "es" /* <- change source language here */
      },
      targetLanguage: "en" /*<- change target language here */
    }
))
```

**Comment by vardan099** [comment]
Did you find How to change the target language in runtime?
I have the same issue

**Comment by KhalidBhyan** [comment]
@vardan099 check the solution above, I edited the original question
