### ISSUE TITLE
Invalid Refresh Token.

### ISSUE THREAD

**Issue by stripathix** [aws-amplify/amplify-js#498]
Bug.

**Configuration:**
1) I have set refresh token expiry to 3064 days
2) I have setting Device Tracking as ALWAYS

Code to refresh Session I have:

`if (cognitoUser !== null) {

                cognitoUser.getSession(function (err, oldSession) {
                    if (!err) {
                        var refreshToken = oldSession.getRefreshToken();
                        console.log("Refreshing session");
                        cognitoUser.refreshSession(refreshToken, function (err, refreshedSession) {
                            if (!err) {
                                console.log("Session refreshed successfully!");
                                var logins = {};
                                logins[cognitoEndpoint + "/" + poolData.UserPoolId] = refreshedSession.getIdToken().getJwtToken();
                                AWS.config.credentials = new AWS.CognitoIdentityCredentials({
                                    IdentityPoolId: identityPoolId,
                                    Logins: logins
                                });
                                // Make the call to obtain credentials
                                AWS.config.credentials.get(function () {
                                    console.log("Success credentials");
                                    refreshingToken = false;
                                    client = new AWS.CognitoSyncManager();
                                    if (client) {
                                        client.openOrCreateDataset(bnDataSetName, function (err, dataset) {
                                            if (!err) {
                                                bnUserPreferencesDataset = dataset;
                                            } else {
                                                errorLogService(err);
                                            }
                                        });
                                    }
                                });
                                deferred.resolve(true);
                            } else {
                                err.message = "ResumeAppplicationCognito: Not able to refresh session: User " + cognitoUser.username + ":" + err.message;
                                err.emailTried = cognitoUser.username;
                                if (!err.code.match(new RegExp(AppConst.exceptionsCodes.UserNotFoundException)) && !err.message.match(new RegExp(AppConst.exceptionsCodes.incorrectPassword))) {
                                    errorLogService(err);
                                }
                                deferred.resolve(false);
                            }
                        });
                    }
                });
            }`

I got this error due to some reason:

`code: NotAuthorizedException, 
column: 1837305, 
emailTried: jo****@yahoo.com, 
line: 1, 
message: User jo****yahoo.com : Invalid Refresh Token., 
name: NotAuthorizedException, 
requestId: a64f28e6-2cd2-11e8-9102-45d988484951, 
retryable: False, 
retryDelay: 58.95665571402836
, 
statusCode: 400, 
time: 2018-03-21T06:39:48.215Z
}
`

**Comment by mlabieniec** [comment]
@stripathix it looks like based on that error that you may just be sending the incorrect token to the refresh method. One thing to note, if you use the amplify lib this will all be automated for you.  The refresh occurs in the background (in amplify) if it is required and is cached/managed for you as well.

There is also a PR from @tipsfedora on documentation for session refresh:
https://github.com/aws/aws-amplify/pull/499/files

are you certain the value returned from: `var refreshToken = oldSession.getRefreshToken();` is valid?

**Comment by stripathix** [comment]
Thanks, @mlabieniec.  Yeah, I am sure that refresh token is valid if the configuration of setting refresh token expiry to 3064 is working right because my app is like 2-3 months old and this was a new user so his refresh token should be valid.

I am not using aws-amplify rather I am using following:

"amazon-cognito-identity-js": "1.31.0",
 "amazon-cognito-js": "1.1.0",
"aws-sdk": "2.152.0",

**Comment by yuntuowang** [comment]
Hi @stripathix, did you always use the same user pool id and client id? Did this issue happen intermittently or you always see this issue? Thanks!

**Comment by stripathix** [comment]
Hi @yuntuowang, 
Sorry for late response.

I always use same user pool id, but different client id. I have one clientId for Web applicaition and another for Cordova mobile application.
My Pool configuration looks like this:
`  var poolData = {
            UserPoolId: AccountConst.awsCognito.userPoolId,
            ClientId: utilityService.isCordovaApplication()
                ? AccountConst.awsCognito.clientIdMobile
                : AccountConst.awsCognito.clientIdWeb
        };`

This issue happens intermittently, I am not able to find an exact scenario for this, but I can tell this is something we started seeing from the last 3-4 weeks frequently.

**Comment by yuntuowang** [comment]
Hi @stripathix, thank you so much for the info. We will investigate this issue and I will post the newest status ASAP. Thanks!

**Comment by stripathix** [comment]
Hi @yuntuowang,  any update on this? We are still getting lots of error logs related to invalid refresh token.

**Comment by shridharns** [comment]
@stripathix The refresh_token is bound to the app client that generated it. Only that app client can be used to generate a new access/id token using that refresh token. This is the same use-case even we have, so tested this. Additionally, found this SOF link as well: https://stackoverflow.com/a/43195252/2994423

**Comment by stripathix** [comment]
@shridharns We have two platforms web/Cordova. 
Web uses client XXX
Cordova mobile app uses client YYY

Even if refresh token is tied to the app client that generated it, why would I get Invalid refresh Token, because website will always use XXX app client and Cordova will always use YYY app client to generate refresh token?

I am not using same refresh token for different app clients. 

When authentication is done for web then tokens are saved in Localstorage of web browser, now next time to generate new access token, refresh token is pulled from localstorage and request is made to get new access token. Same happens for Cordova mobile app.

Does login into one platform using app client XXX and then doing login into another platform using app client YYY has any effect on refresh token?

**Comment by jwdinker** [comment]
I am having the same issue.  This has worked in the past as well.  I generate the tokens and then even try to refresh them afterwards and it throws an InvalidTokenError.

**Comment by tcchau** [comment]
@stripathix This is a long shot, but have you tried turning off Device Tracking in your user pool, if it's currently on, to see if it makes a difference?

I'm still investigating my particular problem: using Amplify for Auth and the migration trigger seems to result in a User object being returned that doesn't have a device key cached to local storage. Thus, when I used Auth.currentSession() to refresh the session, Amplify tries to use InitiateAuth with REFRESH_TOKEN_AUTH to get a new set of credentials, but DEVICE_KEY is set to null. 

If the associated User Pool is set to use Device Tracking, then InitiateAuth will error out with NotAuthorizedException: Invalid refresh token. However, if I turn Device Tracking off, then the session is refreshed as expected.

**Comment by cevatkerim** [comment]
This is the exact issue we were having. Turning off device tracking fixed it.

**Comment by bernhardt1** [comment]
I had the same issue appearing sporadically. It appears to be related to facebook rate limiting https://developers.facebook.com/docs/graph-api/advanced/rate-limiting

I noticed that my application rate limit status was above 100% whenever I got the **'Invalid login token. Token is expired.'** Error.

As far as I can tell I only call the facebook API with the following calls during login:
- Expo.Facebook.logInWithReadPermissionsAsync
- Auth.federatedSignIn("facebook")

When I do make those calls the rate limit current usage percentage jumps up roughly 8%... Seems to use a lot of facebook calls to do a login.

**Comment by moreta** [comment]
@tcchau Thank you.
Turn off Device Tracking fixed it.

I'm also use, user migration trigger.
Maybe DEVICE_KEY parameter and Device Tracking involved.

Before,  Devices tracking setting  to "Always", i got error like this.

Request 

* URL: https://cognito-idp.ap-northeast-1.amazonaws.com/
* X-Amz-Target: AWSCognitoIdentityProviderService.InitiateAuth

* Payload

```
{
"ClientId": "your client id",
"AuthFlow": "REFRESH_TOKEN_AUTH",
"AuthParameters": {
"DEVICE_KEY": null,
"REFRESH_TOKEN": "your refresh token.."
  }
}
```

Response

```
{"__type":"NotAuthorizedException","message":"Invalid Refresh Token."}
```

**Comment by dmks** [comment]
Thank you @tcchau, we have the same issue, turning off the Device Tracking fixed it, however, what if I want to use both USER_PASSWORD_AUTH and Device Tracking feature? any solution or workaround?

**Comment by jordanranz** [comment]
@dmks,

Have you tried the solution accepted in the follow stackoverflow:
https://stackoverflow.com/questions/46879876/aws-cognito-invalid-refresh-token

I will mark this with the Service Team label so we can discuss with the Cognito team if the above solution does not work..

**Comment by powerful23** [comment]
Closing this due to no further response.

**Comment by fenetic** [comment]
For anyone hitting this issue in 2021:

We have implemented an authentication flow with a custom UI using Amplify. Our flow depends on user device tracking so that we can limit the presentation of the MFA challenge on subsequent logins within a timeframe.

Following the Amplify documentation, we were led to believe that calling `Auth.setPreferredMFA('TOTP')` was a necessary step to enforce TOTP MFA, however, this led to the "invalid token refresh' response as detailed in this thread.

It turns out that if a Cognito user pool is configured to enforce TOTP MFA (possibly also SMS), then you do not need to call `Auth.setPreferredMFA` as part of the MFA setup step.
