### ISSUE TITLE
additionalHeaders param is never passed to underlying function -- How do I access the current request headers or set them per request?

### ISSUE THREAD

**Issue by jensbodal** [aws-amplify/amplify-js#4981]
**Which Category is your question related to?**

`API`

**What AWS Services are you utilizing?**

`graphql` via AWS AppSync

**Provide additional details e.g. code snippets**

Foremost, I'd like to ask if this was intentional to include the `additionalHeaders` param in the private `_graphql` function but never use it in any calling function (https://github.com/aws-amplify/amplify-js/blob/master/packages/api/src/API.ts#L380) .

It would seem the signature of the `graphql` function should be 

```
graphql({ query: paramQuery, variables = {}, authMode }, additionalHeaders = {})
```

Would a PR be accepted which passes the `additionalHeaders` param to the function? 

Otherwise, how do I access the request headers or set them on a per request basis? Currently we add a `traceid` header with each request by passing an async function at config time.

```
    Amplify.default.configure({
      API: {
        graphql_headers: async () => ({
          traceid: `${prefix}-${uuidv4()}`,
        }),
      },
    });
```

When graphql comes back with an error, we log the error and we would also like to log the `traceid`. The problem is we don't know what the `traceid` is set to and there is not a reliable way to know this as two simultaneous requests could change the `traceid` prior to logging.

The only option I can think of which would rely on a tight coupling to the implementation details of amplify-js would be to use axios request interceptors and handle errors there.  

Is there a proper way to do this?

**Comment by jensbodal** [comment]
For now I am patching the original method until I know how to better proceed.

```
  let traceid;

  if (!apiPatched) {
    apiPatched = true;

    const privateApi = (API as any)._api.post.bind((API as any)._api);
    (API as any)._api.post = (endpoint: string, init: any) => {
      ({ traceid } = init.headers || {});
      return privateApi(endpoint, init);
    };
  }
```

**Comment by manueliglesias** [comment]
> Would a PR be accepted which passes the `additionalHeaders` param to the function?

That would be great! 😄 

The axios interceptor option is also a good one since we are not planning on replacing it with another library, and if we ever do, it is going to be considered a breaking change and a new major version would be released.

**Comment by jensbodal** [comment]
We already had abstracted the gql client to a service, so basically all of our gql calls would go through there even though it was a fairly light wrapper around amplify gql client. So we were able to just apply the patch in that service.  If you can't do that, a more fragile approach would be to hook into axios' hooks (which was being used at the time of this issue behind the scenes to make the requests) to apply the patch for all calls.

Though you shouldn't have to do any of this now. The PR was merged in.
