### ISSUE TITLE
Storage.put causing A header you provided implies functionality that is not implemented error

### ISSUE THREAD

**Issue by nara** [aws-amplify/amplify-js#4982]
**Describe the bug**
I am using amplify as part react native project. Storage.put call returns an error
A header you provided implies functionality that is not implemented.

This happens only on iOS, not on android. After looking at request/response, this call on iOS adding If-None-Match header.

How can i change code to avoid sending this header?

Request Headers:
PUT /public/path/menu.json HTTP/1.1
Host: bucketname.s3.amazonaws.com
Accept: */*
Authorization: 
x-amz-content-sha256;x-amz-date;x-amz-security-token;x-amz-user-agent, Signature=
content-md5: Dfkqc98JGB+ynzxOk4tzaA==
If-Modified-Since: Tue, 25 Feb 2020 18:35:16 GMT
x-amz-date: 20200225T234024Z
x-amz-security-token: token
x-amz-user-agent: aws-sdk-js-react-native/2.624.0 callback
Accept-Encoding: br, gzip, deflate
Accept-Language: en-us
If-None-Match: "d1a5485b202d67d4dbce954297042dc5"
Content-Type: application/json
Content-Length: 4366
x-amz-content-sha256: UNSIGNED-PAYLOAD
User-Agent: Expo/2.14.0.107619 CFNetwork/978.0.7 Darwin/19.3.0
Connection: keep-alive

Here is the response

<Error>
	<Code>NotImplemented</Code>
	<Message>A header you provided implies functionality that is not implemented</Message>
	<Header>If-None-Match</Header>
	<RequestId>89359668FEDABAFC</RequestId>
	<HostId>TkGbElAdM4spaY1R9BATjCnf1wbEnF0bYEz/sUw0muww4dE69qGooNywdl90qrrCyNemA/YEmeI=</HostId>
</Error>

**To Reproduce**

amplify -v 4.13.4
expo 3.13.1
using a sample call Storage.put

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone Xr]
- OS: [e.g. iOS12.4]

**Comment by annjawn** [comment]
+1. I am facing this issue as well. Only in iOS, Android seems to be fine.

**Comment by antwaven** [comment]
+1. Amplify seems to add If-None-Match randomly to API calls for me as well. Would be good to know how to avoid.

**Comment by pperron** [comment]
+1. Same thing, works fine on Android, Storage.Put fails with the error on IOS...

**Comment by SlimKh** [comment]
Hi! Same for me :(
Did anyone find a workaround ?

**Comment by pperron** [comment]
Hi,
I decided to updated my amplify packages to latest versions and solved that issue for me. But after updating, it caused an other issue when using Storage.get with JSON files, needed to change a bit the code to get the JSON content...

**Comment by SlimKh** [comment]
> Hi,
> I decided to updated my amplify packages to latest versions and solved that issue for me. But after updating, it caused an other issue when using Storage.get with JSON files, needed to change a bit the code to get the JSON content...

@pperron, thank you, worked for me.

**Comment by mauerbac** [comment]
hi @nara - by any chance, does updating to the latest version help?

**Comment by nara** [comment]
hi @mauerbac, I didn't get a chance to test this because I had a workaround at that time. Previous comments indicate it worked by upgrading to latest. This can be closed. Thank you.
