### ISSUE TITLE
Make HubCallback type to return any

### ISSUE THREAD

**Issue by Mighty683** [aws-amplify/amplify-js#4983]
I want attach `async function` to `Hub.listen` in Typescript

But because `HubCallback` type is returning void it's preventing from using  async functions.
`export declare type HubCallback = (capsule: HubCapsule) => void;`

Proposition to change type of hub callback to return `any`:
`export declare type HubCallback = (capsule: HubCapsule) => any;`

**Comment by arlyon** [comment]
Is a better solution not to simply make it `void | Promise<void>`?
