### ISSUE TITLE
Auth.currentAuthenticatedUser() throws after signing in with Google post redirect

### ISSUE THREAD

**Issue by fireflysemantics** [aws-amplify/amplify-js#4988]
**Describe the bug**
Auth.currentAuthenticatedUser() throws after signing in with Google post redirect

**To Reproduce**

1. Create an App that signs in with Google
2. Sign in with Google
3. In the application constructor call Auth.currentAuthenticatedUser()
4. In the first call it will throw because it can't get an authenticated user on the first try
5) On the second try if the browser is manually refreshed it will get a user

-- or --

Link to sample code
I wrote this medium article on how to setup Google Login.
https://medium.com/@ole.ersoy/adding-aws-cognito-federated-login-with-google-using-aws-amplify-78bf68f19c68

Also asked about this on SO:
https://stackoverflow.com/questions/60424478/angular-router-does-not-react-to-cognito-redirect/60425333#60425333

**Expected behavior**
`Auth.currentAuthenticatedUser()` should return the authenticated user on the first attempt post logging in with a social provider. 
**Screenshots**

<details>
  <summary><strong>Environment</strong></summary>

```
ole@mkt:~/Temp/amplify-google-login-test$ npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
npx: installed 1 in 1.521s

  System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 1.43 GB / 7.58 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.10.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.122
    Firefox: 73.0.1
  npmPackages:
    @angular-devkit/build-angular: ~0.900.0-rc.3 => 0.900.0-rc.8 
    @angular/animations: ~9.0.0-rc.3 => 9.0.0-rc.8 
    @angular/cdk: ~8.2.3 => 8.2.3 
    @angular/cli: ~9.0.0-rc.3 => 9.0.0-rc.8 
    @angular/common: ~9.0.0-rc.3 => 9.0.0-rc.8 
    @angular/compiler: ~9.0.0-rc.3 => 9.0.0-rc.8 
    @angular/compiler-cli: ~9.0.0-rc.3 => 9.0.0-rc.8 
    @angular/core: ~9.0.0-rc.3 => 9.0.0-rc.8 
    @angular/forms: ~9.0.0-rc.3 => 9.0.0-rc.8 
    @angular/language-service: ~9.0.0-rc.3 => 9.0.0-rc.8 
    @angular/material: ^8.2.3 => 8.2.3 
    @angular/platform-browser: ~9.0.0-rc.3 => 9.0.0-rc.8 
    @angular/platform-browser-dynamic: ~9.0.0-rc.3 => 9.0.0-rc.8 
    @angular/router: ~9.0.0-rc.3 => 9.0.0-rc.8 
    @fireflysemantics/angular-stripe-service: ^1.0.0 => 1.0.0 
    @fireflysemantics/slice: ^9.0.17 => 9.0.17 
    @types/jasmine: ~3.4.0 => 3.4.6 
    @types/jasminewd2: ~2.0.3 => 2.0.8 
    @types/node: ^12.11.1 => 12.12.24 
    aws-amplify: ^2.2.1 => 2.2.1 
    aws-amplify-angular: ^4.1.5 => 4.1.5 
    codelyzer: ^5.1.2 => 5.2.1 
    cuid: ^2.1.8 => 2.1.8 
    hammerjs: ^2.0.8 => 2.0.8 
    jasmine-core: ~3.5.0 => 3.5.0 
    jasmine-spec-reporter: ~4.2.1 => 4.2.1 
    karma: ~4.3.0 => 4.3.0 
    karma-chrome-launcher: ~3.1.0 => 3.1.0 
    karma-coverage-istanbul-reporter: ~2.1.0 => 2.1.1 
    karma-jasmine: ~2.0.1 => 2.0.1 
    karma-jasmine-html-reporter: ^1.4.2 => 1.5.1 
    ngx-take-until-destroy: ^5.4.0 => 5.4.0 
    protractor: ~5.4.2 => 5.4.2 
    rxjs: ~6.5.3 => 6.5.4 
    ts-node: ~8.3.0 => 8.3.0 
    tslib: ^1.10.0 => 1.10.0 
    tslint: ~5.18.0 => 5.18.0 
    typescript: ~3.6.4 => 3.6.4 
    zone.js: ~0.10.2 => 0.10.2 
  npmGlobalPackages:
    @angular/cli: 9.0.0-rc.3
    @aws-amplify/cli: 4.13.4
    angular-cli-ghpages: 0.6.0
    install-peerdeps: 2.0.1
    madge: 3.4.4
    medium-2-md: 0.4.2
    mediumexporter: 0.1.6
    npm-bump: 0.0.28
    npm-install-peers: 1.2.1
    npm: 6.10.0
    ts-node: 8.3.0
    typescript: 3.5.3
    verdaccio: 4.4.0
    version-bump-prompt: 5.0.7

```

</details>

**Smartphone (please complete the following information):**

**Additional context**

**Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by fireflysemantics** [comment]
I think Hub has the right idea here.  The right way to update the app post redirect is to wait for a Hub to release a signin notification.

The app should create an Observable that perform centralized signin notification.

**Comment by elorzafe** [comment]
@fireflysemantics 

I merged a fix for this, currently is published to `unstable` tag on npm if you can try out. We will publish to `latest` soon.
