### ISSUE TITLE
Make Amplify datastore Nextjs friendly

### ISSUE THREAD

**Issue by mdegrees** [aws-amplify/amplify-js#4990]
**Is your feature request related to a problem? Please describe.**
Making an SSR page using Nextjs implies getting the initial state server side using `getInitialProps` helper function. With Amplify dataStore there seems to be no way to get the initial app state server side. 

**Describe the solution you'd like**
Ideally being able to call datastore.query inside `getInitialProps` (server side). 

**Additional context**
From [Amplify datastore documentation](https://aws-amplify.github.io/docs/js/datastore#how-it-works) it says : 

> The Sync Engine will run a GraphQL query on first start that hydrates the Storage Engine from the network using a Base Query.

Maybe make use of what @dabit3 did with AppSync https://github.com/dabit3/next-apollo-appsync/blob/master/src/withData.js

**Comment by simpleshadow** [comment]
See https://github.com/aws-amplify/amplify-js/issues/1613.

**Comment by ericclemmons** [comment]
This has been addressed as part of #6146!

Please see my synopsis on changes here: https://github.com/aws-amplify/amplify-js/issues/5435#issuecomment-692990722

Internally, DataStore won't run the sync engine when on the server: instead it will get all the data it needs to satisfy `DataStore.query(...)` and return it. No subscriptions needed :)
