### ISSUE TITLE
What authentication check should we perform in our Angular Authentication Guards?

### ISSUE THREAD

**Issue by fireflysemantics** [aws-amplify/amplify-js#4992]
** Which Category is your question related to? **
E.g. Auth, Predictions, Storage, etc.
Auth

** What AWS Services are you utilizing? **
Cognito

E.g. Sample code, versions of Amplify you are using

[In this article](https://itnext.io/part-2-adding-authentication-to-your-angular-material-aws-amplify-powered-pwa-2a9d0fbd305a) the author uses `Auth.currentAuthenticationUser()` in the `AuthGuard` like this:

```
  canActivate(
    next: ActivatedRouteSnapshot,
    state: RouterStateSnapshot): Observable<boolean | UrlTree> | Promise<boolean | UrlTree> | boolean | UrlTree {
    return Auth.currentAuthenticatedUser().then(() => { return true; })
      .catch(() => {
        this.router.navigate(['signin']);
        return false;
      });
  }
```
However [as noted in this issue](https://github.com/aws-amplify/amplify-js/issues/4988) this can throw even though the uses is authenticated and has been redirected, resulting in two redirects.  The first from Cognito and the second from the auth guard, since it does not "Think" that the user has been signed in yet.

So what should we call on `Auth` that will guarantee not to throw when the user is signed in via Federated Identities?

I think `Auth.currentSession()` will work but I wanted to double check with ya'll.

Thoughts?

Also tracking this on SO here:

https://stackoverflow.com/questions/60436826/what-authentication-check-using-the-auth-api-should-we-perform-in-our-angular-au

**Comment by fireflysemantics** [comment]
It seems in general we probably not assume that the authenticated user will be available immediately after the Cognito redirect.  

Since we can't do that we also cannot redirect to a protected resource, since the guard deny access.

Therefore we have to redirect to a non guarded page, and then wait for Amplify to tell us that authentication has taken place.

We can then use a Subject to notify other parts of the app.

Seems like the right way to listen (Until Angular 9 is support by `AngularService`) is to run both `Auth.currentAuthenticatedUser()` and `Hub.listen` in parallel.

Right after the redirect `Auth.currentAuthenticatedUser()` will most likely throw, but `Hub.listen` will eventually emit the `signin` event which we can `next` on our `Subject`.  

After that until the user signs out or the session times out, `Auth.currentAuthenticatedUser()` should always return a user, and we can `next` that on the `Subject` that we are using to observe authenticated state.

So that's how I plan to approach it.  Please let me know if you have any additions.

**Comment by elorzafe** [comment]
@fireflysemantics 

I merged a fix for this, currently is published to `unstable` tag on npm if you can try out. We will publish to `latest` soon.

Using `Auth.currentAuthenticatedUser()` for Auth Guard should work now when using OAuth flows with HostedUI
