### ISSUE TITLE
Angular package deep import warning

### ISSUE THREAD

**Issue by ShahoG** [aws-amplify/amplify-js#4999]
**Describe the bug**
aws-amplify-angular 4.1.7 throws Warning on build that may cause pipelines to fail when build is attempted with ivy enabled on angular 9

`WARNING in Entry point 'aws-amplify-angular' contains deep imports into '/opt/atlassian/pipelines/agent/build/node_modules/rxjs/Subject',`

**Expected behavior**
Build should pass

**Additional context**
Build passes on version 4.1.6 without issues

**Comment by jordanranz** [comment]
Hey @ShahoG,

`aws-amplify-angular` is not supported for Angular 9 as noted [here](https://aws-amplify.github.io/docs/js/angular#angular). Which components are you trying to use?

**Comment by ShahoG** [comment]
I have now moved on to use the new UI components instead and they work fine

**Comment by ericclemmons** [comment]
I highly recommend upgrading to `@aws-amplify/ui-angular` (per @jordanranz's response above).

Additionally, https://github.com/aws-amplify/amplify-js/pull/4862 fixes this in `aws-amplify-angular` (https://www.npmjs.com/package/aws-amplify-angular), which should unblock you while you migrate to `@aws-amplify/ui-angular`.
