### ISSUE TITLE
Ionic Auth not picked up by authstate observable or Hub

### ISSUE THREAD

**Issue by oliverandersencox** [aws-amplify/amplify-js#5002]
Another bug for the Ionic side of things.

After months of trying to get help with authenticating by socials with Angular/Ionic, I figured out how to do it by manually constructing the cognito authorise endpoint and running it in the capacitor in app browser. 

On redirect back to the app, amplify does not pick it up.

Ive tried reloading the route with the state and code from the auth response, and many other approaches.

The only one that triggers the amplify auth and therefore hub is to run:

`document.location.href = `${reloadURL}?code=${queryParams.code}&state=${queryParams.state}`;`

This looks rubbish on the device as it flickers the app reload.

Is there no other way to pass the auth responses code and state to amplify for it to recognise the auth?

**Comment by ashika01** [comment]
Hi, we have now support for ionic with our new UI components - https://docs.amplify.aws/ui/auth/authenticator/q/framework/ionic. Maybe this could help ease social federation for you?
