### ISSUE TITLE
Sample app not working

### ISSUE THREAD

**Issue by amuresia** [aws-amplify/amplify-js#5006]
After following the instructions to setup the sample app as documented in https://github.com/aws-samples/aws-amplify-graphql
when I run `npm run start` the browser opens with the following message
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/16068752/75580824-b8b21a80-5a68-11ea-8f3b-9421ad1a2d94.png">

Dismissing the warning shows a blank page.

**Comment by ashika01** [comment]
@amuresia Apologies on getting back on this late. Where are you with this? Have you found your solution?

**Comment by amuresia** [comment]
Hi, I don't think I did, I am no longer using amplify-js.
