### ISSUE TITLE
Datastore - How to send custom mutation?

### ISSUE THREAD

**Issue by mdebo** [aws-amplify/amplify-js#5008]
** Which Category is your question related to? **
Datastore

Hi, I don't find in the documentation any information about the right way to send a custom mutation to the datastore
In my schema, I have a custom mutation that calls a aws lambda as resolver. How to call it using the datastore, so that even if i'm offline this one is send to the queue for later processing?

**Comment by undefobj** [comment]
I'm not sure exactly what you mean by a custom mutation, but perhaps I can give more context. When you provision a DataStore backend and perform a `.save()` operation the mutations will automatically take place for you, including an enquing process on the client. The resolvers are automatically wired up to DynamoDB and do not use Lambda functions. Custom Lambda functions as the resolvers are not supported at this time, and could be fragile as any mistakes in the code could potentially impact the object versioning and synchronization process leading to data loss. However if you're doing something outside of DynamoDB, such as calling a 3rd party API, and you wish to run a Lambda function when a write to one of the tables created by an `@model` type is modified you can do that with a Trigger outlined here: https://aws-amplify.github.io/docs/cli-toolchain/quickstart#as-a-part-of-the-graphql-api-types-with-model-annotation

You can find a bit more of the process on how things work here: https://aws-amplify.github.io/docs/js/datastore#how-it-works
