### ISSUE TITLE
Does amplify-js use sqlite in react-native/expo?

### ISSUE THREAD

**Issue by alidlo** [aws-amplify/amplify-js#5013]
** Which Category is your question related to? **
Storage,
** What AWS Services are you utilizing? **
N/A
** Provide additional details e.g. code snippets **
Does amplify-js actually use sqlite or is it only the ios/android sdks? From documentation I gathered it did use sqlite, but from reading code I could only find references to async storage. Please let me know if there's something I'm missing.

Thanks

**Comment by Ashish-Nanda** [comment]
Hi @alidlo 

Amplify uses AsyncStorage for React Native and Expo apps. Could you link to the documentation that mentioned SQLite? Its possible it would be specifically for the ios/android SDKs.

Is your question with regards to Amplify DataStore in particular? 
If so, DataStore has the concept of storage adapters for the offline persistence layer, so while currently we have an adapter for AsyncStorage, we may add another adapter that uses SQLite (or any other local database) in the future and customers would be able to choose what to use.

Let me know if this answers your question and if you have follow ups. Thank you.


Does that answer your question?

**Comment by alidlo** [comment]
it was in amplify-js docs. but yes it does, thank you for clarifying will close
