### ISSUE TITLE
await Auth.currentAuthenticatedUser() right after await Auth.federatedSignIn() returns "not authenticated"

### ISSUE THREAD

**Issue by avlonder** [aws-amplify/amplify-js#5017]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
In react-native, how do I access the user data after a social login with Auth.federatedSignIn({provider: 'Google'})? If I use  Auth.currentAuthenticatedUser() without a setTimeout, the user is not yet authenticated...

**Comment by brianchan661** [comment]
I have the same problem, i can only get the user only after i refresh the page (or i should say, after some second delay).
It make my implementation difficult...

**Comment by brianchan661** [comment]
@avlonder 
I just find an old issue https://github.com/aws-amplify/amplify-js/issues/4621
and fixed it by listening to the sign in event
