### ISSUE TITLE
How to query old lines

### ISSUE THREAD

**Issue by djbuch** [aws-amplify/amplify-js#5018]
** Which Category is your question related to? **
Storage
** What AWS Services are you utilizing? **
DataStore, AWS AppSync
** Provide additional details e.g. code snippets **
I read that the DataStore only queries locally, but what if I have a remote DynamoDB sync with AppSync with ten thousands of line and only syncing the last 2k (as in the doc with `maxRecordsToSync`), how could I find a very old one ?

Thanks for your help.

**Comment by Ashish-Nanda** [comment]
Hi @djbuch 
We are currently tracking this as a feature request #4957 

You can find more details in this [comment](https://github.com/aws-amplify/amplify-js/issues/4957#issuecomment-589760076)

Closing as this is a duplicate
