### ISSUE TITLE
Default value for schema type

### ISSUE THREAD

**Issue by blairtaylor** [aws-amplify/amplify-js#5019]
Is there a way to specify a default value for graphQL schema types in Amplify?

ex.
myFlag: Boolean = true

This does not compile using amplify api gql-compile

We have a flag which should default to true and would like to initialize it this way when a type is created.

**Comment by blairtaylor** [comment]
Would appreciate if someone from the Amplify team could comment. Is the answer no?

**Comment by secretshardul** [comment]
Any updates here?

**Comment by cdac901** [comment]
+1

**Comment by quorth0n** [comment]
+1

**Comment by egyangel** [comment]
+1

**Comment by e-e** [comment]
🦗

**Comment by egyangel** [comment]
+1

**Comment by lucasmrdt** [comment]
Hey, I had the same problem as yours. I found this package [graphql-default-value-transformer](https://github.com/trek10inc/graphql-default-value-transformer#readme) which allows us to add a default value.

I hope this will help you.

**Comment by ivankokus** [comment]
Having a @default directive for fields is quite an important feature.  I hope you reconsider and add it in asap.  Thank you.

**Comment by anaibol** [comment]
+1

**Comment by I-himawari** [comment]
+1

**Comment by anaibol** [comment]
+1

**Comment by teezeit** [comment]
+1

**Comment by marcos8896** [comment]
+1

**Comment by yaquawa** [comment]
any update on this???

**Comment by vitalbone** [comment]
@ammarkarachi Is there any plans to add a `@default` type directive or something similar?
