### ISSUE TITLE
Can Amplify keep the existing Identity when signing up a new user to the user pool?

### ISSUE THREAD

**Issue by andsee** [aws-amplify/amplify-js#5022]
** Which Category is your question related to? **
Auth.
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **

I have an app that initially uses a guest identity from an identity pool, this is to ensure that users can use the app without the barrier of registering.

Once the user decides to register I use Amplify.Auth.SignUp followed by SingIn.

However this creates a new identity and links it to the user, I believe it's probably due to the call to Credentials.clear() in Auth.authCallbacks() which clears the current identity.

I originally implemented this app in Unity3D with a similar flow and only called the equivalent of Credentials.clear() if the user was specifically creating a new account or I was signing into a different account.

Is there a work around which would allow me to link the newly created user to the original identity? Of note I wish to avoid merging of identities which I believe would occur when the user is assigned more than one identity, as the docs (https://docs.amazonaws.cn/en_us/cognito/latest/developerguide/authentication-flow.html 'Merging Identities') mention that the resulting identity may change and it is essential that the identity ID remains as the original.

**Comment by jordanranz** [comment]
Hi @andsee, this is currently not supported inside of Amplify and needs some work done in the Cognito service to properly resolve the link you are trying to achieve. I'll mark this as a feature request for now and we can check back on this when we have more information about retrieving the linked identity id.

**Comment by reesscot** [comment]
This is now the default behavior and was fixed in version 4.1.2 (see PR #8466)
