### ISSUE TITLE
Change default opener on React Native to use an in app browser 

### ISSUE THREAD

**Issue by coreyjv** [aws-amplify/amplify-js#5027]
**Is your feature request related to a problem? Please describe.**
Yes, Apple rejected our iOS application because the default sign in behavior when using the hosted UI opened a browser outside of the app.

**Describe the solution you'd like**

The default behavior should be to open the URL in an in app browser.

**Describe alternatives you've considered**

We've overridden the `urlOpener` property on `Auth.auth.options` like so:

```
Amplify.configure({ 
    Auth: { 
        oauth: { 
            options: { 
                urlOpener: async (url, redirectSignIn) => {
                    await InAppBrowser.isAvailable()
          
                    const response = await InAppBrowser.openAuth(url, redirectSignIn, {
                      dismissButtonStyle: 'cancel',
                      showTitle: false,
                      enableUrlBarHiding: true,
                      enableDefaultShare: false
                    })
          
                    if (response.type === 'cancel') {
                      this.signInDeferred.reject(new UserCancelledAuthenticationError())
                    } else if (response.type === 'success' && response.url) {
                      Linking.openURL(response.url)
                    }
                  }
            } 
        }
    }
})
```

**Comment by AndrewJack** [comment]
One of our apps got rejected with the same message. Strangely the others were approved 🤷‍♂️
My appeal was also rejected.

I'll attempt the workaround you've suggested.

Rejection message:
```
Guideline 4.0 - Design


We noticed that the user is taken to Safari to sign in or register for an account, which provides a poor user experience.

Specifically, the Sign in with Apple login navigated to Safari.

Next Steps

To resolve this issue, please revise your app to enable users to sign in or register for an account in the app.

We recommend implementing the Safari View Controller API to display web content within your app. The Safari View Controller allows the display of a URL and inspection of the certificate from an embedded browser in an app so that customers can verify the webpage URL and SSL certificate to confirm they are entering their sign in credentials into a legitimate page.
```

**Comment by sysless** [comment]
Just got rejected too, I will try the in-app browser.

@AndrewJack any luck?

**Comment by AndrewJack** [comment]
@sysless Yes they accepted the app when using the in app browser. I've implemented something similar to what's written above.

I used this library to handle the in app browser - https://github.com/proyecto26/react-native-inappbrowser

**Comment by dev-elevate-usa** [comment]
It is important to note that the in the code snippet provided above, the Amplify.configure function is being called inside of the component. This allows for the dynamic handling of the values returned by the custom url handler which will allow for the developer to create useful UI in all cases of a url being opened for authentication: success, cancelled, and dismissed.

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.

**Comment by itsramiel** [comment]
@cwomack There is nothing in the release announcement that refers to this. What exactly was fixed?

**Comment by timorss** [comment]
Where is the fix of this issue?
How can we use other browser like the in-app browser?
