### ISSUE TITLE
Aws cognito linkedin

### ISSUE THREAD

**Issue by ronmara** [aws-amplify/amplify-js#5028]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
I'm trying to add LinkedIn login to my react app that using Amazon Cognito, I did everything like explained [here](https://aws.amazon.com/premiumsupport/knowledge-center/cognito-linkedin-auth0-social-idp/) and yes it works but I'm not using Amazon Cognito hosted UI and I don't want my user to get redirected to Auth0 site to login with LinkedIn...

Is there any way to implement LinkedIn Cognito login\signup without getting redirected to Cognito\Auth0?

Or maybe there is already a better way to implement this?

**Comment by sammartinez** [comment]
@ronmara Are you solely using Amazon Cognito or are you using Amplify within your React Application? If you are solely using Amazon Cognito please open up an issue on their [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=173).

**Comment by ronmara** [comment]
Opend an issue on AWS formus
https://forums.aws.amazon.com/thread.jspa?threadID=318076
