### ISSUE TITLE
Is it possible to invoke SES inside a pipeline function resolver?

### ISSUE THREAD

**Issue by mdegrees** [aws-amplify/amplify-js#5031]
** Which Category is your question related to? **
API
** What AWS Services are you utilizing? **
Cognito, AWS AppSync
** Provide additional details**
I’m building an app where people follow tags. They get notified by email when a post tagged with a tag they follow is created. In createPost mutation I used to send SES emails to tag subscribers after adding the post to db. If I rewrite my resolver logic in VTL using pipeline function resolvers, is it possible to invoke SES?

**Comment by ashika01** [comment]
You could rewrite the resolver logic, however your pipeline resolvers would need two function - one for create operation in dynamoDB and another one to invoke SES using https resolver.

Reference links:
https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-pipeline-resolvers.html
https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-http-resolvers.html

Does this answer your question? Let us know if you need more clarification.
