### ISSUE TITLE
Enhance responsive form in small screen

### ISSUE THREAD

**Issue by nbedevi** [aws-amplify/amplify-js#5033]
_This issue is a Request For Comments (RFC). It is intended to elicit community feedback regarding a proposed change to the library. Please feel free to post comments or questions here._

## Summary
I'm using amplify UI components in an ionic project, and I notice the UI not working in Mobile as expected, because of the `min-width` property in this line https://github.com/aws-amplify/amplify-js/blob/6e3805b600a5c8dd4eb1c09f000a660504003e8c/packages/amplify-ui-components/src/components/amplify-section/amplify-section.scss#L14

**Comment by ashika01** [comment]
@nbedevi we will mark this as feature request and will add the support for this with the upcoming UI project. You can read more about this https://github.com/aws-amplify/amplify-js/issues/3279 and let us know your support for the project.

**Comment by jordanranz** [comment]
This should be fixed in the latest release. Please open a new issue if you have any related questions or concerns.
