### ISSUE TITLE
OAuth - Error handling auth response. {}

### ISSUE THREAD

**Issue by chinnawatsut** [aws-amplify/amplify-js#5036]
I'm using amplify with React-native, when I use custom OAuth and click confirm permission it's work fine!
If I press "denied or cancel"  on Custom OAuth permission site, It should getting callback normally with event sign-in failure but back and crash the app.

ExceptionsManager.js:94 [ERROR] 44:39.434 OAuth - Error handling auth response. Error: Permissions+error%3B+error%3Daccess_denied%3B+error_code%3D200%3B+error_reason%3Duser_denied
    at OAuth.<anonymous> (OAuth.js:216)
    at step (OAuth.js:56)
    at Object.next (OAuth.js:37)
    at OAuth.js:31
    at tryCallTwo (core.js:45)
    at doResolve (core.js:200)
    at new Promise (core.js:66)
    at __awaiter (OAuth.js:27)
    at OAuth.handleAuthResponse (OAuth.js:192)
    at AuthClass.<anonymous> (Auth.js:1693)

![image](https://user-images.githubusercontent.com/16138030/75837512-a5e86e80-5df7-11ea-9115-0f0c8a10e5ef.png)

**To Reproduce**
1. Sign-in with OAuth likes FB
2. When the granting screen appears, press cancel or denied 
3. See Error

**Dependencies**
 "aws-amplify": "^2.2.2",
 "aws-amplify-react-native": "^3.2.2",

const signInOptions: FederatedSignInOptions = { provider: CognitoHostedUIIdentityProvider.Facebook };
Auth.federatedSignIn(signInOptions);

**Configuration**

Auth: {
    userPoolId: Config.AMPLIFY_USER_POOL_ID,
    region: Config.AMPLIFY_REGION,
    userPoolWebClientId: Config.AMPLIFY_USER_POOL_WEB_CLIENT_ID,
    storage: MemoryStorageNew,
    oauth:  {
      domain: Config.COGNITO_DOMAIN,
      scope: ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
      redirectSignIn: Config.COGNITO_SIGN_IN_URL,
      redirectSignOut: Config.COGNITO_SIGN_OUT_URL,
      responseType: 'code',
    }
  },

**Comment by kevinlin505** [comment]
I am getting the exact same issue, any ideas on how to handle this?
<img width="446" alt="Screen Shot 2020-03-05 at 11 04 52 AM" src="https://user-images.githubusercontent.com/5324658/76000819-3f844e80-5ed2-11ea-859d-e026fcba3457.png">

**Comment by kevinlin505** [comment]
@chinnawatsut any luck on this one?

**Comment by chinnawatsut** [comment]
@kevinlin505 not yet.

**Comment by nihp** [comment]
I am using aws-amplify-react-native. Here I imported all screens from the package itself. 

Any option to customize the error message using this package?

i```
mport {
  Authenticator,
  AmplifyTheme,
  Greetings,
  SignIn,
  ConfirmSignIn,
  RequireNewPassword,
  SignUp,
  ConfirmSignUp,
  VerifyContact,
  ForgotPassword,
  AuthPiece,
} from "aws-amplify-react-native";
```

**Comment by Swaroop-Bhupathiraju** [comment]
Same here, please let me know if anyone was able to resolve this

**Comment by nihp** [comment]
Use errorMessage={map}

Refer here https://aws-amplify.github.io/docs/js/authentication#customize-error-messages

**Comment by Swaroop-Bhupathiraju** [comment]
@chinnawatsut  @kevinlin505 any workarounds?

@nihp I don't think customizing error messages is the problem here

**Comment by rahulje9** [comment]
any update on this?

**Comment by amhinson** [comment]
@chinnawatsut Is the app crashing, or is it just show the red error screen? Based on my testing, I do see the red screen, but that is just because the code is calling `console.error`, which will only show in dev mode and doesn't actually crash the app.

Also, if you want to do a particular action if the request fails, you can listen to the `Hub` events and take the appropriate action ([see docs for example](https://docs.amplify.aws/lib/auth/social/q/platform/js#setup-frontend)). I see a `customState_failure` event come through after clicking cancel and going back to my app.

Is this what you're looking for?

**Comment by ehtulhaq** [comment]
Getting same error. I get this when I go to facebook login but cancel it instead of continuing to login using facebook.  Did anybody found a solution?

**Comment by shide1989** [comment]
Same error here on Amplify JS

**Comment by charleslouis** [comment]
Same error here with Cognito on react.
`28:51.650 OAuth - Error handling auth response. Error: invalid_scope`

I did not have it with my previous Cognito config. 
Front end hasn't changed same but I add to reinstall my backend stack a week ago (in case this info helps).

**Comment by ch4r1y** [comment]
Same error here

**Comment by shide1989** [comment]
@ch4r1y make sure you go through every configuration step on your Cognito Pool, specially the App Client settings. 
I know Cognito can ben very tricky.

On the client side (it's not very explicit) you might want to check the oauth scopes

**Comment by jgiunta1** [comment]
I had this issue because I tried to add "birthday" to the "scope" in the "oauth" section of my aws-exports.js file. I also manually added "user_birthday" to my cognito user pool for Facebook. Removing these solved the issue. I realized I need a separate permission for birthday as facebook recently updated their API.
