### ISSUE TITLE
Disable Create Account and reset password Send Code buttons while loading

### ISSUE THREAD

**Issue by craig-o-curtis** [aws-amplify/amplify-js#5038]
**Is your feature request related to a problem? Please describe.**
Create Account and reset password Send Code buttons not disabled when loading.
This is both an accessibility concern and usability concern.

**Describe the solution you'd like**
Related fix is [#2217](https://github.com/aws-amplify/amplify-js/issues/2217)
This would allow for using CSS to change the styles and text

**Describe alternatives you've considered**
Recreating a component wrapper is too time consuming when a simple CSS solution targeting DOM changes (like issue #2217) allows developers to get to completion.

**Additional context**
Simple CSS solution to target the disabled flag allows for color, animation, and text changes.

`

        // Override AWS-Amplify button
        button[data-test='sign-in-sign-in-button'],
        button[data-test='sign-up-create-account-button'] /** add functionality for this **/,
        button[data-test='forgot-password-send-code-button'] /** add functionality for this **/ {
            width: 12rem;
            height: 3rem;
            &:disabled {
                font-size: 0px !important;
                color: white !important;
                background: linear-gradient(90deg, dodgerblue, white, white, dodgerblue);
                background-size: 400% 400%;
                animation: gradient 2s ease 5;
                animation-fill-mode: forwards;
    
                &::after {
                    font-size: 12px !important;
                    color: navy !important;
                    text-transform: normal !important;
                    content: 'Loading...'
                }
            }
        }
        @keyframes gradient {
	    0% {
	    	background-position: 125% 50%;
	    }
	    100% {
	    	background-position: 0% 50%;
	    }
        }
`

**Comment by ashika01** [comment]
@craig-o-curtis I think the new ui components have a loading indicator which disables the button while the request is being processed. Are you expecting something different?
