### ISSUE TITLE
Which @connection definition to use for DataStore? @key based or alternative?

### ISSUE THREAD

**Issue by AndrewPrifer** [aws-amplify/amplify-js#5039]
** Which Category is your question related to? **
DataStore
** What AWS Services are you utilizing? **
AWS AppSync

The `@connection` [GraphQL Transform docs](https://aws-amplify.github.io/docs/cli-toolchain/graphql#connection) recommend "defining index structures using `@key` and connection resolvers using `@connection`" over the older [alternative definition](https://aws-amplify.github.io/docs/cli-toolchain/graphql#alternative-definition).

However the DataStore [docs](https://aws-amplify.github.io/docs/js/datastore#relational-models) only make mention of this apparently obsolete alternative `@connection` directive.

Which is preferred for using DataStore? Are the docs simply outdated, or is the alternative `@connection` directive indeed the preferred way here?

**Comment by Ashish-Nanda** [comment]
Hi @AndrewPrifer 

The recommended way mentioned in the [GraphQL Transform docs](https://aws-amplify.github.io/docs/cli-toolchain/graphql#connection) is indeed the way we recommend you define relations between your models. 

I will work on updating the DataStore docs.

**Comment by AndrewPrifer** [comment]
Thanks @Ashish-Nanda

**Comment by mdoesburg** [comment]
@Ashish-Nanda Following the recommended way as described in the docs is giving me the following error:

`DataStore does not support connection directive with keyName`

**CLI version:** @aws-amplify/cli@4.18.0 

With the following schema:

```graphql
type Post 
  @model
  @auth(rules: [
    { allow: owner, identityClaim: "email" },
    { allow: groups, groups: ["Admin"] }
  ])
{
  id: ID!
  name: String
  comments: [Comment] @connection(keyName: "byPost", fields: ["id"])
}

type Comment 
  @model
  @auth(rules: [
    { allow: owner, identityClaim: "email" },
    { allow: groups, groups: ["Admin"] }
  ])
  @key(name: "byPost", fields: ["postId"])
{
  id: ID!
  name: String
  postId: ID!
}

```

Should I use the way as described in the DataStore section, and use "name" instead?

**Comment by faris-sa** [comment]
after upgrading CLI to 
CLI version: @aws-amplify/cli@4.18.1
I received this error:
**DataStore does not support connection directive with keyName**
