### ISSUE TITLE
Auth.currentAuthenticatedUser returning cached custom attributes instead of current from user store

### ISSUE THREAD

**Issue by nelsynelz** [aws-amplify/amplify-js#5043]
**Describe the bug**
When registering a user let's say I set a custom attribute in cognito to A. Later in the registration process I then update it to B. When I call Auth.currentAuthenticatedUser it will still return A. The user needs to logout and log back in to get the latest value.

**To Reproduce**
1. Create a user with a custom attribute and set it to X
2. Update it to Y
3. Call Auth.currentAuthenticatedUser
4. Observe that you still see X even though in the user store it's updated to Y

**Expected behavior**
I expect the latest/most current attribute value to be returned.

<details>
  <summary><strong>Environment</strong></summary>

```
  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (4) x64 Intel(R) Core(TM) i5-6402P CPU @ 2.80GHz
    Memory: 1.71 GB / 15.60 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 12.15.0 - /usr/bin/node
    npm: 6.13.4 - /usr/bin/npm
  Browsers:
    Chrome: 80.0.3987.106
    Firefox: 73.0.1
  npmGlobalPackages:
    npm: 6.13.4

```

</details>

**Comment by nelsynelz** [comment]
Any updates on this?

**Comment by ashika01** [comment]
@nelsynelz: Thank you for bringing this up. Do you have sample code somewhere which we could take a look?

**Comment by nelsynelz** [comment]
It's a private Repo. I can reference important code pieces though. 

Upon signup I'm setting two custom attributes, the second is the important one here: 

``` javascript
signUp() {
  this.signUpPosting = true
  const { username, password } = this.signUpForm;

  Auth.signUp({ username, password, attributes: { "custom:UserType": "Realtor", "custom:Rltr_LicenseCnfrm_Cd": "0"}})
    .then(response => (this.signUpPosting = false, (this.stepNum = 1)))
    .catch(error => (console.log(error), this.signUpPosting = false));
}
```
Upon confirming that the license is correct, I set that custom attribute to "1". I do this on my backend:

``` python
response = client.admin_update_user_attributes(
    UserPoolId=cognitoUserPoolId,
    Username=userId,
    UserAttributes=[
        {
            'Name': 'custom:Rltr_LicenseCnfrm_Cd',
            'Value': "1"
        },
    ]
)
```

Now back on my frontend if I am to call the Auth.currentAuthenticatedUser() function, it still returns a 0 even though in Cognito I see that it is now a 1.

Only way I've found to get the fresh value is by logging out then in again.

I can work around this by making an additional API call myself, but it would be nice if I could get it through the amplify api.

**Comment by nelsynelz** [comment]
Also, it just occurred to me that this value is probably encoded in the JwtToken?

If that's the case then can I force a token refresh to get the updated value? If so which Auth method would I call for that?

**Comment by ashika01** [comment]
Might be related to #4396

**Comment by iartemiev** [comment]
Should be fixed now in the latest **unstable** release. Will be released to stable in the near future as well. Closing this issue.

**Comment by pmirandaarias** [comment]
currentAuthenticatedUser still caches the authenticated user info, even with `{ bypassCache: true }` (aws-amplify 3.3.12)

**Comment by jcowley** [comment]
For anyone else who comes across this issue, `{ bypassCache: true }` won't do it. The way to refresh custom attributes is in [this comment](https://github.com/aws-amplify/amplify-js/issues/4396#issuecomment-553954564) on #4396.
