### ISSUE TITLE
Amplify Storage: Get with Range?

### ISSUE THREAD

**Issue by enigmablue** [aws-amplify/amplify-js#5044]
I'm looking for a way to get files (videos) from my S3 with a range request. But in the amplify storage docs i dont see any option for range.
https://aws-amplify.github.io/docs/js/storage

Is this supported? Thank you! 

(something like the range in the s3 API Amazon Simple Storage Service [docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html#API_GetObject_RequestSyntax))

** Which Category is your question related to? **
Storage
** What AWS Services are you utilizing? **
S3
** Provide additional details e.g. code snippets **

**Comment by Ashish-Nanda** [comment]
Hi @enigmablue 
We currently do not support range requests. Can you tell us a bit more about your use-case so we can consider whether we want to add this to Amplify?

**Comment by enigmablue** [comment]
Thanks for getting back!

Actually i was trying to get the first part of a video so i could pre-show
the first part of video to users in my react native mobile app.
Right now they have to load the entire video before they could watch it.
Which is not a good user experience.

However i found out that my react-native-fs has the header option and i
could do the range. However it seems i'm unable to play "partial"
downloaded videos.
So i'm trying to figure something out. I may have to split up the first 10
seconds of a video during the put, separate them by parts and them somehow
join them together.

**Comment by charleslouis** [comment]
@enigmablue 
Have you considered VOD with `amplify video` ?
https://codingcat.dev/lessons/aws-amplify-video/

**Comment by kierancrowntrt** [comment]
Are there currently any plans to implement this. I'm currently using Storage to retrieve MP3's but this method takes too long as it has to load the whole MP3. I'd be interested if this feature was added so I don't have to write a custom class to do this for me.

**Comment by tannerabread** [comment]
Closing this as a duplicate/piece of a larger feature-request that has more traction. #6830
