### ISSUE TITLE
Federated sign in with Facebook is not working in React Native (Expo) app

### ISSUE THREAD

**Issue by jakobpack** [aws-amplify/amplify-js#5046]
** Which Category is your question related to? **

Federated Authentication

** What AWS Services are you utilizing? **

Cognito

** Provide additional details e.g. code snippets **

I am trying to use the federated sign in with Facebook. I've set up everything correctly, but I can't get it to work.
I'm receiving this error when calling `Auth.federatedSignIn()`: 

> Invalid login token. Not a valid OpenId Connect identity token.

The token is a valid access token (I can call Facebook's Graph API successfully).

Maybe I need to pass a different token?

Here is my code:
```javascript
import React from 'react';
import { View, Button } from 'react-native';
import awsconfig from './aws-exports';
import Auth from '@aws-amplify/auth';
import * as Facebook from 'expo-facebook';
import * as WebBrowser from 'expo-web-browser';

const urlOpener = async (url, redirectUrl) => {
    // On Expo, use WebBrowser.openAuthSessionAsync to open the Hosted UI pages.
    const { type, url: newUrl } = await WebBrowser.openAuthSessionAsync(url, redirectUrl);

    if (type === 'success') {
	  await WebBrowser.dismissBrowser();

	  if (Platform.OS === 'ios') {
	     return Linking.openURL(newUrl);
	  }
    }
};

const oauth = {
	domain : 'MY_DOMAIN.auth.eu-central-1.amazoncognito.com', 
	scope : ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin'], 
	redirectSignIn : 'exp://127.0.0.1:19000',
	redirectSignOut : 'exp://127.0.0.1:19000',
	responseType: 'code',
	urlOpener: urlOpener
};

Auth.configure({ ...awsconfig, oauth });

export default function App() {

        useEffect(() => {
		initAsync();
	}, []);

	const initAsync = async () => {
		await Facebook.initializeAsync('YOUR_APP_ID');
	}

	async function signInWithFacebook() {
          const { type, token, expires } = await Facebook.logInWithReadPermissionsAsync({
			permissions: ['public_profile', 'email'],
		});
		console.log(type, token);
         if (type === 'success') {
	     // sign in with federated identity 
             // error --> token not accepted
            Auth.federatedSignIn('Facebook', { token, expires_at: expires })
              .then(credentials => {
                 console.log('get aws credentials', credentials);
              }).catch(e => {
                console.log(e);
              });
          }
	}

  return (
    <View style={styles.container}>
	<View>
	  <Button onPress={signInWithFacebook} title="Open Facebook" />
	</View>
    </View>
  );
}
```

**Comment by jakobpack** [comment]
@ericclemmons Thanks for your response.

1. I configured auth via the Amplify CLI. Chose following options:
    1. Select **Default configuration with Social Provider (Federation)**
    2. Select **Email and Phone Number**
    3. Choose **no advanced settings**
    4. Configure **Google, Facebook and Amazon Sign In**
<details open>
<summary><b>auth/parameters.json</b></summary>
<pre>
{
    "identityPoolName": "MY_ID_POOL",
    "allowUnauthenticatedIdentities": false,
    "resourceNameTruncated": "MY_RESOURCE_NAME",
    "userPoolName": "MY_USER_POOL_NAME",
    "autoVerifiedAttributes": [
        "email"
    ],
    "mfaConfiguration": "OFF",
    "mfaTypes": [
        "SMS Text Message"
    ],
    "smsAuthenticationMessage": "Your authentication code is {####}",
    "smsVerificationMessage": "Your verification code is {####}",
    "emailVerificationSubject": "Your verification code",
    "emailVerificationMessage": "Your verification code is {####}",
    "defaultPasswordPolicy": false,
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": [],
    "requiredAttributes": [
        "email"
    ],
    "userpoolClientGenerateSecret": true,
    "userpoolClientRefreshTokenValidity": 30,
    "userpoolClientWriteAttributes": [
        "email"
    ],
    "userpoolClientReadAttributes": [
        "email"
    ],
    "userpoolClientLambdaRole": "MY_LAMBDA_ROLE",
    "userpoolClientSetAttributes": false,
    "resourceName": "MY_RESOURCE_NAME",
    "authSelections": "identityPoolAndUserPool",
    "authRoleArn": {
        "Fn::GetAtt": [
            "AuthRole",
            "Arn"
        ]
    },
    "unauthRoleArn": {
        "Fn::GetAtt": [
            "UnauthRole",
            "Arn"
        ]
    },
    "useDefault": "defaultSocial",
    "hostedUI": true,
    "usernameAttributes": [
        "email, phone_number"
    ],
    "hostedUIDomainName": "taxiradar",
    "authProvidersUserPool": [
        "Facebook",
        "Google",
        "LoginWithAmazon"
    ],
    "hostedUIProviderMeta": "[{\"ProviderName\":\"Facebook\",\"authorize_scopes\":\"email,public_profile\",\"AttributeMapping\":{\"email\":\"email\",\"username\":\"id\"}},{\"ProviderName\":\"Google\",\"authorize_scopes\":\"openid email profile\",\"AttributeMapping\":{\"email\":\"email\",\"username\":\"sub\"}},{\"ProviderName\":\"LoginWithAmazon\",\"authorize_scopes\":\"profile profile:user_id\",\"AttributeMapping\":{\"email\":\"email\",\"username\":\"user_id\"}}]",
    "userPoolGroupList": [],
    "dependsOn": [],
    "oAuthMetadata": "{\"AllowedOAuthFlows\":[\"code\"],\"AllowedOAuthScopes\":[\"phone\",\"email\",\"openid\",\"profile\",\"aws.cognito.signin.user.admin\"],\"CallbackURLs\":[\"exp://192.168.1.138:19000/\",\"exp://192.168.1.138:19000/\"],\"LogoutURLs\":[\"exp://192.168.1.138:19000/\",\"exp://192.168.1.138:19000/\"]}"
}
</pre>
</details>

2. I want to use Facebook only for sign in

**Comment by ericclemmons** [comment]
@jakobpack Thanks for the detailed information! (And also, nice job using `<details>`! 👏)  

I have a test app doing the same (`amplify add auth` with Federation) that works based on the docs here:
> https://aws-amplify.github.io/docs/js/authentication#oauth-and-hosted-ui

Since your config indicates user pools, Cognito is handling the OAuth token management, so you shouldn't need to handle tokens yourself if you only need social providers for handling authentication.

With `Amplify.configure(awsExports)`, try this:

1. On click, call `Auth.federatedSignIn()`.  This should open/redirect to the Cognito Hosted UI.  Test the Facebook signin there.

1. Once that's validated, you can call `Auth.federatedSign({ provider: 'Facebook' })`, which will skip the Cognited Hosted UI and go straight to the Facebook signin page.  Confirm the flow continues to work.

Here's wha tmy code looks like:
```js
<Form.Button
	content="Sign in with Facebook"
	fluid
	icon="facebook"
	inverted
	onClick={() => Auth.federatedSignIn({ provider: 'Facebook' })}
	size="large"
	style={{ background: '#4267b2' }}
/>
```

Let me know how this flow works for you. 🤞

**Comment by jakobpack** [comment]
@ericclemmons Thanks!

I tried to open Cognito Hosted UI via `Auth.federatedSignIn()`. It opens the browser but displays following error message:

> An error was encountered with the requested page.

There is also following error type in the URL: `error=redirect_mismatch`.

The same goes for `Auth.federatedSignIn({ provider: 'Facebook' })`.

**Comment by ericclemmons** [comment]
Ah!  This would be the first thing we'd want to troubleshoot.

When you run `amplify status` in your console, the last line should list URLs like so:

```console
GraphQL endpoint: https://•••.appsync-api.us-east-1.amazonaws.com/graphql
Hosting endpoint: https://•••.cloudfront.net
Hosted UI Endpoint: https://•••.auth.us-east-1.amazoncognito.com/
Test Your Hosted UI Endpoint: https://•••.auth.us-east-1.amazoncognito.com/login?response_type=code&client_id=•••&redirect_uri=http://localhost:3000/
```

Click the "Test Your Hosted UI Endpoint" and try out the flow there.  

Mine, for example, redirects back to my app at `http://localhost:3000`.

Let me know how far you can get.  I suspect that you need to add the correct Cognito endpoints to your social providers first:
> https://aws-amplify.github.io/docs/js/authentication#finish-social-setup

**Comment by jakobpack** [comment]
Thanks, the URL received by calling `amplify status` is working correctly!
Calling `Auth.federatedSignIn` still resolved in the error.
But I got it fixed now! 
I had duplicate redirect sign-in/out urls configured.
I'm not sure, but I think removing the duplicates fixed it.

**Comment by jakobpack** [comment]
It's still not actually working properly. I can now open a social provider and give access, but when redirected to the App via 'Open in Expo', I get different errors, depending on the social provider..

For Facebook I recieve:

> OAuth - Error handling auth response., [Error: invalid_request]

But the user is getting signed in, I can see that when I refresh the App.

For Google I recieve:

> OAuth - Error handling auth response., [Error: Invalid state in OAuth flow]

User doesn't get signed in.

**Comment by ericclemmons** [comment]
Thanks for the updates @jakobpack!  If I have this correct, you're able to validate the OAuth flow via the `amplify status` URLs, but the Expo integration is the last broken piece.

When you receive those Facebook/Google errors, is that before you complete signing in, before you get redirected, or after the redirect happens?

Besides the `initAsync` and `signInWithFacebook` from your initial sample, your code is spot on with https://aws-amplify.github.io/docs/js/authentication#a-note-for-expo-users.

Is there an alternative `redirectSignIn` you've tried?  Otherwise, I'll need to spend more time trying to reproduce your situation with my local sample.

Let me know! 🤞

**Comment by ericclemmons** [comment]
@jakobpack There are several issues all open around Expo, one of which instructs running `amplify update auth` to persist the `exp://` redirect URLs:
> https://github.com/aws-amplify/amplify-js/issues/4244#issuecomment-586845322

**Comment by jakobpack** [comment]
Thanks, using the solution described in [#4244 (comment)](https://github.com/aws-amplify/amplify-js/issues/4244#issuecomment-586845322) solved the issue!

**Comment by denispixi** [comment]
I'm facing a related issue :(
I have configured cognito with Facebook as identity provider, in web it works ok, but in React Native, when I call `Auth.federatedSignIn({ provider: 'Facebook' })` and back from Safari after successful login, I call `Auth.currentAuthenticatedUser().then(response => console.log({ response })).catch(err=>console.log({err})` and I get the error `{err: "not authenticated"}` 
I'm stuck with this problem. Can someone help me pls? :c
the url for redirect bak to my app is `myapp:///?code=ccdecc0e-e74f-4977-91a1-83fbe8624aa6&state=kgGOfS8sKRijeG1ejZiafX5koTJnhE83#_=_`

**Comment by ericclemmons** [comment]
@denispixi Do repeated calls to `Auth.currentAuthenticatedUser()` succeed?  There's a known race-condition that we're addressing:
> https://github.com/aws-amplify/amplify-js/issues/5133#issuecomment-620717488

In the meantime, you can listen to `Hub`'s `signIn` event for getting the `user`:
> https://aws-amplify.github.io/docs/js/authentication#oauth-and-hosted-ui

If you're experiencing a different problem, feel free to open up a new issue and let me know! 🙏

**Comment by pigslhub** [comment]
Hi jakobpack !
I am trying the same thing to access the hosted UI but i am unable to see the webview with facebook login page. Everytime i got " An error was encountered with the requested page". Please help me how can i solve that error ?
