### ISSUE TITLE
Unresolved dependency when installing `@aws-amplify/auth@^2.1.6`

### ISSUE THREAD

**Issue by jakobpack** [aws-amplify/amplify-js#5047]
**Describe the bug**

After installing `@aws-amplify/auth@^2.1.6` via `npm`, I receive following error in an **Expo** project:

> Unable to resolve "@react-native-community/netinfo" from "node_modules/@aws-amplify/auth/node_modules/@aws-amplify/core/lib/Util/Reachability.native.js"

This is resolved by installing `@react-native-community/netinfo`.

**Project dependencies:**

```json
    "@aws-amplify/api": "^2.1.3",
    "@aws-amplify/auth": "^2.1.6",
    "@aws-amplify/pubsub": "^2.1.3",
    "@mapbox/polyline": "^1.1.0",
    "expo": "^36.0.2",
    "expo-facebook": "~8.0.0",
    "expo-google-sign-in": "~8.0.0",
    "expo-location": "~8.0.0",
    "expo-permissions": "~8.0.0",
    "expo-web-browser": "~8.0.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-maps": "0.26.1",
    "react-native-web": "~0.11.7"
```

**Comment by sammartinez** [comment]
@jakobpack We do use the netInfo community addition from React Native as part of our [DataStore React Native](https://aws-amplify.github.io/docs/js/datastore#react-native-specific-steps) use case. This is something we recently added and called out in the above link. Im going to resolve this issue as we do call this out in our documentation that this is something that you need to install while using React Native within Amplify JS.
