### ISSUE TITLE
Disable autocomplete for username input

### ISSUE THREAD

**Issue by madmed88** [aws-amplify/amplify-js#5048]
**Is your feature request related to a problem? Please describe.**
Currently autocomplete is only disabled for password inputs, but it is also considered a security threat
for username inputs
**Describe the solution you'd like**
disable autocomplete for username input or provide option to disable it

**Comment by eddiekeller** [comment]
As mentioned in https://github.com/aws-amplify/amplify-js/pull/5772 , this is something we are looking to implement in the future. But, for now, you should be able to disable autocomplete via the `inputProps`.

```
<AmplifySignIn
          headerText="Sign in with User Pool Credentials"
          slot="sign-in"
          formFields={[
            {
              type: 'username',
              inputProps: {
                autocomplete: false,
              },
            },
          ]}
        />
```

**Comment by eddiekeller** [comment]
We are looking at including this in the future, but for now, using the `autocomplete` prop inside of `inputProps` on the component should allow you to disable the autocomplete functionality.

```
<AmplifySignIn
  headerText="Sign in with User Pool Credentials"
  slot="sign-in"
  formFields={[
    {
      type: 'username',
      inputProps: {
        autocomplete: 'off',
      },
    },
  ]}
/>
```
