### ISSUE TITLE
How can I customize the validation error messages 

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#5053]
How can I customize the validation error messages while login, SignUp, Sign In, Forgot password, Reset Password and etc..

Here i need to customize the error message to shown in UI of my iOS app.

Any option to do that?

Using the below all imports in my app
```

import {
  Authenticator,
  AmplifyTheme,
 //Greetings,
  SignIn,
  ConfirmSignIn,
  RequireNewPassword,
  SignUp,
  ConfirmSignUp,
  VerifyContact,
  ForgotPassword,
  AuthPiece,
} from "aws-amplify-react-native
```

**Comment by ashika01** [comment]
Hi @nihp, I realized you asked this question in another issue. I have answered the question here https://github.com/aws-amplify/amplify-js/issues/5072#issuecomment-598539666

Do you think you can extend the existing component and catch the error to create your custom error output?

**Comment by nihp** [comment]
Did you know about the sentry
