### ISSUE TITLE
How achieve Apple Touch Id in Amplify ? 

### ISSUE THREAD

**Issue by t-moedano** [aws-amplify/amplify-js#5055]
**Which Category is your question related to?**
OAuth

**What AWS Services are you utilizing?**
Cognito

**Provide additional details e.g. code snippets**
How can I use SignInWithApple OAuth and go for Apple Touch Id workflow using Cognito User Pool? Open web browser won't be accepted by Apple and we need to implement this verification through Touch/Face Id. How we achieve that?

**Comment by ahtokca** [comment]
Hi @t-moedano, did u find a way?
