### ISSUE TITLE
Sign In With Apple shows 'null' in App Name in Touch Id

### ISSUE THREAD

**Issue by t-moedano** [aws-amplify/amplify-js#5056]
**Describe the bug**
When you try to Sign In With Apple, it opens a pop up to use touch id. However, the App name appears as 'null'

**To Reproduce**

1. Enable Sign In With Apple
2. Do Login in device with Touch Id enabled
3. When pop up appears, the application name will be 'null'

**Expected behavior**
Should show the application name. When you try to use a device which does not have touch id enabled, it opens a browser to login with email/password and there appears the application name.

**Screenshots**
![bug-appleid](https://user-images.githubusercontent.com/19256308/76116248-6a50ce80-5fc8-11ea-930f-eba716a7d0f1.jpeg)

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone 8]
- OS: [e.g. iOS 13]

**Comment by ashika01** [comment]
@t-moedano Hi, I am closing this issue since this we are tracking all the issues related to sign in for apple in #4580 . The last few comments talks about this exact issue. Please feel free to add more information in there and track the updates on the mentioned issue.
