### ISSUE TITLE
Is it possible to programatically generate the GraphQL schemas when using Datastore?

### ISSUE THREAD

**Issue by mike-hogan** [aws-amplify/amplify-js#5060]
Category:  Datastore

I am building a system that is a lot like airtable. It allows folks define their own models using a UI. Then they can enter data using auto-generated forms from the models. So the only two types I have are Model and Row. An example, an instance of a model might be a Book, with fields title, isbn, number of pages and price. The model instance will have an id - lets say its 11. Rows entered against this id of 11 will implicitly be "Books", will have json data associated containing the relavant title, isbn, price etc.

So there is no modelgen step for me here.

I am hoping I can get down to a lower level use of Datastore so that I can provide it with programatically generated GraphSQL SDL, and have my own GraphQL resolver(s) that map to a nosql json document store.

I'm only a half day into researching how this might work, so please can you point me towards relevant docs/code/examples/resources that might steer me the right way?

Thx

PS Originally posted in amplify-cli, which might have been a bit wrong - https://github.com/aws-amplify/amplify-cli/issues/3605

**Comment by harrysolovay** [comment]
Amplify DataStore might not be the best fit for this use case (dynamic models). You could use a single DynamoDB table to store many "models", wherein each row could vary from one another in terms of field names and types. You could have users send a JSON document to a lambda, which would handle the interaction with that table... I'm not sure if GraphQL is the right tool for something like this (as a key tenet is strong typing). You could send along the JSON source text in a GraphQL request, but that seems excessive. I think your best bet is to [use the CLI to create a lambda function](https://docs.amplify.aws/cli/function), from which you can interact with the table.
