### ISSUE TITLE
Problems with callback url being on different domain than SPA

### ISSUE THREAD

**Issue by Groot90** [aws-amplify/amplify-js#5061]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
I'm trying to have a single Cognito User Pools auth sign in callback url ( redirectSignIn in Amplify's terms). However, the app I'm building needs to be able to run from multiple (many) domains.

I'm not sure why it doesn't seem to be possible to have Amplify.Auth.oAuth.redirectSignIn url hosted on a different domain than  the React application (SPA)? 

What if the React app needs to be run from multiple domains? I see that customState parameter can be used to identify the actual domain sending the login request, but I'm having issues when trying that approach. Any time I get a redirect back from the central callback url to the React App, React app fails with the following JS error:

EVENT AUTH HUB: index.js:115
Object { event: "customOAuthState", data: "http__colon____forward____forward__localhost__colon__3001", message: "State for user Google_111083168159815163414" }
index.js:116
[DEBUG] 25:10.750 AuthClass - Error in cognito hosted auth response DOMException: "The operation is insecure."

It seems to be generated by replaceState() in this file
https://github.com/aws-amplify/amplify-js/blob/cf8738ac5e7961a163ce158a7383bc27f693475f/packages/auth/src/Auth.ts

(line 1886),  function _handleAuthResponse

**Comment by Groot90** [comment]
To add some more context here:
I'm trying to implement "State" parameters redirection, described here, using Amplify + Cognito User Pools:
https://auth0.com/docs/users/guides/redirect-users-after-login#keep-reading

**Comment by Groot90** [comment]
The code change in PR #5062 seems to be working - callback url on another domain can be used this way. However, I'd like to hear your comments on this issue. I'm wondering why this is needed? Was this intended behavior or a bug? Thank you!

**Comment by AntonioAngelino** [comment]
We have exactly the same use case and issue described by @Groot90 !
We need to redirect the user to a route that is not `oauth.redirectSignIn`.

I'd suggest implementing the solution explained by @hotgazpacho here: https://github.com/aws-amplify/amplify-js/issues/3391 
> I would expect that the location would not be replaced on successful federated sign in, OR, allow consumers to configure (preferably at call time) the URL to redirect to after successful sign in, keeping it separate from the callback URL.
