### ISSUE TITLE
[Javascript] How do I set aws credentials to the API without using AWS Cognito?

### ISSUE THREAD

**Issue by adityats2020** [aws-amplify/amplify-js#5067]
**Which Category is your question related to?**
Auth
**What AWS Services are you utilizing?**
Direct call to API Gateway using REST API
**Provide additional details e.g. code snippets**
Using API to make REST calls to API Gateway.

How do I set AWS Credentials (access key, access key id, session token), without using AWS Cognito. 
Language used: Javascript

**Comment by ashika01** [comment]
@adityats2020 are you using Amplify for setting these up?

**Comment by adityats2020** [comment]
@ashika01 Yes, trying to use Amplify to talk to API Gateway, but without using Cognito.

**Comment by ashika01** [comment]
@adityats2020 do you have sample code or repo which can help to understand your use case better?

**Comment by ashika01** [comment]
@adityats2020 We dont currently have a way in which you can achieve the result you are looking for. However, if you could provide us a detailed information about your use case and the data flow you are looking into. It would be useful for us to have some internal discussion or to open up a feature request for this.

**Comment by adityats2020** [comment]
I want to use Amplify REST API to sign requests using the AWS Credentials (access key id, secret access key and session token) that I provide to Amplify, without requiring AWS Cognito settings on Amplify.
That's the use case.
