### ISSUE TITLE
Observable is not a constructor

### ISSUE THREAD

**Issue by DavidAlvarado23** [aws-amplify/amplify-js#5069]
I am using AppSync's subscriptions on React with Typescript and Parcel as bundler. When I try to make a subscription with Amplify I get the following error:
```
Uncaught TypeError: Observable is not a constructor in PubSub.ts:157
    at PubSub.subscribe (PubSub.ts:157)
    at APIClass._graphqlSubscribe (API.ts:469)
    at APIClass.graphql (API.ts:370)
```

I've tried installing the individual amplify packages such as @aws-amplify/api @aws-amplify/pubsub and configure them after amplify, but didn't work.

```
import awsconfig from "./aws-exports";
import API from @aws-amplify/api;
import PubSub from @aws-amplify/pubsub;

Amplify.configure(awsconfig);
API .configure(awsconfig);
PubSub .configure(awsconfig);
```

**Packages**
```
"aws-amplify": "^2.2.6",
"aws-amplify-react": "^3.1.6", 
"aws-sdk": "^2.627.0",
"react": "^16.13.0",
"react-dom": "^16.13.0"
```

**Sample code**
I do the Amplify configuration in the index.tsx and try to subscribe in another file inside the useEffect hook.

In index.tsx
```
import Amplify from "aws-amplify";
import awsconfig from "./aws-exports";

Amplify.configure(awsconfig);
```

In other file after Cognito Auth
```
import { API, graphqlOperation } from "aws-amplify";
import * as subscriptions from "../../graphql/subscriptions";

const Component= () => {
  useEffect(() => {
    const subscription = API.graphql(
      graphqlOperation(subscriptions.onUpdate)
    ).subscribe({
      next: (todoData: any) => console.log(todoData)
    });

    return () => {
      subscription.unsubscribe();
    };
  }, []);
```

**Comment by DavidAlvarado23** [comment]
**UPDATE:** 
Find out that every package in @aws-amplify/api and @aws-amplify/pubsub imported the library 'zen-observable' as:
`import * as Observable from 'zen-observable';`

When it should be imported like:
`import Observable from 'zen-observable';`

As their documentation explains [zen-observable](https://github.com/zenparsing/zen-observable) . Made this changes locally and worked, but not sure if this affects other functionalities.

**Comment by ashika01** [comment]
The reason we had to take this route , is because when the package is exported as CJS modules, and then consumed or imported as ES6 modules (i.e. using import style statement) then using default exports was causing issues.

**Comment by DavidAlvarado23** [comment]
I understand, but is there another way to make this work with Parcel? Since I think that is the problem. Can it be changed to use Observable.default or verify which is the correct class to instantiate?

**Comment by ashika01** [comment]
@DavidAlvarado23 Do you have a sample app or repo with the parcel setup that I could leverage to debug this?

**Comment by sammartinez** [comment]
@DavidAlvarado23 Please let us know on the sample application and we can circle back with you.
