### ISSUE TITLE
Datastore not syncing due to auth.

### ISSUE THREAD

**Issue by waltermvp** [aws-amplify/amplify-js#5074]
** Which Category is your question related to? **
Datastore / API
** What AWS Services are you utilizing? **
 Cognito, AWS AppSync, Dynamo.

The local datastore does not sync with the backend I get the following error:

`[WARN] 05:04.399 DataStore - Sync error subscription failed Connection failed: {"errors":[{"errorType":"UnauthorizedException","message":"Permission denied"}]}
`

I have am using IAM + cognito as authorization methods.

I also make sure to configure like so:
```
import awsconfig from "./aws-exports";
Amplify.configure(awsconfig);
```

How can I fix this auth issue? Thank you

**Comment by ashika01** [comment]
@waltermvp could you provide us with the schema you are using in Datastore? Also, if you can provide with sample code / repo we could look at?

**Comment by waltermvp** [comment]
Here is the schema

```
# enum PostStatus {
#   ACTIVE
#   INACTIVE
# }

# type Post @model {
#   id: ID!
#   title: String!
#   rating: Int!
#   status: PostStatus!
# }

type Event @model {
  # @searchable
  id: ID!
  name: String!
  notes: String
  tables: [Table] @connection(name: "EventTables")
  dinnerSelection: [ChosenEventMeal] @connection(name: "EventChosenMeal")
  type: EventType
  eventDate: AWSDateTime!
  shift: EventShift
}

enum EventShift {
  morning
  night
}

type User
  # @searchable
  @model {
  # @auth(
  #   rules: [{ allow: owner, ownerField: "id", operations: [create, delete] }]
  # )
  id: ID!
  name: String!
  type: UserType
  imageURL: String
  email: String!
  defaultSeatCount: Int
  assignedTableCount: Int
}

type Table
  # @searchable
  @model {
  @auth(
    rules: [
      { allow: owner }
      { allow: owner, ownerField: "assignedStaff", operations: [read] }
      {
        allow: groups
        groups: ["matriD", "manager"]
        operations: [create, update, read]
      }
    ]
  )
  id: ID!
  number: Int
  seatCount: Int
  event: Event! @connection(name: "EventTables")
  eventID: String
  seats: [Seat] @connection(name: "TableSeats")
  assignedStaff: String
  owner: String
}

type Seat
  # @searchable
  @model {
  id: ID!
  number: Int
  attending: Boolean
  table: Table! @connection(name: "TableSeats")
  tableID: String
  order: Order @connection(name: "SeatOrder")
}

type Order
  #  @searchable
  @model {
  id: ID!
  seat: Seat! @connection(name: "SeatOrder")
  meal: ChosenEventMeal! @connection
  temperature: Temperature
}

type Meal
  #  @searchable
  @model {
  id: ID!

  name: String!
  description: String!
  image: String
  temperature: Boolean
  vegetarian: Boolean
  glutenFree: Boolean
}

type ChosenEventMeal
  #@searchable
  @model {
  id: ID!
  event: Event! @connection(name: "EventChosenMeal")
  meal: Meal! @connection
}

enum EventType {
  Wedding
  SweetSixTeen
  Birthday
  Barmitsfa
}

enum UserType {
  manager
  matriD
  waiter
}

# @auth(
#    rules: [
#      # Defaults to use the "owner" field.
#      {allow: owner}
#      # Authorize the update mutation and both queries. Use `queries: null` to disable auth for queries.
#      {allow: owner, ownerField: "staffs", operations: [read, update]}
#    ]
#  )

type Session @model {
  id: ID!
  sessionToken: String
  refreshToken: String
}

enum Temperature {
  rare
  mediumRare
  medium
  mediumWell
  well
}

input CreateEventResolverInput {
  name: String!
  type: EventType!
  tables: Int
  meals: [String]
  date: AWSDateTime!
  shift: EventShift
}

input DeleteEventResolverInput {
  id: String!
}

type Mutation {
  createEventResolver(input: CreateEventResolverInput!): Event
    @function(name: "customMutation-${env}")
  deleteEventResolver(input: DeleteEventResolverInput!): Event
    @function(name: "customMutation-${env}")
}
```
I was able to get the same working by creating a whole new project

**Comment by manueliglesias** [comment]
> Here is the schema
> 
> ```
> # enum PostStatus {
> #   ACTIVE
> #   INACTIVE
> # }
> 
> # type Post @model {
> #   id: ID!
> #   title: String!
> #   rating: Int!
> #   status: PostStatus!
> # }
> 
> type Event @model {
>   # @searchable
>   id: ID!
>   name: String!
>   notes: String
>   tables: [Table] @connection(name: "EventTables")
>   dinnerSelection: [ChosenEventMeal] @connection(name: "EventChosenMeal")
>   type: EventType
>   eventDate: AWSDateTime!
>   shift: EventShift
> }
> 
> enum EventShift {
>   morning
>   night
> }
> 
> type User
>   # @searchable
>   @model {
>   # @auth(
>   #   rules: [{ allow: owner, ownerField: "id", operations: [create, delete] }]
>   # )
>   id: ID!
>   name: String!
>   type: UserType
>   imageURL: String
>   email: String!
>   defaultSeatCount: Int
>   assignedTableCount: Int
> }
> 
> type Table
>   # @searchable
>   @model {
>   @auth(
>     rules: [
>       { allow: owner }
>       { allow: owner, ownerField: "assignedStaff", operations: [read] }
>       {
>         allow: groups
>         groups: ["matriD", "manager"]
>         operations: [create, update, read]
>       }
>     ]
>   )
>   id: ID!
>   number: Int
>   seatCount: Int
>   event: Event! @connection(name: "EventTables")
>   eventID: String
>   seats: [Seat] @connection(name: "TableSeats")
>   assignedStaff: String
>   owner: String
> }
> 
> type Seat
>   # @searchable
>   @model {
>   id: ID!
>   number: Int
>   attending: Boolean
>   table: Table! @connection(name: "TableSeats")
>   tableID: String
>   order: Order @connection(name: "SeatOrder")
> }
> 
> type Order
>   #  @searchable
>   @model {
>   id: ID!
>   seat: Seat! @connection(name: "SeatOrder")
>   meal: ChosenEventMeal! @connection
>   temperature: Temperature
> }
> 
> type Meal
>   #  @searchable
>   @model {
>   id: ID!
> 
>   name: String!
>   description: String!
>   image: String
>   temperature: Boolean
>   vegetarian: Boolean
>   glutenFree: Boolean
> }
> 
> type ChosenEventMeal
>   #@searchable
>   @model {
>   id: ID!
>   event: Event! @connection(name: "EventChosenMeal")
>   meal: Meal! @connection
> }
> 
> enum EventType {
>   Wedding
>   SweetSixTeen
>   Birthday
>   Barmitsfa
> }
> 
> enum UserType {
>   manager
>   matriD
>   waiter
> }
> 
> # @auth(
> #    rules: [
> #      # Defaults to use the "owner" field.
> #      {allow: owner}
> #      # Authorize the update mutation and both queries. Use `queries: null` to disable auth for queries.
> #      {allow: owner, ownerField: "staffs", operations: [read, update]}
> #    ]
> #  )
> 
> type Session @model {
>   id: ID!
>   sessionToken: String
>   refreshToken: String
> }
> 
> enum Temperature {
>   rare
>   mediumRare
>   medium
>   mediumWell
>   well
> }
> 
> input CreateEventResolverInput {
>   name: String!
>   type: EventType!
>   tables: Int
>   meals: [String]
>   date: AWSDateTime!
>   shift: EventShift
> }
> 
> input DeleteEventResolverInput {
>   id: String!
> }
> 
> type Mutation {
>   createEventResolver(input: CreateEventResolverInput!): Event
>     @function(name: "customMutation-${env}")
>   deleteEventResolver(input: DeleteEventResolverInput!): Event
>     @function(name: "customMutation-${env}")
> }
> ```
> 
> I was able to get the same working by creating a whole new project

I am closing this issue, feel free to create a new one if you face more issues
