### ISSUE TITLE
Receiving warning "Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android"

### ISSUE THREAD

**Issue by MattiaCostamagna** [aws-amplify/amplify-js#5075]
**Describe the bug**
I'm developing a mobile application using React Native and I'm trying to integrate it with my API using the AWS Amplify SDK for Javascript. It's all working nicely except for a warning I'm getting due an AppSync subscription. Here's the message:
` WARN  Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
(Saw setTimeout with duration 300000ms)`

![image](https://user-images.githubusercontent.com/4272711/76527823-1f273780-6470-11ea-9e08-0d8000be5e60.png)

The subscribe function is working despite the warning message, but I think that an improvement should be considered nonetheless if there isn't one already.

Here's the function code that causes the warning:
```javascript
handleSubscription() {
	let sub = API.graphql({
		query: SubscribeWebSocketResponses,
		variables: { user: this.context.id },
		authMode: GRAPHQL_AUTH_MODE.AWS_IAM
	});
	sub.subscribe({
		next: ({ value: { data: { onWebSocketResponse } } }) => {
			console.log(onWebSocketResponse);
			if (
				// Checking data received
			) {
				return;
			}
			try {
				// Handling data
			} catch (err) {
				console.log(err);
			}
		},
		error: (error) => {
			console.log(error);
		}
	});
}
```

These are the dependencies' versions:
- "amazon-cognito-identity-js": "^3.2.5",
- "aws-amplify": "^2.2.6",
- "aws-amplify-react-native": "^3.2.2",

Thanks a lot in advance!

**Comment by jackatkoeln** [comment]
Seems to be a "won't fix" thing
https://github.com/facebook/react-native/issues/12981

**Comment by ajpaulingalls** [comment]
This should be addressable by breaking the timer into smaller pieces.  Setting long timers like this is a big performance no no on android.  Not sure why a timer needs to be set for 300000ms...

**Comment by humatic** [comment]
I'm experiencing this also. In lieu of a proper fix, I'm disabling the warning with
```
import { YellowBox } from 'react-native';
YellowBox.ignoreWarnings(['Setting a timer']);
```
It's not clear to me whether the underlying issue is something that RN needs to fix, Amplify needs to fix, or is something that I need to patch. Can anyone shed any light?

**Comment by MattiaCostamagna** [comment]
Thank you for your reply @humatic 

Even if your solution works, I don't think it's a good idea to just hide a warning, especially when it can cause performance issues. There are already too many apps that slow down our smartphones due to heavy background processing or stuff like that :thinking: .

This problem happens to me only when I use API subscription, so I think it is something related to keep alive or heartbeats sent to the AWS infrastructure in order to know when the client goes offline.
If I'm right, I think that this is not something we can patch without modifying the AWS amplify library.

Anyway, my *temporary* work around consists of doing what has been described [here](https://github.com/firebase/firebase-js-sdk/issues/97#issuecomment-427512040), and I think it's working because I'm not seeing the warning anymore.

**Comment by humatic** [comment]
> Even if your solution works, I don't think it's a good idea to just hide a warning, especially when it can cause performance issues.
I agree wholeheartedly. I will also try the temporary work around you linked. Thanks.

**Comment by ashika01** [comment]
@MattiaCostamagna Looks like this issue can be closed since this can be corrected without amplify patching anything. Let me know if thats not the case and I can reopen the issue.

**Comment by jfhidakatsu** [comment]
> @MattiaCostamagna Looks like this issue can be closed since this can be corrected without amplify patching anything. Let me know if thats not the case and I can reopen the issue.

How can this be corrected? Is it safe to hide the warning as above?

**Comment by antonfrancisjeejo** [comment]
To fix this issue...

Navigate to your node_modules/react-native/Libraries/Core/Timers/JSTimers.js file.

Look for the variable MAX_TIMER_DURATION_MS

Change its value to 10000 * 1000

Save the changes (with auto format turned off) and re-build your app.

It worked for me

**Comment by antonfrancisjeejo** [comment]
To fix this issue...

1. Navigate to your node_modules/react-native/Libraries/Core/Timers/JSTimers.js file.

2. Look for the variable MAX_TIMER_DURATION_MS
 
3. Change its value to 10000 * 1000

Save the changes (with auto format turned off) and re-build your app.

It worked for me

**Comment by DeniferSantiago** [comment]
it happens to me too
"aws-amplify": "^3.3.14",
"aws-amplify-react-native": "^4.2.7"

**Comment by jakemitchellxyz** [comment]
@antonfrancisjeejo this is NOT a solution, and the warning will come back the next time you run yarn/npm.

**NEVER** modify `node_modules/` files directly unless you want headaches in the future.

Just hide the warning like @humatic said. MOST likely, you are not working on an app in which this will be an issue. And if you think you are, ask your senior devs to make a decision about handling this warning per @MattiaCostamagna's advice. If you don't have senior devs, then you're fine. Just hide the warning.
