### ISSUE TITLE
React-Native: signing out, clearing DataStore and creating new user throws errors when trying query DataStore

### ISSUE THREAD

**Issue by nylki** [aws-amplify/amplify-js#5076]
**Describe the bug**
When `Auth.signOut()` is called by a subsequent `DataStore.clear()`, `Auth.signUp()` and `Auth.signIn()` of that newly signed up user, results in errors when trying to query the DataStore for items that should be accessible by everybody:

```
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not an object (evaluating 'storage.query')
http://192.168.127.115:8081/index.bundle?platform=ios&dev=true&minify=false:132391:31
[...snip]
```

When closing and re-opening the app, I can succesfully query the items that errored out previously.

**To Reproduce**
My **App.js** and **schema.graphql**: https://gist.github.com/nylki/fca10b04e215e777d5506d562f12c340
Users are configured to be able to signup with just username + password and are auto-confirmed in a pre-signup lampda-function.

**Expected behavior**
When signin out, calling `DataStore.clear()` and creating a new user, publicly accessible items in the synced DataStore should be resynced after signin or when querying.

**Smartphone (please complete the following information):**

- Device: iPhone X
- OS: iOS 13.2.3
- React-Native-App

my package.json: 
```.json
"dependencies": {
        "@aws-amplify/core": "^2.2.5",
        "@aws-amplify/datastore": "^1.0.8",
        "@react-native-community/netinfo": "^5.5.1",
        "amazon-cognito-identity-js": "^3.2.5",
        "aws-amplify": "^2.2.6",
        "aws-amplify-react-native": "^3.2.2",
        "react": "^16.13.0",
        "react-native": "^0.61.5",
        "react-spring": "^8.0.27"
    },
    "devDependencies": {
        "@babel/core": "^7.6.2",
        "@babel/runtime": "^7.6.2",
        "@react-native-community/eslint-config": "^0.0.5",
        "babel-jest": "^24.9.0",
        "eslint": "^6.5.1",
        "eslint-config-standard": "^14.1.0",
        "eslint-plugin-import": "^2.20.1",
        "eslint-plugin-node": "^11.0.0",
        "eslint-plugin-promise": "^4.2.1",
        "eslint-plugin-react": "^7.19.0",
        "eslint-plugin-standard": "^4.0.1",
        "ini": "^1.3.5",
        "inquirer": "^6.5.1",
        "jest": "^24.9.0",
        "metro-react-native-babel-preset": "^0.56.0",
        "react-test-renderer": "16.9.0"
    },
```

**Comment by yirako** [comment]
It seems that `DataStorage.clear()` sets `storage` object to undefined and it doesn't get reconstructed on next calls.
![image](https://user-images.githubusercontent.com/12821092/76561330-b4263280-6468-11ea-83f0-55dd6b62f794.png)
Looking at DataStorage source this is correct.
![image](https://user-images.githubusercontent.com/12821092/76561445-ecc60c00-6468-11ea-9c17-0ba47bd6c6ef.png)
Now looking at the internal `start()` function, looks like as `initialized` already has a value after using `clear()`, it falls into the `else` statement and doesn't set the `storage` var again
![image](https://user-images.githubusercontent.com/12821092/76561725-8097d800-6469-11ea-9aec-1473d0a837d3.png)
Solution might be to also set `initialized` to `undefined` on `clear()`

**Comment by nylki** [comment]
super, thanks!
