### ISSUE TITLE
I18n: Allow grouping labels in vocabulary

### ISSUE THREAD

**Issue by MattiaCostamagna** [aws-amplify/amplify-js#5079]
I think it would be useful to have the possibility of grouping the labels in the vocabulary in order to keep them organized.
Here's an example:

```javascript
const dict = {
    en: {
        login: {
			email: 'E-mail address',
			passw: 'Password',
			submit: 'Sign in'
		},
		signup: {
			email: 'E-mail address',
			name: 'Your name',
			submit: 'Sign up'
		}
    },
    it: {
        login: {
			email: 'Indirizzo e-mail',
			passw: 'Password',
			submit: 'Accedi'
		},
		signup: {
			email: 'Indirizzo e-mail',
			name: 'Il tuo nome',
			submit: 'Registrati'
		}
    }
};

I18n.putVocabularies(dict);
```

Retrieving the labels could be done by calling the `get` function in the following way:
```javascript
I18n.get('login.submit');
// or
I18n.getAll().login.submit;
// or
I18n.labels.login.submit;
```

I know this might result in duplicate labels (as the `email` field in the example above), but as I said before it'd definitely help keeping them organized.

Thank you

**Comment by ashika01** [comment]
@MattiaCostamagna : Hi, thanks for opening this feature request. Like you mentioned we may end up having duplications. 

We are working our new UI system now. You can read more about this #3279 (https://github.com/aws-amplify/amplify-js/issues/3279). We have basic i18n setup of transalation constants here - https://github.com/aws-amplify/amplify-js/blob/ui-components/master/packages/amplify-ui-components/src/common/Translations.ts

And probably split translations as we add more categories. Look for more updates on the RFC as we go forward.
