### ISSUE TITLE
Migration lambda not called in SignUp Flow

### ISSUE THREAD

**Issue by ak37165** [aws-amplify/amplify-js#5081]
**Describe the bug**
If we set up a migration lambda for the login and forgot password flow in AWS Cognito, that lambda is not called during the signup flow. So suppose we set up the user pool to use email as username. Then we set up a signup flow through our own server that checks if the new signup is using an email already in use in our legacy user database. 

Now an attacker gets our AWS client ID from our website's Javascript, and then uses it via the Amplify JS Auth SDK to call the signup API: such as using the example code at https://aws-amplify.github.io/docs/js/authentication under section "Signup". The attacker will effectively bypass our check to see if the email being used as a username in the signup request is already in use and end up creating a new user in Cognito. Now when the genuine user attempts to login, the migration lambda will never get called.

So effectively, an attacker would have blocked a genuine user from logging into our system, without any access to the victim user's email inbox or password.

**To Reproduce**
1. Create a user pool
2. Create an app client for Javascript (no app client secret key)
3. Setup a migration lambda for the user pool (so login attempts will fetch users from a legacy user database).
4. [as an attacker]: read our app client key from the Javascript code (freely served with our website) and use it to call the "Signup" API (example code at https://aws-amplify.github.io/docs/js/authentication under section "Signup")

THE MIGRATION LAMBDA gets bypassed!

**Expected behavior**
If a username (email) is in use in our legacy system, that should not be allowed for new user signup.

**Comment by ak37165** [comment]
It would appear that we need to replicate some of the migration lambda functionality in the Pre-Signup lambda as that does get called in the signup flow. Is that the recommended approach?

**Comment by ak37165** [comment]
Also, can we differentiate between the signup flows in the pre-signup lambda: such as a social/identity provider based login be treated differently than a password based signup?

**Comment by madsbrydegaard** [comment]
I can confirm this issue.

After switching from Hosted UI to amazon-cognito-identity-js integration my Migration Lampda script is NOT executed upon signin of users.

Version: "amazon-cognito-identity-js": "^3.2.6",

**Comment by ak37165** [comment]
> I can confirm this issue.
> 
> After switching from Hosted UI to amazon-cognito-identity-js integration my Migration Lampda script is NOT executed upon signin of users.
> 
> Version: "amazon-cognito-identity-js": "^3.2.6",

That is NOT the issue I described above. The Migration Lambda script does get executed when using the amazon-cognito-identity-Js SDK. Rather the issue is that the migration lambda check is not performed during Sign Up (it’s only done in sign In).  

Possible fix is to perform similar checks in PreSignup Lambda that does get called in the Sign Up flow.  However that lambda gets called after the migration lambda also if a migration is performed to create a new account. So seems one needs to carefully set up the algorithms in these lambdas to work smoothly for all flows. I was wondering if there is a simpler strategy. 

Simply having the PreSignUp lambda check that the username exists in the legacy system is not enough because that will block the migration in the login flow as well (pre signup lambda can be called both on direct signup and in the login flow when a migration is performed).

**Comment by madsbrydegaard** [comment]
Ok I hear you. 
It does however seem to me that the migration script is not executed. I will have to investigate more.

That said I agree with your point on the complexity.
I have for that reason abandoned the use of the migration script and moved the migration logic back into my own signup proces for better control. So now only using PreSignup for auto-confirming users.

**Comment by ak37165** [comment]
If using just your own signup process and own login process (ie, only your server will call Cognito) then you should disable the App client created for JavaScript (else an attacker can call Cognito using your Java script public key and bypass your server logic).

**Comment by madsbrydegaard** [comment]
Ok so just for the record I can confirm that Migration trigger is called upon signin - if auth flow is USER_PASSWORD_AUTH. 

This took me a while to understand and the documentation on the subject is not very acurate.

However the trick is to set the authenticationFlowType prop to USER_PASSWORD_AUTH on cognitoUser object before signin - and it works like a charm. 
(Default is USER_SRP_AUTH which sign users in without exposing passwords to the network)

>const cognitoUser = this.createCognitoUser(username)
cognitoUser.authenticationFlowType = "USER_PASSWORD_AUTH"

Please note that by using USER_PASSWORD_AUTH passwords are sent over the internet and hence creates a security risk.

**Comment by amhinson** [comment]
@ak37165 Were you able to get this figured out?
