### ISSUE TITLE
Does Auth.currentAuthenticatedUser() Automatically Refresh Token for LoginWithAmazon federated users?

### ISSUE THREAD

**Issue by AdonousTech** [aws-amplify/amplify-js#5082]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
When I use `Auth.federatedSignIn({customProvider: 'LoginWithAmazon'});` the user is created in the user pool and appropriate tokens are returned (JWT and refresh).

According to the [documentation](https://aws-amplify.github.io/docs/js/authentication#token-refresh), Amplify will automatically refresh tokens for Google and Facebook. **Does this also apply to LoginWithAmazon**?

When I call `Auth.currentAuthenticatedUser()` I get back an actual `CognitoUser` not a "federatedUser". I am making the assumption the user is not a strictly federatedUser because there is no entry in storage for `aws-amplify-federatedInfo`. 

The `currentAuthenticatedUser` method of the Auth class tries to access the federatedUser value based on a local storage object with a key 'aws-amplify-federatedInfo' See [Auth Class line 1203](https://github.com/aws-amplify/amplify-js/blob/a047ce73abe98c3bf82e888c3afb4d2f911805f3/packages/auth/src/Auth.ts#L1203). 

If there is no `federatedUser` Auth will attempt to fetch the CognitoUser by calling `Auth.currentUserPoolUser(...)` See [Auth Class line 1219](https://github.com/aws-amplify/amplify-js/blob/a047ce73abe98c3bf82e888c3afb4d2f911805f3/packages/auth/src/Auth.ts#L1219) Now, within the `Auth.currentUserPoolUser` method, the session is refreshed if it is expired. See [Auth Class line  1122](https://github.com/aws-amplify/amplify-js/blob/a047ce73abe98c3bf82e888c3afb4d2f911805f3/packages/auth/src/Auth.ts#L1122). That line calls the `getSession` method on the `CognitoUser` class. The `getSession` method employs logic to get a session, either from the session object, local storage, or **using a refresh token** See [the amazon-cognito-identity-js/CognitoUser class line 1016](https://github.com/amazon-archives/amazon-cognito-identity-js/blob/6b87f1a30a998072b4d98facb49dcaf8780d15b0/src/CognitoUser.js#L1016) for the full method definition.

**Question**: Does `Auth.currentUserPoolUser` actually refresh the access token for a LoginWithAmazon CognitoUser?

Based on my research, the answer seems to be in the affirmative. If that is true, the docs may need to be updated. Currently, its not clear for dummies like myself.

**Comment by AdonousTech** [comment]
I would like to clarify that I am referring to the [documentation ](https://aws-amplify.github.io/docs/js/authentication#oauth-and-federation-overview) listed under OAuth and Federation Overview. Specifically, I am referring to the tokens issued when using the user pool as a service provider (OAuth).

**Comment by ericclemmons** [comment]
@AdonousTech You've done some superb research on this!  I've been running a local demo using `LoginWithAmazon` since Friday and confirmed, yes, tokens appear to be refreshing just like `Google` and `Facebook` providers do.

I also confirmed that I got the `user` object back from both `currentUserPoolUser()` and `currentAuthenticatedUser()`.

I'll update the documentation to match!

**Comment by AdonousTech** [comment]
Excellent! Thanks, Eric.
