### ISSUE TITLE
Datastore | React Native | Valid realtime scenario?

### ISSUE THREAD

**Issue by jackatkoeln** [aws-amplify/amplify-js#5090]
Hello,

before I invest more nights in trying to understand why my app is not working as expect, I would like to ask a simple question.
Is Datastore the right amplify component for a realtime app like a chat? 

I have build the sample app from the documentation. 
https://aws-amplify.github.io/docs/js/datastore#example-react-native-application
Have just added auth (Cognito). 
Everything is up and running. Data is synchronizing in the cloud. Beautiful.

Nevertheless when I run the app on multiple devices, the data is no auto synchronizing on the devices.

Example:
Create data on Device A, doesn't affect Device B even when the subscription is in place. The subscription on Device B only has effect if I close and reopen the app. 

Running on Expo 36.

Any help? 

Thank you!

**Comment by Ashish-Nanda** [comment]
Hey, yes DataStore would be a good option for a chat based app given the realtime and offline capabilities.  Regarding the bug, can you tell me a bit more about your setup:

1) Since you added auth, I'm guessing your schema is not exactly that of the example app. Could you please share it? Link to a sample app would be even better.

2) Are you using `Amazon Cognito User Pools`?

3) When you say you do not get subscription based updates when creating data on Device A, and Device B, is it the same user logged in on both? Or are they different users but both have access to the data/ or the data is not protected by authorization rules?

**Comment by jackatkoeln** [comment]
@Ashish-Nanda first of all, thanks for the quick answer.

1. I am just using Auth for login and I have no auth rules on my schema.
```graphql
enum PostStatus {
  ACTIVE
  INACTIVE
}

type Post @model {
  id: ID!
  title: String!
  comments: [Comment] @connection(name: "PostComments")
  rating: Int!
  status: PostStatus!
}
type Comment @model {
  id: ID!
  content: String
  post: Post @connection(name: "PostComments")
}
```
Anyway I have tested with following auth rules, and the result is the same. Subscription on Device B only syncs to the Cloud after restarting the app and not automatically as expected for real time.
```graphql
@auth(rules: [{ allow: owner, operations: [create, update, delete] }])
```

2. Yes I am using `Amazon Cognito User Pools`. I have just implemented a `Login.js` that navigates me to the App provided in the documentation, so there is no real change here. 

3. I am logged in with User A in Device A and User B in Device B. Same iPhone model/version, as well as Expo Client. 

```json
"@aws-amplify/core": "^2.2.5",
"@aws-amplify/datastore": "^1.0.8",
"@react-native-community/netinfo": "4.6.0",
"expo": "^36.0.0",
"react": "16.13.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz",
"aws-amplify-react-native": "^3.2.2"
```

Obs: All is working as expected. The mutations are taking place locally and on the cloud. Creation, deletion and updates all fine. Only the subscription seems to not react on updates in the cloud. 

Thanks

**Comment by jackatkoeln** [comment]
Closing the topic after having a full read on this:
https://aws-amplify.github.io/docs/cli-toolchain/graphql?sdk=js#authorizing-subscriptions

Nevertheless it seems that Datastore doesn't fully support authorization on subscription.
There is a fix here, but I'm not sure if this should be also working on RN. 
https://github.com/aws-amplify/amplify-js/pull/4617

**Comment by undefobj** [comment]
@jackatkoeln DataStore supports authz on subscriptions and that fix was merged and published months ago. Are you still having this issue? If so lets keep it open so @Ashish-Nanda can help you resolve.

**Comment by manueliglesias** [comment]
Hey @jackatkoeln auth is supported today, if you are still having issues please feel free to open a new issue
