### ISSUE TITLE
How to make the cursor to onFocus in the confirmation input box

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#5093]
@ashika01  When I go to Forgot password and then to confirmation code screen, I need to place the cursor inside the input box.

I need to make the cursor to onFocus in the confirmation input box defaulty while navigating from Forgot password to Confirmatin screen (Code and new password screen)

**Comment by amhinson** [comment]
This isn't possible with aws-amplify-react-native at this point, so I'm just going to label this as a feature request for now. We will take this into consideration as we continue to make improvements to the library though!

**Comment by nihp** [comment]
Okay thanks.

**Comment by tannerabread** [comment]
A new React Native Authenticator was recently released with [documentation here](https://ui.docs.amplify.aws/react-native/connected-components/authenticator). Please try this out for your use case and if this doesn't fit your needs open up a new issue/feature-request in the [ui-repo](https://github.com/aws-amplify/amplify-ui/issues).

Thank you!
