### ISSUE TITLE
Subscriptions Not Working

### ISSUE THREAD

**Issue by karrettgelley** [aws-amplify/amplify-js#5094]
** Which Category is your question related to? **
GraphQL Transform, AppSync

** What AWS Services are you utilizing? **
AppSync, DynamoDB

** Provide additional details e.g. code snippets **
I have a schema with a couple of custom subscriptions (using @aws_subscribe) that filter on a field. It looks something like this:

```
type User
  @model {
  id: ID!
  email: AWSEmail!
  groups: [UserGroup] @connection(keyName: "groupsByUser", fields: ["id"])
}

type UserGroup
  @model(subscriptions: null)
  @key(name: "membersByGroup", fields: ["groupID", "memberID"])
  @key(
    name: "groupsByUser"
    fields: ["memberID", "groupID"]
    queryField: "groupsByUser"
  ) {
  id: ID!
  groupID: ID!
  memberID: ID!
  group: Group! @connection(fields: ["groupID"])
  member: User! @connection(fields: ["memberID"])
}

type Group @model {
  id: ID!
  members: [UserGroup] @connection(keyName: "membersByGroup", fields: ["id"])
}

type GroupInvitation
  @model(subscriptions: null)
  @key(
    name: "invitationsByInvitee"
    fields: ["inviteeID"]
    queryField: "invitationsByInvitee"
  ) {
  id: ID!
  groupID: ID!
  inviteeID: ID!
  inviterID: ID!
  group: Group! @connection(fields: ["groupID"])
  invitee: User! @connection(fields: ["inviteeID"])
  inviter: User! @connection(fields: ["inviterID"])
}

type Subscription {
  onCreateUserGroup(memberID: ID): UserGroup
    @aws_subscribe(mutations: ["createUserGroup"])
  onCreateGroupInvitation(inviteeID: ID): GroupInvitation
    @aws_subscribe(mutations: ["createGroupInvitation"])
}
```

I am not able to get onCreateUserGroup nor onCreateGroupInvitation to fire. I have tried in both the AppSync console and on my react client app both are failing to trigger. Has anyone ran into this before? Is it a schema issue? I created a new amplify project from scratch with just this schema and was able to determine that app configuration was not the issue. I can't figure it out

**Comment by tammomueller** [comment]
@karrettgelley did you resolve this issue?

**Comment by isacRU11** [comment]
@karrettgelley 
why closed this issue?
