### ISSUE TITLE
A suggestion regarding typings for the Amplify.configure() function

### ISSUE THREAD

**Issue by ryands17** [aws-amplify/amplify-js#5095]
Hey @dabit3 , I had sent added a comment on your tweet regarding the improvements that could be made to the Amplify docs but I had mentioned a couple of enchancements that I could contribute to, if possible.

I had the following points in mind and have created an example [repository](https://github.com/ryands17/amplify-auth) for the same.

1. The `Amplify.configure()` and the `Auth.configure()` have a config type of `any`. Is is possible to add types for these?

2. I have created a `getToken` method in the `auth.tsx` file in the above repo that obtains the token from either a username/password login or a social login for validating against API's. Is this the correct way to obtain the token or is there any other inbuild method that amplify provides?

**Comment by jimblanc** [comment]
We have published an RFC on our plan for improving TypeScript support in Amplify JS & would love to get your feedback & suggestions!

[RFC: Amplify JS TypeScript Improvements](https://github.com/aws-amplify/amplify-js/issues/11113)

**Comment by cwomack** [comment]
The developer preview for v6 of Amplify has officially been released with improved support for TypeScript and much more! Please check out our [announcement](https://aws.amazon.com/blogs/mobile/aws-amplify-javascripts-new-developer-preview-with-reduced-bundle-sizes-improved-typescript-and-next-js-support/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=238088647) and updated [documentation](https://docs.amplify.aws/lib-v1/project-setup/create-application/q/platform/js/) to see what has changed.

This issue should be resolved within the dev preview and upcoming General Availability for Amplify v6, but let us know with a comment if there are further issues.

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
