### ISSUE TITLE
Confused about Refreshing JWT Tokens with Hosted UI in react-native

### ISSUE THREAD

**Issue by annjawn** [aws-amplify/amplify-js#5096]
**Which Category is your question related to?**
Auth

**What AWS Services are you utilizing?**
Cognito

**Provide additional details e.g. code snippets**
I am a little confused about the usage here. The [documentation](https://aws-amplify.github.io/docs/js/authentication#react-components) says:

>  if you are using another federated provider, or the app is running in React Native, you will need to provide your own token refresh method

I am using Cognito Hosted UI, with `withOAuth` HOC from `aws-amplify-react-native`. My Cognito User Pool is federated with Google and Facebook, and I am able to log users in using the `this.props.facebookSignIn()` and `this.props.googleSignIn()` methods available in the props of the HOC. I am also able to call back end services and log users out. However, I am confused if I need to handle token refresh myself or if Amplify will take care of token refresh in case I used Hosted UI. The document seems to indicate (as shown above) that in case of react-native I will need to provide my own token refresh method. Does this still apply in case I am using Hosted UI? if so then is the only way to obtain the refresh token is via `Auth.currentAuthenticatedUser()` because `Cache.getItem('federatedInfo')` seems to be returning null and according to [this post](https://github.com/aws-amplify/amplify-js/issues/1011#issuecomment-397380473) by @powerful23  it sounds like `Cache.getItem` is only for federated identity pool rather than federated user pool with hosted UI. A little bit clarity on this would be really appreciated. 

I've looked at post #4388 and it looks like a working example of a react-native expo app with Federated identities with Google/Facebook; and I notice that `refreshHandlers` are being used there with `Auth`. So is the assumption that User Pool federation and usage of Hosted UI doesn't need any custom `refreshHandlers` to passed to `Auth`? If so, it would be great if it can be clarified in the documentation somewhere.

**PS**: I should mention that, I am not really facing any situation where the user tokens have expired and to me it looks like amplify is auto refreshing the tokens without me passing in any custom refresh method, but I really don't know how to verify that. I should also mention that I am on react-native with Expo (not that it would make any difference).

**Comment by ericclemmons** [comment]
>  I am not really facing any situation where the user tokens have expired and to me it looks like amplify is auto refreshing the tokens without me passing in any custom refresh method, but I really don't know how to verify that. I should also mention that I am on react-native with Expo (not that it would make any difference).

@annjawn Your experience is correct: Amplify auto-refreshes tokens for you when using Cognito Hosted UI.

Our docs have been relaunched at https://docs.amplify.aws/, as we're working to clarify use-cases.

Feel free to check out https://docs.amplify.aws/start/getting-started/auth/q/integration/react-native#authentication-with-amplify and click the "Feedback" button to let us know what can be improved!
