### ISSUE TITLE
Sending ClientMetadata while responding to a challenge

### ISSUE THREAD

**Issue by alanmv01** [aws-amplify/amplify-js#5106]
**Describe the bug**
The [RespondToAuthChallenge](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_RespondToAuthChallenge.html) API supports sending ClientMetadata. But, the js library does not send this automatically while sending custom auth challenges:
https://github.com/aws-amplify/amplify-js/blob/45b79f24371de398e36be2770a35aad128ba6ca3/packages/amazon-cognito-identity-js/src/CognitoUser.js#L729

This is sent correctly on InitiateAuth:
https://github.com/aws-amplify/amplify-js/blob/45b79f24371de398e36be2770a35aad128ba6ca3/packages/amazon-cognito-identity-js/src/CognitoUser.js#L257

The [DefineAuthChallenge](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-define-auth-challenge.html) trigger depends on this API to receive the client metadata:
```
You can pass this data to your Lambda function by using the ClientMetadata parameter in the AdminRespondToAuthChallenge and RespondToAuthChallenge API actions. 
```

**Comment by alanmv01** [comment]
It seems the issue with sending ClientMetadata correctly had been fixed. I was able to send the data as expected using:
```
cognitoUser.sendCustomChallengeAnswer(challengeResponses, this, ClientMetadata );
```

However, the index.d.ts file doesn't seem to support this signature:
https://github.com/aws-amplify/amplify-js/blob/master/packages/amazon-cognito-identity-js/index.d.ts#L96

**Comment by sammartinez** [comment]
@alanmv01 we have updated this as of late, can you verify on the signature?
