### ISSUE TITLE
Unable to see the verification messages in email id

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#5108]
I have using the aws-amplify-react-native-package. Here I can't able to see the verification code or link in my email.

But I have received the code for the registered mobile number.

Why the verification process not happened in the email Id?

How it will be handled in both mobile and email id?

**Comment by amhinson** [comment]
@nihp Could you elaborate a bit on the issue you're seeing? The verification email should only contain the code, in which the user would enter into the mobile app.

**Comment by nihp** [comment]
I am using phone number and email. I am receiving the code for phonenumber. But i not received the acknowledgement or anything regarding this in my email.

**Comment by amhinson** [comment]
This sounds like a Cognito configuration for your app. You can check what you have enabled if you go to your Cognito User Pool and see what attributes you have selected to verify. It sounds like you only have phone verification enabled.
