### ISSUE TITLE
'Username cannot be empty' error is thrown after filling the username in SignUp screen

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#5110]
In Sign Up screen it always shows 'Username cannot be empty' after I have filled the Username in sign Up screen in aws-amplify-react-native

**Comment by ashika01** [comment]
@nihp : are you using autofill? just wondering. We had a change out for this. We can track that. Could you also post the version you are using?

**Comment by nihp** [comment]
I am not using autoFill. Manually typing the input. Can you able to reproduce at your end?

I am using 

"aws-amplify-react-native": "^3.2.2"

**Comment by amhinson** [comment]
@nihp Are you still seeing this issue? If so, could you provide a code snippet of your usage, or maybe even an example repo we could test out?

**Comment by nihp** [comment]
This issue will raise if the user using the default screens from the  **aws-amplify-react-native**.

Yes, you can also reproduce this by adding the below code and check the sign Up screen with the following steps

1. Go to sign up screen
2. Hit the Sign Up with out filling any details. It shows **Username cannot be empty**
3. Again fill the username and hit the Sign Up. Again it will shows the error message  **Username cannot be empty**

Note: In 3rd step you only need to fill username alone
```

import {
  Authenticator,
  AmplifyTheme,
  Greetings,
  SignIn,
  ConfirmSignIn,
  RequireNewPassword,
  SignUp,
  ConfirmSignUp,
  VerifyContact,
  ForgotPassword,
  AuthPiece,
} from "aws-amplify-react-native";

```

**Comment by amhinson** [comment]
Can you also post how you're using those components?

**Comment by nihp** [comment]
For default screens
```
//Inside the render
<Authenticator> 
   <SignIn/>
  <SignUp/>
  <ForgotPassword/>
  <ConfirmSignUp/>
</Authenticator>

```

**Comment by amhinson** [comment]
When you ran `amplify add auth`, what option did you select for how the user should login? 
username, phone, or email?

**Comment by nihp** [comment]
In development I am using email to login and in production I am using phone number to login the app

**Comment by amhinson** [comment]
Might be related to this PR: https://github.com/aws-amplify/amplify-js/pull/5469

**Comment by amhinson** [comment]
@nihp We've made an update that might address the issue you're seeing. Could you try testing out the `unstable` version of `aws-amplify-react-native`?

```
yarn add aws-amplify-react-native@unstable
```
