### ISSUE TITLE
Amplify.Auth.currentUserCredentials() reports misleading error when Identity Pool Role trust relationship is improper

### ISSUE THREAD

**Issue by brooksidesw** [aws-amplify/amplify-js#5113]
**Describe the bug**
When AuthClass.currentUserCredentials() encounters an error using the current session, it falls back to the "guest" ID, perhaps hoping to get credentials through an unauth role.  Doing so, however, loses the information from the original failure.  For example, if the auth role trust relationships are not proper, this fact gets lost and a misleading error ("cannot get guest credentials when mandatory signin enabled") is returned instead.

I suggest that this fallback is not a good idea at all.  If a user has signed in, but there are issues with the Identity Pool configuration, this should not be hidden with a fallback to the unauth role.

If nothing else, please preserve the original error and report it.

**To Reproduce**
1. Create User Pool and partner Identity pool.  Add a test user to the User Pool.
2. Mis-configure the auth role trust relationships for the Identity Pool.
3. Log in as the test user, then call AuthClass.currentUserCredentials() within the context of the successful login.
4. Get the misleading error described above.

**Expected behavior**
An error indicating that there is an issue with the ID Pool configuration.

**Comment by sammartinez** [comment]
@brooksidesw Can you please provide us with your `package.json` to us? Seems you may be using an older version of Amplify JS and want to confirm. Thanks ahead of time.

**Comment by brooksidesw** [comment]
Attached is the package.json that I was using at the time.  I have since upgraded to "aws-amplify": "^2.3.0".  I have not tested to see how 2.3.0 behaves.

[package.json.march.zip](https://github.com/aws-amplify/amplify-js/files/4752967/package.json.march.zip)

**Comment by brooksidesw** [comment]
An update to "How to reproduce": also disable access to unauthenticated identities on the Identity Pool.
