### ISSUE TITLE
After remove the greetings, I got a blank white screen

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#5118]
I not need to show the username and SignOut button while login the app. Also, how can I hide the please Sign In/ Sign up label in all Authenticating screens.

So I have removed the greetings from the import and usage. Now it shows a white screen.

**Comment by ashika01** [comment]
@nihp are you using react components or react native? I am unsure on react native, however for the others, removing greetings component would remove the signout button. If you want signout, then you will have to add signout to your flow.

**Comment by nihp** [comment]
Already I have added the Signout in my apps flow. But the Greetings also showing the username and signout default Authenticator component of **react-native.**


Note: So I have customized the screens  now for my requirement.  So it will not show in my UI, because I not using the greetings component inside the react-native app.

**Comment by ashika01** [comment]
@nihp: gotcha.. I am curious about this case, if you could post a sample code for me to reproduce this. it would be great.

**Comment by nihp** [comment]
I have used all screens from Authenticator with loading

```
  <Authenticator
          hideDefault ={true}
          amplifyConfig={awsmobile}
          theme={this.state.theme}
          signUpConfig={signUpConfig}
          onStateChange={this.onStateChange}
        >
          <SignIn/>
          <SignUp  signUpConfig={signUpConfig} />
          <ForgotPassword/>
          <ConfirmSignUp/>
          <VerifyContact/>
          <SignIn/>
          <Loading/>
        </Authenticator>
```

**Comment by the-smart-home-maker** [comment]
I have the same problem described here - I am using React Native and when wrapping my App with Authenticator, after successful login, I will receive a blank white screen. In the background, my components that should be called as soon as the user got authenticated, get called and all background tasks are performed as desired. So it's just about the UI not showing up. I tested this with different components to show and was now able to narrow it down to a somehow existing incompatibility between aws amplify and React Navigation. If I  use a Tab Navigator as my basic app router, then the blank white screen issue pops up.

Any solution to this?

**Comment by the-smart-home-maker** [comment]
For my part, I got this issue resolved. The problem (at least in my case) was that the TabNavigator does not work with align values in stylesheets set. So I had to change the stylesheet value for the AWS Amplify container from
`container: {
            ...
    		alignItems: 'center',
    		justifyContent: 'space-around',
            ...
    	},`

to the default values

`container: {
            ...
            alignItems: 'stretch',
            justifyContent: 'flex-start',
            ...
        },`

- that did the trick. You can also just remove alignItems and justifyContent.

**Comment by amhinson** [comment]
@nihp Are you still having issues with this or did you get it resolved?

**Comment by nihp** [comment]
Will check and let you know. Did you have any updates regarding this issue?
