### ISSUE TITLE
Appsync IAM not working properly

### ISSUE THREAD

**Issue by ricardoribas** [aws-amplify/amplify-js#5122]
**Describe the bug**
I am using CognitoUserPool auth type as a default and IAM as a secondary authentication type (to be used in lambda functions). If i use the IAM auth in the appsync console to make mutations, is not working properly. I always receive old values for the model. I've added logs to the appsync to try to figure out what is happening under the hood, but no error is defined except 

`CustomTemplateException(message=An internal error occurred., errorType=InternalFailure, data=null, errorInfo=null)`

I am using **requests** python library in lambda functions to perform a signed request. The outcome of those requests are always null mutation but with a **200_OK** status code. 

**To Reproduce**
1 - Go to the appsync console
2 - Select the IAM authentication type
3 - Execute a mutation on a data source
4 - See the old values appear in the result

**Expected behavior**
Should show the newest values for that model

**Comment by sammartinez** [comment]
@ricardoribas Are you using AppSync with Amplify? If so, can you please provide a gist/code snippet of your implementation?

**Comment by ricardoribas** [comment]
@sammartinez i am using it with amplify, yes. If i use the appsync console is enough to replicate the issue. All the queries seem to be working. However, mutations are the ones that are failing. I suppose that subscriptions will also fail as they are not GET's and require extra permissions perhaps.

**Comment by sammartinez** [comment]
@ricardoribas Apologizes on circling back on this until now, can you provide your `package.json` you are using for this ?
