### ISSUE TITLE
DataStore error: Failed to execute 'transaction' on 'IDBDatabase'

### ISSUE THREAD

**Issue by karrettgelley** [aws-amplify/amplify-js#5130]
**Describe the bug**
A bug is encountered when trying to save an item to the DataStore: Unhandled Rejection (NotFoundError): Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.

**To Reproduce**

1. Follow this tutorial on [how to make a crud app with DataStore](https://medium.com/open-graphql/create-a-multiuser-graphql-crud-l-app-in-5-minutes-with-the-amplify-datastore-902764f27404).

2. Add the following to the schema:
User @model {
  id: ID!
  firstName: String
  lastName: String
}

3. Generate new models and push changes (npm run amplify-modelgen, npm run amplify-push)

4. Import the User model and change the handleSubmit function to instead create a new User like so

  const handleSubmit = evt => {
    evt.preventDefault();
    evt.stopPropagation();
    DataStore.save(
      new User({
        firstName: ''first",
        lastName: "last"
      }),
    );
  };

5. Reload app and press the submit button.

**Expected behavior**
A user should be created in the DataStore and then synced to the cloud.

**Screenshots**
![Screen Shot 2020-03-18 at 1 53 49 AM](https://user-images.githubusercontent.com/31458115/76933698-b6025280-68bb-11ea-87ab-c37b7ccaa747.png)

**Smartphone (please complete the following information):**

- Device: Mac
- OS: MacOS Catalina 10.15.3
- Browser: Brave
- Version 1.3.115

**Additional context**
I really don't know what this error means. I've been getting a lot of strange DataStore errors lately and I don't understand any of them.

**Sample code**
Follow the aforementioned tutorial. Its really quick.

**Comment by ashika01** [comment]
@karrettgelley could see if the indexedDB table in your browser and let us know of the table[object store] created there?

**Comment by karrettgelley** [comment]
@ashika01 How do I do that? I'm pretty sure this issue is related to #5115 and this similar [DataStore ios error](https://github.com/aws-amplify/amplify-ios/issues/340). The initialization is just very finicky imo. Sometimes I can get DataStore to work, and other times it doesn't. In particular, when I update the api by adding a type or a field, DataStore seems to break.

**Comment by apoorvmote** [comment]
@karrettgelley The tutorial is faulty
```
DataStore.save(
      new Note({
        note: value
      })
    );
    listNotes(setNotes);
```
The save function `Datastore.save` is async so you need to `await` for it to finish before calling query function. Another issue is 
```
async function listNotes(setNotes) {
  const notes = await DataStore.query(Note, Predicates.ALL);
  setNotes(notes);
}
```
The `listNotes` it self is async function why not wait until its finished.

**Comment by karrettgelley** [comment]
@apoorvmote You'll find that if you add async it doesn't fix the problem. DataStore has bugs in its initialization I think. I haven't been able to get it to work consistently.

**Comment by apoorvmote** [comment]
I would like to add to the bug that `npm run amplify-push` is crashing on me. So I gave up on `npx amplify-app@latest`. Also I hate the idea of not having control on naming of the app on aws. It also created naming conflicts for environment. I cannot have 2 dev environment on 2 different project. I had to call other dev1 to fix it.

**Comment by karrettgelley** [comment]
@apoorvmote Agreed. DataStore has some problems and I'm just hoping one of the devs sees these posts. Although your issue is mostly cosmetic, there are tons of esoteric bugs that are flagged as to-be-reproduced which don't seem to be taken seriously atm.

**Comment by ashika01** [comment]
> @ashika01 How do I do that? I'm pretty sure this issue is related to #5115 and this similar [DataStore ios error](https://github.com/aws-amplify/amplify-ios/issues/340). The initialization is just very finicky imo. Sometimes I can get DataStore to work, and other times it doesn't. In particular, when I update the api by adding a type or a field, DataStore seems to break.

Not really. So there is well **three parts** to Amplify Datastore. There is local storage (**Storage adapters/engine**) which happens in your browser using IndexedDB(this is were all the data stored) similar to that of the dynamodb storage in the backend. then there is **Sync Engine** (this bit involves all logic related to sync the data btw backend). The Datastore API itself which is your high level abstraction. You can read more on [how it works](https://aws-amplify.github.io/docs/js/datastore#how-it-works).

So coming to this issue, this happens purely locally. This is an error thrown by the local storage [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) itself. Reasons you might get such error in indexedDB could be:
- table intended for your case has not been created / or not created properly.
- if the table is created, then data provided for the save could have been not of intended format.

To see the indexeddb table, 
- do browser inspect on your app
- open application tab in there
- uncollapse the indexeddb tab
- uncollapse table created and see if `user` table is created

**Comment by undefobj** [comment]
> I would like to add to the bug that `npm run amplify-push` is crashing on me. So I gave up on `npx amplify-app@latest`. Also I hate the idea of not having control on naming of the app on aws. It also created naming conflicts for environment. I cannot have 2 dev environment on 2 different project. I had to call other dev1 to fix it.

@apoorvmote Can you open a new issue with the full stack trace of your crash? I haven't seen any reports of this. Also if there are features you'd like to enhance the flow of the `amplify-app` npx script we'd love to hear them rather than you giving up on them so that we can improve it.

**Comment by undefobj** [comment]
> @apoorvmote Agreed. DataStore has some problems and I'm just hoping one of the devs sees these posts. Although your issue is mostly cosmetic, there are tons of esoteric bugs that are flagged as to-be-reproduced which don't seem to be taken seriously atm.

@karrettgelley We have a triaging process to review all category issues and work through a metric system for prioritization, and everything is taken seriously with a full time team working across different projects. While we can only address so many things at a certain time since the Amplify project as a whole is tackling very difficult concepts, the best way to help us out is by commenting on issues with details of your use case/adding reactions/+1s as this will help us prioritize and design correctly.

**Comment by undefobj** [comment]
> @ashika01 How do I do that? I'm pretty sure this issue is related to #5115 and this similar [DataStore ios error](https://github.com/aws-amplify/amplify-ios/issues/340). The initialization is just very finicky imo. Sometimes I can get DataStore to work, and other times it doesn't. In particular, when I update the api by adding a type or a field, DataStore seems to break.

@karrettgelley can you give more complete code examples here of what you're doing in your schema and your app code? You mention that there are issues when updating a type or initialization. What does your app lifecycle look like? Are you running modelgen and pushing again? Are you changing required fields?

**Comment by apoorvmote** [comment]
@undefobj I have commited my client that I will deliver the app by 1st of next month. So instead of posting crash report I just used the alternative that actually works and initialized the app with `amplify init` instead of `npx amplify-app@latest`. And I have working app with this way. Basically I havn't gave up on datastore but using it to deliver app to my customer. But I will also post bug report on amplify-cli github also.

**Comment by undefobj** [comment]
@apoorvmote excellent sounds like a plan

**Comment by karrettgelley** [comment]
@undefobj I'm going to close this issue because I believe it is intimately related to #5115 . Check out the repo I made that [demonstrates the DataStore syncing error](https://github.com/karrettgelley/datastore-demo). Thanks for your response

**Comment by rideddy84** [comment]
I think it sometimes could be happening when `data model` is changed.
I resolved that with below.
```
DataStore.start().catch(() => {
  DataStore.clear().then(() => {
    DataStore.start();
  });
});
```

**Comment by efraindx** [comment]
In my case I didn't have the table created in `IndexedDB`. I fixed this by deleting the `IndexedDB `and reloading the page (it created the DB again)

**Comment by techandmedia** [comment]
> In my case I didn't have the table created in `IndexedDB`. I fixed this by deleting the `IndexedDB `and reloading the page (it created the DB again)

Thank you, this solved my issue
