### ISSUE TITLE
How to make a head request to a bucket file with Storage?

### ISSUE THREAD

**Issue by Hideman85** [aws-amplify/amplify-js#5131]
**Which Category is your question related to?**
Storage

**What AWS Services are you utilizing?**
S3 + Cognito

**Provide additional details e.g. code snippets**
I simply need to head a file from my bucket but I where not able to do it since we have no method for that and the get method produce a signed url for getObject and so head is forbidden.

I try to find a way to access to your internal s3 client with no success either.

And I finally try to create a new s3 client instance as I think you do it internally but infine I got a missing credentials error.

There is the code I did:
```js
AWS.config.update({
  region: awsconfig.aws_user_files_s3_bucket_region,
  credentials: new AWS.CognitoIdentityCredentials({
    IdentityPoolId: awsconfig.aws_cognito_identity_pool_id
  })
})
const s3Client = new AWS.S3({ apiVersion: '2006-03-01', params: { Bucket: awsconfig.aws_user_files_s3_bucket } })

const response = await s3Client.headObject({ Key: currentValue }).promise()
``` 

Have you any idea how to do a head request on a bucket object?

**Comment by Hideman85** [comment]
Could be seen as a feature request

**Comment by sw-yx** [comment]
do you mind +1ing this request? https://github.com/aws-amplify/amplify-js/issues/6830 if its close enough to your needs?

**Comment by sammartinez** [comment]
Resolving in favor of the above feature request
