### ISSUE TITLE
cognito access token does not contain custom scopes 

### ISSUE THREAD

**Issue by TheRealVish** [aws-amplify/amplify-js#5132]
**Describe the bug**
Cognito access token returned by aws-sdk programmatically does not contain custom scope. This mean we have to rely on a 3rd party identity provider such as auth0.

**To Reproduce** AND **Sample Code**
Steps (in readme) and sample code in the below repo

  ___ - ___ - ___  https://github.com/TheRealVish/node-cognito  ___ - ___ - ___

**Expected behavior**
Access token returns all custom scopes

**Important**
Please do not close without checking with me. Thanks.

**Comment by sammartinez** [comment]
@TheRealVish In looking at the code you provided, it seems to be specific to Amazon Cognito and we do advise to reach out with to them via the [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=173) since you don't have any direct dependency of Amplify JS.

**Comment by TheRealVish** [comment]
Thanks.

**Comment by TheRealVish** [comment]
**Note to the visitors of this thread:** 

I have raised this with AWS and will update this thread when I get response.
