### ISSUE TITLE
Validation mesages are retained in the screens if I revisits the screen

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#5143]
Validation error messages are retained in the screen, If I revisits the already error shown screen in UI.

I am using aws-amplify-react-native with not customizable screens. 

Any solution here to refresh the screen?

**Comment by nihp** [comment]
Any solution for the above.

I have customized the UI now, and again it showing the same error (Error message is retained in the screen.)

I have customized and override the SignUp, SignIn, ForgotPassword

**Comment by amhinson** [comment]
@nihp There isn't a way right now to refresh the error messages, but we will look into it in the future. Thanks for bringing it to our attention 👍

**Comment by nihp** [comment]
@amhinson Thanks for your reply 

Any temporary solution will help for me.

**Comment by nihp** [comment]
@ashika01 Can you able to give any solution to do any temporary fix?

**Comment by amhinson** [comment]
@nihp Unfortunately there isn't a workaround right now, but we will look into adding this in the future as we work on revamping the React Native library.

**Comment by nihp** [comment]
@amhinson  Thanks

**Comment by tannerabread** [comment]
There was a new Authenticator released recently for React Native with [documentation here](https://ui.docs.amplify.aws/react-native/connected-components/authenticator). If you are experiencing an issue with the new component, please open an [issue here](https://github.com/aws-amplify/amplify-ui/issues)

Thank you!
