### ISSUE TITLE
Cannot get Customer Scope set in Access Token

### ISSUE THREAD

**Issue by shukii** [aws-amplify/amplify-js#5147]
**Describe the bug**
Current when using aws-amplify to authorise with Cognito, the scope returned in the access token is only the default

`{
  "sub": "X,
  "event_id": "X",
  "token_use": "access",
  "scope": "aws.cognito.signin.user.admin",
  "auth_time": 1584551201,
  "iss": "https://cognito-idp.us-east-2.amazonaws.com/us-east-2XXX",
  "exp": 1584554801,
  "iat": 1584551201,
  "jti": "XXX",
  "client_id": "XXX",
  "username": "XXX"
}`

**To Reproduce**
* Set up the custom scopes in Cognito
* Add custom scope to amplify config
* Make request

**Expected behavior**
The custom scope should be contained within the token

**Additional context**
There seems to be a lot of issues of this nature, however they have been closed without a resolution

**Comment by elorzafe** [comment]
Amplify is an open source library that allows customers to interact with Cloud Services such as Amazon Cognito.
Amazon Cognito provides a mechanism to get different scopes on the access token. This mechanism is only supported on OAuth flow using Cognito HostedUI. We’ve communicated the feedback to the Cognito team for their backlog, but I would also encourage you to open a case through your support channels to provide direct feedback outside of the GitHub forums.
