### ISSUE TITLE
How to do  role based authentication for aws cognito ? Urgent !!!

### ISSUE THREAD

**Issue by reckinam** [aws-amplify/amplify-js#5148]
** Which Category is your question related to? **
E.g. Auth,amplify
** What AWS Services are you utilizing? **
E.g. Cognito

I am building an online billing website per owner. In that application, the owner can view the dashboard of sales, add product , view shop accountancy, and bill the product. The same Account owner has team members like salesperson and accountants person.The solution that I need if the owner logged in, he should see everything (dashboard, billing and add product). If the salesperson logged in , he has access to add products only.

Need advice about how to do it?

**Comment by ericclemmons** [comment]
@reckinam It sounds like the `@auth` transform is exactly what you're looking for: it allows you to restrict `@model`s based on `owner` and `groups`:

> https://aws-amplify.github.io/docs/cli-toolchain/graphql#auth
