### ISSUE TITLE
API signing does not work with multipart form-data content

### ISSUE THREAD

**Issue by rmaroun** [aws-amplify/amplify-js#5150]
I have an upload api endpoint that is behind API Gateway. When I call this upload endpoint via API gateway using aws amplify on my react native app without signing the request (as my endpoint auth on api gateway us set to none) then all is working fine (content type of the request a multipart form data). When I add AWS_IAM as the authentication method of my upload method on API gateway and I sign the request with amplify signer in the react-native app then I get a mismatch signature message from api gateway. The thing is if I sign my request data with json.stringify and reuse it in the body of my fetch request with json.stringify then the request passes the api gateway auth but the content is considered as application/json and not converted into a multipart/form-data. When I do not use json.stringify in the signer for the request data property and use the formdata content in both the signed request data and in the fetch body property then i get a mismatch signature message back from api gateway. How can i sign my request keeping the formdata as is and not having to stringify it so api gateway automatically received a multipart/form-data?

**Comment by LandedE** [comment]
@rmaroun Did you solve this issue? I am having the same problem.

**Comment by rhard** [comment]
Same here
