### ISSUE TITLE
React Native Authentication Fields Blank

### ISSUE THREAD

**Issue by spanky411** [aws-amplify/amplify-js#5153]
**Describe the bug**
On a recent iphone, text fields did not render text. Text was still present in the fields, just not visible.

**To Reproduce**
I didn't ask for the ios version because I landed here and saw 595 open issues and figured this probably is the least of the issues.

**Expected behavior**
text typed should be visible (i.e. username... even the password should have characters rendered)

**Comment by amhinson** [comment]
Hey @spanky411, thanks for opening this. No issue is too small 🙂 

Would you be able to provide a bit more details in reproducing this, and possibly even some screenshots so we can have a better understanding of the issue?

**Comment by spanky411** [comment]
Unfortunately I don't, but I did see it on the phone where it was happening and can verify text entered in the fields (signup and login components) was not rendering in the textinput field.

I was hoping someone else might have seen a similar issue. I haven't seen this behavior in other react native textinput, or in these components on other phones in the same app. I'll see If I can get a hold of the phone where this happened and verify if its still happening. I suppose it could be one of those random glitches.

I found this, but I don't think it's quite what I saw in this case:
https://github.com/facebook/react-native/issues/22627

**Comment by pokey** [comment]
This happens when I use `withAuthenticator(App, true)` and only occurs when I run on my actual iPhone X (iOS 13.3.1).  When I run on an iPhone X simulator running iOS 13.3, I can see the text just fine.  Here's a screenshot of my iPhone:
![IMG_9987](https://user-images.githubusercontent.com/755842/78979097-0a8f9b00-7b13-11ea-93f7-4ca7202f60ac.PNG)
I am using the following versions:
```
aws-amplify: "3.0.5"
aws-amplify-react: "4.1.4"
aws-amplify-react-native: "4.0.2"
react-native: "0.62.1"
react: "16.11.0"
```

Please let me know if there are other details that might help.  Thanks!

**Comment by amhinson** [comment]
Excellent. Thanks @pokey! We'll check on this and get back to you with an update.

**Comment by amhinson** [comment]
@pokey One other question. Are you using the `aws-amplify-react` library at all in your project?

**Comment by pokey** [comment]
I don't think so.  I think I installed it by accident while I was flailing
trying to get things to work initially 😊

**Comment by amhinson** [comment]
So it seems like a [recent React Native issue](https://github.com/facebook/react-native/issues/27696) related to dark mode. I was able to reproduce this on a physical device as well as the simulator (Settings > Developer > Dark Appearance). 

It seems we can update this within `aws-amplify-react-native` by specifying the `color` style as well as the `placeholderTextColor`.

However, you should be able to override dark mode entirely in your app by implementing either of these suggestions:
https://github.com/facebook/react-native/issues/26299#issuecomment-536155972
https://github.com/facebook/react-native/issues/26299#issuecomment-540261084
