### ISSUE TITLE
React Native Cant Reset A Password

### ISSUE THREAD

**Issue by spanky411** [aws-amplify/amplify-js#5154]
**Describe the bug**
One of the only UI features in cognito is to force a password reset. Unfortunately that doesn't work in the amplify react native ui, leaving the only option to delete the user and have them sign up again.

**To Reproduce**
Install amplify and amplify react native.
Create an account in the app.
Through the cognito UI, "Reset Password" for that user
Go back to the app and try to log in

It appears the Auth component is throwing a "PasswordResetRequiredException". It looks like the react native signin component expects Auth.signin to not error out, but set user.challengeName === 'NEW_PASSWORD_REQUIRED'

**Expected behavior**
Work as advertised - i.e. user can change password in the app (or in the cognito UI, provide some way to recover from this condition)

**Comment by mikeRChambers610** [comment]
I am still having this issue. How do you handle user.challengeName === 'NEW_PASSWORD_REQUIRED'??
