### ISSUE TITLE
How can DataStore observe changes on one item?

### ISSUE THREAD

**Issue by waltermvp** [aws-amplify/amplify-js#5156]
** Which Category is your question related to? **
DataStore / API

** What AWS Services are you utilizing? **
DynamoDB Appsync

** Provide additional details e.g. code snippets **
The following observes the entiire Events table:

```
    const subscription = DataStore.observe(Event).subscribe(msg => {
      console.log(msg.model, msg.opType, msg.element);
      onQuery();
    });
```

How can I observe changes for one specific Event item using an `id`?

**Comment by manueliglesias** [comment]
Hi @waltermvp 

You can observe one item like this:

```js
    const id = '69ddcb63-7e4a-4325-b84d-8592e6dac07b';

    const subscription = DataStore.observe(Event, id).subscribe(msg => {
      console.log(msg.model, msg.opType, msg.element);
      onQuery();
    });
```

**Comment by waltermvp** [comment]
@manueliglesias this is it thank you
