### ISSUE TITLE
Update crypto-js to ^3.2.1

### ISSUE THREAD

**Issue by ericclemmons** [aws-amplify/amplify-js#5159]
**Describe the bug**

> The `secureRandom()` method is supposed to return a cryptographically strong pseudo-random data string, but it is biased to certain digits. An attacker could be able to guess the created digits.
> – https://app.snyk.io/vuln/SNYK-JS-CRYPTOJS-548472

https://github.com/aws-amplify/amplify-js/blob/ab08e38e22801e3a212f299057ecc9670fae5633/packages/auth/package.json#L40

**Expected behavior**

**Additional context**

Customers have expressed concern over whether Amplify is affected by this vulnerability.

**Comment by ericclemmons** [comment]
The original issue came from `^3.2.0` not including the `crypto` library for React Native, breaking apps.

To resolve this security notice, bump to `^3.3.0` and perform regression tests:
> https://github.com/brix/crypto-js/issues/256#issuecomment-585175130

**Comment by ericclemmons** [comment]
❗Include @Ashish-Nanda to review the PR

**Comment by JaroVDH** [comment]
Sorry to bump this closed ticket, but that very same vulnerability is marked as an issue again for crypto-js versions **>=3.3.0 <4.0.0 || <3.2.1**.

Upgrading to a new major version might require a bigger effort though, so should I create a new issue for this?

**Comment by emma3333** [comment]
As this issue has been closed, I've created a new issue for this https://github.com/aws-amplify/amplify-js/issues/8256
