### ISSUE TITLE
Datastore does not sync @connections relationships

### ISSUE THREAD

**Issue by waltermvp** [aws-amplify/amplify-js#5161]
**Describe the bug**
Cannot sync a save a @connection relationship using Datastore. The object exists locally but does not sync.

1. Use this model
```
type Event @model {
  id: ID!
  name: String!
  notes: String
  tables: [Table] @connection(name: "EventTables")
  type: EventType
  eventDate: AWSDateTime!
  shift: EventShift
}

type Table @model {
  id: ID!
  number: Int
  seatCount: Int
  event: Event! @connection(name: "EventTables")
  eventID: String
}

```

2. Save data

```
    const event = await DataStore.save(
      new Event({
        name: `New title ${Date.now()}`,
        notes: "NOTES TESTING",
        type: EventType.WEDDING,
        shift: EventShift.NIGHT,
        eventDate: new Date().toISOString()
      })
    );

const tableInput = {
        number: 001,
        seatCount: 10,
        eventID: newEventID,
        event: event[0]// save retrurns an array
      };
      const tableSAve = await DataStore.save(new Table(tableInput));
      console.log("TableSave", tableSAve);
```
logs from tableSave
```
[Model]
0: Model
number: 4
seatCount: 10
eventID: "86284da0-aabf-400f-b285-fe033fd7ceb9"
event: {id: "86284da0-aabf-400f-b285-fe033fd7ceb9", name: "New title 1584746201669", notes: "NOTES TESTING", type: "Wedding", eventDate: "2020-03-20T23:16:41.669Z", …}
id: "6c13d0a9-74f9-4db6-aace-d77b0d82c02a"
_version: undefined
_lastChangedAt: undefined
_deleted: undefined
```

3. See error
```
{localModel: Model, message: "Variable 'input' has coerced Null value for NonNull type 'EventInput!'", operation: "Create", errorType: undefined, errorInfo: undefined, …}
localModel: Model {id: "da9b93b3-64a1-46ad-99f1-6d962e39c363", number: 0, seatCount: 10, eventID: "86284da0-aabf-400f-b285-fe033fd7ceb9", _version: undefined, …}
message: "Variable 'input' has coerced Null value for NonNull type 'EventInput!'"
operation: "Create"
errorType: undefined
errorInfo: undefined
remoteModel: null
__proto__: Object

```

When saving data without the EventTables @connection the data save fine.

**Comment by rpostulart** [comment]
Same issue here with this schema:

`type Quiz @model @auth(rules: [{ allow: public, provider: iam }]) {
  id: ID!
  title: String!
  subscribers: [Subscribers] @connection(name: "QuizSubscribers")
  resonses: [Responses] @connection(name: "QuizResponses")
  started: Boolean!
}

type Questions @model {
  id: ID!
  question: String!
  answers: [Answers] @connection(name: "QuizAnswers")
  resonses: [Responses] @connection(name: "QuestionResponses")
}

type Answers @model {
  id: ID!
  answer: String!
  status: Boolean
  question: Questions @connection(name: "QuizAnswers")
}

type Subscribers @model {
  id: ID!
  quiz: Quiz @connection(name: "QuizSubscribers")!
  name: String!
  score: Int!
  responses: [Responses] @connection(name: "SubscriberResponses")
}

type Responses @model {
  quiz: Quiz @connection(name: "QuizResponses")
  time: String!
  question: Questions @connection(name: "QuestionResponses")
  subscriber: Subscribers @connection(name: "SubscriberResponses")
}
`

**Comment by waltermvp** [comment]
@rpostulart this appears to be fixed, have you tried with the latest version? Save no longer returns an array.  Also saving with the relation object now establishes the connection.

**Comment by rpostulart** [comment]
Not yet, but I will test later

**Comment by GeorgeIwu** [comment]
@waltermvp what version are you referring to, I tried `aws-amplify/datastore@2.0.10`

**Comment by waltermvp** [comment]
Not sure what the latest version was when I posted, but if it’s happening again try creating a fresh project then copy paste the schema and see if it works

**Comment by wei** [comment]
Hi @waltermvp , I followed your example (minor changes to make it work) at [wei/amplify-js-5161](https://github.com/wei/amplify-js-5161), it looks like I can access `table.event` but not `event.tables` because the example code did not set `event.tables = [tableSAve]`.

Is it supposed to auto link them both ways? Thanks for your insight.

**Comment by ajberasategui** [comment]
May 2021, this is still happening. Did anyone ever find a way to make it work or a workaround? Or are we forced to query model relationships by ourselves by querying each model separatedly?

Thank you in advance, any advise is welcome.
