### ISSUE TITLE
Analytics.updateEndpoint - is address required?

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-js#5162]
** Which Category is your question related to? **
Analytics
** What AWS Services are you utilizing? **
Cognito, AWS AppSync, DynamoDB.
** Provide additional details e.g. code snippets **
I want to settle this once and for all, I have seen some people say that `address` is required, some people say it is automatically inserted by Amplify.
When my user logs in to the app I am updating its endpoint using `Analytics.updateEndpoint()` with the user data, and I get an error saying that an address must be specified, and the endpoint isn't created (I'm checking endpoints for user IDs with the AWS CLI).

If the `address` field is required, can I have a solution from you that tells me how to update the endpoint one single time, with both the address and the user data? what if the user data loads before the notification token event gets registered? How do I check that? Push notifications in my app are very unstable and I don't want it to be that way

**Comment by idanlo** [comment]
@manueliglesias Can I get an update? My notification service is pretty much broken

**Comment by harrysolovay** [comment]
You can grab a unique identifier from the response of `currentUserPoolUser`, and then include it as the `address` when calling `updateEndpoint` (with `attributes`). [See here](https://docs.amplify.aws/lib/analytics/getting-started/q/platform/js#update-your-iam-policy).

**Comment by idanlo** [comment]
@harrysolovay how is that an answer? And why did you close the issue? If I set some random string as the address then I will not get push notifications because pinpoint will not have the device's push notification token.

Also you didn't answer my question - is Amplify automatically doing the updateEndpoint with the address or no?
