### ISSUE TITLE
As a new user is signing up, how can i check Unique username? HELP needed!!!!!!

### ISSUE THREAD

**Issue by chai86** [aws-amplify/amplify-js#5163]
Hi, 

I'm using Auth.signUp() in my react native app. I would ideally like a way to check that the username that has been entered (and corresponding email address ideally), are unique and that no one else in the cognito pool already has those. 

If successful, continue sign up, else choose another username.

How can i achieve this?

**Comment by Klastic** [comment]
> I'm using Auth.signUp() in my react native app. I would ideally like a way to check that the username that has been entered (and corresponding email address ideally), are unique and that no one else in the cognito pool already has those.

Hey @chai86,

Here is one way to go about checking usernames.

First make sure you have Username selected as your sign in method for the userpool.
![image](https://user-images.githubusercontent.com/11662370/77473892-293c2500-6de4-11ea-9e49-20e49fb5b1af.png)

I assume if you also check "Also allow sign in with verified email address" that this method will work for email as well, however, I have not tested it myself.

When you make your call to Auth.signUp() you will need to handle your errors as this is where you will check to see if the account is already taken up.

`
Auth.signUp().catch(err => console.log(err.message))
`

If the user is already created you will get an error like
![image](https://user-images.githubusercontent.com/11662370/77473659-c9de1500-6de3-11ea-885a-5bc2bbe984d9.png)

Here is how is a basic example. 

```
import React, { useState } from "react";
import {View, Text, Button, TextInput} from "react-native";
import Auth from "@aws-amplify/auth";

export default () => {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [passwordConfirm, setPasswordConfirm] = useState("");
  const [errorMessage, setErrorMessage] = useState("");

  const SignUp = () => {
    try {
      // Do some validation
      // VALIDATION FUNC HERE

      // Try to sign your user up
      Auth.signUp();

      // If successful route to your next screen.
      // ROUTE FUNC HERE
    } catch (err) {
      //If auth failed
      setErrorMessage(err.message);
    }
  };

  return (
    <View>
      <TextInput
        placeholder={"Username"}
        value={username}
        onChangeText={text => setUsername(text)}
      />
      <TextInput
        placeholder={"Password"}
        value={password}
        onChangeText={text => setPassword(text)}
      />
      <TextInput
        placeholder={"Password"}
        value={passwordConfirm}
        onChangeText={text => setPasswordConfirm(text)}
      />

      {errorMessage && (
        <View>
          <Text>{errorMessage}</Text>
        </View>
      )}

      <Button
        disabled={!username || !password || !passwordConfirm}
        type="clear"
        onPress={() => SignUp()}
        title={"Sign Up"}
      />
    </View>
  );
};
```

In this example the user will have to enter their username and password and then click on the sign up button. If the username is taken an error message will be displayed to the user.

hope that helps 😁
