### ISSUE TITLE
Datastore - npm run amplify-modelgen not working for non @model types

### ISSUE THREAD

**Issue by rpostulart** [aws-amplify/amplify-js#5178]
I have this schema

`
type Quiz @model @auth(rules: [{ allow: public, provider: iam }]) {
  id: ID!
  title: String!
  subscribers: [Subscribers] @connection(name: "QuizSubscribers")
  resonses: [Responses] @connection(name: "QuizResponses")
  questions: [Questions] @connection(name: "QuizQuestions")
  seconds: Int!
  started: Boolean!
}

type Questions @model @auth(rules: [{ allow: public, provider: iam }]) {
  id: ID!
  quiz: Quiz @connection(name: "QuizQuestions")
  question: String!
  answers: [Answers]
  resonses: [Responses] @connection(name: "QuestionResponses")
}

type Answers {
  answer: String!
  status: Boolean
}

type Subscribers @model @auth(rules: [{ allow: public, provider: iam }]) {
  id: ID!
  quiz: Quiz @connection(name: "QuizSubscribers")
  name: String!
  score: Int!
  responses: [Responses] @connection(name: "SubscriberResponses")
}

type Responses @model @auth(rules: [{ allow: public, provider: iam }]) {
  id: ID!
  quiz: Quiz @connection(name: "QuizResponses")
  time: String!
  question: Questions @connection(name: "QuestionResponses")
  subscriber: Subscribers @connection(name: "SubscriberResponses")
}

`

but 
`
npm run amplify-modelgen
`

is not working. I get this error:

Unknown type Answers for field answers. Did you forget to add the @model directive

But I don't want to make a seperate table for it

**Comment by egoossens** [comment]
See https://github.com/aws-amplify/amplify-cli/issues/2988#issuecomment-601499881.
Hopefully they'll release the feature soon, as I'm also unable to use DataStore without it.

**Comment by undefobj** [comment]
Yes the other issue's related PR has been merged and we are working on a release both of the JS library and CLI. Can we close this issue or is there a separate problem?
