### ISSUE TITLE
AppSync graphql query filter for nulls on nullable string type

### ISSUE THREAD

**Issue by ambriglia** [aws-amplify/amplify-js#5179]
Given this AppSync model...
`type Animal @model  {
  id: ID!
  name: String
}
`
And this graphql query...
`query MyQuery {
  listAnimals (filter: {name: {eq: null}}) {
    items {
      id
     name
    }
  }
}
`
I expect to only return the animals that do not have a name. However, everytime I run this query, nothing is returned. Does the eq filter not work with a null check for nullable string types? Regardless, how can I accomplish this seemingly simple query via graphql?

**Comment by ashika01** [comment]
@ambriglia This might be a service restriction. Have you reached out to the [Appsync forum](https://forums.aws.amazon.com/forum.jspa?forumID=280&start=0)

**Comment by mkwatson** [comment]
@ambriglia did you ever figure this out? I'm also having this problem

**Comment by ambriglia** [comment]
@mkwatson it sounds like we would need to create our own custom resolvers. Amplify does not offer this type of query out of the box. I have not actually tested it out though.

**Comment by IsaacTrevino** [comment]
My suggestion is canceling out the filter all together, especially if your using a type `enum` for `name`

```javascript
query MyQuery { 
  listAnimals (
    filter: currentFilter === 'nullFilter' ? undefined : {
      name: {
        eq: 'someFilter'
      }
    }
  ) {
      items {
        id name 
     } 
  } 
}
```

**Comment by aprilmintacpineda** [comment]
I encountered this and found a work around, instead of doing `eq: null`, do `exists: false`, like so:

```graphql
{
  searchDocuments (
    filter: {
      someNullableValue: {
        exists: false
      }
    }
  ) {
    items {
      id
     someNullableValue
    }
  }
}
```

I haven't had a chance to test if this will return something else other than `someNullableValue` being null.

**Comment by chrisbonifacio** [comment]
> I encountered this and found a work around, instead of doing `eq: null`, do `exists: false`, like so:
> 
> 
> 
> ```graphql
> 
> {
> 
>   searchDocuments (
> 
>     filter: {
> 
>       someNullableValue: {
> 
>         exists: false
> 
>       }
> 
>     }
> 
>   ) {
> 
>     items {
> 
>       id
> 
>      someNullableValue
> 
>     }
> 
>   }
> 
> }
> 
> ```
> 
> 
> 
> I haven't had a chance to test if this will return something else other than `someNullableValue` being null.

This only works with @searchable directive which is not compatible with @connection.

**Comment by dpilch** [comment]
This will work without `@searchable` as well. Although it is `attributeExists` instead of `exists`.


Here is an example with a list query.

```
{
  listDocuments (
    filter: {
      someOptionalField: {
        attributeExists: false
      }
    }
  ) {
    items {
      id
      someOptionalField
    }
  }
}
