### ISSUE TITLE
aws-amplify Storage.get() and S3Image components should allow access for public files in buckets

### ISSUE THREAD

**Issue by mwarger** [aws-amplify/amplify-js#518]
Do you want to request a feature or report a bug?
Featurebug

What is the current behavior?
Storage.get() attempts to ensure there are credentials for getting objects from a bucket.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.
I will work on a demo when I can...

What is the expected behavior?
Would like for amplify to allow the option of allowing for gets from buckets that are public without checking for credentials.  Would suggest maybe a `public` flag to bypass creds check.  The same could also be said for the S3Image component in aws-amplify-react (this seems to exhibit the same behavior, except this fails silently).  I'm assuming this uses Storage.get() behind the scenes and doesn't surface the error to the user.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
Latest version of Amplify.

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by mwarger** [comment]
I'm also looking into this - would be happy to help and submit a PR.

**Comment by mwarger** [comment]
After a bit more research, it seems there may be a more fundamental issue with the S3 SDK.  It appears as if it might be necessary for S3 instance to have credentials.  If this is true, then there may not be a way to implement what I want.  Would love some input from someone who has more experience with the underlying aws-sdk.

**Comment by mlabieniec** [comment]
Hi @mwarger thanks for the detail here. Yes, I believe you are correct in that the low level sdk will require credentials for ***all*** calls made to aws...I think what we could do here though is provide some sort of flag or similar that basically turns this into a standard `fetch` request. We will look into this as a feature i.e. bypassing credentials / sdk for public calls basically.

**Comment by SokichiFujita** [comment]
I also hope that `Storage.put()` with `level:public` option sets actual public ACL to the file. Using `Storage.get()` to get the file URL causes slow file fetching and increases unnecessary complexity of frontend development.

**Comment by AndreasEK** [comment]
I'd like to see that too. Also, dear bot, don't close this issue :)

**Comment by jimmyn** [comment]
This is a very important feature for me as well

**Comment by SokichiFujita** [comment]
@jordanranz @mwarger Is there any progress of both this issue and #659? It seems that @nidsharm who assigned to this issue doesn't have an activity on GitHub. I'm worried about the future of this issue.

**Comment by Zerquix18** [comment]
Currently the only workaround to this is removing the sign from the URL?

**Comment by GeorgeBellTMH** [comment]
https://github.com/aws-amplify/amplify-js/issues/960

This is now possible - just use {acl:"public-read"} - change your parameters.json file to include s3:PutObjectAcl on the appropriate permissions, and in s3-cloudformation-template.json as necessary...then when you do Storage.get you can just remove everything after the ? and the url should work...

**Comment by AakashPat** [comment]
> #960
> 
> This is now possible - just use {acl:"public-read"} - change your parameters.json file to include s3:PutObjectAcl on the appropriate permissions, and in s3-cloudformation-template.json as necessary...then when you do Storage.get you can just remove everything after the ? and the url should work...

This is the approach that I have taken. I had already gotten my files uploaded with acl set to public-read. I was only concerned about the Storage.get function returning a pre-signed URL that was valid for a specific period of time. I needed the file to accessbile publicly forever. So I'm now splitting the returned URL over the '?' character.

**Comment by sw-yx** [comment]
@sammartinez  it reads like  this issue has been resolved with the `level:public` option?

**Comment by sammartinez** [comment]
Correct @sw-yx, This feature is now resolved with the above. Resolving

**Comment by AzherAleem** [comment]
> roach that I have taken. I had a



> #960
> 
> This is now possible - just use {acl:"public-read"} - change your parameters.json file to include s3:PutObjectAcl on the appropriate permissions, and in s3-cloudformation-template.json as necessary...then when you do Storage.get you can just remove everything after the ? and the url should work...

@GeorgeBellTMH I came across this issue. I have an amplify app set up in React JS and I have created an s3 bucket via AWS amplify cli and granted create/update, read, delete access to authenticated users and read access to guest users. I am uploading videos and images in a protected folder per user. However, i want only the image files to be publically accessible thus I pass acl:public-read in the Storage.put but it gives me a 403. Can you point out what to add in the s3 cloud formation script to allow this?
My parameter.json currently looks like this: 
```

{
    "bucketName": "ott-media-bucket",
    "authPolicyName": "s3_amplify_85e86836",
    "unauthPolicyName": "s3_amplify_85e86836",
    "authRoleName": {
        "Ref": "AuthRoleName"
    },
    "unauthRoleName": {
        "Ref": "UnauthRoleName"
    },
    "selectedGuestPermissions": [
        "s3:GetObject",
        "s3:ListBucket"
    ],
    "selectedAuthenticatedPermissions": [
        "s3:PutObject",
        "s3:GetObject",
        "s3:ListBucket",
        "s3:DeleteObject"
    ],
    "s3PermissionsAuthenticatedPublic": "s3:PutObject,s3:GetObject,s3:DeleteObject",
    "s3PublicPolicy": "Public_policy_17e358cd",
    "s3PermissionsAuthenticatedUploads": "s3:PutObject",
    "s3UploadsPolicy": "Uploads_policy_17e358cd",
    "s3PermissionsAuthenticatedProtected": "s3:PutObject,s3:GetObject,s3:DeleteObject",
    "s3ProtectedPolicy": "Protected_policy_d3c599df",
    "s3PermissionsAuthenticatedPrivate": "s3:PutObject,s3:GetObject,s3:DeleteObject",
    "s3PrivatePolicy": "Private_policy_d3c599df",
    "AuthenticatedAllowList": "ALLOW",
    "s3ReadPolicy": "read_policy_17e358cd",
    "s3PermissionsGuestPublic": "s3:GetObject",
    "s3PermissionsGuestUploads": "DISALLOW",
    "GuestAllowList": "ALLOW",
    "triggerFunction": "NONE"
}
```
