### ISSUE TITLE
Attempt to call AWS.CognitoIdentityCredentials results in error

### ISSUE THREAD

**Issue by Thomazella** [aws-amplify/amplify-js#5193]
** Which Category is your question related to? **
aws-sdk/global/CognitoIdentityCredentials

** What AWS Services are you utilizing? **
Cognito, appsync
** Provide additional details e.g. code snippets **
I want to set the config object to then call `AWS.config.credentials.refresh()` use case 4 in readMe here: https://github.com/aws-amplify/amplify-js/blob/master/packages/amazon-cognito-identity-js/README.md
```typescript
            AWS.config.credentials = new AWS.CognitoIdentityCredentials({
              IdentityPoolId: 'us-east-1:930292469738:userpool/us-east-1_8kOblFjg6', // your identity pool id here
              Logins: {
                // Change the key below according to the specific region your user pool is in.
                'cognito-idp.us-east-1.amazonaws.com/us-east-1_8kOblFjg6': result.getIdToken().getJwtToken(),
              },
            })
```
It seems I can't make a regex on the identityPoolId value happy. I've tried:
`us-east-1:930292469738` which passes regex but is not found
`us-east-1_8kOblFjg6` the more obvious value, but also fails at regex
`us-east-1:930292469738:userpool/us-east-1_8kOblFjg6` value above.

error:
![Screen Shot 2020-03-25 at 9 26 01 PM](https://user-images.githubusercontent.com/15015324/77598384-6be32780-6ee0-11ea-8681-64e297c723fa.png)

**Comment by amhinson** [comment]
@Thomazella Were you able to get your issue resolved? It looks like you might just be using the wrong ID for the Identity Pool. It should look something like this: `us-west-2:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`

**Comment by Thomazella** [comment]
I got it resolved, id was wrong as you described. :+1:
