### ISSUE TITLE
Unable to change :hover and :focus effects on theme

### ISSUE THREAD

**Issue by bearsworth** [aws-amplify/amplify-js#5195]
I'm attempting to do this from react, but I'm having an issue with getting the `:hover` or `:focus` effect to work on a button. Everything works so far, but for some reason I can't quite get the syntax for this. I'm implementing my own theme using `<Authenticator theme={MyTheme} />`. Inside that theme here is the button object. 

```jsx button: { 
    backgroundColor: DARK_COLOR, 
    borderColor: DARK_COLOR,
    borderRadius: '.15rem',
    '&:hover': {
      outline: 0,
      boxShadow: '0 0 0 4px #ffffff, 0 0 0 5px #717171, 0 0 0 6px rgba(255,255,255,0.5) !important',
      filter: 'brightness(1.25)'
    },
  },
```

I put quotes around '&:hover' so that it would work with React. It crashes without them. I have tried multiple other things, but I'm running out of ideas. I also noticed that the Amplify theme uses the defaults provided by the browser for the effects here.

**Comment by manueliglesias** [comment]
Hi @bearsworth 

Looks like it is not possible to specify pseudo-classes with the `style` prop in JSX, you can explore using a stylesheet that targets `.button:hover` or take a look at some of these suggestions in SO:

https://stackoverflow.com/questions/28365233/inline-css-styles-in-react-how-to-implement-ahover

Hope this helps!
