### ISSUE TITLE
UI Components: session not persisted after sign up

### ISSUE THREAD

**Issue by amhinson** [aws-amplify/amplify-js#5201]
**Describe the bug**
When using the new `<amplify-authenticator>` in Vue, after I sign up and enter the confirmation code I can see in the browser that I am automatically signed in. However, after refreshing the page, the auth session didn't persist and I see the sign in screen. Once a sign in again and refresh the page, the session is persisted.

**To Reproduce**

1. Follow [quick start](https://github.com/aws-amplify/amplify-js/tree/ui-components/master/packages/amplify-ui-components#quick-start) setup steps and [Vue usage](https://github.com/aws-amplify/amplify-js/tree/ui-components/master/packages/amplify-ui-components#vue)
2. Click "Create Account" and enter in info. 
3. Enter confirmation code and click "Confirm"
4. See user as "signed in"
5. Refresh page
6. See login screen again

**Expected behavior**
User stays signed in after sign up confirmation.

<details>
  <summary><strong>Environment</strong></summary>

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 592.36 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.18.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 68.5.0
    Safari: 13.1
  npmPackages:
    @aws-amplify/ui-vue: ^0.0.2-ui-preview.5545 => 0.0.2-ui-preview.5545+6aae9f44 
    @vue/cli-plugin-babel: ~4.2.0 => 4.2.3 
    @vue/cli-plugin-eslint: ~4.2.0 => 4.2.3 
    @vue/cli-service: ~4.2.0 => 4.2.3 
    aws-amplify: ^1.3.1-ui-preview.40 => 1.3.1-ui-preview.40+6aae9f44 
    babel-eslint: ^10.0.3 => 10.1.0 
    core-js: ^3.6.4 => 3.6.4 
    eslint: ^6.7.2 => 6.8.0 
    eslint-plugin-vue: ^6.1.2 => 6.2.2 
    vue: ^2.6.11 => 2.6.11 
    vue-template-compiler: ^2.6.11 => 2.6.11 
  npmGlobalPackages:
    @aws-amplify/cli: 4.16.1
    @vue/cli: 4.2.3
    detox-cli: 10.0.7
    expo-cli: 3.15.4
    lighthouse: 5.6.0
    n: 6.1.3
    npm: 6.13.4
    serve: 11.3.0
```

</details>

**Smartphone (please complete the following information):**

- Device: MacBook Pro
- OS: OSX 10.14.6
- Browser: Chrome
- Version: 80.0.3987.149

**Comment by ashika01** [comment]
This is happening on all framework.

**Comment by amhinson** [comment]
Resolved with https://github.com/aws-amplify/amplify-js/pull/5236
