### ISSUE TITLE
Amplify datastore is not supporting multitenant

### ISSUE THREAD

**Issue by rpostulart** [aws-amplify/amplify-js#5222]
The observe is listening to all model data, but it is not possible to only listen to specific data on the model and then apply specific queries and filters on that data.

**Comment by rpostulart** [comment]
So something like this:

const subscription = DataStore.observe(Post, 123).subscribe(msg => {
  console.log(msg.model, msg.opType, msg.element);
});

So we only listen to Posts with id 123

**Comment by rpostulart** [comment]
A better requirement description: tell datastore to only get data  locally from a certain model with a certain ID

**Comment by undefobj** [comment]
Could you give more specific information about the use case?

**Comment by rpostulart** [comment]
I have this schema. The idea is to build an online quiz. 
So an admin can create the quiz and send the gamecode to those who want to subscribe. Based on that gamecode they log in and see to quiz data.

But if you look in de localstorage you see all the quiz data and questions

`
type Quiz @model @auth(rules: [{ allow: public, provider: iam }]) {
  id: ID!
  title: String!
  subscribers: [Subscribers] @connection(name: "QuizSubscribers")
  seconds: Int!
  currentQuestion: String
  questionOrder: String
  started: Boolean
  view: Int
  owner: String!
}

type Questions @model @auth(rules: [{ allow: public, provider: iam }]) {
  id: ID!
  image: String
  youtube: String
  question: String!
  answerOne: String
  answerOneCorrect: Boolean
  answerTwo: String
  answerTwoCorrect: Boolean
  answerThree: String
  answerThreeCorrect: Boolean
  answerFour: String
  answerFourCorrect: Boolean
  quizID: String!
  order: Int
  public: Boolean
  category: String
}
type QuestionsDB @model @auth(rules: [{ allow: public, provider: iam }]) {
  id: ID!
  image: String
  youtube: String
  question: String!
  answerOne: String
  answerOneCorrect: Boolean
  answerTwo: String
  answerTwoCorrect: Boolean
  answerThree: String
  answerThreeCorrect: Boolean
  answerFour: String
  answerFourCorrect: Boolean
  relatedQuestion: String!
  public: Boolean
  category: String
  language: String
}

type Subscribers @model @auth(rules: [{ allow: public, provider: iam }]) {
  id: ID!
  type: String!
  score: Int!
  quizID: String!
  quiz: Quiz @connection(name: "QuizSubscribers")
  name: String!
}

type Responses @model @auth(rules: [{ allow: public, provider: iam }]) {
  id: ID!
  quiz: String!
  subscriber: String!
  question: String!
}
type Languages
  @model
  @auth(rules: [{ allow: public, provider: iam }])
  @key(name: "ByCode", fields: ["type", "code"], queryField: "getLangByCode") {
  id: ID!
  type: String!
  code: String!
}

`

**Comment by undefobj** [comment]
It is possible to observe one object like so:

```javascript
const id = '69ddcb63-7e4a-4325-b84d-8592e6dac07b';

const subscription = DataStore.observe(Event, id).subscribe(msg => {
  console.log(msg.model, msg.opType, msg.element);
  onQuery();
});
```

This also came up here: https://github.com/aws-amplify/amplify-js/issues/5156
I'm adding a note internally to get this added to our docs. Additionally we have a feature we're working on related to the sync and filter functionality so that you can apply finer grained controls to the base query functionality. You can track that here: https://github.com/aws-amplify/amplify-js/issues/5119

**Comment by rpostulart** [comment]
Ok cool, so then only that data will be locally in the store and not the other data. Thx

**Comment by rpostulart** [comment]
Is tracked here: https://github.com/aws-amplify/amplify-js/issues/5119

**Comment by rpostulart** [comment]
When I trigger this on a page load:

  const id = "71192197-67f4-4e2d-9569-bbfd67085253"
    const subscription = await DataStore.observe(Quiz, id).subscribe(msg => {
      console.log(msg.model, msg.opType, msg.element)
    })

It still loads all the models and data in the store

<img width="666" alt="Screenshot 2020-04-10 at 07 54 31" src="https://user-images.githubusercontent.com/21346629/78966644-a8c63580-7b00-11ea-8d41-3ae09892bb55.png">

**Comment by undefobj** [comment]
Observing a model is different than loading all the models. If you're looking to just load specific ones that's handled by the feature #5119

**Comment by sammartinez** [comment]
Resolving this issue in favor of the open feature request that is open
