### ISSUE TITLE
aws-ampify-react: peer dep refs non-existent major version @aws-amplify/ui ^2.0.0

### ISSUE THREAD

**Issue by helloPiers** [aws-amplify/amplify-js#5224]
The package.json peer deps for aws-amplify-react contain:
https://github.com/aws-amplify/amplify-js/blob/d630c34f3132ef38ebacc27bb5cb49d2733e4010/packages/aws-amplify-react/package.json#L104

npmjs knows nothing of such a version. I was only able to find this obscure thing https://libraries.io/npm/@aws-amplify%2Fui/2.0.0-preview.1

**Comment by helloPiers** [comment]
Leads to unresolvable WARN messages like 
>npm WARN aws-amplify-react@3.1.8 requires a peer of @aws-amplify/ui@^2.0.0 but none is installed. You must install peer dependencies yourself.

Which lead to a lack of confidence in the project 😞.

**Comment by Amplifiyer** [comment]
@helloPiers thanks for catching this. The warning is not critical, since there is an obvious wrong version in the library's peer dependency which is unmet-able. If you can confirm that you are using 1.x version of @aws-amplify/ui that would be sufficient to know you are using the right version. I'll fix the dependency in library.

**Comment by sammartinez** [comment]
@helloPiers Can you confirm the above statement of @Amplifiyer ?

**Comment by helloPiers** [comment]
Oh, I didn't take "if you can confirm" to mean on this ticket ☺. Yep, I'm using a 1.0 version - as that's the only version (the entire point of this issue) ☺.

**Comment by helloPiers** [comment]
Actually, I'll leave open until it's fixed in aws-amplify-react 3.1 branch. Or should I move to v4?

**Comment by helloPiers** [comment]
I see there are now v2 versions of @aws-amplify/ui, so the specific issue of this ticket is resolved. 

The changelog https://github.com/aws-amplify/amplify-js/blob/release/packages/amplify-ui/CHANGELOG.md doesn't really justify the "major" version bump, but I guess this is part of a (welcome) rationalising of the version numbering across this project.
