### ISSUE TITLE
CognitoUser.refreshSession to update token manually

### ISSUE THREAD

**Issue by 129emma** [aws-amplify/amplify-js#5229]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
aws-amplify: 2.2.6

Hi there, I'm trying to refresh tokens especially idToken after update user attributes by calling `Auth.updateUserAttributes`. 
Tried solution from [here](https://github.com/aws-amplify/amplify-js/issues/446) , something like below code. The idToken still remain the same
```
import { Auth } from 'aws-amplify';

try {
  const cognitoUser = await Auth.currentAuthenticatedUser();
  const currentSession = await Auth.currentSession();
  cognitoUser.refreshSession(currentSession.refreshToken, (err, session) => {
    console.log('session', err, session);
    const { idToken, refreshToken, accessToken } = session;
    // do whatever you want to do now :)
  });
} catch (e) {
  console.log('Unable to refresh Token', e);
}
```

**Comment by Amplifiyer** [comment]
This is related to #4396, #2534, #5043. We will be working on these related issues, until then if you are able to find a workaround that works for you from these related issues, let us know.
