### ISSUE TITLE
How to sync DataStore w/ the local DB when we're mocking the API

### ISSUE THREAD

**Issue by glauberfc** [aws-amplify/amplify-js#5230]
** Which Category is your question related to? **
DataStore

** What AWS Services are you utilizing? **
AWS AppSync and Amplify

** Provide additional details e.g. code snippets **
@aws-amplify/core: ^2.2.6
@aws-amplify/datastore: 1.1.0

Is there a way to sync DataStore w/ the local DB created when we're mocking the GraphQL API? I already added data to the local DB, but the DataStore can't get it.

**Comment by jinnkhan88** [comment]
@glauberfc did you get a solution to this?

**Comment by arminasr** [comment]
@jinnkhan88 @glauberfc did you by any chance find a solution?
By reading https://github.com/aws-amplify/amplify-cli/issues/4155 I made an impression that syncing between the local (mocked API) and datastore is not supported.
