### ISSUE TITLE
DataStore subscription with custom claims

### ISSUE THREAD

**Issue by SebSchwartz** [aws-amplify/amplify-js#5231]
**Describe the bug**
When using "owner" auth rule, the subscriptions all fails with error: **"Validation error of type MissingFieldArgument: Missing field argument clientId @ 'onCreateContact'"**

**To Reproduce**
_Here is an example of my schema entity_:
```graphql
type Contact
  @model
  @auth(
    rules: [
      { allow: owner, ownerField: "clientId", identityClaim: "custom:clientId", provider: userPools }
      { allow: private, provider: iam, operations: [read, create, update] }
    ]
  ) {
  id: ID!
  firstName: String
  lastName: String
  email: String

  clientId: String
}
```
_What the network send as request (in the websocket)_: (payload.data)
`{"query":"subscription operation {\n  onCreateContact {\n    id\n    firstName\n    lastName\n    email\n    clientId\n    _version\n    _lastChangedAt\n    _deleted\n  }\n}\n","variables":{}}`
payload.extensions are ok with the right token.

_My amplify configuration_:
```javascript
Amplify.configure(awsExports);
Amplify.configure({
  API: {
    graphql_endpoint: awsExports.aws_appsync_graphqlEndpoint,
    graphql_region: awsExports.aws_appsync_region,
    graphql_authenticationType: awsExports.aws_appsync_authenticationType,
    aws_appsync_graphqlEndpoint: awsExports.aws_appsync_graphqlEndpoint,
    aws_appsync_region: awsExports.aws_appsync_region,
    aws_appsync_authenticationType: awsExports.aws_appsync_authenticationType,

    graphql_headers: async () => {
      const session = await Auth.currentSession();
      return {
        Authorization: session.getIdToken().getJwtToken(),
        'My-Custom-Header': 'my value',
      };
    },
  },
});

```
The value is present in my id token and the authorization header passed in the websocket is the right one.
_The generated schema.graphql file is giving this for the subscription_:
```graphql
onCreateContact(clientId: String!): Contact @aws_subscribe(mutations: ["createContact"]) @aws_iam @aws_cognito_user_pools
```
So in the request made in the websocket, the clientId is missing.
I supposed this could be something with the getAuthorizationInfo method here:
https://github.com/aws-amplify/amplify-js/blob/master/packages/datastore/src/sync/processors/subscription.ts#L80
As it will return when finding the private iam provider but I also tried without it and I still got the error.

**Expected behavior**
It should work and clientId should be passed in the subscription query.

**Screenshots**
<details>
  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 530.39 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 62.0
    Safari: 13.0.5
  npmPackages:
    aws-amplify: ^2.2.7 => 2.2.7 
    aws-amplify-react: ^3.1.8 => 3.1.8 
    aws-appsync: ^3.0.2 => 3.0.2 
    aws-appsync-react: ^3.0.2 => 3.0.2 
    aws-sdk: ^2.647.0 => 2.647.0 
  npmGlobalPackages:
    @aws-amplify/cli: 4.17.2
    aws-appsync-codegen: 0.17.5
    npm: 6.13.4
    yarn: 1.9.4

</details>

**Comment by SebSchwartz** [comment]
Any news on that @sammartinez ?
Thanks,
Sebastien

**Comment by sammartinez** [comment]
@SebSchwartz Apologizes for not following up sooner, I am marking this as a feature request as we as we use the accessToken within DataStore instead of your implementation looks to be using the idToken

**Comment by SebSchwartz** [comment]
@sammartinez  Yes but why it's not taking the idToken as i'm passing it through the auth header and in the message sent via the websocket, this idToken is well sent?
When checking the code (getAuthorizationInfo function), it's returning the information with the other auth rule first and it's never going to this rule with the custom claims. Maybe there should be a new priority param involved to resolve this or a new field telling which field we want in the subscription?

**Comment by BarbaraPruz** [comment]
I am running into similar problem. I thought this was possible user error and so I tried to start a discussion thread [https://github.com/aws-amplify/amplify-js/discussions/6067](https://github.com/aws-amplify/amplify-js/discussions/6067) which has some details and background.
Let me know if other information would be helpful. I'm also open to other approaches to meeting my requirements. 
Note: at the moment, we restored our schema to a previous working version, but I'm happy to put this broken one back and to try more things.

**Comment by amhinson** [comment]
@SebSchwartz We've recently made some updates around `@auth` in `aws-amplify` as well as the CLI that should fix the issue you are seeing. Could you try updating to the latest version of both the JS library and the CLI and see if you're still seeing the same behavior?

You will also need to run `amplify model codegen` and `amplify push` before testing the changes.

**Comment by amin79** [comment]
I have the same problem. Is there any workaround?

@auth(
    rules: [
      { allow: owner, identityClaim: "custom:classID" }      
    ]
  )
