### ISSUE TITLE
Problems to mock Amplify locally

### ISSUE THREAD

**Issue by glauberfc** [aws-amplify/amplify-js#5241]
**Which Category is your question related to?**
API

**What AWS Services are you utilizing?**
AWS AppSync

**Provide additional details e.g. code snippets**
@aws-amplify/core: ^2.2.6
aws-amplify: ^2.2.7

**Model:**
`type Task @model {
  id: ID!
  title: String!
  description: String
  status: String
}`
`type Note @model {
  id: ID!
  content: String!
}`

I'm w/ some problems to mock Amplify locally. I can create a new Note data, but the fields `_version` and `_lastChangedAt` are not filled automatically.

When I try to fetch this data using the automatically generated listNotes query, I receive an error: **"Cannot return null for non-nullable field `Note._lastChangedAt`"**.

To solve this, I can to try manually add the `_version` field in the input of mutation. But `_lastChangedAt` is not showed as an input property, so, I can't add it manually.

How can I solve this problem?

**Comment by dabit3** [comment]
Are you using DataStore? If so, then Mock will not work as you can just run the app locally (turn network off), and test locally. You can delete the local data in the browser but deleting any data in IndexDB in the browser when you'd like to reconnect to the back end.

**Comment by glauberfc** [comment]
@dabit3 I'm not using the DataStore. I'm adding a Note using the GraphiQL tool and trying to fetch it using the Amplify JS client with the auto generated query `listNotes`. But as the auto generated query includes the `_lastChangedAt` field, I'm getting the error message described above

**Comment by dabit3** [comment]
Also, if the GraphQL schema does not include that field, you can not query for it. Do you need a _lastChangedAt or _version value?

**Comment by glauberfc** [comment]
Ok. I was only thinking that maybe more interesting use the auto generated queries as it is always updated than write manually a query. But I'll do this. Thanks again, man!
