### ISSUE TITLE
Backed up and restored Cognito User Pool. Users are now locked into 'FORCE_CHANGE_PASSWORD' with no recovery.

### ISSUE THREAD

**Issue by michaelcuneo** [aws-amplify/amplify-js#5251]
** Which Category is your question related to? **
Cognito Auth

** What AWS Services are you utilizing? **
Cognito Auth

** Provide additional details e.g. code snippets **
I have a huge list of people in a User Pool.
I had to recreate the User Pool, so I backed everyone up, recreated the user pool, restored all of the users, and the users had no password, because obviously that side of things cannot be backed up.

It sent every single user a one time password. with a time limit imposed, and set them to FORCE_CHANGE_PASSWORD.

People who haven't responded to this within the time limit, are now locked out of their accounts, and cannot use the 'reset password' link in my `<Authenticator />` component to receive a new SMS/Email Code to recover their accounts.

E.g. Sample code, versions of Amplify you are using

**Comment by sammartinez** [comment]
@michaelcuneo This issue seems to be specific to Amazon Cognito. Can you please open up a forum issue on [Amazon Cognito AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=173) for this?

**Comment by RossWilliams** [comment]
Update your "forgot password" flow to trigger a lambda that resends a new one-time password.

here are the pseudo steps with the aws-sdk for the Cognito service:
1. List users using an email or other filter: `Filter: 'email = "' + event.email + '"'`
2. Find your user (listUsers) and see if they are in the state where you need to do something special: ` user.UserStatus !== "FORCE_CHANGE_PASSWORD"`
3. Call adminCreateUser with the values from the listUser response, and set it to resend an email: `{
    UserPoolId: process.env.AUTH_COGNITO${PROJECT_NAME}_USERPOOLID,
    Username: user.Username,
    UserAttributes: user.Attributes.filter(a => a.Name !== "sub"),
    DesiredDeliveryMediums: ["EMAIL"],
    MessageAction: "RESEND"
  }`
4. Send a response to the user that an email has been sent if they had previously created an account.

**Comment by mauerbac** [comment]
Closing from this repo as this is regarding AWS SDK for Cognito
