### ISSUE TITLE
Multiple endpoints are register for one device

### ISSUE THREAD

**Issue by alexkaduk** [aws-amplify/amplify-js#5252]
We are using Amplify and React Native for mobile application. Have configured push notifications.
Have done new installation on the device and run the application.

Download report from PinPoint (All segments). iPhone device has been register, **although several endpoints were created for iOS**. For Android device one endpoint is created.

Examples of reports

![image](https://user-images.githubusercontent.com/12643566/78102573-4f208580-73f3-11ea-8b66-d51e9c883433.png)

![image](https://user-images.githubusercontent.com/12643566/78102614-6b242700-73f3-11ea-9242-28f888a00d31.png)
 
Could this issue be fixed, please? 
We need one endpoint for the installation.

**Comment by idanlo** [comment]
+1

**Comment by amhinson** [comment]
@alexkaduk Could you post your IAM policy with the Pinpoint actions?

**Comment by alexkaduk** [comment]
@amhinson PinPoint configuration has been done based on this article https://medium.com/react-native-training/react-native-push-notifications-with-amazon-pinpoint-ios-b2efa89ced32

**Comment by amhinson** [comment]
@alexkaduk Sorry for the delay! Could you provide a code snippet of your `Analytics`/`PushNotification` usage?

**Comment by amhinson** [comment]
Hey @alexkaduk, I've been working on reproducing this issue and I just want to make sure your use-case is covered as well in the testing. Could you share your usage of `Analytics`/`PushNotification`?

**Comment by amhinson** [comment]
@alexkaduk @idanlo I'm still having some trouble replicating this issue. Are you still experiencing this behavior with the latest version of all of the Amplify libraries you're using? There have been some significant updates related to core that could have had a positive effect on this behavior you were seeing.

Also, we've recently made an update so there is no need to call `Analytics.configure()` or `PushNotification.configure()` anymore if you're already calling `Amplify.configure()`. Here's a link to the docs for [Push Notification configuration example](https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/js#configure-your-app).
