### ISSUE TITLE
Add other ways to add data to the DataStore indexDB

### ISSUE THREAD

**Issue by glauberfc** [aws-amplify/amplify-js#5257]
**Is your feature request related to a problem? Please describe.**
I'm a beginner using Amplify and I'm trying to use DataStore on my MVP project. The problem is that I want to mock a list of products only to test it locally before push my API to AppSync, but the only ways to add data to DataStore locally are: 
1. creating a screen where I can register these products using the DataStore library; 
2. creating a script to run and add products to indexDB using the DataStore library.

**Describe the solution you'd like**
I think that DataStore should have the possibility to receive data in other ways. Maybe syncing data from the local DynamoDB/SQLite when the developer is running the `amplify mock` command. In this way, the developer would add the data to mock using the GraphiQL tool and the DataStore will sync its indexDB w/ the local DB and simulate the sync between AppSync and indexDB.

Is much more easy to add the data using a tool, like GraphiQL or executing a script, than creating a UI only to add this data to the list.

**Comment by renebrandel** [comment]
Hi we have since launched a new content manager in the Amplify Studio interface. That should address this workflow in terms of this:
> Is much more easy to add the data using a tool, like GraphiQL or executing a script, than creating a UI only to add this data to the list.

Try it out and let me know if it addresses your issue. Please @-me to re-open this issue.
