### ISSUE TITLE
How can I customize the UI alone without changing any functions in aws-amlify-react-native

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#5258]
I am using aws-amplify-react-native default screen to login my app. 

Now I need to customize the screen and only need 4 screens. 

Can anyone suggest the best practice  for this and easy and simpler way to customize the UI alone.

Here I have. created custom screens alone and need to know how can I add inside the Authenticator or Shall I add it in the stackNavigator.

1. How can I make the signUp and SignIn as same as the cognito?. Here I need to use the same as it is in aws-amplify-react-native.
 So how can I handle the validations? Shall I need to custom the code for validation and entire things as custom?
2. If I create the screens and added navigation in my routes, how can I add the auth.SignIn and the validations. Shall I need to have any other Api calls to connect with my screens or can I use the same method in aws-amplify here as well?
3. For custom UI, how can I handle the user attribute as email for  dev and phone number for prod

Any samples for this.

Note: I have already used custom UI with other API calls. But here I need to change the UI alone with the same signIn, signUp, Forgot password and confirmation. 

My code imports all screens from the aws-amplify-react-native

```
class AuthScreen extends React.Component {

render(){
return(
<Authenticator errorMessage={map}
          hideDefault={true}
        >
            <SignIn />
 </Authenticator>
        )
   }
}
```

**Comment by amhinson** [comment]
Hey @nihp here are the docs for customizing your own components for Auth. Does this give you what you're looking for?

https://aws-amplify.github.io/docs/js/authentication#customize-your-own-components
