### ISSUE TITLE
Quick Question: Is there a way to manually change Authenticator Sign In/Sign Up state

### ISSUE THREAD

**Issue by xitanggg** [aws-amplify/amplify-js#5259]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Authenticator Component

** Provide additional details e.g. code snippets **
I am using the Authenticator Component `<Authenticator />` for Sign In and Sign Up. I also created a navigation bar on top of the page with "Sign In" and "Sign Up" tabs. Is there a way to change the state to the Authenticator Component in code when the tab is clicked? 

A prompt response would be much appreciate. If it doesn't have such method, I can just rewrite my own Authenticator state management logic. If it does however, I would appreciate knowing soon before I make the change.

**Comment by xitanggg** [comment]
Here is a quick workaround I thought about if you use `<Authenticator />` with your custom `SignIn`, `SignUp` components and use ReactRouter for page navigation.

In the navigation bar, when the `Sign In` tab is click, redirect user to '/signin'. And when the `Sign Up` tab is click, redirect user to '/signup'

At your route module, redirect `/signin` to `/login` (or how your path is set up for `Authenticator` component). The key is to pass the `loginState`.
```javascript
<Route exact path='/signin'>
	<Redirect
		to={{
			pathname: '/login',
			state: { loginState: 'signIn' }
		}}
	/>
</Route>
<Route exact path='/signup'>
	<Redirect
		to={{
			pathname: '/login',
			state: { loginState: 'signUp' }
		}}
	/>
</Route>
```

In your custom SignIn, SignUp compoent, the first lien of showComponent is to check if there is loginState, if so, trigger `super.changeState`.
```javascript
showComponent(theme) {
	if (history.location.state.loginState) {
		super.changeState(history.location.state.loginState);
	}
}
```

**Comment by jordanranz** [comment]
Hey @xitanggg, this is challenging to do with the `aws-amplify-react` package. We have just released a [new Authenticator UI component](https://docs.amplify.aws/ui/auth/authenticator?framework=react) that might make this a bit easier as it uses [Hub](https://docs.amplify.aws/lib/utilities/hub?platform=js) to listen for Authenticator UI events. This part of it however is not yet documented.

Can you provide a snippet of the code with `Authenticator` usage in it? I can follow up using an example with the newly released UI component.

**Comment by xitanggg** [comment]
Ok. No worries. My workaround works fine so I will use it for now then.

This usage is rather typical app usage, check out [Robinhood](robinhood.com), [LinkedIn](https://www.linkedin.com/)... Basically, you first land on a home page called landing page. Then you will have a navigation menu on top that shows you can either Sign Up or Log In. 

```javascript
<Router history={history}>
	<NavMenu />
		<Switch>
			<Route exact path='/'>
				<LandingPage/>
			</Route>
			<Route exact path='/login'>
				<Authenticator/>
			</Route>
		</Switch>
</Router>
```

**Comment by mauerbac** [comment]
Thanks for the feedback @xitanggg . I will share this with the team. Closing this question out.
