### ISSUE TITLE
Cognito Auth using custom provider, hub auth listener is never triggered

### ISSUE THREAD

**Issue by cfaure004** [aws-amplify/amplify-js#5269]
**Describe the bug**

"aws-amplify": "3.0.4"

I'm using aws-amplify to sign-in using cognito with an external auth provider (AzureAD). All the authentication process is working fine but when callback url is called (with hash params access_token,...),neither hub.listen("auth",...) or Auth.currentAuthenticatedUser() is triggered.

Do i have to parse hash params by myself and check if access_token is valid ?

Same behaviour in development and production.

According to the documentation : After being redirected back to your app, you can use the [Hub module]({%if jekyll.environment == ‘production’%}{{site.amplify.docs_baseurl}}{%endif%}/js/hub#listening-authentication-events) to detect whether the user is signed in or not.

**To Reproduce**
Using Cognito Auth with external provider Auth.federatedSignIn({ customProvider: provider });
Configure hub listener in componentDidMount

**Expected behavior**
Should retrieve sign-in user automatically

**Device :**

- Device: MacBook Pro
- Browse: Chrome
- Version: Version 80.0.3987.149 (Build officiel) (64 bits)

**Sample code**
https://docs.amplify.aws/lib/auth/social?platform=js#refreshing-jwt-tokens

Same as the docs

**Comment by Amplifiyer** [comment]
@cfaure004 did this problem start appearing after amplify version upgrade or was it happening with amplify version 2 as well? I've tested hub events with default auth provider and the events seem to be working fine there

**Comment by cfaure004** [comment]
@Amplifiyer i just downgraded to version 2.2.6 and no hub event is trigger (on auth channel) after being redirect with callback url (including access_token in hash params). So it's happening on both versions.

Did you tried using a custom provider ? 

Actually it's really strange because if i trigger again microsoft authentication (after the first attempt), hub event "signIn" in "auth" channel is sometimes triggered, but often not..

**Comment by Amplifiyer** [comment]
my guess is its because of the component's lifecycle. Basically the parsingCallbackUrl is the very first event that is fired and by that time your app's component may not have mounted. Can you try moving the hub listener into the constructor of your app?
Can you also just listen to every auth event and post it here?

**Comment by cfaure004** [comment]
@Amplifiyer i'm using Next.Js. I moved my hub listener initialization in _app.js (in componentDidMount and even add a cleanup function Hub.remove("auth", listener) in componentWillUnMount) but still no event in called.

On the file attached, you can see parsingCallbackUrl and configured events are trigger when Auth.federatedSignIn({ customProvier: .... }) is called. After being redirect on callback url, no other event is called.

[
![Capture d’écran 2020-04-03 à 08 20 16](https://user-images.githubusercontent.com/23209488/78330432-3b585900-7584-11ea-8469-2577e9284d7a.png)
](url)

**Comment by cfaure004** [comment]
Hello @Amplifiyer  ! 
I guess i figured it out. I was initializing oauth not at initial amplify configuration. I moved oauth setup in global amplify setup and it's now working properly.
Thank you !
