### ISSUE TITLE
Mobsf Report: Insecure Random Number Generator. 

### ISSUE THREAD

**Issue by vikas5914** [aws-amplify/amplify-js#5272]
Recently we ran a security scanner (MobSF) on our application and got an error regarding insecure random number on the following line:

https://github.com/aws-amplify/amplify-js/blob/b82c5119ce231f44ba97a81d788546c3f50b6b5a/packages/pushnotification/android/src/main/java/com/amazonaws/amplify/pushnotification/RNPushNotificationMessagingService.java#L110

CVSS V2: 7.5 (high)
CWE: CWE-330 - Use of Insufficiently Random Values
OWASP Top 10: M5: Insufficient Cryptography
OWASP MASVS: MSTG-CRYPTO-6 

Can you please advice on how to fix this?

**Comment by amhinson** [comment]
@vikas5914 Seems like we could replace that with [SecureRandom](https://docs.oracle.com/javase/7/docs/api/java/security/SecureRandom.html) and potentially resolve that issue. Would you be able to make the following changes to that file in your node_modules and see if the error goes away?

```diff
// line 34
- import java.util.Random;
+ import java.security.SecureRandom;

// line 110
- Random randomNumberGenerator = new Random(System.currentTimeMillis());
+ Random randomNumberGenerator = new SecureRandom(System.currentTimeMillis());
```

**Comment by vikas5914** [comment]
@amhinson We got error when using `System.currentTimeMillis()` for the seed. 

So we removed it and its worked. 
Final code : 

`SecureRandom randomNumberGenerator = new SecureRandom()`

**Comment by mauerbac** [comment]
HI @vikas5914 - looks like that is working for you, so will close out. Let me know if you need further help.

**Comment by vikas5914** [comment]
@mauerbac will you accept the pull request for this?

**Comment by mauerbac** [comment]
do you have a link to the PR @vikas5914 ?

**Comment by vikas5914** [comment]
@mauerbac https://github.com/aws-amplify/amplify-js/pull/5418

**Comment by mauerbac** [comment]
Yes @vikas5914 - the team is on it!
