### ISSUE TITLE
IdentityId undefined

### ISSUE THREAD

**Issue by anarerdene** [aws-amplify/amplify-js#5275]
**Describe the bug**
IdentityId undefined

**Expected behavior**
Im using identity id of my guest user. After update amplify 3.0.4 identity id not working properly.

```
 Auth.currentCredentials()
      .then(data => setIdentity(data.identityId))
      .catch(err => console.log(err));
```
![image](https://user-images.githubusercontent.com/2210568/78282120-59a36200-754e-11ea-8d82-4bbd25a5d594.png)

sometimes identity is ok.

**Comment by sammartinez** [comment]
@anarerdene Can you provide us more information on your environment? Or a code snippet ? Thanks ahead of time

**Comment by anarerdene** [comment]
@sammartinez 

i think Auth.currentCredentials() is bugged. First time "identityId" received ok like 

```
accessKeyId: "-----------------------"
secretAccessKey: "-----------------------"
sessionToken: "-----------------------"
expiration: Fri Apr 03 2020 03:17:12 GMT+0800 (Singapore Standard Time) {}
identityId: "eu-central-1:45261a38-ca14-405e-9023-48bbdef90db0"
authenticated: false
``` 

and when i refresh page "identityId" is gone like:

```
accessKeyId: "-----------------------"
secretAccessKey: "-----------------------"
sessionToken: "-----------------------"
expiration: Fri Apr 03 2020 03:17:12 GMT+0800 (Singapore Standard Time) {}
authenticated: false
```

**Comment by mllrmat** [comment]
I am still seeing this in ReactNative with the latest version, does RN need a special fix?

**Comment by bernhardt1** [comment]
@sammartinez I'm also seeing this in the latest version on React Native.

I've relied on the identityId to map users in my dynamoDB user table. With the identityId removed in the new update, I'm unable to map users in the same way. 

Can you provide guidance on a fix for RN?

@mllrmat Did you find a solution?

**Comment by mllrmat** [comment]
@bernhardt1 sorry for the late reply. Downgraded to the latest 2.x version again, and planing the migration away from cognito.
