### ISSUE TITLE
ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by ajatakia** [aws-amplify/amplify-js#5282]
**Describe the bug**
SIM Reference: https://t.corp.amazon.com/amplify-889
Integrated aws-amplify sdk to a react project that was created using create-react-app package.
Below are the webpack, amplify and babel core versions in the app. Webpack config is the one that gets generated with create-react-app package.
"webpack": "4.41.0",
"aws-amplify": "^3.0.4",
"@babel/core": "7.6.0",

When I run the app it throws below error:

ReferenceError: exports is not defined

Module../node_modules/@aws-amplify/api-graphql/node_modules/graphql/error/GraphQLError.mjs
https://dev.audible.com:10201/static/js/0.chunk.js:36005:23
__webpack_require__
src/AudibleNextGen/apps/electron/webpack/bootstrap:785
  782 | };
  783 | 
  784 | // Execute the module function
> 785 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  786 | 
  787 | // Flag the module as loaded
  788 | module.l = true;

**To Reproduce**
Code cannot be shared. 

-- or --

Link to sample code

**Expected behavior**

**Screenshots**

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

</details>

**Smartphone (please complete the following information):**

**Additional context**

**Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by ericclemmons** [comment]
`@aws-amplify/ui-react` is using the same build process as [ionic-team/stencil-ds-plugins-demo](https://github.com/ionic-team/stencil-ds-plugins-demo/blob/master/packages/component-library-react/package.json#L12)

https://github.com/aws-amplify/amplify-js/blob/2f27a6e2d002364af5c44b9f38542ce1e2c8c119/packages/amplify-ui-react/package.json#L14-L18

Instead, we should use the same build script as `aws-amplify-react`:
https://github.com/aws-amplify/amplify-js/blob/2f27a6e2d002364af5c44b9f38542ce1e2c8c119/packages/aws-amplify-react/package.json#L11-L16

**Comment by ericclemmons** [comment]
@sawyerh I'm able to reproduce your issue, but it seems to be different from what @ajatakia has raised.  I moved it here: https://github.com/aws-amplify/amplify-js/issues/5322


@ajatakia Can you share more about your setup?  I'm not able to replicate this with `create-react-app` alone, but based on your logs it looks like the target is Electron?

Is there a custom `webpack.config.js` in this project?

**Comment by Amplifiyer** [comment]
@ajatakia please provide more information about your issue so we can reproduce it or provide a small repro app.

**Comment by pankaj-crypto** [comment]
Facing the same problem.. Any solution to this?

**Comment by ericclemmons** [comment]
@pankaj-crypto Can you open an issue with code/steps to reproduce?
