### ISSUE TITLE
Mobsf Report: Service is not Protected. An intent-filter exists.

### ISSUE THREAD

**Issue by vikas5914** [aws-amplify/amplify-js#5283]
Continue of the #5272 

We are getting following security with high SEVERITY: activate to sort column descending: "A Service is found to be shared with other apps on the device, therefore, leaving it accessible to any other application on the device. The presence of intent-filter indicates that the Service is explicitly exported." 

Services: 
	1. com.amazonaws.amplify.pushnotification.RNPushNotificationDeviceIDService
	2. com.amazonaws.amplify.pushnotification.RNPushNotificationMessagingService

![image](https://user-images.githubusercontent.com/7912297/78329772-28ec1880-75a0-11ea-8cda-9c7631cde972.png)

**Comment by amhinson** [comment]
@vikas5914 After looking at the [Cloud Messaging docs](https://firebase.google.com/docs/cloud-messaging/android/client#manifest), could you try adding `android:exported="false"` to both of those services in your `AndroidManifest.xml`:

```xml
<service
    android:name="com.amazonaws.amplify.pushnotification.RNPushNotificationMessagingService"
    android:exported="false">
    <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT"/>
    </intent-filter>
</service>
<service
    android:name="com.amazonaws.amplify.pushnotification.RNPushNotificationDeviceIDService"
    android:exported="false">
    <intent-filter>
        <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
    </intent-filter>
</service>
```

After you add that, can you confirm you are still receiving push notifications and that the Mobsf warning is gone?

**Comment by vikas5914** [comment]
@amhinson I checked yesterday and yes we are getting the token and push notification.

**Comment by amhinson** [comment]
Did you add `android:exported="false"` to `AndroidManifest.xml`? And is the warning gone?

**Comment by vikas5914** [comment]
@amhinson correct.

**Comment by amhinson** [comment]
Ok great!
