### ISSUE TITLE
Variable 'appendToCognitoUserAgent' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by Zhuravlev1** [aws-amplify/amplify-js#5285]
I use amazon-cognito-identity-js v4.2 for node.js typescript project.
When I run check types I have an error **Variable appendToCognitoUserAgent implicitly has an 'any' type**.
index.d.ts file has export **appendToCognitoUserAgent** but hasn't type.

**Comment by matthiashub-porsche** [comment]
Just ran into the same issue. If I interpret the code correctly it should be exported as `void`, can you try following:

```
        export const appendToCognitoUserAgent: void;
```

**Comment by Amplifiyer** [comment]
Thanks @matthiashub-porsche for catching and submitting a PR. I've assigned this to @jordanranz to take a look as well.
