### ISSUE TITLE
Verification email link send

### ISSUE THREAD

**Issue by SwapnilShoreline** [aws-amplify/amplify-js#5286]
Hi Team, 
Which method used to send verification link over mail id.

Scenario is -
1. After registration, I want to send (resend verification mail) verification link over mail.

I used verifyCurrentUserAttribute() method but getting "No current user" error.

Do needful, 
Thanks

**Comment by Amplifiyer** [comment]
@SwapnilShoreline, I believe what you are looking for is `resendSignUp()`. See docs [here](https://aws-amplify.github.io/docs/js/authentication#sign-up) 

`verifyCurrentUserAttribute` is used to verify a change in username or email for a registered customer.

**Comment by SwapnilShoreline** [comment]
@Amplifiyer, I tried `resendSignUp()` also. 
but getting `No current user` error every time
