### ISSUE TITLE
Auth Error: Amplify has not been configured correctly using Nuxt.js

### ISSUE THREAD

**Issue by madStitcher** [aws-amplify/amplify-js#5289]
This is essentially the same problem as issue [4315](https://github.com/aws-amplify/amplify-js/issues/4315), except I'm using "aws-amplify": "^3.0.3"

The developer console is stating the below error, however this is NOT impacting any functionality. I am able to Sign In, Sign Up, Confirm Code, Fetch Current Authed User with no errors or issues.

    [ERROR] 30:01.743 AuthError - 
                 Error: Amplify has not been configured correctly.
                 This error is typically caused by one of the following scenarios:
 
                 1. Make sure you're passing the awsconfig object to Amplify.configure() in your app's     entry point
                     See https://aws-amplify.github.io/docs/js/authentication#configure-your-app for more information
             
                 2. There might be multiple conflicting versions of aws-amplify or amplify packages in your node_modules.
                     Try deleting your node_modules folder and reinstalling the dependencies with 'yarn install'
 
I have attempted the 2nd suggestion many times without success.

1. Create Nuxt.js project (mode: Universal)
1. Install and Manually Configure Amplify
1. Error occurs on every page reload

Expected behavior
I am hoping to not have an error message in the console if there are no actual errors with the functionality.

The config block I pass to Amplify.configure:

    const awsmobile = {
        aws_project_region: 'us-west-2',
        aws_cognito_identity_pool_id:
            'us-west-2:xxxxx',
        aws_cognito_region: 'us-west-2',
        aws_user_pools_id: 'us-west-2_xxxx',
        aws_user_pools_web_client_id: 'xxxxxx',
        oauth: {
            domain: 'xxxx',
            scope: ['email', 'openid', 'profile'],
            redirectSignIn: 'http://localhost:3000/cognito-callback/',
            redirectSignOut: 'http://localhost:3000/cognito-signout-callback/',
            responseType: 'code',
        },
    federationTarget: 'COGNITO_USER_POOLS',
    }
    export default awsmobile

**Comment by jordanranz** [comment]
Hey @madStitcher, where are you executing `Amplify.configure`? Could you also post a code snippet for how you are executing it?

**Comment by madStitcher** [comment]
I'm including a plugin on nuxt.config.js..

    plugins: [
    {
      src: '~plugins/vuedraggable',
      mode: 'client',
    },
    {
      src: '~/plugins/amplify-client.js',
      mode: 'client',
    },
    ]

And then here is my amplify-client.js.  I've added the process.BROWSER_BUILD in a failed attempt to force client side...

    import Vue from 'vue'
    import Amplify, * as AmplifyModules from 'aws-amplify'
    import { AmplifyPlugin } from 'aws-amplify-vue'
    import awsconfig from '~/aws-exports'

    Amplify.configure(awsconfig)

    if (process.BROWSER_BUILD) {
      Vue.use(AmplifyPlugin, AmplifyModules)
    }

**Comment by jordanranz** [comment]
```
const awsmobile = {
   ...
}
export default awsmobile
```
seems to export `awsmobile`

In the code above you have `import awsconfig from '~/aws-exports'`

You may need to try:
```
import awsmobile from '~/aws-exports'

Amplify.configure(awsmobile)
```
Depending on the name of the file from your manual config listed above.

You can also try:
```
import Vue from 'vue'
import Amplify, * as AmplifyModules from 'aws-amplify'
import { AmplifyPlugin } from 'aws-amplify-vue'

const awsmobile = {
    aws_project_region: 'us-west-2',
    aws_cognito_identity_pool_id:
        'us-west-2:xxxxx',
    aws_cognito_region: 'us-west-2',
    aws_user_pools_id: 'us-west-2_xxxx',
    aws_user_pools_web_client_id: 'xxxxxx',
    oauth: {
        domain: 'xxxx',
        scope: ['email', 'openid', 'profile'],
        redirectSignIn: 'http://localhost:3000/cognito-callback/',
        redirectSignOut: 'http://localhost:3000/cognito-signout-callback/',
        responseType: 'code',
    },
federationTarget: 'COGNITO_USER_POOLS',
}

Amplify.configure(awsconfig)

if (process.BROWSER_BUILD) {
  Vue.use(AmplifyPlugin, AmplifyModules)
}
```

Let me know if either of those approaches help.

**Comment by madStitcher** [comment]
Thank you for your help jordanranz, but neither of these get rid of the error. I'm not sure why it was working (albeit with the error) when I was passing awsconfig.  

When I changed it to awsmobile, it gave the same error.  And when I tried your 2nd suggestion (and changed awsconfig to awsmobile in Amplify.configure) I'm still getting the same error...

<img width="597" alt="Screen Shot 2020-04-07 at 9 55 25 AM" src="https://user-images.githubusercontent.com/26394193/78697639-f733c400-78b5-11ea-89d9-20705154d722.png">

I occasionally get the "The client-side rendered virtual DOM tree is not matching server-rendered content".  Another thing that shouldn't happen since Amplify should only be running in client. 

Here is my config now...

<img width="788" alt="Screen Shot 2020-04-07 at 9 56 23 AM" src="https://user-images.githubusercontent.com/26394193/78697854-4d086c00-78b6-11ea-920f-ee1fb2f6a4e8.png">

**Comment by collinped** [comment]
Experiencing the same issue in  "aws-amplify": "^3.0.7"

Things work fine in Universal or SPA mode, but using the **npm run generate** produces the same error and does not allow for deploying of a static application.

**Comment by madStitcher** [comment]
@collinped Do you not get the error when using it Universal mode?

**Comment by collinped** [comment]
@madStitcher I still get the error in all modes, including Universal Mode. But the generate function is completely broken because Nuxt detects an error and rolls back any pages with errors when building. The application is useable in Universal Mode and SPA, but the console shows the error on every single page.

**Comment by priyanshu-sekhar** [comment]
Faced the same issue. You need to install the auth component
`npm install @aws-amplify/auth`
and then add the following lines to main.js
```
import {Auth} from '@aws-amplify/auth'
import awsconfig from './aws-exports.js'

Auth.configure(awsconfig)
```
