### ISSUE TITLE
DataStore subscriptions with combined authorization rules not working (bug)

### ISSUE THREAD

**Issue by mdoesburg** [aws-amplify/amplify-js#5290]
**Which Category is your question related to?**

GraphQL Transform: @auth

**Amplify CLI Version** 

4.17.1

**What AWS Services are you utilizing?**

- Amplify
- AppSync
- DynamoDB
- Cognito

Within the Amplify framework I am using:

- Auth
- DataStore

**Provide additional details e.g. code snippets**

I've created a React Native app in which users can create contacts. This is the schema:

```graphql
type Contact 
  @model
  @auth(rules: [
    { allow: owner },
    { allow: groups, groups: ["Admin"] }
  ])
{
  id: ID!
  gender: String
  firstName: String
  lastName: String
  dateOfBirth: AWSDateTime
}
```

Within the app users can press a button to toggle the gender of a contact. The code looks like this:

```javascript
const toggleGender = async () => {
    await DataStore.save(
        Contact.copyOf(userDetails, updated => {
            updated.gender = updated.gender === 'male' ? 'female' : 'male';
         }),
    );
};
```

**The problem:**

I have one user logged in who's part of the Admin group. I have another user logged in who created the contact. Both users correctly see the contact and the current value of the gender field. Whenever either of the users hit the toggle gender button, the other user doesn't see the change. Basically it doesn't sync. So it seems like the subscriptions aren't working the way I want them too.

Whenever I remove ` { allow: owner }` from the schema and make both users part of the Admin group, syncing works fine and both users can toggle the gender, and instantly see changes.

How can I make it work so subscriptions/syncing works with the above setup? Am I doing something wrong?

**Comment by brene** [comment]
Hi @mdoesburg - I'm transferring this issue to the Amplify JS Library team

**Comment by mdoesburg** [comment]
@brene Thank you! I hope someone can help with this since I am working on a project that needs this functionality.

**Comment by brene** [comment]
Cc @sammartinez for triage

**Comment by mdoesburg** [comment]
Still having this issue on CLI version 4.18.0.

**Comment by mdoesburg** [comment]
> @mdoesburg we did a newer release for DataStore this last week improving the auth rules. Can you verify on the latest version if you are still experiencing this issue. Thanks ahead of time!

@sammartinez Still having the same issue. Amplify CLI version 4.21.3, and DataStore version 2.2.3.

**Comment by v1pz3n** [comment]
Here I am also having the same problem but with a slightly different rule

type Idea @model @auth (rules: [{allow: owner}])

Amplify CLI: 4.21.3
Datastore: 2.2.4

**Comment by iartemiev** [comment]
@mdoesburg for this one are you using Expo or just RN? (I want to make sure I reproduce in the same environment)

**Comment by mdoesburg** [comment]
@iartemiev Just RN.

**Comment by mdoesburg** [comment]
@iartemiev This was a while back, and honestly this might already work in the newer versions of Amplify.

**Comment by iartemiev** [comment]
@mdoesburg got it. If you'd like to try it out with `@unstable` and let us know.I'll be happy to take a look if it's still giving you trouble. As mentioned in the other issue, this was working fine for me in React.

**Comment by mdoesburg** [comment]
@iartemiev Alright I'll give it try.

**Comment by mdoesburg** [comment]
@iartemiev I am unable to get this to work right now, but I think this not being able to work is related to: https://github.com/aws-amplify/amplify-js/issues/6580 So I'll go ahead and post in there.

**Comment by iartemiev** [comment]
Closing as discussed in #6580
