### ISSUE TITLE
UI Components - AmplifyAuthenticator - How to use formFields for Sign Up? [React]

### ISSUE THREAD

**Issue by budevelop** [aws-amplify/amplify-js#5298]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Amplify, Cognito, API GW, Lambda

** Provide additional details e.g. code snippets **
I want to change the fields shown in the Sign Up form. Currently Username, Password, Email and Phone Number is displayed. I only need to get Email and Password. How can I change SignUp form fields?

I was able to do it by providing signUpConfig parameter while using withAuthenticator; however with AmplifyAuthenticator I could not make it. I tried to use formFields property as below; however it didn't work.
```
import React from "react";
import Amplify from "aws-amplify";
import { AmplifyAuthenticator, AmplifySignIn, AmplifySignUp, AmplifySignOut } from "@aws-amplify/ui-react";
import awsconfig from "./aws-exports";

Amplify.configure(awsconfig);

const App = () => (
  <AmplifyAuthenticator usernameAlias="email">
    <AmplifySignIn
      headerText="Sign In Header"
      slot="sign-in" />
    <AmplifySignUp headerText="Sign Up Header"
      formFields={[{ type: 'email', label: 'Email', placeholder: 'Email', hint: 'Enter Your Email', required: true }, { type: 'password', label: 'Password', placeholder: 'Enter Your Password', hint: 'Password', required: true }]}
      slot="sign-up" />

    <div>
      Internal App
      <AmplifySignOut />
    </div>
  </AmplifyAuthenticator>
);

export default App;
```

**Comment by NastyZ98** [comment]
Hello I am facing the same issue.

Here is my code below:
```ts
import { AmplifySignUp } from "@aws-amplify/ui-react";

const signUpFields = [
  {
    type: "email",
    label: "custom_label",
    placeholder: "Custom placeholder",
    hint: null,
    required: true,
  },
];

const Auth = () => {
  return (
    <div>
      <AmplifySignUp headerText="Custom form" formFields={signUpFields} />
    </div>
  );
};
```
![Capture d’écran 2020-04-06 à 12 43 19](https://user-images.githubusercontent.com/7148684/78550531-841e4500-7804-11ea-9e5f-49de603b1fb8.png)

Thank you.

**Comment by ashika01** [comment]
@budevelop : If you are trying to achieve sign in or sign up with `email` or `phone_number` instead of `username` , I would suggest you use the property `usernameAlias`. You just add 
```
<AmplifyAuthenticator usernameAlias="email"/>
```

**Comment by NastyZ98** [comment]
> @budevelop : If you are trying to achieve sign in or sign up with `email` or `phone_number` instead of `username` , I would suggest you use the property `usernameAlias`. You just add
> 
> ```
> <AmplifyAuthenticator usernameAlias="email"/>
> ```

Hello @ashika01 ,

The problem is that for instance if I pass a custom placeholder for the email, even if I use usernameAlias, it's seems to don't work.

You can easily reproduce the problem with the following code, you will see that the placeholder still the default one for instance.

```ts
import { AmplifySignUp, AmplifyAuthenticator } from "@aws-amplify/ui-react";

const signUpFields = [
  {
    type: "email",
    label: "custom_label",
    placeholder: "Custom placeholder",
    hint: null,
    required: true,
  },
];

const Auth = () => {
  return (
    <AmplifyAuthenticator usernameAlias="email">
      <AmplifySignUp headerText="Custom form" formFields={signUpFields} slot="sign-up" />
    </AmplifyAuthenticator>
  );
};
```

**Comment by ashika01** [comment]
@NastyZ98 That is expected since we setup the form fields internally based on `usernameAlias` (i.e, based on the method of authentication).  However I understand the use case and the way to achieve it is slots for sure. Will do some discussion with team and update on how we would wanna go about this.

**Comment by NastyZ98** [comment]
> @NastyZ98 That is expected since we setup the form fields internally based on `usernameAlias` (i.e, based on the method of authentication). However I understand the use case and the way to achieve it is slots for sure. Will do some discussion with team and update on how we would wanna go about this.

Thank you @ashika01 ! For the moment, as a workaround, I use aws-amplify-react with Authenticator and signUpFields configuration.

**Comment by jordanranz** [comment]
I believe a good solution for this will be to intelligently populate the form field custom data like `hint`, `placeholder`, and `label`. I am looking into how to support this.

**Comment by ashika01** [comment]
@NastyZ98 @budevelop : Update this is being tracked now and we are working on this to provide this customization.

**Comment by helloanil** [comment]
Sorry to necrobump this but does that mean there's no way of removing Phone Number field from Sign Up form, using latest UI Components?

**Comment by ashika01** [comment]
**_Update:_** Got the customization working with form fields. Needs update for supporting all standard and custom user attributes and should have a PR soon.

<img width="475" alt="Screen Shot 2020-04-15 at 3 09 11 AM" src="https://user-images.githubusercontent.com/35131273/79325719-85b3d100-7ec6-11ea-8c28-6c259093cab1.png">

**Comment by josh-tncarry** [comment]
Facing the same issue. I noticed that in the code for both [AmplifySignIn](https://github.com/aws-amplify/amplify-js/blob/master/packages/amplify-ui-components/src/components/amplify-sign-in/amplify-sign-in.tsx) and [AmplifySignUp](https://github.com/aws-amplify/amplify-js/blob/master/packages/amplify-ui-components/src/components/amplify-sign-up/amplify-sign-up.tsx), that it completely ignores anything passed into `formFields`.

The documentation leads one to believe this is possible.

**Comment by helloanil** [comment]
Hey @ashika01 and @jordanranz,

Thanks for taking a look at this but I'm not sure if this is solved. My code:

```js
import {
  AmplifyAuthenticator,
  AmplifySignOut,
  AmplifySignUp,
} from "@aws-amplify/ui-react";

function App() {
  return (
    <AmplifyAuthenticator>
      <AmplifySignUp
        slot="sign-up"
        headerText="Something here"
        formFields={[{ type: "email" }, { type: "password" }]}
      />
      <>
        <MyApp />
        <AmplifySignOut />
      </>
    </AmplifyAuthenticator>
  );
}
```

But I'm still seeing this:

![image](https://user-images.githubusercontent.com/6314657/79602508-df94e080-80ea-11ea-962f-8d27300dc69e.png)

**Comment by ashika01** [comment]
Hi everyone,

Posting update here - Changing form field is going to need documentation update. In meanwhile, here is a sample code for customizing form field.

```js
<AmplifyAuthenticator>
    <AmplifySignUp
      headerText="Custom form"
      formFields={[
        {
          type: 'username',
          label: 'Custom Username Label',
          placeholder: 'custom username placeholder',
          required: true,
          handleInputChange: (event, cb) => {
            console.log('custom username field');
            //perform any actions needed
            cb(event);
          },
        },
        {
          type: 'password',
          label: 'Custom Password Label',
          placeholder: 'custom password placeholder',
          required: true,
          handleInputChange: (event, cb) => {
            console.log('custom pwd field');
            cb(event);
          },
        },
      ]}
      slot="sign-up"
    />
  </AmplifyAuthenticator>
```

In short, `handleInputChange` of form field needs to invoke a callback like shown above in order for us to handle the state internally. `handleInputChange` needs the signature `(event,cb) => { cb(event) }`

Note: The update is in `unstable` right now. We will be doing a release to stable shortly. Please try this out and let us know what needs to be improved.

**Comment by NutterzUK** [comment]
Sorry for being a bit new to this, how do I set up npm to use the `unstable` build so I can try this out?

**Comment by sri7vasu** [comment]
If you are using TypeScript, here is the solution:

**Comment by sri7vasu** [comment]
If you are using TypeScript, here is the solution:

import { FormFieldTypes } from '@aws-amplify/ui-components/dist/types/components/amplify-auth-fields/amplify-auth-fields-interface';

function SignUp() {
  return (
    <AmplifyAuthenticator usernameAlias="email" initialAuthState={AuthState.SignUp}>
      <AmplifySignUp
        headerText="Sign Up"
        usernameAlias="email"
        formFields={[
          {
            type: 'email',
            label: 'Email',
            placeholder: 'Enter your email',
            required: true,
            handleInputChange: (event:Event, cb:Function) => {
             console.log('custom username field');
              cb(event);
            }
          },
          {
            type: 'password',
            label: 'Password',
            placeholder: 'Enter your password',
            required: true,
            handleInputChange: (event: Event, cb: Function) => {
            console.log('custom pwd field');
             cb(event);
            }
          }
        ] as FormFieldTypes}
        slot="sign-up"
        ></AmplifySignUp>
    </AmplifyAuthenticator>
  );
}
export default SignUp;

**Comment by faroceann** [comment]
Things are working ok on unstable, but I wasn't able to get the `phone_number` field to work. 

```
 <AmplifySignUp
   slot="sign-up"
   usernameAlias="email"
  formFields=[{
      label: "Phone number",
      required: true,
      type: "phone_number"
}]
/>
```

When it gets sent to the Cognito IDP, it appears that either only the country calling code is sent, or only the bare phone number is sent.

**Comment by spiii** [comment]
Hey I have the same issue with the @aws-amplify/ui-angular 
Is there any fix on unstable as well ?

**Comment by khiner** [comment]
This workaround solved my problem of not being able to exclude phone number fields from the form input, but it removes the "Forgot password" flow, since that's added as a hint to the `formField` in [`amplify-sign-in`](https://github.com/aws-amplify/amplify-js/blob/master/packages/amplify-ui-components/src/components/amplify-sign-in/amplify-sign-in.tsx), and it uses a private `handleAuthStateChange` method that doesn't have a callback like `handleInputChange` does:

```
      formFieldInputs.push({
        type: 'password',
        hint: (
          <div>
            {I18n.get(Translations.FORGOT_PASSWORD_TEXT)}{' '}
            <amplify-button
              variant="anchor"
              onClick={() => this.handleAuthStateChange(AuthState.ForgotPassword)}
              data-test="sign-in-forgot-password-link"
            >
              {I18n.get(Translations.RESET_PASSWORD_TEXT)}
            </amplify-button>
          </div>
        ),
        required: true,
        handleInputChange: this.handleFormFieldInput('password'),
        inputProps: {
          'data-test': 'sign-in-password-input',
        },
      });
```

Anyone have a suggestion here?

**Comment by 4-life** [comment]
How to use custom fields in `formFields`?
In previous version of amplify were `key: 'custom:pin'`

**Comment by scottkelso** [comment]
I believe I am observing the same issue on my quasar app, using `@aws-amplify/ui-vue`.
I also tried the `handleInputChange` (as you can see below) with no success.

My signin needs:
* email or phone number,
* password

My signup needs 
* email
* phone number
* password
* name

```
<template>
  <q-page class="flex flex-center">
    <amplify-authenticator username-alias="email" initial-auth-state="signin">
      <amplify-sign-up
        :formFields="signupFormFields"
        header-text="SIGNUP"
        slot="'sign-up'"></amplify-sign-up>
        <amplify-sign-in
        :formFields="signinFormFields"
        header-text="SIGNIN"
        slot="'sign-in'"></amplify-sign-in>
    </amplify-authenticator>
  </q-page>
</template>

<script>
export default {
  data () {
    return {
      signupFormFields: [
        {
          type: 'name',
          label: 'Name',
          placeholder: 'Enter your full name',
          required: true,
          handleInputChange: (event, cb) => {
            cb(event)
          }
        },
        {
          type: 'phone_number',
          label: 'Phone Number',
          placeholder: 'Enter your phone number',
          required: true,
          handleInputChange: (event, cb) => {
            cb(event)
          }
        },
        {
          type: 'email',
          label: 'Email',
          placeholder: 'Enter an email address',
          required: true,
          handleInputChange: (event, cb) => {
            cb(event)
          }
        },
        {
          type: 'password',
          label: 'Password',
          placeholder: 'Enter a password',
          required: true,
          handleInputChange: (event, cb) => {
            cb(event)
          }
        }
      ],
      signinFormFields: [...]
    }
  }
}
</script>
```

Produces this:

![image](https://user-images.githubusercontent.com/26043376/80544555-3501a500-89a9-11ea-9472-48c17634b233.png)

The component is picking up my header but not my signin fields.

Operating System: Windows
Browser: Chrome
Amplify CLI: 4.18.1
@aws-amplify/ui-vue: ^0.2.3
aws-amplify: ^3.0.9
Quasar: 1.9.14

**Comment by andriworld** [comment]
@scottkelso : in Vue, try `:formFields.prop=...`
I saw this solution here: https://github.com/aws-amplify/amplify-js/issues/5363#issuecomment-618627713

**Comment by andriworld** [comment]
Hi @khiner, @ashika01 
Have you found a way to keep the "Forgot password link" after formFields customization? 
(this is my only blocking issue)

**Comment by scottkelso** [comment]
Thank you @andriworld !  This did infact work with both `:formFields.prop=`... and `:form-fields.prop=...`. Also thank you for pointing me to that same issue relating to vue.

This allowed me to select the correct formFields. A non-blocking behaviour emerged where I would get `"Username cannot be empty"` error with the following markup. (See same props on [my previous comment](https://github.com/aws-amplify/amplify-js/issues/5298#issuecomment-620895611))

```
<amplify-authenticator username-alias="email">    <!--Did not work-->
    <amplify-sign-up
        :form-fields.prop="signupFormFields"
        slot="sign-up"></amplify-sign-up>
</amplify-authenticator>
```

Moving the `username-alias` attribute to the `<amplify-sign-up>` component worked which I don't understand.

```
<amplify-authenticator>    <!--Worked-->
    <amplify-sign-up
        username-alias="email"
        :form-fields.prop="signupFormFields"
        slot="sign-up"></amplify-sign-up>
</amplify-authenticator>
```

Aside from that smaller issue, I am now blocked by the same issue @faroceann describes with phone_number. On form submission the following payload is being sent where you can see that the country code of the phone number is missing.

```
Password: "************"
UserAttributes: [
  {Name: "name", Value: "Someone"}
  {Name: "phone_number", Value: "7894561233"}
  {Name: "email", Value: "example@gmail.com"}
]
Username: "example@gmail.com"
```

**Comment by jordanranz** [comment]
Going to reopen this to continue the discussion.

**Comment by ashika01** [comment]
Hey, I am checking the phone fields issue right now. I will investigate that and address other questions here.

**Comment by ashika01** [comment]
> Thank you @andriworld ! This did infact work with both `:formFields.prop=`... and `:form-fields.prop=...`. Also thank you for pointing me to that same issue relating to vue.
> 
> This allowed me to select the correct formFields. A non-blocking behaviour emerged where I would get `"Username cannot be empty"` error with the following markup. (See same props on [my previous comment](https://github.com/aws-amplify/amplify-js/issues/5298#issuecomment-620895611))
> 
> ```
> <amplify-authenticator username-alias="email">    
>     <amplify-sign-up
>         :form-fields.prop="signupFormFields"
>         slot="sign-up"></amplify-sign-up>
> </amplify-authenticator>
> ```
> 
> Moving the `username-alias` attribute to the `<amplify-sign-up>` component worked which I don't understand.
> 
> ```
> <amplify-authenticator>    
>     <amplify-sign-up
>         username-alias="email"
>         :form-fields.prop="signupFormFields"
>         slot="sign-up"></amplify-sign-up>
> </amplify-authenticator>
> ```
> 
> Aside from that smaller issue, I am now blocked by the same issue @faroceann describes with phone_number. On form submission the following payload is being sent where you can see that the country code of the phone number is missing.
> 
> ```
> Password: "************"
> UserAttributes: [
>   {Name: "name", Value: "Someone"}
>   {Name: "phone_number", Value: "7894561233"}
>   {Name: "email", Value: "example@gmail.com"}
> ]
> Username: "example@gmail.com"
> ```
> 
> Has anyone managed to get a fix / workaround for this?

@scottkelso : the username-alias in signup is expected. so we you create ur slot , the custom slot overrides our original component, so there is no way for signup to know about the username behavior. We will look into improving this in the future.  but the behavior is expected as of now.

**Comment by ashika01** [comment]
@faroceann @scottkelso I was able to reproduce the `phone_number` bug. I will be working on a PR for this.

**Comment by jordanranz** [comment]
@scottkelso I will add documentation around this in our new docs site to make the usage more clear when using `formFields` for each framework

**Comment by andriworld** [comment]
Hi @ashika01   I also had a question about the "forgot password" link.  How can I make sure it's there after I customize the sign-in form fields?  Thank you

**Comment by ashika01** [comment]
Keeping this reopened to continue discussion on hint component of formField.

**Comment by ashika01** [comment]
@andriworld Looks like this might be a bug.. I am working on this.

**Comment by ashika01** [comment]
Hi, hint handling has been fixed. We have some trouble with stencil react bindings which needs more work on the bindings itself. But for now, when `hint is not specified` it will display the defaults. If you dont want any hints, you could specify `hint: null`. And any `string as hint` would work as expected.

**Comment by andriworld** [comment]
It works!  I updated to @aws-amplify/ui-vue@0.2.5-unstable.25  and the "Reset Password" link is back on my customized login form.
Many thanks @ashika01  !

**Comment by Jason-Reich** [comment]
@ashika01  I have a question about: "And any string as hint would work as expected."

What do you mean by this? It seems to be related to the problem I'm having (which was discussed above)... in particular, I can't put use my custom hint
`hint: `${validationError}`,`
on the password type from formFields without causing the default "Forgot your password" link from going away.

I was hoping that the expected behavior in the use case I have would be that a custom hint would be in addition to the "Forgot your password" link. Is that not the case?

If my imports seem off please let me know...

`import {
  AmplifyAuthenticator,
  AmplifySignIn,
  AmplifyConfirmSignUp,
  AmplifySignUp,
} from '@aws-amplify/ui-react';

import Amplify, { Hub } from 'aws-amplify';

import {
  AuthState,
  onAuthUIStateChange,
} from '@aws-amplify/ui-components';

import awsmobile from '../aws-exports';

import '../index.css';

import '@aws-amplify/ui/dist/style.css';

Amplify.configure(awsmobile);`

One quick note: The variable I'm passing to `Hint` is nothing other than the error messages that I'm grabbing (and slightly rewriting) from `data.payload.data.message`. I am doing this because I have to disable the error message toast feature or else users can't see our navbar and effectively navigate our site as needed when there is an error.

That brings me to a, perhaps, even more serious issue: It is next to impossible to see the error in the gray font that is hard coded for `Hint`. If I change the "amplify gray" to red using CSS... then the "No account?", which happens to be in the same gray, turns red. Any suggestions? I have to fix this soon so I'm happy to do a complete custom solution if that is what you recommend (I suppose I'm free to write the error message I captured elsewhere in the page)... please just let me know what the "best practice" is for finessing the Amplify React Auth error message issue these days. 

Thanks!

**Comment by Jason-Reich** [comment]
@helloanil What did you use to "tell" AmplifyButton what it is supposed to do? For example, I'm using  
`<AmplifyFormSection slot="sign-up">` and
``` <AmplifyAuthFields
          formFields={[
            {
              type: 'email',
               ...```
just like you suggested and everything is super customizable this way! I just don't know how to make AmplifyButton do the right thing (in this case it needs to do what the "CREATE ACCOUNT" button does from the <AmplifySignUp /> component. 

Were you able to get this to work?

**Comment by niloy369** [comment]
any idea how to add select option dropdown in sign up form?

**Comment by hakuna-mathatha** [comment]
Hi,

I wonder if there is an update on the Vue issue?

I am still facing with the same problem with Vue3.
I define the formFields as follows:

```
data() {
    return {
      user: undefined,
      authState: undefined,
      unsubscribeAuth: undefined,
      formFields: [
        {
          type: "email",
          label: "Custom email Label",
          placeholder: "custom email placeholder",
          required: true,
        },
        {
          type: "password",
          label: "Custom Password Label",
          placeholder: "custom password placeholder",
          required: true,
        },
        {
          type: "nickname",
          label: "Nickname",
          placeholder: "Nickname",
          name: "custom:nickname",
          fieldId: "custom:nickname",
        },
      ],
    };
  }
```
I tried using (as it is mentioned in the documentation):

```
<amplify-sign-up header-text="My custom Sign Up text" slot="sign-up"
        username-alias="email"
        :form-fields.prop="formFields"
 ></amplify-sign-up> 
```
and I end up with 
![image](https://user-images.githubusercontent.com/11216305/107153616-68c12080-6966-11eb-8c55-f03dadf51abf.png)

Oddly when I change it to:
```
<amplify-sign-up header-text="My custom Sign Up text" slot="sign-up"
        username-alias="email"
        :formFields="formFields"
 ></amplify-sign-up> 
```
during development it shows the customized form until I don't reload the page. As soon as I reload it is gone.

![image](https://user-images.githubusercontent.com/11216305/107153699-cbb2b780-6966-11eb-930c-8f0d4f9d7ad0.png)

I could use any suggestion.

Thank you!

**Comment by CharlieDigital** [comment]
@gegetoth What `ui-vue` package are you using?

I am using 1.0.2 and have some different issues:

```
<amplify-authenticator
    username-alias="email">
    <amplify-sign-up
        slot="sign-up"
        header-text="SIGN UP NOW"
        username-alias="email"
        :form-fields.prop="formFields">

    </amplify-sign-up>
</amplify-authenticator>
```

The above has no effect on the form at all.  The 'SIGN UP NOW' header text doesn't display, for example. 

Even trying your chnage to `:formFields="formFields"` has no effect.

**Comment by hannesortmeier** [comment]
> Hi,
> 
> I wonder if there is an update on the Vue issue?
> 
> I am still facing with the same problem with Vue3.
> I define the formFields as follows:
> 
> ```
> data() {
>     return {
>       user: undefined,
>       authState: undefined,
>       unsubscribeAuth: undefined,
>       formFields: [
>         {
>           type: "email",
>           label: "Custom email Label",
>           placeholder: "custom email placeholder",
>           required: true,
>         },
>         {
>           type: "password",
>           label: "Custom Password Label",
>           placeholder: "custom password placeholder",
>           required: true,
>         },
>         {
>           type: "nickname",
>           label: "Nickname",
>           placeholder: "Nickname",
>           name: "custom:nickname",
>           fieldId: "custom:nickname",
>         },
>       ],
>     };
>   }
> ```
> 
> I tried using (as it is mentioned in the documentation):
> 
> ```
> <amplify-sign-up header-text="My custom Sign Up text" slot="sign-up"
>         username-alias="email"
>         :form-fields.prop="formFields"
>  ></amplify-sign-up> 
> ```
> 
> and I end up with
> ![image](https://user-images.githubusercontent.com/11216305/107153616-68c12080-6966-11eb-8c55-f03dadf51abf.png)
> 
> Oddly when I change it to:
> 
> ```
> <amplify-sign-up header-text="My custom Sign Up text" slot="sign-up"
>         username-alias="email"
>         :formFields="formFields"
>  ></amplify-sign-up> 
> ```
> 
> during development it shows the customized form until I don't reload the page. As soon as I reload it is gone.
> 
> ![image](https://user-images.githubusercontent.com/11216305/107153699-cbb2b780-6966-11eb-930c-8f0d4f9d7ad0.png)
> 
> I could use any suggestion.
> 
> Thank you!

Got the same problem using vue3 and @aws-amplify/ui-components. Form elements are not showing, no matter what I do.

**Comment by allisonhamelin** [comment]
> > Hi,
> > I wonder if there is an update on the Vue issue?
> > I am still facing with the same problem with Vue3.
> > I define the formFields as follows:
> > ```
> > data() {
> >     return {
> >       user: undefined,
> >       authState: undefined,
> >       unsubscribeAuth: undefined,
> >       formFields: [
> >         {
> >           type: "email",
> >           label: "Custom email Label",
> >           placeholder: "custom email placeholder",
> >           required: true,
> >         },
> >         {
> >           type: "password",
> >           label: "Custom Password Label",
> >           placeholder: "custom password placeholder",
> >           required: true,
> >         },
> >         {
> >           type: "nickname",
> >           label: "Nickname",
> >           placeholder: "Nickname",
> >           name: "custom:nickname",
> >           fieldId: "custom:nickname",
> >         },
> >       ],
> >     };
> >   }
> > ```
> > 
> > 
> > I tried using (as it is mentioned in the documentation):
> > ```
> > <amplify-sign-up header-text="My custom Sign Up text" slot="sign-up"
> >         username-alias="email"
> >         :form-fields.prop="formFields"
> >  ></amplify-sign-up> 
> > ```
> > 
> > 
> > and I end up with
> > ![image](https://user-images.githubusercontent.com/11216305/107153616-68c12080-6966-11eb-8c55-f03dadf51abf.png)
> > Oddly when I change it to:
> > ```
> > <amplify-sign-up header-text="My custom Sign Up text" slot="sign-up"
> >         username-alias="email"
> >         :formFields="formFields"
> >  ></amplify-sign-up> 
> > ```
> > 
> > 
> > during development it shows the customized form until I don't reload the page. As soon as I reload it is gone.
> > ![image](https://user-images.githubusercontent.com/11216305/107153699-cbb2b780-6966-11eb-930c-8f0d4f9d7ad0.png)
> > I could use any suggestion.
> > Thank you!
> 
> Got the same problem using vue3 and @aws-amplify/ui-components. Form elements are not showing, no matter what I do.

Also seeing this same problem.

**Comment by impons** [comment]
> > > Hi,
> > > I wonder if there is an update on the Vue issue?
> > > I am still facing with the same problem with Vue3.
> > > I define the formFields as follows:
> > > ```
> > > data() {
> > >     return {
> > >       user: undefined,
> > >       authState: undefined,
> > >       unsubscribeAuth: undefined,
> > >       formFields: [
> > >         {
> > >           type: "email",
> > >           label: "Custom email Label",
> > >           placeholder: "custom email placeholder",
> > >           required: true,
> > >         },
> > >         {
> > >           type: "password",
> > >           label: "Custom Password Label",
> > >           placeholder: "custom password placeholder",
> > >           required: true,
> > >         },
> > >         {
> > >           type: "nickname",
> > >           label: "Nickname",
> > >           placeholder: "Nickname",
> > >           name: "custom:nickname",
> > >           fieldId: "custom:nickname",
> > >         },
> > >       ],
> > >     };
> > >   }
> > > ```
> > > 
> > > 
> > > I tried using (as it is mentioned in the documentation):
> > > ```
> > > <amplify-sign-up header-text="My custom Sign Up text" slot="sign-up"
> > >         username-alias="email"
> > >         :form-fields.prop="formFields"
> > >  ></amplify-sign-up> 
> > > ```
> > > 
> > > 
> > > and I end up with
> > > ![image](https://user-images.githubusercontent.com/11216305/107153616-68c12080-6966-11eb-8c55-f03dadf51abf.png)
> > > Oddly when I change it to:
> > > ```
> > > <amplify-sign-up header-text="My custom Sign Up text" slot="sign-up"
> > >         username-alias="email"
> > >         :formFields="formFields"
> > >  ></amplify-sign-up> 
> > > ```
> > > 
> > > 
> > > during development it shows the customized form until I don't reload the page. As soon as I reload it is gone.
> > > ![image](https://user-images.githubusercontent.com/11216305/107153699-cbb2b780-6966-11eb-930c-8f0d4f9d7ad0.png)
> > > I could use any suggestion.
> > > Thank you!
> > 
> > 
> > Got the same problem using vue3 and @aws-amplify/ui-components. Form elements are not showing, no matter what I do.
> 
> Also seeing this same problem (except I don't see the custom form fields at all whether I reload or not).

Any update on this? i have the same problem.

**Comment by licanulla** [comment]
Facing the same issue - using formFields has no effect at all.
@aws-amplify/ui-components@1.6.0
aws-amplify@4.1.2
vue@3.1.2

**Comment by StreetLamp05** [comment]
facing the same issue. It is ignoring [the following customization.](https://prnt.sc/1hw3x57)



export default withAuthenticator(App, {
  signUpConfig: {
    hiddenDefaults: ["phone_number"],
    signUpFields: [
      {
        label: "First Name",
        key: "given_name",
        required: true,
        type: "string",
      },
      {
        label: "Last Name",
        key: "family_name",
        required: true,
        type: "string",
      },
    ],
  },
});

**Comment by tnraddatz** [comment]
For reference, the current props you can pass are: 

```
    interface AmplifyAuthenticator {
        /**
          * Federated credentials & configuration.
         */
        "federated": FederatedConfig;
        /**
          * Callback for Authenticator state machine changes
         */
        "handleAuthStateChange": AuthStateHandler;
        /**
          * Hide amplify-toast for auth errors
         */
        "hideToast": boolean;
        /**
          * Initial starting state of the Authenticator component. E.g. If `signup` is passed the default component is set to AmplifySignUp
         */
        "initialAuthState": | AuthState.SignIn
		| AuthState.SignUp
		| AuthState.ForgotPassword;
        /**
          * Username Alias is used to setup authentication with `username`, `email` or `phone_number`
         */
        "usernameAlias": UsernameAliasStrings;
    }
    ```

**Comment by ranopriyo-neogy** [comment]
I ran into similar issues while trying to remove the Submit Button; however, there is limited documentation on how to achieve it. Can anyone suggest how to do it? 

**Code:**

```
function App() {
  return (
    <AmplifyAuthenticator>
        <AmplifyFormSection slot="sign-in" headerText="Sign in with AWS to login using OneLogin">
        <AmplifyOauthButton />
        </AmplifyFormSection>
    </AmplifyAuthenticator>
  );
}
```
 **Current:**

![Screen Shot 2021-11-11 at 5 26 16 PM](https://user-images.githubusercontent.com/68603179/141377855-b791e1e9-fa51-4c20-887a-18fa828dcab1.png)

**Expected**

![Screen Shot 2021-11-11 at 5 27 22 PM](https://user-images.githubusercontent.com/68603179/141377993-1d6836d8-9672-4ce0-8990-f871a4c66145.png)
