### ISSUE TITLE
limit on Amplify list queries

### ISSUE THREAD

**Issue by blairtaylor** [aws-amplify/amplify-js#5299]
Our question relates to using the generated Amplify queries, specifically the listXXX queries. 

Using DynamoDB and AppSync, when we specify a listXXX query, this is our understanding:

- a query is generated with limit of 10 by default or whatever limit is provider as a param (let's say 100)
- if the underlying table was "Country" for example, the query would retrieve 100 country records then apply whatever filter was specified
- the problem occurs when the filter would result in a small number of results (far less than 100) but the number of rows in the DynamoDB Country table is larger than 100 (say 200)
- in this case the returned result would only contain 50% of the expected entries 

In our application, this results in users reporting that added entries don't show up in lists. We have been able to solve the issue (temporarily) by increasing the limit but this seems like a poor solution.

So two questions:

1) Is our understanding correct?

2) What is the best way to deal with this issue? I know we can use custom indexes and query them but this would involve a great deal of work to overcome this issue which is arguably a framework/Appsync issue. Since we mostly sort on the client, listXXX works well for us except for this limit issue.

Would appreciate feedback on this. Thanks.

**Comment by RossWilliams** [comment]
1. Filter is very unfortunate as it is meant as a DynamoDB filter expression (see a great guide [here](https://www.alexdebrie.com/posts/dynamodb-filter-expressions/) ), but many users come to Amplify from an RDBMS background and expect it to behave as a 'WHERE' clause. I wouldn't call it a framework or AppSync issue, except for a documentation or naming fault.

2. The best way depends on your data and tradeoffs. Questions to ask your table: Is it bounded in number of items? Is it bounded in size, and under 1MB? Can you deal with up to 30ms of additional request time? If the answer to all is yes, then you could use filter and set the limit to the upper bound of the number of items. That way the user always gets all data. If the size is greater than 1MB you could *technically* still use filter, but you now need to page through the data with additional round-trips, and your latency will start multiplying fast.
The other option, and generally a good choice, is to use a custom index. I wouldn't call this overcoming an AppSync issue, but rather doing things in a way that is sympathetic to the underlying database. DynamoDB requires you to create indexes that are shaped for your access requests. It is a non-goal of DynamoDB to support arbitrary SQL-like queries.
Lastly, if you have a lot of custom document searching / filtering, consider using @searchable directive.

**Comment by ashika01** [comment]
Closing this on back of https://github.com/aws-amplify/amplify-cli/issues/1865 too. I would suggest tracking the above mentioned Feature request for more info.
