### ISSUE TITLE
How May I Style the Angular Amplify-Authenicator Sign in 

### ISSUE THREAD

**Issue by DeniseJames** [aws-amplify/amplify-js#5303]
I am using Angular 9 and he Amplify Angular Module to get the following sign in screen. It works functionally. It is too large for mobile devices. How can I make it small enough for a mobile device?

![image](https://user-images.githubusercontent.com/17970321/78579822-220b1300-77f7-11ea-8bbb-6be29a2bd710.png)

**Comment by jordanranz** [comment]
Hi @DeniseJames, which version of the angular module are you using for this?

**Comment by DeniseJames** [comment]
@jordanranz  I do not know how to check for the version but I used this command from the aws amplify angular website

$ npm install aws-amplify aws-amplify-angular

**Comment by jordanranz** [comment]
Ok got it. We have just released a [new `amplify-authenticator` for Angular](https://docs.amplify.aws/ui/auth/authenticator?framework=angular) and the usage is very similar to the legacy `aws-amplify-angular` version. The new `amplify-authenticator` should not have the problem you are experiencing above. 

Could you try out the [new component](https://docs.amplify.aws/ui/auth/authenticator?framework=angular) and report back here?

If you want to use the legacy `amplify-authenticator` in `aws-amplify-angular` the only way to achieve this is to apply [css overrides](https://aws-amplify.github.io/docs/js/angular#styles) which can be challenging.

**Comment by DeniseJames** [comment]
@jordanranz  I cannot find aws-exports.js  after installing

import awsconfig from './aws-exports';

**Comment by jordanranz** [comment]
`./aws-exports` is most like at `/src/aws-exports`

Can you find where `aws-exports.js` file is relative to you `app.module.ts`? 
or try:
`import awsconfig from '../aws-exports';`

**Comment by DeniseJames** [comment]
@jordanranz  Do you know why I may be getting this error after adding the new angular amplify UI component

`ERROR in ./node_modules/@aws-amplify/ui-components/dist/esm/amplify-authenticator.entry.js 72:31-35     
"export 'Auth' was not found in '@aws-amplify/auth'`

**Comment by DeniseJames** [comment]
Ignore the previous. I started a new project and it is fine.

**Comment by jordanranz** [comment]
Ahh ok, I was going to ask which version of `aws-amplify` you were using in your `package.json`. Were you able to test the new `amplify-authenticator`?

**Comment by DeniseJames** [comment]
@jordanranz  So far it works. I need to add the amplifyservice.. From another github I was using import { AmplifyService } from '@flowaccount/aws-amplify-angular'; for Angular 9 and it worked. I am about to install it and hopefully it works in the new project with what you gave me.

**Comment by jordanranz** [comment]
Not sure what `@flowaccount/aws-amplify-angular` is but it may have helped with Angular 9 support? Curious how are you using `AmplifyService` from that package?

Let us know if the new UI package works for you for the initial issue you posted about :D

**Comment by DeniseJames** [comment]
@jordanranz  This is how I use AmplifyService, which noticed I cannot use it with the UI angular amplify.  How will I know if I am signed in or not?

`constructor(
    public amplifyService: AmplifyService, public router: Router)
  {
    this.amplifyService = amplifyService;
    this.amplifyService.authStateChange$.subscribe(authState => {
      console.log('authState', authState);
      if (authState.state === 'signedIn') {
        this.router.navigate(['/presub']);
      }
    });
    /** now you can access category APIs:
       * this.amplifyService.auth();          // AWS Amplify Auth
       * this.amplifyService.analytics();     // AWS Amplify Analytics
       * this.amplifyService.storage();       // AWS Amplify Storage
       * this.amplifyService.api();           // AWS Amplify API
       * this.amplifyService.cache();         // AWS Amplify Cache
       * this.amplifyService.pubsub();        // AWS Amplify PubSub
       **/
  }`

**Comment by jordanranz** [comment]
Hi @DeniseJames, apologies for the delay getting back to you. `AmplifyService` is simply a wrapper on top of our categories modules (API, Auth, etc.) To access category modules you can do something like:

```
// Instead of `this.amplifyService.auth();`
import { Auth } from 'aws-amplify';
```
or
```
import Auth from '@aws-amplify/auth';
```
In addition to the category modules, there is a helper to listen to auth state changes as you mentioned. This should now be done using [Hub](https://docs.amplify.aws/lib/utilities/hub?platform=js) to listen for AuthState changes.

To do something like:
```
this.amplifyService.authStateChange$.subscribe(authState => { 
  console.log('authState', authState);
  if (authState.state === 'signedIn') { this.router.navigate(['/presub']); } 
});
```
You can do:
```
import { Hub } from 'aws-amplify';

Hub.listen('auth', (data) => {
    switch (data.payload.event) {
        case 'signIn':
            this.router.navigate(['/presub']);
            break;
    }
});
```
See more Hub authentication event documentation [here](https://docs.amplify.aws/lib/utilities/hub?platform=js#authentication-events).

Please let me know if this helps.

**Comment by DeniseJames** [comment]
@jordanranz  I need the boolean value of signIn in your switch statement. I now get it from the amplifier service. It does not work with angular 9, but I was given this beta service that does work with angular 9.

**Comment by DeniseJames** [comment]
@jordanranz  I found flowaccount package on another issue thread, it is uploaded here as beta for angular 9 https://www.npmjs.com/package/@flowaccount/aws-amplify-angular  I  would like to use this service and also be able to change the size of the sign-in component. I would rather not use hub.

**Comment by jordanranz** [comment]
Ok, keep in mind the `aws-amplify-angular` Authenticator component is now in maintenance mode and we are encouraging the use of the new library to receive the latest updates. 

Curious what your reason is for not wanting to use `Hub`. If we can export a new `authStateChange` function from the new UI library would that suffice for your use case?

**Comment by jordanranz** [comment]
After some investigation, if you'd like to continue using `aws-amplify-angular` and manually style the component you can apply a workaround by adding:
```
@media only screen and (max-width: 480px) {
    .amplify-form-cell-left {
        font-size: 12px;
        margin-top: 14px;
    }
}
```

You can adjust the `margin-top` and media query `max-width` depending on your use case.

**Comment by DeniseJames** [comment]
@jordanranz  I do not understand hub as I do the service that uses subscribe, which is all the rage.  I would love a new authstatechange, boolean is fine.

**Comment by DeniseJames** [comment]
@jordanranz , I have a question about this, where will I get the 'signIn' value from?

import { Hub } from 'aws-amplify';

Hub.listen('auth', (data) => {
    switch (data.payload.event) {
        case 'signIn':
            this.router.navigate(['/presub']);
            break;

**Comment by DeniseJames** [comment]
@jordanranz  I attempted to use [hub](https://docs.amplify.aws/lib/utilities/hub/q/platform/js#authentication-events) from the link you provided. I get this error, as I kind of expect to. How will it now what auth is

![image](https://user-images.githubusercontent.com/17970321/80523053-1bce0980-8953-11ea-8684-47d8edf9715b.png)

**Comment by mybluedog24** [comment]
You could just create an observable like AmplifyService:
https://github.com/aws-amplify/amplify-js/blob/e85640a4e18fa1d55411038fee58919ad73121fa/packages/aws-amplify-angular/src/providers/amplify.service.ts
For more info about Hub: 
https://docs.amplify.aws/lib/utilities/hub/q/platform/js#working-with-the-api

Here is what I do:

app.module.ts:
```js
import { Amplify, Hub } from '@aws-amplify/core';
Amplify.configure(awsconfig);
```

in your auth service:
```js
import { Hub } from '@aws-amplify/core';
import { Observable, Subject } from 'rxjs';
......
export class AuthService {
    private _authState = new Subject<any>();
    authStateChange$ = this._authState.asObservable();
......
    constructor() {
        Hub.listen('auth', (data) => {
            const { payload } = data;
            switch (data.payload.event) {
                case 'signIn':
                    this._authState.next({state: "signedIn", user: payload.data});
                    break;
                case 'signOut':
                    this._authState.next({state: "signedOut", user: null});
                    break;
            }
        })
    }
```

**Comment by amhinson** [comment]
@DeniseJames Were you able to solve your issue here?
