### ISSUE TITLE
Track how long a user has been on a tab and send to PinPoint?

### ISSUE THREAD

**Issue by chai86** [aws-amplify/amplify-js#5316]
I understand that you can track when an app comes to the foreground (using React Native here on iOS) through using AppState from react-native. e.g.

 ```
//Tracks when app is brought to fore
  onAppStateChange(appState) {    
    if(appState === 'active') {
      Analytics.record('User Foreground')
    }
  }
```

What i'd like to do, is to be able to know how long in seconds, a user has spent on a particular tab (i'm using react native bottomTabNavigator).

Any idea how this can be achieved and sent to PinPoint?

**Comment by iartemiev** [comment]
Any time an event is recorded in Pinpoint, it will include a timestamp. I don't think there's a way to achieve your exact use case via the Pinpoint console, but you can try exporting the data and then taking the difference between the timestamps for `_session.start` and `_session.stop` events.
