### ISSUE TITLE
Typescript: can no longer access AuthClass

### ISSUE THREAD

**Issue by lambda0xff** [aws-amplify/amplify-js#5319]
**Describe the bug**
In a typescript project, I need to have access to AuthClass  in order to subclass them.

In previous versions of aws-amplify, `import { AuthClass } from 'aws-amplify'` would work.
With the latest release, this doesn't work anymore.

I don't have the same issue with APIClass or StorageClass.

**Comment by lambda0xff** [comment]
In the published module, it seems it can be fixed easily:

1. In `node_modules/aws-amplify/lib-esm/index.d.ts` replace line 3 with:
`export { Auth, AuthClass } from '@aws-amplify/auth';`

2. In `node_modules/@aws-amplify/auth/lib-esm/index.d.ts`:
```
import { Auth, AuthClass, CognitoHostedUIIdentityProvider } from './Auth';
import { CognitoUser, CookieStorage, appendToCognitoUserAgent } from 'amazon-cognito-identity-js';
/**
 * @deprecated use named import
 */
export default Auth;
export { Auth, CognitoUser, AuthClass, CookieStorage, CognitoHostedUIIdentityProvider, appendToCognitoUserAgent };
```

**Comment by Amplifiyer** [comment]
Hi @lambda0xff, I wanted to understand your use case of extending the AuthClass. These internal Amplify classes are supposed to be singleton and instantiated once (when you import through `@aws-amplify/auth`) and that's why we wanted to remove these exports for public consumption.

But I want to learn more about the use cases that require these classes and if there are other ways to solve such use cases.

**Comment by lambda0xff** [comment]
Hello @Amplifiyer , my use case is simple: testing.

When using the amplify framework, I wrap classes like Auth, API and Storage in "service classes"

For instance (pseudo-code)
```ts
class ServiceAuth {
  authClass: AuthClass

  constructor(authClass: AuthClass) {
    this.authClass = authClass
  } 

  signIn(...) {
    // do other stuff
    return this.authClass.signIn(...)
  }
}
```
Then when writing tests for my ServiceAuth class I can inject a mock authClass object.  In order to create that mock object, I need to have access to the Auth object's class:

```ts
class MockAuth extends AuthClass {
  signIn(...) {
    return Promise.whatever(...)
  }
}
```

ps: I think just exposing an interface could also work, but may be a major pain because that would require users to implement each and every method, so exposing the class is much better

**Comment by greimela** [comment]
We ran into the same issue and fixed it by using `typeof Auth` instead of `AuthClass`.

**Comment by lambda0xff** [comment]
hello @greimela 
I remember trying that as well but it didn't work for me.  For instance, I tried
```ts
type AuthClass = typeof Auth
export class MockAuth extends AuthClass {}
```
but I get the following typescript error: `'AuthClass' only refers to a type, but is being used as a value here.`
Did you try something else ?

**Comment by greimela** [comment]
Oh, I missed your second code snipped. 

You can not extend `typeof Auth` since it is no class itself.
However, you can just create a mock object that looks like `Auth`:

```
type AuthClass = typeof Auth
const MockAuth: AuthClass = {
  signIn: (...) => Promise.resolve("mocked")
}
```

**Comment by lambda0xff** [comment]
@greimela 
I may have done something wrong, but that still doesn't seem to work for me:
```ts
import { Auth } from 'aws-amplify'

type AuthClass = typeof Auth

const MockAuthClass: AuthClass = {
  signIn(usernameOrSignInOpts: string, pw?: string | undefined) {
    return Promise.resolve("value")
  }
}
```
will have the compiler complain with the following message: `Type '{ signIn(usernameOrSignInOpts: string, pw?: string | undefined): Promise<string>; }' is missing the following properties from type 'AuthClass': _config, userPool, user, _oAuthHandler, and 51 more.`

**Comment by ericclemmons** [comment]
Hey there @lambda0xff,

I created a demo of how you can mock `signIn` using a service layer:
> https://codesandbox.io/s/amplify-jsissues5319-dvu7v?file=/src/App.tsx

The key takeaways with this approach are:

• Amplify provides singletons (e.g. `Auth`) over instantiation (via `new AuthClass`), primarily for configuring via `Amplify.configure`.
• `AuthClass` is being upgraded, so relying on implementation details is risky to depend on. This is true for the underlying Storage & API classes as well.
• Using a "service layer" is fine architecturally, so moving the mocking to the service-layer rather than the Auth should work (see codesandbox).
• Types should work as-is, or at least via `typeof Auth` (thanks @greimela).
• When testing, tools like [Jest](https://jestjs.io/docs/en/mock-functions.html#mocking-modules) & [Sinon](https://sinonjs.org/) are best suited for mocking & stubbing functions.

Let me know if this resolves things for you!

**Comment by lambda0xff** [comment]
hello @ericclemmons,
Thank you so much for your detailed answer. Just a few remarks if I may.

As you pointed in your example, using a service layer is great since it allows to test an app with mock services and I'm already doing that.

However, I also need to be able to unit test the service itself because in many cases, the service is more than just a wrapper around the 'working class'; for example, the `signIn` method of the service could do more than just call the signIn method on the Auth object. For instance:

```ts 
signIn = (...args) => {
  return this.auth.signIn(...args)
    .then( /* do something with returned user */)
    .catch(/* do something with the error */)
}
```

In order to do that, I need to be able to mock the Auth object:

1. by using Jest or Sinon as you suggested, or
2. by writing a very simple and basic mock class by subclassing AuthClass 

It is of course just a matter of personal preference, but I much much prefer writing my own extremely simple mocks rather than using "blackboxes" provided by frameworks, as good as they may be.

That's why for me and maybe others, it would be great if classes like Auth, API and Storage could continue to be available for subclassing: the upside would be to able to continue writing simple tests using simple mocks and I'm not too sure about any downside ?

If for some reason you are strongly opposed to keeping these classes available for public consumption, maybe providing public interfaces for them could be a reasonable trade off ?

Thanks

**Comment by ericclemmons** [comment]
I hear you.  I'm the same way when it comes to adopting new tools vs. a simpler, hand-rolled solution.

To be honest, my first solution actually did `Auth.signIn = async () => ...mock...`. Would that work?

The issue for us allowing subclassing is that it breaks the singleton pattern we rely on through all categories, depended on by `Amplify.configure`, where we could no longer guarantee that your subclass is behaving the way the original singleton would.  I definitely don't want your tests seeing different behavior than the live app 😅

**Comment by lambda0xff** [comment]
@ericclemmons 
I'm not too sure I understand what you mean with: `Auth.signIn = async () => ...mock...`  It's getting late where I am so it's probably me. Sorry :)

I see your point re Singleton pattern.  In that case, as I suggested, maybe the cleanest solution would be to provide public interfaces because:

1. we can implement the Singleton pattern
2. the interfaces being public, I can create mock objects implementing the interfaces instead of creating subclasses

**Comment by ericclemmons** [comment]
@lambda0xff I updated https://codesandbox.io/s/amplify-jsissues5319-dvu7v?file=/src/App.tsx:135-461 with my suggestion, which is basically _overriding_ `Auth.signIn` (or any call your app would normally make) with a mock function:

```tsx
class AuthService {
  auth: typeof Auth;

  constructor(auth) {
    this.auth = auth;
  }

  signIn = (...args) => {
    return this.auth.signIn(...args);
  };
}

class MockService extends AuthService {
  constructor(auth) {
    super(auth)

	// 👇 Replacing signIn with my mock function
    this.auth.signIn = async () => {
      return { name: "Mock User" }
    }
  }
}
```

You can consider `Auth` to be the public, typed interface for mocking & overriding as you see fit for testing.

The main difference is that the instantiation happens once by Amplify vs. in your code (by extending `AuthClass`).

You should be able to accomplish what you need without extending `AuthClass` using one of the techniques I've listed above.

**Comment by lambda0xff** [comment]
@ericclemmons
Oh, now I see what you mean.  It's a nice way to go around our problem here, eventhough we may end up doing a lot (too much ?) in the constructor.  I would also have to look at it with more complex setups and tests.

In the meantime, I may have found a solution based on @greimela input by using Typescript's `Partial`:
```ts
type AuthClass = typeof Auth 
const MockObject: Partial<AuthClass> = {
  signIn: (...args) => Promise.resolve(),
  signUp: (...args) => Promise.reject(),
}

class MockClass implements Partial<AuthClass> {
  signIn(username: string, pwd: string) {
    return Promise.resolve()
  }
}
```

I'll probably go with this for the moment, but if we take a step back don't you think all the different tentative "solutions" (hacks ?) that we've come up with here are in fact just trying to 'code our way around' the fact that there are no public interfaces for the Auth, API and Storage classes ?

Wouldn't it be much nicer to have public interfaces for these classes ?
```ts 
export interface AuthInterface {
    signUp: (args: any) => Promise<any>
    login: (args: any) => Promise<any>
}

class AuthSingleton implements AuthInterface {
    private static instance: AuthSingleton;
    private constructor() { }

    public static getInstance(): AuthSingleton {
        if (!AuthSingleton.instance) {
            AuthSingleton.instance = new AuthSingleton();
        }

        return AuthSingleton.instance;
    }

    signUp(args: any) {
        return Promise.resolve()
    }
    login(args: any) { 
        return Promise.resolve()
    }
}

class MockAuth implements AuthInterface {
    signUp(args: any) { return Promise.resolve("mock value") }
    login(args: any) { return Promise.resolve("mock value")}
}
```
I understand you guys are doing some major refactoring work, so it may be a good opportunity to introduce this ?

**Comment by ericclemmons** [comment]
@lambda0xff `Partial` is pretty handy in that situation!

I think you're right, there probably is some benefit to having `Auth` implement an `AuthInterface`.

To recap, there were 2 themes in this thread:

1. Exporting `AuthClass` for instantiation.
1. Leveraging TypeScript's `Partial` or `typeof` when overriding/mocking/stubbing `Auth`

Since both needs are around testing and we have a way to work with what's published today, do you think it's fair for me to create a feature request for `AuthInterface` (among others) and close this original issue?

**Comment by lambda0xff** [comment]
Absolutely.  Thanks again for your help @ericclemmons

**Comment by ericclemmons** [comment]
Awesome!  I'll close this issue and start on a feature request for `AuthInterface` 👀

**Comment by severi** [comment]
Any update on the AuthInterface? Not being able to access to AuthClass is currently blocking us from upgrading Amplify from version 2.3.0 to the newest one...
