### ISSUE TITLE
Get User attributes using Amplify withAuthenticator on signUp

### ISSUE THREAD

**Issue by sri7vasu** [aws-amplify/amplify-js#5328]
** Which Category is your question related to? **
Auth
** What AWS Services are you utilizing? **
Cognito
** Provide additional details e.g. code snippets **
I'm setting up react-native app with cognito and Amplify withAuthenticator. Trying to get user data on click of signUp. Using Hub right now like this , still on SignUp cant get user email and phone number.

    Hub.listen('auth', (data) => {
      switch (data.payload.event) {
        case 'signIn':
           console.log('Confirmed Signed In')
          break;
        case 'signIn_failure':
          this.setState({ authState: 'signIn', authData: null, authError: data.payload.data });
          break;
        case 'signUp':
          console.log('user signed up' + data.payload.data.codeDeliveryDetails.Destination);
          //TODO Code here to insert into Database
          break;
        case 'confirmSignUp':
          console.log('Confirmed sign up')
          break;
        case 'signOut':
          console.log('user signed out');
          break;
        case 'signIn_failure':
          console.log('user sign in failed');
          break;
        case 'configured':
          console.log('the Auth module is configured');
          break;
        default:
          break;
      }
    });

Email is not in plain text as shown in the image, its with asteriks. Is there a different event i need to listen through Hub ? Or is there a code snippet i can use to capture signUp event and read user attributes from the form ? 
<img width="1018" alt="Screen Shot 2020-04-07 at 6 09 48 PM" src="https://user-images.githubusercontent.com/5733652/78732684-dfd1f680-7908-11ea-926d-2472bd297be5.png">

**Comment by sri7vasu** [comment]
I tried something like this as well to capture signUp event but its not hitting the method

class App extends React.Component {
signUp = async () => {
    try {
      await Auth.signUp({
        username, 
        password, 
        attributes: { email, phone_number }
      })
        .then(user => console.log("signup info:" + user))
    }
    catch (err) {
      console.log('error signing up user...', err)
    }
  }
}

**Comment by amhinson** [comment]
@sri7vasu Depending on your Amplify configuration, you won't be able to get the user attributes immediately after sign up until the user is confirmed. Then you should be able to get the attributes after sign in, either using the UI provided by `aws-amplify-react-native` or calling `Auth.signIn` explicitly.
