### ISSUE TITLE
How to fix “A client attempted to write unauthorized attribute” issue in cognito? in react-native custom UI(It works fine with default signUP screen))

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#5345]
I am customizing the UI for signUp screen. I got an error as A client attempted to write unauthorized attribute. Here I have used the attributes as mentioned below.

**Note:** Before I have used the default screens with the below-mentioned attributes from the aws-amplify-react-native. Now also I have the same attributes, but it failed to signUp.

**Attributes:**

```
AuthClass - signUp attrs:', [ { Name: 'name', Value: 'Test' },
  { Name: 'email', Value: 'XXXXX@domain.com' },
  { Name: 'phonenumber', Value: '+XXXXXXX' } ]
```
**Error:**

```
Hub - Dispatching to auth with ', { event: 'signUp_failure',
  data: 
   { code: 'NotAuthorizedException',
     name: 'NotAuthorizedException',
     message: 'A client attempted to write unauthorized attribute' },
  message: 'xxx@domail.com failed to signup' }
```
**My custom signup screen**

```
class CustomSignUp expends Component {

signUp = () => {
 const { email, password, phonenumber, userName, lastname, validation } = this.state;
   Auth.signUp({
    username: email,
    password,
    attributes: {
        name: userName,
        email: email,          
        phonenumber: phonenumber,
         // optional - E.164 number convention
        // other custom attributes
    },
    })
    .then(data => console.warn("ddddddddd"+ data))
    .catch(err =>{
      console.warn('errrr' + err)
      validation.messages.push(err.message);
    }
    );

render () {
  return (
   <Button onPress={this.signUp}>SignUP</Button>
 )
}
}
```
**My Authenticator:**

```
<Authenticator>
   <CustomSignUP override={'SignUp'}
</Authenticator>
```

**Comment by amhinson** [comment]
Hey @nihp, could you go into the Cognito User Pool app client settings and see if all of the attributes you're trying to write are enabled?

General settings -> App clients -> Show details -> Set attribute read and write permissions link

Also, can you confirm that you're using the `custom:` prefix for the custom attributes in your code?

Reference: https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#user-pool-settings-custom-attributes

**Comment by nihp** [comment]
Yes, I found

I have used phonenumber insatead of phone_number

Can you clarify this another thing it will be helpful for me.

1. Error message is retaining in the same screen if I go back to the previous screen(Which shows an error before)
 
**Steps:**
   1. Launch app shows login screen 
   2. Then not enter user name it will shows error (Username cannot be empty)
   3. Then click on the Forgot Password
   4. Then click Back to signIn (It will navigate to SignIn screen)
   5. Here it shows the error message (Username cannot be empty)

2. How can I pass params while onStateChange in the 
`this.props.onStateChange('signIn',{});`

**Comment by amhinson** [comment]
This sounds like another unrelated issue. Could you create a new issue so we can have a more focused discussion around that?

**Comment by nihp** [comment]
For [2] I already created a ticket but no reply from anyone. 
https://github.com/aws-amplify/amplify-js/issues/5143

If you have any idea kindly let me know. It will be useful for me
