### ISSUE TITLE
federatedSignIn fails after sign-out

### ISSUE THREAD

**Issue by nirLumigo** [aws-amplify/amplify-js#5346]
**Describe the bug**
We use Cognito and we’re adding the option to sign in into our platform using Google accounts.
On the client-side we use aws-amplify@2.3.0.
For sign-in with google we use `Auth.federatedSignIn({   provider: CognitoHostedUIIdentityProvider.Google  })`.
For sign-out the user we use `Auth.signOut()`.
Usually it works fine, but sometimes we encounter a problem, we don’t know exactly how to reproduce it but it usually happens after a user sign-in with username+password, then sign-out and then sign-in with a Google account for the first time.
The problem is that `federatedSignIn` isn’t working, we’re getting messages like:
- “Logins don’t match. Please include at least one valid login for this identity or identity pool.”
- From the call to the token we get “invalid_request”.
- From the call to cognito.idp we get 400.
- We also get “customState_failure” - “invalid_request”

When we manually tried to delete the cache of the browser, it seemed that the problem was solved and we weren’t able to reproduce the problem again.
It happened in Chrome browser.

**To Reproduce**
We don’t know exactly how to reproduce it but it usually happens after a user sign-in with username+password, then sign-out and then sign-in with a Google account for the first time.
When we manually tried to delete the cache of the browser, we weren’t able to reproduce the problem again.

**Expected behavior**
`federatedSignIn` won't throw errors and the user will be able to sign-in.

**Comment by jordanranz** [comment]
Hey @nirLumigo,

Does `federatedSignIn` work in if done before a user sign-in with username+password?

**Comment by nirLumigo** [comment]
@jordanranz
We weren't able to try it because the cache was deleted so we can't reproduce it again.

**Comment by VXConsulting** [comment]
Hello,

We have exactly the same problem. 
We can reproduce it each time on some computers but not all machines are impacted.

First we have the 400.
We refresh the page.
Application asks again for authentication.
And then, it works.

We identified that the problem is for the first time, when the problem happens, the code-verifier is not attached to the token request.

Seems that :
`const code_verifier = oAuthStorage.getPKCE();`
is not working.

**Comment by VTSingle** [comment]
same error. Need help, pls

**Comment by Amplifiyer** [comment]
@VXConsulting and @VTSingle are you also able to reproduce after clearing your browser cookies and cache? If yes, can you put together a small repro app which we can clone and try to reproduce here? Without that it will be impossible for us to debug.

**Comment by VTSingle** [comment]
@VXConsulting @nirLumigo  I have news. I created new project with same setting but without splash screen and all functionality working correct. Than I opened my main project and deleted splash screen from him and all functionality working correct. 
@nirLumigo @VXConsulting My suggestions - try to delete splash screen from you project
