### ISSUE TITLE
Upload Remote Image to S3

### ISSUE THREAD

**Issue by karrettgelley** [aws-amplify/amplify-js#5348]
** Which Category is your question related to? **
Storage

** What AWS Services are you utilizing? **
S3 Bucket

** Provide additional details e.g. code snippets **
How can I fetch an image from a url and then upload it to s3? For instance, if I want to save an image at example.com/someimage to my s3, how can I fetch the remote image and then upload it?

edit: In general, is it best practice to save the image file itself in S3, or just to save the url? I am trying to do the former with a remote image, but I'm curious as to what is commonly done

**Comment by Quix0tic** [comment]
I think you could either download the image on the user browser (if you have a website and the users have access to S3) or trigger a lambda function with the URL to download and save the image to S3 (which I think is preferred)

**Comment by mauerbac** [comment]
This looks to be more specific to S3 in general and not Amplify Framework. We recommend to ask this question via [AWS Forums for Storage](https://forums.aws.amazon.com/category.jspa?categoryID=23). However, it looks like @Quix0tic's comment looks to solve your issue, we are resolving this as the above comment and based on our recommendation that this seems to be S3 specific and not Amplify. Please let us know if this is not the case and we can reopen this question. Thanks!
