### ISSUE TITLE
Cannot pass theme.sectionFooterContent for SectionFooterContent styling

### ISSUE THREAD

**Issue by Nyazuki** [aws-amplify/amplify-js#5355]
```
<SectionFooter theme={theme}>
  <Button type='submit' disabled={loading}>
    Log In
  </Button>
</SectionFooter>
```

SectionFooter will create a new `<span>` child element SectionFooterContent, similar like FormSection that creates a child FormContainer.

```
sectionFooter: {
  marginTop: '35px'
},
sectionFooterContent: {
  display: 'flex',
  flexDirection: 'row',
  justifyContent: 'center'
}
```

the above theme props will apply to SectionFooter but SectionFooterContent will not receive style props in sectionFooterContent, which I believe is a bug.

https://github.com/aws-amplify/amplify-js/blob/50f99713572a4c692c3f4bd9da3a4859093bd9e9/packages/aws-amplify-react/src/AmplifyUI.tsx#L105

this should be `<SectionFooterContent theme={theme}>{props.children}</SectionFooterContent>`

**Comment by jordanranz** [comment]
Fixed merged, thank you for contributing! Please open a new issue if you have any related questions or concerns.
