### ISSUE TITLE
Connect Component Modular Import

### ISSUE THREAD

**Issue by karrettgelley** [aws-amplify/amplify-js#5358]
** Which Category is your question related to? **
API 

** What AWS Services are you utilizing? **
AppSync

** Provide additional details e.g. code snippets **
I'm trying to refactor my code to use the newish modular imports but I can't figure out where the \<Connect\> react component is. How can I import \<Connect\> using modular imports?

**Comment by ashika01** [comment]
@karrettgelley could u provide a sample of ur code and brief a little bit more on what you are trying to achieve?

**Comment by karrettgelley** [comment]
@ashika01 I'm just trying to use <Connect> (found in aws-amplify-react) using the modular imports. I'm just not sure which package it was moved to, or is planning to be moved to

**Comment by Amplifiyer** [comment]
@karrettgelley, the `Connect` [component ](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/API/GraphQL/Connect.tsx) from aws-amplify-react has not been moved or refactored. Can you please let us know your code snippet along with the errors you are facing with the new version of the library?

The only caveat is that if you are importing aws-amplify-react and not importing Amplify in the same file, it may cause some issues. See https://github.com/aws-amplify/amplify-js/issues/5458 for reference

**Comment by karrettgelley** [comment]
I was hoping to be able to use <Connect> with `@aws-amplify/core` or `@aws-amplify/api`. It looks like it will be a part of `@aws-amplify/ui-react` eventually, but I've moved on. Thanks anyways
