### ISSUE TITLE
amplify-ui-components @aws-amplify/ui-vue Signup formFields not respected

### ISSUE THREAD

**Issue by valtrem** [aws-amplify/amplify-js#5363]
** Which Category is your question related to? **
amplify-ui-components

** What AWS Services are you utilizing? **
DataStore, Cognito, S3,

** Provide additional details e.g. code snippets **

"dependencies": {
    "@aws-amplify/core": "^3.2.1",
    "@aws-amplify/datastore": "^2.0.5",
    "@aws-amplify/ui-vue": "^0.2.2"
}

```
<template>
  <div>
    <amplify-authenticator username-alias="email">
      <amplify-sign-in
        :username-alias="signInConfig.usernameAlias"
        slot="sign-in"
      />
      <amplify-sign-up
        :header-text="signUpConfig.headerText"
        :username-alias="signUpConfig.usernameAlias"
        :form-fields="signUpConfig.formFields"
        slot="sign-up"
      />
    </amplify-authenticator>
  </div>
</template>
```
```
<script lang="ts">
import Vue from "vue";
export default Vue.extend({
  data: () => ({
    signInConfig: {
      usernameAlias: "email"
    },
    signUpConfig: {
      headerText: "TEST",
      usernameAlias: "email",
      formFields: [
        { type: "email", label: "Email" },
        { type: "password" },
        { type: "username" }
      ]
    }
  })
});
</script>
```
```
<style lang="scss">
:root {
  --amplify-primary-color: var(--v-primary-base);
}
</style>
```
![image](https://user-images.githubusercontent.com/4313339/79020641-5f4d0900-7b47-11ea-94ab-51fcea5f1acc.png)

Expected behaviour :
With the provided example above, I would expect the Email field label to read 'Email' and wouldn't expect the phone field to be present at all. 

What is the proper way to use formFields with amplify-ui-components for Vue ?

**Comment by ashika01** [comment]
@valtrem - I guess you issue is related to this https://github.com/aws-amplify/amplify-js/issues/5298.  We are investigating to enable this function.

**Comment by valtrem** [comment]
Hi @ashika01, 
Yes, It's probably related. 

Please note I can't get this to work even if I remove username-alias prop.

The formFields simply don't seem to be taken into account at all.

**Comment by ashika01** [comment]
@valtrem yeah we are aware of this. we configured our UI to spin up formfields based on `usernameAlias` which is defaulted to `username`. we are revamping that to check for the required login fields and then to allow other fields to be customizable.

**Comment by ashika01** [comment]
I am going to close this ticket and track this with #5298. Please feel free to comment on that issue for more info.

**Comment by albertbenitez** [comment]
Is this fixed in PD? I'm having the same issue with Vue still.

**Comment by ashika01** [comment]
@albertbenitez it should work in unstable. we will be doing release soon and update in the issue tracked.

**Comment by albertbenitez** [comment]
@ashika01 maybe @valtrem can verify but I've tried with:
Dependencies": @aws-amplify/ui-vue": "^0.2.3-unstable.35"
And it still doesn't work, but I can wait for the stable version to try again.

Tried with:
```
<template>
		<amplify-authenticator :federated="signInConfig.federatedConfig">
			<amplify-sign-up
				:header-text="signUpConfig.headerText"
				:form-fields="signUpConfig.formFields"
				:submit-button-text="signUpConfig.submitButtonText"
				:username-alias="signUpConfig.usernameAlias"
				slot="sign-up"
			></amplify-sign-up>
		</amplify-authenticator>
</template>
```

```
export default {
	data() {
		return {
			signUpConfig: {
				headerText: 'Test',     //working
				usernameAlias: 'email',   //working
				submitButtonText: 'test button',   //working
				formFields: [   // NOT working
					{ type: 'username', label: 'Email Label', required: true },
					{ type: 'password', label: 'Pass Label Text', placeholder: 'placetext', required: true },
				],
			},
		};
	},
}
```

**Comment by ashika01** [comment]
@albertbenitez I got this issue too. Looks like its the flow between stencil and vue. Could you try this? I guess it should solve your problem.

```
<amplify-sign-up
				:form-fields.prop="signUpConfig.formFields"
				slot="sign-up"
			></amplify-sign-up>
```

Make the change in your template from `:form-fields` to `:form-fields.prop`

**Comment by albertbenitez** [comment]
Yes, that solved the issue! **Thank you**

**Comment by mstein11** [comment]
This still does not seem to work in vue3 with the `@aws-amplify/ui-components` library. I trief both `:form-fields.prop="signUpConfig.formFields"` and `:form-fields="signUpConfig.formFields" but neither is working.

**Comment by armenr** [comment]
Still happening to me as well. Any help would be much appreciated!

Vue3  + @aws-amplify/ui-components

This doesn't work
```
      <!--eslint-disable-next-line vue/no-deprecated-slot-attribute ! -->
      <amplify-sign-up slot="sign-up"
        username-alias="username"
        :form-fields.prop="formFields"
      >
      </amplify-sign-up>
```

This doesn't work either

```
      <!--eslint-disable-next-line vue/no-deprecated-slot-attribute ! -->
      <amplify-sign-up slot="sign-up"
        username-alias="username"
        :form-fields.prop="signupConfig.formFields"
      >
      </amplify-sign-up>
```

I have the following in my setup:

```
app.config.isCustomElement = tag => tag.startsWith('amplify-')
```

AND in my webpack:

```
      chainWebpack: config => {
        config.module
          .rule('vue')
          .use('vue-loader')
          .loader('vue-loader')
          .tap(options => {
            options.compilerOptions = {
              ...(options.compilerOptions || {}),
              isCustomElement: tag => tag.startsWith('amplify-')
            };
            return options;
          });
      }
```

**Comment by armenr** [comment]
For what it's worth, the following seems to work with Vue3 + TypeScript (using Quasar V2 Beta)

```
      <amplify-sign-up
        header-text="Sign Up Now!"
        slot="sign-up"
        username-alias="email"
        :formFields="formFields"
      ></amplify-sign-up>
```

**Comment by ElvisLzw** [comment]
> Still happening to me as well. Any help would be much appreciated!
> 
> Vue3 + @aws-amplify/ui-components
> 
> This doesn't work
> 
> ```
>       
>       <amplify-sign-up slot="sign-up"
>         username-alias="username"
>         :form-fields.prop="formFields"
>       >
>       </amplify-sign-up>
> ```
> 
> This doesn't work either
> 
> ```
>       
>       <amplify-sign-up slot="sign-up"
>         username-alias="username"
>         :form-fields.prop="signupConfig.formFields"
>       >
>       </amplify-sign-up>
> ```
> 
> I have the following in my setup:
> 
> ```
> app.config.isCustomElement = tag => tag.startsWith('amplify-')
> ```
> 
> AND in my webpack:
> 
> ```
>       chainWebpack: config => {
>         config.module
>           .rule('vue')
>           .use('vue-loader')
>           .loader('vue-loader')
>           .tap(options => {
>             options.compilerOptions = {
>               ...(options.compilerOptions || {}),
>               isCustomElement: tag => tag.startsWith('amplify-')
>             };
>             return options;
>           });
>       }
> ```

I still have this problem, do you solve it?

**Comment by ElvisLzw** [comment]
I still have this issue when using Vue3 + @aws-amplify/ui-components

**Comment by ElvisLzw** [comment]
I do not know why but when I set a timeout it can work
Vue3 + @aws-amplify/ui-components
```
<amplify-authenticator username-alias="email">
  <amplify-sign-up
    header-text="Sign Up Now!"
    slot="sign-up"
    :formFields="formFields"
  ></amplify-sign-up>
  <amplify-sign-out></amplify-sign-out>
</amplify-authenticator>
```
```
data() {
  return {
    user: undefined,
    authState: undefined,
    unsubscribeAuth: undefined,
    formFields: []
  }
},
mounted() {
  setTimeout(() => {
    this.formFields = [
          {
            type: "email",
            required: true,
          },
          {
            type: "password",
            required: true,
          },
          {
            type: "given_name",
            label: "First Name *",
            placeholder: "First Name",
            required: true,
          },
          {
            type: "family_name",
            label: "Last Name *",
            placeholder: "Last Name",
            required: true,
          },
        ]
  }, 1);
}
```

**Comment by yeus** [comment]
is there any update on this? I can not get formFields to work with any of the above solutions..  using Vue3 (quasar app 3.1.0), aws-amplify@4.2.10, @aws-amplify/ui-components@1.7.9,     vue "3.2.4",  vue-loader "16.4.1"

and why is this closed? doesn't seem to be any solution here on this issue...  And the other issue #5928 doesn't seem to be resolved either ... This is very frustrating.
