### ISSUE TITLE
Require cycles in amplify libs

### ISSUE THREAD

**Issue by andreialecu** [aws-amplify/amplify-js#5371]
**Describe the bug**

We've noticed the following warnings being logged:

![image](https://user-images.githubusercontent.com/697707/79049672-b1685a00-7c2d-11ea-8bb0-ca653353052d.png)

It seems that under certain circumstances, this can lead to this problem: https://github.com/aws-amplify/amplify-js/issues/4859

**Expected behavior**

No require cycles should exist.

**Comment by andreialecu** [comment]
This specific line of code can result in a lot of problems:

https://github.com/aws-amplify/amplify-js/blob/c28851a6379f3ba05c4fef529bb5be7f18ebe316/packages/predictions/src/types/Providers/AbstractConvertPredictionsProvider.ts#L12

If the babel config is set up to allow path aliases, or a different `module-resolver` root is configured (see https://github.com/aws-amplify/amplify-js/issues/4859#issuecomment-612462602) the wrong module will be imported.

I assume there are other scenarios where things could blow up because of require cycles, as seen from the reports in #4859 and #4687

**Comment by lucianomlima** [comment]
Same here!

**Comment by yumsquare** [comment]
Same warnings here as well.
