### ISSUE TITLE
S3: header errors when uploading file

### ISSUE THREAD

**Issue by lambda0xff** [aws-amplify/amplify-js#5376]
**Describe the bug**
When uploading a file to S3, I get error/warning messages from the browser:
`Refused to set unsafe header "content-length"`
`Refused to set unsafe header "host"`
in chrome 

`Attempt to set a forbidden header was denied: content-length`
`Attempt to set a forbidden header was denied: host`
if firefox

**To Reproduce**
Using the `aws-amplify` library: `storageClass.put(key, blob, { level, contentType: type, cacheControl: 'max-age=31536000'}))
`
and CORS settings in S3:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>HEAD</AllowedMethod>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <ExposeHeader>x-amz-server-side-encryption</ExposeHeader>
    <ExposeHeader>x-amz-request-id</ExposeHeader>
    <ExposeHeader>x-amz-id-2</ExposeHeader>
    <ExposeHeader>ETag</ExposeHeader>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```

PS: let me add that the image is successfully uploaded to S3

**Comment by juuyan** [comment]
Same here. Any updates? What is the latest safe version with which these errors could be avoided?

**Comment by thebarada** [comment]
same here

**Comment by carlosortizpacheco** [comment]
Same here

**Comment by crolly** [comment]
same here

**Comment by chekodev** [comment]
same here

**Comment by Amplifiyer** [comment]
The issue is when the list operation returns empty results. I've a PR opened to correctly handle that case. Thanks everyone for providing the necessary information to fix this.

**Comment by Amplifiyer** [comment]
The fix will be soon available on an unstable version of aws-amplify and on a stable version when we do a production release.

**Comment by smkim02** [comment]
> **Describe the bug**
> When uploading a file to S3, I get error/warning messages from the browser:
> `Refused to set unsafe header "content-length"`
> `Refused to set unsafe header "host"`
> in chrome
> 
> `Attempt to set a forbidden header was denied: content-length`
> `Attempt to set a forbidden header was denied: host`
> if firefox
> 
> **To Reproduce**
> Using the `aws-amplify` library: `storageClass.put(key, blob, { level, contentType: type, cacheControl: 'max-age=31536000'})) `
> and CORS settings in S3:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
> <CORSRule>
>     <AllowedOrigin>*</AllowedOrigin>
>     <AllowedMethod>HEAD</AllowedMethod>
>     <AllowedMethod>GET</AllowedMethod>
>     <AllowedMethod>PUT</AllowedMethod>
>     <AllowedMethod>POST</AllowedMethod>
>     <AllowedMethod>DELETE</AllowedMethod>
>     <MaxAgeSeconds>3000</MaxAgeSeconds>
>     <ExposeHeader>x-amz-server-side-encryption</ExposeHeader>
>     <ExposeHeader>x-amz-request-id</ExposeHeader>
>     <ExposeHeader>x-amz-id-2</ExposeHeader>
>     <ExposeHeader>ETag</ExposeHeader>
>     <AllowedHeader>*</AllowedHeader>
> </CORSRule>
> </CORSConfiguration>
> ```
> 
> PS: let me add that the image is successfully uploaded to S3

same here

**Comment by jingxizhang** [comment]
I am having the same issue, however, in downloading (instead of uploading file) from S3:
`const data = await Storage.get(key, {download: true})`
I got:
`xhr.js:126 Refused to set unsafe header "host"`
The file is successfully downloaded.

**Comment by edreinoso** [comment]
Any updates on the fix for this issue? I'm having the same trouble when trying to upload a file using Storage.put()

**Comment by Amplifiyer** [comment]
@edreinoso  are you facing this issue even with latest Amplify version? (Make sure to delete your lock files and node_modules )

**Comment by edreinoso** [comment]
@Amplifiyer thanks for the quick response.

I'm using this version of Amplify

├── aws-amplify@3.0.8
├── aws-amplify-vue@2.1.1

Based on the thread and your previous message, I'm assuming that I would have to update to a newer version.

**Comment by edreinoso** [comment]
Just tried updating to a newer version
aws-amplify@3.0.11

It worked when putting objects into a bucket.

Thanks @Amplifiyer

**Comment by mariomerlano** [comment]
Still having the same error in react.

- "aws-amplify": "^3.0.12"

Please get this issue prioritized.
