### ISSUE TITLE
couple of issues when using aws-amplify@3.0.7 and aws-amplify-react@4.1.6

### ISSUE THREAD

**Issue by smoothwood** [aws-amplify/amplify-js#5378]
In my amplify project I used **npm install aws-amplify aws-amplify-react** to install below two libraries
+ aws-amplify@3.0.7
+ aws-amplify-react@4.1.6

Then I observed below issues.

Issue 1: 
I used **amplify add auth** to enable authentication, but the default Sign Up page is not the same as usual (amazon default styling), now there is no any styling applied to that page.

Issue2: 
I used **amplify add storage** to enable S3 and made a simple file uploading page, the file can be uploaded to S3 SUCCESSFULLY, however I saw below two errors in Chrome console
 - Refused to set unsafe header "content-length"
 - Refused to set unsafe header "host"

Issue3:
I used **amplify mock** to start local mocking
while uploading file, in Chrome console, I saw below error and file was not uploaded
error message PUT https://localhost:20005/bucket-name/public/1.png?x-id=PutObject net::ERR_SSL_PROTOCOL_ERROR

After I switched to 
    "aws-amplify": "^2.3.0"
    "aws-amplify-react": "^3.1.9"

All above issues gone

**To Reproduce**
Install 
+ aws-amplify@3.0.7
+ aws-amplify-react@4.1.6

- add auth and storage

- start local mocking

**Expected behavior**
1. Sign Up page showing with default amazon styling
2. Error messages in Issue2 should not be showed
3. file could be uploaded to local directory when using local mocking

**Comment by Amplifiyer** [comment]
@smoothwood 
Issue #1 is a breaking change with amplify V3: https://github.com/aws-amplify/amplify-js#amplify3xx-has-breaking-changes-please-see-the-breaking-changes-below
Issue #2, we are looking into it
Issue #3: Same as https://github.com/aws-amplify/amplify-js/issues/5320

**Comment by Amplifiyer** [comment]
Marking this as duplicate and closing. Please follow up on the related issues.
