### ISSUE TITLE
Slow Auth signin performance: perform user and device auth in parallel?

### ISSUE THREAD

**Issue by tomquisel** [aws-amplify/amplify-js#538]
Do you want to request a feature or report a bug?
bug

What is the current behavior?
When `Auth.signIn` is called, signIn takes just under 2 seconds to complete, even with a fast connection. This is primarily because user auth and then device auth happen in series rather than in parallel.

To reproduce:
call `Auth.signIn` for a user pool that has device remembering on, and watch the Network pane in Chrome devtools. You should see something like [this](https://drive.google.com/file/d/1TqPPjeMKYKFi4yFhTvkKO08ZbDz7LK5h/view?usp=sharing). The first two calls are user auth, the second two calls are device auth. The last two calls are loading userid and attributes.

What is the expected behavior?
User auth and device auth would happen in parallel, shaving about 700ms off signIn time.

**Comment by manhnq94** [comment]
I got the same "issue", it take too slow (about 2-3s) to authenticate an user using Amplify.Auth.signIn function.

Does anybody have idea how to improve this?

**Comment by Pruxis** [comment]
We have the same, it's absurdly slow

**Comment by harrysolovay** [comment]
This is a service issue, as opposed to the a client issue.

When you mention device auth, I'm assuming you mean the device SRP handshake (executed under the hood as an [`InitiateAuth`](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html) request) followed by several [`RespondToAuthChallenge`](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_RespondToAuthChallenge.html) requests?

Sadly there's no getting around the handshakes. This is the correct protocol. You can disable these advanced security mechanisms if you so choose. For instance, a minimal `USER_PASSWORD_AUTH` flow.
