### ISSUE TITLE
The URL response from Storage.get doesn't render image in React-Native

### ISSUE THREAD

**Issue by TamsynJennifer4** [aws-amplify/amplify-js#5380]
**Describe the bug**
The response from

`Storage.get(key,
        {
            level: 'protected',
  })`

is a URL that doesn't render an image in React-Native.

When pasting the URL in a web browser (Chrome) it returns an error saying the key does not exist. 

When I click on the image in the s3 console and click "open" it opens a new tab with the image which I can see/ download. If I paste this URL in a React-Native Image component then it does render the image. 

The URL which is returned from Storage.get is similar but not the same URL as when opening the image from the console. 

**To Reproduce**

1. ` Storage.put(key, blob, {
        contentType: 'image',
        level: 'protected',
     })
`
2. Check the image is in the s3 bucket
3. ` const responseUrl = await Storage.get(key, {
          level: 'protected',
     })`
4. `<Image
          source={{ uri: responseUrl }}
          style={{ height: 100, width: 100 }}
          resizeMode="cover"
      />`

**Expected behavior**
I expect the image to render in React Native after I give the responseUrl to the <Image /> component.

<details>
  <summary><strong>Environment</strong></summary>

```
 System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 610.84 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 80.0.3987.163
    Safari: 13.0.5
  npmPackages:
    @aws-amplify/api: ^2.2.1 => 2.2.1 
    @aws-amplify/pubsub: ^2.1.9 => 2.1.9 
    @babel/core: ^7.9.0 => 7.9.0 
    @babel/preset-env: ^7.9.0 => 7.9.0 
    @babel/preset-flow: ^7.9.0 => 7.9.0 
    @babel/runtime: ^7.9.2 => 7.9.2 
    @react-native-community/cameraroll: ^1.5.2 => 1.5.2 
    @react-native-community/netinfo: ^5.7.0 => 5.7.0 
    amazon-cognito-identity-js: ^3.2.6 => 3.2.6 
    aws-amplify: ^2.3.0 => 2.3.0 
    aws-amplify-react-native: ^2.3.3 => 2.3.3 
    babel-eslint: ^10.1.0 => 10.1.0 
    babel-jest: ^24.9.0 => 24.9.0 
    babel-plugin-transform-inline-environment-variables: ^0.4.3 => 0.4.3 
    eslint: ^6.8.0 => 6.8.0 
    eslint-config-airbnb: ^17.1.1 => 17.1.1 
    eslint-import-resolver-react-native: ^0.2.0 => 0.2.0 
    eslint-plugin-flowtype: ^3.13.0 => 3.13.0 
    eslint-plugin-import: ^2.20.2 => 2.20.2 
    eslint-plugin-jest: ^22.21.0 => 22.21.0 
    eslint-plugin-react: ^7.19.0 => 7.19.0 
    eslint-plugin-react-native: ^3.8.1 => 3.8.1 
    flow-bin: ^0.102.0 => 0.102.0 
    graphql-tag: ^2.10.3 => 2.10.3 
    jest: 23.6.0 => 23.6.0 
    metro-react-native-babel-preset: 0.51.1 => 0.51.1 
    moment: ^2.24.0 => 2.24.0 
    moment-with-locales-es6: ^1.0.1 => 1.0.1 
    react: 16.8.6 => 16.8.6 
    react-apollo: ^2.5.8 => 2.5.8 
    react-native: 0.60.5 => 0.60.5 
    react-native-clean-project: ^3.3.0 => 3.3.0 
    react-native-datepicker: ^1.7.2 => 1.7.2 
    react-native-gesture-handler: ^1.6.1 => 1.6.1 
    react-native-image-picker: ^1.1.0 => 1.1.0 
    react-native-keyboard-aware-scroll-view: ^0.8.0 => 0.8.0 
    react-native-linear-gradient: ^2.5.6 => 2.5.6 
    react-native-masked-text: ^1.13.0 => 1.13.0 
    react-native-reanimated: ^1.7.1 => 1.7.1 
    react-native-screens: ^2.4.0 => 2.4.0 
    react-navigation: ^3.13.0 => 3.13.0 
    react-test-renderer: 16.6.3 => 16.6.3 
    uuid: ^3.4.0 => 3.4.0 
  npmGlobalPackages:
    @aws-amplify/cli: 4.17.2
    expo-cli: 3.4.1
    ios-deploy: 1.9.4
    npm: 6.14.4
    react-native-cli: 2.0.1
```

</details>

**Smartphone (please complete the following information):**

- Device: iPhone 11 (Simulator)
- OS: [e.g. iOS 13.3]
- Browser [e.g. Chrome]

**Comment by TamsynJennifer4** [comment]
THIS DOES WORK!! I was just being stupid. It's because I managed to send a different uuid() to appsync and s3 for the key so there was a mismatch.

**Comment by Cakhavan** [comment]
Hi, I was wondering how you fixed this with the different uuid() solution? My app just stopped working all of a sudden and I can't figure out why. I'm getting the proper signed url from storage.get() and if I paste this into a browser the proper object loads. However, if I put the signed url in an image uri, nothing loads.

Just wondering if your issue was similar to this?
