### ISSUE TITLE
Within custom Authenticator, unable to show SignOut without Greetings

### ISSUE THREAD

**Issue by matwerber1** [aws-amplify/amplify-js#5383]
**Describe the bug**

When using `hide={Greetings}` option of a customized `<Authenticator>`, this also unexpectedly hides the `<SignOut>` button, as if the SignOut is nested within Greetings.

I want to be able to show the Greeting without the SignOut button. Actually, what I'm doing is displaying the Authenticator sub-components in different places in my page... so its not that I don't want the SignOut button, but rather I want it decoupled from Greetings so that I can display it in a different location from the Greetings.

**To Reproduce**

1. Create a sample custom authenticator in React JS, and set `hide={Greetings}`.
2. Log in to a user pool using the Authenticator, and notice that after successful sign-in, no <Greeting> is shown (expected), but also no SignOut (unexpected). 

**Expected behavior**
If I hide the <Greetings>, I still want to see the SignOut button.

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages

  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 71.49 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.10.0 - ~/.nvm/versions/node/v11.10.0/bin/node
    npm: 6.14.1 - ~/.nvm/versions/node/v11.10.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 68.4.1
    Safari: 13.1
  npmPackages:
    @material-ui/core: ^4.9.7 => 4.9.7 
    @material-ui/icons: ^4.9.1 => 4.9.1 
    @risingstack/react-easy-state: ^6.2.0 => 6.2.0 
    @testing-library/jest-dom: ^4.2.4 => 4.2.4 
    @testing-library/react: ^9.5.0 => 9.5.0 
    @testing-library/user-event: ^7.2.1 => 7.2.1 
    amazon-cognito-identity-js: ^4.2.0 => 4.2.0 
    aws-amplify: ^2.2.6 => 2.2.6 
    aws-amplify-react: ^3.1.7 => 3.1.7 
    aws-sdk: ^2.653.0 => 2.653.0 
    cross-fetch: ^3.0.4 => 3.0.4 
    jwt-decode: ^2.2.0 => 2.2.0 
    react: ^16.13.1 => 16.13.1 
    react-cookie: ^4.0.3 => 4.0.3 
    react-dom: ^16.13.1 => 16.13.1 
    react-scripts: 3.4.0 => 3.4.0 
    universal-cookie: ^4.0.3 => 4.0.3 
  npmGlobalPackages:
    @aws-amplify/cli: 4.16.1
    ask-cli: 1.7.2
    aws-cdk: 1.26.0
    eslint-config-airbnb: 17.1.0
    eslint-plugin-import: 2.17.3
    eslint-plugin-jsx-a11y: 6.2.1
    eslint-plugin-react: 7.13.0
    eslint: 6.5.1
    npm: 6.14.1
    npmvet: 0.1.5
    npx: 10.2.0
    optimist: 0.6.1
    serverless-artillery: 0.4.7
    serverless: 1.60.4
    ts-node: 8.4.1
    typescript: 3.6.4
```

</details>

**Comment by jordanranz** [comment]
Hey @matwerber1,

`SignOut` is nested inside of the `Greetings` component so this is expected. To clarify, you still want the `Greetings` component to show up with `SignOut` living in a different place or would you just like to manually place the `SignOut` component without the `Greetings`?

FWIW, we just released a new React library that should alleviate some of the customization problems that the `aws-amplify-react` package had. Here is some documentation: https://docs.amplify.aws/ui/auth/authenticator?framework=react. If we can better under

**Comment by matwerber1** [comment]
Hi Jordan, 

Thanks for the info! Yes, I want the Greetings and SignUp to be in different places. 

I am using the custom <Authenticator> component, and to give you an idea of what I'm doing... 

I have a <header>, <body>, and <footer>, and I'm using the custom `<Authenticator>` from the aws-amplify-react library. 

I wrapped the Amplify `<Authenticator>` in a custom component called `<CustomAuthenticator>` which receives a param, `AuthenticatorType`. 

The `<body>` instantiates `<CustomAuthenticator AuthenticationType='body'>, and renders the standard aws-amplify-react `<Authenticator>` using the `hide=[SignOut]` option. In other words, I want it to show everything (including the greeting) except for the the signout, which I want to display in the header. 

The `<header>` instantiates `<CustomAuthenticator AuthenticationType='header'>`, which then renders the same aws-amplify-react `<Authenticator>`, but this time the `hide=[...]` is configured to hide all components except the `<SignOut>`.

Or at least, that's how I want to do things... but the nesting of SignOut inside Greetings breaks this approach. 

I realize its an edge case and totally understand if it doesn't make sense changing the library just to fit this one example.

**Comment by jordanranz** [comment]
@matwerber1, awesome, thanks for the explanation.

It is currently not support to keep the `Greetings` component and hide the `SignOut` from the `Authenticator` prop level since `SignOut` is contained within the `Greetings` component.

What you can do however is hide the `Greetings` and construct your own header without the `SignOut` component. You can also use the `SignOut` component independently inside your like so:
```
import { Authenticator, SignOut } from 'aws-amplify-react'; // or 'aws-amplify-react-native';
``` 

Do you need the `Greetings` component so it shows the logged in user's name?
