### ISSUE TITLE
Kinesis Firehose Integration not working

### ISSUE THREAD

**Issue by swaroop55** [aws-amplify/amplify-js#5384]
Hi,

I'm building a react-native app with Amplify. I want to send data to a firehose stream. I did the configuration as mentioned in the wiki - https://aws-amplify.github.io/docs/js/analytics#using-amazon-kinesis-firehose. There are no errors in the app but the data is not available on the mentioned stream.

**Configuration**:
```javascript
Analytics.addPluggable(new AWSKinesisFirehoseProvider());
Amplify.configure({
	...awsConfig,
	Auth: {
        region: 'ap-south-1',
		userPoolId: 'xxxx',
		userPoolWebClientId: 'xxx',
	},
	API: {
		endpoints: [{
			name: "xxx",
			endpoint: "xxx"
		}]
	},
	AWSKinesisFirehose: {
		// OPTIONAL -  Amazon Kinesis Firehose service region
		region: 'ap-south-1',
		// OPTIONAL - The buffer size for events in number of items.
		bufferSize: 50,
		// OPTIONAL - The number of events to be deleted from the buffer when flushed.
		flushSize: 10,
		// OPTIONAL - The interval in milliseconds to perform a buffer check and flush if necessary.
		flushInterval: 10000, // 5s
		// OPTIONAL - The limit for failed recording retries.
		resendLimit: 5
	}
});
```

**Implementation:**

```javascript
async submitAnalytics() {
console.log("Analytics start:")
    let analyticsResponse = await Analytics.record({
      data: { 
      "xxx":"yyy"
      },
      streamName: 'stream-name'
    }, 'AWSKinesisFirehose');
    console.log("Analytics end:"+analyticsResponse)
  }
```

Only "Analytics start" log is displayed after method call. Any suggestion will really help. I'm struck here for a day. Tried various configurations. Did network profiling and no request were made by the app.

**Comment by jordanranz** [comment]
Hi @swaroop55,

Can you please post which versions of `aws-amplify` you are using?

**Comment by swaroop55** [comment]
4.18.0

**Comment by jordanranz** [comment]
@swaroop55, that may be your amplify cli version. Which version of `aws-amplify` is in your `package.json`

**Comment by swaroop55** [comment]
^2.2.7

**Comment by swaroop55** [comment]
Hi, Any update on this?

**Comment by Amplifiyer** [comment]
@swaroop55, can you try with the new amplify V3 versions and let us know if you are still facing the issues?

**Comment by nathanagez** [comment]
I have the same issue
amplify cli version: 4.50.2
@aws-amplify/analytics version: "^4.0.20"
