### ISSUE TITLE
Upload an image in React Native app - status 403

### ISSUE THREAD

**Issue by rozhali** [aws-amplify/amplify-js#5385]
**Describe the bug**
When I try to follow the amplify doc for uploading image from React Native I get "Request failed with status code 403"

**To Reproduce**

```
uploadToStorage = async pathToImageFile => {
  try {
    const response = await fetch(pathToImageFile)
    
    const blob = await response.blob()
    
    Storage.put('yourKeyHere.jpeg', blob, {
      contentType: 'image/jpeg',
    })
  } catch (err) {
    console.log(err)
  }
}
```

**Expected behavior**
It goes through successfully if I remove blob and enter file uri, but the file is unreadable in S3

**Screenshots**
<img width="1196" alt="Screen Shot 2020-04-12 at 11 29 58 PM" src="https://user-images.githubusercontent.com/16752065/79097881-abe63f00-7d15-11ea-9752-fb2a4407f421.png">

**Comment by bneigher** [comment]
@rozhali  if you're new to amplify - try using aws-amplify ^2.3.0.. it looks like the new 3.x.x modules are not working on react native.

If that doesn't work, make sure the policies are correct in aws for the roles that the cognito users assume.. I had issues with this in the beginning of my setup

**Comment by amhinson** [comment]
Hey @rozhali, we have a [recent update](https://github.com/aws-amplify/amplify-js/pull/5342) that might fix this issue. Could you try changing your `aws-amplify` version to `unstable` (temporarily) and see if the error goes away?

**Comment by rozhali** [comment]
@bneigher reverting back to 2.3.0 worked. Thanks for your help

@amhinson Do you want me to test out the unstable version? How do I do that?

**Comment by amhinson** [comment]
You can just change the version in `package.json` for `aws-amplify` to be `unstable`. Let me know if that fixes the issue.

**Comment by rozhali** [comment]
@amhinson `unstable` works

**Comment by amhinson** [comment]
Ok that’s great to hear! We should be getting a new stable release out this week, so keep an eye out for that.

**Comment by rozhali** [comment]
Sounds great 👍 thanks

**Comment by CodySwannGT** [comment]
Hitting the same issue. I'm using "unstable"
