### ISSUE TITLE
Storage.put does not save UTF-8 plain text anymore

### ISSUE THREAD

**Issue by masbaehr** [aws-amplify/amplify-js#5387]
Hi, i'm experiencing the following issue - the same code was still working on Amplify v2

It also still works while replacing Привет with "Hello". I've also tried specifying the contentType to text/plain. Same error

```javascript

  Storage.put("test.json", "Привет", {
      customPrefix: {
        public: "",
        protected: "",
        private: ""
      },
      bucket: "mybucket"
    })
      .then(result => {
        console.log(result);
      })
      .catch(err => {
        console.log(err);
      });

```

Error: 403 forbidden:
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>

Edit i actually found a workaround but it seems kinda awkward to do:

```javascript

 var fileToWrite = new Blob(["Привет"], {type: 'plain/text'});
  Storage.put("test.json", fileToWrite, {
      customPrefix: {
        public: "",
        protected: "",
        private: ""
      },
      bucket: "mybucket"
    })
      .then(result => {
        console.log(result);
      })
      .catch(err => {
        console.log(err);
      });

```

**Comment by Amplifiyer** [comment]
@masbaehr , thanks for the issue, it seems to be a bug with aws-sdk to not be able to handle UTF-8 characters correctly. aws/aws-sdk-js-v3#1100 seems to be related.

**Comment by Amplifiyer** [comment]
@masbaehr  can you test again with latest amplify and let us know if it's fixed?

**Comment by masbaehr** [comment]
It seems to be working again 👍

**Comment by ashika01** [comment]
Closing this issue since it is not happening with the latest version which merged in aws-sdk gamma version.
