### ISSUE TITLE
Email Verification by Link

### ISSUE THREAD

**Issue by twils0** [aws-amplify/amplify-js#539]
Do you want to request a feature or report a bug? Feature

What is the current behavior? This feature is not supported.

What is the expected behavior? In the AWS Console, under Cognito, User Pools, and then the Message Customization tab, there's an option to customize an email message to send a link. It would be helpful if aws-amplify had a method to send an email with a verification link and to set the redirect URL (i.e. the link is clicked in the email => a web page is loaded by AWS to confirm the email => AWS then redirects to a URL specified by the developer).

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions? v0.2.11

**Comment by pabloow** [comment]
You can use Lambda to send a the message with a customized link (unfortunately this is not very intuitive). For this go to "Triggers" (inside the User Pools console) and then "Custom Message" and select the function that you will have to create.

Follow this link to create a message with a customized url: https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-lambda-trigger-examples.html#aws-lambda-triggers-custom-message-example

**Comment by angineering** [comment]
Any updates on this issue? Weird that it's not available in Amplify but I can edit it in the browser

**Comment by lucasbastianik** [comment]
+1

**Comment by jordanranz** [comment]
Hi all that are tracking this,

For the feature to happen Cognito will need to expose an API for us to send this verification link.

I have seen some other issues cut for this feature request. I will try and drive this to get a response from the service team.

**Comment by jordanranz** [comment]
Closing in favor of: #2777
