### ISSUE TITLE
Storage get with download option Body is string instead of Uint8Array

### ISSUE THREAD

**Issue by Nabrok** [aws-amplify/amplify-js#5393]
**Describe the bug**
In version 3 when using the download option on Storage.get the Body in the resulting object is a string.  In version 2.3 this was a Uint8Array.

**To Reproduce**
```
Storage.get("somefile", { download: true }).then(console.log);
```

**Expected behavior**
result.Body should be a Uint8Array.

**Comment by shubham234** [comment]
I recently upgraded to @aws-amplify/storage@3.1.9 from @aws-amplify@2.1.0. I was downloading a JSON file with download: true in the request and was able to parse the response as JSON.parse(result.Body) but now I see return type of JSON file set as Blob. How can I convert that Blob to JSON? I'm on react-native.

**Comment by shubham234** [comment]
Parsed the blob response using `const text = await (new Response(blob)).text();` as per https://developer.mozilla.org/en-US/docs/Web/API/Blob.

**Comment by Amplifiyer** [comment]
@Nabrok with Amplify V3, the response type is now a Blob in both web and react native environments. Let us know if you face any issues with using blobs.
