### ISSUE TITLE
Datastore have issue saving AWSJSON type

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/amplify-js#5396]
**Describe the bug**
I have a field `content: AWSJSON!` in graphql api. 
When I generate models for Datastore then its converted to `content: string`. 
The output from [draft-js](https://draftjs.org/) is converted to string with 
`content: JSON.stringify(convertToRaw(editorState.getCurrentContent()))` 
the actual content is 
`"{"blocks":[{"key":"872eg","text":"this is a test message","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}"`

I get following error from Datastore/API
`Supplied AttributeValue is empty, must contain exactly one of the supported datatypes`

**Amplify CLI Version**
4.18.0

**To Reproduce**
- `npx create-react-app test --use-npm --template typescript`
- `amplify init` with dev env
- `amplify add auth` default everything
- `amplify add api` use following schema
```
type Comment @model
  @auth(rules: [{ allow: private }]) {
  id: ID!
  owner: String!
  content: AWSJSON!
}
```
then save with button like this
```
async function createComment() {
    
    try {

      const results = await DataStore.save(new Comment({
        owner: 'd346afec-1d50-4aeb-bfea-e70f67adc0f9',
        content: JSON.stringify(convertToRaw(editorState.getCurrentContent()))
      }))

      console.log(results)

    } catch (err) {

      console.error(err)
    }
  }
```
Then you get following error
`Supplied AttributeValue is empty, must contain exactly one of the supported datatypes`

**Expected behavior**
I should be able to save JSON in dynamodb with datastore. Without error.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 on Windows WSL
 - Node Version. 12.16.1

**Additional context**
It works in 2 conditions 
1. when `content: AWSJSON!` I save it with `content: JSON.stringify(JSON.stringify(convertToRaw(editorState.getCurrentContent())))`
1. if I change  `content: AWSJSON!` to `content: String!` and save with `JSON.stringify(convertToRaw(editorState.getCurrentContent()))`

**Comment by brene** [comment]
cc @sammartinez - I think this is a JS issue

**Comment by ashika01** [comment]
I think this issue is related to https://github.com/aws-amplify/amplify-js/issues/5767

Closing this issue and we will track the progress in the above mentioned issue. There is a workaround posted there. Hope that helps.
