### ISSUE TITLE
Refresh token request is going right after Auth.SignIn with two active JWT tokens at the same time  

### ISSUE THREAD

**Issue by ters52** [aws-amplify/amplify-js#5397]
**Describe the bug**
After using Auth.SignIn I see 4 requests to Cognito. The 4th request is a refresh token request and it happens right after sign in. The problem is that old JWT token which Amplify got on the sign-in process
is still active and in this case, I have 2 active Bearer tokens at the same time.

**To Reproduce**
To reproduce it just check requests after Auth.SignIn with 
`AuthFlow: "USER_SRP_AUTH" `

**Expected behavior**
Only one Bearer token has to be generated on sign-in.

**Additional context**

POST Requests list right after SignIn:

1. 
payload:
```
{
  AuthFlow: "USER_SRP_AUTH"
  ClientId: "***"
  AuthParameters: {USERNAME: "***",…}
  ClientMetadata: {}
}
```

response:
```
{
  "success": true
}
```

2. 
payload:

```
{
  ChallengeName: "PASSWORD_VERIFIER"
  ClientId: "***"
  ChallengeResponses: {USERNAME: "***",…}
  ClientMetadata: {}
}
```

response:

```
{"AuthenticationResult":{"AccessToken"...}
```

3. 
payload:
```
{  AccessToken: *** }
```
response:
```
{"UserAttributes":...}
```

4.
payload:
```
{
  ClientId: "***"
  AuthFlow: "REFRESH_TOKEN_AUTH"
  AuthParameters: {,…}
}
```

**Sample code**
Amplify configuration: 
```
Amplify.configure({
  Auth: {
    region: '***',
    userPoolId: '***',
    userPoolWebClientId: '***',
  },
});
```

```
Auth.signIn(email, password)
      .then(() => {
        Auth.currentAuthenticatedUser().then((user) => {
          console.log(user);
        });
      })
      .catch((err) => {
        console.log(err);
      });
```

**Comment by elorzafe** [comment]
@ters52 I reproduced this issue, I will be working on a fix

**Comment by TimNZ** [comment]
@elorzafe 
Can you please look at this post - I'm getting 8 Cognito calls triggered by Auth.signIn()

https://github.com/aws-amplify/amplify-js/discussions/5755

**Comment by uclaeamsavino** [comment]
Is there any version of aws-amplify 2.x.x that doesn't do this? I tried 2.3.0, 2.2.0 and 2.1.0. All immediately make the REFRESH_TOKEN_AUTH call when calling Auth.signIn(). 

I feel like I must be doing something wrong because it's hard for me to see this going uncaught for all of amplify 2.x.
