### ISSUE TITLE
Wrap the item list to display first set of items after the last set, given pagination size

### ISSUE THREAD

**Issue by AshwiniRaysecur** [aws-amplify/amplify-js#5408]
**Description**

The UI has 'Next set' button, which calls Amplify auto-generated 'listAll' query.
'Next set' button does not wrap the item list to show the first set of items again after the last set is displayed

**Steps to Replicate**
1. Set 'limit' (of displaying number of items in the list) equal to X (eg. 10) in listAll query function
2. Make the number of items in database (dynamo db table), a multiple of X (eg. 20 or 40)
3. Run the app and click the 'Next set' button, till you get to the last set of items in the list
4. Click 'Next set'

**Expected Result**
clicking the 'Next set' button should again display the first X items in the list

**Actual Result**
the items list doesn't change and displays the same last set of items

----
Screenshot of the App :

![listing screenshot](https://user-images.githubusercontent.com/59932758/79144130-6b75d800-7d8c-11ea-9828-1b2bb4b02c83.png)

----

For the application, the pagination limit is set to 5 in 'listAll' query 
+ Case (a)
      1. Total number of items in database (dynamobd) is 11 
      2. Application launch displays 5 items (items 1 - 5)
      3. Click 'Next set' button, displays next 5 items (items 6 - 10)
      4. Click 'Next set' button, displays 1 (11th) item from the database
      4. Click 'Next set' button, wraps around and displays first 5 items (items 1 - 5)

+ Case (b)
      1. Total number of items in database (dynamobd) is 10
      2. Application launch displays 5 items (items 1 - 5)
      3. Click 'Next set' button, displays next 5 items (items 6 - 10)
      4. Click 'Next set' button, displays the same set of 5 items (items 6 - 10) and 
           throws error : "TypeError: Cannot read property 'id' of undefined"

----
Can we have Case (b) to wrap the item list to display first 5 items (items 1 - 5) again ?

**Comment by ashika01** [comment]
@AshwiniRaysecur Could you post some sample code.? Also, I am unclear to which ui component you are using or where this issue is happening.
