### ISSUE TITLE
How can I pass params while onStateChange and how can I use that in another class in overide component of Authenticator

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#5410]
I need to pass params from SignIn to another screen. How can I make this param to pass from one class to another in aws-amplify onStateChange

`this.props.onStateChange('signIn',{});`

**Comment by jordanranz** [comment]
Hey @nihp, which UI framework/Amplify UI library are you using?

**Comment by nihp** [comment]
I am using aws-amplify-react-native 

Authenticator component with my custom UI.

```
<Authenticator>
   <CustomSingIn overide={'signIn}
    <CustomForgotpassword overide={'forgotPassword'}
</Authenticator>
```

**Comment by jordanranz** [comment]
Ok, gotcha.

Which params are you trying to pass?

**Comment by nihp** [comment]
I need to pass the email values.

**Comment by nihp** [comment]
@jordanranz Any update for this.

**Comment by nihp** [comment]
@ashika01 Any update on this. 

I am using this.props.onStateChange('signIn',{}); how can I send the username from one screen to another as param and How can i use there. (override the screens with my custom screens)

**Comment by ashika01** [comment]
@nihp I will check this one out with team. In meanwhile, to make sure I understand this right, you was to send you username from, lets say customSignIn, to another component ? I guess if you could explain what you are trying to achieve as end goal, we may be able to help

**Comment by nihp** [comment]
Yes exactly, need to send param from SignIn to confirmSignUp. Also I have found one solution too.

This is from SignIn
`this.props.onStateChange('confirmSignUp',{email}) // here it may be email or phone number`

Then it will be used as below in confirm signUp
```

const emailparam = this.props.authData;
let emailInput = emailparam.email

//This emailInput is used in the place of TextInput.
```

Now I can able to pass the params from one screen to another screen (with override component in Authenticator)

**Comment by mauerbac** [comment]
Hey @nihp - were you able to move past this? Or is this still an issue?

**Comment by nihp** [comment]
Still not an issue. I can able to get the value.
