### ISSUE TITLE
Better Support For Pagination With API Package

### ISSUE THREAD

**Issue by karrettgelley** [aws-amplify/amplify-js#5411]
**Is your feature request related to a problem? Please describe.**
Most apps needs to paginate their queries. Whether its chat app, marketplace, or social network, everyone is going to need to be able to fetch small amounts of data at first, and more as the user interacts with the UI. This is very difficult to do with amplify's API module on queries that have relations. Yes, listMessages can be paginated ootb, but that query is expensive in time and space. Most people recommend just setting limit: 1000 and hoping you never need to change that, but that approach doesn't work for models that have. relationships. After reading this post about [writing custom queries for pagination](https://dev.to/rakannimer/pagination-sorting-with-aws-amplify-4l37#getchannelmessages), I believe it can be done with amplify, but it's very frustrating and not very testable in the amplify console.

**Describe the solution you'd like**
Extend the pagination capabilities for queries with relationships via `@connection`. The blog post above is a very good example of what I'm talking about. As an example, I need to be able to call API.getChannel(id) which will return a list of 10 messages and a nextToken, and I should then be able to pagination the rest of the messages for that query later on.

**Describe alternatives you've considered**
Writing custom queries seem to be viable, and I'll report back to this post when I have tested it myself. See the blog post above for one example.

**Additional context**
To illustrate the point with an example, suppose I had a schema like the following:

`
type Channel @model {
id: ID!
name: String!
messages: [Messages] @connection
}
type Messages @model {
id: ID!
content: String!
}
`
A very simple case, but it'll do. Now, suppose I have a page that displays a channel and its messages. Obviously I don't want to show 10000 messages at a time, but I do want to display the first 10 and then show more as the user scrolls to the bottom of the page. So I do an inital query: getChannel(id). What I want is that when the user scrolls to the bottom of the page, I can simply call getChannel(id, nextToken) and fetch the next 10 messages.
I hope this example is clear. I did my best to find documentation on this subject and custom queries kept coming up, although it isn't a very hot topic, so I'm wondering if I'm just crazy and this issue has already been solved by amplify. I do hope you read the blog post I linked, because it looks like to me there is a good opportunity for automating the custom query thing. The biggest drawback to the custom query is that you have to maintain them as your api evolves. It would be great if amplify could generate similar such queries.

- PS thank you so much to the amplify team. You guys have made an amazing product and it continues to get better every day.  And every day I am seeing more and more people ditch firebase despite the hype. I would love to contribute someday myself once I can lockdown typescript ;)

**Comment by karrettgelley** [comment]
Am I the only one that wants this feature? Surely there are others out there who are tired of manually transforming the auto-generated graphql queries into queries with pagination.

**Comment by chrisbonifacio** [comment]
Amplify's GraphQL client supports `nextToken` and `limit` as parameters to queries. Custom queries are not necessary to implement pagination anymore but they are easier than ever now to implement with custom resolver logic in Gen 2!
