### ISSUE TITLE
Observing data model changes between clients doesn't work, at all.

### ISSUE THREAD

**Issue by jesper-bylund** [aws-amplify/amplify-js#5413]
**Describe the bug**
Using the "observe" method to subscribe to data updates simply does nothing.

This is my model:
```graphql
type Ting @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  createdAt: AWSDateTime
  references: [String]
  referencedBy: [String]
  content: String!
  access: [UserTing] @connection(keyName: "byUser", fields: ["id"])
}
```

This code triggers ONLY on local update. It is never triggered when on another client:
```js
const subscription = DataStore.observe(Ting).subscribe(msg => { console.log(msg) });
```

There are no errors. And nothing wrong, that I can see, with the Websocket. Any ideas on how to debug?

versions
```
"@aws-amplify/core": "^2.2.5",
"@aws-amplify/datastore": "^1.0.8",

Amplify-cli 4.18.0
```

**Comment by raelmiu** [comment]
Update:
After removing the access connection
`access: [UserTing] @connection(keyName: "byUser", fields: ["id"])`

I get this following error, that has at least one other open issue.
```
react_devtools_backend.js:6 [WARN] 16:18.515 DataStore - Sync error subscription failed Connection failed: {"errors":[{"message":"Validation error of type FieldUndefined: Field 'onCreateUserTing' in type 'Subscription' is undefined @ 'onCreateUserTing'"}]}
```

I'm unable to roll back, I get the "update many" errors when using Amplify Push. So I'm not stuck with an app that no longer works, at all.

**Comment by raelmiu** [comment]
Another update, not sure what happened here but when I looked through the project for `onCreateUserTing`I realized this should be a part of the model that was removed `User`.  And in `schema.js`I could actually see my old models still referenced.

For some reason, my schema was not being updated. But there was no error.
Running `Amplify codegen`didn't resolve this.
Running `npm run amplify-modelgen` did however update schema.js and the app is now functional again.

 I'm not quite sure what happened. Or why this currently works. Feels a lot like magic, and leaves me thinking that this is very fragile. Any theories will be greatly appreciated.

**Comment by rpostulart** [comment]
This helped me:

https://github.com/aws-amplify/amplify-js/issues/5174

**Comment by amhinson** [comment]
@jesper-bylund Did the issue that @rpostulart provided solve your issue, or are you still having problems?

**Comment by jesper-bylund** [comment]
@amhinson I had to stop using Datastore because of the multitenant issue (I think it's #5119 ). But this work around looks solid so I'm closing.

**Comment by amhinson** [comment]
Ok thanks for the feedback!
