### ISSUE TITLE
AuthState is not exported from @aws-amplify/ui-components

### ISSUE THREAD

**Issue by binarydud** [aws-amplify/amplify-js#5416]
**Describe the bug**
In a typescript based react app, when using the AmplifyAuthenticator, i'd like to change the initalAuthState parameter, described here https://docs.amplify.aws/ui/auth/authenticator?framework=react#prop-initial-auth-state. However, the enum AuthState from ui-components is not exported so typescript fails with an error similar to: `node_modules/@aws-amplify/ui-components/dist/types/components"' declares 'AuthState' locally, but it is not exported.`

**To Reproduce**

1. Create a CRA app with a typescript template
2. import AmplifyAuthenticator into the App.tsx.
3. add the initalAuthState property to AmplifyAuthenticator like `<AmplifyAuthenticator usernameAlias="email" initialAuthState={AuthState.SignUp>`

**Expected behavior**
User should be able to import AuthState enum and use it for initalAuthState

**Comment by jordanranz** [comment]
Hey @binarydud, 

You can access this `AuthState` enum by using:
```
import { AuthState } from '@aws-amplify/ui-components';
```
in your `App.tsx`

It may however be better if we pass this through to `@aws-amplify/ui-react` so you can do something like:
```
import { AmplifyAuthenticator, AuthState } from '@aws-amplify/ui-react';
```

I'll test passing it through and mark this as a feature request

**Comment by binarydud** [comment]
@jordanranz what version of ui-components is exporting AuthState, if i add that import statement i get the following error when compiling: 
```
TypeScript error in /Users/matt/src/project/src/App.tsx(28,10):
Module '"../../../../../Users/matt/src/project/node_modules/@aws-amplify/ui-components/dist/types/components"' declares 'AuthState' locally, but it is not exported.  TS2459
```

i have the following version of ui-components installed: @aws-amplify/ui-components@0.3.2

**Comment by jordanranz** [comment]
Did you use:
```
import { AuthState } from '@aws-amplify/ui-components';
```
or 
```
import { AuthState } from '@aws-amplify/ui-react';
```

**Comment by binarydud** [comment]
`import { AuthState } from '@aws-amplify/ui-components'`

**Comment by jordanranz** [comment]
Ok, got it. I was accidentally testing in a non-Typescript app.

Looking into why `AuthState` is not being properly exported now.

**Comment by jordanranz** [comment]
@binarydud the `AuthState` type is not properly being exported by `@aws-amplify/ui-components`

Can you try installing `@aws-amplify/ui-react@unstable` then try:
```
import { AuthState } from '@aws-amplify/ui-components'
```

Let us know if that worked for you.

**Comment by binarydud** [comment]
Sorry about the delay. The unstable package worked for me, thanks.

**Comment by asumaran** [comment]
Using `@aws-amplify/ui-react@unstable` worked for me as well. Thanks

**Comment by 70nyIT** [comment]
> ~Using `@aws-amplify/ui-react@unstable` worked for me as well. Thanks~
> 
> Nope, I got another error now.
> 
> ```
> ./node_modules/@aws-amplify/ui-components/dist/esm-es5/Translations-59947173.js
> Attempted import error: 'AuthErrorStrings' is not exported from '@aws-amplify/auth'.
> ```

Same thing happening to me

**Comment by healthlake** [comment]
any solution yet? I got the same error after installation and using S3 Image Picker

[ng] ERROR in ./node_modules/@aws-amplify/ui-components/dist/esm/Translations-dbe7c89e.js 112:67-83
[ng] "export 'AuthErrorStrings' was not found in '@aws-amplify/auth'

**Comment by healthlake** [comment]
any solution yet? I got the same error after installation and using S3 Image Picker

[ng] ERROR in ./node_modules/@aws-amplify/ui-components/dist/esm/Translations-dbe7c89e.js 112:67-83
[ng] "export 'AuthErrorStrings' was not found in '@aws-amplify/auth'

**Comment by nikevp** [comment]
+1 on error after upgrade

**Comment by dabit3** [comment]
Also getting this error when using version: `^0.2.19` in package.json, installed version `0.2.19`

`Attempted import error: 'AuthErrorStrings' is not exported from '@aws-amplify/auth'.`

**Comment by cbishop-fv** [comment]
using CRA and "@aws-amplify/ui-react": "^0.2.19",

import { withAuthenticator, AmplifySignOut } from '@aws-amplify/ui-react';

from example https://docs.amplify.aws/lib/auth/getting-started/q/platform/js#option-1-use-pre-built-ui-components

Failed to compile.
./node_modules/@aws-amplify/ui-components/dist/esm-es5/Translations-392acb9b.js
Attempted import error: 'AuthErrorStrings' is not exported from '@aws-amplify/auth'.

**Comment by vennemp** [comment]
I am just learning react, npm, and amplify.  Using the aws amplify docs (though I run into this issue with every blog on amplify on the internet) 

Is there a command I have to run after updating the packages.json file with the correct dependency versions?

**Comment by swatantragoswami09** [comment]
npm install -g @aws-amplify/cli
npm install --save aws-amplify @aws-amplify/ui-react
amplify configure
amplify init
amplify add auth
amplify push
Start adding aws amplify in your react project with these cmd hope it helps to you(execute cmds with top to bottom).

**Comment by cbishop-fv** [comment]
> I am just learning react, npm, and amplify. Using the aws amplify docs (though I run into this issue with every blog on amplify on the internet)
> 
> Is there a command I have to run after updating the packages.json file with the correct dependency versions?

You specify the version number in the package.json

eg
```"@aws-amplify/ui-react": "^0.2.21",
"aws-amplify": "^3.3.1",

the leading carrot ( ^ ) means this version or newer up to the next major version. 

remove the leading carrot if you want a specific version and never allow updates. But you should be fine with the versions I listed and a carrot. 

After updating the versions you want in package.json `rm -rf` your node modules and then run `npm install` or `yarn install`  etc
