### ISSUE TITLE
Improve missing auth package error message

### ISSUE THREAD

**Issue by kay-is** [aws-amplify/amplify-js#5431]
**Is your feature request related to a problem? Please describe.**

I used the core, auth and ui-react package, but I didn't import the auth package, because, well I wasn't using it *directly*.

I got the following error:

    Error: Amplify has not been configured correctly.

With some link to a docs page that talked about `Amplify.configure()` etc.

In the end, I fixed the error by importing the auth package before I ran `Amplify.configure()`, but the error never mentioned that it was missing. 

**Describe the solution you'd like**

An error message that actually says something like "Please import @aws-amplify/auth package in your app" or something.

**Comment by amhinson** [comment]
As a follow up, we introduced modularization earlier this year so we recommend just importing `aws-amplify` and relying on tree shaking. We are in the process of updating all documentation to reflect this.
