### ISSUE TITLE
S3 multipart upload using storage.put does not propagate metadata

### ISSUE THREAD

**Issue by angelarw** [aws-amplify/amplify-js#5432]
**Describe the bug**
When using Amplify's `storage.put`, i noticed when the file to upload is larger than a few MB, the upload is completed using s3 multipart upload. However, when this happens, the metadata args passed into `storage.put` is not sent to S3. 
When i use the same code to upload a small file, i can see the metadata being successfully sent to S3. 

**To Reproduce**

When using `Storage.put` or `Storage.vault.put`,and upload a file > 5MB, one can observe the metadata is not being sent and received by s3 when multipart upload happens

Link to sample code
[code here](https://github.com/aws-samples/amplify-photo-gallery-workshop/blob/master/photoalbums/src/App.js#L203)

</details>

**Additional context**
Version of amplify used:

```
    "@aws-amplify/api": "^3.1.6",
    "@aws-amplify/storage": "^3.1.6",
```

**Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)
 
My code is similar to the example [code here](https://github.com/aws-samples/amplify-photo-gallery-workshop/blob/master/photoalbums/src/App.js#L203)  
```
     const result = await Storage.vault.put(
      fileName,
      file,
      {
        metadata: {
          albumid: props.albumId,
          owner: user.username,
        }
      }
    );

```

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by Amplifiyer** [comment]
I have found the root cause and created a PR for the fix. The root cause is an undocumented mysterious behavior which removes the content-type header if the post body is empty. I'm using the workaround suggested to unblock for now.

**Comment by matamicen** [comment]
@angelarw we are realizing that uploading  files of 10mb with storage.put are slow 4x times comparing with the S3 console and sometime unstable , means that sometimes takes more time than the average. Is this happening to you? Did you try pre signed multipart upload or something else ? Thanks! 
Matt

**Comment by angelarw** [comment]
@matamicen i haven't tested the performance so I'm not sure
