### ISSUE TITLE
DataStore API Updating _version field can not be set from the client.

### ISSUE THREAD

**Issue by crolly** [aws-amplify/amplify-js#5433]
**Describe the bug**
Using the DataStore API I am unable to update a model as described in the docs.
It is only updating the local model and not syncing it with the cloud.

**To Reproduce**
```javascript
const original = await DataStore.query(Event, e => e.id('eq', id))
await DataStore.save(
  Event.copyOf(original, (updated) => {
    Object.assign(updated, item)
  })
)
```

**Expected behavior**
1. Update of the local model
2. Sync with the cloud

**Screenshots**
<img width="1660" alt="Bildschirmfoto 2020-04-16 um 21 43 36" src="https://user-images.githubusercontent.com/30681934/79499513-61bdd000-802b-11ea-9b7a-84751dd1e092.png">

**Comment by crolly** [comment]
Btw, as delete with certain index constellations was not working either directly through `DataStore.delete(...)` I was able to work around that problem by running the GraphQL mutation through the API package right afterwards:

```
await DataStore.delete(Event, e => e.geoPart('eq', item.geoPart).geoHash('eq', item.geoHash).id('eq', item.id))
// WORKAROUND - have to run delete mutation until issues is fixed
const toDelete = {
  geoPart: item.geoPart,
  geoHash: item.geoHash,
  id: item.id,
  _version: item._version
}

await API.graphql(graphqlOperation(mutations.deleteEvent, { input: toDelete }))
```

I have tried the same with the update mutation, however I am still getting the same error regarding the `_version` attribute, so this may actually be an API or AppSync issue.

**Comment by crolly** [comment]
Another update: running the mutation from a GraphQL client against the endpoint either returns the same error `Updating _version field can not be set from the client.` if the `_version` is sent as input or if not sent, increases the version number, returns no error, but does not change any attributes.

```graphql
mutation{
  updateEvent(input: {
    geoPart: "u33dc",
    geoHash: "u33dcwfxuthk",
    id: "74483b20-300e-4b4b-9cfd-f013746da968",
    maxSlots: 12,
    _version: 17
  }){
    geoPart
    geoHash
    id
    title
    description
    price
    type
    minSlots
    maxSlots
    _version
    _deleted
    _lastChangedAt
  }
}
```
returns
```graphql
{
  "data": {
    "updateEvent": null
  },
  "errors": [
    {
      "path": [
        "updateEvent"
      ],
      "data": null,
      "errorType": "BadRequest",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "Updating _version field can not be set from the client."
    }
  ]
}
``` graphql
mutation{
  updateEvent(input: {
    geoPart: "u33dc",
    geoHash: "u33dcwfxuthk",
    id: "74483b20-300e-4b4b-9cfd-f013746da968",
    maxSlots: 12
  }){
    geoPart
    geoHash
    id
    title
    description
    price
    type
    minSlots
    maxSlots
    _version
    _deleted
    _lastChangedAt
  }
}
```
returns
```graphql
{
  "data": {
    "updateEvent": {
      "geoPart": "u33dc",
      "geoHash": "u33dcwfxuthk",
      "id": "74483b20-300e-4b4b-9cfd-f013746da968",
      "title": "Test",
      "description": "<p>test</p>",
      "price": 0,
      "type": "SINGLE",
      "minSlots": 0,
      "maxSlots": 24,
      "_version": 18,
      "_deleted": null,
      "_lastChangedAt": 1587132518153
    }
  }
}
```


Don't know, if these information help at all. Any ideas, though?

**Comment by crolly** [comment]
Investigating further I suppose the issue is, that the AppSync Engine is unable to handle the custom index:
```graphql
type Event @model @key(fields: ["geoPart", "geoHash", "id"]){
  geoPart: String!
  geoHash: String!
  id: ID!
  ...
}
```

**Comment by sevensys** [comment]
I'm also struggling with this issue 

My GraphQL schema:
`"""
Users will come from the cognito user pool
"""
type User
@model
@versioned(versionField: "_version")
@key (fields:["id"])
@auth(rules: [{allow: owner, ownerField: "id"},{ allow: groups, groups: ["admin"]}])
{
    id: ID!
    countryId: ID!
    stateId: ID!
    munId: ID!
    email: AWSEmail!
    dateOfBirth: AWSDate!
    gender: Gender!
    education: EducationLevel!
    created: AWSDateTime!
}`

The mutation: 

`mutation UpdateUser(
    $input: UpdateUserInput!
    $condition: ModelUserConditionInput
  ) {
    updateUser(input: $input, condition: $condition) {
      id
      countryId
      stateId
      munId
      email
      dateOfBirth
      gender
      education
      created
      _version
      _deleted
      _lastChangedAt
    }
  }`

`export type UpdateUserInput = {
  id: string,
  countryId?: string | null,
  stateId?: string | null,
  munId?: string | null,
  email?: string | null,
  dateOfBirth?: string | null,
  gender?: Gender | null,
  education?: EducationLevel | null,
  created?: string | null,
  _version?: number | null,
  expectedVersion: number,
};`

The code that updates the entity above:

` awsAppSyncClient?.mutate({
  mutation: gql(updateUser),
  variables: {
    input: {      
      id: "Facebook_103670867891818"
      email: "nfuwnwnyuq_1581898960@tfbnw.net"
      gender: "MALE"
      dateOfBirth: "1982-05-10+00:00"
      education: "GRADUATE"
      countryId: "BRA"
      stateId: "SP"      
      munId: "3502101"​
      created: "2020-04-24T08:28:44.689Z"
      expectedVersion: 4      
    },
    condition: null
  }
}).then((result) => {  
  const user = result.data.updateUser
  logger.info(`${operation} yields object: `, user);
}).catch((error) => {
  logger.warn(`${operation} yields error: `, JSON.stringify(error), error);
});`

Returns: 
`Error: "GraphQL error: Updating _version field can not be set from the client`

If I don't use the @versioned directive on the entity, the update operation goes through but the conflict resolution handler set to AUTOMERGE rejects all of the modifications and the operation does not have any effect  

And you know what the worst part of this dilemma is? I told my wife that this application would help us out of poverty

**Comment by Tom-RulesCube** [comment]
Just hitting this myself ... so basically, a custom index means you can't use an update mutation? Hmmm.

**Comment by undefobj** [comment]
The error "Updating _version field can not be set from the client" will happen if you submit a version higher than is currently committed to the backend DynamoDB table because the conflict detection protocol requires a single owner of updating versions for consistency, which is the service. DataStore will do this automatically (it sends it's last version of the world, which is the current version or something older) but if your're manually running a mutation from the console you'll need to specify this manually.

Can you take a look at the [latest docs for Relational modeling](https://docs.amplify.aws/lib/datastore/relational/q/platform/js) with DataStore and use the latest library version? We made some improvements to the CLI, the library on how it handles this internally, and tried to be explicit about schemas in the documentation including how to use `@key`.

**Comment by aleckzts** [comment]
I am still getting the error "Updating _version field can not be set from the client."
versions:
```
    "@aws-amplify/core": "^3.2.8",
    "@aws-amplify/datastore": "^2.1.1",
    "aws-amplify": "^3.0.12",
    "aws-amplify-react": "^4.1.11",
    "aws-appsync": "^3.0.3",
    "aws-appsync-react": "^3.0.3",
```

Query, create and delete are ok, update gives the error "BadRequest", with that message.

the code:

```javascript
      const original = await DataStore.query(Loja, idloja);
      await DataStore.save(
        Loja.copyOf(original, updated => {
          updated.nome = values.nome;
          updated.cnpj = values.cnpj;
          updated.ativo = values.ativo;
        })
      );
```

**Comment by undefobj** [comment]
> I am still getting the error "Updating _version field can not be set from the client."
> versions:
> ```
>     "@aws-amplify/core": "^3.2.8",
>     "@aws-amplify/datastore": "^2.1.1",
>     "aws-amplify": "^3.0.12",
>     "aws-amplify-react": "^4.1.11",
>     "aws-appsync": "^3.0.3",
>     "aws-appsync-react": "^3.0.3",
> ```
> 
> Query, create and delete are ok, update gives the error "BadRequest", with that message.
> 
> the code:
> 
> ```javascript
>       const original = await DataStore.query(Loja, idloja);
>       await DataStore.save(
>         Loja.copyOf(original, updated => {
>           updated.nome = values.nome;
>           updated.cnpj = values.cnpj;
>           updated.ativo = values.ativo;
>         })
>       );
> ```
> 

Can you try deleting the records from your DynamoDB tables using the console? Alternatively, try clearing your local IndexedDB store using the browser dev tools to force a full sync. It sounds like you might have gotten something out of sync between client and backend.

**Comment by aleckzts** [comment]
> Can you try deleting the records from your DynamoDB tables using the console? Alternatively, try clearing your local IndexedDB store using the browser dev tools to force a full sync. It sounds like you might have gotten something out of sync between client and backend.

Started with a empty table and removed IndexedDB from Chrome.
Create data, Ok. Update the data, same error.

Screenshot
![error](https://user-images.githubusercontent.com/63109594/82843797-b408d100-9eb4-11ea-9dc5-97d5e713a51b.png)

**Comment by undefobj** [comment]
Can you give your complete code and schema?

**Comment by aleckzts** [comment]
> Can you give your complete code and schema?

Thats not the best code you have seen, but ok.
https://github.com/aleckzts/bpc-console

I have started with API and graphqlOperation, and started moving to Datastore now.

**Comment by undefobj** [comment]
I think that [on this line](https://github.com/aleckzts/bpc-console/blob/master/src/pages/Loja/Add.js#L113) your `Object.assign(updated, values)` is stripping  `_version` from the response of the `(updated) => {}` function which means that it doesn't match what is at the server. Can you try just updating the fields like the documentation shows: https://docs.amplify.aws/lib/datastore/data-access/q/platform/js#update-data

**Comment by aleckzts** [comment]
Sure, have tried both ways with no success.
Started over with empty table, deleted local db and discrete values on update. Same error.

The `_version` field are returned in the `localModel` field of the error

**Comment by aleckzts** [comment]
Maybe its a problem with the @key directive on my models.
Removed all of then and now the update finish without errors, DynamoDB tables shows the updated data.

**Comment by undefobj** [comment]
That's possible as well. There was an update to both the JS library and CLI to better support `@key` a couple of weeks ago, along with updated documentation: https://docs.amplify.aws/lib/datastore/relational/q/platform/js

Ensure that you have the latest library and CLI versions and see if the guidance on that page helps.

**Comment by aleckzts** [comment]
Updated CLI and libraries, removed all `@key(fields: ["id"])` from schema and updates are working now.
The others @keys seems to be not interfering.

**Comment by crolly** [comment]
> The error "Updating _version field can not be set from the client" will happen if you submit a version higher than is currently committed to the backend DynamoDB table because the conflict detection protocol requires a single owner of updating versions for consistency, which is the service. DataStore will do this automatically (it sends it's last version of the world, which is the current version or something older) but if your're manually running a mutation from the console you'll need to specify this manually.
> 
> Can you take a look at the [latest docs for Relational modeling](https://docs.amplify.aws/lib/datastore/relational/q/platform/js) with DataStore and use the latest library version? We made some improvements to the CLI, the library on how it handles this internally, and tried to be explicit about schemas in the documentation including how to use `@key`.

I have one question because this is throwing me off.

On one hand the amplify docs say:
`When using the @key directive with DataStore, as long as you specifcy a name you can use any value(s) in fields. However, if the name property is omitted, the first item in the fields array must be "id". E.g., @key(fields: ["id", "content"]).`
At the same time it says this about the `name` attribute of the `key` directive:
`When provided, specifies the name of the secondary index. When omitted, specifies that the @key is defining the primary index. You may have at most one primary key per table and therefore you may have at most one @key that does not specify a name per @model type.`

So now I have the following questions regarding this schema:
```graphql
type Enrollment 
  @model 
  @key(name: "enrollmentKey", fields: ["userId", "roomId", "enrollmentId"]) {

  userId: ID!
  roomId: ID!
  enrollmentId: ID!

  progress: Float

  enrolledAt: AWSTimestamp
}
```

1. With this configuration the key will be defined as secondary index, correct?
2. If so, is the `id` attribute configured automatically or is the schema not going to work at all, because it is missing?
3. How am I able to define my own primary index with custom `HASH` and `SORT/RANGE` keys?

**Comment by atlesp** [comment]
I believe this is the same issue as https://github.com/aws-amplify/amplify-cli/issues/4355 .

I worked around the issue with replacing the update request resolver with a modified one, see https://github.com/aws-amplify/amplify-cli/issues/4355#issuecomment-642565027

**Comment by IsaacTrevino** [comment]
+1 I am getting this error too. I don't want to edit my @keys.

**Comment by david-mcafee** [comment]
@crolly, @atlesp and @IsaacTrevino - closing this ticket. Please reopen if you encounter further issues. Thanks!
