### ISSUE TITLE
Datastore show performance issues on Safari. 

### ISSUE THREAD

**Issue by rpostulart** [aws-amplify/amplify-js#5434]
When there are for example 600 records in your DB and you init/start your app with 

DataStore.configure(awsConfig)

DataStore.observe(Quiz).subscribe(Quiz => {
      console.log(Quiz)
    })

The first time all the records are loaded. In seems like in chrome it's working well and in Safari there is some idle time and looks like your application crashes, your app continues working after all the records are loaded.

**Comment by rpostulart** [comment]
Anyone?

**Comment by manueliglesias** [comment]
Hi @rpostulart 

I am working on some performance improvements on the DataStore, if we don't encounter issues or problems, we are targeting next to release them.

I just tested a DataStore app with an API returning 100k items and it worked fine on Safari, so hopefully these fixes will make the issue go away for you.

Thank you for the patience

**Comment by rpostulart** [comment]
Hi good to hear, but were you also able to reproduce the issue / did you noticed the performance issue?

**Comment by manueliglesias** [comment]
Hey @rpostulart 

We just published new versions to the `unstable` npm tag with a bunch of improvements, it would be great if you can take a look and try them

**Comment by rpostulart** [comment]
Will try immediately, thanks team great job. I will provide you the feedback soon

**Comment by rpostulart** [comment]
I added some error details at the merge page, is that ok?
