### ISSUE TITLE
Signed in user denied access to graphql query

### ISSUE THREAD

**Issue by TheSilentDev** [aws-amplify/amplify-js#5438]
**Describe the bug**
Using multi auth with amplify and react, when unauthenticated I'm able to run queries but If I sign in with Cognito then I'm denied access to graphql, error message below:
``{errorType: "UnauthorizedException", message: "Permission denied"}``

My schema is as follows: 

```
type Event
  @model
  @auth(
    rules: [
      { allow: public, provider: iam, operations: [read] }
      { allow: private, operations: [read] }
      { allow: groups, groups: ["ADMIN"], operations: [create, read, update, delete] }
    ]
  ) {
  id: ID!
  name: String
  startDate: AWSDateTime
  endDate: AWSDateTime
}
```

The query I'm running is as follows: 

```
const { data } = await API.graphql({
          query: listEvents,
          variables: {
            filter: {
              type: {
                eq: type.slice(0, -1).toUpperCase(),
              },
            },
          },
          authMode: 'AWS_IAM',
        })
```

**Expected behavior**
I expected that as a signed-in user I would still have access to running a query. But I'm assuming once I'm signed in with Cognito, no 'IAM' public credentials are created and thus my query fails. The issue I'm having is right now, am I forced to run two different queries for when a user is signed in and when a user is signed out?

**Comment by rpostulart** [comment]
Not sure, but can be similar because datastore is using subscriptions.

https://github.com/aws-amplify/amplify-js/issues/5601

**Comment by TheSilentDev** [comment]
> @TheSilentDev can you confirm this is similar to the above issue? Please let us know.

Not quite, however, I've worked around it. Which was just tracking AuthMode in a ContextProvider which swaps out 'AWS_IAM' and 'AMAZON_COGNITO_USER_POOLS' as its value. 

I guess I was just hoping that amplify would execute queries with the correct authMode, if I'm signed out, use either 'API_KEY' or 'AWS_IAM' and COGNiTO_POOLS if signed in.
