### ISSUE TITLE
No identityID return from currentUserInfo after federatedSignIn with apple

### ISSUE THREAD

**Issue by wattanakorn495** [aws-amplify/amplify-js#5440]
**Describe the bug**
I try to integrate sign in with apple to my react-native app by using identityToken from 
[@invertase/react-native-apple-authentication](https://github.com/invertase/react-native-apple-authentication)
and put AppID(bundleID) to ServiceID field in Cognito identity pool
[Sign in with Apple (Identity Pools)](https://docs.aws.amazon.com/cognito/latest/developerguide/apple.html)
then sign in work and identityId was created
but when I call Auth.currentUserInfo() it only return {}

**To Reproduce**
1. Put AppID to ServiceID field in Cognito identity pool
2. Follow sign in step from react-native-apple-authentication
3. Put identityToken to Auth.federatedSignIn('appleid.apple.com', identityToken)
4. Call Auth.currentUserInfo()

**Expected behavior**
Auth.currentUserInfo() return identityid

**Screenshots**

**Smartphone (please complete the following information):**

- Device: iPhone8
- OS:  iOS13
- Version: 
  -react-native 0.61.5
  -aws-amplify: 3.0.8
  -react-native-apple-authentication: 0.2.0

**Additional context**
I need identityid to query data from graphql

**Sample code**

**Comment by mllrmat** [comment]
I think this is not an appleSignIn issue but related to #5280. I see this with facebook and google login as well. This is not working in V3 - in V2 this is working correctly.

**Comment by bernhardt1** [comment]
@wattanakorn495 did you find any solution for this? I also need identityId to query from graphQL

**Comment by JoeBakalor** [comment]
@bernhardt1 Any luck finding a workaround?

**Comment by bernhardt1** [comment]
@JoeBakalor Yea

They had changed the login logic pretty heavily since the old version I had been using.

you no longer pass an identity token to federatedSignIn.

1. Instead do sign in with just the provider as an argument:
- Auth.federatedSignIn({ provider: 'Facebook' });

2. attach a listener to catch sign in events
```
Hub.listen('auth', ({ payload: { event, data } }) => {
        console.log('event', event);
        switch (event) {
          case 'signIn':
            // this.setState({ user: data });
            this.verifySignIn(data);
            break;
          case 'signOut':
            // this.setState({ user: null });
            break;
          case 'customOAuthState':
            // this.setState({ customState: data });
            break;
          default:
        }
      });
```

3. The identityId should be part of the userCredentials after signing in
```
verifySignIn = async (data) => {
    const currentUserCredentials = (await getCurrentUserCredentials()) || false;

    if (currentUserCredentials?.identityId) {
      AsyncStorage.setItem('federatedId', JSON.stringify(currentUserCredentials.identityId));
      this.handleSignIn(data);
    }
  }
```

**Comment by rapgithub** [comment]
I tried that way too and the problems persists!! no identityID after federatedSignIn with apple! :(
