### ISSUE TITLE
Example using Cognito Hosted UI with Vue.js (OAuth 2.0 Auth Code Grant Flow)

### ISSUE THREAD

**Issue by mrichman** [aws-amplify/amplify-js#5444]
I am using Vue.js and the Cognito hosted UI. My app client is set for OAuth 2.0 authorization code grant flow.

How can I use this library to integrate my logins in this manner?

**Comment by waelio** [comment]
Same here, I am using the hosted UI, upon successful login I get redirected back with auth?code=1234567890

I am assuming that I need to post this code back to Cognito to get the token and the user info.
What is the Auth function?

**Comment by stocaaro** [comment]
Looks related to #6236

**Comment by cwomack** [comment]
@mrichman and @waelio wanted to follow up on this, apologies on the delayed reply.  It sounds like you were trying to use Amplify with the Hosted UI and currently the way to do that is to first integrate your Amplify app with your Auth resources.  You would then want to use `Auth.federatedSignIn()` ([link](https://aws-amplify.github.io/amplify-js/api/classes/authclass.html#federatedsignin)) without passing in a provider which would open up the Hosted UI where a user can sign in and get provided with an active session from Cognito to then be redirected back to the app.  

Let me know if you have any questions, but this should take care of the use case you've described.

**Comment by nadetastic** [comment]
Hi 👋 Closing this issue as we have not heard back from you. The above comment from @cwomack should address the issue, however if you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
