### ISSUE TITLE
Uncaught TypeError: Cannot set property 'createCredentials' of undefined 

### ISSUE THREAD

**Issue by phstc** [aws-amplify/amplify-js#546]
This is just to continue the thread left in the archived repo: https://github.com/aws/amazon-cognito-identity-js/issues/679

![image](https://user-images.githubusercontent.com/105652/38055811-c50cf334-32a8-11e8-8b87-64013b592449.png)

**Comment by phstc** [comment]
@PrashanthThugaiah are you also using `babel-polyfill`?

**Comment by PrashanthThugaiah** [comment]
No.

**Comment by supun19** [comment]
I also have this issue. any updates

**Comment by stevemao** [comment]
See this for solution: https://github.com/MacKentoch/react-redux-bootstrap-webpack-starter/issues/5#issuecomment-335106227

**Comment by Lasim** [comment]
Same here.

**Comment by simodroussi** [comment]
I've had the same problem when I build my app (in dev mode its working well). I have pinned down the problem to aws-amplify installing amazon-cognito-identity-js in /node_modules with crypto-browserify@^1.0.9 dependency. I fixed it by updating crypto-browserify to 3.12.0 in amazon-cognito-identity-js but that only works in my local machine. When my colleagues use 'npm install' in their machines, they run into the same issue. Is there any fix for this?

**Comment by davidpbowe** [comment]
This might not be the best solution but just to get the application working I removed the `UglifyJSPlugin` from my webpack config. Then built and ran it again

**Comment by simodroussi** [comment]
You are right it's not the best solution. At least for me.

**Comment by daviskoh** [comment]
same issue. yikes..

**Comment by daviskoh** [comment]
https://github.com/MacKentoch/react-redux-bootstrap-webpack-starter/issues/5#issuecomment-335106227

worked for me though I am unsure how viable this is for everyone

**Comment by elorzafe** [comment]
Closed by PR #1773
