### ISSUE TITLE
Amplify on Kinesis Firehose Analytics saves corrupt data.

### ISSUE THREAD

**Issue by iKev** [aws-amplify/amplify-js#5463]
**Describe the bug**
I created a clean react app using aws-amplify 2.2.6 and aws-amplify-react 3.1.7 then I sent events (Analytics.record) to Kinesis Firehose and the data on S3 files looks good. When I updated to aws-amplify 3.0.8 and aws-react 4.1.7 the data was sent successfully but when I checked the data on S3 files the entries appear with strange characters (encryption is disabled).

**To Reproduce**

1. Create a new react app
2. Install aws-amplify 3.0.8 and aws-amplify-react 4.1.7
3. Follow steps to implement Analytics (Kinesis or Kinesis Firehose on S3 storage) https://aws-amplify.github.io/docs/js/analytics.
4. Check data stored on S3 files.
5. If you downgrade to aws-amplify 2.2.6 and aws-amplify-react 3.1.7 changing the package.json and build again it will works.

**Expected behavior**
Data stored on S3 files should be keep like it did with the older version.

**Screenshots**
S3 file with data saved on Kinesis Firehose appear full of strange characters.
![24 Firehose S3 data](https://user-images.githubusercontent.com/2651530/79735027-a5cc0180-82c5-11ea-9214-64840afbe155.png)

**Additional context**
I am using Amplify for Javascript on a React App

**Comment by iartemiev** [comment]
Hey @iKev, this got fixed last week and is in the current **unstable** version of amplify (`npm i aws-amplify@unstable`. It will be part of the next stable release.

**Comment by iKev** [comment]
Thanks @iartemiev
