### ISSUE TITLE
Unable to dismiss keyboard in react native

### ISSUE THREAD

**Issue by MuhammadAhmed1994** [aws-amplify/amplify-js#5465]
- I am using aws-amplify-react-native **Authenticator**. module. I have wrapped it in TouchableWithoutFeedback but the keyboard is still not disappearing. 

- On tapping **sign in** or **sign up** button should be disabled. Currently, we can submit multiple times in the mobile app.

**Comment by amhinson** [comment]
@MuhammadAhmed1994 What version of `aws-amplify-react-native` are you using?
