### ISSUE TITLE
Pressing enter does not trigger Sign In in AmplifySignIn

### ISSUE THREAD

**Issue by faroceann** [aws-amplify/amplify-js#5466]
**Describe the bug**
When signing in using AmplifyAuthenticator, hitting the enter key does not trigger sign in. I am using the React component, but this is likely the case for all of the wrappers. Users must instead click the "Sign in" button. 

It looks like this was previously fixed in #1023, but as far as I can tell this repo has been refactored to have common components since then and a regression may have been introduced when that occurred. 

**To Reproduce**

1. Wrap app in `withAuthenticator` 
2. Enter credentials in the fields
3. Press enter key while in the password field
4. Nothing happens

**Expected behavior**
When pressing enter using the SignIn component, the onKeyDown event captures charcode `13` and triggers Sign In.

**Comment by jordanranz** [comment]
We opted to not implement this from a `document` level due to conflicts with shadow DOM. I will however PR adding this back to listen to the keyboard event from a component level.

**Comment by faroceann** [comment]
@jordanranz  Thanks, this is so much better. But, this very reliably triggers an error when using `AmplifySignIn`, for example. If you enter some credentials and hit enter, the password is not populated in state yet. This triggers the `Custom auth lambda trigger is not configured for the user pool.` error, because a request goes out to the Cognito IDP without a `password`. If instead of hitting enter, you click **Sign In**, this error does not occur.
