### ISSUE TITLE
Get 'id' from a row entry in DynamoDB/AppSync?

### ISSUE THREAD

**Issue by chai86** [aws-amplify/amplify-js#5470]
I want to do something seemingly so simple, but i am a bit lost as to how to do it: I have a table with user information already in it. Here's the Schema:

    type Users @model {
      id: ID!
      userName: String
      firstname: String
      weblink: String
      email: String
      mobileNum: String
     .
     .
     .
    }
    
    
    //**Here's my current Query.js**
    export const getUsers = `query GetUsers($id: ID!) {
      getUsers(id: $id) {
        id
        userName
        firstname
        weblink
        email
        .
        .
        .
      }
    }
    `;

This table is populated in DynamoDB when i check my AWS console. What i need is to be able to get the id from the table using the userName (not vice versa). The id is generated when i createUser() and it's used throughout my app to get all my user's information. However when a user signs in on a new phone, this id isn't available anymore. So when they sign in via Cognito, i do know the userName and all i need to do is retrieve this id. Because there's only one unique **userName**, it should only return one **id**

How can this be done easily?

**Comment by mauerbac** [comment]
hi @chai86 - this seems more like a general GQL question. Will move into your discussion section!
