### ISSUE TITLE
Predication API Error for comprehend and translate - Unhandled Rejection (InvalidSignatureException): The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

### ISSUE THREAD

**Issue by wongcyrus** [aws-amplify/amplify-js#5472]
**Describe the bug**
After upgrade to  "aws-amplify": "^3.0.8" and  "aws-amplify-react": "^4.1.6",
Prediction API for comprehend and translate with error.

Unhandled Rejection (InvalidSignatureException): The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
(anonymous function)
/home/protocols/Aws_json1_1.ts:1090
  1087 | case "ExternalServiceException": return [3 /*break*/, 2];
  1088 | case "com.amazonaws.cognito.identity.model#ExternalServiceException": return [3 /*break*/, 2];
  1089 | case "InternalErrorException": return [3 /*break*/, 4];
> 1090 | case "com.amazonaws.cognito.identity.model#InternalErrorException": return [3 /*break*/, 4];
       | ^  1091 | case "InvalidParameterException": return [3 /*break*/, 6];
  1092 | case "com.amazonaws.cognito.identity.model#InvalidParameterException": return [3 /*break*/, 6];
  1093 | case "NotAuthorizedException": return [3 /*break*/, 8];
View compiled
▼ 3 stack frames were expanded.
step
node_modules/tslib/tslib.es6.js:100
next
node_modules/tslib/tslib.es6.js:81
fulfilled
node_modules/tslib/tslib.es6.js:71

      let language = await Predictions.interpret({
        text: {
          source: {
            text: this.state.question,
          },
          type: "LANGUAGE"
        }
      });
      sourceLanguage = language.textInterpretation.language;
      if (!sourceLanguage.startsWith("en")) {
        const translatedMessage = await Predictions.convert({
          translateText: {
            source: {
              text: this.state.question,
              language: sourceLanguage
            },
            targetLanguage: "en"
          }
        });
        message = translatedMessage.text;
        this.setState({ englishQuestion: message });
        console.log(this.state.question, message);
      }

I tried to refresh the new token but it does not work too.

**Comment by Amplifiyer** [comment]
@wongcyrus, can you post your request headers and request body/payload here (remove any sensitive information such as credentials)

**Comment by wongcyrus** [comment]
> @wongcyrus, can you post your request headers and request body/payload here (remove any sensitive information such as credentials)

**Header:**
POST / HTTP/1.1
Host: comprehend.us-east-1.amazonaws.com
Connection: keep-alive
Content-Length: 56
Pragma: no-cache
Cache-Control: no-cache
authorization: AWS4-HMAC-SHA256 Credential=XXXXXXXXX/20200423/us-east-1/comprehend/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-security-token;x-amz-target;x-amz-user-agent, Signature=56e90a5fffd4beaa643f52401fd73785d8e9b134aed58860da050c01730986fd
content-type: application/x-amz-json-1.1
x-amz-content-sha256: 7ee713812a31e0badafaee0f3269759fc576c57749d602c61430652066e20d34
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
x-amz-security-token: XXXXXXXXXXXXXXXXXXXXXXX
Sec-Fetch-Dest: empty
x-amz-target: Comprehend_20171127.DetectDominantLanguage
x-amz-date: 20200423T033112Z
x-amz-user-agent: aws-sdk-js-v3-@aws-sdk/client-comprehend/1.0.0-beta.3 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36 aws-amplify/3.2.3 js
Accept: */*
Origin: https://callouts.d2l221pdutuhiq.amplifyapp.com
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Referer: https://callouts.d2l221pdutuhiq.amplifyapp.com/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,zh-TW;q=0.8,zh;q=0.7

**payload** 
{"Text":"わたしは、あなたを愛しています"}

**Response Header**
HTTP/1.1 400 Bad Request
x-amzn-RequestId: a9adf8c6-183a-42de-a121-ac6864fb216b
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: x-amzn-RequestId,x-amzn-ErrorType,x-amzn-ErrorMessage,Date
Content-Type: application/x-amz-json-1.1
Content-Length: 229
Date: Thu, 23 Apr 2020 03:31:12 GMT
Connection: close

**Response Body**
{"__type":"InvalidSignatureException","message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}

**Comment by Amplifiyer** [comment]
@wongcyrus, thanks for the info, it seems to be an issue with aws-sdk to not be able to handle UTF-8 characters correctly. https://github.com/aws/aws-sdk-js-v3/issues/1100 seems to be related.

**Comment by wongcyrus** [comment]
@Amplifiyer Any update? I tried to install the latest version of package and the problem is still there.

**Comment by bdpaul99** [comment]
@wongcyrus I have also installed the latest version of the package. Problem persists for me as well

**Comment by Amplifiyer** [comment]
@wongcyrus and @bdpaul99 the root cause is the issue I linked earlier in aws-sdk aws/aws-sdk-js-v3#1100. aws-sdk has fixed the issue, it will be available once aws-sdk does a release with the fix and amplify releases with the new version of aws-sdk containing the fix. I'll keep this issue updated when that happens.

**Comment by wongcyrus** [comment]
I upgraded the dependencies to 
"dependencies": {
    "@aws-amplify/api": "^3.1.10",
    "@testing-library/jest-dom": "^5.8.0",
    "@testing-library/react": "^10.0.4",
    "@testing-library/user-event": "^10.3.4",
    "aws-amplify": "^3.0.11",
    "aws-amplify-react": "^4.1.10",
    "aws-sdk": "^2.682.0",
    "es6-promise": "^4.2.8",
    "face-api.js": "^0.22.2",
    "isomorphic-fetch": "^2.2.1",
    "microphone-stream": "^5.0.1",
    "moment-timezone": "^0.5.31",
    "react": "^16.13.1",
    "react-data-export": "^0.6.0",
    "react-dom": "^16.13.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "3.4.1",
    "react-webcam": "^5.0.1",
    "semantic-ui-react": "^0.88.2",
    "xlsx": "^0.16.1"
  }

The problem is changed to have problem in Chinese 你好嗎 or Japanese わたしは、あなたを愛しています.
For language like france "je t'aime" , it works fine.

**Comment by Amplifiyer** [comment]
@wongcyrus can you test again with latest amplify and let us know if it's fixed?

**Comment by wongcyrus** [comment]
The problem solved with the latest version.
    "aws-amplify": "^3.0.13",
    "aws-amplify-react": "^4.1.12",
    "aws-sdk": "^2.686.0",
