### ISSUE TITLE
JWT Token verification

### ISSUE THREAD

**Issue by remyferre** [aws-amplify/amplify-js#5477]
**Is your feature request related to a problem? Please describe.**
I'm using Amplify for a react-native app. According to this [Cognito page](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html), JWT tokens should be first verified in order to be trusted. The article suggests it *might* already be handled by SDKs, but I haven't found any documentation on the matter in Amplify's documentation. I don't know what I should do.

**Describe the solution you'd like**
I would like to know if I should implement JWT token verification in my mobile app or not.

**Describe alternatives you've considered**
Github Discussions may be more appropriate for this question but there is already a similar question [there](https://github.com/aws-amplify/amplify-js/discussions/5381) that is unanswered. That's why I'm creating this issue. Security is an important topic so I think many developers like me want to double-check these kind of things.

**Comment by elorzafe** [comment]
@remyferre  The tokens are not validated on the client, the library can ask for tokens and refresh those in case they are expired however the tokens should be always verified on the backend for Authorization purposes.

What is your use case to validate the token on the client?

**Comment by remyferre** [comment]
No use case really. I thought the client also had to validate tokens for security purposes, but your response seems to imply that only the server really do.
Thanks for clearing that up!

**Comment by IsaacTrevino** [comment]
### **This should be well documented on the amplify auth library (overview) page. I assumed the Auth API Library handled all of this, of course I may have not read between the lines.** 

[Amplify - Auth with AWS Doc](https://docs.amplify.aws/lib/auth/overview/q/platform/js#authentication-with-aws)
The above doc approach mentions "Authorization is often done in one of two ways" thus leading me to conclude amplify Auth API was the alternative.

[Amplify - Accessing AWS](https://docs.amplify.aws/lib/auth/overview/q/platform/js#accessing-aws-services)
This doc explain an automatic approach to authentication handling such as expiration, and refresh.
"Amplify automatically signs requests with short term credentials from a Cognito Identity Pool which automatically expire, rotate, and refresh by the Amplify client libraries"

By reading @remyferre's reply, it clearly states token validation needs to be done on the backend. A bit misleading from the doc's end.. eh
