### ISSUE TITLE
Amplify UI - Angular - amplify-authenticator doesn't fire (handleSubmit) Event

### ISSUE THREAD

**Issue by pechisworks** [aws-amplify/amplify-js#5480]
**Describe the bug**
On the new amplify-authenticator component I am trying to hook in the `handleSubmit` Event for adding additional validationData. But it doesn't get fired, neither on the `amplify-sign-up` or the `amplify-sign-in` component. I've also tried it with the newest unstable version.

**To Reproduce**

```
<amplify-authenticator>
   <amplify-sign-up  slot="sign-up" (handleSubmit)="handleSignUpSubmit($event)">
   </amplify-sign-up>

   <amplify-sign-in slot="sign-in" (handleSubmit)="handleSignInSubmit($event)">
   </amplify-sign-in>
</amplify-authenticator>
```

In my Typescript-File:
```
handleSignUpSubmit(event: any) {
  console.log('HANDLE SUBMIT!', event);
}
handleSignInSubmit(event: any) {
  console.log('HANDLE SUBMIT!', event);
}
```

**Expected behavior**
handleSubmit Event should get fired.

**Packages:**

- @aws-amplify/core@^2.2.4
- @aws-amplify/ui-angular@0.2.3-unstable.21
- @aws-amplify/ui-components@0.3.3-unstable.21

**Comment by jordanranz** [comment]
Hey @pechisworks,

Since `handleSubmit` is a `prop` and not an `event` the code should be:
```
<amplify-authenticator>
   <amplify-sign-up  slot="sign-up" [handleSubmit]="handleSignUpSubmit">
   </amplify-sign-up>

   <amplify-sign-in slot="sign-in" [handleSubmit]="handleSignInSubmit">
   </amplify-sign-in>
</amplify-authenticator>
```

Let me know if that works

**Comment by pechisworks** [comment]
Hi @jordanranz.
Yes, using a `prop` instead of an `event` works.

**Comment by juancpgo** [comment]
I need to setup a custom `handleSubmit` function for the case of web components (no framework).

I need to create a custom `username` for the user in the background during sign up. The user will fill out an email, which will be an alias.

Can anyone help me with that?

**Comment by juancpgo** [comment]
> Hey @pechisworks,
> 
> Since `handleSubmit` is a `prop` and not an `event` the code should be:
> 
> ```
> <amplify-authenticator>
>    <amplify-sign-up  slot="sign-up" [handleSubmit]="handleSignUpSubmit">
>    </amplify-sign-up>
> 
>    <amplify-sign-in slot="sign-in" [handleSubmit]="handleSignInSubmit">
>    </amplify-sign-in>
> </amplify-authenticator>
> ```
> 
> Let me know if that works!
> 
> Also, keep in mind that overriding the `handleSubmit` will override the internal `signUp` or `signIn` function

Will this work for the web components version of Amplify UI Componets??
