### ISSUE TITLE
Tagging in Storage.put doesn't work with v3

### ISSUE THREAD

**Issue by grigull** [aws-amplify/amplify-js#5490]
Previously working in V2 was the ability to add tagging to a file that is uploaded through the Storage.put function. 
```
Storage.put(key, file, {
          level: "private",
          tagging: "delete=24"
        })
```
The files do successfully upload, but the tags are no longer present on the objects in the s3 bucket. 

Amplify core - 3.2.4
Amplify storage 3.1.7

**Comment by Amplifiyer** [comment]
@grigull can you confirm if you are experiencing this issue with >5MB files only? We had an issue which is now fixed in PR #5487 and is available to test on unstable version of aws-amplify. Please let us know if using the unstable version fixed it for you.

**Comment by grigull** [comment]
@Amplifiyer I can confirm that it is working for smaller files, but not for larger ones. I installed the unstable version using ```npm i aws-amplify@3.x.x-unstable.xx``` but it doesn't appear to be any different with that. Is this the correct way to test the current unstable build?

**Comment by Amplifiyer** [comment]
@grigull the fix is released on stable version, can you try again after deleting your lock files and node_modules and see if the error is resolved?

**Comment by grigull** [comment]
@Amplifiyer works perfectly. Tested with a few different file sizes.
