### ISSUE TITLE
Problem customizing placeholder for email field 

### ISSUE THREAD

**Issue by faroceann** [aws-amplify/amplify-js#5498]
**Describe the bug**
The [default placeholder for the email input field ](https://github.com/aws-amplify/amplify-js/blob/025028d48bda5236751878c85ce669d2433a3067/packages/amplify-ui-components/src/common/Translations.ts#L18) should be something more generic, like, "Enter your email", rather than a reference to Amplify (`amplify@example.com`). 

This is primarily an issue because customizing that field through the `formFields` attribute is still a significant effort, even on `0.2.3-unstable.3` – One friction point I can think of: If you use the `formFields` attribute,  the **Forgot Password** link and handler go away and need to be manually reimplemented.

**To Reproduce**

1. Use the default sign in form with  `usernameAlias="email"`
2. Note the placeholder text in the email input

**Comment by jordanranz** [comment]
Merged your PR. I will mark this as a feature request to improve passing in values like `placeholder` without having to reimplement something like the `hint`

**Comment by faroceann** [comment]
Thanks @jordanranz 👍

**Comment by ashika01** [comment]
Closing this issue since the formfields now have defaults for hint, this way you dont have to implement hint separately. Info - https://github.com/aws-amplify/amplify-js/issues/5298#issuecomment-626837509
