### ISSUE TITLE
Unable to use library in a simple nodejs script 

### ISSUE THREAD

**Issue by omar-dulaimi** [aws-amplify/amplify-js#5504]
**Describe the bug**
I've been trying to use Storage to list s3 objects and then reupload them, since the library has a better api. But errors of 
```
[WARN] 50:48.296 AWSS3Provider - list error { TypeError: stream.pipe is not a function
    at Promise (/Images-Validator/node_modules/@aws-sdk/stream-collector-node/build/index.js:6:12)
    at new Promise (<anonymous>)
    at Object.exports.streamCollector (/Images-Validator/node_modules/@aws-sdk/stream-collector-node/build/index.js:4:39)
```
keep showing up for some reason everytime I try to list an s3 bucket objects.
**To Reproduce**

    Storage.list(`${s3Prefix}/`, {
      level: "public",
    }).then((res) => {
      console.log("getS3ImagesOfAd -> res", res);
    });

So is library usable like that? without React, without the browser? if not, then I'll close this report without expanding on the details.

**Comment by elorzafe** [comment]
@omar-dulaimi 

Amplify doesn't officially support NodeJS, where are you trying to use it?

**Comment by omar-dulaimi** [comment]
@elorzafe On Aws Lambda.

**Comment by undefobj** [comment]
Amplify is a library designed for use in frontend mobile/web application. It's not supported in backend. For those use cases - please leverage the AWS nodejs SDK
