### ISSUE TITLE
Pressing enter does not trigger signInWithPassword

### ISSUE THREAD

**Issue by faroceann** [aws-amplify/amplify-js#5512]
**Describe the bug**
After #5466 was merged, it looks like when signing in, typing in a password, and quickly hitting "Enter" –  which now triggers the `handleSubmit` in `amplify-auth-fields`– the `signInWithoutPassword` flow is triggered, due to the state not yet populating with the password. If the users clicks to submit the form instead of hitting Enter, the library goes through the correct flow and signs in with the password. 

**To Reproduce**
1. On latest, configure the following:
```
 <AmplifyAuthenticator
            usernameAlias="email"
          >
            <AmplifySignIn
              slot="sign-in"
              usernameAlias="email"
            />
 </AmplifyAuthenticator>
```
2. Enter credentials and hit Enter from the password field
3. Observe error

**Expected behavior**
Password in the form field is correctly populated in state

**Comment by ashika01** [comment]
@faroceann Thanks for raising this issue. I was able to reproduce this and working on PR for fix. Testing it out with different browsers before PR.

**Comment by jordanranz** [comment]
We release this fix to the latest version of all UI libraries.
