### ISSUE TITLE
cdk synth does not include the metadata in the json generated file

### ISSUE THREAD

**Issue by VXConsulting** [aws-amplify/amplify-js#5515]
When running `cdk synth MyStackName` CDKMetadata are shown but not included in the template.json generated file.

We have a simple stack containing 3 parameters and 3 outputs, with no resource.
`cdk deploy MyStackName` works fine

But in a pipeline, CodeBuild will generate the template.json without any resource.
Then the CloudFormation action will generate a ValidationException :
`"errorMessage": "Template format error: At least one Resources member must be defined."`

**Expected behavior**
We expect to have the same behavior as `cdk deploy` command which use the yaml generated template because, in the following template, there is a Resource:
`Parameters:
  sdgDomainNameParam:
    Type: String
  sdgDomainCertificateArnParam:
    Type: String
  destinationEnvironmentParam:
    Type: String
Outputs:
  sdgDomainName:
    Description: Domain Name
    Value:
      Ref: sdgDomainNameParam
    Export:
      Name: sdgDomainName
  sdgDomainCertificateArn:
    Description: Domain Certificate Arn
    Value:
      Ref: sdgDomainCertificateArnParam
    Export:
      Name: sdgDomainCertificateArn
  destinationEnvironment:
    Description: destination Environment
    Value:
      Ref: destinationEnvironmentParam
    Export:
      Name: destinationEnvironment
Resources:
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.34.1,@aws-cdk/assets=1.34.1,@aws-cdk/aws-apigateway=1.34.1,@aws-cdk/aws-applicationautoscaling=1.34.1,@aws-cdk/aws-autoscaling-common=1.34.1,@aws-cdk/aws-certificatemanager=1.34.1,@aws-cdk/aws-cloudformation=1.34.1,@aws-cdk/aws-cloudfront=1.34.1,@aws-cdk/aws-cloudwatch=1.34.1,@aws-cdk/aws-cognito=1.34.1,@aws-cdk/aws-dynamodb=1.34.1,@aws-cdk/aws-ec2=1.34.1,@aws-cdk/aws-events=1.34.1,@aws-cdk/aws-iam=1.34.1,@aws-cdk/aws-kms=1.34.1,@aws-cdk/aws-lambda=1.34.1,@aws-cdk/aws-logs=1.34.1,@aws-cdk/aws-s3=1.34.1,@aws-cdk/aws-s3-assets=1.34.1,@aws-cdk/aws-sqs=1.34.1,@aws-cdk/aws-ssm=1.34.1,@aws-cdk/cloud-assembly-schema=1.34.1,@aws-cdk/core=1.34.1,@aws-cdk/custom-resources=1.34.1,@aws-cdk/cx-api=1.34.1,@aws-cdk/region-info=1.34.1,jsii-runtime=node.js/v12.14.1
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2`

**Code Snippet**
```
const sdgDomainName = new CfnParameter(this, 'sdgDomainNameParam').value.toString();
        const sdgDomainCertificateArn = new CfnParameter(this, 'sdgDomainCertificateArnParam').value.toString();
        const sdgDestinationEnvironment = new CfnParameter(this, 'destinationEnvironmentParam').value.toString();

        new CfnOutput(this, "sdgDomainName", {
            description: "Domain Name",
            exportName: 'sdgDomainName',
            value: sdgDomainName
        });

        new CfnOutput(this, "sdgDomainCertificateArn", {
            description: "Domain Certificate Arn",
            exportName: 'sdgDomainCertificateArn',
            value: sdgDomainCertificateArn
        });

        new CfnOutput(this, "destinationEnvironment", {
            description: "destination Environment",
            exportName: 'destinationEnvironment',
            value: sdgDestinationEnvironment
        });
```

Generated template
`{
  "Parameters": {
    "sdgDomainNameParam": {
      "Type": "String"
    },
    "sdgDomainCertificateArnParam": {
      "Type": "String"
    },
    "destinationEnvironmentParam": {
      "Type": "String"
    }
  },
  "Outputs": {
    "sdgDomainName": {
      "Description": "Domain Name",
      "Value": {
        "Ref": "sdgDomainNameParam"
      },
      "Export": {
        "Name": "sdgDomainName"
      }
    },
    "sdgDomainCertificateArn": {
      "Description": "Domain Certificate Arn",
      "Value": {
        "Ref": "sdgDomainCertificateArnParam"
      },
      "Export": {
        "Name": "sdgDomainCertificateArn"
      }
    },
    "destinationEnvironment": {
      "Description": "destination Environment",
      "Value": {
        "Ref": "destinationEnvironmentParam"
      },
      "Export": {
        "Name": "destinationEnvironment"
      }
    }
  }
}`

**Comment by jordanranz** [comment]
Hey @VXConsulting, this seems to have nothing to do with the `amplify-js` library. 

Please open an issue in the AWS CDK library [here](https://github.com/aws/aws-cdk/issues).
