### ISSUE TITLE
Angular Amplify + DataStore: no cloud syncing, no error logs.

### ISSUE THREAD

**Issue by sebboe** [aws-amplify/amplify-js#5516]
**Describe the bug**

Data are added locally but not synced to DynamoDB.
- No logs on the client-side.
- No CloudWatch logs.

When data is directly sent through API, it's correctly written on DynamoDB, and I can see CloudWatch logs. I also have the "AmplifyDataStore-xxxxxxxx" table generated.

Already tried to:
- Clean the local database and DynamoDB table.
- Re-generate "amplify codegen".
- Re-generate "amplify codegen models".
- Re-push the backend "amplify push".

**Expected behavior**
Locally added data should sync with cloud.

**Code Snippet**
```
import { Component, OnInit } from '@angular/core';
import { AuthService } from '../services/auth.service'

import { AmplifyService } from 'aws-amplify-angular';
import { APIService } from '../services/api.service'

import Amplify from "@aws-amplify/core";
import { DataStore, Predicates } from "@aws-amplify/datastore";
import { Test } from "../../models";

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage implements OnInit {

constructor( public authService: AuthService, private amplifyService: AmplifyService, private apiService: APIService ) {}

  async addNote(form){
    //This line correcly push data on DynamoDB without going to local
    await this.apiService.CreatePrivateNote(form.value).catch(err=>console.log(err));
    //This keep data locally and didn't sync
    await DataStore.save(
      new Test({content: form.value.content})
    );
    const test = await DataStore.query(Test as any);
    console.log(test); //output locally saved data
    form.reset();
  }
}
```
And here is the schema.graphql:
```
type Test
  @model
{
  id: ID!
  content: String!
}
```
**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which resources do you have configured?

Auth and API are configured.

  * If applicable, please provide your `aws-exports` file:
```
const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:xxxx",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_xxxx",
    "aws_user_pools_web_client_id": "xxx",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xxxxxxxxxx.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};
```
```
  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 167.71 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    npm: 6.13.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.122
  npmPackages:
    @angular-devkit/build-angular: ~0.803.20 => 0.803.26
    @angular/cli: ~8.3.23 => 8.3.26
    @angular/common: ~8.2.14 => 8.2.14
    @angular/compiler: ~8.2.14 => 8.2.14
    @angular/compiler-cli: ~8.2.14 => 8.2.14
    @angular/core: ~8.2.14 => 8.2.14
    @angular/forms: ~8.2.14 => 8.2.14
    @angular/language-service: ~8.2.14 => 8.2.14
    @angular/platform-browser: ~8.2.14 => 8.2.14
    @angular/platform-browser-dynamic: ~8.2.14 => 8.2.14
    @angular/pwa: ^0.901.1 => 0.901.1
    @angular/router: ~8.2.14 => 8.2.14
    @angular/service-worker: ~8.2.14 => 8.2.14
    @aws-amplify/core: ^3.2.4 => 3.2.4
    @aws-amplify/datastore: ^2.0.8 => 2.0.8
    @aws-amplify/pubsub: ^3.0.8 => 3.0.8
    @capacitor/cli: 2.0.1 => 2.0.1
    @capacitor/core: 2.0.1 => 2.0.1
    @ionic-native/core: ^5.0.7 => 5.24.0
    @ionic-native/splash-screen: ^5.0.0 => 5.24.0
    @ionic-native/status-bar: ^5.0.0 => 5.24.0
    @ionic/angular: ^5.0.0 => 5.0.7
    @ionic/angular-toolkit: ^2.1.1 => 2.2.0
    @ionic/lab: 3.1.3 => 3.1.3
    @types/jasmine: ~3.3.8 => 3.3.16
    @types/jasminewd2: ~2.0.3 => 2.0.8
    @types/node: ~8.9.4 => 8.9.5
    aws-amplify: ^3.0.8 => 3.0.8
    aws-amplify-angular: ^5.0.8 => 5.0.8
    codelyzer: ^5.0.0 => 5.2.2
    core-js: ^2.5.4 => 2.6.11
    jasmine-core: ~3.4.0 => 3.4.0
    jasmine-spec-reporter: ~4.2.1 => 4.2.1
    karma: ~4.1.0 => 4.1.0
    karma-chrome-launcher: ~2.2.0 => 2.2.0
    karma-coverage-istanbul-reporter: ~2.0.1 => 2.0.6
    karma-jasmine: ~2.0.1 => 2.0.1
    karma-jasmine-html-reporter: ^1.4.0 => 1.5.3
    protractor: ~5.4.0 => 5.4.4
    rxjs: ~6.5.1 => 6.5.5
    ts-node: ~7.0.0 => 7.0.1
    tslib: ^1.9.0 => 1.11.1
    tslint: ~5.15.0 => 5.15.0
    typescript: ^3.5.3 => 3.5.3
    zone.js: ~0.9.1 => 0.9.1
  npmGlobalPackages:
    @angular/cli: 7.3.7
    @aws-amplify/cli: 4.18.0
    @ionic/cli: 6.6.0
    cordova: 9.0.0
    firebase-tools: 8.0.2
    ionic: 5.4.13
    native-run: 0.3.0
    nativescript: 5.3.4
    node-red-admin: 0.1.5
    nodemon: 1.18.10
    npm: 6.13.1
    serverless: 1.40.0
    typescript: 3.8.3
```

**Comment by elorzafe** [comment]
@sebboe are you using prod build?

**Comment by sebboe** [comment]
@elorzafe I tried with ionic serve and ionic build --prod, same result; no error and no sync.

**Comment by elorzafe** [comment]
@sebboe 

We just did a release that fixed an issue with production builds using DataStore maybe that can help the issue. Can you try the latest release of DataStore (2.0.9)?

**Comment by sebboe** [comment]
@elorzafe 
The update didn't fix my problem; I'm still working on my code to find what's wrong. I'll try on a fresh project today, without auth module. Thank you for your help!

**Comment by sebboe** [comment]
I tried a clean app.
- Sync is working without Cognito auth
- Sync is working with default angular auth UI + Cognito until page refresh, after page refresh... Connection refused error.

In my original app, I have a custom auth form. It could be related to that.

**Comment by sebboe** [comment]
Ok, so I think the problem was the use of "[aws-amplify-angular](https://www.npmjs.com/package/aws-amplify-angular)".

By rewriting my auth service directly with the aws-amplify import, it's working.

Before:
`import { AmplifyService } from 'aws-amplify-angular';`
After:
`import { Auth } from 'aws-amplify';`

For now, I need to make two times the call to avoid "Connection refused" error. Didn't tried with production build.

**Comment by sebboe** [comment]
Confirmation: working on dev but not with prod build. Same issue as #5448 .

**Comment by drewdru** [comment]
I had same problem.

I fix it when I change my main.ts
```import awsconfig from './aws-exports'
import PubSub from '@aws-amplify/pubsub';
import API from '@aws-amplify/api';
import Amplify, { Logger } from 'aws-amplify';
import {DataStore} from '@aws-amplify/datastore';

API.configure(awsconfig);
PubSub.configure(awsconfig);
Amplify.configure(awsconfig);
DataStore.configure(awsconfig);
Logger.LOG_LEVEL = 'ERROR';
DataStore.start();```

And now it works fine if I have subscription to Model changes any time I edit data.
```
import {DataStore} from '@aws-amplify/datastore';
import {User} from '../models';


@Component({
  selector: 'app-edit-page',
  templateUrl: './edit-page.component.html',
  styleUrls: ['./edit-page.component.scss']
})
export class EditPageComponent implements OnInit {
  subscription;

  ngOnInit() {
    this.subscription = DataStore.observe<User>(User).subscribe(() => {});
  }
  async update(data) {
    await DataStore.save(User.copyOf(data, (item:MutableModel<User>) => {
      item.phone = data.phone;
    }));
  }
  ngOnDestroy() {
    if (this.subscription) this.subscription.unsubscribe();
  }
}
```
