### ISSUE TITLE
Announcing the Discussions Tab   

### ISSUE THREAD

**Issue by mauerbac** [aws-amplify/amplify-js#5519]
Previously, the Amplify community has interacted with questions via GitHub Issues, utilizing the Questions label. This seemed to work well but in an effort to find a solution that feels like a true forum, we are trying GitHub's new Discussion feature to facilitate Questions from the community. Please keep in mind, this feature is in Alpha.

The tab can be found [here](https://github.com/aws-amplify/amplify-js/discussions). Feel free to ask your own questions or help other members in the community! 

Let us know your feedback in this issue.

**Comment by mtliendo** [comment]
This is a great iteration, though are there any blockers to having a dedicated slack/discord for a more real time approach?

**Comment by mauerbac** [comment]
hey @mtliendo - nice to see you here! Thank you :) About to start week four, and trying to do a lot for the Amplify community. I'm working on exactly that -- Slack/Discord would be an amazing place to get everyone together and discuss in realtime. Should have an update soon but does take time with internal process - stay tuned !

**Comment by rpostulart** [comment]
I believe it's a good idea.
The only difficulty is to identify upfront if something is a question or issue. So where to post those first?
