### ISSUE TITLE
custom urlOpener shows dialog before open.

### ISSUE THREAD

**Issue by arthurliebhardt** [aws-amplify/amplify-js#5531]
**Describe the bug**
I implemented federated sign in with a custom provider with amplify and react native but unfortunately, I get always the dialog from the image. Im Using the InAppBrowser from 'react-native-inappbrowser-reborn' and calling the openAuth method there, I recognized that when I call the only open method it don't show the dialog but I'm not sure if this correct. Are there any tips / guidelines to implement SSO with an inAppBrowser as everything else will be rejected from the Apple App Store.

<img width="584" alt="Screen Shot 2020-04-24 at 01 35 04" src="https://user-images.githubusercontent.com/4281468/80195336-f7ed8980-861b-11ea-8009-527174775a54.png">

**Expected behavior**
If a user sign ins that no Dialog is showing and he can SSO via there provider.

**Code Snippet**
my Amplify config looks like this: 
```
import InAppBrowser from 'react-native-inappbrowser-reborn';
Amplify.configure({
  Auth: {
    region: 'xxx',
    userPoolId: 'xxx,
    userPoolWebClientId: 'xxx,
    oauth: {
      domain: 'xxxx',
      scope: ['email', 'profile', 'openid', 'xxx/app'],
      redirectSignIn: 'xxx://',
      redirectSignOut: 'xx://',
      responseType: 'code', // or 'token', note that REFRESH token will only be generated when the responseType is code
      urlOpener: async (url, redirectSignIn) => {
        await InAppBrowser.isAvailable();

        const response = await InAppBrowser.openAuth(url, redirectSignIn, {
          dismissButtonStyle: 'cancel',
          showTitle: false,
          enableUrlBarHiding: true,
          enableDefaultShare: false,
        });

        if (response.type === 'success' && response.url) {
          Linking.openURL(response.url);
        }
      },
    },
  },
});
```

and for triggerign the sing in I'm using `await Auth.federatedSignIn({ provider: 'tenant name' });`

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```
```
System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 8.13 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.11.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 72.0.2
    Safari: 13.0.5
  npmPackages:
    @babel/core: ^7.6.2 => 7.9.0 
    @babel/runtime: ^7.6.2 => 7.9.2 
    @react-native-community/async-storage: ^1.9.0 => 1.9.0 
    @react-native-community/eslint-config: ^1.0.0 => 1.0.0 
    @react-native-community/masked-view: ^0.1.9 => 0.1.9 
    @react-native-community/netinfo: ^5.7.1 => 5.7.1 
    @react-navigation/bottom-tabs: ^5.2.6 => 5.2.6 
    @react-navigation/native: ^5.1.5 => 5.1.5 
    @react-navigation/stack: ^5.2.10 => 5.2.10 
    aws-amplify: ^3.0.8 => 3.0.8 
    aws-amplify-react-native: ^4.0.4 => 4.0.4 
    axios: ^0.19.2 => 0.19.2 
    babel-jest: ^24.9.0 => 24.9.0 
    eslint: ^6.5.1 => 6.8.0 
    i18n-js: ^3.5.1 => 3.5.1 
    jest: ^24.9.0 => 24.9.0 
    metro-react-native-babel-preset: ^0.58.0 => 0.58.0 
    prettier: ^2.0.2 => 2.0.4 
    react: 16.11.0 => 16.11.0 
    react-devtools: ^4.6.0 => 4.6.0 
    react-native: 0.62.1 => 0.62.1 
    react-native-gesture-handler: ^1.6.1 => 1.6.1 
    react-native-inappbrowser-reborn: ^3.4.0 => 3.4.0 
    react-native-keyboard-aware-scroll-view: ^0.9.1 => 0.9.1 
    react-native-reanimated: ^1.8.0 => 1.8.0 
    react-native-safe-area-context: ^0.7.3 => 0.7.3 
    react-native-screens: ^2.4.0 => 2.4.0 
    react-native-svg: ^12.1.0 => 12.1.0 
    react-test-renderer: 16.11.0 => 16.11.0 
  npmGlobalPackages:
    bower: 1.8.8
    expo-cli: 3.17.24
    grunt-cli: 1.3.2
    lerna: 3.20.2
    lumigo-cli: 0.36.0
    npm: 6.13.7
    react-native-cli: 2.0.1
    serverless: 1.64.0
    sls-dev-tools: 1.0.0
```

</details>

**Smartphone (please complete the following information):**

iPhone 11
iOS 13.2
Safari

**Comment by ThomasCarca** [comment]
I think this is a default behavior for iOS unfortunately... We have the same "issue" for our project but with a different -- less intrusive -- message : 
![image](https://user-images.githubusercontent.com/24562239/80211439-0ba5e980-8636-11ea-855c-99b0906d7461.png)

See this [Stackoverflow thread](https://stackoverflow.com/questions/43510652/custom-url-scheme-without-confirmation-prompt-swift) for more information

**Comment by arthurliebhardt** [comment]
So actually as I wrote above, when I use the open() method instead of openAuth(), it works without this dialog.

**Comment by ThomasCarca** [comment]
Ah sorry I missed that part. The documentation states for openAuth() : 
"_Opens the url with Safari in a modal on iOS using SFAuthenticationSession/ASWebAuthenticationSession, and Chrome in a new custom tab on Android. **On iOS, the user will be asked whether to allow the app to authenticate using the given url (OAuth flow with deep linking redirection)**._"

It therefore looks like it is expected behavior.

**Comment by arthurliebhardt** [comment]
ahh right, thank you. So you are also don't using some other in-app browser or amplify have no other options here also right?

**Comment by ThomasCarca** [comment]
I am personally not using any in-app browser library because I did not know any before, but the one you're using looks nice, I might give it a try ! 
I think by default aws-amplify opens the stock browser on your phone and you can't alter this behavior other than using urlOpener in the configuration. I might be wrong, can anyone confirm ?

**Comment by arthurliebhardt** [comment]
yes amplify opens by default the safari app, but this is not accepted by Apple app store and also not convenient from UX perspective.
