### ISSUE TITLE
Authentication with hosted UI fails on Edge 18 with TypeError: Invalid Argument

### ISSUE THREAD

**Issue by Stereobit** [aws-amplify/amplify-js#5534]
**Describe the bug**
Authentication with any Identity prover fails when redirecting back to WebApp

**What AWS Services are you utilizing?**
Amplify, Auth

**Environment**
Web

**To Reproduce**

1. Initialise with `Auth.configure`
2. Redirect to Hosted UI
3. Authenticate
4. Redirect back
5. See error

**Expected behavior**
Authentication and removal of code query param, like in other browsers

**Code Snippet**
https://github.com/Stereobit/amplify-test

**Screenshots**
![image](https://user-images.githubusercontent.com/150493/80206115-b2cd5580-8623-11ea-8ff1-5799f6de38d4.png)

**What is Configured?**
```
Auth.configure({
  identityPoolId: "XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab",
  region: "eu-west-1",
  userPoolId: "XX-XXXX-X",
  userPoolWebClientId: "a1b2c3d4e5f6g7h8i9j0k1l2m3",
  oauth: {
    domain: "my_cognito_domain",
    scope: ["email"],
    redirectSignIn: "my_cognito_domain",
    responseType: "code",
  },
});
```
See repo for webpack & babel configs

<details>
  <summary><strong>Environment</strong></summary>

```
  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 68.20 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.0.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.122
    Safari: 13.1
  npmPackages:
    @aws-amplify/auth: ^3.2.4 => 3.2.4
    @babel/core: ^7.9.0 => 7.9.0
    @babel/polyfill: ^7.8.7 => 7.8.7
    @babel/preset-env: ^7.9.5 => 7.9.5
    babel-loader: ^8.1.0 => 8.1.0
    html-webpack-plugin: ^4.2.0 => 4.2.0
    webpack: ^4.43.0 => 4.43.0
    webpack-cli: ^3.3.11 => 3.3.11
  npmGlobalPackages:
    npm: 6.14.4
```

</details>

- Device: Desktop
- OS: Windows 10
- Browser Edge
- Version 18

**Comment by russell-dot-js** [comment]
I've detailed the issue here, your feedback is appreciated https://github.com/aws/aws-sdk-js-v3/issues/1107

**Comment by Amplifiyer** [comment]
@Stereobit can you confirm if the issue is fixed with the new amplify version?

**Comment by Stereobit** [comment]
@Amplifiyer Updated last weekend, happy to confirm that this is now fixed. Thank you!
