### ISSUE TITLE
aws-amplify/ui-react - renders component when user is not signed in

### ISSUE THREAD

**Issue by onlybakam** [aws-amplify/amplify-js#5547]
**Describe the bug**

@aws-amplify/ui-react": "^0.2.3

With

```
export default withAuthenticator(App)
```

user is not signed in but `App` is still "rendered" (though not visible). The useEffect hooks are triggered, indicated that it was rendered. the `App` should not be rendered until a user has signed in.

**Comment by ashika01** [comment]
@onlybakam : could you provide us with a sample of ur code?

**Comment by onlybakam** [comment]
```javascript
import Amplify from 'aws-amplify'
import { withAuthenticator } from '@aws-amplify/ui-react'
Amplify.configure(awsconfig)

function App() {
  React.useEffect(() => {
    console.log('called') // <- logged even if user is not authenticated
  }, [])
  return (

    <div>hi</div>
  )
}

export default withAuthenticator(App)
```

**Comment by onlybakam** [comment]
expectation is that `App` is not rendered if state is not signedIn. so something like

```javascript
{state.signedIn ? <Component /> : null}
```

![image](https://user-images.githubusercontent.com/554722/80243626-2f186680-862d-11ea-85ce-b88fa94a7bfc.png)

**Comment by jordanranz** [comment]
Investigating a change to this behavior

**Comment by jordanranz** [comment]
The auth state handling is now baked into the `withAuthenticator`. Please try the `@aws-amplify/ui-react@unstable`. Working on documenting the same behavior for `AmplifyAuthenticator`

**Comment by mtliendo** [comment]
Hey @jordanranz thanks for all your work on the the amplify components and quick turnaround times on issues/feedback!

I was wanting to make a suggestion in holding off on closing issues until any changes are pushed to the main library as opposed to `@unstable`. 

My use case is that I have a few blog posts coming out regarding the auth components, but want to avoid using the `@unstable` package. It would be easier for tracking if I could follow open issues.

**Comment by kmbro** [comment]
Any update on the AmplifyAuthenticator version of this? I am seeing this issue, and seems to be a very strange behavior.

v2, which I use in different projects does not render the app, but here I have the following:

```jsx
const App = () => (
  <AmplifyAuthenticator>
    {/* Customize Amplify Auth Components (https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#sign-up) */}
    {AuthenticationComponents}

    {/* Application */}
    <Provider store={store}>
      <Router>
        <Navigation defaultExpand={true}>
          {/* Main content */}
          <Routes />
        </Navigation>
      </Router>
    </Provider>
  </AmplifyAuthenticator>
);

export default App;
```

Where `AuthenticationComponents` are my custom SignIn/SIgnUp components as a list. I can view everything below `<Provider>` if I am signed in or not.

Could you advise on how to use your fix if it is already in master? or if not, can I follow your merge request when you put it up? thanks

**Comment by trungtin** [comment]
any update on the Authenticator component part? Still having problem with `@aws-amplify/ui-react@0.2.9-unstable.27`
Thanks

**Comment by jordanranz** [comment]
@mtliendo this is good feedback. It auto closes from the hook in the PR but it may be better to hold off on using that.

@kmbro and @trungtin, this is a known limitation to the web component default slot. The recommended way to to manage the application mounting would be to use this guide: https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#manage-auth-state-and-conditional-app-rendering

**Comment by kmbro** [comment]
@jordanranz This worked great for me. Thanks for the linked doc above!
