### ISSUE TITLE
Amplify DataStore not working in AWS but it works locally

### ISSUE THREAD

**Issue by ykbryan** [aws-amplify/amplify-js#5550]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
Amplify datastore works locally but not in AWS. 

**Amplify CLI Version**
4.18.1

**To Reproduce**
git clone https://github.com/ykbryan/aws-amplify-datestore-notes
amplify init
amplify push

then setup AWS Amplify Console and point to a repo. Save & Deploy.

**Expected behavior**
Amplify datastore should work in the AWS environment. 

**Screenshots**
No graphql made.
![Screenshot 2020-04-24 22 25 05](https://user-images.githubusercontent.com/1001146/80223136-75e07d80-867a-11ea-8144-5f243d45ef60.png)

**Desktop (please complete the following information):**
 - OS: Mac, 10.14.6 (18G4032)
 - Node Version. v13.13.0

**Additional context**
Here's the code: https://github.com/ykbryan/aws-amplify-datestore-notes
Here's the url: https://master.d2d8xjcgqu38wl.amplifyapp.com/

**Comment by brene** [comment]
cc @sammartinez - looks like this is a JS issue

**Comment by manueliglesias** [comment]
@ykbryan 

Thanks for reporting this, I tested your repo and was able to replicate the issue and I can confirm that it will be fixed by https://github.com/aws-amplify/amplify-js/pull/5488

You can expect new versions in npm with the fix soon

**Comment by ykbryan** [comment]
tested. it works now, thx!

**Comment by cnegrisanu** [comment]
@elorzafe @manueliglesias 
Hi guys, for me it is not fixed. I am using datastore 2.0.10 and it works fine when on localhost but doesn't work at all when deployed to the amplify hosting.
Going from offline to online, like the above example, doesn't show ANY attempt to reach out to graphql.
