### ISSUE TITLE
[react] Greetings message does not display

### ISSUE THREAD

**Issue by hauntingEcho** [aws-amplify/amplify-js#5551]
**Describe the bug**
The greetings message (Hello, $USERNAME) does not display.

**To Reproduce**
Go to the greetings documentation example, and see no message:
https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#greetings

If you right click and inspect the greetings element in Firefox, you'll be able to see a span element containing the text `Hello, Test Username` in the DOM.  It is not showing in the page, though.

This issue also affects any attempt I've made to use the greeter.

**Expected behavior**
Message `Hello, Test Username` is visible

**Screenshots**
![Capture](https://user-images.githubusercontent.com/1661988/80242290-c203d180-862a-11ea-9bfd-4d254d904b4c.PNG)

**Additional context**

This issue is visible for me in both Firefox 75.0 (64-bit), and Chrome Version 81.0.4044.122 (Official Build) (64-bit).  I'm using Windows Server 2019.

**Comment by jordanranz** [comment]
The `Greetings` component has a username prop that you can pass in to display the username.

**Comment by hauntingEcho** [comment]
right - the example on the documentation page passes "Test Username" to that property, and is not displaying anything

**Comment by jordanranz** [comment]
This will be released to `@aws-amplify/ui-react@unstable` in the next few minutes.

**Comment by mtliendo** [comment]
Is there a release cycle for when items move from unstable?

**Comment by mtliendo** [comment]
https://github.com/aws-amplify/amplify-js/pull/5555#issuecomment-619483949

**Comment by jordanranz** [comment]
@mtliendo the color and styling should be done using CSS rather than adding to the prop api. Could you try adding the following to your `App.css` or similar file:
```
amplify-greetings {
	--background-color: black;
	--border-color: black;
	color: white;
}
```
If this doesn't work for you please feel free to open a new feature request with your asks

**Comment by amirfarrahi** [comment]
what was the fix?

**Comment by amirfarrahi** [comment]
@jordanranz what was the fix to see the user name?
