### ISSUE TITLE
aws-amplify/ui-react - Warning: findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by onlybakam** [aws-amplify/amplify-js#5552]
**Describe the bug**

using `withAuthenticator` yields error (chrome and firefox):

<pre>
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of
AmplifyAuthenticator which is inside StrictMode. Instead, add a ref directly to the element you
want to reference. Learn more about using refs safely
here: https://fb.me/react-strict-mode-find-node
</pre>

**Comment by jordanranz** [comment]
This is fixed here: https://github.com/ionic-team/stencil-ds-plugins/commit/e3cd7091d80f6258c6ae20fe6b551d781e80dad9

Looking at getting this into our core library now. Will post an update when it is ready
