### ISSUE TITLE
Unhandled error in SignUp using ionic when phone_number field is blank: TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by eshacham** [aws-amplify/amplify-js#5564]
**Describe the bug**
phone_number is a non-required signUpField using the AWS Amplify Auth UI with Angular and Ionic. If a user tries to sign up leaving phone number blank, an unhandled error occurs:

TypeError: Cannot read property 'replace' of undefined
    at composePhoneNumber (common.js:24)
    at SignUpComponentIonic.push../node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-up-component/sign-up.component.core.js.SignUpComponentCore.onSignUp (sign-up.component.core.js:146)
    at Object.eval [as handleEvent] (SignUpComponentIonic.html:45)
    at handleEvent (core.js:38098)
    at callWithDebugContext (core.js:39716)
    at Object.debugHandleEvent [as handleEvent] (core.js:39352)
    at dispatchEvent (core.js:25818)
    at core.js:37030
    at HTMLElement.<anonymous> (platform-browser.js:1789)
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
**To Reproduce**
config:

  usernameAttributes = "email";
  signUpConfig = {
    header: 'Sign Up for This App',
    hideAllDefaults: true,
    defaultCountryCode: '1',
    signUpFields: [
      {
        label: 'Email',
        key: 'email',
        required: true,
        displayOrder: 1,
        type: 'email',
      },
      {
        label: 'Password',
        key: 'password',
        required: true,
        displayOrder: 2,
        type: 'password'
      },{
        label: 'Phone Number',
        key: 'phone_number',
        required: false,
        displayOrder: 3,
        type: 'tel'
      }
    ]
  }
<ion-content>
  <amplify-authenticator [usernameAttributes]="usernameAttributes" [signUpConfig]="signUpConfig" framework="ionic"></amplify-authenticator>
</ion-content>

**Expected behavior**
A blank phone number should not cause an exception if phone number is not a required field.

**Comment by ashika01** [comment]
@eshacham : Could you try the new UI component (@aws-amplify/ui-angular)? https://docs.amplify.aws/ui/auth/authenticator/q/framework/angular

We are going into maintenance mode for aws-amplify-angular soon. So we will only be merging in PR for bugs.

**Comment by eshacham** [comment]
I tried that already: when I upgraded the amplify npm packages to latest, the whole Auth process broke so I had to get back to the older versions (for example, the app lost the reference to the anonymous signed in user).
