### ISSUE TITLE
[API - Observable]: Would it be possible to "dump" zen-observable in favor of RxJS ?

### ISSUE THREAD

**Issue by lambda0xff** [aws-amplify/amplify-js#5571]
**Is your feature request related to a problem? Please describe.**
API subscriptions return Promise or Observable from zen-observable
This can be confusing/annoying when using RxJs

**Describe the solution you'd like**
Dump zen-observable and zen-push in favor of plain RxJs

**Comment by rob3c** [comment]
Yes, this zen-observable dependence is incredibly disappointing!

It's obvious the Amplify team heavily favors React over all other platforms, which is fine as far as it goes. React is a nice framework with a great ecosystem.

However, if the Amplify team has any hope of winning over and keeping Angular users, forcing us to load an additional observable implementation that's incompatible with (and greatly inferior to IMO) the rxjs library used throughout Angular and its ecosystem doesn't seem like the best strategy. It certainly feels to my team like we're second class citizens in the AWS Amplify world.

This is especially felt in the supposedly Angular-specific services created by amplify codegen that are completely un-angular in their use of zen observables for graphql subscriptions. Maybe there's a good argument for using zen in presumably framework-agnostic parts of the amplify library (I doubt it), but at least the Angular-specific bits should be using rxjs.

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
