### ISSUE TITLE
Errors when using Auth and Storage categories directly

### ISSUE THREAD

**Issue by jsangilve** [aws-amplify/amplify-js#5574]
**Describe the bug**

Different errors when using Auth and Storage from the category packages:

**Steps to reproduce**

Using the following packages:

`aws-amplify`: 3.0.9
- @aws-amplify/core@3.2.5
- @aws-amplify/auth@3.2.5
- @aws-amplify/storage@3.1.8

I'm importing the packages as follows: 

```javascript
import Amplify from '@aws-amplify/core';
import AWSStorage from '@aws-amplify/storage';
import AWSAuth from '@aws-amplify/auth';
import awsconfig from '../aws-exports';

Amplify.configure(awsconfig);
```

**First problem**: configuring the category

If I do this, I get the following error:
```
  Error: Amplify has not been configured correctly.
This error is typically caused by one of the following scenarios:

1. Make sure you're passing the awsconfig object to Amplify.configure() in your app's entry point
...
```

However, it works properly if I configure the Auth category directly:

```javascript
AWSAuth.configure(awsconfig);
// I can call here any Auth's API.
```

**Second problem**: Exception `No Credentials` when using the Storage category.

Then, I wanted to use the Storage category imported above. Inside the same file I defined a function that's only called when I have an authenticated user.

```javascript
import Amplify from '@aws-amplify/core';
import AWSStorage from '@aws-amplify/storage';
import AWSAuth from '@aws-amplify/auth';
import awsconfig from '../aws-exports';

Amplify.configure(awsconfig); // this doesn't seem to make a difference
AWSAuth.configure(awsconfig);

// ... more stuff

const listMyBucket = async () => {
  const credentials = await AWSAuth.currentUserCredentials()
  console.log('Credentials', credentials); // I could see the credentials of the authenticated user
  const session = await AWSAuth.currentSession();
  console.log(session); // I could see the session of the authenticated user
  const files = await AWSStorage.list('', { level: 'private'});
};
```

I could see the credentials of the authenticated user, the session, and even the S3 config if I `console.log` the `AWSStorage` obj, but I get this error when calling `AWSStorage.list(...)`

```
AWSS3Provider - ensure credentials error No Auth module registered in Amplify
```

If I understood correctly, the modules register themselves when loaded. Am I doing something wrong?

**It only works if I use `aws-amplify` directly for Auth**:

```javascript
import { Auth as AWSAuth } from 'aws-amplify';
import AWSStorage from '@aws-amplify/storage';
import awsconfig from '../aws-exports';

// Amplify.configure(awsconfig); // this doesn't work

// I still had to configure both categories
AWSAuth.configure(awsconfig);
AWSStorage.configure(awsconfig);
```

```
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:xxxxxx-xxxx-xxxx-xxxx-xxxxxxx",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xxxxxxxxxx",
    "aws_user_pools_web_client_id": "xxxxxxxxxxxxxxx",
    "oauth": {},
    "aws_user_files_s3_bucket": "mybucket",
    "aws_user_files_s3_bucket_region": "us-east-1"
};
```

**Comment by Amplifiyer** [comment]
@jsangilve, can you try importing the `Amplify` object from `aws-amplify` and calling `configure `on that rather than from `@aws-amplify/core`. i.e. try the below (you would not have to use `Auth.configure` or `storage.configure`)
```
import Amplify from 'aws-amplify';
import AWSStorage from '@aws-amplify/storage';
import AWSAuth from '@aws-amplify/auth';
import awsconfig from '../aws-exports';

Amplify.configure(awsconfig);

...
```

**Comment by houmark** [comment]
@Amplifiyer I am also having issues again. I had been using 3.0.x for weeks now and after the initial issues with missing Storage.configure, it was working without issues, but then I upgraded to 3.0.9 and it broke in a really weird way.

When doing Storage.get, it's now trying to get the file from https://localhost/bucketname/filename which is very weird and I'm thinking it may be related to this, due to lack of authentication. I'm testing and seeing if the "workarounds" mentioned by @jsangilve works before I create a new issue. Even downgrading to 3.0.5, for example, did not fix the issue. After that, I cleaned node_modules and it's the same, so my only option was to downgrade to 2.x again to make it work in production.

**Comment by Amplifiyer** [comment]
@houmark did you also try clearing your lock files? There was a bad release from aws-sdk friday night PST that got rolled back (replaced with another version with rolled back code) on Sunday night PST. If your lock file is generated/updated during that period, please try deleting it and try again.

Reference issue: https://github.com/aws-amplify/amplify-js/issues/5572

**Comment by houmark** [comment]
That could be it. My release was Saturday, so I fit perfectly in the timeframe. I'll try to delete the lock file and run it all again and report back. Thanks for the lead.

**Comment by houmark** [comment]
Thanks, my issue resolved by the lock file fix.

**Comment by Amplifiyer** [comment]
Thanks for confirming. Resolving this issue, I'll be updating our docs to address the issue here.

**Comment by jsangilve** [comment]
This is already closed, but my issue was solved as well @Amplifiyer. Thanks
