### ISSUE TITLE
GraphQL subscriptions omit additionalHeaders object in subscribe requests

### ISSUE THREAD

**Issue by bensie** [aws-amplify/amplify-js#5576]
**Describe the bug**
When subscribing and supplying custom headers, these headers are sent for query and mutation requests but not for subscriptions.

Our function that is invoked depends on a custom header (specifies a current account context for account switching).

**To Reproduce**

```js
API.graphql(
  { query, variables },
  { 'X-My-Custom-Header': "hey!" }
).subscribe({})
```

`X-My-Custom-Header` will not be set in the resolver.

**Expected behavior**
I expect custom headers to be available in the resolver for subscriptions, just like queries and mutations.

**Code Snippet**
https://github.com/aws-amplify/amplify-js/blob/3b3f6948cba9d178b1a292ae629a3f9c475db807/packages/api-graphql/src/GraphQLAPI.ts#L197-L201

As you can see in the code above, the `additionalHeaders` object is not passed into `_graphqlSubscribe`.

**Comment by jordanranz** [comment]
Marked this as a feature request as this is an enhancement to the API. The PR looks good to me, getting some other eyes on it before we merge.
