### ISSUE TITLE
aws-amplify-angular - ConfirmSignUp Decorator not accepting ConfirmSignUpOptions/ClientMetaData

### ISSUE THREAD

**Issue by seanvm** [aws-amplify/amplify-js#5583]
**Describe the bug**
According to the documentation on Cognito Lambda triggers, it should be possible to pass through `clientMetaData` on `confirmSignUp` - See: https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-post-confirmation.html

The signature for `AuthClass.confirmSignUp` accepts an `options` parameter that includes `clientMetaData`. 
See: https://github.com/aws-amplify/amplify-js/blob/b4b40aa62644ea3688068e4e64f4573c568677a0/packages/auth/src/Auth.ts#L341-L345

However, the angular decorator does not accept any sort of options, only username and code. As a result, when using the `aws-amplify-angular` package it is not possible to pass through additional metaData on `confirmSignUp`.
See: https://github.com/aws-amplify/amplify-js/blob/b4b40aa62644ea3688068e4e64f4573c568677a0/packages/aws-amplify-angular/src/providers/auth.decorator.ts#L116-L119

**To Reproduce**
- Create a lambda trigger for PostConfirmation/ConfirmSignUp

In an Angular component which has AmplifyService injected:
```
let confirmSignupOptions = {
    clientMetadata: {
        meta: "data",
    },
};

await this.amplifyService.auth().confirmSignUp(
    "username",
    "code",
    confirmSignupOptions
);
```
- Check the Lambda trigger, no clientMetaData will have been passed through.

**Expected behavior**
The lambda trigger should receive a clientMetaData map containing the key-values passed in to confirmSignUp

**Environment**
```
    "aws-amplify": "^3.0.8",
    "aws-amplify-angular": "^5.0.8",
```

**Comment by LucasSubli** [comment]
Any updates on this ?

**Comment by tannerabread** [comment]
Closing as [`aws-amplify@5.0.0`](https://github.com/aws-amplify/amplify-js/releases/tag/aws-amplify%405.0.0) deprecated the package `aws-amplify-angular`. Please follow the [migration guides outlined here](https://ui.docs.amplify.aws/react/getting-started/migration) to migrate to new UI packages
