### ISSUE TITLE
[DATASTORE] Out  of memory error

### ISSUE THREAD

**Issue by PatrickLambert1101** [aws-amplify/amplify-js#5584]
Hello,

I am getting the following out of memory error on my Android 7 device while using the Datastore:
```
Possible Unhandled Promise Rejection (id: 2):
Error: database or disk is full (code 13)
convertError@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:102962:24
map@[native code]
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:102765:35
__invokeCallback@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2790:23
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2494:34
__guard@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2702:15
invokeCallbackAndReturnFlushedQueue@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2493:21
invokeCallbackAndReturnFlushedQueue@[native code]
```

I understand that Android devices have a soft cap of 7MB per app for storage but this is far below my requirements (2GB db), as the storage cap is not recommended to be exceeded, is there any other way to overcome this? Set the DB into the devices storage? My Android devices are running in Kiosk mode with 12GB internal storage.

**Comment by Ashish-Nanda** [comment]
@PatrickLambert1101 it seems like you are using React Native. There is a limit of 6mb on Android.
Could you try the steps linked here to increase the size: https://stackoverflow.com/a/57013148

Also was datastore working initially and then you got the error as the size of your database grew? 
I would try increasing the size but wanted to let you know we are aware of this issue and looking into alternative storage layers to support larger databases.

**Comment by PatrickLambert1101** [comment]
Thanks @Ashish-Nanda that works, 

The issue occurred when my database grew, could I expect the Datastore to handle a 2GB database with its current setup? Do you have a roadmap for larger DB support?

**Comment by Lovecannon** [comment]
> Thanks @Ashish-Nanda that works,
> 
> The issue occurred when my database grew, could I expect the Datastore to handle a 2GB database with its current setup? Do you have a roadmap for larger DB support?

I'd suggest you try using the AppSync SDK instead of DataStore. It supports offline usage and can handle large datasets if you design your schema and indexes correctly.

**Comment by Ashish-Nanda** [comment]
@PatrickLambert1101 glad I was able to help you resolve the issue.

I think it will work for 2GB but it would be more ideal to use a database that has indexing and better query performance when working with those many records. 
We currently have this on our roadmap and are evaluating different approaches. Will keep you posted.

Going to go ahead and close this out since your original issue is resolved.

**Comment by xsmcemmons** [comment]
Hi, I'm using datastore to sync my DB across apps... I'm facing the same problem that was shown in this issue  but the solution given is not working for me, I have a syncProducts that has more that 4000 records in it and it breaks the sync process due to database or disk is full (code 13)
I change in my android gradle properties AsyncStorage_db_size_in_MB=50
My app is made using Expo SDK 39

**Comment by prakashmathpal** [comment]
Hi, I'm using datastore to sync my DB . and my database record size is more than 50k. I'm facing the same problem ' **Error storing data Error: database or disk is full** ' i am using this in MainApplication.java class 
  **long size = 50L * 1024L * 1024L; // 50 MB
  com.facebook.react.modules.storage.ReactDatabaseSupplier.getInstance(getApplicationContext()).setMaximumSize(size);**
but getting error when create a new record and sync data from database.

**Comment by PatrickLambert1101** [comment]
@prakashmathpal , Please let me know if you figure this out

**Comment by prakashmathpal** [comment]
@PatrickLambert1101  i getting same **Error: database or disk is full**
