### ISSUE TITLE
Hub.listen not working in second time after Auth.signOut on Android

### ISSUE THREAD

**Issue by VTSingle** [aws-amplify/amplify-js#5589]
Hub.listen not triggering in second time after Auth.signOut. 

I'm using Auth.federatedSignIn({provider: 'Google'}) for SignIn to system and Auth.signOut() for sign out. 

After Auth.signOut() => Hub.listen() still never trigger. 

Example of my code: 

```
async componentDidMount() {
Hub.listen('auth', async ({payload: {event}}) => {
      console.log('event 1 ', event);
      switch (event) {
        case 'signIn':
          console.log('LogInScreen');
          store.dispatch(getUserInfo());
          break;
        case 'signOut':
          console.log('signOut');
          break;
        case 'signIn_failure':
          break;
        case 'customOAuthState':
          break;
      }
    });
  }
```

Versions of the libs: 
"amazon-cognito-identity-js": "^3.2.4",
"aws-amplify": "^3.0.9",
"aws-amplify-react-native": "^3.2.2",
"aws-sdk": "^2.663.0",
"react-native": "0.61.5",

**Comment by amhinson** [comment]
@VTSingle Looking into this now. I'm not quite sure what you mean by "not working in second time". Could you elaborate a bit more?

Also, where in your app code are you putting this Hub listener?

**Comment by VTSingle** [comment]
@amhinson _**'not working in second time'**_  
**_Steps:_**
1: A user open our app and try to login via Facebook (**Auth.federatedSignIn({provider: 'Facebook'})**);
2: He getting positive result;
3: He logined in the system and moved to welcom page (automaticaly);
4: He on press on a burger menu and after that pressed on Log out button (**Auth.signOut()**);
5: A user succesed sign out  from a system and moved to the login screen (automaticaly);
6: When he press again on log in via facebook (**Auth.federatedSignIn({provider: 'Facebook'})**) he was redirected to browser and moved back to app. But **Hub.listen never trigger event signIn** without reload the app. 
7: If he closed the app and open again it works correct on first time, but when he sign out it broke again and user must reload the app. 

**Its happens only on Android.**

![image](https://user-images.githubusercontent.com/26880406/80570569-b2f29a00-8a03-11ea-952a-ba26a6bbcecd.png)

**Comment by VTSingle** [comment]
@amhinson I have news. I created new project with same setting but without splash screen and all functionality working correct. Than I opened my main project and deleted splash screen from him and all functionality working correct.

**Comment by amhinson** [comment]
Ok thanks for the update! I'm glad you were able to get it working in some capacity. Just for reference, are you using a library for the splash screen? If so, which one?

**Comment by VTSingle** [comment]
@amhinson react-native-splash-screen
