### ISSUE TITLE
API Gateway integration?

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-js#5590]
**Is your feature request related to a problem? Please describe.**

I am currently on version 4.18.0. There is an option to add REST API but it doesn't fully allow you to manage your API Gateway, adding routes (PUT, POST, GET, DELETE), allowing CORS, adding validations (body validation using models, content-type, etc.)

**Describe the solution you'd like**

A model for API Gateway that allows robust management similar to how robust the console UI is.

**Describe alternatives you've considered**

There aren't any alternatives.

**Additional context**

None.

**Comment by sammartinez** [comment]
@aprilmintacpineda is this a request for Amplify JS or Amplify CLI? I only ask as Amplify JS version is only on version 3 so I wanted to clarify with you prior to moving this to Amplify CLI. Please let us know
