### ISSUE TITLE
[DATASTORE] Slow sync to Dynamo DB

### ISSUE THREAD

**Issue by PatrickLambert1101** [aws-amplify/amplify-js#5592]
**Describe the bug**
I am experiencing a very slow sync from my local datastore to Dynamo DB, about 1 records every 3-4 seconds. Is this expected behaviour? What steps could I use to increase this speed? I already have my Dynamo DB table on scaling capacity?
**To Reproduce**
Sync data to Dynamo DB
See slow rate of items being created on Dynamo Console

**Expected behavior**
Faster Syncing
**Code Snippet**
Please provide a code snippet or a link to sample code of the issue you are experiencing to help us reproduce the issue. (Be sure to remove any sensitive data)
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow strict-local
 */

import React, {useEffect, useState} from 'react';
import {DataStore} from '@aws-amplify/datastore';
import {PostStatus, Post} from './src/models';
import {
  SafeAreaView,
  StyleSheet,
  ScrollView,
  View,
  Text,
  StatusBar,
} from 'react-native';

import {Colors} from 'react-native/Libraries/NewAppScreen';
import Amplify from '@aws-amplify/core';

import awsConfig from './aws-exports';
Amplify.configure(awsConfig);
const App: () => React$Node = () => {
  const [usePost, setPosts] = useState([]);
  useEffect(() => {
    async function runData() {
      for (var i = 0; i < 100000; i++) {
        await DataStore.save(
          new Post({
            title: 'My First Post',
            rating: 10,
            status: PostStatus.ACTIVE,
          }),
        );
      }
      const posts = await DataStore.query(Post);
      setPosts(posts);
    }
    runData();
  }, []);
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <ScrollView
          contentInsetAdjustmentBehavior="automatic"
          style={styles.scrollView}>
          <View>
            <Text>Test {usePost.length}</Text>
          </View>
        </ScrollView>
      </SafeAreaView>
    </>
  );
};

const styles = StyleSheet.create({
  scrollView: {
    backgroundColor: Colors.lighter,
  },
  engine: {
    position: 'absolute',
    right: 0,
  },
  body: {
    backgroundColor: Colors.white,
  },
  sectionContainer: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: Colors.black,
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '400',
    color: Colors.dark,
  },
  highlight: {
    fontWeight: '700',
  },
  footer: {
    color: Colors.dark,
    fontSize: 12,
    fontWeight: '600',
    padding: 4,
    paddingRight: 12,
    textAlign: 'right',
  },
});

export default App;

</details>

**Smartphone (please complete the following information):**

- Device: Custom Android 7 With React Native

**Comment by Lovecannon** [comment]
I also experienced slowness using DataStore with AppSync/DynamoDB, among other issues. I ended up using the AppSync SDK and Apollo client instead, and it is much faster and easier to use than DataStore.

**Comment by Ashish-Nanda** [comment]
Hi @PatrickLambert1101 

Do you notice the 3-4 second lag when you have a large number of records needing to be synced (eg. 100,000 in the code example above) or even initially when you have a few records initially.

What about after your runData() is complete, if you create one more item does that also take a while to sync? 

Are you running with the debugger enabled or without?

We will run the test above as well and look into what the issue could be. I also suspect once you reach a large amount of data, querying the entire list of posts for each iteration will be causing performance issues:
```
const posts = await DataStore.query(Post);
setPosts(posts);
```
 Maybe try without that and see if there is some improvement?

**Comment by rpostulart** [comment]
I believe this is related to this one:

https://github.com/aws-amplify/amplify-js/issues/5434

**Comment by Albert-Gao** [comment]
The current Datastore is implemented using AsyncStorage, which has been removed from RN core, and slow compare to SQLite. The migration maybe not hard, I check the source code, just one page CRUD thereof I was not miss anything. But is introducing a new dependency to the lib. You have to `link` it when using with RN.

**Comment by manueliglesias** [comment]
Hi @PatrickLambert1101 

Were you able to try @Ashish-Nanda 's suggestions?
