### ISSUE TITLE
Add a method to hide the sign up link and text from the Vue.js authenticator component

### ISSUE THREAD

**Issue by mrichman** [aws-amplify/amplify-js#5594]
**Is your feature request related to a problem? Please describe.**

There is no documentation on how to hide the signup link and text. This is the "No account? Create account" prompt.

**Describe the solution you'd like**
 
A simple property such as `signUpVisible=false`

**Describe alternatives you've considered**

I've tried hiding via CSS but this is a hack.

**Additional context**

<img width="490" alt="image" src="https://user-images.githubusercontent.com/11228/80485658-cfb99f80-8927-11ea-94a4-09c6cae15b9f.png">

**Comment by jordanranz** [comment]
Closing this in favor of this discussion: https://github.com/aws-amplify/amplify-js/discussions/5593

The solution will be to override the `secondary-footer-slot` on `AmplifySignIn`:
```
<AmplifyAuthenticator>
  <AmplifySignIn slot="sign-in">
    <div slot="secondary-footer-content"></div>
  </AmplifySignIn>
</AmplifyAuthenticator>	
```

**Comment by tedtyree** [comment]
<amplify-authenticator>
    <amplify-sign-in slot="sign-in" hide-sign-up="true"></amplify-sign-in>
    <div>
      <amplify-sign-out></amplify-sign-out>
    </div>
  </amplify-authenticator>
I could not find this documentation either. But eventually found the answer randomly on the internet.
