### ISSUE TITLE
Vue AWS Amplify fail to get credentials

### ISSUE THREAD

**Issue by kannieWeesNie** [aws-amplify/amplify-js#5599]
cannot get credentials after successful signin using authentication.

i am using AWS Amplify for authentication in a Vue app.

i am able to login successfully but cannot get credentials using Auth.currentUserCredentials() and Auth.currentCredentials().

i'd appreciate any help to sort out the problem.

after signing in, i notice this in the console log:

`POST https://localhost/ net::ERR_CONNECTION_REFUSED`

this happens in development and production of vue app. then when calling either currentUserCredentials() or currentCredentials() i see this in the log: 

`failed to load credentials...TypeError: Failed to fetch... setting credentials for guest`

**failed to load credentials** is preceded by the localhost ERR_CONNECTION_REFUSED as mentioned above.

it bothers me that the post to localhost error appears in the production version of the app running as a website.

i'd appreciate any help in resolving this issue so that i can get the signed in users' credentials. thanks

you can see a more detailed debug log at stackoverflow where i posed this question, see [stackoverflow ](https://stackoverflow.com/questions/61441104/vue-aws-amplify-fail-to-get-credentials)

**Comment by Amplifiyer** [comment]
@abhi7cr please try deleting your lock files and node_modules folder and try again.

**Comment by kannieWeesNie** [comment]
thanks very much. it's working now!
