### ISSUE TITLE
403 Access Denied Error When Redirected Back From Stripe

### ISSUE THREAD

**Issue by emmafass** [aws-amplify/amplify-js#5602]
**Describe the bug**
I am creating a marketplace application where I have "participant" users upload videos and I have "judge" users give participants feedback on their videos. After a judge user signs up, I prompt them to go through the steps required by Stripe to create a [Stripe Express Connect](https://stripe.com/docs/connect/express-accounts#integrating-oauth) account so that the judges can be paid.

Stripe requires creating an OAuth link that includes a redirect URI. Once the judge user is done with Stripe's set up process, stripe uses that redirect uri to send the user back to my site. 

In my development environment, I am able to pass in http://localhost:3000/judge/payout as the redirect URI, and the process works great.

When I try to set this up in my deployed dev environment (or in my deployed prod environment), every time Stripe tries to redirect me, I get: `GET https://dev.d1t3q9es6y9lqj.amplifyapp.com/judge/payout/ 403`

<img width="762" alt="Screen Shot 2020-04-28 at 3 10 33 PM" src="https://user-images.githubusercontent.com/13208951/80527997-3d36f180-8963-11ea-844d-f8a0f7a89cf4.png">

I have gotten this error in the past from using an a tag for links when I should be using the [Link](https://reacttraining.com/react-router/web/api/Link) component. 

I am also getting this error when I try to reload the page.

I am guessing it has something to do with not being able to authenticate the user? I am using Amplify Auth with default = cognito user pools.

**Comment by Amplifiyer** [comment]
@emmafass, since your use case looks quite unique, we would need a small repro app with clear steps on how to reproduce/see the error mentioned in this issue for us to be able to debug it.

**Comment by emmafass** [comment]
@Amplifiyer Ok I will work on putting together something like that

**Comment by Amplifiyer** [comment]
Could be related to #3157

**Comment by sammartinez** [comment]
@emmafass Are you still looking for support on this use case? Please let us know on the status of the application if this is something you are still looking for

**Comment by emmafass** [comment]
@sammartinez thanks for reaching out. I believe the solution to [#3157](https://github.com/aws-amplify/amplify-js/issues/3157) fixes my problem.
