### ISSUE TITLE
Better support for cognito developer authenticated identities

### ISSUE THREAD

**Issue by dannymcpherson** [aws-amplify/amplify-js#561]
Do you want to request a feature or report a bug?
feature request

What is the current behavior?
Cognito developer authenticated identities are not fully supported

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

What is the expected behavior?
Ideally, cognito developer authenticated identities should work as well as other federated login methods.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
0.2.14

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by powerful23** [comment]
Closing this issue as this feature has been implemented. Please check the doc: https://aws-amplify.github.io/docs/js/authentication#federated-identities-social-sign-in
