### ISSUE TITLE
Clarification: Can I able to navigate inside the app after successfull signUp in aws-amplify-react-native

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#5633]
I have customized my UI screens and using Auth.SignUp for signIn. Here I need to navigate inside the screen.

How can I change the state after signUp. 

Now, for the signedIn it allows the user inside the app, but how can I change this for success signUp?

```
  Auth.confirmSignUp(users, confirmationCode, {
  }).then(data => {
    this.props.onStateChange('signIn',{})
    console.log(data)
  })
  .catch(err => {
 
}
```

**Comment by rpostulart** [comment]
We have create a base app, maybe you can look into that: 
https://github.com/alowa-apps/baseApp

You can use the hub.listen, you can see it here:
https://github.com/alowa-apps/baseApp/blob/master/App.js
