### ISSUE TITLE
Unable to resolve module aws-amplify from App.js

### ISSUE THREAD

**Issue by chai86** [aws-amplify/amplify-js#5639]
I just created a brand new fresh amplify project in my react native folder. I'm receiving the following error: **Unable to resolve module aws-amplify from App.js. aws-amplify could not be found within the project**

Versions:
```
"react": "16.11.0",
"react-native": "0.62.2"
```
in my App.js i have:

```
import Amplify, { API, graphqlOperation } from 'aws-amplify';

import awsmobile from './aws-exports';
Amplify.configure(awsmobile);
```

And my aws-exports.js file is in the root directory and seems to get located ok. Whats the issue here?

**Comment by Amplifiyer** [comment]
@chai86, did you add aws-amplify in your project? can you share your package.json's dependencies here?

**Comment by chai86** [comment]
@Amplifiyer My Package.json

```
{
  "name": "AppTest",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.11.0",
    "react-native": "0.62.2"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/runtime": "^7.9.2",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^25.4.0",
    "eslint": "^6.8.0",
    "jest": "^25.4.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.11.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by Amplifiyer** [comment]
@chai86 you are missing aws-amplify dependency. in your project. Can you do `npm i aws-amplify` or `yarn add aws-amplify`

**Comment by Amplifiyer** [comment]
Please let us know if you are facing issues after installing the dependencies. Closing this

**Comment by chai86** [comment]
I had to add "aws-amplify-react-native" too, to get it working
