### ISSUE TITLE
No way to distinguish if user registered using federated login or not registered at all

### ISSUE THREAD

**Issue by mynameisguy** [aws-amplify/amplify-js#5646]
**Describe the bug**
I'm using cognito user pool - allowing both manual signup and signin, and federated login using 2 social providers (apple,google).
when a user signin using one of the federated logins and then tries to login or reset his password using the manual auth, the error that returns is that the user does not exist. 

I can't find a way to distinguish between the case that the user haven't signup at all and the case in which he logged in using federated login.

When signing up I have a lambda trigger that throws an error if there is already a user with that email.

**To Reproduce**

1. sign in using federated login
2. reset password on manual authentication

**Expected behavior**
different errors or an API to check if user exists in pool

**Comment by mynameisguy** [comment]
it's stale because I'm waiting for a response...

**Comment by mynameisguy** [comment]
🤷‍♂️

**Comment by Necromancerx** [comment]
up

**Comment by shaharkazaz** [comment]
Can this be reopened?

**Comment by mynameisguy** [comment]
> Can this be reopened?

👆

**Comment by roberthugsy** [comment]
can this be checked please?
