### ISSUE TITLE
Unhandled promise rejection from Amplify.configure() with OAuth configuration

### ISSUE THREAD

**Issue by cshouts-tasc** [aws-amplify/amplify-js#5649]
When an OAuth is configuration is provided, the Amplify.configure() method invokes an asynchronous function that may throw an exception (see https://github.com/aws-amplify/amplify-js/blob/14f1ef9b88bc5cb99ec0a47308d3fb9cf4c89102/packages/auth/src/Auth.ts#L230 ). If the asynchronous function does throw an exception, it results in an unhandled promise rejection. This makes it extremely difficult for an application using the Amplify Auth library with OAuth enabled to catch and recover from OAuth errors when they occur.

A sample project is attached that includes an intentionally invalid configuration (missing userPoolId) to reliably demonstrate the unhandled promise rejection issue.
[amplify-unhandled-promise-rejection.zip](https://github.com/aws-amplify/amplify-js/files/4565412/amplify-unhandled-promise-rejection.zip)

**Comment by Amplifiyer** [comment]
@cshouts-tasc, thanks for pointing this out, it's not a straightforward fix or even possible I think. The async call `_handleAuthResponse()` is happening inside a callback function which is provided inline in the `configure()` method. The execution of this callback(and hence the async method `_handleAuthResponse()`) doesn't happen during the configure call but rather when a callback is called (during hostedUI authentication flow). 
This is why what you are trying to achieve (to get errors from `_handleAuthResponse()` in a try catch block of configure() call) is not possible and configure() method is actually synchronous method.

What we can do is handle and print the error message when `_handleAuthResponse()` is called so you don't see unhandled promise rejection by doing

```
urlListener(({ url }) => {
	...
	this._handleAuthResponse(url).catch(err => console.log("Error handling the Auth response", err));
});
```

Even more ideal way would be to let the users pass in a success/error callbacks to the configure method for reporting success/error of handleAuthResponse(), but that is a non-trivial amount of work.

**Comment by cshouts-tasc** [comment]
@amp I agree with everything you said, except the quoted part below. If you look at the implementation of `urlListener()` https://github.com/aws-amplify/amplify-js/blob/14f1ef9b88bc5cb99ec0a47308d3fb9cf4c89102/packages/auth/src/urlListener.ts#L15 you will see that the callback function is executed _immediately_ and _synchronously_. I believe the best way to address the potential for unhandled promise rejections involves breaking changes such as moving the asynchronous code into a different method or marking the `configure()` method `async`.

> The execution of this callback(and hence the async method `_handleAuthResponse()`) doesn't happen during the configure call but rather when a callback is called (during hostedUI authentication flow).
> This is why what you are trying to achieve (to get errors from `_handleAuthResponse()` in a try catch block of configure() call) is not possible and configure() method is actually synchronous method.

**Comment by Amplifiyer** [comment]
@cshouts-tasc, the execution of method `urlListener()` is indeed synchronous but not the callback(which is the one calling `handleAuthResponse` and is responsible for the promise rejection) which is only triggered on a page load. Making configure() async also doesn't solve the issue here since configure will return right away after creating/passing the callback, unless I'm missing something here.

**Comment by cshouts-tasc** [comment]
> @cshouts-tasc, the execution of method `urlListener()` is indeed synchronous but not the callback(which is the one calling `handleAuthResponse` and is responsible for the promise rejection) which is only triggered on a page load. Making configure() async also doesn't solve the issue here since configure will return right away after creating/passing the callback, unless I'm missing something here.

@amp Respectfully, I disagree. The callback is not run in an asynchronous context. Instead it is run as in IIFE (https://developer.mozilla.org/en-US/docs/Glossary/IIFE). I put together an example below of what it would look like if we inlined the `urlListener()` function into the `configure()` function. 

If the `configure()` method _were_ `async`, then the IIFE could be `async` as well and both the IIFE and `_handleAuthResponse()` could be awaited. An even simpler solution would be to remove the IIFE, since it does not seem to be providing any benefit.

**Amplify Code**
```
const usedResponseUrls = {};
urlListener(({ url }) => {
  if (usedResponseUrls[url]) {
    return;
  }

  usedResponseUrls[url] = true;
  this._handleAuthResponse(url);
});
```

**Equivalent Code if urlListener was inlined**
```
const usedResponseUrls = {};
if (JS.browserOrNode().isBrowser && window.location) {
  const url = window.location.href;
  (({ url2 }) => {
    if (usedResponseUrls[url2]) {
      return;
    }

    usedResponseUrls[url2] = true;
    this._handleAuthResponse(url2);
  })({ url });
} else if (JS.browserOrNode().isNode) {
  // continue building on ssr
  () => { }; // noop
} else {
  throw new Error('Not supported');
}
```

**Comment by Amplifiyer** [comment]
@cshouts-tasc, apologies, I misunderstood that the execution of the callback was happening later in the lifecycle of the page. You are right, it's possible to await on the configure and subsequently handleAuthResponse(), but as you mentioned it involves a breaking change and thus non trivial.

We can mark this as a feature request for our next major version, but until then we won't be able to prioritize this.

**Comment by cwomack** [comment]
The developer preview for v6 of Amplify has officially been released with updates to the Auth package and much more! Please check out our [announcement](https://aws.amazon.com/blogs/mobile/aws-amplify-javascripts-new-developer-preview-with-reduced-bundle-sizes-improved-typescript-and-next-js-support/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=238088647) and updated [documentation](https://docs.amplify.aws/lib-v1/project-setup/create-application/q/platform/js/) to see what has changed. 

We believe this issue should be resolved within the dev preview and upcoming General Availability for Amplify v6, but let us know with a comment if there are further issues.

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
