### ISSUE TITLE
Mock subscriptions fail due to SSL error in 4.18.1

### ISSUE THREAD

**Issue by johannesspohr** [aws-amplify/amplify-js#5652]
First of all, thanks for the effort to get subscriptions working. I've been eagerly waiting for this. However, it still fails for me, even in a newly created environment. 

**Describe the bug**
When using subscriptions with `amplify mock`, the WebSocket connection goes to a secure WebSocket address, which then fails due to SSL problems.

**Amplify CLI Version**
4.18.1

**To Reproduce**
- Init amplify project, add GraphQL API
- Add webpack, aws-amplify etc.
- Set up index.js with minimal configuration like 
```
import API, { graphqlOperation }  from "@aws-amplify/api"
import awsConfig from "./aws-exports"
import { onCreateTodo } from "./graphql/subscriptions"
API.configure(awsConfig)
API.graphql(graphqlOperation(onCreateTodo)).subscribe({next: e => console.log(e)})
```

- Start webpack and `amplify mock`
- Go to localhost:8082 (or whatever port it's running on)

- Error message is: `AWSAppSyncRealTimeProvider.js:661 WebSocket connection to 'wss://192.168.0.115:20002/graphql?header=...' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR`

I also tried to replace my network IP (192.168.0.115) with `localhost` in the exports file, it still wants to use SSL. `aws_appsync_dangerously_connect_to_http_endpoint_for_testing` is set to true there as well.

**Expected behavior**
The WebSocket to localhost should be opened, probably without SSL

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version: 12.14.0

**Comment by yuth** [comment]
I think this is an issue with Amplify JS. I will transfer this issue to the JS repo so that they can help debug/fix this issue.

**Comment by brene** [comment]
@sammartinez - I think this belongs to the JS repo.

**Comment by sammartinez** [comment]
From reading the above, @johannesspohr this seems to be resolved? Can you confirm? thanks
