### ISSUE TITLE
First Time Change Password: Cannot read property 'challengeParam' of undefined

### ISSUE THREAD

**Issue by danluszcz-pariveda** [aws-amplify/amplify-js#5657]
**Describe the bug**
We recently upgraded our AWS Amplify Libraries and now when a user in the FORCE_CHANGE_PASSWORD state enters their temporary password the error 'Cannot read property 'challengeParam' of undefined' is displayed and the password cannot be changed.  This only happens when using slots:

```
<amplify-authenticator>
    <amplify-sign-out></amplify-sign-out>
	<amplify-sign-in slot="sign-in"></amplify-sign-in>
  	<amplify-confirm-sign-in slot="confirm-sign-in"></amplify-confirm-sign-in>
  	<amplify-confirm-sign-up slot="confirm-sign-up"></amplify-confirm-sign-up>
  	<amplify-forgot-password slot="forgot-password"></amplify-forgot-password>
  	<amplify-require-new-password slot="require-new-password"></amplify-require-new-password>
  	<amplify-verify-contact slot="verify-contact"></amplify-verify-contact>
  	<amplify-sign-up header-text="Please contact Support for access" slot="sign-up"></amplify-sign-up>
</amplify-authenticator>
```

Without slots users can set their password successfully:

`<amplify-authenticator></amplify-authenticator>
`
But then the "Account recovery requires verified contact information" view is displayed and if the user clicks the box next to Email and clicks Verify, it throws an error (in the console):

zone-evergreen.js:171 Uncaught TypeError: Cannot read property 'value' of undefined
    at AmplifyVerifyContact.handleSubmit (amplify-confirm-sign-in_8.entry.js:977)
    at HTMLFormElement.handleSubmit (amplify-confirm-sign-in_8.entry.js:1035)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Zone.runTask (zone-evergreen.js:167)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:480)
    at invokeTask (zone-evergreen.js:1621)
    at HTMLFormElement.globalZoneAwareCallback (zone-evergreen.js:1647)
    at HTMLButtonElement.AmplifyButton.handleClick (amplify-button_3.entry.js:38)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Zone.runTask (zone-evergreen.js:167)

If the user clicks Skip, the Verification message disappears but the Auth State does not change to signedIn.

**To Reproduce**

1. Create a new user via the AWS.CognitoIdentityServiceProvider
2. Login via AWS Amplify Angular Authenticator with username and temporary password received from Cognito via email
3. Enter a new password and click Submit
4. Error message 'Cannot read property 'challengeParam' of undefined' is displayed in top banner and no updates are made to the user.

**Expected behavior**
Password is set correctly and user is changed from FORCE_CHANGE_PASSWORD to CONFIRMED

<details>
  <summary><strong>Environment</strong></summary>
    "@angular/core": "^8.2.14"
    "@aws-amplify/ui-angular": "^0.2.2"
    "aws-amplify": "^3.0.8"
    "aws-amplify-angular": "^5.0.8"

**Comment by jordanranz** [comment]
Hey @danluszcz-pariveda,

This is most likely due to using `<amplify-verify-contact slot="verify-contact"></amplify-verify-contact>` without passing in a `user` property. 

I see multiple uses of slots in your example but you are not passing any other props. Curious what you are trying to achieve by adding these slot overrides?

We should probably clean up the documentation and error messaging around this.

**Comment by crustyratfink** [comment]
Same issue here:
```
export const AppAuth = (props) => {
  const classes = useStyles();
  return (
    <div className={`theme-${store.provider} ${classes.pageContainer}`}>
      <img src={logo} alt="logo" className={classes.logo} />
      <div className={`themed-container ${classes.authContainer}`}>
        <AmplifyAuthenticator>
          <AmplifySignIn
            headerText="Please Sign In to the Secure Uploader"
            slot="sign-in"
          />
          <AmplifyRequireNewPassword
            headerText="Please choose a secure password"
            slot="require-new-password"
          />
          <App />
        </AmplifyAuthenticator>
      </div>
    </div>
  );
};
```

`Cannot read property 'challengeParam' of undefined`

**Comment by danluszcz-pariveda** [comment]
> Hey @danluszcz-pariveda,
> 
> This is most likely due to using `<amplify-verify-contact slot="verify-contact"></amplify-verify-contact>` without passing in a `user` property. If you are not using the `verify-contact` slot this will be done under the hood.
> 
> I see multiple uses of slots in your example but you are not passing any other props. Curious what you are trying to achieve by adding these slot overrides?
> 
> We should probably clean up the documentation and error messaging around this.

Using the authenticator without slots has its own issues as I detailed in the original post.

We are building custom UI components to get around this bug and others.

**Comment by ashika01** [comment]
@danluszcz-pariveda - it is unclear as to what bugs you face when you are not using slots. This way we can try and guide you with the proper usage of slots.

**Comment by danluszcz-pariveda** [comment]
> @danluszcz-pariveda - it is unclear as to what bugs you face when you are not using slots. This way we can try and guide you with the proper usage of slots.

We have moved on to custom UI components given the issues with this library.

**Comment by ashika01** [comment]
@danluszcz-pariveda Sorry to hear that. We have a lot of customers who is using the ui-components in production. Also, these components are released recently and we are working on the components to get standards higher on this. Customer feedback is crucial to keep the components growing. Saying there are issues wont help us improve the components. If possible, please provide feedback on the issues since we are actively working on improving.

**Comment by wcordelo** [comment]
Have the same issue with the react package
