### ISSUE TITLE
AWS Pubsub Publish no internet case

### ISSUE THREAD

**Issue by rahulje9** [aws-amplify/amplify-js#5664]
Hi,

I have created a React Native IOT application which uses pubsub to publish the changes made in the app. I have an issue when I try to update the value while I don't have internet reachability the pubsub is getting publish success rather than publish fail. to recreate my issue while using the app, just remove the network cable from modem so that you won't get internet connectivity while the wifi is still on. I tried to get the success message from the method and I'm getting [undefined].

Package version
```
        "aws-amplify": "next",
        "aws-amplify-react-native": "next",
```

**Comment by jordanranz** [comment]
Hey @rahulje9,

For clarity, you are saying that PubSub.publish as documented [here](https://docs.amplify.aws/lib/pubsub/publish/q/platform/js) returns a successful response when you are offline?

**Comment by rahulje9** [comment]
> Hey @rahulje9,
> 
> For clarity, you are saying that PubSub.publish as documented [here](https://docs.amplify.aws/lib/pubsub/publish/q/platform/js) returns a successful response when you are offline?
> 
> Could you also try using the `latest` versions of the packages listed.

yes, in order to reproduce this you would have to disconnect the Lan cable from wifi router, so there will be wifi but no internet.
I had used the latest packages but some functionalities are not working with them, so I have to stick with `next` for the moment.

**Comment by harrysolovay** [comment]
You can wrap your calls with a [`navigator.onLine`](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine) condition and handle retry / postponement logic as best fits your use case.

Also, we'd be grateful for any PRs, if you're interested in building this into the category (we'd of course review it).
