### ISSUE TITLE
problem with Datastore property clear

### ISSUE THREAD

**Issue by founderSalt** [aws-amplify/amplify-js#5686]
Hi,
on react-native, when i call clear or when i clear AsyncStore and then, when i call DataStore.query, i dont  get data which were cleaned in local storage (in App Sync data is present).

**Comment by atedevby** [comment]
Hi,
We checked and this method (DataStore.clear ()) deletes data from DynamoDB

**Comment by nubpro** [comment]
You need to subscribe to the tables and wait until the client fully synchorize with the backend.

**Comment by manueliglesias** [comment]
> Hi,
> We checked and this method (DataStore.clear ()) deletes data from DynamoDB

Hi @atedevby 

`DataStore.clear()` doesn't delete records remotely, it just clears the local storage and stop the graphql subscriptions.

**Comment by sammartinez** [comment]
Resolving this issue as the above comment.
