### ISSUE TITLE
Datastore not working with one->many relationships

### ISSUE THREAD

**Issue by GeorgeBellTMH** [aws-amplify/amplify-js#5702]
```gql
type ResourceRoot @model {
  id: ID!
  type: String
  groupId: String
  resources: [Resource]  @connection(name: "ResourceRootResource", keyField: "id")
}

type Resource @model {
  id: ID!
  type: String
  menuTitle: String
  title: String
  image: Image
  description: String
  extendedDescription: String
  root: ResourceRoot @connection(name: "ResourceRootResource", keyField: "id")
}
```

This seems to work fine in the local datastore, but is having trouble syncing to DynamoDB because it is looking for resourcerootid...which doesn't exist in the resource schema (and associated mutations)...

I am using the latest alpha...as well I have tried current versions going back a few months...

**Comment by brene** [comment]
@sammartinez - I think this is a JS issue. Can you help triage?

**Comment by undefobj** [comment]
@GeorgeBellTMH can you take a look at the [latest docs for Relational modeling](https://docs.amplify.aws/lib/datastore/relational/q/platform/js) with DataStore and use the latest library version? We made some improvements to the CLI, the library on how it handles this internally, and tried to be explicit about schemas in the documentation including how to use `@key`.

**Comment by GeorgeBellTMH** [comment]
Updated to:
    "aws-amplify": "^3.0.12-unstable.3",
    "aws-amplify-react-native": "^4.1.3-unstable.3",
amplify-cli: 4.20.1-alpha.0

My schema is as follows:

type ResourceRoot @model 
 @auth(rules: [{ allow: groups, groups: ["verifiedUsers"] }])
 {
  id: ID!
  type: String
  groupId: String
  resources: [Resource] @connection(keyName: "byResource", fields: ["id"])
}
type Resource @model 
@auth(rules: [{ allow: groups, groups: ["verifiedUsers"] }])
 @key(name: "byResource", fields: ["resourceID","title"])
{
  id: ID!
  type: String
  menuTitle: String
  title: String
  image: Image
  description: String
  extendedDescription: String
  series: [ResourceSeries] @connection(keyName: "byResourceSeries", fields: ["id"])
  resourceID:ID!
  resourceRoot: ResourceRoot! @connection(fields:["resourceID"])
}
type ResourceSeries @model 
@auth(rules: [{ allow: groups, groups: ["verifiedUsers"] }])
 @key(name: "byResourceSeries", fields: ["seriesID","title"])
{
  id: ID!
  type: String
  title: String
  description: String
  image: String
  category: [String]
  status: String
  allFiles: String
  playlist: String
  playlistImage: String
  episodes: [ResourceEpisode] @connection(keyName: "byResourceEpisode", fields: ["id"])
  seriesID: ID!
  parentResource: Resource! @connection(fields: ["seriesID"])
}

type ResourceEpisode @model 
@auth(rules: [{ allow: groups, groups: ["verifiedUsers"] }])
 @key(name: "byResourceEpisode", fields: ["episodeID","title"])
 {
  id: ID!
  episodeNumber: Int
  type: String
  title: String
  description: String
  videoPreview: String
  videoLowRes: String
  videoHiRes: String
  lessonPlan: String
  activityPage: String
  episodeID:ID!
  parentSeries: ResourceSeries! @connection(fields: ["episodeID"])
}

My typescript code is:

        const resourceRoot = await DataStore.save(
            new ResourceRoot({
                type: `curriculum`,
                groupId: this.props.groupId
            })
        );
        console.log({ resourceRoot: resourceRoot })

        const resource = await DataStore.save(
            new Resource({
                type: "curriculum",
                menuTitle: "Overview",
                title: "Overview",
                image: {
                    userId: "123",
                    filenameSmall: "123",
                    filenameMedium: "123",
                    filenameLarge: "123",
                    filenameUpload: "123"
                },
                description: "...",
                extendedDescription: "123",
                resourceRoot: resourceRoot
            })
        );
        console.log({ resource: resource })
        const series = await DataStore.save(
            new ResourceSeries({
                type: "curriculum",
                title: "Overview",
                image: "123",
                description: "...",
                category: ["123"],
                status: "123",
                allFiles: "123",
                playlist: "123",
                playlistImage: "123",
                parentResource: resource
            })
        );
        console.log({ series: series })



        const getResourceRoot = await DataStore.query(ResourceRoot);
        console.log(getResourceRoot[0].resources) //FAILS HERE - resources is undefined....

**Comment by GeorgeBellTMH** [comment]
When I look at resource, I can see the resourceRoot...but when looking from resourceRoot I do not see resources (which I would expect to have one resource in an array)

**Comment by undefobj** [comment]
> console.log(getResourceRoot[0].resources[0]) //FAILS HERE - resources is undefined....

This is Lazy Evaluation which isn't supported yet. You can track that feature here: https://github.com/aws-amplify/amplify-js/issues/5054

For now you'll need to do child queries like this: https://docs.amplify.aws/lib/datastore/relational/q/platform/js#querying-relations

**Comment by sammartinez** [comment]
Closing in favor of the feature request
