### ISSUE TITLE
textToSpeech fails with special characters

### ISSUE THREAD

**Issue by bdpaul99** [aws-amplify/amplify-js#5708]
**Describe the bug**

When using the Predictions library to 1. translate text to a new language, and then 2. use polly to synthesize that text to speech, the api call to polly fails when there are characters with accent marks in the string.

For example, if i want to translate the string "The number" to spanish, it successfully translates to "el número". Then the function call

Predictions.convert({
textToSpeech: {
source: {
text: "el número",
language: "es-MX"
},
voiceId: "Mia"
}
})

would fail, resulting in this error:
{ "name": "InvalidSignatureException", "$fault": "client", "$metadata": { "httpStatusCode": 403, "httpHeaders": { "content-type": "application/json", "date": "Wed, 06 May 2020 22:08:54 GMT", "x-amzn-errortype": "InvalidSignatureException:http://internal.amazon.com/coral/com.amazon.coral.service/", "x-amzn-requestid": "872289c6-e704-41c1-a2fe-5ce93aa954a6" }, "requestId": "872289c6-e704-41c1-a2fe-5ce93aa954a6", "retries": 3, "totalRetryDelay": 430 } }

When the accent mark is removed, it succeeds.

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.
$ npm install -g @aws-amplify/cli
$ amplify configure
$ amplify init
$ amplify add predictions
* Which resources do you have configured?
Predictions- Convert, translateText and textToSpeech

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```
 System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 311.01 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.8.0 - /usr/local/bin/node
    npm: 6.10.3 - /usr/local/bin/npm
  Browsers:
    Firefox: 68.6.1
    Safari: 13.1
  npmPackages:
    @testing-library/jest-dom: ^4.2.4 => 4.2.4 
    @testing-library/react: ^9.5.0 => 9.5.0 
    @testing-library/user-event: ^7.2.1 => 7.2.1 
    aws-amplify: ^3.0.10 => 3.0.10 
    aws-amplify-react: ^4.1.9 => 4.1.9 
    react: ^16.13.1 => 16.13.1 
    react-dom: ^16.13.1 => 16.13.1 
    react-scripts: 3.4.1 => 3.4.1 
  npmGlobalPackages:
    @aws-amplify/cli: 4.18.1
    amplify-category-video: 2.6.0
    awsmobile-cli: 1.1.7
    create-react-app: 3.3.1
    npm: 6.10.3
    serve: 11.3.0
    serverless: 1.49.0
</details>

**Comment by Amplifiyer** [comment]
Same as #5472 and #5387.  the root cause is the issue in aws-sdk aws/aws-sdk-js-v3#1100. aws-sdk has fixed the issue, it will be available once aws-sdk does a release with the fix and amplify releases with the new version of aws-sdk

**Comment by bdpaul99** [comment]
@Amplifiyer Do you happen to have any idea on timeline for this?

**Comment by Amplifiyer** [comment]
@bdpaul99, we are working with aws-sdk for a coordinated release. Should be out in next few days.

**Comment by Amplifiyer** [comment]
@bdpaul99 can you test again with latest amplify and let us know if it's fixed?

**Comment by sammartinez** [comment]
Resolving as there has been no response. Please let us know if you are still experiencing this issue.
