### ISSUE TITLE
Google federated signin error: NotAuthorizedException: Token is not from a supported provider of this identity pool.

### ISSUE THREAD

**Issue by dymyll** [aws-amplify/amplify-js#5712]
Hello, 
When trying to use Auh.federatedSignin for google, I get an error that states _**"NotAuthorizedException: Token is not from a supported provider of this identity pool."**_
I am trying to use this for react-native platforms (IOS and Android) 

**To Reproduce**

1. Go to Google developer console
2. I created OAuth Clients for both IOS, Android, and Web is also there.
3. I navigate to AWS User Pool and scroll to Federation/Identity Providers and select Google
4. According to AWS Amplify docs(https://aws-amplify.github.io/docs/android/auth-google-setup), there should be an option to input IOS Client ID, Android Client ID, and Web Client ID, however, I only see a textbox for one ID
- 'Google app Id'
- 'App secret' 
- 'Authorize Scope'

I wasn't sure which ID to put here as I need both platforms (IOS and Android) to be here. 
But in google developer console, they do not provide an app secret for those platforms either, only the web client has the App ID and App secret. 

I took the IOS client ID and pasted in 'Google app Id' and used Web OAuth 'App secret' into the AWS Federated text boxes
**Expected behavior**
I expect the token I get back from google to be accepted into Auth FederatedSignin to then provide authorized user access. 

**Code Snippet**
      const data = await GoogleSignin.signIn();
      await Auth.federatedSignIn("google", {
        token: data.idToken,
         expires_at: null,
         name: data.user.name,
       }).then(awsUser => {console.log(awsUser)});

**Screenshots**
Console Error: 
![AWS_AuthError](https://user-images.githubusercontent.com/31488060/81263810-f782c480-9005-11ea-88bd-46971e965ea9.png)

Google developer console: 
![OAuthGoogle](https://user-images.githubusercontent.com/31488060/81262254-1a5fa980-9003-11ea-8127-93c75f4fa1e5.png)

AWS User Pool FederatedSignin: 
![AWSFedSignIn](https://user-images.githubusercontent.com/31488060/81262684-e33dc800-9003-11ea-9ce9-89de14a71d91.png)

**What is Configured?**
I added the federated sign in MANUALLY through User pool UI not in the command line. 

If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.
* Which resources do you have configured?
  * If applicable, please provide your `aws-exports` file:
   ```
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f4fe4c97-xxxx-xxxx-xxxx-xxxxxxxx",    
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9xxxxxxx",
    "aws_user_pools_web_client_id": "2cpxxxxxxxxxxxxxxxxx",
    "oauth": {},
};
   ```

I am sure I am messing up somewhere between the Cognito UI and configuration set up. 
PLEASE HELP.

**Comment by dymyll** [comment]
Wow, I knew this was a configuration issue. 
I needed to go to identity providers, not the user pool. I now have access when passing the key.

**Comment by mitchconquer** [comment]
Thank you this helped me! In my AWS console, I went to:

1. Cognito
2. Clicked Manage Identity Pools (not user pools)
3. Clicked on the identity pool with the same name as the identity pool
4. Clicked Edit Identity Pool
5. Scroll down to Authentication Providers
6. Go to the Google+ tab and enter the client ID there (that's this screen, btw)
7. Scroll to bottom of page and click save changes

![image](https://user-images.githubusercontent.com/7675922/114143949-a04a3b80-98c9-11eb-8362-63f434f63a27.png)
