### ISSUE TITLE
Unable to resolve "./providers" from "node_modules/@aws-amplify/storage/lib-esm/index.js"

### ISSUE THREAD

**Issue by Alamut98** [aws-amplify/amplify-js#5715]
**Describe the bug**
i upgrade the expo sdk 35 to 37. in that time i upgrade all the packages what i have. while upgrading aws-amplify i got the following error
Unable to resolve "./providers" from "node_modules/@aws-amplify/storage/lib-esm/index.js"
**To Reproduce**
My package.json is
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/art": "^1.2.0",
    "aws-amplify": "3.0.10",
    "aws-amplify-react-native": "^4.1.1",
    "cli": "^1.0.1",
    "d3": "^5.15.0",
    "d3-scale": "^3.2.1",
    "date-fns": "^2.13.0",
    "expo": "^37.0.3",
    "expo-app-auth": "^9.0.0",
    "expo-av": "8.1.0",
    "expo-camera": "^8.2.0",
    "expo-file-system": "^8.1.0",
    "expo-google-app-auth": "^7.0.0",
    "expo-media-library": "^8.0.0",
    "expo-network": "^2.0.0",
    "expo-permissions": "^8.1.0",
    "firebase": "^7.9.0",
    "moment": "^2.24.0",
    "moment-range": "^4.0.2",
    "native-base": "^2.13.8",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-24h-timepicker": "^1.1.0",
    "react-native-aws3": "^0.0.9",
    "react-native-calendar-picker": "^6.0.1",
    "react-native-gesture-handler": "1.6.0",
    "react-native-keyboard-accessory": "^0.1.10",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-pagination": "^1.5.5",
    "react-native-reanimated": "1.7.0",
    "react-native-responsive-screen": "^1.3.0",
    "react-native-screens": "^2.2.0",
    "react-native-svg": "11.0.1",
    "react-native-svg-charts": "^5.3.0",
    "react-native-swipe-list-view": "^2.0.3",
    "react-native-switch-toggle": "^1.1.2",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "^0.11.7",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.9.3",
    "react-navigation-tabs": "^2.5.5",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "^8.1.0"
  },
  "private": true
}

how to resolve this issue?

**Comment by amhinson** [comment]
@Alamut98, could you try deleting your `node_modules` directory and installing again to see if that fixes the error?

**Comment by ericclemmons** [comment]
I had the same issue, and it was due to a `providers` folder being renamed to `Providers`.  Because of how case sensitivity differs between the OS and module resolution, clearing out `node_modules` resolved it or me.
