### ISSUE TITLE
Apple Touch Id shows different authentication pop up with Amplify

### ISSUE THREAD

**Issue by t-moedano** [aws-amplify/amplify-js#5718]
**Describe the bug**
I created an Apple Sign In journey but the problem is that the authentication pop up that is opened is a little bit different that I see in other apple logins because it shows this text 'Use Different Apple Id' below the touch id login.

![image](https://user-images.githubusercontent.com/19256308/81335613-466c4080-907e-11ea-940b-c00a9b5f9c1d.png)

If you click acts like a 'cancel' button. I don't know if this behavior was expected. Other apps that I saw using apple id does not show this texts, so I don't know if we are supposed to take an action. 

**To Reproduce**
1. With Sign In With Apple configured
2. Start login with apple
4. See the pop-up showing text

**Expected behavior**
Pop-up following the current pattern, without this text

**Comment by jordanranz** [comment]
Hey @t-moedano,

Can you provide a bit more context about how you are using Amplify? Which versions of amplify modules are you using, which categories are you using (Auth?), which platform are you using (React Native?). Also, if possible can add code snippets to your reproductions steps.

All of the above will help us properly respond to your feedback.

**Comment by t-moedano** [comment]
Hi, @jordanranz  sorry for the delay

Yes, we were doing with React Native using the federatedSignIn methods just like in the documentation

`<Button onPress={() => Auth.federatedSignIn({provider: 'SignInWithApple'})}>Continue with Apple</button>`

I made some research and it seems like the problem is something related with AWS conection between Cognito and Apple Sign In

You know, if I use the link directly just link Hosted UI (that I believe, behind the scenes is the same thing Amplify does, right ? ) 

`${env.SOCIAL_LOGIN_URL}/oauth2/authorize?identity_provider=SignInWithApple&redirect_uri=${env.SOCIAL_LOGIN_REDIRECT_URI}&response_type=CODE&client_id=${env.SOCIAL_LOGIN_CLIENT_ID}&scope=aws.cognito.signin.user.admin email openid phone profile`

the same thing happens...

So, after studying a little bit more this problem... Maybe is not Amplify SDK issue at all but the whole configuration between AWS and Apple. But do you know who is responsible for this configuration ? Where can we open issue about this problem ?

**Comment by sammartinez** [comment]
@t-moedano Apologizes on the late response on this. Can you provide the documentation you were following to setup the OAuth workflow? Please let us know.

**Comment by ahtokca** [comment]
@t-moedano, how did u configured react to show touch id? In my case it always opens Safari. What did i miss?
Any help appreciated. Thank you in advance
