### ISSUE TITLE
Amplify 3.2.6 Gives "No credentials, applicationId or region" Error 

### ISSUE THREAD

**Issue by rnadeera** [aws-amplify/amplify-js#5720]
**Describe the bug**
I have created a sample react app from create-react-app and added following code in App.tsx. When I start app, it gives "No credentials, applicationId or region" error. I have contacted AWS support to verify whether it caused by AWS Cognito Identity Pool & Pinpoint configuration issue. They have verified all configuration is done correctly & advice this error maybe caused by some bug in Amplify Module. 

Please note that I have used manual configuration. (i.e; haven't executed amplify init)

**Code Snippet**
```
import React from "react";
import Amplify, { Logger, Analytics } from "aws-amplify";

function App() {
  const logger = new Logger("AuthWrapper", "DEBUG");

  const analytics = () => {
    try {
      logger.debug("in amplify config");
      Amplify.configure({
        Auth: {
          IdentityPoolId: "<<poolId>>",
          region: "<<poolRegion>>",
        },
        Analytics: {
          disabled: false,
          AWSPinpoint: {
            appId: "<<appId>>",
            region: "<<pinpointRegion>>",
          },
        },
      });
      logger.debug("in amplify config completed");
    } catch (e) {
      logger.error(e);
    }

    Analytics.record({ name: "Test" });
    logger.debug("logged");
  };

  return (
    <div className="App">
      {analytics()}
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;
```

**What is Configured?**
aws-amplify: "latest"(3.2.6)

**Comment by jordanranz** [comment]
Can you try moving:
```
Amplify.configure({
        Auth: {
          IdentityPoolId: "<<poolId>>",
          region: "<<poolRegion>>",
        },
        Analytics: {
          disabled: false,
          AWSPinpoint: {
            appId: "<<appId>>",
            region: "<<pinpointRegion>>",
          },
        },
      });
```
above of the App function.

or add `async` `await` on your analytics function:
 ```
const async analytics = () => {
    try {
      logger.debug("in amplify config");
      Amplify.configure({
        Auth: {
          IdentityPoolId: "<<poolId>>",
          region: "<<poolRegion>>",
        },
        Analytics: {
          disabled: false,
          AWSPinpoint: {
            appId: "<<appId>>",
            region: "<<pinpointRegion>>",
          },
        },
      });
      logger.debug("in amplify config completed");
    } catch (e) {
      logger.error(e);
    }

    await Analytics.record({ name: "Test" });
    logger.debug("logged");
  };
```

**Comment by rnadeera** [comment]
Tried it but still same error. Below is my re-factored code.

```
import React from "react";
import Amplify, { Logger, Analytics } from "aws-amplify";
import "./App.css";

Amplify.configure({
  Auth: {
    IdentityPoolId: "ap-southeast-2:31bc02fe-4190-4151-8552-2f5597719558",
    region: "ap-southeast-2",
    identityPoolRegion: "ap-southeast-2",
  },
  Analytics: {
    disabled: false,
    AWSPinpoint: {
      appId: "172b5c9eb0e14466943f70262c96d427",
      region: "us-east-1",
    },
  },
});

function App() {
  const logger = new Logger("AuthWrapper", "DEBUG");

  const analytics = async () => {
    try {
      logger.debug("start log");
      await Analytics.record({ name: "Test" });
      logger.debug("logged");
    } catch (e) {
      logger.error(e);
    }
  };

  return (
    <div className="App">
      <button onClick={analytics}>
        Send Analytics
      </button>
    </div>
  );
}
```
This is the error.
<img width="1438" alt="Screen Shot 2020-05-08 at 12 26 51 pm" src="https://user-images.githubusercontent.com/16377658/81363673-3e1c1000-9127-11ea-959b-70e41e1a550d.png">

**Comment by sanyashvets** [comment]
https://github.com/aws-amplify/amplify-js/issues/3484#issuecomment-625790964 worked for me

**Comment by rnadeera** [comment]
> [#3484 (comment)](https://github.com/aws-amplify/amplify-js/issues/3484#issuecomment-625790964) worked for me

Did you execute `amplify init` command when setting up react app? 

With my AWS environment setup I cannot do this step and I have created AWS resources manually and given required permissions as per the documentation. Is there a additional thing done by `amplify init` command to get this work?

**Comment by jordanranz** [comment]
@rnadeera, I think the crux of what @sanyashvets is mentioning is the fact that `IdentityPoolId` does not use a lowercase 'i' in your config. Can you try using:
```
Amplify.configure({
  Auth: {
    identityPoolId: ..
    ..
  }
  ..
});
```

**Comment by rnadeera** [comment]
> @rnadeera, I think the crux of what @sanyashvets is mentioning is the fact that `IdentityPoolId` does not use a lowercase 'i' in your config. Can you try using:
> 
> ```
> Amplify.configure({
>   Auth: {
>     identityPoolId: ..
>     ..
>   }
>   ..
> });
> ```

Yes. That was the issue. It's working now. Silly mistake by me. Thanks all for your help
