### ISSUE TITLE
Signup config not working

### ISSUE THREAD

**Issue by pushekmadaan** [aws-amplify/amplify-js#5731]
Using signup config with amplify-authenticator has no effect.

**To Reproduce**
Login.ts
`import { Component, OnInit } from '@angular/core';
import { AmplifyService } from '@flowaccount/aws-amplify-angular';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  public signUpConfig = {
    header: 'Welcome to Smart Home',
    hideAllDefaults: true,
    signUpFields: [
      {
        label: 'E-mail',
        key: 'email',
        required: true,
        displayOrder: 1,
        type: 'string',
      },
      {
        label: 'Password',
        key: 'password',
        required: true,
        displayOrder: 2,
        type: 'password'
      },
      {
        label: 'Name',
        key: 'name',
        required: true,
        displayOrder: 3,
        type: 'string'
      }]
    };
  

  constructor(
    private amplifyService: AmplifyService,
    private router: Router
  ) { 
    this.amplifyService = amplifyService;

    this.amplifyService.authStateChange$
     .subscribe (authState => {
      if (authState.state === 'signedIn') {
        console.log(authState.user);
      }
     });
      
  }

  ngOnInit(): void {
  }

}
`
Login.html:
`<amplify-authenticator [signUpConfig]="signUpConfig"></amplify-authenticator>`

**Expected behavior**
Signup form should have E-mail, password and Name as the fields but it still shows the default - Username, password, E-mail and phone number.

**Code Snippet**
Provided above

**Comment by pushekmadaan** [comment]
Angular: 9.1.6
Chrome: Version 81.0.4044.138
MacOS: 10.14.6

Package.json
`{
  "name": "my-test",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.4",
    "@angular/common": "~9.1.4",
    "@angular/compiler": "~9.1.4",
    "@angular/core": "~9.1.4",
    "@angular/forms": "~9.1.4",
    "@angular/platform-browser": "~9.1.4",
    "@angular/platform-browser-dynamic": "~9.1.4",
    "@angular/router": "~9.1.4",
    "@aws-amplify/ui": "^2.0.2",
    "@flowaccount/aws-amplify-angular": "^4.2.11",
    "aws-amplify": "^3.0.10",
    "aws-amplify-angular": "^5.0.10",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.4",
    "@angular/cli": "~9.1.4",
    "@angular/compiler-cli": "~9.1.4",
    "@angular/language-service": "~9.1.4",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }
}
`
tsconfig.app.json
`{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": ["node"]
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ]
}
`
tsconfig.json
`{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}`

**Comment by ashika01** [comment]
@pushekmadaan - why are you using `@flowaccount/aws-amplify-angular` ? This is our official package - https://www.npmjs.com/package/aws-amplify-angular
