### ISSUE TITLE
Problem with dependencies in analytics package.

### ISSUE THREAD

**Issue by dmoskovtsov** [aws-amplify/amplify-js#5735]
**Describe the bug**
Problem with dependencies in analytics package. 

**To Reproduce**
File [AmazonPersonalizeProvider.ts](https://github.com/aws-amplify/amplify-js/blob/master/packages/analytics/src/Providers/AmazonPersonalizeProvider.ts) has got this code: 

```import { isEmpty, isEqual, get } from 'lodash';```

There are 2 problems with it: 

1. lodash is not specified as a dependency in [package.json](https://github.com/aws-amplify/amplify-js/blob/master/packages/analytics/package.json) of analytics project which makes our lambda functions break unless we add lodash as dependency.  
2. This code imports the whole lodash module instead of importing individual functions which significantly increases bundle size in the frontend. 

**Expected behavior**
```
import isEmpty from 'lodash/isEmpty';
...
```

I would check similar imports in other files as well. Please let me know if you want me to create a PR for this. 
Cheers

**Comment by RossWilliams** [comment]
[This](https://github.com/aws-amplify/amplify-js/blob/30a7d20dc13a68f8374102be298d618d13767377/packages/analytics/tsconfig.json#L25) temporary fix in tsconfig from two years ago needs to be removed so the CI server can catch this issue going forwards.
