### ISSUE TITLE
AWSPinPointProvider: Security Token Expires after some inactivity

### ISSUE THREAD

**Issue by chai86** [aws-amplify/amplify-js#5738]
@haverchuck On my react native (iOS) app, i'm using Analytics. If the app goes into the background (as users do), and after about 1hr or more, the user then brings the app back to the foreground to interact with it, this message is displayed: 

<img width="336" alt="Screenshot 2020-04-18 at 23 40 42" src="https://user-images.githubusercontent.com/43324724/81507798-9dc91580-92f7-11ea-86a7-7abc95bb3b98.png">

I'm basically calling Analytics.record()
```
recordTimeEvent = (timeSpent) => {
    Analytics.record({
      name: 'Time On App', //'Button Pressed',
      attributes: { Username: this.state.username },
      metrics: { SecondsOnApp: timeSpent } 
    });
  };

onAppStateChange = (appState) => {

    if(appState === 'active') {   
      //.....
    }
    if(appState === 'background') {
      this.recordTimeEvent(this.state.timeOnApp)
    }  
  }
```

This is quite bad because users do move apps into the background (sometimes for days). They shouldn't have to be confronted with such an error.

**Comment by ericclemmons** [comment]
@chai86 Does this error happen only after foregrounding the app, once, or for every event until some other action takes place (e.g. refreshing or reloading the app)?

**Comment by Alto-Music** [comment]
@ericclemmons When the app is brought to the foreground after some time, this error message displays. I have to reload/refresh the app to get rid of it.

**Comment by ericclemmons** [comment]
@chai86 @Alto-Music This looks similar to https://github.com/aws-amplify/amplify-js/issues/3699.

We need to investigate if this can be resolved via our "clock drift" milestone:
https://github.com/aws-amplify/amplify-js/milestone/17

**Comment by chai86** [comment]
@ericclemmons The app seems to throw this error after an hour or so. When the user brings the app to the foreground (having sent it to the background for an hour or so), i have to refresh the app to remove it. In a users hands, this shouldn't appear on the app because it would be very poor from a usability perspective.

**Comment by ericclemmons** [comment]
Definitely agree.  I didn't realize that the React Native devtools would show up like that with a production build! (/cc @Ashish-Nanda @amhinson)

**Comment by amhinson** [comment]
This does seem related to the Clock Drift issue.

As far as the error showing to a user:
A production build of a React Native doesn't contain any of the dev tools, so this `console.error` would just be disregarded and nothing would show to the user. You can test out a production build locally by running the `Release` Scheme rather than `Debug`: https://reactnative.dev/docs/running-on-device.html#building-your-app-for-production

**Comment by chai86** [comment]
@amhinson @Ashish-Nanda According to the error, either way, the Analytics.record() function that i'm calling fails. Apparently because a token expires. This is functionality is needed, so a resolution would be appreciated. Thanks

**Comment by ericclemmons** [comment]
@chai86 We understand. I just wanted to confirm that, in production builds, users wouldn't experience a breaking user-experience. 

`Analytics.record` should work when foregrounding an app, so we have some work to do here to reproduce & resolve.

**Comment by chai86** [comment]
@amhinson @ericclemmons @Ashish-Nanda Hi guys, any resolution to why this error appears? Thanks 🙂

**Comment by ericclemmons** [comment]
@chai86 I've added it to the our [Auth Clockdrift](https://github.com/aws-amplify/amplify-js/milestone/17) milestone because I suspect that, when foregrounded, we're using in incorrect timestamp reference and the request fails.

**Comment by ericclemmons** [comment]
We've made some fixes with https://github.com/aws-amplify/amplify-js/pull/5869. Can you confirm if this issue still persists?

**Comment by chai86** [comment]
@ericclemmons I can't risk doing a pull or upgrading my aws-amplify version in its entirety, because I always find the robustness of my amplify project in a state of limbo, and right now it's running A ok!

Which files/areas of code do i need to update to resolve this timestamp reference?

**Comment by ericclemmons** [comment]
@chai86 The easiest way I can think of to test it out would be to copy/paste your entire project into a new folder, upgrade `aws-amplify` _there_, and testing that build locally. 🙏

**Comment by chai86** [comment]
@ericclemmons Thanks for the suggestion. I am currently using: 

```
  "aws-amplify": "^1.1.29",
  "aws-amplify-react-native": "^2.1.13",
```
Moving to anything v3.x+ would break a fair bit i would imagine in my current react native project. If i follow your steps to test this out, would i essentially have v1.1.29 as it stands running in one folder and v3.x+ running in another folder on my hard disk? Would the two aws-amplify versions exist independently of each other (no interference)?

**Comment by ericclemmons** [comment]
@chai86 Yes, so long as they're in entirely different git repositories & folders (otherwise they may accidentally share a `node_modules` directory!), you'll be good.

Personally, I like to use `/tmp` for exactly this reason.

**Comment by chai86** [comment]
@ericclemmons I'll need some help along the way, so if you're willing to, i'll give it a go.

So i'll need to: 
1) Copy my react native project folder to a different location on my machine (mac)
2) Run the react native project
3) Go to the terminal (i'm using the amplify-cli) and type `npm install aws-amplify` to get the latest version?
4) Re-run the project

Am i missing something here completely?

**Comment by ericclemmons** [comment]
@chai86 Pretty much!  Assuming your project is in `~/Project/my-project`:

1. Copy `~/Project/my-project` to `/tmp/my-project`
1. Within `/tmp/my-project`, run `npm install aws-amplify@latest`
1. Re-run the project.

**Comment by chai86** [comment]
@ericclemmons so my React Native project folder looks like the below (i don't have a `Project/my-project` structure:

<img width="546" alt="Screenshot 2020-07-15 at 21 49 05" src="https://user-images.githubusercontent.com/43324724/87594747-57bc7380-c6e5-11ea-9210-b2b1f401ef68.png">

It's path is:` /Users/username/Documents/GitHub/ProjectName` and the contents are as you see in the image

So i'd have to copy ProjectName so the path then looks like this: `/Users/username/Documents/GitHub/tmp/ProjectName` ?

**Comment by ericclemmons** [comment]
@chai86 Yep! You can also right-click `ProjectName` and select `Duplicate` to make it easy.

**Comment by chai86** [comment]
@ericclemmons Hi eric, thanks for the guidance. I did get aws-amplify to update to the latest v3.0.20, but i still get the error: 
<img width="345" alt="Screenshot 2020-07-17 at 13 35 29" src="https://user-images.githubusercontent.com/43324724/87786801-84ca6c80-c832-11ea-8733-ea60c6e30413.png">

It seems to happen after an hour or so when the app comes back from the background to foreground

**Comment by chai86** [comment]
@ericclemmons Sure, i'll keep the project with v3.0.20 around. 

I did have to revert back to a backup project using v1.1.29 however, as i noticed some errors in my build and Xcode after the update to v3.0.20, when i started to dig a bit further. But i'll keep it around as a testbed. Thanks
