### ISSUE TITLE
@aws-amplify/storage typo in lib-esm/index.js causing build failure

### ISSUE THREAD

**Issue by paulsjohnson91** [aws-amplify/amplify-js#5739]
**Describe the bug**
To use AWS amplify auth with persistence on a react native app I've installed 
`"@aws-amplify/storage": "^3.1.9"`
In lib-esm/index.js, the last line of code on line 56 has
`export * from './providers';`
However the folder is called `Providers` with a capital P which is causing a build failure

The same can be seen on line 77 of lib-esm/Storage.js

```
Unable to resolve module `./providers` from `node_modules/@aws-amplify/storage/lib-esm/index.js`: 

None of these files exist:
  * node_modules/@aws-amplify/storage/lib-esm/providers(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * node_modules/@aws-amplify/storage/lib-esm/providers/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
0x0


```
**To Reproduce**
Install version 3.1.9 of @aws-amplify/storage

**Code Snippet**
Please provide a code snippet or a link to sample code of the issue you are experiencing to help us reproduce the issue. (Be sure to remove any sensitive data)

**What is Configured?**
   ```
  "dependencies": {
    "@aws-amplify/storage": "^3.1.9",
    "@react-native-community/async-storage": "^1.9.0",
    "@react-native-community/datetimepicker": "^2.3.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^5.6.2",
    "@react-native-community/push-notification-ios": "^1.1.1",
    "@react-native-firebase/app": "6.4.0",
    "@react-native-firebase/messaging": "6.4.0",
    "@react-navigation/bottom-tabs": "5.2.2",
    "@react-navigation/native": "5.2.2",
    "@react-navigation/stack": "5.2.2",
    "amazon-cognito-identity-js": "^3.2.5",
    "aws-amplify": "^3.0.10",
    "aws-amplify-react-native": "^4.1.1"
    ...
}
   ```

**Comment by amhinson** [comment]
Hey @paulsjohnson91 thanks for the detailed issue! Before I dig in, could you try deleting your node modules and installing them again? There have been similar issues recently where that solved it for them.

Also, you shouldn't need to install `@aws-amplify/storage` directly anymore. `aws-amplify` already includes that module.

**Comment by paulsjohnson91** [comment]
Hi, thanks for the quick response.

Your solution worked, it must have been an issue with the folders being changed since a previous version since I was migrating from an earlier version. I've removed the dependency for storage too.

I'll close this issue.
