### ISSUE TITLE
Observable type would be better to export from '@aws-amplify/api'

### ISSUE THREAD

**Issue by tkasuz** [aws-amplify/amplify-js#5741]
**Is your feature request related to a problem? Please describe.**
I always import Observable type from 'zen-observable-ts' to use GraphQL Subscription with Typescript like below.

```typescript
import { API, graphqlOperation } from "aws-amplify"
import { GraphQLResult } from "@aws-amplify/api";
import { Observable } from './../node_modules/zen-observable-ts';
```

But I would like to rather import Observable like this, which looks more natural

```typescript
import { GraphQLResult, Observable } from "@aws-amplify/api";
```

**Describe the solution you'd like**
My suggestion is super simple, which export Observable at '@aws-amplify/api-graphql' like this

index.d.ts
```typescript
export { Observable } from 'zen-observable-ts';
export interface GraphQLResult<T = object> {
    data?: T;
    errors?: [object];
    extensions?: {
        [key: string]: any;
    };
}
```

**Comment by ericclemmons** [comment]
@kopkunka55 This makes sense.  Can you share more of your snippet using `Observable` from `./../node_modules/zen-observable-ts`?  I'm interested to see how you're using it in your code, so I can get the right tests for it.

Thanks!

**Comment by kopkunka55** [comment]
Hi, @ericclemmons 
basically, I often use GraphQL subscription like below in React with Typescript

```typescript
import { OnCreateTodoSubscription } from "./API";
import { API, graphqlOperation } from "aws-amplify";
import { Observable } from './../node_modules/zen-observable-ts';

useEffect(() => {
    const pubSubClient = API.graphql(
      graphqlOperation(onCreateTodo)
    ) as Observable<object>;
    const subscription = pubSubClient.subscribe({
      next: (value: GraphQLResult<OnCreateTodoSubscription>) => {
       // something to store the date to a state
      },
    });
    return () => {
      subscription.unsubscribe();
    };
  }, []);
```

Thanks!

**Comment by ericclemmons** [comment]
Ooh, I see!  I made a demo here:
> https://codesandbox.io/s/aws-amplifyamplify-jsissues5741-ssq5p?file=/src/App.tsx

Without it, the TypeScript error for `API.graphql(...).subscribe` is:

```
Property 'subscribe' does not exist on type 'Promise<GraphQLResult<object>> | Observable<object>'.
  Property 'subscribe' does not exist on type 'Promise<GraphQLResult<object>>'.ts(2339)
```

@manueliglesias Is there a way we can solve this via TypeScript (see below), or do we need to rely on explicit casting (e.g. `as Observable<object>`) as seen above?

https://github.com/aws-amplify/amplify-js/blob/b4b40aa62644ea3688068e4e64f4573c568677a0/packages/api-graphql/src/GraphQLAPI.ts#L173-L183

**Comment by ericclemmons** [comment]
Making a note here: we'll need to update our `lint` and `test` scripts accordingly to test for this error, then correcting the type.

See an example here: 84286be109d7f50eac83a9694e75b61500cc8a83

**Comment by manueliglesias** [comment]
> @manueliglesias Is there a way we can solve this via TypeScript (see below), or do we need to rely on explicit casting (e.g. `as Observable<object>`) as seen above?

Unfortunately we can't solve this via TypeScript, since the return type depends on a runtime inspection of the GraphQL operation type.

We could explore the option of having two methods instead of one, e.g.:

```typescript
function graphql(
  options: GraphQLOptions,
  additionalHeaders: Record<string, string>
): Promise<GraphQLResult>;
```

```typescript
function graphqlSubscription(
  options: GraphQLOptions,
  additionalHeaders: Record<string, string>
): Observable<GraphQLResult>;
```

**Comment by kjellski** [comment]
This problem still exists and I think the solution from @manueliglesias is valid - could we implement it?

**Comment by Stevenje** [comment]
Having the same issue and having to use `// @ts-ignore` would love a fix

**Comment by kilianheinrich** [comment]
Same issue

**Comment by nabeelfarid** [comment]
> Hi, @ericclemmons
> basically, I often use GraphQL subscription like below in React with Typescript
> 
> ```ts
> import { OnCreateTodoSubscription } from "./API";
> import { API, graphqlOperation } from "aws-amplify";
> import { Observable } from './../node_modules/zen-observable-ts';
> 
> useEffect(() => {
>     const pubSubClient = API.graphql(
>       graphqlOperation(onCreateTodo)
>     ) as Observable<object>;
>     const subscription = pubSubClient.subscribe({
>       next: (value: GraphQLResult<OnCreateTodoSubscription>) => {
>        // something to store the date to a state
>       },
>     });
>     return () => {
>       subscription.unsubscribe();
>     };
>   }, []);
> ```
> 
> Thanks!

Should it not be something like this as the next handler expects an object with two parameters (provider and value)

```ts 
next: (payload: {
        provider: AWSAppSyncRealTimeProvider;
        value: GraphQLResult<OnCreateTodoSubscription>;
      }) => {
        console.log(payload);
        console.log(payload.provider);
        console.log(payload.value);```

**Comment by miekassu** [comment]
is only known solution to use `@ts-ignore` ? this is annoying issue, please fix.

**Comment by raykim2414** [comment]
To use "subscribe" in Typescript, try this:

```swift
const subscription = API.graphql({query: Query, authMode: authmode, variables:{}});

if ('subscribe' in subscription) {
  subscription.subscribe({
    next: (event: any) => {}, 
    error: (error: any) => {}
  });
}
```

**Comment by undefobj** [comment]
@elorzafe track for next major version

**Comment by alharris-at** [comment]
This is closely related to https://github.com/aws-amplify/amplify-js/issues/6369, tracking for co-resolution in next major-version.

**Comment by ZYinMD** [comment]
OP, you don't need to import `Observable`. You could do this:
```ts
import { GraphQLSubscription } from '@aws-amplify/api';

const subscription = API.graphql<GraphQLSubscription<typeof onCreateTodo>>(
  graphqlOperation(onCreateTodo)
).subscribe({...});

```

**Comment by Josephenoch** [comment]
For anyone who is having issues with this, I found a workaround for this. The type returned in the next callback isn't exactly accurate, here's a solution for better type safety.


```
import { Observable } from 'zen-observable-ts';
import { GraphQLResult } from '@aws-amplify/api-graphql';

export type AmplifyObservable <T extends {}> = Observable<{
    value: GraphQLResult <T>,
    provider: any
}>```

**Comment by Josephenoch** [comment]
For anyone who is having issues with this, I found a workaround for this. The type returned in the next callback isn't exactly accurate, here's a solution for better type safety.

```javascript
import { Observable } from 'zen-observable-ts';
import { GraphQLResult } from '@aws-amplify/api-graphql';
export type AmplifyObservable <T extends {}> = Observable<{
    value: GraphQLResult <T>,
    provider: any
}>
```

The provider isn't so relevant (except it is, if so you can find the type export).

**Comment by elorzafe** [comment]
On Amplify V6, the library is using `rxjs`

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
