### ISSUE TITLE
No SignIn Section in API Reference Docs

### ISSUE THREAD

**Issue by xon52** [aws-amplify/amplify-js#5752]
**Describe the bug**
There are no `SignIn` section found in the [API Reference Docs](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_Operations.html).

**To Reproduce**
[https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_Operations.html](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_Operations.html)

**Expected behavior**
I would say that `SignIn` would be easily one of the most used API's in this package so it'd be great to have some Docs for it.

**Comment by sammartinez** [comment]
@xon52 This seems to be related to Amazon Cognito instead of AWS Amplify. Please provide this feedback to Amazon Cognito's [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=173) board. Thanks for the feedback!
