### ISSUE TITLE
Amplify.configure() doesn't configure all modules, need to manually configure modules

### ISSUE THREAD

**Issue by idanlo** [aws-amplify/amplify-js#5756]
**Describe the bug**
On our web React application, we do
```js
import Amplify from 'aws-amplify';
import config from 'aws-exports';

Amplify.configure({
  ...config,
  graphql_headers: () => .....
});
```
But in a production build some modules are not working (for example API, Storage) and when manually configuring them using this code works fine - 
```js
Storage.configure(config);
API.configure(config);
```

**To Reproduce**
1. Create app, make sure you have the aws-exports file
2. use Amplify.configure to configure your app
3. run your build script to build the app
4. run your production app and see that your API and Storage requests fail

**Expected behavior**
`Amplify.configure()` configures all needed modules.

**What is Configured?**

```
const awsmobile = {
  "aws_project_region": "",
  "aws_cognito_identity_pool_id": "",
  "aws_cognito_region": "",
  "aws_user_pools_id": ",
  "aws_user_pools_web_client_id": "",
  "oauth": {},
  "aws_appsync_graphqlEndpoint": "",
  "aws_appsync_region": "",
  "aws_appsync_authenticationType": "",
  "aws_user_files_s3_bucket": "", 
  "aws_user_files_s3_bucket_region": "",
  "aws_mobile_analytics_app_id": "",
  "aws_mobile_analytics_app_region": ""
};
```

**Comment by Amplifiyer** [comment]
@idanlo I believe this will be fixed by this PR https://github.com/aws-amplify/amplify-js/pull/5681. It's currently on unstable release. Can you give it a shot and let us know if using unstable version fixed this problem for you?

This fix will be released in stable version in just a few days.
