### ISSUE TITLE
Safari highlights reset password + create account in Authenticator screen

### ISSUE THREAD

**Issue by jasper72** [aws-amplify/amplify-js#5759]
**Describe the bug**

Using the new Authenticator components, the login screen highlights text on Safari on desktop but displays correctly in Chrome.

**To Reproduce**

Open any login screen in Safari on Mac using the new Amplify Authenticator UI framework.

**Expected behavior**
No highlighting of the text

**Code Snippet**

import React from "react";
import { withAuthenticator } from "@aws-amplify/ui-react";

function App() {
  return (
    <div>
      <header>
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a href="https://reactjs.org" target="_blank" rel="noopener noreferrer">
          Learn React
        </a>
      </header>
    </div>
  );
}

export default withAuthenticator(App);

**Screenshots**
![screen](https://user-images.githubusercontent.com/939156/81695379-7179da00-945a-11ea-99ad-6bfab9fe73e9.png)

**Comment by jordanranz** [comment]
Hey @jasper72, this should be fixed by this PR: https://github.com/aws-amplify/amplify-js/pull/5725

Can you try installing @aws-amplify/ui-react@unstable and confirm the fix?

**Comment by jasper72** [comment]
Yes, fixed thanks.

**Comment by jordanranz** [comment]
The fix for this was released to latest. Please feel free to open a new issue if there are any related questions or concerns.
