### ISSUE TITLE
[DataStore]: serialization issue with type AWSJSON

### ISSUE THREAD

**Issue by lambda0xff** [aws-amplify/amplify-js#5767]
**Describe the bug**
With a schema containing a type with an `AWSJSON` property:
```graphql
type MyModel @model {
  id: ID!
  name: String!
  someProp: AWSJSON!
}
```

After `amplify codegen models`, the resulting type for `someProp` is `string` (shouldn't it be `Record<string, any>` ?).

When I save a model, my app fails because at some point, I'm trying to do 'JSON.parse(someProp)' and for some reason, the local indexDB database records the property as: `""{\"key\":1}""` (notice the double double-quotes)

After hitting refresh several times, a sync seems to occur between remote and local datastores, at which point the model is correctly serialized and things work again.

**Comment by yirako** [comment]
I've encountered this issue, too. What I do is `JSON.parse()` once and check the `typeof` of the returned value, if it is a string (which will be, when double double-quotes are used), then we apply `JSON.parse()` again to that value and it works fine on both cases.

**Comment by ondojo** [comment]
Just ran into the same issue. Somewhere along the way the `AWSJSON` type of the GraphQL schema messes up the JSON string. 

Thanks @yirako! 

Your workaround does the trick for now.

**Comment by sammartinez** [comment]
In looking at the issue, this would be more of a feature request since the`JSON.parse(...)` would be something that doesn't exist within our DataStore category.

**Comment by sammartinez** [comment]
#7652

**Comment by iartemiev** [comment]
We just released some changes to the way AWSJSON values are handled in `aws-amplify@4.2.6`. 
You should now receive a JS object from `DataStore.query` and can pass objects as a value to your model when calling `DataStore.save`. Closing this issue, but please let us know if the new version doesn't work the way you expect.
