### ISSUE TITLE
amazon-cognito-identity-js can reset password of users outside of the pool

### ISSUE THREAD

**Issue by mlescaudron** [aws-amplify/amplify-js#5783]
**Describe the bug**
I have a user pool with 4 users
![image](https://user-images.githubusercontent.com/9129639/81925400-d2084300-9623-11ea-83d8-76b53d9dc457.png)

When I want to reset the password of any of my users, I properly receive an email with a token.
But when I type a username that I don't have, I was expecting the same error as AWS CLI but I actually receive a success response like:

```
{
  CodeDeliveryDetails: {
    AttributeName: 'phone_number',
    DeliveryMedium: 'SMS',
    Destination: '+*******8187'
  }
}
```

I don't have any phone numbers stored. If I put a random username, it sends emails or SMS to data that I don't have in my user pool or any user pool that I know.

**To Reproduce**

```
import * as AmazonCognitoIdentity from "amazon-cognito-identity-js";
import fetch from "node-fetch";

export interface GlobalWithCognitoFix extends Global {
  fetch: any;
  navigator: any;
}
declare const global: GlobalWithCognitoFix;

global.fetch = fetch;
global.navigator = () => null;

const userPool = new AmazonCognitoIdentity.CognitoUserPool({
      UserPoolId: "us-east-xxxxx", // replace by yours
      ClientId: "xxxx", // replace by yours
});

 const userData = {
        Username: username,
        Pool: this.userPool,
};

const cognitoUser = new AmazonCognitoIdentity.CognitoUser(userData);
cognitoUser.forgotPassword(
        {
          onSuccess: (data) => {
            console.log(data)
          },
          onFailure: (err) => {
            console.log("ERR:", err)
          },
        }
      );
```

**Expected behavior**

I was expecting to receive an error like AWS CLI: 

"An error occurred (UserNotFoundException) when calling the AdminResetUserPassword operation: User does not exist."

**Comment by sujitsagar** [comment]
I am also facing the same issue.

**Comment by ashika01** [comment]
@sujitsagar @mlescaudron Could one of you post sample code to reproduce this?

@sujitsagar are you using `node-fetch` as well? 

When tried with the react UI, which uses this same API underneath we dont see any issue. We get the error with type `UserNotFoundException`. We think it could be related to some caching.

**Comment by sujitsagar** [comment]
I am using these versions.

```
"aws-amplify": "^2.2.2",
"aws-amplify-react": "^3.1.3",
```

Attaching request, response screenshots for reference. 

<img width="674" alt="Screenshot 2020-06-02 at 10 36 29 PM" src="https://user-images.githubusercontent.com/647175/83989723-f3c7c200-a964-11ea-8bde-1c0e3cef1499.png">
<img width="718" alt="Screenshot 2020-06-02 at 10 34 50 PM" src="https://user-images.githubusercontent.com/647175/83989729-f9250c80-a964-11ea-8db8-c98b1fd30afe.png">

**Comment by ashika01** [comment]
@sujitsagar Could you post sample code to reproduce this? When we tried we definitely did not see this weirdness. Also could you post you `aws-exports ` removing sensitive info?

**Comment by sujitsagar** [comment]
Here is content of our 

**aws-exports.js**
`
import {Auth} from 'aws-amplify';
import Constants from './utils/constants';


const awsmobile = {
    Auth: {

        // REQUIRED only for Federated Authentication - Amazon Cognito Identity Pool ID
        identityPoolId: aws_exports.identitypool_id,
        
        // REQUIRED - Amazon Cognito Region
        region: aws_exports.cognito_region,
        // OPTIONAL - Amazon Cognito User Pool ID
        userPoolId: aws_exports.userpool_id,
        userPoolWebClientId: aws_exports.web_client_id,
        //authenticationFlowType: "aws_exports.authentication_flow_type",
        // cookieStorage: {
        //     domain: "localhost",
        //     path: "/",
        //     expires: 365,
        //     secure: false
        // },
    },
    API: {
        endpoints: [
            {
                name: "API",
                endpoint: PROD_URL,
                custom_header: async () => {
                    let currentSession = await Auth.currentSession();
                    return {
                        Authorization: currentSession.idToken.jwtToken,
                        'Content-type': 'application/json',
                    }
                }
            }
        ]
    },
};
`

CustomForgotPassword.js

`
   Auth.forgotPassword(username)
        .then(data => {
            this.error("Verification code sent to your " + data.CodeDeliveryDetails.DeliveryMedium);
            console.log(data)
            this.setState({ delivery: data.CodeDeliveryDetails, loading: false });
        })
        .catch(err => { 
           this.error(err);
          this.setState({  loading: false }); 
        });
    }
`

**Comment by watanagarwal** [comment]
Hi @sujitsagar 
I am also facing the same issue.
Could you please let me know if you found any solution to this

**Comment by abhisheksett** [comment]
Facing the same issue. Did anyone get any solution/workaround?

**Comment by abhisheksett** [comment]
Is there any way we can prioritize this issue?

@watanagarwal did you find any solution?

**Comment by sammartinez** [comment]
@mlescaudron Im trying to understand your use case, are you looking to do something similar to our [Authenticator component](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react)? Or is your use case focused around Node? For others reading this thread, we do not fully support node at this time within our library. Please let me know what your use case is here

**Comment by abhisheksett** [comment]
@sammartinez I'm trying to do the same implementation what @mlescaudron @sujitsagar mentioned. 
For forgot-password, when I use an email id which is not registered and if I try to request for an auth code, it used to throw me an error saying email not registered. But now it doesn't complain anymore. Any email Id I enter, always get a generic 200 response.

**Comment by sammartinez** [comment]
@abhisheksett Any chance you can cut us a [new issue](https://github.com/aws-amplify/amplify-js/issues/new?assignees=&labels=to-be-reproduced&template=bug_report.md&title=) for us so we can dig into this separately? @mlescaudron Please let us know more on your use case.
