### ISSUE TITLE
Typescript Enums are not exported properly

### ISSUE THREAD

**Issue by PeterBurner** [aws-amplify/amplify-js#5784]
**Describe the bug**
In a typescript based vue app, when using the AmplifyAuthenticator, i'd like to change the usernameAlias parameter, described here https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue#prop-username-alias. However, all the enums from ui-components (except `AuthState` --> see #5416) are not exported properly so vue-cli fails with an error similar to: This dependency was not found: @aws-amplify/ui-components/dist/types/common/types/auth-types.

**To Reproduce**

1. Create a vue-cli app with typescript enabled
2. Setup Amplify as described in the docs
3. Add the `username-alias` property to `amplify-authenticator` like `<amplify-authenticator :username-alias="usernameAlias" />`
4. Add `usernameAlias` to your components props with value `UsernameAlias.email`
5. Import `UsernameAlias` enum (or any other from `@aws-amplify/ui-components`)
6. Build
7. See error

**Expected behavior**
 User should be able to import `UsernameAlias` or any other enum from `@aws-amplify/ui-components` **and use its values**

**Log**
```
ERROR  Failed to compile with 1 errors

This dependency was not found:

* @aws-amplify/ui-components/dist/types/common/types/auth-types in ./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-2!./node_modules/vuetify-loader/lib/loader.js??ref--20-0!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/AuthView.vue?vue&type=script&lang=ts&

To install it, you can run: npm install --save @aws-amplify/ui-components/dist/types/common/types/auth-types
No type errors found
Version: typescript 3.9.2
```

**References**
- #5416

**Comment by jordanranz** [comment]
Hey @PeterBurner, thanks for reporting. Added a PR to export the proper types.

**Comment by PeterBurner** [comment]
works  
thanks
