### ISSUE TITLE
Page does not load if multiple user data is stored in cookie storage

### ISSUE THREAD

**Issue by Steinliiippp** [aws-amplify/amplify-js#5788]
**Describe the bug**
If multiple users a logged in with the cookie storage (i did not try the localstorage) then the pages is not loading. I think is has something to do with the selecton of the LastAuthUser. If i remove alle cookies, which belong to one user and keep the other users cookies the page is loading.

**To Reproduce**
1. Activate the cookie storage of amplify
2. Login into AWS Cognito with one account
3. Login into AWS Cognito with another account on the same page
4. Try to load the site. It will load forever.

**Expected behavior**
The framework (amplify) should select the LastAuthUser and then use the cookies which are associated with this user.

**What is Configured?**
The amplify config is this:
export default {
    Auth: {
        region: "eu-*******"
        userPoolId: "eu-*****_q********",
        userPoolWebClientId: "3e98vt*************",
        cookieStorage: {
            domain: "localhost",
            path: '/',
            expires: 365,
            secure: false
        }
    }
}

**Additional context**
Its the same issue like in #2711.

**Comment by ericclemmons** [comment]
@Steinliiippp Can you complete the bug report template so that we can reproduce "page does not load if multiple user data is stored in cookie storage"?

> https://github.com/aws-amplify/amplify-js/issues/new?assignees=&labels=to-be-reproduced&template=bug_report.md&title=

**Comment by sammartinez** [comment]
@Steinliiippp Please fill in the bug report template so we are able to assist you further on this. Thanks ahead of time
