### ISSUE TITLE
DataStore - Sync engine error on start TypeError: Symbol.asyncIterator is not defined.

### ISSUE THREAD

**Issue by lenarmazitov** [aws-amplify/amplify-js#5789]
**Describe the bug**
I have error message:
```DataStore - Sync engine error on start TypeError: Symbol.asyncIterator is not defined.```
![image](https://user-images.githubusercontent.com/600133/81973664-19470180-962d-11ea-87c3-75844a9bf67d.png)

**To Reproduce**
1. Compliled graphql transfrom
2. Push changes (choose FlowType)
3. Saved data with DataStore
```
await DataStore.save(new User({
          nick: formState.nick
}))
```

**packages**
- amplify cli verion: 4.19.0
- react-native

conflict resolution is configured correctly and tables have all versioning fields, table AmplifyDataStore presents in DynamoDb

Should I use TypeScript to prevent this error?

**Comment by lenarmazitov** [comment]
I've tried to add babel plugin: @babel/plugin-proposal-async-generator-functions
But it did't help.

**Comment by lenarmazitov** [comment]
I added polyfill @azure/core-asynciterator-polyfill and error have gone
But it still not syncing anything on DynamoDb.

**Comment by lenarmazitov** [comment]
@manueliglesias This error could be seen only with React Native Debugger in debug mode.

**Comment by manueliglesias** [comment]
Hi @lenarmazitov 

Which react native version are you using? If not on the latest, can you try on the latest?

regarding:
>  But it still not syncing anything on DynamoDb.

Do you see any network request in the debugger?

**Comment by lenarmazitov** [comment]
@manueliglesias 
I use expo sdk version 36 with react-native 0.61.4

I'm fixed syncing.
The problem was because I installed package @aws-amplify/datastore manually along with "aws-amplify": "^3.0.11".

When I removed package problem dissapear. I still can use @aws-amplify/datastore because I have installed  "aws-amplify": "^3.0.11", but I do not have autocomplete.

I don't know may be there was some version conflicts.

**Comment by manueliglesias** [comment]
Cool! happy to hear that it worked for you. I'll be closing the issue.

**Comment by andrekovac** [comment]
I get the exact same error - but only on **Android**. It works well on iOS and also syncs to the database.
But on Android no single `read` or `write` operation is working. 

I have only the `aws-amplify` package installed and import from `@aws-amplify/datastore` as @lenarmazitov describes but still get the error on Android.

@lenarmazitov Why did you have to add the polyfill `@azure/core-asynciterator-polyfill` ?


My package versions (my app is an ejected Expo app):

```
"aws-amplify": "^3.3.10",
"react-native": "0.63.3",
"expo": "^39.0.4",
```

**Comment by andrekovac** [comment]
Adding the package `@azure/core-asynciterator-polyfill` also made the Android error I got go away for me.
