### ISSUE TITLE
DataStore @connection directive on optional field

### ISSUE THREAD

**Issue by dazweeja** [aws-amplify/amplify-js#5800]
**Describe the bug**
Optional fields with @connection directive appear to be incompatible with DataStore. Valid instances can't be saved/synced. My apologies if I'm making a basic error as I'm new to DataStore, AppSync and GraphQL.

**Amplify CLI Version**
4.19.0

**To Reproduce**
Consider this simple schema:
```
type Lecture @model {
  id: ID!
  title: String!
  blurb: String
  presenter: Presenter @connection(name: "LecturePresenters")
}
type Presenter @model {
  id: ID!
  name: String!
  lectures: [Lecture] @connection(name: "LecturePresenters")
}
```
It seems quite straightforward and similar to other schemas given in the docs. However, this schema does not seem to be able to be used in DataStore. The presenter field on Lecture is deliberately optional. In the real world, a lecture may be created and a presenter found afterwards for the lecture.

Creating a Lecture without presenter DataStore will throw an error when syncing, eg.:
```
await DataStore.save(new Lecture({title: "My First Lecture", blurb: null}));
```
Will throw:
```
One or more parameter values were invalid: Type mismatch for Index Key lecturePresenterId Expected: S Actual: NULL IndexName: gsi-LecturePresenters
```
The POST request is:
```
{"query":"mutation operation($input: CreateLectureInput!) {\n createLecture(input: $input) {\n id\n title\n blurb\n _version\n _lastChangedAt\n _deleted\n presenter {\n id\n _deleted\n }\n }\n}\n","variables":{"input":{"id":<some-id>,"title":"My First Lecture","blurb":null,"lecturePresenterId":null}}}: ""
```
The same result if I pass in 'presenter: null' to new Lecture(). I was not expecting to have to provide a (null) value for 'blurb' in new Lecture() either but it seems that DataStore requires all fields to be provided even if they are optional (requires null value at least).

**Expected behavior**
Schema would be compatible with DataStore.

**Comment by dazweeja** [comment]
I don't believe this is an issue with the JS library. You can't use this schema with Android either. As far as I can tell it's impossible to create a Lecture without a presenter attribute because DataStore requires a value for every attribute, regardless of whether they are optional or not, and for an attribute with a @connection directive, null is an invalid value.

In Android, it gives the error:
```
com.amplifyframework.AmplifyException: An invalid field was provided - presenter is not present in Lecture
```
Whether you use:
```
Lecture lecture = Lecture.builder()
          .title("My First Lecture")
          .build();
```
Or:
```
Lecture lecture = Lecture.builder()
          .title("My First Lecture")
          .blurb(null)
          .presenter(null)
          .build();
```

**Comment by undefobj** [comment]
Can you take a look at the [latest docs for Relational modeling](https://docs.amplify.aws/lib/datastore/relational/q/platform/js) with DataStore and use the latest library version? We made some improvements to the CLI, the library on how it handles this internally, and tried to be explicit about schemas in the documentation including how to use `@key`.

**Comment by dazweeja** [comment]
@undefobj Thanks so much Richard. I've followed the updated docs and this schema works with DataStore and Amplify CLI 4.20.0:

```
type Lecture @model
  @key(name: "byPresenter", fields: ["presenterID", "title"]) {
  id: ID!
  title: String!
  blurb: String
  presenterID: ID
}
type Presenter @model {
  id: ID!
  name: String!
  lectures: [Lecture] @connection(keyName: "byPresenter", fields: ["id"])
}
```
I believe this has solved my issue.

**Comment by undefobj** [comment]
Great to hear! Have a nice weekend.

**Comment by james-braund** [comment]
Hi there - I seem to be encountering this issue myself, around a year after this was closed. I am also trying to create an entity which has an optional relationship with another entity, which gives an error when I do not provide one.

In my data model, I have `Subjects` which can attend one or more `Sessions`. However, when a `Session` initially begins, the `Subject` attending that `Session` is not known, so the `Session` is created without a subject. 

For completeness  - a `Session` takes place at an `Event`, and the `Subjects` attending an `Event` are known ahead of time. I am securing access to this data using IAM roles, to allow me to integrate with a Cognito Federated Identity Pool.

Data models for `Subject` and `Session` defined using GraphQL transform directives as follows:

```
type Session @model
  @key(name: "byEvent", fields: ["eventID"])
  @key(name: "bySubject", fields: ["subjectID"])
  @auth(rules: [
    { allow: private, provider: iam }
  ])
  {
  id: ID!
  eventID: ID!
  event: Event @connection(fields: ["eventID"])
  subjectID: ID
  subject: Subject @connection(fields: ["subjectID"])
}

type Subject @model
  @key(name: "byEvent", fields: ["eventID"])
  @auth(rules: [
    { allow: private, provider: iam }
  ])
  {
  id: ID!
  firstName: String!
  lastName: String!
  eventID: ID!
  event: Event @connection(fields: ["eventID"])
  sessions: [Session] @connection(keyName: "bySubject", fields: ["id"])
}
```

When I attempt to create a new `Session` for a given `eventID`, I get the following error:
```
"One or more parameter values were invalid: Type mismatch for Index Key subjectID Expected: S Actual: NULL IndexName: bySubject (Service: DynamoDb, Status Code: 400, Request ID: XXXXX, Extended Request ID: null)"
```

As recommended above, I've been through the documentation, and can't find anything specifically about this use case, or spot what I might be doing wrong.

In terms of versions, I am using:
```
Amplify CLI: 4.51.2
Amplify JS (aws-amplify npm package): 3.4.0
```

Any suggestions where I might be going wrong?

**Comment by sacrampton** [comment]
I'm having the same issue as @james-braund (#8361)

@undefobj @SwaySway - Richard / Josue - any ideas on this gratefully accepted.
