### ISSUE TITLE
currentSession and currentAuthenticatedUser are throwing errors after an app update 

### ISSUE THREAD

**Issue by ADCrouch** [aws-amplify/amplify-js#5808]
Hi there, 

I'm using `const session = await Auth.currentSession()` to get the idToken from the session.
This works fine but then when I released an app update I noticed that whenever I call this I get an error of `No current user`.

I can see that the session is still stored in my AsyncStorage but I have no idea how to get a new idToken from the refresh token.

I tried calling this to refresh my idToken with the refreshToken from the storage
`const cognitoUser = await Auth.currentAuthenticatedUser();
cognitoUser.refreshSession({ getToken: () => refreshToken }, (err, session) => {` 

but I'm getting an error that the user is not authenticated.

Has anyone come across this issue?
What is the best way to get the session after an app update?
Making the users login again is not an option.

I'm using, 
aws-amplify: v2.2.0 (I tried 3.0.11 it didn't solve the issue)
react-native: 0.59.1

Let me know if you need me to provide more details.

Thanks 

**Update:**

I tried providing my own storage object based on #4027  but my issue still persists, it works fine until I update the app

I can also now confirm this is happening for both iOS and Android devices

**Comment by Ashish-Nanda** [comment]
@ADCrouch does the issue happen when you refresh your app (eg. with Cmd +R on iOS) when developing as well? Or only when you update the app. 
Is installing the app again the right way to simulate this?

Any more steps you can give to make reproduction of the issue more clear will be helpful

**Comment by ADCrouch** [comment]
@Ashish-Nanda This is not happening when refreshing the app or when closing and opening.
The current implementation using `Auth.currentSession()` is live and used by many users without any issues. 

The way to reproduce it:

1. Installed the latest production app
2. Merged the release branch which does not include any Amplify changes 
3. Run `npm install && cd ios && pod install && cd .. && react-native run-<ios or android>`
I also tried Deleting the node_modules and Pods before the installation, it has no effect.
4. When the app opens it goes through `Auth.currentSession()` and I get `No current user`

Can you please confirm if the `sync` function is working correctly from your end?

Let me know if you need me to provide any additional information.

**Comment by ADCrouch** [comment]
@Ashish-Nanda I found the culprit!
We accidentally changed the userPoolWebClientId, reverting it back solved the issue.

Thank you for looking into it.
