### ISSUE TITLE
Amplify auth signIn runs Pre-token generation trigger twice. Unable to override idToken

### ISSUE THREAD

**Issue by nikhil-shrestha** [aws-amplify/amplify-js#5813]
**Describe the bug**
Cognito Trigger: Pre Token Generation is being trigger twice with `Auth.signIn` 
 `2020-05-18T05:42:11.915Z	6dccf05e-d970-4fb5-9b4a-a2bb59c92a44	INFO	TokenGeneration_Authentication`
`2020-05-18T05:42:14.529Z	cd24f3fe-0d40-4c27-838d-3f3d14d077fa	INFO	TokenGeneration_RefreshTokens`

Amplify `Auth.signIn(email, password, { domain })` trigger twice one for  `Authentication` and another `RefreshTokens` due to which i'm unable to add the custom claim to id_token as the refereshToken override the old token created from `TokenGeneration_Authentication`

**Amplify Version**
3.0.8

**To Reproduce**

1. add Cognito Trigger: Pre Token Generation 
2. Goto app Login
3. Goto the CloudWatch

**Expected behavior**

**Code Snippet**
Please provide a code snippet or a link to sample code of the issue you are experiencing to help us reproduce the issue. (Be sure to remove any sensitive data)

**index.js**
```
Amplify.configure({
  Auth: {
    region: config.cognito.REGION,
    userPoolId: config.cognito.USER_POOL_ID,
    identityPoolId: config.cognito.IDENTITY_POOL_ID,
    userPoolWebClientId: config.cognito.APP_CLIENT_ID,
  },
});
```

**login.js**
```
const handleSignInSubmit = async (event) => {
    await Auth.signIn(email, password, { domain });
};
```

**preTokenGen.js**
```
exports.handler = async (event) => {
  console.log('event>>', JSON.stringify(event));

  let payload, params, domain;

  const { userAttributes } = event.request;
  const { sub } = userAttributes;

  switch (event.triggerSource) {
    case 'TokenGeneration_HostedAuth':
      console.log('TokenGeneration_HostedAuth');
      break;

    case 'TokenGeneration_Authentication':
      console.log('TokenGeneration_Authentication');

      domain = event.request.clientMetadata['domain'];

      console.log({ domain });
      // Call tenant service get tenantId from database
      payload = {
        arguments: {
          userId: sub,
          normName: domain,
        },
        field: 'getUser',
      };

      params = {
        FunctionName: process.env.APP_STAGE + '-tenantService',
        InvocationType: 'RequestResponse',
        LogType: 'None',
        Payload: JSON.stringify(payload),
      };

      const tntRslt = await invoke(params);
      console.log('tntRslt>>>', tntRslt);

      const result = JSON.parse(tntRslt);
      console.log('result>>>', result);

      const tenantId = result.tenantId;
      console.log({ tenantId });

      event.response = {
        claimsOverrideDetails: {
          claimsToAddOrOverride: {
            tenant_id: tenantId,
          },
        },
      };
      break;

    case 'TokenGeneration_RefreshTokens':
      console.log('TokenGeneration_RefreshTokens');
      break;

    default:
      break;
  }

  console.log('result::', JSON.stringify(event));

  return event;
};
```

**CloudWatch Log**
```
2020-05-18T05:42:11.915Z 6dccf05e-d970-4fb5-9b4a-a2bb59c92a44 INFO TokenGeneration_Authentication
2020-05-18T05:42:14.529Z cd24f3fe-0d40-4c27-838d-3f3d14d077fa INFO TokenGeneration_RefreshTokens
```

**Additional context**

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by manueliglesias** [comment]
Hi @nikhil-shrestha 

Which versions of amplify are you using?

**Comment by nikhil-shrestha** [comment]
@manueliglesias i'm using amplify 3.0.8

**Comment by nikhil-shrestha** [comment]
@manueliglesias any luck with trying to reproduce the bug

**Comment by manueliglesias** [comment]
Hi @nikhil-shrestha I am looking into it, will circle back with an update soon

**Comment by manueliglesias** [comment]
Hi @nikhil-shrestha 

I've confirmed that the token refresh is no longer being called right after signIn, please upgrade to the latest version of Amplify.

But, while investigating this, I found that at the moment, amplify is not sending the claims you used to sign in when you refresh the token. This means that when the time to refresh the tokens comes, your lambda won't receive the client metadata.

I am labeling this as a feature-request

**Comment by ohnu** [comment]
> This means that when the time to refresh the tokens comes, your lambda won't receive the client metadata.

@manueliglesias I just run into this issue you described, any updates on this ? 
(ps. maybe it makes sense to track it as a separate issue)

**Comment by bronhy** [comment]
@manueliglesias Is there a bug ticket for this so we could follow the progress?

**Comment by econtentmaps** [comment]
Any news on this? Real problem for us that refresh doesn't send the configured clientmetadata - our pre-token lambda requires this metadata.

**Comment by abhimanyuraj** [comment]
@jimjoes Did you find any luck with getting clientmetadata ?

**Comment by cwomack** [comment]
For anyone following this issue, the problem with the `Auth.signIn()` running the pre-token generation trigger 2x has been resolved for quite some time in previous major versions (we [recently released v6](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593) that uses new, functional API's for Auth).  Apologies for the delays in communicating that! 

For the comments related to clientMetaData, please see if any of these issues related to that subject can help us consolidate the feedback/feature-requests/problems to get more context: 

- #5522 
- #5318 
- #8388
