### ISSUE TITLE
Cannot find documentation for previous versions of amplify-js and aws-amplify-react

### ISSUE THREAD

**Issue by zsid** [aws-amplify/amplify-js#5815]
**Describe the bug**
I have joined a legacy project which is using ` "aws-amplify": "^1.1.8"` and ` "aws-amplify-react": "^2.1.2"` and it is not possible to migrate at the moment to the newer versions. I find it very difficult to navigate the documentation and find out the different versions - it seems impossible task to me. 

**To Reproduce**
Try to find the documentation for previous versions especially `1` or `2`.

**Expected behaviour**
I would expect to see versions of the documentation and be able to select the appropriate one easily.

**Comment by jordanranz** [comment]
Hey @zsid, can you provide any details on the reasons for not being able to migrate to the newer versions? amplify 3 is mostly backwards compatible with 1 and 2. Breaking changes from 1 to 2 were very minor and slightly affect behavior on `API.graphql`. Breaking changes from 2 to 3 are listed [here](https://github.com/aws-amplify/amplify-js#notice)

I added a [feature request](https://github.com/aws-amplify/amplify-js/issues/5820) to better document the breaking changes from 1 to 2.

**Comment by zsid** [comment]
Hey @jordanranz, due to time constraints cannot spend time updating packages as there are dependancies between different projects. 

Apart from breaking changes, what I will really like is similar to https://material-ui.com/versions/ where you can open the documentations for the previous versions and navigate there. People are still encouraged to migrate to newer versions but if they cannot do it at the moment due to time constraints, it will be a better user experience to navigate to the docs and read about the implementation there

**Comment by mauerbac** [comment]
Thanks for the feedback @zsid. Going to close this issue as Jordan opened up the change log FR.
