### ISSUE TITLE
AWS Pinpoint Analytics Events resource not found

### ISSUE THREAD

**Issue by sonphnt** [aws-amplify/amplify-js#5816]
**Describe the bug**
I am using AWS Amplify analytics and Pinpoint for tracking user behaviours. Everything works well with Events such as pageView, custom events. But regarding to Custom attributes and User attributes, I can not see it in Console, get an error "Resource not found: attribute not found" when selecting on it.

**Expected behavior**
Should work without red error notification with "Resource not found: attribute not found"

**Screenshots**
![Capture](https://user-images.githubusercontent.com/5907220/82214179-b77ce500-9915-11ea-8faf-cc27ebddbf34.JPG)

**What is Configured?**
   ```
Analytics.updateEndpoint({
      attributes: {
        // Custom attributes that your app reports to Amazon Pinpoint. You can use these attributes as selection criteria when you create a segment.
        interests2: ["science2", "politics2", "travel2"]
      },
      userAttributes: {
        interests3: ["football", "basketball", "AWS"],
        username3: ["ilovethecloud"]
      }
    });
   ```

I call the updateEndpoint above to update attributes and go to AWS PinPoint Events, select my custom attributes then get the error message as described.
I am using "Unauthenticated identities" from Cognito pool to allow access to AWS Pinpoint.

**Comment by sammartinez** [comment]
@sonphnt Can you provide us with your `package.json` ? Thanks ahead of time
