### ISSUE TITLE
"Continue with Facebook" button does not show up on hosted UI

### ISSUE THREAD

**Issue by devth** [aws-amplify/amplify-js#5819]
**Describe the bug**
I configured Cognito via Amplify CLI and setup all oauth providers: Google, Facebook, and Amazon. I followed the [setup docs](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-social-idp.html)

I can successfully log in with Facebook if I create my own button, like:

```jsx
    <Button
      onClick={() => Auth.federatedSignIn({provider: 'Facebook'})} color="inherit">
      Facebook sign in
    </Button>
```

but if I send the user to the Cognito Hosted UI, like:

```jsx
    <Button
      onClick={() => Auth.federatedSignIn()} color="inherit">
      Login / Sign up
    </Button>
```

Then only Amazon and Google login options show up:

![image](https://user-images.githubusercontent.com/86107/82226647-fdb95080-98e3-11ea-8520-546d30bfcf1b.png)

**To Reproduce**

1. Configure all 3 login mechanisms with `amplify auth add`
2. Call `Auth.federatedSignIn()` on button click
3. Observe that Facebook is missing

**Expected behavior**

"Continue with Facebook" should show on the hosted UI, as demonstrated in [Adding Facebook Sign In for Web Applications with AWS Amplify by Nader Dabit](https://dev.to/aws/adding-facebook-sign-in-for-web-applications-with-aws-amplify-2fc8)

**What is Configured?**

```
amplify add auth
```
and

```
amplify update auth
```

**Comment by mauerbac** [comment]
Hi @devth - I wasn't able to reproduce this issue.

Can you try: 
1) `amplify update auth` and select Update OAuth social providers. Ensure all three are selected. 
2) In the AWS console, choose your Cognito user pool and select Identify Providers under Federation on the left hand side. You should see Google, Facebook and Amazon selected? 

Let me know
