### ISSUE TITLE
Add breaking changes to README and/or docs for migrating from Amplify 1 to 2

### ISSUE THREAD

**Issue by jordanranz** [aws-amplify/amplify-js#5820]
There is no centralized place for breaking changes. We should change that!

**Comment by zsid** [comment]
What about having something like `https://material-ui.com/versions/` where you can also browse the docs of previous versions?

**Comment by mauerbac** [comment]
+1 to a formal change log

**Comment by SebSchwartz** [comment]
Yes it is really missing a clear changelog :)

**Comment by mauerbac** [comment]
marking as duplicate in favor of https://github.com/aws-amplify/amplify-js/issues/3974

**Comment by andidev** [comment]
@mauerbac 
Can you please link to the changelog for breaking changes? Or is there any? I am stuck on amplify 1.x.x and want to upgrade to 3.x.x. How can I find the breaking changes?
