### ISSUE TITLE
DataStore forces autogenerated partition key

### ISSUE THREAD

**Issue by lenarmazitov** [aws-amplify/amplify-js#5821]
**Describe the bug**
When I try to save model with defined partition key
```
await DataStore.save(new User({
    id: "someCutommId",
    owner: username,
    name: "Some name",
}))
```
I've get new document in DynamoDb with autogenerated partition key

**Expected behavior**
New document in DynamoDb with given partition key.

**Comment by manueliglesias** [comment]
Hi @lenarmazitov 

This is a duplicate of aws-amplify/amplify-cli#3108, please see @undefobj [comment](https://github.com/aws-amplify/amplify-cli/issues/3108#issuecomment-592279776).
