### ISSUE TITLE
React.js AuthError - Error: Amplify has not been configured correctly.

### ISSUE THREAD

**Issue by hyprstack** [aws-amplify/amplify-js#5836]
**Describe the bug**
Have tried to manually integrate amplify in an existing react-app. I have succeeded in similar projects before, but have now migrated to the @aws-amplify/auth module and keep getting an annoying, and very un-helpful, error in the console:

`[ERROR] 00:42.548 AuthError - 
            Error: Amplify has not been configured correctly. 
            The configuration object is missing required auth properties. 
            Did you run `amplify push` after adding auth via `amplify add auth`?
            See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information`

Not only that but the form is now pushed to the left although the container div has `justify-content: center`, whereas before with the exact same styling, it was centred. Not sure if this is linked to previous error, but is annoying.

<img width="1269" alt="Screenshot 2020-05-19 at 16 01 48" src="https://user-images.githubusercontent.com/5845311/82342903-16ac2980-99ea-11ea-9d8f-37722131b65b.png">

I have tried both formats of config files as shown here:

```javascript
{
  "Auth": {
      "identityPoolId": "xxxxx:xxxxxxxx",
      "region": "xxxxxx",
      "identityPoolRegion": "xxxxxx",
      "userPoolId": "eu-west-xxxxxxxx",
      "userPoolWebClientId": "xxxxxxxxxxx",
      "mandatorySignIn": "true",
      "authenticationFlowType": 'USER_PASSWORD_AUTH',
      "oauth": {
        "domain": 'https://xxxxxxxx.xxxxxx.amazoncognito.com',
        "scope": ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
        "redirectSignIn": 'http://localhost:3000/',
        "redirectSignOut": 'http://localhost:3000/',
        "responseType": 'code' // or 'token', note that REFRESH token will only be generated when the responseType is code
      }
    }
}
```

and 

```javascript
{
     "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_pools_id": "xxxxxxx",
    "aws_user_files_s3_bucket": "xxxx",
    "aws_project_region": "xxxxx",
    "aws_cognito_region": "xxxxx",
    "aws_appsync_region": "xxxxx",
    "aws_content_delivery_bucket_region": "xxxxx",
    "aws_user_files_s3_bucket_region": "xxxxxx",
    "aws_cognito_identity_pool_id": "xxxxxx",
    "aws_user_pools_web_client_id": "xxxxxxxx"
    "oauth": {}
}
```

My package.json is as follows:

```javascript
{
  "name": "demo-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@aws-amplify/auth": "^3.2.7",
    "@aws-amplify/ui-react": "^0.2.6",
    "@date-io/moment": "^2.0.1",
    "@fortawesome/fontawesome-svg-core": "^1.2.26",
    "@fortawesome/free-brands-svg-icons": "^5.12.0",
    "@fortawesome/free-solid-svg-icons": "^5.12.0",
    "@fortawesome/react-fontawesome": "^0.1.8",
    "@material-ui/core": "^4.8.3",
    "@material-ui/icons": "^4.5.1",
    "@material-ui/lab": "^4.0.0-alpha.40",
    "@material-ui/pickers": "^3.2.9",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.4.0",
    "@testing-library/user-event": "^7.2.1",
    "aws-amplify": "^2.3.0",
    "aws-sdk": "^2.608.0",
    "axios": "^0.19.2",
    "local-storage": "^2.0.0",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "nconf": "^0.10.0",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-redux": "^7.1.3",
    "react-router-dom": "^5.1.2",
    "react-scripts": "^3.4.0",
    "redux": "^4.0.5",
    "typeface-roboto": "0.0.75",
    "uuid": "^3.4.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

I have tried deleting node_modules and packga-lock.json and re-installing without any change.

This is my app.js file:

```javascript 
import React from 'react';
import ReactDOM from 'react-dom';
import Amplify, { Auth } from 'aws-amplify';
import { AmplifyAuthenticator } from '@aws-amplify/ui-react';
import App from './App';
import './index.css';
import * as serviceWorker from './serviceWorker';

import { Provider } from 'react-redux';
import { createStore } from 'redux'
import rootReducer from './reducers'

/*global CONFIG */ --> This is {AWS: {Auth: {...}}}
import awsconfig from './aws-exports';
Amplify.configure(awsconfig);
Amplify.configure(CONFIG.AWS) // This also fails

const store = createStore(rootReducer, []);

ReactDOM.render(
  <Provider store={store}>
    <AmplifyAuthenticator>
      <App />
    </AmplifyAuthenticator>
  </Provider>,
  document.getElementById('root')
);

serviceWorker.unregister();
```

Running `npm list | grep "amplify"` yields the following:

```javascript
├─┬ @aws-amplify/auth@3.2.7
│ ├─┬ @aws-amplify/cache@3.1.10
│ │ └── @aws-amplify/core@3.2.7 deduped
│ ├─┬ @aws-amplify/core@3.2.7
├─┬ @aws-amplify/ui-react@0.2.6
│ ├── UNMET PEER DEPENDENCY @aws-amplify/auth@^2.1.5
│ ├── UNMET PEER DEPENDENCY @aws-amplify/core@^2.2.4
│ └─┬ @aws-amplify/ui-components@0.4.1
├─┬ aws-amplify@2.3.0
│ ├─┬ @aws-amplify/analytics@2.2.8
│ │ ├─┬ @aws-amplify/cache@2.1.8
│ │ │ ├── @aws-amplify/core@2.3.0 deduped
│ │ ├─┬ @aws-amplify/core@2.3.0
│ ├─┬ @aws-amplify/api@2.2.1
│ │ ├─┬ @aws-amplify/auth@2.1.8
│ │ │ ├── @aws-amplify/cache@2.1.8 deduped
│ │ │ ├── @aws-amplify/core@2.3.0 deduped
│ │ ├─┬ @aws-amplify/cache@2.1.8
│ │ │ ├── @aws-amplify/core@2.3.0 deduped
│ │ ├─┬ @aws-amplify/core@2.3.0
│ ├─┬ @aws-amplify/auth@2.1.8
│ │ ├── @aws-amplify/cache@2.1.8 deduped
│ │ ├── @aws-amplify/core@2.3.0 deduped
│ ├─┬ @aws-amplify/cache@2.1.8
│ │ ├── @aws-amplify/core@2.3.0 deduped
│ ├─┬ @aws-amplify/core@2.3.0
│ ├─┬ @aws-amplify/datastore@1.2.0
│ │ ├── @aws-amplify/api@2.2.1 deduped
│ │ ├─┬ @aws-amplify/core@2.3.0
│ │ ├── UNMET PEER DEPENDENCY @aws-amplify/pubsub@2.1.9 deduped
│ ├─┬ @aws-amplify/interactions@2.1.8
│ │ ├─┬ @aws-amplify/core@2.3.0
│ ├─┬ @aws-amplify/predictions@2.1.8
│ │ ├─┬ @aws-amplify/core@2.3.0
│ │ ├── @aws-amplify/storage@2.2.3 deduped
│ ├─┬ UNMET PEER DEPENDENCY @aws-amplify/pubsub@2.1.9
│ │ ├─┬ @aws-amplify/auth@2.1.8
│ │ │ ├── @aws-amplify/cache@2.1.8 deduped
│ │ │ ├── @aws-amplify/core@2.3.0 deduped
│ │ ├─┬ @aws-amplify/cache@2.1.8
│ │ │ ├── @aws-amplify/core@2.3.0 deduped
│ │ ├─┬ @aws-amplify/core@2.3.0
│ ├─┬ @aws-amplify/storage@2.2.3
│ │ ├─┬ @aws-amplify/core@2.3.0
│ ├── @aws-amplify/ui@1.2.3
│ ├─┬ @aws-amplify/xr@1.1.8
│ │ ├─┬ @aws-amplify/core@2.3.0
npm ERR! peer dep missing: @date-io/core@^1.3.6, required by @material-ui/pickers@3.2.10
npm ERR! peer dep missing: @aws-amplify/auth@^2.1.5, required by @aws-amplify/ui-components@0.4.1
npm ERR! peer dep missing: @aws-amplify/core@^2.2.4, required by @aws-amplify/ui-components@0.4.1
npm ERR! peer dep missing: @aws-amplify/pubsub@^1.2.4, required by @aws-amplify/api@2.2.1
npm ERR! peer dep missing: @aws-amplify/pubsub@^1.2.4, required by @aws-amplify/api@2.2.1
npm ERR! peer dep missing: @react-native-community/netinfo@^5.5.0, required by @aws-amplify/core@2.3.0
npm ERR! peer dep missing: @react-native-community/netinfo@^5.5.0, required by @aws-amplify/core@2.3.0
npm ERR! peer dep missing: @react-native-community/netinfo@^5.5.0, required by @aws-amplify/core@2.3.0
npm ERR! peer dep missing: @react-native-community/netinfo@^5.5.0, required by @aws-amplify/core@2.3.0
npm ERR! peer dep missing: @react-native-community/netinfo@^5.5.0, required by @aws-amplify/core@2.3.0
npm ERR! peer dep missing: @react-native-community/netinfo@^5.5.0, required by @aws-amplify/core@2.3.0
npm ERR! peer dep missing: @aws-amplify/pubsub@^1.2.4, required by @aws-amplify/api@2.2.1
npm ERR! peer dep missing: @aws-amplify/pubsub@^1.2.4, required by @aws-amplify/api@2.2.1
npm ERR! peer dep missing: @react-native-community/netinfo@^5.5.0, required by @aws-amplify/core@2.3.0
npm ERR! peer dep missing: @react-native-community/netinfo@^5.5.0, required by @aws-amplify/core@2.3.0
npm ERR! peer dep missing: @react-native-community/netinfo@^5.5.0, required by @aws-amplify/core@2.3.0
npm ERR! peer dep missing: @react-native-community/netinfo@^5.5.0, required by @aws-amplify/core@2.3.0
npm ERR! peer dep missing: @react-native-community/netinfo@^5.5.0, required by @aws-amplify/core@2.3.0
npm ERR! peer dep missing: @react-native-community/netinfo@^5.5.0, required by @aws-amplify/core@2.3.0
npm ERR! peer dep missing: @react-native-community/netinfo@^5.5.0, required by @aws-amplify/core@2.3.0
npm ERR! peer dep missing: typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta, required by tsutils@3.17.1
npm ERR! peer dep missing: typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta, required by tsutils@3.17.1
```

**Comment by Fanner487** [comment]
I'm getting the exact same issue too. I just rolled back my package version to use the last version from `^3.2.7` to `3.2.6` and it worked fine

**Comment by hyprstack** [comment]
> I'm getting the exact same issue/error too. I just rolled back my package version to use the last version from `^3.2.7` to `3.2.6` and it's now working again. Hopefully, this issue can be resolved.
> 
> Hope this helps you too!

@Fanner487 This didn't resolve my issue unfortunately, but I rolled back so that my package.json looked like

```javascript
 "dependencies": {
    "@date-io/moment": "^2.0.1",
    "@fortawesome/fontawesome-svg-core": "^1.2.26",
    "@fortawesome/free-brands-svg-icons": "^5.12.0",
    "@fortawesome/free-solid-svg-icons": "^5.12.0",
    "@fortawesome/react-fontawesome": "^0.1.8",
    "@material-ui/core": "^4.8.3",
    "@material-ui/icons": "^4.5.1",
    "@material-ui/lab": "^4.0.0-alpha.40",
    "@material-ui/pickers": "^3.2.9",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.4.0",
    "@testing-library/user-event": "^7.2.1",
    "aws-amplify": "^2.2.1",
    "aws-amplify-react": "^3.1.9",
    "aws-amplify-react-native": "^2.2.3",
    "aws-sdk": "^2.608.0",
    "axios": "^0.19.2",
    "local-storage": "^2.0.0",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "nconf": "^0.10.0",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-redux": "^7.1.3",
    "react-router-dom": "^5.1.2",
    "react-scripts": "^3.4.0",
    "redux": "^4.0.5",
    "typeface-roboto": "0.0.75",
    "uuid": "^3.4.0"
  }
```

This has worked to resolve my immediate issue. 

However I am hoping that the Amplify team can get back to me with an answer to this issue.

**Comment by ryanhinojosa** [comment]
I'm getting this exact same error while moving from Amplify 2.x to 3. Any guidance here would be enormously helpful!

**Comment by ryanhinojosa** [comment]
I was able to get past this error by:
- Removing all Amplify dependencies in package.json
- Deleting package.json
- Deleting node_modules
- npm install aws-amplify @aws-amplify/ui-react
- Going to this page ([](https://docs.amplify.aws/lib/auth/start/q/platform/js#configure-your-application)) and starting with the section "Re-use existing authentication resource" since I already had a Cognito back-end set up.

Hopefully this works for you.

**Comment by manueliglesias** [comment]
Hi @hyprstack 

I noticed you have this in your `package.json`:

```
    "aws-amplify": "^2.2.1",
    "aws-amplify-react": "^3.1.9",
    "aws-amplify-react-native": "^2.2.3",
```
I think you don't need both `aws-amplify-react` and `aws-amplify-react-native` in your project, typically you use one or the other depending on your platform. Also, can you try using the latest versions and make sure you remove your `node_modules` and lock files (`yarn.lock` and `package-lock.json`)?

Basically, @ryanhinojosa 's suggestions 

Let us know how it goes

**Comment by qtagtech** [comment]
I found out that by mistake I had both @aws-amplify/core@3.2.7(latest) and aws-amplify@3.0.10 (one before the latest). I updated to just have aws-amplify 3.0.11 and it worked again. I say again because before in a different branch the project was with @aws-amplify/core@^3.2.7 and aws-amplify@^3.0.10. Probably it was installing both the latest versions and not having the conflict? It might just give some light into the problem.

**Comment by hyprstack** [comment]
@manueliglesias I had deleted my node modules and lock file as describe above.
@qtagtech thanks I will give this a try and let you know.

thanks

**Comment by alexandprivate** [comment]
> I was able to get past this error by:
> 
> * Removing all Amplify dependencies in package.json
> * Deleting package-lock.json
> * Deleting node_modules
> * npm install aws-amplify @aws-amplify/ui-react
> * Going to this page ([docs.amplify.aws/lib/auth/start/q/platform/js#configure-your-application](https://docs.amplify.aws/lib/auth/start/q/platform/js#configure-your-application)) and starting with the section "Re-use existing authentication resource" since I already had a Cognito back-end set up.
> 
> Hopefully this works for you.

I can confirm this works for me! Thanks @ryanhinojosa

**Comment by hyprstack** [comment]
I am still unable to replicate the fix provided by @ryanhinojosa . I have in the meantime used an entirely new laptop and tried following the solution provided above. I then tried following the docs and used the `AmplifyAuthenticator` component. With the docs from using an already existing user pool, there was no login page and the app simple seemed to proceed as if the user was logged in, although I had cleared the local storage and cache.

For now it seems I am going to keep using the previous version and logical flow.

**Comment by iaarnio** [comment]
I had these amplify dependencies:
```
"@aws-amplify/api": "latest",
"@aws-amplify/auth": "^3.2.13",
"@aws-amplify/pubsub": "latest",
"aws-amplify": "^3.0.7",
"aws-amplify-react": "^4.1.6",
```
Hard locking the versions to few days older versions (and removing node_modules and the lock file) fixed the issue for me:
```
"@aws-amplify/api": "3.1.15",
"@aws-amplify/auth": "3.2.12",
"@aws-amplify/pubsub": "3.0.16",
"aws-amplify": "3.0.16",
"aws-amplify-react": "4.1.15",
```

**Comment by JohanAltamar** [comment]
> I was able to get past this error by:
> 
> * Removing all Amplify dependencies in package.json
> * Deleting package-lock.json
> * Deleting node_modules
> * npm install aws-amplify @aws-amplify/ui-react
> * Going to this page (https://docs.amplify.aws/lib/auth/start/q/platform/js#configure-your-application) and starting with the section "Re-use existing authentication resource" since I already had a Cognito back-end set up.
> 
> Hopefully this works for you.

Still working :)

**Comment by ashika01** [comment]
@hyprstack Usually this happens in case one dependencies not being linked to each other properly. Either use all latest version or using all pinned version should help you fix this issue.
