### ISSUE TITLE
DataStore blocking cloud sync in any model after a save call without subscription

### ISSUE THREAD

**Issue by yirako** [aws-amplify/amplify-js#5843]
**Describe the bug**
Just like the title says, DataStore just blocks any type of sync op with the cloud if a `DataStore.save()` is called without any subscription. Any consecutive `.observe(Model).subscribe()` calls are not taken in count for updating nor it does reply to the cloud (both ways).

All data updates locally without any warning, so there's no way of knowing the model has been correctly synced before clearing using `DataStore.clear()`, everything just looks like is working fine.

**Amplify CLI Version**
4.13.4

package.json dependencies:
```
"@aws-amplify/core": "^3.2.7",
"@aws-amplify/datastore": "^2.1.0",
"amazon-cognito-identity-js": "^4.2.4",
"aws-amplify": "^3.0.11",
"aws-amplify-react-native": "^4.1.2",
```

**To Reproduce**
With internet access
1. Start a subscription in a model, save a new record, and unsubscribe from it.
2. Call a `.save()` on the same model.
3. Call any other model method that should sync to the cloud on *any* model (subscribe, save, etc)

**Expected behavior**
Data should be synced in the cloud too.

**Desktop (please complete the following information):**
 - OS: Android (React Native)
 - Node Version: v12.16.1

**Additional context**
It seems that a "global" subscription is started by DataStore automatically when it doesn't detect an active subscription. If another subscription is done before it, this doesn't happen. But it is not mentioned anywhere in the docs and/or it shouldn't be affecting the app globaly (other models in other screens/components).

I'm open to provide more info if needed.

**Comment by manueliglesias** [comment]
Hi @yirako 

I just tried the scenario you outlined in a fresh app and I can see the network traffic for the mutations and incoming subscription messages.

These are the versions I am using:

```
❯ yarn list --depth=0 --pattern amplify
yarn list v1.22.4
├─ @aws-amplify/api-graphql@1.0.14
├─ @aws-amplify/api-rest@1.0.14
├─ @aws-amplify/api@3.1.12
├─ @aws-amplify/auth@3.2.9
├─ @aws-amplify/cache@3.1.12
├─ @aws-amplify/core@3.2.9
├─ @aws-amplify/datastore@2.1.2
└─ @aws-amplify/pubsub@3.0.13
✨  Done in 0.85s.
```

I used [Flipper](https://fbflipper.com/) to inspect the network traffic on React Native.

The other thing you could try is to increase Amplify's logger level to see what's happening:

```javascript
Amplify.Logger.LOG_LEVEL = 'DEBUG';
```
