### ISSUE TITLE
aws-amplify not working in react-native 0.62.2

### ISSUE THREAD

**Issue by govindat415** [aws-amplify/amplify-js#5848]
Error: Unable to resolve module `aws-amplify` from `index.js`: aws-amplify could not be found within the project or in these directories: node_modules

aws-amplify WAS installed with npm and the pods were installed.

**To Reproduce**

```
npx react-native init RNAmplify && cd RNAmplify

amplify pull <application> (to get my existing backend)

npm install aws-amplify aws-amplify-react-native amazon-cognito-identity-js react-native-vector-icons @react-native-community/netinfo

cd ios && pod install && cd ..
```

added UIAppFonts in application's info.plist. (THIS MIGHT BE PART OF THE ISSUE BUT RNAmpIntr WAS NOT IN THE IOS DIRECTORY AS THE DOCUMENTATION STATES THERE WOULD BE)

index.js:

`import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

import Amplify from 'aws-amplify'
import config from './aws-exports'
Amplify.configure(config)

AppRegistry.registerComponent(appName, () => App);
`

`npx react-native run-ios`

**Expected behavior**
The application should start and the amplify configuration should be completed but it is unable to find aws-amplify even though it is in node_modules

**What is Configured?**
package.json:

...
"dependencies": {
    "@react-native-community/netinfo": "^5.9.0",
    "amazon-cognito-identity-js": "^4.2.4",
    "aws-amplify": "^3.0.11",
    "aws-amplify-react-native": "^4.1.2",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-vector-icons": "^6.6.0"
  },
...

**Comment by stephanrotolante** [comment]
We had an issue with apmlify version on our RN project. Did you recently update amplify on your project?

**Comment by govindat415** [comment]
> We had an issue with apmlify version on our RN project. Did you recently update amplify on your project?

I am creating a new project and installing amplify as the guides direct me to, so i believe it is using the latest ampify.

How did you end up solving the issue? (What combination of versions worked for your RN project)

**Comment by govindat415** [comment]
@stephanrotolante 

I am creating a new project and installing amplify as the guides direct me to, so i believe it is using the latest ampify.

How did you end up solving the issue? (What combination of versions worked for your RN project)

**Comment by stephanrotolante** [comment]
It was peer dependency issue with aws-amplify and aws-amplify-react-native. Try downgrading the aws-amplify-react-native vserion

**Comment by govindat415** [comment]
@stephanrotolante what version did you use?

**Comment by govindat415** [comment]
@stephanrotolante for aws-amplify and aws-amplify-react-native

**Comment by govindat415** [comment]
I was blacklisting 'amplify' in my metro config, but I thought it would only blacklist the amplify folder with my backend code, but it turns out it blacklisted everything with amplifying in it!
