### ISSUE TITLE
Update providers list in cognito typescript definition

### ISSUE THREAD

**Issue by Mighty683** [aws-amplify/amplify-js#5856]
**Is your feature request related to a problem? Please describe.**
Current definition of federated login providers:
```
export declare enum CognitoHostedUIIdentityProvider {
    Cognito = "COGNITO",
    Google = "Google",
    Facebook = "Facebook",
    Amazon = "LoginWithAmazon"
}
```

**Describe the solution you'd like**
There is also option to federated login with apple id and it's under key: `SignInWithApple`.
It's not provided in typescript definitions
```
// Example of usage from my application
import { Auth } from 'aws-amplify';
Auth.federatedSignIn({provider: 'SignInWithApple'})
```

**Comment by Mighty683** [comment]
https://github.com/Mighty683/amplify-js/pull/1

I created PR with fix

**Comment by amhinson** [comment]
There is already a PR out for this. I've requested a small change, but it hasn't been implemented yet. Feel free to make the change yourself and submit a PR. Thanks!
https://github.com/aws-amplify/amplify-js/pull/5402
