### ISSUE TITLE
InvalidSignatureException received when using multiple API endpoints with mixed service types

### ISSUE THREAD

**Issue by brandold** [aws-amplify/amplify-js#5858]
**Describe the bug**

I have 3 API endpoints declared in my awsconfig. 2 of them are API Gateway REST APIs with the service parameter defined as 'execute-api'. The remaining endpoint is an Elasticsearch REST API with the service parameter defined as 'es'.

The behavior I'm seeing is that there seems to be a top level service value in the API client object that is overriding the service value defined in a specific endpoint. From what I've observed, that top level value is set by whatever endpoint first invokes an API call. After that, the top level service key (regardless of what endpoint is called thereafter) persists until the DOM is reloaded. 

This behavior results in the sigv4 signature to get incorrectly created, e.g. instead of signing a request to API Gateway for service 'execute-api', the signature is created for 'es', leading to an Invalid Signature Exception and failed request.

**To Reproduce**

Create multiple API endpoints in your awsconfig with different service values, then try using the different endpoints.

**Expected behavior**

I expect the API client to pull in the service parameter value from the endpoint definition itself (why even have it otherwise?) rather than a top level key that is subject to manipulation from other endpoints. 

**Code Snippet**
Please provide a code snippet or a link to sample code of the issue you are experiencing to help us reproduce the issue. (Be sure to remove any sensitive data)

**Screenshots**

Valid signature for API gateway that I expect:

![Screen Shot 2020-05-21 at 2 38 02 PM](https://user-images.githubusercontent.com/46355297/82611352-299f3500-9b75-11ea-871d-c750dc7d5864.png)

Same endpoint, but incorrect signature due to the issue described:

![Screen Shot 2020-05-21 at 2 37 46 PM](https://user-images.githubusercontent.com/46355297/82611421-5ce1c400-9b75-11ea-9449-b455dcd0e495.png)

Here you can see the API client object and top level key I described:

![Screen Shot 2020-05-21 at 2 37 11 PM](https://user-images.githubusercontent.com/46355297/82611496-7edb4680-9b75-11ea-805c-a6f057c6bf15.png)

It's clear that the top level key is 'es' in this case and the endpoints are 'execute-api', yet the client uses the 'es' value and not whats defined in its endpoint configuration. 

Invalid Signature Exception:

![Screen Shot 2020-05-21 at 2 37 41 PM](https://user-images.githubusercontent.com/46355297/82611590-b813b680-9b75-11ea-8646-fa5042de5abf.png)

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.

We have a manual amplify configuration. 

* Which resources do you have configured?
  * If applicable, please provide your `aws-exports` file:
   ```
   const awsconfig = {
    Auth: {
      region: json.AWS_REGION,
      userPoolId: json.USER_POOL_ID,
      userPoolWebClientId: json.USER_POOL_CLIENT_ID,
      identityPoolId: json.IDENTITY_POOL_ID
    },
    Storage: {
      AWSS3: {
        bucket: json.DATAPLANE_BUCKET,
        region: json.AWS_REGION
      }
    },
    API: {
      endpoints: [
        {
          name: "contentAnalysisElasticsearch",
          endpoint: json.ELASTICSEARCH_ENDPOINT,
          service: "es",
          region: json.AWS_REGION
        },
        {
          name: "mieWorkflowApi",
          endpoint: json.WORKFLOW_API_ENDPOINT,
          service: "execute-api",
          region: json.AWS_REGION
        },
        {
          name: "mieDataplaneApi",
          endpoint: json.DATAPLANE_API_ENDPOINT,
          service: "execute-api",
          region: json.AWS_REGION
        }
      ]
    }
  };
   ```
**Additional context**

Initially we were on a quite old version of amplify, so my first troubleshooting step was to simply upgrade to the latest version. Unfortunately this did not solve the problem.

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by manueliglesias** [comment]
Hi @brandold 

Thank you for the report, I've identified the root cause, the RestClient is storing the service name and the region in instance variables:

https://github.com/aws-amplify/amplify-js/blob/3b2ec1b5704dde718649991aec42ffa25efe27cd/packages/api-rest/src/RestClient.ts#L302-L306

And later reading them:

https://github.com/aws-amplify/amplify-js/blob/3b2ec1b5704dde718649991aec42ffa25efe27cd/packages/api-rest/src/RestClient.ts#L326

This can cause problems in async flows. This  needs to be changed to not store them in instance variables.

I am labeling this as a bug

**Comment by brandold** [comment]
Hi @manueliglesias, thanks for the quick reply and confirmation of the bug! I'll keep an eye out for a bugfix.
