### ISSUE TITLE
Expo-Amplify project: aws-amplify-react-native broken using latest react-native-web 0.12.x

### ISSUE THREAD

**Issue by ikakara** [aws-amplify/amplify-js#5865]
When using react-native-web 0.12.x (expo) with aws-amplify-react-native, the following error occurs:
Module not found: Can't resolve 'react-native-web/dist/exports/ViewPropTypes'

See reason: https://github.com/necolas/react-native-web/releases/tag/0.12.0
Short answer: 0.12.x removed use of the prop types exports which have been deprecated in React Native.

Please update aws-amplify-react-native by discontinuing use of ViewPropTypes, and others that have been deprecated in React Native.

Sample code to reproduce the problem.
https://github.com/ikakara/expo-amplify-bug

**Comment by sammartinez** [comment]
Thank you for your feedback @ikakara. I am marking this as a feature request as we don't have a use case around react-native-web and the above ask on removing ViewPropTypes. We will evaluate this further internally. Thank you

**Comment by ikakara** [comment]
Sure.   Keep in mind that react-native-web is the underling mechanism of the Expo (React Native) framework for cross platform support across iOS, Android and Web.  And Expo is used a lot ,,, imho.

**Comment by amhinson** [comment]
@ikakara What version of `aws-amplify-react-native` are you using? I don't see any use of `propTypes` in the Amplify code currently. Could you also post more of the error you're seeing? Perhaps this error is coming from another library.

**Comment by Ashish-Nanda** [comment]
@ikakara looking at your example repo, the issue seems related to react-native-elements, which we depend on. You can create an issue on their library repo. 
Also we plan to remove this in the near future.

**Comment by ikakara** [comment]
I put (most) everything in the sample code: https://github.com/ikakara/expo-amplify-bug

Using "aws-amplify-react-native": "^4.1.2"

The complete error: 
Failed to compile D:/dev0/amplify-experiment/expo-amplify/node_modules/react-native-elements/src/config/ViewPropTypes.js Module not found: Can't resolve 'react-native-web/dist/exports/ViewPropTypes' in 'D:\dev0\amplify-experiment\expo-amplify\node_modules\react-native-elements\src\config'

The way I deduced it was an aws-amplify-react-native issue was by removing this line of code from App.js:

import { withAuthenticator } from 'aws-amplify-react-native'

That import causes the compile error (in the sample app).  I didn't dig deeper to see which imports that aws-amplify-react-native was using.

Thanks for investigating!

**Comment by ikakara** [comment]
Github is having some issues.  Anyway, I filed a bug with the react-native-elements repo: https://github.com/react-native-elements/react-native-elements/issues/2368

**Comment by Ashish-Nanda** [comment]
Thanks @ikakara 
Closing this issue as the bug was related to react-native-elements

**Comment by ikakara** [comment]
> Thanks @ikakara
> Closing this as the issue was related to react-native-elements

Ashish - https://github.com/react-native-elements/react-native-elements/issues/2368 - fixed this issue and deployed it in 2.0.1 has been released.  Can you update aws-amplify-react-native to import the latest release?
