### ISSUE TITLE
DataStore auth delay.

### ISSUE THREAD

**Issue by lenarmazitov** [aws-amplify/amplify-js#5866]
**Describe the bug**
Hello. I have bug with DataStore.query in the next moment after user have authorized. 
When I try to query through DataStore in the next moment after user have authorized then I get undefined, but if I wait a few seconds after auth then I successfully get data.

**To Reproduce**
Requirements: Amplify Auth, Graphql Schema with @auth directive, Data Store.
1. Perform authorization
2. Get cognito user through
```
  const cognitoUser = await Auth.currentAuthenticatedUser()
```
3. See that cognitoUser is presents
4. And right after getting user try to perform DataStore.query with any data belong to current authenticated user. This results to **undefined**
5. Now right after getting user try to wait 5 seconds, and then preform DataStore.query. This results to success.

**Expected behavior**
DataStore.query returns any data instantly after I have cognito user authorized

**Environment**
    "aws-amplify": "^3.0.11",
    "aws-amplify-react-native": "^4.1.2",
    "aws-appsync": "^3.0.3",
    "aws-appsync-react": "^3.0.3"

**Comment by manueliglesias** [comment]
Hi @lenarmazitov 

This will be addressed soon when DataStore notifies of its sync status. I'll be closing this issue in favor of https://github.com/aws-amplify/amplify-js/issues/4808, you can follow progress there
