### ISSUE TITLE
usernameAttributes not read in correctly in withAuthenticator Hook

### ISSUE THREAD

**Issue by jeyashankher** [aws-amplify/amplify-js#5871]
**Describe the bug**
While trying to implement custom SignIn UI using withAuthenticator HOC with email as username, the module still expects username instead of email.

**To Reproduce**
See Code samples below

**Expected behavior**
Sign In should go through with email and password. Instead, an error is shown that username is missing.

**Code Snippet**

```
export default withAuthenticator(
  App,
  false,
  [
    <CustomSignIn />,
    <ConfirmSignIn />,
    <VerifyContact />,
    <SignUp />,
    <ConfirmSignUp />,
    <ForgotPassword />,
    <RequireNewPassword />
  ],
  null,
  null,
  {
    usernameAttributes:'email',
    signUpConfig: {
      hiddenDefaults:['phone_number']
    }
  }
);
```

**Screenshots**

**What is Configured?**

**Smartphone (please complete the following information):**

- Browser [e.g. stock browser, safari]: Chrome

**Additional context**

Diagnosis:

In the above config, code goes into the else block:
https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Auth/index.tsx#L64

```
if (typeof includeGreetings === 'object' && includeGreetings !== null) {
  this.authConfig = Object.assign(this.authConfig, includeGreetings);
} else {
  this.authConfig = {
    includeGreetings,
    authenticatorComponents,
    federated,
    theme,
    signUpConfig,
  };
}
```

The entire configuration is copied into signUpConfig (including usernameAttributes)

So, when Authenticator is created, usernameAttributes is undefined. this.authConfig.usernameAttributes is undefined.

https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Auth/index.tsx#L114

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by jeyashankher** [comment]
I understand that a workaround exists. So, not a critical issue.

```
export default withAuthenticator(
  Home,
  {
    includeGreetings: false,
    usernameAttributes:'email',
    authenticatorComponents: [
      <CustomSignIn />,
      <ConfirmSignIn />,
      <VerifyContact />,
      <SignUp />,
      <ConfirmSignUp />,
      <ForgotPassword />,
      <RequireNewPassword />
    ],
    signUpConfig: {
      hiddenDefaults:['phone_number']
    }
  }
);
```

**Comment by amhinson** [comment]
Hey @jeyashankher, have you considered using the latest [`@aws-amplify/ui-react` library](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react)? It makes these kinds of customizations a bit simpler.

**Comment by jeyashankher** [comment]
I apologise for not responding earlier. I missed that documentation about the new ui-react library.

Is there documentation on customise the look and feel of the UI (including styling)?

**Comment by amhinson** [comment]
There is a [section](https://docs.amplify.aws/ui/customization/theming/q/framework/react) on customization via CSS Variables in the docs. Is that what you are looking for?
