### ISSUE TITLE
Communication error while executing a request to Elasticsearch.

### ISSUE THREAD

**Issue by dogsonacid** [aws-amplify/amplify-js#5879]
**Describe the bug**
We are getting intermittent errors from elasticsearch - query works most of the time and sometimes it returns:

```
 {
      "path": [
        "searchPostsCustom",
        "items",
        0,
        "likes"
      ],
      "data": null,
      "errorType": "Elasticsearch:RuntimeException",
      "errorInfo": null,
      "locations": [
        {
          "line": 46,
          "column": 13,
          "sourceName": null
        }
      ],
      "message": "Communication error while executing a request to Elasticsearch."
    }
```

I'm confident this is not a code or config issue as it is intermittent. Mostly the query works fine. Probably 1 out of 10 times it fails.

It seems it has started happening to us and others since the 

```
Service software release
R20200330-p1
```

This may or may not be the wrong place to post this but it's a critical bug that is effecting production environments 

**To Reproduce**

Create a custom ES resolver with sub fields which are also ES resolvers

**Expected behavior**
Search results to be returned with no errors

**Comment by morficus** [comment]
Here is an ongoing thread on the AWS support form about this as well.

https://forums.aws.amazon.com/thread.jspa?messageID=943553&tstart=0

**Comment by ashika01** [comment]
@dogsonacid I suggest you track the thread. I will bring up with the service team internally.

**Comment by dogsonacid** [comment]
thanks - we got developer support so i've sent in a ticket myself about a week ago but issue is still on going

**Comment by morficus** [comment]
has anyone heard anything on this?

**Comment by jpimentel-primeit** [comment]
We are also facing this issue since the day R20200330-p1 was released. We contacted aws support at 21/05 but we got no answer yet.
I really don’t know why there isn’t more people complaining about this problem as this issue has been around for almost two months now.

**Comment by morficus** [comment]
@ashika01  * ping * any updates on this? it's been 6 weeks and neither this issue nor the thread on the AWS Forum have been updated 😢

**Comment by ashika01** [comment]
The open ticket mentioned above in the forum is probably the best way to get info from the service team. I would suggest pinging there for info.

**Comment by LeoLiiiiiii** [comment]
Hi @morficus, if it is possible, can you try to reproduce it on your local again and share me that request ID? Cause I'm suspecting this is a known and fixed issue.
