### ISSUE TITLE
When using social federation login (Custom UI) calling the social federations with Expo

### ISSUE THREAD

**Issue by ARChatco** [aws-amplify/amplify-js#5884]
**Describe the bug**
It is always going ahead with the user you introduced.
I signOut with global true, but always getting the user I introduced at first time, never can introduce again a different user

**Comment by amhinson** [comment]
Hey @ARChatco, would you be able to provide a code sample as well a what version(s) of Amplify libraries you are using? Also, what JS framework is your app?
