### ISSUE TITLE
Federated Facebook login does not call Cognito Lambda triggers

### ISSUE THREAD

**Issue by joebernard** [aws-amplify/amplify-js#5885]
**Describe the bug**
When logging in with Facebook federated logins, Cognito Lambda triggers are not called depending on the state of the user.

**To Reproduce**

I start with a fresh Cognito with no users. I have a Pre Sign-up trigger and a Post Authentication trigger. When using a custom auth flow, both of these triggers are called properly. However when using a federated login flow the triggers are not called as expected.

Start with empty cognito, no users
Facebook federated login
pre sign-up trigger is called
post auth trigger is NOT called
cognito user record has been created
logout
Facebook login again
pre sign-up trigger is NOT called
post auth trigger is called

**Expected behavior**
Just as in a custom auth flow, both Pre and Post triggers should be called during a federated login.

**Code Snippet**

```javascript
Auth.federatedSignIn({provider: 'Facebook'});
```

**What is Configured?**
My backend is configured with Serverless, not Amplify CLI. This is my Amplify config:
```
Auth: {
        userPoolId: Config.COGNITO_USER_POOL_ID,
        region: Config.COGNITO_REGION,
        userPoolWebClientId: Config.COGNITO_USER_POOL_WEB_CLIENT_ID,
        identityPoolId: Config.COGNITO_IDENTITY_POOL_ID,
        authenticationFlowType: Config.COGNITO_AUTHENTICATION_FLOW_TYPE,
        oauth: {
          domain: Config.COGNITO_DOMAIN,
          scope: [
            'phone',
            'email',
            'profile',
            'openid',
            'aws.cognito.signin.user.admin',
          ],
          redirectSignIn: 'https://app.mydomain.com/signIn',
          redirectSignOut: 'https://app.mydomain.com/signOut',
          responseType: 'code',
        },
      },
```

<details>
  <summary><strong>Environment</strong></summary>

```
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 5.26 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.2.0 - ~/.nvm/versions/node/v14.2.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v14.2.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 76.0.1
    Safari: 13.1
  npmPackages:
    @aws-amplify/analytics: ^3.1.11 => 3.1.11 
    @aws-amplify/auth: ^3.2.8 => 3.2.8 
    @aws-amplify/cache: ^3.1.11 => 3.1.11 
    @aws-amplify/core: ^3.2.8 => 3.2.8 
    @aws-amplify/pushnotification: ^3.0.12 => 3.0.12 
    @aws-amplify/storage: ^3.2.1 => 3.2.1 
    @babel/core: ^7.6.2 => 7.9.0 
    @babel/runtime: ^7.6.2 => 7.9.2 
    @react-native-community/async-storage: ^1.10.1 => 1.10.1 
    @react-native-community/eslint-config: ^0.0.5 => 0.0.5 
    @react-native-community/masked-view: ^0.1.10 => 0.1.10 
    @react-native-community/netinfo: ^5.8.0 => 5.8.1 
    @react-native-community/picker: ^1.3.0 => 1.5.0 
    @react-native-community/push-notification-ios: 1.2.0 => 1.2.0 
    @types/react: 16.9.35 => 16.9.35 
    amazon-cognito-identity-js: ^4.3.0 => 4.3.0 
    apollo-cache: ^1.3.5 => 1.3.5 
    apollo-cache-inmemory: ^1.6.6 => 1.6.6 
    apollo-client: 2.6.10 => 2.6.10 
    apollo-link: ^1.2.14 => 1.2.14 
    apollo-link-http: ^1.5.17 => 1.5.17 
    apollo-utilities: ^1.3.4 => 1.3.4 
    aws-appsync: ^3.0.3 => 3.0.3 
    aws-appsync-auth-link: ^2.0.2 => 2.0.2 
    aws-appsync-react: ^3.0.3 => 3.0.3 
    aws-appsync-subscription-link: ^2.1.0 => 2.1.0 
    babel-jest: ^24.9.0 => 24.9.0 
    bugsnag-react-native: ^2.23.7 => 2.23.7 
    eslint: ^6.5.1 => 6.8.0 
    graphql: 15.0.0 => 15.0.0 
    graphql-tag: ^2.10.3 => 2.10.3 
    jest: ^24.9.0 => 24.9.0 
    lodash.clonedeep: ^4.5.0 => 4.5.0 
    lodash.debounce: ^4.0.8 => 4.0.8 
    lodash.flowright: ^3.5.0 => 3.5.0 
    lodash.uniqby: ^4.7.0 => 4.7.0 
    metro-react-native-babel-preset: ^0.58.0 => 0.58.0 
    moment: ^2.25.3 => 2.25.3 
    moment-timezone: ^0.5.28 => 0.5.28 
    native-base: ^2.13.12 => 2.13.12 
    prop-types: ^15.7.2 => 15.7.2 
    react: 16.11.0 => 16.11.0 
    react-apollo: ^3.1.5 => 3.1.5 
    react-dom: ^16.12.0 => 16.13.1 
    react-native: 0.62.2 => 0.62.2 
    react-native-animatable: ^1.3.3 => 1.3.3 
    react-native-camera: ^3.24.1 => 3.26.0 
    react-native-circular-progress: 1.3.6 => 1.3.6 
    react-native-config: 1.0.0 => 1.0.0 
    react-native-country-picker-modal: ^1.10.0 => 1.10.0 
    react-native-device-info: ^5.5.7 => 5.5.7 
    react-native-fast-image: ^8.1.5 => 8.1.5 
    react-native-fs: ^2.16.6 => 2.16.6 
    react-native-gesture-handler: ^1.6.1 => 1.6.1 
    react-native-haptic-feedback: ^1.9.0 => 1.10.0 
    react-native-orientation-locker: ^1.1.8 => 1.1.8 
    react-native-permissions: ^2.1.4 => 2.1.4 
    react-native-progress: ^4.1.2 => 4.1.2 
    react-native-reanimated: ^1.8.0 => 1.8.0 
    react-native-safe-area-context: ^1.0.0 => 1.0.0 
    react-native-safe-area-view: ^2.0.0 => 2.0.0 
    react-native-screens: ^2.7.0 => 2.7.0 
    react-native-share: 3.3.2 => 3.3.2 
    react-native-svg: ^12.1.0 => 12.1.0 
    react-native-svg-animated-linear-gradient: https://github.com/joebernard/react-native-svg-animated-linear-gradient.git => 0.3.4 
    react-native-tab-view: ^2.14.0 => 2.14.0 
    react-native-vector-icons: ^6.6.0 => 6.6.0 
    react-native-video: ^5.0.2 => 5.0.2 
    react-native-webview: 9.4.0 => 9.4.0 
    react-navigation: ^4.3.9 => 4.3.9 
    react-navigation-props-mapper: ^1.0.4 => 1.0.4 
    react-navigation-stack: ^2.4.0 => 2.5.0 
    react-navigation-tabs: ^2.8.13 => 2.8.13 
    react-test-renderer: 16.11.0 => 16.11.0 
    uuid: ^3.4.0 => 3.4.0 
  npmGlobalPackages:
    npm: 6.14.4
```

</details>

**Smartphone (please complete the following information):**

- Device: iPhone Xs Max
- OS: iOS 13.4.1

**Comment by joebernard** [comment]
Any update on this?

**Comment by amhinson** [comment]
@joebernard Could you share the value for `COGNITO_AUTHENTICATION_FLOW_TYPE`? Also, I'd recommend reaching out to AWS for Cognito support, since these triggers are called by the service itself and not the client-side libraries.

**Comment by joebernard** [comment]
I have posted in the AWS forums here:
https://forums.aws.amazon.com/thread.jspa?threadID=330020

```
Config.COGNITO_AUTHENTICATION_FLOW_TYPE === 'CUSTOM_AUTH'
```

**Comment by DavidGolodetsky** [comment]
I have the same issue. @joebernard did you get any response? Or maybe you found a workaround?

**Comment by joebernard** [comment]
@DavidGolodetsky No, I never received a response. It's a major blocker for us.

@amhinson Do you have any recommendations for promoting this issue beyond posting in the forums?

**Comment by DavidGolodetsky** [comment]
@joebernard are you using Hosted UI for Facebook login? I found out that you can use those triggers only with Hosted UI, (In my case PreSignUp and PostConfirmation) otherwise you would need to create your own triggers.

**Comment by christiankaindl** [comment]
We also face this issue: our Post Authentication lambda is not being triggered when the user did not exist in Cognito before. When the user signs out an then back in, the lambda is triggered. I also posted our side to the AWS forum post mentioned above.

@joebernard did you manage to solve the issue eventually?

@DavidGolodetsky Yes, we are using Hosted UI

**Comment by joebernard** [comment]
We had to abandon Facebook login due to this issue. It was a hard choice but the only way we could move forward.

**Comment by kgoyal98** [comment]
@calebpollman @vyomr13 Can you please help here?

**Comment by chrisbonifacio** [comment]
Hello everyone 👋 The requirements for federation to invoke a Cognito trigger are detailed in this related issue on the CLI repo: https://github.com/aws-amplify/amplify-cli/issues/9751#issuecomment-1138011256

[Cognito documentation on federation and triggers](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html#important-lambda-considerations)

For those implementing their own custom auth flow, please note that the documentation mentions:

>Federated sign-in does not invoke any [Custom authentication challenge Lambda triggers](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-challenge.html), [Migrate user Lambda trigger](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-migrate-user.html), [Custom message Lambda trigger](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-message.html), or [Custom sender Lambda triggers](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-sender-triggers.html) in your user pool.

And, as others have mentioned here before:

>Federated users must use the Amazon Cognito hosted UI to sign in.

>For some actions, federated users invoke more than one Lambda function.

**Comment by kgoyal98** [comment]
@chrisbonifacio But [here](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html#important-lambda-considerations) it is written that the Triggering event of Post confirmation lambda is "A federated user signs in from the Amazon Cognito hosted UI sign-in page for the first time."

**Comment by elorzafe** [comment]
> @chrisbonifacio But [here](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html#important-lambda-considerations) it is written that the Triggering event of Post confirmation lambda is "A federated user signs in from the Amazon Cognito hosted UI sign-in page for the first time."

That is correct, only the first time. If that user already exists on the UserPool then it will invoke Pre and Post Authentication lambda trigger.

If you those resources exported in some format (CDK, Cloudformation or Amplify project) I am more than happy to try it out.

**Comment by saxjonas** [comment]
Want to confirm that this is also the case when using Facebook Login using the Amplify UI Authenticator components. I'm trying to use the pre sign-up triggers. Seeing as the Amplify UI is supposed to be "out-of-the-box" functionality, feels like it should have support for using triggers.

**Comment by nathanagez** [comment]
> Want to confirm that this is also the case when using Facebook Login using the Amplify UI Authenticator components. I'm trying to use the pre sign-up triggers. Seeing as the Amplify UI is supposed to be "out-of-the-box" functionality, feels like it should have support for using triggers.

I have the exact same issue using Amplify UI Authenticator component.

**Comment by nadetastic** [comment]
Hi @saxjonas @nathanagez 

Since Amplify Auth uses Cognito under the hood, the experience details at [1] is what will occur. The behavior described by the original issue above is what what is expected.

In short, new users that haven't signed into your userpool via Facebook (or other Social providers) will trigger on these two lambda functions:
- Pre sign-up 
- Post confirmation

Returning users, will trigger these functions
- Pre authentication
- Post authentication

**Comment by nadetastic** [comment]
@saxjonas @nathanagez following up here - let me know if you have any questions, otherwise I'll close out this issue 😀
