### ISSUE TITLE
Clarification about the MFA code in Auth.signUp

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#5888]
Can anyone clarify these? It could be great helpful for me. Thanks in advance.

My questions are related to MFA.

1. I have set the MFA settings as optional. Here some users received code while signUp and some users not received code while signUp.
(Note: If I set the optional does it behaves like this as [1] point. Any documentation for this) (I have enabled MFA manually for those users who not received the code)

2. I have found this in one github issue MFA is set to Optional; this is to later support the ability to trigger MFA if the user is coming from a new device.

3. How can I check or know the user received the confirmation code while signUp using aws-amplify-react-native?

4. If the confirmation code is not received how the user will proceed signUp (i.e) any option to trigger the MFA for that user via our Auth.signUp

**Comment by aoloo** [comment]
@nihp  for your last quest on `If the confirmation code is not received how the user will proceed signUp (i.e) any option to trigger the MFA for that user via our Auth.signUp`. You use `Auth.resendSignUp()` for that usecase. Here is documentation [resendSignUp](https://aws-amplify.github.io/amplify-js/api/classes/authclass.html#resendsignup)
