### ISSUE TITLE
api.put() overwrites item and does not update single attribute

### ISSUE THREAD

**Issue by kannieWeesNie** [aws-amplify/amplify-js#5889]
using amplify rest api
trying to update an existing item attribute
partition key is "phone", using following code as per documentation:

`const apiName = "myrestapi";
      const path = "/items";
      const myInit = {
         body: {
          phone: 3,
          email: "hello@here.com"//only want to update email and not overwrite all attributes
        } 
      };

      return await API.put(apiName, path, myInit);`

**Expected behavior**
expected to only change the email address attribute of existing item identified by phone = 3

instead result was that all the attributes of the existing item were overwritten

what do i need to do to update the item attribute only (given attribute) and not overwrite all the attributes?

thanks

**Comment by cedricgrothues** [comment]
@kannieWeesNie Could you provide us with steps to reproduce the issue?
