### ISSUE TITLE
Vue authentication module show loading during pre signup lambda

### ISSUE THREAD

**Issue by 24jr** [aws-amplify/amplify-js#5894]
When using the vue aws amplify authentication module I have a post sign up lambda function that adds a user to an "everyone" group. The thing is after the verification code is sent the screen just sits there for like 10 seconds with no indication of anything and the button is still enabled to keep clicking "confirm" so its pretty confusing. 

Ideally it doesn't take 10 seconds or so to add the user to the group but hey if it is it is but I think a loading indicator could still be added to mitigate any confusion upon sign up

**Comment by amhinson** [comment]
@24jr Are you still seeing the behavior here? If so, what version of the Amplify libraries are you using? And can you provide a code snippet?
