### ISSUE TITLE
withOAuth cannot SSO using facebook App in react-native

### ISSUE THREAD

**Issue by darshannahar** [aws-amplify/amplify-js#5897]
**Describe the bug**
withOAuth opens  web browser with hosted  UI. Hence, it  cannot  SSO with facebook app installed on the same mobile. This is a  problem for native apps and react-native apps. Despite of  having an authentication session in facebook app, customer have to enter their credentials again.
On the other hand if we  use facebook sdk, SSO works fine. But then we cannot integrate with UserPool to create a user and map the attributes.

**To Reproduce**
amplify add auth
select "Default configuration with Social Provider (Federation)" and use Facebook as IdP.

**Expected behavior**
Native apps should SSO with facebook app.

**Comment by tannerabread** [comment]
Hi 👋 Closing this as resolved. This package is now deprecated. We recommend that you migrate to the new amplify UI library.

Thank you!
