### ISSUE TITLE
Pinpoint users endpoints disappearing occasionally

### ISSUE THREAD

**Issue by tombaumg** [aws-amplify/amplify-js#5899]
**Hey all,**

I'm updating an endpoint in aws Analytics and successfully getting the emails notifications from Pinpoint.sendUsersMessages.

**But something between 30-60 minutes after the subscription (the updateEndpoint) - this stops working and I get a response says that this user does not have any endpoints, like the endpoint was just removed somehow.**

While investigating this, I even tried to "getUserEndpoints" for the debugging. I got a full described endpoint right after the subscription, but a while after that - when it stopped working - I got no endpoints for this user.

**To Reproduce**
Described above

**Expected behavior**
No endpoint disappearing

**Code Snippet**
The updateEndpoint:

```
export const initPinpoint = (username, email) => {
  Analytics.configure(config)

  Analytics.updateEndpoint({
    address: email,
    userId: username,
    channelType: 'EMAIL',
    optOut: 'NONE',
    userAttributes: {
      type: ['something']
    }
  }).then(console.log).catch(console.error)
}
```

The sendUsersMessages:
```
  const sendMessagesParams = {
    ApplicationId: process.env.ANALYTICS_YYY_ID,
    SendUsersMessageRequest: {
      MessageConfiguration: {
        EmailMessage: {
          SimpleEmail: {
            HtmlPart: {
              Charset: 'UTF-8',
              Data: messageReceivedEmail(name1, name2, message)
            },
            Subject: {
              Charset: 'UTF-8',
              Data: `You have a new message from ${name2}`
            }
          }
        }
      },
      Users: {
        [destination]: {}
      }
    }
  }

  await pinpoint
    .sendUsersMessages(sendMessagesParams)
    .promise()
    .then((data, error) => {
      if (data) {
        console.log('Result:', util.inspect(data, false, null))
      }
      if (error) {
        console.log('Error', util.inspect(error, false, null))
      }
    })
}
```

This is how my endpoint looks when its working:
```
ENPOINTS DATA:  {
  EndpointsResponse: {
    Item: [
      {
        Address: 'bla+123@gmail.com',
        ApplicationId: 'XXXX-XXXX-XXXX-XXXX',
        Attributes: {},
        ChannelType: 'EMAIL',
        CohortId: 'XX',
        CreationDate: '2020-05-25T12:22:31.055Z',
        Demographic: {
          AppVersion: 'Chrome/81.0.4044.138',
          Make: 'Gecko',
          Model: 'Chrome',
          ModelVersion: '81.0.4044.138',
          Platform: 'macintel'
        },
        EffectiveDate: '2020-05-26T11:34:09.417Z',
        EndpointStatus: 'ACTIVE',
        Id: 'YYYY-YYYY-YYYY-YYYY',
        Location: {},
        Metrics: {},
        OptOut: 'NONE',
        RequestId: 'ZZZZ-ZZZZ-ZZZZ-ZZZZ',
        User: {
          UserAttributes: { type: [ 'something' ] },
          UserId: 'AAAA-AAAA-AAAA-AAAA'
        }
      }
    ]
  }
}```

Here's when it's not:

[Resource Not Found](https://user-images.githubusercontent.com/63183428/82899257-567f8d80-9f63-11ea-8335-062e0f4ed64c.png)
[No endpoints found](https://user-images.githubusercontent.com/63183428/82899264-5a131480-9f63-11ea-9434-3e09f4d15201.png
)

**Comment by sammartinez** [comment]
@tombaumg Are you still looking for support for this issue? Please let us know.

**Comment by ahtokca** [comment]
I have the same issue. I don't see anything in cloudaudit :( Is there any way to trace delete endpoint?

**Comment by ahtokca** [comment]
Any news? it is pretty reproducible. 
1. react-native run-ios --device -> no endpoint found, however Analytics.updateEndpoint is called without errors
2. close and open the app -> endpoint found
3. press 'r' to reload the app in metro console -> endpoint is gone
4. close and open the app -> endpoint found

How can I see/debug it further? what do I need to check?

**Comment by ahtokca** [comment]
https://github.com/aws-amplify/amplify-js/blob/df95ea3724eb6406f64b03f25086cd3e8644cb5f/packages/analytics/src/Providers/AWSPinpointProvider.ts 

```javascript
user: {
    userId:
	    event.userId ||
	    defaultEndpointConfig.userId ||
	    credentials.identityId,
    userAttributes: {
	    ...defaultEndpointConfig.userAttributes,
	    ...event.userAttributes,
    },
}
```
I use custom userId, so basically internally it updates endpoint to credentials.identityId and screws my link to user. Any ideas how can configure it in way it does break the link?

**Comment by ahtokca** [comment]
To disable auto updateEndpoint I found this 

```
Amplify.configure({
  ...awsConfiguration,
  Analytics: {
    // OPTIONAL - Allow recording session events. Default is true.
    autoSessionRecord: false,
  },
});
```

**Comment by jacdx** [comment]
This is still an issue with latest. My custom `userId`'s are getting overwritten with `region:identityId`, which is quite maddening, causing endpoints to sometimes disappear
