### ISSUE TITLE
Utilize generic type feature of GraphQLResult in api-graphql pacakge 

### ISSUE THREAD

**Issue by FilipPyrek** [aws-amplify/amplify-js#5902]
**Is your feature request related to a problem? Please describe.**
If I call GraphQL API for example this way:
```typescript
import { API, graphqlOperation } from 'aws-amplify'

const response = await API.graphql(graphqlOperation(query, variables))
```
`response` is always of type [`GraphQLResult<object>`](https://github.com/aws-amplify/amplify-js/blob/master/packages/api/src/API.ts#L176). And then I need to either force the type myself
```typescript
response as { data: FooResult }
```
or create a [User-Defined Type Guard](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards)

**Describe the solution you'd like**
I can see that [`GraphQLResult<T = object>` is a generic type](https://github.com/aws-amplify/amplify-js/blob/master/packages/api-graphql/src/types/index.ts#L29). So it would be nice if I could call the API for example like this:
```typescript
import { GraphQLResult } from '@aws-amplify/api'
import { API, graphqlOperation } from 'aws-amplify'

const response: GraphQLResult<FooResult> = await API.graphql<FooResult>(graphqlOperation(query, variables))
```

That way we can really utilize the feature of `GraphQLResult` being a generic type.

**Describe alternatives you've considered**
Forcing the type or using [User-Defined Type Guard](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards)

**Comment by chrisbonifacio** [comment]
Closing this as the result of graphql queries are now type-safe and mapped to the model being operated on.

See this example using Amplify Gen 2's `client.models` API:

![Image](https://github.com/aws-amplify/amplify-js/assets/16952986/ccd82290-42b8-486a-8e79-1e516ce88ec5)

In Gen 1, type helpers such as `GraphQLQuery<T>` were also added:

```ts
import { API } from 'aws-amplify';
import * as queries from './graphql/queries';
import { GraphQLQuery } from '@aws-amplify/api';
import { ListTodosQuery, GetTodoQuery } from './API';

// Simple query
const allTodos = await API.graphql<GraphQLQuery<ListTodosQuery>>({
  query: queries.listTodos
});
console.log(allTodos); // result: { "data": { "listTodos": { "items": [/* ..... */] } } }

// Fetch a single record by its identifier
const oneTodo = await API.graphql<GraphQLQuery<GetTodoQuery>>({
  query: queries.getTodo,
  variables: { id: 'some id' }
});
```

Please refer to our documentation for more info:
https://docs.amplify.aws/gen1/react/prev/build-a-backend/graphqlapi/query-data/
