### ISSUE TITLE
AppSync subscription not working becaouse of timeout disconnect

### ISSUE THREAD

**Issue by damianrr** [aws-amplify/amplify-js#5914]
Hello,

I've a GraphQL subscription, in AppSync, which has worked perfectly for almost a year, however, now it has starting to fail due to "Timeout Disconnect" errors, it doesn't happen all the time, but when it times out then live update don't work until I refresh the browser, which is unacceptable for the business domain. In terms of debugging down it feels like a dead end for me.
Does anyone know how I can either continue to track this down or (even better!!) a solution for it? Any help will be most appreciated.

PD: Here's a dump of the error that I'm getting in the browser.

```
{
   "provider":{
      "_config":{
         "aws_project_region":"us-east-1",
         "aws_cognito_region":"us-east-1",
         "aws_user_pools_id":"us-east-1_XXXXX",
         "aws_user_pools_web_client_id":"XXXXXXX",
         "oauth":{

         },
         "aws_appsync_graphqlEndpoint":"https://XXXXXXX.appsync-api.us-east-1.amazonaws.com/graphql",
         "aws_appsync_region":"us-east-1",
         "aws_appsync_authenticationType":"AMAZON_COGNITO_USER_POOLS",
         "aws_appsync_apiKey":"XXXXXXX",
         "aws_mobile_analytics_app_id":"XXXXXXXX",
         "aws_mobile_analytics_app_region":"us-east-1"
      },
      "socketStatus":0,
      "keepAliveTimeout":300000,
      "subscriptionObserverMap":[

      ],
      "promiseArray":[

      ],
      "awsRealTimeSocket":null,
      "keepAliveTimeoutId":1127
   },
   "error":{
      "errors":[
         {
            "message":"Timeout disconnect"
         }
      ]
   }
}"\""
```

**Comment by damianrr** [comment]
In the above log there's a `keepAliveTimeout` and a `keepAliveTimeoutId`. Is there a way I can control that and set it to something like: "Never Expire"?

Thanks.

**Comment by watanabethais** [comment]
@damianrr Have you found a workaround for this?

I'm having the same issue. After 5 minutes, it gives me the "Connection closed" error and I need to refresh the browser.
The AppSync subscriptions wasn't suppose to be real time?

**Comment by damianrr** [comment]
Hey @watanabethais, 

I did not. I actually moved away from Amplify / AppSync. 

Sorry.
