### ISSUE TITLE
How to update user password in Cognito user pool without old password?

### ISSUE THREAD

**Issue by navane** [aws-amplify/amplify-js#5915]
Hi,

We have multistep register form where user can set their password in step 2. 
So, we will setting random password during step 1 and registering user details in Cognito user pool.
But end user submitting actual password from step 2.
Cognito will not update password (from step 2) without sending old password (random generated from step1). Cognito considers this process will be password update.

So how we need to handle this situation? or Is there any option / tricks which amplify provides to overcome this case?

**Comment by amhinson** [comment]
@navane That functionality isn't currently possible with Amplify in the way you're describing during registration. Were you able to find a solution to fit your use-case? There is also the `forgotPassword` method to reset the password without the old password, but that might not be exactly what you're looking for: https://docs.amplify.aws/lib/auth/manageusers/q/platform/js#forgot-password
