### ISSUE TITLE
Cognito User inconsistently returns new IdToken on credentials refresh

### ISSUE THREAD

**Issue by munroTom** [aws-amplify/amplify-js#5917]
**Describe the bug**
When calling CognitoUser().getSession when the users access token is invalid it sometimes returns the same id token, sometimes a new one

**To Reproduce**

1. Call CognitoUser.getSession on a user with an invalid access token but valid id + refresh tokens
2. Compare authentication result id token with original
3. Repeat
4. Sometimes a new id token has issued

**Expected behavior**
Consistently return the same result, either a new Id token or the original one. I guess a new token 

**Code Snippet**

```js
  const session = new CognitoUserSession({
    AccessToken // invalid,
    IdToken,
    RefreshToken
  });

  const user = new CognitoUser({
    Pool,
    Username
  });

 user.setSignInUserSession(session)

user.getSession()
```

**Screenshots**

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
- "amazon-cognito-identity-js": "^4.2.4"

**Comment by sammartinez** [comment]
Resolving as the linked issue has the solution to this issue.
