### ISSUE TITLE
filter and limit not applied properly

### ISSUE THREAD

**Issue by pseudyx** [aws-amplify/amplify-js#5920]
**Describe the bug**
a given DynamoDB table has 200 items on it.
When applying a GraphQL query (on posts) with a filter (category =) and a limit (10).
Only 4 results are returned.

**To Reproduce**
as above.

**Expected behavior**
filter should be applied before limit. not the current get limit then filter.

**Code Snippet**
const resp = await API.graphql({
            query: queries.listPosts,
            variables:{
                filter:{ 
                    categoryID: {
                        eq: categoryId
                    } 
                },
                limit: 10
            },
            authMode: 'API_KEY'
        });

**What is Configured?**
GraphQL with API_KEY auth
graph models: Categories -> Posts -> comments 

**Additional context**
query to list items with filter, should apply filter first, then return limit.
current function queries for limit then returns filtered.

**Comment by ashika01** [comment]
Looks like this is what you are asking for as well - https://github.com/aws-amplify/amplify-js/issues/5299

**Comment by ashika01** [comment]
Also, gonna reference this here - https://github.com/aws-amplify/amplify-cli/issues/1865

This is FR with CLI that discusses use-cases and limitations. Also possible workaround based on situation.
