### ISSUE TITLE
CognitoIdentityCredentials is not authorized to perform: apigateway:GET on resource: arn:aws:apigateway:eu-west-1::/restapis

### ISSUE THREAD

**Issue by Afrogoth** [aws-amplify/amplify-js#5924]
Can someone please assist in pointing out what the issue might be when I try to access AWS apigateway resources using AWS Amplify Javascript SDK.

When a user logs into the platform (a portal I'm building)- the role assumed by the AuthRole is able to load the API catalogue as per the permissions to allow read access for all apigateway resources. Here is how the policy looks like:

```
 "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "appsync:*",
                "apigateway:GET",
                "apigateway:POST",
                "apigateway:DELETE",
                "apigateway:PATCH",
                "apigateway:PUT",
                "cloudformation:CreateStack",
                "cloudformation:CreateStackSet",
                "cloudformation:DeleteStack",
                "cloudformation:DeleteStackSet",
                "cloudformation:DescribeStackEvents",
                "cloudformation:DescribeStackResource",
                "cloudformation:DescribeStackResources",
                "cloudformation:DescribeStackSet",
                "cloudformation:DescribeStackSetOperation",
                "cloudformation:DescribeStacks",
                "cloudformation:UpdateStack",
                "cloudformation:UpdateStackSet",
                "cloudfront:CreateCloudFrontOriginAccessIdentity",
                "cloudfront:CreateDistribution",
                "cloudfront:DeleteCloudFrontOriginAccessIdentity",
                "cloudfront:DeleteDistribution",
                "cloudfront:GetCloudFrontOriginAccessIdentity",
                "cloudfront:GetCloudFrontOriginAccessIdentityConfig",
                "cloudfront:GetDistribution",
                "cloudfront:GetDistributionConfig",
                "cloudfront:TagResource",
                "cloudfront:UntagResource",
                "cloudfront:UpdateCloudFrontOriginAccessIdentity",
                "cloudfront:UpdateDistribution",
                "cognito-identity:CreateIdentityPool",
                "cognito-identity:DeleteIdentityPool",
                "cognito-identity:DescribeIdentity",
                "cognito-identity:DescribeIdentityPool",
                "cognito-identity:SetIdentityPoolRoles",
                "cognito-identity:UpdateIdentityPool",
                "cognito-idp:CreateUserPool",
                "cognito-idp:CreateUserPoolClient",
                "cognito-idp:DeleteUserPool",
                "cognito-idp:DeleteUserPoolClient",
                "cognito-idp:DescribeUserPool",
                "cognito-idp:UpdateUserPool",
                "cognito-idp:UpdateUserPoolClient",
                "dynamodb:CreateTable",
                "dynamodb:DeleteItem",
                "dynamodb:DeleteTable",
                "dynamodb:DescribeTable",
                "dynamodb:PutItem",
                "dynamodb:UpdateItem",
                "dynamodb:UpdateTable",
                "iam:CreateRole",
                "iam:DeleteRole",
                "iam:DeleteRolePolicy",
                "iam:GetRole",
                "iam:GetUser",
                "iam:PassRole",
                "iam:PutRolePolicy",
                "iam:UpdateRole",
                "lambda:AddPermission",
                "lambda:CreateFunction",
                "lambda:DeleteFunction",
                "lambda:GetFunction",
                "lambda:GetFunctionConfiguration",
                "lambda:InvokeAsync",
                "lambda:InvokeFunction",
                "lambda:RemovePermission",
                "lambda:UpdateFunctionCode",
                "lambda:UpdateFunctionConfiguration",
                "s3:*",
                "amplify:*"
            ],
            "Resource": "*"
        }
    ]
}
```
The above policy is associated with the authRole (role when user is authenticated) and is working as expected along with the below code:

```js
public async configureAwsIdentityCredentials(): Promise<boolean> {
    const sessionUser = await Auth.currentAuthenticatedUser();

    const idToken = sessionUser.signInUserSession.idToken.jwtToken;
    const cognitoParams = {IdentityPoolId: environment.appClient.identityPoolId, Logins: {}};

    cognitoParams.Logins[environment.cognitoIdpUrl + environment.appClient.userPoolId] = idToken;
    AWS.config.credentials = new AWS.CognitoIdentityCredentials(cognitoParams);

    return of(true).toPromise();

  }
```

The issue comes in when I need to pull the resources from AWS without an unauthenticated user- I have enabled unauthenticated access on the Identity Pool and attached the above policy to the unauthRole. I am receiving an instance of AWS.ICredentials when running the below code... although when I run the application, I receive an access denied error... below is the snippet for unauthenticated access:

```js
public async configureCurrentCreditialsWithoutLogin(): Promise<boolean> {
    const credentials = await Auth.currentCredentials();

    AWS.config.credentials = credentials;

    return of(true).toPromise();

  }
```

Herewith the textContent for the console error on the image:

ERROR Error: "Uncaught (in promise): AccessDeniedException: User: arn:aws:sts::XXXX:assumed-role/amplify-XXXX-unauthRole/CognitoIdentityCredentials is not authorized to perform: apigateway:GET on resource: arn:aws:apigateway:eu-west-1::/restapis

![image](https://user-images.githubusercontent.com/291056/83056379-96bf3880-a055-11ea-9256-5f9a826cb9a0.png)

**Comment by ashika01** [comment]
@Afrogoth : Where does amplify come in play? Could you provide us with sample code that could help us reproduce your issue?

**Comment by Afrogoth** [comment]
@ashika01 - I am using amplify Auth for the authentication within an Angular 8x application... although in order to access other parts of the AWS SDK I use the above code to authenticate the user (update AWS.config.credentials)… it works just fine for an authenticated user although when a user is not authenticated, I receive a CognitoCredentials object and pass that in as AWS.config.credentials. This results in the error specified for this query (cant execute a GET on AWS resources)… I don't have sample code although we could arrange for you to view the code with me... The identityPool is configured correctly as far as I can see (allows for guest users and the unauthrole has the correct policy attached to it) …

**Comment by Afrogoth** [comment]
@ashika01 - I have added the question to stackoverflow and have added Cloudtrail logs to the post. Please see: [](https://stackoverflow.com/questions/62037997/cognitoidentitycredentials-is-not-authorized-to-perform-apigatewayget-on-resou)

**Comment by hackrx** [comment]
@Afrogoth are you able to solve this issue? I am also facing the same issue.
I added one more path to the rest api by following this command: 
```
 amplify update api
? Select from one of the below-mentioned services: REST
? Please select the REST API you would want to update myrestapi
? What would you like to do Update path
? Please select the path you would want to edit /checkifuserexists
? Provide a path (e.g., /book/{isbn}): /checkifuserexists
? Choose a Lambda source Use a Lambda function already added in the current Amplify project
? Choose the Lambda function to invoke by this path checkUsername
? Restrict API access Yes
? Who should have access? Authenticated users only
? What kind of access do you want for Authenticated users? create, read
Successfully updated resource
```
before that for the first time I only created single restapi named as `checkUsername` with path `/checkusername`. It works fine, I can do a query from front-end, but if I am adding another path to it let's say `/checkifuserexists` then it is giving not authorized to perform an error. 
Thanks.

**Comment by ashika01** [comment]
@Afrogoth Apologies for not getting on this. I was on break with Amplify for a while. I would like to reproduce the issue if it is still an issue.

@hackrx did you have the rest api was working the first time but not after the updating the backend resource I would check with aws-amplify/cli team first.

**Comment by hackrx** [comment]
@ashika01 I will let you know soon!. I was outside for a few days. 
Will update my observations here.
Thanks for the follow-up.

**Comment by Afrogoth** [comment]
@ashika01 thanks for the feedback. We have since discontinued using Amplify.
The issue is easy to replicate...
Create an Amplify project and enable unauthenticated access and then expose a resource by assigning the role to a policy.
At first we thought that it was because we enabled the feature via the Ui although we had initially pushed and created the Amplify project using cli toolchain. We have since tried to update using the toolchain although the same result.

**Comment by nadetastic** [comment]
Hi @hackrx following up on this issue, as it has been a while. cc @Afrogoth

One thing to note when enabling access for API, is access configuration needs to be done twice - once on the Auth resource and another on the API resource.

- For Auth, you would do so by running `amplify add/update auth` and then setting allow or deny Guest access based on your needs.

- For API, you would go through `amplify add/update api`, select the API resource and at the step for restricting access select either `Authenticated users` or `Authenticated and Guest users`.

Below is an example that gives both auth and guest users full access to the API when running `amplify add/update api`

![API Example](https://user-images.githubusercontent.com/87148442/219105642-aa1c710c-ba1c-448e-b274-eae2746e8c3c.png)
