### ISSUE TITLE
Datastore.observe update is called twice in a row

### ISSUE THREAD

**Issue by nubpro** [aws-amplify/amplify-js#5940]
**Describe the bug**
In my app.js
```
useEffect(() => {
    const sub_config = DataStore.observe(Config).subscribe(
      ({ element, opType }) => {
        console.log('Config Sync', opType);
        console.log(element);
      },
    );

    return () => {
      sub_config.unsubscribe();
    };
  }, []);
```

Then I insert a new record into the Config table.
The subscription would observe 3 changes, as follow.

1. Optype is INSERT
`{"KDSCancelMsg": "XX", "_deleted": undefined, "_lastChangedAt": undefined, "_version": undefined, "id": "62e202b2-24b4-40a4-9fe1-dfbafa33b5be"}`

2. Optype is UPDATE
`{"KDSCancelMsg": "XX", "_deleted": null, "_lastChangedAt": 1590764564221, "_version": 1, "id": "62e202b2-24b4-40a4-9fe1-dfbafa33b5be"}`

3. Option is also UPDATE
`{"KDSCancelMsg": "XX", "_deleted": null, "_lastChangedAt": 1590764564221, "_version": 1, "id": "62e202b2-24b4-40a4-9fe1-dfbafa33b5be"}`

**Expected behavior**
I don't understand why UPDATE is called twice in a row, why is that?
The records are exactly the same. What more can I do to debug this issue?

**Comment by manueliglesias** [comment]
Hi @nubpro, this is expected behavior, you are seeing events that are happening throughout the item's journey to get synced to AppSync and also on its way back via a real time notification (the graphql subscription):

1. INSERT with no version: This is the event generated when the item is first created and persisted locally
2. UPDATE with version 1: This is from the response of the GraphQL mutation to send the item to the backend
3. UPDATE with version 1: This is from the message received via the GraphQL subscription

Is this causing trouble for you? You can probably inspect the `_version` field and ignore messages you don't care about

**Comment by nubpro** [comment]
> Hi @nubpro, this is expected behavior, you are seeing events that are happening throughout the item's journey to get synced to AppSync and also on its way back via a real time notification (the graphql subscription):
> 
> 1. INSERT with no version: This is the event generated when the item is first created and persisted locally
> 2. UPDATE with version 1: This is from the response of the GraphQL mutation to send the item to the backend
> 3. UPDATE with version 1: This is from the message received via the GraphQL subscription
> 
> Is this causing trouble for you? You can probably inspect the `_version` field and ignore messages you don't care about

On Stage 2, it's not safe to assume that the data is updated yet in DynamoDB, correct?
DynamoDB is only updated in Stage 3.

---
Is this the lifecycle for update?
1. Data is updated locally.
2. Send to DB
3. DB received update.

Here comes the issue, when I update an item through Datastore, I got Stage 1. But it would never progress to 2 and 3. The client just never syncs with the backend and I believe a couple of us is facing this issue as well. https://github.com/aws-amplify/amplify-js/issues/5926

Its difficult to reproduce this bug for a few reasons:
1. It's not consistent, pretty random but it happens to our client and our team.
2. There's no errors, whatsoever.
3. We don't know the tools to debug this issue.

**Comment by nubpro** [comment]
yarn list v1.22.4

```
├─ @aws-amplify/analytics@3.1.9
├─ @aws-amplify/api-graphql@1.0.11
├─ @aws-amplify/api-rest@1.0.11
├─ @aws-amplify/api@3.1.9
├─ @aws-amplify/auth@3.2.6
├─ @aws-amplify/cache@3.1.9
├─ @aws-amplify/core@3.2.6
├─ @aws-amplify/datastore@2.0.10
├─ @aws-amplify/interactions@3.1.9
├─ @aws-amplify/predictions@3.1.9
├─ @aws-amplify/pubsub@3.0.10
├─ @aws-amplify/storage@3.1.9
├─ @aws-amplify/ui@2.0.2
```

**Comment by ashika01** [comment]
@nubpro Do we need to keep this issue open? I know the sync at start is being tracked here https://github.com/aws-amplify/amplify-js/issues/5926 right?

**Comment by nubpro** [comment]
I will close this until I have more information about my issue to open a ticket. Thanks!

**Comment by hocnx** [comment]
I had the same problem.
I have an update function  inside of the event listener.
2 fires of UPDATE with the same content cause double execution.Any suggestions to separate this 2 UPDATE?


> 1. INSERT with no version: This is the event generated when the item is first created and persisted locally
> 2. UPDATE with version 1: This is from the response of the GraphQL mutation to send the item to the backend
> 3. UPDATE with version 1: This is from the message received via the GraphQL subscription

**Comment by reberthkss** [comment]
@hocnx did you found a workaround for it?

**Comment by hpwtaee** [comment]
If it's of any help at all I wrote a custom hook that uses a simple "identifier" ref to keep track of each event fired from the listener.

Since my problem was that for each post update (and on initial load), the listener would fire TWICE (First fire fetched old posts (before mutation), Second fire fetched new posts) my fetch function now only updates state on the second fire by comparing the "element" key in the event argument and determining if there's been a "_version" change.

Hope this makes sense and is useful.

```javascript
export const usePosts = (subscribe) => {
  const [posts, setPosts] = useState([]);
  const [status, setStatus] = useState({ isLoading: false, error: null });
  const identifier = useRef({ id: "0", version: null });

  useEffect(() => {
    fetchPosts();
    const subscription = subscribe ? DataStore.observe(Post).subscribe(fetchPosts) : null;
    return () => subscribe ? subscription.unsubscribe()
  }, []);
  
  const fetchPosts = async (event) => {
    setStatus({ ...status, isLoading: true });
    const element = event?.element;
    const ident = {
      id: !!element ? element.id : "0",
      version: !!element ? element._version : "0",
    }
    try {
      let data = await DataStore.query(Post, Predicates.ALL);
      const condition1 = identifier.current.id === ident.id; // if true, this is the second fire.
      const condition2 = identifier.current.version !== ident.version // if true, versions are different ie. new data.
      if (condition1 && condition2) setPosts(data);
      identifier.current = ident; // update ref to most recent event.
    } catch (e) {
      setStatus({ ...status, error: e.message });
    } finally {
      setStatus({ ...status, isLoading: false });
    }
  };

  return { posts, status };
}
```

**Comment by jdanielsyeah** [comment]
I've had a similar issue and fix to @hpwtaee. I've created a useRef instance to store the `updatedAt` property of my DataStore/DynamoDB object. It seems like a bit of a bodge. Is there no built-in means for `Datastore.observe.subscribe` to ensure it isn't duplicating calls? Even something like
```js
 const subscription = DataStore.observe(SomeModel).subscribe((arg) => {
      if (arg.prevElement.updatedAt !== arg.element.updatedAt) { // Check we aren't repeating ourselves
        triggerSomeStateUpdate();
      }
    });
    return () => subscription.unsubscribe();
```
