### ISSUE TITLE
Country Code in SignUp screen cannot be changed

### ISSUE THREAD

**Issue by chittasec** [aws-amplify/amplify-js#5944]
**Describe the bug**
Did the tutorial app for Amplify on React -native.
Used the default Auth screen . On the signup or login screen country code for phone number cannot be changed. it is always +1 .

**Comment by ashika01** [comment]
@chittasec I was able to reproduce this. Thanks for reporting the bug. We will look into this.

**Comment by amhinson** [comment]
@chittasec We are looking to improve this country code picker in the future, but would you be able to provide a video of the behavior you're seeing? I've got an app running with the latest version of `aws-amplify-react-native` and the picker seems to be working.
![Jun-09-2020 10-21-52](https://user-images.githubusercontent.com/17091790/84179716-3e1b7280-aa3b-11ea-9f6f-ba195d0b77f7.gif)
