### ISSUE TITLE
Modular import of storage is not working as expected, Angular app.

### ISSUE THREAD

**Issue by mrgoos** [aws-amplify/amplify-js#5947]
**Describe the bug**
When importing `Storage` from `@aws-amplify/storage` I get `No credentials` error after a while.
If I import from `aws-amplify` like this: `import  Storage  from 'aws-amplify';` I have no issues.

**To Reproduce**

1. Use this to import storage: `import  Storage  from '@aws-amplify/storage';`
2. Save and run the app with `ng serve`
3. See error in console: `[DEBUG] 05:24.549 Credentials - need to get a new credential or refresh the existing one` and `No credentials`

**Expected behavior**
No error should occur and interaction with storage should work as expected

**Code Snippet**
```
import  Storage  from '@aws-amplify/storage';
```

**Screenshots**
![image](https://user-images.githubusercontent.com/2561935/83329040-c2c5fe00-a28f-11ea-8391-bd11a5e54c90.png)

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.
* Which resources do you have configured?
  * If applicable, please provide your `aws-exports` file:
   ```
const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:xxx-xxxx-xxxx-xxxx-xxxxxxxx",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_xxx",
    "aws_user_pools_web_client_id": "xxxx",
    "oauth": {},
    "aws_user_files_s3_bucket": "xxx",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};
   ```
* If applicable, provide more configuration data, for example for Amazon Cognito, run `aws cognito-idp describe-user-pool --user-pool-id us-west-2_xxxxxx` (Be sure to remove any sensitive data)
 

<details>
  <summary><strong>Environment</strong></summary>

  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 1.17 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Brave Browser: 80.1.5.115
    Chrome: 83.0.4103.61
    Firefox: 76.0.1
    Safari: 13.1
  npmPackages:
    @angular-devkit/build-angular: 0.901.0 => 0.901.0
    @angular/animations: 9.0.7 => 9.0.7
    @angular/cdk: 9.1.3 => 9.1.3
    @angular/cli: 9.1.0 => 9.1.0
    @angular/common: 9.0.7 => 9.0.7
    @angular/compiler: 9.0.7 => 9.0.7
    @angular/compiler-cli: 9.0.7 => 9.0.7
    @angular/core: 9.0.7 => 9.0.7
    @angular/forms: 9.0.7 => 9.0.7
    @angular/language-service: 9.0.7 => 9.0.7
    @angular/material: 9.1.3 => 9.1.3
    @angular/platform-browser: 9.0.7 => 9.0.7
    @angular/platform-browser-dynamic: 9.0.7 => 9.0.7
    @angular/router: 9.0.7 => 9.0.7
    @aws-amplify/ui-angular: 0.2.6 => 0.2.6
    @types/jasmine: 3.3.8 => 3.3.8
    @types/jasminewd2: 2.0.6 => 2.0.6
    @types/node: 12.12.31 => 12.12.31
    ajv: 6.9.1 => 6.9.1
    ajv-keywords: 3.4.1 => 3.4.1
    aws-amplify: 3.0.12 => 3.0.12
    classlist.js: 1.1.20150312 => 1.1.20150312
    codelyzer: 5.2.1 => 5.2.1
    compass-sass-mixins: 0.12.7 => 0.12.7
    core-js: 2.6.11 => 2.6.11
    is-mobile: 2.0.0 => 2.0.0
    jasmine-core: 3.3.0 => 3.3.0
    jasmine-spec-reporter: 4.2.1 => 4.2.1
    json-server: 0.14.2 => 0.14.2
    karma: 4.4.1 => 4.4.1
    karma-chrome-launcher: 2.2.0 => 2.2.0
    karma-cli: 2.0.0 => 2.0.0
    karma-coverage-istanbul-reporter: 2.0.4 => 2.0.4
    karma-jasmine: 2.0.1 => 2.0.1
    karma-jasmine-html-reporter: 1.4.0 => 1.4.0
    ng2-validation: 4.2.0 => 4.2.0
    ngx-css-variables: 1.0.1 => 1.0.1
    node-sass: 4.14.1 => 4.14.1
    powerbi-client: 2.7.5 => 2.7.5
    protractor: 5.4.3 => 5.4.3
    rxjs: 6.5.4 => 6.5.4
    ts-node: 8.0.2 => 8.0.2
    tslib: 1.11.1 => 1.11.1
    tslint: 5.12.1 => 5.12.1
    typescript: 3.7.5 => 3.7.5
    zone.js: 0.10.3 => 0.10.3
  npmGlobalPackages:
    @angular/cli: 9.1.0
    @aws-amplify/cli: 4.21.0
    npm: 6.13.4

</details>

**Additional context**
I have auth and storage categories.
I am not using Angular components from amplify, just the lib code.

**Comment by mrgoos** [comment]
I tried [this approach](https://github.com/aws-amplify/amplify-js/issues/5574#issuecomment-620258084) and it worked but I don't know what are the implications of using it. In addition I saw different logs when debug was on. Logs included my key+secret to AWS while when when not doing this, I got the logs as in the original screenshot.

**Comment by mrgoos** [comment]
OK, I followed option 2 in the Angular related docs [here](https://docs.amplify.aws/start/getting-started/nextsteps/q/integration/angular#option-2-configuring-the-amplify-provider-with-specified-amplify-js-modules).
Now I'm using a service after installing `aws-amplify-angular` which is needed and it also works.
I'm only wondering why every time that I change a config I get different logs in debug.
It is working but I got many debug records like this:
![image](https://user-images.githubusercontent.com/2561935/83336974-4a2b6580-a2c0-11ea-91ef-45e23d6db47e.png)

And after I get: `[DEBUG] 49:01.797 Credentials - Load credentials successfully`.

And yes, I'm using Angular 9 so maybe it's also related.

**Comment by ashika01** [comment]
@mrgoos We dont support Angular 9 with aws-amplify-angular. I am closing this issue as we are aware of this and we are working on providing angular 9 with new ui-components `@aws-amplify/ui-angular`.

We already have angular 9 support for authenticator components and we are working on getting storage components next.

**Comment by mrgoos** [comment]
Thanks @ashika01 - so I'll just use the solution I put in the [1st self comment](https://github.com/aws-amplify/amplify-js/issues/5947#issuecomment-636359090) and hope it's OK.
