### ISSUE TITLE
Fix sendCustomChallengeAnswer typings

### ISSUE THREAD

**Issue by abemusic** [aws-amplify/amplify-js#595]
Do you want to request a feature or report a bug?

Bug

What is the current behavior?

Current typings for `CognitoUser.sendCustomChallengeAnswer` are invalid. See https://github.com/aws/aws-amplify/blob/master/packages/amazon-cognito-identity-js/index.d.ts#L57 and notice the callback of type NodeCallback...then, look at the actual code https://github.com/aws/aws-amplify/blob/master/packages/amazon-cognito-identity-js/src/CognitoUser.js#L696-L706 and notice that the expected callback is a map of functions.

What is the expected behavior?

The typings should match the underlying JS or else things don't work as expected :)

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

amazon-cognito-identity-js v2.0.2

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by elorzafe** [comment]
@abemusic this was fixed on this PR #1024

Feel free to create another issue in case the problem persist

Thanks!
