### ISSUE TITLE
Select MFA Type Angular Directive doesn't seem to work

### ISSUE THREAD

**Issue by nandkv** [aws-amplify/amplify-js#5950]
**Describe the bug**
having issues with activating amplify-select-mfa-type 

**To Reproduce**
Add auth to amplify app and enable the mfa on the user pool.

**Expected behavior**
Verify option with the MFA options

**Code Snippet**
`<amplify-authenticator usernameAlias="email">
  <amplify-sign-up
    slot="sign-up"
    usernameAlias="email"
  ></amplify-sign-up>
  <amplify-sign-in slot="sign-in" usernameAlias="email"></amplify-sign-in>
  <div>
    <amplify-sign-out></amplify-sign-out>
    <h1>Welcome to My App</h1>
  </div>
  <amplify-select-mfa-type MFATypes={MFATypeOptions}></amplify-select-mfa-type>
</amplify-authenticator>`

component:
`export class AppComponent {
  title = 'todoProject';
  MFATypeOptions: any;

  constructor() {
    this.MFATypeOptions = {
      SMS: true,
      Optional: true,
      TOTP: true,
    };
  }
}
`
**Screenshots**

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.
* Which resources do you have configured?
  * If applicable, please provide your `aws-exports` file:
   ```
   const awsmobile = {
       "aws_project_region": "us-east-1",
       "aws_cognito_identity_pool_id": "us-east-1:xxx-xxxx-xxxx-xxxx-xxxxxxxx",
       "aws_cognito_region": "us-east-1",
       "aws_user_pools_id": "us-east-1_xxx",
       "aws_user_pools_web_client_id": "xxxx",
       "oauth": {}
   };
   ```
   * If applicable, please provide your manual configuration example:
   ```
   {
    Auth: {
        identityPoolId: 'XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab',
        region: 'XX-XXXX-X',
        identityPoolRegion: 'XX-XXXX-X',
        userPoolId: 'XX-XXXX-X_abcd1234',
        userPoolWebClientId: 'a1b2c3d4e5f6g7h8i9j0k1l2m3',
        mandatorySignIn: false,
        authenticationFlowType: 'USER_PASSWORD_AUTH',
        oauth: {
            domain: 'your_cognito_domain',
            scope: ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
            redirectSignIn: 'http://localhost:3000/',
            redirectSignOut: 'http://localhost:3000/',
            responseType: 'code' // or 'token', note that REFRESH token will only be generated when the responseType is code
           }
       }
   }
   ```
* If applicable, provide more configuration data, for example for Amazon Cognito, run `aws cognito-idp describe-user-pool --user-pool-id us-west-2_xxxxxx` (Be sure to remove any sensitive data)
 

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

</details>

**Smartphone (please complete the following information):**

**Additional context**

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by ashika01** [comment]
@nandkv Could you provide some your angular code to reproduce this?

**Comment by nandkv** [comment]
The html and the component code is in the original issue. Let me know if that is not sufficient and I can provide link to a repo.

**Comment by ashika01** [comment]
@nandkv - can you link the original issue here for reference?
