### ISSUE TITLE
DataStore: saving relation doesn't work

### ISSUE THREAD

**Issue by roballsopp** [aws-amplify/amplify-js#5955]
**Describe the bug**
When attempting to save the id of a relation in a foreign key field, the saved value is null

**To Reproduce**
My graphql schema is:
```graphql
type SurveyTemplate @model {
  id: ID!
  name: String!
}

type SurveyResponse @model
  @key(name: "BySurveyTemplate", fields: ["surveyTemplateId", "createDate"]) {
  id: ID!
  surveyTemplateId: ID!
  surveyTemplate: SurveyTemplate! @connection(fields: ["surveyTemplateId"])
}
```
I've enabled datastore through the amplify cli, and I'm able to save `SurveyTemplate`s correctly to Dynamo. When I go to save a `SurveyResponse`, I do so [according to the documentation](https://docs.amplify.aws/lib/datastore/relational/q/platform/js#saving-relations):

```javascript
const response = await DataStore.save(
	new SurveyResponse({
		id: await uuid(),
		surveyTemplateId: surveyTemplate.id,
	})
);
```
But `console.log(response)` prints:
```javascript
SurveyResponse {
  "_deleted": undefined,
  "_lastChangedAt": undefined,
  "_version": undefined,
  "id": "1fe1048f-42ec-4f1f-96aa-82c2aa9dfb2f",
  "surveyTemplateId": null, // <--- why?
}
```

I also get a warning from DataStore: `"Variable 'input' has coerced Null value for NonNull type 'ID!'"`

**Expected behavior**
Foreign keys should be saved correctly:
```javascript
SurveyResponse {
  "_deleted": undefined,
  "_lastChangedAt": undefined,
  "_version": undefined,
  "id": "1fe1048f-42ec-4f1f-96aa-82c2aa9dfb2f",
  "surveyTemplateId": <surveyTemplate.id>,
}
```

**What is Configured?**
"@aws-amplify/cli": "4.21.0"
"aws-amplify": "3.0.13"

After running `amplify codegen models`, I see my `SurveyResponse` model in `src/models/index.d.ts` is:
```typescript
export declare class SurveyResponse {
  readonly id: string;
  readonly surveyTemplate: SurveyTemplate;
  readonly responseGroups?: ResponseGroup[];
  readonly questionResponses?: QuestionResponse[];
  readonly createDate: string;
  constructor(init: ModelInit<SurveyResponse>);
  static copyOf(source: SurveyResponse, mutator: (draft: MutableModel<SurveyResponse>) => MutableModel<SurveyResponse> | void): SurveyResponse;
}
```
Is it supposed to have a `surveyTemplateId` field? Why does it remove this when my graphql schema has it?

**Comment by ashika01** [comment]
@roballsopp It is supposed to have `surveyTemplateId`. It something we use under the hood to establish connection thats the reason you dont see it in the graphql schema modelgen. On first glance at your code, I dont understand why you are setting the ID using `Datastore.save()` you shouldn't set the ID. 

Could you explain what you are trying to achieve?

**Comment by roballsopp** [comment]
In my data modal, `SurveyResponse`s always have one `SurveyTemplate`, so there is a foreign key on `SurveyResponse` to establish this relationship. Here's the DataStore documentation I linked to:

![image](https://user-images.githubusercontent.com/6366105/83820243-6432c280-a689-11ea-8f00-6a06441c5c1d.png)

That's pretty much exactly what I'm trying to do. The only difference in my code is I have not defined the `@connection` in the "has many" direction, but rather the "has one" direction because its more useful in my case to get the associated `SurveyTemplate` when I query for a given `SurveyResponse`, and not as useful to get a list of `SurveyResponse`s for a given `SurveyTemplate`:
```
surveyTemplate: SurveyTemplate! @connection(fields: ["surveyTemplateId"])
```
Seems like setting the id field should work the same here as if I had defined the connection in the other direction. Why shouldn't I be setting the id this way?

**Comment by ashika01** [comment]
@roballsopp So you want to establish 1:1 relationship then between `surveyResponse` and `surveyTemplate`? or are you saying `many surveyResponse` has `one surveyTemplate`? Understanding the schema could help me.

Also, when I said not setting the ID, I meant, instead of doing this
```
await DataStore.save(
	new SurveyResponse({
		id: await uuid(),
		surveyTemplateId: surveyTemplate.id,
	})
);
```

You should be doing something like
```
await DataStore.save(
	new SurveyResponse({
		surveyTemplateId: surveyTemplate.id,
	})
);
```
or
```
await DataStore.save(
	new SurveyResponse({
		surveyTemplate: surveyTemplate,
	})
);
```

**Comment by roballsopp** [comment]
I'm saying `many surveyResponse` has `one surveyTemplate`. Its not 1:1. Also, I am in the habit of setting primary key ids on the client for offline purposes. I am actually moving code from Apollo to DataStore, and with Apollo its nice to have the real id in my optimistic updates to the cache. Maybe DataStore handles this nicely somehow, not sure.

**Comment by ashika01** [comment]
@roballsopp Let me try you schema in an app. I am going by your first schema code.

**Comment by ashika01** [comment]
@roballsopp Hi, My initial guess was right. Our codegen looks for specific schema pattern to generate the model gen.

I had success following the pattern in the docs exactly because the connection has to be established from both sides.

My schema 
```
# one side
type SurveyTemplate @model {
  id: ID!
  name: String!
  surveyResponses: [SurveyResponse]
    @connection(keyName: "BySurveyTemplate", fields: ["id"])
}

# many side
type SurveyResponse
  @model
  @key(name: "BySurveyTemplate", fields: ["surveyTemplateId", "content"]) {
  id: ID!
  surveyTemplateId: ID!
  content: String!
}
```

Screenshot:
<img width="783" alt="Screen Shot 2020-06-05 at 11 01 39 AM" src="https://user-images.githubusercontent.com/35131273/83908510-14e9a200-a71c-11ea-87cb-faa63905aefd.png">

There is a lot that goes under hood. With respect to offline, datastore handles a lot of it for you.

I am going to close this issue. If you encounter any bug, ping here and I will reopen the issue. Please feel free to [join our discord](https://discord.gg/Px5YVfQ) or discussions tab to ask questions and get feedback :)
