### ISSUE TITLE
Expo-Amplify project: aws-amplify-react-native broken using latest react-native-web 0.12.x

### ISSUE THREAD

**Issue by ikakara** [aws-amplify/amplify-js#5957]
This bug was closed prematurely: https://github.com/aws-amplify/amplify-js/issues/5865

Related to this bug: https://github.com/react-native-elements/react-native-elements/issues/2368 which has been fixed in 2.0.1.

The latest aws-amplify-react-native v4.2 depends on react-native-elements@0.19.1

Please update aws-amplify-react-native to use react-native-elements@2.0.1

Thanks

**Comment by nckswt** [comment]
Just wanted to note that this is a bug we currently have to work around. 

I manually updated my `package-lock.json` to bump `react-native-elements` to `2.0.4` and no longer experienced the `Module not found: Can't resolve 'react-native-web/dist/exports/ViewPropTypes'` error I'd been experiencing:

```js
    "aws-amplify-react-native": {
      "version": "4.2.1",
      "requires": {
          ... 
         "react-native-elements": "^2.0.4",
          ...
      },
      "dependencies": {
        ...
          "react-native-elements": {
            "version": "2.0.4",
            "resolved": "https://registry.npmjs.org/react-native-elements/-/react-native-elements-2.0.4.tgz",
            ...
         }
    }
```

Would it be helpful if I provided a PR with a version bump of `react-native-elements`?

**Comment by ikakara** [comment]
please,  I tried the following (w/o success):

    "aws-amplify-react-native": {
      "version": "4.1.2",
      "resolved": "https://registry.npmjs.org/aws-amplify-react-native/-/aws-amplify-react-native-4.1.2.tgz",
      "integrity": "sha512-PBbxgqcICtsS8p92MZjTePdyZlrSj14xn7Apm7Z4vJtzXyhzgXPuwowFvXwoP/C+o41fqZj7ke3tv2i3n9Gxjw==",
      "requires": {
        "babel-preset-es2015": "^6.24.1",
        "buffer": "^5.2.1",
        "react-native-elements": "^2.0.4",
        "react-native-vector-icons": "^6.6.0"
      },
      "dependencies": {
        "buffer": {
          "version": "5.6.0",
          "resolved": "https://registry.npmjs.org/buffer/-/buffer-5.6.0.tgz",
          "integrity": "sha512-/gDYp/UtU0eA1ys8bOs9J6a+E/KWIY+DZ+Q2WESNUA0jFRsJOc0SNUO6xJ5SGA1xueg3NL65W6s+NY5l9cunuw==",
          "requires": {
            "base64-js": "^1.0.2",
            "ieee754": "^1.1.4"
          }
        },
        "react-native-elements": {
          "version": "2.0.4",
          "resolved": "https://registry.npmjs.org/react-native-elements/-/react-native-elements-2.0.4.tgz",
          "integrity": "sha512-nIFz47Sk/urOxZX+sqgWF2k7IVL0t9NGsVLg4HC7pN70bsjXMr4VUmS72zioxag3Du8xK1g7lw4vrRX3JQeVYg==",
          "requires": {
            "lodash.isempty": "^4.4.0",
            "lodash.times": "^4.3.2",
            "opencollective": "^1.0.3",
            "prop-types": "^15.5.8"
          }
        }
      }
    },

**Comment by ikakara** [comment]
I'm an idiot ... this works for me 

"aws-amplify-react-native": {
      "version": "4.2.1",
      "resolved": "https://registry.npmjs.org/aws-amplify-react-native/-/aws-amplify-react-native-4.2.1.tgz",
      "integrity": "sha512-J08OL5f8irWPDYbcgUYTS/cmNBBmHgf4hpmNvqGDJdcXpSIbnRR+nFQQXDVkvyJ5UJQnfgMpUXpBEASfSMBUow==",
      "requires": {
        "babel-preset-es2015": "^6.24.1",
        "buffer": "^5.2.1",
        "react-native-elements": "^0.19.1",
        "react-native-vector-icons": "^6.6.0"
      },
      "dependencies": {
        "buffer": {
          "version": "5.6.0",
          "resolved": "https://registry.npmjs.org/buffer/-/buffer-5.6.0.tgz",
          "integrity": "sha512-/gDYp/UtU0eA1ys8bOs9J6a+E/KWIY+DZ+Q2WESNUA0jFRsJOc0SNUO6xJ5SGA1xueg3NL65W6s+NY5l9cunuw==",
          "requires": {
            "base64-js": "^1.0.2",
            "ieee754": "^1.1.4"
          }
        },
        "react-native-elements": {
          "version": "2.0.4",
          "resolved": "https://registry.npmjs.org/react-native-elements/-/react-native-elements-2.0.4.tgz",
          "integrity": "sha512-nIFz47Sk/urOxZX+sqgWF2k7IVL0t9NGsVLg4HC7pN70bsjXMr4VUmS72zioxag3Du8xK1g7lw4vrRX3JQeVYg==",
          "requires": {
            "@types/react-native-vector-icons": "^6.4.5",
            "color": "^3.1.0",
            "deepmerge": "^3.1.0",
            "hoist-non-react-statics": "^3.1.0",
            "lodash.isequal": "^4.5.0",
            "opencollective-postinstall": "^2.0.0",
            "prop-types": "^15.7.2",
            "react-native-ratings": "^7.2.0",
            "react-native-status-bar-height": "^2.5.0"
          }
        }
      }
    },

**Comment by ikakara** [comment]
I'll test some more ... thanks Nick!

**Comment by ikakara** [comment]
i created a branch https://github.com/ikakara/expo-amplify-bug/tree/workaround

The bug can be found here: https://github.com/ikakara/expo-amplify-bug/tags

**Comment by nckswt** [comment]
To be clear, that workaround's a hack and would only allow things to work if you install `node_modules` from the `package-lock.json` directly (`npm ci` instead of `npm i`). 

The proper fix (unless it breaks testing, which I haven't looked at) would be to change the [package.json](https://github.com/aws-amplify/amplify-js/blob/main/packages/aws-amplify-react-native/package.json#L32) from `"react-native-elements": "^0.19.1"` to `"react-native-elements": "^2.0.4"`, then test against that change.

**Comment by ikakara** [comment]
Sometimes a hack is better than nothing.  Thanks for finding it.

I imagine there are dependencies for react-native-elements@0.19.1 in other aws packages which will need to be tested against too.  It's not a trivial change (I'm guessing) ... so I wait patiently
