### ISSUE TITLE
DataStore @auth not working as per docs in Vue app

### ISSUE THREAD

**Issue by kannieWeesNie** [aws-amplify/amplify-js#5961]
**Describe the bug**
using Vue, amplify datastore the @auth directive not working as per documents.

any user (authorized and unauthorized) can create, list and delete all todo objects

**To Reproduce**
using amplify, create Vue app, install authentication and datastore libraries

create object:
`var result = await DataStore.save(
          new Todo({
           name: "authorized",
           description: "Hi everyone!",
            createdAt: new Date().toISOString(),
          })
        );
        console.log(
          "datastore object saved: " + JSON.stringify(result, null, 2)
        );`
		
delete all objects:

`DataStore.delete(Todo, Predicates.ALL)
        .then(() => {
          console.log("all dataStore messages deleted!");
        })
        .catch((error) => {
          console.log("delete error: " + JSON.stringify(error, null, 2));
        });`
		
list all objects:
`        const messages = await DataStore.query(Todo, Predicates.ALL);
         console.log("list all todos: " + JSON.stringify(messages, null, 2));
      } catch (err) {
        console.log("list all todos errors: " + JSON.stringify(err, null, 2));
      }`

my schema:

`type Todo @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  name: String!
  description: String
  priority: String
  owner: String
}`

**Expected behavior**
as per docs - "In this schema, only the owner of the object has the authorization to perform read (getTodo and listTodos), update (updateTodo), and delete (deleteTodo) operations on the owner created object."

**Comment by ashika01** [comment]
@kannieWeesNie : How did you configure your app in the CLI? Also could you share your aws-exports removing sensitive info?

**Comment by kannieWeesNie** [comment]
@ashika01 : How did you configure your app in the CLI? - honestly i have forgotten each step i took but basically followed the documentation - installed amplify, created Vue app, installed api's (graphql & rest), authentication, storage and then updated the graph api to use datastore. i made a few updates to some, if not all the libraries i installed. initially i set the api to use the api key for authentication but changed this to cognito in an update.

i have now just completed setting up a new Vue app as per the docs, installed authentication and api ghraphQl (again used api key for authentication - by mistake as i wanted to use cognito) and then updated to use cognito. then used 
`npm install --save @aws-amplify/core @aws-amplify/datastore`
to install datastore.

i have the same problem with authorization. i create two cognito users, log in with each one, create two data store objects per user. so, if i log in as clive and list items, i see clive's objects as well as bobby's objects. if i look in developer console>application>indexedDb i see both users objects!

similarly if i log in as bobby, i see bobby's 2 items as well as clive's two items, same in developer console's indexedDb, both user's items are displayed.

i can also delete all items if i am logged in as either user!

here's my schema for the new app:

`type Todo @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  name: String!
  description: String
  owner: String
}
`
i notice with this app that when i list an item, the owner field displays the logged in user name whereas the previous app (using same schema) displayed the owner field as null

here's the aws-exports file for the newest Vue app:

`const awsmobile = {
    "aws_project_region": "eu-xxxx",
    "aws_cognito_identity_pool_id": "xxxxxx",
    "aws_cognito_region": "exxxx",
    "aws_user_pools_id": "exxxxxx",
    "aws_user_pools_web_client_id": "1xxxxxx",
    "oauth": {
        "domain": "xxxxxx.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:8080/",
        "redirectSignOut": "http://localhost:8080/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://uxxxxxxx-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "euxxxx",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};`

and her'es the one for previous Vue app:

`const awsmobile = {
    "aws_project_region": "exxxx",
    "aws_appsync_graphqlEndpoint": "https://ixxxxxxxx1.amazonaws.com/graphql",
    "aws_appsync_region": "exxxx",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "xxxxx",
            "endpoint": "https://9xxxxxx-1.amazonaws.com/dev",
            "region": "xxxxx"
        }
    ],
    "aws_cognito_identity_pool_id": "exxxx",
    "aws_cognito_region": "exxx",
    "aws_user_pools_id": "exxxx",
    "aws_user_pools_web_client_id": "6xxxxxx",
    "oauth": {
        "domain": "uxxxxx1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:8080/",
        "redirectSignOut": "http://localhost:8080/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_dynamodb_all_tables_region": "exxxx",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "uxxxx",
            "region": "exxx"
        }
    ],
    "aws_user_files_s3_bucket": "uxxxx",
    "aws_user_files_s3_bucket_region": "exxx"
};`

thanks for your assistance

**Comment by ashika01** [comment]
@kannieWeesNie Before I go down the route to debug, could we try setting up datastore directly instead of having the api put in first? Like follow the steps here - https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js#automated-model-generation-with-npx


We have some mishaps in the past with converting api to datastore. I find this way faster. If its impossible, let me know and we can go down debugging this route.

**Comment by kannieWeesNie** [comment]
@ashika01 thank you for your help. the link you gave refers to building a React app and not a Vue app. i tried following the video tutorial, substituting vue for react but got errors with the push. here are the errors:

> The following resource(s) failed to create: [DataStore, GraphQLSchema].

> Resource creation cancelled (dynamodb table)

> Schema Creation Status is FAILED with details: Found 1 problem(s) with the schema:
There is no top level schema object defined.

> × An error occurred when pushing the resources to the cloud

> Resource is not in the state stackUpdateComplete
> An error occured during the push operation: Resource is not in the state stackUpdateComplete

is there a Vue specific tutorial on how to include DataStore in to a Vue app?

thanks

**Comment by ashika01** [comment]
the setup should be same right? We dont have vue code in there. But we are working on our docs right now and we have action items to get that done.

**Comment by ashika01** [comment]
Basically, I want you try using these steps for setup

```
vue create amplify-datastore
cd amplify-datastore
npx amplify-app@latest
```

So your datastore base is setup for you.

**Comment by kannieWeesNie** [comment]
@ashika01 thanks for the help but unfortunately i still cannot get it to work.

after installing as per your instructions, i installed the Auth library, then changed the schema. then had to update the api to link to cognito pools:
`amplify update api
? Please select from one of the below mentioned services: GraphQL
? Select from the options below Update auth settings
? Choose the default authorization type for the API Amazon Cognito User Pool
Use a Cognito user pool configured as a part of this project.
? Configure additional auth types? No`

then i ran:
`npm run amplify-modelgen`

because i changed the schema.

i then run
`amplify push`

all good and well but when i try to build the app by:
`npm run serve`

i get this error:
` ERROR  Failed to compile with 5 errors                                                                         15:26:51

These dependencies were not found:

* @aws-amplify/datastore in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/HelloWorld.vue?vue&type=script&lang=js&, ./src/models/index.js
* @aws-amplify/ui-vue in ./src/main.js
* aws-amplify in ./src/main.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/HelloWorld.vue?vue&type=script&lang=js&

To install them, you can run: npm install --save @aws-amplify/datastore @aws-amplify/ui-vue aws-amplify
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'`

i then run:
`npm install --save @aws-amplify/datastore @aws-amplify/ui-vue aws-amplify`

all is well after i build the app, except when i test the datastore with auth. i am still able to list all objects for all users no matter which user is logged in (even when not logged in)

appreciate your help but would really like to get it to work and appreciate any hints as to how to do that.

thanks

**Comment by ashika01** [comment]
@kannieWeesNie could you post a sample schema for me with you trying to get it working? I can try reproduce this in vue and post you the steps.

**Comment by kannieWeesNie** [comment]
@ashika01 thanks very much. here's my schema:
`type Todo @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  name: String!
  description: String
  owner: String
}
`
thank you

**Comment by HenryDavies** [comment]
I'm having the same problem in a React Native project set up with expo, with api and auth added via `amplify add`

**Comment by kannieWeesNie** [comment]
@ashika01 any luck with resolving the problem?

**Comment by kannieWeesNie** [comment]
problem solved!

datastorage always accesses the local storage which is then synced with the backend.

i was logging in using different users and creating, updating, deleting items. the result was a lot of different items in the local storage, owned by different users.

calling any query or mutation, no matter the logged in user, would access all the data in the local storage without using the @auth filter, so all the data in the local storage "belonged" to whichever user was logged in. 

the solution was to call DataStore.clear() when users logged out. this would delete all data in the local storage so that when a user logged in, only their data would be in the local storage

hope this helps anyone coming across this problem
