### ISSUE TITLE
Clarification: Without Bearer before the token in Header in aws-amplify-react-native it will work fine or not(without any error 401)

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#5962]
I am using aws-amplify and aws-amplify-react-native for authentication. Here my question is does the  Headers will works without Bearer before the headers section.

(or) it is mandatory to add Bearer before

```
  headers: {
            'Content-Type': 'application/json',
            'Authorization': jwtToken,
        },
```

 ```
headers: {
            'Content-Type': 'application/json',
            'Authorization': "Bearer" + jwtToken,
        },
```

**Comment by amhinson** [comment]
@nihp Can can you provide some additional information:
-  larger code snippet of where you are trying to use this
- What Amplify categories are you using?
- What version of the libraries are you using?

**Comment by nihp** [comment]
I am using Auth.currentSession(); from the import { Auth } from 'aws-amplify'.
I am using the latest version of the aws-amplify("^3.0.11") and aws-amplify-react-native(^4.1.2)

**Comment by amhinson** [comment]
It appears you're hitting a non-Amplify endpoint, so the use of `Bearer` depends on your server's implementation.

**Comment by amhinson** [comment]
That sounds like another issue unrelated to the original. Could you open a new issue for that and provide some reproduction steps so we can replicate the behavior as well?
