### ISSUE TITLE
Unable to resolve "./httpHandlerOptions" from "node_modules\@aws-amplify\storage\lib-esm\providers\AWSS3Provider.js"

### ISSUE THREAD

**Issue by mauerbac** [aws-amplify/amplify-js#5964]
I'm creating a react native expo application with AWS. I got this error once I added storage to the amplify using amplify add storage.

_Originally posted by @rmit-s3705430-rajesh-choudhari in https://github.com/aws-amplify/amplify-js/discussions/5878_

**Comment by ashika01** [comment]
@rmit-s3705430-rajesh-choudhari could you let us know what versions of amplify are using? also how your configuration looks like?

**Comment by rmit-s3705430-rajesh-choudhari** [comment]
@mauerbac @ashika01 Thank you for your response. I don't know this was a very weird issue that I was facing. Later I cleared the cache using 'expo start -c' and it worked.

**Comment by illiteratewriter** [comment]
I've also faced the same issue. But `npx react-native start --reset-cache` fixed the issue for me.
