### ISSUE TITLE
Not receiving the authorization code after signIn, needed for account linking with Alexa

### ISSUE THREAD

**Issue by richa18b** [aws-amplify/amplify-js#5969]
I use Amazon Cognito as my Identity provider for my application, and while trying to link my app's account with Alexa, I am using my own custom UI, instead of going ahead with the hosted UI, due to few requirements. 
I use aws-amplify for signing in the user from my custom UI page, and don't seem to receive an authorization code in the response received, which would be needed to pass on in the 'code' param while redirecting back to Alexa's Redirect URI.

Here's a screenshot of the response received after signing in:

![Screenshot (143)_LI](https://user-images.githubusercontent.com/22676822/83505710-ca7de080-a4e3-11ea-9151-655dcb6acf0d.jpg)

**Comment by ashika01** [comment]
@richa18b We dont have an issue on our side. When I try to do the confirm-sign-in flow I am able to receive the code to continue sign in.

To move forward could you provide with sample code and `aws-exports`(removing sensitive info) to reproduce the issue. 

Note: you could look into our `ui-component` implementation for example.

**Comment by richa18b** [comment]
@ashika01 Hey, I am not talking about the code for continuing the sign-in, I am talking about the authorization code that I expect in the response object, once the user is successfully authenticated by Amazon Cognito.

Check point number 4 on this link: [https://developer.amazon.com/en-US/docs/alexa/account-linking/configure-authorization-code-grant.html#overview-of-the-authorization-code-grant-flow](url)

I need the authorization code to pass it on to Alexa for completing the account-linking process for my skill.

Also, regarding the sample code, I am using React in my custom login page that is replacing the default hosted UI by Amazon Cognito for this process. And, that includes just importing `Auth` from `aws-amplify`, and invoking the `signIn()` method, that's it.

`import { Auth } from 'aws-amplify';
Auth.signIn(username, password);`

My aws-exports file looks like this:

`const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:c6cd4**xxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx**",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_**xxxxxxxxx**",
    "aws_user_pools_web_client_id": "6jedjb**xxxxxxxxxxxxxxxxxxxx**",
    "oauth": {
        domain: 'https://**xxxxxxxxxxx**.auth.ap-south-1.amazoncognito.com',
        scope: ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
        redirectSignIn: 'https://**xxxxxxxxxxx**.auth.ap-south-1.amazoncognito.com/authorize',
        redirectSignOut: 'https://**xxxxxxxxxxx**.auth.ap-south-1.amazoncognito.com/logout',
        responseType: 'code'
    }
};


export default awsmobile;`

**Comment by ashika01** [comment]
@richa18b I am confused here. If you are using hosted UI, then you need to setup like this https://docs.amplify.aws/lib/auth/social/q/platform/js#setup-frontend

And use `Auth.federatedSignIn()` not `Auth.signIn` right?

**Comment by richa18b** [comment]
@ashika01 My identity provider is still Amazon Cognito, I don't think I need `federatedSignIn()` in this case!
Also, this is the case, I am not going with the hosted UI, I have built a custom UI of my own, without using the `ui-components` facility provided in aws-amplify. I am using my own components in there!
