### ISSUE TITLE
signIn event on Hub auth channel is never fired

### ISSUE THREAD

**Issue by atelic** [aws-amplify/amplify-js#5973]
**Describe the bug**
I've set up a listener on the auth channel as described in the documentation [here](https://docs.amplify.aws/lib/utilities/hub/q/platform/js#authentication-events). The `signOut`, `configured`, and `parsingCallbackUrl` events all fire as expected, but the `signIn` never does. 

**To Reproduce**

1. On my sign in page, call `Auth.federatedSignIn()` to open the hosted Cognito UI. 
2. Sign in with my user
3. Be redirected to the home page 
4. See that the `signIn` event is not fired and any console.logs inside are not logged.

**Expected behavior**
I expect the event to be handled by the Hub listener. 

**Code Snippet**
```ts
// App.vue
<template>
  <div id="app">
    <router-view />
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
import { Hub } from 'aws-amplify';

export default Vue.extend({
  name: 'App',
  beforeCreate() {
    Hub.listen('auth', (data: any) => {
      const { payload } = data;
      console.log(payload);
      const { event } = payload;
      console.log(event);
      switch (event) {
        case 'signIn':
          console.log('signing in...', event, data);
          break;
        case 'signOut':
          console.log('signing out...');
          break;
      }
    });
  },
});
</script>
// SignIn.vue
<script lang="ts">
import Vue from 'vue';
import Amplify, { Auth, Hub } from 'aws-amplify';
import awsconfig from '@/awsconfig';
import awsauth from '@/awsauth';

Amplify.configure(awsconfig);
Auth.configure({ oauth: awsauth });

export default Vue.extend({
  mounted() {
    Auth.federatedSignIn();
  },
});
</script>
``` 

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

</details>
- aws-amplify version: 3.0.13
- Vue version: 2.6.11

**Comment by ashika01** [comment]
@atelic Would it be possible for you to [try something like this](https://github.com/aws-amplify/amplify-js/blob/master/packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx#L42)

Basically, in case of hostedUI, you listen for event payload `cognitoHostedUI` and set the state based of that.

**Comment by atelic** [comment]
Hi @ashika01, thanks for the reply. I updated my listener to look like this:

```ts
export default Vue.extend({
  name: 'App',
  beforeCreate() {
    const handleExternalAuthEvent = ({ payload }) => {
      switch (payload.event) {
        case 'cognitoHostedUI':
          console.log('hosted ui success');
          break;
        case 'cognitoHostedUI_failure':
        case 'parsingUrl_failure':
          console.log('failure');
          break;
        case 'signOut':
          console.log('signed out');
          break;
      }
    };
    Hub.listen('auth', handleExternalAuthEvent);
  },
});
```
But I never see the `'cognitoHostedUI'` get fired either. It did make me think about two things though:
1. My app is a SPA and coming back from an external domain causes the app to have to remount. Could the event happen before the listener is set up? I'm creating it at the earliest lifecycle hook possible.
2. After signing in through the hosted UI, I'm redirected back to my home page with the url looking like this: 
`http://localhost:7777/#access_token=SOME_JWT&id_token=ANOTHER_JWT&state=yAXfSDeWh7SBogUtIurFFJtMtO9UQI4P&token_type=Bearer&expires_in=3600`. I don't think it ever parses that url and it just stays like that. Am I missing some step in the callback?

**Comment by atelic** [comment]
@ashika01 here is a repository with the minimum required to reproduce:
https://github.com/atelic/aws-amplify-bug-repro

**Comment by ashika01** [comment]
@atelic : I will be on it shortly.

**Comment by atelic** [comment]
@ashika01, I was able to upgrade `aws-amplify` to the most recent version that was released a day ago and I am now seeing the `cognitoHostedUI` event. However, `currentSession` and `currentAuthenticatedUser` never return user info. Is there something I need to do with hosted UI to get these to work?

**Comment by ashika01** [comment]
How does you payload data look like? I think that should be the user info right?

**Comment by atelic** [comment]
Yes I do get a CognitoUserSession object with an access and id token inside. This is great! However my concern is that if the `currentSession` and `currentAuthenticatedUser` functions always return null or throw an error, even after sign in, I will not be able to easily refresh tokens

**Comment by ashika01** [comment]
Your `currentAuthenticatedUser` shouldn't be null. Can you check your implementation with [our UI to get an idea](https://github.com/aws-amplify/amplify-js/blob/master/packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx)

In our lifecycle we wait till the redirect is finished to get user info,[ around here](https://github.com/aws-amplify/amplify-js/blob/master/packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx#L71-L73)

This might be what you are missing.
