### ISSUE TITLE
react-native s3Images doesn't show other users images under protected level

### ISSUE THREAD

**Issue by kiitos-smasri** [aws-amplify/amplify-js#5987]
am trying to use s3Image in react-native app under protected level but seems you need to pass identityId when getting images from storage 

https://github.com/aws-amplify/amplify-js/blob/a047ce73abe98c3bf82e888c3afb4d2f911805f3/packages/aws-amplify-react-native/src/Storage/S3Image.js

`	getImageSource() {
		const { imgKey, level } = this.props;
		Storage.get(imgKey, { level: level ? level : 'public' })
			.then(url => {
				logger.debug(url);
				this.setState({
					src: { uri: url },
				});
			})
			.catch(err => logger.warn(err));
	}`

**Comment by ashika01** [comment]
@kiitos-smasri What does your code look like? For protected you need to pass in `identityId` to get the image.

**Comment by ashika01** [comment]
The same goes for this issue as well - https://github.com/aws-amplify/amplify-js/issues/5986
I am closing the other one to track it here.

**Comment by ashika01** [comment]
@kiitos-smasri Apologies, I looked into the component we dont have the `protected with identityId` yet for react native. We have feature request open here - https://github.com/aws-amplify/amplify-js/issues/3433

I am closing this issue and will track the updates there.
