### ISSUE TITLE
Api package does not specify core version

### ISSUE THREAD

**Issue by Enase** [aws-amplify/amplify-js#5988]
**Describe the bug**
[This file](https://github.com/aws-amplify/amplify-js/blob/1123cef546e906ba1beecedecdc60b3844f38297/packages/api/src/API.ts#L19) imports `{ Amplify }` from `@aws-amplify/core`
That package [doesn't specify](https://github.com/aws-amplify/amplify-js/blob/1123cef546e906ba1beecedecdc60b3844f38297/packages/api/package.json#L40) the version of `@aws-amplify/core` it depends on, so it uses whatever is available
In some cases it's using version 2.3.0, which doesn't export Amplify as a named export.

**Steps to reproduce:**

1. Run `git clone https://github.com/Enase/babel-issue.git`
2. Run `npm i` in project root
3. Run `npm run start` in project root
4. Open `http://localhost:3000` in browser

**Expected result:**

`Hello` message in a browser with no errors in console.

**Actual result result:**

Error in a browser:
```
Uncaught TypeError: Cannot read property 'register' of undefined
    at new APIClass (API.js?0f51:80)
    at eval (API.js?0f51:205)
    at Object../node_modules/@aws-amplify/api/lib/API.js (vendors~main.chunk.js:2003)
    at __webpack_require__ (main.js:849)
    at fn (main.js:151)
    at eval (index.js?636d:15)
    at Object../node_modules/@aws-amplify/api/lib/index.js (vendors~main.chunk.js:2015)
    at __webpack_require__ (main.js:849)
    at fn (main.js:151)
    at eval (index.js?b994:42)
```

related issue: https://github.com/babel/babel/issues/11661

**Comment by ashika01** [comment]
@Enase could clear any cache, remove your lock files and try doing an install.? Also, could you post your package.json info if the issue still exist?

**Comment by Enase** [comment]
@ashika01 If you try to install `aws-amplify@latest` you will see that `@aws-amplify/pubsub@^2.1.1` is required.
```
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @aws-amplify/api@3.1.16 requires a peer of @aws-amplify/pubsub@^2.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN @aws-amplify/datastore@2.2.3 requires a peer of @react-native-community/netinfo@^5.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN @aws-amplify/api-graphql@1.0.18 requires a peer of @aws-amplify/pubsub@^2.1.1 but none is installed. You must install peer dependencies yourself.
```

If you add `@aws-amplify/pubsub@^2.1.1` to your package.json - as a result you will have two different versions of `@aws-amplify/core` module.

Full example you can find a [repository by url](https://github.com/Enase/babel-issue) provided in issue description.
there is a link to [package.json](https://github.com/Enase/babel-issue/blob/master/package.json)

**Comment by Enase** [comment]
@ashika01 I can update all the dependencies to latest if you need. Issue still exists.

**Comment by GordonSo** [comment]
Ran into the same problem today with npm install, and decided to switch from `npm install` to `yarn add` for my entire project to get it working. It would be nice to fix npm dependencies or update readme so people are not following non-working steps.

**Comment by amhinson** [comment]
@Enase Are you still having an issue here?

**Comment by Enase** [comment]
@amhinson I confirm it works with the latest dependencies. Issue might be closed
