### ISSUE TITLE
API graphqlOperation update doesn't seem to do anything

### ISSUE THREAD

**Issue by Darapsas** [aws-amplify/amplify-js#5990]
**Describe the bug**
After recent updates, I noticed that API.graphql update operation doesn't work properly (it seems that it doesn't do anything at all). 

**To Reproduce**

1. execute await API.graphql(graphqlOperation(updateUserData, {...})
2. nothing changes

**Expected behavior**
Expecting some changes to the data, for example below funds should be updated, but in reality nothing happens.

**Code Snippet**
```
          const updatedUserData: any = await API.graphql(
            graphqlOperation(updateUserData, {
              input: {
                id: state.user.info.id,
                funds: {
                  amount: 100,
                  currency: 'eur',
                },
              },
            })
```

**Screenshots**
It is pretty self explanatory
![20200603_155241](https://user-images.githubusercontent.com/20926795/83638827-6fff8580-a5b2-11ea-9931-57ca504da565.png)

**What is Configured?**
Mainstream configuration:
![20200603_155423](https://user-images.githubusercontent.com/20926795/83638960-a806c880-a5b2-11ea-86cd-e615e6760382.png)

Package packs that I tried to use and still get the same issue:
I think it started when I updated to these packages:
```
    "@aws-amplify/api": "3.1.11",
    "@aws-amplify/auth": "3.2.8",
    "@aws-amplify/cache": "3.1.11",
    "@aws-amplify/core": "3.2.8",
    "@aws-amplify/datastore": "2.1.1",
    "@aws-amplify/pubsub": "3.0.12",
    "@aws-amplify/storage": "3.2.1",
```
Tried on the newest release (still the same issue persists): 
```
    "@aws-amplify/api": "3.1.14-unstable.2",
    "@aws-amplify/auth": "3.2.11-unstable.2",
    "@aws-amplify/cache": "3.1.14-unstable.2",
    "@aws-amplify/core": "3.3.1-unstable.2",
    "@aws-amplify/datastore": "2.2.1-unstable.2",
    "@aws-amplify/pubsub": "3.0.15-unstable.2",
    "@aws-amplify/storage": "3.2.4-unstable.2",
    "amazon-cognito-identity-js": "4.3.0",
```

**Additional context**
Seems to be connected - https://github.com/aws-amplify/amplify-cli/issues/3967
Amplify is used on react-native 0.62.2.

**Comment by ashika01** [comment]
@Darapsas tried the same in react things seem to work as expected. 

<img width="775" alt="Screen Shot 2020-06-05 at 2 19 43 PM" src="https://user-images.githubusercontent.com/35131273/83923741-b7fbe500-a737-11ea-93a1-af5d6ef512d1.png">

I also see the data changed in dynamodb table. 
<img width="1205" alt="Screen Shot 2020-06-05 at 2 21 39 PM" src="https://user-images.githubusercontent.com/35131273/83923881-0610e880-a738-11ea-8be3-0c08d36fadaa.png">

Let me know if I am missing something.

**Comment by Darapsas** [comment]
Hello, @ashika01 ,
I see that it is working properly for you (it worked for me too - a few weeks back), but right now I am still hanging here with API graphql update operation doing nothing, I am almost certain that there is something with DataStore conflict resolution, that is not allowing for it to properly work.

I mainly use DataStore, but there was an exception for which I wanted to use API graphql operation, but I think I will try to move everything to DataStore (because it seems to properly work).

Currently I am using these packages:
```
    "@aws-amplify/api": "3.1.16-unstable.4",
    "@aws-amplify/auth": "3.2.13-unstable.4",
    "@aws-amplify/cache": "3.1.16-unstable.4",
    "@aws-amplify/core": "3.3.3-unstable.4",
    "@aws-amplify/datastore": "2.2.3-unstable.4",
    "@aws-amplify/pubsub": "3.0.17-unstable.4",
    "@aws-amplify/storage": "3.2.6-unstable.4",
    "amazon-cognito-identity-js": "4.3.2-unstable.8",
```

**Comment by ashika01** [comment]
@Darapsas That could totally be it. The Datastore (Appsync) setup is a little different from that API. I would suggest sticking to Datastore e2e. I will close this issue for now. Because from API perspective everything is working fine. If you have issue while doing Datastore, thats on back of this, Please post more info and I can reopen the issue for you.

**Comment by Astrophe** [comment]
Hi there, I am having a similar but slightly different issue. My api call is returning a package everytime I call my mutation:

`                const createdOrder = await API.graphql(graphqlOperation(createOrder, {input: this.state.order}))
`
Console log everytime:
![image](https://user-images.githubusercontent.com/38767935/108216838-e8868200-7100-11eb-8ffc-63b109a4bb85.png)

However, my dynamoDB table is only updated intermittently (around 70%) of the time. I am never getting any errors, and everything always looks good on the client side, except that my call to list orders isn't returning the newly created order (as it isn't getting posted to the DB.

Please let me know if you need anything from me to diagnose.
