### ISSUE TITLE
Grapqhl list query combining filter and limit does not work as expected

### ISSUE THREAD

**Issue by neilime** [aws-amplify/amplify-js#5995]
**Describe the bug**

Hi,

Let's assume that I have query a list using "filter" and "limit" variable : 

```graphql
query ListItems($filter: ModelItemFilterInput, $limit: Int, $nextToken: String) {
    listItems(filter: $filter, limit: $limit, nextToken: $nextToken) {
        items {
            id
            label
        }
        nextToken
    }
}
```

With those variables: 
```js
{
  limit: 20,
  filter: {
    label: { eq: 'test' }
  }
}
```

Let's assume that I have hundreds of items in DynamoDB but only 10 are matching to the expected filter

When I execute the query, I expect to receive an array of 10 items

However, I receive an array of items with variable size and I have to paginate using `nextToken` to retrieve all of the 10 expected items.

Is that behaviour the normal one ?

What am I supposed to do to have the expected behaviour ?

**Comment by ashika01** [comment]
@neilime That is the behavior right now. We have a feature request with the [CLI team](aws-amplify/amplify-cli#1865). That talks about this and you can brief your usecase there .
