### ISSUE TITLE
AWS amplify StorageClass not supporting copyObject while AWS S3 SDK does

### ISSUE THREAD

**Issue by rpostulart** [aws-amplify/amplify-js#5998]
I need a feature where I can copy file within a bucket to another 'folder' 

This option is provided by https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#copyObject-property

but not with https://aws-amplify.github.io/amplify-js/api/classes/storageclass.html

Can we make this functionality available to AWS Amplify

**Comment by entraigas** [comment]
Any update on this matter?
I need this feature too.

**Comment by arelaxend** [comment]
Up!

**Comment by DIntriglia** [comment]
Yes Please!

**Comment by eioo** [comment]
NEED THIS

**Comment by argjent-eduongo** [comment]
Any update on this?

**Comment by jamesaucode** [comment]
Hey folks, 
Wanted to provide an update to you all. We are currently researching and looking into ways to implement this to the Storage class. 

Thanks!
