### ISSUE TITLE
PubSub not working: No Cognito Federated Identity pool provided

### ISSUE THREAD

**Issue by damianrr** [aws-amplify/amplify-js#5999]
Hello, 

I'm following this guide: https://docs.amplify.aws/lib/pubsub/getting-started/q/platform/js for subscribing to IoT messages from my web app. I:
1. imported and configured the classes as stated in the guide:
```
import Amplify, { PubSub } from 'aws-amplify';
import { AWSIoTProvider } from '@aws-amplify/pubsub/lib/Providers';
// Apply plugin with configuration
Amplify.addPluggable(new AWSIoTProvider({
     aws_pubsub_region: '<YOUR-IOT-REGION>',
     aws_pubsub_endpoint: 'wss://xxxxxxxxxxxxx.iot.<YOUR-IOT-REGION>.amazonaws.com/mqtt',
   }));
```
2. Created the IAM Policy and made sure it has sufficient permissions

Now, I'm getting this error on my console: 
```
AWSIotProvider.ts:18 Uncaught (in promise) No Cognito Federated Identity pool provided
```
If I: 
```
    Auth.currentCredentials().then((info) => {
      console.log(info.data.IdentityId);
    }).catch(e => console.log(e))
```
I get exactly the same error.

Does anyone knows how I could fix this?

PS: Nowhere in the docs I see having federated identities as a requirement for using PubSub functionality. 
I'm not using federated identities and would like to keep using my user pool for authentication.

Thanks!

**Comment by ashika01** [comment]
@damianrr I thinking the docs is missing few step.

Your code should look like this 

```
import Amplify, { PubSub } from 'aws-amplify';
import { AWSIoTProvider } from '@aws-amplify/pubsub';
import aws_exports from './aws-exports';

// Apply AWSIoTProvider plugin with configuration
Amplify.addPluggable(new AWSIoTProvider({
  aws_pubsub_region: 'XXXXX',
  aws_pubsub_endpoint: 'XXXXX',
}));

Amplify.configure(aws_exports);
```

- Importing from `lib/provider` could be one bit.
- Amplify configure bit might be another missing piece.

Could you confirm if you have this setup?

**Comment by damianrr** [comment]
Hey @ashika01 yes, I do have my `Amplify.configure(aws_exports);` in place, just like in your snippet I changed the import to `import { AWSIoTProvider } from '@aws-amplify/pubsub';` and I still get the same error.

**Comment by damianrr** [comment]
if I do this:
```
Auth.currentCredentials()                                                                                     
    .then(info => {                                                                                             
      console.log("success! ", info.data.IdentityId);                                                           
    })                                                                                                          
    .catch(e => console.log("error: ", e));  
```
I get the same error. So it seems like an auth thing, not IoT. Still clueless about it.

Any help would be appreciated.

**Comment by ashika01** [comment]
yeah its auth for sure. Thats why I thought You are missing the config. Could you post you `aws-exports`

**Comment by damianrr** [comment]
I had my auth as:  `User Sign-Up & Sign-In only (Best used with a cloud API only)` and did an `amplify auth update` and selected: `User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage features for images or other content, Analytics, and more)`
And it moved! (Not sure if that change would break other parts of the system). Now I'm having a more IoT related error, namely:

```
{provider: AWSIoTProvider, error: {…}}
provider: AWSIoTProvider
region: (...)
endpoint: (...)
clientId: (...)
clientsQueue: (...)
isSSLEnabled: (...)
options: (...)
_config: {aws_project_region: "us-east-1", aws_cognito_identity_pool_id: "XXX", aws_cognito_region: "us-east-1", aws_user_pools_id: "XXX", aws_user_pools_web_client_id: "XXX", …}
_clientsQueue: ClientsQueue {promises: Map(1)}
_topicObservers: Map(1) {"ontario-demand" => Set(1)}
_clientIdObservers: Map(1) {"XXXX" => Set(1)}
__proto__: MqttOverWSProvider
error:
invocationContext: undefined
errorCode: 8
errorMessage: "AMQJS0008I Socket closed."
__proto__: Object
__proto__: Object
```
Any ideas on this one?

**Comment by ashika01** [comment]
I think that might be it. From what I tested , PubSub with Auth is working. Could you try the setup on a sample app. 

Setup your federation following the docs here - https://docs.amplify.aws/lib/auth/social/q/platform/js

Followed by setup PubSub based of this - https://github.com/aws-amplify/amplify-js/issues/5999#issuecomment-638521724
