### ISSUE TITLE
"Missing credentials in config" error when using Auth.currentCredentials()

### ISSUE THREAD

**Issue by charlie0077** [aws-amplify/amplify-js#6002]
**Describe the bug**
Hi, We are using Amplify to manage the coginto credentials and once a while we will get this error when using the credentials: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1

It does not happen often, happens once a day for us. Very hard to trigger. 

The way we use it is like this:
```

const getDocumentClient = (): Promise<DocumentClient> =>
    Auth.currentCredentials().then(
        (credentials) =>
            new DynamoDB.DocumentClient({
                region: REGION,
                credentials: Auth.essentialCredentials(credentials),
            })
    )

export const getItemFromSettingsTable = async (
    Key: KeyType
): Promise<DocumentClient.GetItemOutput> => {
    const params = {
        TableName: xxx,
        Key,
    }

    const client = await getDocumentClient()

    return client.get(params).promise()
}

```
According to the stacktrace, we are getting the error when call the getItemFromSettingsTable. 

**To Reproduce**
Unfortunately this is hard to reproduce. I don't know a specific formula to trigger it.

**Comment by ashika01** [comment]
@charlie0077 You dont see this if you are not using `Auth.currentCredentials()`? This is looks like its not something in Amplify. I see similar issues reported to aws-sdk team in the past - 
- https://github.com/aws/aws-sdk-js/issues/1955
- https://github.com/aws/aws-sdk-js/issues/1483

I would suggest you identify where its coming from and report the issue to aws-sdk git repo.

**Comment by ashika01** [comment]
Closing this issue via my previous comment. Let us know if its something on amplify and I will reopen the issue.
