### ISSUE TITLE
DataStore observe single item by ID doesn't seem to be working anymore

### ISSUE THREAD

**Issue by mdoesburg** [aws-amplify/amplify-js#6003]
**Describe the bug**
Since the new DataStore update (tested this on DataStore 2.2.1), observing a single item by ID doesn't seem to be working anymore. 

**To Reproduce**
1. Create an Amplify app for React Native.
2. Don't use the new DataStore.start(), instead try to observe a model with a specific ID. (make sure a Note with the specified ID exists)

Note: When I remove the ID, it works fine. Every time before testing I cleared the DataStore with DataStore.clear() to make sure there was not data in the store yet.

**Expected behavior**
I expect to be able to observe a model with a specific ID. Just like how is documented in the [docs](https://docs.amplify.aws/lib/datastore/real-time/q/platform/js).

**Code Snippet**
```js
import React from "react";
import { Amplify } from "@aws-amplify/core";
import { DataStore, Predicates } from "@aws-amplify/datastore";
 
import awsConfig from "./aws-exports";
import { Note } from "./models";
 
Amplify.configure(awsConfig);
 
const id = '69ddcb63-7e4a-4325-b84d-8592e6dac07b';

function App() { 
  useEffect(() => {
    const subscription = DataStore.observe(Note, id).subscribe(({ element, ...x }) => {
      console.log(element);
    });
 
    return () => subscription.unsubscribe();
  }, []);
 
  return null;
}
 
export default App;
```

**Comment by nubpro** [comment]
Quick question, is the same when you use Hub.listener on Datastore?

Basically, you would query your specific data only when the client is synced up.
https://github.com/aws-amplify/amplify-js/issues/5991#issuecomment-638278364

Does it yield the same issue?
Cuz' we're evaluating upgrading to the newer version.

Thanks a bunch!

**Comment by mdoesburg** [comment]
@nubpro As long as your not trying to observe a single item by ID, you should be fine. All the code samples shown by @manueliglesias in the issue you linked work. It just doesn't seem to work when you pass an ID into the `DataStore.observe` method like so:

```js
DataStore.observe(Model, id).subscribe(...
```

**Comment by ashika01** [comment]
@mdoesburg What is the error that you are seeing? I have no problem with observe by id using `@aws-amplify/datastore@latest`

Here is my sample code, my useEffect looks something like this

```
useEffect(() => {
		let subscription = undefined;

		const id = '9460d25b-685b-45d7-8d81-7c5adc80a6cd';

		subscription = DataStore.observe(Blog, id).subscribe(
			({ element, ...x }) => {
				console.log('data', element);
				setBlogs(element);
			}
		);

		return () => {
			if (subscription) {
				subscription.unsubscribe();
			}
		};
	}, []);
```

my render UI is simple 
```
<button
	onClick={async () => {
		const query = await DataStore.query(
			Blog,
			'9460d25b-685b-45d7-8d81-7c5adc80a6cd'
		);
		const owner = await DataStore.query(
			BlogOwner,
			'499f8947-7ba3-4f8a-b4a1-88c611dc2843'
		);

		await DataStore.save(
			Blog.copyOf(query, (updated) => {
				updated.name = 'blog updated 1';
				updated.owner = o;
			})
		);
		//console.log('result', query);
	}}
>
	update blog id
</button>
```

**Comment by ashika01** [comment]
Preview of whats happening for me. Let me know if I am missing anything

![ds](https://user-images.githubusercontent.com/35131273/83801663-616ea800-a65e-11ea-9ab7-97138acfd887.gif)

**Comment by mdoesburg** [comment]
@ashika01 Ok, so it seems like the subscription is now actually showing an insert, even when I pass in an ID: 
```js
opType: "INSERT"
```

However, when I query right after the insert, I get no data. Here's the code of the custom React hook I wrote:
```js
export const useSubscriptionById = (model, id) => {
  const [data, setData] = useState();

  useEffect(() => {
    if (!id) {
      return;
    }

    let subscription;

    const dataQuery = async () => {
      const _data = await DataStore.query(model, id);
      console.log(id, _data);
      setData(_data);
    };

    dataQuery();

    subscription = DataStore.observe(model, id).subscribe((msg) => {
      console.log(msg);
      dataQuery();
    });

    return () => {
      if (subscription) {
        subscription.unsubscribe();
      }
    };
  }, [id, model]);

  return data;
};
```

**Comment by ashika01** [comment]
@mdoesburg You wouldnt get any subscription data on query since the query happens in the local storage (indexeddb) and not to appsync backend. You would get subscription data only in cases of datastore insert/update/delete

**Comment by mdoesburg** [comment]
@ashika01 If I query something right after it has been inserted, shouldn't I get the data?

**Comment by mdoesburg** [comment]
@ashika01 Running a query right after the subscription receives a message is literally something shown in the [Example React Native Application](https://docs.amplify.aws/lib/datastore/how-it-works/q/platform/js#example-react-native-application) in the documentation, and it used to work prior to DataStore version 2.2.0.

**Comment by ashika01** [comment]
@mdoesburg Your query result should have the inserted data. But it wouldn't trigger a subscription event right? Sorry if I misunderstood your question. The whole query operation happens in local storage.

**Comment by mdoesburg** [comment]
@ashika01 Yes, sorry for the confusion. I don't expect a subscription event after a query. I am observing a model with a certain ID, once I receive a message I run a query against the DataStore for that model with the same ID, but I am not receiving any data.

**Comment by mdoesburg** [comment]
@ashika01 I see the following in my console:

```
{opType: "INSERT", element: {…}, condition: undefined, model: ƒ}
```

```
54802 undefined
```

**Comment by mdoesburg** [comment]
@ashika01 I guess the issue I am having is literally this: "DataStore queries don't do anything on the first load of the application". So closing this in favor of: https://github.com/aws-amplify/amplify-js/issues/5991

**Comment by ashika01** [comment]
There is a change out in unstable for that now.

**Comment by mdoesburg** [comment]
@ashika01 Thanks for the heads up!
