### ISSUE TITLE
Subscription msg element is not a Model

### ISSUE THREAD

**Issue by slewis77** [aws-amplify/amplify-js#6006]
**Describe the bug**
Subscribe element is not a Model, so can't use it directly

**To Reproduce**
Create a Datastore project with a simple model and create a subscription
When using DataStore.query the returned data is an array of Models
This means you can edit the Model by creating a copyOf and use it in a DataStore.save

If you get notification that the data has changed, the subscription msg contains the update in the element field.

This element field is not a model, so you can't use it in the same way as the query response. I.e. you can't do a copyOf. Instead you must either re-query for that data item or copy the updated fields individually.

**Expected behavior**
The subscription msg contains the update element of type Model

**Code Snippet**
Please provide a code snippet or a link to sample code of the issue you are experiencing to help us reproduce the issue. (Be sure to remove any sensitive data)

**What is Configured?**
    "@aws-amplify/auth": "^3.2.10",
    "@aws-amplify/core": "^3.3.2",
    "@aws-amplify/datastore": "^2.2.2",
    "@aws-amplify/ui-react": "^0.2.8",

**Comment by slewis77** [comment]
Just to add, this is new behaviour since datastore 2.2.1 (which otherwise has some great updates!)

**Comment by ashika01** [comment]
@selwis77 Could you paste you app code or simple sample code so I can reproduce this?

**Comment by slewis77** [comment]
I’ll put something together this weekend. It’s readily reproducible with any subscription using the latest version of datastore

**Comment by slewis77** [comment]
This can be closed as I can't recreate it. I tried on 2.2.2 and 2.2.1 and the subscriptions return Models. I wonder if it was a quirk of upgrading an exisitng project, not sure, anyway, doens't appear to be a real issue.

Thanks.
