### ISSUE TITLE
ERROR in ../node_modules/@aws-amplify/datastore/lib-esm/types.d.ts:73:38 - error TS2304: Cannot find name 'Omit'.

### ISSUE THREAD

**Issue by ender-code** [aws-amplify/amplify-js#6008]
**Describe the bug**
Following docs here: https://aws-amplify.github.io/docs/js/tutorials/building-ionic-4-apps/
 
Error:
`ERROR in ../node_modules/@aws-amplify/datastore/lib-esm/types.d.ts:73:38 - error TS2304: Cannot find name 'Omit'. function getJSType(scalar: keyof Omit<typeof GraphQLScalarType, 'getJSType'>): 'string' | 'number' | 'boolean';`

**To Reproduce**
Following the tutorial, went upto the third step (Implemented CRUD, Installed AWS Amplify, Added Amplify Analytics and Auth) when ran the app at the end of it "ionic serve" and gave the error and failed to compile

**Expected behavior**
App to compile

**Code Snippet**
```
\\ package.json
"dependencies": {
    "@angular/common": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.11.10",
    "aws-amplify": "^3.0.13",
    "aws-amplify-angular": "^5.0.13",
    "core-js": "^2.5.4",
    "rxjs": "~6.5.1",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.801.2",
    "@angular-devkit/build-angular": "~0.801.2",
    "@angular-devkit/core": "~8.1.2",
    "@angular-devkit/schematics": "~8.1.2",
    "@angular/cli": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@ionic/angular-toolkit": "~2.0.0",
    "@ionic/lab": "1.0.23",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.12.0",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.4",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.12.0",
    "typescript": "^3.4.5"
  },
```

**Screenshots**
Compile Error:
![aws_amplify_error](https://user-images.githubusercontent.com/66418784/83759680-88929d00-a691-11ea-83ea-638957637415.PNG)

Ionic Info:
![aws_amplify_ionic_info](https://user-images.githubusercontent.com/66418784/83761135-89c4c980-a693-11ea-94bf-2a700b4aa586.PNG)

**What is Configured?**
Code Editor: VS Code 1.45.0 (TypeScript 3.8.3)
System: Windows 10

**Additional context**
I tried this solution
https://stackoverflow.com/questions/56440272/cannot-find-name-omit-in-typescript
by changing the Typescript  version to "^3.5.1" but got an new compile error that typescript should be between 3.4 to 3.5
P.S. First time posting here. Please do mention if you need any additional data

**Comment by mluis** [comment]
+1

**Comment by herath** [comment]
+1

**Comment by Jun711** [comment]
I updated aws-amplify from 1.1.19 to 3.0.18 in my Angular 7 app and got similar errors. 

```
ERROR in node_modules/@aws-amplify/datastore/lib-esm/types.d.ts(73,38): error TS2304: Cannot find name 'Omit'.
node_modules/@aws-amplify/datastore/lib-esm/types.d.ts(84,69): error TS2304: Cannot find name 'Omit'.
node_modules/@aws-amplify/datastore/lib-esm/types.d.ts(99,17): error TS2304: Cannot find name 'Omit'.
node_modules/@aws-amplify/datastore/lib-esm/types.d.ts(116,36): error TS2304: Cannot find name 'Omit'.
node_modules/@aws-amplify/datastore/lib-esm/types.d.ts(120,39): error TS2304: Cannot find name 'Omit'.
```

**Comment by Jun711** [comment]
@ender-code 
I am not sure if you can upgrade Angular to Angular 9. I could in stall aws-amplify 3.0.18 in my Angular 9 project but not Angular 7.

**Comment by harrysolovay** [comment]
@ender-code can you please paste your tsconfig into this issue?

**Comment by harrysolovay** [comment]
Just a hunch: can you try specifying a resolution for TypeScript in your `package.json`?

```json
{
  ...
  "resolutions": {
    "typescript": "3.8.3"
  },
  ...
}
```

**Comment by richiewebgate** [comment]
same problem here when I tried to use amplify for AppSync APIs instead of REST. 
I'm getting the impression that using amplify in angular projects is a risk for upgradeability.

**Comment by snieves-mh** [comment]
I am having the same problem as the original poster. I'm working on an Angular 8 application and trying to use amplify to provide login functionality. I upgraded typescript to 3.5.3 but that didn't work. Does anyone know what version of Typescript is needed?
