### ISSUE TITLE
Not able to receive AWS Token (ID Token, Access Token, Refresh Token) & Federation Login

### ISSUE THREAD

**Issue by bigzidane** [aws-amplify/amplify-js#6013]
**Describe the bug**
Not able to receive AWS Token (ID Token, Access Token, Refresh Token) after Auth.federatedSignIn with 'facebook' provider

**To Reproduce**

1. Auth.federatedSignIn
2. Auth.currentAuthenticatedUser

**Expected behavior**
I'm expecting AWS token so I can use it to call AWS Services accordingly

**Code Snippet**
```
Auth.federatedSignIn(
    domain,
    {
        token,
        identity_id, // Optional
        expires_at: expiresIn * 1000 + new Date().getTime() // the expiration timestamp
    },
    user
).then(cred => {
    // If success, you will get the AWS credentials
    console.log(cred);
    return Auth.currentAuthenticatedUser();
}).then(user => {
    // If success, the user object you passed in Auth.federatedSignIn
    console.log(user);
}).catch(e => {
    console.log(e)
});
```

**Screenshots**

**What is Configured?**
```
  Auth: {
    identityPoolId: 'us-east-1:xxxxxx',
    region: 'us-east-1'
    userPoolId: 'us-east-1_xxxxxx',
    userPoolWebClientId: 'xxxxxx',  },

```
I have searched a lot but not able to find an answer for it. Hope you guys can help me out.

**Comment by amhinson** [comment]
@bigzidane Have you followed this example in the documentation about [Identity Pool Federation with Facebook](https://docs.amplify.aws/lib/auth/advanced/q/platform/js#facebook-sign-in-react)?

**Comment by mauerbac** [comment]
Hey @bigzidane - we haven't heard back so we will close this issue. Please let us know if you need further help.
