### ISSUE TITLE
React Native. Got SerializationException" after Auth.signUp

### ISSUE THREAD

**Issue by Alegero7** [aws-amplify/amplify-js#6014]
App.js :
`
import Amplify, { Auth } from 'aws-amplify';
Amplify.configure({

    Auth: {

      region: 'eu-central-1',
      identityPoolRegion: "eu-central-1",
      userPoolId: 'eu-central-1_xxxxxx',
      userPoolWebClientId: 'xxxxxx'

    }
  });
`

SignUp.js:
`import { Auth } from 'aws-amplify';

async signUp(email: string, password: string): Promise<void> {

            this._logger.debug('Processing sign up for {userEmail}', email);
            try {

                await Auth.signUp({ username: email, password: password, attributes: { email } });
                this._logger.info('Finished processing sign up for {userEmail}', email);
                await this._navigationService.navigate('Login');

            } catch (error) {
                this._logger.error('An error occured while signing up user {userEmail}', error, email);
                throw error;
            }
        }
`

As a result: code: "SerializationException", name: "SerializationException", message: null

**Comment by amhinson** [comment]
@Alegero7 Could you provide an example of the email you are using to sign up? Also, does the password you are providing anything other than the [default allowed characters](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-policies.html)?

**Comment by Alegero7** [comment]
@amhinson 
juking89@gmail.com
Jane3105!

**Comment by Alegero7** [comment]
Hi @amhinson Do you have any ideas what is going wrong?

**Comment by Alegero7** [comment]
Here I got error from file Auth.js: 
_this.userPool.signUp(username, password, attributes, validationData, function (err, data) {
                if (err) {
                    dispatchAuthEvent('signUp_failure', err, username + " failed to signup");
                    reject(err);
                }
                else {
                    dispatchAuthEvent('signUp', data, username + " has signed up successfully");
                    resolve(data);
                }
            }, clientMetadata);
        });

**Comment by amhinson** [comment]
Could you share more of error you are seeing in the console?

Also, could you run this command to provide your project environment?
```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

**Comment by Alegero7** [comment]
System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 112.70 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.21.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 83.0.4103.97
    Firefox: 51.0
    Safari: 13.1.1
  npmGlobalPackages:
    @aws-amplify/cli: 4.21.1
    awsmobile-cli: 1.1.7
    cordova: 9.0.0
    eslint-config-airbnb-base: 13.1.0
    eslint-plugin-import: 2.16.0
    eslint: 5.12.1
    expo-cli: 2.14.0
    firebase-tools: 6.3.1
    ionic: 4.12.0
    ios-deploy: 1.9.4
    ios-sim: 8.0.1
    n: 6.5.1
    node-gyp: 7.0.0
    node-pre-gyp: 0.15.0
    npm: 6.14.4
    react-native-cli: 2.0.1
    stable: 0.1.8

**Comment by Alegero7** [comment]
Also I found that cognitoUserPoll.storage is a function. Is this ok?

**Comment by Alegero7** [comment]
@amhinson 

System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 1.01 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.21.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 83.0.4103.97
    Firefox: 51.0
    Safari: 13.1.1
  npmPackages:
    @babel/core: ^7.4.5 => 7.10.2 
    @babel/preset-env: ^7.4.5 => 7.10.2 
    @blepi/data-model: =0.48.13 => 0.48.13 
    @econsor-mobile/common-database: ^0.3.2 => 0.3.2 
    @econsor-mobile/firebase: ^0.3.3 => 0.3.6 
    @econsor-mobile/guard: ^0.3.1 => 0.3.1 
    @econsor-mobile/logging: ^0.5.0 => 0.5.4 
    @econsor-mobile/react-native: =0.21.0 => 0.21.0 
    @firebase/app: ^0.4.0 => 0.4.26 
    @firebase/app-types: ^0.4.0 => 0.4.9 
    @firebase/database: ^0.4.0 => 0.4.12 
    @firebase/util: ^0.2.14 => 0.2.48 
    @react-native-community/async-storage: ^1.7.1 => 1.11.0 
    @react-native-community/datetimepicker: ^2.1.0 => 2.4.0 
    @react-native-community/geolocation: ^2.0.2 => 2.0.2 
    @react-native-community/netinfo: ^5.9.2 => 5.9.2 
    amazon-cognito-identity-js: ^4.3.1 => 4.3.1 
    aws-amplify: ^3.0.17 => 3.0.17 
    aws-amplify-react-native: ^4.2.0 => 4.2.0 
    babel-eslint: ^10.0.2 => 10.1.0 
    babel-jest: 24.8.0 => 24.8.0 
    babel-preset-react-native: ^5.0.2 => 5.0.2 
    blepi-core: =0.9.11 => 0.9.11 
    card-validator: ^6.1.0 => 6.2.0 
    chai: ^4.2.0 => 4.2.0 
    color: 3.1.1 => 3.1.1 
    eslint: ^5.16.0 => 5.16.0 
    eslint-config-airbnb: ^17.1.0 => 17.1.1 
    eslint-plugin-flowtype: ^3.6.1 => 3.13.0 
    eslint-plugin-import: ^2.17.2 => 2.21.2 
    eslint-plugin-jsx-a11y: ^6.2.1 => 6.2.3 
    eslint-plugin-react: ^7.13.0 => 7.20.0 
    eslint-plugin-react-native: ^3.7.0 => 3.8.1 
    firebase: ^4.6.2 => 4.13.1 
    flow-bin: ^0.98.0 => 0.98.1 
    iban: ^0.0.12 => 0.0.12 
    jest: 24.7.1 => 24.7.1 
    jest-expo: ^32.0.0 => 32.0.1 
    jest-react-native: 18.0.0 => 18.0.0 
    jetifier: ^1.6.4 => 1.6.5 
    license-checker: ^25.0.1 => 25.0.1 
    lodash: ^4.13.1 => 4.17.15 
    mocha: ^6.1.4 => 6.2.3 
    moment: ^2.19.2 => 2.26.0 
    native-base: ^2.13.12 => 2.13.12 
    numeral: ^2.0.6 => 2.0.6 
    prop-types: ^15.6.0 => 15.7.2 
    react: ^16.13.1 => 16.13.1 
    react-devtools: 3.5.0-alpha.0 => 3.5.0-alpha.0 
    react-native: ^0.60.5 => 0.60.6 
    react-native-autocomplete-input: ^4.0.0 => 4.2.0 
    react-native-autolink: ^1.8.1 => 1.9.2 
    react-native-branch: =4.2.1 => 4.2.1 
    react-native-calendars: ^1.74.0 => 1.294.0 
    react-native-cli: ^2.0.1 => 2.0.1 
    react-native-datepicker: ^1.6.0 => 1.7.2 
    react-native-elements: ^1.2.3 => 1.2.7 
    react-native-fast-image: ^7.0.2 => 7.0.2 
    react-native-fcm: ^16.2.4 => 16.2.4 
    react-native-gesture-handler: ^1.4.1 => 1.6.1 
    react-native-gifted-chat: 0.8.0 => 0.8.0 
    react-native-google-places-autocomplete: ^1.3.9 => 1.7.1 
    react-native-iap: =3.4.12 => 3.4.12 
    react-native-image-crop-picker: ^0.25.2 => 0.25.3 
    react-native-keyboard-aware-scroll-view: ^0.8.0 => 0.8.0 
    react-native-keychain: ^6.1.1 => 6.1.1 
    react-native-loading-spinner-overlay: ^1.0.1 => 1.1.0 
    react-native-localize: ^1.1.4 => 1.4.0 
    react-native-maps: =0.26.1 => 0.26.1 
    react-native-material-bottom-navigation: =0.5.3 => 0.5.3 
    react-native-media-controls: ^1.1.1 => 1.1.1 
    react-native-media-meta: ^0.0.10 => 0.0.10 
    react-native-modal-dropdown: ^0.6.2 => 0.6.2 
    react-native-multi-slider: ^0.3.5 => 0.3.6 
    react-native-navbar: ^2.1.0 => 2.1.0 
    react-native-numeric-input: ^1.8.3 => 1.8.3 
    react-native-parallax-scroll-view: ^0.21.3 => 0.21.3 
    react-native-progress-circle: ^2.0.1 => 2.1.0 
    react-native-router-flux: ^4.2.0 => 4.2.0 
    react-native-scrollable-tab-view: 0.10.0 => 0.10.0 
    react-native-star-rating: ^1.1.0 => 1.1.0 
    react-native-swiper: ^1.5.12 => 1.6.0 
    react-native-thumbnail-grid: ^0.3.0 => 0.3.0 
    react-native-vector-icons: ^6.6.0 => 6.6.0 
    react-native-video: ^5.0.0 => 5.0.2 
    react-native-video-helper: =1.4.4 => 1.4.4 
    react-native-video-player: ^0.10.0 => 0.10.0 
    react-native-webview: ^7.4.3 => 7.6.0 
    react-navigation: =3.9.1 => 3.9.1 
    react-test-renderer: 16.8.6 => 16.8.6 
    reactotron: ^0.9.0 => 0.9.0 
    reactotron-react-native: ^5.0.0 => 5.0.0 
    rn-fetch-blob: 0.12.0 => 0.12.0 
    rn-image-picker: =2.2.3 => 2.2.3 
    rn-in-app-notification: 3.0.0 => 3.0.0 
    rn-sliding-up-panel: ^2.2.0 => 2.4.2 
    url-parse: ^1.4.7 => 1.4.7 
    uuid: ^3.1.0 => 3.4.0 
  npmGlobalPackages:
    @aws-amplify/cli: 4.21.1
    awsmobile-cli: 1.1.7
    cordova: 9.0.0
    eslint-config-airbnb-base: 13.1.0
    eslint-plugin-import: 2.16.0
    eslint: 5.12.1
    expo-cli: 2.14.0
    firebase-tools: 6.3.1
    ionic: 4.12.0
    ios-deploy: 1.9.4
    ios-sim: 8.0.1
    n: 6.5.1
    node-gyp: 7.0.0
    node-pre-gyp: 0.15.0
    npm: 6.14.4
    react-native-cli: 2.0.1
    stable: 0.1.8

**Comment by Alegero7** [comment]
@amhinson I have found error in amazon-cognito-indentity-js Client.js file. Maybe It will be helpfull

![Screen Shot 2020-06-11 at 5 26 13 PM](https://user-images.githubusercontent.com/66474730/84398612-d61a8700-ac08-11ea-85b2-e71046e34070.png)

**Comment by amhinson** [comment]
Are you using any Lambda Triggers on the User Pool?

Could you describe the steps you took when setting up the Auth category?
i.e. `amplify add auth` with default configuration

**Comment by Alegero7** [comment]
@amhinson Hi, I have fixed this issue. aws-amplify is not working with node module rn-fetch-blob 0_0 I have removed it and api is working now...

**Comment by amhinson** [comment]
Thats good to hear you got it working! I'll close this issue for now, but we will make note of `rn-fetch-blob`.
