### ISSUE TITLE
No current user while I am in app (using aws-amplify-react-native) with Auth.currentSession()

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#6015]
Frequently facing No current user while I am in app. Here I am using Auth.currentSession()  to get the token and successfully inside the app.

Why the above issue is getting. Any thoughts on this? 

Using latest aws-amplify and aws-amplify-react-native .

```
"aws-amplify": "^3.0.11",
 "aws-amplify-react-native": "^4.1.2",
 "aws-sdk": "^2.681.0",
```

**Comment by amhinson** [comment]
@nihp Could you provide some reproduction steps so we could replicate this behavior you're seeing?

**Comment by nihp** [comment]
Just I have launch the app and navigating from a screen to another screen

I have using Authenticator from the aws-amplify-react-native
 
`ConsoleLogger.ts:99 [DEBUG] 53:23.994 AuthClass - currentSession: No current user`

```
yarn list v1.22.4
├─ @aws-amplify/analytics@3.1.12
├─ @aws-amplify/api-graphql@1.0.14
├─ @aws-amplify/api-rest@1.0.14
├─ @aws-amplify/api@3.1.12
├─ @aws-amplify/auth@3.2.9
├─ @aws-amplify/cache@3.1.12
├─ @aws-amplify/core@3.2.9
├─ @aws-amplify/datastore@2.1.2
├─ @aws-amplify/interactions@3.1.12
├─ @aws-amplify/predictions@3.1.12
├─ @aws-amplify/pubsub@3.0.13
├─ @aws-amplify/storage@3.2.2
├─ @aws-amplify/ui@2.0.2
├─ @aws-amplify/xr@2.1.12
├─ @aws-crypto/crc32@1.0.0-alpha.0
├─ @aws-crypto/ie11-detection@1.0.0-alpha.0
├─ @aws-crypto/sha256-browser@1.0.0-alpha.0
├─ @aws-crypto/sha256-js@1.0.0-alpha.0
├─ @aws-crypto/supports-web-crypto@1.0.0-alpha.0
├─ @aws-sdk/abort-controller@1.0.0-gamma.1
├─ @aws-sdk/chunked-blob-reader-native@1.0.0-gamma.1
├─ @aws-sdk/chunked-blob-reader@1.0.0-gamma.1
├─ @aws-sdk/client-cognito-identity@1.0.0-gamma.2
├─ @aws-sdk/client-comprehend@1.0.0-gamma.2
├─ @aws-sdk/client-firehose@1.0.0-gamma.2
├─ @aws-sdk/client-kinesis@1.0.0-gamma.2
├─ @aws-sdk/client-lex-runtime-service@1.0.0-gamma.2
├─ @aws-sdk/client-personalize-events@1.0.0-gamma.2
├─ @aws-sdk/client-pinpoint@1.0.0-gamma.2
├─ @aws-sdk/client-polly@1.0.0-gamma.2
├─ @aws-sdk/client-rekognition@1.0.0-gamma.2
├─ @aws-sdk/client-s3@1.0.0-gamma.2
├─ @aws-sdk/client-textract@1.0.0-gamma.2
├─ @aws-sdk/client-translate@1.0.0-gamma.2
├─ @aws-sdk/config-resolver@1.0.0-gamma.1
├─ @aws-sdk/credential-provider-cognito-identity@1.0.0-gamma.2
├─ @aws-sdk/credential-provider-env@1.0.0-gamma.1
├─ @aws-sdk/credential-provider-imds@1.0.0-gamma.1
├─ @aws-sdk/credential-provider-ini@1.0.0-gamma.1
├─ @aws-sdk/credential-provider-node@1.0.0-gamma.1
├─ @aws-sdk/credential-provider-process@1.0.0-gamma.1
├─ @aws-sdk/eventstream-marshaller@1.0.0-gamma.1
├─ @aws-sdk/eventstream-serde-browser@1.0.0-gamma.1
├─ @aws-sdk/eventstream-serde-config-resolver@1.0.0-gamma.1
├─ @aws-sdk/eventstream-serde-node@1.0.0-gamma.1
├─ @aws-sdk/fetch-http-handler@1.0.0-gamma.2
├─ @aws-sdk/hash-blob-browser@1.0.0-gamma.1
├─ @aws-sdk/hash-node@1.0.0-gamma.1
├─ @aws-sdk/hash-stream-node@1.0.0-gamma.1
├─ @aws-sdk/invalid-dependency@1.0.0-gamma.1
├─ @aws-sdk/is-array-buffer@1.0.0-gamma.1
├─ @aws-sdk/md5-js@1.0.0-gamma.1
├─ @aws-sdk/middleware-apply-body-checksum@1.0.0-gamma.1
├─ @aws-sdk/middleware-bucket-endpoint@1.0.0-gamma.1
├─ @aws-sdk/middleware-content-length@1.0.0-gamma.1
├─ @aws-sdk/middleware-expect-continue@1.0.0-gamma.1
├─ @aws-sdk/middleware-header-default@1.0.0-gamma.1
├─ @aws-sdk/middleware-host-header@1.0.0-gamma.1
├─ @aws-sdk/middleware-location-constraint@1.0.0-gamma.1
├─ @aws-sdk/middleware-retry@1.0.0-gamma.1
├─ @aws-sdk/middleware-sdk-s3@1.0.0-gamma.1
├─ @aws-sdk/middleware-serde@1.0.0-gamma.1
├─ @aws-sdk/middleware-signing@1.0.0-gamma.1
├─ @aws-sdk/middleware-ssec@1.0.0-gamma.1
├─ @aws-sdk/middleware-stack@1.0.0-gamma.1
├─ @aws-sdk/middleware-user-agent@1.0.0-gamma.1
├─ @aws-sdk/node-http-handler@1.0.0-gamma.1
├─ @aws-sdk/property-provider@1.0.0-gamma.1
├─ @aws-sdk/protocol-http@1.0.0-gamma.1
├─ @aws-sdk/querystring-builder@1.0.0-gamma.1
├─ @aws-sdk/querystring-parser@1.0.0-gamma.1
├─ @aws-sdk/region-provider@1.0.0-gamma.1
├─ @aws-sdk/s3-request-presigner@1.0.0-gamma.1
├─ @aws-sdk/service-error-classification@1.0.0-gamma.1
├─ @aws-sdk/shared-ini-file-loader@1.0.0-gamma.1
├─ @aws-sdk/signature-v4@1.0.0-gamma.1
├─ @aws-sdk/smithy-client@1.0.0-gamma.1
├─ @aws-sdk/types@1.0.0-gamma.1
├─ @aws-sdk/url-parser-browser@1.0.0-gamma.1
├─ @aws-sdk/url-parser-node@1.0.0-gamma.1
├─ @aws-sdk/util-base64-browser@1.0.0-gamma.1
├─ @aws-sdk/util-base64-node@1.0.0-gamma.1
├─ @aws-sdk/util-body-length-browser@1.0.0-gamma.1
├─ @aws-sdk/util-body-length-node@1.0.0-gamma.1
├─ @aws-sdk/util-buffer-from@1.0.0-gamma.1
├─ @aws-sdk/util-create-request@1.0.0-gamma.1
├─ @aws-sdk/util-format-url@1.0.0-gamma.1
├─ @aws-sdk/util-hex-encoding@1.0.0-gamma.1
├─ @aws-sdk/util-locate-window@1.0.0-gamma.1
├─ @aws-sdk/util-uri-escape@1.0.0-gamma.1
├─ @aws-sdk/util-user-agent-browser@1.0.0-gamma.1
├─ @aws-sdk/util-user-agent-node@1.0.0-gamma.1
├─ @aws-sdk/util-utf8-browser@1.0.0-gamma.1
├─ @aws-sdk/util-utf8-node@1.0.0-gamma.1
├─ @aws-sdk/xml-builder@1.0.0-gamma.1
├─ aws-amplify-react-native@4.2.0
├─ aws-amplify@3.0.13
├─ aws-sdk@2.687.0
└─ aws-sign2@0.7.0

```

**Comment by nihp** [comment]
Here i will took the token from the below code and pass for my API calls to fetch the data. Here while I am in the app doing any fetches it will show the **no current user**.

`AuthClass - Failed to get the current user', 'No current user'`

```
export async function get (endpoint: string, data?) {
    const currentSession = await Auth.currentSession();
    const providerId = currentSession.getIdToken().payload.sub;
    const identityJwt = currentSession.getIdToken().getJwtToken();
    return GET(endpoint, data, identityJwt, providerId);
}
```

Also I have referred lot of suggestions or solutions for this. But I can't able to rectify this. I need to know what causes this issue and need to debug. 

https://github.com/aws-amplify/amplify-js/issues/3943

>>>>>>
 
1. it could be a chance that your App is calling Auth.currentSession() when the users are logged out or didn't sign in yet?

2. The error is usually received by processes running on an interval timer after a period of time. We suspect some type of "failed to load resource: net::ERR_NETWORK_IO_SUSPENDED" but this type of error message is 'hidden' by the current code and replaced with "No current User". I think changing the error handling would help others with these type of problems. 'Network connection is good enough'




In this thread https://github.com/aws-amplify/amplify-js/issues/2702 they mentioned lot.

- I had the same problem, but for me, removing the cookie storage configuration in aws-exports.js solved it. Maybe this helps someone. `Here I not using the cookie storage`
- My solution is to remove the node_modules and reinstall again. 'Already tried'

- I had this very same error
What I realised, is that I needed to run node v8 and that I use nvm to set that version. I think what happened was I ran a node install on the wrong version? Whatever the real cause was, removing node_module, and doing a
npm use 8; npm install for me fixed it

Your commands might be different, but essentially, removing node_modules, and reinstalling my dependencies is what fixed it

UPDATE: What can also cause this, is your react app calling storage, before the user has been authenticated 
`For this previously we have used nvm 8, but now we using 12. I think it not make any issues.`

**Comment by nihp** [comment]
Duplicate https://github.com/aws-amplify/amplify-js/issues/6046

**Comment by amhinson** [comment]
@nihp It's difficult to replicate the behavior you're seeing without a clear reproduction example. Would you be able to create a basic repo to show the behavior you're seeing and share that with us?

**Comment by nihp** [comment]
Here I have

actions.js defines Redux Actions. 

```
const SWITCH_USER = 'SWITCH_USER';

function deleteProfile() {
  return { type: DELETE_PROFILE }
}

export { SWITCH_USER  }
export { switchUser}
```

```
  Hub.listen('auth', (data) => {
            console.log('Hub.auth event:', data);
            const { payload } = data;
            Auth.currentAuthenticatedUser({ bypassCache: true })
                .then(u => {
                    console.log('Auth.currentAuthenticatedUser result:', u);
                    store.dispatch(user.actions.switchUser({...u}));
                }, err => {
                    store.dispatch(user.actions.switchUser(null));
                });
        });
```

For communicating with the backend using

```
export async function get (endpoint: string, data?) {
    const currentSession = await Auth.currentSession();
    const providerId = currentSession.getIdToken().payload.sub;
    const identityJwt = currentSession.getIdToken().getJwtToken();
    return GET(endpoint, data, identityJwt, providerId);
}
```

**Comment by nihp** [comment]
Any updates?

**Comment by amhinson** [comment]
> ```
> export async function get (endpoint: string, data?) {
>     const currentSession = await Auth.currentSession();
>     const providerId = currentSession.getIdToken().payload.sub;
>     const identityJwt = currentSession.getIdToken().getJwtToken();
>     return GET(endpoint, data, identityJwt, providerId);
> }
> ```
> ```
>   <Authenticator
>           hideDefault ={true}
>           amplifyConfig={awsmobile}
>           theme={this.state.theme}
>           signUpConfig={signUpConfig}
>           onStateChange={this.onStateChange}
>         >
>           <CustomizedSignIn  override={'SignIn'}/>
>           <CustomizedSignUp  signUpConfig={signUpConfig} override={'SignUp'}/>
>           <CustomizedForgotPassword override={'ForgotPassword'}/>
>           <CustomizedConfirmRegistration override={'ConfirmSignUp'}/>
>           <ConfirmizedSignInScreen override={'ConfirmSignIn'}/>
>           <Loading/>
>         </Authenticator>
> ```

A couple of thoughts:

- Is this `get` function ever called while the user is not logged in? If so, `Auth.currentSession()` would throw the error you are seeing. Try adding some logging in that function to see when it is actually being called.

- I don't see your actual app inside `<Authenticator>`. Did you leave it out just for the example, or is it rendered somewhere else?

**Comment by nihp** [comment]
> * Is this `get` function ever called while the user is not logged in? If so, `Auth.currentSession()` would throw the error you are seeing. Try adding some logging in that function to see when it is actually being called

Auth.currentSession() only called while am in the app. After logout it not get called for sure.



> > ```
> > export async function get (endpoint: string, data?) {
> >     const currentSession = await Auth.currentSession();
> >     const providerId = currentSession.getIdToken().payload.sub;
> >     const identityJwt = currentSession.getIdToken().getJwtToken();
> >     return GET(endpoint, data, identityJwt, providerId);
> > }
> > ```
> > 
> > 
> > ```
> >   <Authenticator
> >           hideDefault ={true}
> >           amplifyConfig={awsmobile}
> >           theme={this.state.theme}
> >           signUpConfig={signUpConfig}
> >           onStateChange={this.onStateChange}
> >         >
> >           <CustomizedSignIn  override={'SignIn'}/>
> >           <CustomizedSignUp  signUpConfig={signUpConfig} override={'SignUp'}/>
> >           <CustomizedForgotPassword override={'ForgotPassword'}/>
> >           <CustomizedConfirmRegistration override={'ConfirmSignUp'}/>
> >           <ConfirmizedSignInScreen override={'ConfirmSignIn'}/>
> >           <Loading/>
> >         </Authenticator>
> > ```
> 
> A couple of thoughts:
> 
> * Is this `get` function ever called while the user is not logged in? If so, `Auth.currentSession()` would throw the error you are seeing. Try adding some logging in that function to see when it is actually being called.
> * I don't see your actual app inside `<Authenticator>`. Did you leave it out just for the example, or is it rendered somewhere else?


Authenticator is a screen it is handled in the naviagation.

**Comment by amhinson** [comment]
Would it be possible to create a full working basic example repo or [Expo Snack](https://snack.expo.io/) to show the problem you are seeing so we can actually run the app to replicate the behavior?

**Comment by nihp** [comment]
Did you need full app code to debug this issue.

**Comment by amhinson** [comment]
If you could create a small example that replicates the issue you are seeing, that would be great!

**Comment by nihp** [comment]
I have used the customized screen with existing or default screens. 

Also, the above GET call code makes interaction with backend and aws-amplify.

My code structure

Snack expo: https://snack.expo.io/@niph/auth

**Comment by amhinson** [comment]
Thanks for that @nihp! However, is there a way you could make that example a bit more complete? It doesn't need to be your exact code, but just a simplified version of it that can actually run to show the behavior you're seeing. The key here is just providing us a complete reproduction sample so we can determine if there's a bug or documentation that needs to be updated.

You can keep the `aws-exports` file empty, and I'll replace it with my own `aws-exports` file when running the example.

**Comment by nihp** [comment]
It is still an issue

**Comment by antarasi** [comment]
The error is literally saying `No current user` - you need to sign in using the supported identity provider.

Workaround for that:
```javascript
import { Amplify } from "@aws-amplify/core";
import { Auth } from "@aws-amplify/auth";
import { CookieStorage } from 'amazon-cognito-identity-js';
import amplifyConfig from "../lib/Amplify";

Amplify.configure(amplifyConfig);

const cookieStorage = new CookieStorage(amplifyConfig.Auth.cookieStorage);
// cookie that is set before Cognito redirect to prevent infinite loop if authorization fails due to other reason than "No current user"
const redirectedFromAuthorize = cookieStorage.getItem("redirected-from-authorize");

...

Auth.currentAuthenticatedUser()
  .then(user => {
    setUser(user); // your custom function to do something with user attributes
    // authorization was successfull, we can remove the redirect cookie
    cookieStorage.removeItem("redirected-from-authorize");
  })
  .catch(err => {
    console.error(err);

    // if the cookie is set, it means the authorization failed again and you should not redirect back to Cognito
    if (!redirectedFromAuthorize) {
      // set redirect cookie, so that we know next time the error is reocurring
      cookieStorage.setItem("redirected-from-authorize", 'true');
      // redirect to Cognito hosted UI
      return Auth.federatedSignIn();
    }
  });
```
