### ISSUE TITLE
[Feedback][UI][React] Don't know how to set another country dial code by default

### ISSUE THREAD

**Issue by cezarneaga** [aws-amplify/amplify-js#6017]
**Page**: [`/ui/auth/authenticator/q/framework/react`](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react

hi everyone!
i couldnt find how to set another country dial code default. is there a way with the new AplifyAuthenticator component?

**Comment by jordanranz** [comment]
Hey @cezarneaga, there is no simple way to do this with the new Authenticator. We can improve the formFields object by allowing a user to pass in the default country code to their phone field. I'll mark this as a feature request and we can get this prioritized. Thanks for the feedback.

**Comment by cezarneaga** [comment]
That is great. Thanks for this and keep up the great work.

**Comment by igorfel** [comment]
So, for those looking for the answer on this topic look for #6189. So, i think this issue can be closed too.
