### ISSUE TITLE
'aws-amplify' version '3.0.16': `Unable to resolve module `./providers` from `node_modules/@aws-amplify/storage/lib-esm/index.js`:`

### ISSUE THREAD

**Issue by pperron** [aws-amplify/amplify-js#6019]
**Describe the bug**
Updated my 'aws-amplify' react native package to version '3.0.16' and on XCODE IOS, started to have a problem when build ends and metro builder start compiling, started to get errors like:
`Unable to resolve module `./providers` from `node_modules/@aws-amplify/storage/lib-esm/index.js`:`

**To Reproduce**

1. Updated my  'aws-amplify' lib with `yarn add aws-amplify` --> updated to version '3.0.16'
2. Go in XCODE and start compile
3. XCODE build completed with no error, then metro builder starts
4. During the metro build, get the error about './providers'

**Expected behavior**
Metro builder should not give error

=========================
I inspected the files in the 'node_modules/@aws-amplify/storage/lib-ems/' and seen that the 'Providers' folder starts with a capital letters but file pointing to it using not a capital letter './providers'...

I change the source code of file "index.js" and "Storage.js" that were refering to that folder by using  './Providers' and metro builded could compile...

Please check if the capital letter for the folder is the problem or the file refering to the folder not using a capital letter...

Thanks !

**Comment by sammartinez** [comment]
@pperron Did you remove your lock files as you were upgrading? Please let us know and if you can provide us with your `package.json` this will help us with investigating this further for yourself.

Thanks ahead of time

**Comment by pperron** [comment]
Hi,
here is my package.json:

{
  "name": "XXXX",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "postinstall": "patch-package"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.8.0",
    "@react-native-community/datetimepicker": "^2.2.3",
    "@react-native-community/masked-view": "^0.1.6",
    "@react-native-community/netinfo": "^5.9.2",
    "@react-navigation/bottom-tabs": "^5.1.0",
    "@react-navigation/compat": "^5.1.1",
    "@react-navigation/material-top-tabs": "^5.1.1",
    "@react-navigation/native": "^5.0.7",
    "@react-navigation/stack": "^5.0.9",
    "amazon-cognito-auth-js": "^1.3.3",
    "amazon-cognito-identity-js": "^4.3.1",
    "aws-amplify": "^3.0.16",
    "aws-amplify-react-native": "^4.2.0",
    "aws-sdk": "^2.690.0",
    "buffer": "^5.6.0",
    "moment": "^2.24.0",
    "nanoid": "^2.1.11",
    "native-base": "^2.13.8",
    "patch-package": "^6.2.2",
    "postinstall-postinstall": "^2.1.0",
    "react": "16.9.0",
    "react-content-loader": "^5.0.2",
    "react-native": "0.61.5",
    "react-native-admob-native-ads": "^0.2.9",
    "react-native-camera": "^3.27.0",
    "react-native-circular-progress": "^1.3.6",
    "react-native-clock-sync": "^1.1.0-a",
    "react-native-collapsible-tab-header": "^1.3.4",
    "react-native-device-info": "^5.5.3",
    "react-native-elements": "^1.2.7",
    "react-native-fast-image": "^7.0.2",
    "react-native-fbsdk": "^1.1.2",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-geocoder-reborn": "^0.9.0",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-google-static-map": "^0.1.13",
    "react-native-hide-with-keyboard": "^1.2.1",
    "react-native-image-crop-picker": "^0.28.0",
    "react-native-image-resizer": "^1.2.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-maps": "^0.27.1",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-material-menu": "^1.0.0",
    "react-native-material-textfield": "^0.16.1",
    "react-native-modal": "^11.5.4",
    "react-native-modal-datetime-picker": "^8.5.1",
    "react-native-ntp-client": "^1.0.1",
    "react-native-paper": "^3.6.0",
    "react-native-permissions": "^2.0.9",
    "react-native-pose": "^0.9.1",
    "react-native-reanimated": "^1.7.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.0.0-beta.13",
    "react-native-securerandom": "^1.0.0-rc.0",
    "react-native-svg": "^11.0.1",
    "react-native-swipeout": "^2.3.6",
    "react-native-tab-view": "^2.13.0",
    "react-native-tag-select": "^2.0.0",
    "react-native-timeago": "^0.5.0",
    "react-native-udp": "^3.0.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-video": "^4.4.5",
    "react-native-video-processing": "^1.20.0",
    "react-native-video-watermark": "https://github.com/sagark1510/react-native-video-watermark#1.0.2",
    "react-navigation-collapsible": "^5.0.0",
    "react-navigation-transitions": "^1.0.12"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^0.0.7",
    "babel-jest": "^25.1.0",
    "eslint": "^6.8.0",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}


I had to patch a couple of other things like error related to not finding 'aws-sdk' which I added to the package.json. Same thing for "@react-native-community/netinfo" that became to findable.

Anyway, else than looking into the package.json file, just looking at the source code of the "aws-amplify" lib, we can see that the source code is referencing to './providers' folder instead of './Providers' with a capital 'P'...

Change the source code with the capital 'P' and everything compiling, my post was to make you aware of that to correct source code if needed...

**Comment by ashika01** [comment]
@pperron I am not sure what is wrong in your case? but looking at the build folder, we are looking for `./providers` in `lib-esm`

<img width="324" alt="Screen Shot 2020-06-05 at 1 37 09 PM" src="https://user-images.githubusercontent.com/35131273/83920786-cd6e1080-a731-11ea-87fd-54772d615ce1.png">

**Comment by ashika01** [comment]
I am closing this issue. Since this isn't an amplify bug as far as I know. Let me know if it causes problem I can reopen this issue.

There was a similar issue earlier this week soon after we pushed a change out around storage. It was the cache that was causing the issue.

https://github.com/aws-amplify/amplify-js/issues/5964#issuecomment-637218858
