### ISSUE TITLE
NotAuthorizedException: Token is not from a supported provider of this identity pool - google auth

### ISSUE THREAD

**Issue by paulsjohnson91** [aws-amplify/amplify-js#6020]
**Describe the bug**
I'm trying to use Google Auth with AWS Cognito in a React Native configuration but when I use federatedSignIn, I'm getting an error saying NotAuthorizedException: Token is not from a supported provider of this identity pool.

**To Reproduce**
My Config file:
```
const awsConfig = {
  aws_app_analytics: 'enable',

  aws_user_pools: 'enable',
  aws_user_pools_id: '<userpoolid',
  aws_user_pools_mfa_type: 'OFF',
  aws_user_pools_web_client_id: '<clientid>',
  aws_user_settings: 'enable',
  aws_cognito_identity_pool_id: 'eu-west-1:<myidentitypool',
  federationTarget: 'COGNITO_USER_POOLS',
  aws_region: 'eu-west-1'
};
```
The code I'm using to sign in
```
import {
  GoogleSignin,
  GoogleSigninButton,
  statusCodes,
} from '@react-native-community/google-signin';
import Amplify from '@aws-amplify/core';
Amplify.configure({
  ...awsConfig,
});

      GoogleSignin.configure({
        webClientId:
          '<my google api web client id>',
      });
      await GoogleSignin.hasPlayServices();
      const userInfoGoogle = await GoogleSignin.signIn();
      if (userInfoGoogle.idToken) {
        const userInfoCognito = await Auth.federatedSignIn(
          'accounts.google.com',
          {
            token: userInfoGoogle.idToken,
          },
          userInfoGoogle.user,
        );
      }
```
My package.json file
```
    "@react-native-community/google-signin": "^4.0.3",
    "amazon-cognito-identity-js": "^4.3.0",
    "aws-amplify": "^3.0.12",
    "aws-amplify-react-native": "^4.2.0",
```
In the federated identities console I have my authentication provider for Google+ set to my google client id of form <id>apps.googleusercontent.com.
In User Pools, I have the identity provider set up with the same client id in the google app id field, and the app secret taken from the google api site with authorize scope 'profile email'

**Comment by amhinson** [comment]
Hey @paulsjohnson91, could you try using `google` instead of `accounts.google.com` as the first argument for `federatedSignIn` and see if that fixes the issue you're seeing?

**Comment by paulsjohnson91** [comment]
Hi @amhinson, thanks for the quick response. I've changed my code as below but unfortunately the error didn't change.
```
        const userInfoCognito = await Auth.federatedSignIn(
          'google',
          {
            token: userInfoGoogle.idToken,
          },
          userInfoGoogle.user,
        );

**Comment by amhinson** [comment]
Hm interesting! I've got an example app running for iOS using the code you've provided and it all seems to be working correctly, which leads me to believe the issue might just be configuration-related between Cognito & Google/Firebase.

When you were setting up [this step](https://github.com/react-native-community/google-signin/blob/master/docs/get-config-file.md) for `@react-native-community/google-signin`, did you do it with or without Firebase?

Also, did you setup an app within the project for iOS, Android, and/or web? And which one is the Client ID you used in Federated Identities from?

**Comment by paulsjohnson91** [comment]
I already had firebase set up so I used Firebase for that step.
When logging into the google cloud platform, this meant that all my client IDs were already created
<img width="798" alt="Screenshot 2020-06-06 at 00 45 31" src="https://user-images.githubusercontent.com/28013436/83930382-359f0f80-a78f-11ea-881d-33990830e6f9.png">

I used the web one as I read was recommended elsewhere as this one had a client secret and I was able to set URL and authorized redirect url with the format https://<myurl>.auth.eu-west-1.amazoncognito.com/oauth2/idpresponse. When I attempted to use the android client id, the google auth call in google-signin failed.

Although my react native app is built for both ios and android, so far I've only been testing google auth with android. 

My Federated Identities setup, where client id comes from the web client above:
<img width="666" alt="Screenshot 2020-06-06 at 00 51 26" src="https://user-images.githubusercontent.com/28013436/83930558-29678200-a790-11ea-881f-b4130eca80be.png">

My User Pool setup, with the same web client id
<img width="589" alt="Screenshot 2020-06-06 at 00 52 17" src="https://user-images.githubusercontent.com/28013436/83930576-36847100-a790-11ea-889b-5929012b68bf.png">
I've tried selecting Authorization code grant and	Implicit grant with all info selected too and setting the url to myapp://signin but this didn't seem to make a difference.

**Comment by amhinson** [comment]
@paulsjohnson91 Since you are using the native Google SDK to provide the token, I think the Identity Pool would expect to have the iOS client ID. Could you try using one of the iOS client IDs instead of web and see if that solves your issue?

**Comment by paulsjohnson91** [comment]
Sorry for the late reply, I've just tried this and am still getting the same error.

**Comment by paulsjohnson91** [comment]
As a side note, I've considered using openid instead but can find absolutely no documentation on google oauth with openid on react native, does anyone have any?

**Comment by paulsjohnson91** [comment]
ok I switched to using OpenID Connect instead and this seems to work. A separate issue though is that I'm not sure what to do next, I have successfully used federated sign in and have an access key, secret access key, session token etc but now if I do Auth.currentSession it says no user so how do I get a token to access api gateway?

**Comment by paulsjohnson91** [comment]
I don't now see a user with the logged in users email address in the cognito user pool

**Comment by paulsjohnson91** [comment]
To be clear, when I logged in with Google I was given an object of form:
     `{idToken: "<token", serverAuthCode: null, user: {…}, scopes: Array(3)}`

And when I used federated signin I was left with an object of form:
 `{accessKeyId: "<key>", secretAccessKey: "<secret key>", sessionToken: "<session token>", expiration: <time>, authenticated: true}`

I was expecting this to mean that my user was now registered and signed in but using `Auth.currentSession()` gives you a response `No current user`

With my regular cognito users, I use currentSession to get an ID token which I then use as my authorizer to an api gateway. In my api lambdas, I can get user ID which I then use for various things.

**Comment by amhinson** [comment]
There are currently different behaviors here, depending on whether you use Identity Pool Federation or User Pools with Cognito Hosted UI. 

Before diving into what you're seeing, have you considered using [Hosted UI](https://docs.amplify.aws/lib/auth/social/q/platform/js)? This would allow all the users to authenticate with Google, but still exist in the User Pool alongside your regular Cognito users.

**Comment by paulsjohnson91** [comment]
Hi @amhinson thanks for the suggestion, initially was looking to not have to use hosted ui to keep the user in the app, particularly since I wasn't using deep linking.
I've now set up deep linking and have gotten hosted ui to work except for one issue.
Initially I set up the cognito userpool to need birthdate as a required field however it doesn't look like you can get this from google, only birthday.
I'm now getting an error `Error handling auth response. Error: attributes+required%3A+%5Bbirthdate%5D`
Since the console says it's not possible to remove required attributes from a cognito user pool, is it possible to somehow provide a dummy date here to avoid an error? I've tried attribute mapping birthdays to birthdate but that didn't work.

**Comment by paulsjohnson91** [comment]
I've added https://www.googleapis.com/auth/user.birthday.read to the authorization scope and added attribute mapping from birthdays to birthday however despite the hosted ui confirming that date of birth is being requested. I still get the same error

**Comment by amhinson** [comment]
Sorry for the problem you're seeing @paulsjohnson91! It does appear that Cognito doesn't allow removing required attributes. You could either just create a new User Pool (assuming your app is still in development), or potentially add a pre-sign-up lambda function trigger to add the required attribute.

Also, if you would like to keep the user in the app with Hosted UI, here's an [example](https://docs.amplify.aws/lib/auth/social/q/platform/js#hosted-ui-with-expo) of using a custom urlOpener. The example uses Expo's `WebBrowser`, but you could use any other in-app browser library.

**Comment by paulsjohnson91** [comment]
I've tried to add a pre-sign-up lambda function trigger to add the attribute however using the hosted UI doesn't appear to trigger it.
I've tested it with signing up regularly and I can see cloud watch logs appearing for the pre sign up trigger however using hosted ui I don't get any logs making me thing it isn't being used.

`
exports.handler = (event, context, callback) => {
    
    event.request.userAttributes.birthdate = '01-01-2000',
    console.log(event);

    // Return to Amazon Cognito
    callback(null, event);
};`

this is the lambda I wrote.

**Comment by paulsjohnson91** [comment]
I'm reluctant to use a new cognito user pool as I already have my app out live

**Comment by amhinson** [comment]
@paulsjohnson91 Were you able to solve your issue here?

**Comment by paulsjohnson91** [comment]
Hi @amhinson unfortunately no I've been unable to solve this issue so far.
I've set up a pre-signup trigger to add in the date of birth to a google auth sign up however I've been looking at the logs and the lambda isn't actually being triggered. Amplify is returning an error

    console.error: [ERROR] 40:58.475 OAuth - Error handling auth response. Error: attributes+required%3A+%5Bbirthdate%5D

I've verified that my pre-signup lambda is working because I can see logs from a regular sign up. I don't know why amplify is rejecting the sign up without going through the pre-signup lambda, any ideas?

Thanks

**Comment by paulsjohnson91** [comment]
Just on a hunch, I've also just tried to sign up a regular user without date of birth and the pre-signup trigger isn't called in that instance either. So it looks like a broader issue where amplify is validating the required fields itself before calling the pre-signup trigger

**Comment by amhinson** [comment]
@paulsjohnson91 I'm going to close this issue, since it seems that the original problem has been addressed and you've created a new issue for the pre-sign up trigger.
