### ISSUE TITLE
AmplifyAuthenticator auth state is signedin after email confirmation but user is not authenticated

### ISSUE THREAD

**Issue by stephendmalloy** [aws-amplify/amplify-js#6023]
I'm not 100% sure if this is a bug. 

I'm using AmplifyAuthenticator component using React. I've used the CLI to set up Authentication and require that a user enter a confirmation code sent via email. When a user registers for the App they receive a confirmation code and the AmplifyAuthenticator component shows the AmplifyConfirmSignUp screen as expected. When the confirmation code is entered, the user is granted access to my app. However, the user is NOT authenticated when checking with:

Auth.currentAuthenticatedUser

To get around this I simply called Auth.signOut and reload the page but this is an odd experience for my users. Upon subsequent logins Auth.currentAuthenticatedUser returns the users information. I'd expect that after confirming their account that the Auth.currentAuthenticatedUser would return the users attributes, etc. 

I did check the state of AmplifyAuthenticator after account confirmation and the new auth state indeed is "signedin". Not sure if I should be using another class or if this is a bug.

`React.useEffect(() => {
        return onAuthUIStateChange(newAuthState => {
            setAuthState(newAuthState) // newAuthState is signedin 
            props.authStateChangeHandler(newAuthState);
        });
      }, [props]);`

**Comment by jordanranz** [comment]
@stephendmalloy could you post which version of `@aws-amplify/ui-react` you are using.

**Comment by stephendmalloy** [comment]
@jordanranz sure thing.

"@aws-amplify/ui-react": "^0.2.7",

**Comment by jordanranz** [comment]
Can you try installing the latest: `"@aws-amplify/ui-react": "^0.2.8"` and let me know if the same behavior exists. We added an auth guard to `onAuthUIStateChange` in [this PR](https://github.com/aws-amplify/amplify-js/pull/5930/files#diff-e71cd29314568b797d5e2ac4518ed740R62-R72) recently.

**Comment by stephendmalloy** [comment]
@jordanranz unfortunately the issue persists.

**Comment by ecomonestop** [comment]
@jordanranz - I'm having similar behavior.  However, if I don't supply my own slot for AmplifyConfirmSignUp, then the behavior is as expected, i.e. email is pre-populated in username field and when user confirms email, he is taken into the app.  

On the other hand, when using a custom slot for confirm signup, just wrapping the component AmplifyConfirmSignUp, this doesn't work.  Email is not pre-populated and when the user confirms his email, he is not authenticated, thus not taken into the app

I tried both versions  ^0.2.7" and ^0.2.8".  Any other suggestions?

**Comment by stephendmalloy** [comment]
I'm experiencing the same behavior. My apologies for not mentioning that. The email field is also not pre-populated and I too am using custom slots as well. I'm not doing anything crazy, though. Here's my confirmation code UI:

`import React from 'react';
import {
    AmplifyConfirmSignUp
} from '@aws-amplify/ui-react';

import AuthAvatar from './AuthAvatar.js';
import DoormanPoweredBy from './DoormanPoweredBy.js';

export default () => (

    <div slot="confirm-sign-up" className="auth-wrapper">
        <AuthAvatar />
        <AmplifyConfirmSignUp
            slot="confirm-sign-up"
            headerText={"Enter verification code"}
            usernameAlias="email"
            />
        <DoormanPoweredBy />
    </div>

);`

I'm also having issues with require new password screens as well in that I'm unable to use the password field type for new password - the UI simply throws "Password cannot be empty" error, but that appears to be another issue altogether.

**Comment by jordanranz** [comment]
@ecomonestop @stephendmalloy, passing the user object into the slotted `AmplifyConfirmSignUp` may resolve the issue for you.

Something like:
```
// TODO: Add a user state object
React.useEffect(() => { 
  return onAuthUIStateChange((newAuthState, authData) => { 
    setUser(authData);
    setAuthState(newAuthState)
  }); 
}, [props]);
```
then in `AmplifyConfirmSignUp`:
```
<div slot="confirm-sign-up" className="auth-wrapper">
  <AuthAvatar />
  <AmplifyConfirmSignUp user={user} slot="confirm-sign-up" headerText={"Enter verification code"} usernameAlias="email" /> 
  <DoormanPoweredBy />
</div>
```

We can probably improve this experience by checking for a user inside of the component load whenever you use a slotted component like `AmplifyConfirmSignUp` that requires a user object to be passed in.

**Comment by ecomonestop** [comment]
@jordanranz - This is still not working for me. I tried both versions ^0.2.7" and ^0.2.8", essentially copying and pasting your code (I confirmed user prop is being populated on the AmplifyConfirmSignUp component)   I still get the behavior as previously described.

**Comment by jordanranz** [comment]
@ecomonestop can you provide a code snippet of the `AmplifyAuthenticator` render logic

**Comment by ecomonestop** [comment]
Below is just the layout code that wraps the Amplify components:


`
const LayoutForAuth
 = ({ AmplifyComponent, slot, ...rest }) => {
  const classes = useStyles()
  return (
    <div
      slot={slot}
      className={classes.pageHeader}
      style={{
        backgroundImage: "url(" + image + ")",
        backgroundSize: "cover",
        backgroundPosition: "top center",
        justifyContent: "center",
        alignItems: "center",
        display: "flex",
        textAlign: "center",
        margin: "0 auto",
        height: "100vh",
      }}
      // className={classes.cardSignup}
    >
      <div className={classes.container}>
        <GridContainer justify="center">
          <GridItem xs={12} sm={10} md={10}>
            <AmplifyComponent {...rest}></AmplifyComponent>
          </GridItem>
        </GridContainer>
      </div>
    </div>
  )
}
`


This is the code that does the rendering of the wrapped components using your suggested React.useEffect code:


`const Auth = ({ initialAuthState = "signin" }, ...rest) => {
  const [user, setUser] = React.useState(null)
  const [authState, setAuthState] = React.useState(null)
  React.useEffect(() => {
    return onAuthUIStateChange((newAuthState, authData) => {
      console.log("authData is ", authData)
      setUser(authData)
      setAuthState(newAuthState)
    })
  }, [...rest])
  return (

    <AmplifyAuthenticator
      initialAuthState={initialAuthState}
      usernameAlias="email"
    >
      <LayoutForAuth
        AmplifyComponent={AmplifySignUp}
        slot="sign-up"
        usernameAlias="email"
        user={user}
      ></LayoutForAuth>
      <LayoutForAuth
        AmplifyComponent={AmplifySignIn}
        slot="sign-in"
        usernameAlias="email"
        user={user}
      ></LayoutForAuth>
      <LayoutForAuth
        AmplifyComponent={AmplifyConfirmSignUp}
        headerText={"Enter verification code"}
        slot="confirm-sign-up"
        user={user}
        usernameAlias="email"
      ></LayoutForAuth>
      <LayoutForAuth
        AmplifyComponent={AmplifyForgotPassword}
        slot="forgot-password"
        usernameAlias="email"
        user={user}
      ></LayoutForAuth>
      <div>Backend App that will be the backendlayout component</div>
    </AmplifyAuthenticator>
  )
}
`

**Comment by sumeetchawla** [comment]
This is still an error I think? I am not sure what I am doing wrong.

I get the verification code but when I enter it and click the button, nothing happens and I get the below error:

`[ERROR] 02:29.437 helpers - User is not authenticated`

User is created and confirmed though.

How do I debug this?

**Comment by nikh-sugoi** [comment]
I am getting the same issue ` [ERROR] 32:55.639 helpers - User is not authenticated` 
User is confirmed but got this error  in onAuthUIStateChange
Any solution for this?
