### ISSUE TITLE
Subscriptions fail silently when using @auth(owner) rule with a schema with no owner field in React Native

### ISSUE THREAD

**Issue by IDGallagher** [aws-amplify/amplify-js#6032]
**Describe the bug**

When using the @auth(owner) rule in React Native, if you don't add an owner field to the schema, the field is automatically added in the backend and fetching from the backend works fine but subscriptions fail silently. Took me a day of poking around to figure out why my clients weren't syncing with each other!

**To Reproduce**

Use a schema like:

`type Post  
  @model
  @auth(rules: [
      {allow: owner}
    ])
{
  id: ID!
  name: String!
  description: String
}`

App will work fine apart from syncing between two clients with subscriptions. Add an owner field to the schema:

`type Post  
  @model
  @auth(rules: [
      {allow: owner}
    ])
{
  id: ID!
  name: String!
  description: String
  owner: String
}`

And subscriptions will work now :)

**Expected behavior**

I'd expect Amplify to automatically add the owner field to its generated .graphql schema if @auth(owner) is used. Or at least give a warning!

**Comment by mauerbac** [comment]
hey @IDGallagher - thanks for submitting. Would you be able to try the most recent version to see if it's resolved ?
