### ISSUE TITLE
Subscription filter on mutation result

### ISSUE THREAD

**Issue by plus-** [aws-amplify/amplify-js#6040]
Apollo server let you filter a subscription based on the mutation result (see: https://www.apollographql.com/docs/apollo-server/data/subscriptions/#subscription-filters). In the subscription resolver you have access to the payload which represent the mutation result you want to filter on.

**This is usefull if for example a particular mutation doesn't have as a parameter the arguments you want to filter on.** You can instead perform the filtering on the mutation result.

From the documentation it seems Appsync can only filter on the mutation parameters (https://docs.aws.amazon.com/appsync/latest/devguide/real-time-data.html). It would be usefull if there was a way to support payload filtering.

**Comment by undefobj** [comment]
Thank you for the feedback. This is a request that would be best directly to the AppSync team in their OSS feedback repo: https://github.com/aws/aws-appsync-community
