### ISSUE TITLE
Customization to allow Create Account to be removed from UI

### ISSUE THREAD

**Issue by JohnnyK84** [aws-amplify/amplify-js#6045]
Hey Guys, Thanks for the great library.
We have just implemented the angular-ui as part of our application but our users currently dont have the ability to Create an account themselves hence we are wanting to remove this from the UI component.

Is there currently anyway to remove or hide this from the amplify-authenticator, amplify-sign-in? 

I've attached pic for reference:
![Capture](https://user-images.githubusercontent.com/30273732/84206182-bac55400-ab02-11ea-801d-ab0d4163c25f.JPG)

**Comment by thenetimp** [comment]
I am in a similar place, except for a different reason.    For SEO reasons I don't want Registration and Login on the same page.  There seems to be no easy way to separate them out without dismantling the entire component and remaking it as separate components...

**Comment by jordanranz** [comment]
Hey @JohnnyK84 @thenetimp,

This is currently the way to do this:
```
<amplify-authenticator>
  <amplify-sign-in slot="sign-in">
    <div slot="secondary-footer-content"></div>
  </amplify-sign-in>
</amplify-authenticator>
```
It may be useful for us to add a prop to `amplify-sign-in` for this to improve the experience since it seems like a pretty common use case.

**Comment by thenetimp** [comment]
@jordanranz,  I just tried to add the above and got the following linting error  "'amplify-sign-in' is not a known element" in my signin module.  I have read the docs and made sure to import (and export) what it said it needed in my shared module.   My shared module is then imported into my lazyloaded signin module.

`import { AmplifyAngularModule } from 'aws-amplify-angular';
import { AmplifyUIAngularModule } from '@aws-amplify/ui-angular';
`

is there something else that I am missing?

**Comment by JohnnyK84** [comment]
@jordanranz That worked perfect. Thanks for the great help!!!
On another note, is there any plan to add support for Ionic as was with the previous version of this framework which can be found [here](https://aws-amplify.github.io/docs/js/tutorials/building-ionic-4-apps/) to support Ionic 5/Angular9.

Thanks again!

**Comment by jordanranz** [comment]
@thenetimp, if you are using the new `@aws-amplify/ui-angular` you shouldn't need:
```
import { AmplifyAngularModule } from 'aws-amplify-angular';
```
Any reason for importing both?
