### ISSUE TITLE
Cognito Forgot password verificiaton code API

### ISSUE THREAD

**Issue by Xuhan-Liu** [aws-amplify/amplify-js#6057]
**Describe the bug**
I am using Cognito authentication in amplify.js. I implemented a forgot password function by using the following code to get verification code
`import {Auth} from 'aws-amplify'`
`Auth.forgotPassword(username).then(res=>console.log(res))`

I am sure that I have configured amplify and Cognito correctly, because I am able to register and log in. However, when I call the function above, **no matter which username I put in, I can always get a success response, even though I don't have that username.**

So I did some further tests. I create another user pool B, and create a user called "userb" with email address "userb@gmail.com". Then I put "userb" in the function above which is linked to user pool A. **It still returns the success message and `CodeDeliveryDetails.Destination=userb@gmail.com`, even if verification code is not sent to userb@gmail.com.**

**Expected behavior**
I should receive an error response when the username is not in the linked user pool.

**What is Configured?**
this is my aws-config file
   ```
   const awsmobile = {
   "Auth": {
        "region": "ap-southeast-1",
        "userPoolId": "ap-southeast-1_xxxxxxxx",
        "userPoolWebClientId": "xxxxxxxxxxxxxxxxxxxxxx"
    }
   };
   ```

**Comment by sammartinez** [comment]
@Xuhan-Liu can you provide us with a code snippet of how you are using amplify? can you also provide `package.json` as well so we can dig into this deeper. Thanks ahead of time.
