### ISSUE TITLE
"peer dep missing" errors installing aws-amplify@3.0.17

### ISSUE THREAD

**Issue by TheVaporTrail** [aws-amplify/amplify-js#6061]
_2020.07.06: I realize that the `-g` option is incorrect, but this does not affect the issue._

**Describe the bug**
Installing aws-amplify@3.0.17 generates "peer dep missing" errors that I can not resolve by installing the missing packages

**To Reproduce**
I removed all but the minimum packages from npm global

```
[~/Desktop/Development/Javascript/PolygoniaV2_Dev2]$ npm ls -g --depth=0
/Users/david/.nvm/versions/node/v10.21.0/lib
├── copy-webpack-plugin@6.0.2
├── npm@6.14.5
├── PolygoniaV2_Dev2@1.0.0 -> /Users/david/Desktop/Development/Javascript/PolygoniaV2_Dev2
└── webpack@4.43.0
```
and then installed aws-amplify:
```
[~/Desktop/Development/Javascript/PolygoniaV2_Dev2]$ npm install -g aws-amplify
```
which resulted in the following warnings:
```
npm WARN deprecated buffer@4.9.1: This version of 'buffer' is out-of-date. You must update to v4.9.2 or newer

> fast-xml-parser@3.17.4 postinstall /Users/david/.nvm/versions/node/v10.21.0/lib/node_modules/aws-amplify/node_modules/fast-xml-parser
> node tasks/postinstall.js || exit 0

Love fast-xml-parser? Check https://amitkumargupta.work for more projects and contribution.

npm WARN @aws-amplify/api@3.1.16 requires a peer of @aws-amplify/pubsub@^2.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN @aws-amplify/datastore@2.2.3 requires a peer of @react-native-community/netinfo@^5.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN @aws-amplify/api-graphql@1.0.18 requires a peer of @aws-amplify/pubsub@^2.1.1 but none is installed. You must install peer dependencies yourself.

+ aws-amplify@3.0.17
added 145 packages from 413 contributors in 19.88s
```
Installing aws-amplify/pubsub ...
```
[~/Desktop/Development/Javascript/PolygoniaV2_Dev2]$ npm install -g @aws-amplify/pubsub@^2.1.1
npm WARN deprecated buffer@4.9.1: This version of 'buffer' is out-of-date. You must update to v4.9.2 or newer
npm WARN @aws-amplify/core@2.3.0 requires a peer of @react-native-community/netinfo@^5.5.0 but none is installed. You must install peer dependencies yourself.

+ @aws-amplify/pubsub@2.1.9
added 27 packages from 84 contributors in 5.507s
```
...does not resolve the issue:
```
[~/Desktop/Development/Javascript/PolygoniaV2_Dev2]$ npm ls -g --depth=0
/Users/david/.nvm/versions/node/v10.21.0/lib
├── @aws-amplify/pubsub@2.1.9
├── aws-amplify@3.0.17
├── copy-webpack-plugin@6.0.2
├── npm@6.14.5
├── PolygoniaV2_Dev2@1.0.0 -> /Users/david/Desktop/Development/Javascript/PolygoniaV2_Dev2
└── webpack@4.43.0

npm ERR! peer dep missing: @react-native-community/netinfo@^5.5.0, required by @aws-amplify/core@2.3.0
npm ERR! peer dep missing: @react-native-community/netinfo@^5.5.0, required by @aws-amplify/core@2.3.0
npm ERR! peer dep missing: @react-native-community/netinfo@^5.5.0, required by @aws-amplify/core@2.3.0
npm ERR! peer dep missing: @aws-amplify/pubsub@^2.1.1, required by @aws-amplify/api@3.1.16
npm ERR! peer dep missing: @aws-amplify/pubsub@^2.1.1, required by @aws-amplify/api@3.1.16
npm ERR! peer dep missing: @react-native-community/netinfo@^5.5.0, required by @aws-amplify/datastore@2.2.3
npm ERR! peer dep missing: @aws-amplify/pubsub@^2.1.1, required by @aws-amplify/api-graphql@1.0.18
npm ERR! peer dep missing: @aws-amplify/pubsub@^2.1.1, required by @aws-amplify/api@3.1.16
npm ERR! peer dep missing: @aws-amplify/pubsub@^2.1.1, required by @aws-amplify/api@3.1.16
npm ERR! peer dep missing: @aws-amplify/pubsub@^2.1.1, required by @aws-amplify/api@3.1.16
npm ERR! peer dep missing: @aws-amplify/pubsub@^2.1.1, required by @aws-amplify/api@3.1.16
```
**Expected behavior**
Either an installation of aws-amplify without the warnings or steps on how to resolve the warnings.

**Code Snippet**
(none)

**Screenshots**
(none)

**What is Configured?**

<details>
  <summary><strong>Environment</strong></summary>

```
[~/Desktop/Development/Javascript/PolygoniaV2_Dev2]$ npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
npx: installed 1 in 2.389s

  System:
    OS: macOS High Sierra 10.13.5
    CPU: (4) x64 Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz
    Memory: 56.05 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.21.0 - ~/.nvm/versions/node/v10.21.0/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v10.21.0/bin/npm
  Browsers:
    Chrome: 83.0.4103.97
    Firefox: 65.0.2
    Safari: 11.1.1
  npmGlobalPackages:
    @aws-amplify/pubsub: 2.1.9
    aws-amplify: 3.0.17
    copy-webpack-plugin: 6.0.2
    npm: 6.14.5
    PolygoniaV2_Dev2: 1.0.0
    webpack: 4.43.0

```
Node info:
```
[~/Desktop/Development/Javascript/PolygoniaV2_Dev2]$ nvm ls
        v8.11.2
->     v10.21.0
         system
default -> lts/* (-> N/A)
node -> stable (-> v10.21.0) (default)
stable -> 10.21 (-> v10.21.0) (default)
iojs -> N/A (default)
lts/* -> lts/erbium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.21.0
lts/erbium -> v12.18.0 (-> N/A)
```

</details>

**Smartphone (please complete the following information):**
(n/a)

**Additional context**

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by jairenee** [comment]
+1 

This issue is in @aws-amplify/api 3.1.17. It sets a peer dependency of pubsub@2.1.1, but also has api-graphql which has a peer dependency of pubsub@3.0.18. @aws-amplify/datastore requires pubsub 3.0.18 as a peer dependency, so currently, aws-amplify@3.0.18 demands a peer dependency of both 2.1.1 and 3.0.18.

**Comment by TheVaporTrail** [comment]
This is very easy to reproduce. In an new, empty directory:
```
npm init
npm install aws-amplify
npm ls --depth=0
```


<details>

[~/Desktop/Development/Javascript/AmplifyTest]$ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help init` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (amplifytest) 
version: (1.0.0) 
description: 
entry point: (index.js) 
test command: 
git repository: 
keywords: 
author: 
license: (ISC) 
About to write to /Users/david/Desktop/Development/Javascript/AmplifyTest/package.json:

{
  "name": "amplifytest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}


Is this OK? (yes) 
[~/Desktop/Development/Javascript/AmplifyTest]$ npm install aws-amplify
npm WARN deprecated buffer@4.9.1: This version of 'buffer' is out-of-date. You must update to v4.9.2 or newer

> fast-xml-parser@3.17.4 postinstall /Users/david/Desktop/Development/Javascript/AmplifyTest/node_modules/fast-xml-parser
> node tasks/postinstall.js || exit 0

Love fast-xml-parser? Check https://amitkumargupta.work for more projects and contribution.

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @aws-amplify/datastore@2.2.4 requires a peer of @react-native-community/netinfo@^5.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN @aws-amplify/api@3.1.17 requires a peer of @aws-amplify/pubsub@^2.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN @aws-amplify/api-graphql@1.1.0 requires a peer of @aws-amplify/pubsub@^2.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN amplifytest@1.0.0 No description
npm WARN amplifytest@1.0.0 No repository field.

+ aws-amplify@3.0.18
added 145 packages from 413 contributors and audited 145 packages in 11.542s

2 packages are looking for funding
  run `npm fund` for details

found 6 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
[~/Desktop/Development/Javascript/AmplifyTest]$ npm ls --depth=0
amplifytest@1.0.0 /Users/david/Desktop/Development/Javascript/AmplifyTest
└── aws-amplify@3.0.18

npm ERR! peer dep missing: @aws-amplify/pubsub@^2.1.1, required by @aws-amplify/api@3.1.17
npm ERR! peer dep missing: @aws-amplify/pubsub@^2.1.1, required by @aws-amplify/api@3.1.17
npm ERR! peer dep missing: @react-native-community/netinfo@^5.5.0, required by @aws-amplify/datastore@2.2.4
npm ERR! peer dep missing: @aws-amplify/pubsub@^2.1.1, required by @aws-amplify/api-graphql@1.1.0
npm ERR! peer dep missing: @aws-amplify/pubsub@^2.1.1, required by @aws-amplify/api@3.1.17
npm ERR! peer dep missing: @aws-amplify/pubsub@^2.1.1, required by @aws-amplify/api@3.1.17
npm ERR! peer dep missing: @aws-amplify/pubsub@^2.1.1, required by @aws-amplify/api@3.1.17
npm ERR! peer dep missing: @aws-amplify/pubsub@^2.1.1, required by @aws-amplify/api@3.1.17
[~/Desktop/Development/Javascript/AmplifyTest]$ 
</details>

**Comment by amhinson** [comment]
@TheVaporTrail I see there was a PR addressing this issue. Does that solve the problem you were seeing, and are we good to close this issue?
