### ISSUE TITLE
PubSub subscription callback

### ISSUE THREAD

**Issue by UnderSampled** [aws-amplify/amplify-js#6064]
**Is your feature request related to a problem? Please describe.**
I need to send a message to an MQTT topic after subscribing to it, so I can hear the response. Currently, I'd have to set a dumb timeout to give the broker just a little time to process the subscription request

**Describe the solution you'd like**
A callback/promise/connection event for `PubSub.subscribe`

**Describe alternatives you've considered**
I currently use a different MQTT library (the aws-iot-device-sdk), since it supports this sort of callback.

**Comment by UnderSampled** [comment]
It seems that Paho supports a success callback on the call to subscribe. It should be possible to await that in the call [on line 263 of Mqtt over WS](https://github.com/aws-amplify/amplify-js/blob/8c6fb4aefa60b36ed33d89c431e743f674119bde/packages/pubsub/src/Providers/MqttOverWSProvider.ts#L263).

**Comment by nzjoel1234** [comment]
Is there any possibility of this being done? The subscribe is not very useful without it.

**Comment by MikeSussman** [comment]
Any updates please as I am experiencing a similar issue in that my first Pub after subscribing to get the shadow state is not receiving data. If I wait and then manually trigger a pub I get the data.

**Comment by stocaaro** [comment]
Good news. We've added `Hub` events that you can now listen to to know when the IoT connection state changes, such as when it becomes `Connected`. [Here are instructions](https://www.google.com/maps/d/edit?mid=1R7JcHfuNwVnet-g6OBs1XdMU5h7s8Rw&usp=sharing) on how to use this feature with a list of the different states you can watch for.

**Comment by LFMAKER** [comment]
@stocaaro 
How can I verify that my subscription has successfully connected? I have 70+ in-app subscriptions on my mqtt client, but Hub.listen doesn't tell me specifically about each subscription.

I need to do this because I can only publish to a topic after being 100% connected with some subscriptions.

**Comment by stocaaro** [comment]
Hello @LFMAKER,

I added a reply to this question over on #2692.
