### ISSUE TITLE
How to find out the automatically assigned ID of an object created by a datastore.save operation 

### ISSUE THREAD

**Issue by econtentmaps** [aws-amplify/amplify-js#6066]
Title says it all, I think:

How on earth does one find out the ID automatically generated for an object when you create it using DataStore.save()?

I'm building a text editor and I want to store its state along with some metadata (e.g. slug, etc) and a UUID. This all works fine. But when I want to conditionally update an existing record or save a new one (depending on the presence or not of the UUID, which I'm automatically generated on save) I have no idea how to get the ID. I can see that an ID is generated by Amplify (looks to be a UUID or similar), but when I do use DataStore.save, there's no response as far as I can tell that says 'here's a value' that I can use to query for the item in the future using this query in the docs:

```
const original = await DataStore.query(Post, "123");

await DataStore.save(
  Post.copyOf(original, updated => {
    updated.title = `title ${Date.now()}`;
    updated.status =
      updated.status === PostStatus.ACTIVE
        ? PostStatus.INACTIVE
        : PostStatus.ACTIVE;
  })
);
```
In this code block from the docs, you have "123" on the first line, which is the ID? And that's where I'm stuck.

The documentation on this is arguably even sparser than my hair, so it's hard to come at it from lots of angles and muddle through to an epiphany, which is my usual approach, so I'm doing my very first GitHub issue.

I fear I must be missing something fundamental and  I'm tearing out what little hair I have left, so any help with this would help me immensely and possibly avoid an aneurism, so you can consider it healthcare :)

**Which Category is your question related to?**

API (*specifically DataStore)

**Amplify CLI Version** 

4.21.2

**What AWS Services are you utilizing?**

Amplify with Federated auth and an API configured with a DataStore  

**Provide additional details e.g. code snippets**

This is my schema:

```
type Article @model {
  id: ID!
  title: String
  slug: String
  description: String
  articleBodyData: AWSJSON!
}

type Map @model {
  id: ID!
  title: String
  stepData: AWSJSON!
}

**Comment by mdoesburg** [comment]
I don't know if I fully understand the problem your having, but doesn't `DataStore.save()` return the item with all the fields afterwards? Like this:

```js
const updatedPost = await DataStore.save(
  Post.copyOf(original, updated => {
    updated.title = `title ${Date.now()}`;
    updated.status =
      updated.status === PostStatus.ACTIVE
        ? PostStatus.INACTIVE
        : PostStatus.ACTIVE;
  })
);

// Log the ID of the Post that was just updated
console.log(updatedPost.id);
```

**Comment by mdoesburg** [comment]
Or you can get all the posts like this:
```js
const posts = await DataStore.query(Post, Predicates.ALL);
```

**Comment by manueliglesias** [comment]
Hi @econtentmaps 

> How on earth does one find out the ID automatically generated for an object when you create it using DataStore.save()?

When you create a new instance of a model, a uuid is generated for the item automatically (even before calling `DataStore.save()`), that means that as soon as you create the instance, you can get its `id` like this:

```typescript
const post = new Post({
  title: "My Post",
  status: PostStatus.ACTIVE
});

console.log(post.id); // 8bc73384-f14d-4faf-a1f0-16f2674b0b94
```

Let us know if that helps
