### ISSUE TITLE
Export types from @aws-amplify/ui-vue

### ISSUE THREAD

**Issue by mspoulsen** [aws-amplify/amplify-js#6071]
I suggest better access to the typescript types (let me know if I am missing something)

To get to the types I do this:
`import { FormFieldTypes } from '@aws-amplify/ui-components/dist/types/components/amplify-auth-fields/amplify-auth-fields-interface'`

This would be better:
`import { FormFieldTypes } from '@aws-amplify/ui-vue'`

**Comment by jordanranz** [comment]
You should be able to do:
```
import { FormFieldTypes } from '@aws-amplify/ui-components';
```
We can look into passing that through to `@aws-amplify/ui-vue`.

Thanks for the feedback.

**Comment by mspoulsen** [comment]
Yes, I am thanks! Funny thing it that I am not able to re-export them directly though

Would like to be able to do this:
```
export { FormFieldTypes } from "@aws-amplify/ui-components"
```

But I have to do this:
```
import {
  FormFieldTypes as AWSFormFieldTypes
} from '@aws-amplify/ui-components'

export type FormFieldTypes = AWSFormFieldTypes
```

But I can export AuthState directly:
```
export { AuthState } from "@aws-amplify/ui-components"
```

**Comment by wlee221** [comment]
Hi, I'll be closing this issue as @jordanranz's suggestion works. For typescript issue with re-exporting interfaces, I found that this is an expected behavior with `--isolatedModules`: https://github.com/microsoft/TypeScript/issues/28481.
