### ISSUE TITLE
Amplify Auth component affects my styling

### ISSUE THREAD

**Issue by mspoulsen** [aws-amplify/amplify-js#6072]
Hi,
I am using the Amplify Vue Auth component with my vue app.
https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue

It is working, but after successful login the styling of my (vuetify) app has changed. If I remove `<amplify-authenticator>` my styling is back to normal.

Does amplify apply styling that could affect my app? And what can I do about it?

Thanks

**Comment by kendevops** [comment]
Quick question:
- When you say "if i remove my styling is back to normal", do you mean when you remove your styling for vuetify?

**Comment by mspoulsen** [comment]
Forgot the include `<amplify-authenticator>` in quotes so it disappeared from the question. I have update my question :+1:

**Comment by kendevops** [comment]
Can you look at https://docs.amplify.aws/ui/customization/theming/q/framework/vue#for-typography to see if you need to override the CSS of the Authentication Component

**Comment by jordanranz** [comment]
@mspoulsen, could you help me understand which styles are affected in your app?

**Comment by mspoulsen** [comment]
@kendevops That is not the issue. The issue is that when I wrap my app in `<amplify-authenticator>` then the styling of my app is affected.

Here is one example from my app:
Before:
![before](https://user-images.githubusercontent.com/10956790/84567805-67aa0600-ad7b-11ea-8623-46e2dc23695b.png)

After:
![after](https://user-images.githubusercontent.com/10956790/84567808-71336e00-ad7b-11ea-990f-03575e286ee8.png)

So it must apply some global styling of some sort?

@jordanranz 
I have not investigated it. I hate investigating css. I might if I can find the time. Instead I came up with another solution where I use the `onAuthUIStateChange` to control what to show. But it would be nice of course if I could just wrap it in `<amplify-authenticator>`

**Comment by Cigoler** [comment]
Yeah I noticed this as well.

In the CSS for the amplify-authenticator tag if you untick box-sizing: inherit it should go back to normal but i don't know what is adding it.

**Comment by mspoulsen** [comment]
Yeah, it is really annoying :roll_eyes:

**Comment by mspoulsen** [comment]
I wrote the AWS support team and they send me the solution:

In order to troubleshoot the issue, I did some research on my end and:
1. I came across this GitHub notice [1] which mentions that Amplify @3.x.x has some breaking changes.
2. I found out that for using aws-amplify-react's Authenticator Component, you will need to import the styles within your application . Please import the following line of code within your App.js to import the authentication page styles:
```
import '@aws-amplify/ui/dist/style.css';
``` 
This is addition to the imports in the main.js file that is mentioned here[2]
3. Once this change is incorporated, the authentication page styling should work as expected.

Could you please add the above in your application and let me know if the issue still persists? In case the issue still persists, I would request to share a minimal code snippet of your application and other relevant details so that I can try to  reproduce the same on my end if required to further troubleshoot the issue.

I hope this information was useful. Please do let me know if you have any additional queries/concerns that I can assist you with. I would be glad to do the same. 

Wishing you a good day ahead!

-----------------
References
----------------
1. https://github.com/aws-amplify/amplify-js#notice 
2.https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue

**Comment by mspoulsen** [comment]
I use `onAuthUIStateChange` from ```@aws-amplify/ui-components``` instead.

**Comment by sammartinez** [comment]
The above pull request resolves this issue. Closing this issue as these changes are in our `unstable` branch and will be in the next release.

**Comment by jleskovar** [comment]
To anyone else that still sees this issue - be sure to use <amplify-auth-container>, and have your main "Logged In" component as a conditional sibling along side <amplify-sign-in>, like so:
```
<template>
  <amplify-auth-container>
    <amplify-authenticator v-if="authState !== 'signedin'">
    ...
    </amplify-authenticator>
    <v-app dark v-if="authState === 'signedin'">
    ...
    </v-app>
  </amplify-auth-container>
</template>
```
