### ISSUE TITLE
Auth UI Component: customizing text size has no effect

### ISSUE THREAD

**Issue by mspoulsen** [aws-amplify/amplify-js#6073]
Customizing the font-family and colors work:

```
"--amplify-primary-color": "white",
"--amplify-font-family": "Roboto"
```

But the text size has no effect:

```
"--amplify-text-xxs:": "40px",
"--amplify-text-xs:": "40px",
"--amplify-text-sm:": "40px",
"--amplify-text-md:": "40px",
"--amplify-text-lg:": "40px"
```

Anyone experienced the same problem?

**Comment by jordanranz** [comment]
@mspoulsen,

Could you post the css file content for this. Also, which framework are you using?

I am able to use the css var like so:
```
:root {
    --amplify-text-md: 40px;
}
```

**Comment by mspoulsen** [comment]
I am using Vue. Ok, since you were able to I tried again and made it work when using a css file. Before I was applying it as style to the app where `--amplify-primary-color` was working but `--amplify-text-sm` was not. Weird, but everything is good now. Thanks :+1:
