### ISSUE TITLE
[ERROR] 31:59.625 AuthError - Username cannot be empty

### ISSUE THREAD

**Issue by Saqlain-Piecyfer** [aws-amplify/amplify-js#6077]
**Describe the bug**
Empty username or password during login throws exception.
I'm using default UI

**To Reproduce**
Just enter empty user/password and signin

**Expected behavior**
It should show the error message....

**Code Snippet**
import * as React from 'react';
import { Platform, StyleSheet, Text, View, SafeAreaView, StatusBar } from 'react-native';
import WS from 'react-native-websocket'

import aws4 from 'aws4-react-native';
import Amplify from 'aws-amplify';
import Auth from '@aws-amplify/auth';
import { createStackNavigator } from '@react-navigation/stack';
import {NavigationContainer} from '@react-navigation/native'
// import { withAuthenticator } from 'aws-amplify-react-native';
import {} from 'aws4-react-native'
const withAuthenticator = require("aws-amplify-react-native").withAuthenticator;

import awsexports from './aws-exports';
Amplify.configure(awsexports);  

import AppNavigator from './src/navigation/AppNavigator'
import { Authenticator } from 'aws-amplify-react-native';
const useAsyncEffect = (f) => {
  return React.useEffect(() => {
    f().then();
    return;
  })
};

function App(props) {
  let ws = null;
  const onOpen = () => {
      console.log('Open!')
    if (ws) {
      ws.send(JSON.stringify({"action":"requestAuctions"}))
    }
  }
  
  console.log(props.authData.signInUserSession.accessToken.jwtToken);
  const wsurl = `**************`
  console.log(wsurl);

  return (
    <View style={{flex:1}}>
      {wsurl ? <WS 
        ref={ws}
        url={wsurl}
        onOpen={onOpen}
        onMessage={console.log}
        onError={console.warn}
        onClose={console.log}
        reconnect={false} // Will try to reconnect onClose
      /> : null}
      <AppNavigator/>
    </View>
  );
}
export default withAuthenticator(App);

**Comment by amhinson** [comment]
I commented on this similar issue, but the red screen is just coming from[ the use ](https://github.com/aws-amplify/amplify-js/blob/master/packages/core/src/Logger/ConsoleLogger.ts#L82)of `console.error `when `signIn` is not successful to make it more visible, but there isn't actually an error happening.

https://github.com/aws-amplify/amplify-js/issues/4870#issuecomment-643344902

**Comment by imoby** [comment]
Sorry to bring this thread up again but you're saying in an actual production app this error or any error at all wont happen? and this only shows locally? @amhinson

**Comment by amhinson** [comment]
Correct, in a production app the red error showing from React Native won't show. They will only show in a development build.

You can test this out by running a [production build locally](https://reactnative.dev/docs/running-on-device#building-your-app-for-production).
