### ISSUE TITLE
image compression on s3 upload

### ISSUE THREAD

**Issue by 24jr** [aws-amplify/amplify-js#6081]
I was looking at an ideal solution to compress image uploads (png, jpeg, svg, gif, idk others potentially). I'm using vue and I didn't know if there was some client side function I should use to minify the photos before I send them with Storage.put which I failed at trying to figure out with an npm package called imagemin.

Or I could upload the images and then have a lambda function trigger when the image gets uploaded but then what can I change the same image or if I use a different s3 bucket would Storage.get not work and same thing with the protected level. 

Seems complicated so I think it would be great if there was a setting that we could have all uploads be minimized on upload by some function behind the scenes that you guys do because you're really smart and make common hard things easy. Sort of like in auth you can do add user to group on sign up but instead minimize image on upload.

**Comment by ashika01** [comment]
@24jr We are working on storage improvements. Will take this into account as feature request

**Comment by 24jr** [comment]
@ashika01 ok great also wonder if there would be a good way to intertwine the predictions that detects inappropriate content on the upload or if that should be handled separately

**Comment by m98** [comment]
Is there any progress with this issue?
In my case, users can upload profile pictures, and I need to get a thumbnail size of it with `Storage.get`.

**Comment by abdallahshaban557** [comment]
Hi @m98 , we are exploring enabling this. We will provide an update when we have made some progress.

**Comment by dylan-westbury** [comment]
Are we thinking to do compression in the client, or something like resizing on the fly? 

https://aws.amazon.com/blogs/compute/resize-images-on-the-fly-with-amazon-s3-aws-lambda-and-amazon-api-gateway/

**Comment by nadetastic** [comment]
related #10930

**Comment by nadetastic** [comment]
Following up here - we've identified this as a documentation improvement to provide suggestions on how solve this and have will be tracking this request as an [issue](https://github.com/aws-amplify/docs/issues/6629) in the docs repo instead.
