### ISSUE TITLE
add the option to change cognito url  

### ISSUE THREAD

**Issue by nirsnappy** [aws-amplify/amplify-js#6086]
**Is your feature request related to a problem? Please describe.**
we want to do complex stuff in the cognito triggers but there is a lot that missing like the user ip, so we basically want to work with a lambda that will proxy the request and add meta data but then we cant use amplify

**Describe the solution you'd like**
the simplest solution  will be to control this via env variable the code change is minimal.

**Describe alternatives you've considered**
in the future probably want to see this as an option that can pass to the configure method

**Additional context**
if i will open pull request to support env variable will you approve it ?

**Comment by spencerbeggs** [comment]
PRs for this are here, waiting for review:

https://github.com/aws-amplify/amplify-js/pull/6124
https://github.com/aws-amplify/amplify-js/pull/4930

**Comment by sammartinez** [comment]
The above pull request have been merged and/or closed. Resolving this issue.
