### ISSUE TITLE
Unable to hide or disable sign up in Amplify UI

### ISSUE THREAD

**Issue by crcommons** [aws-amplify/amplify-js#6089]
**Is your feature request related to a problem? Please describe.**
Previous version of the Amplify UI allowed you to hide or disable various UI components in both the the authenticator component and the withAuthenticator HOC. However, with the new release, I am unable to hide/disable the sign up component. I can't find any information about this in the documentation either. I'm not sure if it's missing or if it's not possible.

**Describe the solution you'd like**
Pass in configuration to the AmplifyAuthenticator component that hides the sign up component (and removes the sign up link from the signIn component)

**Describe alternatives you've considered**
I've considered using the hosted UI configured in the Amplify console, but would prefer to use the Amplify UI

**Comment by amhinson** [comment]
@crcommons Could you share what Amplify libraries you are you using and their versions?

**Comment by crcommons** [comment]
@amhinson I'm using @aws-amplify/ui-react 0.2.8 and aws-amplify 3.0.17

**Comment by jordanranz** [comment]
Same question as: https://github.com/aws-amplify/amplify-js/issues/6045

For React it would be:
```
<AmplifyAuthenticator>
  <AmplifySignIn slot="sign-in">
    <div slot="secondary-footer-content"></div>
  </AmplifySignIn>
</AmplifyAuthenticator>
```

**Comment by crcommons** [comment]
Thanks, @jordanranz! It would be great to add this to the documentation if possible.

**Comment by jordanranz** [comment]
I ended up adding a first class prop to the sign in component. It is available on `@aws-amplify/ui-react`. Usage:
```
<AmplifyAuthenticator>
  <AmplifySignIn slot="sign-in" hideSignUp></AmplifySignIn>
</AmplifyAuthenticator>
```
Let me know if you are able to test this out

**Comment by crcommons** [comment]
@jordanranz just tested and it works! Thanks!

**Comment by Nxtra** [comment]
> I ended up adding a first class prop to the sign in component. It is available on `@aws-amplify/ui-react@unstable`. Usage:
> 
> ```
> <AmplifyAuthenticator>
>   <AmplifySignIn slot="sign-in" hideSignUp></AmplifySignIn>
> </AmplifyAuthenticator>
> ```
> 
> Let me know if you are able to test this out

Thanks for your solution. 
Is there currently a way to configure this behaviour when using the `withAuthenticator` HOC?

**Comment by amhinson** [comment]
There isn't currently a way to use this with `withAuthenticator`, but switching to `AmplifyAuthenticator` shouldn't be too much effort. Here is our recommended usage: https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#recommended-usage

**Comment by smtech-learning** [comment]
how to bring a custom sign in form when I use AmplifyAuthenticator ?
thx for ideas. I don't want to use the default sign in form.

**Comment by markomelko** [comment]
@smtech-learning you could use https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js :) my way too since ready components doesnt work as I want.

**Comment by sebvdw** [comment]
Hi there, I'm struggling to move over from withAuthenticator to AmplifyAuthenticator, do you know how i could troubleshoot or test for what the issue is?

**Comment by Nxtra** [comment]
> Hi there, I'm struggling to move over from withAuthenticator to AmplifyAuthenticator, do you know how i could troubleshoot or test for what the issue is?

This is my setup:
```
    <AmplifyContainer>
      <AmplifyAuthenticator>
        <AmplifySignIn slot="sign-in" hideSignUp></AmplifySignIn>
      </AmplifyAuthenticator>
    </AmplifyContainer>
```
Is your problem specific to hiding sign up? If not and more help is necessary can you create a separate issue or stackoverflow thread? Then I will tackle it there.

**Comment by sebvdw** [comment]
> > Hi there, I'm struggling to move over from withAuthenticator to AmplifyAuthenticator, do you know how i could troubleshoot or test for what the issue is?
> 
> This is my setup:
> 
> ```
>     <AmplifyContainer>
>       <AmplifyAuthenticator>
>         <AmplifySignIn slot="sign-in" hideSignUp></AmplifySignIn>
>       </AmplifyAuthenticator>
>     </AmplifyContainer>
> ```
> 
> Is your problem specific to hiding sign up? If not and more help is necessary can you create a separate issue or stackoverflow thread? Then I will tackle it there.

Hi thanks so much for your reply! I realised it was an issue of conflicting packages, since i installed both npm install aws-amplify aws-amplify-react and @aws-amplify/ui-react. Thank you so much for your response.

**Comment by acevedomiguel** [comment]
for those looking for the solution for `withAuthenticator`

```
import { withAuthenticator } from '@aws-amplify/ui-react'

function Profile() {
   return (...)
}

export default withAuthenticator(Profile, { hideSignUp: true })
```

**Comment by anjanvb** [comment]
> for those looking for the solution for `withAuthenticator`
> 
> ```
> import { withAuthenticator } from '@aws-amplify/ui-react'
> 
> function Profile() {
>    return (...)
> }
> 
> export default withAuthenticator(Profile, { hideSignUp: true })
> ```

Would love to get the [documentation](https://docs.amplify.aws/lib/auth/getting-started/q/platform/js/#option-1-use-pre-built-ui-components) updated with this.

**Comment by ufo525** [comment]
> for those looking for the solution for `withAuthenticator`
> 
> ```
> import { withAuthenticator } from '@aws-amplify/ui-react'
> 
> function Profile() {
>    return (...)
> }
> 
> export default withAuthenticator(Profile, { hideSignUp: true })
> ```

does this mean someone can still forge a http request to do the sign up?

**Comment by vorant94** [comment]
And what about disabling sign up on the backend? I doubt hiding UI is a reliable solution. It would be nice to have a way to only allow sign ups via AWS admin sdk/cli/console commands

**Comment by nadetastic** [comment]
@vorant94 if you are looking to disable self registration, then you can do so by going to the Sign-up experience tab under Self-service sign-up, set Self-registration to Disabled.

With this disabled, you can only create new users with AdminCreateUser API requests through the AWS CLI,SDK or through the Cognito console.

**Comment by da-poodle** [comment]
> @vorant94 if you are looking to disable self registration, then you can do so by going to the Sign-up experience tab under Self-service sign-up, set Self-registration to Disabled.
> 
> With this disabled, you can only create new users with AdminCreateUser API requests through the AWS CLI,SDK or through the Cognito console.
> 
> ![Disable SelfRegistration](https://user-images.githubusercontent.com/87148442/252391231-b2995f11-92d5-4e5d-b4cd-2218c1b148de.png)

You need to do both, it looks like amplify configuration doesn't allow you to disable sign in via config, but you can hide using the `{ hideSignUp: true }` parameter, with both you have no signup showing and can't do signup if it is showing.

**Comment by yayun-12** [comment]
It is possible to disable signup in the user pool using amplify
Running `amplify override auth` will create override.ts with empty override function
Then add the following and push:
```
export function override(resources: AmplifyAuthCognitoStackTemplate, amplifyProjectInfo: AmplifyProjectInfo) {
    resources.userPool.adminCreateUserConfig = {
        allowAdminCreateUserOnly: true,
    }
}
```

**Comment by rlly92** [comment]
> > @vorant94 if you are looking to disable self registration, then you can do so by going to the Sign-up experience tab under Self-service sign-up, set Self-registration to Disabled.
> > With this disabled, you can only create new users with AdminCreateUser API requests through the AWS CLI,SDK or through the Cognito console.
> > ![Disable SelfRegistration](https://user-images.githubusercontent.com/87148442/252391231-b2995f11-92d5-4e5d-b4cd-2218c1b148de.png)
> 
> You need to do both, it looks like amplify configuration doesn't allow you to disable sign in via config, but you can hide using the `{ hideSignUp: true }` parameter, with both you have no signup showing and can't do signup if it is showing.

I've found this to be the best option tbh. at least there's an additional layer of safety. Thanks!

**Comment by OperationalFallacy** [comment]
Is there a way to disable the hosted UI completely?

Given that Authenticator UI does the same stuff 
Or its too ingrained into the templates? I see about a dozen resources in Cloudformation being created.

**Comment by vforvasquez** [comment]
I have updated my user pool and still see the "Create Account" tab. When I try to create an account I see the error "User creation is not allowed for this user pool." so I know I have the setting correct.

I have also tried adding the property as per the docs but those are also not working:

`<Authenticator hideSignUp={true}>`

What other options are there?
