### ISSUE TITLE
[Auth][Cognitio][AppSync] authorization token is missing

### ISSUE THREAD

**Issue by batical** [aws-amplify/amplify-js#6092]
**Describe the bug**
In some case, the authorization token is not present int the api graphQL. Mainly after the Refresh token expiration expire.

**To Reproduce**
On dev env, I set the expiration token to one day in Cognito UI. When I try to bring my application back from background, I am still connected, but no request are done. error 401.

```
createAuthLink({
        url,
        region: config.awsmobile.aws_appsync_region,
        auth: {
          type: AUTH_TYPE.AMAZON_COGNITO_USER_POOLS,
           jwtToken: async () => (await Auth.currentSession()).getIdToken().getJwtToken()
        }
      }),
      createSubscriptionHandshakeLink({
        url,
        region: config.awsmobile.aws_appsync_region,
        auth: {
          type: AUTH_TYPE.AMAZON_COGNITO_USER_POOLS,
           jwtToken: async () => (await Auth.currentSession()).getIdToken().getJwtToken()
        }
      })
```

I add a little piece of code in the jwtToken: async() part. 
if I got an exception on (await Auth.currentSession()).getIdToken().getJwtToken()
I tried some thing
```
 const cognitoUser = await Auth.currentAuthenticatedUser()
      const currentSession = await Auth.currentSession()
      cognitoUser.refreshSession(currentSession.refreshToken(), (err, session) => {
        console.log('session', err, session)
        const { idToken, refreshToken, accessToken } = session

        return idToken.getJwtToken()
      })

```

I receive clear information that there was not authenticated user.

So In this case I forced a signout()

The app is going back on the login stack screen. I

I try to signIn, I receive a token. (I even add a custom memoryStorage to log everything). I receive token etc everything is fine. But still I receiving error 401 and no authorization header a present in the request. This is affecting all my user when the Refresh token expiration expire

<img width="715" alt="Capture d’écran 2020-06-15 à 15 57 00" src="https://user-images.githubusercontent.com/7248073/84666018-daa0b180-af20-11ea-8956-5660627be5bc.png">

**Expected behavior**
AppSync request done with success.

If I kill the app / delete reinstall it, it is working

**What is Configured?**
Auth.configure({ ... awsmobile, storage: AuthMemoryStorage })

With aws mobile is exported from amplify cli

```
 const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "xxxxxx",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "xxxxxxx",
    "aws_user_pools_web_client_id": "xxxxxx",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "xxxxxxxx",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "xxxxxxxx-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1",
};
```
 

**Smartphone (please complete the following information):**
- all device(android, iOS, simulator)

```
 "@aws-amplify/api": "^3.1.16",
    "@aws-amplify/auth": "^3.2.13",
    "@aws-amplify/core": "^3.3.3",
    "@aws-amplify/storage": "^3.2.6",
    "amazon-cognito-identity-js": "^4.3.1",
    "aws-appsync": "^3.0.3",
```

**Comment by amhinson** [comment]
Hey @batical are you still having issues here?

**Comment by batical** [comment]
I change my code to use the authenticator Component from  react native amplify and updating appsync as much as possible.

- On staging app with one day token, people are disconnected every day but everything is working after signin.

- On prod
Last week a user/customer had a similar issue. I can analyze more his case but :
- status "signin" but no data receive from query. (pretty sure it is a missing token/header)
- Signing out and signing fix his problem.

**Comment by amhinson** [comment]
Ok thanks for the info! A few things:
- Can you enable logging `window.LOG_LEVEL = 'DEBUG'` and share the output? That will help track down where the issue might be.
- Can you share more about your Auth usage? Code snippets would be good, but ideally if you could provide a small sample repo that shows the behavior you're seeing, that would be the quickest way for us to debug this.
- Side note that might be related: I see you have a few modular packages in your `package.json` (i.e. `@aws-amplify/core`). We recommend only using `aws-amplify` and importing from there directly in your code (`import {Auth} from 'aws-amplify'`) instead of modular imports (`import Auth from '@aws-amplify/auth'`) due to version mismatches that might occur between the packages.

**Comment by batical** [comment]
Thanks for you answer.
We are pretty late for some delivery and bug etc (as a lot of startup :p)

- I will ask a trainee next week to do some logs. But we cannot reproduce it all the time and the app is auto signout. We will try
- we are using a monorepo with 2 ReactJS website. I pay attention to have the exact same version with no hoisting etc
the actual version are
"aws-appsync": "^4.0.1",
"aws-amplify": "^3.3.3",
 "aws-amplify-react-native": "^4.2.7",
"amazon-cognito-identity-js": "^4.4.0",

But we are importing like this 
import Auth from '@aws-amplify/auth'

If I remember well it was for circular dependency warning. (don't remember well)

Should I go back to import {Auth} from 'aws-amplify' with a single import package ?

**Comment by amhinson** [comment]
I'd suggest just using `import {Auth} from 'aws-amplify'` for consistency, but that is likely not as much of an issue as long as you just have `aws-amplify` in your `package.json` and don't have multiple versions of packages (i.e. `@aws-amplify/auth`).

I'm going to label this as "can't reproduce" for now, but feel free to follow up in the future in you continue to run into issues.
