### ISSUE TITLE
Failing to verify email via updateUserAttributes

### ISSUE THREAD

**Issue by nocoli** [aws-amplify/amplify-js#6100]
I am trying to mark an email address as verified which is available as per the docs https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminUpdateUserAttributes.html using the adminUpdateUserAttributes call.

I am currently trying to do this via the corresponding non-admin version of this method like so as the admin version doesn't seem to be available (I can see it's been requested in  #5103):
```
Auth.updateUserAttributes(user, {
  email_verified: true
}).then((result) => {
  console.log(result);
});
```
and getting the result logged as 'SUCCESS' in my console but the email is not being verified when I check cognito.

I have tried specifying the attribute in the following ways which all log as successful calls in the code above but none seem to be fixing the problem.

```
email_verified: true,
email_verified: 'true',
email_verified: 'True',
'email_verified': true,
'email_verified': 'true' 
```

**To Reproduce**

1. Call `Auth.updateUserAttributes` method as per above
2. Check user in cognito to see email has not bee verified

**Expected behavior**
Either the `email_verified` should be marked at true in cognito or the call should not be returning `SUCCESS` as per the code above.

**Comment by evcodes** [comment]
Hi nocoli, what application are you currently working on building? I want to walk through the steps but just needed some more context from you.

Thank you!

**Comment by nocoli** [comment]
Building an application in which our clients each have their own user pool. Users can add new users to their own user pool. New user gets invitation email with username, password and link to application to login. User then logs in for the first time and is asked to update their password + set given and family names before proceeding through to the application as an authorized user. 

Basically from here I want to allow the user to be able to change their password if they forget it which is why I am trying to mark the email address as verified.  Please let me know if there is any other details that might assist.

**Comment by amhinson** [comment]
@nocoli It isn't currently possible to update the `email_verified` attribute for a user with Cognito through the standard API. You can, however, work with the AWS SDK directly to update this attribute, if needed: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#adminUpdateUserAttributes-property
