### ISSUE TITLE
Amplify Datastore : Schema is created partially on the local IndexedDb

### ISSUE THREAD

**Issue by coooldevops** [aws-amplify/amplify-js#6101]
**Describe the bug**
Schema is created partially on the local IndexedDb
 DataStore - Sync error DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.

I am calling the datastore query api to get the list of objects in a Vue application. I think schemInit fails as it can not create a schema 

**To Reproduce**
The model generated successfully by Amplify and all dynamodb and appsync in a good state
I have attached the model and schema to this report

**Expected behavior**
It should return the exisiting objects or return null/empty if there is no object

**Code Snippet**
```
getQuestionnaires ({ commit }, payload) {
    return new Promise((resolve, reject) => {
      DataStore.query(Questionnaire, Predicates.ALL)
      .then((response) => {
          commit(types.QUESTIONNAIRES, response)
          commit(types.TOTAL_QUESTIONNAIRES, response.length)
          resolve()
      })
      .catch((error) => {
        console.log('error getting questionnaires...', error)
        reject(error)
        // handleError(error, commit, reject)
      })
    })
  },
```

Schema generated for model:

[index.txt](https://github.com/aws-amplify/amplify-js/files/4790449/index.txt)
[schema.txt](https://github.com/aws-amplify/amplify-js/files/4790450/schema.txt)

**Screenshots**

<img width="1181" alt="Screen Shot 2020-06-17 at 2 48 59 pm" src="https://user-images.githubusercontent.com/67038916/84857347-2e8bd180-b0ac-11ea-94d8-29d3159b7f45.png">
<img width="1438" alt="Screen Shot 2020-06-17 at 2 48 36 pm" src="https://user-images.githubusercontent.com/67038916/84857349-2fbcfe80-b0ac-11ea-8e4e-4011a23c9c55.png">
<img width="1439" alt="Screen Shot 2020-06-17 at 2 48 22 pm" src="https://user-images.githubusercontent.com/67038916/84857350-30ee2b80-b0ac-11ea-833f-5a71e7dc4108.png">

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.
* Which resources do you have configured?
  * If applicable, please provide your `aws-exports` file:
```
const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:ddddddddd",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_s6uEdBxIM",
    "aws_user_pools_web_client_id": "dxxxxxxxxxxxxx",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https:/xxxxxx.amazonaws.com/dev",
            "region": "ap-southeast-2"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://xxxxxxxxxx.appsync-api.ap-southeast-

```

```
    "@aws-amplify/core": "^3.3.3",
    "@aws-amplify/datastore": "^2.2.3",
    "@aws-amplify/pubsub": "^3.0.13",
    "@aws-amplify/ui-vue": "^0.2.6",
    "aws-amplify": "^3.0.17",
    "aws-amplify-vue": "^2.1.1",
```
**Smartphone (please complete the following information):**

-
- Browser [e.g. Chrome, ]
- OS : MacOsX

**Comment by coooldevops** [comment]
I had queries=null in my mode , removed that , still no chance!

**Comment by mauerbac** [comment]
Hi @coooldevops - we just took a look at your issue. Would it be possible to get the schema.graphql file to get a better understanding of your issue?

**Comment by amhinson** [comment]
@coooldevops Could you share your `schema.graphql`? We'll need that to better help you resolve this issue.

**Comment by coooldevops** [comment]
Sorry I do not have the code now. I have changed it substantially and
decided not to  use  amplify.

**Comment by amhinson** [comment]
Ok no problem! Sorry for the trouble you were having. I'm going to close this issue for now, but feel free to reopen it if you do come back around to testing it out and see the same behavior.
