### ISSUE TITLE
Inconsistent and Unclear refresh session experience. 

### ISSUE THREAD

**Issue by myspivey** [aws-amplify/amplify-js#6123]
**Describe the bug**
We have a need to keep sessions alive. We are using Cognito federated with Auth0. As others have noted the [docs](https://docs.amplify.aws/lib/auth/overview/q/platform/js) state that calling `Auth.currentSession` however we have not found success in that as we are finding the same issue as found in this [ticket](https://github.com/aws-amplify/amplify-js/issues/4850). I came across [this ticket](https://github.com/aws-amplify/amplify-js/issues/2529#issuecomment-455271043) which implies that only works for certain providers and to use refreshHandlers but could not really find any real documentation on it so have not tried it yet. 

We have tried two approaches so far. One approach works for half of the devs while the other approach works for the other half. Either method seems to break for half of the people logged in. They are both included below along with our config. We got the idea from these tickets: [446](https://github.com/aws-amplify/amplify-js/issues/446#issuecomment-555559150) [639](https://github.com/aws-amplify/amplify-js/issues/639#issuecomment-553669507). I came across a [third option](https://medium.com/tensult/how-to-refresh-aws-cognito-user-pool-tokens-d0e025cedd52) but this feels very much like an anti-pattern to try and breakout of the SDK.

At this point it feels like we are taking pretty big swings in the dark and starting to get a bit off the reservation if you will on the accepted practices of the SDKs. Hoping for some guidance on where the bug lands as we get failures regardless of solution and an inconsistent experience for our devs and end users. Any clarity here would be very appreciated.

**To Reproduce**

1. Login with Cognito
2. Let sit more than one hour
3. See error

**Expected behavior**
Have refreshSession successfully refresh session until they close the browser.

**Code Snippet**
Works for one half of devs (throws the below screenshot, I am guessing related to this [ticket](https://github.com/aws-amplify/amplify-js/issues/5917)):
```
const session = await Auth.currentSession();
const user = await Auth.currentAuthenticatedUser();

user.refreshSession(session.getRefreshToken(), (e, s) => {});
```

Works for other half (this one personally works for me every-time):
EDIT: Looking at the typings, I am not sure how this ever worked
```
const user = await Auth.currentAuthenticatedUser();

user.refreshSession(user.getSignInUserSession.refreshToken, (e, s) => {
```

**Screenshots**
![image](https://user-images.githubusercontent.com/2472925/85077600-ec33c480-b17f-11ea-8253-983e8822888d.png)

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.
* Which resources do you have configured?

`AuthAmplify.federatedSignIn({ customProvider: 'Auth0' })`

```
Auth: {
    mandatorySignIn: true,
    region: REDACTED,
    userPoolId: REDACTED,
    userPoolWebClientId: REDACTED,
    identityPoolId:REDACTED,
    oauth: {
      domain: REDACTED,
      scope: [
        'email',
        'openid',
        'profile',
        'aws.cognito.signin.user.admin'
      ],
      redirectSignIn: `${URL}/callback`,
      redirectSignOut: URL,
      responseType: 'token'
    },
    federationTarget: 'COGNITO_USER_POOLS'
  },
```

<details>
  <summary><strong>Environment</strong></summary>

```
 System:
    OS: macOS 10.15.5
    CPU: (24) x64 Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
    Memory: 3.67 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.14.1/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Browsers:
    Chrome: 83.0.4103.106
    Safari: 13.1.1
  npmGlobalPackages:
    @nrwl/cli: 9.3.0
    avn-nvm: 0.2.2
    avn: 0.2.4
    firebase-tools: 8.4.1
    fkill-cli: 6.0.1
    http-server: 0.12.3
    npm-check: 5.9.2
    npm: 6.14.5
    webpack: 4.43.0
    yarn-check: 0.0.3
    yarn: 1.22.4
```

</details>

**Comment by sammartinez** [comment]
@myspivey Are you using `aws-amplify` or are you just using `amazon-cognito-identity-js` only? I'm not seeing either within your environment information. Also, which versions of those packages are you using? Thanks ahead of time

**Comment by myspivey** [comment]
Sorry, here you go @sammartinez!  
  "aws-amplify": "3.0.18",
  "aws-appsync-auth-link": "^2.0.2",
  "aws-appsync-subscription-link": "^2.1.0",

**Comment by sammartinez** [comment]
Thanks ! We'll have someone dive deep on this as soon as we can.

**Comment by myspivey** [comment]
@sammartinez Awesome! I am happy to help jump on a call to talk through the problem as well if needed.

**Comment by elorzafe** [comment]
@myspivey just to be clear, you are doing social federation with Cognito User Pools right?

**Comment by elorzafe** [comment]
@myspivey how did you configure Auth0 as OpenID provider on Cognito UserPool?

**Comment by myspivey** [comment]
It is setup through SAML not OpenID.

**Comment by mauerbac** [comment]
Any updates here?

**Comment by myspivey** [comment]
Nothing from our end. We however have decided to switch away from Auth0 and using Cognito for user pools to OpenID with Okta and only federation and so far have not run into this problem.

**Comment by sammartinez** [comment]
@myspivey Thanks for the update. Apologizes on the late reply. Are you ok if we resolve this issue since you have moved away from this use case? Please let us know.
