### ISSUE TITLE
DataStore unable to delete item right after update

### ISSUE THREAD

**Issue by mdoesburg** [aws-amplify/amplify-js#6128]
**Describe the bug**
When you try and delete an item from the DataStore, right after doing an update, it gets inserted again.

**To Reproduce**
Use a delete function like this, in which you update a model right before deleting it:
```js
const deleteChecklistItem = async (item) => {
  // Update _source, then delete
  const updatedItem = await DataStore.save(
    CheckListItem.copyOf(item, (updated) => {
      updated._source = APP_SOURCE;
    })
  );

  const deleted = await DataStore.delete(updatedItem);

  console.log(updatedItem._version, deleted._version);
};
```

GraphQL schema:
```graphql
type CheckListItem
  @model
  @auth(rules: [
    { allow: owner, identityClaim: "custom:user_id" },
    { allow: groups, groups: ["Admin"] }
  ])
{
  id: ID!
  title: String!
  checked: Boolean!
  _source: String
}
```

The example above is from the React Native app I am building. In the component which contains the checklist, I also observe the model. After deleting an item it gives the following output:
```js
{opType: "UPDATE", element: Model, condition: undefined, model: ƒ}
{opType: "DELETE", element: Model, condition: {…}, model: ƒ}
13 13 // <--- version numbers I am logging in the delete function
{opType: "INSERT", element: Model, condition: undefined, model: ƒ}
```

I tried re-querying the item from DataStore in between the update and the delete, and passing that item to the delete function, but the outcome is the same.

The only thing that seems to work is waiting for some arbitrary amount of time in between the 2 actions. The following code seemed to work:
```js
const deleteChecklistItem = async (item) => {
  // Update _source, then delete
  const updatedItem = await DataStore.save(
    CheckListItem.copyOf(item, (updated) => {
      updated._source = APP_SOURCE;
    })
  );

  setTimeout(async () => {
    const deleted = await DataStore.delete(updatedItem);

    console.log(updatedItem._version, deleted._version);
  }, 500);
};
```

**Expected behavior**
I expect to be able to delete an item right after updating it, without having to implement some arbitrary timer.

**Additional context**
```
@aws-amplify/datastore: 2.2.3
@aws-amplify/cli: 4.21.3
```

**Comment by mdoesburg** [comment]
@Ashish-Nanda Hey! Do you think we will be able to get a quick fix on this? This doesn't seem like a complicated issue.

It seems like even though I am using `await`, DataStore is not actually done updating the item at the time I call delete on the same item.

**Comment by mdoesburg** [comment]
@iartemiev Update: This doesn't seem to happen when I turn off my internet connection. So I am assuming this has something to do with conflict handling?

I am just guessing here, but it seems like something like this is happening:
1. I update the item
2. The update gets send to the cloud
3. I delete the item, but I receive the updated item (from the cloud) on my subscription at the same time or before I am trying to delete the item, leading to a conflict in which UPDATE > DELETE or something? Resulting in it being re-inserted into the DataStore?

**Comment by amhinson** [comment]
@mdoesburg Just merged a fix for this. If you have a chance to test, it's available now with `aws-amplify@unstable`. We should be doing a release sometime early next week 👍
