### ISSUE TITLE
Authorizing subscriptions without allowing mutations

### ISSUE THREAD

**Issue by mdoesburg** [aws-amplify/amplify-js#6137]
**Which Category is your question related to?**

GraphQL Transform: @auth

**Amplify CLI Version** 

4.17.1

**What AWS Services are you utilizing?**

- Amplify
- AppSync
- DynamoDB
- Cognito

Within the Amplify framework I am using:
- Auth
- DataStore

**Provide additional details e.g. code snippets**

I am using Amplify and React Native to build a todo app. All users in this app share one todo list. Every user can create new todos, and mark todos as completed or uncompleted, but only the user who initially created the todo is allowed to delete it.

My schema looks like this:
```graphql
type Todo 
  @model
  @auth(rules: [{ allow: owner, operations: [create, delete] }])
{
  id: ID!
  name: String!
  completed: Boolean!
  owner: String
}
```

**Problem:**
Everything works fine but I can't figure out how to make the subscription part do what I want. It is my understanding that the create and delete operations listed in my schema also protects the subscriptions related to those. In this case: onCreate and onDelete. So basically only the owner of the todo can subscribe to those events. You can see how this is weird for the users of my app, because they won't see newly created todos until that todo is updated (since they are allowed to subscribe to onUpdate), and they wont know that a todo got deleted until they try and update that todo themselves.

I've read the following things:
https://github.com/aws-amplify/amplify-cli/issues/2636
https://aws-amplify.github.io/docs/cli-toolchain/graphql#authorizing-subscriptions

But I can't figure out how to make it where other users can still subscribe to onCreate and onDelete without being able to do the delete mutation, which seems like a trivial problem to me.

**Comment by mdoesburg** [comment]
Maybe we should close this issue in favor this one: https://github.com/aws-amplify/amplify-js/issues/6108 as I think the issue is related. I also left a more in-depth comment here: https://github.com/aws-amplify/amplify-js/issues/6108#issuecomment-647708908

**Comment by mauerbac** [comment]
Thanks @mdoesburg . We are working on #6108 and will close this in favor of tracking progress there.
