### ISSUE TITLE
How does the Vue login property use the event method

### ISSUE THREAD

**Issue by MoonCheung** [aws-amplify/amplify-js#6144]
**Describe the bug**
After clicking the amplify-sign-in component attribute to add event method, there is no reaction and no information is printed out from the browser console. Is it wrong for me to operate the added event method correctly? Please help my component to work, thank you

**To Reproduce**

1. The code in auth.vue is as follows
```vue
<amplify-sign-in
  slot="sign-in"
  username-alias="email"
  :form-fields.prop="formFields"
  header-text="登录到您的帐户"
  submit-button-text="登录"
  @submit="onSubmints"
></amplify-sign-in>

<script>
import Amplify, { Auth, Hub, API } from 'aws-amplify'

export default {
  ...省略
  methods: {
    onSubmints(event) {
      console.log('cat event:', event)
    }
  }
}
</script>
```
2. Clicking the login button doesn't work
3. No information was printed from the browser console

**Expected behavior**
I hope the Amplify -sign-in component prints out the information from the browser console after clicking the login button to help me get these questions to work

**Comment by sammartinez** [comment]
@MoonCheung Can you provide us with your `package.json` along with which versions of our UI Components you are using?

**Comment by MoonCheung** [comment]
@sammartinez My related project package.JSON contains amplify UI Component，You can see below：
```json
{
  "name": "vue-cognito",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    ...省略
  },
  "dependencies": {
    "@aws-amplify/ui-vue": "^0.2.7",
    "aws-amplify": "^3.0.17",
    "core-js": "^3.6.5",
    "normalize.css": "^8.0.1",
    "vue": "^2.6.11",
    "vue-router": "^3.2.0",
    "vuex": "^3.4.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.4.0",
    "@vue/cli-plugin-eslint": "^4.4.0",
    "@vue/cli-service": "^4.4.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.1.3",
    "eslint-plugin-vue": "^6.2.2",
    "node-sass": "^4.12.0",
    "prettier": "^1.19.1",
    "sass-loader": "^8.0.2",
    "vue-template-compiler": "^2.6.11"
  }
}
```
