### ISSUE TITLE
Could Not load Image after Upload to S3 as JPEG File

### ISSUE THREAD

**Issue by ashishsoni** [aws-amplify/amplify-js#615]
I am able to upload the image to s3 but when i try to view or download back i am getting below error

![s3_upload_image_error](https://user-images.githubusercontent.com/877509/38507544-d0636d08-3bea-11e8-9d5c-a8ace26ceadc.png)
After capturing from camera 

this.camera.getPicture(options).then(
        imageData => {
          this.base64Image = "data:image/jpeg;base64," + imageData;
});

Storage.put(id , photo, { contentType: 'image/jpeg' })
        .then(res => {
//do something
      });

**Comment by mlabieniec** [comment]
@ashishsoni can you see what the response code is from the service? 404 / 500 ? Also, how do you have Storage configured i.e. Public / Private? Can you add a [debug log](https://aws.github.io/aws-amplify/media/logger_guide) here as well, thanks.

**Comment by richardzcode** [comment]
Hey @ashishsoni , If upload with base64 encoded, you'll need to set 'ContentEncoding' with 'base64'

#576 has more discussion on this.

**Comment by elorzafe** [comment]
It was added a code snippet on our docs on how to use it on react-native

```javascript
import RNFetchBlob from 'react-native-fetch-blob';

readFile(filePath) {
    return RNFetchBlob.fs.readFile(filePath, 'base64').then(data => new Buffer(data, 'base64'));
}

readFile(imagePath).then(buffer => {
    Storage.put(key, buffer, {
        contentType: imageType
    })
}).catch(e => {
    console.log(e);
});
```
@ashishsoni  I am closing the issue for now, but feel free to reopen in case this doesn't work for you.
