### ISSUE TITLE
[Feature request] `Storage.get` to return headers, not just URL

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/amplify-js#6157]
**Is your feature request related to a problem? Please describe.**

In https://github.com/aws-amplify/amplify-js/discussions/6135, @mtakac wanted to check the headers of a file instead of downloading it, but we only expose the URL with `Storage.get`. it'd be nice to give the option to return headers (or just expose headers anyway if it is no cost to us)

**Describe the solution you'd like**

as above

**Describe alternatives you've considered**

add a `Storage.head` api? since it maps to the HTTP HEAD request

**Comment by Amplifiyer** [comment]
`Storage.get()` without `download:true` doesn't actually make a request. It just provides a presigned URL that you can load to get the file. This signed URL can also be parsed to capture the request headers generated by Amplify using SIG_V4. However again note that no service calls are made.

With `download:true` the file is downloaded by the Amplify itself and given to the client. The file is of blob type. Let us know if there is still request for a feature.
