### ISSUE TITLE
Auth.signup not returning a promise

### ISSUE THREAD

**Issue by SunstroUS** [aws-amplify/amplify-js#6159]
**Describe the bug**
When a user goes to signup through our site, after submitting a form we call Auth.signup({..}) and await a promise before we continue. In the network traffic I can see that we are getting a promise back, and the user is being created successfully in Cognito, but no promise. 

**To Reproduce**
```js
try {
     // Create new user
      await Auth.signUp({
        username: fields.email,
        password: fields.password,
        attributes: { email: fields.email, name: fields.name },
      });

    // Do something after promise is resolved
}
```

**Expected behavior**
Return a successful promise when there are no errors

Device: macOS
- OS: 10.15.4
- Browser Chrome
- Version 83.0.4103.106

**Comment by IamFlowZ** [comment]
I've also experienced this issue.

Device: Linux (Fedora 32)
    OS: 5.6.18
    Browser Firefox
    Version 77.0.1

**Comment by elorzafe** [comment]
I tried with the latest Auth version `3.2.14` and is working for me on Chrome and Firefox.

Are you sure your promise is not being reject because of `UsernameExistsException`?

Can you check the network response from the service ?

Do you have enabled Pre SignUp triggers on your userpool?

**Comment by IamFlowZ** [comment]
1.) Not sure how to verify this.
2.) Network is responding with 200.
3.) No, our user pool doesn't have a pre-signup trigger.

**Comment by elorzafe** [comment]
@IamFlowZ on the catch section can you check if an error is being thrown?

**Comment by SunstroUS** [comment]
@elorzafe Thank you, we had been checking for a set of predefined errors and had gotten a new one unrelated to auth library. Appreciate your help!
