### ISSUE TITLE
Auth.updateUserAttributes - custom attribute with '_verified' gets filtered

### ISSUE THREAD

**Issue by mishellnovosel** [aws-amplify/amplify-js#6164]
**Describe the bug**
I've created a new custom attribute in Cognito called 'custom:dmb_verified'. I'm setting value to it upon registration and everything is working, value is added to the user under this attribute. The problem is when I try to update the value using Auth.updateUserAttributes:

```
const body = {
      'custom:dmb_verified': 'true'
    };

Auth.updateUserAttributes(user, body)
            .then(...);
```

The request to the AWS is created, but the attribute is missing, it's sending empty object [].

- I've tried to add multiple attributes, and all are sent except for the one with "_verified" in it.
- I've changed the attribute ( in code, so it wasn't existing in Cognito ) to "custom:dmb_verified1" and it was missing from request as well
- I've tried to send "custom:dmb_verifie" and it was passed with request ( throw 400 because it doesn't exist )
- I've tried to send "custom:test_verified", and again, it was missing from the request.

**To Reproduce**

1. Create an attribute in Cognito with "_verified" word in
2. Update the value of attribute with Auth.updateUserAttributes
3. Request is missing that attribute ( It's not sent )

**Expected behavior**
I'm expecting that all my custom attributes are sent to AWS Cognito without any problem, even if they do have a "_verified" keyword.

**Comment by sammartinez** [comment]
@mishellnovosel Are you able to provide a code snippet and your `package.json` to us for this issue? Thanks ahead of time.

**Comment by mishellnovosel** [comment]
@sammartinez , unfortunately I had to move on a lot from that case( we've changed the cognito attribute name at time time ).
Now I don't have access to Cognito to create an attribute and to test it with latest version of Amplify.

But code snippet is already mentioned above:

```
const body = {
      'custom:dmb_verified': 'true'
    };

Auth.updateUserAttributes(user, body)
            .then(...);
```

**Comment by sammartinez** [comment]
Understood @mishellnovosel since you have moved on from testing, are you ok with us closing this issue so we can look to help other customers? Please let us know.

**Comment by mishellnovosel** [comment]
@sammartinez I am OK with it. But still, maybe it would be a good idea to write someone in the documentation that "_verified" suffix is reserved word and can not be used with Amplify :)

**Comment by sammartinez** [comment]
Thanks @mishellnovosel will look to do a documentation update for this. :)
