### ISSUE TITLE
How to achieve passing hidden attributes to Cognito with new components?

### ISSUE THREAD

**Issue by KevyVo** [aws-amplify/amplify-js#6168]
**Is your feature request related to a problem? Please describe.**
I am having trouble with making user attribute locale hidden then passing them to AWS Cognitio. I was able to able to do this in the old version of amplify but now with @aws-amplify/ui-react this is no longer possible.

**Describe the solution you'd like**
I would like the amplify team to advise me a solution to my problem or add the feature to be able to do this in this current version of amplify.
1) Being able to add custom field with custom name (for custom cognito attribute or additional standard attributes)
2) Being able to have a style hidden on any field

**Additional [context**]
These are the form fields I am referring to below in the snippets:
![Screen Shot 2020-06-25 at 11 30 54 AM](https://user-images.githubusercontent.com/53957494/85791776-41735700-b6e7-11ea-9c52-f839e8f0ab61.png)
![Screen Shot 2020-06-25 at 8 54 49 AM](https://user-images.githubusercontent.com/53957494/85793540-03c3fd80-b6ea-11ea-86fd-93d022a8fccf.png)

``` <AmplifySignUp
          usernameAlias="email"
          headerText={I18n.get("signUpHeader")}
          slot="sign-up"
          submitButtonText={I18n.get("signUpButtonText")}
          formFields={[
            {
              type: "email",
              label: I18n.get("emailLabel"),
              placeholder: I18n.get("emailPlaceHolder"),
              required: true,
            },
            {
              type: "password",
              label: I18n.get("passwordLabel"),
              placeholder: I18n.get("passwordPlaceHolder"),
              required: true,
            },
            {
              type: "phone_number",
              label: I18n.get("phoneNumberLabel"),
              placeholder: I18n.get("phoneNumberPlaceHolder"),
              required: false,
            },
            {
              type: "hidden",
              value: navigator.language,
            }
          ]}></AmplifySignUp>```

**Comment by KevyVo** [comment]
@jordanranz Was able to help me test the code and we found that if we try to make a user attribute hidden in the form field, then set a pre set a value, it bypasses the logic to set the request value. Jordan is currently working to fix the bug and will get back to me when he has fix the bug.

**Comment by jordanranz** [comment]
Worked with @KevyVo offline. The latest release fixes this issue. Closing this issue now. Please open a new issue if you are experiencing any similar problems

**Comment by calvinchso** [comment]
I also run into this requirement but I'm on Vue 2. Can you advise if there is any way to specify a hidden field when using "formFields" property? Thanks.
