### ISSUE TITLE
Do you plan to migrate legacy UI components such as amplify-photo-picker?

### ISSUE THREAD

**Issue by lorentzca** [aws-amplify/amplify-js#6174]
**Is your feature request related to a problem? Please describe.**
In latest UI components it seems that only the Authentication component can be used.

- [Amplify UI Components](https://tiny.amazon.com/ubnn4bwo)

I want to use other components as well.

**Describe the solution you'd like**
Migrate components other than the Authentication component to latest UI components.

**Describe alternatives you've considered**
Use legacy and latest components together.

Thank you.

**Comment by ashika01** [comment]
@lorentzca Hi we are working on it right now...

For more info, there is a RFC here - https://github.com/aws-amplify/amplify-js/issues/6104

Any there is a PR out for review - https://github.com/aws-amplify/amplify-js/pull/6110

We would be doing more testing before we launch 🚀

**Comment by lorentzca** [comment]
Thank you for your reply!
I'm looking forward to it 😃

**Comment by ashika01** [comment]
Hi, we launched the new components. The use case you are trying to achieve is `s3-image-picker`. Feel free to open up issues or FR as you seem fit. We welcome all feedback.

https://github.com/aws-amplify/amplify-js/issues/6104#issuecomment-656882695
