### ISSUE TITLE
Auth.Signout() method not clearing session token on Chrome

### ISSUE THREAD

**Issue by harshraj93** [aws-amplify/amplify-js#6175]
**Describe the bug**
When constructing an SPA backed by cognito authentication, a logout call (Auth.signOut()) appears to work properly using  Edge /Safari.
When initiating that amplify call from a react hosted application in cloudfront on the Chrome version listed blow, when clicking logout and then the back button, users are not redirected to a login page, but are rather granted access back into the application.

Chrome version : Version 83.0.4103.116 (Official Build) (64-bit)
Amplify version 3.0.7

**To Reproduce**

1. Go to https://d2hmmjidvtlws7.cloudfront.net/
2. Click on Logout button
3. Once navigated to Login screen, click on back button
4. The user session is retained

**Expected behavior**
When the user click on logout button, the user should be navigated back to the sign in screen and on click on browser back button the user must stay on login screen until logged in again.

**Code Snippet**
The below method is called on click of Logot button from the application. It uses the signout method from Amplify.
  handleLogout = () => {
    Auth.signOut()
      .then(data => 
      this.setState({
        navigate: true
      })
      )
      .catch(err => console.log(err));
   
  }

**Screenshots**

**What is Configured?**
Amplify.configure({
  Auth: {
    // REQUIRED - Amazon Cognito Region
    region: 'us-east-1',

    // OPTIONAL - Amazon Cognito User Pool ID
    userPoolId: 'us-east-1_XXXXXXXXX',

    // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
    userPoolWebClientId: 'XXXXXXXXXXXXXXXXXXXXX5mvvi',

    // OPTIONAL - Configuration for cookie storage
    // Note: if the secure flag is set to true, then the cookie transmission requires a secure protocol
    cookieStorage: {
      // REQUIRED - Cookie domain (only required if cookieStorage is provided)
      domain: 'https://XXXXXX.auth.us-east-1.amazoncognito.com'
    },
    // OPTIONAL - Hosted UI configuration
    oauth: {
      domain: 'https://XXXXX.auth.us-east-1.amazoncognito.comn',
      scope: ['openid'],
      redirectSignIn: 'https://d2hmmjidvtlws7.cloudfront.net',
      redirectSignOut: 'https://d2hmmjidvtlws7.cloudfront.net',
      responseType: 'code' // or 'token', note that REFRESH token will only be generated when the responseType is code
    }
  },
 
});

**Comment by Amplifiyer** [comment]
@harshraj93, can you check the local storage of your browser (Dev console -> Application -> Storage) to see if the tokens are getting cleared or not? And when you get back to the signed in page/view, are you able to make any amplify calls successfully?

**Comment by harshraj93** [comment]
The tokens are not stored in browser's local storage as the login authentication is managed by cloudfront itself. The authentication tokens are stored in cookies and they retain themselves when click on back button.
Additionally I am not sure whether this would be blocking the whole process as we get an additional following warning in chrome when the logout button is clicked:
**Cross-Origin Read Blocking (CORB) blocked cross-origin response https://smartfactoryfabric-dev.auth.us-east-1.amazoncognito.com/login?client_id=XXXXXXXXXabh5mvvi&response_type=code&scope=openid&redirect_uri=https://XXXXXs7.cloudfront.net with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.**

**Comment by Amplifiyer** [comment]
@harshraj93, thanks for providing additional details. I don't have a way to sign up in your hosted app so can't reproduce. Let me know if there is a way for me to get an account or reproduce it in another way.

Also just wanted to ensure that oauth.domain in the config your provided earlier is just a typo in this issue but not actually in your app since your app works fine in other browsers.

**Comment by harshraj93** [comment]
I have masked the oauth.domain in the details above and the actual domain works fine. **Ben Eichrost** and **Scott Francis** are contacts from AWS team who will be able to provide access or we can connect over Zoom to discuss this issue

**Comment by adamm-monek** [comment]
Is this just the same as this issue: https://github.com/aws-amplify/amplify-js/issues/614 ?

I am calling `Auth.signOut()` as described in https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js#sign-out
and the local storage is not cleared in Chrome or Firefox

**Comment by harshraj93** [comment]
The issue is different in terms of Sign in as it is not done using Amplify. The sign-in is based on the traditional Cognito method. We have just implemented both the suggested solution in #614 but doesn't seem to work.

**Comment by sammartinez** [comment]
@harshraj93 Can you look to turn on the [debugger](https://docs.amplify.aws/lib/utilities/logger/q/platform/js#setting-logging-levels) and see if you are seeing the the [following message](https://github.com/aws-amplify/amplify-js/blob/e85640a4e18fa1d55411038fee58919ad73121fa/packages/core/src/Credentials.ts#L482-L483): `removing aws-amplify-federatedInfo from storage'`.

I have a feeling, since we don't have a use case around CloudFront, that there may be something with how the browser is working with CloudFront and persisting the token. Thanks ahead of time

**Comment by harshraj93** [comment]
@sammartinez I believe it is something to do with the Chrome browser as worked right with Safari and currently, we are not getting any message like 'removing aws-amplify-federatedInfo from storage'.
I have mentioned above the message we get while executing the SignOut method that prevents the clearing of tokens.
The message is per below
**'Cross-Origin Read Blocking (CORB) blocked cross-origin response'**
