### ISSUE TITLE
hideSignUp prop is not working in AmplifySignIn

### ISSUE THREAD

**Issue by sam-webchef** [aws-amplify/amplify-js#6176]
**Describe the bug**
I'm using the `AmplifySignIn` component in my React App. According to the [official doc](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#sign-in) if `hideSignUp` is set to `true`, it should hide the signup link. But it doesn't hide when I add the code as follows.

`<AmplifySignIn hideSignUp={true} headerText="Sign in to the CRM"  ></AmplifySignIn>`

**Update 27/06/2020**: I found the workaround [https://github.com/aws-amplify/amplify-js/issues/6089#issuecomment-644438802](https://github.com/aws-amplify/amplify-js/issues/6089#issuecomment-644438802)

**Comment by ashika01** [comment]
@jordanranz any thoughts? ^^

**Comment by jordanranz** [comment]
@sam-webchef which version of `@aws-amplify/ui-react` are you using? Also the code sample you posted seems to have `slot="sign-in"` missing. Should be: `<AmplifySignIn slot="sign-in" hideSignUp={true} headerText="Sign in to the CRM" ></AmplifySignIn>`

**Comment by SwagMuffinMcYoloPants** [comment]
I had the same issue too but I was on version 0.2.6 of `@aws-amplify/ui-react`...updating to 0.2.9 fixed my issue... @jordanranz 's code worked for me

**Comment by jordanranz** [comment]
@sam-webchef, let me know if this solution works for you

**Comment by jordanranz** [comment]
Going close this for now since there is a solution and workaround

**Comment by sam-webchef** [comment]
@jordanranz, I'm sorry for the late reply. Yes, the solution worked. Thanks, guys.
