### ISSUE TITLE
Build error  when configured Push Notification > Task :@aws-amplify_pushnotification:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by GBanaphal-Fintech** [aws-amplify/amplify-js#6177]
Describe the bug
Working on React Native Project .when configured aws push notifications got the following build error
To Reproduce
0.  **React Native ver: "0.62.2", react-native-cli ver:”2.0.1”,  amplify ver:"3.2.6",  amplify push notification ver:" 3.1.4",  node ver: "12.16.1",   firebase ver: "17.2.0"** 
Start with:
1. **Created Firebase Project (Firebase ver: "17.2.0 )**
  npm install aws-amplify @aws-amplify/pushnotification
 amplify add notifications
2. **Add to android/build.gradle:**
dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
        classpath 'com.google.gms:google-services:4.3.3'
}
3. **Update maven url as the following under allprojects> repositories.**
allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
maven {
    // Android JSC is installed from npm
    url("$rootDir/../node_modules/jsc-android/dist")
}
google()
jcenter()
maven { url 'https://www.jitpack.io' }
maven {
    url 'https://maven.google.com/'
    name 'Google'
}
    }
}
 
4. **Add to android/app/build.gradle**
dependencies {
    implementation (project(':@aws-amplify_pushnotification'))
    {
        exclude group: 'com.google.firebase'
        exclude group: 'com.google.android.gms', module: 'play-services-gcm'
    }
    implementation (project(':amazon-cognito-identity-js'))
    {
        exclude group: 'com.google.firebase'
        exclude group: 'com.google.android.gms', module: 'play-services-gcm'
    }
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:support-v4:19.1.0'
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules

    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"
    
    implementation "com.google.firebase:firebase-analytics:17.2.2"
    implementation 'com.google.firebase:firebase-core:17.2.0'
    implementation 'com.google.firebase:firebase-messaging:20.0.0'

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }

    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}
 
5.  **And add to the bottom of the file:**
apply plugin:” com.google.gms.google-services”
6. **Add to android/app/src/main/AndroidManifest.xml**
   

> <application
>           android:name=".MainApplication"
>           android:label="@string/app_name"
>           android:icon="@mipmap/ic_launcher"
>           android:roundIcon="@mipmap/ic_launcher_round"
>           android:allowBackup="false"
>           android:theme="@style/AppTheme">
>        < activity
>           android:name=".MainActivity"
>           android:label="@string/app_name"
>           android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
>           android:screenOrientation="portrait"
>           android:launchMode="singleTask"
>           android:windowSoftInputMode="adjustResize">
>         < intent-filter>
>             < action android:name="android.intent.action.MAIN" />
>             < category android:name="android.intent.category.LAUNCHER" />
>         < /intent-filter>
>       < /activity>
>       < activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
>     < !-- AmplifyAndroidPush ADD THESE LINES -->
>     < !--[START Push notification config -->
>     < !-- [START firebase_service] -->
>       < service android:name="com.amazonaws.amplify.pushnotification.RNPushNotificationMessagingService">
>         < intent-filter>
>           < action android:name="com.google.firebase.MESSAGING_EVENT"/>
>         < /intent-filter>
>       < /service>
>     < !-- [END firebase_service] -->
>     < !-- [START firebase_iid_service] -->
>       < service android:name="com.amazonaws.amplify.pushnotification.RNPushNotificationDeviceIDService">
>         < intent-filter>
>           < action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
>         < /intent-filter>
>       < /service>
>       < receiver android:name="com.amazonaws.amplify.pushnotification.modules.RNPushNotificationBroadcastReceiver" android:exported="false">
>         < intent-filter>
>           < action android:name="com.amazonaws.amplify.pushnotification.NOTIFICATION_OPENED"/>
>         < /intent-filter>
>       < /receiver>
>     < !-- [END Push notification config -->
> 
>     < /application>
>  

7. **App.js**
import PushNotification from '@aws-amplify/pushnotification';
import amplify from './aws-exports';
PushNotification.configure(amplify);
8. **Build**
./gradlew assembleDebug
9. **Logs and Error**
> Task :@aws-amplify_pushnotification:compileDebugJavaWithJavac FAILED
/codebuild/output/src333513747/src/github.com/FintechGlobalCenter/NoCodeApp-CrossPlatform/node_modules/@aws-amplify/pushnotification/android/src/main/java/com/amazonaws/amplify/pushnotification/modules/RNPushNotificationAttributes.java:16: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/codebuild/output/src333513747/src/github.com/FintechGlobalCenter/NoCodeApp-CrossPlatform/node_modules/@aws-amplify/pushnotification/android/src/main/java/com/amazonaws/amplify/pushnotification/modules/RNPushNotificationHelper.java:34: error: cannot find symbol
import android.support.v4.app.NotificationCompat;
                             ^
  symbol:   class NotificationCompat
  location: package android.support.v4.app
/codebuild/output/src333513747/src/github.com/FintechGlobalCenter/NoCodeApp-CrossPlatform/node_modules/@aws-amplify/pushnotification/android/src/main/java/com/amazonaws/amplify/pushnotification/RNPushNotificationMessagingService.java:28: error: cannot find symbol
import android.support.v4.app.NotificationCompat;
                             ^
  symbol:   class NotificationCompat
  location: package android.support.v4.app
/codebuild/output/src333513747/src/github.com/FintechGlobalCenter/NoCodeApp-CrossPlatform/node_modules/@aws-amplify/pushnotification/android/src/main/java/com/amazonaws/amplify/pushnotification/RNPushNotificationMessagingService.java:29: error: package android.support.v4.content does not exist
import android.support.v4.content.LocalBroadcastManager;
                                 ^
/codebuild/output/src333513747/src/github.com/FintechGlobalCenter/NoCodeApp-CrossPlatform/node_modules/@aws-amplify/pushnotification/android/src/main/java/com/amazonaws/amplify/pushnotification/modules/RNPushNotificationAttributes.java:132: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class RNPushNotificationAttributes
/codebuild/output/src333513747/src/github.com/FintechGlobalCenter/NoCodeApp-CrossPlatform/node_modules/@aws-amplify/pushnotification/android/src/main/java/com/amazonaws/amplify/pushnotification/modules/RNPushNotificationHelper.java:188: error: package NotificationCompat does not exist
            NotificationCompat.Builder notification = new NotificationCompat.Builder(context)
                              ^
/codebuild/output/src333513747/src/github.com/FintechGlobalCenter/NoCodeApp-CrossPlatform/node_modules/@aws-amplify/pushnotification/android/src/main/java/com/amazonaws/amplify/pushnotification/modules/RNPushNotificationHelper.java:192: error: cannot find symbol
                    .setPriority(NotificationCompat.PRIORITY_HIGH)
                                 ^
  symbol:   variable NotificationCompat
  location: class RNPushNotificationHelper
/codebuild/output/src333513747/src/github.com/FintechGlobalCenter/NoCodeApp-CrossPlatform/node_modules/@aws-amplify/pushnotification/android/src/main/java/com/amazonaws/amplify/pushnotification/modules/RNPushNotificationHelper.java:191: error: cannot find symbol
                    .setVisibility(NotificationCompat.VISIBILITY_PRIVATE)
                                   ^
  symbol:   variable NotificationCompat
  location: class RNPushNotificationHelper
/codebuild/output/src333513747/src/github.com/FintechGlobalCenter/NoCodeApp-CrossPlatform/node_modules/@aws-amplify/pushnotification/android/src/main/java/com/amazonaws/amplify/pushnotification/modules/RNPushNotificationHelper.java:188: error: package NotificationCompat does not exist
            NotificationCompat.Builder notification = new NotificationCompat.Builder(context)
                                                                            ^
/codebuild/output/src333513747/src/github.com/FintechGlobalCenter/NoCodeApp-CrossPlatform/node_modules/@aws-amplify/pushnotification/android/src/main/java/com/amazonaws/amplify/pushnotification/modules/RNPushNotificationHelper.java:258: error: package NotificationCompat does not exist
            notification.setStyle(new NotificationCompat.BigTextStyle().bigText(bigText));
                                                        ^
/codebuild/output/src333513747/src/github.com/FintechGlobalCenter/NoCodeApp-CrossPlatform/node_modules/@aws-amplify/pushnotification/android/src/main/java/com/amazonaws/amplify/pushnotification/modules/RNPushNotificationHelper.java:309: error: cannot find symbol
                notification.setCategory(NotificationCompat.CATEGORY_CALL);
                                         ^
  symbol:   variable NotificationCompat
  location: class RNPushNotificationHelper
Note: /codebuild/output/src333513747/src/github.com/FintechGlobalCenter/NoCodeApp-CrossPlatform/node_modules/@aws-amplify/pushnotification/android/src/main/java/com/amazonaws/amplify/pushnotification/modules/RNPushNotificationHelper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
11 errors

**Comment by vincent-cy** [comment]
I have same question.

**Comment by vincent-cy** [comment]
node_modules/@aws-amplify/pushnotification/android/src/main/java/com/amazonaws/amplify/pushnotification/RNPushNotificationMessagingService.java:28: error: cannot find symbol
import android.support.v4.app.NotificationCompat;
                             ^
  symbol:   class NotificationCompat
  location: package android.support.v4.app

**Comment by vincent-cy** [comment]
i solved

**Comment by bevanmw** [comment]
I fixed this in my project by doing the following:

Installing jetifier as a dev dependancy:
```
npm install jetifier --save-dev
```
Adding the following scripts to my `package.json`:
```
"postinstall": "jetify",
"jetify": "npx jetify"
```
And finally running `npm run jetify`

**Comment by sammartinez** [comment]
@GBanaphal-Fintech Are you still experiencing this issue? Please let us know

**Comment by aloknecessary** [comment]
I too have the same problem when running this using gitlab runner, can someone provide any addional help ? 
I tried the `postinstall` fix as explained above, didn't worked for me

**Comment by aloknecessary** [comment]
@vincent-cy  Would you mind sharing your fix, i have tried lots of solution, but no luck ?

**Comment by aloknecessary** [comment]
@sammartinez  Any help is appreciated..

**Comment by ioannisGiak89** [comment]
I also having the same issue

**Comment by ioannisGiak89** [comment]
Running `npx jetify` solved the issue. Thanks @bevanmw

**Comment by sammartinez** [comment]
Resolving as the above callout

**Comment by SofiyaDSRC** [comment]
Still we are facing this issue

> Task :aws-amplify_pushnotification:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
404 actionable tasks: 2 executed, 402 up-to-date
C:\Project\dara_mobile_app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\RNPushNotificationMessagingService.java:199: error: local variable mReactInstanceManager is accessed from within inner class; needs to be declared final
                            mReactInstanceManager.removeReactInstanceEventListener(this);

**Comment by joseasanchezzz91** [comment]
Hello, I am also having the same issue.

Running npx jetify not working for me

> Task :aws-amplify_pushnotification:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
467 actionable tasks: 6 executed, 461 up-to-date
/Users/acl/Desktop/Test/node_modules/@aws-amplify/pushnotification/android/src/main/java/com/amazonaws/amplify/pushnotification/RNPushNotificationMessagingService.java:199: error: local variable mReactInstanceManager is accessed from within inner class; needs to be declared final
                            mReactInstanceManager.removeReactInstanceEventListener(this);
                            
                            
                            
                            
                            Any help is appreciated

**Comment by SofiyaDSRC** [comment]
> Hello, I am also having the same issue.
> 
> Running npx jetify not working for me
> 
> > Task :aws-amplify_pushnotification:compileDebugJavaWithJavac FAILED
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0. Use '--warning-mode all' to show the individual deprecation warnings. See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings 467 actionable tasks: 6 executed, 461 up-to-date /Users/acl/Desktop/Test/node_modules/@aws-amplify/pushnotification/android/src/main/java/com/amazonaws/amplify/pushnotification/RNPushNotificationMessagingService.java:199: error: local variable mReactInstanceManager is accessed from within inner class; needs to be declared final mReactInstanceManager.removeReactInstanceEventListener(this);
> 
> ```
>                         Any help is appreciated
> ```

1) Delete the .gradlew and build files inside android folder.
2)Delete the package-lock.json and node modules.
3) Without push notification package install and then install the push notification package with version 4.2.9

Its worked for me
