### ISSUE TITLE
How can I send an acknowledgement or welcome to the users email address after confirm signup in aws-amplify-react-native

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#6179]
I am using aws-amplify-react-native.

Here If a new user sign up the app, it send the code to the phone number. But here i wish to send the acknowledgement or welcome message to the users email address.

How can i enable this?

**Comment by elorzafe** [comment]
@nihp you mean after the user confirm signUp?

**Comment by nihp** [comment]
Yes ater confirm signup

**Comment by Amplifiyer** [comment]
You can use cognito's lambda triggers to achieve that. Please see https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-post-confirmation.html which also have an example for this use case.
