### ISSUE TITLE
Override COUNTRY_DIAL_CODE_SUFFIX in AmplifySignUp component

### ISSUE THREAD

**Issue by chantii** [aws-amplify/amplify-js#6189]
**Is your feature request related to a problem? Please describe.**
Looks like we +1 is the default countryDialCode in React AmplifySignUp component.

**Describe the solution you'd like**
Allow the Phone number form fields to override the countryDialCode

**Comment by jordanranz** [comment]
Hey @chantii,

`@aws-amplify/ui-react@unstable` (and other `@unstable` Amplify UI libs) includes the ability to pass the `dialCode` and `value` to the `phone_number` form field.
*Usage*
```
{
  type: 'phone_number',
  dialCode: `+27`,
  value: '5555555555',
}
```

Let me know if this works for ya.

**Comment by jordanranz** [comment]
You are now able to pass the `dialCode` in via formFields. Closing this FR now. Please open a new issue if there are any related questions or concerns.
