### ISSUE TITLE
 Location Not Capture for Amplify Analytics in Pinpoint in React Native

### ISSUE THREAD

**Issue by mynameisguy** [aws-amplify/amplify-js#6190]
**Describe the bug**
When reporting events using Amplify Analytics Location is empty

**To Reproduce**
check any event reported from react-native using amplify analytics and check the location field.

**Expected behavior**
the location should be reported at least at a country level.

**Comment by ohlr** [comment]
The same happens for amplify within react (web). While all standard attributes are reported, location remains empty.

**Comment by Amplifiyer** [comment]
@ohlr and @mynameisguy, how are you adding the location information, in the default config while configure Analytics https://docs.amplify.aws/lib/analytics/getting-started/q/platform/js#set-up-existing-analytics-backend or while updating the end point https://docs.amplify.aws/lib/analytics/getting-started/q/platform/js#update-endpoint

Do you see the location information being present in the http request when seen in the developer console? If yes, are you seeing location data being absent in the pinpoint console?

**Comment by ohlr** [comment]
My setup:
https://docs.amplify.aws/lib/analytics/getting-started/q/platform/js#configure-your-app
https://docs.amplify.aws/lib/analytics/autotrack/q/platform/js#session-tracking

```
import Amplify, { Analytics } from 'aws-amplify';
import awsconfig from './aws-exports';

Analytics.autoTrack('session', {
    enable: true,
});
Analytics.autoTrack("pageView", {
    enable: true,
    type: "multiPageApp",
});

Location is not in the request


Amplify.configure(awsconfig);
```
![image](https://user-images.githubusercontent.com/26937880/86330377-e510ba00-bc47-11ea-9bf8-88e39889f065.png)

**Comment by mynameisguy** [comment]
I'm not adding the location information manually. Should I?

**Comment by Amplifiyer** [comment]
yes, the location is supposed to be provided by the user, either in the `udpateEndPoint()` API's attributes or while configuring Amplify or Analytics category. I have provided the link for both in my previous comment.

Code for reference: 
https://github.com/aws-amplify/amplify-js/blob/a75e9c30348d4230fb3649e099c531f4521b3191/packages/analytics/src/Providers/AWSPinpointProvider.ts#L752-L755
and what demographic information is provided by default by Amplify https://github.com/aws-amplify/amplify-js/tree/main/packages/core/src/ClientDevice

**Comment by ohlr** [comment]
@Amplifiyer Google Analytics as far as I know provides user location based on ip address... I wonder why a paid service like pinpoint/amplify does not provide that

**Comment by ohlr** [comment]
Besides seeing this as a feature request I would also appreciate if the docs could be updated with respect to what is captured automatically and what not.
Knowing in advance that features such as location / session duration are not supported yet would improve comparability to other frameworks out there
