### ISSUE TITLE
HTTP Request is not signed by library --> UNAUTHORIZED

### ISSUE THREAD

**Issue by ASchwad** [aws-amplify/amplify-js#6196]
**Describe the bug**
When i am logged in the react-native app and make a request via the API Module to an endpoint (which is secured by cognito user groups authorizer) I get an 401 unauthorized error. When I manually read the token of the logged in User and provide it in the request options, the request is successful.
Is it even possible to use cognito user pools as authorizer in aws-amplify-js? Apparently the identityPoolId (which i dont have) is [mandatory](https://docs.amplify.aws/lib/restapi/getting-started/q/platform/js#manual-setup-import-existing-rest-api) in the configuration. Why is that?

**To Reproduce**
My AWS configuration:
```
const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_dynamodb_all_tables_region": "eu-central-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "XXXXX",
            "region": "eu-central-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "XXXXXXX",
            "endpoint": "https://xxxxx.execute-api.eu-central-1.amazonaws.com/Prod",
            "region": "eu-central-1"
        }
    ],
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_XXXXXXX",
    "aws_user_pools_web_client_id": "XXXXXXXXXXXXXX",
    "oauth": {}
};
```
I also tried the following configuration without success:
```
    AUTH: {
        region: "eu-central-1",
        userPoolId: "eu-central-1_XXXXXX",
        userPoolWebClientId: "XXXXXXXXXXXXXXXXX"
    },
    API: {
        endpoints: [
            {
                "name": "XXXXXXXXX",
                "endpoint": "https://xxxxxx.execute-api.eu-central-1.amazonaws.com/Prod"
            }
        ]
    }
```

**Expected behavior**
 I expected the behaviour mentioned [here](https://github.com/aws-amplify/amplify-js/blob/main/README.md#3-sign-http-requests). The token of the logged in user should be used to sign Requests using the API Module

**Code Snippet**
```
API.get("XXXXXX", "/XXX/XXXXX")
        .then(...)
```
**Additional context**
```
"aws-amplify": "^3.0.18",
 "aws-amplify-react-native": "^4.2.1",
```

**Comment by Amplifiyer** [comment]
@ASchwad, let me know if you have already tried this https://docs.amplify.aws/lib/restapi/authz/q/platform/js#cognito-user-pools-authorization and the issues you faced with this?

**Comment by ASchwad** [comment]
@Amplifiyer thanks for your answer. This is exactly how i resolved the issue. But i was not sure if it was the default behaviour or an error on my side. I've read about [auto signing of requests](https://github.com/aws-amplify/amplify-js/blob/main/README.md#3-sign-http-requests) and got confused.

I am figuring, why is auto signing possible with IAM Authorizer but not Cognito User Groups? I was hoping, that the Auth token could be stored similarily and used for requests via the API Module.

**Comment by Amplifiyer** [comment]
That's just an architecture decision in Amplify. Amplify library provides defaults for most common use cases or opinionated approach while simultaneously providing escape hatches to allow more complex or less frequent use cases. Closing this since your issue is resolved.
