### ISSUE TITLE
Have Amplify work in chrome extension context.

### ISSUE THREAD

**Issue by ripley** [aws-amplify/amplify-js#6197]
**Is your feature request related to a problem? Please describe.**
It seems Amplify auth cannot work when being integrated with chrome extension, where normally the UI logic resides in content script (the auth happens), and the main App logic resides in background scripts (where the backend API got called), the two kinds of script cannot access a sharing localStorage.

IMO chrome extension should be a valid scenario for Amplify.

**Describe the solution you'd like**
Amplify works in this scenario by giving some config options without massive code change.

**Describe alternatives you've considered**
Tried to implement a customized storage with chrome.storage API but didn't get it work. The storage code is like ...

`export class TokensStorage {
  static setItem(key, value) {
      chrome.storage.local.set({[key]: JSON.stringify(value)}, () => {
      console.log('token stored');
    });
  }
  // get item with the key
  static getItem(key) {
    return new Promise((resolve, reject) => {
      chrome.storage.local.get([key], (result) =>  {
        resolve(result)
      });
    })
  }
  // remove item with the key
  static removeItem(key) {
    chrome.storage.local.remove(key, () => {
      console.log("item removed");
    })
  }
  // clear out the storage
  static clear() {
    chrome.storage.local.clear(() => {
      console.log("storage cleared");
    })
  }
}`

And to contain it with ...
Amplify.configure({
  ...awsconfig,
  Auth: {
    storage: TokensStorage
  }
});

**Additional context**
N/A

**Comment by sw-yx** [comment]
thanks. just curious, does Firebase support this?

**Comment by Amplifiyer** [comment]
For any solution to work, wouldn't you need some sort of local storage that **can be** accessed from both places? Is `chrome.storage` not a viable options for that?

Since I don't have context on chrome extensions, can you expand on (Amplify works in this scenario by giving some config options without massive code change.), specifically what kind of config options or solution in Amplify would be required to get it working?

**Comment by ripley** [comment]
> For any solution to work, wouldn't you need some sort of local storage that **can be** accessed from both places? Is `chrome.storage` not a viable options for that?

I tried to add a TokensStorage with chrome.storage but it didn't work, looks like the **setItem** is never called. This is probably the way to go and I need to dig more, I didn't find anyone have done this though.

> Since I don't have context on chrome extensions, can you expand on (Amplify works in this scenario by giving some config options without massive code change.), specifically what kind of config options or solution in Amplify would be required to get it working?

Ideally I'm expecting to pass a flag to Amplify.configure or Auth.configure to indicate it's gonna be working in chrome extension context and a workable storage scheme is selected automatically for Auth. If I understand correctly localStorage is selected by default.

Or a documentation about how to set up a customized storage for this scenario works as well.

**Comment by ripley** [comment]
> thanks. just curious, does Firebase support this?

I never used firebase, but looks like there're quite a few articles discussing their integration, I guess it has better support.

**Comment by Amplifiyer** [comment]
> Ideally I'm expecting to pass a flag to Amplify.configure or Auth.configure to indicate it's gonna be working in chrome extension context and a workable storage scheme is selected automatically for Auth. If I understand correctly localStorage is selected by default.

By passing the flag, Amplify (or any other library) would have to figure out a storage scheme that works in exactly this context. Rather, Amplify takes a more generic approach and let users provide their own storage implementations. Amplify library doesn't make assumptions on how custom storage should be implemented and if provided, skips local storage. 

This may be related to [supporting SSR](https://github.com/aws-amplify/amplify-js/pull/6146) as well where Auth sessions and cookies get stored in the client side and the server needs them to access AWS services. Not sure if the exact solution can work in this context.

**Comment by ripley** [comment]
> > Ideally I'm expecting to pass a flag to Amplify.configure or Auth.configure to indicate it's gonna be working in chrome extension context and a workable storage scheme is selected automatically for Auth. If I understand correctly localStorage is selected by default.
> 
> By passing the flag, Amplify (or any other library) would have to figure out a storage scheme that works in exactly this context. Rather, Amplify takes a more generic approach and let users provide their own storage implementations. Amplify library doesn't make assumptions on how custom storage should be implemented and if provided, skips local storage.
> 
> This may be related to [supporting SSR](https://github.com/aws-amplify/amplify-js/pull/6146) as well where Auth sessions and cookies get stored in the client side and the server needs them to access AWS services. Not sure if the exact solution can work in this context.

I successfully replaced local storage with chrome.storage.local API and it works great in content script alone. Problem now is content script and background script are so separated that the MyStorage instance (get the name from this guide: https://docs.amplify.aws/lib/auth/manageusers/q/platform/js#managing-security-tokens) in both places are not syncing dataMemory properly.

The MyStorage in background script appears empty all the time (even the data are all accessible via chrome.storage.local), maybe that's because auth process is not handled there.
I think I'll need to manually trigger the setItem, getItem, remove, clear, sync ... call in background script by listening to chrome.storage.OnChanged event, is that viable if Amplify is not managing the auth flow?

**Comment by ripley** [comment]
I ended up implement two storage classes, one for content script with chrome.storage support the other for background with only an object to hold the tokens, and shadow it with the one in content script with chrome storage event, it works as expected.
