### ISSUE TITLE
Amplify Hub event not firing in cognito hosted UI- angular

### ISSUE THREAD

**Issue by Ivelraj1997** [aws-amplify/amplify-js#6201]
Amplify Hub event not firing in cognito hosted UI but cognito sign in work well.  

package.json 

  "aws-amplify": "^3.0.18",
 "@aws-amplify/ui-angular": "^0.2.9",

please look this.
![image](https://user-images.githubusercontent.com/37973269/86119153-f61ec700-ba9f-11ea-8d0c-1ee5b5dd6d50.png)

**Comment by Amplifiyer** [comment]
@Ivelraj1997 can you provide your code where you are subscribing and listening to hub events.

**Comment by Ivelraj1997** [comment]
![image](https://user-images.githubusercontent.com/37973269/86217427-751e0900-bb4d-11ea-8b9d-164e201c7761.png)

**Comment by Amplifiyer** [comment]
@Ivelraj1997 thanks for the code snippet. The event name when sign in happens through hosted UI is "cognitoHostedUI", see https://github.com/aws-amplify/amplify-js/blob/8dd92959fbe11c328ec4f8e467c0929ed1e7e5ca/packages/auth/src/Auth.ts#L1917-L1926 and the example here https://docs.amplify.aws/lib/auth/social/q/platform/js#full-samples

**Comment by Ivelraj1997** [comment]
@Amplifiyer   this flag 'cognitoHostedUI' didn't work and some time it is listener work.
