### ISSUE TITLE
Aws amplify with kivy

### ISSUE THREAD

**Issue by purushottam858** [aws-amplify/amplify-js#6205]
I am new to aws services, I want to use aws amplify as backend for kivy application (python framework).
I didn't find any information how to do it?
Does aws amplify support only JavaScript Frameworks ?

**Comment by Amplifiyer** [comment]
@purushottam858, Amplify currently supports Javascript client side frameworks and native iOS and Android frameworks only https://docs.amplify.aws/ and currently there is no plan to support kivy.

**Comment by purushottam858** [comment]
Is there any other possible way to make use of amplify services with python 3 or aws console ?

**Comment by Amplifiyer** [comment]
Unfortunately no. You would have to use aws-sdk for python I believe https://aws.amazon.com/sdk-for-python/
