### ISSUE TITLE
Analytics autoTrack "event" fails with Gatsby (SSR)

### ISSUE THREAD

**Issue by ohlr** [aws-amplify/amplify-js#6208]
**Describe the bug**
following this setup: https://docs.amplify.aws/lib/analytics/autotrack/q/platform/js#page-event-tracking

while Analytics.autoTrack("pageView") and Analytics.autoTrack("session") work fine with Gatsbys Server Side rendering (SSR)

Adding Analytics.autoTrack("event") produces the following error during production builds:

```
TypeError: Cannot convert undefined or null to object
Function.assign
render-page.js:3382 EventTracker../node_modules/@aws-amplify/analytics/lib-esm/trackers/EventTracker.js.EventTracker.configure
render-page.js:964 AnalyticsClass../node_modules/@aws-amplify/analytics/lib-esm/Analytics.js.AnalyticsClass.autoTrack

```
In development mode everything works fine.
I guess that autoTrack uses a variable like (window / location) that is not known at compile time.

The failure only occurs when being called within a React component.
Outside of components it works fine. However in order to be able to turn Analytics on and off I need it to be inside React.

This here could be the reason for failure:
https://github.com/aws-amplify/amplify-js/blob/main/packages/analytics/src/trackers/EventTracker.ts#L33

Related issues:
#5435

Env:
"aws-amplify": "^3.0.10",
"gatsby": "^2.21.9",

**Comment by Amplifiyer** [comment]
@ohlr, as you correctly pointed out, SSR is currently not officially supported. I will mark this as a feature request and work along with #5435. cc @ericclemmons

**Comment by dr-star** [comment]
Which is the status of this task?

**Comment by cwomack** [comment]
@ohlr and @dr-star

With Amplify JS v6 we provide an adapter for only Next.js, although the underlying generic adapters can be used with other frameworks. We have published documentation on how to use the generic adapters which can be viewed here - [docs.amplify.aws/react/build-a-backend/server-side-rendering](https://docs.amplify.aws/react/build-a-backend/server-side-rendering/)

Let me know if you have any questions.
