### ISSUE TITLE
Auth.signIn should throw code InvalidParameterException when email/password is empty

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-js#6213]
**Is your feature request related to a problem? Please describe.**

Currently, when you call `Auth.signIn(email, password)` with the password being empty, it will throw an error:

```js
{
  code: "InvalidParameterException",
  name: "InvalidParameterException",
  message: "Custom auth lambda trigger is not configured for the user pool."
}
```

But calling it with the `email` empty throws a completely different error that says: `[ERROR] 22:19.549 AuthError - Username cannot be empty`, for consistency's sake, I think it makes sense to just throw `InvalidParameterException`.

**Describe the solution you'd like**

Please read above.

**Describe alternatives you've considered**

N/A

**Additional context**
Add any other context, an idea of the implementation or screenshots about the feature request here.

N/A

**Comment by tannerabread** [comment]
The invalidParameterException is coming because Amplify also supports passwordless authentication flow in some cases. 

Could you explain a bit more what the business case would be for throwing the same error, whereas most users ask for more granular errors?

**Comment by stocaaro** [comment]
Related to https://github.com/aws-amplify/amplify-ui/issues/3458 ?

**Comment by cwomack** [comment]
The developer preview for v6 of Amplify has officially been released with updates to the Auth package, error handling, and much more! Please check out our [announcement](https://aws.amazon.com/blogs/mobile/aws-amplify-javascripts-new-developer-preview-with-reduced-bundle-sizes-improved-typescript-and-next-js-support/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=238088647) and updated [documentation](https://docs.amplify.aws/lib-v1/project-setup/create-application/q/platform/js/) to see what has changed. 

We believe this issue should be resolved within the dev preview and upcoming General Availability for Amplify v6, but let us know with a comment if there are further issues.

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
