### ISSUE TITLE
Phone number sign in error

### ISSUE THREAD

**Issue by chantii** [aws-amplify/amplify-js#6224]
**Describe the bug**
Trying to customize the sign up and sign in with phone number with below auth configuration. This renders the appropriate forms and works well for happy cases. But if we click on the sign in button without entering the phone number, there is a an error in validation and state is not being handled.

```html
import { AmplifyAuthenticator, AmplifySignUp, AmplifySignIn } from '@aws-amplify/ui-react';

<AmplifyAuthenticator usernameAlias="phone_number">
            <AmplifySignUp
                slot="sign-up"
                usernameAlias="phone_number"
                formFields={[
                {
                    type: "phone_number",
                    label: "Phone number",
                    placeholder: "Phone number",
                    required: true,
                },
                {
                    type: "password",
                    label: "Password",
                    placeholder: "Password",
                    required: true,
                },
                {
                    type: "name",
                    label: "Name",
                    placeholder: "Full Name",
                    required: true,
                },
                {
                    type: "email",
                    label: "Email (Optional)",
                    placeholder: "abc@email.com",
                    required: false,
                }
                ]}
            />
                Consultation form
            <AmplifySignIn slot="sign-in" usernameAlias="phone_number" />
        </AmplifyAuthenticator>
```

**To Reproduce**
See above.

**Expected behavior**
Handle the validation error and show a error that phone field cannot be empty.

**Code Snippet**
See above

**Screenshots**
<img width="1274" alt="Screen Shot 2020-07-03 at 11 39 41 AM" src="https://user-images.githubusercontent.com/1948874/86492107-e6aeb080-bd21-11ea-97c4-494679cc1006.png">

**Comment by jordanranz** [comment]
Taking a look at this as part of this PR: https://github.com/aws-amplify/amplify-js/pull/6211

**Comment by jordanranz** [comment]
Hi @chantii, I have merged a PR that will properly display error messages when phone_number is empty. Could you please try and test using `@aws-amplify/ui-react@unstable`

**Comment by jordanranz** [comment]
This fix is now in `@latest`. Please open a new issue if you experience any similar issues.
