### ISSUE TITLE
Cognito and IAM 401 or not called.

### ISSUE THREAD

**Issue by Rafcin** [aws-amplify/amplify-js#6227]
The issue is I have created a schema that utilizes cognito groups and IAM. I wanted to use IAM for general read access and cognito to allow specific users to perform action such as creating posts etc.
 
My current model uses the following auth.
```
@auth(
  rules: 
    [
      { allow: owner }
      { allow: public, provider: iam, operations: [read] }
      { allow: private }
      { allow: groups, groups: ["User"], operations: [read] }
      { allow: groups, groups: ["RestaurantUser"] }
      { allow: groups, groups: ["Admin"] }
    ]
)
```

The problem I run into is, I can't user Cognito and IAM. If try to set the authmode by doing 
``` Auth.currentAuthenticatedUser ? "COGNITO..." : "IAM..."```

Even if it uses IAM it won't use IAM when its unauthenticated. Normally when using IAM it doesn't allow the authed user to makes calls, however the unauthed can. And the same is if you use cognito then authed users work and unauthed don't.

The one thing I noticed was if the user isn't in one of the 3 groups then the calls seem to work fine. I originally had read, write etc and the same issue persisted "Permission Denied"

**Comment by Rafcin** [comment]
It seems this issue is actually the result of guest credentials not generating for guest users. I looked at a few of my project and they all log credentials for guest users except for this project even though I have the unauthorized credentials active in cognito.

**Comment by mauerbac** [comment]
HI @Rafcin - I'm going to move this to our discussion form as it seems you need help with the graphQL schema and are not reporting a bug.
