### ISSUE TITLE
How to make force signout if the admin disable the user account in cognito

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#6235]
I have used the Auth.currentAuthenticatedUser and it return as not authenticated error. But here if I try to signout as Auth.signOut() it not worked.

It always updating the **Authenticator - authState has been updated to signedIn**. The payload event not changed to signOut()

**Comment by mauerbac** [comment]
hi @nihp - you've previously asked the same question. It's best to answer all related questions in the same Issue. Thank you!
