### ISSUE TITLE
Cognito SignUp User Enumeration

### ISSUE THREAD

**Issue by siboulet** [aws-amplify/amplify-js#6238]
**Describe the bug**

If users are allowed to sign themselves up on the user pool, Cognito is returning a UsernameExistsException which allows for user enumeration on signup.

A similar [issue with InitiateAuth (Login) was reported and resolved here](https://github.com/aws-amplify/amplify-js/issues/1183).

**To Reproduce**

1. Create a User Pool. Make sure "Allow users to sign themselves up" is enabled under the pool Policies. 
2. Under your App Clients settings, make sure your app is set to "Prevent User Existence Errors".
3. Try signing up a user with an existing username.
4. Cognito is reporting a "User already exists" (UsernameExistsException) error.

**Expected behavior**
Cognito should return an "Incorrect username or password." (NotAuthorizedException) error similar to [how InitiateAuth (login) is returning error](https://github.com/aws-amplify/amplify-js/issues/1183).

Thanks

**Comment by sammartinez** [comment]
@siboulet, this looks specific to the Amazon Cognito service. Please refer to this documentation on "[Managing Error Response](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-managing-errors.html)" in order to handle this. Thanks!

**Comment by Arvanaghi** [comment]
@sammartinez The documentation around this is fairly vague. Any more pointed resources you can share?

**Comment by davestrator** [comment]
@sammartinez Could you please explain why this issue has been closed? The AWS documentation you referenced does not provide any information on how to resolve this issue and indeed it still exists. If you have set up your user pool attributes as follows:

![howToSignIn](https://user-images.githubusercontent.com/87594793/131674369-36da1460-97cf-4c80-a474-7a1a84652430.png)

And you configure your security as follows:

![secConfig](https://user-images.githubusercontent.com/87594793/131674422-fdaad9d4-5005-447a-8f45-1fd75f9ae122.png)

Then you make the following call using the Amplify Auth class from the aws-amplify library:

```
      const userInfo = await Auth.signUp({
        username: email,
        password,
        attributes: {
          email: email, // optional but not in this case as MFA/Verification code wil be emailed
        },
      });
```

You will get the following response:

{
    "__type":"UsernameExistsException",
    "message":"An account with the given email already exists."
}

Nowhere in the linked documentation is there any indication on how to resolve this issue and I beleive it still exists and is a real case of User Enumeration which is an [OWASP](https://owasp.org/www-project-top-ten/2017/A2_2017-Broken_Authentication) known vulnerability.

Could this issue please be reopened? If you are certain the issue can be resolved using the Amplify Auth library and AWS Cognito with the use case I have described above, then could you please provide a working example that closes the vulnerability?

Many thanks

**Comment by BinyominCohen** [comment]
This is still an issue even after enable "prevent user existence errors".
I still get "An account with the given email already exists" when trying to create new user and email already exists

**Comment by mohayad** [comment]
Hello Cognito team

**Comment by abjrcode** [comment]
As far as I see this is indeed an account enumeration vulnerability, can you please open it again and remediate.
Thank you

**Comment by lvancraen** [comment]
Facing the same issue as everyone else. It would be great to have a way of configuring this on the user pools directly instead of needing to hack our way around this via `Pre sign-up` lambdas

**Comment by camin-mccluskey** [comment]
We are also facing this issue - it represents a serious security vulnerability for any app utilising Cognito for auth and must be reopened.

**Comment by fab-mindflow** [comment]
Why is this closed? Looks like it's not fixed.

**Comment by tannerabread** [comment]
Hello thread, I am not sure why this was closed 2 years ago but I will open this up for discussion internally and respond here with any updates.

**Comment by fab-mindflow** [comment]
Thanks. Sign in has a setting to _Prevent User Existence Errors_ but this does not mitigate "Sign up" against account enumeration.
