### ISSUE TITLE
[aws-amplify-angular 3.X.X] Can't resolve '@aws-amplify/*' while using just the auth module

### ISSUE THREAD

**Issue by urfnaino** [aws-amplify/amplify-js#6239]
**Describe the bug**
I'm currently on version 2.X.X and here are my aws-amplify dependencies in package.json:
```
"@aws-amplify/auth": "^2.1.8",
"@aws-amplify/core": "^2.3.0",
"aws-amplify-angular": "^4.1.9"
```
This configuration works without any issue.

But when I try to upgrade to version 3.X.X, the exact set of dependencies doesn't work. Here're the ng serve logs:
```
chunk {main} main.js, main.js.map (main) 480 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 414 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 3.4 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 25.3 MB [initial] [rendered]
Date: 2020-07-02T14:36:15.680Z - Hash: f254b388275b37a4e3ac - Time: 64792ms

ERROR in ./node_modules/aws-amplify-angular/dist/src/providers/amplify.service.js
Module not found: Error: Can't resolve '@aws-amplify/analytics' in 'C:\Source\Git\cloudanalytics\visualization\client\node_modules\aws-amplify-angular\dist\src\providers'
ERROR in ./node_modules/aws-amplify-angular/dist/src/providers/amplify.service.js
Module not found: Error: Can't resolve '@aws-amplify/api' in 'C:\Source\Git\cloudanalytics\visualization\client\node_modules\aws-amplify-angular\dist\src\providers'
ERROR in ./node_modules/aws-amplify-angular/dist/src/providers/amplify.service.js
Module not found: Error: Can't resolve '@aws-amplify/interactions' in 'C:\Source\Git\cloudanalytics\visualization\client\node_modules\aws-amplify-angular\dist\src\providers'
ERROR in ./node_modules/aws-amplify-angular/dist/src/providers/amplify.service.js
Module not found: Error: Can't resolve '@aws-amplify/pubsub' in 'C:\Source\Git\cloudanalytics\visualization\client\node_modules\aws-amplify-angular\dist\src\providers'
ERROR in ./node_modules/aws-amplify-angular/dist/src/providers/amplify.service.js
Module not found: Error: Can't resolve '@aws-amplify/storage' in 'C:\Source\Git\cloudanalytics\visualization\client\node_modules\aws-amplify-angular\dist\src\providers'
ERROR in ./node_modules/aws-amplify-angular/dist/src/providers/amplify.service.js
Module not found: Error: Can't resolve '@aws-amplify/xr' in 'C:\Source\Git\cloudanalytics\visualization\client\node_modules\aws-amplify-angular\dist\src\providers'
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Failed to compile.
```
The new version of aws-amplify-angular directly references other packages in its [provider service](https://github.com/aws-amplify/amplify-js/blob/main/packages/aws-amplify-angular/src/providers/amplify.service.ts#L24) which wasn't the case with [version 2.X.X](https://github.com/aws-amplify/amplify-js/blob/2.0-stable/packages/aws-amplify-angular/src/providers/amplify.service.ts#L20).

Was this change intended? Am I supposed to import the complete aws-amplify package (as suggested [here](https://docs.amplify.aws/start/getting-started/setup/q/integration/angular#install-amplify-libraries)) to be able to upgrade to latest version? If yes, wouldn't it increase the build size unnecessarily?

**Screenshots**
![aws-amplify-auth-n-core](https://user-images.githubusercontent.com/23518044/86611033-bdb14880-bfcb-11ea-84bd-26cf58242ccd.png)

**Comment by ChrisSargent** [comment]
I am using the following in a React project:

```json
    "@aws-amplify/api": "^3.1.18",
    "@aws-amplify/auth": "~3.3.1",
    "@aws-amplify/core": "~3.4.0",
    "@aws-amplify/ui-react": "~0.2.9"
```

I also get the following error (amongst others from other imports): 
```
../node_modules/@aws-amplify/ui-components/dist/esm-es5/amplify-s3-album.entry.js
Module not found: Can't resolve '@aws-amplify/storage' in '/Users/chrissargent/Sites/blockacre/node_modules/@aws-amplify/ui-components/dist/esm-es5'
```
Note that both the `ui-react` and `ui-angular` use the `@aws-amplify/ui-components`.

`@aws-amplify/ui-components` tries to import `@aws-amplify/storage` but it is not included in it's dependencies, which are:

```json
    "qrcode": "^1.4.4",
    "uuid": "^8.2.0"
```

So it seems like `ui-components` is just missing that dependency.

**Comment by ashika01** [comment]
@urfnaino - Officilally, you must be using `@aws-amplify/ui-angular` which supports version 3.X.X. 


@ChrisSargent I will look into the storage dependency.

**Comment by urfnaino** [comment]
@ashika01 : including `@aws-amplify/ui-angular` didn't help. Here is the new set of dependencies:
```
"@aws-amplify/auth": "^3.3.3",
"@aws-amplify/core": "^3.4.4",
"@aws-amplify/ui-angular": "0.2.13",
"aws-amplify-angular": "^5.0.22"
```
As I said, module `aws-amplify-angular` is the one complaining about these unresolved modules and I don't see `@aws-amplify/ui-angular` importing any of those modules.
Plus, I am using Cognito hosted UI for authentication; so do I even need `@aws-amplify/ui-angular`? Because I believe we only need it for its custom UI components like [Authenticator](https://docs.amplify.aws/ui/auth/authenticator/q/framework/angular).

@ChrisSargent : You're right. These UI modules do not import these dependencies directly, but do reference them internally.

And I guess that is the reason why we're asked to [install](https://docs.amplify.aws/start/getting-started/setup/q/integration/angular#install-amplify-libraries) the entire `aws-amplify` package alongside the UI package. And that exactly is what my question is, if I'm planning on using amplify just for authentication, do I still need to install all of those modules?

**Comment by urfnaino** [comment]
@ashika01 Any update on this?

**Comment by ashika01** [comment]
@urfnaino Even if you import `aws-amplify`, while doing a production build tree shaking would be enabled and all unwanted modules will not be bundled. So you shouldnt have an issue.

**Comment by urfnaino** [comment]
@ashika01 Got it. Will be moving to new version of Angular and Amplify soon.
And thanks for the help!

**Comment by alissaVrk** [comment]
hi, it seems that the project went back in history and [this commit ](https://github.com/aws-amplify/amplify-js/pull/6847) isn't there anymore :(

so the bug is back..
