### ISSUE TITLE
Add custom refresh handlers for custom federated identities.

### ISSUE THREAD

**Issue by bloveless** [aws-amplify/amplify-js#624]
I'd like to request a feature.

What is the current behavior?
I'm using `$cognito_client->getOpenIdTokenForDeveloperIdentity([/* custom things here */])` in php to get a developer token which I then pass into AWS Amplify by issuing the following:

```
    try {
        const currentUser = await Auth.currentAuthenticatedUser();
        // A user is already authenticated and logged in.
        dispatch({ type: SET_API_CONFIGURED, payload: true });
    } catch (currentUserErr) {
        const developerTokenResponse = await axios.get('/api/util/developerToken.json');
        const signInReponse = await Auth.federatedSignIn('admin.youniqueproducts.com', { token: developerTokenResponse.accessToken });

        // User was sucessfully logged in.
        dispatch({ type: SET_API_CONFIGURED, payload: true });
        // Unable to get either an unauthenticated user or authenticated.
        dispatch({ type: SET_API_CONFIGURED, payload: false });
    }
```

On the first request this works great! I get logged in and all is great. The second request I get 

```
[WARN] 48:15.692 API - ensure credentials error: "no refresh hanlder for provider"
```

When this message is displayed the credentials are cleared and reloaded on the next page refresh.

I'm wondering if there is a way to provide my own custom refresh handler, or if you'd be interested in a PR where I explore this functionality.

Something along the lines of the following

```
    Auth.configure({
        // Amazon Cognito Identity Pool ID
        identityPoolId: options.cognitoIdentityPoolId,
        // Amazon Cognito Region
        region: options.cognitoRegion,
        // Allow API to make requests when the user is not logged in.
        mandatorySignIn: false,
        refreshHandlers: {
            'admin.youniqueproducts.com': () => {
                // Refresh the token here
            },
        },
    });
```

**Comment by bloveless** [comment]
I feel like I'm doing this wrong anyway :) I'll investigate more and close this if I am doing something wrong.

**Comment by bloveless** [comment]
Also, see this PR https://github.com/aws/aws-amplify/pull/665 which fixes an issue with providing the identity_id to the developer token.

**Comment by NeillGiraldo** [comment]
> I'd like to request a feature.
> 
> What is the current behavior?
> I'm using `$cognito_client->getOpenIdTokenForDeveloperIdentity([/* custom things here */])` in php to get a developer token which I then pass into AWS Amplify by issuing the following:
> 
> ```
>     try {
>         const currentUser = await Auth.currentAuthenticatedUser();
>         // A user is already authenticated and logged in.
>         dispatch({ type: SET_API_CONFIGURED, payload: true });
>     } catch (currentUserErr) {
>         const developerTokenResponse = await axios.get('/api/util/developerToken.json');
>         const signInReponse = await Auth.federatedSignIn('admin.youniqueproducts.com', { token: developerTokenResponse.accessToken });
> 
>         // User was sucessfully logged in.
>         dispatch({ type: SET_API_CONFIGURED, payload: true });
>         // Unable to get either an unauthenticated user or authenticated.
>         dispatch({ type: SET_API_CONFIGURED, payload: false });
>     }
> ```
> On the first request this works great! I get logged in and all is great. The second request I get
> 
> ```
> [WARN] 48:15.692 API - ensure credentials error: "no refresh hanlder for provider"
> ```
> When this message is displayed the credentials are cleared and reloaded on the next page refresh.
> 
> I'm wondering if there is a way to provide my own custom refresh handler, or if you'd be interested in a PR where I explore this functionality.
> 
> Something along the lines of the following
> 
> ```
>     Auth.configure({
>         // Amazon Cognito Identity Pool ID
>         identityPoolId: options.cognitoIdentityPoolId,
>         // Amazon Cognito Region
>         region: options.cognitoRegion,
>         // Allow API to make requests when the user is not logged in.
>         mandatorySignIn: false,
>         refreshHandlers: {
>             'admin.youniqueproducts.com': () => {
>                 // Refresh the token here
>             },
>         },
>     });
> ```

I think this is already provided, (Maybe you forgot to close this one already, but) you have to return a promise like this.

Auth.configure({

 ```
 refreshHandlers: {
    'developer' : () => {
          // Code to retrieve your data
          return new Promise(function(resolve, reject){
                return resolve({
                       token: data.Token,
                       identity_id: data.IdentityId,
                       expires_at: 0
                  })
            })
       }
}
```

@nidsharm  I think you can close this one.

**Comment by bloveless** [comment]
Yup, I added the ability to provide custom refresh handlers in the referenced PR. Closing!
