### ISSUE TITLE
PushNotification.onRegister() is never called on Android

### ISSUE THREAD

**Issue by ArionMiles** [aws-amplify/amplify-js#6241]
**Describe the bug**
This has been reported in the past too, but IDK why I'm still facing this. I'm on the latest packages.
I am aware that this only happens the first time the app is installed, but even if I uninstall my app and re-run `npx react-native run-android` it doesn't seem to ever get printed in the Metro server terminal.

Also, the firebase dependencies in the docs are outdated, the `firebase-core` module has been deprecated.

the documentation lists these:
```
implementation "com.google.firebase:firebase-core:12.0.1"
implementation "com.google.firebase:firebase-messaging:12.0.1"
```

I've removed `firebase-core` and replaced it with firebase-analytics, the latest versions of which I'm referring from here: https://firebase.google.com/support/release-notes/android#latest_sdk_versions

```
implementation 'com.google.firebase:firebase-messaging:20.2.1'
implementation 'com.google.firebase:firebase-analytics:17.4.3'
```

**To Reproduce**
Follow the [Push Notification documentation steps](https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/js).
```
npm install aws-amplify @aws-amplify/pushnotification
```

Add the handler in App.js (outside any react components)
```
PushNotification.onRegister((token) => {
  console.log('in app registration', token);
});
```

**Expected behavior**
On first install, the handler should be called and a log should be printed in the Metro server terminal.

**Code Snippet**
All the code snippets in docs should suffice.

**Screenshots**
NA

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.
* Which resources do you have configured?
  * If applicable, please provide your `aws-exports` file:
   NA
* If applicable, provide more configuration data, for example for Amazon Cognito, run `aws cognito-idp describe-user-pool --user-pool-id us-west-2_xxxxxx` (Be sure to remove any sensitive data)
 

<details>
  <summary><strong>Environment</strong></summary>

npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```
  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 737.16 MB / 7.89 GB
  Binaries:
    Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.19041.1.0
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @apollo/react-hooks: ^3.1.5 => 3.1.5
    @aws-amplify/pushnotification: ^3.1.4 => 3.1.4
    @babel/core: ^7.6.2 => 7.10.3
    @babel/runtime: ^7.6.2 => 7.10.3
    @react-native-community/async-storage: ^1.11.0 => 1.11.0
    @react-native-community/eslint-config: ^0.0.5 => 0.0.5
    @react-native-community/masked-view: ^0.1.10 => 0.1.10
    @react-native-community/netinfo: ^4.7.0 => 4.7.0
    @react-native-community/push-notification-ios: ^1.3.0 => 1.3.0
    @react-native-firebase/app: ^7.1.4 => 7.3.1
    @react-native-firebase/auth: ^8.0.2 => 8.0.8
    @react-navigation/bottom-tabs: ^5.5.1 => 5.6.1
    @react-navigation/material-bottom-tabs: ^5.2.9 => 5.2.12
    @react-navigation/native: ^5.4.3 => 5.6.1
    @react-navigation/stack: ^5.4.0 => 5.6.2
    apollo-cache-inmemory: ^1.6.6 => 1.6.6
    apollo-client: ^2.6.10 => 2.6.10
    apollo-link: ^1.2.14 => 1.2.14
    apollo-link-context: ^1.0.20 => 1.0.20
    apollo-link-error: ^1.1.13 => 1.1.13
    apollo-link-http: ^1.5.17 => 1.5.17
    apollo-link-ws: ^1.0.20 => 1.0.20
    aws-amplify: ^3.0.18 => 3.0.18
    aws-amplify-react-native: ^4.2.1 => 4.2.1
    aws-appsync: ^3.0.3 => 3.0.4
    aws-appsync-auth-link: ^2.0.2 => 2.0.2
    aws-appsync-react: ^3.0.3 => 3.0.4
    babel-jest: ^24.9.0 => 24.9.0
    eslint: ^6.8.0 => 6.8.0
    eslint-config-airbnb: ^18.1.0 => 18.2.0
    graphql-tag: ^2.10.3 => 2.10.3
    husky: ^4.2.5 => 4.2.5
    jest: ^24.9.0 => 24.9.0
    lint-staged: ^10.2.9 => 10.2.11
    metro-react-native-babel-preset: ^0.58.0 => 0.58.0
    moment: ^2.27.0 => 2.27.0
    prettier: ^2.0.5 => 2.0.5
    react: 16.11.0 => 16.11.0
    react-apollo: ^3.1.5 => 3.1.5
    react-apollo-hooks: ^0.5.0 => 0.5.0
    react-native: 0.62.2 => 0.62.2
    react-native-cli: ^2.0.1 => 2.0.1
    react-native-country-picker-modal: ^1.11.0 => 1.11.0
    react-native-elements: ^2.0.3 => 2.0.3
    react-native-gesture-handler: ^1.6.1 => 1.6.1
    react-native-linear-gradient: ^2.5.6 => 2.5.6
    react-native-modal: ^11.5.6 => 11.5.6
    react-native-reanimated: ^1.9.0 => 1.9.0
    react-native-safe-area-context: ^2.0.2 => 2.0.3
    react-native-screens: ^2.8.0 => 2.9.0
    react-native-smooth-pincode-input: ^1.0.9 => 1.0.9
    react-native-svg: ^12.1.0 => 12.1.0
    react-native-svg-transformer: ^0.14.3 => 0.14.3
    react-native-vector-icons: ^6.6.0 => 6.6.0
    react-navigation-custom-bottom-tab-component: ^1.1.1 => 1.1.1
    react-test-renderer: 16.11.0 => 16.11.0
    subscriptions-transport-ws: ^0.9.16 => 0.9.16
    uuid: ^3.4.0 => 3.4.0
  npmGlobalPackages:
    @aws-amplify/cli: 4.21.3
    @cloudflare/wrangler: 1.8.4
    ethereumjs-testrpc: 6.0.3
    surge: 0.21.3
```
</details>

**Smartphone (please complete the following information):**

- Device: Samsung A50
- OS: Android 10 (API 29)

**Additional context**
I have `Amplify.configure(aws-exports)` in my `index.js`
I have followed [this blog series](https://medium.com/@dantasfiles/setting-up-android-push-notifications-with-aws-amplify-e6334c6356d8) by @dantasfiles, even he found `PushNotification.onRegister()` never fired.

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by amhinson** [comment]
@ArionMiles This might have something to do with the Firebase dependencies. We have plans to upgrade these in the future, but for now are you able to test with the ones mentioned in the docs and see if `onRegister` is called?

Could you also try putting `PushNotification.onRegister` inside the component when it mounts (either `componentDidMount` or `useEffect` that only runs once)?
