### ISSUE TITLE
Total count of a type using Appsync Serverless (using aurora)

### ISSUE THREAD

**Issue by stayingcool** [aws-amplify/amplify-js#6246]
**Is your feature request related to a problem? Please describe.**
How can we get the total count of a type using appsync serverless (using aurora)? 
I'm not able to figure out a way to get the total counts of a particular table from the database.

**Describe the solution you'd like**
This is something I see in [Hasura called Aggregate of results](https://hasura.io/docs/1.0/graphql/manual/queries/pagination.html#fetch-limited-results-along-with-data-aggregated-over-all-results-e-g-total-count-in-the-same-query)?

**Describe alternatives you've considered**
I'm new to GraphQL. Not sure about alternatives. I'm about to choose either Appsync or Hasura

**Additional context**
The above details on Hasura should help you visualize the requirement I'm asking about.

**Comment by sammartinez** [comment]
@stayingcool Is this a feature request or more so a question?

**Comment by stayingcool** [comment]
@sammartinez - Do we have the requested functionality in Amplify/AppSync?

**Comment by Ricardo1980** [comment]
That's easy, just use "SELECT COUNT(*)....." in your VTL request template and then later map it properly in your response template.
I guess your GraphQL query type has one of them that returns an integer. That's the integer you are returning in the VTL response template.

**Comment by stayingcool** [comment]
Thanks @Ricardo1980 . 

This is a feature request to provide something out of the box. Otherwise, as you stated we can certainly have a custom resolver to get this done!

**Comment by chrisbonifacio** [comment]
This should be pretty easy to implement now with Amplify Gen 2's support for MySQL/PostgreSQL databases.

You can set up a custom query that executes `SELECT COUNT ...` and returns the count, or a list of rows and count, etc.

https://docs.amplify.aws/react/build-a-backend/data/connect-to-existing-data-sources/connect-postgres-mysql-database/
