### ISSUE TITLE
NotAuthorizedException: Invalid login token. Token expired

### ISSUE THREAD

**Issue by manusharian** [aws-amplify/amplify-js#6249]
**Describe the bug**
After using `Auth.federatedSignIn(
    'google',
    { token, expires_at: 1978332974 * 1000 + new Date().getTime() },
    user
  )`
with google provider after an hour the token expires. To prevent this at regular intervals currentCredentials() is called and the token is refreshed. If the application is closed or there is no internet connection to refresh the token the application only receives [NotAuthorizedException: Invalid login token. Token expired: 1594112831 >= 1594036133].
Even if currentAuthenticatedUser() returns a user (including the refresh token) any calls to currentSession, currentCredetinals and other functions from Auth class give the same error. 
We also use federatedSignIn for Facebook, there is no such error as for google.

**To Reproduce**
After federatedSignIn with google wait an hour then call surrentSession() or currentCredentials() token expired appear

**Expected behavior**
-

**Code Snippet**

**Screenshots**

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.
* Which resources do you have configured?
  * If applicable, please provide your `aws-exports` file:
   ```
  aws_cognito_identity_pool_id: 'eu-central-XXXXXX',
  aws_cognito_region: 'eu-central-1',
  aws_facebook_app_id: '3XXXXX',
  aws_facebook_app_permissions: 'public_profile, email',
  aws_google_app_permissions: 'email,profile,openid',
  aws_google_web_app_id: 'XXXXXXXXXm',
  aws_project_id: 'xxxxxxxx',
  aws_project_name: 'trimwi_prod',
  aws_project_region: 'eu-central-1',
  aws_resource_name_prefix: 'txxxxxxx',
  aws_sign_in_enabled: 'enable',
  aws_user_files: 'enable',
  aws_user_files_s3_bucket: 'xxxxxxx',
  aws_user_files_s3_bucket_region: 'eu-central-1',
  aws_user_pools: 'enable',
  aws_user_pools_id: 'exxxxxx',
  aws_user_pools_mfa_type: 'OPTIONAL',
  aws_user_pools_web_client_id: 'xxxxxx',
   ```
**Additional context**
We are using expo and Google.logInAsync({})

**Comment by dymyll** [comment]
I am also having this issue with the token refresh!

**Comment by svidgen** [comment]
FYI. I wasn't able to reproduce this, but I'll dive on this and continue trying to repro on Monday. I'm not 100% convinced this isn't a problem yet.

Are you still having this problem?
