### ISSUE TITLE
CognitoUser.prototype.setUserMfaPreference is missing from typescript index

### ISSUE THREAD

**Issue by HopScotch47** [aws-amplify/amplify-js#625]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
Method is missing.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

What is the expected behavior?
The function should be exposed

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
2.0.3
You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by yuntuowang** [comment]
Hi @HopScotch47, I have sent a PR about this fix to Amplify team. They will review it and merge it soon! Thanks.

**Comment by CrispySnow** [comment]
Hello, I have seen that this was merged - thank you.
When will a new version be available on npm?

**Comment by AhmedAdes** [comment]
After testing with version 2.0.5 pushed to NPM yesterday
the function **setUserMfaPreference** still expects string[] parameters while it should take parameters of type any like that described in the documentation :
totpMfaSettings = {
PreferredMfa : true,
Enabled : true
};

**Comment by yuntuowang** [comment]
@powerful23 will merge in the fix very soon.

**Comment by whiskerch** [comment]
Is there any updates to a fix for this - I see that in the 2.0.14 unstable releases still expect a string[]

**Comment by powerful23** [comment]
@whiskerch sorry about that, will fix it soon.
