### ISSUE TITLE
For multiple frontends, assign different Cognito user pool group based on frontend

### ISSUE THREAD

**Issue by secretshardul** [aws-amplify/amplify-js#6251]
**Which Category is your question related to?**
Authentication

**Amplify CLI Version** 
4.18.1

**What AWS Services are you utilizing?**
Cognito, DynamoDB, Appsync

**Provide additional details e.g. code snippets**
My web app has 2 frontends for 2 user groups- 'advertisers' and 'players'. As per the GraphQL schema, advertisers create data and players read it. Users should be assigned a Cognito user group depending on which frontend they sign up from. How can this be implemented?

I'm able to assign users to a single group using a post-confirmation Lambda trigger. Is there a way to detect the frontend and assign groups accordingly?

**Comment by brene** [comment]
This seems to be JS specific. cc @sammartinez
