### ISSUE TITLE
UI-Components Sign Up assumes uncofirmed after sign up submit

### ISSUE THREAD

**Issue by wrightkris** [aws-amplify/amplify-js#6252]
https://github.com/aws-amplify/amplify-js/blob/941e6a8f1e6dee2630ca239b00889ca479ecba84/packages/amplify-ui-components/src/components/amplify-sign-up/amplify-sign-up.tsx#L151

**Describe the bug**
The sign up component makes the assumption that the user signing up is not confirmed after `Auth.signUp` is called. As Cognito supports triggers that modify the "default" authentication flow it may be the case that a user is already confirmed after `Auth.signUp` returns. I believe this is exposed in the response via the `userConfirmed` property of `ISignUpResult`.

**Expected behavior**
If a user is already confirmed after `Auth.signUp` then the subsequent `AuthState` should be `AuthState.SignIn` instead of `AuthState.ConfirmSignUp`.

**Comment by jordanranz** [comment]
Great feedback @wrightkris, this should be a fairly straightforward fix to make. I'll see if I can submit a PR for this.

**Comment by wrightkris** [comment]
Thanks @jordanranz ; I'll also look to get the codebase setup locally for dev so I can hopefully just submit PRs alongside these small issue reports to be a bit more helpful.

**Comment by wrightkris** [comment]
@jordanranz out of curiosity is there a recommend method of manually transitioning `AuthState` when using the `AmplifyAuthenticator`? I've seen https://github.com/aws-amplify/amplify-js/issues/5825#issuecomment-631759616 and we're using that in order to render post-authenticated components, but as a potential workaround to the above I haven't had success in setting the state back to `AuthState.SignIn` when `onAuthUIStateChange` sees the new state as `AuthState.ConfirmSignUp` -- it always seems to render the confirm slot.

**Comment by jordanranz** [comment]
@wrightkris that would be super helpful! Feel free to ping me in our Discord if you have any questions.

Internally we use [this](https://github.com/aws-amplify/amplify-js/blob/main/packages/amplify-ui-components/src/common/helpers.ts#L34) `dispatchAuthStateChangeEvent` method which is a wrapper around our Hub utility. I am thinking this might be something we can expose similar to `onAuthUIStateChange`. This being said if a workaround is needed you could copy the code in the `dispatchAuthStateChangeEvent`.

**Comment by wrightkris** [comment]
Fixed by #6429
