### ISSUE TITLE
AWS Lambda Custom Authorizer: Inconsistent Authorization header name

### ISSUE THREAD

**Issue by hasanbaloch** [aws-amplify/amplify-js#6255]
**Describe the bug**
The authorization header name inside the lambda function is not consistent with the authorization header name set in Lambda Authorizer.

**To Reproduce**

Create custom lambda authorizer from the API Gateway service and choose the header name as "authorization"
Make an api call using Postman and set the header name to "authorization". The lambda authorizer will not throw any exception.
After the request has been passed from Lambda Authorizer to Lambda function which will service the request, observe lambda's request parameter object APIGatewayProxyRequest > Headers.
The header name received in the lambda function will always be "Authorization" instead of "authorization".

**Which AWS service(s) are affected?**
API Gateway

**Expected behavior**
The name of the authorization header inside the lambda function must be in the same case as it was set by the initiator of the api caller - "authorization"

**Environment Information (please complete the following information):**
AWS dotnet 3.0

**Comment by sammartinez** [comment]
@hasanbaloch This seems to be related to AWS Lambda more so than Amplify, are you using Amplify? If not, I recommend opening up a AWS forums issue for [AWS Lambda}(https://forums.aws.amazon.com/forum.jspa?forumID=186&start=0) with this feedback.
