### ISSUE TITLE
After signout it updating the authState to signedIn (User is disabled and made force signout)

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#6256]
I disabled the user and try to force signout and it did the signout event.

But again the Auth Data is being set in the Authenticator - authState has been updated to signedIn 

Authenticator - authState has been updated to signedIn

I am using   **Auth.currentAuthenticatedUser({ bypassCache: true })**

**Comment by mauerbac** [comment]
Hi @nihp - I see you've opened multiple bug reports. It looks like these are all questions. It's better to use our [discussion section](https://github.com/aws-amplify/amplify-js/discussions) or our [Discord](www.discord.gg/amplify). 

To be able to help we need more information. Please follow the template in the GitHub workflow.

**Comment by nihp** [comment]
@mauerbac No one is responding to any of the threads. So opened like this. Will discuss in a one thread going forward.
