### ISSUE TITLE
After Auth.signOut() hub listen showing the state as signedIn and needs to reload the app to show the state as signIn (If the user state is disabled and make force signout for the disabled user ) 

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#6257]
I disabled a user from pool and make force logout for that user.

Here after logout it returning the Hub.listen with Auth.currentAuthenticatedUser({ bypassCache: true }) returns the Auth data and changing the state as signIn to signedIn.

  ```
Hub.listen('auth', (data) => {
        console.warn('Hub.auth event:', data);
            if (payload.event !== 'signOut') {
              Auth.currentAuthenticatedUser({ bypassCache: true })
                  .then(u => {
                      console.log('Auth.currentAuthenticatedUser result:', u);
                      navigates to home screen;
}, err => { console.warn("err ===" + err)
```
Then I will reload the app. It works and the state goes to signIn and able to see the SignIn screen,

https://github.com/aws-amplify/amplify-js/pull/5587/commits

**Comment by mauerbac** [comment]
Hey @amhinson - I see your PR is linked. Are you able to take a look at this one?

**Comment by amhinson** [comment]
@nihp Just to make sure I am understanding correctly, are you calling `Auth.signOut()` in your code and then `Auth.currentAuthenticatedUser({ bypassCache: true })` is still returning a user?

**Comment by nihp** [comment]
Thanks for your response.

Yes, it returns empty data (Auth data is return to null) and then immediately changing the state as signedIn. Auth data was set after event: signout.

Note: Can you let me know the exact behaviour for the below. I have summarized my findings

1. If the user is disabled by the admin, how the user know he is disabled immediately. (Now after disabling the user he can still access the app. Can I get any response for this behaviour immediately?
2. In case if the disabled user is in the app, how long the user can access the app?

**Comment by nihp** [comment]
Need more clarification on this issue.

**Comment by nihp** [comment]
Didn't got any solution for this

**Comment by mauerbac** [comment]
Let me ping @amhinson about this @nihp .

**Comment by amhinson** [comment]
@nihp would you be able to provide a full code snippet or repo that shows this behavior you're seeing? I haven't been able to reproduce it so far, unfortunately.

**Comment by nihp** [comment]
@amhinson Follow this steps. You can able to reproduce the same.

1. Login to your app (Auth.signIn)
2. Then you can able to go inside the app
3. Then go to the aws cognito and disable the user in pool(which you have used to login the app in step1)
4. Then go to the app. Here you can able to access the app for one hour.
5. Here still the user can able to access the app. **It is not good to access the app for the disabled user. Need to make the user to force logout the app**
6. Still shows the state as signedIn

**Comment by amhinson** [comment]
Following the steps you provided, on step 4/5 Cognito my "logged in" user (who I just disabled) is no longer authorized to make any requests, and running `Auth.currentAuthenticatedUser({bypassCache: true})` gives me a `not authenticated` error. This sounds like the behavior you are expecting. At this point in your app, you can redirect them to the login screen.

If you are still having issue, I would highly suggest creating a sample repo so that we can easily replicate the specific issue you are seeing. Describing the workflow is helpful to an extent, but a working sample is typically the best way to show reproduce-ability for what you are experiencing.
