### ISSUE TITLE
Signing with GitHub

### ISSUE THREAD

**Issue by andreacavagna01** [aws-amplify/amplify-js#6258]
I want to enable OAuth login with GitHub, like in the example [here](https://developer.github.com/v3/guides/basics-of-authentication/).

It is in the roadmap?

**Comment by mauerbac** [comment]
This can also solved by including documentation/tutorials around how to use Amplify Auth with GitHub. The doc request is here -> https://github.com/aws-amplify/docs/issues/755

**Comment by mauerbac** [comment]
hey @andreacavagna01 - just to be clear, we do not support GitHub login out of the box and while it's possible to configure manually it would be a substantial amount of work. This is not on our immediate roadmap. I'd suggest building this directly with GitHub https://docs.github.com/en/developers/apps/authorizing-oauth-apps

**Comment by andreacavagna01** [comment]
Thanks 😊

**Comment by nadetastic** [comment]
Closing out this issue in order to consolidate it with https://github.com/aws-amplify/amplify-js/issues/3347 which is an ask to provide support for additional providers by default.
