### ISSUE TITLE
User can access the app after disabled the user by admin in cognito (using aws-amplify-react-native)

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#6271]
I have disabled a user in cognito. But the user is already in the app. Here he not received any error and also it will allow him to use the app.

How can I make the user to out of the app immediately after the disable action in cognito?

**Comment by mauerbac** [comment]
Hi @nihp - this sounds more like a question rather than a bug report. Can you provide more information? What is the error?
