### ISSUE TITLE
We are facing problems with Amplify related to social network login

### ISSUE THREAD

**Issue by abudakhmad** [aws-amplify/amplify-js#6274]
Here is the description of the problem:
I opened totaly new browser and swithced on incognito mode, than I entered our platform via facebook login. after that I did log-out from the system and opened facebook page and did log-out from the facebook itself, after that I opened our platform one more time and pressed sign in via facebook and it landed me directly into the system without asking any credentials. I was trying to clear all local storage and cookies and it also didn't help. I'm attaching prototype project with Amplify and it also has the same behaviour like I described above. Can you please assist us with this issue

**Comment by elorzafe** [comment]
@abudakhmad 

```javascript
<button onClick={() => Auth.signOut({ global: true }).then(() => window.location.href = "/")}>Logout</button>
```

For some reason the promise ` Auth.signOut({ global: true })` is resolved before the logout request is sent from the browser. I am looking at right now, `window.location.href="/"` is cancelling the request.

**Comment by elorzafe** [comment]
@abudakhmad 

Why do you need to do `window.location.href = "/"`, even if OAuth flow has sign out url?

**Comment by abudakhmad** [comment]
> @abudakhmad
> 
> Why do you need to do `window.location.href = "/"`, even if OAuth flow has sign out url?

We need it in order to redirect user to the main page. So if I understand right, we need to wait until there will be fix from the Amplify side?
