### ISSUE TITLE
Because there are two different users when logging in with facebook

### ISSUE THREAD

**Issue by Mersmith** [aws-amplify/amplify-js#6281]
Because there is duplication of users in AWS Cognito
Register a user with name, email and cell phone. After that, log in with Facebook. And I register another user with the same email.
I have two users with the same email.
How do I solve that problem?
AWS AMPLIFY AND COGNITO
...............................
1. AWS COGNITO 
2. USERS POOL
..............................
USER 1: ID: 25dec813-1a05-44f5-85d9-b0e9c5687957 | Enabled | CONFIRMED | email: mersmith14@gmail.com

USER 2: ID: Facebook_877704272710563 | Enabled | EXTERNAL_PROVIDER | email: mersmith14@gmail.com
..................

Differents IDs, but the same emails. :( 
It should be one.
A user with multiple ways to log in.

![87100921-348c5280-c213-11ea-9794-33f4fcf3053d](https://user-images.githubusercontent.com/29002211/88556469-abd12d00-cfee-11ea-9d3e-71815220f663.jpg)

![ayuda](https://user-images.githubusercontent.com/29002211/87095810-07d23e00-c207-11ea-8d2e-2ff7e92a6a0e.jpg)
"aws-amplify": "^3.0.10"

**Comment by brene** [comment]
cc @sammartinez

**Comment by sammartinez** [comment]
@Mersmith can you provide us with your environment information so we can dig into this further? 

Please run the following command: 
```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

This will help us further assist you on this.

**Comment by Mersmith** [comment]
> npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages

System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
    Memory: 3.60 GB / 7.90 GB
  Binaries:
    Node: 12.7.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.10.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
    Internet Explorer: 11.0.18362.1
  npmPackages:
    @testing-library/jest-dom: ^4.2.4 => 4.2.4
    @testing-library/react: ^9.5.0 => 9.5.0
    @testing-library/user-event: ^7.2.1 => 7.2.1
    aws-amplify: ^3.0.10 => 3.0.10
    aws-amplify-react: ^4.1.9 => 4.1.9
    react: ^16.13.1 => 16.13.1
    react-dom: ^16.13.1 => 16.13.1
    react-icons: ^3.10.0 => 3.10.0
    react-scripts: 3.4.1 => 3.4.1
    uuid: ^8.0.0 => 8.0.0
  npmGlobalPackages:
    @aws-amplify/cli: 4.18.1
    @vue/cli-init: 3.11.0
    @vue/cli: 3.10.0
    firebase-tools: 7.2.2
    node-gyp: 6.1.0
    nodemon: 2.0.2
    react-devtools: 4.4.0
    vue-cli: 2.9.6
    windows-build-tools: 4.0.0

**Comment by Mersmith** [comment]
@sammartinez When I log in normally without Facebook it creates an id. But when I log in with facebook it creates another user id.

It is rare because I am the same user with the same email but with different id.

And when I make a call from all the users, they both leave with the same emails.

That happens to me when I log in with Facebook and Google.

It would be nice if a single user manages many login accounts. Is it possible to do that?

![r7u3pmm5ztjn9z66g7mm](https://user-images.githubusercontent.com/29002211/87100921-348c5280-c213-11ea-9794-33f4fcf3053d.jpg)

**Comment by ianmartorell** [comment]
Is this really related to the Amplify JS repo? It sounds like this is what you're looking for: https://github.com/aws-amplify/amplify-cli/issues/4427

**Comment by sammartinez** [comment]
@Mersmith I apologize for not getting back to you sooner on this. This looks to related specifically to Amazon Cognito. I would recommend to reach out them via [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=173) to see if there is a way to combined these users as they are one in the same.
