### ISSUE TITLE
TOTP Setup doesn't work if Cognito Pool has remember devices

### ISSUE THREAD

**Issue by BDNilsson** [aws-amplify/amplify-js#6283]
**Describe the bug**
If a cognito pool has settings to remember a device (opt-in or always) the login fails when setting up MFA.

**To Reproduce**
1. Create cognito pool with MFA required, and devices remembered
2. Use a user created by an admin without a phone number to enforce MFA SETUP
3. Login as the new user, scan the qr code and enter the code.
4. You will get an error: "NotAuthorizedException" "Invalid Refresh Token."
5. Refresh and try to log in now
6. log in will be successful

**Expected behavior**
Login should be successful on initial setup  (this is true if devices are not remembered)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Firefox

**Additional context**
Expected behavior does indeed happen if the user pool has device settings set to No.

I believe in the initial MFA setup no device settings are sent which causes the refresh token error, however when not doing the initial setup device settings are sent which is why it works.

**Comment by sammartinez** [comment]
@BDNilsson are you still looking for support for this issue? If so, can you please provide your `package.json` to us to help reproduce this issue further? Please let us know.

**Comment by BDNilsson** [comment]
Just ran into this issue again on a new project

In the last project i just forced a refresh and made the user log in again as a work around which was not great but worked there, this time i don't have that option.

This was on a Angular 9 project clean project.

Same instructions to reproduce using the amplify-authenticator

Attached package.json file.

[package.json.txt](https://github.com/aws-amplify/amplify-js/files/5427087/package.json.txt)

**Comment by chrispruitt** [comment]
@sammartinez I just came across this issue. My MFA set up was working and then all of a sudden it broke after selecting "Always remember devices" in Cognito. I am seeing this at the very basic level using amplify components with defaults and in the Cognito user poo, l have set MFA to required TOTP. 

I am seeing the exact same issue with the above steps to reproduce.

```<amplify-authenticator>
hello, you are logged in
    </amplify-authenticator>
    ```
    
    amplify modules used:
    ```
    "@aws-amplify/ui-vue": "0.2.31"
    "aws-amplify": "3.3.12"
    ```
