### ISSUE TITLE
Code not received while signUp and confirmSignIn the app using aws-amplify-react-native  (now it works fine before)

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#6286]
Code not received while signUp the app using aws-amplify-react-native.

If I click the resend code it will shows **code resent successfully** message. But still not received the code. Same issue happens for confirmSignIn.

Note: Still yesterday it works today onwards not working.

I am using **aws-amplify** and **aws-amplify-react-native**

**Comment by mauerbac** [comment]
hey @nihp - I mentioned in previous issues that we need more information to reproduce the bug you are experiencing. The template should have more info on this. 

I think it would be easiest if we hopped on a call to help sort some of these issues. Are you able to join our [Discord](www.discord.gg/amplify) and send me a DM? My username is mauerbac on there and we can setup time.

**Comment by nihp** [comment]
I think the code received issue is with limit exceeds. Can you let me know any doc related how can i check the SMS limits?

Why the amplify always shows code sent successfully message.

Thanks @mauerbac. Will let you know.

**Comment by amhinson** [comment]
Closing, as this appears to be related to Cognito and not Amplify.

Reference: https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-mfa-sms-text-message.html

**Comment by nihp** [comment]
@mauerbac I have clarifications. https://github.com/aws-amplify/amplify-js/issues/6393.

Any thoughts?
