### ISSUE TITLE
Sign In With Apple via IdentityPool configuration - NotAuthorizedException: Invalid login token. Incorrect token audience.

### ISSUE THREAD

**Issue by Larsrdev** [aws-amplify/amplify-js#6287]
**Describe the bug**
We managed to implement Sign In With Apple in our iOS mobile application. There is still a bug with that the user is only logged in during the 10 min, until the JWT is expired: 
https://github.com/aws-amplify/aws-sdk-ios/issues/2513
https://github.com/aws-amplify/aws-sdk-ios/issues/1809

Despite of this we started to add the "Sign In With Apple" for our web application. According to [this](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/configuring_your_webpage_for_sign_in_with_apple) documentation, we added the appleid.auth.js and call it via

```
AppleID.auth.init({
            clientId: 'com.test.app.dev',
            scope: 'name email',
            redirectURI: 'https://app.test.com',
            state: '',
            usePopup: true,
        });
```

As clientId we use the Apple Services ID Identifier with our corresponding Domain and Return-URL (in this picture from the [amplify-docs](https://docs.amplify.aws/lib/auth/social/q/platform/js#setup-your-auth-provider) the 'com.amazonaws.awesomeapp.sid')
![image](https://user-images.githubusercontent.com/29222942/87167697-a7f29a80-c2cd-11ea-9b9e-d41f64de5573.png)

The Apple Sign In window pops up, the sign in process completes and we get a valid JWT token from apple. 
After this we call Amplify Auth:
```
Auth.federatedSignIn('appleid.apple.com',
                {
                    token, // JWT from apple 
                    expires_at: now +10 min // JWT is only valid for 10 min
                },
                {
                    name: 'apple-user',
                }).then((value) => {
                resolve();
            }).catch((error) => {
                reject(error);
            });
```

This returns an error: 
**NotAuthorizedException: Invalid login token. Incorrect token audience.**

We tried to add Apple Services ID Identifier to the IdentityPool Auth Provider like in the next picture:
![image](https://user-images.githubusercontent.com/29222942/87168897-737fde00-c2cf-11ea-85eb-3e769ca1e6a0.png)

But this doesn't work. We also need this field for our iOS application (bundle ID), but we can only add one Apple Service ID. But Apple demands that the mobile application (App ID) and web application (Service ID) cannot have the same value. 
Is there a way to enable Apple Web login and Apple Mobile login at the same time for a single IdentityPool?

Edit (07/13/2020): As mentioned in the official [Amplify - Sign in with Apple (Identity Pools)](https://docs.aws.amazon.com/cognito/latest/developerguide/apple.html) tutorial, we need to add two Apple-Services IDs for the Identity Pool, but this is not possible:

> If you use Sign in with Apple with native iOS applications, enter the BundleID you obtained from developer.apple.com. Or if you use Sign in with Apple with web or other applications, enter the service ID. Then choose Save Changes.

**Comment by cornr** [comment]
Now we get a "Token is not from a supported provider of this identity pool." Error

**Comment by tylerjames** [comment]
Is there any resolution for this? 

The obvious use case is that the user creates the account on their iPad using Sign In With Apple and then would want to be able to use SIWA to log in to the account on their Android phone.

From here: https://stackoverflow.com/questions/62382400/cognito-identity-pool-integrate-apple-provider-with-app-and-web

It seems like the only way is to have multiple user pools? That seems a bit absurd but if it's the official method then can we get a doc outlining how to manage this?

Thanks

**Comment by sammartinez** [comment]
For clarity @Larsrdev, are you having issues with Amplify JS or Amplify iOS? Please let us know.

**Comment by Larsrdev** [comment]
Sorry, as I am not part of that project anymore, I can't give you an answer if its already fixed.
