### ISSUE TITLE
Add signout component to aws-amplify-react

### ISSUE THREAD

**Issue by wichert** [aws-amplify/amplify-js#630]
This is a feature request: when creating a custom UI you can reuse a lot of existing components normally used in the greeter such as `SignIn` and `SignUp`. It would be very practical if there was a `Signout` component as well. At the moment all the logout logic is hardwired in `Greetings`, which also insists on adding a navbar-structure around the logout button making it unusable in your own UI.

My current workaround is a bit ugly, but effective:

```javascript
class App extends React.Component {
  render() {
    return (
      <button onClick={this.handleLogout}>Logout</button>
    );
  }

  handleLogout = () => {
    const {authState, authData} = this.props;
    const greetings = new Greetings({
      authState,
      authData,
      onStateChange: this.handleAuthStateChange,
    });
    greetings.signOut();
  }
}
```

**Comment by richardzcode** [comment]
This might help: https://github.com/richardzcode/Journal-AWS-Amplify-Tutorial/tree/master/step-02#4-greetings

**Comment by shanonvl** [comment]
@wichert I worked around this using [Auth.signOut](https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify/src/Auth/Auth.ts#L839) directly:

```js
import { Auth } from 'aws-amplify'
...
try {
   await Auth.signOut()
   // signout success
}
catch(e) {
   // signout failed
}

```

**Comment by richardzcode** [comment]
I believe this one can be closed as `SignOut` component is available now.
