### ISSUE TITLE
Unappropriate behaviour during Authentication

### ISSUE THREAD

**Issue by Badal1234** [aws-amplify/amplify-js#6303]
**Describe the bug**
I have Signed up using email and password , got security code to verify my email.when I have entered my code It shows 'Not Authenticate' error on my application but email was got verified in aws console.

When I tried to login with that email and password It shows 
Object {
  "code": "UserNotFoundException",
  "message": "User does not exist.",
  "name": "UserNotFoundException",
}

But When I tried to signup with that email and password It showed me
Object {
  "code": "UsernameExistsException",
  "message": "An account with the given email already exists.",
  "name": "UsernameExistsException",
}

I can see the user through my aws console

I did not understand this type of behaviour.
Could any one guide me in this matter as it is a urgent to me

Thanks

**Comment by amhinson** [comment]
@Badal1234 Would you be able to provide a minimal reproduction example so we can try to replicate the behavior you are seeing?

**Comment by Badal1234** [comment]
Hii @amhinson ,
Actually this happens during signup process.after signing up through username and password I get verification code.
when I submit that code It shows me the error of 'not authenticated'.But in aws console i can see the email_verified is true of that user

**Comment by amhinson** [comment]
Ah ok! However, we will still need more information regarding your app in order to diagnose the issue. Could you share the following info:
- Amplify libraries you are using & versions
- `aws-exports` or manual configuration
- Steps you took when setting up Amplify via the CLI (i.e. `amplify add auth`, `default configuration`, etc)
