### ISSUE TITLE
Updates to "Local Development" guides

### ISSUE THREAD

**Issue by dabit3** [aws-amplify/amplify-js#6305]
It would be nice to update the "local development" guides to:

1. Show updated references to UI libraries - aws-amplify-react -> @aws-amplify/ui-react
2. Be more user friendly and descriptive

https://github.com/aws-amplify/amplify-js/wiki/Local-Development

**Comment by ashika01** [comment]
@dabit3 We updated our [contributing guidelines](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md) recently. Let me know if you have specific comments on that other than new ui reference. I can update that and move the content over to the wiki :D

**Comment by dabit3** [comment]
Thanks @ashika01 this looks great, I'll close this issue.
