### ISSUE TITLE
Amplify setup with ALB OIDC authentication in React app

### ISSUE THREAD

**Issue by deeprao2811** [aws-amplify/amplify-js#6308]
I have a use case where there is a Identity provider configured in Cognito which has its own 3rd party SSO. The ALB uses the OIDC authenticate rule which then redirects to a React app hosted on port 80. I am unable to find enough documentation on how this particular setup can be supported by Amplify library and what configuration needs to be used. To test I have created a simple Cognito user pool and used that as a OIDC authentication rule on the ALB which redirects the request to my EC2. This EC2 has my React app that is using the Amplify library to be able to get the logged in user. When I try to log currentAuthenticatedUser() in the console, it always prints "Not signed in". Any help would be appreciated. Thanks

**Comment by amhinson** [comment]
@deeprao2811 Would you be able to provide more details on your current implementation using `aws-amplify`?
