### ISSUE TITLE
Couldn't deploy custom Lambda Layer from yumda

### ISSUE THREAD

**Issue by ErickWendel** [aws-amplify/amplify-js#6317]
**Describe the bug**
I'm trying to install custom layers using [yumda](https://github.com/lambci/yumda). So I've installed the **GraphicsMagick** on /amplify/backend/function/gm/opt. When I deploy I see the "An error occurred hashing directory" error.

**To Reproduce**

1. Install the GraphicsMagick package on `/opt` layer

```sh
docker run --rm \
    -v "$PWD"/amplify/backend/function/gm/opt:/lambda/opt \
    lambci/yumda:2 yum install -y GraphicsMagick
```

2. Run`amplify push`
4. See error:

```sh
An error occurred hashing directory /Users/erickwendel/Documents/pocs/amplify/meme-maker/app/amplify/backend/function/gm/opt
An error occurred during the push operation: An error occurred hashing directory /Users/erickwendel/Documents/pocs/amplify/meme-maker/app/amplify/backend/function/gm/opt
```

**Expected behavior**
Upload the custom package and inject on the runtime

**What is Configured?**

<details>
  <summary><strong>Environment</strong></summary>

```

  System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 116.02 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.0.0 - /usr/local/bin/node
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 81.1.9.76
    Chrome: 83.0.4103.116
    Safari: 13.0.5
  npmGlobalPackages:
    @aws-amplify/cli: 4.24.0
    autocannon: 4.6.0
    create-react-app: 3.4.1
    fkill-cli: 6.0.1
    npm: 6.14.6
    ntl: 5.0.0
    serverless: 1.67.0
    sloc: 0.2.1
```

</details>

**Comment by SebastianHurubaru** [comment]
Hi Erick,

I have seen you have closed this issue. How did you manage to solve it, as I have the same issue.

Thanks!
