### ISSUE TITLE
Loading spinner color can't be overridden by changing the CSS variable

### ISSUE THREAD

**Issue by lewis-geek** [aws-amplify/amplify-js#6331]
**Describe the bug**
I overrode CSS variable `--amplify-primary-color` value, default is #ff9900, but when amplify-loading-spinner component showing up, I found the color of the loading icon still is the default value which is #ff9900.

The loading icon color value is hardcoding in the codebase, I think we should let this color same with the custom setting, for uniform style.

**To Reproduce**

1. Change the  CSS variable `--amplify-primary-color` value
2. Open sign in dialog by using `AmplifySignUp` component
3. Click sign in button
4. You can see the color of the loading icon still is default color

**Expected behavior**
The expected behavior is the color of the loading icon change to the custom value

**Code Snippet**
related code: https://github.com/aws-amplify/amplify-js/blob/68af3abb54d5af4e1bcedacb8e2137e10e2c971c/packages/amplify-ui-components/src/components/amplify-icon/icons.tsx#L169

**Screenshots**
Gif of the issue:
![screen record](https://user-images.githubusercontent.com/8927407/87527481-c33f1a80-c6be-11ea-8d71-84138b0f4b0d.gif)

**Comment by jordanranz** [comment]
I have add this behavior in #6338 which is now on the `@unstable` version. If possible could you test this version and see if your issue is solved?

**Comment by lewis-geek** [comment]
Hi @jordanranz ! It is working fine with @unstable version, Thanks for your help to fix this issue!

Screenshot:
![image](https://user-images.githubusercontent.com/8927407/87701126-020dc700-c7ca-11ea-9fbe-cf511189a77e.png)

**Comment by jordanranz** [comment]
This is now on `@latest`. Closing now. If you have any further related problems, please open a new issue.
