### ISSUE TITLE
Amplify should only create modules configured and should provide a way to 'clean-up'

### ISSUE THREAD

**Issue by cheedep** [aws-amplify/amplify-js#634]
Do you want to request a feature or report a bug?
Bug
What is the current behavior?
After Unit tests are completed, mocha does not terminates as something from the Amplify module is preventing it. 

What is the expected behavior?
There should be a way to clean-up the Amplify module. There should be a way to just use select modules from Amplify. For example if I just want to use Auth and API, it should not be creating Hubs, PubSub etc..

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
All browsers

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

[DEBUG] 06:00.109 Cache - Using AsyncStorageCache
[DEBUG] 06:00.112 InMemoryCache - now we start!
[DEBUG] 06:00.112 InMemoryCache - Using InMemoryCache
[DEBUG] 06:00.117 Auth - Create Auth Instance
[DEBUG] 06:00.118 AuthClass - configure Auth
[DEBUG] 06:00.118 AuthClass - Do not have identityPoolId yet.
[DEBUG] 06:00.118 Analytics - Create Analytics Instance
[DEBUG] 06:00.119 Hub - noname listening auth
[DEBUG] 06:00.119 Hub - noname listening storage
[DEBUG] 06:00.120 Hub - noname listening analytics
[DEBUG] 06:00.122 Storage - Create Storage Instance
{ '[DEBUG] 06:00.122 StorageClass - Storage Options': null }
{ '[DEBUG] 06:00.124 StorageClass - Storage Options': { level: 'private' } }
[DEBUG] 06:00.151 API - Create API Instance
{ '[DEBUG] 06:00.151 API - API Options': null }
[DEBUG] 06:00.156 PubSub - Create PubSub Instance
{ '[DEBUG] 06:00.156 PubSub - PubSub Options': null }

SideNote: **is paho-mqtt being used**? 
I see the import in aws-amplify/packages/aws-amplify/src/PubSub/PubSub.ts
import { Client } from 'paho-mqtt';
but Client is not used.

**Comment by mlabieniec** [comment]
@cheedep totally agree! We are working on moving from webpack to rollup to do this. It requires a bit of refactoring and cleanup on the typescript side which we will be working on next! And the plan is to do exactly this i.e. allow importing only of specific modules.

Yes paho-client is used for the PubSub category.

**Comment by sammartinez** [comment]
We currently have an open RFC that we are tackling modularization. I am going to resolve this issue in favor of the RFC and no update since April 2018. Please feel free to comment on the RFC.
