### ISSUE TITLE
Import `AsyncStorage` from `@react-native-community` instead of `react-native`

### ISSUE THREAD

**Issue by Jahans3** [aws-amplify/amplify-js#6341]
Newer React Native versions show a warning about `AsyncStorage` moving to `@react-native-community`:

```
Warning: AsyncStorage has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/async-storage' instead of 'react-native'. See https://github.com/react-native-community/async-storage
```

**Comment by amhinson** [comment]
@Jahans3 Thanks for opening this feature request! However, we are currently tracking this in #6031, so I'm going to close this one for now. It is currently is the works, but here is a short overview of why we have delayed the move to the RNC version: https://github.com/aws-amplify/amplify-js/pull/4027#issuecomment-628050861
