### ISSUE TITLE
Amplify with Vue.js "No Access-Control-Allow-Origin header" response.

### ISSUE THREAD

**Issue by SamnnyWong** [aws-amplify/amplify-js#6357]
**Describe the bug**
CORS error is raised when trying to call a lambda function in vue.js using amplify api via aws api gateway.  

In vue component:
```
 async loadNotes() {
 await API.get("Test", "")
                    .then(function(response){
                        //do soemthing in here
                        console.log(response);
                    })
}
```

my lambda function:
```
exports.handler = function(event, context, callback) {
  const response = {
    statusCode: 200,
    headers: {
      'Access-Control-Allow-Origin': '*', // Required for CORS support to work
      'Access-Control-Allow-Credentials': true, // Required for cookies, authorization headers with HTTPS
    },
    body: JSON.stringify({ message: 'Hello World!' }),
  };
```
aws configure as follows in main.js of the vue frontend:
```
Amplify.configure({
  Auth: {
    mandatorySignIn: true,
    region: config.cognito.REGION,
    userPoolId: config.cognito.USER_POOL_ID,
    identityPoolId: config.cognito.IDENTITY_POOL_ID,
    userPoolWebClientId: config.cognito.APP_CLIENT_ID
  },
  Storage: {
    region: config.s3.REGION,
    bucket: config.s3.BUCKET,
    identityPoolId: config.cognito.IDENTITY_POOL_ID
  },
  API: {
    endpoints: [
      {
        name: "Test",
        endpoint: "https://xxxxxxxx.execute-api.us-east-1.amazonaws.com/Test/",
        region: config.apiGateway.REGION,
      }
    ]
  }
});
```
**Screenshots**
AWS api gateway cors is enabled.
<img width="1386" alt="Screen Shot 2020-07-18 at 00 20 15" src="https://user-images.githubusercontent.com/2942477/87844592-89bc0a00-c88c-11ea-835c-fee66b53523d.png">

I am suspecting if i need to configure extra parameters when calling API.get() in my vue components. But i could not find any docs on whats the property i can put in my extra params.

Thanks in advance.

**Comment by manueliglesias** [comment]
Hi @SamnnyWong 

How was your api created? when created via the amplify cli, the API GW endpoint includes handling of preflight requests for CORS

If the amplify cli wasn't used, you might need to follow manual steps to handle it, [this](https://enable-cors.org/server_awsapigateway.html) might help

**Comment by gopal-abbineni** [comment]
> Hi @SamnnyWong
> 
> How was your api created? when created via the amplify cli, the API GW endpoint includes handling of preflight requests for CORS
> 
> If the amplify cli wasn't used, you might need to follow manual steps to handle it, [this](https://enable-cors.org/server_awsapigateway.html) might help

<img width="1062" alt="Screenshot 2021-02-15 at 8 41 56 PM" src="https://user-images.githubusercontent.com/12975073/107963563-58482000-6fce-11eb-837e-35d85df1656c.png">
 Created Using Amplify CLI but still facing the issue. amplify version 4.43.0
