### ISSUE TITLE
DataStore breaks when record is constantly queried after updating

### ISSUE THREAD

**Issue by nubpro** [aws-amplify/amplify-js#6358]
**Describe the bug**
This is the extreme way of reproducing the problem, however we are hitting this problem quite often and we have our own workaround for this issue.

When a user spams the update button on the same record, like I am talking about tapping the update button 10 times in a row. DataStore would throw this error: `TypeError: undefined is not an object (evaluating 'Object.getPrototypeOf(model)')`.

You can refer to the screenshot below:
![image](https://user-images.githubusercontent.com/762914/87845845-cbd16400-c8fd-11ea-95b4-743c50506119.png)
I did some additionally work and find out the error is thrown from the delete function within the asyncstorage.js file due to the `model` being undefined.

The consequence of this error is fairly large, it causes any outgoing mutations not be sent out to the backend.
This error is especially hard to catch on production mode because the error is not visible on the frontend.

**To Reproduce**
1. Using the [example React Native app](https://docs.amplify.aws/lib/datastore/examples/q/platform/js#example-react-application), add a new function to allow for Post update and an update button to the UI.

Update function
```
onUpdate = (postId) => {
    const original = await DataStore.query(Post, "123");
    
    await DataStore.save(
    Post.copyOf(original, updated => {
        updated.title = `title ${Date.now()}`;
    })
    );
}
```

Update button
```
<Text style={styles.text} onPress={() => this.onUpdate('<ID here>')}>
    Update this post
</Text>
```

2. Make sure to keep the `DataStore.observe(Post)` subscription, otherwise you won't be able to reproduce the error.
3. Tap the update button 10 times in a row as quickly as possible.
4. You are very likely to hit this error at this point.

**Expected behavior**
DataStore should somehow recover or prevent this error from happening.

**What is Configured?**
<details>
  <summary><strong>Environment</strong></summary>

```

  System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 77.89 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.3.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 83.0.4103.116
    Safari: 13.1.1
  npmGlobalPackages:
    @aws-amplify/cli: 4.22.0
    ios-deploy: 1.10.0
    npm: 6.14.4
    react-native-cli: 2.0.1
```

</details>

**Smartphone (please complete the following information):**

- Device: iPad
- OS: 13

**Comment by nubpro** [comment]
Just a small update, I removed the subscription - `DataStore.observe(Post)` and this would still happen, but I got to tap the update button more frequently and furiously.

On a side note, will this error happens if the client receives too many mutations from the server within a second? Since it's performing an update to the AsyncStoage for every mutation.

**Comment by manueliglesias** [comment]
HI @nubpro 

Thank you for the detailed report and the PR

If your use case allows it, maybe you can debounce/throtle the saves while a more permanent fix is merged to the library

**Comment by nubpro** [comment]
> HI @nubpro
> 
> Thank you for the detailed report and the PR
> 
> If your use case allows it, maybe you can debounce/throtle the saves while a more permanent fix is merged to the library

I see, appreciate the response.
Shall I close my PR?

**Comment by amhinson** [comment]
@nubpro Are you still seeing this issue? If possible, could you test with `aws-amplify@unstable`, as we have merged some changes related to this.

**Comment by sammartinez** [comment]
Resolving as no response from customer. Please let us know if you are still experiencing this issue after the upgrade to the latest version which handles this issue

**Comment by nubpro** [comment]
@amhinson your PR seems to fix the issue, thanks for the fix!

Took way too long though, but I appreciate it!

Would be great if this issue can get some attention too!
https://github.com/aws-amplify/amplify-js/issues/6363
