### ISSUE TITLE
[Feedback] `API.graphql` return signature is hard to use in TypeScript

### ISSUE THREAD

**Issue by swyxio** [aws-amplify/amplify-js#6369]
**Is your feature request related to a problem? Please describe.**

When I try to `await` an `API.graphql` call in TS, I get this:

![image](https://user-images.githubusercontent.com/6764957/87945385-3b4c7c80-cad3-11ea-8320-9accacbb42ee.png)

This is because you have defined the `graphql` method to also return an `Observable` in case of a subscription:

https://github.com/aws-amplify/amplify-js/blob/b5d14124dfd5f1000f102ac8c84aa964c9d916c5/packages/api/src/API.ts#L173-L178

This is understandable but makes it very annoying to use, particularly because if i need to assert types, the `GraphQLResult` type is not also exported for me to use.

**Describe the solution you'd like**

use overloading and/or a different function for subscriptions to make this experience easier.

ultimately i want to be able to write this:

```ts
const query = await API.graphql<TodoType[]>({query: listTodos})
```

and it should not complain. (a *REALLY* good experience, ofc, would give me that return type for free based on `listTodos`, but that would involve a much deeper redesign)

**Comment by sw-yx** [comment]
Secondly, specifying the return signature like this: 

https://github.com/aws-amplify/amplify-js/blob/b5d14124dfd5f1000f102ac8c84aa964c9d916c5/packages/api/src/API.ts#L173-L178

always assigns the generic type `T` to be `object` because that is how the `GraphQLResult` interface is designed. This causes nasty, nasty type errors when people try to assign the results of the graphql query to a properly typed variable:

![image](https://user-images.githubusercontent.com/6764957/87951748-8d919b80-cadb-11ea-9434-da83aa987d26.png)

i would recommend making `graphql` a generic as well so I can pass along the type i want:

```ts
// pseudocode, modified from source slightly
	graphql<T>(
		options: GraphQLOptions,
		additionalHeaders?: { [key: string]: string }
	): Promise<GraphQLResult<T>> | Observable<object> {
		return this._graphqlApi.graphql(options, additionalHeaders);
	}
```

**Comment by sw-yx** [comment]
for those finding this.. heres how to write a vaguely ergonomic wrapper around this.

```ts
import { GraphQLOptions} from '@aws-amplify/api-graphql'
async function gql<T extends object>(options: GraphQLOptions, additionalHeaders?: {
  [key: string]: string;
}): Promise<GraphQLResult<T>> {
  const query = API.graphql(options, additionalHeaders) as Promise<GraphQLResult<T>>
  return query
}

```

**Comment by sw-yx** [comment]
even specifying the `input`s are quite verbose so i have modified the wrapper as such:

```ts
  async function gql<T extends object>(
    query: string,
    variables?: object,
    additionalHeaders?: {
      [key: string]: string;
    }
  ): Promise<GraphQLResult<T>> {
    setLoading(true);
    const q = (await API.graphql(
      {
        query,
        variables: variables && { input: variables },
      },
      additionalHeaders
    )) as Promise<GraphQLResult<T>>;
    setLoading(false);
    return q;
  }
```

**Comment by manueliglesias** [comment]
Thanks @sw-yx !

This is a great write-up,  as you pointed out, with the current function signature it is not possible to unambiguously tell for sure if you want a promise (for queries/mutations) or an Observable (for subscriptions). This is due to the fact that the return type is not known at compile time, only at runtime (by looking at the operation type: query, mutation or subscription)

 A wrapper similar to the one you propose might be the best course of action for now while we explore a deeper redesign. And of course, exporting the `GraphQLResult` type

**Comment by sw-yx** [comment]
if you are open to deeper redesign, i think my dream API:

```ts
```

**Comment by mikeldking** [comment]
Thanks @sw-yx for opening this. The ergonomics of using typescript is very rough out of the box. Having used apollo before, being able to pass the result and variable types into the generic query function seems like a must. 

> otherwise the mismatches between the user-specified TS types and the GraphQL/DataStore schema are super annoying to have to manually maintain. (i understand this is an unrealistic dream right now)

Not having to pass in the types at all would be amazing!

**Comment by sw-yx** [comment]
related feedback from 1 year ago: https://github.com/aws-amplify/amplify-js/issues/3704#issuecomment-514769571

**Comment by sw-yx** [comment]
i also noticed that the `API.ts` autogenerated types dont seem usable but i am not sure why:

![image](https://user-images.githubusercontent.com/6764957/93265999-02333e80-f7dc-11ea-86d9-f9e8321056ca.png)

```tsx

import { API } from 'aws-amplify';
import { listBlogs } from "./graphql/queries";
import { createBlog } from "./graphql/mutations";
import { ListBlogsQuery } from "./API"; /// <----- the problematic type

type Blog = {
  title: string;
  image: string;
  body: string;
  id?: string;
  createdAt?: Date;
  updatedAt?: Date;
};

function App() {
  const [blogs, setBlogs] = React.useState<Blog[]>([]);
  const [currentSelectedBlog, setCurrentSelectedBlog] = React.useState<Blog>();

  React.useEffect(fetchBlogs);

  function fetchBlogs() {
    const query = API.graphql({ query: listBlogs }) as Promise<{data: ListBlogsQuery}>
    query.then(
      ({
        data: {
          listBlogs: { items }, // <--- type error here
        },
      }) => setBlogs(items)
    );
  }
```

**Comment by hukpavlo** [comment]
This is how I use the API with typescript, if you want, you can customize it

```
import { API, graphqlOperation } from 'aws-amplify';
import { GraphQLOptions } from '@aws-amplify/api-graphql';

class CustomApi {
  public async query<R extends any | any[], V = GraphQLOptions['variables']>(query: string, variables?: V) {
    try {
      return await this.makeRequest<R extends any[] ? { items: R; nextToken: string | null } : R>(query, variables);
    } catch (err) {
      console.error(err);
      throw new Error('Api query error');
    }
  }

  public async mutate<V extends GraphQLOptions['variables'], R = any>(query: string, variables: V) {
    try {
      return await this.makeRequest<R>(query, variables);
    } catch (err) {
      console.error(err);
      throw new Error('Api mutate error');
    }
  }

  private async makeRequest<R>(query: string, variables?: any): Promise<R> {
    const { data } = await API.graphql(graphqlOperation(query, variables)) as any;

    return data[Object.keys(data)[0]];
  }
}

```

**Comment by chriszirkel** [comment]
> This is how I use the API with typescript, if you want, you can customize it
> 
> ```ts
> import { API, graphqlOperation } from 'aws-amplify';
> import { GraphQLOptions } from '@aws-amplify/api-graphql';
> 
> class CustomApi {
>   public async query<R extends any | any[], V = GraphQLOptions['variables']>(query: string, variables?: V) {
>     try {
>       return await this.makeRequest<R extends any[] ? { items: R; nextToken: string | null } : R>(query, variables);
>     } catch (err) {
>       console.error(err);
>       throw new Error('Api query error');
>     }
>   }
> 
>   public async mutate<V extends GraphQLOptions['variables'], R = any>(query: string, variables: V) {
>     try {
>       return await this.makeRequest<R>(query, variables);
>     } catch (err) {
>       console.error(err);
>       throw new Error('Api mutate error');
>     }
>   }
> 
>   private async makeRequest<R>(query: string, variables?: any): Promise<R> {
>     const { data } = await API.graphql(graphqlOperation(query, variables)) as any;
> 
>     return data[Object.keys(data)[0]];
>   }
> }
> ```

Can you give an example on how you use this Api with the generated statements and types?

**Comment by gruckionvit** [comment]
You need to wrap the await inside an async iffy and place this inside the scope of the useEffect

```ts
React.useEffect(() => {
  (async () => {
    await ...
  )();
}, []);
```

**Comment by undefobj** [comment]
@elorzafe lets track this for next major version

**Comment by dpilch** [comment]
We have published an RFC on our plan for improving TypeScript support in Amplify JS & would love to get your feedback & suggestions!

[RFC: Amplify JS TypeScript Improvements](https://github.com/aws-amplify/amplify-js/issues/11113)

**Comment by chrisbonifacio** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), we'll close this feature request. Please refer to our [announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
