### ISSUE TITLE
Accessing window.localStorage causes SecurityException on ios private browsing

### ISSUE THREAD

**Issue by jfo8000** [aws-amplify/amplify-js#637]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?

- Start with an iphone device, a react.js website created using create react app that uses amplify. 
- Use the built in Safari browser to navigate to the website
- Turn on private mode browsing, (which will cause a security exception whenever someone calls window.localStorage)

The source of the problem appears to be CacheUtils which access window.localStorage in it's default exports. 

I get a crash on aws-amplify/lib/Cache/Utils/CacheUtils.js line 25.

exports.defaultConfig = {
    keyPrefix: 'aws-amplify-cache',
    capacityInBytes: 1048576,
    itemMaxSize: 210000,
    defaultTTL: 259200000,
    defaultPriority: 5,
    warningThreshold: 0.8,
    storage: (typeof window === 'undefined') ? null : window.localStorage  //<< blows up here
};

This is incredibly hard to work around on my end as it blows up the webpack loading of the site. 

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

Bug as the exception means I get a blank page for my website.

What is the expected behavior?

That it loads with warning that local storage is not available and logins might expire?

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

 "dependencies": {
    "aws-amplify": "^0.2.14",
    "aws-amplify-react": "^0.1.38",

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by richardzcode** [comment]
The way iOS safari treats local storage in private mode is a bit different than other browsers. I'll make a fix soon.

**Comment by jfo8000** [comment]
@richardzcode Thanks!! :)
