### ISSUE TITLE
Switching Auth flow Bug?

### ISSUE THREAD

**Issue by KevyVo** [aws-amplify/amplify-js#6372]
**Describe the bug**
I am working on a amplify/cognitio project. I am having trouble getting the user migration function to trigger the Auth flow that should be set to USER_PASSWORD_AUTH but it is stuck on USER_SRP_AUTH. I already enable the check marks in app client to enable these flows. I done a lot of research and the most guide/forums said that the flow should switch automatically.

GitHub Repo: https://github.com/xavierraffin/amplify-identity-broker/tree/kevinenv

**To Reproduce**

1) Go to https://d3phwrax2u7um0.cloudfront.net/
2) Sign in with a fake e-mail and password
3) Open the inspector and navigate to the network tab
4) Go down to the post method (should be highlighted red)
5) Inside the Header tab and under the request payload should be the auth flow information.

**Expected behavior**
The auth flow should be set to USER_PASSWORD_AUTH so the Lambda migration function should be trigger as a result.

**Code Snippet**
Please provide a code snippet or a link to sample code of the issue you are experiencing to help us reproduce the issue. (Be sure to remove any sensitive data)
Migration Function:

 ```
 /* Amplify Params - DO NOT EDIT
     AUTH_BROKERAUTH_USERPOOLID
     AUTH_BROKERAUTH_APPCLIENTID
	 ENV
	 REGION
 Amplify Params - DO NOT EDIT */

 'use strict';
 var AWS = require('aws-sdk');
 var cognitoidentityserviceprovider = new AWS.CognitoIdentityServiceProvider();

 exports.handler = async (event, callback) => {
     console.log("UserPoolID = " + process.env.AUTH_BROKERAUTH_USERPOOLID);
     console.log("AppClientID = " + process.env.AUTH_BROKERAUTH_APPCLIENTID);
     console.log(event);
     var user;

     if ( event.triggerSource == "UserMigration_Authentication" ) {

         // authenticate the user with your existing user directory service
         //user = aws.authenticateUser(event.userName, event.request.password);
         if ( user ) {
             event.response.userAttributes = {
                 "email": user.emailAddress,
                 "email_verified": "true"
             };
             event.response.finalUserStatus = "CONFIRMED";
             event.response.messageAction = "SUPPRESS";
             context.succeed(event);
         }
         else {
             // Return error to Amazon Cognito
             callback("Bad password");
         }
     }
     else if ( event.triggerSource == "UserMigration_ForgotPassword" ) {

         // Lookup the user in your existing user directory service
         user = cognitoidentityserviceprovider.getUser(event.userName);
         console.log(user);
         if ( user ) {
             event.response.userAttributes = {
                 "email": user.emailAddress,
                 // required to enable password-reset code to be sent to user
                 "email_verified": "true"  
             };
             event.response.messageAction = "SUPPRESS";
             context.succeed(event);
         }
         else {
             // Return error to Amazon Cognito
             callback("Bad password");
             console.log("Bad Password")
         }
     }
     else { 
         // Return error to Amazon Cognito
         callback("Bad triggerSource " + event.triggerSource);
     }
     // TODO implement
     const response = {
         statusCode: 200,
         body: JSON.stringify('Hello from Lambda!'),
     };
     return response;
  };
  ```

**Screenshots**
![Screen Shot 2020-07-17 at 9 27 45 AM](https://user-images.githubusercontent.com/53957494/87969458-0a3e5e80-ca77-11ea-8920-dbbfd5c77633.png)
![Screen Shot 2020-07-20 at 10 53 46 AM](https://user-images.githubusercontent.com/53957494/87969602-525d8100-ca77-11ea-8b04-df43d367b1e5.png)
![Screen Shot 2020-07-17 at 9 44 48 AM](https://user-images.githubusercontent.com/53957494/87969474-132f3000-ca77-11ea-8510-d534a6e67327.png)
![Screen Shot 2020-07-17 at 9 45 10 AM](https://user-images.githubusercontent.com/53957494/87969484-175b4d80-ca77-11ea-806c-8ba7497b4d84.png)

**Additional context**

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by manueliglesias** [comment]
Hi @KevyVo 

Can you try setting the `authenticationFlowType` to `'USER_PASSWORD_AUTH'`?

After calling `Amplify.configure(awsExports)`, do:

```js
Amplify.configure({
    Auth: {
        // OPTIONAL - Manually set the authentication flow type. Default is 'USER_SRP_AUTH'
        authenticationFlowType: 'USER_PASSWORD_AUTH',
    }
});
```

**Comment by KevyVo** [comment]
> Hi @KevyVo
> 
> Can you try setting the `authenticationFlowType` to `'USER_PASSWORD_AUTH'`?
> 
> After calling `Amplify.configure(awsExports)`, do:
> 
> ```js
> Amplify.configure({
>     Auth: {
>         // OPTIONAL - Manually set the authentication flow type. Default is 'USER_SRP_AUTH'
>         authenticationFlowType: 'USER_PASSWORD_AUTH',
>     }
> });
> ```

Sure I will try it

**Comment by KevyVo** [comment]
@jordanranz  and @manueliglesias both help me solve this error by adding the piece of code to switch the front. 
```
Amplify.configure({...awsconfig, 
	Auth: {
		// OPTIONAL - Manually set the authentication flow type. Default is 'USER_SRP_AUTH'
		authenticationFlowType: 'USER_PASSWORD_AUTH',
	},
});

```
