### ISSUE TITLE
@aws-amplify/auth - IE11 does not support fetch API

### ISSUE THREAD

**Issue by wataruoguchi** [aws-amplify/amplify-js#6377]
**Describe the bug**
`window.fetch` in the line below isn't supported by IE11. [https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)

https://github.com/aws-amplify/amplify-js/blob/e85640a4e18fa1d55411038fee58919ad73121fa/packages/auth/src/OAuth/OAuth.ts#L166

Thus it causes the following error:

> OAuth - Error handling auth response. ReferrenceError: 'fetch' is undefined

**To Reproduce**

Use `import { Auth } from '@aws-amplify/auth'` with Authorization Code Flow and run it in IE11.

**Expected behavior**
The equivalent of `fetch` should run in IE11. We fixed this issue with https://github.com/github/fetch .

**Version**
`@aws-amplify/auth@^3.3.1`

**Comment by manueliglesias** [comment]
Hi @wataruoguchi 

Thanks for the report, this is similar to #6378 in the sense that both are IE11 related and solvable with polyfills

**Comment by wataruoguchi** [comment]
@manueliglesias Sure! I thought they're different packages / symptoms. Let me leave a comment into the other issue and close this.
