### ISSUE TITLE
API.post returns null

### ISSUE THREAD

**Issue by txnico** [aws-amplify/amplify-js#6390]
Upon upgrading to "aws-amplify": "3.0.20" any call to API.post REST returns null. 

**To Reproduce**
Running managed Expo app with Expo SDK 37
Any call to AWS lambda via API.post.

POST Response: null

**Expected behavior**
A response object to be returned once promise is complete.

**Code Snippet**
```javascript
try {
    const apiName = 'userPreferences';
    const path = "/notifyPref?nType=" + nName + "&nValue=" + nValue;
    const myInit = {
        body: {},
        headers: {'Content-Type': 'application/json'}
    }

    var response = await API.post(apiName,path,myInit);
    console.log("POST Response:", response);
            
    if( !response.match(/Success/) ){
        toastType = 'danger';
        response = "Unable to set preference setting.\n" + response;
    }
            
} catch (err) {
    console.log("Error in userPreference update:",  err);
}
```

**Comment by manueliglesias** [comment]
Hi @txnico 

Are you using your lambda as described [here](https://docs.amplify.aws/lib/restapi/getting-started/q/platform/js#aws-regional-endpoints) ?

**Comment by txnico** [comment]
Hi @manueliglesias 

I was at aws-amplify@1.1.19 with Expo SDK 35. 

I used to have the API exports under: "aws_cloud_logic_custom" block and I've updated them to define them as API.endpoints with no change. 

The lambda code is being executed correctly in AWS and the response as far as I can see in API-gateway logs have the expected response object.

Thanks!

**Comment by manueliglesias** [comment]
Can you share your **redacted** aws-exports.js or API.endpoints config?

**Comment by txnico** [comment]
Sure thing:

`const awsmobile =  {
    "aws_project_region": "xxx",
    "aws_content_delivery_bucket": "xxx",
    "aws_content_delivery_bucket_region": "xxx",
    "aws_content_delivery_url": "xxx",
    "aws_cognito_identity_pool_id": "xxx",
    "aws_cognito_region": "xxx",
    "aws_user_pools_id": "xxx",
    "aws_user_pools_web_client_id": "xxx",
    /*
    "aws_cloud_logic_custom": [
        {
            "name": "deviceListRest",
            "endpoint": "https://xxx.execute-api.xxx.amazonaws.com/Prod",
            "region": "xxx"
        },
        {
            "name": "deviceControl",
            "endpoint": "https://xxx.execute-api.xxx.amazonaws.com/Prod",
            "region": "xxx"
        },
        {
            "name": "sensorData",
            "endpoint": "https://xxx.execute-api.xxx.amazonaws.com/Prod",
            "region": "xxx"
        },
        {
            "name": "Notifications",
            "endpoint": "https://xxx.execute-api.xxx.amazonaws.com/Prod",
            "region": "xxx"
        },
        {
            "name": "userPreferences",
            "endpoint": "https://xxx.execute-api.xxx.amazonaws.com/Prod",
            "region": "xxx"
        },
        {
            "name": "deviceSchedules",
            "endpoint": "https://xxx.execute-api.xxx.amazonaws.com/Prod",
            "region": "xxx
        }
    ], */
    //Get rid of: Unhandled promise rejection: Error: No credentials, applicationId or region
    //https://github.com/aws-amplify/amplify-js/issues/5918
    Analytics: {
        disabled: true
    }, 
    
    API: {
        endpoints: [
            {
                "name": "deviceListRest",
                "endpoint": "https://xxx.execute-api.xxx.amazonaws.com/Prod",
                "region": "xxx"
            },
            {
                "name": "deviceControl",
                "endpoint": "https://xxx.execute-api.xxx.amazonaws.com/Prod",
                "region": "xxx"
            },
            {
                "name": "sensorData",
                "endpoint": "https://xxx.execute-api.xxx.amazonaws.com/Prod",
                "region": "xxx"
            },
            {
                "name": "Notifications",
                "endpoint": "https://xxx.execute-api.xxx.amazonaws.com/Prod",
                "region": "xxx"
            },
            {
                "name": "userPreferences",
                "endpoint": "https://xxx.execute-api.xxx.amazonaws.com/Prod",
                "region": "xxx"
            },
            {
                "name": "deviceSchedules",
                "endpoint": "https://xxx.execute-api.xxx.amazonaws.com/Prod",
                "region": "xxx"
            }
        ]
    }
};

export default awsmobile;
`

**Comment by elorzafe** [comment]
@txnico can you share your package.json and how you are configuring Amplify?

**Comment by txnico** [comment]
@elorzafe - here's my package.json. Regarding the configuration, please see aws-exports I posted above.

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo/vector-icons": "10.1.0",
    "@ptomasroos/react-native-multi-slider": "^2.2.2",
    "@react-native-community/netinfo": "^5.9.4",
    "aws-amplify": "3.0.10",
    "aws-amplify-react-native": "4.1.1",
    "expo": "^37.0.0",
    "expo-constants": "~9.0.0",
    "expo-localization": "~8.1.0",
    "expo-permissions": "~8.1.0",
    "moment": "^2.24.0",
    "native-base": "^2.11.0",
    "react": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-appearance": "~0.3.3",
    "react-native-chart-kit": "4.3.0",
    "react-native-circular-progress": "^1.1.0",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-modal-datetime-picker": "^7.6.0",
    "react-native-reanimated": "~1.7.0",
    "react-native-screens": "^2.9.0",
    "react-native-svg": "11.0.1",
    "react-navigation": "^4.4.0",
    "react-navigation-drawer": "^1.4.0",
    "react-navigation-stack": "^1.7.3",
    "react-navigation-tabs": "^1.2.0",
    "victory-native": "^32.0.1"
  },
  "devDependencies": {
    "babel-preset-expo": "^8.1.0"
  },
  "private": true
}

**Comment by elorzafe** [comment]
@txnico I mean are you doing something like this?


```javascript
import { Amplify, API } from 'aws-amplify';
import awsconfig from './aws-exports';

Amplify.configure(awsconfig);
```

**Comment by txnico** [comment]
@elorzafe: 

import Amplify from '@aws-amplify/core';
import Auth from '@aws-amplify/auth';
import { withAuthenticator } from 'aws-amplify-react-native';
import awsmobile from './aws-exports';

Amplify.configure(awsmobile);

**Comment by elorzafe** [comment]
@txnico where are you importing API?

**Comment by txnico** [comment]
@elorzafe - The imports above are in the main app entry-point whereas the API import happens in child components that execute api calls. I'm importing API as:

import { API } from 'aws-amplify';

**Comment by txnico** [comment]
Any update or suggestions?

**Comment by ashika01** [comment]
@txnico Have you tried to import Amplify from "aws-amplify" rather than core?If not could you give that a try, cleaning your node_modules and package lock files?

Something like this,

import Amplify, {API, Auth} from 'aws-amplify';
import { withAuthenticator } from 'aws-amplify-react-native';
import awsmobile from './aws-exports';

Amplify.configure(awsmobile);

**Comment by txnico** [comment]
Hi @ashika01 - same behavior unfortunately after clearing out node_modules, package lock files and updating imports.

**Comment by ashika01** [comment]
@txnico - I think this maybe related https://github.com/aws-amplify/amplify-js/issues/5971

There is some explanation there. which region are you trying this from?

**Comment by txnico** [comment]
@ashika01 - Thanks for the suggestion. The API in question returns plain-text JSON responses and both #5971 and the referred https://github.com/awslabs/aws-serverless-express/issues/99 discuss mime types and compression.

**Comment by txnico** [comment]
I revisited this issue this week and found out that the issue was being caused by the lack of serialization in the body of the response object within my lambda function. It must have been a change in AWS API since previous API.post calls with the unedited lambda functions worked previously for months.
