### ISSUE TITLE
Clarification: Can I able to login with Facebook in aws cognito (Any documentaion) (Mobile app => react-native)

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#6394]
I am planning to add login features with social logins

For e.g) FACEBOOK.

Can i able to authenticate the app using instagram in aws cognito.

**Comment by mauerbac** [comment]
Answered in this issue https://github.com/aws-amplify/amplify-js/issues/6393

**Comment by nihp** [comment]
@mauerbac Kindly reopen the ticket #6393. It is related to instagram login. 

For facebook, it has support for login. https://docs.amplify.aws/lib/auth/social/q/platform/js#setup-frontend

**Comment by mauerbac** [comment]
Done

**Comment by nihp** [comment]
Thanks @mauerbac
