### ISSUE TITLE
ExpiredToken Error after 1 hr during uploading large file

### ISSUE THREAD

**Issue by patelvarun** [aws-amplify/amplify-js#6408]
We use AWS amplify JS library in our React - UI with Cognito auth role to upload files. we are storing session details (like token) in react state to access in the upload page. 

when we upload a bigger file (in GBs like above 5 GB), it’s failing with error  - "AWSS3Provider - error uploading ExpiredToken: The provided token has expired while uploading large file".

we did some research on it. we found that we have default accessToken time 1 hr in Cognito.  the aws-amplify library will automatically handle refreshing access token (using refreshToken) when we do some action on the page & it will refresh the page. it is working fine. But in case of bigger file upload, the token is getting expired after 1 hr since we are not doing any action on page while uploading so it won't get refresh token & There is no option to increase expire time in Cognito. 
If I manually get refresh token and set to react state by calling refreshSession method before refreshToken expire (before 1 hr end) then the page is refresh because of status change. so I lost my uploaded files. 

Below are my questions
1) How we can increase refresh token time? 
2) Is there any option to increase it then, How we can get refresh token & pass it to uploading file once token expire?
3) What is the best way to handle this?

**Comment by patelvarun** [comment]
Hi, Can anyone help me out on this? Let me know if you require more information on this. 
Thanks in advance.

**Comment by patelvarun** [comment]
Is this issue being considered or is it feature-request?

**Comment by sammartinez** [comment]
@patelvarun Thanks for this feedback, there is a similar feature request open as I have related. We will take this into consideration for our project.

**Comment by patelvarun** [comment]
Thanks for considering this as a feature request.

**Comment by iartemiev** [comment]
This feature has been released as part of aws-amplify@3.0.23 / @aws-amplify/storage@3.2.12

**Comment by patelvarun** [comment]
@iartemiev - I appreciate you! Thanks for the support.
