### ISSUE TITLE
Can't query many-to-many relations with DataStore

### ISSUE THREAD

**Issue by Jahans3** [aws-amplify/amplify-js#6412]
**Describe the bug**
As described in title. The docs show us how to create and save mtm relations but using this method it seems we can't query them.

DataStore removes the joining ID fields on the linking schema so it seems impossible to query this using DataStore?

**To Reproduce**
Follow docs on mtm relations: 

**Expected behavior**
I should be able to query my data

**Comment by Jahans3** [comment]
Closing not because I found a solution but because I'm removing DataStore from my project, too many limitations in it's current form

**Comment by undefobj** [comment]
Can you give more details on what you're looking for here? The docs show how to do queries with relations however without a code example it's difficult to answer.

**Comment by Jahans3** [comment]
@undefobj 

This:

```graphql
type JourneyUsersBridge @model(queries: null)
  @key(name: "JourneyUsers", fields: ["journeyId", "userId"])
  @key(name: "UserJourneys", fields: ["userId", "journeyId"]) {
  id: ID!
  userId: ID!
  journeyId: ID!
  user: User! @connection(fields: ["userId"])
  journey: Journey! @connection(fields: ["journeyId"])
}
```

Generated this:

```typescript
export declare class JourneyUsersBridge {
  readonly id: string;
  readonly user: User;
  readonly journey: Journey;
  constructor(init: ModelInit<JourneyUsersBridge>);
  static copyOf(source: JourneyUsersBridge, mutator: (draft: MutableModel<JourneyUsersBridge>) => MutableModel<JourneyUsersBridge> | void): JourneyUsersBridge;
}
```

Which meant I could not query the relationship efficiently using `DataStore.query` since the `userId` and `journeyId` fields were omitted from the model.

This won't work since `JourneyUsersBridge.journeyId` does not exist:

```javascript
DataStore.query(JourneyUsersBridge, j => r.journeyId('eq', journeyId);
```

And I can't realistically expect a user to fetch every single instance of a model and then filter those in the client, as suggested in the one-to-many section of the docs. It's just not scalable.

I'll be using `API.graphql` and a caching library instead of DataStore since we don't have to go through extra steps that run counter to the graphql model to piece together related schema.

It was explained to me here (https://github.com/aws-amplify/docs/issues/2145) that there are currently some limitations in the library but I do think the handling of relationships and the limitations DataStore JS impose on schema design and querying make it currently unfeasible in a project of even moderate scale, especially what essentially boils down to a paid product (I know it's technically open source, but it funnels people into paying for AWS services).

If there's anything I've missed I'd be interested to find out where I was going wrong.

**Comment by undefobj** [comment]
Thanks for the details. I think what you're looking for is lazy loading of the queries which we are tracking here: https://github.com/aws-amplify/amplify-js/issues/5054
