### ISSUE TITLE
*.csv import in all my cognito user pools is broken

### ISSUE THREAD

**Issue by Billybobbonnet** [aws-amplify/amplify-js#6416]
**Describe the bug**
I cannot import csv in any of my cognito user pools. I open the "create import job" modal on the cognito user pool page, set a name, an IAM role for the import, and a file. When I click on the submit button "create job" it switches to "creating job..." and get stuck. 

When I reload the page and run the job, I get an error:

> No csv file was uploaded for import-9sHxosU7BP (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: PreconditionNotMetException; Request ID: d6319b3b-22c7-4bf5-bdb9-b237deb552e7; Proxy: null)

Note that I imported successfully users many times in the last month and it started showing this behavior about 2 weeks ago. It is very problematic to me as it affects the 2 user pools I have (prod and dev) and as a consequence I cannot update my production websites.

**To Reproduce**
Try importing a csv file from cognito web ui.

**Screenshots**
Browser (Firefox) console (let me know if this should be removed regarding privacy of the data leaked in the urls): 
![88525353-c4474480-cffa-11ea-8afa-3274beb69217](https://user-images.githubusercontent.com/8236816/88526196-ec837300-cffb-11ea-9137-f2a46d07194e.png)

Faulty cognito UI:
![image](https://user-images.githubusercontent.com/8236816/88525406-d88b4180-cffa-11ea-80b1-4cebb6cd0e63.png)

**Comment by ashika01** [comment]
@Billybobbonnet This looks like cognito service issue. Have you asked about this in [aws forum.](https://forums.aws.amazon.com/forum.jspa?forumID=173) I would suggest you ask them.

I am closing this issue since I dont see any relation to Amplify JS. If there is anything from our end, please feel free to ping here and I can re open this issue.
