### ISSUE TITLE
Password reset form (for FORCE_CHANGE_PASSWORD Cognito) is broken in Chrome on Ipad

### ISSUE THREAD

**Issue by vomc** [aws-amplify/amplify-js#6417]
It appears that whenever a user attempts to focus on the input field in which they are to enter their new and permanent password, the form resets back to the login form without letting the user complete this action.

To reproduce:

1. Create a user in cognito, give them a temp password and notify them that their account has been set up. User should now be in FORCE_CHANGE_PASSWORD status in cognito
2. Receive the email and open the app that you're trying to make an account for on an iPad
3. You will be asked to login and then to set a new password
4. Focus on the input field and you will be reset to the main login form

**Expected behavior**
I would expect that a user can enter a new password and complete the action

**Code Snippet**
Just using the default `withAuthenticator` function in React

**Screenshots**
I recorded this as it is better in video. You see me entering my test password here and at second 20, the form goes to the 'enter new password' section. As you can see the second I focus it goes back to the login

Video link: https://www.dropbox.com/s/n3m32o5ebp1vm7d/cognito_ipad_chrome.mov?dl=0

**What is Configured?**
```js
...
"aws-amplify": "^1.1.22",
"aws-amplify-react": "^2.3.2",
"react": "^16.12.0",
```

AWS exports contains
```js
region: "eu-central-1",

Not sure that I should paste the ID of our user pool here... but can in a private msg

```

Env info
```js
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages

// note this issue is on ipad, but for my system i am using

  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v10.15.3/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 84.0.4147.89
    Chrome Canary: 86.0.4208.0
    Firefox: 78.0.2
    Safari: 13.1
  npmGlobalPackages:
    0x: 4.9.1
    babel-cli: 6.26.0
    k6: 0.0.0
    nodemon: 1.19.4
    npm: 6.4.1
    typescript: 3.9.5
    yarn: 1.22.4
```

Device in question is an iPad 7th gen, iOS 13.1.1

**Comment by vomc** [comment]
Note this works on Safari but not in Chrome

**Comment by ashika01** [comment]
@vomc I see you are using `aws-amplify-react`. This part of the library is in maintence mode. We have launched, `@aws-amplify/ui-react` which is newer react components. I would suggest you use that and report bug in that case.

Could you try the newer components to see if this issue exists? https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#withauthenticator

**Comment by vomc** [comment]
@ashika01 We will take a look to see how hard it is to switch everything over. 

I am not sure I understand what you mean by maintenance mode though: no support for google chrome for such a critical feature as the login???

**Comment by tannerabread** [comment]
Closing this as the `aws-amplify-react` package is now officially deprecated. If you have any concerns with the new UI components and are experiencing the same issue, please open a new issue in the [UI repo](https://github.com/aws-amplify/amplify-ui). Check out the new documentation [here](https://ui.docs.amplify.aws/react/connected-components/authenticator)
