### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by adobayua-rpay** [aws-amplify/amplify-js#6428]
Sometimes it works, most times it doesn't and throws this error.

**Comment by ashika01** [comment]
@adobayua-rpay Could you please fill out issue template or explain in depth where you are seeing this issue.

**Comment by adobayua-rpay** [comment]
Apologies! I didnt post the solution here but it is more on the client side than you guys. It is an error that happens with large file sizes. To fix the issue simply increase your space size in your package.json.
For me it was adding this 
    "start": "react-app-rewired --max_old_space_size=4096 start",
    "build": "react-app-rewired  --max_old_space_size=4096 build",
Yours might look a little different, for example your start may be npm start so you would replace that with the react-app-rewired.
Heres the stackoverflow link with a similar solution - https://stackoverflow.com/questions/44046366/increase-javascript-heap-size-in-create-react-app-project
