### ISSUE TITLE
Cognito session disappears on page refresh

### ISSUE THREAD

**Issue by Anton2501** [aws-amplify/amplify-js#6434]
Hello
I'm using aws-amplify: "^2.2.6" in my React project. I implemented Cognito authentication via my custom UI, so to authenticate user, I'm using Amplify methods. 

The Problem:
After successful signing-in user, if I just refresh the page (one or more times), I see that Cognito-related data, saved in LocalStorage just disappears and I have no idea why. So authenticated user becomes unauthenticated and I don't know what to do.

I did the configuration manually, but if there was something wrong, the authentication would not work:
const config = {
    Auth: {
        region: 'us-east-1',
        userPoolId: xxxxxxx,
        userPoolWebClientId: xxxxxxxx,
        oauth: {
            domain: domain,
            scope: ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
            redirectSignIn: redirectUrl,
            redirectSignOut: redirectUrl,
            responseType: 'code'
        },
    },
}

Here is a couple of code snippets also: https://snipit.io/lists/12150/38345

I think I haven't done anything complicated, and everything works as it should, except for the page refresh. I will be glad for any help, thank you in advance for your time.

**Comment by ashika01** [comment]
@Anton2501 Does the problem also occur with the latest version?! Could you please verify that.

**Comment by Anton2501** [comment]
I figured out the problem, it's not cognito's fault. Thank you for your time

**Comment by jaivinodha** [comment]
> I figured out the problem, it's not cognito's fault. Thank you for your time

Could you please share the solution ? im also facing the same problem

**Comment by Anton2501** [comment]
> Could you please share the solution ? im also facing the same problem

In my case, I've had cleaning LocalStorage in another component, so data, related to Cognito, was cleaning up after every page refreshing
