### ISSUE TITLE
Fetching with predicates ignores models auth rules (DataStore)

### ISSUE THREAD

**Issue by alexandprivate** [aws-amplify/amplify-js#6435]
**Describe the bug**
Using predicates with DataStore, auth rules seem to be totally ignored if you are setting a model only accessible by the owner, and the query is call using predicates the auth owner rules is ignored and every item from the DB that fulfills the predicate logic and all items that satisfy the predicates are returned even those owned by another user.

**To Reproduce**

1. Create a model with simple owner base auth rule Ex. `type Item @model @auth(rules: [{ allow: owner }]) {...}`
2. Generate your model and deploy your schema (pm run amplify-modelgen and  amplify push)
3.  Create Items from 2 different users
4. Now query those the Items using predicates Ex. ` await DataStore.query(Property, (c) => c.available("eq", false))`
5. The response will return all the Items with key "available" false, even those from created by the other user

**Expected behavior**
Predicates should not violate models auth rules, returning only the filtered owner models

**Comment by manueliglesias** [comment]
Hi @alexandprivate 

Every operation you do on the DataStore happens locally first. What you are seeing is that your local data still has data from another user.

Here the recomendation is to clear the DataStore when a user signs out/in with:

```js
DataStore.clear();
```

**Comment by alexandprivate** [comment]
Hi there @manueliglesias thats exactly what's happening, any recommendation to achieve this using withAuthenticator ?

**Comment by alexandprivate** [comment]
Hi there @manueliglesias I'm using a workaround to clear DataStore data in the browser with the latest version of withAuthenticator/@aws-amplify/ui-react just is not the fancies but it works.

1. Avoid using the AmplifySingOut component to log out
2. Use Auth API to sign out, clear datastore and refresh the window later

`
// IMPORTS
import { Auth, DataStore } from "aws-amplify"

// METHOD
const handleSignOut = async () => {
        await Auth.signOut()
        await DataStore.clear()
        history.push("/")
        window.location.reload()
    }

// BUTTON
 <button onClick={handleSignOut} > Sign Out </button>                  
`

You need to refresh the window since the latest version of withAuthenticator does not listen to the Auth.signOut()
Hope this helps as a temporary solution, ideally, we should either pass the datasore.clear method to the AmplifySignOut component via props or like in older versions make the withAuthenticator component listen the auth.signOut

**Comment by ashika01** [comment]
@alexandprivate i think you maybe able to use `onAuthUIStateChange` to do this on AuthState.SignedOut. Have you tried using this function in your `withAuthenticator`?

**Comment by alexandprivate** [comment]
Hi there @ashika01 certainly not, let take a look at it.

**Comment by alexandprivate** [comment]
Hi there @ashika01 it works like a charm! I'm leaving a hint here just in case someone needs to use it

![carbon (1)](https://user-images.githubusercontent.com/7695887/88868027-b1886780-d1d4-11ea-9066-613d94144497.png)

@manueliglesias this could be closed if you wanted.
