### ISSUE TITLE
Amplify w/Federated Identities that are not list in Amplify but listed in AWS?

### ISSUE THREAD

**Issue by filburt-turle** [aws-amplify/amplify-js#6438]
Hi,

I have an application that needs to use a federated identity that is not included in (google, facebook, amazon).

https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-integrating-3rd-party-saml-providers.html

Either Auth0 or PingIdentity.

I have them working separately when I setup cognito without having to use amplify, but I'm wondering how those settings translate into something amplify would be able to pick up and the hosted UI that comes with amplify would work. Does anyone have any guidance for this?

Any help mixing in providers that don't fit the (google, facebook, amazon) mold would be great. If you could even provide examples that would help as well.

Thank you.

**Comment by ashika01** [comment]
@filburt-turle we are working on this right now. This is the issue we are tracking, https://github.com/aws-amplify/amplify-js/issues/5860 the information on. Should be having a doc update soon on that.

**Comment by div5yesh** [comment]
@filburt-turle Please refer: [[Auth0](https://aws.amazon.com/premiumsupport/knowledge-center/auth0-saml-cognito-user-pool/), [Okta](https://aws.amazon.com/premiumsupport/knowledge-center/cognito-okta-saml-identity-provider/)]. 
When you add Auth to Amplify project with any of the Default Configuration, Amplify will create a user pool, add App client and a domain name. So you can skip those steps.

Then add adding the Hosted UI to the app:
`Auth.federatedSignIn()`
or with custom UI:
`Auth.federatedSignIn({provider: 'Auth0'})`

**Comment by filburt-turle** [comment]
@div5yesh I'm not trying to create a cognito resource, I'm just trying to tie in my already existing cognito w/amplify, this is more of a configuring the `aws-exports.js` correctly for federated signin w/custom auth

@ashika01 I'm primarily interested in PingIdentity -- if there's a way to get that provider working w/Amplify that would be great.

**Comment by ashika01** [comment]
@filburt-turle To answer first bit, have you check in `Amplify CLI` for a way to pull in existing resources or you can always manually configure using `Amplify.configure`. This might help - https://docs.amplify.aws/lib/auth/start/q/platform/js#re-use-existing-authentication-resource

Are you running into any issue with pingIdentity? If its similar to Auth0 or Okta, you might be able to use the links @div5yesh linked to get an idea.

**Comment by filburt-turle** [comment]
@ashika01 I was not able to get PingFed working w/Amplify Hosted UI. I had to separately authenticate outside of the Amplify framework and just pass in a JWT token into configuration -- seems like Amplify is pretty limited when you use anything other than the three they have listed in the CLI. 

Thanks for you help, I was able to get to some resolution for the time being.
