### ISSUE TITLE
Federated user fails to update mutable attributes with a 400 response: "Access Token does not have required scopes"

### ISSUE THREAD

**Issue by pedramp20** [aws-amplify/amplify-js#6444]
**Describe the bug**
Using  "aws-amplify": "3.0.22", when a federated user from an external identity provider (e.g. Google) tries to update a mutable (in my case custom) attribute, it gets a 400 error as follows:

`code: "NotAuthorizedException"
message: "Access Token does not have required scopes"
name: "NotAuthorizedException"`

Please note that an internal user can successfully update the attribute and hence, all the scopes on the client and Cognito sides are set correctly.

**To Reproduce**

1. Setup an external identity provider e.g. Google and enable it on the app client settings
2. Configure right readable and writable attributes
3. Use the following code to update an attribute

` const user = await Auth.currentAuthenticatedUser();
    const result = await Auth.updateUserAttributes(user, { 'custom:role':'myRole'});`

**Expected behavior**
Be able to update a mutable attribute which is not mapped from the external identity provider

**Observed behavior**
400 response code:

` https://cognito-idp.ap-southeast-2.amazonaws.com/ 400
(anonymous) @ VM284:1
request @ Client.js:101
updateAttributes @ CognitoUser.js:1011
(anonymous) @ Auth.ts:1035
Promise.then (async)
(anonymous) @ Auth.ts:1025
AuthClass.updateUserAttributes @ Auth.ts:1024
(anonymous) @ authSlice.js:214
async function (async)
(anonymous) @ authSlice.js:213
(anonymous) @ index.js:8
(anonymous) @ immutableStateInvariantMiddleware.ts:262
dispatch @ VM287:1
handleSetRole @ Role.js:23
onClick @ Role.js:55
onClick @ Button.js:52
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:306
executeDispatch @ react-dom.development.js:389
executeDispatchesInOrder @ react-dom.development.js:411
executeDispatchesAndRelease @ react-dom.development.js:3278
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:3287
forEachAccumulated @ react-dom.development.js:3259
runEventsInBatch @ react-dom.development.js:3304
runExtractedPluginEventsInBatch @ react-dom.development.js:3514
handleTopLevel @ react-dom.development.js:3558
batchedEventUpdates$1 @ react-dom.development.js:21871
batchedEventUpdates @ react-dom.development.js:795
dispatchEventForLegacyPluginEventSystem @ react-dom.development.js:3568
attemptToDispatchEvent @ react-dom.development.js:4267
dispatchEvent @ react-dom.development.js:4189
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
discreteUpdates$1 @ react-dom.development.js:21887
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
authSlice.js:220 {code: "NotAuthorizedException", name: "NotAuthorizedException", message: "Access Token does not have required scopes"}`

**What is Configured?**
:
   ```
   {
    Auth: {
        identityPoolId: 'XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab',
        region: 'XX-XXXX-X',
        identityPoolRegion: 'XX-XXXX-X',
        userPoolId: 'XX-XXXX-X_abcd1234',
        userPoolWebClientId: 'a1b2c3d4e5f6g7h8i9j0k1l2m3',
        mandatorySignIn: false,
        oauth: {
            domain: 'your_cognito_domain',
            scope: ['phone', 'email', 'profile', 'openid'],
            redirectSignIn: 'http://localhost:3000/',
            redirectSignOut: 'http://localhost:3000/',
            responseType: 'code' 
           }
       }
   }
   ```

**Comment by ashika01** [comment]
@pedramp20 Could you open your aws console and double check if these scopes are enabled in `App client settings`. Also, see in google provider if these scopes are setup?!

**Comment by pedramp20** [comment]
They are and as I mentioned in my report, internal users can set them just fine.  I am not sure what you mean by see in the google provider if these scopes are setup, as the only thing needs to be setup is client id and secret and attribute mapping. This attribute is not mapped from the external provider.

**Comment by leosoaivan** [comment]
@pedramp20 might this be what you are looking?

> The aws.cognito.signin.user.admin scope grants access to Amazon Cognito User Pool API operations that require access tokens, such as UpdateUserAttributes and VerifyUserAttribute.

It sounds as though you may be missing the `aws.cognito.signin.user.admin` in your app client settings.

**Comment by ta1bbty** [comment]
@leosoaivan 
I've these set in my aws pool.
[![Oauth Scope][2]][2]

I have been working with AWS cognito and trying to update the `preferred_username` attribute.

I tried the `Auth.updateUserAttributes` call but in vain.

Here's the whole code : 
```js
Auth.updateUserAttributes(user, {
    preferred_username: "new_username",
  })
    .then((data) => {
      setUser(data);
      console.log("updateUserAttributes succ", data);
    })
    .catch((error) => {
      console.log("updateUserAttributes err", error);
    });
})
.catch((r) => console.log("getUser err", r));
```

I have also checked the **app client settings** for read/write permission on the `preferred_username` attribute.
[![Read/Write attribute settings][1]][1]

Still I get this error : 
```js
updateUserAttributes err Object {
  "code": "NotAuthorizedException",
  "message": "Access Token does not have required scopes",
  "name": "NotAuthorizedException",
}
```

I tried on other attributes as well, like `website` but I get the same response.
It seems user from external identity providers can't update their attributes [here](https://github.com/aws-amplify/amplify-js/issues/5921).


Thanks.

Can someone confirm or deny this ?


  [1]: https://i.stack.imgur.com/3ZdjQ.png
  [2]: https://i.stack.imgur.com/fSBRj.png

**Comment by NicolasESchneider** [comment]
Im having similar issues but just with retrieving user Attributes from my user pool.
calling Auth.userAttributes gives me the same error
```
{
  code: "NotAuthorizedException"
  message: "Access Token does not have required scopes"
  name: "NotAuthorizedException"
}
```

**Comment by carloliwanag** [comment]
Hi. I too is having the same issue. I hope this gets resolve.

**Comment by DeniferSantiago** [comment]
The same issue and no solution appears yet

**Comment by DeniferSantiago** [comment]
I found a solution, I was hopeful on the @leosoaivan  comment but it didn't work for me.

I became agnostic to cognito attributes as federated entity users couldn't set them. Two weeks later I saw the need to update the auth module amplify update auth in the process it allowed me to choose the scope (something that did not appear when adding Facebook and Google as entities for my users) among which is aws.cognito .signin.user.admin I saw that it was not selected, as I had selected it like @ta1bbty in cognito and apparently it was not working. After that I tried setting the gender attribute of a user started with google and it worked.

The test was done after logging into a user with Google. Previously I wanted to update some attributes just after creating the user with Facebook or Google and it returned the error `"Access Token does not have required scopes"`, I will try to test it in that scenario to confirm that my problem has been solved. I don't know if any update has helped me or the solution was there before

**Comment by chrisbonifacio** [comment]
If someone else experiencing this issue can also try running 'amplify update auth' and add the scopes through the cli, please let us know if this fixes the issue for you.

**Comment by DeniferSantiago** [comment]
@chrisbonifacio  I already did the tests and I was able to make it work.

In testing I noticed that I still couldn't set custom attributes. So I did another test, went to cognito and turned on reading and writing of my custom attribute but this didn't work. Then I went to the parameters.json file of the Auth module and manually added my attribute in the keys "userpoolClientWriteAttributes" and "userpoolClientReadAttributes" after this it worked correctly.

Now we can update the attributes of users from external providers!

**Comment by DeniferSantiago** [comment]
I will discuss some issues that I have had while working and testing this.

Every time I updated the Auth module, I broke my authentication with Facebook and Google, because it deconfigured the "app client settings" so I had to modify it directly from cognito:

![image](https://user-images.githubusercontent.com/41799285/118351294-2725b000-b529-11eb-9b6e-b20b2da3ea2f.png)

 In addition, `"LambdaConfig"` was always added under `"UserPool"` in the file `{name}-cloudformation-template.json`, which generated an error when doing `amplify push`.

Although I think it is because today I also tried to implement a lambda trigger for pre-signup but I had to remove it because of this: #5522 

I take this opportunity to ask if it is normal that the client of my React Native application in "Cognito App Clients" does not have a secret key.

I don't remember if I had it before and if while trying today I somehow lost it, but for now everything is fine in the app.

**Comment by DeniferSantiago** [comment]
In summary the solution is to add _"aws.cognito.signin.user.admin"_ with `"amplify update auth"` selecting _"Walkthrough all the auth configurations"_ and in case of having custom attributes add them manually to `"parameters.json"` in the Auth module

**Comment by chrisbonifacio** [comment]
Closing this for now as we seem to have a working solution and have not heard back from the original poster. Thank you, @DeniferSantiago for pointing out this necessary step. 

If anyone else tries this and it does not work for you, please open a new issue with the details of your particular project configuration.

**Comment by taouichaimaa** [comment]
> amplify update auth

I'm having the same problem, however, won't this overwrite any configuration I have already set? for example, I have Apple, Facebook and Google already setup and their respective generated userpool groups, making this update requires me to re-enter all of that configuration again and it would create other pools for these same providers, won't it?
