### ISSUE TITLE
Typo ProvidertOptions -> ProvidersOptions in @aws-amplify/pubsub ?

### ISSUE THREAD

**Issue by tarunama** [aws-amplify/amplify-js#6445]
**Describe the bug**
ProvidertOptions -> ProvidersOptions or ProviderOptions ?

**To Reproduce**
https://github.com/aws-amplify/amplify-js/blob/e85640a4e18fa1d55411038fee58919ad73121fa/packages/pubsub/src/types/Provider.ts#L14

**Expected behavior**
confirm that valid variable name.

**Comment by ashika01** [comment]
It is a typo for sure. But it is a consistent typo used all over properly. I will close this issue. But if you are interested in fixing the typo and testing it, please feel free to open a PR 👍
