### ISSUE TITLE
DataStore - Omitting an optional field from a model object results in error on save

### ISSUE THREAD

**Issue by danrivett** [aws-amplify/amplify-js#6453]
**Describe the bug**
Given a GraphQL schema which defines a model type with an optional (string) value, if a model instance is saved without defining that value (it's optional after all), it will fail; definging a `null` value for the optional value succeeds.

**To Reproduce**
This was recently demonstrated to us when we had a graphql schema like the following:

```graphql
type Movie @model {
  id: ID!
  name: String!
  description: String
}
```

When calling something like:

```ts
await DataStore.save(
  new Movie({
    name: "Dumb and Dumber",
  })
);
```

The local DataStore appears to be updated but I see the following _error_ logged as a _warning_:

```
[WARN] 06:03.591 DataStore - failed to execute errorHandler, [Error: Field description should be of type string, undefined received. undefined]
```

**Expected behavior**
All optional fields should be able to be omitted when saved and it should succeed without populating that value. Alternatively, it can also be explicitly specified as `undefined` or `null` which is particularly useful on updates to clear out a field.

**Investigation**
A quick search of the codebase seems to show the culprit of this error [here](https://github.com/aws-amplify/amplify-js/blob/%40aws-amplify/datastore%402.2.8/packages/datastore/src/datastore/datastore.ts#L257).

Perhaps the following line can simply be changed from:

```diff
- } else if (typeof v !== jsType && v !== null) {
+ } else if (typeof v !== jsType && v != null) {
```

(e.g. it avoid strict equality on the `null` check to also include `undefined` and avoid erroring in that case?)

Earlier up in `validateModelFields()` it is already checking if the field is required:

```ts
if (isRequired && (v === null || v === undefined)) {
  throw new Error(`Field ${name} is required`);
}
```

So my suggested change should be sufficient? I don't know if there are other side-effects of this change that are undesired, or if the original exclusion of `undefined` was intentional, but hopefully not?

**Amplify Version**
2.2.8

**Comment by amhinson** [comment]
@danrivett Would you be able to try with the latest version of Amplify? I tested out the example you provided, but everything seemed to work as expected with `aws-amplify@3.0.22`.

**Comment by danrivett** [comment]
@amhinson thanks for taking a look.

The dependency we use is `@aws-amplify/datastore` so what version of that package would `aws-amplify@3.0.22` correspond to?

I'm not sure I understand your second question, we definitely did call `DataStore.save()` and it's updated locally, but not in DynamoDB.

**Comment by amhinson** [comment]
Ah ok so you're just using `@aws-amplify/datstore@2.2.8`, right? That is the latest, so you can disregard my first question.

For the second question, I'm wondering if this `Movie` model was originally created via `amplify-modelgen` and pushed via `amplify push`, and then additional properties (i.e. `description`) were added but not pushed.

Were you able to replicate this behavior by creating a brand new app with DataStore?

**Comment by danrivett** [comment]
The GraphQL schema above is an example and our real schema is more complicated and so I used an example.

I will create an example app with this schema later (hopefully today) and verify the behaviour in that app and send you a link to it.

Regarding `amplify-modegen` question, we use `amplify codegen models` to generate our TypeScript bindings from our GraphQL schema that we manually maintain.

**Comment by danrivett** [comment]
Just an update on this, I created a sample application with this schema above, and I haven't been able to recreate the problem.

I haven't been able to spend much time on this sample application to understand why, as we have too much work on the real app currently, so I'll close this off for now, and reopen it if I can provide a recreatable example.

**Comment by wei** [comment]
For the record, I believe #7044 fixes this issue which has been merged and can be used with `aws-amplify@unstable` for now.

**Comment by danrivett** [comment]
Brilliant, thanks @wei I look forward to checking it out once it's released on a stable version. Thanks for fixing this!
