### ISSUE TITLE
AuthClass - AuthError: ConfirmSignUp Confirmation code cannot be empty

### ISSUE THREAD

**Issue by DemogorGod** [aws-amplify/amplify-js#6457]
I have verified multiple times that the inputs are not empty using console log in many locations, including right before submission. However, when I go to confirm sign up, I receive the following error:
"48:04.107 AuthError - Confirmation code cannot be empty" 

**Expected behavior**
I expect the confirmSignUp to work, and be able to navigate to the sign in view. 

**Screenshots**
![image](https://user-images.githubusercontent.com/63758598/88952110-f8be3900-d264-11ea-936c-971e87e285bf.png)
![image](https://user-images.githubusercontent.com/63758598/88952165-0a074580-d265-11ea-9358-02c5f27e9b5a.png)
![image](https://user-images.githubusercontent.com/63758598/88952541-974a9a00-d265-11ea-83b6-a4d486661331.png)

<details>
  <summary><strong>Environment</strong></summary>

```
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
    Memory: 930.32 MB / 7.81 GB
  Binaries:
    Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.105
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    @aws-amplify/ui-react: ^0.2.12 => 0.2.12
    @testing-library/jest-dom: ^4.2.4 => 4.2.4
    @testing-library/react: ^9.5.0 => 9.5.0
    @testing-library/user-event: ^7.2.1 => 7.2.1
    aws-amplify: ^3.0.21 => 3.0.21
    aws-amplify-react: ^4.1.20 => 4.1.20
    react: ^16.13.1 => 16.13.1
    react-dom: ^16.13.1 => 16.13.1
    react-router: ^5.2.0 => 5.2.0
    react-router-dom: ^5.2.0 => 5.2.0
    react-scripts: 3.4.1 => 3.4.1
  npmGlobalPackages:
    @aws-amplify/cli: 4.24.0
    @vue/cli-init: 4.4.1
    @vue/cli: 4.4.1
    amplify-cli: 1.0.0
    aws-amplify: 3.0.16
    create-react-app: 3.4.1
    figma2react: 0.1.6
    npm-check-updates: 6.0.1

```

**Comment by ashika01** [comment]
@DemogorGod - I think your problem might not be related to amplify. Couple of things, that could help you
- Try changing `onChange` to `onInput` I think that is what is causing the weirdness.
- we have our own ui components, you can either make use of it or can see the source code to help to unblock.

Let us know how it goes.

**Comment by DemogorGod** [comment]
I just figured it out the problem was due to the way i am inputting my username and code. 
![image](https://user-images.githubusercontent.com/63758598/88954105-dc6fcb80-d267-11ea-80f1-bf7640d475c8.png)

**Comment by ashika01** [comment]
Cool 👍 I will go ahead and close this issue. Feel free to ping if you still have some prob, I can reopen this issue.
