### ISSUE TITLE
Request: Support or Documentation for using pubsub with Cognito groups

### ISSUE THREAD

**Issue by atyshka** [aws-amplify/amplify-js#6465]
**Is your feature request related to a problem? Please describe.**
When integrating sensitive IoT data into my web app, I don't want any user of the app to be able to access it, I would like to restrict access using cognito groups. How can I achieve this? I have current tried adding an all-wildcard policy on the group, but this isn't working. Attempting to subscribe leads to an error code 8: socket closed error. I know something is incorrect with the IAM policies, but I'm unsure.

**Describe the solution you'd like**
Support for user groups as a form of permissions for IoT. If this already is possible, then documentation on how to achieve this.

Here is my user-pool-group-precedence.json that adds the inline policy:
```
[
  {
    "groupName": "TrustedUsers",
    "precedence": 1,
    "customPolicies": [
      {
        "PolicyName": "admin-group-policy",
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "statement1",
              "Effect": "Allow",
              "Action": ["iot:*"],
              "Resource": ["*"]
            }
          ]
        }
      }
    ]
  },
  {
    "groupName": "UntrustedUsers",
    "precedence": 2
  }
]
```
Other than that, I haven't made the single-user changes in the pubsub tutorial, as I want to configure on a group basis rather then per user.

**Comment by ashika01** [comment]
@atyshka Have you tried looking into [AppSync service](https://docs.aws.amazon.com/appsync/latest/devguide/welcome.html)? They handle a lot the use cases you are trying to solve. You can use [amplify to interact with the appsync service.](https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/js)
