### ISSUE TITLE
Allow Auth.federatedSign() to take custom attributes

### ISSUE THREAD

**Issue by leosoaivan** [aws-amplify/amplify-js#6466]
**Is your feature request related to a problem? Please describe.**
I'd like to store a user's sign up location from the app/client (something like `window.location.href`) in my database. With `Auth.signUp()`, I can do this by setting a custom attribute and reading that attribute in a post-Confirmation trigger.

**Describe the solution you'd like**
Allow Auth.federatedSign() to take custom attributes as well.

**Describe alternatives you've considered**
I've tried setting data in local/sessionStorage and firing a graphQL call on the relevant Hub auth events. It works, but being able to do it within the Auth class would be nice. 

**Additional context**
N/A

**Comment by klaytonfaria** [comment]
Yep, I agree with @leosoaivan, I think that is **very nice** to have a backward compatibility between the `Auth.signUp()` and `Auth.federatedSign()` having support to the regular UserPool **user attributes** and **custom attributes** as well.

**Comment by tannerabread** [comment]
Hi @leosoaivan and @klaytonfaria 
This should be possible, I haven't done it with `window.location.href` but I don't see why that wouldn't work.

I have made an account in my user pool with federatedSignIn and then added custom attributes to that account with `updateUserAttributes` as found [here in the docs](https://docs.amplify.aws/lib/auth/manageusers/q/platform/js/#managing-user-attributes). This is also possible with custom attributes

Please let me know if I'm misunderstanding what you are trying to do

**Comment by tannerabread** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and are in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
