### ISSUE TITLE
Social Sign In - Facebook App won't go live with recommended Site URL

### ISSUE THREAD

**Issue by zacharywenner** [aws-amplify/amplify-js#6467]
**Describe the bug**  
I have the social sign in configured and working correctly on my React Native app.

I followed these docs:  
https://docs.amplify.aws/lib/auth/social/q/platform/js#amazon-cognito-user-pool-setup

I can login with Facebook, but in development mode only the test users added on Facebook can login, not any facebook user.

However, when I go to facebook to change the app from 'in development' to 'live' it gives me the error:

![Screen Shot 2020-07-31 at 2 39 32 PM](https://user-images.githubusercontent.com/10377501/89079839-393cb600-d33c-11ea-81eb-461e94134d72.jpg)

The recommended site URL from the docs `https://<your-user-pool-domain>/oauth2/idpresponse` is not working with Facebook. How can I resolve this?

**To Reproduce**  
Setup app to have social sign in with Cognito and Auth.federatedSignIn() following this guide:

https://docs.amplify.aws/lib/auth/social/q/platform/js#amazon-cognito-user-pool-setup

1.  Go to https://developers.facebook.com/
2.  Click on your Facebook application
3.  Toggle the 'In Development' to Live
4.  See error 'Broken URL'

**Expected behavior**  
I expect it to be able to toggle to Live, given the other Facebook settings are correct.

**Code Snippet**

**Screenshots**  
 

![Screen Shot 2020-07-31 at 2 39 32 PM](https://user-images.githubusercontent.com/10377501/89080097-cd0e8200-d33c-11ea-8104-85c2a9720e8d.jpg)

**Comment by zacharywenner** [comment]
Just found these related threads as well:  
https://developers.facebook.com/community/threads/278726030042722/  
https://developers.facebook.com/community/threads/605080477083441/

**Comment by ashika01** [comment]
@dabit3 @amhinson any thoughts on this?!

**Comment by amhinson** [comment]
I haven't seen this before. Perhaps there has been a change on the FB side somewhat recently, since those threads are not very old.

I also came across this similar one:
https://developers.facebook.com/community/threads/287439405705720/

**Comment by zacharywenner** [comment]
Does anyone have any workarounds or ideas? We want to deploy Facebook login ability for our 90,000+ users.

**Comment by epappas** [comment]
Hi, has anyone solved this? this has suddenly affected us as well. The app had passed the verification and was working fine, until it stopped recently.

**Comment by zacharywenner** [comment]
There's a suggestion of removing the platform and re-adding it here:  
https://developers.facebook.com/community/threads/278726030042722/  
  
I deleted the app on Facebook, and then made a new one. I switched the app live before adding the Site URL and the rest of the configuration. That worked... for a few days.   
  
I just got an alert that they disabled the app... it changed back to development mode.

Because the Site URL ending in `/oauth2/idpresponse` returns 400, it's rejected by Facebook's auditing system. **The `/oauth2/idpresponse` has to return 200-299 to be compliant.** If this is the bug, then it seems it needs to be fixed by AWS. Sorry to keep pressing on this issue, @amhinson @dabit3, can this be resolved? Or is there a better place to report this since it's involving Cognito?

![](https://user-images.githubusercontent.com/10377501/94834308-d3b98400-03d5-11eb-8e99-2e8ad77b5bfb.jpg)

![](https://user-images.githubusercontent.com/10377501/94834299-d1572a00-03d5-11eb-86cf-952ebee4c652.jpg)

Here's the messages I got:

![](https://user-images.githubusercontent.com/10377501/94833523-d667a980-03d4-11eb-8ece-9a864393962a.jpg)

![](https://user-images.githubusercontent.com/10377501/94833545-dd8eb780-03d4-11eb-97e5-32d16faa9ba3.jpg)

**Comment by zacharywenner** [comment]
It seems this was a bug on Facebook's end. I just got this notification and my app was restored back to "Live" status.

![](https://user-images.githubusercontent.com/10377501/96185515-a0134980-0eff-11eb-8ab7-ecfb09b946df.jpg)

**Comment by vmittal89** [comment]
Hi I am getting the same error "Invalid State" on oauth2 URL in facebook.developers.com. I checked all the settings mentioned in the link - https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-configuring-federation-with-social-idp.html but still getting this invalid state error while accessing URL - https://test.domain.com/oauth2/idpresponse. I was just wondering if anyone has recently received the same issue and how did they resolve it?

**Comment by vmittal89** [comment]
Hi.. do anyone knows its solution?

**Comment by wesam80** [comment]
@vmittal89 I do have the same issue.
The OAuth Redirect URI (e.g. https://test.domain.com/oauth2/idpresponse) does not respond with HTTP status 200-299, as @zacharywenner mentioned above.
Any solution or a workaround @dabit3 @amhinson ?

**Comment by vmittal89** [comment]
Hi @wesam80 - thank you for your post. I am still having the issue and didn't get any solution yet.

**Comment by wesam80** [comment]
@vmittal89 Today I just replaced that value with the URL of the website.
Still working well. Currently, I am not sure what that field is for. 
Could you test and confirm, please?

**Comment by vmittal89** [comment]
Hi @wesam80  - thank you for your message. I also conducted the same steps couple of days ago and awaiting notification from Facebook for their confirmation before I share the solution here. I just received their notification this morning and it seems the issue has been resolved now.

**Comment by JosephVasse** [comment]
Hello, I'm facing the same issue today, Facebook is asking me to provide a valid url for the website where I had put 
```https://myapp.auth.eu-west-1.amazoncognito.com/oauth2/idpresponse```

@wesam80 @vmittal89 sorry for disturbing you but can you confirm adding a "classical" url such as "https://myapp.com" will not broke my authentication system ? 

Thanks 
Joseph

**Comment by wesam80** [comment]
Yes, it worked for me in all three environments, sit, uat, and prod :)
Better you change it and keep watching your website for some time, just to
make sure

**Comment by vmittal89** [comment]
Hi Joseph - it worked for me as well. No issues encountered so far and everything is working as expected as far as Facebook login.

**Comment by zacharywenner** [comment]
> Hello, I'm facing the same issue today, Facebook is asking me to provide a valid url for the website where I had put `https://myapp.auth.eu-west-1.amazoncognito.com/oauth2/idpresponse`
> 
> @wesam80 @vmittal89 sorry for disturbing you but can you confirm adding a "classical" url such as "https://myapp.com" will not broke my authentication system ?
> 
> Thanks Joseph

I've had this issue off and on, even up until now.

Normal URL to our main website seems to work fine and not break the authentication. Thanks!

**Comment by vmittal89** [comment]
Hi @zacharywenner it didn't break the authentication yet.. It's working good so far for me but keep any eye out on it for sometime after making the change.
Replacing your current URL with classical one should work!

**Comment by tharikrizan** [comment]
I am also facing this issue. Is this resolved?
@zacharywenner did you find a way?
![image](https://user-images.githubusercontent.com/53909627/174980145-20c393a6-1d4b-4c66-9281-f37079fd5315.png)

**Comment by dagmfre** [comment]
I think this answer from chatGPT should fix the error

To resolve this issue, you should update the "Website" field in the Basic Settings of your Facebook app with the appropriate URL where your application is hosted. This URL should be accessible over the internet and not limited to your local development environment.
