### ISSUE TITLE
Authenticator shows additional social button

### ISSUE THREAD

**Issue by alexandrefilipiak** [aws-amplify/amplify-js#6469]
**Describe the bug**
I am trying to use federated buttons with the Authenticator component

I have the google button and facebook that appear correctly.

But the UI adds also another unexpected AWS button :
![social_buttons](https://user-images.githubusercontent.com/65644177/89104043-5601e800-d427-11ea-8e40-570c5ac1036d.png)

**To Reproduce**
Here is the code I'm using :
![image](https://user-images.githubusercontent.com/65644177/89104182-6a92b000-d428-11ea-80ac-7e9dc23eacde.png)

**Expected behavior**
I expected to have only the Google and Facebook buttons.
Also, the unwanted buttons leads me to another login screen.

**Code Snippet**

**What is Configured?**
* Which steps did you follow via Amplify CLI when configuring your resources.
I added auth service with option "Federated"
* Which resources do you have configured?
  * If applicable, please provide your `aws-exports` file:
   ```
"aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2bdb919d-7bb0-42dd-9536-04349aecf237",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_KRw8O4NJZ",
    "aws_user_pools_web_client_id": "4vi8rp8kg1v94m6n3le7np1uit",
    "oauth": {
        "domain": "manydone84d59f8d-84d59f8d-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://3h7mtrvvjbfnbaz7juj3nevami.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-6leyk6xxfjaubk4bzo7fy2jote",
    "aws_user_files_s3_bucket": "manydone-images143339-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
   ```

**Comment by ashika01** [comment]
@alexandrefilipiak I was able to reproduce this. We will work on solving this.

**Comment by alexandrefilipiak** [comment]
@ashika01 : thanks for investigating. I did not see much informations about using AmplifyAuthenticator with federated buttons in the official docs. So it might be that it was not meant to use with the AmplifyAuthenticator or not ready yet...

**Comment by yshterev** [comment]
@alexandrefilipiak Any luck with this? I am trying to do the same...
