### ISSUE TITLE
DataStore fails to validate beginsWith predicate with error message TypeError: Cannot read property 'startsWith' of undefined     

### ISSUE THREAD

**Issue by pedramp20** [aws-amplify/amplify-js#6475]
**Describe the bug**
When a query performed with "beginsWith" predicate, the following error message is received

util.ts:95 Uncaught (in promise) TypeError: Cannot read property 'startsWith' of undefined
    at validatePredicateField (util.ts:95)
    at util.ts:59
    at Array.every (<anonymous>)
    at validatePredicate (util.ts:54)
    at indexeddb.ts:396
    at Array.filter (<anonymous>)
    at IndexedDBAdapter.<anonymous> (indexeddb.ts:395)
    at step (index.ts:12)
    at Object.next (index.ts:12)
    at fulfilled (index.ts:12)

**To Reproduce**
query dataStore as follows:

` const users = await DataStore.query(User, u => u.email("beginsWith", email));`

**Expected behavior**
An array of users where their email address starts with the passed string

**Comment by ashika01** [comment]
@pedramp20 I just tried reproducing what you are trying to achieve. And I can not reproduce the issue. 

I am using the version - ` @aws-amplify/datastore@2.2.8`


Here are some screenshots,
**Querying without predicate**
<img width="1195" alt="Screen Shot 2020-08-04 at 12 07 56 AM" src="https://user-images.githubusercontent.com/35131273/89259127-dde22080-d5e6-11ea-9b68-9f689b3a19cb.png">

**Querying with predicate set to `beginsWith` string "My"**
<img width="450" alt="Screen Shot 2020-08-04 at 12 08 15 AM" src="https://user-images.githubusercontent.com/35131273/89259172-f4887780-d5e6-11ea-89d9-61b73a564e08.png">

**Querying with predicate set to `beginsWith` string "Mine"**
<img width="432" alt="Screen Shot 2020-08-04 at 12 08 27 AM" src="https://user-images.githubusercontent.com/35131273/89259191-023dfd00-d5e7-11ea-8fdf-7f87063b4fe8.png">



Share a code snippet of when this is happening, what your schema looks like. Also, where you able to successfully push your modelgen to the backend?!
