### ISSUE TITLE
DataStore doesn't initialize

### ISSUE THREAD

**Issue by Darapsas** [aws-amplify/amplify-js#6478]
**Describe the bug**
Currently I am trying to upgrade my aws packages from:
```
    "@aws-amplify/api": "3.1.16-unstable.4",
    "@aws-amplify/auth": "3.2.13-unstable.4",
    "@aws-amplify/cache": "3.1.16-unstable.4",
    "@aws-amplify/core": "3.3.3-unstable.4",
    "@aws-amplify/datastore": "2.2.3-unstable.4",
    "@aws-amplify/pubsub": "3.0.17-unstable.4",
    "@aws-amplify/storage": "3.2.6-unstable.4",
    "amazon-cognito-identity-js": "4.3.2-unstable.8",
```
to:
```
    "@aws-amplify/api": "^3.1.21",
    "@aws-amplify/auth": "^3.3.3",
    "@aws-amplify/cache": "^3.1.21",
    "@aws-amplify/core": "^3.4.4",
    "@aws-amplify/datastore": "^2.2.8",
    "@aws-amplify/pubsub": "^3.0.22",
    "@aws-amplify/storage": "^3.2.11",
    "amazon-cognito-identity-js": "^4.3.3",
```

When user tries to sign in to the account, the app waits for the 'subscriptionEstablished' event, which never happens, as you can see that last event that I get is outboxStatus and that is it, nothing else happens:

![image](https://user-images.githubusercontent.com/20926795/89193641-f2a2c200-d5ae-11ea-84ff-b427a4f4a8f3.png)

I am using similar code to the one @manueliglesias showed me last time in this issue https://github.com/aws-amplify/amplify-js/issues/5991

**Comment by mauerbac** [comment]
Thanks for filling this @Darapsas. We've identified this as a bug documented in #6108. We will track this in that issue.
