### ISSUE TITLE
Why does DataStore need @connection?

### ISSUE THREAD

**Issue by hanzhaodeng** [aws-amplify/amplify-js#6482]
Given the doc: https://docs.amplify.aws/lib/datastore/data-access/q/platform/js#query-data
`const post = await DataStore.query(Post, "123");
const comments = (await DataStore.query(Comment)).filter(c => c.postID === post.id);`
If we are querying for data in separate queries, why do we still need @connection directive? As I understand it it is for Graphql to pull data in one go, but if we use DataStore don't we always need to pull different objects at different queries? Doesn't that defeat the need for defining @connection?
Am I missing something?
Also is there a way for DataStore to query sorted result?
Thanks for the hard work I really appreciate it.

**Comment by iartemiev** [comment]
Hi @hanzhaodeng, we plan to allow lazy loading relational data, e.g., being able to retrieve all comments

**Comment by iartemiev** [comment]
Hi @hanzhaodeng, we plan on adding lazy loading for relational data, e.g., being able to retrieve all comments related to a post via `post.comments`. You can track this feature here: https://github.com/aws-amplify/amplify-js/issues/5054

Sorting is also a feature that we intend on adding soon: https://github.com/aws-amplify/amplify-js/issues/4652
