### ISSUE TITLE
Cancel dispatched amplify sign out event

### ISSUE THREAD

**Issue by manuelzea** [aws-amplify/amplify-js#6490]
We are trying to implement a way to allow the user of our app to cancel the sign out Auth request in order to not interupt an upload in progress.

We have tried attaching the 'beforeunload' event listener to use the e.preventDefault() to stop the sign out action.

```
 window.addEventListener('beforeunload', handleUploadSessionWarning);

  const handleUploadSessionWarning = (e: BeforeUnloadEvent) => {
    // Cancel the event
    e.preventDefault();
    e.returnValue = '';
  };
```
However, it seems like the sign in/sign out module falls outside of the browser's event and it's not captured in the preventDefault. 

Is there a way to cancel the dispatched aws amplify sign out event?

**Comment by tannerabread** [comment]
Hi @manuelzea, I believe a normal flow for this would be to handle the confirm/cancel functionality on the frontend before making the network request. Once the call to Cognito for sign-out is made I do not believe there is a way to cancel it as it is pretty immediate.

Can you explain a bit more about why this wouldn't be handled in the frontend of your app, or if you are still struggling with this?

**Comment by tannerabread** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and are in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
