### ISSUE TITLE
API 403 error on api-rest calls after recent upgrade

### ISSUE THREAD

**Issue by sadooghi** [aws-amplify/amplify-js#6492]
**Describe the bug**
When upgrading from aws-amplify @3.0.17 to @3.0.22 my REST APIs that need authorization all get back 403 errors. This is solved by downgrading api-rest to 1.0.18. I think the errors starts when upgrading from api-rest 1.0.18 to 1.1.0

**To Reproduce**
Using previously created aws-export.js, upgrade from api-rest 1.0.18 to latest api-reset

**Expected behavior**
Should not show 403 errors with existing api.

**Code Snippet**
Please provide a code snippet or a link to sample code of the issue you are experiencing to help us reproduce the issue. (Be sure to remove any sensitive data)

**Screenshots**

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.
* Which resources do you have configured?
  * If applicable, please provide your `aws-exports` file:
   ```
   const awsmobile = {
       "aws_project_region": "us-east-1",
       "aws_cognito_identity_pool_id": "us-east-1:c52ffa2a-9a1a-4335-a05c-93a72a3e8e41",
       "aws_cognito_region": "us-east-1",
       "aws_user_pools_id": "us-east-1_8jwmL8sZ6",
       "aws_user_pools_web_client_id": "7dvkubl4fct861ca8l14ik6lno",
       "oauth": {}
   };
   ```
   * If applicable, please provide your manual configuration example:
   ```
   {
    Auth: {
        identityPoolId: 'XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab',
        region: 'XX-XXXX-X',
        identityPoolRegion: 'XX-XXXX-X',
        userPoolId: 'XX-XXXX-X_abcd1234',
        userPoolWebClientId: 'a1b2c3d4e5f6g7h8i9j0k1l2m3',
        mandatorySignIn: false,
        authenticationFlowType: 'USER_PASSWORD_AUTH',
        oauth: {
            domain: 'your_cognito_domain',
            scope: ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
            redirectSignIn: 'http://localhost:3000/',
            redirectSignOut: 'http://localhost:3000/',
            responseType: 'code' // or 'token', note that REFRESH token will only be generated when the responseType is code
           }
       }
   }
   ```
* If applicable, provide more configuration data, for example for Amazon Cognito, run `aws cognito-idp describe-user-pool --user-pool-id us-west-2_xxxxxx` (Be sure to remove any sensitive data)
 

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

</details>

**Smartphone (please complete the following information):**

**Additional context**

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by amhinson** [comment]
Could you also share your `package.json`?

**Comment by sadooghi** [comment]
{
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@aws-amplify/core": "^3.3.3",
    "@react-native-community/art": "^1.2.0",
    "@react-native-community/datetimepicker": "^2.6.1",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-firebase/admob": "^7.4.1",
    "@react-native-firebase/analytics": "^7.4.1",
    "@react-native-firebase/app": "^8.3.0",
    "@react-native-firebase/crashlytics": "^8.3.0",
    "amazon-cognito-identity-js": "^3.2.0",
    "aws-amplify": "^3.0.17",
    "axios": "^0.19.2",
    "barcode-reader": "^1.6.1",
    "buffer": "^5.6.0",
    "create-react-class": "^15.6.3",
    "moment": "^2.27.0",
    "native-base": "^2.13.13",
    "react": "16.13.1",
    "react-lifecycles-compat": "^3.0.4",
    "react-native": "^0.63.2",
    "react-native-dotenv": "^0.2.0",
    "react-native-fs": "^2.16.6",
    "react-native-mime-types": "^2.2.1",
    "react-native-multi-range": "^0.1.0",
    "react-native-onesignal": "^3.9.0",
    "react-native-popup-menu": "^0.15.9",
    "react-native-reanimated": "^1.10.2",
    "react-native-safe-area-context": "^3.1.4",
    "react-native-screens": "^2.10.1",
    "react-native-selectmultiple-button": "^0.1.105",
    "react-native-share": "^3.7.0",
    "react-native-speedometer": "^1.0.3",
    "react-native-step-indicator": "^1.0.3",
    "react-native-webview": "^10.4.0",
    "react-navigation": "^4.4.0",
    "react-navigation-hooks": "^1.1.0",
    "react-navigation-stack": "^2.8.2",
    "react-navigation-tabs": "^2.9.0",
    "react-redux": "^7.2.1",
    "react-timer-mixin": "^0.13.4",
    "redux": "^4.0.5",
    "redux-actions": "^2.6.5",
    "redux-thunk": "^2.3.0",
    "rn-fetch-blob": "^0.12.0",
    "save": "^2.4.0",
    "seedrandom": "^3.0.5"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.2.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
    "@babel/preset-env": "^7.2.3",
    "@babel/preset-flow": "^7.0.0",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^25.1.0",
    "babel-plugin-import": "^1.6.3",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "hermes-engine": "^0.5.0",
    "jest": "^25.1.0",
    "jetifier": "^1.6.6",
    "metro": "^0.55.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by sadooghi** [comment]
@amhinson 

> Could you also share your `package.json`?

{
"version": "0.0.1",
"private": true,
"scripts": {
"start": "react-native start",
"test": "jest",
"lint": "eslint ."
},
"dependencies": {
"@aws-amplify/core": "^3.3.3",
"@react-native-community/art": "^1.2.0",
"@react-native-community/datetimepicker": "^2.6.1",
"@react-native-community/masked-view": "^0.1.10",
"@react-native-firebase/admob": "^7.4.1",
"@react-native-firebase/analytics": "^7.4.1",
"@react-native-firebase/app": "^8.3.0",
"@react-native-firebase/crashlytics": "^8.3.0",
"amazon-cognito-identity-js": "^3.2.0",
"aws-amplify": "^3.0.17",
"axios": "^0.19.2",
"barcode-reader": "^1.6.1",
"buffer": "^5.6.0",
"create-react-class": "^15.6.3",
"moment": "^2.27.0",
"native-base": "^2.13.13",
"react": "16.13.1",
"react-lifecycles-compat": "^3.0.4",
"react-native": "^0.63.2",
"react-native-dotenv": "^0.2.0",
"react-native-fs": "^2.16.6",
"react-native-mime-types": "^2.2.1",
"react-native-multi-range": "^0.1.0",
"react-native-onesignal": "^3.9.0",
"react-native-popup-menu": "^0.15.9",
"react-native-reanimated": "^1.10.2",
"react-native-safe-area-context": "^3.1.4",
"react-native-screens": "^2.10.1",
"react-native-selectmultiple-button": "^0.1.105",
"react-native-share": "^3.7.0",
"react-native-speedometer": "^1.0.3",
"react-native-step-indicator": "^1.0.3",
"react-native-webview": "^10.4.0",
"react-navigation": "^4.4.0",
"react-navigation-hooks": "^1.1.0",
"react-navigation-stack": "^2.8.2",
"react-navigation-tabs": "^2.9.0",
"react-redux": "^7.2.1",
"react-timer-mixin": "^0.13.4",
"redux": "^4.0.5",
"redux-actions": "^2.6.5",
"redux-thunk": "^2.3.0",
"rn-fetch-blob": "^0.12.0",
"save": "^2.4.0",
"seedrandom": "^3.0.5"
},
"devDependencies": {
"@babel/core": "^7.8.4",
"@babel/plugin-proposal-nullish-coalescing-operator": "^7.2.0",
"@babel/plugin-proposal-object-rest-spread": "^7.0.0",
"@babel/preset-env": "^7.2.3",
"@babel/preset-flow": "^7.0.0",
"@babel/runtime": "^7.8.4",
"@react-native-community/eslint-config": "^1.1.0",
"babel-jest": "^25.1.0",
"babel-plugin-import": "^1.6.3",
"babel-plugin-transform-remove-console": "^6.9.4",
"hermes-engine": "^0.5.0",
"jest": "^25.1.0",
"jetifier": "^1.6.6",
"metro": "^0.55.0",
"metro-react-native-babel-preset": "^0.59.0",
"react-test-renderer": "16.13.1"
},
"jest": {
"preset": "react-native"
}
}

**Comment by amhinson** [comment]
Are you using an API from Amplify? Could you post your configuration/usage as well? If not, could you explain more about your API?

Also, you can remove the `@aws-amplify/core` dependency, as it is already included in `aws-amplify`. Sometimes having different version in your package.json can cause issues. After removing it, I'd recommend deleting your node_modules and reinstalling.

**Comment by sadooghi** [comment]
removing `@aws-amplify/core` solved the issue thank you.

Only note is aws-amplify 3.0.22 imports core by default, 3.0.23 did not for me.

**Comment by sadooghi** [comment]
closing this

**Comment by sadooghi** [comment]
reopening just for the last point i.e. 3.0.23 didn't import core automatically.

**Comment by amhinson** [comment]
Could you elaborate a bit on what you're seeing? `@aws-amplify/core` is a dependency of `aws-amplify` so it should be getting used. I'd also recommend deleting your node modules and reinstalling.

**Comment by sadooghi** [comment]
I did uninstall and reinstall all packages but when I did 3.0.23 app crashed saying dependencies core was missing, did the same with 3.0.22 but it worked.

**Comment by amhinson** [comment]
Are you importing anything in your project directly from `@aws-amplify/core`? If so, you can now just import it from `aws-amplify`

**Comment by sadooghi** [comment]
I am not (after removing core), but maybe it's just my own issue?
