### ISSUE TITLE
Graphql mutation fails when custom identityClaim is used in the auth directive

### ISSUE THREAD

**Issue by pedramp20** [aws-amplify/amplify-js#6493]
**Describe the bug**
When a custom claim rather than the default cognito username is set in the auth directive, the mutation request fails

**To Reproduce**
1. Define a type like the following type in your schema.graphql
```
   type SomeType
	@model(queries: null)
	@auth(
		rules: [
			{ allow: owner, ownerField: "editors", identityClaim: "email", operations: [create, update, delete, read] }
		]
	) {
	id: ID!	
	editors: [String]	
   }

```
2. Push changes to amplify and generate models

```
amplify push
amplify codegen models
```

3. import the mutation and perform it in your code

```
 const createSomeTypeInput = {
      id: uuid(),
      editors: [user.email],
    }

    const result = await API.graphql(graphqlOperation(createSomeType,
      {
        input: createSomeTypeInput 
      }));
```
4.  error
```
errorType: "Unauthorized"
message: "Not Authorized to access createSomeType on type SomeType"
```

**Expected behavior**
To be able to perform the mutation. Please note that if the identityClaim is removed from the rule, which sets it to the default cognito username and rather than email, user's username is added to the editors, everything works as expected

**Comment by pedramp20** [comment]
Well this could be due to the absence of email claim in the default coginto access token payload.

**Comment by hectorharvey** [comment]
Please elaborate.  From my understanding the email should not be on the Access Token.  It should be on the Identity Token.  I am hitting the same security issue.
