### ISSUE TITLE
Offer option to use py instead of python3

### ISSUE THREAD

**Issue by pendraggon87** [aws-amplify/amplify-js#6496]
**Is your feature request related to a problem? Please describe.**
When adding a Python lambda function, errors occur because python3 is not in the PATH (Windows)

**Describe the solution you'd like**
Allow the use of "py" or just "python" instead of the "python3" binary - on windows, this is still python 3

**Comment by sammartinez** [comment]
@pendraggon87 Is this as you are adding functions via our Amplify CLI?
