### ISSUE TITLE
Authenticator Email Confirmation Fails to Sign User In

### ISSUE THREAD

**Issue by charliegilchrist-sb** [aws-amplify/amplify-js#6501]
**Describe the bug**
When a user creates an account then doesn't confirm their email, then attempts to sign in, they are asked to confirm their email again. After inputting the correct verification code, their email is confirmed, but they are not signed in and the sign in event is not thrown.

**To Reproduce**

Following the new react documentation here : https://docs.amplify.aws/ui/auth/authenticator/q/framework/react

1) Create a new user.
2) When asked to confirm their email, refresh the page.
3) Try to sign in as the new user, and you will be asked to confirm the email.
4) Enter the correct verification code
5) The SignIn event is not thrown and the user is not authenticated. However, the verification did happen.

**Expected behavior**
When a user confirms their email address, it should authenticate them and fire the SignIn event. If the user confirms their email directly after creating a user, it works exactly as expected.

**Code Snippet**
Following the new react documentation here : https://docs.amplify.aws/ui/auth/authenticator/q/framework/react

**What is Configured?**
I am only using the Amplify Authenticator component. Cognito configuration was done via the Cognito Console.

**Comment by ashika01** [comment]
@charliegilchrist-sb Could you try our recent unstable version, to see if that fixes this?!

**Comment by johynpapin** [comment]
I have the same problem with Vue.
