### ISSUE TITLE
Encountered error 404 during npm install aws-amplify

### ISSUE THREAD

**Issue by LDHo** [aws-amplify/amplify-js#6511]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@aws-amplify%2fcache - Not found
npm ERR! 404 
npm ERR! 404  '@aws-amplify/cache@^1.2.3' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'aws-amplify'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/liande/.npm/_logs/2020-08-06T09_23_45_549Z-debug.log

I encountered this while I am trying to npm install aws-amplify.

Hope anyone can help me with this.

**Comment by mxswat** [comment]
+1 same issue here with registry http://registry.npmjs.org

**Comment by worldroamertech** [comment]
+1 facing the same issue here as well 

`error An unexpected error occurred: "https://registry.yarnpkg.com/@mdi/js/-/js-3.8.95.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/codebuild/output/src787143198/src/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[Container] 2020/08/06 09:46:12 Command did not exit successfully yarn install --ignore-engines exit status 1
[Container] 2020/08/06 09:46:12 Phase complete: PRE_BUILD State: FAILED
[Container] 2020/08/06 09:46:12 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: yarn install --ignore-engines. Reason: exit status 1`

**Comment by leejaew** [comment]
+1 also facing some issues here
`error An unexpected error occurred: "https://registry.yarnpkg.com/@mdi/js/-/js-3.8.95.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/codebuild/output/src787143198/src/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[Container] 2020/08/06 09:46:12 Command did not exit successfully yarn install --ignore-engines exit status 1
[Container] 2020/08/06 09:46:12 Phase complete: PRE_BUILD State: FAILED
[Container] 2020/08/06 09:46:12 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: yarn install --ignore-engines. Reason: exit status 1`

**Comment by mxswat** [comment]
From the Amplify discord server:

NPM posted an incident report. Should be resolved now. https://status.npmjs.org/incidents/cksjqc1w11v5

**Comment by nathanqueija** [comment]
The auto deploy feature on Amplify is also not working. It fails in the step of bumping the cli version.

**Comment by iartemiev** [comment]
@mxswat @LDHo we've confirmed that this was an NPM issue that has been resolved. Closing

@nathanqueija please open a GitHub issue in the [Amplify Console](https://github.com/aws-amplify/amplify-console) repo if you're still experiencing problems with the auto-deploy feature.
