### ISSUE TITLE
Cognito Pre Sign Up lambda triggers not being run before rejecting new user sign up

### ISSUE THREAD

**Issue by paulsjohnson91** [aws-amplify/amplify-js#6513]
**Describe the bug**
I'm currently trying to integrate Google Auth into my React Native application using AWS Amplify Cognito, when I originally set up the Cognito instance, I had date of birth as a required field, and unfortunately this isn't supplied by Google Auth and you cannot remove a required field from a Cognito instance. I asked for advice on here before and was told that the best way to do it was to introduce a pre sign up lambda trigger which could add the date of birth field before creation [link to previous](https://github.com/aws-amplify/amplify-js/issues/6020). 
The issue is that when I send off a sign up request through Amplify (either with google auth or just using Auth.SignUp() the pre sign up lambda trigger isn't being run, which I can tell from the logs.

I'm getting back the error
`console.error: [ERROR] 40:58.475 OAuth - Error handling auth response. Error: attributes+required%3A+%5Bbirthdate%5D`

I don't know how I can use Google Auth here.

Config:
```
const awsConfig = {
  aws_app_analytics: 'enable',
  aws_region: 'eu-west-1',
  aws_cognito_region: 'eu-west-1',
  aws_user_pools: 'enable',
  aws_user_pools_id: 'eu-west-1_<id>',
  aws_user_pools_mfa_type: 'OFF',
  aws_user_pools_web_client_id: '<client>',
  aws_user_settings: 'enable',
  aws_cognito_identity_pool_id:
    'eu-west-1:<id>',
  aws_federation_target: 'COGNITO_USER_POOLS',
  aws_logins: {
    google:
      '<google login>',
  },
};

Amplify.configure({
  ...awsConfig,
  region: 'eu-west-1',
  federatedTarget: 'COGNITO_USER_POOLS',
  oauth: {
    domain: '<mydomain>.auth.eu-west-1.amazoncognito.com',
    scope: [
      'phone',
      'email',
      'profile',
      'openid',
      'aws.cognito.signin.user.admin',
    ],
    redirectSignIn: '<redirect>',
    redirectSignOut: '<redirect>',
    responseType: 'code',
  },
});
```

Google sign in method (although this happens with Auth.SignUp too)
`    const userinfo = Auth.federatedSignIn({provider: 'Google'});`

**Comment by RossWilliams** [comment]
You can migrate to a new user pool with date of birth not required. There are API helpers for this in the SDK.

**Comment by dingdongping** [comment]
Is there any restriction on how many mobile phones can log in and use the cognito account at the same time

**Comment by RossWilliams** [comment]
No restrictions by default. You can use triggers to add restrictions

**Comment by dingdongping** [comment]
> No restrictions by default. You can use triggers to add restrictions

Thank you. I only need to use PubSub in my application. Can I just create a cognito account? All accounts in my system share the same cognito account to use PubSub service.

**Comment by RossWilliams** [comment]
You can use API key authentication instead of user pools if you don’t actually need users

**Comment by dingdongping** [comment]
The use of PubSub I found depends on the auth module and needs to register cognito account.（https://docs.amplify.aws/lib/pubsub/getting-started/q/platform/js）

Can you tell me to use PubSub's document link through API key authentication?

**Comment by dingdongping** [comment]
@RossWilliams 
In the document of amplify-JS of react-native, I didn't find the use document of API key authentication.（https://docs.amplify.aws/lib/pubsub/getting-started/q/platform/js）


Can you tell me to use PubSub's document link through API key authentication?

**Comment by RossWilliams** [comment]
You were suggesting that all users would share a single Cognito login, this suggests you want open access to your API, and you don’t have users logging in. In this case you could use API Key auth with AppSync and use the Unauth Cognito role for websocket communication. The instructions are very similar, but you would configure the Unauth role instead of the Auth role

**Comment by dingdongping** [comment]
@RossWilliams 
In react-native,I can now use the PubSub module directly through the tourist identity, but I'm not sure if I'm doing it right because I don't know if the visitor's identity will expire and the PubSub module won't work. Amplify JS creates an ID for each visitor.



Here are my steps to use PubSub

1. Enable access to unauthorized identities in identity pools

2. Configure the IOT related permissions for unauthrole in Iam



         let aws_pubsub_endpoint = 'wss://' + 'a2c946l7o9giax-ats.iot.eu-west-2.amazonaws.com' + '/mqtt';
            // Apply plugin with configuration
            Amplify.addPluggable(new AWSIoTProvider({
              aws_pubsub_region: 'eu-west-2',
              aws_pubsub_endpoint: aws_pubsub_endpoint,
            }));

     PubSub.subscribe('wwwdd').subscribe({
              next: data => {
                console.log('Message received',data)    
              },
              error: error => console.error(error),
              close: () => console.log('Done'),
          
            });

**Comment by RossWilliams** [comment]
Yes, all identities with cognitive expire and Amplify libraries detect this and get new ones when needed

**Comment by dingdongping** [comment]
Thank you. I know that amplify JS will automatically handle the issue of expired tourist identity. 
I don't need to worry that the expired tourist identity will lead to the inability to use PubSub module

**Comment by paulsjohnson91** [comment]
@RossWilliams can you please point me to where I can find this helper?
I've set up a user migration lambda script, and when I sign in with the following curl (with a user that hasn't been migrated yet)
```
curl --request POST \
  --url https://cognito-idp.eu-west-1.amazonaws.com/ \
  --header 'content-type: application/x-amz-json-1.1' \
  --header 'x-amz-target: AWSCognitoIdentityProviderService.InitiateAuth' \
  --data '{
   "AuthParameters" : {
      "USERNAME" : "<user>",
      "PASSWORD" : "<pass>"
   },
   "AuthFlow" : "USER_PASSWORD_AUTH",
   "ClientId" : "<client>"
}'
```
Then I'm successfully signed in and migrated, however if I try to use amplifys sign in function, I just get incorrect credentials, and looking in the cloudwatch trails, as with the original problem from this post, amplify seems to be completely disregarting lambda triggers, in this case the user migration lambda trigger

**Comment by RossWilliams** [comment]
It sounds like you followed this documentation: https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-import-using-lambda.html

Best guess without seeing your code is that you are NOT using password auth. The default SRP auth will not work in this scenario. Check the network requests to Cognito and make sure the password is sent. Or check your configuration

```js
Auth.configure({
    authenticationFlowType: "USER_PASSWORD_AUTH",
  // other config here...
})
```

**Comment by amhinson** [comment]
@paulsjohnson91 Are you still having trigger issues or were you able to resolve it?

**Comment by dingdongping** [comment]
@RossWilliams hello,How can I disconnect PubSub? I found that in react-native, after the mobile network is disconnected, I can't subscribe to a topic after reconnecting
