### ISSUE TITLE
Can't resolve '@aws-amplify/storage' in '@aws-amplify/ui-components/dist/esm'

### ISSUE THREAD

**Issue by gsans** [aws-amplify/amplify-js#6515]
**Describe the bug**
When building an angular app with `ng serve` these errors show:

```
ERROR in ./node_modules/@aws-amplify/ui-components/dist/esm/amplify-s3-text.entry.js
Module not found: Error: Can't resolve '@aws-amplify/storage' in '/Users/gsans/Desktop/Projects/tutorials/amplify-app-demo/node_modules/@aws-amplify/ui-components/dist/esm'

ERROR in ./node_modules/@aws-amplify/ui-components/dist/esm/amplify-s3-text-picker.entry.js
Module not found: Error: Can't resolve '@aws-amplify/storage' in '/Users/gsans/Desktop/Projects/tutorials/amplify-app-demo/node_modules/@aws-amplify/ui-components/dist/esm'

ERROR in ./node_modules/@aws-amplify/ui-components/dist/esm/amplify-s3-image-picker.entry.js
Module not found: Error: Can't resolve '@aws-amplify/storage' in '/Users/gsans/Desktop/Projects/tutorials/amplify-app-demo/node_modules/@aws-amplify/ui-components/dist/esm'

ERROR in ./node_modules/@aws-amplify/ui-components/dist/esm/amplify-s3-image.entry.js
Module not found: Error: Can't resolve '@aws-amplify/storage' in '/Users/gsans/Desktop/Projects/tutorials/amplify-app-demo/node_modules/@aws-amplify/ui-components/dist/esm'

ERROR in ./node_modules/@aws-amplify/ui-components/dist/esm/amplify-s3-album.entry.js
Module not found: Error: Can't resolve '@aws-amplify/storage' in '/Users/gsans/Desktop/Projects/tutorials/amplify-app-demo/node_modules/@aws-amplify/ui-components/dist/esm'

ERROR in ./node_modules/@aws-amplify/ui-components/dist/esm/storage-helper-21c6d15f.js
Module not found: Error: Can't resolve '@aws-amplify/storage' in '/Users/gsans/Desktop/Projects/tutorials/amplify-app-demo/node_modules/@aws-amplify/ui-components/dist/esm'
```

In order to resolve I had to run `npm i @aws-amplify/storage` which shouldn't be necessary.

**To Reproduce**

1. Follow the Getting started guide for Angular [here](https://docs.amplify.aws/start/q/integration/angular)
2. After [Install Amplify libraries](https://docs.amplify.aws/start/getting-started/setup/q/integration/angular#install-amplify-libraries) the errors show after running `ng serve`.

**Expected behavior**
No errors.

**Code Snippet**
NA

**Screenshots**
NA

**What is Configured?**
Amplify CLI: 4.26.0
Angular CLI: 10.0.5
Node: 14.7.0
OS: darwin x64
Angular: 10.0.7

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by sammartinez** [comment]
@gsans There was an issue with npm registry this morning that this looks to be related to. Please try to reinstall now as those issues are resolved. Resolving issue as the Npm issue. Please let us know if it continues and we can re open

**Comment by gsans** [comment]
This issue is still happening after reinstall.

**Comment by sammartinez** [comment]
Did you try to remove your `node_modules` and lock files?

**Comment by gsans** [comment]
Let me try. I saw this error yesterday so I don't think is npm related anyway

**Comment by sammartinez** [comment]
> Let me try. I saw this error yesterday so I don't think is npm related anyway

Sounds good, one thing to note is we only support up to Angular 9 right now. I am seeing you're using Angular 10, which just recently came out but we are exploring this into see what is needed from what we generate for our UI Components.

**Comment by gsans** [comment]
I can confirm this issue is still happening after removing node_modules, lock files and reinstalling all npm packages.

Yes. It would be good if this can be fixed for Angular 10 as many users are getting worried Angular is not given proper attention vs React.

Most Angular developers will be using Angular 10. For now adding the dependency fixes the issue but my app is not using storage so it adds unnecessary weight to the bundle.

**Comment by sammartinez** [comment]
I was able to install the Angular CLI v10 and got no errors. Maybe we talk internally on this @gsans

**Comment by gsans** [comment]
Let's do that. I'm a just bit worried as this issue is related to the getting started guide for Angular

**Comment by dabit3** [comment]
cc @jordanranz
