### ISSUE TITLE
Add custom cognito user pool programmatically?

### ISSUE THREAD

**Issue by sakhmedbayev** [aws-amplify/amplify-js#6518]
**Is your feature request related to a problem? Please describe.**
We are building a SaaS using AWS Amplify and AWS AppSync. For each new tenant/customer, we create a new Cognito User Pool using cloudformation. We know that it is possible to add those user pools to AppSync manually using AppSync's console, however, is it possible to do the same programmatically?

**Describe the solution you'd like**
provide an API to add custom cognito user pool programmatically

**Describe alternatives you've considered**
using cloudformation

**Comment by RossWilliams** [comment]
Yes, I've added some code below to help you do this, but i would strongly advise against it, as Amplify doesn't support it well. Is there another design you can choose? You will need to add @aws_cognito_user_pools on all types you want to access in your schema, and you can't use amplify top-level generated fields, instead you need to add your own with @aws_cognito_user_pools added, or you need to modify amplify to do this for you. You are also limited to 50 authentication providers.

** note: not tested,  **
```typescript


async function addNewPoolToAppSync(
  userPoolId: string,
  graphqlAPIId: string,
  region: string) {
  const appSync = new AWS.AppSync();
  let { graphqlApi } = await appSync.getGraphqlApi({ apiId: graphqlAPIId }).promise();
  if (!graphqlApi || !graphqlApi.apiId) {
    throw new Error("Could not find graphql API");
  }

  const newGraphqlConfig: UpdateGraphqlApiRequest = {
    apiId: graphqlApi.apiId,
    name: graphqlApi.name,
    authenticationType: graphqlApi.authenticationType,
    userPoolConfig: graphqlApi.userPoolConfig,
    additionalAuthenticationProviders: [
      ...graphqlApi.additionalAuthenticationProviders
      {
        authenticationType: "AMAZON_COGNITO_USER_POOLS",
        userPoolConfig: {
          userPoolId: userpoolId,
          awsRegion: region,
        },
      },
    ],
    xrayEnabled: graphqlApi.xrayEnabled,
    logConfig: graphqlApi.logConfig
  };

  return await appSync
    .updateGraphqlApi(newGraphqlConfig)
    .promise()
    .catch((e: any) => {
      console.error(
        "ERROR: Could not update API to accept new pool ",
        e
      );
    });
}
```

remember to give your lambda proper permissions for the AppSync call

**Comment by sakhmedbayev** [comment]
Thanks @RossWilliams, for the reply. Tell me, will I face "50 authorization providers" limit no matter which strategy I choose?

**Comment by RossWilliams** [comment]
This is an AppSync limitation.

Can you say more about why you want a unique user pool for each tenant?

**Comment by sakhmedbayev** [comment]
@RossWilliams this is really bad news :-( Is it documented anywhere?

The reasons for "unique user pool for each tenant" are many. One of them that our customers/tenants could have different requirements for identity providers. Another is that we want to leverage amplify API auth directives while preserving data isolation. Unique user polls can also help us to provide a better analytics to our customers.

Do you know why such a limitation exists in AppSync?

**Comment by RossWilliams** [comment]
Quotas for AppSync are here: https://docs.aws.amazon.com/general/latest/gr/appsync.html

Some alternatives to your needs in a multi-tenant environment
* different requirements fir identity providers does not means you need separate pools. You can have multiple SAML, OIDC, or google providers attached to a pool. You can have 300 identify provers per pool. Also remember that any tenet wanting Azure AD identity provider can share the same OIDC connection, so you are less likely to hit than limit
* auth directives can’t do anything more with multiple cognitive user pools than they can do with just one. Amplify isn’t structured for data isolation between tenants aside from RBAC.
* data isolation inside of different user pools provides no additional security.
* I don’t see how different user pools will help with analytics. You can always have a custom tenantId custom attribute and that would provide the same benefit.

**Comment by sakhmedbayev** [comment]
Thank you agan, @RossWilliams , for the detailed answer. Our decisions were based primarily on [this](https://www.reddit.com/r/aws/comments/fccx6k/multitenant_app_using_aws_amplify/) discussion, more specific on [this](https://www.reddit.com/r/aws/comments/fccx6k/multitenant_app_using_aws_amplify/fjbqsth?utm_source=share&utm_medium=web2x) answer by AWS specialist.

I forgot to add one more reason that we thought that the multiple user pools will benefit our requirements. In terms of tenant-user relationships, our solution will function very similarly to "shopify". From one hand, after the tenant signs up, he/she will get a new domain name on our platform, e.g., `tenant1.example.com` and `tenant2.example.com`.  On another hand, the same end-user can potentially belong to different tenants, so he/she can potentially sign up with the same email (`user1@example.com`) on `tenant1.example.com` and `tenant2.example.com`. The multiple user pools approach is solving this issue for us. I am sure that is solvable in the single-user pool environment too but will require some or a lot of twisting around. Any thoughts?

**Comment by sakhmedbayev** [comment]
It seems that AppSync limitation (Authentication providers per API = 50) make it unfit to scalable multiple tenants' applications.

Taking into account everything said above and the linked resources, what are our options???

**Comment by RossWilliams** [comment]
Do you need to use AppSync? You could run Apollo Server yourself.

**Comment by sakhmedbayev** [comment]
> Do you need to use AppSync? You could run Apollo Server yourself.

Yes, we can use Apollo Server and we probably should. The reason we went with AppSync is that we wanted to leverage its graphql schema directives, e.g., `@auth`, `@connection` e.t.c. We are thinking of moving to Hasura as it provides similar functionality.

> Or you can use a single user pool, but write extra code to handle Cognito admin tasks indirectly.

I would greatly appreciate it if you can demonstrate how I can solve the issue with the end-user belonging to different tenants (the issue that outlined [here](https://github.com/aws-amplify/amplify-js/issues/6518#issuecomment-671148720)).

**Comment by sakhmedbayev** [comment]
Can anyone from Amplify or AppSync team response on how to solve the following issue with the current AppSync limitations:

1. we expect to have more than 50 tenants
2. we want  the end-users to be able to register using their email instead of username
3. the end-user can potentially belong (sign up) to multiple tenants, see my comments [here](https://github.com/aws-amplify/amplify-js/issues/6518#issuecomment-671148720)

**Comment by RossWilliams** [comment]
I'm running a multi-tenant system, although that phrase means many things...

You can have users belong to groups that include their tenancy, and use dynamic group auth. You can use the Cognito pre-token Lambda trigger to populate user groups inside the JWT Access token. This works well where group counts are reasonably bounded.

```graphql
type ProtectedResource @model @auth(rules: [{allow: groups, groupsField: "tenantId", operations: [read]}, {allow: groups, groups: ["Nobody"]}]) {
  id: ID!
  tenantId: String!
  privateData: String
}

type User @model @auth(rules: [{allow: owner, operations: [read]},{allow:groups, groups: ["Admin"]}]) {
  id: ID!
  email: String!
  tenants: [String!]!
}
```

**Comment by sakhmedbayev** [comment]
@RossWilliams do the end-users sing up/register using their email or username in your system?

**Comment by RossWilliams** [comment]
They sign up with their email, but behind the scenes I set their username to be a permutation mixed with their tenant. That way I don’t have issues when users change their email address. Users don’t sign themselves up directly with Cognito, requests go through custom workflows.

**Comment by sakhmedbayev** [comment]
> They sign up with their email, but behind the scenes I set their username to be a permutation mixed with their tenant. That way I don’t have issues when users change their email address. Users don’t sign themselves up directly with Cognito, requests go through custom workflows.
> […](#)
> Sent from my iPad
> On Aug 12, 2020, at 3:04 PM, sakhmedbayev ***@***.***> wrote: ﻿ @RossWilliams do the end-users sing up/register using their email or username in your system? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Nice! I was thinking in the same direction. Can you demonstrate how you do that exactly or at least outline programming flow?

**Comment by RossWilliams** [comment]
I don’t use the withAuthenticator helpers, everything is custom. The user signs up with a form, I validate data, query outside APIs to validate identities, use adminCreateUser and have Cognito send welcome emails with a temp password.

**Comment by tannerabread** [comment]
Hi 👋 Closing this as resolved. This seems to be an old issue that was not really related to Amplify and there is a supplied workaround.

If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with additional information so we can re-open this issue and be better able to assist you.

Thank you!
