### ISSUE TITLE
@aws-amplify/ui-react withAuthenticator does not pass props like aws-amplify-react withAuthenticator does

### ISSUE THREAD

**Issue by scfox** [aws-amplify/amplify-js#6527]
**Describe the bug**
props are passed after login by the withAuthenticator in aws-amplify-react, but not by withAuthenticator in @aws-amplify/ui-react

**To Reproduce**
Put any component behind each authenticator and print out props passed by each after login.

**Expected behavior**
Same behavior of props being passed. 

** Versions **
aws-amplify-react: 4.1.21
@aws-amplify/ui-react: 0.2.13

**Additional context**
Trying to upgrade to use newer @aws-amplify/ui-react but this difference in behavior breaks existing react components and forces staying on aws-amplify-react

**Comment by sw-yx** [comment]
cc @dabit3 - another issue of breaking changes.

**Comment by jordanranz** [comment]
@scfox, which props are you referring to?

**Comment by cormacc** [comment]
I've run into what seems like symptoms of the same issue while converting a project to typescript...

with..
    "@aws-amplify/ui-react": {
      "version": "0.2.14",


Having tried the following permutations, all giving something like the error below:
export default withAuthenticator(App, true);
export default withAuthenticator(App, {includeGreetings: true});
export default withAuthenticator({Comp: App, includeGreetings: true});

TypeScript error in /home/cormacc/nmd/products/mbt/portals/clinician-portal/src/App.tsx(101,39):
Argument of type 'true' is not assignable to parameter of type '(AmplifyAuthenticator & HTMLAttributes<HTMLAmplifyAuthenticatorElement> & ReactProps & RefAttributes<...>) | undefined'.  TS2345

     99 | 
    100 | /* export default withAuthenticator(App, {includeGreetings: true}); */
  > 101 | export default withAuthenticator(App, true);
        |                                       ^
    102 | // export default App;
    103 | 

I suspect the parameter in App.js was silently being ignored before the typescript conversion, as had just spent a day or two working around a regression introduced by a project library update where Auth.signOut() failed to trigger a UI refresh.

Noticed in one of your comments on this earlier issue @jordanranz that this was a known constraint, and that setting includeGreetings to true enabled a builtin method to trigger the refresh. This was working for me with @aws-amplify/ui-react 0.2.5 previously, but broken with the recent update to 0.2.14, if that's any help in narrowing things down.

(comment here: https://github.com/aws-amplify/amplify-js/issues/4643)

**Comment by dwardu89** [comment]
I've also got this problem with the new one, and i had to revert to the legacy framework.

I created a class and exported as follows

```
export default withAuthenticator(Diary, false, [], null, AuthTheme, signUpConfig);

...
<Diary test="proptest" />
```

the test prop is not being stored in the constructor of the component.

**Comment by amhinson** [comment]
Sorry you are having trouble here! We've updated our docs to be clearer about what has changed with the new UI components. The behavior that you are seeing is by design, as to make the experience between different platforms as consistent as possible. Please see the migration guide for updating to the new library: https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#breaking-changes-for-withauthenticator
