### ISSUE TITLE
GraphQL subscriptions error

### ISSUE THREAD

**Issue by bigxalx** [aws-amplify/amplify-js#6529]
### I am subscribing to a GraphQL onUpdate and it fails to deliver data. 
It does fire when I update data, but only returns errors and no data. 
**`"Cannot return null for non-nullable type: 'AWSDateTime' within parent 'Project' (/onUpdateProject/createdAt)"`**

**To Reproduce**
I use React and the amplify-cli and the provided sample code to create an api and subscribe to updates. 
1. I use the amplify CLI with `amplify add api` with API-key as authorization. I don't change any defaults and let it auto-generate all the necessary files and import them into react. 
This is my schema: 
```
type Project @model {
  id: ID
  title: String
  subtitle: String
  description: String
  onHubs: Boolean
  sceneUrl: String
  rooms: [Room]
  website: String
  email: String
  ownerId: String
  ownerName: String
  ownerBio: String
  approved: Boolean
}
type Room {
  hubsId: String
  userCountLobby: Int
  userCountRoom: Int
} 

```  

2. I use the sample code from https://docs.amplify.aws/lib/graphqlapi/subscribe-data/q/platform/js to subscribe: 

```
function subscribeProjects() {
    try {
      API.graphql(graphqlOperation(onUpdateProject)).subscribe({
        next: (projectData) => console.log("project Data: ", projectData)
      });
    }
    catch (err) {
      console.log("subscription error: ", err)
    }
  }
```
3. I create an entry via graphQL create mutation using the [web interface](https://eu-central-1.console.aws.amazon.com/appsync) from AppSync. 

4. I update the entry via a graphQL mutation using the 
```mutation MyUpdate {
  updateProject(input:{id:"38c32632-f471-4c54-a818-d5a500645fe1", title:"changed title"}){
    title
  }
}
```

5. In almost real-time I get the error in the web inspector console in chrome: 
`"Cannot return null for non-nullable type: 'AWSDateTime' within parent 'Project' (/onUpdateProject/createdAt)"`

**Expected behavior**
It should return the updated data. 

**Additional context**
The original API did have non-nullable fields like ID and title. The error includes any fields that are non-nullable. I updated the API to make all fields optional, but the timestamps are auto-generated and apparently non-nullable as well. 

<details>
  <summary><strong>Environment</strong></summary>

```
  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
    Memory: 38.20 MB / 20.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.16.2/bin/npm
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 75.0
    Safari: 13.1.2
    Safari Technology Preview: 14.0
  npmPackages:
    aws-amplify: ^3.0.20 => 3.0.22 
    aws-amplify-react: ^4.1.21 => 4.1.21 
    gatsby: ^2.23.12 => 2.24.23 
    gatsby-image: ^2.4.9 => 2.4.14 
    gatsby-plugin-create-client-paths: ^2.3.10 => 2.3.10 
    gatsby-plugin-manifest: ^2.4.14 => 2.4.21 
    gatsby-plugin-offline: ^3.2.13 => 3.2.21 
    gatsby-plugin-react-helmet: ^3.3.6 => 3.3.10 
    gatsby-plugin-sass: ^2.3.12 => 2.3.12 
    gatsby-plugin-sharp: ^2.6.14 => 2.6.24 
    gatsby-source-filesystem: ^2.3.14 => 2.3.23 
    gatsby-source-graphql: ^2.6.2 => 2.6.2 
    gatsby-transformer-sharp: ^2.5.7 => 2.5.12 
    node-sass: ^4.14.1 => 4.14.1 
    prettier: 2.0.5 => 2.0.5 
    prop-types: ^15.7.2 => 15.7.2 
    react: ^16.12.0 => 16.13.1 
    react-dom: ^16.12.0 => 16.13.1 
    react-helmet: ^6.1.0 => 6.1.0 
  npmGlobalPackages:
    @aws-amplify/cli: 4.26.0
    firebase-tools: 8.5.0
    npm: 6.14.6```

</details>

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6]
- OS: [e.g. iOS8.1]
- Browser [e.g. stock browser, safari]
- Version [e.g. 22]


**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by user32-2** [comment]
This is due to the fact that the mutation needs to include all the fields that are in the subscription.

**Comment by sammartinez** [comment]
@bigxalx As called out from the above, please follow the steps from the solution in #5115
