### ISSUE TITLE
Datastore.query not fetching updated changes from dynamo

### ISSUE THREAD

**Issue by imoby** [aws-amplify/amplify-js#6537]
**Describe the bug**
I've got a react native app where I am storing data using datastore.save. It successfully gets stored to the local storage as well as the dynamodb app sync. In the scenario where I have this app open in multiple devices, the first device that stored it has access to that record because it is in the local storage.

One the second device, however, when calling datastore.query to refresh and get the latest changes from dynamodb app sync, I am still only getting the current local storage of the second device. I don't have the updated record. I have to force quit the app and reload it (possibly fixed by clearing out the local storage) in order to get the updated record.

I've verified that the datastore conflict resolution is setup properly too. I don't understand why the second device is not recognizing that there are 'updates' in the server side that it needs to pull down to the local storage. I thought this was automatic.

Also, I do have auth setup on my records using cognito auth.

**To Reproduce**

Prerequisites: Setup a amplify datastore for a react native project. Add a function to be able to query and save a record.

1. On device 1, save a record and verify that it shows up in the UI by calling a datastore.query
2. Navigate to the dynamo db and you can see the new record is visible there
3. Go to device 2 and do a refresh by calling datastore.query and see if the updated record is there or not
4. Observe that only the local storage records are pulled and that the updated records are not showing

**Expected behavior**
The expected behavior is that on device 2 when I call datastore.query it should also know if there is an update in the backend dynamodb appsync that it should update the local storage too

**Code Snippet**

**Screenshots**

**What is Configured?**
- React native project
- Datastore
- Auth using cognito

**Smartphone (please complete the following information):**

- Device: iPhone 10s max
- OS: iOS 13

**Additional context**

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by amhinson** [comment]
@imoby Would you be able to provide your `package.json` and some code snippets of your Amplify usage?

**Comment by amhinson** [comment]
Could you also share your schema, or at least a minimal example for reproduction purposes?
