### ISSUE TITLE
Missing white space / margin in Angular Authenticator UI

### ISSUE THREAD

**Issue by WolfWalter** [aws-amplify/amplify-js#6540]
**Describe the bug**
On small screens there is no white space between the "sign in" button and the "Create account" link in the sign-in view. Same problem for the sign-up view with the "Create account" button and "Sign In" link. So it is hard to click the link on a mobile device.

**To Reproduce**
https://docs.amplify.aws/ui/auth/authenticator/q/framework/angular

**Expected behavior**
Mobile friendly UI  with enough white space between clickable elements.

**Screenshots**
![docs amplify aws_ui_auth_authenticator_q_framework_angular (1)](https://user-images.githubusercontent.com/2098069/89737257-eb2c5e80-da6f-11ea-90f7-73920bedee21.png)

**Comment by sammartinez** [comment]
@WolfWalter Can you provide us with what size screen you are experiencing this on?

**Comment by WolfWalter** [comment]
For example on my mobile phone with resolution of 1080 x 2340 pixels: ![Screenshot_20200810-171602.jpg](https://user-images.githubusercontent.com/2098069/89799338-a23adf80-db2d-11ea-83a3-4bd489df3b25.jpg)

**Comment by eddiekeller** [comment]
@WolfWalter This ticket is about 10 months old now. I opened up the link you provided to see the Angular auth component on both my phone and on my laptop simulating a few phones, but I am not seeing the same white spacing issue.

Here is what I see - 
<img width="421" alt="Screen Shot 2021-06-16 at 9 24 52 AM" src="https://user-images.githubusercontent.com/17255334/122257327-c7525a00-ce84-11eb-8351-75343f65be81.png">

It looks like there is a bit more whitespace now between those two clickable elements than what your screenshots provided in the OP show. Has the main issue been resolved for you? Or do you feel that they are still too close together and difficult to interact with?

**Comment by WolfWalter** [comment]
Looks better now.
