### ISSUE TITLE
Apple Signin

### ISSUE THREAD

**Issue by mezalejandro** [aws-amplify/amplify-js#6547]
**Describe the bug**
Hello everyone, I have an app made in react-native and they rejected me for not having login with apple.
I still could not get it to work, I wanted to know which way it should work using https://github.com/invertase/react-native-apple-authentication or using https://medium.com/@irwansyah/supporting-sign-in-with-apple-in-aws-amplify-8fdba766a4a like this?

Thanks

**Comment by amhinson** [comment]
Have you checked out the docs for Social sign in? We've recently added a section for setting up Sign In With Apple: https://docs.amplify.aws/lib/auth/social/q/platform/js

Once that is configured, you should be able to use the Cognito Hosted UI with Apple: `Auth.federatedSignIn({provider: 'SignInWithApple'})`

**Comment by mezalejandro** [comment]
Hi @amhinson I'm currently getting this when trying to log in:
invalid_request  invalid web redirect url

When open the browser the url is: 
https://test.auth.us-east-1.amazoncognito.com/oauth2/authorize?redirect_uri=myapp%3A%2F%2Foauth%2F&response_type=code&client_id=xxxxxx&identity_provider=COGNITO&scopes=phone%2Cemail%2Cprofile%2Copenid%2Caws.cognito.signin.user.admin&state=1hDieceL9mF9fKOWgHQfo7zebQf0tkVL&code_challenge=FdMmtwDKl4kT-sQXtWNkcHuT0tQU64EGkLCREQMFk3w&code_challenge_method=S256

I am following the same as in:
https://docs.amplify.aws/lib/auth/social/q/platform/js

**Comment by mezalejandro** [comment]
In the cognito panel in aws I have the same apple services as the one created in apple with the url configured
![apple_error](https://user-images.githubusercontent.com/568141/90252586-21723100-de16-11ea-93f3-f9374237a557.png)

**Comment by amhinson** [comment]
Would you be able to go through all of the Apple setup steps (https://docs.amplify.aws/lib/auth/social/q/platform/js) again to verify everything is configured correctly?

I would specifically check that you have the appropriate user pool domains in the Apple Developer console for `Domains and Subdomains` and `Return URLs`, and also check that the URL Scheme is setup for your app in `Info.plist`.

**Comment by mezalejandro** [comment]
I have this url configured:
![Screen Shot 2020-08-14 at 11 02 05](https://user-images.githubusercontent.com/568141/90257532-b0cf1280-de1d-11ea-98c8-c2963a4b4407.png)

**Comment by amhinson** [comment]
For the return URL it will also need `/oauth2/idpresponse` at the end

**Comment by mezalejandro** [comment]
I added the /oauth2/idpresponse
When entering my password I get the same error and I fixed the redirect url is this:
https://appleid.apple.com/auth/authorize?client_id=myclientid&
redirect_uri=https%3A%2F%2Ftyc-uat.auth.us-east-1.amazoncognito.com%2Foauth2%2Fidpresponse&

In xcode I have url scheme set.

**Comment by amhinson** [comment]
Unfortunately it is a bit difficult to debug without seeing you're entire configuration, but here a few places to check and compare with the setup docs:
- Is `Sign In With Apple` enabled for the client? App Integration -> App client settings -> Enabled Identity Providers ? There is probably 2 app clients, so be sure to enable it for the web client. 
- Do you have the scopes enabled in the Cognito console -> Federation -> Identity Providers -> Sign In With Apple ?

**Comment by mezalejandro** [comment]
Hello @amhinson I attach images of the configuration:
![Screenshot from 2020-08-18 10-24-39](https://user-images.githubusercontent.com/568141/90527656-27368200-e148-11ea-89d3-3b6bcb29b4b0.png)
![Screenshot from 2020-08-18 10-25-59](https://user-images.githubusercontent.com/568141/90527661-2998dc00-e148-11ea-84aa-59e314592ab3.png)

**Comment by amhinson** [comment]
Just curious, are Facebook and Google working as expected?

**Comment by mezalejandro** [comment]
Facebook and google work perfect

**Comment by amhinson** [comment]
It sounds like there just might be some configuration off in the Apple setup since those are working as expected. I know I said it earlier, but I would go through the [docs](https://docs.amplify.aws/lib/auth/social/q/platform/js) one more time to confirm that every step and value are accounted for. 

Also, could you try changing the `Apple services ID` to your app's bundle ID to see if anything changes?

**Comment by amhinson** [comment]
Just checking in to see if you have any progress updates @mezalejandro

**Comment by mezalejandro** [comment]
Hello @amhinson , first of all I want to thank you for the help.
I was in contact with amazon support and they replied this:
"**As for the error you are getting, one of the causes of the failure happens when the client id you are using is incorrect for signing in on web. This means that you maybe using the primary app's id (iOS app's ID) instead of the services ID. Since the primary app does not have any redirect URLs registered whereas the authorization request contains a redirect URL, it fails validation. To fix this, verify that you are using the services app id in your web authorization / sign-in requests.**"

In Apple developer I have multiple apps, my main app has login enabled:
![Screen Shot 2020-08-25 at 06 58 29](https://user-images.githubusercontent.com/568141/91160926-6d3b9a80-e6a0-11ea-9900-74ddc1825d67.png)

In the other application I did a test to test the login:
![Screen Shot 2020-08-25 at 07 00 19](https://user-images.githubusercontent.com/568141/91161106-ac69eb80-e6a0-11ea-8845-0e4caf1929a1.png)

When editing this app I have it like this:
![Screen Shot 2020-08-25 at 07 00 54](https://user-images.githubusercontent.com/568141/91161179-c86d8d00-e6a0-11ea-8f94-2946859f81df.png)

In Apple developer keys I have this:
![Screen Shot 2020-08-25 at 07 02 34](https://user-images.githubusercontent.com/568141/91161324-010d6680-e6a1-11ea-86b3-9a24d07b1a04.png)

**Comment by amhinson** [comment]
Thanks for that info! Just to clarify, you're still having the issue, correct?

**Comment by mezalejandro** [comment]
Correct, I continue with the problem

**Comment by mezalejandro** [comment]
Hello @amhinson In amazon support it asks me this:
"Could you please confirm the full website URLs that you have registered within your Apple account"
Where do I register the url in apple?

Thanks again

**Comment by amhinson** [comment]
It sounds like they are referring to step 7 & 8 under the "Sign In with Apple" tab: https://docs.amplify.aws/lib/auth/social/q/platform/js#configure-auth-category

**Comment by mezalejandro** [comment]
Hello @amhinson ,
i was in contact with amazon support using amazon chime looking at my desktop and testing cognito the amazon support concluded that the problem is on the apple side.

**Comment by amhinson** [comment]
Ok thanks for the update! We'll keep this issue open for now. Let me know if things get resolved on that side. 🙏

**Comment by mezalejandro** [comment]
Thank you very much I will keep you posted

**Comment by saachitech** [comment]
I have written a small story on how everything should be set up. Here is the [link ](https://medium.com/@saachitech/react-native-social-sign-in-with-apple-and-amplify-6c803b2971d6) if you are interested.

**Comment by mezalejandro** [comment]
Hello @saachitech , can I get in touch with you?
Thanks

**Comment by saachitech** [comment]
> Hello @saachitech , can I get in touch with you?
> Thanks

@mezalejandro of course. Contact me at sameer.jain@saachitech.com Thanks

**Comment by mezalejandro** [comment]
Thank you very much @saachitech  I already sent you the email

**Comment by mezalejandro** [comment]
Hello,
after a long time I think the login with apple works.
Now after logging back to the app but I can't detect if the user is logged in with federated.
![Screen Shot 2020-09-07 at 17 54 28](https://user-images.githubusercontent.com/568141/92416310-3d29d800-f133-11ea-8152-bf18c3c6a0ab.png)
I am following these steps:
https://docs.amplify.aws/lib/auth/social/q/platform/js#configure-auth-category

Thanks

**Comment by mezalejandro** [comment]
Hello,
following the tutorial of @saachitech  by console it returns me this:
![Screen Shot 2020-09-08 at 10 53 09](https://user-images.githubusercontent.com/568141/92485686-a526ff80-f1c1-11ea-9ea5-87deeb033139.png)

Token is not from a supported provider of this identity pool.

Thanks

**Comment by mezalejandro** [comment]
Hello,
at the end of the login with apple and when returning to the app I want to make a request to oauth2 / token https://docs.aws.amazon.com/cognito/latest/developerguide/token-endpoint.html but when doing it from the app it returns invalid_request if I do it from chrome console or postman it works fine.
Any ideas?

**Comment by mezalejandro** [comment]
Something new? amazon support tells me to talk to amplify.
Still not recognized once I am logged in with apple

**Comment by gruckionvit** [comment]
@mezalejandro did you ever manage to fix this issue? I am having the same problem.

**Comment by mezalejandro** [comment]
> @mezalejandro did you ever manage to fix this issue? I am having the same problem. 

Hello, I have this problem since A year and a half

**Comment by gruckion** [comment]
> > @mezalejandro did you ever manage to fix this issue? I am having the same problem.
> 
> Hello, I have this problem since A year and a half

Did you ever manage to fix it?

**Comment by gruckion** [comment]
Still having this issue none of the steps seemed to help.

I am using Expo and AWS Amplify.

https://saachitech.medium.com/react-native-social-sign-in-with-apple-and-amplify-6c803b2971d6

This guide is pretty detailed, but still stuck at this issue.

<img src="https://user-images.githubusercontent.com/4559650/121786305-eb791700-cbb6-11eb-94ab-6ab973276ef5.png" width="40%" />

# Apple setup

## App IDs

![Screenshot 2021-06-12 at 19 56 28](https://user-images.githubusercontent.com/4559650/121786539-495a2e80-cbb8-11eb-8ec9-133b02b8e5ea.png)

![Screenshot 2021-06-12 at 19 57 17](https://user-images.githubusercontent.com/4559650/121786560-65f66680-cbb8-11eb-907b-78d316381ad3.png)

![Screenshot 2021-06-12 at 19 57 38](https://user-images.githubusercontent.com/4559650/121786567-71e22880-cbb8-11eb-9e2d-5f1db14cd718.png)

![Screenshot 2021-06-12 at 19 58 02](https://user-images.githubusercontent.com/4559650/121786574-80304480-cbb8-11eb-836e-fd8989f333cd.png)

## Identifiers

![Screenshot 2021-06-12 at 19 49 55](https://user-images.githubusercontent.com/4559650/121786368-5d516080-cbb7-11eb-981c-d00e2fc85cc4.png)

![Screenshot 2021-06-12 at 19 50 47](https://user-images.githubusercontent.com/4559650/121786398-7c4ff280-cbb7-11eb-905d-ec55076f2246.png)

![Screenshot 2021-06-12 at 19 54 27](https://user-images.githubusercontent.com/4559650/121786491-ff714880-cbb7-11eb-98ab-8a0167be0934.png)

The values are of the screen so I clicked the copy button and pasted below

> mycompany-dev-fe82833d-f388-40d7-ac21-cc365a900749.auth.eu-west-2.amazoncognito.com
> https://mycompany-dev-fe82833d-f388-40d7-ac21-cc365a900749.auth.eu-west-2.amazoncognito.com/oauth2/idpresponse

## Keys

![Screenshot 2021-06-12 at 19 59 25](https://user-images.githubusercontent.com/4559650/121786596-b1a91000-cbb8-11eb-91e8-e2ab3ce841f7.png)

![Screenshot 2021-06-12 at 20 00 05](https://user-images.githubusercontent.com/4559650/121786604-c9809400-cbb8-11eb-9c9e-3a5735a8e2e1.png)

![Screenshot 2021-06-12 at 20 00 32](https://user-images.githubusercontent.com/4559650/121786613-da310a00-cbb8-11eb-881a-2239083f7b81.png)

![Screenshot 2021-06-12 at 20 23 38](https://user-images.githubusercontent.com/4559650/121787096-13b74480-cbbc-11eb-8a88-c0099e788c30.png)

# Cognito setup

## App integration

![Screenshot 2021-06-12 at 20 25 25](https://user-images.githubusercontent.com/4559650/121787133-52e59580-cbbc-11eb-80b4-8b76cd80ddb0.png)

![eu-west-2 console aws amazon com_cognito_users_region=eu-west-2 (1)](https://user-images.githubusercontent.com/4559650/121786790-14e77200-cbba-11eb-8c9d-1dc2b1566086.png)

## Federation

![eu-west-2 console aws amazon com_cognito_users_region=eu-west-2 (2)](https://user-images.githubusercontent.com/4559650/121786834-5841e080-cbba-11eb-9619-deec42348190.png)

![eu-west-2 console aws amazon com_cognito_users_region=eu-west-2 (4)](https://user-images.githubusercontent.com/4559650/121786882-9c34e580-cbba-11eb-8f13-eee9961e5511.png)

## Federated Identities

![eu-west-2 console aws amazon com_cognito_pool__region=eu-west-2 id=eu-west-2_4bd525ff-fc50-4bd6-a518-407a0443eb13](https://user-images.githubusercontent.com/4559650/121786934-d900dc80-cbba-11eb-894d-b27c58e3ca8f.png)

![eu-west-2 console aws amazon com_cognito_pool_edit__region=eu-west-2 id=eu-west-2_4bd525ff-fc50-4bd6-a518-407a0443eb13](https://user-images.githubusercontent.com/4559650/121786984-3d23a080-cbbb-11eb-8340-10bf9a488636.png)

# What on Earth am I missing here?

If I use my Expo React-native app or the Hosted UI for the `mycompany3b358f8b_app_clientWeb`

![Screenshot 2021-06-12 at 20 18 39](https://user-images.githubusercontent.com/4559650/121786997-617f7d00-cbbb-11eb-854f-0fc4e1e72e07.png)

![Screenshot 2021-06-12 at 20 19 11](https://user-images.githubusercontent.com/4559650/121787005-765c1080-cbbb-11eb-8a2c-efb8a158c4a7.png)

- Google works
- Facebook works
- Apple 

![Screenshot 2021-06-12 at 20 20 04](https://user-images.githubusercontent.com/4559650/121787025-94c20c00-cbbb-11eb-8067-cc0f2667c96d.png)

Just can't see what I am doing wrong here.

**Comment by gruckion** [comment]
> > @mezalejandro did you ever manage to fix this issue? I am having the same problem.
> 
> Hello, I have this problem since A year and a half

@mezalejandro Did you manage to fix it in the end?

**Comment by gruckion** [comment]
Oh my god... I fixed it jesus that was annoying. So you have the app identifier `com.mycompany.something` and you have the identifier you entered got the service which for me I just added sid on the end `com.mycompany.something.sid`

**MAKE SURE YOU USE THE SERVICE IDS IDENTIFIER!** Not the app identifier.
