### ISSUE TITLE
Support Nuxt.js (Vue) also along with Next.js (React) for SSR 

### ISSUE THREAD

**Issue by IamManchanda** [aws-amplify/amplify-js#6549]
I looked at this milestone https://github.com/aws-amplify/amplify-js/milestone/26

Would request to please also support Nuxt.js along with Next.js for SSR 

https://nuxtjs.org/
https://github.com/nuxt/nuxt.js

**Comment by funkel1989** [comment]
@IamManchanda  the latest amplify releases says it supports nuxt but I can't seem to figure out how to make it all work. Might just be because I'm new to amplify but curious if you've tried yet?

**Comment by amhinson** [comment]
@IamManchanda @funkel1989 Have you seen @dabit3's recent blog post about adding Amplify auth to a Nuxt app?
https://dev.to/aws/adding-authentication-to-a-nuxt-app-with-aws-amplify-2n84

**Comment by funkel1989** [comment]
@amhinson I just looked at it and it looks very similar to what I'm doing but not exactly what I'm looking for. I'm looking to run nuxt in SSR mode and configure page hydration to be done by a lambda or whatever backend infrastructure amplify would spin up for it.

I'm looking to do a deployment like this, only with amplify owning my backend.
https://github.com/tonyfromundefined/nuxt-serverless

In that example it's all done with lambda's but I could care less if it was EKS ECS EC2 Lambda or anything else.

**Comment by nadetastic** [comment]
With Amplify JS v6 we provide an adapter for only Next.js with documentation on how to implement it that can be found here - https://docs.amplify.aws/react/build-a-backend/server-side-rendering/nextjs/

Additionally we provide generic adapters that may be used with other frameworks. You can find documentation on how to use the generic adapters with Nuxt 3 here - [docs.amplify.aws/react/build-a-backend/server-side-rendering/nuxt](https://docs.amplify.aws/react/build-a-backend/server-side-rendering/nuxt/)
