### ISSUE TITLE
Auth.currentSession is not refreshing the idToken

### ISSUE THREAD

**Issue by BFUculsion** [aws-amplify/amplify-js#6553]
**Describe the bug**
On my machine:
  return Auth.currentSession().then((sessionData) => {
      const now = Date.now();
      const { idToken } = sessionData;
      const remaining = (idToken.getExpiration() * 1000) - now;
      console.error(remaining);
      const expired = remaining < 1;
      if (expired) {
        console.error("Id token is expired, and didn't auto refresh");
        throw new Error('Id token is expired. It should be auto refreshed');
      }

Is consistently throwing the error for expired token. This is after a fresh login. From what the docs (and other bugs say) amplify is supposed to automatically refresh the id token before returning.

This is the age I'm getting back for remaining: index.js:1 -21600619 or 2160 seconds

Windows Chrome 84

**Comment by lucasMobee** [comment]
Has anyone seen any progress here? I'm running into a similar issue, trying to get https://docs.amplify.aws/lib/auth/manageusers/q/platform/js#retrieve-current-authenticated-user to work as described and refresh the session.

Given what the doc states, are there any known examples of this working? Everything else I've seen relies on using AWS global to configure the credentials, which we don't do in our project.

**Comment by sammartinez** [comment]
@BFUculsion, Can you provide your `package.json` along with your environment settings? 

Please use the follow command: 
```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

Thanks ahead of time!

**Comment by BFUculsion** [comment]
Sure, it's attached to this email  





On Mon, Oct 5, 2020 3:35 PM, Sam Martinez notifications@github.com  wrote:


@BFUculsion, Can you provide your package.json  along with your environment
settings?

Please use the follow command:

npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages


Thanks ahead of time!

**Comment by hellaeon** [comment]
Hey there, I am getting this as well. My refresh token is 60 minutes, ID and Access are 5 minutes. When I call the 'currentSession' it fails to update the ID and access tokens. Did you find out what it was?

**Comment by hisham** [comment]
I've been getting refresh token expired issues as well from time to time. We've been telling users to refresh their page then it all works out. Haven't investigated more than that.

**Comment by BFUculsion** [comment]
> @BFUculsion, Can you provide your `package.json` along with your environment settings?
> 
> Please use the follow command:
> 
> ```
> npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
> ```
> 
> Thanks ahead of time!

Hi, Did you get what you needed from me? Thanks, Ben

**Comment by disrael** [comment]
Will https://github.com/aws-amplify/amplify-js/pull/7288 fix this?

**Comment by sammartinez** [comment]
The above pull request resolves this issue. Resolving as the above fix is in our latest version
