### ISSUE TITLE
Sapper + AWS, GraphQL No Cognito Identity Pool.

### ISSUE THREAD

**Issue by michaelcuneo** [aws-amplify/amplify-js#6575]
**Describe the bug**
I have an Amplify stack setup that I've been using successfully for months in a React.JS Project.

Just copied the aws-exports.js over to a Svelte project, and I can successfully perform a data retrieval, but it gets stuck with the following.

```
GraphQLAPI - ensure credentials error No Cognito Identity pool provided for unauthenticated access ... etc.
UnhandledPromiseRejectionWarning: Error: No credentials ... etc.
```

If I look into the network tab of Developer Tools, I actually have data returned from the GraphQL request, which is valid data, but it won't give it to me.

I also get a successful IdentityId and Logins from https://cognito-identity.ap-southeast-2.amazonaws.com/ ... so it looks like it should be all working... it just isn't.

**To Reproduce**

Install a sapper environment.
Add aws-amplify.
Add aws-exports.
Configure aws-exports like usual.
Make a call to API.graphql.

**Expected behavior**
Data.

**Code Snippet**
```
<script>
  import { API, graphqlOperation } from 'aws-amplify';

  async function getProjects() {
    const res = await API.graphql(graphqlOperation(listProjects, { limit: 7 }));
    if (res.ok) {
      return await response.json()
    } else {
      throw new Error(text);
    }
  }

  let promise = getProjects();
</script>

<project>
    {#await promise}
      <h1>Loading</h1>
    {:then data}
      {console.log(data)} // Nothing returned here.
      <ProjectContainer project={data} />
    {/await}
</project>
```

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.
* Which resources do you have configured?
  * If applicable, please provide your `aws-exports` file:
   ```
const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:xxxxxxxx",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_alVUaTXyY",
    "aws_user_pools_web_client_id": "3gash2c892q68f2auc02kfh3dl",
    "oauth": {},
    "aws_content_delivery_bucket": "fastlab-20200211165358-master-hostingbucket-master",
    "aws_content_delivery_bucket_region": "ap-southeast-2",
    "aws_content_delivery_url": "https://d1dsftccszhbqu.cloudfront.net",
    "aws_appsync_graphqlEndpoint": "https://auoto3ziwvhb3p4zintlrncac4.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "AWS_IAM",
    "aws_user_files_s3_bucket": "fastlab-master-20190705141744-storage164059-master",
    "aws_user_files_s3_bucket_region": "ap-southeast-2"
};

   ```
* If applicable, provide more configuration data, for example for Amazon Cognito, run `aws cognito-idp describe-user-pool --user-pool-id us-west-2_xxxxxx` (Be sure to remove any sensitive data)
 
<details>
  <summary><strong>Environment</strong></summary>
```
  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (24) x64 Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz
    Memory: 3.50 GB / 23.43 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v10.16.3/bin/npm
  npmPackages:
    @fortawesome/free-solid-svg-icons: ^5.14.0 => 5.14.0
    aws-amplify: ^3.0.23 => 3.0.23
    compression: ^1.7.1 => 1.7.4
    fa-svelte: ^3.1.0 => 3.1.0
    lodash: ^4.17.20 => 4.17.20
    npm-run-all: ^4.1.5 => 4.1.5
    polka: next => 1.0.0-next.11
    sanitize.css: ^11.0.1 => 11.0.1
    sapper: ^0.28.0 => 0.28.0
    sirv: ^1.0.0 => 1.0.6
    svelte: ^3.17.3 => 3.24.1
    svelte-loader: ^2.9.0 => 2.13.6
    webpack: ^4.7.0 => 4.44.1
    webpack-modules: ^1.0.0 => 1.0.0
  npmGlobalPackages:
    @aws-amplify/cli: 4.27.1
    aws-amplify-react: 4.1.22
    aws-amplify: 3.0.23
    docsify-cli: 4.4.0
    gatsby-cli: 2.7.49
    jshint: 2.11.0
    npm: 6.14.7
    react-360-cli: 1.1.0
    serverless: 1.65.0
```
</details>

**Comment by bigxalx** [comment]
I am experiencing the same issue -- but only when running a gatsby.js site in production on first load -- when I run the same code by opening the react app at a different route and then navigating to the affected component, there is no error. 
I'm by all means no expert but, but this leads me to suspecting that the issue is related to dehydration or similar.

**Comment by bigxalx** [comment]
> I am experiencing the same issue -- but only when running a gatsby.js site in production on first load -- when I run the same code by opening the react app at a different route and then navigating to the affected component, there is no error.
> I'm by all means no expert but, but this leads me to suspecting that the issue is related to dehydration or similar.

Turns out I didn't import aws-export in the right component component. Importing it in a parent of the affected component made solved the error.

**Comment by michaelcuneo** [comment]
Yes, this is the exact same issue here... but I believe I'm at the lowest part here that I can possibly be.

**Comment by sammartinez** [comment]
Hey @michaelcuneo, apologizes for the late response here, I do want to callout that I am treating this as a feature request as we do not support currently for Sapper nor Svelte within Amplify JS.

**Comment by michaelcuneo** [comment]
Since posting to this issue I have found that the issue was the lack of import and initialisation of both sides of the Sapper architecture. Sapper runs a Server and Client. Both server.js and client.js need to be set up with the aws-exports config, and the relative login and or hub response need to be synchronised through the Svelte/Sapper store between both sides.

Since this fix, the functionality is seamless.

**Comment by michaelcuneo** [comment]
i.e. place the following into both server.js and client.js within the Sapper App.

```
import Amplify from 'aws-amplify';
import aws_exports from './aws-exports';

Amplify.configure(aws_exports);
```

Then the client and server are both set up to use the authentication.

Subsequently, the sapper.start, and polka().use in each client and server respectively can be used to sync any response from amplify hub to rehydrate login.
