### ISSUE TITLE
Slot for loading text for amplify-authenticator component

### ISSUE THREAD

**Issue by srchulo** [aws-amplify/amplify-js#6577]
**Is your feature request related to a problem? Please describe.**
After a user logs in, I see a "Loading..." flash in the top left.

**Describe the solution you'd like**
It would be great if there was a slot where we could put the loading content that we want, like the slots here:

https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue#slots

**Describe alternatives you've considered**
I've done a very hacky thing to hide the "Loading..." text by making the color of text white and then then black again for a more specific div:

```
amplify-authenticator {
    color: white;
}

div#innerApp {
    color: #000000;
}
```

**Comment by amhinson** [comment]
@srchulo It looks like there is a slot `loading` for the loading component. Does this work for you? https://github.com/aws-amplify/amplify-js/blob/main/packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx#L177

**Comment by srchulo** [comment]
@amhinson that worked, thanks! Looks like maybe it just needs documented?

**Comment by amhinson** [comment]
Good call! We'll get this merged soon :) 
https://github.com/aws-amplify/docs/pull/2244
