### ISSUE TITLE
Auth.currentAuthenticatedUser() returns different sub in user attributes than in idToken payload

### ISSUE THREAD

**Issue by KristineTrona** [aws-amplify/amplify-js#6578]
**Describe the bug**
Calling ``Auth.currentAuthenticatedUser()`` returns different sub values in ``idToken.payload`` and in ``attributes``

**Expected behavior**
The sub should be the same. Currently I am creating a user in database using the sub in ``attributes`` for the id. This causes issues as the id does not match the sub in Cognito console (cognito console user's sub matches ``idToken.payload.sub``). Did not experience this issue before package update. 

**Screenshots**
<img width="457" alt="Screenshot 2020-08-14 at 11 15 19" src="https://user-images.githubusercontent.com/39855778/90238754-b846e980-de26-11ea-8c9d-ea4026107012.png">

**Configuration**
amplify CLI version 4.17.1
```
    "aws-amplify": "^3.0.23",
    "aws-amplify-react-native": "^4.2.4",
    "amazon-cognito-identity-js": "^4.3.3",
    "react-native": "0.62.2",
```

Before package update:  
```
"aws-amplify": "^1.1.23",
"aws-amplify-react-native": "^2.1.9",
```

**Comment by elorzafe** [comment]
@KristineTrona when you used the previous version with the same user, which sub are you getting, the one from the idToken or the one from the user attributes?

**Comment by elorzafe** [comment]
@KristineTrona are you doing identity merging?

The user is authenticating with username and password or is doing federatedSignIn?

**Comment by KristineTrona** [comment]
@elorzafe I am not doing identity merging or using feredatedSignIn.  The user is signing up and initially being logged in using username and password, after that all authentication happens with CUSTOM_AUTH, where user authenticates using phone number and a code that is sent to it.

**Sign up**
```
// Create random string as password
const password = randomize('*', 32);

// This initializes the sign up and sends a confirmation code to the user
 await Auth.signUp({
    username: phone,
    password,
  });


// Later on in the code - confirm sign up with code sent to the user
  await Auth.confirmSignUp(username, code, {
      forceAliasCreation: true
  });

// Automatically log user in:
  await Auth.signIn(username, password)

// Get current authenticated user:
const currentUser = await Auth.currentAuthenticatedUser();

```

I think it is some kind of caching issue, because I found how to reproduce the issue:
1. Create a new user - first time both ``sub`` values are identical.
2. Delete the created user in cognito console.
3. Create a new user through the app - the ``sub`` value in ``attributes`` now matches the user that was deleted in console earlier, and the ``sub`` value in ``idToken`` payload matches the currently created new user. 
4. Also if you simply log out and log in now, the ``sub`` value in ``attributes`` matches the deleted user from the console.

**Comment by mauerbac** [comment]
Hey @KristineTrona - sorry for the delay here. Let us know if you are still looking for support here.

**Comment by KristineTrona** [comment]
@mauerbac I've checked in a different app that I am working on using ` "aws-amplify": "^3.2.0"` and the issue is not present there, so whatever it was is either fixed by now or specific to that userpool. I think this issue can be closed.

**Comment by nickarocho** [comment]
Thanks for verifying @KristineTrona. I'll close the issue now but if you notice this happening again please feel free to reopen and let us know.
