### ISSUE TITLE
Add a way to read text from file retrieved from s3

### ISSUE THREAD

**Issue by asatvilker** [aws-amplify/amplify-js#6582]
**Is your feature request related to a problem? Please describe.**
When using amplify storage you can use method .get() and retrieve a file. If you use the parameter {download:true} you get an object returned. Using chrome on desktop you can use a method .text() which then returns a promise and when you resolve it you get the contents of the file as a string. Heres an example:

`Storage.get(‘welcome.txt`, {download:true})
.then(result => {result.Body.text().then(string => console.log(string))})`

This would return the contents of the file without the need for a file reader or any other library so it is extremely useful *however*, this method isn’t available in all browsers! .text() is not recognised on mobile devices or safari which is very frustrating as it is so beneficial 

**Describe the solution you'd like**
Please you could add this .text() function to all browsers so we can make use of this brilliant capability. It will improve the capability of amplify so much to be able to read the contents of a file so easily with no additional work needed. Plus the method already exists, i just ask if it can be made available for all browsers to really make use of it

Thank you, adam

**Comment by kvramyasri7** [comment]
Sorry for the late response. I have tested the issue in Safari / Firefox currently .text() method is being supported in the browsers. Please take a look at [Browser Compatibility](https://developer.mozilla.org/en-US/docs/Web/API/Response/text#browser_compatibility).

**Comment by kvramyasri7** [comment]
This issue has been opened a while back and the recent investigation shows that the issue is resolved.
