### ISSUE TITLE
DataStore with OIDC results in No federated jwt error

### ISSUE THREAD

**Issue by getglad** [aws-amplify/amplify-js#6585]
**Describe the bug**
I have a GraphQL API with an OIDC provider configured with an `@auth` schema of
`@auth(rules: [{ allow: owner, provider: oidc, identityClaim: "sub" }])`

I also have a successful auth flow (far as I can tell) using `Auth.federatedSignIn` combined with Auth0 (code snippet below).

When I try to use the `DataStore.save` method, it saves locally but starts to throw `No federated jwt` errors in the console.

When I use `@auth(rules: [{ allow: public }])` with the API Key, that works fine, so I'm fairly confident my `DataStore` code is correct.

My issue is very similar to this issue - https://github.com/aws-amplify/amplify-js/issues/5399, but the fix (setting `federatedInfo` through the `Cache.setItem`) sets the key in `localstorage`  different (`aws-amplify-federatedInfo` vs `aws-amplify-cachefederatedInfo`) and saves with a different schema. It does, however, result in a different error - I get several `The connection to {appsyc_api} was interrupted while the page was loading.` and finally a `Error: UnauthorizedException`.

Not sure what would cause Cognito to accept but AppSync to reject the token - but also not sure why inserting into the cache like that would result in a different (but still erroring) outcome.

I can share more, but not exactly sure what else is useful to troubleshoot.

```
Auth.federatedSignIn(
   domain
   {
      token:  raw_token,
      expires_at: exp * 1000
   },
   {
      name
   }
).then(cred => {
   console.log(cred); // assuming when I see this log Amplify is happy
   const fed = Cache.getItem('federatedInfo');
   if (fed === null) {
      Cache.setItem('federatedInfo', { token: raw_token });
   }
   DataStore.start();
}).catch(error => {
   console.log(error);
});
```

Auth configuration object
```
 {
    // REQUIRED only for Federated Authentication - Amazon Cognito Identity Pool ID
    identityPoolId: 'us-east-1:{federated-pool-id}',

    // REQUIRED - Amazon Cognito Region
    region: 'us-east-1',
}
```

Amplify CLI version: 4.27.0
DataStore version: 2.2.9

**Comment by getglad** [comment]
To follow up on this - came across this on StackOverflow - https://stackoverflow.com/questions/62281582/appsync-oidc-with-auth0-as-authorisation-returns-unauthorised -  can confirm that it fixes. So that one is due to my Auth0 vs AppSync configuration and was easy to fix once the problem is understood.

So to summarize...

1) Setting `Cache.setItem('federatedInfo', { token: raw_token });` fixes the `No federated jwt`
2) Removing `authTTL` and `iatTTL` from the AppSync settings fixes the `Error: UnauthorizedException` 

Reading some tea leaves, I am wondering if `Auth.federatedSignIn` is writing to the localstorage key of  `aws-amplify-federatedInfo`, but something in `DataStore` is expecting to read from `aws-amplify-cachefederatedInfo` - so possibly a bug?

And the `authTTL` / `iatTTL` may be worth a call out in the "Federate with Auth0" section of the Amplify documentation - https://docs.amplify.aws/lib/auth/advanced/q/platform/js#federate-with-auth0

**Comment by getglad** [comment]
One more follow up - my best guess is the issue is this line here - https://github.com/aws-amplify/amplify-js/blob/main/packages/datastore/src/sync/processors/subscription.ts#L260

Possible that `Auth` library is using a different write mechanism than `Cache.setItem` which produces the cache miss when `DataStore` pulls with `Cache.getItem`?

**Comment by mauerbac** [comment]
As noted, will mark this as need discussion. Thanks @getglad
