### ISSUE TITLE
Metrics from  Analytics.updateEndpoint() not showing up in AWS Pinpoint

### ISSUE THREAD

**Issue by ecomonestop** [aws-amplify/amplify-js#6589]
**Describe the bug**
When I included the metrics object in a call to Analytics.updateEndpoint(), it is not showing up in AWS Pinpoint Segmentation; thus, I'm not able to use it.  However, in debug mode, I can see that Analytics.updateEndpoint() has the metrics object and is "successful", but since it doesnt show up in segmentation of Pinpoint, I dont see why this is "successful" as I cant use this metric.

**To Reproduce**

1. call Analytics.updateEndpoint() with metrics object
2. go to create segment in AWS pinpoint and you will not find this metric

**Expected behavior**
I expect if I record a metric using Analytics.updateEndpoint() that I can use it when creating segments in AWS pinpoint.

**Code Snippet**
```
await Analytics.updateEndpoint({
      ...
      metrics: { minutesListened: 30 }
    })
```

**Comment by sammartinez** [comment]
@ecomonestop, Can you provide your `package.json` along with your environment settings? 

Please use the follow command: 
```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

Thanks ahead of time!

**Comment by ecomonestop** [comment]
Sorry for the delay:

 System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz  
    Memory: 2.48 GB / 7.92 GB
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE       
    Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
    Internet Explorer: 11.0.18362.1
  npmPackages:
    @aws-amplify/analytics: ^3.2.2 => 3.2.2 
    @aws-amplify/api: ^3.1.18 => 3.1.18 
    @aws-amplify/auth: ^3.3.0 => 3.3.0 
    @aws-amplify/cache: ^3.1.19 => 3.1.19 
    @aws-amplify/core: ^3.4.1 => 3.4.1 
    @aws-amplify/ui-react: ^0.2.8 => 0.2.9 
    @material-ui/core: ^4.10.0 => 4.10.2 
    @material-ui/icons: ^4.9.1 => 4.9.1 
    @material-ui/lab: ^4.0.0-alpha.56 => 4.0.0-alpha.56
    @mdx-js/mdx: ^1.6.13 => 1.6.13
    @mdx-js/react: ^1.6.13 => 1.6.13
    @stripe/react-stripe-js: ^1.1.2 => 1.1.2
    @stripe/stripe-js: ^1.8.0 => 1.8.0
    classnames: ^2.2.6 => 2.2.6
    formik: ^2.1.4 => 2.1.4
    formik-material-ui: ^2.0.0-beta.1 => 2.0.1
    gatsby: ^2.21.37 => 2.23.12
    gatsby-background-image: ^1.1.1 => 1.1.1
    gatsby-image: ^2.4.4 => 2.4.9
    gatsby-plugin-canonical-urls: ^2.3.8 => 2.3.8
    gatsby-plugin-create-client-paths: ^2.3.10 => 2.3.10
    gatsby-plugin-facebook-pixel: ^1.0.3 => 1.0.3
    gatsby-plugin-google-gtag: ^2.1.10 => 2.1.10
    gatsby-plugin-manifest: ^2.4.5 => 2.4.14
    gatsby-plugin-material-ui: ^2.1.9 => 2.1.9
    gatsby-plugin-mdx: ^1.2.28 => 1.2.28
    gatsby-plugin-offline: ^3.2.3 => 3.2.13
    gatsby-plugin-react-helmet: ^3.3.1 => 3.3.6
    gatsby-plugin-s3: ^0.3.3 => 0.3.3
    gatsby-plugin-sharp: ^2.6.4 => 2.6.14
    gatsby-source-filesystem: ^2.3.4 => 2.3.14
    gatsby-transformer-sharp: ^2.5.2 => 2.5.7
    perfect-scrollbar: ^1.5.0 => 1.5.0
    prettier: 2.0.5 => 2.0.5
    prop-types: ^15.7.2 => 15.7.2
    react: ^16.12.0 => 16.13.1
    react-dom: ^16.12.0 => 16.13.1
    react-helmet: ^6.0.0 => 6.1.0
    react-toastify: ^6.0.5 => 6.0.6
    yup: ^0.29.1 => 0.29.1
  npmGlobalPackages:
    @angular/cli: 8.3.8
    @aws-amplify/cli: 4.27.2
    gatsby-cli: 2.8.19
    gatsby: 2.18.8
    lerna: 3.22.0
    live-server: 1.2.0
    npm: 6.13.4
    serve: 11.2.

**Comment by CryogenicPlanet** [comment]
Reproduction sample repository https://github.com/CryogenicPlanet/amplify-6589

**Comment by mauerbac** [comment]
Hey @ecomonestop - I checked with the pinpoint product team and they confirmed that while you can created segments from the API/SDK but you cannot view these metrics in the UI. I've added this as a FR to the pinpoint team. The main use for this is updating the endpoint user id, so it should work as intended for updating things like endpoint profile data like demographic, device name, user-agent etc.

What is your use case? Will close for now.
