### ISSUE TITLE
Can't theme amplify-loading-spinner icon with CSS variables

### ISSUE THREAD

**Issue by neojp** [aws-amplify/amplify-js#6590]
**Describe the bug**
The `<amplify-loading-spinner>` icon's color is hardcoded to orange `#ff9900` which is the value of the CSS variable `--amplify-primary-color`. This color should be passed over from the theme's CSS as a variable.

If we were to set the CSS variable `--amplify-primary-color` to blue, the spinner should show up as that color. Right now it shows up as orange because the value is hard-coded into the SVG markup with a `fill` attribute.

**Note:** See screenshots below.

**To Reproduce**

1. Setup an `<amplify-authenticator>` component
2. Set your primary color to a custom color `:root { --amplify-primary-color: #10109e; }`
2. Click on 'Sign in'
3. The loading spinner icon inside the button will appear as orange

**Expected behavior**
The spinner icon should be blue.

**Code Snippet**
```css
:root {
  --amplify-primary-color: #10109e;
}
```

**Screenshots**
Default theme:
![image](https://user-images.githubusercontent.com/127994/90326896-188b7780-df5c-11ea-8503-b425eab9436b.png)

Custom theme:
![image](https://user-images.githubusercontent.com/127994/90327044-a320a680-df5d-11ea-8e99-3dd02c75fbaf.png)

Expected result:
![image](https://user-images.githubusercontent.com/127994/90327066-d2cfae80-df5d-11ea-8a1a-52251e755a54.png)

Hardcoded color in SVG:
![image](https://user-images.githubusercontent.com/127994/90326954-ab2c1680-df5c-11ea-85cc-c36eb67fffe6.png)

**What is Configured?**
* Amplify UI Authentication component

<details>
  <summary><strong>Environment</strong></summary>

```
System:
    OS: Linux 4.19 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (32) x64 AMD Ryzen Threadripper 2950X 16-Core Processor
    Memory: 351.05 MB / 7.77 GB
    Container: Yes
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.12.0 - /usr/bin/npm
  npmPackages:
    @aws-amplify/ui-vue: ^0.2.8 => 0.2.8 
    @neojp/tailwindcss-aspect-ratio-utilities: ^1.0.1 => 1.0.1 
    @neojp/tailwindcss-important-variant: ^1.0.1 => 1.0.1 
    @nuxtjs/axios: ^5.11.0 => 5.11.0 
    @nuxtjs/eslint-config: ^2.0.0 => 2.0.2 
    @nuxtjs/eslint-module: ^1.0.0 => 1.2.0 
    @nuxtjs/markdownit: ^1.2.9 => 1.2.9 
    @nuxtjs/pwa: ^3.0.0-beta.20 => 3.0.0-beta.20 
    @nuxtjs/router: ^1.5.0 => 1.5.0 
    @nuxtjs/stylelint-module: ^3.1.0 => 3.2.2 
    @nuxtjs/tailwindcss: ^2.0.0 => 2.0.0 
    @vimeo/player: ^2.12.2 => 2.12.2 
    aws-amplify: ^3.0.18 => 3.0.18 
    babel-eslint: ^10.0.1 => 10.1.0 
    dotenv-safe: ^8.2.0 => 8.2.0 
    eslint: ^6.1.0 => 6.8.0 
    eslint-config-prettier: ^6.11.0 => 6.11.0 
    eslint-plugin-nuxt: >=0.4.2 => 1.0.0 
    eslint-plugin-prettier: ^3.1.4 => 3.1.4 
    fuse.js: ^6.4.0 => 6.4.0 
    humps: ^2.0.1 => 2.0.1 
    moment: ^2.27.0 => 2.27.0 
    node-sass: ^4.14.1 => 4.14.1 
    nuxt: ^2.13.0 => 2.13.0 
    prettier: ^1.19.1 => 1.19.1 
    sass-loader: ^8.0.2 => 8.0.2 
    stylelint: ^10.1.0 => 10.1.0 
    tailwindcss-children: ^2.1.0 => 2.1.0 
    vue-clickaway: ^2.2.2 => 2.2.2 
    vue-moment: ^4.1.0 => 4.1.0 
    wpautop: ^1.0.0 => 1.0.0 
  npmGlobalPackages:
    @aws-amplify/cli: 4.21.0
    flow-bin: 0.125.1
    npm-check-updates: 7.0.1
    npm: 6.12.0
    pnpm: 5.4.0
```

</details>

**Desktop:**

- Device: Desktop PC
- OS: Windows 10
- Browser: Microsoft Edge
- Version 85.0.564.30 (Official build) beta (64-bit)

**Additional context**

Icon with the hard-coded `fill` attribute:

https://github.com/ashika01/amplify-js/blob/master/packages/amplify-ui-components/src/components/amplify-icon/icons.tsx#L169

**Comment by jordanranz** [comment]
Hey @neojp, could you try using the latest version of the `@aws-amplify/ui-vue` package? This should be fixed in that version.

**Comment by neojp** [comment]
I can confirm it's working with the current version of `@aws-amplify/ui-vue@0.2.15` . Thank you @jordanranz!

![image](https://user-images.githubusercontent.com/127994/92037085-3f5cf280-ed3f-11ea-98dd-067f9e861ab1.png)
