### ISSUE TITLE
DataStore SYNC query builder does not allow/include filter by owner

### ISSUE THREAD

**Issue by abdielou** [aws-amplify/amplify-js#6595]
**Describe the bug**
The DataStore is not including the `owner` as part of the sync query. Unless this is a limitation on how AppSync implements/expects sync, I think this is a BUG and causes scalability issues.

**To Reproduce**
1. Install and init
2. Implement a simple schema with type having `@model` and `@auth`
3. Configure @auth to include owner
4. Configure DataStore

**Expected behavior**
The DataStore internally builds all queries and mutations. Since we have @auth with owner, it is expected that the `owner` field is populated on all queries, including sync queries. This is not the case.

**Code Snippet**
Here's where the SYNC query is built. The query does not allows for passing `filter`.
https://github.com/aws-amplify/amplify-js/blob/main/packages/datastore/src/sync/utils.ts#L268-L278
```graphql
   documentArgs = `($limit: Int, $nextToken: String, $lastSync: AWSTimestamp)`;
```

**Comment by abdielou** [comment]
Let me expand on scalability. Since authorization filters are implemented on the Response Resolver, the result set to be filtered upon might or not include authorized items. Thus, the client can find itself getting 0 items after a sync event even though the actual query did hit 1k items, but the response resolver filtered them all out. By default the DataStore limits to 1k items for sync per page. For very small apps with few users, this can work as long as the items created by other users do not exceed 1k in between syncs. This won't obviously work on bigger payloads.

**Comment by abdielou** [comment]
The solution is simple, include a filter with the `owner`.

**Comment by mauerbac** [comment]
hi @abdielou - thanks for reaching out. Would you be able to share the schema that you are using here? What is the default auth mode that you are using ? 

In the meantime, this workaround might be helpful -> https://github.com/aws-amplify/amplify-js/issues/5687#issuecomment-631185661

**Comment by abdielou** [comment]
> hi @abdielou - thanks for reaching out. Would you be able to share the schema that you are using here? What is the default auth mode that you are using ?

```graphql
type Channel
  @model
  @auth(rules: [
    { allow: owner }
  ])
{
  id: ID!
  description: String
  owner: String
}
```

**Comment by abdielou** [comment]
Adding the `owner` field won't help anyway. The code does not consider ownership when building the SYNC query.

> **Code Snippet**
> Here's where the SYNC query is built. The query does not allows for passing `filter`.
> https://github.com/aws-amplify/amplify-js/blob/main/packages/datastore/src/sync/utils.ts#L268-L278
> 
> ```graphql
>    documentArgs = `($limit: Int, $nextToken: String, $lastSync: AWSTimestamp)`;
> ```

**Comment by mauerbac** [comment]
Thank you for providing this. To understand the full picture, it would be helpful to know the default auth mode you are using?

**Comment by abdielou** [comment]
> Thank you for providing this. To understand the full picture, it would be helpful to know the default auth mode you are using?

Oh, apologies I did not understood the question. I had selected Cognito User Pool.

<img width="591" alt="Screen Shot 2020-08-20 at 3 23 18 PM" src="https://user-images.githubusercontent.com/1036734/90815692-15e0a780-e2f9-11ea-9c3b-26521a3efe0b.png">

**Comment by abdielou** [comment]
any news?

**Comment by iartemiev** [comment]
Hey @abdielou, you will be able to pass a filter to the sync query once the feature in [this PR](https://github.com/aws-amplify/amplify-js/pull/7001) gets released
