### ISSUE TITLE
Cognito mobile application signout URL is not working in ionic project

### ISSUE THREAD

**Issue by sandeep621** [aws-amplify/amplify-js#6599]
Hi Team,

We are using cognito with Azure active directory. When we use the call back URL for mobile application as mobileManager:// it was throwing below error. sign in is working fine, but when we click on sign out button the below error is coming. could you please help us to resolve this issue ASAP.

**Comment by sammartinez** [comment]
@sandeep621 Apologizes on the late reply back to you, this looks to be related specifically to Amazon Cognito and not AWS Amplify. We act as a proxy to Amazon Cognito. Please open up an issue with Amazon Cognito via their [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=173)
