### ISSUE TITLE
Not receiving the confirmation code after signup when the usernameAlias="phone_number"

### ISSUE THREAD

**Issue by jaivinodha** [aws-amplify/amplify-js#6604]
**Describe the bug**

Not receiving the confirmation code to mobile after signup when the usernameAlias="phone_number" though it creates an entry in the cognito user pool with country code

but usernameAlias="email" is working fine and im receiving the confirmation code to my email 

**To Reproduce**

import React from 'react';
import { AmplifyAuthenticator, AmplifySignUp, AmplifySignIn } from '@aws-amplify/ui-react';

const App = () => {
  return (
    <AmplifyAuthenticator usernameAlias="phone_number">
![image](https://user-images.githubusercontent.com/69211611/90622522-d485c480-e232-11ea-878c-d93a8e3dd48f.png)

      <AmplifySignUp
        slot="sign-up"
        headerText="Create a New account"
        usernameAlias="phone_number"
        formFields={[
          {
            type: "name",
            label: "Name*",
            placeholder: "Enter your name",
            required: true,
          },
          {
            type: "password",
            label: "Password*",
            placeholder: "Enter your password",
            required: true,
          },
          {
            type: "phone_number",
            label: "Phone Number* ",
            placeholder: "Enter your phone",
            required: true,
          },
          
          
        ]} 
      />
     
      <AmplifySignIn slot="sign-in" usernameAlias="phone_number" 
      
      formFields={[
        {
            type: "phone_number",
            label: "Phone Number* ",
            placeholder: "Enter your phone",
            required: true,
          },
        {
          type: "password",
          label: "Password*",
          placeholder: "Enter your password",
          required: true,
        },
       
        
      ]}
     
      />
     
     

    </AmplifyAuthenticator>
  );
};

![image](https://user-images.githubusercontent.com/69211611/90620456-1b25ef80-e230-11ea-8c72-284c6fe0f609.png)

----------------------------------------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/69211611/90620706-6d671080-e230-11ea-9b84-afb5b74dda92.png)

----------------------------------------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/69211611/90621559-82906f00-e231-11ea-9129-36585115ee20.png)

----------------------------------------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/69211611/90621020-d3539800-e230-11ea-9ef8-e7d1f9abf9fe.png)

----------------------------------------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/69211611/90621126-efefd000-e230-11ea-8e0a-f1d3c55f0fb0.png)

----------------------------------------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/69211611/90621207-085fea80-e231-11ea-9987-e85debea38ae.png)

----------------------------------------------------------------------------------------------------------------------------------------

**Comment by amhinson** [comment]
On the 2nd to last screenshot under the `Which attributes do you want to verify?` section, there should be another section with the header `You must provide a role to allow Amazon Cognito to send SMS messages`. Do you have a role created?

**Comment by jaivinodha** [comment]
its there, sorry i have missed to attach it
![image](https://user-images.githubusercontent.com/69211611/90653618-090e7600-e25d-11ea-90ae-568bdec14dcc.png)

**Comment by amhinson** [comment]
Ah ok thanks! Could you also check if you have requested a spending limit increase from Amazon SNS? (see yellow box in 2nd to last screenshot)

**Comment by jaivinodha** [comment]
I haven't . should i ?
because when i test it withAuthenticator(App) , im getting the sms successfully during signup without increasing the spending limit

**Comment by amhinson** [comment]
Ah interesting! If its working there, I'd assume it should work when using `AmplifyAuthenticator` as well. Adding the `Amplify UI Components` label for triaging.

**Comment by amhinson** [comment]
@jaivinodha Also for clarification, when you say `withAuthenticator` worked as expected, was that from `@aws-amplify/ui-react` or `aws-amplify-react`?

**Comment by jaivinodha** [comment]
> Ah interesting! If its working there, I'd assume it should work when using `AmplifyAuthenticator` as well. Adding the `Amplify UI Components` label for triaging.

Hi, Even in withAuthenticator Im not getting sms right now, it has stopped ,May be i have generated a lots of otp during testing.  So i believe i should increase my limit. Thanks, i will do it and let you know :). once again thank you so much

**Comment by jaivinodha** [comment]
> Ah ok thanks! Could you also check if you have requested a spending limit increase from Amazon SNS? (see yellow box in 2nd to last screenshot)

It has started working. Sms limit is the problem :) thank you once again 👍
