### ISSUE TITLE
Create auth challengeMetadata does not show up in the signIn response

### ISSUE THREAD

**Issue by alastair-todd** [aws-amplify/amplify-js#6606]
**Describe the bug**
When setting:

```
event.response.challengeMetadata = "00000000-0000-0000-0000-000000000000";
callback(null, event);
```

in the Cognito create auth lambda, the property does not show up in response from the call to `Auth.signIn`, which returns:

```

CognitoUser {
  username: 'xxxxxxx',
  pool: CognitoUserPool {
    userPoolId: 'eu-west-1_xxx',
    clientId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxx',
    client: Client {
      endpoint: 'https://cognito-idp.eu-west-1.amazonaws.com/',
      fetchOptions: {}
    },
    advancedSecurityDataCollectionFlag: true,
    storage: InMemoryLocalStorage { store: {} }
  },
  Session: redacted',
  client: Client {
    endpoint: 'https://cognito-idp.eu-west-1.amazonaws.com/',
    fetchOptions: {}
  },
  signInUserSession: null,
  authenticationFlowType: 'CUSTOM_AUTH',
  storage: InMemoryLocalStorage { store: {} },
  keyPrefix: 'CognitoIdentityServiceProvider.xxxxxxxxxxxxxxxxxxxxxxxxxxx',
  userDataKey: 'CognitoIdentityServiceProvider.xxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  challengeName: 'CUSTOM_CHALLENGE',
  challengeParam: {
    fingerprintId: '00000000-0000-0000-0000-000000000000',
    pinDigits: '[{"value":null,"label":"2nd"},{"value":null,"label":"4th"},{"value":null,"label":"5th"}]'
  }
}
```

As you can see I can probably work around it using the challenge parameters, but I was expecting to see `challengeMetadata  `in the response.

The property [is documented here](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-create-auth-challenge.html),

**Comment by sammartinez** [comment]
@alastair-todd The documentation you provide is focused on Amazon Cognito, have you setup any[ Lambda Triggers](https://docs.amplify.aws/cli/usage/lambda-triggers) via our Amplify CLI? Please let us know the steps you took for setup. Thanks ahead of time!

**Comment by damien-monni** [comment]
Same issue here. @alastair-todd have you resolved the issue?

**Comment by alastair-todd** [comment]
@damien-monni nope. seems everyone, stalebot included, have their head in the sand on this one. 

If you want to send metadata then you will need to send it in the `publicChallengeParameters` property - the only way you could possibly handle multiple challenges currently.

sorry aws but cognito is a dogs's dinner.

**Comment by damien-monni** [comment]
@alastair-todd  Yes sending in the publicChallengeParameters is what I am doing now... it just does not feel right.

Thanks!

**Comment by ChrisSargent** [comment]
Just kinda came across this but if you see in the sequence diagram the data in the `session` is never passed to the client.
<img width="517" alt="Screenshot 2022-01-11 at 18 57 54" src="https://user-images.githubusercontent.com/12176122/148996703-b0686aeb-536a-4349-bfa4-99e957a2e217.png">
