### ISSUE TITLE
Allow to set our proper ID when using DataStore and generated models

### ISSUE THREAD

**Issue by Hideman85** [aws-amplify/amplify-js#6615]
It would be great to allow us to manage IDs ourself. I see already two case where built-in IDs management is not efficient.

**UserID from Cognito (sub)**
How many devs wanted to save a User object with the sub as ID? But currently we can't and need to save it as separate property with an index.

```gql
type User {
  id: ID! # would be great sub from Cognito
  address: String
}
```

**Support of Union?**
```gql
type Image {
  id: ID!
  name: String!
  width: Int!
  height: Int!
  url: String!
}

type Video {
  id: ID!
  name: String!
  lang: Lang!
  resolutions: [Resolution!]!
  url: String!
}

union Media = Image | Video

type Product {
  id: ID!
  name: String!
  description: Media! @connection
}
```

By having the typename as prefix of the ID we could determine where to fetch the resource. This must be also with a [Improvement of @connection amplify-cli#5129](https://github.com/aws-amplify/amplify-cli/issues/5129).

**Shorter IDs? (more personal choice)**
Personally I like to have short and self descriptive IDs (using uniqid node package) like:
- img-XXXXX
- vid-YYYYY
- pdt-ZZZZZ

**How can it be made?**
I suppose there we can also pass the typename and maybe get from the config a custom uuid factory.
https://github.com/aws-amplify/amplify-js/blob/00d5e1773766dad5a1c04b70e2d6d72a42268796/packages/datastore/src/storage/adapter/AsyncStorageDatabase.ts#L32-L38

**Comment by elorzafe** [comment]
Thanks for your feedback @Hideman85 

We need an internal discussion with the team about this.

**Comment by thiskevinwang** [comment]
Docs on _best practices/common patterns for Cognito User Pool "Users" <> Amplify DataStore "Users"_ would be great as well.

Currently, the field is a bit hazy in this topic.
- How do you specify a unique user-specified `username`?
  Do you query the DataStore first?
- (Reiterating the original ask) How/can you pass a cognito-sub as the `id` for a custom `User` `DataStore` model?
  Currently, it's `readonly` and you cannot update it.
- etc.

**Comment by rraczae** [comment]
+1: it would be great to have a clean solution to one record per cognito user use cases

**Comment by nitemarket** [comment]
Any updates here? would be great to save a predefined ID for the model.

**Comment by bravcmo** [comment]
is there any documentation on associating our application user entities (AppUser) with Cognito?  With the limits on custom fields in Cognito, I'm assuming app-specific attributes for our User is supposed to be stored in our defined schemas.

**Comment by ajmalbabu** [comment]
If you are trying to avoid default DataStore scan behavior and want to issue a query using a global secondary index (GSI) using a ID that you have in the app (such as customer email) this can be done using these instructions https://docs.amplify.aws/lib/datastore/sync/q/platform/js#advanced-use-case---query-instead-of-scan Read the article from beginning how to configure Syncing data to cloud here:  https://docs.amplify.aws/lib/datastore/sync/q/platform/js

**Comment by loganpowell** [comment]
I have a complex data model that relies heavily on the [many:many](https://docs.amplify.aws/lib/datastore/relational/q/platform/js#many-to-many) relationship type. I've found working with the raw API (via graphql) more ergonomic when establishing and querying such connections.  Especially when creating/mutating connections, the requirement to use an _instance_ of the actual DataStore records requires me to write two separate versions of the input functions for every `type`. 

Having the ability - as it is when using the graphql api - to use IDs instead of instances of DataStore records to link everything together would be less vulnerable to my fat fingers.

**Comment by apolat2000** [comment]
We desperately need this affordance of being able to set the id's of class instances manually. Is there any update here?

**Comment by chrisbonifacio** [comment]
This is still being discussed internally. Im not aware of any current plans or timeline on when this will be possible in DataStore.

The current supported path forward here is to use API.graphql to set your own unique ID, such as a Cognito sub for a User record. The creation of such records might best be handled on the server side in a Cognito Post-Confirmation Lambda Trigger. If you use AppSync in the lambda to perform the createUser mutation, it will also trigger subscriptions if needed.

**Comment by danishazmat** [comment]
any progress on this issue?

**Comment by dpilch** [comment]
This is now possible with custom primary key https://docs.amplify.aws/lib/datastore/advanced-workflows/q/platform/js/#customize-primary-keys
