### ISSUE TITLE
Unable to retrieve guest/unauthenticated credentials after identity becomes disabled

### ISSUE THREAD

**Issue by janejjshen** [aws-amplify/amplify-js#6616]
**Describe the bug**
During Cognito's identity merge, a guest identity ID can become disabled. I believe this automatic identity merge is currently supported in the Mobile SDKs but not the JS SDK. Afterwards, if the web user tries to use the same identity again to retrieve IAM credentials, they would receive an error `Access to identity 'us-east-2:xxxxx is forbidden'`, and unable to proceed. The JavaScript SDK should be able to then catch the error and retry to get a new guest ID, instead of throwing the error.

**To Reproduce**

This issue happens intermittently, but this is my hypothesis on how it happened:

1. Web A calls `Auth.currentCredentials()` to creates guest identity 1. They then log in via Cognito, which creates an authenticated identity 2. Browser local storage is swapped with identity 2. Then they log out. Browser local storage is swapped with identity 1 again.
2. Mobile B calls the SDK equivalent of `Auth.currentCredentials()` to creates guest identity 3. They then log in with the same Cognito credentials. They retrieve the same authenticated identity 2 that is now merged with identity 3. 
3. Identity 1 is disabled (can be verified by going to the Cognito Identity Pool's identity browser).
4. Web A tries to use guest identity 1 again via `Auth.currentCredentials()`, fails with `Access to identity 'us-east-2:xxxxx is forbidden'` error and cannot proceed.

**Expected behavior**
If the web client encounters such error, it should retry to get a new guest identity, and replace the local storage with the new id.

**What is Configured?**
A Cognito user pool is federated with an OIDC provider. There are web, Android and iOS clients connecting to it via the code auth flow.

- Browser: Chrome, Firefox

**Additional context**
By looking at here: the error is rethrown and no retry is done:

https://github.com/aws-amplify/amplify-js/blame/00d5e1773766dad5a1c04b70e2d6d72a42268796/packages/core/src/Credentials.ts#L274

**Comment by amhinson** [comment]
This fix is available with `aws-amplify@unstable` right now. We should have a release to `latest` early next week 👍

**Comment by elorzafe** [comment]
I will close this issue for now, we will do a release early next week.
