### ISSUE TITLE
Graphql queries works fine on AppSync Console but throw errors on client side

### ISSUE THREAD

**Issue by ShawnYcx** [aws-amplify/amplify-js#6619]
My schema and queries are working fine on amplify console but throwing a type mismatch error on the client side. This happens only when there are more than one records in the object returned

**Data successfully returned when there's only one record**

[![enter image description here][1]][1]

**Error when object contains more than one record**

[![enter image description here][2]][2]

**Schema:**

```graphql
type Member {
	Id: ID
	PartyId: String
	Status: MemberStatus
	PersonName: MemberName
	Email: String
	UniformId: String
	Name: String
}

type MemberName {
	FirstName: String
	LastName: String
	FullName: String
	InformalName: String
}

type MemberStatus {
	PartyStatusId: String
	Name: String
	Description: String
	ActiveStatus: Int
}

type Query {
	listMembers(id: ID, firstName: String, lastName: String): [Member]
}
```

My query on the frontend
```js
// Single Record 
const [isLoading, state, error] = useGraphql(queries.listMembers, {
    firstName: "BlaBle",
    lastName: "Blu",
})

// Multiple Records
const [isLoading, state, error] = useGraphql(queries.listMembers, {
    firstName: "blee",
})
```

*Resolver*

[![enter image description here][3]][3]

Am I missing something or doing something wrong here? Let me know if more info is required.
If this is not the right place to talk about this issue, let me know!

Thanks!

  [1]: https://i.stack.imgur.com/uIWYT.png
  [2]: https://i.stack.imgur.com/ThwFj.png
  [3]: https://i.stack.imgur.com/AaW93.png

**Comment by sammartinez** [comment]
@ShawnYcx can you provide a little more context? Are you only using Amplify Console and AppSync via the AWS Management Console? Or are you using Amplify JavaScript directly? Just want to make sure I have your issue go to the right location
