### ISSUE TITLE
cypress can't select authenticator inputs for @aws-amplify/ui-react

### ISSUE THREAD

**Issue by dfang** [aws-amplify/amplify-js#6626]
**Describe the bug**
cypress can't select authenticator input in @aws-amplify/ui-react

**To Reproduce**

1. add amplify auth to a react app
2. add amplify auth and cypress
3. write simple test on authenticator, eg. login

**Expected behavior**

[selectors in this blog](https://aws.amazon.com/blogs/mobile/run-end-to-end-cypress-tests-for-your-fullstack-ci-cd-deployment-with-amplify-console/) can select right inputs，but it's legacy amplify-ui-react ....

```
export const selectors = {
  // Auth component classes
  usernameInput: '[data-test="username-input"]',
  signInPasswordInput: '[data-test="sign-in-password-input"]',
  signInSignInButton: '[data-test="sign-in-sign-in-button"]',
  signOutButton: '[data-test="sign-out-button"]'
}
```

tried selectors on chrome developer tools console, it does not work 

** Screenshots **

<img width="1435" alt="Screen Shot 2020-08-24 at 9 51 06 AM" src="https://user-images.githubusercontent.com/1277047/90999735-f8ae2080-e5f9-11ea-95c5-aa050b9654d2.png">

**Comment by dfang** [comment]
this is more of cypress shadow DOM support, not amplify problem. so i'll close it.

for those who want to use cypress to test react application with amplifyAuthenticator in hosted UI, [see here](https://github.com/cypress-io/cypress/issues/830#issuecomment-678876572)

**Comment by jordanranz** [comment]
Hey @dfang, Cypress does now support shadow dom in their [Experiments section](https://docs.cypress.io/guides/references/experiments.html#Shadow-DOM)

```
cy.get('amplify-authenticator')
  .shadow()
  .get('amplify-sign-in')...
```

**Comment by dfang** [comment]
@jordanranz i've already put the link in the comment

**Comment by Nxtra** [comment]
Cypress `5.2.0` added the configuration option includeShadowDom for enabling shadow DOM.

In `cypress.json` set
```
{
  "includeShadowDom": true
}
```

Then in your test select for example the login input field:   
`cy.get('[data-test="sign-in-username-input"]').first().type("DUMMY_USERNAME");`

This works, not sure why the `first()` is necessary though.

**Comment by martinrojas** [comment]
Also would like to add that Cypress considers using the selectors for login as an anti-pattern for login into the application. Their documentation has a tutorial for login in programmatically. https://docs.cypress.io/guides/testing-strategies/amazon-cognito-authentication#Amazon-Cognito-Setup

**Comment by michaelbrewer** [comment]
This is broken again in the new version

**Comment by m-a-c-k** [comment]
^ broken for me as well, even with the "includeShadowDom"

**Comment by ashika01** [comment]
@ryosukemitake these issues are no longer relevant to this repo, please find a duplicate or open a new issue at https://github.com/aws-amplify/amplify-ui
