### ISSUE TITLE
DataStorage (with AppSync backend) saving issue

### ISSUE THREAD

**Issue by Hideman85** [aws-amplify/amplify-js#6630]
There is my testing app: https://github.com/Hideman85/TestApp

```gql
type Comment
@model
@key(name: "byInstanceID", fields: ["instanceID", "organisationID"])
{
  id: ID! # comment-
  userID: ID!
  # user: User! @connection(fields: ["userID"])
  instanceID: ID!
  # instance: CommentInstance! @connection(fields: ["instanceID"])
  organisationID: ID # used for distinguish inter and external comments
  # organisation: Organisation @connection(fields: ["organisationID"])
  text: String!
}
```

```jsx
<button onClick={async () => {
  try {
    await DataStore.save(
      new models.Comment({
        id: `my custom ID ${Math.random()}`,
        userID: 'userID',
        instanceID: 'instanceID',
        organisationID: 'organisationID',
        text: 'text'
      })
    )
    console.info('Comment saved successfully!')
  } catch (error) {
    console.error('Error saving comment', error)
  }
}}>Create comment</button>
```

```
Error saving comment InternalError: "too much recursion"
    isGraphQLScalarType types.ts:126
    result utils.ts:82
    getScalarFields utils.ts:80
    generateSelectionSet utils.ts:57
    getNonModelFields utils.ts:143
    getNonModelFields utils.ts:137
    getNonModelFields utils.ts:129
    generateSelectionSet utils.ts:58
    getNonModelFields utils.ts:143
    getNonModelFields utils.ts:137
    getNonModelFields utils.ts:129
    generateSelectionSet utils.ts:58
```

**Comment by elorzafe** [comment]
@Hideman85 thanks for providing so much details. I am trying your sample app now

**Comment by elorzafe** [comment]
@Hideman85 I ran your app with this schema

```graphql
type Comment
@model
@key(name: "byInstanceID", fields: ["instanceID", "organisationID"])
{
  id: ID! # comment-
  userID: ID!
  # user: User! @connection(fields: ["userID"])
  instanceID: ID!
  # instance: CommentInstance! @connection(fields: ["instanceID"])
  organisationID: ID # used for distinguish inter and external comments
  # organisation: Organisation @connection(fields: ["organisationID"])
  text: String!
}
```

And I didnt get the error you mentioned before, however with the original schema it failed.

DataStore autogenerates the ids, there are synchronization issues behind this, that is why you are not allowed to change.

Why do you need a custom id?

I will keep looking the issue with the other schema

**Comment by Hideman85** [comment]
Hi @elorzafe thanks for looking my case,


.
> And I didnt get the error you mentioned before, however with the original schema it failed.

You're right I've just tested with only the Comment model and it's working I don't know what causing this issue in my current schema


.
> DataStore autogenerates the ids, there are synchronization issues behind this, that is why you are not allowed to change.

Yes I can understand the synchronization issue if you are using incremental IDs but if you are unique ID there is no issues.


.
> Why do you need a custom id?

[There is my response](https://github.com/aws-amplify/amplify-js/issues/6615)

**Comment by elorzafe** [comment]
Thanks for you feedback @Hideman85 ! We can continue id discussion on the other issue

I will continue looking the issue you are having the schema

**Comment by Hideman85** [comment]
I still have issue:
```
[DEBUG] 28:15.523 Util - error on 
{
  "data": {
    "syncSectionTexts": null
  },
  "errors": [
    {
      "path": [
        "syncSectionTexts"
      ],
      "data": null,
      "errorType": "InternalFailure",
      "errorInfo": null,
      "locations": [
        {
          "line": 2,
          "column": 3,
          "sourceName": null
        }
      ],
      "message": "An internal error occurred."
    }
  ]
}
```

The weird aspect is that error block all other actions (queries, mutations, subscriptions)

To reproduce clone the TestApp and create follow the steps describe for initializing an new amplify app. Take the file `schema.graphql` as testing.

**Comment by Hideman85** [comment]
Looks to be the same issue: https://github.com/aws-amplify/amplify-js/issues/6707

**Comment by iartemiev** [comment]
@Hideman85 the latest error is from AppSync. If you run the `syncSectionTexts` query via the AppSync Console, you should get the same error. Typically, when I've seen this before, it's due to malformed data getting saved in DynamoDB that doesn't get caught by DataStore or AppSync validation on its way in.

**Comment by ajmalbabu** [comment]
If you are trying to avoid default DataStore scan behavior and want to issue a query using a global secondary index (GSI) using a ID that you have in the app (such as customer email) this can be done using these instructions https://docs.amplify.aws/lib/datastore/sync/q/platform/js#advanced-use-case---query-instead-of-scan Read the article from the beginning how to configure Syncing data to cloud here:  https://docs.amplify.aws/lib/datastore/sync/q/platform/js
