### ISSUE TITLE
CompleteNewPassword requiredAttributes is not optional

### ISSUE THREAD

**Issue by joeltio** [aws-amplify/amplify-js#6634]
**Describe the bug**
The `Auth.completeNewPassword` should only require two arguments: `user` and `password` but the types do not reflect so. The signature of the function is:
```
completeNewPassword(user: CognitoUser | any, password: string, requiredAttributes: any, clientMetadata?: ClientMetaData): Promise<CognitoUser | any>
```
Notice how `requiredAttributes` is not optional. However, [the docs](https://docs.amplify.aws/lib/auth/manageusers/q/platform/js#complete-new-password) say that it is optional.

**To Reproduce**

1. Create a typescript-enabled project
2. Import the `Auth` package
3. Type `Auth.completeNewPassword('', '')`

**Expected behavior**
There should not be an error reported by typescript.

**Code Snippet**
```javascript
import Auth from '@aws-amplify/auth';
Auth.completeNewPassword('', '');
```

**Comment by elorzafe** [comment]
Thanks @joeltio I will send a PR to fix this
