### ISSUE TITLE
React Native - Apple Sign In

### ISSUE THREAD

**Issue by sregg** [aws-amplify/amplify-js#6637]
I followed the doc to add Sign in with Google, Facebook and Apple from here: 
https://docs.amplify.aws/lib/auth/social/q/platform/js

Google and Facebook work perfectly fine but I couldn't make Apple work after a whole day debugging.

Here's some screenshots of the flow:
<img width="250" alt="Screen Shot 2020-08-24 at 5 12 21 PM" src="https://user-images.githubusercontent.com/1479283/91097365-8e16d800-e62d-11ea-81bd-c49c0745a597.png"> <img width="250" alt="Screen Shot 2020-08-24 at 5 12 43 PM" src="https://user-images.githubusercontent.com/1479283/91097385-9707a980-e62d-11ea-9fa1-2eb1fc8e6a39.png"> <img width="250" alt="Screen Shot 2020-08-24 at 5 20 10 PM" src="https://user-images.githubusercontent.com/1479283/91097661-22813a80-e62e-11ea-9d4e-c4dddaeee6a4.png">

Here's my logs from the `Hub`
```
[Mon Aug 24 2020 17:20:03.980]  LOG      Hub.auth {"payload": {"data": {"url": "setmatch://?error_description=SignInWithApple+Error+-+400+invalid_client&state=wrBob3s5zqoty4YDYInEC9NL5wQnQNuK&error=invalid_request"}, "event": "parsingCallbackUrl", "message": "The callback url is being parsed"}}
[Mon Aug 24 2020 17:20:03.981]  ERROR    [ERROR] 20:03.971 OAuth - Error handling auth response. [Error: SignInWithApple+Error+-+400+invalid_client]
[Mon Aug 24 2020 17:20:04.700]  LOG      Hub.auth {"payload": {"data": [Error: SignInWithApple+Error+-+400+invalid_client], "event": "signIn_failure", "message": "The OAuth response flow failed"}}
[Mon Aug 24 2020 17:20:04.900]  LOG      signIn_failure
[Mon Aug 24 2020 17:20:04.100]  LOG      Hub.auth {"payload": {"data": [Error: SignInWithApple+Error+-+400+invalid_client], "event": "cognitoHostedUI_failure", "message": "A failure occurred when returning to the Cognito Hosted UI"}}
[Mon Aug 24 2020 17:20:04.110]  LOG      Hub.auth {"payload": {"data": [Error: SignInWithApple+Error+-+400+invalid_client], "event": "customState_failure", "message": "A failure occurred when returning state"}}
```

`aws-exports.js`
```javascript
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:xxxxxx,
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xxxxxxx",
    "aws_user_pools_web_client_id": "xxxxxx",
    "oauth": {
        "domain": "setmatch-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "setmatch://",
        "redirectSignOut": "setmatch://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://xxxxxx.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "xxxxxx",
    "aws_user_files_s3_bucket": "xxxxxx",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_mobile_analytics_app_id": "xxxxxx",
    "aws_mobile_analytics_app_region": "us-east-1"
};
```

Here's some Cognito screenshots
![image](https://user-images.githubusercontent.com/1479283/91098034-bb17ba80-e62e-11ea-8754-40e1b1de4085.png)
![image](https://user-images.githubusercontent.com/1479283/91098081-d4b90200-e62e-11ea-910e-b8d1c7adf15b.png)
![image](https://user-images.githubusercontent.com/1479283/91098116-e3071e00-e62e-11ea-81ad-1b33d1b3e529.png)

Here's some Apple screenshots
![image](https://user-images.githubusercontent.com/1479283/91098219-19dd3400-e62f-11ea-9f01-a6b9a0ffae1e.png)
![image](https://user-images.githubusercontent.com/1479283/91098839-2f9f2900-e630-11ea-8a27-6dd8febf5ccb.png)
![image](https://user-images.githubusercontent.com/1479283/91098296-39745c80-e62f-11ea-8bd0-856f022b9a80.png)

**Comment by amhinson** [comment]
Similar to https://github.com/aws-amplify/amplify-js/issues/6547. I will take a look into this soon 👍

**Comment by sregg** [comment]
> Similar to #6547. I will take a look into this soon 👍

Thanks Alex.
Let me know if you'd like to have access to my code and setup to help reproduce

**Comment by amhinson** [comment]
@sregg Could you reach out to me on our Discord? It's just `amhinson`. That could help streamline things a bit

**Comment by sregg** [comment]
Alright. After another afternoon debugging this with the amazing help of @amhinson, I finally made it working.
It basically was something like this:
<img width="300" src="https://media1.tenor.com/images/d1501c6a22fb9568b14c921bf749ec29/tenor.gif?itemid=17823069"/>
Here's the steps I did (not sure which one helped):
- I didn't have the Sign in with Apple capability added in my project in Xcode (pretty sure that's only needed if you use the iOS SDK, but doesn't hurt)
- I deleted the user group created in User Pool > General settings > Users and groups > Groups > us-east-xxx_SignInWithApple
- I disabled the Apple IDP in Federation > Identity providers > Sign in with Apple
- I recreated that IDP (same sid, team id, key id, key file, and scopes email+name)
- Enabled it again in App integrations > App client settings
- Set up the attributes mapping again in Federation > Attribute mapping > Apple (email is unchecked by default)
- Removed the app in my https://appleid.apple.com settings under Security > APPS & WEBSITES
Hope this helps anyone who's seeing this `invalid_client` error

**Comment by ahtokca** [comment]
I'm afraid apple will reject such integration since it opens browser vs TouchId or FaceScan

**Comment by hassankhan** [comment]
Just to add my £0.02; the official AWS Cognito documentation for setting up Sign in with Apple makes zero mention of the 'Set up the attributes mapping again in Federation > Attribute mapping > Apple (email is unchecked by default)' step.

If you are setting up Sign in with Apple, please remember to also set up the attribute mappings. A massive thanks to @sregg for providing a clear set of steps to get it working.

**Comment by gruckion** [comment]
Still having this issue none of the steps seemed to help.

I am using Expo and AWS Amplify.

https://saachitech.medium.com/react-native-social-sign-in-with-apple-and-amplify-6c803b2971d6

This guide is pretty detailed, but still stuck at this issue.

<img src="https://user-images.githubusercontent.com/4559650/121786305-eb791700-cbb6-11eb-94ab-6ab973276ef5.png" width="40%" />

# Apple setup

## App IDs

![Screenshot 2021-06-12 at 19 56 28](https://user-images.githubusercontent.com/4559650/121786539-495a2e80-cbb8-11eb-8ec9-133b02b8e5ea.png)

![Screenshot 2021-06-12 at 19 57 17](https://user-images.githubusercontent.com/4559650/121786560-65f66680-cbb8-11eb-907b-78d316381ad3.png)

![Screenshot 2021-06-12 at 19 57 38](https://user-images.githubusercontent.com/4559650/121786567-71e22880-cbb8-11eb-9e2d-5f1db14cd718.png)

![Screenshot 2021-06-12 at 19 58 02](https://user-images.githubusercontent.com/4559650/121786574-80304480-cbb8-11eb-836e-fd8989f333cd.png)

## Identifiers

![Screenshot 2021-06-12 at 19 49 55](https://user-images.githubusercontent.com/4559650/121786368-5d516080-cbb7-11eb-981c-d00e2fc85cc4.png)

![Screenshot 2021-06-12 at 19 50 47](https://user-images.githubusercontent.com/4559650/121786398-7c4ff280-cbb7-11eb-905d-ec55076f2246.png)

![Screenshot 2021-06-12 at 19 54 27](https://user-images.githubusercontent.com/4559650/121786491-ff714880-cbb7-11eb-98ab-8a0167be0934.png)

The values are of the screen so I clicked the copy button and pasted below

> mycompany-dev-fe82833d-f388-40d7-ac21-cc365a900749.auth.eu-west-2.amazoncognito.com
> https://mycompany-dev-fe82833d-f388-40d7-ac21-cc365a900749.auth.eu-west-2.amazoncognito.com/oauth2/idpresponse

## Keys

![Screenshot 2021-06-12 at 19 59 25](https://user-images.githubusercontent.com/4559650/121786596-b1a91000-cbb8-11eb-91e8-e2ab3ce841f7.png)

![Screenshot 2021-06-12 at 20 00 05](https://user-images.githubusercontent.com/4559650/121786604-c9809400-cbb8-11eb-9c9e-3a5735a8e2e1.png)

![Screenshot 2021-06-12 at 20 00 32](https://user-images.githubusercontent.com/4559650/121786613-da310a00-cbb8-11eb-881a-2239083f7b81.png)

![Screenshot 2021-06-12 at 20 01 49](https://user-images.githubusercontent.com/4559650/121786639-077db800-cbb9-11eb-9609-2411ed698ae7.png)


# Cognito setup

## App integration

![Screenshot 2021-06-12 at 20 06 52](https://user-images.githubusercontent.com/4559650/121786734-bb7f4300-cbb9-11eb-9dc9-6c63e8017906.png)

![eu-west-2 console aws amazon com_cognito_users_region=eu-west-2 (1)](https://user-images.githubusercontent.com/4559650/121786790-14e77200-cbba-11eb-8c9d-1dc2b1566086.png)

## Federation

![eu-west-2 console aws amazon com_cognito_users_region=eu-west-2 (2)](https://user-images.githubusercontent.com/4559650/121786834-5841e080-cbba-11eb-9619-deec42348190.png)

![eu-west-2 console aws amazon com_cognito_users_region=eu-west-2 (4)](https://user-images.githubusercontent.com/4559650/121786882-9c34e580-cbba-11eb-8f13-eee9961e5511.png)

## Federated Identities

![eu-west-2 console aws amazon com_cognito_pool__region=eu-west-2 id=eu-west-2_4bd525ff-fc50-4bd6-a518-407a0443eb13](https://user-images.githubusercontent.com/4559650/121786934-d900dc80-cbba-11eb-894d-b27c58e3ca8f.png)

![eu-west-2 console aws amazon com_cognito_pool_edit__region=eu-west-2 id=eu-west-2_4bd525ff-fc50-4bd6-a518-407a0443eb13](https://user-images.githubusercontent.com/4559650/121786984-3d23a080-cbbb-11eb-8340-10bf9a488636.png)

# What on Earth am I missing here?

If I use my Expo React-native app or the Hosted UI for the `mycompany3b358f8b_app_clientWeb`

![Screenshot 2021-06-12 at 20 18 39](https://user-images.githubusercontent.com/4559650/121786997-617f7d00-cbbb-11eb-854f-0fc4e1e72e07.png)

![Screenshot 2021-06-12 at 20 19 11](https://user-images.githubusercontent.com/4559650/121787005-765c1080-cbbb-11eb-8a2c-efb8a158c4a7.png)

- Google works
- Facebook works
- Apple 

![Screenshot 2021-06-12 at 20 20 04](https://user-images.githubusercontent.com/4559650/121787025-94c20c00-cbbb-11eb-8067-cc0f2667c96d.png)

Just can't see what I am doing wrong here.

**Comment by gruckion** [comment]
Still having this issue none of the steps seemed to help.

I am using Expo and AWS Amplify.

https://saachitech.medium.com/react-native-social-sign-in-with-apple-and-amplify-6c803b2971d6

This guide is pretty detailed, but still stuck at this issue.

<img src="https://user-images.githubusercontent.com/4559650/121786305-eb791700-cbb6-11eb-94ab-6ab973276ef5.png" width="40%" />

# Apple setup

## App IDs

![Screenshot 2021-06-12 at 19 56 28](https://user-images.githubusercontent.com/4559650/121786539-495a2e80-cbb8-11eb-8ec9-133b02b8e5ea.png)

![Screenshot 2021-06-12 at 19 57 17](https://user-images.githubusercontent.com/4559650/121786560-65f66680-cbb8-11eb-907b-78d316381ad3.png)

![Screenshot 2021-06-12 at 19 57 38](https://user-images.githubusercontent.com/4559650/121786567-71e22880-cbb8-11eb-9e2d-5f1db14cd718.png)

![Screenshot 2021-06-12 at 19 58 02](https://user-images.githubusercontent.com/4559650/121786574-80304480-cbb8-11eb-836e-fd8989f333cd.png)

## Identifiers

![Screenshot 2021-06-12 at 19 49 55](https://user-images.githubusercontent.com/4559650/121786368-5d516080-cbb7-11eb-981c-d00e2fc85cc4.png)

![Screenshot 2021-06-12 at 19 50 47](https://user-images.githubusercontent.com/4559650/121786398-7c4ff280-cbb7-11eb-905d-ec55076f2246.png)

![Screenshot 2021-06-12 at 19 54 27](https://user-images.githubusercontent.com/4559650/121786491-ff714880-cbb7-11eb-98ab-8a0167be0934.png)

The values are of the screen so I clicked the copy button and pasted below

> mycompany-dev-fe82833d-f388-40d7-ac21-cc365a900749.auth.eu-west-2.amazoncognito.com
> https://mycompany-dev-fe82833d-f388-40d7-ac21-cc365a900749.auth.eu-west-2.amazoncognito.com/oauth2/idpresponse

## Keys

![Screenshot 2021-06-12 at 19 59 25](https://user-images.githubusercontent.com/4559650/121786596-b1a91000-cbb8-11eb-91e8-e2ab3ce841f7.png)

![Screenshot 2021-06-12 at 20 00 05](https://user-images.githubusercontent.com/4559650/121786604-c9809400-cbb8-11eb-9c9e-3a5735a8e2e1.png)

![Screenshot 2021-06-12 at 20 00 32](https://user-images.githubusercontent.com/4559650/121786613-da310a00-cbb8-11eb-881a-2239083f7b81.png)

![Screenshot 2021-06-12 at 20 23 38](https://user-images.githubusercontent.com/4559650/121787096-13b74480-cbbc-11eb-8a88-c0099e788c30.png)

# Cognito setup

## App integration

![Screenshot 2021-06-12 at 20 25 25](https://user-images.githubusercontent.com/4559650/121787133-52e59580-cbbc-11eb-80b4-8b76cd80ddb0.png)

![eu-west-2 console aws amazon com_cognito_users_region=eu-west-2 (1)](https://user-images.githubusercontent.com/4559650/121786790-14e77200-cbba-11eb-8c9d-1dc2b1566086.png)

## Federation

![eu-west-2 console aws amazon com_cognito_users_region=eu-west-2 (2)](https://user-images.githubusercontent.com/4559650/121786834-5841e080-cbba-11eb-9619-deec42348190.png)

![eu-west-2 console aws amazon com_cognito_users_region=eu-west-2 (4)](https://user-images.githubusercontent.com/4559650/121786882-9c34e580-cbba-11eb-8f13-eee9961e5511.png)

## Federated Identities

![eu-west-2 console aws amazon com_cognito_pool__region=eu-west-2 id=eu-west-2_4bd525ff-fc50-4bd6-a518-407a0443eb13](https://user-images.githubusercontent.com/4559650/121786934-d900dc80-cbba-11eb-894d-b27c58e3ca8f.png)

![eu-west-2 console aws amazon com_cognito_pool_edit__region=eu-west-2 id=eu-west-2_4bd525ff-fc50-4bd6-a518-407a0443eb13](https://user-images.githubusercontent.com/4559650/121786984-3d23a080-cbbb-11eb-8340-10bf9a488636.png)

# What on Earth am I missing here?

If I use my Expo React-native app or the Hosted UI for the `mycompany3b358f8b_app_clientWeb`

![Screenshot 2021-06-12 at 20 18 39](https://user-images.githubusercontent.com/4559650/121786997-617f7d00-cbbb-11eb-854f-0fc4e1e72e07.png)

![Screenshot 2021-06-12 at 20 19 11](https://user-images.githubusercontent.com/4559650/121787005-765c1080-cbbb-11eb-8a2c-efb8a158c4a7.png)

- Google works
- Facebook works
- Apple 

![Screenshot 2021-06-12 at 20 20 04](https://user-images.githubusercontent.com/4559650/121787025-94c20c00-cbbb-11eb-8067-cc0f2667c96d.png)

Just can't see what I am doing wrong here.

**Comment by rapgithub** [comment]
in my experience since apple is making mandatory using "sign in with apple" in your project if you use other socials like Facebook or google, nothings seems to solve the issue that amplify with cognito using federatedSignIn with apple sign in does not work! I have spent days testing everything and still not having any solution! Please amplify put a clear working sample of using federatedSignIn with signInwithApple because it seems it is not working only Facebook and google works!
thanks
