### ISSUE TITLE
[Feedback]More Control over the styling.

### ISSUE THREAD

**Issue by xxcheckmatexx** [aws-amplify/amplify-js#6644]
**Page**: [`/ui/customization/customizing-css/q/framework/react`](https://docs.amplify.aws/ui/customization/customizing-css/q/framework/react)

**Feedback**:

It is very difficult to remove the boxshadow of the authenticator, individual styling for the elements will be very uselful rather than changing css vars.

**Comment by jordanranz** [comment]
You are able to modify the `box-shadow` of the Authenticator by using:
```
amplify-authenticator {
  --box-shadow: 0;
}
```

There are also:
```
  --background-color
  --width
  --min-width
  --border-radius
  --padding
  --margin-bottom
```

As these were added pretty recently, we are working on auto-documenting the css API on the Authenticator docs page. Thanks for the feedback!

**Comment by elorzafe** [comment]
I am closing this issue and leaving in this repo so other can see the response here.

I will create an issue on docs repo that will point to this one

**Comment by xxcheckmatexx** [comment]
> You are able to modify the `box-shadow` of the Authenticator by using:
> 
> ```
> amplify-authenticator {
>   --box-shadow: 0;
> }
> ```
> 
> There are also:
> 
> ```
>   --background-color
>   --width
>   --min-width
>   --border-radius
>   --padding
>   --margin-bottom
> ```
> 
> As these were added pretty recently, we are working on auto-documenting the css API on the Authenticator docs page. Thanks for the feedback!

Thank you for this :)
I've used this https://aws-amplify.github.io/amplify-js/api/classes/authclass.html with formik for more control of styles for now .
