### ISSUE TITLE
getting error "TypeError: callback.customChallenge is not a function" in OTP based authentication

### ISSUE THREAD

**Issue by csarathm** [aws-amplify/amplify-js#6645]
Hi 
I am using amazon-cognito-identity-js for **OTP** based authentication and i deployed success fully coginito based lambda functions and created user for login.
But when try login am getting `"TypeError: callback.customChallenge is not a function"` error. But am getting **OTP**

Am using node 12.8.3

here is my code : 
```
let authenticationDetails = new AmazonCognitoIdentity.AuthenticationDetails({
            Username:  '+15272727282'
          });
          let userData = {
            Username:'+15272727282'
            Pool: userPool
          };
          let cognitoUser = new AmazonCognitoIdentity.CognitoUser(userData);
          cognitoUser.setAuthenticationFlowType('CUSTOM_AUTH');
          cognitoUser.initiateAuth(authenticationDetails, {
            onSuccess: function (result) {
              resolve(result)
            },
            onFailure: function (err) {
              reject(err)
              console.log(err);
            },
          });
```
Please suggest

**Comment by elorzafe** [comment]
@csarathm You need to provide `customChallenge` callback like this

```javascript
cognitoUser.initiateAuth(authenticationDetails, {
	onSuccess: function(result) {
		// User authentication was successful
	},
	onFailure: function(err) {
		// User authentication was not successful
	},
	customChallenge: function(challengeParameters) {
		// User authentication depends on challenge response
		var challengeResponses = 'challenge-answer';
		cognitoUser.sendCustomChallengeAnswer(challengeResponses, this);
	},
});
```

**Comment by csarathm** [comment]
> @csarathm You need to provide `customChallenge` callback like this
> 
> ```js
> cognitoUser.initiateAuth(authenticationDetails, {
> 	onSuccess: function(result) {
> 		// User authentication was successful
> 	},
> 	onFailure: function(err) {
> 		// User authentication was not successful
> 	},
> 	customChallenge: function(challengeParameters) {
> 		// User authentication depends on challenge response
> 		var challengeResponses = 'challenge-answer';
> 		cognitoUser.sendCustomChallengeAnswer(challengeResponses, this);
> 	},
> });
> ```

I tried this after this am getting `"Incorrect username or password."`
What i am missing . Can you Please suggest

**Comment by elorzafe** [comment]
@csarathm 

Are you able to see logs on the `Define Auth Challenge` lambda?
