### ISSUE TITLE
getSession in amazon-cognito-identity-js returning undefined sporadically

### ISSUE THREAD

**Issue by Ceycok** [aws-amplify/amplify-js#6653]
I figured one problem about on https://github.com/aws-amplify/amplify-js/issues/3613
It was never solved so i though sharing it, would be usefull.

I am using amazon-cognito-identity-js for authentication for my project and whenever I am using ```getSession()``` it returns undefined and Local Storage was empty. So I couldn't save the session info.

When ```authenticateUser()``` fonction works it only saves session info at Local Storage when it ends with ```onSuccess()```.
If you are using a user account which created with Cognito Console it ends with ```newPasswordRequired()```. So it doesn't save session info at Local Storage

I hope it helps to some people. Sorry if i explained it bad

**Comment by ericclemmons** [comment]
Thanks for the info @Ceycok !  

@amhinson Is this something we can take action on?

**Comment by ericclemmons** [comment]
Ah, as I re-read it I seem to understand better what's going on: storage happens with `onSuccess`, but the flow ends with `newPasswordRequired`, so nothing is stored.

I can see how this can be surprising, but this doesn't appear to be something we can address in the short-term.
