### ISSUE TITLE
can't find response body when API fails

### ISSUE THREAD

**Issue by Defwentz** [aws-amplify/amplify-js#6661]
**Describe the bug**
The lambda is setup with APIGateway and in the lambda it is set to return with
```
{
  'statusCode': 400,
  'body' : str(e),
  'headers': HEADERS
}
```
but I can't find the `body` in the error object. Things should be setup properly because in the browser network tab, I was able to find my response body. Or please let me know if this is hidden for a particular reason.
**To Reproduce**

1. Setup a lambda and an API gateway to trigger it return 
```
{
  'statusCode': 400,
  'body' : 'Please find this.',
  'headers': HEADERS
}
```
2. Send request with this in a react app.
```
try {
  const response = await API.get(apiName, path, myInit)
} catch (e) {
  console.dir(e)
}
``` 
3. Check browser console for the error object, and find `body: 'Please find this.'` somewhere.

**Expected behavior**
Be able to see the body in the response.

**What is Configured?**
The setup for lambda and apigateway is done through cloudfromation, here is the the lambda and apigateway setup, there is cognito userpool invovled but I believe it is not an issue in this matter since pretty much everything else is working as expected in the react app: 
```
ExampleLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/example_lambda/
      FunctionName: ExampleLambda
      Handler: index.handler
      Runtime: python3.6
      Role:
        !GetAtt ExampleLambdaRole.Arn
      Events:
        WebAppGateWay:
          Type: Api
          Properties:
            Path: /
            Method: any
            RestApiId: !Ref ExampleAPI
  ExampleAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: ExampleAPI
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST'"
        AllowOrigin: "'*'"
        AllowHeaders: "'x-amz-security-token,x-amz-date,Accept,Authorization,Content-Type,CognitoToken'"
      DefinitionBody:
        swagger: 2.0
        schemes:
          - https
        info:
          title:
            Ref: AWS::StackName
        securityDefinitions:
          cognitoUserPool:
            type: apiKey
            name: CognitoToken
            in: header
            x-amazon-apigateway-authtype: cognito_user_pools
            x-amazon-apigateway-authorizer:
              type: cognito_user_pools
              providerARNs: !Ref UserpoolArn
        paths:
          "/":
            post:
              security:
                - cognitoUserPool: []
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ExampleLambda.Arn}/invocations"
              responses: {}
            get:
              security:
                - cognitoUserPool: []
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ExampleLambda.Arn}/invocations"
              responses: {}
```

**Additional context**
I have found a couple of related issues but they don't seen to be active anymore. 
#4144 : I have checked `error.response.data`, but it's always `null` for me.
aws-amplify/amplify-ios#655 : This is from amplify-ios, I'm not sure if it's the case as with amplify-js?

Edit: adding versions used in react app
```
    "aws-amplify": "^1.2.2",
    "aws-appsync": "^1.8.0",
    "aws-sdk": "^2.550.0",
```
Edit: Updated to the latest, issue still exists.
```
    "aws-amplify": "^3.0.24",
    "aws-appsync": "^4.0.0",
    "aws-sdk": "^2.740.0",
```

**Comment by ericclemmons** [comment]
1. Did you enable CORS in API Gateway?

  > https://docs.amplify.aws/lib/restapi/authz/q/platform/js#customizing-http-request-headers

1. Can you provide any console errors/warnings, or export the HAR file so we can view the Network request(s)?

**Comment by Defwentz** [comment]
Apologies, only just see this, didn't think anyone would respond after a while. Thanks for taking a look.

> 1. Did you enable CORS in API Gateway?
I think I did. According this doc [Enabling CORS for a REST API resource](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html), the last section **Enabling CORS support for Lambda or HTTP proxy integrations**, I have headers added in the return value of my lambda, although mine is slightly different:
`{ 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' , "Access-Control-Allow-Credentials" : True }`

> 1. Can you provide any console errors/warnings, or export the HAR file so we can view the Network request(s)?
I have attached the HAR file, this is when I give an bad parameter and my backend gives error code 400.
Also here is the errors/warnings I see in the console:
```xhr.js:172 GET https://xxxx.execute-api.us-east-1.amazonaws.com/Prod/?payload=%7B%22call%22%3A%22get_subscription_attributes%22%2C%22client%22%3A%22snsss 400
dispatchXhrRequest @ xhr.js:172
xhrAdapter @ xhr.js:11
dispatchRequest @ dispatchRequest.js:59
Promise.then (async)
request @ Axios.js:53
wrap @ bind.js:9
RestClient._signed @ RestClient.ts:288
(anonymous) @ RestClient.ts:148
Promise.then (async)
(anonymous) @ RestClient.ts:147
step @ RestClient.ts:1
(anonymous) @ RestClient.ts:1
(anonymous) @ RestClient.ts:1
push../node_modules/@aws-amplify/api/lib/RestClient.js.__awaiter @ RestClient.ts:1
RestClient.ajax @ RestClient.ts:69
RestClient.get @ RestClient.ts:163
(anonymous) @ API.ts:150
step @ parse-url.ts:19
(anonymous) @ parse-url.ts:19
(anonymous) @ parse-url.ts:19
push../node_modules/@aws-amplify/api/lib/API.js.__awaiter @ parse-url.ts:19
APIClass.get @ API.ts:137
componentDidUpdate @ subedit.js:590
commitLifeCycles @ react-dom.development.js:17349
commitAllLifeCycles @ react-dom.development.js:18736
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18948
(anonymous) @ react-dom.development.js:20418
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20417
performWorkOnRoot @ react-dom.development.js:20346
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
interactiveUpdates$1 @ react-dom.development.js:20495
interactiveUpdates @ react-dom.development.js:2170
dispatchInteractiveEvent @ react-dom.development.js:4882
index.js:1 Error: Request failed with status code 400
    at createError (createError.js:16)
    at settle (settle.js:17)
    at XMLHttpRequest.handleLoad (xhr.js:59)
console.<computed> @ index.js:1
overrideMethod @ react_devtools_backend.js:2450
apiErrHandler @ common.js:129
(anonymous) @ subedit.js:596
Promise.catch (async)
componentDidUpdate @ subedit.js:595
commitLifeCycles @ react-dom.development.js:17349
commitAllLifeCycles @ react-dom.development.js:18736
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18948
(anonymous) @ react-dom.development.js:20418
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20417
performWorkOnRoot @ react-dom.development.js:20346
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
interactiveUpdates$1 @ react-dom.development.js:20495
interactiveUpdates @ react-dom.development.js:2170
dispatchInteractiveEvent @ react-dom.development.js:4882
```
[localhost.txt](https://github.com/aws-amplify/amplify-js/files/5432011/localhost.txt)

**Comment by PabloRN** [comment]
Any luck here?

**Comment by iartemiev** [comment]
The thrown error contains the error message, however, you can access all of the data in the request, including the `body` of the response via the `error.response` object.

Please see the first paragraph of the [docs for Fetching data](https://docs.amplify.aws/lib/restapi/fetch/q/platform/js).

E.g., 
```js
try {
  const response = await API.get(apiName, path, myInit)
} catch (error) {
  const { data: { body } } = error.response;
  console.log(body);
}
```

**Comment by PabloRN** [comment]
> The thrown error contains the error message, however, you can access all of the data in the request, including the `body` of the response via the `error.response` object.
> 
> Please see the first paragraph of the [docs for Fetching data](https://docs.amplify.aws/lib/restapi/fetch/q/platform/js).
> 
> E.g.,
> 
> ```js
> try {
>   const response = await API.get(apiName, path, myInit)
> } catch (error) {
>   const { data: { body } } = error.response;
>   console.log(body);
> }
> ```

My error.response is coming with an empty/null data :(

**Comment by tom-wagner** [comment]
FWIW I am seeing the same thing and `error.response.data` is `null`

![image](https://user-images.githubusercontent.com/5388568/126564374-3b874a7b-08cf-4635-acd3-73c44c2f0891.png)

**Comment by hkjpotato** [comment]
I cannot reproduce this issue

**Comment by ynnr85** [comment]
any fix?

**Comment by ynnr85** [comment]
> FWIW I am seeing the same thing and `error.response.data` is `null`
> 
> ![image](https://user-images.githubusercontent.com/5388568/126564374-3b874a7b-08cf-4635-acd3-73c44c2f0891.png)

Did you fix this?

**Comment by wanderSX** [comment]
Any updates on this one?
