### ISSUE TITLE
S3 storage.get()

### ISSUE THREAD

**Issue by asatvilker** [aws-amplify/amplify-js#6662]
**Describe the bug**
When i run storage.get() function and retrieve the object url of a picture stored in s3 (public folder and storage bucket is the one created when you add storage from cli in amplify project). I save that url to a dynamo db table and then on another page I attempt to get that object url from the table and display it. For some reason when i do this, it displays in some browsers but not others. However it isn’t consistent. For example when I upload the first object url and try it and use it on another page it doesn’t display in safari. However if i repeat the process identically (upload the same object url to my database and then use it on the other page), it displays it.
When i checked the requests in the developer tools, it is showing as a 403 forbidden error. However this doesn’t make sense as in the example above ive tried the same thing twice, yet one request for the image from s3 is successful but the other isnt? Ive also experienced it where the first upload works but the second doesnt.
Is there anyway to help with this?
Also, note that the bucket is public so there should be no restriction issue?

**Comment by elorzafe** [comment]
@asatvilker 

Is not recommend to persist the URL storage.get(), that url is signed url that expires, so I am thinking that what you are experiencing is that the url is expired.

The `public` prefix means that any user (guest/authenticated) that you have enabled on that Amplify project can have read/write access. It doesnt mean the bucket is public (that is a bad practice)

What use case are you trying to achieve?
