### ISSUE TITLE
Auth sign in is no longer returning correct username

### ISSUE THREAD

**Issue by paulsjohnson91** [aws-amplify/amplify-js#6667]
**Describe the bug**
I've had to do a user migration to get google auth to work and to preserve the 'sub' of the original users, I've set up the migration script so that the sub becomes their username. However the response from Auth signin is the username as the email address.

<img width="1105" alt="Screenshot 2020-08-27 at 10 16 15" src="https://user-images.githubusercontent.com/28013436/91421879-5f2b7c80-e84e-11ea-889f-3253bf99d479.png">
This image is a screenshot of the user in cognito, where you can see the username is a48acca5-02ee-409a-873c-e3c86b0d3af2
<img width="1057" alt="Screenshot 2020-08-27 at 10 16 58" src="https://user-images.githubusercontent.com/28013436/91421964-7a968780-e84e-11ea-8ed1-a44891baa3b2.png">

However the login response from Cognito is
```
CognitoUser {username: "paul.johnson@billyhill.co.uk", pool: CognitoUserPool, Session: null, client: Client, signInUserSession: CognitoUserSession, …}
Session: null
attributes:
birthdate: "1991-09-11"
email: "paul.johnson@billyhill.co.uk"
email_verified: true
family_name: "Johnson"
given_name: "Paul"
phone_number: "+123456789"
phone_number_verified: false
sub: "ef4fbf12-4688-44ce-abcb-1997adb215a2"
__proto__: Object
authenticationFlowType: "USER_SRP_AUTH"
```

What's also strange is that I had to set Auth Flow to USER_PASSWORD_AUTH to get the migration trigger to fire however the response shows the auth flow USER_SRP_AUTH.
Nowhere in the response from Amplify Auth is the username of the user mentioned and I really need it.

```
Amplify.configure({
  ...awsConfig,
  region: 'eu-west-1',
  federatedTarget: 'COGNITO_USER_POOLS',
  authenticationFlowType: 'USER_PASSWORD_AUTH',
```
Config ^

**Comment by mogarick** [comment]
@paulsjohnson91 the reason your are getting the email as username may be related precisely to the USER_PASSWORD_AUTH that you used. I've reported an issue a few days ago (#6552) and while digging into it I stumbled with the same behavior when I needed to force the `authenticationFlowType` to `USER_PASSWORD_AUTH`. (https://github.com/aws-amplify/amplify-js/issues/6552#issuecomment-682259256).

**Comment by paulsjohnson91** [comment]
Yes I believe that USER_SRP_AUTH is the default auth flow in amplify that's why I set my config to `USER_PASSWORD_AUTH` however my response still has USER_SRP_AUTH in

**Comment by ericclemmons** [comment]
@paulsjohnson91 So I can understand better, you're saying that you're manually setting Amplify to use `USER_PASSWORD_AUTH`, but the authentication flow is returning `USER_SRP_AUTH` (which means you're getting a different `user.sub` value than what you're expecting)?
