### ISSUE TITLE
[aws-amplify-react-native] Ability to change colors errorIconColor, errorIconColor, placeholderColor with theming

### ISSUE THREAD

**Issue by jeromeheissler** [aws-amplify/amplify-js#6668]
**Is your feature request related to a problem? Please describe.**
Colors defining in `AmplifyTheme.ts` : `errorIconColor` `errorIconColor` `placeholderColor`  can't be changed with theming because there are directly imported and used as constant.
 
**Describe the solution you'd like**
A way to change those variable with extra props.
For example we can add to SignIn component a prop placeholderColor in ISignInProps and pass it to FormField

**Comment by tannerabread** [comment]
Closing as this should now be possible with [CSS variables](https://ui.docs.amplify.aws/react/theming/css-variables) in UI components

**Comment by mroswald** [comment]
@tannerabread I found this issue as I stumbled upon the same question. Could you elaborate how the UI repo solves this? I don't see support for React Native there.

**Comment by reesscot** [comment]
@mroswald React Native was recently released and is fully themable. See:
https://ui.docs.amplify.aws/react-native/connected-components/authenticator
And theming section:
https://ui.docs.amplify.aws/react-native/theming
https://ui.docs.amplify.aws/react-native/connected-components/authenticator/customization#styling
