### ISSUE TITLE
AmplifyAuthenticator UI Component automatically displays "Sign in with AWS" button after configuring federated sign in

### ISSUE THREAD

**Issue by liamaws** [aws-amplify/amplify-js#6670]
**Describe the bug**
Configuring federated sign in using the amplify cli makes the AmplifyAuthenticator UI Component automatically display a "Sign in with AWS" button in the UI.

**To Reproduce**
1. Configure federated sign in using the amplify cli. 
2. Use the AmplifyAuthenticator UI Component. 

**Expected behavior**
The ability to remove or toggle the "Sign in with AWS" button from being displayed. Personally, I would prefer it not to appear by default.

**Code Snippet**

```
<AmplifyAuthenticator usernameAlias="email" style={{ textAlign: 'center' }}>
            <AmplifyForgotPassword
              usernameAlias="email"
              slot="forgot-password"
              formFields={[
                {
                  type: "email",
                  required: true,
                },
              ]}></AmplifyForgotPassword>
            <AmplifySignIn
              usernameAlias="email"
              slot="sign-in"
              formFields={[
                {
                  type: "email",
                  required: true,
                },
                {
                  type: "password",
                  required: true,
                }
              ]}></AmplifySignIn>
            <AmplifySignUp
              usernameAlias="email"
              slot="sign-up"
              formFields={[
                {
                  type: "email",
                  required: true,
                },
                {
                  type: "password",
                  required: true,
                },
                {
                  type: "phone_number",
                  required: false,
                },
                {
                  type: "locale",
                  value: this.state.lang,
                  inputProps: {
                    type: 'hidden',
                  }
                }
              ]}></AmplifySignUp>
            <div>
              {I18n.get("WAIT_REDIRECTION")}
              <AmplifySignOut />
            </div>
          </AmplifyAuthenticator>

```

**Screenshots**
The "Sign in with AWS" button appears automatically. It redirects to the hosted UI.
![image](https://user-images.githubusercontent.com/67014943/91490295-39b76680-e880-11ea-9549-de3e2fd9fc6b.png)

**What is Configured?**
* Which resources do you have configured?
```
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xXGwNABGT",
    "aws_user_pools_web_client_id": "7p0ujr64uoflelsulef9tjhrmo",
    "oauth": {
        "domain": "liamidp-liamidp.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://d2xgofpejqjfcr.cloudfront.net/",
        "redirectSignOut": "https://d2xgofpejqjfcr.cloudfront.net/logout",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "broker-20200504180301-hostingbucket-liamidp",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d2xgofpejqjfcr.cloudfront.net",
    "aws_cloud_logic_custom": [
        {
            "name": "amplifyIdentityBrokerApi",
            "endpoint": "https://80gdodby7c.execute-api.us-east-1.amazonaws.com/liamidp",
            "region": "us-east-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "amplifyIdentityBrokerCodes-liamidp",
            "region": "us-east-1"
        },
        {
            "tableName": "amplifyIdentityBrokerClients-liamidp",
            "region": "us-east-1"
        }
    ]
};
   ```

 

<details>
  <summary><strong>Environment</strong></summary>

```
  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 71.31 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.0 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Firefox: 68.8.0
    Safari: 13.1.2
  npmPackages:
    @aws-amplify/ui-react: ^0.2.15 => 0.2.13 
    @testing-library/jest-dom: ^5.11.3 => 5.11.0 
    @testing-library/react: ^10.4.8 => 10.4.6 
    @testing-library/user-event: ^12.1.1 => 12.0.11 
    aws-amplify: ^3.0.24 => 3.0.22 
    axios: ^0.19.2 => 0.19.2 
    jwt-decode: ^2.2.0 => 2.2.0 
    react: ^16.13.1 => 16.13.1 
    react-app-rewired: ^2.1.6 => 2.1.6 
    react-dom: ^16.13.1 => 16.13.1 
    react-router-dom: ^5.2.0 => 5.2.0 
    react-scripts: 3.4.3 => 3.4.1 
  npmGlobalPackages:
    @aws-amplify/cli: 4.27.2
    ask-cli: 2.13.0
    nodemon: 2.0.4
    npm: 6.14.8
    serve: 11.3.2
    serverless: 1.73.1

```

</details>

**Comment by IvanLjubicic** [comment]
Hi guys,

do we have any solution to remove in the current version? I try to play around with css a bit, but unsuccessful at the moment.

Thanks.

**Comment by andriworld** [comment]
I made the Sign in with AWS button go away by passing an empty federated config to the AmplifySignIn component

VueJS:
`<amplify-sign-in :federated.prop="{}" ...`

React (haven't tried this as I am on VueJS):
`<AmplifySignIn  federated={{}}  ....`

FYI - in previous versions, I was just removing the oauth configuration, but this no longer seems to work:
`delete awsconfig['oauth']`

**Comment by IvanLjubicic** [comment]
Did you maybe tried Angular version? I am using Ionic with Angular

**Comment by andriworld** [comment]
@IvanLjubicic the underlying code is the same on all platforms. As long as you know how to pass an empty object {} to the federated property, it should work.

**Comment by liamaws** [comment]
I'm using react and tried `<AmplifySignIn federated={{}}`. 
When I first load the page I see the "Sign in with AWS" button but when I toggle translation (re-render) it disappears.


First like this
![image](https://user-images.githubusercontent.com/67014943/92144246-6f120600-ede4-11ea-847e-e4c730521e1d.png)
Then after clicking top button to translate to French then back to English
![image](https://user-images.githubusercontent.com/67014943/92144296-7fc27c00-ede4-11ea-8b8d-5789fe3bac7f.png)

Currently deployed here https://d14bd1vuw87prr.cloudfront.net

**Comment by IvanLjubicic** [comment]
I used 

`<amplify-authenticator *ngIf="isCordova" framework="ionic" class="white-text" federated></amplify-authenticator>`

on Angular/Ionic and it works fine currently.

Is there some elegant way to change "Sign in with AWS" text on the button?

**Comment by jordanranz** [comment]
After some investigation, this behavior is expected and carried over from the previous version of the UI library's authenticator.

This being said, I am going to work on a new PR to expose a `slot` to customize (or remove) both the `federated-buttons` section and each individual button.

**Comment by xavierraffin** [comment]
Can you please give control on the link and text of the component too? 
Like being able to remove the _No account?_ __Create account__ section
That will be very helpful to give full control over the component content to Amplify users.

**Comment by andriworld** [comment]
Along the lines of @xavierraffin's suggestion, since you're adding slots, I would like to be able to add HTML text: "By creating an account, I agree to the Terms and Conditions" with hyperlink.

**Comment by jordanranz** [comment]
@andriworld, this may already be possible. Where would this text be located? Feel free to ping me on Discord if you want to DM.

**Comment by xavierraffin** [comment]
> Along the lines of @xavierraffin's suggestion, since you're adding slots, I would like to be able to add HTML text: "By creating an account, I agree to the Terms and Conditions" with hyperlink.

See also #6752 @andriworld

**Comment by xavierraffin** [comment]
It works. This remove the label:
```
<AmplifySignIn slot="sign-in">
  <div slot="federated-buttons"></div>
</AmplifySignIn>
```

This issue can be closed

**Comment by campbellgoe** [comment]
With React all I had to do was add the `federated` prop like this

```jsx
<AmplifySignIn
  slot="sign-in"
  federated
/>
```

which removed the 'Sign in with AWS' button.
