### ISSUE TITLE
Non-syncable models prevent SyncEngine start

### ISSUE THREAD

**Issue by abdielou** [aws-amplify/amplify-js#6671]
**Describe the bug**
Non-syncable models prevent SyncEngine start. Sync Queries are NOT generated for Non-Syncable Models, but the `syncQueriesObservable` method still tries to wait on them.

This is an unusual error because Models in the generated schema (`src/models/schema.js`) have the property `syncable` set to true by default.

**To Reproduce**

1. Init Amplify, add GQL, enable DataStore, add Codegen.
2. Create at least 2 Models in your schema.
3. Modify the generated schema (`src/models/schema.js`) and set one of the models to `syncable: false`
4. Push
5. Run your app.
6. Although the DataStore reports "Realtime ready", it never goes online and nothing gets synced.

**Expected behavior**
Skip non-syncable models.

**Code Snippet**
**_I think_** the problem is here:
https://github.com/aws-amplify/amplify-js/blob/main/packages/datastore/src/sync/index.ts#L380-L401

And the solution might be to filter `syncable` models.

**Comment by ashika01** [comment]
@abdielou : Just wanted to confirm, I see you mention `push` after modifying the scheme, did you run codegen again after modifying the scheme before pushing the changes?

**Comment by elorzafe** [comment]
@abdielou why happen if you dont use `@model` directive for the type you dont want to sync?

**Comment by abdielou** [comment]
> did you run codegen again after modifying the scheme before pushing the changes?

@ashika01 yes

**Comment by abdielou** [comment]
>  dont use `@model` directive for the type you dont want to sync?

@elorzafe I need this be a top entity with `@auth`, `@key`, and `@connection`. It just can't be synced locally because it's going to be a big collection. It will still be accessed through pure GQL.

**Comment by amhinson** [comment]
@abdielou Are you still seeing this behavior? I just ran through the steps you provided with setting `syncable` to `false` on one model, but the other models appear to be syncing as expected. Let me know 👍

**Comment by abdielou** [comment]
> @abdielou Are you still seeing this behavior?...

let me check 🎉

**Comment by abdielou** [comment]
@amhinson Still not syncing with the latest Amplify version.

What might be happening to you is that you are probably turning off SYNC on the **last** model. Try turning off SYNC on the first model.

Here's a sample schema
```gql
type MyModel1 @model {
  id: ID!
  name: String!
  description: String
}

type MyModel2 @model {
  id: ID!
  name: String!
  description: String
}
```
And here's the generated DataStore schema with the first model with SYNC off:

```javascript
export const schema = {
    "models": {
        "MyModel1": {
            "name": "MyModel1",
            "fields": {
                "id": {
                    "name": "id",
                    "isArray": false,
                    "type": "ID",
                    "isRequired": true,
                    "attributes": []
                },
                "name": {
                    "name": "name",
                    "isArray": false,
                    "type": "String",
                    "isRequired": true,
                    "attributes": []
                },
                "description": {
                    "name": "description",
                    "isArray": false,
                    "type": "String",
                    "isRequired": false,
                    "attributes": []
                }
            },
            "syncable": false,
            "pluralName": "MyModel1s",
            "attributes": [
                {
                    "type": "model",
                    "properties": {}
                }
            ]
        },
        "MyModel2": {
            "name": "MyModel2",
            "fields": {
                "id": {
                    "name": "id",
                    "isArray": false,
                    "type": "ID",
                    "isRequired": true,
                    "attributes": []
                },
                "name": {
                    "name": "name",
                    "isArray": false,
                    "type": "String",
                    "isRequired": true,
                    "attributes": []
                },
                "description": {
                    "name": "description",
                    "isArray": false,
                    "type": "String",
                    "isRequired": false,
                    "attributes": []
                }
            },
            "syncable": true,
            "pluralName": "MyModel2s",
            "attributes": [
                {
                    "type": "model",
                    "properties": {}
                }
            ]
        }
    },
    "enums": {},
    "nonModels": {},
    "version": "07f7853b2bff9e14e1be4ba2f4e0d88d"
};
```

`MyModel1 ` has ` "syncable": false,`

**Comment by amhinson** [comment]
@abdielou Hmm that is strange! Even if I turn `syncable` to `false` on the first model, the 2nd model is syncing correctly. Here's what I have:
```
type Post @model {
  id: ID!
  title: String!
}

type Note @model {
  id: ID!
  title: String!
}
```

<details>
<summary>schema.js</summary>

```
export const schema = {
    "models": {
        "Post": {
            "name": "Post",
            "fields": {
                "id": {
                    "name": "id",
                    "isArray": false,
                    "type": "ID",
                    "isRequired": true,
                    "attributes": []
                },
                "title": {
                    "name": "title",
                    "isArray": false,
                    "type": "String",
                    "isRequired": true,
                    "attributes": []
                }
            },
            "syncable": false,
            "pluralName": "Posts",
            "attributes": [
                {
                    "type": "model",
                    "properties": {}
                }
            ]
        },
        "Note": {
            "name": "Note",
            "fields": {
                "id": {
                    "name": "id",
                    "isArray": false,
                    "type": "ID",
                    "isRequired": true,
                    "attributes": []
                },
                "title": {
                    "name": "title",
                    "isArray": false,
                    "type": "String",
                    "isRequired": true,
                    "attributes": []
                }
            },
            "syncable": true,
            "pluralName": "Notes",
            "attributes": [
                {
                    "type": "model",
                    "properties": {}
                }
            ]
        }
    },
    "enums": {},
    "nonModels": {},
    "version": "084a39b57e154fc17be5a10293c931a4"
};
```

</details>

Sync response:
![image](https://user-images.githubusercontent.com/17091790/99119195-b1f31580-25ad-11eb-81bf-8a8cff430d46.png)


Would you be able to create a small sample repo that shows the behavior you're seeing?

**Comment by abdielou** [comment]
@amhinson Huh...

would you mind checking out my repo and trying it out?

https://github.com/abdielou/amplifybug6671

**Comment by amhinson** [comment]
@abdielou I have your sample running, but it appears the sync behavior is working as expected. Am I missing something in the reproduction steps?

![image](https://user-images.githubusercontent.com/17091790/99281521-72b00900-27e7-11eb-8227-69d13e6c3d04.png)

**Comment by abdielou** [comment]
@amhinson Sorry for the delay. You are right, it is working just fine. I could not reproduce the problem, so I'll assume I messed up my tests.

Thanks for checking this out!

closing...
