### ISSUE TITLE
Not possible to use MqttOverWsProvider in graphql subscription requests

### ISSUE THREAD

**Issue by bukerok** [aws-amplify/amplify-js#6675]
**Describe the bug**
Before 2.* version (1.3.3 latest version where everything works) graphql subscription request [was executed](https://github.com/aws-amplify/amplify-js/blob/aws-amplify%401.3.3/packages/api/src/API.ts#L476) and data from the response (`extensions`) was ussed to create subscription. From version 2 all subscription requests doesn't get executed and [tries to start web socket connection to grapql endpoint specified in aws config](https://github.com/aws-amplify/amplify-js/blob/main/packages/api-graphql/src/GraphQLAPI.ts#L337).

`
Amplify.addPluggable(new MqttOverWSProvider({
  clientId: 'xxx',
  url: 'wss://xxx.iot.us-west-2.amazonaws.com/mqtt',
}));
`
Adding code snippet above doesn't do anything on subscription request.
It is used only when I directly call `PubSub.subscribe` with required values.

**Expected behavior**
PubSub should be called with details from subscription request.

Please, advise, how can I use mqtt provider with latest aws-amplify.

**Comment by elorzafe** [comment]
@bukerok why you need to connect to GraphQL subscription using that provider instead of API category?

**Comment by bukerok** [comment]
@elorzafe 

> @bukerok why you need to connect to GraphQL subscription using that provider instead of API category?
> 

Could you please explain, what do you mean by "API category"?

**Comment by bukerok** [comment]
I'm connecting to AppSync (AWS GraphQL implementation) via Amplify.
Earlier subscription request was executed to GraphQL endpoint, and data from the response was used to create websocket connection. As I understood, now subscription request tries to create websocket connection to GraphQL endpoint provided in configuration.

./awsconfig.js
```
{
  ...
  aws_appsync_graphqlEndpoint: 'https://my.domain/graphql'
}
```

How can I configure Amplify in such manner to use a websocket from my subscription response?

**Comment by bukerok** [comment]
@elorzafe Could you, please, help?

**Comment by ericclemmons** [comment]
I'm having trouble understanding what's needed.  `API.graphql(...).susbcribe` correctly returns a subscription to AppSync.

Can you describe your specific use-case?  I understand that `Amplify.addPluggable(...)` isn't giving you the desired results, but I'm uncertain if you're trying to query/subscribe to mutations or something else.

Thanks!
