### ISSUE TITLE
How to disable default bucket level prefix?

### ISSUE THREAD

**Issue by alexsmartens** [aws-amplify/amplify-js#668]
Here is original MyS3Bucket  structure:
```
.
├── MyFolder1
├── MyFolder2
```

After using Amplify it's changed to this:
```
.
├── MyFolder1
├── MyFolder2
├── public 
|   ├── MyFolder1
|    |   ├── FileName
```

Here is how I put objects to the storage:
```
   Storage.put( '/MyFolder1/FileName', blob, { contentType: 'image/jpeg' })
    .then(result => {
      console.log('--result')
     console.log(result)
    })
    .catch(err => {});
```
I also tried 
```
   Storage.put( '/MyFolder1/FileName', blob, { contentType: 'image/jpeg' , level:'public' })
    .then(result => {
      console.log('--result')
     console.log(result)
    })
    .catch(err => {});
```
and 
```
   Storage.put( '/MyFolder1/FileName', blob, { contentType: 'image/jpeg', level:'private' }) })
    .then(result => {
      console.log('--result')
     console.log(result)
    })
    .catch(err => {});
```
which basically stores the files to directories with the `public `or `private ` root correspondingly. 

PROBLEM: how to disable the default prefix (`public` or `private ` ) to be able to store files directly to folders in the bucket (to `MyFolder1` for example) ?

**Comment by richardzcode** [comment]
The default public/private directories has default security policy setup by MobileHub. They are convenient for many use cases. However we do see other cases. My colleague is working on the request. Will be available soon.
