### ISSUE TITLE
Different answers mutation/subscription

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-js#6683]
i get two different answers after a mutation and a subscription

**Amplify CLI Version**
4.18.0

**Screenshots**
<img width="593" alt="Bildschirmfoto 2020-05-26 um 14 56 39" src="https://user-images.githubusercontent.com/7137361/82904269-7febe980-9f62-11ea-8206-4eff54e3716c.png">
<img width="581" alt="Bildschirmfoto 2020-05-26 um 14 56 50" src="https://user-images.githubusercontent.com/7137361/82904273-81b5ad00-9f62-11ea-84f3-e22b45c2c7f9.png">

As you can see here is aivy_output and also config.zScore_mean again stringified in subscription data.
I always log out what I get back after the call

All incorrect fields are type = AWSJSON

```type Answer
  @model
  @auth(rules: [{ allow: owner }, { allow: private, provider: iam }])
  @key(
    name: "ByExamId"
    fields: ["exam_id", "createdAt"]
    queryField: "answersByExamIdByDate"
  )
  @key(name: "ByOwner", fields: ["owner"], queryField: "answersByOwner") {
  id: ID!
  owner: String!
  exam_id: String!
  config: ExamConfig @connection(name: "configs", keyField: "exam_id")
  cycle: Int
  user_input: AWSJSON
  aivy_output: AWSJSON
  rating: Int
  score: Float
  version: Int
  os: String
  createdAt: String
  updatedAt: String
}

type ExamConfig @model {
  id: ID!
  answers: Answer @connection(name: "configs", keyField: "id")
  item_count: Int
  zscore_mean: AWSJSON
  zscore_deviation: AWSJSON
  heighest_score_answer: AWSJSON
}

```

**Comment by yuth** [comment]
I have transferred the issue to Amplify JS team as they should be able help you better
