### ISSUE TITLE
[ui-component] AmplifySignUp formFields does not accept a type 

### ISSUE THREAD

**Issue by mayt** [aws-amplify/amplify-js#6689]
**Describe the bug**
AmplifySignUp formFields does not accept custom types like date, time, etc.

**To Reproduce**
```
        <AmplifySignUp
          slot="sign-up"
          formFields={[
            { type: "date", placeholder:"date", label: "date" },
          ]}
        />
```

**Expected behavior**
Expect a date picker to show up. But a text field is rendered.

**Comment by mayt** [comment]
I created a pr to resolve this issue https://github.com/aws-amplify/amplify-js/pull/6690

**Comment by johnthatfield** [comment]
Someone please approve this

**Comment by wlee221** [comment]
Hi, sorry about the delayed response. Please note that you can set input `type` through `inputProps`:

```
formFields={[
	{
		placeholder: 'date',
		label: 'date',
		inputProps: { type: 'date' },
	},
]}
```

But we see the value in merging #6690 to make this implementation simpler + intuitive. Please use the above method while we review #6690.

**Comment by wlee221** [comment]
Closing as #6690 is merged. This will be published in the next release cycle.

**Comment by mayt** [comment]
Thanks @wlee221
