### ISSUE TITLE
Is it possible to customize/change the default username generated for identify federation?

### ISSUE THREAD

**Issue by ignaciolarranaga** [aws-amplify/amplify-js#6692]
I've basically follow the instructions to set up the federated sign in (here for example: https://docs.amplify.aws/lib/auth/social/q/platform/js#setup-frontend) but I noticed the created username refers to the ID of the federation (e.g. Facebook_23469123419831).

The issue I have is that I doesn't want to expose the real user identity.

Is there any way to change the generated user id? (e.g. assigning a uuid for example).
Shouldn't this be the default by the way ?

**Which Category is your question related to?**
Auth

**Amplify CLI Version** 
4.27.3

**Comment by akshbhu** [comment]
Hi @ignaciolarranga

This question seems related to JSLib while setting up frontend. I am transferring this to JS team , they will help you for this issue.

**Comment by harrysolovay** [comment]
Unfortunately this is unsupported by both the AmplifyJS library and the Cognito service itself. You could, however, utilize a `pre-sign-up` trigger to add a custom attribute to the user. This attribute could then serve as the user's unique identifier within your application.

**Comment by ignaciolarranaga** [comment]
@harrysolovay / @renebrandel the problem with the workaround (use a different ID) is that it will totally eject the owner related amplify transformer auth functionality, none of the things related to owner will work as the owner field will not really match the identity.
