### ISSUE TITLE
Storage.get( { download: true } ) does not get latest version of S3 bucket file after modifying

### ISSUE THREAD

**Issue by coljzh214** [aws-amplify/amplify-js#6693]
Unsure if this is a bug, but encountered some weird caching behaviour with Storage.get() when retrieving file data contents, so this should be clarified. I have an Amplify project that gets data from a text file stored in an S3 bucket made with initializing Amplify storage. The issue is when recent updates are made on a specific file, like updating the file directly on the management console or calling Storage.put(), Calling Storage.get() with { download: true } to get the file contents will still retrieve the unmodified version of the file, and not the latest version; this issue persists for some short period of time until get() eventually retrieves the latest. I see that the changes are reflected in the metadata of the file when I call Storage.list(), so I am not sure why Storage.get does not get the changed file immediately. I doubt if this is expected behaviour, why does this happen? Any way to resolve this issue?

Project was initialized with amplify init and S3 storage resources were made by calling amplify add storage.

A short example of how I use Storage.get():

`Storage.get('file-name', {
            download: true
        })
            .then(data => {
                data.Body.text().then(string => {
                  // handle the String data
                  return String
                });
            })
            .catch(e => {
                 // handle error
            });`

**Comment by Jaftem** [comment]
Similar issue (that's also unresolved) here: @6413

**Comment by wei** [comment]
I tried to reproduce in both 
 - React: https://github.com/wei/amplify-js-6693-react
 - React Native iOS: https://github.com/wei/amplify-js-6693-reactnative

and they both worked just fine. Could you pull down my project and check on your end? or provide a minimal reproducable example like the ones I have with latest cli and npm package versions? Thank you!

**Comment by wei** [comment]
By default, the HTTP Headers returned by S3 looks something like follows:
```
HTTP/1.1 200 OK
Content-Type: application/json
Access-Control-Allow-Origin: *
Last-Modified: Wed, 18 Nov 2020 16:53:16 GMT
Access-Control-Allow-Methods: GET, HEAD, PUT, POST, DELETE
Access-Control-Expose-Headers: x-amz-server-side-encryption, x-amz-request-id, x-amz-id-2, ETag
Date: Wed, 18 Nov 2020 17:49:49 GMT
Content-Length: 14
Accept-Ranges: bytes
ETag: "XXXXXXXX"
Vary: Origin, Access-Control-Request-Headers, Access-Control-Request-Method
x-amz-id-2: XXXXXXXXxX
Server: AmazonS3
x-amz-request-id: XXXXXXXXXX
```

Note there is no `Cache-Control` or `Expires` headers. When those headers are missing AND `Last-Modified` header is present, browsers calculates what's called **Heuristic freshness** and sets its own ttl in cache. e.g. [Firefox docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#Heuristic_freshness_checking)

This results in subsequent requests getting cached by default as seen:

![image](https://user-images.githubusercontent.com/5880908/99568399-5e157180-299d-11eb-894b-3bda61a29bfe.png)

As Harry mentioned in https://github.com/aws-amplify/amplify-js/issues/7095#issuecomment-728355794 Doing something like 
```
Storage.get(filename, { download: true, cacheControl: 'no-cache' })
```
will get S3 to return the appropriate `Cache-Control` headers which eliminates this issue.

**Comment by Zilvinaskli** [comment]
this works now. thanks. What got me confused is that in amplify docs cacheControl parameter is only mentioned in Storage.put part and not in Storage.get

**Comment by wei** [comment]
@Zilvinaskli Setting it in GET is overwriting whatever is stored in S3 object metadata. Setting it in PUT will store the `Cache-Control` as metadata on the object in S3. So if you are sending it in PUT, you don't need to overwrite this option in GET.

**Comment by mauerbac** [comment]
As @wei pointed out this is explained here https://github.com/aws-amplify/amplify-js/issues/6413#issuecomment-729856725
