### ISSUE TITLE
Hide Skip link in VerifyContact (force users to verify contact)

### ISSUE THREAD

**Issue by psaks** [aws-amplify/amplify-js#6697]
Hi,

It does not seem to be possible to hide Skip link in VerifyContact.

Specifically, when we invite users to join (setting email to not verified), they get sent an email with username and temporary password.

Upon login they get prompted to change their password, and then to verify their contact. However, in the VerifyContact form they can just click Skip instead of being forced to verify.

**Comment by elorzafe** [comment]
@psaks you are using UI components?

Can you give more details on which framework you are using?

**Comment by psaks** [comment]
Yes @elorzafe , this is what we have,

`import { AmplifyAuthenticator, AmplifySignIn } from '@aws-amplify/ui-react';`

```
<AmplifyAuthenticator usernameAlias="email">
        <AmplifySignIn slot="sign-in" usernameAlias="email">
              <div slot="secondary-footer-content"></div>
        </AmplifySignIn>
</AmplifyAuthenticator>

```

The `<div slot="secondary-footer-content"></div>` is to hide signUp.

**Comment by tannerabread** [comment]
This is now deprecated and should be handled using the Amplify UI [React Authenticator component](https://ui.docs.amplify.aws/react/connected-components/authenticator)
