### ISSUE TITLE
Async Storage -- AWS amplify error 

### ISSUE THREAD

**Issue by rorobolla** [aws-amplify/amplify-js#6703]
<img width="909" alt="asyncstorageerror" src="https://user-images.githubusercontent.com/70610965/91915034-87204300-ec87-11ea-8d0e-a8056aa3df96.png">

**Hi all I am getting this error with AWS amplify and it only started coming recently. Can someone please point me in the right direction?**

this is my package.json
{
  "name": "masterapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.12.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^5.9.6",
    "@react-native-community/toolbar-android": "0.1.0-rc.2",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "amazon-cognito-identity-js": "^4.3.5",
    "aws-amplify": "^2.1.0",
    "aws-amplify-react-native": "^4.2.5",
    "material-icons": "^0.3.1",
    "native-base": "^2.13.14",
    "neo4j-driver": "^4.1.1",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-gesture-handler": "^1.7.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.2",
    "react-native-profile-picture": "^1.0.0",
    "react-native-reanimated": "^1.13.0",
    "react-native-responsive-screen": "^1.4.1",
    "react-native-safe-area-context": "^3.1.7",
    "react-native-screens": "^2.10.1",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-vector-icons": "^7.0.0",
    "react-navigation": "^4.4.0",
    "react-navigation-stack": "^2.8.2"
  },
  "devDependencies": {
    "@babel/core": "^7.11.4",
    "@babel/runtime": "^7.11.2",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.3.0",
    "eslint": "^7.7.0",
    "jest": "^26.4.2",
    "metro-react-native-babel-preset": "^0.63.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by rorobolla** [comment]
@Ashish-Nanda --> I've tried editing the various files like you mentioned in a previous issue like this but I still get the same error. Can you please advise? Thank you so much!

**Comment by rorobolla** [comment]
@sammartinez Hey Sam are there any updates on this issue? Please let me know. Thanks!

**Comment by sammartinez** [comment]
One thing i do notice @rorobolla is that you are using an older version of `aws-amplify`, have you upgraded to our latest version to validate these errors and warning messages are still present? Please let us know

**Comment by rorobolla** [comment]
@sammartinez Just updated and ran and I am still getting the same error. 
<img width="734" alt="Screen Shot 2020-09-10 at 11 57 07 AM" src="https://user-images.githubusercontent.com/70610965/92758520-cbcd6d80-f35c-11ea-8351-cd84564cdbb6.png">

**Comment by sammartinez** [comment]
Can you provide the your update `package.json`?

**Comment by rorobolla** [comment]
{
  "name": "masterapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.12.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^5.9.6",
    "@react-native-community/toolbar-android": "0.1.0-rc.2",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "amazon-cognito-identity-js": "^4.3.5",
    "aws-amplify": "^3.1.1",
    "aws-amplify-react-native": "^4.2.5",
    "material-icons": "^0.3.1",
    "native-base": "^2.13.14",
    "neo4j-driver": "^4.1.1",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-gesture-handler": "^1.7.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.2",
    "react-native-profile-picture": "^1.0.0",
    "react-native-reanimated": "^1.13.0",
    "react-native-responsive-screen": "^1.4.1",
    "react-native-safe-area-context": "^3.1.7",
    "react-native-screens": "^2.10.1",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-vector-icons": "^7.0.0",
    "react-navigation": "^4.4.0",
    "react-navigation-stack": "^2.8.2"
  },
  "devDependencies": {
    "@babel/core": "^7.11.4",
    "@babel/runtime": "^7.11.2",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.3.0",
    "eslint": "^7.7.0",
    "jest": "^26.4.2",
    "metro-react-native-babel-preset": "^0.63.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by amhinson** [comment]
@rorobolla The first "Error" you are seeing is really just a warning from React Native because of our use of `AsyncStorage`. We are planning to update this soon, but that probably isn't what is causing the issue you are seeing here. 

The error `Reference Error: Can't find variable: i` seems to be the actual error and potentially the 2 below that as well.

Would you be able to share a code sample or repo so we can reproduce what you are seeing?

**Comment by rorobolla** [comment]
So this error only started showing up recently and there are no variables in my code that are referenced as "i". The two below those errors arise when a different error crashes the program so it can't be those two. What parts of the project would you like to see? The project only runs into an error only with the aws-amplify code not when I remove the aws amplify.

**Comment by amhinson** [comment]
If you could provide a small sample app that reproduces the issue you're seeing, that'd be great!

**Comment by rorobolla** [comment]
@amhinson -- I just made a copy and found the error. Was a very stupid mistake. Sorry for wasting your time! Thank you for reaching out and helping though. Really appreciate it.

**Comment by amhinson** [comment]
No problem at all! Glad you figured it out 🙂
