### ISSUE TITLE
Unable to Step into the Code in @aws-amplify/core/lib-esm/I18n using Chrome DevTools

### ISSUE THREAD

**Issue by green-turtle** [aws-amplify/amplify-js#6705]
**Describe the bug**
Chrome `DevTools` can't display the right execution line of code, neither to show the right variable values.

**To Reproduce**

1. Launch a `React` application that utilizes `I18n` in `@aws-amplify` `core` in Chrome
2. Lauch `DevTools`
3. Go to source and locate the `index` file under `@aws-amplify/core/lib-esm/I18n`
4. Put a breakpoint at `line 61``I18n.checkConfig();` or anywhere the caller would call
5. Put a breakpoint in the caller where it calls `I18n.setLanguage('lang')` or the one you choose in step 4
6. Step into `I18n.setLanguage('lang')` from caller's breakpoint 
 
**Expected behavior**
Chrome DevTools to step into `I18n.setLanguage('lang')` function in `@aws-amplify` core, also the local variables could be watched in the watch window

**Comment by nadetastic** [comment]
Hi @green-turtle 👋,

Following up on this issue - let me know if you are still having issues with this.
