### ISSUE TITLE
Many redundant requests, even though properly caching

### ISSUE THREAD

**Issue by bloveless** [aws-amplify/amplify-js#671]
**Do you want to request a feature or report a bug?**

I think this is a bug. Or a misunderstanding on my part.

I checked here https://docs.aws.amazon.com/cognito/latest/developerguide/limits.html and didn't see any specific rate limits for the GetCredentialsForIdentity, but wanted to make sure before I invested too much time into this.

**What is the current behavior?**

On every page load, even though I can see my token, identity id, expires at date in my local storage I get at least two requests to https://cognito-identity.us-west-2.amazonaws.com/ AWSCognitoIdentityService.GetCredentialsForIdentity

I'm wondering if this a bug since everything is cached and the expires_at date has not passed yet.

We've had rate limiting issues with Cognito in the past when we mistakenly sent a request to Cognito on every page load. I assumed that switching to AWS-Amplify would remove these HTTP posts.

Is the GetCredentialsForIdentity function rate limited?

You can see my current implementation in this PR https://github.com/aws/aws-amplify/pull/665

**What is the expected behavior?**

I expected that I would see a request to https://cognito-identity.us-west-2.amazonaws.com/  only once every 5 minutes, not on every page refresh.

**Comment by stormit-vn** [comment]
I also facing this issue too, sometimes it sends to Cognito 6 times with the same request

**Comment by MatteoGioioso** [comment]
Same issue here, every time I switch tab and go back, Amplify is sending exactly 2 requests

**Comment by powerful23** [comment]
@MatteoGioioso these two requests are sent as the session event for the Pinpoint Analytics. If you do not want the auto tracking feature, you can turn it off in your Analytics configuration: https://aws-amplify.github.io/docs/js/analytics#manual-setup

**Comment by mlabieniec** [comment]
Looks like this is solved per the above feature. Please feel free to reopen if you are still having issues with the auto tracking disablement.
