### ISSUE TITLE
User cannot be confirmed. Current status is FORCE_CHANGE_PASSWORD 

### ISSUE THREAD

**Issue by tejpowar** [aws-amplify/amplify-js#6711]
**Describe the bug**
Currently I have my app in beta and therefore inviting users from the userpool as admin. When they receive the email with the verification code they are redirected to the register page.

So the user then fills details in and submits I get the error

"User cannot be confirmed. Current status is FORCE_CHANGE_PASSWORD

Does amplify support this kind of journey?

**To Reproduce**

App specific 

**Expected behavior**
I would expect a function which can potentially deal with this kind of journey

**Comment by p12y** [comment]
You need to call `completeNewPassword` to allow the user to create their own password.

https://aws-amplify.github.io/amplify-js/api/classes/authclass.html#completenewpassword

**Comment by tejpowar** [comment]
had a look at that but as the admin has created the user then i would ideally need this right https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminConfirmSignUp.html
