### ISSUE TITLE
Amplify UI Components add 30 extra http requests to the page

### ISSUE THREAD

**Issue by andriworld** [aws-amplify/amplify-js#6722]
**Describe the bug**

Hi, I'm using the Amplify UI  components (VueJS) for the authentication forms. 

When I build (using NodeJS and Webpack) **the package @aws-amplify/ui-components gets split into 30+ chunks**.

This slows down page load time. Please advise. Thank you

**To Reproduce**

1. Import and use a UI component. E.g using NodeJS+VueJS:

```
import '@aws-amplify/ui-vue';
...
<amplify-authenticator>
```
See https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue#recommended-usage

2. Build
```
$ npm run build

  File                                      Size                Gzipped

  dist/js/chunk-vendors.df12567e.js         1073.49 KiB         281.86 KiB
  dist/js/app.679ed1c7.js                   192.65 KiB          48.60 KiB
  dist/js/polyfills-core-js.82a69570.js     77.35 KiB           25.19 KiB
  dist/js/chunk-53e8269a.68443e25.js        54.13 KiB           12.94 KiB
  dist/js/chunk-7703ec26.d96f4dfc.js        50.36 KiB           17.23 KiB
  dist/js/chunk-661fe092.f7cfae5b.js        48.79 KiB           9.78 KiB
  dist/js/polyfills-dom.85348aed.js         36.74 KiB           5.86 KiB
  dist/js/chunk-1587e9ca.997be431.js        22.50 KiB           5.73 KiB
  dist/js/chunk-10edda1c.3e70453c.js        22.16 KiB           6.03 KiB
  dist/js/chunk-03dc3adf.b17e400c.js        21.30 KiB           5.93 KiB
  dist/js/chunk-f96b8456.e9c711e7.js        19.03 KiB           6.62 KiB
  dist/js/chunk-4dac739c.8414dc8b.js        17.40 KiB           5.50 KiB
  dist/js/chunk-e5bcde22.fec1da6d.js        16.28 KiB           6.12 KiB
  dist/js/chunk-639282bc.44b7fa06.js        16.27 KiB           5.40 KiB
  dist/js/chunk-6df1188a.fc6c228a.js        15.32 KiB           4.63 KiB
  dist/js/chunk-f313ebc4.c131b19e.js        14.97 KiB           4.82 KiB
  dist/js/chunk-07ecccc9.70441b6d.js        14.04 KiB           4.60 KiB
  dist/js/chunk-b667f05a.647519da.js        13.52 KiB           4.29 KiB
  dist/js/chunk-4348acb5.0939ba7b.js        12.79 KiB           4.01 KiB
  dist/js/chunk-12b59d95.8d63eaf4.js        12.64 KiB           3.98 KiB
  dist/js/chunk-39b058d8.b30fa952.js        12.18 KiB           4.16 KiB
  dist/js/polyfills-css-shim.138183fd.js    8.57 KiB            3.40 KiB
  dist/js/chunk-7bc0297f.952c0da5.js        7.98 KiB            2.46 KiB
  dist/js/chunk-645217b6.714922de.js        7.74 KiB            2.72 KiB
  dist/js/chunk-64527702.6db6a7a0.js        6.04 KiB            2.22 KiB
  dist/js/chunk-2d0dd0bc.c4c533f8.js        5.69 KiB            2.41 KiB
  dist/js/chunk-35d5ca8f.af956b51.js        4.14 KiB            1.49 KiB
  dist/js/chunk-2d22dbc9.50b02a1a.js        3.66 KiB            1.15 KiB
  dist/js/chunk-2d0a4629.b491a43a.js        2.07 KiB            0.84 KiB
  dist/js/chunk-2d0b722b.116c2fd9.js        1.99 KiB            0.70 KiB
  dist/js/chunk-2d0abfcf.f1d831f0.js        1.48 KiB            0.66 KiB
  dist/js/chunk-2d22c8fe.57ab6dd0.js        0.91 KiB            0.46 KiB
  dist/js/chunk-2d228cf2.6c018d81.js        0.90 KiB            0.49 KiB
  dist/js/chunk-2d208de0.aef903f4.js        0.54 KiB            0.35 KiB
  dist/css/app.616f3a71.css                 137.65 KiB          21.26 KiB
  dist/css/chunk-vendors.bed4c6f6.css       0.04 KiB            0.06 KiB
```

The first chunk has most of the JS libraries. The second chunk is my code.
All the other .js chunks are from Amplify UI Components

**Expected behavior**
The UI components module should not be split into many small chunks. It should be merged with the rest, or be in its own chunk.

**Code Snippet**
See above

**Screenshots**
![Screen Shot 2020-09-03 at 8 13 21 PM](https://user-images.githubusercontent.com/6136757/92151907-28430100-ee22-11ea-85a0-7ed0eb00162c.png)

![bundles-with-amplify-ui](https://user-images.githubusercontent.com/6136757/92393644-79077200-f120-11ea-98b2-d7c7b692b969.png)

** Environment **
```
    "@aws-amplify/ui-vue": "^0.2.16",
    "aws-amplify": "^3.1.0",
```

Webpack configuration in `vue.config.js`:
```
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
const FaviconsWebpackPlugin = require('favicons-webpack-plugin');

module.exports = {
  devServer: {
    https: true,
    // public: '192.168.1.100'
  },
  configureWebpack: {
    plugins: [
        new FaviconsWebpackPlugin('./src/assets/perform-icon.svg')
        ,process.env.npm_lifecycle_event === 'build' ? new BundleAnalyzerPlugin() : false
    ].filter(Boolean)
  }
}
```

**Comment by jordanranz** [comment]
Hey @andriworld, could you share what it looks like without using `@aws-amplify/ui-components`? Both the request list and bundle image would help.

**Comment by andriworld** [comment]
Hi @jordanranz, thank you for your response.
I have added the webpack configuration to the original post.  It's just the default configuration in VueJS. Note that all the other modules (including amplify) are bundled together. Only the amplify UI components are chunked into separate bundles.

Here's what it looks like if I don't import `'@aws-amplify/ui-vue'`

```
$ npm run build

  File                                   Size                           Gzipped

  dist/js/chunk-vendors.d451dc8f.js      1044.04 KiB                    272.65 KiB
  dist/js/app.f7fe4c91.js                189.00 KiB                     47.00 KiB
  dist/css/app.0699d9cb.css              137.65 KiB                     21.26 KiB
  dist/css/chunk-vendors.bed4c6f6.css    0.04 KiB                       0.06 KiB
```

![bundles-without-amplify-ui](https://user-images.githubusercontent.com/6136757/92392232-3e043f00-f11e-11ea-8f09-b33e4e68e03e.png)

**Comment by ericclemmons** [comment]
This can be seen as part of Stencil's output when building `@aws-amplify/ui-components`. Because sub-components are split up so much (e.g. `amplify-sign-in`), this bubbles up to app.

We can test a PR with `bundles` defined (e.g. `amplify-authenticator`) to confirm that this doesn't create a waterfall in the resulting app:
> https://stenciljs.com/docs/config/testing#bundles

**Comment by andriworld** [comment]
Thanks @ericclemmons.  
> "We can test a PR with bundles defined" 
 Is it something I can help test?
