### ISSUE TITLE
Auth using JWT created through API

### ISSUE THREAD

**Issue by raj-durai** [aws-amplify/amplify-js#6723]
**Is your feature request related to a problem? Please describe.**
I am developing the LTI application using Amplify, signup and sign are on the backend using Lambda when a user launches the application inside the LMS, we need to create the Cognito user through lambda and login in lambda and pass the JWT token to Client. I can't able to login in the client using that JWT token

**Describe the solution you'd like**
I need to do Auth.login using JWT token instead of username and password.
For eg: `Auth.signIn(idToken, accessToken); or similar`

**Describe alternatives you've considered**
I tried API configure auth using JWT, it returns `no user logged in error` when I query the GraphQL
```
Amplify.configure({
  API: {
    graphql_headers: async () => ({
        'Authorization': () => { return: <yourToken> }
    })
  }
});
```

`const listQuery = await API.graphql(graphqlOperation(queries.listQuery));`

also, I need to authenticate the user to access API and Storage.

**Comment by rod-eligible** [comment]
Hey @rajcrystaldelta I'm facing the same scenario

Did you find a workaround in the meanwhile, something you can share?

Thank you

**Comment by rorra** [comment]
hi @rajcrystaldelta

I'm facing the same issue, I have the cognito tokens, but I don't have the customer username/password, yet I need to use appsync

Did you find any workaround, until they finally implement such a fundamental feature into the library?

**Comment by raj-durai** [comment]
Still, We can't find the solution for this.

Any updates from the team?

**Comment by cwomack** [comment]
@raj-durai, wanted to circle back and give a quick update that we plan to have this feature implemented as of the next major version of Amplify.  We'll circle back on this issue again when a release date is finalized, but wanted to keep you informed.  Thank you for taking the time to create this feature request!

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should be resolved.  Can anyone following this issue test it locally (after upgrading) to confirm this?  Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information. Thanks!
