### ISSUE TITLE
User friendly invalid username error

### ISSUE THREAD

**Issue by Graham-Stein** [aws-amplify/amplify-js#6737]
**Describe the bug**
I am still seeing the behaviour described by kennu in  [User friendly invalid username error #3862](https://github.com/aws-amplify/amplify-js/issues/3862)  when a user leaves a trailing space after their user name.
**To Reproduce**
Attempt to log in using Amplify UI with a trailing space after username.
**Desired behaviour**
Present the user with a more user friendly error message.

![image](https://user-images.githubusercontent.com/39591264/92382356-5f583180-f104-11ea-980a-67f55bc21dde.png)

**Comment by jordanranz** [comment]
Could you post which npm version of the amplify libraries you are using from your `package.json`

**Comment by Graham-Stein** [comment]
Thanks for the reply.

`"dependencies": {
    "@aws-amplify/ui-react": "^0.2.8",
    "aws-amplify": "^3.0.17",`

**Comment by Graham-Stein** [comment]
I also get the same result with the latest versions:
    "@aws-amplify/ui-react": "^0.2.18"
    "aws-amplify": "^3.1.1"

**Comment by Graham-Stein** [comment]
Do you need any further information to investigate this issue?

**Comment by isaiahtaylorhh** [comment]
Please prioritize this, we are needing to patch it on our side if it doesn't move soon . Thanks!

**Comment by wlee221** [comment]
Hi all, #7408 fixes this. This is on `unstable` tag and will be released to `latest` by the end of this week. Please let us know if the issue persists!
