### ISSUE TITLE
Safari cannot open the page because the address is invalid

### ISSUE THREAD

**Issue by snowleopardAlex** [aws-amplify/amplify-js#6739]
**Describe the bug**
When I click Sign in with Facebook button and React Native, I see my error in the ios emulator IPhone11 : Safari cannot open the page because the address is invalid. I am using domain generated by Amplify, not my own. 

**To Reproduce**

1. I followed successfully the setup of the app in the Facebook Developer
2. I added Facebook app to AWS configuration, I added App Id, App Secret in User Pool
3. I ADDED code to INFO.PLIST
4. I ADDED code to AppDelegate.m 
3. ERROR: Safari cannot open the page because the address is invalid

**Expected behavior**
I want to sign in with Facebook.

**Screenshots**
My app.js, and package.json, aws-exports.js, aws user pool screenshots

<img width="421" alt="Screen Shot 2020-09-07 at 11 59 56 AM" src="https://user-images.githubusercontent.com/30918532/92405412-806c5280-f103-11ea-8f7e-536b035d0d05.png">
<img width="662" alt="Screen Shot 2020-09-07 at 12 00 18 PM" src="https://user-images.githubusercontent.com/30918532/92405413-8104e900-f103-11ea-8fed-d744f6cb15f0.png">
<img width="600" alt="Screen Shot 2020-09-07 at 12 00 43 PM" src="https://user-images.githubusercontent.com/30918532/92405415-819d7f80-f103-11ea-8a59-58abee5b54bb.png">
<img width="1212" alt="Screen Shot 2020-09-07 at 12 09 23 PM" src="https://user-images.githubusercontent.com/30918532/92405416-82361600-f103-11ea-9596-aa3c7ca3669e.png">
<img width="1206" alt="Screen Shot 2020-09-07 at 12 10 32 PM" src="https://user-images.githubusercontent.com/30918532/92405418-83674300-f103-11ea-9eb2-2d8379c27666.png">
<img width="470" alt="Screen Shot 2020-09-07 at 12 14 51 PM" src="https://user-images.githubusercontent.com/30918532/92405555-db9e4500-f103-11ea-888f-d2d14068d652.png">
<img width="633" alt="Screen Shot 2020-09-07 at 12 15 16 PM" src="https://user-images.githubusercontent.com/30918532/92405557-dc36db80-f103-11ea-829a-c0857eed486b.png">
<img width="488" alt="Screen Shot 2020-09-07 at 12 15 25 PM" src="https://user-images.githubusercontent.com/30918532/92405558-dc36db80-f103-11ea-9400-8b33a8975f12.png">

**What is Configured?**
I followed this tutorial a few times and setup everything what it said:

https://dev.to/aws/the-complete-react-native-guide-to-user-authentication-with-the-amplify-framework-ib2

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone11]
- Browser [safari]

To be honest, I am giving up. I have no IDEA what I am doing wrong... What can be possibly wrong in my project?

**Comment by saachitech** [comment]
@snowleopardAlex Have you configured Amplify with the correct redirect URL for signing in and out? I have following set up and it worked fine

Amplify.configure({
  Auth: {
    ....
    oauth: {
      domain: <your_domain>',
      scope: ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin',],
      redirectSignIn: '<redirect_sign_in_url>',
      redirectSignOut: '<redirect_sign_out_url>',
      responseType: 'code',
      // optional, for Cognito hosted ui specified options
      options: {
       AdvancedSecurityDataCollectionFlag: true
      },
    }
  },
  Analytics: {
    disabled: true
  }

**Comment by teamzz111** [comment]
Try with peticofive://auth/ for redirect sign in and signout.

**Comment by amhinson** [comment]
It looks like you need to update `Info.plist` to use `peticofive` instead of `myapp`

**Comment by varmab** [comment]
Same problem.. None of above solutions worked. Any other tips?

**Comment by amhinson** [comment]
@varmab Could you give some more details about your setup? Did you setup the URI scheme for your app, and does that match the callback & signout URLs in Cognito?
