### ISSUE TITLE
DataStore no syncing with cloud with Sveltejs

### ISSUE THREAD

**Issue by nodroglegin** [aws-amplify/amplify-js#6742]
**Describe the bug**
DataStore works offline and saves successfully. But hooking up AWS Amplify to cloud gives errors for syncing.

This is error I get when listing Todos:
```jsx
"data":{"updateTodo":null},"errors":[{"path":["updateTodo"],"data":null,"errorType":"ConditionalCheckFailedException","errorInfo":null,"locations":[{"line":2,"column":3,"sourceName":null}],"message":"No existing item found in the data source : The conditional request failed (Service: DynamoDb, Status Code: 400, Request ID: EKV6BEOE954VD7TCLJS68SVAJJVV4KQNSO5AEMVJF66Q9ASUAAJG, Extended Request ID: null)"}]}
```

And this error when doing a new   add todo:

```jsx
{"data":null,"errors":[{"path":null,"locations":[{"line":1,"column":20,"sourceName":null}],"message":"Variable 'input' has coerced Null value for NonNull type 'Boolean!'"}]}
```

**To Reproduce**
Code base is here:
[https://github.com/nodroglegin/aws-svelte-offline-first/tree/master/src](https://github.com/nodroglegin/aws-svelte-offline-first/tree/master/src)

This is what I did:

Step 1. Svelte app with webpack template

```jsx
$ npx degit sveltejs/template-webpack my-svelte-app
$ npm install
```

Also, add in Svelte todo app into App.svelte and get working locally.

Step 2. Setup base structure for a DataStore app by adding a new GraphQL API to your app

```jsx
$ amplify init
$ amplify add api
//but need to make some changes to the defaults
// Make sure you respond Yes, I want to make some additional changes 
// when prompted for advanced settings and turn on conflict detection. 
// This setting is required when syncing data to the cloud since the 
// conflict resolution strategy is what allows local data to be 
// reconciled with data from the cloud backend.

// if you have an existing amplify project:
$ amplify update api
// chooose GraphQl and then 
? Select from the options below Enable DataStore for entire API
```

Here are the files and folders that `amplify init` adds:

```jsx
	new file:   amplify.json
	new file:   amplify/.config/project-config.json
	new file:   amplify/backend/api/awsofflinefirst/parameters.json
	new file:   amplify/backend/api/awsofflinefirst/schema.graphql
	new file:   amplify/backend/api/awsofflinefirst/stacks/CustomResources.json
	new file:   amplify/backend/api/awsofflinefirst/transform.conf.json
	new file:   amplify/backend/backend-config.json
	new file:   amplify/team-provider-info.json
```

Step 3. Define data schema

We need to convert  the platform-agnostic schema.graphql into platform-specific data structures. DataStore relies on code generation to guarantee schemas are correctly converted to platform code.

In your terminal, make sure you are in your project/root folder and execute the codegen command:

```jsx
$ amplify codegen models
```

here are the files created by `amplify codegen`:

```jsx
	new file:   src/models/index.d.ts
	new file:   src/models/index.js
	new file:   src/models/schema.d.ts
	new file:   src/models/schema.js
```

Step 4. Initialise Amplify Datastore

```jsx
$ npm install @aws-amplify/datastore aws-amplify @aws-amplify/core
```

Step 5. Import Todo model and Datastore Into Svelte Component

```jsx
import { Todo } from './models';
import { DataStore } from '@aws-amplify/datastore';
```

This is coming in from './models/schema.js

The format of the Todo object is: ie for each todos as todo has to be format of todo.todo.done etc 

```jsx
{
id: 85835u3jdfe03u4,
todo: {
	id: 8,
	done: false,
	description: "take out the trash"
}
```

Step 6. Add functionality to save to local datastore when new todo added:

```jsx
<script>
import { DataStore,Predicates } from '@aws-amplify/datastore';
import { onDestroy,onMount } from 'svelte';
import { quintOut } from 'svelte/easing';
import { crossfade } from 'svelte/transition';
import { Todo } from './models';

const [send, receive] = crossfade({
		duration: d => Math.sqrt(d * 200),

		fallback(node, params) {
			const style = getComputedStyle(node);
			const transform = style.transform === 'none' ? '' : style.transform;

			return {
				duration: 600,
				easing: quintOut,
				css: t => `
					transform: ${transform} scale(${t});
					opacity: ${t}
				`
			};
		}
	});

	let uid = 1;

	let todos = [];

	
	const setTodos = v => (todos = v) 

	async function listTodos() {
		DataStore.query(Todo, Predicates.ALL).then(setTodos);
		
  	}

	// do stuff on mount and dismount
	// set up a const 'subscritpion' that observes any changes to the Todo model
	// if there is a change 
	onMount(listTodos);
  	const subscription = DataStore.observe(Todo).subscribe(listTodos);
  	onDestroy(subscription.unsubscribe)
  

	function add(input) {
		const todo = {
			id: uid++,
			done: false,
			description: input.value
		};

		input.value = '';
		DataStore.save(new Todo({ todo: todo }));
	}

	async function remove(todo) {
		const toDelete = await DataStore.query(Todo, todo.id);
      	DataStore.delete(toDelete)
	}

	async function mark(todo, done) {
		const original = await DataStore.query(Todo, todo.id)
		await DataStore.save(
			  Todo.copyOf(original, (updated) => void (updated.todo.done = done))
			  	)
	}
	
	function clearStore() {
		DataStore.clear();
		todos=[];
	}

</script>

<div class='board'>
	<input
		placeholder="what needs to be done?"
		on:keydown={e => e.key === 'Enter' && add(e.target)}
	>

	<div class='left'>
		<h2>todo</h2>
		{#each todos.filter(t => !t.todo.done) as todo (todo.id)}
			<label
				in:receive="{{key: todo.id}}"
				out:send="{{key: todo.id}}"
			>
				<input type=checkbox on:change={() => mark(todo, true)}>
				{todo.todo.description}
				<button on:click="{() => remove(todo)}">remove</button>
			</label>
		{/each}
	</div>

	<div class='right'>
		<h2>done</h2>
		{#each todos.filter(t => t.todo.done) as todo (todo.id)}
			<label
				class="done"
				in:receive="{{key: todo.id}}"
				out:send="{{key: todo.id}}"
			>
				<input type=checkbox checked on:change={() => mark(todo, false)}>
				{todo.todo.description}
				<button on:click="{() => remove(todo)}">remove</button>
			</label>
		{/each}
		<h2 on:click={clearStore}>Clear</h2>
	</div>
	
</div>

<style>
	.board {
		display: grid;
		grid-template-columns: 1fr 1fr;
		grid-gap: 1em;
		max-width: 36em;
		margin: 0 auto;
	}

	.board > input {
		font-size: 1.4em;
		grid-column: 1/3;
	}

	h2 {
		font-size: 2em;
		font-weight: 200;
		user-select: none;
		margin: 0 0 0.5em 0;
	}

	label {
		position: relative;
		line-height: 1.2;
		padding: 0.5em 2.5em 0.5em 2em;
		margin: 0 0 0.5em 0;
		border-radius: 2px;
		user-select: none;
		border: 1px solid hsl(240, 8%, 70%);
		background-color:hsl(240, 8%, 93%);
		color: #333;
	}

	input[type="checkbox"] {
		position: absolute;
		left: 0.5em;
		top: 0.6em;
		margin: 0;
	}

	.done {
		border: 1px solid hsl(240, 8%, 90%);
		background-color:hsl(240, 8%, 98%);
	}

	button {
		position: absolute;
		top: 0;
		right: 0.2em;
		width: 2em;
		height: 100%;
		background: no-repeat 50% 50% url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'%3E%3Cpath fill='%23676778' d='M12,2C17.53,2 22,6.47 22,12C22,17.53 17.53,22 12,22C6.47,22 2,17.53 2,12C2,6.47 6.47,2 12,2M17,7H14.5L13.5,6H10.5L9.5,7H7V9H17V7M9,18H15A1,1 0 0,0 16,17V10H8V17A1,1 0 0,0 9,18Z'%3E%3C/path%3E%3C/svg%3E");
		background-size: 1.4em 1.4em;
		border: none;
		opacity: 0;
		transition: opacity 0.2s;
		text-indent: -9999px;
		cursor: pointer;
	}

	label:hover button {
		opacity: 1;
	}
</style>
```

Which works! To-dos persist via Data store all locally so far.

**Step 7. Deploy cloud backend**

This works fully offline and we haven't updated anything on AWS yet!

Which is also why the terminal is giving this error:

```jsx
DataStore - Data won't be synchronized. 
No GraphQL endpoint configured. 
Did you forget `Amplify.configure(awsconfig)`
```

If we do `$ amplify status` we will see something like

```jsx
Current Environment: dev

| Category | Resource name   | Operation | Provider plugin   |
| -------- | --------------- | --------- | ----------------- |
| Api      | awsofflinefirst | Create    | awscloudformation |
```

The Create indicates that we haven't yet deployed our Api.

```jsx
$ amplify push
```

When asked `Do you want to generate code for your newly created GraphQL API (Y/n)` we answer no because we are using DataStore to do that.

**Step 8. Tell Svelte App About Amplify Cloud**

Up until now we have just been using Datastore in App.svelte. But now we want to hook up Appsync via the following changes in Main.js

```jsx
import Amplify from '@aws-amplify/core';
import App from './App.svelte';
import aws_exports from './aws-exports';

// in this way you are only importing Auth and configuring it.
Amplify.configure(aws_exports);

const app = new App({
  target: document.body
});

export default app;
```

Getting error back

```jsx
"data":{"updateTodo":null},"errors":[{"path":["updateTodo"],"data":null,"errorType":"ConditionalCheckFailedException","errorInfo":null,"locations":[{"line":2,"column":3,"sourceName":null}],"message":"No existing item found in the data source : The conditional request failed (Service: DynamoDb, Status Code: 400, Request ID: EKV6BEOE954VD7TCLJS68SVAJJVV4KQNSO5AEMVJF66Q9ASUAAJG, Extended Request ID: null)"}]}
```

And this error when doing a new   add todo:

```jsx
{"data":null,"errors":[{"path":null,"locations":[{"line":1,"column":20,"sourceName":null}],"message":"Variable 'input' has coerced Null value for NonNull type 'Boolean!'"}]}
```

**Expected behavior**
Expect Appsync to work in background automatically to save data to DynamoDB.

**Code Snippet**
https://github.com/nodroglegin/aws-svelte-offline-first/tree/master/src

**What is Configured?**
```const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://zaygsihbzzaarbiud7ixgijns4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-f7gm4lq7bnetfbhb3grpuw5nqm"
};


export default awsmobile;
```

 

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

</details>

**Smartphone (please complete the following information):**

**Additional context**

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by sw-yx** [comment]
thanks for filing! it looks like you have two errors here:

- during read: `"errorType":"ConditionalCheckFailedException","errorInfo":null,"locations":[{"line":2,"column":3,"sourceName":null}],"message":"No existing item found in the data source"`
- during add: `Variable 'input' has coerced Null value for NonNull type 'Boolean!'`

for the first one, i suspect it is your usage of `Predicates.ALL` here: https://github.com/nodroglegin/aws-svelte-offline-first/blob/master/src/App.svelte#L41 I'm not sure about that though. to fix, try dropping that predicate and see what happens.

for the second one, i'm pretty sure it's because you give a `todo` field [here](https://github.com/nodroglegin/aws-svelte-offline-first/blob/master/src/App.svelte#L62) whereas [your model](https://github.com/nodroglegin/aws-svelte-offline-first/blob/master/src/models/schema.js#L6-L20) expects `id` (which btw will be autogenerated so you dont actually need to fill it), `completed` and `done`. to fix, replace that line with `DataStore.save(new Todo(todo));`

if i'm right about the first one, we may have a bug. for both, the errors could be much more human readable, cc @undefobj. the second one in particular is leaking the graphql abstraction underneath since the user doesn't know about a "`Variable 'input'`".

**Comment by nodroglegin** [comment]
Thanks @sw-yx : almost working. Now it is sending data to Dynamo db successfully but any changes on Dynamo (eg editing a record there) never come back to the local DataStore.
1. Whether I use Predicates.ALL or not it still works - so you don't seem to have a bug there
2. the edits to todo seem to work.

What I get now on network is:

<img width="717" alt="Screen Shot 2020-09-11 at 9 56 53 am" src="https://user-images.githubusercontent.com/19522332/92841620-24f8d800-f415-11ea-9585-1cc6bbbf3455.png">

And also: 
<img width="1111" alt="Screen Shot 2020-09-11 at 10 01 20 am" src="https://user-images.githubusercontent.com/19522332/92842123-c08a4880-f415-11ea-86f4-6036ed8178b0.png">

It looks like the sync down is always empty - though I'm not sure what is going on exactly.

I have put a new commit [here](https://github.com/nodroglegin/aws-svelte-offline-first/commit/cd41571526de9e0f23bafeaa0d75140bfa6d41f1).

I also added `window.app = app;` to main.js

Any suggestions on what I might need to fix up?

Thanks!

**Comment by sw-yx** [comment]
at this point I would refer you to datastore experts who can help you better

**Comment by nodroglegin** [comment]
Thanks @sw-yx 
@jordanranz - are you able to offer any suggestions?

**Comment by CryogenicPlanet** [comment]
@nodroglegin You should not change dynamodb directly. You should use graphql mutations to make any changes. I think this is because the timestamp is not updated or something along those lines if you interact with graphql directly it will work.
