### ISSUE TITLE
I18n not trasnlating constant files

### ISSUE THREAD

**Issue by PtkFerraro** [aws-amplify/amplify-js#6745]
Hi.

Let]s say I have a constant file (constants.js):

import { I18n } from 'aws-amplify';

```
const constants = {

    REFERENCE_RATINGS: [
        I18n.get("Nível de criatividade"),
        I18n.get("Nível de inovação"),
        I18n.get("Qualidade de entrega"),
        I18n.get("Cumprimento dos prazos"),
        I18n.get("Pensamento estratégico"),
        I18n.get("Relacionamento interpessoal"),
    ]
}

export default constants;
```

When I call Amplify I18n to translate my app, the constant entries are not translated.

I am using Amplify in my React app that uses Amplify + Cognito (I am not using CLI module)

**Comment by jordanranz** [comment]
Could you provide the code usage from these constants? Currently `i18n` is best used inside of the React render method where you would pass the constant to it.

Something like:
```
render() {
  return (
    <div>{I18n.get(constants.IMPORTED_CONSTANT)}</div>
  )
}
```

**Comment by PtkFerraro** [comment]
Hi @jordanranz 

I know that, but even using inside the render method, it fails to translate when comes from constant file... take a look at these tests:

**Constants.js**

```
import { I18n } from 'aws-amplify';

const constants = {

MENU_REGISTER: [
        { label: I18n.get("Usuários"), link: "/parceiro/cadastro/usuarios/", activeMenu: 1 },
        { label: I18n.get("A Empresa"), link: "/parceiro/cadastro/empresa/", activeMenu: 2 },
        { label: I18n.get("Especialidades"), link: "/parceiro/cadastro/especialidades/", activeMenu: 3 },
        { label: I18n.get("Mercados de expertise"), link: "/parceiro/cadastro/expertises/", activeMenu: 4 },
        { label: I18n.get("Trabalhos & Realizações"), link: "/parceiro/cadastro/trabalhos/", activeMenu: 5 },
        { label: I18n.get("Liderança"), link: "/parceiro/cadastro/lideranca/", activeMenu: 6 },
        { label: I18n.get("Clientes"), link: "/parceiro/cadastro/clientes-e-referencias/", activeMenu: 7 },
    ]

}
export default constants;
```


**FormExample.js (not working)** (here I will omit some parts to make the example simple)

```
import React, { Component, Fragment } from 'react';
import { I18n } from 'aws-amplify';
import constants from '../../../constants';

render(){

return (<>
             <Menu
                    itens={constants.MENU_REGISTER}
               />
</>
);

}
```

**Menu.js (not working - I18n in constant file only)**

```
render() {

        const { itens } = this.props;

        return (
            <>
                {itens && itens.map(item => {

                        return (
                                    <Link to={url}>{item.label}</Link>
                        )

                })}
            </>
        );
    }
```

## Even if I change to this won´t work:

**Menu.js (not working part. 2 - added I18n directly in Link getting word from constant)**

```
render() {

        const { itens } = this.props;

        return (
            <>
                {itens && itens.map(item => {

                        return (
                                    <Link to={url}>{ I18n.get(item.label) }</Link>
                        )

                })}
            </>
        );
    }
```

## The dummy fix I did (not clever at all) is:

**FormExample.js (working)**

```
import React, { Component, Fragment } from 'react';
import { I18n } from 'aws-amplify';
import constants from '../../../constants';

render(){

//Dummy solution
let menuRegister = [...constants.MENU_REGISTER];
for (let key in menuRegister) {
    menuRegister[key].label = I18n.get(menuRegister[key].label);
}

return (<>
             <Menu
                    itens={ menuRegister }
               />
</>
);

}
```

**Comment by cwomack** [comment]
@PtkFerraro, apologies on the delayed reply from us on this issue.  As of Aug 2021, the [Internationalization](https://docs.amplify.aws/lib/utilities/i18n/q/platform/js/) section (under Utilities) of the docs has been updated with better instructions for implementation. 

Given that this update came _after_ opening this issue and your most recent comments on it, I'll close this out for now.  Please feel free to comment back if this (as well as an update to the most recent version of Amplify) doesn't solve the situation, and I'd be happy to reopen the issue if there's still a problem with I18n.
