### ISSUE TITLE
Having issues integrating with pinpoint/personalize

### ISSUE THREAD

**Issue by minimalistinnovator** [aws-amplify/amplify-js#6747]
Issue:
After enabling Analytics.addPluggable(new AmazonPersonalizeProvider()), I am experiencing issues with the application (React/Amplify).

```
×
Unhandled Rejection (TypeError): Cannot read property 'userId' of undefined
SessionInfoManager.updateSessionInfo
src/Providers/AmazonPersonalizeHelper/SessionInfoManager.ts:77
```

Configuration (App.js):
```
Analytics.autoTrack('session', {
  enable: true,
  provider: 'AWSPinpoint'
});
Analytics.autoTrack('pageView', {
  enable: true,
  eventName: 'pageView',
  type: 'SPA',
  provider: 'AWSPinpoint',
  getUrl: () => {
    return window.location.origin + window.location.pathname;
  }
});
Analytics.configure({
  AWSPinpoint: {
    // Amazon Pinpoint App Client ID
    appId: 'xxxxxxxxxx',
    // Amazon service region
    region: 'xxxxx',
    mandatorySignIn: false,
  },
  AmazonPersonalize: {
    tackingId: 'xxxxxxxxxxxx',
    region: 'xxxxxxxxx',
    flushSize: 10,
    flushInterval: 5000,
  }
});

Amplify.configure(aws_exports);
Auth.configure();
Storage.configure();
```

**Comment by jordanranz** [comment]
@minimalistinnovator, could you try moving the `configure` methods above any usage of the categories (like Analytics.autoTrack)

**Comment by minimalistinnovator** [comment]
> @minimalistinnovator, could you try moving the `configure` methods above any usage of the categories (like Analytics.autoTrack)

Thank you for prompt response Jordan. The issue persists in the local development environment (amplify serve) even after the switch in code. However, the problem does not occur when I publish to production using amplify publish. The site is [here](https://master.d3i74sih14e4fh.amplifyapp.com/#/) if you want to look into the scripts.
```
Amplify.Logger.LOG_LEVEL = 'INFO'; // We write INFO level logs throughout app
Amplify.configure(aws_exports);
Auth.configure();
Storage.configure();

Analytics.addPluggable(new AmazonPersonalizeProvider());
...
```

**Comment by jordanranz** [comment]
`Amplify.configure(aws_exports)` should configure both `Auth` and `Storage` so you should need those 2 configure lines. I'll keep investigating.
