### ISSUE TITLE
More UI style and slots customization

### ISSUE THREAD

**Issue by xavierraffin** [aws-amplify/amplify-js#6752]
**Is your feature request related to a problem? Please describe.**
Today it is hard to customize the Amplify UI component deeply. While there is the alternative of not using UI components at all, it is a lot of work to reproduce all the screen, manage the auth state and the auth API myself to change a button border radius (this is an example).
 
**Describe the solution you'd like**
What I like to have is:

* __CSS variable at the component level__ Like [this](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#managing-layout-with-css) for _amplify-authenticator_ I like to have variable to customize style at the component level (like amplify-sign-in).
Maybe having a grid/flex system would be nice: some customer wants to have login button full width or on the right or on the left, it will be nice to have some flexibility here.
* __systematically more slots__ It would be nice to have slots before and after each section (at least each component) empty and ready to inject customer code. On some component you already have some like `header-subtitle-slot` but this is not everywhere and not on all components.

**Comment by xavierraffin** [comment]
I saw this one is on roadmap https://github.com/aws-amplify/amplify-js/issues/5750 
If css class injection is fine grained enought that may solve the first point.

Having more slot to give control on what appears or not and layout is still a concern

**Comment by sammartinez** [comment]
The above pull request resolves this issue. Closing this issue as these changes are in our `unstable` branch and will be in the next release.

**Comment by xavierraffin** [comment]
@sammartinez Is there a documentation that explains hot to use the new feature from #6948 ?

**Comment by ncolboc** [comment]
@sammartinez If this feature has been released, could you provide us a sample about how to use it? I also try to find a way to apply custom style on auth components (according to my theme site) without needed to re-create my own auth components. 
thanks in advance for your help.
