### ISSUE TITLE
AmplifyOAuthButton component does not pass provider to Auth.federatedSignIn

### ISSUE THREAD

**Issue by adamkowalczykB2M** [aws-amplify/amplify-js#6760]
Apologies, I'm not sure if this is bug or a feature request, but the way the federated sign in buttons work seems to mean that we cannot currently use an oauth config with a custom provider.

**Describe the bug**

The `AmplifyOAuthButton` component in the `ui-components` package calls `Auth.federatedSignIn` with [no arguments](https://github.com/aws-amplify/amplify-js/blob/main/packages/amplify-ui-components/src/components/amplify-oauth-button/amplify-oauth-button.tsx#L18), which means it cannot be used with a custom provider.

**Expected behavior**

We are using the `AmplifyAuthenticator` component and an oath config with a `domain` configured. The `AmplifyFederatedButtons`  component [extracts ](https://github.com/aws-amplify/amplify-js/blob/main/packages/amplify-ui-components/src/components/amplify-federated-buttons/amplify-federated-buttons.tsx#L30) that config, and adds it to the `federated` prop as `federated.oauthConfig`.

`federated` is passed to the `AmplifyOAuthButton` as a prop, but that component only refers to `federated.oauthConfig` to get the label text for the button. 

I believe `Auth.federatedSignIn` should be called with the `provider` specified in `federated.oauthConfig`, if there is one, otherwise presumably it should be called  with no arguments.

e.g. 
```ts
const options = federated?.oauthConfig?.provider && { provider: federated.oauthConfig.provider };
Auth.federatedSignIn(options);
```

**Comment by jordanranz** [comment]
I'd say this is more of a feature request to add this functionality to that particular button. Thank you for the feedback!

**Comment by hkjpotato** [comment]
@adamkowalczykB2M  Thank you for opening the issue. Would like to get some more info about your setting:
Have you configure `Amplify` before you use the `AmplifyAuthenticator`?
1. when you configure Amplify by `Amplify.configure(awsExports);` you will also add configuration to the [`Auth` instance created](https://github.com/aws-amplify/amplify-js/blob/main/packages/core/src/Amplify.ts#L72). 
2. This way, even if we don't pass in configuration from `federatedSignIn`, the call fired by the `Auth` instance will still get [the domain from its own config](https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/Auth.ts#L1938).

Basically, the `oauth` setting has been delegated by the Auth instance already. Please let me know if this helps address your concern or if I miss something.

Besides, it will be great if you can provide sample data for your oauth config. Mine is like 
```
    "oauth": {
        "domain": "{domain}.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin",
        ],
        "redirectSignIn": "http://localhost:8080/",
        "redirectSignOut": "http://localhost:8080/",
        "responseType": "token"
    },
```

Thanks ahead of time!

**Comment by adamkowalczykB2M** [comment]
Thanks for responding to this @hkjpotato !

I'm afraid I'm not working on code in this area at the moment, so I can't really verify our config.

If you are satisfied that the oauth provider gets passed in via the initial `Auth` configuration then I'm happy to take your word for it and for the issue to be closed.

**Comment by hkjpotato** [comment]
@adamkowalczykB2M no problem! I will close it for now and we can reopen it if you find any other concern. Thank you.
