### ISSUE TITLE
'Rate exceeded' when calling listGroupsForUser admin action a couple times

### ISSUE THREAD

**Issue by tobiasfeil** [aws-amplify/amplify-js#6767]
**Describe the bug**
I have an app with 60 users and am calling `listGroupsForUser` for all of them at the same time. This generates a lot of `400` errors with the following content: `{"message":"Rate exceeded"}`. Is there a way to fix this?

**Comment by ashika01** [comment]
@tobiasfeil Could you provide us with more information? What are using amplify for? API thats getting called? Maybe a sample app/code snippet

**Comment by undefobj** [comment]
This is a Cognito service rate limit. You may want to open a support ticket with the Cognito team.
