### ISSUE TITLE
The conditional request fails when updating sort key of the primary index

### ISSUE THREAD

**Issue by pedramp20** [aws-amplify/amplify-js#6775]
**Describe the bug**
A model defined with a primary index (a key directive without specifying the name) containing a hash and sort key, when updated by a graphql update mutation in which the sort key is changed, the following error is received

```
errorType: "DynamoDB:ConditionalCheckFailedException"
message: "The conditional request failed (Service: DynamoDb, Status Code: 400, Request ID xxxx
```
**To Reproduce**
define a models as follows:

```
type Exercise
	@key(fields: ["id", "name"]) #primary index
	@model
	@auth(
		rules: [
			{ allow: owner, operations: [create, update, delete, read] }
		]
	) {
	id: ID!
	owner: String!
	name: String!
}
```
try to update the model's NAME attribute using an update mutation

```
     const updateInput = {
          id: '1',
          name: 'SOMETHING DIFFERENT'
     }
    await API.graphql(graphqlOperation(updateExercise, { input: updateInput }));

```

**Comment by RossWilliams** [comment]
DynamoDB does not allow this. You need to delete the item and create a new one with your new sort key. This isn't an Amplify issue

**Comment by sammartinez** [comment]
@pedramp20 As based on the feedback above, this seems to be related to DynamoDB specifically instead of Amplify. Resolving
