### ISSUE TITLE
Query M2M models using DataStore

### ISSUE THREAD

**Issue by djou-13** [aws-amplify/amplify-js#6779]
**Is your feature request related to a problem? Please describe.**
Using DataStore with a M2M model. 
Storing data using Datastore is great and easy... getting it back is another story.

To get back the list of editor for a post I ended up writing the following code:
`const editors = (await DataStore.query(PostEditor)).filter( pe.post.id === "123").map( pe => pe.editor );`
Which has one major issue... the filer is applied AFTER the result of the query, i.e. all the items are loaded in memory.
I was expecting to be able to use predicates like
`await DataStore.query(PostEditor, pe => pe.postID("eq", "123" ))`
But codegen do not include postID in the generated schema. If I add it manually, then the predicate works fine. 
Any reason for not adding postID and editorID in the generated schema ?

**Describe the solution you'd like**
Being able to query the list of editor for a post using a single query,
Using something like:
`await DataStore.query(PostEditor, pe => pe.postID("eq", "123" ))`
Or even better something like
`await DataStore.query(Post, "123" , { level: 2} )` or `await DataStore.query(Post, "123" , { include: ["editors"]} )`

**Describe alternatives you've considered**
You can get the result using 
`const editors = (await DataStore.query(PostEditor)).filter( pe.post.id === "123").map( pe => pe.editor );`
But that query first ALL the PostEditor and the does the filtering... This will not scale. 

**Additional context**
This question is related to the example model for M2M in https://docs.amplify.aws/lib/datastore/relational/q/platform/js#many-to-many

**Comment by ecc7220** [comment]
Please, some team member should comment on this.

**Comment by chrisbonifacio** [comment]
Hi @djou-13, we've since changed the syntax for querying relations and now lazy loading is possible.

Please refer to the documentation for examples on how to query relations using the new lazy loading syntax:

https://docs.amplify.aws/lib/datastore/relational/q/platform/js/#querying-relations
