### ISSUE TITLE
AmplifyConfirmSignIn - How to call default handleSubmit condition when customizing

### ISSUE THREAD

**Issue by kkomaz** [aws-amplify/amplify-js#6787]
**Is your feature request related to a problem? Please describe.**
Per documentation the default handleSubmit will call `this.confirmSignup(event)`

![Screenshot of Google Chrome (9-14-20, 5-33-53 PM)](https://user-images.githubusercontent.com/8473884/93144715-a2904280-f6b8-11ea-9d9d-f57b3660ca39.png)

I would like to do some custom function calls AFTER the user successfully confirms his or her account.  I am unable to get access to `this.confirmSignup(event)` and tried to use the `aws-amplify` Auth object to call it but that does not work saying I have the wrong parameters.  How do I call the parent component (AmplifyConfirmSignIn) handleSubmit function in my custom function and get that return value?

```js
function Root() {
  handleSubmit(event) {
    event.preventDefault();
    // Call this.confirmSignup(event);
    console.log('do custom stuff')
  }

  return (
    <AmplifyAuthenticator>
      <AmplifyConfirmSignIn
        headerText="My Custom Confirm Sign In Text"
        slot="confirm-sign-up"
         handleSubmit={handleSubmit}
      >
      </AmplifyConfirmSignIn>
    </AmplifyAuthenticator>
  )
}
```

**Describe the solution you'd like**
I think having a ref to this component can be make the parent component function accessible.

**Describe alternatives you've considered**
I tried using the aws-amplify library directly but that does not work either.

**Comment by Albert-Gao** [comment]
I was wondering this too,

Based on the current class component implementation,

you have 2 options:

1. Check their source code, pick the part you need, and bring it to your project, I know, I know
1. `class MySignIn extends SignIn {}`, I know, anti-pattern, but this works, and can lead to minimal changes. Something like, if you just want to change UI, you rewrite the `showComponent()` method after inheritance. Bbut strangely, for me, it only works when I write this `MySignIn` in the same file with the `Authenticator`. If I put `MySignIn` in another file, it will have a building problem.

I ended up with just copy their logic and remove the part I don't need.

I was talking about react-native, do not know if the React implementation got a function component approach, which will enable this in a much easier way.

**Comment by humblepie** [comment]
The request to be able to access and call the default handler needs to be added to all the handlesubmit events.  ie, sign up, sign in, sign out, etc.

Right now if you hook the handlesubmit event you lose the ability to use the base functionality as well.

**Comment by harrysolovay** [comment]
It looks like you have a type:

```diff
function Root() {
- handleSubmit(event) {
+ const  handleSubmit = (event) => {
    event.preventDefault();
    // Call this.confirmSignup(event);
    console.log('do custom stuff')
  }

  return (
    <AmplifyAuthenticator>
      <AmplifyConfirmSignIn
        headerText="My Custom Confirm Sign In Text"
        slot="confirm-sign-up"
         handleSubmit={handleSubmit}
      >
      </AmplifyConfirmSignIn>
    </AmplifyAuthenticator>
  )
}
```
