### ISSUE TITLE
[Feedback]Application doesn't work for Angular production builds

### ISSUE THREAD

**Issue by BenjaminNielsen** [aws-amplify/amplify-js#6796]
**Page**: [`/start/q/integration/angular`](https://docs.amplify.aws/start/q/integration/angular)

**Feedback**:

When I follow these instructions the application will run with ng build. However, when running ng build --prod the resulting distribution will not run either locally or with the amplify console. The browser inevitably throws the error
ERROR TypeError: Cannot read property 'aws_appsync_region' of null  (on chrome)
or
ERROR TypeError: "r is null" (on firefox)

I've tried this mostly with Angular 10.1.1. I also tried downgrading to angular 9 with the same result.

**Comment by wlee221** [comment]
Hi @BenjaminNielsen, thanks for reporting the issue! I was able to reproduce it so I'll have this issue transferred to our js repo.

**Comment by malcomm** [comment]
+1 on this - my production build just failed when I deployed AWS Console build. Not having production working should make this issue priority 1? Any updates?

**Comment by ericclemmons** [comment]
Thanks for the report! We're working on it!

> https://github.com/aws-amplify/amplify-js/issues/6761

**Comment by ericclemmons** [comment]
For a quick fix, you can manually register Auth via `Amplify.register(AUth)`:
> https://github.com/aws-amplify/amplify-js/issues/6761#issuecomment-697164608

**Comment by BenjaminNielsen** [comment]
> For a quick fix, you can manually register Auth via `Amplify.register(Auth)`:
> 
> > [#6761 (comment)](https://github.com/aws-amplify/amplify-js/issues/6761#issuecomment-697164608)

I was able to push a production build to amplify console after following your suggestion. Thank you!

**Comment by wlee221** [comment]
Hi @BenjaminNielsen and @malcomm, sorry about the delay. We just pushed pr #6867 to `latest` that addresses this. Please try again with the latest amplify and let us know if this solves your issue. Thank you!

**Comment by BenjaminNielsen** [comment]
> Hi @BenjaminNielsen and @malcomm, sorry about the delay. We just pushed pr #6867 to `latest` that addresses this. Please try again with the latest amplify and let us know if this solves your issue. Thank you!

I can confirm prod build are now working for me. Thanks so much!
