### ISSUE TITLE
Deprecated tag should be BIG and RED

### ISSUE THREAD

**Issue by tomgiagtz** [aws-amplify/amplify-js#6798]
Yes hello. 

https://github.com/aws-amplify/amplify-js/blob/5bf77b128284006fa7fc1184ec0571322af4ed53/docs/api/classes/authclass.html#L1574

Almost didn't notice this,  would be nice if it were more attention grabbing

**Comment by abdallahshaban557** [comment]
These docs are deprecated and not being used anymore.
