### ISSUE TITLE
No way to add a custom form field for the "Name" attribute with the AmplifyAuthenticator component.

### ISSUE THREAD

**Issue by kylekirkby** [aws-amplify/amplify-js#6804]
**Describe the bug**
https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#custom-form-fields

There is no way listed in the docs to supply a custom form field. E.g I'm required to collect an email (usernameAlias), name and password. The email/password field support is fine but I cannot see a way to supply a custom field for a Name attribute. Instead I get an error stating that the Authenticator has not been configured properly.

**To Reproduce**

https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#custom-form-fields

**Expected behavior**
To be able to supply custom form fields that map directly into the object that gets posted to the Cognito Auth API.

**Code Snippet**
```jsx
<AmplifyAuthenticator usernameAlias="email">
        <AmplifySignUp
          usernameAlias="email"
          slot="sign-up"
          formFields={[
            { type: "email" },
            { type: "text", label: "Name", key: "name", placeholder: "Your name e.g Elon Musk" },
            {
              type: "password",
              label: "Password",
              placeholder: "Choose a password"
            },
          ]} 
        />
      </AmplifyAuthenticator>
```

Any help in finding how I can support `name` as a required field using the pre-built Amplify React UI components would be greatly appreciated!

**Comment by amhinson** [comment]
This doesn't seem to be supported currently, but I've marked it as a feature request for now.

**Comment by kylekirkby** [comment]
> This doesn't seem to be supported currently, but I've marked it as a feature request for now.

Actually, I can get this `name` required field issue working by specifying:

```jsx
<AmplifySignUp
        slot="sign-up"
        usernameAlias="email"
        formFields={[
          {
            type: "email",
            label: "Your Email",
            placeholder: "E.g elon@musk.com",
            required: true,
          },
          {
            type: "password",
            label: "Your Password",
            placeholder: "YourPassword",
            required: true,
          },
          {
            type: "name",
            label: "Your Name",
            placeholder: "Elon Musk",
            required: true,
          },
        ]}
      />
```

**Comment by danielfdsilva** [comment]
I'm also having this problem. I realized that if you set the `type` to the field name it works.
In my case:
```
{
  type: 'preferred_username',
  label: 'Name',
  placeholder: 'Your name'
}
```
However this results in `<input type='preferred_username' />` which is incorrect.

The documentation is not clear how you'd specify the field name to use when the API call is made, if at all possible.
