### ISSUE TITLE
SSR: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by oste** [aws-amplify/amplify-js#6813]
**Describe the bug**
I am testing the new SSR capabilities with next.js and I am seeing:

```
ReferenceError: window is not defined
    at UniversalStorage.setUniversalItem (/node_modules/@aws-amplify/core/lib/UniversalStorage/index.js:88:21)
    at UniversalStorage.setItem (/node_modules/@aws-amplify/core/lib/UniversalStorage/index.js:69:22)
    at CognitoUser.cacheTokens (/node_modules/amazon-cognito-identity-js/lib/CognitoUser.js:1412:18)
    at /node_modules/amazon-cognito-identity-js/lib/CognitoUser.js:1391:17
    at /node_modules/amazon-cognito-identity-js/lib/Client.js:127:31
```

**To Reproduce**
Follow steps in tutorial here https://docs.amplify.aws/start/getting-started/data-model/q/integration/next
Connect with auth and sign in with cognito. 

**Expected behavior**
`window` is not used on the server.

**Comment by ericclemmons** [comment]
@oste I haven't been able to reproduce this.  Can you update the issue to follow the template (https://github.com/aws-amplify/amplify-js/issues/new?assignees=&labels=to-be-reproduced&template=bug_report.md&title=) so I can see what versions you're using and how to reproduce this?

My local repo has the following:

```
 npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
npx: installed 1 in 1.334s

  System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 4.23 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.3/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 85.0.4183.102
    Edge: 83.0.478.45
    Firefox: 68.11.0
    Safari: 13.1.2
  npmPackages:
    @aws-amplify/ui-react: ^0.2.20 => 0.2.20
    aws-amplify: ^3.3.0 => 3.3.0
    next: 9.5.3 => 9.5.3
    react: 16.13.1 => 16.13.1
    react-dom: 16.13.1 => 16.13.1
  npmGlobalPackages:
    @angular/cli: 10.0.8
    @aws-amplify/cli: 4.29.1
    detox-cli: 10.0.7
    expo-cli: 3.21.3
    npm: 6.14.4
    parcel-bundler: 1.12.4
    pure-prompt: 1.12.0
    yarn: 1.22.4
```

**Comment by oste** [comment]
Hi @ericclemmons. Thanks for taking a look. Belo is my config. 

```
 System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 2.12 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.7.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/Sites/sports.im/node_modules/.bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: 80.0
    Safari: 13.1.2
  npmPackages:
    aws-amplify: 3.3.1 => 3.3.1
    aws-amplify-react: ^4.2.5 => 4.2.5
    aws-amplify-react-native: 4.2.6 => 4.2.6
    aws-appsync: ^4.0.1 => 4.0.1
    next: ^9.5.3 => 9.5.3
    react: 16.13.1 => 16.13.1
    react-dom: 16.13.1 => 16.13.1
  npmGlobalPackages:
    @aws-amplify/cli: 4.29.2
    expo-cli: 3.23.3
    npm: 6.14.7
    prettier: 2.0.5
    typescript: 3.9.7
```

Is this more of an issue with @aws-amplify/ui-react vs  aws-amplify-react: ^4.2.5 => 4.2.5 and    aws-amplify-react-native: 4.2.6 => 4.2.6. I am using expo in my project and wanted to use as much react native web as possible... Either way, doesn't it seem like the code in question(https://github.com/aws-amplify/amplify-js/blob/main/packages/core/src/UniversalStorage/index.ts#L105) should have a ssr check? Or is this code not expected to be called from the server?

**Comment by ericclemmons** [comment]
We do have an `ssr` check here:
https://github.com/aws-amplify/amplify-js/blob/5651365e75f2989238110660f5c4dfc7adcfd45d/packages/auth/src/Auth.ts#L157-L159

Can you share more of your code? Like, I don't know if or where you're using `ssr: true`, and what command you're running to reproduce, etc.

We tested that `aws-amplify-react-native` worked with this latest release (which doesn't use `ssr: true`), but that's not being used in the tutorial, Next.js is:
>  Follow steps in tutorial here docs.amplify.aws/start/getting-started/data-model/q/integration/next

**Comment by oste** [comment]
@ericclemmons I have this line directly below my imports in both _app.tsx and pages/index.tsx `Amplify.configure({ ...awsExports, ssr: true });`

The page renders until I add this to pages/index.tsx

```
export async function getServerSideProps({ req }) {
  const SSR = withSSRContext({ req });
  const response = await SSR.API.graphql({ query: getPost });

  return {
    props: {
      posts: response.data.getPost,
    },
  };
}
```

**Comment by ericclemmons** [comment]
So you're saying that your `pages/index.tsx` looks just like https://docs.amplify.aws/start/getting-started/data-model/q/integration/next#api-with-server-side-rendering-ssr but is returning that `window` error when you run `npm run dev`?

**Comment by oste** [comment]
yeah. It's very similar. I am trying to debug Auth.ts to get some more info.

**Comment by oste** [comment]
I am getting a white screen and next server logs are showing `No current user` which seems to be coming from Auth.ts

**Comment by oste** [comment]
So maybe since i was logged in it was causing the issue. I cleared cache, localstorage and cookies etc and now I get this new error. Previously I had auth config'd like this for the server in _documnet.tsx

```
    Auth: {
      storage: {
        getItem: (key) => {
          const cookies = nextCookie({ req });

          if (cookies[key]) {
            return cookies[key];
          }
          return null;
        },
        setItem: (key, value) => {
          console.log('storage function not used for ssr - setItem', key, value);
        },
        removeItem: () => {
          console.log('storage function not used for ssr - removeItem');
        },
        clear: () => {
          console.log('storage function not used for ssr - clear');
        },
      },
    },
```

**Comment by oste** [comment]
so I wrapped this part in a `trycatch` `const response = await SSR.API.graphql({ query: getPost });` to avoid the `No current user` error. Then I was able to log back in with the authenticator component and everything seems to be working as expected.

So I think the issue was related to my logged in user. Somehow it was still trying to use the non universal storage still.

**Comment by ericclemmons** [comment]
Ooh yes, that makes sense. So, this seems more like a documentation problem where my tutorial should use `try`/`catch`?

(cc @renebrandel)

**Comment by oste** [comment]
Yeah, it would be good to document the suggested way to handle an unauthorized user. It seems to throw an error. It would also be a good addition to show a different auth mechanism. Most users will need to work with both secure and public queries. 

Previously I was using aws-appsync with appsync clients like this

```
import Auth from '@aws-amplify/auth';

import AWSAppSyncClient, { AUTH_TYPE } from 'aws-appsync';
import awsconfig from '../aws-exports';

export const publicClient = new AWSAppSyncClient({
  disableOffline: true,
  url: awsconfig.aws_appsync_graphqlEndpoint,
  region: awsconfig.aws_appsync_region,
  auth: {
    type: AUTH_TYPE.AWS_IAM,
    credentials: () => Auth.currentCredentials(),
  },
});

export const privateClient = new AWSAppSyncClient({
  disableOffline: true,
  url: awsconfig.aws_appsync_graphqlEndpoint,
  region: awsconfig.aws_appsync_region,
  auth: {
    type: AUTH_TYPE.AMAZON_COGNITO_USER_POOLS, // or type: awsconfig.aws_appsync_authenticationType,
    jwtToken: async () => {
      try {
        return (await Auth.currentSession()).getIdToken().getJwtToken();
      } catch (error) {
        return '';
      }
    },
  },
});
```

It seems I will need to revisit this and see if I can use `SSR.API.graphql` for both of these use cases.

**Comment by ericclemmons** [comment]
@oste Originally, the tutorial used **IAM** and Cognito User Pools. Instead I converted to API key & Cognito User Pools, because IAM has a bunch of steps in the CLI that I wanted to avoid initially.

The tutorial does both public (for reading) & private (creating/deleting) posts, like a normal blog setup.

Your `getPost` should be using the `AWS_IAM` `authMode`. Otherwise, Cognito User Pools will be the default & throw, like you're seeing.

**Comment by m5r** [comment]
I could reproduce this bug with Cognito User Pools and Custom Auth flow type.

```typescript
import { withSSRContext } from "aws-amplify";
import Auth from "@aws-amplify/auth";
import type { AuthClass } from "@aws-amplify/auth/lib/Auth";

import awsconfig from "../aws-export";

Auth.configure({ ...awsconfig, ssr: true });

const Index: NextPage = () => {
	return null;
};

export const getServerSideProps: GetServerSideProps = async (context) => {
	const Auth = withSSRContext(context).Auth as AuthClass;

	const user = await Auth.signIn("ACTUAL USER EMAIL");
	await Auth.sendCustomChallengeAnswer(user, "ONE TIME PASSWORD"); // <== throws the error
};

export default Index;
```

I fixed it by modifying `node_modules/@aws-amplify/core/lib/UniversalStorage/index.js`, here is the diff:

```diff
--- a/node_modules/@aws-amplify/core/lib/UniversalStorage/index.js
+++ b/node_modules/@aws-amplify/core/lib/UniversalStorage/index.js
@@ -15,6 +15,13 @@ var UniversalStorage = /** @class */ (function () {
             ? new universal_cookie_1.default(context.req.headers.cookie)
             : new universal_cookie_1.default();
         Object.assign(this.store, this.cookies.getAll());
+        let host = "";
+        if (isBrowser) {
+            host = (window.location.host.indexOf(":") > -1 && window.location.host.split(":")[0]) || window.location.host;
+        } else if (context.req && context.req.headers && context.req.headers.host) {
+            host = (context.req.headers.host.indexOf(":") > -1 && context.req.headers.host.split(":")[0]) || context.req.headers.host;
+        }
+        this.secure = !(["localhost", "127.0.0.1"].includes(host));
     }
     Object.defineProperty(UniversalStorage.prototype, "length", {
         get: function () {
@@ -85,7 +92,7 @@ var UniversalStorage = /** @class */ (function () {
             // `httpOnly` cannot be set via JavaScript: https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#JavaScript_access_using_Document.cookie
             sameSite: true,
             // Allow unsecure requests to http://localhost:3000/ when in development.
-            secure: window.location.hostname === 'localhost' ? false : true,
+            secure: this.secure,
         });
     };
     return UniversalStorage;
```

I'm not sure if we'd need to update `this.secure` at some point though.

**Comment by ericclemmons** [comment]
@m5r At this moment, the supported use-case is `Auth` happening on the client so credentials can be shared with the server.

In your example, you're attempting to do the authentication on the server, which we're still solving for. That would make it a feature request, but this use-case seems different than what's happening for @oste.

@oste https://github.com/aws-amplify/amplify-js/issues/6813#issuecomment-695056643 makes it sound like you were specifying a custom storage adapter.  That won't be necessary with `Amplify.configure({ ...awsexports, ssr: true })`.

**Comment by m5r** [comment]
I understand, thanks for clarifying the situation Eric!

**Comment by ebsaral** [comment]
@ericclemmons Should we create a feature request for @m5r 's situation since I do have the same problem for using `Auth.sendCustomChallengeAnswer` with SSR. I couldn't find a request regarding this, should I create a new one or did I miss it? Thanks.

**Comment by rgksugan** [comment]
> @m5r At this moment, the supported use-case is `Auth` happening on the client so credentials can be shared with the server.
> 
> In your example, you're attempting to do the authentication on the server, which we're still solving for. That would make it a feature request, but this use-case seems different than what's happening for @oste.
> 
> @oste [#6813 (comment)](https://github.com/aws-amplify/amplify-js/issues/6813#issuecomment-695056643) makes it sound like you were specifying a custom storage adapter. That won't be necessary with `Amplify.configure({ ...awsexports, ssr: true })`.

Is Authentication on the server made available now?

**Comment by davidsonsns** [comment]
my approach was similar to @m5r. but if you aren't familiar with `patch-package`, I highly recommend using it to get the same behavior for all your teammates.
