### ISSUE TITLE
Amplify not notifying when refresh token expires

### ISSUE THREAD

**Issue by DavidAlvarado23** [aws-amplify/amplify-js#6816]
**Describe the bug**
I have configured Amplify Auth using the library for React: aws-amplify-react. I'm using the Authenticator component to manage the auth system of the app such as the login and sign up. 

I have the refresh token validity for 60 minutes, as well as the access and ID token. When the refresh token expires there is no way to know when this had happened, it only throws an error that the refresh token has expired. 

**To Reproduce**
The user logs in to the application, the different tokens are created by Cognito. Wait and hour to let the refresh token expire and then call any other Amplify feature such as API or Storage.

**Expected behavior**
I'm not sure if this is the default behaviour when the refresh token has expired or it should redirect the user to the login page (set on the Authenticator component) or at least notify throught the Authenticator component that the user is no longer logged in. I'm aware that the refresh tokens cannot be refreshed but there should be a way to notify the user that it has to log in again.

**Code Snippet**
I have the Authenticator component as follows:
```
      <Authenticator
        onStateChange={(authState) => {
          this.setState({ authState });
          if (authState === "signedIn") {
            this.updateConfiguration();
          }
        }}
        federated={FederatedConfig}
        theme={CustomTheme}
        hideDefault={true}
      >
        {/* <Greetings/> */}
        <Login override={"SignIn"} />
        <ConfirmSignIn />
        <RequireNewPassword />
        {/* <SignUp/> */}
        <ConfirmSignUp />
        <VerifyContact />
        <ForgotPassword />
        <TOTPSetup />
        {/* <Loading/> */}
        <App />
      </Authenticator>
```

The login component that overrides the SignIn is almost the same as the SignIn component but with a different layout. So when the refresh token expires it should render this component.

**What is Configured?**
I have configured Cognito to make tokens that are only valid through 60 minutes. Also in the amplify project I have http calls throught the API library that connects to AWS AppSync.

**Comment by wei** [comment]
@amhinson I see you marked it as a `feature-request`, do you have something in mind? Perhaps through the use of hub events? 

If you could share your thoughts on how you envision this to work and/or the location in the codebase where this should reside, me or another MLH fellow would be more than happy to help out~ 😉

**Comment by amhinson** [comment]
@DavidAlvarado23 @wei This actually has been addressed recently through `Hub` events in this PR: https://github.com/aws-amplify/amplify-js/pull/7111

```js
Hub.listen('auth', (data) => {
  switch (data.payload.event) {
    case 'tokenRefresh': {
      logger.log("New token has been process");
      break;
    }
    case 'tokenRefresh_failure': {
      logger.log("Failed to retrieve new token");
      break;
    }
  }
});
```

I'll close this for now, but feel free to open it back up if it doesn't quite address your needs.
