### ISSUE TITLE
Handling browser closing server-side 

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/amplify-js#6821]
Hi,

It seems impossible to handle browser closing (without a prompt) front-side.

So I would like to get a solution server-side, maybe with subscriptions.

Is it possible ?

**Comment by amhinson** [comment]
Could you provide more details on the issue you are seeing as it related to Amplify? It would be great if you could fill in the details on the "New issue"/"Feature Request" template.

**Comment by rudyhadoux** [comment]
For a Chat application we can see when a user is connecting or when a user is logging out. 
But I think there is no way to achieve that with Amplify actually.

**Comment by amhinson** [comment]
Ok. I will close this for now, but feel free to open a new issue or feature request.
