### ISSUE TITLE
Cannot get a list of files for a public folder

### ISSUE THREAD

**Issue by donnrri** [aws-amplify/amplify-js#6825]
Storage.list does not return a list of files in public folder.
I have a react application to add and get S3 files.

I have add storage using amplify
I have added user access to a group called 'demouser'
I have uploaded a file using  a user in that group
In my AWS console I see the public 'folder' is created  and contains a file 'demo' (no extension), which is the file I uploaded above.
I add some code to list the files in public folder

I have tried :
```
Storage.list('public/')
    .then(result => console.log(result))
    .catch(err => console.log(err));
also..
Storage.list('public/', { level: 'public' })....
Storage.list('public/', { level: 'protected' })....
also..
Storage.list('/', { level: 'public' })....
Storage.list('/', { level: 'protected' })....
Storage.list('/')...
```
Every time I get an empty array

Please can you tell me what do I use to see files uploaded by a user , when logged in as that user, using the above ?

Thanks

**Comment by sammartinez** [comment]
@donnrri, thanks for reporting this, can you please provide us a little more detail with running the following command within your project `npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages`. Thanks ahead of time

**Comment by donnrri** [comment]
Thanks for your response here is the uotput from the above
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 1.52 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Safari: 14.0
  npmPackages:
    @babel/core: ^7.8.6 => 7.8.6 
    @babel/plugin-proposal-class-properties: ^7.8.3 => 7.8.3 
    @babel/preset-env: ^7.11.0 => 7.11.0 
    @babel/preset-react: ^7.8.3 => 7.8.3 
    @reach/router: ^1.3.4 => 1.3.4 
    aws-amplify: ^3.1.1 => 3.1.1 
    aws-amplify-react: ^4.2.2 => 4.2.2 
    babel-loader: ^8.0.6 => 8.0.6 
    babel-polyfill: ^6.26.0 => 6.26.0 
    bootstrap: ^4.5.2 => 4.5.2 
    clean-webpack-plugin: ^3.0.0 => 3.0.0 
    css-loader: ^3.4.2 => 3.4.2 
    d3: ^5.15.0 => 5.15.0 
    dotenv: ^8.2.0 => 8.2.0 
    file-loader: ^6.0.0 => 6.0.0 
    file-saver: ^2.0.2 => 2.0.2 
    font-awesome: ^4.7.0 => 4.7.0 
    html-webpack-plugin: ^4.4.1 => 4.4.1 
    memoize-one: ^5.1.1 => 5.1.1 
    mini-css-extract-plugin: ^0.11.1 => 0.11.1 
    react: ^16.13.0 => 16.13.0 
    react-bootstrap: ^1.3.0 => 1.3.0 
    react-datepicker: ^2.16.0 => 2.16.0 
    react-dom: ^16.13.0 => 16.13.0 
    react-router-dom: ^5.1.2 => 5.1.2 
    style-loader: ^1.1.3 => 1.1.3 
    url-loader: ^4.1.0 => 4.1.0 
    webpack: ^4.42.0 => 4.42.0 
    webpack-cli: ^3.3.11 => 3.3.11 
    webpack-dev-server: ^3.11.0 => 3.11.0 
    webpack-merge: ^5.1.4 => 5.1.4 
    worker-loader: ^2.0.0 => 2.0.0 
  npmGlobalPackages:
    @aws-amplify/cli: 4.29.1
    npm: 6.14.6

**Comment by ashika01** [comment]
@donnrri could you screenshot the folder structure of your s3 storage bucket ?!

**Comment by donnrri** [comment]
Here is my screenshot.  Thanks for any help
<img width="1627" alt="Screenshot 2020-09-25 at 11 43 37" src="https://user-images.githubusercontent.com/1951795/94258641-0b7f8200-ff25-11ea-8600-ec4d08f8b68b.png">

**Comment by donnrri** [comment]
Is there any news on this.  Can you assist me in resolving this issue please

**Comment by donnrri** [comment]
Thanks for your help . I have made some errors , since when I make a new project and try this it works . sSo once again thanks for your input , apologise for wasting your time . I will close this issue
