### ISSUE TITLE
Storage class should expose head operation & range requests

### ISSUE THREAD

**Issue by marksteele** [aws-amplify/amplify-js#6830]
**Is your feature request related to a problem? Please describe.**

I would like to be able to perform a HEAD operation on an object stored in S3 (ex: so that I can determine the file size) as well as the ability to perform range requests (to read specific byte ranges out of a file). In my case, to retrieve just a few bytes at the end of a file.

**Describe the solution you'd like**

* A head operation in the Storage API that would return the headers of the request as a map.
* The ability to provide byte offsets to the get call (to generate properly signed urls)

**Describe alternatives you've considered**

Possibly expose the raw S3 client and utility functions to get key prefixes for logged in user, etc... That would allow for these types of advanced use-cases to be implemented.

**Additional context**

**Comment by kierancrowntrt** [comment]
I'd like to see this also. Possibly relates to https://github.com/aws-amplify/amplify-js/issues/5044

**Comment by sw-yx** [comment]
related requests:

- https://github.com/aws-amplify/amplify-js/issues/6157
- https://github.com/aws-amplify/amplify-js/issues/5131

**Comment by stocaaro** [comment]
Related to #3236

**Comment by pacchij** [comment]
I am also waiting for this functionality. Ability to get file last modified attribute is much needed to see if file changed.
In my use case, I want to download only if file changes. Is this possible with amplfiy?

**Comment by kvramyasri7** [comment]
Now we can access properties of file using `Storage.getProperties` .
