### ISSUE TITLE
Ability to list "directories" in Storage

### ISSUE THREAD

**Issue by marksteele** [aws-amplify/amplify-js#6831]
**Is your feature request related to a problem? Please describe.**
While S3 doesn't have directories per-se, it files inside are often organized with common prefixes.

Would be nice to have a directory listing function, which allows you to specify a prefix and it lists the common prefixes below it. (a request with prefix and delimiter)

**Describe the solution you'd like**
A listDirectories function, or modify the list function to be able to provide prefixes and delimiters.

**Describe alternatives you've considered**
A method to expose the raw s3 client to implement missing functionality (along with methods to find paths like currently logged in user's private keyspace paths)

**Additional context**

**Comment by stocaaro** [comment]
Maybe things have changed since this issue was create, this request sounds a lot like the [list behavior](https://docs.amplify.aws/lib/storage/list/q/platform/js/). Is there a gap between what your looking for and what this function does?

**Comment by haverchuck** [comment]
@marksteele  This feature is now available:
https://docs.amplify.aws/react/build-a-backend/storage/list-files/#get-all-nested-files-within-a-path
https://docs.amplify.aws/react/build-a-backend/storage/list-files/#excluding-subpaths
