### ISSUE TITLE
Storage - more than 1000 keys

### ISSUE THREAD

**Issue by marksteele** [aws-amplify/amplify-js#6838]
**Is your feature request related to a problem? Please describe.**
There are many use cases which involve listing out a more than 1000 keys, however the storage api provides no means of doing so (nor any work-arounds that I could find).

**Describe the solution you'd like**
A mechanism to list out keys supporting paging/offsets/prefixes and delimiters.

**Describe alternatives you've considered**
Would also be possible to do with the raw S3 client if that was accessible from the Storage api.

**Additional context**

**Comment by harrysolovay** [comment]
Hi @marksteele –– I'd recommend creating a custom storage adapter for [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API).

Storage adapters abide by the following interface.

```ts
interface Storage {
  // set item with the key
  static setItem(key: string, value: string): string;
  // get item with the key
  static getItem(key: string): string;
  // remove item with the key
  static removeItem(key: string): void;
  // clear out the storage
  static clear(): void;
  // If the storage operations are async(i.e AsyncStorage)
  // Then you need to sync those items into the memory in this method
  static sync(): Promise<void>;
}
```

And can be provided via a `storage` field in your Amplify config.

In auth, for instance:

```ts
import {Auth} from "@aws-amplify/auth";
import Config from "./aws-exports";
import {MyStorageAdapter} from "./wherever";

Auth.configure({
  ...config,
  storage: new MyStorageAdapter,
});
```

**Comment by marksteele** [comment]
Why would I want to use indexdb? The reason I'm using the Storage API is to leverage S3.

I have users who want to store thousands of files in S3. I'd like to be able to leverage Amplify (makes handling the authentication/token handling bits so simple, it's great!). I understand the reasons for dumbing down the API for some use cases, but to cripple it to the point where it removes some pretty basic functionality seems like a very odd design choice (nobody thought: "what if a user has more than 1000 files?).

Why can't additional functionality be added to the list function to expose more of the underlying S3 API? Is there some fundamental reason you can just add all the options from ListObjectsV2 to the Storage.list calls?

ex:
```
Storage.list('photos/', { level: 'private', ... other options .., listv2: {
ContinuationToken: 'asdf',
  Delimiter: 'asdf/',
  MaxKeys: 1000,
  StartAfter: 'STRING_VALUE'
}
}})
// Prefix would be auto-derived from access level and prefix passed in
/* returns something like
[{
key: 'photos/foo',
<other current keys>
Istruncated: true,
NextContinuationToken: "1w41l63U0xa8q7smH50vCxyTQqdxo69O3EmK28Bi5PcROI4wI/EyIJg=="
}]
*/
```

You could add some more properties to each returned item (to pass back the truncated flag and continuation token) which wouldn't be a backward-breaking change (not elegant, but that's the trade-off of possibly over-simplifying it).

Alternatively, when listv2 is passed in, return the raw S3 response back out and avoid the ugliness above.

**Comment by harrysolovay** [comment]
@marksteele apologies––I must have misread your initial comment. I thought you were referring––not to the storage category––but to underlaying storage mechanisms for things such as authentication state. I'll communicate about this with a team member who is more well-versed.

**Comment by kmbro** [comment]
I am looking for this feature as well. once you hit 1000 files or whatever your max page size is, you should get a key back. It is pretty basic pagination 👍

**Comment by boston99green** [comment]
Following this thread. I'm trying to retrieve all files in S3 bucket using React Amplify, It just list 1000 objects , but I do have more than 1000 objects in it. How can I retrieve it, Looking for a solution..?

**Comment by jmanek** [comment]
Has anyone found a workaround or solution to this?

**Comment by boston99green** [comment]
Since Amplify doesn't support listing more than 1000 files, I used AWS-SDK to solve this

```
var AWS = require('aws-sdk');
var allKeys = [];
AWS.config.region=awsmobile.Auth.region;

 async function listAllKeys(prefix) {
   params.Prefix=prefix;
  Auth.currentCredentials().then((creds) => {
    AWS.config.credentials = creds
    new AWS.S3().listObjectsV2(params,function (err, data) {
      if (err) {
          if(err.response.status ===403){
            console.log('token expired')
            Auth.signOut();
           }
      } else {
          var contents = data.Contents;
          contents.forEach(function (file) {
            allKeys.push(file);
          });
          if (data.IsTruncated) {
              params.ContinuationToken = data.NextContinuationToken;
              listAllKeys(prefix);
          } 
      } 
  });
}
);
}
```

**Comment by boston99green** [comment]
> Has anyone found a workaround or solution to this?


Since Amplify doesn't support listing more than 1000 files, I used AWS-SDK to solve this

```
var AWS = require('aws-sdk');
var allKeys = [];
AWS.config.region=awsmobile.Auth.region;

 async function listAllKeys(prefix) {
   params.Prefix=prefix;
  Auth.currentCredentials().then((creds) => {
    AWS.config.credentials = creds
    new AWS.S3().listObjectsV2(params,function (err, data) {
      if (err) {
          if(err.response.status ===403){
            console.log('token expired')
            Auth.signOut();
           }
      } else {
          var contents = data.Contents;
          contents.forEach(function (file) {
            allKeys.push(file);
          });
          if (data.IsTruncated) {
              params.ContinuationToken = data.NextContinuationToken;
              listAllKeys(prefix);
          } 
      } 
  });
}
);
}
```

**Comment by mattbonaventura** [comment]
I agree that the Amplify Storage API should allow the user to retrieve lists of files longer than 1000 items. Can we get a response as to whether this will be accepted as a feature request @harrysolovay ?

**Comment by stocaaro** [comment]
Related to #7133

**Comment by stocaaro** [comment]
The above change changes the `Storage.list` interface to allow accessing all objects in a list result set by adding a special `maxKeys` option.

Ex. `Storage.list('',{maxKeys : 'ALL'})`

`maxKeys`  can be called with any value `1-1000` or `'ALL'`.

A separate task is open to add token based pagination which we expect to include in the next major version release as a breaking change.

**Comment by tsmiyamoto** [comment]
@kvramyasri7 
This is a great update! Thank you so much!!
