### ISSUE TITLE
Auth.forgotPasswordSubmit doesn't work

### ISSUE THREAD

**Issue by siaolichi** [aws-amplify/amplify-js#6863]
I used amplify with React Native.

When I called
```
await Auth.forgotPasswordSubmit(username, code, password)
```
it return nothing.
after call the function again, the error return: 
```
{
  "code": "ExpiredCodeException",
  "message": "Invalid code provided, please request a code again.",
  "name": "ExpiredCodeException",
}
```
Every other functions (including confirmSignUp) works fine except this one.
It used to work fine but at some point it just broken and I have no clue how to fix it.
Is there any way to fix it or find the cause of these situation?

Thanks a lot!

**Comment by ianjennings** [comment]
Hey! I've been working with @mauerbac to help document these **to-be-reproduced** issues with [Paircast](https://paircast.io). Paircast is essentially "loom for developers," it combines screencasts, code, and git to create video documentation of code changes. The idea is that with this added context, everyone will have the context they need to fix these bugs quickly.

We had a developer from @haxordx record themselves reproducing this issue. You can also find the full GitHub repo [here](https://github.com/exactweblingli/amplify-forgot-password-error) and the Paircast below. I've created a highlight where we see the bug log to console, and you can scub backward to see how we got there.

<a href="https://app.paircast.io/replay/b1c11b52-c804-4c8c-a3b5-d3b578c0e30c?shareKey=Pot5D8KFXRnqWknQpsYDDw#7741190:8187797"><img src="https://user-images.githubusercontent.com/318295/95260434-b3832e00-07f6-11eb-8a0b-c9b9e72b63f5.png" /></a>

<a href="https://app.paircast.io/replay/b1c11b52-c804-4c8c-a3b5-d3b578c0e30c?shareKey=Pot5D8KFXRnqWknQpsYDDw#7741190:8187797"><img src="https://app.paircast.io/images/watch-on-paircast.png" /></a>

**Comment by wlee221** [comment]
Hi @siaolichi, thanks for reporting the issue! I was unable to reproduce this issue and got forgotPassword flow to work on a [sample repo](https://github.com/wlee221/amplify-react-native-auth) (with `aws-amplify@3.3.3` and expo-sdk `39.0.3`).

@ianjennings, thanks for the paircast 👍  The problem was that  `forgotPassword(username)`needs to be called first. This sends a new code to your email. Then you need to call `forgotPasswordSubmit(username, code, password)` with the new acquired code and new password to change the password. If you try to use `forgotPasswordSubmit` with expired code that you used for signup, then you'll see the `ExpiredCodeException`.

@siaolichi, can you confirm that your app uses the forgot password flow described above? You might want to check that your `forgotPassword` and `forgotPasswordSubmit` are executed once and sequentially. [This](https://github.com/wlee221/amplify-react-native-auth/blob/main/App.js#L62...L74) is how I implemented those functions in my RN app, if it helps!

Thanks!

**Comment by siaolichi** [comment]
Hi! Sorry for late response!
I used them in the useContext and it used to work fine before but all the sudden it didn't work at all...
I'm sorry I don't have more information about it :(

Here is all my code of the forget password function from amplify:


```
import {Auth} from 'aws-amplify';

const sendResetPasswordCode = (dispatch) => async (username) => {
    if (!username)
        return dispatch({
            type: 'ADD_ERROR',
            payload: {message: i18n.t('authContext.emptyUsername')},
        });
    try {
        const data = await Auth.forgotPassword(username);
        navigate('ResetPassword', {
            username,
            message: data.CodeDeliveryDetails.Destination,
        });
    } catch (error) {
        console.log(error);
        return dispatch({
            type: 'ADD_ERROR',
            payload: error,
        });
    }
};

const resetPassword = (dispatch) => async (Username, ConfirmationCode, Password) => {
    try {
        await Auth.forgotPasswordSubmit(Username, ConfirmationCode, Password);
        navigate('Auth', {screen: 'Login'});
    } catch (error) {
        console.log('reset password', error);
        return dispatch({
            type: 'ADD_ERROR',
            payload: error,
        });
    }
};
```

I solved the problem by directly calling cognito from our backend here: 
```
router.post('/forget-password', async function (req, res) {
    const {Username, Password, ConfirmationCode} = req.body;
    var params = {
        ClientId: 'xxxxxxxxxxxxxx',
        ConfirmationCode,
        Password,
        Username,
    };
    cognito.confirmForgotPassword(params, function (error, data) {
        if (error) res.status(402).json({error});
        else res.json(data);
    });
});
```

**Comment by wlee221** [comment]
Hi @siaolichi, sorry about the late response too :( I think I see the problem. `Auth.forgotPassword` returns `Promise<void>`, so it does not return any values. You said that you called the function again, but calling it multiple times would break the flow and you would get invalid codes. Can you make sure you're not calling the function again? I would suggest that you log the parameters before you call the functions.

**Comment by wlee221** [comment]
As per why it stopped working suddenly, I'm not entirely sure yet. I don't see any problems with your sample code; can you share a minimal sample repo if possible? I'd be happy to help!
