### ISSUE TITLE
All Web- and ServiceWorkers reliably destroyed by new `cognito-identity-js`

### ISSUE THREAD

**Issue by ngault** [aws-amplify/amplify-js#6868]
**Describe the bug**
With the introduction of `isomorphic-unfetch` to `amazon-cognito-identity-js/src/Client.js` at https://github.com/aws-amplify/amplify-js/blob/7cbed47cb2bbbc3a94a6fcae87efee80a5542f2e/packages/amazon-cognito-identity-js/src/Client.js#L1 any Service Worker or Web Worker making API calls will crash with a `window not found`.  Moreover, the inclusion of file in a JS bundle instantly destroys the browser's Worker environment, with other fatal exceptions soon to follow.

This is because `isomorphic-unfetch` depends on `unfetch`, which fails to check for `self` (i.e., a Worker environment), and, thereby, replaces the Worker environment's built-in `fetch` implementation with a fetch polyfill that, incorrectly, assumes `window` is present.
https://github.com/developit/unfetch/issues/104

To fully appreciate the severity of this bug, consider that that the standardized worker implementation of the `fetch` spec (in Chrome it's >> 100,000 lines, and includes proxying, cacheing, etc)  is replaced by a 500 line polyfill the moment the worker loads the Amplify JS bundle, and executes `import "isomorphic-unfetch"`.  

Unfortunately,  the`unfetch` project is not actively maintained, with a straightforward PR to fix the problem being outstanding almost 2 years:
https://github.com/developit/unfetch/pull/109

**The problem CAN be fixed without impacting any other Amplify code by either:**
**1.  replacing `unfetch` with a `fetch` polyfill that correctly detects all environments,** 
**OR**
**2. checking for `self` on the 1st line of `Client.js`, and, if a Worker is detected, not importing `isomorphic-fetch` and overwriting the Worker global namespace** 

--------------------
**To Reproduce**
Based on the self-evident nature of the problem and its documentation in the `isomorphic-unfetch`/`unfetch` repo,  reproducing the behavior in a Worker using Amplify should not be necessary... but, if our process nonetheless requires reproducing, do this:

From within a Web or Service Worker, call any method in `@aws-amplify/auth` (which will, in turn invoke `amazon-cognito-identity-js/src/Client.js`) or any other Amplify function dependent on `@aws-amplify/auth`.

The `/amazon-cognito-identity-js/__tests__/` does not currently consider workers (nor SSR).  Similarly, there is no testing for  authentication in workers in core... all of which explains why this problem wasn't previously identified.  

To configure a worker to use Auth,  you'll need to provide an implementation of a the `ICognitoStorage` interface with your Config with something like:
```ts
Auth.configure({
  storage: AuthStorage,
});
```
The custom storage interface is required because workers don't support LocalStorage, Amplify's default store.  Numerous examples for memory and IndexedDB stores can be found with a Google search.

**Comment by bebraw** [comment]
For reference, it looks like https://github.com/supabase/postgrest-js/pull/109 moved to use [cross-fetch](https://www.npmjs.com/package/cross-fetch) which doesn't appear to have the issue when run within workers so using that over the current solution is one option.

**Comment by ngault** [comment]
FYI, the offending problem in the `unfetch` repo has just now been fixed: 
https://github.com/developit/unfetch/pull/109 

The problem in `amazon-cognito-identity-js` should go away by updating to the `isomorphic-unfetch` dependency, which depends on `unfetch`.

**Comment by sammartinez** [comment]
Thanks for reporting this @ngault, @nickarocho can we look at this bug and see about the upgrade path?

**Comment by nickarocho** [comment]
Hi @ngault, I started looking into this and was wondering if this is still an issue for you? The `package.json` within Amplify's `amazon-cognito-identity-js` package is showing the following version: `"isomorphic-unfetch": "^3.0.0"`.

Since this should bump the dependency to any minor version (via the `^`) if you do a fresh `yarn install` and inspect the `browser.js` file within the `node_modules/isomorphic-unfetch` directory, you should see the file contains the following fix you were hoping for:
```
module.exports = self.fetch || (self.fetch = require('unfetch').default || require('unfetch'));
```

If this is still a problem for you we will open a PR with the minor version bump, otherwise I believe we can close this issue.

Thanks!

**Comment by ngault** [comment]
> If this is still a problem for you we will open a PR with the minor version bump, otherwise I believe we can close this issue.
> 
> Thanks!

The problem was fixed within a few days of my reporting it 8 month as ago. @ericclemmons took the lead.

**Comment by nickarocho** [comment]
Got it, thanks for the follow up!
