### ISSUE TITLE
Auto resolve Datastore @connection fields

### ISSUE THREAD

**Issue by mdegrees** [aws-amplify/amplify-js#6869]
**Is your feature request related to a problem? Please describe.**

When working with @connection in a relational DataStore model, I find myself having to loop through the results and manually resolve the connection fields one by one whereas with API.graphql I don't have to.

Fetching Posts with comments @connection for examples requires me to:
. Fetch all the posts
. loop through the posts and for each post fetch the comments

Given the simplicity of Datastore API, the fetching is not a big deal if you have one @connection, but once you have many it starts to feel cumbersome. 

**Describe the solution you'd like**
It would be cool if Datastore automatically resolves the @connections the way `API.graphql` works.

**Comment by undefobj** [comment]
@iartemiev 👀

**Comment by danrivett** [comment]
I'm trying to understand this issue, as a developer on my team ran into something very similar today and I am working under the assumption it's an issue on our end, but this ticket makes me question that.

Are you saying that in the example `Post` and `Comment` example documented in [AWS Docs](https://docs.amplify.aws/lib/datastore/relational/q/platform/js) that the `Post.comments` field isn't automatically populated when you query for a `Post` such as by:

```ts
const post = (await DataStore.query(Post, p => p.id("eq", postId))[0];
```

This wouldn't return a `Post` object with a populated `comments` array?

If that's the case why would the generated TypeScript types contain a `comments` array if it's not useable.

I know I must be missing something here, so apologies for that, I'm just trying to see if I can unblock my dev on this issue so diving in.

@undefobj could you please quickly clarify this to avoid us going down the wrong path? Thanks.

**Comment by iartemiev** [comment]
That's correct, `comments` currently does not get populated. The docs specify [retrieving them separately](https://docs.amplify.aws/lib/datastore/relational/q/platform/js#querying-relations) by passing in the related `postID` in the predicate. 

We are currently working on a solution to retrieving related child items when querying a parent, so it will be possible to do in the near future.

**Comment by danrivett** [comment]
Thanks @iartemiev I appreciate the clarification that helps us going down rabbit holes on our end, and I'm also glad to see it's something on your radar for a future enhancement.

It's great to see DataStore being actively worked on and enhanced to fill these gaps, as really does make a huge difference for our use of DataStore as it's typically death by a thousand papercuts for us, but you guys are steadily fixing them, which makes me excited.

**Comment by mdegrees** [comment]
@undefobj please, any updates on this issue? The code base we're working on is getting bigger, the cumbersomeness from model relationship just getting worse. We reached a point where we're considering rolling back to the API category. Is this issue of a any priority right now?

**Comment by undefobj** [comment]
This feature request is still a priority we are working on in the coming months.

**Comment by mdegrees** [comment]
@undefobj thank you

**Comment by renebrandel** [comment]
Closing this as we've addressed this as part of the lazy loading feature launch: https://aws.amazon.com/blogs/mobile/new-lazy-loading-nested-query-predicates-for-aws-amplify-datastore/ Feel free to @-me if you have anymore questions.
