### ISSUE TITLE
Datastore - Support IndexedDBAdapter for WebWorker

### ISSUE THREAD

**Issue by wylfent** [aws-amplify/amplify-js#6870]
**Is your feature request related to a problem? Please describe.**
We have a project plan that to use the Datastore with the WebWorker, and store the synced data into the local IndexedDB.
But the current behavior is it will pick the AsyncStorageAdapter instead of IndexedDBAdapter. As it only allow to use IndexedDBAdapter when `browserOrNode().isBrowser` is true.

**Describe the solution you'd like**
Currently, `required('@aws-amplify/core').browserOrNode().isBrowser` is return as false when we use the WebWorker, as this flag is check by `typeof window !== 'undefined' && typeof window.document !== 'undefined'`, which the window will always be, by default, undefined in WebWorker.

So I suggest providing `isWebWorker` flag in the [JS](https://github.com/aws-amplify/amplify-js/blob/main/packages/core/src/JS.ts), with the following logic:
`typeof self !== 'undefined' && self.constructor.name === 'DedicatedWorkerGlobalScope';`

And update the [getDefaultAdapter](https://github.com/aws-amplify/amplify-js/blob/df835731ae8e2b6049f98625a40ff1ec5dd7b2cb/packages/datastore/src/storage/adapter/getDefaultAdapter/index.ts#L7), to check `(isBrowser && window.indexedDB) && (isWebWorker && self.indexedDB)`.

**Describe alternatives you've considered**
\-

**Additional context**
\-

**Comment by iartemiev** [comment]
Thank you for opening the PR, @wylfent. It was released as part of **aws-amplify@unstable** and will be included in the next stable release this week.
