### ISSUE TITLE
PubSub: Unblock subscriptions in desktop Node environments

### ISSUE THREAD

**Issue by adamup928** [aws-amplify/amplify-js#6873]
A recent update to the `PubSub` component in this [pull request](https://github.com/aws-amplify/amplify-js/pull/6726), checks for a Node environment, and if it exists, prevents subscriptions from being established.

I understand the justification for this regarding multi-tenant apps sharing sockets. In our implementation, however, we are using the PubSub module in a client application running in a desktop environment and built with Electron. This pull request breaks the functionality of the application entirely, and we can not use the latest update.

Per my conversation with @ericclemmons in the PR, I'd like to request a change to the `isNode` check.  The two solutions proposed are both workable; however, I like the simplicity of checking for `config.ssr` over checking for frameworks.

**Comment by pl4yradam** [comment]
+1 here my electron app has bust due to this. I have built a Remote app that communicates with this.

**Comment by ericclemmons** [comment]
This looks like a straightforward fix!

The current implementation keys off of `isNode`:

https://github.com/aws-amplify/amplify-js/blob/53be43d7a0049e04a47e7fece5dcd726c7a414fe/packages/pubsub/src/PubSub.ts#L152-L158

Instead, let's key off of `this._options.ssr`, which should be propagated from `Amplify.configure({ ssr: true })` calls:

https://github.com/aws-amplify/amplify-js/blob/53be43d7a0049e04a47e7fece5dcd726c7a414fe/packages/pubsub/src/PubSub.ts#L88-L96

**Comment by ericclemmons** [comment]
Alright, I just created #6937 to address this!  We'll review this with our security team so they're aware of the use-case and unblock Electron usage 🙏
