### ISSUE TITLE
Aws-Amplify importing the entire aws-sdk library creating huge bundle size

### ISSUE THREAD

**Issue by drixta** [aws-amplify/amplify-js#6875]
**Describe the bug**

AWS-Amplify is importing aws-sdk entirely creating a massive bundle size. This issue hasn't happened before.

![Screen Shot 2020-09-25 at 4 42 38 PM](https://user-images.githubusercontent.com/2681321/94324352-58c41980-ff4e-11ea-8c7f-1d68679e0288.png)

**To Reproduce**
I'm currently using [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) to generate this report;

My current project dependencies is as follows.
As you can see I'm not importing `aws-sdk` anywhere and aws-amplify imports aws-sdk for it's own logic, specifically in cognito.

  "dependencies": {
    "@ag-grid-community/all-modules": "^23.2.1",
    "@ag-grid-enterprise/all-modules": "^24.0.0",
    "@aws-amplify/ui-react": "^0.2.18",
    "@craco/craco": "^5.6.4",
    "@emotion/core": "^10.0.28",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "@types/facebook-js-sdk": "^3.3.0",
    "@types/jest": "^24.0.0",
    "@types/node": "^12.0.0",
    "@types/react": "^16.9.0",
    "@types/react-big-calendar": "^0.24.6",
    "@types/react-dom": "^16.9.0",
    "@types/react-router-dom": "^5.1.5",
    "ag-grid-community": "^23.2.1",
    "ag-grid-react": "^23.2.1",
    "antd": "^4.2.5",
    "aws-amplify": "^3.3.1",
    "date-fns": "^2.16.1",
    "dayjs": "^1.8.36",
    "formik": "^2.1.4",
    "formik-antd": "^2.0.1",
    "handsontable": "^7.4.2",
    "react": "16.12.0",
    "react-big-calendar": "^0.27.0",
    "react-contenteditable": "^3.3.5",
    "react-dnd": "^11.1.3",
    "react-dnd-html5-backend": "^11.1.3",
    "react-dom": "^16.13.1",
    "react-icons": "^3.10.0",
    "react-infinite-scroll-hook": "^3.0.0",
    "react-intersection-observer": "^8.28.5",
    "react-loading-skeleton": "^2.1.1",
    "react-query": "^2.21.0",
    "react-query-devtools": "^1.1.16",
    "react-router-dom": "^5.2.0",
    "react-scripts": "3.4.1",
    "react-spring": "^8.0.27",
    "react-stack-gallery": "^1.0.4",
    "react-stack-grid": "^0.7.1",
    "time-ago": "^0.2.1",
    "typescript": "~3.7.2",
    "yup": "^0.29.1"
  },

**Expected behavior**
Expecting not the entire `aws-sdk` is imported to the project as it is unreasonable to expect the users to download the entire library without using it.

**Comment by ashika01** [comment]
@drixta Amplify lib enable tree shaking on prod builds. Please run a prod build and compare size you should not be seeing huge bundle chunks.
