### ISSUE TITLE
Push Notification Image does not appear on notification.

### ISSUE THREAD

**Issue by Sahejmaharjan1** [aws-amplify/amplify-js#6881]
If I send a message directly from Pinpoint to my app, I have the possibility to attach Media Urls (pictures), which should be displayed as I understood it in the Push Notification. But they won't.

I do get the url in logs but am not able to recieve the image on notification.
```
GCMMessage: {
    IconReference: 'ic_stat_warning',
    Action: 'OPEN_APP',
    Title: row.userAssetId+", ID: "+row.title,
    SilentPush: false,
    Body: row.body,
    ImageUrl: 'https://cdn4.iconfinder.com/data/icons/8-bit/160/bit-12-512.png',
    SmallImageIconUrl: 'https://cdn4.iconfinder.com/data/icons/8-bit/160/bit-12-512.png'
}
```

How do i show Image on notification??

**Comment by Sahejmaharjan1** [comment]
@ashika01 is ``@aws-amplify/pushnotification``  not able to handle notification images? Have been searching how to implementing images on notification for a while now and can't get any further..

**Comment by amhinson** [comment]
Sorry for the delay @Sahejmaharjan1. The library currently doesn't support images, but I will mark this as a feature request to make sure it is taken into account in the future 👍

**Comment by Sahejmaharjan1** [comment]
Ok @amhinson. One of a must have feature for notification hope it gets added soon.

**Comment by ziwenpickle** [comment]
@amhinson Hi, any news if push notifications supports images?

**Comment by tannerabread** [comment]
Hi @Sahejmaharjan1, @ziwenpickle we have recently released a rewritten Push Notification category with new features including the ability to send images with notifications, can you try it out and let me know if it works for you?

You can follow the [migration steps here](https://docs.amplify.aws/lib/push-notifications/migrate-from-previous-version/q/platform/react-native/) or if you are starting again from scratch follow the [getting-started guide here](https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/react-native/)

**Comment by tannerabread** [comment]
Hi 👋 Closing this as resolved. This should be handled with the recent release of the rewritten Push Notification category mentioned above. 

If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with additional information so we can re-open this issue and be better able to assist you.

Thank you!
