### ISSUE TITLE
Allow setting SSR cookies as `lax` when using `ssr` setting

### ISSUE THREAD

**Issue by jdmwood** [aws-amplify/amplify-js#6884]
**Is your feature request related to a problem? Please describe.**

As expected, when I set `ssr: true` in the config, amplify sets a couple of cookies which are sent with all requests.

The issue is that these are set to `SameSite = strict` which means that when I follow a link from a third party (e.g. clicking a link in gmail), these cookies are filtered out by the browser.

**Describe the solution you'd like**

A config setting which allows setting the cookie policy to `lax` when operating in SSR mode.

**Describe alternatives you've considered**

We could simply switch to using cookie only storage by setting the `cookies` section of the configuration but this is not so desirable as this causes everything to be stored in cookies which increases the size of every server side request (whereas the current approach only seems to send the minimal cookies, using local storage for everything else).

**Additional context**

**Comment by jdmwood** [comment]
Wow @stocaaro this was 3 years ago... I can barely remember what I had for breakfast this morning!

I *think* the issue was that when you click a link in another domain (I believe the context was a link in an email in gmail) when you arrive at our site you were not automatically logged in because of the `SameSite = strict` policy (the cookies were not sent). This is because of the way `SameSite = strict` works.

If you hit refresh it was fine.

So I think we just wanted a way to configure this setting to `lax` which is the most usual behaviour.

**Comment by stocaaro** [comment]
Hi @jdmwood,

Appreciate your thoughts/memories on this 3 years later. We have folks working on improving the auth workflow and SSR support in the near future (months, not years). Trying to make sure we catch any requirement / behavior misses for those deliverables.

I'm going to review this with a peer or two and might come back with more questions later today.

Thanks!
Aaron

**Comment by NtchPlayer** [comment]
Hi !
Any news about this feature request ?
Allow configuration of cookie can be very helpfull if your login page is on specific domain (example www.mywebsite.com) and our backend application on another domain (backend.mywebsite.com).

@stocaaro

**Comment by nadetastic** [comment]
Hi @jdmwood @NtchPlayer following up here - With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved as the SSR cookies default is `lax`.

Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/build-a-backend/server-side-rendering/)for more information.
