### ISSUE TITLE
React native Ui block when uploading

### ISSUE THREAD

**Issue by aneeshtoobler** [aws-amplify/amplify-js#6888]
**Describe the bug**
Upload to using 

**To Reproduce**

1. npm install aws-amplify --save
2. npm install aws-amplify-react-native --save
3. import { Storage } from "aws-amplify";
4.Storage.put(key, blob, {
    contentType: blob.type,
    metadata: { payload: JSON.stringify(meta) },
  });

**Expected behavior**
Using  "aws-amplify": "3.3.1",

Upload file in background thread with out making block in UI

**Code Snippet**
.Storage.put(key, blob, {
    contentType: blob.type,
    metadata: { payload: JSON.stringify(meta) },
  });

**What is Configured?**
amplifyConfig = {
  Auth: {
    identityPoolId: XX-XXXX,
    region: AWS.REGION
  },
  Storage: {
    bucket: AWS.S3_BUCKET,
    region: AWS.REGION
  }
}

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone11]

**Comment by radom88** [comment]
@sammartinez as per discussed with Elise in the AWS Builders community, see the issue above with amplify v3

**Comment by romeorr** [comment]
@sammartinez as per discussed with Elise in the AWS Builders community, see the issue above with amplify v3

**Comment by sammartinez** [comment]
Thanks @romeorr for cutting this! Ill see about having our oncall look into this once we are freed up

**Comment by romeorr** [comment]
@sammartinez let me know if you need more information here - this is a big blocker for us right now and our live application so would be keen to collaborate with you guys on this to fix this and provide as much information as you need for fixing it. For now we have to temporarily look at a different library unfortunately but keen to revert back to amplify v3 for the upload process.

**Comment by ahansson89** [comment]
Can this please be prioritized?

**Comment by chrisbonifacio** [comment]
Sorry for the delay. We are currently working on a fix for this. Closing this as a dupe. Please track this issue as it should also fix this issue once we have the PR ready.

https://github.com/aws-amplify/amplify-js/issues/6419

**Comment by SaurabhDixit120987** [comment]
I am facing the same issue
