### ISSUE TITLE
Auth.currentAuthenticatedUser replacing URL parameters with category=0

### ISSUE THREAD

**Issue by MattM31** [aws-amplify/amplify-js#6892]
Before performing an API call to api gateway with fetch I call Auth.currentAuthenticatedUser to refresh the tokens as they were expiring if the browser was left open on my app for too long so I assumed calling the above function first would prevent API gateway returning Unauthorized responses if the tokens expired. But when I call the above function its removing my current url params and replacing them with category=0, thus confusing my app. I have no idea where the category=0 is coming from or why its appearing when calling  Auth.currentAuthenticatedUser. An example of my code is below.

``
Auth.currentAuthenticatedUser({
      bypassCache: false  
    }).then(user => {
      console.log(user);
      // REST OF THE FETCH API CALL USING THE REFRESHED TOKENS, CATCH STATEMENTS ETC
 };
``

**Comment by amhinson** [comment]
If I'm understanding correctly, you're saying that the URL params are replaced with `category=0` only after calling `Auth.currentAuthenticatedUser({ bypassCache: false })`?

**Comment by sammartinez** [comment]
@MattM31 Can you respond to @amhinson question? Thanks ahead of time
