### ISSUE TITLE
PushNotification.onRegister generate token once on IOS

### ISSUE THREAD

**Issue by RadagastCH** [aws-amplify/amplify-js#6910]
**Describe the bug**
PushNotification.onRegister generate token only first time and then never called 

**To Reproduce**

Works only on iOS 

1. Open app
2. Press accept for Push Notification 
3. Token is returned 
4. Choose future date( That's force iOS to crate new notification token ) 
5. Token is not returned 

**Expected behavior**
The token should be returned for each change or just each request 

**Code Snippet**
PushNotification.onRegister(token => {
  console.log("in app registration", token);
});

**What is Configured?**
   aws-amplify: 2.2.5
   aws-amplify-react-native: 3.2.2
   aws-amplify/pushnotification: 3.1.3
   react-native: 0.63.2

**Smartphone (please complete the following information):**
- Device: iPhone7
- OS:  iOS14.0
- Version React-native 0.63

**Comment by ashika01** [comment]
@RadagastCH Whats the use case for wanting token on each request?! `onRegister` is primarily to register the device with pinpoint for PushNotification.

**Comment by RadagastCH** [comment]
> @RadagastCH Whats the use case for wanting token on each request?! 
On request I mean `onRegister` because this is a request from js thread to native



> `onRegister` is primarily to register the device with pinpoint for PushNotification.
Definitely no, I don't where you read this, but the [documentation](https://docs.amplify.aws/lib/push-notifications/working-with-api/q/platform/js)  says:  
_The onRegister handler will only be triggered once when the token is generated or updated by the push provider i.e. Apple/Google (and when the app opened the first time)._

Also, you should see this on documentation  
`
// This will only be triggered when the token is generated or updated.
PushNotification.onRegister((token) => {
  console.log('in app registration', token);
});
`

**Comment by ashika01** [comment]
@RadagastCH Sorry for the confusion. Did not mean to offend anyone. I was wondering about the use case/ what you are trying to achieve with the token, so I could help better.

Also, sorry for the misunderstanding, what I meant with
> onRegister is primarily to register the device with pinpoint for PushNotification.

Is exactly what you mentioned here, 
> This code register the device token to the Pinpoint
>
> PushNotification.updateEndpoint(token)

**Comment by ashika01** [comment]
Couple of things that could help us out here to debug this,

1. Could you explain in detail about your step 3 and how I can reproduce that
2. If you could provide a sample code snippet/ repo to reproduce the issue you are facing

Side note: Just calling out, looks like you are in old version of aws-amplify. We have so many update since then suggest trying new version so it help with finding the root cause.

**Comment by RadagastCH** [comment]
Latest packages is worked to me
Thanks to @ashika01 
I will close this

**Comment by vivekvt** [comment]
PushNotification.onRegister(async (token) => {
  await AsyncStorage.setItem('deviceToken', token);
  console.log(`PushNotification.onRegister: ${token}`);
  PushNotification.updateEndpoint(token);
});

On iOS i am getting token = null


It is working fine on android

I followed everything as told in -  [https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/js](https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/js)
