### ISSUE TITLE
Pass custom attribute to Federated Signin

### ISSUE THREAD

**Issue by bilalashraf1710** [aws-amplify/amplify-js#6913]
**Which Category is your question related to?**
Federated Signin

**Amplify CLI Version** 
4.18.1

**What AWS Services are you utilizing?**
AWS Cognito

**Provide additional details e.g. code snippets**
I want to pass a custom attribute with the federated signin.
At the moment I am doing:
"Auth.federatedSignIn({ provider: "Google" })"

But I want to do something like this:
"Auth.federatedSignIn({ provider: "Google", 'custom:group': 'groupname' })"

Is it possible to do it?

What other options do I have if I want to assign a group to a user by passing the custom group name somehow?

**Comment by renebrandel** [comment]
@sammartinez this seems to be a library issue.

**Comment by elorzafe** [comment]
@bilalashraf1710 

What you mention is not possible from the client.

For assigning the user to a group you will have to configure a lambda trigger. By default federated users are assign to a group with the provider name. If you are using Amplify cli you can take a look on [Cognito lambda triggers section](https://docs.amplify.aws/cli/usage/lambda-triggers#cognito-lambda-triggers)

**Comment by LaurentEscalier** [comment]
Hey there ! I am facing a situation that relates to this issue:

When a user signs up with Federated SignIn, I'd like to save the preferred locale using Cognito's locale attribute. Unfortunately, not all providers share the user's preferred locale. I'd like to be able to pass the preferred locale as a custom attribute:

```
Auth.federatedSignIn({
  provider: "Google",
  attributes: {
    'locale': currentLocale
  }
});
```

Is there a way to achieve that ?

**Comment by mercan-topkara** [comment]
I am also looking into a solution for this.
