### ISSUE TITLE
Storage.list returning an incorrect list of files

### ISSUE THREAD

**Issue by stayingcool** [aws-amplify/amplify-js#6916]
**Issue**
Storage.list is returning an incorrect list of files.

**Expected behavior**
The list API should return files only for specific ID (Example - 125).

**To Reproduce**
Here is the screenshot of my UI showing an incorrect list of files being returned:
<img width="195" alt="Screen Shot 2020-10-06 at 8 30 53 pm" src="https://user-images.githubusercontent.com/31205483/95184437-14b8fa80-0813-11eb-978e-3c3e40eb8717.png">

The API was invoked with the ID as 125. However, the result came up with the list of files for IDs (125, 1250,  1256 ...).

**Code Snippet (Excerpt)**
```
import { Storage } from "aws-amplify";

export function getAttachments(ID) {
  const path = {
    public: "uploads/orders/tax/attachments/",
  };

  return function (dispatch) {
     return Storage.list(ID, {
        customPrefix: path,
      })   
  };
}
```

**Env**
package.json:
"aws-amplify": "^3.0.13",

Amplify CLI:
4.25.0

**Comment by ashika01** [comment]
@stayingcool Sorry I dont understand you request for ID here. `Storage.list` can only take input as path. Can you brief more on this so I can help.

Also, if you are trying to get all file under `125/`, I suggest you make an call something along these lines,

`Storage.list('uploads/orders/tax/attachments/125/')`

**Comment by stayingcool** [comment]
This is the excerpt code from my other project with Amplify Version ("aws-amplify": "1.2.4",) which seems to be working fine.
```
getListOfAttachments(ID: string): Promise<Attachment[]> {
        return new Promise((resolve, reject) => {
            Storage.list(ID, {
                customPrefix: this.customPrefix
            }).then(function (results) {
                results.map(item => {
                    return new Attachment(
                        item.key,
                        item.lastModified,
                        item.size
                    );
                });
                resolve(results);
            }).catch(function (results) {
                reject(results)
            });
        });
    }
```

I think this issue is with customPrefix. Not sure if the current version of Storage.list API went through change due to which the API returns all the bucket contents with a begins with clause maybe!

As per your suggestion, If I invoke the API as follows then the API returns an empty response:
```
getListOfAttachments(ID) {
    let path = `uploads/orders/tax/attachments/${ID}`
    return Storage.list(path);
  }
```
**Request in Chrome**
<img width="1377" alt="Screen Shot 2020-10-07 at 10 46 41 am" src="https://user-images.githubusercontent.com/31205483/95271921-df4ff380-088a-11eb-9343-3f352f6408e4.png">

**Response in Chrome**
<img width="902" alt="Screen Shot 2020-10-07 at 10 51 00 am" src="https://user-images.githubusercontent.com/31205483/95272100-3c4ba980-088b-11eb-829b-acbcfa4a4ff4.png">


**This is the path where the attachments are being stored:**
<img width="899" alt="Screen Shot 2020-10-07 at 10 24 42 am" src="https://user-images.githubusercontent.com/31205483/95271327-597f7880-0889-11eb-85fe-473f307b241f.png">

**Comment by ashika01** [comment]
@stayingcool The older version of Amplify was using `aws-sdk-js` v2 but the latest ones use https://github.com/aws/aws-sdk-js-v3. Looking at ts file for the call, it was the path. I will try custom prefix and update here in a while. Thanks for the info, let me get back with some code snippets.

**Comment by ashika01** [comment]
@stayingcool : Hey, sorry my suggestion was wrong. Apologies from my end.

Could you turn on the the Amplify debug logger by following to `App.js` 
`Amplify.Logger.LOG_LEVEL = 'DEBUG';`

And what the list file resolves to. Screenshot similar to this,

![Screen Shot 2020-10-07 at 5 15 03 PM](https://user-images.githubusercontent.com/35131273/95401030-0a553a00-08c1-11eb-9630-a9e17359b6e7.png)

**Comment by stayingcool** [comment]
<img width="1250" alt="Screen Shot 2020-10-08 at 1 02 29 pm" src="https://user-images.githubusercontent.com/31205483/95406804-0c71d400-0967-11eb-99d4-68c6f2f3196b.png">

**Comment by ashika01** [comment]
@stayingcool I want you to try do do that list with `125/` rather than `125` you have here.
