### ISSUE TITLE
Unexpected validation error for custom email message using ReactDOMServer.renderToStaticMarkup

### ISSUE THREAD

**Issue by theshumanator** [aws-amplify/amplify-js#6917]
**Describe the bug**
When I try to create a custom message using ReactDOMServer.renderToStaticMarkup, I get a validation error. However if I pass the value and regex into a regex tool, I get a match.

Error below:
`
1 validation error detected: Value '<html><body><div style="padding:20"><h4>Hi, there!</h4><p>Thank you for signing up to xxx. Here is the confirmation code {####} to complete your registration.</p><p> </p><p>--</p><p>Happy days,</p><p>CompanyName</p></div></body></html>' at 'emailBody' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{M}\p{S}\p{N}\p{P}\s*]*\{####\}[\p{L}\p{M}\p{S}\p{N}\p{P}\s*]*
`

**To Reproduce**
I have a lambda that handles the `CustomMessageTriggerEvent` events. It sets the `event.response.emailSubject` and `event.response.emailMessage`. The problem is with the `emailMessage` field.

See code snippet below.

**Expected behavior**
It should just work.

**Code Snippet**
```
event.response.emailMessage = getCustomEmailMessage(triggerSource, event.request.codeParameter);
```
calls:
```
const getCustomEmailMessage = (triggerSource: string, codeParameter: string): string => {
    if (triggerSource === 'CustomMessage_SignUp') {
        return getHtmlMessage(
            `Thank you for signing up to CompanyName. Here is the confirmation code ${codeParameter} to complete your registration.`
        );
    } else {
       //do something else
}
};
```
```
const getHtmlMessage = (textToInject: string): string => {
const reactComponent = renderEmailMessage(textToInject)
 return "<html><body>" + reactComponent + "</body></html>"
//I have also tried using return`<html><body>${reactComponent}</body></html>`
};
```
The `renderEmailMessage` is in `EmailMessage.tsx`. The entire file is below:
```import React from "react";
import ReactDOMServer from "react-dom/server";

interface EmailMessageProps {
    code: string;
}
 const EmailMessage: React.FC<EmailMessageProps> = ({code}: EmailMessageProps) => (
    <div style={{padding: "20"}}><h4>Hi, there!</h4><p>{code}</p><p>&nbsp;</p><p>--</p><p>Happy hacking,</p><p>CompanyName</p></div>
  );

export const renderEmailMessage = (code: string) => {
    return ReactDOMServer.renderToStaticMarkup(<EmailMessage code={code} />)
}
```

If instead of using react and I simply have the below in `getHtmlMessage`, it works:

```
const getHtmlMessage = (textToInject: string): string => {
    return `<html>
                <body>
                    <div style="padding: 20;">
                        <h4>Hi, there!</h4><p>${textToInject}</p><p>&nbsp;</p><p>--</p><p>Happy hacking,</p><p>CompanyName</p>
                    </div>
                </body>
            </html>`;
};
```

**Comment by amhinson** [comment]
@theshumanator Could you share some more information:
- Amplify packages with versions
- Code snippet of Amplify usage

Based on what you provided, it doesn't look like this issue is related to `aws-amplify`.

**Comment by theshumanator** [comment]
Hi @amhinson ,

Amplify packages w/versions:
aws-amplify: 2.3.0 
aws-amplify-react: 3.1.9

Amplify usage:
```
import { Authenticator, ConfirmSignIn, ConfirmSignUp, ForgotPassword, Loading, RequireNewPassword, SignIn, SignUp, VerifyContact } from 'aws-amplify-react'

const signUpConfig = {
    hideAllDefaults: true,
    signUpFields: [
        {
            label: 'Email',
            key: 'username',
            required: true,
            placeholder: 'Email',
            type: 'email',
            displayOrder: 1,
        },
        {
            label: 'Password',
            key: 'password',
            required: true,
            placeholder: 'Password',
            type: 'password',
            displayOrder: 2,
        }
    ]
}

const amplifyConfig = {
            Auth: {
                //enrich with userpool info
            },
            Analytics: {
                disabled: true
            }
        };

const amplifyTheme = {
    formContainer: {
        margin: 0
    },
    formSection: {
        boxShadow: 'none',
        marginBottom: 0
    },
    toast: {
        backgroundColor: //color from my palette,
        position: 'relative'
    },
    button: {
        backgroundColor: //color from my palette
    },
    a: {
        color: //color from my palette
    },
}


//the  component is here:
        <Authenticator hideDefault={true}
                       theme={amplifyTheme}
                       amplifyConfig={amplifyConfig}
                       onStateChange={onStateChange}
            >
            <SignIn/>
            <ConfirmSignIn/>
            <RequireNewPassword/>
            <SignUp signUpConfig={signUpConfig}/>
            <ConfirmSignUp/>
            <VerifyContact/>
            <ForgotPassword/>
            <Loading/>
        </Authenticator>
```

**Comment by amhinson** [comment]
I'm still a bit confused on your issue here. Where exactly are you seeing the error? Would you be able to provide more detailed  reproduction steps so we can attempt to see the same behavior?

**Comment by theshumanator** [comment]
I have a web app that uses amplify & cognito for user authentication.

I would like to customise the messages users receive on email. So I created a lambda (separate from the web app app) which handles the CustomMessageTriggerEvent events. It sets the event.response.emailSubject and event.response.emailMessage. 

The two events I'm trying to customise a message for are the forgot password and the sign up events.

If I set `event.response.emailMessage` to raw html (see first message for details) then it works fine, i.e the user receives the new customised email message. 

However, if I use `ReactDOMServer.renderToStaticMarkup`, the user gets an error message on the sign in form.

The error message is:
```1 validation error detected: Value '<html><body><div style="padding:20"><h4>Hi, there!</h4><p>Thank you for signing up to xxx. Here is the confirmation code {####} to complete your registration.</p><p> </p><p>--</p><p>Happy days,</p><p>CompanyName</p></div></body></html>' at 'emailBody' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{M}\p{S}\p{N}\p{P}\s*]*\{####\}[\p{L}\p{M}\p{S}\p{N}\p{P}\s*]*```

It seems like amplify (or service in the backend?) is doing some pattern matching for validation. However, if I pass the above to regex tool, it matches the expected pattern. So I don't understand why there is an issue or how to fix it.

**Comment by amhinson** [comment]
Ah ok I understand now. Thanks for the info! This does look more related to the Cognito service itself. Did you create the lambda with Amplify as well (`amplify add function`)?

**Comment by theshumanator** [comment]
No, I created the lambda using AWS CDK.
Re the validation error that appears on the amplify login form, does that mean the Cognito service is sending this error back to the form because it cannot handle this specific html/custom message?
Thanks.

**Comment by amhinson** [comment]
It appears that way. I would suggest reaching out to AWS Cognito support on this issue to see if they can provide any additional insight.

**Comment by igorkosta** [comment]
@amhinson why has this issue been closed without providing the link to the `AWS Cognito support` issue. I'm experiencing the same issue although I created the function for custom message with `amplify`
