### ISSUE TITLE
currentCredentials() hangs when on offline mode

### ISSUE THREAD

**Issue by ablbol** [aws-amplify/amplify-js#6918]
I am using the following 2 functions to make sure user is authenticated and get some info about the user:

Auth.currentAuthenticatedUser({bypassCache: false})
Auth.currentCredentials()

When the user is in online mode, both functions return data without any problem.  However when going offline (no network), 
 currentCredentials() hangs and does not return or throw any exception.  In other words, my application keeps waiting right at currentCredentials().

I expect that currentCredentials() should return data from cache but it does not.

I am using the following libraries:

"react": "16.13.1",
"react-native": "0.63.3",
"@aws-amplify/pushnotification": "^3.2.6",
"aws-amplify": "^3.3.3",
"aws-amplify-react-native": "^4.2.7",
"aws-appsync": "^4.0.1",
"aws-appsync-auth-link": "^3.0.2",
"aws-appsync-subscription-link": "^3.0.3",

My config looks like this:

```
{
  aws_project_region: AWS_PROJECT_REGION,
  aws_appsync_graphqlEndpoint: AWS_APPSYNC_GRAPHQLENDPOINT,
  aws_appsync_region: AWS_APPSYNC_REGION,
  aws_appsync_authenticationType: AWS_APPSYNC_AUTHENTICATIONTYPE,
  Auth: {
    identityPoolId: AWS_COGNITO_IDENTITY_POOL_ID,
    region: AWS_COGNITO_REGION,
    userPoolId: AWS_USER_POOLS_ID,
    userPoolWebClientId: AWS_USER_POOLS_WEB_CLIENT_ID,
  },
  oauth: {
    domain: AWS_COGNITO_DOMAIN,
    scope: ['email', 'openid', 'profile', 'aws.cognito.signin.user.admin'],
    redirectSignIn: REDIRECT_SIGN_IN,
    responseType: 'code',
  },
  Storage: {
    AWSS3: {
      bucket: AWS_USER_FILES_S3_BUCKET,
      region: AWS_USER_FILES_S3_BUCKET_REGION,
    },
  },
  PushNotification: {
    requestIOSPermissions: false,
  },
  Analytics: {
    appId: AWS_MOBILE_ANALYTICS_APP_ID,
    region: AWS_MOBILE_ANALYTICS_APP_REGION,
  },
}
```

I am testing on iPhone simulator.

What is the right behavior of Auth.currentCredentials() when going offline. Thanks in advance.

**Comment by elorzafe** [comment]
@ablbol are you getting always this error or might be that the access token is expired when you are making the API call?

**Comment by ablbol** [comment]
I am not getting an error.  The application halts right at the Auth.currentCredentials() function without throwing exception.  This happens as soon as I go off line.  If I go back online and refresh, the application will be fine.

**Comment by ablbol** [comment]
To see the problem really well, please do these things:

- Use real mobile device (I user Android).
- Go offline
- Refresh your application (This is important step).

Once you do that, you will see your application halting at Auth.currentCredentials().

In couple occasions, the application did not halt at the function but I was never able to get identityId (when offline).

**Comment by lucianomlima** [comment]
Any news related to use amplify offline with RN?

**Comment by tannerabread** [comment]
Seems like a similar thing happens with `currentSession` 
#7464

**Comment by tannerabread** [comment]
Hi @ablbol, apologies for the delay in a response on this issue. I am trying to reproduce it and have run into a couple of questions related to the setup:
1. Does this only happen on a real device or is it just more consistent there? I am not seeing the behavior on an emulator, instead it throws the error `TypeError: Network request failed` when I am in offline mode.
2. Are you calling the function manually or is it run every time your app/component loads?
3. How are you reloading your app after going offline?

**Comment by tannerabread** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and are in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
