### ISSUE TITLE
Cannot find file './aws-exports' in './src'

### ISSUE THREAD

**Issue by duncangroenewald** [aws-amplify/amplify-js#6923]
Describe the bug
When building Frontend with AWS CI/CD we are now getting this error.

To Reproduce
Any time we commit code the CodeCommit and the front-end application is deployed we get this error during the build process

Expected behaviour
The build process should automatically create the aws-exports.js file relevant for the environment being deployed to.

Screenshots
N/A

Desktop (please complete the following information):
N/A

Smartphone (please complete the following information):
N/A

Additional context
It's not clear what other information is required. As we understand it the aws-exports.js file should be created automatically by AWS Amplify when the Frontend is built. It's unclear where there is anything we need to do to or might have don't to affect creation of the aws-exports.js file.

**Comment by ashika01** [comment]
@duncangroenewald are you using setting up your backend using Amplify CLI?!
