### ISSUE TITLE
Remove auth attribute from required but still it's create as required 

### ISSUE THREAD

**Issue by lochawala** [aws-amplify/amplify-js#6924]
**Describe the bug**
when i add auth in amplify and removing email from required attribute still it's create as required  

**To Reproduce**

amplify add auth
Do you want to use the default authentication and security configuration?
❯ Default configuration
How do you want users to be able to sign in?
❯ Email or Phone Number
Do you want to configure advanced settings?
❯ Yes, I want to make some additional changes.
What attributes are required for signing up?
❯ unselect Email
Do you want to enable any of the following capabilities?
❯ hit enter
amplify push

**Expected behavior**
create user pull as not required email attribute

**Comment by ashika01** [comment]
@lochawala What is the error you are seeing? Could you provide with your amplify js code sample.

Also, I would suggest to through the manual configuration flow in CLI rather than going down default and unselecting required.

**Comment by lochawala** [comment]
@ashika01 Thanks for your reply 
I have tried with custom configuration too, but still, it's created email as required attribute 
I have attached some screen shots for better understanding
 
![Screen Shot 2020-10-08 at 10 02 45 AM](https://user-images.githubusercontent.com/14148438/95415602-539f9b00-094e-11eb-8499-4b093573d761.png)


![Screen Shot 2020-10-08 at 10 07 18 AM](https://user-images.githubusercontent.com/14148438/95415538-2521c000-094e-11eb-8732-bcb85d032c2d.png)


Check in first screenshot I have unselected email, but in the 2nd screen shot you can seen email as a required attribute

**Comment by ashika01** [comment]
Hi @lochawala I was able to setup with just username login by following manual configuration.

This is steps to go through in Amplify CLI for manual configuration,
![Screen Shot 2020-10-08 at 2 19 56 PM](https://user-images.githubusercontent.com/35131273/95517755-79409a80-0976-11eb-9a15-a8fcc78e8d5e.png)


This is my userpool console equivalent,
![Screen Shot 2020-10-08 at 2 53 50 PM](https://user-images.githubusercontent.com/35131273/95517799-8eb5c480-0976-11eb-82d8-168b45056547.png)


If you want your users to sign in with email and phone number it will become required attribute. That might be why you are having problems. I am moving this to discussion to get help from community.
