### ISSUE TITLE
UnauthorizedException at AWSAppSyncRealTimeProvider

### ISSUE THREAD

**Issue by darylalexjohnson** [aws-amplify/amplify-js#6938]
**Describe the bug**
We are using Amplify -> Appsync in our project. We are using OIDC for auth and after a successful handshake with the client to establish a subscription, the client (amplify) sends a `connection_init` message to start the communication with the AWS AppSync real-time endpoint.
 
The header in this request contains
```
"Authorization": <string>: JWT Access Token.       
"host": <string>: This is the host for the AWS AppSync GraphQL endpoint.
``` 
The response from the `connection_init` is an `UnauthorizedException`
 
#### Debug
```
[DEBUG] 46:44.546 AuthClass - Succeed to get the user session CognitoUserSession {idToken: CognitoIdToken, refreshToken: CognitoRefreshToken, accessToken: CognitoAccessToken, clockDrift: 1}
ConsoleLogger.ts:91 [DEBUG] 46:44.547 AWSAppSyncRealTimeProvider - Initializaling retryable Handshake
ConsoleLogger.ts:91 [DEBUG] 46:44.547 Util - bound  attempt #1 with this vars: [{"awsRealTimeUrl":"wss://xxxxxxxx.appsync-realtime-api.us-west-2.amazonaws.com/graphql?header=jwtToken==&payload=e30="}]
ConsoleLogger.ts:91 [DEBUG] 46:44.547 AWSAppSyncRealTimeProvider - Initializing handshake wss://xxxxxxxx.appsync-realtime-api.us-west-2.amazonaws.com/graphql?header=jwtToken==&payload=e30=
ConsoleLogger.ts:91 [DEBUG] 46:44.679 AWSAppSyncRealTimeProvider - subscription message from AWS AppSyncRealTime: {"payload":{"errors":[{"errorType":"UnauthorizedException","message":"Unauthorized"}]},"type":"connection_error"} 
ConsoleLogger.ts:99 [DEBUG] 46:44.679 Util - error on bound  Error: UnauthorizedException
    at AWSAppSyncRealTimeProvider.<anonymous> (AWSAppSyncRealTimeProvider.ts:731)
    at step (AWSAppSyncProvider.ts:204)
    at Object.throw (AWSAppSyncProvider.ts:204)
    at rejected (AWSAppSyncProvider.ts:204)
```

### Websocket Sequence
```
Websocket Sequence
{"type":"connection_init"}
{"payload":{"errors":[{"errorType":"UnauthorizedException","message":"Unauthorized"}]},"type":"connection_error"}
```

**Expected behavior**
Sequence of events
To successfully initiate, establish, register and process the subscription request, the client must step through the following sequence:
 
1. Initialize connection (connection_init) <-- We are stuck here.
2. Connection acknowledgment (connection_ack)
3. Subscription registration (start)
4. Subscription acknowledgment (start_ack)
5. Processing subscription (data)
6. Subscription unregistration (stop)

### Amplify Configuration
   ```
  const AMPLIFY_CONFIG = {
    region,
    userPoolId: userPoolId,
    userPoolWebClientId: clientId,
    oauth: {
        domain: issuer,
        scope: ['openid'],
        redirectSignIn: `${window.location.origin}/callback`,
        responseType: 'code',
        codeChallengeMethod: 'S256',
        codeChallenge: encodeURI(btoa(Math.random())),
    },
    aws_appsync_graphqlEndpoint: graphQLEndpoint,
    aws_appsync_region: region,
    aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
    graphql_headers: async () => ({
        Authorization: (await Auth.currentSession()).getIdToken().getJwtToken(),
    }),
};
   ```
### Subscription Schema
```
type Subscription @aws_cognito_user_pools(cognito_groups: ["AllowedGroup"])
@aws_oidc {
	onUpdateObjectPermissions: Permission
		@aws_subscribe(mutations: ["updateObjectPermissions"])
}
```

**Comment by darylalexjohnson** [comment]
I have determined that the `header` in:
 `wss://xxx.appsync-realtime-api.region.aamazonaws.com/graphql?header={<this is the access_Token>}` 
is the access token. Since this is OIDC auth, I would expect it to be the `idToken` - Would this be from this setting?
```aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",```

Changing the authentication type to `OPENID_CONNECT` results in:
```
[INFO] 33:45.483 Cache - Get item: key is federatedInfo with options undefined
```
I am on Amplify 3.3.3 which included a fix around this [issue](https://github.com/aws-amplify/amplify-js/pull/6858). When I change this setting to `OPENID_CONNECT` I am still getting `No federated jwt at GraphQLAPIClass`. [Reference](https://github.com/aws-amplify/amplify-js/blob/main/packages/api-graphql/src/GraphQLAPI.ts#L141). My response from my identity provider returns: 
```
{
  access_token: "..."
  expires_in: 3600
  id_token: "..."
  refresh_token: "..."
  token_type: "Bearer"
}
```

**Comment by amhinson** [comment]
@darylalexjohnson When using `OPENID_CONNECT`, it is expecting the OIDC token to be set either by authenticating with Cognito Identity Pools with `Auth.federatedSignIn()` (which adds the token to the return of `Auth.currentAuthenticatedUser()`) or using `Cache.setItem('federatedInfo', <token>)`.

If you don't want to authenticate with Identity Pools, can you try setting the token to the `Cache` manually and see if that resolves your issue?

Reference:
https://github.com/aws-amplify/amplify-js/blob/e1d122bec0fb67eab0a696ee6e0ffa976631e4f0/packages/api-graphql/src/GraphQLAPI.ts#L141-L159

**Comment by darylalexjohnson** [comment]
Manually setting the token to Cache on the hub signIn event worked. Thanks for the direction.
