### ISSUE TITLE
amazon-cognito-identity-js Does not build on Android against React Native 0.63.3

### ISSUE THREAD

**Issue by aloknecessary** [aws-amplify/amplify-js#6942]
**Describe the bug**
Task :amazon-cognito-identity-js:compileDebugJavaWithJavac FAILED

**To Reproduce**

Create a new RN project on RN 0.63.3 version;
Install amazon-cognito-identity-js & @aws-amplify/pushnotification package;
Start dev build `react-native run-android`

**Expected behavior**
dev bundling should complete and app should launch

**Code Snippet**
yarn run v1.22.4
$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1281 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...

 

> Configure project :app
Reading env from: .env
Unable to read signing.debug.properties......using default signing configuration
Unable to read signing.release.properties......using default signing configuration

 

> Configure project :react-native-firebase_app
:react-native-firebase_app package.json found at D:\Byteridge\PROJ\iuiw-ui-react\node_modules\@react-native-firebase\app\package.json
:react-native-firebase_app:firebase.bom using default value: 25.7.0
:react-native-firebase_app:play.play-services-auth using default value: 16.0.1
:react-native-firebase_app package.json found at D:\Byteridge\PROJ\iuiw-ui-react\node_modules\@react-native-firebase\app\package.json
:react-native-firebase_app:version set from package.json: 8.4.5 (8,4,5 - 8004005)
:react-native-firebase_app:android.compileSdk using custom value: 30
:react-native-firebase_app:android.targetSdk using custom value: 30
:react-native-firebase_app:android.minSdk using custom value: 21
:react-native-firebase_app:reactNativeAndroidDir D:\Byteridge\PROJ\iuiw-ui-react\node_modules\react-native\android

 

> Configure project :react-native-firebase_crashlytics
:react-native-firebase_crashlytics package.json found at D:\Byteridge\PROJ\iuiw-ui-react\node_modules\@react-native-firebase\crashlytics\package.json
:react-native-firebase_app package.json found at D:\Byteridge\PROJ\iuiw-ui-react\node_modules\@react-native-firebase\app\package.json
:react-native-firebase_crashlytics:firebase.bom using default value: 25.7.0
:react-native-firebase_crashlytics package.json found at D:\Byteridge\PROJ\iuiw-ui-react\node_modules\@react-native-firebase\crashlytics\package.json
:react-native-firebase_crashlytics:version set from package.json: 8.4.9 (8,4,9 - 8004009)
:react-native-firebase_crashlytics:android.compileSdk using custom value: 30
:react-native-firebase_crashlytics:android.targetSdk using custom value: 30
:react-native-firebase_crashlytics:android.minSdk using custom value: 21
:react-native-firebase_crashlytics:reactNativeAndroidDir D:\Byteridge\PROJ\iuiw-ui-react\node_modules\react-native\android

 

> Task :amazon-cognito-identity-js:compileDebugJavaWithJavac FAILED

 

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
9 actionable tasks: 9 executed

 

FAILURE: Build failed with an exception.

 

* What went wrong:
Execution failed for task ':amazon-cognito-identity-js:compileDebugJavaWithJavac'.
> Could not create service of type DefaultGeneralCompileCaches using GradleScopeCompileServices.createGeneralCompileCaches().

 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

 

* Get more help at https://help.gradle.org

 

BUILD FAILED in 8s

 

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

 

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Screenshots**

**What is Configured?**

aws  push notifications & analytics 
 
**Smartphone (please complete the following information):**

- Device: [e.g. Vivo 1803]
- OS: [e.g. Android 8.1]

**Additional context**

It works perfectly if we remove these two packages

**Comment by thenderson55** [comment]
Have you tried deleting node_modules and cleaning all the caches then run with sudo?

```sudo react-native run-android```

**Comment by sammartinez** [comment]
@aloknecessary Are you following the setup steps for push notifications [here](https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/js)? Are you following the setup for the `gradle` changes listed under [Setup for Android](https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/js#setup-for-android) ? Please let us know.

**Comment by galgord** [comment]
Can we please re-open this issue? It is still not working for me.
I get the following error:
> Task :amazon-cognito-identity-js:compileDebugJavaWithJavac FAILED
/Users/galgordon/dev/React Native/pets/node_modules/amazon-cognito-identity-js/android/src/main/java/com/amazonaws/RNAWSCognitoModule.java:48: error: cannot find symbol
  @ReactMethod(isBlockingSynchronousMethod = true)
               ^
  symbol:   method isBlockingSynchronousMethod()
  location: @interface ReactMethod
1 error

**Comment by alivemachine** [comment]
Same, this has not been solved and is an issue for me too.
