### ISSUE TITLE
Cannot read property 'items' of null at SyncProcessor. DataStore errror at initialization. 

### ISSUE THREAD

**Issue by EliasCoelho** [aws-amplify/amplify-js#6946]
**Describe the bug**
DataStore exception is throwing while DataStore initializing.  The SyncProcessor cannot read property items of null. Using DataStore channel hub for listen event changes, the Ready events is not fired because the exception interrumped workflow. 

**To Reproduce**
* Install aws-amplify 3.3.3
* Hub.listen('datastore', calback)
* DataStore.Start()

**Expected behavior**
DataStore initialization without SyncProcessor error

![image](https://user-images.githubusercontent.com/9299757/95658566-639fb200-0ae9-11eb-80f9-f604b62fc9a1.png)

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**
[logDataStoreInitialization.txt](https://github.com/aws-amplify/amplify-js/files/5359241/logDataStoreInitialization.txt)

**Comment by EliasCoelho** [comment]
The Issue was resolved with the following steps:

* Run amplify update api
* Disable DataStore for entire API
* Run amplify push
* Run amplify update api
* Enable DataStore for entire API
* Run amplify push

**Comment by brienpafford** [comment]
> The Issue was resolved with the following steps:
> 
> * Run amplify update api
> * Disable DataStore for entire API
> * Run amplify push
> * Run amplify update api
> * Enable DataStore for entire API
> * Run amplify push

This works. You are a gentleman and a scholar!
