### ISSUE TITLE
DataStore not provide a validate model method

### ISSUE THREAD

**Issue by EliasCoelho** [aws-amplify/amplify-js#6950]
**Is your feature request related to a problem? Please describe.**
When you use DataStore you must Save data models using the DataStore.Save() method, but it first create or update the object 
 model locally and following it be created in cloud, but DataStore library not provided a usefull method for validate the model, dataType and foreign key connecctions is correctly. This use can raise an exception error when it not be created in the cloud and operation was sucessfully locally. 

**Describe the solution you'd like**
aws-amplify/DataStore core library can provide a method model.ValidateModel() : bool returning a boolean type that response if the object is valid or not.

**Describe alternatives you've considered**
A event raised using a Hub.listen('datastore', callback) that provide a exception type with event and data [Model] or Model Type and ID for use it with custom logic by developer

**Comment by undefobj** [comment]
@EliasCoelho can you give a bit more detail on what type of validation you are looking for, perhaps with a sample schema? DataStore should do all validation for you and the goal is to not offload this responsibility to the developer. However perhaps there are some coverage gaps we're not aware of that you're looking at in terms of relational models?

cc @iartemiev

**Comment by EliasCoelho** [comment]
@undefobj @iartemiev when DataStore save a new model or update it, it must be a pre validation locally for void exception when it can not be created by restriction's db cloud.

* schema.graphql   
type Order @model
  @key(
    name: "byConsumerByStatus"
    fields: ["consumerId", "status"]
    queryField: "OrdersByConsumersByStatus"
  )
  @key(
    name: "byConsumerByDate"
    fields: ["consumerId", "date"]
    queryField: "OrdersByConsumersByDate"
  ) {
  id: ID!
  supplierId: ID!
  consumerId: ID!
  consumerIdERP: String
  orderCode: String
  date: String #just the date
  deliveryOn: String
  deliveryExpectedOn: String
  requestComment: String #comentario indicado por el consumer
  orderComments: String #comentario indicado por el supplier
  shipping: ShippingType
  status: OrderStatus
  grossAmount: Float
  discountAmount: Float
  taxAmount: Float
  netAmount: Float
  orderProducts: [OrderProduct] @connection(keyName: "OrderProductsByDetail", fields: ["id"])
}

type OrderProduct @model @key(name: "OrderProductsByDetail", fields: ["orderId"]) {
  id: ID!
  orderId: ID! 
  productId: ID! 
  unitId: String!
  price: Float
  quantity: Int
  grossAmount: Float
  discountAmount: Float
  taxAmount: Float
  netAmount: Float
}

* Code for insert data using DataStore
SetNewOrder = async () => {
        let ord = await DataStore.save(new db.Order({ 
            consumerId: '123',
            supplierId: '1234',
            consumerIdERP: '1508141324',
            date: XSalesConsumer.getDateFormatter(new Date()),
            deliveryExpectedOn: XSalesConsumer.getDateFormatter(new Date()),
            deliveryOn: XSalesConsumer.getDateFormatter(new Date()),
            discountAmount: 0,
            grossAmount: 0,
            netAmount: 0,
            orderComments: '',
            requestComment: '',
            orderCode: '123',
            shipping: db.ShippingType.DELIVERY,
            status: db.OrderStatus.CREATING,
            taxAmount: 0
        }))

        let orderProducts = []
        let op1 = await DataStore.save(new db.OrderProduct({
            orderId: ord.id,
            productId: '1405',
            unitId: 'CA',
            discountAmount: 0,
            grossAmount: 0,
            netAmount: 0,
            price: 14,
            quantity: 2,
            taxAmount: 1,
        }))
        orderProducts.push(op1)
        let op2 = await DataStore.save(new db.OrderProduct({
            orderId: ord.id,
            productId: '1405',
            unitId: 'CJ',
            discountAmount: 0,
            grossAmount: 0,
            netAmount: 0,
            price: 14,
            quantity: 1,
            taxAmount: 2,
        }))
        orderProducts.push(op2)

        return await DataStore.save(db.Order.copyOf(ord, updated => {
            updated.orderProducts = orderProducts
            updated.status = db.OrderStatus.DRAFT
        })) 
    }


* Exception in console when it can not be created in db cloud
![image](https://user-images.githubusercontent.com/9299757/95847541-d6dc3a80-0d1a-11eb-8136-47a822788afb.png)

![image](https://user-images.githubusercontent.com/9299757/95847594-e9567400-0d1a-11eb-8e85-bf46fe3fde37.png)

**Comment by undefobj** [comment]
What do you mean by "void exception when it can not be created by restriction's db cloud" exactly?

The error message that you are seeing is a DynamoDB conditional check error. Are you trying to create an item where the primary key already exists? If so that's an expected return value as this isn't supported in DataStore at this time.

**Comment by iartemiev** [comment]
@EliasCoelho please see [this example](https://docs.amplify.aws/lib/datastore/relational/q/platform/js#saving-relations) in the docs for saving One-to-Many relations. 

Just saving the `orderId` when creating `OrderProduct` items is enough to establish the relationship. You shouldn't attempt to save an array of `OrderProduct` items inside of an `Order` item.

For example:

```js
let ord = await DataStore.save(
  new db.Order({
    consumerId: '123',
    supplierId: '1234',
    consumerIdERP: '1508141324',
    date: XSalesConsumer.getDateFormatter(new Date()),
    deliveryExpectedOn: XSalesConsumer.getDateFormatter(new Date()),
    deliveryOn: XSalesConsumer.getDateFormatter(new Date()),
    discountAmount: 0,
    grossAmount: 0,
    netAmount: 0,
    orderComments: '',
    requestComment: '',
    orderCode: '123',
    shipping: db.ShippingType.DELIVERY,
    status: db.OrderStatus.CREATING,
    taxAmount: 0,
  })
);

let op1 = await DataStore.save(
  new db.OrderProduct({
    orderId: ord.id,
    productId: '1405',
    unitId: 'CA',
    discountAmount: 0,
    grossAmount: 0,
    netAmount: 0,
    price: 14,
    quantity: 2,
    taxAmount: 1,
  })
);

let op2 = await DataStore.save(
  new db.OrderProduct({
    orderId: ord.id,
    productId: '1405',
    unitId: 'CJ',
    discountAmount: 0,
    grossAmount: 0,
    netAmount: 0,
    price: 14,
    quantity: 1,
    taxAmount: 2,
  })
);

return await DataStore.save(
  db.Order.copyOf(ord, (updated) => {
    updated.status = db.OrderStatus.DRAFT;
  })
);

```

**Comment by EliasCoelho** [comment]
> What do you mean by "void exception when it can not be created by restriction's db cloud" exactly?
  I refer to this warning raised in console with the db cloud conditional check. This warning must not be raised after creatiation at DataStore locally.. If I have  a Model.ValidateModel() method, this warning can be catch before create it in DataStore.
  
> The error message that you are seeing is a DynamoDB conditional check error. Are you trying to create an item where the primary key already exists? If so that's an expected return value as this isn't supported in DataStore at this time.
No, I really create a Model with mock data and this values not corresponding with the PK in tables, it not be created yet.

@undefobj

**Comment by EliasCoelho** [comment]
@iartemiev thanks for the reference...

**Comment by amhinson** [comment]
Closing for now, as @iartemiev's suggested solution seems to work. However, feel free to reopen if you're still having problems on this particular issue.
