### ISSUE TITLE
Incorrect TypeScript types for generated one-to-many models and DataStore SubscriptionMessage

### ISSUE THREAD

**Issue by shanecav** [aws-amplify/amplify-js#6951]
**Describe the bug**
The TypeScript types generated by `amplify codegen models` for a schema with one-to-many models don't seem to be correct.

**CodeSandbox Example**

https://codesandbox.io/s/amplify-datastore-type-errors-6fwwo?file=/src/App.tsx

1. Saving a new `Post` (App.tsx line 100) doesn't work as expected when passing a `blogID` (maybe this is by design, but it was surprising to me)
2. Attempting to access `post.blogID` (App.tsx line 131) shows a TypeScript error even though it's part of the schema
3. Attempting to access `msg.element.blogID` (App.tsx line 148) shows a TypeScript error, even though it's part of the schema **and** it really is a property on the object (which you can see in the `console.log`)

1 and 2 may just be me misunderstanding how the library works, although I would expect `blogID` to be accessible since it is part of the schema.

3 seems to be a real problem, since the `blogID` property TypeScript is complaining about really is in the object, and the `blog` property TypeScript thinks should be there is _not_ in the object.

**Description of the problem**

Given the following schema:

```graphql
type Blog @model {
  id: ID!
  name: String!
  posts: [Post] @connection(keyName: "byBlog", fields: ["id"])
}

type Post @model @key(name: "byBlog", fields: ["blogID"]) {
  id: ID!
  title: String!
  blogID: ID!
  blog: Blog @connection(fields: ["blogID"])
}
```

I'd expect both of the following to not cause TypeScript errors:

#### 1:
```typescript
// I'd expect to be able to specify `blogID` as a string when creating a new `Post`.
new Post({ title: "Some title", blogID: "a-blog-uuid" });
//                              ^^^^^^^^^^^^^^^^^^^^^
// This results in the TypeScript error:
// "Object literal may only specify known properties, but 'blogID' does not exist in
// type 'Pick<Post, "blog" | "title" | "comments">'. Did you mean to write 'blog'?"
```

#### 2:
```typescript
const subscription = DataStore.observe(Post).subscribe((msg) => {
  console.log("post change", msg);
  if (msg.element.blogID === blog.id) {
    //            ^^^^^^
    // This results in the TypeScript error: "Property 'blogID' does not exist on type 'Post'. Did you mean 'blog'?"
    //
    // But when I log `msg` to the console, the `blogID` property _is_ there, and `blog` _is not_ there.
  }
});
```

**Both of the above examples _do_ work if I remove the `blog: Blog @connection(fields: ["blogID"])` line from the `Post` schema.** The presence of the `blog` connection on the `Post` model seems to remove the `blogID` property from the type definition, which I don't understand.

And the `SubscriptionMessage<Post>["element"]` type definition is incorrect, because the `element` doesn't actually match the `Post` type: it contains `blogID` but not `blog`.

**Screenshots**
n/a

**What is Configured?**
(Not related to this issue)

**Additional context**
```
// package.json dependencies:
"@aws-amplify/datastore": "2.5.1"
"aws-amplify": "3.2.0"

// amplify CLI version:
@aws-amplify/cli@4.29.2
```

**Comment by iartemiev** [comment]
Hey @shanecav sorry, I had misread the issue when I transferred it. 

I think a less confusing approach would be following [this example in the docs](https://docs.amplify.aws/lib/datastore/relational/q/platform/js#updated-schema). I.e., not using a `@connection` directive in your `Post` model, but just saving and accessing by `blogID`. That should resolve the TypeScript errors you're seeing.
