### ISSUE TITLE
Missing NOTICE

### ISSUE THREAD

**Issue by ajorg-aws** [aws-amplify/amplify-js#6952]
This project should have a NOTICE file including an Amazon copyright notice. Please correct this issue.

**Comment by sammartinez** [comment]
Thanks for bringing this to our attention @ajorg-aws, we will get this done.

**Comment by sammartinez** [comment]
Added missing file, https://github.com/aws-amplify/amplify-js/blob/main/NOTICE will resolve once this hits our `unstable` branch

**Comment by sammartinez** [comment]
Resolving as the changes have been deployed to our `unstable` branch and will go out this week's release
