### ISSUE TITLE
hideForgotPassword no longer possible after upgrade

### ISSUE THREAD

**Issue by andidev** [aws-amplify/amplify-js#6959]
hideSignUp works but hideForgotPassword does not. This used to be possible in "aws-amplify-react".

```jsx
<AmplifySignIn
    slot="sign-in"
    hideSignUp
    hideForgotPassword
/>
```

**Comment by andidev** [comment]
Ok maybe not that obvioys but it looks like it is possible to hide by setting hint on the password formField to blank like this:
```jsx
<AmplifySignIn
    slot="sign-in"
    formFields={[
        { type: "username" },
        { type: "password", hint: '' }
    ]}
    hideSignUp
/>
```

hence closing this.

**Comment by sscotth** [comment]
I reproduced, but the `formFields` hack worked. Thanks @andidev
