### ISSUE TITLE
customMessage lambda not getting clientMetata from updateUserAttributes()

### ISSUE THREAD

**Issue by toschlog** [aws-amplify/amplify-js#6961]
**Describe the bug**
When I call updateUserAttributes() I'm passing in some metadata.  As I understand it, that metadata should be passed to the customMessage lamda.  But it is not.

**To Reproduce**

I call:
```
  Auth.updateUserAttributes(user, {
      email: email,
    }, {
      "language": "en"
    })
```

In my lambda, I look at event.request and there's no clientMetadata field.

But here's the crazy thing:  One time (out of perhaps 20 tries), the metadata was there.  Could it be a timing thing and I got lucky once?

**What is Configured?**
Here's my config:

```
export const cognitoConfigStaging = {
  Auth: {
    region: "us-east-2",
    userPoolId: "us-east-2_XXXX",
    userPoolWebClientId: "XXXX",
    identityPoolId: "us-east-2:XXXX",
  },
}

```

<details>
  <summary><strong>Environment</strong></summary>

```
  System:
    OS: Windows 10 10.0.18363
    CPU: (16) x64 Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz
    Memory: 12.40 GB / 31.93 GB
  Binaries:
    Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.7 - D:\Projects\Hearo.Live\stadium-web\node_modules\.bin\npm.CMD
  Browsers:
    Chrome: 85.0.4183.121
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    @material-ui/core: ^4.10.2 => 4.10.2
    @material-ui/icons: ^4.9.1 => 4.9.1
    aws-amplify: ^2.3.0 => 2.3.0
    aws-amplify-react: ^2.6.3 => 2.6.3
    aws-sdk: ^2.699.0 => 2.699.0
    axios: ^0.19.2 => 0.19.2
    babel-plugin-preval: ^3.0.1 => 3.0.1
    electron: https://github.com/castlabs/electron-releases#v9.1.1-wvvmp => 9.1.1-wvvmp
    electron-builder: ^22.7.0 => 22.7.0
    electron-differential-updater: ^4.3.2 => 4.3.2
    electron-is-dev: ^1.2.0 => 1.2.0
    electron-log: ^4.2.2 => 4.2.2
    electron-notarize: ^1.0.0 => 1.0.0
    electron-store: ^5.2.0 => 5.2.0
    firebase: ^7.15.1 => 7.15.1
    hls.js: ^0.14.9 => 0.14.9
    js-yaml: ^3.14.0 => 3.14.0
    lodash: ^4.17.20 => 4.17.20
    npm: ^6.14.7 => 6.14.7
    platform: ^1.3.6 => 1.3.6
    react: ^16.13.1 => 16.13.1
    react-addons-css-transition-group: ^15.6.2 => 15.6.2
    react-cookie-consent: ^3.0.0 => 3.0.0
    react-dom: ^16.13.1 => 16.13.1
    react-full-screen: ^0.2.4 => 0.2.4
    react-player: ^2.3.1 => 2.3.1
    react-scripts: ^3.4.3 => 3.4.3
    react-slick: ^0.26.1 => 0.26.1
    react-tooltip: ^4.2.7 => 4.2.7
    serve: ^11.3.2 => 11.3.2
    shaka-player: ^3.0.2 => 3.0.2
    simplebar: ^5.2.0 => 5.2.0
    simplebar-react: ^2.2.0 => 2.2.0
    slick-carousel: ^1.8.1 => 1.8.1
    source-map-explorer: ^2.4.2 => 2.4.2
    typescript: ^3.7.5 => 3.7.5
    url-join: ^4.0.0 => 4.0.1
  npmGlobalPackages:
    npm: 6.14.5
```
</details>

**Comment by amhinson** [comment]
Based on the client-side code and referencing the Cognito API docs, it looks like we are correctly passing the `clientMetadata` down to when the service call is actually made. Would you be able to reach out to AWS support for Cognito to see if they have any other ideas here?


https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/Auth.ts#L1055
https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/src/CognitoUser.js#L1120

Also, take a look at the note for `ClientMetadata` in the docs to see if there are any other considerations needed here:
https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateUserAttributes.html

**Comment by toschlog** [comment]
I posted an issue in the Cognito forum: https://forums.aws.amazon.com/thread.jspa?threadID=330325

Thanks for your help!

**Comment by sammartinez** [comment]
@toschlog As this is related to Amazon Cognito and not Amplify specifically, we are going to close this issue. Thanks!
