### ISSUE TITLE
react-native 0.63.3 Auth.signIn method returns TypeError: undefined is not an object (evaluating 'challengeParameters.USER_ID_FOR_SRP')]

### ISSUE THREAD

**Issue by GlebKozenko** [aws-amplify/amplify-js#6967]
After upgrading react-native to version 0.63.3 and aws-amplify to 3.3.3 `Auth.signIn` method returns `TypeError: undefined is not an object (evaluating 'challengeParameters.USER_ID_FOR_SRP')]`

I've tried to set up new User and Identity Pools, but no luck as well.

I've debugged down the line and seems like `amazon-cognito-identity-js` is where an issue comes from.

To be more specific `this.client.request('InitiateAuth', jsonReq, (err, data) => {` that line produces empty response. I'm wonedring if it's an issue related to networking bug caused by latest flipper integration or so..

**Comment by sammartinez** [comment]
@GlebKozenko Thanks for reporting this. Can you provide your `package.json` along with your environment settings? 

Please use the follow command: 
```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

Also, do you have a link to the networking bug you are calling out for Flipper? 

Thanks ahead of time!
