### ISSUE TITLE
Incomplete types for Amazon Auth

### ISSUE THREAD

**Issue by rabbitXIII** [aws-amplify/amplify-js#6974]
```
Property 'challengeName' does not exist on type 'CognitoUser'.
```

As has been reported many times in the past (e.g. [#3733](
https://github.com/aws-amplify/amplify-js/issues/3733)), the type definitions exported by the `amazon-cognito-identity-js` package are missing critical fields.  The previous threads have gone stale, lacking a response from aws, so I'm filing a new bug to report the issue still exists.  This is a terrible customer experience, and requires brittle solutions by every typescript user of the amplify sdk.

Users are currently required to define custom types (see [comment ](https://github.com/aws-amplify/amplify-js/issues/3733#issuecomment-533817764)in previous thread) adding fields to exported `CognitoUser`.

The types available on interface functions are also very loosely typed, as seen in, but not limited to, the examples below from `aws-amplify@3.3.3`

```
	export interface IAuthenticationCallback {
		onSuccess: (
			session: CognitoUserSession,
			userConfirmationNecessary?: boolean
		) => void;
		onFailure: (err: any) => void;
		newPasswordRequired?: (
			userAttributes: any,
			requiredAttributes: any
		) => void;
		mfaRequired?: (challengeName: any, challengeParameters: any) => void;
		totpRequired?: (challengeName: any, challengeParameters: any) => void;
		customChallenge?: (challengeParameters: any) => void;
		mfaSetup?: (challengeName: any, challengeParameters: any) => void;
		selectMFAType?: (challengeName: any, challengeParameters: any) => void;
	}
```
or
```
export interface MfaRequiredDetails {
	challengeName: any;
	challengeParameters: any;
}
```
source: [packages/auth/src/types/Auth.ts](https://github.com/aws-amplify/amplify-js/blob/2f74c6b74d38af570017139f2ba8269dc1009135/packages/auth/src/types/Auth.ts#L106-L109)
Marking this as a bug, since the feature (typedefs) exist, but are woefully missing or unmaintained.

**Comment by sammartinez** [comment]
Thank you for this feedback, I have marked this as a feature request for future support of TypeScript into our package.

**Comment by abdallahshaban557** [comment]
This issue was resolved thanks to @micksatana !
