### ISSUE TITLE
DataStore predicates without Predicates.ALL specified usage question

### ISSUE THREAD

**Issue by myfairshare** [aws-amplify/amplify-js#6980]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
DataStore

**Amplify CLI Version** 

4.29.6

**What AWS Services are you utilizing?**
Amplify, DataStore

**Provide additional details e.g. code snippets**
I'm wondering if its possible to use pagination when not using predicates.all on a set of data.
Below works fine..

`const messages = await DataStore.query(Message, Predicates.ALL, {
  page: 0,
  limit: 100
});`

But what about if I want to limit the following filtered results..

`const messages = await DataStore.query(Message, (m) =>
        m.msgConvID('eq', conversationId)
      )`

Is it possible to paginate these filtered results without using a slice on front end, thank you!

**Comment by renebrandel** [comment]
transferring this to JS repo. cc @sammartinez

**Comment by myfairshare** [comment]
Why does it matter, I'm just following the Amplify DataStore documentation here..

[https://docs.amplify.aws/lib/datastore/data-access/q/platform/js#predicates](url)

I would just like to know if I can limit the results of a query, thanks.

**Comment by manueliglesias** [comment]
Hi @myfairshare 

> Is it possible to paginate these filtered results without using a slice on front end, thank you!

Yeah, you can do:

```typescript
const messages = await DataStore.query(Message, (m) => m.msgConvID('eq', conversationId), { page: 0, limit: 100 } )
```

**Comment by sammartinez** [comment]
Resolving issue as the above callout, apologizes from early @myfairshare as I read the question to fast !

**Comment by myfairshare** [comment]
Brilliant, thanks guys, worked a charm!
