### ISSUE TITLE
DataStore - Sync error  - UnauthorizedException

### ISSUE THREAD

**Issue by rpostulart** [aws-amplify/amplify-js#6982]
I receive this error:
`DataStore - Sync error – "subscription failed Connection failed: {\"errors\":[{\"errorType\":\"UnauthorizedException\",\"message\":\"Permission denied\"}]}"`

While I run this code:

`Auth.currentCredentials()
      .then(d => console.log("data: ", d))
      .catch(e => console.log("error: ", e));`

before 

`this.init = DataStore.observe(Quiz).subscribe();`

with this schema:

```graphql
type Quiz
  @model
  @auth(
    rules: [
      { allow: public, provider: iam, operations: [read] }
      { allow: owner }
    ]
  ) {
  id: ID!
  title: String!
  seconds: Int!
  currentQuestion: String
  questionOrder: String
  started: Boolean
  questionTime: Int
  view: Int
  owner: String!
}

type Questions
  @model
  @auth(
    rules: [
      { allow: public, provider: iam, operations: [read] }
      { allow: owner }
    ]
  ) {
  id: ID!
  image: String
  youtube: String
  question: String!
  answerOne: String
  answerOneCorrect: Boolean
  answerTwo: String
  answerTwoCorrect: Boolean
  answerThree: String
  answerThreeCorrect: Boolean
  answerFour: String
  answerFourCorrect: Boolean
  quizID: String!
  order: Int
  public: Boolean
  fromLibrary: Boolean
  category: String
}
type QuestionsDB
  @model
  @auth(
    rules: [
      { allow: public, provider: iam, operations: [read] }
      { allow: owner }
    ]
  ) {
  id: ID!
  image: String
  youtube: String
  question: String!
  answerOne: String
  answerOneCorrect: Boolean
  answerTwo: String
  answerTwoCorrect: Boolean
  answerThree: String
  answerThreeCorrect: Boolean
  answerFour: String
  answerFourCorrect: Boolean
  relatedQuestion: String!
  public: Boolean
  category: String
  language: String
}

type Subscribers @model @auth(rules: [{ allow: public, provider: iam }]) {
  id: ID!
  type: String!
  score: Int!
  quizID: String!
  name: String!
}

type Responses @model @auth(rules: [{ allow: public, provider: iam }]) {
  id: ID!
  quiz: String!
  subscriber: String!
  question: String!
}
type Languages
  @model
  @auth(rules: [{ allow: public, provider: iam }])
  @key(name: "ByCode", fields: ["type", "code"], queryField: "getLangByCode") {
  id: ID!
  type: String!
  code: String!
}
```

**Comment by ltaljaard** [comment]
@SwaySway fyi I created a new app and backend and copied the same code over from old app to new app and now i don't get this error anymore. Not sure whether it is a package version thing or something that changed on the cloud/backend side but the latest DataStore does seem to work with the latest cloud formation stuff again.

That said i am only using public for now: @auth(rules: [{ allow: public }])

But even the allow:public gave me this error before i redid the app.

**Comment by ltaljaard** [comment]
This issue has started up again in my Expo Web app. It happens both from the browser and the mobile app. It does not help to sign out and sign back in once it starts happening. The first few days everything works and syncs fine but then it stops with this UnauthorizedException and the syncing stops working.

I'm using the standard suggested project setup and configuration as per the docs: [https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js#option-1-platform-integration](url)

My package versions:
    "@react-native-community/netinfo": "^5.9.7",
    "aws-amplify": "^3.3.3",
    "aws-amplify-react-native": "^4.2.7",
    "expo": "~39.0.2",
    "react": "16.13.1",
    "react-native-web": "^0.11.7",


Here is the full log that i get when setting `Amplify.Logger.LOG_LEVEL = 'DEBUG'`: [https://github.com/ltaljaard/amplify-datastore-log/blob/main/debug-logger.txt](url)
