### ISSUE TITLE
Federated Sign In Does Not Return an Access Token

### ISSUE THREAD

**Issue by MysteryMachine** [aws-amplify/amplify-js#699]
When I do a federated sign in, I get back a CognitoIdentityCredentials object that contains an a sessionToken, but no accessToken. I need this accessToken to validate users in some services. When doing a non-federated sign in, I get this authToken.

In general, I would love to be pointed to good documentation about how federated sign-in works. I can sign in with Google just fine, but I do not see anything corresponding to that user in my userpool. I see a group that has been autogenerated for people signing in through google, but I don't see any users assigned to that group, despite my successful login.

I was under the impression that doing this federated login would provide me a CUP token I could use to do validation everywhere. The session token does not seem to be that, it's definitely not a JWT or anything.

Is there a specific thing I need to do in my userpool to start getting users to properly exist in the pool and start getting an authentication token?

**Comment by MysteryMachine** [comment]
I do see issue #402 where you mentioned doing

```
token = credentials.webIdentityCredentials.params.Logins['accounts.google.com'];
```

But this doesn't actually solve the issue. This is the token issued by Google, not a token issued by Cognito. It means my backend validates users by checking google, instead of Cognito. If I'm doing that, Cognito is largely an unneeded middleman in the process. 

In 

https://www.youtube.com/watch?v=KWjgiNgDfwI&t=1122s

At around 20 minutes a "CUP" is mentioned as a single token you can use to authenticate on Cognito from many identity providers.

**Comment by kyeljmd** [comment]
I would like to know this as well. I am having the same problem as well. I need the token issued by Cognito after performing a federated login

**Comment by guanzo** [comment]
@mlabieniec 

My app is using Cognito User Pools for authentication at the moment. I'm securing my own API with the idToken. You say that Cognito Federated Identities do not work with JWT Tokens. If i was to add authentication via Federated Identities (Google, Facebook, etc), how would I secure my API against users who don't sign in through User Pools, and therefore don't have an idToken JWT?

**Comment by okarlsson** [comment]
@MysteryMachine @guanzo 

I've been experimenting with this the last couple of days, with the same use case. I want to handle the authentication and federation through Amplify, get an access token and send it to my backend as an Authorization header and validate it against the userpool.

You get the feeling while reading the documentation that you can just select sign in with federated identities or with a custom userpool and be on your way. But you quickly get the feeling that these are entire different authentication flows. Everything except using the Hosted UI seems like a no go.

The naming of things are also really confusing, for example there are these methods:
`Auth.currentSession();`
`Auth.currentAuthenticatedUser();`
`Auth.currentCredentials();`
`Auth.currentUserCredentials();`
`Auth.currentUserInfo();`
`Auth.currentUserPoolUser();`

Where currentSession() returns credentials for user pool users but with federated sign in throws an error with "No current user". And  currentCredentials() returns an entire different set of credentials.

**Comment by kavyasoni** [comment]
Did anyone find a fix for this? We are facing an exact issue in our project. Its a roadblock for us.

**Comment by laurentbourg** [comment]
I am also trying to pass JWT tokens when using a federated sign-in on iOS with AWSMobileClient, if anybody has a solution, please share.

**Comment by suzannechang** [comment]
Same problem here

**Comment by waqas-syed** [comment]
So there is still no resolution to this? The docs now mention how to get the JWT tokens after federated sign-in: https://aws-amplify.github.io/docs/js/authentication#retrieve-jwt-tokens

But it always returns null! Any help???

**Comment by MohsinGhani** [comment]
facing same issue.

**Comment by miguel258** [comment]
The same history for me...., its incredible, i think so this is simple thing.....

**Comment by mobee-bill** [comment]
I have been working with Apple Sign in.  The only way I have been able to get the identityToken or any for that matter is through the Hosted UI.  When doing a federated sign in I am unable to get any tokens back.  It appears my users may end up stuck with a hosted UI.

**Comment by teamzz111** [comment]
Same problem here...

**Comment by elorzafe** [comment]
How to get Cognito Tokens when Authenticating with Social Providers

1. You need to Setup your Auth Provider with Cognito User Pools. More info [here](https://docs.amplify.aws/lib/auth/social/q/platform/js#setup-your-auth-provider)
2. On your App you have to call Auth.federatedSignIn in this way
    1. `Auth.federatedSignIn()` this will open Cognito Hosted UI Web App.
    2. In case you want to skip Cognito Hosted UI you can invoke from your App
        1. `Auth.federatedSignIn({provider: 'Facebook'})`
        2. `Auth.federatedSignIn({provider: 'Google'})`
        3. `Auth.federatedSignIn({provider: 'LoginWithAmazon'})`
        4. `Auth.federatedSignIn({provider: 'SignInWithApple'})`

Then you will have a user on your userpool and Cognito tokens on your App.

Note
If you get a token from your Authentication Provider and then use

```javascript
Auth.federatedSignIn(
    domain,
    {
        token,
        identity_id, // Optional
        expires_at: expiresIn * 1000 + new Date().getTime() // the expiration timestamp
    },
    user
)
```
You wont be able to get a Cognito Tokens and you will get **No current user** error.

**Comment by danielgeri** [comment]
@elorzafe any chance you've been able to find a workaround for the `No current user` error if getting the token from the Authentication Provider (i.e. the method you have under `Note`)?
