### ISSUE TITLE
React: AWS Cognito token endpoint returns 400 invalid_grant when being redirected from another site

### ISSUE THREAD

**Issue by pavinduLakshan** [aws-amplify/amplify-js#6991]
**Describe the bug**
Our React app uses AWS Amplify and Cognito hosted UI for authentication. There is a feature in our app to link a Shopify store. To do that, we get the user's Shopify store URL and redirect the user to its admin panel to obtain permissions and access token. After the user grants permission, he is redirected again to our app.

The problem occurs at this point. When looking at the console, we see something like this.  
![invalid_grant](https://user-images.githubusercontent.com/41533942/96817329-bc057680-143c-11eb-9afb-3fd9a190b2f7.PNG)

Cognito token endpoint throws 400 invalid_grant error. This error goes away when we refresh the page, but we think there should be a better solution.

**To Reproduce**

Try to redirect from another site to a page of amplify-powered React app and open the console to see errors

**Expected behavior**
No `invalid_grant` errors should appear on the console.

**Code Snippet**
I have posted a question on Stackoverflow regarding this issue.   
https://stackoverflow.com/questions/64402488/react-aws-cognito-token-endpoint-returns-400-invalid-grant-when-being-redirecte

**Screenshots**
https://i.stack.imgur.com/vOoVp.png

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.
* Which resources do you have configured?
  * If applicable, please provide your `aws-exports` file:
   ```
   const awsmobile = {
       "aws_project_region": "us-east-1",
       "aws_cognito_identity_pool_id": "us-east-1:b94ff9e9-e7f0-4e3a-a4e9-42abb9d1423b",
       "aws_cognito_region": "us-east-1",
       "aws_user_pools_id": "us-east-1_v5WFEv3z5",
       "aws_user_pools_web_client_id": "4a4s1bfj9fdth6ea52c25fotsq",
       "oauth": {
          "domain": "ogmo-topic.auth.eu-central-1.amazoncognito.com",
            "scope": [
               "phone",
               "email",
               "openid",
               "profile",
               "aws.cognito.signin.user.admin"
            ],
       },
      "redirectSignIn": "https://topic.ogmo.xyz/",
           "redirectSignOut": "https://topic.ogmo.xyz/",
           "responseType": "code"
   };
   ```
   * If applicable, please provide your manual configuration example:
   ```
   {
    Auth: {
        identityPoolId: 'XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab',
        region: 'XX-XXXX-X',
        identityPoolRegion: 'XX-XXXX-X',
        userPoolId: 'XX-XXXX-X_abcd1234',
        userPoolWebClientId: 'a1b2c3d4e5f6g7h8i9j0k1l2m3',
        mandatorySignIn: false,
        authenticationFlowType: 'USER_PASSWORD_AUTH',
        }
       }
   }
   ```
* If applicable, provide more configuration data, for example for Amazon Cognito, run `aws cognito-idp describe-user-pool --user-pool-id us-west-2_xxxxxx` (Be sure to remove any sensitive data)
 

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

</details>

**Smartphone (please complete the following information):**

**Additional context**

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by mauerbac** [comment]
@ericclemmons / @wlee221 - please triage this and remove the label

**Comment by ericclemmons** [comment]
> To do that, we get the user's Shopify store URL and redirect the user to its admin panel to obtain permissions and access token. After the user grants permission, he is redirected again to our app.
> The problem occurs at this point. When looking at the console, we see something like this.

We'd need to understand this flow better. Do you have a video of it as well?

I was able to Sign in with Google on https://topic.ogmo.xyz/ successfully, but of course this isn't the exact flow you describe.

> ** redirect the user to its admin panel to obtain permissions and access token. **

What URL is this?  

> ** After the user grants permission, he is redirected again to our app. **

Redirect back to what URL, exactly? 

Because, if Shopify is _also sending a `?code`_ to that page, that would explain why Amplify thinks it's a Cognito authentication code.

Is that what's going on?

**Comment by chrisbonifacio** [comment]
@pavinduLakshan Closing this for now as we have not heard back from you. Please re-open if you are still experiencing the issue and need assistance.
