### ISSUE TITLE
Error  :  GraphQLError {message: "Network Error", locations: undefined

### ISSUE THREAD

**Issue by jpca999** [aws-amplify/amplify-js#6992]
I'm very new to this library. 

when i try to retrieve the data from backend ( Aws ) it gives me this error. 

![image](https://user-images.githubusercontent.com/1026325/96353668-2d32db80-1083-11eb-970f-cf3e85204f29.png)

on mac Catalina

**Comment by amhinson** [comment]
@jpca999 Could you provide some more details for this issue you are seeing? These would be helpful in order to debug:
- versions of Amplify libraries you are using
- code snippet or sample repo
