### ISSUE TITLE
"invalid_request" when performing token exchange for SAML federated auth

### ISSUE THREAD

**Issue by rajeshmishra189** [aws-amplify/amplify-js#6995]
Upon upgrading to @aws-amplify/auth 3.3.3, federated signin using SAML failed with an "invalid_grant" error being returned from the token endpoint.

**Steps to reproduce the behavior:**
Configure federated signin via OKTA to the hosted UI, follow the process and end up back at the application. When Amplify tries to obtain the token, invalid_request is returned.

**Expected behavior**
The user successfully logs in

**Code Snippet**
This happens out of the box.

**What is Configured?**
const awsconfig = {
    aws_project_region: 'ap-southeast-2',
    aws_cognito_region: 'ap-southeast-2',
    aws_user_pools_id: environment.UserPoolId,
    aws_user_pools_web_client_id: environment.ClientId,
    aws_appsync_region: 'ap-southeast-2',
    aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
    oauth: {
        domain: environment.AppWebDomain,
        scope: environment.TokenScopesArray,
        redirectSignIn: environment.RedirectUriSignIn,
        redirectSignOut: environment.RedirectUriSignOut,
        responseType: 'code',
        client_id: environment.ClientId
    }
}

**What is Configured?**
   * If applicable, please provide your manual configuration example:
   ```
   {
    Auth: {
        identityPoolId: 'XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab',
        region: 'XX-XXXX-X',
        identityPoolRegion: 'XX-XXXX-X',
        userPoolId: 'XX-XXXX-X_abcd1234',
        userPoolWebClientId: 'a1b2c3d4e5f6g7h8i9j0k1l2m3',
        mandatorySignIn: false,
        authenticationFlowType: 'USER_PASSWORD_AUTH',
        oauth: {
            domain: 'your_cognito_domain',
            scope: ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
            redirectSignIn: 'http://localhost:3000/',
            redirectSignOut: 'http://localhost:3000/',
            responseType: 'code' // or 'token', note that REFRESH token will only be generated when the responseType is code
           }
       }
   }
   ```
* If applicable, provide more configuration data, for example for Amazon Cognito, run `aws cognito-idp describe-user-pool --user-pool-id us-west-2_xxxxxx` (Be sure to remove any sensitive data)
 

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

</details>

**Smartphone (please complete the following information):**

- Browser [chrome]

**Additional context**

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by sammartinez** [comment]
@rajeshmishra189 Thanks for opening up this issue, for us to reproduce this we do need a few more things from you. 

Can you provide your `package.json` along with your environment settings? 

Please use the follow command: 
```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

Also, are you following a guide for setup of Okta? We do not provide any guides on Okta from Amplify JS so was curious if you can pass us the references you are looking at.

Thanks ahead of time!
