### ISSUE TITLE
Graphql library included even if you don't want to use graphql

### ISSUE THREAD

**Issue by shark404** [aws-amplify/amplify-js#701]
#### Do you want to request a feature or report a bug?
I guess you could say it's an optimisation feature request.

#### What is the current behavior?

Since v0.3.0 with the introduction of graphql in the API module the graphql library is forced upon users of the Amplify library even if you're not using the graphql functionality. This is a ~140kb library so the affect on a webapp bundle size is actually quite large.

#### What is the expected behavior?

Ideally the imports of graphql should be done in a way that webpack can remove them during treeshaking. I'm not sure the best approach here but happy to help on the implementation side of things if someone has some ideas on how to approach it.

**Comment by richardzcode** [comment]
Hi @shark404 this is a very valid request. Modularized Amplify is in our plan. We are exploring approaches right now, not just graphql but also all categories.

**Comment by manueliglesias** [comment]
Hi @ishtiaque23 

As a quick workaround you can try depending on the same aws-sdk version that the aws-amplify version is using, that would be aws-sdk@2.198.0

https://github.com/aws/aws-amplify/blob/aws-amplify%400.2.14/packages/aws-amplify/package.json#L61

**Comment by jordanranz** [comment]
Modular imports for Amplify has been implemented as part of v1.0. See docs here:
https://aws-amplify.github.io/amplify-js/media/api_guide#using-modularized-module

Going to close this issue as the release of modular Amplify seems to solve the issue here. Please reopen if there are any more related questions or concerns.

**Comment by mordka** [comment]
Module imports doesn't resolve this. graphl is a direct dependency on `@aws-amplify/api`
https://github.com/aws-amplify/amplify-js/blob/master/packages/api/package.json#L58

**Comment by nihakue** [comment]
See
https://github.com/aws-amplify/amplify-js/issues/488#issuecomment-420100364

**Comment by nihakue** [comment]
See
https://github.com/aws-amplify/amplify-js/issues/488#issuecomment-420100364
