### ISSUE TITLE
Federated refresh token

### ISSUE THREAD

**Issue by mezalejandro** [aws-amplify/amplify-js#7015]
**Describe the bug**
Hello,
I have a problem with the tokens being logged in with facebook, google or by username and password.
With facebook I have this message: **refreshing federation token failed: no fb sdk available**

With google I have this message: **refreshing federation token failed: no gapi auth2 available**

And with cognito: **Invalid login token. Token is expired.**

How can i fix this?
I am using react-native.
Thanks

**Comment by amhinson** [comment]
Could you share more info about the issue you're seeing:
- Amplify config
- packages & versions
- code snippets
- sample repo (we prefer this over code snippets because it allows us to attempt reproduce the issue immediately, which ultimately can resolve your issue quicker)

**Comment by amhinson** [comment]
A few observations:
- You are currently on an older version of the library, which could lead to issues. Can you update to the latest for both libraries?
- Can you share more code related to how you're setting up the FB & Google SDKs in your app and how you're using them with Amplify Auth?

**Comment by mezalejandro** [comment]
Thanks @amhinson 
react-native-fbsdk: ^1.0.1
react-native-google-signin: ^2.0.0

Attached login code with google:
```
await GoogleSignin.configure({
        scopes: ['email','profile'], 
        webClientId: Platform.OS == 'ios' ? Config.googleIOSClientID : Config.googleWebClientID, 
        iosClientId: Config.googleIOSClientID,
        offlineAccess: false, 
        hostedDomain: '', 
        loginHint: '',
        forceConsentPrompt: true, 
      });
      try {
        const data = await GoogleSignin.signIn();
        let user = await Auth.federatedSignIn('google', { token: data.idToken, expires_at: null }, data)
        if(user) {
            return { success: true }
        }else{
            return { success: false, err: 'Login failed' }
        }
        
      } catch (error) {
        console.log('error ', error)
        return { success: false, err: error }
      }
```

Login with Facebook:
```
try {

        let { isCancelled } = await LoginManager.logInWithPermissions(['email'])
        if (!isCancelled) {
            let data = await FBAccessToken.getCurrentAccessToken()
            const { accessToken, expirationTime } = data
            const userData = await getFBGraphRequest() //get profile user fb
            const user = await Auth.federatedSignIn('facebook', { token: accessToken, expires_at: expirationTime }, userData)
            if(user) {
                return { success: true }
            }else{
                return { success: false, err: 'Login failed' }
            }
        } else {
            return { success: false, err: 'facebook canceled' }
        }
    } catch ( error ) {
        console.log('fb_ error ' , error)
        return { success: false, err: error.message}
    }
```

**Comment by amhinson** [comment]
Ok thanks! I think what is happening is that you will need to configure a [`refreshHandler`](https://docs.amplify.aws/lib/auth/advanced/q/platform/js#token-refresh) for Google and Facebook in order to refresh the tokens, since Amplify cannot do that automatically in React Native. Right now it looks like the library can only handle automatic token refresh in the browser (https://github.com/aws-amplify/amplify-js/blob/main/packages/core/src/OAuthHelper/GoogleOAuth.ts#L25).

I will also update the documentation to be more explicit about this.
