### ISSUE TITLE
amazon-cognito-identity-js : Cannot read property 'headers' of undefined

### ISSUE THREAD

**Issue by stripathix** [aws-amplify/amplify-js#702]
Do you want to request a feature or report a bug?
Report a bug

What is the current behavior?
This is an intermittent problem. While refreshing a session an error occured inside lib amazon-cognito-identit-js.

Error: 
`Cannot read property 'headers' of undefined`

I was trying to refresh session to make sure that access token do not expire. No respose was returned, netither error was returned. Only error was logged in console.

This occured during below execution:
`cognitoUser.refreshSession(refreshToken, function (err, refreshedSession) {});`

Callback never executed.

**Comment by Fefbug** [comment]
@stripathix you can use  amazon-cognito-identity-js  2.0.4 in npm beta (npm install  amazon-cognito-identity-js@2.0.4

@manueliglesias Hi Could you push a new version of amazon-cognito-identity-js ? 
aws-amplify still use the 2.0.3. Fix https://github.com/aws/aws-amplify/pull/706 and https://github.com/aws/aws-amplify/pull/605 has not been pushed

**Comment by boozedog** [comment]
@manueliglesias can you assist?

**Comment by boozedog** [comment]
@Fefbug do you know if there is anyone else who can help? @manueliglesias isn't responding

**Comment by jordanranz** [comment]
Hi, sorry about the delay here.

I see the fix was merged and aws-amplify is using the newest version of amazon-cognito-identity-js

Are any of you guys still experiencing issues?

**Comment by stripathix** [comment]
No looks good now. Not seen this bug in a long time. Thanks.

**Comment by jordanranz** [comment]
Going to close this issue. Please reopen if you are still experiencing related issues.
