### ISSUE TITLE
DataStore save with predicate explanation

### ISSUE THREAD

**Issue by myfairshare** [aws-amplify/amplify-js#7024]
**Which Category is your question related to?**
DataStore save with predicate

**Amplify CLI Version** 
4.29.3

**What AWS Services are you utilizing?**
Amplify, DataStore

**Provide additional details e.g. code snippets**
I'm having trouble understanding the code snippet below of the DataStore documenation under 'synching to the cloud' section.
Should I be doing similar every time I save new data?
What does the Amplify array represent in the predicate?

Thanks for any tips!

```
await DataStore.save(
  new Post({
    title: "My First Post",
    rating: 10,
    status: PostStatus.DRAFT
  }),
  (p) => p.title('beginsWith', '[Amplify]')
);
```

**Comment by iartemiev** [comment]
> Should I be doing similar every time I save new data?

No, you don't need to specify a predicate each time you perform a `save`. This is an option that allows you to perform a conditional update when you're expecting that the back end might be out of sync with the client.

> What does the Amplify array represent in the predicate?

It's just a string value. E.g., it would match a post containing: `{title: "[Amplify] - my post"}`
