### ISSUE TITLE
AWS Amplify SignUp SMS Verification Code not getting sent/delivered to some addresses

### ISSUE THREAD

**Issue by gvb26** [aws-amplify/amplify-js#7026]
**Describe the bug**
Upon signing up with a phone number, the Verification SMS with the 6 digit code is never sent to the phone number. After trying to resend the code multiple times, the message is never received.

The most troublesome part is that some phone numbers receive the SMS verification without fail but some never do.

**Steps to reproduce the behavior:**
SignUp using phone number
SMS not received.
Resend verification code.
No SMS received
Expected behavior
A SMS Verification code is sent to the phone number used during SignUp.

**Additional context**
I have already raised a Service Quota Increase ticket and have that increased. I have also explicitly set the spending limit on the SNS (Text Messaging) Console.

My SNS service is working as expected as I can send out other SMS communication to our users using the aws-sdk.

Also, if the user registers using the email address, an email is promptly sent to the user with the verification code. Only SMS are not delivered.

This seems to be a recurring issue with AWS users this past summer. I recommend the support team do something to rectify this issue since it seems to be such a glaring error

**Comment by gvb26** [comment]
**UPDATE** 

After doing a deep dive into the issue, the problem originates from some change in AWS that requires SNS users to request a long a dedicated long code (Phone number to send messages) in the AWS Pinpoint SMS Settings Dashboard. This, this along with increasing your spending limit will ensure that all SNS messages will now be received by your users. The cost of the long code is $1.

This isn't anywhere in the AWS documentation nor was there any transparency in regards to long codes being a requirement when this occurred over the summer. On top of that, when asking support for help they request you upgrade your support service for their faulty communication. Do better AWS. Closing this ticket.

**Comment by grousseva** [comment]
@gvb26 

hey! I'm currently facing the exact same problem you've described but I'm a bit stuck. Are you saying that I need to choose long code rather than toll-free in the settings? 

But this is a problem for me because when I select long code it only allows for voice, not sms

Thanks so much
