### ISSUE TITLE
getItem being called before setItem in authstorage after successful login

### ISSUE THREAD

**Issue by Rajan-Gupta1** [aws-amplify/amplify-js#7030]
**Describe the bug**
getItem being called before setItem in authstorage after successful login.

**To Reproduce**

1. AWS Exports has the following settings and 
const aws_configure = {
    Auth: {
        "region": "us-east-1",
        "userPoolId": "xxxxxxxxxxxxx",
        "userPoolWebClientId": "yyyyyyyyyy",
        **storage: AuthStorage**
    }
}
2. On debugging the Auth.js code I see that storage functions are correctly registered as from code below
AuthClass.prototype._isValidAuthStorage = function (obj) {
        // We need to check if the obj has the functions of Storage
        return (!!obj &&
            typeof obj.getItem === 'function' &&
            typeof obj.setItem === 'function' &&
            typeof obj.removeItem === 'function' &&
            typeof obj.clear === 'function');
    };
3. However setItem is not being called before getItem and setItem is actually never called when I played with it

**Expected behavior**
setItem must be called before getItem

**Code Snippet**
Provided above in steps

**Screenshots**
Not Applicable

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.
* Which resources do you have configured?
  * If applicable, please provide your `aws-exports` file:
   ```
   const aws_configure = {
    Auth: {
        "region": "us-east-1",
        "userPoolId": "xxxxxxxxxxxxx",
        "userPoolWebClientId": "yyyyyyyyyy",
        **storage: AuthStorage**
    }
}
   ```
   * If applicable, please provide your manual configuration example:
   ```
  
 

<details>
  <summary><strong>Environment</strong></summary>

<!-- Please run the following command inside your project and copy/paste the output into the codeblock: -->

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-3840QM CPU @ 2.80GHz
    Memory: 6.22 GB / 15.58 GB
  Binaries:
    Node: 12.18.4 - C:\Program Files\nodejs\node.EXE      
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.111
    Edge: Spartan (44.19041.423.0), Chromium (86.0.622.38)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @angular-devkit/build-angular: ~0.901.0 => 0.901.12
    @angular/animations: ~9.1.0 => 9.1.12
    @angular/cdk: ~9.2.0 => 9.2.4
    @angular/cli: ~9.1.0 => 9.1.12
    @angular/common: ~9.1.0 => 9.1.12
    @angular/compiler: ~9.1.0 => 9.1.12
    @angular/compiler-cli: ~9.1.0 => 9.1.12
    @angular/core: ~9.1.0 => 9.1.12
    @angular/flex-layout: ^9.0.0-beta.31 => 9.0.0-beta.31
    @angular/forms: ~9.1.0 => 9.1.12
    @angular/language-service: ~9.1.0 => 9.1.12
    @angular/material: ^9.2.0 => 9.2.4
    @angular/material-moment-adapter: ^10.2.4 => 10.2.4
    @angular/platform-browser: ~9.1.0 => 9.1.12
    @angular/platform-browser-dynamic: ~9.1.0 => 9.1.12
    @angular/router: ~9.1.0 => 9.1.12
    @aws-amplify/ui-angular: ^0.2.11 => 0.2.15
    @ngx-pwa/local-storage: ^9.0.3 => 9.0.3
    @swimlane/ngx-charts: ^14.0.0 => 14.0.0
    @types/jasmine: ~3.5.0 => 3.5.14
    @types/jasminewd2: ~2.0.3 => 2.0.8
    @types/node: ^12.11.1 => 12.12.62
    aws-amplify: ^3.0.20 => 3.3.1
    aws-amplify-angular: ^5.0.20 => 5.0.30
    buffer: ^5.6.0 => 5.6.0
    chart.js: ^2.9.3 => 2.9.3
    codelyzer: ^5.1.2 => 5.2.2
    core-util-is: ^1.0.2 => 1.0.2
    jasmine-core: ~3.5.0 => 3.5.0
    jasmine-spec-reporter: ~4.2.1 => 4.2.1
    karma: ~4.4.1 => 4.4.1
    karma-chrome-launcher: ~3.1.0 => 3.1.0
    karma-coverage-istanbul-reporter: ~2.1.0 => 2.1.1
    karma-jasmine: ~3.0.1 => 3.0.3
    karma-jasmine-html-reporter: ^1.4.2 => 1.5.4
    ng2-charts: ^2.4.1 => 2.4.1
    ng2-charts-schematics: ^0.1.7 => 0.1.7
    ngx-daterangepicker-material: ^3.0.4 => 3.0.4
    ngx-quill: ^8.1.8 => 8.1.8
    protractor: ~5.4.3 => 5.4.4
    quill: ^1.3.7 => 1.3.7
    rxjs: ^6.6.3 => 6.6.3
    ts-node: ~8.3.0 => 8.3.0
    tslib: ^1.10.0 => 1.13.0
    tslint: ~6.1.0 => 6.1.3
    typescript: ~3.8.3 => 3.8.3
    zone.js: ~0.10.2 => 0.10.3
  npmGlobalPackages:
    @angular/cli: 9.0.7
    @aws-amplify/cli: 4.30.0
    aws-amplify: 3.3.4
    version-check: 1.2.0
</details>


**Additional context**
[DEBUG] 17:14.130 AuthClass - signIn failure TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at Object.getItem (myAsyncStorage.ts:23)
    at CognitoUser.getCachedDeviceKeyAndPassword (CognitoUser.js:1437)
    at CognitoUser.js:288
    at Client.js:119
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Zone.run (zone-evergreen.js:123)
    at zone-evergreen.js:857
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Zone.runTask (zone-evergreen.js:167)

**Comment by sammartinez** [comment]
@Rajan-Gupta1 Can you fill me in as to what your use case is? I am slightly confused on the code snippets and what you are trying to do with the library. Thanks ahead of time!

**Comment by Rajan-Gupta1** [comment]
@sammartinez I am wanting to manage security tokens using the following the following [ [https://docs.amplify.aws/lib/auth/manageusers/q/platform/js#managing-security-tokens](url) in an Angular App. 
On integration, the code flow calls getItem() before it would have called setItem() resulting in he error provided above in Additional Context.

**Comment by sammartinez** [comment]
Got it, so I will state, the location you placed the `AuthStorage` value needs to be adjusted. You do want to call this from where you are initializing Amplify in your Angular application, most likely the `src/main.ts` file, to use Amplify and call properly instead of adding your `storage:AuthStorage` to the `aws-exports` file. 

Please look at these instructions from our docs site [here](https://docs.amplify.aws/start/getting-started/data-model/q/integration/angular#connect-frontend-to-api).

So once that is all setup, I would look to call `Auth.configure({ storage: AuthStorage });` from the `src/main.ts` file as well.

This should be what you need. Please report back if you are having any issues with this and please share a code snippet if you can. Thanks!
