### ISSUE TITLE
Amplify calls to get current username and JWT

### ISSUE THREAD

**Issue by GennadiyT** [aws-amplify/amplify-js#7034]
Hi there.
Here is my settings. There are 2 users in Cognito pool, RMSTEST and GENET. Web App, Web services and local DB are hosted on our own servers. RMSTEST user exists in our local db, GENET doesn't. When I log in as RMSTEST everything is Ok: Web App gets JWT via amplifyService.auth().currentSession().getAccessToken().getJwtToken() and attaches this token to the header of the service request.
On the service side request gets received, username claim verified against local db, expiration date verified and data gets sent back.
I log out as RMSTEST, **restart** browser and log in as GENET. Everything is Ok too: Web App let me in as GENET is in the pool, it gets token and sends request. On the service side request is rejected with 401 as GENET is not in local db.
Problem occurs when I don't restart browser in between users logs out. If I start browser, login as RMSTEST, than log out, log in back as GENET, service receives token with username claim as RMSTEST (?). But that was a user who was previously logged in, not current. As a result service verifies username against local db and sends data back. 
Vise versa, if I login first as GENET, Web App let me in, but service doesn't verify user name and sends back 401. If I log out and log in back as RMSTEST (w/o restarting browser) service still sends back 401, as username claim in JWT it received, has a name as GENET.
Interestingly, our Web App displays currently logged in user name in its header bar (for that we use amplifyService().aut().currentAuthenticatedUser() call). And in all those cases above user name displayed is **correct**, even in those two cases where we don't restart browser in between. IOW, in those two cases user name obtained via currentAuthenticatedUser is not the same as in JWT username claim.

Is this expected behavior or there is a bug in my code?
If this is a bug in my code please advise how to fix it.

Thank you very much in advance.
Gene

**Comment by amhinson** [comment]
@GennadiyT Would you be able to provide for some details about your issue:
- Amplify packages & versions
- code snippet of usage
- clear reproduction steps

**Comment by GennadiyT** [comment]
Hello Alex.
Sure I can. How can I get info about my Amplify packages & versions?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by amhinson** [comment]
You can just provide your `package.json` if you'd like! 👍

**Comment by GennadiyT** [comment]
Alex, I will be back to you as soon as I can get. I think we just got power outage. Sending it from my phone

**Comment by GennadiyT** [comment]
Hello Alex. Please find attached package.json.
Overview is component (see attached Overview.ts.txt),  where it makes call to service, implemented in SettingsService(see attached SettingsService.ts.txt).

Prerequisites:

  1.  Users “rmstest” and “genet” are valid members of the Cognito pool.
  2.  There is a record for “rmstest” user in our local Db, whereas there is no record for user “genet” in our local Db. IOW, from the service side, user “genet” is not a valid user.

--------------------------------------------------------------------------------------

Case I. Steps to repro:

  1.  Open browser.
  2.  Sign in as “rmstest” user. At this point browser opens Overview.html page
  3.  Sign out “rmstest” user. Do not close browser.
  4.  Sign in as “genet” user.
Result: browser opens Overview.html page
Expected result: browser shouldn’t open Overview.html page but rather open Sign in/Sign out page instead. Upon decoding received token and examining username claim, service should return 401 (Unauthorized) error code.

Here is a content of the token which service receives when user “rmstest” signed in:
{"kid":"q+u25gSefQ+B\/kMYyJBhmznwpJvjR0WVz4bunm1jUdQ=","alg":"RS256"}
{
  "sub": "3ad59935-dfaf-4c2b-8782-9bb5c7f5336c",
  "event_id": "db8526f1-cfda-4437-ad26-3faf2929d68b",
  "token_use": "access",
  "scope": "aws.cognito.signin.user.admin",
………
"jti": "54e975fe-94cd-4208-8439-793c29ea8475",
  "client_id": "49l54ma3d372rlvbi3lgt5shvv",
  "username": "rmstest"
}

Here is a content of the token which service receives after “rmstest” user signed out and user “genet” signed in:
{"kid":"q+u25gSefQ+B\/kMYyJBhmznwpJvjR0WVz4bunm1jUdQ=","alg":"RS256"}
{
  "sub": "3ad59935-dfaf-4c2b-8782-9bb5c7f5336c",
  "event_id": "db8526f1-cfda-4437-ad26-3faf2929d68b",
  "token_use": "access",
  "scope": "aws.cognito.signin.user.admin",
…….
  "jti": "54e975fe-94cd-4208-8439-793c29ea8475",
  "client_id": "49l54ma3d372rlvbi3lgt5shvv",
  "username": "rmstest"
}

I expect that second token would have “username”: ”genet”
--------------------------------------------------------------------------------------

Case II. Steps to repro:

  1.  Open browser.
  2.  Sign in as “genet” user. At this point browser stays at Sign In/Sign Out page. (Service returned back 401 Unauthorized, as “genet” user for service is not valid one).
  3.  Sign out “genet” user. Do not close browser
  4.  Sign in as “rmstest” user.
Result: browser stays on Sign In/Sign Out page.
Expected result: browser should open Overview.html page, but it rather stays on Sign In/Sign Out page instead. Upon decoding received token and examining username claim, service should return 200 Ok code along with data.

Here is a content of the token which service receives when user “genet” signed in:
{"kid":"q+u25gSefQ+B\/kMYyJBhmznwpJvjR0WVz4bunm1jUdQ=","alg":"RS256"}
{
  "sub": "6c993af1-99de-4add-aae9-c085324a5eaf",
  "event_id": "0e25a1cc-c1c6-43c4-98c3-c8d4ac88ef8e",
  "token_use": "access",
  "scope": "aws.cognito.signin.user.admin",
…..
"jti": "652ab47a-1ca3-46d9-8d21-57131a15c310",
  "client_id": "49l54ma3d372rlvbi3lgt5shvv",
  "username": "genet"
}

Here is a content of the token which service receives after user “genet” signed out and user “rmstest” signed in:
{"kid":"q+u25gSefQ+B\/kMYyJBhmznwpJvjR0WVz4bunm1jUdQ=","alg":"RS256"}
{
  "sub": "6c993af1-99de-4add-aae9-c085324a5eaf",
  "event_id": "0e25a1cc-c1c6-43c4-98c3-c8d4ac88ef8e",
  "token_use": "access",
  "scope": "aws.cognito.signin.user.admin",
…..
"jti": "652ab47a-1ca3-46d9-8d21-57131a15c310",
  "client_id": "49l54ma3d372rlvbi3lgt5shvv",
  "username": "genet"
}

Alex, just to make it clear: these 2 cases work  Ok, as I would expect, if I restart (close and reopen) browser between signing out/signing in users.
IOW:

  1.  if I sign in as user “rmstest” (valid user in Cognito pool as well as valid for service), browser opens Overview.html. Then I sign off, close browser, open browser again, and sign in as user “genet”, browser stays in Sign In/Sign Out page as it received 401 from service (invalid user from service side).
  2.  If I sign in as user “genet” (valid user in Cognito pool, but invalid for service), browser stays on Sign In/Sign Out page, doesn’t let open Overview.html as it receives 401 from service. Then I sign off, close browser, reopen browser, and sign in as user “rmstest”, browser opens up Overview.html.

Hopefully you will get a picture of the problem. And please let me know if you need more info from me.

Thanks,
Gene


From: Gene Tsekhanovskiy
Sent: Wednesday, October 21, 2020 1:59 PM
To: aws-amplify/amplify-js <reply@reply.github.com>
Subject: RE: [Potential Spam] Re: [aws-amplify/amplify-js] Amplify calls to get current username and JWT (#7034)

Alex, I will be back to you as soon as I can get. I think we just got power outage. Sending it from my phone

**Comment by amhinson** [comment]
Could you provide how you are signing in and signing out user? And just any other Amplify usage related to this Auth flow. It appears that you are managing tokens yourself, which could conflict with what `amplify-js` is already doing behind the scenes.

**Comment by GennadiyT** [comment]
Hi Alex.
I don’t think we are managing tokens ourselves, we just query for a token for a given (signed in) user.
May be this would help:
we have component class (OverviewComponent.ts)) and we have service class (SettingServices.ts). SettingsService  gets called from OverviewComponent.
If I call Amplify/Auth from OverviewComponent ctor and store data(username/accessToken) in localStorage than I don’t have any problems in SettingsService to fetch data back from localStorage and attach token to Authorization header. On the contrary, when I call Amplify/Auth from within SettingsService ctor and try then same, httpRequest gets sent with empty Authorization header or with the token belonged to previously signed in user.
Just to make sure, I added/implemented HTTP Interceptor to catch and examine request,  and that also proved a case: if Amplify gets called from within Overview and data is stored in localStorage – no problems whatsoever;; if it gets called from SettingsService, than value of the token either empty (in case of browser’s new session) or token is from previously assigned user (if browser was not restarted).

And if you still would like to see how we signing in – where I can find this. For signing out here is one of our functions:

private logOut() {
      console.log("Clearing sessionStorage after logging out.");
      sessionStorage.clear();
      console.log("Clearing localStorage after logging out.");
      localStorage.clear();
      this.amplifySvc.auth().signOut(global, true);
      this.router.navigateByUrl("/login");
}

Thanks,
Gene

**Comment by GennadiyT** [comment]
HI Alex.
Please take a this. Is this what’ve asked about signing in:

import { Component, OnInit } from '@angular/core';
import { AmplifyService } from 'aws-amplify-angular';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {
  signedIn: boolean;
  user: any;
  greeting: string;
  appBrand;
  constructor(private amplifySvc: AmplifyService,
    private router: Router) {
    this.amplifySvc.authStateChange$
    .subscribe(authState => {
      if (authState.state === "signedIn") {
          sessionStorage.setItem("userid", "");

          this.router.navigateByUrl("/dashboard/overview");
      }
    });
}

  ngOnInit() {
  }

}



From: Gene Tsekhanovskiy
Sent: Monday, October 26, 2020 3:52 PM
To: aws-amplify/amplify-js <reply@reply.github.com>
Subject: RE: [Potential Spam] Re: [aws-amplify/amplify-js] Amplify calls to get current username and JWT (#7034)

Hi Alex.
I don’t think we are managing tokens ourselves, we just query for a token for a given (signed in) user.
May be this would help:
we have component class (OverviewComponent.ts)) and we have service class (SettingServices.ts). SettingsService  gets called from OverviewComponent.
If I call Amplify/Auth from OverviewComponent ctor and store data(username/accessToken) in localStorage than I don’t have any problems in SettingsService to fetch data back from localStorage and attach token to Authorization header. On the contrary, when I call Amplify/Auth from within SettingsService ctor and try then same, httpRequest gets sent with empty Authorization header or with the token belonged to previously signed in user.
Just to make sure, I added/implemented HTTP Interceptor to catch and examine request,  and that also proved a case: if Amplify gets called from within Overview and data is stored in localStorage – no problems whatsoever;; if it gets called from SettingsService, than value of the token either empty (in case of browser’s new session) or token is from previously assigned user (if browser was not restarted).

And if you still would like to see how we signing in – where I can find this. For signing out here is one of our functions:

private logOut() {
      console.log("Clearing sessionStorage after logging out.");
      sessionStorage.clear();
      console.log("Clearing localStorage after logging out.");
      localStorage.clear();
      this.amplifySvc.auth().signOut(global, true);
      this.router.navigateByUrl("/login");
}

Thanks,
Gene

**Comment by amhinson** [comment]
@GennadiyT I am still having a bit of trouble replicating your use-case and example here. Would you be able to create a small sample repo that shows the behavior you are seeing?

**Comment by GennadiyT** [comment]
Hi Alex. I found work around. I think you can close this ticket and thank you.

Gene

**Comment by amhinson** [comment]
Ok glad you were able to figure it out! 👍
