### ISSUE TITLE
Pre-rendering for dynamic server-rendered routes

### ISSUE THREAD

**Issue by arelaxend** [aws-amplify/amplify-js#7037]
Dear contributors, 

**Is your feature request related to a problem? Please describe.**
In the current documentation, we see: 
`Note: Next also supports pre-rendering for dynamic server-rendered routes. At this time, Amplify does not support the hosting of dynamic server-rendered routes with Next.`

**Describe the solution you'd like**
Is it plan to add this feature ?

Or should we go for https://github.com/serverless-nextjs/serverless-next.js as this is not in a roadmap?

Thanks,
A.

**Comment by amhinson** [comment]
There is actually an open issue that the Amplify Console team is tracking for SSR support with hosting: https://github.com/aws-amplify/amplify-console/issues/412

Feel free to add your comments and support on that issue 👍
