### ISSUE TITLE
How can i style the sign out button for the authentication component

### ISSUE THREAD

**Issue by FrankSD** [aws-amplify/amplify-js#7039]
How can i style the sign out button for the authentication component

- After  signing in the sign-out button  stretch across my entire viewport.

- I want the sign-out button to be small in size and an ability to be placed anywhere on my navigation bar

- Is there a way i can override  its  CSS  styling?

**Comment by amhinson** [comment]
@FrankSD Have you tried wrapping the button with your own `div` wrapper, which you can then style and position appropriately?

**Comment by FrankSD** [comment]
@amhinson   let me  check that  out....

**Comment by FrankSD** [comment]
It   very hard  to style the  button.....is there a sample code  i can follow? Otherwise i will  go  with another  Authentication API for now.I simply want to place the sight out button on my navigation....and listen  events for sign in and sign out.I need  the ability to change from sign in button to  sign out.The only  Element i  see is      <amplify-sign-out ></amplify-sign-out>.And this is not a button...am i  missing something  here?I think users should be able to style and move the sign in/Signout button  easily for this  to work

**Comment by amhinson** [comment]
Here are some options for customizing the theme, if that's what you're looking to do: https://docs.amplify.aws/ui/customization/theming/q/framework/react

Otherwise, you could always just fallback to managing the UI yourself and just using `Auth` directly: https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js

**Comment by garrettmaring** [comment]
@amhinson unfortunately, managing the sign out UI ourselves isn't a great option at the moment since the behavior is different. The button correctly redirects to the login page when clicked while using `Auth.signOut()` does not.

**Comment by twillisdev** [comment]
I have the same issue. How do I open a new topic for this issue. The component works , but I am needing 2 things: 

1. to style the component according to my client's needs
2. to redirect user back to the home screen after sign out.

Thanks in advance if anyone can tell me how to get an answer. :)

**Comment by iamjimmyg** [comment]
Same Issue

**Comment by twillisdev** [comment]
@iamjimmyg hey. I actually figured it out. You can place the <AmplifySignOut /> component within a div and apply your css styling as normal. And I also found a workaround for redirecting logout back to home. from the following post: https://serverless-stack.com/chapters/redirect-on-login-and-logout.html

Hope that helps you!

**Comment by sytolk** [comment]
This works for me
```javascript
import { Auth } from 'aws-amplify';
import Button from '@material-ui/core/Button';

<Button
                onClick={() => Auth.signOut()}
                title={i18n.t('core:signOut')}
                className={classes.mainActionButton}
                size="small"
                variant="outlined"
                color="primary"
                style={{ width: '95%' }}
              >
                <ExitToAppIcon className={classNames(classes.leftIcon)} />
                {i18n.t('core:signOut')}
</Button>
```

**Comment by madak17** [comment]
I'm also having trouble with styling the sign out button... all I want to do is reduce its size! I wrapped the component in a div, but still can't seem to change the size of the button. E.g. this doesn't work:

<div id="LoginSignOut">
    <AmplifySignOut id="SignOutButton"/>
</div>

div#LoginSignOut amplify-sign-out#SignOutButton {
    min-width: 0;
    --padding: 0;
} 

Trying to hit down to the amplify-button or button level doesn't seem to work either since it's in the shadow-dom. Having to create custom components just to change simple styles seems overkill to me.

**Comment by nomadus** [comment]
Why has this issue been closed? I don't see any valid solution or workaround suggested. Creating whole new custom components just to be able to change the style of a button is not justified.

**Comment by nathanielrindlaub** [comment]
It looks like the amplify-js sign-out component [dispatches](https://github.com/aws-amplify/amplify-js/blob/8fe18534b752d807d175104cbd8ccb3099997b2d/packages/amplify-ui-components/src/components/amplify-sign-out/amplify-sign-out.tsx#L35) an `authStateChangeEvent` to the Amplify [Hub](https://docs.amplify.aws/lib/utilities/hub/q/platform/js) after it calls `Auth.signOut()`. So you can mimic that behavior by creating a custom button, manually evoking the `Auth.signOut()` method, and publishing a sign out event to the Hub. The following worked for me and successfully redirects users back to the login  screen:

```javascript
import React from 'react';
import { Auth, Hub } from 'aws-amplify';

const handleSignOutButtonClick = async () => {
    try {
        await Auth.signOut();
        Hub.dispatch('UI Auth', {.   // channel must be 'UI Auth'
            event: 'AuthStateChange',    // event must be 'AuthStateChange'
            message: 'signedout'    // message must be 'signedout'
        });
    } catch (error) {
        console.log('error signing out: ', error);
    }
};  

const CustomSignOutButton = () => {
    return (
        <button
            onClick={handleSignOutButtonClick}>
            Sign out
        </button>
    );
};

```

**Comment by rescueahero** [comment]
> It looks like the amplify-js sign-out component [dispatches](https://github.com/aws-amplify/amplify-js/blob/8fe18534b752d807d175104cbd8ccb3099997b2d/packages/amplify-ui-components/src/components/amplify-sign-out/amplify-sign-out.tsx#L35) an `authStateChangeEvent` to the Amplify [Hub](https://docs.amplify.aws/lib/utilities/hub/q/platform/js) after it calls `Auth.signOut()`. So you can mimic that behavior by creating a custom button, manually evoking the `Auth.signOut()` method, and publishing a sign out event to the Hub. The following worked for me and successfully redirects users back to the login screen:
> 
> ```js
> import React from 'react';
> import { Auth, Hub } from 'aws-amplify';
> 
> const handleSignOutButtonClick = async () => {
>     try {
>         await Auth.signOut();
>         Hub.dispatch('UI Auth', {.   // channel must be 'UI Auth'
>             event: 'AuthStateChange',    // event must be 'AuthStateChange'
>             message: 'signedout'    // message must be 'signedout'
>         });
>     } catch (error) {
>         console.log('error signing out: ', error);
>     }
> };  
> 
> const CustomSignOutButton = () => {
>     return (
>         <button
>             onClick={handleSignOutButtonClick}>
>             Sign out
>         </button>
>     );
> };
> ```



> It looks like the amplify-js sign-out component [dispatches](https://github.com/aws-amplify/amplify-js/blob/8fe18534b752d807d175104cbd8ccb3099997b2d/packages/amplify-ui-components/src/components/amplify-sign-out/amplify-sign-out.tsx#L35) an `authStateChangeEvent` to the Amplify [Hub](https://docs.amplify.aws/lib/utilities/hub/q/platform/js) after it calls `Auth.signOut()`. So you can mimic that behavior by creating a custom button, manually evoking the `Auth.signOut()` method, and publishing a sign out event to the Hub. The following worked for me and successfully redirects users back to the login screen:
> 
> ```js
> import React from 'react';
> import { Auth, Hub } from 'aws-amplify';
> 
> const handleSignOutButtonClick = async () => {
>     try {
>         await Auth.signOut();
>         Hub.dispatch('UI Auth', {.   // channel must be 'UI Auth'
>             event: 'AuthStateChange',    // event must be 'AuthStateChange'
>             message: 'signedout'    // message must be 'signedout'
>         });
>     } catch (error) {
>         console.log('error signing out: ', error);
>     }
> };  
> 
> const CustomSignOutButton = () => {
>     return (
>         <button
>             onClick={handleSignOutButtonClick}>
>             Sign out
>         </button>
>     );
> };
> ```

This worked for me!

**Comment by smiccoli** [comment]
> It looks like the amplify-js sign-out component [dispatches](https://github.com/aws-amplify/amplify-js/blob/8fe18534b752d807d175104cbd8ccb3099997b2d/packages/amplify-ui-components/src/components/amplify-sign-out/amplify-sign-out.tsx#L35) an `authStateChangeEvent` to the Amplify [Hub](https://docs.amplify.aws/lib/utilities/hub/q/platform/js) after it calls `Auth.signOut()`. So you can mimic that behavior by creating a custom button, manually evoking the `Auth.signOut()` method, and publishing a sign out event to the Hub. The following worked for me and successfully redirects users back to the login screen

Thanks! 

After putting some terrible workaround with multiple Hub.listen, to target both `Auth` and `UI Auth` channels this really give me some peace of mind.

Once again the official documentation was not exaustive enough...

**Comment by icurto2020** [comment]
Just styling the button worked for me:
 <button onClick={signOut}
	  style={{background: 'beige', width: '250px', height: '75px', margin:'50px',
	  borderRadius:'20%', border: 'none', outline: 'none', fontSize:'35px', fontWeight:'bold' }}
	  >Sign Out</button>
