### ISSUE TITLE
TOTP Setup doesn't work if Cognito Pool has remember devices

### ISSUE THREAD

**Issue by BDNilsson** [aws-amplify/amplify-js#7051]
Same as https://github.com/aws-amplify/amplify-js/issues/6283

Describe the bug
If a cognito pool has settings to remember a device (opt-in or always) the login fails when setting up MFA.

To Reproduce

    Create cognito pool with MFA required, and devices remembered
    Use a user created by an admin without a phone number to enforce MFA SETUP
    Login as the new user, scan the qr code and enter the code.
    You will get an error: "NotAuthorizedException" "Invalid Refresh Token."
    Refresh and try to log in now
    log in will be successful

Expected behavior
Login should be successful on initial setup (this is true if devices are not remembered)

Desktop (please complete the following information):

    OS: Win 10
    Browser: Firefox

Additional context
Expected behavior does indeed happen if the user pool has device settings set to No.

I believe in the initial MFA setup no device settings are sent which causes the refresh token error, however when not doing the initial setup device settings are sent which is why it works.
[package.json.txt](https://github.com/aws-amplify/amplify-js/files/5429083/package.json.txt)

Using a very incredibly basic project can easily reproduce this with just following the docs and using the amplify-authenticator ui

**Comment by chrispruitt** [comment]
I am seeing the exact issue as well.

**Comment by BDNilsson** [comment]
Is there anything else needed to get this resolved or looked at?

**Comment by sammartinez** [comment]
@evcodes can you validate this with the work you are doing with Device tracking?

**Comment by evcodes** [comment]
I will take a look at this today

**Comment by evcodes** [comment]
Hello @BDNilsson, I walked through this entire issue and I was able to login without a problem on the first time. This leads me to believe that either some settings are off or you could try a more updated version of Amplify. Please show me your user pool configurations and aws exports. 

Here's a video of me registering a user without a phone number and logging them in for the first time:

https://user-images.githubusercontent.com/22283303/119178238-6c6f4380-ba3b-11eb-9cc0-64a1d060a9bb.mp4


I did have some errors come up on the console:

`cognito-idp.us-east-1.amazonaws.com/:1 Failed to load resource: the server responded with a status of 400 ()
cognito-idp.us-east-1.amazonaws.com/:1 Failed to load resource: the server responded with a status of 400 ()
cognito-idp.us-east-1.amazonaws.com/:1 Failed to load resource: the server responded with a status of 400 ()
cognito-idp.us-east-1.amazonaws.com/:1 Failed to load resource: the server responded with a status of 400 ()
2index.js:1 [ERROR] 17:16.939 helpers - User is not authenticated`

However, I was able to login the first time and I tried on both Chrome and Mozilla Firefox. I would recommend trying to update your amplify version to the latest, I used 4.0.2. Please let us know if this issue persists. 

Thank you again for choosing Amplify to power your apps.
