### ISSUE TITLE
AuthClass API ICredentials Breaking Change on IdentityId since when?

### ISSUE THREAD

**Issue by chantlong** [aws-amplify/amplify-js#7054]
I used to retrieve the IdentityId from a Cognito Login via the following

```
const identityId = Auth.currentCredentials().then(response => {
              const { IdentityId } = response.data
              return IdentityId
            })
```

Because it broke recently, I found out the API for AuthClass changed so you have to use below instead.

```
Auth.currentCredentials().then(response => {
              const { identityId } = response
              return identityId
            })
```

As you can see the API response changed and `IdentityId` became `identityId` and 1 layer of nesting was removed.

When did this happen and where should I go to keep posted?

I was looking though amplify core CHANGE LOG but not sure if this was related.
https://github.com/aws-amplify/amplify-js/pull/6618/files

**Comment by amhinson** [comment]
@chantlong Do you know what previous version of `aws-amplify` was returning the data as you were expecting?

**Comment by chantlong** [comment]
@amhinson 
Looking at the my package.json history I noticed I upgraded from 

```
aws-amplify: ^2.2.1
```

to

```
"@aws-amplify/api": "^3.2.6",
"@aws-amplify/api-graphql": "^1.2.6",
"@aws-amplify/auth": "^3.4.6",
"@aws-amplify/core": "^3.6.0",
"@aws-amplify/storage": "^3.3.6",
```

That may be related.

**Comment by amhinson** [comment]
Ah ok thanks for that info! As an aside, we do recommend just using `aws-amplify` in your `package.json` instead of using the modular libraries independently because it is easy for them to get out of sync.

It does appear, however, that the return type based on the [TypeScript definitions](https://github.com/aws-amplify/amplify-js/blob/main/packages/core/src/types/types.ts#L14) has always been `identityId`. Perhaps this might have been a bug at one point, but the behavior you're seeing now is expected.

**Comment by chantlong** [comment]
Thanks for the heads up. If it's better to use `aws-amplify`, I was just wondering why the `@aws-amplify/...` are public on npm out of curiosity.
I switched over to the modules because I thought when importing it, the bundle sizes would be smaller because I don't use Data Store ...etc.

Yeah when I reviewed the TypeScript defs I noticed it didn't changed either. Anyways thanks.

**Comment by amhinson** [comment]
The packages are modular, so any tree-shaking with webpack/babel will effectively eliminate any dead code when using `aws-amplify`. There are other reasons as to why they are all individually published, but long story short is that we now recommend just the single package 🙂
