### ISSUE TITLE
AppSync websocket does not reconnect

### ISSUE THREAD

**Issue by bensie** [aws-amplify/amplify-js#7057]
**Describe the bug**
The connection to the GraphQL subscription websocket provided by AppSync is made during the call to ` GraphQLAPI.graphql({ query: ..., variables: {...} }, {}).subscribe(...)`. If the connection is dropped for any reason, there are no attempts to reconnect. Common reasons for disconnecting include closing the lid of the computer, switching networks, dropping the connection on an unreliable network, etc.

We are seeing this issue constantly, as it has been plaguing both our web application and our React Native application. On the React Native side, it occurs after an unknown/arbitrary period after the application is backgrounded or when switching between wi-fi and cellular networks.

Since the connection appears to be lazily instantiated during the call to Amplify's [`subscribe()`](https://github.com/aws-amplify/amplify-js/blob/61f7478609fce7dd2f25c562aeb887d3f3db4a67/packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts#L165) and we have dozens of subscriptions on a connection, we're struggling to come up with a reasonable workaround for reconnecting and resubscribing. We do get an error in `subscribe`'s error callback, but it gets called for each subscription - there doesn't seem to be a place to hook into the connection singleton.

Really appreciate you all taking a look! Let me know if there's anything else I can provide.

**To Reproduce**

I've made a [sample application](https://github.com/bensie/amplify-ws-disconnect) that demonstrates the issue in web. If you need a sample React Native project as well, happy to provide that but thought I'd start with this.

1. Run [this CloudFormation template](https://github.com/bensie/amplify-ws-disconnect/blob/main/template.yml) in an account and region where AppSync is supported. It creates an AppSync API, Schema, Resolvers, and a Lambda function that returns some sample data.
1. Once the stack is created, go to the Outputs tab in the CloudFormation stack and copy the values for `Region`, `GraphQLAPIUrl`, and `APIKey` and paste them into their respective variables in [App.js](https://github.com/bensie/amplify-ws-disconnect/blob/main/spa/src/App.js#L7-L9).
1. `cd` into the `spa` directory and run `yarn install` and `yarn start`.
1. This should launch your browser into development mode of a React app, which is configured to subscribe to changes when the `updateWidget` mutation is fired. Browser dev tools should indicate a successful connection and that subscription is active. This demo only makes a single subscription, but please assume the presence of dozens in a real-world app.
1. Disable your network interface
1. After a few seconds, you'll get an error in the browser dev console for `The connection to wss://xxxyyyy.appsync-realtime-api.us-west-2.amazonaws.com/graphql?header=xxxyyy&payload=e30= was interrupted while the page was loading.`
1. Re-enable the network interface. No reconnect attempt is made.

**Expected behavior**
Reconnect to the websocket and resubscribe to any subscriptions that were dropped by the flaky connection. Or alternatively, some way to get visibility into the client/connection so we can code around this, check connection status, and reconnect in our own timeout or whatever you recommend :)

**Code Snippet**
https://github.com/bensie/amplify-ws-disconnect

* CloudFormation template in the root for server resources
* React single-page app in the `spa` folder for client-side code

**Comment by elorzafe** [comment]
@bensie 

Thanks for your feedback. Automatic reconnection is not available on API category. You will have to deal with this on the `observer error` callback.

The problem is that handling data and control messages on the subscription channel will be a breaking change and we cannot add this to the current version. The existing mechanism is using by re-initializing the subscription. 

DataStore has this logic implemented by listening network changes, specially because if there is a network issue you want to reconnect when the network is on again. 

You can take a look on the code [here](https://github.com/aws-amplify/amplify-js/blob/main/packages/datastore/src/sync/index.ts#L155)

**Comment by stayingcool** [comment]
Does this apply to GraphQL client as well? I'm not using GraphQL SDK and I'm seeing the same issue.

**Comment by mpruyn** [comment]
if I may,not to intrude or be disrespectful im new to well every thing tech related and have been having serious issues with my phone ,pc,etc. and well can any one help with tech ip and problems with intruders I have one in ip address of problem 192.168.0.63 and remote address 52.242.211.89 and that is acced through port 49672 ...please help

**Comment by bensie** [comment]
Thanks for the info @elorzafe. Going to close this since it cannot be supported in the current major version. We opted to implement our own client based on the [AppSync websocket spec](https://docs.aws.amazon.com/appsync/latest/devguide/real-time-websocket-client.html), which is pretty great and works exactly as documented.

**Comment by avlonder** [comment]
> Thanks for your feedback. Automatic reconnection is not available on API category. You will have to deal with this on the `observer error` callback.

Is it possible to use a Hub listener to detect the disconnect error?

**Comment by AceTheNinja** [comment]
@bensie 

> We opted to implement our own client based on the AppSync websocket spec

We use a lot of subscriptions and are facing the same issue. Any chance you can open-source that client?
