### ISSUE TITLE
Appsync Datastore large Document Data usage

### ISSUE THREAD

**Issue by imoby** [aws-amplify/amplify-js#7059]
Using aws app sync with datastore is creating a really large document data in iOS

Some additional details:
- I’m using the datastore to just store text and references to images in an S3 bucket
- Actual images are not stored in datastore
- I’m seeing a 500mb document data for what is mainly text stored in datastore

**To Reproduce**

1. Create a react native app using react native cli
2. Add appsync datastore and store images in S3 and references to those image names in datastore dynamo db
3. After about 50 or so records the size of the document data shows as a lot 

**Expected behavior**
I’d expect with the datastore data to be just text that it shouldn’t be 500mbs

**Screenshots**
![B41C4D63-070F-4C72-A4AB-45922FC41DBF](https://user-images.githubusercontent.com/6380855/97098436-e9c00a80-164a-11eb-915d-f707dfc0b8a9.jpeg)

**What is Configured?**
- React native
- AWS datastore app sync to store small amounts of text

**Comment by sw-yx** [comment]
interesting. any way for you to peek inside and see what's in that 500mb?

**Comment by elorzafe** [comment]
@imoby, can you share the schema you are using?

Have you tried this on a Web App or Android App?

**Comment by iartemiev** [comment]
@imoby it's very unlikely that that space is being taken up by DataStore. I just tested an RN app on a physical device with 50 records and 10 models and it's using ~ 600kb. 

Could your app be caching your images locally?

**Comment by andrekovac** [comment]
@imoby May I ask why you closed the issue? What was the reason for the big amount of data? How much of that was taken up by the DataStore?

**Comment by imoby** [comment]
@andrekovac sorry I should have posted that when I closed it. Yes the issue was that my images were taking up space and was caching them in a different folder even though the folder that original was going into I already deleted.
