### ISSUE TITLE
Unable to verify secret hash for client

### ISSUE THREAD

**Issue by castledraw** [aws-amplify/amplify-js#7064]
Hi @ericclemmons , I want to login my amplify app with a cognito appclient with secret key. There is required for me, because i configured an elasticsearch instances with cognito, and automatically thats created an appclient with secretkey. So i want to load a dashboard kibana in my amplify app, but i received de same error Unable to verify secret hash for client.

I can't create another appclient without secret key, because elasticsearch use another with this.
https://github.com/aws-amplify/amplify-js/discussions/7063

_Originally posted by @castledraw in https://github.com/aws-amplify/amplify-js/issues/1368#issuecomment-716726826_

**Comment by elorzafe** [comment]
@castledraw 

Can you give more details from your App, and how you are using Amplify?

Is a SSR App?

**Comment by castledraw** [comment]
@elorzafe I have an application built with react and amplify.  This use cognito for Auth, and i want to embed a kibana dashboard in my app. 

There is my elasticsearch instance configuration
![image](https://user-images.githubusercontent.com/11053872/97232596-0bcca080-17a3-11eb-9566-6d37b3da995b.png)
![image](https://user-images.githubusercontent.com/11053872/97232607-10915480-17a3-11eb-949e-0f0d3541bbc7.png)

When i enabled the cognito auth, elasticsearch generate an application client with secret key
![image](https://user-images.githubusercontent.com/11053872/97232770-6108b200-17a3-11eb-9b61-97fbe9f236b6.png)

And i designed a kibana dashboard, that i want to embed in my application. So, i modified aws_user_pools_web_client_id in the aws-export with the appclient generate by elasticsearch in my cognito userpools, but cant login in my app, i received the following error:
![image](https://user-images.githubusercontent.com/11053872/97233073-f146f700-17a3-11eb-9f34-7c3782be7979.png)

If, i modify my aws-export with an appclient withou secretkey, i can loginf without problem, but i cant embed my kibana dashboard
![image](https://user-images.githubusercontent.com/11053872/97233309-6286aa00-17a4-11eb-9ec4-a88e07fcac0f.png)

**Comment by castledraw** [comment]
I want to embed my kibana dashboard(configured with cognito) in my react amplify application with the same cognito user pool. I'm Ok all the configuration:

- ElasticSearch with cognito authentication, its Ok
- React Application with Amplify, its Ok
- Auth with cognito in my application, its Ok, if i use a new appclient without secret key.... but i need to share the same appclient created by elasticsearch in my app

**Comment by castledraw** [comment]
Hi guys, i want to know if my use case is valid? and if it's possible make adjust to support it? Some alternative? 
Thanks!

**Comment by castledraw** [comment]
Hi guys, do you have anything solution's alternative?

**Comment by thetaPC** [comment]
I'm getting the same error for `SECRET_HASH` when using `amazon-cognito-identity-js`. There's a PR https://github.com/aws-amplify/amplify-js/pull/7974 that has a possible solution.

However, the `CognitoUserPool` might be best to implement the `SECRET_HASH` as I mention in my comment over there https://github.com/aws-amplify/amplify-js/pull/7974#issuecomment-867838527

@elorzafe thoughts?

**Comment by thetaPC** [comment]
@sammartinez Here's an open issue for #7974 
What is the status of this issue?

**Comment by nadetastic** [comment]
Hi @castledraw @thetaPC following up on this issue.

Amplify doesn't currently support the use of client secrets for auth. There has been much discussion about this in the past and the conclusion has always ended up being to not support the use of client secrets as they are meant to be used for server to server communications.

I have been revisiting this discussion and in particular for your use case, one option would be to create a second non-private app client for your user pool and use that with your Amplify application. Would this be a viable route?

**Comment by thetaPC** [comment]
> Hi @castledraw @thetaPC following up on this issue.
> 
> Amplify doesn't currently support the use of client secrets for auth. There has been much discussion about this in the past and the conclusion has always ended up being to not support the use of client secrets as they are meant to be used for server to server communications.
> 
> I have been revisiting this discussion and in particular for your use case, one option would be to create a second non-private app client for your user pool and use that with your Amplify application. Would this be a viable route?
> 
>     * [Configure User pool app client](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-client-apps.html)
> 
>     * [Setting up Ampify Auth](https://docs.amplify.aws/lib/auth/getting-started/q/platform/js/#set-up-backend-resources) (Manual Configuration tab)

@nadetastic Thank you for the follow up! The option provided is a viable route. However, we ended up using a different library.

**Comment by nadetastic** [comment]
@thetaPC thanks for following up 😄 - then I'll go ahead and resolve this issue. Let me know if you have any related questions.
