### ISSUE TITLE
React native iOS user signed out when offline and idToken expired

### ISSUE THREAD

**Issue by vishgoel007** [aws-amplify/amplify-js#7073]
**Describe the bug**
When the app is open in offline mode (no internet connection) and ```Auth.currentAuthenticatedUser()``` is called, the function give exception "not authenticated". Id token is expired and refresh token is valid.

**To Reproduce**

1. User signed in
2. User went offline
3. User opened the app again after one hour or more (since idToken expiry is one hour) in offline mode
4. User signed out (getting err "not authenticated")

**Expected behavior**
We should not get exception/error ("not authenticated") when the idToken has expired and app is opened in offline mode.

**Code Snippet**
Provided in screenshots below

**Screenshots**
![PastedGraphic-1](https://user-images.githubusercontent.com/36643209/97390850-ca9fd200-1903-11eb-8128-c73ef01ce89b.png)
![PastedGraphic-3](https://user-images.githubusercontent.com/36643209/97390937-ffac2480-1903-11eb-9cda-e8f9625fa74a.png)

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.
* Which resources do you have configured?
   * If applicable, please provide your manual configuration example:
   ```
    Auth: {
    region: "us-east-2",
    userPoolId: xxxxxx123",
    userPoolWebClientId: "1234xxxxxxxxe5678",
    mandatorySignIn: true,
    authenticationFlowType: "CUSTOM_AUTH",
  },
  Analytics: {
    disabled: true,
  }
   ```
* If applicable, provide more configuration data, for example for Amazon Cognito, run `aws cognito-idp describe-user-pool --user-pool-id us-west-2_xxxxxx` (Be sure to remove any sensitive data)
 

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages

System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 106.25 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.21.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 86.0.4240.111
    Safari: 14.0
  npmGlobalPackages:
    azure-functions-core-tools: 3.0.2881
    create-react-native-app: 3.5.0
    expo-cli: 3.21.10
    n: 6.6.0

```

</details>

**Smartphone (please complete the following information):**

- Device: iPhone11
- OS: iOS14.0
- Version
 amazon-cognito-identity-js: 4.4.0
 aws-amplify: 3.3.2
 aws-amplify-react-native:  4.2.7
 react-native: 0.63.3

**Comment by mauerbac** [comment]
Apologies on the late response here. Going through old issues. If this is still occurring, please re-open the issue and tag us.
