### ISSUE TITLE
AuthClass was removed from the export of ./aws/amplify-js/packages/auth/src/index.ts

### ISSUE THREAD

**Issue by ruiyang** [aws-amplify/amplify-js#7074]
**Describe the bug**
AuthClass was removed from commit 2b34736f8b88f022618a2933b3a02987ec1ab514.

**Expected behavior**
AuthClass should remain exported because it could be used by others.

**Code Snippet**
before:
export {
	Auth,
	AuthClass,
	CognitoUser,
	CookieStorage,
	CognitoHostedUIIdentityProvider,
	appendToCognitoUserAgent
};

now:
export { Auth, CognitoUser, CookieStorage, CognitoHostedUIIdentityProvider };

**Additional context**
Because cognito saml login require email as an mutable fields and there is no way to make it from immutable to mutable once you created the user pool. So we ended up with two user pools to support normal login and saml login in one app.
In the app, we need to create two AuthClass instances. one is the default Auth, and another one is created using new AuthClass() for saml. Removing the AuthClass from export blocked us from upgrading the library.

**Comment by mauerbac** [comment]
Sorry for the delay in responding to this feedback. This was removed [here](https://github.com/aws/aws-sdk-js-v3/#configuration). In version 3.x.x, due to credentials within the AWS SDK.
