### ISSUE TITLE
Federated SignIn during manual configuration.

### ISSUE THREAD

**Issue by Mskalba** [aws-amplify/amplify-js#7080]
**Describe the bug**
I am trying to implement Federated SignIn with usage of manual Amplify configuration. The Cognito is already used and Google setup is finished in Cognito as well.

**To Reproduce**
In Create react app add package: `aws-amplify`

Configure it following the documentation:

```
Amplify.configure({
  Auth: {
    identityPoolId: process.env.REACT_APP_IDENTITY_POOL_ID,
    region: process.env.REACT_APP_COGNITO_REGION,
    userPoolId: process.env.REACT_APP_COGNITO_POOL_ID,
    userPoolWebClientId: process.env.REACT_APP_COGNITO_USER_POOL_WEB_CLIENT_ID,
}
})
```

Try to use SignIn with Google:

```
Auth.federatedSignIn({ provider: "Google" });
```

The error displayed:

```
Uncaught (in promise) TypeError: Cannot read property 'redirectSignIn' of undefined
```

redirectSignIn should not be required without usage of HostedUI. It is right now. But lets think that I should configure it, so I do it and add to configuration:

```
oauth: { 
redirectSignIn: "localhost:3000",
domain: '***',
}
```

I am landing on:

![Screenshot 2020-10-29 at 01 08 20](https://user-images.githubusercontent.com/7830148/97509714-5573e180-1983-11eb-8a30-afb4a5663cab.png)

And I do not know why this error occur.

**Comment by elorzafe** [comment]
@Mskalba 

Are you trying to implement Cognito UserPools federation with HostedUI?

In that case you should configure Oauth section like is mentioned on [Re-use existing authentication resource](https://docs.amplify.aws/lib/auth/start/q/platform/js#re-use-existing-authentication-resource)
