### ISSUE TITLE
PubSub used in Angular does not receive messages when built with the prod flag (ng build --prod)

### ISSUE THREAD

**Issue by sravimohan** [aws-amplify/amplify-js#7085]
**Describe the bug**
PubSub used in Angular ("10.0.7") does not receive messages when built with the prod flag (**ng build --prod**).

**To Reproduce**
1. Create a angular application and configure PubSub with  AWS IoT Core MQTT.
2. build the application with the prod flag
    ng build --prod

**Expected behavior**
PubSub.subscribe should receive messages.

**Code Snippet**

      import { PubSub } from 'aws-amplify';
      ...
      PubSub.subscribe('xxx').subscribe({
        next: data => ...,
        error: error => console.error(error)
      });

**What is Configured?**
// https://github.com/aws-amplify/amplify-js/issues/5558
// import { AWSIoTProvider } from '@aws-amplify/pubsub/lib/Providers'; 
import { AWSIoTProvider } from '@aws-amplify/pubsub/lib/Providers/AWSIotProvider';
...
            
            Amplify.configure({
              Auth: {
                region: cognitoRegion,
                userPoolId: cognitoUserPoolId,
                userPoolWebClientId: cognitoUserPoolWebClientId,
                identityPoolId: identityPoolId,
                cookieStorage: {
                  domain: domain,
                  expires: 7,
                  secure: false
                },
              }
            });

            // MQTT
            Amplify.addPluggable(new AWSIoTProvider({
              aws_pubsub_region: cognitoRegion,
              aws_pubsub_endpoint: mqttEndpoint,
            }));

<details>
  <summary><strong>Environment</strong></summary>

  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 2.92 GB / 15.76 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE      
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (86.0.622.51)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @angular-devkit/build-angular: ~0.1000.7 => 0.1000.7  
    @angular/animations: ~10.0.11 => 10.0.11
    @angular/cdk: ^10.1.3 => 10.1.3
    @angular/cli: ~10.0.7 => 10.0.7
    @angular/common: ~10.0.11 => 10.0.11
    @angular/compiler: ~10.0.11 => 10.0.11
    @angular/compiler-cli: ~10.0.11 => 10.0.11
    @angular/core: ~10.0.11 => 10.0.11
    @angular/forms: ~10.0.11 => 10.0.11
    @angular/localize: ~10.0.11 => 10.0.11
    @angular/platform-browser: ~10.0.11 => 10.0.11
    @angular/platform-browser-dynamic: ~10.0.11 => 10.0.11
    @angular/router: ~10.0.11 => 10.0.11
    @aws-amplify/core: ^3.7.0 => 3.7.0
    @aws-amplify/ui-angular: ^0.4.7 => 0.4.7
    @fortawesome/fontawesome-free: ^5.15.0 => 5.15.1
    @ng-bootstrap/ng-bootstrap: ^7.0.0 => 7.0.0
    @types/jasmine: ~3.5.0 => 3.5.12
    @types/jasminewd2: ~2.0.3 => 2.0.8
    @types/node: ^12.11.1 => 12.12.54
    angular2-text-mask: ^9.0.0 => 9.0.0
    aws-amplify: ^3.3.4 => 3.3.4
    bootstrap: ^4.5.0 => 4.5.2
    codelyzer: ^6.0.0 => 6.0.0
    file-saver: ^2.0.2 => 2.0.2
    jasmine-core: ~3.5.0 => 3.5.0
    jasmine-spec-reporter: ~5.0.0 => 5.0.2
    karma: ~5.0.0 => 5.0.9
    karma-chrome-launcher: ~3.1.0 => 3.1.0
    karma-coverage-istanbul-reporter: ~3.0.2 => 3.0.3
    karma-jasmine: ~3.3.0 => 3.3.1
    karma-jasmine-html-reporter: ^1.5.0 => 1.5.4
    lodash: ^4.17.20 => 4.17.20
    lonsec-styles-common: ^1.0.9 => 1.0.9
    ngx-uploader: ^10.0.0 => 10.0.0
    primeflex: ^2.0.0-rc.1 => 2.0.0-rc.1
    primeicons: ^4.0.0 => 4.0.0
    primeng: ^10.0.0-rc.3 => 10.0.0-rc.3
    protractor: ~7.0.0 => 7.0.0
    rx-polling: ^1.1.0 => 1.1.0
    rxjs: ~6.5.5 => 6.5.5
    rxjs-operators: ^1.1.3 => 1.1.3
    text-mask-addons: ^3.8.0 => 3.8.0
    ts-node: ~8.3.0 => 8.3.0
    tslib: ^2.0.0 => 2.0.1
    tslint: ~6.1.0 => 6.1.3
    typescript: ~3.9.5 => 3.9.7
    zone.js: ~0.10.3 => 0.10.3
  npmGlobalPackages:
    @angular/cli: 10.1.3
    @aws-amplify/cli: 4.27.3
    http-server: 0.12.3
    npm: 6.14.8
    vsts-npm-auth: 0.41.0
</details>

**Additional context**
The same code works when built without "--prod" flag.

**Comment by elorzafe** [comment]
sravimohan@

Can you try doing this?

```javascript
import { AWSIoTProvider } from '@aws-amplify'
```

**Comment by sravimohan** [comment]
thank your for your response @elorzafe.  This does not seem to fix the issue for me.  

I notice, the websocket connection seems to get stuck at HTTP 101.

![image](https://user-images.githubusercontent.com/253584/97789477-e7dee400-1c14-11eb-826b-12a4d1c03585.png)

Is there any more details I can provide?

**Comment by sravimohan** [comment]
In addition to the above,  changing from **Amplify.addPluggable to PubSub.addPluggable** seems to fix the issue.

So I am guessing, "import Amplify from 'aws-amplify'" gets tree sharked?

working code:

 ```
import { AWSIoTProvider, PubSub } from '@aws-amplify/pubsub'
 ...

 PubSub.addPluggable(new AWSIoTProvider({
     aws_pubsub_region: cognitoRegion,
     aws_pubsub_endpoint: mqttEndpoint,
 }));

```

**Comment by sravimohan** [comment]
This issue seems to be back with the latest releases and the previous work  work  around do not work any more.

`    "@aws-amplify/auth": "^3.4.9",
    "@aws-amplify/core": "^3.8.1",
    "@aws-amplify/interactions": "^3.3.30",
    "@aws-amplify/pubsub": "^3.2.7",
    "@aws-amplify/storage": "^3.4.0",
    "@aws-amplify/ui-angular": "^1.0.7",`
  ...    

`import { AWSIoTProvider, PubSub } from '@aws-amplify/pubsub';

    // MQTT
    PubSub.addPluggable(new AWSIoTProvider({
      aws_pubsub_region: appConfigService.cognitoRegion,
      aws_pubsub_endpoint: appConfigService.mqttEndpoint,
    }));
`

**Comment by sammartinez** [comment]
Hey @sravimohan, sorry for the delay. This is correct that `aws-amplify` does tree shake on production builds. As you have found the working code, I am going to resolve this issue. Please let us know if this is not the case and we can reopen
