### ISSUE TITLE
API not found error

### ISSUE THREAD

**Issue by arunsai-mweb** [aws-amplify/amplify-js#7086]
Index.js:246 API "GetModelsFromAurora-API" does not exist

Amplify.configure(
  {
    API: {
      endpoints: [
        {
          name: "GetModelsFromAurora-API",
          endpoint: "https://xxxxxx.xxx.amazonaws.com/Sandbox"          
        }
      ]
    }
  });
const apiName = "GetModelsFromAurora-API"
const path = "/GetModelsFromAurora"
API
      .get(apiName, path, {})
      .then(response => {
      
}).catch(error=>{

})

I can access the API from postman but not able to access it from here.

**Comment by elorzafe** [comment]
@arunsai-mweb 

Can you share your `package.json`? 

Can you retry removing your `node_modules` directory and try a fresh install?
