### ISSUE TITLE
WithAuthenticator crashes in React 17

### ISSUE THREAD

**Issue by mcqj** [aws-amplify/amplify-js#7094]
**Describe the bug**
When upgrading an App from React 16 to React 17, `withAuthenticator` fails with the error:-

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

**To Reproduce**
Use WithAuthenticator in the usual way to wrap the React App and execute.
Login to your app - (I was using username/password with Cognito user)
Upon authentivation, the error appears. 

**Expected behavior**
No error

**Code Snippet**
Please provide a code snippet or a link to sample code of the issue you are experiencing to help us reproduce the issue. (Be sure to remove any sensitive data)

**Screenshots**

**What is Configured?**
Not using Amplfy CLI

**Additional context**
App works fine with React 16.13

**Comment by amhinson** [comment]
@mcqj Would you be able to share a code sample for the issue you are seeing? I am trying to replicate the error you're seeing with a brand new React app (`17.0.1`) wrapped in `withAuthenticator` but everything appears to be working as expected.

**Comment by mcqj** [comment]
@amhinson The app in which I am experiencing the problem is too large to share in and of itself. I will try to re-create the problem with a slimmed down app but it'll probably be a few days before I can get to it.

**Comment by amhinson** [comment]
That is perfectly fine! Thanks @mcqj 🙂

**Comment by mcqj** [comment]
Finally had time to create a stripped back version of the App and the problem is not there when I striped away other packages. So, I'll have to do more analysis but it looks like the issue is not with Amplfy.
I'm happy enough for the issue to be closed.

**Comment by c0** [comment]
I was able to recreate this when combining `withAuthenticator` with `withUrqlClient` (this is a Next.js app). `withAuthenticator` has to be on the inside and not the outside.

**Produces the error:**
```js
export default withAuthenticator(
  withUrqlClient((ssrExchange, ctx) => (
    urqlOptions(ssrExchange)
  ))
)(App)
```

**No error:**
```js
export default withUrqlClient((ssrExchange, ctx) => (
  urqlOptions(ssrExchange)
))(
  withAuthenticator(App)
)
```
