### ISSUE TITLE
Ability to remove an AWSIoTProvider pluggable or change the endpoint after calling addPluggable?

### ISSUE THREAD

**Issue by matwerber1** [aws-amplify/amplify-js#7103]
**Is your feature request related to a problem? Please describe.**

I'm creating an AWS IoT message tester, similar to what you get in the AWS IoT web console.

I am configuring with an IoT pluggable, per below:

```js
Amplify.addPluggable(new AWSIoTProvider({
      aws_pubsub_region: region,
      aws_pubsub_endpoint: endpoint,
    }));  
  }
```

I would like the ability to populate `region` and `endpoint` based on form input. This is easy enough... however, I also want the user to be able to change the endpoint and region. That's where it gets tricky.

I can call `addPluggable` again, which seems to work... but it still leaves the old provider there.. and subsequent `Pubsub.publish()` commands publish to both the old and new provider. 

It doesn't seem like there's a way to change the existing (old) provider endpoint, nor is there a way to remove the old provider when I add the new one.

**Describe the solution you'd like**

I'd like to either (a) change the IoT endpoint of a previously configured AWSIoTProvider pluggable, or (b) remove a pluggable that was previously added via `Amplify.addPlugable()` (so that I can re-add a new one).

**Describe alternatives you've considered**

**Additional context**
Add any other context, an idea of the implementation or screenshots about the feature request here.

**Comment by zacharyrogers1** [comment]
@matwerber1 I took a shot at this and created a PubSub.removePluggable() function to be able to remove and add providers as needed. This should work for being able to change region, endpoint, etc as needed.

**Comment by david-mcafee** [comment]
[The PR](https://github.com/aws-amplify/amplify-js/pull/7256) for this has been merged, closing this ticket. Thanks again, @zacharyrogers1!
