### ISSUE TITLE
React 17 support for ui-react

### ISSUE THREAD

**Issue by ankon** [aws-amplify/amplify-js#7105]
**Is your feature request related to a problem? Please describe.**

Right now @aws-amplify/ui-react (0.2.27) requires react ^16.7.0 as peer dependency. React 17.0.1 has been released recently, so when updating one now gets unmet peer dependency warnings from npm.

**Describe the solution you'd like**

Support, and declare support for React 17 by updating the peer dependency declaration.

**Describe alternatives you've considered**

I'm going to ignore the warning for now, and will see whether things work.

Note that there is #7094 filed that seems to indicate potential issues with React 17.

**Additional context**

See the release notes: https://reactjs.org/blog/2020/10/20/react-v17.html

**Comment by burntsugar** [comment]
I am trying to resolve same - did ignoring the warning work for you @ankon ?

**Comment by amlcodes** [comment]
Ignoring it so far, but running into auth "configured incorrectly"

**Comment by wei** [comment]
@amlcodes Please make sure both all amplify related packages are at latest:
```
yarn add aws-amplify@latest
yarn add @aws-amplify/ui-react@latest  # or any other amplify ui component package
```

https://github.com/aws-amplify/amplify-js/discussions/5836#discussioncomment-123904

**Comment by kingferiol** [comment]
Hi all, any news here? Experimenting the same here.

**Comment by nilooy** [comment]
it's not working with `npm i @aws-amplify/ui-react@latest`

> Error on react 17: peer react@"^16.7.0" from @aws-amplify/ui-react@0.2.33

**Comment by djmittens** [comment]
whats the status on this? seems like its time to upgrade.

**Comment by thedaviddias** [comment]
Same problem here. Any workaround?

**Comment by Aggiemaster** [comment]
Ran into the same issue running the Amplify tutorial with react since it starts with the latest react version 17.0.1

**Comment by Temez1** [comment]
> Same problem here. Any workaround?

I guess you can install with `--legacy-peer-deps` to "[ignore all peerDependencies when installing](https://docs.npmjs.com/cli/v7/commands/npm-install#configuration-options-affecting-dependency-resolution-and-tree-design). I did that to do one short tutorial and withAuthenticator worked.

**Comment by thedaviddias** [comment]
> > Same problem here. Any workaround?
> 
> I guess you can install with `--legacy-peer-deps` to "[ignore all peerDependencies when installing](https://docs.npmjs.com/cli/v7/commands/npm-install#configuration-options-affecting-dependency-resolution-and-tree-design)". I did that to do one short tutorial and withAuthenticator worked.

Oh nice, I forgot about that. That should solve the issue. Thanks @Temez1!

**Comment by ericclemmons** [comment]
Closing, as https://github.com/aws-amplify/amplify-js/pull/7718 (via `v1.0.1`) should resolve this duplication issue.

To install the latest version of `@aws-amplify/ui-react`, for example:
```shell
npm install aws-amplify @aws-amplify/ui-react
# or
yarn add aws-amplify @aws-amplify/ui-react
```

React 17 is supported as a peerDependency now!

Let us know if you experience any issues! 🙏
