### ISSUE TITLE
AWS Cognito SignIn() function won't work because of Expo

### ISSUE THREAD

**Issue by Anybowdy** [aws-amplify/amplify-js#7112]
I am currently working on a project using AWS Amplify and I use Cognito for users authentification.
I added the Signup and signin feature few weeks ago, everything worked well.
Yesterday, I tried to signUp again with an existing account but the Auth.signin() function would instantly crash.
There is no reason why this wont work. It just suddenly stopped working.

**Screenshots**
![stack](https://user-images.githubusercontent.com/36242531/98040814-395bbe80-1e21-11eb-8596-0e3d47c2886d.JPG)

**Comment by amhinson** [comment]
@Anybowdy What version of Expo are you using? Could you try updating to the latest version?

**Comment by Anybowdy** [comment]
> @Anybowdy What version of Expo are you using? Could you try updating to the latest version?

I am using expo 3.28.2, I already tried to update etc... not working. A friend who has the same expo version does not have that error

**Comment by amhinson** [comment]
The error you're seeing should be fixed for Expo SDK 39. Could you try upgrading? Here's [Expo upgrade guide](https://dev.to/expo/expo-sdk-39-is-now-available-1lm8). I've just created a new Expo app with SDK 39 with Amplify Auth and it appears to working as expected.

If you're still seeing the error after that, would you be able to provide a small sample repo that shows the behavior you're seeing?

**Comment by Anybowdy** [comment]
I went through a lot of pb but an expo upgrade worked. Thank you

**Comment by amhinson** [comment]
Ok glad you were able to get it figured out @Anybowdy 👍
