### ISSUE TITLE
Datastore finding the latest record of each userId scenario

### ISSUE THREAD

**Issue by mchitson** [aws-amplify/amplify-js#7125]
hello i have a question about Datastore and syncing to/from the cloud:
i have this scenario:
i have 100s of users
and my app needs to know the latest status of each user
and the status is updated pretty frequently, meaning we can have up to 100s of status for each user
i need to find latest for each on loading my app
i was reading that datastore sync's only 100 items and paginates up to a 1000 items.

Does that mean:
1.That i will have not the latest updates for all users when i do a query? because the users who have not updated recently fall out of the 1000 item?
2. how does this impact subscriptions? Does that that the users that fall out of 1000 item, my app will never get subscriptions or missed subscriptions (due to offline) for those users that are not in the local datastore?

I can not also just have a userId as an ID! because i need a meaningful id so my model will look like:

type userStatus @model {
  id: ID!
  userId : String!
  status: String!
  time: AWSDateTime!
}

**Comment by iartemiev** [comment]
Hey @mchitson, by default DataStore syncs down 10,000 items per model with a page size of 1000. This means that if the DynamoDB table for your model contains 10k items, the base sync will execute 10 queries, each returning 1k items, with which it will populate the local store. 

You can override those values by using `DataStore.configure`:
```js
DataStore.configure({
  maxRecordsToSync: 30000,
  syncPageSize: 3000
});
```

If you're using authorization in your app, e.g. [owner authorization](https://docs.amplify.aws/cli/graphql-transformer/auth#owner-authorization), DataStore will only sync down items that the logged-in user is authorized to access.

You can also use [this feature](https://docs.amplify.aws/lib/datastore/sync/q/platform/js#selective-sync) to limit the data set being persisted to your local store. Otherwise, the entire contents of the table will be saved locally up to the `maxRecordsToSync` value.

If you've reached `maxRecordsToSync` items in your local store for a model, DataStore will still accept new incoming records, whether they're coming in via the delta sync or subscriptions.

**Comment by mchitson** [comment]
Hi Ivan

Thanks. However unless am missing something, this does not answer my question as to how do I guarantee that I can get the latest updated status for every userId in the db via query? I won’t know if setting the maxRecord to 30k is sufficient. I tried to use the default id (key) so that I have only one row per unique id of the status (I just update on same id each time), but I am not able to force generate my own id, seems datastore generates a UUID instead. And I really need to map to a meaningful userid. This is an issue and a non starter for me. Surely this is a very common scenario?

**Comment by iartemiev** [comment]
If I understand your question correctly, you can query userStatus by the `userId` and sort by `time`:
```js
const [latestStatus] = await DataStore.query(
  userStatus,
  (c) => c.userId('eq', 'some-id'),
  { sort: (s) => s.time(SortDirection.DESC) }
);
```

You are correct that you cannot set your own id field in DataStore at the moment.

**Comment by mchitson** [comment]
But this operates against the local query? Will this work if I have userId’s that have not been loading in the first 30k items?

**Comment by iartemiev** [comment]
Yes, all DataStore operations are performed against the local store. You can set the `maxRecordsToSync` value higher than 30k. 
Alternatively, if you'd like to query AppSync directly, you can access this model using the API category instead of DataStore.

**Comment by mchitson** [comment]
Thanks. I wanted to use Datastore because it has a better resilience when there’s spotty internet and a device goes offline often. I found a work around where I query the datastore with my userId and then update against the id from the returned object so it keeps only 1 record per userId. Not ideal but it works.

I have another question though, I am also subscribing to events and want to receive updates that belong to only one event (in this case I want to keep a record of all events and not overwrite over them as above). In direct appsync we just use filters. What’s the solution with datastore? I am trying to use SyncExpression but it doesn’t seem to work for subscriptions? Am still getting subscription updates from over events.

**Comment by mchitson** [comment]
Sync Expresion am using:

import { DataStore, SortDirection, syncExpression } from "@aws-amplify/datastore";
DataStore.configure({
  syncExpressions: [
    syncExpression(Events,  (c) => eventId('eq', '95596167100'))
  ]
});


Doesn’t seem to filter either queries or subscriptions

**Comment by iartemiev** [comment]
>  I wanted to use Datastore because it has a better resilience when there’s spotty internet and a device goes offline often
You can use DataStore and API together if needed. E.g., you can use DataStore for models that you'd like to persist locally and API for others.

The sync expression applies predicates to the sync query that populates the local store. If you already have data in your local store you should clear it first with `DataStore.clear()`.

**Comment by nubpro** [comment]
> > I wanted to use Datastore because it has a better resilience when there’s spotty internet and a device goes offline often
> 
> You can use DataStore and API together if needed. E.g., you can use DataStore for models that you'd like to persist locally and API for others.
> 
> The sync expression applies predicates to the sync query that populates the local store. If you already have data in your local store you should clear it first with `DataStore.clear()`.

Side track, wouldn't calling `DataStore.clear()` remove any pending mutations still in the outbox?

**Comment by mchitson** [comment]
So it’s not possible currently to just subscribe to a particular value of an attribute via datastore ? (Subscribing to just id does not work for my current use case). Could we please have subscription filtering with datastore as we have with current appsync ?

**Comment by mchitson** [comment]
Hey Ivan

So i tried your suggestion and am using datastore for subscriptions that i need persisting and then direct graphql API for subscriptions that i don't need persisting and pass in a parameter (eventId) to subscribe to just that eventId. however it seems my app is still getting packets related to other events even tho i receive on the call back only the eventId. i don't really want the app for a particular user to get flooded by other packets even tho only his/her event filters through. it seems somehow the datastore observer is interfering with appsync filtering. I did a seperate test with another appsync api with same schema but no sync/no datastore and it seems to filter correctly. is the issue here the delta sync or is it datastore observer?

**Comment by mchitson** [comment]
Here are some debug messages for above issue:

The message below seems to imply that i am subscribing only to subscriptions for meetingId 95596167100:

DEBUG] 25:11.835 AWSAppSyncRealTimeProvider - subscription ready for {"query":"subscription onCreateEvents($meetingId: String) {\n  onCreateEvents(meetingId: $meetingId) {\n    id\n    meetingId\n    createdAt\n    event\n    data\n    _version\n    _deleted\n    _lastChangedAt\n    updatedAt\n  }\n}\n","variables":{"meetingId":"95596167100"}}


however i still see those messages in the debugger for a different meeting id 98305866706 :

DEBUG] 38:18.484 AWSAppSyncRealTimeProvider - subscription message from AWS AppSync RealTime: {"id":"e7a2098c-fc7e-4f6e-95c7-798e2cad6b82","type":"data","payload":{"data":{"onCreateEvents":{"id":"712d2122-7aa8-411c-a6ea-bce4b240aedf","meetingId":"98305866706","createdAt":"2020-11-06T13:38:18.043Z","event":"meeting.ended"}


why am i still receiving subscriptions for other meetingId? that doesn't seem to happen with no deltasync/datastore api.

**Comment by iartemiev** [comment]
API and DataStore function independently. If you're passing a parameter to a subscription you're initiating with the API category, that's not going to apply to DataStore subscriptions.

You can turn off syncing for that model completely by setting the `syncable` property to `false` for that model in ./models/schema.js. You will need to do that each time after running `amplify codegen models`. In the future we'll be adding a way to specify this more easily.

Or you can use selective sync on that model and pass a predicate that matches the parameter you're passing in your API subscription. This will apply the filter to the sync query and it will filter inbound subscriptions clientside on that predicate. So you will still see those subscriptions coming in in the debug statements, but they won't actually get persisted to the local store.

**Comment by mchitson** [comment]
So then why am I still getting subscriptions for other id’s that I did not subscribe for? (Am using subscription to API). Is sync the issue there (I would imagine not)? 
My schema is as follows and yet am still receiving subscriptions for other ids. Can I have an answer specific to this issue please? Thank you. See the debug messages I sent earlier.

export const onCreateEvents = /* GraphQL */ `
  subscription OnCreateEvents($meetingId: String) {
    onCreateEvents(meetingId: $meetingId) {
      id
      meetingId
      createdAt
      event
      data
      _version
      _deleted
      _lastChangedAt
      updatedAt
    }
  }
`;

**Comment by iartemiev** [comment]
As I tried to explain in my last comment, if this model is also being synced by DataStore, then by default, you will see all subscriptions coming in.

**Comment by mchitson** [comment]
Ah ok, turning off sync for that particular model worked, now I get only what I subscribed for. Thanks!

To continue with this thread though, would it be possible to have the datastore observe also filter on the backend side, rather than getting all subscriptions and the sync filtering only on the client side to the datastore? Just from a latency and network capacity point of view. The client side can decide on which option.

**Comment by iartemiev** [comment]
Nice! Glad that's working.

I'm definitely happy to look into that. Off the top of my head, when developers specify sync expressions that use the `eq` operator, we should be able to pass that to the subscription as a subscription argument. Any additional filters would still need to be applied clientside, since AppSync currently does not support filters.

Here's an example of how this could work. 

If you have the following sync expression

```js
syncExpression(Events, (c) =>
  c. meetingId('eq', 'some-value').createdAt('gt', '2020-11-01')
),
```

DataStore will initiate this subscription:

```graphql
onCreateEvents(meetingId: 'some-value') {
  id
  meetingId
  createdAt
  event
  data
  _version
  _deleted
  _lastChangedAt
  updatedAt
}
```

And then when the subscription messages come in, we apply the `createdAt('gt', '2020-11-01')` predicate clientside before persisting to the local store.

Do you feel like this would address your use case accordingly?

**Comment by mchitson** [comment]
Yes that would work! So just to make sure I understand only subscriptions belonging to ’some-value’ will come down the network to the app. Then datastore applies the additional filter createdAt(‘gt’, ‘2020-11-01’)? I think that works!

**Comment by iartemiev** [comment]
Yep, that's exactly right. 

I'm going to mark this as a feature request and will work on adding this functionality in the near future.

**Comment by mchitson** [comment]
Great! Thanks Ivan! Where should I look to see when this feature comes online ?

**Comment by iartemiev** [comment]
We will post any developments for the feature in this issue

**Comment by mchitson** [comment]
Fantastic! Thank you very much !! And thanks for the help and patience!

**Comment by mchitson** [comment]
Hey Ivan

Sorry i posted a few things on github, to reprise this thread, i set one model to syncable:false and just do the subscription directly via API. It seems however it is now less resilient than if i didn't use a hybrid datastore and direct API, it seems if i turn off my wifi to test offline, datastore seems to cause all websockets to close. When i turn back online, the datastore model recovers (as it should) but the API one is forever closed.

**Comment by mir1198yusuf** [comment]
Hello  @iartemiev , considering above syncExpression 
```
syncExpression(Events, (c) =>
  c.meetingId('eq', 'some-value').createdAt('gt', '2020-11-01')
)
```

Suppose i have a list displaying Events , by above expression only events created after 2020-11-01 will be stored in client-side database.

Now if user keeps scrolling up and suddenly wants to see an event records before 2020-11-01 or the very first oldest event, that data would not be available in client-side.

So how to inform Datastore to sync these older records with backend and display it, because `Datastore.query` returns only data from client-side .

Also` maxRecordsToSync` would not help as we dont know in advance the number of older records.

**Comment by chrisbonifacio** [comment]
Closing this as the original issue seems to have been addressed and a resolution was found. In regards to the last comment, the API library does not yet automatically reconnect websockets/subscriptions similarly to DataStore and is a feature request.
