### ISSUE TITLE
Datastore connection close/timeout disconnect

### ISSUE THREAD

**Issue by mchitson** [aws-amplify/amplify-js#7126]
Hello am reading in various places that datastore with appsync as backend is supposed to recover subscriptions when a device goes offline.
In the case of the device on which my web app is running goes offline for more than 5 minutes (> Keep alive connection), appsync subscription has a timeout disconnect. Does datastore try to restore the connection in that case? If not, is there away to have datastore restart the connection via datastore api?

**Comment by nubpro** [comment]
As soon as your device suffered a short period internet connection (lets say 1 second), the subscriptions will break immediately.

However, PubSub will only detect this 5 minutes later. Timeout disconnect will be thrown and DataStore will attempt to recover the subscriptions.

https://github.com/aws-amplify/amplify-js/blob/8b3183f4d2ec7289044e2b6700e3ff4df3f98ce4/packages/datastore/src/sync/index.ts#L663

>If not, is there away to have datastore restart the connection via datastore api?
Yes but actually no. You could try calling `DataStore.clear()` and followed by `DataStore.start()`. However, doing so, any mutations still on the outbox will be immediately vanished. So this isn't a good idea at all.

**Comment by amhinson** [comment]
@mchitson Does @nubpro's answer give you what you're looking for? We will continue to track the resiliency of DataStore with regards to timeout and handshake errors in this issue: https://github.com/aws-amplify/amplify-js/issues/6488
