### ISSUE TITLE
ConsoleLogger.ts:99 [WARN] 25:02.663 DataStore - Data won't be synchronized. No GraphQL endpoint configured. Did you forget `Amplify.configure(awsconfig)`?

### ISSUE THREAD

**Issue by mchitson** [aws-amplify/amplify-js#7137]
Hi out of the blue am getting this warning:

ConsoleLogger.ts:99 [WARN] 25:02.663 DataStore - Data won't be synchronized. No GraphQL endpoint configured. Did you forget `Amplify.configure(awsconfig)`? {config: {…}}

am using IAM for the appsync/datastore and configuring this way:

Amplify.configure({
  Auth: {
    identityPoolId: awsconfig.aws_cognito_identity_pool_id,
    region: awsconfig.aws_cognito_region ,
    userPoolId: awsconfig.aws_user_pools_id,
    userPoolWebClientId: awsconfig.aws_user_pools_web_client_id
  },
  aws_project_region: awsconfig.aws_project_region,
  aws_appsync_graphqlEndpoint: awsconfig.aws_appsync_graphqlEndpoint,
  aws_appsync_region: awsconfig.aws_appsync_region,
  aws_appsync_authenticationType: awsconfig.aws_appsync_authenticationType
});

this was working fine before, i created a new datastore and now it's throwing up.

**Comment by sw-yx** [comment]
what was the fix?

**Comment by rahulnainwal** [comment]
Why this issue been close without even having a solution, i am also getting the same issue even though i have added **Amplify.configure(aws_exports)** in my root file App.js.
 **DataStore - Data won't be synchronized. No GraphQL endpoint configured. Did you forget `Amplify.configure(awsconfig)`?**

**Comment by BenjaminWatts** [comment]
I have the same issue

**Comment by reberthkss** [comment]
+1

**Comment by apolat2000** [comment]
+1
