### ISSUE TITLE
Datastore send a lot of replayed subscriptions on start up

### ISSUE THREAD

**Issue by mchitson** [aws-amplify/amplify-js#7138]
Hello 

I am having a lot of issues with DataStore:
1. When i login into my website, for some odd reason i get a whole bunch of subscriptions that had already happened before (my app did not miss them by being offline or otherwise). Why does this happen and can we turn this off? Because it's confusing and comes out of order as well.
2. I am trying SyncExpressions, as Ivan suggested before and i thought it worked i set my object schema to sync false so that i receive only subscriptions as predicated by SyncExpressions. however i actually receive NO subscriptions whatsoever.
3. When i login as another user and try to change the syncExpression at runtime, i do not get any subscriptions predicated by that sync expression.

I am doing this:

let MEETING_ID = '0';
DataStore.configure({
  syncExpressions: [
    syncExpression(Events,  (c) => c.meetingId('eq', MEETING_ID))
  ]
});

class Services { 

changeSync = async(meetingId) => {
    try {
      console.log('ChangeSync : changing syncExpression');
      MEETING_ID = meetingId;
      await DataStore.stop();
      await DataStore.start();
    } catch (e) {
      console.log('changeSync: ', e);
    }
  }

subscribeEvents = async(meetingId) => {
    try  {
      this.changeSync(meetingId);
      this.zoomSubscription = DataStore.observe(Events).subscribe(msg => {
        console.log(msg.element);
      });
    }
    catch (e) {
      console.log("error in graphQL: ", e) 
    }
  }

can i get some help here? it seems moving to datastore has opened another can of worms for me.

**Comment by mchitson** [comment]
secondly if i set one model to             "syncable": false,
as per Ivan's earlier recommendation, it seems ALL modals are affected and do not return subscriptions to the app even though i can see the packets arriving.

**Comment by mchitson** [comment]
One more issue, when i don't explicitly subscribe to a model i.e i don't call Datastore.observe(...) i STILL see packets coming down the wire for that model. How can that be? surely if we're not subscribing to a model we shouldn't get subscriptions for it? (even if not sync'ed to datastore).

**Comment by mchitson** [comment]
Also one more thing, the Events DB is populated by a lambda webhook listener that saves the events via AppSync API directly. Is this why datastore is confused by those events that had been added a while ago? It sends OPTYPE update.

**Comment by iartemiev** [comment]
Calling `DataStore.observe` is not what creates the subscriptions. It's simply the mechanism for receiving mutation notifications on the client. 

DataStore relies on AppSync subscriptions to keep your local store in sync with the cloud. So it will create a subscription behind the scenes for each of your models.

**Comment by mchitson** [comment]
I think there should definitely be ability to subscribe to only one id as per what appsync does. At this point I can not use datastore as is.

**Comment by iartemiev** [comment]
If you flip the `syncable` value to `false` in the generated models, that will disable syncing for those models and prevent any subscriptions from getting initiated for them.

We will be adding the ability to pass equality predicates to subscriptions as we discussed [in this issue](https://github.com/aws-amplify/amplify-js/issues/7125#issuecomment-723132997)
