### ISSUE TITLE
 Datastore - Constructor is not for a valid model, object {"modelconstructor": ""

### ISSUE THREAD

**Issue by rpostulart** [aws-amplify/amplify-js#7140]
When you don't start you schema models with a capital you will end up with these errors when using aws amplify datastore    

`Datastore - Constructor is not for a valid model, object {"modelconstructor": ""}`

**Comment by harrysolovay** [comment]
I was unable to repro––not sure if your error is the result of capitalization, or something else entirely. Can you please share more context?

Side-note: while it's not in [the 2018 spec](http://spec.graphql.org/June2018/), it is common practice to treat certain GQL type definitions with certain casings / prefixing.

- `MyType`
- `MY_ENUM_VALUE`
- `InputMyType`

**Comment by rpostulart** [comment]
Mmmh, I also changed to model now to a capital and noticed after that, that is works fine.
But if your can't reproduce, then I will close it.

Thx
