### ISSUE TITLE
Local storage is missing an ID Token, Please authenticate - Backend implementation

### ISSUE THREAD

**Issue by Benzer1406** [aws-amplify/amplify-js#7141]
I use `aws-cognito-identity-js` in a backend with lambda functions and api gateway. I basically want to manage the authentication in my own backend through lambda functions (I'm not doing it in the frontend app).

I could successfully implement methods like `login`, `signUp`, `verifyUser`,.

But when trying to use `changePassword` I have the challenge that the user is not authenticated because every lambda function is a new instance. So I call `getSession(....)` trying to get the userSession in order then to call `cognitoUser.changePassword(...)`.

I use the email to get the cognitoUser like that: 

```
export const getCognitoUser = (email) => {
    const userData = {
        Username: email,
        Pool: getUserPool()
    };
    return new AmazonCognitoIdentity.CognitoUser(userData);
```

Here's the cognitoUser I get:

`CognitoUser {
  username: 'email@gmail.com',
  pool:
   CognitoUserPool {
     userPoolId: 'us-east-asdfasdfasdfasdfasdfasdf',
     clientId: '1111111111asdfadsfasdfasdfasdfasdf',
     client:
      Client {
        endpoint: 'https://cognito-idp.us-east-1.amazonaws.com/',
        fetchOptions: {} },
     advancedSecurityDataCollectionFlag: true,
     storage:
      { [Function: MemoryStorage]
        setItem: [Function: setItem],
        getItem: [Function: getItem],
        removeItem: [Function: removeItem],
        clear: [Function: clear] } },
  Session: null,
  client:
   Client {
     endpoint: 'https://cognito-idp.us-east-1.amazonaws.com/',
     fetchOptions: {} },
  signInUserSession: null,
  authenticationFlowType: 'USER_SRP_AUTH',
  storage:
   { [Function: MemoryStorage]
     setItem: [Function: setItem],
     getItem: [Function: getItem],
     removeItem: [Function: removeItem],
     clear: [Function: clear] },
  keyPrefix: 'CognitoIdentityServiceProvider.asdfasdfasdfasdfasdf',
  userDataKey:
   'asdfasdfasdfasdf' }`

But when I then call `getSession` I always get this error 
`Error in getCognitoUserSession  Error: Local storage is missing an ID Token, Please authenticate
    at CognitoUser.getSession (path/node_modules/amazon-cognito-identity-js/lib/CognitoUser.js:1333:16)`

I understand that AWS-Amplify is primarily thought to be used in the frontend app, but I suppose it should be possible to use it on the backend without any issue?! Any idea?

**Comment by harrysolovay** [comment]
@Benzer1406 this is not a use case for which we account; if you wish to interact with the Cognito service from a Lambda, I highly recommend making direct use of the [`@aws-sdk/client-cognito-identity`](https://www.npmjs.com/package/@aws-sdk/client-cognito-identity) package. Otherwise, you'll subject your Lambda to manage back-end-irrelevant state.

Is there a particular reason that you have `@aws-amplify/auth`'s usage in a Lambda?

**Comment by Benzer1406** [comment]
@harrysolovay You're absolutely right, using the low-level aws-sdk works perfectly. The thing is that in the beginning in can be confusing as AWS always redirects to AWS-Amplify. But no notice that it is only meant for the frontend. I had to hit the wall to realize that it's not thought for lambda use. Thanks for your help!
