### ISSUE TITLE
Datastore SyncExpressions - i do not get any subsequent subscriptions

### ISSUE THREAD

**Issue by mchitson** [aws-amplify/amplify-js#7144]
Hi i am trying to use SyncExpressions to only sync subscriptions that i need, for eg by EventId. I have 2 models, when i do:

DataStore.configure({
        syncExpressions: [
          syncExpression(Events, () => {
            return (c) => c.meetingId('eq', meetingId)
          })
        ]
      });     

I get some previous missed out sync's:

[DEBUG] 23:30.34 Hub - Dispatching to datastore with  {event: "modelSynced", data: {…}}
Listener.js:10 Datastore Listener: Model synced: {"isFullSync":false,"isDeltaSync":true,"counts":{"new":0,"updated":2,"deleted":0}}
ConsoleLogger.ts:99 [DEBUG] 23:30.100 Hub - Dispatching to datastore with  {event: "modelSynced", data: {…}}
Listener.js:10 Datastore Listener: Model synced: {"isFullSync":true,"isDeltaSync":false,"counts":{"new":4,"updated":113,"deleted":0}}
ConsoleLogger.ts:99 

BUT then get NO new subsequent subscription messages whatsoever for BOTH models. Any ideas why?

**Comment by mchitson** [comment]
And just to be clear mutations on either models doesn't seem to leave the local store either. this is becoming extremely frustrating right now.

**Comment by mchitson** [comment]
correction i am able to continue mutating and getting subscriptions on the model with no SyncExpressions. however for the one with syncexpression i no longer seem to be a able to sync anything to/from the cloud

**Comment by mchitson** [comment]
more problems, when i logout and login as different user, am getting this issue:

DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

???????

**Comment by mchitson** [comment]
Just to be clear this is when am trying to do a syncExpression at runtime. Datastore does not seem to pick up the change

**Comment by mchitson** [comment]
it is also quite ridiculous if i am not subscribing via observe to a model,  i still get my datastore populated!!! this is a disaster.

**Comment by iartemiev** [comment]
What steps are you taking to have the expression reevaluated at runtime?

**Comment by mchitson** [comment]
I do this at the start (outside any class):


let MEETING_ID = null;
DataStore.configure({
  syncExpressions: [
    syncExpression(Events, () => {
      if (MEETING_ID) {
        return (c) => c.meetingId('eq', MEETING_ID);
      }
      return Predicates.ALL;
    })
  ]
});



And then in the function just before I ’subscribe’ via observe:


 console.log('Subscribing to events.');
    try  {
      await this.changeSync(meetingId); //Piece of shit does not work
      this.subscription = DataStore.observe(Events).subscribe(msg => {
	…...
      });
    }
    catch (e) {
      console.log("error in graphQL: ", e) 
    }


changeSync = async(meetingId) => {
    try {
  
      MEETING_ID = meetingId;
      await DataStore.stop();
      await DataStore.start();
    } catch (e) {
      console.log('changeSync: ', e);
    }
  }

**Comment by iartemiev** [comment]
Since you're applying a more restrictive filter when going from `Predicates.ALL` (all results) to filtering on an id, you would need to use `DataStore.clear()` instead of `DataStore.stop()` to remove any existing entries. If you go with that approach, you'll also need to reestablish the subscription.

For example:
```js
changeSync = async (meetingId) => {
  try {
    MEETING_ID = meetingId;
    await DataStore.clear();
    await DataStore.start();
    this.subscription = DataStore.observe(Events).subscribe((msg) => {
      ...
    });
  } catch (e) {
    console.log('changeSync: ', e);
  }
};
```

**Comment by mchitson** [comment]
What is the difference between that and the code I had? I call observe after await changeSync as per below and what I pasted:

    try  {
      await this.changeSync(meetingId);
      this.subscription = DataStore.observe(Events).subscribe(msg => {
	…...
      });
    }
    catch (e) {
      console.log("error in graphQL: ", e)
    }

**Comment by iartemiev** [comment]
That's fine. I was mainly talking about using `DataStore.clear` instead of `DataStore.stop` since you're narrowing the filter.

**Comment by mchitson** [comment]
That’s not solving my issue that after I do that, I do not get ANY subscriptions coming up the observe callback.

**Comment by iartemiev** [comment]
I've created a sample app that demonstrates this working successfully: https://github.com/iartemiev/selective-sync-sample. Could you please let me know what you are doing differently?

[Here's a video](https://www.amazon.com/clouddrive/share/OWomuadCZClrnitrK24xbXgglWeQrBrQj5mgrnqdnF5/oGWpYILGRC-2Gi1jfnwhQQ?_encoding=UTF8&*Version*=1&*entries*=0&mgh=1) of my running the app on 2 browsers side-by-side (Firefox and Chrome). I apply a sync filter to the app in one browser, then create additional records in the other one. The mutations come in successfully via subscriptions (seen in the console and the UI).

**Comment by mchitson** [comment]
Thanks I will give it a try. The only difference is that I subscribe once after changing sync expression as opposed to initial subscribe with predicate all and then subscribe again after sync expression change.

Secondly I use amplify along with amplify/datastore. I don’t know if that’s an issue but it’s all latest versions.

**Comment by mchitson** [comment]
Also one more thing it seems on computers with spotty connection datastore falls over on handshakes.

**Comment by iartemiev** [comment]
> Secondly I use amplify along with amplify/datastore. I don’t know if that’s an issue but it’s all latest versions.

I would not recommend explicitly installing both `aws-amplify` and `@aws-amplify/datastore`. That can lead to conflicts between the dependencies and result in unexpected behavior.

You can still import from `@aws-amplify/datastore` if you just have `aws-amplify` installed.

Try the following:
```bash
```

**Comment by xsmcemmons** [comment]
Hi, Using syncExpressions, i get this error on the code:..

![image](https://user-images.githubusercontent.com/63744088/99442944-dbd37180-28f8-11eb-957c-af8ea4716316.png)

I'm using the same  code given in  the documentation:

![image](https://user-images.githubusercontent.com/63744088/99443050-06bdc580-28f9-11eb-8509-8359ba93abbd.png)

Should I open another Issue for this one?

**Comment by iartemiev** [comment]
@xsmcemmons yes, please open a new issue
