### ISSUE TITLE
Datastore gets into an inconsistent state when browser history refreshed.

### ISSUE THREAD

**Issue by mchitson** [aws-amplify/amplify-js#7150]
I am getting this error when browser history refreshed. this is something that's bound to happen pretty frequently and am getting this error:

Unhandled Rejection (NotFoundError): Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.

Why doesn't datastore recover from there? Events doesn't help because it only tells me if the datastore is ready not when it's wiped out.

**Comment by mchitson** [comment]
this is a more detailed error:

Unhandled Rejection (InvalidStateError): Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
▼ 8 stack frames were expanded.
(anonymous function)
node_modules/idb/build/esm/wrap-idb-value.js:150
_callee$
node_modules/idb/build/esm/index.js:65
tryCatch
node_modules/regenerator-runtime/runtime.js:45
invoke
node_modules/regenerator-runtime/runtime.js:274
asyncGeneratorStep
node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3
_next
node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25
(anonymous function)
node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:32
(anonymous function)
node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:21
▲ 8 stack frames were expanded.
(anonymous function)
src/storage/adapter/IndexedDBAdapter.ts:397
  394 |     }
  395 |     tx = this.db.transaction(__spread(connectionStoreNames), 'readonly');
  396 |     _e.label = 1;
> 397 | case 1:
      | ^  398 |     _e.trys.push([1, 34, 35, 40]);
  399 |     relations_1 = __asyncValues(relations);
  400 |     _e.label = 2;
View compiled
▼ 2 stack frames were expanded.
step
http://localhost:3001/static/js/1.chunk.js:95055:23
fulfilled
http://localhost:3001/static/js/1.chunk.js:94939:28
▲ 2 stack frames were expanded.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to

**Comment by amhinson** [comment]
@mchitson Would you be able to provide some more reproduction steps to get the error you're seeing? I'm trying to reproduce it but I haven't come across the particular issue you're seeing so far.

**Comment by mchitson** [comment]
Open 2 different browsers (chrome and safari, so that one keeps it’s datastore), with mutations and subscriptions.

From one browser clear all the cache (clear history all time in safari for eg), then from the browser that was not cleared do a mutation. The subscription will cause the app with cleared cache to crash with the error above.

**Comment by amhinson** [comment]
Ok thanks for the additional info @mchitson! I was able to reproduce the error you are seeing. I'm going to look more into how we can improve the error handling around indexedDB. Just curious, what is your expected outcome here in how you would want DataStore to handle this scenario? I see you are asking if DataStore can recover from this, but what do you mean by "recover"?

**Comment by mchitson** [comment]
So instead of just throwing the error and not sync’ing and simply silently not working anymore (all subsequent subscriptions queries and mutations fail), the datastore should rebuild itself and resend on first query/mutation/subscription.

**Comment by amhinson** [comment]
I'm hesitant on DataStore automatically rebuilding itself in these situations, but does it seem reasonable to bubble up any indexedDB terminations so that you would be able to call `DataStore.start()` in your code?

**Comment by mchitson** [comment]
Yes that would work.

**Comment by mchitson** [comment]
Actually how would that work in practice? Someone clears the cache, subscriptions will continue (I have no control over when next subscriptions are coming) and fail, are u sending an event as soon as the datastore is cleared?

**Comment by amhinson** [comment]
Its still just hypothetical at this point, but one possibility would be to clear the subscriptions when the db is terminated and send the event, so you could immediately restart DataStore if you wish.

**Comment by mchitson** [comment]
What would be the ETA for this? After a lot of days of wrangling with datastore I am finding out I can’t use it for production because of those issues.

**Comment by amhinson** [comment]
We've added this to our backlog queue, so any future updates will be posted here.

**Comment by wei** [comment]
@mchitson I'm able to reproduce by using the two browser and clear cache method. Quick question: what do you mean by "browser history refreshed" in your original comment? Why would a refresh clear out application data (IndexDB)?

**Comment by mauerbac** [comment]
@mchitson - we will close this as we haven't heard from you. Please open a new issue if you have concerns.
