### ISSUE TITLE
Datastore selective sync equal acts like begintWith

### ISSUE THREAD

**Issue by rpostulart** [aws-amplify/amplify-js#7153]
When I do a syncExpression and I add this for example this ID: 63460c1c-b622-4522-95d2-fa54a051624f

```
syncExpression(Channel, () => {
              return (c) =>
                c.tenant("eq", id);
            }),

```

It shows the data from that id.

When I add a random char behind the ID, then still that same data is synced, while when I add a random char before it shows no records as excepted.

here is my repo: https://github.com/rpostulart/multitenant

**Comment by iartemiev** [comment]
@rpostulart - are you clearing your local store in between these changes? I can't seem to reproduce this locally. If I append a character to an id (at the beginning or end), I don't get any results back.

**Comment by rpostulart** [comment]
Me neither, I will close the issue
