### ISSUE TITLE
"TypeError: Cannot read property 'getPredicates' of undefined" and selective sync

### ISSUE THREAD

**Issue by monotv** [aws-amplify/amplify-js#7166]
**Describe the bug**

I am using this library in a React Native project.

I do this:
```
      DataStore.configure({
        syncExpressions: [
          syncExpression(SomeModel, () => {
            return (user) => user.id('eq', id);
          }),
        ],
      });
      DataStore.observe(SomeModel, id).subscribe(
      async (msg) => {
        console.log(msg);
      },
      (error) => console.log(error),
    );
```
The code here:
https://github.com/aws-amplify/amplify-js/blob/947197d39e4136af1d114ef716fe77725712f51f/packages/datastore/src/datastore/datastore.ts#L703

up to and including line 710 results in this warning:

```
Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'getPredicates' of undefined
TypeError: Cannot read property 'getPredicates' of undefined
```
Code after that is not executed anymore because of the rejection.

If I comment the lines 703 to 710 out, the warning goes away. It then still syncs the whole DynamoDB table and is not selective.

**To Reproduce**

I don't have a minimal repository but I am trying to use a `syncExpression` in a React Native project to selectively sync and then subscribe to a data store in a DynamoDB.

**Expected behavior**
The logger code should not interfere with executing the app.

**What is Configured?**
```
    "aws-amplify": "3.3.7",
    "aws-amplify-react": "4.2.11",
    "aws-amplify-react-native": "4.2.8",
    "react-native": "0.62.2",
```
**Smartphone (please complete the following information):**

- Device: iPhone 11 simulator
- OS: iOS 14.0

**Comment by iartemiev** [comment]
Hey @monotv, is this the only place you're calling `DataStore.configure`? 
The error you mention is being thrown by `DataStore.query` could you share how you're using that method?
