### ISSUE TITLE
Federated Sign in rendering bug

### ISSUE THREAD

**Issue by VolodymyrPliuta** [aws-amplify/amplify-js#7173]
**Describe the bug**

&nbsp; &nbsp; Federated sign in sets local storage after application renders so there is no way to find out if the user is signed in or not
localStorage is empty and it doesn't matter if I check it on my own or use  `Hub.listen("auth"...`
UX doesn't look good because the user will see a Sign In page for a moment before Hub.listen("auth"...) will pick up a `token` form from `local storage`

**To Reproduce**
1. Click sign in button: `Auth.federatedSignIn({ provider: 'some-custom-provider' })`
2. Listen for auth:
```
 componentDidMount() {
    Hub.listen("auth", ({ payload: { event, data } }) => {
      switch (event) {
        case "signIn":
          this.setState({ user: data });
          break;
        case "signOut":
          this.setState({ user: null });
          break;
        case "customOAuthState":
          this.setState({ customState: data });
      }
    });


    Auth.currentAuthenticatedUser()
      .then(user => this.setState({ user }))
      .catch(() => console.log("Not signed in"));
  }
```

3. See rendering issue

**Expected behavior**

&nbsp; &nbsp; Should be a way to figure out if federated Sign in was successful without a delay(Should work clean like `withAuthenticator` component  from `'@aws-amplify/ui-react';`)

**What is Configured?**

  ```
 const awsconfig = {
  auth: {
    mandatorySignIn: true,
    region: REGION,
    userPoolId: USER_POOL_ID,
    identityPoolId: IDENTITY_POOL_ID,
    userPoolWebClientId: WEB_CLIENT_ID,
    signInUrl: SIGNIN_URL,
    oauth: {
      domain: DOMAIN,
      scope: SCOPE,
      redirectSignIn: REDIRECT_URL,
      redirectSignOut: REDIRECT_URL,
      responseType: RESPONSE_TYPE,
      client_id: WEB_CLIENT_ID
    },
  },
  storage: {
    region: REGION,
    identityPoolId: IDENTITY_POOL_ID
  },
  api: {
    endpoints: [
      {
        name: API_NAME,
        endpoint: API_URL,
        region: REGION
      }
    ]
  }
};
```

**Comment by rosmu** [comment]
Are there any updates for this yet? there seems to be about 2-4 seconds delay in firing the 'SignIn' event after logging into  the Federated signin. While the delay happens the sign in page is shown again which will be confusing to the users.

**Comment by harrysolovay** [comment]
Use the `currentAuthenticatedUser` call (or, it seems you want the `currentUserInfo` method) instead of awaiting the hub event.

You can display a spinner or some loading state for the first paint, or you can block rendering by returning undefined. Send off the request, and then––upon the user data retrieval––set it in state, as to render out the appropriate pane.

```tsx
const MyExampleComponent: React.FC = () => {
  const [loading, setLoading] = useState(true);
  const [user, setUser] = useState<any>(undefined);

  useEffect(() => {
    (async() => {
      setUser(await Auth.currentAuthenticatedUser());
    })();
  }, []);

  return loading ? <Loading /> : user ? <Dashboard {...{user}} /> : <LogIn />;
}
```

**Comment by VolodymyrPliuta** [comment]
@harrysolovay The solution you provided is working. it is going to have Loading component forever.
I tried to use `Auth.currentAuthenticatedUser()` before I switched to `Hub.listen("auth"...`
But even if I refactor solution you provided and then setUser, and change loading to `false` after `user info` will be retrieved 
_Users still going to see SignIn component after Cognito redirects it to `redirect URL` for a second or two before they will see `Welcome` page_
