### ISSUE TITLE
Changing temporary password fails due to phone number issue @aws-amplify/ui-angular

### ISSUE THREAD

**Issue by mgilroy** [aws-amplify/amplify-js#7175]
When using    "@aws-amplify/ui-angular": "^0.4.10" and logging in with a temporary password the user is prompted to enter a phone number. Whilst the UI allows you to select the appropriate country code +1 for US, +44 for UK. If you type the remainder of the phone number in to the text box for example,

+44 7777777777

It reports a failure in the phone number. Looking at what is actually sent in the post the +44 is missing:

userAttributes.phone_number | "7777777777"

The user selected portion of the phone number is not being added to the post. If you add the +44 to the text field it works.

Additionally, the text entry box implies that phone numbers should be entered as (555) 555-1234, however, the formatting rules expect there to be only numbers.

**Comment by chrispruitt** [comment]
I am seeing this in `@aws-amplify/ui-vue` as well. Currently confusing most users.

**Comment by sammartinez** [comment]
Thanks for reporting this issue @mgilroy, from the above pull request, we will evaluate the change and get the bug fix in when we can.

**Comment by cloudadmin2** [comment]
Apologies for the delayed response. The emails have been going to my previous employer.

 This is still happening in "aws-amplify-angular": "^6.0.1",

To replicate:

Create a user in cognito userpool, login via the aws-amplify/amplify-ui-components

During first login with a temporary password when the user is prompted for a phone number it doesn't work unless they manually enter the international dialling code in the text field. The value in the drop down does not work.

**Comment by mgilroy** [comment]
I also apparently used a different account to confirm the issue still exists. Only occurs when the user is prompted for a new password.

Create the user in congito without a confirmed phone number: 
![cognito-create-user](https://user-images.githubusercontent.com/1001204/122176145-34152680-ce7c-11eb-8e64-905000305040.png)

Sign in as the user:
![signin-page](https://user-images.githubusercontent.com/1001204/122175650-bf41ec80-ce7b-11eb-9efc-23ce307a1046.png)

Then change the password:
![change-password](https://user-images.githubusercontent.com/1001204/122175683-c49f3700-ce7b-11eb-81b3-cad55b90ff1c.png)

I continue to get an invalid phone number format error message which is missing the international dial code from the drop down. It doesn't matter which international dial code is selected from the drop down, none are used. You need to manually type +447777777777 in place of the 7777777777 which a user would expect to enter.

**Comment by eddiekeller** [comment]
PR merged in here - https://github.com/aws-amplify/amplify-js/pull/8489

Closing this issue as this should be fixed now. Feel free to reopen and let us know if the fix does not address the issue properly.
