### ISSUE TITLE
DataStore generates invalid GQL: unrecognized token '$util' in `syncFoo` query

### ISSUE THREAD

**Issue by jcf** [aws-amplify/amplify-js#7179]
**Describe the bug**

I have a number of models in my codebase, and I'm using `DataStore` in a few places to enable offline editing etc. When my app starts up I see repeated requests to `https://{redacted}.appsync-api.eu-west-2.amazonaws.com/graphql` with the following `MappingTemplate` error due to a `filter` that looks like it's made it out of a template and into a GraphQL query:

``` json
{
  "data": { "syncProducts": null },
  "errors": [
    {
      "path": ["syncProducts"],
      "data": null,
      "errorType": "MappingTemplate",
      "errorInfo": null,
      "locations": [{ "line": 2, "column": 3, "sourceName": null }],
      "message": "Unrecognized token '$util': was expecting ('true', 'false' or 'null')\n at [Source: (String)\"\n\n{\n      \"version\": \"2018-05-29\",\n      \"operation\": \"Sync\",\n      \"limit\": 1000,\n      \"nextToken\": null,\n      \"lastSync\": 0,\n      \"filter\":     $util.transform.toDynamoDBFilterExpression($ctx.args.filter)\n      }\n\"; line: 9, column: 26]"
    }
  ]
}
```

The query itself looks like this (again, generated by DataStore as far as I can tell):

``` json
{
  "query": "query operation($limit: Int, $nextToken: String, $lastSync: AWSTimestamp, $filter: ModelProductsFilterInput) {\n  syncProducts(limit: $limit, nextToken: $nextToken, lastSync: $lastSync, filter: $filter) {\n    items { REDACTED }\n    nextToken\n    startedAt\n  }\n}\n",
  "variables": {
    "limit": 1000,
    "nextToken": null,
    "lastSync": 0,
    "filter": null
  }
}
```

**To Reproduce**

Create a couple of models. My `Product` model looks something like this:

``` graphql
type Product
@model
@searchable
@auth(rules: [
    {
      allow: groups,
      groups: ["admins"],
      operations: [create, delete, read, update]
    }
    {
      allow: groups,
      groups: ["shoppers"],
      operations: [read]
    }
    {
      allow: private,
      operations: [read]
    }
  ])
@key(name: "productsByState", fields: ["state"], queryField: "productsByState")
{
  id: ID!
  name: String!
  description: String
  state: PRODUCT_STATE!

  images: [ProductImage]
    @connection(keyName: "byProduct", fields: ["id"])
}
```

All I need to do is configure Amplify to trigger repeated requests to AppSync. I'm not observing or subscribing at this point so it looks like something internal to DataStore.

**Expected behavior**

I would expect to see no errors in the response from Amplify. I'm not passing in any filters etc. This is some internal code in Amplify and DataStore as far as I can tell.

**Code Snippet**

Please let me know if this is required.

**Screenshots**

Chromium DevTools shows the repeated requests to sync two models.

![image](https://user-images.githubusercontent.com/18374/98964815-2fad1780-2501-11eb-8c1f-98948cbc96cb.png)

I can see the initiator is some retry logic inside DataStore.

**What is Configured?**

I have API (GraphQL), Auth, and Analytics configured.

<details>
  <summary><strong>Environment</strong></summary>

```
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jcf/.npm/_logs/2020-11-12T16_09_12_945Z-debug.log
Install for [ 'envinfo@latest' ] failed with code 1
```

I have Amplify v3.3.1 in my `package.json`. My dev dependencies contains `@aws-amplify/cli` v4.29.3.

</details>

**Comment by jcf** [comment]
I love that _I_ added the label "to-be-reproducted". It's like I don't believe I'm having this issue, and need someone to double check I'm not imagining things. :1st_place_medal: 

Also, the environmental info that requires executing who knows what code on my dev machine via `npx` failed so all I could share was the error message. It tickled me so, and I thought it might put a smile on someone else's face so couldn't resist sharing.

**Comment by jcf** [comment]
I think this is the problematic blob of VTL:

``` vtl
## [Start]  Set query expression for @key **
#if( !$scan )
  #set( $limit = $util.defaultIfNull($context.args.limit, 100) )
  #set( $QueryRequest = {
  "version": "2018-05-29",
  "operation": "Sync",
  "limit": $limit,
  "query": $modelQueryExpression
} )
  #if( !$util.isNull($ctx.args.sortDirection)
                    && $ctx.args.sortDirection == "DESC" )
    #set( $QueryRequest.scanIndexForward = false )
  #else
    #set( $QueryRequest.scanIndexForward = true )
  #end
#if( $context.args.nextToken ) #set( $QueryRequest.nextToken = $context.args.nextToken ) #end
  #if( $filterMap != {} )
    #set( $QueryRequest.filter = $util.parseJson($util.transform.toDynamoDBFilterExpression($filterMap)) )
  #end
  #if( $index != "dbTable" )
    #set( $QueryRequest.index = $index )
  #end
  $util.toJson($QueryRequest)
#else
{
      "version": "2018-05-29",
      "operation": "Sync",
      "limit": $util.defaultIfNull($ctx.args.limit, 100),
      "nextToken": $util.toJson($util.defaultIfNull($ctx.args.nextToken, null)),
      "lastSync": $util.toJson($util.defaultIfNull($ctx.args.lastSync, null)),
      "filter":     #if( $ctx.args.filter != {} )
$util.transform.toDynamoDBFilterExpression($ctx.args.filter)
    #else
null
    #end
  }
#end
## [End]  Set query expression for @key **
```

Specifically where the `"filter"` is being set to either `null` or `$util.transform.toDynamoDBFilterExpression($ctx.args.filter)`.

This is code generated by Amplify that I've not modified. I'm told there are no changes to make to my API when I run `amplify push`, and `amplify codegen` does nothing when I invoke it.

**Comment by amhinson** [comment]
@jcf Just to validate, could you try running `amplify model codegen` as well as `amplify push --force` and see if the same error appears?

**Comment by jcf** [comment]
Thank you for getting back to me so quickly, @amhinson.

I've generated model definitions, and force pushed my Amplify environment as per your instructions.

```sh
~/c/l/REDACTED ❯❯❯ amplify model codegen

GraphQL schema compiled successfully.

Edit your schema at /home/jcf/code/REDACTED/REDACTED/amplify/backend/api/REDACTED/schema.graphql or place .graphql files in a directory at /home/jcf/code/REDACTED/REDACTED/amplify/backend/api/REDACTED/schema
Successfully generated models. Generated models can be found /home/jcf/code/REDACTED/REDACTED/src

~/c/l/REDACTED ❯❯❯ git status -sb
## datastore-sync-wat...origin/master [ahead 3]

~/c/l/REDACTED ❯❯❯ amplify push --force
✔ Successfully pulled backend environment dev from the cloud.

Current Environment: dev

| Category  | Resource name    | Operation | Provider plugin   |
| --------- | ---------------- | --------- | ----------------- |
| Auth      | REDACTED709df6da | No Change | awscloudformation |
| Api       | REDACTED         | No Change | awscloudformation |
| Analytics | REDACTED         | No Change | awscloudformation |
? Are you sure you want to continue? Yes
✔ All resources are updated in the cloud

Pinpoint URL to track events https://eu-west-1.console.aws.amazon.com/pinpoint/home/?region=eu-west-1#/apps/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/analytics/overview
GraphQL endpoint: https://xxxxxxxxxxxxxxxxxxxxxxxxxx.appsync-api.eu-west-2.amazonaws.com/graphql
GraphQL API KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Hosted UI Endpoint: https://REDACTED-REDACTED-dev.auth.eu-west-2.amazoncognito.com/
Test Your Hosted UI Endpoint: https://REDACTED-REDACTED-dev.auth.eu-west-2.amazoncognito.com/login?response_type=code&client_id=xxxxxxxxxxxxxxxxxxxxxxxxxx&redirect_uri=https://REDACTED.dev.REDACTED.com/oauth/callback/
```

I'm still seeing the same errors syncing two models.

**Comment by jcf** [comment]
I'm now seeing this same error with all of my models rather than just the two that I noticed previously. I've tried setting `"syncable"` to `false` in my `src/models/schema.js` to prevent the sync from taking place but I can't do that on every model without ditching DataStore and handling that stuff myself via GraphQL.

**Comment by amhinson** [comment]
@jcf Thanks for the info! I've got a few more clarifying questions and requests:
- Is the other model you are seeing this behavior `ProductImage`? And could you share that schema as well?
- Could you share your `package.json`? Feel free to remove anything that you don't deem necessary to share.
- What version of the Amplify CLI are you using? `amplify -v`

**Comment by iartemiev** [comment]
@jcf the `@searchable` directive [isn’t compatible with DataStore](https://docs.amplify.aws/cli/graphql-transformer/searchable#known-limitations) or `@connection`. 
Could you please try removing it, followed by:
```bash
amplify push
amplify codegen models
```

**Comment by jcf** [comment]
@aminson please find answers to your questions inline below.

> Is the other model you are seeing this behavior ProductImage? And could you share that schema as well?

The problematic models are the `Nutrient` and `Product` models. I've included the `Product` schema in the issue description; this is the `Nutrient` schema:

``` graphql
type Nutrients
@model
@auth(rules: [
    {
      allow: groups,
      groups: ["admins"],
      operations: [create, delete, read, update]
    }
    {
      allow: owner,
      operations: [create, delete, read, update]
    }
    {
      allow: private,
      operations: [read]
    }
    {
      allow: public,
      provider: apiKey,
      operations: [create, delete, read, update]
    }
  ])
@key(name: "byRecipe", fields: ["recipeID"])
{
  id: ID!
  recipeID: ID!
  recipe: Recipe! @connection(fields: ["recipeID"])

  carbs: Int
  energy: Int
  fibre: Int
  protein: Int
  salt: Int
  sugar: Int

  fat: Int
  saturates: Int
}
```

> Could you share your package.json? Feel free to remove anything that you don't deem necessary to share.

My `package.json` looks something like this:

``` json
{
  "private": true,
  "dependencies": {
    "@date-io/date-fns": "1.x",
    "@material-ui/core": "^4.11.0",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/lab": "^4.0.0-alpha.56",
    "@tailwindcss/typography": "^0.2.0",
    "aws-amplify": "^3.3.1",
    "cloudinary-react": "^1.6.7",
    "date-fns": "^2.16.1",
    "formik": "^2.1.7",
    "formik-material-ui": "^3.0.0",
    "formik-material-ui-lab": "^0.0.5",
    "formik-material-ui-pickers": "^0.0.11",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-router": "^5.2.0",
    "react-router-dom": "^5.2.0"
  },
  "scripts": {
    "build": "concurrently --names cljs,css \"yarn:release-cljs\" \"yarn:release-css\"",
    "dev": "concurrently --names cljs,css \"yarn:watch-cljs\" \"yarn:watch-css\"",
    "release-cljs": "shadow-cljs release REDACTED",
    "release-css": "postcss styles/REDACTED.css -o public/css/REDACTED.css",
    "watch-cljs": "shadow-cljs watch REDACTED",
    "watch-css": "postcss styles/REDACTED.css --watch -o public/css/REDACTED.css"
  },
  "devDependencies": {
    "@aws-amplify/cli": "^4.29.3",
    "concurrently": "^5.3.0",
    "cssnano": "^4.1.10",
    "postcss": "^8.1.6",
    "postcss-cli": "^8.2.0",
    "postcss-import": "^13.0.0",
    "postcss-loader": "^4.0.4",
    "postcss-nested": "^5.0.1",
    "precss": "^4.0.0",
    "sass": "^1.27.1",
    "shadow-cljs": "^2.11.4",
    "tailwindcss": "^1.9.6"
  }
}
```

I'll be removing Material UI and SASS soon as we're opting for Tailwind instead.

> What version of the Amplify CLI are you using? amplify -v

``` sh
$ amplify -v
Scanning for plugins...
Plugin scan successful
4.32.1
```

---

> the @searchable directive isn’t compatible with DataStore or @connection. Could you please try removing it

@iartemiev in what way is `@searchable` incompatible with DataStore? Is this the serialisation bug where Elasticsearch treats epoch seconds as a float?

Does this mean I can't have offline support for a model that needs full text support? I think I can do without the `@searchable` but not having any connections will cause problems as I can't represent all my data without relationships…

https://github.com/aws-amplify/amplify-cli/issues/2517

**Comment by iartemiev** [comment]
> in what way is @searchable incompatible with DataStore?

It's primarily incompatible because the Elasticsearch response template doesn't return the `_version`, `_lastChangedAt`, and `_deleted` fields.
You can use `@connection` with DataStore, but not with `@searchable`.

Another thing to check is whether your data in DynamoDB contains any empty lists `[]`. There's currently a bug in the AppSync service where enabling sync/conflict resolution on an API will cause AppSync to error out when encountering an empty list. The AppSync team is currently working on fixing that. In the meantime, a workaround would be to persist `[null]` or `['']`  instead of `[]`.
