### ISSUE TITLE
Invalid Refresh Token with USER_PASSWORD_AUTH

### ISSUE THREAD

**Issue by k-ahn** [aws-amplify/amplify-js#7182]
**Describe the bug**
I am getting "Invalid Refresh Token" when running `Auth.currentSession()` 1 hour after successful login to a React JS app.

**To Reproduce**
1. At the login screen, successfully execute `Auth.signIn(USERNAME, PASSWORD)`
2. Redirect to the main app and i can run `Auth.currentSession()` to retrieve the ID, Access and Refresh tokens as often as required for the next 1 hour, even if i reload the app. I see the cookies are created.
3. After exactly 1 hour i get `NotAuthorizedException` and `Invalid Refresh Token` and the cookies have disappeared.

**Expected behavior**
`Auth.currentSession()` should use the Refresh token to obtain a new ID token

**Code Snippet**
```
    // Import and setup
    import Amplify, { Auth } from 'aws-amplify';
    
    Amplify.configure({
      Auth: {
          region: REGION,
          userPoolId: USERPOOLID,
          userPoolWebClientId: USERPOOLWEBCLIENTID,
          authenticationFlowType: 'USER_PASSWORD_AUTH',
          cookieStorage: {
               domain: '.domain.co.uk',
               path: '/',
               expires: 60,
               secure: false
           },
      }
    })


    // Login Function
    let user = await Auth.signIn(USERNAME, PASSWORD);
    if (user.hasOwnProperty('authenticationFlowType')) {
      this.setState( { response: 'Login Success!' }, this.login )
    } else {
      this.setState( { response: user.message });
    };
```

**Screenshots**
![image](https://user-images.githubusercontent.com/53981218/98996980-ae1eaf00-252b-11eb-86af-aa414273efd4.png)

<details>
  <summary><strong>Environment</strong></summary>

```
  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
    Memory: 1.22 GB / 7.92 GB
  Binaries:
    Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.193
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    @date-io/date-fns: ^1.3.13 => 1.3.13
    @material-ui/core: ^4.11.0 => 4.11.0
    @material-ui/pickers: ^3.2.10 => 3.2.10
    @testing-library/jest-dom: ^4.2.4 => 4.2.4
    @testing-library/react: ^9.3.2 => 9.5.0
    @testing-library/user-event: ^7.1.2 => 7.2.1
    amazon-chime-sdk-js: ^1.20.2 => 1.20.2
    aws-amplify: ^3.3.4 => 3.3.4
    bootstrap: ^4.5.3 => 4.5.3
    moment: ^2.29.1 => 2.29.1
    react: ^16.13.1 => 16.13.1
    react-big-calendar: ^0.28.5 => 0.28.5
    react-bootstrap: ^1.3.0 => 1.3.0
    react-datepicker: ^3.3.0 => 3.3.0
    react-dom: ^16.13.1 => 16.13.1
    react-moment: ^1.0.0 => 1.0.0
    react-open-weather: git+https://github.com/mhonkanen/react-open-weather.git => 0.6.2
    react-router-bootstrap: ^0.25.0 => 0.25.0
    react-router-dom: ^5.2.0 => 5.2.0
    react-scripts: 3.4.3 => 3.4.3
  npmGlobalPackages:
    expo-cli: 3.21.13
    node-gyp: 4.0.0
    react-native-cli: 2.0.1
    windows-build-tools: 5.1.0
    yarn: 1.22.10
```

</details>

**Smartphone (please complete the following information):**

- Device: Laptop
- OS: Windows 10
- Browser Chrome
- Version 86.0.4240.193

**Additional context**
If `Auth.CurrentSession()` has access to the ID, Access and Refresh tokens within the hour i am not clear why it doesn't when a refresh is required?

I am currently running the app locally via **localhost:3000** as loaded by **npm start**

### UPDATE

- ISSUE CAUSE: On further investigation it looks like the issue relates to `authenticationFlowType: 'USER_PASSWORD_AUTH'` in the configuration. 
- DEBUGGING: Irrespective of whether using `LocalStorage `or `cookieStorage `executing `Auth.currentSession()` causes the "Invalid Refresh Token" error when `authenticationFlowType: 'USER_PASSWORD_AUTH'`
- INFO: The 1 hour time period above is dictated in configuration. This is the point ID token expires and the Refresh token is required, and when it breaks. Changing the "ID token expiration" to 6 minutes causes it to fail after 6 minutes, as expected.
- WORKAROUND: I've removed authenticationFlowType from configuration thus reverting to the default USER_SRP_AUTH, which i've learned it should have been anyway. 
- DEFECT: I believe it is still a defect for anyone requiring the Refresh token with USER_PASSWORD_AUTH

**Comment by houmark** [comment]
Hey @k-ahn — appreciate the detailed analysis here, but I may have lost track on exactly what goes wrong here.

Still, I would like to do some testing on this particular setup in our Amplify based platform to either verify or discard this issue.

We are in the situation where we are using `cookieStorage` due to login across multiple subdomains on the same web app and also using `authenticationFlowType: 'USER_PASSWORD_AUTH'` due to a migration of users from a prior platform.

Reading the above bug report and analysis, it seems like we could potentially be affected by this bug, but we have not yet seen any such issues, though `cookieStorage` is only in production for less than a day at this point, while USER_PASSWORD_AUTH has been in production for months without reports of issues that seems to relate to this potential bug.

Would it be possible for you to share more information about the exact setup that seems to trigger this refresh token bug?

**Comment by k-ahn** [comment]
Hi @houmark 

Much head scratching here - i can no longer reproduce the issue. Having gone to great lengths to resolve the issue and then recreate it for the purposes of writing the defect this is most confusing. 

I'll close the defect.

**Comment by houmark** [comment]
Maybe it got solved with other changes. Ultimately glad these seems to be a non-issue. We have not seen user reports either, so it seems to be resolved. Thanks for your reply.
