### ISSUE TITLE
Feature Request: A Way to Remove Sign in with AWS Button

### ISSUE THREAD

**Issue by ChihweiLHBird** [aws-amplify/amplify-js#7199]
I just used amplify in a React frontend project, and the sign in page looks like:

![image](https://user-images.githubusercontent.com/43905414/99199613-975f9e80-275d-11eb-9b31-365658323762.png)

And this is what I expect:

![image](https://user-images.githubusercontent.com/43905414/99199620-a6dee780-275d-11eb-9e05-275f4584d518.png)

So, how can I remove the Sign In with AWS button and keep others?
The code looks like:
```
const federated = {
    amazonClientId: "a client id",
    facebookAppId: "a client id",
    googleClientId: "a client id",
  }
```
```
<AmplifyAuthenticator
                    usernameAlias="email"
                >
                    <AmplifySignIn headerText="Sign In" slot="sign-in"
                        federated={federated}
                        usernameAlias="email"
                        formFields={[...]}
                    >
                    </AmplifySignIn>
                    <AmplifySignUp
                        usernameAlias="email"
                        formFields={[...]}
                        slot="sign-up"
                    ></AmplifySignUp>
                </AmplifyAuthenticator>
```

**Comment by tjleing** [comment]
Hello!  I'm going to look into the issue more tomorrow, but in the meantime, have you tried simply removing the `amazonClientId`?
```
const federated = {
    facebookAppId: "a client id",
    googleClientId: "a client id",
  }
```
Thank you for using Amplify 😄

**Comment by tjleing** [comment]
Ah, now I understand your issue -- sorry, my advice was completely wrong then.

**Comment by ChihweiLHBird** [comment]
> Ah, now I understand your issue -- sorry, my advice was completely wrong then.

No worries, lol.
Do you need any other information, like our config file?

**Comment by tjleing** [comment]
I'm struggling a little bit to reproduce your behavior.  Locally, setting
```
const federated = {
	amazonClientId: "a client id",
	facebookAppId: "a client id",
	googleClientId: "a client id",
	oauthConfig: "oauth config",
}
```
shows the "Sign in with AWS" button, and removing the oauthConfig variable causes it to disappear.  So I'm not entirely sure what's different about your code base to cause this difference in outcome.  The only possibility (other than oauthConfig accidentally being added at some point in your code) that I can think of comes from [this file](https://github.com/aws-amplify/amplify-js/blob/main/packages/amplify-ui-components/src/components/amplify-federated-buttons/amplify-federated-buttons.tsx):
```
const { oauth = {} } = Auth.configure();

// backward compatibility
if (oauth['domain']) {
    this.federated.oauthConfig = { ...this.federated.oauthConfig, ...oauth };
} else if (oauth['awsCognito']) {
    this.federated.oauthConfig = { ...this.federated.oauthConfig, ...oauth['awsCognito'] };
}
```

Do you happen to know if the domain or awsCognito attributes are being set in your Amplify configuration?  Perhaps the config file would be helpful in diagnosing this problem.  Hope this helps!

**Comment by ChihweiLHBird** [comment]
> oauthConfig

Thank you for your effort on solving this. 
I do have `"oauth"` value in the config value, so is there any way to disable Login With AWS button while having the oauth config?

**Comment by ChihweiLHBird** [comment]
> I'm struggling a little bit to reproduce your behavior. Locally, setting
> 
> ```
> const federated = {
>     amazonClientId: "a client id",
>     facebookAppId: "a client id",
>     googleClientId: "a client id",
>     oauthConfig: "oauth config",
> }
> ```
> 
> shows the "Sign in with AWS" button, and removing the `oauthConfig` variable causes it to disappear. So I'm not entirely sure what's different about your code base to cause this difference in outcome. The only possibility (other than `oauthConfig` accidentally being added at some point in your code) that I can think of comes from [this file](https://github.com/aws-amplify/amplify-js/blob/main/packages/amplify-ui-components/src/components/amplify-federated-buttons/amplify-federated-buttons.tsx):
> 
> ```
> const { oauth = {} } = Auth.configure();
> 
> // backward compatibility
> if (oauth['domain']) {
>     this.federated.oauthConfig = { ...this.federated.oauthConfig, ...oauth };
> } else if (oauth['awsCognito']) {
>     this.federated.oauthConfig = { ...this.federated.oauthConfig, ...oauth['awsCognito'] };
> }
> ```
> 
> Do you happen to know if the `domain` or `awsCognito` attributes are being set in your Amplify configuration? Perhaps the config file would be helpful in diagnosing this problem. Hope this helps!

Thank you for your effort on solving this.
I do have "oauth" value in the config value, so is there any way to disable Login With AWS button while having the oauth config?

**Comment by tjleing** [comment]
After discussing with the team, it seems like your use case is not officially supported by Amplify.  However, it seems that running a snippet such as
```
document.querySelector("amplify-sign-in").shadowRoot.querySelector("amplify-federated-buttons").shadowRoot.querySelector("amplify-oauth-button").style.display = "none";
```
after the first render can achieve your desired behavior.  Please let me know if this resolves your issue.

**Comment by camhart** [comment]
> After discussing with the team, it seems like your use case is not officially supported by Amplify. However, it seems that running a snippet such as
> 
> ```
> document.querySelector("amplify-sign-in").shadowRoot.querySelector("amplify-federated-buttons").shadowRoot.querySelector("amplify-oauth-button").style.display = "none";
> ```
> 
> after the first render (in `componentDidMount()`, for instance) can achieve your desired behavior. Please let me know if this resolves your issue.

Are there plans to support it down the road?

**Comment by ChihweiLHBird** [comment]
> After discussing with the team, it seems like your use case is not officially supported by Amplify. However, it seems that running a snippet such as
> 
> ```
> document.querySelector("amplify-sign-in").shadowRoot.querySelector("amplify-federated-buttons").shadowRoot.querySelector("amplify-oauth-button").style.display = "none";
> ```
> 
> after the first render (in `componentDidMount()`, for instance) can achieve your desired behavior. Please let me know if this resolves your issue.

Thank you, and I am going to try this method. By the way, as @camhart mentioned, is there any plan to support disable of the button?

**Comment by tjleing** [comment]
Thanks again for the feedback!  I hope we've found a functioning workaround to your issue.

As far as getting this feature into the library, I've marked this as a feature request so that we can more effectively gauge demand from the community.  We also welcome contributions in the form of pull requests if you're up to it!

**Comment by countryst** [comment]
Any update on this?

**Comment by tjleing** [comment]
Hey @ChihweiLHBird and @countryst -- my teammate @ericclemmons put together [a CodeSandbox](https://codesandbox.io/s/amplify-ui-federated-buttons-48x56?file=/src/App.js) showing how to do this using the `<slot>` of the `AmplifySignIn` component, which is the officially-supported solution for this use case.

However, we would also like to support it better -- recreating the entire block of buttons is not optimal.

Please let us know if this solves your issue! 😄

**Comment by lack-of-gravitas** [comment]
For the love of all that is holy can you make this better documented -- rummaging around for hours to find out how to hide a federated ID i never enabled is annoying.

**Comment by pbergue** [comment]
I had the same issue and found a workaround. I give to the federated props of AmplifySignIn component an empty string and use a button with Auth.federatedSignIn() for each social you want to log in with.
For example:
`<AmplifyAuthenticator usernameAlias="email">
    <AmplifySignIn  slot="sign-in"  federated="" usernameAlias="email" />
    <Button sx={sxBtn} onClick={() => Auth.federatedSignIn({ provider: 'Facebook' })}>FACEBOOOOOOOOOK</Button>
</AmplifyAuthenticator>`
