### ISSUE TITLE
authenticateUser using cookie storage should correctly set the expires time for id token, refresh token and accesToken

### ISSUE THREAD

**Issue by kickthedragon** [aws-amplify/amplify-js#720]
Do you want to request a feature or report a bug?

Feature

What is the current behavior?

Cookie storage for authenticateUser currently sets the access token, refresh token, id token by default one year ahead of the time it is inserted.  

What is the expected behavior?

It should correctly set the expires time to the expiration time of the returned values from the cognitoUser.authenticateUser() response for each token respectively.

**Comment by ericclemmons** [comment]
`CookieStorage` is no longer the default, while `localStorage` is.

Customers can provide a custom adapter and control this to match their Cognito configuration (e.g. 1 hr):
> https://docs.amplify.aws/lib/auth/manageusers/q/platform/js#managing-security-tokens
