### ISSUE TITLE
Phone number input - type tel

### ISSUE THREAD

**Issue by adampblack** [aws-amplify/amplify-js#7201]
**Describe the bug**
The phone number input does not have the correct type set.

The problem without this is the mobile phone devices do not automatically suggest a phone number from contacts.

**To Reproduce**

<AmplifyAuthenticator
        style={{
          alignItems: 'flex-start',
          display: 'flex',
          flexWrap: 'wrap',
          justifyContent: 'center',
        }}
        usernameAlias="phone_number"
      />

It should have **<input type="tel"**
https://www.w3schools.com/tags/att_input_type_tel.asp

**Comment by uncodable** [comment]
Type `tel` is on the `amplify-phone-field` component https://github.com/aws-amplify/amplify-js/blob/dbd46299af9c558251b8c652c3e50208982655c8/packages/amplify-ui-components/src/components/amplify-phone-field/amplify-phone-field.tsx#L36

**Comment by sammartinez** [comment]
@adampblack, @uncodable is correct. Are you using these [UI Components](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react) within Amplify? Please let us know.

**Comment by adampblack** [comment]
I have run:
yarn upgrade --latest

info All dependencies
├─ @aws-amplify/analytics@3.3.11
├─ @aws-amplify/api-graphql@1.2.11
├─ @aws-amplify/datastore@2.7.3
├─ @aws-amplify/predictions@3.2.11
├─ @aws-amplify/ui-components@0.9.3
├─ @aws-amplify/ui-react@0.2.28
├─ @aws-amplify/ui@2.0.2

To answer your question I am using:
import { AmplifyAuthenticator, AmplifyConfirmSignIn, AmplifyConfirmSignUp, AmplifyForgotPassword, AmplifySignIn, AmplifySignUp } from '**@aws-amplify/ui-react**';

I had been using ui-components previously but the form field customization stopped working when I upgraded the modules for some reason so I upgraded to ui-react.

In terms of the field type it definitely says type="text" - but this might be a bug specific to ui-react not in ui-components.
![Screenshot 2020-11-17 at 15 29 52](https://user-images.githubusercontent.com/11552373/99360587-c7d54300-28eb-11eb-8fff-aefda0e936fc.png)

This is in the AmplifySignIn component but also occurs in the other components under ui-react as well.

**Comment by tjleing** [comment]
This should be resolved in the next release now that #7211 is merged in!

**Comment by adampblack** [comment]
Great job, thanks @tjleing
