### ISSUE TITLE
REST API call not taking place when Auth & API used simultaneously inside Amplify.configure block. Page needs to be re-loaded manually to get data on the page after authentication.

### ISSUE THREAD

**Issue by ranopriyo-neogy** [aws-amplify/amplify-js#7205]
Post authentication React page is getting stuck with loading status as REST API call is not taking place and hence page needs to get re-loaded manually for REST API call to take place. There are no suggestions on how to handle both Auth & REST API call manually in Amplify.configure block. Tried using the suggested methods on - https://docs.amplify.aws/lib/graphqlapi/create-or-re-use-existing-backend/q/platform/js#using-openid_connect , but no luck. Can someone please suggest an alternative or suggest on how to get this fixed. 

```
Amplify.configure({

  Auth: {
    region: 'us-east-1',
    userPoolId: process.env.REACT_APP_USERPOOL_ID,
    userPoolWebClientId: process.env.REACT_APP_USERPOOL_WEB_CLIENT_ID,

    oauth: {
      "domain": "xxxxx-dev.auth.us-east-1.amazoncognito.com",
      "scope": [
          "phone",
          "email",
          "openid",
          "profile",
          "aws.cognito.signin.user.admin"
      ],
      "redirectSignIn": "http://localhost:3000/",
      "redirectSignOut": "http://localhost:3000/",
      "responseType": "code",
    }
  },  

  API: {
    endpoints: [
      {
        name: "MyAPIGatewayAPI",
        endpoint: process.env.REACT_APP_APIG_ENDPOINT,
        region: 'us-east-1',
        custom_header: async () => {
          return { Authorization: (await Auth.currentSession()).idToken.jwtToken }; 
        }
      }
    ]
  }
  }); 
  

```

**Comment by mauerbac** [comment]
Transferring to JS Repo as this looks like a question about Auth

**Comment by amhinson** [comment]
@ranopriyo-neogy Would you be able to provide a small repo showing the behavior you're seeing? Calling `Amplify.configure()` doesn't actually make any API calls for `Auth` or `API`, it only provides the necessary configuration for each.

**Comment by ranopriyo-neogy** [comment]
> @ranopriyo-neogy Would you be able to provide a small repo showing the behavior you're seeing? Calling `Amplify.configure()` doesn't actually make any API calls for `Auth` or `API`, it only provides the necessary configuration for each.

@amhinson - Here's the repo link -  https://github.com/ranopriyo-neogy/multi-account-viewer/blob/master/Front-End/src/App.js

**Comment by ranopriyo-neogy** [comment]
@amhinson - Here are the screenshots: Actual & Expected

<img width="1424" alt="Page Hung-up and fails to load completely " src="https://user-images.githubusercontent.com/68603179/99469669-3ed10280-2911-11eb-9653-a3bc83d9108b.png">

<img width="1435" alt="Expected Page After Authentication" src="https://user-images.githubusercontent.com/68603179/99469672-41cbf300-2911-11eb-880d-6dd2fb40ba2f.png">

**Comment by amhinson** [comment]
@ranopriyo-neogy It looks like you are using an older version of `aws-amplify` and `aws-amplify-react`. Would you be able to update to the latest for both? Based on your configuration, I don't think you should run into any breaking changes.

Also, I would recommend using the new version of the UI components `@aws-amplify/ui-react`, as any future updates we put out will be for that library and not the one you are currently using. Here is a [migration guide](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#migration) to upgrade.

Can you try those out and get back to be with what you find?

**Comment by ranopriyo-neogy** [comment]
Thanks a ton @amhinson , upgrading the versions fixed the  Loading issue.
