### ISSUE TITLE
DataStore throws exception when using dynamic group authorization with custom claim on subscription

### ISSUE THREAD

**Issue by mlxyz** [aws-amplify/amplify-js#7206]
**Describe the bug**
I have the following schema:
```gql
type Tenant
@model
@auth(rules: [
    { allow: groups, groupsField: "id", groupClaim: "custom:tenant", operations: [read] }
])
{
    id: ID!
    name: String!
}
```
The auth rule ensures that users can only read tenant item(s) with an id they are assigned to (using the "tenant" custom attribute). This  approach works flawlessly for gql queries.
When using DataStore to sync this model, it throws the following error when trying to setup the subscriptions:
`ERROR Error: Uncaught (in promise): TypeError: userGroups.find is not a function`
As far as i can tell this is caused by the following lines: https://github.com/aws-amplify/amplify-js/blob/dbd46299af9c558251b8c652c3e50208982655c8/packages/datastore/src/sync/processors/subscription.ts#L140-L145
Line 143 assumes that the "custom:tenant" attribute is an array, which might not be the case. In our application, we store a json formatted list in the "tenant" attribute because cognito does not support lists for custom attributes yet.

**I would expect that DataStore handles custom claims similar to the way resolvers do.** The same auth rule from above generates the following vtl code:
```vtl
  #set( $isDynamicGroupAuthorized = $util.defaultIfNull($isDynamicGroupAuthorized, false) )
  ## Authorization rule: { allow: groups, groupsField: "id", groupClaim: "custom:tenant" } **
  #set( $allowedGroups = $util.defaultIfNull($ctx.result.id, []) )
  #set( $userGroups = $util.defaultIfNull($ctx.identity.claims.get("custom:tenant"), []) )
  #if( $util.isString($userGroups) )
    #if( $util.isList($util.parseJson($userGroups)) )
      #set( $userGroups = $util.parseJson($userGroups) ) 
    #else
      #set( $userGroups = [$userGroups] )
    #end
  #end
  #foreach( $userGroup in $userGroups )
    #if( $util.isList($allowedGroups) )
      #if( $allowedGroups.contains($userGroup) )
        #set( $isDynamicGroupAuthorized = true )
      #end
    #end
    #if( $util.isString($allowedGroups) )
      #if( $allowedGroups == $userGroup )
        #set( $isDynamicGroupAuthorized = true )
      #end
    #end
  #end
```
The code automatically handles cases like json formatted strings (our case) and single values. This should also be done by DataStore.

**To Reproduce**

1. Setup a project using the model from above, cognito integration and a "tenant" custom attribute (string type)
2. Create a user in cognito and assign him a value (any value) for the "custom:tenant" attribute
3. Try to initialize DataStore to sync the model while authenticated as this user

**Expected behavior**
I expect DataStore to initialize without throwing any errors. I am aware of the current limitation when using dynamic group authorization on subscriptions (see https://docs.amplify.aws/cli/graphql-transformer/auth#authorizing-subscriptions).

<details>
  <summary><strong>Environment</strong></summary>

```
  System:
    OS: Linux 5.8 Manjaro Linux
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 14.98 GB / 31.33 GB
    Container: Yes
    Shell: 5.0.18 - /bin/bash
  Binaries:
    Node: 15.0.1 - /usr/bin/node
    npm: 6.14.8 - /usr/bin/npm
  Browsers:
    Firefox: 82.0.3
  npmPackages:
    @angular-devkit/build-angular: ^0.1100.0 => 0.1100.0 
    @angular/cli: ^10.2.0 => 10.2.0 
    @angular/common: ^10.2.3 => 10.2.3 
    @angular/compiler: ^10.2.3 => 10.2.3 
    @angular/compiler-cli: ^10.2.3 => 10.2.3 
    @angular/core: ^10.2.3 => 10.2.3 
    @angular/forms: ^10.2.3 => 10.2.3 
    @angular/language-service: ^10.2.3 => 10.2.3 
    @angular/platform-browser: ^10.2.3 => 10.2.3 
    @angular/platform-browser-dynamic: ^10.2.3 => 10.2.3 
    @angular/router: ^10.2.3 => 10.2.3 
    @angular/service-worker: ^10.2.3 => 10.2.3 
    @aws-amplify/datastore: ^2.7.2 => 2.7.2 
    @aws-amplify/ui-angular: ^0.2.15 => 0.2.15 
    @babel/compat-data: ~7.8.0 => 7.8.6 
    @ionic-native/core: ^5.29.0 => 5.29.0 
    @ionic-native/splash-screen: ^5.29.0 => 5.29.0 
    @ionic-native/status-bar: ^5.29.0 => 5.29.0 
    @ionic/angular: ^5.4.4 => 5.4.4 
    @ionic/angular-toolkit: ^2.3.3 => 2.3.3 
    @types/jasmine: ~3.3.8 => 3.3.16 
    @types/jasminewd2: ~2.0.3 => 2.0.8 
    @types/luxon: ^1.25.0 => 1.25.0 
    @types/moment-duration-format: ^2.2.2 => 2.2.2 
    @types/node: ^12.19.4 => 12.19.4 
    aws-amplify: ^3.3.7 => 3.3.7 
    aws-amplify-angular: ^5.0.36 => 5.0.36 
    codelyzer: ^5.1.2 => 5.2.2 
    core-js: ^2.5.4 => 2.6.11 
    cron-parser: ^2.17.0 => 2.17.0 
    jasmine-core: ~3.5.0 => 3.5.0 
    jasmine-spec-reporter: ~5.0.0 => 5.0.2 
    karma: ~5.0.0 => 5.0.9 
    karma-chrome-launcher: ~3.1.0 => 3.1.0 
    karma-coverage-istanbul-reporter: ~3.0.2 => 3.0.3 
    karma-jasmine: ~3.3.0 => 3.3.1 
    karma-jasmine-html-reporter: ^1.5.0 => 1.5.4 
    luxon: ^1.25.0 => 1.25.0 
    protractor: ~7.0.0 => 7.0.0 
    rxjs: ^6.6.3 => 6.6.3 
    ts-node: ~7.0.0 => 7.0.1 
    tslib: ^2.0.3 => 2.0.3 
    tslint: ^6.1.3 => 6.1.3 
    typescript: ^3.9.7 => 3.9.7 
    zone.js: ~0.10.3 => 0.10.3 
  npmGlobalPackages:
    @angular/cli: 10.1.6
    @aws-amplify/cli: 4.32.1
    @ionic/cli: 6.12.1
    aws-cdk: 1.60.0
    node-gyp: 7.1.0
    npm: 6.14.8
    semver: 7.3.2

```

</details>

**Comment by amhinson** [comment]
Hey @mlxyz thanks for opening this issue! 🙏  We've just merged a PR that should address the behavior you're seeing. You can test things out right now with `aws-amplify@unstable`. The fix will be included in the next release later this week or next week.

**Comment by mlxyz** [comment]
Hey @amhinson thanks for the quick fix. I just tried it and it works as expected for arrays as strings.
However, using only a single-value plain string (non array) fails with this error `ERROR Error: Uncaught (in promise): SyntaxError: JSON.parse: unexpected keyword at line 1 column 1 of the JSON data` at https://github.com/aws-amplify/amplify-js/blob/main/packages/datastore/src/sync/utils.ts#L464-L467.
This issue is not a blocker though, because we can just use
- `'custom:groups': '["mygroup"]'` (works) instead of
- `'custom:groups': 'mygroup'` (does not work)

but for convenience, plain strings should also be supported like in the generated VTL resolvers.

**Comment by amhinson** [comment]
Good observation @mlxyz! Just updated the implementation a bit to account for that use. It's available with `unstable` now and should be on `latest` sometime next week.
