### ISSUE TITLE
Auth.signOut() doesn't log user out of social federation

### ISSUE THREAD

**Issue by ericluwj** [aws-amplify/amplify-js#7213]
**Describe the bug**
In Expo (React Native), `Auth.signOut()` does not log user out of social federation, hence user is unable to switch social federation account.

**To Reproduce**

1. Set up Expo (React Native) project based on https://docs.amplify.aws/lib/auth/social/q/platform/js#deploying-to-amplify-console
2. Sign in using `Auth.federatedSignIn({ provider: 'Facebook' })`
3. Sign out using `Auth.signOut()`, Expo would also open logout URL in web browser and dismiss it after success
4. Now run `Auth.federatedSignIn({ provider: 'Facebook' })` again
5. See error: There is no way to switch facebook user at all, I'm automatically logged in using the previous Facebook account.
6. Sign out using `Auth.signOut()`, Expo would also open logout URL in web browser and dismiss it after success
7. Now run `Auth.federatedSignIn()`
8. Again, there is no way to sign in with a different Facebook account (See screenshot). "Continue with Facebook" automatically logs in with previous Facebook account.

**Expected behavior**
There should at least be a way to sign in to another Facebook account, just like ![Sign in as a different user?](https://user-images.githubusercontent.com/11042868/48646146-c9866c00-e99c-11e8-8a6a-0ab1f1b5cade.png).

Or perhaps allow an entire Facebook logout.

**Screenshots**
![Simulator Screen Shot - iPhone 12 Pro Max - 2020-11-17 at 14 33 34](https://user-images.githubusercontent.com/1736023/99355731-cacc3580-28e3-11eb-9ee8-1b2bc0d7b8b9.png)

**What is Configured?**
```
{
    "aws_project_region": "XXXX",
    "aws_cognito_identity_pool_id": "XX-XXXX-X:XXXXXXXX-XXXX-4f7a-ac07-5e618d1db841",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_XXXXXXXXX",
    "aws_user_pools_web_client_id": "XXXXXXXXX",
    "oauth": {
        "domain": "XXXXXXXXX.auth.ap-southeast-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "exp://127.0.0.1:19000/--/",
        "redirectSignOut": "exp://127.0.0.1:19000/--/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
...
}
```

**Smartphone (please complete the following information):**

- Device: iPhone 12 Pro Max simulator
- OS: iOS 14.2
- Browser safari

**Comment by amhinson** [comment]
I have seen this behavior before. It does appear to be a limitation with Cognito right now, unfortunately. I've attached a few similar issues and StackOverflow questions for more context. There are a few potential workarounds presented in those, but they might not fit your use case entirely. I'm closing this for now, but we can use #3933 for tracking purposes on this feature request.

- https://github.com/aws-amplify/amplify-js/issues/4720
- https://github.com/aws-amplify/amplify-js/issues/3933
- https://stackoverflow.com/questions/58154256/aws-cognito-how-to-force-select-account-when-signing-in-with-google
- https://stackoverflow.com/questions/12909332/how-to-logout-of-an-application-where-i-used-oauth2-to-login-with-google/12909563#12909563
