### ISSUE TITLE
modelName is not returned in the modelSynced Event 

### ISSUE THREAD

**Issue by xsmcemmons** [aws-amplify/amplify-js#7219]
**Describe the bug**
As per documentation: https://docs.amplify.aws/lib/datastore/datastore-events/q/platform/js#modelsynced

HubPayload modelSyncedEvent contains: modelName (String): the name of the model that was synced

But in the modelSynced event there's no modelName, It returns something like this.

`{"counts": {"deleted": 0, "new": 0, "updated": 0}, "isDeltaSync": true, "isFullSync": false, "model": [Function Window]}`

**Comment by nubpro** [comment]
Did some experimenting, you can expose the model name by doing so: 

```
    useEffect(() => {
        // Create listener
        const listener = Hub.listen('datastore', async (hubData) => {
            const { event, data } = hubData.payload;

            if (event === 'modelSynced') {
                console.log(data.model.name);
            }
        });

        // Remove listener
        return () => {
            listener();
        };
    });
```

Perhaps the docs should have stated it clearly

**Comment by xsmcemmons** [comment]
Yep, as @nubpro  says, it works with data.model.name
