### ISSUE TITLE
Error when building amplify-ui-components on Windows

### ISSUE THREAD

**Issue by nubpro** [aws-amplify/amplify-js#7221]
**Describe the bug**
When I run `yarn build` on my `amplify-js` folder on my **Windows** machine. I get these errors:
```
[ ERROR ]  sass error: src/components/amplify-authenticator/amplify-authenticator.scss:1:1
           Can't find stylesheet to import.

      L1:  /**
      L2:   * @prop --background-color: Background color of the container

[ ERROR ]  sass error: src/components/amplify-sign-in/amplify-sign-in.scss:1:1
           Can't find stylesheet to import.

      L1:  /**
      L2:   * @prop --footer-font-family: Font family of the footer
```

I've narrowed down the issue to[ `sass()` in stenci.config.ts](https://github.com/aws-amplify/amplify-js/blob/main/packages/amplify-ui-components/stencil.config.ts#L26-L28).
I reverted it back to `sass()` without any params passed to it.
After removing the `@include md` from some of the components and perform `yarn build`. ~~It builts everything successfully.~~
Well I lied, you need this PR #7222.

<details>
  <summary><strong>Environment</strong></summary>

```
  System:
    OS: Windows 10
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 4.36 GB / 15.95 GB
  Binaries:
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20200509.222254.0 - C:\Users\Chai\AppData\Local\watchman\watchman.EXE
  Browsers:
    Edge: 44.17763.831.0
    Internet Explorer: 11.0.17763.771
```

</details>

**Smartphone (please complete the following information):**
Windows machine

**Comment by wlee221** [comment]
Hi @nubpro, thanks for letting us know. This should be fixed by #7309. I'll look at #7222 tomorrow and check if #7222 + #7309 resolve build issues on windows.
