### ISSUE TITLE
CognitoUser object 'email_verified' attribute not updated to 'true' after user successfully changing email address.

### ISSUE THREAD

**Issue by tatighm** [aws-amplify/amplify-js#7224]
**Describe the bug**
Within my app, user changes their email address. This is all done successfully with all the right 'Auth' calls and after user enters correct verification code. The problem is that after user enters correct verification code, the CognitoUser object does not get updated to reflect 'email_verified: true'. It remains false until user logs out and logs back in.

**To Reproduce**

1) Auth.updateUserAttributes(CognitoUser, {'email": newEmailAddress});
2) User must now enter verification code to app.
3) Auth.verifyCurrentUserAttributeSubmit('email': verificationCode);
4) Auth.currentAuthenticatedUser()-----> CognitoUser attribute 'email_verified' is still false.

**Expected behavior**
Auth.currentAuthenticatedUser() should immediately show 'email_verified': 'true', not after user signs out and back in.

**Code Snippet**
try  {
       
    const currentUser = await Auth.currentAuthenticatedUser();

    await Auth.updateUserAttributes(currentUser, {'email': newEmailAddress});

    // get code from user

    await Auth.verifyCurrentUserAttributeSubmit('email', verificationCode);

    const updatedUser = await Auth.currentAuthenticatedUser();
}

catch(e) {
    // handle error
}

**Additional context**
After user enters correct verification code, they are routed to the dashboard of the app, but route has guard which checks that 'email_verified' attribute. If user is verified according to that attribute, they can navigate anywhere in the app, if not, they are asked to provide that verification code. The latter keeps happening because that attribute stays 'false' until they log out and log back in again. I'm sorry if I sound repetitive but this is my first time opening an issue. I'm an amateur.

**Comment by amhinson** [comment]
@tatighm Could you try using `Auth.currentAuthenticatedUser({ bypassCache: true })`? The behavior without `bypassCache` will just be to grab the current user from what is stored locally, but setting it to `true` will fetch the latest user info from Cognito.

Reference: [documentation](https://docs.amplify.aws/lib/auth/manageusers/q/platform/js#retrieve-current-authenticated-user)

**Comment by tatighm** [comment]
@amhinson Ah, yes! That did it. I had not taken notice of this very critical option for this call. Thank you!
