### ISSUE TITLE
Orphan (and maybe unneccessary) dependency zen-observable-ts has an invalid sourcemap

### ISSUE THREAD

**Issue by justingrant** [aws-amplify/amplify-js#7229]
**Describe the bug**
One of the aws-amplify dependencies, [zen-obsevable-ts](https://github.com/apollographql/apollo-link/tree/master/packages/zen-observable-ts), has an invalid sourcemap. Here's the first line of its sourcemap:
```
{"version":3,"file":"bundle.esm.js","sources":["../src/zenObservable.ts"]
```

This package didn't publish its source code to NPM, so the link to `../src/zenObservable.ts` will cause build-time warnings for some tools like `source-map-loader`.

Normally I'd just file a bug against the zen-obsevable-ts repo, but it's archived. Normally for archived repos, I'd file a PR to Amplify to switch to the new, non-archived repo. But zen-obsevable-ts doesn't seem to have any successor repo.

So I'm filing a bug report here because this repo is probably the only place to fix the problem. 

Looking at https://unpkg.com/zen-observable-ts, there's no executable code; the zen-observable-ts package seems to be solely a TS wrapper to add types around zen-observable. Here's the entire ESM [implementation](https://unpkg.com/zen-observable-ts@0.8.21/lib/bundle.esm.js): 

```js
import zenObservable from 'zen-observable';

var Observable = zenObservable;

export default Observable;
export { Observable };
//# sourceMappingURL=bundle.esm.js.map
```

So it might be possible to remove this package completely and just rely on `zen-observable` and `@types/zen-observable`.

I'm removing the rest of the bug report template since it doesn't seem to apply to this case, but let me know if I should put it back. 

I'll take a stab at PR-ing a fix to this by removing this package and relying on @types/zen-observable instead.

**Comment by sammartinez** [comment]
@nickarocho can you look at this one when you get a chance?

**Comment by justingrant** [comment]
BTW, I didn't have time to PR a fix to this. If I remember correctly, there was some limitation in typing that was easier to work around when it was a separate, typed package. It's possible that someone with better TS skills than me can figure out how to do it without a separate package, though.

**Comment by nickarocho** [comment]
Hi @justingrant I'm just getting caught up to speed on this. I see you have a `draft` PR here: https://github.com/aws-amplify/amplify-js/pull/7235/files

Do you remember if this approach worked locally for you? I'll keep investigating on my side, but just wanted to clarify first.

**Comment by justingrant** [comment]
Sorry I don't remember the details-- it's been a while. If I remember correctly, I couldn't figure out a way to get it to work. I left comments in the PR explaining the problem I ran into. My memory of the TL;DR is that it's easy to solve this via a separate package, but I couldn't figure out how to solve it by directly importing zen-observable without an intermediate package to wrap it with something TS-friendly.

**Comment by justingrant** [comment]
One more note: I think where I left things was that I assumed that adding a new package would be the easiest solution (perhaps just forking zen-observable-ts and fixing the sourcemap) but I wasn't sure how adding a new package would work in context of Amplify, so I left it there. I definitely wasn't ready to fork and take over as maintainer of that package, because I can't commit to ongoing support.

**Comment by nickarocho** [comment]
Thanks for the insight and historical context. I need a little more time to fully understand what kind of scope this will take to resolve, so we appreciate your patience while we sort through it.

**Comment by justingrant** [comment]
Not stale. Hoping that @nickarocho or someone else can help.

**Comment by stocaaro** [comment]
Hello @justingrant ,

Reviewing this, I don't see a reference to [zen-obsevable-ts](https://github.com/apollographql/apollo-link/tree/master/packages/zen-observable-ts).  Is this something amplify used to depend upon that has gone away this past year? Am I missing something?

If I where going to reproduce the steps to run into the issue your describing here, what would I run?  What should I expect to see?

Thanks,
Aaron

**Comment by justingrant** [comment]
Hi @stocaaro - this issue is almost 2 years old, so it's possible that amplify has changed its implementation since then. If you don't see [zen-obsevable-ts](https://github.com/apollographql/apollo-link/tree/master/packages/zen-observable-ts) in your package_lock.json, then I assume that the problem is fixed?

**Comment by stocaaro** [comment]
Thats what I'm seeing. If you see anything different than that, happy to have this reopened with detail on what I'm missing.
Thanks! Aaron
