### ISSUE TITLE
Some translations not working using I18n

### ISSUE THREAD

**Issue by FabioNevesAbreu1** [aws-amplify/amplify-js#7233]
I was trying to translate the amplify-authenticator tag in vue, using I18n.putVocabulariesForLanguage, some translations are ok, but others are not changing,

main.js
```
import { I18n } from "aws-amplify";
import { Translations } from "@aws-amplify/ui-components";

I18n.putVocabulariesForLanguage("en-US", {
  [Translations.SIGN_IN_HEADER_TEXT]: "Entre na sua conta",
  [Translations.SIGN_IN_ACTION]: "Acessar",
  [Translations.SIGN_UP_PASSWORD_PLACEHOLDER]: "Senha",
  [Translations.SIGN_UP_USERNAME_PLACEHOLDER]: "Usuário",
  [Translations.USERNAME_PLACEHOLDER]: "Digite seu usuario",
  [Translations.PASSWORD_PLACEHOLDER]: "Digite sua senha",
  [Translations.FORGOT_PASSWORD_TEXT]: "Mot de passe oublié?",
  [Translations.RESET_PASSWORD_TEXT]: "Resetar senha",  
  [Translations.NO_ACCOUNT_TEXT]: "Sem conta?",
  [Translations.CREATE_ACCOUNT_TEXT]: "Crie sua conta",
  [Translations.SIGN_UP_HEADER_TEXT]: "Crie sua conta agora",
  [Translations.PHONE_LABEL]: "Numero de telefone",
  [Translations.SIGN_UP_HAVE_ACCOUNT_TEXT]: "Ja tem uma conta?",
  [Translations.SIGN_IN_TEXT]: "Entre agora",
  [Translations.SIGN_OUT]: "Sair"

});

I18n.setLanguage("en-US")
```

![Captura de Tela 2020-11-19 às 10 32 53](https://user-images.githubusercontent.com/55453504/99672802-af336d00-2a52-11eb-8d08-93a419b30bc6.png)

![Captura de Tela 2020-11-19 às 10 39 45](https://user-images.githubusercontent.com/55453504/99673478-94152d00-2a53-11eb-9e15-c2d603d49d69.png)

i was taken the https://github.com/aws-amplify/amplify-js/blob/main/packages/amplify-ui-components/src/common/Translations.ts as based

**Comment by samicey** [comment]
Hello @FabioNevesAbreu1 I reproduced the issue and found out that 
you are missing up the Translations property.

You can use the translations below to solve the issue.

I18n.putVocabulariesForLanguage("en-US", {
  [Translations.SIGN_UP_SUBMIT_BUTTON_TEXT]: "Crie sua conta",
  [Translations.SIGN_IN_HEADER_TEXT]: "Entre na sua conta",
  [Translations.SIGN_IN_ACTION]: "Acessar",
  [Translations.SIGN_UP_PASSWORD_PLACEHOLDER]: "Senha",
  [Translations.SIGN_UP_USERNAME_PLACEHOLDER]: "Usuário",
  [Translations.USERNAME_PLACEHOLDER]: "Entre sua Usuário",
  [Translations.PASSWORD_PLACEHOLDER]: "Entre sua senha",
  [Translations.USERNAME_LABEL]: "Digite seu usuario",
  [Translations.SIGN_UP_EMAIL_PLACEHOLDER]: "Entre sua Email",
  [Translations.USERNAME_LABEL]: "Digite seu usuario",  
  [Translations.PASSWORD_LABEL]: "Digite sua senha",
  [Translations.FORGOT_PASSWORD_TEXT]: "Mot de passe oublié?",
  [Translations.RESET_PASSWORD_TEXT]: "Resetar senha",  
  [Translations.NO_ACCOUNT_TEXT]: "Sem conta?",
  [Translations.SIGN_UP_HEADER_TEXT]: "Crie sua conta agora",
  [Translations.PHONE_LABEL]: "Numero de telefone",
  [Translations.SIGN_UP_HAVE_ACCOUNT_TEXT]: "Ja tem uma conta?",
  [Translations.SIGN_IN_TEXT]: "Entre agora",
  [Translations.SIGN_OUT]: "Sair",
  [Translations.CREATE_ACCOUNT_TEXT]: "Crie sua conta"

});

**Comment by mauerbac** [comment]
@FabioNevesAbreu1 - are you able to try Sam's suggestion and let us know if that works ?
