### ISSUE TITLE
DataStore does not restart after re-enabling WiFi on Chrome (React)

### ISSUE THREAD

**Issue by nubpro** [aws-amplify/amplify-js#7243]
**Describe the bug**
DataStore does not restart after I re-enabled my Wi-Fi on my laptop (Windows).
This is a React app.

Is this an expected behaviour, or do I need to get Service Worker configured on my app?

**To Reproduce**

1. Start DataStore.
2. Off Wi-Fi from Windows Taskbar.
3. You'll observe that DataStore tries to reconnect, ignore that.
4. After roughly 15 seconds, turn Wi-Fi back on.
5. DataStore does nothing.
6. Calling `DataStore.start()` manually doesn't help.

Here's a video with logs and everything:
https://streamable.com/a10fvi

**Expected behavior**
I'd expect DataStore to restart the websocket connection.

**Code Snippet**
schema.graphql
```
enum PostStatus {
    ACTIVE
    INACTIVE
}

type Post @model {
    id: ID!
    title: String!
    rating: Int!
    status: PostStatus!
}
```

App.js
```
import React, { useEffect } from 'react';
import './App.css';

import { Hub } from '@aws-amplify/core';
import { DataStore, Predicates } from '@aws-amplify/datastore';
import { Post, PostStatus } from './models';
import { withAuthenticator, AmplifySignOut } from '@aws-amplify/ui-react';

// window.LOG_LEVEL = 'DEBUG';

function onCreate() {
    DataStore.save(
        new Post({
            title: `New title ${Date.now()}`,
            rating: (function getRandomInt(min, max) {
                min = Math.ceil(min);
                max = Math.floor(max);
                return Math.floor(Math.random() * (max - min)) + min;
            })(1, 7),
            status: PostStatus.ACTIVE,
        })
    );
}

function onDeleteAll() {
    DataStore.delete(Post, Predicates.ALL);
}

async function onQuery() {
    const posts = await DataStore.query(Post, (c) => c.rating('gt', 4));

    console.log(posts);
}

function App() {
    useEffect(() => {
        const subscription = DataStore.observe(Post).subscribe((msg) => {
            console.warn('Post subscription:', msg.opType, msg.element);
        });
        return () => subscription.unsubscribe();
    }, []);

    useEffect(() => {
        // Create listener
        const listener = Hub.listen('datastore', async (hubData) => {
            const { event, data } = hubData.payload;

            console.log(event, data);
        });

        // Remove listener
        return () => {
            listener();
        };
    }, []);

    return (
        <div className="App">
            <header className="App-header">
                <div>
                    <input type="button" value="NEW" onClick={onCreate} />
                    <input
                        type="button"
                        value="DELETE ALL"
                        onClick={onDeleteAll}
                    />
                    <input
                        type="button"
                        value="QUERY rating > 4"
                        onClick={onQuery}
                    />

                    <input
                        type="button"
                        value="Clear datastore"
                        onClick={async () => {
                            await DataStore.clear();
                        }}
                    />

                    <input
                        type="button"
                        value="Start datastore"
                        onClick={async () => {
                            try {
                                await DataStore.start();
                            } catch (error) {
                                console.warn(123, error);
                            }
                        }}
                    />

                    <AmplifySignOut />
                </div>
            </header>
        </div>
    );
}

export default withAuthenticator(App);

```

<details>
  <summary><strong>Environment</strong></summary>

```
  System:
    OS: Windows 10 10.0.17763
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 4.79 GB / 15.95 GB
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20200509.222254.0 - C:\Users\Chai\AppData\Local\watchman\watchman.EXE
  Browsers:
    Chrome: 86.0.4240.198
    Edge: Spartan (44.17763.831.0)
    Internet Explorer: 11.0.17763.771
  npmPackages:
    @aws-amplify/ui-react: ^0.2.28 => 0.2.28
    @testing-library/jest-dom: ^5.11.4 => 5.11.6
    @testing-library/react: ^11.1.0 => 11.1.2
    @testing-library/user-event: ^12.1.10 => 12.2.2
    aws-amplify: ^3.3.8 => 3.3.8
    react: ^17.0.1 => 17.0.1
    react-dom: ^17.0.1 => 17.0.1
    react-scripts: 4.0.0 => 4.0.0
    web-vitals: ^0.2.4 => 0.2.4
  npmGlobalPackages:
    @angular/cli: 8.1.3
    @aws-amplify/cli: 4.32.1
    @ionic/angular: 4.10.0
    cordova-res: 0.8.0
    cordova: 9.0.0
    create-react-app: 3.4.1
    create-react-native-app: 3.4.0
    firebase-tools: 7.6.2
    ionic: 5.4.5
    my-project: 0.0.1
    native-run: 0.2.8
    nodemon: 1.19.4
    react-devtools: 4.6.0
    react-native-cli: 2.0.1
    rimraf: 3.0.2
    serve: 11.2.0
    serverless: 1.62.0
    typescript: 4.0.5
    webextension-toolbox: 3.0.0
```

</details>

**Smartphone (please complete the following information):**

- Browser: Chrome, New Edge

**Root cause**
[Reachability implementation](https://github.com/aws-amplify/amplify-js/blob/main/packages/core/src/Util/Reachability.ts#L26-L27) which depends on `navigator.onLine` does not detect when the device loses Wi-Fi. It only works if I go to developer tools and swich to offline under network tab. You can test it here (https://jsfiddle.net/02v3t6h7/).

**Is it also possible to expose an API that allows developer to restart the websocket connection for DataStore?**
Update: I just realize u can "restart" datastore by doing `DataStore.stop()` followed by `DataStore.start()`.

**Comment by iartemiev** [comment]
@nubpro I've tested this on Chrome and Firefox on macOS and Windows and could not reproduce the behavior you're describing. Disabling WiFi triggers the `offline` event and enabling it triggers the `online` event. [According to MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/offline_event), this behavior is supported in all major browser. 

Any chance you remained connected to the internet (e.g., via ethernet) when you were experiencing this while disabling your WiFi?

**Comment by nubpro** [comment]
> @nubpro I've tested this on Chrome and Firefox on macOS and Windows and could not reproduce the behavior you're describing. Disabling WiFi triggers the `offline` event and enabling it triggers the `online` event. [According to MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/offline_event), this behavior is supported in all major browsers.
> 
> Any chance you remained connected to the internet (e.g., via ethernet) when you were experiencing this while disabling your WiFi?
Did you setup service worker?

In my case, I did not.

**Comment by iartemiev** [comment]
This should have nothing to do with the service worker. 

Here's a video of my running your jsfiddle in Edge and Chrome on Windows 10: https://streamable.com/o0dd97. It responds as expected when network connectivity is lost/reestablished.

I don't have access to a physical Windows machine, so I'm running it in a VM but there's no reason the behavior should be any different on a physical machine. I would make sure that your system configuration isn't interfering with these events somehow.

**Comment by nubpro** [comment]
> This should have nothing to do with the service worker.
> 
> Here's a video of my running your jsfiddle in Edge and Chrome on Windows 10: https://streamable.com/o0dd97. It responds as expected when network connectivity is lost/reestablished.
> 
> I don't have access to a physical Windows machine, so I'm running it in a VM but there's no reason the behavior should be any different on a physical machine. I would make sure that your system configuration isn't interfering with these events somehow.

I see, I see.

Anways, it does not detect if you manually off the wifi from the taskbar.
https://streamable.com/lbfjzg

Looking at this stackoverflow post, https://stackoverflow.com/questions/14283124/navigator-online-not-always-working
`Navigator.onLine` does not seem to reliable compared to NetInfo.

Here's another one:
https://stackoverflow.com/questions/2779367/navigator-online-still-true-when-turning-off-wifi-false-when-set-work-offline

**Comment by iartemiev** [comment]
When I toggle WiFi on macOS or iOS, it responds as expected. I only have physical devices that run on those OSs, so, unfortunately, I can't locally test other platforms without a VM. I'll try testing this on Windows using Device Farm to see if I can reproduce that way. 

FWIW those SO questions are from ~8 and 10 years ago respectively, current `navigator.onLine` implementation should be much more stable, but nonetheless, I'll mark this as a feature request and we'll explore other options for detecting internet connectivity in browsers.

**Comment by nubpro** [comment]
> When I toggle WiFi on macOS or iOS, it responds as expected. I only have physical devices that run on those OSs, so, unfortunately, I can't locally test other platforms without a VM. I'll try testing this on Windows using Device Farm to see if I can reproduce that way.
> 
> FWIW those SO questions are from ~8 and 10 years ago respectively, current `navigator.onLine` implementation should be much more stable, but nonetheless, I'll mark this as a feature request and we'll explore other options for detecting internet connectivity in browsers.

I suggest that we take off the `cannot reproduce` label, isnt this actually a bug?

**Comment by iartemiev** [comment]
We've not been able to actually reproduce this. Both myself and several teammates have attempted on Chrome in Windows and everything works as expected. 

Here's my latest attempt a few minutes ago on the latest version of Windows 10 / latest Chrome. This time it's on an actual physical Windows machine, not a VM:

![Windows Chrome DataStore](https://user-images.githubusercontent.com/29709626/106396805-5714d180-63d8-11eb-9383-22362835d06d.gif)

**Comment by nubpro** [comment]
> We've not been able to actually reproduce this. Both myself and several teammates have attempted on Chrome in Windows and everything works as expected.
> 
> Here's my latest attempt a few minutes ago on the latest version of Windows 10 / latest Chrome. This time it's on an actual physical Windows machine, not a VM:
> 
> ![Windows Chrome DataStore](https://user-images.githubusercontent.com/29709626/106396805-5714d180-63d8-11eb-9383-22362835d06d.gif)

Unfortunately I dont have my old PC with me.... and you're right about this.
Since it's a non-issue, I'll close this right away!
