### ISSUE TITLE
Expo Blob S3 upload fails on iOS (Unable to resolve data for blob)

### ISSUE THREAD

**Issue by macsj200** [aws-amplify/amplify-js#7257]
**Describe the bug**
I am selecting an image via `expo-image-picker` `ImagePicker.launchImageLibraryAsync()`. This returns a `result` with a `uri` field set that points to a local image.

I want to resolve `result.uri` into a `Blob` that can be passed into `Storage.put(filename, data)`.

I've tried converting the URI to a `Blob` with these two approaches
```
let picture = await fetch(result.uri);
picture = await picture.blob();
```
```
  const urlToBlob = (url: string) => new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.onerror = reject;
    xhr.onreadystatechange = () => {
      if (xhr.readyState === 4) {
        resolve(xhr.response);
      }
    };
    xhr.open('GET', url);
    xhr.responseType = 'blob'; // convert type
    xhr.send();
  });
  //...
  const picture = await urlToBlob(result.uri);
```
both of the above seem to work the first time but break when I try to reuse the logic to upload another photo. This is the error message I get:
```
Unable to resolve data for blob: 6a275923-2372-4525-b46d-a4f8cf13886b
```

I realize the `Storage.put()` API limitations may be causing issues here. I can potentially look into changing the API to use more standard `fetch()`/`axios`/etc. and upload to a signed URL, but I’m not necessarily confident that I wouldn’t just run into the same issue down the road. Some examples suggest using `FormData()` and appending the files but I have the suspicion that I will run into similar tomfoolery.

Expo does provide a way to access the `base64` representation of the image as `result.base64`. This `base64`-encoded string seems to load more or less consistently even for large image files. However, when I try passing in `Storage.put(filename, result.base64)` the uploaded image file is garbled and can't be opened on subsequent download. I believe this is an encoding issue with the provider config params. https://github.com/aws-amplify/amplify-js/issues/3977#issuecomment-731976492

I tried to get https://github.com/joltup/rn-fetch-blob working but it's not compatible with Expo.

I made a similar post in the Expo forum: https://forums.expo.io/t/issues-uploading-image-to-s3-via-amplify-ios/45738

Another possibly related issue: https://github.com/aws-amplify/amplify-js/issues/5311

**Versions**
iOS `14.0.1`
```
    "expo": "~39.0.2",
    "expo-image-picker": "~9.1.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz",
    "aws-amplify": "^3.3.9",
    "aws-amplify-react-native": "^4.2.9",
```

Thank you for your help.

**Comment by nubpro** [comment]
I can't seem to reproduce this. I have no problem getting Blob to work on my iPhone.

This is my test expo project:
https://pastebin.com/pWsXvpEm

The code:
```
    const pickImage = async () => {
        let result = await ImagePicker.launchImageLibraryAsync({
            mediaTypes: ImagePicker.MediaTypeOptions.All,
            allowsEditing: true,
            aspect: [4, 3],
            quality: 1,
        });
 
        console.log(result);
 
        if (!result.cancelled) {
            setImage(result.uri);
 
            const response = await fetch(result.uri);
            const blob = await response.blob();
            const now = new Date();
 
            console.log('blob', blob);
 
            Storage.put(`${now.toISOString()}.png`, blob, {
                contentType: 'image/png',
            })
                .then((result) => console.log('Upload success', result))
                .catch((err) => console.warn(err));
        }
    };
```

**Comment by macsj200** [comment]
@nubpro Thanks for the response! I noticed I had an intermediate step doing this `const imageData = new File([picture], imageName)`
I wonder if that's what was wrong?

**Comment by macsj200** [comment]
Seems to be working great now, thanks!
