### ISSUE TITLE
Auth methods hanging on Android but not iOS in React Native

### ISSUE THREAD

**Issue by jamesalester** [aws-amplify/amplify-js#7258]
**Describe the bug**
Auth methods such as `signIn` and `signUp` hang on Android in React Native but work fine on iOS.

**Expected behavior**
The `signIn` promise should either resolve or reject but it just hangs continuously.

**What is Configured?**
I'm using amplify in conjunction with Apollo. My app is setup like this:

```
import React from 'react'
import { AppRegistry } from 'react-native'
import Amplify, { Storage } from 'aws-amplify'
import { ApolloProvider } from 'react-apollo'

import { name as appName } from './app.json'
import config from './aws-exports'
import client, { Rehydration } from './src/apollo'
import App from './src/containers/App'

Storage.configure(config)
Amplify.configure(config)
Amplify.Analytics.disable()

const PeekApp = () => (
  <ApolloProvider client={client}>
    <Rehydration>
      <App />
    </Rehydration>
  </ApolloProvider>
)

AppRegistry.registerComponent(appName, () => PeekApp)
```

```
// aws.exports.js

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://xxx.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "eu-west-2:xxx-xxxx-xxxx-xxxx-xxxxxxxx",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_xxx",
    "aws_user_pools_web_client_id": "xxx",
    "oauth": {},
    "aws_user_files_s3_bucket": "xxx",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};
```

I used this [guide](https://dev.to/willsamu/how-to-get-aws-appsync-running-with-offline-support-and-react-hooks-678) to help connect Apollo.

**Smartphone:**

- Device: Pixel 3 Emulator 
- OS: Android API 29

**Additional context**
I put comments inside the signIn function and it seems that it is getting stuck in `node_modules/amazon-cognito-identity-js/src/CognitoUser.js` at line 282 where it calls: 
```
this.client.request('InitiateAuth', jsonReq, (err, data) => {
```
The callback is never called so I'm assuming there's an issue with the client. If anyone has any ideas on how to debug this further I'd be very grateful.

**Comment by amhinson** [comment]
@jamesalester This looks to be the same issue people are seeing in this issue: https://github.com/aws-amplify/amplify-js/issues/5539

Could you add your findings there? We are still trying to reproduce this on our end, but have had no luck so far. I'll close this issue so we can focus on the other one.
