### ISSUE TITLE
Blocker for Upgrading to 3.0 - Storage timeout config

### ISSUE THREAD

**Issue by j2d2** [aws-amplify/amplify-js#7262]
**Is your feature request related to a problem? Please describe.**
I have a production Angular 10 webapp that requires extending the S3 upload timeout longer than the default 2 minutes to support larger files and users on slower connections. This is a blocker for me to upgrade to Amplify JS 3.0. 
Hoping for ideas or workarounds, as trying to maintain my production app with less than the _latest_ Amplify versions is not ideal, and a major headache.

Per the [README](https://github.com/aws-amplify/amplify-js#amplify3xx-has-breaking-changes-please-see-the-breaking-changes-below) the top section "**Amplify @3.x.x has breaking changes**" mentions that 

> AWS.config don’t exist anymore anywhere in Amplify JS
> Both options will not be available to use in version 3. 
> ...Migration plan on “How to migrate to using Amplify provided credentials” will follow in the coming weeks after GA launch.

**Describe the solution you'd like**
I need to configure the S3 upload timeout longer than the default 2 minutes. But AWS.config doesn't exist anymore anywhere in Amplify JS 3.0.
Hoping that there's a migration plan documented, as mentioned in the README.

**Describe alternatives you've considered**
I recently upgraded from 1.3.3, and am currently using:
```
"aws-amplify": "^2.3.0",
"@aws-amplify/api": "^2.2.1",
"@aws-amplify/auth": "^2.1.8",
"@aws-amplify/storage": "^2.2.0",
"@aws-amplify/pubsub": "^1.2.4",
"@aws-amplify/ui-angular": "^0.4.13",
```
I have the config working by setting
```
import Amplify, { AWS } from '@aws-amplify/core';
AWS.config.s3 = { httpOptions: { timeout: 120000 } };
```

**Additional context**
As mentioned, this is critical for our production webapp. We are requesting a documented migration plan, or plan to support this S3 timeout config, or ideas or workarounds that can support us upgrading to the latest. Thanks!

**Comment by jamesaucode** [comment]
Hi @j2d2, in Storage we uses `Axios` as our custom HttpHandler for our s3client, and the default timeout is unlimited. [axios doc](https://github.com/axios/axios/blob/master/README.md#request-config)

I manually tested the behavior by throttling the network speed, and it was able to keep the put request going for 10+ minutes (I didn't test any further than that), but that should work for your use case.

**Comment by j2d2** [comment]
Thanks @jamesaucode ! My recent testing supports your results as well. I'm closing this issue.
