### ISSUE TITLE
Feature Request - Configurable oauthStorage

### ISSUE THREAD

**Issue by camhart** [aws-amplify/amplify-js#7264]
**Is your feature request related to a problem? Please describe.**
I'm trying to use AWS Amplify Auth with Electron with AWS Amplify running on the nodejs side and storing credentials on the local file system.  The `storage` config option has been working great, however `oauthStorage` attempts to use `window.sessionsStorage` which doesn't exist in node.

**Describe the solution you'd like**
Allow an `oauthStorage` custom implementation to be passed through the config, similar to how `storage` can be customized.

**Describe alternatives you've considered**
Well, right now I'm hacking it by setting `global.window = myCustomImplementation` for the initial authentication, then once authenticated I set `global.window = undefined`.  This appears to work, but it's ugly.

**Additional context**
This is 1/3 for Electron support.  See https://github.com/aws-amplify/amplify-js/issues/7265 and https://github.com/aws-amplify/amplify-js/issues/7266 for the other 2/3,

**Comment by harrysolovay** [comment]
Management of `customState` in the OAuth flow is `SessionStorage` for security reasons (this is what we reviewed and deemed reliable). Enabling customization of the storage mechanism for that one field is currently out-of-scope.

**Comment by camhart** [comment]
What's the difference between sessionsStorage and in memory storage from a security perspective?

The react native solution you guys built uses in memory storage.  I'm simply indicating that same in memory solution should be able to be used for electron or any other non-web solution.

I understand electron is out of scope.  However with 3 relatively small/simple changes, amplify could be used for a wide array of different technologies (including electron).

**Comment by harrysolovay** [comment]
It's not about security––it's about persistence. When you redirect away from the site (to get an OAuth code), the OAuth state is lost, unless persisted with a mechanism such as session storage. Upon being redirected (with the code) back to your site, that state needs to be available in order to get a valid access token.

Are you being successfully brought back to your electron app, with the code? If so––and if you think a state storage adapter is the right solution for you––wanna put in a PR? Would be more than happy to review & hopefully get it merged in!

**Comment by camhart** [comment]
> Are you being successfully brought back to your electron app, with the code?
Yes--because Amplify is running on nodejs.  I have electron launch a new window to the hosted sign in ui, then I capture the redirect in that browser window.  The oauth storage is all being handled in nodejs--but nodejs doesn't have window.sessionStorage :D.

>  If so––and if you think a state storage adapter is the right solution for you––wanna put in a PR? Would be more than happy to review & hopefully get it merged in!
I'll give it a go.

**Comment by camhart** [comment]
There are two ways to handle my specific use case:

1. Allow passing a custom implementation of `oauthStorage` through the `OAuthOpts` config.
2. Default to oauthStorage.native.ts **if** window is not defined (ie, not in a browser environment).

To be up front--I don't have any real experience with typescript.   I'm happy with either approach mentioned above.  #1 offers more flexibility--but is that flexibility actually needed?
