### ISSUE TITLE
Cross Origin Read Blocking CORB Error

### ISSUE THREAD

**Issue by strange1120** [aws-amplify/amplify-js#7291]
**Describe the bug**
Trying a very simple set up to storage images and get them out on subsequent page redirect. If I store my S3Object on the Listing type and try to get with `<AmplifyS3Image imgKey={key} /> then I get this error in the browser. "Cross-Origin Read Blocking (CORB) blocked cross-origin response {url} with MIME type image/jpeg. See https://www.chromestatus.com/feature/5629709824032768 for more details."  

Additionally, tried a workaround with getting the url from `Storage.get` on image key and rendering a simple `img` tag and the image isn't loading due to `UNSIGNED_PAYLOAD`  in the url. 

I have searched high and low for days on what I think should be super simple.  I thought that the Storage.get would be a workaround but no success either. I have ran into the CORB error for 3 days straight now. 

**To Reproduce**

My schema 

type S3Object {
  bucket: String!
  region: String!
  key: String!
}

type User
  @model
  @key(
    name: "contactByUser"
    fields: ["contact"]
    queryField: "contactByUser"
  ) {
  id: ID!
  contact: String!
  name: String
  avatar: String
  walletId: String
  income: Int
  bookings: [Booking] @connection(keyName: "byUser", fields: ["id"])
  listings: [Listing] @connection(keyName: "byUser", fields: ["id"])
}

type Booking
  @model
  @key(name: "byUser", fields: ["userID"])
  @key(name: "byListing", fields: ["listingID"]) {
  id: ID!
  listing: Listing! @connection(fields: ["listingID"])
  tenant: User! @connection(fields: ["userID"])
  userID: ID!
  listingID: ID!
  contact: String
  checkIn: String
  checkOut: String
}

type Listing @model @searchable @key(name: "byUser", fields: ["userID"]) {
  id: ID!
  name: String
  title: String
  description: String
  city: String
  address: String
  country: String
  admin: String
  price: Int
  numOfGuests: Int
  authorized: Boolean
  state: String
  photo: S3Object
  host: User! @connection(fields: ["userID"])
  userID: ID!
  type: String
  bookings: [Booking] @connection(keyName: "byListing", fields: ["id"])
  bookingsIndex: String
}

**Expected behavior**

**Code Snippet**
Please provide a code snippet or a link to sample code of the issue you are experiencing to help us reproduce the issue. (Be sure to remove any sensitive data)

```const handleHostListing = async (values) => {
    const fullAddress = `${values.address}, ${values.city}, ${values.state}, ${values.postalCode}`;

    if (file) {
      const { name: fileName, type: mimeType } = file;
      const key = `${uuid()}${fileName}`;
      const fileForUpload = {
        bucket,
        key,
        region,
      };
      // const inputData = { username, avatar: fileForUpload };

      try {
        await Storage.put(key, file, {
          contentType: mimeType,
        });
        const input = {
          ...values,
          address: fullAddress,
          photo: fileForUpload,
        };

        delete input.postalCode;
        delete input.image;

        await communiclimbStore.createListing(input);

        console.log("successfully stored user data!");
      } catch (err) {
        console.log("error: ", err);
      }
    }
  };```

   <AmplifyS3Image imgKey={photo.key} />

This is where the error is happening. 

**Screenshots**
If applicable, add screenshots to help explain your problem.

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.
For Auth all options are enabled for auth users, and read only for non auth users. 
* Which resources do you have configured?
  * If applicable, please provide your `aws-exports` file:
   ```
  const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ed560339-d7b1-4b0b-9139-dd86da9834fc",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_JTORDVu7f",
    "aws_user_pools_web_client_id": "6mrfun7r5apqjmeumvs8u53212",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://u22axd2jxzh57fvynkchw6uuvm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-vesosoycpfc3bm7eu6rhavaadm",
    "aws_user_files_s3_bucket": "communiclimbv28ecff901251545f5ae3cd0192bf33d67191704-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};

export default awsmobile;
   ```

* If applicable, provide more configuration data, for example for Amazon Cognito, run `aws cognito-idp describe-user-pool --user-pool-id us-west-2_xxxxxx` (Be sure to remove any sensitive data)
 

<details>
  <summary><strong>Environment</strong></summary>

<!-- Please run the following command inside your project and copy/paste the output into the codeblock: -->

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

</details>

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6]
- OS: [e.g. iOS8.1]
- Browser [e.g. stock browser, safari]
- Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by harrysolovay** [comment]
Hi @strange1120 –– often times, CORS issues are a matter of your local development server configuration. Can you please try running a production build, `cd`-ing into the build directory, and running `serve` (you'll need to `npm i -g serve`)?

**Comment by strange1120** [comment]
@harrysolovay it is CORB and not CORS, will that make a difference in next steps ?

**Comment by graylancome** [comment]
Having this same issue with CORB. @strange1120 did you get this to work?

**Comment by strange1120** [comment]
@graylancome I would suggest trying their solution. I unfortunately was in a time crunch for school project and had already removed S3 from the project before they responded. I went with cloudinary for image storage with storing url in Dynamo for my solution.

**Comment by sammartinez** [comment]
Hey @strange1120, 

Apologizes on the delay and hearing that you have moved on to use Cloudinary. Let us know if there is anything we can do even though you have moved on to use something else. Thanks
