### ISSUE TITLE
Automating Authentication with Appium

### ISSUE THREAD

**Issue by ajmontero** [aws-amplify/amplify-js#730]
Currently, I do not see of a way to automate the login process when using "withAuthenticator". Does anyone have this working? I do not see any accessibility labels set when looking at the amplify UI code.

**Comment by manueliglesias** [comment]
Hi @ajmontero 

Currently there are no accessibility labels set, We'll take this as a enhancement request

**Comment by elorzafe** [comment]
@ajmontero we will take over this because of merge conflicts and close your PR meanwhile. THanks for your contribution
