### ISSUE TITLE
On network change from offline to online data sync gets fired multiple times.

### ISSUE THREAD

**Issue by ramakrishnan** [aws-amplify/amplify-js#7312]
**Describe the bug**
On network change from online to offline. when `DataStore.stop()` is issued to reevaluate the syncExpression the sync queries upon online gets fired twice, the count increased by additional 1 on every switch from online / offline, or every time a syncExpression is reevaludated.
Plus the Mutation query too happen more than one time.  

**To Reproduce**
```
DataStore.configure({
        maxRecordsToSync: 10000,
        syncPageSize: 500,
        syncExpressions: [
            syncExpression(Todonote, async (c) => {
                const lastTime = await getLastUpdatedTime("Todo")
                return (c) => c.userId('eq', 'User-1').updatedAt("gt", lastTime);
            }, {
                sort: s => s.updatedAt(SortDirection.ASCENDING)
            })
        ]
})
```
1. Launch app.
2. Start sync  `await DataStore.start();`
3. Go offline. do DataStore stop
```
window.addEventListener("offline", async (event) => {
    await DataStore.stop()
})
```
4. Create document `await DataStore.save(new Todo(input))`
5. Bring app back online.
Notice.
The sync query is fired twice, 1. With old updateAt, 2. With new updated At
Two create mutation being called.

**Expected behavior**
During offline one switch `syncExpression` should be run only once.

**Comment by iartemiev** [comment]
Thanks for opening the issue, @ramakrishnan, we will be looking into it. 
As an aside, just want to point out that attempting to pass a sort predicate to the `syncExpression` will not have any effect.

**Comment by amhinson** [comment]
@ramakrishnan I was able to reproduce the issue you are seeing. Thanks for the instruction! 🙏 

One question I have is: why are you calling `DataStore.stop()` when the network connection goes offline? In my testing _without_ calling `stop()`, the app comes back online and syncs appropriately. Offline functionality is already handled by default with DataStore, so there might not be a need for you to manage that here manually.

I'm continuing to look into the original issue, but for the time being, removing that might help you get around any issues you are having.

**Comment by ramakrishnan** [comment]
@amhinson 
Thanks for the response.
I had to do a `DataStore.stop()` in order to reevaluate the syncexpression as mentioned by 
https://docs.amplify.aws/lib/datastore/sync/q/platform/js#selectively-syncing-a-subset-of-your-data
As mentioned in a description above, I need a latest updatedAt to be used on next sync call.

**Comment by amhinson** [comment]
Ah ok. Well the fix is available now with `aws-amplify@unstable`, so let me know if you're still having issues here!
