### ISSUE TITLE
Considerable bundle size increase when upgrading from @aws-amplify/auth@3.2.4 to @aws-amplify/auth@3.4.13

### ISSUE THREAD

**Issue by huoxito** [aws-amplify/amplify-js#7313]
Hi!

We're trying to upgrade to latest `@aws-amplify/auth` and we noticed a considerable build size increase. Our vendor bundle went from 213,58KB to 304,46KB.

Looking into npm it seems the unpacked size went from [2.16 MB](https://www.npmjs.com/package/@aws-amplify/auth/v/3.2.4) to [6.47 MB](https://www.npmjs.com/package/@aws-amplify/auth/v/3.4.14). Any chance there's a way to decrease this bundle size? Maybe opt out some features not needed for some apps. Is there any on going project / task to try decrease that bundle size?

We haven't found any bugs with 3.4.13, so far all good. But since this build increase affects our TTI I was hoping to understand better what happened or how we could make it better moving forward with amplify/js.

**Comment by kushmangal** [comment]
Any update on this?

**Comment by quinnturner** [comment]
More specifically, it's between `3.4.0` and `3.4.2`, or `aws-amplify` `3.1.0` and `3.2.0`.

On `aws-amplify` `3.1.0`, my bundle size is `216kb`. On `aws-amplify` `3.2.0`, my bundle size is `301kb`.

**Comment by PaulTime** [comment]
still having problems with this issue 
![image](https://user-images.githubusercontent.com/26630246/103099983-3dce7780-4619-11eb-80be-a2bef8ea04d9.png)

bundle size increased from 200kb gzip to 440kb gzip after I installed @aws-amplify/auth and called configure() method

**Comment by PaulTime** [comment]
![image](https://user-images.githubusercontent.com/26630246/103100429-24c6c600-461b-11eb-82e0-898a9eb7405a.png)

**Comment by picardplaisimond** [comment]
This is a very important problem in my opinion. I have to support this.
In my case, I only use:
`import Amplify from '@aws-amplify/core'`
`import Auth from '@aws-amplify/auth'`

It increases the size of the application by ***244kb*** ! It's way too much to just handle authentication !
Chrome DevTools tells us that most of the javascript isn't even executed. So it's an optimization problem.

From what I've seen, if we use the `Auth` module, all the functions of this class are imported. There must be a way to optimize that. Maybe with more targeted *dynamic imports* in that class? I'm talking about a big refactoring.

I found nothing else to fix it. If anyone has a better solution, that would be great.
I'm also thinking about using `amazon-cognito-identity-js` on the client to cut over the amplify's overload..

Here are the versions I am currently using:
```
@aws-amplify/auth": "^3.4.16,
@aws-amplify/core": "^3.8.8,
```

**Comment by nnyath** [comment]
I think I've identified part of the issue and have got the ball rolling with a detailed PR here https://github.com/aws-amplify/amplify-js/pull/7521

Thanks everyone for your stats and input; they have helped in corroborating my initial findings :)

**Comment by jamessouth** [comment]
My bundle, from [7484](https://github.com/aws-amplify/amplify-js/issues/7484#issuecomment-757422411).

You can significantly reduce your dev bundle by using `@aws-amplify/auth`, etc., rather than `aws-amplify` as instructed in the [Amplify React docs](https://docs.amplify.aws/start/getting-started/setup/q/integration/react#initialize-a-new-backend).

**Comment by cwomack** [comment]
@huoxito and anyone following this, our team is investigating improvements to the bundle size for Amplify. We will provide you with updates when we have the next steps identified. Thank you all for providing us with this feedback!

**Comment by abdallahshaban557** [comment]
Hello everybody, our team has been focusing on reducing the bundle size of the Amplify library, and starting v 5.2.5, we have been able to reduce the bundle size for the below use cases:

        * Amplify core + Auth category: 73kB → 54kB (-26%)
        * Amplify core + Analytics category: 56kB → 30kB (-46%)

This is only the first step in our bundle size reduction efforts. In our next major version of Amplify JavaScript, we are going to provide better mechanisms for tree-shaking that will substantially reduce the bundle size. Stay tuned - we will provide updates on this issue when we have expected timelines mapped out.

Please try out the newest version of Amplify, and let us know if you are seeing the improvements I've mentioned! Your feedback is essential to helping us improve our library!

**Comment by abdallahshaban557** [comment]
Hello everyone, We have made some additional changes to reduce the bundle size which include reduction to the Storage category as part of aws-amplify@5.3.4. Below are our updated reduction numbers for the gzip bundle size. Please let us know if you are seeing these reductions in your apps.

- Amplify core + Auth category: 73kB → 54kB (-26%)
- Amplify core + Analytics category: 56kB → 30kB (-46%)
- Amplify core + Storage category: 71KB → 29kB (-59%).

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
