### ISSUE TITLE
Auth stopped working with Jest version 26.0.0, with Jest testEnvironment to default.

### ISSUE THREAD

**Issue by p-gag** [aws-amplify/amplify-js#7314]
**Describe the bug**
With default Jest configuration, AWS Cognito authentification stopped working with Jest 26.0.0. I reproduced the same issue using cognitoUser.authenticateUser or Amplify Auth.signIn. The effect is a "NotAuthorizedException: Incorrect username or password.". Note that the issue wont happen with Jest 25.5.4 or with Jest 26.0.0 and testEnvironment: 'node'.

**To Reproduce**

1. Have a project with Jest version 25 or lower and validate that you can sign in with any valid back-end using Amplify or Cognito. Ex:
test("integration-test-cognito", async () =>
{
  Amplify.configure(awsconfig);
  const user = await Auth.signIn(USER, PASSWORD);
});    
2. Make sure your project does NOT set testEnvironment in the jest config.
3. Change to Jest to version 26.0.0
4. See the "NotAuthorizedException: Incorrect username or password."

**Expected behavior**
Authentication continue to work as expected.

**Code Snippet**
See step 1.

**What is Configured?**
Region is us-east-2 and auth type AMAZON_COGNITO_USER_POOLS.
Reproduced on Windows 10.
Typescript (may not be related)

**Comment by harrysolovay** [comment]
Hi @p-gag –– unfortunately this isn't enough information for us to diagnose. If the project is public, can you please provide a link? Otherwise, can you please provide more context. For instance, I don't see where `USER` and `PASSWORD` are defined.

One thing that might be useful––move the `Amplify.configure` call to the outer-most scope. It's meant to be called once. Hopefully you're not calling it within each test case.

**Comment by p-gag** [comment]
Hello, 
Sorry if I removed the user/psw, I did not want to expose our credentials. In my repro, I've removed everything but this test so yes, I call configure only once. 

If I provide a small frontend sample, do you have a existing backend to test it? I have two ways to repro it: with an Amplify backend or directly with cognito in which case we only need a UserPoolId and ClientId with existing user/psw.

**Comment by harrysolovay** [comment]
Can you confirm that the user exists and that the account is confirmed? Are you getting any other log information? Are there other tests executing `Auth` methods (which could potentially set conflicting state)?

**Comment by DmitryGulin** [comment]
I ran into the same issue, trying to create some integration tests requiring login with Cognito User Pool credentials.

Steps to reproduce:
1. Create Cognito User pool: [Tutorial: Creating a User Pool](https://docs.aws.amazon.com/cognito/latest/developerguide/tutorial-create-user-pool.html);
2. Add a new user: [Creating User Accounts as Administrator](https://docs.aws.amazon.com/cognito/latest/developerguide/how-to-create-user-accounts.html);
3. Create User Pool Client: [Configuring a User Pool App Client](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-client-apps.html)
3. the test below succeeds only after adding `testEnvironment: 'node'` to `jest.config.js` file:
```ts
import { AuthenticationDetails, CognitoUser, CognitoUserPool } from 'amazon-cognito-identity-js';

describe.only('integration tests', () => {
    test('can get JWT token', async () => {
        const userName = '<< user name >>';
        const password = '<< password >>';
        const userPoolId = '<< Cognito User Pool ID >>';
        const clientAppId = '<< Cognito User Pool App client ID >>';

        const authenticationDetails = new AuthenticationDetails({
            Username: userName,
            Password: password,
        });
    
        var cognitoUser = new CognitoUser({
            Username : userName,
            Pool : new CognitoUserPool({
                UserPoolId : userPoolId,
                ClientId : clientAppId,
            })
        });

        const idToken: string = await new Promise((resolve, reject) => {
            cognitoUser.authenticateUser(authenticationDetails, {
                onSuccess: function (result) {
                    resolve(result.getIdToken().getJwtToken());
                },
        
                onFailure: function(err) {
                    reject(err);
                },
        
            })
        });

        expect(idToken.length).toBeGreaterThan(100);
    });
})
```

`package.json` dependencies are:
```json
  "dependencies": {
    "amazon-cognito-identity-js": "^4.6.0"
  },
  "devDependencies": {
    "@types/node": "^14.14.37",
    "@types/jest": "^26.0.22",
    "jest": "^26.6.3",
    "ts-jest": "^26.5.4",
    "typescript": "^4.2.3"
  }
```

**Comment by mspoulsen** [comment]
@p-gag I have exactly same issue. Did you find a solution?

**Comment by mspoulsen** [comment]
https://stackoverflow.com/questions/67333167/aws-cognito-returns-notauthorizedexception-incorrect-username-or-password-whe

**Comment by chrisbonifacio** [comment]
If you need to call the real service in order to test Auth, we recommend doing so through e2e tests with a framework such as Cypress. Unit testing the Auth library would only work in a node testing environment but since Amplify is intended to be a front end tool, the jest environment is probably best set to 'jsdom' in order to unit test your components.

In that case, you should be mocking the Auth methods in order to include them in your 'jsdom' environment unit tests.

**Comment by mattstobbs** [comment]
@chrisbonifacio Why does the Auth library only work in node? We've just updated to jest 26 and now we're getting these same problems, but switching the environment to node causes problems (e.g. we lose `global.window`).

**Comment by alexjball** [comment]
I am writing integration tests for my client-side data layer so it is convenient to both render hooks and use the non-mocked amplify sdk. By following [this comment](https://github.com/aws-amplify/amplify-js/issues/6552#issuecomment-686153238), I am able to get auth working in a jsdom environment with Jest 28 by using the node Uint8Array implementation rather than jsdom's:

```ts
import { EnvironmentContext, JestEnvironmentConfig } from '@jest/environment'
import BrowserEnvironment from 'jest-environment-jsdom'

class IntegrationEnvironment extends BrowserEnvironment {
  constructor(config: JestEnvironmentConfig, context: EnvironmentContext) {
    Object.assign(config.projectConfig.globals, {
      // https://github.com/aws-amplify/amplify-js/issues/6552#issuecomment-686153238
      Uint8Array: Uint8Array
    })
    super(config, context)
  }
}

export default IntegrationEnvironment
```
