### ISSUE TITLE
Setting custom ownerField breaks DataStore sync

### ISSUE THREAD

**Issue by iartemiev** [aws-amplify/amplify-js#7315]
**Describe the bug**
Using DataStore with an API with owner-based auth containing a custom `ownerField` currently breaks sync. 

**To Reproduce**
Create a sync-enabled API with the following schema:
```graphql
type Test 
@model
@auth(rules: [{ allow: owner, ownerField: "editor" }])
{
  id: ID!
  editor: String
}
```
Followed by calling `DataStore.start()` from the app.

This results in the following error:
```
DataStore - subscriptionError Connection failed: {"errors":[{"message":"Validation error of type FieldUndefined: Field 'owner' in type 'Test' is undefined @ 'onUpdateTest/owner'"}]}
```

This is due to us automatically adding an `owner` field to the GQL selection sets for all operations when that field isn't explicitly defined in the schema.

**Expected behavior**
DataStore should sync correctly when specifying a custom owner field via `ownerField`.
Instead of generating the selection set with `owner`, we should generate it with whatever the value of `ownerField` is if it's not explicitly defined in the schema.

**Comment by amhinson** [comment]
Closing with #7317
