### ISSUE TITLE
AmplifyAuthenticator(@aws-amplify/ui-react) not work on Internet Explorer 11

### ISSUE THREAD

**Issue by Mulyu** [aws-amplify/amplify-js#7320]
**Describe the bug**
An error occurs when using AmplifyAuthenticator in Internet Explorer 11.

**To Reproduce**

1. install `@aws-amplify/ui-react`
2. add `AmplifyAuthenticator` component to index.tsx
3. open with IE11

**Expected behavior**

**Code Snippet**
```
import 'react-app-polyfill/ie11';
import 'react-app-polyfill/stable';

import './index.css';
import * as serviceWorker from './serviceWorker';
import Amplify from 'aws-amplify';
import React from 'react';
import ReactDOM from 'react-dom';
import awsconfig from './aws-exports';
import createRootStore from './store';
import { Provider } from 'react-redux';

import 'bootstrap/dist/css/bootstrap.min.css';
import { AmplifyAuthenticator } from '@aws-amplify/ui-react';

Amplify.configure({
  ...awsconfig,
});

const store = createRootStore();

ReactDOM.render(
  <React.StrictMode>
    <Provider store={ store }>
      <AmplifyAuthenticator />
    </Provider>
  </React.StrictMode>,
  document.getElementById('root'),
);

serviceWorker.unregister();

```

**Screenshots**
![スクリーンショット 2020-12-02 165347](https://user-images.githubusercontent.com/6552219/100847503-440e7f80-34c3-11eb-9d89-0786fcd0bde9.png)

**Smartphone (please complete the following information):**

- OS: Windows 10
- Browser Internet Explorer 11
- Version 
  - @aws-amplify/ui-react: 0.2.15
  - aws-amplify: 3.0.24

**Additional context**
There seems to be an error in css-shim-xxx.js generated by stencil.

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by harrysolovay** [comment]
This is a transpilation configuration issue and is therefore out of scope. That being said, I'd love to point you in the right direction! Can you please describe your project? Is its build system using react-scripts (create-react-app), Gatsby, NextJS, etc.?

**Comment by Mulyu** [comment]
Thanks for the help!
I use create-react-app for this build.
And package.json is as follows.
```
{
  "name": "xxxx",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@aws-amplify/ui-react": "^0.2.15",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "@types/aws-sdk": "^2.7.0",
    "@types/jest": "^24.0.0",
    "@types/node": "^12.0.0",
    "@types/react": "^16.9.48",
    "@types/react-dom": "^16.9.0",
    "@types/react-dropzone": "^5.1.0",
    "@types/styled-components": "^5.1.2",
    "@typescript-eslint/eslint-plugin": "^3.10.1",
    "@typescript-eslint/parser": "^3.10.1",
    "aws-amplify": "^3.0.24",
    "aws-sdk": "^2.744.0",
    "babel-polyfill": "^6.26.0",
    "bootstrap": "^4.5.2",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-babel": "^5.3.1",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-react": "^7.20.6",
    "eslint-plugin-react-hooks": "^4.1.0",
    "eslint-plugin-sort-imports-es6-autofix": "^0.5.0",
    "eslint-plugin-unused-imports": "^0.1.3",
    "promise-polyfill": "^8.2.0",
    "react": "^16.13.1",
    "react-app-polyfill": "^2.0.0",
    "react-bootstrap": "^1.3.0",
    "react-dom": "^16.13.1",
    "react-dropzone": "^11.0.3",
    "react-redux": "^7.2.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "3.4.3",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0",
    "reselect": "^4.0.0",
    "styled-components": "^5.1.1",
    "typescript": "~3.9.7",
    "uuid": "^8.3.0"
  },
  "scripts": {
    "start": "REACT_APP_ENV=development react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version",
      "ie 11"
    ]
  },
  "devDependencies": {
    "@types/react-redux": "^7.1.9",
    "@types/react-router-dom": "^5.1.5",
    "@types/redux-mock-store": "^1.0.2",
    "@types/uuid": "^8.3.0",
    "redux-mock-store": "^1.5.4"
  }
}

```

**Comment by harrysolovay** [comment]
I don't know if the browserlist actually changes the transpilation (conversion of modern JS to versions compatible with IE 11).

I'd recommend looking into tools such as [rescripts](https://github.com/harrysolovay/rescripts) and [react-app-rewired](https://github.com/timarney/react-app-rewired#readme). They'll let you update the [Babel](https://babeljs.io/docs/en/) configuration such that the target / output code is compatible!

The aforementioned tools are necessary because react-scripts (CRA) has a pretty strict configuration lock-in. They want it to be easy for developers to get up and running and evolve their applications according to best practices, without needing to know too much about the world of transcompilers. This poses some difficulty when users decide they want access to the knobs.

Hopefully this gets you up & running. Closing this issue for now. That being said, please feel free to ping this issue with more questions & I'll do my best to be helpful.
