### ISSUE TITLE
Auth.forgotPassword() does not throw any exception if the user does not exist and Prevent User Existence Error is Disabled

### ISSUE THREAD

**Issue by lucre74** [aws-amplify/amplify-js#7323]
**Describe the bug**
A call to Auth.forgotPassword(username) must not succeed if the user does not exist. Otherwise, there is no way to tell the user that something went wrong (most probably the user does not exist). 

Currently, the call raises a "UserNotFoundException" if the Prevent User Existence Errors is LEGACY on the AppClient of the User Pool. The call succeeds if the Prevent User Existence Errors is ENABLED on the AppClient of the User Pool. It must fail with a generic error message like "NotAuthorizedException".

**To Reproduce**
Code: 
 1     Auth.forgotPassword("not_a_valid_user")
 2       .then(data => {
 3           console.log(`onForgotPassword::Response#1: ${JSON.stringify(data, null, 2)}`);
 4         })
 5       .catch(err => {
 6           console.log(`onForgotPassword::Error#1: ${JSON.stringify(err, null, 2)}`);
 7         });

This  correctly throws an error when Prevent User Existence Errors is LEGACY:
onForgotPassword::Error#1: {
  "code": "UserNotFoundException",
  "name": "UserNotFoundException",
  "message": "Username/client id combination not found."
}

Incorrectly succeeds when Prevent User Existence Errors is DISABLED:
onForgotPassword::Response#1: {
  "CodeDeliveryDetails": {
    "AttributeName": "email",
    "DeliveryMedium": "EMAIL",
    "Destination": "n***@h***.com"
  }
}

**Expected behavior**
The call to forgotPassword(invalid_user) must fail when the Prevent User Existence Errors is ENABLED on the AppClient of the User Pool with a generic error message like "NotAuthorizedException".

**Comment by harrysolovay** [comment]
If the User Pool's `PreventUserExistenceErrors` is enabled, then we wouldn't want to call out the request as faulty. This would give bad actors a way to validate whether a given username is registered. Aka., this is the correct behavior.

If you do want to enable special handling of this case on the client, I'd recommend leaving `PreventUserExistenceErrors` enabled and catching and handling the error as you see fit. Or, you can implement an endpoint that that calls `AdminGetUser` (to check if the user exists) and does some special handling per-your use case.
