### ISSUE TITLE
Amplify subscription is not working

### ISSUE THREAD

**Issue by Anybowdy** [aws-amplify/amplify-js#7324]
I am trying to make a basic subscription using AWS Amplify when an object is updated.
I should get a response containing the new updated object but instead, I get a provider object.

To make the update, I use the App sync console.

```
useEffect(() => {
    const subscription = API.graphql(graphqlOperation(onUpdateParty)).subscribe({
      next: (party) => {
        console.log(party);
      },
    });

    return () => {
      subscription.unsubscribe();
    };
  }, []);
```

The fetched object is the following: 

`Object {
  "provider": AWSAppSyncRealTimeProvider {
    "_config": Object {
      "aws_appsync_apiKey": ...
      "aws_appsync_authenticationType": "API_KEY",
      "aws_appsync_graphqlEndpoint": ...
      "aws_appsync_region": "eu-west-2",
      "aws_cognito_identity_pool_id":
      "aws_cognito_region": "eu-west-2",
      "aws_project_region": "eu-west-2",
      "aws_user_pools_id": ...
      "aws_user_pools_web_client_id": ...
      "oauth": Object {},
    },
    "awsRealTimeSocket": WebSocket {
      "CLOSED": 3,
      "CLOSING": 2,
      "CONNECTING": 0,
      "OPEN": 1,
      "_eventEmitter": NativeEventEmitter {
        "_nativeModule": Object {
          "addListener": [Function nonPromiseMethodWrapper],
          "close": [Function nonPromiseMethodWrapper],
          "connect": [Function nonPromiseMethodWrapper],
          "getConstants": [Function anonymous],
          "ping": [Function nonPromiseMethodWrapper],
          "removeListeners": [Function nonPromiseMethodWrapper],
          "send": [Function nonPromiseMethodWrapper],
          "sendBinary": [Function nonPromiseMethodWrapper],
        },
        "_subscriber": EventSubscriptionVendor {
          "_currentSubscription": null,
          "_subscriptionsForType": Object {
            "RCTDevMenuShown": Array [
              EmitterSubscription {
                "context": undefined,
                "emitter": RCTDeviceEventEmitter {
                  "_currentSubscription": EmitterSubscription {
                    "context": undefined,
                    "emitter": [Circular],
                    "eventType": "websocketMessage",
                    "key": 2,
                    "listener": [Function anonymous],
                    "subscriber": [Circular],
                  },
                  "_subscriber": [Circular],
                  "sharedSubscriber": [Circular],
                },
                "eventType": "RCTDevMenuShown",
                "key": 0,
                "listener": [Function connectToDevTools],
                "subscriber": [Circular],
              },
            ],
            "appStateDidChange": Array [
              EmitterSubscription {
                "context": undefined,
                "emitter": AppState {
                  "_eventHandlers": Object {
                    "blur": Map {},
                    "change": Map {},
                    "focus": Map {},
                    "memoryWarning": Map {},
                  },
                  "_nativeModule": Object {
                    "addListener": [Function nonPromiseMethodWrapper],
                    "getConstants": [Function anonymous],
                    "getCurrentAppState": [Function nonPromiseMethodWrapper],
                    "initialAppState": "active",
                    "removeListeners": [Function nonPromiseMethodWrapper],                  },
                  "_subscriber": [Circular],
                  "_supportedEvents": Array [
                    "change",
                    "memoryWarning",
                    "blur",
                    "focus",
                  ],
                  "currentState": "active",
                  "isAvailable": true,
                },
                "eventType": "appStateDidChange",
                "key": 0,
                "listener": [Function anonymous],
                "subscriber": [Circular],
              },
            ],
            "collectBugExtraData": Array [
              EmitterSubscription {
                "context": null,
                "emitter": RCTDeviceEventEmitter {
                  "_currentSubscription": EmitterSubscription {
                    "context": undefined,
                    "emitter": [Circular],
                    "eventType": "websocketMessage",
                    "key": 2,
                    "listener": [Function anonymous],
                    "subscriber": [Circular],
                  },
                  "_subscriber": [Circular],
                  "sharedSubscriber": [Circular],
                },
                "eventType": "collectBugExtraData",
                "key": 0,
                "listener": [Function collectExtraData],
                "subscriber": [Circular],
              },
            ],
            "collectRedBoxExtraData": Array [
              EmitterSubscription {
                "context": null,
                "emitter": RCTDeviceEventEmitter {
                  "_currentSubscription": EmitterSubscription {
                    "context": undefined,
                    "emitter": [Circular],
                    "eventType": "websocketMessage",
                    "key": 2,
                    "listener": [Function anonymous],
                    "subscriber": [Circular],
                  },
                  "_subscriber": [Circular],
                  "sharedSubscriber": [Circular],
                },
                "eventType": "collectRedBoxExtraData",
                "key": 0,
                "listener": [Function collectExtraData],
                "subscriber": [Circular],
              },
            ],
            "devLoadingView:hide": Array [
              EmitterSubscription {
                "context": undefined,
                "emitter": NativeEventEmitter {
                  "_nativeModule": Object {
                    "addListener": [Function nonPromiseMethodWrapper],
                    "getConstants": [Function anonymous],
                    "hide": [Function nonPromiseMethodWrapper],
                    "removeListeners": [Function nonPromiseMethodWrapper],                    "showMessage": [Function nonPromiseMethodWrapper],
                  },
                  "_subscriber": [Circular],
                },
                "eventType": "devLoadingView:hide",
                "key": 0,
                "listener": [Function handleHide],
                "subscriber": [Circular],
              },
            ],
            "devLoadingView:showMessage": Array [
              EmitterSubscription {
                "context": undefined,
                "emitter": NativeEventEmitter {
                  "_nativeModule": Object {
                    "addListener": [Function nonPromiseMethodWrapper],
                    "getConstants": [Function anonymous],
                    "hide": [Function nonPromiseMethodWrapper],
                    "removeListeners": [Function nonPromiseMethodWrapper],                    "showMessage": [Function nonPromiseMethodWrapper],
                  },
                  "_subscriber": [Circular],
                },
                "eventType": "devLoadingView:showMessage",
                "key": 0,
                "listener": [Function handleShowMessage],
                "subscriber": [Circular],
              },
            ],
            "didCompleteNetworkResponse": Array [
              undefined,
              undefined,
              undefined,
              undefined,
              undefined,
              undefined,
              undefined,
            ],
            "didReceiveNetworkData": Array [
              undefined,
              undefined,
              undefined,
              undefined,
              undefined,
              undefined,
              undefined,
            ],
            "didReceiveNetworkDataProgress": Array [
              undefined,
              undefined,
              undefined,
              undefined,
              undefined,
              undefined,
              undefined,
            ],
            "didReceiveNetworkIncrementalData": Array [
              undefined,
              undefined,
              undefined,
              undefined,
              undefined,
              undefined,
              undefined,
            ],
            "didReceiveNetworkResponse": Array [
              undefined,
              undefined,
              undefined,
              undefined,
              undefined,
              undefined,
              undefined,
            ],
            "didSendNetworkData": Array [
              undefined,
              undefined,
              undefined,
              undefined,
              undefined,
              undefined,
              undefined,
            ],
            "didUpdateDimensions": Array [
              EmitterSubscription {
                "context": undefined,
                "emitter": RCTDeviceEventEmitter {
                  "_currentSubscription": EmitterSubscription {
                    "context": undefined,
                    "emitter": [Circular],
                    "eventType": "websocketMessage",
                    "key": 2,
                    "listener": [Function anonymous],
                    "subscriber": [Circular],
                  },
                  "_subscriber": [Circular],
                  "sharedSubscriber": [Circular],
                },
                "eventType": "didUpdateDimensions",
                "key": 0,
                "listener": [Function anonymous],
                "subscriber": [Circular],
              },
            ],
            "keyboardDidHide": Array [
              undefined,
              EmitterSubscription {
                "context": undefined,
                "emitter": NativeEventEmitter {
                  "_nativeModule": Object {
                    "addListener": [Function nonPromiseMethodWrapper],
                    "getConstants": [Function anonymous],
                    "removeListeners": [Function nonPromiseMethodWrapper],                  },
                  "_subscriber": [Circular],
                  "dismiss": [Function dismissKeyboard],
                  "scheduleLayoutAnimation": [Function anonymous],
                },
                "eventType": "keyboardDidHide",
                "key": 1,
                "listener"...(truncated to the first 10000 characters)`

Need help

**Comment by amhinson** [comment]
@Anybowdy There should also be a `value` object in what is returned, based on the Amplify code:
https://github.com/aws-amplify/amplify-js/blob/daca2ab654159dfdb43527b42703497c105c2bf6/packages/pubsub/src/PubSub.ts#L175

Is that there for you?

**Comment by Anybowdy** [comment]
Thank you @amhinson, how come this is not mentionned in AWS Amplify Docs ?

**Comment by amhinson** [comment]
Good idea! Just put up a PR to add more details there. Thanks @Anybowdy 🙏 

https://github.com/aws-amplify/docs/pull/2736
