### ISSUE TITLE
Unable to authenticate using either amplify init or amplify pull

### ISSUE THREAD

**Issue by neighlyd** [aws-amplify/amplify-js#7326]
**Describe the bug**
I am attempting to create a new amplify app. I am following along with the [Build a Full-Stack App](https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/) tutorial on AWS' website.

However, when I attempt to "initialize the local app", as discussed in module 3, I am unable to proceed.

If I try to use `amplify init --appId XXXXXX` I receive the following error:

```
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

Failed to fetch Amplify Admin credentials
init failed
Error: TypeError: Cannot read property 'idToken' of undefined
```

If I create the backend app through the Console UI and then run `amplify pull --appId XXXXX`, I am taken to a login page that does not accept either my AWS username/password or an IAM account (with or without password set). It returns `Incorrect username or password.`

I have made sure that the IAM account and amplify app are on the same region (`us-west-2`)

**Comment by neighlyd** [comment]
Addendum:

If I run `amplify init` without an `--appId` flag specified, it fails with the following error:

```
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use default
init failed
MissingRequiredParameter: Missing required key 'name' in params
```

**Comment by harshhpaatel** [comment]
Have the same issue happening

**Comment by neighlyd** [comment]
1) It appears I submitted this issue to the wrong library (go figure). It ought to be in `aws-amplify/amplify-cli`. My bad!

2) It looks like this is an issue with the most recent version (4.37.0). If you run `amplify configure` and `amplify init` without creating the project in the console things _should_ work. You just then need to go to the console to create the FE application. See [issue 6037](https://github.com/aws-amplify/amplify-cli/issues/6037)
