### ISSUE TITLE
Datastore Query sort showing 'SortDirection' is not defined

### ISSUE THREAD

**Issue by DevTGhosh** [aws-amplify/amplify-js#7335]
**Describe the bug**
When using the datastore query sort it is showing `'SortDirection' is not defined` 

**To Reproduce**
Datastore code 
```
import { DataStore, Predicates } from '@aws-amplify/datastore'

    const quoteInfo = await DataStore.query(QuoteInfoModel, Predicates.ALL, {
      sort: (row) => row.tableRowIndex(SortDirection.ASCENDING),
    })
```

Schema

```
type Quote @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  name: String!
  quoteInfo: [QuoteInfo] @connection(keyName: "byQuote", fields: ["id"])
}

type QuoteInfo @model @key(name: "byQuote", fields: ["quoteId"]) @auth(rules: [{ allow: owner }]) {
  id: ID!
  quoteId: ID!
  tableRowIndex: Int
}
```

**Comment by iartemiev** [comment]
@DevTGhosh you need to import `SortDirection` from `@aws-amplify/datastore` before you can use it.

**Comment by DevTGhosh** [comment]
Thank you I tried that but must have messed the spelling up. I dunno maybe we need to mention about importing `SortDirection` and `Predicates` in the docs there isn't a lot of info available on it.

Also another question can you chain another filter with sorting 

For e.g fetching posts by type and then sorting according to rating 
```
const posts = await DataStore.query(Post, c => c.postType("eq", "Intro"));

const posts = await DataStore.query(Post, Predicates.ALL, {
  sort: s => s.rating(SortDirection.ASCENDING)
});
```

How would you combine both these queries?

**Comment by iartemiev** [comment]
> can you chain another filter with sorting

Yes, you can do:
```js
const posts = await DataStore.query(Post, c => c.postType("eq", "Intro"), {
  sort: s => s.rating(SortDirection.ASCENDING)
});
```

**Comment by DevTGhosh** [comment]
Thanks a lot! Maybe the team could consider adding these examples in the docs? The doc examples are very straight forward. Closing the issue for now.
