### ISSUE TITLE
[Typing Issue] EventAttributes interface should require value to be `string` not `any`

### ISSUE THREAD

**Issue by gnomishperson** [aws-amplify/amplify-js#734]
https://github.com/aws/aws-amplify/blob/d5d27d622f1643251d42274333bbf1c6427404ec/packages/aws-amplify/lib/Analytics/types/Analytics.d.ts#L12-L14

https://github.com/aws/aws-amplify/blob/d5d27d622f1643251d42274333bbf1c6427404ec/packages/aws-amplify/lib/Analytics/Analytics.d.ts#L56

```javascript
let attributes = { 'stringKey': { another: customObject } }
Analytics.record('customEventName', attributes)
```

`attributes` matches the ```[key: string]: any; ``` 

However, this fails to record the event with an error stating that the value of `'stringKey'` is not a string, but the typing would lead you to believe it did not have to be.

Should probably be:
```typescript
export interface EventAttributes { 
     [key: string]: string; 
}
```

**Comment by elorzafe** [comment]
Hi @gnomishperson I will take a look on your pr.

Thank you!
