### ISSUE TITLE
How to catch PubSub errors if MQTT connection lost or broken? (Re-report of #2692)

### ISSUE THREAD

**Issue by blacksheep--** [aws-amplify/amplify-js#7341]
This is a re-report of #2692 as the issue was erroneously closed, because the mentioned PR #6448 did not touch the necessary file MqttOverWSProvider.ts (which has not been touched since 20th March 2020).

---

** Which Category is your question related to? **
PubSub connection problems

** What AWS Services are you utilizing? **
PubSub in aws-amplify 1.1.19

** Provide additional details e.g. code snippets **
What is the best way to keep PubSub connection alive by using aws-amplify? Or is there even any way?

I am using similar code as you mention in the documentation:
PubSub.subscribe(['myTopic1','myTopic1']).subscribe({ next: data => console.log('Message received', data), error: error => console.error(error), // this never logs anything) close: () => console.log('Done'), // this never logs anything) })

However, I have the problem that clients Internet connection can be lost for a short period of time and then these can no longer receive messages. For example, if portable Wifi router switch connection from 4G to 3G, I get the following message in console:
ConsoleLogger.js:88 [WARN] 14:36.405 MqttOverWSProvider - ... { "errorCode": 4, "errorMessage": "AMQJS0004E Ping timed out.", "uri": "wss://..." }
I would like to catch these connection problems somehow in order to subscribe to topics again so that I can keep connection alive.

**Comment by mauerbac** [comment]
Hey - sorry for the delay. After reading through it, are you able to upgrade to latest and confirm it's still an issue?

**Comment by chrisbonifacio** [comment]
Closing this for now as we haven't heard back from you. Please re-open if you're still in need of assistance.

**Comment by tsc329** [comment]
Same issue here, is there any solution can catch the Warn?

**Comment by tsc329** [comment]
Same issue here, is there any solution can catch the WARN?
