### ISSUE TITLE
Sync query not updated after calling DataStore.configure() with new SyncExpression

### ISSUE THREAD

**Issue by dmcd2** [aws-amplify/amplify-js#7345]
**Describe the bug**
Trying to update a DataStore sync expression when a user logs in does not have the effect of changing the initial table sync.

In our application would would like to filter records from a contacts table when the user logs in. Ideally we only want the contact for the user currently logged in to be held in DataStore. I am trying to achieve this using a sync expression on the initial fetch where the table is filtered against a contact ID which is pulled from a Cognito user attribute.

When the user logs out, the store is cleared using DataStore.clear(). On next log in (same browser) the sync expression is set using DataStore.configure() based on the user's contact attribute. What I am finding is that the sync query sent to AppSync is the same as the first user to login, and does not match what I set with configure() for the second user. My second call to configure doesn't seem to have any effect.

The documentation says that you can change the sync at runtime if you call stop() or clear() first and then configure(). This does not seem to be working in my case.

Is what I'm trying to achieve possible with DataStore? The above behaviour seems like a bug to me. I'm open to a different approach if sync expressions are not the correct way to approach this.

**To Reproduce**

1. Login as user 1
2. Check that user has the correct contact ID from user attribute
3. Check syncContact contains the correct filter parameter 
4. Check IndexedDB contains only the contact record for the user
5. Log out
6. Check IndexedDB has been removed
7. Login as user 2
8. Check that user has the correct contact ID from user attribute 
9. Check syncContact contains the correct filter parameter - Fail, still has user 1 contact ID 
10. Check IndexedDB contains only the contact record for the user - Fail, still contains user 1 details.

**Expected behavior**
Setting the sync expression on each login should return data that matches the last set filter.

**Code Snippet**

```
// contact ID pulled from user attribute

DataStore.clear();
DataStore.configure({
  syncExpressions: [
    syncExpression(Contact, () => {
      return (c) => c.id('eq', userContactId)
    })
  ]
});
DataStore.start();
```

This is called after user authentication through Ampilfy

**Additional context**
Desktop browser: Chrome on Mac (87.0.4280.67)
aws-amplify: 3.3.11
aws-amplify-react: 4.2.15
amplify cli: 4.37.1

**Comment by amhinson** [comment]
@dmcd2 See this [comment](https://github.com/aws-amplify/amplify-js/discussions/7128#discussioncomment-123377) from a similar issue. Basically, you shouldn't call `DataStore.configure()` more than once. You can set `userContactId` as a globally scoped variable, and then just update its value anytime you change users. The function you pass to `syncExpression` will be re-evaluated each time you run `DataStore.start()`.

**Comment by dmcd2** [comment]
@amhinson thanks, exactly what I needed.
