### ISSUE TITLE
Getting invalid_request / invalid_grant Errors from Amplify Hosted UI On Mobile Devices Whenever OTP Code Is Used

### ISSUE THREAD

**Issue by Caoimhin89** [aws-amplify/amplify-js#7350]
**Describe the bug**
I have a web app built with AWS Amplify that relies on Amplify Hosted UI for authentication.

I started receiving complaints from users that they are not able to register or sign-in from their mobile devices. On desktop/laptop, everything seems to work fine. After testing more heavily on mobile I eventually encountered an error.

I noted that I was getting `invalid_request` and `invalid_grant` errors on mobile, even though registration seemed to work. (I received AWS credentials in the initial response and amplify-signin-with-hostedUI was set to true in localStorage. However, the request to /token came back with a 400 error with the `invalid_request` and `invalid_grant` messages. I kept poking around and eventually found something interesting. 

On mobile, when I try to register or login with the Cognito Hosted UI, I am first met with the Federated Identity Provider buttons and email/password page, as expected. When I sign-up through one of these methods, **if I am prompted for an OTP code**, then after I enter it and I'm redirected back to the my web-app, the app can see from the localStorage that the I'm logged in and loads the correct view (the user profile component), but it does not get populated with any data, it's just empty (which means that the authenticated request to get that data has failed - that request uses COGNITO_USER_POOLS as the authorization mechanism). At this point, if I refresh the page in the hopes of triggering a new request for the profile data, I instead get the `invalid_grant` error mentioned above.

It seems to me that the key to the problem is the OTP code. I do not encounter this error when logging in with Facebook or Google where my accounts are set up to keep me logged in. I get it instead when I log in with Amazon, which requires an OTP code and when I try with email and password, which requires an email confirmation code to be typed in before my account is considered active.

Also to note - if I open the AWS Console and go to my Cognito User Pool, I can see that I have successfully registered. However, I'm just not able to sign-in due to something about the OTP flow.

**To Reproduce**

1. Go to (I can provide this privately, if necessary.)
2. Click on Register / Login on the upper-right of the page
3. Login or Register through any of the provided means in the Hosted UI which will send you an OTP code
4. Enter the OTP code when prompted
5. Upon redirect, check DevTools Network Tab or JS Console to see errors

**Expected behavior**
I expect the user to successfully register & signin and to be met with either a user dashboard (if a profile is already associated with his/her account) or a profile creation form, if this is a newly registered user.

**Code Snippet**
Everything happens within the Amplify Hosted UI auth flow, so my application code isn't invoked during this process.

**Screenshots**

**What is Configured?**

Here is my sanitized aws-exports file:
   ```
   {
    "aws_project_region": "us-xxxxx-x",
    "aws_content_delivery_bucket": "xxxxxxxx-prod",
    "aws_content_delivery_bucket_region": "us-xxxxx-x",
    "aws_content_delivery_url": "http://xxxxxxxxxxxx.s3-website-us-*****-*.amazonaws.com",
    "aws_appsync_graphqlEndpoint": "https://xxxxxxxxxxxx.appsync-api.us-xxxxx-x.amazonaws.com/graphql",
    "aws_appsync_region": "us-xxxxx-x",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "xxx-xxxxxxxxxxxxxxxxxxxxxxxxxx",
    "aws_cognito_identity_pool_id": "us-xxxxx-x:xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "aws_cognito_region": "us-xxxxx-x",
    "aws_user_pools_id": "us-xxxxx-x_xxxxxxxx",
    "aws_user_pools_web_client_id": "xxxxxxxxxxxxxxxxxxxxx",
    "oauth": {
        "domain": "xxxxxxx-prod.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://website.com/",
        "redirectSignOut": "https://website.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "xxxxxxx-imagesxxxxxxx-prod",
    "aws_user_files_s3_bucket_region": "us-xxxxx-x",
    "aws_mobile_analytics_app_id": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
    "aws_mobile_analytics_app_region": "us-xxxxx-x"
}
   ```

<details>
  <summary><strong>Environment</strong></summary>

```
@amplify/cli: v4.37.0
aws-sdk:  v2.701.0
```

</details>

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy Note8
- OS: Android 7.1.1
- Browser: Chrome
- Version 86.0.4240.198

**Additional context**

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by sammartinez** [comment]
Hey @Caoimhin89, This seems to be related to Amazon Cognito specifically instead of Amplify JavaScript. Amplify JavaScript acts as a proxy to Amazon Cognito. We suggest you open an issue via the [AWS Forums for Cognito](https://forums.aws.amazon.com/forum.jspa?forumID=173).

Thanks,
Amplify team
