### ISSUE TITLE
Sending formData over API.post

### ISSUE THREAD

**Issue by shweta-codeprism** [aws-amplify/amplify-js#7353]
**Bug Description**
Getting xhr status 0 on sending formData over API.post

**Code Snippet**
``` javascript
import API from '@aws-amplify/api'

const formData= new FormData()
formData.append('data1', 'dat1content')

API.put('MyApi', '/api_route', {body: formData})
```

**Expected behavior**
Getting a proper html response code.

**Additional context**
1. Using the Latest version of amplify ( which also has the avoid stringyfying FormData Fix #6899 ), so request payload successfully contains the formdata.
2. Also tried with adding multipart/form-data as a binary type to the apigateway created.

**Comment by ericclemmons** [comment]
Hmmm, yes this one's tricky. We need to validate if `boundary` is necessary for this to work or not:
> https://stackoverflow.com/questions/47630163/axios-post-request-to-send-form-data

In the meantime, if you're constructing `FormData` from scratch, JSON would be the best workaround.

**Comment by shweta-codeprism** [comment]
Currently, worked around with sending the csv as string with FileReader and forwarding the request in json format
```javascript
    var reader = new FileReader();
    reader.readAsText(file); // the file from input
    reader.onload = () => {
      console.log("On Completion of File Reading")
    };
```
