### ISSUE TITLE
Manage 404 page in Next app deployment

### ISSUE THREAD

**Issue by MrHertal** [aws-amplify/amplify-js#7358]
Hi,

I am following these [instructions](https://docs.amplify.aws/guides/hosting/nextjs/q/platform/js) to deploy a Next app with the CLI.

Everything works great.

However, I have a question regarding 404 page. I have set up a custom 404 page which is correctly exported by Next in the `/out` folder. This 404 is showing well in `dev` mode when I try to access a wrong URL.

After deploying my app with `amplify publish`, I try to access a wrong URL and I'm getting a 403 `AccessDenied`. It seems logical since the deployment is only static.

So my question is: is there any way to be redirected to /404 when accessing a wrong URL?

Thanks for your help.

**Which Category is your question related to?**

Hosting

**Amplify CLI Version** 

4.37.1

**Comment by attilah** [comment]
This seems to be an Amplify JS related question, perhaps something we could enhance in the guide as well.

**Comment by bobbyhadz** [comment]
You can add a custom redirect for folders and paths that can't be found and map it to your `/404.html` page.

In your AWS Amplify console - click on the app and then click **Rewrites and redirects**. Add the `/<*>` source address to map to `/404.html` target address (your next.js custom page), with the type of **404 (Rewrite)**. 

The rewrites and redirects for my site look like:
![redirects](https://user-images.githubusercontent.com/25652656/101636796-7e809b00-3a34-11eb-9f88-28791b6988d9.png)

**Comment by MrHertal** [comment]
Hi @bobbyhadz, thanks for suggesting that solution.
I guess this would work when there is no dynamic routing.

But let's say you have a dynamic route such as `/posts/[id].js` and you want to redirect to your 404 page when user tries to access a non existing id.

In that case, instead of showing a 403 forbidden, Amplify could add a server rule that redirect to `/404`.

**Comment by bobbyhadz** [comment]
Hello @MrHertal ,

On my site [bobbyhadz.com](https://bobbyhadz.com) I use Next.js to `export` to static html files. My `fallback` property in the return value of the `getStaticPaths` function in Next.js is set to false. 

I do have a dynamic route - `/blog/[slug].js` - [an-existing-blog-path](https://bobbyhadz.com/blog/hosting-nextjs-amplify) which does `404` when I go to [non-existing-blog-path](https://bobbyhadz.com/blog/non-existing-blog-path/) because all the static files are generated at build time since `fallback` is set to false.

As far as I'm aware Amplify hosting only supports fully static Next.js apps at the moment, and any of the features that require a server are not supported - like `fallback` set to true.

**Comment by MrHertal** [comment]
Is your blog hosted by Amplify? @bobbyhadz

**Comment by bobbyhadz** [comment]
@MrHertal Yes, it is hosted on Amplify, which uses S3 and Cloudfront under the hood, pushes to my [blog-repo](https://github.com/bobbyhadz/bobbyhadz.com) initialize the build and deploy to Amplify.

**Comment by MrHertal** [comment]
Thanks @bobbyhadz problem solved!
I added exactly the same redirect rule as you and it works.

I misunderstood those redirect rules and thought I would have to explicitly add a rule for each URL.
But it actually works with dynamic routing as you told me.

**Comment by kashkashio** [comment]
@bobbyhadz Solution is right besides for me setting it to 404 redirect and not rewrite worked.

**Comment by situplastik** [comment]
That solution doesn't work for me... I have a NextJs with a custom 404 error page (`pages/404.js`), some root pages and dinamic subfoder urls. For non-exist URL subpages created dynamically (with fallback = false) works like a charm, but not for non-exist pages from root folder (I guess that fallback force to use custom 404 page)

I tested @bobbyhadz solution **Type to 404 (Rewrite)**, but the browser get dark and looking in netwook console show a `404 Not found`.

Testing different options of **Rewrites and redirects**, I found 2 configuration that done half of the job:

- **/404 in Target address and 404 (Redirect) in Type** after the automatic rule that amplify creates. But with this configuration, the non-exist root URLs are changed to /404... It would be better keeping the non-existent URL but show the custom 404 page:
![Captura de Pantalla 2021-09-06 a les 17 20 19](https://user-images.githubusercontent.com/19546264/132238285-355ff100-af90-4da2-b956-ecf93aa381ed.png)

- **Type to 200 (Rewrite)**. In that case, the non-exist root URLs keep the URL, but shows the 404 NextJs default page (I have a custom one as I said). In Target address I tested **/404 or /404.html** and the result is the same:
![Captura de Pantalla 2021-09-06 a les 17 27 21](https://user-images.githubusercontent.com/19546264/132239238-ed5b4fb9-eec1-4e26-8b42-2db2bf9069a1.png)
![Captura de Pantalla 2021-09-06 a les 17 29 11](https://user-images.githubusercontent.com/19546264/132239241-1fb98000-41fe-41c5-9f65-0eadccf12edf.png)

Any idea why it doesn't show the custom URL? exporting NextJs locally and looking for the `/out` files, `/404.html` page are created correctly 🤔

**Comment by fanismahmalat** [comment]
If anyone is asking, I found a solution that works for me. Basically you need to remove the rule for redirecting to 404 completely in Rewrites and redirects. Next.js will handle the 'not found' itself.

**Comment by situplastik** [comment]
Totally agree @fanismahmalat , leaving just the first one Nextjs catch all non-existing URLs, but the root non-existing URLs (as `https://domain.com/blablabla`) show the default 404 page (not the custom 404 error page that I have created).

Have you got a custom 404 page and works as expected if you load a non-existent root URL?

**Comment by situplastik** [comment]
Ok, I found by myself a solution, but it looks like NextJs have some bug.... on Amplify Rewrites, I just left the first Rewrite as @fanismahmalat said.

Just if anyone have the same issue:

## NextJs app features

- Custom 404 page `pages/404.js` but not an _error custom page `pages/_error` (it wasn't logical to create it because all the possible errors in Amplify SSR service would be 404; 500 errors aren't possible).
- Some root pages and dynamic subpages created with `fallback: false` attribute.

With that conditions, subpages 404 work well, but root 404 shows the default 404 error page

## Solution

- add `/pages/_error.js` keeping `/pages/404.js`

With that, 404 subpages (`fallback:false`) use custom `/pages/404.js` component, beside 404 root pages use custom `/pages/_error.js` component.

**Comment by ACPK** [comment]
> y you need to remove the rule for redirecting to 404 completely in Rewrites and redirects. Next.js will handle the 'not found' itself.

This causes the following error:

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>d34df34</RequestId>
<HostId>
wQJadfadfkadfjkkjhadfjkadfNixAvhfvXR6i0=
</HostId>
</Error>

**Comment by fanismahmalat** [comment]
@ACPK where do you see this error? what technologies are you deploying on amplify?

**Comment by ndquang14** [comment]
> @fanismahmalat If I remove the 404 redirect tool, I get the AWS error below:
> 
> ```
> <Error>
> <Code>AccessDenied</Code>
> <Message>Access Denied</Message>
> <RequestId>d34df34</RequestId>
> <HostId>
> wQJadfadfkadfjkkjhadfjkadfNixAvhfvXR6i0=
> </HostId>
> </Error>
> ```

Hi @ACPK , did you resolve this issue, I'm having the same issue, pls gimme any ideals

**Comment by ndquang14** [comment]
> @MrHertal Yes, it is hosted on Amplify, which uses S3 and Cloudfront under the hood, pushes to my [blog-repo](https://github.com/bobbyhadz/bobbyhadz.com) initialize the build and deploy to Amplify.

Hi @MrHertal your link has been removed, can u gimme some examples for this, thank u so much!
