### ISSUE TITLE
Verify email using verifyUserAttribute is not working

### ISSUE THREAD

**Issue by FadilaNuzha** [aws-amplify/amplify-js#7361]
**Describe the bug**
I'm developing the project using angular 10. I have set MFA to verify the phone number on sign up. I am trying to verify the user's email using verifyUserAttribute(). I have passed the attribute as 'email'. Still I'm receiving the verification for the mobile number, not the email

**Expected behavior**
To receive an email with a verification code

**Code Snippet**
![image](https://user-images.githubusercontent.com/13960624/101476521-e4591e00-3973-11eb-89cb-888673fff99f.png)

**What is Configured?**
region: 'ap-southeast-1',
userPoolId: 'ap-southeast-1_F2TbXwZqE',
userPoolWebClientId: '2ccjdsd32ju2gaks6md4o95k5b',
mandatorySignIn:true,

**Smartphone (please complete the following information):**
- Browser [chrome]
- Version [87.0.4280.88 (Official Build) (64-bit)]

**Comment by StriderHND** [comment]
Hello, I would like to report that I have the same issue as @FadilaNuzha, tried to use `Auth. verifyCurrentUserAttribute` and having the same my case I'm building an App in React Native.

**Comment by harrysolovay** [comment]
Has the phone number yet been confirmed? If not, then the account itself is "unconfirmed" (and the lack of a confirmation email would be expected).

**Comment by StriderHND** [comment]
The Phone Number on the account was "unconfirmed" once updated but no confirmation code was delivered.

**Comment by FadilaNuzha** [comment]
> Has the phone number yet been confirmed? If not, then the account itself is "unconfirmed" (and the lack of a confirmation email would be expected).

@harrysolovay yes, phone number is confirmed. i was trying to confirm the email

**Comment by mauerbac** [comment]
This is expected behavior and I've shared the feedback with the UI team. Please feel free to open a new issue with future concerns.
