### ISSUE TITLE
AuthError - no matter what I do now

### ISSUE THREAD

**Issue by lbatasu** [aws-amplify/amplify-js#7367]
**Describe the bug**
I am not sure what update/npm install or otherwise caused this to happen, however, I am unable to get auth working on an existing project or even on a new project. I receive the following message when loading the app:

[ERROR] 24:32.124 AuthError - 
            Error: Amplify has not been configured correctly. 
            The configuration object is missing required auth properties. 
            Did you run `amplify push` after adding auth via `amplify add auth`?
            See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information

**To Reproduce**
1. Create-react-app
2. Amplify configure (do steps to configure)
3. Amplify add auth (accept defaults) - and then do amplify push
4. Load app that contains WithAuthenticator tags
5. Attempt to create a new account
6. Receive "Authentication Error" across top banner - stuck.

**Expected behavior**
1. Create-react-app
2. Amplify configure (do steps to configure)
3. Amplify add auth (accept defaults) -  - and then do amplify push
4. Load app that contains WithAuthenticator tags
5. Attempt to create a new account
6. Account is created and can login

**Screenshots**
![image](https://user-images.githubusercontent.com/72431257/99852016-3a306800-2b24-11eb-8319-b6b318872585.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.7
 - Browser Chrome
 - Version Version 86.0.4240.198 (Official Build) (x86_64)

**Additional context**

- I have deleted ALL of my AWS resources to attempt to start from scratch and am having the same issue. 

- I have also deleted the node modules and performed npm install.
- I have created a new project and tried this again to no avail.

**Comment by amhinson** [comment]
@lbatasu Could you share your `package.json`?

**Comment by lbatasu** [comment]
I was able to resolve this late last week. I uninstalled and reinstalled the aws-amplify package and then added auth. I noticed that one of the errors (I don't have a screen shot) mentioned no user pools. Even though I had created the auth with default config, I decided to go through the auth config via amplify auth update. I walked through all configurations and added a user pool and was then able to move forward. 
I am not sure if the user pool is always needed - and if the default config does not create one - or if what I did was a workaround - in any event - smooth sailing after adding the user pool.
Please feel free to close this out. 

If anyone else is hitting this and sees an error related to no user pools, perhaps try to go through the config and add one.
