### ISSUE TITLE
"API <name> does not exist" but configuration seems OK

### ISSUE THREAD

**Issue by marianoc84** [aws-amplify/amplify-js#7370]
’m trying to introduce some Amplify features (without Amplify CLI) into a vanilla JS app. I managed Auth (sign in/up/out) without a problem, now I want to use API REST module to make a call to a pre-existing API Gateway resource (in this test environment I used the PetStore API).
This is the code that I have:
```
import Amplify from '@aws-amplify/core';
Amplify.configure({
    Auth: {
       ...
    },
    API: {
        endpoints: [
            {
                name: "PetStore", // name of the API in API Gateway console
                endpoint: "https://XXX.execute-api.eu-central-1.amazonaws.com/dev",
                region: "eu-central-1",
                paths: ['/']
            }
        ]
    }
});
```
and somewhere else:
```
import Api from '@aws-amplify/api-rest'; 
Api.get('PetStore', '/pets', {})
   .then(response => {
       console.log(response)
   }).catch(error => {
       console.log(error);
   });
```
it builds (Webpack) without problems, but, when executed I get 

> API PetStore does not exist

It seems a common issue even if it sounds like a silly error I made. There are any caveats?

**Comment by zero-t4** [comment]
i've catch the same issue, any workarounds here?

**Comment by zero-t4** [comment]
Ok, i solved it, by recreating `aws-exports.js` file with `amplify env pull command`

**Comment by chrisbonifacio** [comment]
I get this error when I use `import API from "@aws-amplify/api-rest"`
Fixed it with `import { API } from "@aws-amplify/api"`
