### ISSUE TITLE
When I use sign in with apple in amplify, it jumps to safari, so it is rejected by the App Store review.

### ISSUE THREAD

**Issue by shinpeiyamagiwa** [aws-amplify/amplify-js#7373]
```
Auth.federatedSignIn({provider: 'SignInWithApple'});
```
When I use this code, it jumps to safari, so it will be rejected by the app review.
Is there a way to use sign in with apple without jumping to safari?
<img width="826" alt="スクリーンショット 2020-12-10 0 52 55" src="https://user-images.githubusercontent.com/49158626/101652822-0ccf3e00-3a82-11eb-9142-59d2ce3f563f.png">

**Comment by amhinson** [comment]
@shinpeiyamagiwa Yes! We have a section in the docs about setting up an in app browser so that the OAuth flow happens within your app instead of jumping over to Safari: https://docs.amplify.aws/lib/auth/social/q/platform/js#full-samples

**Comment by mcarlstein** [comment]
Hello i use the in app browser but still got rejected. :( 

Anyone have the same problem and know how to fix it? 

response from apple. 

![Skärmavbild 2020-12-10 kl  11 20 09](https://user-images.githubusercontent.com/4611678/101759366-cb6a7d00-3ad9-11eb-821a-7efa1767151d.png)

**Comment by amhinson** [comment]
@mcarlstein Could you share a code snippet of your Amplify configuration and `Auth. federatedSignIn()` usage?

**Comment by mcarlstein** [comment]
` Auth.federatedSignIn({ provider: 'SignInWithApple' })`

**then config** 

` Amplify.configure({
    // OPTIONAL - if your API requires authentication
    Auth: {
      // REQUIRED - Amazon Cognito Identity Pool ID
      identityPoolId: AWS_AUTH.identityPoolId,
      // REQUIRED - Amazon Cognito Region
      region: AWS_AUTH.region,
      // OPTIONAL - Amazon Cognito User Pool ID
      userPoolId: AWS_AUTH.userPoolId,
      // OPTIONAL - Amazon Cognito Web Client ID
      userPoolWebClientId: AWS_AUTH.userPoolClientId
    },
    API: {
      endpoints: [
        {
          name: API_CONSTS.wmaApiAlarm.name,
          region: AWS_AUTH.region,
          endpoint: API_CONSTS.wmaApiAlarm.endpoint
        }
      ]
    },
    storage: MyStorage,
    oauth: {
      domain: AWS_AUTH.appWebDomain,
      scope: ['phone', 'email', 'profile', 'openid'],
      redirectSignIn: 'yourSchemeurl://', // 'exp://127.0.0.1:19000/--/', // 'wake-me-app://',
      redirectSignOut: 'yourSchemeurl://', //'exp://127.0.0.1:19000/--/', //'wake-me-app://',
      responseType: 'code', // or 'token', note that REFRESH token will only be generated when the responseType is code
      urlOpener: urlOpener
    },
  })`

**urlOpener**

`const urlOpener = async (url, redirectUrl) => {
  await InAppBrowser.isAvailable()
  const { type, url: newUrl } = await InAppBrowser.openAuth(url, redirectUrl, {
    showTitle: false,
    enableUrlBarHiding: true,
    enableDefaultShare: false,
    ephemeralWebSession: false
  })

  if (type === 'success') {
    Linking.openURL(newUrl)
  }
}`


i guess they complain about this popup. 

![Simulator Screen Shot - iPhone 8 - 2020-12-10 at 20 39 36](https://user-images.githubusercontent.com/4611678/101821176-e6fc7480-3b27-11eb-812d-5aff7e6b3451.png)

**Comment by amhinson** [comment]
Thanks for all the info @mcarlstein! 🙏 

This is the first I've heard of Apple rejecting this behavior. We will look further into alternative solutions for this, but unfortunately it is not likely to be simple due to how Cognito currently handles the OAuth2 flow. For the time being if you are in a bind, you could call `Auth.federatedSignIn()` without the `provider` to show the Cognito Hosted UI, in which the user can then select "Sign In With Apple" to continue the flow. This might require the UI to be reworked a bit, however.

**Comment by mcarlstein** [comment]
Yes okey thanks!  

Maybe apple just having a bad day. I will try to contact them to get more information about this. 

Will post here when i have more.

**Comment by mcarlstein** [comment]
@amhinson 

just talk to an apple representative and when you log in with apple, you must not go through any external steps, but you must enter directly into the app. However, it is okay to go through extra steps when logging in with google or facebook. So now I do not really know how to solve this. Is it possible to use  https://github.com/invertase/react-native-apple-authentication instead in any way?

**Comment by nubpro** [comment]
@mcarlstein Have you stumbled on any workaround yet?

**Comment by gki** [comment]
Hi @nubpro @mcarlstein @amhinson

In my project, I would like to share that Apple has accepted "Sign in with Apple" with a little change.

In `urlOpener`, I changed `ephemeralWebSession` to `true`, so that iOS doesn't show the dialog before opening in-app browser.
At least, about Jan, 2 React Native apps I involved have been accepted with this change.

```
async function urlOpener(url, redirectUrl) {
  await InAppBrowser.isAvailable();
  const { type, url: newUrl } = await InAppBrowser.openAuth(url, redirectUrl, {
    showTitle: false,
    enableUrlBarHiding: true,
    enableDefaultShare: false,
    ephemeralWebSession: true, // update
  });

  if (type === 'success') {
    Linking.openURL(newUrl);
  }
}
```

### Detail
in iOS, `ephemeralWebSession` has these pros/cons.

#### ephemeralWebSession === true
- No confirmation dialog.
- User **_MUST_** provide authentication info like ID/PW, Touch ID or Face ID etc, **_EVERY TIME_**.

#### ephemeralWebSession === false
- iOS shows the confirmation dialog. **_(EVERY TIME, Even if for logout!!!!)_**
- iOS will reuse auth info if exists. That means user only needs to provide authentication info at first time.

So I recommend to check the url before calling `InAppBrowser.openAuth()` and set `ephemeralWebSession` dynamically depends on the `url`.

**Comment by mcarlstein** [comment]
> @mcarlstein Have you stumbled on any workaround yet?

No sorry I have not.

**Comment by magrinj** [comment]
I'm trying to get a similar behaviour with the native library for Facebook, Google and Apple and using `federatedSignIn` with legacy provider like so:

Facebook example:
```javascript
  const facebookLogin = async () => {
    const result = await Facebook.logInWithReadPermissionsAsync({
      permissions: ['public_profile', 'email'],
    });

    console.log(result);

    if (result.type === 'success') {
      const {data} = await facebookMe({
        accessToken: result.token,
        fields: ['name', 'email', 'picture', 'first_name', 'last_name'],
      });

      await Auth.federatedSignIn(
        'facebook',
        {token: result.token, expires_at: result.expirationDate.getTime()},
        {name: data.name ?? '', email: data.email ?? ''},
      );
    }

    return result;
  };
  ```
  
  But for now it's not really working for me, on Facebook I got an error saying `Token is not from a supported provider of this identity pool` even with everything setup properly...
  On google it seams to work, but `federatedSignIn` just return the same token as the `idToken` provided by google, without any `accessToken` or `refreshToken`.

**Comment by mkrn** [comment]
For anyone looking to use a native Sign In with Apple (SIWA), here's the work-around:

- Use [this package](https://github.com/invertase/react-native-apple-authentication), or native SIWA code with Swift and decode the idToken from Apple, to get the email and name of your user.
- Sign in with amplify with authenticationFlowType: "CUSTOM_AUTH",
- You'll have to implement 3 lambdas to define auth challenge, create auth challenge, and verify auth challenge response
- Add them as hooks to your Cognito user pool
- If your sign-in errors out with UserNotFoundException then sign Up with randomized password
- If your sign in receives challengeName CUSTOM_CHALLENGE, respond with the idToken you've got from apple
- In your verify challenge response hook use `verifyAppleToken` npm package to validate the token
- In your define auth hook, issue the tokens, voila = you're signed in with your cognito user!
You might have to verify nonce for extra security

Unfortunately, it's NOT possible to use native SIWA with federatedSignIn (it must use hosted UI, for Cognito auth backend to generate cognito users linked to identities). I've tried many workarounds, with no luck.

**Comment by DatMoser** [comment]
I am actually SUPER disappointed by this conclusion. Even though I am very thankful for @mkrn and his thoughts, I really don't get why Amplify makes it so incredibly hard to provide a custom authentication flow, because Firebase already showed us how easy it can be done and I am quite shocked at how bad of a job Amplify is doing at this, especially as I do not want to settle for the mediocre UX that the HostedUI would provide my users. 

Nevertheless, thanks to everybody contributing

**Comment by abdallahshaban557** [comment]
Hi @DatMoser - we share your frustration about how complex it is to setup CUSTOM_AUTH currently with Amplify. We have multiple conversations happening internally now to find ways to streamline this experience for our customers.

**Comment by pjsandwich** [comment]
Has there been any movement on this? I'm confused as to why there is documentation describing how to implement Apple Sign In with Amplify while every preliminary discussion I've looked at prior to attempting implementation seems to have its own issues. I'm personally interested in why [this](https://github.com/aws-amplify/amplify-js/issues/4689#issuecomment-720591131) doesn't work.

A better question is: If I follow the [Expo CLI full sample code](https://docs.amplify.aws/lib/auth/social/q/platform/react-native/#full-samples), will this work? I'm assuming not, or this issue would be closed.

For anyone looking at a variety of attempted solutions, here are some related issues:
[#4689](https://github.com/aws-amplify/amplify-js/issues/4689) , [#6637](https://github.com/aws-amplify/amplify-js/issues/6637) , [#4580 ](https://github.com/aws-amplify/amplify-js/issues/4580), [#6547](https://github.com/aws-amplify/amplify-js/issues/6547)

Considering Apple is now going to enforce all apps submitted to App Store to have Apple Sign In as an authentication option, I'd expect this to be a high priority item, however it seems like this is now entering its third year of issues... Hope there's some progress soon.

**Comment by jadechip** [comment]
@abdallahshaban557 has there been any updates internally regarding this? It still doesn't appear possible to login without having to go through Safari on iOS.

**Comment by pjsandwich** [comment]
@jadechip I was able to implement following the docs, however, If you have an existing iOS project you will need to generate new provisioning certificates, may be different process if you're doing bare RN vs Expo

**Comment by kewur** [comment]
@pjsandwich any specific docs you followed for this?

**Comment by pjsandwich** [comment]
> @pjsandwich any specific docs you followed for this?

https://docs.amplify.aws/lib/auth/social/q/platform/react-native/#oauth-and-federation-overview and select Sign in with Apple. If you have an existing app, you won't need to create some of the Apple resources or keys, but you will need to generate new provisioning certificates.

**Comment by itsramiel** [comment]
Has there been any solutions to not show an external/in-app browser?

**Comment by nadetastic** [comment]
Hi @itsramiel currently tracking this issue, are you implementing 'InAppBrowser.openAuth()' from 'react-native-inappbrowser-reborn' as shown in the docs?


[1] https://docs.amplify.aws/lib/auth/social/q/platform/react-native/#full-samples

**Comment by itsramiel** [comment]
@nadetastic yes I am.

Just to make it clear for you. When I use `InAppBrowser.openAuth()`, it will open the in app browser and then show the native ios login, not the web based login which is nice.

https://user-images.githubusercontent.com/80689446/215415748-81b139b3-eac2-4413-bba2-f72fd08cbd67.MP4


What I am wondering and looking for is to never have the `InAppBrowser` open at all. Can't it make the auth call without opening a browser. It is not nice UX.

**Comment by abdallahshaban557** [comment]
Hello everyone, we are working closely with the Amazon Cognito team to resolve this pain point. We understand that the Sign In With Apple experience through hosted UI is a sub-optimal experience, and we are working on enabling a mechanism for helping you use it natively in your apps. We will provide updates on this issue as we make progress.

**Comment by nadetastic** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! The `Auth.federatedSignIn()` method has been renamed to `signInWithRedirect` which displays the sign-in UI inside a platform-dependent webview. On iOS devices, an [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession) will be launched and, on Android, a [Custom Tab](https://developer.chrome.com/docs/android/custom-tabs/).

Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/react-native/build-a-backend/auth/add-social-provider/)for more information.

**Comment by DarrKing** [comment]
Is it really not possible to provide a way for us to pass an identity token from sign in with apple to the amplify SDK ?

**Comment by aldensully** [comment]
@DarrKing did you ever figure anything out? A year later and I'm still coming back to this hoping for a solution that doesn't involve a webview 😭

**Comment by kewur** [comment]
should be possible with custom auth flows. a lot of work on your end. we decided to just ditch cognito and move to supabase instead. it's the only part we're not using aws for, but totally worth the decision

**Comment by aldensully** [comment]
@kewur I am now looking to do the same thing. Are you using amplify or handling the setup manually? I'm not quite sure how I should handle passing off the auth from supabase to cognito (or if I even need to). Any help is appreciated!

**Comment by DarrKing** [comment]
@aldensully @kewur @aldensully Just to update.

After a lot of time wasted I gave up and used firebase auth. Superfast and easy to use. Couldn't achieve what I wanted with amplify sadly.

**Comment by aldensully** [comment]
@DarrKing Are you just using firebase for auth and the rest is still amplify?

**Comment by DarrKing** [comment]
> @DarrKing Are you just using firebase for auth and the rest is still amplify?

Firebase entirely for auth. Gave up on amplify completely for anything auth related.

**Comment by joaoschaab** [comment]
That's crazy that we still don't have a proper way to handle apple sign-in. I wish I knew that before implementing a lot of stuff with Cognito. That sucks.

**Comment by kewur** [comment]
> @kewur I am now looking to do the same thing. Are you using amplify or handling the setup manually? I'm not quite sure how I should handle passing off the auth from supabase to cognito (or if I even need to). Any help is appreciated!

we've never used amplify for anything other than the UI code for fetching tokens.

**Comment by coalfocks** [comment]
Same issue as @BPagoaga, our app is a capacitor port of our web app, and Apple will reject the app until it uses the in-app browser. It seems the fix was made specifically for react native, but not for anything else.
