### ISSUE TITLE
https://aws.github.io/aws-amplify/media/storage_guide questions

### ISSUE THREAD

**Issue by kaihendry** [aws-amplify/amplify-js#738]
I can't find a place to ask questions about Amplify and its storage API, so here goes:

* Do you support S3 transfer acceleration?
* Do you have any simple Lambda upload examples where credentials are assumed from the lambda role? Or is a Cognito configuration always required?
* Do you support direct client side uploads to S3 from a browser? 
* Can you handle large videos when uploading?

**Comment by manueliglesias** [comment]
Hi @kaihendry 

>Do you support S3 transfer acceleration?

It is currently not supported. Amplify leverages the aws-sdk-js package and that one [supports it](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putBucketAccelerateConfiguration-property), so it should be doable in Amplify

>Do you have any simple Lambda upload examples where credentials are assumed from the lambda role? Or is a Cognito configuration always required?

[Pending reponse]

>Do you support direct client side uploads to S3 from a browser?

Yes, this is currently supported in Amplify. Take a look at this repo with a sample app that does that using amplify https://github.com/aws-samples/aws-amplify-graphql

>Can you handle large videos when uploading?

Currently, for files bigger than 5mb, the underlying aws-sdk-js uses multipart upload

**Comment by kaihendry** [comment]
Thank you for answering my questions!

> Currently, for files bigger than 5mb, the underlying aws-sdk-js uses multipart upload

Does multipart upload work from the _client side browser_? Can it for example resume?

**Comment by M1chaelTran** [comment]
It looks like there's an issue with multipart upload on the client side.
The second part is cancelled when the first part response... 
Since the second part got cancelled, a delete request is then sent out.

Would very much interested in knowing a workaround for this issue

**Comment by mlabieniec** [comment]
We have a feature-request for better multi-part upload support, tracking on:
https://github.com/aws-amplify/amplify-js/issues/61
