### ISSUE TITLE
Unable to install aws-amplify and aws-amplify-react-native in expo project with the latest expo and amplify versions

### ISSUE THREAD

**Issue by amin79** [aws-amplify/amplify-js#7381]
I'm trying to run this command in my expo project:

npm install --save aws-amplify aws-amplify-react-native

But I get the following error:

While resolving: undefined@undefined
Found: react-native@0.63.2
node_modules/react-native
  react-native@"https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz" from the root project

Could not resolve dependency:
peer react-native@"^0.59.5" from react-native-fs@2.16.6
node_modules/react-native-fs
  peer react-native-fs@"^2.12.1" from aws-amplify-react-native@4.2.9
  node_modules/aws-amplify-react-native
    aws-amplify-react-native@"*" from the root project

I have installed the latest expo-cli version 4.0.13 and the latest aws-amplify-cli 4.38.2.
Here the package.json:
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~40.0.0",
    "expo-status-bar": "~1.0.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0"
  },
  "private": true
}

**Comment by amhinson** [comment]
@amin79 What version of the NPM CLI are you running? This appears to be related to the recent [NPM update](https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/) in 7.0.0 to automatically install peer dependencies. I will look into what we can do on our side to fix this, but for the time being, you should be able to use the latest `6.x` release or use `yarn` to get around this.

**Comment by amin79** [comment]
@amhinson Thank you for your answer. Following are what I use:

├── @aws-amplify/cli@4.38.2
├── expo-cli@4.0.13
└── npm@7.1.0

**Comment by amhinson** [comment]
We've got a pending PR for the fix, but for now one of those options I presented should work for you 👍

**Comment by amin79** [comment]
@amhinson Yes. Thank you. With npm 6.14.9 I was able to install the packages. Could you please write here when it is fixed then I can update my npm again. Thank you again

**Comment by amhinson** [comment]
It is fixed now with the `unstable` release, and should be on `latest` within a few days. You can try it out now with:

`npm install --save aws-amplify@unstable aws-amplify-react-native@unstable`

**Comment by amhinson** [comment]
@amin79 We just did a release that contain this fix, so it is available to use now. Let me know if you are still having issues.

**Comment by amin79** [comment]
@amhinson I confirm that the packages are successfully installed with node7.1.2.
Thank you again.
