### ISSUE TITLE
[bug] Why Amazon Cognito Identity Pool ID is required always when Amplify.configure

### ISSUE THREAD

**Issue by ozbillwang** [aws-amplify/amplify-js#740]
### Bug report:

Why I have to provide Amazon Cognito Identity Pool ID when `Amplify.configure`

### What is the current behavior?

```
import Amplify from 'aws-amplify';

Amplify.configure({
    Auth: {
    // REQUIRED - Amazon Cognito Identity Pool ID
        identityPoolId: 'XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab',
    // REQUIRED - Amazon Cognito Region
        region: 'XX-XXXX-X',
    // OPTIONAL - Amazon Cognito User Pool ID
        userPoolId: 'XX-XXXX-X_abcd1234',
    // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
        userPoolWebClientId: 'a1b2c3d4e5f6g7h8i9j0k1l2m3',
    }
});
```

### What is the expected behavior?

I only need cognito user pool, and not going to use cognito Identify pool. 

But if I don't set `identityPoolId`, I can't sign in with below codes.

```
import { Auth } from 'aws-amplify';

Auth.signIn(username, password)
    .then(user => console.log(user))
    .catch(err => console.log(err));
```

**Comment by elorzafe** [comment]
Hi @ozbillwang 
The behavior was by design, so you don't need to ask aws credentials (the library is doing that internally). What is the use case you only will use signIn?

Thanks for your feedback!

**Comment by kgoedecke** [comment]
@elorzafe I'm with @ozbillwang here. Same scenario, I have a user pool but no identity pool is needed. This is bad design imo.

**Comment by s-takehana** [comment]
My `aws-amplify` version is `1.0.5` .
I can use `Auth.signIn` without `identityPoolId` .

```javascript
Amplify.configure({
    Auth: {
        userPoolId: 'ap-northeast-1_xxxxxxxxx',
        userPoolWebClientId: 'xxxxxxxxxxxxxxxxxxxxxxxxxx',
    }
});
```

**Comment by elorzafe** [comment]
@kgoedecke @ozbillwang as @s-takehana commented now, `identityPoolId` is not required. For example when using AWS AppSync and you configure your API secure method as Amazon Cognito User Pools, you just need the jwt token to allow access to that resource.
