### ISSUE TITLE
Cannot read property 'completeNewPasswordChallenge' of undefined

### ISSUE THREAD

**Issue by wcordelo** [aws-amplify/amplify-js#7406]
The intent of my app is to log in to a AWS Cognito User Pool where new users are created by the admin and sent a temporary password.

The user pool was created with the Amplify CLI.

This code is pretty much copied and pasted from the AWS Amplify documentation:

```
import React from "react";
import Amplify from "aws-amplify";
import { AmplifyAuthenticator, AmplifyRequireNewPassword } from "@aws-amplify/ui-react";
import awsconfig from "./aws-exports";
import './App.css';

Amplify.configure(awsconfig);

function App() {
  return (
      <AmplifyAuthenticator>
          <AmplifyRequireNewPassword
              headerText="My Custom Require New Password Text"
              slot="require-new-password"
          ></AmplifyRequireNewPassword>
          Logged In
      </AmplifyAuthenticator>
  );
}

export default App;
```

After creating a new user in the Cognito console, on a test run of the app I successfully signed in and was prompted to change my password. However, when I submitted the new password, I was presented with the following error:

Cannot read property 'completeNewPasswordChallenge' of undefined
The browser was Microsoft Edge 86.0

**Comment by elorzafe** [comment]
@wcordelo 

Have you tested this in other browsers?

**Comment by wcordelo** [comment]
@elorzafe Yes this has been tested in Safari and Google Chrome

**Comment by elorzafe** [comment]
@wcordelo 

I confirm is a bug, looking on the fix now

**Comment by elorzafe** [comment]
I found a couple of problems

- `amplify-require-new-password` component. Should receive `user` data on the props like this

```javascript
     <AmplifyAuthenticator>
        <AmplifyRequireNewPassword
          headerText={headerText}
          slot="require-new-password"
          user={user}
        ></AmplifyRequireNewPassword>
          Logged In
      </AmplifyAuthenticator>
```
That will require a docs change

The other issue is that `this.currentUser` is always `undefined` talking with @wlee221 it seems there is an issue with stencil component.

@wlee221 will continue looking more into this

**Comment by mattschutt** [comment]
Running into this as well.  

```
    "@aws-amplify/ui-react": "^0.2.33",
    "aws-amplify": "^3.3.13",
```

The error banner appears after prompting the 'require new password UI' and submitting the new password:
<img width="1394" alt="Screen Shot 2020-12-22 at 4 33 19 PM" src="https://user-images.githubusercontent.com/2907989/102939218-7e8c8c00-4473-11eb-85f3-56893caa8c76.png">



```
  const renderLoggedIn = () => {
    return (
      <AmplifyAuthenticator onStateChange={handleAuthStateChange}>
        <div slot="greetings">
          <AmplifyGreetings
            username={user.username} 
          />
        </div>
        <div slot="require-new-password">
          <Logo />
          <AmplifyRequireNewPassword
            user={user}
          />
        </div>
        Main Content : TODO
      </AmplifyAuthenticator>
    );
  }

  const renderLoggedOut = () => {
    return (
      <AmplifyAuthenticator onStateChange={handleAuthStateChange}>
        <div slot="sign-in">
          <Logo />
          <AmplifySignIn hideSignUp={true} headerText="Please sign-in to access your secure portal" />
        </div>
        <div slot="forgot-password">
          <Logo />
          <AmplifyForgotPassword
            user={user}
          />
        </div>
        <div slot="require-new-password">
          <Logo />
          <AmplifyRequireNewPassword
            user={user}
          />
        </div>
      </AmplifyAuthenticator>
    );
  }
```

**Comment by mattschutt** [comment]
@wlee221  or could you point me to a version that would work until there's a fix?  Thanks again

**Comment by wlee221** [comment]
Hi! Fix is up on PR #7442. I'll let you know again when this hits `unstable` so that you can install the patch to your app.

**Comment by wlee221** [comment]
@mattschutt, fix is up on the `unstable` npm tag now. Please let us know if the issue persists. Thanks!

```
yarn add aws-amplify@unstable 
```

**Comment by mattschutt** [comment]
@wlee221 — first off, thanks for your hard work and responsiveness on this.  I’ll try it out.  I think it’s also somewhat related to the required fields not being allowed — logged here: https://github.com/aws-amplify/amplify-js/issues/6885#issuecomment-750713337


Second thought— dude it’s Christmas!  Enjoy and put this stuff down for a day!  :) 


Thanks again, you guys rock.

**Comment by josephlevenson** [comment]
Still running into this with aws-amplify: ^3.3.14-unstable.3

**Comment by wilmer-daza** [comment]
> I found a couple of problems
> 
> * `amplify-require-new-password` component. Should receive `user` data on the props like this
> 
> ```js
>      <AmplifyAuthenticator>
>         <AmplifyRequireNewPassword
>           headerText={headerText}
>           slot="require-new-password"
>           user={user}
>         ></AmplifyRequireNewPassword>
>           Logged In
>       </AmplifyAuthenticator>
> ```
> 
> That will require a docs change
> 
> The other issue is that `this.currentUser` is always `undefined` talking with @wlee221 it seems there is an issue with stencil component.
> 
> @wlee221 will continue looking more into this

Hi ! Thank you for the update! I just don't know where the 'user' is instantiated? Do you guys have an example of the 'AmplifyRequireNewPassword' working? I couldn't find one in the documentation ! Thanks

**Comment by allisonhamelin** [comment]
I am having this same issue because of the amplify-require-new-password slotted component despite passing in user. Vue code: 
`<amplify-authenticator username-alias="email">
        <amplify-sign-in username-alias="email" header-text="Sign in" slot="sign-in">
          <a slot="secondary-footer-content" />
        </amplify-sign-in>
        <amplify-require-new-password
          :user="user"
          header-text="Set a permanent password"
          submit-button-text="Set password"
          slot="require-new-password"
        />
      </amplify-authenticator>`

**Comment by wlee221** [comment]
Hi, apologies on the late reply.

1. `user` can be fetched with `onAuthUIStateChange`. See [docs](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react#recommended-usage) for example.
2. For vue, you would need to add `.prop` modifier like so:  `:user.prop="user"`. If this does not work, please open an issue and we'll be glad to help!
