### ISSUE TITLE
Local DataStore not syncing with Cloud

### ISSUE THREAD

**Issue by JohnBenfer** [aws-amplify/amplify-js#7414]
**Describe the bug**
DataStore calls seem to be using local data instead of hitting the cloud db. The DynamoDB has one row that I inserted on 12/14 but has not changed since then so it seems to have been hitting the DynamoDB at first but now is using local db. We checked amplify status which shows the API and AUTH, amplify update api which shows that the DataStore is enabled for the entire API. We checked that the DynamoDB tables had data source versioning enabled and had a delta sync table name. 

**Expected behavior**
I expect the DataStore.save() calls to update the database in DynamoDB and the Amplify Admin console. I expect DataStore.query() to query the DynamoDB. Neither seems to be happening now. 

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.
* Which resources do you have configured?
  * If applicable, please provide your `aws-exports` file:
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "",
    "aws_cognito_identity_pool_id": "us-east-2:",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_",
    "aws_user_pools_web_client_id": "",
    "oauth": {}
};

export default awsmobile;

* If applicable, provide more configuration data, for example for Amazon Cognito, run `aws cognito-idp describe-user-pool --user-pool-id us-west-2_xxxxxx` (Be sure to remove any sensitive data)
 

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```
System:
    OS: macOS 11.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.61 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.3.0 - /usr/local/bin/node
    npm: 6.14.9 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 87.0.4280.88
  npmPackages:
    @babel/core: ~7.9.0 => 7.9.6 
    @expo/vector-icons: ^10.0.0 => 10.2.1 
    @react-native-community/masked-view: ^0.1.10 => 0.1.10 
    @react-native-community/netinfo: ^5.9.9 => 5.9.9 
    @react-navigation/bottom-tabs: ^5.11.1 => 5.11.2 
    @react-navigation/native: ^5.8.10 => 5.8.10 
    @react-navigation/stack: ^5.12.8 => 5.12.8 
    aws-amplify: ^3.3.8 => 3.3.8 
    aws-amplify-react-native: ^4.2.10 => 4.2.10 
    expo: ~40.0.0 => 40.0.0 
    expo-constants: ~9.3.1 => 9.3.4 
    expo-file-system: ~9.3.0 => 9.3.0 
    expo-font: ~8.4.0 => 8.4.0 
    expo-status-bar: ~1.0.3 => 1.0.3 
    ini: ^1.3.5 => 1.3.7 
    inquirer: ^6.5.1 => 6.5.2 
    react: 16.13.1 => 16.13.1 
    react-dom: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
    react-native-elements: 2.3.2 => 2.3.2 
    react-native-gesture-handler: ^1.9.0 => 1.9.0 
    react-native-reanimated: ^1.13.2 => 1.13.2 
    react-native-safe-area-context: ^3.1.9 => 3.1.9 
    react-native-screens: ^2.16.1 => 2.16.1 
    react-native-vector-icons: 7.1.0 => 7.1.0 
    react-native-web: ~0.13.12 => 0.13.18 
  npmGlobalPackages:
    expo-cli: 4.0.13
    npm: 6.14.9
    react-native-cli: 2.0.1
    react-native-fs: 2.16.6
</details>

**Smartphone (please complete the following information):**

- Device: [Galaxy s8]
- OS: [Android 9]
- Browser [expo client]

**Additional context**
We have not edited the backend outside of the Amplify Admin console.

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by nubpro** [comment]
Here's a few things you can do.
1. Listen to DataStore events with Hub (https://docs.amplify.aws/lib/datastore/datastore-events/q/platform/js). If DataStore is successfully starting up, the final emitted event should be `ready`.
2. Do you find any errors from the device's console?

**Comment by iartemiev** [comment]
@JohnBenfer DataStore is a local-first service so when interacting with it via the DataStore API (`DataStore.save()`, `DataStore.query()`, etc. it will always execute these operations against the local store. The contents of the local store are synchronized to the cloud in the background, you can learn more about that process [here](https://docs.amplify.aws/lib/datastore/how-it-works/q/platform/js).

If the data in the local store is out of sync with DynamoDB, something might be misconfigured. Can you share your GraphQL schema? Also, you can enable logs by adding `Amplify.Logger.LOG_LEVEL = 'DEBUG'`. Check to see if there are any subscription errors or warnings in the logs. If so - please share them.

**Comment by myfairshare** [comment]
In my particular case I had everything correct apart from my package dependencies, I had extra amplify core packages hanging around, so I changed package.json to only have 'aws-amplify'.  I then deleted my node modules and package lock and ran npm install, fixed my synching issues.

**Comment by emmafass** [comment]
> In my particular case I had everything correct apart from my package dependencies, I had extra amplify core packages hanging around, so I changed package.json to only have 'aws-amplify'. I then deleted my node modules and package lock and ran npm install, fixed my synching issues.

Been trying to solve this issue for a couple days! Removing unneeded packages did it, Thanks!

**Comment by myfairshare** [comment]
Thats great Emma, it really stumped me big time until I found out through an AWS support engineer, he was able to spot it pretty quickly, such relief when you no longer see the three '_version...' values as undefined!!

**Comment by Frittux** [comment]
I got the following error when starting the app: _TypeError: Cannot read property 'version' of undefined @ 'datastore.js:509'_

I was able to solve this by using **DataStore.query**(...) instead of DataStore.start() on the first startup.
