### ISSUE TITLE
No current user while I am in app (using aws-amplify-react-native) with Auth.currentSession()

### ISSUE THREAD

**Issue by nihp** [aws-amplify/amplify-js#7415]
Frequently facing No current user while I am in app. Here I am using Auth.currentSession() to get the token and successfully inside the app.

Why the above issue is getting. Any thoughts on this?

**Comment by elorzafe** [comment]
@nihp 

Can you give more details.

Which version of the library your using?
Are you experiencing this on simulator/real devices?
Which OS have you tested this behavior, iOS/Android versions?
Do you any specific setting on the userpool?
