### ISSUE TITLE
Subscription not working with Custom GraphQL Endpoint

### ISSUE THREAD

**Issue by mithleshjs** [aws-amplify/amplify-js#7420]
**Describe the bug**
I am using Amplify with custom GraphQL endpoint in my NextJS app. Queries are working fine but when I use subscription, I get this error - "Subscribe only available for AWS AppSync endpoint"

**Code Snippet**
```
const ARTISTS_SUBSCRIPTION = `
        subscription GetArtists {
             artists {
                id
                name
            }
        }
    `;

const subsciption = API.graphql(graphqlOperation(ARTISTS_SUBSCRIPTION)).subscribe({
        next: eventData => console.log(eventData),
   });
```

**Comment by elorzafe** [comment]
@mithleshjs 

Subscription protocol is only supported with [AppSync RealTime](https://docs.aws.amazon.com/appsync/latest/devguide/real-time-websocket-client.html)

Which GraphQL engine are you using?

**Comment by mithleshjs** [comment]
@elorzafe I am using Hasura GraphQL Engine. Would subscription support for custom endpoint be added in the near future?
