### ISSUE TITLE
Amplify services provided through withSSRContext have no type definition

### ISSUE THREAD

**Issue by emilioschepis** [aws-amplify/amplify-js#7426]
**Describe the bug**
When using `withSSRContext` in a Next.js project, the resulting object is of type `AmplifyClass`.

Inside of this object, `Auth`, `API`, `DataStore`, all have a type of `any`.

**To Reproduce**

1. Setup a basic Next.js TypeScript project.
2. Add a `getServerSideProps` method to the default page.
3. See code snippet below.

**Expected behavior**
`Auth` and all the other objects have the same types they have in their "client side" version.

**Code Snippet**
```typescriptreact
export const getServerSideProps: GetServerSideProps = async (context) => {
  const { Auth } = withSSRContext(context);
  // ---- ^ ---- Auth has a type of `any`.

  return {
    props: {},
  };
};
```

**Comment by sammartinez** [comment]
@emilioschepis, for clarity, were you following [this setup guide](https://docs.amplify.aws/start/q/integration/next) we have for Next.js? Please let us know

**Comment by emilioschepis** [comment]
Hi @sammartinez ,

I was not following that setup guide directly, but the same applies to this section: 
https://docs.amplify.aws/start/getting-started/data-model/q/integration/next#api-with-server-side-rendering-ssr

By adding that code to my component, `API` is still typed as `any`.
![image](https://user-images.githubusercontent.com/16031715/102636804-65bf6600-4155-11eb-9688-ab74e0b684a8.png)

**Comment by quinnturner** [comment]
`withSSRContext` returns `AmplifyClass`, which has the type definition:

```ts
export declare class AmplifyClass {
    private _components;
    private _config;
    private _modules;
    Auth: any;
    Analytics: any;
    API: any;
    Credentials: any;
    Storage: any;
    I18n: any;
    Cache: any;
    PubSub: any;
    Interactions: any;
    Pushnotification: any;
    UI: any;
    XR: any;
    Predictions: any;
    DataStore: any;
    Logger: typeof LoggerClass;
    ServiceWorker: any;
    register(comp: any): void;
    configure(config?: any): {};
    addPluggable(pluggable: any): void;
}
```

Looking at the [`Amplify.js` file on the `main` branch](https://github.com/aws-amplify/amplify-js/blob/main/packages/core/src/Amplify.ts):

```ts
export class AmplifyClass {
	// Everything that is `register`ed is tracked here
	private _components = [];
	private _config = {};

	// All modules (with `getModuleName()`) are stored here for dependency injection
	private _modules = {};

	// for backward compatibility to avoid breaking change
	// if someone is using like Amplify.Auth
	Auth = null;
	Analytics = null;
	API = null;
	Credentials = null;
	Storage = null;
	I18n = null;
	Cache = null;
	PubSub = null;
	Interactions = null;
	Pushnotification = null;
	UI = null;
	XR = null;
	Predictions = null;
	DataStore = null;

	Logger = LoggerClass;
	ServiceWorker = null;
...
}
```

This is a fairly useless type definition.

**Comment by quinnturner** [comment]
`withSSRContext(ctx).Auth` should probably be typed as `AuthClass`.

As a current workaround, I am performing this:

```ts
import { withSSRContext } from "aws-amplify";
import { Auth } from '@aws-amplify/auth';

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const auth = withSSRContext(ctx).Auth as typeof Auth;

  let user: any;
  try {
    user = await auth.currentAuthenticatedUser();
    console.log('user is authenticated');
    // fetch some data and assign it to the data variable
  } catch (err) {
    console.log('error: no authenticated user');
  }
};
```

**Comment by emilioschepis** [comment]
That is how I solved the problem as well, it seems like the only option we currently have.
Does this also mean that the fix for this would be as simple as changing the type definition to be `AuthClass` or are there significant differences between the SSR and the client-side versions of the export that need specialized types?

**Comment by harrysolovay** [comment]
For now, that assertion is the right solution. However, I'd recommend using a type-only import.

```diff
import { withSSRContext } from "aws-amplify";
- import { Auth } from '@aws-amplify/auth';
+ import type { Auth } from '@aws-amplify/auth';

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const auth = withSSRContext(ctx).Auth as typeof Auth;

  let user: any;
  try {
    user = await auth.currentAuthenticatedUser();
    console.log('user is authenticated');
    // fetch some data and assign it to the data variable
  } catch (err) {
    console.log('error: no authenticated user');
  }
};
```

**Comment by harrysolovay** [comment]
For good hygiene, might I recommend the following:

```diff
import { withSSRContext } from "aws-amplify";
- import { Auth } from '@aws-amplify/auth';
- import type { APIClass } from '@aws-amplify/auth';

export const getServerSideProps: GetServerSideProps = async (ctx) => {
-  const auth = withSSRContext(ctx).Auth as typeof Auth;
+ const auth = withSSRContext(ctx).Auth as APIClass;

  let user: any;
  try {
    user = await auth.currentAuthenticatedUser();
    console.log('user is authenticated');
    // fetch some data and assign it to the data variable
  } catch (err) {
    console.log('error: no authenticated user');
  }
};
```

**Comment by quinnturner** [comment]
`APIClass` does not exist on `@aws-amplify/auth` `v3.4.0`, which is the most recent version that does not succumb to a bloated bundle: #7313

**Comment by quinnturner** [comment]
I don't think this stale, sorry if it is

**Comment by jimblanc** [comment]
We have published an RFC on our plan for improving TypeScript support in Amplify JS & would love to get your feedback & suggestions!

[RFC: Amplify JS TypeScript Improvements](https://github.com/aws-amplify/amplify-js/issues/11113)

**Comment by cwomack** [comment]
The developer preview for v6 of Amplify has officially been released with improved support for TypeScript and much more! Please check out our [announcement](https://aws.amazon.com/blogs/mobile/aws-amplify-javascripts-new-developer-preview-with-reduced-bundle-sizes-improved-typescript-and-next-js-support/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=238088647) and updated [documentation](https://docs.amplify.aws/lib-v1/project-setup/create-application/q/platform/js/) to see what has changed.

This issue should be resolved within the dev preview and upcoming General Availability for Amplify v6, but let us know with a comment if there are further issues.

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
