### ISSUE TITLE
Missing loader on "Create Account"

### ISSUE THREAD

**Issue by ignaciolarranaga** [aws-amplify/amplify-js#7427]
**Describe the bug**
When you hit create account there is no "loader" (as with Login for example), so the user might attempt to hit the button again or get confused because nothing happens while really the call is already in progress and just taking more time than expected.

Same happens for the verification (in my case through SMS message)

**To Reproduce**

Following any tutorial can be reproduced (e.g. https://docs.amplify.aws/lib/auth/getting-started/q/platform/js#enable-sign-up-sign-in-and-sign-out)
Just use the create account functionality and pay attention when you hit the button.

**Expected behavior**
A loading/loader is displayed.

**Code Snippet**
N/A

**Screenshots**
<img width="529" alt="Missing Loader" src="https://user-images.githubusercontent.com/15932965/102628348-4a8a3180-4128-11eb-8868-0d6d842625cc.png">

**What is Configured?**
N/A

**Smartphone (please complete the following information):**
- Device: Desktop
- OS: MacOS
- Browser Chrome
- Version  87.0.4280.88

package.json:
- "@aws-amplify/ui-react": "^0.2.32",
- "aws-amplify": "^3.3.12",

**Additional context**
N/A

**Comment by sammartinez** [comment]
@ignaciolarranaga Thanks for providing this feedback. Are you looking for the button to be disabled while the request is being made? Just wanted some clarity prior to placing this into our backlog and getting it groomed.

**Comment by ignaciolarranaga** [comment]
I think it has to be disabled yes (just to prevent resubmission I believe), but my mine concern is the user experience.

**Comment by sammartinez** [comment]
Thanks for the feedback here @ignaciolarranaga, we will get this groomed and look where this will fit into the upcoming sprints

**Comment by SijmenHuizenga** [comment]
Hi there!  Today I felt inspired to contribute to this project. This issue seemed like something I could solve so I fixed the bug and created pr #7436. I hope this helps :rocket:

**Comment by wlee221** [comment]
Closing as @SijmenHuizenga's PR has been merged. Thanks!
