### ISSUE TITLE
Picker resently depricated with expo 40..

### ISSUE THREAD

**Issue by Statsministeriet** [aws-amplify/amplify-js#7430]
https://github.com/aws-amplify/amplify-js/blob/be53c6187057728a9e2cf24265324fd1f470e5e0/packages/aws-amplify-react-native/src/AmplifyUI.tsx#L117

**Comment by Statsministeriet** [comment]
Actually I think the picker is just adapted from react-native-community to the react-native version. It's a very low level problem tbh.

**Comment by amhinson** [comment]
This appears to be the same issue as described in this feature request https://github.com/aws-amplify/amplify-js/issues/6845, so I'm. going to close this for now so we can track any progress in the other issue.
