### ISSUE TITLE
Error: The keyPrefix reduxPersist: is already in use. Multiple clients cannot share the same keyPrefix. Provide a different keyPrefix in the offlineConfig object.

### ISSUE THREAD

**Issue by savita-malaghan** [aws-amplify/amplify-js#7434]
When I am upgrading expo from sdk-33 to sdk-40 version of expo. I am getting this issue, I have aws_appsync dependency in my react-native version 59.10.0. 
The problem is occurring  when I create new AWSAppSyncClient, I have set "disableOffline" property to true. Still I am getting this issue.

Is this any issue with upgrade expo or react-native dependencies? 

Please help me to upgrade EXPO SDK-33 to SDK-40.

**Comment by amhinson** [comment]
Are you using Amplify in your project? Or are you using https://github.com/awslabs/aws-mobile-appsync-sdk-js?

**Comment by savita-malaghan** [comment]
These are my dependency using in my application 
    "aws-amplify": "^3.3.13",
    "aws-amplify-react-native": "^4.0.1",
    "aws-appsync": "^4.0.1",
    "aws-appsync-react": "^4.0.1",
    "aws-sdk": "^2.815.0", 


This way i am creating awsappscyncleint 

```
> export const stateLink = createLinkWithCache(cache =>
>   withClientState({
>     //cache,
>     defaults: initialState,
>     resolvers
>   })
> );
> 
> 
> export const linkError = onError(({graphQLErrors, networkError}) => {
>     if (graphQLErrors)
>         graphQLErrors.map(({ message, locations, path }) =>
>             alert(
>                 `[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`
>             )
>         );
> 
>     if (networkError) {
>         alert(`[Network error]: ${networkError}`);
>     }
> })
> 
> const appSyncLink = createAppSyncLink({
>     url: aws_exports.aws_appsync_graphqlEndpoint,
>     disableOffline: true,
>     region: aws_exports.aws_appsync_region,
>     auth: {
>         type: aws_exports.aws_appsync_authenticationType,
>         jwtToken: async () =>
>             (await Auth.currentSession()).getIdToken().getJwtToken(),
>         credentials: () => Auth.currentCredentials()
>     },
>     offlineConfig: {
>         keyPrefix: 'myPrefix'
>     }
> });
> const link = ApolloLink.from([linkError, stateLink, appSyncLink]);
> export const client = new AWSAppSyncClient({}, { link });
```

**Comment by amhinson** [comment]
This appears to be the same issue as https://github.com/aws-amplify/amplify-js/issues/3372. Would you be able to provide a small sample repo that shows the behavior so that we can reproduce it? As mentioned on the other issue, it appears that multiple instances of `AWSAppSyncClient` are being created.

**Comment by mauerbac** [comment]
Haven't heard back from customer. Will close. Please open a new issue if you have future concerns.

**Comment by shakeel0581** [comment]
I have set "disableOffline" property to false, after I changed it, everything works as expected.

**Comment by pranjalkoshti** [comment]
So far what I understood is that this issue occurs when multiple clients are being created with same keyPrefix, lets say in a scenario while creating react app, if multiple rerenders are happening and client is created inside render function of class component, then client will be created multiple times and it will thow this error. Moving creating appsync client outside the react component solved this error for me.
