### ISSUE TITLE
Datastore fails to sync if I restrict access to group

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/amplify-js#7443]
**Describe the bug**
When you set auth to `{allow: groups, groups: ["admin"]}` then entire datastore only works if admin logs in. If non admin logs in then other types that are `{allow:owner}` also don't sync. Everything stops working if non admin logs in. 
`DataStore - Sync error subscription failed Connection failed: {"errors":[{"errorType":"Unauthorized","message":"Not Authorized to access onUpdateNote on type Subscription"}]}`

**Amplify CLI Version**
Amplify v4.16.1

**To Reproduce**
1. `npx create-react-app blog --use-npm --template typescript`
1. `amplify init`
1. `amplify add auth` select email for login and everything else default
1. `amplify update auth` add group admin & again add admin queries
1. `amplify add api` with conflict resolution to optmistic concurrency with following schema
```
type Blog @model
  @auth(rules: [ {allow: owner} ]) {
  id: ID!
  owner: String!
  title: String!
}

type Note @model 
    @auth(rules: [ {allow: groups, groups: ["admin"]} ]) {
    id: ID!
    content: String!
}
```
**EVERYTHING WORKS WHEN ADMIN LOGS IN**

But if non admin logs in then I get following error
`DataStore - Sync error subscription failed Connection failed: {"errors":[{"errorType":"Unauthorized","message":"Not Authorized to access onUpdateNote on type Subscription"}]}`

**Expected behavior**
Datastore should sync even if non admin user logs in. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 from Windows 10 WSL
 - Node Version. 12.16.1

**Additional context**
Other than this issue being huge dealbreaker for me. I wanted to talk about what is working.
```
type Note @model 
    @auth(rules: [ 
        {allow: owner},
        {allow: groups, groups: ["admin"]} 
    ]) {
    id: ID!
    owner: String!
    content: String!
}
```
In combination with allow owner it works fine. But I don't want to add owner. I want to only restrict to the admin group.
```
type Note @model 
    @auth(rules: [ 
        {allow: private}
    ]) {
    id: ID!
    content: String!
}
```
If I change to allow private then also it works fine. And when you fix this issue its easily upgradable to `{allow: groups, groups: ["admin"]}` without encountering error `only one resolver allowed per field`. Drawback is there are 100's of non admin users that will download data that they will never see on their UI. 10,000's of wasted requests and payload data costs that I am paying until you fix this issue for me. And its not just single `Note` type that is exlusive for admin. The admin has more data `type` exlusive for them than regular users.  So its much worse than you think.

**Comment by iartemiev** [comment]
We released multiple authorization type support for DataStore in aws-amplify@3.4.0. 

Please see this section of the docs on how to configure it: https://docs.amplify.aws/lib/datastore/setup-auth-rules/q/platform/js#configure-multiple-authorization-types
