### ISSUE TITLE
amplify-authenticator template doesn't do anything

### ISSUE THREAD

**Issue by 9037568** [aws-amplify/amplify-js#7458]
**Describe the bug**
Working through the documentation [example for configuring auth](https://docs.amplify.aws/lib/auth/getting-started/q/platform/js#option-1-use-pre-built-ui-components) in angular.

Using the amplify-authenticator template there without modification is rendering an empty block:

````
<template _ngcontent-lgp-c65=""></template>
````

**What is Configured?**
  * `aws-exports` file:
   ```
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:...",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_...",
    "aws_user_pools_web_client_id": "2be388au6e155cshdq2ust1o6t",
    "oauth": {}
};
   ```

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages

  System:
    OS: Windows 10 10.0.17134
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
    Memory: 3.12 GB / 7.95 GB
  Binaries:
    Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 87.0.4280.88
    Edge: Spartan (42.17134.1.0)
    Internet Explorer: 11.0.17134.1
  npmGlobalPackages:
    @angular/cli: 11.0.5

```

</details>

**Comment by amhinson** [comment]
@9037568 Could you provide a larger code sample of your Amplify usage in your app?

**Comment by 9037568** [comment]
>@9037568 Could you provide a larger code sample of your Amplify usage in your app?

@amhinson Sure. What do you need to see?

**Comment by amhinson** [comment]
It'd be helpful to see these files:
- `app.component.ts`
- `app.component.html`
- `app.module.ts`

**Comment by 9037568** [comment]
app.component.ts

````javascript
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'polymma';
}
````

app.component.html

````javascript
<template>
  <amplify-authenticator>
    <div>
      My App
      <amplify-sign-out></amplify-sign-out>
    </div>
  </amplify-authenticator>
</template>
````

app.module.ts

````javascript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';
import { AppRoutingModule } from './app-routing.module';

import { AmplifyUIAngularModule } from '@aws-amplify/ui-angular';
import Amplify, {API, graphqlOperation} from 'aws-amplify';
import awsconfig from '../aws-exports';
import { ModelsComponent } from './ltc/models/models.component';
import { LandingComponent } from './landing/landing.component';
import { SessionsComponent } from './ltc/sessions/sessions.component';

/* Configure Amplify resources */
Amplify.configure(awsconfig);

@NgModule({
  declarations: [
    AppComponent,
    ModelsComponent,
    LandingComponent,
    SessionsComponent,
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    AmplifyUIAngularModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
````

**Comment by amhinson** [comment]
It looks like the setup instructions are slightly different in the link you provided as opposed to [this one](https://docs.amplify.aws/ui/auth/authenticator/q/framework/angular#recommended-usage) from the UI Components page. Could you try this approach and see what might be off? We might need to update the other docs.

**Comment by 9037568** [comment]
Interesting.  In the section labelled "Recommended Usage", there are two completely different sets of content shown for the `app.component.html` file. And no explanation for why...

Here's the first one:

````javascript
<amplify-authenticator *ngIf="authState !== 'signedin'"></amplify-authenticator>

<div *ngIf="authState === 'signedin' && user" class="App">
    <amplify-sign-out></amplify-sign-out>
    <div>Hello, {{user.username}}</div>
    <!-- This is where you application template code goes -->  
</div>
````

And here's the second one, which mostly matches the content from the guide I was following before:

````javascript
<amplify-authenticator>
  <div>
    My App
    <amplify-sign-out></amplify-sign-out>
  </div>
</amplify-authenticator>
````

Is there any expected functional difference between these two? They both seem to work now that I've deployed the suggested content of `app.component.ts`.

**Comment by amhinson** [comment]
Yes, that is confusing! I think the two examples are just showing that you can either manage how your app behaves regarding the auth state with `onAuthUIStateChange`, or you can just wrap your protected app content inside `amplify-authenticator`. I will work on updating the documentation to be clearer about these examples. Thanks for bringing it to our attention! 👍

**Comment by stefanomiccoli** [comment]
the issue is marked as closed, however the documentation is still confusing and i landed on this issue only by accident googling around to undesrtand why my angular app apparently does not manage properly the change detection (unhandled clicks etc) when put inside the amplify-authenticator component.

Would it be possible to have the documentation to be updated to avoid waste of time for the next poor guy?

**Comment by amhinson** [comment]
@stefanomiccoli Good thought. Could you create an issue on the [docs repo](https://github.com/aws-amplify/docs)? That will allow more focused attention specifically on the examples in the docs.
