### ISSUE TITLE
AppSync : Issue syncing DataStore with iOS devices when app is installed for the first time

### ISSUE THREAD

**Issue by hmisonne** [aws-amplify/amplify-js#7459]
**Describe the bug**

Before rendering the app, I am using a **syncDataStore** function to make sure the DataStore is synced:

```javascript
export function syncDataStore() {
  const [isSyncComplete, setSyncComplete] = React.useState(false);

  React.useEffect(() => {
    async function loadResourcesAndDataAsync() {
      try {
        await DataStore.start();
      } catch (e) {
        console.warn(e);
      } finally {
        const removeListener = Hub.listen("datastore", async (data) => {
          const { payload } = data;
          if (payload.event === "ready") {
            console.log('READY', payload)
            const users = await DataStore.query(User)
            console.log('users after sync', users)
            setSyncComplete(true)
            removeListener();
          }
        });        
      }
    }
    loadResourcesAndDataAsync();
  }, []);
  return isSyncComplete
}

```

This works well on Android device but it fails on iOS as no data is received.
![image](https://user-images.githubusercontent.com/52170580/103317123-6bcc0700-49df-11eb-8beb-3b2b9d0ac8de.png)

This is problematic because if no previous User instance is found on the datastore, a new one will be created. Meaning that every time a User installs the app on another iOS device a duplicate instance will be created

**To Reproduce**

1. Create a User Model with a `@auth` rule
```graphql
type User @model 
@auth(rules: [{ allow: owner }])
{
  id: ID!
  sub: String!
  username: String
  groceryLists: [String]
}
```
2. Create a React App that waits for Data synchronization before rendering.
```javascript
const App = () => {
  const isDataStoreReady = syncDataStore()

  if ( !isDataStoreReady) {
    return (
      <AppLoading
    />
    )
  }
  return (
    //... App Content
  );
};
export default withAuthenticator(App);

```
3. Add a user to the database by signing in to the app
4. Use an iOS device and connect to the app with the user created (make sure no data has been saved on the datastore of this iOS device before)
5. After reloading the app on the iOS, the User info will correctly appear. The issue only occurs when the app is synchronized with the datastore for the first time

**Expected behavior**
Upon loading the app for the first time, a User should be receiving his own User information (this is working properly on Android)
![image](https://user-images.githubusercontent.com/52170580/103317303-e1d06e00-49df-11eb-82a5-b00e2fe70848.png)

From what I could see from the logs, on Android the `AWSAppSyncRealTimeProvider` calls are initiated before rendering the app (before DataStore is set to ready) whereas this call is performed afterwards on iOS.
```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages

System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 2.48 GB / 15.78 GB
  Binaries:
    Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.10 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Chrome: 86.0.4240.198
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    @babel/core: ~7.9.0 => 7.9.6
    @iconify/icons-mdi: ^1.0.142 => 1.1.0
    @iconify/react: ^1.1.3 => 1.1.3
    @react-native-community/masked-view: 0.1.10 => 0.1.10
    @react-native-community/netinfo: 5.9.6 => 5.9.6
    @react-native-community/picker: 1.6.6 => 1.6.6
    @react-native-picker/picker: ^1.9.3 => 1.9.3
    @react-navigation/bottom-tabs: ^5.9.1 => 5.11.2
    @react-navigation/native: ^5.7.5 => 5.8.10
    @react-navigation/stack: ^5.9.2 => 5.12.8
    @testing-library/jest-native: ^3.4.3 => 3.4.3
    @testing-library/react-native: ^7.1.0 => 7.1.0
    aws-amplify: ^3.3.8 => 3.3.10
    aws-amplify-react-native: ^4.2.8 => 4.2.9
    babel-polyfill: ^6.26.0 => 6.26.0
    expo: ^39.0.3 => 39.0.5
    expo-app-loading: ^1.0.1 => 1.0.1
    expo-font: ^8.3.0 => 8.3.0
    expo-mail-composer: ^8.4.0 => 8.4.0
    expo-splash-screen: ^0.6.2 => 0.6.2
    expo-status-bar: ~1.0.2 => 1.0.2
    ini: ^1.3.5 => 1.3.5
    inquirer: ^6.5.1 => 6.5.2
    jest: ^26.4.2 => 26.6.3
    react: 16.13.1 => 16.13.1
    react-dom: 16.13.1 => 16.13.1
    react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
    react-native-gesture-handler: ~1.7.0 => 1.7.0
    react-native-paper: ^4.5.0 => 4.5.0
    react-native-reanimated: ~1.13.0 => 1.13.2
    react-native-safe-area-context: 3.1.4 => 3.1.4
    react-native-screens: ~2.10.1 => 2.10.1
    react-native-swipe-list-view: ^3.2.5 => 3.2.5
    react-native-vector-icons: ^7.1.0 => 7.1.0
    react-native-web: ~0.13.12 => 0.13.18
    react-redux: ^7.2.1 => 7.2.2
    react-redux-loading-bar: ^5.0.0 => 5.0.0
    react-router-dom: ^5.2.0 => 5.2.0
    react-test-renderer: ^16.13.1 => 16.14.0
    redux: ^4.0.5 => 4.0.5
    redux-thunk: ^2.3.0 => 2.3.0
    redux-undo: ^1.0.1 => 1.0.1
  npmGlobalPackages:
    @aws-amplify/cli: 4.40.0
    @ionic/cli: 6.7.0
    bower: 1.8.8
    create-react-native-app: 3.1.0
    exp: 57.2.1
    expo-cli: 4.0.1
    express-generator: 4.16.1
    gulp: 4.0.2
    npm: 6.14.10
    react-native-cli: 2.0.1
    sequelize-cli: 6.1.0
    serverless: 1.71.3
    sharp-cli: 1.14.1
    wscat: 4.0.0
```

</details>

**Smartphone (please complete the following information):**

- Device: all iPhone
- OS: all OS

**Comment by iartemiev** [comment]
Hey @hmisonne, there was an issue in DataStore on React Native where the `ready` event was getting fired prematurely. It was fixed in [this PR](https://github.com/aws-amplify/amplify-js/pull/7407) which was released as part of aws-amplify@3.3.13. Could you please update to the latest version and see if that solves the issue for you?

**Comment by hmisonne** [comment]
Hi @iartemiev ! 

Thank you for getting back to me so quickly!
Upgrading `aws-amplify` package solved my issue. 

However, I can no longer build a new version of my app. When I run `expo build:ios`, I am having this error message:

![image](https://user-images.githubusercontent.com/52170580/103384262-98008a00-4aaa-11eb-8a83-e04064263772.png)

**Comment by iartemiev** [comment]
@hmisonne interesting 🤔. Are you able to start/run the app in Simulator? Have you tried clearing the Metro bundler cache with `expo start --clear`?

**Comment by hmisonne** [comment]
@iartemiev that did the trick ! 

I also had to run `rm -rf node_modules/ && rm -f package-lock.json && rm -f yarn.lock && npm cache verify && npm install && expo r -c` https://github.com/expo/expo/issues/6489#issuecomment-564708368 since I was having an error with expo-font not loading

Thanks again so much for your help!

**Comment by iartemiev** [comment]
@hmisonne - awesome! I'll go ahead and close this issue
