### ISSUE TITLE
Feature request: Add ability to manually trigger a refetch of a query in the React Connect component

### ISSUE THREAD

**Issue by gabehollombe** [aws-amplify/amplify-js#746]
In a React app I'm working on, I'm uploading files to S3 and then sending mutations to persist the S3 urls of the newly uploaded files. The component that hosts this uploading functionality is an index view of these files, showing metadata about the uploaded files pulled from a query. After new files are uploaded and their metadata is persisted to my backend via mutations, I'd like to force a refetch of my component that shows the items index, but it doesn't look like Amplify's `Connect` component allows this behavior.  

The best I can do right now is include a changing variable like a timestamp in my query variables so that if I call `forceUpdate` on the component hosting the `Connect` component, the `Connect` component will do it's normal lifecycle methods and decide the query has changed because one of the variable inputs has changed, so it will refetch.

Does it maybe make sense for the `Connect` component to pass down a handle to its refetching function so code can trigger a refetch without changing query params?

**Comment by elorzafe** [comment]
Hi @gabehollombe, thanks for your feedback. We will discuss this internally and will let you know.

**Comment by khola** [comment]
Hi, any progress with this? I can create PR for this feature, as I already did such change in our internal fork of this component, but don't know if it aligns with your idea of this component. Of course, in an ideal world, it should be done using subscription, but it's not always possible ;)

**Comment by harrysolovay** [comment]
This is a legacy component. Unfortunately, a manual `forceUpdate` call is the best solution, aside from utilizing [the new generation of components](https://docs.amplify.aws/ui/storage/s3-album/q/framework/react).

Also––incase you're open to creating a PR––we'd love to review your suggested changes!
