### ISSUE TITLE
No events recorded in Xcode release mode

### ISSUE THREAD

**Issue by OrangeChickens** [aws-amplify/amplify-js#7461]
**Describe the bug**
Hi there are two issues I am facing while integrating amplify analytics with my react native app.(react-native-cli)
1) Issue 1: App crash if i import library direct from 'aws-amplify" in xcode release mode.
- Steps:
In my index.js or app.js file, paste 
```
import Amplify from 'aws-amplify'
import config from './aws-exports'
Amplify.configure(config)
```
 App will crash on start in release mode with error 
```
2020-12-27 17:07:01.836 [error][tid:com.facebook.react.JavaScript] Can't find variable: self
2020-12-27 17:07:01.857180+0800 PandaBrick[82671:13882526] Can't find variable: self
2020-12-27 17:07:01.862 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Can't find variable: self..
```
2)Issue 2: Using modular imports fixed the error, but no events recorded in pinpoint in release mode as well.
- Steps:
In my app.js or index.js, paste 
```
 import Amplify from '@aws-amplify/core';
import awsmobile from './aws-exports';
Amplify.Logger.LOG_LEVEL = 'DEBUG';
Amplify.configure(awsmobile);
```
For both issues, if I build my app in xcode debug mode, all works fine and I could see events in pinpoint being recorded.

**Expected behavior**
I should see events recorded in xcode release mode and there should be no error if I import from 'aws-amplify'.

** config ** 
My configs:
Package.json
    "aws-amplify": "^3.3.13",
    "aws-amplify-react-native": "latest"
    "react": "16.8.3",
    "react-native": "0.59.9",

aws-exports.js
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "xxx",
    "aws_cognito_region": "us-west-2",
    "oauth": {},
    "aws_mobile_analytics_app_id": "xxx",
    "aws_mobile_analytics_app_region": "us-west-2"
};

export default awsmobile;

**Comment by mtoninelli** [comment]
I have the same issue here running React Native 0.59.9
In my case I've added only `notification`.
The error happens on the import:
`import Amplify from 'aws-amplify';`

**Comment by mauerbac** [comment]
Hey @amhinson - can you have Kaleb look at this asap?

**Comment by chrisbonifacio** [comment]
Hi :wave: Sorry this was auto-closed by stale bot. We are working towards preventing this from happening in the future. Please let us know if you are still experiencing this issue and in need of assistance.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!
