### ISSUE TITLE
Make the init parameter of get requests optional.

### ISSUE THREAD

**Issue by fireflysemantics** [aws-amplify/amplify-js#7469]
The `API.get` third parameter used to not exist.  Now we have to provide something.  For example this works:

```
    const result = API.get('testapi', '/items', {})
```

It would be nice if it was optional.  

```
class API {

   static get(apiName: string, path:string, init?: any) 

}
```

Also an [API description](https://aws-amplify.github.io/amplify-js/api/classes/apiclass.html#get) of what the `init`  parameter is for would be nice

**Comment by nadetastic** [comment]
Related to https://github.com/aws-amplify/amplify-js/issues/9429
