### ISSUE TITLE
Angular - authState looks to not update after completeNewPassword is being triggered

### ISSUE THREAD

**Issue by 39ro** [aws-amplify/amplify-js#747]
Hello guys, I was trying to re-write the Angular components for AWS-amplify and I encountered a few problems with the **completeNewPassword** method.

Here the component provided by you: [require-new-password.component.ts](https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify-angular/src/components/authenticator/require-new-password.component.ts)

1. I am trying to login an user with "UserStatus": "FORCE_CHANGE_PASSWORD" (ex. after creating an User using the API admin-create-user ), 
2. My completeChallengeNewPassword CanActivate is triggered, check  ` if (this._auth.currentUser.challengeName === 'NEW_PASSWORD_REQUIRED')`, true redirect to "/new-password" to let him update his new password.
3. After I submit my new password, the completeChallengeNewPassword is being triggered but the AuthState doesn't looks to update his challengeName field and my CanActivate still match the condition
` if (this._auth.currentUser.challengeName === 'NEW_PASSWORD_REQUIRED')` as true, avoiding me to redirect the user to protected pages.

*Now **trying to refresh the page manually the AuthState is being updated** and I **can now redirect the user to protected pages**.*

- [Authentication Service](https://www.typescriptlang.org/play/index.html#src=import%20%7BInjectable%7D%20from%20'%40angular%2Fcore'%3B%0D%0Aimport%20%7BAmplifyService%2C%20AuthState%7D%20from%20'aws-amplify-angular'%3B%0D%0Aimport%20%7BBehaviorSubject%7D%20from%20'rxjs%2FBehaviorSubject'%3B%0D%0A%0D%0A%0D%0Ainterface%20LoginModel%20%7B%0D%0A%20%20username%3A%20string%3B%0D%0A%20%20password%3A%20string%3B%0D%0A%7D%0D%0A%0D%0A%40Injectable()%0D%0Aexport%20class%20AuthService%20%7B%0D%0A%20%20public%20authState%3A%20BehaviorSubject%3Cany%3E%20%3D%20new%20BehaviorSubject(null)%3B%0D%0A%0D%0A%20%20constructor(private%20_amplify%3A%20AmplifyService)%20%7B%0D%0A%20%20%20%20this._amplify.authStateChange%24.subscribe(authState%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20console.log('authStateChange')%3B%0D%0A%20%20%20%20%20%20(!authState.user)%20%3F%20this.authState.next(null)%20%3A%20this.authState.next(authState.user)%3B%0D%0A%20%20%20%20%7D)%0D%0A%20%20%7D%0D%0A%0D%0A%20%20get%20authenticated()%20%7B%0D%0A%20%20%20%20return%20this.authState.getValue()%20!%3D%3D%20null%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20get%20currentUser()%3A%20any%20%7B%0D%0A%20%20%20%20return%20(this.authenticated)%20%3F%20this.authState.getValue()%20%3A%20null%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20public%20login(user%3A%20LoginModel)%20%7B%0D%0A%20%20%20%20return%20this._amplify.auth().signIn(user.username%2C%20user.password)%0D%0A%20%20%20%20%20%20.then(user%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log('User%20Logged%20In!')%3B%0D%0A%20%20%20%20%20%20%20%20this._amplify.setAuthState(%7Bstate%3A%20'confirmSignIn'%2C%20user%3A%20user%7D)%3B%0D%0A%20%20%20%20%20%20%7D)%0D%0A%20%20%7D%0D%0A%0D%0A%20%20public%20logout()%20%7B%0D%0A%20%20%20%20this._amplify.auth().signOut()%0D%0A%20%20%20%20%20%20.then(()%20%3D%3E%20console.log('User%20Logged%20Out!'))%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20completeNewPassword(password%3A%20string)%20%7B%0D%0A%20%20%20%20return%20this._amplify.auth()%0D%0A%20%20%20%20%20%20.completeNewPassword(%0D%0A%20%20%20%20%20%20%20%20this.currentUser%2C%0D%0A%20%20%20%20%20%20%20%20password%2C%0D%0A%20%20%20%20%20%20%20%20this.currentUser.challangeParam%0D%0A%20%20%20%20%20%20)%0D%0A%20%20%20%20%20%20.then(()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log('complete%20new%20Password!')%3B%0D%0A%20%20%20%20%20%20%20%20console.log(this.currentUser)%3B%0D%0A%20%20%20%20%20%20%20%20this._amplify.setAuthState(%7Bstate%3A%20'signIn'%2C%20user%3A%20this.currentUser%7D)%3B%0D%0A%20%20%20%20%20%20%7D)%0D%0A%20%20%7D%0D%0A%7D%0D%0A)
- [New Password Component](https://www.typescriptlang.org/play/index.html#src=import%20%7BComponent%2C%20OnInit%7D%20from%20'%40angular%2Fcore'%3B%0D%0Aimport%20%7BAuthService%7D%20from%20'%40app%2Fcore%2Fauth%2Fauth.service'%3B%0D%0Aimport%20%7BRouter%7D%20from%20'%40angular%2Frouter'%3B%0D%0A%0D%0A%40Component(%7B%0D%0A%20%20selector%3A%20'app-new-password'%2C%0D%0A%20%20template%3A%20%60%0D%0A%20%20%20%20%3Ch1%3ENew%20Password%20is%20required%3C%2Fh1%3E%0D%0A%20%20%20%20%3Chr%3E%0D%0A%20%20%20%20%7B%7BerrorMessage%7D%7D%0D%0A%20%20%20%20%3Cform%20%23newPasswordForm%3D%22ngForm%22%0D%0A%20%20%20%20%20%20%20%20%20%20(submit)%3D%22completeChallengeNewPassword(newPasswordForm.value)%22%3E%0D%0A%20%20%20%20%20%20%3Cinput%20%5B(ngModel)%5D%3D%22newPassword%22%20%23password%20name%3D%22newPassword%22%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20type%3D%22password%22%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20placeholder%3D%22Password%22%2F%3E%0D%0A%0D%0A%20%20%20%20%20%20%3Cbutton%20class%3D%22amplify-form-button%22%20type%3D%22submit%22%3ESet%20new%20password%3C%2Fbutton%3E%0D%0A%20%20%20%20%3C%2Fform%3E%0D%0A%20%20%60%2C%0D%0A%20%20styleUrls%3A%20%5B'.%2Fnew-password.component.scss'%5D%0D%0A%7D)%0D%0Aexport%20class%20NewPasswordComponent%20implements%20OnInit%20%7B%0D%0A%20%20public%20newPassword%3B%0D%0A%20%20public%20errorMessage%3A%20string%3B%0D%0A%0D%0A%20%20constructor(private%20_auth%3A%20AuthService%2C%20private%20route%3A%20Router)%20%7B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20ngOnInit()%20%7B%0D%0A%20%20%20%20console.log('%23%23%23%23%23%23%23%23')%3B%0D%0A%20%20%20%20console.log(this._auth.currentUser)%3B%0D%0A%20%20%20%20this.newPassword%20%3D%20''%3B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20completeChallengeNewPassword(password)%20%7B%0D%0A%20%20%20%20this._auth.completeNewPassword(password.newPassword)%0D%0A%20%20%20%20%20%20.then(()%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log('navigate%20to%20admin')%3B%0D%0A%20%20%20%20%20%20%20%20this.route.navigate(%5B'%2Fadmin'%5D)%0D%0A%20%20%20%20%20%20%7D)%0D%0A%20%20%20%20%20%20.catch(err%20%3D%3E%20this.errorMessage%20%3D%20err.message)%0D%0A%20%20%7D%0D%0A%7D%0D%0A)
- [ChallengeNewPasswordRequired - CanActivate](https://www.typescriptlang.org/play/index.html#src=import%20%7BActivatedRouteSnapshot%2C%20CanActivate%2C%20Router%2C%20RouterStateSnapshot%7D%20from%20'%40angular%2Frouter'%3B%0D%0Aimport%20%7BObservable%7D%20from%20'rxjs%2FObservable'%3B%0D%0Aimport%20%7BInjectable%7D%20from%20'%40angular%2Fcore'%3B%0D%0Aimport%20%7BAuthService%7D%20from%20'%40app%2Fcore%2Fauth%2Fauth.service'%3B%0D%0Aimport%20'rxjs%2Fadd%2Foperator%2Fmap'%0D%0A%0D%0A%40Injectable()%0D%0Aexport%20class%20ChallengeNewPasswordRequired%20implements%20CanActivate%20%7B%0D%0A%20%20constructor(private%20_auth%3A%20AuthService%2C%20private%20route%3A%20Router)%20%7B%0D%0A%20%20%7D%0D%0A%0D%0A%20%20canActivate(route%3A%20ActivatedRouteSnapshot%2C%20state%3A%20RouterStateSnapshot)%3A%20Observable%3Cboolean%3E%20%7C%20Promise%3Cboolean%3E%20%7C%20boolean%20%7B%0D%0A%20%20%20%20if%20(this._auth.authenticated)%20%7B%0D%0A%20%20%20%20%20%20if%20(this._auth.currentUser.challengeName%20%3D%3D%3D%20'NEW_PASSWORD_REQUIRED')%20%7B%0D%0A%20%20%20%20%20%20%20%20this.route.navigate(%5B'%2Fnew-password'%5D)%3B%0D%0A%20%20%20%20%20%20%20%20console.log('user.challengeName%20TRUE%20%23%23%23%23%23%23%23')%3B%0D%0A%20%20%20%20%20%20%20%20return%20false%3B%0D%0A%20%20%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log('user.challengeName%20FALSE%20%23%23%23%23%23%23%23')%3B%0D%0A%20%20%20%20%20%20%20%20return%20true%0D%0A%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20this.route.navigate(%5B'%2Flogin'%5D)%3B%0D%0A%20%20%20%20%20%20return%20false%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%0D%0A%7D%0D%0A): the ChallengeNewPasswordRequired is a guardian. CanActivate, to help me protect specific routes.

It's a couple of hours that I am struggling on it and would be happy if one of you could help me to sort out where the problem is. Thanks!

**Comment by 39ro** [comment]
Ok, I was able to solve by signing in again the user, after the **completeNewPassword** has been triggered.
```
  completeChallengeNewPassword(password) {
    this._auth.completeNewPassword(password.newPassword)
      .then(user => {
        this._auth.login({username: user.username, password: this.newPassword}).then(() => {
          this.route.navigate(['/admin'])
        });
      })
      .catch(err => this.errorMessage = err.message)
  }
```

The previous behaviour doesn't sound really good, at least I am not able to understand why the _authStateChange$_ is not being update!
After I set a new passowrd (**completeChallengeNewPassword: Promise**) the response still result as `challengeName: 'NEW_PASSWORD_REQUIRED'.`
Refreshing the page the user result loggedin and no challengeName are present.

**Comment by jan1za** [comment]
I think the reason is is not working is there is no decorator (auth.decorator.ts) for completeNewPassword. Temp workaround is to call the following when the  Auth.completeNewPassword comes back successful .    
amplifyService.setAuthState({ state: 'signedIn', user: userReturned });  

Where userReturned is the user I got back from  Auth.completeNewPassword.     

The decorators (auth.decorator.ts) are not complete, so if you for example: 
I delete the user in cognito while still logged in on the frontend, and you refresh the angular page. The authstate remains signedIn. Even if  Auth.currentUserInfo() returns {}.  The reason is function check(authState: Subject<AuthState>) in auth.decorator.ts returns a user, on check but does not validate that it has data? So it makes it signed in even though it is not and the service call to Cognito threw a 400.

Something else,  amplify.service.ts has private _authState = new Subject<AuthState>();
If my code signs up late for the authState, I dont get a value, unless I do something. It should be BehaviorSubject and not Subject.

If what I am saying is crap, please let me know. I am trying to learn TypeScript only been busy with it for 2 days, else I would have updated the code and submitted. I don't want to be that idiot :) 

Thank you again for an awesome package. Much nicer than building cognito intergation it in JavaScript.

**Comment by elorzafe** [comment]
@39ro @jan1za, @haverchuck is looking into this issue.

**Comment by haverchuck** [comment]
@39ro @jan1za - Yes, I think this is a decorator issue.  Continuing to look into it.
