### ISSUE TITLE
Ability to check if access token has expired without renewing the access token

### ISSUE THREAD

**Issue by motzko** [aws-amplify/amplify-js#7480]
Request: an SDK method to check if access token has expired without renewing the access token.

- `Auth.currentSession()`
- `Auth.currentAuthenticatedUser()`

^ both of these methods expose an `isValid` function to check if access token is valid, but both call `getSession` which renews the access token.

The [documentation](https://docs.amplify.aws/lib/auth/manageusers/q/platform/js#retrieve-current-session) indicates this is expected for `currentSession`, but [doesn't](https://docs.amplify.aws/lib/auth/manageusers/q/platform/js#retrieve-current-authenticated-user) for `currentAuthenticatedUser`. It's unclear if this is expected behavior or not. Regardless, it would be great to have an SDK method to check if the session is still valid without renewing the token. ~~Right now it seems like the only option is to read from cookies directly and manually calculate expiration.~~

**Comment by elorzafe** [comment]
@motzko 

What use case you are trying to solve by only checking if the token is expired without having the library to renew the token?

**Comment by martinmicunda** [comment]
@elorzafe one example would be when I would like to use analytics to track when user login to the system. I already have analytics when user login to application, however, when user check a checkbox `Keep me logged in` and visit application next day the way how this work is through refresh/expire token and there is no way how I can hook up analytics to track user.

**Comment by martinmicunda** [comment]
@elorzafe ah thanks.. Hub was exactly what I needed ...

**Comment by AllanZhengYP** [comment]
@martinmicunda Glad to see `Hub` is what you need. I will close this issue. Please feel free to open a new issue if you have further questions.
