### ISSUE TITLE
Server-Side Request Forgery high severity vulnerability in axios < v0.21.1

### ISSUE THREAD

**Issue by stage88** [aws-amplify/amplify-js#7490]
**Describe the bug**
A high severity vulnerability has been reported via npm for axios in versions prior to 0.21.1, see https://npmjs.com/advisories/1594. This breaks pipelines for those that include "npm audit" as a step in their pipeline execution.

**To Reproduce**

1. npm init
2. npm install aws-amplify
3. npm audit
4. see npm audit security report

**Expected behavior**
No high  high severity vulnerabilities

**Additional context**
Also see https://github.com/aws-amplify/amplify-js/commit/5314076b68bf3f2c8a5e7e958b98945c3ef9054e and https://github.com/aws-amplify/amplify-js/pull/5487 and https://github.com/aws-amplify/amplify-js/issues/5432.

> If the POST request body is empty but content-type header is set, axios is forcibly removing it. See axios/axios#1535 and axios refusing to fix it axios/axios#755. This change is a workaround to set the data as null (instead of undefined) to prevent axios from removing the content-type header. Link for the source code
> 
> Because of this workaround, forcing the axios version to avoid newer axios versions breaking this.

Looks like axios is pinned to v0.19.0 in `packages/storage/package.json` and `packages/api-rest/package.json`.

**Comment by wlee221** [comment]
Hi @stage88, this has been fixed in #7489 and now is merged. Thanks for giving out the context too! Will keep an eye on it.

**Comment by stage88** [comment]
@wlee221 Thanks for addressing this, much appreciated!
