### ISSUE TITLE
Transcribe audio to text always returns empty string

### ISSUE THREAD

**Issue by SebSchwartz** [aws-amplify/amplify-js#7494]
**Describe the bug**
Hello,
I'm currently trying to use the "transcribe audio to text" feature from [amplify](https://docs.amplify.aws/lib/predictions/transcribe/q/platform/js) in the web version. 
The problem is that, no matter which file I'm sending in my requests, the answer is always an empty string.
I'm working with .mp3 files. I've tried sending their Blob, ArrayBuffer, Base64 but without any success.
I can't seem to find a working example on the internet, which is why I was wondering if anyone had a reproducible scenario where the server actually answers with the transcribed text from the file.
Any example with a real audio file in the source object of the request would do.

Thanks in advance!

**Expected behavior**
Receiving the right response or an error, not an empty string response.

**Code Snippet**
This is how we are calling the prediction category:
```javascript
const fileBlob = await audioFile.file.arrayBuffer()
const speechToTextOutput = await Predictions.convert({
                      transcription: {
                        source: {
                          bytes: fileBlob,
                        },
                        language: 'en-US',
                      },
                    });
```
To record the audioFile, we are using [mic-recorder-to-mp3](https://www.npmjs.com/package/mic-recorder-to-mp3) library

**What is Configured?**
I'm using the latest version of **@aws-amplify/predictions**
* Which resources do you have configured?
  * If applicable, please provide your `aws-exports` file:
   ```json
   const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:xxxx",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_xxxxxx",
    "aws_user_pools_web_client_id": "xxxxx",
    "oauth": {
        "domain": "xxxxx-dev.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://app.xxxxx.com/,https://dev.xxxxx.com/,https://test.xxxxx.com/,http://localhost:3000/,exp://127.0.0.1:19000/--/,xxxx://",
        "redirectSignOut": "https://app.xxxxx.com/,https://dev.xxxxx.com/,https://test.xxxxxx.com/,http://localhost:3000/,exp://127.0.0.1:19000/--/,xxx://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_content_delivery_bucket": "xxxxxx-xxxx-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "https://xxxxx.cloudfront.net",
    "aws_user_files_s3_bucket": "xxxxx-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://xxxxxxx.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "xxxx",
            "endpoint": "https://xxxxx.execute-api.eu-west-1.amazonaws.com/dev",
            "region": "eu-west-1"
        }
    ],
    "predictions": {
        "convert": {
            "transcription": {
                "region": "eu-west-1",
                "proxy": false,
                "defaults": {
                    "language": "en-US"
                }
            }
        }
    }
    };
   ```
   * If applicable, please provide your manual configuration example:
   ```javascript
  Amplify.configure({
  ...awsExports,
  API: {
    graphql_endpoint: awsExports.aws_appsync_graphqlEndpoint,
    graphql_region: awsExports.aws_appsync_region,
    graphql_authenticationType: awsExports.aws_appsync_authenticationType,
    aws_appsync_graphqlEndpoint: awsExports.aws_appsync_graphqlEndpoint,
    aws_appsync_region: awsExports.aws_appsync_region,
    aws_appsync_authenticationType: awsExports.aws_appsync_authenticationType,

    graphql_headers: async () => {
      const session = await Auth.currentSession();
      return {
        Authorization: session.getIdToken().getJwtToken(),
      };
    },
    },
    });
     Amplify.register(Predictions);
     Predictions.addPluggable(new AmazonAIPredictionsProvider());
   ```

**Comment by SebSchwartz** [comment]
@wlee221 no news to my question :(

**Comment by wlee221** [comment]
Hi @SebSchwartz! Sorry this took long to respond. Right now, `Predictions` use Transcribe streaming service that accepts raw audio stream and not mp3. If you are not required to mp3, I would suggest you use some package like [microphone-stream](https://www.npmjs.com/package/microphone-stream). There's a working example on our docs for this: https://docs.amplify.aws/lib/predictions/sample/q/platform/js.

Otherwise, this would be a feature request if you need to use mp3.

**Comment by wlee221** [comment]
We will close this issue as the suggested solution works for the use case. You are always welcome to open a new issue if you are looking for a mp3 support as a feature request. Thanks!
