### ISSUE TITLE
Selective sync ignores delta sync

### ISSUE THREAD

**Issue by TheMoums** [aws-amplify/amplify-js#7495]
**Describe the bug**
We are trying out the selective sync but the sync operations seem to be called from scratch on every page reload (like if delta sync was not taken into account).
 
When not using any selective sync and on _DataStore.start()_, on page refresh, sync operations were returning:
 `{data: [] }` because nothing had changed. 

But, with the selective sync, when reloading the page, all sync operations are returning all the data again which is a huge performance drawback. 

This issue was supposed to be solved by https://github.com/aws-amplify/amplify-js/pull/7200
But the problem persists anyway.
**To Reproduce**
The following configuration
```
const getClientId = async () => { 
const user = await Auth.currentAuthenticatedUser(); const userAttributes = await Auth.userAttributes(user); 
const clientIdAttribute = userAttributes.find((attribute) => attribute.getName() === ‘custom:clientId’); 
return !isNil(clientIdAttribute) && !isNil(clientIdAttribute.getValue()) ? clientIdAttribute.getValue() : null; 
}; 

DataStore.configure({ 
syncExpressions: [ 
    syncExpression(Address, async () => { 
    const clientId = await getClientId(); 
    return (t: ModelPredicate<Address>) => t!.clientId(‘eq’, clientId!); 
    }), 
  syncExpression(Contact, async () => { 
  const clientId = await getClientId(); 
  return (t: ModelPredicate<Contact>) => t!.clientId(‘eq’, clientId!); }); 
   }),
 ],
});
```
Refetch all data in the sync queries at each refresh, like nothing was synced.
(The clientId is the same each time as the user stays logged in and just refreshing the page.)
**Expected behavior**
If nothing has changed in the database, the sync operations should be returning `{data: [] }`

**What is Configured?**
I'm using the latest version of **@aws-amplify/datastore**

If applicable, please provide what is configured for Amplify CLI:
* Which resources do you have configured?
  * If applicable, please provide your `aws-exports` file:
```
const awsmobile = {
 "aws_project_region": "eu-west-1",
 "aws_cognito_identity_pool_id": "eu-west-1:xxxx",
 "aws_cognito_region": "eu-west-1",
 "aws_user_pools_id": "eu-west-1_xxxxxx",
 "aws_user_pools_web_client_id": "xxxxx",
 "oauth": {
     "domain": "xxxxx-dev.auth.eu-west-1.amazoncognito.com",
     "scope": [
         "phone",
         "email",
         "openid",
         "profile",
         "aws.cognito.signin.user.admin"
     ],
     "redirectSignIn": "https://app.xxxxx.com/,https://dev.xxxxx.com/,https://test.xxxxx.com/,http://localhost:3000/,exp://127.0.0.1:19000/--/,xxxx://",
     "redirectSignOut": "https://app.xxxxx.com/,https://dev.xxxxx.com/,https://test.xxxxxx.com/,http://localhost:3000/,exp://127.0.0.1:19000/--/,xxx://",
     "responseType": "code"
 },
 "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
 "aws_content_delivery_bucket": "xxxxxx-xxxx-hostingbucket-dev",
 "aws_content_delivery_bucket_region": "eu-west-1",
 "aws_content_delivery_url": "https://xxxxx.cloudfront.net",
 "aws_user_files_s3_bucket": "xxxxx-dev",
 "aws_user_files_s3_bucket_region": "eu-west-1",
 "aws_appsync_graphqlEndpoint": "https://xxxxxxx.appsync-api.eu-west-1.amazonaws.com/graphql",
 "aws_appsync_region": "eu-west-1",
 "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
 "aws_cloud_logic_custom": [
     {
         "name": "xxxx",
         "endpoint": "https://xxxxx.execute-api.eu-west-1.amazonaws.com/dev",
         "region": "eu-west-1"
     }
 ],
 };
```
   * If applicable, please provide your manual configuration example:
```
   Amplify.configure({
...awsExports,
API: {
 graphql_endpoint: awsExports.aws_appsync_graphqlEndpoint,
 graphql_region: awsExports.aws_appsync_region,
 graphql_authenticationType: awsExports.aws_appsync_authenticationType,
 aws_appsync_graphqlEndpoint: awsExports.aws_appsync_graphqlEndpoint,
 aws_appsync_region: awsExports.aws_appsync_region,
 aws_appsync_authenticationType: awsExports.aws_appsync_authenticationType,

 graphql_headers: async () => {
   const session = await Auth.currentSession();
   return {
     Authorization: session.getIdToken().getJwtToken(),
   };
 },
 },
 });
```

**Comment by iartemiev** [comment]
@TheMoums if you inspect the network request for that graphql query in dev tools, do you see a timestamp for `lastSync` in the request payload?

**Comment by iartemiev** [comment]
Could you share screenshots or copy-paste the contents of the request payload on initial load (e.g., delete the IDB database and reload) and then after refreshing the page again.

For example, in my sample app, on initial load I see:
![Screen Shot 2021-01-05 at 10 27 51 AM](https://user-images.githubusercontent.com/29709626/103665073-fd3bfb80-4f40-11eb-8293-91f8ca26a63a.png)
(Note `lastSync` = 0, which will result in a base sync and return all of the data that matches the predicate as expected)

But then on refresh, I get
![Screen Shot 2021-01-05 at 10 28 12 AM](https://user-images.githubusercontent.com/29709626/103665140-147ae900-4f41-11eb-94b4-dae008765497.png)
Which results in a Delta sync and returns `data: []`

**Comment by TheMoums** [comment]
Hi @iartemiev 

My first syncing query looks like

![initial](https://user-images.githubusercontent.com/22890903/103667086-c502e000-4f75-11eb-93f0-b69c17e25f2a.PNG)

And results with 

![answer_initial](https://user-images.githubusercontent.com/22890903/103667173-e5329f00-4f75-11eb-8cb1-de0a60d434d1.PNG)

If I reload the page (same filter i.e. _syncExpression_), the lastSync variable is correctly set

![reload](https://user-images.githubusercontent.com/22890903/103667260-fbd8f600-4f75-11eb-9bb6-e0549425329d.PNG)

**But** everyhing is refetched from the database as shown below

![answer_reload](https://user-images.githubusercontent.com/22890903/103667509-51ad9e00-4f76-11eb-85ea-d1a38b69f98e.PNG)

**Comment by iartemiev** [comment]
Thanks for sharing that info. The library itself seems to be working as expected then. The issue might be with the AppSync resolver. Are you using a recent version of amplify-cli? If so, are you using custom resolvers (specifically for `syncContacts`)?

**Comment by TheMoums** [comment]
I'm not using using any custom resolver. However, I'm still using an old amplify-cli version (4.32.1) as I'm waiting for some specific bugs to be fixed to upgrade it.

What's the minimum cli version needed?

**Comment by iartemiev** [comment]
@TheMoums selective sync support was added to @aws-amplify/cli in version 4.32.0, however, there may be bugs in the CLI version you're using that have since been fixed that are causing this issue. Could you perhaps try creating a duplicate project with the latest CLI version to see if you're still experiencing the issue there?

**Comment by TheMoums** [comment]
I have upgrraded my cli to the latest version (4.41.1) and the problem unfortunately persists

**Comment by iartemiev** [comment]
Do you see the same behavior if you do:

1. Start app in 2 browsers
2. Perform some mutations in browser 1
3. Reload the page in browser 2

In other words, I'm curious if AppSync still performs a base sync for you when there _are_ items in the delta table.

**Comment by TheMoums** [comment]
Yes I see the same behaviour.

Below, I have started two pages on localhost:3000 in chrome as well as in edge.

If I perform a mutation, for instance createContact in my chrome browser:

![chrome_request](https://user-images.githubusercontent.com/22890903/105475826-21693d80-5ca0-11eb-9696-be84de033ef5.PNG)

And I reload my edge browser:

![edge_reload](https://user-images.githubusercontent.com/22890903/105475829-2201d400-5ca0-11eb-8174-34b974ba9ae6.PNG)

I get my new contact, but I'm still syncing all the other ones. (And I'm still re-syncing all the other tables).

**Comment by TheMoums** [comment]
@iartemiev 
Any news on this?

**Comment by iartemiev** [comment]
I've attempted multiple different ways but was not able to reproduce this issue.

Let's try this: could you share your `Contact` model definition from your schema.graphql and the corresponding sync query resolver (should be `amplify/backend/api/<app_name>/build/resolvers/Query.syncContacts.req.vtl`)

**Comment by TheMoums** [comment]
Is there a way I can send you this by mail or any other private way?

My contract forbids me to post this code online

**Comment by iartemiev** [comment]
Perhaps you could create a private GitHub repo, upload the files containing the requested information, and then add me as a contributor to the repo?

**Comment by iartemiev** [comment]
If uploading to a private repo is still considered posting it online per your contract, feel free to reach out to me directly via Discord. My handle is ObjectiveCat#3157

**Comment by iartemiev** [comment]
Your teammate SebS reached out to me on Discord and provided the requested files. I was able to reproduce and opened a [PR in the CLI ](https://github.com/aws-amplify/amplify-cli/pull/6664)repo with a minor bug fix.

**Comment by TheMoums** [comment]
It is now working with the latest version of amplify cli.

Thanks a lot!!

**Comment by iartemiev** [comment]
Great! Thank you for letting us know
