### ISSUE TITLE
withAuthenticator: login error hidden by keyboard 

### ISSUE THREAD

**Issue by hmisonne** [aws-amplify/amplify-js#7501]
**Describe the bug**

I am using the `withAuthenticator` Higher Order Component for Authentication and app users do not see login error message (wrong Username/Password): keyboard is covering error messages.
<img src="https://user-images.githubusercontent.com/52170580/103698089-af7dbe00-4f55-11eb-8f5c-d9b35ed70cb7.png" width="200"> 
To see the actual error message users have to click outside the keyboard area.
<img src="https://user-images.githubusercontent.com/52170580/103698119-bc021680-4f55-11eb-8393-d4651d2bcaf4.png" width="200"> 

Is there a way to display this error message on top of the keyboard?

**Comment by amhinson** [comment]
There isn't currently a way to change where the error message is located. The only option right now would be to create your own [custom sign in screen](https://docs.amplify.aws/ui/auth/authenticator/q/framework/react-native#using-the-authenticator-component).

We are wanting to improve the UI components for React Native in the future, so I'm going to mark this as a feature request for now to make sure it is accounted for when those improvements start 👍

**Comment by amhinson** [comment]
With that said, this could be a relatively straightforward fix of using `Keyboard.dismiss()` module from React Native to hide the keyboard on the [`signIn` method](https://github.com/aws-amplify/amplify-js/blob/main/packages/aws-amplify-react-native/src/Auth/SignIn.tsx#L53). We'd probably also want to do that for every other auth flow screen as well (i.e. sign up, forgot password, etc).

**Comment by hmisonne** [comment]
Thanks @amhinson, I would like to work on this issue (my first time contribution :smile: !) 
I will submit a PR asap
