### ISSUE TITLE
Password ONLY Access control

### ISSUE THREAD

**Issue by papistan** [aws-amplify/amplify-js#7508]
**Is your feature request related to a problem? Please describe.**
A username is not necessary for many Access control use cases, so it's extra to enter username + password, if not needed.

**Describe the solution you'd like**
User goes to page, is prompted to enter ONLY a password. Access to site is granted.

**Describe alternatives you've considered**
None

**Additional context**
I want to share with lots of people, just need a password here.
<img width="596" alt="Screen Shot 2021-01-06 at 10 41 39 AM" src="https://user-images.githubusercontent.com/17535265/103808031-355c4080-500c-11eb-8776-49ad1dfcf86f.png">

**Comment by cwomack** [comment]
@papistan, can you share a little more about what would be the implementation of this and how you'd like a single password to be used? Does it have to be a unique password or are you asking for a single password to be shared among many users?

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. Please feel free to reply back some additional context regarding the implementation and use cases you're looking for with this feature request and we'd be happy to re-open the issue.

Thank you!
