### ISSUE TITLE
SignUp Screen withAuthenticator: No errors are displayed upon submitting incorrect form inputs

### ISSUE THREAD

**Issue by hmisonne** [aws-amplify/amplify-js#7510]
**Describe the bug**
I am using the `withAuthenticator` HOC and I realized that no error messages are displayed when an input field is incorrect (wrong password format, username not available...) 

<img src="https://user-images.githubusercontent.com/52170580/103818348-30ec5380-501d-11eb-8152-828b13a0211e.gif" alt="signup_missing_error_messages" height="400"/>

I actually had to add "(8 characters min)" to the password label, otherwise users would keep on trying to sign up (with short password) without knowing what's not working

**Comment by amhinson** [comment]
Hmm that is strange! I tried to reproduce this, but I am seeing the error showing, as expected. Could you try with the latest version?
![image](https://user-images.githubusercontent.com/17091790/105919130-ec375500-5fe9-11eb-96a3-213873acd25d.png)

**Comment by hmisonne** [comment]
Hi @amhinson!

I am using the latest aws-amplify version and I am still having these issues on Android and Android emulator:
![amplify-auth-error](https://user-images.githubusercontent.com/52170580/105924183-a8951900-5ff2-11eb-9fad-2a65d1094bf6.gif)
It looks like the first time I click on Sign Up, I do not have any error, but if I click a second time, then the error is correctly showing up.

**Comment by amhinson** [comment]
Ah interesting! This looks like it might be an issue with the `ScrollView` used here, specifically the [`keyboardshouldpersisttaps`](https://reactnative.dev/docs/scrollview#keyboardshouldpersisttaps) property. Maybe we can experiment with using `handled` instead of the default (`never`)?

**Comment by hmisonne** [comment]
Thanks @amhinson, it looks like adding `keyboardShouldPersistTaps='handled'` to the `ScrollView` component fixed the error on the SignUp screen. I will submit a PR!
