### ISSUE TITLE
Support for pool per tenant

### ISSUE THREAD

**Issue by s1mrankaur** [aws-amplify/amplify-js#7539]
**Is your feature request related to a problem? Please describe.**
AWS suggests using pool per tenant in multi-tenant saas applications but amplify does not seem to support it

**Describe the solution you'd like**
Native support for pool per tenant for multi-tenant apps

**Comment by abdallahshaban557** [comment]
Closing this issue as a duplicate of https://github.com/aws-amplify/amplify-category-api/issues/452
