### ISSUE TITLE
DataStore - Data won't be synchronized. No GraphQL endpoint configured. Did you forget `Amplify.configure(awsconfig)`?

### ISSUE THREAD

**Issue by rahulnainwal** [aws-amplify/amplify-js#7541]
I am also getting the same issue even though i have added **Amplify.configure(aws_exports)** in my root file App.js. For project set-up i am using Platform integration.
Environment :
        "@aws-amplify/datastore": "^2.9.3",
        "amazon-cognito-identity-js": "^4.5.6",
        "aws-amplify": "^3.3.13",
        "react": "16.13.1",
        "react-native": "0.63.4",

_Originally posted by @rahulnainwal in https://github.com/aws-amplify/amplify-js/issues/7137#issuecomment-757916306_

**Comment by amhinson** [comment]
Could you share your `aws-exports.js` file (with any sensitive data removed)?

Also, I'd recommend removing the direct `@aws-amplify/datastore` dependency, as it is already included in `aws-amplify`. If these versions get out of sync, it can lead to multiple instances of Amplify running, which sometimes shows the error that you are seeing.

**Comment by rahulnainwal** [comment]
Hi @amhinson, thank you for consideration. I have removed direct dependency of `@aws-amplify/datastore` but still i am getting same warning. My `aws-exports.js` file looks like this:
```
const awsmobile = {
    "aws_project_region": "***********",
    "aws_cognito_identity_pool_id": "***********",
    "aws_cognito_region": "***********",
    "aws_user_pools_id": "***********",
    "aws_user_pools_web_client_id": "***********",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "***********",
    "aws_appsync_region": "***********",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
```

**Comment by DrTipmack** [comment]
Hello, I have the same problem, and I am relatively new to JS. Could you please explain what removing the direct dependency is?

**Comment by rahulnainwal** [comment]
If you are using `aws-amplify` then there is no need to install separate package of  `@aws-amplify/datastore` as it already contains datastore. So if you are using `aws-amplify` and also installed `@aws-amplify/datastore` package then just uninstall `@aws-amplify/datastore` and remove your `node_modules` and run npm i to install dependencys again.

**Comment by gHashTag** [comment]
How to remove @aws-ampify/datastore if it is generated automatically in the models folder?

```javascript
import { Schema } from '@aws-amplify/datastore'

export declare const schema: Schema
```

**Comment by johnrusch** [comment]
![Screen Shot 2022-01-14 at 12 32 13 AM](https://user-images.githubusercontent.com/35750236/149478191-11e7e583-6719-4e50-9729-34540a4900a5.png)

Yes, this is a bit confusing.

**Comment by piyapoonsawat** [comment]
I got the same problem. First I see that it stops for long lime and I think I forget to install @aws-ampify/datastore. Then, I use npm install to install it. It causes the problem. 
To solve, run npm uninstall @aws-ampify/datastore. Then, run npm install aws-amplify again.
