### ISSUE TITLE
Datastore failed to handle hash and range key

### ISSUE THREAD

**Issue by Blockchainforcommons** [aws-amplify/amplify-js#7549]
I wrote a simple scheme that would create a DynamoDB table with id (hash) and sort (range) keys : 

type FieldData @model 
  @key(fields: ["id","sort"]) {  
  id: ID!
  sort: String!
  type: String
} 

I then have a python lambda function that writes to the table, and included the fields: 
* _lastChangedAt, 
* _version, 
* _deleted, 
* createdAt, 
* updatedAt

However, calling:   

const analysis = await DataStore.query(FieldData)
console.log(analysis) 

**will result in 12 items, 1 item per available HASH key, not the entire table (107 items).** 

modelSynced:  
Object
counts: {new: 0, updated: 107, deleted: 0}
isDeltaSync: false
isFullSync: true
model: ƒ Model(init)
__proto__: Object

What am i missing here, they are clearly locally, how can i retrieve them? 
const analysis = (await DataStore.query(FieldData, (a) => a.sort("eq", 'PROP'))) doesnt work.

Thanks

**Comment by sammartinez** [comment]
@iartemiev Any feedback on this?
