### ISSUE TITLE
Amplify SignIn Form Button Customization Options

### ISSUE THREAD

**Issue by alu-men** [aws-amplify/amplify-js#7564]
While using the AmplifySignIn component in a React project, it does not appear to be possible to center or widen the Sign In button.

Code for component:
```
                <AmplifyAuthenticator handleAuthStateChange={handleAuthStateChange}>
                  <AmplifySignIn
                    headerText="Sign in with User Pool Credentials"
                    slot="sign-in"
                    hideSignUp
                  >
                    <div slot="federated-buttons"></div>
                  </AmplifySignIn>
                </AmplifyAuthenticator>
```

This code creates:

![image](https://user-images.githubusercontent.com/75809779/104824341-d32ae900-581e-11eb-8d4c-e222c0cd9678.png)

Which does not look great at the button seems to be misplaced. (Note, it appears off-center because the default form has the "Create account" option that I have disabled, as seen below)

Default form:

![image](https://user-images.githubusercontent.com/75809779/104824370-171dee00-581f-11eb-91c4-7cde1b39083b.png)

It would be great if we had the ability to either center the button on the sign in form, or widen it so that the placement looks cleaner. For example:

![image](https://user-images.githubusercontent.com/75809779/104824408-5ea47a00-581f-11eb-90b2-a4ccc704d0f8.png)

Version numbers for project are the following:
    "@aws-amplify/ui-react": "^0.2.34",
    "aws-amplify": "^3.3.14",
    "react": "^16.13.1"

**Comment by UnderSampled** [comment]
I also have run into difficulties with styling the Sign-In button. There is no custom property to specify a border-radius, so the button does not match the rest of our site's buttons.

**Comment by eddiekeller** [comment]
Yeah, CSS override support is lacking in the current implementation of these components. It is easy enough, however, to at least make it so that the sign in button takes the full width of the form, like in your screenshot, if the "Sign up" button is hidden. I'll have a PR out for that soon.

**Comment by eddiekeller** [comment]
PR merged in. Hopefully that new button width works better for you. I'm going to close this ticket, but please reach out to us when any other requests you might have!
