### ISSUE TITLE
Datastore updating a model with an array leads to duplication of the array being saved

### ISSUE THREAD

**Issue by DevTGhosh** [aws-amplify/amplify-js#7566]
**Describe the bug**
When trying to update a model that contains an array of objects the array of objects. a copy of the array objects is being pushed into the original item even if the original array is not being changed.  

**To Reproduce**

1. Create an model like 
```graphql
type QuoteInfo
  @model{
  id: ID!
  quantity: Float
  overtimeDetails: [overtimeDetail]
}

type overtimeDetail {
  multiplier: Float
  overtimeHours: Float
}
```
2. Create a model item then try to update it multiple times 

Here is what a model item looks like 
```json
"id": "OPEajAGtQB-MebWwZ",
"quantity": 10,
"overtimeDetails": [
     {
        "multiplier": 1,
        "overtimeHours": null
      },
     {
        "multiplier": 2,
        "overtimeHours": null
      },
     {
        "multiplier": 3,
        "overtimeHours": null
      },
     {
        "multiplier": 4,
        "overtimeHours": null
      }
    ],
```

Here is my update model code 
```js
      const originalRow = await DataStore.query(QuoteInfo, row.id)
      const parsedOriginalRow = JSON.parse(JSON.stringify(originalRow))
      // uses lodash isEqual(https://lodash.com/docs/#isEqual) to only update if the row being updated is different from row fetched from the datastore
      if (!isEqual(parsedOriginalRow, row)) {
        // updates the og quote and saves it
        const updatedRow = await DataStore.save(
          QuoteInfo.copyOf(originalRow, (updated) => {
            for (const property in row) {
              // Only updates the property that is different
              if (!isEqual(row[property], updated[property])) {
                console.log('updated[property]: ', updated[property])
                updated[property] = row[property]
              }
            }
          })
        )
      }
```

3. Update the quantity multiple times and you will see that overtimeDetails array is being updated with copies of original array. 

Here is an ex 
```json
"id": "OPEajAGtQB-MebWwZ",
"quantity": 30,
"overtimeDetails": [
       {
          "multiplier": 1,
          "overtimeHours": null
        },
       {
          "multiplier": 2,
          "overtimeHours": null
        },
       {
          "multiplier": 3,
          "overtimeHours": null
        },
       {
          "multiplier": 4,
          "overtimeHours": null
        },
       {
          "multiplier": 1,
          "overtimeHours": null
        },
       {
          "multiplier": 2,
          "overtimeHours": null
        },
       {
          "multiplier": 3,
          "overtimeHours": null
        },
       {
          "multiplier": 4,
          "overtimeHours": null
        }
      ],
      "_version": 3,

```

**Expected behavior**
The array object is unchanged when  updating other fields and only the relevant array object property when it is changed. 

**Screenshots**
Graphql network request has the input of 4 array objects but the output contains 8 array objects 
![image](https://user-images.githubusercontent.com/25743418/104851242-ebcbf980-5919-11eb-8587-2ac7afb0886d.png)

**Comment by DevTGhosh** [comment]
Ok so it looks like the client is sending an older version  number of the input. After every update I have a call for fetching the updated value just to make sure it  dynamo & datastore is in sync. The datastore query call is passing but there is no actual network request made by the datastore. 

Even without the datastore query the datastore should be updated right. 

Here is the network calls let me know if you need more info 
![image](https://user-images.githubusercontent.com/25743418/105077297-54e67500-5ab2-11eb-9bac-3db6dd1cbf83.png)

![image](https://user-images.githubusercontent.com/25743418/105077343-6760ae80-5ab2-11eb-97c7-3b0a76f13ba8.png)

**Comment by iartemiev** [comment]
If the client is sending an older version, then duplication is the expected behavior for the AutoMerge conflict resolution strategy. See the 2nd bullet point "conflict on a set" here: https://docs.aws.amazon.com/appsync/latest/devguide/conflict-detection-and-sync.html#automerge

> The datastore query call is passing but there is no actual network request made by the datastore.

`DataStore.query` fetches data from the local store, so you should not expect to see a network request. 

> Even without the datastore query the datastore should be updated right when the update call is made?

Yes, DataStore should keep the local store in sync with DynamoDB via AppSync subscriptions. For example, if userA performs a `DataStore.save`, userB should receive the data from that mutation as an incoming subscription message automatically and persist this data to the local store.

 If this is not the behavior you're observing, there may be an issue. Could you please add `Amplify.Logger.LOG_LEVEL = 'DEBUG'` to your app code (e.g., in the same place you call `Amplify.configure`) and check the console for any errors or warnings mentioning datastore and subscriptions?

**Comment by DevTGhosh** [comment]
Hmm not seeing any errors I will post the debug log when I update here 
Changed some of the ids and urls 
```
[DEBUG] 22:35.32 Util -  attempt #1 with this vars: ["QuoteInfo","Update","{\"id\":\"MiMUTzDpE1Y7iDbhU0A\",\"quoteId\":\"H1qVGIuOeDNoc-H86lD\",\"tenantId\":\"5203349b-43e0-428f-b0fe-ea59c3cc0f\",\"freelancers\":null,\"activeFlag\":true,\"agentCommission\":null,\"agentCommissionPercentage\":null,\"allowMarginAndOverheadPercentageGlobalUpdate\":true,\"language\":\"en\",\"category\":\"Preproduction\",\"categoryId\":1,\"categoryPrefix\":\"IA\",\"category_fr\":\"Préproduction\",\"costLineLabel\":\"106A\",\"costLineType\":\"costLine\",\"editable\":true,\"exchangeEnabled\":false,\"exchangeRate\":1,\"tableRowIndex\":7,\"isInternational\":false,\"isVisible\":true,\"item\":\"Scouting car\",\"item_fr\":\"Voiture repérages\",\"margin\":null,\"marginPercentage\":null,\"number\":null,\"overhead\":null,\"overheadPercentage\":null,\"overtimeHours\":null,\"overtimeHoursCost\":null,\"payrollTaxEnabled\":\"No\",\"payrollTaxType\":\"\",\"quantity\":10,\"rate\":null,\"rateInEuros\":null,\"subCategory\":\"Expenses\",\"subCategoryId\":2,\"subCategoryPrefix\":\"2A\",\"subCategorySuffix\":\"A\",\"subCategory_fr\":\"Frais\",\"total\":null,\"totalHeading\":null,\"totalMargin\":null,\"unit\":\"Day\",\"smg\":null,\"overtimeDetails\":[{\"multiplier\":1,\"overtimeHours\":null},{\"multiplier\":2,\"overtimeHours\":null},{\"multiplier\":3,\"overtimeHours\":null},{\"multiplier\":4,\"overtimeHours\":null}],\"_version\":1,\"_lastChangedAt\":1610824751773,\"_deleted\":null}","{}",null,null,{"data":"{\"id\":\"MiMUTzDpE1Y7iDbhU0AQz\",\"quoteId\":\"H1qVGIuOeDNoc-H86lD\",\"tenantId\":\"5203349b-43e0-428f-b0fe-ea59c3cc0f\",\"freelancers\":null,\"activeFlag\":true,\"agentCommission\":null,\"agentCommissionPercentage\":null,\"allowMarginAndOverheadPercentageGlobalUpdate\":true,\"language\":\"en\",\"category\":\"Preproduction\",\"categoryId\":1,\"categoryPrefix\":\"IA\",\"category_fr\":\"Préproduction\",\"costLineLabel\":\"106A\",\"costLineType\":\"costLine\",\"editable\":true,\"exchangeEnabled\":false,\"exchangeRate\":1,\"tableRowIndex\":7,\"isInternational\":false,\"isVisible\":true,\"item\":\"Scouting car\",\"item_fr\":\"Voiture repérages\",\"margin\":null,\"marginPercentage\":null,\"number\":null,\"overhead\":null,\"overheadPercentage\":null,\"overtimeHours\":null,\"overtimeHoursCost\":null,\"payrollTaxEnabled\":\"No\",\"payrollTaxType\":\"\",\"quantity\":10,\"rate\":null,\"rateInEuros\":null,\"subCategory\":\"Expenses\",\"subCategoryId\":2,\"subCategoryPrefix\":\"2A\",\"subCategorySuffix\":\"A\",\"subCategory_fr\":\"Frais\",\"total\":null,\"totalHeading\":null,\"totalMargin\":null,\"unit\":\"Day\",\"smg\":null,\"overtimeDetails\":[{\"multiplier\":1,\"overtimeHours\":null},{\"multiplier\":2,\"overtimeHours\":null},{\"multiplier\":3,\"overtimeHours\":null},{\"multiplier\":4,\"overtimeHours\":null}],\"_version\":1,\"_lastChangedAt\":1610824751773,\"_deleted\":null}","modelId":"MiMUTzDpE1Y7iDbhU0A","model":"QuoteInfo","operation":"Update","condition":"{}","id":"01EWDZV4VP7BH9MT7SMAD697"}]
```

```
[DEBUG] 22:35.33 AuthClass - Getting current session
[DEBUG] 22:35.35 AuthClass - Getting the session from this user:
[DEBUG] 22:35.35 AuthClass - Succeed to get the user session
```

```
[DEBUG] 22:35.35 RestClient - POST https://b6pjastgf5cnxf3fy.appsync-api.eu-west-2.amazonaws.com/graphql
````

```
[DEBUG] 22:36.85 AWSAppSyncRealTimeProvider - subscription message from AWS AppSync RealTime: {"id":"d2931efd-0988-4cb6-9382-840fc25fb","type":"data","payload":{"data":{"onUpdateQuoteInfo":{"id":"MiMUTzDpE1Y7iDbhU0","quoteId":"H1qVGIuOeDNoc-H86l","tenantId":"5203349b-43e0-428f-b0fe-ea59c3cc0","freelancers":null,"activeFlag":true,"agentCommission":null,"agentCommissionPercentage":null,"allowMarginAndOverheadPercentageGlobalUpdate":true,"language":"en","category":"Preproduction","categoryId":1,"categoryPrefix":"IA","category_fr":"Préproduction","costLineLabel":"106A","costLineType":"costLine","editable":true,"exchangeEnabled":false,"exchangeRate":1.0,"tableRowIndex":7,"isInternational":false,"isVisible":true,"item":"Scouting car","item_fr":"Voiture repérages","margin":null,"marginPercentage":null,"number":null,"overhead":null,"overheadPercentage":null,"overtimeHours":null,"overtimeHoursCost":null,"payrollTaxEnabled":"No","payrollTaxType":"","quantity":10.0,"rate":null,"rateInEuros":null,"subCategory":"Expenses","subCategoryId":2,"subCategoryPrefix":"2A","subCategorySuffix":"A","subCategory_fr":"Frais","total":null,"totalHeading":null,"totalMargin":null,"unit":"Day","smg":null,"overtimeDetails":[{"multiplier":1.0,"overtimeHours":null},{"multiplier":2.0,"overtimeHours":null},{"multiplier":3.0,"overtimeHours":null},{"multiplier":4.0,"overtimeHours":null}],"_version":2,"_lastChangedAt":1611082355488,"_deleted":null}}}}
````

Then a whole bunch of repeat of this message 

```
[DEBUG] 23:22.77 AWSAppSyncRealTimeProvider - subscription message from AWS AppSync RealTime: {"type":"ka"}
[DEBUG] 23:22.96 AWSAppSyncRealTimeProvider 
```

It's basically a repeat of all the above anytime I update.

**Comment by DevTGhosh** [comment]
> Yes, DataStore should keep the local store in sync with DynamoDB via AppSync subscriptions. For example, if userA performs a DataStore.save, userB should receive the data from that mutation as an incoming subscription message automatically and persist this data to the local store.

Also for this I am seeing that is isn't really happening properly. The subscription updates are only happeining if userB is interacting with the model in someway. 

See the video here. Each row is it's own item in dynamodb. So user A updates items row 1 & 2 it doesn't show up in userB's screen no matter how long i wait. It only shows up once user B updates row 3. 
https://user-images.githubusercontent.com/25743418/105140088-3b2e4780-5b1d-11eb-95eb-77049c392d7b.mp4

**Comment by iartemiev** [comment]
The logs aren't giving us much insight here, unfortunately. 

I saw you mention in [this issue](https://github.com/aws-amplify/amplify-js/issues/7588) that you had `aws-amplify` as well as `@aws-amplify/datastore` installed. Have you tried uninstalling `@aws-amplify/datastore`? That could be causing syncing issues.

If you tried the above and things still aren't syncing correctly, are you seeing this behavior with all of your models or only certain ones?

**Comment by DevTGhosh** [comment]
It wasn't working because I was working with redux to display the data.
