### ISSUE TITLE
Image file uploads with Storage.put() fail if size > ~5 MB

### ISSUE THREAD

**Issue by mjhecht** [aws-amplify/amplify-js#7574]
**Describe the bug**
Image files (e.g. `.png`) fail with file sizes larger than 5 MB, and work fine at smaller sizes. For larger than 5 MB files, the upload appears to complete (file progress is shown consistently for the duration of the upload), but the response yielded shows errors. From Chrome debugger:

POST fails: 400 (Bad Request).

```
index.js:1 [ERROR] 04:37.928 axios-http-handler Error: Request failed with status code 400
    at createError (createError.js:16)
    at settle (settle.js:17)
    at XMLHttpRequest.handleLoad (xhr.js:62)
```

```
index.js:1 [ERROR] 04:37.930 AWSS3ProviderManagedUpload - error happened while finishing the upload. Cancelling the multipart upload Error: Request failed with status code 400
    at createError (createError.js:16)
    at settle (settle.js:17)
    at XMLHttpRequest.handleLoad (xhr.js:62)
```

**To Reproduce**
Use `Storage.put()` to upload a file. We're using the [react-dropzone-uploader] (https://www.npmjs.com/package/react-dropzone-uploader) package for file selection and preparation.

**Expected behavior**
- Upload succeeds regardless of file size, if there is no size limit
- If there is a file size limit, it can be configured
- Files larger than the limit should fail immediately, and not show consistent progress via the `progressCallback` argument to `Storage.put()`
- Any size limitations and config options are documented with respect to `Auth`
- Clearer error message in console as to what went wrong

**Code Snippet**
Please provide a code snippet or a link to sample code of the issue you are experiencing to help us reproduce the issue. (Be sure to remove any sensitive data)

```
        return Storage.put(`${uuid}`, file.file, {
          level: "private",
          contentType: file.meta.type,
          metadata,
          progressCallback(progress) {
            setFileStatuses(prev => {
              let next = { ...prev };
              next[uuid].loaded = progress.loaded;
              next[uuid].total = progress.total;
              next[uuid].previewUrl = file.meta.previewUrl;
              return next;
            });
          },
        });
```

**Screenshots**

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.
* Which resources do you have configured?

   * If applicable, please provide your manual configuration example:
   ```
   {
    Auth: {
        identityPoolId: 'XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab',
        region: 'us-east-1',
        // identityPoolRegion: not set
        userPoolId: 'us-east-1_xxxxxxx'
        userPoolWebClientId: 'xxxxxx'
        mandatorySignIn: false,
        // authenticationFlowType: not set
       }
   }
   ```
* If applicable, provide more configuration data, for example for Amazon Cognito, run `aws cognito-idp describe-user-pool --user-pool-id us-west-2_xxxxxx` (Be sure to remove any sensitive data)
 

<details>
  <summary><strong>Environment</strong></summary>

```
 System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 51.60 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  Managers:
    pip3: 20.3.3 - /usr/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    CMake: 2.8.12.2 - /opt/local/bin/cmake
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.23.0 - /usr/local/bin/git
    Clang: 1200.0.32.28 - /usr/bin/clang
    Mercurial: 2.9+20140204 - /usr/local/bin/hg
    FFmpeg: 2.1.4 - /opt/local/bin/ffmpeg
  Servers:
    Apache: 2.4.46 - /usr/sbin/apachectl
  IDEs:
    Nano: 2.0.6 - /usr/bin/nano
    Sublime Text: 2
    VSCode: 1.52.1 - /usr/local/bin/code
    Vim: 8.2 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Perl: 5.12.4 - /opt/local/bin/perl
    PHP: 7.3.24 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.8.2 - /usr/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    SQLite: 3.8.3.1 - /opt/local/bin/sqlite3

```

</details>

**Comment by mkrn** [comment]
This is most likely because the IAM role that you're using lacks permissions to the bucket:
        "s3:PutObject",
        "s3:GetObject",
        "s3:ListBucket",
        "s3:PutObjectAcl",
        "s3:CreateMultipartUpload"

The last one may be necessary after 5MB when a multi-part upload is created. Please check the role that you're using, the identity pool's Unauthenticated role.

**Comment by mauerbac** [comment]
Sorry for the delay. Linking to https://github.com/aws-amplify/amplify-js/issues/6419

**Comment by Jun711** [comment]
@mkrn 

Is there a typo in `"s3:CreateMultipartUpload"`?  I got this error when I pasted it in IAM policy writing window input

<img width="658" alt="Screen Shot 2021-05-25 at 6 44 08 PM" src="https://user-images.githubusercontent.com/6880939/119590234-34446980-bd89-11eb-8904-63b5783d06cf.png">

**Comment by mkrn** [comment]
@Jun711  can you share the whole policy JSON? Check the version
The action exists: https://docs.aws.amazon.com/AmazonS3/latest/API/API_CreateMultipartUpload.html

Here's my example:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:PutObjectAcl",
                "s3:CreateMultipartUpload"
            ],
            "Resource": [
                "arn:aws:s3:::bucketnamehere",
                "arn:aws:s3:::bucketnamehere/*"
            ],
            "Effect": "Allow"
        }
    ]
}
```
