### ISSUE TITLE
API subscriptions fail after an update

### ISSUE THREAD

**Issue by noskovvkirill** [aws-amplify/amplify-js#7579]
**Describe the bug**
Hello! I've tried to use a subscription in my Next.js project, but it fails for an unknown reason. In a debug mode, I could see that PubSub doesn't get an API key (apiKey: undefined). I assume that the problem with incorrect configuration. The error that I see in my console 
```
AWSAppSyncRealTimeProvider.js?8f61:29 Uncaught (in promise) undefined
rejected @ AWSAppSyncRealTimeProvider.js?8f61:29
Promise.then (async)
step @ AWSAppSyncRealTimeProvider.js?8f61:30
eval @ AWSAppSyncRealTimeProvider.js?8f61:31
__awaiter @ AWSAppSyncRealTimeProvider.js?8f61:27
AWSAppSyncRealTimeProvider._startSubscriptionWithAWSAppSyncRealTime @ AWSAppSyncRealTimeProvider.js?8f61:280
eval @ AWSAppSyncRealTimeProvider.js?8f61:228
Subscription @ Observable.js?aefe:197
subscribe @ Observable.js?aefe:279
eval @ PubSub.js?b238:170
eval @ PubSub.js?b238:168
Subscription @ Observable.js?aefe:197
subscribe @ Observable.js?aefe:279
eval @ index.js?e10b:25
commitHookEffectListMount @ react-dom.development.js?61bb:19731
commitPassiveHookEffects @ react-dom.development.js?61bb:19769
callCallback @ react-dom.development.js?61bb:188
invokeGuardedCallbackDev @ react-dom.development.js?61bb:237
invokeGuardedCallback @ react-dom.development.js?61bb:292
flushPassiveEffectsImpl @ react-dom.development.js?61bb:22853
unstable_runWithPriority @ scheduler.development.js?3069:653
runWithPriority$1 @ react-dom.development.js?61bb:11039
flushPassiveEffects @ react-dom.development.js?61bb:22820
eval @ react-dom.development.js?61bb:22699
workLoop @ scheduler.development.js?3069:597
flushWork @ scheduler.development.js?3069:552
performWorkUntilDeadline @ scheduler.development.js?3069:164

```

**To Reproduce**
1. Subscriptions were failing due to the issue with SSR (#7210). 
2. I've updated Amplify ("aws-amplify": "^3.3.14") and had to deal with a new issue due to config files. I've solved that by adding Auth.configure(awsconfig) and API.configure(awsconfig) next to Amplify.configure({ ...awsconfig, ssr: true });
3. New issue with the subscriptions as described above 
4. Tried to use DataStore, but fails due the same reason 

**Code Snippet**
My schema
```
type TestProject @model 
 @auth(rules: [
    # Defaults to use the "owner" field.
    { allow: owner },
    # Authorize the update mutation and both queries.
    { allow: owner, ownerField: "editors", operations: [update, read] }])

{
  id: ID!
  title: String!
  editors: [String]!
  description: String 
  something: String
}
```
And subscription test:
```
import {API, graphqlOperation} from 'aws-amplify'
import * as subscriptions from '../../src/graphql/subscriptions'
....
  useEffect(()=>{
            const subscription = API.graphql(graphqlOperation(subscriptions.onCreateTestProject))
            .subscribe({   
                next: (newProject) => console.log('prokect', newProject)
            });
            setTimeout(()=>{subscription.unsubscribe()},500);
    },[])
```

**What is Configured?**
```
const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:xxxx",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_xxx",
    "aws_user_pools_web_client_id": "xxxxx",
    "oauth": {},
    "aws_user_files_s3_bucket": "xxxx",
    "aws_user_files_s3_bucket_region": "eu-west-2",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://xxxx.execute-api.eu-west-2.amazonaws.com/dev",
            "region": "eu-west-2"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://xxxx.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};
```
 

<details>
  <summary><strong>Environment</strong></summary>

 ```
 System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 52.10 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.9 - /usr/local/bin/npm
  Browsers:
    Chrome: 87.0.4280.141
    Safari: 13.0.4
  npmPackages:
    @auth0/auth0-react: ^1.2.0 => 1.2.0 
    @auth0/nextjs-auth0: ^0.16.0 => 0.16.0 
    @aws-amplify/ui-react: ^0.2.34 => 0.2.34 
    @mdx-js/loader: ^1.6.22 => 1.6.22 
    @next/mdx: ^10.0.5 => 10.0.5 
    @radix-ui/react-dialog: ^0.0.1 => 0.0.1 
    @react-hook/mouse-position: ^4.1.0 => 4.1.0 
    @roomservice/react: ^1.0.6 => 1.0.6 
    aws-amplify: ^3.3.14 => 3.3.14 
    aws-sdk: ^2.828.0 => 2.828.0 
    axios: ^0.21.1 => 0.21.1 
    browser-image-compression: ^1.0.14 => 1.0.14 
    filepond-plugin-image-exif-orientation: ^1.0.9 => 1.0.9 
    filepond-plugin-image-preview: ^4.6.4 => 4.6.4 
    is-image-url: ^1.1.8 => 1.1.8 
    jsonwebtoken: ^8.5.1 => 8.5.1 
    jwk-to-pem: ^2.0.4 => 2.0.4 
    jwt-decode: ^3.1.1 => 3.1.2 
    lodash-move: ^1.1.1 => 1.1.1 
    markdown-to-jsx: ^7.1.1 => 7.1.1 
    moment: ^2.29.1 => 2.29.1 
    next: ^10.0.5 => 10.0.5 
    react: 16.13.1 => 16.13.1 
    react-contenteditable: ^3.3.5 => 3.3.5 
    react-cursor-position: ^3.0.3 => 3.0.3 
    react-dom: 16.13.1 => 16.13.1 
    react-draggable: ^4.4.3 => 4.4.3 
    react-dropzone: ^11.2.4 => 11.2.4 
    react-filepond: ^7.1.0 => 7.1.0 
    react-flip-toolkit: ^7.0.13 => 7.0.13 
    react-flow-renderer: ^8.3.7 => 8.3.7 
    react-hook-form: ^6.14.2 => 6.14.2 
    react-infinite-scroll-component: ^5.1.0 => 5.1.0 
    react-mde: ^11.0.6 => 11.0.6 
    react-motion: ^0.5.2 => 0.5.2 
    react-outside-click-handler: ^1.3.0 => 1.3.0 
    react-resize-detector: ^5.2.0 => 5.2.0 
    react-sortable-hoc: ^1.11.0 => 1.11.0 
    recoil: ^0.1.2 => 0.1.2 
    sass: ^1.32.4 => 1.32.4 
    showdown: ^1.9.1 => 1.9.1 
    url-regex: ^5.0.0 => 5.0.0 
    use-editable: ^1.2.0 => 1.2.0 
  npmGlobalPackages:
    @aws-amplify/cli: 4.39.0
    contentful-cli: 1.4.39
    expo-cli: 3.27.10
    gatsby-cli: 2.12.99
    http-server: 0.11.1
    marked: 1.2.7
    n.: 0.0.2
    n: 6.6.0
    netlify-cli: 2.59.1
    node-gyp: 5.0.3
    node-static: 0.7.11
    nodemon: 2.0.4
    npm: 6.14.9
    sass: 1.26.10
```

</details>

Thank you!

**Comment by noskovvkirill** [comment]
So, after diving a bit more into issue to understand what is going on, I assume it's related to the problem with field ownership. I've changed the code to use DataStore and it gave me a more explicit reasons for subscriptions to fail.
In my schema I have 
```
 { allow: owner },
 { allow: owner, ownerField: "editors", operations: [update, read] }])
```
Two @auth rules together are conflicting somehow and subscriptions are generated incorrectly (without ($owner: String!))  
```
 subscription OnUpdateBlocksPrivate {
    OnUpdateBlocksPrivate {
    }
  owner
}
```

However, if I specify actions for an owner explicitly such as 
 ```
 { allow: owner, operations: [create, delete, update, read] },
  { allow: owner, ownerField: "editors", operations: [update, read] }
```
Then subscriptions are correct
 ```
subscription OnUpdateBlocksPrivate($owner: String!, $editors: String!) {
    onUpdateBlocksPrivate(owner: $owner, editors: $editors) {
```
 
 but I still see in my console 
```
react_devtools_backend.js:2430 [WARN] 08:09.444 DataStore - subscriptionError Connection failed: {"errors":[{"message":"Validation error of type MissingFieldArgument: Missing field argument owner @ 'onUpdateBlocksPrivate'"}]}
overrideMethod @ react_devtools_backend.js:2430
ConsoleLogger._log @ ConsoleLogger.js?36de:107
ConsoleLogger.warn @ ConsoleLogger.js?36de:150
error @ subscription.js?3369:322
notifySubscription @ Observable.js?aefe:140
onNotify @ Observable.js?aefe:179
error @ Observable.js?aefe:240
error @ Observable.js?aefe:330
notifySubscription @ Observable.js?aefe:140
onNotify @ Observable.js?aefe:179
error @ Observable.js?aefe:240
error @ PubSub.js?b238:173
notifySubscription @ Observable.js?aefe:140
onNotify @ Observable.js?aefe:179
error @ Observable.js?aefe:240
AWSAppSyncRealTimeProvider._handleIncomingSubscriptionMessage @ AWSAppSyncRealTimeProvider.js?8f61:501

```
If I use  
`{ allow: owner, ownerField: "editors", operations: [update, read] }]) `
without  
`{ allow: owner }`
then everything works. 

I can work with an editors @auth field only for now. I can prevent editors from changing fields of others client-side by checking against owner field, but would love to have a server side solution for safety. Appreciate any advice or help.

**Comment by iartemiev** [comment]
Hey @noskovvkirill, the array of owners auth rule (`editors: [String]`) does not work with AppSync subscriptions, and since DataStore relies on subscriptions to keep the local store updated, this auth rule will not work correctly with DataStore. 

If you know the groups in advance and membership in them is consistent throughout your app, you could leverage static group auth with Cognito groups and then add/remove users to those groups. 

E.g., 
```gql
{ allow: owner },
{ allow: groups, groups: ["editor"], operations: [update, read]  }
```
This auth configuration is compatible with subscriptions and DataStore. However, if you need to be able to have different lists of editors for different items, this will not work, unfortunately.

The teams are working on enabling dynamic auth rules, such as the array of owners, so please keep checking back.

**Comment by noskovvkirill** [comment]
@iartemiev Oh, I see. Unfortunately, I need a dynamic auth rules to let users invite collaborators and edit project together. Good to know that it's on a roadmap! I really hope to see it implemented soon. Thank you for the reply! I will close an issue for now.

**Comment by jarrodwatts** [comment]
Any update on this? I've just come across this issue

**Comment by noskovvkirill** [comment]
@jarrodwatts It doesn't work yet, but I saw that they've added multi-auth https://github.com/aws-amplify/amplify-js/pull/8008 to DataStore. I hope it means that subscriptions will support multi-auth queries too.

**Comment by noskovvkirill** [comment]
> @jarrodwatts It doesn't work yet, but I saw that they've added multi-auth #8008 to DataStore. I hope it means that subscriptions will support multi-auth queries too.

It seems like I'm wrong — just tried to subscription on a multi-auth field after update and it worked!

**Comment by iartemiev** [comment]
@noskovvkirill we've merged the multi-auth PR, but have not yet released it. We're planning on releasing it in the very near future in the next stable version of aws-amplify. 

I want to clarify that multi-auth allows you to use [multiple authorization rules](https://docs.amplify.aws/cli/graphql-transformer/auth#multiple-authorization-rules) in a single API, for example, API key + Cognito + IAM. 

Multi-auth does not, however, enable using a dynamic list of owners with DataStore (i.e., `{ allow: owner, ownerField: "editors", operations: [update, read] }])`). That's a separate feature that we're working on with the AppSync team and will be released at a later date.

**Comment by jarrodwatts** [comment]
I am in the same boat as @noskovvkirill .
I was hoping to design a collaborative-style app with subscriptions but not possible currently :(

That does seem like quite a _big_ limitation on subscriptions though - would love to see it implemented 😄

**Comment by shubhamsharma98** [comment]
I'm stuck on similar issue as well, however, to my surprise the subscription is firing on the subsequent event but not on the first event. Here is the sample code: 

```js
IOUEntryCreatedListener = API.graphql(
        graphqlOperation(onCreateIOUEntry, {
          iouOwnerId: ownerSubscriber,
          iouEditor: editorSubscriber,
        })
      ).subscribe({
        next: newEntry => onIOUEntryCreatedListener(newEntry.value.data.onCreateIOUEntry),
        error: error => console.error('onIOUEntryCreatedListener err: ', error)
      });
```
Here, I have auth directive applied to two fields - iouOwnerId and iouEditor and so I'm adding both in the listener. The listener shows 'undefined' on the first event but fires off afterwards for every event! 🤷🏻‍♂️

If the functionality is not there yet, how is it so that I'm able to get the subscription for subsequent events?
