### ISSUE TITLE
Issue with using of authenticateUser() on Amazon Cognito

### ISSUE THREAD

**Issue by illunerkorea** [aws-amplify/amplify-js#7604]
**Describe the bug**
I am trying to implement sign in function for the website using Cognito, and I believe there is an issue implementing authenticateUser(). I have successfully implemented signing up and verification process of the Cognito, but when I am trying to sign in using the verified account information, the authenticateUser() part of the code seems to error.

**To Reproduce**
I have the UI for the sign in process.
1. I put the user sign in information on the UI.
2. I click submit.
3. The website it supposed to produce action, but it does not.

I checked whether the UI part of the website works fine or not; it seems like the information that I put in are correctly carried in in this part of the code. I used alert() function to check where the code errors, and that's where I figured that authenticateUser() part of the code is not implemented correctly.

**Code Snippet**
function handleSignin() {
	AWSCognito.config.region = _config.cognito.region;

	var poolData = {
        	UserPoolId: _config.cognito.userPoolId,
        	ClientId: _config.cognito.userPoolClientId
    	};

    	var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData);

    	var email = document.getElementById("login-email").value;
        var password = document.getElementById("login-password").value;

    	var authenticationData = {
    		Username : email,
    		Password : password
  	};

  	var userData = {
   		Username : email,
    		Pool : userPool
  	};

  	var authenticationDetails = new AWSCognito.CognitoIdentityServiceProvider.AuthenticationDetails(authenticationData);
  	var cognitoUser = new AWSCognito.CognitoIdentityServiceProvider.CognitoUser(userData);

  	cognitoUser.authenticateUser(authenticationDetails, {
    		onSuccess: function (result) {
      			var accessToken = result.getAccessToken().getJwtToken();
            		var idToken = result.idToken.jwtToken;
            		console.log('Successfully Logged In');
                	location.href = 'aboutus.html';
    		},
    		onFailure: function(err) {
      			alert(err);
    		}
  	});
}

**Comment by amhinson** [comment]
Could you share the error you are seeing as well?

**Comment by illunerkorea** [comment]
@amhinson I am using the response of the UI to test the code so I don't have the specific error message, unfortunately. Would you have any recommendations on the possible testing method that I might be able to use?

**Comment by amhinson** [comment]
Would you be able to share a sample repo that shows the behavior, and/or a video of what you are seeing? Unfortunately it is hard to debug these sorts of issues without a clear reproduction sample.
