### ISSUE TITLE
When run the amplify from localhost, getting {"data": {}, "errors": [[GraphQLError: Network Error]]} error

### ISSUE THREAD

**Issue by fistofzen** [aws-amplify/amplify-js#7612]
**Describe the bug**
When run the amplify from localhost, getting {"data": {}, "errors": [[GraphQLError: Network Error]]} error
**To Reproduce**
 
1.  run amplify mock api
2.  const Data = await API.graphql(graphqlOperation(listDatas));
3.  test it from android emultor

**Expected behavior**
I expect to return the data but it throws  {"data": {}, "errors": [[GraphQLError: Network Error]]} error

**Code Snippet**
const Data = await API.graphql(graphqlOperation(listDatas));

awsmobile file : 

/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "XXXXXXXXX",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "XXXXXXXX",
    "aws_user_pools_web_client_id": "XXXXXXX",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "http://127.0.0.1:20002/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "XXXXXXXXX",
    "aws_appsync_dangerously_connect_to_http_endpoint_for_testing": true
};

export default awsmobile;

**Comment by sammartinez** [comment]
@fistofzen can you provide the documentation you are walking through to get to this issue? 

Also, can you provide your `package.json` along with your environment settings? 

Please use the follow command: 
```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

Thanks ahead of time!

**Comment by fistofzen** [comment]
Hello, 

package.json file : 
{
  "name": "NameOfApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^5.9.10",
    "@react-navigation/bottom-tabs": "^5.11.3",
    "@react-navigation/native": "^5.9.0",
    "@react-navigation/stack": "^5.13.0",
    "amazon-cognito-identity-js": "^4.5.7",
    "aws-amplify": "3.3.15",
    "aws-amplify-react-native": "^4.3.1",
    "lottie-ios": "^3.1.8",
    "lottie-react-native": "^3.5.0",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-gesture-handler": "^1.9.0",
    "react-native-iphone-x-helper": "^1.3.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-maps": "0.27.1",
    "react-native-maps-directions": "^1.8.0",
    "react-native-reanimated": "^1.13.2",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.16.1",
    "react-native-svg": "^12.1.0"
  },
  "devDependencies": {
    "@babel/core": "7.12.10",
    "@babel/runtime": "7.12.5",
    "@react-native-community/eslint-config": "1.1.0",
    "babel-jest": "25.5.1",
    "eslint": "6.8.0",
    "jest": "25.5.4",
    "jetifier": "^1.6.6",
    "metro-react-native-babel-preset": "0.59.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by fistofzen** [comment]
@sammartinez 

And the system is : 

ystem:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz 
    Memory: 13.40 GB / 31.70 GB
  Binaries:
    Node: 12.19.0 - C:\Program Files\nodejs\node.EXE       
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.63) 
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @babel/core: 7.12.10 => 7.12.10 
    @babel/runtime: 7.12.5 => 7.12.5 
    @react-native-community/eslint-config: 1.1.0 => 1.1.0  
    @react-native-community/masked-view: ^0.1.10 => 0.1.10 
    @react-native-community/netinfo: ^5.9.10 => 5.9.10     
    @react-navigation/bottom-tabs: ^5.11.3 => 5.11.3       
    @react-navigation/native: ^5.9.0 => 5.9.0 
    @react-navigation/stack: ^5.13.0 => 5.13.0 
    amazon-cognito-identity-js: ^4.5.7 => 4.5.7 
    aws-amplify: 3.3.15 => 3.3.15
    aws-amplify-react-native: ^4.3.1 => 4.3.1
    babel-jest: 25.5.1 => 25.5.1
    eslint: 6.8.0 => 6.8.0
    jest: 25.5.4 => 25.5.4
    jetifier: ^1.6.6 => 1.6.6
    lottie-ios: ^3.1.8 => 3.1.8
    lottie-react-native: ^3.5.0 => 3.5.0
    metro-react-native-babel-preset: 0.59.0 => 0.59.0
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-gesture-handler: ^1.9.0 => 1.9.0
    react-native-linear-gradient: ^2.5.6 => 2.5.6
    react-native-maps: 0.27.1 => 0.27.1
    react-native-maps-directions: ^1.8.0 => 1.8.0
    react-native-reanimated: ^1.13.2 => 1.13.2
    react-native-safe-area-context: ^3.1.9 => 3.1.9
    react-native-screens: ^2.16.1 => 2.17.1
    react-native-svg: ^12.1.0 => 12.1.0
    react-test-renderer: 16.13.1 => 16.13.1
  npmGlobalPackages:
    @aws-amplify/cli: 4.41.2
    @ui5/cli: 2.6.4
    expo-cli: 4.0.17
    generator-code: 1.4.0
    git: 0.1.5
    nodemon: 1.18.5
    react-devtools: 4.10.1
    react-native-cli: 2.0.1
    yo: 3.1.1

**Comment by fistofzen** [comment]
When I debug the code, It throws the exception as in the screenshots below; 

![image](https://user-images.githubusercontent.com/6533119/107148452-24348580-6964-11eb-9027-b2adb5c6b08f.png)

**Comment by fistofzen** [comment]
@sammartinez 
Hello Sam, changing the proxy value in android emulator to 10.0.2.2 fixed the error.
Regards.
