### ISSUE TITLE
amazon-cognito-identity-js - authenticationFlowType:'USER_PASSWORD_AUTH' initiated with USERNAME ALIAS does not use correct username in MFA Challenge response, which causes device remembering to fail

### ISSUE THREAD

**Issue by w1z952** [aws-amplify/amplify-js#7615]
**Replication Steps:**

1. Set authenticationFlowType to 'USER_PASSWORD_AUTH' in Auth config
2. Attempt 'signIn()' Auth operation for a user in Cognito user pool set up for MFA (SMS) AND username alias
2a. Make sure the username being entered is actually an alias for the user (i.e. phone number, email, perferred_username, etc.)
3. Once the signIn operation is complete (resolves with SMS_MFA challenge), attempt a 'confirmSignIn()' Auth operation using the returned user object and the appropriate MFA code.
4. Once confirmSignIn operation is complete, attempt 'rememberDevice()' operation
5. Note 400-level error from the Cognito server

**What's happening:**
Amplify is using the username which was initially provided in the 'signIn()' operation when responding to the 'SMS_MFA' challenge, which results in a successful 'confirmSignIn()' operation, however, the 'new' device cannot be associated to the actual user when responding to 'SMS_MFA' challenge - and thus obtaining tokens - with an alias username

**What SHOULD be happening:**
Amplify should be smart enough to use the 'USER_ID_FOR_SRP' challengeParam, which was provided by the server in the 'SMS_MFA' challenge, in the username field when responding to the challenge.

**Why this is a problem:**
Currently, it is impossible to remember device via Amplify for clients configured to use authflow 'USER_PASSWORD_AUTH' and an alias username.  Users who are allowed to log in via alias email, phone number, etc. should be able to have their devices remembered, without having to enter the actual username as defined on the server.

**The Fix**

https://github.com/aws-amplify/amplify-js/blob/286c9e8fbec3ccdc5bf24edf3cbfb2bae370d751/packages/amazon-cognito-identity-js/src/CognitoUser.js#L848
`
		challengeResponses.USERNAME = this.challengeParam.USER_ID_FOR_SRP || this.username;  //FIXED;
`

**Comment by sammartinez** [comment]
@evcodes Wasn't there a similar issue you were looking at related to this?

**Comment by evcodes** [comment]
Hey @w1z952, thanks for bringing this up.

Let me take a look at this...
