### ISSUE TITLE
Unable to load Amplify

### ISSUE THREAD

**Issue by ebuychance** [aws-amplify/amplify-js#762]
_Do you want to request a feature or report a bug?_
* Unknown - not sure if the failure is my fault yet.

_What is the current behavior?_
• Loading the aws-amplify.js/aws-amplify.min.js library with a script tag I cannot seem to figure out how to access any of the classes.
• I was able to wrap the cognito-auth library in a RequireJS define block successfully, so I decided to try and use Amplify in the same way. I do need to use RequiredJS but I can not even seem to use Amplify when loading it in the head of the DOM.

_If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify._
• just trying to consume the Amplify sdk at this time.

_What is the expected behavior?_
• I should have access to the Amplify classes like Amplify and Auth.

_Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?_
• latest Amplify version (0.3.3) and Chrome Version 65.0.3325.181 / macOS Sierra

_You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app._

**Comment by mbahar** [comment]
@ebuychance please check this sample app for a reference use-case with script tag:
https://jsfiddle.net/0gmqtq7g/226/

**Comment by ebuychance** [comment]
Ah ha and Eureka!
`Amplify = window['aws-amplify']` is the key. **Thanks!**
I will play with this some more now and mark this as closed.

**Comment by ebuychance** [comment]
@mbahar I can not seem to get Amplify access from within a requireJS define wrapper. Any ideas would greatly be appreciated - thanks! The window global scope seems to be an issue?

**Comment by ebuychance** [comment]
The sample app does not seem to work for me either.

**Comment by mlabieniec** [comment]
@ebuychance I created a fiddle here that uses window['aws-amplify'] with auth:
https://jsfiddle.net/0gmqtq7g/226/

**Comment by ebuychance** [comment]
I think my issue with the fiddle demo app is I do not know where to get my identity pool id. I was using the amazon-cognito-auth.js lib and did not need it there...

But trying to load the amplify lib in my own app I get 'undefined' even using the CDN.
`const Amplify = window['aws-amplify'];`
Amplify is always undefined for me...

The script src tag in the head and script code block is at the end of my html body. I see the amplify lib loaded but missing from the window object...

Not sure what I am missing still?

**Comment by ebuychance** [comment]
@mbahar @mlabieniec **If I go back to version 0.2.15 I do not see the error... and can load the lib.**

**Comment by andersforsell** [comment]
I ran into a similar issue when trying to use aws-amplify.min.js: `Uncaught TypeError: Cannot set property 'createCredentials' of undefined
    at index.js:94
    at index.js:95
    at Object.<anonymous> (index.js:81)
    at t (bootstrap 515bcd2fd5c585957926:19)
    at Object.<anonymous> (AuthenticationHelper.js:21)
    at t (bootstrap 515bcd2fd5c585957926:19)
    at Object.<anonymous> (aws-amplify.min.js:22007)
    at t (bootstrap 515bcd2fd5c585957926:19)
    at Object.<anonymous> (Auth.js:51)
    at t (bootstrap 515bcd2fd5c585957926:19)`

See https://jsfiddle.net/aforsell/jnro7g6p/  (check the Console for the error)

With version 0.2.15 it works, see https://jsfiddle.net/aforsell/0v36znch (Console shows Amplify object correctly)

Any updates when this can be fixed?

**Comment by elorzafe** [comment]
@andersforsell I've just tried version 1.1.19 and it works as expected. Feel free to reopen or create a new issue if this problem persists. (tested there https://jsfiddle.net/zog84ej9/)
