### ISSUE TITLE
Deprecation notice on npm amazon-cognito-auth-js

### ISSUE THREAD

**Issue by jlsjonas** [aws-amplify/amplify-js#7627]
Please add a deprecation notice to https://www.npmjs.com/package/amazon-cognito-auth-js to avoid people from accidentally starting to use it;only the github repo has a deprecation notice now; where it's stated that, while development of the (v2) package will continue, it seems that only v1 (which is no longer maintained) will reside under that name on NPM.

If this is not the case, please clarify this.

Thank you

**Comment by tannerabread** [comment]
@jlsjonas Thank you for pointing this out, we will be handling this soon and I will close the issue when it is complete

**Comment by tannerabread** [comment]
This warning is now shown on the npm page and if you try to install the package. Thank you again for pointing this out!

**Comment by bulatgab** [comment]
Hello. I am curious about `amazon-cognito-identity-js` - is it deprecated now?
It is not marked as such on npm and it is receiving updates 🤔 
(but Amplify is the recommended way?)

**Comment by bulatgab** [comment]
I see it's been added in #13086 and is now shown on the npm page, thank you
