### ISSUE TITLE
Local React App Not Synching to cloud

### ISSUE THREAD

**Issue by Ama-Lion** [aws-amplify/amplify-js#7642]
**Describe the bug**
I have a React App created with Amplify console that was perfectly synching with the cloud.
I am using Amplify Admin ui DataStore to create my contents and my Backend.
And I am also using Amplify manual deployment to deploy my frontend
So here are the issues :
- My local app is non longer synching to the cloud. 
i.e when i add contents locally it works and i see them but i can't see them on the cloud.
- My productions app does not sync either and also when i use prod app to add contents, i don't see it locally neither in the cloud.

I looked at this https://github.com/aws-amplify/amplify-js/issues/5448  GitHub issues trying to solve the problem but still is not working.

So the only thing working is my local environment.
AS U CAN SEE ON MY SCREENSHOT I HAVE 23 ARRAY OF USERS AND ON THE CLOUD ONLY THREE USERS.

Thank you..

**Screenshots**

<img width="1315" alt="Capture d’écran 2021-01-28 à 18 45 13" src="https://user-images.githubusercontent.com/51505362/106177615-082d2900-6199-11eb-9d2f-a7b4d2063eab.png">

<img width="1093" alt="Capture d’écran 2021-01-28 à 18 53 35" src="https://user-images.githubusercontent.com/51505362/106178511-26475900-619a-11eb-917a-586c4e8df668.png">

IN INDEX.JS 
`import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import './index.css'

import Amplify from "@aws-amplify/core"
import config from './aws-exports'
Amplify.configure(config)

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);`
<details>
  <summary><strong>Environment</strong></summary>

</details>

**Comment by elorzafe** [comment]
@Ama-Lion can you clean your local store or try incognito mode?

**Comment by iartemiev** [comment]
In Chrome Dev Tools:

![image](https://user-images.githubusercontent.com/29709626/106190854-32222380-6178-11eb-9de5-107057977d5d.png)

Click that button, then refresh the page.

I would also enable logging with `Amplify.Logger.LOG_LEVEL = 'DEBUG'`

Then go through the logs in the Dev Tools Console and see if you come across any errors or warnings around sync, subscriptions, etc.

**Comment by Ama-Lion** [comment]
okay 

> In Chrome Dev Tools:
> 
> ![image](https://user-images.githubusercontent.com/29709626/106190854-32222380-6178-11eb-9de5-107057977d5d.png)
> 
> Click that button, then refresh the page.
> 
> I would also enable logging with `Amplify.Logger.LOG_LEVEL = 'DEBUG'`
> 
> Then go through the logs in the Dev Tools Console and see if you come across any errors or warnings around sync, subscriptions, etc.

okay thank you.
But why that my app is not sending data to the cloud?
I still have three users on my Admin ui.
i can see the data that is in the cloud and i can't send data to the cloud.

**Comment by Ama-Lion** [comment]
- APP NOT SYNCHING TO CLOUD
- I CAN ADD CONTENTS LOCALLY BUT IT WON'T APPEAR ON THE CLOUD
- MY CONTENTS ON THE CLOUD ARE NOT SHOWING WHEN I USE QUERY METHODE. IT ONLY SHOW CONTENTS I ADDED LOCALLY.
- AND ON PROD NOTHING WORKS

**Comment by iartemiev** [comment]
The steps we shared with you are supposed to help you diagnose the syncing issues

**Comment by Ama-Lion** [comment]
It's still not working

**Comment by iartemiev** [comment]
Are you seeing any errors or warnings in the logs?

**Comment by Ama-Lion** [comment]
No errors

**Comment by Ama-Lion** [comment]
do you use discord ??
i would love to share my screen with you.

**Comment by iartemiev** [comment]
> No errors

Have you enabled the logs with `Amplify.Logger.LOG_LEVEL = 'DEBUG'`?

Please share the logs you're seeing.

**Comment by Ama-Lion** [comment]
![Capture d’écran 2021-01-28 à 21 32 09](https://user-images.githubusercontent.com/51505362/106195337-4e41b700-61b0-11eb-85ec-4b287bfb05ae.png)

**Comment by Ama-Lion** [comment]
![Uploading Capture d’écran 2021-01-28 à 21.32.42.png…]()

**Comment by Ama-Lion** [comment]
<img width="716" alt="Capture d’écran 2021-01-28 à 21 32 42" src="https://user-images.githubusercontent.com/51505362/106195465-77624780-61b0-11eb-8280-f5d45152990a.png">

**Comment by iartemiev** [comment]
Delete lines 19 - 24 and replace that with `Logger.LOG_LEVEL = 'DEBUG'` then refresh your app and look in the Console tab in Dev Tools

**Comment by Ama-Lion** [comment]
![Capture d’écran 2021-01-28 à 21 36 56](https://user-images.githubusercontent.com/51505362/106195801-f9eb0700-61b0-11eb-99c5-0d51761c6a7f.png)

**Comment by iartemiev** [comment]
The logs will appear in the browser console. Even if there are no errors, there will be lots of Amplify logs in there. Please paste them here.

**Comment by Ama-Lion** [comment]
![Uploading Capture d’écran 2021-01-28 à 21.42.22.png…]()

**Comment by Ama-Lion** [comment]
<img width="1439" alt="Capture d’écran 2021-01-28 à 21 42 22" src="https://user-images.githubusercontent.com/51505362/106196556-dbd1d680-61b1-11eb-89ae-a73b46648e5f.png">

**Comment by iartemiev** [comment]
Is there a `aws_appsync_graphqlEndpoint` property in your aws-exports.js file?

**Comment by Ama-Lion** [comment]
yes

> Is there a `aws_appsync_graphqlEndpoint` property in your aws-exports.js file?

**Comment by iartemiev** [comment]
Please share the contents of your `package.json`

**Comment by Ama-Lion** [comment]
`{
  "name": "develop",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@aws-amplify/ui-react": "^0.2.32",
    "@material-ui/core": "^4.11.2",
    "@material-ui/data-grid": "^4.0.0-alpha.13",
    "@material-ui/icons": "^4.11.2",
    "@material-ui/styles": "^4.11.2",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "aws-amplify": "^3.3.14",
    "material-ui": "^0.20.2",
    "material-ui-phone-number": "^2.2.6",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.1",
    "web-vitals": "^0.2.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
`

**Comment by Ama-Lion** [comment]
![Capture d’écran 2021-01-28 à 21 54 56](https://user-images.githubusercontent.com/51505362/106197916-90b8c300-61b3-11eb-96b1-4e8ea9b2596b.png)

**Comment by iartemiev** [comment]
Try replacing line 6 of your index.js with: 
```js
import Amplify from 'aws-amplify'
```
Then re-start your app and check if you're still seeing the "No GraphQL Endpoint" warning in the console.

**Comment by Ama-Lion** [comment]
<img width="1315" alt="Capture d’écran 2021-01-28 à 22 04 25" src="https://user-images.githubusercontent.com/51505362/106198836-d45ffc80-61b4-11eb-813e-51ec86e96438.png">

**Comment by iartemiev** [comment]
Can you filter by DataStore and just copy and paste all of the DataStore logs you see?

**Comment by Ama-Lion** [comment]
How ??

**Comment by iartemiev** [comment]
![dsFilter](https://user-images.githubusercontent.com/29709626/106199391-67803e80-6183-11eb-9353-6f092b6f290c.gif)

**Comment by Ama-Lion** [comment]
<img width="1438" alt="Capture d’écran 2021-01-28 à 22 14 22" src="https://user-images.githubusercontent.com/51505362/106199854-50a70f80-61b6-11eb-89ce-22f2e7ac590a.png">

**Comment by iartemiev** [comment]
That looks like DataStore isn't even starting. Try interacting with it via `DataStore.query` and then check the logs

**Comment by Ama-Lion** [comment]
![Capture d’écran 2021-01-28 à 22 27 03](https://user-images.githubusercontent.com/51505362/106200902-f909a380-61b7-11eb-9ac5-b4e4a9a9d8d7.png)

**Comment by iartemiev** [comment]
Is that component actually getting rendered? It's hard to tell from just a few snippets. 
If you'd like, feel free to share the repo and I'll take a look at your app.

**Comment by Ama-Lion** [comment]
[develop-develop.zip](https://github.com/aws-amplify/amplify-js/files/5892580/develop-develop.zip)

**Comment by Ama-Lion** [comment]
here is a link of a public repo i just made for the bug fix
https://github.com/Ama-Lion/AmplifyBugFix

**Comment by Ama-Lion** [comment]
Did you found any problem on the code ??

**Comment by iartemiev** [comment]
I was able to run the app, but I'm unable to actually add a form submission because I encounter React state update errors. Therefore, I can't really diagnose any issues with the way your app is using DataStore.

A few things to note: 
1. You should only call `Amplify.configure` in one place, e.g., in your `index.js`. No need to call it again from `App.js` or `Form.js`. You do not need to call `DataStore.configure` at all unless you're wanting to overwrite some of the default syncing behavior.
2. In order to see DataStore logs, like we were discussing above, you need to be in a view where DataStore actually gets rendered, for example, your `Users` component. Try navigating to `/users` and then check the console logs for any warnings/errors around syncing or subscriptions. Alternatively, you can call `DataStore.start()` in your `index.js` or `App.js` to eagerly start DataStore before your code interacts with it. Then you will see DataStore logs in your app right away.
3.  The way you have your schema modeled, it's going to be quite difficult to fetch all of the data for a user, since you've split everything up into 19 different tables. DataStore does not resolve relations for you so if you want to get all the related data for a user, you will have to[ query each of those models separately](https://docs.amplify.aws/lib/datastore/relational/q/platform/js#querying-relations).

For example:
```js
const userId = "some-id"
const user= await DataStore.query(User, userId);
const gestionDesSols = await DataStore.query(GestionDesSols, (c) => c.userId("eq", userId));
const produitsDentretiens = await DataStore.query(ProduitsDentretiens, (c) => c.userId("eq", userId));
```
...and so on. 

if your access patterns are such that you will always need that data as part of a user, I would switch those to non-model types. E.g., 
```gql
type ImpactTerritorial @model @auth(rules: [{allow: public}]) @key(name: "byUser", fields: ["userID"]) {
  id: ID!
  userID: ID!
  q319: String
  q320: String
  ...
}

type User @model @auth(rules: [{allow: public}]) {
  id: ID!
  nom: String
  ...
  ImpactTerritorials: [ImpactTerritorial] @connection(keyName: "byUser", fields: ["id"])
}
``` 
would become 
```gql
type ImpactTerritorial {
  q319: String
  q320: String
  ...
}

type User @model @auth(rules: [{allow: public}]) {
  id: ID!
  nom: String
  ...
  ImpactTerritorials: [ImpactTerritorial]
}
```

Then when saving the data, you would only need to perform a single `DataStore.save` on the `User` model:
```js
const impactTerritorial = new ImpactTerritorial({              
  q319: this.state.q319,       
  q320: this.state.q320,
  ...
});

const user = await DataStore.save(
  new User({
    nom: this.state.nom,
    discipline: this.state.discipline,
    ...
    ImpactTerritorials: [impactTerritorial]
}));
```
And so on for all the other models.

This will allow you to retrieve these values when you `DataStore.query(User)`. In other words
```js
const user = DataStore.query(User);
const impactTerritorials = user.ImpactTerritorials // will resolve to a value, whereas the way you have it now, it will be undefined
```

**Comment by Ama-Lion** [comment]
Okay thank you.
I will try fixing all that and I will message you again if I still have problems.
Thank you a lot.

**Comment by Ama-Lion** [comment]
Hello ! 
I have a different problem this time.
When i use 
`import Amplify, { DataStore, Predicates } from "aws-amplify";`
i receive this error....
<img width="1316" alt="Capture d’écran 2021-01-31 à 12 54 27" src="https://user-images.githubusercontent.com/51505362/106383009-79e8bb00-63c3-11eb-8b29-8e84416305bc.png">

**Comment by Ama-Lion** [comment]
and when i use 
`import Amplify, { DataStore, Predicates } from "@aws-amplify/core";`
i have this error 
<img width="1365" alt="Capture d’écran 2021-01-31 à 12 56 05" src="https://user-images.githubusercontent.com/51505362/106383045-bddbc000-63c3-11eb-9206-7d988a5d4f8d.png">

**Comment by Ama-Lion** [comment]
here is the code 
`import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import './index.css'

// import Amplify from "@aws-amplify/core";
import Amplify, { DataStore, Predicates } from "@aws-amplify/core";
import config from './aws-exports';
import { Logger } from 'aws-amplify';

Amplify.configure(config);
Logger.LOG_LEVEL = 'DEBUG'
DataStore.start()

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);


`

**Comment by iartemiev** [comment]
`/core` doesn't export DataStore or Predicates. You can just import everything from `aws-amplify`. 
```js
import Amplify, { DataStore, Predicates, Logger } from 'aws-amplify';
```

**Comment by Ama-Lion** [comment]
> `/core` doesn't export DataStore or Predicates. You can just import everything from `aws-amplify`.
> 
> ```js
> import Amplify, { DataStore, Predicates, Logger } from 'aws-amplify';
> ```

but when i use this line i have this error
<img width="1313" alt="Capture d’écran 2021-01-31 à 18 43 44" src="https://user-images.githubusercontent.com/51505362/106392915-483c1800-63f4-11eb-8fde-ee10346e3e56.png">

**Comment by iartemiev** [comment]
Are you attempting to call `Amplify.configure` in more than one file? It should only be called once.

**Comment by Ama-Lion** [comment]
i only called it on my index.js

**Comment by iartemiev** [comment]
This is due to an issue with the way you're importing some of the modules.
Can you update the repo you shared with me with your latest code? I'll take another look at it.

**Comment by Ama-Lion** [comment]
okay

**Comment by Ama-Lion** [comment]
Done

**Comment by iartemiev** [comment]
Replace the contents of your `index.js` with this:
```js
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import './index.css';

import Amplify, { DataStore, Logger } from 'aws-amplify';
import config from './aws-exports';

Amplify.configure(config);
Logger.LOG_LEVEL = 'DEBUG';
DataStore.start();

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);
```

**Comment by Ama-Lion** [comment]
still the same error

**Comment by iartemiev** [comment]
Do you have all of the following properties in your aws-exports file: `aws_cognito_identity_pool_id`, `aws_cognito_region`, `aws_user_pools_id`, `aws_user_pools_web_client_id`?

**Comment by Ama-Lion** [comment]
Yeah i have everything on my aws-exports file.

when i use 
```import Amplify from "@aws-amplify/core";```
everything work but i can't import dataStore

**Comment by iartemiev** [comment]
You can try this instead:
```js
import Amplify, { Logger } from '@aws-amplify/core';
import { DataStore } from '@aws-amplify/datastore';
import config from './aws-exports';

Amplify.configure(config);
Logger.LOG_LEVEL = 'DEBUG';
DataStore.start();
```

**Comment by Ama-Lion** [comment]
thanks it works...

**Comment by iartemiev** [comment]
I looked through your package-lock and it appears you have duplicate amplify dependencies installed. That is the most reason you were seeing these issues. You can run `rm -rf node_modules package-lock.json && npm i` from the root of your project to fix this. 
Afterward, you should be able to import everything from `aws-amplify` like in [my comment above](https://github.com/aws-amplify/amplify-js/issues/7642#issuecomment-770423858) instead of from individual modules.

**Comment by Ama-Lion** [comment]
okay thank you.

**Comment by Ama-Lion** [comment]
I have good news, my app is synching.
I can now get my data from the cloud.
but am having this little error
<img width="1429" alt="Capture d’écran 2021-01-31 à 22 08 07" src="https://user-images.githubusercontent.com/51505362/106398063-1be2c480-6411-11eb-85db-9f51281474d0.png">

**Comment by Ama-Lion** [comment]
and also this method is not working for me
`const impactTerritorial = new ImpactTerritorial({              
  q319: this.state.q319,       
  q320: this.state.q320,
  ...
});

const user = await DataStore.save(
  new User({
    nom: this.state.nom,
    discipline: this.state.discipline,
    ...
    ImpactTerritorials: [impactTerritorial]
}));`
when i fill the form and send  i have this error
![Uploading Capture d’écran 2021-01-31 à 22.14.59.png…]()

**Comment by Ama-Lion** [comment]
and also this method is not working for me
`const impactTerritorial = new ImpactTerritorial({
q319: this.state.q319,
q320: this.state.q320,
...
});

const user = await DataStore.save(
new User({
nom: this.state.nom,
discipline: this.state.discipline,
...
ImpactTerritorials: [impactTerritorial]
}));`

when i fill the form and send i have this error
<img width="1140" alt="Capture d’écran 2021-01-31 à 22 14 59" src="https://user-images.githubusercontent.com/51505362/106398230-ea1e2d80-6411-11eb-810a-0f9e3a06251f.png">

**Comment by iartemiev** [comment]
Have you made changes to the graphql schema? And if so, did you do an `amplify push` afterwards?

**Comment by Ama-Lion** [comment]
![Capture d’écran 2021-02-02 à 06 48 58](https://user-images.githubusercontent.com/51505362/106557736-c0086080-6522-11eb-876f-6ae463b452ee.png)
don't you think that i should add @model on the example u snet me ??

**Comment by Ama-Lion** [comment]
<img width="1183" alt="Capture d’écran 2021-02-02 à 06 50 11" src="https://user-images.githubusercontent.com/51505362/106557816-eaf2b480-6522-11eb-9325-f82d1a2058f3.png">
i have this error when i query my data.

**Comment by Ama-Lion** [comment]
> I was able to run the app, but I'm unable to actually add a form submission because I encounter React state update errors. Therefore, I can't really diagnose any issues with the way your app is using DataStore.
> 
> A few things to note:
> 
> 1. You should only call `Amplify.configure` in one place, e.g., in your `index.js`. No need to call it again from `App.js` or `Form.js`. You do not need to call `DataStore.configure` at all unless you're wanting to overwrite some of the default syncing behavior.
> 2. In order to see DataStore logs, like we were discussing above, you need to be in a view where a component that's using DataStore actually gets rendered, for example, your `Users` component. Try navigating to `/users` and then check the console logs for any warnings/errors around syncing or subscriptions. Alternatively, you can call `DataStore.start()` in your `index.js` or `App.js` to eagerly start DataStore before your code interacts with it. Then you will see DataStore logs in your app right away.
> 3. The way you have your schema modeled, it's going to be quite difficult to fetch all of the data for a user, since you've split everything up into 19 different tables. DataStore does not resolve relations for you so if you want to get all the related data for a user, you will have to[ query each of those models separately](https://docs.amplify.aws/lib/datastore/relational/q/platform/js#querying-relations).
> 
> For example:
> 
> ```js
> const userId = "some-id"
> const user= await DataStore.query(User, userId);
> const gestionDesSols = await DataStore.query(GestionDesSols, (c) => c.userId("eq", userId));
> const produitsDentretiens = await DataStore.query(ProduitsDentretiens, (c) => c.userId("eq", userId));
> ```
> 
> ...and so on.
> 
> if your access patterns are such that you will always need that data as part of a user, I would switch those to non-model types. E.g.,
> 
> ```graphql
> type ImpactTerritorial @model @auth(rules: [{allow: public}]) @key(name: "byUser", fields: ["userID"]) {
>   id: ID!
>   userID: ID!
>   q319: String
>   q320: String
>   ...
> }
> 
> type User @model @auth(rules: [{allow: public}]) {
>   id: ID!
>   nom: String
>   ...
>   ImpactTerritorials: [ImpactTerritorial] @connection(keyName: "byUser", fields: ["id"])
> }
> ```
> 
> would become
> 
> ```graphql
> type ImpactTerritorial {
>   q319: String
>   q320: String
>   ...
> }
> 
> type User @model @auth(rules: [{allow: public}]) {
>   id: ID!
>   nom: String
>   ...
>   ImpactTerritorials: [ImpactTerritorial]
> }
> ```
> 
> Then when saving the data, you would only need to perform a single `DataStore.save` on the `User` model:
> 
> ```js
> const impactTerritorial = new ImpactTerritorial({              
>   q319: this.state.q319,       
>   q320: this.state.q320,
>   ...
> });
> 
> const user = await DataStore.save(
>   new User({
>     nom: this.state.nom,
>     discipline: this.state.discipline,
>     ...
>     ImpactTerritorials: [impactTerritorial]
> }));
> ```
> 
> And so on for all the other models.
> 
> This will allow you to retrieve these values when you `DataStore.query(User)`. In other words
> 
> ```js
> const user = DataStore.query(User);
> const impactTerritorials = user.ImpactTerritorials // will resolve to a value, whereas the way you have it now, it will be undefined
> ```

<img width="1218" alt="Capture d’écran 2021-02-02 à 06 52 35" src="https://user-images.githubusercontent.com/51505362/106557946-40c75c80-6523-11eb-91b6-eb94911402b3.png">
And also when i use the method you sent me  to submit my form i have this error.

**Comment by Ama-Lion** [comment]
It's really stressful from one error to another, my client is waiting for his app to start running again but no way.

**Comment by Ama-Lion** [comment]
Hello ! anyone here to help please ???

**Comment by Ama-Lion** [comment]
hello @iartemiev  are u there ?

**Comment by Ama-Lion** [comment]
Thank you all for helping.
I finally solved my problem.
