### ISSUE TITLE
Replace Zen-Observable with RxJS for API Package

### ISSUE THREAD

**Issue by iyz91** [aws-amplify/amplify-js#7647]
**Is your feature request related to a problem? Please describe.**
Many users, especially Angular users, utilize [RxJS](https://github.com/ReactiveX/rxjs) which is apparently far more capable than Zen and highly optimized. It's slightly annoying and bloating having both for this subset of users, and RxJS would be more than sufficient for Amplify's requirements. 

**Describe the solution you'd like**
Replace Zen-Observable with RxJS (should be fairly painless).

**Comment by elorzafe** [comment]
Thanks @iyz91 

I think needs more discussion, other customers can be on the other side as well. 

I did a quick search on bundlephobia
zen-observable: 2.1 kB (MINIFIED + GZIPPED)
rxjs: 11.1kB (MINIFIED + GZIPPED)

It seems rxjs is 5x zen-observable.

**Comment by iyz91** [comment]
Yeah fair point, but afaik RxJS is well tree shakeable since RxJS 6 so that shouldn't be a problem but having the expanded toolkit is certainly a great benefit, especially as mentioned for those who already have it as an integral component in their apps.

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
