### ISSUE TITLE
AWSOBJECT type remains a simple Javascript String when using Amplify DataStore query

### ISSUE THREAD

**Issue by juanlucky** [aws-amplify/amplify-js#7652]
**Which Category is your question related to?**
Amplify CLI, DataStore, auth, GraphQL API

**Amplify CLI Version**
4.41.2

**What AWS Services are you utilizing?**
Amplify CLI, Datastore, AppSync, Cognito User Pools, Vue.js webapp

**Provide additional details**
hello,
I defined a GQL schema containing an AWSJSON property  :
`type Movie @model
    @auth(rules: [{ allow: owner }])  
    @key(fields: ["owner","id"]) {
  id: ID!
  owner:String!
  title: String!
....
  versions: AWSJSON
}` 

The corresponding Movie GQL API was generated using Amplify "add API" with a generated DynamoDB data source.

I succeeded to create some movies from a Python app using the GQL createMovie mutator and stringify the JSON content of the "versions" property as it is designed by the AWSJSON type for transportation. 

The movie's JSON "versions" property content  is stored in DynamoDB as a JSON structure which is as expected.  

Then I tried to read the movies from a vue.js webapp using Amplify DataStore with the following code :
` await DataStore.query(Movie, Predicates.ALL).then(movies => {
            this.setMovies(movies);
            console.log (movies);
        })`
The problem is that the "versions" property of the Movie javascript model is not automatically "un-stringified"/unmarshalling from the "by design" transportation String representation.
i.e it is not automatically converted to javacript object but remains as a JS string in the Movie Object !

I had to use the code
`JSON.parse(movie.versions) `
to be able to get the real JS expected "versions" complex object
 
**Expected behavior**
Would expect to have a JS object unmarshalled from a GQL result when using the AWSOBJECT type and not a simple String.

**Comment by juanlucky** [comment]
Seems similar to #5767

**Comment by sammartinez** [comment]
Hello @juanlucky, thanks for this feedback. As this feature request is like what you called out, I am going to close this issue as a duplicate since we currently have the other issue already created. Can I have you upvote on the other issue? Thanks again for this feedback

**Comment by juanlucky** [comment]
Ok @sammartinez to close this ticket. 
It looks like more to a bug than a feature-request to me, according to [AWSJSON doc](https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html) :

"Any valid JSON construct is automatically parsed and loaded in the resolver mapping templates as maps, lists, or scalar values rather than as the literal input strings"

Otherwise, as much use the String type directly in the modèle.
