### ISSUE TITLE
signUp validationData not reference attributes

### ISSUE THREAD

**Issue by ewah** [aws-amplify/amplify-js#7655]
**Describe the bug**
validationData should not depend on attributes.  currently sending in validationData without matching attribute return generates an empty string. 

**To Reproduce**

sending 
```
{
  "username": "ed.210129r@test.com",
  "password": "Abcd123!",
  "attributes": {
    "given_name": "ed",
    "family_name": "210129r",
    "name": "ed 210129r",
    "email": "ed.210129r@test.com"
  },
  "validationData": {
    "recaptchaToken": "03AGdBq25..."
  }
}
```

yields
a payload of 
```
{"ClientId":"XXXX","Username":"ed.210129r@test.com","Password":"Abcd123!","UserAttributes":[{"Name":"given_name","Value":"ed"},{"Name":"family_name","Value":"210129r"},{"Name":"name","Value":"ed 210129r"},{"Name":"email","Value":"ed.210129r@test.com"}],"ValidationData":[{"Name":"recaptchaToken","Value":""}]}
```

adding recaptchaToken into attributes yields an AWS error further down of "Attributes did not conform to the schema: recaptchaToken: Attribute does not exist in the schema." (correctly)

**Expected behavior**
expecting validationData to be filled.

**Code Snippet**

i suspect it is this code update in packages/auth/src/Auth.ts
```
+                       const validationDataObject = params['validationData'];
+                       if (validationDataObject) {
+                               validationData = [];
+                               Object.keys(validationDataObject).map(key => {
+                                       validationData.push(
+                                               new CognitoUserAttribute({ Name: key, Value: attrs[key] })
+                                       );
                                });
                        }
-                       validationData = params['validationData'] || null;
```
where the new CognitoUserAttribute should be CognitoUserAttribute({ Name: key, Value: validationDataObject[key] })

**Screenshots**
...

**What is Configured?**
...

**Comment by ewah** [comment]
in v.3.3.13 we sent validation data as an array of Name/Value-s

**Comment by WIStudent** [comment]
Shouldn't this issue stay open until the PR is merged into the aws-amplify/amplify-js repo?
