### ISSUE TITLE
Accessing OIDC Refresh and Access Tokens with Amplify Auth (Cognito User Pools)

### ISSUE THREAD

**Issue by lvillacin** [aws-amplify/amplify-js#7657]
**Is your feature request related to a problem? Please describe.**
I need to have access to the OIDC access and refresh tokens to make a few API calls. Is there anyway I can retrieve these when using Amplify Auth?

**Comment by elorzafe** [comment]
@lvillacin are you doing `Auth.federatedSignIn` with a token from your OIDC provider?

**Comment by nadetastic** [comment]
Hi @lvillacin, following up on this issue.

If you need to have access to the OIDC tokens, then you would need to retrieve and manage those yourself, and create your own custom credentials provider to get AWS credentials through Amplify from Cognito Federated Identities as described in our [documentation here](https://docs.amplify.aws/react/build-a-backend/auth/advanced-workflows/). By default, calling `signInWithRedirect()` (previously `Auth.federatedSignIn()`) does not provide you with the 3rd party OIDC tokens as they will be retrieved and managed by Cognito on your behalf.
