### ISSUE TITLE
Storage.get should have conditional return type

### ISSUE THREAD

**Issue by avlonder** [aws-amplify/amplify-js#7667]
**Describe the bug**
Storage.get currently returns a *Promise<string|Object>*, where the object case only occurs for *config.download = true*.
As such, this would benefit from conditional typing, as it now complicates the integration in a larger typescript code base.

**Additional context**
Frankly, I just started refactoring my JS code to TS code, so I'm very new to TS, and maybe I'm overlooking some stuff.

**Comment by sammartinez** [comment]
Thank you for this feedback @avlonder. I will mark this as a feature request and we will take this into consideration for the future of the library.

**Comment by jamesaucode** [comment]
The latest Typescript improvement for Storage has been merged and released. That includes conditional return type 😄
