### ISSUE TITLE
Allow ForgotPassword as AmplifyAuthenticator.initialAuthState (TS)

### ISSUE THREAD

**Issue by ronnyroeller** [aws-amplify/amplify-js#7668]
**Is your feature request related to a problem? Please describe.**
The TypeScript signature for `AmplifyAuthenticator.initialAuthState` allows only for `AuthState.SignIn` and `AuthState.SignUp`.

Yet, we would like to open the AmplifyAuthenticator in the Forgot Password view. For example, when mailing all users to reset their passwords after a Cognito User Pool migration - we want to add a deeplink to the Forgot Password view. 

**Describe the solution you'd like**
The `AmplifyAuthenticator` does already support to other values for `initialAuthState`. Just the TypeScript signature doesn't allow it. I'd therefore propose to allow the other `AuthState` values for `initialAuthState`.

**Describe alternatives you've considered**
As a workaround, we switch off the Typescript signature check:
```typescript
<AmplifyAuthenticator initialAuthState={AuthState.ForgotPassword as any} />
```

**Comment by eddiekeller** [comment]
Some of the `AuthState` values don't really seem to make much sense as an `initialAuthState` (`VerifyingAttributes`, for instance), but `ForgotPassword` makes sense. I'll at least make an update to include that in the TypeScript definition.

Interestingly, we already have a test covering `ForgotPassword` as the `initialAuthState`, so this seems like a solid ask to me. Will put out a PR to update this.

**Comment by eddiekeller** [comment]
PR for update - https://github.com/aws-amplify/amplify-js/pull/8414

**Comment by eddiekeller** [comment]
Merged in PR.
