### ISSUE TITLE
graphql onCreateTodo returns 200 but item is not created in the DynamoDB

### ISSUE THREAD

**Issue by raullm7** [aws-amplify/amplify-js#7669]
**Describe the bug**
If i create a simple todo item, delete it and then create it again, the appsync api returns a 200 and the object itself, but the item is not stored in the DynamoDB.

**To Reproduce**
1. Create todo item (this works fine and is stored in the DB)
2. Delete the created todo item (this works fine and the item is removed from the DB)
3. Create an identical item to the recently deleted one (this returns 200 but is not stored in the DB)
4. Check the DynamoDB - the item is not there...

**Expected behavior**
I expect the api to not return a 200 status if the item was not successfully stored in the DB. The root problem tho is the item not being stored in the DB for some reason... (cant find any log)

**Code Snippet**
My code to create the todo:

```
await API.graphql(
      graphqlOperation(createTodo, {
        input: {
          ...this.state,
        },
      })
    );
```

My code to delete the todo:
```
await API.graphql(
      graphqlOperation(deleteTodo, {
        input: {
          id: this.state.id,
        },
      })
    );
```

Note that ALL the calls return a 200 - so I assume that there is nothing wrong in my clients code - i can only repro this when i create, delete and create again immediately, if I wait then it works fine.

**Screenshots**
When creating the item the second time (which fails to store it in the DB) i get a 200 response from the server:

<img width="978" alt="Screenshot 2021-02-02 at 14 53 26" src="https://user-images.githubusercontent.com/17517630/106617383-7e010e00-6566-11eb-9c45-5de46000d6a9.png">

**Comment by amhinson** [comment]
Returning a 200 response for everything is common practice with GraphQL. However, there should be an `errors` key in the response. That should give you more insight into what the problem is.

**Comment by raullm7** [comment]
Hey @amhinson - thanks for the reply! Unfortunately i do not get any errors key in the response, only a data key with the object being 'created' which is not in the DB:

<img width="345" alt="Screenshot 2021-02-03 at 10 14 39" src="https://user-images.githubusercontent.com/17517630/106732467-a2adc200-6608-11eb-9adc-3404432dfbcc.png">

**Comment by amhinson** [comment]
Could you also share your `graphql.schema` file?

**Comment by raullm7** [comment]
Yes, this is my graphql.schema:
```
type Todo @model @auth(rules: [{ allow: owner, operations: [create] }]) {
  id: ID!
  orden: Int
  descripcion: String
  entrada: AWSDateTime
  plazo: AWSDateTime
  salida: AWSDateTime
  fase: Fase
  estado: Estado
  estadoSalida: EstadoSalida
}

enum Fase {
  archivos
  preimpresion
  impresion
  encuadernacion
  transporte
  entregado
}

enum Estado {
  blanco
  verde
  naranja
  rojo
}

enum EstadoSalida {
  indefinido
  importante
  normal
}

```

**Comment by raullm7** [comment]
I have realized that it does not work when i try to create multiple items in a short amount of time (~5 secs) - it has nothing to do with the id or the name being the same...

**Comment by amhinson** [comment]
Ah ok thats good to know! Could you provide some more specific reproduction steps to make sure we are testing it in the exact same way you are?

**Comment by mauerbac** [comment]
@raullm7 - it seems our team still needs help reproducing this issue. Are you able to provide more steps ? Or provide a short screencast ?

**Comment by chrisbonifacio** [comment]
@raullm7 closing this for now as we have not heard back from you. Please re-open if you're still experiencing this issue on the latest version of Amplify.
