### ISSUE TITLE
DOMException: Failed to execute 'get' on 'IDBIndex': No key or key range specified when using Datastore.save on child element

### ISSUE THREAD

**Issue by djom202** [aws-amplify/amplify-js#7673]
**Describe the bug**
When i use Datastore.save for a child element i get the following error:

`DOMException: Failed to execute 'get' on 'IDBIndex': No key or key range specified`

```javascript
async add_vehicle({ commit, dispatch }, payload) {
    console.log('payload', payload)

    try {
      const resp = await DataStore.save(
        new Vehicle({
          enterpriseid: payload.enterprise.id,
          enterprise: new Enterprise(payload.enterprise),
          ownerid: payload.owner.sub,
          owner: new Enterprise(payload.owner),
          ...payload
        })
      )

      commit('add_vehicle_mutation', resp)
      dispatch('set_vehicleselected', resp)

      return resp
    } catch (err) {
      console.log('Error add_vehicle', err, payload)
      return err
    }
}
```

This error happen with different models, but I just explain with the vehicles since it's the same behavior

**To Reproduce**

1. vue create xxx
2. amplify init
3. npm i @aws-amplify/core @aws-amplify/datastore
4. amplify add api
5. amplify codegen models

[Code and Schema Link](https://gist.github.com/djom202/55d1a0760bfa68a6e015fb5878bb6fcf)

**Expected behavior**
I expect to save the objects locally and sync them with my Dynamo DB.

**Screenshots**
![image](https://user-images.githubusercontent.com/1834808/106666858-24084480-6576-11eb-91f1-ca3a3f5211a3.png)

**What is Configured?**
* Which resources do you have configured?
    - API
    - Auth
    - Storage
  
OS: MacOs Catalina v10.15.7
Node: 14.15.1
Npm: 6.14.11
Chrome Browser v88.0.4324.96
Vue/Cli v4.5.10

**Comment by amhinson** [comment]
You'll need to save each item individually when using DataStore: https://docs.amplify.aws/lib/datastore/relational/q/platform/js#saving-relations

Also, as an aside, we highly recommend just installing `aws-amplify` instead of the individual packages. This can lead to mismatched versions, which is known to cause various problems throughout Amplify in your app.

**Comment by djom202** [comment]
Hi @amhinson 

I just to change following your notes by:

```
const resp = await DataStore.save(
  new Vehicle({
    enterpriseid: payload.enterprise.id,
    ownerid: payload.owner.sub,
    ...payload
  })
)
```

Also I have installed the next dependencies:

- "@aws-amplify/core": "^3.8.9",
- "@aws-amplify/datastore": "^2.9.3",
- "aws-amplify": "^3.3.14"

**Comment by iartemiev** [comment]
Seems like there may be some corrupted data in your local store. Have you tried deleting your IndexedDB database via dev tools and then refreshing the page to re-sync?

**Comment by djom202** [comment]
@iartemiev yes I did, but that's not works.

**Comment by iartemiev** [comment]
> but that's not works

As in, you're unable to delete the DB? Or you're still getting the same error after deleting the DB and reloading? 

Can you please share your schema, specifically the `Vehicle` and `Enterprise` models?

Have you been getting that error since the first time you attempted to save a `Vehicle` record? Or did it work before and then stopped working?

**Comment by djom202** [comment]
@iartemiev yeah, I still getting the same error after deleting the DB and reloading the data.

The schema is into the link of the issue description.

At the first times that's works that expected but one of models was failing with this issue, now I have 4 models failing. Even I updated the amplify to check if that's solving that issue, but it's not works.

**Comment by iartemiev** [comment]
Ah, thanks! I had missed the link.

The `@versioned` directive you have [on your `Enterprise` model](https://gist.github.com/djom202/55d1a0760bfa68a6e015fb5878bb6fcf#file-schema-graphql-L14) should not be used with DataStore: https://docs.amplify.aws/cli/graphql-transformer/versioned#versioned

Also, your relationships are not defined correctly. You need to use a combination of `@key` and `@connection` as described here: https://docs.amplify.aws/lib/datastore/relational/q/platform/js.

**Comment by djom202** [comment]
@iartemiev I going to remove them @version directive and also I going to add the relationships again, but in the past I had issues before with that schema and the relationships

**Comment by iartemiev** [comment]
If you don't want to use relationships, you need to remove the `@connection` directives. The way your schema is now, the relationships are incorrectly configured both locally and in the cloud. Since `@key` is omitted from your models, the necessary indexes are not being created in IndexedDB, which is causing the error in the issue title.

**Comment by djom202** [comment]
@iartemiev Maybe I'm wrong but my relationships are 1:1 (I think so, that relationships that not needs @key directive) excepted one that I still not create so well many to many, and in the documentation that you provided me are 1 to many and many to many.

**Comment by djom202** [comment]
@iartemiev Also I updated the [Schema](https://gist.github.com/djom202/55d1a0760bfa68a6e015fb5878bb6fcf)

**Comment by djom202** [comment]
I'm still facing the same issue

![image](https://user-images.githubusercontent.com/1834808/108788036-16c2f200-7545-11eb-8aaf-e8436f3a3b67.png)

**Comment by iartemiev** [comment]
The way you're using `@connection` is still incorrect in the schema. E.g., [here](https://gist.github.com/djom202/55d1a0760bfa68a6e015fb5878bb6fcf#file-schema-graphql-L36-L39). The `@connection(name: "some name")` syntax is [deprecated](https://docs.amplify.aws/cli/graphql-transformer/connection#alternative-definition) and although it's still supported by the API category, it won't work correctly with DataStore.

For your 1:M relationships like Vehicle -> [ActivityHistory], you'll want to use `@connection` with `@key`. 
For the 1:1 relationships you can omit the name and just use do e.g., 
```gql
type Vehicle @model @auth(rules: [{ allow: public }]) {
  id: ID!
  owner: User @connection
  enterprise: Enterprise @connection
```

**Comment by djom202** [comment]
@iartemiev if the connection is 1:M so I'd know if the fields `postID´ and ´content` are all necessary or if I just need to use the fields that I need? talking about this example:

```
type Post @model {
  id: ID!
  title: String!
  comments: [Comment] @connection(keyName: "byPost", fields: ["id"])
}

type Comment @model
  @key(name: "byPost", fields: ["postID", "content"]) {
  id: ID!
  postID: ID!
  content: String!
}

```

**Comment by djom202** [comment]
Another question about the code, if I need to save the relationships 1:1, how I need to do it? e.g.

```
const resp = await DataStore.save(
  new Vehicle({
    enterprise: payload.enterprise,
    owner: payload.owner,
    ...payload
  })
)
```
Do I need to pass all the `enterprise` and ´owner´ objects (obviously I created them before), or is there any other way?

Also how I tackled the M:M relationship ?

´´´
type UserVehicle
  @model
  @auth(rules: [{ allow: public }])
  @key(name: "byDrivers", fields: ["userId", "vehicleId"])
  @key(name: "byVehicles", fields: ["vehicleId", "userId"]) {
  id: ID!
  vehicleId: ID!
  userId: ID!
  vehicle: Vehicle! @connection(fields: ["vehicleId"])
  user: User! @connection(fields: ["userId"])
  state: Int!
}
´´´

```
const resp = await DataStore.save(
  new UserVehicle({
    vehicleId: payload.vehicleId,
    userId: payload.userId,
    vehicle: payload.vehicle,
    user: payload.user,
    state: payload.state
  })
)
```

**Comment by iartemiev** [comment]
> @iartemiev if the connection is 1:M so I'd know if the fields `postID´ and ´content` are all necessary or if I just need to use the fields that I need? 

You only need the connected model's PK in the `fields` list to establish the relationship. You don't need to add any more fields.

E.g., `type Comment @model @key(name: "byPost", fields: ["postID"])` is sufficient.

> Another question about the code, if I need to save the relationships 1:1, how I need to do it? e.g.

You would pass the model as a value

```gql
type Project @model {
  id: ID!
  name: String
  team: Team @connection
}

type Team @model {
  id: ID!
  name: String!
}
```

```js
const newTeam = await DataStore.save(new Team({name: 'some-name'}));

await DataStore.save(new Project({name: 'project-name', team: newTeam}));
```

> Also how I tackled the M:M relationship ?

Just passing the models should be enough, you don't need to pass the ids as well. 

```js
const vehicle = await DataStore.query(Vehicle, 'vehicle-id');
const user = await DataStore.query(User, 'user-id');

const resp = await DataStore.save(
  new UserVehicle({
    vehicle: vehicle, 
    user: user,
    state: payload.state
  })
)
```

**Comment by djom202** [comment]
Ok great @iartemiev I changed every relationship in the models, nevertheless I still have the initial issue, so what I doing wrong? Why the models still don't allow me to save them? What I missing in the code?

**Comment by djom202** [comment]
@iartemiev I'm thinking that the relationships are the issue, I made another small platform of example without them and it's working as expected. So I going to remove them in order to solve this issue and if its works I'll let you know once I finished.

**Comment by djom202** [comment]
@iartemiev I removed them and it's working fine. I guess there are a lot relationships or there is something there that causes that issue. I just remove the `@connection` directives but I left the field that made the relationship in each model. I update the Schema.
