### ISSUE TITLE
Amazon-cognito-js: Error in getSession function

### ISSUE THREAD

**Issue by Ivan-Vetster** [aws-amplify/amplify-js#7678]
**Describe the bug**
Invoke getSession function throws error

**To Reproduce**
Steps to reproduce the behaviour:

1. Invoke getSession

**Expected behavior**
Should not throw error saying it cant find the clientMetadata of undefined

**Code Snippet**
Line 1430: this.refreshSession(refreshToken, callback, options.clientMetadata);

**Additional context**
Change line 1379 from:
- getSession(callback, options) {
to:
- 	getSession(callback, options={}) {

**Comment by elorzafe** [comment]
@Ivan-Vetster 

Apologies for the inconvenience. 

We have just release the fix for `amazon-cognito-identity-js` version `4.5.10` that solves this issue.
