### ISSUE TITLE
Cannot auto-verify email after login when changing it

### ISSUE THREAD

**Issue by dibell** [aws-amplify/amplify-js#768]
Hi,

This issue https://github.com/aws/amazon-cognito-identity-js/issues/575 has been closed but it is still an issue I believe.

Automatic verification of emails is available on sign up but **not** when emails are changed.

Is there currently a way to do this? Or a timeline for when this might be available?

Many thanks
David

**Comment by yuntuowang** [comment]
Hi @dibell, this feature request is in our queue. However, we cannot comment on its ETA.

**Comment by Targettrade** [comment]
A workaround for this issue is to use a lambda function that invokes AdminUpdateUserAttributes
and auto verifies the email.

Here is such a function:


```
'use strict';


const AWS = require('aws-sdk');
const docClient = new AWS.DynamoDB.DocumentClient();
const cognitoService = new AWS.CognitoIdentityServiceProvider();

const USERPOOLID = "USER_POOL_ID"

 /*
 
 Adds email to user attributes and performs auto verify on it
 Note: The role used with this lambda function must have access to AdminUpdateUserAttributes in IAM

 */

exports.handler = (event, context, callback) => {


     let username = event.username
     let email = event.email



      var params = {
            UserAttributes: [ 
              {
                Name: "email_verified",
                Value: "true"
              },
              {
                Name: "email",
                Value: email
              },
            ],
            UserPoolId: USERPOOLID, 
            Username: username
          };

      cognitoService.adminUpdateUserAttributes(params, function(err, data) {

          if (err) {
            console.log(err, err.stack); // an error occurred
            context.fail(err)
          }
          else  {
            context.done(null, data);
          }

      });


};

```

**Comment by Jasminou** [comment]
@Targettrade your workaound work the user is confirmed, but the user still receive an email with verification code, when we put the code in the custom message trigger.

**Comment by Targettrade** [comment]
@Jasminou I don't understand what you mean by "when we put the code in the custom message trigger". In any case, no, the above code will NOT send a verification code to the user's email as it will auto-verify them. If you are doing something else as a result of some trigger you have set up then perhaps a code is being sent but it is not the behaviour of AWS in this context

**Comment by Jasminou** [comment]
@Targettrade  I Mean I used this code in lambda function who will be triggered by cognito when user update his email, the above code don't send an email Ièm totaly agree with you.

**Comment by harrysolovay** [comment]
This is not a bug. One can use the Auth category's [`verifyUserAttribute` method](https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/Auth.ts#L1432) or `amazon-cognito-identity-js`'s underlaying [`getAttributeVerificationCode` method](https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/src/CognitoUser.js#L1698).

**Comment by njariwala2019** [comment]
I was able to auto-verify the user with the following setup: 

https://www.lazydeveloper.tech/aws/aws-amplify-how-to-auto-verify-email-on-sign-up/
