### ISSUE TITLE
Authentication Angular UI sign-up component does not respect required attributes for custom formFields array

### ISSUE THREAD

**Issue by oliverschenk** [aws-amplify/amplify-js#7682]
**Describe the bug**
When specifying the formFields attribute, the Amplify sign-up form does not display any of the required fields as required (*) and does not perform any validation to check if fields have been filled out when clicking on the CREATE ACCOUNT button.

**To Reproduce**
The initial steps to set up an Angular Amplify project are provided in issue [7636](https://github.com/aws-amplify/amplify-js/issues/7636).

After that the code is as follows:

app.component.html
```
<amplify-authenticator usernameAlias="email">
  <amplify-sign-up
    slot="sign-up"
    usernameAlias="email"
    [formFields]="formFields"
  ></amplify-sign-up>
</amplify-authenticator>
```

app.component.ts
```
import { Component } from '@angular/core';
import { FormFieldTypes, PhoneFormFieldType } from '@aws-amplify/ui-components';

@Component({
  selector: 'my-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'amplify-usernamealias';
  formFields: FormFieldTypes = [
    {
      type: "name",
      label: "Full name",
      placeholder: "Enter your full name",
      required: true
    },
    {
      type: "phone_number",
      label: "Phone number",
      placeholder: "4123456789",
      required: true,
      dialCode: "+61",
    } as PhoneFormFieldType,
    {
      type: "email",
      label: "Email address",
      required: true
    },
    {
      type: "password",
      label: "Password",
      required: true
    }
  ];

}
```

**Expected behavior**
Each field where `required: true` should show an asterisk (*) next to the field name and should validate when no value is provided.

**Code Snippet**
The repo is here:
https://github.com/oliverschenk/aws-amplify-username-alias

**Screenshots**
![not-required](https://user-images.githubusercontent.com/17871110/106910452-3207c200-673c-11eb-86e3-dccb283305e3.PNG)

**Comment by ErikCH** [comment]
@oliverschenk Looks like this has been resolved in [7636](https://github.com/aws-amplify/amplify-js/issues/7636). Please let us know if it doesn't.

**Comment by sammartinez** [comment]
With the above comment being that this issue is resolved, I am going to close this out. Please let us know if this is not the case and we can reopen the issue. Thanks
