### ISSUE TITLE
using lambda resolver and nested fields

### ISSUE THREAD

**Issue by amlcodes** [aws-amplify/amplify-js#7683]
trying to make an example schema for patreon - I have this main creator type. Everything is wired up and working except for monetizedPhoto access for "subscribed" (not to be confused with graphql subscriptions) users. I guess I would like the @auth directive and groupsField to resolve the connected type to the owner / user. instead of having to create a group for every "creator"? Are groups the only way to handle dynamic authorization? How does one build a multi tenant - premium content hosted schema like patreon?

```
type Creator
  @key(
    name: "byURL"
    fields: ["creatorURL"]
    queryField: "creatorsByCreatorURL"
  )
  @key(name: "byUser", fields: ["userID"], queryField: "creatorsByUserID")
  @model
  @auth(
    rules: [
      { allow: owner, ownerField: "owner", provider: userPools }
      { allow: groups, groups: ["Admin"] }
      { allow: private, provider: userPools, operations: [read] }
      { allow: public, provider: iam, operations: [read] }
    ]
  ) {
  id: ID!
  owner: String
  userID: ID!
  user: User @connection(fields: ["userID"])
  creatorURL: String!
  subscribers: [Sub]
    @connection(keyName: "SubscriptionByCreatorID", fields: ["id"])
  photos: [Photo] @connection(keyName: "byCreator", fields: ["id"])
  monetizedPhotos: [MonetizedPhoto]
    @connection(keyName: "byCreator", fields: ["id"])
    @auth(
      rules: [
        { allow: owner, ownerField: "owner", provider: userPools }
        { allow: groups, groups: ["Admin"] }
        { allow: groups, groupsField: "subscribers", operations: [read] }
      ]
    )
}
```

**Comment by iartemiev** [comment]
Hey @amlcodes, just so we're on the same page, are you building this with AppSync / the API category? Or with DataStore?

**Comment by amlcodes** [comment]
@iartemiev  API currently. going to have to dig deeper into DataStore and see how it' s different, truly don't understand, it seems like AppSync/API/DataStore modules get the same thing done in different ways.

**Comment by iartemiev** [comment]
Ok cool, the above schema won't work correctly with DataStore at the moment (multiple auth types are not yet supported), so I just wanted to make sure.

With the API category, I think what you're looking for is the array of owners auth rule. Check out the `editors` field/auth rule [here](https://docs.amplify.aws/cli/graphql-transformer/auth#multiple-authorization-rules). You can specify up to 1000 authorized users in the array and modify it dynamically.

**Comment by amlcodes** [comment]
@iartemiev Thanks! Where does the 1000 authorized user limit come from? Anyway around it? Should I move to RDS?

**Comment by iartemiev** [comment]
That's an AppSync limit, so the data source you're using will not affect it. 

See **Iterations in a foreach loop in mapping templates** here: https://docs.aws.amazon.com/general/latest/gr/appsync.html#limits_appsync

**Comment by amlcodes** [comment]
After going thru the docs, it looks like patreon couldn't be made with amplify / appsync without staying under 1000 subscribers per creators?

**Comment by iartemiev** [comment]
Not necessarily. The suggestion I gave above was specifically around using `owner` auth. Which requires the least amount of effort to use, but comes with some limitations. 

You could instead utilize the `{allow: private}` auth rule with Cognito and write custom authorization logic in your AppSync resolvers. I'd recommend checking out Pipeline Resolvers: https://aws.amazon.com/blogs/mobile/appsync-pipeline-resolvers-1/

**Comment by amlcodes** [comment]
@iartemiev thanks so much pointing me in the right direction to tie a solutions together. I have a question around pipeline resolvers or direct lambda resolvers. I should only need a @function directive on a custom query to create a lambda resolver, correct? 

For some reason, I am able to edit and return the top level string fields from lambda, like result.owner. But not any other fields like result.photos or result.photos.items. Every time, the result looks fine in lambda, but the result comes back unedited - except for the top level fields
