### ISSUE TITLE
updated amplify now getting "No api-key configured" when trying to log in with cognito

### ISSUE THREAD

**Issue by ShehryarKh** [aws-amplify/amplify-js#7693]
> **Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the
> [Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

updated amplify-vue-ui from ^0.2.29 to 0.2.31
updated "aws-amplify": "^3.3.10"to "^3.3.16"

Users are unable to login via 

```
login({ commit, state }, email, password) {
    Auth.signIn(email, password)
      .then(async(user) => {
        const cognitoUser = await API.graphql({ query: userbyCognitoId, authMode: "API_KEY", variables: { cognitoId: user.username }});
        var stateUser = cognitoUser['data']['userbyCognitoID']['items'][0]
        stateUser.cognitoId = user.username
        commit("SET_USER_LOGIN", { user: stateUser, cognitoId: user.username })
        
      })
      .catch((err) => {
        if (err.message.includes('User is not confirmed')) {
          commit("SET_UNCONFIRMED_USER");
        }
        else {
          alert(err.message)
        }
      });
```

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
4.40.1
**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

**Expected behavior**
to login as normal

**Desktop (please complete the following information):**

- OS: [e.g. Mac/Windows/Ubuntu]
- Node Version. You can use `node -v` to check the node version on your system
  v14.15.3

**Comment by amhinson** [comment]
@ShehryarKh Could you share your `aws-exports.js`?

**Comment by ShehryarKh** [comment]
@amhinson all the keys as well?

```
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:*",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_*",
    "aws_user_pools_web_client_id": "*",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "*.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-*",
    "aws_user_files_s3_bucket": "*-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;

```

**Comment by amhinson** [comment]
Thanks! I've got a few comments and questions as well as some general troubleshooting steps:
- I'm thinking that is related to API instead of Auth. If you remove the `API.graphql()` block of code, do you still see any errors?
- I see that the default auth type (`aws_appsync_authenticationType`) for the API is `AMAZON_COGNITO_USER_POOLS`. Did you also enable an additional auth type when you ran `amplify add api` or `amplify update api`?
- You mentioned `amplify-vue-ui` but did you mean `@aws-amplify/ui-vue`?
- Can you update to the latest version of `@aws-amplify/ui-vue` as well as `aws-amplify`? Be sure to remove the node modules and do a clean install, just to make sure there are no duplicate dependencies. This has been know to cause issues if multiple versions of Amplify packages are not in sync in a project.

**Comment by ShehryarKh** [comment]
@amhinson It is an API issue, not an Auth issue. 

Yes i have enabled additional auth type when i ran `amplify update api` where the default was Cognito and additional was api key expiring in 365 days.

yes i meant `@aws-amplify/ui-vue`

I have just updates those packages and it seemed to fix some of the issues. The last issue im running into is all images are returning `No credentials`

<img width="442" alt="Screen Shot 2021-02-06 at 8 49 41 AM" src="https://user-images.githubusercontent.com/12723403/107119886-68d2fa80-6858-11eb-9be4-36482ad2892c.png">

**Comment by ShehryarKh** [comment]
unfortunately.. im back to square one after running `npm install`   getting `No api-key configured`

**Comment by ShehryarKh** [comment]
Closing this, it's working right now, and I have the slightest idea. Will reopen if experiencing the issue again.

**Comment by charlesfayal** [comment]
Having the same issue with needing react dependencies for a NodeJS project

**Comment by c0deWookiee** [comment]
https://github.com/aws-amplify/amplify-js/issues/7934#issuecomment-810115625

resolved this issue for me
