### ISSUE TITLE
DataStore Authorization - combining owner and api_key based methods breaks sync

### ISSUE THREAD

**Issue by rraczae** [aws-amplify/amplify-js#7709]
**Describe the bug**
I have a datastore with Auth Mode: Cognito user pool. It works, but I need to add a new Table that is available to "guest users" who are not authenticated. I am able to run `amplify update api` and add the Api Key method and it shows up in the backend changes. However after pushing this and adding the new model `AppSettings` I keep getting a DataSync error:

`DataStore - subscriptionError, Connection failed: {"errors":[{"errorType":"Unauthorized","message":"Not Authorized to access onUpdateAppSettings on type Subscription"}]}`

**To Reproduce**

1. create a new amplify app 
2. add auth Cognito User Pool
3. create a model that has owner auth:
```
type MySettings
  @model
  @auth(rules: [{ allow: owner, operations: [read, create, update] }]) {
  id: ID!
  key: String
  value: String
}
```
4. push
5. run amplify update api, add additional auth for Api Key
6. push
7. add public model
```
type AppSettings
  @model
  @auth(rules: [{ allow: public, operations: [read], provider: apiKey }]) {
  id: ID!
  key: String!
  value: String!
}
```
8. push
9. generate models
10. run the app and observe the errors (logged in/out)

**Expected behavior**
Expect the datastore to sync properly. Load the public data when logged out, also load the owner based data when logged in,

**Code Snippet**
-

**Screenshots**
-

**What is Configured?**
`aws-exports` was auto generated and it has the proper api key

<details>
  <summary><strong>Environment</strong></summary>

```
System:
    OS: macOS 11.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 7.70 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.14.0 - ~/.nvm/versions/node/v14.14.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.14.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.14.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 88.1.19.86
    Chrome: 88.0.4324.150
    Firefox: 85.0
    Safari: 14.0.3
  npmPackages:
    @babel/core: ~7.12.10 => 7.12.10 
    @expo/browser-polyfill: ^0.1.0 => 0.1.0 
    @expo/vector-icons: ^12.0.2 => 12.0.2 
    @react-native-community/datetimepicker: 3.0.4 => 3.0.4 
    @react-native-community/masked-view: 0.1.10 => 0.1.10 
    @react-native-community/netinfo: 5.9.7 => 5.9.7 
    @react-navigation/bottom-tabs: ^5.11.2 => 5.11.2 
    @react-navigation/native: ^5.8.10 => 5.8.10 
    @react-navigation/stack: ^5.12.8 => 5.12.8 
    @types/base64-js: ^1.3.0 => 1.3.0 
    @types/react: ^17.0.0 => 17.0.0 
    @types/react-native: ~0.63.40 => 0.63.40 
    @types/react-redux: ^7.1.15 => 7.1.15 
    @typescript-eslint/eslint-plugin: ^4.10.0 => 4.10.0 
    @typescript-eslint/parser: ^4.10.0 => 4.10.0 
    appcenter: 4.0.0 => 4.0.0 
    appcenter-analytics: 4.0.0 => 4.0.0 
    appcenter-crashes: 4.0.0 => 4.0.0 
    aws-amplify: ^3.3.14 => 3.3.14 
    aws-amplify-react-native: ^4.3.0 => 4.3.0 
    babel-plugin-module-resolver: ^4.1.0 => 4.1.0 
    eslint: ^7.15.0 => 7.15.0 
    eslint-config-prettier: ^7.0.0 => 7.0.0 
    eslint-config-react: ^1.1.7 => 1.1.7 
    eslint-config-universe: ^6.0.1 => 6.0.1 
    eslint-plugin-jest: ^24.1.3 => 24.1.3 
    eslint-plugin-jsx-a11y: ^6.4.1 => 6.4.1 
    eslint-plugin-prettier: ^3.3.0 => 3.3.0 
    eslint-plugin-react: ^7.21.5 => 7.21.5 
    eslint-plugin-react-hooks: ^4.2.0 => 4.2.0 
    eslint-plugin-react-native: ^3.10.0 => 3.10.0 
    expo: ~40.0.0 => 40.0.0 
    expo-asset: ~8.2.1 => 8.2.1 
    expo-asset-utils: ^1.2.0 => 1.2.0 
    expo-constants: ~9.3.5 => 9.3.5 
    expo-font: ~8.4.0 => 8.4.0 
    expo-gl: ~9.2.0 => 9.2.0 
    expo-linear-gradient: ~8.4.0 => 8.4.0 
    expo-linking: ^2.0.0 => 2.0.0 
    expo-pixi: ^1.2.0 => 1.2.0 
    expo-print: ~9.2.0 => 9.2.0 
    expo-screen-orientation: ~2.1.0 => 2.1.0 
    expo-sharing: ~8.5.0 => 8.5.0 
    expo-splash-screen: ~0.8.1 => 0.8.1 
    expo-status-bar: ~1.0.3 => 1.0.3 
    expo-web-browser: ~8.6.0 => 8.6.0 
    husky: ^5.0.6 => 5.0.6 
    jest-expo: ~40.0.1 => 40.0.1 
    prettier: ^2.2.1 => 2.2.1 
    react: 17.0.1 => 17.0.1 
    react-dom: 17.0.1 => 17.0.1 
    react-hook-form: ^6.13.1 => 6.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
    react-native-gesture-handler: ~1.9.0 => 1.9.0 
    react-native-image-pan-zoom: ^2.1.12 => 2.1.12 
    react-native-modal: ^11.6.1 => 11.6.1 
    react-native-safe-area-context: 3.1.9 => 3.1.9 
    react-native-screens: ~2.16.1 => 2.16.1 
    react-native-svg: 12.1.0 => 12.1.0 
    react-native-web: ~0.14.9 => 0.14.9 
    react-redux: ^7.2.2 => 7.2.2 
    redux: ^4.0.5 => 4.0.5 
    typescript: ~4.1.3 => 4.1.3 
  npmGlobalPackages:
    @aws-amplify/cli: 4.41.2
    expo-cli: 4.1.6
    npm-check-updates: 10.2.5
    npm: 6.14.8
    yarn: 1.22.10
```

</details>

**Smartphone (please complete the following information):**

- Device: any ios
- OS: ios 14
- Browser -
- Version -

**Comment by amhinson** [comment]
@rraczae DataStore currently only supports using the default authorization type for the API, which in your case is Cognito User Pools. However, we are actively working on the ability to support multiple authorization types in the future. I'm labelling this a feature request to be sure to update the ticket when the feature is ready.

**Comment by rraczae** [comment]
Hey @amhinson thanks for the quick response. Could you recommend any temporary workaround to achieve this until it's ready? My goal is simple: not to rely on app updates for common settings of the app (like about us). I mean I could always write a custom endpoint to load these if there is no other way.

Thank you!

Rob

**Comment by amhinson** [comment]
Even though DataStore might not working for your use case at the moment, you can still use the [API category](https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/js) for your AppSync API. You'll just need to make the requests yourself and persist the data locally, if necessary.

**Comment by rraczae** [comment]
Gotcha. Yea I need to support offline scenarios so DataStore is a must for logged in users. I guess it's possible to add a second API independent of datastore and put the settings in there. It just sucks that it will be outside my amplify app.

**Comment by rraczae** [comment]
So what I ended up doing is creating a separate GraphQL app, however now I am having trouble with CI/CD as it cannot be done with just checkout & push. Any hints/workarounds on that front until this feature arrives?

**Comment by amhinson** [comment]
I am not sure on that front, but it might be helpful to get some advice from the [CLI repo](https://github.com/aws-amplify/amplify-cli), as that is more in their domain.

**Comment by iartemiev** [comment]
We released multiple authorization type support for DataStore in aws-amplify@3.4.0.

Please see this section of the docs on how to configure it: https://docs.amplify.aws/lib/datastore/setup-auth-rules/q/platform/js#configure-multiple-authorization-types
