### ISSUE TITLE
Angular package - federated identity

### ISSUE THREAD

**Issue by haverchuck** [aws-amplify/amplify-js#771]
Do you want to request a feature or report a bug?
Feature Request

What is the current behavior?
Aws-amplify-angular does not include federated identity functionality in its auth component.

What is the expected behavior?
Aws-amplify-angular provides federated identity functionality.

**Comment by CarlosV89** [comment]
+1

**Comment by temesxgn** [comment]
Any update on this?

**Comment by andrewryan1906** [comment]
+1... so I'm assuming that if I'm using Amplify and Angular, there's NO way to do Google sign in without the hosted UI... is that correct?

**Comment by ashika01** [comment]
Closing this Feature request as we now have federation available in [new UI component](https://github.com/aws-amplify/amplify-js/tree/master/packages/amplify-ui-components#amplify-authenticator-federated). 

If there is any suggestion or issue with federation, please feel free to open up new issue or feature request.
