### ISSUE TITLE
Config option for Amplify Storage Exact Path/Key

### ISSUE THREAD

**Issue by Ochaun** [aws-amplify/amplify-js#7715]
**Is your feature request related to a problem? Please describe.**
I would like to be able to upload the exact key of an object into S3 using the client side API without the user UUID prepended on it. In other words, I would like to do S3 operations without the `user_identity_id` prefix. 

**Describe the solution you'd like**
A configuration option called **exactKey** or **exact**. This would be a boolean option to tell the **AWSS3Provider** not to add the user UUID and/or region prefix to the key for the S3 object being uploaded, downloaded, updated, deleted or listed. So that the following code 

```js
 Storage.put(fileName, fileContents, {
      exact: true,
      contentType: 'image/jpeg',
      customPrefix: {
        private: 'someDir/'
      }
    })
      .then((res) => {
        alert("all done here!");
      })
      .catch((err) => {
        console.error(err);
      });
```
Would upload an object with **someDir/fileName.jpeg** as a key to S3. Instead of **someDir/us-east-1:c7c464af-bca0-4e00-a2f4-8c99caeb3e8b/fileName.jpeg**.

**Describe alternatives you've considered**
There aren't alternatives through Amplify. The other alternatives I'm aware of is using the S3 SDK and manually hooking up authentication to cognito Auth roles. Then automating it through cloudformation. Amplify does an excellent job with provisioning file level user permissions using cognito. I'd rather use that than a manual configuration 

**Additional context**
I'm actively working on a PR for this. This is the original discussion question and documentation. 
https://github.com/aws-amplify/amplify-js/discussions/7708
https://docs.amplify.aws/lib/storage/configureaccess/q/platform/js

**Comment by undefobj** [comment]
@Ochaun can you give more information on this use case? Is there a reason why you cannot upload the data to Public access level in the bucket which will join all the keys to the same directory? Note this doesn't make your bucket Public, it just is a location where all users in your app can upload data. Knowing the business use case in your application will allow us to look at this in the future and determine if the proposed design in your PR is correct or if we need to look at other workflows and DX. Thanks.

**Comment by Ochaun** [comment]
@undefobj Setting it to public access helped. I was paranoid since I'm dealing with confidential files.
