### ISSUE TITLE
amazon-cognito-identity-js doesnt support token validation

### ISSUE THREAD

**Issue by cnikolov** [aws-amplify/amplify-js#7720]
**Describe the bug**
I am hoping that I am not a trouble, I looked in the docs for amazon-cognito-identity-js
I have simple express app that handles register/confirm/login/etc... however I have missing piece.

I can't validate the token unless i try to refresh the session.

**Expected behavior**
Login --> Get token --> Hit secret API endpoint --> get the jwt from cookie or whatever..  
FAIL use identity-js to validate the token and obtain the user.
**Code Snippet**
Please provide a code snippet or a link to sample code of the issue you are experiencing to help us reproduce the issue. (Be sure to remove any sensitive data)

The AuthenticationDetails can only be user and password.
so the only option i have left with is to use empty cognitoUser and call refreshSession with my token

Any idea how to efficiently validate token and obtain cognitoUser?
**Screenshots**

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.
* Which resources do you have configured?
  * If applicable, please provide your `aws-exports` file:
   ```
   const awsmobile = {
       "aws_project_region": "us-east-1",
       "aws_cognito_identity_pool_id": "us-east-1:xxx-xxxx-xxxx-xxxx-xxxxxxxx",
       "aws_cognito_region": "us-east-1",
       "aws_user_pools_id": "us-east-1_xxx",
       "aws_user_pools_web_client_id": "xxxx",
       "oauth": {}
   };
   ```
   * If applicable, please provide your manual configuration example:
   ```
   {
    Auth: {
        identityPoolId: 'XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab',
        region: 'XX-XXXX-X',
        identityPoolRegion: 'XX-XXXX-X',
        userPoolId: 'XX-XXXX-X_abcd1234',
        userPoolWebClientId: 'a1b2c3d4e5f6g7h8i9j0k1l2m3',
        mandatorySignIn: false,
        authenticationFlowType: 'USER_PASSWORD_AUTH',
        oauth: {
            domain: 'your_cognito_domain',
            scope: ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
            redirectSignIn: 'http://localhost:3000/',
            redirectSignOut: 'http://localhost:3000/',
            responseType: 'code' // or 'token', note that REFRESH token will only be generated when the responseType is code
           }
       }
   }
   ```
* If applicable, provide more configuration data, for example for Amazon Cognito, run `aws cognito-idp describe-user-pool --user-pool-id us-west-2_xxxxxx` (Be sure to remove any sensitive data)
 

<details>
  <summary><strong>Environment</strong></summary>

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

</details>

**Smartphone (please complete the following information):**

**Additional context**

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by sammartinez** [comment]
Hey @cnikolov, Can you let us know what your use case is here. I see that you have mixed part of your question with the issue template so wanted to understand what you are looking to do. Are you using a node application for the `amazon-cognito-identity-js` package? Can you provide your `package.json` along with your environment settings? 

Please use the follow command: 
```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

Thanks ahead of time!

**Comment by cnikolov** [comment]
https://github.com/cnikolov/aws-cognito-http <https://github.com/cnikolov/aws-cognito-http>
I have a repository here and I am struggling to validate the upcoming tokens

Sent from my iPhone

On 19 May 2021, at 22:05, Sam Martinez ***@***.***> wrote:

﻿

Hey @cnikolov<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcnikolov&data=04%7C01%7C%7C9230bdeea024490252ab08d91b09cb00%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637570551130128688%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fo5HCZwETMZy6%2F4uBJiq%2F2RZCO5dgdd5Yle8uMfJ9FQ%3D&reserved=0>, Can you let us know what your use case is here. I see that you have mixed part of your question with the issue template so wanted to understand what you are looking to do. Are you using a node application for the amazon-cognito-identity-js package? Can you provide your package.json along with your environment settings?

Please use the follow command:

npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages


Thanks ahead of time!

**Comment by evcodes** [comment]
Hey @cnikolov, I will be taking a look at this today and let you know if I have any updates or questions.

**Comment by evcodes** [comment]
I cloned your repo and I tried to reproduce but for some reason I do not have a location where I can put my client secret so I am not able to a register a new user.

```{
    "error": {
        "code": "NotAuthorizedException",
        "name": "NotAuthorizedException",
        "message": "Unable to verify secret hash for client xxxxxxxxxxxxxxxxxxx"
    }
}
```

**Comment by cnikolov** [comment]
@evcodes just create in the top directory  file with name ".env"

With this content
```

USER_POOL_ID=YOUR POOLID
CLIENT_ID=YOURCLIENTID
HOST_URL=localhost
PORT=3001
CLIENT_DOMAIN=localhost
```

**Comment by tannerabread** [comment]
hi @cnikolov :wave:
Amplify was never intended to validate JWTs. It is a client-side library and is not fully functional in a node/express environment.

There are other ways to validate the tokens, if you need more information refer to [these docs](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html).
