### ISSUE TITLE
"No Current User" from AppSync API and Auth in General

### ISSUE THREAD

**Issue by chantlong** [aws-amplify/amplify-js#7729]
**Describe the bug**

I am getting "No Current User" as an error message when users make AppSync GraphQL API Calls of a React Native app.
This is only happening to like 1-2% of my users.

I am not sure if this is a bug or spec. 

I would like to know when "No Current User" is returned as an error from AppSync. I understand it returns that if it cannot determine if the user is logged in.

This is happening on:
- iOS 14.4
- Amplify Version: 4.41.2
- AMAZON COGNITO_USER_POOLS as Auth Mode for AppSync

According to the docs, a Cognito User Token lasts 30 days.
https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html

Some of the users are getting logged out in a few days though.

What I am doing to check if user is logged in or not is this function below If this function is returns nothing/errors out, I set the user to unauthenticated.

```
try {
    const userData = await Auth.currentAuthenticatedUser()
    if (userData.username) {
      return userData.username
    }
    return userData.attributes.sub
  } catch (err) {
    console.warn(ERROR_MSG.AUTH_GET_USERNAME, err)
  }
```

Is it possible that `Auth.currentAuthenticatedUser` wouldn't work when the user is offline for a split second or something?

**Comment by amhinson** [comment]
The way you are checking for the user seems correct, as `Auth.currentAuthenticatedUser` should still return a user while they are offline if they have previously authenticated while online. 

However, this seems like a difficult issue to debug right now, unfortunately. Would you be able to provide some steps so we can attempt to see the same behavior?

Another helpful thing would be to enable Amplify logging with `Amplify.Logger.LOG_LEVEL = 'DEBUG';`. If you could post that as well, that'd be great!

**Comment by chantlong** [comment]
I haven't been able to reenact this problem as the "No Current User" is coming from my Sentry events. If I ever get it, I'll paste it.

What I notice from a `Auth.signIn` is that I get back this payload from the response for the jwtToken and accessToken

```
        "auth_time": 1613353950,
        "exp": 1613374217,
        "iat": 1613370617,
```

which equates to

`auth_time` is Mon Feb 15 2021 10:52:30 GMT+0900 (Japan Standard Time)
`exp` is Mon Feb 15 2021 16:30:17 GMT+0900 (Japan Standard Time)

It looks to me as if the Cognito access token only lasts 5-6 hours so **how is it getting refreshed?**

When calling an AppSync API, my understanding is that it verifies the token, but does not refresh it.

I was told `Auth.currentAuthenticatedUser` will help refresh the token on React Native. The only time I call this method is during login or when there is a Network Error. So is it best practice to call this method when an app is woken from a minimized state?

**Comment by amhinson** [comment]
How are you calling the AppSync API? Could you post a code snippet along with your `schema.graphql`? When using `API.graphql` from Amplify, it should still refresh the token if necessary.

**Comment by chantlong** [comment]
According to the docs https://docs.amplify.aws/lib/auth/advanced/q/platform/js#token-refresh
React Native cannot refresh token automatically, but you are saying an API GraphQL call will refresh the token if it fails? 

It is just your average API call.
```
type Profile
  @model
  @searchable
  @auth(
    rules: [
      {
        allow: owner
        ownerField: "uid"
        operations: [create, update, read, delete]
      }
      { allow: groups, groups: ["admin"] }
    ]
  )
   {
  id: ID!
  uid: String
   }

```
with 

```
import { API } from '@aws-amplify/api'
import { graphqlOperation } from '@aws-amplify/api-graphql'

const response = (await API.graphql(
  graphqlOperation(fetchProfile, {
    uid,
    sortDirection: ModelSortDirection.DESC,
    limit: 20,
    filter: filter,
    
  }
))
```

**Comment by chantlong** [comment]
Downgrading back Auth module to "@aws-amplify/auth": "3.4.6" fixed the issue.

**Comment by amhinson** [comment]
> According to the docs https://docs.amplify.aws/lib/auth/advanced/q/platform/js#token-refresh
> React Native cannot refresh token automatically, but you are saying an API GraphQL call will refresh the token if it fails?

This section of the docs is only referring to Identity Pool federation with 3rd party providers like Google and Facebook, which is different than the default User Pool authentication that Amplify `Auth` uses.

But yes, the Cognito token should get refreshed automatically without you needing to do anything yourself.

**Comment by chantlong** [comment]
@amhinson 
So I tried getting the log for `Auth.currentAuthenticatedUser()` when it fails and it gave me back the following.
I think this confirms that this method can fail when offline.

```
 {"code":"NetworkError","name":"Error","message":"Network error"}
```
