### ISSUE TITLE
UniversalStorage custom config

### ISSUE THREAD

**Issue by usualdesigner** [aws-amplify/amplify-js#7730]
There's no ability to configure cookies while using UniversalStorage. I'd like to have the ability to customize `sameSite` cookie option.

Would be ideal to configure this in Auth scoped configuration as we have this for `cookieStorage`;

**Comment by cwomack** [comment]
@usualdesigner Apologies that we didn't get you a response sooner on this, but if this is still needed we'd like to hear more. Can you provide a little more context on what the implementation and use case would be for this feature request?

**Comment by cwomack** [comment]
May be related to #6884

**Comment by cwomack** [comment]
@usualdesigner, this may be currently possible as seen [here](https://docs.amplify.aws/lib/client-configuration/configuring-amplify-categories/q/platform/js/#top-level-configuration:~:text=sameSite%3A%20%27strict%27%20%7C%20%27lax%27%2C) in the docs depending on your use case.  Can you verify if that is sufficient for what you're looking for?

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. Please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
