### ISSUE TITLE
Cognito - oauth/authorise - Found 2 elements with non-unique id #cognito-asf-data

### ISSUE THREAD

**Issue by tarundhillon** [aws-amplify/amplify-js#774]
Do you want to request a feature or report a bug? Bug

The login page throws error on chrome ( an possibly other browsers) due to elements with duplicate #ids
> [DOM] Found 2 elements with non-unique id #cognito-asf-data: (More info: https://goo.gl/9p2vKq) 

What is the current behavior?
Console error are thrown in the browser

What is the expected behavior?
The form shouldn't be using duplicate IDs and there not be no errors in the console. 

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

NA

**Comment by elorzafe** [comment]
Hi @tarundhillon are you just using amazon-cognito-identity-js or aws-amplify?

**Comment by tarundhillon** [comment]
Hi - I am using amazon-cognito-identity-js only.

**Comment by real1988** [comment]
I also have a question of consent,How can do?

**Comment by real1988** [comment]
I have the same problem.  How can I do???

**Comment by real1988** [comment]
who is here?please hlep me !!!thank you very much!!!

**Comment by yuntuowang** [comment]
I am not entirely sure about this issue. But can you migrate to use aws-amplify? The old repo has not been maintained and updated for a while.

**Comment by real1988** [comment]
Who can give me an Amazon Cognito  demo about login/logout???
I'm a novice, and I'm learning to use it.
My E-mail:3563997480@qq.com.
Thank you very much!!!

**Comment by svstartuplab** [comment]
I used the console to setup an app client for a user pool and I used the default domain name.  The Cognito login page loads with non-unique id errors for #cognito-asf-data, #password, #username.  I don't see how I have control of that in the Cognito console.

**Comment by cwardcode** [comment]
Yeah, this is a problem with Cognito's hosted sign-in page, not amplify. Is there any way to +1 a feature request so that the Cognito team can take care of it?

**Comment by powerful23** [comment]
Closing this issue as this is an issue related to the Cognito service. Please your feedback to the Cognito service team via AWS Forum: https://aws.amazon.com/premiumsupport/knowledge-center/send-feedback-aws/
