### ISSUE TITLE
User attribute validation incorrect

### ISSUE THREAD

**Issue by lifedup** [aws-amplify/amplify-js#7745]
**Describe the bug**

When a Cognito user pool has user defined required attributes - the signup allows empty strings to validate.

**To Reproduce**

Create a user pool with extra required attributes and send empty string for required values.

```
import { Auth } from 'aws-amplify';

Auth.signUp({
 username: 'test@a',
 password:'123456aA!',
 attributes: {
  family_name: 'last',
  given_name: ''
 }
});
```

**Expected behavior**
Throw InvalidParameterException

**Screenshots**
Pool settings
![image](https://user-images.githubusercontent.com/2423551/107870711-c541a580-6e68-11eb-953b-d55ceb24b5fd.png)

**Comment by sammartinez** [comment]
Thanks for this feedback @lifedup. I wanted to get a little more clarity on your use case. Are you wanting us to support this from the API level or from the UI Components level? Please let us know.

**Comment by lifedup** [comment]
We are using our UI and have client-side validation in place. However, trying to figure out all of the errors Cognito returns, we discovered that empty strings pass the server-side required validation set in the user pool.

We believe that it shouldn't pass the server validation and assumed it was a bug.

**Comment by lifedup** [comment]
> Thanks for this feedback @lifedup. I wanted to get a little more clarity on your use case. Are you wanting us to support this from the API level or from the UI Components level? Please let us know.

We are using our UI and have client-side validation in place. However, trying to figure out all of the errors Cognito returns, we discovered that empty strings pass the server-side required validation set in the user pool.

We believe that an empty string shouldn't pass the server validation and assumed it was a bug.

**Comment by lifedup** [comment]
My users are confired and the session and user were returning not logged in even though the user's data was set in cookies (or localstorage depending on the config)

I figured out what is happening however I do not know how to fix it with out using both aws-amplify and @aws-amplify/auth libraries together.  I think there are some interdependencies that are not being captured in some of the libraries.  This works with cookies and localstorage

NOTES: 
- I'm using next js so this will cover SSR and client side fixes
- Users Need to be confirmed before they can be logged in

**congnito-config.ts**

I use env vars - I converted and added notes to show localhost settings

```
const amplifyConfig = {
  region: 'us-east-1',
  userPoolId: process.env.NEXT_PUBLIC_COGNITO_POOL_ID,
  userPoolWebClientId: process.env.NEXT_PUBLIC_COGNITO_CLIENT_ID,
  mandatorySignIn: false,
  authenticationFlowType: 'USER_SRP_AUTH',
  cookieStorage: { // can remove to use localstorage
    domain: "localhost", // dont add port
    secure: process.env.NODE_ENV !== 'development',// make sure is boolean
    path: "/",
    expires: Number(".5"), //env vars are strings - convert to a number
    sameSite: "lax", //set to lax bc using multiple sub domains
  },
};

export default amplifyConfig;
```

**_app.tsx** (main app entry point for client side

```
import React from 'react';
import Auth from '@aws-amplify/auth';// you do not need to import core
import amplifyConfig from 'lib/cognito-config';

const App = () => {
  Auth.configure(amplifyConfig);
  return (<div>My app</div>);
};

export default App;
```
**_NOTES: for client side it does not matter what library you import it will work with the following -_**

```
import Auth from '@aws-amplify/auth';
Auth.configure(amplifyConfig)

OR
import { Auth } from '@aws-amplify/auth';
Auth.configure(amplifyConfig)

OR
import Amplify from '@aws-amplify/core';
Amplify.configure({Auth: amplifyConfig})

OR
import { Auth } from '@aws-amplify/core';
Auth.configure(amplifyConfig)

OR
import Amplify from 'aws-amplify'; (this library is really slow client side I wouldn't use it)
Amplify.configure({Auth: amplifyConfig})
```

SERVER SIDE

Note: 

- The ssr flag in the cognito config does not make a difference if it's true or false
- On the server the ONLY import that works is aws-amplify - none of the others listed above work in any combination.
- You have to import the config in every server render function

index.tsx (can be any page)

```
import React from 'react';
import { withSSRContext } from 'aws-amplify';
import AmplifyAuth, { CognitoUser } from '@aws-amplify/auth';
import { GetServerSideProps } from 'next';
import Amplify from 'aws-amplify'; // the only lib that will return a signed in user on the server
import amplifyConfig from 'lib/cognito-config';

type User = {
  user: CognitoUser;
  session: any;
};

const Index = (props: User): JSX.Element => {
  //logs in browser
  console.log('SSR Props - logs in browser', props);

  React.useEffect(() => {
    // this uses main entry config in _app.tsx
    // logs in browser
    const getUser = async () => {
      const user = await AmplifyAuth.currentAuthenticatedUser();
      console.log(user);
      const session = await AmplifyAuth.currentSession();
      console.log(session);
    };
    getUser();
  });

  return <div>Some Page</div>;
};

// next js server side props option
export const getServerSideProps: GetServerSideProps = async (context) => {
  Amplify.configure({ Auth: amplifyConfig });//the only config that will return a user after signin
  //logs in terminal
  try {
    const { Auth, API } = withSSRContext(context);
    const user = await Auth.currentAuthenticatedUser();
    const session = await Auth.userSession(user);
    console.log('\n\n\n*************API**************\n\n\n');
    console.log(API);
    console.log('\n\n\n*************USER**************\n\n\n');
    console.log(user);
    console.log('\n\n\n*************SESSION**************\n\n\n');
    console.log(session);
    return {
      props: { user: JSON.stringify(user), session: JSON.stringify(session) },
    };
  } catch (e) {
    console.log(e);
    return { props: { user: null, session: null } };
  }
};

export default Index;
```

**Comment by sammartinez** [comment]
Hey @lifedup, apologizes on the delay, this seems to be related to Amazon Cognito specifically instead of Amplify JavaScript. Amplify JavaScript acts as a proxy to Amazon Cognito. We suggest you open an issue via the [AWS Forums for Cognito](https://forums.aws.amazon.com/forum.jspa?forumID=173).

Thanks,
Amplify team
