### ISSUE TITLE
XCode 12 Build - amazon-cognito-identity-js

### ISSUE THREAD

**Issue by johnny-minty** [aws-amplify/amplify-js#7747]
**Problem Description:** 

amazon-cognito-identity-js pod spec lists 'React' instead of 'React-Core' which breaks when building under XCode 12. 

**Version affected:** 
4.5.10

**See below - commentary and discussion from the react-native GITHUB:** 

https://github.com/facebook/react-native/issues/29633#issuecomment-694187116

**Example pull request from a like project:** 

https://github.com/react-native-masked-view/masked-view/commit/f218a831525fac8399ab58f19edb5fd154d9e481

**Comment by amhinson** [comment]
I've been working with RN projects that have `amazon-cognito-identity-js` as a dependency in Xcode 12, but I haven't come across an error before. Do you happen to have some reproduction steps?

**Comment by johnny-minty** [comment]
@amhinson Thanks for the quick response. I will review this today and get back to you with reproduction steps. The problem tends to arise only when using 'use_frameworks' in the Pod file.

**Comment by johnny-minty** [comment]
@amhinson I've confirmed this only occurs when building with 'use_frameworks!' in the PodFile using XCode12.

Removing it or updating the podspec for the Cognito project to depend on 'React-Core' will resolve the issue.

**Steps to reproduce:** 

1. react-native init amptest
2. Add the following dependencies to **package.json** and run 'npm install'

    "@aws-amplify/api": "3.2.21",
    "@aws-amplify/auth": "3.4.21",
    "@aws-amplify/core": "3.8.13",
    "amazon-cognito-identity-js": "4.5.10",

3. Open the POD file add 'use_frameworks!' to the top of the file

![image](https://user-images.githubusercontent.com/6396138/109406566-fb416680-79de-11eb-9a8d-9c8e880cfca5.png)

5. Run pod install in the IOS directory
6. Build from XCode - error occurs: 

![image](https://user-images.githubusercontent.com/6396138/109406552-d9e07a80-79de-11eb-8fa8-1f48de22f42a.png)

**Comment by amhinson** [comment]
Thanks for looking further into that @johnny-minty 🙏  We're got a PR to address this, and should be able to get it into the next release after it is approved.

**Comment by johnny-minty** [comment]
Cheers @amhinson - thanks for the quick response!

**Comment by amhinson** [comment]
Closing this issue, as the related PR has been merged. We will likely have a new release out later this week or early next week 👍
