### ISSUE TITLE
Support Content-Encoding header on Storage.put

### ISSUE THREAD

**Issue by wesww** [aws-amplify/amplify-js#7750]
**Is your feature request related to a problem? Please describe.**
I have an application that allows uploading of large, repetitive data sets. The browser can gzip the file in a web worker thread to massively shrink the upload size, but Storage doesn't respect the content encoding header as an option.

**Describe the solution you'd like**
Add content encoding as an optional header on put.

**Describe alternatives you've considered**
I could deploy an API for the sole purpose of add this header on such files, but that would be a ridiculous amount of extra overhead for something so simple.

**Comment by wesww** [comment]
for the time being can use a workaround mixing amplify with the underlying `@aws-sdk/client-s3` lib:
https://github.com/aws-amplify/amplify-js/pull/7751#issuecomment-779421244

**Comment by jamesaucode** [comment]
#7751 should fix this, closing this now.
