### ISSUE TITLE
DataStore does not expose errors on initial sync

### ISSUE THREAD

**Issue by KyleBrost** [aws-amplify/amplify-js#7752]
**Is your feature request related to a problem? Please describe.**

When the DataStore does it's initial sync and there is an error on converting the data into Models there are silent errors raised.  If you enable Amplify.Logger.LOG_LEVEL = 'DEBUG', you can see them on the console.  Unfortunately there is no way to programmatically receive these errors and handle things gracefully.

**Describe the solution you'd like**
It would be great to have a listener function that could receive these errors so we could:
1) Respond to the user with informative text
2) Gracefully allow us to "ignore" the message and discard the offending records

**Describe alternatives you've considered**
The only option is to ensure the data model has no errors, which is ideal but then again we don't plan bad data.  If we get bad data, it's a hard stop for the application as the DataStore does not fire the "ready" event.

**Additional context**
To reproduce:

1) Create a simple model with no relationships, just an ID and a couple optional string fields
2) Load some data
3) Create an app that displays the data in a console after the DataStore has fired ready
4) Change the data model to have another field "thisIsRequired: String!"
5) Rebuild the app with the new model and try to fire it up

If you watch the network tab you will see the graphql query for the object failing because thisIsRequired cannot be null.

**Comment by amhinson** [comment]
Have you considered using the `errorHandler` in the configuration object? This should notify you when these sync errors happen: https://docs.amplify.aws/lib/datastore/conflict/q/platform/js#custom-configuration

**Comment by KyleBrost** [comment]
> Have you considered using the `errorHandler` in the configuration object? This should notify you when these sync errors happen: https://docs.amplify.aws/lib/datastore/conflict/q/platform/js#custom-configuration

The `errorHandler` does not fire on the initial sync.

**Comment by amhinson** [comment]
Ah interesting! I'd expect those errors to bubble up there. We can look into this 👍

**Comment by rraczae** [comment]
Hey team! Would it also be possible to add an event when a local migration is about to happen? That would be really super helpful in terms of migrating data especially for mobile apps. 

I realize that the challenge here is we have to be aware of the last version the app was running, but at least we could create a local backup of the current data as json and re-sync manually for the time being.

Users working offline then the app updating in the background is a pretty common scenario.

Btw, appreciate the quick and thorough feedback on issues, it is really a great experience to work with the framework like this.

Rob

**Comment by amhinson** [comment]
Hey @rraczae 👋  Would you be able to open up a new feature request for this? That will help our team better understand prioritization for any future improvements.

**Comment by rraczae** [comment]
@rraczae I think there is already a feature request for this actually: https://github.com/aws-amplify/amplify-js/issues/7413
I added my comment here because migration came up as part of this convo on discord. Let me know if you'd still like a separate feature request. Cheers! Rob

**Comment by mtakac** [comment]
I ran into the same issue. It took me quite a while to realise what was wrong. Basically I had data in wrong format in my Dynamo DB and I never received the initial sync READY event. I have configured an error handler, but it didn't receive any errors.

**Comment by dpilch** [comment]
This should be fixed by https://github.com/aws-amplify/amplify-js/pull/9861. Please comment if you are still experiencing the issue.
