### ISSUE TITLE
Unable to resolve module `../asyncstorage` from `node_modules/@aws-amplify/datastore/lib-esm/storage/adapter/getDefaultAdapter/index.native.js`: 

### ISSUE THREAD

**Issue by InheritxSolution** [aws-amplify/amplify-js#7761]
"amazon-cognito-identity-js": "^4.5.10"
"aws-amplify": "^3.3.19"
"aws-amplify-react-native": "^4.3.1"
"react-native": "0.61.4"

**Comment by amhinson** [comment]
Did you just upgrade to these versions recently? Could you try deleting your `node_modules` and any lock files and reinstalling? Let me know if that changes anything 👍

**Comment by InheritxSolution** [comment]
> Did you just upgrade to these versions recently? Could you try deleting your `node_modules` and any lock files and reinstalling? Let me know if that changes anything 👍

Working now.

**Comment by amhinson** [comment]
Could you open up a new issue with this info? It'd also be great to have the the `aws-exports.js` file 👍
