### ISSUE TITLE
React Native Auth SignIn: Double Clicking SignIn crashes with Error: Pending sign-in attempt already in progress

### ISSUE THREAD

**Issue by rraczae** [aws-amplify/amplify-js#7763]
**Describe the bug**
In the react native Auth library the SignIn component does not have a pending state and the `Sign In` button can be tapped again before the request completes. This leads to an exception that crashes the app.

https://github.com/aws-amplify/amplify-js/blob/3e423d017a98362a0117e1218dc3fa55abbff609/packages/aws-amplify-react-native/src/Auth/SignIn.tsx#L103

**To Reproduce**
Wrap your app with the `useAuthenticator` or drop the `<Authenticator />` component anywhere and double click sign in after filling out fields with anything.

**Expected behavior**
Sign In button is disabled (and loading indicator is displayed)

**Code Snippet**
-

**Screenshots**
![image](https://user-images.githubusercontent.com/73604600/108251142-aec37480-711c-11eb-8eef-391702db2511.png)

**Comment by Sandeepbadri** [comment]
On the first click of button I get no response. So I click on it again hoping  to some response but I get the same error.

**Comment by leowz** [comment]
Same issue here. If I am not logged in already, it's pending sign-in. If I was logged in before, then the screen just show a 
"loading..." text and an empty screen. Some body from Amplify team could help on this issue?

**Comment by cleett** [comment]
+1

**Comment by austindvo** [comment]
+1

**Comment by SeanRenet** [comment]
Has anyone figure this out yet?

**Comment by meehawk** [comment]
From the looks of it, it seems that it is not communicated to the user that the sign in request has already been made via a UI. This leads to user tapping the button again and hence the error. Would something like disabling the button while the sign in is in progress help or appear as a potential solution?  First time contributor here

**Comment by pablo-lopez-domowicz** [comment]
+1

**Comment by danieloi** [comment]
+1

**Comment by danieloi** [comment]
My issue was with a dependency. This solved it:
https://github.com/aws-amplify/amplify-js/issues/7191#issuecomment-728234443

**Comment by BeifeiZhou** [comment]
same issue here.

**Comment by bcs-gbl** [comment]
+1

**Comment by PFStein** [comment]
+1

**Comment by chrisbonifacio** [comment]
If you're experiencing this issue, please try the steps mentioned here https://github.com/aws-amplify/amplify-js/issues/7191#issuecomment-728238337

Please let me know if this works for you.

**Comment by rraczae** [comment]
@chrisbonifacio this issue will only happen in react native and not in the browser. Chrome will just swallow the exception. Since there was no movement here I decided to do an ugly hack which I would not recommend to anyone but basically looks like this:

```tsx
import { Auth } from 'aws-amplify';
import { SignIn } from 'aws-amplify-react-native';

// this is almost the exact copy override of the original sign in
// except it prevents a crash caused by double tapping the button...
// https://github.com/aws-amplify/amplify-js/issues/7763

class SignInOverride extends SignIn {
  _isLoading = false;
  _onLoadingCb?: (isLoading: boolean) => void;

  constructor(props: any) {
    super(props);

    this._onLoadingCb = props._onLoadingCb;
    this.setLoading = this.setLoading.bind(this);
  }

  setLoading(isLoading: boolean) {
    this._isLoading = isLoading;
    this._onLoadingCb?.(isLoading);
  }

  signIn() {
    const username = this.getUsernameFromInput() || '';
    const { password } = this.state;

    // this prevents calling `Auth.signIn()` again before it returns thus prevents the crash
    if (this._isLoading) return;

    this.setLoading(true);

    return Auth.signIn(username, password)
      .then((user) => {
        this.setLoading(false);

        const requireMFA = user.Session !== null;
        if (user.challengeName === 'SMS_MFA') {
          this.changeState('confirmSignIn', user);
        } else if (user.challengeName === 'NEW_PASSWORD_REQUIRED') {
          this.changeState('requireNewPassword', user);
        } else {
          this.checkContact(user);
        }
      })
      .catch((err) => {
        this.setLoading(false);

        if (err.code === 'PasswordResetRequiredException') {
          this.changeState('forgotPassword', username);
        } else {
          this.error(err);
        }
      });
  }
}

export default SignInOverride;
```

And then on Auth screen:

```jsx
     <Authenticator
            hideDefault={true}
            theme={CustomAmplifyTheme}
            onStateChange={onAuthStateChange}
            authState={authState}
            usernameAttributes="Email"
            signUpConfig={signUpConfig}
            errorMessage={map}
          >
            {/* 
              // this is almost the exact copy override of the original sign in 
              // except it prevents a crash caused by double tapping the button... 
              // https://github.com/aws-amplify/amplify-js/issues/7763 
              */}
            {/* eslint-disable-next-line @typescript-eslint/ban-ts-comment */}
            {/* @ts-ignore */}
            <SignInOverride _onLoadingCb={setIsLoading} />
            <SignUp signUpConfig={signUpConfig} />
            <ConfirmSignUp />
            <ForgotPassword />
            <VerifyContact />
            <RequireNewPassword />
            <Loading />
            <Status />
       </Authenticator>
```

Hope this helps.

Cheers,
Robert

**Comment by chrisbonifacio** [comment]
@rraczae I'm able to reproduce this consistently if I try to double-click very quickly. I'm certain this would be more consistent on a slower connection though so I've labeled it as a bug for the UI team to look into. Thank you!

**Comment by calebpollman** [comment]
Fix can be tested by installing `aws-amplify@unstable `, will be included in the next prod release
