### ISSUE TITLE
Error Uploading to s3 bucket

### ISSUE THREAD

**Issue by RandyWuchi** [aws-amplify/amplify-js#7768]
**Describe the bug**
I tried uploading to s3 but I get an error used to work till I updated aws cli

Here is the Error
AWSS3Provider - error uploading, [TypeError: undefined is not an object (evaluating 'data.byteLength')]

And this is the code I use
const uploadImage = async (uri) => {
    try {
      const response = await fetch(uri);

      const blob = await response.blob();

      const urlParts = uri.split(".");
      const extension = urlParts[urlParts.length - 1];

      const key = `${uuidv4()}.${extension}`;
      const url = `https://${bucket}.s3.${region}.amazonaws.com/public/${key}`;

      console.log(key, url);

      await Storage.put(key, blob, { contentType: "image/jpeg" });

      return url;
    } catch (error) {
      console.log("Error @upLoadImage:", error);
    }
  };

**Comment by sammartinez** [comment]
Can you provide your `package.json` along with your environment settings? 

Please use the follow command: 
```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

Thanks ahead of time!

**Comment by RandyWuchi** [comment]
Okay here it is,

` System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 820.95 MB / 3.92 GB
  Binaries:
    Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    @babel/core: ~7.9.0 => 7.9.0
    @expo/vector-icons: ^12.0.0 => 12.0.3
    @react-native-async-storage/async-storage: ^1.13.4 => 1.13.4
    @react-native-community/masked-view: 0.1.10 => 0.1.10
    @react-native-community/netinfo: ^5.9.7 => 5.9.7
    @react-navigation/bottom-tabs: ^5.11.7 => 5.11.7
    @react-navigation/drawer: ^5.12.3 => 5.12.3
    @react-navigation/native: ^5.9.2 => 5.9.2
    @react-navigation/stack: ^5.14.2 => 5.14.2
    aws-amplify: ^3.3.19 => 3.3.19
    aws-amplify-react-native: ^4.3.1 => 4.3.1
    dayjs: ^1.10.4 => 1.10.4
    expo: ^40.0.1 => 40.0.1
    expo-blur: ~8.2.2 => 8.2.2
    expo-constants: ~9.3.3 => 9.3.5
    expo-font: ~8.4.0 => 8.4.0
    expo-image-picker: ~9.2.0 => 9.2.1
    expo-linking: ~2.0.1 => 2.0.1
    expo-location: ~10.0.0 => 10.0.0
    expo-permissions: ~10.0.0 => 10.0.0
    expo-secure-store: ~9.3.0 => 9.3.0
    expo-status-bar: ~1.0.3 => 1.0.3
    formik: ^2.2.6 => 2.2.6
    jwt-decode: ^3.1.2 => 3.1.2
    lottie-react-native: ~2.6.1 => 2.6.1
    react: 16.13.1 => 16.13.1
    react-dom: 16.13.1 => 16.13.1
    react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
    react-native-animatable: ^1.3.3 => 1.3.3
    react-native-expo-image-cache: ^4.1.0 => 4.1.0
    react-native-geocoding: ^0.5.0 => 0.5.0
    react-native-gesture-handler: ~1.8.0 => 1.8.0
    react-native-get-random-values: ^1.6.0 => 1.6.0
    react-native-maps: 0.27.1 => 0.27.1
    react-native-progress: ^4.1.2 => 4.1.2
    react-native-reanimated: ~1.13.0 => 1.13.2
    react-native-redash: ^16.0.8 => 16.0.8
    react-native-safe-area-context: 3.1.9 => 3.1.9
    react-native-screens: ~2.15.2 => 2.15.2
    react-native-shared-element: 0.7.0 => 0.7.0
    react-native-web: ^0.13.18 => 0.13.18
    react-navigation-shared-element: ^2.3.1 => 2.3.1
    uuid: ^8.3.2 => 8.3.2
    yup: ^0.32.9 => 0.32.9
  npmGlobalPackages:
    @aws-amplify/cli: 4.44.0
    expo-cli: 4.1.6
    nodemon: 2.0.6
    typescript: 4.0.5`

**Comment by RandyWuchi** [comment]
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 820.95 MB / 3.92 GB
  Binaries:
    Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    @babel/core: ~7.9.0 => 7.9.0
    @expo/vector-icons: ^12.0.0 => 12.0.3
    @react-native-async-storage/async-storage: ^1.13.4 => 1.13.4
    @react-native-community/masked-view: 0.1.10 => 0.1.10
    @react-native-community/netinfo: ^5.9.7 => 5.9.7
    @react-navigation/bottom-tabs: ^5.11.7 => 5.11.7
    @react-navigation/drawer: ^5.12.3 => 5.12.3
    @react-navigation/native: ^5.9.2 => 5.9.2
    @react-navigation/stack: ^5.14.2 => 5.14.2
    aws-amplify: ^3.3.19 => 3.3.19
    aws-amplify-react-native: ^4.3.1 => 4.3.1
    dayjs: ^1.10.4 => 1.10.4
    expo: ^40.0.1 => 40.0.1
    expo-blur: ~8.2.2 => 8.2.2
    expo-constants: ~9.3.3 => 9.3.5
    expo-font: ~8.4.0 => 8.4.0
    expo-image-picker: ~9.2.0 => 9.2.1
    expo-linking: ~2.0.1 => 2.0.1
    expo-location: ~10.0.0 => 10.0.0
    expo-permissions: ~10.0.0 => 10.0.0
    expo-secure-store: ~9.3.0 => 9.3.0
    expo-status-bar: ~1.0.3 => 1.0.3
    formik: ^2.2.6 => 2.2.6
    jwt-decode: ^3.1.2 => 3.1.2
    lottie-react-native: ~2.6.1 => 2.6.1
    react: 16.13.1 => 16.13.1
    react-dom: 16.13.1 => 16.13.1
    react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
    react-native-animatable: ^1.3.3 => 1.3.3
    react-native-expo-image-cache: ^4.1.0 => 4.1.0
    react-native-geocoding: ^0.5.0 => 0.5.0
    react-native-gesture-handler: ~1.8.0 => 1.8.0
    react-native-get-random-values: ^1.6.0 => 1.6.0
    react-native-maps: 0.27.1 => 0.27.1
    react-native-progress: ^4.1.2 => 4.1.2
    react-native-reanimated: ~1.13.0 => 1.13.2
    react-native-redash: ^16.0.8 => 16.0.8
    react-native-safe-area-context: 3.1.9 => 3.1.9
    react-native-screens: ~2.15.2 => 2.15.2
    react-native-shared-element: 0.7.0 => 0.7.0
    react-native-web: ^0.13.18 => 0.13.18
    react-navigation-shared-element: ^2.3.1 => 2.3.1
    uuid: ^8.3.2 => 8.3.2
    yup: ^0.32.9 => 0.32.9
  npmGlobalPackages:
    @aws-amplify/cli: 4.44.0
    expo-cli: 4.1.6
    nodemon: 2.0.6
    typescript: 4.0.5

**Comment by amrut1999** [comment]
Facing the same issue. Any resolutions to this?

**Comment by RandyWuchi** [comment]
> Facing the same issue. Any resolutions to this?
> The error arises even for `const result = await Storage.put('test.txt', 'Hello');`
> 
> System:
> OS: macOS 11.2.3
> CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
> Memory: 2.42 GB / 16.00 GB
> Shell: 5.8 - /bin/zsh
> Binaries:
> Node: 14.15.4 - /usr/local/bin/node
> Yarn: 1.22.10 - /usr/local/bin/yarn
> npm: 7.5.4 - /usr/local/bin/npm
> Watchman: 4.9.0 - /usr/local/bin/watchman
> Browsers:
> Chrome: 89.0.4389.90
> Safari: 14.0.3
> npmPackages:
> @babel/core: ~7.9.0 => 7.9.6
> @react-native-community/netinfo: ^6.0.0 => 6.0.0
> aws-amplify: ^3.3.26 => 3.3.26
> aws-amplify-react-native: ^4.3.2 => 4.3.2
> expo: ~40.0.0 => 40.0.1
> expo-app-loading: ^1.0.1 => 1.0.1
> expo-av: ~8.7.0 => 8.7.0
> expo-camera: ~9.1.0 => 9.1.1
> expo-font: ~8.4.0 => 8.4.0
> expo-media-library: ~10.0.0 => 10.0.0
> expo-permissions: ~10.0.0 => 10.0.0
> expo-status-bar: ~1.0.3 => 1.0.3
> native-base: ^2.15.2 => 2.15.2
> react: 16.13.1 => 16.13.1
> react-dom: 16.13.1 => 16.13.1
> react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
> react-native-camera: ^3.42.0 => 3.43.1
> react-native-elements: ^3.2.0 => 3.3.2
> react-native-linear-gradient: ^2.5.6 => 2.5.6
> react-native-safe-area-context: 3.1.9 => 3.1.9
> react-native-swiper: ^1.6.0 => 1.6.0
> react-native-torch: ^1.2.0 => 1.2.0
> react-native-web: ~0.13.12 => 0.13.18
> npmGlobalPackages:
> @aws-amplify/cli: 4.46.0
> expo-cli: 4.0.17
> npm: 7.5.4
> react-native-cli: 2.0.1
> yarn: 1.22.10

Unfortunately it has not been resolved yet but hoping they would someday... For now I'm using some other service till this is resolved

**Comment by amrut1999** [comment]
@RandyWuchi I seem to resolved it. The issue arises when amplify add storage is configured to only "Auth Users" instead of "Auth and Guest Users". If you selected "Auth Users", I believe you need to implement a login system to register new users to the app?

**Comment by RandyWuchi** [comment]
> @RandyWuchi I seem to have resolved it. The issue arises when amplify add storage is configured to only "Auth Users" instead of "Auth and Guest Users". If you selected "Auth Users", I believe you need to implement a login system to register new users to the app?

Okay, thanks will try to do that

**Comment by magicmove** [comment]
Had the same issue with Pinpoint.
Added unauth users to amplify auth solved the issue. But i hope it will be fixed for amplify as well. 

Thanks
