### ISSUE TITLE
API.graphql .subscribe gives AWSAppSyncRealTimeProvider.js:29 Uncaught (in promise) undefined

### ISSUE THREAD

**Issue by thenewcoda** [aws-amplify/amplify-js#7776]
**Describe the bug**
I wish the bug is more descriptive but it's not. It's simply:

AWSAppSyncRealTimeProvider.js:29 Uncaught (in promise) undefined
![image](https://user-images.githubusercontent.com/65274840/108469966-2aabf100-72c4-11eb-8128-0fa1795694e4.png)

![image](https://user-images.githubusercontent.com/65274840/108470023-41eade80-72c4-11eb-9753-855c10c3528d.png)

**To Reproduce**
This is my code:
```
API.graphql({ query: onUpdateMainSwitch })
                .subscribe({
                    next: (eventData) => {
                        const mainSwitch = eventData.value.data.onUpdateMainSwitch;
                        this.mainSwitch = Boolean(mainSwitch.enabled)
                    }
                });
```
Nothing fancy

**Expected behavior**
It was working before. I am not sure what caused this to fail now. Perhaps after I updated the amplify-cli but I am not totally sure.

I even tried reverting my GIT to the point when it was working and it still doesn't which means it's not my code. It's Amplify somewhere.

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.
* Which resources do you have configured?
  * If applicable, please provide your `aws-exports` file:
   ```
   const awsmobile = {
    "aws_project_region": "ap-xxxx-1",
    "aws_appsync_graphqlEndpoint": "xxxxx",
    "aws_appsync_region": "xxxxxxx",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "ap-xxx-1:xxxxxx",
    "aws_cognito_region": "ap-xxxx-1",
    "aws_user_pools_id": "ap-xxxx-1_xxxxx",
    "aws_user_pools_web_client_id": "xxxxxx",
    "oauth": {},
    "predictions": {
        "convert": {
            "speechGenerator": {
                "region": "ap-xxxx-1",
                "proxy": false,
                "defaults": {
                    "VoiceId": "Emma",
                    "LanguageCode": "en-GB"
                }
            }
           }
        }
    };


   export default awsmobile;
   ```
</details>

More details:
- Everything else works fine (CRUD operations). It's just not live since subscription fails.
- I believe this person is having the same issue so his post might give more details to this: https://stackoverflow.com/questions/64927865/amplify-appsync-subscription-uncaught-in-promise (obviously the one 'answer' doesn't solve it, although it's for React, but still, I thought it's worth linking.)

**Comment by amhinson** [comment]
Can you share your `package.json` as well?

**Comment by thenewcoda** [comment]
> Can you share your `package.json` as well?

Sure thing

```
{
  "name": "xxxxx",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@aws-amplify/ui-vue": "^0.2.20",
    "aws-amplify": "^3.3.1",
    "bootstrap": "^4.5.2",
    "bootstrap-vue": "^2.17.3",
    "core-js": "^3.6.5",
    "dayjs": "^1.8.36",
    "howler": "^2.2.0",
    "node-sass": "^4.14.1",
    "sass-loader": "^10.0.2",
    "typeface-montserrat": "0.0.75",
    "v-calendar": "^1.0.8",
    "vue": "^2.6.12",
    "vuex": "^3.5.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "vue-template-compiler": "^2.6.11"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}
```

**Comment by thenewcoda** [comment]
You may close this issue. I have figured it out. Turns out it's the AppSync API (Auth) that is expired. I hope this helps other people who encounter this issue as well.
