### ISSUE TITLE
Google login not creating entries in User pool (not using Hosted UI)

### ISSUE THREAD

**Issue by roks0n** [aws-amplify/amplify-js#778]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
I've set up User pool and Identity Pool. (I've created Identity Pool only because it's required by aws-amplify, otherwise I wouldn't - I don't think I need it if I only want to use User Pool with 3rd party signin aka Identity Providers?)
I've set Google in the Identity providers section of User pools.
I've also set attribute mappings.
![image](https://user-images.githubusercontent.com/889696/39547762-ce7f19ee-4e58-11e8-9b7a-4f0a9b7b699c.png)
![image](https://user-images.githubusercontent.com/889696/39547778-ddcf3faa-4e58-11e8-9524-3d53a3024564.png)

After signing in via Google, I only see an Identity Pool entry but no entry in the User pool.

Note that I'm using `Authenticator` which renders the Google login button for me.

**What is the expected behavior?**
After signing in via Google, I expect to see an entry for that user created under User pool.

**Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?**
I'm using the following versions:
```
"aws-amplify": "0.2.15",
"aws-amplify-react": "^0.1.43",
```
I can't upgrade do 0.3.0 and higher due to https://github.com/aws/aws-amplify/issues/686

**Comment by powerful23** [comment]
@roks0n How are you signin via Google? If you are not using the [Hosted UI](https://aws.github.io/aws-amplify/media/authentication_guide#configuring-the-hosted-ui) feature you will not have the google user mapped into your userpool.

**Comment by roks0n** [comment]
I'm not using hosted ui, that's correct. I'll make a change later in the day and update you here, I'm positive it will work with that approach.

What can I use to make it work using custom? If not, is this something that you intend to do in the future and if you have a rough estimation when could this be available?

I really appreciate your fast reply, thank you! :)

**Comment by elorzafe** [comment]
Hi @yuntuowang I am not sure if that is possible (outside the hosted UI).

**Comment by roks0n** [comment]
Hey @powerful23, sorry that it took me a bit to get back to you. I can confirm that by using the Hosted UI it works as expected. Ty! :)

@elorzafe do you think that will still be the case in future? It would really be beneficial if we could make our own auth flows.

**Comment by sammartinez** [comment]
Closing issue from roks0n response above. Please feel free to reopen if youre still experiencing an issue

**Comment by TOPSinfo** [comment]
Has anyone found any solution for this. I cant have hosted UI for my application and need to give option to login via google.
