### ISSUE TITLE
Customizing React AmplifyRequireNewPassword  says "Password cannot be empty"

### ISSUE THREAD

**Issue by sridharbch** [aws-amplify/amplify-js#7784]
I'm customizing my React AmplifyRequireNewPassword form to have custom text, but when I click on 'Change' button I always end up getting "Password cannot be empty" validation error even when password is filled. If I try to add User attribute tag, first name and last name fields are repeated twice in the screen and I still get the same error. I'm not sure whether it is a bug or I'm missing something

Versions:  "@aws-amplify/ui-react": "^1.0.2",,  "aws-amplify": "^3.3.20",    "react": "^17.0.1" .
```
<AmplifyRequireNewPassword 
      slot="require-new-password" 
      formFields={[
        {
          type: "password",
          label: "Password",
          placeholder: "your new password should have 12 characters with uppercase, lower case and number",
          required: true,
          inputProps: { 'data-test': 'require-new-password-password-input' }
        },       
        {
          label: 'First Name',
          placeholder: "Your First Name",
          required: true,
          type: 'name',
        },
        {
          label: 'Last name',
          placeholder: "Your Last Name",
          required: true,
          type: 'family_name',
        }
      ]} 
    headerText="My Custom Require New Password Text">
    </AmplifyRequireNewPassword>
```

**Comment by sridharbch** [comment]
Are you able to reproduce this issue?

**Comment by sridharbch** [comment]
Experts, any help on this ?? . I just want to change  'Family Name' to 'Last Name' and add a placeholder in password field..

**Comment by wlee221** [comment]
Hi! If you are looking to just change the text, you can use [Translations](https://docs.amplify.aws/ui/customization/translations/q/framework/vue) to change the text.

```
import { I18n } from "aws-amplify";
import { Translations } from "@aws-amplify/ui-components";

I18n.putVocabulariesForLanguage("en-US", {
  [Translations.FAMILY_NAME_LABEL]: "Last Name",
  [Translations.FAMILY_NAME_PLACEHOLDER]: "Your Last Name"
});
```

and so on. You can see the list of supported translatable text [here](https://github.com/aws-amplify/amplify-js/blob/main/packages/amplify-ui-components/src/common/Translations.ts).

**Comment by wlee221** [comment]
Though, it is true that custom `formFields` do not work as expected for `amplify-require-new-password`. Please let us know / open a new issue so we can prioritize fixing that, but for your use case using `translations` should be sufficient.

**Comment by sridharbch** [comment]
Thanks for your suggestion @wlee221 , I tried the translations, It still didn't change the FAMILY_NAME_LABEL / FAMILY_NAME_PLACEHOLDER / GIVEN_NAME_LABEL / GIVEN_NAME_PLACEHOLDER,  but it could change the NEW_PASSWORD_LABEL text , bit weird.


```
import { I18n } from "aws-amplify";
import { Translations } from "@aws-amplify/ui-components";

I18n.putVocabulariesForLanguage("en-US", {
  //working
  [Translations.NEW_PASSWORD_LABEL]:"New Pwd",
 // below 4 lines not working
  [Translations.FAMILY_NAME_LABEL]: "Last Name",
  [Translations.FAMILY_NAME_PLACEHOLDER]: "Your Last Name",
  [Translations.GIVEN_NAME_LABEL]:"FName",
  [Translations.GIVEN_NAME_PLACEHOLDER]:"FName label"
});
```

  ```
     <AmplifyRequireNewPassword 
      slot="require-new-password" 
      user={user}
       headerText="My Custom Require New Password Text">
      </AmplifyRequireNewPassword>
```

**Comment by sridharbch** [comment]
@wlee221 , Any ETA on it ? , I need to implement this in one of my project.

**Comment by wlee221** [comment]
Hi, I apologize about the delayed response. I do see that this is a bug on our code: 

https://github.com/aws-amplify/amplify-js/blob/01649ed2d6b98b115af6d944898fca33235c31d5/packages/amplify-ui-components/src/components/amplify-require-new-password/amplify-require-new-password.tsx#L84-L85

These need to be mapped to the correct `translation`. I'll make a PR by this week.

**Comment by wlee221** [comment]
For now, can you try placing the translations inside the your entry file (e.g. `src/index.js` with create-react-app) is and see if translation works?

**Comment by sridharbch** [comment]
Thanks @wlee221 for your suggestion, I tried placing the translation inside the index.js, but it didn't work. I appreciate you looking into this issue.

**Comment by wlee221** [comment]
@sridharbch, @Edo-San opened a PR for this that would resolve this. We'll get this reviewed + merged -- thanks for the patience!

**Comment by wlee221** [comment]
Hi, I'll be closing this as #7998 has been merged. This is now on the `unstable` tag for you to try:

```bash
npm i --save aws-amplify@unstable @aws-amplify/ui-components@unstable
# or
yarn add aws-amplify@unstable @aws-amplify/ui-components@unstable 
```

This will be published to stable on the next release cycle. Please let us know if the issue persists after then.

**Comment by k4mp3r** [comment]
@sridharbch did you ever get a resolution to this issue? I am having the same problem but this issue shows as fixed.
Currently using:
 "@aws-amplify/ui-components": "^1.7.0",
 "@aws-amplify/ui-react": "^1.2.7",

**Comment by Alaqwer** [comment]
The issue still appears with
"@aws-amplify/ui-react": "^1.2.8"

The main problem is that overriding fields not allow further flow of changing password via AmplifyRequireNewPassword component. It shows the exclamation 'Password cannot be empty'.

I consider this issue as a bug of @aws-amplify/ui-react

**Comment by shoaib30** [comment]
This issue still appears in `"@aws-amplify/ui-react": "^1.2.19"`

Any plans on fixing this issue? makes the ui-react component unusable when sending an invite to the user.
