### ISSUE TITLE
Typedefinition: userConfirmationNecessary missing from sendMFACode onSuccess

### ISSUE THREAD

**Issue by mk0sojo** [aws-amplify/amplify-js#7793]
**Describe the bug**
The userConfirmationNecessary flag is missing from onSuccess callback on sendMFACode 

Will add a pull request

**Comment by evcodes** [comment]
Hello Jonas,

It is unclear how we can reproduce this issue and help solve it. Can you please add more information/link your pull request so that we can review you bug and help take care of the issue. 

Thank you!

**Comment by mk0sojo** [comment]
Hi, created a pull request for the issue.

**Comment by amhinson** [comment]
Closing this issue, as the associated PR has been merged 👍
