### ISSUE TITLE
signInUserSession is null during sendMFACode

### ISSUE THREAD

**Issue by stenmuchow** [aws-amplify/amplify-js#7799]
**Describe the bug**
I have a cognitoUser setup during the confirmSignIn auth method call we are sending the MFA code that the system is sending to us via SMS internally we are getting an error that says the cannot getIdToken of null. Ive managed to find the lines that are failing us. 

In the file CognitoUser.js line 885:

```
this.signInUserSession = this.getCognitoUserSession(
					dataAuthenticate.AuthenticationResult
				);
```

after this method is called the constructor method is passed correct values and no errors are thrown when the constructor method in CognitoUserSession.js is invoked. 

However this.signInUserSession remains null and then the next line is invoked

```
				this.cacheTokens();
```

Which internally asks for the token via the this.signInUserSession object that was supposed to be created above however its null. 

So it throws the [TypeError: Cannot read property 'getIdToken' of null]

**To Reproduce**

I have a react native application using the steps outlined in the documentation of how to setup signin with MFA. 

**Expected behavior**
I dont want a typeerror to be thrown

**Code Snippet**
```
    SIGNIN Fct
    const user = await Auth.signIn(username, password)
    setRecoilValue(userAtom, user)

     CONFIRM_SIGNIN Fct
    const { contents } = getRecoilValue(userAtom)
    const currentUser = await Auth.confirmSignIn(contents, code, 'SMS_MFA')
```

**Screenshots**

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.
* Which resources do you have configured?
  * If applicable, please provide your `aws-exports` file:
  

```
const COGNITO_CLIENT_ID = '503k11j7q7oujkfemrr62o0k12'
const COGNITO_USER_POOL_ID = 'us-east-2_LjdzgbOoq'

Amplify.configure({
  authenticationFlowType: 'USER_PASSWORD_AUTH',
  region: 'us-east-2',
  userPoolId: COGNITO_USER_POOL_ID,
  userPoolWebClientId: COGNITO_CLIENT_ID,
  storage: AmplifyAuthStorage
})
```

* If applicable, provide more configuration data, for example for Amazon Cognito, run `aws cognito-idp describe-user-pool --user-pool-id us-west-2_xxxxxx` (Be sure to remove any sensitive data)
 

**Smartphone (please complete the following information):**

IOS Emulator

**Additional context**

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by stenmuchow** [comment]
Im working on getting a couple screen shots as well but we are having some issues with the sms.

**Comment by stenmuchow** [comment]
I know the issue now - and its to do with passing this:

const user = Auth.signIn() 

The user object has way too much stuff going on and can fail if passed between a couple react components. I was storing it in a Recoil state and navigating to the verify number page but under the hood this object is not anything simple. 

Would be great if this object was easier to pass around. 

I solved this by adding a modal to the sign up and sign in pages so I dont have to store the user object anywhere else.

**Comment by ClaudionorJunior** [comment]
This Solution works for me, I create again user object with createCognitoUser, passing username from prop...

`let user = (Auth as any).createCognitoUser(
        param.cognitoRequeriments.user.username,
      );
      user.Session = param.cognitoRequeriments.user.Session;
      Auth.sendCustomChallengeAnswer(
        user,
        code,
        param.cognitoRequeriments.validationData,
      )`
