### ISSUE TITLE
AWSDateTime query filtering bypassed if I don't refresh the page after updating data 

### ISSUE THREAD

**Issue by vincent38wargnier** [aws-amplify/amplify-js#7804]
Hi,
I spent some hours finding what was weird in my app. I will try to be clear in its way of working:

-I have services that a user can subscribe. When a user unsubscribes to a service, I update the field "dateUnsubscribed".
If the "dateUnsubscribed" field = to null or < now, it means the user still subscribes to the service.
To test my system, I subscribed and unsubscribed to many services.

Now if I call a query that gets the services subscribed with the following filtering :
`services(filter: {or: [{dateUnsubscribed: {attributeExists: false}}, {dateUnsubscribed: {gt: "${new Date().toISOString()}"}}]})`
the query returns me all the services even the ones that have "dateUnsubscribed" < now.

Here is the services returned :
![image](https://user-images.githubusercontent.com/33725800/107952943-b8bd6a00-6f9a-11eb-884f-cad7fe040bfe.png)
You can see at the bottom of the screenshot the actual time. We see here that it returns services with dateUnsubscribed < now, even if I have the filtering.

Now, if i refresh the page, and call this query again, the query doesn't return me the services with "dateUnsubscribed" < now:
![image](https://user-images.githubusercontent.com/33725800/107952907-ab07e480-6f9a-11eb-908c-7277bfc4797c.png)

You can see that all the services with "dateUnsubscribed" < now are not returned anymore.

**My question is : is there some stuff stored in cash memory or something that bypass the filtering of my query?**

I spent hours looking for the cause of this pb and I don't understand how the filtering could work better if I refresh the page or not. The database is well updated, and all I'm doing is reading the database content. I don't understand how refreshing my page interacts with the database reading.

Thank you

I use cli version 4.41.2 on mac OS.

**Comment by sammartinez** [comment]
@vincent38wargnier,
 
Can you provide your `package.json` along with your environment settings? 

Please use the follow command: 
```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

Thanks ahead of time!

**Comment by vincent38wargnier** [comment]
Hi @sammartinez ,
this is what I get from this command : 
```
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 929.79 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.3.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 7.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Safari: 13.1.2
  npmPackages:
    @aws-amplify/ui-react: ^0.2.38 => 0.2.38 
    @craco/craco: ^6.0.0 => 6.1.1 
    @graphql-codegen/cli: ^1.21.1 => 1.21.1 
    @tailwindcss/postcss7-compat: ^2.0.3 => 2.0.3 
    @testing-library/jest-dom: ^5.11.4 => 5.11.9 
    @testing-library/react: ^11.1.0 => 11.2.5 
    @testing-library/user-event: ^12.1.10 => 12.7.3 
    @types/react-transition-group: ^4.4.0 => 4.4.1 
    autoprefixer: ^9.8.6 => 9.8.6 
    aws-amplify: ^3.3.21 => 3.3.21 
    aws-sdk: ^2.826.0 => 2.853.0 
    axios: ^0.21.1 => 0.21.1 
    blueimp-load-image: ^2.31.0 => 2.31.0 
    compress.js: ^1.1.2 => 1.1.2 
    exif-js: ^2.3.0 => 2.3.0 
    fix-image-rotation: ^2.0.0 => 2.0.0 
    graphql: ^15.4.0 => 15.5.0 
    graphql-tag: ^2.11.0 => 2.11.0 
    html2canvas: ^1.0.0-rc.7 => 1.0.0-rc.7 
    ibantools: ^3.2.3 => 3.2.3 
    moment: ^2.29.1 => 2.29.1 
    pdf-image: ^2.0.0 => 2.0.0 
    postcss: ^7.0.35 => 7.0.35 
    qrcode.react: ^1.0.1 => 1.0.1 
    react: ^17.0.1 => 17.0.1 
    react-beautiful-dnd: ^13.0.0 => 13.0.0 
    react-datepicker: ^3.5.0 => 3.6.0 
    react-dom: ^17.0.1 => 17.0.1 
    react-facebook-pixel: ^1.0.4 => 1.0.4 
    react-ga: ^3.3.0 => 3.3.0 
    react-icons: ^4.1.0 => 4.2.0 
    react-pdf: ^5.2.0 => 5.2.0 
    react-router-dom: ^5.2.0 => 5.2.0 
    react-scripts: 4.0.1 => 4.0.1 
    react-select: ^3.2.0 => 3.2.0 
    react-select-country-list: ^2.2.3 => 2.2.3 
    react-simple-toasts: ^1.1.2 => 1.1.2 
    react-switch: ^6.0.0 => 6.0.0 
    styled-components: ^5.2.1 => 5.2.1 
    web-vitals: ^0.2.4 => 0.2.4 
    yaqrcode: ^0.2.1 => 0.2.1 
  npmGlobalPackages:
    @aws-amplify/cli: 4.50.0
    nan: 2.14.1
    node-modules: 1.0.1
    npm-install-peers: 1.2.1
    npm: 7.6.0
```

All those versions might be different than when I had this issue, I didn't try again, I changed my system to not face this issue again.

**Comment by chrisbonifacio** [comment]
Hi :wave: Sorry this was auto-closed by stale bot. We are working towards preventing this from happening in the future. Please let us know if you are still experiencing this issue and in need of assistance.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!
