### ISSUE TITLE
Predictions Speech to text doesn't work in fr-FR, en-AU, en-GB and fr-CA

### ISSUE THREAD

**Issue by SebSchwartz** [aws-amplify/amplify-js#7808]
**Describe the bug**
The speech to text cannot work in fr-FR, en-AU, en-GB and fr-CA as the sample rate for the streaming transcription is limited to 8 kHz and amplify always send 16 kHz in the request.
As explained in the doc -> https://docs.aws.amazon.com/transcribe/latest/dg/streaming.html

**To Reproduce**

1. Take the example from -> https://docs.amplify.aws/lib/predictions/sample/q/platform/js#sample-react-app
2. Specify the language in one of the listed one.
3. You will receive 2 errors 
   1. One that should be fixed in https://github.com/aws-amplify/amplify-js/pull/7803 -> missing return in code
   2. The real error -> **The requested language doesn't support the specified sample rate. Use the correct sample rate then try again.**
6. You could try to resample to 8 kHz as requested in the aws doc with _wavefile_ library for example (code is working for en-US)
```javascript
let wav = new WaveFile();
wav.fromBuffer(new Uint8Array(fileBlob));
wav.toSampleRate(8000);
```
7. But the request made to Streaming Transcription endpoint is hardcoded to 16 kHz as you can see in the code (L402):
https://github.com/aws-amplify/amplify-js/blob/ac0ef4b994a863fac3b5899fe7190c20a070fa16/packages/predictions/src/Providers/AmazonAIConvertPredictionsProvider.ts#L397-L402

**Expected behavior**
Amplify should detect the sample rate or allow user to pass it as param (more easy to do).

**Code Snippet**
```javascript
const speechToTextOutput = await Predictions.convert({
                      transcription: {
                        source: {
                          bytes: rawPcm,
                        },
                        language: 'fr-FR',
                      },
                    });
```

**Comment by wlee221** [comment]
Hi @SebSchwartz, thanks for your research! You are right, and we should downsample the buffer to 8khz depending on the language code. We already have code for downsampling that should make this fix easier: https://github.com/aws-amplify/amplify-js/blob/ac0ef4b994a863fac3b5899fe7190c20a070fa16/packages/predictions/src/Providers/AmazonAIConvertPredictionsProvider.ts#L332

and we were hard setting the target downsample samplerate to 8khz here https://github.com/aws-amplify/amplify-js/blob/ac0ef4b994a863fac3b5899fe7190c20a070fa16/packages/predictions/src/Providers/AmazonAIConvertPredictionsProvider.ts#L330

We would just need to set that to 8khz if the target code is one of the four you mentioned. Then finally we would dynamically set

https://github.com/aws-amplify/amplify-js/blob/ac0ef4b994a863fac3b5899fe7190c20a070fa16/packages/predictions/src/Providers/AmazonAIConvertPredictionsProvider.ts#L402

to 8khz or 16khz. Do you think you can work on creating a PR for this?

**Comment by SebSchwartz** [comment]
@wlee221 I've pushed my PR #7835 ;)

**Comment by wlee221** [comment]
Thanks a lot @SebSchwartz ! I'll take a look :)

**Comment by sammartinez** [comment]
From the above pull request being merged, I am going to close this issue.
