### ISSUE TITLE
AWSIoTProvider not connecting

### ISSUE THREAD

**Issue by rogueturnip** [aws-amplify/amplify-js#781]
Bug:

Not connecting

We've enabled the Role on the Cognito Identity Pool and the Policy on the Identity ID for the user but when using amplify in our we are not getting it to connect.  I don't even see anything in the Cloudwatch logs when I enable debug on IoT.  When using Paho client we get Error: AMQJS0007E Socket error: Unknown socket error.

WHen I console log the return on PubSub.addProvider I get:
Promise {
"_40": 0,
"_55": Object {
     "Auth": Object {
     "identityPoolId": "<Correct pool ID>",
       "region": "us-west-2",
       "userPoolId": "<correct pool id>",
       "userPoolWebClientId": "<web client id",
     },
     "aws_pubsub_endpoint": "wss://<endpoint>.iot.us-west-2.amazonaws.com/mqtt",
     "aws_pubsub_region": "us-west-2",
     "clientId": "81bc4e0c-1775-42a8-b286-3b0acd6e1126",
   },
   "_65": 1,
   "_72": null,
}

Is there any way to debug more on PubSub or is there anything that might be causing this issue?  It almost feels like the IoT endpoint isn't there.

We are doing this in React Native if that matters but just using aws-amplify library.

Thanks!

**Comment by rogueturnip** [comment]
Doing more investigation this to see if it was an Auth issue I did find for mqtt Paho I was using the wrong keys (still not authorized but at least seeing in cloudwatch logs).  I couldn't see anything from PubSub so I looked at the Auth.currentCredentials() return and it doesn't match what is expected in the PubSub AWSIoTProvider.ts file:
            const { accessKeyId: access_key,
                secretAccessKey: secret_key,
                sessionToken: session_token,
            } = await Auth.currentCredentials();

These don't seem to exist in the object.

Am I missing something?

**Comment by johnrjj** [comment]
Had same issue - unfortunately the docs leave out the part of adding the IAM policy to the cognito pool. Attaching a policy to IOT is just one of two steps necessary.

For testing sake, if you add the full `AWSIoTFullAccess` policy to your cognito user pool and try to connect, it should work. Docs should probably add this step.

**Comment by rogueturnip** [comment]
It would be really nice if the PubSub functionality had a debug option that put alot of details on the console.  The only way we found our authentication issue was by using Paho-mqtt and logging.

**Comment by johneast** [comment]
How do you add the IAM Policy to the cognito pool? I can't see how to do this.

**Comment by rogueturnip** [comment]
You have to add it from the aws cli. Three commands I found useful.
aws iot attach-policy --policy-name 'IoT_Access' --target 'us-west-2:XXXXX'
aws iot list-attached-policies --target 'us-west-XXXXXXX'
aws iot detach-policy --policy-name 'IoT_Access' --target 'us-west-2:XXXXXXX'

We found that the best way was to build a lambda function that did this when the user signs up.  You can find the api in the documentation.

**Comment by Jun711** [comment]
What are the minimum permissions needed if anyone knows? thanks

**Comment by Jun711** [comment]
Note that list-principal-policies is deprecated. You can use list-attached-policies instead. 
https://docs.aws.amazon.com/iot/latest/apireference/API_ListPrincipalPolicies.html
https://docs.aws.amazon.com/cli/latest/reference/iot/list-principal-policies.html

**Comment by manueliglesias** [comment]
The [documentation](https://aws-amplify.github.io/docs/js/pubsub#aws-iot) has now a section that mentions the steps needed to get it working.

Also, to debug, you can enable logging using these [instructions](https://aws-amplify.github.io/docs/js/logger#setting-logging-levels)
