### ISSUE TITLE
AsyncStorage dependency is now deprecated 

### ISSUE THREAD

**Issue by sotomaque** [aws-amplify/amplify-js#7811]
**Describe the bug**
within @aws-amplify > core > src > StorageHelper there is an import for `import { AsyncStorage } from 'react-native';`
React native no longer exports AsyncStorage and it has now moved to `@react-native-community/async-storage`

This is leading to a crashing bug whenever users try to add an aws storage service to their application.

![](https://cdn.discordapp.com/attachments/793094402741633024/813695885157597194/Screen_Shot_2021-02-23_at_12.56.28_AM.png)

**Expected behavior**
- `import AsyncStorage from '@react-native-community/async-storage'`

**Screenshots**
![Screen Shot 2021-02-23 at 4 29 17 PM](https://user-images.githubusercontent.com/7506954/108926976-4977f380-75f4-11eb-99e1-128f3b5f67fa.png)

```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

![Screen Shot 2021-02-23 at 4 31 56 PM](https://user-images.githubusercontent.com/7506954/108927172-a673a980-75f4-11eb-9b5b-051487a71c92.png)

**Comment by iartemiev** [comment]
Hey, there's already a [PR](https://github.com/aws-amplify/amplify-js/pull/7118) for this. Since this will be a breaking change (customers will need to manually install `@react-native-async-storage/async-storage`), we'll be releasing it with the next major version of DataStore. Closing this issue.

**Comment by bjornbreck** [comment]
@iartemiev this causes an issue for any user following one of React Natives recommendation to use `@react-native-community/async-storage` instead. Are there any work arounds for this yet?

**Comment by iartemiev** [comment]
@bjornbreck `@react-native-community/async-storage` has been deprecated: https://www.npmjs.com/package/@react-native-community/async-storage

The latest supported version of AsyncStorage is [`@react-native-async-storage/async-storage`](https://www.npmjs.com/package/@react-native-async-storage/async-storage), which is what Amplify works with as well.

**Comment by bjornbreck** [comment]
@iartemiev ah gotcha gotcha, thanks so much for pointing that out to me! 💯
