### ISSUE TITLE
TypeError: Cannot read property 'translateText' of undefined

### ISSUE THREAD

**Issue by InheritxSolution** [aws-amplify/amplify-js#7812]
Package.json
"@aws-amplify/auth": "^3.2.7",
"@aws-amplify/predictions": "^3.1.10",
"amazon-cognito-identity-js": "^4.2.3",
"aws-amplify": "^3.0.10",
"aws-amplify-react-native": "^4.1.1"

App.js

import Amplify from 'aws-amplify';
import Predictions, {
  AmazonAIPredictionsProvider,
} from '@aws-amplify/predictions';

import config from './src/aws-exports';
Amplify.configure(config);
Predictions.addPluggable(new AmazonAIPredictionsProvider());

**Comment by iartemiev** [comment]
You should npm/yarn uninstall `@aws-amplify/auth` and `@aws-amplify/predictions`. Those are already included with `aws-amplify` and installing them separately can cause conflicts.

**Comment by InheritxSolution** [comment]
> You should npm/yarn uninstall `@aws-amplify/auth` and `@aws-amplify/predictions`. Those are already included with `aws-amplify` and installing them separately can cause conflicts.

I have follow the document & i have also removed  `@aws-amplify/auth` and `@aws-amplify/predictions` but its shows npm module does not exist error.

**Comment by wlee221** [comment]
Hello @InheritxSolution, what framework (if any) are you using and can you provide us a sample repository we can inspect?

**Comment by InheritxSolution** [comment]
> Hello @InheritxSolution, what framework (if any) are you using and can you provide us a sample repository we can inspect?

Using react native

**Comment by InheritxSolution** [comment]
sd

**Comment by chrisbonifacio** [comment]
Hi :wave: Sorry this was auto-closed by stale bot. We are working towards preventing this from happening in the future. Please let us know if you are still experiencing this issue and in need of assistance.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!
