### ISSUE TITLE
Rest api and Graphql api

### ISSUE THREAD

**Issue by rraczae** [aws-amplify/amplify-js#7817]
**Is your feature request related to a problem? Please describe.**
I have an amplify app using graphql. Now I need to trigger a custom action so I wanted to add a simple rest endpoint and put my business logic in a lambda function. Is there a way to achieve this?

**Describe the solution you'd like**
A guide how to add a rest api to trigger lambda when there is already to graphql endpoint in the app. (or any other way to achieve this simple task)

**Describe alternatives you've considered**
Invoking the lambda directly with `aws-sdk/clients/lambda`.

**Additional context**
none

**Comment by iartemiev** [comment]
Hey, are you asking how to call an existing REST API when you're already using the Amplify API category with a GraphQL back end? Or do you not yet have the REST API created and want a Lambda and API Gateway to be provisioned for you, e.g., via the CLI?

**Comment by rraczae** [comment]
Hey @iartemiev! The first. I have GraphQL api setup already and now I would like make an api to trigger a lambda (no data change, the user just wants to trigger an action like send email)

**Comment by rraczae** [comment]
@iartemiev I created a new project from scratch and everything works fine! ヽ(´▽`)/ 

I was able to use datastore and publish a rest api with a lambda function handling requests, everything works great. When I try to repeat this to the existing project tho I get this error:

![image](https://user-images.githubusercontent.com/73604600/109244972-4708cb80-77a5-11eb-9586-3d71d32ef52c.png)

The difference is that here we are consuming a "shared" user pool whereas in my test project I let amplify create the cognito pool. Both project have UserPool as default auth. Any ideas how we could fix this? Should we add another auth method that's IAM?
Cheers!
Rob

**Comment by medelman17** [comment]
Hey! Rather than spin up the additional REST api, you might consider adding a "custom mutation" backed by a lambda to your GraphQL api? Something like 'sendEmail(input: DataWeNeedToSatisfyRequest): EmailApiResponse @function(name: "myEmailSendingLamdba")'?

**Comment by rraczae** [comment]
Actually I just thought about it a little more and got it running: 
- created an identity pool and add my app client
- removed the current auth
- re-imported the same pool but now with identity
- adding the function was super easy

Thanks everyone appreciate the help!
