### ISSUE TITLE
Typescript errors when using PubSub on ionic

### ISSUE THREAD

**Issue by janpoltan** [aws-amplify/amplify-js#783]
Im trying to connect to the IOT device shadows via PubSub,

i got this type errors

```
Amplify.addPluggable(new AWSIoTProvider({
      aws_pubsub_region: 'eu-xxx-x',
      aws_pubsub_endpoint: 'wss://xxxxxxxx.iot.xx-xx-x.amazonaws.com/mqtt'
    }));
```

```
Typescript Error
Argument of type '{ aws_pubsub_region: string; aws_pubsub_endpoint: string; }' is not assignable to parameter of type 'MqttProvidertOptions'. Object literal may only specify known properties, and 'aws_pubsub_region' does not exist in type 'MqttProvidertOptions'.
```

**Comment by janpoltan** [comment]
Adding those types to

`
export interface MqttProvidertOptions {
    clientId?: string;
    url?: string;
    aws_pubsub_region?: string;
    aws_pubsub_endpoint?: string;
}
`
Will result to
`
api-service.ts:77 Error: Missing connections info
    at AWSAppSyncProvider.subscribe (AWSAppSyncProvider.js:75)
    at PubSub.js:114
    at Array.map (<anonymous>)
    at PubSub.js:112
    at new Subscription (Observable.js:179)
    at Observable.subscribe (Observable.js:258)
    at ApiServiceProvider.webpackJsonp.91.ApiServiceProvider.getMqttSensorData (api-service.ts:75)
    at HubsPage.webpackJsonp.203.HubsPage.getMqttSensorData (hubs.ts:51)
    at Object.eval [as handleEvent] (HubsPage.html:23)
    at handleEvent (core.js:13589)
`

**Comment by janpoltan** [comment]
The issue was no connections set for the AppSync, but still the typescript error persists

**Comment by berrylands** [comment]
Can I vote that this stays open until the interface definition is fixed as per your observation in the original post.

**Comment by johneast** [comment]
Can we get the interface definition fixed for AWSIotProvider please? It makes it awkward to use Amplify  to connect to IOT when using Angular.

**Comment by elorzafe** [comment]
@Jun711 the PR needs a change that @manueliglesias will be updating soon.
