### ISSUE TITLE
DataStore: Confusion about Relations. Why can't we get the ID of a connection?

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-js#7831]
**Which Category is your question related to?**

DataStore - web

**Amplify CLI Version** 

4.44.0

**What AWS Services are you utilizing?**

AppSync

**Provide additional details e.g. code snippets**

Given the following schema I'm confused as to why I can't get to the foreign key ID fields within my generated models. I have an Address model, this can belong to an Area (an Area have have multiple Addresses). An Address also has a M-to-1 connection to a HouseType model and finally an Address can belong to a Customer via a M-to-1 connection.

![image](https://user-images.githubusercontent.com/1674590/109301452-e5da0a00-782f-11eb-961d-2ababec7bfec.png)

Here is there things get odd. After generating my models using ``amplify codegen models`` and assuming I have a correctly filled in Address object queried from DataStore in my code I can:

- get to ``address.houseTypeID``
- get to ``address.houseType.id`` but it comes back undefined (this I expect from previous experience, but its confusing).
- can't get to ``address.customerID`` its not available in the intellisense or the model
- can get ``address.customer`` but again its undefined
- can't get to ``address.areaID``
- can get ``address.area`` but its undefined

Not sure why the first would work and the others wouldn't, is it something to do with my @keys?

How am I supposed to look up the Area for an Address when I can't get the areaID back and the ``address.area.id`` is undefined so can't use that either? Same goes for Customer, no way to actually look them up as is.

I'm sure there is a quirk in the way my schema is but not sure what as its a legit schema for GraphQL.

Any pointers?

Full schema:

```
type Address
  @model
  @searchable
  @auth(
    rules: [
      { allow: groups, groups: ["admin"] }
      { allow: public, provider: apiKey }
    ]
  )
  @key(
    name: "byCustomer"
    fields: ["customerID"]
    queryField: "addressesByCustomer"
  )
  @key(
    name: "byAreaAndStatus"
    fields: ["areaID", "addressStatus"]
    queryField: "addressesByAreaAndStatus"
  )
  @key(name: "byArea", fields: ["areaID"], queryField: "addressesByArea") {
  id: ID!
  houseType: HouseType @connection(fields: ["houseTypeID"])
  customerID: ID!
  customer: Customer! @connection(fields: ["customerID"])
  comments: [Comment] @connection(keyName: "bySource", fields: ["id"])
  subscribedServices: [ServiceSubscription]
    @connection(keyName: "byAddress", fields: ["id"])
  sectorID: ID
  areaID: ID!
  area: Area! @connection(fields: ["areaID"])
}
type Customer
  @model
  @searchable
  @auth(
    rules: [
      { allow: groups, groups: ["admin"] }
      { allow: public, provider: apiKey }
    ]
  )
  @key(
    name: "byPhoneNumber"
    fields: ["phoneNumber", "id"]
    queryField: "customerByPhoneNumber"
  )
  @key(name: "byStatus", fields: ["status"], queryField: "customerByStatus") {
  id: ID!
  firstName: String
  lastName: String
  phoneNumber: String
  email: String
  addresses: [Address] @connection(keyName: "byCustomer", fields: ["id"])
  paymentMethodID: ID!
  paymentMethod: PaymentMethod @connection(fields: ["paymentMethodID"])
  comments: [Comment] @connection(keyName: "bySource", fields: ["id"])
}
type Area
  @model
  @searchable
  @auth(
    rules: [
      { allow: groups, groups: ["admin"] }
      { allow: public, provider: apiKey }
    ]
  )
  @key(
    name: "bySector"
    fields: ["sectorID", "name"]
    queryField: "areaBySectorID"
  ) {
  id: ID!
  displayName: String!
  sectorID: ID!
  sector: Sector @connection(fields: ["sectorID"])
  accountManagerID: ID!
  accountManager: StaffMember @connection(fields: ["accountManagerID"])
  technicianID: ID!
  technician: StaffMember @connection(fields: ["technicianID"])
  servicePricings: [ServicePricing]
    @connection(keyName: "byArea", fields: ["id"])
}
```

**Comment by PeteDuncanson** [comment]
To get around this for now I've had to add an areaID to my customer entity and just have to manage updating it in both places. This allows me to filter Customers by area easily.

Question still stands though, what is the reasoning/logic for why some come back and others don't? Knowing that would help with schema choices in the future.

**Comment by PeteDuncanson** [comment]
Any more thoughts on this one anyone?

**Comment by PeteDuncanson** [comment]
Related https://github.com/aws-amplify/amplify-js/issues/7830

**Comment by PeteDuncanson** [comment]
Hey, todays my birthday! Any chance of a comment on this one as a present? It got raised again today in Discord and I still don't know why it behaves the way it does.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!

**Comment by PeteDuncanson** [comment]
Totally missed Ivans comment, sorry. Since then I've moved away from DataStore so maybe the updates mentioned have resolved the issue in the meantime.
