### ISSUE TITLE
Tags not showing on Cognito user pool but appear for other resources

### ISSUE THREAD

**Issue by gruckionvit** [aws-amplify/amplify-js#7834]
**Describe the bug**

Resource tagging not appearing for Cognito resource.

**To Reproduce**

1. Follow the guide for creating tags https://docs.amplify.aws/cli/usage/tags#adding-and-updating-tags
2. Check that your stack has tags
3. Check your cognito resource has tags

**Expected behavior**

Expected to see the tags of Cognito user pool as well as my other resources

**Screenshots**

![Screenshot 2021-02-28 at 21 02 55](https://user-images.githubusercontent.com/67283459/109433486-753a1580-7a08-11eb-82ff-195665301030.png)

![Screenshot 2021-02-28 at 21 02 17](https://user-images.githubusercontent.com/67283459/109433452-3efc9600-7a08-11eb-8690-ef1e2318e244.png)

**Smartphone (please complete the following information):**

N/A

**Comment by gruckionvit** [comment]
I've also closed the issue here. https://github.com/aws-amplify/amplify-cli/issues/6642

**Comment by amhinson** [comment]
Closing, as this appears to be related to the CLI and an issue has already been opened up on that repo.
