### ISSUE TITLE
Login inputs not treated as a single form in new Angular UI

### ISSUE THREAD

**Issue by lkowalski-smartbusiness** [aws-amplify/amplify-js#7837]
**Describe the bug**
The login form is not treated as a "whole" in the new Angular UI Auth module
Resulting issue is that none of my users can use Chrome's account autosuggestion - the password just never shows up (or the login, if you go straight for the password input, which nobody ever does). Even if you try forcing a new entry via "Suggest a password" it just stubbornly stays blank.

From a brief review of the new dynamic component present in the login form I could see that the shadow-dom is used extensively. This poses an issue when the form inputs are scattered across multiple encapsulated DOMs, not connected by an ancestor `<form>` element.

**To Reproduce**
_The steps provided assume you have credentials stored in a Chromium-based browser for your local development page_
--- steps to get a valid aws-exports.js file
1. Create new amplify project
2. Select Angular as frontend component
3. Add auth
--- steps for the error
4. install `aws-amplify ^3.3.21`, `@aws-amplify/ui-components ^1.0.3` and `@aws-amplify/ui-angular ^1.0.3`
4. add AmplifyUIAngularModule to app.modules.ts
5. put `<amplify-authenticator></amplify-authenticator>` in the `app.component.html` template
6. run the app and try to autopopulate

**Expected behavior**
The user is able to autofill *both* input fields in the login page if he's saved the credentials before

**Screenshots**
![image](https://user-images.githubusercontent.com/64459849/109492688-a4459b00-7a8b-11eb-9fe1-827150ec25f2.png)

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Auth
* Hosting
* Angular as frontend
 
<details>
  <summary><strong>Environment</strong></summary>

```
   System:
    OS: macOS 11.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.53 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    npm: 7.6.0 - ~/.nvm/versions/node/v12.19.0/bin/npm
  npmPackages:
    @angular-devkit/build-angular: ~0.1102.0 => 0.1102.0 
    @angular/animations: ~11.2.0 => 11.2.0 
    @angular/cdk: ~11.2.0 => 11.2.0 
    @angular/cli: ~11.2.0 => 11.2.0 
    @angular/common: ~11.2.0 => 11.2.0 
    @angular/compiler: ~11.2.0 => 11.2.0 
    @angular/compiler-cli: ~11.2.0 => 11.2.0 
    @angular/core: ~11.2.0 => 11.2.0 
    @angular/forms: ~11.2.0 => 11.2.0 
    @angular/language-service: ~11.2.0 => 11.2.0 
    @angular/material: ~11.2.0 => 11.2.0 
    @angular/material-moment-adapter: ~11.2.0 => 11.2.0 
    @angular/platform-browser: ~11.2.0 => 11.2.0 
    @angular/platform-browser-dynamic: ~11.2.0 => 11.2.0 
    @angular/router: ~11.2.0 => 11.2.0 
    @aws-amplify/api: ^3.2.24 => 3.2.24 
    @aws-amplify/api-rest: ^1.2.24 => 1.2.24 
    @aws-amplify/auth: ^3.4.24 => 3.4.24 
    @aws-amplify/cache: ^3.1.49 => 3.1.49 
    @aws-amplify/pubsub: ^1.3.3 => 1.3.3 
    @aws-amplify/storage: ^3.3.24 => 3.3.24 
    @aws-amplify/ui-angular: ^1.0.3 => 1.0.3 
    @aws-amplify/ui-components: ^1.0.3 => 1.0.3 
    @swimlane/ngx-charts: ^16.0.0 => 16.0.0 
    @types/jasmine: ~3.6.3 => 3.6.3 
    @types/jasminewd2: ~2.0.8 => 2.0.8 
    @types/node: ^12.20.1 => 12.20.1 
    @w11k/git-info: ^1.0.2 => 1.0.2 
    aws-amplify: ^3.3.21 => 3.3.21 
    codelyzer: ^6.0.1 => 6.0.1 
    file-saver: ~2.0.5 => 2.0.5 
    file-type: ^16.2.0 => 16.2.0 
    fs-extra: 6.0.1 => 6.0.1 
    git-describe: 4.0.4 => 4.0.4 
    jasmine-core: ~3.6.0 => 3.6.0 
    jasmine-spec-reporter: ~5.0.2 => 5.0.2 
    karma: ~5.2.3 => 5.2.3 
    karma-chrome-launcher: ~3.1.0 => 3.1.0 
    karma-coverage-istanbul-reporter: ~3.0.3 => 3.0.3 
    karma-jasmine: ~4.0.1 => 4.0.1 
    karma-jasmine-html-reporter: ^1.5.4 => 1.5.4 
    less: ^4.1.1 => 4.1.1 
    moment: ^2.29.1 => 2.29.1 
    nanoid: ^3.1.20 => 3.1.20 
    ng2-currency-mask: ^9.0.2 => 9.0.2 
    ngx-awesome-uploader: ^10.0.4 => 10.0.4 
    ngx-filesize: ^2.0.16 => 2.0.16 
    ngx-mask: ^11.1.4 => 11.1.4 
    performant-array-to-tree: ^1.8.1 => 1.8.1 
    protractor: ~7.0.0 => 7.0.0 
    rxjs: ~6.6.3 => 6.6.3 
    ts-node: ~9.1.1 => 9.1.1 
    tslib: ^2.1.0 => 2.1.0 
    tslint: ~6.1.3 => 6.1.3 
    typescript: ~4.1.5 => 4.1.5 
    webpack-bundle-analyzer: ^4.4.0 => 4.4.0 
    zone.js: ~0.11.4 => 0.11.4 
  npmGlobalPackages:
    @aws-amplify/cli: 4.44.1
    jsdoc: 3.6.6
    npm: 7.6.0
```

</details>

**Additional context**

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

**Comment by piotr-zielinski-lab** [comment]
Seems like it is the same problem as described here: #5782 and #6782

**Comment by wlee221** [comment]
As pointed out by @piotr-zielinski-lab, this is the same problem as #5782 so we will track the issue there. Please see https://github.com/aws-amplify/amplify-js/issues/5782#issuecomment-826968238 for more detail as well.
