### ISSUE TITLE
Issues with using Hosted UI in Angular

### ISSUE THREAD

**Issue by dppower** [aws-amplify/amplify-js#784]
(1) In an Angular 5 app, I had set up a CanActivate Route Guard to redirect if there is not a valid user session, it works as expected when signing in with username/password but when google login via hosted ui, the user is not valid until after this route guard is run. It will work as expected after the page is refreshed, or I put a setTimeout of 1 second before I call currentAuthenticatedUser.

```
import { Injectable } from '@angular/core';
import { CanActivate, ActivatedRouteSnapshot, RouterStateSnapshot, Router } from '@angular/router';
import { AwsAuthService } from "./aws-auth.service";

@Injectable()
export class AuthGuardService implements CanActivate {

    constructor(private router_: Router, private auth_service_: AwsAuthService) { };

    canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) {     
        return this.auth_service_.auth.currentAuthenticatedUser()
        .then(user => {
            return true;
        })
        .catch(err => {
            this.router_.navigate(["/auth/sign-in"]);
            return false
        });
    };
}
```

(2) The other issue is that the redirectSignOut when adding oauth to AuthOptions. Is this required for hosted ui, and can't be made optional? I'd prefer to use angular router to redirect when user signs out, rather than triggering a page refresh if it can be avoided, can use the router to navigate when not using hosted ui.

**Comment by haverchuck** [comment]
@dppower Are you using the code flow for the hosted UI?

**Comment by powerful23** [comment]
Closing this issue due to no further response. Please feel free to reopen if you still have this issue.
