### ISSUE TITLE
PubSub Documentation incorrect

### ISSUE THREAD

**Issue by rogueturnip** [aws-amplify/amplify-js#785]
The screen that shows how to create a policy is incorrect.

In the screen it has the action set to iot:* you must set the resource to *.  Restricting the topic with iot:* causes all the iot actions to be restricted to that but it makes no sense for things like connect.

**Comment by elorzafe** [comment]
@rogueturnip we updated the docs https://aws-amplify.github.io/docs/js/pubsub I will close the issue for now, but feel free to reopen or create a new one. Thanks!
