### ISSUE TITLE
Web Components Requires ui-vue ?

### ISSUE THREAD

**Issue by allcentury** [aws-amplify/amplify-js#7856]
**Describe the bug**

According to the docs here:  https://github.com/aws-amplify/amplify-js/blob/main/packages/amplify-ui-components/Readme.md#web-components

```js
import '@aws-amplify/ui-vue';
import Amplify from 'aws-amplify';
import awsconfig from './aws-exports';

Amplify.configure(awsconfig);
```

install instructions

```
yarn add aws-amplify@ui-preview @aws-amplify/ui-components@ui-preview
```

Web Components requires the ui-vue import but it is not part of the installation instructions.  Is the import required or is there a way to do this without `ui-vue`?

**Comment by wlee221** [comment]
Hi @allcentury! You can define web components this without @aws-amplify/ui-vue. In your entry file:

```ts
import { 
  applyPolyfills,
  defineCustomElements
} from '@aws-amplify/ui-components/loader';

import Amplify from 'aws-amplify';
import awsconfig from './aws-exports';
Amplify.configure(awsconfig);

applyPolyfills().then(() => {
  defineCustomElements(window);
});
```
This is what `ui-vue` does under the hood, but I see that it doesn't make much semantic sense. 

ps. we see that our readme documentation is outdated; `ui-components` is now stable and you can just use 
```
yarn add aws-amplify @aws-amplify/ui-components
```
We will update our docs accordingly.

**Comment by allcentury** [comment]
@wlee221 thanks for the quick response!
