### ISSUE TITLE
InAppBrowser get closed when Google 2FA prompt is shown and cancel login in android, react-native

### ISSUE THREAD

**Issue by mynameisguy** [aws-amplify/amplify-js#7863]
**Describe the bug**ֿ

When trying to login using Google social provider with the following conditions:
* the account is connected to the android phone
* the account is using 2FA
* the login is done using an in app browser
it fails.

When the android phone pops the prompt to approve the 2FA the in app browser is closed with the type='cancel'

I encounter this behavior on multiple android phones.

it works for any of these options:
* iOS phone
* Account without 2FA
* logging through Hosted UI Endpoint in the android phone
* Using `Linking.openURL` instead of in app browser

**To Reproduce**

1. Using an Android phone connected to google account xxx@gmail.com with 2FA enabled, try to use federated login using Google.
2. After the phone prompt you with the option to approve the login, the in-app browser closes and bring you back to the login screen

**Expected behavior**
It should fire the login event.

**Code Snippet**

login button:
`Auth.federatedSignIn({provider: 'Google'})`

awsconfig.oauth:
```
async function urlOpener(url, redirectUrl) {
    console.log('-------------------urlOpener entry');
    if (url.includes('logout')) {
        return await fetch(url)
            .then(() => {})
            .catch(() => {});
    } else {
        console.log('-------------------urlOpener else');
        await InAppBrowser.isAvailable();
        const {type, url: newUrl} = await InAppBrowser.openAuth(
            url,
            redirectUrl,
            {
                showTitle: false,
                enableUrlBarHiding: true,
                enableDefaultShare: false,
                ephemeralWebSession: false,
            },
        );
        console.log('-------------------urlOpener end', type, newUrl);

        if (type === 'success') {
            Linking.openURL(newUrl);
        }
    }
}

awsconfig.oauth.urlOpener = urlOpener;
awsconfig.oauth.domain = 'auth.domain.com';
Amplify.configure(awsconfig);
```

<details>
  <summary><strong>Environment</strong></summary>

  npmPackages:
    aws-amplify: ^3.3.21 => 3.3.21
    aws-amplify-react-native: ^4.3.1 => 4.3.1
    react-native-inappbrowser-reborn: ^3.5.1 => 3.5.1,
  npmGlobalPackages:
    @aws-amplify/cli: 4.44.0
    npm: 7.5.3

</details>

**Additional context**
logs:
```
LOG      {"attributes": {"appState": "active"}, "metrics": {}, "name": "app changed state"}
LOG      [DEBUG] 44:00.74 AuthClass - cannot load federated user from auth storage
LOG      [DEBUG] 44:00.75 AuthClass - get current authenticated userpool user
LOG      [DEBUG] 44:00.77 AuthClass - cannot load federated user from auth storage
LOG      [DEBUG] 44:00.77 AuthClass - get current authenticated userpool user
LOG      [DEBUG] 44:00.82 AuthClass - Failed to get user from user pool
LOG      [DEBUG] 44:00.84 AuthClass - Failed to get user from user pool
LOG      [DEBUG] 44:00.84 AuthClass - The user is not authenticated by the error No current user
LOG      [DEBUG] 44:00.85 AuthClass - The user is not authenticated by the error No current user
LOG      [DEBUG] 44:00.88 AnalyticsClass - Analytics has been disabled
LOG      {"attributes": {"button": "Google", "screen": "Auth"}, "metrics": {}, "name": "clicked button"}
LOG      [DEBUG] 44:12.265 OAuth - Redirecting to https://auth.domain.com/oauth2/authorize?*****************
LOG      -------------------urlOpener entry
LOG      -------------------urlOpener else
LOG      [DEBUG] 44:12.321 SessionTracker - App has come to inactive/background, recording stop session
LOG      [DEBUG] 44:12.321 AnalyticsClass - Analytics has been disabled
LOG      {"attributes": {"appState": "background"}, "metrics": {}, "name": "app changed state"}
LOG      [DEBUG] 44:38.156 SessionTracker - App has come to the foreground, recording start session
LOG      [DEBUG] 44:38.157 AnalyticsClass - Analytics has been disabled
LOG      [DEBUG] 44:38.159 urlListener - urlListener {"url": null}
LOG      {"attributes": {"appState": "active"}, "metrics": {}, "name": "app changed state"}
LOG      -------------------urlOpener end cancel undefined
```

**Is this a production issue?**
Are you experiencing this issue with a production application where end users are affected?

- [x] (check box if yes)

**Comment by amhinson** [comment]
It sounds like this might be an issue with [react-native-inappbrowser](https://github.com/proyecto26/react-native-inappbrowser), since the browser is being closed on its own, but I could be wrong there. Just for testing, would you be able to see if the same behavior happens without using the in-app browser?

**Comment by mynameisguy** [comment]
You are right. it's a react-native-inappbrowser issue.

for anyone who is seeing this, the solution is described here: https://github.com/proyecto26/react-native-inappbrowser/issues/153#issuecomment-727833604

I do recommend that you will add this solution to your example that uses react-native-inappbrowser in your docs:  https://docs.amplify.aws/lib/auth/social/q/platform/js#full-samples


Thanks!
