### ISSUE TITLE
I want to customize my own authentication process, because I have my own authentication server. I use Vue to test functions. I encounter some problems, like a bug

### ISSUE THREAD

**Issue by wedreamer** [aws-amplify/amplify-js#7865]
this is app.vue
```vue
<template>
  <amplify-authenticator>
    <amplify-sign-up
      slot="sign-up"
      username-alias="email"
      :form-fields.prop="formFields"
    ></amplify-sign-up>
    <amplify-sign-in slot="sign-in" header-text="My Custom Sign In Tex" username-alias="email" :handle-submit="signIn" submit-button-text="ok"></amplify-sign-in>
  </amplify-authenticator>
</template>

<script>
export default {
  name: "app",
  data() {
    return {
      formFields: [
        {
          type: "email",
          label: "Custom email Label",
          placeholder: "custom email placeholder",
          required: true,
        },
        {
          type: "password",
          label: "Custom Password Label",
          placeholder: "custom password placeholder",
          required: true,
        },
        {
          type: "address",
          label: "Custom Address Label",
          placeholder: "Enter your address",
          required: false,
        },
      ],
    };
  },
  methods: {
    async signUp() {
      debugger
      try {
        // const { user } = await Auth.signUp({
        //   username,
        //   password,
        //   attributes: {
        //     email, // optional
        //     phone_number, // optional - E.164 number convention
        //     // other custom attributes
        //   },
        // });
        // console.log(user);
      } catch (error) {
        console.log("error signing up:", error);
      }
    },
    async signIn() {
      debugger
      try {
        // const user = await Auth.signIn(username, password);
      } catch (error) {
        console.log("error signing in", error);
      }
    },
    async resendConfirmationCode() {
      try {
        // await Auth.resendSignUp(username);
        console.log("code resent successfully");
      } catch (err) {
        console.log("error resending code: ", err);
      }
    },
    async signOut() {
      try {
        // await Auth.signOut();
      } catch (error) {
        console.log("error signing out: ", error);
      }
    },
  },
};
</script>
```

[docs link](https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue#sign-in)

When I click the submit button to log in, I don't get the expected result - trigger breakpoint, on the contrary, execute it Auth.signIn I don't want to, because I have my own authentication server. So I tried to pass in handle submit and it didn't work. Please help me

**Comment by ErikCH** [comment]
Hi @wedreamer 

To override sign-in you have to setup the prop on your sign-in like this.

`:handleSubmit.prop="signIn"`

Please try that, and let us know!

**Comment by juancpgo** [comment]
> Hi @wedreamer
> 
> To override the submit you have to setup the prop on your sign-in like this.
> 
> `:handleSubmit.prop="signIn"`
> 
> Please try that, and let us know!

Does that work for web components too?

(meaning: I'm not using any of the typical frameworks, only the "bare" web component)

**Comment by ErikCH** [comment]
> > Hi @wedreamer
> > To override the submit you have to setup the prop on your sign-in like this.
> > `:handleSubmit.prop="signIn"`
> > Please try that, and let us know!
> 
> Does that work for web components too?
> 
> (meaning: I'm not using any of the typical frameworks, only the "bare" web component)

For web components you wouldn't add the `:` to the front. That is Vue specific. It should work without the `.prop`

**Comment by chrisbonifacio** [comment]
@wedreamer closing this for now as we have not heard back from you. Please re-open if you are still experiencing this issue and require additional assistance.
