### ISSUE TITLE
Auth.signIn error (0, s.default) is not a function. (in '(0, s.default)(t.bytelength)','(0,s.default)' is undefined)

### ISSUE THREAD

**Issue by ZeeshanSafdar93** [aws-amplify/amplify-js#7875]
Hi All, I am using React Native and Expo cli to build an AWS Amplify cognito app. It works fine locally but gives the following error when I install it on my phone.
 
Auth.signIn error :
 (0, s.default) is not a function. (in '(0, s.default)(t.bytelength)','(0,s.default)' is undefined)

- Device: [Samsung Note 10]
- OS: [Android 11]

**Comment by danieloi** [comment]
I have the exact issue! 

How did you solve this?

Please and thank you!

**Comment by ZeeshanSafdar93** [comment]
Use Mananged Workflow. It worked for me
![image](https://user-images.githubusercontent.com/74564398/114524665-b2b7d280-9c45-11eb-9150-2f2fd3d9cfae.png)

**Comment by danieloi** [comment]
This comment did it for me 
https://github.com/aws-amplify/amplify-js/issues/7191#issuecomment-728234443

**Comment by ZeeshanSafdar93** [comment]
I did that. It didn't worked for me

**Comment by zero-t4** [comment]
> I did that. It didn't worked for me

It really solves the problem, maybe you were using `npm` instead of `yarn`?
