### ISSUE TITLE
API- error undefined - Most infuriating bug ever

### ISSUE THREAD

**Issue by amlcodes** [aws-amplify/amplify-js#7878]
I dont know at this point anymore. I have done everything, lock files, node modules, cache, etc. pulled my amplify app. Any time I use my api, I get a credential error when trying to use IAM, and an undefined error when using cognito. no where to go, cloudwatch logs are all clean.  NEXTJS

**Comment by amlcodes** [comment]
looks like nothing is being ready by amplify.configure()

**Comment by nubpro** [comment]
Can u take a screenshot of the error you're getting?

**Comment by amlcodes** [comment]
@nubpro literally "undefined" is my error if i use cognito user pools as my authmode. 

if I use graphqloperation() which should assume my default provider (cognito),  it will try to use IAM, which tells me it looks like Amplify.configure(awsexport) or Amplify.configure({...awsexport, ssr: true}) on my nexjs page or _app.js is not being recognized.  Happens during literally any client side api request using Cognito -  however  when using SSR.API using IAM and getServerSideProps() while loading the same page, the request succeeds. 

Client side api requests using iam fails with "error no credentials" 
Client side api requests using cognito fail with "undefined" as error in a try/catch
server side api requsts using iam succeeds as normal. 

```try {

        await API.graphql(
          graphqlOperation(createContent, {
            input: {
              id: id
            },
          })
        )
      } catch (error) {
        console.log({ error })
      }
```

**Comment by amlcodes** [comment]
This makes absolutely  zero sense to me. I have tried cloning my repo and pulling my app, and I get the same results. I used previously working package.json deps, and it does the same.

**Comment by amlcodes** [comment]
To reiterate: This is a horrendous bug and has completely halted the project. Running queries or mutations server side with getServerSideProps with NEXTJS and SSR.API importing from 'aws-ampilfy' works, as well as IAM or Cognito User Pools requests in the Appsync Queries Console.

When making any client side request with API importing from 'aws-amplify' - explicitly using 'AMAZON_COGNITO_USER_POOLS' as authMode, I will catch an error - however it will be undefined and useless. If I use "AWS_IAM" as authMode or not set authMode, I will get an error "Error: no credentials". 

However I can remove my Amplify.configure line at _app.js as well as my /pages/page.js and see an error warning me amplify is not configured, just as well ssr requests stop working, as well as Auth.

For some reason API is not recognizing any configuration client side. I have set up a new project directory and this still occurs, I have removed package-lock.json, reverted back to a list of working package versions, delete and reinstall node_modules.


 ------------ WOW ------------- AMPLIFY CONSOLE just started to attempt DELETION on every one of my projects when I deleted just one from the console. That has got to be the most unfortunate bug.

**Comment by amlcodes** [comment]
I had created a package of useful amplify hooks, and left it in package.json ----- my b

**Comment by Shomari** [comment]
@amlcodes can you go into a bit more detail as to what happened with your package.json?  I'm facing a similar issue

**Comment by amlcodes** [comment]
I had a custom module as a dependency with outdated amplify dependencies
