### ISSUE TITLE
Refresh Handler not waiting for async method to complete execution to get latest token

### ISSUE THREAD

**Issue by Tanuja0064** [aws-amplify/amplify-js#7889]
**Describe the bug**
We have implemented 'Developer Authenticated Identities' authentication for third party logins. We have added the token generation code in lambda which gets called from API gateway.
We are sending the google token to lambda using API call which will validate the token and provide us with the cognito token for authenticated access to AWS resources. This flow is working as exptected.

The issue is, after 1 hour when the token expires we are catching it using the refreshhandler. But the refresh handler is not waiting for the API call to get the new token. 
The same code works when we implement the federated sign in flow with google token directly.

I have tried debugging the code, and we do receive the API response at some point of time but the refresh handler is not waiting for it. But the same call works on initial login.

**To Reproduce**
1. setup developer auth flow for login, google or cognito any will do
2. initial login works fine. We get the cognito token
3. for refresh token, we have written below logic:

//refresh handler initialization:
export const RefreshHandlers = {
  refreshHandlers: {
    ['cognito-identity.amazonaws.com']: async () => {
      return await Authentication.refresh();
    },
  },
};

//actual configuration call
 Auth.configure({
        ...config,
        ...RefreshHandlers,
      });

//refresh method to get token from lambda
static async refresh(): Promise<FederatedResponse | undefined> {
  return new Promise<FederatedResponse | undefined>(async (resolve, reject) => {
    // API call to get latest token
  });
}

5. after timeout, if we refresh the app the refresh method gets called, but it does not wait for API completion.

**Expected behavior**
refresh call should work similar to initial authentication call.

**Code Snippet**
Please provide a code snippet or a link to sample code of the issue you are experiencing to help us reproduce the issue. (Be sure to remove any sensitive data)

**Screenshots**

**What is Configured?**
@aws-amplify/auth - 3.3.4
OS- Windows 10
device - Android

**Comment by chrisbonifacio** [comment]
Hi :wave: Sorry this was auto-closed by stale bot. We are working towards preventing this from happening in the future. Please let us know if you are still experiencing this issue and in need of assistance.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!
