### ISSUE TITLE
After verifyTotpToken - using setPreferredMFA will lead to NotAuthorizedException in all actions afterwards

### ISSUE THREAD

**Issue by doron-mil** [aws-amplify/amplify-js#7893]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Is this a production issue?

- [ ] (check box if yes)

### JavaScript Framework

Vue

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

```
npx: installed 1 in 3.72s

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 94.77 MB / 16.00 GB
    Shell: 5.0.18 - /usr/local/bin/bash
  Binaries:
    Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
  Browsers:
    Chrome: 88.0.4324.192
    Firefox: 82.0.2
    Safari: 14.0
  npmPackages:
    @quasar/app: ^1.0.0 => 1.8.10
    @quasar/extras: ^1.0.0 => 1.8.1
    @quasar/quasar-app-extension-dotenv: ^1.0.1 => 1.0.1
    aws-amplify: ^3.3.22 => 3.3.22
    aws-sdk: ^2.746.0 => 2.856.0
    babel-eslint: ^10.0.1 => 10.1.0
    eslint: ^6.8.0 => 6.8.0
    eslint-config-airbnb-base: ^14.0.0 => 14.1.0
    eslint-loader: ^3.0.3 => 3.0.4
    eslint-plugin-import: ^2.20.1 => 2.20.2
    eslint-plugin-vue: ^6.1.2 => 6.2.2
    github-markdown-css: ^4.0.0 => 4.0.0
    lodash: ^4.17.20 => 4.17.20
    otpauth: ^6.2.2 => 6.2.2
    qrcode.vue: ^1.7.0 => 1.7.0
    quasar: ^1.0.0 => 1.11.3
    vue-markdown: ^2.2.4 => 2.2.4
  npmGlobalPackages:
    @vue/cli: 4.5.11
    npm: 6.14.5
    recursive-install: 1.4.0
    serverless: 2.11.1
```

### Describe the bug

I have an application that is using totp setup.
All is working except for the initial sign-in with totp setup.
If the user logout and re-login everything is working as well.

The problem arrises only on the first sign in.
I have the code :
`Auth.verifyTotpToken(user,  totp).then(() => {`
         ` Auth.setPreferredMFA(user, 'TOTP')`
`....`
`});`

Every action that I'm doing afterwards using Auth will result in NotAuthorizedException.
The Amplify Hub doesn't indicate sign-out, but it does indicate tokenRefresh_failure events.

I've tried to not use the setPreferredMFA, because the MFA is already set as needed (checked) - but then, if the user tries something like Auth.updateUserAttributes, the same problem arises and user is cut from possible way to retain Auth.currentAuthenticatedUser()

Does anyone know where is all this coming from ? Maybe a configuration problem in AWS ?

### Expected behavior

After calling verifyTotpToken and setPreferredMFA to be able to get currentAuthenticatedUser

### Reproduction steps

1. Auth.signIn(username, password)
2. Auth.completeNewPassword(user, newPassword)
3. Auth.signIn(username, password)
4. Auth.setupTOTP(user)
5. Auth.verifyTotpToken(user, totp) => Auth.setPreferredMFA(user, 'TOTP')

### Code Snippet

```javascript
// Put your code below this line.
```

### Log output

`Auth.verifyTotpToken(user,  totp).then(() => {`
         ` Auth.setPreferredMFA(user, 'TOTP')`
`....`
`});`

**Comment by vimkp** [comment]
Hello @amhinson and @chrisbonifacio 
Thanks for taking a look, I was wondering if you had any luck reproducing this?

**Comment by chrisbonifacio** [comment]
Hi :wave: Sorry this was auto-closed by stale bot. We are working towards preventing this from happening in the future. Please let us know if you are still experiencing this issue and in need of assistance.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!

**Comment by kevinduke10** [comment]
I'm seeing the same behavior.
"aws-amplify": "^4.2.3"

I verify the Totp Token with 
```
Auth.verifyTotpToken(user, code)
```

My Hub is listening for auth events and sees the 'signIn' event and sets the user that appears correct. 
```
Hub.listen('auth', ({payload: {event, data}}) => {
            console.log("HUB SEES EVENT")
            console.log(event)
            console.log(data)
            switch (event) {
                case 'signIn':
                case 'cognitoHostedUI':
                    setUser(data)
....
```

After this first login, if I ask for the current session it seems to be valid.
```
Auth.currentSession()
            .then(result => {
                console.log("Session")
                console.log(result)
            })
```

But when I subsequently ask for the current authenticated user I see a 'tokenRefresh_failure' come across the Hub
```
Auth.currentAuthenticatedUser({
            bypassCache: true
        })
```
If I remove the bypassCache it will successfully returns the cached user.

On page refresh, I see that no user is auth'ed and I'm forced to login again but once I successfully login, everything works as expected.
