### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by volkanunsal** [aws-amplify/amplify-js#7901]
**Describe the bug**

There are several `require`s in DataStore source code. It causes this error:

```
Uncaught ReferenceError: require is not defined
```

Here is a screenshot from the Dev Tools:

![Screen Shot 2021-03-07 at 4 13 34 PM](https://user-images.githubusercontent.com/151600/110255152-5d124b00-7f60-11eb-8f3f-9119b42b7fcf.png)

**What is Configured?**

I'm using the latest version of amplify-js,  i.e. 3.3.22.

This is the file where it is coming from:

https://github.com/aws-amplify/amplify-js/blob/8fa348b8ba708434992d97557b0fceebbf7abe9a/packages/datastore/src/storage/adapter/getDefaultAdapter/index.ts

**Comment by iartemiev** [comment]
Which browser/platform are you getting this error in? Which framework or build tool are you using?

**Comment by volkanunsal** [comment]
I'm using Snowpack bundler, which uses esbuild. It uses the `lib-esm` folder of the project to load the code, which should contain only ESM code, and that's why it's not using interop for require statements. Configuring interop would be difficult for a single dependency, so it'd be great if it were changed at the source.

**Comment by iartemiev** [comment]
I see. We're using `require` in that file to conditionally import the necessary storage adapter. Once dynamic imports for ESM modules reaches sufficient cross-browser stability, we can migrate to using those instead.

**Comment by volkanunsal** [comment]
What is the reasoning for importing them conditionally? Is it the file size? Or do they have a side effect or something?

**Comment by iartemiev** [comment]
Mainly file size, as AsyncStorage has upstream dependencies that are not needed on web

**Comment by volkanunsal** [comment]
> Once dynamic imports for ESM modules reaches sufficient cross-browser stability, we can migrate to using those instead.

The main issue for me here is that this is not standards compliant ESM. There are two compilation targets for this project. If you were to use `import('...')`, it would be transformed into `require('...')` for the CJS target, and developers who are concerned about supporting legacy browser would use that. 

The developers who target ESNext now have no other choice but to fork the project to use DataStore.

**Comment by iartemiev** [comment]
That's fair. Most of our customers rely on Webpack (via CRA, @angular/cli, etc.), and by default the ESM modules with those get transpiled further, so it's not an issue in most cases. I would be resistant to changing the conditional `require` behavior as that would introduce a breaking change (all customers would need to install React Native dependencies in order to upgrade). 

However, it looks like ESM Dynamic Imports are now supported by > 3 major versions in all major browsers, so we should be able to start using that feature. We'll look into refactoring any conditional `require` statements into ESM Dynamic Imports.

**Comment by niwasmala** [comment]
Is there any update on this? I'm having same problem when using Svelte Kit, Vite, and AWS Amplify DataStore. 
Any ideas how to temporary solve this?
