### ISSUE TITLE
[aws-amplify-react] truthy value cannot be passed to the "preview" prop of <PhotoPicker> on TypeScript

### ISSUE THREAD

**Issue by matsuby** [aws-amplify/amplify-js#7908]
**Describe the bug**
```
import { PhotoPicker } from 'aws-amplify-react'

const A = () => <PhotoPicker preview />
```
TypeScript compiler output error.
`Type 'true' is not assignable to type '"hidden" | undefined'.ts(2322)`

TypeScript user cannot pass truthy value to "preview" prop. 
It's only accept `undefined` or `'hidden'`.

I think I need to add a boolean type to the Union Type with a default value of false.

#### preview prop Type
https://github.com/aws-amplify/amplify-js/blob/83273b1030f544fbb84e8a0751611d189d23675b/packages/aws-amplify-react/src/Widget/PhotoPicker.tsx#L37

#### in handlePick()
https://github.com/aws-amplify/amplify-js/blob/83273b1030f544fbb84e8a0751611d189d23675b/packages/aws-amplify-react/src/Widget/PhotoPicker.tsx#L70-L81

#### in render()
https://github.com/aws-amplify/amplify-js/blob/83273b1030f544fbb84e8a0751611d189d23675b/packages/aws-amplify-react/src/Widget/PhotoPicker.tsx#L96
https://github.com/aws-amplify/amplify-js/blob/83273b1030f544fbb84e8a0751611d189d23675b/packages/aws-amplify-react/src/Widget/PhotoPicker.tsx#L104-L112

**Expected behavior**
* "preview" prop accept true and false 
* disable preview feature when "preview" prop are undefined

---

**addition**
preview = "hidden" was not tested, instead passed boolean value.
https://github.com/aws-amplify/amplify-js/blob/main/packages/aws-amplify-react/__tests__/Widget/PhotoPicker-test.tsx

**Comment by eddiekeller** [comment]
Hi @matsuby , I'm wondering if you can provide some more context on the ask and why you want to pass a boolean to the prop?

Here is the React docs for the component in case you haven't seen them - https://docs.amplify.aws/ui-legacy/storage/photo-picker/q/framework/react

**Comment by matsuby** [comment]
@eddiekeller thanks for reply and telling me the location of the documentation.
As written there, "preview" is passed without a value.
```
To display a preview, you can use preview directive:

<PhotoPicker preview onLoad={dataURL => console.log(dataURL)} />
```
React doc says, [If you pass no value for a prop, it defaults to true.](https://reactjs.org/docs/jsx-in-depth.html#props-default-to-true)
so I think "preview" should support boolean value, is it wrong?

**Comment by eddiekeller** [comment]
I see, so it sounds like what you are asking is for the value of the prop to be a `boolean` *instead of* a string. Is that accurate? So if you want the preview to be hidden, you would pass in `preview={false}` instead of `preview={'hidden'}`?

If I'm understanding that correctly, then I think I agree with you. A boolean makes more sense to me. However, this component was made quite a few years ago (before I joined the team), so I don't have a ton of context on *why* this prop was set up like this. Let me chat with my team and see if I can get some more info.

**Comment by eddiekeller** [comment]
@matsuby I approved the PR. Looks good to me! :)

**Comment by eddiekeller** [comment]
Merged in your change @matsuby . Thank you for your contribution!
