### ISSUE TITLE
is it possible to skip email confirmation when user update his email ?

### ISSUE THREAD

**Issue by Jasminou** [aws-amplify/amplify-js#791]
Do you want to request a feature or report a bug?
question
What is the current behavior?
when user update his email, I setup a custom lambda trigger to manage this workflow, however, I would like to confirm the user and set the email_verifid to true withtout sending an email confirmation to the user. is it possible ?

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

What is the expected behavior?

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by mlabieniec** [comment]
@Jasminou apologies for the delay on this question. You could technically achieve this when using the AWS JavaScript SDK via the Lambda function assuming your lambda has the appropriate permissions to call the Cognito API and do this.  More docs on that here: 
https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html

Feel free to re-open this if you need further help regarding the usage of the Amplify-js lib
