### ISSUE TITLE
error 304 - incompleteSignatureException when passing Cognito headers to Amplify Rest Api

### ISSUE THREAD

**Issue by ZalgirisKaunas** [aws-amplify/amplify-js#7911]
I really need to access the user group names of the user pool in the rest API lambda functions but I'm not sure how to do that. I've tried to pass the JWT token in the authorization header like that:

```
const user = await Auth.currentAuthenticatedUser();
const token = user.signInUserSession.idToken.jwtToken;

const result = await API.get(data.apiName, data.dbPath, {
  headers: {
    Authorization: token,
  },
});
```

but it returned incompleteSignatureException from cloudfront. 

I've also tried

```
      headers: { 
        Authorization: `Bearer ${(await Auth.currentSession()).getIdToken().getJwtToken()}`,
      },
```

and without  `Bearer ` but error is always the same. 
It is also interesting that passing the authorization header to Admin Queries API works fine and it's possible to get group names from the request context in there.

**Comment by volkanunsal** [comment]
I was having the same issue today. It turns out that the `authenticationType` field was set to `AWS_IAM`, instead of `AMAZON_COGNITO_USER_POOLS`. If you try updating from the CLI, it doesn't work. You have to update it from the AppSync console –– under Settings. 

This is the configuration that worked for me:

![Screen Shot 2021-03-09 at 8 25 32 AM](https://user-images.githubusercontent.com/151600/110477524-429bb700-80b1-11eb-8882-92522d6ec018.png)

**Comment by ZalgirisKaunas** [comment]
I'm not using appSync or GraphQl so I went to my API gateway selected my database function and added a Cognito user pool authorizer. I've changed AWS_IAM on both '/items' and '/{proxy}' to use that authorizer and now I'm getting different error that says 'UnauthorizedException'

**Comment by IsaacTrevino** [comment]
I'd like to avoid manually editing my API Gateway settings. As mentioned in my comment [#7906 ](https://github.com/aws-amplify/amplify-js/issues/7906)
I used the modular packages `@aws-amplify/api` and it seems to work for now, though It seems like `aws-amplify 3.3.23` is broken for api as of now.

**Comment by pedromagalhaes** [comment]
Solution https://github.com/aws-amplify/amplify-js/issues/7911#issuecomment-793897661 worked for me
