### ISSUE TITLE
Upgraded amplify version broke auth

### ISSUE THREAD

**Issue by imoby** [aws-amplify/amplify-js#7916]
**Describe the bug**
I've upgraded my aws-amplify version to the latest and my auth no longer seems to work and throws various errors that I can't seem to figure out where/why its going on. Reverting back to the older version works again.

Old:
"aws-amplify": "^3.0.20",
"aws-amplify-react-native": "^4.2.1",

New:
"aws-amplify": "3.3.23",
"aws-amplify-react-native": "^4.3.1",

I'm using the sign in/signup functionality the same way its mentioned in the docs online. Below are the two different errors that the sign in method is throwing at me:

`[TypeError: (0, _getRandomBase.default) is not a function. (In '(0, _getRandomBase.default)(array.byteLength)', '(0, _getRandomBase.default)' is undefined)]
`

And after getting that error and attempting to sign in again, it throws this:

`
[Error: Pending sign-in attempt already in progress]
`
**To Reproduce**

1. Upgrade from older version of amplifyjs
2. Using the same docs to sign in, attempt to sign in
3. Error is thrown

**Expected behavior**
I should be able to login normally

**Code Snippet**
Please provide a code snippet or a link to sample code of the issue you are experiencing to help us reproduce the issue. (Be sure to remove any sensitive data)

**Screenshots**

**Comment by sammartinez** [comment]
Hello @imoby, Would you mind sharing a code snippet or screenshots of what you are experiencing? Also, can you provide your `package.json` along with your environment settings? 

Please use the follow command: 
```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

Thanks ahead of time!

**Comment by sammartinez** [comment]
In testing the documentation on our docs site, I cannot reproduce this issue. @imoby have you done a `rm -rf node_modules` and re-install your dependencies? You may also need to remove your `package-lock.json` or `yarn.lock` file if you have one. Please let us know how we can help you further.

**Comment by imoby** [comment]
@sammartinez Im going to give you some of the items you requested later today but I have definitely removed my node modules and lock and the issue still has happened.

**Comment by imoby** [comment]
I was able to update successfully after running a clean build but only through xcode directly. Not sure why a dependency like amplify would be affected there but so far things seem to be good now. if theres any update I'll post here.

**Comment by svidgen** [comment]
Is this working for you now? If not, are you using expo by chance?

The error in the OP seems the same as this one: https://github.com/aws-amplify/amplify-js/issues/8113

**Comment by svidgen** [comment]
@imoby, the changes from #8162 were published [late last week](https://www.npmjs.com/package/aws-amplify/v/3.4.0) and are expected to resolve this. Please update to the latest version and let us know if you're still having issues.

Thanks!
