### ISSUE TITLE
Reset Password in amplify is not working, throwing error "Invalid version. Version should be 1"

### ISSUE THREAD

**Issue by deepaknayak01** [aws-amplify/amplify-js#7920]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Is this a production issue?

- [X] (check box if yes)

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

storage

### Environment information

System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 16.80 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.11.0 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/Pto/Funnel/funnelrolodex-sharetribe/rolodex-frontend/node_modules/.bin/yarn
    npm: 7.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.192
    Firefox: 10.0.1
    Safari: 12.1.2
  npmPackages:
    @fortawesome/fontawesome-svg-core: ^1.2.30 => 1.2.34 
    @fortawesome/free-solid-svg-icons: ^5.14.0 => 5.15.2 
    @fortawesome/react-fontawesome: ^0.1.11 => 0.1.14 
    @hookform/error-message: ^0.0.5 => 0.0.5 
    @hookform/resolvers: ^0.1.0 => 0.1.1 
    @material-ui/core: ^4.11.0 => 4.11.2 
    @material-ui/icons: ^4.9.1 => 4.11.2 
    @material-ui/lab: ^4.0.0-alpha.56 => 4.0.0-alpha.57 
    @reduxjs/toolkit: ^1.4.0 => 1.5.0 
    @testing-library/jest-dom: ^4.2.4 => 4.2.4 
    @testing-library/react: ^9.3.2 => 9.5.0 
    @testing-library/user-event: ^7.1.2 => 7.2.1 
    add: ^2.0.6 => 2.0.6 
    aws-amplify: ^3.3.3 => 3.3.12 
    axios: ^0.20.0 => 0.20.0 
    chart.js: ^2.9.4 => 2.9.4 
    classnames: ^2.2.6 => 2.2.6 
    draft-js: ^0.11.7 => 0.11.7 
    draft-js-plugins-editor: ^3.0.0 => 3.0.0 
    draftjs-to-html: ^0.9.1 => 0.9.1 
    escape-json-node: ^2.0.0 => 2.0.0 
    eslint: ^6.8.0 => 6.8.0 
    eslint-config-airbnb: ^18.1.0 => 18.2.1 
    eslint-config-prettier: ^6.12.0 => 6.15.0 
    eslint-plugin-css-modules: ^2.11.0 => 2.11.0 
    eslint-plugin-import: ^2.20.2 => 2.22.1 
    eslint-plugin-jsx-a11y: ^6.2.3 => 6.4.1 
    eslint-plugin-prettier: ^3.1.4 => 3.3.0 
    eslint-plugin-react: ^7.20.0 => 7.21.5 
    eslint-plugin-react-hooks: ^4.1.2 => 4.2.0 
    html-react-parser: ^0.14.0 => 0.14.3 
    material-ui-phone-number: ^2.2.6 => 2.2.6 
    moment: ^2.29.1 => 2.29.1 
    node-sass: ^4.14.1 => 4.14.1 
    prop-types: ^15.7.2 => 15.7.2 
    query-string: ^6.13.1 => 6.13.7 
    quill: ^1.3.7 => 1.3.7 
    react: ^16.13.1 => 16.14.0 
    react-alert: ^7.0.2 => 7.0.2 
    react-chartjs-2: ^2.10.0 => 2.11.1 
    react-dates: ^21.8.0 => 21.8.0 
    react-dom: ^16.13.1 => 16.14.0 
    react-draft-wysiwyg: ^1.14.5 => 1.14.5 
    react-dropzone: ^11.2.4 => 11.3.1 
    react-hook-form: ^6.3.0 => 6.13.0 
    react-image-gallery: ^1.0.8 => 1.0.8 
    react-media: ^1.10.0 => 1.10.0 
    react-phone-input: ^1.2.1 => 1.2.1 
    react-phone-input-2: ^2.13.9 => 2.13.9 
    react-player: ^2.7.2 => 2.7.2 
    react-query: ^2.25.2 => 2.26.4 
    react-query-devtools: ^2.6.0 => 2.6.3 
    react-quilljs: ^1.2.11 => 1.2.13 
    react-redux: ^7.2.1 => 7.2.2 
    react-responsive: ^8.1.0 => 8.2.0 
    react-responsive-carousel: ^3.2.9 => 3.2.11 
    react-router-dom: ^5.2.0 => 5.2.0 
    react-scripts: 3.4.1 => 3.4.1 
    react-select-country-list: ^2.2.1 => 2.2.1 
    react-slick: ^0.27.11 => 0.27.13 
    redux: ^4.0.5 => 4.0.5 
    redux-saga: ^1.1.3 => 1.1.3 
    sharetribe-flex-sdk: ^1.11.0 => 1.13.0 
    slick-carousel: ^1.8.1 => 1.8.1 
    yarn: ^1.22.4 => 1.22.10 
    yup: ^0.29.3 => 0.29.3 
  npmGlobalPackages:
    @aws-amplify/cli: 4.44.2
    create-react-app: 3.4.1
    gulp: 4.0.2
    n: 7.0.2
    nodemon: 2.0.4
    npm: 7.6.0
    npx: 10.2.2

### Describe the bug

While trying to reset password through Amplify, it is throwing error "Invalid version. Version should be 1" (InvalidLambdaResponseException). Causing which app is not allowing user to reset the password.

Auth.forgotPasswordSubmit(username, code, new_password) -> POST payload is sending these parameters.

### Expected behavior

POST payload should get successfully saved with 200 status & replace the new password.

### Reproduction steps

1. User clicks on Forgot password button, by providing username or email.
2. OTP will be sent to user's email to reset the password.
3. User went to reset password page to provide OTP and new password.
4. Click on Submit in reset password page.

- User is getting error on submit as 'Invalid version. Version should be 1'

### Code Snippet

await Auth.forgotPasswordSubmit(username, OTP, new_password)
        .then(data => console.log(data))
        .catch(err => console.log(err));

### Log output

message: "Invalid version. Version should be 1"
__type: "InvalidLambdaResponseException"

### Mobile Operating System

iOS

**Comment by amhinson** [comment]
Thanks for the info! Could you also add some more detail regarding the reproduction steps? Particularly, what steps did you select with the CLI when setting up auth? Also, are you using any Lambda triggers?

**Comment by yogeshwar607** [comment]
> Thanks for the info! Could you also add some more detail regarding the reproduction steps? Particularly, what steps did you select with the CLI when setting up auth? Also, are you using any Lambda triggers?

@amhinson we used - `amplify import auth  `and imported existing cognito user pool & identity pool

We are using Lambda triggers but for this specific event Auth.forgotPasswordSubmit , we there is no lambda trigger and also in cognito trigger docs there is no such event

**Comment by amhinson** [comment]
Just to verify, do you have a trigger for `Post confirmation`?

![image](https://user-images.githubusercontent.com/17091790/110696621-262a7800-81a0-11eb-998d-5458b2d032fa.png)

This is the trigger used for the `ConfirmForgotPassword` action, which `Auth.forgotPasswordSubmit(...)` calls behind the scenes.

Cognito docs reference: https://docs.amazonaws.cn/cognito-user-identity-pools/latest/APIReference/API_ConfirmForgotPassword.html
