### ISSUE TITLE
Calling REST Api that requires auth from localhost has Credential=undefined

### ISSUE THREAD

**Issue by johanlantz** [aws-amplify/amplify-js#7921]
**Describe the bug**
I have a working amplify project (amplify is great) and today I have added authentication for my REST endpoint.

This works just fine if I run things in AWS but when I start my frontend locally my API calls fail and I see that in the Authorization header I have Credential=undefined

**To Reproduce**
npm run start in my frontend folder
The API calls all fail with CORS error but I think it is due to the failed authorization.
I see the preflight OPTIONS after the failed GET but that might just be due to the error I guess. 

**Expected behavior**
I can call my backend API's even if I am running the frontend locally. 
The Cognito sign-in works as expected but the API calls fail

**Code Snippet**
```
// This works if I run in AWS but not locally. The endpoint uri used is correct also locally
export const fetchData = async (apiName: string, path: string) => {
  const data = await API.get(apiName, path, null)
  return data
}
```
**Screenshots**
A GET with credential=undefined in Authorization header
![Screenshot 2021-03-10 at 18 28 32](https://user-images.githubusercontent.com/7461655/110671429-c7302780-81ce-11eb-8949-cf82a3dfaabf.png)

And the OPTIONS (coming after the failed GET at least in the log)
![Screenshot 2021-03-10 at 18 32 08](https://user-images.githubusercontent.com/7461655/110671758-30179f80-81cf-11eb-928f-e87d34adeeae.png)

**What is Configured?**
```
const aws_exports = require('../../aws-exports').default;

Amplify.configure(aws_exports);

// The below was not needed from the beginning but at some point auth stopped working in the cloud
// https://github.com/aws-amplify/amplify-js/issues/4315#issuecomment-785015032
// Adding these line fixed it
import { Auth } from '@aws-amplify/auth'
import { API } from 'aws-amplify'
Auth.configure(aws_exports)
API.configure(aws_exports)
```

```
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 145.40 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    npm: 6.14.8 - ~/.nvm/versions/node/v12.19.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 88.0.4324.192
    Firefox: 84.0.2
    Safari: 13.1
  npmGlobalPackages:
    @aws-amplify/cli: 4.41.1
    npm: 6.14.8
```

Additional context
Seems similar to [this](https://stackoverflow.com/a/55657227/1816142)

Again, this only happens locally.

All suggestions are welcome

**Comment by amhinson** [comment]
Could you describe a bit more about your API? What steps did you do to set it up with the CLI?

**Comment by johanlantz** [comment]
Hi @amhinson and thanks for the quick reply.

I have figured out the cause. My app is still under development and the hooks that called the API uses useEffect so they call immediately even if the user is not yet authenticated. That is fine but it meant that I always had to reload the page after I signed in. Now reloading the page works fine when I run towards the AWS instance but when running from localhost, after reloading the cognito credentials did not work anymore so while I was still Signed in on the webpage, the credentials needed to talk to the API did not work.

I do not know if this is expected behaviour when testing locally but it seems a bit strange. Perhaps you can see if you can reproduce it? I simply use this for auth (copied from some tutorial):

```
const AuthStateApp = () => {
  const [authState, setAuthState] = React.useState();
  const [user, setUser] = React.useState();
  React.useEffect(() => {
      return onAuthUIStateChange((nextAuthState, authData) => {
          setAuthState(nextAuthState);
          setUser(authData)
      });
  }, []);

return authState === AuthState.SignedIn && user ? (
    <div className="App">
        <App/>
        <AmplifySignOut />
    </div>
  ) : (
    <AmplifyAuthenticator>
      <AmplifySignUp
        slot="sign-up"
        usernameAlias="email"
        formFields={[
          { type: "email" },
          { type: "password" }
        ]}
      />
    </AmplifyAuthenticator>
);
}
```

and then I call the API with:
```
userEffect...
const data = await API.get(apiName, path, null)
```

and after reloading the page on localhost, the call to API.get always fail.

**Comment by amhinson** [comment]
Would it be possible to share a small sample repo that shows the behavior you're seeing, or some larger code samples? I really just want to make sure that we are testing it in the exact same way that you are experiencing the issue. I'm particularly interested in the files where you are using `Auth`, `API` and the Amplify UI Components.

As a side note, we recommend only having `aws-amplify` as a dependency and relying on tree-shaking to remove any unused modules. Using the modular dependencies in your app can lead to unexpected behavior, which might be what you were seeing here:

> // The below was not needed from the beginning but at some point auth stopped working in the cloud
// https://github.com/aws-amplify/amplify-js/issues/4315#issuecomment-785015032
// Adding these line fixed it
import { Auth } from '@aws-amplify/auth'
import { API } from 'aws-amplify'
Auth.configure(aws_exports)
API.configure(aws_exports)

This could also be related to the original issue you are facing.

**Comment by johanlantz** [comment]
Hi @amhinson 
I added your user to the project so you should have received an invite. I am not a webdeveloper so feel free to rant about anything weird you come across. Since the backend is already deployed, I think you should be ok to start the frontend. I pasted the aws_exports in the README since I guess you need that info.

**Comment by mauerbac** [comment]
Hey @johanlantz , coming back to this issue. Thanks for the feedback here. If you are still experiencing an issue please open a new issue.
