### ISSUE TITLE
`receiverID` null when input param `receiverID` is not null

### ISSUE THREAD

**Issue by osddeitf** [aws-amplify/amplify-js#7931]
**Describe the bug**
OnCreateSubscription return id null when creating input param not null.

**To Reproduce**

1. Create an OnCreateSubscription to the changes of my model - `Conversation`.
2. Create an instance of `Conversation` with `receiverID` not null.
3. See errors on data passed to the `next()` function: `data.receiver` is not null but `data.receiverID` is null.

**Expected behavior**
`data.receiverID` should be equal with `data.receiver.id`.

**Code Snippet**
Create data:
```js
const { data } = (await API.graphql(
  graphqlOperation(createConversation, {
    input: {
      authorID: "278361a7-e4ea-4edb-8251-d381b0d038cc",
      receiverID: "e8e7bd09-d645-41bd-9735-5d34894ee856"
    }
  } as CreateConversationMutationVariables)
)) as GraphQLResult<CreateConversationMutation>;
```
Subscription: 
```js
const [createConvo, updateConvo, deleteConvo] = threadSubscriptions();
const createConvoSub = createConvo.subscribe({
  next: data => {
    const res = data?.value?.data;
    console.log(res)
  }
});
```
The output of the above `console.log()` is:
```js
{ onUpdateConversation: {
    author: {id: "278361a7-e4ea-4edb-8251-d381b0d038cc", …}
    authorID: "278361a7-e4ea-4edb-8251-d381b0d038cc"
    createdAt: "2021-03-13T18:39:13.778Z"
    id: "bc0c3742-30c1-4ef2-ac6f-a865c781c891"
    receiver: {id: "e8e7bd09-d645-41bd-9735-5d34894ee856", …}
    receiverID: null
    updatedAt: "2021-03-13T20:05:21.921Z"
} }
```
You could easily see the `receiver` is not null whilst `receiverID` is null.
The `receiverID` is configured similar to`authorID` (I'm not sure how).
When I reload my website, the same `Conversation` instance is returned with the correct `receiverID`.

I cannot sure this is a bug or a misconfiguration, because I'm not the one who set things up, not that I have privileges in doing the updates either.
I'm truly sorry for jumping right away into this bug report. I have searched the existing issues but couldn't find any related ones. Please point me out if I'm mistaken my issue to be a bug.

**Comment by osddeitf** [comment]
Actually, when data is created, the `receiverId` response of that operation is `null`, not the fault of Subscription.

**Comment by chrisbonifacio** [comment]
Hi :wave: Sorry this was auto-closed by stale bot. We are working towards preventing this from happening in the future. Please let us know if you are still experiencing this issue and in need of assistance.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!
