### ISSUE TITLE
503 Error when invoking NextJS API Route from Client

### ISSUE THREAD

**Issue by felixs8696** [aws-amplify/amplify-js#7940]
**Describe the bug**
I am using Amplify's API functionality to invoke an AppSync GraphQL endpoint to resolve my API calls. But, I'm getting a GraphQL error message in my Lambda@Edge CloudWatch logs when trying to invoke my API in my application from the client side.

```
Error: No credentials
    at GraphQLAPIClass.<anonymous> (/var/task/pages/api/users/[username].js:163397:35)
    at step (/var/task/pages/api/users/[username].js:163243:23)
    at Object.next (/var/task/pages/api/users/[username].js:163224:53)
    at fulfilled (/var/task/pages/api/users/[username].js:163215:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

The weird thing is that when I try to execute the API's internal logic on the server side, everything works properly. So, this correctly retrieves and display all data in my application.

```
# pages/index.js
export const getServerSideProps = async ({ req, res }) => {
  const response = await API.graphql(graphqlOperation(UserQueries.GetUser, <username>))
  
  return {
    props: {
      user: response.data,
    },
  };
};
```

However, if if I invoke this api route, by going to `<app_id>.cloudfront.net/api/users/[username]`, I receive the following error page:

![503 Error Message from Application](https://user-images.githubusercontent.com/7238671/110446564-2fb6c180-8074-11eb-8dcb-35e541570d20.png)

```
# pages/api/users/[username]/index.js

const handler = async (req, res) => {
  const { username } = req.query.username;
  const response = await API.graphql(graphqlOperation(UserQueries.GetUser, <username>))
  res.status(200).json(response.data);
};
```

This tells me that I have set up my Cognito and identity pools correctly. For now I am just developing using an API Key, so I expect there to be no permissions barriers.

**To Reproduce**
1. Deploy a GraphQL API using CDK (separately, not using Amplify)
2. Create. NextJS application (https://nextjs.org/docs/getting-started)
3. Put the AppSync Endpoint URL in the config and set up a [custom "_app.js" file](https://nextjs.org/docs/advanced-features/custom-app) using `Amplify.configure(config);`
4. Add an API Route to the NextJS Application using the instructions here: https://nextjs.org/docs/api-routes/introduction.
5. Handle the API route by using Amplify's API client: `const response = await API.graphql(graphqlOperation(operation, params))`
6. Add a `serverless.yaml` at the root of the project with the following content:
```
# serverless.yml
App:
  component: "@sls-next/serverless-component@1.18.0"
```
7. Deploy the application by running the command `serverless`. See: https://github.com/serverless-nextjs/serverless-next.js
8. Go to https://<app_id>.cloudfront.net/api/<path_to_your_api_route>.

This will result in the 503 error above.

**Expected behavior**
API query response should be returned when invoked client side.

**Code Snippet**
N/A

**Screenshots**
![CloudWatch Log Stack Trace](https://user-images.githubusercontent.com/7238671/110446631-40ffce00-8074-11eb-9318-9d5b1bb2bfbb.png)

**What is Configured?**
Serverless Config

```
# serverless.yml
App:
  component: "@sls-next/serverless-component@1.18.0"
```

If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources
  * I deployed all resources via a separate CDK stack and I'm referencing their AWS ARN's in the amplify config. I did not deploy any of my cloud resources using amplify.
* Which resources do you have configured?
   * If applicable, please provide your manual configuration example:
   ```
   const AMPLIFY_CONFIG ={
      // API Settings
      aws_appsync_graphqlEndpoint: process.env.NEXT_PUBLIC_GRAPHQL_ENDPOINT,
      aws_appsync_region: process.env.NEXT_PUBLIC_AWS_REGION,
      aws_appsync_authenticationType: process.env.NEXT_PUBLIC_API_AUTH_TYPE,
      aws_appsync_apiKey: process.env.NEXT_PUBLIC_API_KEY,
      // Auth Settings
      aws_cognito_region: process.env.NEXT_PUBLIC_AWS_REGION,
      aws_user_pools_id: process.env.NEXT_PUBLIC_USER_POOL_ID,
      aws_user_pools_web_client_id: process.env.NEXT_PUBLIC_USER_POOL_WEB_CLIENT_ID,
      aws_cognito_identity_pool_id: process.env.NEXT_PUBLIC_IDENTITY_POOL_ID,
      aws_user_files_s3_bucket_region: process.env.NEXT_PUBLIC_AWS_REGION,
      aws_user_files_s3_bucket: process.env.NEXT_PUBLIC_S3_BUCKET,
      ssr: true,
      Analytics: {
        disabled: true,
      },
    };
   ```
  * If it is necessary for me to provide actual resource IDs, please let me know. I just want to be careful sharing resource IDs around.
 

<details>
  <summary><strong>Environment</strong></summary>

```
# npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages

  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 24.88 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.7.0 - ~/Home/startups/hatch_project/website/.env/bin/node
    npm: 7.4.3 - ~/Home/startups/hatch_project/website/.env/bin/npm
  Browsers:
    Chrome: 89.0.4389.82
    Safari: 14.0
  npmPackages:
    @material-ui/core: ^4.11.3 => 4.11.3 
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.57 
    @reduxjs/toolkit: ^1.5.0 => 1.5.0 
    @svgr/webpack: ^5.5.0 => 5.5.0 
    aws-amplify: ^3.3.23 => 3.3.23 
    axios: ^0.21.1 => 0.21.1 
    bootstrap: ^4.6.0 => 4.6.0 
    immutability-helper: ^3.1.1 => 3.1.1 
    luxon: ^1.25.0 => 1.26.0 
    next: ^10.0.8 => 10.0.8 
    react: 17.0.1 => 17.0.1 
    react-bootstrap: ^1.4.3 => 1.5.1 
    react-dom: 17.0.1 => 17.0.1 
    react-icons: ^4.1.0 => 4.2.0 
    react-redux: ^7.2.2 => 7.2.2 
    react-responsive: ^8.2.0 => 8.2.0 
    react-router-dom: ^5.2.0 => 5.2.0 
    sass: ^1.32.6 => 1.32.8 
    serverless: ^2.28.7 => 2.28.7 
    swr: ^0.4.2 => 0.4.2 
    update: ^0.7.4 => 0.7.4 
    uuid: ^8.3.2 => 8.3.2 
  npmGlobalPackages:
    @aws-amplify/cli: 4.41.2
    npm-check-updates: 11.1.1
    npm: 7.4.3
    serverless: 2.23.0
```

</details>

**Additional context**
The strangest part of this is that server side calls are working properly and client side calls are not working on the deployed site. However, on the local server everything is working fine. Right now, both the deployed and development applications are using the same environment variable settings.

**Comment by felixs8696** [comment]
Related to this issues I posted in the serverless-next-js issues page: https://github.com/serverless-nextjs/serverless-next.js/issues/936, but not much luck there. I'm assuming this is more of an Amplify configuration problem than a serverless one, but I'm not sure.

**Comment by shaase** [comment]
Hi all, I'm experiencing a similar issue to @felixs8696. I was following the the new post, [Host a Next.js SSR app with real-time data on AWS Amplify](https://aws.amazon.com/blogs/mobile/host-a-next-js-ssr-app-with-real-time-data-on-aws-amplify/). I just started over, following the tutorial closely. While the home page works, trying out /api/hello gives me a 503 error.

<img width="709" alt="Screen Shot 2021-05-21 at 8 08 51 AM" src="https://user-images.githubusercontent.com/1431147/119142187-cc4df600-ba0b-11eb-9942-6943e7277170.png">

Going into CloudWatch, I see a different error:

<img width="1086" alt="Screen Shot 2021-05-21 at 8 11 18 AM" src="https://user-images.githubusercontent.com/1431147/119142503-35356e00-ba0c-11eb-90ac-fb25089e3916.png">

That would initially lead me to believe it's an issue with my build, but everything is working locally (both content and api pages), and as I mentioned, I haven't done much with the project beyond following the tutorial.

**Comment by chrisbonifacio** [comment]
Hi :wave: Sorry this was auto-closed by stale bot. We are working towards preventing this from happening in the future. Please let us know if you are still experiencing this issue and in need of assistance.

**Comment by DaviBrancol** [comment]
Hey guys, I'm facing the same problem described here.

Any updates on how to fix?

**Comment by chrisbonifacio** [comment]
@felixs8696 @DaviBrancol I believe this issue may have been caused by using a version of NextJS greater than v9 at the time. I believe we now support v10 and v11. Please let me know if this is still happening for you. If the issues persists, you may have to downgrade to NextJS v9.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!

**Comment by MartinCura** [comment]
Hi there, just deployed the first API route in our Next.js app and it returns this error when deployed.

We've been using Next.js 11 and would prefer to keep it (i set "latest" for the Next.js version in the Amplify console).

Is there a timeframe for these things to be ironed out? Is there any way to not drop down to v9 and lose a lot of functionality?

If this is being tracked in another issue please point to it :) If i can be of any help don't hesitate.

**Comment by MartinCura** [comment]
Update: switched to using [serverless-next.js](https://github.com/serverless-nextjs/serverless-next.js) because of this and other nuisances.

**Comment by Rafcin** [comment]
I know this is a bit late but here is the current solution. Some people have been having issues on Next 12.0.9 and up with the API routes and if you don't want to deploy manually with serverless then this will also work.

3.6.0 has been running into some issues so it's recommended to use `@sls-next/serverless-component@3.7.0-alpha.11` or version 10. If you use this version it will work fine. I assume 3.6.0 works with Next 11 but I haven't looked at it.

To switch the version, create a new folder in the root of the project and call it config or whatever you want and to that add a new serverless.yml like this:

```
ID HERE (ex d30o3wao...):
  component: '@sls-next/serverless-component@3.7.0-alpha.11'
  inputs:
    memory:
      defaultLambda: 1024
      apiLambda: 2048
      imageLambda: 2048
    timeout:
      defaultLambda: 30
      apiLambda: 30
      imageLambda: 30
      regenerationLambda: 30
    cloudfront:
      defaults:
        forward:
          headers:
            - CloudFront-Is-Desktop-Viewer
            - CloudFront-Is-Mobile-Viewer
            - CloudFront-Is-Tablet-Viewer
            - CloudFront-Viewer-Country
            - CloudFront-Viewer-Latitude
            - CloudFront-Viewer-Longitude
            - CloudFront-Viewer-Time-Zone
            - CloudFront-Viewer-City
            - Authorization
    build:
      env:
        AMPLIFY_DIFF_DEPLOY: 'false'
        AMPLIFY_MONOREPO_APP_ROOT: apps/appname
```
**Note** my config is for a  monorepo and I also added headers and changed the memory for the 4 lambdas. If you want to view the current generated serverless file anytime just add `aws s3 cp serverless.yml s3://bucketname/public/` to your build and you can see it later, for some reason you cant log it.

And then in your amplify yml during the build step add this.
```
build:
          commands:
            - yarn appname-build
            - cd apps/appname
            - cp config/serverless.yml serverless.yml
            # - aws s3 cp serverless.yml s3://appname-sandbox/public/
        postBuild:
          commands:
            - ls
```

**Comment by Nithur-M** [comment]
I am using Nextjs 12.2.2 and still facing the issue when fetching data from the client side.

**Comment by Nithur-M** [comment]
> Hi all, I'm experiencing a similar issue to @felixs8696. I was following the the new post, [Host a Next.js SSR app with real-time data on AWS Amplify](https://aws.amazon.com/blogs/mobile/host-a-next-js-ssr-app-with-real-time-data-on-aws-amplify/). I just started over, following the tutorial closely. While the home page works, trying out /api/hello gives me a 503 error.
> 
> <img alt="Screen Shot 2021-05-21 at 8 08 51 AM" width="709" src="https://user-images.githubusercontent.com/1431147/119142187-cc4df600-ba0b-11eb-9942-6943e7277170.png">
> 
> Going into CloudWatch, I see a different error:
> 
> <img alt="Screen Shot 2021-05-21 at 8 11 18 AM" width="1086" src="https://user-images.githubusercontent.com/1431147/119142503-35356e00-ba0c-11eb-90ac-fb25089e3916.png">
> 
> That would initially lead me to believe it's an issue with my build, but everything is working locally (both content and api pages), and as I mentioned, I haven't done much with the project beyond following the tutorial.

Hi @shaase were you able to get this resolved? I am having this issue now.

**Comment by abdallahshaban557** [comment]
Hi @Nithur-M - the Amplify hosting team is aware of this issue and are actively working towards fixing it.

**Comment by Nithur-M** [comment]
@abdallahshaban557 so there is no workaround also?

**Comment by abdallahshaban557** [comment]
@Nithur-M  - which version of NextJS are you using? can you please submit a new Github issue for us to track your concern?

**Comment by Nithur-M** [comment]
@abdallahshaban557 I've already migrated to Vercel. I am using NextJS 12.
I've submitted an issue yesterday. Here is the link: https://github.com/aws-amplify/amplify-hosting/issues/2944#issue-1347371986
P.S: my issue is not related to Amplify js but Amplify hosting.

**Comment by abdallahshaban557** [comment]
@Nithur-M - thank you for getting back to me. It makes sense on the hosting issue. Our Hosting team is working on solidifying our support for NextJS 12.
