### ISSUE TITLE
"@aws-amplify/core"@3.8.18 amplify forces to use identityPoolId

### ISSUE THREAD

**Issue by iegik** [aws-amplify/amplify-js#7941]
As I understand, In AWS documentation says, that IdentityPoolId is "OPTIONAL" and used only for Federation identification, such as google, facebook and so on:
- https://docs.amplify.aws/lib/auth/start/q/platform/js#re-use-existing-authentication-resource

Because IdentityPoolId can be used to "Accessing AWS Services", I don't want to use it in configuration:

- https://docs.amazonaws.cn/en_us/cognito/latest/developerguide/amazon-cognito-integrating-user-pools-with-identity-pools.html
- https://notsosecure.com/hacking-aws-cognito-misconfigurations/

In fact, in "@aws-amplify/core"@3.8.18 release, `aws-amplify` was updated from "v3.3.22" to `v3.3.24` where in [_setCredentialsFromSession](https://github.com/aws-amplify/amplify-js/commit/b9aa033f192a5b1cdee25b81ea185abb13c24521#diff-529fe0eb9dda8c67eb9f7cf7c63a52b642bc7c4919a1e5195580c747073e885dR216) method check for "identityPoolId" was added:

```
if (!identityPoolId) {
            logger.debug('No Cognito Federated Identity pool provided');
            return Promise.reject('No Cognito Federated Identity pool provided'); /* Remove this line, because identityPoolId is OPTIONAL, rejecting here breaks the flow */
        }
```

Previously, was able to use `Amplify.signUp` without providing identityPoolId in `Amplify.configure`.

**To Reproduce**

1. Go to Login page
2. Click on 'Login'
4. Don't See error because in 

**Expected behavior**

**Code Snippet**

https://github.com/aws-amplify/amplify-js/commit/b9aa033f192a5b1cdee25b81ea185abb13c24521#diff-529fe0eb9dda8c67eb9f7cf7c63a52b642bc7c4919a1e5195580c747073e885dR216

**Screenshots**

When I try to confirm registred user with provided code in email I got first error:

```Incorrect username or password```

And after submitting code again second:

```User cannot be confirmed. Current status CONFIRMED```

**What is Configured?**
If applicable, please provide what is configured for Amplify CLI:
* Which steps did you follow via Amplify CLI when configuring your resources.
* Which resources do you have configured?
 
   * If applicable, please provide your manual configuration example:
   ```
   {
    Auth: {
        region: 'XX-XXXX-X',
        userPoolId: 'XX-XXXX-X_abcd1234',
        userPoolWebClientId: 'a1b2c3d4e5f6g7h8i9j0k1l2m3',
        mandatorySignIn: true,
        oauth: {
            domain: 'your_cognito_domain',
            scope: ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
            redirectSignIn: 'http://localhost:3000/',
            redirectSignOut: 'http://localhost:3000/',
            responseType: 'code' // or 'token', note that REFRESH token will only be generated when the responseType is code
           }
       }
   }
   ```

<details>
  <summary><strong>Environment</strong></summary>

```
    "@aws-amplify/auth": "^3.2.13",
    "@aws-amplify/core": "^3.3.3",
```

</details>

Following commit broke the flow:

https://github.com/aws-amplify/amplify-js/commit/b9aa033f192a5b1cdee25b81ea185abb13c24521

```
private _setCredentialsFromSession(session) {
        logger.debug('set credentials from session');
        const idToken = session.getIdToken().getJwtToken();
        const { region, userPoolId, identityPoolId } = this._config;
        if (!identityPoolId) {
            logger.debug('No Cognito Federated Identity pool provided');
            return Promise.reject('No Cognito Federated Identity pool provided'); /* Remove this line, because identityPoolId is OPTIONAL, rejecting here breaks the flow */
        }
        const key = 'cognito-idp.' + region + '.amazonaws.com/' + userPoolId;
        const logins = {};
        logins[key] = idToken;
        const credentials = new AWS.CognitoIdentityCredentials(
            {
            IdentityPoolId: identityPoolId,
            Logins: logins
        },  {
            region
        });

        const that = this;
        return this._loadCredentials(credentials, 'userPool', true, null);
    }
```

Working code:

```
private _setCredentialsFromSession(session) {
        logger.debug('set credentials from session');
        const idToken = session.getIdToken().getJwtToken();
        const { region, userPoolId, identityPoolId } = this._config;
        const key = 'cognito-idp.' + region + '.amazonaws.com/' + userPoolId;
        const logins = {};
        logins[key] = idToken;
        const credentials = new AWS.CognitoIdentityCredentials(
            {
            IdentityPoolId: identityPoolId, /* can be undefined here */
            Logins: logins
        },  {
            region
        });

        const that = this;
        return this._loadCredentials(credentials, 'userPool', true, null);
    }
```

@powerful23 Please, check this

**Comment by iegik** [comment]
Possible duplicate of https://github.com/aws-amplify/amplify-js/issues/7919

**Comment by iegik** [comment]
Possible duplicate of https://github.com/aws-amplify/amplify-js/issues/7684

**Comment by chrisbonifacio** [comment]
Good evening! Thank you for raising this. After doing some testing, I have not been able to reproduce this issue using `Auth.signUp` and `Auth.confirmSignUp` to confirm a new user's registration.

Could you please provide a sample from your code of how you are using `Auth.signUp` and `Auth.confirmSignUp`?

Also, just so that I am accurate in my attempts to reproduce, am I correct in that you are not using an OAuth configuration?

To be most accurate, if you could update the `Which steps did you follow via Amplify CLI when configuring your resources.` so that I can try to set up my auth configuration the same way, that would be very helpful.

**Comment by chrisbonifacio** [comment]
There can be issues when using duplicate packages, so just to be sure could you please run the appropriate command in your terminal and include in your comment the output?

This will tell us if there are any duplicate packages in your dependency tree

# Using YARN
`yarn list --pattern amplify | \
  grep -o -e '@\?aws-amplify[^ ]*' | \
  sort | uniq | \
  sed -E 's/^(@?[^@]+).*$/\1/g' | \
  uniq -d | sort`
  
  # Using NPM
  `npm ls -all 2>/dev/null | \
  grep -o -e '@\?aws-amplify[^ ]*' | \
  sort | uniq | \
  sed -E 's/^(@?[^@]+).*$/\1/g' | \
  uniq -d | sort`

**Comment by chrisbonifacio** [comment]
After further investigation, running the duplicate check command in the terminal with both of the packages in your environment results in this dependency tree

```
yarn list v1.22.4
├─ @aws-amplify/auth@3.2.13
│  └─ @aws-amplify/core@3.8.21
├─ @aws-amplify/cache@3.1.54
│  └─ @aws-amplify/core@3.8.21
└─ @aws-amplify/core@3.3.3
```

You'll notice that the `@aws-amplify/auth@3.2.13` version includes `@aws-amplify/core@3.8.21`
But we already installed `@aws-amplify/core@3.3.3` so this will cause some issues.

I did not get the same error you did but it did get an error saying that my auth was not properly configured.

Upgrading both packages to the latest version fixed the issue for me

**Comment by iegik** [comment]
@chrisbonifacio Thank You for response! After some investigation I realised, that identityPoolId check was in code since first commit.

```
$ npm ls -all 2>/dev/null | \
grep -o -e '@\?aws-amplify[^ ]*' | \
sort | uniq
@aws-amplify/auth@3.2.13
@aws-amplify/cache@3.1.16
@aws-amplify/core@3.3.3
```

I'll try update `@aws-amplify/core` as you mentioned and will tell you the results later.

**Comment by chrisbonifacio** [comment]
No problem! Be sure to upgrade the @aws-amplify/auth package as well. Looks like you're using 3.2.13 but the latest version is 3.4.30.
