### ISSUE TITLE
NestJS FrameWork support

### ISSUE THREAD

**Issue by hugoebarboza** [aws-amplify/amplify-js#7949]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, an idea of the implementation or screenshots about the feature request here.

I would like to implement my GraphQL NestJS API with Amazon Amplify,

**Comment by nadetastic** [comment]
Hi @hugoebarboza 👋,

Amplify was created to be used on the client side, and other than Next.js(SSR), Amplify isn't supported on Node runtimes. 

As a work around, you can use an HTTP request library of your choice (fetch, axios, etc) to send graphql queries and mutations to your AppSync endpoint created by the Amplify CLI.

The CLI provisioned resources can be accessed from a backend environment with the AWS SDK but the Amplify libraries themselves are intended to be used on the client.
