### ISSUE TITLE
Analytics is not working

### ISSUE THREAD

**Issue by arupdasTA** [aws-amplify/amplify-js#7951]
Pinpoint Analytics is not working with AWS Cognito for the Angular app

@angular/cli: 10.1.3
aws-amplify: 3.3.1
aws-amplify-angular": "5.0.30

AWS export file looks like

```
import { environment } from './environments/environment';

const awsmobile = {
    'aws_project_region': environment.aws_project_region,
    'aws_cognito_region': environment.aws_cognito_region,
    'aws_user_pools_id': environment.aws_user_pools_id,
    'aws_user_pools_web_client_id': environment.aws_user_pools_web_client_id,
    'aws_app_analytics': environment.aws_app_analytics,
    'aws_cognito_identity_pool_id': environment.aws_cognito_identity_pool_id,
    'aws_mobile_analytics_app_id': environment.aws_mobile_analytics_app_id,
    'aws_mobile_analytics_app_region': environment.aws_mobile_analytics_app_region,
    'aws_user_pools': environment.aws_user_pools,
};

export default awsmobile;
```

main.ts file looks like

```
import Amplify, { Analytics } from 'aws-amplify';
import amplify from './aws-exports';
Amplify.configure(amplify);
Analytics.enable();
```
We are having an identical configuration for three different environments. It's working for the other two environments. Double checked the AWS export file and all the configurations are propagating correctly.

**Comment by sammartinez** [comment]
I know you listed some of the dependencies above but can you provide your `package.json` along with your environment settings? 

Please use the follow command: 
```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

Thanks ahead of time!

**Comment by arupdasTA** [comment]
Here is the requested details

System:
OS: macOS High Sierra 10.13.6
CPU: (4) x64 Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz
Memory: 50.43 MB / 8.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.16.3 - /usr/local/bin/node
npm: 6.9.0 - /usr/local/bin/npm
Browsers:
Chrome: 89.0.4389.90
Firefox: 87.0
Safari: 13.0.2
npmPackages:
@agm/core: 3.0.0-beta.0 => 3.0.0-beta.0
@amcharts/amcharts4: 4.10.4 => 4.10.4
@angular-devkit/build-angular: ~0.1001.3 => 0.1001.7
@angular/animations: 10.1.3 => 10.1.3
@angular/cdk: 10.2.2 => 10.2.2
@angular/cli: ~10.1.3 => 10.1.7
@angular/common: 10.1.3 => 10.1.3
@angular/compiler: 10.1.3 => 10.1.3
@angular/compiler-cli: 10.1.3 => 10.1.3
@angular/core: 10.1.3 => 10.1.3
@angular/flex-layout: 10.0.0-beta.32 => 10.0.0-beta.32
@angular/forms: 10.1.3 => 10.1.3
@angular/language-service: 10.1.3 => 10.1.3
@angular/platform-browser: 10.1.3 => 10.1.3
@angular/platform-browser-dynamic: 10.1.3 => 10.1.3
@angular/router: 10.1.3 => 10.1.3
@asymmetrik/ngx-leaflet: 8.1.0 => 8.1.0
@asymmetrik/ngx-leaflet-markercluster: 5.0.1 => 5.0.1
@ng-idle/core: 10.0.0-beta.1 => 10.0.0-beta.1
@ng-idle/keepalive: 10.0.0-beta.1 => 10.0.0-beta.1
@ngx-progressbar/core: 5.3.2 => 5.3.2
@ngx-translate/core: 13.0.0 => 13.0.0
@ngx-translate/http-loader: 6.0.0 => 6.0.0
@types/datatables.net: 1.10.19 => 1.10.19
@types/intro.js: 2.4.7 => 2.4.7
@types/jasmine: 3.5.14 => 3.5.14
@types/jasminewd2: ~2.0.8 => 2.0.8
@types/jquery: 3.5.1 => 3.5.1
@types/leaflet: 1.5.23 => 1.5.23
@types/leaflet.markercluster: ~1.4.4 => 1.4.4
@types/moment-timezone: 0.5.30 => 0.5.30
@types/node: 14.11.2 => 14.11.2
angular-datatables: 9.0.2 => 9.0.2
angular-svg-icon: 10.0.0 => 10.0.0
angular-user-idle: 2.2.4 => 2.2.4
angular2-moment: 1.9.0 => 1.9.0
aws-amplify: 3.3.1 => 3.3.1
aws-amplify-angular: 5.0.30 => 5.0.30
bootstrap: 4.5.2 => 4.5.2
codelyzer: 6.0.0 => 6.0.0
core-js: 3.6.5 => 3.6.5
datatables.net: 1.10.22 => 1.10.22
datatables.net-dt: 1.10.22 => 1.10.22
font-awesome: 4.7.0 => 4.7.0
handlebars: 4.7.6 => 4.7.6
intro.js: 2.9.3 => 2.9.3
jasmine-core: ~3.6.0 => 3.6.0
jasmine-spec-reporter: ~6.0.0 => 6.0.0
jquery: 3.5.1 => 3.5.1
karma: ~5.2.2 => 5.2.3
karma-chrome-launcher: ~3.1.0 => 3.1.0
karma-coverage-istanbul-reporter: ~3.0.3 => 3.0.3
karma-htmlfile-reporter: 0.3.8 => 0.3.8
karma-jasmine: ~4.0.1 => 4.0.1
karma-jasmine-html-reporter: 1.5.4 => 1.5.4
leaflet: 1.7.1 => 1.7.1
leaflet-easybutton: ^2.4.0 => 2.4.0
leaflet-geosearch: 3.2.1 => 3.2.1
leaflet-google-places-autocomplete: 0.0.9 => 0.0.9
leaflet-search: 2.9.9 => 2.9.9
leaflet.markercluster: 1.4.1 => 1.4.1
lodash: 4.17.20 => 4.17.20
moment: 2.29.0 => 2.29.0
moment-timezone: 0.5.31 => 0.5.31
ng-multiselect-dropdown: 0.2.10 => 0.2.10
ng-sidebar: 9.4.2 => 9.4.2
ngx-avatar: 4.0.0 => 4.0.0
ngx-bootstrap: 6.1.0 => 6.1.0
ngx-device-detector: 2.0.0 => 2.0.0
ngx-google-places-autocomplete: 2.0.4 => 2.0.4
ngx-hotjar: 9.0.2 => 9.0.2
ngx-icons: 0.3.0 => 0.3.0
ngx-image-cropper: 3.2.1 => 3.2.1
ngx-malihu-scrollbar: 9.0.0 => 9.0.0
ngx-mask: 10.0.1 => 10.0.1
ngx-moment: 5.0.0 => 5.0.0
ngx-owl-carousel: 2.0.7 => 2.0.7
ngx-toastr: 13.0.0 => 13.0.0
node-sass: 4.14.1 => 4.14.1
protractor: ~7.0.0 => 7.0.0
rxjs: 6.6.3 => 6.6.3
sockette: 2.0.6 => 2.0.6
ts-node: ~9.0.0 => 9.0.0
tslib: 2.0.1 => 2.0.1
tslint: ~6.1.0 => 6.1.3
typescript: 4.0.3 => 4.0.3
web-animations-js: 2.3.2 => 2.3.2
zone.js: 0.11.1 => 0.11.1
npmGlobalPackages:
@angular/cli: 10.0.6
@ionic/cli: 6.0.1
3s-money-backend: 1.0.0
bower: 1.8.8
cordova: 9.0.0
generator-angular: 0.16.0
generator-karma: 2.0.1
grunt-cli: 1.3.2
native-run: 0.3.0
nodemon: 2.0.2
npm: 6.9.0
serverless: 1.61.2
yo: 3.1.1

**Comment by wlee221** [comment]
Hi @arupdasTA, apologies about the delayed response here. Can you describe the error you're seeing with `Analytics` + `Auth`? Do you see any error messages, and can you provide us a sample code how you're using analytics?

**Comment by chrisbonifacio** [comment]
@arupdasTA Closing this one for now as we have not heard back from you. Please feel free to re-open if you are still experiencing this issue and are still in need of support. Thank you.

**Comment by edwint88** [comment]
I kind of have the same problem, the analytics works on dev and test and then on prod they don't work at all. Is a must to have identiyPool with the analytics? 
The strange part is that on the first 2 envs I don't have any identityPool and works
