### ISSUE TITLE
Cognito - User Pool - SAML Connection (Auth0) - Hosted UI - Endless redirects

### ISSUE THREAD

**Issue by the-s0urce** [aws-amplify/amplify-js#7952]
**Describe the bug**
Redirect from Hosted UI ends up in an endless redirect back to hosted ui.

**To Reproduce**

1. Connect a SAML Connection to your Cognito user pool
2. `import Amplify, { Auth } from 'aws-amplify'`
3. configure your aws-exports to userpoolid and oauth settings
4. Call: `Amplify.configure(awsconfig);`
5. Call: `Auth.federatedSignIn('COGNITO', { token: locationHashes.access_token, expires_at: locationHashes.expires_in * 1 + Date.now() });`

**Expected behavior**
Handling session with given access_token from hosted ui redirect.

**Code Snippet**
`import Amplify, { Auth } from 'aws-amplify';
import awsconfig from './aws-exports';

Amplify.configure(awsconfig);

const locationHashes = {};
for (const pair of location.hash.slice(1).split('&')) {
  const [key, value] = pair.split('=');
  locationHashes[key] = value;
}

Auth.federatedSignIn('COGNITO', { token: locationHashes.access_token, expires_at: locationHashes.expires_in * 1 + Date.now() });
`
**What is Configured?**
 ```
 const awsmobile = {
"Auth": {
  "userPoolId": "eu-west-1_XXXXX",
  "userPoolWebClientId": "YYYYYYY",
  "region": "eu-west-1",
  "oauth": {
	  "domain": "XXXX.auth.eu-west-1.amazoncognito.com",
	  "scope": [
		  "email",
		  "profile",
		  "openid"
	  ],
	  "redirectSignIn": "http://localhost:8080/",
	  "redirectSignOut": "http://localhost:8080/",
	  "responseType": "token",
	  "mandatorySignIn": false,
	  "cookieStorage": {
			  "domain": "localhost",
			  "path": "/",
			  "expires": 365,
			  "secure": true
	  }
  }
 };
 ```

**Comment by chrisbonifacio** [comment]
Hi :wave: Sorry this was auto-closed by stale bot. We are working towards preventing this from happening in the future. Please let us know if you are still experiencing this issue and in need of assistance.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!
