### ISSUE TITLE
NEW_PASSWORD_REQUIRED allows to set old password again.

### ISSUE THREAD

**Issue by axelgalicia** [aws-amplify/amplify-js#7957]
**Describe the bug**
When using completeNewPassword from Auth object it allows to set the temporal password again.

**To Reproduce**

1. Call Auth.completeNewPassword(...) passing same temporal password received either by email or sms.
2. Amplify will allow to have new password set using temporal password.

**Expected behavior**
I would expect to get an error when trying to set new password using same temporal.

- Version 4.44.2

**Comment by chrisbonifacio** [comment]
Thank you for reaching out and opening an issue. As I look into this, I assume that by "temporal" you mean the "temporary" password, correct?

**Comment by axelgalicia** [comment]
Thank Chris, 

You are correct. The temporary password can be used again.

**Comment by chrisbonifacio** [comment]
So, I was able to reproduce this issue and you are correct, the temporary password can be set as the New Password.
It seems this is the current behavior, but I can label this as a feature request for the team.

**Comment by axelgalicia** [comment]
Thanks a lot Chris. I would love to be a collaborator to fix this issue.

**Comment by evcodes** [comment]
Hi @axelgalicia, thank you for opening this issue.

Unfortunately, this same [issue has been raised in the Cognito forums ](https://forums.aws.amazon.com/thread.jspa?messageID=960680&#960680). Unfortunately, we cannot fix this issue.
