### ISSUE TITLE
"Error: No credentials" error from the Vue.js

### ISSUE THREAD

**Issue by m2broth** [aws-amplify/amplify-js#7964]
**Describe the bug**
We are using Vue.JS as an Amplify frontend. The congito auth method was set by default. We init the Amplify class in the main index file. It authorizes users without any issues using the Auth.sign method but when we try to call the API.graphql(graphqlOperation(testQueryMethod)) we get "25:14.386 GraphQLAPI - ensure credentials error No Cognito Identity pool provided for unauthenticated access" warning. 
I tried to debug the issue and found that the "_options" property of the GraphqlAPI class is empty within the API.graphql call. 

**Code Snippet**
Our init block:
import Amplify from "aws-amplify";
import awsconfig from "./aws-exports";
Amplify.configure(awsconfig);

The API block:
API.graphql(graphqlOperation(testQueryMethod))

**What is Configured?**
Amplify console version is 4.45
Amplify Core version is 3.8.19
Amplify API version is 3.2.27

**Comment by m2broth** [comment]
eg. This block of code doesn't work. It's strange. The API class doesn't have any information about credentials. 

import awsconfig from "./aws-exports";

Amplify.configure(awsconfig);

import { graphqlOperation } from "aws-amplify";
import { testQuery } from "@/graphql/queries";

(async() => {
  await Auth.signIn('test@user.com', '****');
  const API = new APIClass(awsconfig);
  const res = await API.graphql(graphqlOperation(testQuery));
})();

**Comment by sammartinez** [comment]
Hey @m2broth, thanks for opening this issue. Can you provide your `package.json` along with your environment settings? 

Please use the follow command: 
```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

Thanks ahead of time!

**Comment by sky4git** [comment]
I have exactly the same issue on ReactJS app. I can login and authorize with cognito pool user but GraphQL queries  gives the same error.

[WARN] 42:03.750 GraphQLAPI - ensure credentials error No Cognito Identity pool provided for unauthenticated access

My npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
is given in [#7934](https://github.com/aws-amplify/amplify-js/issues/7934)

**Comment by m2broth** [comment]
The issue was resolved by fixing the package-lock.json file. It had some issues with packages.

**Comment by sky4git** [comment]
@m2broth What kind of issues with package-lock.json file? 
Could you please explain it so I can solve my issue too?
Thanks.

**Comment by m2broth** [comment]
@sky4git Try to remove the "package-lock.json" and use the  "^3.3.17" of "aws-amplify" library

**Comment by sky4git** [comment]
I solved it yesterday. See my last comment on #7934 

The main reason was amplify-js new modular approach. We not need to add sub modules in package.json, just amplify-js enough. If we add submodules in package.json dependencies then it will create issues.
