### ISSUE TITLE
Redirect Uri is not registered with the client

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/amplify-js#7968]
**Describe the bug**
I am trying to login with google and facebook. The user is registered successfully. 
But its saying redirect uri is not registered with the client.
**Where is this redirect uri specified???** I have set callback url and signout url.
I am NOT using amplify cli to build backend auth. Instead I am using aws cdk to build backend auth.
I am using `@aws-amplify/auth` to consume the backend.

**To Reproduce**
I have set `callback url` and `signout url` inside user pool(console) -> app client settings -> sign in and sign out urls. to my live website domain. Again I have set it with cdk but verified from console.

**Expected behavior**
I should redirect to home page of my domain. with correct auth.

**Code Snippet**
I am just writing network requests made when clicked on sign in with google or facebook.

First request made is success to following url
`amazoncognito.com/oauth2/authorize?redirect_uri`

Second request made is also success to follwing url
`accounts.google.com/o/oauth2/v2/auth?client_id`

Third request made here is that returns error response
`amazoncognito.com/oauth2/idpresponse?state`

**What is Configured?**
* Which resources do you have configured?
  * If applicable, please provide your `aws-exports` file:
```ts
const config = {
  aws_project_region: "us-east-1",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-xxxxxxxx",
  aws_user_pools_web_client_id: "xxxxxxxxxxxxxxxxxxxxxxxx",
  aws_appsync_graphqlEndpoint: "https://xxxxxxxxxxx.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  oauth: {
    domain: "xxxxxxxx.auth.us-east-1.amazoncognito.com",
    scope: ["phone", "email", "openid", "profile", "aws.cognito.signin.user.admin"],
    redirectSignIn: "https://my-actual-live-domain.com/",
    redirectSignOut: "https://my-actual-live-domain.com/",
    responseType: "code",
  },
}
   ```
Above config is written in typescript.

**Comment by apoorvmote** [comment]
# Answer

My callback url and sign out url was `https://my-actual-live-domain.com` 

It was missing the trailing slash. 

That is `https://my-actual-live-domain.com/`

And now everything works

**Comment by countryst** [comment]
@apoorvmote my aws-exports matches yours, when I login using Facebook, the login details don't get added to my Cognito Pool (if I use hosted UI, it gets added). And I'm getting `No Cognito Federated Identity pool provided` in console log. Here is more details about my setup https://github.com/aws-amplify/amplify-js/discussions/8160 could you let me know if I have configured something incorrectly
