### ISSUE TITLE
Auth.verifyCurrentUserAttribute does not send sms

### ISSUE THREAD

**Issue by bishonbopanna** [aws-amplify/amplify-js#7982]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v15.12.0

### Amplify CLI Version

4.45.2

### What operating system are you using?

Mac

### Amplify Categories

auth

### Amplify Commands

add, init

### Describe the bug

Auth.verifyCurrentUserAttribute('phone_number') API does not send sms with code to verify.

### Expected behavior

Sms with code is expected 

### Reproduction steps

1. Amplify init
2. Add auth 
3. write the below logic to send OTP - which does not give any error but we dont get any OTP 

ENV is in ap-south-1 (Mumbai) and number is provided that of US.

```
Auth.currentAuthenticatedUser()
            .then((cognitoUser) => {
                Auth.updateUserAttributes(cognitoUser, {
                    'phone_number': this.state.phone
                }).then(res => {
                    Auth.verifyCurrentUserAttribute('phone_number')
                        .then(() => {
                            console.log('a verification code is sent');
                            alert("OTP Sent")
                        }).catch((e) => {
                        console.log('failed with error', e);
                    });
                }).catch(err => {
                    console.error(err);
                });
            }).catch(err => {
            console.error(err);
        });

```
### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

Question - Are there any additional configs needed in Cognito ? This was a working code and after initializing a new env UNDER A  NEW ACCOUNT it has got it to stop working.

**Comment by Khairo-kh** [comment]
Hello @bishonbopanna! Do you have destination phone numbers configured in the [SMS Sandbox](https://docs.aws.amazon.com/sns/latest/dg/sns-sms-sandbox.html)? If not please try configuring that in your [Amazon SNS console](https://console.aws.amazon.com/sns/v3/). For your dev environment, it's very easy to add numbers to work with for testing. You can follow the steps [here](https://docs.aws.amazon.com/sns/latest/dg/sns-sms-sandbox-verifying-phone-numbers.html) to add numbers (up to 10 numbers allowed in the sandbox environment).

There is also a [new requirement](https://docs.aws.amazon.com/sns/latest/dg/channels-sms-us-requirements.html)  where you will need to set up [origination number](https://docs.aws.amazon.com/sns/latest/dg/channels-sms-originating-identities-origination-numbers.html) for messaging US destinations. I think you can get an origination number from the Amazon pinpoint console. 

I tested `Auth.verifyCurrentUserAttribute('phone_number')` and it works correctly with numbers verified in the sandbox. If you are getting this issue in production (outside the sandbox environment) or you have any questions please let me know. 

Hope this helps!

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!
