### ISSUE TITLE
Amplify Storage Storage.get cancel download

### ISSUE THREAD

**Issue by enriqueavg** [aws-amplify/amplify-js#7984]
**Is your feature request related to a problem? Please describe.**
For many cases it's necessary cancel download for large files. When users start download there is no way for cancel this.

**Describe the solution you'd like**
May be is necessary a method like Storage.cancel or Storage.stop for current download process.

**Comment by sammartinez** [comment]
Thanks for opening this feature request @enriqueavg. We have a feature request open for this. Can you look to upvote the issue linked here? Also, I am going to close this issue as a duplicate since we have a feature request already created for this.

**Comment by agileurbanite** [comment]
Folks we recently introduced work to allow users to cancel put and get ☝️ , please let us know if this meets your needs and it will be made available in the next release. Appreciate everyones feedback in helping us get better!
