### ISSUE TITLE
NG compiler error T6200, TS2649

### ISSUE THREAD

**Issue by SteveB1955** [aws-amplify/amplify-js#7986]
I get the following errors when compiling my Angular, Amplify project. 

Error: node_modules/amazon-cognito-identity-js/index.d.ts:1:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: ClientMetadata, AuthenticationDetails, CognitoUser, CognitoUserAttribute, CognitoUserPool, CognitoUserSession, CognitoAccessToken, CognitoIdToken, CognitoRefreshToken, CookieStorage, UserAgent, appendToCognitoUserAgent

1 declare module 'amazon-cognito-identity-js' {
  ~~~~~~~

  node_modules/aws-amplify/node_modules/amazon-cognito-identity-js/index.d.ts:1:1
    1 declare module 'amazon-cognito-identity-js' {
      ~~~~~~~
    Conflicts are in this file.

Error: node_modules/amazon-cognito-identity-js/index.d.ts:4:14 - error TS2649: Cannot augment module 'NodeCallback' with value exports because it resolves to a non-module entity.

4  export type NodeCallback<E, T> = (err?: E, result?: T) => void;
               ~~~~~~~~~~~~


Error: node_modules/aws-amplify/node_modules/amazon-cognito-identity-js/index.d.ts:1:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: ClientMetadata, AuthenticationDetails, CognitoUser, CognitoUserAttribute, CognitoUserPool, CognitoUserSession, CognitoAccessToken, CognitoIdToken, CognitoRefreshToken, CookieStorage, UserAgent, appendToCognitoUserAgent

1 declare module 'amazon-cognito-identity-js' {
  ~~~~~~~

  node_modules/amazon-cognito-identity-js/index.d.ts:1:1
    1 declare module 'amazon-cognito-identity-js' {
      ~~~~~~~
    Conflicts are in this file.

This may not be the appropriate place to ask about this but I wasn't sure where to post this problem. 

I'm Using MacOS Big Sur v11.2.2, Apple M1 Chip, VS Code, 
![Screen Shot 2021-03-14 at 4 28 21 PM](https://user-images.githubusercontent.com/80649623/111084816-4f217480-84e2-11eb-9706-e29634940e4e.png)


**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by siegerts** [comment]
Hi @VictorCcccc  :wave: - thanks for raising this!  

To get a bit more context, do you mind porting this to the [formatted bug report template](https://github.com/aws-amplify/amplify-js/issues/new?assignees=&labels=&template=1.bug_report.yaml&title=).

This will help the team determine the best approach to take based on your environment and setup.

**Comment by justinkroh22** [comment]
I had this same issue, I had two copies of amazon-cognito-identity-js

One was at: node_modules/amazon-cognito-identity-js
The other: node_modules/aws-amplify/node_modules/amazon-cognito-identity-js

I removed the one inside aws-amplify and now the problem is gone. That's probably not a good solution, but I am just experimenting with cognito.

**Comment by localsecurity-emily** [comment]
I can confirm I am having this problem also

**Comment by CSHaze** [comment]
Is there any solution to this or another issue that has been opened? I am seeing this as well, after upgrading

**Comment by brymartinez** [comment]
@CSHaze 's solution does not work for me.

I had to downgrade to `aws-amplify@3.3.18` to make it work, as it seems like the 4.6 version of `amazon-cognito-identity-js` is not configured on all of `@aws-sdk`'s dependency

**Comment by LaszloPrekop-InDest** [comment]
I have the same definitions conflict error, it started after an `ng audit fix`. I tried the following: 

- removing `package-lock.json` and `node_modules` following with `npm install`
- upgrade aws-amplify to the latest by `npm install aws-amplify@latest`
- downgrade 'aws-amplify@3.3.27` (latest) to `aws-amplify@3.1.1` -- the version stored in `package.json`

with no success.

**Comment by medelman17** [comment]
I was able to reproduce this issue today while helping out an internal user. We were able to solve it by upgrading Amplify to the latest version (v3.4.3), clearing `node_modules`, reinstalling, etc. Please let me know if, after upgrading to v3.4.3, this remains an issue.

**Comment by localsecurity-emily** [comment]
@medelman17 I am still able to reproduce this issue after upgrading to 3.4.3

**Comment by brymartinez** [comment]
This is still happening on v3.4.3 even after an `npm install / uninstall` recycle.
