### ISSUE TITLE
Required attributes from Cognito in require-new-password component cannot be translated

### ISSUE THREAD

**Issue by Edo-San** [aws-amplify/amplify-js#7997]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

Authentication, Internationalization

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Memory: 149.18 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  npmPackages:
    @aws-amplify/ui-vue: ^1.0.3 => 1.0.3
    @fortawesome/fontawesome-svg-core: ^1.2.34 => 1.2.34
    @fortawesome/free-solid-svg-icons: ^5.15.2 => 5.15.2
    @fortawesome/vue-fontawesome: ^2.0.2 => 2.0.2
    @types/jest: ^24.0.19 => 24.9.1
    @typescript-eslint/eslint-plugin: ^2.33.0 => 2.34.0
    @typescript-eslint/parser: ^2.33.0 => 2.34.0
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.11
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.11
    @vue/cli-plugin-router: ^4.5.11 => 4.5.11
    @vue/cli-plugin-typescript: ~4.5.0 => 4.5.11
    @vue/cli-plugin-unit-jest: ~4.5.0 => 4.5.11
    @vue/cli-plugin-vuex: ~4.5.0 => 4.5.11
    @vue/cli-service: ~4.5.0 => 4.5.11
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0
    @vue/eslint-config-typescript: ^5.0.2 => 5.1.0
    @vue/test-utils: ^1.0.3 => 1.1.3
    aws-amplify: ^3.3.21 => 3.3.21
    buefy: ^0.9.4 => 0.9.4
    core-js: ^3.6.5 => 3.9.0
    eslint: ^6.7.2 => 6.8.0
    eslint-plugin-prettier: ^3.1.3 => 3.3.1
    eslint-plugin-vue: ^6.2.2 => 6.2.2
    lint-staged: ^9.5.0 => 9.5.0
    prettier: ^1.19.1 => 1.19.1
    sass: ^1.26.5 => 1.32.8
    sass-loader: ^8.0.2 => 8.0.2
    typescript: ~3.9.3 => 3.9.9
    vue: ^2.6.11 => 2.6.12
    vue-router: ^3.2.0 => 3.5.1
    vue-template-compiler: ^2.6.11 => 2.6.12
    vuex: ^3.4.0 => 3.6.2
  npmGlobalPackages:
    eslint: 6.6.0
    gitmoji-cli: 3.2.12
    nodemon: 1.19.4
    npm: 6.14.8
    serve: 11.3.2
    yarn: 1.22.10

```

</details>

### Describe the bug

Cognito required user attributes prompted in the amplify-require-new-password component always get the default translation instead of the localized string.

### Expected behavior

I'd expect them to be translatable, like all the other strings, via Amplify I18n class.

### Reproduction steps

1. Setup a user in Cognito with a given_name property that is required AND empty
2. Make him force to change his password
3. Setup a basic Amplify I18n Translation that includes the GIVEN_NAME_LABEL and GIVEN_NAME_PLACEHOLDER keys
4. When the user will reach the "require new password" step, he will also be prompted the "given name", since it's mandatory and it's not yet filled in.
5. All the strings in the require new password component will be translated correctly, accordingly to the I18n setup, while the GIVEN_NAME_LABEL and GIVEN_NAME_PLACEHOLDER strings will still show the default strings.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

I dug on this a little bit. I think this inconsistency is related to the `requiredAttributesMap` object in [https://github.com/aws-amplify/amplify-js/blob/main/packages/amplify-ui-components/src/common/helpers.ts](url).
IMHO it needs to be a function that returns an object, instead of an object, so that it will be computed at the time the function is called, and not before.

**Comment by Edo-San** [comment]
I opened a PR where you can check the solution I'm proposing #7998

**Comment by wlee221** [comment]
Closing as #7998 is merged. Thanks again!
