### ISSUE TITLE
Vue with amplify-authenticator + onAuthUIStateChange breaks refresh and on page change

### ISSUE THREAD

**Issue by Path-A** [aws-amplify/amplify-js#8007]
On the first page load, the authenticator login/signup works perfectly. However, after signing in, if you refresh the page or navigate away and back, you are greeted with an entirely blank page (white in my case). Funnily enough, I can still click my non-authenticator buttons and dropdowns on the page that are only available after a user has signed in. I can see that with my console logs. There's just a giant blank page visually...

It seems that onAuthUIStateChange is not working properly with the authenticator when the page loads. I've tried putting this function within beforeCreate(), created() and setup() lifecycle hooks with no success.

Here's some other issues in other frameworks with the same problem. If there's some hacky workaround for Vue (or Ionic-Vue), I'd love to hear it!

React: https://github.com/aws-amplify/docs/issues/2895
Angular: https://github.com/aws-amplify/docs/issues/2031

**Comment by nickarocho** [comment]
Hi @Path-A, thank you for your question.

Can you provide your `package.json` along with your environment settings? 

Please use the follow command: 
```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

Thanks ahead of time!

**Comment by wlee221** [comment]
Hello @Path-A, thanks for reporting this issue. In your `created` lifecycle, can you try adding the following snippet to `created()` (assuming you're using [this pattern](https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue#recommended-usage) on docs):

```diff
created() {
+    if(this.authState === undefined) {
+      Auth.currentAuthenticatedUser().then(authData => {
+        this.authState = AuthState.SignedIn;
+        this.user = authData;
+      });
+    }
// ...
}
```

**Comment by wlee221** [comment]
Closing as stale. Please let us know if this doesn't resolve the issue.

**Comment by davidallenmann** [comment]
This solution resolves issue with amplify ui components with vue for desktop. This would be helpful to add to the amplify documentation for Vue Auth.
