### ISSUE TITLE
Cannot get @auth  owner directive working with DataStore

### ISSUE THREAD

**Issue by Kilo-Loco** [aws-amplify/amplify-js#8009]
**Is your feature request related to a problem? Please describe.**
I'm currently unable to get DataStore working with the @auth directive. The use case is a basic Todo app where only the owner is able to query the Todos they created.
```graphql
type Todo @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  name: String!
  description: String
}
```
To accommodate the @auth directive, I setup the API category using Amazon Cognito User Pool for the API authorization. Additionally, I am using the typical host web UI sign in configuration for the Auth category.

The problem is that the API and Auth category setups are not really covered in the documentation so I'm assuming that this is the correct path, but the fact that I can't get it working suggests that I set it up wrong.

**Describe the solution you'd like**
It would be good to have better documentation on how to get this process going for a simple use case like `owner` just so one can get started with custom auth rules. Maybe it can be at the top of the [DataStore auth rules page](https://docs.amplify.aws/lib/datastore/setup-auth-rules/q/platform/ios) or included in [guides](https://docs.amplify.aws/guides/q/platform/ios).

**Describe alternatives you've considered**
n/a

**Additional context**
I'd be willing to get these changes added to the docs myself, but I need help getting through to the root problem causing the basic example to not work.

**Comment by chrisbonifacio** [comment]
Hi @Kilo-Loco, re-opened this as it was closed by stalebot. Just so I understand the issue here, I have a few questions.

1. With the current schema and auth directive, what behavior are you seeing?
2. Do you see an owner field being added to the Todos, which should come back as a hash string (this is the User Pool ID of the owner)
3. If so, are other users able to read/write to those Todos with owners?

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!
