### ISSUE TITLE
Attempt limit exceeded, please try after some time.

### ISSUE THREAD

**Issue by gruckionvit** [aws-amplify/amplify-js#8013]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
npx: installed 1 in 1.997s

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 149.20 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.19.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 89.0.4389.114
    Edge: 89.0.774.54
    Safari: 14.0.3
  npmGlobalPackages:
    @aws-amplify/cli: 4.44.2
    create-react-app: 4.0.0
    detox-cli: 18.0.0
    exp: 57.2.1
    expo-cli: 4.0.1
    gh-pages: 3.1.0
    ignite-cli: 3.5.3
    kill-port: 1.6.1
    npm: 6.14.8
    postmark-cli: 1.4.8
    react-native: 0.63.3
    react: 16.13.1
    serve: 11.3.2
    serverless: 2.8.0
    tcs: 10.0.0
    to: 0.2.9
    trash-cli: 3.1.0
    tree-cli: 0.6.7
    typescript: 4.2.2
    update: 0.7.4
    yarn: 1.22.10
    yo: 3.1.1
```

</details>

### Describe the bug

When writing code and littering on a feature I am getting blocked by `LimitExceededException` which is slowing down my development effort. I have to park that task go to something else and come back to it later and hope I get it solved without submitting as much next time.

This isn't ideal, is there a way to extend this limit for staging environments?

### Expected behavior

Be able to work without getting blocked by an API limit in a staging environment.

### Reproduction steps

Call an Auth API multiple times whilst testing

### Code Snippet

```javascript
N/A
```

### Log output

<details>

```
{
  "code": "LimitExceededException",
  "name": "LimitExceededException",
  "message": "Attempt limit exceeded, please try after some time.",
}
```

</details>

### aws-exports.js

N/A

### Manual configuration

N/A

### Additional configuration

N/A

### Mobile Device

N/A

### Mobile Operating System

N/A

### Mobile Browser

N/A

### Mobile Browser Version

N/A

**Comment by iartemiev** [comment]
Hey @gruckionvit, the error you're receiving is in regards to a service-imposed limit coming from Cognito. The AmplifyJS clientside library has no effect on this. Depending on which action is resulting in your receiving this error, you may be able to request a service limit increase. See https://docs.aws.amazon.com/cognito/latest/developerguide/limits.html#api-request-rate-quotas for more info.
