### ISSUE TITLE
storage.put and storage.get use different prefixes for protected level

### ISSUE THREAD

**Issue by JoshiiSinfield** [aws-amplify/amplify-js#8031]
### Before opening, please confirm:

I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

Storage

### Environment information

<details>

```
# Put output below this line
npx: installed 1 in 1.42s

  System:
    OS: macOS 11.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 122.16 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.13.1 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Edge: 89.0.774.68
    Firefox: 86.0.1
    Safari: 14.0.2
  npmPackages:
    @fortawesome/fontawesome-svg-core: ^1.2.30 => 1.2.32 
    @fortawesome/free-brands-svg-icons: ^5.14.0 => 5.15.1 
    @fortawesome/free-solid-svg-icons: ^5.14.0 => 5.15.1 
    @fortawesome/vue-fontawesome: ^2.0.2 => 2.0.2 
    @nuxtjs/axios: ^5.12.5 => 5.12.5 
    @nuxtjs/eslint-config: ^3.1.0 => 3.1.0 
    @nuxtjs/eslint-module: ^2.0.0 => 2.0.0 
    @nuxtjs/google-analytics: ^2.4.0 => 2.4.0 
    @nuxtjs/pwa: ^3.3.3 => 3.3.3 
    @vue/test-utils: ^1.1.2 => 1.1.2 
    aws-amplify: ^3.3.16 => 3.3.16 
    aws-amplify-vue: ^2.1.5 => 2.1.5 
    aws-sdk: ^2.822.0 => 2.822.0 
    babel-core: 7.0.0-bridge.0 => 7.0.0-bridge.0 
    babel-eslint: ^10.1.0 => 10.1.0 
    babel-jest: ^26.3.0 => 26.6.3 
    babel-plugin-component: ^1.1.1 => 1.1.1 
    body-parser: ^1.19.0 => 1.19.0 
    bootstrap: ^4.5.3 => 4.5.3 
    cookie: ^0.4.1 => 0.4.1 
    cross-env: ^5.2.0 => 5.2.1 
    element-ui: ^2.11.1 => 2.14.1 
    eslint: ^7.17.0 => 7.17.0 
    eslint-plugin-nuxt: ^1.0.0 => 1.0.0 
    jest: ^26.4.2 => 26.6.3 
    js-cookie: ^2.2.1 => 2.2.1 
    newrelic: ^7.2.1 => 7.2.1 
    node-sass: ^4.12.0 => 4.14.1 
    nouislider: ^11.1.0 => 11.1.0 
    nuxt: ^2.14.12 => 2.14.12 
    rellax: ^1.10.0 => 1.12.1 
    sass-loader: ^10.0.4 => 10.1.0 
    vue-jest: ^3.0.4 => 3.0.7 
    vue-lazyload: ^1.2.6 => 1.3.3 
    vue-loaders: ^4.1.4 => 4.1.4 
    vue-runtime-helpers: ^1.1.2 => 1.1.2 
    vue2-transitions: ^0.2.3 => 0.2.3 
    vuex-persistedstate: ^4.0.0-beta.1 => 4.0.0-beta.1 
  npmGlobalPackages:
    @aws-amplify/cli: 4.41.2
    npm: 6.14.8
    serverless: 2.16.1


```

</details>

### Describe the bug

When using Storage.put it uses the identity pool Id of the cognito userpool user, however Storage.get only uses this for the current user. If I try to pass in the userpool username(sub) of a different user to IdentityId it fails to get the object.

### Expected behavior

To return the correct prefix, i.e. the identityId of the username passed in.

### Reproduction steps

1. New App.
2. Configure Auth & create user
3. Configure Storage
4. Write object to Storage as 'protected' level
5. using a different user attempt to access the object created in 4 by specifying username as 'identityId'

### Code Snippet

```javascript
// Put your code below this line.
 const putConfig = {
      level: 'protected',
      progressCallback (progress) {
        console.log(`picture upload progress: ${progress.loaded} / ${progress.total}`)
      }
    const storedObject = await Storage.put(`${theFile.name}/${filename}`, theFile, putConfig)
    
    this.picURL = await Storage.get(storedObject.key, {
      level: 'protected',
      identityId: '<username>'
    })

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

Hi,

This seems a major flaw... I'm unable to do a Storage.get at all for a different user's stored objects. This is a requirement of my admin user being able to get a signed link of images stored in S3 by other users, to then display in the admin area.

I'm struggling to work out the right way to go about this. I think I'll be keeping track of the IdentityId on next login in order to use going forward. Seems hacky and shouldn't be at all necessary. 

Feels like a major flaw / bug in Storage here. Unless I'm jsut using it completely wrong.

Cheers,
Josh

**Comment by chrisbonifacio** [comment]
Hey! 👋 Thanks for raising this! Quick question as I look into this. Are you setting the `IdentityId` property by using the `identityId` returned from `Auth.currentCredentials`?

**Comment by JoshiiSinfield** [comment]
Hi @chrisbonifacio ,

Thanks for picking this up :)

I'm storing identityId from  `Auth.currentUserCredentials()` for the admin user to then use in the `storage.get`.


Cheers,
Josh

**Comment by chrisbonifacio** [comment]
Sorry for not getting back to you sooner. After doing some digging into this, I can see why it's difficult to get an item from Storage if another user's identityId is required.

This seems like a duplicate issue, the previous one addressed here:
https://github.com/aws-amplify/amplify-js/issues/2203

It seems the solution here would be to store the S3 key and identityId of the uploading user to an API of yours.

**Comment by JoshiiSinfield** [comment]
thanks for your time on this @chrisbonifacio,

I'm doing what's in that duplicate already. Feels like a major piece of the puzzle is missing from auth api - to get identityid from user sub.

Thanks for your help
