### ISSUE TITLE
MFA for disabling MFA, changing password

### ISSUE THREAD

**Issue by tomquisel** [aws-amplify/amplify-js#804]
There seem to be several best practices missing from Cognito's MFA implementation. See Gmail or Github for examples of the below implemented properly.

With Cognito, a user who has TOTP MFA enabled can:

- disable their MFA (assuming MFA is optional on their user pool) without needing to confirm their password or enter an MFA code
- change their password without needing an MFA code
- reset their password without needing an MFA code

In addition, there appears to be no way to download recovery codes that can be used instead of MFA codes in case they lose their TOTP device.

This means that Cognito is both too permissive and too stringent.

A legitimate user who loses their TOTP device has no way to recover their account without admin intervention (which is susceptible to social engineering), as there are no recovery codes. Even resetting their password will not change their MFA status.

Conversely, an attacker who finds a laptop left open and signed in can disable MFA with no credentials, swipe the user's password from their password manager, and change the user's email + password, taking full control of their account without needing the TOTP device.

Are there plans to address those points? Am I missing something?

**Comment by Ch3ck** [comment]
@tomquisel I wonder if there's been any updates on generating the recovery codes for a user account with MFA on Cognito

**Comment by danawoodman** [comment]
Bump. This is a huge issue and should be addressed

**Comment by filipsuk** [comment]
Agreed. Cognito should bring best security practices instead of breaking them :/ But I am afraid it will not be implemented as it would be a breaking change.

**Comment by porquelaquiero** [comment]
it's been 7 months since filipsuk made last comment. But it doesn't seem like we have solutions for recovery from MFA.. Am I right??

**Comment by danawoodman** [comment]
Short answer; don't use Cognito if you want a proper security model 😢
