### ISSUE TITLE
Missing default handling in AmplifySignIn.handleFormFieldInputChange

### ISSUE THREAD

**Issue by molnarzs** [aws-amplify/amplify-js#8046]
### Before opening, please confirm:

I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 11.1
    CPU: (8) x64 Apple M1
    Memory: 42.28 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.20.0 - ~/.nvm/versions/node/v12.20.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.20.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 89.1.21.77
    Chrome: 89.0.4389.114
    Firefox: 84.0.1
    Safari: 14.0.2
  npmGlobalPackages:
    npm: 6.14.8


```

</details>

### Describe the bug

When I set a custom field:

```
     this.formFields = [
      { type: 'email' },
      { type: 'password' },
      {
        type: 'text',
        label: 'Context',
        required: false,
        handleInputChange: (inputEvent: Event) => {
          console.log('******EVENT', inputEvent);
        },
      },
    ];
```

```
    <amplify-authenticator *ngIf="authState !== 'signedin'" federated="">
      <amplify-sign-in
        header-text="AnyUPP Admin"
        slot="sign-in"
        [formFields]="formFields"
      >
        <div slot="secondary-footer-content"></div>
        <img
          width="20px"
          slot="header-subtitle"
          src="https://cdn.logo.com/hotlink-ok/logo-social-sq.png"
        />
        <div slot="federated-buttons"></div>
      </amplify-sign-in>
    </amplify-authenticator>

```

and try to type anything to the Context field, the code crashes. The reason is in the screenshot: there is no default in the switch in `AmplifySignIn.handleFormFieldInputChange`. Therefore, the code crashes in the `handleFormFieldInputWithCallback` method. In AmplifySignUp, there is such a default so the code does not crash.

### Expected behavior

I expect a non-crashing code in case of any custom form fields.

### Reproduction steps

See the above code snippets, then type anything to the context field.

### Code Snippet

```javascript
// Put your code below this line.

See it in the description.
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

N/A

### Manual configuration

N/A

### Additional configuration

N/A

![Cursor_and_AnyUpp_admin](https://user-images.githubusercontent.com/516425/113940255-74618400-97fd-11eb-81e0-66d536039aae.jpg)

**Comment by hkjpotato** [comment]
Hello @molnarzs, we have merged [PR](https://github.com/aws-amplify/amplify-js/pull/8192) that fixes this issue. 

This will be available in `aws-amplify@unstable` shortly and will be released in
the next release cycle. Please let us know if the issue persists afterwards.

Thanks.
