### ISSUE TITLE
SSR in Next js app not working when deployed on ECS Fargate

### ISSUE THREAD

**Issue by asp3** [aws-amplify/amplify-js#8049]
### Before opening, please confirm:

I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

obalPackages:
    @gxl/epub-parser: 2.0.3
    aws-cdk: 1.91.0
    depcheck: 1.2.0
    emus: 0.9.0
    expo-cli: 4.0.7
    ios-deploy: 1.11.4
    modclean: 3.0.0-beta.1
    npm: 6.14.6
    react-devtools: 4.8.2
    react-native-cli: 2.0.1
    serverless: 2.23.0
    verdaccio: 4.11.3
    webpack: 5.17.0

### Describe the bug

We currently have a docker image that works perfectly locally, and is now deployed on ECS using fargate. However, when trying to use SSR here, we end up with a 500 Server error, and by checking the logs it seems that it says the user is not authenticated when checking await Auth.currentCredentials() from const { Auth } = withSSRContext(context). 

However, when pulling and running the exact same docker image locally on the same port, everything works as expected and the user is properly authenticated. 

I recently debugged the issue with an expert from the ECS team, and it looks like none of the calls are being blocked and all traffic is being sent/received properly, and they believe that the issue is with the amplify-js. Is there some configuration we are missing, or is this possibly a bug with the amplify-js library? We have set up SSR using the blog (https://aws.amazon.com/blogs/mobile/ssr-support-for-aws-amplify-javascript-libraries/). 

### Expected behavior

On the deployed ECS instance, SSR should return authenticated: true. 

### Reproduction steps

Create sample app with SSR
Deploy on ECS
Authenticate and try to get the user using SSR

### Code Snippet

```javascript
 Amplify.configure({
    ...aws_exports,
    oauth: {
        ...oauth
    },
    ssr: true
});
...
export async function getServerSideProps(context) {
    const { Auth, API } = withSSRContext(context);

    console.log(await Auth.currentCredentials());
    // returns and object with a key authenticated: true when running locally, but authenticated: false when running on ECS with the same image
}
```

### Log output

<details>

```
// Put your logs below this line
// Logs from ECS 
{
identityId: 'xxxx',
accessKeyId: 'xxxxxxx',
secretAccessKey: 'xxxxxxx',
sessionToken: 'xxxxx',
expiration: 2021-04-08T00:28:15.000Z,
authenticated: false
}

// Logs from Docker Image running locally  
{
identityId: 'xxxx',
accessKeyId: 'xxxxxxx',
secretAccessKey: 'xxxxxxx',
sessionToken: 'xxxxx',
expiration: 2021-04-08T00:28:15.000Z,
authenticated: true
}

```

</details>

**Comment by wlee221** [comment]
Hello @asp3, we don't currently support SSR with Next.js on an ECS Fargate instance. We will mark this as a feature request.

**Comment by asp3** [comment]
Update: Running on EC2 leads to the same issue

**Comment by ericclemmons** [comment]
@asp3 Can you share your `package.json` and `Dockerfile`?

I was reproducing this today, but was experiencing issues with `docker run`, but you said this worked locally.

Do you have a public URL I can hit that's not working? I'm happy to debug a live instance as well in the meantime.

**Comment by zul-yang** [comment]
@wlee221 Hi William, are there any updates on SSR with Next.js on an ECS Fargate? Thanks!

**Comment by nadetastic** [comment]
Hi @Riglanto 👋,

I've been working to reproduce this issue, and although I have encountered a potential issue, it may not be quite inline with what you are experiencing. 

Could you clarify - 
- How you are authenticating the user?
- Are you federating/social auth or using Cognito user pools?
- What version of `aws-amplify` are you using?

Some context on my experience - I am able to deploy the app via Fargate successfully, using `v5.0.4`. I placed Auth call under `getServerSideProps` like so:

```js
export async function getServerSideProps({ req }) {
  const SSR = withSSRContext({ req });

  let authResponse;

  try { authResponse = await SSR.Auth.currentCredentials(); }
  catch(err){ authResponse = err; }

  return {
    props: { creds: JSON.stringify(authResponse) }
  }
}
```

After federating with google, this returns `NotAuthorizedException` but a refresh returns credentials. Also, the task does not crash.

**Comment by nadetastic** [comment]
Following up on this issue, I am able to get a Next 12 app working as expected with aws-amplify on ECS. They main thing to note here is if you authenticate on the client side without sending a request to the server - or the inverse where you try to send a request to the server without being authenticated you will face some of these issues.

For now I'll go ahead and close this issue out but let me know if you have any questions. @Riglanto @zul-yang
