### ISSUE TITLE
remove image option for S3Album

### ISSUE THREAD

**Issue by 19bharatvikram** [aws-amplify/amplify-js#805]
Feature Request

No functionality to remove image from S3Album (aws-amplify-react)

There should be a option to remove accidently added images in S3Album picker

**Comment by ceich** [comment]
I am adding this to a containing component using the `select` prop and `onSelect` hook (cf. #2215); at least in my case, deletion is best handled by the client of `S3Album`.

**Comment by ceich** [comment]
Since very little of the coded functionality of `S3Album` is documented, would the code owners please confirm that the best way for the parent to signal that files have been deleted is to change the `ts` prop?

**Comment by ceich** [comment]
Specifically, these are the `S3Album` props I care about, and how I'm using them in a containing component, whose purpose is to help its parent maintain a list of the album photos in AppSync:
```
  s3AlbumProps = ({level, path}) => ({
    // Addition support
    picker: !!this.props.onLoad,
    accept: 'image/*', // BUG: ignored by S3Album
    pickerTitle: 'Add a Photo',
    fileToKey: this.fileToKey,
    onLoad: this.handleUpload,
    // Deletion support
    select: !!this.props.onDelete,
    onSelect: this.handleSelect,
    // Basic props
    level: level,
    path: `${path}/`,
    theme: this.theme,
    ts: this.state.ts // update to force a refresh of the album from S3
  });
```
My intent is to update `ts` whenever files are deleted, which will make `S3Album` call `list`.

**Comment by ceich** [comment]
The above approach seems to work.

I used `Promise.all` to ensure that all the file deletes were complete, and set `ts` in the subsequent `then` function:
```
    Promise.all(selectedItems.map(item => {
      return Storage.remove(item.key, { level })
      .then(data => that.toS3Object(item))
      .catch(error => error);
    }))
    .then(deletedItems => {
      onDelete(deletedItems);      
      that.setState({
        selectedItems: [],
        ts: new Date().getTime()
      });
    })
```

**Comment by elorzafe** [comment]
@ceich We are missing you around here ❤️  I hope you are still using Amplify.

**Comment by ericclemmons** [comment]
Closing as `aws-amplify-react` is in maintenance with the release `@aws-amplify/ui-react`:
> https://docs.amplify.aws/ui/storage/s3-album/q/framework/react
