### ISSUE TITLE
Error: No credentials, applicationId or region when using PinPoint Analytics (Possible dependency version mismatch?)

### ISSUE THREAD

**Issue by HieronymusLex** [aws-amplify/amplify-js#8053]
### Before opening, please confirm:

I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

Analytics

### Amplify Categories

analytics

### Environment information

<details>

```
# Put output below this line

Yarn: 1.22.5 - ~/.yarn/bin/yarn
npm: 6.14.1 - ~/.nodenv/versions/12.13.0/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
Browsers:
  Chrome: 89.0.4389.114
npmPackages (relevant):
@aws-amplify/analytics: ^4.0.17 => 4.0.17
@aws-amplify/api: ^3.2.24 => 3.2.24
@aws-amplify/auth: ^3.4.24 => 3.4.24
@aws-amplify/core: ^3.8.16 => 3.8.16
@aws-amplify/interactions: ^3.3.24 => 3.3.24
@aws-amplify/storage: ^3.3.24 => 3.3.24
@aws-amplify/ui-vue: ^1.0.3 => 1.0.3
```

</details>

### Describe the bug

I'm trying to add Pinpoint analytics to the [Serverless Airline](https://github.com/aws-samples/aws-serverless-airline-booking) however when calling `Analytics.record` I'm getting an error stating `Error: No credentials, applicationId or region`. I followed the Amplify docs for adding analytics, i.e. `amplify add analytics` the only difference is `import { Analytics } from '@aws-amplify/analytics'` rather than `import { Analytics } 'aws-amplify'` . I did try with the latter also but it didn't make a difference.

Debugging in chrome show [this call to get credentials](https://github.com/aws-amplify/amplify-js/blob/main/packages/analytics/src/Providers/AWSPinpointProvider.ts#L153) is returning null. Based on [this comment](https://github.com/aws-amplify/amplify-js/issues/3484#issuecomment-504096004) I reverted `@aws-amplify/analytics` to 1.2.16 which removed the error in the console but no data is being sent.

### Expected behavior

Analytics works obtains credentials as expected and uses these to send data to pinpoint

### Reproduction steps

1. Deploy the serverless airline web app (or a representative app with the aforementioned versions)
2. Add analytics i.e. `amplify add analytics`
3. Attempt to record analytics using PinPoint

### Code Snippet

```javascript
// Put your code below this line.
import { Analytics } from '@aws-amplify/analytics'
await Analytics.record({
  name: 'search'
})
```

### Log output

<details>

No additional useful logs reported using debug level logging

</details>

### aws-exports.js

```
const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:xxx-xxx-xxx-xxx-xxxx",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_xxxxxx",
    "aws_user_pools_web_client_id": "xxxxxxxxxx",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xxxxx.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_mobile_analytics_app_id": "xxxxxxxxxxx",
    "aws_mobile_analytics_app_region": "eu-west-1"
};
```

**Comment by chrisbonifacio** [comment]
I don't see it in your environment information, but would you happen to have `aws-amplify` installed as well as the `@aws-amplify` packages?

**Comment by michaelgmcd** [comment]
@chrisbonifacio I've been struggling with this issue for the past couple of days. Happy to walk through some steps here. I'd prefer not to use the "aws-amplify" package as it adds a lot of extra dependencies, but I've tried with/without it with no luck. I'm not using the amplify CLI for my infrastructure (I'm using the aws-cdk). I've tried enabling unauthenticated identities in my identity pool and several other solutions from google as well.

**Comment by michaelgmcd** [comment]
For me, the issue is the line below. Despite having auth configured (and being able to log in via the user pool), it's always null:
`const credentials = await Credentials.get();`
https://github.com/aws-amplify/amplify-js/blob/d59880c4a427efadfd4c06961e352ad678914721/packages/analytics/src/Providers/AWSPinpointProvider.ts#L720

**Comment by chrisbonifacio** [comment]
It looks like most of your scoped amplify packages are v3 but your analytics package is on v4. I think you might have to either upgrade the others to v4 as well, or downgrade analytics to v3. Might be quicker to downgrade, so could you do that real quick and let me know it helps?

**Comment by michaelgmcd** [comment]
Hey thanks for the response. Running `npm dedupe` in addition to upgrading everything was the solution. The analytics module had it's own nested core module.

**Comment by chrisbonifacio** [comment]
Awesome! You were right on the money about it being caused by the dependencies :smile:

Glad you got it working again. Enjoy the rest of your day!
