### ISSUE TITLE
DataStore can't delete items on belong-to relation

### ISSUE THREAD

**Issue by marlonmarcello** [aws-amplify/amplify-js#8068]
### Before opening, please confirm:

I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

GraphQL API, DataStore

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 166.14 MB / 32.00 GB
    Shell: 3.2.1 - /usr/local/bin/fish
  Binaries:
    Node: 12.18.3 - ~/n/bin/node
    Yarn: 1.22.10 - ~/npm/bin/yarn
    npm: 7.5.2 - ~/npm/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 87.0
    Safari: 14.0.3
  npmGlobalPackages:
    @aws-amplify/cli: 4.46.1
    @marlonmarcello/vite-plugin-pug: 1.0.3
    @wethegit/preact-stickerbook: 1.0.2
    @wethegit/sweet-potato-components: 0.0.3
    @wethegit/sweet-potato-cooker: 0.9.0
    @wethegit/sweet-potato-peeler: 0.3.8
    node-gyp: 7.1.2
    npm: 7.5.2
    twosg: 0.1.0
    tpci-tcgportal: 1.0.0
    yarn: 1.22.10

```

</details>

### Describe the bug

Schema:
```graphql
type Project @model {
  id: ID!
  name: String!
  emails: [Email] @connection(keyName: "byProject", fields: ["id"])
}

type Email @model @key(name: "byProject", fields: ["projectID"]) {
  id: ID!
  title: String!
  language: String!
  body: String!
  projectID: ID!
  project: Project @connection(fields: ["projectID"])
}
```
Amplify models generated with `amplify codegen models`:
```ts
export declare class Project {
  readonly id: string;
  readonly name: string;
  readonly emails?: (Email | null)[];
  constructor(init: ModelInit<Project>);
  static copyOf(source: Project, mutator: (draft: MutableModel<Project>) => MutableModel<Project> | void): Project;
}

export declare class Email {
  readonly id: string;
  readonly title: string;
  readonly language: string;
  readonly body: string;
  readonly project?: Project;
  constructor(init: ModelInit<Email>);
  static copyOf(source: Email, mutator: (draft: MutableModel<Email>) => MutableModel<Email> | void): Email;
}
```
Note: notice the model is missing `projectID` as well.

Given the following schema and models, when trying to delete a `Project` record with `Emails` DataStore errors:
```js
const project = await DataStore.query(Project, ID);
DataStore.delete(project);
// Unhandled Rejection (NotFoundError): Failed to execute 'index' on 'IDBObjectStore': The specified index was not found.
```
Same goes for the other way around, trying to delete an `Email` gives the same error.

### Expected behavior

When deleting a parent record with a `belogs-to` relation, both the parent and children should be deleted.

### Reproduction steps

`amplify init`
`amplify add api`
Select GraphQL, go through base steps and use the schema provided above
`amplify codegen models`
Add a Project record
Add an Email record to that Project
Try to delete Project

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi 👋 Thank you for raising this issue. I was able to reproduce this issue where deleting documents with a Belongs to relationship does not delete related/connected documents.

Reading the documentation, I noticed that it specifies

> When you delete a parent object in a one to many relationship, the children will also be removed from the DataStore and mutations for this deletion will be sent over the network. 
> 
> However, in a many to many relationship the children are not removed and you must explicitly delete them.
https://docs.amplify.aws/lib/datastore/relational/q/platform/js#deleting-relations

It does not mention Belongs to relationships.

I have reached out to the team for clarification if this behavior is to be expected.

In the meantime, if you were to change your schema to this, you should see the Emails being deleted along with the related Project

```
type Project @model {
  id: ID!
  name: String!
  emails: [Email] @connection(keyName: "byProject", fields: ["id"])
}

type Email @model @key(name: "byProject", fields: ["projectID"]) {
  id: ID!
  title: String!
  language: String!
  body: String!
  projectID: ID!
}
```

**Comment by chrisbonifacio** [comment]
I'm able to reproduce this consistently. Labeled this as a bug and have made the team aware.

**Comment by marlonmarcello** [comment]
Thanks for investigating it @chrisbonifacio !

**Comment by ArkamJ** [comment]
Hi @marlonmarcello

Can you upgrade to the latest version of Amplify and let us know if you are still experiencing this issue?

**Comment by sammartinez** [comment]
Hey @marlonmarcello, I am going to resolve this issue for now as we have not heard from you in over 7+ days. Please let us know if you are still experiencing this issue on the latest version and we can reopen this issue. Thanks!

**Comment by Gab1988** [comment]
Hi @chrisbonifacio 

We are also experiencing the same issue with the following schema when I attempt to delete a parent object (workspace)
While instead deleting the children objects (entity) does work

```

type Workspace
  @model
  @auth(
    rules: [
      { allow: private }
      { allow: public } # Allows access with API key
    ]
  )
  @key(name: "UserWorkspaces", fields: ["userID"]) {
  id: ID!
....
  entities: [EntityAI] @connection(keyName: "WorkspaceEntities", fields: ["id"])
  users: [ID]
}

type Entity
  @model
  @auth(
    rules: [
      { allow: private }
      { allow: public } # Allows access with API key
    ]
  )
  @key(name: "WorkspaceEntities", fields: ["workspaceID"]) {
  id: ID!
  owner: String
....
  workspaceID: ID!
}

```

Here the packages I'm using :

```
 "@aws-amplify/core": "4.2.2",
 "@aws-amplify/datastore": "3.3.0",
```

**Comment by Gab1988** [comment]
Never mind the issue was a misspelling in the configuration of the key for the connection between the workspace and another entity
If it can help anyone this issues occurs if you declare incorrectly the connection between 2 entities (e.g. my case)

`type Workspace
  @model
  @auth(
    rules: [
      { allow: private }
      { allow: public } # Allows access with API key
    ]
  )
  @key(name: "UserWorkspaces", fields: ["userID"]) {
  id: ID!
//////
  trainingLogs: [TrainingLog]
    @connection(**_key_**: "WorkspaceTrainingLogs", fields: ["id"]) -- issue here as it was key rather than keyName
  entities: [EntityAI] @connection(keyName: "WorkspaceEntities", fields: ["id"])
  users: [ID]
}

type TrainingLog
  @model
  @auth(
    rules: [
      { allow: private }
      { allow: public } # Allows access with API key
    ]
  )
  @key(name: "WorkspaceTrainingLogs", fields: ["workspaceID"]) {
  id: ID!
/////
  workspaceID: ID!
}`
