### ISSUE TITLE
GraphQL subscribe method throws Unexpected reserved word 'yield' error when using with redux-saga

### ISSUE THREAD

**Issue by shubhamsharma98** [aws-amplify/amplify-js#8078]
### Before opening, please confirm:

I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 913.13 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 78.8.0
    Safari: 14.0.3
  npmPackages:
    @testing-library/jest-dom: ^5.11.4 => 5.11.10
    @testing-library/react: ^11.1.0 => 11.2.5
    @testing-library/user-event: ^12.1.10 => 12.8.3
    antd: ^4.14.1 => 4.14.1
    aws-amplify: ^3.3.26 => 3.3.26
    aws-amplify-react: ^4.2.30 => 4.2.30
    dayjs: ^1.10.4 => 1.10.4
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    react-icons: ^4.2.0 => 4.2.0
    react-redux: ^7.2.3 => 7.2.3
    react-router-dom: ^5.2.0 => 5.2.0
    react-scripts: 4.0.3 => 4.0.3
    redux: ^4.0.5 => 4.0.5
    redux-saga: ^1.1.3 => 1.1.3
    uuid: ^3.4.0 => 3.4.0
    web-vitals: ^1.0.1 => 1.1.1
  npmGlobalPackages:
    @aws-amplify/cli: 4.45.2
    nodemon: 2.0.7
    npm: 7.6.3
    yarn: 1.22.10


```

</details>

### Describe the bug

When using graphql subscriptions inside redux-saga generator functions, the method doesn't allow usage of `yield`. 

```js
export function* rowFlagListenerSaga() {
  try {
    yield API.graphql(graphqlOperation(onUpdateDailyFinancesEntry)).subscribe({
      next: (record) => {
        console.log('record', record);
        yield put(actions.setNewRowFlag(record.value.data.onUpdateDailyFinancesEntry))  //throws error: Unexpected reserved word 'yield'
      }
    });
  } catch (err) {
    console.error("rowFlagListenerSaga err: ", err);
  }
}

```

### Expected behavior

`yield` able to execute the next action resolver. 

### Reproduction steps

Try setting a amplify subscribe method inside any redux-saga generator function and you should notice the same error.

### Code Snippet

```javascript
// Put your code below this line.
export function* rowFlagListenerSaga() {
  try {
    yield API.graphql(graphqlOperation(onUpdateDailyFinancesEntry)).subscribe({
      next: (record) => {
        console.log('record', record);
        yield put(actions.setNewRowFlag(record.value.data.onUpdateDailyFinancesEntry))
      }
    });
  } catch (err) {
    console.error("rowFlagListenerSaga err: ", err);
  }
}

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by iartemiev** [comment]
Hi @shubhamsharma98, the `subscribe` function does not return a generator, so it's not expected to work with `yield`.

**Comment by shubhamsharma98** [comment]
Thanks @iartemiev , I did not know that. Any recommendations as to how can I make subscribe work within redux-saga? Or should I even?

**Comment by iartemiev** [comment]
Assuming I understand the intent correctly, I don't see the use case for redux-saga here, since the callback passed to `subscribe` is getting invoked as a result of network events. Whereas sagas are meant to be invoked by some clientside action. If you're using redux, you can just dispatch the event from the subscribe callback, e.g., 

```js
const subscription = API.graphql(API.
    graphqlOperation(subscriptions.onCreateTodo)
).subscribe({
    next: ({ value: {data} }) => dispatch({type: TODO_CREATED, data.onCreatePost })
});
```

**Comment by shubhamsharma98** [comment]
Okay, thanks for this example. I was looking to do this and meanwhile also learned to use the useEffect hook instead to invoke subscription. Appreciate your help!
