### ISSUE TITLE
[Feedback]Facebook is requiring Site URL to return 200

### ISSUE THREAD

**Issue by krucraft** [aws-amplify/amplify-js#8082]
**Page**: [`/lib/auth/social/q/platform/js`](https://docs.amplify.aws/lib/auth/social/q/platform/js)

**Feedback**:

I received the following email from Facebook:

```
In order to keep our Facebook platform and community safe, we periodically review apps for compliance. We need the following action from you on your app, [Redacted], in order to approve your app’s continued operation on our platform.

URL(s) listed on your app dashboard settings could not be accessed for platform compliance review. Kindly make sure that the following field(s) on your app dashboard are working correctly:
Website: Site URL

The corresponding URL(s) should return a successful HTTP status code. You can verify this using the Sharing Debugger.
- Sharing Debugger: https://developers.facebook.com/tools/debug/sharing/
- Compliant response codes: 200-299
- Violating response codes: 100-199, 300-399, 400-499, 500-599

Please also whitelist the user agent strings or the IP addresses (more secure) used by the crawler. For detailed instructions, please visit: https://developers.facebook.com/docs/sharing/webmasters/crawler.

For Google Package Name(s) and iPhone Store ID(s), please make sure that these are publicly available.

Kindly apply the requested changes to prevent your app from being restricted on our platform. You can check your app dashboard to verify if the violating fields are now compliant, otherwise you will receive an automated alert as soon as we've detected that the fields are compliant.

Thank you for your cooperation in our continued efforts to keep our platform safe.

Facebook Developer Operations Team
```

The problem is that the Facebook team is using a web crawler to determine the response from the Site URL. The instructions on Amplify's documentation specifies to set the Site URL to https://\<your-user-pool-domain>/oauth2/idpresponse which will return code 400 to their crawler because the crawler does not include any oAuth data in the request.

I imagine anyone who has configured Facebook oAuth per this method has received this email and perhaps all of our oauth integrations will be disabled shortly?

I have not been successful in reaching out to the Facebook team. Their bug submission form is also broken. 

Please advise on a best course of action.

**Comment by sammartinez** [comment]
@amhinson and @nickarocho Let's see if we find some time to chat on this Friday

**Comment by krucraft** [comment]
Any update on this? Facebook has disabled our app. They will not be able to re-enable Facebook login without returning a 200-299 response code. The instructions for Amplify Facebook oauth [here](https://docs.amplify.aws/lib/auth/social/q/platform/js/#configure-auth-category) will lead to the app being disabled by Facebook.

**Comment by cnbrkkaya** [comment]
still waiting for an update ?

**Comment by nadetastic** [comment]
Hi @krucraft @cnbrkkaya,

Following up on this - the documentation incorrectly states to add the cognito userpool url instead of your website URL when adding a platform. [This PR](https://github.com/aws-amplify/docs/pull/4731) will clarify the  steps.

**Comment by krucraft** [comment]
We ended up disabling Facebook login and migrating those users to new accounts with email/pass login given that I reported this issue over a year ago and they needed a way to access their account. Now we're migrating off Amplify and Cognito entirely.
