### ISSUE TITLE
Event should be fired or notification should appear after selecting MFA type

### ISSUE THREAD

**Issue by m-bilal-dev9** [aws-amplify/amplify-js#8084]
**Is your feature request related to a problem? Please describe.**
Yes, when ever user click on verify MFA type button no notification is being shown to user on MFA Set.
```
    <AmplifySelectMfaType
          MFATypes={{ TOTP: true, SMS: true, Optional: true }}
          authData={data}
        />
```

**Describe the solution you'd like**
After preferred MFA type is set for user an event should be fired OR at-least notification should appear `Preferred MFA type has been set`.

**Describe alternatives you've considered**
As a workaround I've added the link above the UI so user can navigate to another page.
```
  <p>
        Verify preffered MFA type and click here to
        <Link
        to={// redirect to another page}
        >
          {' '}
          Complete Signup
        </Link>
      </p>
       <AmplifyAuthenticator usernameAlias="email">
        <AmplifySelectMfaType
          MFATypes={{ TOTP: true, SMS: true, Optional: true }}
          authData={data}
        />
      </AmplifyAuthenticator>
```

**Additional context**
I tried to use onAuthUIStateChange() function but that's not relevant in few use cases.
![image](https://user-images.githubusercontent.com/77671366/114538088-659b2700-9c6c-11eb-84c5-ad7579d25dfc.png)

**Comment by tannerabread** [comment]
Hi 👋 Closing this as resolved. We no longer support this component but you can create your own flow with selecting MFA type as shown [here](https://docs.amplify.aws/lib/auth/mfa/q/platform/js/#setup-mfa-type).

Thank you!
