### ISSUE TITLE
DataStore: How to handle a partial sync up to AppSync?

### ISSUE THREAD

**Issue by PeteDuncanson** [aws-amplify/amplify-js#8087]
I've run into a bit of a problem and I don't know enough about DataStore to know how to fix it. In short how should I handle a partial sync from DataStore to AppSync when only half of a relation has been pushed up?

Last week our whole app (its an internal CRM tool) just died after you logged in. On investigation it seems that an entity (Address in this case) had a reference to another entity (Customer) that didn't exist. The Address had the Customer ID but in DynamoDB there wasn't an Customer record to match. 

Checking the timestamps we saw something odd, we store a "signUpDateTime" field that we set ourselves in our code, this was for the day before the create time timestamp that AppSync adds in for us! Logically what we think happened is that when someone entered a Customer and Address via the App it saved it all locally via DataStore and then got stopped from syncing half way through, so it synced the Address but was prevented from syncing the Customer (our guess is laptop got shut as it was at the end of the work day).

Come the next morning everyone logs in and starts syncing down from AppSync in their browsers, DataStore hits the broken relation and gets stuck on retrying it which blocked the whole app.

It blocked the app as we wait until DataStore has finished syncing before we let the users loose (via a "please wait" modal), we did this as we had issues with half views or other errors if data was initially missing when new users logged in so we went the brute force option of just stopping them doing anything until DataStore hub tells us its ready.

To fix the issue quickly we created a new Customer with the missing ID via AppSync UI which got unstuck and then we had to do some digging to try to piece together missing contract details for the customer.

**Possible solutions/ideas that I could do**

I could remove that pop up that blocks any interactions and just let DataStore keep retrying under the hood, this would make the app responsive at least. However in that instance we have had a data lose. That Customer doesn't exist and we currently wouldn't have any way to know that they are missing, how would I catch that data lose and flag it up some how?

I could try to catch the error and handle it some how, seems dangerous though to be trying to guess or patch what DataStore would have done?

Other than that I'm out of ideas. I'm hoping this is a known "thing" and there is a pattern or advice on how to handle it gracefully, hence this issue! :)

**Which Category is your question related to?**

DataStore

**Amplify CLI Version** 

v4.46.1

**What AWS Services are you utilizing?**

AppSync, ElasticSearch

**Provide additional details e.g. code snippets**

Error syncing:
![image](https://user-images.githubusercontent.com/1674590/114544342-6757f100-9c52-11eb-87ac-389d48a8d4bd.png)

Timestamps:
![image](https://user-images.githubusercontent.com/1674590/114544442-8787b000-9c52-11eb-8e38-86b55a049967.png)

**Comment by chrisbonifacio** [comment]
Hey 👋 Thanks for raising this! After reading over this issue, it appears to be more of a general question or topic for discussion and will be labeled as such. This is to differentiate it from the other types of issues and make sure it receives the attention it deserves. 

I have also asked a member of the team that, to my knowledge, is focused on this area of Amplify to take a look and give their feedback when/if they can.

I hope that helps!
