### ISSUE TITLE
[REGRESS] Can't globally configure Auth since @aws-amplify/core@3.8.13

### ISSUE THREAD

**Issue by WeatherGod** [aws-amplify/amplify-js#8091]
### Before opening, please confirm:

I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Linux 4.18 CentOS Linux 8
    CPU: (8) x64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
    Memory: 1.85 GB / 23.29 GB
    Container: Yes
    Shell: 6.20.00 - /bin/tcsh
  Binaries:
    Node: 10.24.0 - /usr/bin/node
    npm: 6.14.11 - /usr/bin/npm
  Browsers:
    Firefox: support!
Mozilla Firefox 78.8.0esr
  npmPackages:
    @aws-amplify/ui-components: ^0.10.4 => 0.10.4 
    @aws-amplify/ui-react: ^0.2.34 => 0.2.38 
    @testing-library/jest-dom: ^4.2.4 => 4.2.4 
    @testing-library/react: ^9.5.0 => 9.5.0 
    @testing-library/user-event: ^7.2.1 => 7.2.1 
    aws-amplify: ^3.3.14 => 3.3.26 
    ol: ^6.5.0 => 6.5.0 
    parcel-bundler: ^1.12.4 => 1.12.5 
    react: ^16.14.0 => 16.14.0 
    react-datepicker: ^3.7.0 => 3.7.0 
    react-dom: ^16.14.0 => 16.14.0 
    react-scripts: ^3.4.3 => 3.4.4

```

</details>

### Describe the bug

When I updated my package set, my working react webapp couldn't authenticate users anymore. I narrowed down the package changes to be specifically the following changeset (although, I haven't narrowed down exactly what versions the break was introduced):
```
@aws-amplify/core@3.8.13  -> @aws-amplify/core@3.8.21
@aws-sdk/client-cognito-identity@1.0.0-rc.4 -> @aws-sdk/client-cognito-identity@3.6.1
@aws-sdk/credential-provider-cognito-identity@1.0.0-rc.4 -> @aws-sdk/credential-provider-cognito-identity@3.6.1
```

My top-level code did a configure call like so:
```
Amplify.configure({
        aws_cognito_region: process.env.REACT_APP_AWS_REGION,
        aws_user_pools_id: process.env.REACT_APP_USER_POOL_ID,
        aws_user_pools_web_client_id: process.env.REACT_APP_CLIENT_ID,
        aws_cognito_identity_pool_id: process.env.REACT_APP_IDENTITY_POOL_ID,
        aws_mandatory_sign_in: "enable"
});
```

This worked fine in the older version, and also follows what the current documentation shows here: https://docs.amplify.aws/lib/client-configuration/configuring-amplify-categories/q/platform/js

But, with the latest version, this results in an error show here:
![image](https://user-images.githubusercontent.com/291576/114617679-718be680-9c76-11eb-9273-c99352be32b1.png)

However, if I do the configuration directly with Auth, everything works:
```
Auth.configure({
        identityPoolRegion: process.env.REACT_APP_AWS_REGION,
        region: process.env.REACT_APP_AWS_REGION,
        userPoolId: process.env.REACT_APP_USER_POOL_ID,
        userPoolWebClientId: process.env.REACT_APP_CLIENT_ID,
        identityPoolId: process.env.REACT_APP_IDENTITY_POOL_ID,
        mandatorySignIn: true
});
```

### Expected behavior

The global configuration method should work as documented.

### Reproduction steps

Described above using a basic react app with authentication through amplify. Possibly relevant, the cognito resources were created through Terraform, but both the working and non-working code used the same cognito resources.

### Code Snippet

Code snippets in the bug description.

### Log output

I can provide additional logs if needed, but let's hash this out a bit first.

**Comment by iartemiev** [comment]
We often see this kind of behavior when duplicate Amplify dependencies get installed inadvertently. Could you please try deleting your node modules and lock file, then reinstalling your app's dependencies, e.g.,
```bash
rm -rf node_modules yarn.lock package-lock.json
yarn [or npm i]
```
Afterward, please let us know if the issue persists.

**Comment by WeatherGod** [comment]
Yes, this behavior persisted after removing node_modules and reinstalling packages. I am able to reproduce this reliably with my webapp. Today, I'll try to make an SSCCE webapp that demonstrates the problem, hopefully with a "good" and "bad" package-lock file.

**Comment by WeatherGod** [comment]
Heh, never had this experience before. Usually, when I make an SSCCE, I end up figuring out exactly what the problem was, or at the very least, I can reproduce exactly the problem I had. This time, my (almost) SSCCE is producing worst behavior than with my full app. So I am still investigating this on my end a bit.

Question, is a difference in behavior expected with `Auth.configure()` if one imports like this: 
`import Auth from '@aws-amplify/auth';` 
versus: 
`import { Auth } from 'aws-amplify';`

I don't have a lot of JS experience, so I don't know if those two imports are supposed to be considered as equivalent or not.

**Comment by WeatherGod** [comment]
Ok, I think I have made a bit of headway in this. For some reason, and I am still not 100% on this, the problem is coming from whatever the version strings are in `prackage.json` for the three aws-amplify sub-modules. Even though they are set as being "at least" (e.g. - "@aws-amplify/auth": "^3.4.17"`), it apparently makes a difference what this is set to for clean installs and upgrades. That doesn't seem right at all, but I don't have experience with `npm` to know if that is possible.

**Comment by WeatherGod** [comment]
Not stale, stale-bot. Just waiting for a human.

**Comment by tannerabread** [comment]
Hi @WeatherGod, are you still struggling with this? Apologies for not hearing from a human in so long, your comment about the `package.json` was probably indicative of the reason you were having issues. 

Amplify has changed to all named exports in recent versions and no longer recommends importing packages separately as it causes problems like you experienced. I didn't see the actual scoped imports in your environment info, but it would now be recommended to only import `aws-amplify` and none of the packages such as `@aws-amplify/auth` except for more advanced use cases.

Can you confirm if you are still experiencing issues?

**Comment by WeatherGod** [comment]
I have since done some package refreshes that seems to have eliminated the problem. I will look into implementing the approach you suggested with the next round of updates coming up soon. Thank you for confirming my suspicions that the issue was likely due to how the sub-packages were being handled in the `package.json` file.

**Comment by chrisbonifacio** [comment]
@WeatherGod 

This sort of issue was common enough that we ended up creating a troubleshooting page specifically for making sure there are no duplicate dependencies and upgrading amplify package versions to the latest to ensure compatibility.

https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js/

Let us know if this helps and, if not, we'll re-open this issue and go from there. Thanks for confirming you are no longer experiencing this issue after updating your packages!
