### ISSUE TITLE
Please add PushNotification.removeAllDeliveredNotifications() to @aws-amplify/pushnotification

### ISSUE THREAD

**Issue by thenderson55** [aws-amplify/amplify-js#8092]
I want to be able to clear the Android badge count when opening my react-native mobile application.

Currently you can only clear the badge count by removing the actual push notifications.

The original react-native-push-notification library has this feature I think:

https://github.com/zo0r/react-native-push-notification#3-removealldeliverednotifications

**Comment by tannerabread** [comment]
Hi @thenderson55 we have recently released a rewritten Push Notification category with new features including the [ability to update the badge count](https://docs.amplify.aws/lib/push-notifications/app-badge-count/q/platform/react-native/#get-the-current-badge-count), can you try it out and let me know if it works for you?

You can follow the [migration steps here](https://docs.amplify.aws/lib/push-notifications/migrate-from-previous-version/q/platform/react-native/) or if you are starting again from scratch follow the [getting-started guide here](https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/react-native/)

**Comment by tannerabread** [comment]
Hi 👋 Closing this as resolved. This should be handled with the recent release of the rewritten Push Notification category mentioned above. 

If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with additional information so we can re-open this issue and be better able to assist you.

Thank you!
