### ISSUE TITLE
All injected service get null value when using authenticator UI

### ISSUE THREAD

**Issue by Beni312** [aws-amplify/amplify-js#8114]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
{
  "name": "test",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~11.0.0",
    "@angular/cdk": "~11.0.0",
    "@angular/common": "~11.0.0",
    "@angular/compiler": "~11.0.0",
    "@angular/core": "~11.0.0",
    "@angular/forms": "~11.0.0",
    "@angular/material": "~11.0.0",
    "@angular/platform-browser": "~11.1.1",
    "@angular/platform-browser-dynamic": "~11.1.1",
    "@angular/router": "~11.0.0",
    "@aws-amplify/ui-angular": "^1.0.7",
    "aws-amplify": "^3.3.27",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1101.1",
    "@angular/cli": "~11.0.1",
    "@angular/compiler-cli": "~11.0.0",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.19.12",
    "bootstrap": "~4.6.0",
    "bourbon": "^7.0.0",
    "codelyzer": "^6.0.1",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.10.2",
    "tslint": "~6.1.3",
    "typescript": "~4.0.5"
  }
}


```

</details>

### Describe the bug

When i use the authenticator component, the dependencies get null values.
On auth change, need to detect changes manually, and here i get undefined error.
If i remove the component from the html, the "ChangeDetectorRef" dependency loading correctly.

### Expected behavior

Should be able to inject dependencies.

### Reproduction steps

1. Use the package json i copied
2. Create a component that use authenticator component
3. Dependencies does not injected, get null values

### Code Snippet

Module

```
Amplify.configure({Auth: {
    mandatorySignIn: true,
    region: 'eu-west-1',
    userPoolId: 'eu-west-1_xxxxxxxxx',
    userPoolWebClientId: 'xxxxxxxxxxxxxxxxxxxx',
    identityPoolId: 'eu-west-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  }
});

@NgModule({
  declarations: [
    LoginComponent
  ],
  imports: [
    CommonModule,
    BrowserModule,
    BrowserAnimationsModule,
    AmplifyUIAngularModule
  ],
  providers: [
  ]
})
export class LoginModule { }


```
   

Component
```
@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {

  user: CognitoUserInterface | undefined;
  authState: AuthState;

  constructor(private readonly changeDetectorRef: ChangeDetectorRef) {
  }

  ngOnInit(): void {
  }

  authHandler(authState, authData) {
    this.authState = authState;
    this.user = authData as CognitoUserInterface;
    this.changeDetectorRef.detectChanges();
  }
}
```

html

  ```
<amplify-authenticator [handleAuthStateChange]="handler" *ngIf="authState !== 'signedin'"></amplify-authenticator>

  <div style="height: 600px" *ngIf="authState === 'signedin' && user" class="App">
    <amplify-sign-out></amplify-sign-out>
    <div>Hello, {{user.username}}</div>
    <!-- This is where you application template code goes -->
  </div>
```

### Log output

<details>

```
Uncaught (in promise) TypeError: Cannot read property 'detectChanges' of undefined
    at AmplifyAuthenticator.authHandler (main.js:46)
    at AmplifyAuthenticator.onAuthStateChange (14.js:133)
    at 14.js:80
    at Object.authUIStateHandler [as callback] (0.js:139)


```

</details>

**Comment by ErikCH** [comment]
@Beni312 Could you check a few things?

I noticed that you have an `authHandler`. This looks to be the code that sets the `authState` and `user` variables. 

Typically this is done with the `onAuthUIStateChange` method, and the first argument is a callback function that sets those values. It needs to be called from the `ngOnInit` like this.

```
import { onAuthUIStateChange, CognitoUserInterface, AuthState } from '@aws-amplify/ui-components';
...
export class AppComponent {
  user: CognitoUserInterface | undefined;
  authState: AuthState

  constructor(private readonly changeDetectorRef: ChangeDetectorRef) {}

ngOnInit() {
    onAuthUIStateChange((authState, authData) => {
      this.authState = authState;
      this.user = authData as CognitoUserInterface;
      this.changeDetectorRef.detectChanges();
    })
  }
...
```
Otherwise the `authState` variable will never receive the correct auth state.

You also have a `[handleAuthStateChange]="handler"` in your template. But I didn't see a `handler` method in the component you pasted.

This property will fire whenever the user signs in and signs out. You can use that as another way to keep track of the user state.

I would try to make those few changes first and see if that fixes your problem. Also all this code was taken from the Amplify Angular getting started guide for UI Components here. https://docs.amplify.aws/ui/auth/authenticator/q/framework/angular#recommended-usage
