### ISSUE TITLE
AmplifyAuthenticator: Set phone_number default dial_code

### ISSUE THREAD

**Issue by dayvough** [aws-amplify/amplify-js#8115]
Currently the default dial_code is `+1` and all the options are available. What if we wanted to build something for a select number of countries, why can't we restrict it only to just say `["+63"]`?

Also as a side note, I know you can set the default dial code via formFields on AmplifySignUp BUT if you set your code like this:
```js
<AmplifySignUp slot="sign-up" usernameAlias="phone_number"
  formFields={[
    {
      type: "phone_number",
      dialCode: "+63",
    }
  ]}
></AmplifySignup>
```

You would end up with the "Username cannot be empty" error.

And I know that formFields overrides the usernameAlias but then now I'm lost as to how I can parse the phone_number with the dialcodes and country prefixes.

**Comment by tannerabread** [comment]
This should now be handled by the [UI Authenticator component](https://ui.docs.amplify.aws/react/connected-components/authenticator/configuration#sign-up-attributes) via the sign-up attributes. If you are still experiencing this with that component please open a new issue in the [UI repo](https://github.com/aws-amplify/amplify-ui) as the component mentioned in the original post is now deprecated.
