### ISSUE TITLE
Auth.confirmSignIn() – 

### ISSUE THREAD

**Issue by marco910** [aws-amplify/amplify-js#8119]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (1) x64 Intel(R) Xeon(R) CPU E3-1220 v5 @ 3.00GHz
    Memory: 823.91 MB / 3.63 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.22.1 - /usr/bin/node
    npm: 6.14.12 - /usr/bin/npm
  npmPackages:
    amphtml-validator:  undefined ()
    arg:  undefined ()
    async-retry:  undefined ()
    async-sema:  undefined ()
    aws-amplify: ^3.3.1 => 3.3.1 
    aws-sdk: 2.756.0 => 2.756.0 
    axios: 0.20.0 => 0.20.0 (0.19.0)
    babel-loader:  undefined ()
    cache-loader:  undefined ()
    chalk:  undefined ()
    ci-info:  undefined ()
    comment-json:  undefined ()
    compression:  undefined ()
    conf:  undefined ()
    content-type:  undefined ()
    cookie:  undefined ()
    debug:  undefined ()
    devalue:  undefined ()
    escape-string-regexp:  undefined ()
    etag:  undefined ()
    file-loader:  undefined ()
    find-up:  undefined ()
    fresh:  undefined ()
    fuse.js: ^6.4.6 => 6.4.6 (3.6.1)
    gzip-size:  undefined ()
    http-proxy:  undefined ()
    ignore-loader:  undefined ()
    is-animated:  undefined ()
    is-docker:  undefined ()
    is-wsl:  undefined ()
    json5:  undefined ()
    jsonwebtoken:  undefined ()
    lodash.curry:  undefined ()
    lru-cache:  undefined ()
    nanoid:  undefined ()
    next: latest => 10.0.0 
    next-auth: 3.1.0 => 3.1.0 
    node-fetch:  undefined ()
    ora:  undefined ()
    postcss-flexbugs-fixes:  undefined ()
    postcss-loader:  undefined ()
    postcss-preset-env:  undefined ()
    qrcode.react: ^1.0.1 => 1.0.1 
    raw-body:  undefined ()
    react: ^16.13.1 => 16.14.0 
    react-dom: ^16.13.1 => 16.14.0 
    react-dropzone: 11.2.0 => 11.2.0 
    react-select-search: ^3.0.5 => 3.0.5 
    react-toastify: ^6.0.9 => 6.0.9 
    recast:  undefined ()
    resolve:  undefined ()
    semver:  undefined ()
    send:  undefined ()
    serverless-mysql: 1.5.4 => 1.5.4 
    source-map:  undefined ()
    sql-template-strings: 2.2.2 => 2.2.2 
    string-hash:  undefined ()
    strip-ansi:  undefined ()
    swr: 0.3.3 => 0.3.3 
    terser:  undefined ()
    terser-webpack-plugin:  undefined ()
    text-table:  undefined ()
    thread-loader:  undefined ()
    unistore:  undefined ()
  npmGlobalPackages:
    npm: 6.14.12


```

</details>

### Describe the bug

When trying to call `Auth.confirmSignIn()` with the user-object from `Auth.signIn`, the software token, and MFA type as parameters I'm getting a 400 response with the following:

`
{
code: "InvalidParameterException",
name: "InvalidParameterException",
message: "Missing required parameter Session"
}
`

The value of `session` in the user-object is `null`.

### Expected behavior

Verification of the MFA token and sign in.

### Reproduction steps

1. Configure a Cognito user pool with optional MFA (software token)
2. Set up Amplify Auth in React
3. Try to signIn with `Auth.signIn()` and pass the user-object to `Auth.confirmSignIn()`

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
`Auth.confirmSignIn` is expecting three arguments - the CognitoUser (returned from `Auth.signIn`), the MFA code, and the mfaType (string of "SMS_MFA" or "SOFTWARE_TOKEN_MFA". Are you also passing all of these to the function?

**Comment by marco910** [comment]
Hi @chrisbonifacio 
Yes, I've passed three arguments to `Auth.confirmSignIn`. The problem is that `Auth.confirmSignIn` is expecting a session id/object inside the user object returned from `Auth.signIn`, but the value of `session` inside the user object is `null`.

**Comment by chrisbonifacio** [comment]
What does the user object look like from the `Auth.signIn` response?

**Comment by marco910** [comment]
@chrisbonifacio 

Unfortunately, I don't have an example user object to show to you, but what I have in mind is that it looked "normal and correct". But the value for `session` was `null` and there were also no challenge names or params.

**Comment by chrisbonifacio** [comment]
Are you still running into this error or unable to reproduce it consistently?

**Comment by marco910** [comment]
@chrisbonifacio I will test it with a demo project in the next few days and give you feedback after that.

**Comment by chrisbonifacio** [comment]
@marco910 any updates on this?

**Comment by chrisbonifacio** [comment]
Closing for now as we have not heard back from you. If you're still experiencing this issue and need additional assistance, please feel free to re-open.

**Comment by marco910** [comment]
@chrisbonifacio Sorry for the late reply.

I have set up a test environment for the 2FA auth issue. The environment runs on Next.js. I also created a new user and enabled MFA "TOTP" for it.

After logging in with username, password and MFA code I'm a valid user object from Coginto (I think so) without any errors.
So, I think the issue method above is caused by my app.

Is it normal that I'm also able to login in without the MFA code when only using username and password? (MFA is set to optional in the user pool settings)

**Comment by chrisbonifacio** [comment]
@marco910 you mean you're able to log into the same user that has MFA enabled by only passing the username/password to `Auth.confirmSignIn` and not the MFA code? Or are you using `Auth.signIn`?

**Comment by chrisbonifacio** [comment]
@marco910 sorry for the delayed response but from your last comment it sounds like you're able to login if you provide the MFA code. Does that mean you're not experiencing issues anymore? I apologize if I'm misunderstanding.

**Comment by marco910** [comment]
@chrisbonifacio Now it's working as expected. Thanks for your help!
