### ISSUE TITLE
cognitoUser.signOut() leaves behind 3 key/value pairs

### ISSUE THREAD

**Issue by jrobbins-LiveData** [aws-amplify/amplify-js#8137]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 4.51 GB / 15.73 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.128
    Edge: Spartan (44.19041.906.0), Chromium (90.0.818.42)
    Internet Explorer: 11.0.19041.1
  npmGlobalPackages:
    aws-cdk: 1.98.0

```

</details>

### Describe the bug

Using the default `window.localStorage` handler, 3 key/value pairs are left behind after each logged-in user logs out.  Replacing the default storage handler with an instance of `CookieStorage` yields the same results, except 3 cookies are left behind.

On a system where many users are logging in and out all day, this will result in a lot of accumulated data.  In the case of `CookieStorage`, the overall header limits in AWS API Gateway (10,240 bytes) might thereby be exceeded, breaking the app.

### Expected behavior

I expected my call to `cognitoUser.signOut()` to completely remove all the key/value pairs generated by `cognitoUser.authenticateUser`.

### Reproduction steps

Write a simple vanilla HTML/JavaScript SPA using

```
<script src="https://cdn.jsdelivr.net/npm/amazon-cognito-identity-js@4.6.0/dist/amazon-cognito-identity.min.js"></script>
```

Assuming a Cognito User Pool is setup with a user and confirmed password, log in as that user via

```
              cognitoUser.authenticateUser(authenticationDetails, {
                onSuccess: function (result) {
                  console.log(
                    `newly logged in cognitoUser = ${cognitoUser.username}`
                  );
                },

                onFailure: function (err) {
                  console.error("authenticateUser error:", err);
                },
```

Then log out via

```
            cognitoUser.signOut();
```

Then observe your localStorage in your browser's dev tools to see the 3 stragglers:

![left-behind-local-storage](https://user-images.githubusercontent.com/79278744/115554196-35f7aa80-a27c-11eb-912e-ca2b47b34029.png)

### Code Snippet

```javascript
// Put your code below this line.
            cognitoUser.signOut();
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by sammartinez** [comment]
Thanks for reporting this @jrobbins-LiveData, we will be looking into this today.

**Comment by amhinson** [comment]
@jrobbins-LiveData It looks like you have [device tracking and remembering](https://aws.amazon.com/blogs/mobile/tracking-and-remembering-devices-using-amazon-cognito-your-user-pools/) enabled for your User Pool. These keys persist by default so a device can be remembered for a user's subsequent logins.

If you don't want this behavior, you could either disable device tracking in Cognito or call `cognitoUser.forgetDevice()` somewhere in your code. Would either of those solutions work for you?

**Comment by jrobbins-LiveData** [comment]
@amhinson, that makes perfect sense.  Is there a cleanup strategy if a PC is shared by many users?  Won't the browser's LocalStorage for an  app simply accumulate more and more of this triplet of items?  I know that LocalStorage is plenty big, but this also affects switching from LocalStorage to CookieStorage, and the cookie has a much more finite capacity.  If there's no "garbage collection", won't these keys accumulate to potential bad effect?

**Comment by amhinson** [comment]
Right now there isn't anything built into Amplify to do this automatically since every application could have a different expectation of what the desired garbage collection behavior would be. Perhaps you could use either of the solutions recommended in my last comment, or use the "Opt In" device remembering feature (which could minimize the number of keys on a shared PC) and implement your own localStorage/cookie cleanup? Deleting those keys manually shouldn't have any effect on Amplify functionality aside from just not remembering the device.

**Comment by jrobbins-LiveData** [comment]
That makes good sense to me...thanks for helping me understand the choices available.  I'm sure we'll be able to navigate them and come up with something good for our customers.
