### ISSUE TITLE
SyntaxError: await is only valid in async function Amplify Serverless Function

### ISSUE THREAD

**Issue by myfairshare** [aws-amplify/amplify-js#8140]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication, REST API, GraphQL API, DataStore, Storage

### Amplify Categories

function

### Environment information

<details>

```
# Put output below this line
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx
    Memory: 6.58 GB / 13.92 GB
  Binaries:
    Node: 14.4.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.114
    Edge: Spartan (44.19041.906.0), Chromium (89.0.774.77)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @aws-amplify/ui-react: ^0.2.22 => 0.2.33
    @craco/craco: ^5.8.0 => 5.9.0
    @date-io/date-fns: ^1.3.13 => 1.3.13
    @fullcalendar/core: ^5.4.0 => 5.5.0
    @fullcalendar/daygrid: ^5.4.0 => 5.5.0
    @fullcalendar/interaction: ^5.4.0 => 5.5.0
    @fullcalendar/list: ^5.4.0 => 5.5.0
    @fullcalendar/moment: ^5.4.0 => 5.5.0
    @fullcalendar/react: ^5.4.0 => 5.5.0
    @fullcalendar/timegrid: ^5.4.0 => 5.5.0
    @material-ui/core: ^4.11.0 => 4.11.2
    @material-ui/data-grid: ^4.0.0-alpha.10 => 4.0.0-alpha.13
    @material-ui/icons: ^4.9.1 => 4.11.2
    @material-ui/lab: ^4.0.0-alpha.56 => 4.0.0-alpha.57
    @material-ui/pickers: ^3.2.10 => 3.2.10
    @mui-treasury/components: ^1.9.1 => 1.9.2
    @mui-treasury/styling: ^0.2.8 => 0.2.8

```

</details>

### Describe the bug

I'm trying to execute an amplify serverless post function which performs a stripe operation but I keep getting an error in my logs saying..

SyntaxError: await is only valid in async function

I have ran similar functions with similar post requests with no issue.

### Expected behavior

The function runs and performs the stripe operation

### Reproduction steps

I'm just running a post request from my react app

### Code Snippet

```javascript
// Put your code below this line.

exports.handler = async (event, context) => {
  console.log(`EVENT: ${JSON.stringify(event)}`)
  return awsServerlessExpress.proxy(server, event, context, 'PROMISE').promise
}

app.post('/external', async (req, res) => {
  try {
    const bankAccount = await stripe.accounts.createExternalAccount(
      'acct_12345',
      { external_account: 'btok_12345'}
    )
    res.json({
      success: 'post call to create external account succeed!',
      tos: 'tos accepted successfully',
      bankAccount,
    })
  } catch (err) {
    console.log(err)
    res.status(400)
    res.send({ err })
    return
  }
})

function createExternal() {
    API.post('paymentapi', '/external',)
      .then((response) => console.log(response))
      .catch((error) => console.log(error.response))
  }

```

### Log output

<details>

```
// Put your logs below this line
2021-04-21T13:30:23.105Z	undefined	ERROR	Uncaught Exception 	{
    "errorType": "Runtime.UserCodeSyntaxError",
    "errorMessage": "SyntaxError: await is only valid in async function",
    "stack": [
        "Runtime.UserCodeSyntaxError: SyntaxError: await is only valid in async function",
        "    at _loadUserApp (/var/runtime/UserFunction.js:98:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}


```

</details>

**Comment by chrisbonifacio** [comment]
Hey 👋 Thanks for raising this! After reading over this issue, it seems that might have more to do with the syntax/structure of your code. Taking a look at your dependencies, it seems you only have `@aws-amplify/ui-react` installed. I don't think that API is exported from that package. Although, I think you would be getting a different error if that were the problem.

Are those all the dependencies in your app?

**Comment by myfairshare** [comment]
Hey Chris,

   Thanks for your reply, I didn't copy the full list of dependencies as its quite long!  I'm sure the issue must be in the actual app.js serverless function, I just dont understand why the log is giving me the await error as I have specified 'async' in the post function.

**Comment by chrisbonifacio** [comment]
@myfairshare No worries! Funny how sometimes the smallest things can trip us up the longest, isn't it? haha
Good work finding the root of the problem!
