### ISSUE TITLE
GraphQL returning Undefined

### ISSUE THREAD

**Issue by suhailsaqan** [aws-amplify/amplify-js#8144]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v14.16.0

### Amplify CLI Version

4.46.1

### What operating system are you using?

Mac

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

I am doing the following code, however, it is erroring with an 'undefined' error. I tried to perform a query as well, instead of a mutation, to test it and it gives the same error.
```const res = (await API.graphql(
        graphqlOperation(createUser, {
          input: {
            email: email_,
            phone: phone,
            first_name: first_name,
            last_name: last_name,
          },
        }),
      )) as GraphQLResult<CreateUserMutation>;
```

### Expected behavior

I expect it create the user with no error.

### Reproduction steps

1. amplify add api
2. created the schema
3. perform the above graphql command
4. gives error as undefined

### GraphQL schema(s)

```graphql
# Put schemas below this line
type User @model {
  id: ID!
  email: AWSEmail!
  phone: AWSPhone!
  first_name: String!
  last_name: String!
  profile_picture: AWSURL
}


```

### Log output

<details>

```
# Put your logs below this line
undefined


```

</details>

**Comment by suhailsaqan** [comment]
Any progress on this?

**Comment by chrisbonifacio** [comment]
Hey 👋 would you mind sharing the rest of that code snippet? I see that you're using `graphqlOperation` but I'm curious if you're also passing it as an argument to a `API.graphql()` call. Could you please confirm this?

**Comment by suhailsaqan** [comment]
Just realized that I didn't copy the full code. 

`const res = (await API.graphql(
        graphqlOperation(createUser, {
          input: {
            email: email,
            phone: phone,
            first_name: first_name,
            last_name: last_name,
          },
        }),
      )) as GraphQLResult<CreateUserMutation>;`

How do I reach the Network Tab?

**Comment by suhailsaqan** [comment]
Alright, well I just tried it again without changing any code (at least not aware I did) and it's working perfectly. Thank you!

**Comment by chrisbonifacio** [comment]
Haha well that's strange but glad it's working!

To get to the Network Tab, right click on the page -> Inspect -> Network.

From this tab you should be able to see any network requests being made from your app.
![image](https://user-images.githubusercontent.com/16952986/115778405-a0940d80-a384-11eb-9316-2f3072de621a.png)

Closing the issue for now as it seems you might have been able to fix it in your app. Feel free to reopen if it happens again and is a recurring issue for you.

**Comment by suhailsaqan** [comment]
I'm running into the same issue again. There was nothing in the network either. I ran the code which runs the graphql query.
![Screen Shot 2021-04-27 at 5 10 32 PM](https://user-images.githubusercontent.com/43693074/116327370-7b840e00-a77b-11eb-8cc5-0dac719d7778.png)
