### ISSUE TITLE
Can't verify email of the user autoconfirmed

### ISSUE THREAD

**Issue by harleyguru** [aws-amplify/amplify-js#815]
Here is my use case:
1. I need to allow users with unverified email to sign in
2. I also need to allow users to sign in with preferred_username alias

So I've tried all options for attributes section in user pool, but here are some issues I've found out so far:
- It didn't allow unconfirmed user to login
- so I do auto confirm for new users so that unverified users can't login
- when I try to verify email of autoconfirmed user, it fails

This is very common scenario in a lot of services over the world, but wondering why Cognito blocks this use case.
I can't find any way to accomplish my requirements in User Pool.
Pls help me!

Here is the screenshot of failed verification:
![screen shot 2018-05-10 at 12 37 23 pm](https://user-images.githubusercontent.com/35247645/39863289-e92dc956-544e-11e8-9a6b-2fa7711178b3.png)

**Comment by buggy** [comment]
@harleyguru You can automatically verify email addresses using a Pre Sign-Up trigger on your Cognito User Pool. See https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-lambda-trigger-syntax-pre-signup.html

**Comment by harleyguru** [comment]
hi @buggy I know I can verify email automatically and using it for development.
But in the production, I'd like to let the users to verify their email from verification link as other sites do.
How can I do that?

**Comment by harleyguru** [comment]
btw, I could make it working by using `UpdateUserAttributeVerificationCode` and `VerifyUserAttribute` API calls, but we need to support email verification by link.
More over in order to support login with unverified email, I had to set email as a username.
But we also need to support login with preferred_username, unfortunately preferred_username attributue can't be set as username.

Can you point me to right direction to accomplish these requirements please?
These are very common requirements for most of sites, but Cognito doesn't provide any way to do this.

**Comment by elorzafe** [comment]
@harleyguru we will discuss with Cognito team.

**Comment by harleyguru** [comment]
Thanks @elorzafe , I wish you to update me as soon as possible you get update and solution for this issue because we are closing to the release soon.
Thanks a lot for your investigation and help
