### ISSUE TITLE
Auth.signin throws error after successful signup/user creation.

### ISSUE THREAD

**Issue by zaura-payments** [aws-amplify/amplify-js#8153]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication, GraphQL API

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 5.91 GB / 15.96 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 90.0.4430.85
    Edge: Spartan (44.19041.906.0), Chromium (90.0.818.42)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @babel/core: ^7.13.16 => 7.13.16 (7.9.0)
    @react-native-community/eslint-config:  1.1.0
    @react-native-community/eslint-plugin:  1.0.0
    @react-native-community/masked-view: ^0.1.10 => 0.1.10
    @react-native-community/netinfo: ^6.0.0 => 6.0.0
    @react-navigation/native: ^5.9.4 => 5.9.4
    @react-navigation/stack: ^5.14.4 => 5.14.4
    HelloWorld:  0.0.1
    amazon-cognito-identity-js: ^4.6.0 => 4.6.0
    aws-amplify: ^3.3.27 => 3.3.27
    aws-amplify-react-native: ^4.3.2 => 4.3.2
    babel-plugin-inline-view-configs:  0.0.5
    buffer: ^6.0.3 => 6.0.3 (4.9.2, 5.7.1)
    expo: ~41.0.1 => 41.0.1
    expo-status-bar: ~1.0.4 => 1.0.4
    hermes-inspector-msggen:  1.0.0
    joi: ^17.4.0 => 17.4.0
    react: ^17.0.1 => 17.0.1
    react-animated:  0.1.0
    react-dom: ^17.0.1 => 17.0.1
    react-native: https://github.com/expo/react-native/archive/sdk-39.0.2.tar.gz => 0.63.2
    react-native-codegen:  0.0.2
    react-native-gesture-handler: ~1.10.2 => 1.10.3
    react-native-reanimated: ^2.1.0 => 2.1.0
    react-native-safe-area-context: 3.2.0 => 3.2.0
    react-native-screens: ~3.0.0 => 3.0.0
    react-native-web: ^0.16.0 => 0.16.0
    webpack-cli: ^4.6.0 => 4.6.0
  npmGlobalPackages:
    @aws-amplify/cli: 4.49.0
    argo-trading: 6.2.4
    awsmobile-cli: 1.1.7
    browserify: 16.2.3
    create-react-app: 4.0.3
    electron: 4.0.7
    expo-cli: 4.4.3
    react-native-cli: 2.0.1

```

</details>

### Describe the bug

After a successful user signup using AWS Amplify I try to login using the correct authentication details. The following error is then thrown in the console:

` Error signing in... [TypeError: (0, _getRandomBase.default) is not a function. (In '(0, _getRandomBase.default)(array.byteLength)', '(0, _getRandomBase.default)' is undefined)]`

The user is created properly on the server side, I can view this in the dashboard and see all the test users I have created.

### Expected behavior

As the sign-in details are correct I should be able to sign in and Auth.signIn() should be successful. 

I will mention that I have tried all the suggestions in this previous bug report:  https://github.com/aws-amplify/amplify-js/issues/7191 to no avail. 

### Reproduction steps

This error is outputted after Auth.signIn(username,password) is called. 

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by zaura-payments** [comment]
I found some more information on a previous post about the same error.https://github.com/aws-amplify/amplify-js/issues/8113

https://github.com/aws-amplify/amplify-js/issues/8113

**Comment by mozadeh** [comment]
Why is this closed, I have the same problem i.e. everything works and is fine on server side but a error message is thrown "[TypeError: undefined is not an object (evaluating 'user.signInUserSession.idToken.payload.identities[0]')]"
