### ISSUE TITLE
Cognito jwt token fails verification every time

### ISSUE THREAD

**Issue by jonathan-kosgei** [aws-amplify/amplify-js#816]
Do you want to request a feature or report a bug?

Bug with the token generated by cognito.

What is the current behavior?

This is the access token I get from logging in a user;
```
eyJraWQiOiJ3bXF3Q2ttbVFubll1RXJEVGU2MDVOWUdMR0VTSW5iWUVmd3ZBeXJHc053PSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJiMTMzZWQ0ZC02ZmUwLTQ0YjgtYjZiOS00YWY4NmJkMDYzMmQiLCJldmVudF9pZCI6IjlkMTE0N2I0LTU0NDItMTFlOC04YTIxLWM3Y2U2NjBlOWVlMCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE1MjU5NTA1NzEsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX21yazRSeWpZeiIsImV4cCI6MTUyNTk1NDE3MSwiaWF0IjoxNTI1OTUwNTcxLCJqdGkiOiIxNzkyYzk0Ni00ZWVkLTRjY2MtYTAzZS1mOTcyNDFlMzkxMTUiLCJjbGllbnRfaWQiOiI2dXBlNm5kdW5ka3Y3ZjVpOWpsbzZhOHAydCIsInVzZXJuYW1lIjoiam9uYXRoYW5rb3NnZWkxMDAwQGdtYWlsLmNvbSJ9.svSsUbl0deDKhQfQju-rjmmNVz31ljQLzaTDV_je3LeP-qDS1kYU8RC3k2cyQkq9xjFvHoSwUWQ4zbgLgDfcjnktvpbSNjuCvAvv-8MpQiD83b3OnsiNV0mgddegl-GBInMQplNVJgBIDchOeTsJc2Qkz8XNM7J3yUpS4B1QXgIOZJUjHagXjTbQwi_VAUMi-qs5hFpfeaRDh6zalYAeRBvNLxaQObZytAwrPges2eOEmC31v8sGOrZkWC577yb36qMuVSrtRgKwlKKsiuucPB44b4oB7zXO6jqRjPyY3rEo7GzCzGhwK_73gAwkSekENSrYA6NtnZqMFm3L1sGCIA
```
The public key for this user pool, matching the kid is;
```
umZZl1U3GFFZyVTRmHLgb1II9-fOIqg9CT4gGDyfLglsPMBV3m6G88KhgiStpnY_nmR_yx0PewIBYPJNEC6xxdKxDbKkIA7oZz-P-I1qJwYQsyhIfmVd9IwGIebYu1ZNrlJmseu4axi-Q3NbjRs4svXDt_WF4bkmGIvdlt35xta7-Djo-WiGWfFZBaurnDZqtIZ4xl_CJW0rByX1hBHSUn_sS4JL8YUnPC8vLDUXlG5sLH_7BTI1VMtpWWqROnY9B_J8fR6oDdaSWP_BaYQQr8g6ye3a95zpaTweTNnom2VMgj9g23qPYrKD9zXL4oXTjjTb0MbUHRLP8FcYI7E5Sw
```
I get the token from cognito directly with valid credentials, however all the tokens I've generated dozens of times always fail jwt verification. Every single one.

What is the expected behavior?

A validly generated jwt token from cognito signin should be verifiable with the correct public key.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

I'm using the plain javascript example above which depends on;
```
    <script src="assets/js/aws-cognito-sdk.min.js"></script>
    <script src="assets/js/amazon-cognito-identity.min.js"></script>
    <script src="assets/js/aws-sdk.min.js"></script>
```

I've tried the verification in Python in Node and on jwt.io, none worked.

**Comment by ZhuangER** [comment]
Do you transfer your public key to pem?

**Comment by jordanranz** [comment]
Going to close this issue due to lack of response from the last question. Please reopen if you are still experiencing this issue and we can look into escalating to the Cognito service team.

**Comment by namya-r** [comment]
I think I have an issue similar to @jonathan-kosgei. I am following the steps listed [here](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html) and looking at [this example](https://aws.amazon.com/premiumsupport/knowledge-center/decode-verify-cognito-json-token/).

My issue is that the kid of my JWT (which I get from Cognito after successfully logging in) does not match either of the kids in my JSON Web Key Set. This is even before I try to verify the signature.
