### ISSUE TITLE
Dependences error using ssr with svelte

### ISSUE THREAD

**Issue by RiosQ** [aws-amplify/amplify-js#8163]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication, REST API

### Amplify Categories

auth

### Environment information

trying to deploy a web application using sapper and developed with svelte the library cant find the dependence 'buffer', the rollup configuration of the server can't detect the main npm packages and take it  as a local dependence.

![error returned](https://i.imgur.com/VGurO03.png)

### Describe the bug

using SSR the web application not recognize the aws-amplify dependences as npm packages, read them as local dependence

### Expected behavior

a correction or method to read the dependences correctly

### Reproduction steps

to repply this download the sapper template:

```
npx degit "sveltejs/sapper-template#rollup" my-app
```

install the dependences:

```
npm i 
npm i aws-amplify @rollup/plugin-json
```

go to `rollup.config.js` and add:

```
import json from '@rollup/plugin-json'; // import this

export default {
	client: {
		input: config.client.input(),
		output: config.client.output(),
		plugins: [
                        json(),                         //add this
			replace({
```

later, go to `client.js` and call the amplify configuration:

```
import Amplify from 'aws-amplify';

Amplify.configure({
	Auth: {
		mandatorySignIn: true,
		region: 'REGION',
		userPoolId: 'USER_POOL_ID',
		identityPoolId: 'IDENTITY_POOL_ID',
		userPoolWebClientId: 'APP_CLIENT_ID'
	},);
```
on `npm run dev` the application will present the error...

Thanks for your help...

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hello @RiosQ :wave: what kind of issue are you experiencing with this error shown in the browser's console? To mitigate this error you can add `preberBuiltins` to the `client` piece of your rollup config, as it will ensure the aws-sdk will use its browser-specific buffer API rather than confuse it for the built-in. Also for good measure, install `@rollup/plugin-json` as a devDependency

```diff
resolve({
  browser: true,
  dedupe: ['svelte'],
+ preferBuiltins: false,
}),
```

**Comment by RiosQ** [comment]
thanks
