### ISSUE TITLE
Errors on all requests to cloud API - Cannot read property 'forEach' of undefined at RestClient

### ISSUE THREAD

**Issue by declan4** [aws-amplify/amplify-js#817]
I have tried implementing a basic cloud API through both the cli and the mobile hub interface. After following the instructions (https://docs.aws.amazon.com/aws-mobile/latest/developerguide/web-access-databases.html) I am getting a cannot read property forEach() of undefined error at RestClient. I have tried the solution here with no luck: https://github.com/aws/aws-amplify/issues/145.

The requests work when tested through the cli using 'awsmobile cloud-api invoke', just not in my app.

**Comment by powerful23** [comment]
Closing the issue. Feel free to reopen if you still have this issue.

**Comment by rbcorrea** [comment]
Hi, I'm also facing this problem. 

Printing the configuration with `console.log(API.configure(ENV.awsmobile))` (note that this is the same configuration I'm using in my AppComponent.ts in `Amplify.configure()`), I got:

```
{
    "Storage": {
        "bucket": "petfy-store-prod/petimages",
        "region": "us-east-1"
    },
    "aws_app_analytics": "enable",
    "aws_cloud_logic": "enable",
    "aws_cloud_logic_custom": [
        {
            "id": "---",
            "name": "app",
            "description": "Proxy API to x",
            "endpoint": "https://---.execute-api.us-east-1.amazonaws.com/v1",
            "region": "us-east-1",
            "paths": [...]
        }
    ],
    "aws_cognito_identity_pool_id": "---",
    "aws_cognito_region": "us-east-1",
    "aws_sign_in_enabled": "enable",
    "aws_user_files": "enable",
    "aws_user_files_s3_bucket": "---",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_user_pools": "enable",
    "aws_user_pools_id": "---",
    "aws_user_pools_web_client_id": "-"
}
```
and in the next line, trying to use `API.get(endpointName, path, {headers:{}})`, I'm getting:

`Cannot read property 'forEach' of undefined
    at RestClient.endpoint (RestClient.js:205)`.

I was using and configuring the library the same way and it was working as expected.
