### ISSUE TITLE
[ui-react] withAuthenticator throws if component has custom props

### ISSUE THREAD

**Issue by ctjlewis** [aws-amplify/amplify-js#8173]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
    Memory: 2.28 GB / 31.30 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 90.0.4430.85
    Firefox: 87.0
  npmPackages:
    @babel/cli: ^7.0.0 => 7.13.16 
    @babel/core: ^7.0.0 => 7.13.16 (7.9.0, 7.9.0, 7.12.9, 7.9.0, 7.9.0, 7.9.0, 7.12.9)
    @babel/preset-env: ^7.0.0 => 7.13.15 (7.3.4, 7.9.0)
    @babel/preset-react: ^7.0.0 => 7.13.13 (7.9.1)
    @types/blob-util:  1.3.3 
    @types/bluebird:  3.5.29 
    @types/chai:  4.2.7 
    @types/chai-jquery:  1.1.40 
    @types/jest: ^24.0.18 => 24.9.1 
    @types/jquery:  3.3.31 
    @types/lodash:  4.14.149 
    @types/minimatch:  3.0.3 
    @types/mocha:  5.2.7 
    @types/node: ^8.9.5 => 8.10.66 (14.14.41, 14.14.41, 14.14.41, 14.14.41, 14.14.41, 14.14.41)
    @types/puppeteer: 1.3.0 => 1.3.0 
    @types/sinon:  7.5.1 
    @types/sinon-chai:  3.2.3 
    babel-loader: ^8.0.0 => 8.2.2 (8.1.0)
    bundlewatch: ^0.3.1 => 0.3.2 
    codecov: ^3.6.5 => 3.8.1 
    compression-webpack-plugin: ^1.1.3 => 1.1.12 
    cypress: ^3.2.0 => 3.8.3 
    husky: ^3.0.5 => 3.1.0 
    jest: ^24.x.x => 24.9.0 
    jest-config: 24.8.0 => 24.8.0 (24.9.0, 24.9.0)
    json-loader: ^0.5.7 => 0.5.7 
    lerna: ^3.13.1 => 3.22.1 
    prettier: ^1.19.0 => 1.19.1 
    pretty-quick: ^1.11.1 => 1.11.1 
    rimraf: ^2.6.2 => 2.7.1 (2.6.3, 2.2.8)
    rollup: ^0.67.4 => 0.67.4 
    rollup-plugin-commonjs: ^9.2.0 => 9.3.4 
    rollup-plugin-json: ^3.1.0 => 3.1.0 
    rollup-plugin-node-resolve: ^4.0.0 => 4.2.4 
    rollup-plugin-sourcemaps: ^0.4.2 => 0.4.2 
    rollup-plugin-typescript: ^1.0.0 => 1.0.1 
    source-map-loader: ^0.2.1 => 0.2.4 
    ts-jest: ^24.x.x => 24.3.0 
    tslint: ^5.7.0 => 5.20.1 
    tslint-config-airbnb: ^5.8.0 => 5.11.2 
    typedoc: ^0.16.9 => 0.16.11 
    typescript: ~3.6.4 => 3.6.5 
    uglifyjs-webpack-plugin: ^0.4.6 => 0.4.6 
    uuid-validate: ^0.0.3 => 0.0.3 
    webpack: ^4.32.0 => 4.46.0 
    webpack-bundle-analyzer: ^3.3.2 => 3.9.0 
    webpack-cli: ^3.1.0 => 3.3.12 
    winston: ^3.2.1 => 3.3.3 
  npmGlobalPackages:
    npm: 6.14.11

```

</details>

#### TS
Use the `withAuthenticator` wrapper with a `FunctionComponent` that has custom props, i.e.:

```typescript
const CustomComponent: FC<{ prop1: string }> = ({ prop1 = '' }) => { ... }

export default withAuthenticator(CustomComponent)
```

Fails because this type is not assignable to `ComponentType<{}>`.

#### Runtime
In Next, App components *do* have props, and take the form:

```ts
const App = ({
  Component,
  pageProps,
}: {
  Component: ComponentClass;
  pageProps: { [key: string]: any };
})
```

However, wrapping with `export default withAuthenticator(App)` prevents the entire app from rendering:

> Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> 
> Check the render method of `App`.

#### TS
No error should be generated, and `withAuthenticator` should handle generic typing. 

#### Runtime
`withAuthenticator` should not throw a runtime error when fed a component with custom props.

#### TS
1. Define a component with custom props (`FunctionComponent<T>`)
2. Attempt to wrap a component with `withAuthenticator(functionComponent<FunctionComponent<T>>)`
3. Observe TypeScript failure

#### Runtime
1. Create a NextJS project (or any other project which uses an App component with custom props)
2. Attempt to wrap a component with `export default withAuthenticator(fApp)`
3. Observe react failure

Repro at: https://github.com/ctjlewis/aws-amplify-test/tree/auth

#### TS
```typescript
const CustomComponent: FC<{ prop1: string }> = ({ prop1 = '' }) => (<></>);

// TS error
export default withAuthenticator(CustomComponent);
```

#### Runtime
```typescript
const App = ({
  Component,
  pageProps,
}: {
  Component: ComponentClass;
  pageProps: { [key: string]: any };
}) = // ...;

// Runtime error
export default withAuthenticator(App);
```

### Log output

<details>

#### TS
```
Argument of type 'FC<{ prop1: string; }>' is not assignable to parameter of type 'ComponentType<{}>'.
  Type 'FunctionComponent<{ prop1: string; }>' is not assignable to type 'FunctionComponent<{}>'.
    Types of parameters 'props' and 'props' are incompatible.
      Type '{ children?: ReactNode; }' is not assignable to type 'PropsWithChildren<{ prop1: string; }>'.
        Property 'prop1' is missing in type '{ children?: ReactNode; }' but required in type '{ prop1: string; }'.ts(2345)
```

#### Runtime
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.
```

</details>

### Additional information and screenshots

I tried to add my own typing in [`packages/amplify-ui-react/src/withAuthenticator.tsx`](https://github.com/ctjlewis/amplify-js/blob/main/packages/amplify-ui-react/src/withAuthenticator.tsx), but could not get around the compiler error.

**Comment by chrisbonifacio** [comment]
Hey 👋 Thanks for raising this! After reading over this issue, it appears to be more of a feature request and will be labeled as such.

I was able to reproduce this and you are correct, passing a component with its own props to `withAuthenticator` does cause this error. Usually, it is the root App component that is wrapped and does not accept its own props. However, we realize it should be possible to wrap any component and so we are working to enhance the typing to allow for custom props on the wrapped component.

I hope that helps!

**Comment by ctjlewis** [comment]
Thanks for your response.

I would definitely consider it a bug because it is effectively impossible to use this without workarounds on Next apps given this information. I have only ever wrapped specific pages, `export default withAuthenticator(SignUp)`, and your note that the App component does not except props explains a *separate* error I had where wrapping the root App (which I only did for a test project) actually blew the entire app up, because in Next, the App component *does* accept props and takes the form:

```ts
const App = ({
  Component,
  pageProps,
}: {
  Component: ComponentClass;
  pageProps: { [key: string]: any };
})
```

And so, when you go to root dir `/`, Next normally decides which page to load, and feeds it into the `{ Component }` arg (say, `{ Component: HomePage }`). `withAuthenticator` breaks that and causes an error I will document in a separate ticket.

I think this library should work as expected and as such would not agree that the feature request label is appropriate.

**Comment by ctjlewis** [comment]
Added details - issue is really bipartite, TS failures and runtime failures. We want the TS to compile and we want the code to run. Repro up as well for the runtime + framework compat aspect.
