### ISSUE TITLE
Keep asking to verify even if email_verified is true

### ISSUE THREAD

**Issue by namwkim** [aws-amplify/amplify-js#8189]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>
  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 420.18 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    npm: 6.14.11 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.85
    Firefox: 52.3.0
    Safari: 14.0.3
  npmPackages:
    @aws-amplify/ui-react: ^1.0.6 => 1.0.6 
    @material-ui/core: ^4.11.3 => 4.11.3 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @testing-library/jest-dom: ^5.11.10 => 5.11.10 
    @testing-library/react: ^11.2.6 => 11.2.6 
    @testing-library/user-event: ^12.8.3 => 12.8.3 
    aws-amplify: ^3.3.26 => 3.3.26 
    d3-fetch: ^2.0.0 => 2.0.0 
    ini: ^1.3.5 => 1.3.8 
    inquirer: ^6.5.1 => 6.5.2 
    lodash: ^4.17.21 => 4.17.21 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    react-router-dom: ^5.2.0 => 5.2.0 
    react-scripts: 4.0.3 => 4.0.3 
    vega: ^5.20.2 => 5.20.2 
    vega-embed: ^6.17.0 => 6.17.0 
    vega-lite: ^5.0.0 => 5.0.0 
    web-vitals: ^1.1.1 => 1.1.1 
  npmGlobalPackages:
    expo-cli: 3.13.1
    n: 7.0.2
    npm: 6.14.11
    supervisor: 0.12.0
</details>

### Describe the bug

![image](https://user-images.githubusercontent.com/70299/116305503-df093e00-a771-11eb-9a8f-0248549e00c7.png)

![image](https://user-images.githubusercontent.com/70299/116305450-cbf66e00-a771-11eb-974c-e1306a3fadd5.png)

### Expected behavior

The recovery UI should not appear.

### Reproduction steps

1. Create a User in the Amplify Admin UI with a temporary password
2. Sign the user in and change the password and verify the email
3. Signout
4. Sign in again

I played with Cognito by adding a custom attribute and custom messaging. I wonder if that created some conflict with Amplify authentication. But they should be in sync no matter what, right?

### Code Snippet

```javascript
      <Route path="/">
            <AmplifyAuthenticator usernameAlias="email">
              <Home />
              <AmplifySignIn slot="sign-in" hideSignUp={true}></AmplifySignIn>
            </AmplifyAuthenticator>
          </Route>

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by 24601** [comment]
Seems similar to something we have, there is some check in their state machine that forwards to this page spuriously, luckily, ours seems to "figure it self out" after a few seconds and forwards to normal login state, but not after users freak out and file support tickets. :SMH:

**Comment by chrisbonifacio** [comment]
Hello 👋 thank you for raising this issue. @24601 I did take a look at your related issue and it seems that this is happening regardless of the framework as yours was on Angular and this one is in React. I also see that @namwkim is using the latest version of the `@aws-amplify/ui-react` package.

I followed the reproduction steps on this issue but I am not getting the temporary verify view yet.

I will also try to add a custom attribute and custom messaging to see if that helps to reproduce the issue.

**Comment by chrisbonifacio** [comment]
So, I just tried with a custom attribute and messing in the verification email/sms and that doesn't seem to have any effect. Going to keep looking into it.

@24601 I see in your issue you mention this is occasional but seems to happen in new browsers or having not been authenticated in a while. I will try in other browsers and report back.

**Comment by namwkim** [comment]
@chrisbonifacio Thanks for the response. Yes, this is difficult to reproduce. 

I resolved the issue by resetting the authentication in Admin UI. My hunch is that it is related to some internal sync issue.

**Comment by chrisbonifacio** [comment]
@namwkim Could you verify if when you were experiencing this issue, you were still able to login and this view would only show temporarily or would it change to this VerifyContact component and remain stuck there without logging you in?

**Comment by namwkim** [comment]
> @namwkim Could you verify if when you were experiencing this issue, you were still able to login and this view would only show temporarily or would it change to this VerifyContact component and remain stuck there without logging you in?

I was able to log in or even skip the verification and use the app. The main issue was that it keeps asking to verify whenever I sign out and attempt to log in again, even though the Admin UI (or Cognito) says the email is already verified.

I think when I touch the Cognitio to customize the messages beyond the Amplify admin, things got messed up.

**Comment by chrisbonifacio** [comment]
@namwkim I did try to reproduce with custom messaging and attributes but it didn't cause the verify contact view to show. It's probably something to do with the transitioning between states/views during login as @24601.

I apologize for the delay, we're still trying to reproduce the issue so that we can work on a fix.
