### ISSUE TITLE
Request: Modular UI Component imports for Vue

### ISSUE THREAD

**Issue by atyshka** [aws-amplify/amplify-js#8193]
**Is your feature request related to a problem? Please describe.**
It appears that the React api for UI Components now allows for tree-shakeable imports, but unfortunately the Vue API does not. Is this a hard technical limitation of StencilJS or could the Vue API get the same ability? The s3 storage dependency from UI Components is a real pain when all you want to use is Auth. We may be forced to create a custom sign in UI if this isn't possible.

**Describe the solution you'd like**
Something like this:
`import { AmplifyAuthenticator, AmplifySignOut } from '@aws-amplify/ui-vue';`

**Describe alternatives you've considered**
Creating signin components from scratch

**Additional context**
Related to #7484

**Comment by tannerabread** [comment]
Closing as this should be how the current [Vue Authenticator](https://ui.docs.amplify.aws/vue/connected-components/authenticator) functions. There are also primitives on the roadmap for Vue that can be tracked better in the [UI repo](https://github.com/aws-amplify/amplify-ui)
