### ISSUE TITLE
No notification on selecting Preferred MFA Type

### ISSUE THREAD

**Issue by m-bilal-dev9** [aws-amplify/amplify-js#8199]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
npx: installed 1 in 4.549s

  System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 61.21 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.0/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 83.0
    Safari: 14.0.2
  npmGlobalPackages:
    eslint-plugin-prettier: 3.4.0
    npm: 6.14.11
    yarn: 1.22.10

```

</details>

### Describe the bug

Using AmplifySelectMfaType component for allowing users to set their preferred MFA type.
Once user clicks on verify button, API request is being but users are not getting notified.

### Expected behavior

An hub event should be fired for MfaTypeSet for both cases success & failure.
Or There should be a notification at-least in case of success/failure to notify the user.

### Reproduction steps

1. Add UI component for AmplifySelectMfaType with MFATypes props
2. Select the preferred MFA from UI and click verify

### Code Snippet

```javascript
        <AmplifySelectMfaType
          MFATypes={{ TOTP: true, SMS: true, Optional: true }}
          authData={data}
        />
```

**Comment by sidverma32** [comment]
Hi @chrisbonifacio ,  I would like to pick this up. If you can guide me how to proceed from here?

**Comment by eddiekeller** [comment]
merged in PR. toast should show when selecting an MFA type now
