### ISSUE TITLE
withAuthenticator hanging

### ISSUE THREAD

**Issue by JoeKlimcak** [aws-amplify/amplify-js#8237]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 11.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 5.34 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.14.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 7.7.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 88.0.1
    Safari: 14.1
  npmPackages:
    @babel/core: ^7.8.4 => 7.14.0 
    @babel/plugin-proposal-class-properties: ^7.13.0 => 7.13.0 
    @babel/preset-react: ^7.13.13 => 7.13.13 
    @babel/runtime: ^7.8.4 => 7.14.0 
    @eva-design/eva: ^2.0.0 => 2.1.0 
    @react-native-async-storage/async-storage: ^1.13.2 => 1.15.4 
    @react-native-community/eslint-config: ^1.1.0 => 1.1.0 
    @react-native-community/masked-view: ^0.1.10 => 0.1.11 
    @react-native-community/netinfo: ^5.9.10 => 5.9.10 
    @react-navigation/drawer: ^5.11.4 => 5.12.5 
    @react-navigation/native: ^5.8.10 => 5.9.4 
    @react-navigation/stack: ^5.12.8 => 5.14.4 
    @stripe/react-stripe-js: ^1.2.2 => 1.4.0 
    @stripe/stripe-js: ^1.12.0 => 1.14.0 
    @testing-library/dom: ^7.29.4 => 7.30.4 
    @testing-library/react-native: ^7.1.0 => 7.2.0 
    @ui-kitten/components: ^5.0.0 => 5.1.0 
    @ui-kitten/eva-icons: ^5.0.0 => 5.1.0 
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: ^4.5.7 => 4.6.1 
    aws-amplify: ^3.4.0 => 3.4.0 
    aws-amplify-react-native: ^4.3.3 => 4.3.3 
    babel-jest: ^25.1.0 => 25.5.1 
    eslint: ^6.5.1 => 6.8.0 
    example:  0.0.1 
    hermes-inspector-msggen:  1.0.0 
    identity-obj-proxy: ^3.0.0 => 3.0.0 
    jest: ^25.1.0 => 25.5.4 
    metro-react-native-babel-preset: ^0.59.0 => 0.59.0 (0.64.0)
    react: 16.13.1 => 16.13.1 
    react-native: 0.64.1 => 0.64.1 
    react-native-dotenv: ^2.5.1 => 2.5.5 
    react-native-elements: ^3.2.0 => 3.4.1 
    react-native-gesture-handler: ^1.9.0 => 1.10.3 
    react-native-reanimated: ^1.13.2 => 1.13.3 
    react-native-safe-area-context: ^3.1.9 => 3.2.0 
    react-native-screens: ^2.16.1 => 2.18.1 
    react-native-svg: ^12.1.0 => 12.1.1 
    react-native-toast-message: ^1.4.9 => 1.4.9 
    react-native-vector-icons: ^8.0.0 => 8.1.0 
    react-native-week-view: ^0.3.0 => 0.3.0 
    react-redux: ^7.2.2 => 7.2.4 
    react-test-renderer: 16.13.1 => 16.13.1 
    redux: ^4.0.5 => 4.1.0 
    tipsi-stripe: ^9.0.0 => 9.0.0 
  npmGlobalPackages:
    @aws-amplify/cli: 4.22.0
    create-react-native-app: 3.5.1
    expo-cli: 3.27.4
    express: 4.17.1
    nodemon: 2.0.2
    npm: 7.7.6
    react-native-git-upgrade: 0.2.7
    react-native-scripts: 2.0.1
    yarn: 1.22.4

```

</details>

### Describe the bug

This is a repeat of [#3471](https://github.com/aws-amplify/amplify-js/issues/3471), [#3242](https://github.com/aws-amplify/amplify-js/issues/3242) and [#3206](https://github.com/aws-amplify/amplify-js/issues/3206). Except this time, it always hangs, not just occassionally. 

On some (older) iOS target versions, we get the white "Loading..." page. 

On iOS 14.5, we get to the login page, input credentials, click the 'SIGN IN' button but nothing happens (with no logs). If we try to click on 'SIGN IN' again, we get:

```
Uncaught Error
Pending sign-in attempt already in progress
```

We're using basic Cognito Pool User sign-ins with emails/passwords, so no Federated sign-ins through third parties.

We were previously on
```
"aws-amplify": "^3.3.14",
"aws-amplify-react-native": "^4.3.0",
```
when the problem suddenly arose. We updated to latest:
```
"aws-amplify": "^3.4.0",
"aws-amplify-react-native": "^4.3.3",
```
but the problem still persists. 

This problem has only recently started occurring, but it's been really plaguing us for days now, any help would be greatly appreciated.

### Expected behavior

We expect withAuthenticator to not hang with a loading/unresponsive page.

### Reproduction steps

Our withAuthenticator usage should be basic. 
In index.js:

```
import config from './aws-exports';
Amplify.configure({
  ...config,
  Analytics: {
    disabled: true,
  },
});
```

Note: config file above is auto-generated by AWS Amplify.

Then in App.js:

```
import {withAuthenticator} from 'aws-amplify-react-native';
import withAuthenticatorConfig from './authConfig';

function App() {
    ...
}

export default withAuthenticator(App, withAuthenticatorConfig);
```

where _withAuthenticatorConfig_ looks like:

```
export default {
  usernameAttributes: 'email',
  signUpConfig: {
    signUpFields: [
      {
        label: 'First Name',
        key: 'given_name',
        required: true,
        displayOrder: 1,
        type: 'string',
      },
      {
        label: 'Last Name',
        key: 'family_name',
        required: true,
        displayOrder: 2,
        type: 'string',
      },
      {
        label: 'Phone Number (Scroll on prefix)',
        key: 'phone_number',
        dialCode: '+44',
        required: true,
        displayOrder: 3,
        type: 'phone_number',
      },
      {
        label: 'Email',
        key: 'email',
        required: true,
        displayOrder: 4,
        type: 'string',
      },
      {
        label: 'Password',
        key: 'password',
        required: true,
        displayOrder: 5,
        type: 'password',
      },
    ],
  },
};
```

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

There are no logs. It simply hangs with nothing going to the console where _npm start_ is running, nor is there anything in _system.log_

### aws-exports.js

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "<OUR_COGNITO_IDENTITY_POOL_ID>",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "<OUR_USER_POOLS_ID>",
    "aws_user_pools_web_client_id": "<OUR_USER_POOLS_WEB_CLIENT_ID>",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "<OUR_GRAPHQL_ENDPOINT>",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};

export default awsmobile;

**Comment by chrisbonifacio** [comment]
Good morning 👋 I see that you're using `amazon-cognito-identity-js` along with `aws-amplify`. If you don't mind, please try only using `aws-amplify` and the exported Auth object from it. Amplify already uses that cognito package to handle auth so just curious if they might be conflicting. Let me know if that makes any difference for you.

**Comment by JoeKlimcak** [comment]
Hi Chris, thanks for taking a look at this.

I don't think that's the solution I'm afraid, as that seems to cause more errors. Namely, when I get to the login page and click 'SIGN IN', the screen shows 'Validate that amazon-cognito-identity-js has been linked', and according to [#7533](https://github.com/aws-amplify/amplify-js/discussions/7533), it's exactly because it wasn't included.

 
![Screenshot 2021-05-08 at 06 07 18](https://user-images.githubusercontent.com/19940004/117527427-f04d1880-afc3-11eb-9872-48064604eb6d.png)

**Comment by chrisbonifacio** [comment]
Sorry, I should've asked if you were using Expo or the React Native CLI to set up the project. I saw it in the global dependencies and misread. The docs instruct to install the cognito package separately for the cli and not expo so you're right, it is needed in this case.

I will take this into consideration in my reproduction efforts. I apologize for the delay!

**Comment by JoeKlimcak** [comment]
Hi @chrisbonifacio, may I ask if there are any updates please? Unfortunately this issue is delaying the release of our app.

**Comment by chrisbonifacio** [comment]
@JoeKlimcak Sorry for the delay. So, I've made a React Native project with the same package versions in your environment and I have not been able to get the sign in to hang. I ran into other issues while setting up the project that only had to do with making sure I had Amplify properly configured, amazon-cognito-identity-js being linked, etc. Other than that it seems to be working.

https://www.loom.com/share/bd42a7a4502442f6adf7666eeceb3730

Here's my package.json

```json
{
  "name": "ui8237",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.15.4",
    "@react-native-community/netinfo": "5.9.10",
    "amazon-cognito-identity-js": "4.5.7",
    "aws-amplify": "3.4.0",
    "aws-amplify-react-native": "4.3.3",
    "react": "17.0.1",
    "react-native": "0.64.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "17.0.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

index.js
```js
/**
 * @format
 */

import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import Amplify from 'aws-amplify';
import awsconfig from './src/aws-exports';

Amplify.configure({
  ...awsconfig,
  Analytics: {
    disabled: true,
  },
});

AppRegistry.registerComponent(appName, () => App);

```

App.js
```js
import React from 'react';
import {Button, Text, View} from 'react-native';
import {withAuthenticator} from 'aws-amplify-react-native';
import {Auth} from 'aws-amplify';
import withAuthenticatorConfig from './authConfig';

function App() {
  const signOut = async () => {
    await Auth.signOut();
  };
  return (
    <View style={customStyles}>
      <Text>Homepage</Text>
      <Button onPress={signOut} title="Sign Out" />
    </View>
  );
}

export default withAuthenticator(App, withAuthenticatorConfig);

const customStyles = {
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  height: '100%',
};
```

**Comment by JoeKlimcak** [comment]
Thanks @chrisbonifacio, tried the above, still experiencing the same issue. 

Is there any way we can get some logs out of withAuthenticator? It doesn't seem to log anything into system.log. We're basically trying to avoid having to recreate and reconfigure the entire app from scratch, as that wouldn't really tell us why this is happening in the first place so we can avoid it in the future.

**Comment by chrisbonifacio** [comment]
@JoeKlimcak This might be a silly question, but when you installed `amazon-cognito-identity-js`, did you also run `pod install` inside of your ios folder?

If so, maybe upgrade it to the latest version and run `pod update`?

**Comment by chrisbonifacio** [comment]
Closing this for now since we haven't heard back in over a week. Please re-open if you are still experiencing issues.

**Comment by jroeland1993** [comment]
@JoeKlimcak - we intermittently notice something very similar in production on essentially the same versions. I'm curious how/if you resolved this. Looking at this thread we're planning to upgrade. Hoping that resolves...

**Comment by JoeKlimcak** [comment]
Unfortunately not, @jroeland1993. Upgrading didn't help us either. We've basically had to recreate everything from scratch - new repo, new amplify profile, new user pools etc. The code is exactly the same, but now it works.

My suspicion is that withAuthenticator somehow entered into a corrupt state, maybe in conjunction with other libraries being used. Please do keep me updated on your progress, however. Would be good to know for future reference if it were to come back.
