### ISSUE TITLE
Social sign-in redirect to dynamic URIs

### ISSUE THREAD

**Issue by clickchainz** [aws-amplify/amplify-js#8239]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, an idea of the implementation or screenshots about the feature request here.

**Comment by siegerts** [comment]
Hi @clickchainz :wave: !  - Can you please reopen with the [feature request form](https://github.com/aws-amplify/amplify-js/issues/new?assignees=&labels=feature-request&template=2.feature_request.yaml), leaving the required fields.  

Answering these questions helps other community members and users who may come across this add additional use cases, upvote (with [GitHub reactions feature](https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)), or provide additional context that can help guide prioritization and development.
