### ISSUE TITLE
I am frustrated that redirect the user to the path which their originally landed on after social signIn

### ISSUE THREAD

**Issue by clickchainz** [aws-amplify/amplify-js#8242]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, an idea of the implementation or screenshots about the feature request here.

**Comment by sammartinez** [comment]
@clickchainz Can you provide more information regarding this? Are you stating that following this [guide](https://docs.amplify.aws/lib/auth/social/q/platform/js#setup-your-auth-provider) you are being redirected to the `redirectSignIn` even with configuring a `redirectSignOut`? Please let us know

**Comment by sammartinez** [comment]
Resolving as we have not heard from you in over a week. Please let us know if you are still looking for support for this issue and we can reopen. Thanks!
