### ISSUE TITLE
How to implement redirection to a dynamic route after federatedSignIn

### ISSUE THREAD

**Issue by clickchainz** [aws-amplify/amplify-js#8251]
### Is this related to a new or existing framework?

React

### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

I am trying to access a link of our application but they are directed to home screen(default route) not the desired link after federatedSignIn. I found this document 
https://aws-amplify.github.io/amplify-js/api/globals.html#federatedsigninoptions

And I need more Information about customState.

### Describe the solution you'd like

When we use https://example.com  as the redirect URL, after a user signs in, they are being redirected to https://example.com . If they sign in with a specific ID, we want the users to be redirected to that particular landing page for the ID(like query string parameters) and make this redirect URL dynamic. 

### Describe alternatives you've considered

I would like to redirect the user to the path which they originally landed on. 

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by sammartinez** [comment]
Hello @clickchainz, there is a [guide](https://docs.amplify.aws/lib/auth/social/q/platform/js) to our Social Sign In workflow. Please look at our documentation site, specifically around using [Custom State](https://docs.amplify.aws/lib/auth/social/q/platform/js#setup-frontend). Hope this helps!

**Comment by clickchainz** [comment]
Hi I tried the code as in the document,  

 Hub.listen("auth", ({ payload: { event, data } }) => {
      switch (event) {
        case "signIn":
          this.setState({ user: data });
          break;
        case "signOut":
          this.setState({ user: null });
          break;
        case "customOAuthState":
          this.setState({ customState: 'xyz' });
      }
    });
Auth.federatedSignIn({ customState: 'xyz' })

 For example, I have signin page with url  "https://example.com/?id=xyz". The id is dynamic .  But I am not able to access query param (?id=xyz).

I have two questions :
1. How can I get  variable "xyz"  from original URL?
2. could  you send me example code?

Looking forward to hear from you!

**Comment by manueliglesias** [comment]
Hi @clickchainz 

I think you need to pass an object to `customState`, not just a string. Then you should be able to read it inside the `Hub` listener for the `customOAuthState` event.

```diff
- Auth.federatedSignIn({ customState: 'xyz' })
+ Auth.federatedSignIn({ customState: { id: 'xyz'} })
```

**Comment by clickchainz** [comment]
Hey  @manueliglesias 

Thank you!  I tried it, and  I got error and it makes the signIn button is not clickable.
![Screen Shot 2021-05-14 at 1 47 29 PM](https://user-images.githubusercontent.com/35280936/118309343-20605400-b4bb-11eb-92f1-1ee47a8f2b22.png)
