### ISSUE TITLE
Customizing `formFields` in amplify-confirm-sign-in is not working

### ISSUE THREAD

**Issue by dennybiasiolli** [aws-amplify/amplify-js#8254]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
npx envinfo --system --binaries --browsers --npmPackages --duplicates --npmGlobalPackages

  System:
    OS: macOS 11.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 3.30 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 88.0.1
    Safari: 14.1
  npmPackages:
    @babel/cli: ^7.0.0 => 7.13.16 
    @babel/core: ^7.0.0 => 7.14.0 (7.9.0, 7.12.9)
    @babel/preset-env: ^7.0.0 => 7.14.1 (7.3.4, 7.9.0)
    @babel/preset-react: ^7.0.0 => 7.13.13 (7.9.1)
    @types/blob-util:  1.3.3 
    @types/bluebird:  3.5.29 
    @types/chai:  4.2.7 
    @types/chai-jquery:  1.1.40 
    @types/jest: ^24.0.18 => 24.9.1 
    @types/jquery:  3.3.31 
    @types/lodash:  4.14.149 
    @types/minimatch:  3.0.3 
    @types/mocha:  5.2.7 
    @types/node: ^8.9.5 => 8.10.66 (15.0.2)
    @types/puppeteer: 1.3.0 => 1.3.0 
    @types/sinon:  7.5.1 
    @types/sinon-chai:  3.2.3 
    babel-loader: ^8.0.0 => 8.2.2 (8.1.0)
    bundlewatch: ^0.3.1 => 0.3.2 
    codecov: ^3.6.5 => 3.8.2 
    compression-webpack-plugin: ^1.1.3 => 1.1.12 
    cypress: ^3.2.0 => 3.8.3 
    husky: ^3.0.5 => 3.1.0 
    jest: ^24.x.x => 24.9.0 (23.6.0)
    jest-config: 24.8.0 => 24.8.0 (24.9.0, 23.6.0)
    json-loader: ^0.5.7 => 0.5.7 
    lerna: ^3.13.1 => 3.22.1 
    prettier: ^1.19.0 => 1.19.1 
    pretty-quick: ^1.11.1 => 1.11.1 
    rimraf: ^2.6.2 => 2.7.1 (3.0.2, 2.6.3, 2.2.8)
    rollup: ^0.67.4 => 0.67.4 
    rollup-plugin-commonjs: ^9.2.0 => 9.3.4 
    rollup-plugin-json: ^3.1.0 => 3.1.0 
    rollup-plugin-node-resolve: ^4.0.0 => 4.2.4 
    rollup-plugin-sourcemaps: ^0.4.2 => 0.4.2 
    rollup-plugin-typescript: ^1.0.0 => 1.0.1 
    source-map-loader: ^0.2.1 => 0.2.4 
    ts-jest: ^24.x.x => 24.3.0 
    tslint: ^5.7.0 => 5.20.1 
    tslint-config-airbnb: ^5.8.0 => 5.11.2 
    typedoc: ^0.16.9 => 0.16.11 
    typescript: ~3.6.4 => 3.6.5 (3.9.5, 3.7.7)
    uglifyjs-webpack-plugin: ^0.4.6 => 0.4.6 
    uuid-validate: ^0.0.3 => 0.0.3 
    webpack: ^4.32.0 => 4.46.0 (4.42.0)
    webpack-bundle-analyzer: ^3.3.2 => 3.9.0 
    webpack-cli: ^3.1.0 => 3.3.12 
    winston: ^3.2.1 => 3.3.3 
  npmGlobalPackages:
    npm: 6.14.12
```

</details>

### Describe the bug

Trying to customize the input type the `amplify-confirm-sign-in` results in an un-usable component, caused by the inner override of the `handleInputChange` function.

### Expected behavior

I was expecting that passing only the other fields should be enough, but now the component is not working anymore.
I'm providing a PR trying to solve the problem.

### Reproduction steps

Trying to customize the input type the `amplify-confirm-sign-in` results in an un-usable component, caused by the inner override of the `handleInputChange` function.

Here's the example code
1. Configure the amplify-authenticator component in your vue application (it's working)
2. Customize the amplify-confirm-sign-in component in this way
    ```js
    <amplify-confirm-sign-in
      slot="confirm-sign-in"
      header-text="Enter code from your Authenticator App"
      :form-fields.prop="formFields"
    />
    
    // ...
      data() {
        return {
          formFields: [
            {
              type: 'text',
              label: 'Verification codex',
              placeholder: 'Enter codex',
              required: true,
              // handleInputChange: I don't want to handle the input change here, it's already inside the amplify-confirm-sign-in component
            },
          ],
        };
      },
    ```

3. Try to enter the confirmation code after logging-in
4. Click on the "CONFIRM" button, it doesn't work anymore

### Code Snippet

```js
<amplify-confirm-sign-in
  slot="confirm-sign-in"
  header-text="Enter code from your Authenticator App"
  :form-fields.prop="formFields"
/>

// ...
  data() {
    return {
      formFields: [
        {
          type: 'text',
          label: 'Verification codex',
          placeholder: 'Enter codex',
          required: true,
          // handleInputChange: I don't want to handle the input change here, it's already inside the amplify-confirm-sign-in component
        },
      ],
    };
  },
```

### Log output

Not sure if it can be useful, but here's the log from my console

<details>

```
// Put your logs below this line

amplify-confirm-sign-in_7.entry.js?e862:120 Uncaught (in promise) TypeError: Cannot read property 'challengeName' of undefined
    at class_1.eval (amplify-confirm-sign-in_7.entry.js?e862:120)
    at step (amplify-confirm-sign-in_7.entry.js?e862:32)
    at Object.eval [as next] (amplify-confirm-sign-in_7.entry.js?e862:13)
    at eval (amplify-confirm-sign-in_7.entry.js?e862:7)
    at new Promise (<anonymous>)
    at __awaiter (amplify-confirm-sign-in_7.entry.js?e862:3)
    at class_1.confirm (amplify-confirm-sign-in_7.entry.js?e862:112)
    at HTMLFormElement.handleSubmit (amplify-confirm-sign-in_7.entry.js?e862:57)
eval @ amplify-confirm-sign-in_7.entry.js?e862:120
step @ amplify-confirm-sign-in_7.entry.js?e862:32
eval @ amplify-confirm-sign-in_7.entry.js?e862:13
eval @ amplify-confirm-sign-in_7.entry.js?e862:7
__awaiter @ amplify-confirm-sign-in_7.entry.js?e862:3
class_1.confirm @ amplify-confirm-sign-in_7.entry.js?e862:112
handleSubmit @ amplify-confirm-sign-in_7.entry.js?e862:57
```

</details>

**Comment by ericclemmons** [comment]
Ahh, so I just remembered why this probably isn't working – `type` isn't so much for `<input type={type}>`, but to indicate what type (e.g. `username`, `email`, `code`) field it is:

https://github.com/aws-amplify/amplify-js/blob/8d62d9d9dd1d5934f40c0b800ab2440d805d4239/packages/amplify-ui-components/src/components/amplify-confirm-sign-up/amplify-confirm-sign-up.tsx#L169-L177

It looks like, from your snippet, you're trying to override the label & placeholder?  If so, have you tried using `I18n` to customize it?

https://github.com/aws-amplify/amplify-js/blob/8d62d9d9dd1d5934f40c0b800ab2440d805d4239/packages/amplify-ui-components/src/components/amplify-confirm-sign-up/amplify-confirm-sign-up.tsx#L119-L134

https://docs.amplify.aws/ui/customization/translations/q/framework/vue

(I'm curious if there's a solution that exists today, because we're redoing this component because of these issues 😅 )

**Comment by wlee221** [comment]
Looking at this too! I agree with @ericclemmons that this can be better handled with [Translations](https://docs.amplify.aws/ui/customization/translations/q/framework/react). Though I'm in still happy to review your PR if you're still interested in merging it, as this is still technically a bug in `confirm-sign-in` if you're trying to use `formFields.props`. I'll leave that up to you!

**Comment by wlee221** [comment]
Having read into our code a bit more, I'm in favor of leaving the code as is. `confirm-sign-in` is less flexible than other components and only expects a `code` input field, so I don't see much value in exposing `formFields` prop to be overridden. 

Can you let us know if @ericclemmons's workaround works? The translations you would use in your use case would be `Translations.CODE_LABEL` and `Translations.CODE_PLACEHOLDER`.

**Comment by dennybiasiolli** [comment]
Thank you all, my primary goal for my changes (as requested by our customers) was to change the input type from "code" to "text", in order to remove the "up and down" buttons on the input. I tried with CSS without luck, so I decided to inspect the code inside AWS because [in the documentation](https://docs.amplify.aws/ui/auth/authenticator/q/framework/vue#confirm-sign-in) it seems possible.

Other than this, the reason I'm using the `header-text` props is that I tried with translations, but it's limited to a single language only.
I'm trying with
```js
I18n.putVocabulariesForLanguage('en-US', {
  [Translations.CONFIRM_TOTP_CODE]: 'Enter code from your Authenticator App',
  [Translations.CODE_LABEL]: 'CODE_LABEL 2',
  [Translations.CODE_PLACEHOLDER]: 'CODE_PLACEHOLDER 2',
});
```

But in this case I'm able to change translations only for those who have the browser with language set to 'en-US'. How can I change the default translation for everyone? For example a user with the browser set to 'it-IT' sees the default text.
I also tried to override the default translations with
```js
import { Translations } from '@aws-amplify/ui-components';
Translations.CONFIRM_TOTP_CODE = 'Enter code from your Authenticator App';
Translations.CODE_LABEL = 'CODE_LABEL';
Translations.CODE_PLACEHOLDER = 'CODE_PLACEHOLDER';
```
But with no luck

Any other suggestions?

**Comment by ericclemmons** [comment]
Ah, so these are all really good points:

First, `number` is the wrong `<input type>` IMO for the `code`:

https://github.com/aws-amplify/amplify-js/blob/8448b4fe1f995f0d6056bcb46dd0fb2023fb197d/packages/amplify-ui-components/src/components/amplify-code-field/amplify-code-field.tsx#L35

This has been documented at length (https://www.twilio.com/blog/html-attributes-two-factor-authentication-autocomplete), but our `code` input should look more like:

```html
<input
  type="text"
  name="code"
  id="code"
  inputmode="numeric"
  pattern="[0-9]*"
  autocomplete="one-time-code"
/>
```

Second, you're right – this is a limitation of `I18n`. It'll attempt to use your provided translation, but ultimately falls back to the default.

On one hand, you could iterate through suppported languages (e.g. `it`, `en`, not all `en-*` variations) and set the same values. Overriding defaults (like you showed above) is definitely a useful feature.

But the reality is there isn't a great workaround for both situations today without merging in #8255. But even then, that really only solves the `number` issue, since translations elsewhere won't get your updated label.

**Comment by wlee221** [comment]
Thanks for the insight, @dennybiasiolli! I think the problem really points to our ambiguous use of `type` as @ericclemmons brought up:

> Ahh, so I just remembered why this probably isn't working – type isn't so much for `<input type={type}>`, but to indicate what type (e.g. username, email, code) field it is [...]

I think this could have been better named as `fieldType` to clarify this 😅

To actually set the `<input type="text">`, we can use the `inputProps` to do so which will take precedence and pass the attributes to the inner `input` element. The code will look like this for your use case: 

```
      formFields: [
        {
          type: 'code', // indicates this is an input for accepting code
          label: 'Verification codex',
          placeholder: 'Enter codex',
          inputProps: { 
            type: 'text', // specify the actual html input type here
            inputmode: 'numeric', 
            required: true 
           }
        },
      ],
```

This and #8255 will be enough to enable your use case. I'll follow up on your PR!

**Comment by dennybiasiolli** [comment]
@ericclemmons thanks!
I discovered I can update the "default" translation in another way:
```
I18n.putVocabulariesForLanguage(navigator.language, {
  [Translations.CONFIRM_TOTP_CODE]: 'Enter code from your Authenticator App',
  [Translations.CODE_LABEL]: 'CODE_LABEL 2',
  [Translations.CODE_PLACEHOLDER]: 'CODE_PLACEHOLDER 2',
});
```

This way we are updating the translations for the user's browser language (`navigator.language`) without overriding the default translations 😉

**Comment by dennybiasiolli** [comment]
@wlee221 thanks for your response, this will be perfect.
I'm using #8255 and
```js
      formFields: [
        {
          inputProps: {
            type: 'text', // specify the actual html input type here
            inputmode: 'numeric',
            pattern: '[0-9]*',
            autocomplete: 'one-time-code',
            required: true,
          },
        },
      ],
```

and everything is working fine, also with the improvements that @ericclemmons suggested

**Comment by wlee221** [comment]
Closing as #8255 is merged. This will be published in the next release cycle. Thanks again for your thorough PR @dennybiasiolli 👍
