### ISSUE TITLE
Security vulnerability. Insecure Randomness affecting crypto-js package, versions >=3.3.0 <4.0.0 || <3.2.1

### ISSUE THREAD

**Issue by emma3333** [aws-amplify/amplify-js#8256]
### Describe the bug

Insecure randomness vulnerability brought in through `crypto-js`.

Affected versions of this package are vulnerable to Insecure Randomness. The secureRandom() method is supposed to return a cryptographically strong pseudo-random data string, but it is biased to certain digits. An attacker could be able to guess the created digits.

More information here: https://app.snyk.io/vuln/SNYK-JS-CRYPTOJS-548472

Remidiation: 
Affecting crypto-js package, versions >=3.3.0 <4.0.0 || <3.2.1
Upgrade crypto-js to version 4.0.0, 3.2.1 or higher.

The current version of crypto-js being used in aws-amplify^3.4.0 is 3.3.0 

### Expected behavior

Update version of crypto-js to remove security vulnerability

### JavaScript Framework

Vue

### Amplify APIs

Authentication

### Amplify Categories

auth

**Comment by sammartinez** [comment]
thanks for reporting this @emma3333, we will look to resolve this as soon as we can

**Comment by iartemiev** [comment]
We've upgraded to CryptoJS@4.0.0 as part of [aws-amplify@4.0.1](https://www.npmjs.com/package/aws-amplify/v/4.0.1)
The previous major version will be patched as well tomorrow (3.4.2 -> 3.4.3)

**Comment by iartemiev** [comment]
CryptoJS has now been updated in the previous version of aws-amplify as well ([aws-amplify@3.4.3](https://www.npmjs.com/package/aws-amplify/v/3.4.3))

Thanks again, @emma3333!
