### ISSUE TITLE
DataStore syncExpression with boolean value cause local IndexedDB version back

### ISSUE THREAD

**Issue by mm-git** [aws-amplify/amplify-js#8264]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

DataStore

### Amplify Categories

api

### Environment information

<details>

```
  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 2.50 GB / 15.62 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 7.12.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 90.0.4430.212
    Edge: Spartan (44.19041.964.0), Chromium (90.0.818.56)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @testing-library/jest-dom: ^5.12.0 => 5.12.0
    @testing-library/react: ^11.2.6 => 11.2.6
    @testing-library/user-event: ^12.8.3 => 12.8.3
    @types/jest: ^26.0.23 => 26.0.23
    @types/node: ^15.0.2 => 15.0.2
    @types/react: ^17.0.5 => 17.0.5
    @types/react-dom: ^17.0.4 => 17.0.4
    @types/uuid: ^8.3.0 => 8.3.0
    aws-amplify: ^4.0.0 => 4.0.0
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    react-scripts: 4.0.3 => 4.0.3
    typescript: ^4.2.4 => 4.2.4
    uuid: ^3.4.0 => 3.4.0 (3.3.2, 8.3.2)
    web-vitals: ^1.1.2 => 1.1.2
  npmGlobalPackages:
    @aws-amplify/cli: 4.50.2
    @ionic/cli: 6.14.1
    @vue/cli-init: 4.5.13
    @vue/cli: 4.5.13
    coffeescript: 2.5.1
    cordova: 10.0.0
    eslint: 7.26.0
    eslit: 6.0.0
    exp: 57.2.1
    expo-cli: 4.4.4
    graphql-schema-utilities: 1.1.3
    gulp: 4.0.2
    ionic: 5.4.16
    live-server: 1.2.1
    mocha: 8.4.0
    node-gyp: 8.0.0
    node-ts: 5.1.1
    npm: 7.12.0
    production: 0.0.2
    react-native-cli: 2.0.1
    serverless-create-global-dynamodb-table: 3.1.1
    serverless-dynamodb-autoscaling: 0.6.2
    serverless: 2.40.0
    to-ico-cli: 1.0.0
    ts-node: 9.1.1
    typescript: 4.2.3
    vue-next: 0.0.1
    webpack-cli: 4.7.0
    webpack: 5.36.2
    windows-build-tools: 5.2.2
    wscat: 4.0.1
```

</details>

### Describe the bug

I made a simple model as follows.

```
type SampleModel @model {
  id: ID!
  available: Boolean!
}
```

I configured DataStore with syncExpression and subscribe data like this.

```javascript
DataStore.configure({
  syncExpressions: [
    syncExpression(SampleModel, () => {
      return s => s.available('eq', false)
    }),
  ]
})

DataStore.observe(SampleModel).subscribe(async () => {
  const data = await DataStore.query(SampleModel)
  console.log(data)
})
```

After application starts, I created some new SampleModel data with available value false. So subscriber received  new data.
I changed an available value to true in the application following code.

```javascript
const data = await DataStore.query(SampleModel)
const target = data.filter(s => !s.available)[0]  // please don't mind if data.length === 0

await DataStore.save(SampleModel.copyOf(target, update => {
  update.available = true
}))
```

After that..
- DynamoDB table's available value is true.
- Subscriber received updated data with true value.
- Local IndexedDB table. it have a SampleModel data with true value. More specifically, new data's _version is changed 2 as well.

It seems no problems so far.
However, when I reload application, available value reverted to false in local IndexedDB and also _version became 1.

If I don't use syncExpression, it's no problem. 

I guess after reloading application, IndexedDB is reconstructed by some historical data. But syncExpression removes data having a true available value from history. So restrcted IndexedDB is missing latest data.

For sake of simplicity, I explained a reloading case. But I think version back is caused by any other reason.

### Expected behavior

Even if I use syncExpression, keep latest data in IndexedDB after reloading

### Reproduction steps

1. Configure Datastore syncExpression with filtering boolean true value
2. DataStore subscriber receives new data with boolean false value
3. Save updated data with boolean true value.
4. Reload application. Then true value versioned back to false.

**Comment by nickarocho** [comment]
Hi @mm-git thank you for taking the time to explain the issue to us. I'm going to work on reproducing this issue in one of my own sample apps and trying to understand the root cause of the problem. I will keep you posted with my findings!

**Comment by nickarocho** [comment]
Hi @mm-git thank you for your patience on this while we attempted to reproduce the issue.

I have created a similar sample app and have a model with a boolean attribute, but I'm having trouble reproducing the problem on my end but want to make sure I fully understand the steps you are taking.

You mentioned:
> when I reload application, available value reverted to false in local IndexedDB and also _version became 1.

Can you please clarify what you are doing when you say "reload the application"? Are you hard-refreshing your browser window and clearing the cache? Are you refreshing the IndexedDB? Or you are reloading the application programmatically from a Datastore perspective via `DataStore.clear()`?

Refreshing the browser doesn't affect the IndexedDB data at all for me until either explicitly clearing the IndexedDB via the method above in the application code or by hard-refreshing the IndexedDB (via Chrome's IndexedDB view within the Application tab) so I wanted to clarify this with you.

Thanks!
