### ISSUE TITLE
Support using IdentityPool with UserPool from different AWS regions

### ISSUE THREAD

**Issue by thiagohirata** [aws-amplify/amplify-js#8265]
### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

`core/Credentials._setCredentialsFromSession` only work when both UserPool and IdentityPool are located in the same AWS region. I have a use case where both are located in different regions.

### Describe the solution you'd like

`Credentials._setCredentialsFromSession` should use the prefix from userPoolId to determine the key for the `Logins` parameter when calling IdentityPool APIs.

There may be other instances in the code where the region for the UserPool may be different from the region defined in `Auth.configuration.region`

### Describe alternatives you've considered

I rewrote `Credentials._setCredentialsFromSession` with an implementation that extracts the userpool region from the userPoolId:

``` ts
		const userPoolRegion = userPoolId?.split('_')[0] || region
		const key = 'cognito-idp.' + userPoolRegion + '.amazonaws.com/' + userPoolId;
		const logins = {};
		logins[key] = idToken;
```

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by nadetastic** [comment]
Hi @thiagohirata,

This is currently supported as a result of https://github.com/aws-amplify/amplify-js/pull/10709

I'll mark this issue as solved, thank you!
