### ISSUE TITLE
User can never login if MFA is enabled and wrong phone number is entered in sign-up

### ISSUE THREAD

**Issue by raghavgoel1994** [aws-amplify/amplify-js#8268]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
NA

```

</details>

### Describe the bug

# Put output below this line

But the user will never get the OTP in his phone number because the user entered the wrong number on the signup page.
So I ask the user to update the number, but when I tried to update it in AWS, they returned the exception "the user is not authentic". How can I update the number to the correct number after the user just signup(confirmed) and still not authenticated?

Development URL -

dev-webapp.myhomey.io

### Expected behavior

The user should be able to edit the phone number somehow.

### Reproduction steps

Steps to replicate the issue:

1. The user enters details on the signup page in UI (First and last name, Email, Phone Number and Password (Wrong phone number by mistake))
2. AWS send OTP confirmation code to email
3. The user enters OTP in the UI, the email field is verified and the user is confirmed
4. The user tries to log in and AWS tries to send OTP to the user's phone number (MFA Enabled)

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
I don't think there's a way to change the user's phone number after sign up without logging into their account.

You should, however, be able to disable MFA on their account from the Cognito console, let them log in and update their phone attribute through the UI and re-enable MFA.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!
