### ISSUE TITLE
"Invalid phone number format" when adding MFA phone number with dropdown

### ISSUE THREAD

**Issue by ashleyoldershaw** [aws-amplify/amplify-js#8274]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

Note that this issue is also happening on the hosted version for my development and staging environment.

<details>

```
# Put output below this line
  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 24.79 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.14.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.7.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Safari: 14.1
  npmPackages:
    @aws-amplify/ui-components: ^1.3.0 => 1.3.0 
    @aws-amplify/ui-react: ^1.1.0 => 1.1.0 
    @testing-library/jest-dom: ^5.11.9 => 5.12.0 
    @testing-library/react: ^11.2.3 => 11.2.6 
    @testing-library/user-event: ^12.6.2 => 12.8.3 
    amplify-ui-components-loader:  undefined ()
    aws-amplify: ^3.4.0 => 3.4.0 
    bootstrap: ^4.6.0 => 4.6.0 
    bootswatch: ^4.6.0 => 4.6.0 
    eslint: ^7.18.0 => 7.26.0 
    eslint-config-airbnb: ^18.2.1 => 18.2.1 
    eslint-config-standard: ^16.0.2 => 16.0.2 
    eslint-plugin-import: ^2.22.1 => 2.22.1 
    eslint-plugin-jsx-a11y: ^6.4.1 => 6.4.1 
    eslint-plugin-node: ^11.1.0 => 11.1.0 
    eslint-plugin-promise: ^4.2.1 => 4.3.1 
    eslint-plugin-react: ^7.22.0 => 7.23.2 
    eslint-plugin-react-hooks: ^4.2.0 => 4.2.0 
    formik: ^2.2.6 => 2.2.6 
    jquery: ^3.5.1 => 3.6.0 
    memo-parser:  0.2.1 
    react: * => 16.14.0 (17.0.1)
    react-dom: * => 16.14.0 
    react-scripts: ^4.0.3 => 4.0.3 
    timers-browserify: ^2.0.12 => 2.0.12 
    web-vitals: ^0.2.4 => 0.2.4 
    yup: ^0.32.8 => 0.32.9 
  npmGlobalPackages:
    @aws-amplify/cli: 4.49.0
    @cloudflare/wrangler: 1.13.0
    eslint: 7.18.0
    express-generator: 4.16.1
    ganache-cli: 6.0.3
    npm: 7.7.6
    truffle: 4.0.1

```

</details>

### Describe the bug

When an admin invites a user to join the project using the default amplify auth setup, we need the phone number for our MFA. When we enter the number using the dropdown country code and then the rest of the number, it says "Invalid phone number format".

![image](https://user-images.githubusercontent.com/15020968/118262806-55fe4080-b4ad-11eb-9e93-8ea1779e4bee.png)

This also happens when we add a leading 0 into the phone number, and is only resolved when the country code is put in the text box as well.

### Expected behavior

Ideally, we wouldn't need to add the country code to the text box as well, or we could get rid of the dropdown option. Either works :)

### Reproduction steps

1. Set up auth on the project
2. Enforce MFA
3. Invite user via the admin UI
4. Log in with temporary password
5. Attempt to put in phone number for +44 on the drop down (I am from the UK and haven't tried for any other countries)

e.g. for a UK phone number of +441234567890 you can select +44 from the dropdown and try 1234567890 or 01234567890. It will only work with +441234567890 in the text box.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by ashleyoldershaw** [comment]
Hi there, 

I didn't respond to some of the questions because they didn't seem relevant, but if you need them let me know and I'll put them on there ASAP.

Thanks,
Ash

**Comment by chrisbonifacio** [comment]
So does it seem like the country code is not being applied to the phone number before it is sent to cognito?

**Comment by ashleyoldershaw** [comment]
That's what I'm thinking, yes :)

**Comment by chrisbonifacio** [comment]
Okay, I will try and reproduce this issue and see if I can figure out what might be happening here. Thank you!

**Comment by ashleyoldershaw** [comment]
Thanks Chris, let me know if there's anything I can do to help :)

**Comment by eddiekeller** [comment]
@ashleyoldershaw We are trying to reproduce this so we can tackle this issue for you, but I'm having a bit of trouble doing so. Can you share some info with me?

1. Can you share your code where you set up the Amplify authenticator in your app?
2. Can you show the request that is being sent in the network logs to Cognito when attempting to submit the phone number?
3. Is there any output being logged to the browser's console?
4. Which version of Amplify are you using?

**Comment by ashleyoldershaw** [comment]
Hi @eddiekeller, no problem!

1. In terms of authentication, I'm just using the following in the `index.js`: `export default withAuthenticator(App)`, we have some required attributes, `name`, `email`, `phone_number` and we have `AllowAdminCreateUserOnly` set to true
2. I send the request off and had a look at the request on the developer's console, the response was `{"__type":"InvalidParameterException","message":"Invalid phone number format."}`. It returned a 400, image attached
3. The only output is in the image
4. My amplify version in the `package-lock.json` and set to `^3.4.0`. I think it might be 3.4.3 but not sure


![image](https://user-images.githubusercontent.com/15020968/122424493-aa05b480-cf86-11eb-977c-8818d380b03b.png)

**Comment by zchenwei** [comment]
Hi @ashleyoldershaw, are you using `withAuthenticator` inside of our new UI component library `@aws-amplify/ui-react`? I am trying to set up an app with auth and enforce MFA to reproduce it but phone number is not required when changing the user password.

**Comment by eddiekeller** [comment]
@ashleyoldershaw Hey, I just put out a PR that I think addresses this issue, from what I can understand. Take a look and let me know your thoughts. https://github.com/aws-amplify/amplify-js/pull/8489

**Comment by eddiekeller** [comment]
PR merged in here - https://github.com/aws-amplify/amplify-js/pull/8489

Closing this issue as this should be fixed now. Feel free to reopen and let us know if the fix does not address the issue properly.
