### ISSUE TITLE
Struggling with handling the handleSubmit event

### ISSUE THREAD

**Issue by juancpgo** [aws-amplify/amplify-js#8275]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Web Components

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
OS: macOS 10.15.7
(non relevant)

```

</details>

### Describe the bug

I'm struggling with the lack of documentation and information online regarding using Amplify UI Components for Web Components.

I need to customize the Sign up form, in which my user will fill out email and password, and I will fill out a custom username auto generated. (in my user pool I'll setup email as alias, so the user can always sign up with email).

I see in the [GitHub readme for the amplify-sign-up Web Component](https://github.com/aws-amplify/amplify-js/blob/main/packages/amplify-ui-components/src/components/amplify-sign-up/readme.md) that the component has this property `handleSubmit`, which is an event with default value `event => this.signUp(event)`.

### Expected behavior

I would like to customize this so that the form submission will trigger a function like this:
```
async function signUp() {
  try {
      const { user } = await Auth.signUp({
          username, // auto generated user id
          password,
          attributes: {
              email,
              phone_number,
              'custom:licenseStatus': 'trial',
              'custom:trialExpiration': new Date(),
          }
      });
      console.log(user);
  } catch (error) {
      console.log('error signing up:', error);
  }
}
```

But how do I set this function to be triggered by the Web Component?

For the `usernameAlias` property, I know that I can use the attribute `username-alias`, ex:
```
<amplify-sign-up username-alias="email" slot="sign-up"></amplify-sign-up>
```

But how do I trigger the `handleSubmit` property?

### Reproduction steps

non applicable

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by xnf** [comment]
I cannot answer about hooking into the submit payload (AFAIU handleSubmit is an alternative way and not a pre-hook or pre-action or pre-other). 

But I had a similar task for auto-generation of a username and I solved it by using the [custom fields feature](https://docs.amplify.aws/ui/auth/authenticator/q/framework/angular#custom-form-fields). Like this:
```typescript
  formFields: FormFieldTypes = [
    {
      type: 'username',
      label: 'ID',
      required: true,
      disabled: true,
      value: myGuidGeneratorFn()
    },
    /** other fields **/
  ];
```

**Comment by juancpgo** [comment]
@xnf Interesting.. but I suppose this will make the username visible in the form, just as a disabled (uneditable) field, right?

The solution I'm looking for is to auto-generate the username in the background, but also hide it from the user. The user will only sign up and sign in with their email.

Did you use just "pure" web components in your solution or did you use some framework, like Angular?

In the docs you linked it shows how to do this for Angular, but unfortunately I can't find anywhere an example of how to do this for just Web Components. I'm almost giving up on these UI Components, just because of the lack of examples and documentation. 😕

**Comment by eddiekeller** [comment]
Hey @juancpgo , I want to make sure that I'm understanding your question properly.

You should just be able to pass in your custom function to the `handle-submit` prop. Then the submit handler will call your custom function instead of the default one.

Maybe you can share how you are trying to set up/use this?

**Comment by wlee221** [comment]
I agree that our documentation is lacking regarding overriding `handleSubmit`. To add some clarity,

#### Passing Props
- On vue 2, you would set `:handleSubmit.prop="..."`. 
- On Angular, you'd set it with `[handleSubmit]="..."`

#### Triggering transition
After your Auth.signUp is completed, you need to make an Hub event with the `CognitoUser` object so that authenticator is aware of the state transition. 

```tsx
private customSubmit(event) {
  event.preventDefault();

  const formData = new FormData(event.target);
  const formValues = Object.fromEntries(formData);
  console.log({ event, data });

  const data = await Auth.signUp(formValues);

  Hub.dispatch(UI_AUTH_CHANNEL, {
    event: AUTH_STATE_CHANGE_EVENT,
    message: AuthState.ConfirmSignUp,
    data: { 
      ...data.user, 
      signUpAttrs: formData
    }
  });
}
```

I'll make a PR in our docs site soon. Please let us know if this works.

**Comment by eddiekeller** [comment]
Hey @juancpgo , I just merged in a PR yesterday that I think might address your issue - https://github.com/aws-amplify/amplify-js/pull/8474

It adds a new prop to specifically target overriding the `Auth.signUp()` method without losing all the functionality that using the `handleSubmit` prop causes. Try that out and let me know if it fixes things for you.

**Comment by wlee221** [comment]
I just merged https://github.com/aws-amplify/docs/pull/3346 that adds documentation to overriding sign up [here](https://docs.amplify.aws/ui/auth/authenticator/q/framework/angular#override-sign-up). We'll go ahead and close this, but please let us know if you need more clarification.
