### ISSUE TITLE
Datastore selective sync parsing expression incorrectly

### ISSUE THREAD

**Issue by vydhi-v** [aws-amplify/amplify-js#8284]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

NodeJS v14

### Amplify APIs

DataStore

### Environment information

<details>
NodeJS runtime v14, aws-amplify v4.0.2

```
# Put output below this line
The http request being sent to the appsync api seems to have incorrectly interpreted this expression and makes it look like
{
  query: "query operation(...)",
  variables: {
    limit:1000,
    nextToken: null,
    lastSync: 0,
    filter: {and: [{attr_name: {eq: "attr_value"}}]   }
  }
}


The API seems to set the "filter" value incorrectly and makes it think it has to look for a field called 'and' when in reality it is supposed to only look for a field named 'attr_name' 

```

</details>

### Describe the bug

Datastore syncExpression seems to not support the default syntax specified in the amplify docs for javascript. For a sync expression that looks like -
Datastore.configure({
  syncExpressiosn: [
    syncExpression(Test, (test) => test.attr_name('eq','attr_value'))
  ]
}) 

Request payload sent to the appsync URL seems to have incorrect variables. It looks like
{
  query: "query operation (...)",
  variables: {
    limit: 1000,
    nextToken: null,
    lastSync: 0,
    filter: {and: [{attr_name: {eq: "attr_value"}}] }
  }
}

The "filter" variable looks incorrect. This makes the request to look for a field named "and" in the graphQL schema type as opposed to the correctly defined "attr_name" field on which the original query was made in the first place. The response contains this error -
The variables input contains a field name 'and' that is not defined in for the input object type 'ModelTestFilterInput'

### Expected behavior

The syncExpression is translated as expected to use filter fields defined in the graphQL schema as opposed to 'and'

### Reproduction steps

Use syncExpression on any model following supported JS syntax specified in the docs. 

### Code Snippet

```javascript
Datastore.configure({
  syncExpressiosn: [
    syncExpression(Test, (test) => test.attr_name('eq','attr_value'))
  ]
}) 

```

### Log output

<details>

```
Request payload sent to the appsync URL seems to have incorrect variables. It looks like
{
  query: "query operation (...)",
  variables: {
    limit: 1000,
    nextToken: null,
    lastSync: 0,
    filter: {and: [{attr_name: {eq: "attr_value"}}] }
  }
}

The "filter" variable looks incorrect. This makes the request to look for a field named "and" in the filter type as opposed to the correctly defined "attr_name" field on which the original query was made in the first place. 

```

</details>

**Comment by iartemiev** [comment]
The filter generated by the sync expression is expected to be wrapped in an `and` operator. The resolver looks for this operator in order to craft a DynamoDB query or scan expression. 

Have you enabled DataStore on your API (`amplify api update -> GraphQL -> Enable DataStore for entire API`)? 

If so, could you share the generated sync query resolver code here? You can find it in `./amplify/backend/api/{your-app}/build/resolvers/Query.syncTests.req.vtl`

**Comment by vydhi-v** [comment]
This seems to work in a different project where I had used an older version of amplify datastore - 2.9.7. I had in fact observed that the request payload looks identical in that case too. So the cause for the error might not be what I had originally mentioned. The issue still stays though, I get the error response like I had mentioned before - 
The variables input contains a field name 'and' that is not defined in for the input object type 'ModelTestFilterInput'

One thing from your response that is of interest to me is the fact you mention enabling datastore for the "entire" API. Can you please elaborate on that?

What I have is an appsync schema that is hybrid in nature. My client-side app works by defining an apollo client to work with types/resolvers that are non-offline use-cases. The same client-side app also has an amplify Datastore configured separately to work with the same appsync (URL) schema. But it works on a subset of types and resolvers that are meant for offline use-cases. I have datastore working for the most part in that, these offline queries/mutation/subscriptions all work as expected. It is only the syncExpression that seems to have an issue. Will this not work out?

**Comment by iartemiev** [comment]
If you can please paste your sync query resolver code, we should be able to help you debug this further.

> One thing from your response that is of interest to me is the fact you mention enabling datastore for the "entire" API. Can you please elaborate on that?

That's just what the option is called in the Amplify CLI. 
Here's an example screenshot:
![image](https://user-images.githubusercontent.com/29709626/118882389-25aa0e00-b8c2-11eb-9604-e0a04f574efd.png)

In other words, your AppSync backend needs to be sync-enabled in order to work with DataStore correctly. If sync works, then I'm assuming you've enabled this option via the CLI already.

**Comment by vydhi-v** [comment]
Ok, that was helpful. I compared the resolvers with the working ones and figured out what I was doing wrong. Confirming this is not an issue
