### ISSUE TITLE
Area code filtering/customisation on Amplify Components using formFields phone_number

### ISSUE THREAD

**Issue by adampblack** [aws-amplify/amplify-js#8287]
### Is this related to a new or existing framework?

React

### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

There are hundreds of area codes which make it difficult for users to choose one.

Some apps are only rolled out to a small number of countries.

Also some users may not know what their country area code is.

It would be good to be able to:
1. Filter the number of area codes, and/or
2. Customise the number of area codes

### Describe the solution you'd like

On our app we have added some custom code to have the area code next to the country name.

![Screenshot 2021-05-18 at 10 07 20](https://user-images.githubusercontent.com/11552373/118579796-5a826c00-b7c1-11eb-810d-15d7a6c25872.png)

### Describe alternatives you've considered

This is what we currently use to filter but it does not work until the user focuses on to the phone_number area code input - It does not work when the component first renders (unless first page render in which the autofocus works)

`inputProps: {
                autofocus: true,
                onfocus: (objFocusEvent) => {
                  // amplify-country-dial-code
                  const objCountryDialCodeSelector = objFocusEvent.target.parentNode.parentNode.children[0];
                  // eslint-disable-next-line max-len
                  const objCountryDialCodeSelectBoxSelector = objCountryDialCodeSelector.shadowRoot.children[0].shadowRoot.children[0];

                  objCountryDialCodeSelectBoxSelector.innerHTML = '';

                  for (let index = 0; index < Object.keys(AREA_CODE_SETTINGS).length; index += 1) {
                    const option = document.createElement('option');
                    option.label = Object.values(AREA_CODE_SETTINGS)[index];
                    option.value = Object.keys(AREA_CODE_SETTINGS)[index];
                    objCountryDialCodeSelectBoxSelector.add(option);
                  }

                  // manually trigger an onchange event
                  const event = new Event('change');
                  objCountryDialCodeSelectBoxSelector.dispatchEvent(event);
                }
              },`

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by tannerabread** [comment]
This should now be possible with the current React Authenticator. It is shown here in the [docs here](https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#change-dial-code-list)

If this doesn't fit your use case, please open a new issue in the [UI repo](https://github.com/aws-amplify/amplify-ui)

Thank you!
