### ISSUE TITLE
npm update fails to install graphql dependency for aws-amplify-react

### ISSUE THREAD

**Issue by jfo8000** [aws-amplify/amplify-js#829]
Do you want to request a feature or report a bug?
bug

What is the current behavior?

Steps to repro:
Start with aws-amplify-react 0.1.38
npm update
Updates to 0.1.43
npm run start

Result:
Module not found: Can't resolve 'graphql/language/parser' in '/edited/my/path/to/node_modules/aws-amplify-react/dist/API/GraphQL'

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

What is the expected behavior?

'npm update' seemlessly updates

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by jfo8000** [comment]
This got me back up and running again:  
npm install graphql --save 

I'd love to avoid the dependency if I could.

**Comment by elorzafe** [comment]
@jfo8000 did you try the latest version of aws-amplify-react? That should have this issue solved

**Comment by jfo8000** [comment]
Great.  Will have a go of uninstalling it on my next upgrade.

**Comment by powerful23** [comment]
@jfo8000 I am going to close this issue now but if you have any further issue, please reopen it.
