### ISSUE TITLE
Federated sign in with Sign In With Apple fails because invalid scopes when more than one scope required

### ISSUE THREAD

**Issue by edu-zamora** [aws-amplify/amplify-js#8302]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 23.28 MB / 16.00 GB
    Shell: 5.1.4 - /usr/local/bin/bash
  Binaries:
    Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.4/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 87.0
    Safari: 14.0.1
  npmPackages:
    @babel/core: ^7.8.4 => 7.14.2
    @babel/runtime: ^7.8.4 => 7.14.0
    @react-native-async-storage/async-storage: 1.15.4 => 1.15.4
    @react-native-community/eslint-config: ^1.1.0 => 1.1.0
    @react-native-community/netinfo: 6.0.0 => 6.0.0
    @types/jest: 25.1.5 => 25.1.5
    @types/react: 16.14.0 => 16.14.0 (17.0.5, 16.14.6)
    @types/react-native: 0.63.49 => 0.63.49
    @types/react-test-renderer: 16.9.5 => 16.9.5
    HelloWorld:  0.0.1
    amazon-cognito-identity-js: 5.0.1 => 5.0.1
    aws-amplify: 4.0.1 => 4.0.1
    aws-amplify-react-native: 4.3.3 => 4.3.3
    babel-jest: ^25.1.0 => 25.5.1
    eslint: ^6.5.1 => 6.8.0
    hermes-inspector-msggen:  1.0.0
    jest: ^25.1.0 => 25.5.4
    metro-react-native-babel-preset: ^0.59.0 => 0.59.0
    react: 16.13.1 => 16.13.1
    react-animated:  0.1.0
    react-native: 0.63.4 => 0.63.4
    react-test-renderer: 16.13.1 => 16.13.1
    typescript: ^4.2.4 => 4.2.4
  npmGlobalPackages:
    @aws-amplify/cli: 4.51.0
    appcenter-cli: 2.7.3
    detox-cli: 18.0.0
    eslint: 7.9.0
    expo-cli: 4.0.17
    flow-bin: 0.133.0
    lerna: 3.22.1
    node-gyp: 7.1.0
    npm-check: 5.9.2
    npm: 6.14.6
    shx: 0.3.2
    ts-node: 9.0.0
    ts-prune: 0.8.3
    typescript: 4.0.2
```

</details>

### Describe the bug

For a user pool with Sign In With Apple configured as Identity Provider and with the Email and Name scopes selected, calling `Auth.federatedSignIn({ provider: CognitoHostedUIIdentityProvider.Apple })` does not work as expected. The Apple ID webpage will be opened, but it will show the next error: `invalid_request (Invalid client scope)`.

The scope in the URL is specified as `scope=email%2Cname`. If I manually change it to `scope=email%20name` and refresh, the expected page loads successfully and I can successfully sign in.

### Expected behavior

The scopes should be properly provided to Apple ID, so the page loads successfully without errors and users can sign in.

### Reproduction steps

1. Follow the Get Started tutorial for React Native: https://docs.amplify.aws/start/q/integration/react-native
2. When running `amplify add auth`, provide the next answers:
     ```
     Using service: Cognito, provided by: awscloudformation

   The current configured provider is Amazon Cognito.
  
   Do you want to use the default authentication and security configuration? Default configuration with Social Provider (Federation)
   Warning: you will not be able to edit these selections.
   How do you want users to be able to sign in? Username
   Do you want to configure advanced settings? Yes, I want to make some additional changes.
   Warning: you will not be able to edit these selections.
   What attributes are required for signing up? Email, Family Name (This attribute is not supported by Login With Amazon.), Given Name (This attribute is not supported by Login With Amazon.)
   Do you want to enable any of the following capabilities?
   What domain name prefix do you want to use? scopes-bug
   Enter your redirect signin URI: scopesbug://
    ? Do you want to add another redirect signin URI No
     Enter your redirect signout URI: scopesbug://
    ? Do you want to add another redirect signout URI No
     Select the social providers you want to configure for your user pool: Facebook, Google, Sign in with Apple
     ```
3. Add a button on the React Native app:
    ```
       <Button
          title="Sign in with Apple"
          onPress={() =>
            Auth.federatedSignIn({
              provider: CognitoHostedUIIdentityProvider.Apple,
            })
          }
        />
    ```
4. Run the app and tap on that button
5. You should see the next error:
<img width="1037" alt="Screenshot 2021-05-19 at 12 24 24" src="https://user-images.githubusercontent.com/129863/118810113-c80ac700-b8ab-11eb-8fa1-6282026a2c98.png">

### aws-exports.js

```javascript
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": COGNITO_IDENTITY_POOL_ID,
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": USER_POOLS_ID,
    "aws_user_pools_web_client_id": USER_POOLS_WEB_CLIENT_ID,
    "oauth": {
        "domain": "scopesbug.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "scopesbug://",
        "redirectSignOut": "scopesbug://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};
```

**Comment by edu-zamora** [comment]
For the record, if I uncheck one of the scopes (either Email or Name, it does not matter which one) for the Sign In With Apple Identify Provider from the Cognito console, the Apple ID sign in page loads successfully.

<img width="1229" alt="sign-in-with-apple-one-scope" src="https://user-images.githubusercontent.com/129863/118813930-eb377580-b8af-11eb-8a5f-6d11d2c5951c.png">
<img width="1039" alt="apple-id-with-one-scope" src="https://user-images.githubusercontent.com/129863/118814485-7fa1d800-b8b0-11eb-9b4b-c844ba720a1a.png">

**Comment by edu-zamora** [comment]
Hi @chrisbonifacio! Were you able to reproduce the issue? If that's so, do we have an estimation on when will it be fixed? Meanwhile, is there a workaround so we can request both the Email and Name scopes from Apple?

Thank you for your time! :)

**Comment by edu-zamora** [comment]
I tried the repro steps again and the issue seems to be fixed :) The Apple ID page loads successfully and I can see `scope=email%20name` in the URL.

Thank you a lot!

**Comment by chrisbonifacio** [comment]
Hey @edu-zamora ! Sorry for the delayed reply. I wasn't able to reproduce it but I did make the team aware of it. Thank you for bringing it to our attention, glad to see it's fixed now 😄

**Comment by edu-zamora** [comment]
In case it is helpful for anyone: I bumped into this issue again when creating a new user pool with "Sign in with Apple" by using `amplify add auth`, but I was able to fix it by re-integrating "Sign in with Apple" from the AWS Console.

To be a bit more specific, these are the steps I followed:
1. Navigate to the specific user pool in the AWS Console
2. Click on `Federation > Identity Providers`
3. Select "Sign in with Apple" and click on the "Disable" button
4. Select "Sign in with Apple" again, fill in all required fields, check the Email and Name scopes and click on the "Enable Sign in with Apple" button
5. Go to `Federation > Attribute mapping`, click on the "Apple" tab and make sure that the attributes are mapped correctly
6. Go to `App Integration > App client settings` and for each app that needs it, check "Sign in with Apple" (under "Enabled Identity Providers") and then click on the "Save changes" button

**Comment by jacdx** [comment]
I had this issue. It was a configuration issue on my end. In order to setup the oAuth provider on Cognito for Apple (via Terraform) and I suspect CloudFormation, too, I could specify the scopes as "email,name" or "email name". Both succeeded in configuring Cognito correctly, but the "email,name" scope caused 'invalid client scope' errors in practice.
