### ISSUE TITLE
 IndexedDBAdapter with custom dbName

### ISSUE THREAD

**Issue by UXDart** [aws-amplify/amplify-js#8310]
### Is this related to a new or existing framework?

React

### Is this related to a new or existing API?

DataStore

### Describe the feature you'd like to request

allow to define the dbName to be used in IndexedDBAdapter / allow to stop change start new usages of the adapter

### Describe the solution you'd like

I want to use the actual  IndexedDBAdapter but with another dbName, I think I could just extend  IndexedDBAdapter and override dbName. but then how do you use the new adapter? also if I do .stop() .configure() or change the dbName and .start() can I use a different db in that case? if not can it be supported? this would be useful to use for different users on same app. thanks

### Describe alternatives you've considered

same as solution

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by iartemiev** [comment]
@UXDart, could you please tell us a bit more about how being able to set a custom DB name would help in your use case?

If you're expecting multiple users to access your app on the same device, we recommend [clearing the local store](https://docs.amplify.aws/lib/datastore/sync/q/platform/js#clear-local-data) via `DataStore.clear()` on sign out, particularly, if you're storing potentially sensitive/private data. 

If you were to create additional databases with different names, those databases would be available to all users of your app (e.g., via DevTools), provided they access the app via the same domain, since IndexedDB abides by the same-origin policy.

**Comment by UXDart** [comment]
I see your point of different users having access, but the idea is one user with different accounts, imagine Slack (not sure if you use it) you can signin to different workspaces at the same time, but lets say you are signedin to one at a time. I want to set the dbName to something like 'amplify-db-workspaceId' so without cleaning it, I can setup again maybe using stop() re config the dbName and start(). and that way now the same user will be able to signin to another account. so each user/account access a different dbName, and yes is all in the localstorage so you can read it, but is the same user/person, but different accounts. Thx

**Comment by UXDart** [comment]
is this possible? how can I define which adapter to use? also will that work (stop re-configure start)? thanks

**Comment by iartemiev** [comment]
If you want to be able to switch between multiple IDB databases at runtime, you would need to perform more extensive changes than just setting the dbName in the storage adapter. The team will look into adding this as a feature in the future, but it's not something that is on our roadmap at the moment.

I would suggest checking out this blog post on how customers have built multi-tenant apps using DataStore: https://dev.to/aws-builders/the-guide-to-create-multi-tenant-apps-with-aws-amplify-28ic (it also uses Slack as an example).

**Comment by UXDart** [comment]
thanks, I'm not sure I like a lot the idea of the tenantId... it could easily sync data from user A to user B. and what about "saving auth data".. not sure how to do that. then calling signout, and simulating signin restoring auth data from other user? is there a auth.save auth.read way of doing that? I only need one user X using the app at one moment, but I can't ask the user to sign in again and again. TIA

**Comment by UXDart** [comment]
ok I decided to use separate (this is an electron app) browserview, so each one will have a different session, so each one will have its own signin and indexeddb db. so is like having many browsers each one on different user. thx!
