### ISSUE TITLE
Amplify federated sign-in redirect issue on Samsung browser

### ISSUE THREAD

**Issue by byyoungjin** [aws-amplify/amplify-js#8314]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 173.05 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 90.0.4430.212
    Firefox Nightly: 83.0a1
    Safari: 14.0.3
  npmPackages:
    @babel/core: ^7.9.0 => 7.14.0 (7.9.0)
    @react-native-community/masked-view: ^0.1.11 => 0.1.11 
    @react-native-community/netinfo: ^6.0.0 => 6.0.0 
    @react-navigation/native: ^5.9.4 => 5.9.4 
    @react-navigation/stack: ^5.14.4 => 5.14.4 
    @types/react: ~16.9.35 => 16.9.56 (17.0.4)
    @types/react-native: ~0.63.2 => 0.63.52 
    @typescript-eslint/eslint-plugin: ^4.22.0 => 4.22.0 
    @typescript-eslint/parser: ^4.22.0 => 4.22.0 
    HelloWorld:  0.0.1 
    awesome-phonenumber: ^2.50.0 => 2.50.0 
    aws-amplify: ^3.4.0 => 3.4.0 
    babel-plugin-module-resolver: ^4.1.0 => 4.1.0 (3.2.0)
    babel-preset-expo: ~8.3.0 => 8.3.0 
    date-fns: ^2.21.3 => 2.21.3 
    eslint: ^7.25.0 => 7.25.0 
    eslint-plugin-react: ^7.23.2 => 7.23.2 
    expo: ~41.0.1 => 41.0.1 
    expo-apple-authentication: ~3.1.0 => 3.1.0 
    expo-linking: ~2.2.3 => 2.2.3 
    expo-splash-screen: ~0.10.2 => 0.10.2 
    expo-updates: ~0.5.4 => 0.5.4 
    hermes-inspector-msggen:  1.0.0 
    jest-expo: ~41.0.0 => 41.0.0 
    react: 16.13.1 => 16.13.1 
    react-animated:  0.1.0 
    react-dom: 16.13.1 => 16.13.1 
    react-native: ~0.63.4 => 0.63.4 
    react-native-gesture-handler: ^1.10.3 => 1.10.3 
    react-native-reanimated: ^2.1.0 => 2.1.0 
    react-native-redash: ^16.0.11 => 16.0.11 
    react-native-safe-area-context: ^3.2.0 => 3.2.0 
    react-native-screens: ^3.2.0 => 3.2.0 
    react-native-svg: 12.1.0 => 12.1.0 
    react-native-svg-transformer: ^0.14.3 => 0.14.3 
    react-native-unimodules: ~0.13.3 => 0.13.3 
    react-native-web: ~0.13.12 => 0.13.18 
    typescript: ~4.0.0 => 4.0.7 
    yup: ^0.32.9 => 0.32.9 
  npmGlobalPackages:
    @aws-amplify/cli: 4.43.0
    @react-native-community/cli: 4.13.1
    bit-bin: 14.8.8
    expo-cli: 4.4.6
    express-generator: 4.16.0
    firebase-tools: 8.9.2
    fsevents: 1.2.7
    http-server: 0.11.1
    jest: 24.5.0
    json-server: 0.16.1
    mongo-hacker: 0.0.16
    n: 7.1.0
    nave: 3.2.2
    netlify-cli: 2.36.0
    node-sass: 4.13.0
    node: 12.6.0
    nodemon: 1.18.10
    now: 15.7.0
    npm: 6.14.11
    parcel-bundler: 1.12.4
    r: 0.0.5
    rimraf: 3.0.2
    serve: 11.0.2
    ts-node: 9.0.0
    typescript: 4.0.2
    watchman: 1.0.0


```

</details>

### Describe the bug

This is what I recorded. 
https://www.youtube.com/watch?v=t8tZ4SvKiqM

I'm using 
- Galaxy 8
- android 9 
- Samsung Internet browser (version 5.4.21.52) 

what happens is 
1. Press 'Sign in with google' ->It open Samsung internet which is default.
2. Select google user in the browser -> it shows indicator like forever and never redirect. 

So, 
3. I just go back to my app manually and press 'Sign in with google' again 
-> Then it redirect to the previous Samsung internet page. And now it redirect to my app. 

So, user need to go to my app manually to actually sigin in. 
chrome and safari doesn't show this behavior. Just work fine. 
It only happens on 'Samsung browser' so far. 

I think it's kind of edge case.
I just want to know is there is any solution from amplfy to improve user experience. 

### Expected behavior

It should redirect to my app. Not indicator running like forever. 

### Reproduction steps

1. set samsung browser as deafult browser app. 
2. press federated signin button on the app 
3. select google user 
4. You can see indicator running forever.

### Code Snippet

```javascript
// Put your code below this line.
// this is my google login button
 <Button
              title="구글로 로그인 하기"
              style={styles.loginbutton}
              accesoryLeft={<Icon name="googleLogo" size="small" />}
              onPress={async () => {
                await Auth.federatedSignIn({
                  provider: CognitoHostedUIIdentityProvider.Google,
                });
              }}
            />

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

```jsavscript 
{
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:4a568c89-06e5-4d96-8342-0796a2ccef11",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_WxHVEyfuH",
    "aws_user_pools_web_client_id": "1em9jpbo9785eddeq56u6m9cik",
    "oauth": {
        "domain": "pnuuclientmobile-develop.auth.ap-northeast-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "pnuu://,exp://127.0.0.1:19000/--/",
        "redirectSignOut": "pnuu://,exp://127.0.0.1:19000/--/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://672safabpnbdfpm3j7pghlg5o4.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-iublij3dbvdefki6ylmn77tvt4"
```

### Mobile Device

galaxy 8 

### Mobile Operating System

android 9 

### Mobile Browser

samsung internet 

### Mobile Browser Version

5.4.21.52

### Additional information and screenshots

recorded video
https://www.youtube.com/watch?v=t8tZ4SvKiqM

**Comment by chrisbonifacio** [comment]
Hi @byyoungjin 👋 Sorry to hear you are experiencing this issue. Unfortunately, we don't officially support the Samsung Internet browser.

[These are the browsers we do support](https://aws.amazon.com/premiumsupport/knowledge-center/browsers-management-console/)

I tried to see if I could reproduce this but while I'm able to emulate a Samsung Galaxy device in Android Studio, there doesn't seem to be a way to emulate Samsung Internet without a physical device.
