### ISSUE TITLE
May I have a way to override the height of auth-container?

### ISSUE THREAD

**Issue by lhmcn** [aws-amplify/amplify-js#8329]
### Is this related to a new or existing framework?

React

### Describe the feature you'd like to request

The min-height of auth-container is set to 100vh, and it's a shadow DOM and cannot be overridden. It seems it's designed for full-screen use. But what if the user wants to go back without logging in? I must have a navbar on the top or bottom, therefore it cannot be full-screen.

### Describe the solution you'd like

Allow the styles to be overridden by specifying the className or style.

### Describe alternatives you've considered

Allow the values to be overridden by :root values.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by wlee221** [comment]
Hello @lhmcn, thanks for raising this issue! You mean `amplify-container`, not `amplify-auth-container`, right? 

We recently had this PR https://github.com/aws-amplify/amplify-js/pull/8181 that removed shadow DOM from `amplify-container` so you should be able to target and style it with CSS directly. Can you try the latest `@aws-amplify/ui-react` and see if you're able to style it?

**Comment by lropero** [comment]
`<AmplifyAuthenticator style={{ '--container-height': 'auto' }} />`

**Comment by wlee221** [comment]
@lropero Ah, yes -- to change the inner container properties, using css variable would be the preferred way. Thanks for bringing this up! I'll close this issue as alternatives have been suggested, but please let us know if you have questions.
