### ISSUE TITLE
Uncaught ReferenceError: exports is not defined in CryptoOperation.js - Svelte Typescript

### ISSUE THREAD

**Issue by adikdev5** [aws-amplify/amplify-js#8332]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
 System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 482.82 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.5 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 7.5.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 57.0
    Safari: 14.0.3
  npmPackages:
    @rollup/plugin-commonjs: ^17.0.0 => 17.1.0 
    @rollup/plugin-json: ^4.1.0 => 4.1.0 
    @rollup/plugin-node-resolve: ^11.0.0 => 11.2.1 
    @rollup/plugin-typescript: ^8.0.0 => 8.2.1 
    @tsconfig/svelte: ^1.0.0 => 1.0.10 
    aws-amplify: ^4.0.2 => 4.0.2 
    rollup: ^2.3.4 => 2.49.0 
    rollup-plugin-css-only: ^3.1.0 => 3.1.0 
    rollup-plugin-livereload: ^2.0.0 => 2.0.0 
    rollup-plugin-svelte: ^7.0.0 => 7.1.0 
    rollup-plugin-terser: ^7.0.0 => 7.0.2 
    sirv-cli: ^1.0.0 => 1.0.11 
    svelte: ^3.0.0 => 3.38.2 
    svelte-check: ^1.0.0 => 1.5.4 
    svelte-preprocess: ^4.0.0 => 4.7.3 
    tslib: ^2.0.0 => 2.2.0 (1.14.1)
    typescript: ^4.0.0 => 4.2.4 
  npmGlobalPackages:
    @aws-amplify/cli: 4.51.2
    docker: 1.0.0
    n: 2.1.12
    npm: 7.5.4
    yarn: 1.12.3

```

</details>

### Describe the bug

I have been encountering build issue while integrating Amplify auth in Svelte app with Typescript

I also created [very simple Svelte app created from boilerplate + Amplify SDK](https://github.com/adikdev5/svelte-typescript-app/) to reproduce

![Screen Shot 2021-05-23 at 6 18 41 PM](https://user-images.githubusercontent.com/1070328/119284057-a4b98200-bbf3-11eb-8758-a1423a842560.png)

![Screen Shot 2021-05-23 at 6 22 37 PM](https://user-images.githubusercontent.com/1070328/119284161-e4806980-bbf3-11eb-8fac-3006eb90e16f.png)

### Expected behavior

Application should build without the error

### Reproduction steps

Follow [this Svelte with Typescript tutorial](https://svelte.dev/blog/svelte-and-typescript)
`npx degit sveltejs/template svelte-typescript-app`
`cd svelte-typescript-app`
`node scripts/setupTypeScript.js`

Install amplify SDK and @rollup/plugin-json
`npm i aws-amplify @rollup/plugin-json --save-dev`

In rollup config file, (I had to do this because there was build error when I added Amplify SDK)
1. Set preferBuiltins to false
https://github.com/adikdev5/svelte-typescript-app/blob/master/rollup.config.js#L65
2. Add the json plugin
https://github.com/adikdev5/svelte-typescript-app/blob/master/rollup.config.js#L73

Add Amplify auth on main.ts
https://github.com/adikdev5/svelte-typescript-app/blob/master/src/main.ts#L7

or

You may clone [this sample repo](https://github.com/adikdev5/svelte-typescript-app)

Then, run the app in localhost by following
1. run `npm i`
2. run ` npm run dev`

### Code Snippet

https://github.com/adikdev5/svelte-typescript-app/blob/master/src/main.ts#L7

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

````javascript
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {    
"aws_project_region": "us-east-1"
};

export default awsmobile;
````

**Comment by chrisbonifacio** [comment]
Hey, @adikdev5  👋 Would you mind trying to add this to your rollup config?

`@rollup/plugin-replace`

```js
replace({
      'Object.defineProperty(exports, "__esModule", { value: true });': '',
      delimiters: ['\n', '\n']
    }),
```

**Comment by adikdev5** [comment]
Hi @chrisbonifacio,
Thank you. I have tried and it did passed the build, however, the page does not load and getting this error when I try to use `Auth` in App.svelte. 
Are we sure it bundled properly by replacing that line?

![Screen Shot 2021-05-25 at 10 59 13 PM](https://user-images.githubusercontent.com/1070328/119609704-e3466c80-bdac-11eb-9a13-816f3e94eadf.png)


I found similar issues and it seems to be the issue with common js 
https://github.com/aws-amplify/amplify-js/issues/6202
https://github.com/aws-amplify/amplify-js/issues/2199

**Comment by josefaidt** [comment]
Hey @adikdev5 :wave: after taking a deeper look into this we've found a solution that has allowed us to add auth and sign up with a new user. 

- for the `Uncaught ReferenceError: require$$0$2 is not defined`, add the following to your rollup config
  ```diff
  export default {
    input: 'src/main.ts',
    output: {
      sourcemap: true,
      format: 'iife',
      name: 'app',
      file: 'public/build/bundle.js',
  +    globals: {
  +      'crypto': 'crypto'
  +    }
    },
    // ...
  ```
- we can remove the `replace` in rollup and add the following to our `index.html` file
  ```diff
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width,initial-scale=1'>

    <title>Svelte app</title>

    <link rel='icon' type='image/png' href='/favicon.png'>
    <link rel='stylesheet' href='/global.css'>
    <link rel='stylesheet' href='/build/bundle.css'>

  +	<script>
  +		window.global = window
  +		var exports = {}
  +	</script>
    <script defer src='/build/bundle.js'></script>
  </head>

  <body>
  </body>
  </html>

  ```
- and finally our `main.ts` file will look like this
  ```ts
  import App from './App.svelte';

  import { Amplify } from 'aws-amplify'
  import aws_exports from './aws-exports';

  Amplify.configure(aws_exports);

  const app = new App({
    target: document.body,
    props: {
      name: 'world',
    },
  });

  export default app;

  ```

**Comment by adikdev5** [comment]
It worked! Thank you so much.
