### ISSUE TITLE
Can't resolve '@aws-amplify/core'

### ISSUE THREAD

**Issue by barosanuemailtest** [aws-amplify/amplify-js#8333]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (1) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 145.68 MB / 6.40 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 14.11.0 - /usr/local/bin/node
    npm: 7.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 88.0.1
  npmPackages:
    @aws-amplify/auth: ^3.4.20 => 3.4.34 
    @testing-library/jest-dom: ^5.11.9 => 5.12.0 
    @testing-library/react: ^11.2.5 => 11.2.7 
    @testing-library/user-event: ^12.8.3 => 12.8.3 
    @types/jest: ^26.0.22 => 26.0.23 
    @types/node: ^12.20.5 => 12.20.13 
    @types/react: ^17.0.3 => 17.0.6 
    @types/react-dom: ^17.0.2 => 17.0.5 
    @types/react-router-dom: ^5.1.7 => 5.1.7 
    @types/react-test-renderer: ^17.0.1 => 17.0.1 
    aws-amplify: ^3.3.17 => 3.4.3 
    react: ^17.0.1 => 17.0.2 (17.0.1)
    react-dom: ^17.0.1 => 17.0.2 
    react-router-dom: ^5.2.0 => 5.2.0 
    react-scripts: 4.0.3 => 4.0.3 
    react-test-renderer: ^17.0.2 => 17.0.2 
    ts-jest: ^26.5.4 => 26.5.6 
    ts-node: ^9.1.1 => 9.1.1 
    typescript: ^4.2.3 => 4.2.4 
    web-vitals: ^1.1.0 => 1.1.2 
  npmGlobalPackages:
    @angular/cli: 8.3.19
    aws-cdk: 2.0.0-rc.1
    electron-packager: 14.1.0
    generator-code: 1.2.8
    n: 7.0.1
    npm: 7.6.0
    npx: 10.2.0
    stable: 0.1.8
    ts-node: 9.1.1
    typescript: 4.2.4
    vsce: 1.69.0
    yo: 3.1.0

```

</details>

### Describe the bug

Trying to run a simple login form in React with AWS amplify. With the latest version I get this error o npm start:
```
Can't resolve '@aws-amplify/core'
```

However, the project starts just fine with AWS amplify 3.3.17.

### Expected behavior

Expect error to not appear and project to compile fine.

### Reproduction steps

1. Install AWS amplify into React project
2. Write minimal login logic
3. Npm start

### Code Snippet

```javascript
// Put your code below this line.
import { User, UserAttribute } from '../model/Model'
import { CognitoUser } from '@aws-amplify/auth'
import { config } from './config';
import { Auth } from 'aws-amplify';
import Amplify from 'aws-amplify';

Amplify.configure({
    Auth: {
        mandatorySignIn: false,
        region: config.REGION,
        userPoolId: config.USER_POOL_ID,
        userPoolWebClientId: config.APP_CLIENT_ID,
        identityPoolId: config.IDENTITY_POOL_ID,
        authenticationFlowType: 'USER_PASSWORD_AUTH'
    }
})

export class AuthService {

    public async login(userName: string, password: string):Promise<User | undefined> {
        const user = await Auth.signIn(userName, password) as CognitoUser;
        const realUserName = user.getUsername();
        return {
            cognitoUser: user,
            userName: realUserName
        }

    }
}
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
I created a TS project with those packages and versions you have but did not run into this issue.

There's probably some issue with the dependency versions not matching.
https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js

If that doesn't work, would you mind removing the `@aws-amplify/auth` package and importing Auth from `aws-amplify` instead?

You should still be able to import `CognitoUser` from `@aws-amplify/auth` without it explicitly installed since it's already included in the `aws-amplify` package."

Let me know if any of this helps.

**Comment by martinmalia** [comment]
I also have this issue with a project. Amplify 3.4.3 works fine but @aws-amplify/core package is missing in node modules for 4 onwards. API has a dependency on core which it can not find. @chrisbonifacio how are you creating the TS project because I have been unable to get a single project to work following the Amplify directions and using amplify 4.

**Comment by barosanuemailtest** [comment]
I've made a mistake in the environment information of this issue. With aws-amplify: ^3.3.17 everything is OK, but the problem appears on aws-amplify 4. 
Can you please check if you can reproduce the issue with aws-amplify 4?

**Comment by martinmalia** [comment]
> I've made a mistake in the environment information of this issue. With aws-amplify: ^3.3.17 everything is OK, but the problem appears on aws-amplify 4.
> Can you please check if you can reproduce the issue with aws-amplify 4?

I get the same error with 4 no matter the framework or bundler. 3.4.3 includes the @aws-amplify/core folder in node modules while 4+ does not

**Comment by iartemiev** [comment]
I was able to reproduce this with npm@7 specifically. The issue is caused by conflicting peer dependencies and the way npm 7 handles them. PR with the fix has been opened: https://github.com/aws-amplify/amplify-js/pull/8368

**Comment by chrisbonifacio** [comment]
@barosanuemailtest please let us know if this is fixed for you now that the PR has been merged 😄

**Comment by iartemiev** [comment]
Just to clarify, you can test the changes in the PR by installing `aws-amplify@unstable` or specifically `aws-amplify@4.0.4-unstable.4`, but the change has not yet been released in a prod/stable version of Amplify. 

We'll release it later this week as part of version 4.0.4 of Amplify

**Comment by martinmalia** [comment]
> Just to clarify, you can test the changes in the PR by installing `aws-amplify@unstable` or specifically `aws-amplify@4.0.4-unstable.4`, but the change has not yet been released in a prod/stable version of Amplify.
> 
> We'll release it later this week as part of version 4.0.4 of Amplify

Nice job, looks good to me!

**Comment by barosanuemailtest** [comment]
Works great. Thanks!
