### ISSUE TITLE
DataStore syncExpression causing "Resolver invocation limit reached" error

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-js#8342]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

DataStore

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line
npx: installed 1 in 1.316s

  System:
    OS: Linux 4.14 Amazon Linux 2
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
    Memory: 6.22 GB / 7.58 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 10.23.1 - ~/.nvm/versions/node/v10.23.1/bin/node
    npm: 6.14.10 - ~/.nvm/versions/node/v10.23.1/bin/npm
  npmGlobalPackages:
    @aws-amplify/cli: 4.51.2
    cdk: 1.83.0
    coffeescript: 2.5.1
    esformatter: 0.11.3
    js-beautify: 1.13.2
    npm: 6.14.10
    prettier: 2.2.1
    typescript: 3.7.5

```

</details>

### Describe the bug

We have 31 Models in our database and 29 of them sync fine to DataStore - but 2 models fail with the message "Resolver invocation limit reached".

The message indicates that this is a system resource issue - but I think its a data problem. For example, one of the models where this error is thrown actually has no records that match the sync query.

### Expected behavior

Sync proceeds without misleading error message.

### Reproduction steps

See code snippet.

### Code Snippet

```javascript
// Put your code below this line.
// When using this expression it shows showing resolver limit error.
syncExpression(AssetVisitAttribute, () => {
return assetVisitAttribute => assetVisitAttribute.assetVisitAttributeOperatingUnitId('eq', operatingUnitId);
}),
//
//But….When using this it's working & record syncing to local cache
syncExpression(AssetVisitAttribute, () => {
return assetVisitAttribute => assetVisitAttribute.id('eq', 'b75e9816-5eca-4aec-bdcf-4959326a003f');
}),

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi :wave: Sorry this was auto-closed by stale bot. We are working towards preventing this from happening in the future. Please let us know if you are still experiencing this issue and in need of assistance.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!
