### ISSUE TITLE
SSE-C Customer provided encryption key

### ISSUE THREAD

**Issue by bmw46033** [aws-amplify/amplify-js#8346]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Storage

### Amplify Categories

storage, api

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 5.96 GB / 15.92 GB
  Binaries:
    Node: 15.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.964.0), Chromium (90.0.818.66)
    Internet Explorer: 11.0.19041.1
  npmGlobalPackages:
    npm: 7.9.0
    react-devtools: 4.8.2
    react-native-cli: 2.0.1
    serverless: 2.6.0

```

</details>

### Describe the bug

When specifying SSE-C (Server Side Encryption with Customer provided key) for the "Storage.Put" options, the current code requires you to add "serverSideEncryption: 'AES256'" yet the AWS specifications do not require this.  Specifying this option adds the following header to the request: "x-amz-server-side-encryption" = AES256 along with the rest of the headers needed for SSE-C: (as an example)
"x-amz-server-side-encryption-customer-algorithm" = AES256;
"x-amz-server-side-encryption-customer-key" = "at1TMx82nEy7SoAK8jHYanMQDVZMSLayXaaUvTc6CP0=";
"x-amz-server-side-encryption-customer-key-MD5" = "LWkBoT3psNdTYez70TVHUQ==";

which returns the following error as a response:
"Server Side Encryption with Customer provided key is incompatible with the encryption method specified"

Within AWSS3Provider.js, I commented out line 259 so that this header value is not populated as a test to verify.

                        if (serverSideEncryption) {
                            //params.ServerSideEncryption = serverSideEncryption;
                            if (SSECustomerAlgorithm) {
                                params.SSECustomerAlgorithm = SSECustomerAlgorithm;
                            }
                            if (SSECustomerKey) {
                                params.SSECustomerKey = SSECustomerKey;
                            }
                            if (SSECustomerKeyMD5) {
                                params.SSECustomerKeyMD5 = SSECustomerKeyMD5;
                            }
                            if (SSEKMSKeyId) {
                                params.SSEKMSKeyId = SSEKMSKeyId;
                            }
                        }
 
and using the following call:

        const result = await Storage.put(selectedNode.item.key + file.name, file, {
        level: 'private',
        serverSideEncryption: 'AES256',
        SSECustomerAlgorithm: 'AES256',
        SSECustomerKey: '12345678901234567890123456789012',
        SSECustomerKeyMD5: '767179c7a2bff19651ce97d294c30cfb'
        });    

Doing so worked and I was able to verify that the file was properly encrypted when uploaded.

### Expected behavior

I should either be using AWS managed encryption or customer provided key encryption.  However, the code assumes I am always using server side encryption with AWS via stored keys or KMS.

### Reproduction steps

1. Install Amp
2. Configure Storage
3. Call API to put a file in S3 with customer provided key.
4. You must add "serverSideEncryption: 'AES256' as an option.  Doing so will produce the error message.

### Code Snippet

```javascript
// Put your code below this line.

```
        const result = await Storage.put(selectedNode.item.key + file.name, file, {
        level: 'private',
        serverSideEncryption: 'XYZ',  // <-- arbitrary value with AWSS3Provider modified to not add the SSE header
        SSECustomerAlgorithm: 'AES256',
        SSECustomerKey: '12345678901234567890123456789012',
        SSECustomerKeyMD5: '767179c7a2bff19651ce97d294c30cfb'
        });    

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by jamesaucode** [comment]
Thanks @bmw46033.  I was able to repro this issue. It does seem like the AWS spec didn't mention anything about requiring `ServerSideEncryption` to be set to use SSE-C. This seems to  fix the issue:
```diff
@@ -280,18 +290,18 @@ export class AWSS3Provider implements StorageProvider {
                }
                if (serverSideEncryption) {
                        params.ServerSideEncryption = serverSideEncryption;
-                       if (SSECustomerAlgorithm) {
-                               params.SSECustomerAlgorithm = SSECustomerAlgorithm;
-                       }
-                       if (SSECustomerKey) {
-                               params.SSECustomerKey = SSECustomerKey;
-                       }
-                       if (SSECustomerKeyMD5) {
-                               params.SSECustomerKeyMD5 = SSECustomerKeyMD5;
-                       }
-                       if (SSEKMSKeyId) {
-                               params.SSEKMSKeyId = SSEKMSKeyId;
-                       }
+               }
+               if (SSECustomerAlgorithm) {
+                       params.SSECustomerAlgorithm = SSECustomerAlgorithm;
+               }
+               if (SSECustomerKey) {
+                       params.SSECustomerKey = SSECustomerKey;
+               }
+               if (SSECustomerKeyMD5) {
+                       params.SSECustomerKeyMD5 = SSECustomerKeyMD5;
+               }
+               if (SSEKMSKeyId) {
+                       params.SSEKMSKeyId = SSEKMSKeyId;
                }

                const emitter = new events.EventEmitter();
```
I will have a PR out in a moment

**Comment by bmw46033** [comment]
Thank you, James.  Any chance the Storage.Get will also incorporate SSE-C?  

REF: https://docs.aws.amazon.com/AmazonS3/latest/userguide/specifying-s3-c-encryption.html

Get object—Downloads the object uploaded in the previous step. In the request, you provide the same encryption information you provided when you uploaded the object. Amazon S3 needs this information to decrypt the object so that it can return it to you.
