### ISSUE TITLE
RFC: Logging Improvements

### ISSUE THREAD

**Issue by eddiekeller** [aws-amplify/amplify-js#8354]
Using this ticket as a storage site for ideas for future improvements for our logging solution.

** Future ideas **
* CloudWatch EMF logging support
* Support for more external cloud logging providers
* Move Logging into its own api category?
* Add in a separate log level for remote logging?
* Store logs "offline" until connectivity is restored

### Describe the solution you'd like

Will discuss with team moving forward about what ideas should take priority and outline a plan internally to tackle these. Will then create individual issues for each one.

**Comment by nubpro** [comment]
Does CloudWatch logging works while offline?

**Comment by eddiekeller** [comment]
@nubpro No, not yet. Although...I suppose the current implementation *will* keep trying to submit logs to CloudWatch while they exist in the queue...so once connectivity is restored, I would expect them to get pushed up.

But, that is an inelegant solution at the moment. There is certainly a better approach that can be taken. I will add that to the list in the parent comment.

**Comment by michaeljcalkins** [comment]
All of our teams lean into `CloudWatch EMF logging` quite heavily so that we don't have to setup MetricFilters in CDK.  That will likely be a blocker for teams from migrating to this at the moment.

`Store logs "offline" until connectivity is restored`, I hadn't thought of this one but would be incredibly insightful.

**Comment by sammartinez** [comment]
Resolving as this feature is out.

**Comment by aaronlna** [comment]
Thanks for releasing this feature.

I was trying to track down if there may be any future support for writing EMF logs or support for writing custom formatted logs, e.g. JSON log format for better querying with CW Insights. Are these improvements still being tracked anywhere or is support for these features at all planned?
