### ISSUE TITLE
Multiples @connection field values are not downloads in the local DB

### ISSUE THREAD

**Issue by djom202** [aws-amplify/amplify-js#8355]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

DataStore

### Amplify Categories

api

### Environment information

<details>

```
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 31.48 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    npm: 7.8.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.77
    Firefox: 88.0.1
    Safari: 14.0.3
  npmPackages:
    @fortawesome/fontawesome-free: ^5.13.0 => 5.13.0 
    @vue/cli-plugin-e2e-cypress: ~4.3.0 => 4.3.1 
    @vue/cli-plugin-eslint: ~4.3.0 => 4.3.1 
    @vue/cli-plugin-pwa: ~4.3.0 => 4.3.1 
    @vue/cli-plugin-router: ~4.3.0 => 4.3.1 
    @vue/cli-plugin-unit-mocha: ~4.3.0 => 4.3.1 
    @vue/cli-plugin-vuex: ~4.3.0 => 4.3.1 
    @vue/cli-service: ^3.3.1 => 3.3.1 
    @vue/eslint-config-airbnb: ^5.0.2 => 5.0.2 
    @vue/test-utils: 1.0.0-beta.31 => 1.0.0-beta.31 
    aws-amplify: ^3.3.16 => 3.3.16 
    axios: ^0.21.1 => 0.21.1 
    chai: ^4.1.2 => 4.2.0 
    eslint: ^6.7.2 => 6.8.0 
    eslint-plugin-import: ^2.20.2 => 2.20.2 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    memo-parser:  0.2.1 
    node-sass: ^4.14.1 => 4.14.1 
    register-service-worker: ^1.7.1 => 1.7.1 
    sass-loader: ^8.0.2 => 8.0.2 
    uiv: ^0.34.4 => 0.34.4 
    uuid: ^3.4.0 => 3.4.0 (3.3.2)
    v-mask: ^2.2.4 => 2.2.4 
    vue: ^2.6.11 => 2.6.11 
    vue-axios: ^3.2.4 => 3.2.4 
    vue-excel-editor: ^1.3.60 => 1.3.60 
    vue-google-charts: ^0.3.2 => 0.3.2 
    vue-gravatar: ^1.3.1 => 1.3.1 
    vue-moment: ^4.1.0 => 4.1.0 
    vue-number-animation: ^1.0.5 => 1.0.5 
    vue-qr-generator: ^3.0.1 => 3.0.1 
    vue-router: ^3.1.6 => 3.1.6 
    vue-select-image: ^1.9.0 => 1.9.0 
    vue-template-compiler: ^2.6.11 => 2.6.11 
    vue-window-size: ^0.6.2 => 0.6.2 
    vue2-filters: ^0.11.0 => 0.11.0 
    vue2-google-maps: ^0.10.7 => 0.10.7 
    vuex: ^3.1.3 => 3.2.0 
    vuex-persistedstate: ^3.0.1 => 3.0.1 
  npmGlobalPackages:
    @aws-amplify/cli: 4.49.0
    @vue/cli-service-global: 4.5.10
    @vue/cli: 4.5.10
    amplify: 0.0.11
    npm: 7.8.0
```

</details>

### Describe the bug

I'm creating a Model with 2 connections to another models, nevertheless I noticed that when I tried to get the information of that Model said that the property created `activityHistoryVehicleId` is null but the another one `activityHistoryActivityId` has a value, so I checked the dynamoDB and I see all fields has a value. So I thinking that when the sync try to download them just works if there is only one connection (so far it working for me thus).

Another point is when I tried to do a get the condition is equal to the id that I send and I got the error that `activityHistoryVehicleId` field not exist in the model.

### Expected behavior

The model must have all relationship fields with the id of the model.

### Reproduction steps

1. Create 3 model
2. Create a relationship on one of these models.
3. Insert a new records in the models without relationship
4. Insert a new record in the model with the relationship
5. Check in DynamoDB if exits that relationship field and their value
6. Check in the local DB if exits that relationship field and their value

### Code Snippet

```javascript
const resp = await DataStore.query(ActivityHistory, c => c
    .activityHistoryVehicleId('eq', params.vehicle)
    .createdAt('between', params.dateInit, params.dateEnd))
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

![image](https://user-images.githubusercontent.com/1834808/120022923-b2378900-bfb2-11eb-8dc2-88e1dccd27ff.png)

![image](https://user-images.githubusercontent.com/1834808/120022964-c11e3b80-bfb2-11eb-9649-73ddedb51288.png)

**Comment by iartemiev** [comment]
Hi @djom202, could you please share: 
1. the schema definitions for these 3 models
2. the app code where you're saving the data (e.g., where `activityHistoryVehicleId` is being set in the client)
3. is `activityHistoryVehicleId` showing up as `null` on the same device where you saved the data originally, or is that how the data syncs down to a different device?

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you in over a week. If you are still experiencing this issue and in need of assistance, please feel free to re-open and provide us with any information previously requested by our team members so we are better able to assist you. Thank you!
