### ISSUE TITLE
how to check if refresh token is expired ?

### ISSUE THREAD

**Issue by Jasminou** [aws-amplify/amplify-js#836]
Do you want to request a feature or report a bug?
question 

What is the current behavior?
Hi, I just wanted to know how I'm supposed to handle the expiration of the refresh token, there is no clear doc about it, there is no playlod containg the info about the expiration as the others tokens ( see below) 
![image](https://user-images.githubusercontent.com/14798195/40069886-88d70dfc-583a-11e8-99d5-3e2bf2c7aaf0.png)

Thanks

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

What is the expected behavior?

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by Jasminou** [comment]
he already answerd to my question on the chat so I'm closing this question

**Comment by powerful23** [comment]
Mark this a enhancement of the documentation to provide and example to handle refresh token expiration case.

**Comment by Ligia-Andreica** [comment]
I am also interested in this topic. Could you please answer this question here as well, until the documentation is updated?

**Comment by Jasminou** [comment]
@Ligia-Andreica  here you are: 
"... for now we don't have an example for that case. We will put that in our backlog. 
As a workaround you can log user our when catching an error from Auth.currentSession() 
we will mark this case in documentation in the future. You may try Auth.currentSession().catch(e => // log user out here); "

**Comment by BirgerMoell** [comment]
This is how I solved the problem. The function takes the payload.exp and compares it to current time.

checkTokenExpiration = expiration => {
    const currentUnixTime = new Date().getTime() / 1000
    if (currentUnixTime > expiration) {
      console.log("the token is expired!")
    }
    else {
      console.log("the token is valid")
    }
  };

**Comment by anis-shaikh** [comment]
@powerful23 Have you provided any documentation for this issue? Because I am facing the same issue. I want to validate the refreshToken, so please give me your input.

**Comment by sammartinez** [comment]
This is the [documentation](https://aws-amplify.github.io/docs/js/authentication#retrieve-current-session) we have on this. Resolving
