### ISSUE TITLE
Connection failed Max number of 100 subscriptions reached

### ISSUE THREAD

**Issue by MedNabilEssefaihi** [aws-amplify/amplify-js#8370]
Dear Support Team

I am using AWS Amplify in my React Native mobile app and Web app, they are real time app and they need to change data many times in short time, using **GraphQL** with **Subscription** Method

At the beginning everything works fine but after seconds It drops and get me an error message
 
`"Connection failed: {\"errors\":{\"errorType\":\"MaxSubscriptionsReachedError\",\"message\":\"Max number of 100 subscriptions reached\"}}"`

and sometimes it shows me another error like websocket is unconnected

### My question
What should I do to get unlimited subscription requests ?

thank you!

**Comment by chrisbonifacio** [comment]
Hi @MedNabilEssefaihi 👋 Would you mind sharing the code where you're creating the subscription for the user?

**Comment by iartemiev** [comment]
@MedNabilEssefaihi, are you using the Amplify API category or DataStore?

**Comment by MedNabilEssefaihi** [comment]
Dear Mr @siegerts,

Thank you for your answer and oriented my issue to the right place, I already readed that issue #6260 but I am using Amplify API not DataStore.

**Comment by MedNabilEssefaihi** [comment]
Dear @chrisbonifacio 

I am already fixed the problem

The code was: 

```
  useEffect(() => {
    //update when inService go to the next call
    API.graphql({
      query: subscriptions.onChangeInService,
      authMode: "AWS_IAM",
    }).subscribe({
      next: ({ provider, value }) => {
        setServices((old) => {
          return old.map((item) => {
            console.log("update inService", value.data.onChangeInService);
            if (item.id === value.data.onChangeInService.id) {
              return {
                ...item,
                inService: value.data.onChangeInService.inService,
              };
            } else {
              return item;
            }
          });
        });
      },
      error: (error) => console.log("update inservice ", error.error.errors[0]),
    });
  }, []);
```

and the solution was adding **.unsubscribe();** like this: 

```
 useEffect(() => {
    const changeInservice = API.graphql({   //  <== add const changeInservice 
      query: subscriptions.onChangeInService,
      authMode: "AWS_IAM",
    }).subscribe({
      next: ({ provider, value }) => {
        setServices((old) => {
          return old.map((item) => {
            console.log("update inService", value.data.onChangeInService);
            if (item.id === value.data.onChangeInService.id) {
              return {
                ...item,
                inService: value.data.onChangeInService.inService,
              };
            } else {
              return item;
            }
          });
        });
      },
      error: (error) => console.log("update inservice ", error.error.errors[0]),
    });

    return () => changeInservice.unsubscribe();    // <== add this one
  }, []);
```


⚠️ I find the solution in these sources : ⚠️
video:  https://www.youtube.com/watch?v=HZUlQ7Z2xHQ&t=2154s
AWS awmplify docs:  https://docs.amplify.aws/lib/graphqlapi/subscribe-data/q/platform/js#using-amplify-graphql-client


Thank you Sir for your answer

**Comment by MedNabilEssefaihi** [comment]
Dear Mr @iartemiev 

I am using AWS Amplify (with GraphQL API) not DataStore

**Comment by chrisbonifacio** [comment]
Awesome! I had a feeling it might've been the side effect cleanup lol

Thank you for the update and glad we could help! Enjoy the rest of your day, sir 😄

**Comment by MedNabilEssefaihi** [comment]
@chrisbonifacio thank you Mr
