### ISSUE TITLE
Subscription returns null when using both owner and group authorization

### ISSUE THREAD

**Issue by nathanagez** [aws-amplify/amplify-js#8373]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v16.0.0

### Amplify CLI Version

4.50.2

### What operating system are you using?

Mac

### Amplify Categories

auth, function, api

### Amplify Commands

push

### Describe the bug

When using both owner and group authorization returned data is null.
According to the documentation: 

"Finally, if you use both owner and group authorization then the username argument becomes optional. This means the following:
- If you don’t pass the user in, but are a member of an allowed group, the subscription will notify you of records added.
- If you don’t pass the user in, but are NOT a member of an allowed group, the subscription will fail to connect.
- If you pass the user in who IS the owner but is NOT a member of a group, the subscription will notify you of records added of which you are the owner.
- If you pass the user in who is NOT the owner and is NOT a member of a group, the subscription will not notify you of anything as there are no records for which you own"

So, when my user is part of a specified group I don't pass the owner to my subscription according to the documentation: `If you don’t pass the user in, but are a member of an allowed group, the subscription will notify you of records added` and when he's not (my user), I pass the owner value to my subscription.

In fact I'm notified, the subscription don't fail but I'm not able to see the data, 

```
provider: AWSAppSyncRealTimeProvider {_config: {…}, socketStatus: 1, keepAliveTimeout: 300000, subscriptionObserverMap: Map(1), promiseArray: Array(0), …}
value: data: onCreateCampaign: null
```

### Expected behavior

I am expecting non-null data, note that subscription works well with owner data.

### Reproduction steps

Subscribe to a model creation using both owner and group authentication.

Here is the snippet of code used for the subscription:

```js
const onCreateCampaign = async (campaigns, setCampaigns) => {
  const currentUser = await Auth.currentAuthenticatedUser();
  if (currentUser.username !== 'admin') {
    return API.graphql(
      graphqlOperation(subscriptions.onCreateCampaign, { owner: currentUser.username })
    ).subscribe({
      next: ({ provider, value }) => {
        console.log("subscription: ", { provider, value }, );
        setCampaigns([...campaigns, value.data.onCreateCampaign]);
      },
      error: (error) => console.warn(error),
    });
  }
  return API.graphql(
    graphqlOperation(subscriptions.onCreateCampaign)
  ).subscribe({
    next: ({ provider, value }) => {
      console.log("subscription: ", { provider, value });
      setCampaigns([...campaigns, value.data.onCreateCampaign]);
    },
    error: (error) => console.warn(error),
  });
};
```

### GraphQL schema(s)

<details>

```graphql
type Campaign
  @model
  @auth(rules: [{ allow: owner }, { allow: groups, groups: ["admin"] }]) {
  id: ID!
  name: String!
  description: String!
  stories: [Story] @connection(keyName: "byCampaign", fields: ["id"])
}

enum BackgroundType {
  COLOR
  IMAGE
  VIDEO
}

type Widget @model
@auth(rules: [{ allow: owner }, { allow: groups, groups: ["admin"] }])
@key(name: "byPage", fields: ["pageId"]) {
  id: ID!
  pageId: ID!
  name: String!
  category: String!
}

type Page @model 
  @auth(rules: [{ allow: owner }, { allow: groups, groups: ["admin"] }])
  @key(name: "byStory", fields: ["storyId"]) {
    id: ID!
    storyId: ID!
    backgroundType: BackgroundType!
    backgroundColor: String
    backgroundSource: String
    widgets: [Widget] @connection(keyName: "byPage", fields: ["id"])
}

type Story @model 
  @auth(rules: [{ allow: owner }, { allow: groups, groups: ["admin"] }])
  @key(name: "byCampaign", fields: ["campaignId"]) {
  id: ID!
  campaignId: ID!
  name: String!
  width: String
  height: String
  purpose: String
  pages: [Page] @connection(keyName: "byStory", fields: ["id"])
}

type Query {
  send(email: String!): String @function(name: "appsyncworkshop0018db7e-${env}")
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Not sure how you set up that subscription but have you tried setting the variables of your admin subscription to `{ owner: { eq: currentUser.username } }`?

If that doesn't work, could you please share what your schema looks like so that we can try to reproduce the issue with the same auth rules set up on that model?

**Comment by chrisbonifacio** [comment]
Hi @nathanagez are you still experiencing this issue? We've since released a v2 graphql transformer so I'm wondering if upgrading and migrating your API might help.

for more information: https://docs.amplify.aws/cli/migration/transformer-migration/

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!
