### ISSUE TITLE
Datastore start function error "Cannot read property 'version' of undefined"

### ISSUE THREAD

**Issue by CarlJoven** [aws-amplify/amplify-js#8374]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

DataStore

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 2.64 GB / 11.91 GB
  Binaries:
    Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.77
    Edge: Spartan (44.19041.964.0), Chromium (91.0.864.37)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @aws-amplify/api: ^4.0.1 => 4.0.1
    @aws-amplify/auth: ^4.0.1 => 4.0.1
    @aws-amplify/cache: ^4.0.3 => 4.0.3
    @aws-amplify/core: ^4.0.3 => 4.0.3
    @aws-amplify/datastore: ^3.0.3 => 3.0.3
    @aws-amplify/pushnotification: ^4.0.3 => 4.0.3
    @aws-amplify/storage: ^4.1.0 => 4.1.0
    @azure/core-asynciterator-polyfill: ^1.0.0 => 1.0.0
    @babel/core: ^7.12.9 => 7.14.0
    @babel/runtime: ^7.12.5 => 7.14.0
    @react-native-async-storage/async-storage: ^1.15.4 => 1.15.4
    @react-native-community/eslint-config: ^2.0.0 => 2.0.0
    @react-native-community/netinfo: ^6.0.0 => 6.0.0
    @types/jest: ^26.0.20 => 26.0.23
    @types/react-native: ^0.64.0 => 0.64.5
    @types/react-test-renderer: ^16.9.2 => 16.9.5
    HelloWorld:  0.0.1
    amazon-cognito-identity-js: ^4.6.1 => 4.6.1 (5.0.2)
    aws-amplify-react-native: ^4.3.3 => 4.3.3
    babel-jest: ^26.6.3 => 26.6.3
    babel-plugin-transform-remove-console: ^6.9.4 => 6.9.4
    eslint: ^7.14.0 => 7.26.0
    eslint-plugin-simple-import-sort: ^7.0.0 => 7.0.0
    hermes-inspector-msggen:  1.0.0
    husky: ^6.0.0 => 6.0.0
    jest: ^26.6.3 => 26.6.3
    lint-staged: ^11.0.0 => 11.0.0
    metro-react-native-babel-preset: ^0.64.0 => 0.64.0
    prettier: ^2.3.0 => 2.3.0
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0
    react-native-config: ^1.4.2 => 1.4.2
    react-native-elements: ^3.4.1 => 3.4.1
    react-native-keychain: ^7.0.0 => 7.0.0
    react-native-vector-icons: ^8.1.0 => 8.1.0
    react-native-version: ^4.0.0 => 4.0.0
    react-navigation: ^4.4.4 => 4.4.4
    react-redux: ^7.2.4 => 7.2.4
    react-test-renderer: 17.0.1 => 17.0.1
    redux: ^4.1.0 => 4.1.0
    redux-thunk: ^2.3.0 => 2.3.0
    typescript: ^3.8.3 => 3.9.9
  npmGlobalPackages:
    @aws-amplify/cli: 4.51.4
    aws-cdk: 1.106.1
    firebase-tools: 9.10.0
    gatsby-cli: 3.3.0
    graphql-ttl-transformer: 1.1.0
    npm: 6.14.11

```

</details>

### Describe the bug

Datastore throwing error "Cannot read property 'version' of undefined" and the synching process does not start.

### Expected behavior

Datastore should sync to the cloud.

### Reproduction steps

1. Install @aws-amplify/datastore
2. Go to App.tsx and import @aws-amplify/datastore
3. Call DataStore.start().catch(err => console.error(err)) inside useEffect react hook.
4. Error will encounter

### Code Snippet

```javascript
  useEffect(() => {
    DataStore.start().catch(err => console.error(err));
  }, []);
```

### Log output

![Capture](https://user-images.githubusercontent.com/32753771/120411505-7f610c80-c387-11eb-886f-bbaa79e712ac.PNG)

### Additional information and screenshots

When I am using the DataStore.query API, everything is alright but I only want to initially sync my datastore upon the start of the application.

**Comment by iartemiev** [comment]
Hi @CarlJoven 
* Do you have DataStore enabled on your API (`amplify update api` > `GraphQL` > `Enable DataStore...`)?
* Have you tried deleting and re-installing your app in Simulator (or on your physical device)
* Could you please share the rest of your app code with us? 
 
When using `DataStore.query`, DataStore will call `DataStore.start` internally the first time you interact with it, so I don't think the problem lies in calling `start` explicitly.

**Comment by CarlJoven** [comment]
Hmmm, that's weird. My react native app project is just the initial template given by react-native CLI using the typescript template and I am just trying to integrate the datastore API.  For the first question, the project Graphql API has Datastore enabled.

**Comment by CarlJoven** [comment]
For additional info. I already have Amplify backend set up with the web app that we develop and for the mobile I am just pulling the models without the amplify folder.

**Comment by patrickspafford** [comment]
@CarlJoven How did you resolve this?
