### ISSUE TITLE
Bypass the Hosted UI for use SAML federated sign in.

### ISSUE THREAD

**Issue by arslanali16** [aws-amplify/amplify-js#8377]
### Is this related to a new or existing framework?

Angular

### Is this related to a new or existing API?

Authentication

### Is this related to another service?

Cognito

### Describe the feature you'd like to request

Hello, 
I am implementing SAML (Okta) based federated sign-in login in my angular amplify application. I have implemented the flow(sign in flow) like following:

Hosted UI URL >> Okta Login Page >> Authenticated Id and access token >> After i get the id and access token i have defined custom logic to signin and redirect the user to whichever page you want.

I have implemented same above flow using "Auth.federatedSignIn()" and using "Hub" listeners.
 
Now i want to bypass the Hosted UI as our customer requirement so is there any way to bypass the hosted UI?

### Describe the solution you'd like

I would like to give my solution but honestly i am not sure that it will work.
My question is can we bypass the Hosted UI using headless chrome lambda?

### Describe alternatives you've considered

 using headless chrome lambda can we bypass that?

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cbschuld** [comment]
@arslanali16 I am curious if your solution is still working?  I would also like to bypass the hosted UI (_similar to what you can do with Facebook or Google_) via:

```typescript
Auth.federatedSignIn({ provider: CognitoHostedUIIdentityProvider.Google })
```

**Comment by w0otness** [comment]
`Auth.federatedSignIn({ customProvider: 'AzureAD' })`
where
AzureAD = name of your own provider
![image](https://user-images.githubusercontent.com/1296032/204709454-288a7c68-99c4-407e-8417-721ee51fdbec.png)

**Comment by tannerabread** [comment]
Hi @arslanali16, @cbschuld have you tried what @w0otness suggested? I have set this up before the same way, e.g. `Auth.federatedSignIn({ customProvider: 'Azure' })`

**Comment by tannerabread** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and are in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

I will also say that for this issue, there is currently not a fully supported way to handle _adding_ the custom provider through Amplify CLI and one should exercise caution if manually setting up the resources as an `amplify push` to any auth resources from the CLI will override the custom resource. There is a potential to handle this with the CDK and overrides through the CLI, but currently that is [also blocked](https://github.com/aws-amplify/amplify-cli/issues/12079).

Thank you!
