### ISSUE TITLE
ReferenceError: Can't find variable: global

### ISSUE THREAD

**Issue by martinmalia** [aws-amplify/amplify-js#8382]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 11.4
    CPU: (8) arm64 Apple M1
    Memory: 571.64 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.2.0 - /opt/homebrew/bin/node
    npm: 7.13.0 - /opt/homebrew/bin/npm
  Browsers:
    Safari: 14.1.1
  npmPackages:
    @types/react: ^17.0.0 => 17.0.9 
    @types/react-dom: ^17.0.0 => 17.0.6 
    @vitejs/plugin-react-refresh: ^1.3.1 => 1.3.3 
    aws-amplify: ^4.0.4-unstable.4 => 4.0.4-unstable.6+ea97dda28 
    react: ^17.0.0 => 17.0.2 (17.0.1)
    react-dom: ^17.0.0 => 17.0.2 
    typescript: ^4.1.2 => 4.3.2 
    vite: ^2.3.5 => 2.3.6 
  npmGlobalPackages:
    @aws-amplify/cli: 4.52.0
    npm: 7.13.0


```

</details>

### Describe the bug

When building a TS React project using Vite (https://vitejs.dev), the browser content goes blank and the console displays "ReferenceError: Can't find variable: global" as soon as I add the following to main.tsx
import Amplify from "aws-amplify";
import awsExports from "./aws-exports";
Amplify.configure(awsExports);

### Expected behavior

I would expect it run just fine. 

### Reproduction steps

1. Scaffold app with npm init @vitejs/app
2. select react and then typescript
3. run amplify init
4. npm install aws-amplify or npm install aws-amplify@unstable
5. add the amplify client config to main.tsx (import Amplify from "aws-amplify";
import awsExports from "./aws-exports";
Amplify.configure(awsExports);)
6. npm run dev

### Code Snippet

```javascript
// Put your code below this line.
no code needed
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by iartemiev** [comment]
This seems to be related to Vite not including various node built-ins. There are some workarounds mentioned in this issue: https://github.com/vitejs/vite/issues/728 in the Vite repo

**Comment by wlee221** [comment]
Closing as duplicate for #7499. @ErikCH has a workaround for `global` here: https://github.com/aws-amplify/amplify-js/issues/7499#issuecomment-804386820 (and more down the thread).

**Comment by ianpogi5** [comment]
@martinmalia were you able to make this work?
