### ISSUE TITLE
How to update _deleted field to false?

### ISSUE THREAD

**Issue by zzBrunoBrito** [aws-amplify/amplify-js#8410]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
Graphql, appsync

**Amplify CLI Version** 
4.32.1

**What AWS Services are you utilizing?**
Amplify, appsync, dynamoDB

**Provide additional details e.g. code snippets**
I'd like to update the _deleted field of a record to false, how can I do that? Tried to set _deleted = false on the update mutation but not success. Is possible to update the _deleted field of a record using amplify?

**Comment by chrisbonifacio** [comment]
If you don't mind, could you please share your schema and how you're trying to update the field in your code?

Not sure if this helps, but a mutation done through Amplify's API would look like this

```js
API.graphql(
        graphqlOperation(updateRecord, {
          input: {
            id: recordID,
            _deleted: false,
          },
        })
      );
```

**Comment by chrisbonifacio** [comment]
@zzBrunoBrito Hey 👋 , going to close this as we haven't heard back from you in a week. Please let me know if my example above helped or feel free to re-open if you need additional help. Thanks!

**Comment by mrsimply** [comment]
> If you don't mind, could you please share your schema and how you're trying to update the field in your code?
> 
> Not sure if this helps, but a mutation done through Amplify's API would look like this
> 
> ```js
> API.graphql(
>         graphqlOperation(updateRecord, {
>           input: {
>             id: recordID,
>             _deleted: false,
>           },
>         })
>       );
> ```

@chrisbonifacio This is not supported! Result is:

`"Validation error of type WrongType: argument 'input' with value 'ObjectValue{objectFields=[ObjectField{name='id', value=StringValue{value='6e86d8d7-7d3e-4380-9c78-30a2319b2426'}}, ObjectField{name='_deleted', value=BooleanValue{value=false}}]}' contains a field not in 'UpdateCustomerInput': '_deleted' @ 'updateCustomer'"`
