### ISSUE TITLE
Deeper look into the Require Cycles for React Native

### ISSUE THREAD

**Issue by sammartinez** [aws-amplify/amplify-js#8421]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Not applicable

### Amplify Categories

auth, storage

### Environment information

Please refer to the issues listed below

### Describe the bug

We recently solved the [Async Storage community version update](https://github.com/aws-amplify/amplify-js/issues/6031) for our React Native customers. There has also been [updates for the Require Cycles issues](https://github.com/aws-amplify/amplify-js/issues/5371) but we still need to validate some of the other warning callout for our customers. 

### Expected behavior

Make sure there are no warning messages for Require Cycle callout for React Native 

### Reproduction steps

Please refer to the below issues:
* https://github.com/aws-amplify/amplify-js/issues/5371
* https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+require+cycles+is%3Aclosed

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by thomasyim02** [comment]
@sammartinez Following from the previous issue #6031 , the require cycle issue occurs immediately after installing the amplify-js library to a React Native app (in my case, is RN version 0.63.4). The three warnings are:

> > WARN  Require cycle: ../../node_modules/@aws-amplify/pubsub/lib-esm/index.js -> ../../node_modules/@aws-amplify/pubsub/lib-esm/PubSub.js -> ../../node_modules/@aws-amplify/pubsub/lib-esm/Providers/index.js -> ../../node_modules/@aws-amplify/pubsub/lib-esm/Providers/AWSAppSyncRealTimeProvider.js -> ../../node_modules/@aws-amplify/pubsub/lib-esm/index.js
> > Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
> > WARN  Require cycle: ../../node_modules/@aws-amplify/datastore/lib-esm/types.js -> ../../node_modules/@aws-amplify/datastore/lib-esm/util.js -> ../../node_modules/@aws-amplify/datastore/lib-esm/types.js
> > Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
> > WARN  Require cycle: ../../node_modules/aws-amplify/lib-esm/index.js -> ../../node_modules/aws-amplify/lib-esm/withSSRContext.js -> ../../node_modules/aws-amplify/lib-esm/index.js
> > Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

**Comment by thomasyim02** [comment]
> @sammartinez Following from the previous issue #6031 , the require cycle issue occurs immediately after installing the aws-amplify library to a React Native app (in my case, is RN version 0.63.4). The three warnings are:
> 
> > > WARN  Require cycle: ../../node_modules/@aws-amplify/pubsub/lib-esm/index.js -> ../../node_modules/@aws-amplify/pubsub/lib-esm/PubSub.js -> ../../node_modules/@aws-amplify/pubsub/lib-esm/Providers/index.js -> ../../node_modules/@aws-amplify/pubsub/lib-esm/Providers/AWSAppSyncRealTimeProvider.js -> ../../node_modules/@aws-amplify/pubsub/lib-esm/index.js
> > > Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
> > > WARN  Require cycle: ../../node_modules/@aws-amplify/datastore/lib-esm/types.js -> ../../node_modules/@aws-amplify/datastore/lib-esm/util.js -> ../../node_modules/@aws-amplify/datastore/lib-esm/types.js
> > > Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
> > > WARN  Require cycle: ../../node_modules/aws-amplify/lib-esm/index.js -> ../../node_modules/aws-amplify/lib-esm/withSSRContext.js -> ../../node_modules/aws-amplify/lib-esm/index.js
> > > Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

@sammartinez Do you need more information for this issue?

**Comment by paulinhapenedo** [comment]
I have the same warnings on a project I'm working on:

> Require cycle: node_modules/@aws-amplify/core/lib-esm/index.js -> node_modules/@aws-amplify/core/lib-esm/Providers/index.js -> node_modules/@aws-amplify/core/lib-esm/Providers/AWSCloudWatchProvider.js -> node_modules/@aws-amplify/core/lib-esm/index.js

Calling `import { Auth } from '@aws-amplify/auth'` instead of `import { Auth } from 'aws-amplify'` has helped a lot. I use to get 4 warnings, but now I only have one.


**AWS Dependencies**
**@aws-amplify/ui-components:** 1.0.2
**amazon-cognito-identity-js:** 5.1.0
**aws-amplify:** 4.2.5,
**aws-amplify-react-native:** 4.3.1

Would be happy to provide more info about it! :)

**Comment by bnb-briankim** [comment]
any update?

**Comment by ApplicationNinja** [comment]
Need this fixed please...

**Comment by jeffinhk** [comment]
no updates on this?

**Comment by jakex7** [comment]
This case is still an issue

**Comment by blwinters** [comment]
I think these warnings should be ignored by the metro default for `requireCycleIgnorePatterns`, but they are still getting through for whatever reason. https://facebook.github.io/metro/docs/configuration/#requirecycleignorepatterns

**Comment by jayant-lumino** [comment]
I'm having this error

`Require cycle: node_modules/@aws-amplify/pubsub/lib-esm/index.js -> node_modules/@aws-amplify/pubsub/lib-esm/PubSub.js -> node_modules/@aws-amplify/pubsub/lib-esm/Providers/index.js -> node_modules/@aws-amplify/pubsub/lib-esm/Providers/AWSAppSyncRealTimeProvider.js -> node_modules/@aws-amplify/pubsub/lib-esm/index.js`

**Comment by cwomack** [comment]
Would anyone following this issue be able to confirm if they see these warning persisting in a v6 Amplify app?  We haven't had reports in v6 tied to this yet, but wanted to check with this thread.  Thanks!
