### ISSUE TITLE
Decouple package for withSSRContext

### ISSUE THREAD

**Issue by holden-caulfield** [aws-amplify/amplify-js#8435]
### Is this related to a new or existing framework?

Next.js

### Describe the feature you'd like to request

Currently I'm using just a very minimal setup for aws-amplify. Basically, just @aws-amplify/core and @aws-amplify/auth 

However, since I'm working on a NextJS application, I need to use `withSSRContext` (for example to check if user is authenticated and/or retrieve its credentials on a `getServerSideProps` function)

This forced me to have to set the whole `aws-amplify` package, which has a HUGE footprint compared to what I was using.

### Describe the solution you'd like

To have withSSRContext be part of a specific subpackage. For example, making it part of `@aws-amplify/core` or create a new `@aws-amplify/ssr` subpackage that is specific to it.

### Describe alternatives you've considered

Set the whole `aws-amplify` package as dependency which has a huge footprint and is quite an overkill

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by voigtito** [comment]
Any update on this?

**Comment by ericclemmons** [comment]
Using `aws-amplify` shouldn't be a problem with tree-shaking.  We're monitoring sizes here for validation:

https://github.com/aws-amplify/amplify-js/blob/8cfbe10cccac41affbb0e16da7013e7ece588bcb/.github/actions/bundle-size-action/next/package.json#L14-L31

To your point, however, `withSSRContext` is large by default (but should only affect server build only, not client) by having batteries-included for `Auth`, `DataStore`, and `API`:

https://github.com/aws-amplify/amplify-js/blob/8cfbe10cccac41affbb0e16da7013e7ece588bcb/packages/aws-amplify/src/withSSRContext.ts#L9-L17

I believe this is the best fix – removing `defaultModules` and requiring them to be explicit:

```js
import { Amplify, Auth } from "aws-amplify"

export function getServerSideProps({ req }) {
  const ssr = withSSRContext({ modules: [Auth], req })
  ...
```

This would keep `DataStore` and `API` out of the server-side bundle.  We can also track the bundle-size before & after with an additional page as either an `/api` route, or `getServerSideProps`:
> https://github.com/aws-amplify/amplify-js/tree/main/.github/actions/bundle-size-action/next/pages

**Comment by philohelp** [comment]
Another argument in favor of OP's solution is the size of the node-modules - representing a 100-150 extra MBs. I use Amplify for Auth, Api and Storage but Vercel for hosting and I quickly hit their 500MB limit.

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (`aws-amplify@>6`), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/) for more information.
