### ISSUE TITLE
Installation of ui-react creates duplicate versions when installed alongside aws-amplify@4. No problems with aws-amplify@3

### ISSUE THREAD

**Issue by Delannor** [aws-amplify/amplify-js#8437]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Not applicable

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 49.15 GB / 63.96 GB
  Binaries:
    Node: 16.1.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.17.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.77
    Edge: Spartan (44.19041.964.0), Chromium (91.0.864.41)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @aws-amplify/ui-react: ^1.2.2 => 1.2.2
    @testing-library/jest-dom: ^5.14.1 => 5.14.1
    @testing-library/react: ^11.2.7 => 11.2.7
    @testing-library/user-event: ^12.8.3 => 12.8.3
    aws-amplify: ^4.1.0 => 4.1.0 (3.4.3)
    react: ^17.0.2 => 17.0.2 (17.0.1)
    react-dom: ^17.0.2 => 17.0.2
    react-scripts: 4.0.3 => 4.0.3
    web-vitals: ^1.1.2 => 1.1.2
  npmGlobalPackages:
    @aws-amplify/cli: 4.52.0
    npm: 7.17.0
    serve: 12.0.0

```

</details>

### Describe the bug

Installing @aws-amplify/ui-react together with aws-amplify@4 creates duplicate versions

### Expected behavior

Expected no duplicate versions after installing @aws-amplify/ui-react

### Reproduction steps

Create a fresh project on Windows (PowerShell) using npm:
>> npx create-react-app testapp

Install aws-amplify inside the project folder:
>> cd ./testapp
>> npm i aws-amplify

Check for duplicate versions (found on https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js):
>> npm ls -all 2>$null |
  Select-String -Pattern  '(@?aws\-amplify[^@]*).*(?<!deduped)$' | 
  %{$_.Matches.Groups[1].value} | Group-Object | 
  Where-Object { $_.Count -gt 1 } | Select-Object -ExpandProperty Name |
  Sort-Object

No output => no duplicates

Install @aws-amplify/ui-react

>> npm i @aws-amplify/ui-react

Check for duplicate versions again
This time the output is:
@aws-amplify/analytics
@aws-amplify/api
@aws-amplify/api-graphql
@aws-amplify/api-rest
@aws-amplify/auth
@aws-amplify/cache
@aws-amplify/core
@aws-amplify/datastore
@aws-amplify/interactions
@aws-amplify/predictions
@aws-amplify/pubsub
@aws-amplify/storage
@aws-amplify/ui
@aws-amplify/xr
aws-amplify

**Comment by wlee221** [comment]
Hi @Delannor, thanks for reporting this issue! 

I found that our peer dependency from `@aws-amplify/ui-components` isn't up to date:

https://github.com/aws-amplify/amplify-js/blob/eb3b707722084f07d025344bf6bbc34927b79bf5/packages/amplify-ui-components/package.json#L37-L39

This should point to `4.x.x`. I'll make a PR shortly. Meanwhile, you can pass [`--legacy-peer-deps`](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies) tag to bypass peer dependency installation.

**Comment by wlee221** [comment]
@Delannor, just letting you know that the fix has been merged and will be included in the next release cycle.
