### ISSUE TITLE
Amplify stuck in the provision phase

### ISSUE THREAD

**Issue by ryanbagwell** [aws-amplify/amplify-js#8444]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Not applicable

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

Deploy preview is stuck in the provision phase. Won't move on to the build phase. I've cancelled and initiated a new build twice, without success.

App ID is: dzdjg1b39mpia

### Expected behavior

I expect the provision phase to complete and being the build phase.

### Reproduction steps

n/a

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by reddypramod85** [comment]
We are also facing the same issue. Amplify struck in the provisioning phase.

![image](https://user-images.githubusercontent.com/12749370/121926580-b6c6a600-cd03-11eb-81a4-e9ab73d26500.png)

**Comment by chrisbonifacio** [comment]
Hey @ryanbagwell 👋 thanks for raising this. Sorry to hear you're experiencing this issue. In order for me to try to reproduce the issue, can you provide the details of your amplify configuration such as what Categories you might be using? (Auth, API, DataStore, etc)

@reddypramod85 if you can provide the details of your environment as well, please do.

**Comment by reddypramod85** [comment]
I don't see the issue anymore.

**Comment by ryanbagwell** [comment]
This corrected itself after a few hours for me as well.

Sent from my iPhone

On Jun 14, 2021, at 3:41 PM, Chris Bonifacio ***@***.***>
wrote:

﻿

Hey @ryanbagwell <https://github.com/ryanbagwell> 👋 thanks for raising
this. Sorry to hear you're experiencing this issue. In order for me to try
to reproduce the issue, can you provide the details of your amplify
configuration such as what Categories you might be using? (Auth, API,
DataStore, etc)

@reddypramod85 <https://github.com/reddypramod85> if you can provide the
details of your environment as well, please do.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/aws-amplify/amplify-js/issues/8444#issuecomment-860943118>,
or unsubscribe
