### ISSUE TITLE
Hub auth listener example missing 'this' keyword

### ISSUE THREAD

**Issue by jamesoflol** [aws-amplify/amplify-js#845]
Two issues:

# 1: There's an error in the Hub auth listener code example

https://aws.github.io/aws-amplify/media/hub_guide#listening-authentication-events specifies:

    class MyClass {
      ...

      onHubCapsule(capsule) {
        const { channel, payload } = capsule;
        if (channel === 'auth') { onAuthEvent(payload); }
      }

      onAuthEvent(payload) {
        ...
      }
    }

Now, my javascript/ES6 knowledge isn't great, but AFAIK calls to other child functions in a class require the `this` keyword. I.e., the call should be

    this.onAuthEvent(payload);

When I tried to implement the example as standard, I received error

    Hub - error dispatching auth event to MyListener

Adding the `this` keyword resolved the error for me.

# 2: Error handling gobbles up error contents (doesn't bubble up)

All I got was `Hub - error dispatching auth event to MyListener`. I suppose this is a point of style, but I thought conventional wisdom was to bubble up errors - at least console log the entire thing to the logger while in debug mode.

**Comment by amlcodes** [comment]
any fix?

**Comment by elorzafe** [comment]
@powerful23 will take a look into this.

**Comment by elorzafe** [comment]
@haverchuck will fix the docs.
