### ISSUE TITLE
Mutation Overwrites DataStore with incorrect NULL values 

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-js#8450]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

DataStore

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line
npx: installed 1 in 1.19s

  System:
    OS: Linux 4.14 Amazon Linux 2
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
    Memory: 6.47 GB / 7.58 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 10.23.1 - ~/.nvm/versions/node/v10.23.1/bin/node
    npm: 6.14.10 - ~/.nvm/versions/node/v10.23.1/bin/npm
  npmGlobalPackages:
    @aws-amplify/cli: 4.52.0
    cdk: 1.83.0
    coffeescript: 2.5.1
    esformatter: 0.11.3
    js-beautify: 1.13.2
    npm: 6.14.10
    prettier: 2.2.1
    typescript: 3.7.5

```

</details>

### Describe the bug

In the back end we have AWS Lambda functions that are updating data via GraphQL.

However, any subscription that is listening to the change that was made via GraphQL will get sent a null value for any field that is not explicitly declared in the mutation. This overwrites valid data in DataStore with null values.

See examples in the code snippet section below.

It is not feasible to have to declare every field in a mutation response because if I add a field to a schema I'd have to go and update every single Lambda function to include this additional field. It also corrupts nested fields/relations by nulling everything out.

### Expected behavior

In the mutation response I declare ONLY the fields that have changed and those fields are MERGED with the existing record in DataStore to update ONLY the fields that have changed.

Therefore this mutation updates the data in DataStore as shown
```
mutation updateField2 {
   updatePost(input:{
           id: "id1"
           field2: "someField02"
       }){
          field2
     }
}
```
Only field2 was mentioned in the subscription, so only field2 gets updated in DataStore.

```
{
  "id": "id1",
  "title": "someTitle",
  "field1": "someField01",
  "field2": "someFIeld02",
  "field3": null,
  "field4": null,
  "field5": null
}

```

### Reproduction steps

See code snippet and Expected Behavior sections

### Code Snippet

```javascript
<details>


schema.graphql definition of model

```
type Post @model {
  id: ID!
  title: String!
  field1: String
  field2: String
  field3: String
  field4: String
  field5: String
}
```

Data stored in record id1 in DynamoDB

```
{
  "id": "id1",
  "title": "someTitle",
  "field1": "someField01",
}

```

Data stored in record id1 in DataStore

```
{
  "id": "id1",
  "title": "someTitle",
  "field1": "someField01",
  "field2": null,
  "field3": null,
  "field4": null,
  "field5": null
}

```
GraphQL mutation to update data in DynamoDB

```
mutation updateField2 {
   updatePost(input:{
           id: "id1"
           field2: "someField02"
       }){
          id
          field2
     }
}
```
Update to Datastore that is subscribed/listening to change in record.

```
{
  "id": "id1",
  "title": null,
  "field1": null,
  "field2": "someFIeld02",
  "field3": null,
  "field4": null,
  "field5": null
}

```



</details>


```

**Comment by sacrampton** [comment]
Hi @iartemiev - just wondering if this issue is related to #8405 that you are currently working

**Comment by sacrampton** [comment]
Please see another thing we are wrestling with - before the subscription DataStore has connected/nested items (operatingUnit and plant). After the subscription the connected/nested fields are no longer visible.

![before_subscription](https://user-images.githubusercontent.com/6362888/122019419-1659aa00-ce07-11eb-8016-8aeb8ba77640.png)

![after_subscription](https://user-images.githubusercontent.com/6362888/122019412-15287d00-ce07-11eb-82b1-b406da9cb26c.png)





Before the mutation

**Comment by sacrampton** [comment]
Hi @chrisbonifacio  @iartemiev  - this problem is on my critical path and impacting release. Is anyone able to look at this issue and advise. Thanks

**Comment by sacrampton** [comment]
Hi @chrisbonifacio @iartemiev - just wondering if you (or someone) can take a look at this

**Comment by manueliglesias** [comment]
Hey @sacrampton can you DM me on twitter? (https://twitter.com/menyao) I might be able to help

**Comment by sacrampton** [comment]
Thanks for your help @manueliglesias - I want to document what we did in case anyone else runs into this issue, then I'll close this issue. The solution we implemented is not ideal, but it works.

First thing to understand is that if you want subscriptions to work you need the mutation to return every possible value in the schema so that it "broadcasts" correct/current values to all listeners. We don't want to be in a situation where if the schema changes that we have to go and modify every mutation. We have a table/model we use for pick list values - so in this table we create a list of all fields in every model so at run time we can execute a query to get all the fields we need to include in the mutation. Obviously this slows down the entire process, but like I said, it at least works.

Below we have 2 examples - one is a field on the model, and the other is a connection to another model (ie. plant). We simply need to include id & _deleted in the return from the mutation and all the connection issues described above disappear.

```
name
plant{id _deleted}
```

Whilst this gets us moving forward, it does so with a significant speed hit. If I have a model with 300+ fields and I update a single field then I need to broadcast out all 300+ fields rather than just the single field that was updated. So it would be great if AWS could look to be more efficient with subscriptions just broadcasting what changes within a record.

Thanks again for your help in resolving this @manueliglesias
