### ISSUE TITLE
Year Month is null only in USA and Canada

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/amplify-js#8452]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line
System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 2.10 GB / 12.44 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.0 - /usr/local/lib/nodejs/bin/node
    npm: 6.14.13 - /usr/local/lib/nodejs/bin/npm
  npmPackages:
    @ampproject/toolbox-optimizer:  undefined ()
    @aws-amplify/api: ^4.0.2 => 4.0.2 
    @aws-amplify/auth: ^4.0.2 => 4.0.2 
    @aws-amplify/core: ^4.1.0 => 4.1.0 
    @babel/core:  undefined ()
    @headlessui/react: ^1.2.0 => 1.2.0 
    @heroicons/react: ^1.0.1 => 1.0.1 
    @tailwindcss/forms: ^0.3.3 => 0.3.3 
    @types/node: ^15.12.2 => 15.12.2 
    @types/react: ^17.0.11 => 17.0.11 
    @types/react-select: ^4.0.15 => 4.0.15 
    @types/react-table: ^7.7.1 => 7.7.1 
    @typescript-eslint/eslint-plugin: ^4.27.0 => 4.27.0 
    @typescript-eslint/parser: ^4.27.0 => 4.27.0 
    amphtml-validator:  undefined ()
    arg:  undefined ()
    async-retry:  undefined ()
    async-sema:  undefined ()
    autoprefixer: ^10.2.6 => 10.2.6 
    bfj:  undefined ()
    cacache:  undefined ()
    ci-info:  undefined ()
    comment-json:  undefined ()
    compression:  undefined ()
    conf:  undefined ()
    content-type:  undefined ()
    cookie:  undefined ()
    css-loader:  undefined ()
    debug:  undefined ()
    devalue:  undefined ()
    escape-string-regexp:  undefined ()
    eslint: ^7.28.0 => 7.28.0 
    eslint-config-prettier: ^8.3.0 => 8.3.0 
    eslint-plugin-jsx-a11y: ^6.4.1 => 6.4.1 
    eslint-plugin-prettier: ^3.4.0 => 3.4.0 
    eslint-plugin-react: ^7.24.0 => 7.24.0 
    eslint-plugin-react-hooks: ^4.2.0 => 4.2.0 
    file-loader:  undefined ()
    find-cache-dir:  undefined ()
    find-up:  undefined ()
    fresh:  undefined ()
    gzip-size:  undefined ()
    http-proxy:  undefined ()
    ignore-loader:  undefined ()
    is-animated:  undefined ()
    is-docker:  undefined ()
    is-wsl:  undefined ()
    json5:  undefined ()
    jsonwebtoken:  undefined ()
    loader-utils:  undefined ()
    lodash.curry:  undefined ()
    lru-cache:  undefined ()
    mini-css-extract-plugin:  undefined ()
    nanoid:  undefined ()
    neo-async:  undefined ()
    next: ^10.2.3 => 10.2.3 
    ora:  undefined ()
    postcss: ^8.3.4 => 8.3.4 (8.2.13, 6.0.23)
    postcss-flexbugs-fixes:  undefined ()
    postcss-loader:  undefined ()
    postcss-preset-env:  undefined ()
    postcss-scss:  undefined ()
    prettier: ^2.3.1 => 2.3.1 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    react-hook-form: ^7.8.6 => 7.8.6 
    react-query: ^3.17.0 => 3.17.0 
    react-select: ^4.3.1 => 4.3.1 
    react-table: ^7.7.0 => 7.7.0 
    recast:  undefined ()
    resolve-url-loader:  undefined ()
    sass-loader:  undefined ()
    schema-utils:  undefined ()
    semver:  undefined ()
    send:  undefined ()
    source-map:  undefined ()
    string-hash:  undefined ()
    strip-ansi:  undefined ()
    tailwindcss: ^2.1.4 => 2.1.4 
    terser:  undefined ()
    text-table:  undefined ()
    timeago-react: ^3.0.2 => 3.0.2 
    typescript: ^4.3.2 => 4.3.2 
    unistore:  undefined ()
    use-resize-observer: ^7.0.0 => 7.0.0 
    web-vitals:  undefined ()
    webpack:  undefined ()
    webpack-sources:  undefined ()
  npmGlobalPackages:
    npm: 6.14.13

```

</details>

### Describe the bug

I use `const yearMonth = new Date().toISOString().substr(0, 7)` code in react to get current year month in user's browser. Then I pass it as variable for graphql API to give me records only for current year month. 

Now I have tested above in India, UAE, UK customers and everything from top to bottom works perfectly.

I tested on USA and Canada customers and I get error that `yearMonth` is `null` from amplify graphql api.

The exact error is as follows

`Variable 'yearMonth' has coerced Null value for NonNull type 'String!'`

### Expected behavior

Amplify graphql api should take `const yearMonth = new Date().toISOString().substr(0, 7)` this year month input and return related records only.

### Reproduction steps

I created graphql api with CDK.
Also graphql api is protected with congito auth also created with CDK.
The data is stored in dynamodb also created with CDK.
The react app is stored in S3 and delivered via Cloudfront. Both created with CDK.
The error generating code is as following
```ts
const yearMonth = new Date().toISOString().substr(0, 7)

  const router = useRouter()

  return useQuery<Budget[] | undefined, MyError | string, Budget[] | undefined>(
    ["budget", yearMonth],
    () =>
      Auth.currentAuthenticatedUser()
        .then(() => {
          return API.graphql({
            query: latestBudgetByOwnerID,
            authMode: GRAPHQL_AUTH_MODE.AMAZON_COGNITO_USER_POOLS,
            variables: { yearMonth },
          }) as GraphQLResult<GetLatestBudgetByOwnerID>
        }))
  )
```
The exact error is as follows

`Variable 'yearMonth' has coerced Null value for NonNull type 'String!'`

Let me reiterate the above code works in India, UK, UAE. Does not work in USA and Canada.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hey @apoorvmote 👋 could you share an example of what `yearMonth` looks like before being sent as a variable to the graphQL mutation?

I'm in the US (East Coast) and running that code returns this string: `2021-07`

**Comment by apoorvmote** [comment]
Thanks for getting back to me on this. 

Yes I am also now suspecting the issue :bug: is previous step not the graphql request. See `yearMonth` is required value and my guess is that in the previous step when it was saved it got saved as `null` value and graphql error is saying `null` value found where it is required value. 

See I live in India :india: and I am not able to reproduce the error here. That means if the bug :bug: is in previous step then it should not work in India :india: as well. But everything works perfectly in India :india:. Now my beta testers in USA :us: & Canada 🍁  were upset with bad first impression and I haven't been able to get them to try again or get them to help me debug.

Please visit grwab.com from either USA :us: or Canada :canada: and create account with disposible email and go through initial wizard :mage: and after completion you will find the same error.

**Comment by chrisbonifacio** [comment]
@apoorvmote Hey, so I did sign up for the website you linked and I can see the graphql error you mentioned. However, using my VPN and switching back to a server in India doesn't seem to change anything. I would definitely compare the ISO strings that are being passed to your `yearMonth` variable between a customer in India and a customer in the US & Canada to see if there are any noticeable differences between them such as the formatting.

Here's the data that I can see being returned from graphql when I login, I do see there's an `endYearMonth` field but no `yearMonth` field.

<img width="1092" alt="Screen Shot 2021-07-28 at 1 51 32 PM" src="https://user-images.githubusercontent.com/16952986/127372002-06a6c603-4176-4fd3-87c4-9ee14a195271.png">

**Comment by chrisbonifacio** [comment]
Also, it looks like there are similar queries that use the same `yearMonth` variable and they seem to work just fine (in the US). It's only when I get to the end of the sign up process that the query doesn't work.

Request

<img width="1291" alt="Screen Shot 2021-07-28 at 1 58 53 PM" src="https://user-images.githubusercontent.com/16952986/127372825-df44268c-c9a5-416b-8550-4bd5f0247b24.png">

Response

<img width="443" alt="Screen Shot 2021-07-28 at 2 00 10 PM" src="https://user-images.githubusercontent.com/16952986/127372976-4a404f62-eec1-42de-a83f-f7f4d5e038b8.png">

**Comment by chrisbonifacio** [comment]
Looking further into the network calls, the issue seems to happen wherever the `getBudgetForYearMonth` query is being called. It happens multiple times, succeeds the first time and fails on the subsequent calls.

First `getBudgetForYearMonth` Query (you can see yearMonth is present in the query variables)

<img width="1283" alt="Screen Shot 2021-07-28 at 2 04 20 PM" src="https://user-images.githubusercontent.com/16952986/127373488-1272d2cf-1632-4c76-92a0-3f8728884808.png">

Response

<img width="1102" alt="Screen Shot 2021-07-28 at 2 04 52 PM" src="https://user-images.githubusercontent.com/16952986/127373566-331b7d41-1c1b-42bb-8866-9f3125ea86ed.png">

After this the same query seems to be called about four times but are now missing the `yearMonth` query variable

<img width="1285" alt="Screen Shot 2021-07-28 at 2 07 29 PM" src="https://user-images.githubusercontent.com/16952986/127373873-70631f1b-393a-400a-a249-be4754eca847.png">

**Comment by apoorvmote** [comment]
@chrisbonifacio Thanks for going above and beyond to solve this issue. 

You have clearly exonerated amplify-js from being cause of this issue. So feel free to close this issue. I will have to get remote access to someone in USA and debug the problem. VPN is not going to help recreate the issue. Its the Chrome or other browsers in USA are the problem. I will post my solution here if this thread is still active by that time.

BTW I have tested with friends in France and Australia (NOT Austria). It works properly. Also using regularly in India. It works here as well.

**Comment by apoorvmote** [comment]
Windows Server 2019 on AWS EC2 seems good place to debug the issue. Just found out about this.

**Comment by chrisbonifacio** [comment]
I am curious what the solution will be, so do post it here if you can! I imagine there might be some conditional logic that determines whether `yearMonth` is passed as a query since it's missing from the last few queries altogether rather than being passed in with a value of `null`.

**Comment by apoorvmote** [comment]
Thanks but that doesn't explain why it does not work in USA and Canada but works in rest of the world.

**Comment by apoorvmote** [comment]
@chrisbonifacio 
I knew it something is wrong with USA and Canada chrome or just browsers.

This is how code works in rest of the world.
![date](https://user-images.githubusercontent.com/9799239/127732797-8fbb649e-d149-43cc-95ff-49ccb531c6c0.jpg)

But only in USA this happens 
![Screen Shot 2021-07-31 at 3 42 03 AM](https://user-images.githubusercontent.com/9799239/127732865-f0be93ff-e800-4fc4-b562-2712eb15080a.png)

I wasted months of my time fixing something that wasn't my fault.
