### ISSUE TITLE
Response when Success Auth.forgotPasswordSubmit

### ISSUE THREAD

**Issue by LuisValgoi** [aws-amplify/amplify-js#8453]
### Is this related to a new or existing framework?

React

### Is this related to a new or existing API?

Authentication

### Is this related to another service?

Amazon Cognito

### Describe the feature you'd like to request

To receive the response on the success callback of the `Auth.forgotPasswordSubmit`

### Describe the solution you'd like

To receive the response on the success callback of the `Auth.forgotPasswordSubmit`

### Describe alternatives you've considered

n/a

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by nadetastic** [comment]
Hi @LuisValgoi 

Closing this issue out, as this feature was added with PR https://github.com/aws-amplify/amplify-js/pull/8744
