### ISSUE TITLE
Datastore does not save on Next JS API Route

### ISSUE THREAD

**Issue by theAndrewCline** [aws-amplify/amplify-js#8454]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

DataStore

### Amplify Categories

auth

### Environment information

<details>

```
 System:
    OS: macOS 11.2.3
    CPU: (8) x64 Apple M1
    Memory: 27.85 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.9 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.101
    Firefox: 89.0
    Firefox Developer Edition: 90.0
    Safari: 14.0.3
  npmPackages:
    @ampproject/toolbox-optimizer:  undefined ()
    @aws-amplify/ui-react: ^1.0.3 => 1.2.0
    @babel/core:  undefined ()
    @cypress/code-coverage: ^3.9.2 => 3.9.5
    @date-io/luxon: 1.x => 1.3.13
    @datepicker-react/hooks: ^2.8.0 => 2.8.0
    @iconscout/react-unicons: ^1.1.6 => 1.1.6
    @iconscout/unicons: ^3.0.6 => 3.0.6
    @istanbuljs/nyc-config-typescript: ^1.0.1 => 1.0.1
    @material-ui/core: ^4.11.3 => 4.11.4
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.58
    @material-ui/pickers: ^3.3.10 => 3.3.10
    @react-native-async-storage/async-storage: ^1.13.0 => 1.15.4
    @svgr/cli: ^5.5.0 => 5.5.0
    @testing-library/cypress: ^7.0.3 => 7.0.6
    @testing-library/jest-dom: ^5.11.9 => 5.12.0
    @testing-library/react: ^11.2.3 => 11.2.7
    @types/cors: ^2.8.10 => 2.8.10
    @types/graphql: ^14.5.0 => 14.5.0
    @types/jest: ^26.0.20 => 26.0.23
    @types/luxon: ^1.25.1 => 1.26.5
    @types/node: ^14.14.25 => 14.17.0 (15.3.1, 12.12.50)
    @types/react: ^17.0.4 => 17.0.6 (16.14.6)
    @types/react-beautiful-dnd: ^13.0.0 => 13.0.0
    @types/react-csv: ^1.1.1 => 1.1.1
    @types/react-dom: ^16.9.4 => 16.9.13 (17.0.5)
    @types/react-hooks-helper: ^1.6.3 => 1.6.3
    @types/react-select: ^4.0.14 => 4.0.15
    @types/styled-components: ^5.1.9 => 5.1.9
    @types/uuid: ^8.3.0 => 8.3.0
    amphtml-validator:  undefined ()
    arg:  undefined ()
    async-retry:  undefined ()
    async-sema:  undefined ()
    autoprefixer: ^10.2.1 => 10.2.5
    aws-amplify: ^4.0.1 => 4.0.2
    aws-amplify-react: ^4.2.31 => 4.2.35
    babel-plugin-istanbul: ^6.0.0 => 6.0.0
    babel-plugin-macros: ^3.0.1 => 3.1.0 (2.8.0)
    babel-plugin-styled-components: ^1.12.0 => 1.12.0
    bfj:  undefined ()
    cacache:  undefined ()
    cache-loader:  undefined ()
    ci-info:  undefined ()
    comment-json:  undefined ()
    compression:  undefined ()
    conf:  undefined ()
    content-type:  undefined ()
    cookie:  undefined ()
    cors: ^2.8.5 => 2.8.5
    css-loader:  undefined ()
    ctix: ^0.3.1 => 0.3.1
    cypress: ^6.2.1 => 6.9.1
    debug:  undefined ()
    devalue:  undefined ()
    dotenv: ^8.2.0 => 8.6.0
    escape-string-regexp:  undefined ()
    file-loader:  undefined ()
    find-cache-dir:  undefined ()
    find-up:  undefined ()
    formik: ^2.2.6 => 2.2.7
    framer-motion: ^4.1.17 => 4.1.17
    fresh:  undefined ()
    graphql-tag: ^2.11.0 => 2.12.4
    gzip-size:  undefined ()
    http-proxy:  undefined ()
    ignore-loader:  undefined ()
    immer: ^8.0.1 => 8.0.4 (8.0.1)
    immutable: ^4.0.0-rc.12 => 4.0.0-rc.12
    is-animated:  undefined ()
    is-docker:  undefined ()
    is-wsl:  undefined ()
    jest: ^26.6.3 => 26.6.3
    json5:  undefined ()
    jsonwebtoken:  undefined ()
    libphonenumber-js: ^1.9.11 => 1.9.17
    libphonenumber-js-core:  1.0.0
    libphonenumber-js-max:  1.0.0
    libphonenumber-js-min:  1.0.0
    libphonenumber-js-mobile:  1.0.0
    loader-utils:  undefined ()
    lodash.curry:  undefined ()
    lru-cache:  undefined ()
    luxon: ^1.26.0 => 1.27.0
    nanoid:  undefined ()
    neo-async:  undefined ()
    next: 10.2.0 => 10.2.0
    nyc: ^15.1.0 => 15.1.0
    ora:  undefined ()
    postcss: ^8.2.8 => 8.2.15 (8.2.13, 6.0.23)
    postcss-flexbugs-fixes:  undefined ()
    postcss-loader:  undefined ()
    postcss-preset-env:  undefined ()
    postcss-scss:  undefined ()
    react: ^16.12.0 => 16.14.0
    react-beautiful-dnd: ^13.1.0 => 13.1.0
    react-csv: ^2.0.3 => 2.0.3
    react-dom: ^16.12.0 => 16.14.0
    react-feather: ^2.0.9 => 2.0.9
    react-hooks-helper: ^1.6.0 => 1.6.0
    react-is: ^17.0.2 => 17.0.2 (16.13.1)
    react-multistep: ^5.1.0 => 5.1.0
    react-scrollspy: ^3.4.3 => 3.4.3
    react-select: ^4.3.0 => 4.3.1
    recast:  undefined ()
    recoil: ^0.1.2 => 0.1.3
    recoil-persist: ^2.3.0 => 2.5.0
    recoil-undo: ^0.0.7 => 0.0.7
    resolve-url-loader:  undefined ()
    sass-loader:  undefined ()
    schema-utils:  undefined ()
    semver:  undefined ()
    send:  undefined ()
    source-map:  undefined ()
    source-map-support: ^0.5.19 => 0.5.19
    start-server-and-test: ^1.11.7 => 1.12.2
    string-hash:  undefined ()
    strip-ansi:  undefined ()
    styled-components: ^5.2.3 => 5.3.0
    styled-components/macro:  undefined ()
    styled-components/native:  undefined ()
    styled-components/primitives:  undefined ()
    swr: ^0.4.2 => 0.4.2
    tailwindcss: ^2.1.2 => 2.1.2
    terser:  undefined ()
    text-table:  undefined ()
    thread-loader:  undefined ()
    ts-node: ^9.1.1 => 9.1.1
    twin.macro: ^2.4.1 => 2.4.1
    typescript: 4.0 => 4.0.7
    unistore:  undefined ()
    use-immer: ^0.4.2 => 0.4.2
    uuid: ^8.3.2 => 8.3.2 (3.4.0, 3.3.2)
    web-vitals:  undefined ()
    webpack:  undefined ()
    webpack-sources:  undefined ()
    window-mock: ^0.1.0 => 0.1.0
    yarn-run-all: ^3.1.1 => 3.1.1
    yup: ^0.32.8 => 0.32.9

```

</details>

### Describe the bug

When using a NextJS API route. DataStore does not save data because the user is not authenticated there is a warning that looks like this.

```
ARN] 46:16.232 DataStore - User is unauthorized to query syncReviews with auth mode AMAZON_COGNITO_USER_POOLS. No data could be returned.
``` 

However, I am able to run Auth.currentAuthenticatedUser() and get a result.

### Expected behavior

DataStore should be able to save data to an auth-protected model in a NextJS API route.

### Reproduction steps

1. setup nextjs and amplify
2. try to save a model in an API route.

### Code Snippet

```typescript
async function handler(req: NextApiRequest, res: NextApiResponse) {
    const review = new Review({ ...req.body.review })

    const { DataStore } = withSSRContext({ req })

    const result = await DataStore.save(review)

   res.json({ result })

)


```

### Log output

<details>

```
ARN] 46:16.232 DataStore - User is unauthorized to query syncReviews with auth mode AMAZON_COGNITO_USER_POOLS. No data could be returned. 
```

</details>

### Mobile Device

Iphone8

### Mobile Operating System

iOS8.1

### Mobile Browser

Safari

### Mobile Browser Version

22

**Comment by theAndrewCline** [comment]
Here is an example.

some of my models also have { allow: public, provider: IAM }

```gql
type Review
  @model
  @auth(rules: [{ allow: private }])
  @key(name: "byAuthor", fields: ["author_id"])
  @key(name: "byMeal", fields: ["meal_id"]) {
  id: ID!
  content: [String]
  additional_content: String
  author_id: ID
  meal_id: ID
  author: Student @connection(fields: ["author_id"])
  meal: Meal @connection(fields: ["meal_id"])
  rating: Rating
}
```

**Comment by chrisbonifacio** [comment]
Thank you! Could also you share the code that is trying to call the api route?

**Comment by theAndrewCline** [comment]
Just a fetch
```
fetch('/review/create', { method: 'POST', credentidials: 'include', body: new_review })
```

**Comment by chrisbonifacio** [comment]
Looks like this is more of an authentication configuration issue. Could you try going through the docs here and turn on Multi Auth for DataStore?

https://docs.amplify.aws/lib/datastore/setup-auth-rules/q/platform/js#configure-multiple-authorization-types

```js
import Amplify, { AuthModeStrategyType } from 'aws-amplify';
import awsconfig from './aws-exports'; 

Amplify.configure({
  ...awsconfig,
  DataStore: {
    authModeStrategyType: AuthModeStrategyType.MULTI_AUTH
  }
})
```

**Comment by chrisbonifacio** [comment]
Btw, you have a typo in your fetch for `credentials`

**Comment by theAndrewCline** [comment]
We are not using the API key because the Amplify Admin doesn't work using the API Key and Cognito User Pools, so for any public requests, we are using the IAM unauthenticated user. 

Do you think we still need the AuthModeStrategyType to be Multi_AUTH? 

Also I just wrote that code real fast. It's not copied and pasted from what I was using. 😆

**Comment by chrisbonifacio** [comment]
Ahh, gotcha! If you are trying to use any auth type other than your default one in DataStore, you will have to enable MULTI_AUTH. Otherwise, DataStore will ignore the auth rules and use your default auth type. That docs link will do a much better job at explaining it than I can but it seems like that might be the issue here.

**Comment by chrisbonifacio** [comment]
could you check what your default auth type is in your aws-exports file and paste it here? I'm assuming it's IAM but just want to be sure.

**Comment by chrisbonifacio** [comment]
Also, just in case, if you're still trying to use IAM as the auth provider for your `private` rules, you'd just need to adjust the rules to be `{allow: private provider: iam}`. So, if you're only using IAM then you don't need to be enable MULTI_AUTH. It's only necessary if you want to use more than 1 auth provider in your schema.

**Comment by theAndrewCline** [comment]
```
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "<graphql-endpoint>",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "<cognito-id>",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "",
    "aws_user_pools_web_client_id": "",
    "oauth": {
        "domain": "collegefresh1fcce227-1fcce227-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
```

**Comment by theAndrewCline** [comment]
So since we are using both, we should have multi-auth enabled. Why do we only have issues on a NextJS API route though. It works fine on the client-side.

**Comment by chrisbonifacio** [comment]
Hmm, okay it makes sense that it's working client side if your default auth type is Cognito. So your auth rule is set correctly. I was able to reproduce the issue but I also tried to call `Auth.currentAuthenticatedUser` from my api route and that returns `The user is not authenticated.` So, I would try that and see if you get the same message. That might explain why we're getting that error from DataStore.

**Comment by chrisbonifacio** [comment]
I haven't been able to figure out how to invoke `DataStore.save` with credentials from the context of an API route, but doing it from within my React component seems to work just fine. Is there a reason why you want to do it from the api route rather than the component?

Interestingly, I tried to save a record to my DDB Table using API.graphql from within an API route and that also works.

My api route

```js
import { withSSRContext } from "aws-amplify";
import { createPrivateNote } from "../../src/graphql/mutations";
import { PrivateNote } from "../../src/models";

export default async function handler(req, res) {
  const data = JSON.parse(req.body);

  const { Auth, API, DataStore } = withSSRContext({ req });

  const user = await Auth.currentAuthenticatedUser();

  // const result = await DataStore.save(new PrivateNote(data));
  /*
  [WARN] 29:28.207 DataStore - User is unauthorized to query syncTasks with auth mode AMAZON_COGNITO_USER_POOLS. No data could be returned.
  */

  const result = await API.graphql({
    query: createPrivateNote,
    variables: {
      input: data,
    },
  });
  /* 
  {
    content: "user input from client"
    id: "071fc0b0-ca1a-4beb-86a0-46edcd62306e"
  }
   */

  console.log(user);
  console.log(result);

  res.json(result);
}
```

**Comment by chrisbonifacio** [comment]
This might be gaps in my knowledge on using DataStore in an SSR context but I labeled this as a bug for the team to look into further since I was able to reproduce the issue consistently.

**Comment by theAndrewCline** [comment]
@chrisbonifacio actually, ideally I would like to invoke this DataStore call from another origin. Trying to give an API option to import data into my app. I'm trying to import a large amount of data so calling datastore on the client-side isn't performant enough. 

If we don't figure this out quickly I will likely migrate to using the Graphql API rather than Datastore. 

Thanks for your help.

**Comment by undefobj** [comment]
> @chrisbonifacio actually, ideally I would like to invoke this DataStore call from another origin. Trying to give an API option to import data into my app. I'm trying to import a large amount of data so calling datastore on the client-side isn't performant enough. 
> 
> If we don't figure this out quickly I will likely migrate to using the Graphql API rather than Datastore. 
> 
> Thanks for your help.

Why not just make a direct GraphQL mutation to the AppSync API for your import use cases? That's the recommended pattern for non-client app flows.

**Comment by theAndrewCline** [comment]
@undefobj We will migrate to that. I would be nice to have this worked out so we can use the same API across the board.

**Comment by undefobj** [comment]
@theAndrewCline Just to clarify, you can still use DataStore on your client apps and use GraphQL mutations from the AWS Console or a backend system such as Lambda. The information on that is here: https://docs.amplify.aws/lib/datastore/how-it-works/q/platform/js#writing-data-from-the-appsync-console

**Comment by theAndrewCline** [comment]
Thanks!

@undefobj I am also noticing this issue in getServerSideProps as well.

**Comment by theAndrewCline** [comment]
@undefobj Hey, just wanted to follow up on this. Is there any way we can assist or provide more information?

**Comment by undefobj** [comment]
> @undefobj Hey, just wanted to follow up on this. Is there any way we can assist or provide more information? 

Sorry I'm unsure what extra information you're looking for? The above link I provided shows how you can use a GraphQL API call on the backend for data ingestion use cases by providing the proper fields in your selection set. Your client apps can still use DataStore and will get updates as appropriate.
