### ISSUE TITLE
Missing Authentication token

### ISSUE THREAD

**Issue by MedNabilEssefaihi** [aws-amplify/amplify-js#8457]
Dear Support Team, 

I am using AWS Amplify with **Cognito** and **DynamoDB** by **GraphQL API** to connect with my app
In my case I am trying to get data from **DynamoDB** by **Graphql API** the request works very well in some devices but in some other devices it doesn't work and returns the error: `Missing Authentication token.`

Also Auth.currentUserInfo(); doesn't work.

**Comment by svidgen** [comment]
Hey @MedNabilEssefaihi,

We'll need a little more information to help you. Can you give us the devices/environments you're having issues with, what your `package.json` looks like, and what the problematic code looks like.

Thanks!

**Comment by MedNabilEssefaihi** [comment]
Dear @svidgen ,
Thank you so much for your answer. 
### Some information about the project
I am building react app with **Cognito** for auth and unauth user, DynamoDB with GraphQL

### the step that I did
I gave permission to **auth** and **unauth** user to use **getUser** request by GraphQL.
 Note: it works vey well in my devices like (PC widnow 10, smartphone android 9.1) it works very well in smartphone in browser
but in some other devices like asus, window 10, pro it doesn't work

### my code
![255](https://user-images.githubusercontent.com/74948380/124310943-d879b700-db64-11eb-8c1a-be508dc39007.png)

### Error I got
![209187467_247443596789390_7859047681257598933_n](https://user-images.githubusercontent.com/74948380/124311221-4de58780-db65-11eb-86b5-03976a3e7500.jpg)


### My package.json
```
{
  "name": "myApp",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    ...
    "@aws-amplify/ui-react": "^1.0.7",
    "aws-amplify": "^3.4.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^4.0.3",
     ....
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

**Comment by chrisbonifacio** [comment]
Hi @MedNabilEssefaihi 👋 I apologize for the delay. Are you still experiencing this issue and in need of assistance?

Because you're using IAM as the auth mode, I would check to make sure that you have enabled unauthenticated identities on your auth resource.

You can check by taking a look in your `amplify/backend/auth/<userPoolName>/build/parameters.json` file and look for this line

`"allowUnauthenticatedIdentities": true`

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
