### ISSUE TITLE
Please add LINE sign in

### ISSUE THREAD

**Issue by Wivil** [aws-amplify/amplify-js#8461]
### Is this related to a new or existing framework?

React Native

### Describe the feature you'd like to request

 I want to have a function which enable us to easily allow user to sign in with LINE account

### Describe the solution you'd like

include default setting in Amplify Auth.

### Describe alternatives you've considered

include amplify auth console

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by stocaaro** [comment]
Could be related to #3347

**Comment by nadetastic** [comment]
I'll close out this issue in order to consolidate it with #3347 which is an ask to provide support for additional providers by default.
