### ISSUE TITLE
Ability to actually get object (not just URL) with Storage#get.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [aws-amplify/amplify-js#847]
Do you want to request a feature or report a bug?

Feature

What is the current behavior?

`Storage.get` returns a URL to reach the object.

What is the desired behavior?

Have an option to actually get the object, similar to the `aws-sdk` `S3#getObject` method. Otherwise, if I want to actually download the object for some reason, I'm making two AJAX calls, which seems a bit silly when it can be accomplished with one through the original SDK.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

Working on 0.4.0.

**Comment by AndrewSouthpaw** [comment]
Ping? This seems relatively simple to implement?

Unless I'm misunderstanding usage?... just seems excessive to make two calls for every object access.

**Comment by PaulPCIO** [comment]
seems like this just went stale, no response yet? @AndrewSouthpaw i agree, it's redundant having to make two calls to achieve one simple task.

**Comment by PaulPCIO** [comment]
Okey with a little further dive into the actual get function i see that there is a [download option](https://github.com/aws-amplify/amplify-js/blob/50f697bc4075ea719b692fba8426006766300d69/packages/storage/src/Providers/AWSS3Provider.ts#L117-L144)

so you can just do:
```javascript
Storage.get(`filename.pdf`, { download: true }).then(result =>  console.log(result))
```

**Comment by AndrewSouthpaw** [comment]
Good to know, thanks!

**Comment by donnrri** [comment]
Can you update the documentation please. I really like some this project but at nearly every turn of implementing it I have problems , I am not so experienced and poor documentation really hinders developers like me progress. Please update the documentation.

**Comment by sw-yx** [comment]
i hear you and i agree. made a start on the docs, please have a look at https://github.com/aws-amplify/docs/pull/2416 and let me know what else you want to add.

**Comment by ericclemmons** [comment]
Closing, thanks to https://github.com/aws-amplify/docs/pull/2416.

I agree that, were we to create `Storage.get` again, we'd want to validate existence before returning successfully.

Unfortunately, we can't do so in a backwards-compatible manner.  What's really needed is a way to _link_ to an object (with validation) and _get_ an object.

If & when `Storage` gets a major upgrade, this is behavior we'll consider.

**Comment by mikeRChambers610** [comment]
Why would anyone want to use an async await method to call a filename from an S3 bucket and then try to display it on the screen??

Why can you get the URL directly from the Storage.put method so oyu can store the actual URL in dynamodb and call the link directly in your <Image/> Component??
