### ISSUE TITLE
[REACT-NATIVE DATASTORE] Error storing data Error: database or disk is full

### ISSUE THREAD

**Issue by prakashmathpal** [aws-amplify/amplify-js#8471]
### Before opening, please confirm:

- [x] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

DataStore

### Amplify Categories

storage

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

Hi, I'm using datastore to sync my DB . and my database record size is more than 50k. I'm facing the same problem ' **Error storing data Error: database or disk is full** ' i am using this in MainApplication.java class
**long size = 50L * 1024L * 1024L; // 50 MB
com.facebook.react.modules.storage.ReactDatabaseSupplier.getInstance(getApplicationContext()).setMaximumSize(size);**
but getting error when create a new record and sync data from database.

### Expected behavior

![Screenshot 2021-06-18 at 5 16 59 PM](https://user-images.githubusercontent.com/5989879/122556433-1d77f680-d059-11eb-997d-4e1b0ab8acc6.png)

### Reproduction steps

![Screenshot 2021-06-18 at 5 16 59 PM](https://user-images.githubusercontent.com/5989879/122556548-47311d80-d059-11eb-87b5-aa02450d6c1b.png)

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by iartemiev** [comment]
You can increase the size limit of Async Storage on Android: https://react-native-async-storage.github.io/async-storage/docs/advanced/db_size

**Comment by prakashmathpal** [comment]
@iartemiev  i am increase size limit of Async Storage but getting same error **Database or Disk is full**.

**Comment by prakashmathpal** [comment]
@iartemiev <https://github.com/iartemiev> i have increase size limit of
Async Storage but getting same error Database or Disk is full.

>

**Comment by prakashmathpal** [comment]
@iartemiev  i have increase size limit of Async Storage but getting same error Database or Disk is full.
