### ISSUE TITLE
Datastore.start does not start syncing data the first time we install the application

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-js#8475]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

DataStore

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line
# Put output below this line
npx: installed 1 in 1.188s

  System:
    OS: Linux 4.14 Amazon Linux 2
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
    Memory: 6.35 GB / 7.58 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 10.23.1 - ~/.nvm/versions/node/v10.23.1/bin/node
    npm: 6.14.10 - ~/.nvm/versions/node/v10.23.1/bin/npm
  npmGlobalPackages:
    @aws-amplify/cli: 4.52.0
    cdk: 1.83.0
    coffeescript: 2.5.1
    esformatter: 0.11.3
    js-beautify: 1.13.2
    npm: 6.14.10
    prettier: 2.2.1
    typescript: 3.7.5

```

</details>

### Describe the bug

We can see from the logs that Datastore.start does not not start syncing data for the first time we install the application on the mobile.

If we kill the app and launch it again it starts syncing and then working fine after that every time.

I have created a similar issue related to creating the first time here ( https://github.com/aws-amplify/amplify-js/issues/8463 ).

We believe it is also the same problem that was listed here (https://github.com/aws-amplify/amplify-js/issues/5991), but we can't see where that was actually ever resolved.

### Expected behavior

App works the same regardless of whether its the 1st time after install.

### Reproduction steps

Install App and try sync

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by sacrampton** [comment]
Hi @chrisbonifacio - not sure if this is related to the current issue we are working (#8463 ).

**Comment by chrisbonifacio** [comment]
@sacrampton It looks like https://github.com/aws-amplify/amplify-js/issues/5991#issuecomment-639194287 was resolved from the [PR](https://github.com/aws-amplify/amplify-js/pull/6010) mentioned

**Comment by sacrampton** [comment]
Hi @chrisbonifacio - yes we have now resolved this issue. Thanks
