### ISSUE TITLE
CORS error with GraphQL API

### ISSUE THREAD

**Issue by charlesfayal** [aws-amplify/amplify-js#8482]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>
I am getting this error using the GraphQL Amplify API and I am not sure how to get around it.
```
Access to XMLHttpRequest at 'https://t...appsync-api.us-east-1.amazonaws.com/graphql' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

</details>

### Describe the bug

Cannot get past CORS

### Expected behavior

Need someway to get past

### Reproduction steps

Normal Amplify init for GraphQL API

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hey @charlesfayal :wave: Can you provide the code that's producing this error and how your api is set up like if you set up the API through the CLI or if you are using API Gateway?

**Comment by chrisbonifacio** [comment]
@charlesfayal closing this for now since we haven't heard back from you. If you're still experiencing and in need of assistance, please feel free to re-open. Thank you!
