### ISSUE TITLE
AWSAnalyticsProvider.ts add _sessionId to _recordCustomEvent() method

### ISSUE THREAD

**Issue by erikmunkby** [aws-amplify/amplify-js#849]
**Do you want to request a feature or report a bug?**

Feature

**What is the current behavior?**

Currently only _startSession() and _stopSession() includes the _sessionId.

**What is the desired behavior?**

To include _sessionId in _recordCustomEvent() events.
It would be greatly helpful when streaming events out of Pinpoint for further analytics if all events within the same session included the _sessionId. The session object of the event json received from _recordCustomEvent is even included, just empty.

**Comment by powerful23** [comment]
Closing as this feature has already been implemented.
