### ISSUE TITLE
Can't extend AmplifySignIn class for custom Sign In component anymore

### ISSUE THREAD

**Issue by blazinaj** [aws-amplify/amplify-js#8491]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication, GraphQL API

### Amplify Categories

auth, api

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

Can not extend the AmplifySignIn class to implement our custom Sign In component anymore.

Getting forced to upgrade from the old amplify packages to the new ones and this is blocking us. The documentation here https://docs.amplify.aws/lib/auth/customui/q/platform/js#customize-withauthenticator-hoc still uses `aws-amplify-react`. How do we do this with `@aws-amplify/ui-react`?

When you extend the 'AmplifySignIn' class the constructor throws an error with the super(props) method call. The original `SignIn` class is no longer available, and I would assume that `AmplifySignIn` replaces it.

![image](https://user-images.githubusercontent.com/39976117/123032879-a06fb880-d39b-11eb-8800-b3c4232aef25.png)

Someone else with this problem: https://github.com/aws-amplify/amplify-js/discussions/7960

### Expected behavior

Expect this documentation will work with `@aws-amplify/ui-react` package

### Reproduction steps

See above

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Closing this one per my comment on the discussion https://github.com/aws-amplify/amplify-js/discussions/7960
