### ISSUE TITLE
Campaign Push Notifications Are Not Received 

### ISSUE THREAD

**Issue by kc9gpj** [aws-amplify/amplify-js#8504]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Push Notifications

### Amplify Categories

Notifications

### Environment information

<details>

```
  System:
    OS: macOS 11.4
    CPU: (8) x64 Apple M1
    Memory: 33.47 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.2.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.13.0 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 91.0.4472.114
    Firefox Developer Edition: 90.0
    Safari: 14.1.1
  npmPackages:
    @aws-amplify/pushnotification: ^4.1.1 => 4.1.1
    @babel/core: ^7.14.6 => 7.14.6
    @babel/runtime: ^7.14.6 => 7.14.6
    @react-native-async-storage/async-storage: ^1.15.5 => 1.15.5
    @react-native-community/eslint-config: ^3.0.0 => 3.0.0
    @react-native-community/netinfo: ^6.0.0 => 6.0.0
    @react-native-community/push-notification-ios: github:react-native-community/push-notification-ios => 1.8.0 (1.0.3)
    HelloWorld:  0.0.1
    aws-amplify: ^4.1.1 => 4.1.1
    babel-jest: ^27.0.5 => 27.0.5
    eslint: ^7.29.0 => 7.29.0
    hermes-inspector-msggen:  1.0.0
    jest: ^27.0.5 => 27.0.5
    metro-react-native-babel-preset: ^0.66.0 => 0.66.0 (0.64.0)
    react: 17.0.1 => 17.0.1
    react-native: 0.64.2 => 0.64.2
    react-native-push-notification: ^7.3.2 => 7.3.2
    react-test-renderer: 17.0.1 => 17.0.1
  npmGlobalPackages:
    @aws-amplify/cli: 4.52.0
    npm: 7.13.0
    react-devtools: 4.10.4
    react-native-cli: 2.0.1


```

</details>

### Describe the bug

Test notifications with a device token work properly for ios and android. 

![aws_screen](https://user-images.githubusercontent.com/25382071/123324559-90231f00-d4fc-11eb-8062-bc016ce79993.png)

![notification](https://user-images.githubusercontent.com/25382071/123324572-931e0f80-d4fc-11eb-9782-743c71043c4c.png)

Campaign Notifications are not received on any device. Test notifications via Endpoint IDs receives error.

![Screen Shot 2021-06-24 at 3 10 16 PM](https://user-images.githubusercontent.com/25382071/123325987-4d624680-d4fe-11eb-9dc6-baaac23d1c63.png)

![console error](https://user-images.githubusercontent.com/25382071/123326547-fe68e100-d4fe-11eb-9570-18d7ab32cd80.png)

**Related closed and unaddressed issues:**

No endpoint are registered in pinpoint campaign
https://github.com/aws-amplify/amplify-js/issues/1415

UpdateEndpoint does not create Push Notification subscription
https://github.com/aws-amplify/amplify-js/issues/2544

I'm not getting push notifications from AWS Pinpoint in react native (android) project, onRegister method is never triggered
https://github.com/aws-amplify/amplify-js/issues/3080

Pinpoint Push Notifications are not received through campaigns, sometimes they are sent and sometimes not
https://github.com/aws-amplify/amplify-js/issues/8066

### Expected behavior

Targeted devices via campaigns should receive a push notification. We have 250k+ monthly users and would love to interact with them through this service!

### Reproduction steps

1. Create Firebase/APN,Pinpoint accounts and configure according to documentation.
2. Follow steps outlined in the documentation to implement in codebase.
https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/js
3. Create a campaign in AWS pinpoint (created during documentation guided setup)
4. Send campaign targeting all users
5. Processed successfully, but 0% of users processed or received the notification.

Test Repo:
https://github.com/kc9gpj/testApp

### Code Snippet

```javascript
Amplify.configure({
  Analytics: {
    autoSessionRecord: true,
    AWSPinpoint: {
      appId: AWS_KEY,
      region: AWS_REGION,
      bufferSize: 1000,
      flushInterval: 30000,
      endpoint: {
        demographic: {
          appVersion: DeviceInfo.getVersion(),
          model: DeviceInfo.getDeviceId(),
          platform: DeviceInfo.getSystemName(),
          platformVersion: DeviceInfo.getSystemVersion(),
        },
      },
    },
  }
});

Amplify.configure({
  PushNotification: {
    appId: AWS_KEY,
    requestIOSPermissions: false,
  },
});

PushNotification.onNotification((notification) => {
  console.log('in app notification', notification);

  notification.finish(PushNotificationIOS.FetchResult.NoData);
});

PushNotification.onRegister((token) => {
  console.log('in app registration', token);
  
  // is this needed?
  PushNotification.updateEndpoint({
    address: token,
    optOut: 'NONE',
    userId: id
    })
});

PushNotification.onNotificationOpened((notification) => {
    console.log('the notification is opened', notification);
});

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by elorzafe** [comment]
@kc9gpj are you testing this on real device or simulator? If is a real device, which device (model and OS version) are you using?

**Comment by kc9gpj** [comment]
@elorzafe This has been tested on a mixture of real devices and simulators/emulators. 

Real Devices:
- Ipad Pro (IOS 14)
- Redmi Note 8 (Android 10)
- Poco X3 (Android 11)
