### ISSUE TITLE
API Auth Issues after introducing federatedSignIn

### ISSUE THREAD

**Issue by danielvouch** [aws-amplify/amplify-js#8505]
**Which Category is your question related to?**
Auth

**Amplify CLI Version** 
4.5.0

**What AWS Services are you utilizing?**
Auth, API, Function, Storage

**Description**

We have just introduced social sign ups in our apps and are using the Amplify helper function `federatedSignIn` to authenticate through Google.

If an existing native Cognito user exists, we link the two users using `adminLinkProviderForUser` however, in this scenario when using `owner` authorisation in our AppSync API layer the authenticated user is getting the following error `Not Authorized to access account on type Query`. (Accessing Account table)

This happens if I sign in with the native credentials or authenticate through Google within our App, but if I execute the same query in the AppSync console I do not get the error.

Is there any particular reason why this would be happening?

**Schema Replica**

```graphql
type Account
  @model(
    mutations: { update: "updateAccount" },
    queries: { get: "account", list: "accounts" },
    subscriptions: null
  )
  @auth(rules: [
    { allow: owner, ownerField: "entityId", identityClaim: "custom:entityid"},
    { allow: public, provider: iam, operations: [read] },
    { allow: private, provider: iam, operations: [read] },
  ])
{
  id: ID!
  field: ID
  email: AWSEmail
  entityId: String
  name: String
  position: String
}

```

**Comment by elorzafe** [comment]
@danielvouch 

When you use Amplify to make API request to AppSync is using Cognito Access Token, however you can only edit the claims for an ID token, which I think is what it uses AppSync console.

You can use Cognito Id Token on `API.graphql` by doing this

```javascript
Amplify.configure({
    API: {
        aws_appsync_graphqlEndpoint: 'https://xxxxxxxxxxxxxxxxxxxxxxxxxx.appsync-api.us-east-1.amazonaws.com/graphql',
        aws_appsync_region: 'us-east-1',
        aws_appsync_authenticationType: 'NONE',
        graphql_headers: async () => ({
            'Authorization': (await Auth.currentSession()).getIdToken().getJwtToken()
        })
    }
})
```

**Comment by danielvouch** [comment]
@elorzafe we managed to fix this, it was a business logic issue. 

Sorry for wasting your time with it..

**Comment by elorzafe** [comment]
@danielvouch I am happy that is solved. I will close the issue.

Thanks!
