### ISSUE TITLE
Deprecated API is used by @aws-amplify/pushnotification com.google.firebase.iid.FirebaseInstanceId

### ISSUE THREAD

**Issue by ahtokca** [aws-amplify/amplify-js#8506]
### Is this related to a new or existing framework?

React Native

### Is this related to a new or existing API?

Push Notifications

### Describe the feature you'd like to request

@aws-amplify/pushnotification uses very old version (12.0.1) of firebase. 
In particular package com.google.firebase.iid which is removed from latest version of firebase.

### Describe the solution you'd like

Upgrade to use firebase bom 

### Describe alternatives you've considered

none

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by elorzafe** [comment]
@ahtokca thank you for your feedback, we will discuss on the team how to fix this.

Is this breaking a production App? 

Are you able to publish your to Google Play Store?

You see this as a build error? Or just a warning message?

**Comment by ahtokca** [comment]
@elorzafe Thank you the rapid answer.

Starting Starting August 2021, new apps will be required to target API level 30, see https://developer.android.com/distribute/play-policies#APILevel30.

I end up with a runtime error 'java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId' when upgrading components of my react-native app to satisfy the requirements

> Is this breaking a production App?

Yes

> Are you able to publish your to Google Play Store?

Till Aug 2021

> You see this as a build error? Or just a warning message?

It is a runtime error, I assume jetifier somehow provide correct dependency build time, but not a runtime

**Comment by elorzafe** [comment]
@ahtokca thanks for clarifying

Can you share your package.json file?

**Comment by ahtokca** [comment]
Hi @elorzafe 

Here is part of it

```json
"@aws-amplify/pushnotification": "^3.2.14", <-- I tried latest too, effectively the package still uses very old FB messaging
....
"@react-native-firebase/analytics": "^12.1.0", 
"@react-native-firebase/app": "^12.1.0",
"@react-native-firebase/crashlytics": "^12.1.0",
"@react-native-firebase/messaging": "^12.1.0", <-- I believe anything above 9 breaks the app 
```

**Comment by Samaritan1011001** [comment]
> https://developer.android.com/distribute/play-policies#APILevel30

@ahtokca Can you please provide the following two pieces of information?
- changes you made to satisfy the requirements to target API level 30. Did you have to upgrade firebase? if so, to which version? 
- react-native versions -- before and after the changes to target API level 30

**Comment by yonatanganot** [comment]
Hey @Samaritan1011001,

We are having the same issue.

To replicate it, please go `android/app/build.gradle` file and change these lines:

```
implementation 'com.google.firebase:firebase-core:15.0.2'
implementation 'com.google.firebase:firebase-messaging:15.0.2'
```
to those:
```
implementation platform('com.google.firebase:firebase-bom:29.0.0')
implementation 'com.google.firebase:firebase-messaging'
```

Our react-native version is `0.66.1`.

Upon searching, I have found that `aws-sdk-android` does use the new API:
https://docs.amplify.aws/sdk/push-notifications/getting-started/q/platform/android/#set-up-your-backend

**Comment by Samaritan1011001** [comment]
Hi @yonatanganot, thank you for the steps! Are you also looking to target API level 30 and upgrade firebase? If so, are you trying to do it like OP in the `package.json` through the `@react-native-firebase/messaging` version as shown [above](https://github.com/aws-amplify/amplify-js/issues/8506#issuecomment-871989807)?

**Comment by yonatanganot** [comment]
Hey @Samaritan1011001,

Yes.

**Comment by Samaritan1011001** [comment]
@yonatanganot and @ahtokca the PR has been merged and released. Please try out the latest version `@aws-amplify/pushnotification@4.3.4`

**Comment by yonatanganot** [comment]
Hey @Samaritan1011001,

Thanks, it is fixed the issue!
