### ISSUE TITLE
cognitoUser.protoType.setUserMfaPreference still expects string[] parameters while it should take parameters of type any

### ISSUE THREAD

**Issue by AhmedAdes** [aws-amplify/amplify-js#851]
Do you want to request a feature or report a bug?
bug 

What is the current behavior?
After testing with **amazon-cognito-identity-js version 2.0.5** pushed to NPM yesterday
the function **setUserMfaPreference** still expects string[] parameters while it should **take parameters of type any** like that described in the documentation :
totpMfaSettings = {
PreferredMfa : true,
Enabled : true
};

What is the expected behavior?

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
amazon-cognito-identity-js@2.0.5

**Comment by vitrukroman** [comment]
It's not the type any, type should be { PreferredMfa : true, Enabled : true } for each mfa: SMS and TOTP
};

**Comment by elorzafe** [comment]
@powerful23 will be working on this. Thanks @AhmedAdes @vitrukroman
