### ISSUE TITLE
[Feedback] Amplify subscriptions stop when app goes to sleep. Don't resubscribe

### ISSUE THREAD

**Issue by spmatthews03** [aws-amplify/amplify-js#8513]
**Page**: [`/guides/q/platform/js`](https://docs.amplify.aws/guides/q/platform/js)

**Feedback**:

I'm trying to have a simple subscription and it works until the phone goes to sleep, or if the app is in the background for too long. I would like a way to resubscribe to the data so my UI and my server are not out of sync.

**Comment by chrisbonifacio** [comment]
@spmatthews03 are you using `API` or `DataStore` in your app?

**Comment by spmatthews03** [comment]
@chrisbonifacio API. I semi fixed it buy a listener on AppState and if subscriptions are null then I reload ALL subscriptions. just 8 of them soits not terrible and only if their componentn is mounted

**Comment by dave-vazquez** [comment]
@spmatthews03 I'm currently running into the same issue. Can you share your implementation for listening to AppState, checking if subscriptions are null and reloading all subscriptions?

**Comment by chrisbonifacio** [comment]
@spmatthews03 Nice workaround! I'm going to find out if this issue is expected behavior so I know if it's either a bug or a feature request that can be built in.

**Comment by dave-vazquez** [comment]
> @spmatthews03 Nice workaround! I'm going to find out if this issue is expected behavior so I know if it's either a bug or a feature request that can be built in.

@spmatthews03 Thank you, this would be super-helpful if you could find out.

**Comment by chrisbonifacio** [comment]
Hey @spmatthews03 and @dave-vazquez, so I did talk to the team about this. At the moment re-establishing connections to subscriptions is only handled by Amplify in the DataStore category. Unfortunately, this functionality is not yet available out of the box from the API category as explained here https://github.com/aws-amplify/amplify-js/issues/7057#issuecomment-716843165

That being said, until we do implement subscription reconnection I'm going to label this as a feature request. I'm personally interested in this and I know there are examples of how to handle this out there in the wild so I'll try to find that and post it here as well as make sure the docs are updated with a code snippet that achieves that.

**Comment by dave-vazquez** [comment]
Thanks @chrisbonifacio ! Very much apprrciated

**Comment by CSHaze** [comment]
Is this still being worked on?

**Comment by rudalson** [comment]
Hello. I need to solve this issue. It happens to frequently in ios. @spmatthews03  Can you also share your workaround to me?

**Comment by stocaaro** [comment]
Good news. Automated Reconnection is now available on the latest `aws-amplify` release! Review the [updated subscription docs](https://docs.amplify.aws/lib/graphqlapi/subscribe-data/q/platform/js/#connection-issues-and-automated-reconnection) and consider any application behavior you may want to add to best meet your users needs when subscriptions reconnect.

Please review our [breaking change guidance](https://github.com/aws-amplify/amplify-js#notice) before upgrading your application.

To upgrade Amplify to version 5, run the following in your project folder:
```
yarn add aws-amplify@latest
```

Check `package.json` to see if your project uses other `@aws-amplify/*` packages directly and upgrade them to latest as well.

With this behavior released, I am closing this issue as resolved.
