### ISSUE TITLE
"ReferenceError: regeneratorRuntime is not defined" in v4

### ISSUE THREAD

**Issue by TheDutchCoder** [aws-amplify/amplify-js#8514]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 22.42 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.0.0 - ~/.nvm/versions/node/v16.0.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 7.19.0 - ~/.nvm/versions/node/v16.0.0/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 91.0.4472.114
    Edge: 91.0.864.59
    Firefox: 84.0.2
    Safari: 14.1.1
  npmPackages:
    @aws-amplify/datastore: ^3.1.1 => 3.1.2 (2.10.1)
    @creativelayer/chalk-icons: ^1.1.2 => 1.1.2
    @creativelayer/chalk-ui: ^1.32.0 => 1.32.0
    @types/jest: ^26.0.23 => 26.0.23
    @typescript-eslint/eslint-plugin: ^4.28.1 => 4.28.1
    @typescript-eslint/parser: ^4.28.1 => 4.28.1
    @vitejs/plugin-vue: ^1.2.4 => 1.2.4
    @vue/compiler-sfc: ^3.1.2 => 3.1.2
    @vue/eslint-config-standard: ^6.0.0 => 6.0.0
    @vue/eslint-config-typescript: ^7.0.0 => 7.0.0
    @vue/test-utils: ^2.0.0-rc.9 => 2.0.0-rc.9
    @xstate/vue: ^0.6.0 => 0.6.0 (0.5.0)
    autoprefixer: ^10.2.6 => 10.2.6
    aws-amplify: ^3.4.3 => 3.4.3
    buffer: ^6.0.3 => 6.0.3 (4.9.2)
    cypress: ^7.6.0 => 7.6.0
    dynamic-import-polyfill: ^0.1.1 => 0.1.1
    eslint: ^7.29.0 => 7.29.0
    eslint-plugin-cypress: ^2.11.2 => 2.11.3
    eslint-plugin-import: ^2.23.4 => 2.23.4
    eslint-plugin-jest: ^24.3.6 => 24.3.6
    eslint-plugin-vue: ^7.12.1 => 7.12.1
    jest: ^26.6.3 => 26.6.3
    mockdate: ^3.0.5 => 3.0.5
    postcss: ^8.3.5 => 8.3.5
    tailwindcss: ^2.2.4 => 2.2.4
    ts-jest: ^26.5.5 => 26.5.6
    typescript: ^4.3.4 => 4.3.4
    vite: 2.2.4 => 2.2.4
    vue: ^3.0.11 => 3.1.2
    vue-jest: ^5.0.0-alpha.10 => 5.0.0-alpha.10
    vue-loader: ^16.2.0 => 16.2.0
    vue-router: ^4.0.10 => 4.0.10
    vue-router-mock: 0.0.3 => 0.0.3
    xstate: ^4.20.1 => 4.20.1
  npmGlobalPackages:
    @aws-amplify/cli: 5.0.2
    np: 7.5.0
    npm: 7.19.0
```

</details>

### Describe the bug

When using `aws/amplify` and import the Auth part, `Auth.signOut()` throws a "ReferenceError: regeneratorRuntime is not defined" error when using Vite as the builder.

### Expected behavior

Not to throw an error

### Reproduction steps

1. Use Vite (latest)
2. Use aws/amplify (latest)
3. Sign in with Auth
4. Call `Auth.signOut()`
5. Results in error

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

```javascript
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://hqptdavyajhyrjy5hsucf7s4aq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-dvzhiao7afalnd4ngy656gg57i",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://hl5y1tbtsc.execute-api.us-east-1.amazonaws.com/reinier",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:a5a66054-9e29-4237-bd34-92f3f757230c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_bPyCr6PJt",
    "aws_user_pools_web_client_id": "6pgdqdokmqvtnv7d732teu478f",
    "oauth": {},
    "aws_user_files_s3_bucket": "creativelayeromsf1e74c96893d4c5180677f6c846170d102506-reinier",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;

```

### Additional information and screenshots

The error doesn't occur with any v3 version. I'll see if any of the old v4 versions also work, but I have my doubts.

**Comment by TheDutchCoder** [comment]
The solution is to pass `Auth.signOut({ global: true })` for _some reason_.
I don't know why, but that seems like a bug to me.

**Comment by chrisbonifacio** [comment]
Hey @TheDutchCoder do you happen to be using async/await in your code?

**Comment by TheDutchCoder** [comment]
> Hey @TheDutchCoder do you happen to be using async/await in your code?

Yes all over the place, so that shouldn't be an issue (e.g. signIn also uses that).
It looks like Auth is hitting a `retry` function that uses a transpiled async/await in amplify, which is the point where it breaks down.

So my reasoning is that it actually fails to signout _first_ and then hits that retry where the bug is.

The bigger problem is why it fails to sign me out in the first place and why 1 other colleague has the same problem and 1 other _doesn't_. We're all on the same versions of node, npm, amplify-cli, aws-amplify, etc.

**Comment by TheDutchCoder** [comment]
I'm digging into this some more, and it seems to have happened somewhere between version `4.0.3` (works) and `4.1.0` (doesn't work).

Going through all the commits, I've found this piece that is actually throwing the error: https://github.com/aws-amplify/amplify-js/commit/fa5cdb81539e6b734e69b9b912898d25058140e7#diff-4bea2f0020039d5275abe5c4e4747c1c7c1457e59abb4101f26230011834925d

Also, the signout function changed here:https://github.com/aws-amplify/amplify-js/commit/fa5cdb81539e6b734e69b9b912898d25058140e7#diff-8645b6bfe673522e9f71ef69ab2dc9bc01f0e15c4fe41cb5766a3acef1749ca5

The new signOut changes look fishy, especially since it now can take a callback, but the TS definitions don't mention this at all (it still shows an option object).

Yeah you didn't generate the esm lib:
![image](https://user-images.githubusercontent.com/1668207/124010169-7ece8c80-d9ac-11eb-90a5-b1ffdb33d95b.png)

This is from aws-amplify 4.1.2, going into the esm lib the signout method looks like this:
`AuthClass.prototype.signOut = function (opts) {`

But in the actual dist folder it's:
`_proto.signOut = function signOut(revokeTokenCallback) {`

It looks like either the ESM lib was not generated (along with the types).

Tangentially related: you guys don't provide a list of release notes? This is a breaking change and should at least be mentioned somewhere in a release note and/or (even better) should have gotten a major release.

**Comment by chrisbonifacio** [comment]
Hi @TheDutchCoder, sorry for the delay. We do update the README with any breaking changes between versions. There are known issues with Vite which usually can be resolved through your configuration but we are actively working towards making our library more compatible with Vite.

You can track and/or contribute to the work being done to remedy these issues in PRs like these https://github.com/aws-amplify/amplify-js/pull/7970

We also opened our own issue in the `aws-sdk-js` repo to help with this https://github.com/aws/aws-sdk-js/issues/3673

In the meantime, I was able to reproduce this issue pretty quickly and consistently with a fresh Vite + React app with Amplify so I labeled it a bug for the team and they are aware of the cause. This is a bandaid for now but you can get past this issue currently by simply installing `regenerator-runtime` if you don't already have it in your dependencies and importing it in the file you're calling `Auth.signOut`.

```js
import "regenerator-runtime";

```

**Comment by hkjpotato** [comment]
@TheDutchCoder Thank you for reporting this. Currently we are creating a quick fix, meanwhile you can follow the readme to import `regenerator-runtime`.
https://www.npmjs.com/package/regenerator-runtime

for reference: https://github.com/babel/babel/issues/9849#issuecomment-487040428

**Comment by TheDutchCoder** [comment]
Thanks for picking this up @chrisbonifacio and @hkjpotato !
I'll import the regenerator-runtime in the Auth file to circumvent it.

Could you maybe shed some light onto why the ESM build differs from the transpiled JS build?
Mainly the ESM build still has the signOut method with options, wheres the minified build has the signOut method with the revokeTokenCallback, or am I looking in the wrong place?

**Comment by hkjpotato** [comment]
@TheDutchCoder `AuthClass.signOut = function (opts) ` and behind the scene `CognitoUser.signOut = function (revokeCallback)`

Normally, when we use a third party codebase, we seldomly use its "source code" or uncompiled code directly.

```
third party                             |              your app
src code->build->exposed code           |             e.g. find the code based on package.json `main` field 
```

I haven't used vite yet, but I assume it still follow the normal node module resolving path to load the JS code?  This might be a better question for the Vite community though..
