### ISSUE TITLE
Storage can't make CRUD to S3 bucket

### ISSUE THREAD

**Issue by totaland** [aws-amplify/amplify-js#8526]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Storage

### Amplify Categories

storage

### Environment information

<details>

```
# Put output below this line
**Issues with GET, PUT object from s3**

Unhandled Runtime Error
TypeError: Cannot read property 'byteLength' of undefined

Call Stack
Object.isEmptyData
../../node_modules/.pnpm/node_modules/@aws-crypto/sha256-browser/build/isEmptyData.js (8:0)
Sha256.update
../../node_modules/.pnpm/node_modules/@aws-crypto/sha256-browser/build/webCryptoSha256.js (21:0)
Sha256.update
../../node_modules/.pnpm/node_modules/@aws-crypto/sha256-browser/build/crossPlatformSha256.js (23:0)
hmac
../../node_modules/.pnpm/node_modules/@aws-sdk/signature-v4/dist/es/credentialDerivation.js (86:0)
eval
../../node_modules/.pnpm/node_modules/@aws-sdk/signature-v4/dist/es/credentialDerivation.js (33:0)
step
../../node_modules/.pnpm/node_modules/tslib/tslib.es6.js (102:0)
Object.eval [as next]
../../node_modules/.pnpm/node_modules/tslib/tslib.es6.js (83:44)
eval
../../node_modules/.pnpm/node_modules/tslib/tslib.es6.js (76:0)



```

</details>

### Describe the bug

It seems this is the dependencies issues with AWS-Amplify and AWS-SDK. I believe the newer version of the s3Client should fix this issue

### Expected behavior

Should have get and put the object without issue. 

### Reproduction steps

Add authentication with Cognito, set authrole to get all access to s3 just like in the aws-amplify docs
Add a function to get object from s3 bucket. 
This will show the result like above

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

All authentication is set wth Cognito AuthRole to put, get, delete objects from s3with

**Comment by chrisbonifacio** [comment]
Hey @totaland Are you experiencing this behavior on the latest version of `aws-amplify`? If not, could you copy/paste your package.json so we can see what packages and versions you're working with?

**Comment by svidgen** [comment]
Hi @totaland, I was unable to repro this, so I'm going to need some more detail.

In addition to the `package.json`, could you show me which particular docs/steps you followed? Which options you chose (minus any sensitive info). Could you also give me a code snippet that repros the problem?

Thanks!

**Comment by totaland** [comment]
> Hi @totaland, I was unable to repro this, so I'm going to need some more detail.
> 
> In addition to the `package.json`, could you show me which particular docs/steps you followed? Which options you chose (minus any sensitive info). Could you also give me a code snippet that repros the problem?
> 
> Thanks!

I use:
aws-amplify: 4.1.2
react-dropzone: 11.3.2
build with material-ui latest
` const onDrop = useCallback(
        (droppedFiles) => {
            let newFiles = mode === 'update' ? droppedFiles : [...(files || []), ...droppedFiles];
            if (mode === 'append') {
                newFiles = newFiles.reduce((prev: File[], file: File) => {
                    const fo = Object.entries(file);
                    if (
                        prev.find((e: File) => {
                            const eo = Object.entries(e);
                            return eo.every(
                                (
                                    [key, value],
                                    index,
                                ) => key === fo[index][0] && value === fo[index][1],
                            );
                        })
                    ) {
                        return prev;
                    }
                    return [...prev, file];

                }, []);
            }
            setValue(name as string, newFiles, { shouldValidate: true, shouldDirty: false });
            try {
                newFiles.forEach((file: File) => {
                    console.log(file);
                    // TODO some issues in dependencies
                    // Storage.put(file.name, file, {
                    //     level: 'protected',
                    //     contentType: 'application/pdf',
                    // });
                });
            } catch (e) {
                console.log(e);
            }
        },
        [setValue, name, mode, files],
    );`

https://docs.amplify.aws/cli/storage/import#connect-to-an-imported-s3-bucket-with-amplify-libraries
This is the setup that I follow to set up the authentication for Cognito with auth-role etc.

https://react-dropzone.js.org/
This is the react-dropzone library that I use. The onDrop function is where the Storage.put method was call.

**Comment by chrisbonifacio** [comment]
@totaland what's the particular error you're getting from the `catch`? And what kind of files are you trying to upload?

**Comment by totaland** [comment]
@chrisbonifacio 
![image](https://user-images.githubusercontent.com/36496259/124962973-979d0900-e062-11eb-97fd-413076868bc1.png)

**Comment by chrisbonifacio** [comment]
Actually, I just saw the error you posted in the Env Information. Sorry about that. I see what you mean about the dependency, the error is coming from `@aws-crypto`. Seems to be checking if the data passed is empty depending on the string length if data type is string or the byteLength if otherwise.

```js
export function isEmptyData(data: SourceData): boolean {
  if (typeof data === "string") {
    return data.length === 0;
  }

  return data.byteLength === 0;
}
```

I tried uploading pdfs as well but I haven't run into that error either. Also on 4.1.2. Can you try just uploading a simple text file and see if that works for you? Just to see if it's an issue with the file type/encoding.

you can do so by changing the commented out Storage code to this

```
Storage.put("test", "this is a test file", {
                        level: 'protected',
                        contentType: 'text/plain',
                    });
```

**Comment by PeterEckIII** [comment]
@chrisbonifacio , I am receiving the same error message but on a `Storage.get` request. Would you like me to open a separate issue here?

**Comment by chrisbonifacio** [comment]
@PeterEckIII yeah that would be best. If you can fill out the Bug Report form with the requested information that would help us greatly in trying to reproduce the issue.

I

**Comment by chrisbonifacio** [comment]
Hi @totaland 👋 Closing this as we have not heard back from you in over a week. If you are still experiencing this issue and in need of assistance, please feel free to re-open. Thank you!
