### ISSUE TITLE
Amplify app cloudformation template should have option for integrating Notification service(SNS)

### ISSUE THREAD

**Issue by akanungo22** [aws-amplify/amplify-js#8528]
### Is this related to a new or existing framework?

React

### Is this related to a new or existing API?

Push Notifications

### Is this related to another service?

SNS

### Describe the feature you'd like to request

Amplify app cloudformation template should have option for integrating Notification service(SNS).

### Describe the solution you'd like

Amplify app cloudformation template should have option for integrating Notification service(SNS).

### Describe alternatives you've considered

Manual setting up SNS

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by nadetastic** [comment]
Hi @akanungo22 👋

Have you had a chance to look at adding Custom resource with `amplify add custom`? https://docs.amplify.aws/cli/custom/cdk/

This may address your needs. Let me know if you have questions, and feel free to elaborate on your use case if the above isn't a fit for you
