### ISSUE TITLE
Authorization fails when sending authorization header along with api_key (GraphQL API)

### ISSUE THREAD

**Issue by hedgehogs-mind** [aws-amplify/amplify-js#8545]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

Authentication, GraphQL API

### Amplify Categories

auth, api

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 11.2.1
    CPU: (8) arm64 Apple M1
    Memory: 123.78 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.8.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.5.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Safari: 14.0.3
  npmGlobalPackages:
    @ionic/cli: 6.16.3
    npm: 7.5.0
    yarn: 1.22.10

```

</details>

### Describe the bug

I have an amplify data model and an API configured to use
- API_Key for default auth AND
- Cognito User Pools

Requests requiring cognito authorization fail, as the cognito auth mode is not added along with the api_key. Even adding the jwt token as an authorization header results in an "Unauthorized" response.

Two questions:

1. Why amplify / the graphql API does not configure BOTH (api key and cognito) auth modes automatically?
2. Why does authorization even fail, if I additionally append the jwt token as an header?

```
Amplify.configure({
  ...awsconfig,
  API: {
    graphql_headers: async () => {
      const session = await Auth.currentSession().catch(() => null)
      let headers = {}

      if ( session ) {
        const accessToken = session.getAccessToken()

        if ( accessToken ) {
          headers["authorization"] = accessToken.getJwtToken()
        }
      }

      return headers
    }
  }
})
```

### Expected behavior

API should grant access to the mutation if the authorization header is present (although the API_KEY is given too).

Ideally amplify would configure the authorization header along the api_key.

Same behavior like when using DataStore with the following config:
```
  Amplify.configure({
    ...awsconfig,
    DataStore: {
      authModeStrategyType: AuthModeStrategyType.MULTI_AUTH
    },
  }
```

### Reproduction steps

Configure Amplify as described in Code Snippet and executing the calls for the described schema.

### Code Snippet

Here is my short graphql schema:
```
type BlogPost
  @auth(
    rules: [
      {
        allow: groups,
        groups: ["Admins"]
      },
      {
        allow: groups,
        groups: ["Authors"],
        operations: [create]
      },
      {
        allow: public,
        operations: [read]
      },
      {
        allow: owner,
        operations: [update, delete],
        identityClaim: "sub"
      }
    ]
  )
{
  id: ID!
  title: String!
  content: String!
}
```

Everyone (with an api key) should read data, and Authors/Admins can also create them.

But when logged in, the create-Call fails, as the auth mode in awsexports is set to `API_KEY`. When setting the authMode for that one request, it succeeds:
```
await API.graphql({
  query: createBlogPost,
  variables: 
    { input: 
      {
        "title": "Titel "+random.toString(),
        "content": "Content "+random.toString()
      }
    },
  authMode: "AMAZON_COGNITO_USER_POOLS"
})
```

This fails:
```
await API.graphql({
  query: createBlogPost,
  variables: 
    { input: 
      {
        "title": "Titel "+random.toString(),
        "content": "Content "+random.toString()
      }
    }
})
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "...",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "...",
    "aws_user_pools_web_client_id": "...",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "...",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "..."
};

**Comment by hedgehogs-mind** [comment]
Hey guys,

After work I had some time to set up a demo repository: https://github.com/hedgehogs-mind/aws-amplify-js-ticket-8545-example

The README.md contains all steps for precise reproduction and two GIFs.

Kind regards,
Peter

**Comment by Khairo-kh** [comment]
Investigating this now. Thank you @hedgehogs-mind

**Comment by Khairo-kh** [comment]
From what I see in your example repo requests with default authorization are failing (i.e., without the optional parameter `authMode` on `API.graphql({ })`). 

When we have multiple authorization modes and we do not specify the `authMode`  parameter, the default authorization mode will be used. In the case of the example repo, the default is the API key. 

The API call fails to create a post with the API key because you did not authorize this action in your GraphQL schema. The rules you have with the auth directive are the following:
```graphql
@auth(
    rules: [
      {
        allow: groups,
        groups: ["Authors"]
      },
      {
        allow: public,
        operations: [read]
      }
    ]
  )
```
The `public` authorization by default works with an API key behind the scene and you have the allowed operations set to only read so you will get unauthorized if you try to create an object with API key authorization. I hope this helps!

**Comment by Khairo-kh** [comment]
Just to be more clear, if you want to allow creating objects with API key authorization just add `create` in the operation as follows: 
```
 operations: [create,  read]
```
You can read more on authorization rules [here](https://docs.amplify.aws/cli/graphql-transformer/auth). Please let me know if you have any other questions!

**Comment by chrisbonifacio** [comment]
Hi @hedgehogs-mind 👋 Closing this as we have not heard back from you in over a week. If you are still experiencing this issue and in need of assistance, please feel free to re-open and provide us with any information previously requested by our team members so we are better able to assist you. Thank you!
