### ISSUE TITLE
Auth.currentSession() error with "buildOptimizer": true (angular.json) when prod release

### ISSUE THREAD

**Issue by dilantha-nimshan** [aws-amplify/amplify-js#8546]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

npmGlobalPackages:
    @angular/cli: 11.1.4
    @nestjs/cli: 7.2.0

</details>

### Describe the bug

This may be bug... 
Previously had angular project with version 8 and upgraded to the version 11. 
aws-amplify : 1.3.3 after upgrade.
We have angular project that working fine with dev and test environment.  When comes to the prod environment we added configurations to the angular,js file.

`"optimization": true,
 "outputHashing": "all",
 "sourceMap": true,
 "namedChunks": false,
 "extractLicenses": true,
 "vendorChunk": false,
 "buildOptimizer": true`
 
 since then we having error like below in auth component,
 
![image](https://user-images.githubusercontent.com/79845067/124594497-7af3ac00-de7d-11eb-9c2f-bb900cc49a59.png)

Added debug point and error comes from here,
![image](https://user-images.githubusercontent.com/79845067/124594618-a4acd300-de7d-11eb-9c3d-8836df4ac36b.png)

 We tried with aws-amplify:1.3.3 and 4.1.2 . Still no luck.

### Expected behavior

Build without errors

### Reproduction steps

Reproduce when login to prod environment , 
![image](https://user-images.githubusercontent.com/79845067/124595463-ad51d900-de7e-11eb-8e4f-e80091f3c22f.png)

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by cwomack** [comment]
@dilantha-nimshan, apologies on the time it's taken to follow up on this from us.  Are you still experiencing this issue within the most recent version of Amplify (v.5+) or older versions? And just to confirm, the issues only happen when the described changes are made to the `angular.js` file?

**Comment by cwomack** [comment]
@dilantha-nimshan, going from v8 to v11 may cause some issues with your compiler since the Just-in-Time (JIT) compiler was the default setting up to v8, then changed to the Ahead-ofTime (AOT) after v9+.  I wonder if that's what's causing some of the TS errors you're seeing (if you're not using AOT).  If you get a chance to reply to this, could you check your `angular.json` file to see if you've got `aot: true`  in there? 

I'll close out this issue for now since we haven't heard from you and it doesn't seem to be a widespread issue, but happy to reopen if you can reply back and give some additional insight.
