### ISSUE TITLE
[RFC] Location based uses cases in Amplify

### ISSUE THREAD

**Issue by Amplifiyer** [aws-amplify/amplify-js#8553]
_This is a Request For Comments (RFC). RFCs are intended to elicit feedback regarding a proposed change to the Amplify Framework. Please feel free to post comments or questions here._

This RFC is to gather customer feedback for a new proposed functionality in Amplify related to location use cases. We would like to hear from Amplify customers 
* Which all of these you would want to see in Amplify?
* Are any use cases that are not covered below that Amplify should consider?

## Motivation

Location based uses cases are critical for a lot of mobile and web applications where users would like to see a Map, search for addresses or POI, track a device location against a geofence or turn-by-turn navigation.

Amazon launched [Location Services](https://aws.amazon.com/about-aws/whats-new/2020/12/aws-announces-amazon-location-service-preview/) during 2020 re-invent that made it easier and more cost-effective to add maps, location awareness, and other location-based features to web and mobile applications (See [blog post](https://aws.amazon.com/blogs/aws/amazon-location-service-is-now-generally-available-with-new-routing-and-satellite-imagery-capabilities/)).

To add location functionality in mobile and web apps, developers are required to set up backend location services resources and provision the correct IAM policies for their Cognito auth/un-auth roles. Moreover, geofence breach events emitted through EventBridge requires creating more backend resources to consume these events in your front-end apps. See simplified guides on how this integration works today for [JavaScript](https://docs.amplify.aws/guides/location-service/setting-up-your-app/q/platform/js), [Android](https://docs.amplify.aws/guides/location-service/setting-up-your-app/q/platform/android) and [iOS](https://docs.amplify.aws/guides/location-service/setting-up-your-app/q/platform/ios)

Rendering and displaying the maps using popular open source Map SDKs is also not straightforward and developers are required to write the [request transformation code to sign AWS requests](https://docs.aws.amazon.com/location/latest/developerguide/display-map.html) to render the Amazon Location Services map data in these open source Map SDKs.

Amplify CLI can help developers automate provisioning Amazon Location service resources and creating pipeline to consume EventBridge events in their front-end apps. Amplify libraries will expose use case-centric APIs to easily interact with these backend resources.

## Use cases

* Display a Map (using [Maplibre](https://github.com/maplibre)) with map data retrieved from Amazon Location Services, easy to add markers to display relevant POIs.
* Search for POI or Addresses on map (Geocoding)
  * Search text box Map module for searching and showing the results on the Maps. Clicking on a result will show the location on the map.  
* Lookup address from a map coordinates (Reverse Geocoding)
* Create and display Geofences on a map or through APIs
* Display devices locations and device location history on a map
* Consume events when a device enters or exits a Geofence
* Generate and display route(s) between two location coordinates (or with multiple waypoints in between).

You can combine some of these functionalities to easily achieve the following use cases.
* Live Asset Tracking -> Create devices and geofences such that you have the ability to track live and location history of your devices and get events when devices enter or exit a geofence.
* Package Delivery -> Send notifications to customers when their package has been picked up by the delivery person or the package has been delivered.
* Location based advertising -> Personalize Ads and marketing to your customers based on their location.

**Comment by Kilo-Loco** [comment]
Turn-by-turn navigation
![Loki ouuuu](https://media.giphy.com/media/AsKkJB6JbFGiQ/giphy.gif)

**Comment by markramrattan** [comment]
_Which one of these you would want to see in Amplify?_

That's difficult, I like more than one. If I had to pick… 'Consume events when a device enters or exits a Geofence'. Many use cases, targeting content based on entering / exiting an area. For example, aligning to the meet-up app / something I would build, notifications that say: 'you're near an AWS meet-up happening in 30mins and 0.3 miles away. Would you like to attend?' 

_Other ones I liked:_ 

- Create and display Geofences on a map or through APIs - Be cool to display reviews from users as you walk through different areas based on things you like. 
- Display devices locations and device location history on a map - Customer metrics / insights / connect with pinpoint
- Generate and display route(s) between two location coordinates (or with multiple waypoints in between) - Sales conversion aka show me the way. 

_Are any use cases that are not covered below that Amplify should consider?_

Probably, though those three cover the spectrum well and provide strong justification for this integration. I also think as we build more apps that try, connect us & information closer together, Amazon Location Services will be a fundamental part of enabling those outcomes.

**Comment by PeteDuncanson** [comment]
Planning a route with multiple drop offs (waypoints) would be my biggest need. 

"I have 20 customers to see a these addresses and I'll take 10 minutes with each customer, which order should I visit them in?"

If it can be traffic aware for the time of day all the better (avoid schools at pick/drop off times etc.)

**Comment by rprisram** [comment]
This is amazing! Thanks.
Few things that i would want to know if geofence already caters to.
- Overlapping geofences - venn diagram three circles and user is in common intersection.
- Concentric geofences - inner and outer ones.
Will there be separate events to denote above kind of geofences? Because from user point of view, they might want to know that they fall within overlapping or concentric geofences.
- will the radius be customizable?
- For mobile apps, there appears to be platform related restrictions on geofences monitored when user enters or exits a region, so the number of events triggered - would these be restricted as well, can this be circumvented?
Sorry if these have been already addressed.
Thanks for the amazing work as always!

**Comment by evertson90** [comment]
Nice. As soon as I saw the announcement about AWS Location Services I thought about Amplify and having it as a category. It is nice to see that this is happening!

As for use cases, you have already covered the use cases I am currently using Google Maps for in my Amplify apps. One thing that would be nice if we could get UI components for the map in the Amplify UI packages. Is this already planned?

**Comment by Amplifiyer** [comment]
@markramrattan thanks for your feedback and sorry for confusion, I didn't mean to say "pick only one of these features" but rather which all are relevant for your use cases.

Can you expand a little bit more on pinpoint integration and what use case you are trying to solve.

**Comment by Amplifiyer** [comment]
> If it can be traffic aware for the time of day all the better (avoid schools at pick/drop off times etc.)

Thanks @PeteDuncanson for your feedback. And yes the route will be traffic aware. https://aws.amazon.com/location/features/

**Comment by Amplifiyer** [comment]
@ev

> One thing that would be nice if we could get UI components for the map in the Amplify UI packages. Is this already planned?

@evertson90 thanks for your feedback! Yes we are planning to build UI components leveraging maplibre library.

**Comment by Amplifiyer** [comment]
@rprisram, Most of the geofences related use cases you asked will be covered while rendering the geofences on the map, however the events generated for breaching these geofences will be consistent across all types of geofences with geofence Ids included in the event so developers can identify which geofence was breached.

Geofence breach events are implemented at the service layer and so typical client side limitations for mobile devices are not applicable for them.

Can you help us describe your use cases in more detail for us to understand how you will use concentric and overlapping geofences?

**Comment by markramrattan** [comment]
@Amplifiyer Sure, i've been thinking about what type of marketing i'll need to do for rapid user growth of my application. Having device location history on a map would be a great parameter to segment and do target marketing to users (via Pinpoint). I think it would get a higher conversion rate than facebook adverts (I won't know for sure until I do testing). The user would already be interacting with the app. If they've never visited a particular location you would be able to distribute & communicate different incentives to those who have visited. Which should lead to better app / customer / engagment experience.

**Comment by Amplifiyer** [comment]
Amplify Geo has been launched as a developer preview. Add maps and location search to your web applications!

https://aws.amazon.com/about-aws/whats-new/2021/08/announcing-amplify-geo-developer-preview-aws-amplify/

**Comment by hdworld11** [comment]
@rprisram Thanks for your input! We are looking for more geofence use cases so we can improve the library to better assist you with your location features! Please DM me on Discord (harshitadaddala#5464) or [Twitter](https://twitter.com/HarshitaDaddala) if you' are interested in chatting further :)
