### ISSUE TITLE
Unable to resolve module ./aws-exports from /Users/ed/projecttest/App.js: None of these files exist:   * aws-exports(.native|.ios.ts|

### ISSUE THREAD

**Issue by srikared** [aws-amplify/amplify-js#8577]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Not applicable

### Amplify Categories

Not applicable

### Environment information

<details>

```
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 280.13 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.22.3 - /usr/local/opt/node@12/bin/node
    npm: 6.14.13 - /usr/local/opt/node@12/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Chrome Canary: 93.0.4573.0
    Firefox: 89.0.2
    Safari: 14.1.1
  npmPackages:
    @aws-amplify/cli: ^4.47.1 => 4.47.1
    @babel/core: ^7.9.0 => 7.9.0
    @react-native-async-storage/async-storage: ^1.15.5 => 1.15.5
    @react-native-community/eslint-config:  1.1.0
    @react-native-community/eslint-plugin:  1.0.0
    @react-native-community/netinfo: ^6.0.0 => 6.0.0
    HelloWorld:  0.0.1
    aws-amplify: ^4.1.3 => 4.1.3
    aws-amplify-react-native: ^5.0.3 => 5.0.3
    babel-plugin-inline-view-configs:  0.0.5
    expo: ~42.0.1 => 42.0.1
    expo-status-bar: ~1.0.4 => 1.0.4
    hermes-inspector-msggen:  1.0.0
    new-plugin-package:  1.0.0
    react: 16.13.1 => 16.13.1
    react-animated:  0.1.0
    react-dom: 16.13.1 => 16.13.1
    react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
    react-native-codegen:  0.0.2
    react-native-web: ~0.13.12 => 0.13.18
  npmGlobalPackages:
    eslint: 4.5.0
    expo-cli: 4.7.3
    lerna: 3.13.0
    npm: 7.3.0
    solc: 0.8.4
    truffle: 5.3.5
```

</details>

### Describe the bug

After installing the react-native app using expo, I tied to run the app on simulator but it blocks due to the error
`› Opening exp://127.0.0.1:19000 on iPhone 11
Failed building JavaScript bundle.
Unable to resolve module ./aws-exports from /Users/ed/projecttest/App.js:

None of these files exist:
  * aws-exports(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * aws-exports/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  3 | import { StyleSheet, Text, View } from 'react-native';
  4 | import Amplify,{API} from 'aws-amplify'
> 5 | import config from './aws-exports'
    |                     ^
  6 | Amplify.configure(config)
  7 |
  8 | export default function App() {
Unable to resolve module ./aws-exports from /Users/ed/projecttest/App.js:`

### Expected behavior

The app should perfectly build and run

### Reproduction steps

I followed the following tutorial https://docs.amplify.aws/start/getting-started/setup/q/integration/react-native#initialize-a-new-backend but initialised the BE using REST API GO

### Code Snippet

```javascript
// Put your code below this line.
import { StatusBar } from 'expo-status-bar';
import React, {useEffect, useState} from 'react';
import { StyleSheet, Text, View } from 'react-native';
import Amplify,{API} from 'aws-amplify'
import config from './aws-exports'
Amplify.configure(config)

export default function App() {
  const [health, setHealth] = useState('loading')
  useEffect(()=>{
    checkHealth()
  },[])

  async function checkHealth() {
    const healthStatus = await API.get('goapi','/health-check')
    setHealth(healthStatus.message)
  }

  return (
    <View style={styles.container}>
      <h2>{health}</h2>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by srikaredgrab** [comment]
I used
` import config from './src/aws-exports'`
instead of 
`import config from './aws-exports'`

And that fixed the error. Please update the documentation https://docs.amplify.aws/start/getting-started/setup/q/integration/react-native#create-a-new-react-native-app
