### ISSUE TITLE
Option to get display=popup on facebook URL from auth.federatedSign

### ISSUE THREAD

**Issue by suryamangi1213** [aws-amplify/amplify-js#8595]
### Is this related to a new or existing framework?

React

### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

On FB  button click, we are calling the Auth.federatedSign('facebook'). This will call AWS amplify and amplify will call Facebook. Here it will generate URL(FB URL with display=page).
We required option to get display=popup on generated FB URL.

Currently, We are getting like,
https://www.facebook.com/login.php?display=page,

Required display=popup.
https://www.facebook.com/login.php?display=popup,

We checked, couldn't find option to provide display property.

Request to provide an option  on auth.federated sign .

Find the below screenshots.

display=page

<img width="1784" alt="Screen Shot 2021-07-15 at 8 47 53 AM" src="https://user-images.githubusercontent.com/87489400/125883781-5d32d57a-552e-4d31-9a4b-b1fcec448b76.png">

display=popup
<img width="1787" alt="Screen Shot 2021-07-15 at 8 49 12 AM" src="https://user-images.githubusercontent.com/87489400/125883811-d7927101-3957-412a-a0b4-1080942e5d06.png">

### Describe the solution you'd like

Required option to provide display=page or display=popup on auth.federatedSignIn to get desired UI.

### Describe alternatives you've considered

so far, we didn't find any alternatives.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by njreid** [comment]
Hi - not sure if you saw there is the option to use a custom Federated login provider.

```
export type FederatedSignInOptionsCustom = {
	customProvider: string;
	customState?: string;
};
```

It might take a little bit of playing around, but you might be able to use the complete string (including the query parameter) as the provider.

```
Auth.federatedSignIn("https://www.facebook.com/login.php?display=popup", ...}
```

**Comment by suryamangi1213** [comment]
Hi ,

I have checked above options , but it is not working for me.

I saw this post in aws forum ,https://forums.aws.amazon.com/thread.jspa?messageID=889040.

But it was  2 years back,  not sure if this feature implemented.

Can you please provide more details on it?

**Comment by elorzafe** [comment]
@suryamangi1213 

Are you trying to do federation with UserPools (OAuth flow) or IdentityPools (Getting the token from facebook and pass that to Amplify) ? 

Can you share a redacted version on how you are configuring the library?
