### ISSUE TITLE
Error messages are not localized.

### ISSUE THREAD

**Issue by marcolino** [aws-amplify/amplify-js#8599]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
$ npx envinfo --system --binaries --browsers --npmPackages --duplicates --npmGlobalPackages
npx: installato 1 in 2.03s

  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    Memory: 851.73 MB / 7.62 GB
    Container: Yes
    Shell: 5.0.17 - /usr/bin/bash
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/apps/sistemisolari/quiccasa-client/node_modules/.bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.164
    Firefox: 87.0
  npmPackages:
    @babel/core: ^7.14.6 => 7.14.6 (7.12.3, 7.12.17)
    @babel/node: ^7.14.7 => 7.14.7 
    @babel/preset-env: ^7.14.7 => 7.14.7 (7.12.17, 7.12.1)
    @babel/preset-es2015: ^7.0.0-beta.53 => 7.0.0-beta.53 
    @babel/preset-react: ^7.14.5 => 7.14.5 (7.12.13, 7.12.1)
    @babel/register: ^7.14.5 => 7.14.5 
    @material-ui/core: ^4.11.4 => 4.11.4 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @testing-library/jest-dom: ^5.11.4 => 5.14.1 
    @testing-library/react: ^11.1.0 => 11.2.7 
    @testing-library/user-event: ^12.1.10 => 12.8.3 
    add: ^2.0.6 => 2.0.6 
    aws-amplify: ^4.1.1 => 4.1.1 
    babel-plugin-require-context-hook: ^1.0.0 => 1.0.0 
    bootstrap: ^5.0.2 => 5.0.2 
    node-sass: 5 => 5.0.0 
    prettier: ^2.3.1 => 2.3.1 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    react-router-dom: ^5.2.0 => 5.2.0 
    react-router-sitemap: ^1.2.0 => 1.2.0 
    react-scripts: 4.0.3 => 4.0.3 
    react-toastify: ^7.0.4 => 7.0.4 
    web-vitals: ^1.0.1 => 1.1.2 
    yarn: ^1.22.10 => 1.22.10 
  npmGlobalPackages:
    eslint: 7.21.0
    html-minifier: 4.0.0
    n: 7.0.0
    npm: 6.14.4
    serverless: 2.28.7
```

</details>

### Describe the bug

Error messages are not localized.

### Expected behavior

Error messages should be locallized in the language set with `I18n.setLanguage(language)`  
(for example `I18n.setLanguage('it')`).

### Reproduction steps

1. Install "aws-amplify"

### Code Snippet

```javascript

import Amplify, { Auth } from "aws-amplify";
import { I18n } from "aws-amplify";

...

I18n.setLanguage('it');

...

signUp({
      username: 'wrong username',
      password: 'wrong password',
    }, {
      success: (data) => {
        console.log('signUp success:', data);
      },
      error: (err) => {
        console.error('signup error should be localized in Italian, but it is not:', err);
      },
    });
  };
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Are you expecting the error messages from the Auth library to be translated according to the language set by the i18n library? Or do you mean the errors that are displayed by the UI components?

**Comment by marcolino** [comment]
I am expecting the error messages from the Auth library to be translated according to the language set by the i18n library.

**Comment by chrisbonifacio** [comment]
Ah okay. At the moment this is not currently the expected behavior. Not all error messages are localized by Amplify yet. It seems like there was some work towards this but it is still ongoing. I will label this as a feature request for now. Please feel free to help add translations to the error messages and submit a PR.

**Comment by marcolino** [comment]
Thanks. I'd love to help, translating at least to Italian locale. The problem is I don't have all the server-side error messages, I can only see the most obvious ones ("The user already exists", and such...) calling the APIs. And, most important, I can't find any translation file in this project that I can modify and submit a PR... :-)

**Comment by marcolino** [comment]
@chrisbonifacio: can you help please?

**Comment by chrisbonifacio** [comment]
Hey @marcolino 👋 Sorry for the confusion. When I said "feel free to help add translations and submit a PR" I should've specified that I meant for the UI library's error message component since that's where we've been accepting translation PRs so far.

Currently we're not translating the error messages from the Auth library and recommend that the customer to use the i18n library to catch the errors and translate them as they see fit for their end users for now. Hope you understand and apologies again for not being clear.

**Comment by marcolino** [comment]
Hey @crisbonifacio! Of course I understand. I thank you for the great job... I don't know if I had choosen to use aws-amplify if I had know this from the beginning, but now I think I'll try to translate client side all server errors as they pop up...
Thanks again, and keep up the good job.

**Comment by murathany7** [comment]
@chrisbonifacio did you fix this from AWS side? I am having the same issue using Authenticator, what is the workaround for this?

**Comment by tannerabread** [comment]
Hi @murathany7
This should be handled now with the newer version of the `<Authenticator>` component through the [UI repo](https://github.com/aws-amplify/amplify-ui) as shown in the [docs here](https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#internationalization-i18n)
