### ISSUE TITLE
Better typings

### ISSUE THREAD

**Issue by John0x** [aws-amplify/amplify-js#8612]
### Describe the feature you'd like to request

The typings for the aws-amplify js library are lacking in a lot of places, and the lack of support from the aws team is concerning.

See: https://github.com/aws-amplify/amplify-js/issues/4927
There was one response from an official contributor (@sammartinez), which was obviously not helping, to be honest. A lot of projects, nowadays, use typescript and therefore require accurate typings. The issue is older than a year and the problem hasn't even been addressed properly yet, at least from what I've read.

The issue should not have been closed.

### Describe the solution you'd like

Add proper types that accurately match the actual object.

### Describe alternatives you've considered

Writing my own types, which I have. That should not be considered a solution tho

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by aaronmcadam** [comment]
>Describe alternatives you've considered
Writing my own types, which I have. That should not be considered a solution tho

Would you mind sharing your custom types, @John0x?

**Comment by jcuervas** [comment]
I support this feature request, for example, i'm trying to guess what to pass to this Amplify.configure(). According to reference this is what i got:
https://aws-amplify.github.io/amplify-js/api/classes/amplify.html#configure
and this
https://github.com/aws-amplify/amplify-js/blob/a047ce73/packages/core/src/Amplify.ts#L37
Therefore i have no idea how to use this except by researching for some example.

**Comment by aaronmcadam** [comment]
I think it would be good to collect together some of the typings that the community has created to see where the gaps are.

**Comment by cwomack** [comment]
The developer preview for v6 of Amplify has officially been released with improved support for TypeScript and much more! Please check out our [announcement](https://aws.amazon.com/blogs/mobile/aws-amplify-javascripts-new-developer-preview-with-reduced-bundle-sizes-improved-typescript-and-next-js-support/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=238088647) and updated [documentation](https://docs.amplify.aws/lib-v1/project-setup/create-application/q/platform/js/) to see what has changed.

This issue should be resolved within the dev preview and upcoming General Availability for Amplify v6, but let us know with a comment if there are further issues.

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
