### ISSUE TITLE
Latency issues introduces due to need to use /LOGOUT Endpoint to clear out the existing session.

### ISSUE THREAD

**Issue by akashbhandwalkar** [aws-amplify/amplify-js#8625]
### Is this related to a new or existing framework?

React

### Is this related to a new or existing API?

Cache

### Describe the feature you'd like to request

We are using `Auth.faderatedSignIn` to log in the user via Facebook. It gives the us session and we are able to log in the user. If we logout user and try to log in back we get the error from amplify with code "invalid_grant" or code "pre-mutation error". 

When I searched around this issue, we found a solution where if we can clear the cognito session using /GET LOGOUT API, we are able to log in next time successfully.

LOGOUT API - https://docs.aws.amazon.com/cognito/latest/developerguide/logout-endpoint.html

Calling this API is adding latency due to additional redirects. 

### Describe the solution you'd like

In the configuration of the amplify we can add property to set true/false to cache the user session.

```
config = {
     cacheUserSession: false | true
}
```

### Describe alternatives you've considered

By default the SDK will behave considering amplify will cache the session. If configuration has explicitly set it to false then can be ignored. 

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by elorzafe** [comment]
@akashbhandwalkar 

Can you share the library versions and code snippets on how you are using the library?

Curious if you are using `Auth.signOut`

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
