### ISSUE TITLE
Android build fails after changing the distributionUrl gradle version per Push Notifications docs

### ISSUE THREAD

**Issue by omer-to** [aws-amplify/amplify-js#8627]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication, Analytics, Push Notifications

### Amplify Categories

auth, analytics, notifications

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 245.58 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.3/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 91.0.4472.164
    Safari: 14.1.1
  npmGlobalPackages:
    @aws-amplify/cli: 5.1.2
    npm: 6.14.13
    ts-node: 10.1.0
    typescript: 4.3.5
    yarn: 1.22.10

```

</details>

### Describe the bug

I have a React Native project created with the following command using the TypeScript template:

```bash
npx react-native init MyApp --template react-native-template-typescript
```

Following the [official documentation to setup for android](https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/js#setup-for-android) to add push notifications, I changed the distributionUrl from `distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip` to `distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-all.zip`, i.e., the gradle version from **6.7** to **6.3**

However, now when I try to run on Android by executing `yarn android`, the build fails with the following error:

```bash
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.

Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file '~/myapp/node_modules/amazon-cognito-identity-js/android/build.gradle' line: 11

* What went wrong:
A problem occurred evaluating project ':amazon-cognito-identity-js'.
> Failed to apply plugin [id 'com.android.internal.version-check']
   > Minimum supported Gradle version is 6.5. Current version is 6.3. If using the gradle wrapper, try editing the distributionUrl in ~/myapp/android/gradle/wrapper/gradle-wrapper.properties to gradle-6.5-all.zip
```

I had to install `amazon-cognito-identity-js` when I was following the [documentation for adding auth](https://docs.amplify.aws/lib/auth/getting-started/q/platform/js#configure-your-application).

### Expected behavior

The project to build successfully on Android.

### Reproduction steps

1. Create a react native project using node v14.17.3, and npm 6.14.13
```bash
npx react-native init myapp --template react-native-template-typescript
```

2. Install auth packages:
```bash
yarn add aws-amplify amazon-cognito-identity-js @react-native-community/netinfo @react-native-async-storage/async-storage
```

3. Install push notification package:
```bash
yarn add @aws-amplify/pushnotification
```

4. Configure Android following the documentation ( https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/js#setup-for-android ), especially the 8th step where you set the `distributionUrl` as follows:
`distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-all.zip`

5. Start the metro bundler `yarn start --reset-cache`, and then run on Android `yarn android`

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by Samaritan1011001** [comment]
@omer-to Thank you for opening the issue. Can you paste your `package.json` package versions here? Specifically I want to know which `react-native` and `aws-amplify` versions you are using. Thanks!

**Comment by tannerabread** [comment]
Hi @omer-to, I ran through this workflow yesterday and ignored the step about changing the distributionUrl and it worked for me. Can you confirm if this is the case for you as well?

**Comment by tannerabread** [comment]
Hi @omer-to.
I have updated the documentation for proper setup on android for Push Notifications per docs [PR#4939](https://github.com/aws-amplify/docs/pull/4939)

It should be [live here](https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/react-native/#setup-for-android) soon. This should resolve the issues in your original post.

If you find any more errors when working with our library, please feel free to open a new issue.

Thank you!
