### ISSUE TITLE
Sign in with phone_number or email

### ISSUE THREAD

**Issue by ricardoribas** [aws-amplify/amplify-js#8637]
### JavaScript Framework

React Native

### Amplify APIs

Not applicable

### Amplify Categories

auth

### Environment information

Not applicable

</details>

### Describe the bug

I am using a cognito application to authenticate users on the application i am helping to build. The old version was only allowing users to authenticate with the phone number. Happens that right now, we are going to allow users to authenticate through email.

Do we need to have a special care on this topic? Old users have their username in a phone_number format (for instance +351XXXXXXXX) and have one of the attributes as email (for instance example@domain.com). If I try to login with the email for this kind of users, i get a UserNotFoundException. That might be returned as the property username is not the email. In order to solve this issue, i need to create a cognito trigger (pre-signin) that will try to get a user from cognito using email or phone_number? Or i need to have my own authentication endpoint that will try to get a username by a specific phone_number and fallback to a specific attribute?

Additionally, i tried to see if it was a problem of not having one of the properties (phone_number or email) not verified. On my testing environment i've updated the user attributes to have **email_verified** and **phone_verified** to true, but it didn't work as well.

For this particular topics, i might have two use cases:
1 - A user signup with the phone_number and property email
2 - A user signup with the email and property phone_number

### Expected behavior

Should return a user if available

### Reproduction steps

1. Sign up with phone number
2. Add email as an attribute
3. Try to sign in with the phone_number (OK)
4. Logout
5. Try to sign in with the email added as an attribute (NOT OK)

**Comment by ricardoribas** [comment]
As i was not sure if this is a BUG or not, i've added it as a discussion as well [here](https://github.com/aws-amplify/amplify-js/discussions/8630).

**Comment by evcodes** [comment]
Taking a look at this issue @ricardoribas

**Comment by evcodes** [comment]
It looks like you need to configure your user pool to be able to signup/in with username, email or phone number like so:


![](https://i.stack.imgur.com/TNWmt.png)

**Comment by evcodes** [comment]
Please reopen this issue if my comment does not unblock you.
