### ISSUE TITLE
Wrong name in providers's federated signin screen

### ISSUE THREAD

**Issue by marcolino** [aws-amplify/amplify-js#8648]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Environment information

<details>

```
System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    Memory: 200.36 MB / 7.62 GB
    Container: Yes
    Shell: 5.0.17 - /usr/bin/bash
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 7.20.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.107
    Firefox: 87.0
  npmGlobalPackages:
    babel-cli: 6.26.0
    create-react-app: 4.0.3
    eslint: 7.21.0
    html-minifier: 4.0.0
    n: 7.0.0
    npm: 7.20.0
    serverless: 2.28.7


```

</details>

### Describe the bug

Why the (Google in this case) provider's federated signin screen shows "CHOOSE AN ACCOUNT to continue to **amazoncognito.com** ?

I'd expect "CHOOSE AN ACCOUNT to continue to **mydomain.com**" ...

A [screenshot](https://pasteboard.co/Kd8os9S.png) is worth a thousand words...

### Expected behavior

I'd expect "CHOOSE AN ACCOUNT to continue to **mydomain.com**" ...

### Reproduction steps

Just try a federatedSignIn ...

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by tannerabread** [comment]
Hi @marcolino, the redirect flow for HostedUI works by navigating from your app to Cognito Hosted UI, then Google for login and then returning through the Cognito service (Hosted UI) before returning to your app. 

There might be some settings in Google that allow you to show the different domain, but that is not something handled by Amplify. I will close this issue but please open any new issues if you have any other problems with our library.

Thank you!
