### ISSUE TITLE
react-native hard crash on Auth.signOut() when using federated identities

### ISSUE THREAD

**Issue by andreialecu** [aws-amplify/amplify-js#8673]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>
 irrelevant
</details>

### Describe the bug

Using the documentation from the section in "In-App Browser Setup (optional, but recommended)" at: https://docs.amplify.aws/lib/auth/social/q/platform/js#full-samples results in a crash when signing out when authenticated with a federated identity (apple sign in):

```
Exception '*** -[NSURL initWithString:relativeToURL:]: nil string parameter' was thrown while invoking openAuth on target RNInAppBrowser with params (
    "https://....auth.eu-west-2.amazoncognito.com/logout?client_id=49jjijjs1g3lle6of82imj25j0&logout_uri=zzz%3A%2F%2FsignOut",
    "<null>",
        {
        enableDefaultShare = 0;
        enableUrlBarHiding = 1;
        ephemeralWebSession = 0;
        forceCloseOnRedirection = 0;
        showTitle = 0;
    },
    17634,
    17635
)
callstack: (
	0   CoreFoundation                      0x00000001803f7978 __exceptionPreprocess + 236
	1   libobjc.A.dylib                     0x0000000180188800 objc_exception_throw + 56
	2   Foundation                          0x000000018083ac2c -[NSURL(NSURL) _cfurl] + 0
	3   zzz                               0x0000000100c72bc8 -[RNInAppBrowser openAuth:redirectURL:options:resolver:rejecter:] + 480
	4   CoreFoundation                      0x00000001803fe030 __invoking___ + 144
	5   CoreFoundation                      0x00000001803fb384 -[NSInvocation invoke] + 300
	6   CoreFoundation                      0x00000001803fb644 -[NSInvocation invokeWithTarget:] + 76
	7   zzz                               0x0000000100e4d48c -[RCTModuleMethod invokeWithBridge:module:arguments:] + 1752
	8   zzz                               0x0000000100e50c50 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicEiN12_GLOBAL__N_117SchedulingContextE + 1088
	9   zzz                               0x0000000100e50640 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 156
	10  zzz                               0x0000000100e50598 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 28
	11  libdispatch.dylib                   0x0000000180100580 _dispatch_call_block_and_release + 24
	12  libdispatch.dylib                   0x0000000180101d44 _dispatch_client_callout + 16
	13  libdispatch.dylib                   0x000000018010f2f4 _dispatch_main_queue_callback_4CF + 956
	14  CoreFoundation                      0x0000000180365d1c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
	15  CoreFoundation                      0x000000018036025c __CFRunLoopRun + 2448
	16  CoreFoundation                      0x000000018035f3bc CFRunLoopRunSpecific + 572
	17  GraphicsServices                    0x000000018afdd70c GSEventRunModal + 160
	18  UIKitCore                           0x00000001843f03d0 -[UIApplication _run] + 964
	19  UIKitCore                           0x00000001843f51ac UIApplicationMain + 112
	20  zzz                               0x00000001007669bc main + 120
	21  libdyld.dylib                       0x0000000180224554 start + 4
)

RCTFatal
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start
```

The reason for it is that on this line https://github.com/aws-amplify/amplify-js/blob/028e4ee1f7a660ae811b0e1ee846c978958719ae/packages/auth/src/OAuth/OAuth.ts#L294 the second parameter is missing. 

The redirectUri is supposed to be passed as per the contract of the `urlOpener` object. react-native-browser-reborn crashes if `openAuth` is called with a null redirect uri.

### Expected behavior

Should not crash

### Reproduction steps

1) Use code in documentation link:  "In-App Browser Setup (optional, but recommended)" at https://docs.amplify.aws/lib/auth/social/q/platform/js#full-samples
2) Sign in with a federated identity, like an apple account.
3) Sign out.
4) See crash.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

The reason for it is that on this line https://github.com/aws-amplify/amplify-js/blob/028e4ee1f7a660ae811b0e1ee846c978958719ae/packages/auth/src/OAuth/OAuth.ts#L294 the second parameter is missing. 

The redirectUri is supposed to be passed as per the contract of the `urlOpener` object. react-native-browser-reborn crashes if `openAuth` is called with a null redirect uri.

**Comment by Samaritan1011001** [comment]
@andreialecu, the change you suggested is correct. The PR for the same has been merged. Thank you for catching this! 
If you are still experiencing this issue please let us know.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!
