### ISSUE TITLE
Session expire if authenticated at backend

### ISSUE THREAD

**Issue by abhimanusharma** [aws-amplify/amplify-js#8683]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Environment information

<details>

```
# Put output below this line
https://www.npmjs.com/package/amazon-cognito-identity-js

</details>


### Describe the bug

Session expire after 5 minutes when authenticated at backend with idToken `https://www.npmjs.com/package/amazon-cognito-identity-js` with jwt, jwks idToken

### Expected behavior

Token should refresh automatically or option to increase expiration time.

### Reproduction steps

authenticateUser,

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by evcodes** [comment]
Hello @abhimanusharma can you please provide more context?

**Comment by evcodes** [comment]
Hey @abhimanusharma if we cannot get more context from you, we are unable to solve this issue and we will be closing in 3 days.

**Comment by abhimanusharma** [comment]
Code at my nodejs end.

```
const poolData = {
  UserPoolId: conf.userPoolId, // Your user pool id here
  ClientId: conf.clientId, // Your client id here
};
const userPool = new CognitoUserPool(poolData);

const authenticationDetails = new AuthenticationDetails({
  Username: Email,
  Password: Password,
});
const userData = {
  Username: Email,
  Pool: userPool,
};

const newUser = new CognitoUser(userData);

const userAuthCognitoData = new Promise((resolve, reject) => {
  return newUser.authenticateUser(authenticationDetails, {
    onSuccess: result => {
      this.logger.info("SRC:auth.service.authenticateUser", { message: JSON.stringify({
        user: Email,
        msg: "User authenticated"
      }) });
      resolve(result);
    },
    onFailure: err => {
      this.logger.error("SRC:auth.service.authenticateUser", { message: JSON.stringify({
        user: Email,
        err: err.message || err}) });
      reject(err);
    },
  });
});
```

From above code I am getting `idToken, refreshToken, jwtToken` I am using idToken with passport strategy to validate the token with jwk keys. I am able to validate it properly.

```
export class JwtStrategy extends PassportStrategy(Strategy) {
  constructor(private authConfig: AuthConfig) {
    super({
      secretOrKeyProvider: passportJwtSecret({
        cache: true,
        rateLimit: true,
        jwksRequestsPerMinute: 5,
        jwksUri: `${authConfig.get().authority}/.well-known/jwks.json`,
      }),

      jwtFromRequest: ExtractJwt.fromAuthHeaderAsBearerToken(),
      audience: authConfig.get().audience,
      issuer: authConfig.get().authority,
      algorithms: ['RS256'],
    });
  }

  public async validate(payload: any) {
    return !!payload.sub;
  }
}
```

Now if user is trying to access any authenticated api after 5 minutes, his idToken is expired. I could not find any way to increase the expire time as mentioned [here](https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-cognito-user-pools-supports-customization-of-token-expiration/) using https://www.npmjs.com/package/amazon-cognito-identity-js package.

**Comment by chrisbonifacio** [comment]
I'm not sure how to do it through the library, but if you got to the Cognito console -> User Pools -> App Client page you can adjust the expiration time for the ID and other tokens there.

<img width="2229" alt="Screen Shot 2021-08-13 at 2 18 27 PM" src="https://user-images.githubusercontent.com/16952986/129402379-f33ce508-75c1-457f-9015-03cadc41fbfb.png">

**Comment by abhimanusharma** [comment]
I think this will solve my problem temporarily, but I hope there should be a way to refresh idToken with refresh token from nodejs end without forcibly using  amplify.

**Comment by chrisbonifacio** [comment]
@abhimanusharma If you're using Node.js to manage a User Pool, you may want to use the `aws-sdk` from which you can import the CognitoIdentityServiceProvider and call methods like `updateUserPoolClient`. Some of the parameters to such methods include `accessTokenValidity`, which you can use to adjust the length of time.

https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateUserPoolClient.html
