### ISSUE TITLE
Geo: `Geo.searchByText()` w/ `searchAreaConstraints`

### ISSUE THREAD

**Issue by mojodna** [aws-amplify/amplify-js#8690]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Not applicable

### Environment information

n/a

### Describe the bug

In https://docs.amplify.aws/lib/geo/search/q/platform/js#location-based-search-capabilities, `searchAreaConstraints` is doc'd as:

```javascript
searchAreaConstraints: [SWLatitude, SWLongitude, NELatitude, NELongitude]
```

Unless you're transposing coordinates before calling the service, it should be:

```javascript
searchAreaConstraints: [SWLongitude, SWLatitude, NELongitude, NELatitude]
```

(longitude is X, latitude is Y)

### Expected behavior

```javascript
searchAreaConstraints: [SWLongitude, SWLatitude, NELongitude, NELatitude]
```

### Reproduction steps

n/n

**Comment by TreTuna** [comment]
This was a mistake in the types, PR submitted with the fix.

**Comment by Amplifiyer** [comment]
The fix has been released.
