### ISSUE TITLE
Geo: `Geo.searchByCoordinates` coordinate order

### ISSUE THREAD

**Issue by mojodna** [aws-amplify/amplify-js#8691]
### Is this related to another service?

Geo

### Describe the feature you'd like to request

```javascript
Geo.searchByCoordinates([latitudePoint, longitudePoint])
````

is reversed from Amazon Location's [`SearchPlaceIndexForText`](https://docs.aws.amazon.com/location-places/latest/APIReference/API_SearchPlaceIndexForPosition.html).

I recognize that Amplify is an abstraction layer, so this may be intentional, but I wanted to confirm.

### Describe the solution you'd like

Confirmation that this is intentional ;-)

### Describe alternatives you've considered

Since coordinate ordering can be somewhat arbitrary (read https://macwright.com/lonlat/), clearly documenting / highlighting the chosen order would help alleviate any confusion.

FWIW, Amazon Location's opinion on the matter is `lon,lat` (because `x,y`).

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [X] ⚠️ This feature might incur a breaking change

**Comment by TreTuna** [comment]
This was a mistake, PR submitted with the fix.

**Comment by Amplifiyer** [comment]
The fix has been released
