### ISSUE TITLE
Access token is not invalidated even if user account(aws cognito) has been deleted

### ISSUE THREAD

**Issue by yaquawa** [aws-amplify/amplify-js#8693]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I tried to delete the current logged-in user with the following code:

```js
async function deleteUser() {
  const user = await Auth().currentAuthenticatedUser()

  user.deleteUser(async (error: Error, data: string) => {
    if (error) {
      throw error
    }

    await Auth().signOut({ global: true })
    localStorage.clear()

    location.href = '/'
  })
}
```

After I performed the above code,I could confirm that the user account has been deleted, but I could still run graphql mutation via AppSync using the old access token.

### Expected behavior

Invalidate the access token.

### Reproduction steps

x

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hey @yaquawa 👋 thank you for raising this issue. Do you have token revocation enabled in the Cognito User Pool settings?

<img width="699" alt="Screen Shot 2021-08-16 at 3 42 45 PM" src="https://user-images.githubusercontent.com/16952986/129620806-72054625-166d-4ac1-ad11-f7329604e6c0.png">

**Comment by yaquawa** [comment]
Hi @chrisbonifacio , where can I find the option?

**Comment by chrisbonifacio** [comment]
@yaquawa Sorry for the delay, you can find this option by navigating to the Cognito console -> Manage User Pools -> select your User Pool -> App clients -> click Show Details -> Security Configuration

Also, I spoke with the team about this and, at the moment, it is expected behavior for the access token to be valid (for AppSync) until it expires so even after a user deletes their account. This is mentioned in the documentation.

https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js/#global-sign-out

**Comment by yaquawa** [comment]
Hi @chrisbonifacio , thanks for the info.

So even if I have enabled the option [**Enable token revocation**] as you mentioned earlier, the access token for the deleted user is still valid when used with other services like AppSync for 60 minutes?
