### ISSUE TITLE
Getting "UserNotConfirmedException" even when "No Verification" is selected within Cognito

### ISSUE THREAD

**Issue by ayhoung** [aws-amplify/amplify-js#8695]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 11.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 742.97 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.0/bin/yarn
    npm: 7.20.0 - ~/.nvm/versions/node/v14.16.0/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 91.1.26.74
    Chrome: 92.0.4515.107
    Firefox: 89.0.2
    Safari: 14.1.2
  npmPackages:
    @aws-amplify/ui-react: ^1.0.6 => 1.2.7 
    @babel/core: ~7.9.0 => 7.9.6 (7.14.8, 7.9.0)
    @eva-design/eva: ^2.1.0 => 2.1.1 
    @react-native-async-storage/async-storage: ~1.15.0 => 1.15.5 
    @react-native-community/masked-view: 0.1.10 => 0.1.10 
    @react-native-community/netinfo: 6.0.0 => 6.0.0 
    @react-native-community/picker: ^1.8.1 => 1.8.1 
    @react-navigation/bottom-tabs: ^5.11.10 => 5.11.11 
    @react-navigation/native: ^5.9.2 => 5.9.4 
    @react-navigation/stack: ^5.14.2 => 5.14.5 
    @stripe/stripe-react-native: 0.1.1 => 0.1.1 
    @types/jest: ^26.0.23 => 26.0.24 
    @types/react: ~16.9.35 => 16.9.56 (17.0.14)
    @types/react-native: ~0.63.2 => 0.63.52 
    @types/react-test-renderer: ^17.0.1 => 17.0.1 
    @typescript-eslint/eslint-plugin: ^4.25.0 => 4.28.4 
    @typescript-eslint/parser: ^4.25.0 => 4.28.4 
    @ui-kitten/components: ^5.1.0 => 5.1.1 
    @ui-kitten/eva-icons: ^5.1.0 => 5.1.1 
    HelloWorld:  0.0.1 
    aws-amplify: ^3.3.26 => 3.4.3 
    aws-amplify-react: ^4.2.31 => 4.2.35 
    aws-amplify-react-native: ^4.3.2 => 4.3.3 
    bluebird: ^3.7.2 => 3.7.2 
    eslint: ^7.27.0 => 7.31.0 
    eslint-config-airbnb: ^18.2.1 => 18.2.1 
    eslint-config-airbnb-base: ^12.1.0 => 12.1.0 (14.2.1)
    eslint-import-resolver-typescript: ^2.4.0 => 2.4.0 
    eslint-plugin-import: ^2.23.3 => 2.23.4 
    eslint-plugin-jsx-a11y: ^6.4.1 => 6.4.1 
    eslint-plugin-react: ^7.23.2 => 7.24.0 
    eslint-plugin-react-hooks: ^4.2.0 => 4.2.0 
    expo: ^42.0.0 => 42.0.3 
    expo-analytics-amplitude: ~10.2.0 => 10.2.0 
    expo-analytics-segment: ~10.2.1 => 10.2.1 
    expo-av: ~9.2.3 => 9.2.3 
    expo-camera: ~11.2.2 => 11.2.2 
    expo-constants: ~11.0.1 => 11.0.1 
    expo-crypto: ~9.2.0 => 9.2.0 
    expo-firebase-analytics: ~4.1.0 => 4.1.0 
    expo-image-manipulator: ~9.2.2 => 9.2.2 
    expo-image-picker: ~10.2.2 => 10.2.2 
    expo-linking: ~2.3.1 => 2.3.1 
    expo-localization: ~10.2.0 => 10.2.0 
    expo-location: ~12.1.2 => 12.1.2 
    expo-notifications: ~0.12.3 => 0.12.3 
    expo-permissions: ~12.1.1 => 12.1.1 
    expo-screen-orientation: ~3.2.1 => 3.2.1 
    expo-secure-store: ~10.2.0 => 10.2.0 
    expo-status-bar: ~1.0.4 => 1.0.4 
    expo-store-review: ~4.1.0 => 4.1.0 
    expo-updates: ~0.8.1 => 0.8.2 
    firebase: 8.2.3 => 8.2.3 
    firebase/analytics:  undefined ()
    firebase/app:  undefined ()
    firebase/auth:  undefined ()
    firebase/database:  undefined ()
    firebase/firestore:  undefined ()
    firebase/firestore/bundle:  undefined ()
    firebase/firestore/memory:  undefined ()
    firebase/functions:  undefined ()
    firebase/installations:  undefined ()
    firebase/messaging:  undefined ()
    firebase/performance:  undefined ()
    firebase/remote-config:  undefined ()
    firebase/storage:  undefined ()
    hermes-inspector-msggen:  1.0.0 
    i18n-js: ^3.8.0 => 3.8.0 
    react: 16.13.1 => 16.13.1 
    react-animated:  0.1.0 
    react-dom: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-fast-image: ^8.3.6 => 8.3.6 
    react-native-flatlist-slider: ^1.0.5 => 1.0.5 
    react-native-gesture-handler: ~1.10.2 => 1.10.3 
    react-native-keyboard-aware-scroll-view: ^0.9.4 => 0.9.4 
    react-native-maps: 0.28.0 => 0.28.0 
    react-native-markdown-display: ^7.0.0-alpha.2 => 7.0.0-alpha.2 
    react-native-safe-area-context: 3.2.0 => 3.2.0 
    react-native-screens: ~3.4.0 => 3.4.0 
    react-native-svg: 12.1.1 => 12.1.1 
    react-native-unimodules: ~0.14.5 => 0.14.6 
    react-native-vector-icons: ^8.0.0 => 8.1.0 
    react-native-web: ~0.13.12 => 0.13.18 
    react-redux: ^7.2.2 => 7.2.4 
    redux: ^4.0.5 => 4.1.0 
    redux-promise-middleware: ^6.1.2 => 6.1.2 
    redux-thunk: ^2.3.0 => 2.3.0 
    tslint: ^6.1.3 => 6.1.3 
    type-to-reducer: ^1.2.0 => 1.2.0 
    typescript: ~4.0.0 => 4.0.8 
    underscore: ^1.12.0 => 1.13.1 
    unimodules-permissions-interface: ~6.1.0 => 6.1.0 
  npmGlobalPackages:
    @aws-amplify/cli: 5.2.1
    amplify-cli: 1.0.0
    amplify: 0.0.11
    eas-cli: 0.21.0
    eslint: 7.27.0
    expo-cli: 4.9.1
    expo: 41.0.1
    nodemon: 2.0.12
    npm: 7.20.0
    react-native: 0.64.1
    react: 17.0.1
    tslint: 6.1.3
    typescript: 4.2.4
    yarn: 1.22.10

```

</details>

### Describe the bug

I'm trying to allow users to directly sign-in after sign-up without requiring email confirmations.

I've configured the below in Cognito:
![Screen Shot 2021-08-03 at 7 41 55 PM](https://user-images.githubusercontent.com/308375/128009582-cf72e9db-8e12-427a-ae81-e944e714c9f5.jpg)

But still getting the below error:
```
Object {
  "code": "UserNotConfirmedException",
  "message": "User is not confirmed.",
  "name": "UserNotConfirmedException",
}
```

### Expected behavior

User should be allowed to sign in without confirmation of email address

### Reproduction steps

1. Use Auth API
2. Signup with Email
3. Signin with Email

### Code Snippet

```javascript
await Auth.signUp({
      username: email,
      password: password,
});
 const user = await Auth.signIn(email, password);
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by fkunecke** [comment]
I solved this by using a `PreSignup` lambda trigger. Here is some code to get you started:

index.js:

```
/*
  this file will loop through all js modules which are uploaded to the lambda resource,
  provided that the file names (without extension) are included in the "MODULES" env variable.
  "MODULES" is a comma-delimmited string.
*/
const moduleNames = process.env.MODULES.split(',');
const modules = moduleNames.map(name => require(`./${name}`));


// from https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-sign-up.html#aws-lambda-triggers-pre-registration-example-2
// automatically approves every new account created.
// Note that this supresses the confirmation code emails.
exports.handler = (event, context, callback) => {

  // Confirm the user
      event.response.autoConfirmUser = true;

  // Set the email as verified if it is in the request
  if (event.request.userAttributes.hasOwnProperty("email")) {
      event.response.autoVerifyEmail = true;
  }

  // Set the phone number as verified if it is in the request
  if (event.request.userAttributes.hasOwnProperty("phone_number")) {
      event.response.autoVerifyPhone = true;
  }

  // Return to Amazon Cognito
  callback(null, event);
};

```

Then, I have a Profile model in my GraphQL schema with a `verified: Boolean` property that I check and show some 'verification required' UI. If you need more help tag me and I will try to get back to you, I have this working in production.

**Comment by ayhoung** [comment]
thanks @fkunecke ~ i'd still rather see if this can be fixed because the workaround shouldn't be necessary

**Comment by chrisbonifacio** [comment]
Hey @ayhoung 👋 thanks for raising this issue. I was able to reproduce this consistently (first try really). Unfortunately this seems to be more of an issue with Cognito rather than Amplify but I'll bring this to the team's attention and see if I can get some feedback on it. Until then, I've labeled this as a bug. I will report back when I get a response from the Cognito team.

Thanks again!

**Comment by ayhoung** [comment]
Thanks @chrisbonifacio !

**Comment by chrisbonifacio** [comment]
@ayhoung No problem! So, I spoke to someone on the Auth team and, as it turns out, @fkunecke had the right idea and is actually the recommended way to handle this verification option.

The `No verification` option within the Cognito User Pool settings is not for omitting the need to verify/confirm users. The way it was intended to work is that the customer would decide when to confirm and/or verify a user's contact information rather than letting Cognito do it for them.

From the [documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/signing-up-users-in-your-app.html#allowing-users-to-sign-up-and-confirm-themselves)

> None
> If you choose this option, Amazon Cognito doesn't send verification codes when users sign up. Choose this option if you are using a custom authentication flow that verifies at least one contact method without using verification codes from Amazon Cognito. For example, you might use a pre sign-up Lambda trigger that automatically verifies email addresses that belong to a specific domain.
> 
> If you don't verify your users' contact information, they might be unable to use your app in some cases. Remember that users require verified contact information to:
> 
> Reset their passwords. When a user does an action in your app that calls the ForgotPassword API action, Amazon Cognito sends a temporary password to the user's email address or phone number. Amazon Cognito sends this password only if the user has at least one verified contact method.
> 
> Sign in by using an email address or phone number as an alias. If you configure your user pool to allow these aliases, then a user can sign in with an alias only if the alias is verified. For more information, see Overview of Aliases.

**Comment by ayhoung** [comment]
@chrisbonifacio thanks for the response - i'll proceed with the workaround then thank you.
