### ISSUE TITLE
GraphQL update query not working

### ISSUE THREAD

**Issue by asatvilker** [aws-amplify/amplify-js#8704]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 11.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 811.55 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.5 - /usr/local/bin/node
    npm: 6.14.11 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.107
    Edge: 91.0.864.54
    Firefox: 85.0.2
    Safari: 14.0.3
  npmPackages:
    @aws-amplify/ui-react: ^0.2.14 => 0.2.14 
    @testing-library/jest-dom: ^4.2.4 => 4.2.4 
    @testing-library/react: ^9.5.0 => 9.5.0 
    @testing-library/user-event: ^7.2.1 => 7.2.1 
    aws-amplify: ^3.0.17 => 3.0.17 
    aws-sdk: ^2.735.0 => 2.735.0 
    mdbreact: ^4.27.0 => 4.27.0 
    node-sass: ^4.14.1 => 4.14.1 
    react: ^16.13.1 => 16.13.1 
    react-circular-progressbar: ^2.0.3 => 2.0.3 
    react-dom: ^16.13.1 => 16.13.1 
    react-hook-form: ^6.0.4 => 6.0.4 
    react-markdown: ^4.3.1 => 4.3.1 
    react-router-hash-link: ^1.2.2 => 1.2.2 
    react-scripts: 3.4.1 => 3.4.1 
    react-typewriting-effect: ^1.0.3 => 1.0.3 
    react-typist: ^2.0.5 => 2.0.5 
    update-json-file: ^1.1.1 => 1.1.1 
  npmGlobalPackages:
    @aws-amplify/cli: 4.43.0
    create-react-app: 3.4.1
    gatsby-cli: 2.19.1
    mdb-cli: 1.1.34
    npm: 6.14.11
    test: 0.6.0

```

</details>

### Describe the bug

When running a graphQL update query, the query does not return an error however it is not updating the item. The result of the query is not an error but if you look at the values meant to have been updated, they are still the same and the updatedAt timestamp has also not changed.

<img width="1622" alt="Screenshot 2021-08-04 at 11 21 11" src="https://user-images.githubusercontent.com/56475258/128166200-51ddcca9-6b18-4c7e-be28-2d02b711ecfb.png">

### Expected behavior

The query should update the values specified

### Reproduction steps

setup a graphQL api from the amplify cli in your project

then go to the AWS console -> appsync  -> select your api -> queries

in the editor run a similar update query as shown below. As you can see it does not return an error but it is not updating the title, the result shows the title is still 'Python' not 'PythonUpdated'

<img width="1622" alt="Screenshot 2021-08-04 at 11 21 11" src="https://user-images.githubusercontent.com/56475258/128165276-a7bce57e-ecda-4716-87fe-14a646908207.png">

### Code Snippet

```javascript
// Put your code below this line.
mutation MyMutation5 {
  updatePortfolioCategory(input: {id: "8661eb26-11d6-4be3-a71c-b314e0d5ff43", topic: "PythonUpdated"}) {
    topic
    updatedAt
  }
}

```

### Log output

<details>

```
// Put your logs below this line
179ddcf3-425d-4845-bc8a-581cef60bbef Begin Request
179ddcf3-425d-4845-bc8a-581cef60bbef Conflict Resolution flow:{"conflictType":"Conflict encountered on version mismatch between client and server. Server had an item version of \u002720\u0027.","conflictHandlerConfigured":"AUTOMERGE","message":"AUTOMERGE was executed on the conflicting items.","data":{"__typename":"REJECTED","topic":"REJECTED","updatedAt":"REJECTED"},"syncAttempt":1}
{
  "duration": 88836822,
  "logType": "ExecutionSummary",
  "requestId": "179ddcf3-425d-4845-bc8a-581cef60bbef",
  "startTime": "2021-08-04T12:25:11.202996Z",
  "endTime": "2021-08-04T12:25:11.291832Z",
  "parsing": {
    "startOffset": 272202,
    "duration": 262979
  },
  "version": 1,
  "validation": {
    "startOffset": 714300,
    "duration": 438891
  },
  "graphQLAPIId": "ryxjza6hxrghzbtfyulwra67qy"
}
{
  "logType": "RequestSummary",
  "requestId": "179ddcf3-425d-4845-bc8a-581cef60bbef",
  "graphQLAPIId": "ryxjza6hxrghzbtfyulwra67qy",
  "statusCode": 200,
  "latency": 106365000
}
179ddcf3-425d-4845-bc8a-581cef60bbef End Request
```

</details>

**Comment by chrisbonifacio** [comment]
Hey @asatvilker 👋 Are you using DataStore in your app? Also, are you experiencing the same behavior when updating records from your application or is this only happening on the AppSync console?

**Comment by chrisbonifacio** [comment]
Well, I was able to reproduce this pretty quickly. Will look into this further and bring it to the team's attention. Thank you!

<img width="1528" alt="Screen Shot 2021-08-04 at 11 45 29 AM" src="https://user-images.githubusercontent.com/16952986/128212083-71b05e3d-6ff5-4bf1-8f92-9d070a97d28c.png">

**Comment by chrisbonifacio** [comment]
Spoke to a member of the AppSync team today about this issue and, as it turns out, you simply need to include the `_version` of the record you're trying to update. If you take a look at the graphql queries DataStore makes in the browser, you can see it included in the variables.

False alarm! 😅 haha

<img width="1135" alt="Screen Shot 2021-08-04 at 5 20 40 PM" src="https://user-images.githubusercontent.com/16952986/128256510-ed519339-0769-4ede-a553-09f04adcf2a5.png">

In the AppSync console

<img width="1619" alt="Screen Shot 2021-08-04 at 5 24 40 PM" src="https://user-images.githubusercontent.com/16952986/128256920-d31e8362-8457-4414-b404-09d860dead7e.png">

**Comment by asatvilker** [comment]
I see, thank you for your help, just wondering if its possible to remove data store then as this is more problematic? I tried using the amplify cli to update api -> graphQL -> remove data store from api. However then the queries dont work at all? Is there anyway to reverse the use of data store back to how it was? I just enabled data store i didn’t actively start using it so sort of no point having it. Thanks again for the support

**Comment by chrisbonifacio** [comment]
Hey @asatvilker. DataStore would automatically include the version of the record being updated when it triggers the GraphQL mutations from your application. What behavior are you seeing when attempting perform queries through the AppSync console? I just tried disabling DataStore for my app (be sure to run `amplify push` after doing so), and it seems to have just removed the `_version`, `_lastChangedAt`, etc fields but I am still able to query the data.

<img width="1270" alt="Screen Shot 2021-08-05 at 5 19 02 PM" src="https://user-images.githubusercontent.com/16952986/128422585-7f2be711-0083-42d6-8730-c560c5ca1dbd.png">

**Comment by chrisbonifacio** [comment]
Looking over your environment information it seems you're behind on amplify updates. Is there a reason you haven't upgraded your packages to v4 and/or the CLI to v5?

**Comment by asatvilker** [comment]
Hi @chrisbonifacio . I did the same to disable and also I did run amplify push. However when running an update mutation on appsync it would return an error. The error is essentially saying that it is looking for the _version but of course that has been removed.

I haven’t done any updates, haven’t used amplify in a while ahaha. Perhaps that is the reason!

**Comment by chrisbonifacio** [comment]
@asatvilker We have these pages to help with upgrading the CLI and packages respectively.

https://docs.amplify.aws/cli/usage/upgrade

https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js

Let me know if updating helps! Otherwise, we can continue to work to get you in a working state 😄

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!
