### ISSUE TITLE
DataStore.update sync only first time

### ISSUE THREAD

**Issue by mimccio** [aws-amplify/amplify-js#8726]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

DataStore

### Amplify Categories

auth, api

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

When updating it sync only the first time with the server. If we try to update again the same object it won't sync.

### Expected behavior

It should update every time not only the first time.

### Reproduction steps

DataStore.save()

### Code Snippet

```javascript
const updatedItem= await DataStore.save(
        ItemModel.copyOf(item, (updated) => {
          updated.name = newName
        })
      )

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by OkkarMin** [comment]
Hey @mimccio I see that you have closed the issue.

Were you able to figure out and solve the issue? I am having the EXACT same issue over in my own project

Thank you!
