### ISSUE TITLE
Custom Forms: How to Access Error Message and IsFetching status

### ISSUE THREAD

**Issue by luke-unifymonitor** [aws-amplify/amplify-js#873]
Hi.

Feature Request - If not already possible :)

I'd like to be able to access the error message in my custom form? Rather than have the error message displayed at the bottom of the form as is by default, I would like to be able to get access to it via props or state, then display it within the form itself.  Apologies if I'm missing something already available.

Also, it would be good to give the user some <Spinner/> feedback when submitting a form.  Would it be possible to add a Fetching or Loading status to the prop?

`import React from "react"
import { SignIn as AmpSignIn } from "aws-amplify-react"
import { I18n } from "aws-amplify"

class SignIn extends AmpSignIn {
  showComponent(themeIn) {
    const { error, fetching } = this.state (or this.props) // SOMETHING LIKE THIS WOULD BE IDEAL
    return (<div>
      Sign In
        {error && <div>{error}</div>}
        {fetching && <div>Loading</div>}
        <input
        type="text"
        id="username"
        key="username"
        name="username"
        placeholder={I18n.get("Username")}
        onChange={this.handleInputChange}
      />
      <input
        type="password"
        id="password"
        key="password"
        name="password"
        placeholder={I18n.get("Password")}
        onChange={this.handleInputChange}
      />
      <button disabled={fetching} onClick={this.signIn}>
        {I18n.get("Sign In")}
      </button>
      <button onClick={() => this.changeState('forgotPassword')}>
        {I18n.get("Forgot Password")}
      </button>
      <button onClick={() => this.changeState('confirmSignUp')}>
        {I18n.get("Confirm a Code")}
      </button>
    </div>
    )
  }
}

export default SignIn`

**Comment by luke-unifymonitor** [comment]
Looking here:

https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify-react/src/Auth/Authenticator.jsx#L110 

I'm guessing the error needs to be included in the call to cloneElement

**Comment by jordanranz** [comment]
Hello there. Thanks for submitting feedback.

I am a little confused at what you are asking, so I have a few questions/comments here:
- Would this be for sign in or sign up or both?
- Are you using Amplify's Auth category to implement your sign in/sign up interaction?
- Showing a 'loading' or 'error' state depends on the interaction with your Auth provider and can be implemented by setting state within that interaction. If you are using Amplify Auth you could implement a 'loading' and/or 'error' state using the signIn or signUp promises documented here:
https://aws.github.io/aws-amplify/media/authentication_guide#sign-in

**Comment by jameswestbv** [comment]
I'm struggling a bit with this too.

I can see how to customise each component SignIn, SignOut, ForgotPassword etc

But for errors I can't see how you customise it - the <Toast></Toast> seems to be the only way it will display it?

Is the only way to override the whole render() of Authenticator and build a custom one?
