### ISSUE TITLE
Following CONTRIBUTING.md guidelines doesn't build correctly when running in watch mode

### ISSUE THREAD

**Issue by jagonzalr** [aws-amplify/amplify-js#8747]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Not applicable

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line

  System:
    OS: macOS 11.5.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 3.66 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.5 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
  npmPackages:
    @babel/cli: ^7.0.0 => 7.14.8
    @babel/core: ^7.0.0 => 7.15.0 (7.9.0, 7.9.0, 7.9.0, 7.9.0, 7.12.9, 7.9.0, 7.9.0, 7.9.0, 7.12.9)
    @babel/preset-env: ^7.0.0 => 7.15.0 (7.3.4, 7.9.0)
    @babel/preset-react: ^7.0.0 => 7.14.5 (7.9.1)
    @types/blob-util:  1.3.3
    @types/bluebird:  3.5.29
    @types/chai:  4.2.7
    @types/chai-jquery:  1.1.40
    @types/jest: ^24.0.18 => 24.9.1
    @types/jquery:  3.3.31
    @types/lodash:  4.14.149
    @types/minimatch:  3.0.3
    @types/mocha:  5.2.7
    @types/node: ^8.9.5 => 8.10.66 (16.6.0, 16.6.0, 16.6.0, 16.6.0, 16.6.0, 16.6.0)
    @types/puppeteer: 1.3.0 => 1.3.0
    @types/sinon:  7.5.1
    @types/sinon-chai:  3.2.3
    babel-loader: ^8.0.0 => 8.2.2 (8.1.0)
    bundlewatch: ^0.3.1 => 0.3.2
    codecov: ^3.6.5 => 3.8.3
    compression-webpack-plugin: ^1.1.3 => 1.1.12
    cypress: ^3.2.0 => 3.8.3
    husky: ^3.0.5 => 3.1.0
    jest: ^24.x.x => 24.9.0
    jest-config: 24.8.0 => 24.8.0 (24.9.0, 24.9.0)
    json-loader: ^0.5.7 => 0.5.7
    lerna: ^3.13.1 => 3.22.1
    prettier: ^1.19.0 => 1.19.1
    pretty-quick: ^1.11.1 => 1.11.1
    rimraf: ^2.6.2 => 2.7.1 (2.6.3, 2.2.8)
    rollup: ^0.67.4 => 0.67.4
    rollup-plugin-commonjs: ^9.2.0 => 9.3.4
    rollup-plugin-json: ^3.1.0 => 3.1.0
    rollup-plugin-node-resolve: ^4.0.0 => 4.2.4
    rollup-plugin-sourcemaps: ^0.4.2 => 0.4.2
    rollup-plugin-typescript: ^1.0.0 => 1.0.1
    source-map-loader: ^0.2.1 => 0.2.4
    ts-jest: ^24.x.x => 24.3.0
    tslint: ^5.7.0 => 5.20.1
    tslint-config-airbnb: ^5.8.0 => 5.11.2
    typedoc: ^0.16.9 => 0.16.11
    typescript: ~3.7.7 => 3.7.7
    uglifyjs-webpack-plugin: ^0.4.6 => 0.4.6
    uuid-validate: ^0.0.3 => 0.0.3
    webpack: ^4.32.0 => 4.46.0
    webpack-bundle-analyzer: ^3.3.2 => 3.9.0
    webpack-cli: ^3.1.0 => 3.3.12
    winston: ^3.2.1 => 3.3.3
  npmGlobalPackages:
    @aws-amplify/cli: 4.11.0
    @aws-amplify/ui-react: 1.2.8
    expo-cli: 3.21.12
    gatsby-cli: 2.12.7
    generator-serverless-policy: 2.0.0
    npm: 6.14.14
    prettier: 1.19.1
    react-native-cli: 2.0.1
    serve: 11.3.2
    serverless: 1.78.1
    yo: 2.0.5
```

</details>

### Describe the bug

I followed the guidelines in `CONTRIBUTING.md` and run the following

```
git clone git@github.com:[username]/amplify-js.git
cd amplify-js

yarn
yarn bootstrap
```

After that I ran

```
yarn build # Build the whole library
yarn link-all # Make all the packages available to link
yarn build:esm:watch # All packages are building ES6 modules in watch mode
```

`yarn build` and `yarn link-all` worked correctly

![Screenshot 2021-08-12 at 10 48 01](https://user-images.githubusercontent.com/3858265/129185197-98c00f96-d99b-4e54-b7eb-3ecfcb1d70f5.png)

![Screenshot 2021-08-12 at 10 48 20](https://user-images.githubusercontent.com/3858265/129185209-971847af-0266-4ebc-a38b-44764e0b7632.png)

But when running `yarn build:esm:watch` several packages fail because it can't find some modules.
I'm looking specifically at `@aws-amplify/ui-react` because I'm interested in making a PR for that package.

Currently it throws 58 errors similar to `Cannot find module '@aws-amplify/ui-components` or `Cannot find module '@aws-amplify/ui-components/loader'`

![Screenshot 2021-08-12 at 11 55 38](https://user-images.githubusercontent.com/3858265/129185533-fcc62dbf-e823-46a4-9160-a2bd762c042e.png)

![Screenshot 2021-08-12 at 11 55 59](https://user-images.githubusercontent.com/3858265/129185546-324db1ac-c3a1-4727-bccb-70f02c59fc6a.png)

Is there an extra step that I'm missing?

### Expected behavior

Running amplify packages locally in watch mode should run without errors.

### Reproduction steps

```
git clone git@github.com:[username]/amplify-js.git
cd amplify-js

yarn
yarn bootstrap
yarn build # Build the whole library
yarn link-all # Make all the packages available to link
yarn build:esm:watch # All packages are building ES6 modules in watch mode
```

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @jagonzalr 👋 Thanks for raising this issue. Some errors are expected along the build process in watch mode because packages are being built/re-built. However, it may take a bit but it should eventually get to a point where there are no errors found and it is just watching for new changes. Is this the case for you? If so, when making changes it will then detect them and recompile, displaying errors if any.

<img width="748" alt="Screen Shot 2021-08-18 at 2 46 30 PM" src="https://user-images.githubusercontent.com/16952986/129956932-22ec7665-bf4a-4da6-8f19-b3e876c99a73.png">

**Comment by jagonzalr** [comment]
Hi @chrisbonifacio I tried again and it still throws errors on any change I make.

https://user-images.githubusercontent.com/3858265/130031028-0b7d4971-deee-4a08-b69f-dc63756eb16f.mp4

Then I try to link `@aws-amplify/ui-react` to my sample project

```
System:
    OS: macOS 11.5.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 418.19 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.5 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
  npmPackages:
    @aws-amplify/ui-react: ^1.2.8 => 1.2.9 
    @popperjs/core: ^2.9.2 => 2.9.3 
    @testing-library/jest-dom: ^5.11.4 => 5.14.1 
    @testing-library/react: ^11.1.0 => 11.2.7 
    @testing-library/user-event: ^12.1.10 => 12.8.3 
    autoprefixer: ^9.8.6 => 9.8.6 
    aws-amplify: ^4.2.2 => 4.2.3 
    bootstrap: ^5.0.2 => 5.1.0 
    bootstrap-icons: ^1.5.0 => 1.5.0 
    husky: ^7.0.0 => 7.0.1 
    node-sass: ^6.0.1 => 6.0.1 
    prettier: ^2.3.2 => 2.3.2 
    pretty-quick: ^3.1.1 => 3.1.1 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    react-scripts: 4.0.3 => 4.0.3 
    redux-logger: ^3.0.6 => 3.0.6 
    workbox-background-sync: ^5.1.3 => 5.1.4 
    workbox-broadcast-update: ^5.1.3 => 5.1.4 
    workbox-cacheable-response: ^5.1.3 => 5.1.4 
    workbox-core: ^5.1.3 => 5.1.4 
    workbox-expiration: ^5.1.3 => 5.1.4 
    workbox-google-analytics: ^5.1.3 => 5.1.4 
    workbox-navigation-preload: ^5.1.3 => 5.1.4 
    workbox-precaching: ^5.1.3 => 5.1.4 
    workbox-range-requests: ^5.1.3 => 5.1.4 
    workbox-routing: ^5.1.3 => 5.1.4 
    workbox-strategies: ^5.1.3 => 5.1.4 
    workbox-streams: ^5.1.3 => 5.1.4 
  npmGlobalPackages:
    @aws-amplify/cli: 4.11.0
    @aws-amplify/ui-react: 1.2.8
    expo-cli: 3.21.12
    gatsby-cli: 2.12.7
    generator-serverless-policy: 2.0.0
    npm: 6.14.14
    prettier: 1.19.1
    react-native-cli: 2.0.1
    serve: 11.3.2
    serverless: 1.78.1
    yo: 2.0.5
```

And I get an error that my Amplify project is not setup correctly.

<img width="631" alt="Screenshot 2021-08-19 at 08 55 40" src="https://user-images.githubusercontent.com/3858265/130030734-58aaa024-53ec-4fef-8d71-b8dc93138f91.png">

If I unlink `@aws-amplify/ui-react` my project runs correctly.

**Comment by chrisbonifacio** [comment]
@jagonzalr could you try to replace the `yarn build:esm:watch` command with `yarn build:watch` instead? Let me know if that helps at all. The issue seems to stem from the ui component libraries, the UI team is aware and trying to address the issue. Apologies for the inconvenience.

**Comment by jagonzalr** [comment]
@chrisbonifacio so `yarn build` runs fine without errors. I tried `yarn build:watch` and returns the same errors as `yarn build:esm:watch`. If I want to write code I would need to run `yarn build` to see my changes instead of just automatically reloading.

**Comment by chrisbonifacio** [comment]
@jagonzalr you could also try to scope the watch mode to the package you're working on like so `yarn build:esm:watch --scope <package-name>`.

**Comment by jagonzalr** [comment]
@chrisbonifacio if I do that and run `yarn build:esm:watch --scope @aws-amplify/ui-react --stream` I get no errors but changing a file inside `ui-components` doesn't cause a rebuild on `ui-react`. Do I need to scope on `@aws-amplify/ui-components` instead? 

What I install on my sample project is `aws-amplify` and `@aws-amplify/ui-react`. 

If I run `yarn build:esm:watch --scope @aws-amplify/ui-components --stream` it doesn't throw errors. Should I do then `yarn link @aws-amplify/ui-components` in my sample project?

**Comment by chrisbonifacio** [comment]
@jagonzalr sorry for the delayed response. Were you able to make the changes you needed?

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!
