### ISSUE TITLE
(Nextjs SSR) Requests from server-side are many times slower than from the client-side

### ISSUE THREAD

**Issue by dn-l** [aws-amplify/amplify-js#8751]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 11.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.74 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.2.1 - ~/.nvm/versions/node/v15.2.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v15.2.1/bin/yarn
    npm: 7.17.0 - ~/.nvm/versions/node/v15.2.1/bin/npm
  Browsers:
    Brave Browser: 92.1.27.111
    Chrome: 92.0.4515.131
    Firefox: 90.0.2
    Safari: 14.1.2
  npmGlobalPackages:
    @aws-amplify/cli: 5.3.0
    @commitlint/cli: 12.1.4
    @commitlint/config-conventional: 12.1.4
    aws-cdk: 1.114.0
    localtunnel: 2.0.1
    npm-check-updates: 11.7.1
    npm: 7.17.0
    typescript: 4.3.5
    yarn: 1.22.10

```

</details>

### Describe the bug

Reference: https://github.com/vercel/next.js/discussions/22778

API (AppSync) requests from `getServerSideProps` with `withSSRContext` are 2-3 times slower than from the client-side `import { API } from 'aws-amplify'`. I'm getting 600-800ms currently and it is unacceptable.

I don't have any problems with requests from the client side (similar requests, 100-150ms).

The query is very basic, DynamoDB table doesn't have much data.

How I measure?

```tsx
import { performance } from "perf_hooks"

...


  const start = performance.now()
  const { data } = (await API.graphql({
    query: getProfile,
    variables: {
      ...
    }
  })) as GraphQLResult<Record<"getProfile", Profile>>
  const end = performance.now()
```

My connection is not a problem: avg ping to {app}.appsync-api.us-east-2.amazonaws.com ~ 6-8 ms

### Expected behavior

100-150ms

### Reproduction steps

1. Create a page
2. Add `export const getServerSideProps = ...`
3. Use `const { API } = withSSRContext(context)`
4. Make a request inside `getServerSideProps` and measure the time

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @dn-l 👋 Thanks for raising this issue. There isn't any difference in implementation between `API.graphql` on the client and the server. 

The only reason for a disparity between client/server performance is the difference region or distance between the client and the hosting service to AppSync/DynamoDB. Are you experiencing this during local development or on a deployed app?

I tried benchmarking with the same library (perf_hooks) on my server vs the client (window.performance). 
These were my results.

**Server**

Code

```js
export async function getServerSideProps(context) {
  const { API } = withSSRContext(context);

  try {
    console.log("Getting programs...");
    const start = performance.now();
    const res = await API.graphql(graphqlOperation(listPrograms));
    const end = performance.now();
    console.log("Server Perf:", end - start);
    console.log({ data: res.data.listPrograms });
  } catch (error) {
    console.log("Error getting programs: ", error);
  }

  return { props: {} };
}
```
Result

<img width="438" alt="Screen Shot 2021-08-18 at 4 51 44 PM" src="https://user-images.githubusercontent.com/16952986/129971044-390e37d2-dec9-457e-9cd1-af79d08047e6.png">

---------------------------------------------------------------------------------------------------------------

**Client**

Code

```js
  useEffect(() => {
    getProgram();
  }, []);

  async function getProgram() {
    try {
      console.log("Getting programs...");
      const start = window.performance.now();
      const res = await API.graphql(graphqlOperation(listPrograms));
      const end = window.performance.now();
      console.log("Client Perf:", end - start);
      console.log({ data: res.data.listPrograms });
    } catch (error) {
      console.log("Error getting programs: ", error);
    }
  }
  ```
  
  Result
  
<img width="1302" alt="Screen Shot 2021-08-18 at 4 54 28 PM" src="https://user-images.githubusercontent.com/16952986/129971346-8a4849d6-84c6-46af-8400-0c71368a098d.png">

**Comment by dn-l** [comment]
@chrisbonifacio hello
Thanks for the effort! I experience slow response in `getServerSideProps` both locally and on the server. Locally it can easily reach 800-1000ms while client request is just less than 200. Any possible recommendations? What should I check? Can you share your test application credentials so I could check it locally? I'm on the Discord DL#8722

**Comment by dn-l** [comment]
Somehow it got fixed and as fast as it should be now. Closed.
Thanks @chrisbonifacio
