### ISSUE TITLE
Graphql Subscription firing multiple times

### ISSUE THREAD

**Issue by rexwreyes** [aws-amplify/amplify-js#8755]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 761.16 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.77
    Firefox Developer Edition: 91.0
    Safari: 14.0.2
  npmPackages:
    @aws-amplify/ui-react: ^1.0.3 => 1.0.3 
    @date-io/moment: ^1.3.13 => 1.3.13 
    @material-ui/core: ^4.11.3 => 4.11.3 
    @material-ui/data-grid: ^4.0.0-alpha.22 => 4.0.0-alpha.22 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.57 
    @material-ui/pickers: ^3.2.10 => 3.2.10 
    @reduxjs/toolkit: ^1.5.1 => 1.5.1 
    @testing-library/jest-dom: ^5.11.9 => 5.11.9 
    @testing-library/react: ^11.2.5 => 11.2.5 
    @testing-library/user-event: ^12.7.3 => 12.7.3 
    aws-amplify: ^3.3.21 => 3.3.21 
    aws-amplify-react: ^4.2.25 => 4.2.25 
    aws-appsync: ^4.0.3 => 4.0.3 
    aws-appsync-react: ^4.0.3 => 4.0.3 
    clsx: ^1.1.1 => 1.1.1 
    graphql: ^15.5.0 => 15.5.0 (14.0.0, 0.13.0)
    graphql-tag: ^2.11.0 => 2.11.0 
    isomorphic-fetch: ^3.0.0 => 3.0.0 
    lodash: ^4.17.21 => 4.17.21 
    moment: ^2.29.1 => 2.29.1 
    prop-types: ^15.7.2 => 15.7.2 
    react: ^17.0.1 => 17.0.1 
    react-apollo: ^3.1.5 => 3.1.5 
    react-big-calendar: ^0.33.2 => 0.33.2 
    react-dom: ^17.0.1 => 17.0.1 
    react-number-format: ^4.5.1 => 4.5.1 
    react-redux: ^7.2.3 => 7.2.3 
    react-router-dom: ^5.2.0 => 5.2.0 
    react-scripts: 4.0.3 => 4.0.3 
    recharts: ^2.0.8 => 2.0.8 
    redux: ^3.7.2 => 3.7.2 (4.0.5)
    redux-promise-middleware: ^4.4.2 => 4.4.2 
    redux-thunk: ^2.3.0 => 2.3.0 
    semantic-ui-react: ^2.0.3 => 2.0.3 
    styled-components: ^5.2.1 => 5.2.1 
    styled-components/macro:  undefined ()
    styled-components/native:  undefined ()
    styled-components/primitives:  undefined ()
    uuid: ^8.3.2 => 8.3.2 (3.4.0, 3.3.2)
    web-vitals: ^1.1.0 => 1.1.0 
  npmGlobalPackages:
    @aws-amplify/cli: 4.44.1
    npm: 6.14.11
    yarn: 1.22.11

```

</details>

### Describe the bug

I am building an app for event planners.  When they create an event, i have a graphql subscription that calls a function to create a "quote" record with a relationship to that event.  It works but a random amount multiple quotes with all the same data (except for the ID) get created. 

### Expected behavior

I want only one Quote record to get created.

### Reproduction steps

When a subscription for **createEvent** graphql mutation triggers createQuote.

### Code Snippet

```javascript
 useEffect(() => {
   const subscription = API.graphql( graphqlOperation(subscriptions.onCreateEvent) ).subscribe({
      next: ({ provider, value }) => addQuote(value.data.onCreateEvent),
      error: error => console.warn(error)
    });    
    subscription.unsubscribe()
  }, [])

  async function addEvent() {
    try {
      const event = { ...formState }
      await API.graphql(graphqlOperation(createEvent, {input: event}))
      handleNext()
    } catch (err) {
      console.log('Error Creating Event:', err)
    }
  }

  async function addQuote(data) {
    try {
        await API.graphql(graphqlOperation(createQuote, {input: { 'eventid' : data.id, 'useremail': data.useremail, 'name': data.name + ' Quote', 'status': 'Open'  }}))
        console.log('QUOTE ADDED FOR:' + data.name)
        //history.go(0)  
    } catch (err) {
      console.log('Error Adding Quote:', err)
    }
  }

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @rexwreyes 👋 you may want to clean up the subscription in your useEffect by returning the call for `subscription.unsubscribe()` like this

```js
 useEffect(() => {
   const subscription = API.graphql( graphqlOperation(subscriptions.onCreateEvent) ).subscribe({
      next: ({ provider, value }) => addQuote(value.data.onCreateEvent),
      error: error => console.warn(error)
    });    
    return () => subscription.unsubscribe()
  }, [])
```

**Comment by chrisbonifacio** [comment]
@rexwreyes It just occurred to me that running a graphql mutation from a subscription is probably not a good idea because other clients (users) could be subscribed to `createEvent` mutations and they will all create a quote with the same data.

If you want to guarantee that only one `Quote` record is created as a result of a `Event` record being created, you should probably handle that order of events differently and made not need to use a graphql subscription at all. I would rely on a graphql to update the state of the app to reflect changes in the database instead and display new info to the user.

**Comment by chrisbonifacio** [comment]
@rexwreyes Ah, I understand! And absolutely, you can save the result of the GraphQL mutation to a variable within `addEvent` and pass the returned `Event` data to the `addQuote` function like so.

example:

```js
async function addEvent() {
  try {
    const event = { ...formState }
    const data = await API.graphql(graphqlOperation(createEvent, {input: event}))
    await addQuote(data)
    handleNext()
  } catch (err) {
    console.log('Error Creating Event:', err)
  }
}

async function addQuote(data) {
  try {
      await API.graphql(graphqlOperation(createQuote, {input: { 'eventid' : data.id, 'useremail': data.useremail, 'name': data.name + ' Quote', 'status': 'Open'  }}))
      console.log('QUOTE ADDED FOR:' + data.name)
      //history.go(0)  
  } catch (err) {
    console.log('Error Adding Quote:', err)
  }
}
```

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!

**Comment by funes79** [comment]
I do have a similar problem, graphql is firing 1 event the other client side (where the add mutation was not executed) and 55 AWSAppSyncRealTimeProvider events on the produced side (where the add mutation was executed).  And it does not matter whether I do have unsubscribe or not in the useEffect. If I remove the unsubscribe I still go 55 on producer side, but now 2 events on the other window (client side).

```
  React.useEffect(() => {
    const subscription = API.graphql(
      graphqlOperation(onCreateProduct)
    ).subscribe({
      next: ({ provider, value }) => {
        console.log({ provider, value });
      },
      error: (error) => console.warn(error),
    });
    //subscription.unsubscribe();
  }, []);
```
![image](https://user-images.githubusercontent.com/20202121/147091378-98d945c7-cab0-4c31-9219-ca6d6d06ac93.png)

**Comment by funes79** [comment]
yes, correct. I already figured it out, thanks!

**Comment by majirosstefan** [comment]
@chrisbonifacio chrisbonifacio (https://github.com/chrisbonifacio) I have around 8 subscriptions in the app - t**he idea is to unsubscribe when the React Native app is put into background and then re-subscribe when app is active** / in foreground / open.

The logic is put into useFetchAndSub hook that is shared across few components / used at different places.
Its code looks like this: 


```
import { AppState, AppStateStatus } from "react-native";
import React, { useCallback, useContext, useEffect, useMemo, useState } from "react";
import { Logger, PubSub  } from "aws-amplify";
const logger = new Logger("AppStateFetchSubHook");

const useFetchAndSub = ({ name, fetch, clearData, subFn }: Props) => {
 const [appState, setAppState] = useState<AppStateStatus>(AppState.currentState);
 const [subs, setSubs] = useState<any[]>([]);
 
 useEffect(() => {
    AppState.addEventListener("change", setAppState);

    return () => {
      AppState.removeEventListener("change", setAppState);      
    };
  }, []);
    
  const handleAppState = async () => {
    console.log("running hook", appState, PubSub) 

    switch (appState) {
      case "active":
        await fetchAndSubscribe();
        break;

      case "background":
      case "inactive":
        await unsubscribe();
        break;

      default:
      // do nothing!
    }
  }; 
  
    useEffect(() => {     
    handleAppState();
    return () => unsubscribe();
  }, [appState]);
  
   const unsubscribe = async () => {
    if (subs.length === 0) return;
    
    for (const s of subs) {
      console.log("unsubscribe", s);
      s.unsubscribe();
    }

    // setSubs([]);
  };
  
  const fetchAndSubscribe = async () => {
    logger.info("fetching: ", name);
    await fetch();

    logger.info("subscribing: ", name);
    setSubs(subFn);
  };
  return {}; 
}
 ```
 
**When you put the app in background / and back few times (7) in row (in relative short time)**, PubSub._awsAppSyncRealTimeProvider contains map with subcriptions (subscriptionObserverMap) where items are duplicated: 
 
![Screen Shot 2022-04-07 at 3 07 33 PM](https://user-images.githubusercontent.com/44647381/162207200-f33dbd74-6717-4246-b20c-83d35c814f3d.png)

This looks to me like unsubscription method clearly does not work properly.
For real-world example, this affect users with settings where display turns off after 15 seconds of inactivity.

The app was ejected from expo": "^39.0.0", is using "react-native": "~0.63.4",  "aws-amplify": "^4.3.11",
    "aws-amplify-react-native": "^6.0.2".

**Comment by majirosstefan** [comment]
Any fix coming soon (or maybe re-opening this)or should we somehow patch it ourselves, please ? 

I am thinking to save subscriptions in subscriptionObserverMap by subscriptionName instead of its id. It should be also easier to check if there are multiple subscriptions for same query or not.

**Comment by lazaro-contato** [comment]
I'm having a problem similar to this problem. My sucbription is duplicating notifications. Sometimes 4 times, other times 8, it really depends. I checked the console and indeed it is subscribing several times, but the unsubscribe is declared correctly. Could you tell me if there is something wrong with my code?


```
const {user} = useUserSelector()
const userId = user?.id

const dispatch = useDispatch()

const createNotificationSubscription = useCallback(
(id?: string) => {
console.log('subscription')
const subscription = API.graphql(
graphqlOperation(onCreateNotificationCustom, {userID: id}),
) as unknown as Observable<{
value: {data: OnCreateNotificationCustomSubscription}
}>
return subscription.subscribe(
response => {
const notification = response.value.data.onCreateNotificationCustom
if (notification) {
console.log(notification)
dispatch(NotificationsActions.addNotification(notification))
}
},
error => {
console.log(error)
},
)
},
[dispatch],
)
```


I'm using a useEffect to unsubscribe:

```
useEffect(() => {
    if (userId) {
      createNotificationSubscription(userId)
    }
    return () => {
      createNotificationSubscription().unsubscribe()
    }
  }, [
    createNotificationSubscription,
    dispatch,
    userId,
  ])
```

**Comment by jellyfisssh** [comment]
poopy
