### ISSUE TITLE
getStaticPaths No current user Server Error

### ISSUE THREAD

**Issue by levelingup** [aws-amplify/amplify-js#8758]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React, Next.js

### Amplify APIs

Authentication, GraphQL API

### Amplify Categories

auth

### Environment information

```
  System:
    OS: macOS 11.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 97.55 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.10.0 - ~/.nvm/versions/node/v15.14.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 92.0.4515.131
    Safari: 14.1.2
    Safari Technology Preview: 15.0
  npmPackages:
    @ampproject/toolbox-optimizer:  undefined ()
    @aws-amplify/ui-react: ^1.2.8 => 1.2.8 
    @babel/core:  undefined ()
    @headlessui/react: ^1.4.0 => 1.4.0 
    @heroicons/react: ^1.0.3 => 1.0.3 
    @tailwindcss/forms: ^0.3.3 => 0.3.3 
    @tailwindcss/typography: ^0.4.1 => 0.4.1 
    amphtml-validator:  undefined ()
    arg:  undefined ()
    async-retry:  undefined ()
    async-sema:  undefined ()
    autoprefixer: ^10.3.1 => 10.3.1 
    aws-amplify: ^4.2.2 => 4.2.2 
    bfj:  undefined ()
    cacache:  undefined ()
    ci-info:  undefined ()
    comment-json:  undefined ()
    compression:  undefined ()
    conf:  undefined ()
    content-type:  undefined ()
    cookie:  undefined ()
    css-loader:  undefined ()
    debug:  undefined ()
    devalue:  undefined ()
    escape-string-regexp:  undefined ()
    eslint: 7.32.0 => 7.32.0 
    eslint-config-next: 11.0.1 => 11.0.1 
    file-loader:  undefined ()
    find-cache-dir:  undefined ()
    find-up:  undefined ()
    fresh:  undefined ()
    gzip-size:  undefined ()
    http-proxy:  undefined ()
    ignore-loader:  undefined ()
    is-animated:  undefined ()
    is-docker:  undefined ()
    is-wsl:  undefined ()
    json5:  undefined ()
    jsonwebtoken:  undefined ()
    loader-utils:  undefined ()
    lodash.curry:  undefined ()
    lru-cache:  undefined ()
    mini-css-extract-plugin:  undefined ()
    nanoid:  undefined ()
    neo-async:  undefined ()
    next: 11.0.1 => 11.0.1 
    ora:  undefined ()
    postcss: ^8.3.6 => 8.3.6 (8.2.13)
    postcss-flexbugs-fixes:  undefined ()
    postcss-loader:  undefined ()
    postcss-preset-env:  undefined ()
    postcss-scss:  undefined ()
    react: 17.0.2 => 17.0.2 (17.0.1)
    react-dom: 17.0.2 => 17.0.2 
    recast:  undefined ()
    resolve-url-loader:  undefined ()
    sass: ^1.37.5 => 1.37.5 
    sass-loader:  undefined ()
    schema-utils:  undefined ()
    semver:  undefined ()
    send:  undefined ()
    source-map:  undefined ()
    string-hash:  undefined ()
    strip-ansi:  undefined ()
    tailwindcss: ^2.2.7 => 2.2.7 
    terser:  undefined ()
    text-table:  undefined ()
    unistore:  undefined ()
    uuid: ^8.3.2 => 8.3.2 (3.4.0, 3.3.2)
    web-vitals:  undefined ()
    webpack:  undefined ()
    webpack-sources:  undefined ()
  npmGlobalPackages:
    @aws-amplify/cli: 5.0.2
    agentkeepalive: 4.1.4
    expo-cli: 4.5.2
    npm: 7.10.0
    react-native-cli: 2.0.1
```

### Describe the bug

Using Next.JS

Constantly getting this error:

![Screen Shot 2021-08-14 at 11 25 57 AM](https://user-images.githubusercontent.com/1781551/129456821-e078a26c-7249-4577-96b4-e0412d2b4dbf.png)

Using `getStaticPaths()` and `getStaticProps()` for dynamic routing
```
export async function getStaticPaths() {
  const activationData = await API.graphql({
    query: list*****,
  });
  // ...
}

export async function getStaticProps() {
  // ...
}
```

In addition, it just keeps refreshing the page

### Expected behavior

I was able to get a list of my queries from client side, so I should be able to return something, but instead, getting the No current user error on server side.

### Reproduction steps

1. install amplify and other required packages.
2. set Cognito user pool and a public API key
3. fetch the list using amplify api

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Manual configuration

![Screen Shot 2021-08-14 at 1 43 26 PM](https://user-images.githubusercontent.com/1781551/129459565-b9289a0b-639a-4422-a464-fe8232515180.png)

**Comment by chrisbonifacio** [comment]
Hi @levelingup :wave: Thank you for raising this issue. Did you call `Amplify.configure` like so?

```js
Amplify.configure({ ...awsconfig, ssr: true });

```

**Comment by levelingup** [comment]
Hello, I wanted to see if there's any updates on this? I'm getting no current user when I'm doing getServerSideProps as well with a different query. But when I'm in the AWS AppSync website to query the same thing, its allowing me to actually query. I've Logged in using the same login I'm using in my app.

**Comment by moneebalalfi** [comment]
@levelingup Hi, have you found the solution?

**Comment by giulioambrogi** [comment]
Same problem here, I'm doing exactly what suggested in the docs

**Comment by VTFLAB** [comment]
same for me problem.

**Comment by KiryuKz** [comment]
same problem here, is there any solution on this?

**Comment by naingaungphyo** [comment]
When we are using SSR to fetch data, we need to pass authentication info via context and consume it with `withSSRContext` as below. 

const { API } = withSSRContext(context);

And then, use `API` that is returned from `withSSRContext`.

The above way is working in pure SSR page but it doesn't work in GetStaticPath right now. I'm still finding the problem with types. I'm using typescript.

**Comment by naingaungphyo** [comment]
@chrisbonifacio Hi, can you please help me with an example to call appsync in GetStaticProps. 
There is no doc for GetStaticProps but for [GetServerSideProps](https://docs.amplify.aws/lib/ssr/q/platform/js/#withssrcontext).

First of all, I already have amplify configure as ssr to true `Amplify.configure({ ...awsconfig, ssr: true });` in _app.tsx.

in GetStaticProps, I'm calling API as below. Is it correct? 

`
const SSR = withSSRContext();
const posts = await SSR.API.graphql({ query: MyQuery, variables: { MyVariable },
authMode: 'AMAZON_COGNITO_USER_POOLS' })
`
The above way is not working and getting `No current user` error. 

My default appsync authentication type is 'cognito user pools'. i.e  `"aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",`  in aws-exports.js,  

so if I don't set `authMode` parameter, it will be the same result as the above query imo. 
It is also not working with same error.
`
const SSR = withSSRContext();
const posts = await SSR.API.graphql({ query: MyQuery, variables: { MyVariable } })
`

With `authMode: API_KEY`, it is working though.
`
const SSR = withSSRContext();
const posts = await SSR.API.graphql({ query: MyQuery, variables: { MyVariable },
authMode: 'API_KEY' })
`

**Comment by asangamanage** [comment]
Same error in 08/2022. It's not great when you follow the official documentation and stuck in the middle. (QA documentation?)

**Comment by chrisbonifacio** [comment]
@naingaungphyo @asangamanage can you share the schema for the models you are trying to access in your server-side functions?

I should point out that `withSSRContext` can still be used in `getStaticProps` and `getStaticPaths` but if you're trying to perform a GraphQL query, the model has to be publicly accessible (via API_KEY). They don't take `req` objects so there's no way to pass user credentials to make authenticated requests.

**Comment by chrisbonifacio** [comment]
Based on the original issue, I can see that `withSSRContext` was not being used and the default authorization type for the API is `Amazon Cognito User Pool` so this is the auth mode the AppSync query was made with.

```js
export async function getStaticPaths() {
  const activationData = await API.graphql({
    query: list*****,
  });
  // ...
}
```

Instead, we would use `withSSRContext` to initialize Amplify on the server, and the request should have manually specified the authMode as `API_KEY` and the model should allow public read access for the request to be authorized

```js
export async function getStaticPaths() {
  const { API } = withSSRContext();
  
  const activationData = await API.graphql({
    query: list*****,
    authMode: "API_KEY"
  });
  // ...
}
```

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
