### ISSUE TITLE
Signed URL from Storage.get() call not working

### ISSUE THREAD

**Issue by kgoyal98** [aws-amplify/amplify-js#8795]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

5.1.2

### What operating system are you using?

Ubuntu

### Amplify Categories

storage

### Amplify Commands

Not applicable

### Describe the bug

I am trying to have profile image upload functionality for users in my application.

```
Storage.put(filename, uri, {
    level: 'public',
    contentType: 'image/*'
});
const imageUrl = await Storage.get(filename) as Promise<string>;
```

The above two function calls are working. I checked that the image got stored in the S3 bucket. However when I try to open the url _imageUrl_, it shows AccessDenied. I want to know how this is possible and how I can solve the issue. If the user was able to put the object and get it, why was it not able to show the image?
 

### Expected behavior

The image url should be able to return image. 

### Reproduction steps

1. Available in description.

**Comment by sammartinez** [comment]
Thanks for this transfer @attilah. @kgoyal98 Can you provide the versions of Ubuntu you are using? This will help us triage the issue you are experiencing.

**Comment by kgoyal98** [comment]
Ubuntu 20.04.2 LTS

**Comment by kgoyal98** [comment]
@petercwk Thanks, this solved the issue.

As a suggestion, I think it would be better if Storage.get() call fails will error if the user does not have enough permission.

**Comment by evcodes** [comment]
@kgoyal98  Thank you for reporting this issue. We will consider this for future iterations on our API
