### ISSUE TITLE
PubSub - Publish working locally but not when deployed (Gatsby)

### ISSUE THREAD

**Issue by juancarloselorriaga** [aws-amplify/amplify-js#8798]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication, PubSub

### Amplify Categories

Not applicable

### Environment information

<details>

```
  System:
    OS: macOS 11.4
    CPU: (8) x64 Apple M1
    Memory: 19.21 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.11.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Firefox: 91.0.1
    Safari: 14.1.1
  npmPackages:
    @aws-amplify/pubsub: ^4.1.2 => 4.1.2 
    @aws-amplify/ui-components: ^1.7.3 => 1.7.3 
    @aws-amplify/ui-react: ^1.2.10 => 1.2.10 
    amplify-ui-components-loader:  undefined ()
    aws-amplify: ^4.2.4 => 4.2.4 
    babel-plugin-styled-components: ^1.13.2 => 1.13.2 
    bundle-optimisations:  1.0.0 
    dev-404-page:  1.0.0 
    functions:  1.0.0 
    gatsby: ^3.11.1 => 3.12.0 
    gatsby-plugin-image: ^1.12.0 => 1.12.0 
    gatsby-plugin-manifest: ^3.12.0 => 3.12.0 
    gatsby-plugin-sharp: ^3.12.0 => 3.12.0 
    gatsby-plugin-styled-components: ^4.12.0 => 4.12.0 
    gatsby-source-filesystem: ^3.12.0 => 3.12.0 
    gatsby-transformer-sharp: ^3.12.0 => 3.12.0 
    internal-data-bridge:  1.0.0 
    load-babel-config:  1.0.0 
    prod-404:  1.0.0 
    react: ^17.0.1 => 17.0.2 
    react-dom: ^17.0.1 => 17.0.2 
    styled-components: ^5.3.0 => 5.3.0 
    styled-components/macro:  undefined ()
    styled-components/native:  undefined ()
    styled-components/primitives:  undefined ()
    webpack-theme-component-shadowing:  1.0.0 
  npmGlobalPackages:
    @aws-amplify/cli: 5.3.0
    @vue/cli-service-global: 3.8.3
    @vue/cli: 3.8.4
    aws-cdk: 1.118.0
    bit-bin: 14.4.2
    eslint: 5.16.0
    expo-cli: 4.8.1
    firebase-tools: 9.12.1
    gatsby-cli: 3.5.0
    graphql-cli: 4.1.0
    ironhack_generator: 1.2.0
    jest: 24.9.0
    live-server: 1.2.1
    mocha: 6.1.4
    ngrok: 3.2.5
    nodemon: 2.0.2
    npm: 7.6.0
    parcel-bundler: 1.12.4
    prettier: 2.1.2
    serve: 11.3.0
    serverless: 2.53.1
    ts-node: 9.0.0
    typescript: 4.0.2
    vercel: 20.1.2
    vue-cli: 2.9.6
    yarn: 1.22.10



```

</details>

### Describe the bug

I'm developing a project in Gatsby JS (SSR) which actually works on my local environment publishing messages to AWS IoT Core but when deployed, it doesn't work on production.

I see no errores, the only difference between the two outputs (publish response) is that locally I receive an array with one undefined item -  [undefined] and when deployed I receive an empty array. Can't find anything online. My only guess would be something with SSR but I have no more ideas.

### Expected behavior

publish working in local environment and deployed

### Reproduction steps

1. Create gatsby project
2. Amplify Init
3. Install dependencies (pubsub, amplify react)
4. Amplify add auth
5. Amplify push
6. Follow documentation instructions for IoT policies (Amplify Docs)
7. Publish a message on local enviroment (works ok)
8. Deploy to Aws Amplify
9. Publish a message on deployed project (doesn't work)

### Code Snippet

```javascript
// gatsby-browser.js
import Amplify from 'aws-amplify'
import { AWSIoTProvider } from '@aws-amplify/pubsub/lib/Providers'
import awsConfig from './src/aws-exports'

import '@aws-amplify/ui/dist/style.css'
import './src/global.css'


Amplify.configure( { ...awsConfig, ssr: true } )

Amplify.addPluggable( new AWSIoTProvider( {
  aws_pubsub_region: 'us-east-1',
  aws_pubsub_endpoint: 'wss://myendpoint.iot.myregion.amazonaws.com/mqtt'
} ) )

export const onServiceWorkerUpdateReady = () => window.location.reload( true )

// index.js

import PubSub from '@aws-amplify/pubsub'
PubSub.configure()

  const handleButtonPress = async ( ope ) => {
    setPubSubErr( '' )

    if ( userGroup ) {
      setLoading( true )
      if ( ope === 'abrir' || ope === 'cerrar' ) {
        const topic = `${ userGroup }/comandos`
        try {
          const res = await PubSub.publish(
              topic,
              { ope }
          )
          console.log( 'pubsub response: ', res )
        } catch ( e ) {
          console.log( 'pubsub error: ', e )
        }
      }
    }
  }

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

````
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "rrrrrrrr",
    "aws_cognito_identity_pool_id": "rrrrrrrr",
    "aws_cognito_region": "rrrrrrrr",
    "aws_user_pools_id": "123412341234",
    "aws_user_pools_web_client_id": "234123412341234",
    "oauth": {},
    "aws_cognito_login_mechanism": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    }
};


export default awsmobile;


````

**Comment by IsaacIsrael** [comment]
The same here

**Comment by cwomack** [comment]
@ohlr and @dr-star

With Amplify JS v6 we provide an adapter for only Next.js, although the underlying generic adapters can be used with other frameworks. We have published documentation on how to use the generic adapters which can be viewed here - [docs.amplify.aws/react/build-a-backend/server-side-rendering](https://docs.amplify.aws/react/build-a-backend/server-side-rendering/)

Let me know if you have any questions.

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

Thank you!
