### ISSUE TITLE
API call is not working with Ionic 3

### ISSUE THREAD

**Issue by jatindera** [aws-amplify/amplify-js#880]
Do you want to request a feature or report a bug?
Bug

**What is the current behavior?**

API call runs successful in **Ionic 3 application** only when cloud api is enabled from command line and it runs only for SampleAPI. Following are two observations:

1. SampleAPI stops working from Ionic 3 application if we change the behavior from protected to public in Mobile HUB -> Cloud Logic. It never runs again even if you change the behavior back to protected.

2. Create a new API using Mobile HUB -> Cloud Logic and call this API in Ionic 3 code. It will never work. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.**

```
$ npm install -g awsmobile-cli
$ cd my-app #Change to your project's root folder
$ awsmobile init
$ awsmobile cloud-api enable
$ awsmobile push #Update your backend
``` 

In Project Entry Point,

```
import Amplify, { API } from 'aws-amplify';
import aws_exports from './aws-exports';

Amplify.configure(aws_exports);

```
In the home.ts (Ionic 3 Angular/TypeScript).
```
let apiName = 'SampleAPI';
let path = '/items/12345'; 
let myInit = { }
API.get(apiName, path, myInit).then(response => {
    // Add your code here
}).catch(error => {
    console.log(error.response)
});

```
**Execute code and everything is perfect till this moment. API.get(.....) gives you result**

**Bug 1:**
Next, Open Browser -> open AWS console -> Open Mobile Hub -> Choose your project -> Go to Cloud Logic -> Click on SampleAPI -> Change behavior from protected to public. Save changes.

- Ionic 3 code will start failing. 
- Pull changes. Even after that code will fail
- Revert the behavior from public to protected, save change, pull changes. Ionic API call will still fail

**Bug 2:**

- open AWS console -> Open Mobile Hub -> Choose your project -> Go to Cloud Logic -> Create new API
- Pull changes on your local computer
- In the code, change the API and path name. It will never work.
- Check the API call from command prompt, it works perfectly, but from Ionic code, it never works.

Following is the code sample.
In the home.ts (Ionic 3 Angular/TypeScript). Using "**NewAPI**" in code, created using above step. 
```
let apiName = 'NewAPI';
let path = '/newitem/12345'; 
let myInit = { }
API.get(apiName, path, myInit).then(response => {
    // Add your code here
}).catch(error => {
    console.log(error.response)
});
```

Conclusion:
Only API call working on Ionic 3 application is SampleAPI when you use command line to enable cloud-api. 

What is the expected behavior?
1. Create an API using mobile hub and it should work in Ionic 3.
2. Make changes in API behavior from protected to public or vice-versa and it should work.
3. Make changes in API behavior from protected to public and then revert the behavior, Ionic 3 app should work.

**Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?**

I am on AWS-Amplify 0.4.1 and AWS-Amplify-Angular 0.1.1. Working on Ubuntu 18.04 LTS. Chrome Browser. Testing on Android Phone Nexus 5 and Chrome Browser. 
No, I didn't work on the previous versions.

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by mlabieniec** [comment]
@jatindera can you post some response codes/data for the failing API calls? I'll run through some tests on my ionic app and see if I can reproduce. 

Just to be clear, when using the sample api (with the cli), things are setup with lambda, api gateway with a lambda proxy, and [lambda-express](https://github.com/awslabs/aws-serverless-express). The permissions are also bootstrapped with Cognito Federated Identities and use a Auth and UnAuthenticated role. If you were to change permissions on the API, these roles/policies might need to be updated. Assuming Mobile Hub automates some of this, we'll report this and see if this is a possible bug there as well, thanks for the detailed issue!

**Comment by shufankang** [comment]
@jatindera There are some limitations if you choose to use AWS Mobile Hub Console to configure an API that was created by awsmobile-cli. Alternatively if you directly modify  
`/my-app/awsmobilejs/backend/mobile-hub-project.yml`,
under `!com.amazonaws.mobilehub.v0.API` section -> `attributes`  -> 
add `disable-aws-auth: true` 
and make sure `requires-signin: false`. It will work for you. I will also submit a feature request to enable "awsmobile cloud-api configure" for modifying API's permission model.

**Comment by elorzafe** [comment]
@jatindera did you try [amplify-cli](https://github.com/aws-amplify/amplify-cli)? You can create  API without restricting access
