### ISSUE TITLE
amplify geo - Webpack error - Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by manavsehgal** [aws-amplify/amplify-js#8804]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Not applicable

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line

  System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 158.91 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    npm: 7.21.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Firefox: 90.0.2
    Safari: 14.1.1
  npmGlobalPackages:
    @aws-amplify/cli: 5.2.2-geo.2
    expo-cli: 4.5.2
    npm: 7.21.0
    typescript: 4.3.5


```

</details>

### Describe the bug

1. Webpack error: ERROR in ./node_modules/maplibre-gl-js-amplify/dist/public/marker.svg 1:0. Module parse failed: Unexpected token (1:0). You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
2. Webpack error: ERROR in ./node_modules/@maplibre/maplibre-gl-geocoder/dist/maplibre-gl-geocoder.css 2:0

### Expected behavior

Webback build succeeds

### Reproduction steps

1. Follow Getting Started JavaScript through to Geo until initializeMap()
2. run `npm start`

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by thaddmt** [comment]
@manavsehgal we released a newer version of the [maplibre-gl-js-amplify](https://www.npmjs.com/package/maplibre-gl-js-amplify/v/1.0.7) which should fix the issue in question for any customers going through the javascript tutorial then proceeding to the Geo setup. Thanks and let us know if you are seeing any other issues!
