### ISSUE TITLE
Hub listeners not being removed by Hub.remove()

### ISSUE THREAD

**Issue by wvidana** [aws-amplify/amplify-js#8807]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Not applicable

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line

  System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 298.86 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.7.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.20.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Firefox: 91.0.1
    Safari: 14.1.2
  npmPackages:
    @aws-amplify/ui-components: ^1.7.3 => 1.7.3 
    @aws-amplify/ui-react: ^1.2.10 => 1.2.10 
    @testing-library/jest-dom: ^4.2.4 => 4.2.4 
    @testing-library/react: ^9.3.2 => 9.5.0 
    @testing-library/user-event: ^7.1.2 => 7.2.1 
    amplify-ui-components-loader:  undefined ()
    apollo-client: ^2.4.2 => 2.6.10 
    aws-amplify: ^4.2.4 => 4.2.4 
    env-cmd: ^10.1.0 => 10.1.0 
    firebase: 7.23.0 => 7.23.0 
    firebase/analytics:  undefined ()
    firebase/app:  undefined ()
    firebase/auth:  undefined ()
    firebase/database:  undefined ()
    firebase/firestore:  undefined ()
    firebase/firestore/memory:  undefined ()
    firebase/functions:  undefined ()
    firebase/installations:  undefined ()
    firebase/messaging:  undefined ()
    firebase/performance:  undefined ()
    firebase/remote-config:  undefined ()
    firebase/storage:  undefined ()
    ini: ^1.3.5 => 1.3.8 
    inquirer: ^6.5.1 => 6.5.2 
    react: ^16.8.0 => 16.14.0 (17.0.2)
    react-apollo: ^3.1.5 => 3.1.5 
    react-dom: ^16.8.0 => 16.14.0 
    react-scripts: ^4.0.3 => 4.0.3 
  npmGlobalPackages:
    @aws-amplify/cli: 5.3.0
    aws-cdk: 1.74.0
    npm: 7.20.5
    to: 0.2.9
    update: 0.7.4



```

</details>

### Describe the bug

I have a Hub listener for datastore events, like so:

```javascript
Hub.listen("datastore", (data) => {
  if (data.payload.event === "ready") {
    // do something
  }
})
```

Then, on `signOut` I have a `Hub.remove('datastore')`, but when I sign back in, i realize i have 2 Datastore listeners reporting. If I do it again, I have 3... Which makes me think the Hub `remove()` method is not working.

I also tried to save the listener callback and use it in the remove method, but still not working. I also tried to just call the callback method, but doesn't work either

```javascript
const listener = Hub.listen("datastore", (data) => { /*my code*/ })
// some code later
listener()
//or
Hub.remove('datastore', listener)
```

Am I doing something wrong? How do I remove a `datastore` Hub listener?

### Expected behavior

When calling `Hub.remove('datastore')` the listener gets removed

### Reproduction steps

1. Create a React app
2. Place a Datastore listener like
```javascript
Hub.listen("datastore", (data) => {
  if (data.payload.event === "ready") {
    console.log("Datastore is ready")
  }
});
```
3. Try to remove afterwards with `Hub.remove('datastore')`
4. ...
5. The listener is never removed, and everytime the code cicles it creates a new listener, which makes the callback action to execute several times (when only one is needed)

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
@wvidana I think you may be passing in the `listener` incorrectly, `Hub.remove` expecting the callback as an argument rather than the Hub listener itself.

try something like this instead

```js
const listener = (data) => {*/my code */ }) // callback for Hub.listen

Hub.listen("datastore", listener)

/* later */
Hub.remove('datastore', listener)

```

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!

**Comment by andrewtremblay** [comment]
We've encountered this as well on our react-native application during development. Our theory is that since we want global listeners for the Hub events that during the hot reloading process, whatever the identifier the function signature uses is refreshed, which leads to the remove function not finding the old event. We've resorted to the following: 

```
export function configureAmplifyListeners(): void {
  // removing the listeners before adding them in the case we're hot reloading
  if (__DEV__) {
    // Hub.remove can't be used during hot reload because
    // refreshed functions have a different internal signature.
    (Hub as any).listeners.auth = [];
    (Hub as any).listeners.authmessage = [];
  }
  // We listen to certain auth messages from the amplify/cognito library
  Hub.listen('auth', authListener);
  Hub.listen('authmessage', customAuthMessageListener);
}
```
This feels risky, since listeners is private and there could be internal listeners that we're blowing away with this initialization. A `removeAllListeners("auth")` would be safer since we'd be more certain that we weren't doing that.
