### ISSUE TITLE
Not able to check if user is signed in on API route

### ISSUE THREAD

**Issue by marco910** [aws-amplify/amplify-js#8819]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

  System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (2) x64 Intel Xeon Processor (Skylake, IBRS)
    Memory: 852.41 MB / 3.75 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.15.3 - /usr/local/bin/node
    npm: 6.14.9 - /usr/local/bin/npm
  npmPackages:
    @ampproject/toolbox-optimizer:  undefined ()
    @babel/core:  undefined ()
    amphtml-validator:  undefined ()
    arg:  undefined ()
    async-retry:  undefined ()
    async-sema:  undefined ()
    aws-amplify: ^4.0.3 => 4.0.3
    bfj:  undefined ()
    cacache:  undefined ()
    ci-info:  undefined ()
    comment-json:  undefined ()
    compression:  undefined ()
    conf:  undefined ()
    content-type:  undefined ()
    cookie:  undefined ()
    css-loader:  undefined ()
    debug:  undefined ()
    devalue:  undefined ()
    escape-string-regexp:  undefined ()
    file-loader:  undefined ()
    find-cache-dir:  undefined ()
    find-up:  undefined ()
    fresh:  undefined ()
    gzip-size:  undefined ()
    http-proxy:  undefined ()
    ignore-loader:  undefined ()
    is-animated:  undefined ()
    is-docker:  undefined ()
    is-wsl:  undefined ()
    json5:  undefined ()
    jsonwebtoken:  undefined ()
    loader-utils:  undefined ()
    lodash.curry:  undefined ()
    lru-cache:  undefined ()
    mini-css-extract-plugin:  undefined ()
    nanoid:  undefined ()
    neo-async:  undefined ()
    next: 10.2.3 => 10.2.3
    ora:  undefined ()
    postcss-flexbugs-fixes:  undefined ()
    postcss-loader:  undefined ()
    postcss-preset-env:  undefined ()
    postcss-scss:  undefined ()
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
    recast:  undefined ()
    resolve-url-loader:  undefined ()
    sass-loader:  undefined ()
    schema-utils:  undefined ()
    semver:  undefined ()
    send:  undefined ()
    source-map:  undefined ()
    string-hash:  undefined ()
    strip-ansi:  undefined ()
    terser:  undefined ()
    text-table:  undefined ()
    unistore:  undefined ()
    web-vitals:  undefined ()
    webpack:  undefined ()
    webpack-sources:  undefined ()
  npmGlobalPackages:
    n: 7.0.0
    npm: 6.14.9

</details>

### Describe the bug

Hi there,

I'm using Amplify with an existing Cognito backend on my Next.js app and try to check on an API route if a user is signed in or not.

I'm getting always an error that no user is signed in. Although, when a user is signed in.

### Expected behavior

If the user is signed in, I expected to get the user object. If the user is not signed in, I expected to get null, undefined or an error message.

### Reproduction steps

1. Setup Next.js and Amplify with a Cognito backend
2. Use the above posted API route
3. Access the route when you are signed in (cookie stored in the browser) => user should be signed in on API route
4. Try to access the route when you are not signed in => no user object should be available on the API route

### Code Snippet

```javascript
import Amplify, { withSSRContext } from "aws-amplify";
import awsconfig from "../../aws-exports.js";

Amplify.configure({ ...awsconfig, ssr: true });

export default async (req, res) => {
  const { Auth } = withSSRContext({ req });

  try {
    const user = await Auth.currentAuthenticatedUser();
    res.json({ user });
  } catch (error) {
    res.json({ error });
  }
};

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hey @marco910 :wave: Thanks for raising this issue. 

Can you change your import of Amplify to this and restart your dev server? Let me know if that makes a difference.

```js
import {Amplify, withSSRContext } from "aws-amplify";
```

**Comment by marco910** [comment]
Thank you, @chrisbonifacio ! Now it works
