### ISSUE TITLE
Async Iterator error

### ISSUE THREAD

**Issue by zaithel** [aws-amplify/amplify-js#8822]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-adminui/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-adminui/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

us-east1

### If applicable, what version of Node.js are you using?

14.17.5

### What operating system are you using?

Windows

### Describe the bug

Hello, 

I'm using React Native with AWS amplify. 

Visual studio

And Running on an Android device

When I use 

yarn start I get this:

Possible Unhandled Promise Rejection (id: 0):
TypeError: Symbol.asyncIterator is not defined.
TypeError: Symbol.asyncIterator is not defined.

I think this could be the reason why when I'm trying to use this 
await DataStore.save(newUser); 
It's not saving the information, actually, it gets stuck 

And if I remove the "await", the information doesn't get store either. 

### Expected behavior

The information of the user should be added to the Data Store.

### Reproduction steps

 const save= async() => {
        if (!isValid()) {
            console.warn('Not valid');
            return;
        }

        const user = await Auth.currentAuthenticatedUser();

        await DataStore.save(
            new User({
                "name": "Lorem ipsum dolor sit amet",
                "image": "Lorem ipsum dolor sit amet",
                "bio": "Lorem ipsum dolor sit amet",
                "character": Character.ALEGRE,
                "lookingFor": Character.ALEGRE,
                "sub": "Lorem ipsum dolor sit amet"
            })
        );

**Comment by chrisbonifacio** [comment]
Hello @zaithel 👋 We'll need more information in order to reproduce this error. Could you share the contents of your `package.json` as well as the full code snippet around your use of `DataStore.save` such as imports and where/how it's being called?

**Comment by zaithel** [comment]
> Hello @zaithel 👋 We'll need more information in order to reproduce this error. Could you share the contents of your `package.json` as well as the full code snippet around your use of `DataStore.save` such as imports and where/how the code is being used?

Hello, 
Thanks a lot

This is the package.json

{
  "name": "matchDogApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@aws-amplify/analytics": "1.2.16",
    "@aws-amplify/core": "2.2.5-rn-datastore.6",
    "@aws-amplify/datastore": "1.0.7-rn-datastore.6",
    "@aws-sdk/client-cognito-identity": "^3.28.0",
    "@aws-sdk/client-s3": "^3.28.0",
    "@aws-sdk/credential-provider-cognito-identity": "^3.28.0",
    "@azure/core-asynciterator-polyfill": "^1.0.0",
    "@react-native-async-storage/async-storage": "^1.15.7",
    "@react-native-community/netinfo": "^6.0.1",
    "@react-native-picker/picker": "^1.16.7",
    "amazon-cognito-identity-js": "^5.1.0",
    "aws-amplify": "^4.2.5",
    "aws-amplify-react-native": "^5.0.3",
    "aws-sdk": "^2.978.0",
    "react": "17.0.2",
    "react-native": "0.65.1",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-image-picker": "^4.0.6",
    "react-native-permissions": "^3.0.5",
    "react-native-reanimated": "^2.3.0-alpha.2",
    "react-native-vector-icons": "^8.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.15.0",
    "@babel/runtime": "^7.15.3",
    "@react-native-community/eslint-config": "^3.0.0",
    "babel-jest": "^27.1.0",
    "eslint": "^7.32.0",
    "jest": "^27.1.0",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-native-codegen": "^0.0.7",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}


The code
import React, {useState, useEffect} from 'react';
import { View, Text, StyleSheet, SafeAreaView, Pressable, TextInput } from 'react-native';
import {Auth, Storage} from 'aws-amplify';
import {Picker} from '@react-native-picker/picker';
import { User, Character } from '../models';
import { DataStore } from '@aws-amplify/datastore';


  const isValid =()=>{
        return name && bio && character && lookingFor;
    };


    const save= async() => {
        if (!isValid()) {
            console.warn('Not valid');
            return;
        }


 //dummy data with await
        console.log("save data store");
        await DataStore.save(
            new User({
                id: "12",
                "name": "Lorem ipsum dolor sit amet",
                "image": "Lorem ipsum dolor sit amet",
                "bio": "Lorem ipsum dolor sit amet",
                "character": Character.ALEGRE,
                "lookingFor": Character.ALEGRE,
                "sub": "Lorem ipsum dolor sit amet"
            })
        );
        console.log("saved");

       try{
           console.log("new");
           //real data without the await
        const newUser = new User({
            sub: user.attributes.sub,
            name : name,
            bio: bio,
            character: character,
            lookingFor: lookingFor, 
            image: 
                'https://www.nationalgeographic.com.es/medio/2021/03/09/perro_4da5a8be_800x1200.jpg',
        });

        console.log(newUser);
        DataStore.save(newUser);

        console.log("end");
       }catch(error){
        console.log("Error saving post", error);
       }

        
    };

**Comment by chrisbonifacio** [comment]
@zaithel Thank you! Could you please post your schema as well so that I can reproduce the API?

**Comment by zaithel** [comment]
Hello, 

Sure, thanks a lot

![image](https://user-images.githubusercontent.com/73706460/131713843-93eb4105-a672-4fa3-b5cf-19f80e05feb9.png)

If anything else is needed, please let me know

**Comment by chrisbonifacio** [comment]
@zaithel In the code you provided, where do these variables come from before being checked?

```js
const isValid = () => {
  return name && bio && character && lookingFor;
};
```

**Comment by zaithel** [comment]
Hi @chrisbonifacio 

User is defined only in that line. 
And the other variables are from this part of the code
return (
        <SafeAreaView style={styles.root}>
           <View style ={styles.container}>

               <TextInput 
               style={styles.input} 
               placeholder='Nombre de  sumascota' 
               value={name} 
               onChangeText={setName}>
               </TextInput>

               <TextInput 
               style={styles.input} 
               placeholder='Descripción de la mascota' 
               multiline
               numberOfLines={3}
               value={bio} 
               onChangeText={setBio}>
               </TextInput>

               <Text>Mi mascota es:</Text>

                <Picker
                    label='Mi mascota es:'
                    selectedValue={character} 
                    onValueChange={itemValue => setCharacter(itemValue)}>
                    <Picker.Item label="Alegre" value="ALEGRE" />
                    <Picker.Item label="Tranquilo" value="TRANQUILO" />
                    <Picker.Item label="Sociable" value="SOCIABLE" />
                    <Picker.Item label="Ansioso" value="ANSIOSO" />
                    <Picker.Item label="Energia" value="ENERGETICO" />
                </Picker>

                <Text>Busco otra mascota:</Text>

                <Picker
                    label='Busco otra mascota:'
                    selectedValue={lookingFor} 
                    onValueChange={itemValue => setLookingFor(itemValue)}>
                    <Picker.Item label="Alegre" value="ALEGRE" />
                    <Picker.Item label="Tranquila" value="TRANQUILO" />
                    <Picker.Item label="Sociable" value="SOCIABLE" />
                    <Picker.Item label="Ansiosa" value="ANSIOSO" />
                    <Picker.Item label="Energia" value="ENERGETICO" />
                </Picker>

               <Pressable onPress={save} style={styles.button}>
                 <Text>Guardar</Text>
               </Pressable>
               
               <Pressable onPress={()=> Auth.signOut()} style={styles.button}>
                 <Text>Sign Out</Text>
                </Pressable>
               
           </View>
        </SafeAreaView>
    )
};

**Comment by chrisbonifacio** [comment]
Hi @zaithel apologies for the delay. I have not been able to reproduce this issue, my best guess as to why it may be happening is that there is an issue with the way babel is configured in your project or some dependencies are causing issues. I noticed that you have scoped packages (ex. @aws-amplify/datastore": "1.0.7-rn-datastore.6") as well as the global `aws-amplify` package.

I would remove all of the scoped `@aws-amplify/*` packages and only use `aws-amplify.` Make sure that it is updated to the latest version of 4.2.11 and then let me know if that helps at all.

Lastly, if that does not help, I would suggest recreating the project following the [documentation](https://docs.amplify.aws/start/q/integration/react-native/) for React Native and sticking to the Amplify packages it recommends installing.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!
