### ISSUE TITLE
Always require email log in to be verified

### ISSUE THREAD

**Issue by 24jr** [aws-amplify/amplify-js#8827]
### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

I was talking about my confusion here and the conclusion may be that it is not setup for this and so would be a feature request https://github.com/aws-amplify/amplify-adminui/issues/308 

Basically I have email as sign up and requires verification. If a user wants to change email this becomes an issue. It seems the user can change email to something and never verify it or be forced to verify on new login. 

### Describe the solution you'd like

I was hoping to be able to verify a new attribute such as phone or email before updating the attributes of the user. Perhaps one could add multiple emails to their account or phones and the users main email can only be switched with one of the other emails if the new one is verified. 

Or just have a call like 'verifyAttribute({'email': 'test@test.com'})' and 'updateUserAttribute({'email': 'test@test.com'}, code)' and only succeed if code is correct to update user attribute. 

### Describe alternatives you've considered

The helpful person in other issue suggested managing this by allowing the unverified attribute updates to occur and just prevent access to app through front end until email is verified

### Additional context

I haven't fully thought about every detail of login like signups with phone or email or maybe even just unverified usernames but I may look into that. Also might be overcomplicating things and just not care if changed email is verified. But could change to a@a.com if wanted and doesnt matter cause can change whenever

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by clementAC** [comment]
I don't understand why this has to be a feature request. It's a **bug**. If I mark an attribute as 'It need to be verified' I'm expecting to be verified no matter if it's at creation or update. 
The alternative considered is not viable, you can't handle access in front end, malicious users will find a way to bypass the front end restrictions to access backend services (API Gateway...).

Plus, a malicious user can usurpate someone's email identity.Even if you don't have the feature in your application, you can change the user email and every writable attribute by using the aws cli and the access token issued on login. With this technique I can change my email to jeff.bezos@aws.com and cognito will say "Ok no problem you are validated". 

Lot of application have system of invitation or whatever system that mainly use email to identify your interlocutor. Without verification, the trustiness is completely lost and attacks based on social engineering is facilitated by this _feature_

**Comment by abdallahshaban557** [comment]
Hi @clementAC - you are correct, this is a bug. I have changed the label accordingly. The Cognito team has completed a fix for this issue, and you can for now manually change a configuration on its console until the Amplify CLI releases a fix to do this for you. https://github.com/aws-amplify/amplify-js/issues/987#issuecomment-1146251705

I will be closing this issue since it is a duplicate.
