### ISSUE TITLE
MFAMethodNotFoundException after removing phone_number

### ISSUE THREAD

**Issue by 24jr** [aws-amplify/amplify-js#8829]
### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

I have email set as primary login and mfa optional. If i set sms mfa it requires a phone number naturally. But I can delete the phone number and sms mfa still be enabled so when I logout and login again i get MFAMethodNotFoundException. 

### Describe the solution you'd like

SMS should be returned to NOMFA after phone is removed I think

### Describe alternatives you've considered

handling in front end if user deletes phone also call setPrefferredMFA to NOMFA but maybe call could fail or something

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by abdallahshaban557** [comment]
Hello!

This issue has now been resolved from Cognito. You will receive an error if you try to delete a phone number attribute for a user and MFA is enabled and required.

![image](https://github.com/aws-amplify/amplify-js/assets/17932473/591b8b23-00b6-4189-bcde-7e790c32d313)
