### ISSUE TITLE
AWS Amplify Version Upgrade - SignIn & SignOut does not work

### ISSUE THREAD

**Issue by nhgupta12345** [aws-amplify/amplify-js#8838]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 606.26 MB / 7.82 GB
  Binaries:
    Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 92.0.4515.159
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.84)
    Internet Explorer: 11.0.19041.906
  npmPackages:
    concurrently: ^5.0.1 => 5.3.0
    dotenv: ^8.2.0 => 8.6.0
    envinfo: ^7.8.1 => 7.8.1
    express: ^4.17.1 => 4.17.1
    http-proxy-middleware: ^0.20.0 => 0.20.0
  npmGlobalPackages:
    @angular/cli: 8.3.20
    create-react-app: 3.4.1
    firebase-tools: 8.12.1
    node: 10.17.0
    windows-build-tools: 5.2.2

```

</details>

### Describe the bug

I was using below amplify versions in my project:
   "aws-amplify": "^1.1.22",
   "aws-amplify-react": "^2.3.2"

Below API calls with the above versions:

![image](https://user-images.githubusercontent.com/56863357/131796222-06725ea7-7937-4e9d-ba55-379fffaf1c58.png)

When I tried to upgrade the versions as below:
      "aws-amplify": "^4.2.5",
      "aws-amplify-react": "^5.0.11"

Below API calls after upgrading the amplify versions as above:

![image](https://user-images.githubusercontent.com/56863357/131796478-3d6c9003-532c-4b7d-a00f-a6414837efe0.png)

The AWS Cognito calls are not happening due to which the Cognito sign in and signout not working.

### Expected behavior

With both the amplify versions the Cognito calls should be the same and user should be able to sign in and sign out.

### Reproduction steps

1. Implement AWS Amplify Google login & logout functionality in your appliation.
2. Use below versions:
          "aws-amplify": "^1.1.22",
          "aws-amplify-react": "^2.3.2"
3. Upgrade the versions as below:
          "aws-amplify": "^4.2.5",
          "aws-amplify-react": "^5.0.11"
4. Try Google login & logout functionality. Open developer tools -> Networks tab -> The cognito calls wont happen & login - logout does not work.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @nhgupta12345 👋 Thanks for raising this issue. Are there any errors being logged in the console? You've jumped several major versions so there are some breaking changes you'll have to account for. These are mentioned in the [README](https://github.com/aws-amplify/amplify-js#amplify-4xx-has-breaking-changes-for-react-native-please-see-the-breaking-changes-below). You can also copy/paste the code where you're configuring Amplify and using the Auth library in your project and we may be able to point out anything that needs to be adjusted.

**Comment by evcodes** [comment]
Hello, I was not able to reproduce these errors but I did put together my findings in [this repo](https://github.com/evcodes/social_sign_on). You can run through the different commits and see that regardless of what Amplify version I was on, Social Sign on still worked. 

I would have to see how you're configuring things because there's probably an error somewhere with how you're setting up Authentication.

**Comment by nhgupta12345** [comment]
> Hello, I was not able to reproduce these errors but I did put together my findings in [this repo](https://github.com/evcodes/social_sign_on). You can run through the different commits and see that regardless of what Amplify version I was on, Social Sign on still worked.
> 
> I would have to see how you're configuring things because there's probably an error somewhere with how you're setting up Authentication.

I tried running your repo code and while adding my aws-exports.js and clicking on Login I am facing below issue:
![image](https://user-images.githubusercontent.com/56863357/131978997-2719e432-d42c-41ec-b219-3f953e008609.png)

**Comment by nhgupta12345** [comment]
> Hi @nhgupta12345 👋 Thanks for raising this issue. Are there any errors being logged in the console? You've jumped several major versions so there are some breaking changes you may have to account for. These are mentioned in the [README](https://github.com/aws-amplify/amplify-js#amplify-4xx-has-breaking-changes-for-react-native-please-see-the-breaking-changes-below).
> 
> You can also copy/paste the code where you're configuring Amplify and using the Auth library in your project here and we may be able to point out anything that needs to be adjusted.

There are no errors in the console. The cognito calls are not happening after version upgrade and sign in is not working.

**Comment by chrisbonifacio** [comment]
@nhgupta12345 Did you pull your amplify environment into @evcodes 's project? I was able to use it and sign in with google.

Not signed in
<img width="1497" alt="Screen Shot 2021-09-03 at 12 52 30 PM" src="https://user-images.githubusercontent.com/16952986/132041172-add1ff0d-f0d8-4491-b431-7bcf77c9ce96.png">

Signed in
<img width="1497" alt="Screen Shot 2021-09-03 at 12 52 47 PM" src="https://user-images.githubusercontent.com/16952986/132041191-26663bf9-7796-4196-9d36-5db2b2d3ae9f.png">


In any case, it would probably be best if you shared the snippets in your code where you're importing Amplify and Auth, calling `Amplify.configure` and `Auth.signIn` or `Auth.federatedSignIn.1, etc.

**Comment by nhgupta12345** [comment]
Hi, Please find the code snippet that we are using in our Application.js as below:

import React, { Component, createContext } from "react";
import { connect } from "react-redux";
import Amplify, { Auth, Hub } from "aws-amplify";
import PropTypes from "prop-types";

import Router from "./Router";
import OAuthButton from "./modules/user/components/OAuthButton";
import { loadUser } from "./modules/user/authReducer";

import ServerError from "./modules/core/components/errors/ServerError";
import awsmobile from "./aws-exports";

const oauth = {
    domain: domain,
    scope: ["phone", "email", "profile", "openid", "aws.cognito.signin.user.admin"],
    redirectSignIn: `${window.location.origin}/callback`,
    redirectSignOut: `${window.location.origin}`,
    responseType: "code", // or token
};

Amplify.configure(awsmobile);
Auth.configure({
    oauth,
});

class Application extends Component {
    constructor(props) {
        super(props);
        // let the Hub module listen on Auth events
        Hub.listen("auth", this);
        this.state = {
            authState: "loading",
        };
    }

    componentDidMount = () => {
        // check the current user when the App component is loaded
        setTimeout(() => {
            Auth.currentAuthenticatedUser()
                .then((user) => {
                    console.log(user);
                    this.props.load();
                    this.setState({ authState: "signedIn" });
                })
                .catch((e) => {
                    console.log(e);
                    this.setState({ authState: "signIn" });
                });
        }, 3000);
    };

    onHubCapsule = (capsule) => {
        // The Auth module will emit events when user signs in, signs out, etc
        const { channel, payload } = capsule;
        if (channel === "auth") {
            switch (payload.event) {
                case "signIn":
                    console.log("signed in");
                    this.setState({ authState: "loading" });
                    break;
                case "signIn_failure":
                    console.log("not signed in");
                    this.setState({ authState: "signIn" });
                    break;
                default:
                    break;
            }
        }
    };

    signOut = () => {
        Auth.signOut()
            .then(() => {
                this.setState({ authState: "signIn" });
            })
            .catch((e) => {
                console.log(e);
            });
    };

    componentWillReceiveProps(nextProps) {
        if (this.props.loading && !nextProps.loading && !nextProps.error && !this.state.loaded) {
            this.setState({ loaded: true });
        }
    }

    componentDidUpdate() {
        window.dispatchEvent(new Event("resize"));
    }

    render() {
        const { authState } = this.state;
        const { user, authzLoading, authzSuccess, authzError } = this.props;

        return (
            /**Passing history in AppProvider to be used in other components */
            <AppProvider value={{ history: this.props.history, user: this.props.user }}>
                <div className="App">
                    {(authState === "loading" || authzLoading) && <Loading />}
                    {authState === "signIn" && <OAuthButton />}

                    {authState === "signedIn" && authzSuccess && user && <Router history={this.props.history} />}
                    {authzError && <ServerError />}
                </div>
            </AppProvider>
        );
    }
}

function Loading() {
    return (
        <div
            style={{
                display: "flex",
                height: "100vh",
                alignItems: "center",
                justifyContent: "center",
                backgroundColor: "white",
            }}
        >
            <i className="fa fa-refresh fa-spin fa-2x" />
        </div>
    );
}

Application.propTypes = {
    load: PropTypes.func.isRequired,
    loading: PropTypes.bool,
    error: PropTypes.shape({
        message: PropTypes.string.isRequired,
    }),
    user: PropTypes.object,
    history: PropTypes.object,
};

/**Adding  AppContext to pass values to other component from here*/
const AppContext = createContext({});
export const AppProvider = AppContext.Provider;
export const AppConsumer = AppContext.Consumer;

export default Application;

We are facing below error on debugging the code:
![image](https://user-images.githubusercontent.com/56863357/132509744-7ba7a498-9eb5-4d8b-be5b-80aa14f8c223.png)

**Comment by evcodes** [comment]
I think you may have a bug because there's no port on your `localhost` endpoint, it should be something like localhost:3000/callback

**Comment by chrisbonifacio** [comment]
@nhgupta12345 yeah, it seems like the issue might be stemming from here for you

```js
const oauth = {
domain: domain,
scope: ["phone", "email", "profile", "openid", "aws.cognito.signin.user.admin"],
redirectSignIn: ${window.location.origin}/callback,
redirectSignOut: ${window.location.origin},
responseType: "code", // or token
};
```

**Comment by nhgupta12345** [comment]
> localhost

With previous versions, the URL "localhost" and google login works fine. I tried adding the port no to the localhost:3001 and still fails on amplify version upgrade.

**Comment by chrisbonifacio** [comment]
you may want to make sure there's a trailing slash at the end and that it's prefixed with `http://`

<img width="1075" alt="Screen Shot 2021-09-10 at 11 15 23 AM" src="https://user-images.githubusercontent.com/16952986/132876730-e4714e2b-8e63-40d0-b5d5-4075a9b0156d.png">

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!
