### ISSUE TITLE
why always occured error "Missing Credentials" when I use AssosicateSoftwareToken

### ISSUE THREAD

**Issue by minchch** [aws-amplify/amplify-js#8839]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

REST API

### Amplify Categories

api

### Environment information

<details>

```
I'm creating about Login OTP page with Cognito (Our projects Login systems already use Cognito User pool)

and I stucked in Cognito OTP work

[ Here is my action history ]

My current Cognito Userpool MFA Settings : "OPTIONAL"
Node.js
SignIn Logic is already created.
 [Our projects modules use below ]
import { Config, CognitoIdentityCredentials, CognitoIdentityServiceProvider } from 'aws-sdk';
import {
 CognitoUserPool,
 CognitoUser,
 AuthenticationDetails,
 CognitoUserAttribute
} from 'amazon-cognito-identity-js'; 



```

</details>

### Describe the bug

**When I use AssociateSoftwareToken(), as below, 
I got Missing Credentials error, 
but in my console.log result, credentials and User information is saved without reset. 

please check and let me know what kinds of info is need to added.** 

`signin(username, pass, cb) {
    let authenticationDetails = new AuthenticationDetails({
      Username: username,
      Password: pass
    });
    let cognitoUser = new CognitoUser({
      Username: username,
      Pool: this.userPool
    });

    this.cognitoUser = cognitoUser;
    try{
      cognitoUser.authenticateUser(authenticationDetails, {
        onSuccess: result => {
          var logins = {};
          logins[
            'cognito-idp.' + this.options.region + '.amazonaws.com/' + this.options.UserPoolId
          ] = result.getIdToken().getJwtToken();
         
          console.log(result)
          Config.credentials = new CognitoIdentityCredentials({
            IdentityPoolId: this.options.UserPoolId,
            Logins: logins
          });
          console.log(Config.credentials)
          **var params1 = {
            AccessToken: result.getAccessToken().getJwtToken()
          };
                    
          const cognitoServiceProvider = new CognitoIdentityServiceProvider({region:this.options.region});
          cognitoServiceProvider.associateSoftwareToken(params1, function(err, data) {
            if (err) console.log(err, err.stack); // an error occurred
            else     console.log(data);           // successful response
          });**

          this.onChange(true);
          cb(null, result);
        },
        onFailure: err => {
          cb(err);
        },
        newPasswordRequired: result => {
          cb({
            code: 'NEW_PASSWORD_REQUIRED',
            message: '처음으로 접속하셨습니다. 새로운 비밀번호를 입력해주세요.'
          });
        }
      });
    }catch(err){
      console.log(err);
`

### Expected behavior

Below URL is my behavior! 

https://stackoverflow.com/questions/68995457/whats-different-aws-config-and-awsconfig-config-aws-cognito

### Reproduction steps

N/A

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

<img width="758" alt="스크린샷 2021-09-02 오후 4 52 11" src="https://user-images.githubusercontent.com/77950422/131810675-567dd1b7-de51-42b7-90bf-dda7f7efdd76.png">

**Comment by tannerabread** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment so we can re-open this issue and be better able to assist you.

Thank you!
