### ISSUE TITLE
Cognito: MFA refresh token never expire when remembering a device

### ISSUE THREAD

**Issue by dguayrobotiq** [aws-amplify/amplify-js#884]
**Do you want to request a feature or report a bug?**

Bug

**What is the current behavior?**

I'm not sure if that is intended but if I turn on MFA and call `setDeviceStatusRemembered(...)` for a certain user, the user is never asked again to do the MFA (i.e. enter a code sent by SMS) with that device. I found `Refresh token expiration (days)` settings under General Settings > App clients > Show Details on Cognito but that doesn't seem to expire even if I put 1 day and wait X days before trying to login again.  Also, with aws cli if I check the same user list of devices, the device's `dev:device_remembered_status` is always `remembered`.

**What is the expected behavior?**

The refresh token for MFA should expire after 30 days (default value) or after a number of days configured in Cognito.

**Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?**

`amazon-cognito-identity-js 1.18.0`

**Comment by dguayrobotiq** [comment]
@cbernardes Just to make sure, are you saying that there is no expiration when the user decide to remember its device for the MFA? I thought there would be one.

**Comment by cbernardes** [comment]
@dguayrobotiq I didn't said that. I said there is no "MFA", if you have a second mobile authentication, for example.

**Comment by dguayrobotiq** [comment]
@cbernardes I know what MFA is and what remembering device does. What I'm asking is whether or not there is an expiration on the `remembered status`.

**Comment by ruiyang** [comment]
Having an expiration date for the remembered state is good. Seemed that cognito doesn't support this out of the box now. what we could do is to create a cron job to clear the remembered state after 30 days.

On the UI, instructions for the user will be "Remember this device for 30 days".

**Comment by harrysolovay** [comment]
MFA should be suppressed if the device is remembered, and the refresh token should expire in the time that is configured on the User Pool. This is working as intended.

**Comment by ruiyang** [comment]
@harrysolovay Hi, what would be really useful is cognito to implement a configuration for days of remembering the device for supressing MFA. eg. we can have "Remember this device for 30 days" in our login UI, then after first MFA login, the following login from this device will not require MFA until 30 days. I think it is different from refresh token expiration. Again, would be great if there is a similar setting like the refresh token expiry time config for remembering devices duration.
