### ISSUE TITLE
Records are not fetching properly in AWS GraphQl

### ISSUE THREAD

**Issue by Ni7iN** [aws-amplify/amplify-js#8851]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line

```

</details>

### Describe the bug

We are using graphql queries for fetching data from dynamodb but records are not fetching properly when the table data is large.
When setting the limit it returns only some of the data.
Please suggest a workaround

### Expected behavior

All the records that is set by the limit should be fetched from the table.

### Reproduction steps

1. Install '...'
2. Configure '...'
3. Go to '...'

### Code Snippet

```javascript
// Put your code below this line.
module.exports = function getAWSAppSync(token) {
    const getFunctionToken = async () => await token;
    const client = new AWSAppSyncClient({
        url: aws_exports.aws_appsync_graphqlEndpoint,
        region: aws_exports.aws_appsync_region,
        auth: {
            type: AUTH_TYPE.AWS_LAMBDA,
            token: () => getFunctionToken()
        },
        disableOffline: true
    });
    return client;
}

    /**
     * Find the record inside the model using a filter query
     * 
     * @param {} filter - Filter(and|or)
     * @param {} entity - Model Name
     */
   async findByQuery(filter, entity) {

        // Getting graphql queries
        var query = _actions(entity, "list");

        const result = await this.client.query({
            query: gql(query),
            fetchPolicy: 'no-cache',
            variables: {
                filter: this.getQuery(filter),
                limit: 10000
            }
        });

        var method = "list" + _type(entity, true);
        return result["data"][method]["items"];
    }


```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hey @Ni7iN :wave: Thanks for raising this issue. From what I can find, there seems to be a 1000 record fetch limit for AppSync queries. Here is the relevant [documentation](https://docs.aws.amazon.com/general/latest/gr/appsync.html)

> 


Iterations in a foreach loop in mapping templates | The maximum number of iterations in a #foreach...#end loop in mapping templates | 1000
-- | -- | --

The workaround seems to be querying the 1000 records and then paginating.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!
