### ISSUE TITLE
axios should be updated

### ISSUE THREAD

**Issue by elcreator** [aws-amplify/amplify-js#8852]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

Not applicable

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

axios@0.21.1 is vulnerable https://snyk.io/vuln/npm:axios@0.21.1 so apps using aws-amplify/amplify-js have problems with security scanners. Please update it to 0.21.3

### Expected behavior

axios@0.21.1 -> axios@0.21.3 in all dependencies

### Reproduction steps

npm i
run security scanner

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by evcodes** [comment]
Thanks for opening this issue, I am working on merging in the latest axios version. Will close when updated

**Comment by evcodes** [comment]
releasing a new version of Amplify with Axios patched today
