### ISSUE TITLE
AppSync subscriptions do not work with a custom setup using existing resources

### ISSUE THREAD

**Issue by lambda0xff** [aws-amplify/amplify-js#8853]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

GraphQL API

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 11.5.2
    CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
    Memory: 125.49 MB / 8.00 GB
    Shell: 3.3.1 - /usr/local/bin/fish
  Binaries:
    Node: 14.17.5 - /usr/local/opt/node@14/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/opt/node@14/bin/npm
    Watchman: 2021.08.23.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 93.1.29.77
    Chrome: 92.0.4515.159
    Chrome Canary: 95.0.4634.3
    Firefox: 91.0.2
    Safari: 14.1.2
  npmGlobalPackages:
    @aws-amplify/cli: 5.4.0
    @vue/cli: 4.5.13
    neovim: 4.10.0
    npm: 7.21.0
    typescript: 4.4.2
    watchman: 1.0.0
    yarn: 1.22.11

```

</details>

### Describe the bug

After setting up a Vue 3 project with amplify using existing resources, AppSync subscriptions throw an error

### Expected behavior

This setup used to work before

### Reproduction steps

In the same region (eu-west-1), I have the following existing resources:
- Cognito Identity pool + User pool
- AppSync api connected to a single DynamoDB table resource

In a new Vue 3 application:
- `amplify init`
- `amplify codegen add --api xxxxxx`
- `amplify codegen` to generate the API localy

- in `main.ts`, connect to amplify
```js
const Auth = {
  identityPoolId     : 'eu-west-1:xxx',
  region             : 'eu-west-1',
  userPoolId         : 'eu-west-xxx',
  userPoolWebClientId: 'xxx',
  mandatorySignIn    : false,

  cookieStorage: {
    domain : 'localhost'
    path   : '/',
    expires: 365,
    secure : false
  },
}

const API = {
  aws_appsync_graphqlEndpoint   : 'https://xxx.appsync-api.eu-west-1.amazonaws.com/graphql',
  aws_appsync_region            : 'eu-west-1',
  aws_appsync_authenticationType: 'AWS_IAM'
}

Amplify.configure({ Auth, ...API })
```

In the application, querying and creating items work fine.  However, when I try:

```js
  setup() {
    const a = API.graphql(graphqlOperation(subscriptions.onPutPost)) as Promise<any>

    console.log(a)

    a.then(res => console.log(res))
      .catch(e => console.log("error", e))
    return {}
  }
```
I get a error in the browser console: `Uncaught TypeError: a.then is not a function`
The console log statement prints:
![Screenshot 2021-09-07 at 09 04 23](https://user-images.githubusercontent.com/38687176/132301100-d7edc4ea-7f49-4e1b-9107-e49acdad08dc.png)

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional configuration

{
    "UserPool": {
        "Id": "eu-west-1_yKbli8BlY",
        "Name": "test",
        "Policies": {
            "PasswordPolicy": {
                "MinimumLength": 6,
                "RequireUppercase": false,
                "RequireLowercase": false,
                "RequireNumbers": false,
                "RequireSymbols": false,
                "TemporaryPasswordValidityDays": 7
            }
        },
        "LambdaConfig": {},
        "LastModifiedDate": "2021-09-07T08:35:28.422000+02:00",
        "CreationDate": "2021-09-07T08:35:28.422000+02:00",
        "SchemaAttributes": [
            {
                "Name": "sub",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": false,
                "Required": true,
                "StringAttributeConstraints": {
                    "MinLength": "1",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "given_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "family_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "middle_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "nickname",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "preferred_username",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "profile",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "picture",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "website",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "email",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "email_verified",
                "AttributeDataType": "Boolean",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false
            },
            {
                "Name": "gender",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "birthdate",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "10",
                    "MaxLength": "10"
                }
            },
            {
                "Name": "zoneinfo",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "locale",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "phone_number",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "phone_number_verified",
                "AttributeDataType": "Boolean",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false
            },
            {
                "Name": "address",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "updated_at",
                "AttributeDataType": "Number",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "NumberAttributeConstraints": {
                    "MinValue": "0"
                }
            }
        ],
        "AutoVerifiedAttributes": [
            "email"
        ],
        "UsernameAttributes": [
            "email"
        ],
        "SmsVerificationMessage": "Your verification code is {####}. ",
        "EmailVerificationMessage": "Your verification code is {####}. ",
        "EmailVerificationSubject": "Your verification code",
        "VerificationMessageTemplate": {
            "SmsMessage": "Your verification code is {####}. ",
            "EmailMessage": "Your verification code is {####}. ",
            "EmailSubject": "Your verification code",
            "DefaultEmailOption": "CONFIRM_WITH_CODE"
        },
        "SmsAuthenticationMessage": "Your authentication code is {####}. ",
        "MfaConfiguration": "OFF",
        "EstimatedNumberOfUsers": 0,
        "EmailConfiguration": {
            "EmailSendingAccount": "COGNITO_DEFAULT"
        },
        "UserPoolTags": {},
        "AdminCreateUserConfig": {
            "AllowAdminCreateUserOnly": false,
            "UnusedAccountValidityDays": 7,
            "InviteMessageTemplate": {
                "SMSMessage": "Your username is {username} and temporary password is {####}. ",
                "EmailMessage": "Your username is {username} and temporary password is {####}. ",
                "EmailSubject": "Your temporary password"
            }
        },
        "UsernameConfiguration": {
            "CaseSensitive": false
        },
        "Arn": "arn:aws:cognito-idp:eu-west-1:546225261971:userpool/eu-west-1_yKbli8BlY",
        "AccountRecoverySetting": {
            "RecoveryMechanisms": [
                {
                    "Priority": 1,
                    "Name": "verified_email"
                }
            ]
        }
    }
}

**Comment by lambda0xff** [comment]
Schema:
```gql
type Mutation {
	# Put a single value of type 'Post'.
	# If an item exists it's updated. If it does not it's created.
	putPost(id: ID!, title: String!): Post
}

type Post {
	id: ID!
	title: String!
}

type Query {
	# Get a single value of type 'Post' by primary key.
	singlePost(id: ID!): Post
}

type Subscription {
	onPutPost: Post
		@aws_subscribe(mutations: ["putPost"])
}

schema {
	query: Query
	mutation: Mutation
	subscription: Subscription
}
```

generated ts mutations file:
```ts
/* tslint:disable */
/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onPutPost = /* GraphQL */ `
  subscription OnPutPost {
    onPutPost {
      id
      title
    }
  }
`;

```

**Comment by chrisbonifacio** [comment]
Hi @lambda0xff 👋 Thanks for raising this. To use a subscription, you need to call the `subscribe` method after `API.graphql(<yourSubscription>)` because it returns an Observable rather than a Promise.

So your code would be:

```js
  setup() {
    const a = API.graphql(graphqlOperation(subscriptions.onPutPost)) as any

    console.log(a)

    a.subscribe({
      next: ({ provider, value }) => console.log({ provider, value }),
      error: error => console.warn(error)
    }); 
   
    return {}
  }
```

Here's some [documentation](https://docs.amplify.aws/lib/graphqlapi/subscribe-data/q/platform/js/) with examples


Let me know if that helps!

**Comment by lambda0xff** [comment]
Hi @chrisbonifacio , that doesnt work for me.  I may be mistaken but I think your snippet only looks like it's working because not actual subscription takes place (for instance, the console logs inside the subscribe block do not output anything).

The moment the observable is subscribed, I have an error.  Also, like in my snippet there's an error when trying to cast the result of `API.graphql(...)` into a Promise<any>

Also, if your look at the first `console.log(a)`, what I have is the following:

![Screenshot 2021-09-07 at 22 14 16](https://user-images.githubusercontent.com/38687176/132405225-0c2dab95-b58d-41bb-9fa1-21356990b320.png)

which seems to indicate that there's some kind of a problem ?

**Comment by lambda0xff** [comment]
@chrisbonifacio : while putting together a repro application, realised it's definitely an issue on my side.  Sorry for the trouble.
