### ISSUE TITLE
zen-observable-ts broken import 

### ISSUE THREAD

**Issue by kyleownsaterrier** [aws-amplify/amplify-js#8873]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-west-2:220927856021:apps/d2hxpiwsgtlb15

### Region

us-west-2

### Amplify Console feature

Build settings

### Describe the bug

I receive this error when trying to deploy my app with amplify-aws api included. Fixing this file locally by using "{ Observable }" solves the issue but I cannot make changes to this file when building on the server.
```
`2021-09-09T18:57:21.046Z` [WARNING]: Error: node_modules/@aws-amplify/api/lib-esm/API.d.ts:2:8 - error TS2613: Module '"/codebuild/output/src167203613/src/black-dashboard-angular-master/node_modules/zen-observable-ts/index"' has no default export. Did you mean to use 'import { Observable } from "/codebuild/output/src167203613/src/black-dashboard-angular-master/node_modules/zen-observable-ts/index"' instead?
                                    2 import Observable from 'zen-observable-ts';
```

### Expected behavior

Build successful

### Reproduction steps

deploy from master branch

**Comment by chrisbonifacio** [comment]
@kyleownsaterrier Would you happen to have `zen-observable`, any version over 1.0.0, as a dependency separate from Amplify's anywhere in your project?

**Comment by kyleownsaterrier** [comment]
Yes, there appears to be **node_modules/zen-observable-ts/** folder outside of the @aws-amplify folder that is version 1.1.0. I don't believe its needed anywhere in the project as I'm only using amplify datatstore. How do I go about removing it?

**Comment by kyleownsaterrier** [comment]
I have removed the entire node_modules folder, then installed zen-observable-ts@1.0.0 but I am still facing the same issue with this line of the aws-amplify generated file: API.d.ts

`import Observable from 'zen-observable-ts';`

Changing this to:
`import { Observable } from 'zen-observable-ts';`

fixes the issue on my local, but I cannot do this on the server.

**Comment by chrisbonifacio** [comment]
I don't think you need to install the package yourself. Amplify has a pre-beta version of 0.8.19 as a dependency, it will be installed for you. So, make sure that `zen-observable-ts` is not a dependency in your `package.json` file and try again.

If that does not work, then I will ask the team if we can update to 1.0.0+, which are the versions that do not have a default export.

**Comment by kyleownsaterrier** [comment]
I fixed the dependency issues and now I can build and deploy on AWS Amplify. Thank you for your help!
