### ISSUE TITLE
Delete user and register again will make login not work if save devices is set.

### ISSUE THREAD

**Issue by Amaya88** [aws-amplify/amplify-js#8895]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Environment information

<details>

```
# Put output below this line
 System:
    OS: macOS 11.4
  Binaries:
    Node: 15.2.0 - ~/.nvm/versions/node/v15.2.0/bin/node
    npm: 7.17.0 - ~/.nvm/versions/node/v15.2.0/bin/npm
  Browsers:
    Chrome: 93.0.4577.63
  npmPackages:
    @aws-amplify/ui-react: ^1.2.10 => 1.2.10 
    aws-amplify: ^4.2.4 => 4.2.9 
    aws-sdk: ^2.975.0 => 2.987.0 

```

</details>

### Describe the bug

If you delete some user in cognito and then you register with that user again (same username/email) you will become an error when trying to log in ( "Device not found."). It seems that it tries to use the device key stored in localstorage for that user with same email that existed before deleting it and all it devices in cognito. It also seems not posible to delete this key, cause you need to be logged in in order to use the functions for delete cached device.

### Expected behavior

Devices are in this case automatish deleted or there is a function to delete this devices 

### Reproduction steps

1 - Configure your user pool to use emall as username
2 -  Register and log in with a user
3 - Delete that user in Cognito
4 - Register new user with same email
5 - All in same browser, try to log in with that user

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @Amaya88 I tried to reproduce this issue with the steps you listed but I was able to login into the second account after deleting the first and having devices remembered. Can you share how your user pool is configured in the Attributes tab?

these are my User Pool attribute settings for comparison:

<img width="1097" alt="Screen Shot 2021-09-21 at 2 48 41 PM" src="https://user-images.githubusercontent.com/16952986/134229798-5321c63e-a3d3-402d-aa77-8980c81ea238.png">

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!

**Comment by kaldebert** [comment]
Hi @chrisbonifacio !
I have the same issue when using aws-amplify@4.3.4.
The user pool is configured to always remember devices and MFA is disabled.
When the user signs in with a device key that does not exist anymore in the user pool, an exception is thrown:
```
{
  "__type": "ResourceNotFoundException",
  "message": "Device does not exist."
}
```
The error is ok but it would be great if aws-amplify could handle it and retry without the device key, or provide a method to clear the device key from the local storage.
