### ISSUE TITLE
Cannot setup Auth with email singup via official guide

### ISSUE THREAD

**Issue by pwnreza** [aws-amplify/amplify-js#8908]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 11.5.2
    CPU: (8) arm64 Apple M1
    Memory: 182.86 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.0/bin/yarn
    npm: 7.14.0 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome: 93.0.4577.63
    Firefox: 88.0.1
    Safari: 14.1.2
  npmPackages:
    @ampproject/toolbox-optimizer:  undefined ()
    @babel/core:  undefined ()
    @material-ui/core: ^4.12.3 => 4.12.3 
    amphtml-validator:  undefined ()
    arg:  undefined ()
    async-retry:  undefined ()
    async-sema:  undefined ()
    aws-amplify: ^4.1.0 => 4.1.1 
    aws-amplify-react: ^5.0.2 => 5.0.3 
    babel-eslint: ^10.1.0 => 10.1.0 
    babel-plugin-inline-react-svg: ^2.0.1 => 2.0.1 
    bfj:  undefined ()
    cacache:  undefined ()
    ci-info:  undefined ()
    comment-json:  undefined ()
    compression:  undefined ()
    conf:  undefined ()
    content-type:  undefined ()
    cookie:  undefined ()
    css-loader:  undefined ()
    cypress: ^7.5.0 => 7.5.0 
    debug:  undefined ()
    devalue:  undefined ()
    escape-string-regexp:  undefined ()
    eslint: ^7.28.0 => 7.28.0 
    eslint-config-airbnb: ^18.2.1 => 18.2.1 
    eslint-config-next: 11.0.1 => 11.0.1 
    eslint-config-prettier: ^8.3.0 => 8.3.0 
    eslint-import-resolver-alias: ^1.1.2 => 1.1.2 
    eslint-plugin-import: ^2.23.4 => 2.23.4 
    eslint-plugin-jsx-a11y: ^6.4.1 => 6.4.1 
    eslint-plugin-prettier: ^3.4.0 => 3.4.0 
    eslint-plugin-react: ^7.24.0 => 7.24.0 
    eslint-plugin-react-hooks: ^4.2.0 => 4.2.0 
    file-loader:  undefined ()
    find-cache-dir:  undefined ()
    find-up:  undefined ()
    fresh:  undefined ()
    graphql: ^15.5.0 => 15.5.0 (14.0.0)
    gzip-size:  undefined ()
    http-proxy:  undefined ()
    ignore-loader:  undefined ()
    ini: ^2.0.0 => 2.0.0 
    inquirer: ^8.1.0 => 8.1.1 
    is-animated:  undefined ()
    is-docker:  undefined ()
    is-wsl:  undefined ()
    json5:  undefined ()
    jsonwebtoken:  undefined ()
    loader-utils:  undefined ()
    lodash.curry:  undefined ()
    lru-cache:  undefined ()
    mini-css-extract-plugin:  undefined ()
    nanoid:  undefined ()
    neo-async:  undefined ()
    next: ^11.1.0 => 11.0.1 
    ora:  undefined ()
    postcss-flexbugs-fixes:  undefined ()
    postcss-loader:  undefined ()
    postcss-preset-env:  undefined ()
    postcss-scss:  undefined ()
    prettier: ^2.3.1 => 2.3.1 
    prop-types: ^15.7.2 => 15.7.2 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    react-hook-form: ^7.12.0 => 7.12.0 
    recast:  undefined ()
    resolve-url-loader:  undefined ()
    sass-loader:  undefined ()
    schema-utils:  undefined ()
    semver:  undefined ()
    send:  undefined ()
    source-map:  undefined ()
    start-server-and-test: ^1.12.5 => 1.12.5 
    string-hash:  undefined ()
    strip-ansi:  undefined ()
    terser:  undefined ()
    text-table:  undefined ()
    unistore:  undefined ()
    web-vitals:  undefined ()
    webpack:  undefined ()
    webpack-sources:  undefined ()
  npmGlobalPackages:
    @aws-amplify/cli: 5.6.0
    npm: 7.14.0
    sass: 1.34.0
    yarn: 1.22.10

```

</details>

### Describe the bug

I followed following [guide](https://docs.amplify.aws/guides/authentication/email-only-authentication/q/platform/js/) (https://docs.amplify.aws/guides/authentication/email-only-authentication/q/platform/js/) to setup auth via email but it has not worked. It still requires an username for signup.

The signup looks like following:

`
Auth.signUp({
            username: "myemail@provider.com",
            password: "somepassword",
            attributes: {
                email: "myemail@provider.com",
            }
        });
`

When I try signing up like this I receive following error message in my response:
"Username cannot be of email format, since user pool is configured for email alias."

### Expected behavior

The expected behaviour would be to be able to signup and signin via email.

### Reproduction steps

1. Setup amplify project
2. follow this guide to setup auth: https://docs.amplify.aws/guides/authentication/email-only-authentication/q/platform/js/
3. signup and signin via email

### Code Snippet

```javascript
// Put your code below this line.
Auth.signUp({
            username: "myemail@provider.com",
            password: "somepassword",
            attributes: {
                email: "myemail@provider.com",
            }
        });
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hey @pwnreza there are some issues we're ironing out in the CLI. You can get around this error by passing an arbitrary username for the user like so:

```js
Auth.signUp({
  username: String(Date.now()),
  password: "somepassword",
  attributes: {
    email: "myemail@provider.com",
  },
});
```

the email attribute is the important part

**Comment by oliverschenk** [comment]
I have the same issue. Last week it was working fine, I was able to `amplify add auth` using phone number only signup without username and it was working fine. Now, no matter how I answer the questions in the Amplify CLI when adding auth, it always ends up creating a Cognito configuration that includes username AND phone/email rather than email only or phone number without username.

**Comment by chrisbonifacio** [comment]
@oliverschenk you can try downgrading to 5.1.2 or wait for our next release where we address the issue. Either way, the auth resource would have to be recreated.

**Comment by chrisbonifacio** [comment]
@pwnreza @oliverschenk We just released CLI v6.0.0 (`@aws-amplify/cli`) which should address this issue. Please upgrade your CLI versions and try creating your auth resource again.

**Comment by oliverschenk** [comment]
This works fine now with v6.0.0. thanks

**Comment by pwnreza** [comment]
Thanks for the fix. The Signup does work with the amplify/cli v6+

But after signing up with email and getting a autogenerated username the signin does not work.

signup works 
`
Auth.signUp({
    username: "myemail@provider.com",
    password: "somepassword",
    attributes: {
        email: "myemail@provider.com",
    }
});
`

signin afterwards does not work
`
Auth.signIn("myemail@provider.com", "somepassword");

Auth.signIn({
    username: "myemail@provider.com",
    password: "somepassword"
});
`

what does work is to use the autogenerated username in the cognito user pool to signin.

best regards
