### ISSUE TITLE
Store multiple identity providers data in Auth instance

### ISSUE THREAD

**Issue by Abror1997** [aws-amplify/amplify-js#8909]
When I try to use `Auth.federatedSignIn` with multiple providers, Auth instance clears the previous signed-in providers' data and stores only the last signed-in provider data. Is it possible to store previous providers' data among with the last signed-in provider?

**Comment by chrisbonifacio** [comment]
Hi @Abror1997 can you explain your use case a bit more and provide some examples of what you mean such as code snippets, output logs, and/or screenshots?

**Comment by Abror1997** [comment]
Steps of reproduce:
 1. I sign in with facebook IdP and cognito instance saves the facebook data (like attributes, sub, username, ...)
 2. Then, I sign in with google IdP

Actual Result:
 - `CognitoUser` instance overrides the facebook data and stores only google IdP's data

Expected Result:
 - `CognitoUser` instance stores both facebook and google IdPs' data

@chrisbonifacio Please let me know if it is still not clear for you

**Comment by chrisbonifacio** [comment]
@Abror1997 Okay, I see what you mean but I'm still not sure why you would want to store both? How would you know that the person signing in through a different social provider is the same user? Currently there is no link between federated identities in Cognito. You would have to implement that in your API and manage that association (probably using email as the unique identifier between social providers).

**Comment by Abror1997** [comment]
@chrisbonifacio I see, then I have to store every IdP data in my own storage by provider name. Thank you for your explanation! Now, I am closing this issue.
