### ISSUE TITLE
[Error] ReferenceError: Can't find variable: Buffer

### ISSUE THREAD

**Issue by iamnogada** [aws-amplify/amplify-js#8914]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication, Not applicable

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
npx envinfo --system --binaries --browsers --npmPackages --duplicates --npmGlobalPackages

  System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.90 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.6.1 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.20.3 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 93.0.4577.82
    Firefox: 89.0.2
    Safari: 14.1.2
  npmPackages:
    @babel/core: ^7.9.0 => 7.15.5 (7.9.0)
    @expo/vector-icons: ^12.0.0 => 12.0.5
    @react-native-async-storage/async-storage: ~1.15.0 => 1.15.8
    @react-native-community/eslint-config:  1.1.0
    @react-native-community/eslint-plugin:  1.0.0
    @react-native-community/netinfo: 6.0.0 => 6.0.0
    @react-navigation/bottom-tabs: ^6.0.5 => 6.0.5
    @react-navigation/native: ^6.0.2 => 6.0.2
    @react-navigation/native-stack: ^6.1.0 => 6.1.0
    @types/react: ~16.9.35 => 16.9.56 (17.0.21)
    @types/react-native: ~0.63.2 => 0.63.53
    HelloWorld:  0.0.1
    aws-amplify: ^4.2.9 => 4.2.9
    aws-amplify-react-native: ^5.0.3 => 5.0.3
    babel-plugin-inline-view-configs:  0.0.5
    expo: ~42.0.1 => 42.0.3
    expo-asset: ~8.3.2 => 8.3.3
    expo-constants: ~11.0.1 => 11.0.2
    expo-font: ~9.2.1 => 9.2.1
    expo-linking: ~2.3.1 => 2.3.1
    expo-splash-screen: ~0.11.2 => 0.11.4
    expo-status-bar: ~1.0.4 => 1.0.4
    expo-web-browser: ~9.2.0 => 9.2.0
    hermes-inspector-msggen:  1.0.0
    jest-expo: ~41.0.0-beta.0 => 41.0.0
    react: 16.13.1 => 16.13.1
    react-animated:  0.1.0
    react-dom: 16.13.1 => 16.13.1
    react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
    react-native-codegen:  0.0.2
    react-native-gesture-handler: ~1.10.2 => 1.10.3
    react-native-reanimated: ~2.2.0 => 2.2.2
    react-native-safe-area-context: 3.2.0 => 3.2.0
    react-native-screens: ~3.4.0 => 3.4.0
    react-native-web: ~0.13.12 => 0.13.18
    typescript: ~4.0.0 => 4.0.8
  npmGlobalPackages:
    @aws-amplify/cli: 5.6.0
    @expo/ngrok: 4.1.0
    @vue/cli: 4.5.13
    expo-cli: 4.11.0
    express-generator: 4.16.1
    json-server: 0.16.3
    katacoda-cli: 0.0.22
    npm: 7.20.3
    react-native-cli: 2.0.1
    to: 0.2.9
    typescript: 4.4.3
    update: 0.7.4
    yarn: 1.22.11

```

</details>

### Describe the bug

After npm install or yarn install,

iOS Emulator can't run at code
"
Amplify.configure(config);
" in App.tsx

### Expected behavior

It shoudl run in emulator

### Reproduction steps

1. npm install -g expo-cli  
2. expo init RNAmplify
3. cd RNAmplify
4. npm install aws-amplify aws-amplify-react-native @react-native-community/netinfo @react-native-async-storage/async-storage
5. edit code 'App.tsx'
import Amplify from 'aws-amplify'
import config from './src/aws-exports'
Amplify.configure(config)
6. expo start

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line
ReferenceError: Can't find variable: Buffer
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0

```

</details>

**Comment by Nidhinkmadhu** [comment]
Same issue coming up on version  4.2.9

**Comment by abepuentes** [comment]
I just installed the package and this error show up

**Comment by abepuentes** [comment]
I would like to add some information, I've been doing some testing and for me actually the error was not from aws-amplify 4.2.9 but from aws-amplify-react-native 5.0.1.
No error about "can't find variable: Buffer" using aws-amplify-react-native 5.0.0, aws-amplify 4.29 and amazon-cognito-identity-js 5.0.4. The app works as usual with this combination of versions.

**Comment by sammartinez** [comment]
https://github.com/aws/aws-sdk-js-crypto-helpers/pull/217

**Comment by sammartinez** [comment]
This issue has now been resolved, please let us know if you are still experiencing this issue after reinstalling your `node_modules` and updating your `package-lock.json` or `yarn.lock`

**Comment by abepuentes** [comment]
> This issue has now been resolved, please let us know if you are still experiencing this issue after reinstalling your `node_modules` and updating your `package-lock.json` or `yarn.lock`

@sammartinez thanks for the info. It is actually working fine now.
