### ISSUE TITLE
(amazon-cognito-identity-js) `error` should be an Error object

### ISSUE THREAD

**Issue by naseemkullah** [aws-amplify/amplify-js#8919]
callback is taking non-error object as error, this causes pain further up (down?) the stack when trying to handle such errors with tooling that treats Error objects specially

**Comment by naseemkullah** [comment]
referring to:

https://github.com/aws-amplify/amplify-js/blob/419e530e88bac14fa03b9696ce32fe02f23820c7/packages/amazon-cognito-identity-js/src/Client.js#L115-L120


and


https://github.com/aws-amplify/amplify-js/blob/419e530e88bac14fa03b9696ce32fe02f23820c7/packages/amazon-cognito-identity-js/src/Client.js#L131-L137

and

https://github.com/aws-amplify/amplify-js/blob/419e530e88bac14fa03b9696ce32fe02f23820c7/packages/amazon-cognito-identity-js/src/Client.js#L143-L148

**Comment by chrisbonifacio** [comment]
Hi @naseemkullah 👋 Would you like to submit a PR for the changes you're suggesting?

**Comment by naseemkullah** [comment]
Hi @chrisbonifacio, sure!

**Comment by naseemkullah** [comment]
Hi @chrisbonifacio, https://github.com/aws-amplify/amplify-js/pull/8923 opened, PTAL 🙏
