### ISSUE TITLE
Broken; Unhelpful Type Declarations in Storage APIs (and others?)

### ISSUE THREAD

**Issue by ericdrobinson** [aws-amplify/amplify-js#8925]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Storage

### Amplify Categories

storage

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 19.65 GB / 31.82 GB
  Binaries:
    Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (93.0.961.52)
    Internet Explorer: 11.0.19041.906
  npmGlobalPackages:
    npm: 6.14.14
    yarn: 1.22.11

```

</details>

### Describe the bug

Both of the `Storage` APIs that we have used so far have had incomplete Type Declarations. In one case, the Type Declarations that do exist generate errors.

The two APIs are [`list`](https://github.com/aws-amplify/amplify-js/blob/a047ce73abe98c3bf82e888c3afb4d2f911805f3/packages/storage/src/Storage.ts#L225) and [`put`](https://github.com/aws-amplify/amplify-js/blob/a047ce73abe98c3bf82e888c3afb4d2f911805f3/packages/storage/src/Storage.ts#L189). The API that causes the error is `put`.

Specifically, the type declarations are:

```ts
/**
 * List bucket objects relative to the level and prefix specified
 * @param {String} path - the path that contains objects
 * @param {Object} [config] - { level : private|protected|public, maxKeys: NUMBER }
 * @return - Promise resolves to list of keys for all objects in path
 */
list(path: any, config?: any): Promise<any>;

/**
 * Put a file in storage bucket specified to configure method
 * @param {string} key - key of the object
 * @param {Object} object - File to be put in bucket
 * @param {Object} [config] - { level : private|protected|public, contentType: MIME Types,
 *  progressCallback: function }
 * @return - promise resolves to object on success
 */
put(key: string, object: any, config?: any): Promise<Object>;
```

The problems here are many:

1. `list` has a return type of `Promise<any>`. The `any` type here doesn't help anyone. In fact, in order to understand the shape of data, users have to debug or otherwise log the structure of the results to determine what the function actually returns. This frequently means testing _many_ different inputs to verify different conditions (e.g. no results [in this case an empty array]). This could (should) be clearly expressed in the return type.
2. `put` has a return type of `Promise<Object>`. The `Object` type here is problematic because it can't be assigned to many other types. Attempts to set the result to a reasonable object shape (in this case, a custom interface of shape `{ key: string; }`) results in an error:
   ```
   The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
   ```
   Both `any` and `object` would likely suffice here, though an _actual_ type declaration that defined the shape of the output properly would be preferable.
3. The parameter types are lacking in detail. This is actually somewhat frustrating as the documentation comments for both `config` parameters _are_ the types themselves!

### Expected behavior

As a developer working with the Amplify library, I expect top-notch Type Declarations that assist me in writing code and exploring the API. I should be able to select "Go to Definition" in Visual Studio Code (or any other TypeScript-enabled JavaScript IDE) and jump to the exact shape of an object that I'm working with. I should not have to define my own interfaces to describe the shape of objects returned from or expected by the Amplify library, but rather I should be able to import them from the library itself.

At the very least I should not have to type-coerce to make the TypeScript compiler happy due to issues with the type declarations in the library itself:

```ts
interface PutResult
{
	/** The object's path within the bucket. */
	key: string;
}

const uploadResult: PutResult = await Storage.put(key, file) as unknown as PutResult;
```

### Reproduction steps

1. Install the AmplifyJS library into a TypeScript environment.
2. Configure everything to support the Storage library.
3. Start using the Storage APIs with proper type declarations in either TypeScript or type-checked JavaScript.

**Comment by jamesaucode** [comment]
Thanks for raising the issue. The new Typescript definition for Storage is shipped with the latest release which will hopefully solve the issues you have. 😄
