### ISSUE TITLE
The issue #6000 still happening (App doesn't open on tapping the Notification)

### ISSUE THREAD

**Issue by agloks** [aws-amplify/amplify-js#8947]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Push Notifications

### Amplify Categories

notifications

### Environment information

<details>

```
    "react-native": "0.63.4",
    "amazon-cognito-identity-js": "^4.5.7",
    "aws-amplify": "^3.3.27",
    "aws-amplify-react-native": "^4.3.0",
    "@aws-amplify/pushnotification": "^3.2.32",
    "@react-native-community/push-notification-ios": "^1.8.0",
    "@react-native-firebase/app": "^10.5.0",
```

</details>

### Describe the bug

The issue #6000 still happening, and not just it, after x time (normally no more than 2 hours) without open it, the notification can't open the application.

### Expected behavior

The issue #6000 working as expected and the notification be able to open the application after long time in idle.  

### Reproduction steps

1)

Kill the App.
Send yourself a notification.
Open the App by clicking on the App Icon (Not Notification).
Kill the App again.
Tap on the notification.
You'll see that notification closes but App doesn't open.

2)

Kill the App.
Send yourself a notification.
Waiting for the minimum 2 hours.
Tap on the notification.
You'll see that notification closes but App doesn't open.

### Additional configuration

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="xxxxxxx">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="false"
      android:theme="@style/AppTheme"
      android:networkSecurityConfig="@xml/network_security_config">
      <activity
        android:name=".MainActivity"
        android:theme="@style/SplashTheme"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
            <action android:name="android.intent.action.DOWNLOAD_COMPLETE"/>
        </intent-filter>
        <intent-filter>
          <action android:name="android.intent.action.VIEW" />
          <category android:name="android.intent.category.DEFAULT" />
          <category android:name="android.intent.category.BROWSABLE" />
          <!-- Accepts URIs that begin with "xxx://root” -->
          <data android:scheme="xxx"
                android:host="root" />
        </intent-filter>
        <intent-filter>
          <action android:name="android.intent.action.VIEW" />
          <category android:name="android.intent.category.DEFAULT" />
          <category android:name="android.intent.category.BROWSABLE" />
          <!-- Accepts URIs that begin with "xxx://building/list” -->
          <data android:scheme="xxx"
                android:host="building"
                android:pathPrefix="/list" />
          <!-- note that the leading "/" is required for pathPrefix-->
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      <service
        android:name="com.amazonaws.amplify.pushnotification.RNPushNotificationMessagingService">
        <intent-filter>
          <action android:name="com.google.firebase.MESSAGING_EVENT"/>
        </intent-filter>
       </service>
       <!-- [END firebase_service] -->
       <!-- [START firebase_iid_service] -->
      <service
        android:name="com.amazonaws.amplify.pushnotification.RNPushNotificationDeviceIDService">
        <intent-filter>
          <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
        </intent-filter>
      </service>
      <receiver
        android:name="com.amazonaws.amplify.pushnotification.modules.RNPushNotificationBroadcastReceiver"
        android:exported="false" >
        <intent-filter>
          <action android:name="com.amazonaws.amplify.pushnotification.NOTIFICATION_OPENED"/>
        </intent-filter>
      </receiver>
      <receiver
        android:name="com.amazonaws.mobileconnectors.pinpoint.targeting.notification.PinpointNotificationReceiver" android:exported="false" >
        <intent-filter>
          <action android:name="com.amazonaws.intent.fcm.NOTIFICATION_OPEN" />
        </intent-filter>
      </receiver>
    </application>
</manifest>         
```

**Comment by brijesh2609** [comment]
hey, @chrisbonifacio any update or eta on this? Facing the same issue with a lot of users. any temporary solution/fix for this?

**Comment by Jemisson** [comment]
Any updates for this issue? Are there PRs that haven't been accepted yet? We are experiencing the same problem.

**Comment by Samaritan1011001** [comment]
@Jemisson The PR got in. Let me know if that fixes it for you.

**Comment by Jemisson** [comment]
> @Jemisson The PR got in. Let me know if that fixes it for you.

Updates were made according to the new MR sent.
The new versions I have in the project now are:
"@aws-amplify/pushnotification": "^4.3.5" / "aws-amplify": "^4.3.8" / "aws-amplify-react-native": "^6.0.1"
However, push notifications only had an increase in lifetime, going from the previous situation to a new period of 03 hours, repeating the previous problem after this time
To clarify further questions, is there a functional repository with tests that I can see/use as an example and check more details on why this continues to occur with this incidence of longer time?

**Comment by mtsymlov** [comment]
@Samaritan1011001 Maybe do you have idea why doesn't work yet after you fixed? :(

**Comment by Samaritan1011001** [comment]
@Jemisson  and @mtsymlov can you check and confirm you are seeing the issue only on Android Oreo or newer versions? If so, the recent PR could potentially fix it. It basically makes the intent provided to the notification explicit so the Android system can find the app and the component to call when the user taps on the notification with the app being in the killed state.

**Comment by abdallahshaban557** [comment]
@Jemisson @mtsymlov , did you get a chance to re-test this issue?

**Comment by Jemisson** [comment]
@Samaritan1011001 @abdallahshaban557 As none of the changes that were made had a positive effect, I changed the amplify service for another one.

**Comment by abdallahshaban557** [comment]
@Jemisson - that is unfortunate. We apologize for not being able to solve this issue earlier for you.

@mtsymlov - have you been able to validate if the recent PR has fixed the issue for you?

**Comment by tannerabread** [comment]
@agloks @brijesh2609 @mtsymlov are you still experiencing this issue? Did @Samaritan1011001 's [comment](https://github.com/aws-amplify/amplify-js/issues/8947#issuecomment-1079474355) fit your use case and the PR solve the problem?

**Comment by tannerabread** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and are in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
