### ISSUE TITLE
Geo: first-class support for react-map-gl

### ISSUE THREAD

**Issue by mojodna** [aws-amplify/amplify-js#9013]
### Is this related to a new or existing framework?

React

### Describe the feature you'd like to request

[`react-map-gl`](https://visgl.github.io/react-map-gl/) is the defacto React wrapper for Mapbox GL JS / MapLibre GL JS. Amplify's Geo category should support it as a first-class target, as its use results in easier-to-understand code than embedding `Map` instances as React `ref`s and managing their lifecycle, options, sources, and layers separately.

### Describe the solution you'd like

I'd like a component-driven way to embed a map within a web app. It could be as simple as a wrapper that passes all unconsumed props and child elements to `<ReactMapGL>` along with a `transformRequest` function constructed using Amplify Auth + Geo configuration.

### Describe alternatives you've considered

Manually configuring `ReactMapGL` components with a `transformRequest` function constructed using `maplibre-gl-js-amplify`. Credential and `transformRequest` handling is awkward and could be simplified by Amplify.

```javascript
import { ICredentials } from "@aws-amplify/core";
import { Geo, AmazonLocationServiceMapStyle } from "@aws-amplify/geo";
import Amplify, { Auth } from "aws-amplify";
import { AmplifyMapLibreRequest } from "maplibre-gl-js-amplify";
import { useEffect, useState } from "react";
import ReactMapGL, {
  MapRequest,
  NavigationControl,
} from "react-map-gl";

import awsconfig from "./aws-exports";

import "maplibre-gl/dist/maplibre-gl.css";
import "./index.css";
import { TransformRequestFunction } from "maplibre-gl";

Amplify.configure(awsconfig);
Geo.configure(awsconfig);

const App = () => {
  const [credentials, setCredentials] = useState<ICredentials>();
  const [transformRequest, setRequestTransformer] =
    useState<TransformRequestFunction>();

  useEffect(() => {
    const fetchCredentials = async () => {
      setCredentials(await Auth.currentUserCredentials());
    };

    fetchCredentials();
  }, []);

  // create a new transformRequest function whenever the credentials change
  useEffect(() => {
    const makeRequestTransformer = async () => {
      if (credentials != null) {
        const tr = new AmplifyMapLibreRequest(credentials, (Geo.getDefaultMap() as AmazonLocationServiceMapStyle).region)
          .transformRequest;
        // wrap the new value in an anonymous function to prevent React from recognizing it as a
        // function and immediately calling it
        setRequestTransformer(() => tr);
      }
    };

    makeRequestTransformer();
  }, [credentials]);

  return (
    <div>
      {transformRequest ? (
        <ReactMapGL
          width="100%"
          height="100vh"
          transformRequest={
            transformRequest as (
              url?: string,
              resourceType?: string
            ) => MapRequest
          }
          mapStyle={Geo.getDefaultMap().mapName}
        >
          <div style={{ position: "absolute", left: 20, top: 20 }}>
            <NavigationControl showCompass={false} />
          </div>
        </ReactMapGL>
      ) : (
        <h1>Loading...</h1>
      )}
    </div>
  );
};
```

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by Milan-Shah** [comment]
I am pleased to let you know that we have made a pre package release for React Map Component on Feb 24th. It is build upon `react-map-gl` and [Amplify UI](https://github.com/aws-amplify/amplify-ui) which will allow customers to easily add /customize maps and search capabilities for their React application. We will do a formal GA release in early March. Stay tuned! 👍

**Comment by thaddmt** [comment]
This should be resolved with the MapView component - https://ui.docs.amplify.aws/react/components/geo#mapview

**Comment by ErikCH** [comment]
Since this has been resolved, I'll close it!
