### ISSUE TITLE
Allow user to deleter their own account

### ISSUE THREAD

**Issue by Jukez17** [aws-amplify/amplify-js#9059]
### Is this related to a new or existing framework?

React Native

### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

I would like to allow user to delete their own account when they press button.

### Describe the solution you'd like

It should be simple auth function that takes either the username or access token as a parameter of the currently authenticated user.

Like as follows: Auth.DeleteUser(accessToken)

### Describe alternatives you've considered

Making an custom lambda but it would be a lot more extra work.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by chrisbonifacio** [comment]
Hi @Jukez17 👋 thanks for opening this feature request. This is technically already possible. You can have a user delete themselves like so:

```js
const handleDeleteCognitoUser = async () => {
  const user = await Auth.currentAuthenticatedUser();
  user.deleteUser((error, data) => {
    if (error) {
      throw error;
    }
  // do stuff after deletion
  });
};
```

as mentioned on this [issue](https://github.com/aws-amplify/amplify-js/issues/469#issuecomment-640509418)
