### ISSUE TITLE
License in NPM incorrect for amazon-cognito-identy-js

### ISSUE THREAD

**Issue by Anthony-Mckale** [aws-amplify/amplify-js#9068]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

Came up during a eze management console, licensing audit, the license in NPM for package amazon-cognito-identity-js appears to be incorrect

In NPM Audit and on npm's page

https://www.npmjs.com/package/amazon-cognito-identity-js

this license is "SEE LICENSE IN LICENSE.txt"

However I believe this should be "Apache-2.0"

as per the other amplify projects aka
https://www.npmjs.com/package/aws-amplify

source file is https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/package.json

"license": "SEE LICENSE IN LICENSE.txt",

### Expected behavior

I believe this should be "Apache-2.0"

on https://www.npmjs.com/package/amazon-cognito-identity-js

### Reproduction steps

go to https://www.npmjs.com/package/amazon-cognito-identity-js

look at license

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

![image](https://user-images.githubusercontent.com/585681/138303928-969b4c84-ceee-4d03-8169-5126d7e00392.png)

**Comment by tannerabread** [comment]
Hi 👋 Closing this as resolved. The license now displays the correct `Apache-2.0`

Thank you!
