### ISSUE TITLE
Unable to setAuthenticationFlowType when using Authenticator component 

### ISSUE THREAD

**Issue by risaac** [aws-amplify/amplify-js#909]
Do you want to request a feature or report a bug?

Feature

What is the current behavior?

At the moment when using the Authenticator component CognitoUser is set to authenticationFlowType = 'USER_SRP_AUTH' by default. @yuntuowang I would like the ability to change this, while still being able to keep the plug and play ability that is currently in place.  

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify.

What is the expected behavior?

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

**Comment by ZhuangER** [comment]
I think this feature is necessary. Currently, I am trying to migrate user data from MySQL to Cognito now. The flow type has to be set as 'USER_PASSWORD_AUTH', otherwise the migration trigger will not be fired.

I can only use amazong-cognito-identity-js as the solution now.

**Comment by agonbina** [comment]
It is very surprising this hasn't been taken care of already (and even more so the fact that this works in the `amazon-cognito-identity-js`library and does not in amplify). 

Moreover it is listed as a configuration option in the documentation, could you please remove it if you don't plan to make it functional? That way we save us some time trying to understand why the library does not behave as it is described in the documentation.

**Comment by agonbina** [comment]
Can confirm that this is fixed/works in the unstable release.

**Comment by mduecker** [comment]
> Can confirm that this is fixed/works in the unstable release.
Which release? 
For me it's not working on aws-amplify@1.1.8-unstable.1

**Comment by sammartinez** [comment]
This [documentation](https://aws-amplify.github.io/docs/js/authentication#manual-setup) shows the manual setup to change the default value of `USER_SRP_AUTH ` to what you prefer. Resolving as this is implemented
