### ISSUE TITLE
Invariant Violation: Picker has been removed from React Native. It can now be installed and imported from '@react-native-picker/picker' instead of 'react-native'. See https://github.com/react-native-picker/picker

### ISSUE THREAD

**Issue by ekeklol** [aws-amplify/amplify-js#9112]
Hope I'm submitting this to the appropriate place.

Trying to use the default auth UI provided by amplify but, when pressing the Sign Up button, this error appears

`Invariant Violation: Picker has been removed from React Native. It can now be installed and imported from '@react-native-picker/picker' instead of 'react-native'. See https://github.com/react-native-picker/picker`

<img width="463" alt="Screenshot 2021-10-16 at 19 58 26" src="https://user-images.githubusercontent.com/7149015/137596427-aaccf379-15c8-4cf8-a397-a630fb3f4f91.png">

Thinking it's a version mismatch of react-native and a workaround would be to create my own auth components

**Comment by calebpollman** [comment]
Closing as a duplicate of https://github.com/aws-amplify/amplify-js/issues/6845

**Comment by ameer0706** [comment]
Invariant Violation: Picker has been removed from React Native. It can now be installed and imported from '@react-native-picker/picker' instead of 'react-native'. See https://github.com/react-native-picker/picker

**Comment by ameer0706** [comment]
Invariant Violation: Picker has been removed from React Native. It can now be installed and imported from '@react-native-picker/picker' instead of 'react-native'. See https://github.com/react-native-picker/picker

**Comment by mikeRChambers610** [comment]
I am not using Picker from React-Native. Only in the '@react-native-picker/picker' so why am I getting this issue still???
