### ISSUE TITLE
aws-amplify datastore sqlite-adapter issue with connections [NOT NULL constraint]

### ISSUE THREAD

**Issue by cybexai** [aws-amplify/amplify-js#9128]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

DataStore

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line

"dependencies": {
    "@aws-amplify/datastore-storage-adapter": "^1.1.10",
    "@azure/core-asynciterator-polyfill": "^1.0.0",
    "@react-native-async-storage/async-storage": "^1.15.9",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^6.0.2",
    "amazon-cognito-identity-js": "^5.2.0",
    "aws-amplify": "^4.3.2",
    "aws-amplify-react-native": "^5.0.4",
    ...
  },
```

</details>

### Describe the bug

We're receiving NOT NULL constraint when retrieving data from datastore. These NOT NULL constraints affects entities with "connections". 

### Expected behavior

We want the data of all entities to be retrieved from datastore

### Reproduction steps

type Enterprise
  @model
  @auth(
    rules: [
      {
        allow: owner
        ownerField: "belongTo"
      }
    ]
  ) {
  id: ID!
  name: String!
  image: String
  contact: String
  Departments: [Department!]
    @connection(keyName: "byEnterprise", fields: ["id"])
  belongTo: String!
}

...

type Department
  @model
  @key(name: "byEnterprise", fields: ["enterpriseID"])
  @auth(
    rules: [
      {
        allow: owner
        ownerField: "belongTo"
      }
    ]
  ) {
  id: ID!
  name: String!
  options: AWSJSON
}

...

await DataStore.query(
Enterprise,
(enterprise) => enterprise.isDeleted("eq", false),
{
sort: (s) => s.name(SortDirection.DESCENDING),
}
)

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line
 
Possible Unhandled Promise Rejection (id: 3):
Object {
  "code": 6,
  "message": "NOT NULL constraint failed: Enterprise.Departments",
}

```

</details>

### Mobile Device

iPhone 6, iPhone Xr, LG G6, Xiaomi Redmi

### Mobile Operating System

iOS 14.5, iOS 12.5, Android 9,10

**Comment by iartemiev** [comment]
Thank you for opening the issue. We've opened a PR with the fix: https://github.com/aws-amplify/amplify-js/pull/9166

**Comment by cybexai** [comment]
thanks

**Comment by iartemiev** [comment]
Closing, as this is fixed as of `@aws-amplify/datastore-storage-adapter@1.1.11`
