### ISSUE TITLE
Pinpoint integration causes `Error: No credentials, applicationId or region` on multiple versions

### ISSUE THREAD

**Issue by naaaateeee** [aws-amplify/amplify-js#9131]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication, Analytics

### Amplify Categories

auth, analytics

### Environment information

<details>

```
System:
    OS: Linux 5.14 Fedora 34 (KDE Plasma)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 1.46 GB / 15.29 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.18.1 - /usr/bin/node
    npm: 6.14.15 - /usr/bin/npm
  Browsers:
    Firefox: 93.0
  npmGlobalPackages:
    @aws-amplify/cli: 5.3.1
    @microsoft/rush: 5.50.0
    @openscreen/sdk: 0.3.0
    aws-cdk: 1.118.0
    aws-sdk: 2.968.0
    eslint: 7.32.0
    pnpm: 6.7.1
    typescript: 4.3.5
```

</details>

The only package that is related to the issue is `aws-amplify`. The issue is captured on several `3.x.x` and `4.x.x` versions, incl. the latest one.

### Describe the bug

Trying to have Cognito events (signups and signins) + session starts/ends appear in Pinpoint console. After creating a Congito User Pool and Pinpoint project outside Amplify (without using CLI) and putting them into `Amplify.configure({...})` no events are being recorded.
The only indication of the issue is a console message on the web app itself. See **Log Output** below.

### Expected behavior

Auth usage (`signIn`, `signUp`, etc) as well as session starts being recorded by Pinpoint and are visible in Pinpoint Console. 

### Reproduction steps

Prerequisites are a Pinpoint project and Cognito User Pool
<details>

CDK, **but doable through web console**
```typescript
// see '@aws-cdk/aws-pinpoint'
const app = new CfnApp(this, 'PinpointApp', {
      name: 'PinpointApp',
})
// cfnUserPoolClient instance of CfnUserPoolClient class in '@aws-cdk/aws-cognito'
cfnUserPoolClient.analyticsConfiguration = {
      applicationArn: app.attrArn
      userDataShared: true,
}
```

</details>

The steps are:
1. Install `aws-amplify`.
2. Amplify is configured with Auth and Analytics categories as per [Amplify docs](https://docs.amplify.aws/lib/analytics/getting-started/q/platform/js/#set-up-existing-analytics-backend). See code snippet below

### Code Snippet

```tsx
Amplify.configure({
  Auth: {
    region: 'xxx',
    userPoolId: 'xxx',
    userPoolWebClientId: 'xxx'
  },
  Analytics: {
    disabled: false,
    autoSessionRecord: true,
    AWSPinpoint: {
        appId: 'xxx',
        region: 'xxx'
    },
  }
})
```

### Log output

<details>

```
Uncaught (in promise) Error: No credentials, applicationId or region
    at AWSPinpointProvider.eval (AWSPinpointProvider.js:176)
    at step (AWSPinpointProvider.js:55)
    at Object.eval [as next] (AWSPinpointProvider.js:36)
    at fulfilled (AWSPinpointProvider.js:27)
```

</details>

### Manual configuration

```javascript
const awsmobile = {
  Auth: {
    region: 'xxx',
    userPoolId: 'xxx',
    userPoolWebClientId: 'xxx'
  },
  Analytics: {
    disabled: false,
    autoSessionRecord: true,
    AWSPinpoint: {
        appId: 'xxx',
        region: 'xxx'
    },
  }
}
```

### Additional information

After going through 4-5 similar issues, I've tried multiple solutions, none of which have worked. In most of them it appears that people who got their issue resolved had it due to mismatching package versions or duplicates, which isn't the case for me.
Attaching `mandatorySignIn: false` to `Auth` category for `.configure({...})` as per similar closed issues didn't work.

**Comment by chrisbonifacio** [comment]
Hi @naaaateeee :wave: can you please share the dependencies related to `aws-amplify` in your package.json?

Sounds like you did try to check for duplicate package versions but just in case, seeing what you're working with might still help in reproducing your issue. This page might be helpful as well if you haven't already seen it.

https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js/

**Comment by naaaateeee** [comment]
> Hi @naaaateeee wave can you please share the dependencies related to `aws-amplify` in your package.json?
> 
> Sounds like you did try to check for duplicate package versions but just in case, seeing what you're working with might still help in reproducing your issue. This page might be helpful as well if you haven't already seen it.
> 
> https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js/

Hey @chrisbonifacio!
The only amplify related package I got installed on the web app is `"aws-amplify": "^3.3.27"`

**Comment by chrisbonifacio** [comment]
Just to be sure, are you importing the `Analytics` library in your project and calling `Analytics.record()` to record events? If so, can you share code snippets of how it's being called?

**Comment by chrisbonifacio** [comment]
thank you! curious, how are you importing and using the Analytics library in your code?

**Comment by chrisbonifacio** [comment]
I was able to reproduce this issue and found that you need to configure a Cognito Identity Pool with an unauthenticated role with permissions to allow PutEvents and UpdateEndpoints on your pinpoint resource.

So, in the Pinpoint console,

1. Go to the Settings tab on the left and click Web App analytics and from there you can get a convenient policy to copy/paste

2. You can click "Create an identity pool"

<img width="1060" alt="Screen Shot 2021-11-03 at 1 12 59 PM" src="https://user-images.githubusercontent.com/16952986/140136237-e78d0010-efe2-4958-ae0a-37bdc662db42.png">

3. In the Identity Pool configuration, enable access to unauthenticated identities

<img width="1197" alt="Screen Shot 2021-11-03 at 1 14 38 PM" src="https://user-images.githubusercontent.com/16952986/140138581-a19f7597-f208-40dd-9089-592bb45feb6a.png">

4. Paste the policy from the Pinpoint Web app analytics page and click "Allow"

<img width="815" alt="Screen Shot 2021-11-03 at 1 18 56 PM" src="https://user-images.githubusercontent.com/16952986/140144036-43acd1e3-4acb-4dcc-a7e6-aac90c34b2c4.png">

5. Add the Identity Pool ID to your Amplify config in the app

```js
Amplify.configure({
  Auth: {
    region: "xxx",
    userPoolId: "xxx",
    userPoolWebClientId: "xxx",
    identityPoolId: "xxx",
  },
  Analytics: {
    disabled: false,
    autoSessionRecord: true,
    AWSPinpoint: {
      appId: "xxx",
      region: "xxx,
    },
  },
});
```

**Comment by chrisbonifacio** [comment]
If you're curious, this is how I was able to see that you needed to configure an Identity Pool by using the Amplify Debug Logger.

index.js
```
Amplify.Logger.LOG_LEVEL = "DEBUG";
```

Output with no `identityPoolId` property in Auth config

<img width="1452" alt="Screen Shot 2021-11-03 at 1 24 28 PM" src="https://user-images.githubusercontent.com/16952986/140151292-866a4b93-4a3e-48b6-ad2e-bd1d91f25e10.png">

**Comment by naaaateeee** [comment]
@chrisbonifacio thanks for the help!
Thing is, my issue happened with an authenticated user.
The way I'm importing Amplify is sort of like this:
```javascript
import Amplify, { Auth } from 'aws-amplify';
import awsmobile from './aws-exports'
Amplify.configure(awsmobile);
// ... some signup function
await Auth.signIn(u, p)
// ... some other function
await Auth.signout()
// etc
```
I don't export Analytics because I don't record any specific events myself, I just want to have Auth events captured as part of Cognito Analytics (see cognito => user pool => general settings side menu => analytics)
I also did not configure an identity pool as I don't anticipate giving unauth access.

**Comment by chrisbonifacio** [comment]
Oh okay, I think I understand your use case. You'll still need to have an identity pool ID if using the Amplify Analytics library to record any events.

However, based off your use case, you can enable Cognito analytics in the console by navigating to your User Pool -> Analytics -> select an App Client and Pinpoint project.

You will need to adjust the IAM role permissions for the Auth Role of your Identity Pool. I configured mine like so:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "mobileanalytics:PutEvents",
                "mobiletargeting:PutEvents",
                "mobiletargeting:UpdateEndpoint",
                "cognito-sync:*",
                "cognito-identity:*"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```
Afterwards, I can see that my app is automatically recording auth events and sending them to Pinpoint.

Sign Up
<img width="1063" alt="Screen Shot 2021-11-04 at 2 47 30 PM" src="https://user-images.githubusercontent.com/16952986/140401321-dec532ac-30b6-4768-b892-d3be8565afad.png">

Sign In
<img width="1063" alt="Screen Shot 2021-11-04 at 2 46 27 PM" src="https://user-images.githubusercontent.com/16952986/140401343-19409d0a-2cb1-49d4-8c6a-6685ed5f5885.png">

Sign Out
<img width="1063" alt="Screen Shot 2021-11-04 at 2 48 53 PM" src="https://user-images.githubusercontent.com/16952986/140401447-16ee05be-967b-4ad5-a961-5a603b51fa2c.png">

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!
