### ISSUE TITLE
Return code delivery details list after updateUserAttributes

### ISSUE THREAD

**Issue by jvliwanag** [aws-amplify/amplify-js#9134]
### Is this related to a new or existing API?

Authentication

### Is this related to another service?

Cognito

### Describe the feature you'd like to request

UpdateUserAttributes when called directly on the Cognito API returns a code delivery details list in its response as documented [here](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateUserAttributes.html#API_UpdateUserAttributes_ResponseElements). It would be useful to expose these details directly on the API for any UI bindings to direct to the respective verification step.

### Describe the solution you'd like

Return codeDeliveryDetails on updateUserAttributes API.

### Describe alternatives you've considered

Guess if code verification is required based on prior knowledge of the user pool configuration.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by sammartinez** [comment]
Thanks for opening up this feature request @jvliwanag. Can you provide a little more information on your use case. We do have this functionality built into our UI components with sending the event to a `ConfirmSignUp` which will change the UI state to the confirmation code section. Currently, the code is sent via email for users to put into.

**Comment by jvliwanag** [comment]
Hi @sammartinez . The code delivery details list I believe is the indicator what, if any, are the required confirmation steps right after calling updateAttributes. If there are cognito lambda hooks to auto verify, then there's no need to prompt the user for verification. If there are none, then updating special fields such as email/mobile can put the identifiers to an awaiting verification state, which the client can know of through the code delivery details list.

**Comment by nolde** [comment]
I've made a PR to support this partially, allowing it to pass though `amazon-cognito-identity-js`. Further work would be needed to allow it to pass through `@aws-amplify/auth`.

**Comment by helgabalashova** [comment]
Hi @jvliwanag,
we've added a feature that can help you identify what attributes require verification. You can read more about it in our docs in [this](https://docs.amplify.aws/lib/auth/manageusers/q/platform/js/#update-user-attributes) section. Let us know if you have further questions.

**Comment by nolde** [comment]
Hello @helgabalashova ,

Why not merge my PR in? It just returns the details straight in from the function call. It shouldn't conflict with the hub events, and it currently returns void, so no one is expecting it anyway.

**Comment by helgabalashova** [comment]
Hi @nolde,
we appreciate your input into this issue. The main reason we didn't merge your PR is that it would result in breaking change for customers who use cognito-identity-js package.

**Comment by nolde** [comment]
Hi @helgabalashova ,

Sorry, I disagree. An update from nothing, void, to something, is not a breaking change. If you are not expecting anything, there is nothing to break. Anyone using the library would be checking for error only, and then moving forward.

**Comment by helgabalashova** [comment]
Hi @nolde, the PR you have submitted is considered a breaking change for customers that are using the `cognito-identity-js` package. For example, in a scenario where a developer is parsing the results of updateAttributes , a developer that is checking for `result === SUCCESS` would now get `CodeDeliveryDetails` list instead.

**Comment by nolde** [comment]
Hi @helgabalashova ,

Indeed, you are correct, the callback does return `SUCCESS`. I've made the mistake to pay too much attention to the actual function's return, instead of callback.

That said, why not fix it? If your semantic-release is done correctly, and your release clearly states the breaking change, this seems to be the correct path to take. The API is returning a proper response, and I imagine it is far more useful than `SUCCESS`. I wouldn't also expect anyone to have problems with a change from a meaningless string to actual useful information.

**Comment by helgabalashova** [comment]
@nolde,
From an API design perspective your solution makes sense, and you're correct that semantically versioning a release of this change would prevent consuming apps from breaking. However, in the interest of minimizing major version releases, we decided to avoid a breaking change and go with a non-breaking, temporary fix before the next major version of `Auth` is released. Unfortunately, we won't be able to merge your PR, but we will consider the solution you've provided when we work on improving `cognito-identity-js` and `Auth` packages. Thanks again for your input.

**Comment by nolde** [comment]
Hi @helgabalashova ,

Ok, I understand. Thanks for taking the time to explain your reasoning.
