### ISSUE TITLE
Pinpoint error in Angular prod builds: No credentials, applicationId, or region

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-js#9156]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

Analytics

### Amplify Categories

analytics

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I started to use Analytics category. It's working fine in dev builds but in prod builds I get: 

```
Error: No credentials, applicationId or region
    at e.<anonymous> (AWSPinpointProvider.js:176)
    at AWSPinpointProvider.js:55
    at Object.next (AWSPinpointProvider.js:36)
    at a (AWSPinpointProvider.js:27)
    at l.invoke (zone.js:372)
    at Object.onInvoke (core.js:28677)
    at l.invoke (zone.js:371)
    at t.run (zone.js:134)
    at zone.js:1276
    at l.invokeTask (zone.js:406)
    at e.onInvokeTask (task-tracking.js:73)
    at l.invokeTask (zone.js:405)
    at Object.onInvokeTask (core.js:28664)
    at l.invokeTask (zone.js:405)
    at t.runTask (zone.js:178)
    at m (zone.js:582)
    at invokeTask (zone.js:491)
    at invoke (zone.js:476)
    at n.args.<computed> (zone.js:2541)
    at Z (zone.js:1213)
    at zone.js:1120
    at zone.js:1136
    at l.invoke (zone.js:372)
    at Object.onInvoke (core.js:28677)
    at l.invoke (zone.js:371)
    at t.run (zone.js:134)
    at zone.js:1276
    at l.invokeTask (zone.js:406)
    at e.onInvokeTask (task-tracking.js:73)
    at l.invokeTask (zone.js:405)
    at Object.onInvokeTask (core.js:28664)
    at l.invokeTask (zone.js:405)
    at t.runTask (zone.js:178)
    at m (zone.js:582)
    at invokeTask (zone.js:491)
    at invoke (zone.js:476)
    at n.args.<computed> (zone.js:2541)
```

### Expected behavior

Analytics should work in prod build. 

### Reproduction steps

Install and use Analytics category in Angular prod builds. 

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

Running angular 12.1.5 and aws-amplify 4.3.4

I tried running npm dedupe and also deleting node_modules and package-lock and doing fresh npm install with no resolution.

**Comment by hisham** [comment]
I enabled debug log and I see this error, but I do have Auth registered. However I'm using [Angular lazy loaded modules](https://angular.io/guide/lazy-loading-ngmodules), and the Analytics lib is used in a separate module than where Auth is registered. Maybe that's the issue. I'll look into further tmrw. 

You can see that Analytics is succesfully configured in the beginning but then later it fails. 

[DEBUG] 35:08.594 Amplify - component registered in amplify s {config: {…}, cacheCurSizeKey: 'aws-amplify-cacheCurSize', getItem: ƒ, setItem: ƒ, removeItem: ƒ}
instrument.js:109 [DEBUG] 35:08.597 Amplify - component registered in amplify e {_config: {…}, _pluggables: Array(0), _disabled: false, _trackers: {…}, record: ƒ}
instrument.js:109 [DEBUG] 35:08.599 AnalyticsClass - configure Analytics {aws_project_region: 'us-east-1', aws_cloud_logic_custom: Array(1), aws_appsync_graphqlEndpoint: 'https://<redact>.appsync-api.us-east-1.amazonaws.com/graphql', aws_appsync_region: 'us-east-1', aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS', …}
instrument.js:109 [DEBUG] 35:08.600 Parser - parse config (3) [{…}, 'to amplifyconfig', {…}]
instrument.js:109 [DEBUG] 35:08.604 AWSPinpointProvider - configure Analytics {disabled: undefined, appId: '<redact>', region: 'us-east-1'}
.....
[DEBUG] 35:09.647 AWSPinpointProvider - _public record {event: {…}, provider: undefined}
instrument.js:109 [DEBUG] 35:09.647 Credentials - getting credentials
instrument.js:109 [DEBUG] 35:09.648 Credentials - picking up credentials
instrument.js:109 [DEBUG] 35:09.648 Credentials - getting new cred promise
instrument.js:109 [DEBUG] 35:09.648 Credentials - checking if credentials exists and not expired
instrument.js:109 [DEBUG] 35:09.649 Credentials - need to get a new credential or refresh the existing one
**instrument.js:109 [DEBUG] 35:09.649 AWSPinpointProvider - ensure credentials error No Auth module registered in Amplify**
instrument.js:109 [DEBUG] 35:09.650 AWSPinpointProvider - cannot send events without credentials, applicationId or region

**Comment by hisham** [comment]
I also had similar error when using Storage category. 

At the end, what fixed is before I had the following: 

`Amplify.configure({ ...awsmobile, Auth: { authenticationFlowType: 'USER_PASSWORD_AUTH' })`

And when I changed it to: 

```
Amplify.configure(awsmobile);
Auth.configure({
  authenticationFlowType: 'USER_PASSWORD_AUTH',
});
```

Why? I have no idea.

**Comment by chrisbonifacio** [comment]
You may have to import Analytics and configure it separately, like you did with Auth. That should guarantee that it's included in the build and not lost due to tree shaking, which has been known to happen.

That being said, are you already using Analytics in the file where you're configuring Amplify, as in creating any events or enabling any auto tracking, etc?

**Comment by hisham** [comment]
No I'm not using Analytics in the file where I'm configuring Amplify. 

It turned out I guess I had to import Auth or else that would get lost in the tree shaking and caused Analytics and Storage to not work due to no Auth provider. 

Though API and logging into Cognito worked fine, perhaps because it was in same module or something.

**Comment by chrisbonifacio** [comment]
Okay, yeah if you import it and use it that should fix the problem, even just configuring it should do the trick. Let me know if that helps.

**Comment by hisham** [comment]
Yes that's what I ended up doing. Still the reality that this issue happened in prod and not dev caused me some downtime and another developer of aws-amplify can easily run into it again.
