### ISSUE TITLE
Typescript: Better Typings for Analytics methods

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-js#9162]
### Is this related to a new or existing framework?

Angular

### Is this related to a new or existing API?

Analytics

### Describe the feature you'd like to request

Analytics.record is confusing, I see multiple uses for it, well first here's what the typings say: 

```
    /**
     * Record one analytic event and send it to Pinpoint
     * @param {String} name - The name of the event
     * @param {Object} [attributes] - Attributes of the event
     * @param {Object} [metrics] - Event metrics
     * @return - A promise which resolves if buffer doesn't overflow
     */
    record(event: string | object, provider?: any, metrics?: EventMetrics): Promise<unknown>;
```

So is the second parameter provider or attributes? 

And then the documentation at https://docs.amplify.aws/lib/analytics/record/q/platform/js/#record-a-custom-event-with-attributes gives a very different way to do it: 

```
Analytics.record({
    name: 'albumVisit', 
    // Attribute values must be strings
    attributes: { genre: '', artist: '' }
});

```

Plus there's zero documentation on the "standard" events and attributes/metrics that pinpoint has such as '_monetization.purchase' and _item_price. 

### Describe the solution you'd like

Good consistent documentation. 

### Describe alternatives you've considered

Fishing around google and questioning my choice of using pinpoint. 

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [x] ⚠️ This feature might incur a breaking change

**Comment by sammartinez** [comment]
Thanks for this feedback and feature request @hisham. We will take this into consideration as this may lead to breaking changes. We will provide an update on a timeline for this work once we have groomed this item and gotten clarity on next steps

**Comment by cwomack** [comment]
The developer preview for v6 of Amplify has officially been released with improved support for TypeScript and much more! Please check out our [announcement](https://aws.amazon.com/blogs/mobile/aws-amplify-javascripts-new-developer-preview-with-reduced-bundle-sizes-improved-typescript-and-next-js-support/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=238088647) and updated [documentation](https://docs.amplify.aws/lib-v1/project-setup/create-application/q/platform/js/) to see what has changed.

This issue should be resolved within the dev preview and upcoming General Availability for Amplify v6, but let us know with a comment if there are further issues.

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
