### ISSUE TITLE
Trying to hide Username, Password and SignIn button completely in React but not able to override default Amplify function

### ISSUE THREAD

**Issue by ranopriyo-neogy** [aws-amplify/amplify-js#9196]
### Is this related to a new or existing framework?

React

### Describe the feature you'd like to request

I am trying to remove the two text fields along with Sign In button for the default login page but am not able to do so. I just want to keep Sign in with AWS and clear everything in the default Amplify UI. Not sure if there is a way to achieve it with formFields?

```
function App() {
  return (
    <AmplifyAuthenticator  >
    <div className="App">
     <Users></Users>
    </div>
    <AmplifySignIn 
              headerText="[ Sign in with AWS if you are a regular user]"
              formFields={[]}
    
    hideSignUp="true" slot="sign-in" >
    </AmplifySignIn>
    </AmplifyAuthenticator>
  );
}

export default App
```

![Screen Shot 2021-11-10 at 8 03 09 PM](https://user-images.githubusercontent.com/68603179/141218258-81c6c57b-536b-479f-ab54-1a0bcb88c3d6.png)

### Describe the solution you'd like

Should be a way to completely hide formFields as when required. 

### Describe alternatives you've considered

I did `formFields={[]}` however it didn't work. 

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by ranopriyo-neogy** [comment]
I am able to remove the username and password fields however not able to remove the Submit Button. I don't see any available documentations at Amplify to achieve it.  

<img width="581" alt="Screen Shot 2021-11-11 at 3 58 38 PM" src="https://user-images.githubusercontent.com/68603179/141368330-1bd78316-83fb-4fdc-bb58-d2fb0c462ac2.png">

```
function App() {
  return (
    <AmplifyAuthenticator>
        <AmplifyFormSection  slot="sign-in">
        <AmplifyOauthButton />
        </AmplifyFormSection>
    </AmplifyAuthenticator>
  );
}
```

**Comment by ashika01** [comment]
@ranopriyo-neogy is there a reason to wrap the `OAuthButton` inside the formsection? That might be bringing in the submit button.

Also is there a reason for not making use of `federated` prop here? Ref: https://github.com/aws-amplify/amplify-js/tree/main/packages/amplify-ui-components#amplify-authenticator-federated

**Comment by ericclemmons** [comment]
So I can better understand your use-case, it sounds like you need to replace the entire Sign In screen with just the _Sign in with AWS_ button (and perhaps some header text.

Does the `Authenticator` provide any additional value to you then?
(It also looks like the Sign Up screen is hidden/removed, too).

It sounds like a custom button that calls `Auth.federatedSign()` would meet your needs more easily. See:
> https://docs.amplify.aws/lib/auth/social/q/platform/js/#setup-frontend

**Comment by ranopriyo-neogy** [comment]
Thanks, @ericclemmons / @ashika01  - I solved it using Oauth button wrapping it in AmplifyAuthenticator. 

```
function App() {
  return (
    <AmplifyAuthenticator >
    <AmplifyOauthButton slot="sign-in" />
    <div className="App">
    <Users></Users>
   </div>
    </AmplifyAuthenticator> 
  );
}

```
