### ISSUE TITLE
Getting error "error on fetching instances Error: No current user" with initial login.

### ISSUE THREAD

**Issue by mguja-fcc** [aws-amplify/amplify-js#9212]
Getting error "error on fetching instances Error: No current user" with initial login. If I refresh the browser than no issue fetching data from the database. It works fine until authentication token expires. I implemented authentication as per the example https://docs.amplify.aws/ui/auth/authenticator/q/framework/react/#use-cases below. I am fetching initial data under useEffect().

```
import React from 'react';
import './App.css';
import Amplify from 'aws-amplify';
import { AmplifyAuthenticator, AmplifySignOut } from '@aws-amplify/ui-react';
import { AuthState, onAuthUIStateChange } from '@aws-amplify/ui-components';
import awsconfig from './aws-exports';

Amplify.configure(awsconfig);

const AuthStateApp = () => {
    const [authState, setAuthState] = React.useState();
    const [user, setUser] = React.useState();

    React.useEffect(() => {
        return onAuthUIStateChange((nextAuthState, authData) => {
            setAuthState(nextAuthState);
            setUser(authData)
        });
    }, []);

  return authState === AuthState.SignedIn && user ? (
      <div className="App">
          <div>Hello, {user.username}</div>
          <AmplifySignOut />
      </div>
    ) : (
      <AmplifyAuthenticator />
  );
}

export default AuthStateApp;
```

**Amplify CLI Version** 

6.2.1

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**

**Comment by chrisbonifacio** [comment]
Hi @mguja-fcc 👋 thanks for raising this issue. I tried setting up a new amplify app with a basic auth flow and used the code snippet you shared but did not run into any issues. Maybe I'm not understanding your use case.

Can you copy/paste the contents of your package.json file here?

1. Are you getting this error before or after logging in?
2. What do you mean by "How can I fetch data only after authentication ?" from this [discussion](https://github.com/aws-amplify/amplify-js/discussions/9211)?

**Comment by mguja-fcc** [comment]
Hi,

   I was able to figure it out. It actually worked the way it should. I moved my pos authentication event to `<AmplifyAuthenticator handleAuthStateChange={handleAuthStateChange}>` where `handleAuthStateChange` function is fetching data from the database. I do not fetch data from `useEffect` react hook since it tries to fetch data before authentication happens.

**Comment by chrisbonifacio** [comment]
Ahh, nicely done! Glad to hear it's working for you 😄
