### ISSUE TITLE
DataStore SQLite not compatible with Android API Level 30 - Invalid Database Handle

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-js#9218]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

DataStore

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line
npx: installed 1 in 1.12s

  System:
    OS: Linux 4.14 Amazon Linux 2
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
    Memory: 6.45 GB / 7.50 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 10.24.1 - ~/.nvm/versions/node/v10.24.1/bin/node
    npm: 6.14.12 - ~/.nvm/versions/node/v10.24.1/bin/npm
  npmGlobalPackages:
    @aws-amplify/cli: 6.4.0
    cdk: 1.105.0
    coffeescript: 2.5.1
    esformatter: 0.11.3
    js-beautify: 1.13.13
    npm: 6.14.12
    prettier: 2.3.0
    typescript: 3.7.5

```

</details>

### Describe the bug

To publish apps to the Google Play Store after 1st November 2021 your app must support the Android API Level 30.

This error doesn't happen on iOS or on Android API Level 29. 

```
Error: Invalid database handle
at newSQLError (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:310478:18)
at SQLitePlugin.abortAllPendingTransactions (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:310655:23)
at http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:310768:17
at MessageQueue.__invokeCallback (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:5086:18)
at http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:4791:18
at MessageQueue.__guard (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:4999:13)
at MessageQueue.invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:4790:14)
at http://localhost:8081/debugger-ui/debuggerWorker.aca173c4.js:4:902
```

### Expected behavior

DataStore SQLite Adapter works the same on Android API Level 30 as it does with 29

### Reproduction steps

Upgrade Android API to Level 30

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Mobile Device

Android

### Mobile Operating System

API Level 30

**Comment by sacrampton** [comment]
Hi @iartemiev - one for your SQLite Adapter.

**Comment by iartemiev** [comment]
I just loaded up the application I use for testing DataStore with the SQLite adapter on react-native@0.65.2 on a virtual Pixel 5 device running Android 11 / API 30 and did not get any errors. Tested `DataStore.start`, `clear`, `observe`, `save`, `query`, and `delete`.

Could you try deleting the application from the device (including any application data) and then re-installing it?

If that doesn't help, please provide the following:

1. What are the steps you took to upgrade to Android API 30? 
2. Which version of React Native are you on? 
3. Do you see this error when your app first starts up or after some user action is taken? 
4. If on start, which DataStore method is getting called right before you see this error? 
5. Are you experiencing this in an emulator or a physical device? 
6. Is this a fresh install of your application on this device? Or was the application installed when the device was on Android 10 and then upgraded to 11?

**Comment by iartemiev** [comment]
Another thing you can try: https://github.com/andpor/react-native-sqlite-storage/issues/496#issuecomment-963869396

**Comment by sacrampton** [comment]
Hi @iartemiev - we try this (https://github.com/aws-amplify/amplify-js/issues/9218#issuecomment-968413088) - \ - andpor/react-native-sqlite-storage#496 (comment)'

The errror gets resolved, but response of datastore query gets very slow like the way it was working before introducing sqlite in datastore.

**Comment by sacrampton** [comment]
@iartemiev - responses to your questions:

1. What are the steps you took to upgrade to Android API 30?
> Just Updating buildscript ext  
> buildToolsVersion = "30.0.2"
> minSdkVersion = 21
> compileSdkVersion = 30
> targetSdkVersion = 30     

2. Which version of React Native are you on?
> "react-native": "0.63.3",

3. Do you see this error when your app first starts up or after some user action is taken?
> Getting error when calling  
> await DataStore.start()

4. If on start, which DataStore method is getting called right before you see this error?
> await DataStore.start()

5. Are you experiencing this in an emulator or a physical device?
> Physical device

6. Is this a fresh install of your application on this device? Or was the application installed when the device was on Android 10 and then upgraded to 11?
>Getting Issue In Both Case

**Comment by sacrampton** [comment]
Hi @chrisbonifacio & @iartemiev - some further updates

We have upgraded the react-native version to 0.65.2 but sqlite issue is still there for API level 30.

The AWS lib version which we are using currently is - "aws-amplify": "^4.1.3-rn-sqlite.5"

**Comment by iartemiev** [comment]
Looks like you're still on the preview version of Amplify. You can upgrade to latest, but then just make sure to follow the React Native > Use SQLite portion of [this section](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js/#option-1-platform-integration) of the docs. I'm not sure that would have any effect on this issue, but it's still a good idea to upgrade to the stable version.

Have you been able to reproduce this issue on an Android emulator as well? My physical device only runs Android 10 unfortunately, so I can only test this on an emulator and I'm not able to reproduce the error there.

**Comment by sacrampton** [comment]
Hi @iartemiev & @chrisbonifacio 

We have tried everything, by upgrading react native version to 0.65.2 & upgrading aws-amplify version to 4.3.6

It works find on Android 10 - but fails on Android 11 with API Level 30. It works on Android 11 with API Level 29.

With Android 11 / API Level 30 the following error is thrown as soon as you start datastore.

```
Error: Invalid database handle
at newSQLError (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:310478:18)
at SQLitePlugin.abortAllPendingTransactions (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:310655:23)
at http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:310768:17
at MessageQueue.__invokeCallback (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:5086:18)
at http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:4791:18
at MessageQueue.__guard (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:4999:13)
at MessageQueue.invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:4790:14)
at http://localhost:8081/debugger-ui/debuggerWorker.aca173c4.js:4:902
```

**Comment by iartemiev** [comment]
Have you been able to reproduce this issue on an Android emulator as well?

**Comment by sacrampton** [comment]
Hi @chrisbonifacio  @iartemiev 

To fix this we added AsyncStorage_db_size_in_MB=1024 in the gradle.properties file.
