### ISSUE TITLE
Can't find variable : self 

### ISSUE THREAD

**Issue by vkanagarajan** [aws-amplify/amplify-js#9236]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Storage

### Environment information

 "react-native": "0.59.9",
"react": "16.8.3",

### Describe the bug

Install "@aws-amplify/datastore": "^3.6.1", package in terminal 
After importing the package name in screen 
Run the app Getting error

### Expected behavior

After installed the package without error run the app 

### Reproduction steps

Install "@aws-amplify/datastore": "^3.6.1", package in terminal 
After importing the package name in screen 
Run the app Getting error

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

![Simulator Screen Shot - iPad 6thGeneration - 2021-10-21 at 17 47 13](https://user-images.githubusercontent.com/53504749/142209939-1eb5b5ba-a141-4480-8128-0dabd3e48d40.png)

**Comment by sammartinez** [comment]
Thanks for opening this issue @vkanagarajan. Can you provide your `package.json` along with your environment settings? 

Please use the follow command: 
```
npx envinfo --system --binaries --browsers --npmPackages --npmGlobalPackages
```

Thanks ahead of time!

**Comment by vkanagarajan** [comment]
System:
    OS: macOS 11.0.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 42.70 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 13.10.1 - /usr/local/bin/node
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 96.0.4664.45
    Firefox: 94.0.1
    Safari: 14.0.1
  npmPackages:
    @babel/core: 7.4.5 => 7.4.5 
    @babel/runtime: 7.4.5 => 7.4.5 
    @react-native-async-storage/async-storage: 1.13.2 => 1.13.2 
    @react-native-community/async-storage: 1.6.1 => 1.6.1 
    @react-native-community/netinfo: 3.2.1 => 3.2.1 
    @react-native-community/push-notification-ios: 1.8.0 => 1.8.0 
    @sentry/react-native: ^3.1.1 => 3.2.3 
    appcenter: 2.5.0 => 2.5.0 
    appcenter-analytics: 2.5.0 => 2.5.0 
    appcenter-crashes: 2.5.0 => 2.5.0 
    awesome-react-native-video-controls: 1.0.7 => 1.0.7 
    aws-amplify: 2.2.7 => 2.2.7 
    axios: 0.18.0 => 0.18.0 
    babel-eslint: 8.2.1 => 8.2.1 
    babel-jest: 24.8.0 => 24.8.0 
    babel-preset-es2016: 6.24.1 => 6.24.1 
    backbone-events-standalone: 0.2.7 => 0.2.7 
    buffer: 6.0.3 => 6.0.3 
    compare-versions: 3.6.0 => 3.6.0 
    dateformat: 3.0.3 => 3.0.3 
    email-validator: 2.0.3 => 2.0.3 
    eslint: 4.12.1 => 4.12.1 
    eslint-plugin-babel: 5.0.0 => 5.0.0 
    eslint-plugin-promise: 3.6.0 => 3.6.0 
    eslint-plugin-react: 7.5.1 => 7.5.1 
    graphql-tag: 2.6.1 => 2.6.1 
    ini: ^1.3.5 => 1.3.8 
    inquirer: ^6.5.1 => 6.5.2 
    jest: 24.8.0 => 24.8.0 
    lodash: 4.17.15 => 4.17.15 
    metro-react-native-babel-preset: 0.55.0 => 0.55.0 
    moment: 2.22.1 => 2.22.1 
    nsp: 3.2.1 => 3.2.1 
    pre-commit: 1.2.2 => 1.2.2 
    react: 16.8.3 => 16.8.3 
    react-native: 0.59.9 => 0.59.9 
    react-native-animatable: 1.2.4 => 1.2.4 
    react-native-appstore-version-checker: 3.0.0 => 3.0.0 
    react-native-autosuggest: 1.0.1 => 1.0.1 
    react-native-bcrypt: 2.4.0 => 2.4.0 
    react-native-blink-view: 0.0.6 => 0.0.6 
    react-native-camera: 3.18.0 => 3.18.0 
    react-native-check-app-install: 0.0.5 => 0.0.5 
    react-native-check-box: 2.1.3 => 2.1.3 
    react-native-code-push: 5.6.1 => 5.6.1 
    react-native-cookies: 3.2.0 => 3.2.0 
    react-native-datepicker: 1.6.0 => 1.6.0 
    react-native-datetime-picker: 1.1.2 => 1.1.2 
    react-native-device-info: 5.5.4 => 5.5.4 
    react-native-easy-grid-view: 0.1.1 => 0.1.1 
    react-native-easy-listview-gridview: 1.0.3 => 1.0.3 
    react-native-easy-toast: 1.2.0 => 1.2.0 
    react-native-error-boundary: 1.1.0 => 1.1.0 
    react-native-fetch-blob: 0.10.8 => 0.10.8 
    react-native-fit-image: 1.5.5 => 1.5.5 
    react-native-flexi-radio-button: 0.2.2 => 0.2.2 
    react-native-fs: 2.14.1 => 2.14.1 
    react-native-image-crop-picker: 0.24.0 => 0.24.0 
    react-native-image-pan-zoom: 2.1.3 => 2.1.3 
    react-native-image-placeholder: 1.0.14 => 1.0.14 
    react-native-iphone-x-helper: 1.2.1 => 1.2.1 
    react-native-keep-awake: 2.0.6 => 2.0.6 
    react-native-keyboard-aware-scroll-view: 0.4.4 => 0.4.4 
    react-native-local-notifications: 2.0.0 => 2.0.0 
    react-native-material-buttons: 0.5.0 => 0.5.0 
    react-native-material-dropdown: 0.9.0 => 0.9.0 
    react-native-material-ripple: 0.8.0 => 0.8.0 
    react-native-material-textfield: 0.12.0 => 0.12.0 
    react-native-modal-dropdown: 0.6.2 => 0.6.2 
    react-native-pdf: 5.0.2 => 5.0.2 
    react-native-permissions: 1.1.1 => 1.1.1 
    react-native-popover-view: 1.0.19 => 1.0.19 
    react-native-progress: 3.4.0 => 3.4.0 
    react-native-push-notification: git+https://github.com/karthinidc/react-native-push-notification.git => 3.1.1 
    react-native-root-siblings: 3.2.3 => 3.2.3 
    react-native-router-flux: 4.0.6 => 4.0.6 
    react-native-segmented-control-tab: 3.4.1 => 3.4.1 
    react-native-sensitive-info: 5.1.0 => 5.1.0 
    react-native-signature-capture: 0.4.9 => 0.4.9 
    react-native-simple-events: 1.0.1 => 1.0.1 
    react-native-smart-timer-enhance: 1.0.3 => 1.0.3 
    react-native-sound-player: 0.10.1 => 0.10.1 
    react-native-spinkit: 1.3.0 => 1.3.0 
    react-native-sqlite-storage: ^3.3.6 => 3.3.11 
    react-native-super-grid: 2.0.2 => 2.0.2 
    react-native-tiny-toast: 1.0.7 => 1.0.7 
    react-native-toast-native: 1.2.1 => 1.2.1 
    react-native-uuid-generator: 3.0.2 => 3.0.2 
    react-native-video: 5.0.0 => 5.0.0 
    react-native-web-service-handler: 1.0.2 => 1.0.2 
    react-native-webview: 10.2.1 => 10.2.1 
    react-native-zip-archive: 2.2.2 => 2.2.2 
    react-redux: 7.2.0 => 7.2.0 
    react-test-renderer: 16.8.3 => 16.8.3 
    redux: 4.0.5 => 4.0.5 
    redux-devtools-extension: 2.13.8 => 2.13.8 
    redux-logger: 3.0.6 => 3.0.6 
    redux-persist: 6.0.0 => 6.0.0 
    redux-saga: 1.1.3 => 1.1.3 
    redux-thunk: 2.3.0 => 2.3.0 
    rn-fetch-blob: 0.10.12 => 0.10.12 
    scandit-react-native: 5.18.3 => 5.18.3 
    timespan: 2.3.0 => 2.3.0 
    uuid: 3.2.1 => 3.2.1 
    validator: 10.8.0 => 10.8.0 
  npmGlobalPackages:
    @angular/cli: 9.1.0
    @aws-amplify/cli: 6.4.0
    appcenter-cli: 2.4.0
    create-react-app: 3.4.1
    eslint: 6.8.0
    InnovaZones: 0.0.1
    npm: 6.13.7
    react-native-cli: 2.0.1
    react-native-datetime-picker: 1.1.2
    react-native-push-notification: 8.1.1
    react-native-signature-capture: 0.4.12
    react-native-spinkit: 1.5.0
    react-native-sqlite-storage: 6.0.1
    scandit-react-native: 5.14.4

**Comment by sammartinez** [comment]
Thanks for this, super helpful. In looking at your dependencies, I am noticing that your `aws-amplify` version is a previous version to what is current. For Amplify DataStore dependencies for version `^3.6.1` does have a dependency on our version 4 of the library. Please see [this](https://github.com/aws-amplify/amplify-js/blob/main/packages/datastore/package.json#L51-L53). Please look to upgrade your dependencies to the latest version of `aws-amplify` and report back. Also, if you can provide code snippets it would be helpful to us as well.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!
