### ISSUE TITLE
Datastore throws duplicate subscriptions - Intermittent

### ISSUE THREAD

**Issue by Akash-T2S** [aws-amplify/amplify-js#9255]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

DataStore

### Amplify Categories

storage, interactions, predictions

### Environment information

<details>

```
# Put output below this line

System:
    OS: macOS 11.2.3
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 23.93 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 96.0.4664.55
    Safari: 14.0.3
  npmPackages:
    amazon-cognito-identity-js: 5.0.4 => 5.0.4 (5.1.1)
    aws-amplify: 4.2.10 => 4.2.10 
    aws-amplify-react-native: 5.0.3 => 5.0.3 
    axios: 0.21.1 => 0.21.1 (0.21.4)
    eslint: 7.15.0 => 7.15.0 
    eslint-config-prettier: 7.0.0 => 7.0.0 (6.15.0)
    eslint-plugin-jest: 24.1.3 => 24.1.3 (22.4.1)
    eslint-plugin-prettier: 3.2.0 => 3.2.0 (3.1.2)
    eslint-plugin-react: 7.21.5 => 7.21.5 
    file-loader: 6.2.0 => 6.2.0 
    file-saver: 2.0.5 => 2.0.5 
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-datetime: 3.1.1 => 3.1.1 
    react-devtools: 4.14.0 => 4.14.0 
    react-dom: 17.0.2 => 17.0.2 
    hermes-inspector-msggen:  1.0.0 
    html-webpack-plugin: 5.3.2 => 5.3.2 
    husky: 4.3.8 => 4.3.8 
    lint-staged: 10.5.3 => 10.5.3 
    localforage: 1.10.0 => 1.10.0 
    lodash: 4.17.20 => 4.17.20 (4.17.21)
    lottie-ios: 3.2.3 => 3.2.3 (3.1.8)
    lottie-react-native: 4.0.3 => 4.0.3 
    md5: 2.3.0 => 2.3.0 
    rn-fetch-blob: 0.12.0 => 0.12.0 
    rn-placeholder: 3.0.3 => 3.0.3 
  npmGlobalPackages:
    @aws-amplify/cli: 5.0.0
    code-push-cli: 2.1.9
    expo-cli: 4.7.2
    n: 7.3.0
    node-pre-gyp: 0.17.0
    npm-check-updates: 4.0.4
    npm: 6.14.13
    react-native-cli: 2.0.1
```

</details>

### Describe the bug

I have a application which uses Datastore for real time updates, The intermittent issue is the subscription gets duplicated when I receive from Datastore.observe. There is no internet interruption while this issue occurs. Also, while debugging with "    Amplify.Logger.LOG_LEVEL = 'DEBUG';" There is no duplication subscription in console whereas the duplication occurs when I receive message from Datastore.observe.

### Expected behavior

Through DataStore.observe I shouldn't receive duplicate subscription.

### Reproduction steps

1) Sync items from Datastore
2) Do multiple manipulation for different items through Datastore.Save.
3) Multiple subscriptions will get triggered.
4) Check subscriptions where fews subscriptions get duplicated where the _version and _lastChangedAt are same.

### Code Snippet

```javascript
// Put your code below this line.


 DataStore.configure({
            syncExpressions: [
                syncExpression(Order, (order) =>
                    order.storeId('eq', storeId).deliveryAt('ge', '2021:11:19 05:00:00')
                )
            ],
            syncPageSize: 500,
            maxRecordsToSync: 100000
        });

 orderSubscription = DataStore.observe(Order).subscribe(
            (msg) => {
               // Duplication msg arrives here.
                reactotron.log('msg', msg);
            },
            (err) => {}
        );
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Mobile Device

iOS Simulator
Reproduced in Android Physical device as well

### Additional information and screenshots

<img width="1134" alt="Screenshot 2021-11-19 at 3 59 51 PM" src="https://user-images.githubusercontent.com/39513832/142607976-dcec721a-6a10-44de-9451-384022e8074b.png">

**Comment by nubpro** [comment]
did u unsubscribed the observables within the return function of the useEffect?

**Comment by Akash-T2S** [comment]
We do unsubscribe at componentWillUnmount. The issue which I reported is not consistent. Out of 10 subscriptions 3 gets duplicated.

**Comment by evcodes** [comment]
Hey @Akash-T2S , thanks for opening this issue. Would you be able to provide your entire source code for this issue? It would help us better understand step 2 specifically. Can you also provide your schema?

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
