### ISSUE TITLE
authState and authData not both changing at once.

### ISSUE THREAD

**Issue by michaelcuneo** [aws-amplify/amplify-js#926]
Question.

I'm using Authenticator, and I've set an onStateChange={this.handleStateChange} ... which triggers when authState and authData have changed. I run an action inside the handleStateChange to set my props and store that the user has logged in... the handleStateChange takes both authState and authData both at once.

When I login with Cognito as a normal 'created' user, the authStatus and authData are filled immediately, and the program carries on like normal.

When I login with Facebook or Google, the delay between authState being set to signedIn and the authData being filled with information, I end up passing 'undefined' to the handleStateChange, very time. How do I get the handleStateChange to wait for the data. It can't be retriggered when the authData receives new data, it can't be callback'd, it can't be await/async, because the handleStateChange considers that it's a legitimate state change whether it's undefined ... or not.

Can we have maybe a onAuthStatusChange, and onAuthDataChange? Because they don't both fill themselves with data at once, or am I looking at this all wrong.

**Comment by mlabieniec** [comment]
@michaelcuneo I think you can use the Hub class for this:
https://aws.github.io/aws-amplify/media/hub_guide#listen

Since the <Authenticator> is canned for using with user pool sign in, i don't think the onStateChange will fire as you said for federated / social login since those HOCs are separate...but i think if you listen with Hub you will get it. Let me know what you think.

**Comment by michaelcuneo** [comment]
I've managed to get some authData from that... now I'm having more issues that I'll make a new post about. I'm literally baffled by the complete differences of structure and the inability to have a complete working example of either of the three login types. (Completely custom, Authenticator, Hosted) I've got all three login systems running side by side here for comparison, and for fallback, so I can switch between one to another, as one is updated and breaks... 

In this particular case, over the Authenticator version of my login, I can get the authData now, but it's lacking the information that I assumed that it would have. I have a tonne of custom attributes in the userPool. Authenticator is successfully taking federated users and adding them as a user in the Cognito User Pool, but now I need access to that data. I thought it would come back after logging in, through the authData, but it appears as though it's not there. So I've ran through all the available currentUserCredentials, currentAuthenticatedUser, narrowing it down to 'Auth.UserAttributes' which results in "Cannot read property 'getSession' of undefined.

**Comment by powerful23** [comment]
@michaelcuneo which version of Amplify are you using? The latest one is 0.4.1 which have a fix around the user object. Also you are saying using the cognito hosted ui to add those federated users into user pool right? Did you do the attributes mapping configuration in the Cognito User Pool console?

**Comment by michaelcuneo** [comment]
I am using 0.4.1 The Authenticator object was mapping my attributes into my User Pool as well as the Hosted UI. I think? I'm sure I got some mapped attributes into the UserPool from the Authenticator HOC. Either that or it's just matching them up after using the Hosted UI at least once when I tested the other login system at some point.
