### ISSUE TITLE
check user is verified

### ISSUE THREAD

**Issue by supun19** [aws-amplify/amplify-js#927]
is there any method to check user is verified or not.

**Comment by powerful23** [comment]
@supun19 you can get the user attributes by `Auth.currentUserInfo()` and there will be two attributes: `phone_verified` and `email_verified`

**Comment by yashutanna** [comment]
These attributes are no longer available in the latest version of amplify. is there something i am missing?

**Comment by mjmaix** [comment]
@yashutanna Make sure you have your Cognito UserPool properly configured. Your `amplify/backend/auth/<appname>/parameters.json` should have the `email_verified` and `phone_number_verified` in `userpoolClientReadAttributes`

```parameters.json
"userpoolClientReadAttributes": [
    "email",
    "email_verified",
    "family_name",
    "given_name",
    "phone_number",
    "phone_number_verified",
    "picture"
  ],
```

**Comment by kirandash** [comment]
Is there a way to check if a user is verified without logging in? Any method that tells if a user is verified with just username
