### ISSUE TITLE
API requests error with axios createError

### ISSUE THREAD

**Issue by txnico** [aws-amplify/amplify-js#9273]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

REST API

### Amplify Categories

api

### Environment information

  System:
    OS: macOS 11.6
    CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
    Memory: 296.13 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.13.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 96.0.4664.55
    Safari: 15.0
  npmPackages:
    @expo/vector-icons: ^12.0.0 => 12.0.3 (12.0.5)
    @ptomasroos/react-native-multi-slider: ^2.2.2 => 2.2.2 
    @react-native-async-storage/async-storage: ^1.15.5 => 1.15.5 
    @react-native-community/datetimepicker: 3.5.2 => 3.5.2 
    @react-native-community/eslint-config:  1.1.0 
    @react-native-community/eslint-plugin:  1.0.0 
    @react-native-community/masked-view: 0.1.10 => 0.1.10 
    @react-native-community/netinfo: 6.0.0 => 6.0.0 
    @react-native-picker/picker: 1.16.1 => 1.16.1 
    @react-navigation/bottom-tabs: ^5.11.1 => 5.11.2 
    @react-navigation/drawer: ^5.11.4 => 5.11.4 
    @react-navigation/native: ^5.8.9 => 5.8.10 (3.8.3)
    @react-navigation/stack: ^5.12.7 => 5.12.8 
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: ^5.0.6 => 5.2.3 
    aws-amplify: 4.3.8 => 4.3.8 
    aws-amplify-react-native: 5.0.3 => 5.0.3 
    babel-plugin-inline-view-configs:  0.0.5 
    babel-preset-expo: 8.3.0 => 8.3.0 (8.4.1)
    expo: ^42.0.0 => 42.0.3 
    expo-constants: ~11.0.1 => 11.0.1 
    expo-device: ~3.3.0 => 3.3.0 
    expo-localization: ~10.2.0 => 10.2.0 
    expo-location: ~12.1.2 => 12.1.2 
    expo-notifications: ~0.12.3 => 0.12.3 
    expo-permissions: ~12.1.1 => 12.1.1 
    hermes-inspector-msggen:  1.0.0 
    moment: ^2.29.1 => 2.29.1 
    native-base: 2.13.14 => 2.13.14 
    react: 16.13.1 => 16.13.1 
    react-animated:  0.1.0 
    react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
    react-native-appearance: ~0.3.3 => 0.3.4 
    react-native-chart-kit: 6.7.0 => 6.7.0 
    react-native-circular-progress: ^1.3.6 => 1.3.6 
    react-native-codegen:  0.0.2 
    react-native-gesture-handler: ~1.10.2 => 1.10.3 
    react-native-modal-datetime-picker: ^9.1.0 => 9.1.0 
    react-native-reanimated: ~2.2.0 => 2.2.0 
    react-native-responsive-linechart: ^5.7.1 => 5.7.1 
    react-native-safe-area-context: 3.2.0 => 3.2.0 
    react-native-screens: ~3.4.0 => 3.4.0 
    react-native-svg: 12.1.1 => 12.1.1 
    react-navigation: 4.4.3 => 4.4.3 
    react-navigation-drawer: ^1.4.0 => 1.4.0 
    react-navigation-stack: 1.10.3 => 1.10.3 
    react-navigation-tabs: ^1.2.0 => 1.2.0 
    sharp-cli: ^1.14.1 => 1.14.1 
  npmGlobalPackages:
    @aws-amplify/cli: 4.21.1
    create-react-native-app: 2.0.2
    eslint: 7.15.0
    expo-cli: 4.10.0
    npm: 6.14.8
    react-native-cli: 2.0.1

### Describe the bug

All API.get calls to any endpoint in AWS fail with "Network Error" in axiom core during connection create.

### Expected behavior

APi connections successful. 

API calls work as expected with aws-amplify 4.2.3 with no other code changes.

### Reproduction steps

- Install modules
- Load app
- App fails to load due to network error

### Code Snippet

```javascript
// Put your code below this line.

```
        const apiName = 'apiName';
        const path    = '/apiPath';
        const myInit = {
            headers: { 'Content-Type': 'application/json' }, 
            response: true, 
            queryStringParameters: {  
                'param1': 'type1'
            },
        };
        /*
            const { data: { body } } = error.response;
            console.log(body);
        */

        API
        .get(apiName, path, myInit)
        .then(response => {
            console.log("GOOD CALL, Response: ", response);
        })
        .catch(error => {
            const { data: { body } } = error.response;
            console.log(body);
        });

### Log output

<details>

```
// Put your logs below this line


```
at node_modules/axios/lib/core/createError.js:15:17 in createError
at node_modules/axios/lib/adapters/xhr.js:96:22 in handleError
at node_modules/react-native/Libraries/Network/XMLHttpRequest.js:600:10 in setReadyState
at node_modules/react-native/Libraries/Network/XMLHttpRequest.js:395:6 in __didCompleteResponse
at node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:189:10 in emit

</details>

**Comment by txnico** [comment]
Any status updates with this? 

Thanks

**Comment by chrisbonifacio** [comment]
Hi @txnico are you still experiencing this issue on the latest version of `aws-amplify`?

**Comment by txnico** [comment]
@chrisbonifacio - issue seems to be resolved in 

    "aws-amplify": "4.3.15",
    "aws-amplify-react-native": "6.0.3",
