### ISSUE TITLE
[Feature request] Support for local notifications in react-native

### ISSUE THREAD

**Issue by karlmosenbacher** [aws-amplify/amplify-js#928]
Do you want to request a feature or report a bug?
Feature

What is the current behavior?
Today, aws-amplify can only manage push notifications on Android and Ios (that I know). But to be able to handle more use-cases regarding notifications in an mobile application written in react-native, the library needs to be able to manage local notifications as well. 

Features that I am requesting are for instance:
- Show local notification immediately
- Schedule local notification 
- Get initial notification (A notification that starts an application if pressed)
- Show heads-up notification from local notification in Android
- Be able to set priority on a local notification in Android
... and more.

React-native-firebase is another library that offers this functionality, but I rather stay with aws-amplify.

**Comment by mlabieniec** [comment]
@karlmosenbacher thanks for the feedback! The latest service worker integration does support notifications. You can see an example [here](https://aws.github.io/aws-amplify/media/service_workers_guide#handling-a-push-notification). The [Notification Web API](https://developer.mozilla.org/en-US/docs/Web/API/notification) is fairly straight forward and simple. Can you provide a bit more detail on how you'd like to see Amplify help here more?

**Comment by karlmosenbacher** [comment]
@mlabieniec Thanks for your reply! I noticed that I missed some important information in my feature description and title. I will update it right away. I apologize!

**Comment by mlabieniec** [comment]
@karlmosenbacher thanks for the awesome feedback! We will add this to the backlog :)

**Comment by blacksheep--** [comment]
Any schedule for this? It shouldn't be a big deal to open the existing native code that is used to display the already working pinpoint (remote) push notifications to the public.

**Comment by elorzafe** [comment]
@karlmosenbacher 
* Get initial notification (A notification that starts an application if pressed) is already implemented. The other are still in our backlog.

**Comment by karlmosenbacher** [comment]
@elorzafe Great! Thanks for the reply!

**Comment by joebernard** [comment]
Bumping this as it is still a desired feature.

**Comment by zilurrane** [comment]
+1

**Comment by harrysolovay** [comment]
This is out of scope. One can implement notifications via [`onNotification` callbacks](https://docs.amplify.aws/lib/push-notifications/working-with-api/q/platform/js). [here's Expo's docs](https://docs.expo.io/versions/latest/sdk/notifications/), incase that's your preferred RN API.
