### ISSUE TITLE
Update types for Promises on Auth calls

### ISSUE THREAD

**Issue by jhechtf** [aws-amplify/amplify-js#9286]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React, Not applicable

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 5.41 GB / 15.87 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE       
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.34)
    Internet Explorer: 11.0.19041.1202
  npmGlobalPackages:
    pnpm: 5.18.3
```

</details>

### Describe the bug

**Note:** I do not use the Amplify CLI, and I am only using the @aws-amplify/auth package directly. I am also currently using the following packages/versions

```
@aws-amplify/core: v4.3.8
@aws-amplify/auth: v4.3.16 (both most recent version as of writing this)
```

The TypeScript definitions for the Auth package _heavily_ use the `any`  as a return type when they should be denoted as some other type.

### Expected behavior

The return types for the typescript definitions should _entirely_ remove the use of `any` in the return types of the methods.

### Reproduction steps

1. Create new project.
2. Install `@aws-amplify/core` and `@aws-amplfiy/auth`
3. Configure the Auth appropriately to use an AWS Cognito User Pool.
4. Attempt to use one of the many methods that has incorrect / insufficient type definitions associated.

### Code Snippet

the project that got this all started is located at https://github.com/vini-vici/front-end

Some examples:

```ts
import Auth from '@aws-amplify/auth';
// Return type of Auth.signIn is `Promise<any>` when the result is `CognitoUser`
const value = await Auth.signIn('user','very secure password'); 

// Return type for Auth.currentUserInfo() is `Promise<any>` when it is more accurately conveyed as `{ username: string; attributes: Record<string, string | boolean>}`
const currentUser = await Auth.currentUserInfo();

// return type `Promise<any>`
const confirmSignup = await Auth.confirmSignUp('new user', 'new password');

// Return type `Promise<any>`
const signedOut = await Auth.signOut();
```

### Log output

<details>

```
// Put your logs below this line

N/A
```

</details>

### Additional information and screenshots

Currently the work around is to have to manually type the statements, e.g.

```ts
const user = await Auth.signIn(username, password) as CognitoUser;
```

This becomes harder in more obscure places where it's much harder to tell what the return result actually is, or if it has an associated type in the definitions.

**Comment by sammartinez** [comment]
Thanks for this feedback @jhechtf. I have marked this as a feature request as this is something we are currently evaluating for the Auth Category. While we don't have a timeline at this moment as to when to expect for this TypeScript work to be completed, we will keep you updated once we have an update on this front. Thanks!

**Comment by jhechtf** [comment]
Thanks; let me know if there is anything i can do to assist.

**Comment by jhechtf** [comment]
Any word on this @sammartinez ?

**Comment by cwomack** [comment]
The developer preview for v6 of Amplify has officially been released with improved support for TypeScript and much more! Please check out our [announcement](https://aws.amazon.com/blogs/mobile/aws-amplify-javascripts-new-developer-preview-with-reduced-bundle-sizes-improved-typescript-and-next-js-support/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=238088647) and updated [documentation](https://docs.amplify.aws/lib-v1/project-setup/create-application/q/platform/js/) to see what has changed.

This issue should be resolved within the dev preview and upcoming General Availability for Amplify v6, but let us know with a comment if there are further issues.

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
