### ISSUE TITLE
Warning: No GraphQL endpoint configured

### ISSUE THREAD

**Issue by Dilip-Solanki-Logistic-Infotech** [aws-amplify/amplify-js#9293]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

DataStore

### Amplify Categories

auth, function, api

### Environment information

<details>

```
System:
  OS: Linux 4.15 Ubuntu 18.04.6 LTS (Bionic Beaver)
  CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
  Memory: 2.22 GB / 15.60 GB
  Container: Yes
  Shell: 4.4.20 - /bin/bash
Binaries:
  Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
  npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
Browsers:
  Chrome: 96.0.4664.45
  Firefox: 94.0
npmPackages:
  @aws-amplify/ui-react: ^2.1.2 => 2.1.2 
  @aws-amplify/ui-react-internal:  undefined ()
  @aws-amplify/ui-react-legacy:  undefined ()
  @testing-library/jest-dom: ^5.15.1 => 5.15.1 
  @testing-library/react: ^11.2.7 => 11.2.7 
  @testing-library/user-event: ^12.8.3 => 12.8.3 
  aws-amplify: ^4.3.8 => 4.3.8 
  aws-amplify-react: ^5.1.9 => 5.1.9 
  react: ^17.0.2 => 17.0.2 (16.14.0)
  react-dom: ^17.0.2 => 17.0.2 
  react-scripts: 4.0.3 => 4.0.3 
  web-vitals: ^1.1.2 => 1.1.2 
npmGlobalPackages:
  @aws-amplify/cli: 7.5.2
  corepack: 0.10.0
  npm: 8.1.0


```

</details>

### Describe the bug

I have updated the aws-amplify and aws-amplify-react versions to the latest.
Also, I have used the latest built-in auth UI in my react project.
But, I have get the following warning related to datastore.
`DataStore - Data won't be synchronized. No GraphQL endpoint configured. Did you forget Amplify.configure(awsconfig)?`

Also, it works well on older versions. This is the version list of the old package.

```
"@aws-amplify/ui-react": "^1.2.19",
"aws-amplify": "^4.3.3",
"aws-amplify-react": "^5.1.4",
"react": "^16.13.1",
"react-dom": "^16.13.1",
```

### Expected behavior

I expect to perfectly data sync in my project because it is worked previously on the same configuration.

### Reproduction steps

1. Install all dependency packages
2. Configure the AWS
3. Generate all models and schema for Datastore
4. Fire the Datastore query of the list/create/update
5. See the console log on browser

![image](https://user-images.githubusercontent.com/61177438/144018042-24aa5871-40d7-4302-9443-ea50dfe32834.png)

### Code Snippet

```
import Amplify from "aws-amplify";
import awsconfig from "./aws-exports";
Amplify.configure(awsconfig);
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

```
const awsmobile = {
  "aws_project_region": "us-east-1",
  "aws_cognito_identity_pool_id": "us-east-1:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": "us-east-XXXXXXXXX",
  "aws_user_pools_web_client_id": "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "oauth": {},
  "aws_appsync_graphqlEndpoint": "https://XXXXXXXXXXXXXXXXXXXXXXXXXXXX.appsync-api.us-east-1.amazonaws.com/XXXXXX",
  "aws_appsync_region": "us-east-1",
  "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
  "aws_appsync_apiKey": "XXXX-XXXXXXXXXXXXXXXXXXXXXXXX"
};
```

**Comment by chrisbonifacio** [comment]
Hi @Dilip-Solanki-Logistic-Infotech 👋 I created an amplify project with the dependencies and versions you listed but have not been able to reproduce this issue. Can you share the code where you're importing and using DataStore?

**Comment by Dilip-Solanki-Logistic-Infotech** [comment]
@chrisbonifacio
I have put the query in App.js.
Like,
```
useEffect(() => {
  DataStore.query(OrderVerTwo, Predicates.ALL).then(response => console.log(response));
}, []);
```

Also, I have added the Authenticator and Hub listen of auth and datastore in this App.js file.

**Comment by iartemiev** [comment]
Please try re-installing your NPM dependencies:

```
rm -rf node_modules package-lock.json yarn.lock
npm i  
(or `yarn` if you're using Yarn)
```

**Comment by Dilip-Solanki-Logistic-Infotech** [comment]
@iartemiev Already I tried many times.

**Comment by iartemiev** [comment]
Can you try executing this script: https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js/#check-for-duplicate-versions

**Comment by Dilip-Solanki-Logistic-Infotech** [comment]
Yes

**Comment by iartemiev** [comment]
Thanks, let us know what the output of the script is

**Comment by Dilip-Solanki-Logistic-Infotech** [comment]
Check for duplicate versions
![image](https://user-images.githubusercontent.com/61177438/144245503-5bca63bd-6920-4093-b3c5-5142002c798d.png)

Upgrade Amplify packages
![image](https://user-images.githubusercontent.com/61177438/144245974-0c09ef85-3b7e-4962-b419-809ea0f18705.png)

**Comment by iartemiev** [comment]
The duplicates script is showing that you have duplicate Amplify packages installed in your app. That's most likely what's causing the behavior you're seeing here. 

Can you share your lock file contents?

**Comment by chrisbonifacio** [comment]
I have a feeling the duplicates are being caused by the `aws-amplify-react` package, all of its peer dependencies are listed there and they seem to be v2-3 in its package.json.

https://github.com/aws-amplify/amplify-js/blob/main/packages/aws-amplify-react/package.json

If you're using the `@aws-amplify/ui-react` package, should be okay to remove `aws-amplify-react` from your dependencies and then try reinstalling them.

**Comment by Dilip-Solanki-Logistic-Infotech** [comment]
@chrisbonifacio @iartemiev
I removed the `aws-amplify-react` and it is working fine now.
Thank you.
