### ISSUE TITLE
Unknown directive "primaryKey". 

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/amplify-js#9297]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

GraphQL API

### Environment information

sh-3.2# npx envinfo --system --binaries --browsers --npmPackages --duplicates --npmGlobalPackages
Need to install the following packages:
  envinfo
Ok to proceed? (y) y
sh: envinfo: command not found

### Describe the bug

The new directives like primaryKey are unknown.

### Expected behavior

Using new directives here
https://docs.amplify.aws/cli/graphql/data-modeling/

### Reproduction steps

Amplify push

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @rudyhadoux 👋 what version of the CLI are you using? If you're on v7, did you run `amplify migrate api` first?

**Comment by rudyhadoux** [comment]
7.5.4
I had answers in ampli-cli repository.
Thanks.
