### ISSUE TITLE
npm ERR! notarget No matching version found for @aws-amplify/ui@2.0.4.

### ISSUE THREAD

**Issue by Nicktho** [aws-amplify/amplify-js#9302]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication, GraphQL API

### Amplify Categories

auth, api

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 11.3.1
    CPU: (8) arm64 Apple M1
    Memory: 185.30 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - /opt/homebrew/bin/node
    npm: 7.15.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Safari: 14.1
  npmPackages:
    @testing-library/jest-dom: ^5.15.1 => 5.15.1 
    @testing-library/react: ^11.2.7 => 11.2.7 
    @testing-library/user-event: ^12.8.3 => 12.8.3 
    @types/jest: ^26.0.24 => 26.0.24 
    @types/node: ^12.20.37 => 12.20.37 
    @types/react: ^17.0.37 => 17.0.37 
    @types/react-dom: ^17.0.11 => 17.0.11 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    react-scripts: 4.0.3 => 4.0.3 
    typescript: ^4.5.2 => 4.5.2 
    web-vitals: ^1.1.2 => 1.1.2 
  npmGlobalPackages:
    @aws-amplify/cli: 7.6.1
    aws-cdk: 1.132.0
    create-next-app: 11.0.1
    n: 7.1.0
    npm: 7.15.1
    pure-prompt: 1.16.0
    vercel: 23.0.1


```

</details>

### Describe the bug

Running `npm i aws-amplify` results in the error

```bash
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-amplify/ui@2.0.4.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tho/.npm/_logs/2021-12-02T23_16_56_139Z-debug.log
```

### Expected behavior

`aws-amplify` installs locally.

### Reproduction steps

1. `mkdir app & cd app & npm init`
2. `npx create-react-app . --template typescript`
3. `npm i aws-amplify`

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @aws-amplify/ui@2.0.4.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tho/.npm/_logs/2021-12-02T23_25_44_232Z-debug.log

```

</details>

**Comment by wesleymilan** [comment]
+1

**Comment by sammartinez** [comment]
Thanks for reporting this @Nicktho, we are looking to resolve this within the next hour. Please give us time to resolve this.

**Comment by sammartinez** [comment]
https://github.com/aws-amplify/amplify-js/pull/9303

**Comment by sammartinez** [comment]
@Nicktho we have resolved this issue, can you please re test with a new build and let us know if you are still experiencing this issue?

**Comment by drag0022** [comment]
Issue is fixed on my end. Thank you for the prompt fix

**Comment by sammartinez** [comment]
Awesome! I will go ahead and resolve this issue then

**Comment by Nicktho** [comment]
All good thanks @sammartinez

**Comment by wesleymilan** [comment]
Thank you @sammartinez for resolving this issue so fast, everything is ok now
