### ISSUE TITLE
How to implement redirection to a dynamic route after Auth.signout

### ISSUE THREAD

**Issue by jgf5013** [aws-amplify/amplify-js#9321]
### Is this related to a new or existing framework?

React

### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

TL;DR: How do you record basic information about the user's state prior to sign-out so that it can be used during the sign-in proces?

Longer version:
I'm using `customState` to record some information during the login process about where the user should go after they've successfully authenticated using 

```
  Auth.federatedSignIn({ provider, customState: queryParams });
```

Works great - thanks!!

Now I also want to record similarly basic information about where the user was when they signed out so that I can pass this information back to the sign-in page (so that, after signing in, the user can be redirected to the URL where they signed out from.)
But I don't see any way to do this as there's no `customState` parameter on the `Auth.signOut` function and redirection to the configured signout URL seems to happen immediately.

My understanding is that this signout URL can't be dynamic since

1. It must match what's in the AWS Cognito console
2. The config console parameter for Sign out URL(s) does not take wildcards.

Any help is very much appreciated!!

### Describe the solution you'd like

One of the two below

- Documentation on how to accomplish what I think is probably a supported workflow.
- Confirmation that this is not a supported workflow but that it should be and this will be turned into a proper feature request.

### Describe alternatives you've considered

- Dynamic or wild-card Cognito signout URLs or URLs where query parameters are accepted as "matching" the configured URLs (per my understanding, this is not permitted for security reasons)
- Manually redirecting user with window.location.href immediately after signout (doesn't work as Cognito sigout kicks in before and this just feels like a hacky solution)

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by jgf5013** [comment]
Any updates on this?

**Comment by evcodes** [comment]
Hey @jgf5013, this is pretty particular use case and I have dug around cognito's docs and could not find this being a supported use case. I believe that the best way to do this is to implement some logic on your signout function to [update the UserAttribute](https://github.com/aws-amplify/amplify-js/blob/bc5235ac0d15242f7a13457f40999b5331823395/packages/auth/src/Auth.ts#L1215) with the route they were on. Then, on the [post auth lambda trigger](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-post-authentication.html), redirect the user to the right route based on their user attribute.

**Comment by cwomack** [comment]
Hey @jgf5013, I wanted to get a little more context on this issue.  Are you asking for the recording of user information to happen AFTER calling the `Auth.signOut`?  Or trying to implement logic to store customer state/info BEFORE it's called and be able to utilize said state/info when the user returns?

**Comment by cwomack** [comment]
Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested so we can re-open the issue and assist you further.

Thank you!

**Comment by Nick-Zag** [comment]
Hi! Any updates on this? 
I have almost the same issue: 
my react amplify config looks like : 
```
const amplifyConfig = {
  Auth: {
    identityPoolId: process.env.REACT_APP_IDENTITY_POOL_ID,
    region: process.env.REACT_APP_AWS_REGION,
    userPoolId: process.env.REACT_APP_USER_POOL_ID,
    userPoolWebClientId: process.env.REACT_APP_USER_POOL_WEB_CLIENT_ID,
    oauth: {
      domain: process.env.REACT_APP_COGNITO_DOMAIN,
      scope: ['email', 'profile', 'openid'],
      redirectSignIn: `${process.env.REACT_APP_BASE_URL}/login`,
      redirectSignOut: `${process.env.REACT_APP_BASE_URL}/login`,
      responseType: 'code'
    }
  }
};
```
Our users can signIn with different providers, and after logout we need to redirect them on different urls depends on which one they used to login. So it should be `redirectSignOut: `${process.env.REACT_APP_BASE_URL}/login/{provider-id}`` 
How can I catch {provider-id} when oauth config has been applied on application initialization stage and we don't know where user come from?

**Comment by cwomack** [comment]
@Nick-Zag, would you be looking for a solution similar to the issue/feature request #10472?
