### ISSUE TITLE
$[_version] for amplify graphql v2 error

### ISSUE THREAD

**Issue by 24jr** [aws-amplify/amplify-js#9323]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

GraphQL API

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 12.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 35.43 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.4.2 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/node_modules/.bin/npm
    Watchman: 2021.08.30.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 95.1.31.88
    Chrome: 92.0.4515.107
    Safari: 15.1
  npmGlobalPackages:
    @aws-amplify/cli: 7.6.2
    @vue/cli: 4.5.15
    n: 8.0.1
    npm: 8.2.0


```

</details>

### Describe the bug

when updating or deleting an item I get error `message: "Value for field '$[_version]' must be a number."`

my schema is 
```
type BodyArea
  @model
  @auth(
    rules: [
      { allow: public, operations: [read] }
      { allow: groups, groups: ["admin"], operations: [read] }
      { allow: private }
    ]
  ) {
  id: ID!
  key: String!
  name: String!
  symptoms_common: [Symptom] @manyToMany(relationName: "BodyAreaSymptomCommon")
  symptoms_all: [Symptom] @manyToMany(relationName: "BodyAreaSymptomAll")
  body_parts: [BodyPart] @hasMany(indexName: "byBodyArea", fields: ["id"])
}

type BodyPart
  @model
  @auth(
    rules: [
      { allow: public, operations: [read] }
      { allow: groups, groups: ["admin"], operations: [read] }
      { allow: private }
    ]
  ) {
  id: ID!
  key: String!
  name: String!
  symptoms_common: [Symptom] @manyToMany(relationName: "BodyPartSymptomCommon")
  symptoms_all: [Symptom] @manyToMany(relationName: "BodyPartSymptomAll")
  body_area_id: ID! @index(name: "byBodyArea", sortKeyFields: ["key"])
  body_area: BodyArea @belongsTo(fields: ["body_area_id"])
}

type Symptom
  @model
  @auth(
    rules: [
      { allow: public, operations: [read] }
      { allow: groups, groups: ["admin"], operations: [read] }
      { allow: private }
    ]
  ) {
  id: ID!
  key: String!
  name: String!
  body_area_common: [BodyArea] @manyToMany(relationName: "BodyAreaSymptomCommon")
  body_area_all: [BodyArea] @manyToMany(relationName: "BodyAreaSymptomAll")
  body_part_common: [BodyPart] @manyToMany(relationName: "BodyPartSymptomCommon")
  body_part_all: [BodyPart] @manyToMany(relationName: "BodyPartSymptomAll")
}
```

### Expected behavior

deletes/updates as expected

### Reproduction steps

I made initial backend in admin-ui with auth and made schema with cli. I'm using sveltekit but don't think thats relevant

create. item
```
mutation CreateBodyPart($key: String!, $name: String!, $body_area_id: ID!) {
    createBodyPart(input: {
      key: $key,
      name: $name,
      body_area_id: $body_area_id
    }) {
      id
      key
      name
      body_area_id
    }
  }
```
delete item 
```
mutation DeleteBodyPart($id: ID!) {
  deleteBodyPart(input: {id: $id }){
    id
  }
}
```

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @24jr 👋 thanks for raising this issue. Do you have DataStore enabled for your amplify project?

**Comment by 24jr** [comment]
@chrisbonifacio I am not using it and don't believe I remember hitting enable although I am using the admin ui which I believe may require it to be enabled especially for content page (which isn't even working right now) https://github.com/aws-amplify/amplify-adminui/issues/375 But when calling from aws appsync or a direct graphQl call from front end I am not using satastore for those calls when getting error but it may have been enabled through admin ui for the project

**Comment by chrisbonifacio** [comment]
if you created the data model in Amplify Studio first, it seems that may be the case. It assumes you want to use DataStore:

<img width="484" alt="Screen Shot 2021-12-08 at 11 36 29 AM" src="https://user-images.githubusercontent.com/16952986/145246984-65ef20db-9f01-4afd-b94a-2cb30c2217e2.png">

I think you may have to disable it through the CLI by running `amplify update api` and then `amplify push` once disabled

**Comment by 24jr** [comment]
@chrisbonifacio when i disabled conflict detection locally and pushed I was able to update and delete items. Then back in ampllify studio it said enable datastore to use content section so i enabled datastore and went right back to
<img width="761" alt="Screen Shot 2021-12-08 at 3 14 32 PM" src="https://user-images.githubusercontent.com/34662182/145277792-02872b3c-a72f-4d03-8d98-001eb2e71bda.png"> https://github.com/aws-amplify/amplify-adminui/issues/375

**Comment by chrisbonifacio** [comment]
Yeah, Admin UI was renamed to Amplify Studio as it encompasses all the GUIs for managing an Amplify project, including a new front end UI builder feature. I didn't realize there were issues with Studio if datastore was disabled. Until these issues get resolved, I would probably stick to either exclusively using Studio or the CLI, but not both.

For example: if you make changes in Studio, you'll have to remember to pull them down first in your local amplify project before pushing up changes you might've made locally because `amplify push` from the CLI will overwrite what you might've done in Studio.

So, it's a matter of which interface you prefer using to manage your Amplify project.

**Comment by chrisbonifacio** [comment]
I'll close this issue here since there's already an issue in the admin ui where this is more relevant as opposed to the JS libraries.

**Comment by 24jr** [comment]
@chrisbonifacio I don't like the autogenerated names for the id fields for the hasMany and what not in amplify studio so i made my own schema in cli but my coworkers whom are not as technically savvy need to use the content page to add content so datastore needs enabled and the app im not using data store so odd to be getting datastore errors. Not sure where the issues mentioned above are already in an issue so please send me the link to it and at least i hope that issue at least can read my experience with this. I just want to make sure this problem gets solved not brushed under the rug

**Comment by chrisbonifacio** [comment]
Hey @24jr the original issue mentioned where AppSync returns a version error is because some records were created without DataStore enabled. Then, when it was enabled, the mapping templates were changed to expect a version field.

So, you may have to clear the database of all records that don't have a `version` field set, I just ended up clearing my database altogether because I didn't have many records and that fixed the issue for me.

You can leave DataStore enabled for your coworkers to make changes in Studio, but if you want to use GraphQL on the front end, you'll need to include a `version` argument in the mutations with the current version number of the record so AppSync knows how to merge changes.

you'll see the _version field in your input types in the schema like so:

```graphql
input CreateBodyPartInput {
	id: ID
	key: String!
	name: String!
	body_area_id: ID!
	_version: Int
}

input DeleteBodyPartInput {
	id: ID!
	_version: Int
}
```

**Comment by 24jr** [comment]
@chrisbonifacio I appreciate you helping me! Ok I did already add maybe 100 parts but not the end of the world if have to re add those. Ok I will make a new one and start with datastore enabled from the get-go to avoid this and do that maybe tomorrow and see if that works. Thanks again!

**Comment by 24jr** [comment]
@chrisbonifacio I started a new graphQL api from scratch with 
```
type BodyArea
  @model
  @auth(
    rules: [
      { allow: public, operations: [read] }
      { allow: groups, groups: ["admin"], operations: [read] }
      { allow: private }
    ]
  ) {
  id: ID!
  key: String!
  name: String!
  symptoms_common: [Symptom] @manyToMany(relationName: "BodyAreaSymptomCommon")
  symptoms_all: [Symptom] @manyToMany(relationName: "BodyAreaSymptomAll")
  body_parts: [BodyPart] @hasMany(indexName: "byBodyArea", fields: ["id"])
}

type BodyPart
  @model
  @auth(
    rules: [
      { allow: public, operations: [read] }
      { allow: groups, groups: ["admin"], operations: [read] }
      { allow: private }
    ]
  ) {
  id: ID!
  key: String!
  name: String!
  symptoms_common: [Symptom] @manyToMany(relationName: "BodyPartSymptomCommon")
  symptoms_all: [Symptom] @manyToMany(relationName: "BodyPartSymptomAll")
  body_area_id: ID! @index(name: "byBodyArea", sortKeyFields: ["key"])
  body_area: BodyArea @belongsTo(fields: ["body_area_id"])
}

type Symptom
  @model
  @auth(
    rules: [
      { allow: public, operations: [read] }
      { allow: groups, groups: ["admin"], operations: [read] }
      { allow: private }
    ]
  ) {
  id: ID!
  key: String!
  name: String!
  body_area_common: [BodyArea] @manyToMany(relationName: "BodyAreaSymptomCommon")
  body_area_all: [BodyArea] @manyToMany(relationName: "BodyAreaSymptomAll")
  body_part_common: [BodyPart] @manyToMany(relationName: "BodyPartSymptomCommon")
  body_part_all: [BodyPart] @manyToMany(relationName: "BodyPartSymptomAll")
}
```
add api as auth 365 days
add cognito and IAM 
allow conflict resolution
auto merge

amplify push 

then in amplify studio I get same content error and if I put my computer to sleep and awake again the error is gone and it shows the tables. If I add an item it doesnt work and just shows a red X
<img width="1271" alt="Screen Shot 2021-12-10 at 12 54 30 AM" src="https://user-images.githubusercontent.com/34662182/145524452-e5c6a8df-7d92-4bac-aa52-181d20b8b326.png">

That should work so must be some issue that needs fixed
