### ISSUE TITLE
Input fields for required attributes configured via CognitoUserPool are missing.

### ISSUE THREAD

**Issue by elmoGrummelig** [aws-amplify/amplify-js#935]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
The CognitoUserPool is configured with a required attribute like given_name,family_name or website. The AuthenticatorComponent does not provide input fields for these values in signup.

**What is the expected behavior?**
Either the fields for the required entries are displayed automatically or this can be configured

**Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?**
angular: 6.0.3
aws-amplify: 0.4.1
aws-amplify-angular: 0.1.1

I changed the file "node_modules/aws-amplify-angular/lib/providers/amplify.service.ts". I changed the the line from `import { Subject } from 'rxjs/Subject';` to `import { Subject } from 'rxjs';` and i included the following in the index.html file of my angular project 
`<script>
    if (global === undefined) {
      var global = window;
    }
  </script>`

**You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.**

`{
  "[DEBUG] 26:11.34 AuthDecorator - signUp error": {
    "code": "InvalidParameterException",
    "name": "InvalidParameterException",
    "message": "Attributes did not conform to the schema: given_name: The attribute is required\nfamily_name: The attribute is required\nwebsite: The attribute is required\n"
  }
}`

**Comment by mlabieniec** [comment]
@elmoGrummelig the error your seeing is coming from Cognito, your user pool is requiring the attributes given_name, family_name, and website. You can configure it the cognito console what is required if you don't want them to be required, or send them up with your signUp request in the attributes param: https://aws.github.io/aws-amplify/media/authentication_guide#sign-up

**Comment by elmoGrummelig** [comment]
@mlabieniec i know. i configured cognito to require the fields given_name, family_name, and website. I expect aws-amplify-angular AuthenticatorComponent to automatically adapt. AuthenticatorComponent should display input fields so the user is able to enter the required attributes. 
The Auth SignUp method is not a solution, because aws-amplify-angular AuthenticatorComponent hides this from me.

**Comment by DrFriendless** [comment]
I had this problem too. The required attributes are impossible to use with amplify-authenticator if there's no way to fill them in.

**Comment by mlabieniec** [comment]
Thanks for the clarification and feedback, we'll look into getting this added to the HOC. Feel free to propose a PR if you have any thoughts around the implementation.

**Comment by christo1745** [comment]
This is how I solved this. It still needs some work to determine which input fields to require.  In a nutshell I'm just displaying the required attributes as inputs, then posting those back to cognito.

class App extends Component {

    render() {
        return (
            <Wrapper>
                <Authenticator theme={CustomAmplifyTheme} hide={[Greetings, RequireNewPassword]}>
                    <CustomRequireNewPassword/>
                    <Header/>
                    <Body/>
                </Authenticator>
            </Wrapper>
        );
    }
}

export default App;



import React from 'react';
import {RequireNewPassword, FormSection, SectionHeader, SectionBody, InputRow, ButtonRow, SectionFooter, Link} from 'aws-amplify-react';
import {I18n, Auth} from 'aws-amplify';

class CustomRequireNewPassword extends RequireNewPassword {

    change() {
        const user = this.props.authData;
        const { password } = this.inputs;
        const { name } = this.inputs;

        let finalRequiredAttributes = {
            name : name
        }
        if (!Auth || typeof Auth.completeNewPassword !== 'function') {
            throw new Error('No Auth module found, please ensure @aws-amplify/auth is imported');
        }
        Auth.completeNewPassword(user, password, finalRequiredAttributes)
            .then(user => {
                //logger.debug('complete new password', user);
                if (user.challengeName === 'SMS_MFA') {
                    this.changeState('confirmSignIn', user);
                } else if (user.challengeName === 'MFA_SETUP') {
                    //logger.debug('TOTP setup', user.challengeParam);
                    this.changeState('TOTPSetup', user);
                } else {
                    this.checkContact(user);
                }

            })
            .catch(err => this.error(err));
    }

    render() {
        if (this.props.authState !== 'requireNewPassword') {
            return null;
        }
        const theme = this.props.theme;

        return (
            <FormSection theme={theme}>
                <SectionHeader theme={theme}>{I18n.get('Change Password')}</SectionHeader>
                <SectionBody>
                    <InputRow
                        autoFocus
                        placeholder={I18n.get('New Password')}
                        theme={theme}
                        key="password"
                        name="password"
                        type="password"
                        onChange={this.handleInputChange}
                    />
                    <InputRow
                        autoFocus
                        placeholder={I18n.get('Name')}
                        theme={theme}
                        key="name"
                        name="name"
                        type="text"
                        onChange={this.handleInputChange}
                    />
                    <ButtonRow theme={theme} onClick={this.change}>
                        {I18n.get('Change')}
                    </ButtonRow>
                </SectionBody>
                <SectionFooter theme={theme}>
                    <Link theme={theme} onClick={() => this.changeState('signIn')}>
                        {I18n.get('Back to Sign In')}
                    </Link>
                </SectionFooter>
            </FormSection>
        );
    }
}

export default CustomRequireNewPassword;

**Comment by haverchuck** [comment]
@elmoGrummelig  @DrFriendless @christo1745  - We have implemented configurable signup fields and they are currently avaible on our Beta branch, which can be accessed via 'npm install aws-amplify-[react || react-native || angular]@beta. The functionality allows users to pass in a signUpConfig object, which not only can contain a signUpField array that describes a given field, but also allows developers to hide default fields or set the default country code dropdown (the latter in Angular, React and Vue only).

Draft documentation is available for Angular, for React/React Native.

The functionality is already available in Vue package.

We would love to hear any feedback you might have!

**Comment by askpatrickw** [comment]
@haverchuck  I installed aws-amplify@beta & aws-amplify-react@beta. I added auth (with required fields) and hosting to a new react app. The 'hello-world' create-react-app is wrapped `export default withAuthenticator(App, true);`. But, when I get to the create account page, I don't see the required fields. 

Are there more steps documented someplace? I don't see the beta version of the docs online.

Thank you, looking forward to the new functionality.

**Comment by askpatrickw** [comment]
> @haverchuck I installed aws-amplify@beta & aws-amplify-react@beta. I added auth (with required fields) and hosting to a new react app. The 'hello-world' create-react-app is wrapped `export default withAuthenticator(App, true);`. But, when I get to the create account page, I don't see the required fields.
> 
> Are there more steps documented someplace? I don't see the beta version of the docs online.
> 
> Thank you, looking forward to the new functionality.


I see  now you have to pass in a signUpConfig object. Nevermind. thank you !
