### ISSUE TITLE
Remove node build-ins.

### ISSUE THREAD

**Issue by ivands** [aws-amplify/amplify-js#9350]
### Is this related to a new or existing framework?

New framework

### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

Trying to use amplify is a pain right now because for some reason it uses node build-in libraries while it is supposed to work in the browser.
The next generation of build tools (like vite) don't include node's build-in libraries anymore.
Amplify should stop using them and migrate.

### Describe the solution you'd like

Stop using node build-in libraries

**Comment by jiahao-c** [comment]
As discussed in https://github.com/aws-amplify/amplify-ui/issues/268#issuecomment-804386820  
Seems like this problem can only be fixed by [aws-sdk](https://github.com/aws/aws-sdk-js)

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6) and in the latest version of v5 (v5.3.18+), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information on the v6 release.

Feel free to reply back if this isn't the case or we missed something!
