### ISSUE TITLE
observeQuery does not return an updated items array when a model has been mutated

### ISSUE THREAD

**Issue by wcole1-godaddy** [aws-amplify/amplify-js#9352]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

DataStore

### Amplify Categories

Not applicable

### Environment information

<details>

```
  System:
    OS: macOS 12.0.1
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Memory: 15.88 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.1 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 96.0.4664.93
    Firefox: 94.0.2
    Safari: 15.1
  npmPackages:
    @sermonary/components: ^0.3.29 => 0.3.29
    @sermonary/theme: ^0.3.29 => 0.3.29
    @types/node: ^12.0.0 => 12.20.15
  npmGlobalPackages:
    corepack: 0.10.0
    npm: 8.1.2

```

</details>

### Describe the bug

The `ObserveQuery` API is not returning the updated items when a single model has been mutated. For example, if I am querying and subscribing to model updates like `DataStore.observeQuery(Sermon)`, new items are only emitted for CREATE and DELETE. Updated items are not being emitted when updating a single model in the list, and thus causes my query to be stale and does not reflect what is actually in the DataStore or in the DB. 

### Expected behavior

I would expect any change to a model to emit a message and cause `observeQuery` to return a new array of items with the updated model in the response. 

### Reproduction steps

1. Observe a model query with `DataStore.observeQuery()`
2. Perform a mutation with `DataStore.save()` on a model that currently exists and was returned by the `observeQuery` method. 
3. Note that the items are not updated from `DataStore.observeQuery()`

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hey @wcole1-godaddy thanks for raising this issue. Can you share the code where you're updating a record?

**Comment by wcole1-godaddy** [comment]
```
await DataStore.save(
            Sermon.copyOf(sermon, (updated) => {
              updated.title = newSermon?.title;
              updated.bigIdea = newSermon?.bigIdea;
              updated.referenceVerses = newSermon?.referenceVerses;
              updated.seriesId = seriesId;
              updated.blocks = newSermon?.blocks;
            }),
          );
```

```
DataStore.observeQuery(Sermon)
```

It's a pretty simple handler to update a Sermon model on a single sermon view page and then going back to the sermon list screen, the list hasn't updated because the Update snapshot hasn't been sent to observeQuery.

**Comment by chrisbonifacio** [comment]
I don't think that you're using observeQuery as intended. Here's how I'm using it

```js
useEffect(() => {
  const subTodos = DataStore.observeQuery(Todo).subscribe({
    next: ({ items, isSynced }) => {
      isSynced && setTodos(items);
    },
  });

  return () => subTodos.unsubscribe();
}, []);
```

hosted example: https://dev.d1k4mg9xib2kkx.amplifyapp.com/

**Comment by nubpro** [comment]
> I don't think that you're using observeQuery as intended. You can chain`.subscribe` and use the `items` and `isSynced` properties that are exposed by the `next` callback to update your state.
> 
> ```js
> useEffect(() => {
>   const subTodos = DataStore.observeQuery(Todo).subscribe({
>     next: ({ items, isSynced }) => {
>       isSynced && setTodos(items);
>     },
>   });
> 
>   return () => subTodos.unsubscribe();
> }, []);
> ```
> 
> hosted example: https://dev.d1k4mg9xib2kkx.amplifyapp.com/

Sorry to chip this in out of nowhere, I've observed an odd behaviour when I tap on the "Toggle Complete" button. Why is it that the `Title` becomes empty and reappear a second later?

**Comment by chrisbonifacio** [comment]
@nubpro I'm not sure why that happens. I think it might be the way updates to records are merged by observeQuery, where the change I made locally stay and the other fields are being "resynced". I adjusted it so that it shows the ID of the records and also edits the title when toggling `Completed`. You'll see that the ID and title don't flash anymore but createdAt and updatedAt do.

**Comment by nubpro** [comment]
> @nubpro I'm not totally sure why that happens. I think it might be the way updates to records are merged by observeQuery, where the changes I made locally stay and the other fields are being "resynced". I adjusted it so that it shows the ID of the records and also edits the title when toggling `Completed`. You'll see that the ID and title don't flash anymore but createdAt and updatedAt do.

That doesnt seems right does it?
Could you also link your demo to the repo you're using, I'd love to take a look at it
