### ISSUE TITLE
Graphql create API not working for FB login users

### ISSUE THREAD

**Issue by kgoyal98** [aws-amplify/amplify-js#9353]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication, GraphQL API

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I created an amplify application with email signup which is working perfectly. Recently, I added FB signin option in the application. The FB signin is successful. The get user API is also working. However, the create graphql APIs are not working with the error: **Not Authorized to access createUser on type User** 

User graphql definition:
```
type User @model
  @auth(rules: [
      {allow: groups, groups: ["admin"]},
      {allow: owner, ownerField: "id", operations: [create, update, delete]},
      {allow: private, operations: [read]}
    ])
    @key(fields: ["id"])
    @key(name: "byUsername", fields: ["username"], queryField: "usersByUsername") {
  id: ID!
  username: String!
  name: String!
}
```

### Expected behavior

The create user graphql API should work for FB authenticated users as well.

### Reproduction steps

N/A

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

```
const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://u4xvhzzdanctxp5htlchyaalf4.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "ap-south-1:abd9c47c-e74c-4999-b1f5-d843b21fce3e",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_pHVdDxjiO",
    "aws_user_pools_web_client_id": "2n7p0s03ob0tppfl2ro83l67lr",
    "oauth": {
        "domain": "24ehrd4ndpbr-staging.auth.ap-south-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://<domain>.in,http://localhost:3000",
        "redirectSignOut": "https://<domain>.in,http://localhost:3000",
        "responseType": "token"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_user_files_s3_bucket": "telebuffimages105947-staging",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
```

### Manual configuration

_amplify/backend/backend-config.json_

```
{
  "api": {
    "telebuff": {
      "service": "AppSync",
      "providerPlugin": "awscloudformation",
      "output": {
        "authConfig": {
          "defaultAuthentication": {
            "authenticationType": "AMAZON_COGNITO_USER_POOLS",
            "userPoolConfig": {
              "userPoolId": "authtelebuff"
            }
          },
          "additionalAuthenticationProviders": [
            {
              "authenticationType": "AWS_IAM"
            }
          ]
        }
      }
    }
  },
  "auth": {
    "telebuff": {
      "service": "Cognito",
      "providerPlugin": "awscloudformation",
      "dependsOn": [],
      "customAuth": false
    }
  },
  "storage": {
    "images": {
      "service": "S3",
      "providerPlugin": "awscloudformation"
    }
  }
}
```

**Comment by chrisbonifacio** [comment]
Hi @kgoyal98 thanks for raising this issue. I was not able to reproduce the issue, I was able to create a user record while logged in as a facebook user in my app. If you try creating a user with a normal username/email and password login, do you experience the same behavior?

**Comment by chrisbonifacio** [comment]
for reference:
https://staging.d13c7lh58sja73.amplifyapp.com/

aws-exports.js

```js
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0842f275-a91d-41bc-988e-4f26de400f07",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_B5dxgXBp1",
    "aws_user_pools_web_client_id": "6smtsec602ivrka2fhlc2cmtch",
    "oauth": {
        "domain": "tibxlj6drokt-staging.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000,https://staging.d13c7lh58sja73.amplifyapp.com/",
        "redirectSignOut": "http://localhost:3000,https://staging.d13c7lh58sja73.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "FACEBOOK"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://dolgi5qhhvcm3e5d4lygyglgyq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-agesyzefiva45mndtrfvkd3qei"
};


export default awsmobile;

```

**Comment by kgoyal98** [comment]
@chrisbonifacio If I create a user with a normal email and password login, it is working fine.
I think there is some configuration issue in my Amplify app. I can see some keys in your aws-exports.js which are not present in mine. How did you configure your amplify app?

**Comment by chrisbonifacio** [comment]
Here's the codebase for the project I used to reproduce: https://github.com/chrisbonifacio/amplify-dse-repros/tree/main/studio/starter

Might be worth comparing how we are both signing into Facebook. Are you authenticating against the User Pool or Identity Pool? For example, when you signup/signin as a FB user, do your users appear in the Cognito console under User Pool?

**Comment by kgoyal98** [comment]
@chrisbonifacio The FB user is coming in user pool. I do not understand user identity page since I never used it as amplify handled everything internally. Here is the dashboard snapshot:
![image](https://user-images.githubusercontent.com/32641543/146049014-5651731b-80bd-4fba-adca-e30f244ae33c.png)


I am using this code (in nodejs) to do FB signin: `await Auth.federatedSignIn({ provider: CognitoHostedUIIdentityProvider.Facebook });`

Here is the walkthrough of amplify authentication.
```
$ amplify auth update
Please note that certain attributes may not be overwritten if you choose to use defaults settings.

You have configured resources that might depend on this Cognito resource.  Updating this Cognito resource could have unintended side effects.

Using service: Cognito, provided by: awscloudformation
 What do you want to do? Walkthrough all the auth configurations
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage features for images or o
ther content, Analytics, and more)
 Allow unauthenticated logins? (Provides scoped down permissions that you can control via AWS IAM) No
 Do you want to enable 3rd party authentication providers in your identity pool? Yes
 Select the third party identity providers you want to configure for your identity pool: Facebook
  
 You've opted to allow users to authenticate via Facebook.  If you haven't already, you'll need to go to https://developers.facebook.com and create an App ID. 
 
 Enter your Facebook App ID for your identity pool:  371436797834763
 Do you want to add User Pool Groups? No
 Do you want to add an admin queries API? No
 Multifactor authentication (MFA) user login options: OFF
 Email based user registration/forgot password: Enabled (Requires per-user email entry at registration)
 Please specify an email verification subject: Your verification code
 Please specify an email verification message: Your verification code is {####}
 Do you want to override the default password policy for this User Pool? No
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? No
 Do you want to enable any of the following capabilities? 
 Do you want to use an OAuth flow? Yes
 What domain name prefix do you want to use? 24ehrd4ndpbr
 Which redirect signin URIs do you want to edit? 
 Do you want to add redirect signin URIs? Yes
```

**Comment by chrisbonifacio** [comment]
Well, it turns out the issue might actually be just that you're including the `id` in the `createUser` inputs. Try leaving that out, it should still be set to the user's sub automatically.

**Comment by kgoyal98** [comment]
@chrisbonifacio I am still getting the same error.
In your case, it happened because the sub of your user is not what you supplied but facebook_... If you supply the correct sub, you won't get any error.

**Comment by chrisbonifacio** [comment]
In the screenshots I shared, trying to use a FB user's Cognito sub failed. By leaving out the `id` in the input, the username was used automatically instead and that worked.

this doesn't work for you?

```js
const res = await API.graphql({
  query: createUser,
  variables: {
    input: {
      username,
      name,
    },
  },
});
```

**Comment by kgoyal98** [comment]
No, it didn't work.

**Comment by chrisbonifacio** [comment]
Can you share the code where you're importing and configuring Amplify?

**Comment by kgoyal98** [comment]
`
import Amplify from 'aws-amplify';
import awsconfig from './aws-exports';

const isLocalhost = Boolean(
  window.location.hostname === "localhost" ||
  // [::1] is the IPv6 localhost address.
  window.location.hostname === "[::1]" ||
  // 127.0.0.1/8 is considered localhost for IPv4.
  window.location.hostname.match(
    /^127(?:\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}$/
  )
);

// Assuming you have two redirect URIs, and the first is for localhost and second is for production
const [
  localRedirectSignIn,
  productionRedirectSignIn,
] = awsconfig.oauth.redirectSignIn.split(",");

const [
  localRedirectSignOut,
  productionRedirectSignOut,
] = awsconfig.oauth.redirectSignOut.split(",");

const updatedAwsConfig = {
  ...awsconfig,
  oauth: {
    ...awsconfig.oauth,
    redirectSignIn: isLocalhost ? productionRedirectSignIn : localRedirectSignIn,
    redirectSignOut: isLocalhost ? productionRedirectSignOut : localRedirectSignOut,
  }
}

Amplify.configure(updatedAwsConfig);

`

**Comment by chrisbonifacio** [comment]
Interestingly, using the Cognito user's username (which happens to be the sub if you're using email login mechanism) might be the best way to approach this with your schema. Making the call like this worked for me for multiple social providers (amazon, fb, google) as well as a cognito user.

```
// mutation
const res = await API.graphql(
  graphqlOperation(createUser, {
    input: {
      id: (await Auth.currentAuthenticatedUser()).username,
      username,
      name,
    },
  })
);
```

**Comment by kgoyal98** [comment]
@chrisbonifacio 
With the above code, I am getting ConditionalCheckFailedException "The conditional request failed (Service: DynamoDb, Status Code: 400, Request ID: 9RES2F6P0CRL50QOARQ82DCVMJVV4KQNSO5AEMVJF66Q9ASUAAJG, Extended Request ID: null)"

**Comment by chrisbonifacio** [comment]
what kind of user is trying to make that request?

**Comment by kgoyal98** [comment]
Facebook logged in user is making that request

I am using email login mechanism.

**Comment by kgoyal98** [comment]
You are right. There was a user record with the same ID. I am able to create the user with username instead of sub.
