### ISSUE TITLE
GraphQl query filter behave differently

### ISSUE THREAD

**Issue by goodryanboy** [aws-amplify/amplify-js#9356]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

GraphQL API

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line

No details
```

</details>

### Describe the bug

I have table Users then it has a field called searchFields this search fields contains first name and last name of the user in lower case. This table has 24 rows then the one I want to search is on the row 24. Now I used a filter in the graphql query but I got unexpected results. If I set the limit to 10 I got 0 results but if I set the limit to 50 I got 1 result.

### Expected behavior

I should get the results if the limit is 10

### Reproduction steps

NO info

### Code Snippet

```javascript
// Put your code below this line.
query MyQuery {
      userLeadByCreatedAt(userId: "414d8e4c-287c-4418-a132-bc1cc997a309", filter: {searchField: {contains: "zach"}}, limit: 10) {
          nextToken
          items {
              firstName
              lastName
              searchField
          }
      }
}
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @goodryanboy 👋 thank you for raising this issue. Can you share your schema?

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!
