### ISSUE TITLE
Cognito: Add email verification code to subject of email

### ISSUE THREAD

**Issue by Targettrade** [aws-amplify/amplify-js#936]
How is it possible to add the email verification code sent by AWS Cognito to the subject of an email?

**Comment by Jasminou** [comment]
@Targettrade I don't think it's possible, I already tried to add  {####} in the subject email from the web console cognito under message cutomization tab, but it didn't work. Also I tried with a custom message for the forget password verification using triggers, It's not replacing the code verification place holder by the real code parameter in subject as it's done for the email body.

**Comment by mlabieniec** [comment]
It is a security risk to add the code to the subject since it would be visible in the listing.
