### ISSUE TITLE
On local dev : Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by julienlaurent-migso** [aws-amplify/amplify-js#9367]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

with npm

### If applicable, what version of Node.js are you using?

v16.13.1

### Amplify CLI Version

7.6.3

### What operating system are you using?

windows

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

- On my local environment, 
- I launch "npm start" to launch the developpement server
- Everything works well
- but when i refresh my code, my front freeze and i have this issue :

`Uncaught ReferenceError: process is not defined`

![Captur1e](https://user-images.githubusercontent.com/79509459/146347297-e4b85046-fd4f-4ca7-8f4f-85712a437017.PNG)

![Capture](https://user-images.githubusercontent.com/79509459/146346512-ff9d0e1e-2279-4c30-a1e7-06b3e81a9128.PNG)

My package.json :
```
"@aws-amplify/analytics": "^3.3.11",
    "@aws-amplify/api": "^3.3.3",
    "@aws-amplify/api-graphql": "^2.2.15",
    "@aws-amplify/api-rest": "^2.0.26",
    "@aws-amplify/auth": "^3.4.34",
    "@aws-amplify/cache": "^4.0.28",
    "@aws-amplify/core": "^3.8.24",
    "@aws-amplify/datastore": "^3.7.0",
    "@aws-amplify/geo": "^1.1.8",
    "@aws-amplify/interactions": "^3.3.34",
    "@aws-amplify/predictions": "^4.0.26",
    "@aws-amplify/pubsub": "^4.2.2",
    "@aws-amplify/storage": "^3.4.4",
    "@aws-amplify/ui": "^2.0.3",
    "@aws-amplify/xr": "^2.2.34",
    "@testing-library/jest-dom": "^5.11.10",
    "@testing-library/react": "^11.2.6",
    "@testing-library/user-event": "^12.8.3",
    "aws-amplify": "^4.3.8",
    "aws-amplify-react": "^5.1.9",
    "lodash": "^4.17.21",
    "npm": "^7.24.2",
    "performant-array-to-tree": "^1.9.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^4.0.3",
    "react-select": "^5.2.1",
    "react-tooltip": "^4.2.21",
    "uuid": "^8.3.2",
    "web-vitals": "^1.1.1"
```

### Expected behavior

I need my frontend refresed when i save my code

### Reproduction steps

1) create react app
2) add my package
3) add my front
4) amplify pull my backend

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @julienlaurent-migso 👋 thank you for raising this issue. I haven't run into this error yet by just installing the packages and running the dev server, refreshing, etc.

Can you share the code for rendering that page specifically to see which packages, functions, etc are being used when the error occurs? The stack trace seems really obscure from the screenshot.

**Comment by julienlaurent-migso** [comment]
Hi @chrisbonifacio, thank you for your answer. I got the package-losk.json of an other amplify working app, and the issue has been fixed. Something happened between packages version but impossible to identify ... 
Thank you very much and sorry for your time consuming.
