### ISSUE TITLE
amazon-cognito-identity-js - Changing email leads to successful login for non-verified email

### ISSUE THREAD

**Issue by jashsayani** [aws-amplify/amplify-js#9381]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Environment information

<details>

```
  System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 7.37 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    npm: 8.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Safari: 15.2
  npmGlobalPackages:
    corepack: 0.10.0
    npm: 8.1.0
```
</details>

### Describe the bug

AWS Cognito dashboard shows `Email verified: false` for a user but auth is successful (no error about unverified email).

### Expected behavior

Should error with `UserNotConfirmedException`

### Reproduction steps

1. Create user
2. Verify email
3. Update user (email change)
4. Login with new email (login successful even if email is unconfirmed)

**Comment by wduminy** [comment]
From the [docs](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-email-phone-verification.html) there is a setting called `Keep original attribute value active when an update is pending.`
I think the problem could be solved by switching that `on` for email.

**Comment by nadetastic** [comment]
Hi @jashsayani I'm following up with you on this.

Are you still facing this issue while using `amazon-cognito-identity-js`? And if so, is there a requirement/reason to use
 `amazon-cognito-identity-js` and not Amplify Auth?
 
 We have created a streamlined experience for our developers needing to use Authentication with Cognito using the Authentication library from Amplify. You can opt in to use just the [JS library without the Amplify CLI](https://docs.amplify.aws/lib/auth/start/q/platform/js/#re-use-existing-authentication-resource) if you feel like 
that would be better for your use case.

While we do provide some occasional fixes/upgrades to the cognito-identity-js library, we are planning on deprecating that package in the near future.

**Comment by nadetastic** [comment]
Hi @jashsayani 

Following up on this, let me know if you still need assistance on this.
