### ISSUE TITLE
amazon-cognito-identity-js - Allow signUp to accept Group that user should be added to upon user creation

### ISSUE THREAD

**Issue by jashsayani** [aws-amplify/amplify-js#9383]
### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

Users must be added to groups for access to AWS resources like DynamoDB. The current practice is to have a post-creation event fire a Lambda that calls `adminAddUserToGroup`. This adds a lot of overhead to common boilerplate task. Would be nice to have `signUp` take in Group info that user should be added to upon creation.

### Describe the solution you'd like

Something like:
```
signUp(username, password, userAttributes, validationData, callback, clientMetadata, groups)
```

**Comment by elorzafe** [comment]
@jashsayani thanks for your request.

I would like to understand more your use case

Why do you need access to DynamoDB from the client? is not a good practice to do that directly from the client is recommended to use something in between like AppSync or API Gateway? Have you tried amplify cli? it can prepare this for you.

Those permissions will be for every user of the App or are you going to restrict those from the client, I am saying this because it seems a bad practice to configure permissions or assign groups from the client. Someone can assign themself to be Admin for example.

**Comment by jashsayani** [comment]
> Why do you need access to DynamoDB from the client?

I would like the user to be able to add / update items in the database.

> is not a good practice to do that directly from the client is recommended to use something in between like AppSync or API Gateway?

Not really if the database can handle ACL directly. If DynamoDB had no ACL support, then yes I would use API Gateway, and send a request to it, then check authentication / validate the user action, and then do a database operation. But DynamoDB supports ACL and Identity Pools are designed specially for this use-case. 

Here is a quick video from Amazon on this topic: https://www.youtube.com/watch?v=uAUYphLWL5w

> Have you tried amplify cli? it can prepare this for you.

From what I have read, it only does this if you go through the GraphQL wrapper. I am not using GraphQL.

> Those permissions will be for every user of the App or are you going to restrict those from the client

Yes, this is intended. My app setup is as follows:

1. User creates account (added to User Pool)
2. My Identity Pool has a group, which I want all users to be added to
3. The group has IAM Policy associated with it, so user can access AWS Services

On app actions:
1. User credentials are refreshed and identityId is fetched
2. Cognito exchanges the identityId for AWS credentials
3. AWS credentials used with services like DynamoDb

This currently works, but I had to add the user to the group from AWS Console, and would like the "signUp" to add new users to the group automatically.

> I am saying this because it seems a bad practice to configure permissions or assign groups from the client.

It again depends on what you are trying to do. Clients cant be trusted, sure. But you can create accounts from the client. So adding to group (a group that every user should belong to) is no different.

> Someone can assign themself to be Admin for example.

This is not possible. There is no such group. Cognito Identity Pool creates 2 groups: CognitoIdentityPoolAuthenticated, and CognitoIdentityPoolUnauthenticated. In my case, I only care about CognitoIdentityPoolAuthenticated. I want users to be part of this so IAM Policy can be applied to the user.

As of database security/integrity, I intend to use: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/specifying-conditions.html

**Comment by chrisbonifacio** [comment]
If you just need to add users to a group I would recommend either using the [Admin Queries API](https://docs.amplify.aws/cli/auth/admin/) or a Cognito Pre-Signup or Post-Confirmation [Lambda Trigger](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-post-confirmation.html).
