### ISSUE TITLE
RFC: react component HOCs allowing for bringing your own component

### ISSUE THREAD

**Issue by cdaringe** [aws-amplify/amplify-js#940]
## Do you want to request a feature or report a bug?

**feature**

## current behavior

The current set of `react` components bring their own, strongly opinionated DOM.

Example:

```jsx
<Authenticator />
```

brings it's own specific versions of `<AmplifyUI.InputRow />` , `<AmplifyUI.FormRow />`, etc, and each of those brings an explicit `<html>` element of its own choosing.

This is problematic because it hinders extension.  For instance, what if you need to use _your own_ component library's visual components, whilst still getting the benefit of the amplify HOC?  Consider if your component library has deep prebaked CSS styles & JS bindings on something as simple as an `<Input />`.  you may care to use said `<Input />`, but instead must use the `<input />` that `<AmplifyUI.InputRow />`owns completely, and style it through the theme interface.  The theme interface is a great start, but adds complication when really all you want out of the library is the logic and perhaps component structure, not the aesthetics or DOM.

## expected behavior

luckily, this is a solved problem in other react spaces.  there are two implementations that i use commonly, and thus cite both for reference

- [react-styleguidist](https://react-styleguidist.js.org/docs/cookbook.html#how-to-change-the-layout-of-a-style-guide)
  - essentially, they let you create a map between their internal HOC's and your own components.  your own components just need to render children and pass thru key top-level props

here's a hypothetical usage:

```jsx
// some amplify aware file
const theme = {
  ...,
  components: {
     FormRow: MyCustomFormRow,
     InputRow: MyCustomInputRow
   }
}

// AmplifyUI.jsx
...
export const FormRow = (props) => {
    const theme = props.theme || AmplifyTheme;
    const style = propStyle(props, theme.formRow);
    const p = JS.objectLessAttributes(props, 'theme');
    const ElementType = getElementType('FormRow', theme) // returns MyCustomFormRow if provided, or, the previous default, `'div'`
    return beforeAfter(
        <ElementType {...p} className={themedClassName("amplify-form-row", theme.formRow)} style={style}>
            {props.children}
        </ElementType>
    )
}
```

- [semantic-ui-react](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/lib/getElementType.js), aka SUIR
  - SUIR lets you use any of their components with an `as` prop.
  - e.g. `<Header as={SomeOtherComponent />`, vs. the default `<h1 />`, etc

The SUIR strategy works best when composing components from the bottom up.  The styleguidist approach works best when users want to use a predefined component structure, but with tweaks to the DOM tree.  Most likely, a styleguidst approach would be the ideal 1st pass, with consideration for using the SUIR approach longer term.

I'd be happy to PR this if accepted.

**Comment by nidsharm** [comment]
Hi @cdaringe,

Thank you for the suggestion. We do accept PRs, and I have added this to our backlog too.

**Comment by phatcatmatt** [comment]
Any progress happening on this?

**Comment by cdaringe** [comment]
i dropping the project that motivated this, so no work from my end

**Comment by jordanranz** [comment]
This is one of the tenants of the UI Component refactor milestones.

**Comment by jordanranz** [comment]
FYI, we have started an RFC discussion for a proposed Amplify UI Component refactor to increase customizability and flexibility for our components. Please feel free to add any additional comments to the following issue:

https://github.com/aws-amplify/amplify-js/issues/3279

**Comment by ericclemmons** [comment]
Closing as `aws-amplify-react` is in maintenance mode and superseded by #3279 (`@aws-amplify/ui-react`).
