### ISSUE TITLE
Bundle-size impact on react-native

### ISSUE THREAD

**Issue by ACHP** [aws-amplify/amplify-js#9406]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Analytics

### Amplify Categories

analytics

### Environment information

<details>

```
  System:
    OS: macOS 11.4
    CPU: (8) arm64 Apple M1
    Memory: 79.50 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.2.0 - ~/.nvm/versions/node/v16.2.0/bin/node
    npm: 7.13.0 - ~/.nvm/versions/node/v16.2.0/bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 95.0.2
    Safari: 14.1.1
  npmPackages:
    @aws-amplify/analytics: ^5.1.9 => 5.1.9
    @aws-amplify/core: ^4.3.11 => 4.3.11
    @babel/core: ^7.12.9 => 7.16.5
    @babel/runtime: ^7.12.5 => 7.16.5
    @callstack/repack: ^2.5.1 => 2.5.1
    @react-native-async-storage/async-storage: ^1.15.14 => 1.15.14
    @react-native-community/eslint-config: ^2.0.0 => 2.0.0
    @react-native-community/netinfo: ^7.1.7 => 7.1.7
    @rnx-kit/cli: ^0.9.58 => 0.9.58
    @rnx-kit/metro-config: ^1.2.26 => 1.2.26
    @rnx-kit/metro-serializer-esbuild: ^0.0.23 => 0.0.23
    HelloWorld:  0.0.1
    babel-jest: ^26.6.3 => 26.6.3
    babel-loader: ^8.2.3 => 8.2.3
    esbuild: ^0.12.29 => 0.12.29 (0.13.15)
    eslint: 7.14.0 => 7.14.0
    hermes-inspector-msggen:  1.0.0
    jest: ^26.6.3 => 26.6.3
    metro-minify-esbuild: ^0.1.0 => 0.1.0
    metro-react-native-babel-preset: ^0.66.2 => 0.66.2
    patch-package: ^6.4.7 => 6.4.7
    react: 17.0.2 => 17.0.2
    react-native: 0.67.0-rc.6 => 0.67.0-rc.6 (0.66.4)
    react-test-renderer: 17.0.2 => 17.0.2
    terser-webpack-plugin: ^5.3.0 => 5.3.0
    webpack: ^5.65.0 => 5.65.0
  npmGlobalPackages:
    @gdc/localiser: 1.5.0
    @swc-node/core: 1.8.2
    @types/node: 16.7.8
    expo-cli: 4.13.0
    gsts: 3.0.6
    npm: 7.13.0
    patch-package: 6.4.7
    pod-install: 0.1.27
    release: 6.3.0
    source-map-explorer: 2.5.2
    ts-node: 10.2.1
    tsm: 2.1.2
    typescript: 4.5.2


```

</details>

### Describe the bug

Hi !

When trying to reduce our ReactNative app size I noticed that *amplify-js* and *aws-sdk-v3* had a HUGE impact on the js bundle size. Even when using modular import.
These libs are 3 times bigger than react native itself ( js code only of course, but still ... )

I know there are some open issue about this, mainly related to nextJS. But I create a new one because ReactNative is very different as it does not use esbuild nor webpack and AFAIK metro bundler does not implement any kind of tree-shaking.

I was wondering if there was any solution to "fix" this ? We use aws-amplify only for the `analytics` part, and include this much code (especially the `Aws_restJson1.js` of 500ko) just to do this is kind of "_annoying_" :/ :) 

I'm not looking for a perfect easy solution here, I don't think there is a simple config line to apply to solve the problem, but more for suggestion. How would you recommand to solve this issue with this lib ?

For now I tried using `repack bundler`  instead of metro but it failed. I also tried `@rnx-kit/cli` with different configuration but it did not improve the output bundle...

### Expected behavior

The library should not be that huge ... :(

### Reproduction steps

I've created a ReactNative project so everyone can inspect the bundle and maybe play with configuration:
https://github.com/ACHP/aws-amplify-bundle-size-demo

```
git clone https://github.com/ACHP/aws-amplify-bundle-size-demo.git
```

inspection is simple:

```
npm ci && npm run inspect
```

### Additional information and screenshots

![image](https://user-images.githubusercontent.com/9294168/147484843-bdcd1a7d-cbe6-4392-885d-80808fd65777.png)

**Comment by elorzafe** [comment]
@ACHP thanks for your concern. We will take a look on this situation. Just curious why is so important for your case that react-native build size? Are you using a particular device that has storage limitations?

**Comment by ACHP** [comment]
### Why
Smaller APK sizes generaly correlate with higher install conversion rates, and smaller js bundle should also increase app startup time. ( As the js bundle to load/parse will be smaller ).

It's not a technical requirement, our app works even when using 1.75Mo of aws-sdk ^^ So, if there is no "real" solution to this, it wouldn't be that big of a deal. But maybe adding a note on this in the documentation would be appropriate.

But if we can avoid shipping unused code to final users (especially when all of this code is imported for analytics purpose).

### Alternative
For now the solution we use is some kind of "pre-bundled" version using esbuild ( which support tree-shaking)
We don't import *aws-amplify* directly in our RN app. Instead, we use an intermediate file ("awsBridge" in the screenshot ) that just import and re-export aws-amplify required function. This file is bundled using *esbuild* and the result is imported in our app.
This *awsBridge.native.js* is a kind of "lighter" version of aws-amplify + aws-sdk-v3 (400Ko)

<img width="1371" alt="Screenshot 2021-12-27 at 23 36 45" src="https://user-images.githubusercontent.com/9294168/147512179-1d7f29c5-7980-49d5-9add-9e649af8258c.png">

**Comment by cwomack** [comment]
@ACHP, our team is investigating improvements to the bundle size for Amplify. We will provide you with updates when we have the next steps identified. Thank you for providing us with this feedback!

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
