### ISSUE TITLE
Invalid login token. Issuer doesn't match providerName

### ISSUE THREAD

**Issue by tro9999** [aws-amplify/amplify-js#9409]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
 System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 511.11 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.18.2 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 2021.11.15.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 94.0.2
    Safari: 15.1
  npmPackages:
    @reach/auto-id: ^0.16.0 => 0.16.0 
    uuid: ^8.3.2 => 8.3.2 
  npmGlobalPackages:
    @aws-amplify/cli: 4.18.1
    @storybook/cli: 6.1.14
    api-spec-converter: 2.6.0
    babel-eslint: 10.0.2
    bower: 1.8.4
    contentful-cli: 0.34.1
    cordova: 6.5.0
    create-react-app: 2.1.1
    dotenv: 8.0.0
    eslint-config-airbnb: 16.1.0
    eslint-restricted-globals: 0.1.1
    eslint: 6.8.0
    expo-cli: 2.21.2
    ganache-cli: 6.1.5
    get-graphql-schema: 2.1.2
    gulp-cli: 2.2.0
    ionic: 4.12.0
    lerna: 4.0.0
    n: 4.1.0
    newman: 4.5.4
    npm: 6.14.15
    npx: 10.2.0
    react-native-cli: 2.0.1
    remix-ide: 0.8.5
    scrypt: 6.0.3
    serverless-pseudo-parameters: 2.5.0
    serverless-step-functions: 2.12.0
    serverless: 1.83.3
    truffle: 4.1.13
    wscat: 2.2.1
    yarn: 1.22.17
```

</details>

### Describe the bug

Seems this is very close to this old issue https://github.com/aws-amplify/amplify-js/issues/6462

Also the proposed fix works in my case too, but for some reason it is not approved. 

If Amplify Auth config identityPoolRegion is different than userpool region, Auth.signIn() doesn't work as expected. Authentication is correct with userpool, proper tokens are returned, but Identitypool identity is unauthenticated. Browser console show request error  "Invalid login token. Issuer doesn't match providerName" and seems the provider name has incorrect region. Correct region should be identitypool region. 

### Expected behavior

Auth Identitypool region should be used with cognito identity provider name

### Reproduction steps

Simply configure Amplify Auth with different userpool region and identitypool region. 

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by ashika01** [comment]
@tro9999 could u try explicitly mentioning `identityPoolRegion` in aws config ? Would it be possible to share ur redacted aws-exports here?

**Comment by tro9999** [comment]
> @tro9999 could u try explicitly mentioning `identityPoolRegion` in aws config ? Would it be possible to share ur redacted aws-exports here?

This is my Auth-config... 
let AUTHConfig = {
  // To get the aws credentials, you need to configure
  // the Auth module with your Cognito Federated Identity Pool
  mandatorySignIn: false,
  userPoolId: config.cognito.USER_POOL_ID,
  identityPoolId: config.cognito.IDENTITY_POOL_ID,
  userPoolWebClientId: config.cognito.APP_CLIENT_ID,
  region: config.auth_region,
  identityPoolRegion: config.main_region,
  //region: config.main_region,
}
auth_region is us-east-1 and identitypool_region (main_region) is eu-west-1. Separation is required, because data is stored here in EU . 

In browser console I see  https://cognito-identity.eu-west-1.amazonaws.com/ request (POST+Preflight) 
payload is like this... 
IdentityId: "eu-west-1:2965aca4-dc6a-41ab-8f8b-df4679685931"
Logins: {,…}
cognito-idp.eu-west-1.amazonaws.com/us-east-1_L9xxxxx: "eyJra.....

and response status is 400 with following message.

 message: "Invalid login token. Issuer doesn't match providerName"}
message: "Invalid login token. Issuer doesn't match providerName"
__type: "NotAuthorizedException"

I have tested the year old solution and it seems to solve this issue. (https://github.com/juranki/amplify-js/commit/29af87c566749002c1f3d0a65c801940f8cd1d83)

**Comment by tro9999** [comment]
May I ask, why this issue was closed? Is it something, that is not going to be fixed.... then I would like to know why. If you need more informations, I'll gladly provide more and I even gave the old #PR, which solves this bug.

**Comment by ashika01** [comment]
Hi @tro9999, this issue shouldn’t be closed. Sorry about that! I will look into the old PR and get back on this.

**Comment by tro9999** [comment]
Hi,
Any update on this?

**Comment by chrisbonifacio** [comment]
Hi @tro9999 sorry for the delay, we're still aware of the issue here and discussing possible actions we can take to address it from the library.

**Comment by nadetastic** [comment]
Hi @tro9999 - following up here

This is now supported as a result of https://github.com/aws-amplify/amplify-js/pull/10709

I'll mark this issue as solved, thank you!
