### ISSUE TITLE
AWSS3Provider - get signed url error TypeError

### ISSUE THREAD

**Issue by SolokiAbbas** [aws-amplify/amplify-js#9416]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

GraphQL API

### Amplify Categories

storage

### Environment information

<details>

```
# Put output below this line
 npmPackages:
    @ampproject/toolbox-optimizer:  undefined ()
    @babel/core:  undefined ()
    @peculiar/webcrypto:  undefined ()
    @types/node: 16.11.6 => 16.11.6 (16.11.12)
    @types/react: 17.0.33 => 17.0.33 (17.0.37)
    @typescript-eslint/eslint-plugin: ^5.4.0 => 5.6.0
    @vercel/nft:  undefined ()
    @zeit/next-sass: ^1.0.1 => 1.0.1
    amphtml-validator:  undefined ()
    antd: 4.17.0 => 4.17.0
    arg:  undefined ()
    async-retry:  undefined ()
    async-sema:  undefined ()
    aws-amplify: ^4.3.8 => 4.3.10
    aws-amplify-react: ^5.1.9 => 5.1.9
    babel-packages:  undefined ()
    ci-info:  undefined ()
    cli-select:  undefined ()
    comment-json:  undefined ()
    compression:  undefined ()
    conf:  undefined ()
    content-type:  undefined ()
    cookie:  undefined ()
    cross-spawn:  undefined ()
    debug:  undefined ()
    devalue:  undefined ()
    escape-string-regexp:  undefined ()
    eslint: 7 => 7.32.0
    eslint-config-next: 12.0.2 => 12.0.2
    find-cache-dir:  undefined ()
    find-up:  undefined ()
    formdata-node:  undefined ()
    fresh:  undefined ()
    glob:  undefined ()
    gzip-size:  undefined ()
    http-proxy:  undefined ()
    husky: ^4.2.1 => 4.3.8
    icss-utils:  undefined ()
    ignore-loader:  undefined ()
    is-animated:  undefined ()
    is-docker:  undefined ()
    is-wsl:  undefined ()
    json5:  undefined ()
    jsonwebtoken:  undefined ()
    lint-staged: ^12.0.3 => 12.1.2
    loader-utils:  undefined ()
    lodash.curry:  undefined ()
    lru-cache:  undefined ()
    micromatch:  undefined ()
    mini-css-extract-plugin:  undefined ()
    nanoid:  undefined ()
    native-url:  undefined ()
    neo-async:  undefined ()
    next: 12.0.2 => 12.0.2
    next-purgecss: ^4.0.0 => 4.0.0
    next-redux-wrapper: ^7.0.5 => 7.0.5
    nextjs-progressbar: ^0.0.13 => 0.0.13
    node-libs-browser:  undefined ()
    node-sass: ^6.0.1 => 6.0.1
    ora:  undefined ()
    postcss-flexbugs-fixes:  undefined ()
    postcss-modules-extract-imports:  undefined ()
    postcss-modules-local-by-default:  undefined ()
    postcss-modules-scope:  undefined ()
    postcss-modules-values:  undefined ()
    postcss-preset-env:  undefined ()
    postcss-safe-parser:  undefined ()
    postcss-scss:  undefined ()
    postcss-value-parser:  undefined ()
    prettier: ^2.4.1 => 2.5.1
    pretty-quick: ^3.1.2 => 3.1.2
    quill-image-uploader: ^1.2.2 => 1.2.2
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
    react-indiana-drag-scroll: ^2.1.0 => 2.1.0
    react-quill: ^1.3.5 => 1.3.5
    react-redux: ^7.2.6 => 7.2.6
    react-server-dom-webpack:  undefined ()
    redux: ^4.1.2 => 4.1.2
    redux-devtools-extension: ^2.13.9 => 2.13.9
    redux-thunk: ^2.4.1 => 2.4.1
    resolve-url-loader:  undefined ()
    sass: ^1.43.4 => 1.44.0
    sass-loader:  undefined ()
    schema-utils:  undefined ()
    semver:  undefined ()
    send:  undefined ()
    source-map:  undefined ()
    string-hash:  undefined ()
    strip-ansi:  undefined ()
    swr: ^1.0.1 => 1.1.0
    swr-immutable:  0.0.1
    swr-infinite:  0.0.1
    terser:  undefined ()
    text-table:  undefined ()
    typescript: 4.4.4 => 4.4.4
    ua-parser-js:  undefined ()
    unistore:  undefined ()
    uuid:  undefined ()
    web-streams-polyfill:  undefined ()
    web-vitals:  undefined ()
    webpack:  undefined ()
    webpack-sources:  undefined ()
    ws:  undefined ()
  npmGlobalPackages:
    @aws-amplify/cli: 7.6.5
    parcel-bundler: 1.12.5
    yarn: 1.22.17

```

</details>

### Describe the bug

`AWSS3Provider - get signed url error TypeError: Cannot read properties of undefined (reading 'byteLength')`

I am trying to do a get `const res = await Storage.get("test.json");`

The rest .list or .put do not work either and give the same results.

It is giving me that error. I made sure authroles have permissions, made sure i have the latest amplify, made sure the config has correct info, yet no luck. I even removed node_modules and reinstalled. 

`    at Object.fromArrayBuffer (C:\Users\asolo\Desktop\Coding\project\rates-web\node_modules\@aws-sdk\hash-node\node_modules\@aws-sdk\util-buffer-from\dist\cjs\index.js:6:60)
    at castSourceData (C:\Users\asolo\Desktop\Coding\project\rates-web\node_modules\@aws-sdk\hash-node\dist\cjs\index.js:29:31)
    at Hash.update (C:\Users\asolo\Desktop\Coding\project\rates-web\node_modules\@aws-sdk\hash-node\dist\cjs\index.js:12:26)
    at hmac (C:\Users\asolo\Desktop\Coding\project\rates-web\node_modules\@aws-sdk\s3-request-presigner\node_modules\@aws-sdk\signature-v4\dist\cjs\credentialDerivation.js:60:10)
    at Object.getSigningKey (C:\Users\asolo\Desktop\Coding\project\rates-web\node_modules\@aws-sdk\s3-request-presigner\node_modules\@aws-sdk\signature-v4\dist\cjs\credentialDerivation.js:32:29)
    at SignatureV4.getSigningKey (C:\Users\asolo\Desktop\Coding\project\rates-web\node_modules\@aws-sdk\s3-request-presigner\node_modules\@aws-sdk\signature-v4\dist\cjs\SignatureV4.js:139:39)
    at SignatureV4.presign (C:\Users\asolo\Desktop\Coding\project\rates-web\node_modules\@aws-sdk\s3-request-presigner\node_modules\@aws-sdk\signature-v4\dist\cjs\SignatureV4.js:43:106)`

### Expected behavior

I should just be able to get the test.json in my S3

### Reproduction steps

1. install next.js 
2. install typescript
3. install aws-amplify
4. add auth
5. add api
6. add storage
7. write code to .get

### Code Snippet

```javascript
// Put your code below this line.
export const getStaticProps: GetStaticProps = async ({ params }) => {

  // const res2 = await Storage.put("test.txt", "hello");
  // console.log(res2);
  const res = await Storage.get("test.json");
  console.log(res);
  return {
    props: {
      data: res,
      params: params?.subclass as string,
    },
  };
};
```

### Log output

<details>

```
// Put your logs below this line
at Object.fromArrayBuffer (C:\Users\asolo\Desktop\Coding\project\rates-web\node_modules\@aws-sdk\hash-node\node_modules\@aws-sdk\util-buffer-from\dist\cjs\index.js:6:60)
    at castSourceData (C:\Users\asolo\Desktop\Coding\project\rates-web\node_modules\@aws-sdk\hash-node\dist\cjs\index.js:29:31)
    at Hash.update (C:\Users\asolo\Desktop\Coding\project\rates-web\node_modules\@aws-sdk\hash-node\dist\cjs\index.js:12:26)
    at hmac (C:\Users\asolo\Desktop\Coding\project\rates-web\node_modules\@aws-sdk\s3-request-presigner\node_modules\@aws-sdk\signature-v4\dist\cjs\credentialDerivation.js:60:10)
    at Object.getSigningKey (C:\Users\asolo\Desktop\Coding\project\rates-web\node_modules\@aws-sdk\s3-request-presigner\node_modules\@aws-sdk\signature-v4\dist\cjs\credentialDerivation.js:32:29)
    at SignatureV4.getSigningKey (C:\Users\asolo\Desktop\Coding\project\rates-web\node_modules\@aws-sdk\s3-request-presigner\node_modules\@aws-sdk\signature-v4\dist\cjs\SignatureV4.js:139:39)
    at SignatureV4.presign (C:\Users\asolo\Desktop\Coding\project\rates-web\node_modules\@aws-sdk\s3-request-presigner\node_modules\@aws-sdk\signature-v4\dist\cjs\SignatureV4.js:43:106)

```

</details>

### aws-exports.js

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:xxx",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xxx",
    "aws_user_pools_web_client_id": "xxx",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://xxx.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "xxx",
    "aws_user_files_s3_bucket": "xxx-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};

**Comment by zachjonesnoel** [comment]
Hi @SolokiAbbas,

Not sure if I'm reproducing it right but can you try the same with `download : true`?

`const res = await Storage.get("test.json", { download: true });`

**Comment by jamesaucode** [comment]
It seems like you are trying to call `Storage.get` inside `getStaticProps` with nextJS. Unfortunately this is not supported atm. I will mark this as a feature request.

**Comment by nadetastic** [comment]
Closing this in favor of #7505 which contains a work around
