### ISSUE TITLE
Make apiName and Init parameter optional

### ISSUE THREAD

**Issue by siammridha** [aws-amplify/amplify-js#9429]
**Page**: [`/lib/restapi/fetch/q/platform/[platform]`](https://docs.amplify.aws/lib/restapi/fetch/q/platform/js/#get-requests)

**Feedback**:

it's really annoying that you have to pass the init parameter every time you are making an API request. Not really sure why it's required now because it definitely was not in version 1.2.4 which is when I used it last. Also it would be a good idea to make the apiName parameter optional as well and an option to choose a default app.

**Comment by chrisbonifacio** [comment]
Closing in favor of #4675
