### ISSUE TITLE
Cookies persisting after logout: `deviceKey`, `deviceGroupKey`, `randomPasswordKey`

### ISSUE THREAD

**Issue by kernowal** [aws-amplify/amplify-js#9435]
### Before opening, please confirm:

- [x] I have searched for duplicate or closed issues and discussions.
- [x] I have read the guide for submitting bug reports.
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Auth, Storage

### Amplify Categories

auth, storage

### Environment information

<details>

```
 System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 1.20 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.8.0 - ~/.nvm/versions/node/v11.8.0/bin/node
    npm: 6.5.0 - ~/.nvm/versions/node/v11.8.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 95.0
    Safari: 14.1.2
  npmPackages:
    @hookform/resolvers: 1.3.0 => 1.3.0 
    @material-ui/core: 4.11.0 => 4.11.0 
    @material-ui/icons: 4.9.1 => 4.9.1 
    @material-ui/lab: 4.0.0-alpha.56 => 4.0.0-alpha.56 
    @sentry/react: ^6.0.4 => 6.0.4 
    @stripe/react-stripe-js: 1.1.2 => 1.1.2 
    @stripe/stripe-js: 1.11.0 => 1.11.0 
    @testing-library/jest-dom: 4.2.4 => 4.2.4 
    @testing-library/react: 9.5.0 => 9.5.0 
    @testing-library/user-event: 7.2.1 => 7.2.1 
    @types/html2canvas: 0.0.36 => 0.0.36 
    @types/jest: 24.9.1 => 24.9.1 
    @types/node: 12.12.67 => 12.12.67 (14.14.7)
    @types/react: 16.9.52 => 16.9.52 (16.9.56)
    @types/react-dom: 16.9.8 => 16.9.8 
    @types/react-pdf: 5.0.1 => 5.0.1 
    @types/react-redux: 7.1.9 => 7.1.9 
    @types/react-router-dom: 5.1.6 => 5.1.6 
    @types/react-router-hash-link: 1.2.1 => 1.2.1 
    @types/recharts: 1.8.16 => 1.8.16 
    @types/uuid: ^8.3.3 => 8.3.3 
    aws-amplify: ^4.3.11 => 4.3.11 
    axios: 0.21.0 => 0.21.0 (0.21.4)
    clsx: 1.1.1 => 1.1.1 
    date-fns: 2.16.1 => 2.16.1 
    eslint-plugin-import: 2.22.1 => 2.22.1 (2.20.1)
    eslint-plugin-react-hooks: 4.1.2 => 4.1.2 (1.7.0)
    html2canvas: 1.0.0-rc.5 => 1.0.0-rc.5 
    husky: 4.3.0 => 4.3.0 
    i18next: 19.8.2 => 19.8.2 
    jest-canvas-mock: 2.3.0 => 2.3.0 
    jspdf: 2.1.1 => 2.1.1 (2.1.0)
    lint-staged: 10.4.0 => 10.4.0 
    lottie-web: 5.7.3 => 5.7.3 
    material-table: 1.69.1 => 1.69.1 
    memo-parser:  0.2.1 
    mutationobserver-shim: 0.3.7 => 0.3.7 
    nanoid: 3.1.16 => 3.1.16 
    prettier: 2.1.2 => 2.1.2 
    rc-field-form: 1.15.1 => 1.15.1 
    react: 16.13.1 => 16.13.1 
    react-dom: 16.13.1 => 16.13.1 
    react-ga: ^3.3.0 => 3.3.0 
    react-hook-form: 6.15.1 => 6.15.1 
    react-i18next: 11.7.3 => 11.7.3 
    react-markdown: 5.0.3 => 5.0.3 
    react-pdf: 5.2.0 => 5.2.0 
    react-redux: 7.2.2 => 7.2.2 
    react-router-dom: 5.2.0 => 5.2.0 
    react-router-hash-link: 2.3.1 => 2.3.1 
    react-scripts: 3.4.3 => 3.4.3 
    react-spring: 8.0.27 => 8.0.27 
    recharts: 1.8.5 => 1.8.5 
    redux: 4.0.5 => 4.0.5 
    redux-saga: 1.1.3 => 1.1.3 
    redux-saga-test-plan: 4.0.1 => 4.0.1 
    redux-saga/effects:  undefined ()
    typescript: 3.9.7 => 3.9.7 
    uuid: ^8.3.2 => 8.3.2 (3.4.0, 3.3.2)
    yup: 0.32.8 => 0.32.8 
  npmGlobalPackages:
    @aws-amplify/cli: 4.32.1
    expo-cli: 3.21.0
    npm: 6.5.0

```

</details>

### Issue

I am sharing authentication across subdomains by using Amplify's built-in cookieStorage. When logging in and out with different Users, the `deviceKey`, `deviceGroupKey`, `randomPasswordKey` cookies are persisting. This is making the RequestHeader increase in size with time, resulting in a `RequestHeaderSectionTooLarge` error, which prevents the page from loading until the cookies are removed manually.

### Cause

When using cookieStorage, Amplify stores the `accessToken`, `refreshToken` and `idToken`, which are all sizeable and pose a potential security risk as outlined in #3436. The size of these, coupled with the persisting cookies for multiple Users is causing the request header to exceed the maximum allwed size.

Other solutions to this security issue involve using local Storage to store the tokens, but as I understand this will not allow the authentication to be shared between subDomains.

**Why are these cookies persisting after logout?**

### Attempts to resolve

I have attempted to programatically remove all cookies on logout, but this causes the following browser warning:

`Some cookies are misusing the recommended "SameSite" attribute`
`Cookie "CognitoIdentityServiceProvider.xxxx.user.deviceKey" will be soon rejected because it has the "SameSite" attribute set to "None" or an invalid value, without the "secure" attribute`

As you can see from the config below, `SameSite` is set to `"lax"` and `secure` is set to `True`, as long as we are not running on `localhost`. 

NB: When testing the programmatic removal of the cookies on `localhost` there are no issues, it is only failing to remove the cookies once deployed. However the cookies persist locally without programmatically removing them.

### Configuration

Amplify config:
```
Amplify.configure({
  ...
  cookieStorage: {
    domain: getEnv().DOMAIN,
    path: "/",
    expires: 30,
    sameSite: "lax",
    secure: getEnv().DOMAIN !== "localhost",
  },
  ...
});
```

### Code snippet

**deleteCookies** function to programmatically remove cookies (called on login and logout):
```
const deleteCookies = () => {
  var cookies = document.cookie.split(";");
  for (var i = 0; i < cookies.length; i++) {
    var cookie = cookies[i];
    var eqPos = cookie.indexOf("=");
    var name = eqPos > -1 ? cookie.substr(0, eqPos) : cookie;
    document.cookie = name + "=;expires=Thu, 01 Jan 1970 00:00:00 GMT";
  }
};
```

### Expected behavior

Be able to log in and out endless times with different Users without exceeding the RequestHeader size limit

### Reproduction steps

1. Run webapp
2. Login with User A
3. Logout
4. Login with User B
5. Logout
6. Login with User C
7. Logout
8. Login with User D
9. Logout
10. Login with User E
11. Page crashes

### Manual configuration

```
Amplify.configure({
  aws_project_region: "eu-west-2",
  aws_cognito_identity_pool_id: "eu-west-2:xxxx",
  aws_cognito_region: "eu-west-2",
  aws_user_pools_id: "eu-west-2:xxxx",
  aws_user_pools_web_client_id: "xxxx",
  cookieStorage: {
    domain: getEnv().DOMAIN,
    path: "/",
    expires: 30,
    sameSite: "lax",
    secure: getEnv().DOMAIN !== "localhost",
  },
  Auth: {
    identityPoolId: "eu-west-2:xxxx",
    region: "eu-west-2",
  },
});
```

### Additional information and screenshots

![image](https://user-images.githubusercontent.com/30602325/148379502-bbe10c5a-0960-4d76-b6f8-75d0cd9de244.png)

**Comment by kernowal** [comment]
@chrisbonifacio any update on this?

**Comment by kernowal** [comment]
@chrisbonifacio have you had a chance to investigate this yet?

**Comment by deepaktammali** [comment]
In my use case I am using localStorage for storing the information, local storage keys ending with deviceKey, randomPasswordKey and deviceGroupKey are not getting removed after logout.

**Comment by tannerabread** [comment]
Hi @kernowal @deepaktammali I am able to see that those keys persist after logout, but are either of you still experiencing the app crashing after a few users log in? I tried to reproduce this and logged in with about 15 users with no error about header size limit

**Comment by deepaktammali** [comment]
Hi @tannerabread, 

Thanks for the response.

I am using localStorage as the storage for the keys.
I am not experiencing any issues, It seems that these keys are constructed using the user sub. So If a same user is signing in, It seems the same keys are replaced. I just wanted to know If there is any reason that we are persisting these keys after the user signed out.

**Comment by deepaktammali** [comment]
understood, thanks @israx.
