### ISSUE TITLE
Storybook : bootstrap:856 Uncaught TypeError: Cannot read properties of undefined (reading 'call')

### ISSUE THREAD

**Issue by Sakinalh** [aws-amplify/amplify-js#9458]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
 System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
    Memory: 1013.91 MB / 15.55 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.9.1 - ~/.nvm/versions/node/v16.9.1/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.1.4 - ~/workspace/node_modules/.bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 95.0.1
  npmPackages:
    @babel/core: ^7.9.6 => 7.16.0 (7.12.3, 7.16.7, 7.12.9)
    @date-io/dayjs: 1.x => 1.3.13 (2.11.0)
    @emotion/react: ^11.1.5 => 11.6.0 
    @emotion/styled: ^11.1.5 => 11.6.0 (10.3.0)
    @hookform/resolvers: ^2.8.0 => 2.8.3 
    @loadable/component: ^5.14.1 => 5.15.0 
    @material-ui/core: ^5.0.0-alpha.25 => 5.0.0-beta.5 
    @material-ui/icons: ^5.0.0-alpha.24 => 5.0.0-beta.5 
    @material-ui/lab: ^5.0.0-alpha.25 => 5.0.0-alpha.44 
    @material-ui/pickers: ^3.3.10 => 3.3.10 
    @mui/icons-material: ^5.0.3 => 5.1.1 
    @mui/lab: ^5.0.0-alpha.55 => 5.0.0-alpha.55 
    @mui/material: ^5.2.1 => 5.2.1 
    @mui/styles: ^5.0.1 => 5.1.1 
    @react-mock/state: ^0.1.8 => 0.1.8 
    @sentry/browser: ^6.2.0 => 6.15.0 
    @sentry/react: ^6.9.0 => 6.15.0 
    @sentry/tracing: ^6.9.0 => 6.15.0 
    @storybook/addon-actions: ^6.4.9 => 6.4.9 
    @storybook/addon-essentials: ^6.4.9 => 6.4.9 
    @storybook/addon-links: ^6.4.9 => 6.4.9 
    @storybook/node-logger: ^6.4.9 => 6.4.9 
    @storybook/preset-create-react-app: ^3.2.0 => 3.2.0 
    @storybook/react: ^6.4.9 => 6.4.9 
    @testing-library/jest-dom: ^5.11.9 => 5.15.0 
    @testing-library/react: ^11.2.5 => 11.2.7 
    @testing-library/react-hooks: ^5.0.3 => 5.1.3 
    @testing-library/user-event: ^12.6.2 => 12.8.3 
    @types/jest: ^26.0.20 => 26.0.24 (27.0.3)
    @types/mocha: ^8.2.0 => 8.2.3 
    @types/node: ^14.14.28 => 14.17.34 (16.11.9, 14.18.5, 12.12.50)
    @types/react: ^17.0.2 => 17.0.35 
    @types/react-beautiful-dnd: ^13.0.0 => 13.1.2 
    @types/react-dom: ^17.0.1 => 17.0.11 
    @types/react-router: ^5.1.11 => 5.1.17 
    @types/react-router-dom: ^5.1.7 => 5.3.2 
    @types/styled-components: ^5.1.7 => 5.1.15 
    @typescript-eslint/eslint-plugin: ^5.4.0 => 5.4.0 (4.33.0)
    array-move: ^3.0.1 => 3.0.1 
    awesome-typescript-loader: ^5.2.1 => 5.2.1 
    aws-amplify: ^4.3.12 => 4.3.12 
    axios: ^0.21.1 => 0.21.4 
    axios-observable: ^1.3.0 => 1.3.0 
    babel-loader: 8.1.0 => 8.1.0 (8.2.3)
    class-validator:  1.0.0 
    computed-types:  1.0.0 
    cypress: ^6.8.0 => 6.9.1 
    date-fns: ^2.16.1 => 2.26.0 (1.30.1)
    dayjs: ^1.10.6 => 1.10.7 
    dotenv: ^8.2.0 => 8.6.0 (8.2.0)
    dotenv-expand: ^5.1.0 => 5.1.0 
    eslint: ^7.32.0 => 7.32.0 
    eslint-config-airbnb: ^19.0.0 => 19.0.0 
    eslint-plugin-react: ^7.27.0 => 7.27.1 (7.21.5)
    eslint-plugin-storybook: ^0.5.5 => 0.5.5 
    fp-ts: ^2.9.3 => 2.11.5 
    frisby: ^2.1.3 => 2.1.3 
    history: ^5.0.0 => 5.1.0 (5.0.0, 5.2.0)
    html5-file-selector: ^2.1.0 => 2.1.0 
    husky: =4 => 4.3.8 
    immer: ^8.0.1 => 8.0.4 (9.0.6, 8.0.1)
    io-ts: ^2.2.13 => 2.2.16 (1.0.0)
    jest-localstorage-mock: ^2.4.6 => 2.4.18 
    joi:  1.0.0 
    lint-staged: >=10 => 12.0.3 
    lodash: ^4.17.21 => 4.17.21 
    msw: ^0.26.0 => 0.26.2 
    newman: ^5.2.4 => 5.3.0 
    nope:  1.0.0 
    prettier: ^2.2.1 => 2.4.1 
    query-string: ^7.0.1 => 7.0.1 (4.3.4)
    react: ^17.0.1 => 17.0.2 
    react-beautiful-dnd: ^13.1.0 => 13.1.0 
    react-dom: ^17.0.1 => 17.0.2 
    react-dropzone: ^11.3.1 => 11.4.2 
    react-dropzone-uploader: ^2.11.0 => 2.11.0 
    react-hook-form: ^7.2.2 => 7.20.1 
    react-loadable: ^5.5.0 => 5.5.0 
    react-multi-carousel: ^2.6.3 => 2.6.5 
    react-query: ^3.23.2 => 3.33.1 
    react-redux: ^7.2.2 => 7.2.6 
    react-router: ^6.0.0-beta.0 => 6.0.2 (6.2.1)
    react-router-dom: ^6.0.0-beta.0 => 6.0.2 (6.2.1)
    react-scripts: ^4.0.3 => 4.0.3 
    react-sortable-hoc: ^2.0.0 => 2.0.0 
    react-test-render: ~1.1.2 => 1.1.2 
    react-test-renderer: ^17.0.1 => 17.0.2 
    react-virtual: ^2.4.0 => 2.8.2 
    recharts: ^2.1.4 => 2.1.6 
    redux: ^4.0.5 => 4.1.2 
    redux-devtools-extension: ^2.13.9 => 2.13.9 
    redux-observable: ^1.2.0 => 1.2.0 
    redux-persist: ^6.0.0 => 6.0.0 
    redux-persist/integration/react:  undefined ()
    rxjs: ^6.6.6 => 6.6.7 (7.4.0)
    rxjs-compat: ^6.6.6 => 6.6.7 
    rxjs/ajax:  undefined ()
    rxjs/fetch:  undefined ()
    rxjs/internal-compatibility:  undefined ()
    rxjs/operators:  undefined ()
    rxjs/testing:  undefined ()
    rxjs/webSocket:  undefined ()
    semistandard: ^16.0.0 => 16.0.1 
    serve: ^13.0.2 => 13.0.2 
    source-map-explorer: ^2.5.2 => 2.5.2 
    styled-components: 5.2.1 => 5.2.1 
    styled-components/macro:  undefined ()
    styled-components/native:  undefined ()
    styled-components/primitives:  undefined ()
    stylelint: ^13.13.1 => 13.13.1 
    stylelint-config-standard: ^22.0.0 => 22.0.0 
    superstruct:  1.0.0 
    ts-node: ^9.1.1 => 9.1.1 
    typanion:  1.0.0 
    typedoc: ^0.20.25 => 0.20.37 
    typescript: ^4.2.3 => 4.5.2 (4.5.4)
    unimported: ^1.19.1 => 1.19.1 
    vest:  1.0.0 
    yup: ^0.32.9 => 0.32.11 (1.0.0)
    zod:  1.0.0 
  npmGlobalPackages:
    @aws-amplify/cli: 7.6.5
    corepack: 0.9.0
    expo-cli: 4.13.0
    lighthouse: 9.1.0
    modclean: 3.0.0-beta.1
    nodemon: 2.0.15
    npm: 7.21.1
    serve: 13.0.2

```

</details>

### Describe the bug

My react app is using cognito, as soon as i add react-redux provider globally for storybook, and run  yarn storybook it keeps loading and i have an error in the console where aws-amplify is involded that start like this :  `Cannot read properties of undefined (reading 'call')
    at __webpack_require__ (bootstrap:856)...`
 The strange thing is that i have no error when running my react app.

### Expected behavior

Expect Storybook to be launched normally with my components on the left

### Reproduction steps

1: yarn start
2: start-storybook -p 6006 -s public

### Code Snippet

```javascript
// Put your code below this line.
```
performReload @ VM49 vendors~main.iframe.bundle.js:315890
logUpdates @ VM49 vendors~main.iframe.bundle.js:315854
applyCallback @ VM49 vendors~main.iframe.bundle.js:315810
(anonymous) @ VM49 vendors~main.iframe.bundle.js:315818
Promise.then (async)
cb @ VM49 vendors~main.iframe.bundle.js:315817
(anonymous) @ VM49 vendors~main.iframe.bundle.js:315828
Promise.then (async)
check @ VM49 vendors~main.iframe.bundle.js:315827
push../node_modules/webpack-hot-middleware/process-update.js.module.exports @ VM49 vendors~main.iframe.bundle.js:315789
processMessage @ VM49 vendors~main.iframe.bundle.js:315457
handleMessage @ VM49 vendors~main.iframe.bundle.js:315317
handleMessage @ VM49 vendors~main.iframe.bundle.js:315280
bootstrap:856 Uncaught TypeError: Cannot read properties of undefined (reading 'call')
    at __webpack_require__ (VM47 runtime~main.iframe.bundle.js:857)
    at fn (VM47 runtime~main.iframe.bundle.js:151)
    at Object../node_modules/@aws-amplify/storage/lib-esm/index.js (VM49 vendors~main.iframe.bundle.js:6968)
    at __webpack_require__ (VM47 runtime~main.iframe.bundle.js:857)
    at fn (VM47 runtime~main.iframe.bundle.js:151)
    at Object../node_modules/aws-amplify/lib-esm/index.js (VM49 vendors~main.iframe.bundle.js:155350)
    at __webpack_require__ (VM47 runtime~main.iframe.bundle.js:857)
    at fn (VM47 runtime~main.iframe.bundle.js:151)
    at Object.<anonymous> (VM50 main.iframe.bundle.js:82171)
    at Object../src/index.tsx (VM50 main.iframe.bundle.js:82603)

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Manual configuration

const baseCFG = {
  Common: {
    "Auth": {
      "identityPoolId": "xx-xxxx-x:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "region": "xx-xxxx-x",
      "userPoolId": "xx-xxxx-x_xxxxxxxxx",
      "userPoolWebClientId": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
      "authenticationFlowType": "USER_SRP_AUTH"
    }
  }
};

switch (document.domain) {
  default:
    // prod
    baseCFG.Common.Auth.identityPoolId = "eu-west-1XXXXXXX";
    baseCFG.Common.Auth.region = baseCFG.Common.Auth.identityPoolId.split(":")[0];
    baseCFG.Common.Auth.userPoolId = "eu-west-5_XXXX";
    baseCFG.Common.Auth.userPoolWebClientId = "121wwwx12x12x1x21";

}

export default baseCFG;

### Additional information and screenshots

![image](https://user-images.githubusercontent.com/86977100/148762553-aef59662-9628-4775-b4dc-3db191a3ca71.png)

**Comment by chrisbonifacio** [comment]
Hi @Sakinalh 👋 thanks for raising this issue. A couple of questions to get more info

1. Could you provide either the repo where you're experiencing this issue if it's a public repo or the minimal steps to reproduce?

2. What kind of component are you trying to render with Storybook? Is it a custom ui or the Amplify UI library components?

3. Do you experience this error without the react-redux provider? I'm not familiar with using Redux and Storybook in the same project, if you could provide a guide or documentation you might've been following that can help as well. I'm currently looking at this: https://www.digitalocean.com/community/tutorials/react-storybook-with-redux

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!

**Comment by Sakinalh** [comment]
Hi,

Sorry to answer only now, our issu was fixed by importing Amplify the named
import way {Amplify} .... it still a mystery ...
That being said, thank you for your answer it make us rethink our
architecture and pass to a monorepo architecture in the future in order to
not having trouble with redux or amplify in our storybook...

Thank you 🙏 !

Le mer. 19 janv. 2022 à 21:28, Chris Bonifacio ***@***.***> a
écrit :

**Comment by napcoder** [comment]
>  fixed by importing Amplify the named import way {Amplify} .... it still a mystery ... 

You literally saved my life, thank you.

**Comment by James-Bu** [comment]
Exactly the same problem replaced:
`import Amplify from 'aws-amplify';`
with 
`import {Amplify} from 'aws-amplify';`
and suddenly my issue was resolved!
