### ISSUE TITLE
Cognito forgotPassword with invalid username, gives valid response and sends email to random email address

### ISSUE THREAD

**Issue by Baloc22m** [aws-amplify/amplify-js#9484]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

Just try 

const response = await Auth.forgotPassword(invalidUsername)

look at the response, it is sending an email notification despite the user does not exist

### Describe the bug

When I try forgotPassword api with invalid username, it still returns a valid response: CodeDeliveryDetails, it is sending a verification code to some random email or number. I am confused why is this happening.

Can someone will tell me if this is a known bug and if there is a workaround

### Expected behavior

It should return some error response according to the documentation

### Reproduction steps

n/a

### Code Snippet

```javascript

import {Auth} from 'aws-amplify';


await Auth.forgotPassword(username).then(response => {
 if (response) { 
        navigation!.navigate('NewPasswordPage', {username: username}); 

} else { 
       setError('username', { type: 'manual', message: 'User does not exist', });
 }
 });


```

I entered invalid username, and the response is:
CodeDeliveryDetails:
AttributeName: "email"
DeliveryMedium: "EMAIL"
Destination: "B***@y***.com"
[[Prototype]]: Object
[[Prototype]]: Object

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

package.json 

"amazon-cognito-identity-js": "^5.2.4",
    "aws-amplify": "^4.3.12",

**Comment by LeJ84** [comment]
Hi!
Have you checked "prevent user existence errors" in your cognito configuration ? If you did, it works as attempted. A 'User does not exist' gives to much information. If you didn't i let experts answer ^^.

**Comment by chrisbonifacio** [comment]
Hi @Baloc22m 👋 I was not able to reproduce this issue using the Amplify Auth library (used aws-amplify@4.3.12). When attempting to pass a username/email that didn't exist in my user pool but did not receive an email. I just got this error from Cognito instead.

<img width="766" alt="Screen Shot 2022-01-19 at 11 46 45 AM" src="https://user-images.githubusercontent.com/16952986/150176636-8c57566f-1f80-4cbe-9288-34425d7d553b.png">
