### ISSUE TITLE
Amplify GraphQL support for local cache, refetchQueries and optimisticResponse

### ISSUE THREAD

**Issue by OlivierPT** [aws-amplify/amplify-js#949]
Do you want to request a feature or report a bug?

Feature report or documentation addition

What is the current behavior?

I can't find any documentation to know if Amplify GraphQL client supports local cache and refetchQueries, optimisticResponse option for Mutations and how to use it.
Is it planned?  Do we have, or should we have the same feature with the Amplify API and with the Connect component for React?

What is the expected behavior?

It would be great that Amplify support all graphql client option and that these options are documented.

**Comment by manueliglesias** [comment]
Hi @OlivierPT 

For now, Amplify's GraphQL support is basic (query, mutations and subscriptions), at the moment there is no caching, refetchQueries or support for optimistic UIs.

This first release is intended to be a simple and very easy to use client. As for future plans, there's nothing concrete yet but feedback like yours is very welcome and great to help us plan.

**Comment by OlivierPT** [comment]
Hi @manueliglesias,

Thanks for these informations.
Indeed, current Amplify Graphql implementation is easy to use but I am pretty sure than I am not the only one to wait for the implementation of the other features than come with graphql and which are the real power of it. :)
I really hope it will come!

In the mean time, I feel the most complete solution remains aws-appsync and appollo client.

**Comment by OlivierPT** [comment]
Hi @undefobj ,

I am working on the development of a PWA for a startup, so I am definitely looking for all the features of GraphQL and AppSync : refretchQuery after mutation, cache for offline and optimisticUI... 
Currently, I don't use Redux or Mobx but I would not be surprised to have to integrate it later...

At one point, I was thinking that the point of Amplify would be to unify the existing AWS libs so I was expecting to have all these features inside Amplify... But as you said, there are already Appollo and AWS Appsync SDK (that I experimented in the past - I was just thinking to find a more simple solution with Amplify), it is ok for me to use it. And if it happens that Amplify provides all the features, then no problem to migrate back to Amplify when they would be available :)

**Comment by undefobj** [comment]
@OlivierPT the goals of Amplify aren't around unification of SDKs, though that may be a natural byproduct. It might be good to read the goals of the project here: https://github.com/aws/aws-amplify/wiki

What I'm mostly curious is do you actually need controls of things like refetching queries or optimistic UI, or could it just happen automatically for you?

**Comment by OlivierPT** [comment]
Hi @undefobj 

Actually, I was expecting Amplify to handle refetchQuery after a mutation call and to manage  the cache, the optimisticResponse and so on "automatically"... Despite I think it is necessary to have some params and callbacks. Indeed, I think it would suite to most of my uses cases, at least for now, since we are just starting the project and we are targeting a simple first version.

That would be definitely a great plus to get these feature from the beginning with Amplify when you start a new project.

Do you think this could be implemented in Amplify? Would you be able to provide a rought schedule?

**Comment by buggy** [comment]
@OlivierPT It's probably better to use Apollo's React components rather implement the same functionality inside Amplify. They've put a lot of though and effort into making a GraphQL client that's power and easy to use. The mobile appsync sdk provides a compatible client for Apollo that you integrate with Amplify to handle authentication and everything else.

**Comment by OlivierPT** [comment]
Hi @buggy ,
Thank you for your answer. I agree with you that appsync-sdk and apollo-client seems to be the best solution for my needs with appsync/graphql.

**Comment by joshuagamboa** [comment]
I assume then that the default fetch policy for Amplify's simple query support for appsync is "network-only". Is this correct? Thanks.

**Comment by jordanranz** [comment]
@joshuagamboa, that is correct for now. Amplify's fetch is "network-only" at the moment.

I am going to close this as the question above seemed to have been answered. Please reopen if you have any related questions or concerns.
