### ISSUE TITLE
Get Push Notification Token after initial request

### ISSUE THREAD

**Issue by marcato15** [aws-amplify/amplify-js#9496]
### Is this related to a new or existing framework?

React Native

### Is this related to a new or existing API?

Push Notifications

### Describe the feature you'd like to request

I would like to be able to get the device token for a Push Notification after the initial permission request. There are a number of reasons for this like handling the deregistration of push notifications (we currently are doing this manually). According to the docs, only the initial time a user is asked for their permission with the register callback get triggered. 

### Describe the solution you'd like

I would like to be able to manually call the registerDevice function multiple times and get the device token if the user has already granted permissions.

### Describe alternatives you've considered

Using a different library as other libraries currently implement this feature.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by RMG0** [comment]
Hey, Faced the similar issue and what I endup doing is like put this code in `didFinishLaunchingWithOptions`

```
//Basically this will register with APNS irrespective of a user granted notification permissions. 
  if(![[UIApplication sharedApplication] isRegisteredForRemoteNotifications]){
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(5.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [[UIApplication sharedApplication] registerForRemoteNotifications];
    });
  }
```

Also, unofficial way you can get token by doing 
```
const aws_mobile_analytics_app_id = awsmobile.aws_mobile_analytics_app_id;
const awsPushToken = await AsyncStorage.getItem('push_token' + aws_mobile_analytics_app_id);
```

And this is true for android and iOS both.

Hope this helps

**Comment by tannerabread** [comment]
Hi @marcato15 we have recently released a rewritten Push Notification category with new features which includes the ability to [receive the device token on every app launch](https://docs.amplify.aws/lib/push-notifications/receive-device-token/q/platform/react-native/), can you try it out and let me know if it works for you?

You can follow the [migration steps here](https://docs.amplify.aws/lib/push-notifications/migrate-from-previous-version/q/platform/react-native/) or if you are starting again from scratch follow the [getting-started guide here](https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/react-native/)

**Comment by cshfang** [comment]
Hi @cn-cit would it be possible for you to share an app where this is minimally reproducible? In my local RN app - I have the following and it is receiving a token on app launch (i.e. app killed and reopened)

```
// index.js
Amplify.configure(config);
Notifications.Push.enable();

// App.tsx
const App = () => {
  useEffect(() => {
    const tokenListener = Notifications.Push.onTokenReceived(token => {
      console.log(`Got a new token: ${token}`);
    });

    return () => {
      tokenListener.remove();
    };
  }, []);
};
```

**Comment by cn-cit** [comment]
@tannerabread , sorry it has taken me a while to get back to this.  I tried commenting out everything my app did except for the useEffect as noted above.  Still no joy.

However, I did work out what was causing the problem ...
`export default withAuthenticator(App);`
When I removed the Amplify withAuthenticator wrap, it worked as documented.

**Comment by cshfang** [comment]
Shoots. I suspect the HOC pushes the token listener further into the app lifecycle - causing it to miss the event 🤔 

Would it be possible to re-compose your app a bit so that the initialization happens in the entry component first? E.g.

```tsx
// App.tsx
const App = () => {
  useEffect(() => {
    const tokenListener = Notifications.Push.onTokenReceived(token => {
      console.log(`Got a new token: ${token}`);
    });

    return () => {
      tokenListener.remove();
    };
  }, []);

  return <Main />
};
```
```tsx
// Main.tsx
const Main = () => {
}

export default withAuthenticator(Main)
```
```

**Comment by wasurocks** [comment]
> Hi @cn-cit would it be possible for you to share an app where this is minimally reproducible? In my local RN app - I have the following and it is receiving a token on app launch (i.e. app killed and reopened)
> 
> ```tsx
> // index.js
> Amplify.configure(config);
> Notifications.Push.enable();
> 
> // App.tsx
> const App = () => {
>   useEffect(() => {
>     const tokenListener = Notifications.Push.onTokenReceived(token => {
>       console.log(`Got a new token: ${token}`);
>     });
> 
>     return () => {
>       tokenListener.remove();
>     };
>   }, []);
> };
> ```

Hi, this is not working for me. I've tried putting the `onTokenReceived` method at all levels and it only gives me the token on the initial app installation and not every time the app is launched. This is making it difficult to access the token and unlike what the documentation mentions 😢

**Comment by wasurocks** [comment]
> Hi @marcato15 we have recently released a rewritten Push Notification category with new features which includes the ability to [receive the device token on every app launch](https://docs.amplify.aws/lib/push-notifications/receive-device-token/q/platform/react-native/), can you try it out and let me know if it works for you?
> 
> You can follow the [migration steps here](https://docs.amplify.aws/lib/push-notifications/migrate-from-previous-version/q/platform/react-native/) or if you are starting again from scratch follow the [getting-started guide here](https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/react-native/)

To reference what I said, I've followed all of this documentation linked.

**Comment by cn-cit** [comment]
@wasurocks my problem appears to be that I wrapped my component with the Amplify Authenticator ...
`export default withAuthenticator(Main)`
Without that it was fine.

I am testing the suggestion from @cshfang of splitting my App.tsx to a Main.tsx as well.  I will report how that goes later.

**Comment by wasurocks** [comment]
@cn-cit I see. I'm not using `withAuthenticator` so it's definitely not related to that. Would you suggest opening a new issue?

**Comment by cshfang** [comment]
> Hi, this is not working for me. I've tried putting the `onTokenReceived` method at all levels and it only gives me the token on the initial app installation and not every time the app is launched. This is making it difficult to access the token and unlike what the documentation mentions 😢 

@wasurocks are you experiencing this on Android, iOS or both? The token event should be fired on app launch, not every resume. Could you please confirm that you are fully quitting out of the app (i.e. swiping it away) and relaunching?

**Comment by cn-cit** [comment]
@cshfang that split worked for me.  thanks.

**Comment by cwomack** [comment]
@wasurocks, are you able to clarify what @cshfang asked above?

@marcato15, did you get a chance to see @tannerabread's [comment](https://github.com/aws-amplify/amplify-js/issues/9496#issuecomment-1513631836) regarding migrations steps and starting from scratch?

**Comment by cwomack** [comment]
Closing this issue as we have not heard back from you and it appears a few followers of this were fixed by the previous comments. If you are still experiencing this, please feel free to reply back and provide any information previously requested and we'd be happy to re-open the issue.

For reference: 

- [Comment](https://github.com/aws-amplify/amplify-js/issues/9496#issuecomment-1523577220) to split `App.tsx` and `Main.tsx`
- [Comment](https://github.com/aws-amplify/amplify-js/issues/9496#issuecomment-1513631836) about new Push Notifications features and migration steps to follow. 

Thank you!
