### ISSUE TITLE
Cognito Identity Service Provider returning different cognito error for Refresh Token API from Jan 21st, 2022.

### ISSUE THREAD

**Issue by Suvab-rently** [aws-amplify/amplify-js#9502]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication

### Environment information

<details>

```
# Put output below this line
System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 354.88 MB / 15.49 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.4/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 96.0
  npmPackages:
    @airbrake/node: ^2.1.7 => 2.1.7 
    amazon-cognito-identity-js: ^1.29.0 => 1.31.0 
    axios: ^0.21.0 => 0.21.0 
    babel-webpack:  1.0.0 
    body-parser: ^1.19.0 => 1.19.0 
    celebrate: ^13.0.4 => 13.0.4 
    chai: ^4.2.0 => 4.2.0 
    chai-as-promised: ^7.1.1 => 7.1.1 
    cookie-parser: ^1.4.5 => 1.4.5 
    cors: ^2.8.5 => 2.8.5 
    crypto: ^1.0.1 => 1.0.1 
    ejs: ^3.1.5 => 3.1.5 
    express: ^4.17.1 => 4.17.1 
    express-http-proxy: ^1.6.2 => 1.6.2 
    fs: 0.0.1-security => 0.0.1-security 
    jsonwebtoken: ^8.5.1 => 8.5.1 
    jwk-to-pem: ^2.0.4 => 2.0.4 
    mocha: ^8.2.1 => 8.2.1 
    morgan: ^1.10.0 => 1.10.0 
    node-mocks-http: ^1.9.0 => 1.9.0 
    nyc: ^15.1.0 => 15.1.0 
    proxyquire: ^2.1.3 => 2.1.3 
    redis: ^3.0.2 => 3.0.2 
    request: ^2.88.2 => 2.88.2 
    serverless-domain-manager: ^5.1.0 => 5.1.0 
    serverless-http: ^2.6.0 => 2.6.0 
    serverless-offline: ^8.3.1 => 8.3.1 
    sinon: ^9.2.1 => 9.2.1 
  npmGlobalPackages:
    npm: 6.14.6


```

</details>

### Describe the bug

I have a single userPool under which I have two client apps.

Using: amazon-cognito-identity-js, aws-sdk

Previously before (Jan 21, 2022 IST), when we signed in using one client app and then used the refresh token api to refresh the access token by passing another client app Id we were getting the error **NotAuthorizedException: Invalid Refresh Token**. 

But since Jan 21, 2022 IST we are receiving a different error for the same scenario - **NotAuthorizedException: Refresh Token has different Client**.

I also tried with an updated amazon-cognito-identity-js library but the issue persists.

### Expected behavior

When we signed in using one client app and then used the refresh token api to refresh the access token by passing another client app Id we should be getting the error **NotAuthorizedException: Invalid Refresh Token**. 

### Reproduction steps

Let us consider a userPoolId -  UserPoolA
and two client app within the userpool -  clientApp1 and clientApp2.

1. Login using **clientApp1**. 
2. Use the refresh token received from step (1) to refresh the access token but this time pass the clientId as **clientApp2**

Initial Error Message: **NotAuthorizedException: Invalid Refresh Token** (Expected)
New Errror Message: **NotAuthorizedException: Refresh Token has different Client** (Unexpected, happening since January 21, 2022 IST)

### Code Snippet

```javascript
// Put your code below this line.

// Let us consider a userPoolId -  UserPoolA
// and two client app -  clientApp1 and clientApp2.

const AmazonCognitoIdentity = require('amazon-cognito-identity-js');
const { CognitoUserPool } = AmazonCognitoIdentity;
const aws = require('aws-sdk');
const cognitoidentityserviceprovider = new aws.CognitoIdentityServiceProvider();

// For logging in: 
const params = {
          AuthFlow: "ADMIN_NO_SRP_AUTH"
          ClientId: **clientApp1**
          UserPoolId: **UserPoolA**
          AuthParameters: {
            USERNAME: username,
            PASSWORD: password
          }
        }
        cognitoidentityserviceprovider.adminInitiateAuth(params, function (err, data) { }

// For refreshing the token: 

const params = {
    AuthFlow: 'REFRESH_TOKEN_AUTH',
    ClientId: **clientApp2** ,
    UserPoolId: **UserPoolA**
    AuthParameters: {
      REFRESH_TOKEN: **refreshToken received from step 1 Login.**
    }
  }
  cognitoidentityserviceprovider.adminInitiateAuth(params, function (err, data) { }
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by Suvab-rently** [comment]
I think this issue can be better debugged from aws-sdk side: https://github.com/aws/aws-sdk-js/issues/4016

**Comment by chrisbonifacio** [comment]
closing this one as a duplicate, if the response from the server has changed it's probably not something that can be addressed by the js client
