### ISSUE TITLE
Issue to query model with @hasMany relationship using DataStore

### ISSUE THREAD

**Issue by svidgen** [aws-amplify/amplify-js#9514]
### Discussed in https://github.com/aws-amplify/amplify-js/discussions/9499

<div type='discussions-op-text'>

<sup>Originally posted by **duranmla** January 20, 2022</sup>
👋 Hi!

I am having issues with **`@hasMany`** relation. I am trying to access the related model from the source model returns empty. What is odd is that at some point I was able to query without issues since the generated types when `amplify codegen models` run used to contain `pathwayID`, currently, when I generate models the property `pathwayID` is removed.

The case of study looks like below, I have this schema:

```graphql
type Pathway @model @auth(rules: [{ allow: private }]) {
  id: ID!
  title: String!
  description: String
  thumbnail: String
  pathwayPitstops: [PathwayPitstop] @hasMany(indexName: "byPathway", fields: ["id"])
}

type PathwayPitstop @model @auth(rules: [{ allow: private }]) {
  id: ID!
  pathwayID: ID! @index(name: "byPathway")
  pathway: Pathway @belongsTo(fields: ["pathwayID"])
  pitstopID: ID!
  pitstop: Pitstop @hasOne(fields: ["pitstopID"])
  positionX: Int!
  positionY: Int!
  pathwayPitstopParentID: ID
}
```

And then this are the approaches I have done to query:

1. **Trying to get the pathwayPitstops using the source model and then accessing to the related model using the property**
```ts
const pathwayPitstops = (await DataStore.query(Pathway, pathwayId))
      ?.pathwayPitstops
```
*Always return undefined*

2. **Trying to query all the pathwayPitstops and filter by `pathwayID`** (this used to work but since I don't have pathwayID anymore it does not.)

```ts
const pathwayPitstops = await DataStore.query(PathwayPitstop, (pp) => pp.pathwayID('eq', pathwayId))
```
*It complains that pathwayID is not a property* (at some point it was valid but now when I run `amplify codegen models` it deletes the pathwayID from the types)

**And yes, I do have a record that suppose to be returned**
[Screenshot to DynamoDB](https://user-images.githubusercontent.com/1425162/150333471-52d77710-e694-4538-9843-bd20ef35f70c.png)</div>

**Comment by svidgen** [comment]
Tracked on the codegen side here: https://github.com/aws-amplify/amplify-codegen/issues/349

**Comment by david-mcafee** [comment]
@svidgen / @duranmla - Looks like https://github.com/aws-amplify/amplify-codegen/pull/427 has been merged. I just tested this with the following test code, and things are working as expected:

```typescript
import "./App.css";
import { DataStore } from "aws-amplify";
import { Pathway, PathwayPitstop } from "./models";

function App() {
  const test = async () => {
    const pathway = await DataStore.save(
      new Pathway({
        title: `Pathway title ${Date.now()}`,
        description: "Pathway Description",
        thumbnail: "thumbnail",
      })
    );

    console.log("pathway:", pathway);

    let pathwayPitstop;

    // If using TypeScript, check that the pathway is not `undefined`
    if (pathway) {
      pathwayPitstop = await DataStore.save(
        new PathwayPitstop({
          pathwayID: pathway.id,
          positionX: 100,
          positionY: 100,
        })
      );
    }

    console.log("pathwayPitstop:", pathwayPitstop);

    const queriedPathway = await DataStore.query(Pathway, pathway.id);

    // If using TypeScript, check that the queriedPathway is not `undefined`
    if (queriedPathway) {
      const pathwayPitstops = await queriedPathway.pathwayPitstops.toArray();
      console.log("pathwayPitstops", pathwayPitstops);
    }
  };

  return (
    <div className="App">
      <header className="App-header">
        <button onClick={test}>Create Records + Query</button>
      </header>
    </div>
  );
}

export default App;
```

Closing this ticket since this issue has been remediated. @duranmla - if you are still running into issues, please don't hesitate to re-open the ticket. Thanks!
