### ISSUE TITLE
Not Authorized to access OBJECT on type Query

### ISSUE THREAD

**Issue by rudyhadoux** [aws-amplify/amplify-js#9524]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

Authentication, GraphQL API, Storage

### Amplify Categories

auth, api

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

Hi,

I have an ENTERPRISE object with @auth(rules: [{ allow: owner }]).
When an enterprise signs in, if an object Enterprise with the primary key enterprise_email does not exist, I create it.
But I have an error =>
Not Authorized to access getEntreprise on type Query.

Is it right to be not authorized for a GET request ? Even if the object does not exist. 

### Expected behavior

The request for getEntreprise( email ) should be authorized.

### Reproduction steps

Yes.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
the auth rule you're using only allows the owner of a record to perform any queries/mutations. In order for an authenticated user to be able to search records that may or may not belong to them, you'll have to set an auth rule that allows the user to at least read.

example:

```graphql
@auth(rules: [
    { allow: owner }
    { allow: private, operations: [read] }
])
```
note: `private` in this instance assumes the authenticated user belongs to a Cognito User Pool.

**Comment by rudyhadoux** [comment]
Ok thanks.
I set the authorization mode to 'API KEY' too, and I think it is 'AMAZON COGNITO' instead.

**Comment by chrisbonifacio** [comment]
oh, if the auth mode of the api call is API_KEY, then yes it would return unauthorized with your current auth rules and the example I provided. The call would have to be made when the user is logged out and the auth rules would have to contain `{ allow: public, operations: [read] }`

For more information and examples: https://docs.amplify.aws/cli/graphql/authorization-rules/

**Comment by rudyhadoux** [comment]
I have the answer. It was only the authorization mode. No need to add { allow: private, operations: [read] }.

**Comment by chrisbonifacio** [comment]
Just to confirm, did you change the auth mode of the api call to API_KEY? If so, do you also happen to have this line in your schema?

```graphql
input AMPLIFY {
  globalAuthRule: AuthRule = { allow: public }
} # FOR TESTING ONLY!
```

**Comment by rudyhadoux** [comment]
No. I am in production mode like.
