### ISSUE TITLE
Changed my data model, associated DynamoDB table did not updated. All datastore queries don't work, but I don't get any log information

### ISSUE THREAD

**Issue by Parth220** [aws-amplify/amplify-js#9552]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

DataStore

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line

 System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
    Memory: 18.77 GB / 24.97 GB
    Container: Yes
    Shell: 5.8 - /home/linuxbrew/.linuxbrew/bin/zsh
  Binaries:
    Node: 17.0.1 - /home/linuxbrew/.linuxbrew/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.3.0 - /home/linuxbrew/.linuxbrew/bin/npm
  npmPackages:
    @babel/core: ^7.12.9 => 7.16.0
    @expo/vector-icons: ^12.0.0 => 12.0.5
    @fortawesome/fontawesome-svg-core: ^1.2.36 => 1.2.36
    @fortawesome/free-brands-svg-icons: ^5.15.4 => 5.15.4
    @fortawesome/free-regular-svg-icons: ^5.15.4 => 5.15.4
    @fortawesome/free-solid-svg-icons: ^5.15.4 => 5.15.4
    @fortawesome/react-native-fontawesome: ^0.2.7 => 0.2.7
    @react-native-async-storage/async-storage: ~1.15.0 => 1.15.14
    @react-native-community/netinfo: 6.0.2 => 6.0.2
    @react-native-community/picker: ^1.8.1 => 1.8.1
    @react-native-picker/picker: 2.1.0 => 2.1.0
    @react-navigation/bottom-tabs: ^5.11.8 => 5.11.15
    @react-navigation/native: ^5.9.3 => 5.9.8 (3.8.4)
    @react-navigation/stack: ^5.14.3 => 5.14.9
    @types/react: ~17.0.21 => 17.0.37
    @types/react-dom: ~17.0.9 => 17.0.11
    @types/react-native: ~0.64.12 => 0.64.19 (0.65.16)
    @types/styled-components: ^5.1.17 => 5.1.17
    @types/styled-components-react-native: ^5.1.3 => 5.1.3
    @typescript-eslint/eslint-plugin: ^5.7.0 => 5.7.0
    @typescript-eslint/parser: ^5.7.0 => 5.7.0
    HelloWorld:  0.0.1
    aws-amplify: ^4.3.6 => 4.3.10
    aws-amplify-react-native: ^6.0.1 => 6.0.1
    eslint: ^8.4.1 => 8.4.1
    eslint-config-prettier: ^8.3.0 => 8.3.0
    eslint-plugin-jsx-a11y: ^6.5.1 => 6.5.1
    eslint-plugin-react: ^7.27.1 => 7.27.1
    eslint-plugin-react-hooks: ^4.3.0 => 4.3.0
    eslint-plugin-simple-import-sort: ^7.0.0 => 7.0.0
    expo: ~43.0.3 => 43.0.4
    expo-linking: ~2.4.2 => 2.4.2
    expo-location: ~13.0.4 => 13.0.4
    expo-status-bar: ~1.1.0 => 1.1.0
    hermes-inspector-msggen:  1.0.0
    prettier: ^2.2.1 => 2.5.1 (2.3.2, 1.19.1)
    react: 17.0.1 => 17.0.1 (17.0.2)
    react-dom: 17.0.1 => 17.0.1 (17.0.2)
    react-native: 0.64.3 => 0.64.3
    react-native-card-stack-swiper: ^1.2.5 => 1.2.5
    react-native-gesture-handler: ~1.10.2 => 1.10.3
    react-native-safe-area-context: 3.3.2 => 3.3.2
    react-native-screens: ~3.8.0 => 3.8.0
    react-native-svg: ^12.1.1 => 12.1.1
    react-native-web: 0.17.1 => 0.17.1
    react-navigation: ^4.4.4 => 4.4.4
    styled-components: ^5.3.3 => 5.3.3
    styled-components/macro:  undefined ()
    styled-components/native:  undefined ()
    styled-components/primitives:  undefined ()
    typescript: ~4.3.5 => 4.3.5 (4.4.4, 3.9.10, 4.2.4)
  npmGlobalPackages:
    @aws-amplify/cli: 7.6.15
    expo-cli: 5.0.3
    npm: 8.3.0
    react-native-cli: 2.0.1
    typescript: 4.5.3
```

</details>

### Describe the bug

I updated an existing data model using the Amplify Studio UI. I added 4 optional fields string fields and 2 required ones. 

My project is relatively small so prior to deploying the data model changes, I deleted all of my table data using the content tab in Studio/AdminUI. Then I deployed the data model changes. 

These changes don't reflect to the corresponding DynamoDB table and the deletion also did not persist to the database. 

When I use my application, none of my queries return. They are stuck infinitely running. 

I logged my app using 
`import { Logger } from 'aws-amplify'
Logger.LOG_LEVEL = 'DEBUG'
`

And the last output is :
> [DEBUG] 56:47.607 DataStore - Starting DataStore ConsoleLogger.js:127 
> [DEBUG] 56:47.607 DataStore - Starting Storage

Then it just stays stuck here.

Really unsure why my amplify is in this state. 

### Expected behavior

I expected to run the deletion of entries in the table I was working with, then update the data model for that model. 
I expected that the related DynamoDB databases updated to reflect the data model change deployment. 

Also expected that the Datastore queries would return something or log out a warning if something was wrong, instead the queries are stuck loading.

### Reproduction steps

I updated an existing data model using the Amplify Studio UI. I added 4 optional fields string fields and 2 required ones. 

My project is relatively small so prior to deploying the data model changes, I deleted all of my table data using the content tab in Studio/AdminUI. Then I deployed the data model changes. 

### Log output

<details>

```
// Put your logs below this line

And the last output is :
> [DEBUG] 56:47.607 DataStore - Starting DataStore ConsoleLogger.js:127 
> [DEBUG] 56:47.607 DataStore - Starting Storage

Then it just stays stuck here.

Really unsure why my amplify is in this state. 

```

</details>

### aws-exports.js

```
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:19564f03-e3d3-4497-92ee-b13db7cc0304",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_kNuc9mqbb",
    "aws_user_pools_web_client_id": "48vj95813li697q9apmsekvtm7",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "ON",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "PHONE_NUMBER"
    ],
    "aws_appsync_graphqlEndpoint": "https://6aelg75iorbijdt3r47h4haavy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ekg3rjs3ergl3dowt33sabpycu"
};


export default awsmobile;

```

**Comment by chrisbonifacio** [comment]
Hi @Parth220 👋 Can you try updating your `aws-amplify` package to the latest version? (4.3.14 at the time of this comment)

Let me know if that helps with the DataStore sync on your app.

Also, are there any errors in your Network Activity tab while this is happening?

**Comment by Parth220** [comment]
Thank you so much, not sure how my package version # ended up being 4.3.6, but when I changed it 4.3.14, it worked.

**Comment by chrisbonifacio** [comment]
No problem! Glad that worked 😄

**Comment by Parth220** [comment]
So the thing is, this issue has happened to me almost every time I deploy model changes from Amplify Studio. 

It just happened to me again when I simply added another field to a model.  No issues on the network tab. My queries are not showing up on the request tab, and my console outputs the following when `Logger.LOG_LEVEL = 'DEBUG'` : 

```
[DEBUG] 10:30.178 DataStore - Starting DataStore
[DEBUG] 10:30.179 DataStore - Starting Storage
```

Just gets stuck here.


In the past, failure to load queries after model updates takes like an hour of time to pass before my queries work again. Is this normal? 

Would really appreciate any help you can offer, as it's really hurts my flow when I'm stuck in this limbo state after every schema update.

**Comment by Parth220** [comment]
I dug a little more and it seems like my AppSync queries have updated, but it's corresponding DynamoDB database has not updated with my new field. `Match-ye5u2nlzi5dcbghcgjboe5ksma-staging`

Is this normal? Do I just have to wait until all of the updates propagate through to the different services?

**Comment by Parth220** [comment]
Magically, it has started working a day later, without any changes. What is the reason for this?
