### ISSUE TITLE
Calling Auth.signUp from an Angular Package Format Library produces type error?

### ISSUE THREAD

**Issue by fireflysemantics** [aws-amplify/amplify-js#9555]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

^CTemp/tsamplifylibdemoapp $ npx envinfo --system --binaries --browsers --npmPackages --duplicates --npmGlobalPackages

  System:
    OS: macOS 12.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 556.92 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 96.0.3
    Safari: 15.2
  npmPackages:
    @angular-devkit/build-angular: ~13.0.3 => 13.0.4 
    @angular/animations: ~13.0.0 => 13.0.3 
    @angular/animations/browser:  undefined ()
    @angular/animations/browser/testing:  undefined ()
    @angular/cli: ~13.0.3 => 13.0.4 
    @angular/common: ~13.0.0 => 13.0.3 
    @angular/common/http:  undefined ()
    @angular/common/http/testing:  undefined ()
    @angular/common/testing:  undefined ()
    @angular/common/upgrade:  undefined ()
    @angular/compiler: ~13.0.0 => 13.0.3 
    @angular/compiler-cli: ~13.0.0 => 13.0.3 
    @angular/compiler/testing:  undefined ()
    @angular/core: ~13.0.0 => 13.0.3 
    @angular/core/testing:  undefined ()
    @angular/forms: ~13.0.0 => 13.0.3 
    @angular/platform-browser: ~13.0.0 => 13.0.3 
    @angular/platform-browser-dynamic: ~13.0.0 => 13.0.3 
    @angular/platform-browser-dynamic/testing:  undefined ()
    @angular/platform-browser/animations:  undefined ()
    @angular/platform-browser/testing:  undefined ()
    @angular/router: ~13.0.0 => 13.0.3 
    @angular/router/testing:  undefined ()
    @angular/router/upgrade:  undefined ()
    @types/jasmine: ~3.10.0 => 3.10.3 
    @types/node: ^12.11.1 => 12.20.43 
    amplifylibe: ^0.0.1 => 0.0.1 
    jasmine-core: ~3.10.0 => 3.10.1 
    karma: ~6.3.0 => 6.3.13 
    karma-chrome-launcher: ~3.1.0 => 3.1.0 
    karma-coverage: ~2.0.3 => 2.0.3 
    karma-coverage-coffee-example:  1.0.0 
    karma-jasmine: ~4.0.0 => 4.0.1 
    karma-jasmine-html-reporter: ~1.7.0 => 1.7.0 
    rxjs: ~7.4.0 => 7.4.0 (6.6.7)
    rxjs/ajax:  undefined ()
    rxjs/fetch:  undefined ()
    rxjs/internal-compatibility:  undefined ()
    rxjs/operators:  undefined ()
    rxjs/testing:  undefined ()
    rxjs/webSocket:  undefined ()
    tslib: ^2.3.0 => 2.3.1 (1.14.1, 2.1.0)
    typescript: ~4.4.3 => 4.4.4 
    zone-mix:  undefined ()
    zone-node:  undefined ()
    zone-testing:  undefined ()
    zone.js: ~0.11.4 => 0.11.4 
    zone.js/async-test:  undefined ()
    zone.js/async-test.min:  undefined ()
    zone.js/fake-async-test:  undefined ()
    zone.js/fake-async-test.min:  undefined ()
    zone.js/jasmine-patch:  undefined ()
    zone.js/jasmine-patch.min:  undefined ()
    zone.js/long-stack-trace-zone:  undefined ()
    zone.js/long-stack-trace-zone.min:  undefined ()
    zone.js/mocha-patch:  undefined ()
    zone.js/mocha-patch.min:  undefined ()
    zone.js/proxy:  undefined ()
    zone.js/proxy.min:  undefined ()
    zone.js/sync-test:  undefined ()
    zone.js/sync-test.min:  undefined ()
    zone.js/task-tracking:  undefined ()
    zone.js/task-tracking.min:  undefined ()
    zone.js/webapis-media-query:  undefined ()
    zone.js/webapis-media-query.min:  undefined ()
    zone.js/webapis-notification:  undefined ()
    zone.js/webapis-notification.min:  undefined ()
    zone.js/webapis-rtc-peer-connection:  undefined ()
    zone.js/webapis-rtc-peer-connection.min:  undefined ()
    zone.js/webapis-shadydom:  undefined ()
    zone.js/webapis-shadydom.min:  undefined ()
    zone.js/wtf:  undefined ()
    zone.js/wtf.min:  undefined ()
    zone.js/zone-bluebird:  undefined ()
    zone.js/zone-bluebird.min:  undefined ()
    zone.js/zone-error:  undefined ()
    zone.js/zone-error.min:  undefined ()
    zone.js/zone-legacy:  undefined ()
    zone.js/zone-legacy.min:  undefined ()
    zone.js/zone-patch-canvas:  undefined ()
    zone.js/zone-patch-canvas.min:  undefined ()
    zone.js/zone-patch-cordova:  undefined ()
    zone.js/zone-patch-cordova.min:  undefined ()
    zone.js/zone-patch-electron:  undefined ()
    zone.js/zone-patch-electron.min:  undefined ()
    zone.js/zone-patch-fetch:  undefined ()
    zone.js/zone-patch-fetch.min:  undefined ()
    zone.js/zone-patch-jsonp:  undefined ()
    zone.js/zone-patch-jsonp.min:  undefined ()
    zone.js/zone-patch-message-port:  undefined ()
    zone.js/zone-patch-message-port.min:  undefined ()
    zone.js/zone-patch-promise-test:  undefined ()
    zone.js/zone-patch-promise-test.min:  undefined ()
    zone.js/zone-patch-resize-observer:  undefined ()
    zone.js/zone-patch-resize-observer.min:  undefined ()
    zone.js/zone-patch-rxjs:  undefined ()
    zone.js/zone-patch-rxjs-fake-async:  undefined ()
    zone.js/zone-patch-rxjs-fake-async.min:  undefined ()
    zone.js/zone-patch-rxjs.min:  undefined ()
    zone.js/zone-patch-socket-io:  undefined ()
    zone.js/zone-patch-socket-io.min:  undefined ()
    zone.js/zone-patch-user-media:  undefined ()
    zone.js/zone-patch-user-media.min:  undefined ()
  npmGlobalPackages:
    @angular/cli: 13.0.3
    @aws-amplify/cli: 7.5.1
    @fireflysemantics/fsd-cli: 1.0.124
    @jsdevtools/version-bump-prompt: 6.1.0
    @superflycss/cli: 4.2.00
    corepack: 0.10.0
    del-cli: 4.0.1
    npm-check-updates: 12.0.2
    npm-install-peers: 1.2.2
    npm: 8.1.0
    verdaccio: 5.2.2

</details>

### Describe the bug

I wrote it up here on SO and provided demo projects:

https://stackoverflow.com/questions/70993171/calling-auth-signup-from-an-angular-package-format-library-produces-type-error

### Expected behavior

I wrote it up here on SO and provided demo projects:

https://stackoverflow.com/questions/70993171/calling-auth-signup-from-an-angular-package-format-library-produces-type-error

### Reproduction steps

I wrote it up here on SO and provided demo projects:

https://stackoverflow.com/questions/70993171/calling-auth-signup-from-an-angular-package-format-library-produces-type-error

### Code Snippet

I wrote it up here on SO and provided demo projects:

https://stackoverflow.com/questions/70993171/calling-auth-signup-from-an-angular-package-format-library-produces-type-error

### Log output

I wrote it up here on SO and provided demo projects:

https://stackoverflow.com/questions/70993171/calling-auth-signup-from-an-angular-package-format-library-produces-type-error

**Comment by tannerabread** [comment]
Hi @fireflysemantics do I understand your SO post correctly that this was more of a blocker with the library `amplifylibe` you were building not being able to get amplify's types at compile time, and not with amplify itself?

I see that you were using `currentAuthenticatedUser` which does return the type `Promise<CognitoUser | any>`

And if that's the case, is this still an issue with amplify that needs to be open?

**Comment by tannerabread** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and are in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
