### ISSUE TITLE
DataStore observeQuery function not behaving as expected on update

### ISSUE THREAD

**Issue by alharris-at** [aws-amplify/amplify-js#9556]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

DataStore

### Amplify Categories

Not applicable

### Environment information

<details>

```
  System:
    OS: macOS 11.6.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 4.42 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.7.0 - ~/.nvm/versions/node/v16.7.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 7.20.3 - ~/.nvm/versions/node/v16.7.0/bin/npm
    Watchman: 2022.01.31.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 91.5.1
    Safari: 15.3
  npmPackages:
    @testing-library/jest-dom: ^5.16.2 => 5.16.2 
    @testing-library/react: ^12.1.2 => 12.1.2 
    @testing-library/user-event: ^13.5.0 => 13.5.0 
    aws-amplify: ^4.3.14 => 4.3.14 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    react-scripts: 5.0.0 => 5.0.0 
    web-vitals: ^2.1.4 => 2.1.4 
  npmGlobalPackages:
    @aws-amplify/cli: 7.6.9
    npm: 7.20.3
    typescript: 4.5.2
```

</details>

### Describe the bug

When using observeQuery, it appears on local element update, only partial fields from the model are being returned, and the remaining fields are just not propagated through the snapshot callback.

### Expected behavior

I'd expect the full model to be returned, since we return all matching elements from the query as part of the response. I have confirmed that in IndexedDB the full model is updated and appears to be complete.

### Reproduction steps

I created a repo to demo this behavior, you should be able to just pull and verify, but the README.md also includes repro steps.

Repo: https://github.com/alharris-at/observeQueryBugRepro
Commit Adding Repro: https://github.com/alharris-at/observeQueryBugRepro/commit/c330849f0047fc48ac05647f8ba56bdb5761f2b9

### Code Snippet

My repro code has a bunch of test harness config in it, but effectively the functional code is below.

```javascript
import React, { useEffect, useState } from 'react';
import Amplify, { DataStore } from 'aws-amplify';
import { User } from './models'

Amplify.configure({ ...config here });

export default function App() {
  const [idToUpdate, setIdToUpdate] = useState('');
  const [users, setUsers] = useState([]);

  useEffect(() => {
    const initializeAppState = async () => {
      const queriedIdToUpdate = (await DataStore.query(User, (criteria) => criteria.firstName('eq', 'Update')))[0].id;
      setIdToUpdate(queriedIdToUpdate);

      const subscription = DataStore.observeQuery(User).subscribe((snapshot) => setUsers(snapshot.items));

      return () => subscription && subscription.unsubscribe();
    };

    return initializeAppState();
  }, []);

  const updateUser = async () => {
    const original = await DataStore.query(User, idToUpdate);

    await DataStore.save(
      User.copyOf(original, updated => {
        updated.firstName = "I've been updated";
      })
    );  };

  return (
    <div>
      <button onClick={updateUser}>Update User</button>
      <h5>Users</h5>
      <ul>
        {users.map((user)=> {
          return <li key={user.id}>First Name: "{user.firstName}", Last Name: "{user.lastName}"</li>
        })}
      </ul>
    </div>
  );
}
```

### Log output

N/A - not using the CLI to generate this repro.

### aws-exports.js

N/A - I don't have an aws-exports.js file, I'm just testing datastore in isolation.

### Manual configuration

Included the folllowing manual config so datastore will initialize, but we're not communicating w/ a cloud backend.

```json
{
    aws_appsync_graphqlEndpoint: 'https://fake-appsync-endpoint/graphql',
}
```

### Additional configuration

N/A

### Additional information and screenshots

Before Update:

![Screen Shot 2022-02-04 at 3 29 54 PM](https://user-images.githubusercontent.com/91494052/152616691-c4fb9c6c-f0ba-48c4-9553-d8b32533d457.png)

After Update:

![Screen Shot 2022-02-04 at 3 29 58 PM](https://user-images.githubusercontent.com/91494052/152616705-89561eef-b5bb-4355-9bb5-fbd14003c58f.png)

**Comment by Jesmaster** [comment]
I'm having the exact same issue. Using observeQuery creating and deleting work fine but when updating an existing item, the intial local response is not the full Model but an object containing the field that changed along with the id, _version, _lastChangedAt and _deleted but none of the other Model fields. Shortly after the full Model is returned and then shortly after that the full Model is returned again.

Here is a screenshot of me logging the timestamp and items returned from the observeQuery snapshot when modifying the "editable" property from true to false on my Model called "Score". You'll see the first return is not the full Model as expected but only the property that changed along with the other metadata.

![Screenshot at 2022-02-14 18-42-41](https://user-images.githubusercontent.com/1197834/153965815-229a4199-7422-403e-952c-c29ec43bbd68.png)

            const subscription = DataStore.observeQuery(Score).subscribe({
                next: ({items, isSynced}) => {
                    isSynced && console.log(Date.now());
                    isSynced && console.log(items);
                    isSynced && setScores(items);
                }
            });

**Comment by VijiGeo** [comment]
I've been having this issue as well -- is there a temporary workaround until this gets resolved/merged?

**Comment by david-mcafee** [comment]
> I've been having this issue as well -- is there a temporary workaround until this gets resolved/merged?

Hi @VijiGeo! - The PR has been merged, and the fix will go out with next week's release. If you need the fix sooner, you can pull in the latest unstable release, which will include this fix. Thank you!
