### ISSUE TITLE
aws-amplify-vue build fails with recent versions of node

### ISSUE THREAD

**Issue by david-mcafee** [aws-amplify/amplify-js#9559]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Not applicable

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 11.6.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.99 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Brave Browser: 98.1.35.100
    Chrome: 98.0.4758.80
    Edge: 97.0.1072.76
    Firefox: 91.5.0
    Safari: 15.3
  npmGlobalPackages:
    corepack: 0.10.0
    npm: 8.1.2
    yarn: 1.22.17

```

</details>

### Describe the bug

When attempting to run `yarn build` using Node version 17.4.0 (as well as earlier versions of Node 17), I receive the following error:

```
aws-amplify-vue: node:internal/crypto/hash:67
aws-amplify-vue:   this[kHandle] = new _Hash(algorithm, xofLen);
aws-amplify-vue:                   ^
aws-amplify-vue: Error: error:0308010C:digital envelope routines::unsupported
aws-amplify-vue:     at new Hash (node:internal/crypto/hash:67:19)
aws-amplify-vue:     at Object.createHash (node:crypto:135:10)
aws-amplify-vue:     at module.exports (/Volumes/workplace/origin/amplify-js/node_modules/webpack/lib/util/createHash.js:135:53)
aws-amplify-vue:     at NormalModule._initBuildHash (/Volumes/workplace/origin/amplify-js/node_modules/webpack/lib/NormalModule.js:417:16)
aws-amplify-vue:     at handleParseError (/Volumes/workplace/origin/amplify-js/node_modules/webpack/lib/NormalModule.js:471:10)
aws-amplify-vue:     at /Volumes/workplace/origin/amplify-js/node_modules/webpack/lib/NormalModule.js:503:5
aws-amplify-vue:     at /Volumes/workplace/origin/amplify-js/node_modules/webpack/lib/NormalModule.js:358:12
aws-amplify-vue:     at /Volumes/workplace/origin/amplify-js/node_modules/loader-runner/lib/LoaderRunner.js:373:3
aws-amplify-vue:     at iterateNormalLoaders (/Volumes/workplace/origin/amplify-js/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
aws-amplify-vue:     at Array.<anonymous> (/Volumes/workplace/origin/amplify-js/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
aws-amplify-vue:     at Storage.finished (/Volumes/workplace/origin/amplify-js/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
aws-amplify-vue:     at /Volumes/workplace/origin/amplify-js/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
aws-amplify-vue:     at /Volumes/workplace/origin/amplify-js/node_modules/graceful-fs/graceful-fs.js:123:16
aws-amplify-vue:     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
aws-amplify-vue:   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
aws-amplify-vue:   library: 'digital envelope routines',
aws-amplify-vue:   reason: 'unsupported',
aws-amplify-vue:   code: 'ERR_OSSL_EVP_UNSUPPORTED'
aws-amplify-vue: }
aws-amplify-vue: Node.js v17.4.0
aws-amplify-vue: error Command failed with exit code 1.
aws-amplify-vue: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I attempted previous releases of Node 17, but the last supported version appears to be Node v16.13.2 (npm v8.1.2), which is the `lts` version. I realize this *may* be expected, but felt it was worth calling out. If this *is* expected, we should update [our contributing guide](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#setting-up-for-local-development) (i.e. from `You will need the latest version of [Node.js](https://nodejs.org/en/) on your system` to something like `You will need the lts version of Node.js on your system`)

### Expected behavior

I would expect the build to succeed when using recent versions of Node

### Reproduction steps

1. `nvm install 17.4.0`
2. cd `amplify-js`
3. `yarn build`

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

None (attempting to build `amplify-js` locally)

**Comment by nadetastic** [comment]
Closing this out as `aws-amplify-vue` has now been deprecated as of version 5.

https://github.com/aws-amplify/amplify-js/releases/tag/aws-amplify%405.0.0
