### ISSUE TITLE
observeQuery: support id as second parameter

### ISSUE THREAD

**Issue by clintfoster** [aws-amplify/amplify-js#9568]
### Is this related to a new or existing API?

DataStore

### Describe the feature you'd like to request

The DataStore `query` & `observe` APIs allow supplying an id in p2. However, `observeQuery` only supports a filter. I'm wondering if there is a reason for this.

I have a page where I only need to load one item and observe subsequent changes. I could do this with a filter in p2, but the table can contain millions of items.

### Describe the solution you'd like

Allow p2 to be a simple id (like `query` & `observe`).

### Describe alternatives you've considered

Calling `query` and `observe` separately instead of using `observeQuery`.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by chrisbonifacio** [comment]
Very late to this issue but I'm curious if you only need real time updates for one record, does `DataStore.observe(Post, id).subscribe()` not fulfill this use case?

**Comment by clintfoster** [comment]
Closing since we're no longer using DataStore, and I'm no longer intimate enough with the API to provide feedback. Thanks for looking at this.
