### ISSUE TITLE
Response data was mutated by API.get method?

### ISSUE THREAD

**Issue by matsuo-ts** [aws-amplify/amplify-js#961]
> Do you want to request a feature or report a bug?

Probably it's a bug.

> What is the current behavior?

I send a GET request to API Gateway by below code.

```javascript
export const apiPost = (apiName, path = '', options = {}) => {
  return API.post(apiName, path, { ...API_INIT, ...options })
    .then(data => {
      console.log(data) // DATA_1
      return data
    })
};
```

then `DATA_1` is looks like.
![screen shot 2018-06-01 at 12 38 41](https://user-images.githubusercontent.com/25472199/40819978-c61a54e2-6598-11e8-8d11-26fca192534a.png)

But expected data to be like this as I see in `Network` tab of chrome dev tool.
![screen shot 2018-06-01 at 12 39 52](https://user-images.githubusercontent.com/25472199/40820007-ef752e20-6598-11e8-93be-38650b1e507a.png)

Somehow the order of array has been changed before we see in our code.
Could you guys please provide a solution how can I avoid this?

```javascript
// Node.js version 
8.9.0

// NPM version
5.5.1

// npm modules
{
"dependencies": {
    "aws-amplify": "^0.3.3",
    "babel-core": "^6.25.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-polyfill": "^6.23.0",
    "i18next": "^10.0.3",
    "linkstate": "^1.1.0",
    "lodash.set": "^4.3.2",
    "money": "^0.2.0",
    "preact": "^8.2.5",
    "preact-redux": "^2.0.3",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0",
    "whatwg-fetch": "^2.0.3"
  },
  "devDependencies": {
    "babel-cli": "^6.24.0",
    "babel-jest": "^21.2.0",
    "babel-preset-es2015": "^6.24.0",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "babelify": "^7.3.0",
    "browser-sync": "^2.24.1",
    "browserify": "^14.4.0",
    "dotenv": "^4.0.0",
    "envify": "^4.1.0",
    "gulp": "^4.0.0",
    "gulp-buffer": "0.0.2",
    "gulp-clean-css": "^3.9.0",
    "gulp-replace": "^0.6.1",
    "gulp-sourcemaps": "^2.6.4",
    "gulp-tap": "^1.0.1",
    "gulp-uglify": "^3.0.0",
    "gulplog": "^1.0.0",
    "jest": "^21.2.1",
    "jest-serializer-html-string": "^1.0.1",
    "preact-render-to-string": "^3.7.0",
    "react-test-renderer": "^16.1.1",
    "redux-mock-store": "^1.3.0"
  }
}

// Browser
Chrome  66.0.3359.181

// OS
Mac 10.13.4
```

**Comment by jordanranz** [comment]
Hi matsuo-ts, thanks for submitting this issue.

To clarify, you see the response array ordered in the network tab but when console logging DATA_1 it is unordered. Am I understanding the issue correctly?

Have you tried this using a different browser?

**Comment by jordanranz** [comment]
Going to close this due to inactivity. Please reopen if you are still experiencing this issue.
