### ISSUE TITLE
SSR Auth does not work with Restricted Access

### ISSUE THREAD

**Issue by kolodi** [aws-amplify/amplify-js#9613]
### Before opening, please confirm:

- [x] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 4.39 GB / 12.31 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 17.3.1 - ~/.nvm/versions/node/v17.3.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v17.3.1/bin/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v17.3.1/bin/npm
  npmPackages:
    @ampproject/toolbox-optimizer:  undefined ()
    @aws-amplify/ui-react: ^2.4.0 => 2.4.0 
    @aws-amplify/ui-react-internal:  undefined ()
    @aws-amplify/ui-react-legacy:  undefined ()
    @babel/core:  undefined ()
    @babel/runtime:  7.15.4 
    @fontsource/inter: ^4.5.4 => 4.5.4 
    @hapi/accept:  undefined ()
    @headlessui/react: ^1.4.3 => 1.4.3 
    @heroicons/react: ^1.0.5 => 1.0.5 
    @napi-rs/triples:  undefined ()
    @next/react-dev-overlay:  undefined ()
    @next/react-refresh-utils:  12.0.10 
    @peculiar/webcrypto:  undefined ()
    @types/node: 17.0.17 => 17.0.17 
    @types/react: 17.0.39 => 17.0.39 
    @types/three: ^0.137.0 => 0.137.0 
    @vercel/nft:  undefined ()
    abort-controller:  undefined ()
    acorn:  undefined ()
    amphtml-validator:  undefined ()
    arg:  undefined ()
    assert:  undefined ()
    async-retry:  undefined ()
    async-sema:  undefined ()
    autoprefixer: ^10.4.2 => 10.4.2 
    aws-amplify: ^4.3.14 => 4.3.14 
    babel-packages:  undefined ()
    browserify-zlib:  undefined ()
    browserslist:  undefined ()
    buffer:  undefined ()
    chalk:  undefined ()
    ci-info:  undefined ()
    cli-select:  undefined ()
    comment-json:  undefined ()
    compression:  undefined ()
    conf:  undefined ()
    constants-browserify:  undefined ()
    content-disposition:  undefined ()
    content-type:  undefined ()
    cookie:  undefined ()
    cross-spawn:  undefined ()
    crypto-browserify:  undefined ()
    cssnano-simple:  undefined ()
    debug:  undefined ()
    devalue:  undefined ()
    domain-browser:  undefined ()
    eslint: 8.8.0 => 8.8.0 
    eslint-config-next: 12.0.10 => 12.0.10 
    etag:  undefined ()
    events:  undefined ()
    find-cache-dir:  undefined ()
    find-up:  undefined ()
    formdata-node:  undefined ()
    fresh:  undefined ()
    get-orientation:  undefined ()
    glob:  undefined ()
    gzip-size:  undefined ()
    http-proxy:  undefined ()
    https-browserify:  undefined ()
    icss-utils:  undefined ()
    ignore-loader:  undefined ()
    image-size:  undefined ()
    is-animated:  undefined ()
    is-docker:  undefined ()
    is-wsl:  undefined ()
    jest-worker:  undefined ()
    json5:  undefined ()
    jsonwebtoken:  undefined ()
    loader-utils:  undefined ()
    lodash.curry:  undefined ()
    lru-cache:  undefined ()
    micromatch:  undefined ()
    mini-css-extract-plugin:  undefined ()
    nanoid:  undefined ()
    native-url:  undefined ()
    neo-async:  undefined ()
    next: 12.0.10 => 12.0.10 
    next-auth: ^4.2.1 => 4.2.1 
    node-fetch:  undefined ()
    node-html-parser:  undefined ()
    ora:  undefined ()
    os-browserify:  undefined ()
    p-limit:  undefined ()
    path-browserify:  undefined ()
    postcss: ^8.4.6 => 8.4.6 (8.4.5)
    postcss-flexbugs-fixes:  undefined ()
    postcss-modules-extract-imports:  undefined ()
    postcss-modules-local-by-default:  undefined ()
    postcss-modules-scope:  undefined ()
    postcss-modules-values:  undefined ()
    postcss-preset-env:  undefined ()
    postcss-safe-parser:  undefined ()
    postcss-scss:  undefined ()
    postcss-value-parser:  undefined ()
    process:  undefined ()
    punycode:  undefined ()
    querystring-es3:  undefined ()
    raw-body:  undefined ()
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    react-is:  17.0.2 
    react-refresh:  0.8.3 
    react-server-dom-webpack:  undefined ()
    regenerator-runtime:  0.13.4 
    sass-loader:  undefined ()
    schema-utils:  undefined ()
    semver:  undefined ()
    send:  undefined ()
    setimmediate:  undefined ()
    source-map:  undefined ()
    stream-browserify:  undefined ()
    stream-http:  undefined ()
    string-hash:  undefined ()
    string_decoder:  undefined ()
    strip-ansi:  undefined ()
    tailwindcss: ^3.0.22 => 3.0.22 
    terser:  undefined ()
    text-table:  undefined ()
    three: ^0.137.5 => 0.137.5 
    timers-browserify:  undefined ()
    tty-browserify:  undefined ()
    typescript: 4.5.5 => 4.5.5 
    ua-parser-js:  undefined ()
    unistore:  undefined ()
    util:  undefined ()
    uuid:  undefined ()
    vm-browserify:  undefined ()
    watchpack:  undefined ()
    web-streams-polyfill:  undefined ()
    web-vitals:  undefined ()
    webpack:  undefined ()
    webpack-sources:  undefined ()
    ws:  undefined ()
    zustand: ^3.7.0 => 3.7.0 
  npmGlobalPackages:
    @aws-amplify/cli: 7.6.19
    corepack: 0.10.0
    npm: 8.3.0
    react-native-cli: 2.0.1
    yarn: 1.22.17

```

</details>

### Describe the bug

I want to restrict access to a page on server side.
I have this page

```ts
import { withSSRContext } from "aws-amplify";
import { NextPage, GetServerSidePropsContext } from "next";
import { CognitoUserInterface } from "@aws-amplify/ui-components";

const Protected: NextPage = (props) => {
    const { email } = props as any;
    return (
        <p>Logged In As {email}</p>
    );
};

export const getServerSideProps = async (context: GetServerSidePropsContext) => {
    const { req, res } = context;
    const { Auth } = withSSRContext({ req });
    try {
        const user = (await Auth.currentAuthenticatedUser() as CognitoUserInterface);
        return {
            props: {
                authenticated: true,
                email: user.attributes?.email,
            },
        };
    } catch (err) {
        res.writeHead(302, { Location: "/profile" });
        res.end();
    }
    return { props: { authenticated: false, email: null } };
};

export default Protected;
```
All works well on production deployment, you can navigate to this page after login and so you get the authenticated user in SSR. However, it does not work on another deployment from different git branch (same identical code and build settings) which has restricted access feature enabled (the page asks you to login with another pair of credentials). I have tested and SSR works well but it fails to get the authenticated user. When restricted access is disabled on DEV deployment, it all works.

### Expected behavior

Getting authenticated user on Server Side should work together with restricted access feature.

### Reproduction steps

1. Create a default nextjs app with SSR enabled
2. Create a page as in description where user is checked on server side
3. Deploy to Amplify
4. Enable restricted access 
5. Go to deployed page and you will be redirected to /profile page because getting auth use fails

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @kolodi 👋 Thanks for raising this issue.

The Restrict Access feature in the console is meant to protect feature branches from being publicly viewable.

https://docs.aws.amazon.com/amplify/latest/userguide/access-control.html

Is that what you intend to do?

If so, are you expecting the username/password to be considered an authenticated by Amplify afterwards?

**Comment by kolodi** [comment]
> If so, are you expecting the username/password to be considered an authenticated by Amplify afterwards?

There are both. You enter the restricted access credentials to access the website. Then you can login with cognito username and password on separate page. As you can see in code I posted, it is getting the authenticated cognito user on the server side. It works well if no restricted access is enabled. I have tested with and without restricted access.

**Comment by chrisbonifacio** [comment]
@kolodi sorry for the delay. Unfortunately, I haven't been able to reproduce this behavior. After signing in with username/password, I'm able to use authenticate with Amplify.

https://dev.d1r5f8sb1v1qe2.amplifyapp.com/

Can you add this line where you are configuring Amplify and share the console logs from the restricted access environment?

```js
Amplify.Logger.LOG_LEVEL = "DEBUG";
```

**Comment by kolodi** [comment]
> @kolodi sorry for the delay. Unfortunately, I haven't been able to reproduce this behavior. After signing in with username/password, I'm still able to authenticate with Amplify.

I am able to authenticate as well. The problem is then in another page where I am trying to get user on server side. See the code within `getServerSideProps()`.

> Can you add this line where you are configuring Amplify and share the console logs from the restricted access environment?
> 
> ```js
> Amplify.Logger.LOG_LEVEL = "DEBUG";
> ```

Where I can see log messages on the server side?

**Comment by chrisbonifacio** [comment]
@kolodi sorry for the delay. You should be able to see the logs in your terminal when developing locally.

**Comment by chrisbonifacio** [comment]
@kolodi just out of curiosity, would you happen to be signing in with a social provider like Google? Or only as a Cognito User?

**Comment by kolodi** [comment]
> @kolodi sorry for the delay. You should be able to see the logs on the server side in your terminal when developing locally. I would also check the context in `getServerSideProps` to make sure credentials are being sent along with the request in the cookies.
> 
> Can you share how you're configuring Amplify and make sure that you are setting `ssr` to `true?`
> 
> example:
> 
> ```js
> import { Amplify } from "aws-amplify"
> import aws_config from "../src/aws-exports.js"
> 
> Amplify.configure({
> ...aws_config,
> ssr: true,
> })
> ```

Yes, I set SSR to true in Amplify configuration.



> @kolodi just out of curiosity, would you happen to be signing in with a social provider like Google? Or only as a Cognito User?

No, it is a simple Cognito user. 


When testing locally `Auth.currentAuthenticatedUser()` works fine on Server Side. The session is working correctly. In production it is working as well (main branch). On the second branch deployment (dev) everything was exactly the same except the additional restricted access turned on. For some reason, the  `Auth.currentAuthenticatedUser()` fails to obtain the authenticated user. I've tried to pass all possible data from `getServerSideProps` to the client side page and it all works fine, so it is only the getting user that is failing.  I'm not sure how to debug it properly.

**Comment by chrisbonifacio** [comment]
@kolodi would it be possible to share your repo/app with the `amplify` folder so that I can recreate the backend and use the same logic. This would hopefully allow me to consistently reproduce the behavior you're seeing.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!

**Comment by Davidrl1000** [comment]
@chrisbonifacio I'm getting the same error.

**Some of my libraries**
```
"@aws-amplify/ui-react": "^3.0.1"
"aws-amplify": "^4.3.26"
"next": "12.1.6"
"react": "18.1.0"
```
**Important lines of code**
__app.tsx_
`Amplify.configure({ ...awsExports, ssr: true });`

_All Pages are using getServerSideProps_
```
export const getServerSideProps: GetServerSideProps = async (context : any) => {
    try {
        const SSR = withSSRContext({ req });

        await SSR.Auth.currentAuthenticatedUser();
        
        console.log('User logged in');
    } catch (e) {
        console.log('User not logged in');
    }

    return {
        props: {}
    };
}
```

**Expected behavior and issue description**
After successful Cognito login, if the user navigates to any of the pages, the message `'User logged in'` should be printed in the server/console. 

The code works perfectly on my localhost, also in my main branch which I'm hosting in Amplify. But it does not work on another branch (develop in this case), which I'm hosting in Amplify too, but it has the `Access control` turned on.

An important point: Cognito is login in the user successfully, I'm able to see the cookies set with correct values. 

Something with Access control + getServerSideProps is messing up with the Auth object.

Sadly, I'm unable to share my code, but please let me know if you need more data and I'll share it.

**Comment by joekendal** [comment]
Wow still no progress on this

**Comment by kolodi** [comment]
Sorry for late response. I have disabled Restricted Access since the when the problem occurred and never used again. I'm probably going to check this again later.
