### ISSUE TITLE
DataStore: How to not sync admin only models

### ISSUE THREAD

**Issue by matart15** [aws-amplify/amplify-js#9619]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React, React Native

### Amplify APIs

DataStore

### Environment information

<details>

```

  System:
    OS: macOS 12.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 34.08 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
    Yarn: 1.22.17 - ~/workplace/gitlab/goldware/salescircle/salescircle_front/node_modules/.bin/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v12.22.1/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 98.0.4758.102
    Firefox: 97.0
    Safari: 15.3
  npmGlobalPackages:
    @aws-amplify/cli: 7.6.21
    @nestjs/cli: 8.1.5
    @teambit/bvm: 0.0.34
    aws-cdk: 2.3.0
    detox-cli: 19.0.0
    eas-cli: 0.47.0
    expo-cli: 5.2.0
    http-server: 14.1.0
    npm: 8.3.0
    nx: 13.2.3
    pm2: 5.1.2
    prisma: 3.5.0




```

</details>

### Describe the bug

I have admin only model 

```

type Project @model @auth(rules: [{allow: groups, groups: ["Admin"]}, {allow: groups, groupsField: "company", operations: [read]}]) {
  id: ID!
  name: String
  status: ProjectStatus
  company: String
}
```

I am using `Datastore` for my employee-only app. Since it is an employee-only app, I know this app does not need a `Project` model.

Currently it gives me warning everytime I open app
`Connection failed: {"errors":[{"errorType":"Unauthorized","message":"Not Authorized to access onDeleteProject on type Project"}]}`
`Connection failed: {"errors":[{"errorType":"Unauthorized","message":"Not Authorized to access onUpdateProject on type Project"}]}`
`Connection failed: {"errors":[{"errorType":"Unauthorized","message":"Not Authorized to access onCreateProject on type Project"}]}`

I tried, returning false on `syncExpressions` it did not help.

```
DataStore.configure({
  syncExpressions: [
    // @ts-ignore
    syncExpression(Project, (): ((p: Project) => unknown) => {
      return (p: Project) => !p
    }),
    // @ts-ignore
    syncExpression(Door, (): ((post: Door) => unknown) => {
      return (post: Door) => post
    }),
  ],
})
```

### Expected behavior

```
   syncExpression(Project1, (): ((p: Project1) => unknown) => {
      return (p: Project1) => false
    }),
```

stop trying sync Project

### Reproduction steps

1. Create simple amplify project
2. set datastore
3. add stop sync method

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @matart15 👋 thanks for raising this issue. After discussing with the team, I've learned you wouldn't need or want to use sync expressions for this use case. The errors to subscribe the mutation events on the model are to be expected because the auth rule is being applied correctly and preventing an unauthorized user from syncing or subscribing to that data.

**Comment by matart15** [comment]
@chrisbonifacio  Thank you.

I could not understand very well

are you saying 1 or 2?. Or did I completely misunderstand?
1. ignore the `Project` sync warnings. 
2. following code should not give a `warning`?
```
type Project @model @auth(rules: [{allow: groups, groups: ["Admin"]}]) {
  id: ID!
  name: String
  status: ProjectStatus
  company: String
}
```

**Comment by chrisbonifacio** [comment]
Hi @matart15 Sorry for the confusion. I meant number 1, it should be safe to ignore the Project sync warnings. The important thing is that if the user should not have access to the Project data, they are not able to sync it. So this behavior is expected.

**Comment by matart15** [comment]
Ok. thank you.
