### ISSUE TITLE
Android app not opening if in a killed state

### ISSUE THREAD

**Issue by RMG0** [aws-amplify/amplify-js#9637]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Push Notifications

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 1.52 GB / 15.71 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 98.0.4758.102
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.56)       
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @aws-amplify/pushnotification: ^4.3.8 => 4.3.8 
    @babel/core: ^7.16.7 => 7.16.7 
    @babel/runtime: ^7.16.7 => 7.16.7 
    @react-native-community/push-notification-ios: ^1.10.1 => 1.10.1 (1.0.3)
    @types/react: ^17.0.38 => 17.0.38
    @types/react-native: ^0.66.11 => 0.66.11
    aws-amplify: ^4.3.11 => 4.3.11
    axios: ^0.24.0 => 0.24.0 (0.21.4)
    babel-plugin-transform-remove-console: ^6.9.4 => 6.9.4
    eslint: 8.6.0 => 8.6.0
    hermes-inspector-msggen:  1.0.0
    metro-react-native-babel-preset: ^0.66.2 => 0.66.2
    react: 17.0.2 => 17.0.2
    react-native: 0.66.4 => 0.66.4
    react-native-cli: ^2.0.1 => 2.0.1
  npmGlobalPackages:
    @aws-amplify/cli: 7.6.2
    npm: 8.3.2
    react-devtools: 4.8.2
    react-native-cli: 2.0.1
    yarn: 1.22.10
```

</details>

### Describe the bug

Like if you got a notification and then kill the app, Tapping on the notification wont open it.
Did some debugging and found this. In RNPushNotificationHelper, while creating notification ,
we set pendingIntent
PendingIntent pendingIntent = PendingIntent.getBroadcast....
Now if we kill the app, the RNPushNotificationBroadcastReceiver also gets killed and so now tapping on notification not finding this.

May be related to (but still happening )
https://github.com/aws-amplify/amplify-js/pull/9055
https://github.com/aws-amplify/amplify-js/issues/6000
### Expected behavior

I checked some other libraries like
https://github.com/zo0r/react-native-push-notification
which uses Service to solve this as Services won't get killed if app gets killed.
I cant use other libraries because amplify is tightly linked to aws pinpoint.

Hope this will help anyone and get better solution.

### Reproduction steps

1. kill the app
2. send push notification
3. Open the app
4. send push notification again
5. kill the app
6. Now ope the app from push received in step4 above

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Mobile Device

Any Android Device

### Mobile Operating System

Any Android OS

**Comment by Samaritan1011001** [comment]
Hi @RMG0, thank you for opening the issue. I want you to make sure you have the following setup correctly, 
- Use the latest `pushnotification` version -- "@aws-amplify/pushnotification": "^4.3.9" 
- Make sure you have updated `AndroidManifest.xml` as shown in step 9 from the documentation -- https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/js/#setup-for-android

**Comment by RMG0** [comment]
Hi @Samaritan1011001 , Thanks for quick response on this.

1. I had already tried "@aws-amplify/pushnotification": "^4.3.9" version and still hapening, I also can not see any change from 4.3.8=>4.8.9 related to this, so I am sure issue will still persist in any of these versions.

2. I have correct settings according to the given documentation. 

One suggestion on documentation though like, documentation suggests to add below code but its irrelevant now as we dont have `RNPushNotificationDeviceIDService ` anymore in library so below code is irrelevant.

```
<service
             android:name="com.amazonaws.amplify.pushnotification.RNPushNotificationDeviceIDService">
             <intent-filter>
                 <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
             </intent-filter>
         </service>
```

**Comment by Samaritan1011001** [comment]
Thank you. I was only able to reproduce your issue when I **_did not_** have the following in my `AndroidManifest.xml`, 
```
 <receiver
            android:name="com.amazonaws.amplify.pushnotification.modules.RNPushNotificationBroadcastReceiver"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.amazonaws.amplify.pushnotification.NOTIFICATION_OPENED"/>
            </intent-filter>
        </receiver>
```
And I agree with your suggestion. Thank you for pointing it out. 
Can you make sure you have the above in the right place? Make sure to rebuild the app and if you are still seeing the same issue, please provide a reproducible example so I can take a better look.

**Comment by RMG0** [comment]
Thank you and I think I am using the same code in `AndroidManifest.xml`, Just pasting here, in case I am missing anything here.
 ```
<receiver
             android:name="com.amazonaws.amplify.pushnotification.modules.RNPushNotificationBroadcastReceiver"
             android:exported="false" >
             <intent-filter>
                 <action android:name="com.amazonaws.amplify.pushnotification.NOTIFICATION_OPENED"/>
             </intent-filter>
         </receiver>
```
If we remove above code then opening app will never work when a user taps on a notification, But my case a little different and I can put exact steps again here
1. Open app normally by launching from app icon
2. Send a push notification.
3. Dont interact with this push notification and just swipe out app instance (basically kill your app manually)
4. Now, tap on the push notification you got in step 2). Here app will not open. 

I had done some debugging and found this. In `RNPushNotificationHelper`, while creating notification ,
we set `pendingIntent`
`PendingIntent pendingIntent = PendingIntent.getBroadcast....`
Now if we kill the app, the `RNPushNotificationBroadcastReceiver `also gets killed and so now tapping on notification not finding this.

**Comment by RMG0** [comment]
Do you have any example project working correctly in this case? To be honest I didnt find any bare sample project using this library where I can test this.

**Comment by Samaritan1011001** [comment]
You can use this sample project for [reference](https://github.com/Samaritan1011001/push_notif)
Another question I have for you is: are you seeing this in a production build or the debug one?

**Comment by RMG0** [comment]
Thanks for sample project 
And I am facing this in both debug + prod builds

**Comment by RMG0** [comment]
One thing I forgot to mention her is like we have made a slight change in 
`com.amazonaws.amplify.pushnotification.RNPushNotificationMessagingService`
We have just removed `if (!isForeground)`  condition in `sendNotification `so that our app can get notification even in foreground. (Not sure if there is any other way to achieve this) 


I think irrespective of this change, the original issue still remains like app wont open if in a killed state.

**Comment by RMG0** [comment]
I tried your sample app https://github.com/Samaritan1011001/push_notif and was able to reproduce this bug
Steps
1. Open the app
2. Background your app
3. Send push notification to app
4. You can see push notification shown on notification tray. 
5. Dont tap this notification but rather kill your app by swiping from recent app/activity list
6. Now tap notification and it will not open the app.

**Comment by Samaritan1011001** [comment]
How are you sending the notification? 

And can you open `logcat` on android studio and filter using `RNPushNotificationHelper` and capturing the output when a notification is sent to the app? It should look like this, 

`02-25 07:45:04.942 15592-15592/com.push_notif I/RNPushNotificationHelper: sendNotification: Intent { act=com.amazonaws.amplify.pushnotification.NOTIFICATION_OPENED (has extras) }
`

I want to check that the intent is being set on the notification that is coming in. Thanks!

**Comment by RMG0** [comment]
Hi,
I am sending notification to device token using pinpoint TestMessanging console screen and here are my steps and logs

```
1.Open app and put in bg

2. Send notification from AWS pinpoint to token (captured from RNPushNotificationModule: got token ..... earlier)
I can see below logs
2022-02-25 09:06:50.710 15094-15131/com.my.app I/RNPushNotificationMessagingService: Message From: XXX5XX2248XX
2022-02-25 09:06:52.536 15094-15159/com.my.app I/RNPushNotificationModule: constructing RNPushNotificationModule
2022-02-25 09:06:52.583 15094-15094/com.my.app I/RNPushNotificationMessagingService: sendNotification: Bundle[{pinpoint.openApp=true, userInteraction=false, pinpoint.notification.title= test, pinpoint.notification.body=dasdsad, id=1466337821, pinpoint.campaign.campaign_id=_DIRECT, pinpoint.notification.silentPush=0}]
2022-02-25 09:06:52.599 15094-15094/com.my.app I/RNPushNotificationHelper: sendNotification: Intent { act=com.amazonaws.amplify.pushnotification.NOTIFICATION_OPENED (has extras) }
2022-02-25 09:06:52.615 15094-15164/com.my.app I/RNPushNotificationModule: initializing RNPushNotificationModule
2022-02-25 09:06:52.615 15094-15164/com.my.app I/RNPushNotificationModule: registering receiver
2022-02-25 09:06:54.753 15094-15164/com.my.app I/RNPushNotificationModule: initializing RNPushNotificationModule
2022-02-25 09:06:55.288 15094-15094/com.my.app I/RNPushNotificationModule: got token XXXX-XXXQt2C4QeOGATnKD:APA91bGo3MDvrb7qoP13i-XXXFzpgdegQec0lAZYE7_FYzKqmpI6KD_kYpIpUvzNwbDPr-G5KaMgE_nBJqQTm46yDcngfsjdVLnVErM08TxsIVOaJIX8lHFDkGIxDESqLJVzJrNlH7hE

3. Kill app and not tap on notification , its not opening app but logging below
2022-02-25 09:07:46.265 1435-1958/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=com.amazonaws.amplify.pushnotification.NOTIFICATION_OPENED flg=0x10 (has extras) } to com.my.app/com.amazonaws.amplify.pushnotification.modules.RNPushNotificationBroadcastReceiver
```

-Rajni

**Comment by Samaritan1011001** [comment]
Thanks! Which device are you testing this on?

**Comment by RMG0** [comment]
It' Samsung S21,

Sent from my Bell Samsung device over Canada’s largest network.
________________________________

**Comment by Samaritan1011001** [comment]
@RMG0 thank you for the log output above! I was able to reproduce and get to the root of this issue. It seems to be happening because this particular scenario falls right in between the [drawbacks](https://developer.android.com/guide/components/broadcast-exceptions) of manifest-registered broadcasts on Android Oreo and context-registered broadcasts. 
This would mean we need to replace the use of manifest-registered broadcast with a scheduled job which is a bigger effort. 
Meanwhile, I was able to resolve the problem by decreasing the `targetSdkVersion` to 25 in the `android/build.gradle` 
Let me know if that works for you for now until we work on replacing manifest-registered broadcasts.

**Comment by RMG0** [comment]
Thanks @Samaritan1011001 for checking this and really appreciate this.

I can understand the reason behind this issue.
Tested with `targetSdkVersion `to 25 and this fixes the problem but **_we can't use `targetSdkVersion `25 on stores_** because as per their requirement `targetSdkVersion `should be 30.  (https://support.google.com/googleplay/android-developer/answer/9859152?visit_id=637402646062706504-1797308153&rd=1#targetsdk)

So even if this fixed this problem, no one can use it in production. 

This is a big issue for us because we are having a huge user base and we send many push notifications on daily basis based on event and some engagement cases, And most of the time push is failing to open the app failing our push notification purpose.

Please don't mind but Can I ask any approximate time for this fix? I know you may have other priority stuffs too but just wanted to check so we can set out plan on this.

Again, A huge thank you to you and the team for this awesome module.

**Comment by LeviWilliams** [comment]
Hey, this is also happening to us in production with a similar use case as above. As @Samaritan1011001  mentioned, a scheduled job is a decent amount of work for this fix. Would appreciate any ideas or patches for our project - this would be a huge help for us. 

Thanks!

**Comment by Samaritan1011001** [comment]
@RMG0 and @LeviWilliams 
Created a PR with a simple fix. Let me know if the solution works on your setup. 
It still needs to be reviewed and merged.

**Comment by RMG0** [comment]
Hi @Samaritan1011001 , I see the fix is merged to master, any timeline to get this as npm update?
Thank you

**Comment by Samaritan1011001** [comment]
@RMG0, the fix should be released early next week if there is no other delay.

**Comment by Samaritan1011001** [comment]
@RMG0 Meanwhile, if you want to test it. It's available now with, 
`npm i @aws-amplify/pushnotification@4.3.17-unstable.1`

**Comment by RMG0** [comment]
That's a good idea, Thanks a lot.

**Comment by Samaritan1011001** [comment]
@RMG0 the release is complete and the fix is available in the latest version. Please check if it solves it and close the issue if so. Thank you for working with us on this and opening the issue!

**Comment by BMR11** [comment]
That's awesome, Thank you for all hard work on this and really appreciate it.
I will test this and close this.

**Comment by RMG0** [comment]
That's awesome, Thank you for all hard work on this and really appreciate
it.
I will test this and close this.

**Comment by RMG0** [comment]
I tested latest release 4.3.17 and can confirm like this is fixed. 
Thank you all for fixing this
