### ISSUE TITLE
Auth.signOut() freezes tab

### ISSUE THREAD

**Issue by RodPaDev** [aws-amplify/amplify-js#9640]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
 System:
    OS: macOS 12.1
    CPU: (8) x64 Apple M1
    Memory: 33.34 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.1/bin/npm
  Browsers:
    Brave Browser: 98.1.35.103
    Chrome: 98.0.4758.109
    Safari: 15.2
  npmPackages:
    @aws-amplify/ui-react: ^2.5.0 => 2.5.0 
    @aws-amplify/ui-react-internal:  undefined ()
    @aws-amplify/ui-react-legacy:  undefined ()
    @babel/eslint-parser: ^7.17.0 => 7.17.0 
    @vitejs/plugin-react: ^1.0.7 => 1.2.0 
    aws-amplify: ^4.3.14 => 4.3.14 
    eslint-config-react-app: ^7.0.0 => 7.0.0 
    eslint-plugin-import: ^2.25.4 => 2.25.4 
    eslint-plugin-jsx-a11y: ^6.5.1 => 6.5.1 
    eslint-plugin-react: ^7.28.0 => 7.28.0 
    eslint-plugin-react-hooks: ^4.3.0 => 4.3.0 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    react-redux: ^7.2.6 => 7.2.6 
    react-router: ^6.2.1 => 6.2.1 
    react-router-dom: ^6.2.1 => 6.2.1 
    redux: ^4.1.2 => 4.1.2 
    redux-logger: ^3.0.6 => 3.0.6 
    redux-saga: ^1.1.3 => 1.1.3 
    redux-saga/effects:  undefined ()
    vite: ^2.8.0 => 2.8.4 
    vite-plugin-eslint: ^1.3.0 => 1.3.0 
  npmGlobalPackages:
    @aws-amplify/cli: 5.3.1
    ganache-cli: 6.12.2
    generator-code: 1.5.2
    live-server: 1.2.1
    npm: 6.14.13
    serverless: 2.54.0
    solc: 0.8.10
    svg-to-react-cli: 1.5.0
    truffle: 5.4.18
    yo: 4.2.0


```

</details>

### Describe the bug

I'm using `React` and `Vite` and when I call `await Auth.signOut()`  it freezes the app and the tab becomes unresponsive after closing the tab and re-opening it is signed out.

I'm invoking the function straight on the `onClick` event in the react component but that shouldn't be an issue I think. It's either something stupid that I'm missing or a bug

### Expected behavior

Should sign-out and not freeze the tab

### Reproduction steps

1. Install `aws-amplify` in a react + vite project
2. use `await Auth.signOut()` in a button 

### Code Snippet

```js
  const signOut = async () => {
    try {
      e?.preventDefault()
      Print.log('Signed out')
      await Auth.signOut()
      setTriggerFetch(false)
      dispatch({ type: 'RESET_USER_DATA' })
    } catch (error) {
      Print.error('Error signing out user ', error)
    }
  }
``` 

```jsx
      <button onClick={signOut}>Sign Out</button>
```

### Log output

No logs or errors

### Manual configuration

```js
const {
  VOTERO_AWS_REGION,
  VOTERO_CONGITO_USER_POOL_ID,
  VOTERO_CONGITO_USER_POOL_WEB_CLIENT_ID,
  VOTERO_GRAPHQL_ENDPOINT
} = import.meta.env

const Auth = {
  region: VOTERO_AWS_REGION,
  userPoolId: VOTERO_CONGITO_USER_POOL_ID,
  userPoolWebClientId: VOTERO_CONGITO_USER_POOL_WEB_CLIENT_ID
}

const API = {
  graphql_endpoint: VOTERO_GRAPHQL_ENDPOINT,
  graphql_endpoint_iam_region: VOTERO_AWS_REGION
}

const amplifyConfig = {
  Auth,
  API
}

export default amplifyConfig
ƒ
```

### Additional information and screenshots

There is no information

**Comment by RodPaDev** [comment]
I have tried debugging and stepping into the function and it freezes before stepping into it

**Comment by chrisbonifacio** [comment]
Hi @RodPaDev 👋 I think I might've been able to reproduce the issue but for me, clicking on a custom sign out button was not doing anything because I was getting this error.

<img width="800" alt="Screen Shot 2022-02-24 at 11 09 22 AM" src="https://user-images.githubusercontent.com/16952986/155562371-85f9b737-2c18-491a-b281-45915ebc65f2.png">

Optional chaining (i.e. `e?.preventDefault()` is not working here because `e` was not used as an argument to your signOut function.

Can you try adjusting it to this and see if that helps?

```js
  const signOut = async (e) => {
    try {
      e?.preventDefault()
      Print.log('Signed out')
      await Auth.signOut()
      setTriggerFetch(false)
      dispatch({ type: 'RESET_USER_DATA' })
    } catch (error) {
      Print.error('Error signing out user ', error)
    }
  }
```

By the way - since I can't tell from your dependencies if you're already doing this - there are compatibility issues with Amplify and bundlers like Vite, Webpack 5, etc where you might need to include node polyfills because some things like `global` won't be defined otherwise.

this is how I configured my vite.config.js as a workaround to include node polyfills

```js
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
// yarn add --dev @esbuild-plugins/node-globals-polyfill
import { NodeGlobalsPolyfillPlugin } from "@esbuild-plugins/node-globals-polyfill";
// yarn add --dev @esbuild-plugins/node-modules-polyfill
import { NodeModulesPolyfillPlugin } from "@esbuild-plugins/node-modules-polyfill";
// You don't need to add this to deps, it's included by @esbuild-plugins/node-modules-polyfill
import rollupNodePolyFill from "rollup-plugin-node-polyfills";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      // This Rollup aliases are extracted from @esbuild-plugins/node-modules-polyfill,
      // see https://github.com/remorses/esbuild-plugins/blob/master/node-modules-polyfill/src/polyfills.ts
      // process and buffer are excluded because already managed
      // by node-globals-polyfill
      util: "rollup-plugin-node-polyfills/polyfills/util",
      sys: "util",
      events: "rollup-plugin-node-polyfills/polyfills/events",
      stream: "rollup-plugin-node-polyfills/polyfills/stream",
      path: "rollup-plugin-node-polyfills/polyfills/path",
      querystring: "rollup-plugin-node-polyfills/polyfills/qs",
      punycode: "rollup-plugin-node-polyfills/polyfills/punycode",
      url: "rollup-plugin-node-polyfills/polyfills/url",
      string_decoder: "rollup-plugin-node-polyfills/polyfills/string-decoder",
      http: "rollup-plugin-node-polyfills/polyfills/http",
      https: "rollup-plugin-node-polyfills/polyfills/http",
      os: "rollup-plugin-node-polyfills/polyfills/os",
      assert: "rollup-plugin-node-polyfills/polyfills/assert",
      constants: "rollup-plugin-node-polyfills/polyfills/constants",
      _stream_duplex:
        "rollup-plugin-node-polyfills/polyfills/readable-stream/duplex",
      _stream_passthrough:
        "rollup-plugin-node-polyfills/polyfills/readable-stream/passthrough",
      _stream_readable:
        "rollup-plugin-node-polyfills/polyfills/readable-stream/readable",
      _stream_writable:
        "rollup-plugin-node-polyfills/polyfills/readable-stream/writable",
      _stream_transform:
        "rollup-plugin-node-polyfills/polyfills/readable-stream/transform",
      timers: "rollup-plugin-node-polyfills/polyfills/timers",
      console: "rollup-plugin-node-polyfills/polyfills/console",
      vm: "rollup-plugin-node-polyfills/polyfills/vm",
      zlib: "rollup-plugin-node-polyfills/polyfills/zlib",
      tty: "rollup-plugin-node-polyfills/polyfills/tty",
      domain: "rollup-plugin-node-polyfills/polyfills/domain",
    },
  },
  optimizeDeps: {
    esbuildOptions: {
      // Node.js global to browser globalThis
      define: {
        global: "globalThis",
      },
      // Enable esbuild polyfill plugins
      plugins: [
        NodeGlobalsPolyfillPlugin({
          process: true,
          buffer: true,
        }),
        NodeModulesPolyfillPlugin(),
      ],
    },
  },
  build: {
    rollupOptions: {
      plugins: [
        // Enable rollup polyfills plugin
        // used during production bundling
        rollupNodePolyFill(),
      ],
    },
  },
});
```

**Comment by chrisbonifacio** [comment]
Hmm, really having trouble reproducing this behavior. I even configured my env variables similar to yours along with the vite.config.js I shared in the previous comment. App loads and signs in/out just fine 🤔 

```
// .env
VOTERO_AWS_REGION = us-east-1
VOTERO_CONGITO_USER_POOL_ID = us-east-1_xxxxx
VOTERO_CONGITO_USER_POOL_WEB_CLIENT_ID = xxxxxxxxxx
VOTERO_GRAPHQL_ENDPOINT =
  https://xxxxxxxxxxx.appsync-api.us-east-1.amazonaws.com/graphql
```

**Comment by RodPaDev** [comment]
Yep, that's exactly what my config looked like.

I created a repo where it should be able to be replicated, it only has the necessary to replicate it
All you need to do is add the .env file like you did above
https://github.com/RodPaDev/mwe-amplify-bug

**Comment by chrisbonifacio** [comment]
Awesome, thank you! I will try that repo now and report back.

**Comment by RodPaDev** [comment]
Also to rule out browsers I tested with chrome, safari, and brave and it happens in all

Awesome thank you for the support!

**Comment by RodPaDev** [comment]
Just to rule out Apple Silicon I tried to run it on code sandbox and the same thing it froze the tab

**Comment by chrisbonifacio** [comment]
Okay, so if you add this line to your main.jsx file, you'll be able to see whether the signOut event is really beind dispatched by Amplify under the hood

```js
Amplify.Logger.LOG_LEVEL = 'DEBUG'
```

I noticed that you're using both the `Authentictor.Provider` and the `AmplifyProvider` components. With this setup, I see the behavior you described where the page freezes and I don't see any auth events being dispatched or logged in the console.

If I remove the `Authenticator.Provider` wrapper around your app and leave only the AmplifyProvider, I can see that the auth signout event is being dispatched.

```js
//main.jsx

import React from 'react'
import ReactDOM from 'react-dom'
import { BrowserRouter } from 'react-router-dom'

import './style/global.scss'

import Amplify from 'aws-amplify'
import { AmplifyProvider, Authenticator } from '@aws-amplify/ui-react'
import '@aws-amplify/ui-react/styles.css'

import Routes from './router'
import amplifyConfig from './config/amplify'

Amplify.Logger.LOG_LEVEL = 'DEBUG'

Amplify.configure(amplifyConfig)

ReactDOM.render(
  <React.StrictMode>
    <BrowserRouter>
      <AmplifyProvider>
        <Routes />
      </AmplifyProvider>
    </BrowserRouter>
  </React.StrictMode>,
  document.getElementById('root')
)
```

<img width="1451" alt="Screen Shot 2022-02-24 at 12 32 57 PM" src="https://user-images.githubusercontent.com/16952986/155576979-7fd330bd-a0f0-4ac1-97dc-8c75a27cf732.png">

**Comment by RodPaDev** [comment]
That was it!  I was using Authenticator before but wanted more control and forgot to remove the provider before adding the amplify one🤦🤦🤦 Thank you a lot for the great help and sorry for taking up your time for what seemed to be a bug but turned out to be simple and pure stupidity

**Comment by chrisbonifacio** [comment]
It's usually the smallest things that stump us haha Thanks for providing the repo, the extra context was super helpful!

**Comment by alexandre-bedos-upandgo** [comment]
Hi guys ! Thank you you saved my day I had exactly the same issue (using Authenticaticor and then dropped it) and the freeze was driving me crazy !!!
