### ISSUE TITLE
Auth signIn creates new Cognito Identity Id everytime

### ISSUE THREAD

**Issue by matart15** [aws-amplify/amplify-js#9642]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

PubSub

### Environment information

<details>

```
# Put output below this line

  System:
    OS: macOS 12.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 28.63 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
    Yarn: 1.22.17 - ~/.yvm/shim/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v12.22.1/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 98.0.4758.109
    Firefox: 97.0.1
    Safari: 15.3
  npmPackages:
    @babel/core: 7.17.4 => 7.17.4 (7.17.5)
    @eva-design/eva: 2.1.1 => 2.1.1 
    @expo/vector-icons: 12.0.0 => 12.0.0 (12.0.5)
    @react-native-async-storage/async-storage: 1.16.1 => 1.16.1 
    @react-native-community/eslint-config: 3.0.1 => 3.0.1 
    @react-native-community/netinfo: 7.1.3 => 7.1.3 
    @react-navigation/drawer: 6.3.1 => 6.3.1 
    @react-navigation/native: 6.0.2 => 6.0.2 
    @react-navigation/native-stack: 6.1.0 => 6.1.0 
    @types/jest: 27.4.0 => 27.4.0 
    @types/react: 17.0.39 => 17.0.39 
    @types/react-native: 0.64.12 => 0.64.12 (0.66.16)
    @types/react-native-snap-carousel: 3.8.5 => 3.8.5 
    @typescript-eslint/eslint-plugin: 5.12.0 => 5.12.0 (4.33.0)
    @typescript-eslint/eslint-plugin-tslint: 5.12.0 => 5.12.0 
    @typescript-eslint/parser: 5.12.0 => 5.12.0 (4.33.0)
    @ui-kitten/components: 5.1.1 => 5.1.1 
    @ui-kitten/eva-icons: 5.1.1 => 5.1.1 
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: 5.2.6 => 5.2.6 
    aws-amplify: 4.3.14 => 4.3.14 
    aws-amplify-react-native: 6.0.2 => 6.0.2 
    babel-jest: 27.5.1 => 27.5.1 (26.6.3)
    eslint: 8.9.0 => 8.9.0 
    eslint-config-airbnb: 19.0.4 => 19.0.4 
    eslint-config-prettier: 8.3.0 => 8.3.0 (6.15.0)
    eslint-import-resolver-typescript: 2.5.0 => 2.5.0 
    eslint-plugin-autofix: 1.1.0 => 1.1.0 
    eslint-plugin-flowtype: 8.0.3 => 8.0.3 (2.50.3)
    eslint-plugin-graphql: 4.0.0 => 4.0.0 
    eslint-plugin-import: 2.25.4 => 2.25.4 
    eslint-plugin-prettier: 4.0.0 => 4.0.0 (3.1.2)
    eslint-plugin-react: 7.28.0 => 7.28.0 
    eslint-plugin-react-native: 4.0.0 => 4.0.0 (3.11.0)
    eslint-plugin-simple-import-sort: 7.0.0 => 7.0.0 
    eslint-plugin-unused-imports: 2.0.0 => 2.0.0 
    expo: 44.0.0 => 44.0.0 
    expo-asset: 8.4.6 => 8.4.6 
    expo-constants: 13.0.1 => 13.0.1 (13.0.2)
    expo-dev-client: ~0.8.4 => 0.8.4 
    expo-font: 10.0.4 => 10.0.4 (10.0.5)
    expo-linking: 3.0.0 => 3.0.0 
    expo-secure-store: ~11.1.0 => 11.1.1 
    expo-splash-screen: 0.14.1 => 0.14.1 
    expo-status-bar: 1.2.0 => 1.2.0 
    expo-updates: ~0.11.6 => 0.11.6 
    expo-web-browser: 10.1.0 => 10.1.0 
    formik: 2.2.9 => 2.2.9 
    hermes-inspector-msggen:  1.0.0 
    husky: 7.0.4 => 7.0.4 
    jest: 26.6.3 => 26.6.3 
    jest-expo: 44.0.1 => 44.0.1 
    lint-staged: 12.3.4 => 12.3.4 
    react: 17.0.1 => 17.0.1 
    react-dom: 17.0.1 => 17.0.1 
    react-native: 0.64.3 => 0.64.3 
    react-native-fast-image: 8.5.11 => 8.5.11 
    react-native-gesture-handler: ~2.1.0 => 2.1.3 
    react-native-keyboard-aware-scroll-view: 0.9.5 => 0.9.5 
    react-native-linear-gradient: 2.5.6 => 2.5.6 
    react-native-reanimated: ~2.3.1 => 2.3.2 
    react-native-safe-area-context: 3.3.2 => 3.3.2 
    react-native-screens: 3.10.1 => 3.10.1 (3.12.0)
    react-native-size-matters: 0.4.0 => 0.4.0 
    react-native-snap-carousel: 3.9.1 => 3.9.1 
    react-native-svg: 12.1.1 => 12.1.1 
    react-native-web: 0.17.1 => 0.17.1 
    react-test-renderer: 17.0.2 => 17.0.2 
    typescript: 4.5.5 => 4.5.5 
  npmGlobalPackages:
    @aws-amplify/cli: 7.6.21
    @nestjs/cli: 8.1.5
    @react-native-community/cli: 7.0.3
    @teambit/bvm: 0.0.34
    aws-cdk: 2.3.0
    detox-cli: 19.0.0
    eas-cli: 0.47.0
    expo-cli: 5.2.0
    http-server: 14.1.0
    npm: 8.3.0
    nx: 13.2.3
    pm2: 5.1.2
    prisma: 3.5.0



```

</details>

### Describe the bug

As documentation says, I can get CognitoIdentityId. But if I enable Uanuthrized login on my federation pool, `cognitIdentityId` changes every time on the same email/password account. I end up with hundreds of `cognitIdentityId`

I know we have to add CognitoIdentityId to the IoT policy manually on every new user. But now I have to do this every time an existing users signout and sign in back.

1. I want to enable UnAuthenticated usage on our app. ( some pages )
2. I want to logout and login back functionality on our app
3. I want some users permitted to send pubSub to my IoT device. some are not. ( this part I can't quiet figure out )

If I allow on the application all users, I can't block some users from sending pubSub to my IoT device.

I was trying to create an admin page that allows which user to allow access to IoT messages. But everytime cognitoIdentityId changes its hard to do ( not impossible. I have to hold extra data model which holds allowed userId )

Is it expected behaviour?

### Expected behavior

expects : even unauthorized access is allowed, same account have same `cognitIdentityId`

### Reproduction steps

1. create amplify with auth
2. allow unauthrized auth on federation
3. create user
4. sign in, signout, signin again
5. there will be 2 cognitIdentityId

**Comment by stocaaro** [comment]
Hello @matart15,

I think you are correct that unauthorized login will create a new identityId for each user session, which makes it a difficult candidate for granting individuals access to IoT. I'm confused by talking about having an Admin page that is accessed by users that aren't logged in. Can you describe the user interactions you're hoping to support with these PubSub subscriptions? I'm interested in who these unauthenticated users are and the reasons for not having them create accounts before accessing these subscriptions. 

Have you looked at [AppSync subscriptions](https://docs.aws.amazon.com/appsync/latest/devguide/aws-appsync-real-time-data.html) as an alternative to IoT Core?

Thanks,
Aaron

**Comment by stocaaro** [comment]
I think I may have misread your message. I'm not certain of the federated behavior when unauthorized auth is allowed. I have had mixed experience trying to grant PubSub access by a mechanism other than per identityId, as the documents recommend.

If you can reply with more details about what you've tried, what you're seeing and what you business case / constraints are, I would be happy to troubleshoot with you. For now, I'm going to close this issue and will reopen it with your reply.

Thanks!
Aaron
