### ISSUE TITLE
user.completeNewPasswordChallenge is not a function catch 22

### ISSUE THREAD

**Issue by jmarshall9120** [aws-amplify/amplify-js#9661]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
 System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 17.06 GB / 31.74 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 98.0.4758.102
    Edge: Spartan (44.22000.120.0), Chromium (98.0.1108.62)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @aws-amplify/ui-vue: ^2.1.3 => 2.1.3
    @babel/eslint-parser: ^7.16.3 => 7.17.0
    @nuxt/image: ^0.6.2 => 0.6.2
    @nuxtjs/auth-next: 5.0.0-1643791578.532b3d6 => 5.0.0-1643791578.532b3d6
    @nuxtjs/axios: ^5.13.6 => 5.13.6
    @nuxtjs/eslint-config: ^8.0.0 => 8.0.0
    @nuxtjs/eslint-module: ^3.0.2 => 3.0.2
    @nuxtjs/pwa: ^3.3.5 => 3.3.5
    @nuxtjs/vuetify: ^1.12.3 => 1.12.3
    @vue/test-utils: ^1.3.0 => 1.3.0
    aws-amplify: ^4.3.14 => 4.3.14
    babel-core: 7.0.0-bridge.0 => 7.0.0-bridge.0
    babel-jest: ^27.4.4 => 27.5.1
    core-js: ^3.19.3 => 3.21.1 (2.6.12)
    eslint: ^8.4.1 => 8.9.0
    eslint-config-prettier: ^8.3.0 => 8.4.0
    eslint-plugin-nuxt: ^3.1.0 => 3.1.0
    eslint-plugin-vue: ^8.2.0 => 8.4.1
    jest: ^27.4.4 => 27.5.1
    nuxt: ^2.15.8 => 2.15.8
    prettier: ^2.5.1 => 2.5.1
    vue: ^2.6.14 => 2.6.14 (3.2.31)
    vue-jest: ^3.0.4 => 3.0.7
    vue-server-renderer: ^2.6.14 => 2.6.14
    vue-template-compiler: ^2.6.14 => 2.6.14
    vuetify: ^2.6.1 => 2.6.3
    webpack: ^4.46.0 => 4.46.0
  npmGlobalPackages:
    @aws-amplify/cli: 7.6.22
    @vue/cli: 4.5.11
    browserify: 17.0.0
    gulp-cli: 2.3.0
    gulp-exec: 5.0.0
    npm-install-all: 1.1.21
    sass: 1.32.4
    webpack-cli: 4.5.0
```

</details>

### Describe the bug

There is a very annoying catch 22 that results when trying to use the Auth.completeNewPassword
function.  The Auth.completeNewPassword function takes 2 arguments, the first one 
being the cognito 'user' object returned by the Auth.signIn function.  There are two problems:
  1. Auth.completeNewPassword has a side effect which mutates the 'user' object causing 
  issues with vuex.
  2. If you try to clone the cognito 'user' object, you get this weird 
  'user.completeNewPasswordChallenge is not a function' error.

Here's the necessary back end for the setup.  The view is a basic sign in form, that allows
the user to submit a username and password.  If this results in a 'NEW_PASSWORD_REQUIRED' 
challenge, then the view will display a dialog prompting the user for a password. 

In the `amplifyChangePassword` function, I've included two options for passing the 
arguments both of which will result in different errors.  One of these strategies must 
be chosen if your attempting to implement this example.

```js
export const state = () => ({
  // variable for holding cognito user object
  user: '',

  // variable determining if a 'NEW_PASSWORD_REQUIRED' challenge needs to be
  // done.  When this is true the view shows a form for entreing the new password.
  changePasswordChallenge: false,
})

export const mutations = {
  updateUser(state, [user, error]) {
    state.user = user
    state.error = error
  },
  updateChangePasswordChallenge(state, bValue) {
    state.changePasswordChallenge = bValue
  },
}

export const actions = {
  
  // AUTHENTICATE WITH CREDENTIALS
  // This is called from the initial sign in form on the view
  amplifySignIn_WithCredentials: async (context, { username, password }) => {
    try {

      // get user object
      const cognitoUser = await Auth.signIn(username, password)

      //test to see if password update is required.
      if (cognitoUser.challengeName === 'NEW_PASSWORD_REQUIRED') {
        
        // make the challange as neccessary so the view can display dialog
        // form to the user for changing the password.
        context.commit('updateChangePasswordChallenge', true)
      }

      // store the user object for use later (such as when
      // the password change is submitted.)
      context.commit('updateUser', [cognitoUser, null])
    } catch (error) {
      console.log(error)
    } finally {
      // context.commit('authResolved', true)
    }
  },

  //CHANGE PASSWORD
  amplifyChangePassword: async (context, newPassword) => {
    try {

      // Option 1: copy user object, to avoid error: 
      //    [vuex] do not mutate vuex store state outside mutation handlers.
      // Results in error: 
      //    user.completeNewPasswordChallenge is not a function
      const lastUser = JSON.parse(JSON.stringify(context.state.user))
      const newUser = await Auth.completeNewPassword(lastUser, newPassword)

      // Option2: pass origional user object returned from sign in to avoig error:
      //     user.completeNewPasswordChallenge is not a function
      // Results in:
      //     [vuex] do not mutate vuex store state outside mutation handlers.
      const newUser = await Auth.completeNewPassword(context.state.user, newPassword)
      
      context.commit('updateUser',newUser)
    } catch (err) {
      console.log(err)
    }
  }
}
```

If using option 1 in the `amplifyChangePassword` function above (copying user object), you'll get this error:
```
Errors:
TypeError: user.completeNewPasswordChallenge is not a function
    at eval (Auth.js?bf82:924:1)
    at new Promise (<anonymous>)
    at AuthClass.completeNewPassword (Auth.js?bf82:923:1)
    at _callee5$ (auth.js?2c80:91:1)
    at tryCatch (runtime.js?96cf:63:1)
    at Generator.invoke [as _invoke] (runtime.js?96cf:294:1)
    at Generator.eval [as next] (runtime.js?96cf:119:1)
    at asyncGeneratorStep (asyncToGenerator.js?1da1:3:1)
    at _next (asyncToGenerator.js?1da1:25:1)
    at eval (asyncToGenerator.js?1da1:32:1)
```

If using option 2 in the `amplifyChangePassword` function above (passing user object), you'll get this error:
```
client.js?06a0:103 Error: [vuex] do not mutate vuex store state outside mutation handlers.
    at assert (vuex.esm.js?2f62:135:1)
    at Vue.store._vm.$watch.deep (vuex.esm.js?2f62:893:1)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1863:1)
    at Watcher.run (vue.runtime.esm.js?2b0e:4584:1)
    at Watcher.update (vue.runtime.esm.js?2b0e:4558:1)
    at Dep.notify (vue.runtime.esm.js?2b0e:730:1)
    at CognitoUser.reactiveSetter [as signInUserSession] (vue.runtime.esm.js?2b0e:1055:1)
    at CognitoUser.authenticateUserInternal (CognitoUser.js?3c43:476:1)
    at eval (CognitoUser.js?3c43:576:1)
    at eval (Client.js?1610:140:1)

client.js?06a0:103 Error: [vuex] do not mutate vuex store state outside mutation handlers.
    at assert (vuex.esm.js?2f62:135:1)
    at Vue.store._vm.$watch.deep (vuex.esm.js?2f62:893:1)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1863:1)
    at Watcher.run (vue.runtime.esm.js?2b0e:4584:1)
    at Watcher.update (vue.runtime.esm.js?2b0e:4558:1)
    at Dep.notify (vue.runtime.esm.js?2b0e:730:1)
    at CognitoUser.reactiveSetter [as challengeName] (vue.runtime.esm.js?2b0e:1055:1)
    at CognitoUser.authenticateUserInternal (CognitoUser.js?3c43:477:1)
    at eval (CognitoUser.js?3c43:576:1)
    at eval (Client.js?1610:140:1)
```

### Expected behavior

I would expect this jive with vue a little more easily.  I assume given, time I will be able to find what's preventing the copy solution from working, however its a bit annoying.  

1. Is it possible to set up this workflow so there's not a side effect?
2. At the very least, a better error message for when the copy technique fails.

### Reproduction steps

1. Implement a vue store as shown above.
2. Add a cognito user, using the web console so it requires a new password on first login.
3. Attempt to signIn and do the completeNewPassword call.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by jmarshall9120** [comment]
I used several function to deep copy the user object and found the lodash.deepcopy function to be the only one that worked.

**Comment by cwomack** [comment]
The developer preview for v6 of Amplify has officially been released with updates to the Auth package and much more! Please check out our [announcement](https://aws.amazon.com/blogs/mobile/aws-amplify-javascripts-new-developer-preview-with-reduced-bundle-sizes-improved-typescript-and-next-js-support/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=238088647) and updated [documentation](https://docs.amplify.aws/lib-v1/project-setup/create-application/q/platform/js/) to see what has changed.  Please take note that for this issue in particular, the `confirmSignIn()` method is imported directly in v6 and replaced the `Auth.completeNewPassword()` method. 

We believe this issue should be resolved within the dev preview and upcoming General Availability for Amplify v6, but let us know with a comment if there are further issues.

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
