### ISSUE TITLE
Error retrieving posts DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.

### ISSUE THREAD

**Issue by matart15** [aws-amplify/amplify-js#9663]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

DataStore

### Environment information

<details>

```

  System:
    OS: macOS 12.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 33.11 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
    Yarn: 1.22.17 - ~/.yvm/shim/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.3/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 98.0.4758.109
    Firefox: 97.0.1
    Safari: 15.3
  npmPackages:
    @aws-amplify/datastore: 3.7.7 => 3.7.7 
    @testing-library/jest-dom: 5.16.2 => 5.16.2 
    @testing-library/react: 12.1.3 => 12.1.3 
    @testing-library/user-event: 13.5.0 => 13.5.0 
    @types/jest: 27.4.1 => 27.4.1 
    @types/node: 16.11.26 => 16.11.26 (17.0.21)
    @types/react: 17.0.39 => 17.0.39 
    @types/react-dom: 17.0.12 => 17.0.12 
    aws-amplify: 4.3.15 => 4.3.15 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    react-scripts: 5.0.0 => 5.0.0 
    typescript: 4.6.2 => 4.6.2 
    web-vitals: 2.1.4 => 2.1.4 
  npmGlobalPackages:
    npm: 6.14.15
    nx: 13.6.1
    ts-node: 10.5.0




```

</details>

### Describe the bug

Error retrieving posts DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
    at Proxy.<anonymous> (http://localhost:3000/static/js/bundle.js:36217:22)
    at Proxy.method (http://localhost:3000/static/js/bundle.js:36015:21)
    at IndexedDBAdapter.<anonymous> (http://localhost:3000/static/js/bundle.js:27108:23)
    at step (http://localhost:3000/static/js/bundle.js:26065:17)
    at Object.next (http://localhost:3000/static/js/bundle.js:25996:14)
    at http://localhost:3000/static/js/bundle.js:25968:67
    at new Promise (<anonymous>)
    at __awaiter (http://localhost:3000/static/js/bundle.js:25947:10)
    at IndexedDBAdapter.getAll (http://localhost:3000/static/js/bundle.js:27102:12)
    at IndexedDBAdapter.<anonymous> (http://localhost:3000/static/js/bundle.js:27136:20)

### Expected behavior

just sync dsatastore

### Reproduction steps

https://github.com/matart15/amplify-datastore-fail/tree/strange-error

`strange-error` branch

1. yarn
2. yarn start

**Comment by chrisbonifacio** [comment]
This might be fixed by my suggestion on your other issue https://github.com/aws-amplify/amplify-js/issues/9631#issuecomment-1058150131

If the issue persists after upgrading amplify package versions:

I would check in your dev tools > Application > Storage > IndexedDB and make sure that the model you're trying to query/mutate has a table in the database.

If not, you can try clearing IndexedDB either manually through the dev tools, or with `DataStore.clear`. Then, call `DataStore.start` from your app to initiate the sync process so that IndexedDB is populated with the tables for each model in your schema.

**Comment by matart15** [comment]
Since https://github.com/aws-amplify/amplify-js/issues/9631#issuecomment-1058150131 is solved, closing this issue
