### ISSUE TITLE
Event is not accepted, the error is Event attribute key length should be less than 50.

### ISSUE THREAD

**Issue by nikhilgupta46** [aws-amplify/amplify-js#9665]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

Create React App 

### Please describe your bug.

Getting this event response error being logged onto my Sentry dashboard to catch user error's 

[ERROR] 24:40.508 AWSPinpointProvider - Event c44f3e31-9a0e-11ec-9c1e-fb6f2df2fead is not accepted, the error is Event attribute key length should be less than 50.
{
arguments: [
[ERROR] 24:40.508 AWSPinpointProvider - Event c44f3e31-9a0e-11ec-9c1e-fb6f2df2fead is not accepted, the error is Event attribute key length should be less than 50.
], 
logger: console

Even after going through all the keys and values didn't get whoch is the point of origin for this issue. Since , all keys are less than 50 in my react app

### What's the expected behaviour?

Getting to know the origin of this issue to and why it is happening in very large number's i.e. thousands user's / events being affected

### Help us reproduce the bug!

const eventType = { name: event, attributes: attribute };
  Analytics.record(eventType);
In this the attribute is an object which has key value pair's . So keep one key of attribute to be of length >50 it iwll be replicated but why is it happening for length <50 is not known

### Code Snippet

```typescript
// Put your code below this line.

```
const eventType = { name: event, attributes: attribute };
  Analytics.record(eventType);

### Additional information and screenshots

check above

**Comment by nikhilgupta46** [comment]
any updates ? over the above issue

**Comment by chrisbonifacio** [comment]
Hi @nikhilgupta46 👋 thanks for raising this issue. Can you give an example of what your `attribute` object might look like?

I was only to reproduce this error if I purposely made an attribute key more than 50 characters.

```js
const recordEvent = async () => {
    const stringOfChars = "a".repeat(50); // event accepted with 50 chars, rejected with 51

    try {
      const eventType = {
        name: "test-event",
        attributes: {
          [stringOfChars]: "test-attribute",
        },
      };
      const res = await Analytics.record(eventType);

      console.log({ res });
    } catch (error) {
      console.error(error);
    }
  };
```

Event MetaData
<img width="654" alt="Screen Shot 2022-03-03 at 4 18 15 PM" src="https://user-images.githubusercontent.com/16952986/156654828-c08763de-1a1c-400b-b2bb-039b6dbf1fe2.png">

50 chars
<img width="654" alt="Screen Shot 2022-03-03 at 4 18 43 PM" src="https://user-images.githubusercontent.com/16952986/156654872-2e45a133-916f-4b57-a78f-5b79373479d1.png">

51+ chars

<img width="654" alt="Screen Shot 2022-03-03 at 4 18 26 PM" src="https://user-images.githubusercontent.com/16952986/156654899-bd85ca91-dc55-403c-91ee-102af81d3ad0.png">

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you. Thank you!
