### ISSUE TITLE
Report email_verified event in auth event channel

### ISSUE THREAD

**Issue by richmengsix** [aws-amplify/amplify-js#9668]
### On which framework/platform would you like to see this feature implemented?

React

### Which UI component is this feature-request for?

Authenticator

### Please describe your feature-request in detail.

I had been using the new [Authenticator UI](https://ui.docs.amplify.aws/components/authenticator) and having a blast. I had also been using Hub in conjunction to have my web app react based on auth state. 

However, I have been attempting to have my web app navigate to another web page after users finish the email validation flow. This became really difficult because there was no `email_validated` event built-in as part of the auth event channel. 

### Please describe a solution you'd like.

Adding such `email_validated` event or similar into Auth event streams would be really helpful in consolidating Hub usage. 

### We love contributors! Is this something you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request.
- [ ] ⚠️ This feature might incur a breaking change.

**Comment by ErikCH** [comment]
This ticket has not been transferred to the JS repo since it deals with adding another Hub event to the Auth stream.

**Comment by chrisbonifacio** [comment]
@amehi0index

**Comment by amehi0index** [comment]
comment

**Comment by amehi0index** [comment]
Hi @richmengsix, 

Have you had the opportunity to check out the [documentation]( https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#override-function-calls) on function calls to override default behaviors and/or [hiding the sign up UI](https://aws.amazon.com/blogs/mobile/8-new-features-in-the-amplify-authenticator-for-web-you-should-try/)? If not, please have a look and let me know if these features would work for your particular use case.

**Override default behavior:**
```
import { Amplify, Auth } from 'aws-amplify';
import { Authenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';
import awsExports from './aws-exports';
Amplify.configure(awsExports);

export default function AuthenticatorWithEmail() {
  const services = {
    async handleSignUp(formData) {
      let { username, password, attributes } = formData;
      // custom username
      username = username.toLowerCase();
      attributes.email = attributes.email.toLowerCase();
      return Auth.signUp({
        username,
        password,
        attributes,
      });
    },
  };

  return (
    <Authenticator services={services} initialState="signUp">
      {({ signOut }) => <button onClick={signOut}>Sign out</button>}
    </Authenticator>
  );
}
```
**Hide Sign-up UI:**
```
export default function App() {
  return (
    <Authenticator
      hideSignUp={true}
    >
      {({ signOut }) => <button onClick={signOut}>Sign out</button>}
    </Authenticator>
  );
}
```

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
