### ISSUE TITLE
React Native Storage.put Axios Network Error

### ISSUE THREAD

**Issue by NiksanJP** [aws-amplify/amplify-js#9681]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Storage

### Amplify Categories

storage

### Environment information

<details>

```
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 8.45 GB / 15.96 GB
  Binaries:
    Node: 14.15.0 - D:\Node\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - D:\Node\npm.CMD
  Browsers:
    Chrome: 87.0.4280.66
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    @aws-amplify/ui-react: ^2.9.0 => 2.9.0
    @aws-amplify/ui-react-internal:  undefined ()
    @aws-amplify/ui-react-legacy:  undefined ()
    @babel/core: ^7.17.5 => 7.17.5
    @react-native-async-storage/async-storage: ^1.16.1 => 1.16.1
    @react-native-community/masked-view: ^0.1.11 => 0.1.11
    @react-native-community/netinfo: ^7.1.12 => 7.1.12
    @react-native-picker/picker: ^2.3.1 => 2.3.1
    @react-navigation/bottom-tabs: ^6.2.0 => 6.2.0
    @react-navigation/material-bottom-tabs: ^6.1.1 => 6.1.1
    @react-navigation/native: ^6.0.8 => 6.0.8
    @react-navigation/stack: ^6.1.1 => 6.1.1
    HelloWorld:  0.0.1
    aws-amplify: ^4.3.15 => 4.3.15
    aws-amplify-react-native: ^6.0.3 => 6.0.3
    expo: ~43.0.2 => 43.0.5
    expo-image-picker: ~11.0.3 => 11.0.3
    expo-status-bar: ~1.1.0 => 1.1.0
    hermes-inspector-msggen:  1.0.0
    react: 17.0.1 => 17.0.1
    react-dom: 17.0.1 => 17.0.1
    react-native: 0.64.3 => 0.64.3
    react-native-gesture-handler: ^2.3.0 => 2.3.0
    react-native-paper: ^4.11.1 => 4.11.1
    react-native-safe-area-context: ^3.4.1 => 3.4.1
    react-native-screens: ^3.13.1 => 3.13.1
    react-native-table-component: ^1.2.2 => 1.2.2
    react-native-web: 0.17.1 => 0.17.1
  npmGlobalPackages:
    @aws-amplify/cli: 7.6.22
    bit-bin: 14.8.8
    bower: 1.8.8
    electron: 6.0.1
    expo-cli: 5.0.3
    firebase-tools: 9.3.0
    npm-check-updates: 12.0.3
    react-scripts: 4.0.1
    serve: 11.3.2
    yarn: 1.22.10


```

</details>

### Describe the bug

So I want to upload a text file or image file to my bucket which has everything set up.

Code
```
try {
            const response = await fetch(image[0]);
            const blob = await response.blob();
            await Storage.put("yourKeyHere", blob, {
                contentType: "image/jpeg", 
            });
        } catch (err) {
            console.log("Error uploading file:", err);
        }
```

This is just a demo code where I try to upload it to my bucket but I get this error.
![image](https://user-images.githubusercontent.com/40626274/157390350-c310728b-b3ab-4994-9428-d17ec367e450.png)
![image](https://user-images.githubusercontent.com/40626274/157390902-10a54c5c-0ac9-4fff-8b08-e8a70b382111.png)

I also have tried other code
```
await Storage.put("test.txt", "Hello")
        .catch(err => {
            console.log(err);
        });;
```
Which return the same error for everything.

### Expected behavior

It should upload to the bucket without any errors returned.

### Reproduction steps

1. Use Expo image picker to select an image
2. Store that image to a list
3. use Storage.put to upload that image
4. Get that error
5. CRY

### Code Snippet

```javascript
await Storage.put("test.txt", "Hello")
        .catch(err => {
            console.log(err);
        });;
        console.log(image)
       

 try {
            const response = await fetch(image[0]);
            const blob = await response.blob();
            await Storage.put("yourKeyHere", blob, {
                contentType: "image/jpeg", 
            });
        } catch (err) {
            console.log("Error uploading file:", err);
        }

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

const awsmobile = {
    "aws_project_region": "ap-xxxxx-1",
    "aws_cognito_identity_pool_id": "ap-southeast-xxxxxxxxxxxxxxxxx",
    "aws_cognito_identity_pool_region": "ap-xxxxxxxxx-2",
    "aws_cognito_region": "ap-xxxxxxxxxx-3",
    "aws_user_pools_id": "ap-xxxxxxxxxxxxx",
    "aws_user_pools_web_client_id": "xxxxxxxxxxxxxxxxxxxxxxxx",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "NAME",
        "EMAIL",
        "GENDER",
        "BIRTHDATE",
        "PHONE_NUMBER",
        "ADDRESS"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "xxxxxxxx-storage-xxxxxxxxxxxxxxxxx-dev",
    "aws_user_files_s3_bucket_region": "ap-xxxxxxxxxxxx-4"
};

### Manual configuration

Amplify.configure({
    Storage: {
        AWSS3: {
            bucket: 'xxxxxxxxxxxxxxx-storage-xxxxxxxxxxxxxxxxxxxxxxx-dev', //REQUIRED -  Amazon S3 bucket name
            region: 'ap-xxxxxxxxxxxxxx-1', //OPTIONAL -  Amazon service region
        }
    },
	Auth: {
        identityPoolId: 'ap-southeast-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
		identityPoolRegion: 'ap-xxxxxxxxxxxxxxxxxxxxxx-2',
        region: 'us-eat-1',
		userPoolId: 'ap-xxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxx',
		userPoolWebClientId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    },
	Analytics: {
		disabled: true,
	},
});

### Mobile Device

Android and Web

**Comment by NiksanJP** [comment]
Another React Native Error
![image](https://user-images.githubusercontent.com/40626274/158010013-51b25bc3-802e-4798-aae8-2d8637d45555.png)
Error
![image](https://user-images.githubusercontent.com/40626274/158010057-4c413081-da6d-4c8c-9f69-ad97d02c7f02.png)

**Comment by NiksanJP** [comment]
The datastore Session ID is also missing
![image](https://user-images.githubusercontent.com/40626274/158010853-1321f03e-6388-420b-9f15-c867903935e9.png)
![image](https://user-images.githubusercontent.com/40626274/158010859-ef0247be-b7d7-462f-9c88-f8e3f3bb5fe2.png)

**Comment by stocaaro** [comment]
There's a lot going on here. If you are seeing unrelated issues, I would recommend opening separate issues to keep it clear which issue the discussion is regarding.  Looking at your storage errors, it appears that your manual config is pointed at a misspelled region name `region: 'us-eat-1'`. Can you fix this and let us know if the error you're seeing is still happening?

Thanks,
Aaron

**Comment by stocaaro** [comment]
From the original, my best guess is that fixing the region as suggested would resolve the initial issue.  The auth region is pretty core, so my best guess is that this would resolve some of the other issues, but without more detail on what you see after this fix, I'll close this for now. Please reopen it with more feedback when you able.

Thanks!
Aaron

**Comment by ferrero1987** [comment]
i also have the same errors! 
Mistaking the bucket or region name on purpose I would not want to see a blocking error but I expect it is handled in the catch
