### ISSUE TITLE
DataStore creating mutations for connected records on update/create

### ISSUE THREAD

**Issue by sacrampton** [aws-amplify/amplify-js#9701]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

DataStore

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line
npx: installed 1 in 1.725s

  System:
    OS: Linux 4.14 Amazon Linux 2
    CPU: (2) x64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
    Memory: 6.41 GB / 7.79 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 10.23.2 - ~/.nvm/versions/node/v10.23.2/bin/node
    npm: 6.14.10 - ~/.nvm/versions/node/v10.23.2/bin/npm
  npmGlobalPackages:
    @aws-amplify/cli: 6.3.1
    cdk: 1.87.1
    coffeescript: 2.5.1
    esformatter: 0.11.3
    js-beautify: 1.13.5
    npm: 6.14.10
    prettier: 2.2.1
    typescript: 3.7.5

```

</details>

### Describe the bug

After a significant amount of time working with @iartemiev we have identified an issue that has significant implications for the sync of mutations from the mobile device to the server.

Let's say I have a user object and it is connected to an Asset object and a Package object as shown here
```
query userObject {
  getUser(id: "4fb6d568-a999-4c99-a999-47c28219bff6") {
    id
    asset {
      id
      name
    }
    package {
      id
      name
    }
  }
}
```
This returns the following data from the connected objects.
```
{
  "data": {
    "getUser": {
      "id": "4fb6d568-a999-4c99-a999-47c28219bff6",
      "asset": {
        "id": "6cc57a52-12a2-4ba8-b8bb-16cb43501d37",
        "name": "STEST20"
      },
      "package": {
        "id": "fa3887a9-3f65-4c35-a76c-192a0b51b6a6",
        "name": "STEST20"
      }
    }
  }
}

```

Now if I update the user record what we are finding is that DataStore will issue additional mutations to create an asset and package object (the connected records) and both will fail because we are not specifying mandatory fields in the asset & package object "Variable 'input' has coerced Null value for NonNull type 'ID!'" - and of course these record already exist and would fail for that reason as well.

Package
<img width="1057" alt="packageMutationError" src="https://user-images.githubusercontent.com/6362888/158273451-8c188950-38a9-4541-93d8-b0c454c983eb.png">
Asset
<img width="1050" alt="assetMutationError" src="https://user-images.githubusercontent.com/6362888/158273455-beac4d10-5831-4163-b316-73ef9f41b5fa.png">

But then this create an Error in the mutation queue and all subsequent mutations are ENQUEUED and never move to the server. The sync engine is effectively stopped.

This stands out for example because we NEVER create a Package record in the mobile app - all Package records are created in the back end and synced to the mobile. So this was our confusion when we started seeing DataStore Mutation Errors appearing related to Package creation on the mobile?

### Expected behavior

I expect that I can update an object (ie. user) and that no mutation of any type is attempted on any connected record.

### Reproduction steps

See above.

We are still looking into the circumstances when this is triggered as it doesn't appear to happen for all records that have connections.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @sacrampton 👋 thanks for raising this issue. Can you share the schema just enough to show the type of relationships between the User and an Asset and/or Package models?

**Comment by sacrampton** [comment]
Hi @chrisbonifacio - hope the cut down schema below is helpful. By the way, the User object and the Package object are never created by our Mobile App (DataStore). We do update the User object and we are seeing invalid Package  & Asset creation mutations.

The User model has the Asset ID and Name - however the Asset also has assetOperatingUnitId as a mandatory field and that is not in the User table -  we are seeing the create Asset mutation trying to just create with id & name and it fails because the other mandatory fields are not there. If that was not the case it would also fail because the record already exists. Aside from the fact, none of these connected objects should ever trigger a mutation on update of another object.

Hope that helps.

Regards,

Stephen
```
type User @model @searchable
  @key(name: "byUserAssetId", fields: ["userAssetId"]) 
  @key(name: "byUserPackageId", fields: ["userPackageId"])   
  @auth(rules: [ {allow: groups, groups: ["XXXX"], operations: [create,update,delete,read]}])
{
  id: ID!
  name: String!
  asset: Asset @connection (fields: ["userAssetId"])
  userAssetId: ID  
  assetName: String
  package: Package @connection (fields: ["userPackageId"])
  userPackageId: ID
  packageName: String
}

type Asset @model @searchable 
  @key(name: "byAssetPackageId", fields: ["assetPackageId"]) 
  @key(name: "byAssetOperatingUnitId", fields: ["assetOperatingUnitId"]) 
  @auth(rules: [{allow: groups, groups: ["XXXX"], operations: [create, update, delete,read]}])
{
  id: ID!
  name: String!
  package: Package @connection (fields: ["assetPackageId"])
  assetPackageId: ID
  packageName: String
  user: [User] @connection (keyName: "byUserAssetId", fields: ["id"])
  operatingUnit: OperatingUnit @connection (fields: ["assetOperatingUnitId"])
  assetOperatingUnitId: ID!
  operatingUnitName: String
}

type Package @model @searchable 
  @key(name: "byPackageOperatingUnitId", fields: ["packageOperatingUnitId"]) 
  @auth(rules: [{allow: groups, groups: ["XXXX"], operations: [create,update,delete,read]}]}
{
  id: ID!
  name: String!
  operatingUnit: OperatingUnit @connection (fields: ["packageOperatingUnitId"])
  packageOperatingUnitId: ID!
  operatingUnitName: String
  asset: [Asset] @connection (keyName: "byAssetPackageId", fields: ["id"])
  user: [User] @connection (keyName: "byUserPackageId", fields: ["id"])
}

type OperatingUnit @model @searchable 
  @auth(rules: [{allow: groups, groups: ["XXXX"], operations: [create,update,delete,read]}]}
{
  id: ID!
  name: String!
  asset: [Asset] @connection (keyName: "byAssetOperatingUnitId", fields: ["id"])
  package: [Package] @connection (keyName: "byPackageOperatingUnitId", fields: ["id"])
}
```

**Comment by sacrampton** [comment]
@chrisbonifacio @iartemiev - we continue to investigate this. We have discovered a disturbing thing that is happening with DataStore during updates. Every time we do an update of the User table above DataStore is also performing an update of the connected Package & Asset tables. This should not be happening and offers opportunities for corrupting data. If we want to update the Asset and the Package records then we will do so with an update of those records - but our investigation is showing these updates of connected Models are being auto generated on update.

Our working hypothesis at the moment is that if there is a conflict on update then DataStore is does not update the connected records but tries to create them and that is the error we are seeing that is blocking the sync queue. However, if DataStore was not issuing update mutations on connected models then these invalid create mutations would not be getting created - so if our hypothesis is correct then that is the root cause of the issue.

**Comment by manueliglesias** [comment]
Hi @sacrampton 

I tried to reproduce your issue in the [manueliglesias/sacrampton-gh-9701 repo](https://github.com/manueliglesias/sacrampton-gh-9701) (I tested it on web, not on react native, the sync pieces and protocol is the same for all platforms) and couldn't get the behavior you are seeing.

> Every time we do an update of the User table above DataStore is also performing an update of the connected Package & Asset tables.

I used a [simplified version of your schema](https://github.com/manueliglesias/sacrampton-gh-9701/blob/738db1de84d42f44d6a9bd9cee79786eb8e77c10/schema.graphql) and this is how I am doing the save on a `User` model:

https://github.com/manueliglesias/sacrampton-gh-9701/blob/738db1de84d42f44d6a9bd9cee79786eb8e77c10/src/App.tsx#L49-L57

Can you share a minimal repro of a failing save?

> Our working hypothesis at the moment is that if there is a conflict on update then DataStore is does not update the connected records but tries to create them

What do you mean by conflict in this context? Is it a failed mutation with a GraphQL response of ` “errorType”: “ConflictUnhandled”` ?

I also noticed you shared this in your comment:

```graphql
query userObject {
  getUser(id: "4fb6d568-a999-4c99-a999-47c28219bff6") {
    id
    asset {
      id
      name
    }
    package {
      id
      name
    }
  }
}
```

That is not a query that DataStore invokes, DataStore gets items to the device by invoking the `syncXXX` queries (where `XXX` is a model)

Are you invoking GraphQL directly in your app?

**Comment by sacrampton** [comment]
Thanks @manueliglesias 

We are not using GraphQL in our App. The guys have included some screen shots of the connected mutations that we are seeing in DataStore.

[AssetMutations.zip](https://github.com/aws-amplify/amplify-js/files/8283385/AssetMutations.zip)
[UserMutations.zip](https://github.com/aws-amplify/amplify-js/files/8283388/UserMutations.zip)

**Comment by sacrampton** [comment]
This has been resolved
