### ISSUE TITLE
TypeError: cannot read property 'USER_ID_FOR_SRP' of undefined

### ISSUE THREAD

**Issue by s1mrankaur** [aws-amplify/amplify-js#9720]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

Running into 

`TypeError: cannot read property 'USER_ID_FOR_SRP' of undefined
`
when running the cypress test suite. After Cypress logs out the user and tries to login again, I get:
 
`TypeError: cannot read property 'USER_ID_FOR_SRP' of undefined` from **Auth.SignIn(username, password)**

This happens only when Cypress tries to login though. Not able to get the same error when manually logging in.

### Expected behavior

Auth.SignIn should be able to log in the user without any errors

### Reproduction steps

1.  Trigger Login using Cypress
2. Logout
3. Login again

### Log output

<details>

```
// Put your logs below this line
TypeError: cannot read property 'USER_ID_FOR_SRP' of undefined 

```

</details>

**Comment by chrisbonifacio** [comment]
@s1mrankaur thank you for the quick response! I think I should be able to reproduce in that case. Just to clarify, are you using the Amplify UI Library's Authenticator component or did you write you own custom login form?

**Comment by s1mrankaur** [comment]
@chrisbonifacio Thanks for your response. We are using the in-built method as described here https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js/#sign-in

**Comment by chrisbonifacio** [comment]
@s1mrankaur apologies for the delay here. Are you still running into this issue by chance? I've used Cypress before with a custom command to login via Cognito but haven't run into this error yet.

This is my command for reference:

```js
// Amazon Cognito
Cypress.Commands.add("loginByCognitoApi", async (username, password) => {
  const log = Cypress.log({
    displayName: "COGNITO LOGIN",
    message: [`🔐 Authenticating | ${username}`],
    autoEnd: false,
  });

  log.snapshot("before");

  const cognitoResponse = await Auth.signIn({ username, password });

  const keyPrefixWithUsername = `${cognitoResponse.keyPrefix}.${cognitoResponse.username}`;

  window.localStorage.setItem(
    `${keyPrefixWithUsername}.idToken`,
    cognitoResponse.signInUserSession.idToken.jwtToken
  );

  window.localStorage.setItem(
    `${keyPrefixWithUsername}.accessToken`,
    cognitoResponse.signInUserSession.accessToken.jwtToken
  );

  window.localStorage.setItem(
    `${keyPrefixWithUsername}.refreshToken`,
    cognitoResponse.signInUserSession.refreshToken.token
  );

  window.localStorage.setItem(
    `${keyPrefixWithUsername}.clockDrift`,
    cognitoResponse.signInUserSession.clockDrift
  );

  window.localStorage.setItem(
    `${cognitoResponse.keyPrefix}.LastAuthUser`,
    cognitoResponse.username
  );

  window.localStorage.setItem("amplify-authenticator-authState", "signedIn");
  log.snapshot("after");
  log.end();
});
```

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
