### ISSUE TITLE
Amplify cognito signin function is not working on production but works on local

### ISSUE THREAD

**Issue by abdeleo17** [aws-amplify/amplify-js#9721]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Authentication

### Amplify Categories

auth

### Describe the bug

Auth.signIn() function is not even getting triggered on production but works perfectly on local env. I am using @aws-amplify/auth and @aws-amplify/core packages and updated the latest version but still throwing the same error.

**Comment by chrisbonifacio** [comment]
Hi @abdeleo17 👋 thanks for raising this issue. I might need some more information to figure out why you're experiencing this issue.

1. Can you please share the contents of your `package.json` file?

2. Can you please share any instances of `Amplify.configure` or `Auth.configure` in your code?

3. Please also add this line where you are configuring Amplify and/or Auth and share the logs, might show us some useful info as to why the login is failing.

```js
Amplify.Logger.LOG_LEVEL = "DEBUG";
```

**Comment by kgoyal98** [comment]
I am facing the same issue too.

**Comment by kgoyal98** [comment]
@chrisbonifacio any updates on this?

**Comment by chrisbonifacio** [comment]
@kgoyal98 can you add the line of code I mentioned in my previous comment to your app (right before Amplify.configure) and share the console logs? Might be able to tell us why the signin isn't working.

**Comment by kgoyal98** [comment]
On localhost, both Facebook and username/password are working.
On production (i.e. live hosted app) Facebook is not working but username/password is working.

**Comment by PGuimarais** [comment]
@chrisbonifacio Getting the same error over here with Nextjs in a production build using Google OAuth.

I'm successfully routed to the Google signin page, and on the redirect, Amplify Hub does not appear to be receiving any auth events on the frontend - although the user is created in Cognito and all the auth triggers are called and work fine. 

After setting LOG_LEVEL `Amplify.Logger.LOG_LEVEL = "DEBUG";` I'm getting the following logs repeating.

```
[DEBUG] 16:26.877 AuthClass - Getting current session
_app-0e8cd9095f5c42fc.js:1 [DEBUG] 16:26.878 AuthClass - Failed to get user from user pool
_app-0e8cd9095f5c42fc.js:1 [DEBUG] 16:26.878 AuthClass - Failed to get the current user No current user
```

**Comment by chrisbonifacio** [comment]
could you run `amplify env list` and share the output?

**Comment by kgoyal98** [comment]
```
$ amplify env list

| Environments |
| ------------ |
| *staging     |

```

These are my FB login settings - 
![image](https://user-images.githubusercontent.com/32641543/164279673-e192ab41-2442-4295-ba7d-0daadaf9abb2.png)

**Comment by kgoyal98** [comment]
@chrisbonifacio Any updates on this?

**Comment by chrisbonifacio** [comment]
Hi @kgoyal98 it looks like your production Allowed Domain might be incorrect. It should be the same URI but without the `/oauth2/idpresponse` paths.

For example, these are my settings on a similar project with Facebook Login.

<img width="943" alt="Screen Shot 2022-05-10 at 12 48 28 PM" src="https://user-images.githubusercontent.com/16952986/167681160-150532a5-6d59-4d8d-83f8-52f0d8d7eb2a.png">

Try removing that path and let me know if the issue persists.

**Comment by kgoyal98** [comment]
@chrisbonifacio If this was the issue, it would not work locally too.

Still I did what you suggested and getting the same issue.

![image](https://user-images.githubusercontent.com/32641543/167686517-7bccde36-61dc-4abf-9de3-2d1559942abe.png)

**Comment by chrisbonifacio** [comment]
An update here. For @kgoyal98, the issue had to do with their rewrite and redirect rules.

```js
{
        "source": "https://telebuff.in",
        "target": "https://www.telebuff.in",
        "status": "302",
        "condition": null
    },
    ```
    
    Changing status from 302 to 200 fixed the issue.

**Comment by sachsom95** [comment]
This seems to have solved my issue as well. I am using google with web application. This might needed to be noted down in amplify docs somewhere as a gotcha for people developing SPA. However I will not push this to production without analysing the full implications or issues arising from using a 200 instead of 302 redirect

**Comment by kmallari** [comment]
> An update here. For @kgoyal98, the issue had to do with their rewrite and redirect rules.
> 
> ```diff
> {
>     "source": "https://telebuff.in",
>     "target": "https://www.telebuff.in",
> -   "status": "302",
> +   "status: "200",
>     "condition": null
> }
> ```
> 
> Changing status from 302 to 200 fixed the issue.
> 
> Closing this as we have not heard back from the original commenter. If anyone else is experiencing this issue and the solution mentioned above does not work, please create a new issue with the details of your Amplify configuration, Auth code usage, and environment information. Thank you!

Hello, I'm current experiencing this issue and am very new to Amplify. I'm confused where there rewrite and redirect rules were configured since OP did not mention these in any of their posts?

**Comment by kmallari** [comment]
I found how you change the redirect rules in the Amplify management console.
However, I'm curious why changing the status from 302 to 200 fixes this issue?

**Comment by tannerabread** [comment]
@kmallari I wasn't the one that worked on this issue originally so this is my best guess, but the 302 code is a [temporary redirect](https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html) which might break the oauth flow. Cognito redirects back to the app once with a code to exchange for credentials but another redirect (302) changes the request location and then that code is lost

**Comment by gstaykov** [comment]
I'm experiencing the same problem with the latest version `"aws-amplify": "^6.0.13"`. How did you resolve this ?

**Comment by nadetastic** [comment]
Hi @gstaykov do you mind opening a new bug report to better investigate your issue?

https://github.com/aws-amplify/amplify-js/issues/new/choose

**Comment by gstaykov** [comment]
@nadetastic done: https://github.com/aws-amplify/amplify-js/issues/12927
