### ISSUE TITLE
@key on non-unique column causes sync issues between datastore and appsync

### ISSUE THREAD

**Issue by alharris-at** [aws-amplify/amplify-js#9725]
Even key field does not ensure uniqueness. I have following and duplicate email accepted even though I have indicated that as key. Worse part is that the backend corresponding dynamo table does not seem to take the duplicate record. So now, my client side sqlite is out of sync with dynamoDB. So I have to write code to check if the record exists..Sounds ugly unless someone can enlighten me please..

type AddUserToT
  @model
  @key(fields: ["userEmail"])
  id: ID!
  email: ID!

_Originally posted by @droidgeek1 in aws-amplify/amplify-category-api#286

We expect the current behavior here is such that datastore will accept the record with a non-unique `userEmail` in this case, but appsync will fail uniqueness constraints. Datastore will attempt to sync a few times, then switch to an offline mode, and the app local store will need to be cleared in order to move forward.

**Comment by iartemiev** [comment]
This is implemented in CPK
