### ISSUE TITLE
How can we force sync without Datastore.clear

### ISSUE THREAD

**Issue by teenahjob** [aws-amplify/amplify-js#9727]
### Is this related to a new or existing framework?

Angular

### Is this related to a new or existing API?

DataStore

### Describe the feature you'd like to request

How can we force sync without datastore.clear and changing the sync interval? 

### Describe the solution you'd like

Datastore.sync(Force) ->  force syncs from dyanamo DB 
This is needed because there can be different system changing the DB. And there should be some way the change in DB can be sync with the local storage.  

### Describe alternatives you've considered

Listed solution above

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by david-mcafee** [comment]
Hi @teenahjob, thanks for starting this discussion! It sounds like you are requesting that DataStore expose a function to perform a _full_ sync, not just a delta sync. Can you help us understand why `DataStore.clear` and / or changing the sync interval isn't a viable solution? Is there an issue with the delta sync that perhaps we're not aware of? If we could understand your use-case, we could help provide a better answer - I know you had mentioned something regarding "different systems changing the DB", but I was unclear about what you meant. Could you provide more explanation? Thank you!

**Comment by david-mcafee** [comment]
Also wanted to clarify that in the event you _do_ want to perform a full sync, you could execute the following:

```
async function fullSync() {
  await DataStore.clear();
  await DataStore.start();
}
```

**Comment by teenahjob** [comment]
It can happen that a user has saved a datapoint on his amplify storage and dynamo DB table through sync from a mobile device and a background process that runs on the server at 2 pm in the afternoon updates that data point in the dynamo DB table. 

I will ideally want to refresh the datapoint which is changed and sync it to local. How can that be done?

I do not want to do Datastore.clear(), because it clears the entire datastore and tries to sync all data again. which is not efficient and cost-effective.

**Comment by teenahjob** [comment]
I found another way of acheiving this
