### ISSUE TITLE
DataStore "IndexedDB not supported in this browser's private mode" error in Chrome 99

### ISSUE THREAD

**Issue by aspittel** [aws-amplify/amplify-js#9728]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Environment information

 Chrome: 99.0.4844.83

### Describe the bug

When you use DataStore in Chrome 99, there's an error: "IndexedDB not supported in this browser's private mode"

### Expected behavior

DataStore should sync!

### Reproduction steps

- Go to the `content` tab in studio
- Add DataStore to your app

### Additional information and screenshots

Follow this blog post in order to fix the issue - https://mrcoles.com/how-reset-your-chrome-quotamanager-database/ 

Note, this is an error with Chrome, not DataStore itself but it manifests as a DataStore error.

**Comment by david-mcafee** [comment]
Here's [a link to the Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1303434#c28), along with mitigation guidance. Seeing if I can reproduce this locally myself.

**Comment by nickarocho** [comment]
Taking a look to try and reproduce as well.

**Comment by BillyLuisNeedham** [comment]
@aspittel did you ever resolve this? I am also experiencing this

**Comment by chrisbonifacio** [comment]
Hi @BillyLuisNeedham 👋 

Are you able to reproduce this consistently? If so, would you mind commenting here with reproduction steps or a link to your repo if public? 

This has been very difficult for us to reproduce when it first happened so I'm curious what version of chrome you might be on, if this occurs in any other browser, what DataStore operation is attempting to run, etc.

**Comment by BillyLuisNeedham** [comment]
Hi @chrisbonifacio 

This is now consistently occurring for me as of maybe yesterday. Previously no issue. 

I built this whole project using Brave browser to run the code in, no issue. As of yesterday everyone that was using any Windows Chromium browser seemed to get the issue. Using Edge or Safari there was no issue. Using brave browser on an Android phone there is no issue. Using Chromium browsers on MacOS no issue.

The repo is not public, apologies.

For me to reproduce all I have to do is:
- Be on Windows 
- Run local host (also occurs on hosted sites with https)
- Be in a Chromium browser (I'm using Brave, also occurs on Chrome)
- Requests any data from DataStore
- See error

**Comment by BillyLuisNeedham** [comment]
@chrisbonifacio there has been an interesting development.

On Windows Chrome has all of a sudden started to work. At the time of writing, Brave Browser still has not.

**Comment by dbanksdesign** [comment]
I am experiencing this now on Mac Chrome Version 114.0.5735.133 (Official Build) (arm64)

**Comment by trey-rosius** [comment]
this bug is still in wild. Mac Chrome Version Version 135.0.7049.97 (Official Build) (arm64)
