### ISSUE TITLE
Feature Request: All script auto-generated by aws-amplify in ES6

### ISSUE THREAD

**Issue by michaelcuneo** [aws-amplify/amplify-js#973]
Do you want to request a feature or report a bug?

**Feature.**

What is the current behavior?

All JS pulled in from awsmobile to the project is in ES5 format.
Could it be changed to ES6? Why isn't it ES6 already?

**Comment by kaustavghosh06** [comment]
Hey Michael,
Which script are you specifically referring to? Could you provide a sample?

**Comment by michaelcuneo** [comment]
Hey Kaustavghosh06 ... I've gone and posted this into the wrong GitHub account. I was intending to request this feature from awsmobile-cli, can delete now. Sorry.

**Comment by jordanranz** [comment]
Closing this issue as advised above.
