### ISSUE TITLE
Get session returns error : Access Token has expired

### ISSUE THREAD

**Issue by stripathix** [aws-amplify/amplify-js#974]
Do you want to request a feature or report a bug?
Bug
What is the current behavior?
In some case on trying to get session aws Cognito return **Access Token has expired**. We have configured refresh token expiry days as 3650. So even if access token has expired we can refresh users Access token by using refresh token.

So to get refresh token I do cognitoUser.getSession() but this is returning response **Access Token has expired** due to some reason.

`{
code: NotAuthorizedException, 
emailTried: j********@gmail.com, 
message: User j********@gmail.com : Access Token has expired, 
name: NotAuthorizedException
}`

Logic to refresh existing session:
https://gist.github.com/stripathix/0f68b3a81379f39a80c8860cbf37a2aa

What is the expected behavior?
Should give me old session from which I can get refresh token.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
"amazon-cognito-identity-js": "2.0.6",
"amazon-cognito-js": "1.1.0",

Not able to reproduce it but it does get logged a lot of time on error logger.

**Comment by powerful23** [comment]
Can you describe those cases when you are not able to get the session? @yuntuowang any idea? I look through the code snippet which looks good to me.

**Comment by stripathix** [comment]
@powerful23 
**One case that I have noticed recently:**
When I use like some browser for ex:firefox and login into it. Now I leave it as logged in.

Now I use chrome to login again and keep using chrome for few days. Here I would do all kind of activities like refreshing my access token, logout, coginto sync etc.... No problem faced here.

Now If I return to firefox again after few days, throws this error in console. On returning to firefox getSession() should give me a refreshToken again which I can use to refresh access token.

Note:
My logout is pretty simple, It has nothing to do with expring refresh token or loggingout from all device:
https://gist.github.com/stripathix/de39bf3a527c05a14c4792df905baee7

**Comment by stripathix** [comment]
I mean why should getSession give me **Access Token Expired.** I just need refreshToken to refresh my access token. And as my refresh token does not expires in like 3650 days so it sounds right to get new access token easily.

 I think something not right with refresh token expiry days setting in aws cognito because few time I have also received:
`
{
code: NotAuthorizedException,
message: Invalid Refresh Token., 
name: NotAuthorizedException
}
`

**Comment by powerful23** [comment]
@stripathix will try to reproduce it.

**Comment by stripathix** [comment]
Hi @powerful23, any update on this?

**Comment by powerful23** [comment]
@stripathix I am trying to reproduce it like what you did, but for now it looks working for me.

**Comment by luisgurmendez** [comment]
Correct me if I'm wrong, but doesn't getSession automatically refreshes the accessToken?

https://github.com/aws/aws-amplify/blob/master/packages/amazon-cognito-identity-js/src/CognitoUser.js#L1160

**Comment by guanzo** [comment]
@luisgurmendez It "should". But I have a `setInterval` that calls `Auth.currentSession()` every 10 minutes, yet the access token always expires within an hour.

**Comment by leonachan1** [comment]
I manage our auth module that gets refreshed token calling https://xxx.auth.us-east-2.amazoncognito.com/oauth2/token. It worked well for over 6 months but now it keeps getting the expired token from cognito.

@stripathix did you already address out this issue?

**Comment by jordanranz** [comment]
@leonachan1, Does the accepted answer in this StackOverflow thread help?
https://stackoverflow.com/questions/48887594/how-to-restore-an-expired-token-aws-cognito

If not, could you elaborate on the implementation that is no longer working and what version of the package you are using? I can use this to escalate to the Cognito team.

**Comment by cazzer** [comment]
@jordanranz the StackOverflow answer is interesting and I will certainly explore it, but it leaves me a bit confused. I was under the impression that calling `await Auth.currentSession()` should handle refreshing tokens without any additional calls, assuming the refresh token is still valid.

I've set my application client's refresh token expiration to 10 years, as others in this thread have, to avoid such issues but am still getting a `Refresh Token has expired` error back from Cognito.

Please clarify if this is expected or not without explicitly checking if `AWS.config.credentials.needsRefresh()`, as suggested by the answer you linked.
