### ISSUE TITLE
S3 upload Error

### ISSUE THREAD

**Issue by supun19** [aws-amplify/amplify-js#975]
when upload pdf to s3 i got this error what would be the course??

Storage: {
    bucket: 'bucketname', // REQUIRED -  Amazon S3 bucket
    region: 'us-west-2', // OPTIONAL -  Amazon service region
  }
`<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>AuthorizationHeaderMalformed</Code>
<Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2'</Message>
<Region>us-west-2</Region>
<RequestId>43F7330B1F58227B</RequestId><HostId>EbC5J5EsHGhkBI5grmLvonpACoKVOT3aUS/ZREoYpOEo5QkpAOGlZe4QTCHCBXhGPt4Hz8qjVX4=</HostId></Error>`

**Comment by supun19** [comment]
when I make a public s3 bucket upload is working. do I need to set permission in cogntio to access bucket?. I am using serverless framework

**Comment by mattychen** [comment]
@supun19, yes you should set permissions in cognito. This can be achieved by adding a policy to your identity pools auth role.

**Comment by supun19** [comment]
thank you @mattychen

**Comment by jordanranz** [comment]
Closing this issue as it seems to have been solved. Please reopen if there are any related questions or concerns.
