### ISSUE TITLE
Unexpected "signIn" event when activating TOTP MFA with setPreferredMFA

### ISSUE THREAD

**Issue by agoldis** [aws-amplify/amplify-js#9750]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
npx envinfo --system --binaries --browsers --npmPackages --duplicates --npmGlobalPackages

  System:
    OS: macOS 11.6.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 115.53 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.3 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 7.3.0 - /usr/local/bin/npm
    Watchman: 2021.10.11.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 99.1.36.122
    Chrome: 99.0.4844.84
    Edge: 81.0.416.68
    Firefox: 98.0.2
    Safari: 15.2
  npmPackages:
    @types/node: ^16.3.1 => 16.11.21 
```

</details>

### Describe the bug

During successful activation of TOTP MFA `Auth.setPreferredMFA(user, 'TOTP');` triggers `signIn` event, while no sign-in happened.

### Expected behavior

No `signIn` event should **not** be emitted because user has already been signed in. TOTP MFA should be successfully activated.

### Reproduction steps

1. Enable Hub listener on `auth` channel
2. Enable MFA for a user
3. See the event

### Code Snippet

```ts
const listener: HubCallback = async (data) => {
      const payload = data.payload;
      console.log(payload.event);
}
Hub.listen('auth', listener);
```

```ts
const user = await Auth.currentAuthenticatedUser();
await Auth.verifyTotpToken(user, code);
await Auth.setPreferredMFA(user, 'TOTP');
```

### Log output

<details>

```text
ConsoleLogger.jss:139 [DEBUG] 51:30.780 AuthClass - associateSoftwareToken sucess MMXNTNPGKU4RSVBUPOZFP64TV74LY4RV3M2V7AVHP4OGUONZCJYQ
ConsoleLogger.jss:127 [DEBUG] 51:45.81 AuthClass - getting current authenticated user
ConsoleLogger.jss:127 [DEBUG] 51:45.82 AuthClass - get current authenticated userpool user
ConsoleLogger.jss:139 [DEBUG] 51:45.84 AuthClass - verification totp token 
(2) [CognitoUser, '965931']
ConsoleLogger.jss:139 [DEBUG] 51:45.379 Hub - Dispatching to auth with  
{event: 'signIn', data: CognitoUser, message: 'A user a039320d-af6f-41a8-b9c6-e4d74cb11889 has been signed in'}
ConsoleLogger.jss:139 [DEBUG] 51:45.380 Hub - Dispatching to auth with  
{event: 'signIn', data: CognitoUser, message: 'A user a039320d-af6f-41a8-b9c6-e4d74cb11889 has been signed in'}
ConsoleLogger.jss:127 [DEBUG] 51:45.380 AuthClass - getting current authenticated user
ConsoleLogger.jss:139 [DEBUG] 51:45.380 AuthClass - verifyTotpToken success 
{Status: 'SUCCESS'}
ConsoleLogger.jss:127 [DEBUG] 51:45.380 AuthClass - get current authenticated userpool user
ConsoleLogger.jss:139 [DEBUG] 51:45.935 Hub - Dispatching to auth with  
{event: 'tokenRefresh', data: undefined, message: 'New token retrieved'}
ConsoleLogger.jss:139 [DEBUG] 51:45.935 Hub - Dispatching to auth with  
{event: 'tokenRefresh', data: undefined, message: 'New token retrieved'}
ConsoleLogger.jss:127 [DEBUG] 51:45.936 AuthClass - getting current authenticated user
ConsoleLogger.jss:127 [DEBUG] 51:45.936 AuthClass - get current authenticated userpool user
ConsoleLogger.jss:139 [DEBUG] 51:46.201 AuthClass - Set user mfa success SUCCESS
ConsoleLogger.jss:127 [DEBUG] 51:46.201 AuthClass - Caching the latest user data into local
ConsoleLogger.jss:139 [DEBUG] 51:46.731 Hub - Dispatching to auth with  
{event: 'tokenRefresh', data: undefined, message: 'New token retrieved'}
ConsoleLogger.jss:139 [DEBUG] 51:46.731 Hub - Dispatching to auth with  
{event: 'tokenRefresh', data: undefined, message: 'New token retrieved'}
ConsoleLogger.jss:127 [DEBUG] 51:46.732 AuthClass - getting current authenticated user
ConsoleLogger.jss:127 [DEBUG] 51:46.732 AuthClass - get current authenticated userpool user
```

</details>

### Manual configuration

```ts
import { Amplify } from '@aws-amplify/core';
import { environment } from '@xxx';

const config = {
  Auth: {
    // REQUIRED - Amazon Cognito Region
    region: environment.COGNITO_REGION,

    // OPTIONAL - Amazon Cognito User Pool ID
    userPoolId: environment.COGNITO_USER_POOL_ID,

    // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
    userPoolWebClientId: environment.COGNITO_CLIENT_ID,

    // OPTIONAL - Enforce user authentication prior to accessing AWS resources or not
    mandatorySignIn: true,


    // OPTIONAL - Manually set the authentication flow type. Default is 'USER_SRP_AUTH'
    authenticationFlowType: 'USER_SRP_AUTH',
  },
  oauth: {
    redirectSignIn: environment.OAUTH_REDIRECT_SIGNIN,
    redirectSignOut: environment.OAUTH_REDIRECT_SIGNOUT,
    responseType: environment.OAUTH_RESPONSE_TYPE,
    domain: environment.OAUTH_DOMAIN,
  },
};

Amplify.configure(config);
```

**Comment by agoldis** [comment]
Thanks  for prompt reply @vyomr13. 

It is somewhat blocking  - my system is listening for `auth` events does certain actions on login - e.g. navigates to the root screen, sends analytic events etc. 

I can work around this,but having arbitrary events creates undesireable side effects, and, in general is incorrect.

**Comment by danielsharvey** [comment]
+1 I'm experiencing this as well

**Comment by KristianLake** [comment]
I can confirm this issue.

Auth.setPreferredMFA(user, 'TOTP'); without the following code in app.tsx

`
import { Hub } from 'aws-amplify';

const Listener = async (data: any): Promise<void> => {
    switch (data.payload.event) {
        case 'signIn':
            console.log('user signed in');
            break;
        case 'signUp':
            console.log('user signed up');
            break;
        case 'signOut':
            console.log('user signed out');
            break;
        case 'signIn_failure':
            console.log('user sign in failed');
            break;
        case 'tokenRefresh':
            console.log('token refresh succeeded');
            break;
        case 'tokenRefresh_failure':
            console.log('token refresh failed');
            break;
        case 'autoSignIn':
            console.log('Auto Sign In after Sign Up succeeded');
            break;
        case 'autoSignIn_failure':
            console.log('Auto Sign In after Sign Up failed');
            break;
        case 'configured':
            console.log('the Auth module is configured');
    }
};

Hub.listen('auth', Listener);
`
does not force a logout.

**Comment by KristianLake** [comment]
Auth.setPreferredMFA(user, 'TOTP'); will trigger the hub listener.

example in App.tsx (react app)

import { Hub } from 'aws-amplify';

const Listener = async (data: any): Promise<void> => {
    switch (data.payload.event) {
        case 'signIn':
            console.log('user signed in');
            break;
====
        case 'tokenRefresh_failure':
            console.log('token refresh failed'); <---- this section is triggered in your code.
            //     window.location.reload(); <--- can causes problems

            break;
====
    }
};

Hub.listen('auth', Listener);
====
...

check your listener isn't accidentally doing anything here

**Comment by MatthewChon** [comment]
bump

**Comment by abdallahshaban557** [comment]
This issue has now been addressed as part of this [PR](https://github.com/aws-amplify/amplify-js/pull/10511). The verifytotptoken() method will emit a 'verify' event instead of 'signIn'.
