### ISSUE TITLE
amplify add geo not working

### ISSUE THREAD

**Issue by jmohon1** [aws-amplify/amplify-js#9756]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Geo

### Amplify Categories

geo

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

When running the following command: "amplify add geo". I get the following error: "The Amplify CLI can NOT find command:  add geo"

### Expected behavior

Should install the dependency.

### Reproduction steps

installed amplify CLI (I have Auth and Storage already installed in the same project, within Visual Studio Code, I ran the command within my root folder.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Thanks for raising this issue! What version of the CLI are you using?

**Comment by jmohon1** [comment]
6.0.1

**Comment by jmohon1** [comment]
ahhh that was it, thank you!!
