### ISSUE TITLE
[Auth] Add support for group-based IAM role assignment

### ISSUE THREAD

**Issue by ffxsam** [aws-amplify/amplify-js#9759]
### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

The Authentication library should support assigning an IAM role based on the user's group(s), per https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-user-groups.html#assigning-iam-roles-to-groups.

It appears this isn't currently possible.

### Describe the solution you'd like

Authenticating should automatically assign the proper IAM role based on the user's groups (and group precedence).

### Describe alternatives you've considered

None that I'm aware of.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by abdallahshaban557** [comment]
Hi @ffxsam! Can you please elaborate a bit on the use case here? What are you trying to accomplish with assigning that IAM role?

**Comment by tannerabread** [comment]
Similar to #1125

**Comment by nadetastic** [comment]
After discussing this internally, I'll close this issue out in favor of tracking this request on #1125 as it doesn't seem to be much different from it.

Thanks!
