### ISSUE TITLE
Typescript compiler errors using AWS-Amplify in a custom app

### ISSUE THREAD

**Issue by fabiocbr75** [aws-amplify/amplify-js#976]
Hello,
I tried to convert my application from AppSyncSDK to Amplify but I have some compiler errors when I import it.
The errors are:

- node_modules/aws-amplify/lib/Cache/types/Cache.d.ts:38:15 - error TS2304: Cannot find name 'Storage'.
- node_modules/aws-amplify/lib/Cache/types/Cache.d.ts:39:13 - error TS2304: Cannot find name 'Cache'.
- node_modules/aws-amplify/lib/Common/RNComponents/index.d.ts:6:29 - error TS2304: Cannot find name 'Storage'.
- node_modules/aws-amplify/lib/Common/ServiceWorker/ServiceWorker.d.ts:23:29 - error TS2304: Cannot find name 'ServiceWorker'.
- node_modules/aws-amplify/lib/Common/StorageHelper/index.d.ts:2:30 - error TS2304: Cannot find name 'Storage'.

I tried to start from scratch with very simple program. The repro app include only 3 files

package.json:
```
{
  "name": "aws_amplify_test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@types/node": "^8.10.18",
    "aws-amplify": "0.4.4",
    "typescript": "^2.9.1"
  }
} 

```
tsconfig.json:
```
{
    "compilerOptions": {
        "module": "commonjs",
        "moduleResolution": "node",
        "target": "es6",
        "lib": [ "es6"],
        "sourceMap": true,
        "noImplicitAny": false,
        "outDir": "./dist/"
    },
  "include": [
    "./**/*"
  ],
  "exclude": [
    "node_modules",
    "./**/*.spec.ts"
  ]
}
```

app.ts:
```
import Amplify from 'aws-amplify';
console.log('Hello world');
```
   
When I run TSC compiler I retrieve the previous errors.
if It is my fault, could you provide a very simple typescript app with aws-amplify?

Repro in the zip file attached
[aws_amplify_test.zip](https://github.com/aws/aws-amplify/files/2069891/aws_amplify_test.zip)

**Comment by fabiocbr75** [comment]
I add a missing information. I want to use in a node application.

**Comment by vallyscode** [comment]
Just in case someone else has such problem in nodejs. Solution is to add "dom" to lib in tsconfig.json so that compiler can find definitions.

**Comment by danieladams456** [comment]
@vallyscode solution worked.  This issue should probably be marked as solved.

**Comment by jordanranz** [comment]
Closing as the solution is posted above. Please reopen if there are any further questions or concerns.

**Comment by HintikkaKimmo** [comment]
> Just in case someone else has such problem in nodejs. Solution is to add "dom" to lib in tsconfig.json so that compiler can find definitions.

This turned out to cause new issues in my environment. Having dom as lib trickered host of new errors in the newest version of React-Native typings.

**Comment by cinder92** [comment]
@HintikkaKimmo did you fixed, i have exact same issue

**Comment by nlindroos** [comment]
@jordanranz The answer [posted above](https://github.com/aws-amplify/amplify-js/issues/976#issuecomment-423061773) only works as a solution in some environments as pointed out by @HintikkaKimmo and the original issue is therefore not solved. `ServiceWorker` or `dom` is hardly available in a React Native app for example even if you would falsely tell the TS compiler that they are, as the supposed solution suggests.

**Comment by ws333** [comment]
I'm using Amplify with React Native and this helped me...

Add this to tsconfig:

  "compilerOptions": {
    "skipLibCheck": true
  },

**Comment by theneekz** [comment]
> I'm using Amplify with React Native and this helped me...
> 
> Add this to tsconfig:
> 
> ```
>   "compilerOptions": {
>     "skipLibCheck": true
>   },
> ```

I'm not sure ignoring all *.d.ts files is the best solution
