### ISSUE TITLE
Adding or updating existing user attributes in AWS Cognito

### ISSUE THREAD

**Issue by vymao** [aws-amplify/amplify-js#9762]
### Is this related to a new or existing framework?

React

### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

Not sure if this is currently possible (I didn't see any documentation about it), but it would be great if Amplify could support the possibility of users updating their Cognito attributes besides just the password. For example, if the user decides later after signing up to add their birthday, there ought to be a way to programatically add this information to the Cognito pool. As of now, it seems like all information needs to be inputted only at the sign in page. 

### Describe the solution you'd like

Have an API endpoint via `Auth` that allows applications to take user updates to Cognito information and add it to the Cognito pool.

### Describe alternatives you've considered

Have considered just storing this information in a separate database, but this is a hassle and requires additional resources. 

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by Samaritan1011001** [comment]
Hi @vymao, you should be able to use the `updateUserAttributes` function to update user details after `signup` and it's documented [here](https://docs.amplify.aws/guides/authentication/managing-user-attributes/q/platform/js/).

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
