### ISSUE TITLE
How to use cognito login without amplify on ReactNative

### ISSUE THREAD

**Issue by matart15** [aws-amplify/amplify-js#9764]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line


  System:
    OS: macOS 12.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 15.70 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
    Yarn: 1.22.18 - ~/.yvm/shim/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.3/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 99.0.4844.84
    Firefox: 98.0.2
    Safari: 15.3
  npmPackages:
    @babel/core: 7.17.4 => 7.17.4 (7.17.8)
    @eva-design/eva: 2.1.1 => 2.1.1 
    @expo/vector-icons: 12.0.0 => 12.0.0 (12.0.5)
    @react-native-async-storage/async-storage: 1.16.1 => 1.16.1 
    @react-native-community/eslint-config: 3.0.1 => 3.0.1 
    @react-native-community/netinfo: 7.1.3 => 7.1.3 
    @react-navigation/drawer: 6.3.1 => 6.3.1 
    @react-navigation/native: 6.0.2 => 6.0.2 
    @react-navigation/native-stack: 6.1.0 => 6.1.0 
    @types/jest: 27.4.0 => 27.4.0 
    @types/react: 17.0.39 => 17.0.39 (17.0.43)
    @types/react-native: 0.64.12 => 0.64.12 (0.67.3)
    @types/react-native-snap-carousel: 3.8.5 => 3.8.5 
    @typescript-eslint/eslint-plugin: 5.12.0 => 5.12.0 (4.33.0)
    @typescript-eslint/eslint-plugin-tslint: 5.12.0 => 5.12.0 
    @typescript-eslint/parser: 5.12.0 => 5.12.0 (4.33.0)
    @ui-kitten/components: 5.1.1 => 5.1.1 
    @ui-kitten/eva-icons: 5.1.1 => 5.1.1 
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: 5.2.6 => 5.2.6 
    babel-jest: 27.5.1 => 27.5.1 (26.6.3)
    eslint: 8.9.0 => 8.9.0 
    eslint-config-airbnb: 19.0.4 => 19.0.4 
    eslint-config-prettier: 8.3.0 => 8.3.0 (6.15.0)
    eslint-import-resolver-typescript: 2.5.0 => 2.5.0 
    eslint-plugin-autofix: 1.1.0 => 1.1.0 
    eslint-plugin-flowtype: 8.0.3 => 8.0.3 (2.50.3)
    eslint-plugin-graphql: 4.0.0 => 4.0.0 
    eslint-plugin-import: 2.25.4 => 2.25.4 
    eslint-plugin-prettier: 4.0.0 => 4.0.0 (3.1.2)
    eslint-plugin-react: 7.28.0 => 7.28.0 (7.29.4)
    eslint-plugin-react-native: 4.0.0 => 4.0.0 (3.11.0)
    eslint-plugin-simple-import-sort: 7.0.0 => 7.0.0 
    eslint-plugin-unused-imports: 2.0.0 => 2.0.0 
    expo: 44.0.0 => 44.0.0 
    expo-asset: 8.4.6 => 8.4.6 
    expo-constants: 13.0.1 => 13.0.1 (13.0.2)
    expo-dev-client: ~0.8.4 => 0.8.4 
    expo-font: 10.0.4 => 10.0.4 (10.0.5)
    expo-linking: 3.0.0 => 3.0.0 
    expo-secure-store: ~11.1.0 => 11.1.1 
    expo-splash-screen: 0.14.1 => 0.14.1 
    expo-status-bar: 1.2.0 => 1.2.0 
    expo-updates: ~0.11.6 => 0.11.6 
    expo-web-browser: 10.1.0 => 10.1.0 
    formik: 2.2.9 => 2.2.9 
    hermes-inspector-msggen:  1.0.0 
    husky: 7.0.4 => 7.0.4 
    jest: 26.6.3 => 26.6.3 
    jest-expo: 44.0.1 => 44.0.1 
    lint-staged: 12.3.4 => 12.3.4 
    react: 17.0.1 => 17.0.1 
    react-dom: 17.0.1 => 17.0.1 
    react-native: 0.64.3 => 0.64.3 
    react-native-fast-image: 8.5.11 => 8.5.11 
    react-native-gesture-handler: ~2.1.0 => 2.1.3 
    react-native-keyboard-aware-scroll-view: 0.9.5 => 0.9.5 
    react-native-linear-gradient: 2.5.6 => 2.5.6 
    react-native-reanimated: ~2.3.1 => 2.3.3 
    react-native-safe-area-context: 3.3.2 => 3.3.2 
    react-native-screens: 3.13.1 => 3.13.1 
    react-native-size-matters: 0.4.0 => 0.4.0 
    react-native-snap-carousel: 3.9.1 => 3.9.1 
    react-native-svg: 12.1.1 => 12.1.1 
    react-native-web: 0.17.1 => 0.17.1 
    react-test-renderer: 17.0.2 => 17.0.2 
    typescript: 4.5.5 => 4.5.5 
  npmGlobalPackages:
    aws-cdk: 2.18.0
    npm: 6.14.15
    nx: 13.6.1
    ts-node: 10.5.0

```

</details>

### Describe the bug

1. [this](https://github.com/amazon-archives/amazon-cognito-identity-js) library is deprecated
2. [npm](https://www.npmjs.com/package/amazon-cognito-identity-js) points to amplify-js

But I am not using amplify. Created cognito through cdk. 
If I use `amplify-js` it requires me to have `aws-exports.js` from amplify.

### Expected behavior

have a way to implement cognito auth without requiring amplify exported file

### Reproduction steps

1. expo init
2. don't know how to implement cognito login

### Code Snippet

```ts
import {
  AuthenticationDetails,
  CognitoUser,
  CognitoUserPool,
  CognitoUserSession,
} from 'amazon-cognito-identity-js'

import awsmobile from './aws-exports-dev'

const awsExports = awsmobile

export const userPool = new CognitoUserPool({
  UserPoolId: awsExports.aws_user_pools_id,
  ClientId: awsExports.aws_user_pools_web_client_id,
})

export const logout = (): void => {
  const cognitoUser = userPool.getCurrentUser()
  if (cognitoUser != null) {
    cognitoUser.signOut()
  }
}

export const isAuthenticated = async (): Promise<boolean> => {
  const cognitoUser = userPool.getCurrentUser()
  console.log('cognitoUser: ', cognitoUser)

  if (!cognitoUser) {
    return false
  }
  //   cognitoUser.getSession((err: Error, result: CognitoUserSession | null) => {
  //     if (!err) {
  //       console.log('err: ', err);
  //       isSessionValid = result?.isValid() || false
  //     }
  //   })
  return new Promise<boolean>((resolve, reject) => {
    cognitoUser.getSession((err: Error, result: CognitoUserSession | null) => {
      if (err || !result) {
        reject(new Error('Failure getting Cognito session: ' + err))
        return
      }

      // Resolve the promise with the session credentials
      console.debug('Successfully got session: ' + JSON.stringify(result))
      // const session = {
      //   credentials: {
      //     accessToken: result.accessToken.jwtToken,
      //     idToken: result.idToken.jwtToken,
      //     refreshToken: result.refreshToken.token,
      //   },
      //   user: {
      //     userName: result.idToken.payload['cognito:username'],
      //     email: result.idToken.payload.email,
      //   },
      // }
      resolve(true)
    })
  })
}

export const loginToCognito = async ({
  email,
  password,
}: {
  email: string
  password: string
}): Promise<string> => {
  const authenticationDetails = new AuthenticationDetails({
    Username: email,
    Password: password,
  })
  const cognitoUser = new CognitoUser({
    Username: email,
    Pool: userPool,
  })
  return new Promise((resolve, reject) => {
    cognitoUser.authenticateUser(authenticationDetails, {
      onSuccess: (result) => {
        const token = result.getAccessToken().getJwtToken()
        resolve(token)
      },
      onFailure: (err) => {
        reject(err)
      },
      newPasswordRequired: () => {
        reject(new Error('Change your password'))
      },
    })
  })
}

```

On Login screen 
```ts        const userToken = await loginToCognito({ email, password })
        console.log('userToken: ', userToken)
```
this displays login when i successfully login.

then next time app reload I am checking user logged in or not with this code

```ts
     const authenticated = await isAuthenticated()
      console.log('authenticated: ', authenticated)
```

which always returns 
```txt
cognitoUser:  null
authenticated:  false
```

**Comment by Tran-Minh23** [comment]
I think you can try something like context for authentication (https://reactnavigation.org/docs/auth-flow/). When you login, save your token in private store, and when you reload the app, you will check from the store to know whether the user logs in or not

**Comment by matart15** [comment]
> I think you can try something like context for authentication (https://reactnavigation.org/docs/auth-flow/). When you login, save your token in private store, and when you reload the app, you will check from the store to know whether the user logs in or not

1. Does it mean on react native, `amazon-cognito-identity-js` does not save Tokens automatically like web?
2. If yes, Do I have to manually parse JWT and check it's legit?
3. On react native, To get current logged user Id, do I have to do implementations of nodejs?

**Comment by Tran-Minh23** [comment]
I'm afraid that you have to save the tokens on your own, until now I haven't seen any topic about token will be autimatically saved.  I don't think you need to parse your token because  amazon-cognito-identity-js will respond all of the user info like sub or email. I don't have any experience in nodejs, but in my case, when the user logs in, I will save some info like email, exp time, access token, and refresh token, and when I need to reuse them, I just call from the storage

**Comment by matart15** [comment]
@Tran-Minh23 

Sorry my question went to wrong direction.

I can save toke nafter login and read it later.

But I can't find a way to get cognitoUserId, userGroups from jwt token?


```ts
        // after login
        AsyncStorage.setItem('@storage_Key', token).then(() => {
          resolve(token)
        })
```

```ts
// when to check user group
  const jwtToken = await AsyncStorage.getItem('@storage_Key')

  // how to get userGroups using jwtToken?
```

looking at this. https://github.com/amazon-archives/amazon-cognito-identity-js/blob/master/index.d.ts

**Comment by Tran-Minh23** [comment]
onSuccess: (respond) => {
                      const jwtToken = respond.getAccessToken().getJwtToken();
                      const exp = respond.getAccessToken().payload.exp;
                      const refreshToken = respond.getRefreshToken().getToken();

            const authInfo = {
              refreshToken,
              exp,
              email: data.authenticationData.Username,
            };
            PrivateStore.setAsync(storageKey.ACCESS_TOKEN, jwtToken);
            PublicStore.setAsync(storageKey.AUTH_INFO, authInfo);
          },


Here is my login code, when you login successfully, print out your respond to see what you can get from that, all the data you need in that repsond. I don't only save the token, but also save some additional datas

**Comment by matart15** [comment]
Thank you.

can you share me then what `data` is?

**Comment by Tran-Minh23** [comment]
> Thank you.
> 
> But that will only give me text datas, and email etc.
> 
> But how do I call this 2 functions? `resendConfirmationCode()` or [forgotPassword](https://github.com/amazon-archives/amazon-cognito-identity-js/blob/master/index.d.ts#L57)

https://reactnavigation.org/docs/auth-flow/, you can check this link, I've followed the flow in that. In my auth context, I use reducer to update the state, and the jobs like login, logout, reset password,... I stored each of them as a single function, whereever I need to use that function, I just call from my context

    resendCode: (data) => {
        const userData = {
          Username: data.email,
          Pool: UserPool,
        };
        const cognitoUser = new CognitoUser(userData);
        cognitoUser.resendConfirmationCode((err, result) => {
          if (err) {
            console.log(err);
          }
          if (result) {
            dispatch({ type: 'RESEND_CODE' });
          }
        });
      }

this is my resend confirmation function, you can write your own logic in your context for each job

**Comment by matart15** [comment]
I see. you created `new CognitoUser(userData)` object. 

I was hesitant to do that. because web was always giving me the object. Somehow I thought creating new is anti pattern. 

Thank you. I will continue with creating new object.

Closing the issue.

**Comment by matart15** [comment]
Thank you. This is my first time implementing authentication on react native too.

Now my question changed to [amazon-cognito-identity-js](https://github.com/amazon-archives/amazon-cognito-identity-js) library is deprecated. Is it right to use it? But I think I will open new issue or discussion for this?

**Comment by Tran-Minh23** [comment]
> Thank you. This is my first time implementing authentication on react native too.
> 
> Now my question changed to [amazon-cognito-identity-js](https://github.com/amazon-archives/amazon-cognito-identity-js) library is deprecated. Is it right to use it?
> 
> But I think I will open new issue or discussion for this?

https://www.npmjs.com/package/amazon-cognito-identity-js, you can check their, I see they update the library the frequently. Maybe you are viewing the old repository

**Comment by matart15** [comment]
Oh I see. That explained a lot. Thank you.

**Comment by hoIIer** [comment]
@matart15 @Tran-Minh23 glad to find this, working on my first RN app and first thing I need to do is hook up cognito. I did some searching and very little if anything comes up with how to integrate amazon-cognito-identity-js with react-native other than 3 lines in the readme file.

May return with questions! Glad to see there are others doing same integration w/o using amplify.
