### ISSUE TITLE
aws-amplify-react-native, Authenticator/ConfirmSignUp: Disable for "Resend Code" button based on state, which is not used the the callback for the button

### ISSUE THREAD

**Issue by bensewell** [aws-amplify/amplify-js#9766]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
  System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 12.30 GB / 23.79 GB
  Binaries:
    Node: 14.17.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 99.0.4844.82
    Edge: Spartan (44.22000.120.0), Chromium (98.0.1108.43)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @babel/core: ^7.12.9 => 7.17.8
    @react-native-async-storage/async-storage: ^1.17.3 => 1.17.3
    @react-native-community/netinfo: ^8.2.0 => 8.2.0
    @react-native-picker/picker: ^2.4.0 => 2.4.0
    @types/react: ~17.0.21 => 17.0.43
    @types/react-native: ~0.64.12 => 0.64.24
    HelloWorld:  0.0.1
    aws-amplify: ^4.3.18 => 4.3.18
    aws-amplify-react-native: ^6.0.4 => 6.0.4
    expo: ~44.0.0 => 44.0.6
    expo-status-bar: ~1.2.0 => 1.2.0
    hermes-inspector-msggen:  1.0.0
    react: 17.0.1 => 17.0.1
    react-dom: 17.0.1 => 17.0.1
    react-native: 0.64.3 => 0.64.3
    react-native-web: 0.17.1 => 0.17.1
    typescript: ~4.3.5 => 4.3.5
  npmGlobalPackages:
    amplify-category-video: 3.9.2
    autoprefixer: 9.8.8
    aws-sdk: 2.1074.0
    expo-cli: 5.1.2
    firebase-tools: 10.2.0
    http-server: 13.1.0
    postcss-cli: 8.3.1
    postcss: 8.4.6
    undefined: 0.1.0
    twilio-cli: 2.36.1
    typescript: 4.5.5
    yarn: 1.22.17

```

</details>

### Describe the bug

The "Resend Code" button doesn't show up when entering a username in the Confirmation dialogue, if you use the Authenticator control.

### Expected behavior

I expect that on the "Confirm a Code" page, when I enter an e-mail address, I should be able to get a new code by clicking "Resend Code".

### Reproduction steps

To reproduce:
1. `expo init testauthenticator` -> select `blank (TypeScript)`. Enter directory.
2. `amplify init` -> select a React Native app
3. Configure authentication with `amplify add auth`: 
`Do you want to use the default authentication and security configuration? Manual configuration
 Select the authentication/authorization services that you want to use: User Sign-Up, Sign-In, connected with AWS IAM controls (Enables per-user Storage
 features for images or other content, Analytics, and more)
 Warning: you will not be able to edit these selections.
 What attributes are required for signing up? Email
 Specify the app's refresh token expiration period (in days): 30
 Do you want to specify the user attributes this app can read and write? No
 Do you want to enable any of the following capabilities?
 Do you want to use an OAuth flow? No
? Do you want to configure Lambda Triggers for Cognito? No`

4. `yarn add aws-amplify aws-amplify-react-native @react-native-community/netinfo @react-native-async-storage/async-storage @react-native-picker/picker`
5. `yarn web`
6. On the page that comes up, click "Confirm a Code", then put an e-mail address into the "Email" field.

At this point, I'd expect the "Resend Code" button to become enabled, but it doesn't.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by bensewell** [comment]
I've also created a repo at https://github.com/bensewell/test-authenticator-confirmsignup.git showing this.

**Comment by Samaritan1011001** [comment]
@bensewell Could you please provide a video of what you are seeing as the issue? It could help us better understand the problem. Thank you!

**Comment by bensewell** [comment]
Sure - no problem, here it is @Samaritan1011001 

https://user-images.githubusercontent.com/1528716/168596501-ea42855d-e9f5-4651-b061-cb29b5b0a349.mp4

**Comment by bensewell** [comment]
(that is using the Git repo above)

**Comment by Samaritan1011001** [comment]
@bensewell Thanks! Can you confirm you have the following attribute set in `withAuthenticator`? That is the only case when I could reproduce the bug. 
```js
withAuthenticator(App,{
  usernameAttributes: 'email'
})
```

**Comment by bensewell** [comment]
Hi!

I'm not at my computer right now, but that is correct from memory.

Further up I've referenced a simple repo showing the issue.

Kind regards,
Ben

**Comment by Samaritan1011001** [comment]
Closing this in favor of the merged [PR](https://github.com/aws-amplify/amplify-js/pull/9767). Thank you for opening the issue and the contribution @bensewell.
