### ISSUE TITLE
Amplify prints out AuthError when NOT having Auth component

### ISSUE THREAD

**Issue by jamesaucode** [aws-amplify/amplify-js#9771]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

REST API

### Amplify Categories

auth, api

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

Amplify JS version: "aws-amplify": "^4.3.17",

When setting up a Amplify React app WITHOUT Auth component, calling the API.get will print out the below error in browser console
```
[ERROR] 00:14.198 AuthError - 
            Error: Amplify has not been configured correctly. 
            The configuration object is missing required auth properties.
            This error is typically caused by one of the following scenarios:

            1. Did you run `amplify push` after adding auth via `amplify add auth`?
                See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information

            2. This could also be caused by multiple conflicting versions of amplify packages, see (https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js) for help upgrading Amplify packages.
```

### Expected behavior

It should not print error in the browser console

### Reproduction steps

- set up a basic React app
- set up a public accessible API GW
- Use the following code snippet to call REST API
```jsx
import Amplify, { API } from 'aws-amplify';
Amplify.configure({
  API: {
    endpoints: [
      {
        name: "rest",
        endpoint: "<API endpoint>" 
      }
    ]
  }
});

function App() {

  API.get('rest', '/items')

  return (
    <div className="App">
     
    </div>
  );
}

export default App;
```

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by alharris-at** [comment]
@jamesaucode, could you provide your `package.json` file to help in repro and resolution? As noted in the error, we've seen this happen from time to time when there are duplicate version of the amplify-js lib, or `amplify-js` alongside the `amplify-datastore` imports.

**Comment by RMG0** [comment]
Similar issue for me with react-native app.

**Comment by mcnamara-charles** [comment]
I'm still getting this. No Auth component, here's my package.json:
```
{
  "name": "react-amplified",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.1.1",
    "@fortawesome/free-solid-svg-icons": "^6.1.1",
    "@fortawesome/react-fontawesome": "^0.1.18",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.2.0",
    "@testing-library/user-event": "^13.5.0",
    "aws-amplify": "^4.3.24",
    "framer-motion": "^6.3.6",
    "react": "^18.1.0",
    "react-dom": "^18.1.0",
    "react-router-dom": "^6.3.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

**Comment by khatruong2009** [comment]
Hi James,

The code is inside a try-catch and is there to make sure that the user is given UnAuth credentials. Although an error is being logged, the functionality is still the same. I have submitted a pull request to fix this issue (and another similar one) and remove the logging of the error when a user pool is not present. 

Thanks,
Kha

**Comment by dreamorosi** [comment]
Hi @stocaaro I see that you have closed the issue and the PR has been merged, any indication is the fix has already been released? If not, will it be in the next release?

**Comment by khatruong2009** [comment]
Hi @dreamorosi, 

This fix was released in the 2022-08-01 Amplify release: aws-amplify@4.3.30.

Thanks,
Kha
