### ISSUE TITLE
Allow custom s3 endpoint

### ISSUE THREAD

**Issue by guanzo** [aws-amplify/amplify-js#978]
This is a feature request.

I'd like to specify a custom endpoint that the S3 module will send requests to. This feature is available in the AWS SDK seen here: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Endpoint.html

There are many S3 clones out there, such as ceph, swift, minio, zenko etc. Most S3 client libraries allow you to specify an endpoint because they know these clones exist, I think aws-amplify should do the same.

**Comment by workforfilmsGithub** [comment]
any news on it..

**Comment by whisper-bye** [comment]
+1

**Comment by undefobj** [comment]
@whisper-bye @workforfilmsGithub @guanzo can you give more information on the use case you're trying to accomplish that you could not achieve by leveraging the configuration of the Storage category and passing in the bucket & region name? For example:

```
    Storage: {
        bucket: '', //REQUIRED -  Amazon S3 bucket
        region: 'XX-XXXX-X', //OPTIONAL -  Amazon service region
    }
```

Amplify has a goal around simplicity and settings through config, so it would help to know what you're trying to accomplish with a custom endpoint. It's also important to note that S3 is just one of the potential providers in the Storage category as it grows in the future, so we try to avoid implementation specific config. However, you can always just use a passthrough to the AWS SDK if something custom is needed like so: https://aws-amplify.github.io/amplify-js/media/authentication_guide#working-with-aws-service-objects

**Comment by jordanranz** [comment]
Closing this issue as requested above. Please reopen if there are any further questions or concerns.

**Comment by yareyaredesuyo** [comment]
When developing using serverless and amplify, there is a option to using local s3 simulation. So this feature-request looks nice to me.

And there is `RFC - Local development and testing`  and it maybe related to this. 

https://github.com/aws-amplify/amplify-cli/issues/1433

- https://hub.docker.com/r/scality/s3server/

**Comment by kkkkkt** [comment]
There is some libraries supporting local and s3 emulation endpoint (aws-sdk also support it) ( https://github.com/jubos/fake-s3/wiki/Supported-Clients )

So if you want to use local or another s3 service, u should try it.
