### ISSUE TITLE
Hiding/renaming default fields for the SignIn form when using Authenticator

### ISSUE THREAD

**Issue by j0b0sapi3n** [aws-amplify/amplify-js#979]
**Do you want to request a feature or report a bug?**
Feature

**What is the current behavior?**
Right now, the Authenticator's provided SignIn form defaults to showing username, password, email, and phone number. However, my Cognito user pool only allows users to sign up with email and password, which seems like it'd be a common set up for a lot of apps. I _could_ write an entire new SignIn form but I find the default SignIn form works great for my current prototyping/move fast phase. Being able to pass in some prop indicating which fields, or better yet for it to auto-detect the user pool attributes set up and only showing the required fields would be even better and in the spirit of having Auth being a "true" quick start.

Furthermore, since I'm only allowing `email`, technically that gets submitted under `username` which is a confusing experience. If we could rename the `username` field to `email` if that's the only field required that'd actually line up with what Cognito is doing. Thanks!

**Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?**
    "aws-amplify": "0.4.1",
    "aws-amplify-react": "0.1.43",

**Comment by jameskhamil** [comment]
> , or better yet for it to auto-detect the user pool attributes set up and only showing the required fields would be even better and in the spirit of having Auth being a "true" quick start.

I assumed this was the default behavior! You have to recode the form from scratch when changing fields?

**Comment by sammartinez** [comment]
This is now implemented, please see the documentation [here](https://aws-amplify.github.io/docs/js/react#sign-upin-with-emailphone-number). Resolving.
