### ISSUE TITLE
"Max number of 100 subscriptions reached" after "unsubscribe" in real-time communication

### ISSUE THREAD

**Issue by shichi18** [aws-amplify/amplify-js#9790]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

GraphQL API, PubSub

### Amplify Categories

api

### Environment information

<details>

```
# Put output below this line

```

</details>

### Describe the bug

I register for multiple OnListener in succession, unregister when I want to switch to another OnListener, register again, and so on.

When a certain point is reached, an error occurs.
(probably the number of times the OnListener setting has been repeated).
"Max number of 100 subscriptions reached" is displayed.

I repeat unsubscribe to avoid going over 100.

### Expected behavior

"Max number of 100 subscriptions reached" is displayed.
I want to prevent this Error.

Can this error be resolved by disconnecting with unsubscribe?
Or is this a Bug?
Is there a workaround?

What I want to do
I want to get all the Update process of one Table in real time.

### Reproduction steps

1. Multiple subscribe settings.
2. do "unsubscribe" to set the next subscribe.

3. Repeat up to about ↑100.
4. Error occurs.

### Code Snippet

```javascript
// Put your code below this line.

  public subscribe() {
    this.unsubscribe();

    this.roomSubscriptions = rooms.map((room) => {
      return this.apiService.OnUpdateRoomsListener(room.id).subscribe(
        (res) => {},
        (e) => {
          console.log(e);
        },
        () => console.log('Room Done')
      );
    });
  }

  public unsubscribe() {
    if (this.roomSubscriptions) {
      this.roomSubscriptions.forEach((room) => {
        room.unsubscribe();
      });
    }
  }

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @shichi18 👋 thanks for raising this issue.

I'm not as familiar with Angular as I am a framework like React. How and/or when are you unsubscribing from the observers? In React, this would happen in a clean up function when the component unmounts.

It looks like the [Angular equivalent](https://blog.bitsrc.io/6-ways-to-unsubscribe-from-observables-in-angular-ab912819a78f) of this is to run `unsubscribe` within the `ngOnDestroy` method. Are you handling it similarly in your app?

Also, how many models are in your schema? Unless there are a ton it should be difficult to hit the limit especially if you're also unsubscribing when not needed (on component unmount/destroy).

Are you setting up create, update, and delete subscriptions for every model to listen at all times in your app? This is more common when using Amplify DataStore because it will attempt to set up all three for every model, meaning there is a soft cap of 33 models in (33 models * 3 subs for each = 99 subs).

**Comment by shichi18** [comment]
@chrisbonifacio 

Thank you!
The "unsubscribe" is also added to "ngOnDestroy".
However, the component is not destroyed until the app is closed.

The first startup was fine.
And the model we're using is "3 models * 3 subs for each = 9 subs".
All models are 12 models but use "@model(subscriptions: null)"


Room will get all of them first.
My app has a search function, where I can search for Rooms (using Filter and other switching feature).
Each time that search or criteria changes, I repeat subscribe and unsubscribe.

I set the id of the room to subscribe and repeat onListener for that number of times.
I do "unsubscribe" before setting(subscribe) it.

``` ts
// Put your code below this line.

  public subscribe() {
    this.unsubscribe(); // this unsubscribe

    this.roomSubscriptions = rooms.map((room) => {
      return this.apiService.OnUpdateRoomsListener(room.id).subscribe( // Is this the right usage here?
        (res) => {},
        (e) => {
          console.log(e);
        },
        () => console.log('Room Done')
      );
    });
  }

  public unsubscribe() {
    if (this.roomSubscriptions) {
      this.roomSubscriptions.forEach((room) => {
        room.unsubscribe();
      });
    }
  }
```

**Comment by shichi18** [comment]
@chrisbonifacio

I understood this issue...

My project has two groups, customer and employee.
Customers basically have login control by id.
Currently I just separate them.

The GraphQL schema is as follows
```
type Rooms @model
@auth(rules: [
  { allow: owner, ownerField: "id", operations: [create, update, read] }
  { allow: groups, groups: ["employee"] }
  { allow: public, provider: iam, operations: [create, update, read] }
]) {
  id: ID!
 data1: string
 data2:string
...
}
```

I want to get all Updates that occur in real time for an Employee group account.
However, when I set OnListener, I set the id to "null".
However, I got a "Validation error of type UndefinedVariable: variable not found".

To avoid this error, I wrote a process to repeatedly set OnListener for each Room.
The real expected behavior was that "Validation error of type UndefinedVariable: variable not found" would not appear.
(May be this another issue?)

So, this issue...
Then, I think the number of subscriptions is increasing by repeating OnListener for each Room.

I thought that I could unsubscribe the distribution by doing unsubscribe.
However, it does not seem to be doing that.

By unsubscribing, the subscribe itself is stopped.
But, It may be more correct to say that the connection is not broken (Cache may be still there?).

However, this approach may be a little peculiar.
I think this only happens when allow: owner is used.

thank you!

**Comment by chrisbonifacio** [comment]
Hey @shichi18 For the "Validation error of type UndefinedVariable: variable not found" error you are seeing, can you check the `API.service.ts` file and search for the `onUpdateRoomsListener` function? Does it accept an `id` as an argument like so?

```js
OnUpdateRoomsListener(
    id?: string
  ): Observable<
    SubscriptionResponse<Pick<__SubscriptionContainer, "onUpdateRooms">>
  > {
    const statement = `subscription OnUpdateRooms($id: String) {
        onUpdateRooms(id: $id) {
          __typename
          id
          data1
          data2
          createdAt
          updatedAt
        }
      }`;
    const gqlAPIServiceArguments: any = {};
    if (id) {
      gqlAPIServiceArguments.id = id;
    }
    return API.graphql(
      graphqlOperation(statement, gqlAPIServiceArguments)
    ) as Observable<
      SubscriptionResponse<Pick<__SubscriptionContainer, "onUpdateRooms">>
    >;
  }
  ```

**Comment by shichi18** [comment]
@chrisbonifacio 

``` js
OnUpdateRoomsListener(
    id?: string
  ): Observable<
    SubscriptionResponse<Pick<__SubscriptionContainer, "onUpdateRooms">>
  > {
    const statement = `subscription OnUpdateRooms($id: String) {
        onUpdateRooms(id: $id) {
          __typename
          id
 
          ... 
          ...
          ...
         
          createdAt
          updatedAt
        }
      }`;
    const gqlAPIServiceArguments: any = {};
    if (id) {
      gqlAPIServiceArguments.id = id;
    }
    return API.graphql(
      graphqlOperation(statement, gqlAPIServiceArguments)
    ) as Observable<
      SubscriptionResponse<Pick<__SubscriptionContainer, "onUpdateRooms">>
    >;
  }
```
↑
id = null
The code is intact.
If you enter an existing ID, it works fine.
If you enter null, an error will occur.
This is an error that is caught the moment OnListener is set.

I thought that if you belong to a group, you could get updates for everyone with null, but is that not the case?

The account belongs to a group.
However, since we are authenticating allow: owner, the id is required for entry.
However, I don't think it was necessary in the case of allow: group.(null is OK?)

`"Connection failed: {"errors":[{"message":"Validation error of type UndefinedVariable: variable not found"}]}"`

**Comment by shichi18** [comment]
@chrisbonifacio 
Thank you!!!

That may be the behavior I was hoping for!
I will comment as soon as we have confirmation.

**Comment by chrisbonifacio** [comment]
Hey @shichi18 , just wanted to follow up on this issue and see how everything's going. Did the proposed solution work for you?

**Comment by shichi18** [comment]
@chrisbonifacio 
Thank you !!!
It worked!!!
I was able to do what I originally wanted to do.

Before Amplify push (use amplify cli).
`
Be careful when using @auth directives on a field in a root type. @auth directives on field definitions use the source object to perform authorization logic and the source will be an empty object for fields on root types. Static group authorization should perform as expected.
`
Can I ignore this warning if I use this method only for group authentication?
Is there anything I can fix?

If there is no problem, you can close it!
Thank you!
