### ISSUE TITLE
Cache.getItem('federatedInfo') for .JWT Token

### ISSUE THREAD

**Issue by michaelcuneo** [aws-amplify/amplify-js#980]
Hey guys,

I've been trying to pull a .JWT token to supply some details to my Cognito User so it can be all linked from the Authenticator after login, set the username and picture of people from their respective Google/Facebook accounts. I was able to do this easy when I had a full custom login flow, but now I can't seem to get a valid Auth Token from Facebook. Whatever is stored in there now isn't a valid Auth Token, it's some other odd Token that has no user details in it.

How can I get user details now after logging in... the usual public_profile?

**Comment by powerful23** [comment]
@michaelcuneo Sorry to be late. Are you using the cognito hosted ui feature?

**Comment by michaelcuneo** [comment]
I’m using <Authenticated/>

**Comment by powerful23** [comment]
@michaelcuneo so you are following this (doc)[https://aws.github.io/aws-amplify/media/authentication_guide#enabling-federated-identities]?

**Comment by michaelcuneo** [comment]
I have ... but it is broken.
__WEBPACK_IMPORTED_MODULE_4_aws_amplify__.Cache.getItem(...).then is not a function

**Comment by michaelcuneo** [comment]
And when it does work... it's not a token that comes full of data, it's not a .JWT Token.

**Comment by mlabieniec** [comment]
tracking this / duplicate:
https://github.com/aws-amplify/amplify-js/issues/980
