### ISSUE TITLE
test

### ISSUE THREAD

**Issue by phor3nsic** [aws-amplify/amplify-js#9802]
### Before opening, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).

### JavaScript Framework

React

### Amplify APIs

Storage

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

- [ x ]  (yes)

### Expected behavior

- [ X ]

### Reproduction steps

1. test

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by phor3nsic** [comment]
- [ x ] asd

**Comment by chrisbonifacio** [comment]
@phor3nsic 👋 should I leave this open?

**Comment by chrisbonifacio** [comment]
Hey @phor3nsic not sure if you're still testing something here 😅 In any case, good luck on the bug hunt! Thanks for helping us maintain the integrity of our repo.
