### ISSUE TITLE
Cognito update_user_attributes hijacks verified phone_number from another account

### ISSUE THREAD

**Issue by yellowred** [aws-amplify/amplify-js#981]
Hi,
I have a user pool with aliases enabled so `Alias attributes phone_number, email, preferred_username`. I expect the phone_number property to be unique across the user pool.

The problem is a user can update it's attribute `phone_number` (using `update_user_attributes`) it receives an SMS with confirmation code and can confirm his phone even though that phone is already confirmed in another account.

How could I prevent it? I would like to receive an error saying some sort of PhoneExists.

Not sure it is a bug or a feature request.

Btw, I use the latest aws-sdk-ruby.

See also: https://github.com/amazon-archives/amazon-cognito-identity-js/issues/530

**Comment by mlabieniec** [comment]
@yellowred i believe you can use a custom trigger to check if the attribute exists in the lambda function perhaps pre-authentication?
https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-authentication.html

@yuntuowang do you have any suggestions on this?

**Comment by yellowred** [comment]
Hi, thank you for looking into this issue! Validation inside a lambda would be ideal, but I am not sure `pre-authentication` will work for me as I use `ADMIN_NO_SRP_AUTH` authentication (`admin_initiate_auth`). Then I call `update_user_attributes` which I would prefer to trigger a lambda.
