### ISSUE TITLE
Why domain name .mydomain.com is not set in cookies using Safari for AmazonCognitoIdentity.CookieStorage()

### ISSUE THREAD

**Issue by proraheelaslam** [aws-amplify/amplify-js#9814]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Authentication, DataStore, Storage

### Environment information

```
 var poolData = {
     UserPoolId : '...', // Your user pool id here
     ClientId : '...' // Your client id here
     Storage: new AmazonCognitoIdentity.CookieStorage({domain: "paramount.com"})
 };

 var userPool = new AmazonCognitoIdentity.CognitoUserPool(poolData);

 var userData = {
     Username: 'username',
     Pool: userPool,
     Storage: new AmazonCognitoIdentity.CookieStorage({domain: "paramount.com"})
 };
```

### Describe the bug

When we try to set the CookieStorage using different domain name it adds dot(.) automatically in cookie domain.
If we set [paramount.com](http://paramount.com/) CookieStorage it set .[mydomain.com](http://paramount.com/)
If we set we set [dev.paramount.com](http://paramountcom/) it also add .[paramount.com](http://paramount.com/)
The safari is blocks the dot(.) domain at the start of domain.  For example it set domain .[paramount.com](http://paramount.com/)
Safari does not accept this. It accepts [paramount.com](http://paramount.com/)
This is wild card domain. It ignore the wild card domain.

How can do this ?

### Expected behavior

We have tried this 
```
 var poolData = {
     UserPoolId : '...', // Your user pool id here
     ClientId : '...' // Your client id here
     Storage: new AmazonCognitoIdentity.CookieStorage({domain: "paramount.com"})
 };
 var userPool = new AmazonCognitoIdentity.CognitoUserPool(poolData);
 var userData = {
     Username: 'username',
     Pool: userPool,
     Storage: new AmazonCognitoIdentity.CookieStorage({domain: "paramount.com"})
 };
 
```
 This is script make issue on only safari iPhone. All other browsers are working fine.
 The cookies are not created in safari.

### Reproduction steps

No cookies has been created on safari

### Code Snippet

```
 var poolData = {
     UserPoolId : '...', // Your user pool id here
     ClientId : '...' // Your client id here
     Storage: new AmazonCognitoIdentity.CookieStorage({domain: "paramount.com"})
 };

 var userPool = new AmazonCognitoIdentity.CognitoUserPool(poolData);

 var userData = {
     Username: 'username',
     Pool: userPool,
     Storage: new AmazonCognitoIdentity.CookieStorage({domain: "paramount.com"})
 };
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by proraheelaslam** [comment]
@chrisbonifacio Sorry for mention. Can we save it without dot(.) in cookies so that safari can work ?

**Comment by proraheelaslam** [comment]
@vyomr13 We have checked if we save manually via this method it saves on safari. but according to documentation it is not save in safari. I have also try this option `SameSite=None `

`document.cookie = ""+refreshTokenKey+"="+refreshToken+"; SameSite=None; Secure; domain=.paramount.com";`

It is very urgent our users are unable to use the system

Please help use.

Thanks

**Comment by vyomr13** [comment]
@proraheelaslam are you seeing this behavior on a simulator or on a physical device and also are you using react-native or a webapp?

**Comment by proraheelaslam** [comment]
@vyomr13 Thanks for reply we have tested on both simulator and real physical devices it is not working. We are using only JavaScript not any framework.

**Comment by proraheelaslam** [comment]
@vyomr13 Are you investigating safari issue ?

**Comment by chrisbonifacio** [comment]
Hi @proraheelaslam 👋 sorry for the delay, we have no been able to reproduce this issue with the code provided. Could you explain what you're trying to build? Is the code snippet provided running in a browser or a node environment (node, lambda, etc)?
