### ISSUE TITLE
Storage.Put provide ability to change partSize

### ISSUE THREAD

**Issue by sushmasatish** [aws-amplify/amplify-js#9834]
### Is this related to a new or existing framework?

React

### Is this related to a new or existing API?

Storage

### Describe the feature you'd like to request

Currently Storage.Put uses a constant partSize of 5MB. When uploading files more than 5GB, it would be help if the partSize is like 100-500MB.

### Describe the solution you'd like

Either use options provided by user ex: {partSize: 100MB} and pass it down to low-level.

(or)

Storage.put automatically sets an appropriate partSize based on file size.

### Describe alternatives you've considered

We are currently doing Multipart Upload ourselves with partSize set to 500MB. Upload finished far quickly in comparison to Storage.put.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by nadetastic** [comment]
Hi @sushmasatish,

This was recently addressed with https://github.com/aws-amplify/amplify-js/pull/10820 and is available with `aws-amplify@5.0.10`.

I'll be closing this out now, thank you!
