### ISSUE TITLE
DataStore not updating after update DynamoDB from lambda function

### ISSUE THREAD

**Issue by duranmla** [aws-amplify/amplify-js#9842]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

DataStore

### Amplify Categories

api

### Environment information

<details>

```
System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1
    Memory: 125.19 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.4 - ~/.nvm/versions/node/v14.17.4/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v14.17.4/bin/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.4/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Firefox: 99.0
    Safari: 15.3
  npmPackages:
    @aws-amplify/ui-react: ^1.2.1 => 1.2.12 
    @aws-crypto/sha256-js: ^1.0.0 => 1.1.0 (1.0.0-alpha.0)
    @commitlint/cli: ^15.0.0 => 15.0.0 
    @commitlint/config-conventional: ^15.0.0 => 15.0.0 
    @fortawesome/fontawesome-svg-core: ^1.2.35 => 1.2.36 
    @fortawesome/free-brands-svg-icons: ^5.15.3 => 5.15.4 
    @fortawesome/free-solid-svg-icons: ^5.15.3 => 5.15.4 
    @fortawesome/react-fontawesome: ^0.1.14 => 0.1.15 
    @jackfranklin/test-data-bot: ^1.3.0 => 1.3.0 
    @react-theming/storybook-addon: ^1.1.1 => 1.1.1 
    @reduxjs/toolkit: ^1.6.1 => 1.6.1 
    @reduxjs/toolkit-query:  1.0.0 
    @reduxjs/toolkit-query-react:  1.0.0 
    @storybook/addon-essentials: ^6.3.7 => 6.3.7 
    @storybook/addon-links: ^6.3.7 => 6.3.7 
    @storybook/addons: ^6.3.7 => 6.3.7 
    @storybook/preset-create-react-app: ^3.2.0 => 3.2.0 
    @storybook/react: ^6.3.7 => 6.3.7 
    @storybook/theming: ^6.3.7 => 6.3.7 
    @stripe/react-stripe-js: ^1.7.0 => 1.7.0 
    @stripe/stripe-js: ^1.24.0 => 1.24.0 
    @svgr/plugin-prettier: ^5.5.0 => 5.5.0 
    @testing-library/cypress: ^8.0.0 => 8.0.1 
    @testing-library/dom: ^8.5.0 => 8.5.0 (8.2.0, 7.31.2)
    @testing-library/jest-dom: ^5.11.4 => 5.14.1 
    @testing-library/react: ^11.1.0 => 11.2.7 
    @testing-library/user-event: ^13.2.1 => 13.2.1 
    @types/eth-sig-util: ^2.1.1 => 2.1.1 
    @types/jest: ^26.0.15 => 26.0.24 (27.0.1)
    @types/lodash: ^4.14.172 => 4.14.172 
    @types/node: ^12.0.0 => 12.20.23 (16.7.10, 14.17.14)
    @types/react: ^17.0.38 => 17.0.38 (17.0.19)
    @types/react-dom: ^17.0.11 => 17.0.11 
    @types/react-redux: ^7.1.16 => 7.1.18 
    @types/react-router-dom: ^5.1.7 => 5.1.8 
    @types/react-slider: ^1.3.1 => 1.3.1 
    @types/redux-logger: ^3.0.8 => 3.0.9 
    @types/styled-components: ^5.1.13 => 5.1.13 
    @types/styled-system: ^5.1.12 => 5.1.13 
    @types/styled-system__css: ^5.0.16 => 5.0.16 
    @walletconnect/client: ^1.6.6 => 1.6.6 
    @walletconnect/qrcode-modal: ^1.6.6 => 1.6.6 
    aws-amplify: ^4.2.0 => 4.2.6 
    aws-sdk: ^2.989.0 => 2.989.0 
    babel-plugin-styled-components: ^1.13.2 => 1.13.2 
    base64-js: ^1.3.1 => 1.5.1 
    chromatic: ^5.9.2 => 5.9.2 
    cypress: ^9.5.1 => 9.5.1 
    dayjs: ^1.10.6 => 1.10.6 
    eslint-config-prettier: ^8.3.0 => 8.3.0 
    eslint-plugin-cypress: ^2.12.1 => 2.12.1 
    eslint-plugin-prettier: ^3.3.1 => 3.4.1 
    formik: ^2.2.9 => 2.2.9 
    framer-motion: ^4.1.17 => 4.1.17 
    husky: ^7.0.4 => 7.0.4 
    lodash: ^4.17.21 => 4.17.21 
    polished: ^4.1.3 => 4.1.3 
    prettier: ^2.4.1 => 2.4.1 (2.2.1, 2.3.2)
    pretty-quick: ^3.1.2 => 3.1.2 
    react: ^17.0.2 => 17.0.2 
    react-accessible-dropdown-menu-hook: ^3.0.0 => 3.0.0 
    react-country-region-selector: ^3.3.0 => 3.3.0 
    react-dom: ^17.0.2 => 17.0.2 
    react-feather: ^2.0.9 => 2.0.9 
    react-feature-flags: ^1.0.0 => 1.0.0 
    react-graceful-image: ^1.5.0 => 1.5.0 
    react-hot-toast: ^2.2.0 => 2.2.0 
    react-loader-spinner: ^4.0.0 => 4.0.0 
    react-markdown: ^7.1.0 => 7.1.0 
    react-redux: ^7.2.4 => 7.2.4 
    react-router-dom: ^5.2.0 => 5.2.1 
    react-scripts: ^4.0.3 => 4.0.3 
    react-select: ^5.0.0 => 5.0.0 
    react-slider: ^1.3.1 => 1.3.1 
    redux-logger: ^3.0.6 => 3.0.6 
    redux-persist: ^6.0.0 => 6.0.0 
    redux-persist/integration/react:  undefined ()
    sendbird-uikit: ^2.4.3 => 2.5.1 
    storybook-react-router: ^1.0.8 => 1.0.8 
    styled-components: ^5.3.1 => 5.3.1 (5.3.3)
    styled-components/macro:  undefined ()
    styled-components/native:  undefined ()
    styled-components/primitives:  undefined ()
    styled-system: ^5.1.5 => 5.1.5 
    ts-morph: ^11.0.3 => 11.0.3 
    typescript: ^4.0.3 => 4.4.2 (4.5.2)
    wait-on: ^6.0.0 => 6.0.0 
    web-vitals: ^0.2.4 => 0.2.4 
  npmGlobalPackages:
    @aws-amplify/cli: 8.0.0
    amplify: 0.0.11
    commitizen: 4.2.4
    cz-conventional-changelog: 3.3.0
    npm: 6.14.14
    typescript: 4.5.2
    yarn: 1.22.11
```

</details>

### Describe the bug

When updating my data directly from the server using `DynamoDB.DocumentClient` the sync with DataStore does not trigger on my client. In order to see the changes I need to logout and login on my app.

![CleanShot 2022-04-27 at 13 38 03@2x](https://user-images.githubusercontent.com/1425162/165510141-4e05abf3-b05a-4c68-8f8a-daec19730d64.png)

![CleanShot 2022-04-27 at 13 39 31@2x](https://user-images.githubusercontent.com/1425162/165510376-7d0a665b-156d-4cf6-a684-41d4544f261c.png)

I am also taking a look to the events on the `Hub` to see if there is something I can hook to but it seems like the client is just unaware that there is something different on the cloud

![CleanShot 2022-04-27 at 13 42 50@2x](https://user-images.githubusercontent.com/1425162/165511169-f5b5dab2-8e5d-470f-9d6a-7712116b315a.png)

### Expected behavior

I will expect DataStore to behave as it does when I create data from my client, enqueue a change that afterwards gets sync with the backend. In this case, backend somehow notify the client of changes and the client will pickup those and update.

### Reproduction steps

1. Create an app with amplify
2. Add a table with model `Foo`
3. Using DataStore create a new `Foo`
4. Update just created instance of `Foo` model using nodejs and Dynamo
5. Changes are not reflected into the Client **until logout and login again**

### Code Snippet

My current flow looks like:

- User attempt to buy `Product`
- A `Order` is being created with status `pending`
- Checkout process happen and we got notify via web hook
- Lambda function with `webhook` endpoint will update the `Order` using the `trackingID` to have status `succeeded`

---

Lambda function that updates `Order` 

```js
const updateOrderStatus = async ({ status, trackingId }) => {
  const { Items } = await docClient
    .scan({
      TableName: process.env.API_SOL_ORDERTABLE_NAME,
      FilterExpression: 'trackingID = :trackingID',
      ExpressionAttributeValues: {
        ':trackingID': trackingId,
      },
    })
    .promise()

  console.log('Orders scanned', Items)

  if (Items.length === 0) {
    throw new Error(`Unable to find Order with given trackingId: ${trackingId}`)
  }

  const order = Items[0]
  const newVersion = order._version + 1
  const date = new Date()
  await docClient
    .update({
      TableName: process.env.API_SOL_ORDERTABLE_NAME,
      Key: {
        id: order.id,
      },
      UpdateExpression:
        'SET #status = :status, #version = :version, #changedAt = :changedAt',
      ExpressionAttributeNames: {
        '#status': 'status',
        '#version': '_version',
        '#changedAt': '_lastChangedAt',
      },
      ExpressionAttributeValues: {
        ':status': status,
        ':version': newVersion,
        ':changedAt': date.getTime(),
      },
    })
    .promise()

  console.log(`Updated order status: ${status}, version: ${newVersion}`)
}
```

Code that triggers when `logout`

```js
signOut: async (options?: Object) => {
    await Auth.signOut(options)
    await DataStore.clear()
    dispatch(logOutUser())
},
```

### Log output

<img width="1281" alt="CleanShot 2022-04-27 at 13 58 18@2x" src="https://user-images.githubusercontent.com/1425162/165513333-c70bc75f-e8d3-4c6f-9a0c-7cc210e950b7.png">

_This is how the log level DEBUG looks like when coming back from the checkout process (which is done with Stripe outside the application) and I filter with `order` keyword (cause there is a bunch of lines I am not sure what to look for there)_

**Comment by duranmla** [comment]
I don't think this is a bug, rather this might be something I am overlooking. Sorry to add this as a bug. :(

**Comment by chrisbonifacio** [comment]
DataStore uses AppSync subscriptions and queries to keep data in sync. A change to DynamoDB directly won't trigger an update through AppSync and/or the client. Try making the change using AppSync in your Lambda instead.

**Comment by duranmla** [comment]
Thanks for your quick response. That makes a lot of sense, I knew I was missing something but I couldn't find a source of knowledge to drive my debugging process. One more thing tho:

- When you say are you talking about making a mutation like described on [DataStore docs](https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js/#mutation) or something more closer to [AppSync Client](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-appsync/index.html)

If it is more on the second option literally `AppSync Client` do you have a link I can use? Otherwise, I will start work day tomorrow and I will find it out. This is just to see if I can accelerate the process.

As a side note I have on `src/graphql/mutations.ts` an auto generated code but I think I can't use that code.

```js
export const updateOrder = /* GraphQL */ `
  mutation UpdateOrder(
    $input: UpdateOrderInput!
    $condition: ModelOrderConditionInput
  ) {
    updateOrder(input: $input, condition: $condition) {
      id
      productID
      priceID
      buyerID
      sellerID
      status
      trackingID
      stripePriceID
      stripeProductID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`;
```

**Comment by chrisbonifacio** [comment]
Hi @duranmla 👋 Your first link, the [GraphQL from NodeJS](https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js/#mutation) section of the Amplify docs would be the one I'd go with to fulfill this use case.

What I was referring to by "AppSync Client" is the `aws-appsync` package which I've seen some other customers use in the past to fulfill the same use case (mutation from Lamdba) but it can be done with just a signed post request as well.

**Comment by duranmla** [comment]
I think we can close this issue for now. If I encounter any issue I will re-open but this seems to be a quite common scenario that is widely known and well supported. I don't want to keep this open as It seems I need to finish other stuff before coming back to this. Thanks **a lot** @chrisbonifacio

**Comment by duranmla** [comment]
Just for people that land on this topic, the `_version` needs to be the same version you have in the Database, it seems a way to make sure you can update as you are using the latest known version of the item. I though before I needed to do `_version: currentVersion + 1` **but that's no the case**.


I am doing something like:

```js
const updateOrderStatus = async ({ status, trackingId }) => {
  const { Items } = await docClient
    .scan({
      TableName: process.env.API_SOL_ORDERTABLE_NAME,
      FilterExpression: 'trackingID = :trackingID',
      ExpressionAttributeValues: {
        ':trackingID': trackingId,
      },
    })
    .promise()

  console.log('Orders scanned', Items)

  if (Items.length === 0) {
    throw new Error(`Unable to find Order with given trackingId: ${trackingId}`)
  }

  const order = Items[0]

  console.log('About to update order', order)

  const response = await updateOrder({
    id: order.id,
    _version: order._version,
    status,
  })

  console.log(
    `Updated order status: ${response.data.updateOrder.status}, version: ${response.data.updateOrder._version}`
  )
}
```

Where `updateOrder` has the code @chrisbonifacio shared above.
