### ISSUE TITLE
App sync Mutations Arguments are all { Null: true} Suddenly without any code change

### ISSUE THREAD

**Issue by NiksanJP** [aws-amplify/amplify-js#9852]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

GraphQL API

### Amplify Categories

Not applicable

### Environment information

<details>

```
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 4.35 GB / 15.96 GB
  Binaries:
    Node: 14.15.0 - D:\Node\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - D:\Node\npm.CMD
  Browsers:
    Chrome: 87.0.4280.66
  npmPackages:
    @aws-amplify/ui-react: ^2.9.0 => 2.10.0
    @aws-amplify/ui-react-internal:  undefined ()
    @aws-amplify/ui-react-legacy:  undefined ()
    @babel/core: ^7.17.5 => 7.17.5
    @react-native-async-storage/async-storage: ^1.16.1 => 1.16.1
    @react-native-community/masked-view: ^0.1.11 => 0.1.11
    @react-native-community/netinfo: ^7.1.12 => 7.1.12
    @react-native-picker/picker: ^2.3.1 => 2.3.1
    @react-navigation/bottom-tabs: ^6.2.0 => 6.2.0
    @react-navigation/material-bottom-tabs: ^6.1.1 => 6.1.1
    @react-navigation/native: ^6.0.8 => 6.0.8 (3.8.4)
    @react-navigation/stack: ^6.1.1 => 6.1.1
    HelloWorld:  0.0.1
    aws-amplify: ^3.0.13 => 3.0.13
    aws-amplify-react-native: ^6.0.1 => 6.0.3
    expo: ~43.0.2 => 43.0.5
    expo-image-picker: ~11.0.3 => 11.0.3
    expo-status-bar: ~1.1.0 => 1.1.0
    hermes-inspector-msggen:  1.0.0
    react: 17.0.1 => 17.0.1
    react-dom: 17.0.1 => 17.0.1
    react-native: 0.64.3 => 0.64.3
    react-native-gesture-handler: ~1.10.2 => 1.10.3
    react-native-image-slider-box: ^1.1.22 => 1.1.22
    react-native-paper: ^4.11.1 => 4.11.2
    react-native-safe-area-context: ^3.3.2 => 3.4.1
    react-native-screens: ^3.10.1 => 3.13.1
    react-native-table-component: ^1.2.1 => 1.2.2
    react-native-web: 0.17.1 => 0.17.1
    react-navigation: ^4.4.4 => 4.4.4
    react-style-proptype: ^3.2.2 => 3.2.2
  npmGlobalPackages:
    @aws-amplify/cli: 7.6.23
    bit-bin: 14.8.8
    bower: 1.8.8
    electron: 6.0.1
    expo-cli: 5.4.3
    firebase-tools: 9.3.0
    npm-check-updates: 12.0.3
    react-native-cli: 2.0.1
    react-scripts: 4.0.1
    serve: 11.3.2
    yarn: 1.22.10


```

</details>

### Describe the bug

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I run a mutation from my react-native, all the args are turn to "NULL": true.
But all the extra ones like Username from identity stay the same!

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The $ctx.args should be able to add proper data into dynamodb

**What is the expected behavior?**
The Dynamodb table should not have null values

**Which versions and which environment (browser, react-native, nodejs) / OS are affected by this issue? Did this work in previous versions?**
React-native, when I woke up the next morning I stopped working, everything was working fine until last night (no changes)

**SCHEMA**

```
type Item {
	id: ID!
	Title: String
	Available: Boolean
	PublishDate: String
	Description: String
	Location: String
	Price: String
	Type: String
	Images: String
	tags: String
	UserName: String
	user: User
}
```

**Mutation**

```
`#set($ctx.args.UserName = $ctx.identity.username)
#set($ctx.args.PublishDate = $util.time.nowISO8601())

{
    "version" : "2017-02-28",
    "operation" : "PutItem",
    "key" : {
        "id": $util.dynamodb.toDynamoDBJson($util.autoId()),
    },
    "attributeValues" : $util.dynamodb.toMapValuesJson($ctx.args),
}`
```
I also tried using `$util.dynamodb.toMapValuesJson($context.arguments)` but it does not seem to work!
 `$util.dynamodb.toMapValuesJson($ctx.args` dynamodb output: 
![image](https://user-images.githubusercontent.com/40626274/165955862-d691f362-195c-4660-a604-dd2365ee51a9.png)
 `$util.dynamodb.toMapValuesJson($context.arguments)`  output:
![image](https://user-images.githubusercontent.com/40626274/165955988-20423ba3-41ef-4547-a544-78bff7b6303b.png)

**Native Code**

```
export async function addItem(title, available, description, price, type, images) {
    try{
        console.log(title, available, description, price, type, images)
        let res = await API.graphql(graphqlOperation(createItem, {
            input: {
                Title: title,
                Available: true,
                Description: description,
                Location: "Auburn, Sydney",
                Price: price,
                Type: "rent",
                Images: images,
                tags: ["electronic"]
            }
        }));
        console.log(res)

        return res.data
    }catch(err){
        console.log('error creating item', err)
        return false;
    }
}

```

Just did some printing, the query that is going to be executed:
```
{query: '\n  mutation CreateItem(\n    $Available: Boolean\n  …     UserType\n        Verified\n      }\n    }\n  }\n', variables: {…}}
query: "\n  mutation CreateItem(\n    $Available: Boolean\n    $Description: String\n    $Images: String\n    $Location: String\n    $Price: String\n    $Title: String\n    $Type: ItemAdType\n    $tags: [ItemTags]\n  ) {\n    createItem(\n      Available: $Available\n      Description: $Description\n      Images: $Images\n      Location: $Location\n      Price: $Price\n      Title: $Title\n      Type: $Type\n      tags: $tags\n    ) {\n      Available\n      Description\n      Images\n      Location\n      Price\n      PublishDate\n      Title\n      Type\n      UserName\n      id\n      tags\n      user {\n        Address\n        Email\n        FullName\n        MFA\n        PhoneNumber\n        ShowEmail\n        ShowNumber\n        SuburbNo\n        UserJoinDate\n        UserName\n        UserType\n        Verified\n      }\n    }\n  }\n"
variables:
input:
Available: true
Description: "Random description"
Images: "None"
Location: "Sydney"
Price: "2.0"
Title: "No title LMAO"
Type: "rent"
[[Prototype]]: Object
[[Prototype]]: Object
[[Prototype]]: Object
```
![image](https://user-images.githubusercontent.com/40626274/165954789-bf251234-c92a-4a67-afcc-016b2e768054.png)

This all worked until last night and suddenly stopped working!
No Error Message or anything!
But when running on App sync's platform it runs fine!

### Expected behavior

The Data should be reflected to the DynamoDB tables!

### Reproduction steps

1. Install existing Appsync to Amplify
2. WIll run fine
3. But out of nowhere without any changes this will happen
4. Panic

### Code Snippet

**SCHEMA**

```
type Item {
	id: ID!
	Title: String
	Available: Boolean
	PublishDate: String
	Description: String
	Location: String
	Price: String
	Type: String
	Images: String
	tags: String
	UserName: String
	user: User
}
```

**Mutation**

```
`#set($ctx.args.UserName = $ctx.identity.username)
#set($ctx.args.PublishDate = $util.time.nowISO8601())

{
    "version" : "2017-02-28",
    "operation" : "PutItem",
    "key" : {
        "id": $util.dynamodb.toDynamoDBJson($util.autoId()),
    },
    "attributeValues" : $util.dynamodb.toMapValuesJson($ctx.args),
}`
```
I also tried using `$util.dynamodb.toMapValuesJson($context.arguments)` but it does not seem to work!
 `$util.dynamodb.toMapValuesJson($ctx.args` dynamodb output: 
![image](https://user-images.githubusercontent.com/40626274/165955862-d691f362-195c-4660-a604-dd2365ee51a9.png)
 `$util.dynamodb.toMapValuesJson($context.arguments)`  output:
![image](https://user-images.githubusercontent.com/40626274/165955988-20423ba3-41ef-4547-a544-78bff7b6303b.png)

**Native Code**

```
export async function addItem(title, available, description, price, type, images) {
    try{
        console.log(title, available, description, price, type, images)
        let res = await API.graphql(graphqlOperation(createItem, {
            input: {
                Title: title,
                Available: true,
                Description: description,
                Location: "Auburn, Sydney",
                Price: price,
                Type: "rent",
                Images: images,
                tags: ["electronic"]
            }
        }));
        console.log(res)

        return res.data
    }catch(err){
        console.log('error creating item', err)
        return false;
    }
}

```

### Log output

<details>

```
Just did some printing, the query that is going to be executed:
```
{query: '\n  mutation CreateItem(\n    $Available: Boolean\n  …     UserType\n        Verified\n      }\n    }\n  }\n', variables: {…}}
query: "\n  mutation CreateItem(\n    $Available: Boolean\n    $Description: String\n    $Images: String\n    $Location: String\n    $Price: String\n    $Title: String\n    $Type: ItemAdType\n    $tags: [ItemTags]\n  ) {\n    createItem(\n      Available: $Available\n      Description: $Description\n      Images: $Images\n      Location: $Location\n      Price: $Price\n      Title: $Title\n      Type: $Type\n      tags: $tags\n    ) {\n      Available\n      Description\n      Images\n      Location\n      Price\n      PublishDate\n      Title\n      Type\n      UserName\n      id\n      tags\n      user {\n        Address\n        Email\n        FullName\n        MFA\n        PhoneNumber\n        ShowEmail\n        ShowNumber\n        SuburbNo\n        UserJoinDate\n        UserName\n        UserType\n        Verified\n      }\n    }\n  }\n"
variables:
input:
Available: true
Description: "Random description"
Images: "None"
Location: "Sydney"
Price: "2.0"
Title: "No title LMAO"
Type: "rent"
[[Prototype]]: Object
[[Prototype]]: Object
[[Prototype]]: Object
```


```

</details>

### aws-exports.js

```
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:c8d85be2-ccfd-42ea-9da5-2a0225ef221a",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_QfVnfq7LL",
    "aws_user_pools_web_client_id": "34sh3h16tsvvsh6b4svpqdslo6",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "NAME",
        "EMAIL",
        "GENDER",
        "BIRTHDATE",
        "PHONE_NUMBER",
        "ADDRESS"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "borlen-storage105812-staging",
    "aws_user_files_s3_bucket_region": "ap-southeast-2",
    "aws_appsync_graphqlEndpoint": "https://ol7hhh4upbe6ta2zddv5i6ytvi.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "identityPoolId": "ap-southeast-2:c8d85be2-ccfd-42ea-9da5-2a0225ef221a"
};


export default awsmobile;

```

### Manual configuration

```
//Setup Storage
Amplify.configure({
    Storage: {
        AWSS3: {
            bucket: 'borlen-storage105812-staging', //REQUIRED -  Amazon S3 bucket name
            region: 'ap-southeast-2', //OPTIONAL -  Amazon service region
        }
    },
	Auth: {
        identityPoolId: 'ap-southeast-2:c8d85be2-ccfd-42ea-9da5-2a0225ef221a',
		identityPoolRegion: 'ap-southeast-2',
		userPoolId: 'ap-southeast-2_QfVnfq7LL',
		userPoolWebClientId: '34sh3h16tsvvsh6b4svpqdslo6',
    }
});

const myAppConfig = {
    // ...
    'aws_appsync_graphqlEndpoint': 'https://uoavq7onpnemdoo6g72zdrtrvu.appsync-api.ap-southeast-2.amazonaws.com/graphql',
    'aws_appsync_region': 'ap-southeast-2',
    'aws_appsync_authenticationType': 'AMAZON_COGNITO_USER_POOLS', // You have configured Auth with Amazon Cognito User Pool ID and Web Client Id
    // ...
}

Amplify.configure(myAppConfig);
```

### Mobile Device

Pixel XL and IOS

**Comment by svidgen** [comment]
Apologies for the delay. Just wondering if you got unblocked on this issue or if you're still looking for help.

One thing we noticed is you're using pretty old versions of `amplify-js` and the CLI. Are you able to upgrade these?

**Comment by david-mcafee** [comment]
@NiksanJP - are you still looking for help with this issue, and / or were you able to upgrade your versions of Amplify JS and the CLI? For reference, please see @svidgen's [comment](https://github.com/aws-amplify/amplify-js/issues/9852#issuecomment-1614889206). Thank you!
