### ISSUE TITLE
Page freezes on Auth.signOut

### ISSUE THREAD

**Issue by imanubhardwaj** [aws-amplify/amplify-js#9867]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 636.41 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.1 - ~/.nvm/versions/node/v16.14.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.14.1/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.1/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Safari: 15.1
  npmPackages:
    @aws-amplify/auth: ^3.4.34 => 3.4.34 (4.4.2)
    @aws-amplify/ui-react: ^2.9.0 => 2.9.0 
    @aws-amplify/ui-react-internal:  undefined ()
    @aws-amplify/ui-react-legacy:  undefined ()
    @craco/craco: ^7.0.0-alpha.0 => 7.0.0-alpha.3 
    @emotion/react: ^11.8.1 => 11.8.1 
    @emotion/styled: ^11.8.1 => 11.8.1 
    @mui/icons-material: ^5.4.2 => 5.5.0 
    @mui/material: ^5.4.4 => 5.5.0 
    @mui/styled-engine: ^5.4.4 => 5.4.4 
    @tailwindcss/postcss7-compat:  2.2.17 
    @types/lodash: ^4.14.180 => 4.14.180 
    @types/node: ^16.11.26 => 16.11.26 
    @types/react: ^17.0.39 => 17.0.39 
    @types/react-dom: ^17.0.12 => 17.0.13 
    @typescript-eslint/eslint-plugin: ^5.14.0 => 5.14.0 
    @typescript-eslint/parser: ^5.14.0 => 5.14.0 
    autoprefixer: ^10.4.2 => 10.4.2 (9.8.8)
    aws-amplify: ^4.3.15 => 4.3.15 
    aws-amplify-react: ^5.1.9 => 5.1.9 
    axios: ^0.26.1 => 0.26.1 (0.21.4)
    clsx: ^1.1.1 => 1.1.1 
    eslint: ^8.10.0 => 8.10.0 
    eslint-config-airbnb: ^19.0.4 => 19.0.4 
    eslint-plugin-import: ^2.25.4 => 2.25.4 
    eslint-plugin-jsx-a11y: ^6.5.1 => 6.5.1 
    eslint-plugin-react: ^7.29.3 => 7.29.3 
    eslint-plugin-react-hooks: ^4.3.0 => 4.3.0 
    lodash: ^4.17.21 => 4.17.21 
    postcss: ^8.4.8 => 8.4.8 (6.0.23, 7.0.39)
    react: ^17.0.2 => 17.0.2 (16.14.0)
    react-dom: ^17.0.2 => 17.0.2 
    react-query: ^3.34.16 => 3.34.16 
    react-router-dom: ^6.2.2 => 6.2.2 
    react-scripts: 5.0.0 => 5.0.0 
    tailwindcss: npm:@tailwindcss/postcss7-compat@^2.2.17 => undefined (3.0.23)
    typescript: ^4.6.2 => 4.6.2 
  npmGlobalPackages:
    corepack: 0.10.0
    npm: 8.5.0
    pnpm: 6.32.3
    yarn: 1.22.17

```

</details>

### Describe the bug

When I login and try to logout after that it works fine. But if I refresh the page after the signing in and then try to sign out the app freezes. After turning debug mode on, log shows that user has been signed out but nothing happens.

### Expected behavior

Signout should work normally without freezing the UI.

### Reproduction steps

1. Sign in
2. Refresh the page
3. Sign out

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by stocaaro** [comment]
Hello imanubhardwaj@,

Can you provide code snippets (especially the `App.js` and instructions to help us reproduce what you're seeing. Following the [auth flow](https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js/#sign-out) from the documents, it looks like everything is working as expected.

Any additional context you can provide would be very helpful.

Thanks!
Aaron

**Comment by abdallahshaban557** [comment]
Hi @imanubhardwaj 

Can you please provide us with the code snippets as mentioned above?

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!

P.S. For reference, I installed the same amplify packages and versions as detailed in your environment information. I noticed you had `@aws-amplify/auth` at v3 but `aws-amplify` at v4, and also the `aws-amplify-react` package which has been deprecated and has a peer dependency on v3 of many other amplify packages. So, if you run our script to check for duplicate/redundant dependencies, you'll see that you have many incompatible packages and that usually explains a lot of strange behavior in your amplify app.

my dependencies
```js
  "dependencies": {
    "@aws-amplify/auth": "^3.4.34",
    "@aws-amplify/ui-react": "^2.9.0",
    "@tailwindcss/typography": "^0.5.2",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.3.0",
    "@testing-library/user-event": "^13.5.0",
    "autoprefixer": "^10.4.7",
    "aws-amplify": "^4.3.15",
    "aws-amplify-react": "^5.1.9",
    "postcss": "^8.4.14",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-icons": "^4.4.0",
    "react-markdown": "^8.0.3",
    "react-router-dom": "^6.3.0",
    "react-scripts": "5.0.1",
    "react-simplemde-editor": "^5.0.2",
    "tailwindcss": "^3.1.3",
    "uuid": "^8.3.2",
    "web-vitals": "^2.1.4"
  },
  ```
duplicates
<img width="380" alt="Screen Shot 2022-06-26 at 11 44 50 AM" src="https://user-images.githubusercontent.com/16952986/175822644-764c8e99-a36e-4a40-a170-3b1621941242.png">


So, the solution here is probably to remove the `aws-amplify-react` package altogether, you can instead rely on `@aws-amplify/ui-react` for managing auth state via the `Authenticator` component and `useAuthenticator` hook. Finally, make sure to upgrade any other remaining amplify packages to the latest versions by running one of these commands.

# Using YARN
`yarn upgrade --latest --pattern aws-amplify`

# Using NPM
`npx npm-check-updates -i '/@?aws-amplify/' && npm update`
