### ISSUE TITLE
To listen to OAuth responses through Hub (Cognito PreSignUp Exceptions)

### ISSUE THREAD

**Issue by jeff-ong** [aws-amplify/amplify-js#9875]
### Is this related to a new or existing framework?

React

### Is this related to a new or existing API?

Auth

### Is this related to another service?

Cognito PreSigUp Lambda

### Describe the feature you'd like to request

After setting up Cognito to trigger a Lambda function at the PreSignUp step, our web app begins to behave as follow when the Lambda is triggered:

**Result**
`OAuth - Error handling auth response. Error: `
<img width="782" alt="Screen Shot 2022-05-05 at 4 46 02 PM" src="https://user-images.githubusercontent.com/13773039/167023039-82ff39b4-9944-4283-8554-65734486028a.png">

**The PreSignUp Lambda function**
```
   if (!userEmail || userEmail.endsWith("bademaildomain.com")) {
      throw new Error('bad email');
   }
```

This is the desirable result but is there currently a way to catch the "bad email" error through the Hub module and update the UI accordingly ? Currently, the error is only being caught in  OAuth.ts - handleAuthResponse function and not being dispatched to any subscribers.

### Describe the solution you'd like

Allow us to subscribe to a `presignup` and `preauthenticate` event through the Hub module to handle Cognito  authorization/authentication errors accordingly on the frontend.

### Describe alternatives you've considered

Provide documentation about how to add custom Hub events and how to integrate it with Cognito PreSignup Lambda function.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by stocaaro** [comment]
Hello Jeff,

You indicated this issue is related to the PubSub API, but I don't see any details in your description that interact with the PubSub API. If I'm reading this correctly, you are looking to get help with Auth related Hub events.  I've updated the description, happy to have you roll it back with more details on the PubSub interaction if this is actually a PubSub API issue.

Thanks,
Aaron

**Comment by jeff-ong** [comment]
Hi Aaron, 

Thanks for updating the description. I might have overcomplicated the issue with PubSuB API. But yes, please help provide some guidance on how I could use Hub to subscribe to preauthenticate and presignup events.
Thanks, 
Jeff

**Comment by vericardo** [comment]
@jeff-ong I am also experiencing these issues.  One workaround I have found for the time being is to call the Auth.configure function after you subscribe to the 'auth' events via the Hub listener.  There are a number of events which you will start seeing once that change is made including 'configure' itself.  Although this is working, its a fundamentally different way to configure the app and has created at least one side effect which also required a workaround.  I would be nice for the events to be caught w/o having to change where the app is configured as stated in the doc.  Hope this helps.

**Comment by jeff-ong** [comment]
> @jeff-ong I am also experiencing these issues. One workaround I have found for the time being is to call the Auth.configure function after you subscribe to the 'auth' events via the Hub listener. There are a number of events which you will start seeing once that change is made including 'configure' itself. Although this is working, its a fundamentally different way to configure the app and has created at least one side effect which also required a workaround. I would be nice for the events to be caught w/o having to change where the app is configured as stated in the doc. Hope this helps.

Thanks for response but I am hoping to avoid the side effect if possible.

**Comment by vericardo** [comment]
@jeff-ong I completely agree with you and am still looking for another option.  I was just trying to point out that I am also experiencing the same issue and that the Hub listener has the ability to catch those error events but an issue is preventing it from doing so.  From other threads I have seen, everything works as expected.

**Comment by Schadrack10** [comment]
my issue is more on Auth.signin , the auth class is failing to get the user , even after i have used the hub module to listen to the auth events

**Comment by tannerabread** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and are in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
