### ISSUE TITLE
Safari cannot open the page because the address is invalid.

### ISSUE THREAD

**Issue by KrishnarajS-FSP** [aws-amplify/amplify-js#9885]
### Is this related to a new or existing framework?

React Native

### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

When I tried to logout the Facebook login in iPhone with AWS amplifier it moved to the Safari and it show the alert to move back to the app with the "cancel and open" option. when I click the open it redirected to the app. If again login and logout it work fine. if I click the Cancel option and re-login and logout that time I am facing the issues "Safari cannot open the page because the address is invalid". when I clear the all the page in the safari and retry to logout that it work fine.

### Describe the solution you'd like

Need to close that browse page when the "cancel" option is choose.

### Describe alternatives you've considered

Need to close that browse page when the "cancel" option is choose.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by nickarocho** [comment]
Hi @KrishnarajS-FSP , thanks for your question.

It is a bit unclear to me as to the entire authentication flow you are expecting vs. how it is working. Could you please supply us with some code snippets detailing how you are using the Amplify Auth API's within your app? The more the better :)

It would also be helpful if you could please supply the contents of your `package.json` so we can see your app's dependencies and associated versions.

Thanks!

**Comment by abdallahshaban557** [comment]
@KrishnarajS-FSP  - did you get a chance to see the response from @nickarocho ? We need more information to research this further.
