### ISSUE TITLE
SecurityError: The operation is insecure.

### ISSUE THREAD

**Issue by joekendal** [aws-amplify/amplify-js#9886]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

GraphQL API

### Environment information

Safari on Mac

This now also occurs on the amplify docs website too, not just my website.

### Describe the bug

Unhandled Runtime Error
SecurityError: The operation is insecure.

Call Stack
eval

[native code]
./node_modules/paho-mqtt/paho-mqtt.js

.next/static/chunks/pages/_app.js (16511:5)
<unknown>

/_next/static/chunks/webpack.js (685:35)
__webpack_require__

next/static/chunks/webpack.js (37:37)
eval

[native code]
./node_modules/@aws-amplify/pubsub/lib-esm/Providers/MqttOverWSProvider.js

/_next/static/chunks/pages/_app.js (1597:5)
<unknown>

.next/static/chunks/webpack.js (685:35)
__webpack_require__

/_next/static/chunks/webpack.js (37:37)
eval

[native code]
./node_modules/@aws-amplify/pubsub/lib-esm/Providers/AWSAppSyncProvider.js

.next/static/chunks/pages/_app.js (1553:5)
<unknown>

/_next/static/chunks/webpack.js (685:35)
__webpack_require__

.next/static/chunks/webpack.js (37:37)
eval

[native code]
./node_modules/@aws-amplify/pubsub/lib-esm/Providers/index.js

/_next/static/chunks/pages/_app.js (1619:5)
<unknown>

.next/static/chunks/webpack.js (685:35)
__webpack_require__

/_next/static/chunks/webpack.js (37:37)
eval

[native code]
./node_modules/@aws-amplify/pubsub/lib-esm/PubSub.js

.next/static/chunks/pages/_app.js (1630:5)
<unknown>

/_next/static/chunks/webpack.js (685:35)
__webpack_require__

.next/static/chunks/webpack.js (37:37)
eval

[native code]
./node_modules/@aws-amplify/pubsub/lib-esm/index.js

/_next/static/chunks/pages/_app.js (1641:5)
<unknown>

.next/static/chunks/webpack.js (685:35)
__webpack_require__

/_next/static/chunks/webpack.js (37:37)
eval

[native code]
./node_modules/@aws-amplify/api-graphql/lib-esm/GraphQLAPI.js

.next/static/chunks/pages/_app.js (304:5)
<unknown>

/_next/static/chunks/webpack.js (685:35)
__webpack_require__

.next/static/chunks/webpack.js (37:37)
eval

[native code]
./node_modules/@aws-amplify/api-graphql/lib-esm/index.js

/_next/static/chunks/pages/_app.js (315:5)
<unknown>

/.next/static/chunks/webpack.js (685:35)
__webpack_require__

/_next/static/chunks/webpack.js (37:37)
eval

[native code]
./node_modules/@aws-amplify/api/lib-esm/API.js

/.next/static/chunks/pages/_app.js (370:5)
<unknown>

/_next/static/chunks/webpack.js (685:35)
__webpack_require__

/.next/static/chunks/webpack.js (37:37)
eval

[native code]

### Expected behavior

For it not to crash.

### Reproduction steps

Visit https://docs.amplify.aws/lib/q/platform/js/

![Screenshot 2022-05-09 at 14 22 31](https://user-images.githubusercontent.com/13680617/167419249-47fae3ba-1eed-48f0-8ab5-d367cd641067.png)
 

### Log output

![Screenshot 2022-05-09 at 14 23 03](https://user-images.githubusercontent.com/13680617/167419342-d0861689-27ac-4f96-90b1-a17822052c7f.png)

**Comment by chrisbonifacio** [comment]
Hi @joekendal 👋 thanks for raising this issue! I tried clicking on the docs link you provided but the page loaded normally on my end. Are you experiencing this issue on a hosted application of yours?

**Comment by joekendal** [comment]
@chrisbonifacio have you tried using Safari on Mac? That is the only environment I have found to cause this error.

**Comment by chrisbonifacio** [comment]
@joekendal I did but same result unfortunately(?). What version of Safari might you be using? I'm also on a M1 Mac, not sure if that matters yet though but just in case.

This is the page you linked, opened on Safari on my machine. I also tried clicking through the links, no issues yet.

<img width="1728" alt="Screen Shot 2022-05-09 at 4 14 20 PM" src="https://user-images.githubusercontent.com/16952986/167490069-633c034a-7742-4914-be4d-83a903bd7bce.png">

**Comment by joekendal** [comment]
After further investigation, I've discovered the root of the problem was twofold:

Using ssr: true on a non-ssr page 

Importing and configuring Amplify instead of just the sub-package e.g import { Auth } from '@aws-amplify/auth'.

**Comment by abdallahshaban557** [comment]
@joekendal - with that realization, is your issue resolved?

**Comment by joekendal** [comment]
Well it doesn't really make sense why it would occur in the amplify docs.

**Comment by abdallahshaban557** [comment]
@joekendal - we will share this issue with our documentation team to try to replicate it, Chris and I have not been able to replicate it on our machines.
