### ISSUE TITLE
Subscriptions not working (Angular)

### ISSUE THREAD

**Issue by spc16670** [aws-amplify/amplify-js#9889]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.14.2

### Amplify CLI Version

7.6.26

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

Enabled TTL on the table that I want to have subscriptions working on

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

GRAPHQL Subscriptions not working - no data updates

### Expected behavior

I want to be notified any time a new object is insert to the table I am subscribing to

### Reproduction steps

```
constructor(private apiSerivce: APIService) {}

this.apiSerivce.OnCreateLogsListener.subscribe(d => {
  console.log(d)
})
```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line

type Logs @model
  @auth(rules: [
    # Root (crud)
    { allow: groups, groups: ["Root"] }
  ])
  @key(fields: ["id"])
  @key(name: "logsByCreatedAt", fields: ["createdAt"], queryField: "logsByCreatedAt")
{
  id: String!
  message: String!
  component: String!
  createdAt: AWSDateTime!
  timestamp: Int
  ttl: Int
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

I can see in the Network tab WebSocket subscription being established but no data coming from the api.

**Comment by chrisbonifacio** [comment]
Hi @spc16670 👋 thanks for raising this issue. I noticed you said "Enabled TTL on the table that I want to have subscriptions working on". This sounds like you enabled DataStore on your API. Can you check in DynamoDB for any records that might be missing a `_version` field?

**Comment by spc16670** [comment]
I don't know what is DataStore - I enabled TTL using aws cli. None of my models features a _version attribute. I am confused by your response.

**Comment by chrisbonifacio** [comment]
@spc16670 Ohh, sorry for the confusion. I mistook your mentioning of enabling TTL for enabling DataStore. So you just enabled TTL by itself on a DynamoDB table. Disregard my previous comment!

So, to follow up, would you mind sharing the schema for the `Log` model you're trying to subscribe to?
Also, how are you trying to trigger the subscription? AppSync/GraphQL mutation (ex. createLog) or directly through DynamoDB (ex. AWS.DynamoDB.DocumentClient.put)?

**Comment by spc16670** [comment]
Schema and usage example are already reported in the ticket.

I have a 'background job' that puts the data into the table.

**Comment by chrisbonifacio** [comment]
How is the 'background' job putting the data into the table? one of the methods I mentioned in my previous comment? Is it a Lambda?

I see how you're establishing the subscription in the usage example shared but I need to know how you're creating the records to know if it would actually trigger the subscription. For example, if it's directly putting an item in the DynamoDB table, that wouldn't trigger the AppSync subscription. The creation has to be done through AppSync (i.e. a graphql mutation).

**Comment by spc16670** [comment]
got you, yeah, that  must be it then, let me give it a try - I will reopen the ticket if it still does not work.

**Comment by spc16670** [comment]
Thank you very much for looking into this!
