### ISSUE TITLE
Add the ability to cancel any API call

### ISSUE THREAD

**Issue by stevemao** [aws-amplify/amplify-js#989]
Do you want to request a feature or report a bug?
feature
What is the current behavior?
an api call can't be canceled once made.

What is the expected behavior?
https://github.com/axios/axios#cancellation

**Comment by samuelcastro** [comment]
Any update on this? We really would like to start using in-flight request cancelation.

**Comment by ahsanwtc** [comment]
they say Amplify.API uses axios under the hood for api functions. Axios has the support for in flight call cancellation. Is there any way to tap into that?

**Comment by kbuechl** [comment]
Looks like I found this just in time. I am going to take a stab at this, so I don't want the issue to close just yet. Working on a few minor aspects of this now, just deciding on how to proceed with a few opinionated parts, then testing.

**Comment by kbuechl** [comment]
Here is what I am thinking about how the implementation should look. I think axios's cancel token should be aliased so that we don't need to import axios to do anything. This is just a single APIcall example. but you could  reuse the same token for multiple calls if you wanted to cancel all, or create a source for each call you want to cancel independently. 

```javascript
const { API } = require('aws-amplify');
const cancelTokenSource = API.CancelToken.Source();
   const init = {
   cancelToken: cancelTokenSource.token,
   //...
};
let response = await API.get(API_NAME, PATH, init);
//...
```

Then when you wanted to cancel (like when a UI component is unmounting)
```javascript
cancelTokenSource.cancel("Tired of waiting");
```

**Comment by houmark** [comment]
@kbuechl did you make more progress on this?

Was this also intended to work for GraphQL requests meaning `await API.graphql(listItems, {limit: 100})`?

**Comment by cor1** [comment]
+1 this would be useful

**Comment by kbuechl** [comment]
Yeah I have the code for the rest API ready to go but was having problems building and running the test suite. I set it down and haven't come back to it. I'll pick it back up Monday. I was only looking to do the restapi portion since axios supports it already.

**Comment by houmark** [comment]
Sounds great @kbuechl, I'm looking to get it working with GraphQL requests. I have some filters and they apply as you click or type and I'm looking to cancel pending requests if more filters are added or removed. Currently race situations can happen where an earlier request finishes after the most recent one and that results in the wrong data being displayed according to the filter.

I was not aware that GraphQL requests are done using a different request library than REST request as GraphQL requests, in the end, is just a POST with more or less the same payload and headers as a REST call.

**Comment by kbuechl** [comment]
@houmark Sorry I didn't mean to imply they were different under the covers, just that I wasn't sure without looking into it! I took a peak and the graphql stuff any you are right it all uses the same core functions underneath using axios.

**Comment by kbuechl** [comment]
@houmark @cor1 I am not super familiar with the graphql client, how do you feel about this (very similar to rest api example above)? I took a look through the amplify docs on the graphql client and tried to just keep it simple and keep the cancel token syntax the same as what axios uses today.

```javascript
import { API } from 'aws-amplify';
import * as queries from './graphql/queries';

let cancelTokenSource;

// ex1: todo with no parameters
cancelTokenSource = API.CancelToken.source();
const allTodos = await API.graphql(graphqlOperation(queries.listTodos, null,  cancelTokenSource ));

// ex2: Query using a parameter
cancelTokenSource = API.CancelToken.source();
const oneTodo = await API.graphql(graphqlOperation(queries.getTodo, { id: 'some id' }, cancelTokenSource));

// ... elsewhere if you detect a change 
cancelTokenSource.cancel('reason if you want one');
```

**Comment by kbuechl** [comment]
@houmark @cor1 I went ahead and updated the graphql stuff as well. It would work similar to this, I also added it into the subscription process the same way as listed below. This would result in an error you need to handle in your subscription similar to the catch block below

```javascript
import { API } from 'aws-amplify';
import * as queries from './graphql/queries';

let cancelTokenSource;

try {
  cancelTokenSource = API.CancelToken.source();
  const allTodos = await API.graphql(graphqlOperation(queries.listTodos, {limit: 100}, cancelTokenSource.token));
//can also use  await API.graphql({queries.listTodos, {limit: 100}, cancelTokenSource.token});
}
catch (err) {
  if (!API.isCancel(err)) {
     // handle error ...
  }
}

// ... elsewhere if you detect a change 
cancelTokenSource.cancel('reason if you want one');
```

**Comment by houmark** [comment]
This is looking great! I hope this PR makes it in really fast, as this is gonna solve a lot of race situations for us... Thanks for your work @kbuechl — I will try to test out your PR, but I'm traveling the next 2-3 days so it may not happen until next week.

**Comment by a428tm** [comment]
does this mean it works now?

**Comment by houmark** [comment]
@a428tm afraid not, this is an open PR waiting for approval and merge. Hopefully, it'll get some attention soon!

**Comment by a428tm** [comment]
@houmark thanks for the quick response. if you don't mind me bugging you.. there isn't any workaround at the moment, is there? :)

**Comment by houmark** [comment]
Not really. This should cancel the request, which should save bandwidth and all that, but if you're more concerned about not overwriting data in your UI with a delayed request from a race situation because you have multiple requests at the same time, then you could make some kind of local solution where you keep track of each request you have in-flight and ignore anyone but the very latest one.

**Comment by a428tm** [comment]
@houmark understood!

**Comment by ex3emxl** [comment]
@kbuechl I tried use code-snippet witch you propose, but got error " Property 'CancelToken' does not exist on type 'APIClass' " 
I am using "aws-amplify": "1.1.29" and "aws-amplify-react": "2.3.9". Any ideas?

**Comment by ex3emxl** [comment]
@kbuechl I tried use code-snippet witch you propose, but got error " Property 'CancelToken' does not exist on type 'APIClass' "
I am using "aws-amplify": "1.1.29" and "aws-amplify-react": "2.3.9". Any ideas?

**Comment by kbuechl** [comment]
@ex3emxl this has not been added into amplify yet. Once the pull request is finished it will be merged to master, then it will be in the next release after that. You can keep an eye on the pull request (linked above) and also keep an eye on the 'Releases' tab on the repo's page.

**Comment by minaairsupport** [comment]
yea I believe we need this feature to be included
