### ISSUE TITLE
TypeError: _datastore.default is undefined

### ISSUE THREAD

**Issue by vkanagarajan** [aws-amplify/amplify-js#9903]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

DataStore

### Amplify Categories

storage

### Environment information

   "react": "16.13.1",
        "react-native": "0.63.4",
"aws-amplify": "4.3.22",
 "@aws-amplify/datastore": "3.11.1",

```
# Put output below this line
Error : 
TypeError: _datastore.default is undefined

```

</details>

### Describe the bug

TypeError: _datastore.default is undefine
![Simulator Screen Shot - iPad Air 2 - 2022-05-13 at 22 42 53](https://user-images.githubusercontent.com/53504749/168334656-d55faa6e-70cf-483c-846e-2754e9fbcba3.png)
d

### Expected behavior

it will run without error 

### Reproduction steps

After installing the pacakge getting error 

"aws-amplify": "4.3.22",
 "@aws-amplify/datastore": "3.11.1",

TypeError: _datastore.default is undefine

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

**Comment by chrisbonifacio** [comment]
Hi @vkanagarajan 👋 thanks for raising this issue. Can you share how you're importing DataStore in your project?

Did you create your app using the React Native CLI or the Expo CLI?

**Comment by vkanagarajan** [comment]
import Amplify, { DataStore } from '@aws-amplify/datastore';

import awsConfig from '../../src/aws-exports'; 
Amplify.configure(awsConfig);


I am using  React Native CLI

**Comment by vkanagarajan** [comment]
@chrisbonifacio i have realized my import Amplify, { DataStore } from '@aws-amplify/datastore'; it was wrong 

import Amplify from 'aws-amplify';
import awsConfig from '../../src/aws-exports';
Amplify.configure(awsConfig);


If i am using Amplify from 'aws-amplify'; 
. I am not getting error

**Comment by chrisbonifacio** [comment]
ah, nice catch! Are you unblocked then?
