### ISSUE TITLE
forgetSpecificDevice or forgetAllDevices?

### ISSUE THREAD

**Issue by aligg** [aws-amplify/amplify-js#9904]
### Is this related to a new or existing API?

Authentication

### Describe the feature you'd like to request

In the Authentication API we expose: `rememberDevice`, `forgetDevice`, and `fetchDevices`. 

However, I'd like to allow users to forget a specific device (not the one they are currently using) or just forget all devices. 

Is it possible to create `forgetSpecificDevice` or `forgetAllDevices`? 

I did note that `forgetSpecificDevice` exists within the amplify codebase, but it isn't made available via the AuthClass.  

### Describe the solution you'd like

A method e.g. `forgetSpecificDevice` or `forgetAllDevices` in AuthClass. 

### Describe alternatives you've considered

I considered moving to the backend and using boto3 but couldn't figure out how to implement remember / forget there, and given the rest of my codebase is using the JS SDK I wanted to ask about this. 

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by nickarocho** [comment]
Hi @aligg, thanks for opening this and asking about `Auth.forgetDevice()` (and specifically trying to target a _specific device_ to forget).

When you call `Auth.forgetDevice()` for the `currentAuthenticatedUser` within a Multi-Factor Authentication (MFA)-enabled Cognito User pool, **this will remove the specific device which the current user is making the request from** out of the list of remembered devices returned with `Auth.fetchDevices()`. (keep in mind, the device is still tracked - see the [terminology definitions](https://docs.amplify.aws/lib/auth/device_features/q/platform/js/#fetch-devices) for more info on what distinguishes `tracked` vs. `remembered`)

It sounds like you're probably already aware of all this, and maybe instead want to be able to target a different device than the one the user is currently using, is that right? If not, could you please explain your detailed use case as to your ideal scenario so we can fully understand the feature you are looking for us to implement?

Thanks!

**Comment by aligg** [comment]
Hey @nickarocho thanks for getting back!

In an ideal scenario, I would like to be able to pass in the device_key to forget a *specific* remembered device. I would like to be able to implement something like the following, where the user sees a list of their remembered devices and can choose one to forget:
<img width="922" alt="Screen Shot 2022-05-17 at 2 32 22 PM" src="https://user-images.githubusercontent.com/7331495/168913605-ddb7b703-0d9d-4f56-a0c5-8c5eb2792b7c.png">

Currently we can use `fetchDevices` to display the list, but I don't think there is functionality exposed via amplify js to `forgetSpecificDevice(device_key)`. 

Does that help provide more color? 

For anyone who reads this in the future, for now I am planning to use boto3 and create a backend call to `admin_forget_device()` but I still think this would be super useful functionality to add to amplify js!

**Comment by cwomack** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.

You can now call the forgetDevice() API in v6 and then pass in the specific deviceId to accomplish this.
```
// usecase 1: current device
await forgetDevice();

// usecase 2: current/external device
// you can also get deviceId from fetchDevices()
await forgetDevice({
  device: {
    id: "myDeviceId",
  },
});

// usecase 3: current/external device
const devices = await fetchDevices();
await forgetDevice({
  device: devices[0],
});
```

**Comment by sonny-jordan** [comment]
There is no release announcement nor documentation for amplify v6 -> forgetDevice({
  device: devices[0],
});

Can we re-open this ticket?
