### ISSUE TITLE
No api-key configured (React Native 0.68.2)

### ISSUE THREAD

**Issue by Oriole-Alex** [aws-amplify/amplify-js#9929]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.14.2

### Amplify CLI Version

8.2.0

### What operating system are you using?

windows 11

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth

### Amplify Commands

Not applicable

### Describe the bug

Running android app (npx react-native run-android) builds successfully however returns the error below.
We have been using API key for Auth, it was working previously, however updating to a new react native  (0.68.2) version, it stops working.
We have tried the steps mentioned in the console log with no success.

error fetching global setting: [Error: No api-key configured]

[ERROR] 11:01.439 AuthError -
            Error: Amplify has not been configured correctly.
            The configuration object is missing required auth properties.
            This error is typically caused by one of the following scenarios:

            1. Did you run `amplify push` after adding auth via `amplify add auth`?
                See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information

            2. This could also be caused by multiple conflicting versions of amplify packages, see (https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js) for help upgrading Amplify packages.

### Expected behavior

Amplify should be authorised correctly already

### Reproduction steps

1. Using react nativ (0.68.2) run amplify pull (including amplify auth)
2. run amplify codegen configure
3. run amplify codegen
4. run npx react-native run-android

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
LOG  error fetching global setting: [Error: No api-key configured]
 ERROR  [ERROR] 11:01.439 AuthError -
            Error: Amplify has not been configured correctly.
            The configuration object is missing required auth properties.
            This error is typically caused by one of the following scenarios:

            1. Did you run `amplify push` after adding auth via `amplify add auth`?
                See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information

            2. This could also be caused by multiple conflicting versions of amplify packages, see (https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js) for help upgrading Amplify packages.
 ERROR  [ERROR] 11:01.444 AuthError -
            Error: Amplify has not been configured correctly.
            The configuration object is missing required auth properties.
            This error is typically caused by one of the following scenarios:

            1. Did you run `amplify push` after adding auth via `amplify add auth`?
                See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information

            2. This could also be caused by multiple conflicting versions of amplify packages, see (https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js) for help upgrading Amplify packages.
 LOG  error checking The user is not authenticated


```

</details>

### Additional information

I already updated all my packages, re-ran amplify configure and tried it in another enviorment

**Comment by tannerabread** [comment]
@Oriole-Alex Did I understand that you were able to keep this running because of a backup you had made of the project? Did you ever get it working outside of that?

**Comment by tannerabread** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
