### ISSUE TITLE
PubSub module: subscribing with wildcards

### ISSUE THREAD

**Issue by npellegrin** [aws-amplify/amplify-js#993]
Hello !

We are using the AWS IoT broker with Amplify, and we observed that PubSub module do not work when we try to subscribe with wilcard characters (as we can do in the AWS console). The two example below will "work" without error, but nothing will be received:

```
PubSub.subscribe('my-topic/#').subscribe({
    next: data => console.log('Message received', data),
    error: error => console.error(error),
    close: () => console.log('Done'),
});
```

```
PubSub.subscribe('my-topic/+/something-else').subscribe({
    next: data => console.log('Message received', data),
    error: error => console.error(error),
    close: () => console.log('Done'),
});
```

There is nothing in the documentation about it. Is it a limitation of the AWS IoT broker, the websocket transport protocol, or the Javascript library ?

If it is currently not supported, I can make a pull request on the documentation to add this warning.

**Comment by mlabieniec** [comment]
@npellegrin thanks for reporting this. Does your IoT policy have the correct permissions for subscribing via wildcard?
https://docs.aws.amazon.com/iot/latest/developerguide/pub-sub-policy.html

**Comment by npellegrin** [comment]
Hi @mlabieniec thanks for the reply :)

I have temporary set an "open-world" policy for debugging on IoT policy and the federated IAM policy. Both were:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iot:Connect",
        "iot:Publish",
        "iot:Receive",
        "iot:Subscribe"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}
```

When I try to suscribe to a topic without special characters it works (messages are received):
```
PubSub.subscribe('my-topic/foo/bar').subscribe({
    next: data => console.log('Message received', data),
    error: error => console.error(error),
    close: () => console.log('Done'),
});
```

I am not sure it is a permission problem, when I put a restrictive policy, and try to subscribe to a topic I am not authorized to, I have in the console the expected error message "AMQJS0008I Socket closed."

Here, I have no error message in the Javascript console, all seems to be fine, but I do not receive the MQTT messages.

**Comment by syeem** [comment]
@manueliglesias Any updates on this? I have facing the exact same problem.

**Comment by onyii5119** [comment]
I have been trying to get Amplify PubSub to work but without success. Has anyone been able to get the current version to work? Do you have an example to share?

**Comment by davevh** [comment]
I am facing the same issue with using wild cards. It is not working. Is there a work around. If i subscribe without wildcards it works. But can i subscribe to more then one at once ?

```PubSub.subscribe('+/mytopic').subscribe({
  next: data => console.log("Message:", data.value),
  error: error => console.error(error),
  close: () => console.log('Done')
});```

**Comment by onyii5119** [comment]
Hi Dave,
I have not been able to get PubSub to work for me. Could you please publish an outline of what works for you (even without wild cards). Also, please include your code for receiving messages.

My platform is Angular/Ionic. AS a matter of fact this simple code does not compile clean for me. 
PubSub.subscribe('+/mytopic').subscribe({
  next: data => console.log("Message:", data.value),
  error: error => console.error(error),
  close: () => console.log('Done')
});
In my my own environment this is what compiles (requires 2 params):
PubSub.subscribe('+/mytopic', null).subscribe({
  next: data => console.log("Message:", data.value),
  error: error => console.error(error),
  close: () => console.log('Done')
});
Can't really figure out what is wrong. I am using aws-amplify version 1.1.7

Thanks.

**Comment by dominictwlee** [comment]
same issue here

**Comment by Pwntus** [comment]
I'm also experiencing this issue at `aws-amplify@1.1.7`.
A topic containing an ending *#* will not trigger the `next()` callback.
