### ISSUE TITLE
DataStore loses database connection on Safari/Chrome (iPad Mini)

### ISSUE THREAD

**Issue by dsharygin** [aws-amplify/amplify-js#9946]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

DataStore

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 91.23 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 100.0
    Safari: 15.4
  npmPackages:
    @aws-amplify/core: ^4.2.1 => 4.2.1 
    @aws-amplify/datastore: ^3.2.2 => 3.2.2 
    @aws-amplify/ui-react: ^2.10.4 => 2.10.4 
    @aws-amplify/ui-react-internal:  undefined ()
    @aws-amplify/ui-react-legacy:  undefined ()
    @babel/core: ^7.17.10 => 7.17.10 (7.4.5, 7.12.3, 7.10.5)
    @babel/preset-env: ^7.17.10 => 7.17.10 (7.4.5, 7.12.1)
    @babel/preset-typescript: ^7.16.7 => 7.16.7 (7.12.1)
    @cypress/code-coverage: ^3.9.11 => 3.9.11 
    @cypress/instrument-cra: ^1.4.0 => 1.4.0 
    @cypress/react: ^5.12.0 => 5.12.0 
    @cypress/webpack-dev-server: ^1.8.0 => 1.8.0 
    @date-io/date-fns: ^1.3.13 => 1.3.13 
    @emotion/react: ^11.8.1 => 11.8.1 
    @emotion/styled: ^11.8.1 => 11.8.1 
    @istanbuljs/nyc-config-typescript: ^1.0.1 => 1.0.1 
    @material-ui/core: ^4.12.2 => 4.12.2 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/pickers: ^3.3.10 => 3.3.10 
    @mui/material: ^5.4.4 => 5.4.4 
    @mui/x-data-grid: ^5.10.0 => 5.10.0 
    @reduxjs/toolkit: ^1.6.1 => 1.6.1 
    @reduxjs/toolkit-query:  1.0.0 
    @reduxjs/toolkit-query-react:  1.0.0 
    @testing-library/jest-dom: ^5.14.1 => 5.14.1 
    @testing-library/react: ^12.0.0 => 12.0.0 
    @testing-library/user-event: ^13.2.1 => 13.2.1 
    @types/jest: ^27.5.0 => 27.5.0 
    @types/lodash: ^4.14.178 => 4.14.178 
    @types/node: ^16.11.10 => 16.11.10 (14.17.34, 8.10.66, 14.17.6)
    @types/qs: ^6.9.7 => 6.9.7 
    @types/react: ^17.0.37 => 17.0.37 
    @types/react-dom: ^17.0.11 => 17.0.11 
    @types/react-router: ^5.1.18 => 5.1.18 
    @types/react-router-dom: ^5.3.2 => 5.3.2 
    @types/react-text-mask: ^5.4.10 => 5.4.10 
    assert:  1.0.0 
    async-mutex: ^0.3.2 => 0.3.2 
    aws-amplify: ^4.2.1 => 4.2.1 
    aws-appsync: ^4.1.6 => 4.1.6 
    babel-jest: ^26.6.3 => 26.6.3 
    babel-plugin-istanbul: ^6.1.1 => 6.1.1 (6.0.0)
    babel-plugin-transform-class-properties: ^6.24.1 => 6.24.1 
    bundle-optimisations:  1.0.0 
    chai: ^4.3.4 => 4.3.4 
    cross-env: ^7.0.3 => 7.0.3 
    cypress: ^9.2.0 => 9.2.0 
    cypress-file-upload: ^5.0.8 => 5.0.8 
    cypress-wait-until: ^1.7.2 => 1.7.2 
    dev-404-page:  1.0.0 
    expect.js:  0.3.1 
    functions:  1.0.0 
    gatsby: ^3.10.2 => 3.10.2 
    graphql-tag: ^2.12.6 => 2.12.6 
    internal-data-bridge:  1.0.0 
    istanbul-lib-coverage: ^3.2.0 => 3.2.0 (3.0.0)
    jest: ^26.6.0 => 26.6.0 
    load-babel-config:  1.0.0 
    localforage: ^1.9.0 => 1.9.0 
    lodash: ^4.17.21 => 4.17.21 
    mocha: ^9.1.3 => 9.1.3 
    notistack: ^1.0.10 => 1.0.10 
    nyc: ^15.1.0 => 15.1.0 
    prod-404:  1.0.0 
    qs: ^6.10.1 => 6.10.1 (6.5.2, 6.7.0)
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    react-image-file-resizer: ^0.4.8 => 0.4.8 
    react-redux: ^7.2.6 => 7.2.6 
    react-router-dom: ^5.2.0 => 5.2.0 
    react-scripts: 4.0.3 => 4.0.3 
    react-text-mask: ^5.4.3 => 5.4.3 
    react-uuid: ^1.0.2 => 1.0.2 
    recoil: ^0.6.1 => 0.6.1 
    redux: ^4.1.2 => 4.1.2 (3.7.2)
    source-map-support: ^0.5.21 => 0.5.21 
    text-mask-addons: ^3.8.0 => 3.8.0 
    ts-mockito: ^2.6.1 => 2.6.1 
    ts-node: ^10.4.0 => 10.4.0 (9.1.1)
    typescript: ^4.6.3 => 4.6.3 
    web-vitals: ^2.1.0 => 2.1.0 
    webpack-dev-server: ^3.11.1 => 3.11.1 (3.11.2)
    webpack-theme-component-shadowing:  1.0.0 
    workbox-background-sync: ^6.1.5 => 6.1.5 (5.1.4)
    workbox-broadcast-update: ^6.1.5 => 6.1.5 (5.1.4)
    workbox-cacheable-response: ^6.1.5 => 6.1.5 (5.1.4)
    workbox-core: ^6.1.5 => 6.1.5 (5.1.4)
    workbox-expiration: ^6.1.5 => 6.1.5 (5.1.4)
    workbox-google-analytics: ^6.1.5 => 6.1.5 (5.1.4)
    workbox-navigation-preload: ^6.1.5 => 6.1.5 (5.1.4)
    workbox-precaching: ^6.1.5 => 6.1.5 (5.1.4)
    workbox-range-requests: ^6.1.5 => 6.1.5 (5.1.4)
    workbox-routing: ^6.1.5 => 6.1.5 (5.1.4)
    workbox-strategies: ^6.1.5 => 6.1.5 (5.1.4)
    workbox-streams: ^6.1.5 => 6.1.5 (5.1.4)
  npmGlobalPackages:
    @aws-amplify/cli: 8.0.3
    corepack: 0.10.0
    lighthouse: 9.6.1
    npm: 8.5.0
    serve: 13.0.2
    yarn: 1.22.18
```

</details>

### Describe the bug

We have an app that prompts users to fill out forms. As part of the form submission, users can upload photos. The form data is modeled as a schema.graphql type (i.e. Todo). The images being uploaded are modeled as a schema.graphql type (Attachment) with a "key" pointer to the actual file contents in S3/localforage. Users can upload up to 10 images at a time. We use DataStore for data interactions so that users can submit forms while offline. There is nothing unusual about the way we interact with the DataStore code-wise.

The following bug is reproduce-able on Safari and Chrome on 6th generation iPad Mini running OS version 15.1:

Users continuously submit a form with 10 images at a time each. After about 30 form submissions (30 Todos and 300 Attachments), an error is thrown:
```
Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
```

After this, all save operations on DataStore fail (any type). Likewise, all queries return an empty array. The only thing that helps remedy the issue is manual page refresh, which executes DataStore.configure, followed by a DataStore query. The data collected prior to the issue seems to exist.

### Expected behavior

DataStore operations working as expected. If an error is thrown for some reason, DataStore should recover on its own and allow the client app to retry the operations that failed.

### Reproduction steps

See the bug description.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Mobile Device

iPad Mini (6th generation)

### Mobile Operating System

15.1

### Mobile Browser

Chrome, Safari

**Comment by dsharygin** [comment]
We discovered another issue with DataStore that is potentially related, but not sure if it's DataStore hitting some bottleneck on iPad Mini or if it's actually losing the connection as originally reported.

We have a button that triggers a DataStore query (pagination controls: Next/Previous). If we click on it multiple times in rapid succession, DataStore enters the state where it does not return any results or does not save anything. Again, this is reproduce-able on both Chrome and Safari on a Mini.

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!

**Comment by dsharygin** [comment]
Hi, sorry for the late response. We figured out what the issue was. Our application had a memory leak in FileReader usage due to not cleaning up the event listener: https://stackoverflow.com/questions/72663368/filereader-page-memory-leak/72676857

The memory leak didn't manifest on Heap memory, so it was difficult to pinpoint. Seems like the side effect of the browser window VM running out of page memory was dropping IndexedDB connections, which affected DataStore.
