### ISSUE TITLE
Can't mock Auth.currentSession() for Jest unit testing

### ISSUE THREAD

**Issue by dragoshcode** [aws-amplify/amplify-js#9952]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line


  System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 165.25 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.18 - ~/Desktop/portal/node_modules/.bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Firefox Developer Edition: 102.0
    Safari: 15.4
  npmPackages:
    @aws-amplify/ui-react: ^2.18.3 => 2.18.3 
    @aws-amplify/ui-react-internal:  undefined ()
    @aws-amplify/ui-react-legacy:  undefined ()
    @babel/core: ^7.18.2 => 7.18.2 (7.12.3)
    @babel/preset-env: ^7.18.2 => 7.18.2 
    @babel/preset-typescript: ^7.17.12 => 7.17.12 
    @emotion/react: ^11.4.0 => 11.9.0 
    @emotion/styled: ^11.3.0 => 11.8.1 
    @mui/icons-material: ^5.2.1 => 5.8.2 
    @mui/lab: ^5.0.0-alpha.50 => 5.0.0-alpha.84 
    @mui/material: ^5.0.3 => 5.8.2 
    @mui/styles: ^5.0.1 => 5.8.0 
    @mui/system: ^5.0.3 => 5.8.2 
    @prisma/client: ^3.13.0 => 3.14.0 
    @reduxjs/toolkit: ^1.6.2 => 1.8.2 
    @reduxjs/toolkit-query:  1.0.0 
    @reduxjs/toolkit-query-react:  1.0.0 
    @testing-library/jest-dom: ^5.11.4 => 5.16.4 
    @testing-library/react: ^11.1.0 => 11.2.7 
    @testing-library/user-event: ^12.1.10 => 12.8.3 
    @typeform/embed: ^1.18.1 => 1.35.1 
    @typeform/embed-react: ^1.1.2 => 1.16.0 
    @types/history: ^2.0.45 => 2.0.51 (4.7.11)
    @types/hoist-non-react-statics: ^3.3.1 => 3.3.1 
    @types/istanbul-lib-report: ^3.0.0 => 3.0.0 
    @types/jest: ^27.5.1 => 27.5.1 
    @types/react-dom: ^17.0.11 => 17.0.17 
    @types/react-redux: ^7.1.18 => 7.1.24 
    @types/react-resizable: ^1.7.4 => 1.7.4 
    @types/react-router: ^5.1.18 => 5.1.18 
    @types/react-router-dom: ^5.1.7 => 5.3.3 
    @types/segment-analytics: ^0.0.34 => 0.0.34 
    @typescript-eslint/eslint-plugin: ^4.28.2 => 4.33.0 
    @typescript-eslint/parser: ^4.28.2 => 4.33.0 
    @typescript-eslint/typescript-estree: ^5.22.0 => 5.27.0 (4.33.0, 3.10.1)
    amazon-cognito-identity-js: ^5.2.8 => 5.2.9 
    aws-amplify: ^4.3.24 => 4.3.24 
    babel-jest: ^28.1.0 => 28.1.0 (26.6.3)
    babel-preset-env: ^1.7.0 => 1.7.0 
    caniuse-lite: ^1.0.30001243 => 1.0.30001344 
    date-fns: ^2.23.0 => 2.28.0 
    eslint: ^7.30.0 => 7.32.0 
    eslint-config-airbnb: ^18.2.1 => 18.2.1 
    eslint-config-prettier: ^8.3.0 => 8.5.0 
    eslint-import-resolver-typescript: ^2.4.0 => 2.7.1 
    eslint-plugin-import: ^2.23.4 => 2.26.0 
    eslint-plugin-jsx-a11y: ^6.4.1 => 6.5.1 
    eslint-plugin-prettier: ^3.4.0 => 3.4.1 
    eslint-plugin-react: ^7.24.0 => 7.30.0 
    eslint-plugin-react-hooks: ^4.2.0 => 4.5.0 
    husky: ^7.0.0 => 7.0.4 
    identity-obj-proxy: ^3.0.0 => 3.0.0 
    jest: ^28.1.0 => 28.1.0 (26.6.0)
    jest-environment-jsdom: ^28.1.0 => 28.1.0 (26.6.2)
    jsdom: ^19.0.0 => 19.0.0 (16.7.0)
    logrocket: ^2.1.2 => 2.2.1 
    markdown-to-jsx: ^7.1.3 => 7.1.7 
    msw: ^0.36.5 => 0.36.8 
    notistack: ^2.0.2 => 2.0.5 
    prettier: ^2.3.2 => 2.6.2 
    prisma: ^3.13.0 => 3.14.0 
    re-resizable: ^6.9.9 => 6.9.9 
    react: ^17.0.2 => 17.0.2 
    react-cool-dimensions: ^2.0.7 => 2.0.7 
    react-dom: ^17.0.1 => 17.0.2 
    react-draggable: ^4.4.5 => 4.4.5 
    react-flow-renderer: ^10.1.2 => 10.3.4 
    react-height: ^3.0.2 => 3.0.2 
    react-html-parser: ^2.0.2 => 2.0.2 
    react-html-parser-demo:  0.0.0 
    react-icons: ^4.3.1 => 4.4.0 
    react-markdown: ^7.0.0 => 7.1.2 
    react-player: ^2.9.0 => 2.10.1 
    react-query: ^3.34.16 => 3.39.1 
    react-redux: ^7.2.2 => 7.2.8 
    react-router-dom: ^5.2.0 => 5.3.3 
    react-scripts: 4.0.1 => 4.0.1 
    react-sizeme: ^3.0.2 => 3.0.2 
    react-spring: ^9.4.4 => 9.4.5 
    react-visibility-sensor: ^5.1.1 => 5.1.1 
    redux: ^4.0.5 => 4.2.0 
    simplebar-react: ^2.3.6 => 2.4.1 
    styled-components: ^5.3.5 => 5.3.5 
    styled-components/macro:  undefined ()
    styled-components/native:  undefined ()
    styled-components/primitives:  undefined ()
    ts-jest: ^28.0.3 => 28.0.3 
    ts-node: ^10.8.0 => 10.8.0 
    typescript: ^4.1.3 => 4.7.2 
    use-screenfull: ^0.0.4 => 0.0.4 
    use-screenfull-example:  0.0.0 
    v8-to-istanbul: ^9.0.0 => 9.0.0 (7.1.2)
    web-vitals: ^0.2.4 => 0.2.4 
    xterm: ^4.16.0 => 4.18.0 
    xterm-addon-fit: ^0.5.0 => 0.5.0 
    yarn: ^1.22.18 => 1.22.18 
  npmGlobalPackages:
    corepack: 0.10.0
    npm: 8.5.5
    yarn: 1.22.18

```

</details>

### Describe the bug

I'm writing a unit test with Jest for the login page to render
Jest throws the next error:
![SCR-20220601-hko](https://user-images.githubusercontent.com/88434441/171396609-8470499e-ef49-49f6-b755-430542e0b79a.png)

I use Cognito for the User Pool and Amplify just for the Sign In & Sign Up functionality so I simply don't need to configure AWS Amplify Hosting as asked in the error message from Jest, and also I checked for package duplicates, there are no duplicates

### Expected behavior

Test should pass, but I have to mock the `Auth.currentSession()` and when the function is done I just use a state `setPanel` which just renders another JSX on the page

### Reproduction steps

The Jest test:

```
test("login page renders", () => {
  render(
    <Provider store={store}>
      <Login redirect="" from="" />
    </Provider>
  );
});
```

On `yarn test` the error message is triggered

```
    [ERROR] 37:32.902 AuthError - 
                Error: Amplify has not been configured correctly. 
                The configuration object is missing required auth properties.
```

### Code Snippet

```javascript
// Put your code below this line.

I think it could be mocked with a snippet like this


```
  const spy = jest.spyOn(Auth, "currentSession").mockReturnValue({
    getAccessToken: () => ({
      getJwtToken: () => "Secret-Token",
    }),
  });
```

But in my case I don't retrieve anything from the `.currentSession()` object, but just set a new state so I really don't know how to mock that and find no examples on internet

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

I don't have any for a reason

### Manual configuration

const USER_POOL_ID = process.env.REACT_APP_USER_POOL_ID;
const USER_POOL_WEB_CLIENT_ID = process.env.REACT_APP_USER_POOL_WEB_CLIENT_ID;

export default {
  Auth: {
    // REQUIRED only for Federated Authentication - Amazon Cognito Identity Pool ID
    // identityPoolId: '',
    identityPoolId: "",

    // REQUIRED - Amazon Cognito Region
    region: "eu-west-1",

    // OPTIONAL - Amazon Cognito Federated Identity Pool Region
    // Required only if it's different from Amazon Cognito Region
    // identityPoolRegion: 'eu-west-2',

    // OPTIONAL - Amazon Cognito User Pool ID
    userPoolId: USER_POOL_ID,

    // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
    userPoolWebClientId: USER_POOL_WEB_CLIENT_ID,

    // OPTIONAL - Enforce user authentication prior to accessing AWS resources or not
    mandatorySignIn: false,
  },
  Storage: {
    AWSS3: {
      bucket: "", // REQUIRED -  Amazon S3 bucket
      region: "eu-west-1", // OPTIONAL -  Amazon service region
    },
  },
};

**Comment by jgtorrejon** [comment]
Hi @lindsaycode05, did you find a solution for this ?

**Comment by lindsaycode05** [comment]
@jgtorrejon no lil bro, jus use chatgpt
but i remember i never fixed it, and i jus hate testing anyway
