### ISSUE TITLE
navigator.userAgent in CognitoUser.js is raising a Chrome Audit notification

### ISSUE THREAD

**Issue by jrobbins-LiveData** [aws-amplify/amplify-js#9957]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Not applicable

### Amplify APIs

Not applicable

### Environment information

<details>

```
# Put output below this line
  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 5.15 GB / 31.73 GB
  Binaries:
    Node: 16.6.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.30)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    cdk-dia: ^0.6.1 => 0.6.1
  npmGlobalPackages:
    @aws-amplify/cli: 7.6.19
    @mhlabs/cfn-diagram: 1.1.33
    @openapitools/openapi-generator-cli: 2.5.1
    aws-cdk: 2.26.0
    npm: 8.5.3
    python: 0.0.4
    serve: 13.0.2
    yarn: 1.22.18

```

</details>

### Describe the bug

https://github.com/aws-amplify/amplify-js/blob/1b188626afcc7f0f755ba449534236a38260e692/packages/amazon-cognito-identity-js/src/CognitoUser.js#L62 triggers `Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform` from Chrome.

### Expected behavior

Following Chrome's suggestion "To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData." should result in removing this flagged "Audit Issue", reducing concerns from security reviews and audits about `amazon-cognito-identity.js`.

### Reproduction steps

Any web app using `amazon-cognito-identity.js` should exhibit the Audit Issue.

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional information and screenshots

While `amazon-cognito-identity.js`'s use of `navigator.userAgent` in `CognitoUser.js` appears safe with respect to the announcing browser "reduction" (https://www.chromium.org/updates/ua-reduction/#reduced-navigatoruseragent-values), such Audit Issues cause concern for those of us using Cognito in secure environments with apps subject to security reviews and audits.  Rather than having to give a lengthy explanation why this particular Audit Issue isn't really a concern, it is much much easier to not have to explain it to begin with!  

There is hopefully an alternative way for the code to determine the `DeviceName` rather than using this property.

**Comment by chrisbonifacio** [comment]
Hi @jrobbins-LiveData 👋 thank you for raising this issue.

We were able to consistently reproduce the issue as you mentioned and the team will be looking into how it can be addressed within our library. We've noted the mention of a User Agent Client Hints API, which according to Chromium, will help to solve the problems of browser fingerprinting and complex string parsing.

**Comment by jrobbins-LiveData** [comment]
Hi @chrisbonifacio.  I worry about the apparent lack of cross-browser support for that API, at least as listed [here](https://developer.mozilla.org/en-US/docs/Web/API/User-Agent_Client_Hints_API#browser_compatibility).  But if you restrict its use to only when running on Chrome, that would work.  (Sorry if that is obvious!)

**Comment by chrisbonifacio** [comment]
@jrobbins-LiveData that's a good point. We could make it backwards compatible until browser support is better by checking for `navigator.userAgentData` first, and if not found, fallback to `navigator.userAgent`.

```js
if (navigator.userAgentData) {
  // use new hints
} else {
  // fall back to user-agent string
}
```

**Comment by nickarocho** [comment]
I'm also able to consistently reproduce the issue with a super simple implementation of `amazon-cognito-identity-js` in a React app.

I'll begin looking into solutions and will keep you updated along the way. Thanks for pointing this out, @jrobbins-LiveData!

![Screen Shot 2022-06-16 at 3 11 26 PM](https://user-images.githubusercontent.com/16296496/174185431-7357d5f5-b027-486c-a4ee-3b0a40646ba5.png)

**Comment by nadetastic** [comment]
With the release of the latest major version of Amplify (aws-amplify@>6), this issue should now be resolved! Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.
