### ISSUE TITLE
TypeError: undefined is not an object (evaluating 's.headers')

### ISSUE THREAD

**Issue by ldgarcia** [aws-amplify/amplify-js#996]
_Do you want to request a feature or report a bug?_

Possible bug

_What is the current behavior?_ 

`TypeError: undefined is not an object (evaluating 's.headers')`
Please see: https://sentry.io/share/issue/bc98bb1121614f6baaf8d04e47b319f6/ for the stack trace.

_If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than AWS Amplify._

We got this on an error report. Haven't got the chance to reproduce it.

_What is the expected behavior?_
N/A

_Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?_

```
"amazon-cognito-identity-js": "^2.0.3",
"aws-amplify": "^0.2.14",
"aws-amplify-react-native": "^0.2.7",
```

This is the first report we've got for this issue.

_You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app._

**Comment by jordanranz** [comment]
Hello @ldgarcia,

Are you still experiencing this issue? If so, have you tried upgrade to latest version of aws-amplify?

**Comment by ldgarcia** [comment]
Hi @jordanranz. Yes, we've received ~14 Sentry events with this issue. However, we haven't upgraded to the latest version of aws-amplify yet.

**Comment by jordanranz** [comment]
@powerful23 has merged a fix for this issue. Going to close this. Please reopen if you have any related questions or concerns.
