### ISSUE TITLE
FIS_AUTH_ERROR

### ISSUE THREAD

**Issue by Oriole-Alex** [aws-amplify/amplify-js#9967]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Push Notifications

### Amplify Categories

auth, storage, function, api, analytics, hosting, notifications

### Environment information

<details>

```
# Put output below this line
 System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 10.50 GB / 31.95 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.10.0 - C:\React Native\FairArtFair\node_modules\.bin\npm.CMD
  Browsers:
    Chrome: 102.0.5005.63
    Edge: Spartan (44.22000.120.0), Chromium (98.0.1108.50)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @aws-amplify/pushnotification: ^4.3.21 => 4.3.21
    @babel/core: ^7.12.9 => 7.18.0
    @babel/runtime: ^7.12.5 => 7.18.0
    @flyerhq/react-native-chat-ui: ^1.4.3 => 1.4.3
    @react-native-async-storage/async-storage: ^1.17.5 => 1.17.5
    @react-native-community/eslint-config: ^2.0.0 => 2.0.0
    @react-native-community/netinfo: ^8.3.0 => 8.3.0
    @react-native-picker/picker: ^2.4.1 => 2.4.1
    @react-navigation/drawer: ^6.4.1 => 6.4.1
    @react-navigation/native: ^6.0.10 => 6.0.10
    @react-navigation/stack: ^6.2.1 => 6.2.1
    @react-spring/native: ^9.4.5 => 9.4.5
    HelloWorld:  0.0.1
    amazon-cognito-identity-js: ^5.2.9 => 5.2.9
    aws-amplify: ^4.3.24 => 4.3.24
    aws-amplify-react-native: ^6.0.4 => 6.0.4
    axios: ^0.27.2 => 0.27.2 (0.21.4)
    babel-jest: ^26.6.3 => 26.6.3
    eslint: ^7.32.0 => 7.32.0
    hermes-inspector-msggen:  1.0.0
    jest: ^26.6.3 => 26.6.3
    jwt-decode: ^3.1.2 => 3.1.2
    lodash: ^4.17.21 => 4.17.21
    metro-react-native-babel-preset: ^0.67.0 => 0.67.0
    moti: ^0.18.0 => 0.18.0
    npm: ^8.9.0 => 8.10.0
    react: 17.0.2 => 17.0.2
    react-content-loader: ^6.2.0 => 6.2.0
    react-content-loader/native:  undefined ()
    react-native: 0.68.2 => 0.68.2
    react-native-aws3: ^0.0.9 => 0.0.9
    react-native-fs: ^2.20.0 => 2.20.0
    react-native-gesture-handler: ^2.4.2 => 2.4.2
    react-native-get-random-values: ^1.8.0 => 1.8.0
    react-native-html-to-pdf: ^0.12.0 => 0.12.0
    react-native-iaphub: ^7.0.6 => 7.0.6
    react-native-image-crop-picker: ^0.37.3 => 0.37.3
    react-native-maps: ^0.31.1 => 0.31.1
    react-native-modal: ^13.0.1 => 13.0.1
    react-native-paper: ^4.12.1 => 4.12.1
    react-native-paper-dates: ^0.8.7 => 0.8.7
    react-native-permissions: ^3.3.1 => 3.3.1
    react-native-reanimated: ^2.8.0 => 2.8.0
    react-native-safe-area-context: ^4.2.5 => 4.2.5
    react-native-screens: ^3.13.1 => 3.13.1
    react-native-share: ^7.4.1 => 7.4.1
    react-native-simple-toast: ^1.1.3 => 1.1.3
    react-native-svg: ^12.3.0 => 12.3.0
    react-native-svg-transformer: ^1.0.0 => 1.0.0
    react-native-vector-icons: ^9.1.0 => 9.1.0
    react-native-video: ^5.2.0 => 5.2.0
    react-test-renderer: 17.0.2 => 17.0.2
    rn-fetch-blob: ^0.12.0 => 0.12.0
    use-debounce: ^8.0.1 => 8.0.1
    uuid: ^8.3.2 => 8.3.2 (3.4.0, 3.3.2, 7.0.3)
  npmGlobalPackages:
    @aws-amplify/cli: 8.0.1
    vercel: 24.1.0

```

</details>

### Describe the bug

Setting up Amplify Push Notifications on android. Completed all steps as per documentation (https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/js/#setup-for-android) however launching android build, it successfully builds but throws the following error on launch:

"[ERROR] 03.28.361 Notification - Error getting the token from Firebase service java.util.concurrent.ExecutionException: java.io.IOException: FIS_AUTH_ERROR"

An issue that could be related, I'm not sure, but I'm using (inside gradle-wrapper.properties) distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-all.zip rather than 6.3 as per the documentation. This is because dropping the version down caused the app to fail to build with a whole number of errors, but leaving it at 7.3.3 allows it to successfully build. Is this an issue, do I absolutely need to get version 6.3 working instead?

Furthermore, I assumed the issue was related to the google-services.json file in the Android\app directory however after checking the package name and sha-1 value is absolutely correct on Firebase, and redownloading the file, that didn't resolve the issue.

### Expected behavior

The app should be correctly authorised with Firebase.

### Reproduction steps

1. Complete all the steps for android set up here - https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/js/
2. run npx react-native run-android

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Mobile Device

Pixel 4

### Mobile Operating System

Android 12

### Additional information and screenshots

![Screenshot_20220607-101551](https://user-images.githubusercontent.com/45561476/172344151-f365f943-83b3-4fdb-9a4e-e91533d68bd3.png)

**Comment by tannerabread** [comment]
Hi @Oriole-Alex, are you still running into this issue? I just built a new project following the docs, and while I had some difficulties that I will be clearing up in the docs, I didn't get this error when launching the app.

I left the gradle-wrapper.properties alone to whatever they were by default when I built the project.

Outside of the Amplify-specific config/code, the only code I changed after a new react-native project was:
```js
// android/app/build.gradle

// add at the top of the file
apply plugin: "com.google.gms.google-services"

// add in dependencies
implementation "com.google.firebase:firebase-core:15.0.2"
implementation "com.google.firebase:firebase-messaging:15.0.2"
```

```js
// android/build.gradle

// in the buildscript add
...
classpath("com.google.gms:google-services:4.3.3")
```

Another note is if you try to build on Android 12, you have to add `android:exported="false"` to both of the service tags in `AndroidManifest.xml` for Step 9

**Comment by tannerabread** [comment]
@Oriole-Alex I have updated the documentation for proper setup on android for Push Notifications per docs [PR#4939](https://github.com/aws-amplify/docs/pull/4939)

It should be [live here](https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/react-native/#setup-for-android) soon. Can you retry following the steps that exist now and let me know if it solves your issue? I never got the FIS_AUTH_ERROR when I was running into errors trying to fix the documentation so want to make sure your issue isn't stemming from somewhere else.

**Comment by tannerabread** [comment]
I'm going to close this as I believe the above should solve your issue, but please comment if it does not and I will reopen to assist in the other error you were seeing.

Thank you!
