### ISSUE TITLE
Auth does not return `attributes` for Federated uesrs

### ISSUE THREAD

**Issue by m98** [aws-amplify/amplify-js#9972]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 12.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 97.51 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    npm: 8.1.4 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 91.0.2
    Safari: 15.4
  npmPackages:
    aws-sdk: ^2.569.0 => 2.1067.0 
  npmGlobalPackages:
    @angular/cli: 13.3.4
    @aws-amplify/cli: 8.1.0
    corepack: 0.10.0
    eslint: 8.14.0
    nodemon: 2.0.15
    npm: 8.1.4

```

</details>

### Describe the bug

When signing in with social login (Federated sign-in), the user that I receive from `Auth` (for example `Auth.currentAuthenticatedUser()`, or `Hub.listen('auth')`)  does not have `attributes`. 

### Expected behavior

Users regardless of their authentication type or flow should have `attributes` and other common data.

### Reproduction steps

1. Open a user pool with supported federated login
2. Sign in using Google
3. Go to the user pool, and manually set some attributes for the user (picture, name, phone number, ...)
4. check the user that is returned from the `Auth` 
5. It does not contain `attributes` 

### Code Snippet

```javascript
// Put your code below this line.
    Auth.currentAuthenticatedUser()
      .then(currentUser => {
        console.log('User:', currentUser) //---> This should contain `attributes` for federated user. But does not
      })
      .catch((e) => console.error(e))
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

```javascript
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-xxxx",
    "aws_user_pools_web_client_id": "xxxx",
    "oauth": {
        "domain": "xxx",
        "scope": [
            "email",
            "openid",
            "phone",
            "profile"
        ],
        "redirectSignIn": "xxxx",
        "redirectSignOut": "xxxx",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS"
        ]
    },
    "aws_cognito_verification_mechanisms": []
};


export default awsmobile;
```

### Additional information and screenshots

I tried signing in with a phone number, and I could get access to attributes. The problem is only with Federated signin, and I could see other people have this issue on StackOverflow and other forums.

This might not necessarily be a bug, but at least it adds inconsistency in the  `Auth`.

We found a solution that if we add the following into `scope`, `attributes` will be returned by `Auth` 

```javascript
 "aws.cognito.signin.user.admin"
```

But the issue with the above scope is that the user can get granted access to some actions such as VerifyUserAttribute which we don't want. 
![image](https://user-images.githubusercontent.com/7496103/172649487-146687a7-1e69-4086-80db-1423732fae00.png) ([source](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-app-idp-settings.html))
Maybe I'm confused about what the documentation is saying. But what I'm understanding is that a user pool configured with this scope might allow users to do some extra actions. For example, a user can verify their email address or phone number. Is my understanding correct?

By the way, the Cognito or Amplify documentation did not mention anything about this limitation of the Federated logins. Could be nice to document this!

**Comment by chrisbonifacio** [comment]
>Maybe I'm confused about what the documentation is saying. But what I'm understanding is that a user pool configured with this scope might allow users to do some extra actions. For example, a user can verify their email address or phone number. Is my understanding correct?

Hi @m98 👋 thanks for raising this issue. Your understanding is correct, this scope will grant federated users access to the same User Pool API operations that require an access token, and one of those operations includes `GetUser` which includes the attributes and metadata for the user. Otherwise, I think you would have to obtain the attributes from the ID token instead.

**Comment by tannerabread** [comment]
Closing this as the question has been answered. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with more information so we can re-open this issue and be better able to assist you.

Thank you!
