### ISSUE TITLE
SSO (federatedSignIn) flow not working in Safari -> "No current user"

### ISSUE THREAD

**Issue by its-wufu** [aws-amplify/amplify-js#9977]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React Native

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 12.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 45.71 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 2022.01.17.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 102.0.5005.61
    Edge: 102.0.1245.33
    Firefox: 88.0
    Safari: 15.1
  npmPackages:
    @babel/core: ^7.16.12 => 7.16.12 (7.9.0)
    @microsoft/teams-js: ^1.10.0 => 1.11.0 
    @react-native-async-storage/async-storage: ~1.15.0 => 1.15.17 
    @react-native-community/masked-view: 0.1.10 => 0.1.10 
    @react-native-community/netinfo: 6.0.2 => 6.0.2 
    @react-navigation/native: ^5.9.0 => 5.9.8 
    @react-navigation/stack: ^5.13.0 => 5.14.9 
    @testing-library/jest-native: ^3.0.2 => 3.4.3 
    @testing-library/react-native: ^9.0.0 => 9.0.0 
    @types/iban: ^0.0.32 => 0.0.32 
    @types/jest: ^27.0.2 => 27.4.0 
    @types/react: ~17.0.21 => 17.0.38 (16.14.21)
    @types/react-dom: ~17.0.9 => 17.0.11 
    @types/react-native: ~0.64.12 => 0.64.23 (0.66.15)
    @types/react-native-modalbox: ^1.4.8 => 1.4.10 
    @types/styled-components: 4.4.2 => 4.4.2 
    HelloWorld:  0.0.1 
    amazon-cognito-identity-js: ^5.2.4 => 5.2.4 (4.6.3)
    aws-amplify: 3.4.3 => 3.4.3 
    country-codes-list: 1.6.8 => 1.6.8 
    date-time-format-timezone: ^1.0.22 => 1.0.22 
    dayjs: ^1.10.7 => 1.10.7 
    eslint: 7.32.0 => 7.32.0 
    eslint-config-react-native-wcandillon: ^3.7.2 => 3.7.2 
    expo: ^43.0.0 => 43.0.5 
    expo-brightness: ~10.0.3 => 10.0.3 
    expo-checkbox: ~2.0.0 => 2.0.0 
    expo-cli: ^4.12.12 => 4.13.0 
    expo-constants: ~12.1.3 => 12.1.3 
    expo-font: ~10.0.3 => 10.0.4 
    expo-keep-awake: ~10.0.0 => 10.0.1 
    expo-linking: ~2.4.2 => 2.4.2 
    expo-localization: ~11.0.0 => 11.0.0 
    expo-notifications: ~0.13.3 => 0.13.3 
    expo-splash-screen: ~0.13.5 => 0.13.5 
    expo-status-bar: ~1.1.0 => 1.1.0 
    expo-updates: ~0.10.15 => 0.10.15 
    expo-web-browser: ~10.0.3 => 10.0.3 
    formik: ^2.2.9 => 2.2.9 
    hermes-inspector-msggen:  1.0.0 
    i18next: 19.7.0 => 19.7.0 
    iban: 0.0.12 => 0.0.12 
    jest: 26 => 26.6.3 
    jest-date-mock: ^1.0.8 => 1.0.8 
    jest-expo: ^43.0.0 => 43.0.1 
    jest-extended: ^1.1.0 => 1.2.0 
    jest-junit: ^13.0.0 => 13.0.0 
    mockdate: ^3.0.5 => 3.0.5 
    react: 17.0.1 => 17.0.1 
    react-dom: 17.0.1 => 17.0.1 
    react-hooks-testing-library: ^0.6.0 => 0.6.0 
    react-i18next: 11.7.3 => 11.7.3 
    react-native: 0.64.3 => 0.64.3 
    react-native-gesture-handler: ~1.10.2 => 1.10.3 
    react-native-image-zoom-viewer: 3.0.1 => 3.0.1 
    react-native-qrcode-svg: 6.0.6 => 6.0.6 
    react-native-reanimated: ~2.2.0 => 2.2.4 
    react-native-safe-area-context: 3.3.2 => 3.3.2 
    react-native-screens: ~3.8.0 => 3.8.0 
    react-native-svg: 12.1.1 => 12.1.1 
    react-native-web: 0.17.1 => 0.17.1 
    react-query: 2.25.2 => 2.25.2 
    standard-version: ^7.1.0 => 7.1.0 
    standard-version-expo: ^1.0.3 => 1.0.3 
    styled-components: 4.4.1 => 4.4.1 
    styled-components/macro:  undefined ()
    styled-components/native:  undefined ()
    styled-components/primitives:  undefined ()
    typescript: ~4.3.5 => 4.3.5 
  npmGlobalPackages:
    appium-doctor: 1.13.1
    appium: 1.16.0
    bit-bin: 14.8.8
    expo-cli: 5.0.3
    n: 6.1.3
    npm: 6.13.4
    react-native-cli: 2.0.1
    sharp-cli: 1.15.0

```

</details>

### Describe the bug

We have a React Native Expo App and the SSO flow works great in all browsers but not in Safari. What I see after using the 

```
await Auth.federatedSignIn({
      customProvider,
});
```

is that the Safari Browser opens the Popup -> I can login with Microsoft -> Signin finishes and the Popup closes -> Safari then seems to delete my local storage information and my App return me "No current user", as there is no token stored.

### Expected behavior

Then the popup closes the App runs

```
Auth.currentSession()
```
and should return the CognitoUserSession to me but it doesn't. (Only in Safari!)

### Reproduction steps

It's kind of a big project so it's not reasonable to have a working code sandbox copy or similar.
We have connected our cognito user to the Microsoft Azure user that is configured for this custom provider. For now Microsoft is our only provider, so I cannot be sure if this only happens for MS.

Using the `Auth.currentSession()` directly in the urlOpener reveals to me, that I am actually logged in and I can also see for a split second that the local storage gets some data in safari but gets deleted. So even if I use the info that I am logged in and let the user use the app, I cannot perform any api call, because the token is deleted again.

If I can provide more information, please let me know!

Thank you so much!

### Code Snippet

For the SSO login we simply call this function:

```javascript
  const executeSSOLogin = async () => {
    setStatus('idle');
    setError(undefined);
    setIsLoading(true);
    try {
      const customProvider = await AsyncStorage.getItem('provider');
      if (customProvider) {
        await Auth.federatedSignIn({
          customProvider,
        });
      }
    } catch (e) {
      setError(ERRORS.GENERIC_ERROR);
      setStatus('error');
    } finally {
      setIsLoading(false);
    }
  };
```
For Web we are using this to update our config:

```javascript
    awsConfig.userPoolWebClientId = USER_POOL_CLIENT_ID_WEB;
    awsConfig.oauth.redirectSignIn = `${window.location.origin}`; // WEB
    awsConfig.oauth.redirectSignOut = `${window.location.origin}/signout`;
    awsConfig.oauth.urlOpener = urlOpener;
```

```javascript
async function urlOpener(url: string, redirectUrl: string) {
  const { url: newUrl } = await WebBrowser.openAuthSessionAsync(
    url,
    redirectUrl
  );

  if (!newUrl) {
    Platform.OS === 'ios' && WebBrowser.dismissBrowser();
    return;
  }

  // iOS
  if (Platform.OS === 'ios') {
    WebBrowser.dismissBrowser();
    return Linking.openURL(newUrl);
  }

  //WEB
  if (Platform.OS === 'web' && !url.includes('signout')) {
    Linking.openURL(newUrl);
  }
}
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Manual configuration

Depending on the env and device we fill out the config with a function like I showed above in the code snippet.

```javascript
const awsConfig: ConfigOptions = {
  identityPoolId: IDENTITY_POOL_ID,
  userPoolId: USER_POOL_ID,
  region: REGION,
  userPoolWebClientId: '',
  mandatorySignIn: true,
  oauth: {
    domain: `${OAUTH_DOMAIN}.auth.eu-central-1.amazoncognito.com`,
    scope: ['email', 'openid', 'aws.cognito.signin.user.admin', 'profile'],
    redirectSignIn: '',
    redirectSignOut: '',
    responseType: 'code',
  },
  endpoints: [...],
  bucket: BUCKET,
};
```

### Additional information and screenshots

What I tried so far was to research for known issues and try to apply known solutions like
- changing Safaris privacy settings like: Turn off "Prevent cross-site tracking" or "Block all cookies"
- Using cookies instead of local storage with 
```
cookieStorage: {
      domain: "localhost",
      path: "/",
      expires: 365,
      secure: false
    },
```
and similar options

But nothing seems to change anything. 
To me this looks like an issue with the setting of the storage/cookies but I am stuck now.

I'd appreciate any idea and input at this point. 

Thank you so much!

**Comment by tannerabread** [comment]
Hi @its-wufu, do I understand correctly that you were using a React Native Expo app but as web and not on a mobile device?

Also as it has been a while, did you get this resolved?

**Comment by tannerabread** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and are in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
