### ISSUE TITLE
Example of using current authenticated user's credentials with aws-sdk clients

### ISSUE THREAD

**Issue by pjarts** [aws-amplify/amplify-js#998]
Do you want to request a feature or report a bug?
Documentation improvement

Could you provide an example of how to keep the IAM credentials for aws-sdk clients in sync with the current authenticated user's credentials? I need to make admin requests to the user pool using the CognitoIdentityServiceProvider client from the 'aws-sdk' pacakge.

**Comment by powerful23** [comment]
@pjarts you can use `Auth.currentCredentials()` to get the credentials and use it to initialized the `CognitoIdentityServiceProvider`
